### ISSUE TITLE
liferea can't play audio

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#39587]
## Issue description

The RSS Reader has a feature to play podcasts, but it don't work.

### Steps to reproduce

1. start liferea
2. open "EscapePod" feed from examples
3. try to play any podcast

https://youtu.be/BisT8v6bzJk

console output:
```
Error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) gsturidecodebin.c(998): no_more_pads_full (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin7:
no suitable plugins found:
gstdecodebin2.c(4600): gst_decode_bin_expose (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin7/GstDecodeBin:decodebin7:
no suitable plugins found:
Missing decoder: MPEG-1 Layer 3 (MP3) (audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true)

```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.35, NixOS, 18.03.132155.b50443b5c4a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
MP3 codecs were moved from `gst-plugins-bad` to `gst-plugins-good`. All music players will need to be adjusted.

**Comment by matthewbauer** [comment]
Maybe we need to set https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/clementine/default.nix#L85 ?

**Comment by jtojnar** [comment]
`wrapGAppsHook` will do that automatically.

**Comment by jtojnar** [comment]
I can play EscapePod on 6c064e6b without any error.

**Comment by jtojnar** [comment]
Right, the mp3 codec was actually previously in ugly, which liferea package does not depend on, so it did not have MP3 support before https://github.com/NixOS/nixpkgs/pull/38149.

**Comment by jtojnar** [comment]
Closing, since it works in `unstable`. If someone wants this in `release`, I suggest adding `gst-plugins-ugly` dependency.
