### ISSUE TITLE
vivaldi-ffmpeg-codecs build fails

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#39590]
## Issue description
I try to install vivaldi-ffmpeg-codecs, it tries to build it —
```
In file included from ../../buildtools/third_party/libc++/trunk/include/ios:216:0,
                 from ../../buildtools/third_party/libc++/trunk/include/ostream:138,
                 from ../../buildtools/third_party/libc++/trunk/include/istream:163,
                 from ../../buildtools/third_party/libc++/trunk/include/random:1646,
                 from ../../buildtools/third_party/libc++/trunk/src/algorithm.cpp:11:
../../buildtools/third_party/libc++/trunk/include/__locale:39:11: fatal error: xlocale.h: No such file or directory
 # include <xlocale.h>
           ^~~~~~~~~~~
compilation terminated.
```
### Steps to reproduce
Just try to install vivaldi-ffmpeg-codecs.
## Technical details
```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.34, NixOS, 18.03.132021.c0c5571ec1a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.132155.b50443b5c4a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```
there was the same thing in previous 18.03.

**Comment by Anton-Latukha** [comment]
I found that `xlocale.h` was removed in `glibc 2.26+`.
Here it is in the [changelog](https://sourceware.org/ml/libc-alpha/2017-08/msg00010.html):
> * The nonstandard header <xlocale.h> has been removed.  Most programs should
>   use <locale.h> instead.  If you have a specific need for the definition of
>   locale_t with no other declarations, please contact
>   libc-alpha@sourceware.org and explain.
> 

Here was a fix for `libc++`: https://github.com/llvm-mirror/libcxx/commit/6e02e89f65ca1ca1d6ce30fbc557563164dd327e

And the helpful thread: https://www.linuxquestions.org/questions/slackware-14/no-luck-with-libc-on-current-xlocale-h-missing-4175612648/

**Comment by Anton-Latukha** [comment]
I tried bluntly update the chromium source where codecs stored. But it failed:
```
source root is chromium-65.0.3325.18
setting SOURCE_DATE_EPOCH to timestamp 1516911185 of file chromium-65.0.3325.18/skia/ext/skia_commit_hash.h
patching sources
applying patch /nix/store/wkc502916v4spj8rlsfmfyi507wci0mw-chromium-gn-bootstrap-r14.patch
patching file tools/gn/bootstrap/bootstrap.py
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
patch unexpectedly ends in middle of line
2 out of 2 hunks ignored -- saving rejects to file tools/gn/bootstrap/bootstrap.py.rej
builder for '/nix/store/kpf5424vly9yxhfkqibkjikg3isz64z2-vivaldi-ffmpeg-codecs-65.0.3325.18.drv' failed with exit code 1
```

**Comment by Anton-Latukha** [comment]
That patch is marked `WIP`.

**Comment by Anton-Latukha** [comment]
Let's call author: @lluchs

**Comment by lluchs** [comment]
>I tried bluntly update the chromium source where codecs stored.

This is the right approach, but you'll also have to remove the old patches and check whether you need any newer [patches from the main chromium derivation](https://github.com/NixOS/nixpkgs/blob/6078f01969e8e704f44965a97730f95634887ca2/pkgs/applications/networking/browsers/chromium/common.nix#L140-L161). The patches used by the [AUR package](https://aur.archlinux.org/packages/vivaldi-ffmpeg-codecs/) are usually a good starting point.

**Comment by matthewbauer** [comment]
So unless I'm mistaken, shouldn't we just build chromium & provide a vivaldi output? The chromium build is huge & we don't want Hydra to have to do it multiple times. What's the intended use of ffmpeg-vivaldi-codecs?

I think we can disable libcxx building with ```use_custom_libcxx=false``` in args, though.

**Comment by comonoid** [comment]
As i can see, there are some license issues (?) with something like h264.
So we build in on "client" side from sources (probably it's x264)... I don't know exactly...

**Comment by lluchs** [comment]
Providing a Vivaldi output from chromium (as @matthewbauer suggests) is difficult because chromium moves at a different speed than Vivaldi, so the resulting library may not fit properly. I don't know how often this happens, but it looks like upstream ffmpeg changes their ABI fairly often.

The build actually isn't that much of an issue. The only difficulty is having to download and extract the full chromium tarball, the compile times are short as we only need `libffmpeg.so`.

>What's the intended use of ffmpeg-vivaldi-codecs?

Vivaldi (the company) cannot distribute certain codecs in ffmpeg in their packages, so we have to compile that separately.
