### ISSUE TITLE
Steam doesn't build

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#39607]
## Issue description

Tried to make a system upgrade, got this:

```unpacking source archive /nix/store/07dxmky7f1rr66wnzq2z44zdwvirbx1r-glslang-714e58b2fc5a45714596e6aa2f6ac8f64260365c-src
cp: setting permissions for 'glslang-714e58b2fc5a45714596e6aa2f6ac8f64260365c-src': Operation not permitted
do not know how to unpack source archive /nix/store/07dxmky7f1rr66wnzq2z44zdwvirbx1r-glslang-714e58b2fc5a45714596e6aa2f6ac8f64260365c-src
builder for ‘/nix/store/mbmmdibqv3c4jgpy5b7rydzcsin6np68-glslang-git-2017-03-29.drv’ failed with exit code 1
building path(s) ‘/nix/store/34zd6l4a228kk5hsggr9zy1a7f94ncs1-gtk2-engines-murrine.deb’
cannot build derivation ‘/nix/store/1416c4lpjlifczbghmrik7j50p6yd8j1-vulkan-loader-1.0.42.2.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/aw221q1f651gsj0j5g04s85cxzamf2yd-xkb-validated’
cannot build derivation ‘/nix/store/z2pr061p5n18p04wgvifkh3vl2bq8va2-steam-runtime-wrapped.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/a1pp1x7m0vyzqwcg8cd80ms44bjh3rdz-steam-usr-multi.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/kwrcx5g3rfsm1np2aa9r069frpbjzig6-idea-ultimate-2017.3.3’
cannot build derivation ‘/nix/store/hixq91iq6f27fyfswsc4kk7l1wwv4lan-steam-fhs.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ar9rz16zc0l33k59wz7jpqf1h7y3qg6a-steam-init.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6hflw3kyz756njm3ygmllwb6b5ppp2r2-steam.drv’: 1 dependencies couldn't be built
```

Obviously, upgrade can't be completed.

### Steps to reproduce

- have `steam` in `environment.systemPackages`.
- run `nixos-rebuild --upgrade switch`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.83, NixOS, 17.09.3047.8bce347f02f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3243.bca2ee28db4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
This looks like the offending line: https://github.com/NixOS/nixpkgs/blob/1ba44cc9573266cd1bef4383accddab5aac6a818/pkgs/development/compilers/glslang/default.nix#L20

**Comment by matthewbauer** [comment]
Actually this looks like unrelated to glslang.

Works on master:

https://hydra.nixos.org/job/nixpkgs/trunk/glslang.x86_64-linux
