### ISSUE TITLE
PyCharm Professional doesn't build

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#39606]
## Issue description

Tried to make a system upgrade, got this:

```chmod: changing permissions of 'pycharm-2017.3.3': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/bin': Operation not permitted
< many many lines here >
chmod: changing permissions of 'pycharm-2017.3.3/jre64/lib/images/cursors': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/jre64/lib/management': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/jre64/lib/security': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/jre64/lib/security/policy': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/jre64/lib/security/policy/limited': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/jre64/lib/security/policy/unlimited': Operation not permitted
chmod: changing permissions of 'pycharm-2017.3.3/jre64/bin': Operation not permitted
```

Obviously, upgrade can't be completed.

### Steps to reproduce

- have `jetbrains.pycharm-professional` in `environment.systemPackages`.
- run `nixos-rebuild --upgrade switch`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.83, NixOS, 17.09.3047.8bce347f02f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3243.bca2ee28db4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
This looks like a disk error. Can you try removing pycharm-professional, updating, then adding it back in?

**Comment by chekoopa** [comment]
Unfortunately, I can't reproduce this error anymore. Looks, like it was resolved [after btrfs subvolumes removal](https://github.com/NixOS/nixpkgs/issues/39730#issuecomment-385645393).
