### ISSUE TITLE
Create NixOS module for spice-gtk usb redirection

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#39618]
## Issue description

To use the usb redirection features of `virt-manager` or`virt-viewer` in NixOS, the user currently has to put `spice-gtk` into `environment.SystemPackages`, create a setuid wrapper, and activate a `polkit` action. This is neither obvious nor user-friendly, and currently undocumented except for some code comments.

Creating a little NixOS module to hide these steps behind a single config option will make this much easier to use. 

I plan to implement this for 18.09 but anyone feel free to do it earlier...

**Comment by jtojnar** [comment]
Creating setuid wrapper should not be needed with polkit. You just need to enable the polkit policy, which you can do by adding the polkit file to the `/var/run/current-system/sw/share/polkit-1/actions`, which is co-incidentally a side-effect of adding `spice-gtk` to `environment.systemPackages`. We could create `services.polkit.enabledActions` as an alias of `environment.systemPackages` for semantically more correct option.

**Comment by xeji** [comment]
If I remember correctly, in `spice-gtk` they have a helper program that needs to run setuid root to set device ACLs but internally uses polkit to authenticate the user's access to the usb devices. Last time I tried, both a  setuid wrapper and the polkit action were needed for this to work. And I believe upstream docs mention that somewhere. Don't really understand why they do this...

But I'll try again without wrapper when implementing the module.

**Comment by lheckemann** [comment]
I have `spice_gtk` in my systemPackages and `security.wrappers.spice-client-glib-usb-acl-helper.source = "${pkgs.spice_gtk}/bin/spice-client-glib-usb-acl-helper";` and it works for me.

**Comment by tmplt** [comment]
> I have `spice_gtk` in my systemPackages (not sure if necessary)

Just tested this fix locally: it is required.

**Comment by lheckemann** [comment]
#97826
