### ISSUE TITLE
`azure-xplat-cli` should be removed in favor of azure-cli (the python package)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#39638]
`azure-cli` is the 2.0 of Azure's CLI. 

There is a significant amount of functionality only available through it, and it's generally just always preferrable. We should package it. I hope to be able to do this, but any pointed appreciated.

(It's generally installable with `pip install --user azure-cli` but it has FFI and C dependencies in some places.)

**Comment by matthewbauer** [comment]
PRs welcome! We should probably setup an alias for azure-xplat-cli though.

**Comment by colemickens** [comment]
@matthewbauer Tracking issue for packaging `azure-cli`: https://github.com/NixOS/nixpkgs/issues/40073

I'm a bit stuck on it, but whenever it's available, I'll loop back around here and figure out how to clean up the old CLI.

**Comment by Artturin** [comment]
we don't have that package anymore
