### ISSUE TITLE
XFCE: main screen stays dark after hibernate

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#39648]
## Issue description

After i resume from hibernate, the screen of the notebook stays dark, only an attached display shows the picture. I can still move the mouse to the dark screen...

![screenshot_2018-04-19_17-08-16](https://user-images.githubusercontent.com/91113/39395747-baa52d60-4ae2-11e8-948b-a11005121a05.png)

### Steps to reproduce

1. hibernate
2. resume
3. ???

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.36, NixOS, 18.03.132155.b50443b5c4a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by symphorien** [comment]
I have experienced a similar problem; the workaround I found iirc is to uncheck "lock screen when system is going to sleep" in the settings of `xfce4-power-manager`. Somehow `loginctl` or something else still locks the screen, but in a non-buggy way.

**Comment by davidak** [comment]
I unchecked that, but now the system freezes after boot... can't even ping it.

**Comment by symphorien** [comment]
I have also experienced black screen when resuming from hibernation and this was solved by downgrading the kernel to 4.9. Maybe we have similar hardware.

**Comment by baracoder** [comment]
Is there any chance that got fixed with a recent kernel version?

**Comment by davidak** [comment]
I don't know. I use GNOME now.

**Comment by mdedetrich** [comment]
I  am having a similar problem with KDE, I don't think its DE specific

**Comment by davidak** [comment]
I use the pantheon desktop now and don't have this issue. I also don't had it with GNOME. So it's not a general problem.

Please open a new issue if you still have this problem.

**Comment by mansoormojo** [comment]
Currently have the same issue with KDE
