### ISSUE TITLE
Idris executables do not run

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#39655]
## Issue description

```
$ idris 2_goodies.idr -o out && ./out
./out: relocation error: /nix/store/27x7pinqdsl9f3rpbm8bsszd9fhwq266-glibc-2.27/lib/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

### Steps to reproduce

I used  the following for the .idr file compiled above:

```
module Main
main: IO ()
main = pure ()

-- Need to figure out hide
-- %hide Point
-- data Point a = Point a a

data Tree a             = Leaf a | Branch (Tree a) (Tree a)

fringe                     :  Tree a -> List a
fringe (Leaf x)            =  [x]
fringe (Branch left right) =  fringe left ++ fringe right

aTree: Tree Int
aTree = Branch (Branch (Leaf 10)(Leaf (-5))) (Leaf 3)

aTreeOut: List Int
aTreeOut = fringe aTree

treePrints: IO ()
treePrints = do
  print aTreeOut
  putStrLn "hi"
```

## Technical details

Seem to have a bit of an issue right now with this:

```
$ `nix-shell -p nix-info --run "nix-info -m"`
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: -: command not found
```

**Comment by dtzWill** [comment]
Hmm, your example compiles and -- I think-- executes fine. Although there is no output.

Using the "hello world" example from [1] seems to work, and prints the expected greeting :).

I suspect various "impurities" in your environment-- such as idris finding and using toolchain bits from your system.

1) Try running from within a nix-shell (`nix-shell -p idris`)
2) Check your LD_LIBRARY_PATH
3) .. dunno.  But at least it seems to work for me at least, so there's some hope yet :).

[1] http://docs.idris-lang.org/en/latest/tutorial/starting.html

**Comment by bbarker** [comment]
@dtzWill awesome, thanks for the ideas: (1): worked. I had inspected (2) before, which had `/usr/local/nvidia/lib:/usr/local/nvidia/lib64` - this seemed reasonable, and was unavoidable afaik due to running it in an nvida cuda container, but I `unset` it and had the same result - not sure what is up with this, but I guess I can inspect the shell wrapper later to see how it helps.
