### ISSUE TITLE
liferea: settings not saved

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#39650]
## Issue description

```
[davidak@X230:~]$ liferea

(liferea:13895): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
Traceback (most recent call last):
  File "/nix/store/4plwfwvv6yfrjdlkxh3i27apa18x1cpa-liferea-1.12.2/lib/liferea/plugins/gnome-keyring.py", line 38, in do_activate
    + GnomeKeyring.result_to_message(result))
ValueError: Failed to unlock GnomeKeyring, error: A keyring with that name does not exist.
```

### Steps to reproduce

1. open program
1. change window size
2. close program
3. open program
4. has again default window size

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.36, NixOS, 18.03.132155.b50443b5c4a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
You need dconf installed for all GTK applications. There is already an issue about that https://github.com/NixOS/nixpkgs/issues/11239

The GNOME Keyring part looks like an upstream bug.

**Comment by jtojnar** [comment]
Dconf part is a question and gnome-keyring part is no longer relevant.
