### ISSUE TITLE
(nixos-install & nixos-enter) Chroot cannot resolve dns names

### ISSUE THREAD

**Issue by nlvw** [NixOS/nixpkgs#39665]
## Issue description

After installing NixOS then using nixos-enter to chroot into the installation dns does not work.  I am trying to clone down a repository but it fails because it cannot resolve github.com.

Here is a picture of the of some commands run inside the chrooted installation
<img width="435" alt="capture" src="https://user-images.githubusercontent.com/5723368/39402951-9a9012b2-4b2b-11e8-80dd-65bc51e24b7c.PNG">

[Bootstrap.sh](https://github.com/Wolfereign/nixos-configs/blob/8321bb6bbee9a1e38eabeaf81ccc920270f806c9/bootstrap.sh) being run to install and call the chrooted commands.
[Configuration.nix](https://github.com/Wolfereign/nixos-configs/blob/8321bb6bbee9a1e38eabeaf81ccc920270f806c9/machines/testing/configuration.nix) being used

### Steps to reproduce

1. Boot a vm using one of the 18.03.132155.b50443b5c4a isos (UEFI Mode).
2. Clone this [repo and tree](https://github.com/Wolfereign/nixos-configs/tree/8321bb6bbee9a1e38eabeaf81ccc920270f806c9)
3. run bootstrap.sh
4. select "test" machine (option 4) when prompted  (this is setup for hyper-v so you may need to fix the hardware-configuration.nix back to the default one generated).
5. Observer error after installation finishes

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
<img width="276" alt="capture2" src="https://user-images.githubusercontent.com/5723368/39402986-1aac6518-4b2c-11e8-80ae-f11219f6ab6d.PNG">

**Comment by lheckemann** [comment]
I'm guessing this is because nixos-enter doesn't create a resolv.conf. I think the appropriate solution would be to bind-mount that in from the host system.

As a workaround, you should be able to make it work by running `cp /etc/resolv.conf /mnt/etc/`.

**Comment by Wolfereign** [comment]
This leaves me a bit confused.  I'm using the nixos-enter after nixos-install has completed.  Does resolv.conf not get generated during the build?

**Comment by Wolfereign** [comment]
Yep no issues in the regular environment.  DNS resolution works fine, as well, once rebooted into the fresh installation.

It is just in the nixos-enter environment right after installation, before reboot, that DNS doesn't want to work.

**Comment by johnae** [comment]
I have a similar problem during install where an overlay does a curl as part of make install - fails because it can't resolve dns (in this case github.com).

**Comment by johnae** [comment]
Skipping the install of that overlay and then trying nixos-enter:

```
nixos-enter -c "curl https://github.com"
setting up /etc...
curl: (6) Could not resolve host: github.com
```

**Comment by johnae** [comment]
Trying the below does work (so clearly something isn't right about the generated resolv.conf):

```
nixos-enter -c "echo nameserver 8.8.8.8 > /etc/resolv.conf; curl https://github.com"
... lots of html output as expected ...
```

**Comment by johnae** [comment]
Finally, bind mounting the host resolv.conf readonly does allow me to to run nixos-enter:

```
mount -o bind,ro /etc/resolv.conf /mnt/etc/resolv.conf
nixos-enter -c "curl https://github.com" | head
setting up /etc...
/nix/store/zm1cn7di1zcapka1jlr9w4p714sl3jxq-openresolv-3.9.0/libexec/resolvconf/libc: line 230: /etc/resolv.conf: Read-only file system
... lots of expected html output ...
```

So now nixos-enter fails to generate the resolv.conf as it's readonly.

**Comment by johnae** [comment]
So my host resolv.conf looks like this:

```
# Generated by resolvconf
nameserver 10.0.2.3
options edns0
```

The generated resolv.conf under /mnt/etc (when not bind mounting) looks like this:

```
# Generated by resolvconf
options edns0
```

So it's missing the nameserver(s).

**Comment by johnae** [comment]
Hmm. As I am a nixos newbie it may just be that I don't fully understand the notion of fixedOutput packages. Looking through the sources for the package manager it seems the build environment will only allow networking when the output is a fixedOutputHash one. However, that does seem like it would mean the package cannot be built everywhere as the binary won't have the same hash...

**Comment by johnae** [comment]
Ok so I think I get it now. I was installing packages in an impure way I suppose as they were downloading things "behind the scene", sorry I'm a newbie still. So nixos-install is doing what it should do I think.

Still, I don't understand why `nixos-enter` generates an unusable resolv.conf as detailed above and I think that's what this issue really is about.

**Comment by Wolfereign** [comment]
The issue becomes more severe when you take into account that even if you create a correct resolv.conf it will get replaced every time nixos-enter is called.  So if you are using nixos-enter in a script it becomes a blocking issue.

**Comment by jluttine** [comment]
I have the same problem. I'm running a live USB NixOS but I have already installed NixOS on my computer. I'd like to just chroot to my already installed NixOS system and run nixos-install there but it doesn't work because network fails.

**Comment by Wolfereign** [comment]
@jluttine After you mount the installation you can just run "nixos-install --no-root-passwd" again.  It will pull the configuration from whatever is already installed in the /mnt folder and just update it.

The core root of the problem for this ticket/issue is resolve.conf being generated incorrectly.  Just waiting for nixos-enter to be fixed in this regard for the ticket to be closed.

**Comment by chkno** [comment]
still important to me.

I confirm that this is still broken as of 20.03.2102.e2bb73ce5f7

![39665-20 03 2102 e2bb73ce5f7](https://user-images.githubusercontent.com/1118859/84089394-b5052c80-a9a3-11ea-9bd0-168101f28820.png)

**Comment by EvilMav** [comment]
Still broken in 20.09

**Comment by sovelten** [comment]
`$ sudo cp /etc/resolv.conf /mnt/etc/resolv.conf` solved it for me.
The file did not get replaced when running nixos-enter.
Still far from ideal though

**Comment by WolfangAukang** [comment]
I have to be that person ("use the reactions instead of posting you also have this issue"), but this issue is from 2018.

Well, I'm having this issue with the GNOME 21.05.

**Comment by Artturin** [comment]
arch-chroot bind mounts 
https://github.com/archlinux/arch-install-scripts/blob/bb04ab435a5a89cd5e5ee821783477bc80db797f/arch-chroot.in#L51

**Comment by Artturin** [comment]
#137677

**Comment by philipwilk** [comment]
I just experienced this on unstable 25.05....

Was replacing/recovering my root drive because zfs was panicking on mount, so had to drop to a live usb, and as I was reinstalling my bootloader, this happened (dns not working, cache inaccesible, inside of nixos-enter)

`mount -o bind,ro /etc/resolv.conf /mnt/etc/resolv.conf` worked for me.

**Comment by bjornfor** [comment]
@philipwilk: It might be a good idea to create a new issue, for visibility. Linking back here is good.
