### ISSUE TITLE
`writeTextFile` fails when building for a different platform

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#39664]
I might be missing something, but on macOS:

```
$ nix-build -A removeReferencesTo '<nixpkgs>' --option system x86_64-linux
these derivations will be built:
  /nix/store/z73mwv7j43519pz55qjxnhfycxda313q-remove-references-to.drv
building '/nix/store/z73mwv7j43519pz55qjxnhfycxda313q-remove-references-to.drv'...
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: /nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: cannot execute binary file
builder for '/nix/store/z73mwv7j43519pz55qjxnhfycxda313q-remove-references-to.drv' failed with exit code 126
error: build of '/nix/store/z73mwv7j43519pz55qjxnhfycxda313q-remove-references-to.drv' failed

$ file /nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/27x7pinqdsl9f3rpbm8bsszd9fhwq266-glibc-2.27/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

`removeReferencesTo` is simply `writeScriptBin`, which is `writeTextFile`, which has `preferLocalBuild = true`, so it is not trying to build it using my remote builder. But why is it using a wrong bash?

-----------

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.6.0, macOS 10.13.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(kirelagin): `"nixpkgs-18.09pre138136.d0b24f28fa3"`
 - nixpkgs: `/Users/kirelagin/.nix-defexpr/channels/nixpkgs`

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/2ce9b9842b5e63884dfc3dea6689769e2a1ea309/pkgs/build-support/trivial-builders.nix#L257-L259 the scripts are dry run with the shell
