### ISSUE TITLE
neo4j cannot write to disk

### ISSUE THREAD

**Issue by andrewmiller1** [NixOS/nixpkgs#39690]
## Issue description

neo4j shuts down immediately on start up. I've tried both 3.3.2 and 3.3.4. I've tried both container and

### Steps to reproduce

Put the following in your configuration.nix:

```nix
{ config, lib, pkgs, ... }:
 
 with lib;
 
 { services.neo4j = {
     enable = true;
   };
   
 }
```

Command your shell: `neo4j console`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (20.55 MiB download, 204.50 MiB unpacked):
  /nix/store/1sq8mqjly01pb1nf471phgbgc71v12yy-expand-response-params
  /nix/store/5hszvi0hczzh25mmsz5rkb9qa758c10p-bash-4.4-p12-dev
  /nix/store/9bkj2zjc8jdzwgwdwb5d890hrhrk9d3g-bash-4.4-p12-dev
  /nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1
  /nix/store/bkx6rzqciq0sdn1z5liard33ffvv1n3s-bash-4.4-p12-doc
  /nix/store/cmxaqb5cbzy4jk26na842n6hy1s4yn19-binutils-wrapper-2.28.1
  /nix/store/d5ki460cwwydf93f31is95sqpcf334r4-bash-4.4-p12-info
  /nix/store/f1rp3j71id6g6zcmiafrksmw1cgydl9k-bash-4.4-p12-doc
  /nix/store/fskpf2pdlgn4gm2kay7lfbw1cmjil6s3-bash-4.4-p12-man
  /nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0
  /nix/store/l3nz0167a4xhb78ldcjns5p4dwvlm1cw-stdenv
  /nix/store/lhp5rw0dagi5mgqwr9i3x41240ba4ypz-gnumake-4.2.1
  /nix/store/rf7pnq8qk9bkjpl4s2pm5dm2pk4yqhrc-paxctl-0.9
  /nix/store/y5rlyv6nz8134s687d95ysc2gakwx7am-patchelf-0.9
copying path '/nix/store/bkx6rzqciq0sdn1z5liard33ffvv1n3s-bash-4.4-p12-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/f1rp3j71id6g6zcmiafrksmw1cgydl9k-bash-4.4-p12-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/d5ki460cwwydf93f31is95sqpcf334r4-bash-4.4-p12-info' from 'https://cache.nixos.org'...
copying path '/nix/store/fskpf2pdlgn4gm2kay7lfbw1cmjil6s3-bash-4.4-p12-man' from 'https://cache.nixos.org'...
copying path '/nix/store/5hszvi0hczzh25mmsz5rkb9qa758c10p-bash-4.4-p12-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/9bkj2zjc8jdzwgwdwb5d890hrhrk9d3g-bash-4.4-p12-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1' from 'https://cache.nixos.org'...
copying path '/nix/store/1sq8mqjly01pb1nf471phgbgc71v12yy-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/lhp5rw0dagi5mgqwr9i3x41240ba4ypz-gnumake-4.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/y5rlyv6nz8134s687d95ysc2gakwx7am-patchelf-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/rf7pnq8qk9bkjpl4s2pm5dm2pk4yqhrc-paxctl-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/cmxaqb5cbzy4jk26na842n6hy1s4yn19-binutils-wrapper-2.28.1' from 'https://cache.nixos.org'...
copying path '/nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/l3nz0167a4xhb78ldcjns5p4dwvlm1cw-stdenv' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.36, NixOS, 18.03.132155.b50443b5c4a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03"`
 - channels(pirateking): `"nixos-18.03.132083.06c576b0525"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by andrewmiller1** [comment]
@dtzWill Perhaps you have some experience with this module?

**Comment by dtzWill** [comment]
It seems to start fine in the simple NixOS test I put together (linked below), but connecting isn't working...

Oh, right.  Need to set some environment variables -- or perhaps just su over to run as "neo4j".

https://github.com/dtzWill/nixpkgs/commit/c7f314ff0184bc476940095160511a7a0e499d36#diff-ca609eb02968c93ee4420f2faf1f2e33R16 should give an idea.

Hope this helps but we should probably do something to make this better!

**Comment by dtzWill** [comment]
If you enable the neo4j service, you can use it via your browser by pointing it at ... localhost:7474 or so.  FWIW.

**Comment by andrewmiller1** [comment]
Thank you! I'm working on getting it working live.

Though the test connected. I'm wonder if it already had connected just fine though. The issue was probably the logging on the read only share drive.

One thing though.. and if this question is outside the scope of what you feel like answering, it's appropriate to not work on an answer. I'm trying to learn GNU and everything. Since Neo4j community is GPLv3, and Neo4j enterprise is AGPLv3, isn't Neo4j fully free for our purposes? They have commercial licenses if you want to use it inside a product your selling, but that doesn't restrict anybody. Only opens new doors. How do people make money to eat if additionally providing the option of a commercial license is tainting your software?

**Comment by andrewmiller1** [comment]
And to get back on topic, is it normal for the connected test to also not have the neo4j browser show up in your web browser?

**Comment by dtzWill** [comment]
Haha, yes GPLv3 is definitely "free" in this context--I'm not sure what license I thought it was under.

So a NixOS test would indeed be useful once we have things working as we'd like.  Or even if we don't, to help ensure it doesn't get worse :3.

Not sure re:browser, sorry.  Good luck!

**Comment by andrewmiller1** [comment]
Thank you for your help

**Comment by andrewmiller1** [comment]
It was running all along. Use `systemctl` to control `neo4j.service`. Use `cypher-shell`. Initial login is `neo4j` user and `neo4j` password.

If the `neo4j` command is supposed to work, then this issue can be reopened.
