### ISSUE TITLE
Firefox doesn't build (store corruption?)

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#39730]
## Issue description

Fails with chmod permission error on any build.
https://pastebin.com/qAz7yyP6

Derivation contains: 
https://pastebin.com/5yyi37qQ

As noted by chat members, my derivation' hash differs from their, and however builds on their systems, but not mine. If you want try building it: http://ge.tt/6zzdEdp2

The question is: how can we note that the system is corrupted and how we can repair it? 

### Steps to reproduce

* I don't know. That's something about cosmic radiation.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.83, NixOS, 17.09.3047.8bce347f02f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3243.bca2ee28db4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by chekoopa** [comment]
BTW, I have to resolve this problem by reinstallation.

**Comment by lheckemann** [comment]
Did you try checking the store for corruption? `nix verify --all --no-trust`

**Comment by chekoopa** [comment]
@lheckemann Yes, I've checked that. No errors.

The issue is resolved by full reinstallation and getting rid of brtfs subvolumes for /var, /tmp, /home, which could trigger abnormal behavior.
