### ISSUE TITLE
base-noprelude needs to track the version of base

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#39741]
[`base-noprelude`](https://hackage.haskell.org/package/base-noprelude) seems to need some sort of special treatment. It depends on a specific version of `base`, since the idea is to mirror `base` precisely, except for the Prelude.

Currently `hackage-packages.nix` contains only the latest version, which means that it works only with the latest GHC. To make it usable with different versions of the compiler, we need each `haskell.packages.ghc*` to have its own version of `base-noprelude` 🤷‍♂️.

(@peti)

**Comment by cdepillabout** [comment]
There hasn't been any activity on this, I'll go ahead and close.  Feel free to open a new issue (or even better, a PR) if you'd like additional packages available.
