### ISSUE TITLE
gpg2 does not also install pinentry

### ISSUE THREAD

**Issue by campadrenalin** [NixOS/nixpkgs#3975]
If I run `nix-env -i gnupg`, I get gpg2. Cool. But if I try to generate a key, I soon run into an issue: there is a missing dependency, a program called 'pinentry' which was not installed at all.

This is actually a bit of a known issue of sorts - the gpg2 nix file actually starts with some instructions in comments. Unfortunately, this isn't good enough. It's only visible to people who know where to look, and it shouldn't be necessary to do hack workarounds at all.

Where gpg2 is installed, it should either put pinentry into the $PATH, or configure gpg2 to know where to look in /nix/store. There should be no manual configuration to make this work, just install and go.

**Comment by wkennington** [comment]
Fixed via 5302ae07
