### ISSUE TITLE
geant4 derivations cannot be built in a sandbox

### ISSUE THREAD

**Issue by Tmplt** [NixOS/nixpkgs#39766]
## Issue description
The derivations under `geant4` (at present only `geant4.v10_0_2` is available, but [v10.4.1 has been PR'd](https://github.com/NixOS/nixpkgs/pull/39514)) cannot be build in a sandbox because external datasets are downloaded during the build stage; building fails when trying to resolve `geant4.cern.ch`. These datasets should probably be downloaded via `fetchurl` instead, prior to building.

### Steps to reproduce
```
$ nix repl
nix-repl> :l <nixpkgs>
nix-repl> :b geant4.v10_0_2
```

**Comment by veprbl** [comment]
I agree. Current ```installData``` is just impure. I think the nix way to do this is to not download these data files before building geant (I assume it builds without any data files present). Then the data files should come with separate derivations with ```setupHook``` pointing to a script like:
```
@name@ () {
  export G4NEUTRONHPDATA="@out@"
}

postHooks+=(@name@)
```
So user would just put in their shell ```geant4.v10_4_1```  (built on hydra), ```geant4.v10_4_1.data.G4NEUTRONHPDATA```, ```geant4.v10_4_1.data.G4XXXDATA```, etc as needed

**Comment by Tmplt** [comment]
>I assume it builds without any data files present

Yes, this is the case.

**Comment by Tmplt** [comment]
Working from `lhapdf` I came up with the following for when it comes to the datasets:
```nix
{ stdenv, fetchurl }:

let
  mkDataset = { name, version, sha256, envvar}:
    stdenv.mkDerivation {
      inherit name version;

      src = fetchurl {
        url = "https://geant4-data.web.cern.ch/geant4-data/datasets/${name}.${version}.tar.gz";
        inherit sha256;
      };

      preferLocalBuild = true;

      installPhase = ''
        cp -R data/ $out/
      '';

      setupHook = writeTextFile {
        name = "setup-hook.sh";
        text = ''
          @name@ () {
            export G4@envvar@DATA="@out@"
          }

          postHooks+=(@name@)
        '';
      };
    };
in
  stdenv.lib.mapAttrs mkDataset {
    # If name and envvar is common, specify rec to set name = envvar.
    { name = "G4NDL"; version = "4.5"; envvar = "NEUTRONHP"; }
    { name = "G4EMLOW"; version = "7.3"; envvar = "LE"; }
    { name = "G4PhotonEvaporation"; version = "5.2"; envvar = "LEVELGAMMA"; }
    { name = "G4RadioactiveDecay"; version = "5.2"; envvar = "RADIOACTIVE"; }
    { name = "G4SAIDDATA"; version = "1.1"; envvar = "SAIDXS"; }
    { name = "G4NEUTRONXS"; version = "1.4"; envvar = "NEUTRONXS"; }
    { name = "G4ABLA"; version = "3.1"; envvar = "ABLA"; }
    { name = "G4PII"; version = "1.3"; envvar = "PII"; }
    { name = "G4ENSDFSTATE"; version = "2.2"; envvar = "ENSDFSTATE"; }
    { name = "G4RealSurface"; version = "2.1"; envvar = "REALSURFACE"; }
  }
```
This wont work as I haven't figured out how to map sets, and because I have omitted the sha256. Am I on the right path?

**Comment by veprbl** [comment]
Maybe something like
```
builtins.listToAttrs (map (a: { inherit (a) name; value = mkDataset a; }) [ { name = "G4NDL"; version = "4.5"; envvar = "NEUTRONHP"; } ])
```

**Comment by Tmplt** [comment]
Alright, got it working with the commit above, one of multiple in https://github.com/NixOS/nixpkgs/pull/39514.

When "building" the datasets, a lot of `Makefile not found`, `configure file not found` is printed. Should another phase  be used when it's just about moving files?

Aside from that, the sourced  `@out@/bin/geant4.sh` in `geant4` exports its own dataset environment variables; these are all wrong now, but since `cd` is used to resolve the path the exports fail and the export from `geant4.<version>.data` remain (which is what we want).  Nevertheless, useless errors are printed. Should we omit these exports from `geant4.sh`?

**Comment by veprbl** [comment]
There is ```dontBuild = true```. You can also put ```dontConfigure = true```, it has no effect yet, but probably will be added sooner or later (#28910).

I also noticed ```geant4.sh``` issue. In principle it should not matter because hooks will be executed after that and they will override G4* variables. But if the cd calls make noise we probably prefer to silence them. I would do ```sed -i 's/export G4\([A-Z]*\)DATA/#export G4\1DATA/' "$out"/bin/geant4.sh```.
