### ISSUE TITLE
criu package requires CONFIG_CHECKPOINT_RESTORE kernel option to work

### ISSUE THREAD

**Issue by bosu** [NixOS/nixpkgs#3982]
To enable CONFIG_CHECKPOINT_RESTORE we need to enable CONFIG_EXPERT as well.

Enabling CONFIG_EXPERT leads to many configuration changes. The attempt to do this is documented in the following PR: https://github.com/NixOS/nixpkgs/pull/3545

**Comment by eduarrrd** [comment]
Maybe we should mark criu as broken while CONFIG_CHECKPOINT_RESTORE is not enabled.

**Comment by lethalman** [comment]
Isn't it usable on other distros that have this option?

**Comment by bluescreen303** [comment]
it is, and it is on nixos systems where people supply their own custom config.

**Comment by eduarrrd** [comment]
Can we mark it broken for nixos only? Or perhaps only if the right kernel options unset?

I'm worried about the user experience. Install nixos ... install criu ... doesn't work.

Or ... adding criu to the system packages could cause the option to be enabled. Any thoughts on this (or the other suggestions)?

**Comment by offlinehacker** [comment]
I wouldn't mark it as broken, as not everyone is running it on nixos, and even on nixos you can enable CONFIG_EXPERT and CONFIG_CHECKPOINT_RESTORE. We should reevalute what CONFIG_EXPERT does in newer kernels, it might not be so wrong to enable it.

**Comment by Profpatsch** [comment]
triage: what’s the status?

**Comment by dasJ** [comment]
@Profpatsch Should be closable as [the module checks for that](/nixos/nixpkgs/tree/master/nixos/modules/programs/criu.nix#L19).
