### ISSUE TITLE
kpmcore fails to build

### ISSUE THREAD

**Issue by mickk-on-cpp** [NixOS/nixpkgs#39834]
### Steps to reproduce

I have this happens on a snapshot of master:

```session
$ nix-env -iA pkgs.libsForQt5.kpmcore
```

results in the following (excerpted):

```session
-- Checking for module 'blkid>=2.30'
--   No package 'blkid' found
CMake Error at /nix/store/9hmhxgj4jk6jmxihgavj6gm0p759misc-cmake-3.10.2/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /nix/store/9hmhxgj4jk6jmxihgavj6gm0p759misc-cmake-3.10.2/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:81 (pkg_check_modules)
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.09pre133640.ea145b68a01 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(mickk): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by peterhoeg** [comment]
Try adding ```utillinux``` to the ```buildInputs```.

**Comment by mickk-on-cpp** [comment]
That does indeed do the trick and build.

**Comment by peterhoeg** [comment]
Any chance you can whip up a PR? If so, please ping me in it.
