### ISSUE TITLE
unixODBCDrivers.mariadb: package is broken -> libmyodbc3-3.51.12.so file not found

### ISSUE THREAD

**Issue by rszibele** [NixOS/nixpkgs#39835]
## Issue description

The file `/nix/store/4cnh6dg7mwhsw0yy7c5ajxhw29l6hwa8-mariadb-connector-odbc-2.0.10/lib/libmyodbc3-3.51.12.so` does not exist so ODBC connections fail.

~~The file `/nix/store/4cnh6dg7mwhsw0yy7c5ajxhw29l6hwa8-mariadb-connector-odbc-2.0.10/lib/libmaodbc.so` seems like the right library, but if you modify (delete and recreate) `/etc/odbcinst.ini` and replace the library's path with the `libmaodbc.so` then isql still fails with a `file not found` error.~~

~~The offending line seems to be snip but as manually editing `/etc/odbcinst.ini` causes a `file not found` with the other library as well, I'm pretty much out of ideas.~~

The offending line is https://github.com/NixOS/nixpkgs/blob/3f47ee271bc10c2ea68e3d2119816d06d4b1feb5/pkgs/development/libraries/unixODBCDrivers/default.nix#L48 which should reference `lib/libmaodbc.so`.

### Steps to reproduce
In `configuration.nix` add:
* `unixODBCDrivers.mariadb` to nixpkgs
* `environment.unixODBCDrivers = with pkgs.unixODBCDrivers; [ mariadb ];` 

Create/Edit `/etc/odbc.ini` and add the following:

    [MyNewDSN]
    Driver = MariaDB
    Server = localhost
    Port = 3306
    Database = MyDatabase
    User = MyUser
    Password = MyPassword

Run `nixos-rebuild switch`

Then run: `isql -v MyNewDSN` and you get the error:

    [01000][unixODBC][Driver Manager]Can't open lib '/nix/store/4cnh6dg7mwhsw0yy7c5ajxhw29l6hwa8-mariadb-connector-odbc-2.0.10/lib/libmyodbc3-3.51.12.so' : file not found
    [ISQL]ERROR: Could not SQLConnect

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.37, NixOS, 18.09pre138687.1b1be29bf82 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.09pre138687.1b1be29bf82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xeji** [comment]
Fixed in #39841
