### ISSUE TITLE
libreoffice starts with warnings

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#39831]
## Issue description
Within a few 100ms, I see the following:
```
LC_ALL=C libreoffice 
mkdir: cannot create directory '/run/user/1000/libreoffice-dbus': File exists
Unknown username "pulse" in message bus configuration file
Failed to drop supplementary groups: Operation not permitted
Failed to start message bus: Failed to set GID to 4: Operation not permitted
```
Expected output when running libreoffice, no warnings.

NixOS 18.03 (release-channel)

**Comment by 7c6f434c** [comment]
Does it still happen on master, by the way? I think I have made a change that might have fixed it…

**Comment by coretemp** [comment]
No idea. How can I test it without building it from source?

**Comment by 7c6f434c** [comment]
It is actually in unstable channel already.

nix-build -I nixpkgs=https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.09pre139198.9d0b6b9dfc9/nixexprs.tar.xz '<nixpkgs>' -A libreoffice

**Comment by coretemp** [comment]
@7c6f434c  You fixed this issue. However, when I run it without specifying `LC_ALL=C` I get the following. 
```
(soffice:31960): Gtk-WARNING **:<time>.198: Locale not supported by C library.
        Using the fallback 'C' locale.
```

It should output *which* locale is not supported and it should also output which ones *are* to make it easy to resolve the problem.

**Comment by 7c6f434c** [comment]
>It should output *which* locale is not supported and it should also output which ones *are* to make it easy to resolve the problem. 

Sorry, what you say should not be fixed in a wrapper. GTK does that, patching GTK error reporting is not in scope.

More to the point: do you have $LOCALE_ARCHIVE in your environment? It sounds like you use Nix on non-NixOS Linux, and do not use the default nix.sh profile snippet.

Unlike DBus and Java paths etc. where LibreOffice has some requirements and some other software doesn't, $LOCALE_ARCHIVE — to the best of my knowledge — is a universal thing for everything from Nixpkgs.

**Comment by coretemp** [comment]
@7c6f434c I was not saying that it was in scope of this particular issue. I am happy that you made `libreoffice` an improvement for NixOS, as well as that you made it easy for me to test things. I also did not say it had to be fixed in the wrapper.   

I am using NixOS (as indicated in many issues on GitHub).
```
env| grep LOCALE
LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.git.45cd609 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by 7c6f434c** [comment]
Sorry for assumptions — well I do expect people to run different things in different environments, so I never try to look up what people used last time.

I was a bit brief with my scoping claim — sorry if it sounded rude, I didn't want to say you were saying or doing something wrong, just that some of your points probably need an additional issue with a different scope for discussing tradeoffs.

I hope that my wrapper is either an improvement or a no-op for every case; I think some cases it helps with are more likely outside NixOS, but no idea. It is cheap to rebuild, so anything that seems related to LibreOffice can be merged into it without too much risk.

As a quick test: if you run `perl -e 'print "1\n"'`, what happens? Best case: it prints 1 and nothing else. Worst case (what I get with `LOCALE_ARCHIVE= `): ir complains about locales.

Does you NixOS configuration contain anything about locale? Like `supportedLocales`, which seem to default to `"all"` but may be restricted in configuration?

**Comment by coretemp** [comment]
It prints 1 and nothing else.
```
i18n.defaultLocale = "de_DE.UTF-8"; # only thing related to locales. 
```

What you did is a net improvement. Just for form I will close this issue.

**Comment by 7c6f434c** [comment]
If Perl doesn't complain, I might have (previously) broken something in the wrapper…

If you run `libreoffice.libreoffice`, does it complain the same way about locale?

**Comment by coretemp** [comment]
I don't know what `libreoffice.libreoffice` is, but running plain `libreoffice` (the one in 18.03 stable) does not print the locale error.

**Comment by 7c6f434c** [comment]
In the `master` branch and in the unstable channels unwrapped Libreoffice is available as `libreoffice.libreoffice` package. 

`env -i PATH=$PATH LOCALE_ARCHIVE=$LOCALE_ARCHIVE DISPLAY=$DISPLAY HOME=$HOME LC_ALL=de_DE.UTF-8 libreoffice` doesn't complain about locales, so I am trying to narrow down what is going on…

**Comment by coretemp** [comment]
Using `libreoffice.libreoffice` from unstable as specified above.

```
/nix/store/yjcya0dni8k63asghwk2crfkllxsy5j5-libreoffice-5.4.6.2/bin $ env -i PATH=$PATH LOCALE_ARCHIVE=$LOCALE_ARCHIVE DISPLAY=$DISPLAY HOME=$HOME LC_ALL=de_DE.UTF-8 ./libreoffice /nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/sh: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
/nix/store/yjcya0dni8k63asghwk2crfkllxsy5j5-libreoffice-5.4.6.2/bin/.soffice-wrapped: line 160: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)

```

**Comment by 7c6f434c** [comment]
Hm. And if you wrap perl in the same way, it doesn't complain, right?

**Comment by coretemp** [comment]
Not sure whether you meant this, but: 
```
env -i PATH=$PATH LOCALE_ARCHIVE=$LOCALE_ARCHIVE DISPLAY=$DISPLAY HOME=$HOME LC_ALL=de_DE.UTF-8 perl -e 'print "1\n"'
1
```

**Comment by 7c6f434c** [comment]
Thanks!

So there is some LibreOffice-specific problem, I cannot reproduce it locally, and I have no idea what it is… annoying.

**Comment by coretemp** [comment]
One way to fix this is to write a NixOS module, which supports less environment variables. For example, only `LC_ALL`, `PAPER_SIZE` and `LANGUAGE`. This way you don't have to support all possible combinations of environment variables users might throw at your wrapped version. 

I would try to fix the error message upstream. I don't expect you to do this. I think libreoffice already works better on NixOS with your fixes than it does on some other Linux operating systems.

**Comment by 7c6f434c** [comment]
Well, I try to fix in the wrapper things I can reproduce easily. And I don't want to complain to upstream about things I cannot reproduce, either… (also: I don't use NixOS mainline; and I think manipulating the environment that is needed only for LibreOffice could be reasonably done on the level of the wrapper — maybe optionally).

For example: apparently, even with the same restricted environment LibreOffice complains about locale and Perl doesn't. If I could reproduce that behaviour locally, I would have an opinion what is the saner way to debug and triage and maybe fix it…

If you are willing to do some more random experiments, maybe creating a completely fresh/empty user account and comparing the behaviour there could help localizing the difference…
