### ISSUE TITLE
spamassassin service fails

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#39842]
## Issue description

The services `spamassassin` and `sa-update` are failing to start on my NixOS unstable system.

The service is enabled in `configuration.nix`:
```
  services.spamassassin.enable = true;
```

And the status of the services are:
```
$ systemctl status spamd
● spamd.service - Spam Assassin Server
   Loaded: loaded (/nix/store/s4l1wvi5n7n8z1szs8b3b1x8b7s4dfjy-unit-spamd.service/spamd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-05-01 17:23:59 -03; 2h 15min ago
  Process: 1028 ExecStartPre=/nix/store/7wsjbg58vm2ff5f7cyvblkkywiisf324-unit-script/bin/spamd-pre-start (code=exited, status=4)

May 01 17:22:42 romildo systemd[1]: Starting Spam Assassin Server...
May 01 17:22:42 romildo spamd-pre-start[1028]: Recreating '/var/lib/spamasassin' with creating '3.004001' (or similar) and 'sa-update-keys'
May 01 17:22:42 romildo su[1065]: Successful su for spamd by root
May 01 17:22:42 romildo su[1065]: pam_unix(su:session): session opened for user spamd by (uid=0)
May 01 17:23:59 romildo spamd-pre-start[1028]: channel: no 'mirrors.updates.spamassassin.org' record found, channel failed
May 01 17:23:59 romildo spamd-pre-start[1028]: sa-update execution error
May 01 17:23:59 romildo systemd[1]: spamd.service: Control process exited, code=exited status=4
May 01 17:23:59 romildo systemd[1]: spamd.service: Failed with result 'exit-code'.
May 01 17:23:59 romildo systemd[1]: Failed to start Spam Assassin Server.

$ systemctl status sa-update
● sa-update.service
   Loaded: loaded (/nix/store/hxcby29dhvaiqc9cql8winrh3avswqzr-unit-sa-update.service/sa-update.service; linked; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-05-01 17:23:54 -03; 2h 16min ago
  Process: 843 ExecStart=/nix/store/gwwbvv7q0qkwla6dhym0y3kfm6v0b9df-unit-script/bin/sa-update-start (code=exited, status=4)
 Main PID: 843 (code=exited, status=4)

May 01 17:22:34 romildo systemd[1]: Started sa-update.service.
May 01 17:22:34 romildo su[847]: Successful su for spamd by root
May 01 17:22:34 romildo su[847]: pam_unix(su:session): session opened for user spamd by (uid=0)
May 01 17:23:54 romildo sa-update-start[843]: channel: no 'mirrors.updates.spamassassin.org' record found, channel failed
May 01 17:23:54 romildo su[847]: pam_unix(su:session): session closed for user spamd
May 01 17:23:54 romildo sa-update-start[843]: sa-update execution error
May 01 17:23:54 romildo systemd[1]: sa-update.service: Main process exited, code=exited, status=4/NOPERMISSION
May 01 17:23:54 romildo systemd[1]: sa-update.service: Failed with result 'exit-code'.
```

cc @peti @qknight 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.5, NixOS, 18.09pre138687.1b1be29bf82 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.09pre138687.1b1be29bf82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by qknight** [comment]
@romildo spamassassin does impure software deployments when sa-update is running. it seems as the remote url changed and the client wasn't updated properly.

on the other hand, http://spamassassin.org/ seems to be down also. 

i don't like this at all and was looking into patching spamassassin in a way, that this exact impure dependency issue is actually made at build-time and distributed using nix instead of a sa-update service which downloads perl code as it is now. 

to implement this properly, at least for me, it would consume lots of time/money i'm not willing to spend as we at nixcloud have other priorities with `nixcloud.email`. so we might just fix the issue at hand but we also thought chaning to a different spam checker tool: https://rspamd.com/ maybe?

**Comment by peti** [comment]
`spamassassin.org` is still offline. This is not good. I think switching to https://rspamd.com/ is the way to go, indeed.

**Comment by romildo** [comment]
I will try `rspamd`.

**Comment by romildo** [comment]
I have moved to `rspamd`.
