### ISSUE TITLE
can one control the encoding used by writeText ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#39847]
## Issue description
I've been working on a home-manager module to generate email MUA/MTA/MRA configs (since I like to use several). 
I seem to have a problem with the encoding of the generated file (us-ascii) and I would like home-manager to write an unicode one instead of us-ascii one:
https://github.com/pazz/alot/issues/1238

The pseudocode is 
```
let       
configFile =mailAccounts:  pkgs.writeText "alot.conf" ("my conf");
in
{
...
xdg.configFile."alot/config".source = configFile config.mail.accounts;
}
```

How can I specify the encoding ?

## Technical details
nixos-unstable

**Comment by vcunat** [comment]
You can't ATM.  I recommend writing a simple `runCommand` derivation that uses a command-line utility to do the conversion, or perhaps abstracting that into a nix function.

**Comment by dezgeg** [comment]
Nix strings are just byte strings (except `\0`) with no specific encoding attached. So just writing UTF-8 text in string literals should just work, no?

**Comment by teto** [comment]
is there any way to change the default then ? Is it influenced by some config locale ? unicode >> us-ascii.
Any suggestion for a "command-line utility to do the conversion" ?

@dezgeg are you suggesting to run '' cat $myString > .config/alot/config'' instead ? I would rather have writeText work but your suggestion might do the trick.

**Comment by vcunat** [comment]
You can probably write that `"my conf"` part in the other encoding, but I expect that would be an editor mess :-)

**Comment by dezgeg** [comment]
I mean that I can just write this in a .nix file and save it in vim with UTF-8 encoding (which is the default):
````
with import <nixpkgs> {}; writeText "foo" "äöä €"
````
So it looks like this on the disk:
````
$ hexdump -C test.nix
00000000  77 69 74 68 20 69 6d 70  6f 72 74 20 3c 6e 69 78  |with import <nix|
00000010  70 6b 67 73 3e 20 7b 7d  3b 20 77 72 69 74 65 54  |pkgs> {}; writeT|
00000020  65 78 74 20 22 66 6f 6f  22 20 22 c3 a4 c3 b6 c3  |ext "foo" ".....|
00000030  a4 20 e2 82 ac 22 0a                              |. ...".|
````
and building that with `nix-build test.nix` results in:
````
$ cat result
äöä €

$ hexdump -C 
00000000  c3 a4 c3 b6 c3 a4 20 e2  82 ac                    |...... ...|
````

No configuration necessary.

**Comment by dezgeg** [comment]
Well did you put any non-ASCII characters there? UTF-8 is a strict superset of ASCII.

**Comment by teto** [comment]
> Well did you put any non-ASCII characters there ?

is that relevant ? I would like it to always be in Unicode since as you say it's a superset of ASCII. The initial reason is because the ASCII charset seems to confuse alot's configobj parser https://github.com/pazz/alot/issues/1238 (I find it hard to believe but that's my best bet here).

**Comment by dezgeg** [comment]
Yes it matters because any ASCII text already is in "Unicode" (and also equivalent in bunch of other encodings like ISO-8859-1) so `file` will report it as such.

For your original problem, I really doubt encodings are involved at all but rather something else.

**Comment by edolstra** [comment]
Note: "Unicode" is not an encoding, UTF-8 is. Nix / writeText will pass through any UTF-8 characters in the input. If you want UTF-16 you'll have to convert the string in the builder, e.g. by piping it though `iconv`.

**Comment by teto** [comment]
Thanks for the detailed answers, seems like the original is completely unrelated :shame:
