### ISSUE TITLE
Remove duplicate references in all-packages.nix

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#39840]
## Issue description

Quite a few files are referenced in callPackage multiple times. This is almost always not the right way to do things. Almost always an override is preferred to running callPackages multiple times. I remove many in #39686 but lots still remain. Here is the full list:

- [ ] ../applications/networking/browsers/firefox-bin
- [ ] ../applications/office/libreoffice/wrapper.nix
- [ ] ../applications/video/mkvtoolnix
- [ ] ../applications/video/vlc
- [ ] ../development/go-modules/generic
- [ ] ../development/interpreters/lua-5/5.2.nix
- [ ] ../development/interpreters/lua-5/5.3.nix
- [ ] ../development/libraries/audio/libbass
- [ ] ../development/libraries/glibc
- [ ] ../development/libraries/gpgme
- [ ] ../development/libraries/phonon
- [ ] ../development/libraries/phonon/backends/gstreamer.nix
- [ ] ../development/libraries/phonon/backends/vlc.nix
- [ ] ../development/libraries/poppler
- [ ] ../development/libraries/qscintilla
- [ ] ../development/libraries/qtkeychain
- [ ] ../development/libraries/telepathy/qt
- [ ] ../development/web/nodejs/v10.nix
- [ ] ../development/web/nodejs/v6.nix
- [ ] ../development/web/nodejs/v8.nix
- [ ] ../development/web/nodejs/v9.nix
- [ ] ../os-specific/linux/sysdig
- [ ] ../os-specific/linux/uclibc
- [ ] ../os-specific/linux/wireguard
- [ ] ../os-specific/linux/zfs
- [ ] ../shells/bash/4.4.nix
- [ ] ../test/cc-wrapper
- [ ] ../test/cc-wrapper/multilib.nix
- [x] ../tools/misc/grub/2.0x.nix
- [x] ../tools/misc/heimdall
- [ ] ../tools/networking/openconnect
- [x] ../tools/system/rsyslog

Output comes from this command:

```
grep 'callPackage ' pkgs/top-level/all-packages.nix | sed 's,^.*callPackage ,,' | sed 's, .*,,' | sort | uniq -d
```

**Comment by Artturin** [comment]
> Almost always an override is preferred to running callPackages multiple times

this is not true as it, for example, breaks replacing a package with its nox version via a overlay.
