### ISSUE TITLE
question: apt-proxy equivalent for NixOS?

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#39851]
## Issue description
When building docker images from scratch repeatedly, I am hitting cache.nixos.org quite hard (because the store in inside the docker image as opposed to on the host). Is there a way to setup a proxy on NixOS such that I don't do this repeatedly? I.e., I just want to have a 100GB cache or so.

**Comment by dtzWill** [comment]
A caching proxy would probably do the trick.  IIRC someone implemented one specifically for Nix (at least experimentally).

Nix 2 has a flag for binary-stores to use a local path for caching nars-- undocumented AFAIK, and perhaps intentionally undocumented.  But might help: https://github.com/NixOS/nix/blob/47ad88099b1cd2b19bdf3eef35c21baf35cc7e82/src/libstore/binary-cache-store.hh#L21

Using that as a parameter to the binary cache store of cache.nixos.org, pointed at a shared volume mounted from host? Something like that might do the trick.  YMMV, good luck!

**Comment by c0bw3b** [comment]
You might be interested:
https://discourse.nixos.org/t/ann-eris-a-simple-binary-cache-server/1265
