### ISSUE TITLE
package request/idea: gvisor

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#39889]
"Sandboxed container runtime"

https://github.com/google/gvisor

Bonus points for NixOS option for docker support :P. But just having it to poke at would be neat, i think!

**Comment by q3k** [comment]
I've looked quickly at this, and it seems like the main limitation in implementing this is https://github.com/bazelbuild/rules_go/issues/1376 . I think we either have to patch Bazel in NixOS or any Bazel package that compiles Go to fix this...
