### ISSUE TITLE
can't forward port to vm

### ISSUE THREAD

**Issue by eisbaer-north** [NixOS/nixpkgs#39908]
## Issue description
I have a nixos host running a kvm vm. i want to forward the external port 22221 to the ssh port of the virtual machine so i can ssh into my vm from the outside (`ssh ip -p 22221`)

This is my nat configuration

```
networking.nat = {
  enable = true;
  externalInterface = "enp0s20";
  forwardPorts = [
    {
      sourcePort = 22001;
      proto = "tcp";
      destination = "192.168.122.122:22";
    }
  ];
};
```

## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3243.bca2ee28db4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by eisbaer-north** [comment]
it creates a the nat rule 
```
chain nixos-nat-pre (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:optocontrol to:192.168.122.122:22
```

**Comment by flokli** [comment]
Is this a duplicate of #28721?
