### ISSUE TITLE
Cannot download google-chrome 65 from servers

### ISSUE THREAD

**Issue by xurei** [NixOS/nixpkgs#39916]
## Issue description
On 17.09, after a `sudo nix-channel --update`, Google Chrome is not found on the servers.

### Steps to reproduce
`nixos-rebuild switch`

## Technical details

Trace :
```
trying http://repo.fdzh.org/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_65.0.3325.162-1_amd64.deb
curl: (22) The requested URL returned error: 404 
error: cannot download google-chrome-stable_65.0.3325.162-1_amd64.deb from any mirror
```

nix-shell -p nix-info --run "nix-info -m" : 
```
- system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3204.d16ffa15090 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3243.bca2ee28db4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by xurei** [comment]
Workaround: 
I found the mising file here : http://sagasl.uccuyosl.edu.ar/mirror/dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_65.0.3325.162-1_amd64.deb

And installed it manually with : `sudo nix-prefetch-url http://sagasl.uccuyosl.edu.ar/mirror/dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_65.0.3325.162-1_amd64.deb`

**Comment by wamserma** [comment]
@xurei I think this can be closed.

**Comment by xurei** [comment]
Indeed
