### ISSUE TITLE
Manual says nixos-install won't prompt for root password if mutableUsers is false, but 18.03.132217 is asking for root password

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#39915]
On new installation of nixos 18.03 c56ebaba1b0

I have set `users.mutableUsers = false`.

Upon `nixos-install`. It's asking for the root password.

**Comment by npmccallum** [comment]
I'm also seeing this problem.

**Comment by eliasp** [comment]
Use `nixos-install --no-root-passwd` as a temporary workaround.

**Comment by CMCDragonkai** [comment]
The new flag helps now.

Also just wanted people to know that if you do set no root password, and you don't set any users, you'll install an OS that cannot be logged in at all. So either set a temporary root password that you can later delete, or enable mingetty to autologin.
