### ISSUE TITLE
anonscm.debian.org has migrated to salsa.debian.org!

### ISSUE THREAD

**Issue by voobscout** [NixOS/nixpkgs#39927]
## Debian SCM moved to gitlab at new URI!
At some point in recent time, Debian maintenance team migrated SCM from http://anonscm.debian.org to https://salsa.debian.org. In the process, redirects have not been provided, the old site is still up, but contains none of the expected content at 404.

Whoever moderates issues here, please rename this one appropriately and assign severity and somehow let package maintainers know about this, it looks like this move by Debian is going to affect quite a few things.

### Steps to reproduce
Try building any package that depends on anything from the old debian SCM, in my case it was qt48 (nixpkgs/pkgs/development/libraries/qt-4.x/4.8/default.nix)

A patch is being pulled from http://anonscm.debian.org/cgit/pkg-kde/qt/qt4-x11.git/plain/debian/patches/kubuntu_39_fix_medium_font.diff?id=21b342d71c19e6d68b649947f913410fe6129ea4 and fails, since the new version is available at https://salsa.debian.org/qt-kde-team/qt/qt4-x11/raw/21b342d71c19e6d68b649947f913410fe6129ea4/debian/patches/kubuntu_39_fix_medium_font.diff

Relevant part of qt48 default.nix: https://github.com/NixOS/nixpkgs/blob/ef01f17c2dcfea87669019349d7d11bb32fd4d88/pkgs/development/libraries/qt-4.x/4.8/default.nix#L80-L85

Thanks for taking a look!

**Comment by matthewbauer** [comment]
I take this to mean that Debian probably doesn't want other distros using their patches. This is also an issue with patch-tracker.debian.org (https://github.com/sgeb/homebrew-mutt/issues/3). Luckily we are not using it too often 

https://github.com/NixOS/nixpkgs/search?q=anonscm.debian.org
https://github.com/NixOS/nixpkgs/search?q=patch-tracker.debian.org

Anyone have objections to just removing them? If Debian hasn't upstreamed them by now they probably never will be.

**Comment by voobscout** [comment]
Upon further investigation and after having a chat with nice folks at #debian-devel irc, it has been noted that:

* The move to gitlab has been planned for a few years and was the best-effort deal.
* Maintaining redirects for links compatibility has been deemed unfeasible, with current attempt https://paste.debian.net/1023154 being what it is and anyone being welcome to take a crack at it or have a similar service.

As for nix:

Should it really depend on some web deep-links? There're lots of patches maintained with the nixpkgs as far can be seen, why not just extend this practice to everything?

**Comment by voobscout** [comment]
The fact of the matter is - getting stuff upstreamed is rather a big deal unfortunately. Many projects have questionable policies and individuals in-place to make this process bumpy to the point of it being irritating and ultimately not worth the effort.

This qt48 pkg is an excellent example - why was this particular patch not accepted upstream? If we start digging, we'll find some very convincing reason, at least in the eyes of the project maintainers and we still won't be able to exert our will upon the situation.

We're dealing with the real world here, why inconvenience ourselves with yet another non-resolvable issue in the long term.

For myself, I resolved it with an overlay so far, but it would have been a lot more preferable not to encounter it in the first place.

Having "in-house" patches seems to be the logical solution.

Also, how is this not nix specific, if it is included in the pkgbuild? If this patch wasn't required, I imagine it would not have been included, the name of the patch suggests that it originally was developed for kubuntu variant of debian. It is being included here in nixpkgs, hence it is nix specific and merits being included in the repo.

Just my couple of cents... I could also be spectacularly mistaken...

**Comment by dtzWill** [comment]
I'll add that sometimes upstream is no longer maintained-- in which case I think local patches is usually the best choice.

It might make sense to keep them separately so as to not bloat the nixpkgs tree (and making channel updates slower).

Are patches made available on the hashed mirror like source tarballs?

**Comment by matthewbauer** [comment]
Oh yeah definitely open a pr with your overlay changed - it’s certainly better than having broken urls. I didn’t mean to suggest we won’t fix these - just why it’s not a priority for me at least. My main concern is what happens when Debian decides they don’t like GitLab anymore and moves to something else and then after that.

I could have sworn there was a place where Debian puts all of there patches to be mirrored but I can’t find it right now.

**Comment by voobscout** [comment]
@matthewbauer Do you want me to open PR for this?

```nix
self: super:

let
  patch-name-regex = "(.*fix-medium-font.*)";
  patch-old = with builtins; filter (x: let p = match "(.*fix-medium-font.*)" (toString(x)); in if p == null then false else true) super.qt48.patches;
  patch-new = super.fetchpatch {
    name = "fix-medium-font.patch";
    url = "https://salsa.debian.org/qt-kde-team/qt/qt4-x11/raw/" +
      "21b342d71c19e6d68b649947f913410fe6129ea4/debian/patches/kubuntu_39_fix_medium_font.diff";
    sha256 = "0bli44chn03c2y70w1n8l7ss4ya0b40jqqav8yxrykayi01yf95j";
  };
  proper-patches = (super.lib.lists.remove patch-old super.qt48.patches) ++ [ patch-new ];
in

{
  qt48 = super.qt48.overrideAttrs ( oldAttrs: {
    patches = proper-patches;
  });
}
```
I am not sure where to stick this, I got it in my nixpkgs.overlays section, not to mention the fact that I am not confident this solution is either correct or working, since I got stuck rebuilding my system with a few broken pkgs.

Correct me please, if this is the wrong way of fixing that specific case.

**Comment by matthewbauer** [comment]
Okay thanks just updated the url - applied in ef82607d90b45683740f70bacc218566093a4455.
