### ISSUE TITLE
meson support for clang broken

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#39936]
meson's setup-hook.sh [sets `CC=@cc@/bin/cc CXX=@cc@/bin/c++`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/meson/setup-hook.sh#L26), clobbering the values provided by the stdenv. This (silently?) breaks `clangStdenv` and, because gcc doesn't support `-stdlib=libc++`, noisily breaks `libcxxStdenv`.

This was introduced by 284f75a258e0f766b8b5d047c486f11c4c4e102d (cc @shlevy). Never having touched the crosscompilation infrastructure before, I'm not sure what the intended behavior here is, let alone the correct way to do it, but it probably shouldn't be forcing everything to use some arbitrary gcc.

**Comment by Ralith** [comment]
On closer examination I see that what's happening is that the meson package hardcodes the stdenv it's built with, therefore breaking use targeting any other stdenv. Was this intended?

**Comment by shlevy** [comment]
Not necessarily intended, but not sure the nicest solution either. Maybe a way to bundle meson with a particular stdenv? @Ericson2314 , thoughts?

**Comment by Ericson2314** [comment]
Can we just not set those vars? The environment should already have them.

**Comment by shlevy** [comment]
There was definitely a real case where this was needed (cross systemd maybe?) but I don't remember the symptoms.

**Comment by Ralith** [comment]
I assume `cc` is being set at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/meson/default.nix#L73 and substituted in by default somewhere.

**Comment by Ericson2314** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/commit/3c00ca03a251693e58eb4e3c247ee1f640215783#diff-6b138c4aaf5164baf820a221e2d6dd93 :)

**Comment by nh2** [comment]
@Ericson2314 Thanks, that was sorely needed.

Fixes my non-cross C++ builds with Meson.

**Comment by L-as** [comment]
I can't seem to use `overrideCC stdenv llvmPackages_10.lldClang` as my stdenv still.
meson gives me this:
```
Using 'CC_FOR_BUILD' from environment with value: 'gcc'
Using 'AR_FOR_BUILD' from environment with value: 'ar'
Using 'CXX_FOR_BUILD' from environment with value: 'g++'

meson.build:21:0: ERROR: Compiler g++ can not compile programs.
```

**Comment by L-as** [comment]
Made a new issue, since it only seems to be mesa?
