### ISSUE TITLE
User environment not updating to system binaries/libraries (persistent)

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#39955]
## Issue description
This is occurring with something that has to link `ffmpeg-full` and `graphicsmagick` while compiling.
`/nix/store/zk9pppcfihpb9067c55kxkh4glzzr1dg-go-1.10.1/share/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1`
`/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lGraphicsMagick`
`/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lavcodec`
`/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lavutil`
`/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lavformat`
`/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lswscale`
`collect2: error: ld returned 1 exit status`

### Steps to reproduce
Attempt to compile something that uses ffmpeg and the aforementioned linker options.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.38, NixOS, 18.03.132229.7cbf6ca1c84 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132229.7cbf6ca1c84, nixos-unstable-18.09pre138871.af55a0c3002, nixpkgs-18.09pre139130.b30c6d79503"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Chiiruno** [comment]
This problem seems to go away when making a [VM](https://nixos.wiki/wiki/Cheatsheet) with the latest nixpkgs git.
Is this perhaps an upgrade path issue with the linker not getting updated?

**Comment by Chiiruno** [comment]
Interestingly, if I build as root it compiles and builds.
I believe this is a problem with the user directory in `/run`.

**Comment by Chiiruno** [comment]
This doesn't seem to be a problem now on my side, but I'm keeping open until someone with more knowledge on the matter comments.

**Comment by vcunat** [comment]
I suspect using sandboxing would "solve" such issues.

**Comment by Chiiruno** [comment]
@vcunat That's sort of what happened, but it's still affecting certain packages such as emscripten, where I can build as another user but not as my own.

**Comment by Chiiruno** [comment]
Go problems are fixed by deleting `~/.cache/go-build`
Emscripten problems are fixed by deleting `~/*emscripten*`
I wish I knew what was causing this issue, but I'll close for now.
