### ISSUE TITLE
nix-prefetch-git does not handle submodules with spaces

### ISSUE THREAD

**Issue by lionello** [NixOS/nixpkgs#39956]
This bug manifests itself as showing the following error during `nix-prefetch-git`:
```
error: key does not contain a section: .url
```

I've tracked this down to this line:
https://github.com/NixOS/nixpkgs/blob/4d6a14e915b8e2f4142eaf54c225bbce0d75dd87/pkgs/build-support/fetchgit/nix-prefetch-git#L188

The `awk` command in that line ends up picking up the first word of the folder, instead of the entire folder. Changing that line to the following fixes this:
```
         dir=$(echo "$l" | awk '{for(i=1; i<NF-1; ++i) $i=$(i+1); NF-=2; print}')
```

This effectively deletes the first and last columns of the `git submodule status` line, cutting off the commit hash and tag, leaving the folder name intact.

**Comment by adisbladis** [comment]
For future reference:

This is the repro case `nix-prefetch-git --url "https://github.com/Carthage/Carthage.git" --rev c6952b87ce11a14cf17eccb829598c4ff538b140 --fetch-submodules`
