### ISSUE TITLE
Package dmd is broken

### ISSUE THREAD

**Issue by voobscout** [NixOS/nixpkgs#39951]
## Failed installing dmd
```
warning: path '/nix/store/3jngv6gzm5qyqdlkicxj48gknhxv033c-phobosUnittests-2.067.1' claims to be content-addressed but isn't
error: unexpected end-of-file
```

### Steps to reproduce
```bash
nix-env -iA nixos.dmd
```
or add it to system:
```nix
{ pkgs, config, ... }:

{
  environment.systemPackages = with pkgs ; [ dmd ];
}
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.6, NixOS, 18.03.132192.ce0d9d638de (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(admin): `""`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/store/2kh4bx71ras3bwwlag3919by0d5hgfvs-nixexprs.tar.xz`

**Comment by voobscout** [comment]
ping @ThomasMader, can anything be done about it?

**Comment by ThomasMader** [comment]
The error is not reproducible on hydra. See https://hydra.nixos.org/eval/1453850?filter=dmd&compare=1453744&full= for example.
The build of dmd 2.079.0 was successful on branch 18.03.
Are you trying to build it on your machine?
What has changed on your branch? Is there a more verbose error message?

**Comment by voobscout** [comment]
Can't keep it opened if Hydra builds it, will be looking into my config. Thanks!

**Comment by ThomasMader** [comment]
The build on master and staging master is broken, maybe you are on one of those branches?
I will try to fix the problems on master, can't tell you when that will be finished though.
On the positive side I am aware of the problems. :-)
