### ISSUE TITLE
aarch64-linux required to build netboot PXE image on x86_64-linux

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#39959]
## Issue description

Trying to build a PXE image following the instructions in the manual.  I have the latest 18.03 in <nixpkgs> and I try to build the netboot as follows:

`nix-build /nix/var/nix/profiles/per-user/root/channels/nixpkgs/nixos/release.nix -A netboot`

This ultimately results in:
`error: a 'aarch64-linux' is required to build '/nix/store/0lcllwrkw2f4xqpkpx5hzdmnr7r6b35c-append-initrd-secrets.drv', but I am a 'x86_64-linux'`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.34, NixOS, 18.03.132021.c0c5571ec1a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.03.132229.7cbf6ca1c84"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by dezgeg** [comment]
You need to do `-A netboot.x86_64-linux`, not just plain `-A netboot`.

**Comment by ledettwy** [comment]
@dezgeg OH, okay. Silly me :p thank you for the clarification!

**Comment by bbigras** [comment]
> You need to do -A netboot.x86_64-linux, not just plain -A netboot.

Maybe https://nixos.org/nixos/manual/index.html#sec-booting-from-pxe should be corrected.
