### ISSUE TITLE
clementine: misses gstreamer plugins to play flac.

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#39960]
## Issue description

Clementine refuses to play FLAC files (in my case).

### Steps to reproduce

I'm on the latest `nixos-unstable`. Both `clementine` and `clementineUnfree` say:

> GStreamer could not create the element: pulsesink. Please make sure that you have installed all necessary GStreamer plugins (e.g. OGG and MP3)

whenever I try to play a file.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.38, NixOS, 18.09pre138871.af55a0c3002 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `"nixos-18.09pre138871.af55a0c3002"`
 - channels(mark): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Pneumaticat** [comment]
I get the same error, except for me it's autoaudiosink and not pulsesink. I've also tried with both clementine and clementineUnfree.

**Comment by mrkkrp** [comment]
So what do you people use to play music?

**Comment by peterhoeg** [comment]
cantata (Qt frontend for mpd)

**Comment by jerith666** [comment]
Clementine was able to play music until fairly recently.  Alas, I can't say for sure exactly when it stopped working as I recently made a hardware change that makes older versions of my system unbootable.

**Comment by jerith666** [comment]
Ah, okay, I found my older issue #39179; the fix there was #38513, which I recall verifying locally.  So somewhere in that neighborhood could be a good starting point for a bisect.

**Comment by schmittlauch** [comment]
I can report that #42314 fixes this issue for me on nixos-stable-18.09. Without this fix the situation is even worse, as not only FLAC files couldn't been played, but (all?) other formats like mp3 or Vorbis were affected as well.
