### ISSUE TITLE
Simple application with haskell and sdl2 segfaults

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#39965]
## Issue description

Original issue [here](https://github.com/haskell-game/sdl2/issues/181). A very simple SDL2 test application written in Haskell segfaults. Since it works on other systems, I expect the fault to be somewhere with nixOS.

### Steps to reproduce

1. Copy this into a file with ending `.hs`:
```haskell
{-# LANGUAGE OverloadedStrings #-}
import SDL

main :: IO ()
main = do
  initializeAll
  window <- createWindow "My SDL Application" defaultWindow
  renderer <- createRenderer window (-1) defaultRenderer
  appLoop renderer

appLoop :: Renderer -> IO ()
appLoop renderer = do
  rendererDrawColor renderer $= V4 0 0 255 255
  clear renderer
  rendererDrawColor renderer $= V4 255 255 255 255
  drawPoint renderer $ P $ V2 100 100
  present renderer
  appLoop renderer
```
2. Create a cabal project (and stack project if you want) containing this executable, with dependency `sdl2`
3. In case of cabal, enter a `nix-shell -p pkgconfig SDL2`, build the project, run your executable
4. Segmentation Fault

## Technical details

I'm running this in xmonad.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.132192.ce0d9d638de (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03"`
 - channels(turion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ocharles** [comment]
Are you building this with exactly the same nixpks as what is running on your system?

**Comment by matthewbauer** [comment]
Do you get a segfault running the program like this:

```
#! /usr/bin/env nix-shell
#! nix-shell -i runghc -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [sdl2])"

{-# LANGUAGE OverloadedStrings #-}
import SDL

main :: IO ()
main = do
  initializeAll
  window <- createWindow "My SDL Application" defaultWindow
  renderer <- createRenderer window (-1) defaultRenderer
  appLoop renderer

appLoop :: Renderer -> IO ()
appLoop renderer = do
  rendererDrawColor renderer $= V4 0 0 255 255
  clear renderer
  rendererDrawColor renderer $= V4 255 255 255 255
  drawPoint renderer $ P $ V2 100 100
  present renderer
  appLoop renderer
```

Just run:

```
nix-shell -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [sdl2])" --run 'runghc test.hs'
```

It's working for me at least on macOS. IIRC cabal outside of the Nix store is officially unsupported (although it works in most cases). It is usually safest to build the ghc wrapper above in a nix-shell.

**Comment by turion** [comment]
@ocharles I'm not quite sure I understand. I think yes..? (How could it be otherwise?)

@matthewbauer strangely enough, this now outputs:
```
Renderer.hs: SDLCallFailed {sdlExceptionCaller = "SDL.Video.createRenderer", sdlFunction = "SDL_CreateRenderer", sdlExceptionError = "Couldn't find matching render driver"}
```

**Comment by typetetris** [comment]
see #9415 it seems to be the same issue. If you are on non-nixos, nixpkgs tries to bring the graphics driver, which is of course pointless.

**Comment by turion** [comment]
@typetetris I'm on NixOS.

**Comment by typetetris** [comment]
@turion Its just a wild guess: Did you use the same channel when running the script from https://github.com/NixOS/nixpkgs/issues/39965#issuecomment-386916408, as you used for your nixos installation?

I only had the error message you cite, when using non-nixos and then I needed to provide the following libraries from my system:
```
./dri/i965_dri.so
./libGL.so.1
./libdrm_intel.so.1
./libGL.so.1.2.0
./libdrm_intel.so.1.0.0
```

So maybe you could check wether the runtime closure of your X uses the same libGL as the runtime closure of your program. For me this was
```
nix-store -qR $(readlink $(which X)) | grep -i libgl
```
and
```
nix-store -qR $(readlink result) | grep -i libgl
```
issued in the directory, where I used `nix-build` to build the program. And see if the paths for libGL match.

**Comment by schell** [comment]
Looks like I've run into this as well in https://github.com/haskell-game/sdl2/issues/196.

**Comment by typetetris** [comment]
You probably should get all available drivers with `getRenderDriverInfo` and try to create the renderer by index, catching the possible exception, until one succeeds. In case of not properly installed drivers, that should always fall back to the software renderer.

Also the exception from `createRenderer` if an index is used, is usually more specific.

I got `glx not supported` and noticed, that I am unintentionally running the `vesa` xorg driver.

One can also use (shameless self promotion): https://github.com/typetetris/sdl-try-drivers which simply tries all drivers.

**Comment by turion** [comment]
@matthewbauer your suggestion (from over a year ago) works! I can't reproduce my original problem anymore, for some reason. It must have been related to some driver mismatch because of different `nixpkgs` versions. I'll close for now.

**Comment by someodd** [comment]
@turion Sorry to ping you in an old issue, but which suggestion exactly was it that got it to work for you? I've been struggling with this issue for a while (https://github.com/haskell-game/sdl2/issues/196#issuecomment-1761020268).

**Comment by turion** [comment]
I'm not sure anymore, but I consider it good practice to use `haskellPackages.ghcWithPackages (pkgs: with pkgs; [sdl2])` for such situations. In general, when a Haskell library needs a non-Haskell dependency (OpenGL, PulseAudio, ...), I usually just install that Haskell library via nix with `ghcWithPackages`, and that usually works.

**Comment by someodd** [comment]
Thank you for responding.

I couldn't seem to get it working prior so I ended up using `SDL_RENDER_DRIVER=software nix run` as a workaround for now.
