### ISSUE TITLE
Solaar 0.9.2 - cannot detect receiver

### ISSUE THREAD

**Issue by xurei** [NixOS/nixpkgs#39966]
## Issue description
solaar installed as a systemPackage. The `solaar-cli` and `solaar` commands cannot detect the receiver, while lsusb lists it.
There is a mouse already linked with the receiver thats works.

My guess is that there is some udev configuration to do. Anyone has an working example ?

### Steps to reproduce
- Install solaar as a system package
- `solaar-cli show` : `solaar-cli: error: Logitech receiver not found`

## Technical details
```
$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 005: ID 1bcf:2883 Sunplus Innovation Technology Inc. 
Bus 003 Device 004: ID 13d3:3362 IMC Networks Atheros AR3012 Bluetooth 4.0 Adapter
Bus 003 Device 003: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 003 Device 002: ID 046d:0a29 Logitech, Inc. H600 [Wireless Headset]
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3243.bca2ee28db4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3243.bca2ee28db4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by peterhoeg** [comment]
Can you see it with ```ltunify```?

**Comment by xurei** [comment]
After looking in Windows, the reason was that the dongle was not Anywhere compatible, so Solaar could not detect it.

Closing this issue. However, it would be nice to have a message in such cases
