### ISSUE TITLE
Remove old GStreamer

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#39975]
`comm -23 <(git grep -l gstreamer | sort) <(git grep -l gst_all_1 | sort)`

False positives are crossed out:

- [x] ~~`nixos/modules/services/x11/desktop-managers/plasma5.nix`~~
- [x] `pkgs/applications/audio/banshee/default.nix` – there is [unstable version](http://ftp.gnome.org/pub/GNOME/sources/banshee/2.9/banshee-2.9.1.news) from 2014 that supports GStreamer 1.0 but it still depends on other deprecated libraries – **drop**
- [x] `pkgs/applications/audio/transcribe/default.nix` – recent version supports GStreamer 1.0 https://www.seventhstring.com/xscribe/download_linux.html` – **upgrade** – cc @michalrus
- [x] `pkgs/applications/graphics/draftsight/default.nix` – cc @Hodapp87 – 2018 release seems to still use GStreamer 0.10 we will need to drop it
- [x] ~~`pkgs/applications/kde/kdenlive.nix`~~
- [x] ~~`pkgs/applications/misc/pdfpc/default.nix`~~
- [x] ~~`pkgs/applications/misc/workrave/default.nix`~~
- [x] `pkgs/applications/misc/xneur/0.8.nix` – @7c6f434c do you still use this?
- [x] `pkgs/applications/misc/xneur/default.nix` – 0.20 supports gst1 – **update**
- [x] `pkgs/applications/networking/browsers/firefox-bin/default.nix`
- [x] `pkgs/applications/networking/browsers/firefox/common.nix` – apparently firefox has been removed https://bugzilla.mozilla.org/show_bug.cgi?id=1234092
- [x] `pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix`
- [x] `pkgs/applications/networking/browsers/tor-browser-bundle/default.nix`
- [x] `pkgs/applications/networking/browsers/vivaldi/default.nix` – @otwieracz @nequissimus https://github.com/NixOS/nixpkgs/pull/93367
- [x] `pkgs/applications/networking/instant-messengers/baresip/default.nix` – supports gst1
- [x] ~~`pkgs/applications/networking/instant-messengers/gajim/default.nix`~~
- [x] `pkgs/applications/networking/instant-messengers/zoom-us/default.nix` – cc @danbst
- [x] `pkgs/applications/networking/mailreaders/thunderbird-bin/default.nix` probably unnecessary since gst support was removed in 2015
- [x] `pkgs/applications/networking/mailreaders/thunderbird/default.nix`
- [x] ~~`pkgs/applications/networking/remote/freerdp/default.nix`~~
- [x] `pkgs/applications/video/miro/gconf.patch` – abandoned – **drop**
- [x] ~~`pkgs/applications/video/pitivi/default.nix`~~
- [x] `pkgs/applications/video/qstopmotion/default.nix` – does not use gstreamer since 2.3.1
- [x] ~~`pkgs/desktops/xfce/applications/xfce4-mixer.nix`~~ – deleted
- [x] `pkgs/desktops/xfce/applications/xfce4-volumed.nix` unmaintained **drop** cc @YegorTimoshenko
- [x] ~~`pkgs/desktops/xfce/core/tumbler.nix`~~
- [x] ~~`pkgs/development/compilers/orc/default.nix`~~
- [x] ~~`pkgs/development/libraries/farstream/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/bad/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/base/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/core/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/core/setup-hook.sh`~~
- [x] ~~`pkgs/development/libraries/gstreamer/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/ges/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/good/default.nix`~~
- [ ] `pkgs/development/libraries/gstreamer/legacy/gnonlin/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gst-ffmpeg/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gst-plugins-bad/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gst-plugins-base/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gst-plugins-good/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gst-plugins-ugly/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gst-python/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gstreamer/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gstreamermm/default.nix`
- [ ] `pkgs/development/libraries/gstreamer/legacy/gstreamer/setup-hook.sh`
- [ ] `pkgs/development/libraries/gstreamer/legacy/qt-gstreamer/default.nix`
- [x] ~~`pkgs/development/libraries/gstreamer/libav/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/rtsp-server/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/ugly/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/vaapi/default.nix`~~
- [x] ~~`pkgs/development/libraries/gstreamer/validate/default.nix`~~
- [x] ~~`pkgs/development/libraries/gtkd/paths.d`~~
- [x] `pkgs/development/libraries/libcanberra/default.nix` – references the old gstreamer but apparently only supports the new one
- [x] ~~`pkgs/development/libraries/phonon/backends/gst-plugin-paths.patch`~~
- [x] `pkgs/development/libraries/qt-4.x/4.8/default.nix` – **build without multimedia support**
- [x] ~~`pkgs/development/libraries/qt-5/5.10/default.nix`~~
- [x] ~~`pkgs/development/libraries/qt-5/5.6/default.nix`~~
- [x] ~~`pkgs/development/libraries/qt-5/5.9/default.nix`~~
- [x] ~~`pkgs/development/libraries/qt-5/modules/qtmultimedia.nix`~~
- [x] `pkgs/development/libraries/wxwidgets/2.8/default.nix` – **drop**
- [x] `pkgs/development/libraries/wxwidgets/2.9/default.nix` – **drop**
- [x] `pkgs/development/libraries/wxwidgets/3.0/default.nix` support from [3.1.0](https://wxwidgets.org/news/2016/02/wxwidgets-3.1.0-released/)
- [x] ~~`pkgs/development/python-modules/gst-python/default.nix`~~
- [x] ~~`pkgs/games/steam/runtime-generated.nix`~~ – uses vendored version
- [x] ~~`pkgs/misc/emulators/wine/default.nix`~~
- [x] ~~`pkgs/servers/home-assistant/component-packages.nix`~~
- [x] ~~`pkgs/tools/audio/liquidsoap/full.nix`~~
- [x] `pkgs/tools/graphics/swfdec/default.nix` – dead – **drop** or build without gstreamer
- [x] ~~`pkgs/tools/graphics/wkhtmltopdf/default.nix`~~
- [ ] `pkgs/top-level/aliases.nix`

**Comment by matthewbauer** [comment]
This is a little unrelated - but it would be nice to get a cleaner name for gstreamer. IMO ```gst_all_1``` is a little unintuitive. Something like just ```gstreamer``` and ```gstreamerPlugins``` makes more sense to me. May need to have a legacy ```gst_all_0_10``` for those that break with newer gstreamer.

**Comment by jtojnar** [comment]
Renaming would be nice, I imagine using `pasthru.plugins` for better synchronization. `gst_all_0_10` should be removed altogether, though, not even Debian [supports it](https://packages.debian.org/sid/libgstreamer0.10-0) any more.

**Comment by danbst** [comment]
Addressed this here 
https://github.com/NixOS/nixpkgs/pull/40018/files#diff-7776e323bdfe9eaa393d43003259106bL26

**Comment by 7c6f434c** [comment]
Re: xneur: at some point I gave up on it, because of input handling problems unrelated to multimedia.

**Comment by Anton-Latukha** [comment]
- [x] ~~`pkgs/development/libraries/gstreamer/legacy/qt-gstreamer/default.nix`~~ is really unneded now.
It is legacy Qt bindings project of Gnome. Unmaintained long ago, no dependencies on it.
I am deleting it here: https://github.com/NixOS/nixpkgs/pull/69070

**Comment by Anton-Latukha** [comment]
```
nixos/modules/services/x11/desktop-managers/plasma5.nix
pkgs/applications/kde/dragon.nix
pkgs/applications/kde/kdenlive.nix
pkgs/applications/misc/pdfpc/default.nix
pkgs/applications/misc/workrave/default.nix
pkgs/applications/networking/browsers/vivaldi/default.nix
pkgs/applications/networking/instant-messengers/gajim/default.nix
pkgs/applications/networking/mailreaders/thunderbird-bin/default.nix
pkgs/applications/networking/remote/freerdp/default.nix
pkgs/desktops/gnome-3/core/rygel/add-option-for-installation-sysconfdir.patch
pkgs/desktops/xfce/applications/xfce4-volumed/default.nix
pkgs/development/compilers/orc/default.nix
pkgs/development/haskell-modules/configuration-hackage2nix.yaml
pkgs/development/libraries/aravis/default.nix
pkgs/development/libraries/farstream/default.nix
pkgs/development/libraries/gstreamer/bad/default.nix
pkgs/development/libraries/gstreamer/base/default.nix
pkgs/development/libraries/gstreamer/core/default.nix
pkgs/development/libraries/gstreamer/core/setup-hook.sh
pkgs/development/libraries/gstreamer/default.nix
pkgs/development/libraries/gstreamer/ges/default.nix
pkgs/development/libraries/gstreamer/good/default.nix
pkgs/development/libraries/gstreamer/legacy/gnonlin/default.nix
pkgs/development/libraries/gstreamer/legacy/gst-plugins-bad/default.nix
pkgs/development/libraries/gstreamer/legacy/gst-plugins-base/default.nix
pkgs/development/libraries/gstreamer/legacy/gst-plugins-good/default.nix
pkgs/development/libraries/gstreamer/legacy/gst-plugins-ugly/default.nix
pkgs/development/libraries/gstreamer/legacy/gst-python/default.nix
pkgs/development/libraries/gstreamer/legacy/gstreamer/default.nix
pkgs/development/libraries/gstreamer/legacy/gstreamermm/default.nix
pkgs/development/libraries/gstreamer/legacy/gstreamer/setup-hook.sh
pkgs/development/libraries/gstreamer/libav/default.nix
pkgs/development/libraries/gstreamer/rtsp-server/default.nix
pkgs/development/libraries/gstreamer/ugly/default.nix
pkgs/development/libraries/gstreamer/vaapi/default.nix
pkgs/development/libraries/gstreamer/validate/default.nix
pkgs/development/libraries/gtkd/paths.d
pkgs/development/libraries/libextractor/gst-hardcode-plugins.patch
pkgs/development/libraries/phonon/backends/gst-plugin-paths.patch
pkgs/development/libraries/qt-4.x/4.8/default.nix
pkgs/development/libraries/qt-5/5.12/default.nix
pkgs/development/libraries/qt-5/modules/qtmultimedia.nix
pkgs/development/libraries/wxwidgets/2.8/default.nix
pkgs/development/libraries/wxwidgets/2.9/default.nix
pkgs/development/libraries/wxwidgets/3.0/default.nix
pkgs/development/libraries/wxwidgets/3.1/default.nix
pkgs/development/python-modules/gst-python/default.nix
pkgs/development/python-modules/wxPython/4.0.nix
pkgs/misc/emulators/wine/default.nix
pkgs/servers/home-assistant/component-packages.nix
pkgs/tools/audio/liquidsoap/full.nix
pkgs/tools/graphics/swfdec/default.nix
pkgs/tools/networking/gmrender-resurrect/default.nix
pkgs/top-level/aliases.nix
pkgs/top-level/wine-packages.nix
```

Seems like the big part of what is left - is in Qt/KDE.

**Comment by jtojnar** [comment]
Most of these are false positives. Only vivaldi, thunderbird-bin, xfce4-volumed, qt4, wxwidgets and swfdec still depend on the old gstreamer and they can probably build without it too.

**Comment by FRidh** [comment]
It's a good way to motivate people to look into migrating if their application depends on it (transitively).

**Comment by vcunat** [comment]
Not much is left now.  For reference, current more precise list: https://github.com/NixOS/nixpkgs/pull/92261#issuecomment-653783170
