### ISSUE TITLE
[request] Brother's brscan2 scanner driver

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#39995]
## Issue description
I have an old [DCP-130C](http://support.brother.com/g/b/downloadlist.aspx?c=us&lang=en&prod=dcp130c_all&os=128) Printer+Scanner that doesn't seem to work with existing [brscan4](https://nixos.org/nixos/options.html#brscan).

I try to build the driver source and failed. Try to modify the brscan4 expression to use brscan2 binaries but it seem not an easy task. I have virtually zero knowledge on SANE.

You can find the list of devices that support by difference driver version [here](http://support.brother.com/g/s/id/linux/en/download_scn.html)

Any help would be appreciated.

**Comment by siraben** [comment]
Is this still important to you?

**Comment by wizzup** [comment]
@siraben Not much anymore. I have other machine to use the printer with.
