### ISSUE TITLE
wine: WINEARCH set to win64 but '/tmp/prefix' is a 32-bit installation

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#40023]
## Issue description

I want to create 64-bit prefix, but this doesn't work. Looking at the `wineboot` script, there is no `wine64` it calls in the package, so it calls `wine` instead and creates 32-bit prefix.

### Steps to reproduce

```sh
WINEPREFIX="/tmp/prefix" WINEARCH=win64 wineboot
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.38, NixOS, 18.09pre138871.af55a0c3002 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ikervagyok** [comment]
the default as of now is a 32bit install of wine. https://github.com/NixOS/nixpkgs/blob/90cfaf1ab343eeb5dfa80bf56dfc6e66f88e613e/pkgs/misc/emulators/wine/default.nix#L11 is misleading, as it shows a default of `build = winewow` for 64bit systems. but this gets overwritten by default in https://github.com/NixOS/nixpkgs/blob/90cfaf1ab343eeb5dfa80bf56dfc6e66f88e613e/pkgs/top-level/all-packages.nix#L20845

so just set `config.wine.build = "wineWow"` and then rebuild. hope this helps.

**Comment by gnidorah** [comment]
@ikervagyok Thank you!

**Comment by ikervagyok** [comment]
@gnidorah i don't know. i've asked about this in https://github.com/NixOS/nixpkgs/issues/32435 but there was no response. Maybe you could just create a pull request? I'm probably not going to have time for it in the next few even weeks.

**Comment by gnidorah** [comment]
@ikervagyok ok, opened pr https://github.com/NixOS/nixpkgs/pull/43065
