### ISSUE TITLE
gcc8.x86_64-darwin failing

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#40038]
gcc8 is failing on x86_64-darwin:

Job: https://hydra.nixos.org/job/nixpkgs/trunk/gcc8.x86_64-darwin

Not sure what's going on. Clang gives this error:

  clang-5.0: error: unsupported option '--gstabs'

**Comment by dtzWill** [comment]
My favorite is the only other mention in the log is:

```
checking assembler for --gstabs option... no
```

I'm sure there's a reason, but.. LOL.

**Comment by matthewbauer** [comment]
Unless anyone has any ideas, I think I will disable the test for now. We just want to make sure it is fixed when we switch to GCC8.

**Comment by Laaas** [comment]
Any news on this? Seems unfortunate to be stuck on GCC 7 forever.

**Comment by matthewbauer** [comment]
It looks like it was fixed in gcc 8.3.0.
