### ISSUE TITLE
Request: Pure nixos-rebuild mode that ignores current system state.

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#40066]
The problem:

 To this day I am not totally sure what the list of impure references can affect my system build, but I feel they might include:

- My desktop machine channel changing.
- Accidentally leaving NIX_PATH set to something.
- nixpkgs-conf file existing.
- overlays on my system
- others?

The result is that I feel It is difficult to have reproducible server deployments that don't depend on the state of my desktop machine without ad hoc wrapper scripts that wipe NIX_PATH and then re-run nixos-rebuild. Even then I am unsure if i have purged all impurities from my server build, and I suspect many people are doing this their own way with ad hoc scripts, (especially for server deployments).

Perhaps it would be nice if some functionality like this were included in nixos-rebuild

I am imagining something like an option to nixos-rebuild that wipes NIX_PATH and ensures your deployment is totally reproduce-able and can never depend on any state that isn't in a given nix expression.
```
$ nixos-rebuild --pure  ./machine.nix switch
```

machine.nix
```
{
  pkgs = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/b0dac30ab552a59b772b4fe34c494b107fce01e5.tar.gz";
    sha256 = "064vg2m7n92spjzjck3hia38afjpv026641ih0jlh5knsjk099j0";
  };

  config = {config, pkgs, ...}:
  {
    imports = [ "${pkgs}/nixos/modules/virtualisation/google-compute-config.nix" ];
  };
};
```

Feedback?

Another note, https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs could also have a section on "pinning_nixos" which is a similar, but slightly different topic.

**Comment by andrewchambers** [comment]
In the meantime, heres my ad hoc script: 
https://github.com/andrewchambers/nixos-pure-rebuild

**Comment by edolstra** [comment]
I prototyped something like this a while ago using `--pure` mode. The idea is to build from a single Git repository containing a `system.nix` file, which uses `fetchGit` to fetch Nixpkgs and other dependencies. The hash of the top-level repo then uniquely identifies the configuration. 

`system.nix` looks like this:
```
let

  nixpkgs = fetchGit {
    url = https://github.com/NixOS/nixpkgs.git;
    ref = "release-17.09";
    rev = "d9a2891c32ee452a2cd701310040b660da0cc853";
  };

in

(import (nixpkgs + "/nixos") {
  configuration = ./configuration.nix;
  system = "x86_64-linux";
}).system
```
However, this is pretty verbose and having to update hashes of dependencies is annoying. It might be better to use Git externals.

**Comment by andrewchambers** [comment]
@edolstra This approach works, there just is some extra work to do when it comes to deploying and activating. The --target-host and --build-host options of nixos-rebuild are super nice. nixos-rebuild also does some tricks around rebuilding nix, though in practice maybe that doesn't matter much, you would know better.

Another passing thought, if there was a signed database of human readable tags to fixed outputs then  something like:

```
builtins.fetchNixpkgs {
  version = "18.03.132268";
}
```

would work (though I think special casing is bad).

**Comment by samueldr** [comment]
(Triaging)

I'm closing this, as, AFAIUI, using Flakes to build a NixOS system nowadays does what is intended here.

Note that #306099 was opened for the documenting part of this issue.
