### ISSUE TITLE
Remove ~/bin from NixOS path

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#40065]
This is kind of bugging me & I'm interested in seeing if anyone relies on it.

We add ~/bin to PATH in shells-environment.nix.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/shells-environment.nix#L171-L172

IMO we should encourage users to build Nix expressions themselves and avoid hardcoding directories like these.

**Comment by xeji** [comment]
I do need ~/bin in PATH but add it in ~/.bashrc (from a shared dotfiles git repo) anyway,  so on my NixOS systems it currently ends up in PATH twice :smile: . No objections to removing it from shells-environment.nix

**Comment by dezgeg** [comment]
Well, users can use nix-shell shebangs to add their dependencies to their private scripts which works just as well.

Also removing this is a breakage to users using `~/bin`.

**Comment by matthewbauer** [comment]
Does anyone know the original reasoning for including it? I realize now that it's been there for quite a long time & may be worth keeping just for legacy purposes. It's a very nonstandard thing to have in PATH though. Even distros without user package management will not have it set globally by default.

I think occasionally other distros will also add ```$HOME/.local/bin``` to PATH. Would that be an acceptable alternative to ```$HOME/bin```? That would make sense to just put ```$HOME/.local``` into ```environment.profiles``` instead of appending to PATH like it is now.

**Comment by edolstra** [comment]
I use ~/bin and I don't see a compelling reason for getting rid of it. As far as I know it's actually pretty standard and every Unix system I've used had it. Anyway let's keep the gratuitous breakage to a minimum...
