### ISSUE TITLE
Reproducible squashfs

### ISSUE THREAD

**Issue by ruuda** [NixOS/nixpkgs#40144]
## Issue description

The version of `mksquashfs` in nixpkgs is nondeterministic (even when passing `-no-fragments` and `-processors 1`). Squashfs images produced by it are not reproducible. This affects NixOS directly, as iso and netboot images are produced by `mksquashfs`.

The [Reproducible Builds projects recommends](https://reproducible-builds.org/docs/system-images/#squashfs-metadata--compression) three patches that are present in the [squashfskit fork](https://github.com/squashfskit/squashfskit) of squashfs. It looks like the squashfskit repository is a fork of squashfs-tools at `3de1687d74` (one commit after the version currently in nixpkgs), with many patches applied collected from various places, that never got upstreamed to squashfs-tools. In the mean time there was also some activity on squashfs-tools, and the two have diverged.

**What would be the best course of action here? Replace squashfs-tools with squashfskit? Or cherry-pick the reproducibility patches from squashfskit and apply them on top of squashfs-tools?**

### Steps to reproduce

Here is an example that builds a squashfs image. The filesystem contents are reproducible, yet the image file itself is not.

    git clone https://github.com/ruuda/miniserver
    cd miniserver
    git checkout d23dedc48e6981cf589d50231338655f77dac8cb
    nix-build image.nix
    nix-build --check image.nix

After replacing squashfs-tools with squashfskit like below, the image did become reproducible.

```nix
squashfsTools.overrideDerivation (oldAttrs: {
  src = fetchFromGitHub {
    owner = "squashfskit";
    repo = "squashfskit";
    sha256 = "1qampwl0ywiy9g2abv4jxnq33kddzdsq742ng5apkmn3gn12njqd";
    rev = "3f97efa7d88b2b3deb6d37ac7a5ddfc517e9ce98";
  };
})
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.6-1-ARCH, Ubuntu, 16.04.4 LTS (Xenial Xerus)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixpkgs-18.09pre139198.9d0b6b9dfc9"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Any ideas why they haven't been included in squashfs-tools? That would probably help us making that decision. I would say for now just applying the patches make sense although it would be good to see it eventually included as an option in squashfs.

**Comment by ruuda** [comment]
Two of the patches [were proposed on a mailing list](https://sourceforge.net/p/squashfs/mailman/message/34673610/) but received no reply as far as I can see. The squashfs-tools author [said](https://patchwork.kernel.org/patch/9544197/) in a different thread:

> The repo at kernel.org is the official repo.  It hasn't been updated in a while
> simply because the tools are considered stable, and I have not had a burning
> desire to add new features for a while.

I cannot find any attempt to upstream the third patch.

I’ll try to contact the squashfs-tools author and ask if these patches can be included. In the mean time I’ll try to make a pull request to apply them separately in nixpkgs.
