### ISSUE TITLE
Update GHCJS to version based on GHC 8.4

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#40140]
## Issue description

GHCJS has recently been updated to support GHC 8.4. This should be packaged along with the other versions and probably made the default eventually.

https://github.com/ghcjs/ghcjs/issues/602

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Ericson2314** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/40392 Thanks @ElvishJerricco!
