### ISSUE TITLE
Improving unixtools

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#40162]
I'm still looking on improving ```unixtools``` & getting better portability for packages that use them. Right now Linux still uses the original version of ```utillinux```, ```nettools```, & ```procps```. I want to look into replacing those "raw" versions with the unixtools compatible version. This could break some Linux-specific uses of these commands, but also make it easier for Linux users to spot where their package is not portable to macOS. Before this is possible I have a TODO list of things:

- [ ] Provide man page from ```posix-man-pages``` for each command (we don't want to show Linux-specific or BSD-specific flags).
- [ ] Wrap each Unix tool so that it fails when non-Unix "flags" are used.

For instance, with ```ps```, the POSIX man page defines these flags:

```
-a
Write information for all processes associated with terminals. Implementations may omit session leaders from this list.
-A
Write information for all processes.
-d
[XSI] [Option Start] Write information for all processes, except session leaders. [Option End]
-e
[XSI] [Option Start] Write information for all processes. [Option End] (Equivalent to -A.)
-f
[XSI] [Option Start] Generate a full listing. (See the STDOUT section for the contents of a full listing.) [Option End]
-g  grouplist
[XSI] [Option Start] Write information for processes whose session leaders are given in grouplist. The application shall ensure that the grouplist is a single argument in the form of a <blank> or comma-separated list. [Option End]
-G  grouplist
Write information for processes whose real group ID numbers are given in grouplist. The application shall ensure that the grouplist is a single argument in the form of a <blank> or comma-separated list.
-l
[XSI] [Option Start] Generate a long listing. (See STDOUT for the contents of a long listing.) [Option End]
-n  namelist
[XSI] [Option Start] Specify the name of an alternative system namelist file in place of the default. The name of the default file and the format of a namelist file are unspecified. [Option End]
-o  format
Write information according to the format specification given in format. This is fully described in the STDOUT section. Multiple -o options can be specified; the format specification shall be interpreted as the <space>-separated concatenation of all the format option-arguments.
-p  proclist
Write information for processes whose process ID numbers are given in proclist. The application shall ensure that the proclist is a single argument in the form of a <blank> or comma-separated list.
-t  termlist
Write information for processes associated with terminals given in termlist. The application shall ensure that the termlist is a single argument in the form of a <blank> or comma-separated list. Terminal identifiers shall be given in an implementation-defined format. [XSI] [Option Start]  On XSI-conformant systems, they shall be given in one of two forms: the device's filename (for example, tty04) or, if the device's filename starts with tty, just the identifier following the characters tty (for example, "04" ). [Option End]
-u  userlist
[XSI] [Option Start] Write information for processes whose user ID numbers or login names are given in userlist. The application shall ensure that the userlist is a single argument in the form of a <blank> or comma-separated list. In the listing, the numerical user ID shall be written unless the -f option is used, in which case the login name shall be written. [Option End]
-U  userlist
Write information for processes whose real user ID numbers or login names are given in userlist. The application shall ensure that the userlist is a single argument in the form of a <blank> or comma-separated list.
```

If any flag outside of these are used, we would prefer it to error everywhere, even on Linux when additional flags are available. This would mean that Linux users wouldn't have to guess at what support exists on macOS.

**Comment by coretemp** [comment]
It's not clear to me what you think you should happen if I write `man ps` on a future version of my system.

For context from my system:
```
/run/current-system/sw/bin/ps: symbolic link to /nix/store/awsi1h746ian2afdmrhpw8ajkn0gsavb-procps-3.3.12/bin/ps
```

Writing portable software is useful, but your method of achieving that goal is too agressive. If I would design this feature, there would be a NixOS module allowing one to specify ```encouragePortability = true;``` which would then mark the non-portable bits of a man page, but it would not display just the portable parts. 

Additionally, I think it would be more useful to port the non-portable features.

Introducing breakage is not acceptable. Trust me, if you build something that is better (like perhaps the nix single binary allvm thing might become), I will use it. Just removing features because *you* think that's best for everyone is not cool. Breakage means that somewhere someone is paying for it and all because you didn't want to properly introduce a new feature (which means keeping compatibility). There is a well established process for breaking compatibility, it's called introducing a newly named tool (see python2/python3).
