### ISSUE TITLE
-Werror=format-security for default gcc flags

### ISSUE THREAD

**Issue by bfrog** [NixOS/nixpkgs#40182]
## Issue description
It seems as if -Werror=format-security is added somewhere, somehow, to gcc flags. This causes 
https://www.zephyrproject.org/ to fail to build on my local machine.

### Steps to reproduce

Use a default.nix with nix-shell with stdenv, ncurses, and cmake.

``` sh
git clone https://github.com/zephyrproject-rtos/zephyr
cd zephyr
mkdir build
cd build
cmake ../scripts
make
```

## Technical details

nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.03.132275.2352d46904d (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by globin** [comment]
You can set `hardeningDisable = [ "format" ];` or `export hardeningDisable=format`
