### ISSUE TITLE
pgrep and pkill segfault when no pattern is given

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#40208]
## Issue description
```
[linus@sudoku:~]$ nix-shell -I nixpkgs=channel:nixos-unstable -p procps --run 'pgrep -G nixbld'
/tmp/nix-shell-27800-0/rc: line 1: 28280 Segmentation fault      pgrep -G nixbld
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.15, NixOS, 18.03.132217.c56ebaba1b0 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03, nixos-unstable-18.09pre137207.92f0d31b949"`
 - channels(linus): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Note that the issue *only* occurs on the current nixos-unstable (1d9330d63a5), not 18.03.

**Comment by matthewbauer** [comment]
I think it's this issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894917

Should be fixed in 38ef327aec2d59e484438c36851c0c3ac930ca7a & currently on staging.

**Comment by lheckemann** [comment]
Thanks for tracking that down!

**Comment by matthewbauer** [comment]
Fixed in master.
