### ISSUE TITLE
Fontconfig warning: "/etc/fonts/fonts.conf": blank doesn't take any effect anymore

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#40219]
## Issue description

```
Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
```

```
$  file /etc/fonts/fonts.conf 
/etc/fonts/fonts.conf: symbolic link to /nix/store/vyihrsb0xl42gdk7qvvvza0chj09a54q-fonts.conf
```
### Steps to reproduce
```
if grep -q blank /etc/fonts/fonts.conf; then
echo it is still broken
else
echo you fixed it
fi
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.git.2352d46 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
Which app were you running when this warning happened? According to @vcunat, ```/etc/fonts/2.11/fonts.conf``` should be found with the newer fontconfig. This could be a bug in how the app is using fontconfig.

See #24596.

**Comment by vcunat** [comment]
Well, any fontconfig without our patches would look into `/etc/fonts/fonts.conf` instead (regardless of version).  That would affect packages that bundle it, be it in binary or source form.

**Comment by vadzimt** [comment]
@matthewbauer I am seeing exact same message when running Google Chrome on latest stable NixOS.

**Comment by coretemp** [comment]
Opera has the same problem.

If there are so many buggy apps, perhaps we should just help the apps a bit by having some wrapper which remaps the file system?

**Comment by rileyinman** [comment]
This is still an issue for me on a couple applications I have to use from .deb packages. Since there is no source available, it hasn't been updated in a while, and I can't easily patch it myself, I'm currently a bit stuck.

**Comment by mhwombat** [comment]
I'm getting the same warning with `meld` and `okular`.

**Comment by mmlb** [comment]
ditto with chromium

**Comment by ogkloo** [comment]
I have this with UnityHub

**Comment by jtojnar** [comment]
This should be fixed as of https://github.com/NixOS/nixpkgs/pull/97441.
