### ISSUE TITLE
texlive: 2017 -> 2018,  document update process

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#40232]
TeX Live 2018 is out.

As is not obvious how to do update texlive using the scripts in `pkgs/tools/typesetting/tex/texlive`,
a short README documenting the update process would be helpful.

cc maintainers @vcunat @lovek323 @7c6f434c @jwiegley and @veprbl who did the last bump.

**Comment by bhipple** [comment]
It looks like whoever does this may have to spend some time updating the inter-dependencies between the various `bin.nix` packages to get them to build.  I gave it a shot and it doesn't appear trivial, plus there's the whole `pkgs.nix` CTAN distribution to consider.

**Comment by xeji** [comment]
In staging now, keeping this open until it hits master.

**Comment by xeji** [comment]
cherry-picked to staging-18.09  in 1845c6e3f75..f3ed8122dc6

**Comment by xeji** [comment]
It's in release-18.09 now :smile:
