### ISSUE TITLE
GNOME: no way to log out a user

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#40249]
## Issue description

There is no way to logout in the GNOME desktop (GUI at least).

I would expect a "logout" icon near "power off" in the top right menu.

The search shows a gnome shell extension. We might need that.

![logout](https://user-images.githubusercontent.com/91113/39839891-e88ec296-53dd-11e8-88da-3cd30ac4ad8f.png)

### Steps to reproduce

1. use gnome desktop
2. try to logout current session

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.03.132275.2352d46904d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132275.2352d46904d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
It is only shown when you have multiple users:

![image](https://user-images.githubusercontent.com/705123/39841933-d438bdfe-53e4-11e8-9e3d-fade40ae0b96.png)

Of the two extensions that support this, the better looking one is [currently broken](https://gitlab.com/paddatrapper/log-out-button-gnome-extension/issues/4).

**Comment by davidak** [comment]
There are situations where you want to log out and log back in for changes to take effect, for example for apps installed with Nix to show up in app menu. So, not the best UX.

We could document: "How do i get a logout button?" in NixOS doc or wiki

**Comment by jtojnar** [comment]
For apps, you can do <kbd>alt</kbd>-<kbd>F2</kbd>, type `r`, and press <kbd>Enter</kbd>. Though new GNOME session is still needed for some things, so we need the extension. It would be better to figure out how to swap the environment during switch, though.
