### ISSUE TITLE
pgmanage docs "installed as" incorrect (minor)

### ISSUE THREAD

**Issue by ariutta** [NixOS/nixpkgs#40247]
## Issue description

The pgmanage man pages say this:

>FULL PATH
 >      This instance of pgmanage was installed as /usr/local/sbin/pgmanage (Usually /usr/local/sbin/pgmanage)

but it's actually installed as `/nix/store/rahc3ms3iy4sfylr3kvl8c7wxiz1bhgy-pgmanage-10.0.2/bin/pgmanage`

Minor issue but just wanted to log it.

### Steps to reproduce

Install pgmanage and look at the man pages:
```
nix-env -iA nixos.pgmanage
man pgmanage
/FULL
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(andersriutta): `"nixos-17.09.3243.bca2ee28db4, nixpkgs-18.09pre139064.27eb2859f27"`
 - channels(root): `"nixpkgs-18.03pre122585.b212125b541"`
 - nixpkgs: `/Users/andersriutta/.nix-defexpr/channels/nixpkgs`

**Comment by xeji** [comment]
cc maintainer @basvandijk
