### ISSUE TITLE
GNOME: "Packages" and "Package Updater" useless

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#40254]
## Issue description

![packages](https://user-images.githubusercontent.com/91113/39840517-f3bd914a-53df-11e8-960f-a75b2f130a6a.png)

I think this programs don't make sense when we have Nix.

Also, they are empty:

![screenshot from 2018-05-09 20-41-06](https://user-images.githubusercontent.com/91113/39840539-0b73c28c-53e0-11e8-8897-046db36a8bef.png)

### Steps to reproduce

1. open programs from gnome launcher
2. question their necessity

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.03.132275.2352d46904d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132275.2352d46904d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
I am not really sure what purpose these programs have. Maybe they would be useful with the [Nix packagekit backend](https://github.com/NixOS/nixpkgs/issues/21230).

**Comment by davidak** [comment]
Maybe. A clue is that the name is linked to the PackageKit page on [Wikipedia](https://en.wikipedia.org/wiki/GNOME_Core_Applications#System). I don't find any information on GNOMEs website.

**Comment by jtojnar** [comment]
```ShellSession
$ readlink -f $(which gpk-application)
/nix/store/27djgnchrg3vd1d6r23ffbh4h8crg80d-gnome-packagekit-3.28.0/bin/gpk-application
$ readlink -f $(which gpk-update-viewer)
/nix/store/27djgnchrg3vd1d6r23ffbh4h8crg80d-gnome-packagekit-3.28.0/bin/gpk-update-viewer
```

**Comment by davidak** [comment]
Great, then this report is just a note that this apps have currently no function, but will have when https://github.com/NixOS/nix/issues/233 is done. (or https://github.com/NixOS/nixpkgs/issues/21230 is fixed)
