### ISSUE TITLE
GNOME: no suspend or hibernate from menu

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#40251]
## Issue description

there is **only restart** and **power off**.

the search show a related gnome shell extension. we might need that.

![suspend](https://user-images.githubusercontent.com/91113/39839982-37be47a6-53de-11e8-9799-264684236a03.png)

similar to https://github.com/NixOS/nixpkgs/issues/40249

### Steps to reproduce

1. use gnome desktop
2. try to **suspend** or **hibernate** from menu

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.03.132275.2352d46904d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132275.2352d46904d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
The suspend is shown when you hold the shutdown button pressed. Not sure about hibernation, I was not able to make it work on my hardware.

**Comment by Ortega-Dan** [comment]
Hi, 
If your system is already supporting hibernation (let's say it actually hibernates after executing in terminal: systemctl hibernate) then you are able to create a .desktop file with the hibernation and place it in your .local/share/applications under your user's home directory .... then you can hibernate from the search ..
![image](https://user-images.githubusercontent.com/24926168/74068101-be1bc800-49c8-11ea-8803-d2c057386d49.png)


Being more specific what you do is:
first open a terminal and make sure you are able to actually hibernate
![image](https://user-images.githubusercontent.com/24926168/74068155-ea374900-49c8-11ea-91c5-e297f9687274.png)

if so ... just create a text file called: hibernate.desktop with the following content:
## content starts here:
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=System Hibernate
Exec=systemctl hibernate
Icon=/your/own/path/to/the/image/you/are/going/to/use/as/icon.png
## content ends here

Then place that file under /home/[replaceByYourUsername]/.local/share/applications

And then you are able to hit search look for hiber... and hit enter.
