### ISSUE TITLE
dit: render issues (ncurses)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#40305]
## Issue description

I noticed that the output get's corrupted when i used PAGE-UP und PAGE-DOWN to navigate through files. Then sometimes characters stay on the display where other should be...

https://asciinema.org/a/V0gEYXLSzOQuJ05PtFicGPCAk

visible at 0:32 and 3:56.

@matthiasbeyer is that similar to https://github.com/NixOS/nixpkgs/issues/29355?

here is my upstream bugreport: https://github.com/hishamhm/dit/issues/30

the maintainer asks:

>I've had htop users in the past who had similar weird problems when their libncurses version did not match the version of their ncurses headers. Do you happen to have multiple ncurses versions installed?

i think with nix, only the specified dependencies should be visible to the application, right?

for htop, we don't have any special fixes. https://github.com/NixOS/nixpkgs/blob/release-18.03/pkgs/tools/system/htop/default.nix

### Steps to reproduce

1. open text file in dit
2. scroll und and down

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.03.132275.2352d46904d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03.132275.2352d46904d, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by davidak** [comment]
@matthiasbeyer no difference.

I'm using NixOS 18.03, which has `ncurses-6.0-20171125` and install dit from master, what has `ncurses-6.1`.

So could it be possible that the "libncurses version did not match the version of the ncurses headers." because dit uses the system version instead of the one specified as dependency?

**Comment by matthiasbeyer** [comment]
> So could it be possible that the "libncurses version did not match the version of the ncurses headers." because dit uses the system version instead of the one specified as dependency?

No. Nix is there to prevent exactly this. I don't know how to go on, sorry. And I am leaving for a sabatical tomorrow, so I guess someone else has to help you. Sorry!

**Comment by davidak** [comment]
@matthiasbeyer no problem. have a great time!

**Comment by vcunat** [comment]
Some other ncurses stuff is broken for me but works inside plain `xterm`.

**Comment by c0bw3b** [comment]
@davidak still an issue on 18.09 with newer ncurses? i.e. 6.1

**Comment by davidak** [comment]
@c0bw3b i was not able to reproduce it in a quick test. Thanks for the reminder.

I use [micro](https://micro-editor.github.io/) now.
