### ISSUE TITLE
meson could be bumped from 0.44.0 to 0.46.0

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#40422]
## Issue description

meson is on version 0.44.0 in nixpkgs. There already is a version 0.46.0.
Sadly there is a bug in meson 0.44.0 , which hinders me from packaging with it (the problem is with https://github.com/sardemff7/eventd, I have a workaround, but it's not nice). That bug is already fixed in meson 0.44.1. It would be nice if someone came around for a version bump.

Sadly that will probably trigger a lot of package rebuilding …

**Comment by jtojnar** [comment]
We have meson 0.45.1 in `nixos-unstable`.

Feel free to open a pull request with 0.46.0. Usually, trying to build just a few dependent packages (e.g. `systemd`, `json-glib`, `colord`, `appstream-glib`) should be enough.

**Comment by maralorn** [comment]
Oh, sorry. I failed to pull before checking. 0.45.1 suffices for me. Thank you!
