### ISSUE TITLE
Kitty doesn't work when installed via nix-env but works if installed via configuration.nix

### ISSUE THREAD

**Issue by sondr3** [NixOS/nixpkgs#40448]
## Issue description
I've been meaning to try out Kitty as my terminal emulator but ran into an issue where it refuses to launch because `LC_ALL` has no value.

```sh
$ kitty
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[133 18:38:33.929728] Traceback (most recent call last):
  File "/nix/store/fyf9ra3nsbqkn6hxvkl904x71s4fm873-kitty-0.9.1/bin/../lib/kitty/kitty/main.py", line 180, in main
    _main()
  File "/nix/store/fyf9ra3nsbqkn6hxvkl904x71s4fm873-kitty-0.9.1/bin/../lib/kitty/kitty/main.py", line 114, in _main
    locale.setlocale(locale.LC_ALL, '')
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

And `locale` shows:

```sh
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Now, this only happens when I install it as a user with `nix-env -iA unstable.kitty` and not when I declare it in my `configuration.nix` file. Any ideas on how to fix this?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.40, NixOS, 18.03.132336.ef74cafd3e5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(sondre): `"unstable-18.09pre139929.c839771129f"`
 - channels(root): `"nixos-18.03.132336.ef74cafd3e5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
I think this is from #38991. Can you try installing via ```nix-env -iA nixos.kitty``` to verify that works?

**Comment by sondr3** [comment]
And now Kitty has been updated in the `nixos` branch to be version `0.9.1` and has stopped working :cry:

**Comment by sondr3** [comment]
Nevermind, yeah, not sure why it was upgraded.

**Comment by Luflosi** [comment]
Can this issue be closed?

**Comment by sondr3** [comment]
Yep!
