### ISSUE TITLE
stripHash documentation functionality mismatch

### ISSUE THREAD

**Issue by Davorak** [NixOS/nixpkgs#4045]
[stripHash documentation](https://github.com/NixOS/nixpkgs/blob/15bb4c20e614ed6835c59c7c9101ee59eacbe473/doc/stdenv.xml#L1079) states that it prints out the stripped name to the `stdout`, but the [current function](https://github.com/NixOS/nixpkgs/blob/15bb4c20e614ed6835c59c7c9101ee59eacbe473/pkgs/stdenv/generic/setup.sh#L432) stores the value in `strippedName` instead.

The functionality in the documentation seems more convenient is there a reason not to switch to it?

**Comment by Profpatsch** [comment]
This one is interesting. There are maybe two dozen uses of that function, but it would be nice to change it. Maybe I’ll look into it tomorrow. Always happy to trigger a mass rebuild. :P

**Comment by Profpatsch** [comment]
Was fixed in the meantime.
