### ISSUE TITLE
nixos-unstable channel ist stuck, hydra eval fails (too many heap sections)

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#40456]
## Issue description

`nixos-unstable` channel is stuck since, for the last 5 days, every single Hydra eval of the `nixos:trunk-combined` has failed with

```
hydra-eval-jobs returned signal 6:
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

See https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors (ignore the ugly `stateVersion` warnings, they're harmless). 

I have opened https://github.com/NixOS/hydra/issues/557 but I'm opening this here as well since I'm not really sure whether this is an issue with hydra, the configuration of our jobset, nixpkgs, nix, or a combination thereof.

Same thing happens for `release-18.03` as well, but only for about 50% of evals. Different settings?
Or maybe `release-combined.nix` is slowly growing too large for a monolithic eval? 

Hope that someone familiar with our Hydra infrastructure can help.

cc @vcunat @srhb

**Comment by vcunat** [comment]
I guess it's either just progressively growing larger or some large jump that dealt the killing blow.

**Comment by xeji** [comment]
Let's hope that we can somehow fix it by giving it more memory. Do you know where to find these
`MAXHINCR or MAX_HEAP_SECTS` settings ? I guess they're somewhere deep down in nix. Couldn't find anything in the docs or in the nix or hydra code.

**Comment by matthewbauer** [comment]
Actually are we sure that he stateversion is harmless? There are tons of them. Maybe someone can try reverting that change.

**Comment by xeji** [comment]
> Actually are we sure that he stateversion is harmless? 

Yes. They're caused by nixos test VMs not having `system.nixos.stateVersion` set in their config.
I'm working on a fix. Unrelated to the eval failures, which were there for days before that warning was activated.

**Comment by xeji** [comment]
@matthewbauer  88fa50c2f2bbc472fe7169eac8f2a1b2312ef03b should eliminate most of the stateVersion warnings from eval, I'll take care of the rest soon.

**Comment by matthewbauer** [comment]
Thanks!

**Comment by matthewbauer** [comment]
It looks like it started one again 9h ago:

https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

**Comment by vcunat** [comment]
I just hope it wasn't just some random success.  One evaluation per week wouldn't be fast enough.

**Comment by srhb** [comment]
Indeed, was anything done to fix this or is it just a random success,in which case we should not close the issue? I heard about some Hydra patches but neither this issue nor the linked one mentions anything.

**Comment by srhb** [comment]
Last evaluation has:

```
Errors occurred at 2018-05-17 02:57:40.

hydra-eval-jobs returned exit code 1:
GC Warning: Failed to expand heap by 10737418240 bytes
Can't start up: not enough memory
```

**Comment by xeji** [comment]
Someone appears to have changed memory parameters (but no idea who did what exactly):
After succeding once, the next eval  of `nixos:trunk-combined` failed with
```
hydra-eval-jobs returned exit code 1:
GC Warning: Failed to expand heap by 10737418240 bytes
Can't start up: not enough memory
```

I guess our Hydra infrastructure needs a RAM upgrade after all....

**Comment by xeji** [comment]
@srhb great parallel processing :smile:

**Comment by srhb** [comment]
Yeah, if only we didn't process the same thing! :roll_eyes: :smile:

**Comment by xeji** [comment]
Has been ok for a few days now. Fingers crossed.
