### ISSUE TITLE
DMD or related packages are broken on NixOS 18.09

### ISSUE THREAD

**Issue by AdrianVovk** [NixOS/nixpkgs#40461]
## Issue description

dmd/druntime/phobos (Not exacly sure which one - I don't know the language) fails to build.

I tried to install Tilix on NixOS 18.09 and it fails with [this log](https://pastebin.com/sTkAWeaf). I know nothing about D so I cannot give many more details. I do not know exactly where or why it fails.

### Steps to reproduce

Try to install tilix on NixOS 18.09. It will fail because dependencies failed to build.

## Technical details
```
Please warning: Nix search path entry '/home/adrian/.nix-defexpr/channels' does not exist, ignoring
warning: Nix search path entry '/home/adrian/.nix-defexpr/channels' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.09pre139651.6db7f92cc2a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos"`
 - channels(adrian): `""`
warning: Nix search path entry '/home/adrian/.nix-defexpr/channels' does not exist, ignoring
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by AdrianVovk** [comment]
This renders my system virtually unusable, since not having my terminal completely ruined my workflow. I'm rolling back my Nix installation, but I will need the configuration changes I applied. Please fix this. I do not understand why it is building in the first place. Isn't the cache supposed to handle that? Also, how did a broken package make it into nixpkgs. Doesn't hydra check for that?

I appologise for my rant. It's just frustrating that I cannot have both my workflow and the changes necessary to build my projects (allowing me to change brightness without sudo) at once. Isn't NixOS supposed to alleviate these things? I understand that I am using the unstable branch, but, as I understood, that does not invalidate any of the protections set into place to stop broken packages from shipping. Am I missing something here?

**Comment by xeji** [comment]
Unfortunately, it looks like `dmd`, which is a dependency of `tilix`, has been broken on `master` since April 11. 



> Is this somehow related to #40456?

No. This issue just means that the `nixos-unstable` channel has not advanced since a week ago.

**Comment by xeji** [comment]
Maybe  dmd maintainer @ThomasMader can help.

**Comment by AdrianVovk** [comment]
@xeji I mean is the fact that a a package somehow broke on Nix related to that issue?

**Comment by AdrianVovk** [comment]
@xeji Alright I see now. Aren't the stable channels fixed to a single version and just recieve maintenance/security updates? It'd be awesome if there was a rolling-esqe release model (like unstable) that actually checked all of the packages. Therefore there could be new versions for people that want it but not breaking changes that stop a nixos-rebuild.

**Comment by xeji** [comment]
> Aren't the stable channels fixed to a single version and just recieve maintenance/security updates? 

Yes, but there's a stable release every 6 months, so it doesn't become too outdated.

>  It'd be awesome if there was a rolling-esqe release model (like unstable) that actually checked all of the packages.

That may be possible but not easy to implement, and that's a general policy question rather outside the scope of this specific issue...

**Comment by ThomasMader** [comment]
The problem of the log will be fixed with https://github.com/NixOS/nixpkgs/pull/40228.
But as can be seen in that PR there are two more problems.

The first is no problem as long as nix 2.0.2 is used. See https://github.com/NixOS/nix/issues/2155#issuecomment-389191846
This issue is independent of the branch to be built.

The second is branch dependent and is only happening on master and not on stable. The problem was the update of binutils to version 2.30. See https://github.com/NixOS/nixpkgs/issues/40397 for details.

**Comment by AdrianVovk** [comment]
@ThomasMader any progress on the fix?

**Comment by ThomasMader** [comment]
Yes everything is fixed now. https://github.com/NixOS/nixpkgs/pull/40228 just needs to be merged.

**Comment by AdrianVovk** [comment]
@ThomasMader Awesome! Thank you. It looks like this was already merged. I'm closing this issue.
