### ISSUE TITLE
GSConnect GNOME Shell extension unable to find typelib

### ISSUE THREAD

**Issue by tiramiseb** [NixOS/nixpkgs#40474]
## Issue description

After manually installing the gsconnect@andyholmes.github.io GNOME extension on my account (from a package that is more recent than the one on extensions.gnome.org : see , I get the following error in the logs, and the extension is not working:
```
mai 13 18:15:18 sebastien gjs[10146]: JS ERROR: Error: Requiring GjsPrivate, version none: Typelib file for namespace 'Gtk', version '3.0' not found
                                      @resource:///org/gnome/gjs/modules/gettext.js:39:7
                                      @/home/sebastien/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:5:7
```

If I manually start `daemon.js` and then restart GNOME Shell, it works. Looks like it may be related to how the environment is different for GNOME Shell itself (like I already encountered for the system-monitor extension for example).

There is an issue upstream here:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/77#issuecomment-388637385

@jtojnar maybe you can help?

### Steps to reproduce

Install the GSConnect extension, restart GNOME Shell.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.09.git.6db7f92 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-17.09.3047.8bce347f02f"`
 - nixpkgs: `/home/sebastien/Code/nixpkgs-channels` (which is a local clone of `nixos-unstable`).

**Comment by tiramiseb** [comment]
Haaaa sorry I haven't looked hard enough, I didn't see you have already worked on the subject (https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/91).

**Comment by jtojnar** [comment]
@hedning You would need to wrap the `@DATADIR@/service/daemon.js`, and remove `gjs` from `Exec=` in the `.desktop` and `.service` files.

Hopefully, the upstream will be more packaging friendly, now that the extension is [considered for inclusion into Ubuntu](https://www.omgubuntu.co.uk/2018/05/ubuntu-18-10-gsconnect-extension-by-default).

cc @etu, who tried to package this.

**Comment by etu** [comment]
Yeah, I took a shot at this as well...

@jtojnar That link is great news for us as well I'd say :smile:

**Comment by mickours** [comment]
Is someone have a working configuration for this GsConnect extension in the end?

**Comment by cyplo** [comment]
Heya ! Is this still an issue ? If so - is there an existing configuration that someone has that would work or is there something else that we need to do to fix this ? Thanks !

**Comment by hedning** [comment]
This should just work now by installing `gnomeExtensions.gsconnect` (on 19.03 or unstable).

**Comment by jtojnar** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/47059.

`environment.systemPackages = [ pkgs.gnomeExtensions.gsconnect ];` should work.

**Comment by Fresheyeball** [comment]
I just got this error on 19.03 with the above code to include gsconnect

**Comment by jtojnar** [comment]
Could you please share a whole error message logged in the journal?
