### ISSUE TITLE
modprobe can't load module: modules.dep missing on linuxManualConfig

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#40485]
## Issue description
I first  ran into this error with a custom kernel:
```
modprobe tcp_probe
modprobe: FATAL: Module tcp_probe not found in directory /run/current-system/kernel-modules/lib/modules/4.9.87
```
I looked up in the folder and found `/run/current-system/kernel-modules/lib/modules/4.9.87/kernel/net/ipv4/tcp_probe.ko.xz`. I looked it up and for some reason it had CONFIG_MODULE_COMPRESS set to y: https://unix.stackexchange.com/questions/308870/how-to-load-compressed-kernel-modules-in-ubuntu

Regarding modprobe config, I suppose it should have been possible to load the module according to its config so I am not sure why it couldn't. Does nixos do anything fancy with kmod ?
```
modprobe -V
kmod version 25
+XZ -ZLIB -EXPERIMENTAL
```

### Steps to reproduce
compile a kernel with 
```
CONFIG_MODULE_COMPRESS=y
CONFIG_MODULE_COMPRESS_XZ=y
```
load a not builtin module.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.7, NixOS, 18.09.git.94593f6 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - nixpkgs: `/home/teto/nixpkgs`
```

**Comment by teto** [comment]
The answer seems to be in the previous link: https://unix.stackexchange.com/questions/308870/how-to-load-compressed-kernel-modules-in-ubuntu since I can insmod the compressed module and do the other operations as listed by the op. Thus I tried to run depmod to fix the problem but then depmod seems to look at the wrong path
```
$ depmod 
depmod: ERROR: could not open directory /lib/modules/4.9.87: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
```

**Comment by dezgeg** [comment]
Kernel module compression has been on for quite long (since 48f51f118506db271567cc19739bc6e66edb6483) so it's probably a red herring.

**Comment by dezgeg** [comment]
I see on a stock kernel:
````
[tmtynkky@jetson:~]$ ls /run/current-system/kernel-modules/lib/modules/4.14.39/
kernel  modules.alias  modules.alias.bin  modules.builtin  modules.builtin.bin  modules.dep  modules.dep.bin  modules.devname  modules.order  modules.softdep  modules.symbols  modules.symbols.bin
````

Presumably `linuxManualConfig` is broken then.
