### ISSUE TITLE
smbldaptools package is trying to look for configuration files within /nix/store 

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#40504]
## Issue description

I've installed `smbldaptools` by adding them into `configuration.nix`.

Now when I'm trying to invoke them I'm getting a weird error message:
```
[root@central:/etc/nixos]# smbldap-populate
Unable to open /nix/store/mrfpnr5lfh93csz8yz92crds1vp20hm7-smbldap-tools-0.9.11/etc/smbldap-tools/smbldap.conf for reading !
Compilation failed in require at /nix/store/mrfpnr5lfh93csz8yz92crds1vp20hm7-smbldap-tools-0.9.11/sbin/.smbldap-populate-wrapped line 30.
BEGIN failed--compilation aborted at /nix/store/mrfpnr5lfh93csz8yz92crds1vp20hm7-smbldap-tools-0.9.11/sbin/.smbldap-populate-wrapped line 30.
```

So, these paths are hardcoded and cannot be modified. I'm not sure what is the "right approach" of doing things in this situation but seems like the only thing I can do is to edit config files in-place, at their `/nix/store` locations. Is that ok?..

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.03.132304.45cd6090d9a (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132304.45cd6090d9a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by matthewbauer** [comment]
So usually this is solved by adding something like ```--confdir=/etc``` to configureFlags.

The problem right now is I can't downloaded the source url. Can you find a working mirror for this? GNA.org is no longer around.

**Comment by pshirshov** [comment]
https://src.fedoraproject.org/lookaside/pkgs/smbldap-tools/smbldap-tools-0.9.11.tar.gz/md5/e3ce9034922175087bb4fbcd3ca50368/ ?

**Comment by c0bw3b** [comment]
Closing as "wontfix" since this is legacy software that disappeared.
Plus it was Samba3-only and one should use Samba4 now.
