### ISSUE TITLE
Add nix->plist serialization functions

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#40508]
## Issue description
@LnL7 has nice serialization code for turning nix data into Apple's `plist` file format. I've extended it slightly here: https://github.com/LnL7/nix-darwin/pull/78

Could we put this in `nixpkgs` somewhere? If so, where?

**Comment by 3noch** [comment]
cc @ElvishJerricco

**Comment by matthewbauer** [comment]
We do this in xcbuild but it’s not exported (yet)

**Comment by 3noch** [comment]
More importantly, does nix->json->plist support all plist data types? I like the direct approach because we have full power of plist format if we need it.

**Comment by matthewbauer** [comment]
I think it supports everything toJSON supports. The only thing I recall missing were XML attributes.

I think this stuff should go in lib/generators.nix though. You can also rewrite xcbuild to use it if you wish.

**Comment by 3noch** [comment]
Hm, how do you represent `<real>` in JSON? Good point about attrs. My additions don't go that far but could be the beginning of adding features for that if needed.

**Comment by matthewbauer** [comment]
Well you can do doubles in JSON and I think that converts to <real></real>. The two that it looks like are missing are data & date.

**Comment by matthewbauer** [comment]
This works for me:

```
with import <nixpkgs> {};
writeText "test" (builtins.toJSON {
  a = 0.33333333333333333333333333333333333;
})
```

It truncates at like 6 digits, so not a real double I guess.

**Comment by 3noch** [comment]
This magic must be new in nix 2.0. I didn't realize floating numbers were a thing...

**Comment by cbarrett** [comment]
Probably the least lossy way to encode a date in JSON to a string following ISO8601. For data I'd suggest an array of bytes (or words) encoded as hex digits? So for bytes that's two digits, for 4-byte word that's 8 digits.

**Comment by 3noch** [comment]
The extensions I added allow you to write arbitrary tags so no need to lose anything.
