### ISSUE TITLE
staruml fails to export as pdf, jpeg and png

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#40503]
## Issue description
When trying to export a diagram as jpeg and png, the following error appears:

![latest-screenshot](https://user-images.githubusercontent.com/1181362/40004404-e999c6ac-5795-11e8-9901-f4b4f33b6718.png)

For search engines: Failed to export diagram (Error=Max connection attempts reached)

On the staruml forums it is suggested to reboot the machine and/or restart startuml, however that doesn't do the trick here.

I also found that when run via the terminal it will print the following error at startup:
```
staruml the Node process failed to start: No such file or directory
```

### Steps to reproduce
1. Create a new diagram
2. Attempt File ->Export Diagram as... -> *Select jpeg or png*, choose a filename and store
3. See error

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.132268.5f16ba8fb0f (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `"nixos-18.03.132268.5f16ba8fb0f, nixos-unstable-18.09pre139319.1d9330d63a5"`
 - channels(steveej): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bwzhang2011** [comment]
6.0.1 repeat the same thing please verify and release new version to solve that problem
