### ISSUE TITLE
nice to have: spectre checker as a module

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#40515]
## Issue description
spectre checker requires one to load the `cpuid` module for best results. If spectre checker would be a module, users wouldn't need to know that. 

Similar for the requirement to have readelf (binutils package) available, which is a missing dependency of the spectre checker script.

Preferred interface is the standard `programs.spectre*.enable = true;` interface
 
I already have this working on my machine, so this is just a "nice to have"-thing. 

## Technical details

Applies to 18.03 and `master`.

**Comment by dotlambda** [comment]
Are referring to spectre-meltdown-checker? I'm running `sudo spectre-meltdown-checker` without cpuid loaded and I don't get an error message. What's the output you're getting? Which version of the script are you running using which command?

**Comment by coretemp** [comment]
Yes, it's an optional dependency, btw. 

I just ran `sudo spectre-meltdown-checker`.

IIRC, it was: https://github.com/speed47/spectre-meltdown-checker/blob/master/spectre-meltdown-checker.sh#L1497.

**Comment by dotlambda** [comment]
@coretemp Interested in writing such a module? Should be doable in a few minutes.
