### ISSUE TITLE
Configuration not kept after reboot

### ISSUE THREAD

**Issue by Semantimancer** [NixOS/nixpkgs#40533]
## Issue description

I added google-play-music-desktop-player to my configuration.nix, ran nixos-rebuild switch, and was able to use the program as normal. When I shut the computer down and reboot, however, I am unable to call it up until I run nixos-rebuild switch again.

[My configuration.nix](https://github.com/Semantimancer/dotfiles/blob/master/Irmo_configuration.nix)

[Original post post on the issue (reddit)](https://www.reddit.com/r/NixOS/comments/8jfuuw/configuration_not_taking/)

### Steps to reproduce

Add google-play-music-desktop-player to configuration.nix
`nixos-rebuild switch`
`google-play-music-desktop-player` (it works)
`reboot`
`google-play-music-desktop-player` ("command not found" error)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.37, NixOS, 18.03.132192.ce0d9d638de (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
After nixos-rebuild, can you figure out the location of google-music-player-desktop-player? I wonder if it is somehow installed in some directory that is getting removed.

```
command -v google-music-player-desktop-player
```

**Comment by Semantimancer** [comment]
Some of the folks over on the reddit thread think it might be a case of accidentally booting into a previous generation, or not having my boot partition set up correctly. I'm still looking into that, but here is that output, both before and after the rebuild.

Also included a listing from /nix/store, in case that would be helpful.

```
$ google-play-music-desktop-player
google-play-music-desktop-player: command not found

$ command -v google-music-player-desktop-player

$ ls /nix/store/ | grep google
8pm7rrkfa4ddvy3mg6jpgracfcsxdzi9-google-play-music-desktop-player-4.4.1
gj8srkdpkh6wwhzp7bywm009vbr6gk7n-google-play-music-desktop-player_4.4.1_amd64.deb.drv
z45kclrv56pzm3n28936d03sirh6ki97-google-play-music-desktop-player-4.4.1.drv

$ sudo nixos-rebuild switch 
[sudo] password for ben: 
building Nix...
building the system configuration...
activating the configuration...
setting up /etc...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: polkit.service

$ command -v google-play-music-desktop-player 
/run/current-system/sw/bin/google-play-music-desktop-player

$ ls /nix/store/ | grep google
8pm7rrkfa4ddvy3mg6jpgracfcsxdzi9-google-play-music-desktop-player-4.4.1
gj8srkdpkh6wwhzp7bywm009vbr6gk7n-google-play-music-desktop-player_4.4.1_amd64.deb.drv
z45kclrv56pzm3n28936d03sirh6ki97-google-play-music-desktop-player-4.4.1.drv
```

**Comment by Semantimancer** [comment]
Update: After more digging, it seems my hardware-configuration.nix was somehow reset, such that it no longer mentions my boot directory. That certainly explains the problems I've been having, but I haven't found a solution just yet.

[Further explanation](https://www.reddit.com/r/NixOS/comments/8jfuuw/configuration_not_taking/dz1dhht)

**Comment by Semantimancer** [comment]
Solved the problem by booting into live disc, regenerating hardware-configuration.nix, and then (because I had seen hardware-configuration.nix get reset once already) manually copying everything into configuration.nix

Seems to be working, only side-effect is I can't import hardware-configuration.nix, so any future changes to the file will need to be migrated over manually
