### ISSUE TITLE
Package 'multibootusb'

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#40545]
## Issue description

http://multibootusb.org/

https://github.com/mbusb/multibootusb

**Comment by colemickens** [comment]
@matthewbauer Hi, did I do something wrong? Should I have requested this in a different way?

**Comment by colemickens** [comment]
Weird, I thought I'd seen something to make me think this was resolved in a way other than just closing, but I can't find that linkage now.

Searching manually though, I do see a merged PR around the same time: https://github.com/NixOS/nixpkgs/pull/40184

Thanks; no action needed!

**Comment by matthewbauer** [comment]
Yeah sorry! Meant link it.
