### ISSUE TITLE
discord-0.0.4 broken in release-18.03

### ISSUE THREAD

**Issue by goertzenator** [NixOS/nixpkgs#40564]
## Issue description

discord-0.0.4 appears to be remotely disabled by the Discord servers.  It shows the following window and then does not let you continue running the app:

![image](https://user-images.githubusercontent.com/605072/40077881-8d634c38-5848-11e8-99e4-5ab0154a7047.png)

discord-0.0.5 is available in unstable.  Recommend backporting this to release-18.03

**Comment by MP2E** [comment]
Thanks, fixed as of 6f7f6876e5d75eaa88ede1240ebc27baf19d8569

**Comment by tenten8401** [comment]
What's the status of this? Running `sudo nixos-rebuild switch` doesn't seem to actually recognize that there's an update available for Discord.
![image](https://user-images.githubusercontent.com/6174343/40213782-4a25f252-5a25-11e8-800c-9bd58fce57cc.png)
![image](https://user-images.githubusercontent.com/6174343/40213791-58d74f80-5a25-11e8-8305-ae41b08c85f4.png)
(kind've new to NixOS and Nix in general, apologies if I'm just being plain dumb)

**Comment by goertzenator** [comment]
I think it's because the 18.03 channel hasn't been updated since 13 May. (https://nixos.org/channels/).  I don't know how often it updates, but based on the age of the other channels I would assume every few days.

**Comment by goertzenator** [comment]
I found this site: https://howoldis.herokuapp.com/

Looks like 18.03 keeps having build hiccups of one kind or another.

**Comment by tenten8401** [comment]
Make sense. Thanks!

May switch to 18.03-small for the time being.
