### ISSUE TITLE
Version bump request: altair-2.0

### ISSUE THREAD

**Issue by yegle** [NixOS/nixpkgs#40569]
## Issue description
https://altair-viz.github.io/ recently released 2.0 and I'm hoping to get an updated version.

While you are at it, could we also get `vega_datasets` in nixpkgs?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/iz6is2lssv9myy46750s69n1ihca37m3-nix-info
copying path '/nix/store/iz6is2lssv9myy46750s69n1ihca37m3-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-6-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(ych): `"nixpkgs-18.09pre140156.0e6fb50954b"`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`

**Comment by florianjacob** [comment]
NixOS 18.09 has altair 2.1 and also comes with vega_datasets, so this can be closed.

**Comment by yegle** [comment]
Confirmed:

```
$ nix-env -qa|grep altair
python2.7-altair-2.2.2
python3.7-altair-2.2.2

$ nix-env -qa|grep vega_datasets
python2.7-vega_datasets-0.5.0
python3.7-vega_datasets-0.5.0
```
