### ISSUE TITLE
proposal/idea: setup-hook that scans for "unexpected" NT_GNU_ABI_TAG values

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#40578]
## Issue description

After investigating #38832, I thought it would be nice to learn from this ("fool me once, shame on you; fool me twice, shame on me") and do at least the simple thing of adding a setup-hook that checks that none of the ELF files (executables/shared libraries) produced by our builds has an unexpected requirement re:kernel minimum version.

Probably wouldn't be too hard to put together, does this sound like a good idea?

Not sure how likely this is to be a problem again, but if nothing else would be nice to ensure we don't have this already in other packages and to avoid regressing in the future :).

Just wanted to make a note of this to get some feedback about this, before I forgot it entirely :).

If it sounds good I can look into it, but am happy to let someone else do so if you're interested :).

**Comment by dezgeg** [comment]
3.2.0 is due to latest glibc which dropped support for all kernels older than that.

**Comment by dtzWill** [comment]
Hmm. Well AFAICT on master and staging "glibc" itself at least doesn't seem to be this way-- nor does the first thing I tried, "gzip":

```console
$ readelf -n /nix/store/l1cq6ybv11ps2hdfp708j5fvx4rn3crx-glibc-2.27-bin/bin/iconv

Displaying notes found in: .note.ABI-tag
  Owner                 Data size	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 2.6.32

Displaying notes found in: .note.gnu.build-id
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 582bb51aa6f6cd6ab6a0607dd649c413a5c39963
```

```console
$ readelf -n /nix/store/cvs1nka6x25k7w20jii2srymlx9njy4s-gzip-1.9/bin/gzip

Displaying notes found in: .note.ABI-tag
  Owner                 Data size	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 2.6.32
```

So maybe we fixed this or something? Or am I looking at the wrong paths?

**Comment by dezgeg** [comment]
Right, we have this hack in `pkgs/development/libraries/glibc/common.nix` which affects the numbers:
````
      /* Allow running with RHEL 6 -like kernels.  The patch adds an exception
        for glibc to accept 2.6.32 and to tag the ELFs as 2.6.32-compatible
        (otherwise the loader would refuse libc).
        Note that glibc will fully work only on their heavily patched kernels
        and we lose early mismatch detection on 2.6.32.
````

**Comment by grahamc** [comment]
IMO we should maintain support for CentOS 6 -- lots of places are using Nix as a way to escape their ancient package set.

**Comment by dezgeg** [comment]
From a quick glance, vast majority (or perhaps all) of the 2.6.x ones in your gist are just prebuilt binaries and not nixpkgs-compiled ones, presumably just compiled against old glibc of whatever distro the upstream uses. Nothing that can be done there.

So it still seems to me that Qt is the only software in existence that ever sets this ABI tag manually.

**Comment by dtzWill** [comment]
Thanks for sorting through them! I agree with your findings, hooray this isn't seeing widespread use!

Alright so that reduces the utility of a setup-hook to avoid regressing, which is still probably useful but a bit less exciting :).
