### ISSUE TITLE
slimserver: indexing doesn't work

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#40589]
## Issue description
The slimserver service in NixOS 18.03 doesn't complete the indexing of
media due to a missing dependency.

### Steps to reproduce
Enable slimserver by adding the following line to `configuration.nix`:

```nix
  services.slimserver.enable = true;
```

Then build & install this configuration. Then connect to the port 9000
using a browser and configure the service to scan a directory
containing some (audio) media files. In my installation the service
aborts the scan with the following lines dumped to the log visible by
running `journalctl -eu slimserver`:

```
[18-05-16 12:42:33.4502] main::main (331) Error: Failed when running main scan: [Can't locate Media/Scan.pm in @INC (you may need to install the Media::Scan module) ...
BEGIN failed--compilation aborted at /nix/store/wm3zzp1j3x248kaa0kr4a2rlraqd1bln-perl-slimserver-7.9.0/Slim/Utils/Scanner/LMS.pm line 18.
Compilation failed in require at /nix/store/wm3zzp1j3x248kaa0kr4a2rlraqd1bln-perl-slimserver-7.9.0/Slim/Media/MediaFolderScan.pm line 78.
]
[18-05-16 12:42:33.4506] main::main (332) Error: Skipping post-process & Not updating lastRescanTime!
        (in cleanup) Internal error: Root Logger not initialized. at /nix/store/wm3zzp1j3x248kaa0kr4a2rlraqd1bln-perl-slimserver-7.9.0/lib/perl5/site_perl/Log/Log4perl/Logger.pm line 580.
        (in cleanup) Internal error: Root Logger not initialized. at /nix/store/wm3zzp1j3x248kaa0kr4a2rlraqd1bln-perl-slimserver-7.9.0/lib/perl5/site_perl/Log/Log4perl/Logger.pm line 580
```

See also the discussion on the AUR package page at https://aur.archlinux.org/packages/logitechmediaserver/?comments=all

## Technical details

- system: `"x86_64-linux"`
- host os: `Linux 4.15.18, NixOS, 18.03.132336.ef74cafd3e5 (Impala)`
- multi-user?: `no`
- sandbox: `yes`
- version: `nix-env (Nix) 2.0.1`
- channels(root): `"nixos-18.03.132336.ef74cafd3e5"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by azazel75** [comment]
cc @phile314

**Comment by phile314** [comment]
I am currently upgrading slimserver on the nixos-unstable branch ( https://github.com/phile314/nixpkgs/tree/slimserver ), will take a look afterwards at this. Might take a few days, as I have just managed to brick the server which runs my slimserver instance ....

**Comment by phile314** [comment]
What are your exact settings? Do you have the Pictures/Videos checkbox set for your media folder? What kind of file provokes the issue (mp3, flac, ogg, png, jpg, mkv)?

Does the media database contain no entries at all after the scan has aborted or does the scan partially succeed?

**Comment by azazel75** [comment]
Hi Philipp, thanks for looking into this...
>>>>> "Philipp" == Philipp Hausmann <notifications@github.com> writes:

    Philipp> What are your exact settings?

I've tried to attach the server.prefs to this message, we'll see if it
ends up correctly in the issue, there's nothing private.

 

    Philipp> Do you have the Pictures/Videos checkbox
    Philipp> set for your media folder?

no, just music

    Philipp> What kind of file provokes the issue (mp3, flac, ogg, png,
    Philipp> jpg, mkv)?

It's not clear from the logs, but the only filetypes I use are flac,
mp3, jpg and png for the covers, m3u for the playlists.

I do have a couple of additional indexes by composer and by conductor to
help with classical music.

    Philipp> Does the media database contain no entries at all after the
    Philipp> scan has aborted or does the scan partially succeed?
    
I've still to access the database files, but the effect is strange: the
various list (artists, albums, etc..) are browsable, but the search from
the ui  doesn't work at all, returning always empty results.

Previously I had the slimserver running on Debian, that's why it's so
customized.

**Comment by azazel75** [comment]
mmm, it  seems that the attachment got evicted...

**Comment by phile314** [comment]
I could reproduce the problem. I copied the solution from the Arch package, just disabling image/video support seems to do the trick. Patch:

https://github.com/NixOS/nixpkgs/compare/master...phile314:slimserver-fix

Could you try out if the fix solves the problem?

**Comment by azazel75** [comment]
Indeed it works, thanks! Let's hope it will be backported to 18.03! Even the images of the covers show up correctly!
