### ISSUE TITLE
useACMEHost does not add subdomain as valid to SSL certificate

### ISSUE THREAD

**Issue by AdrianVovk** [NixOS/nixpkgs#40593]
## Issue description
I'm setting up a webserver with (roughly) this kind of structure:
```
"carbon.sh" {
   useACME = true;
   serverAliases = [ "www.carbon.sh" ];
   [...]
}
"source.carbon.sh" {
   useACMEHost = "carbon.sh";
   [...]
}
```

When using this config, `source.carbon.sh` does not get added to the list of domains on my SSL certificate. Only `www.carbon.sh` and `carbon.sh` work. If I add the broken subdomain as an alias of carbon.sh, it works, but the functionality is broken.

I'm guessing the issue happens because of [the conditions on this line](https://github.com/NixOS/nixpkgs/blob/release-18.03/nixos/modules/services/web-servers/nginx/default.nix#L595). For some reason if a domain uses `useACMEHost`, it gets excluded from the list of approved domains on the certificate.

### Steps to reproduce
Follow the same configuration I wrote out on my issue description. Or you can try and access my site. carbon.sh will work but source.carbon.sh will say this:
> This server could not prove that it is source.carbon.sh; its security certificate is from carbon.sh. This may be caused by a misconfiguration or an attacker intercepting your connection.

## Technical details
~Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the results.~

I currently do not have access to my server, so I cannot run this command. I could post it in a little while once I get to my machine and log in.

**Comment by jtojnar** [comment]
`useACMEHost` is supposed to be used with certificates created using `security.acme.certs`, see the [original commit](https://github.com/NixOS/nixpkgs/commit/41d252d7a4be12db7cec5a47468cee1024525eca). If I recall correctly, it was not possible to add the subdomains automatically due to the way the option is structured.

**Comment by AdrianVovk** [comment]
@jtojnar Well what is the point of having `enableACME` in the first place then?

Should I submit a PR for this at some point or should I not bother?
