### ISSUE TITLE
ATK gobject introspection broken on macOS

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#40599]
## Issue description

Try running redshift-gtk & observe error.

The ATK .gir location is incorrect. There is an @rpath in the path. It looks like it’s a meson issue.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by jtojnar** [comment]
Either problem is with the `meson` patch or the `gobjectIntrospection` one.

```ShellSession
$ cat (nix-build -A atk.dev --system x86_64-darwin)/share/gir-1.0/Atk-1.0.gir | grep shared-library
             shared-library="/nix/store/j5vlkkv64p7ppq27j4xvh7qn5aihlc5z-atk-2.28.1/lib/@rpath/libatk-1.0.0.dylib"
$ cat (nix-build -A atk.dev --system x86_64-linux)/share/gir-1.0/Atk-1.0.gir | grep shared-library
             shared-library="/nix/store/32d67c4dsgqzsll3jm33pksa1dq167z9-atk-2.28.1/lib/libatk-1.0.so.0"
```

**Comment by matthewbauer** [comment]
Trying it right now. Might take a little bit to build though.

**Comment by matthewbauer** [comment]
So it's still an issue but maybe we're getting closer.

With patches:


```
** (.redshift-gtk-wrapped:18980): WARNING **: 16:51:48.373: Failed to load shared library '/nix/store/j5vlkkv64p7ppq27j4xvh7qn5aihlc5z-atk-2.28.1/lib/@rpath/libatk-1.0.0.dylib' referenced by the typelib: dlopen(/nix/store/j5vlkkv64p7ppq27j4xvh7qn5aihlc5z-atk-2.28.1/lib/@rpath/libatk-1.0.0.dylib, 9): image not found
```

Without patches:

```
** (.redshift-gtk-wrapped:15156): WARNING **: 16:50:21.527: Failed to load shared library '@rpath/libatk-1.0.0.dylib' referenced by the typelib: dlopen(@rpath/libatk-1.0.0.dylib, 9): image not found
```

So the patches are probably still needed, they just need to overwrite the @rpath part.

**Comment by jtojnar** [comment]
I think that is a meson bug, the same one that requires us to use `fixDarwinDylibNames`. I guess that `gobject-introspection` uses `install_name` but the setup hook did not fire yet. If it is the case, the only reasonable fix would be meson producing a correct `install_name`.

**Comment by jtojnar** [comment]
Either way, you should use the unpatched file in the [upstream report](https://github.com/mesonbuild/meson/issues/3574).

**Comment by pftbest** [comment]
I have the same exact problem with `meld`. Is there some workaround that I can do?

**Comment by jtojnar** [comment]
This is already fixed by https://github.com/NixOS/nixpkgs/pull/46310

**Comment by pftbest** [comment]
I think I am using unstable. At least `nix-channel --list` tells me that.
Here is my log https://gist.github.com/pftbest/5b9041fe9c8ea7dde5ba4fac85944263
