### ISSUE TITLE
Use upstream tmpfiles.d

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#40594]
Currently, NixOS modules define tmpfiles.d manually using `systemd.tmpfiles.rules` option. Many packages provide the configuration files, though, so it would make sense to reuse them.

The easiest method would be manually adding the files to `/etc`, e.g. `environment.etc."tmpfiles.d/rkt.conf".source = "${pkgs.rkt}/lib/tmpfiles.d/rkt.conf";`, but automating it the same way services are installed would probably make more sense in the long term. `systemd.packages` could recognize at least `${pkg}/etc/tmpfiles.d/*.conf` and `${pkg}/lib/tmpfiles.d/*.conf` files, see `tmpfiles.d(5)`, and install them to `/etc` automatically.

**Comment by flokli** [comment]
I agree this should be done in `systemd.packages` - we recently (#65376) moved support for generators into `systemd.packages` too.

We might also want to add `example/tmpfiles.d` to the list of paths (#69295), or move the systemd tmpfiles to an appropriate location during install.

possible usages: https://github.com/NixOS/nixpkgs/pull/66856

**Comment by flokli** [comment]
I think this has been implemented with https://github.com/NixOS/nixpkgs/pull/93073, hasn't it?

**Comment by Mic92** [comment]
yes.
