### ISSUE TITLE
Cross-compiling Clang fails because clang-tblgen must be run.

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#40602]
## Issue description
Like LLVM (see https://github.com/NixOS/nixpkgs/issues/39170), clang needs a tblgen binary that's both built and run at package build time, and this is problematic for cross-compiling clang itself for the same reasons. Unfortunately, unlike llvm-tblgen, clang-tblgen is not installed by clang's build system.

There was a patch upstream to fix this:

https://reviews.llvm.org/D10916#change-9P8m0KkVhKUz

But it was rejected on the premise that clang-tblgen isn't useful for anything other than building clang. Given this, I'm not sure what upstream views as the "right" way to cross-compile clang. Perhaps you're meant to just build a native clang-tblgen manually and use that?

As a workaround we could apply the rejected makefile patch so that clang-tblgen gets installed, then use `${buildPackages.clang}/bin/clang-tblgen` when `buildPlatform != hostPlatform`.

### Steps to reproduce
In nixpkgs master: `nix-build -E "with import ./default.nix {crossSystem = (import ./lib).systems.examples.aarch64-multiplatform;}; llvmPackages_5.clang"`

**Comment by dtzWill** [comment]
> Given this, I'm not sure what upstream views as the "right" way to cross-compile clang. Perhaps you're meant to just build a native clang-tblgen manually and use that?

Apparently? I imagine it's probably best to ensure to only use "tablegen" tools built from the same llvm/clang source, but if there's any other requirement on the build configuration/method they don't say...  hopefully that means whatever works for us!

As evidenced by that patch rejection (and other details) this is not really how **"they"** do things,
and this disconnect is sadly all too common and it's part of a larger trend across the LLVM project.  Not that there are bad intentions or anything of the sort -- but just the sort of inevitable change as the project is shaped by the priorities and values of the parties involved .   Sigh.  Maybe I should chat with them about these things, sorry hehe.  Anyway let's just say I wouldn't hold your breath for this to be addressed anytime soon, and if we're unhappy about that we should consider finding funding/resources to put towards improving things for us (and hopefully others) :). I'm sure they'll be happy  to work with us!
And honestly our wrappers are increasingly brilliant but with a small amount of integration support there are lots of things that would be much easier and very awesome :).

Back to the matter at hand, I don't think you/we should worry too much about this and either apply that patch if it's easy to do so or honestly just add a line to our expression that copies it explicitly.

-----------

FWIW they do facilitate this sort of thing --  but I think we'd have to go all-in with the sort of thing they describe as "advanced": http://llvm.org/docs/AdvancedBuilds.html. Lots of goodness here, "but" isn't immediately compatible with how we've previously done things or how we'd like to do them.

**Comment by dezgeg** [comment]
Shouldn't Clang's build system just build `clang-tblgen` using the native compiler regardless of whether it's being cross compiled or not?

**Comment by dezgeg** [comment]
Based on https://github.com/llvm-mirror/llvm/blob/5d61ed94175695af323eff94ca92de6944bc94a0/cmake/modules/TableGen.cmake, you probably need to define `LLVM_USE_HOST_TOOLS`. Which sounds like it should be automatically enabled when cross compiling: https://github.com/alisw/clang/blob/master/CMakeLists.txt#L434

**Comment by dtzWill** [comment]
Here's hoping it's something easy like that! Can you give that a try and report what you find?

**Comment by dtzWill** [comment]
Wasn't looking for this but found this as part of mingw-w64 work, seemed relevant:

https://github.com/martell/mingw-w64-clang/blob/master/patches/llvm/0001-fixup-tblgen.patch

**Comment by dtzWill** [comment]
Hehe: https://github.com/martell/mingw-w64-clang/blob/ec96ff3a4d10a36325824f5041a441910b3cc24f/scripts/build-llvm.sh#L41

**Comment by TravisWhitaker** [comment]
This actually works now.
