### ISSUE TITLE
nix uses deprecated ghc-pkg package databases

### ISSUE THREAD

**Issue by MP2E** [NixOS/nixpkgs#4062]
GHC HEAD has removed the ghc-pkg single file configuration databases in favor of the folder databases  initialized via 'ghc-pkg init $dbDir'. This means that nix can't install any packages with GHC HEAD, and it will break when GHC 7.10.1 comes out and we inevitably update. The new folder-style database was added in GHC 6.12, so it shouldn't break anything old to update. I'm writing a solution now..

**Comment by peti** [comment]
This has been fixed in the `haskell-ng` package set.
