### ISSUE TITLE
Pencil crashes on launch

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#40675]
## Issue description

Can't launch Pencil from userspace, it crashes with the stack trace:

```Hardware acceleration disabled for Linux.
[16216:0517/221855:FATAL:udev_loader.cc(38)] Check failed: false. 
#0 0x000001e5839e <unknown>
#1 0x000001e6e09b <unknown>
#2 0x000000cbebe4 <unknown>
#3 0x000000cbdab6 <unknown>
#4 0x000000cbe4ca <unknown>
#5 0x000001248442 <unknown>
#6 0x000001e59066 <unknown>
#7 0x000001e74595 <unknown>
#8 0x000001e74888 <unknown>
#9 0x000001e74cdb <unknown>
#10 0x000001e4e4a9 <unknown>
#11 0x000001e8d25e <unknown>
#12 0x000001eac24a <unknown>
#13 0x000002707c76 <unknown>
#14 0x000002707e7e <unknown>
#15 0x000001eac30e <unknown>
#16 0x000001ea8893 <unknown>
#17 0x7f0882b872a7 start_thread
#18 0x7f087c58257f __GI___clone

Aborted
```

### Steps to reproduce

- `nix-env -i pencil`
- `pencil`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.37, NixOS, 18.03.132192.ce0d9d638de (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
So digging into this, I've realized that it's a Yarn/Electron app just like RocketChat (#39604). I'd really like us to get these kinds of apps working from source (right now pencil is just built from the .deb file). Otherwise we have to deal with random issues like this.

**Comment by chekoopa** [comment]
As for `20.09pre226586.571212eb839`, Pencil runs and works. Closing the issue.
