### ISSUE TITLE
lolcat clashes with travis

### ISSUE THREAD

**Issue by mt-caret** [NixOS/nixpkgs#40674]
## Issue description

lolcat seems to clash with travis regarding a LICENSE.md.

### Steps to reproduce

```
$ nix-env -iA nixpkgs.travis
...
$ nix-env -iA nixpkgs.lolcat
installing 'lolcat-99.9.11'
building '/nix/store/7lzj3n3nxa2ghrkxx9ybjqvwv6sammw6-user-environment.drv'...
error: packages '/nix/store/h1lpzdg5gljg8gppr2l4h38k0iqlq5na-lolcat-99.9.11/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/LICENSE.md' and '/nix/store/c7wraplc7mfnv1q4b2mrpaz1xcrhvpqs-shell-tools/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/LICENSE.md' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/7lzj3n3nxa2ghrkxx9ybjqvwv6sammw6-user-environment.drv' failed with exit code 1
error: build of '/nix/store/7lzj3n3nxa2ghrkxx9ybjqvwv6sammw6-user-environment.drv' failed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.09pre139651.6db7f92cc2a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre139651.6db7f92cc2a"`
 - channels(delta): `"nixpkgs-18.09pre140004.425ff431aba"`
 - nixpkgs: `/home/delta/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
It looks like a ruby gem issue. Is that LICENSE.md the only conflict?

I'll bet we can just delete that in the fixup phase.

/cc @zimbatm @aneeshusa

**Comment by zimbatm** [comment]
I am getting something a bit different:
```
[@x1:~]$ nix-env -iA nixos.travis nixos.lolcat
installing 'travis-1.8.8'
installing 'lolcat-99.9.11'
building '/nix/store/9nbh2gly97brcd4kgrh916s7hs4qacz8-user-environment.drv'...
error: packages '/nix/store/h1lpzdg5gljg8gppr2l4h38k0iqlq5na-lolcat-99.9.11/lib/ruby/gems/2.4.0/cache/bundler-1.14.6.gem' and '/nix/store/dkd4jbyvp88lppggpawlabym976bivws-travis-1.8.8/lib/ruby/gems/2.4.0/cache/bundler-1.14.6.gem' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/9nbh2gly97brcd4kgrh916s7hs4qacz8-user-environment.drv' failed with exit code 1
error: build of '/nix/store/9nbh2gly97brcd4kgrh916s7hs4qacz8-user-environment.drv' failed
```

There is a conflict but if I look at those files they both resolve to the same symlink:
```
[@x1:~]$ readlink /nix/store/h1lpzdg5gljg8gppr2l4h38k0iqlq5na-lolcat-99.9.11/lib/ruby/gems/2.4.0/cache/bundler-1.14.6.gem
/nix/store/c0yrkixjw8bxm6l9jx3i62f2x281xipm-bundler-1.14.6/lib/ruby/gems/2.4.0/cache/bundler-1.14.6.gem

[@x1:~]$ readlink /nix/store/dkd4jbyvp88lppggpawlabym976bivws-travis-1.8.8/lib/ruby/gems/2.4.0/cache/bundler-1.14.6.gem
/nix/store/c0yrkixjw8bxm6l9jx3i62f2x281xipm-bundler-1.14.6/lib/ruby/gems/2.4.0/cache/bundler-1.14.6.gem
```

**Comment by FRidh** [comment]
This seems like a design mistake. Why pull in parts that are likely to be used also in other packages. That's asking for collisions. I think in general it is better to install only the `bin/` of a derivation, e.g. by creating a wrapper derivations. Are any of the other folders needed?

**Comment by zimbatm** [comment]
Sometimes gems also expose data like manpages but I agree, the gem dependencies should be linked by environment instead of by file

**Comment by FRidh** [comment]
Downside with environment variables is that they tend to leak to sub-processes. Considering issues like these only occur when installing in a profile, do you think it would be possible to use multiple outputs with a default `bin/` output?

**Comment by zimbatm** [comment]
seems to be solved:
```
$ tree $(nix-build -A lolcat)
/nix/store/rjgb3c4qxvg462n9c0hyfj4prqvxmg1v-lolcat-100.0.0
├── bin
│   └── lolcat -> /nix/store/9k6dhwcwfw5h890vd64kh27dsp0lhmjs-lolcat-100.0.0/bin/lolcat
└── share
    └── man
        └── man6
            └── lolcat.6

4 directories, 2 files
```
