### ISSUE TITLE
Is it possible to revive rpm-14.3 alongside rpm-14.4

### ISSUE THREAD

**Issue by Assassinkin** [NixOS/nixpkgs#40683]
## Issue description

We are building an rpm package that requires rpm. The build succeed and the binaries execute correctly on 17.09. after upgrading to 18.03 the binaries are no longer able to excecute due to a missing header in the librpm-so.8  which is part of rpm-14.4
Is it possible to revive rpm-14.3 (which include librpm.so.7) alongside the latest one. 
If not is there any workaround for that.
I also tried to package rpm-14.3 locally but it also requires dependencies that got upgraded.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by matthewbauer** [comment]
I guess this will depend on whether there is a legitimate reason to need that missing header from librpm-so.7. If it's a trivial change, it seems like we can expect other packages to update to rpm 14.4 fairly quickly. Otherwise we may need to revive the old version (of course we will also need to add old versions of rpm dependencies as well).

**Comment by Assassinkin** [comment]
@matthewbauer We basically have an rpm binary that we are "packaging"  (trendmicro deep-security agent ) and it requires that specific header in run-time which is not included in librpm.so.8. Not sure if trendmicro are planning on fixing that cause RedHat families are still using older versions of rpm.
Not sure if that can be considered legitimate reason. But, librpm.so being a shared library, the missing header "could" break other packages.

**Comment by bhipple** [comment]
If you have a set of NixPkgs for your organization and would like to globally hold back RPM, you can use an overlay like this:

```
# ~/.config/nixpkgs/overlays/rpm-overlay.nix
self: super: {
  rpm = super.rpm.overrideAttrs (oldAttrs: rec {
    name = "rpm-${version}";
    version = "4.13.0.1";
    src = super.fetchurl {
      url = "http://ftp.rpm.org/releases/rpm-4.13.x/rpm-${version}.tar.bz2";
      sha256 = "27fc7ba7d419622b1ce34d6507aa70b0808bc344021d298072a0c2ec165f9b0d";
    };
  });
}
```

Then `nix-build . -A rpm` will give you rpm 4.13, and anywhere you've specified `rpm` you'll get the older one.

If it's just needed for this 1 package, you could just put the override within this one package.

If the RPM upgrade represents a legitimate major version with backwards incompatibility and there are potentially many upstream users who would like to use the older one, NixPkgs does keep around multiple versions for these cases.  There's a section in the NixPkgs manual that describes why we prefer to keep as few versions around as possible:
https://nixos.org/nixpkgs/manual/#sec-versioning

**Comment by Assassinkin** [comment]
@bhipple THanks for the reply.
Not Sure if that supposed to be a major release but here are the release highlights:

> Highlights include:
Major revamp of debuginfo packages
Major macro engine changes to sanitize and improve the “language”
Major rewrite of package/header reading and signature checking to utilize a single codepath

I m trying to override rpm for my specific package as you suggested. I m declaring it as follow 
`nixpkgs.config.packageOverrides = with pkgs; pkgs: {
     rpm413 = lib.overrideDerivation rpm (a: rec {
     name = "rpm-${version}";
     version = "4.13.0.1";
     src = fetchurl {
       url = "http://ftp.rpm.org/releases/rpm-4.13.x/rpm-${version}.tar.bz2";
       sha256 = "27fc7ba7d419622b1ce34d6507aa70b0808bc344021d298072a0c2ec165f9b0d";
     };
  })
};`


when building i get the following error: 


> /nix/store/fnvms0cfcl0frbbmcp90zka14g6brbl9-libbfd-2.30-dev/include/bfd.h:35:2: error: #error config.h must be included before this header
 #error config.h must be included before this header
  ^~~~~
make[2]: *** [Makefile:1146: tools/sepdebugcrcfix.o] Error 1
make[2]: Leaving directory '/build/rpm-4.13.0.1'
make[1]: *** [Makefile:1376: all-recursive] Error 1
make[1]: Leaving directory '/build/rpm-4.13.0.1'
make: *** [Makefile:756: all] Error 2
builder for '/nix/store/ni0np78gqbq97yl5hs4yrpl6yqf05g8q-rpm-4.13.0.1.drv' failed with exit code 2

Am I doing something wrong ?

**Comment by Assassinkin** [comment]
Fixed the issue using this 
```+  nixpkgs.config.packageOverrides = pkgs: {
+    rpm =
+      if ((builtins.substring 0 5 lib.nixpkgsVersion) < "18.03")
+        then pkgs.rpm
+      else (
+        lib.overrideDerivation pkgs.rpm (a: rec {
+          name = "rpm-${version}";
+          version = "4.13.0.1";
+          src = pkgs.fetchurl {
+            url = "http://ftp.rpm.org/releases/rpm-4.13.x/rpm-${version}.tar.bz2";
+            sha256 = "27fc7ba7d419622b1ce34d6507aa70b0808bc344021d298072a0c2ec165f9b0d";
+          };
+          patches = [ ./rpm-4.13.0.1-bfd-config.patch ];
+       }));
+  };

Thanks for the help.
