### ISSUE TITLE
Adding a deprecated notice to libgnome-keyring-X to the "Long description"

### ISSUE THREAD

**Issue by elaOnMars** [NixOS/nixpkgs#40764]
## Issue description
libgnome-keyring [1] is horrible deprecated.
But it is not mentioned in the package descriptions [2] 

libgnome-keyring could be replaced with libsecret. [3]

Because some applications still require this library it should 
not be removed but adding a notice would be helpfull.

## Technical details
[1] https://github.com/GNOME/libgnome-keyring [updated]
[2] https://nixos.org/nixos/packages.html#libgnome-keyring
[3] https://nixos.org/nixos/packages.html#libsecret

**Comment by AndersonTorres** [comment]
Three things.

**First**: Libgnome-Keyring isn't marked as deprecated by mainstream, it is? I've found a github repo [1] of it.

**Second**, to the real work: can you submit a patch, adding to the last line of LongDescription something like 

`"*Warning*: <this package> is deprecated! Use <that package> instead."?`

where the <packages> are their mainstream names, not Nixpkgs' ones.

**Third**, we can chase the dependent packages and patch them in order to use the new library.

Drop me a line if you need some help!

1 - https://github.com/GNOME/libgnome-keyring

**Comment by jtojnar** [comment]
What would be the point? Users should not really install libraries, so it will only be used as a dependency of some package that needs it. Well, we had some packages that had `libgnome-keyring` in `buildInputs` even though they were already ported to `libsecret` but that is orthogonal issue of maintainers not reading changelogs. 

Instead, we should check that packages that declare dependency on `libgnome-keyring` really need it and either correct the dependecies, or request the port upstream (e.g. [lifferea](https://github.com/lwindolf/liferea/issues/436)).

**Comment by jtojnar** [comment]
@AndersonTorres [upstream deprecation](https://git.gnome.org/browse/libgnome-keyring/commit/?id=6a5adea4aec931708d2b16decff7405fb0ae67c3), [dropping from Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359)

**Comment by elaOnMars** [comment]
@jtojna: I needed to install this library because evolution mail did not have asked for the main application  password.

**Comment by elaOnMars** [comment]
I've created a Pull request: [GNOME/libgnome-keyring
](https://github.com/GNOME/libgnome-keyring/pull/1)

**Comment by jtojnar** [comment]
The GitHub repository is just a read-only mirror. You will need to open an issue on [GNOME Bugzilla](https://bugzilla.gnome.org/enter_bug.cgi?product=gnome-keyring), if you want the README changed. You can add [your patch](https://github.com/GNOME/libgnome-keyring/pull/1.patch) as an attachment.

Evolution in nixpkgs have used libsecret for a long time now. The thing you might need is GNOME Keyring which is a backend used by `libgnome-keyring` and `libsecret`. You may use other backend like KWallet, your desktop environment should already contain some keyring manager.

**Comment by AndersonTorres** [comment]
As an advice: put each expression you will update as a separate commit.

Say, if you find packages A, B and C depending on old lib, fill a commit for A, other for B and another for C, then do a PR.
