### ISSUE TITLE
zoom is broken in master

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#40776]
## Issue description
Zoom crashes on startup: 

```
$ zoom-us
sh: /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6: version `GLIBC_2.27' not found (required by /nix/store/fycm4swi722vz4l5ckpqrd4nfzj6av79-v4l-utils-1.12.3/lib/libv4l2.so.0)
zoom started.
Could not initialize GLX
Aborted
```

`glxgears` does work.

```
glxinfo  | grep dir.*render
direct rendering: Yes
```

### Steps to reproduce
Install zoom from master.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.git.ee80654 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

CC: @srhb (because you touched it last, but it might be that it was already broken before that).

**Comment by manveru** [comment]
It works for me via `nix build -f . zoom-us && ./result/bin/zoom-us`. I'm using nvidia and also get this on startup:
```
sh: /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6: version `GLIBC_2.27' not found (required by /nix/store/fycm4swi722vz4l5ckpqrd4nfzj6av79-v4l-utils-1.12.3/lib/libv4l2.so.0)
zoom started.
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: D8:50:E4:DC:C2:52][client: Linux][OS: NixOS 18.03.132336.ef74cafd3e5 (Impala)][Hardware: CPU Core:8 Frenquency:3.5 G Memory size:32047MB CPU Brand:Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz GPU Brand:][Req ID: ]
Linux Client Version is 2.0.123200.0405
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = ;   GDMSESSION = 
Graphics Card Info:: 
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name:  
qrc:/qml/PreMeeting.qml:117: TypeError: Cannot read property of null
qrc:/qml/PreMeeting.qml:128: TypeError: Cannot read property of null
qrc:/qml/PreMeeting.qml:117: TypeError: Cannot read property of null
qrc:/qml/PreMeeting.qml:128: TypeError: Cannot read property of null
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
```

**Comment by srhb** [comment]
If I caused that error, I'm afraid I have no idea how. I'll try a master build tomorrow. I tested it on unstable just this morning and everything looked fine to me. :(

**Comment by srhb** [comment]
@coretemp Oh, I just noticed your system is on an 18.03 commit. I don't think you can mix and match like that because of the libglvnd changes in master. Either use zoom from 18.03 or change your system to master as well, and everything should be fine.

**Comment by srhb** [comment]
(Alternatively, if someone knows how to make it backwards compatible, that could work too.)

**Comment by coretemp** [comment]
One argument for fixing it in NixOS is that I can imagine the first thing Zoom support will say when there is an issue is: "Do you run the latest version?". 

It depends on what other Linux distributions do, too. 

I don't know what the right answer here is either.

**Comment by danbst** [comment]
You can "emulate" install zoom_latest with the following
```
$ nix-env -i $(nix-build -E 'with import <nixpkgs> {}; zoom-us.overrideAttrs (sup: { src = (import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/master.tar.gz") {}).zoom-us.src;})')
```
In most cases it will work.

@srhb maybe you know what is the source of impurity? It looks like V4L tries to communicate to system libc. But why should it, if it has own libc in closure?

**Comment by coretemp** [comment]
Based on @danbst's suggestion the following should allow everyone on Linux to run the latest Zoom on 18.03 (and presumably future versions) without any modifications.

```
#!/bin/sh
# save in a file called zoom in e.g. ~/bin

# possibly change of remove these next three lines depending on your system
driver=uvcvideo
sudo rmmod "$driver"
sudo modprobe "$driver" &&

nix-env -i $(nix-build -E 'let pkgs = (import <nixpkgs> {config = {allowUnfree = true;};}); in with pkgs; zoom-us.overrideAttrs (sup: { src = (import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/master.tar.gz") {}).zoom-us.src;})') &&
"${HOME}"/.nix-profile/bin/zoom-us
```
