### ISSUE TITLE
(Important) ib-tws: out of date

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#40784]
## Issue description

@garbas (original author of package)

```
 LogonDispatcher received reject(probably running an old ccp version), reason [The version of the application you are running, 952.1e, is no longer supported.
Please download the current version from our web site.]
```

I am using the version in `master` when I tried this.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.git.ee80654 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Rizvanov-Rinat** [comment]
Having similar problems. Found any solution?

**Comment by stefan-j** [comment]
I am also looking for a solution. Currently I see the downloaded jar file for mac is out of date

**Comment by Rizvanov-Rinat** [comment]
I solved the problem after installing new versions ib-controller and tws. I installed on a linux and used [this](https://dimon.ca/how-to-setup-ibcontroller-and-tws-on-headless-ubuntu-in-10-minutes/) guide

**Comment by coretemp** [comment]
@Rizvanov-Rinat What does "I installed on a linux" mean?

**Comment by CMCDragonkai** [comment]
I wonder if anybody will package up the client portal API? It provides a RESTful API.

**Comment by mahe-ymc** [comment]
> Looks like we need to update the package to extract the jar from a .sh install script instead of expecting it to be directly downloaded.

That's true, at the end of the .sh file is a .tar.gz postfixed. Can be extracted by 
```
tail -3014990c tws-latest-linux-x64.sh > sfx_archive.tar.gz
```
Exact byte number can be read from .sh in the first place.

**Comment by johnjameswhitman** [comment]
Should we mark the current package as broken until there's a fix in place? I spent a little while trying to get this to work before realizing the build was from 2015 and is no longer supported.

**Comment by Mic92** [comment]
Will be removed in: https://github.com/NixOS/nixpkgs/pull/327306

**Comment by Mic92** [comment]
I think we can close this than.

**Comment by RobinKD** [comment]
> Can this [flake](https://git.sr.ht/~rhizomic/tws/tree) be used to repair the packages?

I managed to get my own package (used in my config, you can see it [here](https://github.com/RobinKD/dotfiles/blob/main/pkgs/ib-tws/default.nix)) mostly working using this flake, as well as [clefru's NUR package](https://github.com/clefru/nur-packages/tree/master/pkgs/ib-tws). 

The only problem I still encounter is when trying to open news in the browser, which gives me a firefox error _Couldn't load XPCOM_, which I have no clue how to resolve.
