### ISSUE TITLE
Autoconf/m4 dependency error when using local nixpkgs

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#40782]
## Issue description

When Trying to use a local checkout of nixos/nixpkgs to build my environment (`with import ((builtins.getEnv "HOME") + "/workspace/nixpkgs") { };` instead of `with import <nixpkgs> { }; `), I get a build error related to autoconf and m4. I've tried this on both very recent commits (as of  May 18 and  May 19), and `tags/18.03` (early April):

```
building '/nix/store/504rhi0hr6q4wmbb495mqpgf9d0ib4x5-autoconf-2.64.drv'...
unpacking sources
unpacking source archive /nix/store/ahcpsh04cnmi3wmxjlnp6nxnvw4npfic-autoconf-2.64.tar.xz
source root is autoconf-2.64
setting SOURCE_DATE_EPOCH to timestamp 1248665434 of file autoconf-2.64/.tarball-version
patching sources
configuring
configure flags: --prefix=/nix/store/h44w4q2kddh1mckf7mgcnvlqp58fx5c2-autoconf-2.64
checking for a BSD-compatible install... /nix/store/5niqd24sw2m81i4qim51znrdyk4zi5y9-coreutils-8.29/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/5niqd24sw2m81i4qim51znrdyk4zi5y9-coreutils-8.29/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether /bin/sh -n is known to work... no
checking for characters that cannot appear in file names... none
checking whether directories can have trailing spaces... yes
checking for expr... /nix/store/5niqd24sw2m81i4qim51znrdyk4zi5y9-coreutils-8.29/bin/expr
checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
GNU M4 1.4.6 or later is required; 1.4.13 is recommended
builder for '/nix/store/504rhi0hr6q4wmbb495mqpgf9d0ib4x5-autoconf-2.64.drv' failed with exit code 1
building '/nix/store/l95h1hzpr1bwp1rv00b2wsrfmx9zcpiy-autoconf-2.69.drv'...
cannot build derivation '/nix/store/1dnx4kya891a7nph7ryi8j6pdqws5qrq-hook.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mplfxn9py3qnc5xxdfgpg5xny6qqf922-libbfd-2.28.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/99w0g7zls81wywn67iji4qjyw90zxkcj-llvm-5.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sjz3wvyy2b9xqarjbgbi3ab7v4azcdpx-clang-5.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z0vcpixc4awq8hdhy409mkrcd0dnjc7n-clang-manpages-5.0.1.drv': 1 dependencies couldn'tbe built
cannot build derivation '/nix/store/5i87yfb46l4mmd0amva8glbrvh8xnkgh-mesa-noglu-17.3.6.drv': 1 dependencies couldn't bebuilt
cannot build derivation '/nix/store/na8g0mqlra35cv8bji7f67dc8qvmkr2p-cairo-1.14.10.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/g0lz2ld75503wblx52zi8zwhjwcp0gay-clang-wrapper-5.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dsps3mmj1mzhywsrnvwqgaifyi3ln604-jetbrainsjdk-152b1036.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vzqll29vrxnc0lc53xwvwasm2sgp3vvp-libdevil-1.7.8.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wrcfnv6hjv1fmg6ks3ccfmkdj5rfwscr-mesa-17.3.6.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rwrz9zzkzfk7ws2lb5fi6d50c02r7f0b-qtbase-5.10.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/g76r2kbrsfc1wiply72h76f7s5nwzf3z-brandon-dev-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/g76r2kbrsfc1wiply72h76f7s5nwzf3z-brandon-dev-env.drv' failed
```

### Steps to reproduce

I've been using `nix-env -if` on this [nix expression](https://github.com/CornellCAC/docker-nix-intellij/blob/986f9f65a8e0164084c04de32a302570d34cfeef/dev-env.nix) but this could probably be greatly minified.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-41-generic, Ubuntu, 18.04 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(brandon): `"nixos-18.09pre139651.6db7f92cc2a, nixpkgs-18.09pre140156.0e6fb50954b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/brandon/channels/nixpkgs`

**Comment by bbarker** [comment]
I checked out commit 0e6fb50954b in nixpkgs to match what was shown as the known working version from nix-channels, and have the same problem.

**Comment by thomasjm** [comment]
I'm seeing this too, it seems to be on `autoconf-2.64`. The latest `autoconf-2.69` doesn't have the problem.

If you open `nix-shell '<nixpkgs>' -A autoconf264`, it seems that `m4` is version `1.4.18`. Yet the configure script complains `GNU M4 1.4.6 or later is required; 1.4.13 is recommended`. Seems like a bad version check?

**Comment by thomasjm** [comment]
I notice that nixpkgs only depends on `autoconf-2.64` via `autoreconfHook264` which was introduced by @Ericson2314. John, any chance it would be possible to bump this build hook to use `autoconf-2.69`? Or perhaps get rid of it entirely and use the vanilla `autoreconfHook`?
