### ISSUE TITLE
ld: -rpath can only be used when targeting Mac OS X 10.5 or later

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#40787]
## Issue description

Is there an easy way to disable rpath in ld-wrapper.sh? Right now it looks like it will add an -rpath arg every time.

This happens when -mmacosx-version-min is set really low. We can always of course patch it, but it might be nice to support these really old macosx versions.

The original culprit is NIX_COREFOUNDATION_RPATH being set here:

https://github.com/NixOS/nixpkgs/blob/136403655c15b830fff4f58fd90b3e1478c7ba30/pkgs/stdenv/darwin/default.nix#L341

Here is the source code causing this issue:

https://github.com/libretro/libretro-fceumm/blob/master/Makefile.libretro#L88

**Comment by matthewbauer** [comment]
Here's a job failing from this: https://hydra.nixos.org/job/nixpkgs/trunk/libretro.snes9x-next.x86_64-darwin/all

**Comment by LnL7** [comment]
We don't support versions of macOS older than 10.10 anymore, so there's no real reason for builds to use `-mmacosx-version-min` older than the `MACOSX_DEPLOYMENT_TARGET` we set in the stdenv.

Support for rpaths was introduced in 10.5 IIRC, that's really old now.

**Comment by Ericson2314** [comment]
The extra `--rpath` generated from ld-wrapper should already be disabled when building for Darwin too.

**Comment by matthewbauer** [comment]
Closing as unsupported.
