### ISSUE TITLE
upgrade pidgin to 2.13.0

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#40798]
## Issue description

The current version of pidgin in nixpkgs is 2.12.0 while the latest from upstream is 2.13.0. 

I have a commit which implements the upgrade [here](https://github.com/emmanuelrosa/nixpkgs/commit/b74cd52d02cd5266a3d149f618854ff40824d2af) (note this also pulls in a new libpurple plugin for OMEMO). I'm going to use this for a while to see how it holds up, do the `nox` thing, and then a pull request.

I welcome testers since I obviously won't be using all the available plugins. If you want to try out `lurch`, the OMEMO implementation, install `pidgin` like this:

```
environment.systemPackages = with pkgs; [
       (pidgin.override { plugins = [ purple-lurch ]; })
];
```

**Comment by turion** [comment]
@emmanuelrosa I observe a reproducible crash on startup in version 2.13.0

**Comment by emmanuelrosa** [comment]
That's unfortunate, @turion 
Please consider opening an issue; This one is over a year old. There you can report the problem in detail. You may reference this issue there, if you'd like.
