### ISSUE TITLE
bash syntax error with python36

### ISSUE THREAD

**Issue by chdsbd** [NixOS/nixpkgs#40804]
## Issue description
Running `nix-shell -p python36` produces the following error message:
`bash: /nix/store/w3k60lgxbkj1sj1zpyh50671qpky0v1w-stdenv-darwin/setup: line 135: syntax error near unexpected token `('`

However, if I run `nix-shell -p python36 --pure --run python3`, the python shell is brought up without issue.

### Steps to reproduce
- Run `nix-shell -p python36`

 I don't have an identical machine to reproduce the issue. I couldn't reproduce this on `Darwin 16.7.0, macOS 10.12.6`

## Technical details
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.5.0, macOS 10.13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixpkgs-18.09pre133932.ee28e35ba37"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by knedlsepp** [comment]
I guess we still have some problems with nix-shell impurely accessing `/bin/bash` instead of the nix provided one. Maybe comparing `dtruss -f nix-shell --pure  -p python36` with `dtruss -f nix-shell -p python36` reveals something.

**Comment by veprbl** [comment]
Can't reproduce on ee28e35ba37, the bash shell starts normally for me on:
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.5.0, macOS 10.13.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`

**Comment by veprbl** [comment]
@chdsbd Is this still an issue?
