### ISSUE TITLE
nix-env -qaP lists package that doesn't appear in <nixpkgs>

### ISSUE THREAD

**Issue by Steell** [NixOS/nixpkgs#40865]
## Issue description
I've added nixpkgs-unstable to my channel list, and nix-env is reporting that a package is there. But when I try to access the derivation via `import <nixpkgs> {}` the attribute isn't available.

### Steps to reproduce
```
> nix-channel --list
nixpkgs-unstable  https://nixos.org/channels/nixpkgs-unstable

> nix-env -qaP openzwave
nixos-unstable    openzwave-2018-04-04
nixpkgs-unstable  openzwave-2018-04-04

> nix repl
nix-repl> let p = import <nixpkgs> {}; in p.openzwave
error: attribute 'openzwave' missing, at (string):1:33
```
## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.40, NixOS, 18.03.132336.ef74cafd3e5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132405.ee80654b526, nixos-unstable-18.09pre140588.beef7ae1b38"`
 - channels(stephen): `"nixpkgs-unstable-18.09pre140605.bc309f5c57e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
`<nixpkgs>` points to `nixos-18.03.132405.ee80654b526`, which dos not have `openzwave`; you can use `<nixpkgs-unstable>` for the channel from `nix-channel --list`. Invoke the command with `sudo` to see the root channels name.

**Comment by henrylaxen** [comment]
Steell: I'm having the same problem.  Did you ever find a solution?

**Comment by abathur** [comment]
Closing since it sounds like Jan answered the narrow question here and this has been stale for a while, but I'm happy to reopen if I'm overstepping.
