### ISSUE TITLE
gnome-terminal: new windows doesn't inherit working directory of current terminal

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#40878]
## Issue description

- Open a gnome-terminal and go to any directory other than $HOME. 
- Right-click in the terminal and click "New Terminal"

A new terminal opens, but the current directory is $HOME.

This has probably always been like this in NixOS. On traditionally systems [vte.sh](https://git.gnome.org/browse/vte/tree/src/vte.sh) is sourced  which exposes the shell $PWD to the terminal.

In NixOS that file lies "dormant" in the store: `/nix/store/*-vte-0.52*/etc/profile.d/vte.sh`

Users can workaround this by manually sourcing the file: `source /nix/store/*-vte-0.52*/etc/profile.d/vte.sh` (probably best to pick the one in gnome-terminal's clousure)

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.09.git.beef7ae (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(ole): `"unstable-18.09pre133621.56fb68dcef4"`
 - channels(root): `"nixos-18.03.132405.ee80654b526, oldnixos-16.09.1943.25f4906da6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Gnome installed by `  services.xserver.desktopManager.gnome3.enable = true;`

**Comment by jtojnar** [comment]
Is that supposed to be done for new windows? It works for me with new tabs, I think.

**Comment by olejorgenb** [comment]
It does after sourcing the vte.sh file so I assume it's intended. I'll check on an other system when I get the chance. 

I get the same behavior with new tabs (does not preserve $PWD when vte.sh is not sourced)

Can you check the content of `$PROMPT_COMMAND` (bash) or `$precmd_functions` (zsh)?

**Comment by jtojnar** [comment]
I use fish-shell and the pwd just seems to be preserved.

**Comment by olejorgenb** [comment]
Seems fish notifies various terminal by itself: https://github.com/fish-shell/fish-shell/blob/e02e485cc6e712879d10fc99034543b7424567fb/share/functions/__fish_config_interactive.fish#L269

**Comment by jtojnar** [comment]
Would something like the following work?

```nix
environment.etc = {
  "profile.d/vte.sh" = {
    source = "${pkgs.gnome3.vte}/etc/profile.d/vte.sh";
  }
};
```

**Comment by hedning** [comment]
The alternative might be to add something like the linked fish config to `gnome.nix`:
```nix
environment.interactiveShellInit = ''
  if [[ "$VTE_VERSION" > 3405 ]]; then
    source "${pkgs.gnome3.vte}/etc/profile.d/vte.sh"
  fi
'';
```

The `vte.sh` script checks returns if the shell isn't bash or zsh, so it should be safe to so.

Did a quick test in a VM and it seems to do the trick.

**Comment by bjornfor** [comment]
For some reason the above snippet doesn't "initialize" for me. I have to manually run ```source "${pkgs.gnome3.vte}/etc/profile.d/vte.sh"```. Weird. I even added some manual trace and see that vte.sh _is_ sourced. But still it doesn't work. I'm using bash, but perhaps I have some untracked stuff in .bashrc that is interfering? I'm currently unable to debug using the NixOS VM. ```nixos-rebuild build-vme && QEMU_OPTS="-m 4096" ./result/bin/run-*-vm``` stops in stage-1 at "mke2fs 1.44.1 (24-Mar-2018)".

**Comment by bjornfor** [comment]
Thanks to 7fc78862033683a8f5e6cbe1764f5bbb6dd726fb I am now able to use "nixos-rebuild build-vm" again (on NixOS 18.03). I can confirm the above patch (https://github.com/NixOS/nixpkgs/issues/40878#issuecomment-390820048) fixes it. (I guess why it doesn't work on my physical laptop is due to some imperative changes in my $HOME.)

@hedning: Would you like to make a PR?

**Comment by chrissound** [comment]
This seems to strangely only work in bash, has anyone gotten this to work with ZSH? I suppose I could source the vte.sh file manually though I'm not sure which path the ${pkgs.gnome3.vte} refers to?

**Comment by hedning** [comment]
I have this patch in my tree which works for ZSH:
```
modified   nixos/modules/services/x11/desktop-managers/gnome3.nix
@@ -180,6 +180,12 @@ in {
                               networkmanager-openconnect networkmanager-fortisslvpn
                               networkmanager-iodine networkmanager-l2tp; };
 
+    environment.interactiveShellInit = ''
+      if [[ "$VTE_VERSION" > 3405 ]]; then
+        source "${pkgs.gnome3.vte}/etc/profile.d/vte.sh"
+      fi
+    '';
+
     # Needed for themes and backgrounds
     environment.pathsToLink = [ "/share" ];
 
```

Kinda forgot about this, should really subit a PR.

**Comment by chrissound** [comment]
I've added that bit into my config and have done a rebuild, but don't get the desired behavior. Where does the `environment.interactiveShellInit` actually output to (which file) - would this not be needed in my .zshrc?

**Comment by hedning** [comment]
It should show up in `/etc/zshrc`.

The exact patch I posted relies on `services.xserver.desktopManager.gnome3.enable = true` btw. You could also include it straight in your configuration if you're not using gnome.

**Comment by chrissound** [comment]
Many thanks @hedning - I'm a bit cautious to try that line as I've previously had various issues with fonts / themes / icons.

I've found a direct copy of `vte.sh` from my old Arch installation and just sourcing that manually for now -\works perfectly! In the event it's useful to someone:

```
# Copyright © 2006 Shaun McCance <shaunm@gnome.org>
# Copyright © 2013 Peter De Wachter <pdewacht@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Not bash or zsh?
[ -n "$BASH_VERSION" -o -n "$ZSH_VERSION" ] || return 0

# Not an interactive shell?
[[ $- == *i* ]] || return 0

# Not running under vte?
[ "${VTE_VERSION:-0}" -ge 3405 ] || return 0

__vte_urlencode() (
  # This is important to make sure string manipulation is handled
  # byte-by-byte.
  LC_ALL=C
  str="$1"
  while [ -n "$str" ]; do
    safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}"
    printf "%s" "$safe"
    str="${str#"$safe"}"
    if [ -n "$str" ]; then
      printf "%%%02X" "'$str"
      str="${str#?}"
    fi
  done
)

# Print a warning so that anyone who's added this manually to his PS1 can adapt.
# The function will be removed in a later version.
__vte_ps1() {
  echo -n "(__vte_ps1 is obsolete)"
}

__vte_osc7 () {
  printf "\033]7;file://%s%s\007" "${HOSTNAME:-}" "$(__vte_urlencode "${PWD}")"
}

__vte_prompt_command() {
  local pwd='~'
  [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
  printf "\033]0;%s@%s:%s\007%s" "${USER}" "${HOSTNAME%%.*}" "${pwd}" "$(__vte_osc7)"
}

case "$TERM" in
  xterm*|vte*)
    [ -n "$BASH_VERSION" ] && PROMPT_COMMAND="__vte_prompt_command"
    [ -n "$ZSH_VERSION"  ] && precmd_functions+=(__vte_osc7)
    ;;
esac

true

```

**Comment by hedning** [comment]
Sorry, guess I wasn't clear. I meant including
```nix
    environment.interactiveShellInit = ''
      if [[ "$VTE_VERSION" > 3405 ]]; then
        source "${pkgs.gnome3.vte}/etc/profile.d/vte.sh"
      fi
    '';
```
in your `/etc/nixos/configuration.nix`, that way it isn't hidden behind the `gnome3.enable` flag.

**Comment by worldofpeace** [comment]
I'm struggling to find a way to represent that configuration snippet as a nixos option that can be generalized to just mean `bash` or `zsh` support for vte terminals.

For example it could be `programs.vte.enableBashIntegration` but vte isn't a program.

**Comment by Kjuvi** [comment]
> I'm struggling to find a way to represent that configuration snippet as a nixos option that can be generalized to just mean `bash` or `zsh` support for vte terminals.
> 
> For example it could be `programs.vte.enableBashIntegration` but vte isn't a program.

Since the VTE lib comes from `gnome3.vte`,  what about something like `environment.gnome3.enableBashIntegration` ?
In the same way we have `environment.gnome3.excludePackages`.

`environment` also have a bunch of shell configuration (`loginShellInit`, `shellAlias`, `shells`, ...), so it could make sens.

**Comment by worldofpeace** [comment]
Yay, great suggestion @Kjuvi. I can do that :+1:

**Comment by chrissound** [comment]
My old solution posted no longer seems to work after upgrading to nixos 20.09. I can't seem to find the actual solution to this, any pointers?

**Comment by worldofpeace** [comment]
@chrissound What was your old solution? If you enable gnome-terminal you will have the vte module enabled. If not enable them manually https://search.nixos.org/options?channel=20.09&from=0&size=30&sort=relevance&query=vte

**Comment by chrissound** [comment]
I've got:
```
  programs.zsh.vteIntegration = true;
  programs.bash.vteIntegration = true;
  programs.gnome-terminal.enable = true;
```

However I still seem to run into the same issue, after running `systemctl restart --user gnome-terminal-server`.

As for the old solution - that was sourcing the vte.sh file I had from arch linux.

**Comment by chrissound** [comment]
I managed to fix this by setting `Preferences > Profiles > *** > Command > Preserve working directory` to `Always` instead of `Shell only`.

No idea if this setting perhaps got reset somehow - but it worked previously. :)
