### ISSUE TITLE
security.acme

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#40874]
## Issue description

on 18.03 we see that the `postRun` hook is not executed and therefore the services to be reloaded/restarted are not reloaded/restarted and keep running with the initial selfsigned certificates or with the old ones which are about to run out.

is there a good reason for having a https://github.com/NixOS/nixpkgs/blame/164ead312e6c1c7eb455cbcd251cb7b603eef298/nixos/modules/security/acme.nix#L183

instead of just doing the reload/restart from here https://github.com/NixOS/nixpkgs/blame/164ead312e6c1c7eb455cbcd251cb7b603eef298/nixos/modules/security/acme.nix#L180

my suspicion is that the shared variable `/tmp/lastExitCode`, because of using `privateTmp`, has vanished and thus the postRun is never executed on our 18.03 servers.

we are using it with `nixcloud.TLS` and the generated `security.acme` scripts look exactly like they should be but as i mentioned the restart/reload is never executed altough valid let's encrypt certificates were retrieved. 

i removed the certificates and started the query anew just to make sure -> again, no reload/restart

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by aanderse** [comment]
@qknight is this still an issue in 18.09? I've been running this on numerous servers for a long time and haven't had any issues with my certificates.

**Comment by qknight** [comment]
@aanderse the new `nixcloud.TLS` implementation does not use `security.acme` anymore so it is save to close this now. see https://github.com/nixcloud/nixcloud-webservices/blob/master/documentation/nixcloud.TLS.md

we are also using `lego` instead of `simp_le`. 

thanks for bringing that up
