### ISSUE TITLE
ksysguard desktop file does not have an Exec line

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#40916]
## Issue description
Related to #40915

`kbuildsycoca5`
```    
kbuildsycoca5 running...
kf5.kservice.services: The desktop entry file "/run/current-system/sw/share/applications/org.kde.systemmonitor.desktop" has Type= "Application" but no Exec line
kf5.kservice.sycoca: Invalid Service :  "/run/current-system/sw/share/applications/org.kde.systemmonitor.desktop"
```

### Steps to reproduce
Run `kbuildsycoca5` with `ksysguard` installed.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.03.132405.ee80654b526 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03, nixos-unstable, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by peterhoeg** [comment]
```ksysguard``` and its corresponding ```.desktop``` file exists in two places which is clearly wrong:

 - ```plasma-workspace.bin```, and
 - ```ksysguard```

@adisbladis @bkchr

**Comment by bkchr** [comment]
I think this issue is already solved with latest master?

**Comment by Chiiruno** [comment]
@bkchr Are you referencing #42639

**Comment by bkchr** [comment]
No, I did not read the description correctly...

But with the following pr: https://github.com/NixOS/nixpkgs/pull/43288
It should be really solved ^^

**Comment by Chiiruno** [comment]
Sounds great, when it's pulled I'll test and close.

**Comment by bkchr** [comment]
@Chiiruno the pull request was merged.

**Comment by Chiiruno** [comment]
Okay thanks.
I'll test this tomorrow and close.

**Comment by Chiiruno** [comment]
It works!
