### ISSUE TITLE
flex does not install libfl.{a,so}

### ISSUE THREAD

**Issue by sgraf812** [NixOS/nixpkgs#40918]
## Issue description

Installing the `flex` package makes available the `flex` binary, but not the libraries that you are required to link with, e.g. `libfl.{a,so}`. 

### Steps to reproduce

1. `$ echo "%%" > repro.l`
1. `$ flex repro.l` 
1. `$ cc lex.yy.c -lfl`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-20-generic, Ubuntu, 18.04 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(sgraf): `"nixpkgs-18.09pre140702.c68996f147a"`
 - nixpkgs: `/afs/info.uni-karlsruhe.de/user/sgraf/.nix-defexpr/channels/nixpkgs`

**Comment by dezgeg** [comment]
Can't reproduce:

````
$ find $(nix-build -A flex)/lib
/nix/store/ppn0x6csda68xjrwqq9jinlr939x8fr6-flex-2.6.4/lib
/nix/store/ppn0x6csda68xjrwqq9jinlr939x8fr6-flex-2.6.4/lib/libfl.so.2
/nix/store/ppn0x6csda68xjrwqq9jinlr939x8fr6-flex-2.6.4/lib/libfl.so.2.0.0
/nix/store/ppn0x6csda68xjrwqq9jinlr939x8fr6-flex-2.6.4/lib/libfl.la
/nix/store/ppn0x6csda68xjrwqq9jinlr939x8fr6-flex-2.6.4/lib/libfl.so
````

**Comment by sgraf812** [comment]
Hmm... `nix-build -A flex` only complains that it couldn't find a `default.nix` file:

```
error: getting status of '/afs/info.uni-karlsruhe.de/user/sgraf/default.nix': No such file or directory
```

**Comment by dezgeg** [comment]
You need to do that in a nixpkgs checkout.

**Comment by symphorien** [comment]
I guess that you have installed flex with `nix-env`: this won't work. See https://nixos.wiki/wiki/FAQ/Libraries
Try compiling inside `nix-shell -p flex` instead.

**Comment by sgraf812** [comment]
Very helpful, thanks!
