### ISSUE TITLE
nm-applet failed to show notification

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#40926]
## Issue description

On a machine which has XFCE installed, running `nm-applet`, including on i3 works fine.
But on a machine which only has i3, running `nm-applet` gives me:

```
(nm-applet:14035): libnotify-WARNING **: Failed to connect to proxy

(nm-applet:14035): nm-applet-WARNING **: Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

and doesn't show any icon in the tray.

### Steps to reproduce

I used

```
networking.networkmanager.enable = true;
environment.systemPackages = [ pkgs.networkmanagerapplet ];
users.extraUsers.theo.extraGroupes = [ "networkmanager" ];
```

The answer [here](https://unix.stackexchange.com/questions/104364/networkmanager-applet-after-click-on-network-no-window-or-error/282489#282489) hints that this could be a problem of missing dependencies...

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.34, NixOS, 18.03.132021.c0c5571ec1a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(theo): `"nixpkgs-17.03pre95548.8ef3eae"`
 - channels(root): `"nixos-18.03.132021.c0c5571ec1a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by jtojnar** [comment]
Your desktop environment should contain some notification server, see https://wiki.archlinux.org/index.php/Desktop_notifications. I guess that would be `xfce4-notifyd` on XFCE.

**Comment by Zimmi48** [comment]
Thanks @jtojnar! This was the issue indeed.
