### ISSUE TITLE
Clang can't be used to cross-build packages.

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#40934]
## Issue description
It seems that clang can't be used to cross-build packages, at least not in the way Nixpkgs documentation would suggest.

### Steps to reproduce
Consider this test:

```nix
with import ./default.nix {crossSystem = (import ./lib).systems.examples.aarch64-multiplatform;};
let testdrv = { callPackage
              , stdenv
              }: stdenv.mkDerivation
    {
        name = "cross-test";
        version = "0.1";
        unpackPhase = "true";
        buildPhase = ''
            echo 'int main() { return 0; }' > main.c
            echo ${stdenv.cc}
            $CC -o cctest main.c
            '';
        installPhase = ''
            mkdir $out
            cp cctest $out
        '';
    };
in { gcc-cross-test   = callPackage testdrv {};
     clang-cross-test = callPackage testdrv {stdenv = clangStdenv;};
   }
```

When running `nix-build -E "(import ./cross-test.nix).gcc-cross-test`, eventually a cross-compiling GCC/binutils and aarch64 libc is built. However, `nix-build -E "(import ./cross-test.nix).clang-cross-test` seems to try (and fail, see https://github.com/NixOS/nixpkgs/issues/40602) to build clang itself for aarch64 (`clang-5.0.1-aarch64-unknown-linux-gnu` with current master). From what I understand Clang itself is always a cross compiler. I suppose I was expecting Nix to build a cc-wrapper for Clang that just adds the appropriate flags (`-target <triple>`, etc.). Using `clangMultilibStdenv` seems to yield the same results.

I see that @Ericson2314 has done some work over in https://github.com/NixOS/nixpkgs/issues/36867, but it's unclear what machinery presently exists in master, to what degree that machinery works, and where current efforts are being applied. There's a chance I'm totally misunderstanding this, too; I've only recently attempted cross compiling things with Nix. It seems there's some cross-compiling magic somewhere in the GCC bootsrapping/stdenv that causes `crossSystem = ...` to do the right thing. Does similar (hopefully much simpler!) machinery simply need to be built for clang?

**Comment by Ericson2314** [comment]
Yeah the work just needs to be done. This is exactly what https://github.com/NixOS/nixpkgs/issues/36867 was supposed to track, haha. You have a change making cross compil*ed* LLVM use `buildPackages.llvm` for the table gen thing? I'd like to apply that first, even though it's technically unrelated.

**Comment by Ericson2314** [comment]
[And btw, we should be some cross tests in pkgs/test like your OP.]

**Comment by matthewbauer** [comment]
It looks like @ElvishJerricco's wasm-cross has gotten pretty far on this:

https://github.com/WebGHC/wasm-cross

**Comment by matthewbauer** [comment]
@ericson2314 Can this be closed?

**Comment by TravisWhitaker** [comment]
@matthewbauer Why was this closed? The test in the original issue report still fails. Right now (12bb60fc18e0b4d1a45f4953ec0b8be034508c2f) `compiler-rt-5.0.2-aarch64-unknown-linux-gnu` seems broken. Is there a pending PR somewhere that fixes this?

**Comment by matthewbauer** [comment]
This example works:

```
with import ./default.nix {
  crossSystem = (import ./lib).systems.examples.aarch64-multiplatform-musl // { useLLVM = true; };
};
let testdrv = { callPackage
              , stdenv
              }: stdenv.mkDerivation
    {
        name = "cross-test";
        version = "0.1";
        unpackPhase = "true";
        buildPhase = ''
            echo '#include <stdio.h>' >> main.c
            echo 'int main() { printf("llvm aarch64 build\n"); return 0; }' >> main.c
            echo ${stdenv.cc}
            $CC -o cctest main.c
        '';
        installPhase = ''
            mkdir $out
            cp cctest $out
            ${stdenv.hostPlatform.emulator buildPackages} $out/cctest
        '';
    };
in { clang-cross-test = callPackage testdrv {}; }
```

In addition, instead of ```clangStdenv```, you can use ```overrideCC stdenv buildPackages.buildPackages.llvmPackages_7.lldClang```, but note this does not support c++ currently. Also this will only use clang for that one derivation

**Comment by TravisWhitaker** [comment]
@Ericson2314 Is there any way to get a working cc-wrapper that uses `buildPlatform.clang` yet?
