### ISSUE TITLE
Remove alias for udiskie

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#40941]
See https://github.com/NixOS/nixpkgs/pull/40830#issuecomment-390765431. 

/cc @FRidh @dotlambda

**Comment by dotlambda** [comment]
This could be generalized: all aliases added in 8d9f170 should be removed.

**Comment by dotlambda** [comment]
How about setting
```
udiskie = abort "pythonPackages.udiskie has been replaced by udiskie"
```
in `python-packages.nix`?
