### ISSUE TITLE
Python: `No module named pkg_resources` in develop mode

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#40971]
## Issue description

As I am trying to quickly iterate/debug a package (the systemwide python package install works fine but I want to run it in develop mode to debug its interactions with other components) I want to add to nixpkgs, I've written this shell.nix :
```
with import <nixpkgs> {};

pythonPackages.buildPythonApplication {
  name = "mininet";
  version="alpha";

  propagatedBuiltInputs = [ 
    pythonPackages.setuptools 
  ];
  src = ./.;

}

```
Then I run `$ nix-shell` and starts the python application called `mn`. If I start it with just `mn`, it starts ok but doesn't have the right to communicate with the other components. If I start it with sudo it fails with
```
sudo mn -v debug --switch ovsk
Traceback (most recent call last):
  File "/run/user/1000/tmp.pz8zG9r521/bin/mn", line 4, in <module>
    __import__('pkg_resources').require('mininet===2.3.0d1')
ImportError: No module named pkg_resources
```

I've seen that some packages tend to write
```
    postInstall = ''
      echo "__import__('pkg_resources').declare_namespace(__name__)" >> "$out/lib/${python.libPrefix}"/site-packages/azure/__init__.py
      echo "__import__('pkg_resources').declare_namespace(__name__)" >> "$out/lib/${python.libPrefix}"/site-packages/azure/mgmt/__init__.py
    '';
```

not sure that would work in nix-shell ?

@FRidh any idea as how to fix it or work around ? I need to make frequent changes to the python code so I insist on the develop mode `src=./.;`.

## Technical details
nixos-unstable

**Comment by teto** [comment]
I've updated the previous issue with some details on the sudo aspect of the problem. Even with ` sudo -E` I get the error. As a workaround, I run `sudo nix-shell` and it seems ok.

**Comment by davidak** [comment]
I get the same issue when inside a nix-shell and execute tool i installed using pip.

```
nix run '((import <nixpkgs> {}).python35.withPackages (ps: with ps; [pip bcrypt cryptography lxml pynacl]))'
pip install --user https://github.com/greenbone/gvm-tools/archive/1.3.1.tar.gz
[davidak@nixos:~/code/gsm-performance-check]$ gvm-cli socket --xml "<get_version/>"
Traceback (most recent call last):
  File "/home/davidak/.local/bin/gvm-cli", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

**Comment by FRidh** [comment]
@davidak check the shebang of `gvm-cli`. You'll see it points to the non-wrapped Python executable. That's why it is not working. At some point, `setuptools` replaces the generic shebang with an absolute one, and for that it tries to determine the location of the interpreter. Clearly it does not consider the wrapped one.

I for one have no intention in looking into this as the supported way of working is "write a nix expression", but maybe someone else does.

Also, I don't think this is the same issue as reported by @teto despite the same error message.

**Comment by davidak** [comment]
@FRidh thanks. I then write a nix expression for it and maybe add to nixpkgs later.

**Comment by rnhmjoj** [comment]
I've just found this same error trying to run subliminal today (it worked fine until recently).

**Comment by FRidh** [comment]
> As a workaround, I run sudo nix-shell and it seems ok.

That could mutate the store.

This is an old issue, and the Python infra has changed since then, so I am closing this.

@rnhmjoj pretty sure your issue is different, see As a workaround, I run sudo nix-shell and it seems ok.
