### ISSUE TITLE
dd-agent doesn't allow many config options

### ISSUE THREAD

**Issue by shmish111** [NixOS/nixpkgs#40980]
## Issue description

I need my dd-agent config to have `non_local_traffic: yes` but https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/monitoring/dd-agent/dd-agent.nix#L8 only allows overriding of some specific options. Looks from history that there used to be an option to add lines but it has been removed. This means for one thing that I can't access dogstatsd from docker containers :-(

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by peterhoeg** [comment]
Maybe @fuuzetsu has some thoughts as he change the service def.

**Comment by rvl** [comment]
I have opened PR #40399 with a new module for datadog-agent v6. This adds extensible config like in @Fuuzetsu's change but without breaking the dd-agent module API.

**Comment by peterhoeg** [comment]
Fixed in #40399.
