### ISSUE TITLE
Case-sensitivity of package name

### ISSUE THREAD

**Issue by k0ral** [NixOS/nixpkgs#4099]
I noticed `nix-env` is currently case-sensitive on the package name. It took me some time to notice some packages because of the presence of uppercase characters in their name.
When no package matches a given name case-sensitively, it would be great to at least suggest case corrections, or even look for case-insensitive matches. What do you think ?

**Comment by domenkozar** [comment]
I really think we should follow upstream if possible. It's easier to match upstream for (security) updates.

**Comment by domenkozar** [comment]
Let's merge this discussion to https://github.com/NixOS/nixpkgs/issues/11052
