### ISSUE TITLE
Package name normalization

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#41007]
## Issue description
I don't think there's an issue for this, so wanted to open this. Just some things to make package naming more consistent.

- [ ] All packages have a version
- [ ] Packages versions of dates unified (YYYY.MM.DD vs. YYYYMMDD vs. YYYY-MM-DD)
- [ ] Remove commit hash versions, replace with either "pre" style or dates
- [ ] Use "pre" suffix where appropriate over dates & commits
- [ ] Get rid of ```-git``` suffix wherever possible
- [ ] Remove other "flavor" suffixes wherever possible (```-sdl```, ```-gtk```, ```-qt```, ```-cli```) - needs community feedback

Some of these need community feedback on which is the "correct" way to do things. Unofficial releases are always hard to get right but I think we can settle on a standardized date scheming, hopefully in a way that preserves the ```nix-env -u``` behavior.

**Comment by primeos** [comment]
A few guidelines are specified in the nixpkgs manual: https://nixos.org/nixpkgs/manual/#sec-package-naming, e.g.:
> - If a package is not a release but a commit from a repository, then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also append "unstable" to the name - e.g., "pkgname-unstable-2014-09-23".

**Comment by jtojnar** [comment]
Related – attribute name standardization: https://github.com/NixOS/nixpkgs/issues/17625, https://github.com/NixOS/nixpkgs/issues/32804

**Comment by Anton-Latukha** [comment]
I would say that obvious stuff, that everyone probably knows, and as happens in those situations stays not said.

I don't see the other than YYYY-MM-DD format.
It is IT and industrial default, also because it is standardized by [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard as the default.

**Comment by ryantm** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/41162

**Comment by ryantm** [comment]
We need a derivation linter that can help us discover which packages are not compliant with the rules in the OP. Has anyone done work on that?

**Comment by matthewbauer** [comment]
@ryntm Not exactly but you can use this to find packages with incorrect versioning:

https://gist.github.com/matthewbauer/e21eb80b695c2b52b502b7c66c216ae3

It will list all packages with names that are not parsable by parseDrvName.

**Comment by matthewbauer** [comment]
Closing for now.
