### ISSUE TITLE
Expose more features in the dnscrypt-proxy module

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#41022]
## Issue description

I want to control the cache for dnscrypt-proxy, but that option is not exported in the module. 

See https://github.com/jedisct1/dnscrypt-proxy/wiki/Caching#dns-cache for the description of the future. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.03.git.ee80654 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ryneeverett** [comment]
The cache options can be set via `services.dnscrypt-proxy2.settings` or `services.dnscrypt-proxy2.configFile`.
