### ISSUE TITLE
home-assistant fails to load when component doesn't have dependencies

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#41028]
## Issue description

Before HA 0.69, the upstream requirements file listed ```notify.matrix``` however since 0.69 that is no longer the case. As a consequence when trying to add a matrix notifier, things will fail with:

```
error: attribute 'notify.matrix' missing, at /home/peter/src/active/nixpkgs_unstable/pkgs/servers/home-assistant/default.nix:69:28
```

Adding in a dummy like this in ```component-packages.nix``` makes things work again:

```
    "notify.matrix" = ps: with ps; [  ];
```

Cc: @dotlambda 

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.9, NixOS, 18.09.git.3864e6e9515M (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `""`
 - channels(peter): `""`
 - nixpkgs: `/home/peter/src/active/nixpkgs_unstable`
```

**Comment by peterhoeg** [comment]
Sorry, I should have been clearer. There *is* a ```notify.matrix``` component but it is not listed in ```requirements.txt``` because the functionality is provided using the ```matrix``` component (matrix vs notify.matrix) - see https://www.home-assistant.io/components/matrix/ and https://www.home-assistant.io/components/notify.matrix/

**Comment by peterhoeg** [comment]
How about a mapping of components to other component dependencies so that the parse script can generate the correct entry?

I don't know if there are others than the matrix component but it wouldn't be too far fetched to assume that this was the case.

So ```notify.matrix``` gets written out to the components file with the dependencies of ```matrix```.

**Comment by dotlambda** [comment]
There are definitely others, with the most notable one being the history component which depends on the recorder component which requires the SQLAlchemy package.
There is currently no way of detecting these dependencies in `parse-requirements.py`. However, it is possible using the `DEPENDENCIES` list exported by each component, see e.g. https://github.com/home-assistant/home-assistant/blob/0.69.1/homeassistant/components/notify/matrix.py#L21. This would require downloading the Home Assistant source tarball, importing each component and looking up its dependencies in `parse-requirements.py`. There is https://github.com/home-assistant/home-assistant/blob/0.69.1/script/gen_requirements_all.py which can serve as a guide on how to do that.

**Comment by peterhoeg** [comment]
The alternative is to define in ```parse-requirements.py``` which components have dependencies on others. That would have to be manually maintained (which isn't ideal) but would be a quick way to get things going.
