### ISSUE TITLE
Kate fails to start unless QT_QPA_PLATFORM_PLUGIN_PATH is set

### ISSUE THREAD

**Issue by clacke** [NixOS/nixpkgs#41026]
## Issue description

Kate fails with:

    This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

### Steps to reproduce

```
$ nix-shell --pure -p kate --run "XAUTHORITY=$XAUTHORITY DISPLAY=$DISPLAY kate"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
```

This works (kate starts, opens its main window, runs fine):
```
$ nix-shell --pure -p kate --run "XAUTHORITY=$XAUTHORITY DISPLAY=$DISPLAY QT_QPA_PLATFORM_PLUGIN_PATH=$(nix-build '<nixpkgs>' -A qt5.qtbase)/lib/qt-5.10/plugins/platforms kate"
```

`qtbase` should probably set that variable, and `kate` wrap it?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3254.967e40787c5 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixpkgs-18.09pre140004.425ff431aba, nixos-17.09.3254.967e40787c5"`
 - channels(clacke): `"nixpkgs-18.09pre140004.425ff431aba"`
 - nixpkgs: `/home/clacke/.nix-defexpr/channels/nixpkgs`

**Comment by clacke** [comment]
Same `kate` hash:

    $ nix-shell -p kate --run 'file $(which kate)'
    /nix/store/pm35jrp2nagsj0cw88svj8k9pn94jmi4-kate-18.04.1/bin/kate: ELF 64-bit

**Comment by peterhoeg** [comment]
The issue is that the qt/kde applications don't work well (or at all) unless installed using ```environment.systemPackages```. Sorry, I should have noticed that from the beginning.

**Comment by clacke** [comment]
What is it that makes them work as system packages? Must be some environment variable somewhere, right?

**Comment by peterhoeg** [comment]
No, it's not quite that simple unfortunately: https://github.com/NixOS/nixpkgs/issues/24256#issuecomment-328349797

Your two options are:
1. Install in ```environment.systemPackages```
2. Set the variable manually

**Comment by clacke** [comment]
> I believe setting that variable in the wrapper will break the application under KDE.

Ok, that settles it then. Thanks for the clear information.

**Comment by clacke** [comment]
For any passers-by who happen to read this:

It's not necessary to install KDE and it's not necessary to install anything system-wide. Simply installing with `nix-env -iA nixpkgs.kate` makes kate work without issues.

It finds the appropriate things via your profile, it's only the environment method via `nix-shell` that doesn't work.

**Comment by peterhoeg** [comment]
While that is technically true, having Qt applications in both the system environment as well as user environments has its own problems in case they happen to be updated at different times. If you have application A in the system environment that depends on Qt 5.9.2 and application B that depends on Qt 5.9.3 just because they were installed at different times, depending on the load order one of them will stop working.

**Comment by clacke** [comment]
Right, that would be an issue. My comment is meant only from the perspective of "what do I need to do to make my program start?". To reframe it to be clear:

If you have a Qt program that won't start from platform plugin load failure when you `nix-shell` it, your three options are:

1.    Install in `environment.systemPackages`.
1.    Set `QT_QPA_PLATFORM_PLUGIN_PATH`.
1.   Install in your profile with `nix-env`.

**Comment by clacke** [comment]
The my Qt vs system Qt issue sounds like a tough nut to crack.
