### ISSUE TITLE
export to repology: names from haskellPackages.* leaked to toplevel namespace

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#41047]
## Issue description

```nix_unstable``` and ```nix_stable``` took 2st and 3rd places by total number of packages (seconding only to AUR), but most of the "packages" are leaked to toplevel namespace from haskellPackages.* 

### Steps to reproduce

https://repology.org/repository/nix_unstable

cc @peti @ryantm

**Comment by ryantm** [comment]
This is on purpose https://github.com/NixOS/nixos-homepage/pull/201

**Comment by xeji** [comment]
related: #41029

**Comment by volth** [comment]
closed as dup of #41029
