### ISSUE TITLE
ghc842 needs update to criterion_1_4_1_0

### ISSUE THREAD

**Issue by infinity0** [NixOS/nixpkgs#41053]
On master branch, `configuration-hackage2nix.yaml` still says `criterion ==1.3.0.0` but this requires `base-compat (==0.9.*)` and we need 0.10 to work with GHC 8.4.

Sorry for lack of PR for such a trivial issue, but I'm not familiar with Nix syntax and unsure if my changes would affect the other derivations like ghc822 etc.

**Comment by maralorn** [comment]
This is long resolved.
