### ISSUE TITLE
Can't disable NixOS service modem-manager

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#41055]
## Issue description
Given following module change:
```
{
  networking.network-manager.enable = true;
}
---->
{
  networking.network-manager.enable = true;
  systemd.services.modem-manager.enable = false;  # <-- this line was added
}
```
We get inconsistent behavior on activation:
1. When doing `nixos-rebuild switch`, `modem-manager` service is stopped.
2. But on system start (or reboot), `modem-manager` service is started. On subsequent `nixos-rebuild switch` it is stopped.

### Steps to reproduce
When using Network Manager try to disable Modem Manager service. Even it is stopped, it is then started after reboot

Reported in https://discourse.nixos.org/t/permanently-disable-systemd-services/263/1

## Technical details

NixOS 18.03

**Comment by zimbatm** [comment]
I don't see any modem-manager service being declared in nixpkgs/nixos.

Can you give me the output of `systemctl cat ModemManager` or `systemctl cat modem-manager`? I suspect that this is a user service that is being spawned by network-manager itself as I don't see it on my system.

**Comment by danbst** [comment]
@zimbatm 

it is defined here https://github.com/NixOS/nixpkgs/blob/db920b5a0ab4b71f5388f9b138e7e15ff4e112f4/nixos/modules/services/networking/networkmanager.nix#L136 and is used by `systemd.packages` here https://github.com/NixOS/nixpkgs/blob/db920b5a0ab4b71f5388f9b138e7e15ff4e112f4/nixos/modules/services/networking/networkmanager.nix#L331

So, `modem-manager` service file comes from `modemmanager` package. It isn't defined as NixOS `systemd.services`, however activation script **should** do the merge of both (like in OP-post example)

https://github.com/NixOS/nixpkgs/blob/db920b5a0ab4b71f5388f9b138e7e15ff4e112f4/nixos/modules/system/boot/systemd-lib.nix#L135-L160

**Comment by zimbatm** [comment]
Okay, that explains why the disable doesn't work. I was specifically looking for a service module declaration.

If the unit was declared with the NixOS module system it would not be there upon reboot so the activation scripts doesn't need to disable it again. That explains why the logic doesn't handle that corner-case.

**Comment by danbst** [comment]
Oh, thanks for investigation! It happens to be some shitty misunderstanding.

`modemmanager` package has following files:
```
$ ls -l /nix/store/gk6h88clacdzqyq8zb7d24pp92blwn45-modem-manager-1.7.990/etc/systemd/system/
total 8
lrwxrwxrwx 1 root root 106 Jan  1  1970 dbus-org.freedesktop.ModemManager1.service -> /nix/store/gk6h88clacdzqyq8zb7d24pp92blwn45-modem-manager-1.7.990/etc/systemd/system/modem-manager.service
-r--r--r-- 1 root root 461 Jan  1  1970 modem-manager.service
```
So, there are 2 services, one is a symlink to another.

We have then following situation in `/etc/systemd/system`:
```
$ ls -l /etc/systemd/system/ | grep -i modem
lrwxrwxrwx 1 root root  127 Jan  1  1970 dbus-org.freedesktop.ModemManager1.service -> /nix/store/gk6h88clacdzqyq8zb7d24pp92blwn45-modem-manager-1.7.990/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service
lrwxrwxrwx 1 root root    9 Jan  1  1970 modem-manager.service -> /dev/null
```
Again, 2 services, but they don't link one to another now! NixOS properly masked `modem-manager.service` by pointing it to `/dev/null`, but the other still points to a symlink to a proper service inside `modemmanager` package.

What makes things especially bad is that systemd chooses name `ModemManager`, based of final service symlink target `modem-manager.service`. But which one does systemd starts?

```
May 23 20:32:33 station dbus[784]: [system] Activating via systemd: service name='org.freedesktop.ModemManager1' unit='dbus-org.freedesktop.ModemManager1.service'
May 23 20:32:33 station ModemManager[1717]: <info>  ModemManager (version 1.7.990) starting in system bus...
May 23 20:32:33 station dbus[784]: [system] Successfully activated service 'org.freedesktop.ModemManager1'
May 23 20:32:36 station ModemManager[1717]: <info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:1d.2/0000:04:00.0': not supported by any plugin
May 23 20:32:36 station ModemManager[1717]: <info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:1d.3/0000:05:00.0': not supported by any plugin
```

-----

So, there are two solutions to this problem. One is disable 2 services:
```
  systemd.services.modem-manager.enable = false;
  systemd.services."dbus-org.freedesktop.ModemManager1".enable = false;
```
Another is to fix package:
https://github.com/NixOS/nixpkgs/blob/c6882b2cf9fa13579f64d5c33cbc071fa5d5e884/pkgs/tools/networking/modem-manager/default.nix#L41-L55

But I don't know how...

**Comment by spinus** [comment]
@danbst did you try ``mkForce false``?

**Comment by danbst** [comment]
@spinus yup, it was my first dumb guess too https://discourse.nixos.org/t/permanently-disable-systemd-services/263/2?u=danbst

But the core problem here is with package itself - it provides two services (`$out/etc/systemd/system/modem-manager.service` and `$out/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service`), which systemd can handle as one service, but NixOS treats as separate services.

That explains why after `nixos-rebuild switch` both are stopped - because systemd handles service stop.

That also explains why both services should be disabled in NixOS configuration - otherwise one of them will be started on boot (systemd has lost information, that those services are linked to each other).

**Comment by Schweber** [comment]
I'm sorry, what is the solution now? How do i disable modem manager?

**Comment by KCynk** [comment]
Problem still exists: 
https://github.com/NixOS/nixpkgs/issues/298741

**Comment by jtojnar** [comment]
The service aliases have been removed in 3f9ac24d531090a6b49afd212b5cf2b78c825b94 and 447d625edc3a488deee1c9b2e5890dd974e55ee3.
