### ISSUE TITLE
Test suite of Hasktags fails with GHC 8.4.2 and so I can't install it

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#41079]
## Issue description

Test suite of Hasktags fails with GHC 8.4.2 and so I can't install it.

### Steps to reproduce

```
$ nix-shell -p haskell.packages.ghc842.hasktags
<...>
Running 1 test suites...
Test suite testsuite: RUNNING...
### Failure in: 6:16.hs:0:these were not found
tests/Test.hs:39
expected: ["t2","t3","t4","t5"]
 but got: []
Cases: 156  Tried: 156  Errors: 0  Failures: 1
Test suite testsuite: FAIL
Test suite logged to: dist/test/hasktags-0.70.1-testsuite.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/m10707l816lryx3rk4279jpa82mi1bbd-hasktags-0.70.1.drv' failed with exit code 1
error: build of '/nix/store/m10707l816lryx3rk4279jpa82mi1bbd-hasktags-0.70.1.drv' failed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.42, NixOS, 18.09pre140682.5da85431fb1 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `"nixos-18.09pre140682.5da85431fb1"`
 - channels(mark): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mrkkrp** [comment]
Seems to be a known issue, maybe we should disable running tests for this package?

https://github.com/MarcWeber/hasktags/issues/52

**Comment by peti** [comment]
I'd like upstream to release a fix -- either by fixing the issue or by disabling that particular failing test. If that doesn't work out for some reason, then we should probably disable the test suite altogether, yes.

**Comment by jhenahan** [comment]
I'll split off a develop branch (which I should probably do, anyway), and remove the failing testcases from master, then push a new release without the failing cases.

**Comment by mpickering** [comment]
Now fixed: https://github.com/NixOS/nixpkgs/commit/9c32d185d12f48a996b9b4fb3999c41d7445e548
