### ISSUE TITLE
buildRustPackage installs cdylib to /bin

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#41090]
When I build a `cdylib`, for example, the following random package:

```nix
{ rustPlatform, fetchFromGitHub }:

rustPlatform.buildRustPackage rec {
  name = "foo";

  src = fetchFromGitHub {
    owner = "mhelmetag";
    repo = "levenshtein";
    rev = "7a2e90e11833645ea3d9e939dcd907896da8b49c";
    sha256 = "0jb4qrz08bda1zl26zsigx86qs4aaqysgds63bd3chjsd2hv2x4y";
  };

  cargoSha256 = "1fs0a7sxv4clsq0jr9lm8ld3v7l8mbdwswq7dspx5xinbryg15xc";
}
```

it produces a directory tree like this one:

```
result
└── bin
   └── liblevenshtein.so
```

The library is installed to `$out/bin` instead of `$out/lib`.

cc @P-E-Meunier

**Comment by dywedir** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/commit/6ad43a0bce3603b25bcadb458d39701616d245f4 + https://github.com/NixOS/nixpkgs/commit/64d0676fe1cafc47d710f0e62ff1139814e314ad

**Comment by jtojnar** [comment]
Thanks.
