### ISSUE TITLE
Plasma: systemsettings5 crashes when selecting display settings

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#41146]
## Issue description

Selecting "Displays and Monitor" or "Displays" results in a segmentation fault.

I've opened an issue upstream as well:
https://bugs.kde.org/show_bug.cgi?id=394756

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.03.132507.5f2da7f837e (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03"`
 - channels(freddy): `"nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by bkchr** [comment]
@peterhoeg reported something similar. Does gdb does give you a backtrace with `bt`?

**Comment by peterhoeg** [comment]
Yep, I've been seeing the the same thing since 5.12.3 or .4. I did not however, report it upstream... :blush:

**Comment by peterhoeg** [comment]
With latest unstable (and plasma 5.13, kde-frameworks 5.47, kde-apps 18.04.2, qt 5.11), systemsettings no longer crash for me.

**Comment by FRidh** [comment]
I have not tested as I run stable.

**Comment by FRidh** [comment]
Switched to unstable, and I don't have the issue there.
