### ISSUE TITLE
pkgs.xorg should use newScope

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixpkgs#41154]
## Issue description
it is basically imposible to override things like `pkgs.xorg.libX11` because things like `xorg.libXrandr` refer to it within a `rec {` set

if it was redone like this:
```
let
  packages = self: {
    libX11 = self.callPackage .... {};
    libXrandr = self.callPackage ... {};
  };
in pkgs.lib.makeScope pkgs.newScope packages
```
then you can more easily refer to other packages within that set, and it can also support `xorg = pkgs.xorg.overrideScope` to insert overrides into it

**Comment by LunNova** [comment]
Still an issue, ran into while trying to override `xorg.fontbhlucidatypewriter100dpi`.

**Comment by Artturin** [comment]
It uses `makeScopeWithSplicing'` now
