### ISSUE TITLE
cmake.x86_64-darwin broken, now requires ApplicationServices

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#41161]
## Issue description

After  https://gitlab.kitware.com/cmake/cmake/commit/5de37a4a6474fa569e2ac28d5e9c164b6e7d2f46, CMake needs to be built with ApplicationServices. At one time we did this but it was decided to avoid putting a proprietary dependency in such a core package. Should we file an issue with CMake?

https://hydra.nixos.org/build/74954644/nixlog/1

**Comment by LnL7** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/02dcc8d734302b22ba635844c1c2a57ddca83853.
