### ISSUE TITLE
Build of ghc-8.0.2 is broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#41166]
`ghc-8.0.2` does not compile in recent versions of `master`: https://hydra.nixos.org/build/75011641.

It looks to me like ad35019501e6b263e08ecb4c66f1ee6e3eee80f1 broke it (ping @oxij), but I haven't bisected things yet, so I might be wrong about this.

**Comment by oxij** [comment]
> It looks to me like ad35019501e6b263e08ecb4c66f1ee6e3eee80f1 broke it

That's a merge commit. What broke it is #28029, see discussion there.

**Comment by oxij** [comment]
See fix in #41192.

**Comment by peti** [comment]
Thank you for the quick fix!
