### ISSUE TITLE
python3Packages.tensorflow is broken.

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#41163]
## Issue description
` nix-shell -p python3Packages.tensorflow` failed with errors

example: 
~~~~
ERROR: /tmp/nix-build-tensorflow-build-1.5.0.drv-0/output/external/jpeg/BUILD:122:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:                                       
@jpeg//:k8                                                                                                                                                                                            
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
~~~~

### Steps to reproduce

~~~~
$ nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/master.tar.gz" -p python3Packages.tensorflow 2>&1 | tee log.txt
~~~~

[log.txt](https://github.com/NixOS/nixpkgs/files/2043658/log.txt)

## Technical details

 - system: `"x86_64-linux"`                                                                                                                                                                           
 - host os: `Linux 4.14.41, NixOS, 18.09pre-git (Jellyfish)`                                                                                                                                          
 - multi-user?: `yes`                                                                                                                                                                                 
 - sandbox: `no`                                                                                                                                                                                      
 - version: `nix-env (Nix) 2.0.2`                                                                                                                                                                     
 - channels(root): `"nixos-18.09pre139651.6db7f92cc2a"`                                                                                                                                               
 - channels(wizzup): `""`                                                                                                                                                                             
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by FRidh** [comment]
cc @abbradar @jyp

**Comment by jyp** [comment]
This seems related to #40211. Most certainly some sort of incompatibility between bazel and tensorflow versions.

Unfortunately, I understand nothing about bazel. A possible workaround would be to use the binary (wheel-based) build which was phased out some months ago.

**Comment by FRidh** [comment]
I like that we build tensorflow ourselves, but it also needs to be maintainable. @jyp , if you think the Bazel build is outside your scope but you are willing to add a complementing wheel based solution, then please re-add it. I think in this case it is more important we have a working solution than a preferred solution.

**Comment by wizzup** [comment]
@jyp #41259 build without any error.

~~~~
$ nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/0704c7e17b904aceefec80e26f58e0da10a951ae.tar.gz" -p python3Packages.tensorflow
~~~~
