### ISSUE TITLE
add Darwin as supported platform for ffmpeg  2.x.nix

### ISSUE THREAD

**Issue by ibeex** [NixOS/nixpkgs#4117]
I tred to add Darwin as suported platform, but then it breaks builidng wayland-1.5.0 since it is also not supported, it looks like libva is calling darwin. I seen that homebrew dot use libva.

**Comment by spwhitt** [comment]
This has been fixed by https://github.com/NixOS/nixpkgs/commit/a5f065d708af26be86e1f639cee1dd68303f5339
