### ISSUE TITLE
perlPackages.DBDPg and thus Hydra fails to build

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#41199]
## Issue description
https://hydra.nixos.org/build/75040700

### Steps to reproduce
```
nix-build '<nixpkgs>' -A perlPackages.DBDPg
```

## Technical details
nixpkgs rev ab6d08132daea7cfc8437027f156d6bf9f64941a

**Comment by srhb** [comment]
I wonder if this is another case of the socket path being too long...

**Comment by srhb** [comment]
Tests appear to work iff sandboxing is disabled.

**Comment by xeji** [comment]
Same issue reproduced locally on `master` 7a23f1accaccdbadfb28da89e00c2489aa96245c

**Comment by ledettwy** [comment]
If the hydra build failed, how did this get released to the 18.03 stable channel?

**Comment by srhb** [comment]
@ledettwy It is not a release blocking build. Here are the constituents: https://hydra.nixos.org/job/nixos/release-18.03/tested#tabs-constituents

I'm more curious how it ever worked. I can't really imagine that it hasn't changed since the sandbox was enabled on Hydra.

**Comment by xeji** [comment]
I tried some older revisions and it really looks like DBD-Pg tests _never_ worked in a sandbox. 
The package was last updated 2015. 

Bumping to current DBD-Pg 3.7.4 doesn't help either - it first results in an error about the socket path being too long, and after patching that the tests freeze at the same point as with 3.5.3.

So let's stick to 3.5.3 and just set `doCheck=false`.

**Comment by srhb** [comment]
Sounds good to me, will you or shall I?

**Comment by xeji** [comment]
I'm working on it.
