### ISSUE TITLE
Zoom black video on NixOS

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#41203]
## Issue description
Currently Zoom on master launches, but the camera video is black. This happens to be with one of updated SYSTEM packages.

So far, I've figured the following:

1. This is SYSTEM issue. I've found that with following Nixpkgs revisions it works:
```
  nixos-2018-04-04 = mkNixpkgs {
    rev = "ea145b68a01";
  };

  nixos-pre-libvnd-change = mkNixpkgs {
    rev = "01b254ec50299f1fe1d3e9a4eb9a002f6fe0c84d";
    patches = [
      { meta.description = "ostree-patch-new-version";
        url = "https://github.com/NixOS/nixpkgs/commit/546696e367fe94159aa7765313d93caffd11fb37.patch";
        sha256 = "01jmdfzzcsidmah269m51020g2waf7j4dbnwr7chif8cci8096qy";
        name = "ostree-patch.diff";
      }
      { meta.description = "fix-build-webkitgtk";
        url = "https://github.com/NixOS/nixpkgs/pull/38375/commits/50585295724de4d971dec1e4258daf047ce7da54.patch";
        sha256 = "1mjf0ydrfl6js1flv4hgg1i0gcamxwpd0yspgd9ai0aalnjqh6m4";
        name = "webkitgtk.diff";
      }
    ];
  };
```
2. Zoom from master also works on that revision (camera video works)
3. I haven't yet bisected this, but with following revision camera video doesn't work
```
  nixos-2018-05-21 = mkNixpkgs {
    rev = "5da85431fb1";
  };
```
4. It may be of interest - I'm using Gnome Shell as DM.
5. Running nix-diff on my system closures revealed the following changes:
```
    - dbus-1.10.24
    - e2fsprogs-1.44.0
    - fuse-3.2.1
    - linux-4.15.12
    - sudo-1.8.22
    + dbus-1.12.6
    + e2fsprogs-1.44.1
    + fuse-3.2.3
    + linux-4.16.10
    + perl-Net-DBus-1.1.0
    + perl-XML-Parser-2.44
    + perl-XML-Twig-3.52
    + sudo-1.8.23
```
I assume that this happens to be something with DBus or kernel then (Zoom has own DBus in Qt bundle)

### Steps to reproduce
Install Zoom and launch new video conference. Screen is black.

This probably isn't dupe of https://github.com/NixOS/nixpkgs/issues/40776, but perhpas related

**Comment by danbst** [comment]
copy @srhb @shlevy and whoever uses zoom on latest unstable

**Comment by coretemp** [comment]
@danbst Your experience suggests that nixpkgs could benefit from a feature where a package recommends a particular kernel version.

**Comment by danbst** [comment]
@coretemp in this case I'm working with their Support so they can fix incompatibility ASAP. But in general - interesting idea. How would it be implemented though? Nix has very limited installation checks.

**Comment by tadfisher** [comment]
Have you had any luck with support?

FWIW, my webcam works on other applications, including:

- chromium
- gnome3.cheese
- falkon (another QtWebEngine product)
- qv4l2 from v4l_utils

Also on `linuxPackages_latest`.

**Comment by tadfisher** [comment]
The Flatpak-packaged version of Zoom works correctly.

To test, add `services.flatpak.enable = true;` to your configuration and run:
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak update
flatpak install flathub us.zoom.Zoom
flatpak run us.zoom.Zoom
```

I'm attempting to determine what the difference is, but it appears this is not a system issue. So far, I've found that the Flatpak package is running the `ZoomLauncher` binary, which doesn't work on NixOS by default as it resets `LD_LIBRARY_PATH`. However, it appears this binary isn't doing much other than forking the `zoom` process.

**Comment by tadfisher** [comment]
Running the following:

```
strace -f -e trace=file ./result/bin/zoom-us 2>&1 >/dev/null | grep "\.so"
```

results in the output:

```
[pid 20261] openat(AT_FDCWD, "./libturbojpeg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 20261] openat(AT_FDCWD, "./libturbojpeg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 20261] openat(AT_FDCWD, "./libturbojpeg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 20261] openat(AT_FDCWD, "./libturbojpeg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 20261] openat(AT_FDCWD, "./libturbojpeg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 20261] openat(AT_FDCWD, "./libturbojpeg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

This happens many times a second, probably corresponding to the frame rate of my webcam. What's sort of terrible is that it is attempting to load from AT_FDCWD, and I don't know how to patch the binary to use `dlopen` in a more sane way.

**Comment by domenkozar** [comment]
I also get black screen on kernel 4.14 :)

**Comment by danbst** [comment]
I confirm that `libturbojpeg.so` was the issue

**Comment by coretemp** [comment]
I still have this issue when zoom starts. After I have been talking for 15 minutes or so and then try to start video again, it sometimes starts to work again. 

I am using the master version of zoom as posted  in the other zoom thread started by me.

It might be that one cause has been addressed, but not all of them have been addressed.

**Comment by danbst** [comment]
@coretemp Are you on kernel 4.14.x?

**Comment by coretemp** [comment]
@danbst  yes, 4.14.48. It only seems to happen when I join a meeting. When I just start a new meeting by myself, it does not happen.

**Comment by danbst** [comment]
@coretemp I think I have had similar issue - my video stream was frozen after a few minutes after meeting join.

**Comment by coretemp** [comment]
Do you also have this with the flatpak package? (I have never tried that package.)

**Comment by danbst** [comment]
I've just had meeting call and didn't experience this issue. I'm using `zoom-us` from nixpkgs-unstable now. You may try it like this:
```
$ nix-env -if channel:nixpkgs-unstable -A zoom-us -p ~/zoom-us-nix-profile
```
and then launch using `~/zoom-us-nix-profile/bin/zoom-us`. I hope @tadfisher fixed remaining bits of GLIBC incompatibility, so you may try that even if you are on 18.03

**Comment by mayhewluke** [comment]
I'm seeing this issue with `zoom-us` from `18.09` as well as from `unstable`, and with kernel `4.14.88` as well as `4.19.9`.

When using Zoom, the video is blank (black) in the settings pane as well as any call, started by myself or anyone else, and waiting does not appear to make any difference. Other applications have no problem accessing the webcam (eg. `cheese`, `chromium`, etc.)

**Comment by mayhewluke** [comment]
@danbst @coretemp @tadfisher @domenkozar Is this resolved for all of you? I can't imagine why it would be broken on my system only :confused: Use of Zoom is critical for my work so this is a major blocker for upgrading to `18.09` and resolving the security vulnerability in Zoom pre-`2.5.146186.1130`

**Comment by Creator54** [comment]
same issue on 
 - zoom: `5.10.6.3192`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.40-xanmod1, NixOS, 22.05 (Quokka), 22.05.915.9ff91ce2e4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05.915.9ff91ce2e4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

then installed via flatpak, and it works :)
