### ISSUE TITLE
avrgcc error

### ISSUE THREAD

**Issue by nickbeljaev** [NixOS/nixpkgs#41210]
## Issue description
avrgcc fatal error from cross link stdint.h
avr-gcc stdint.h have cross link to another stdint.h instead definitions, but this not work.

### Steps to reproduce
>$nix-env -iA nixos.avrbinutils
>$nix-env -iA nixos.avrgcc
>$nix-env -iA nixos.avrlibc
main.c
`#include <stdint.h>`
`int main() { }`
*$avr-gcc main.c 
In file included from main.c:2:0:
/nix/store/lsajpsiqc3hgyby3kjnbrfj6nckfxx96-avr-gcc-5.4.0/lib/gcc/avr/5.4.0/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory
compilation terminated.*

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.44, NixOS, 18.03.132531.ab6d08132da (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.132531.ab6d08132da"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

 find /nix/store/ -name stdint.h
/nix/store/pymp4cq49z4whxzjzys4by7dij0axdb0-gcc-6.4.0/lib/gcc/x86_64-unknown-linux-gnu/6.4.0/include/stdint.h
/nix/store/pymp4cq49z4whxzjzys4by7dij0axdb0-gcc-6.4.0/include/c++/6.4.0/tr1/stdint.h
/nix/store/kywwzykjq29b79vd1cwkfc2frgw780z9-glibc-2.26-131-dev/include/stdint.h
/nix/store/arziqfaahn2zczjm0pqr2fgp7fl4sarf-avr-libc-2.0.0/avr/include/stdint.h
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/stdint.h
/nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include/stdint.h
/nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/tr1/stdint.h
/nix/store/xday07ik9qpnsxqyb365d1ccrfs6q09a-gcc-6.4.0/lib/gcc/x86_64-unknown-linux-gnu/6.4.0/include/stdint.h
/nix/store/xday07ik9qpnsxqyb365d1ccrfs6q09a-gcc-6.4.0/include/c++/6.4.0/tr1/stdint.h
/nix/store/fhbmyy5b289rgj0w1qj7s3dzg239ar2w-glibc-multi-2.26-131-dev/include/stdint.h
/nix/store/8c3424kxz3kb8k1ldl0m8mga3cjp7zxf-isl-0.14.1/include/isl/stdint.h
/nix/store/sqd4p8illpkxb37xy5fw3bsfwzjclgf5-virtualbox-5.2.8/libexec/virtualbox/additions/src/vboxguest/include/iprt/stdint.h
/nix/store/sqd4p8illpkxb37xy5fw3bsfwzjclgf5-virtualbox-5.2.8/libexec/virtualbox/additions/src/vboxsf/include/iprt/stdint.h
/nix/store/3p1b66av1sflap15jr4b8z6hw28fmjam-gcc-6.4.0/lib/gcc/x86_64-unknown-linux-gnu/6.4.0/include/stdint.h
/nix/store/3p1b66av1sflap15jr4b8z6hw28fmjam-gcc-6.4.0/include/c++/6.4.0/tr1/stdint.h
/nix/store/lsajpsiqc3hgyby3kjnbrfj6nckfxx96-avr-gcc-5.4.0/lib/gcc/avr/5.4.0/include/stdint.h
/nix/store/a1kx18cc69m6ad8kpnniw1aawcr75pl8-gfortran-6.4.0/lib/gcc/x86_64-unknown-linux-gnu/6.4.0/include/stdint.h
/nix/store/a1kx18cc69m6ad8kpnniw1aawcr75pl8-gfortran-6.4.0/include/c++/6.4.0/tr1/stdint.h
/nix/store/8mvrk53wmqglcdk8h0bq6ny72i8q6shw-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include/stdint.h
/nix/store/8mvrk53wmqglcdk8h0bq6ny72i8q6shw-gcc-7.3.0/include/c++/7.3.0/tr1/stdint.h
/nix/store/j4q18y05wpnjin423wf69nfb7r7q0ml9-glibc-2.25-123-dev/include/stdint.h
/nix/store/iiv9p9d16rncvk85d6nm6zmjwk00xzpn-glibc-multi-2.25-123-dev/include/stdint.h
/nix/store/jxy9c9fbxqai3r66kx61jdwdpbzbhbl4-glibc-2.25-49-dev/include/stdint.h
/nix/store/g5kq4hzaca72qyh0g4xkgrb9wy5chx69-virtualbox-5.1.26/libexec/virtualbox/additions/src/vboxguest/include/iprt/stdint.h
/nix/store/g5kq4hzaca72qyh0g4xkgrb9wy5chx69-virtualbox-5.1.26/libexec/virtualbox/additions/src/vboxsf/include/iprt/stdint.h
/nix/store/g5kq4hzaca72qyh0g4xkgrb9wy5chx69-virtualbox-5.1.26/libexec/virtualbox/additions/src/vboxvideo/include/iprt/stdint.h
/nix/store/ay565i268nzl83j8jwzs1q9xwy8inbf9-glibc-2.25-123-dev/include/stdint.h

**Comment by nickbeljaev** [comment]
Hi, @mguentner 
Can You comment this issue? In 17.09..18.03 I'm lost avr-gcc functional :(, 17.03 with avrgcclibc live.

**Comment by mguentner** [comment]
Please read this commit message:

https://github.com/NixOS/nixpkgs/commit/6a458c169b86725b6d0b21918bee4526a9289c2f
