### ISSUE TITLE
IPAddressDeny=any present when firewall is disabled

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#41250]
## Issue description

I see the following warning when I have  `networking.firewall.enable = false;` on an AWS xen based system.

```
File /nix/store/cya0k4g78bd518wzgqghkk6srlvl2jgv-systemd-237/example/systemd/system/systemd-udevd.service:34 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
```

### Steps to reproduce
Unknown, probably easy.      

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 18.03.git.fdb5ba4 (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by peterhoeg** [comment]
This is unrelated to the normal firewall but a part of systemd's built-in access controls: http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html

You should have this error with ```networking.firewall.enable = true;``` as well.

My guess is that you are running kernel 4.9 which the relevant kernel support was only introduced in 4.11.
