### ISSUE TITLE
nix from nixpkgs 18.03 fails to build on Darwin

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#41277]
## Issue description
https://hydra.nixos.org/build/74965578

The culprit appears to be in doInstallCheck

### Steps to reproduce
nix build nixpkgs.nix

## Technical details
nixpkgs rev fdb5ba4cdf9f61e3cba204cbb5b1f81e49231958

**Comment by aanderse** [comment]
@srhb is this fixed on 18.09?
