### ISSUE TITLE
Idea Ultimate download fails with 403

### ISSUE THREAD

**Issue by pSub** [NixOS/nixpkgs#41282]
## Issue description

Idea Ultimate download fails with 403 error. It seems we need to update it, because they don't server old versions long enough.

### Steps to reproduce

```
% nix-env -iA nixpkgs.idea.idea-ultimate                                                                                                                                 
installing 'idea-ultimate-2018.1'
these derivations will be built:
  /nix/store/hn7lylbpq0bnbx8vi1627d9hmvskmyzf-ideaIU-2018.1-no-jdk.tar.gz.drv
  /nix/store/ass43bbsrzigcvg38009vczp017syg47-idea-ultimate-2018.1.drv
building '/nix/store/hn7lylbpq0bnbx8vi1627d9hmvskmyzf-ideaIU-2018.1-no-jdk.tar.gz.drv'...

trying https://download.jetbrains.com/idea/ideaIU-2018.1-no-jdk.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    911      0 --:--:-- --:--:-- --:--:--   911
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
error: cannot download ideaIU-2018.1-no-jdk.tar.gz from any mirror
builder for '/nix/store/hn7lylbpq0bnbx8vi1627d9hmvskmyzf-ideaIU-2018.1-no-jdk.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/ass43bbsrzigcvg38009vczp017syg47-idea-ultimate-2018.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ass43bbsrzigcvg38009vczp017syg47-idea-ultimate-2018.1.drv' failed
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.03.132405.ee80654b526 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(pascal): `"nixpkgs-18.03.132536.fdb5ba4cdf9"`
 - channels(root): `"nixos-18.03.132405.ee80654b526"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

cc @Mic92 @kirelagin

**Comment by kirelagin** [comment]
I am looking at the expression in `master` and it has version 2018.1.3 in it, so, I guess, you just need to upgrade your nixpkgs. Moreover, judging by the history, @jokogr is running an automatic script that bumps the version.

**Comment by pSub** [comment]
I'm using 18.03. Then maybe we should cherry-pick the update.

**Comment by jokogr** [comment]
I have made PR #41410 for master, I will make one for 18.03 once it gets accepted.

Unfortunately the update script we are using to update Jetbrains' products has been recently broken, I will try to fix it, too.

**Comment by Mic92** [comment]
I back ported all jetbrains update back to 18.03: https://github.com/NixOS/nixpkgs/compare/320e278ffb40...7295e175bf6c

**Comment by pSub** [comment]
Thank you very much!

**Comment by jokogr** [comment]
@Mic92 IDEA 2018.1.4 is not included in the commits you mentioned, please have a look at #41410, it is still open and not for 18.03.
