### ISSUE TITLE
Add derivation for pulseaudio-ctl

### ISSUE THREAD

**Issue by IvanMalison** [NixOS/nixpkgs#41329]
Here is the PKGBUILD for pulseaudio-ctl:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pulseaudio-ctl

I will probably contribute this myself soon, just wanted to file an issue so that it is searchable.

**Comment by peterhoeg** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/33ff34f3a21c7f8870159835be2152ddf3d148e2
