### ISSUE TITLE
packageOverrides not being called from nixos-rebuild

### ISSUE THREAD

**Issue by lostdj** [NixOS/nixpkgs#4132]
I'm nixnoob and am not sure this is a bug, but it sure looks like it to me.

I'm trying to reorganize my configuration.nix to group all options per-package: override, install, configure, instead of a one huge `packageOverrides` and `systemPackages` (or import files):

```
{ config, pkgs, ... }:
 
{
  config = pkgs.lib.mkMerge
  [
   
   
  {
    # ...
     
     
    my.pkgOverrides =
    [
      (pkgs: rec
      {
        jdk = pkgs.oraclejdk7;
      })
    ];
     
    environment.systemPackages = with pkgs;
    {
      jdk;
    };
  }
   
   
  {
    my.pkgOverrides =
    [
      # Other packages similarly...
    ];
  }
   
   
  ];
}
```

`my.pkgOverrides` definition: https://github.com/lostdj/nixpkgs/commit/26d91be9862fb1e4135fd3467c428de2ee147329

Testing:

```bash
# nixos-option my.pkgOverrides
[ <LAMBDA> ]
```

```bash
nix-repl> config.my.pkgOverrides 
[ «lambda» ]

nix-repl> config.nixpkgs.config.packageOverrides pkgs
{ jdk = «derivation /nix/store/pz7fl0ymx2h8c0hkm3xhc09gyl44nfgf-oraclejdk-7u65.drv»; }
```

But...

```bash
# nixos-rebuild build 
...
these paths will be fetched (27.24 MiB download, 55.55 MiB unpacked):
  /nix/store/3l9h8x85awyyx79pqm1y79xl53r6357l-openjdk-7u65b32
```

Put `abort` in `nixpkgs.config.packageOverrides`:
```bash
evaluation aborted with the following error message: `abortion!11'
```

`abort` in `my.pkgOverrides` and in `my.nix`: nothing. It's not being called.

**Comment by matthiasbeyer** [comment]
@lostdj So is this problem solved? Maybe this issue can be closed... don't know..

**Comment by lostdj** [comment]
Don't know, too.
I guess it can. :)
