### ISSUE TITLE
Problems building python36Packages.cython on aarch64 on latest nixos-unstable

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#41347]
## Issue description
I'm trying to install python36Packages.cython on my raspberry pi. It works if I go in to the cython's file `pkgs/development/python-modules/Cython/default.nix` and add `doCheck = false;` and build it. Then it's fine.

So I think it has something to do with `numpy`.

### Steps to reproduce

I have a complete build log from running: `nix-build -A python36Packages.cython 2> log` here: https://ptpb.pw/jkjC

It only took 15.49 hours or so to run on that hardware :smile:, I haven't enabled more than one build core.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"aarch64-linux"`
 - host os: `Linux 4.16.11, NixOS, 18.09.git.5b468ea6b1d (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre140920.5b468ea6b1d"`
 - nixpkgs: `/etc/nixos/nixpkgs`

cc @FRidh maybe?

**Comment by FRidh** [comment]
These issues are for upstream (Cython) to look at. Considering there are not many Cython on Arm users I am sure they would be interested in seeing this.

**Comment by etu** [comment]
Reported upstream :)

**Comment by etu** [comment]
I'm not sure if upstream want's to fix this and I believe that it's "always" been an issue. Thinking if we maybe could disable the tests depending on architecture just to have binary cached packages working...

**Comment by dezgeg** [comment]
Ah, but before that the tests were unconditionally disabled as well.

**Comment by tobihan** [comment]
We were all talking about a specific test failure in this issue. If you have other tests failing on other architectures, you should probably open a new issue for that.

For the record, this was about this failure:

    ======================================================================
    FAIL: test_coerce_to_numpy (numpy_memoryview.__test__)
    Doctest: numpy_memoryview.__test__.test_coerce_to_numpy
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/nix/store/qdcj04rnk8kb34zjrfzg8gfgl6svfcr8-python3-3.6.5/lib/python3.6/doctest.py", line 2199, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for numpy_memoryview.__test__.test_coerce_to_numpy
      File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/c/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line unknown line number, in test_coerce_to_numpy

    ----------------------------------------------------------------------
    File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/c/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line ?, in numpy_memoryview.__test__.test_coerce_to_numpy
    Failed example:
        test_coerce_to_numpy()
    Expected:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        13.25
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (18.8125+19.9375j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...
    Got:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        0.0
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (0+0j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...


    ======================================================================
    FAIL: test_coerce_to_numpy (numpy_memoryview)
    Doctest: numpy_memoryview.test_coerce_to_numpy
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/nix/store/qdcj04rnk8kb34zjrfzg8gfgl6svfcr8-python3-3.6.5/lib/python3.6/doctest.py", line 2199, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for numpy_memoryview.test_coerce_to_numpy
      File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/c/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line unknown line number, in test_coerce_to_numpy

    ----------------------------------------------------------------------
    File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/c/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line ?, in numpy_memoryview.test_coerce_to_numpy
    Failed example:
        test_coerce_to_numpy()
    Expected:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        13.25
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (18.8125+19.9375j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...
    Got:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        0.0
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (0+0j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...


    ======================================================================
    FAIL: test_coerce_to_numpy (numpy_memoryview.__test__)
    Doctest: numpy_memoryview.__test__.test_coerce_to_numpy
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/nix/store/qdcj04rnk8kb34zjrfzg8gfgl6svfcr8-python3-3.6.5/lib/python3.6/doctest.py", line 2199, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for numpy_memoryview.__test__.test_coerce_to_numpy
      File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/cpp/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line unknown line number, in test_coerce_to_numpy

    ----------------------------------------------------------------------
    File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/cpp/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line ?, in numpy_memoryview.__test__.test_coerce_to_numpy
    Failed example:
        test_coerce_to_numpy()
    Expected:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        13.25
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (18.8125+19.9375j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...
    Got:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        0.0
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (0+0j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...


    ======================================================================
    FAIL: test_coerce_to_numpy (numpy_memoryview)
    Doctest: numpy_memoryview.test_coerce_to_numpy
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/nix/store/qdcj04rnk8kb34zjrfzg8gfgl6svfcr8-python3-3.6.5/lib/python3.6/doctest.py", line 2199, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for numpy_memoryview.test_coerce_to_numpy
      File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/cpp/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line unknown line number, in test_coerce_to_numpy

    ----------------------------------------------------------------------
    File "/tmp/nix-build-python3.6-Cython-0.28.1.drv-0/Cython-0.28.1/TEST_TMP/memoryview/cpp/numpy_memoryview/numpy_memoryview.cpython-36m-aarch64-linux-gnu.so", line ?, in numpy_memoryview.test_coerce_to_numpy
    Failed example:
        test_coerce_to_numpy()
    Expected:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        13.25
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (18.8125+19.9375j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...
    Got:
        [97, 98, 600, 700, 800]
        deallocating...
        (600, 700)
        deallocating...
        ((100, 200), (300, 400), 500)
        deallocating...
        (97, 900)
        deallocating...
        99
        deallocating...
        111
        deallocating...
        222
        deallocating...
        333
        deallocating...
        11.1
        deallocating...
        12.2
        deallocating...
        0.0
        deallocating...
        (14.4+15.5j)
        deallocating...
        (16.5+17.7j)
        deallocating...
        (0+0j)
        deallocating...
        22
        deallocating...
        33.33
        deallocating...
        44
        deallocating...
