### ISSUE TITLE
Unable to install GOG games

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#41364]
## Issue description
It's impossible to install GOG games that are in a mojosetup shell file, due to NixOS's structure.
Is it possible to create an expression to allow this use case, or even better, the ability to emulate a "normal" Linux distribution on top of NixOS?

### Steps to reproduce
Try to install the .sh setup file from a game like Besiege that GOG provides.
```
./besiege_en_v0_6_17054.sh
Verifying archive integrity... All good.
Uncompressing Besiege (GOG.com)  100%  
Collecting info for this system...
Operating system: linux
CPU Arch: x86_64
trying mojosetup in bin/linux/x86_64
USING en_US
./startmojo.sh: line 55: /tmp/selfgz2109529507/bin/linux/x86_64/mojosetup: No such file or directory
Error: Couldn't run mojosetup
./besiege_en_v0_6_17054.sh: line 517: /bin/rm: No such file or directory
```
The reason the `mojosetup` binary fails is because it's dynamically linked to `/bin64/linux-whatever.so`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.46, NixOS, 18.03.132545.c40fdcd26c2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03, nixos-unstable, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Chiiruno** [comment]
Actually, would it be possible to do something crazy like put Arch Linux or some other distribution into a nix expression inside the nix store? Or would I end up having to use LXC or systemd-nspawn?

**Comment by coretemp** [comment]
@Chiiruno Can you link to their documentation for Linux where they specify what the system requirements are for a technical audience (I didn't find it immediately)?

If they do not offer that, you could ask them to provide this data on their website.

Failing all of the above, you want to do something like http://sandervanderburg.blogspot.com/2013/09/composing-fhs-compatible-chroot.html.

Generalizing all of that, I too would find it a nice feature if the following would be a shell session that actually worked out of the box on NixOS:

```
archlinux ls
nixos nixos --version
centos75 ls var
archlinux --shell
> Welcome to ArchLinux
$ ls 
```
With the right hardware it is even possible to make that work for Windows and Macs.

**Comment by orivej** [comment]
You can install `steam-run-native` or `steam-run` and run e.g. `steam-run ./besiege_en_v0_6_17054.sh`. You will probably have to use `steam-run` to launch the installed game anyway.

**Comment by tadfisher** [comment]
@coretemp This might interest you: https://github.com/systemd/mkosi

I attempted to package it but it needs quite a bit of patching to work on NixOS, and many of its dependencies (dnf, yum, arch-install-scripts) aren't packaged yet.

**Comment by Chiiruno** [comment]
I had no idea about `steam-run`, thank you!
As far as I can tell, the fact that this works means coretemp's question is answered.
It seems like making a `gog-run` might be a good idea, but may be redundant if `steam-run` works.
Closing since this is fixed, thanks!

**Comment by MohammadAlsayed49** [comment]
> You can install `steam-run-native` or `steam-run` and run e.g. `steam-run ./besiege_en_v0_6_17054.sh`. You will probably have to use `steam-run` to launch the installed game anyway.

steam-run command not found... How can I install it?
Thanks in advance

**Comment by mausch** [comment]
@MohammadAlsayed49 https://search.nixos.org/packages?channel=22.05&show=steam-run&from=0&size=50&sort=relevance&type=packages&query=steam-run
