### ISSUE TITLE
traefik: ship webui

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#41378]
## Issue description
Copied over from #41208:

> Since 1.6.0, Træfik normally ships a webui (containous/traefik#2226) at http://localhost:8080/dashboard/, displaying current configuration, status and latest errors (if enabled).
> 
> The upstream build process seems to include spinning up a docker container, basically compiling files in webui using ng build --prod --no-delete-output-path --output-path ../static/ (from inside webui folder), which is then baked into the binary using go-bindata.
> 
> Our build process leaves the static folder empty, so the dashboard would return a 404.
> We should at least document that, but it would be even better if we shipped the dashboard too, as it's really nice :-)
> 
> I tried packaging ng and the webui subproject using yarn2nix, while trying to bump this package at an earlier attempt, but wasn't that successful.
> I got all dependencies properly nixified, but had problems with building the ng binary itself.

/cc @vdemeester @ryantm @xeji

**Comment by ljani** [comment]
Here's a workaround inspired by https://github.com/NixOS/nixpkgs/issues/42614 for the time being:

```nix
{ stdenv, fetchurl }:

let
  version = "2.0.2";

  sources = let
    base = "https://github.com/containous/traefik/releases/download/v${version}";
  in {
    "x86_64-linux" = fetchurl {
      url = "${base}/traefik_v${version}_linux_amd64.tar.gz";
      sha256 = "f9adf514fc7ae0e90b88680213d44d59df429d8b68978b4a7ed4f9408fb0ad67";
    };
  };
in stdenv.mkDerivation rec {
  pname = "traefik-bin";
  inherit version;

  src = sources."${stdenv.hostPlatform.system}" or (throw "unsupported system: ${stdenv.hostPlatform.system}");

  sourceRoot = ".";

  installPhase = ''
    runHook preInstall

    mkdir -p $bin/bin $out/bin
    mv traefik $bin/bin

    runHook postInstall
  '';

  meta = with stdenv.lib; {
    homepage = https://traefik.io/;
    description = "A modern reverse proxy";
    platforms = [ "x86_64-linux" ];
    license = licenses.mit;
    maintainers = with maintainers; [ hamhut1066 vdemeester ];
  };

   outputs = [ "bin" "out" ];
}
```

I'm not too eager to send a PR since I have no idea what I'm doing, but it seems to work with `services.traefik.package = pkgs.callPackage ./traefik-bin.nix {};` I guess something similar would work for `nixpkgs` as well.

**Comment by flokli** [comment]
Building javascript frontends with Nix unfortunately isn't quite nice, and the tooling we have isn't too good either.  I doubt we'll be able to solve this any time soon.

@ljani, in the meantime traefik has been bumped to 2.x (in https://github.com/NixOS/nixpkgs/pull/76723) - would you be up to create a PR adding a `traefik-bin` derivation, that ships the webui?

Users that want it could then set `services.traefik.package = pkgs.traefik-bin;` to get the webui, which sounds like a good compromise.

**Comment by ljani** [comment]
@flokli: It seems I do not have enough time to play at this point, sorry. Also, I've moved to Debian on WSL2 for the time being. I should try that NixOS for WSL2 package first.

**Comment by jokogr** [comment]
Actually I have a working version of this, but it's not very maintainable: people would have to manually do the version bump for the frontend. Would anyone be interested to make a PR for that?

**Comment by flokli** [comment]
@jokogr I'm not sure if I quite follow - why would `traefik-bin` require a manual version bump for the frontend?

**Comment by jokogr** [comment]
@flokli I meant to say that I have already managed to package the frontend inside the `traefik` package, but I don't have a solid way to handle its update, one needs to do some manual steps.

Should I create a PR, so that you could have a look?

**Comment by flokli** [comment]
@jokogr it probably depends on how much code and how maintainable it is.

If we need to jump through a lot of hoops to update the package, maybe it's better to ship it without the webui, and provide the binary package for those who want the webui.

**Comment by eljojo** [comment]
Hi any updates on this? anyway to continue this work?

**Comment by flokli** [comment]
@eljojo I think getting https://github.com/NixOS/nixpkgs/issues/41378#issuecomment-637107226 would be a good start :-)
