### ISSUE TITLE
fixed-output derivation produced path XXX instead of the expected hash YYY for fetchFromGithub

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#41374]
I have this:

```
    src = fetchFromGitHub {
      repo = "bup";
      owner = "nh2";
      rev = "5170c3fde72d45ddcf4e1d657e2788f7b4560831";
      sha256 = "0401067152dx9z878d4l6dryy7f611g2bm8rq4dyn366w6c9yrcb";
    };
```

building it after an upgrade to `nixpkgs-18.03`, I get

```
fixed-output derivation produced path '/nix/store/cn22m5wz95whqi4wgzfw5cfz9knslak4-source' with sha256 hash '1c0sv4rqixvinrc7vmdmgm6gf7f9dc7blscp9372v1hcfzg15r0z' instead of the expected hash '0401067152dx9z878d4l6dryy7f611g2bm8rq4dyn366w6c9yrcb'
cannot build derivation '/nix/store/8savxwnx8yw7r1ccrc00l680lmq5c15f-bup-0.29.1-network-fs-improvements.drv': 1 dependencies couldn't be built
```

What's going on? How can the hash change given that my `rev` is fixed to a commit SHA?

I've #39308 but that's because of file upper/lower case normalisation on Darwin, and I'm on Linux.

Maybe `fetchFromGithub` changed?

## Technical details

* `nix` on Ubuntu 16.04
* `nix (Nix) 2.0.2`; the earlier fixed-output derivation was obtained with the last `1.11` point release

**Comment by orivej** [comment]
`nix-prefetch-url --unpack https://github.com/nh2/bup/archive/5170c3fde72d45ddcf4e1d657e2788f7b4560831.zip` prints `1c0sv4rqixvinrc7vmdmgm6gf7f9dc7blscp9372v1hcfzg15r0z`. You might have updated `rev` without updating `sha256`, and then either GCed Nix cache or update Nixpkgs to the version of `fetchFromGithub` that downloads into the `source` directory, which made Nix rebuild the source derivation and find the hash mismatch.

**Comment by nh2** [comment]
> You might have updated rev without updating `sha256`, and then either GCed Nix cache or update Nixpkgs to the version of `fetchFromGithub` that downloads into the source directory

@orivej I still don't understand 100% how either of these approaches can associate a wrong hash with what was downloaded before.

If the steps are as follows:

1. Originally write that `.nix` file; write correct `sha256 = 123` and `rev = a`
2. Update to `rev = b` but forget to update `sha256`

then I think what happens is that nix doesn't do anything and just reuses the sha you already have. Or is that not correct and it actually associates `rev=b` with the wrong hash `123`?

I'm not clear on how exactly that works.

**Comment by orivej** [comment]
When instantiating a fixed output derivation, Nix computes its store path (`/nix/store/{storehash}-{name}`), and if this path does not exist, it builds it and verifies that the actual sha256 of the contents matches the specified sha256. The `storehash` part of the store path depends on its `name` and `sha256`, but it does not depend on other arguments to `fetchFromGithub` (such as `repo` or `rev`). This is conceptually right since different repos and revs can have the same content, but this also lets you change `rev` and miss that you should change `sha256` too. If you really want to prevent this, you can include `rev` in `name` like this:
```
    src = fetchFromGitHub rec {
      name = "github-${owner}-${repo}-${rev}";
      owner = "nh2";
      repo = "bup";
      rev = "5170c3fde72d45ddcf4e1d657e2788f7b4560831";
      sha256 = "0401067152dx9z878d4l6dryy7f611g2bm8rq4dyn366w6c9yrcb";
    };
```

**Comment by nh2** [comment]
Thanks!
