### ISSUE TITLE
Awesome 3.5 doesn't understand `--search`

### ISSUE THREAD

**Issue by jpdoyle** [NixOS/nixpkgs#41385]
## Issue description

#33169 has broken Awesome 3.5, which does not understand the `--search` flag.

### Steps to reproduce

Build a configuration that includes

    services.xserver.windowManager.awesome = {
        enable = true;
        luaModules = [ pkgs.luaPackages.vicious ];
        package = pkgs.awesome-3-5;
    };

then run `echo "require('vicious')" | awesome-shell` (I think this is enough, I had to run from a custom `nixpkgs` or rollback to get my configuration to work, so I haven't tested this exact line of code). 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.47, NixOS, 18.03.git.a9fdfb6 (Impala)` (this is with a patch rolling back to the `LUA_PATH` method -- any current `18.03` version should have this bug)
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.132545.c40fdcd26c2"`

**Comment by teto** [comment]
awesome 3 isn't available anymore ? shall we close ?

**Comment by jpdoyle** [comment]
I suppose so
