### ISSUE TITLE
Use 0.7 version of stackage2nix

### ISSUE THREAD

**Issue by qrilka** [NixOS/nixpkgs#41391]
## Issue description

version 0.6.1 seems to be incompatible with Nixos-18.03, see https://github.com/typeable/stackage2nix/issues/59

### Steps to reproduce

Run `nix-env -f "<nixpkgs>" -i -A haskellPackages.stackage2nix`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
[kirill@qnixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.132545.c40fdcd26c2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(kirill): `""`
 - channels(root): `"nixos-18.03, nixpkgs-18.03pre123927.5be70c39f3e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

There is a fix https://github.com/typeable/stackage2nix/pull/57 which was included in `stackage2nix-0.7.0` but nixos uses only 0.6.1

**Comment by cdepillabout** [comment]
`stackage2nix` is no longer used, I'll go ahead and close.

**Comment by qrilka** [comment]
@cdepillabout could you tell what it was replaced with?

**Comment by cdepillabout** [comment]
@qrilka Now people are generally using [haskell.nix](https://github.com/input-output-hk/haskell.nix).

I'll also picth my own [`stacklock2nix`](https://functor.tokyo/blog/2022-12-15-stacklock2nix) :-)
