### ISSUE TITLE
plasma5: all menus gone after upgrade

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#41416]
## Issue description
After an upgrade I lost a working Plasma5. 

I did log out and log in again. 

There is no task bar,  panel, or K menu button.

I used to use the following if I did an upgrade in a running session, which stopped working.

```
#!/bin/sh
kquitapp5 plasmashell; plasmashell &
disown
```

```
timeout 15s plasmashell 
```
results in no output at all where previously it would output a lot of warnings indicating that at least something was happening.

`strace plasmashell` ends (before I kill it) with:

`futex(0x8f8b10, FUTEX_WAIT_PRIVATE, 0, NULL`. 

### Steps to reproduce

Unknown, other than using Plasma5. Others will likely also see this, because I don't do anything special with Plasma5.

### Nice to have

A test that would run a simulated desktop session would be nice to have. This would also allow me to make upgrades unattended.

Perhaps this is something the Plasma team should setup, but at such times I am considering to switch desktop environment to something less advanced for reliability reasons.

Plasma5 is the least reliable program I have on my system.

## Technical details

Please run - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.03.git.03ba84e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - nixpkgs: https://github.com/NixOS/nixpkgs/tree/03ba84eb56559d23031261a9fb744cbf9f7062c3

**Comment by Anton-Latukha** [comment]
Yes I have this too for a long time.
I saw a bugreport that KDE does not ran `kbuildsycoca5`.
There is number of bugreports around KDE can not find new path after update.
Probably it is a sign that we can talk to KDE team.

* KDE will not automatically update it's start menu #40915
* ksysguard desktop file does not have an Exec line #40916
* Application launcher menu is not updated #20776

**Comment by coretemp** [comment]
A reboot as opposed to just a `systemctl restart display-manager.service` was a workaround for me.

**Comment by aanderse** [comment]
@coretemp I believe this was fixed in 18.09. Can you please close ticket?

**Comment by pirboazo** [comment]
@aanderse , @coretemp It's not fixed in 18.09

**Comment by aanderse** [comment]
@peterhoeg Do I recall correctly that you put in the user activation scripts for 18.09 which was going to fix this? Do you have any insight?

**Comment by peterhoeg** [comment]
Actually it was @bkchr's PR mentioned above that should deal with this exact problem - my work was on the activation scripts in general. I might get some time on this weekend to have a look if nobody beats me to it.

**Comment by bkchr** [comment]
@pirboazo could you please execute `kbuildsycoca5` manually and post the output?

**Comment by peterhoeg** [comment]
No input from submitter - please reopen if the problem persists.
