### ISSUE TITLE
Gitea: Nix store paths are permanantly associated with repos + ssh keys

### ISSUE THREAD

**Issue by tkerber** [NixOS/nixpkgs#41436]
## Issue description

When repos are created on a gitea server running on nixos, various git hooks under the repository link directly to the nix path of the gitea binary. Likewise, adding ssh keys adds them specifically for the nix path of the currently running gitea binary.

When a new version of gitea is installed, and the old one garbage collected, this results in a) hooks producing errors, and b) ssh accesses failing.

Due to their common history, this likely affects gogs too.

### Steps to reproduce

* Enable gitea
* Create a repository
* Update gitea
* GC old gitea
* Try to pull/push/etc the old repository

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by tkerber** [comment]
Wait, it seems this was just fixed recently. Sorry.

**Comment by tkerber** [comment]
Yes, it seems that the fix I was talking about (#41218) is only in master.

**Comment by aanderse** [comment]
@tkerber as master from this time was released this ticket can now be closed please.
