### ISSUE TITLE
nixpkgs/nixos/modules/system/boot/stage-1-init.sh tries to find fsck when its a nilfs2 filesystem

### ISSUE THREAD

**Issue by vicgc** [NixOS/nixpkgs#41458]
## Issue description

when it loads tries to find a fsck that dont exist, nilfs2 dont need it by design

[    1.307537] stage-1-init: checking /dev/disk/by-uuid/76b2bf5a-3155-4e42-bd61-55dd825b5b1b...
[    1.307984] stage-1-init: fsck (busybox 1.28.1)
[    1.308162] stage-1-init: [fsck.nilfs2 (1) -- /mnt-root/] fsck.nilfs2 -a /dev/disk/by-uuid/76b2bf5a-3155-4e42-bd61-55dd825b5b1b
[    1.308223] stage-1-init: fsck: fsck.nilfs2: No such file or directory
[    1.308339] stage-1-init: mounting /dev/disk/by-uuid/76b2bf5a-3155-4e42-bd61-55dd825b5b1b on /...

### Steps to reproduce

make a root nilf2fs

The problem is resolved if you add at the checkFS() in the nixos/modules/system/boot/stage-1-init.sh

    # Skip fsck for nilfs - not implemented yet.
    if [ "$fsType" = nilfs2 ]; then return 0; fi

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.47, NixOS, 18.03.132561.03ba84eb565 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.132561.03ba84eb565"`
 - channels(me): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

PS thanks for this awesome distro ;)

**Comment by bkchr** [comment]
Would you mind to open a pull request with your provided fix?

**Comment by S-NA** [comment]
This should be closed due to the fix landing in ee4bb94.

**Comment by xaverdh** [comment]
I guess this can be closed now?

**Comment by vicgc** [comment]
For Sure, thanks for remind me 👍👍
