### ISSUE TITLE
Haskell Packages Versions Mismatches

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#41473]
## Issue description
I've noticed no numerous occasions now that various haskell packages fail to build because they depend on older versions of other packages, which are no longer in nixpkgs.

Sometimes the package has actually been updated to use the newer version, but nixpkgs has an older version of one package and a newer version of a different one, and the version mismatch causes problems.

For example, right now nixpkgs version of diagrams-builder requires `lens < 4.16`, but only has lens 4.16. The most recent version of diagrams-builder actually requires `lens < 4.17`, but nixpkgs isn't using that yet. I tried to make a patch for diagrams-builder to update the package requirements, but diagrams-postscript has the same problem, and it seems like I shouldn't have to go down this rabbit hole of patches every time there's an update.

Is there a way to fix this? It seems to me that nixpkgs should have access to older versions of haskell packages to use as dependencies. Isn't that part of the point of nix, to let you mix and match different versions of software?

### Steps to reproduce

This happens with a variety of packages, but for a specific example:
1. cd into nixpkgs repo
1. run `nix-build . -A diagrams-builder`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.42, NixOS, 18.09pre140682.5da85431fb1 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos"`
 - channels(qolen): `"nixos-18.09pre140682.5da85431fb1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by teto** [comment]
I had once a similar , in some cases, jailbreak can solve it, for instance in your overlay
```
   yst = super.haskellPackages.yst.overrideAttrs (oldAttrs: {
     jailbreak = true;
  });

```

**Comment by Radvendii** [comment]
Oh, that seems useful. Is there an easy way to propogate it to the build inputs? Because diagrams-builder relies on several other haskell libraries that suffer from the same problem.

**Comment by puffnfresh** [comment]
https://nixos.org/nixpkgs/manual/#how-to-build-with-profiling-enabled

You can do something like this, but with `jailbreak = true;` which will jailbreak all of your packages.
