### ISSUE TITLE
Tracking of projects that are migrating from GitHub (to GitLab, etc.)

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#41477]
## Issue description

![screenshot_20180606_194325](https://user-images.githubusercontent.com/20933385/41052698-2f04afc0-69c2-11e8-810d-65bfa3c30657.png)

[GitLab monitoring is here](https://monitor.gitlab.net/dashboard/db/github-importer?orgId=1)

This is a meta issue thread about projects migrating their upstream from GitHub to GitLab and other places.

How we can structure tracking of this changes?

It is better if someone with Maintainer authority can close this issue and reopen a thread like this, or maintainers form a unified strategy how we handle this and inform the community.

---

Folowing @volth in https://github.com/NixOS/nixpkgs/issues/41448#issuecomment-394522865:

volth:
```
16000 of fetchFromGitHub across nixpkgs

We will definitively get a lot of dead links, if not as the result of Microsoft activity then as the result of developers deleting their accounts

```

---

For example, if GitHub URL becomes unresponsive, something accordingly watch does the same project exists on GitLab. Maybe after call `fetchFromGitHub` fails - launch does it on according `fetchFromGitLab` (gitlab.com) URL, and output a message "Please look, maybe project migrated to GitLab <url>" that can cover huge part of cases of migration.

**Comment by ryantm** [comment]
I think crawling the web for information about packages is hard. It seems like every package does things slightly differently. 

nixpkgs-update uses Repology to get information about the URLs for sources and it can even change the URL for a `fetchurl` src derivation. It should be possible to detect the switch from GitHub to GitLab and change the fetcher. If someone knows an example of a project that has made the move, I'd like to hear about it so I can try testing switcher code on it.

**Comment by Anton-Latukha** [comment]
It does not mean bot would switch automatically.

I talked about informing with "a message".
---

So far as I look not so many big projects moving.
It is mostly personal accounts of developers. But them also have important projects.

So far I found that "Ring project" moved to seft-hosted GitLab ([link](https://twitter.com/JoinTheRing/status/1004362281017171970)). But it is so far not in NixPkgs. 

You can look Twitter for [#movingtogitlab](https://twitter.com/hashtag/movingtogitlab?src=hash) and they have tracking account at [@movingtogitlab](https://twitter.com/movingtogitlab).

**Comment by Anton-Latukha** [comment]
Well, for today this is not needed.
