### ISSUE TITLE
Connection editor does not open in Plasma

### ISSUE THREAD

**Issue by va1entin** [NixOS/nixpkgs#41494]
## Issue description
A click on "Configure network connections..." in the Plasma networking applet does not do anything.

I have installed `plasma-nm`, `networkmanagerapplet`, `networkmanager`, `networkmanager-openvpn`
set `hardware.networkmanager.enable = true`
and my user is in the extraGroup `networkmanager`

I also rebuilt, switched and rebooted multiple times. According to the NixOS manual it should pretty much just work without any additional packages on Plasma.

### Steps to reproduce
Install plasma, do the above and click on "Configure network connections..." in the Plasma networking applet

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.47, NixOS, 18.03.132597.9df3c53f38b (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03, nixos-unstable-18.09pre137305.d91caac6c3e, old-17.09"`
 - channels(val): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jafonsor** [comment]
Hi. I the same problem, after I added `networking.networkmanager.enable = true;` to the `configuration.nix`. It got solved when I installed `plasma-nm`.

**Comment by jafonsor** [comment]
Actually I think that the `plasma-nm` package should be automatically installed after enabling the network manager.

**Comment by va1entin** [comment]
@jafonsor Thanks for your feedback. I got it working too in the meantime. Unfortunately build-vm does not work for me currently. I'll try to document the solution when I got it working again.

**Comment by aanderse** [comment]
@va1entin did you get this working? Can this issue be closed now?

**Comment by va1entin** [comment]
@aanderse I guess it can be closed. It started working again for me at some point, but even with build-vm and a few of my old configs I couldn't find what the issue was.
