### ISSUE TITLE
Wrap some utilities in flent ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#41521]
## Issue description

I tried to run some tests with the newly packaged https://flent.org/ thanks to @mmlb.
The flent-gui works which was nice. So I tried to launch a few tests but I stumbled from error to error.
```
11:49:18 INFO: Starting http-1up test. Expected run time: 70 seconds.
11:49:18 ERROR: Runner HTTP latency failed check: No http-getter binary found in PATH.
11:51:58 INFO: Starting rrul_be_iperf test. Expected run time: 70 seconds.
11:51:58 WARNING: Found iperf binary (), but it does not have an --enhancedreports option. Not using.
11:51:58 ERROR: Runner TCP upload BE failed check: No suitable Iperf binary found.
12:35:29 INFO: Starting rrul_be_iperf test. Expected run time: 70 seconds.
12:35:29 ERROR: Runner Ping (ms) ICMP failed check: Cannot parse output of the system ping binary (/run/current-system/sw/bin/ping6). Please install fping v3.5+.
```
I had an iperf3 in PATH but it seems flent only supports iperf2. It could
I tried
`nix-shell -p iperf2 http-getter fping flent --command "flent-gui"`but it still doesn't pickup fping. Any idea  @mmlb ? I wonder if the package shouldn't wrap these utilities to make it easier to use ?

EDIT: I ran flent with -v and it didn't use fping because  `WARNING: Found fping, but it does not appear to support IPv6. Not using.`. It parses the output of fping -h which doesn't appear if not root hence the error. Running it as sudo, it picks up fping.

### Steps to reproduce
launch flent-gui with the previous command then try "File -> Run new tests"

## Technical details

Btw I packaged locally http-getter (necessary for some http requests tests)
```
{ stdenv, fetchFromGitHub, cmake
, curl, pkgconfig }:

stdenv.mkDerivation rec {
  name = "http-getter";
  version = "20180606";

  src = fetchFromGitHub {
    owner = "tohojo";
    repo = "http-getter";
    rev = "79bcccce721825a745f089d0c347bbaf2e6e12f4";
    sha256 = "1zxk52s1h5qx62idil237zdpj8agrry0w1xwkfx05wvv9sw4ld35";
  };

  buildInputs = [ cmake pkgconfig curl ];

  meta = with stdenv.lib; {
    homepage = https://github.com/tohojo/http-getter;
    description = "Simple getter for HTTP URLs using cURL";
    platforms = platforms.unix;
    license = licenses.gpl3;
  };
}
```

**Comment by teto** [comment]
I did some wrapping there https://github.com/NixOS/nixpkgs/pull/41614

**Comment by teto** [comment]
Wrapping was not such a good idea after all.

**Comment by mmlb** [comment]
@teto can we resurrect this issue? I think we should probably add the tools as dependencies so that they will be available for use. We can add a flent-gui if necessary to get a package that only had that if necessary. I'm not sure why we want to wrap flent? So that it will refer to the versions of the tools it depends on?
