### ISSUE TITLE
sonic-pi crashes at startup

### ISSUE THREAD

**Issue by rittelle** [NixOS/nixpkgs#41622]
## Issue description

Sonic Pi crashed at startup with the following message:
```
sonic-pi: include/boost/interprocess/segment_manager.hpp:861: void* boost::interprocess::segment_manager<CharType, MemoryAlgorithm, IndexType>::priv_generic_find(const CharT*, IndexType<boost::interprocess::ipcdetail::index_config<CharT, MemoryAlgorithm> >&, boost::interprocess::ipcdetail::in_place_interface&, boost::interprocess::segment_manager<CharType, MemoryAlgorithm, IndexType>::size_type&, boost::interprocess::ipcdetail::true_, bool) [with CharT = char; CharType = char; MemoryAlgorithm = boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family>; IndexType = boost::interprocess::iset_index; boost::interprocess::segment_manager<CharType, MemoryAlgorithm, IndexType>::size_type = long unsigned int; boost::interprocess::ipcdetail::true_ = boost::interprocess::ipcdetail::bool_<true>]: Assertion `(ctrl_data->m_value_bytes % table.size) == 0' failed.
```

### Steps to reproduce

`nix-shell -p qt5.full sonic-pi supercollider --run sonic-pi`

This is reproducible on master ( 4dc7cc8cc7eb6993c24ebdaeac074738c538cb2f ) and tho version below.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.46, NixOS, 18.03.132545.c40fdcd26c2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.132545.c40fdcd26c2"`
 - channels(lennart): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by JohnAZoidberg** [comment]
@Phlogistique @kamilchm sonic-py is broken now because we don't have ruby 2.4 anymore but sonic-py doesn't support 2.7 yet: https://github.com/samaaron/sonic-pi/issues/2179

Should we keep it and can we fix it or should we remove it?

**Comment by Phlogistique** [comment]
As far as I can see it is not fixed upstream. I have no plan to work on getting it fixed so I suggest removing it unless someone else comes up.

**Comment by Phlogistique** [comment]
Should I create the PR for the removal?

**Comment by kamilchm** [comment]
I don't have time to fix it either. :+1: for removal.

**Comment by JohnAZoidberg** [comment]
Actually, wait: https://github.com/samaaron/sonic-pi/issues/2179#issuecomment-587404416

> Yes, we have supported 2.7 for a while now :-)

Maybe isn't too hard then, to upgrade and fix remaining issues.

**Comment by JohnAZoidberg** [comment]
Seems like they have moved some files around and changed their build process.
I tried to figure out, but I haven't been successful.

If you don't want to put in the effort either, yes please create a PR for removal. :/

**Comment by c0deaddict** [comment]
This issue can be closed now that https://github.com/NixOS/nixpkgs/pull/82043 is merged.
