### ISSUE TITLE
How to depend on SDL2 (libGL error)

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#41620]
## Issue description

I hope opening an issue for this is appropriate. I'm using pysdl2 (meaning I have `pysdl2` in my `propagatedBuildInputs`), which depends on SDL2, of course. Initialization of SDL2 fails because it cannot find `libGL.so.1`. 
Looking at SDL2's source code, I see that it tries to `dlopen` either "libGL.so.1" (hard-coded) or whatever is inside `SDL_OPENGL_LIBRARY`. To properly package my application, am I to create a wrapper script for my application that sets this environment variable? Or what's the recommended approach when depending on libGL? I'm aware of PR 37369 (glvnd), but I'm not sure how to react to it.

**Comment by orivej** [comment]
Are you on non-NixOS Linux?

**Comment by pmiddend** [comment]
Nope, I'm on NixOS.

**Comment by orivej** [comment]
Then your `LD_LIBRARY_PATH` environment variable should contain `/run/opengl-driver/lib:/run/opengl-driver-32/lib` with `libGL.so.1` in both of them. Is that so?

**Comment by pmiddend** [comment]
No, and it shouldn't contain that, see [here](https://github.com/NixOS/nixpkgs/pull/37369).

**Comment by orivej** [comment]
Oops, I was not up to date on #37369. @abbradar, could you help?

**Comment by volth** [comment]
maybe related https://github.com/NixOS/nixpkgs/issues/41730

**Comment by orivej** [comment]
`SDL2` was not properly adapted for #37369, I'll fix it.

**Comment by andrewrk** [comment]
This broke glfw and/or libepoxy, whichever one tries to find libGL.so.1. It also broke zsnes.
