### ISSUE TITLE
Unable to change transmission service default download directory

### ISSUE THREAD

**Issue by savorocks** [NixOS/nixpkgs#41643]
## Issue description
I tried to change the default download directory, since it shouldn't be done in settings.json, but in the configuration.nix. Here's the relevant part of the configuration:
```
services.transmission = {
    enable = true;
    settings = {
      download-dir = "/mnt/disk1/Torrents/";
      rpc-whitelist = "127.0.0.1,192.168.*.*";
     };
  };
```

but when I do `sudo nixos-rebuild switch` I get the following:

warning: the following units failed: transmission.service

● transmission.service - Transmission BitTorrent Service
   Loaded: loaded (/nix/store/hg7d316iy1pn1n3nnk6084phl8ljc939-unit-transmission.service/transmission.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-06-07 20:31:33 CEST; 21ms ago
  Process: 26534 ExecStartPre=/nix/store/qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start (code=exited, status=1/FAILURE)
 Main PID: 765 (code=exited, status=0/SUCCESS)

Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + chmod 770 /var/lib/transmission
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + for DIR in '/var/lib/transmission' '/var/lib/transmission/.config/transmission-daemon' '/mnt/disk1/Torrents/' '/var/lib/transmission/.incomplete'
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + mkdir -p /var/lib/transmission/.config/transmission-daemon
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + chmod 770 /var/lib/transmission/.config/transmission-daemon
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + for DIR in '/var/lib/transmission' '/var/lib/transmission/.config/transmission-daemon' '/mnt/disk1/Torrents/' '/var/lib/transmission/.incomplete'
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + mkdir -p /mnt/disk1/Torrents/
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: mkdir: cannot create directory ‘/mnt/disk1/Torrents/’: Permission denied
Jun 07 20:31:33 hp-desktop systemd[1]: transmission.service: Control process exited, code=exited status=1
Jun 07 20:31:33 hp-desktop systemd[1]: transmission.service: Failed with result 'exit-code'.
Jun 07 20:31:33 hp-desktop systemd[1]: Failed to start Transmission BitTorrent Service.
warning: error(s) occurred while switching to the new configuration

### Steps to reproduce
Mentioned above. 
Change transmission service's default directory in configuration.nix and try to rebuild.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.09pre139319.1d9330d63a5 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre139319.1d9330d63a5"`
 - channels(savo): `"nixos-17.09pre106916.c5badb123a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by aanderse** [comment]
@savorocks this has been fixed so please close ticket.
