### ISSUE TITLE
error: while setting up the build environment: getting attributes of path '/etc/hosts': Permission denied

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#41651]
I get the above error when I ``nixos-rebuild``.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.11, NixOS, 18.09pre140958.696c6bed4e8 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(bart): `""`
 - channels(root): `"nixos"`
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ryantm** [comment]
@magnetophon Can you provide a log of the `nixos-rebuild` and a copy of your `configuration.nix` file?

**Comment by magnetophon** [comment]
Does anyone have an idea what's going on here?
I just tried to upgrade to the latest nixos-unstable, but am still getting this error.

**Comment by ryantm** [comment]
@magnetophon Thank you for trying the latest nixos-unstable. A suggestion I have for you is to try simplifying your configuration until you figure out which part of it is causing the error. You could start by combining all your configuration into one file and then remove half of it and binary search your way to what line is causing the problem.

**Comment by magnetophon** [comment]
Status update: I've been able to update my system by commenting out certain pkgs:
- m32edit
- musnix kernel (which earlier I have been able to build on this system in the period where I was having this problem) 

I havent found a link between these pkgs yet.

**Comment by magnetophon** [comment]
@ryantm Yes I am.
I just tried updating a pkg in nixpkgs, and got it again.

**Comment by ryantm** [comment]
What is the output of `ls -la /etc/hosts` for your system?

**Comment by magnetophon** [comment]
Another odd thing about this:
NixOS will rebuild a rt kernel just fine, but when I put a new version number of it in nixpkgs, I get the above error.

**Comment by magnetophon** [comment]
@ryantm I've simplified my configuration to the maximum, and stil get the same error, as long as I include one of the affected packages.
I'm building with ``nixos-rebuild test -I nixos-config=/home/me/test.nix -I nixpkgs=$NIXPKGS``
The content of ``test.nix`` is:
```
{pkgs, config, ...}: with pkgs;
{
  fileSystems =
  {
    "/" =
    {
      device = "/dev/mapper/VolGroup-nixos";
      fsType = "ext4";
      options = [ "relatime" "errors=remount-ro" "discard" ];
    };
    "/home" =
    { device = "/dev/mapper/VolGroup-home";
      fsType = "ext4";
      options = [ "relatime" "errors=remount-ro" "discard" ];
    };
  };

  swapDevices = [{
    device = "/dev/mapper/VolGroup-swap";
  }];

  boot.loader.systemd-boot.enable = true;

  environment.systemPackages = [    ir.lv2 ];
}
```
The output is:
```
nixos-rebuild test -I nixos-config=/home/bart/test.nix -I nixpkgs=$NIXPKGS                                                                                                               [21:25:54]
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
building Nix...
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
building the system configuration...
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
trace: warning: You don't have `system.nixos.stateVersion` explicitly set. Expect things to break.
these derivations will be built:
  /nix/store/nsalgsff163hzh63nqd6h9q916w06x0g-source.drv
  /nix/store/3n7hzab254q4mq65ly9593mj68v4aqj8-ir.lv2-1.2.4.drv
  /nix/store/ahhcn3scpzwwvs6ddfd64hwxir4ibfa3-system-path.drv
  /nix/store/2pidp87ir57gvhq3hl7qgrswwpa1c6nl-dbus-1.drv
  /nix/store/9fjg194j29lkfnxdwispy3c30ii3jsl3-hwdb.bin.drv
  /nix/store/1klbk9dj3i9s97by9alfxhyg3kf2r950-unit-script.drv
  /nix/store/1r4xjanizabchqzkb8dnb2p9mfj2bdkw-unit-post-resume.service.drv
  /nix/store/5hdw4znjv9nh7pppsrzndl4y04rhk564-unit-polkit.service.drv
  /nix/store/6i1bhbv7n8xy1mb9z5n58ij1868ny37r-unit-systemd-fsck-.service.drv
  /nix/store/lzviz5pkyfb3msnk5f2lncd17c5b3s88-unit-dbus.service.drv
  /nix/store/kfplkadmas91fvdwwiywya786bv3fvmm-unit-script.drv
  /nix/store/qhdghd2689r31jw0zfyss5ylj2vwr4n6-unit-pre-sleep.service.drv
  /nix/store/zdh0cc75n3xrapjjq0iqnqjmhkgajka2-firewall-stop.drv
  /nix/store/1w7j7gh0n9gz68plskjq9sdhml1pj2lq-firewall-reload.drv
  /nix/store/zsy80j1zsf77fz9fmldai4dn00hywida-unit-firewall.service.drv
  /nix/store/lpskpfrrsw2dmjfvzibxh9ilrff00mv0-system-units.drv
  /nix/store/46f6sgdck8j0498qnblyg2h4iiq6pig8-unit-dbus.service.drv
  /nix/store/wmqmzspnp4lhx1b8cmfp5khim56h4dqd-user-units.drv
  /nix/store/3jp4w9dnnir6fpyxl4d2fcay80gd7gsj-etc.drv
  /nix/store/623aa959y1kvnfhbsz69byhps8v8h221-stage-1-init.sh.drv
  /nix/store/530yqs4gmxcmigm2gbby6rsgpzam2bym-initrd.drv
  /nix/store/0byxkzclx6a6h44a9vkwkv4jkc68c1dh-nixos-system-nixos-18.09.git.dae9cf6.drv
building '/nix/store/9fjg194j29lkfnxdwispy3c30ii3jsl3-hwdb.bin.drv'...
building '/nix/store/zdh0cc75n3xrapjjq0iqnqjmhkgajka2-firewall-stop.drv'...
building '/nix/store/1klbk9dj3i9s97by9alfxhyg3kf2r950-unit-script.drv'...
building '/nix/store/kfplkadmas91fvdwwiywya786bv3fvmm-unit-script.drv'...
Adding hwdb files for package /nix/store/mhjpsx24jwm660rkcf43yrm2kww8q8y9-systemd-238
error: while setting up the build environment: getting attributes of path '/etc/hosts': Permission denied
```
I also get the error if I change
```
environment.systemPackages = [    ir.lv2 ];
``` 
into:

```
  environment.systemPackages = [    m32edit ];
  nixpkgs.config.allowUnfree = true;
```
and build without ``-I nixpkgs=$NIXPKGS``.

How can I continue troubleshooting?

**Comment by ryantm** [comment]
@magnetophon How about we try using the `--show-trace` option with `nixos-rebuild`?

**Comment by magnetophon** [comment]
@ryantm Thanks, but unfortunately that doesn't tell us much:
```
nixos-rebuild test --show-trace -I nixos-config=/home/bart/test.nix -I nixpkgs=$NIXPKGS                                                                                                  
```
```
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
building Nix...
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
building the system configuration...
warning: Nix search path entry '$HOME/.nix-defexpr/channels' does not exist, ignoring
trace: warning: You don't have `system.nixos.stateVersion` explicitly set. Expect things to break.
these derivations will be built:
  /nix/store/nsalgsff163hzh63nqd6h9q916w06x0g-source.drv
  /nix/store/3n7hzab254q4mq65ly9593mj68v4aqj8-ir.lv2-1.2.4.drv
  /nix/store/ahhcn3scpzwwvs6ddfd64hwxir4ibfa3-system-path.drv
  /nix/store/2pidp87ir57gvhq3hl7qgrswwpa1c6nl-dbus-1.drv
  /nix/store/5hdw4znjv9nh7pppsrzndl4y04rhk564-unit-polkit.service.drv
  /nix/store/6i1bhbv7n8xy1mb9z5n58ij1868ny37r-unit-systemd-fsck-.service.drv
  /nix/store/lzviz5pkyfb3msnk5f2lncd17c5b3s88-unit-dbus.service.drv
  /nix/store/lpskpfrrsw2dmjfvzibxh9ilrff00mv0-system-units.drv
  /nix/store/46f6sgdck8j0498qnblyg2h4iiq6pig8-unit-dbus.service.drv
  /nix/store/wmqmzspnp4lhx1b8cmfp5khim56h4dqd-user-units.drv
  /nix/store/3jp4w9dnnir6fpyxl4d2fcay80gd7gsj-etc.drv
  /nix/store/0byxkzclx6a6h44a9vkwkv4jkc68c1dh-nixos-system-nixos-18.09.git.dae9cf6.drv
error: while setting up the build environment: getting attributes of path '/etc/hosts': Permission denied
```

**Comment by ryantm** [comment]
Sorry, I don't have any other ideas. I see you don't have the stateVersion set, but I'm not sure how that would be relevant. Maybe try posting on the [forum](http://discourse.nixos.org/). Or asking on IRC.

**Comment by ryantm** [comment]
You could try installing your configuration on another machine or virtual machine and see if there is some state-based issue.

**Comment by magnetophon** [comment]
@ryantm Thanks. 

Now we know it isn't config-related, It would have to be a state-based issue, wouldn't it?
I don't have a VM set up right now, and I'm online via sketchy mobile data, so no easy way to test.

If it *is* a state-based issue, would I have to reinstall my machine, or is there another way?

**Comment by magnetophon** [comment]
@ryantm I had some HW issues in the meantime, but now I'm back in buisiness, and on a decent net pipe.

The debugging continues.

**Comment by magnetophon** [comment]
Currently I'm running ``nix-store --verify --check-contents --repair``, and it's finding and repairing lots of modified paths.
I think my old ssd was broken, and hope that after this repair, my NixOS will be healthy again...

**Comment by magnetophon** [comment]
That didn't fix it, unfortunately.

**Comment by magnetophon** [comment]
Turns out that my issue was [this line](https://github.com/magnetophon/nixosConfig/blob/master/common.nix#L439), which links /etc/hosts to a file in my user home dir.
Thanks to @LnL7 for providing the fix on IRC!

**Comment by chrissound** [comment]
I got this same error when I by accident added my ssh private key to the sandbox (file permission 600)...

I'd assume this should be a bug then? As the only way to recover that I know of is, booting into a previous generation.

**Comment by jonringer** [comment]
Ran into this error when running `nixos-install` on a new SSD from an already established nixos install. The issue was that I was using `su` , using `sudo -i` seems to not cause issues.

More context: nix daemon was refrencing paths from `/run/user/$UID` which was the cause of the issue.
