### ISSUE TITLE
Issues building python36Packages.cython on hydra on aarch64

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#41673]
## Issue description
This is a follow-up issue on #41347 and #41453.

Since the tests was enabled for Cython the build has failed on aarch64. One of the first issues was that one test didn't work on that architecture. That test has now been excluded from the build while on that architecture.

The second issue is that it takes more than ten hours to run this build, even on Hydra: https://hydra.nixos.org/build/75636013

You can see my build logs from my RaspberryPi that took about 15.5 hours to run. But we hoped that Hydra would be quicker. But it appears that Hydra wasn't quick enough to crunch through this within ten hours.

### Steps to reproduce
Available on Hydra.

### How do we take this forward?
The situation is improved with #41453 since one can go and build Cython and get a working package. But it's still quite bad since it takes 15.5 hours to do so (in my case). And on top of that time one has to compile all the things that depends on Cython as well.

One solution would be to increase the timeout but I'm not sure if that's the right move. Like it was done in 537d14f4e2c8ef908641223bc80fe8e2bca74e90 or something.

Any opinions? @grahamc @FRidh @dotlambda mabye?

**Comment by etu** [comment]
Since last update of cython, it seems to build fine on hydra:
https://hydra.nixos.org/job/nixpkgs/trunk/python27Packages.cython.aarch64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/python27Packages.cython.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/python36Packages.cython.aarch64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/python36Packages.cython.x86_64-linux

And no longer hit the timeout.

**Comment by dotlambda** [comment]
https://hydra.nixos.org/build/76387733

**Comment by dotlambda** [comment]
All 4 build succeed now, let's hope it stays that way. :crossed_fingers:
