### ISSUE TITLE
android-ndk: Output Limit Exceeded on Hydra

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#41704]
## Issue description
Currently android-ndk is failing on Hydra:

https://hydra.nixos.org/build/75668895

Looks like something that could be trivially fixed. Any ideas?

/cc @bkchr

**Comment by bkchr** [comment]
We probably should disable building the ndk on Hydra? Is it just copying and fixing stuff, that can be done easily locally.

**Comment by matthewbauer** [comment]
But we have cross jobs that it would be really nice to get working:

https://hydra.nixos.org/jobset/nixpkgs/cross-trunk#tabs-jobs

Cross frequently breaks on master & it would be nice to have some stable enough tests that we can make them block channel updates.

**Comment by bkchr** [comment]
What does this Hydra error mean? Is the builded derivation to big?

**Comment by Mic92** [comment]
It exceeds size per package.

**Comment by matthewbauer** [comment]
Okay I assumed it was output logs but that makes more sense

**Comment by bkchr** [comment]
Hmm, we could try to make some architectures configurable, aka remove not wanted architectures.

**Comment by matthewbauer** [comment]
I wonder if multiple outputs could fix this problem?

**Comment by edolstra** [comment]
No, because it checks the total size of all outputs.
