### ISSUE TITLE
Chromium hiDPISupport ineffectual

### ISSUE THREAD

**Issue by eborden** [NixOS/nixpkgs#4174]
The hiDPISupport setting for Chromium does not seem to change any rendering options after a rebuild/switch.

**Comment by aszlig** [comment]
@eborden: Does this help and/or is that issue solved by now?

**Comment by dfoxfranke** [comment]
I just tried this on a 27" 3840x2160 monitor (163dpi). Enabling hiDPI still has no effect with the default build options, but `--force-device-scale-factor` works. On this same monitor and video card under Debian jessie with the official Chrome build, I got appropriate scaling automatically.

Current hypothesis: X is misreporting my screen dimensions and this isn't a Chromium bug at all. I'll investigate more this evening.

**Comment by puffnfresh** [comment]
I compiled Chromium 45 beta with `enable_hidpi=1` and hidpi is working perfectly. I'm not sure if the switch actually changed anything, I haven't tried without it.

**Comment by dfoxfranke** [comment]
Well, I was at least partly right. `xdpyinfo` was incorrectly reporting 96dpi. After manually overriding that with `xrandr --dpi 163` I get properly scaled fonts in Chrome UI controls (tabs, etc), but I still need to use `--force-device-scale-factor` to get properly-scaled page content.

**Comment by dfoxfranke** [comment]
Turns out it was reporting 96dpi because Xfce's default is to force that. I've unchecked that setting but still need to use `--force-device-scale-factor`.

**Comment by benley** [comment]
I just installed a new hidpi laptop on the unstable channel, and chromiumBeta seems to work almost perfectly with the screen resolution.  The only remaining quirk that I can see now is the mouse cursors are tiny.

Are others still having problems?

**Comment by puffnfresh** [comment]
I don't think any patches are necessary any more.

**Comment by grahamc** [comment]
chromium has been working on hidpi for some time now, and I believe this issue should be closed.
