### ISSUE TITLE
haskellPackages.importify broken

### ISSUE THREAD

**Issue by mgttlinger** [NixOS/nixpkgs#41751]
## Issue description
The `haskellPackages.importify` package does not compile.

The executable itself compiles fine, but it seems like the derivation tries to run the tests, which in turn try to spawn a process executing `stack` which is not present in the specified build environment, causing the build to fail with

    importify-test: stack: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

### Steps to reproduce
`nix-shell -p haskellPackages.importify`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.38, NixOS, 18.03.132597.9df3c53f38b (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(merlin): `""`
 - channels(root): `"nixos-18.03.132597.9df3c53f38b, nixos-unstable-18.03pre123130.1bc288591ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mgttlinger** [comment]
Given that the [`haskellPackages` list](https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix) is auto generated, what are the ways to influence this?

**Comment by pmiddend** [comment]
Note that currently, this is broken (at least for me) in a dependency: `log-warper`:

```
Setup: Encountered missing dependencies:
aeson ==1.2.*,
fmt >=0.5.0.0 && <0.6,
lifted-async ==0.9.*,
o-clock >=0.1.1 && <0.2,
universum >=1.1.0 && <1.2

builder for '/nix/store/ljk9dmvh337dgkxkx3rp0nfwqd98cxm1-log-warper-1.8.11.drv' failed with exit code 1
```

**Comment by mgttlinger** [comment]
I would still care for an explanation on how to deal with such situations

**Comment by mgttlinger** [comment]
I believe the way to fix these things is to create a manually written package overriding the auto-generated one to disable tests.
