### ISSUE TITLE
abcde missing Perl dependencies

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#41789]
## Issue description

MusicBrainz-based metadata collection does not work in abcde. The problem is that the Perl modules cannot be found. Full error message:

```
Can't locate WebService/MusicBrainz/Release.pm in @INC (you may need to install the WebService::MusicBrainz::Release module) (@INC contains: /home/james/.opam/system/lib/perl5 /home/james/.opam/system/lib/perl5 /home/james/.nix-profile/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /home/james/.nix-profile/lib/perl5/site_perl/5.24.3 /home/james/.nix-profile/lib/perl5/site_perl /nix/var/nix/profiles/default/lib/perl5/site_perl /run/current-system/sw/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /run/current-system/sw/lib/perl5/site_perl/5.24.3 /run/current-system/sw/lib/perl5/site_perl /etc/profiles/per-user/james/lib/perl5/site_perl /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl/5.24.3 /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl /nix/store/414c03w4wd2d8d1l7yjilyfsw7qdih0p-perl-WebService-MusicBrainz-1.0.4/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/414c03w4wd2d8d1l7yjilyfsw7qdih0p-perl-WebService-MusicBrainz-1.0.4/lib/perl5/site_perl/5.24.3 /nix/store/414c03w4wd2d8d1l7yjilyfsw7qdih0p-perl-WebService-MusicBrainz-1.0.4/lib/perl5/site_perl /nix/store/3xdsflxwx6nh2fwfx5i6lc3lk9j2764i-perl-Mojolicious-7.71/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/3xdsflxwx6nh2fwfx5i6lc3lk9j2764i-perl-Mojolicious-7.71/lib/perl5/site_perl/5.24.3 /nix/store/3xdsflxwx6nh2fwfx5i6lc3lk9j2764i-perl-Mojolicious-7.71/lib/perl5/site_perl /nix/store/yy0flplqglhqyds717wa3vsfm0azp1sq-perl-MusicBrainz-DiscID-0.03/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/yy0flplqglhqyds717wa3vsfm0azp1sq-perl-MusicBrainz-DiscID-0.03/lib/perl5/site_perl/5.24.3 /nix/store/yy0flplqglhqyds717wa3vsfm0azp1sq-perl-MusicBrainz-DiscID-0.03/lib/perl5/site_perl /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl/5.24.3 /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl /nix/store/414c03w4wd2d8d1l7yjilyfsw7qdih0p-perl-WebService-MusicBrainz-1.0.4/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/414c03w4wd2d8d1l7yjilyfsw7qdih0p-perl-WebService-MusicBrainz-1.0.4/lib/perl5/site_perl/5.24.3 /nix/store/414c03w4wd2d8d1l7yjilyfsw7qdih0p-perl-WebService-MusicBrainz-1.0.4/lib/perl5/site_perl /nix/store/3xdsflxwx6nh2fwfx5i6lc3lk9j2764i-perl-Mojolicious-7.71/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/3xdsflxwx6nh2fwfx5i6lc3lk9j2764i-perl-Mojolicious-7.71/lib/perl5/site_perl/5.24.3 /nix/store/3xdsflxwx6nh2fwfx5i6lc3lk9j2764i-perl-Mojolicious-7.71/lib/perl5/site_perl /nix/store/yy0flplqglhqyds717wa3vsfm0azp1sq-perl-MusicBrainz-DiscID-0.03/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/yy0flplqglhqyds717wa3vsfm0azp1sq-perl-MusicBrainz-DiscID-0.03/lib/perl5/site_perl/5.24.3 /nix/store/yy0flplqglhqyds717wa3vsfm0azp1sq-perl-MusicBrainz-DiscID-0.03/lib/perl5/site_perl /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/site_perl/5.24.3 /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/5.24.3/x86_64-linux-thread-multi /nix/store/cxdmh98g0lvl1dyq304c1lq7f90dh01f-perl-5.24.3/lib/perl5/5.24.3 .) at /nix/store/d2jcrcafkihml67rx5s0rr1lm7r4523g-abcde-2.8.1/bin/.abcde-musicbrainz-tool-wrapped line 19.
BEGIN failed--compilation aborted at /nix/store/d2jcrcafkihml67rx5s0rr1lm7r4523g-abcde-2.8.1/bin/.abcde-musicbrainz-tool-wrapped line 19.
```

This should be an easy fix for anyone who knows about Perl in nixpkgs.

### Steps to reproduce

1) Install `abcde` globally (not in `nix-shell`).
2) Make sure `~/.abcde.conf` includes `CDDBMETHOD=musicbrainz`.
3) Insert a CD.
4) Run `abcde`.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.42, NixOS, 18.09.git.649791c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `""`
 - nixpkgs: `/home/james/nixpkgs`
```

**Comment by pSub** [comment]
That dependency seems to be included already. I don't have a CD drive. Is there an other way to reproduce?

**Comment by league** [comment]
I am experiencing this problem too. Even without a CD drive, you should be able to reproduce simply by running `abcde-musicbrainz-tool`. This is an auxiliary program invoked by `abcde`, a wrapped Perl script that will immediately attempt to import the module in question:

```perl
use WebService::MusicBrainz::Release;
```

and fail as described.

I have been able to get partway there by manually prefixing with a PERL5LIB environment variable:

```
PERL5LIB=/nix/store/lvqmkg234gm5w7w2diwnxwagc16wf7zg-perl-WebService-MusicBrainz-0.93/lib/perl5/site_perl abcde-musicbrainz-tool
```

That invocation dies with

```
Can't locate MusicBrainz/DiscID.pm
```

and then presumably I can go find that and add it to the manual PERL5LIB, but now I'm chasing all the dependencies manually.

There's no `perlWithPackages` though, right? I don't know how to refer to a Perl that has all required dependencies.

**Comment by bjornfor** [comment]
Backported to release-18.09: f5689d5d6b9be626e8528cb63e2f2cf8f9a0c87e.

**Comment by laMudri** [comment]
Can confirm that this is working. :+1:

**Comment by docum3nt** [comment]
It's broken anyway. I just tried `cpan install WebService::MusicBrainz::Release` and it install a huge bunch of stuff but ended up with:

      BFAIST/WebService-MusicBrainz-0.94.tar.gz
      Has already been unwrapped into directory /home/peter/.cpan/build/WebService-MusicBrainz-0.94-1
    Configuring B/BF/BFAIST/WebService-MusicBrainz-0.94.tar.gz with Build.PL
    Created MYMETA.yml and MYMETA.json
    Creating new 'Build' script for 'WebService-MusicBrainz' version '0.94'
      BFAIST/WebService-MusicBrainz-0.94.tar.gz
      /usr/bin/perl Build.PL --installdirs site -- OK
    Running Build for B/BF/BFAIST/WebService-MusicBrainz-0.94.tar.gz
    Building WebService-MusicBrainz
      BFAIST/WebService-MusicBrainz-0.94.tar.gz
      ./Build -- OK
    Running Build test
    t/Artist.t ........ 1/? URL (http://musicbrainz.org/ws/1/artist/4eca1aa0-c79f-481b-af8a-4a2d6c41aa5c?type=xml) Request Failed - Code: 410 Error: Gone
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 255 just after 3.
    t/Artist.t ........ Dubious, test returned 255 (wstat 65280, 0xff00)
    All 3 subtests passed 
    t/Label.t ......... ok   
    t/Release.t ....... 1/? URL (http://musicbrainz.org/ws/1/release/?type=xml&title=Van+Halen) Request Failed - Code: 410 Error: Gone
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 255 just after 3.
    t/Release.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
    All 3 subtests passed 
    t/ReleaseGroup.t .. ok   
    t/Track.t ......... ok   
    
    Test Summary Report
    -------------------
    t/Artist.t      (Wstat: 65280 Tests: 3 Failed: 0)
      Non-zero exit status: 255
      Parse errors: No plan found in TAP output
    t/Release.t     (Wstat: 65280 Tests: 3 Failed: 0)
      Non-zero exit status: 255
      Parse errors: No plan found in TAP output
    Files=5, Tests=15,  7 wallclock secs ( 0.03 usr  0.01 sys +  0.52 cusr  0.07 csys =  0.63 CPU)
    Result: FAIL
    Failed 2/5 test programs. 0/15 subtests failed.
      BFAIST/WebService-MusicBrainz-0.94.tar.gz
      ./Build test -- NOT OK
    //hint// to see the cpan-testers results for installing this module, try:
      reports BFAIST/WebService-MusicBrainz-0.94.tar.gz
    $

I'm not a Perlie, so I have no idea how to report this or where to fix it.
