### ISSUE TITLE
fetchurl: quoted arguments in curlOpts don't work

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#41820]
## Issue description
I was trying to download something that required that I put a token to the header.
That has to be quoted mind you.

```
url = https://some.where.in.the.internet.com
curlOpts = '' -H "PRIVATE-TOKEN: XXXXXXX" ''
```
Then I got these errors:
```
curl: (6) Could not resolve host: XXXXXXXXX"
curl: (22) The requested URL returned error: 404 Not Found
```
Then it tries to download what's in the url, but It can't because that token authorizes it.

Clearly not what I wanted :)

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.09pre140958.696c6bed4e8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre140958.696c6bed4e8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @copumpkin @dtzWill

**Comment by orivej** [comment]
This seems difficult to support. You could use `-H PRIVATE-TOKEN:XXXXXXX` or `-H @headers.txt` (e.g. `-H @${writeText "headers.txt" "PRIVATE-TOKEN: XXXXXXX"}`) instead.

**Comment by worldofpeace** [comment]
@orivej 
> This seems difficult to support.


I honestly think someone would expect this to just work like that. Perhaps there should be a note somewhere, if no one is interested in supporting this, that you cannot use quoted args here.

> You could use -H PRIVATE-TOKEN:XXXXXXX or -H @headers.txt (e.g. -H @${writeText "headers.txt" "PRIVATE-TOKEN: XXXXXXX"}) instead.

Either of those are a workaround for me at least :+1: . But there could be more complex times when this isn't enough.

**Comment by orivej** [comment]
> I honestly think someone would expect this to just work like that. Perhaps there should be a note somewhere, if no one is interested in supporting this, that you cannot use quoted args here.

Actually you can use such quoted args only in scripts (e.g. `buildPhase` or `postInstall`).

This could be made to work with Nix 2 and its structured attributes feature (even while maintaining compatibility with Nix 1):
```
curlOpts = [ "-H" "PRIVATE-TOKEN: XXXXXXX" ];
```

**Comment by rileyinman** [comment]
I believe this can still be implemented, and would be better than the current solution of writeText.

**Comment by codygman** [comment]
I just had this need in svanderburg/node2nix#172. The file workaround worked, but it took a very very long time to find this issue.

**Comment by kvtb** [comment]
still an issue
and why it is difficult to support?
looks like a trivial bug
