### ISSUE TITLE
Ledger-autosync is missing

### ISSUE THREAD

**Issue by PlasmaShift** [NixOS/nixpkgs#41836]
## Issue description
Can't find ledger-autosync or subsequently install it

I can see evedancs that ledger-autosync was installable in
[https://github.com/NixOS/nixpkgs/issues/13411](url)

### Steps to reproduce
nix search ledger-autosync
nix-env -iA nixos.python27Packages.ledger-autosync
nix-env -iA nixos.pythonPackages.ledger-autosync

don't find it

## Technical details

nix-shell -p nix-info --run "nix-info -m"                                                                                                       ~/
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.09pre140958.696c6bed4e8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre140958.696c6bed4e8, unstable-18.03pre119292.cfafd6f5a8, nixpkgs-18.03pre117898.5a21efdcdf"`
 - channels(PlasmaStrike): `"nixos-18.03pre126798.42b9b8f7c86"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## As a side note
On NixOs unstable how do I install a specific channel version of Emacs, i want Emacs 26. I can see hydra is building Emacs successfully here [https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.emacs26.x86_64-linux](url) But don't know how to get one of those builds in my config?

**Comment by ryantm** [comment]
It was removed in https://github.com/NixOS/nixpkgs/commit/e86b3a07d188950f2c46af7c09df9ab16c6f4aed by @adisbladis 
Discussion here https://github.com/NixOS/nixpkgs/pull/30919

**Comment by ryantm** [comment]
It looks like there is nothing specifically against it aside from lack of maintenance, so if someone were to add it back in and volunteer to maintain it that would probably be accepted.

**Comment by wamserma** [comment]
on NixOS 20.03:

```
> nix search ledger-autosync
* nixpkgs.ledger-autosync (ledger-autosync)
  OFX/CSV autosync for ledger and hledger
```
@PlasmaShift @ryantm I think this can be closed.
