### ISSUE TITLE
rabbitmq-server 3.6.x has reached end of life

### ISSUE THREAD

**Issue by joehealy** [NixOS/nixpkgs#41832]
## Issue description
The current version of rabbitmq-server in nixpkgs has reached eol:

https://www.rabbitmq.com/news.html#2018-05-09T17:00:00+00:00

It would be good to upgrade to 3.7.5.

**Comment by andir** [comment]
There have been two attempts to update RabbitMQ. @Profpatsch seems to be one of the bigger stakeholders in this.
https://github.com/NixOS/nixpkgs/pull/39466
https://github.com/NixOS/nixpkgs/pull/34265

**Comment by Profpatsch** [comment]
Yes! We should update now.

**Comment by joehealy** [comment]
What is holding the application of #34265 up? Is it responding to the review then getting it applied?

**Comment by Profpatsch** [comment]
Jep, basically.

**Comment by globin** [comment]
cc @grahamc, too

**Comment by aanderse** [comment]
@joehealy this can be closed as the package has been updated as requested in master.

**Comment by joehealy** [comment]
great thanks
