### ISSUE TITLE
seahorse requires gnome3.dconf

### ISSUE THREAD

**Issue by gmarmstrong** [NixOS/nixpkgs#41886]
## Issue description

Launching Seahorse without `gnome3.dconf` installed causes a warning:

```
(seahorse:1707): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

Trying to select any keyring in the sidebar fails and causes the warning to repeat.

https://github.com/NixOS/nixpkgs/issues/14966 seems related.

### Steps to reproduce

Install Seahorse (without GNOME in my case). Launch `seahorse` from the command line, and see the warning in the output. Try to select a keyring in the Seahorse sidebar to repeat the warning. The keyrings cannot be selected.

### Steps to fix

Add `gnome3.dconf` to `environment.systemPackages`.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.132645.43c77db3aa5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03"`
 - channels(guthrie): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### Additional notes

**I'll create a PR to fix this in a few minutes.**

**Comment by jtojnar** [comment]
`gnome3.dconf` is a system service that needs to be added to `services.dbus.packages` by your desktop environment. If you create your own environment, you will need to add it yourself (adding `programs.dconf.enable = true;` to `configuration.nix` should work). Nix does not contain a mechanism for representing a dependency on a service.
