### ISSUE TITLE
I just spent hours bisecting to find a single commit making mpv unable to play anything, only for it to suddenly start working

### ISSUE THREAD

**Issue by Infinisil** [NixOS/nixpkgs#41905]
## Issue description
I really don't know what's going on here, mpv was failing for me to play all files, it just got stuck on something. Invoking it with `-v` ended with something like `yt-dl hook`.

I spent about a whole day bisecting this problem. Started with the bad state in master, good state in 18.03. Just now I found the commit that broke it: 7d0906eea89f94b24d9df9af90579a88422dc126. It seems pretty much unrelated, but running
```
$ nix-build -A mpv
$ result/bin/mpv /path/to/some/file.mp4
```
failed on that commit, but worked perfectly fine on the one before.

But then suddenly, I can't reproduce it anymore (that's also the reason I don't know the exact line it got stuck on anymore, and unfortunately I closed the terminal inbetween..), all files just start playing just fine on all commits, problem gone! Maybe something to do with free memory? But that shouldn't cause it to block completely in the first place..

I feel like there's some impurity lingering somewhere in there.. Just writing this in the hopes that if somebody else ever has such a problem, they might find this issue.

### Steps to reproduce
?????

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.09pre-git (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(infinisil): `""`
 - nixpkgs: `/cfg/external/nixpkgs`

**Comment by Mic92** [comment]
Should we keep this issue open? I do not see anything actionable here.

**Comment by Infinisil** [comment]
Yeah :)
