### ISSUE TITLE
chromium: swiftshader broken, enable_swiftshader has no effect

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#41918]
## Issue description

In https://github.com/NixOS/nixpkgs/pull/29335 the copying of Chromium's swiftshader `.so` files was removed:

```diff
-cp -v "$buildPath/swiftshader/"*.so "$libExecPath/swiftshader/"
```

[due to an accident after it being defaulted to false](https://github.com/NixOS/nixpkgs/pull/29335#issuecomment-396750813).

This [breaks](https://github.com/NixOS/nixpkgs/pull/29335#issuecomment-396283609) the effect of `enable_swiftshader = true`; it has no effect.

We should do that copy exactly when `enable_swiftshader = true`.

### Steps to reproduce

1. Build chromium with `enable_swiftshader = true`
2. Run with `/nix/store/....-chromium-66.0.3359.181/bin/chromium --user-data-dir=/tmp/nix-chromium-temp-data-dir --use-gl=swiftshader`
3. See in `chrome://gpu` that SwiftShader is not shown, and WebGL is broken

---

CC @bendlas @aszlig

**Comment by bendlas** [comment]
Sounds good to me. Do you want to prepare the PR?

**Comment by nh2** [comment]
> Sounds good to me. Do you want to prepare the PR?

@bendlas Yes. By now I also think that it's a good idea to enable swiftshader by default:

PR #83304
