### ISSUE TITLE
Bluetooth fails to connect after resume

### ISSUE THREAD

**Issue by ivanovsaleksejs** [NixOS/nixpkgs#41912]
## Issue description
After suspend-resume I'm trying to connect via blueman-manager but I'm getting an error:
```fail (/nix/store/39x33f2aw9jp5387wighw6z7790xzxjy-blueman-2.0.4/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:124)
fail org.freedesktop.DBus.Python.blueman.bluez.errors.DBusFailedError: DBusFailedError: Resource temporarily unavailable
 
/nix/store/39x33f2aw9jp5387wighw6z7790xzxjy-blueman-2.0.4/lib/python2.7/site-packages/blueman/gui/manager/ManagerProgressbar.py:165: Warning: Source ID 403 was not found when attempting to remove it
  GObject.source_remove(self.gsource)
```
After I run `systemctl restart bluetooth` I can connect again.

### Steps to reproduce
1) Enable bluetooth;
2) Suspend and resume;
3) Try to connect.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.44, NixOS, 18.03.132645.43c77db3aa5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132645.43c77db3aa5"`
 - channels(aleksejs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by joepie91** [comment]
Likely this bug, that I just ran into as well: https://bugzilla.redhat.com/show_bug.cgi?id=1534857

An [upstream patch](https://marc.info/?l=linux-bluetooth&m=151801178209679&w=2) for this issue exists, and should probably be applied to our bluez.

**Comment by jraygauthier** [comment]
See https://github.com/NixOS/nixpkgs/pull/45901. This problem is fixed with bluez-5.50

**Comment by joepie91** [comment]
Problem no longer occurs for me in 18.09.

**Comment by thorstenweber83** [comment]
@ivanovsaleksejs can you please check if this is still an issue for you?
If not could you please close the issue?
Thanks!

**Comment by ivanovsaleksejs** [comment]
The problem does not appear anymore.
