### ISSUE TITLE
ghcjs-ng derivations are missing the haskellCompilerName attribute

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#41943]
## Issue description

The ghcjs-ng derivations (i.e. `haskell.packages.ghcjs82` and `haskell.packages.ghcjs84`) don’t have `haskellCompilerName` attributes. This means that `haskellSrc2nix` and thereby also `hackage2nix` and `callCabal2nix` will fail complaining about a missing attribute.

### Steps to reproduce
Use `haskell.packages.ghcjs84.hackage2nix` on any package.

**Comment by cocreature** [comment]
That was really quick, thanks a lot @matthewbauer!

**Comment by matthewbauer** [comment]
Yeah we hit that in reflex-platform - I just forgot to upstream it.
