### ISSUE TITLE
Remote unlocking encrypted root partition

### ISSUE THREAD

**Issue by jgeerds** [NixOS/nixpkgs#4196]
It is already possible to boot NixOS from a encrypted root partition. However, unlocking a partition remotely through SSH (dropbear) would be a nice feature. Has someone already tried this in NixOS?

**Comment by dezgeg** [comment]
This is implemented by https://github.com/NixOS/nixpkgs/pull/10460, right?

**Comment by garbas** [comment]
@dezgeg i think so. i'm closing this ticket.
@jgeerds could you confirm this solves the issue for you? if it doesn't, please re-open this ticket.
