### ISSUE TITLE
ruby build segfaults when nix-daemon runs inside a `ulimit -s 300000`

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#41997]
## Issue description
I'm building ruby on a CentOS machine with a custom nix prefix. (The installation is with a regular user, without root privileges running the nix-daemon in a mutually trusted multi-user setup.)
When I tried building ruby (for nixpkgs at 211309626af028dba079f7b8c08c5bf63a7a2969), I get a segfault:
```
    linking miniruby
    generating encdb.h
    make: *** [uncommon.mk:625: .rbconfig.time] Segmentation fault (core
    dumped)
    make: *** Waiting for unfinished jobs....
    make: *** [uncommon.mk:818: encdb.h] Segmentation fault (core dumped)
```
The segfault occurs in `reserve_stack` (thread_pthread.c:722)
This seems to be a long standing issue for ruby, since there are lots of threads discussing this online.
Most of the suggestions revolve around configuring with `--with-setjmp-type=_setjmp` or compiling with `-O0`, `-fno-omit-frame-pointer`, `-fno-stack-protector`. Sadly none of those suggestions worked.

I did however manage to build ruby when running the `nix-daemon` inside a shell where I set the stacksize to unlimited using `ulimit -s unlimited`. My CentOS machine seems to have a default value of `ulimit -s 300000`. This default leads to a crash of miniruby during the build.
This seems like an impurity in the build process.

My nix setup might be a really weird edge-case, but I was wondering if we should still set `uname -s unlimited` in the `preBuild` phase in nixpkgs.

**Comment by dtzWill** [comment]
Another workaround would be using gcc6, perhaps: https://github.com/rbenv/ruby-build/issues/1092
https://github.com/rbenv/ruby-build/issues/1115 .

I wonder if this happens in latest version?

That's quite the stack size limit (300MB!), so it seems surprising ruby exhausts it during the build?

However setting consistent limits seems like a good idea-- IIRC there's a TODO for this already near where we set the limit for core dumps :).

**Comment by knedlsepp** [comment]
I tried this with both the nixpkgs-17.09 gcc 6.4.0, as well as with the CentOS gcc 4.8.x compiler. From what I've read in the forums this issue has shown in one form or another for ruby builds in the last six years, so it's probably not something that can be solved in the context of nixpkgs. What surprised me the most, was however the "impurity" involved with setting `ulimit -s unlimited` outside of nix-build.

**Comment by knedlsepp** [comment]
Sadly I cannot reproduce this issue on a different machine with the same nixpkgs checkout. I guess I'll close this then, as I don't see any action item.
