### ISSUE TITLE
ghc 8.4.3 is broken in master

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#42033]
`haskell.compiler.ghc843` no longer compiles in current versions of `master`: https://hydra.nixos.org/build/75863743.

Ping @Ericson2314. Could it be that 812decd5c1abe497d44d7752fb295b69d6eed100 is incomplete here?

**Comment by matthewbauer** [comment]
We don't think it's that commit. More likely one of:

- 529a0f74edc
- eeeaab8d5e0

**Comment by Ericson2314** [comment]
I just compiled it on master `HEAD`. Weird!

**Comment by peti** [comment]
I restarted the build on Hydra, and it failed again. Then I ran it locally using commit 1511a45ba65e502e210306969f4a001241911, and it succeeded there. Wonderful. :confused: 

Hydra has been acting strange lately (running out of memory, etc.). Maybe these build failures are another side effect of those troubles.

**Comment by Ericson2314** [comment]
Let's hope! Thanks for pinging me.
