### ISSUE TITLE
Support for compilers and build tools in profiles

### ISSUE THREAD

**Issue by uri-canva** [NixOS/nixpkgs#42059]
I'm planning to use nix as a package manager for my development toolchain, but not do the actual development in nix, is that a supported use case?

I've hit some issues and have been sending in PRs to resolve them, but looking into it more the issues I've been hitting might have been derivations just working as intended.

https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F explains that library derivations in Nix only work when used in a nix environment, be it nix-shell or within nixpkgs.

Is the same true for all development derivations, for example compilers and build tools?

Examples:
1. clang++ doesn't work outside of nix-shell on darwin, but it does on linux, and I'm not sure which of the two is correct (#41589).
2. wrapCC creates compiler wrappers to handle the way flags from dependencies are propagated in nixpkgs, but those wrappers are unnecessary when using the compilers from profiles.
3. in the bazel derivation `bin/bazel` is a script that wraps bazel to make it use clang and java from nix, instead of resolving it from the caller's `PATH`, so that it can be used from within nixpkgs, but it results in a bazel that doesn't function correctly when installed.

If existing development derivations are meant to be only used in a nix environment, would it be ok to add new derivations for use outside of a nix environment?

**Comment by orivej** [comment]
Nixpkgs do not explicitly support C++ compilers outside Nix environment, but this is a valuable use case and it would be great if you could work towards it.

**Comment by uri-canva** [comment]
It won't be helpful if there's no convention around it, how would someone find out which specific compilers work outside a Nix environment and which don't?

**Comment by uri-canva** [comment]
I have managed to work around this issue by creating wrappers for the compilers tailored to the specific use cases I have. It works very well, and it seems it's what others are doing as well. I'll close this issue since it's not relevant anymore.
