### ISSUE TITLE
Cannot build docker image as part of a derivation

### ISSUE THREAD

**Issue by samuelrivas** [NixOS/nixpkgs#42064]
## Issue description

This may be not a nix-proper way of doing it, but I have some derivations that build docker images, that are then used by the scripts that are part of the derivation. That used to work but seems to have broken in some update.

The problem seems to be that the build users cannot connect to the docker daemon. I get 

    time="2018-06-15T08:54:54Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied"

Is there a proper way to solve this? I guess I could add all the nixbld users to the docker group, but that seems hacky, unless there is a clean way of doing that in nixos' configuration file.

### Steps to reproduce
 
Create a Dockerfile, for example like this:

    FROM python:3.6-slim

    ARG uid=1000
    ARG gid=100
    ARG user_name=docker_user

    RUN useradd -r -m -d /home/$user_name --gid $gid --uid $uid $user_name
    CMD /bin/bash

And a derivation like this

    {
      docker,
      stdenv,
    }:

    stdenv.mkDerivation rec {

      name = "generic-python-env";
      src = ./../src;

      buildInputs = [
        docker
      ];

      installPhase = ''
        mkdir -p "$out/bin"
        mkdir -p "$out/etc"

        cp "$src/Dockerfile" "$out"
        cp "$src/Makefile" "$out"
      '';
    }

And a Makefile like this

    all: Dockerfile
    	whoami
    	docker build --rm -t test .

Put everything in their right places and try to build with `nix-build`, and you should get:

    whoami
    nixbld1
    docker build --rm -t test .
    time="2018-06-15T09:14:57Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied"

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.46, NixOS, 18.03.132545.c40fdcd26c2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(samuel): `""`
 - channels(root): `"nixos-18.03.132545.c40fdcd26c2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by manveru** [comment]
I assume this worked when your system was single user? The normal way to build docker images with nix is to use `dockerTools.buildImage`, otherwise how do you specify your `python:3.6-slim` input?

This should build an image for you:

    with import (fetchTarball {
      url = "https://github.com/nixos/nixpkgs/archive/a8c71037e041725d40fbf2f3047347b6833b1703.tar.gz";
      sha256 = "1z4cchcw7qgjhy0x6mnz7iqvpswc2nfjpdynxc54zpm66khfrjqw";
    }) {};
    let
      pythonImage = dockerTools.pullImage {
        imageName = "python";
        imageDigest = "sha256:ce4ea6b8cb8730d6a48b747037d0448b8151ea666d65f58e1b967147b0787734";
        sha256 = "0na3idj2g4zzg39h0g55wzwy2vpvbblfrw3iw1b1ybaqn6bvs6nz";
        finalImageTag = "3.6-slim";
      };
    in dockerTools.buildImage {
      name = "python-shell";
      fromImage = pythonImage;
      contents = [ bashInteractive shadow ];
      runAsRoot = ''
        #!${stdenv.shell}
        set -ex
        useradd -r -m -d /home/docker_user --gid 100 --uid 1000 docker_user
      '';

      config = {
        User = "docker_user";
        Cmd = "${bashInteractive}/bin/bash";
      };
    }

You can use it with `docker load -i /nix/store/kv7hqblz12ndmpkmlkm560mdx79j5k2c-docker-image-python-shell.tar.gz` and then `docker run --rm -ti python-shell:latest python --version`

**Comment by samuelrivas** [comment]
> I assume this worked when your system was single user? The normal way to build docker images with nix is to use dockerTools.buildImage, otherwise how do you specify your python:3.6-slim input?

Before nixos-18.03 I just used a regular Dockerfile and run docker
build when building the derivation, but I was aware that it was not
really repeatable. I didn't know of docekerTools, it seems exactly
what I need, I'll give it a try as soon as I have time. Thanks!
>
> This should build an image for you:
>
> with import (fetchTarball {
>   url = "https://github.com/nixos/nixpkgs/archive/a8c71037e041725d40fbf2f3047347b6833b1703.tar.gz";
>   sha256 = "1z4cchcw7qgjhy0x6mnz7iqvpswc2nfjpdynxc54zpm66khfrjqw";
> }) {};
> let
>   pythonImage = dockerTools.pullImage {
>     imageName = "python";
>     imageDigest = "sha256:ce4ea6b8cb8730d6a48b747037d0448b8151ea666d65f58e1b967147b0787734";
>     sha256 = "0na3idj2g4zzg39h0g55wzwy2vpvbblfrw3iw1b1ybaqn6bvs6nz";
>     finalImageTag = "3.6-slim";
>   };
> in dockerTools.buildImage {
>   name = "python-shell";
>   fromImage = pythonImage;
>   contents = [ bashInteractive shadow ];
>   runAsRoot = ''
>     #!${stdenv.shell}
>     set -ex
>     useradd -r -m -d /home/docker_user --gid 100 --uid 1000 docker_user
>   '';
>
>   config = {
>     User = "docker_user";
>     Cmd = "${bashInteractive}/bin/bash";
>   };
> }
>
> You can use it with docker load -i /nix/store/kv7hqblz12ndmpkmlkm560mdx79j5k2c-docker-image-python-shell.tar.gz and then docker run --rm -ti python-shell:latest python --version
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
Samuel

**Comment by FRidh** [comment]
Closing because the reported use case was not supported.
