### ISSUE TITLE
inkscape fails with argument list too long

### ISSUE THREAD

**Issue by LnL7** [NixOS/nixpkgs#42093]
## Issue description

This is blocking nixpkgs-unstable, all jobs that are part of unstable should probably also have a maintainer.

/cc @matthewbauer

```
[ 89%] Building CXX object src/CMakeFiles/inkscape_base.dir/splivarot.cpp.o
[ 89%] Building CXX object src/CMakeFiles/inkscape_base.dir/viewbox.cpp.o
[ 89%] Linking CXX shared library ../lib/libinkscape_base.dylib
/nix/store/jpwsh1pzwnizdzqk2l266526j9ap1r5j-clang-wrapper-5.0.2/bin/clang++: line 183: /nix/store/zq6w7nl1fgkm2449ip0f5rbjbczn8lb7-clang-5.0.2/bin/clang++: Argument list too long
make[2]: *** [src/CMakeFiles/inkscape_base.dir/build.make:10488: lib/libinkscape_base.dylib] Error 126
make[1]: *** [CMakeFiles/Makefile2:695: src/CMakeFiles/inkscape_base.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
builder for '/nix/store/xq31kqr6k7rhnvplil8i54b310cbh7ql-inkscape-0.92.3.drv' failed with exit code 2
```

### Steps to reproduce

https://hydra.nixos.org/build/75956995

```sh
nix-build pkgs/top-level/release.nix -A inkscape.x86_64-darwin
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by jtojnar** [comment]
This was already solved once: https://github.com/NixOS/nixpkgs/issues/39175

**Comment by LnL7** [comment]
That's from a month ago, the problem was reintroduced a 1 or 2 days ago.

**Comment by matthewbauer** [comment]
Yeah fwiw switching to make seemed to solve it (but introduces its own issues). Has anything big changed in the last two days?

**Comment by matthewbauer** [comment]
Fixed in 1f8f89d309eeebfe00b25c30cc9dca103f3d8b47.

**Comment by dhess** [comment]
I'm seeing this problem on multiple other packages on macOS, e.g., `stack` and a few of my own Haskell packages that I build with Nix. Does this mean I need to add `strictDeps = true` to all of these packages? If so, that doesn't seem like a robust fix.

**Comment by dhess** [comment]
Thanks for the pointer to #41420. I'll take this over there.
