### ISSUE TITLE
[closure size]: nfs-utils depends on gcc and bootstrap-tools

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#42104]
## Issue description

```nfs-utils``` (```grub2```'s dependency, so it is in every closure) depends on ```bootstrap-tools``` (110Mb) and ```gcc```  (130Mb).

### Steps to reproduce

```$ strings nfs-server-generator | grep gcc```
```
/nix/store/d1prcspbh2qsviipvnaxizcj8l3g7fpw-bootstrap-tools/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include                           
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/include                                 
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/crtbegin.o                              
/nix/store/jbifj9j7jpycamc950i898msrxxj876k-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/crtend.o                                
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.0, NixOS, 18.09.771-g124b640 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/store/0xcp3l506zgx3n1kpxyx6ry09h3ji58s-master-2018-06-10`

**Comment by dezgeg** [comment]
IIRC when I looked into this, one problem was this `kerberosEnv` in `pkgs/os-specific/linux/nfs-utils/default.nix`:
````
  9   # Not nice; feel free to find a nicer solution.
 10   kerberosEnv = buildEnv {
 11     name = "kerberos-env-${kerberos.version}";
 12     paths = with lib; [ (getDev kerberos) (getLib kerberos) ];
 13   };
````
which would then eventually hold a reference to `kerberos.dev` which referred to a bunch of other dev stuff.

I presume that one requires patching the autoconf scripts to be able to find Kerberos headers and libraries from separate directories.

**Comment by volth** [comment]
As a simple fix, that dependency (anyclosure -> grub -> zfs-util -> nfs-utils -> gcc) may be torn apart by accepting https://github.com/NixOS/nixpkgs/pull/30192

**Comment by vcunat** [comment]
This doesn't hold anymore, neither on master/unstable nor on 18.09.  Note that the oldest version there is nfs-utils-2.3.2 ATM, i.e. you must be catching some unmaintained nixpkgs commit.

Well, on master the closure isn't too small, but it doesn't fit the original post, so we'd better open another issue if that's still considered a problem.
