### ISSUE TITLE
Get rid of builderDefsPackage

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4210]
We have too many ways to write packages, let's get rid of ways we all agree they're deprecated. Any reason to keep builderDefsPackage?

```
$ git grep ^builderDefsPackage|wc -l
93
```

**Comment by iElectric** [comment]
78 left:

```
pkgs/applications/misc/vue/default.nix:builderDefsPackage
pkgs/applications/networking/instant-messengers/oneteam/default.nix:builderDefsPackage
pkgs/applications/networking/instant-messengers/vacuum/default.nix:builderDefsPackage
pkgs/applications/science/logic/cvc3/default.nix:builderDefsPackage
pkgs/applications/science/logic/iprover/default.nix:builderDefsPackage
pkgs/applications/science/logic/leo2/default.nix:builderDefsPackage
pkgs/applications/science/logic/minisat/default.nix:builderDefsPackage
pkgs/applications/science/logic/opensmt/default.nix:builderDefsPackage
pkgs/applications/science/logic/satallax/default.nix:builderDefsPackage
pkgs/applications/science/logic/spass/default.nix:builderDefsPackage
pkgs/applications/science/logic/tptp/default.nix:builderDefsPackage
pkgs/applications/science/math/gap/default.nix:builderDefsPackage
pkgs/applications/science/math/singular/default.nix:builderDefsPackage
pkgs/applications/version-management/veracity/default.nix:builderDefsPackage
pkgs/applications/window-managers/fbpanel/default.nix:builderDefsPackage
pkgs/applications/window-managers/stalonetray/default.nix:builderDefsPackage
pkgs/build-support/builder-defs/template-auto-callable.nix:builderDefsPackage
pkgs/data/fonts/andagii/default.nix:builderDefsPackage
pkgs/data/fonts/anonymous-pro/default.nix:builderDefsPackage
pkgs/data/fonts/cm-unicode/default.nix:builderDefsPackage
pkgs/data/fonts/eb-garamond/default.nix:builderDefsPackage
pkgs/data/fonts/gentium/default.nix:builderDefsPackage
pkgs/data/fonts/inconsolata/default.nix:builderDefsPackage
pkgs/data/fonts/oldstandard/default.nix:builderDefsPackage
pkgs/data/fonts/source-code-pro/default.nix:builderDefsPackage
pkgs/data/fonts/tempora-lgc/default.nix:builderDefsPackage
pkgs/data/fonts/theano/default.nix:builderDefsPackage
pkgs/development/compilers/eql/default.nix:builderDefsPackage
pkgs/development/interpreters/angelscript/default.nix:builderDefsPackage
pkgs/development/interpreters/j/default.nix:builderDefsPackage
pkgs/development/interpreters/kona/default.nix:builderDefsPackage
pkgs/development/interpreters/picolisp/default.nix:builderDefsPackage
pkgs/development/interpreters/regina/default.nix:builderDefsPackage
pkgs/development/libraries/allegro/5-unstable.nix:builderDefsPackage
pkgs/development/libraries/allegro/5.nix:builderDefsPackage
pkgs/development/libraries/allegro/default.nix:builderDefsPackage
pkgs/development/libraries/box2d/2.0.1.nix:builderDefsPackage
pkgs/development/libraries/box2d/default.nix:builderDefsPackage
pkgs/development/libraries/cgui/default.nix:builderDefsPackage
pkgs/development/libraries/dssi/default.nix:builderDefsPackage
pkgs/development/libraries/geoclue/default.nix:builderDefsPackage
pkgs/development/libraries/ggz_base_libs/default.nix:builderDefsPackage
pkgs/development/libraries/libfixposix/default.nix:builderDefsPackage
pkgs/development/libraries/libgdata/0.6.nix:builderDefsPackage
pkgs/development/libraries/ois/default.nix:builderDefsPackage
pkgs/development/libraries/openscenegraph/default.nix:builderDefsPackage
pkgs/development/libraries/speech-tools/default.nix:builderDefsPackage
pkgs/development/libraries/srtp/default.nix:builderDefsPackage
pkgs/development/libraries/unicap/default.nix:builderDefsPackage
pkgs/development/tools/build-managers/bam/default.nix:builderDefsPackage
pkgs/games/atanks/default.nix:builderDefsPackage
pkgs/games/gl-117/default.nix:builderDefsPackage
pkgs/games/glestae/default.nix:builderDefsPackage
pkgs/games/sauerbraten/default.nix:builderDefsPackage
pkgs/games/soi/default.nix:builderDefsPackage
pkgs/games/stardust/default.nix:builderDefsPackage
pkgs/games/the-butterfly-effect/default.nix:builderDefsPackage
pkgs/games/warmux/default.nix:builderDefsPackage
pkgs/games/xconq/default.nix:builderDefsPackage
pkgs/misc/drivers/foo2zjs/default.nix:builderDefsPackage
pkgs/os-specific/linux/untie/default.nix:builderDefsPackage
pkgs/servers/http/4store/default.nix:builderDefsPackage
pkgs/servers/http/joseki/default.nix:builderDefsPackage
pkgs/tools/filesystems/smbnetfs/default.nix:builderDefsPackage
pkgs/tools/filesystems/udftools/default.nix:builderDefsPackage
pkgs/tools/filesystems/xtreemfs/default.nix:builderDefsPackage
pkgs/tools/graphics/barcode/default.nix:builderDefsPackage
pkgs/tools/graphics/welkin/default.nix:builderDefsPackage
pkgs/tools/graphics/zbar/default.nix:builderDefsPackage
pkgs/tools/misc/xdaliclock/default.nix:builderDefsPackage
pkgs/tools/networking/altermime/default.nix:builderDefsPackage
pkgs/tools/networking/mtr/default.nix:builderDefsPackage
pkgs/tools/networking/philter/default.nix:builderDefsPackage
pkgs/tools/networking/ripmime/default.nix:builderDefsPackage
pkgs/tools/networking/tftp-hpa/default.nix:builderDefsPackage
pkgs/tools/networking/wavemon/default.nix:builderDefsPackage
pkgs/tools/system/ioping/default.nix:builderDefsPackage
pkgs/tools/typesetting/tex/disser/default.nix:builderDefsPackage
```

**Comment by domenkozar** [comment]
72.

**Comment by domenkozar** [comment]
61

**Comment by domenkozar** [comment]
57

**Comment by domenkozar** [comment]
28 \o/

**Comment by rycee** [comment]
Sorry for the spammy commits. I didn't expect them to show up like this!

**Comment by domenkozar** [comment]
@rycee thanks! `24` left.

**Comment by domenkozar** [comment]
14 :tada:

**Comment by domenkozar** [comment]
Since #12701 there are 9 packages left and a few Tex packages.

**Comment by domenkozar** [comment]
@vcunat @7c6f434c is there a reason to keep the old texlive?

**Comment by 7c6f434c** [comment]
>@vcunat @7c6f434c is there a reason to keep the old texlive?

Hm, probably it's time to properly migrate to the new TeXLive…

Will check if verything goes smoothly.

**Comment by vcunat** [comment]
I expect there's no reason to keep it; just check for stray referrers.

**Comment by 7c6f434c** [comment]
How do I get `repstopdf` from the new `texlive`? Apparently this should be a symlink to `epstopdf` provided by `epstopdf`, but it is absent in our build.

**Comment by vcunat** [comment]
Well, the way it's done currently is rather hacky. Upstream apparently maintains a list of scripts which gets into `${texlive.bin.core.out}/share/texmf-dist/scripts/texlive/scripts.lst`, so I just symlink those that are present, using their basenames.

**Comment by 7c6f434c** [comment]
>Well, the way it's done currently is rather hacky. Upstream apparently maintains a list of scripts which gets into `${texlive.bin.core.out}/share/texmf-dist/scripts/texlive/scripts.lst`, so I just symlink those that are present, using their basenames.

Where you would put packages with manual additions to that list?

Currently, `repstopdf` is among things that make it impossible to 
compile my thesis using the new texlive (I don't need to be able to
compile it right now, but including eps into pdf may be needed by other
people, too).

I have not yet looked into the bibliography problem, apparently some
bibtex things have a version incompatible with the disser package. This
may be an upstream problem with disser, though.

**Comment by vcunat** [comment]
> Where you would put packages with manual additions to that list?

I don't know ATM. Also, maybe I've missed a better source of information and more executables are missing. I found no documentation on this and their install scripts were rather unreadable to me.

**Comment by domenkozar** [comment]
@7c6f434c let me know the resolution you get from this :)

**Comment by domenkozar** [comment]
@7c6f434c did you manage to migrate?

**Comment by 7c6f434c** [comment]
>@7c6f434c did you manage to migrate?

Well, we still need to do something about repstopdf (I currently have
just a dirty hack in my system). As for the disser package we could just
declare it broken upstream (I cannot build my thesis with TeXLive from 
last week's master, but fortunately I don't really need to rebuild it 
now anyway).

**Comment by domenkozar** [comment]
@7c6f434c I'll port then `repstopdf` to mkDerivation, hopefully you can combine it with new texlive. Sounds good?

**Comment by 7c6f434c** [comment]
>@7c6f434c I'll port then `repstopdf` to mkDerivation, hopefully you can combine it with new texlive. Sounds good?

There is no separate `repstopdf` package.

I was asking how to handle this best.

There is `epstopdf` package that works fine, but doesn't create the
`repstopdf` symlink. If the correct solution is just to have 
a single-symlink package, I can push such a trivial wrapper myself 
(I use it already). But initially I wondered whether @vcunat thinks 
there is a good way to specify such extra fixes in expressions like 
`epstopdf`, if there is an accepted better way, I would prefer to follow
it.

**Comment by domenkozar** [comment]
5.

**Comment by domenkozar** [comment]
Only `pkgs/applications/networking/instant-messengers/oneteam/default.nix` and tex packages left.

**Comment by joachifm** [comment]
`dict-db` and `relfs` are also using `builderDefs` machinery, so might be good to refactor those as well.

**Comment by domenkozar** [comment]
@joachifm ah you're right. 3 more then :)

**Comment by domenkozar** [comment]
I'm working to get this done.

**Comment by grahamc** [comment]
Nice work!
