### ISSUE TITLE
Emacs NIX_PATH issue?

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#42131]
It seems `emacs` is modifying my nix environment in some way, causing
problems for (at least) the haskell stack tool. Of course, it might be
something entirely different

``` example
$ realpath $(which emacs)
/nix/store/31aw9v9bkrl6686lb83jad1iii2gjr08-emacs-25.3/bin/emacs
```

From within emacs:

``` example
$ stack path --project-root
warning: Nix search path entry 'nixpkgs' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:14
```

``` example
$ echo $NIX_PATH
nixpkgs
```

From my shell

``` example
$ stack path --project-root
/home/simendsjo/code/tmp/aoeu
```

``` example
$ echo $NIX_PATH
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

I haven't overridden any emacs stuff in my configuration. My
configuration file is pretty much (although with more packages)

``` example
environment.systemPackages = with pkgs; [
  emacs
];
```

I've tried removing all custom channels, without any luck:

``` example
$ nix-channel --list
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-18.03
```

``` example
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/l3nz0167a4xhb78ldcjns5p4dwvlm1cw-stdenv
copying path '/nix/store/l3nz0167a4xhb78ldcjns5p4dwvlm1cw-stdenv' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.49, NixOS, 18.03.132687.14c248a4ab7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(simendsjo): `""`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by periklis** [comment]
- Which shell are you using inside emacs? eshell? term?
- Are you importing any env variables manually or by any package inside you emacs configuration?

**Comment by simendsjo** [comment]
> Which shell are you using inside emacs? eshell? term?
eshell, but it's unrelated to the shell. `(getenv "NIX_PATH")` returns `"nixpkgs"`

> Are you importing any env variables manually or by any package inside you emacs configuration?
Not consciously.. I'm using spacemacs.. I just tried running `emacs -q` and it seems NIX_PATH is set correctly. Guess it's some of the packages or spacemacs layers I'm using then. Not sure how I find out who's setting this though. I'm closing the issue as it's invalid. Thanks! :)

**Comment by tadfisher** [comment]
@simendsjo See https://github.com/syl20bnr/spacemacs/issues/10910

**Comment by simendsjo** [comment]
Ah, thanks! Looks like the cause. Right now I just store temporary before loading layers, and restore it after loading the layers.
