### ISSUE TITLE
Tectonic fails to build on Darwin

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#42142]
## Issue description

`tectonic` fails to compile on Darwin with the following error message:

```sh
   Compiling app_dirs v1.1.1
error[E0282]: type annotations needed
  --> /private/tmp/nix-build-tectonic-0.1.7.drv-0/tectonic-0.1.7-vendor/app_dirs/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^ cannot infer type for `T`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
builder for '/nix/store/wr4qy8g7lsqw7hh1a0z0fg1wwx5c5c5z-tectonic-0.1.7.drv' failed with exit code 101
error: build of '/nix/store/wr4qy8g7lsqw7hh1a0z0fg1wwx5c5c5z-tectonic-0.1.7.drv' failed
```

### Steps to reproduce

```
nix-build . -A tectonic
```

## Technical details

`nixpkgs` at 176380dbbbbf53434c0

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.6.0, macOS 10.13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixpkgs-18.09pre133932.ee28e35ba37"`
 - channels(smaret): `"nixpkgs-unstable-18.09pre142651.95a8cb3ade1"`
 - nixpkgs: `/Users/smaret/Documents/Software/nixpkgs`

**Comment by marsam** [comment]
This is a issue in [app_dirs](https://github.com/AndyBarron/app-dirs-rs/issues/28), should be fixed with https://github.com/NixOS/nixpkgs/pull/42215
