### ISSUE TITLE
godoc works as CLI, but not as HTTP server

### ISSUE THREAD

**Issue by campadrenalin** [NixOS/nixpkgs#4218]
When run with a package argument, we get documentation printed to STDOUT, as expected. So in this case, it's able to find the packages successfully.

However, if you run with `--http=:6060` (which hosts a server on localhost:6060), and try to access /pkg/fmt, you will be greeted with an error. In this case, godoc is looking for files in the wrong directory (one directory too high), and not finding the files it expects to exist.

This is the cause of at least some of the test failures for the godoc package (which is why testing is currently turned off for this package in the go/1.3.nix derivation). I'm not sure that it's the reason for _all_ the test failures for the godoc package, but it would be nice to at least cut this down, and get closer to being able to run the full suite of tests in the derivation. I really don't like having to skip tests.

**Comment by Profpatsch** [comment]
can be closed @Fuuzetsu
