### ISSUE TITLE
chromium: Fail build on wrong gn args

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#42189]
## Issue description

When building chromium with `gn` args like this

https://github.com/NixOS/nixpkgs/blob/4f9f2cbb40d37f975fd71693941973b36c1569ca/pkgs/applications/networking/browsers/chromium/common.nix#L218-L219

and the gn args aren't known/accepted by chromium (like the above one actually is that is still given incorrectly in 18.03), it will print:

```
WARNING at build arg file (use "gn args <out_dir>" to edit):22:13: Build argument has no effect.
use_gconf = false
            ^----
```

but continue to build anyway, which can be super surprising when your build doesn't do what you expect.

We should catch that when building.

Unfortunately `gn` doesn't seem to have a feature to warn.

But we can run `gn check DIR buildtarget` to see the `WARNING` in stdout and grep for it:

```
gn check out/Release/ chrome
WARNING at build arg file (use "gn args <out_dir>" to edit):22:13: Build argument has no effect.
use_gconf = false
```

I have confirmed that `gn check` only seems to work that way when giving a build target, like `chrome`.

CC @bendlas

**Comment by nh2** [comment]
Suggestion: We switch https://github.com/NixOS/nixpkgs/blob/4f9f2cbb40d37f975fd71693941973b36c1569ca/pkgs/applications/networking/browsers/chromium/common.nix#L262

to

```
      gn gen --args=${escapeShellArg gnFlags} out/Release | tee gn-gen-outputs.txt

      # Fail if `gn gen` contained a WARNING.
      ! grep -o WARNING gn-gen-outputs.txt
```

**Comment by nh2** [comment]
PR #42194

**Comment by Mic92** [comment]
pull request was merged.
