### ISSUE TITLE
zoom (the game) crashes

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#42245]
## Issue description

I don't use this package, but it should be marked broken or fixed. 

```
$ zoom
INTERPRETER PANIC - Unable to find game directory '/nix/store/7h97sf0fd9gjan2mxf5r22y975zw7hs9-zoom-1.1.5/share/zoom/games' (PC = #0)
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.git.14c248a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Lassulus** [comment]
According to the manual zoom needs to be run with a game file.
Games can be downloaded from here for example.: http://www.ifarchive.org/indexes/if-archiveXgamesXzcode.html testing it with a game works.

**Comment by xeji** [comment]
Closing as resolved.

**Comment by coretemp** [comment]
A program should not crash when it has no input. Please reopen.

You can't just close all my issues, because you disagree on something.

**Comment by Lassulus** [comment]
Well it's a complicated issue.
How do other distributions handle this case? Should we wrap the original game in the case the user didn't supply a game file and show the help for example (and exit with code 0)? this would make automatic updating and testing easier.

**Comment by coretemp** [comment]
Leave it open, contact upstream, or fix it. Those are the options. You provided one particular example of a fix.

**Comment by ber4444** [comment]
"zoom" (the game) should be also renamed as everyone is confusing it with the popular video conferencing software

**Comment by Lassulus** [comment]
> "zoom" (the game) should be also renamed as everyone is confusing it with the popular video conferencing software

sounds like a good idea, I guess back in 2018 this was not a big issue. Can you open a PR for it?
