### ISSUE TITLE
stage-1.nix fails to be built on nixos-unstable-small

### ISSUE THREAD

**Issue by eadwu** [NixOS/nixpkgs#42276]
## Issue description
Called it `stage-1.nix` because I don't really know what package it is and that it looked similar to https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-1.nix.

Don't really know why it fails to build though the questionable output to me `not an ELF executable`, `Couldn't satisfy dependency ld-linux-x86-64.so.2`, and `libssl.so.1.0.0: cannot open shared object file: No such file or directory`.

Output: https://pastebin.com/raw/Tizv6j7d
`debec6d` is the commit SHA after reverting so that I could isolate the logs.
```
debec6dd117fa8de91535c3b426abd02cfa2ddf8 Revert "inkscape: work around ARGMAX limit"
a5cd4b26851734a6d49b097d8d4da69b9b51d4a0 deepin.deepin-terminal: 2.9.2 → 3.0.0
8e786a5a6ca772601a04967749111fdfcd2d93b8 Merge pull request #42232 from mnacamura/lf-darwin
```

### Steps to reproduce
```
git clone https://github.com/NixOS/nixpkgs.git tmp
cd tmp
git checkout a5cd4b26851
git revert 1f8f89d
nixos-rebuild -I nixpkgs=. test
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.49, NixOS, 18.09.git.b348421 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre143553.a5cd4b26851"`
 - channels(yin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by peti** [comment]
Git bisect says the commit that broke the build is d72f22607acd26c04f4447f3db99946aa15f9fe2 from https://github.com/NixOS/nixpkgs/pull/38382.

**Comment by peti** [comment]
@dezgeg, when you say you'll have a fix soon, what time frame does that mean approximately? Minutes? Hours? Days?

**Comment by dezgeg** [comment]
Pushed f9218b1346a025d213dec6b838ef33864b3e3456. At least it passed the luksroot installer test for me.

**Comment by eadwu** [comment]
Works for me.

**Comment by dezgeg** [comment]
FWIW since I went and checked, the bug which only now surfaced has probably existed only since 897b7c7e9b45c6cb272f3221a28f2e5529a52e19 which is not in any release branch, so no need to cherry-pick anything.
