### ISSUE TITLE
 libvpx fails on darwin

### ISSUE THREAD

**Issue by ibeex** [NixOS/nixpkgs#4227]
make[1]: *** [vp9/common/x86/vp9_loopfilter_intrin_avx2.c.o] Error 1 
make: *** [.DEFAULT] Error 2
builder for ‘/nix/store/vp54pjxr8gsxkjqyyai35y20qx08jrrw-libvpx-1.3.0.drv’ failed with exit code 2
error: build of ‘/nix/store/vp54pjxr8gsxkjqyyai35y20qx08jrrw-libvpx-1.3.0.drv’ failed

related to https://github.com/NixOS/nixpkgs/issues/4117

**Comment by spwhitt** [comment]
This is fixed in master.

**Comment by vcunat** [comment]
Reopen otherwise.
