### ISSUE TITLE
Gnome3 on Wayland sets `SSH_AUTH_SOCK` which breaks stuff

### ISSUE THREAD

**Issue by dpc** [NixOS/nixpkgs#42291]
## Issue description

Gnome3 on Wayland sets `SSH_AUTH_SOCK` to `/run/user/1000/keyring/ssh` for no good reason:

https://unix.stackexchange.com/questions/315004/where-does-gnome-keyring-set-ssh-auth-sock
https://github.com/GNOME/gnome-session/commit/a8896ccad65583885735a04205351f48a42f29ae

Couple of places in Nixos relies on `SSH_AUTH_SOCK` being initially empty:

https://github.com/NixOS/nixpkgs/search?q=SSH_AUTH_SOCK&unscoped_q=SSH_AUTH_SOCK

### Steps to reproduce

Use Gnome3 on Wayland.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.09pre142796.4b649a99d84 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - channels(dpc): `"nixpkgs-18.09pre137243.31effc1d7d5"`
 - nixpkgs: `/home/dpc/.nix-defexpr/channels/nixpkgs`

**Comment by dpc** [comment]
Actually it is said to be droped in Version 3.25.3. https://github.com/GNOME/gnome-session/blob/0d6da15e38652e1a5f9198589d86e127a310c572/NEWS

**Comment by dpc** [comment]
Ehhh... Something, somewhere is setting this variable for no good reason.

**Comment by dpc** [comment]
Could it be: https://github.com/NixOS/nixpkgs/blob/9cd3c7a12ee6d131c9ea545c2c75b412b7506673/nixos/modules/services/x11/desktop-managers/gnome3.nix#L103 that unconditionally enabled keyring and thus breaks other stuff?

**Comment by jtojnar** [comment]
> for no good reason

The reason is that GNOME, like other desktop environments, tries to provide an integrated solution, including a key management.

This really should not be a problem, unless you want to use a different keyring. Then it should be easy to disable.

**Comment by jtojnar** [comment]
Regarding the environment variable, I think it comes from PAM, either

https://github.com/NixOS/nixpkgs/blob/cac9f088103828f2c24c42d7e8ef3530d49b1eb4/nixos/modules/security/pam.nix#L321

or

https://github.com/NixOS/nixpkgs/blob/cac9f088103828f2c24c42d7e8ef3530d49b1eb4/nixos/modules/services/x11/display-managers/gdm.nix#L199

We should probably consolidate those.

**Comment by dpc** [comment]
You're correct of course about the integrated env. And I indeed want a different keyring because gnome keyring does not support GPG smartcards which I heavily rely on. I can' ssh anywhere if gpg-agent is not an ssh-agent ...  BTW. This whole architecture of bunch of agents pretending to be each other and intercepting their own sockets is bizarre in the first place and I'm already used for this to be a problem wherever distro I use. :/

Actually, after quickly googling about it, it seems that newer gnome-keyring do support GPG smartcards: https://wiki.debian.org/Smartcards/YubiKey4#GNOME_Keyring , but it has to be configured in yet another place. Making all of this pieces work together well is probably outside of the scope of this github issue.

Please let me know if there's anything I could do beyond #42293 - please note I'm not very familiar with nixpkgs internals.

**Comment by jtojnar** [comment]
I still think that requiring `mkForce` in

```
  services.gnome3.gnome-keyring.enable = pkgs.lib.mkForce false;
```

is a right thing at the moment, as it makes sure user is aware of the risks.

---

Checking the build logs of gnome-keyring, gcr, libsecret, pinentry and gnupg, only the lattermost mentions smartcards and they are enabled. The Debian wiki talks about `pinentry-gnome` which you should be able to enable as follows:

```nix
  nixpkgs = {
    overlays = [
      (self: super: {
        pinentry = super.pinentry_gnome;
      })
    ];
  };
```

Unfortunately, this might cause a massive rebuild. (@fpletz worked on a reducing the rebuild needs but so far has not finished the effort.)

**Comment by dpc** [comment]
Oh. I wasn't aware of `mkForce`. I'll give it a shot.

**Comment by dpc** [comment]
Bot my PR and `services.gnome3.gnome-keyring.enable = pkgs.lib.mkForce false;` don't help.

**Comment by jtojnar** [comment]
Yep, the variable is introduced by the pam modules. I would try removing the `pam_gnome_keyring.so` references from [GDM module](https://github.com/NixOS/nixpkgs/blob/cac9f088103828f2c24c42d7e8ef3530d49b1eb4/nixos/modules/services/x11/display-managers/gdm.nix), and then adding 

```
security.pam.services.gdm.enableGnomeKeyring = true;
security.gdm-password.services.gdm.enableGnomeKeyring = true;
```

to the [gnome-keyring module](https://github.com/NixOS/nixpkgs/blob/cac9f088103828f2c24c42d7e8ef3530d49b1eb4/nixos/modules/services/desktops/gnome3/gnome-keyring.nix).

Then you could disable the PAM thing while other users could still rely on it.

Though in order for the PR to be merged, we would need it to be more generic (i.e. also work for lightdm and others).

Actually finding out how to make the smartcards work with GNOME Keyring might be easier.

**Comment by jtojnar** [comment]
Actually, as I [understand it](https://github.com/NixOS/nixpkgs/issues/38266#issuecomment-398976407) the first thing would not work at all. At least until PAM services of display managers are re-designed.

**Comment by tadfisher** [comment]
Here is what I have to do to disable Gnome's SSH_AUTH_SOCK behavior:

```nix
    # Prevent clobbering SSH_AUTH_SOCK
    home.sessionVariables.GSM_SKIP_SSH_AGENT_WORKAROUND = "1";

    # Disable gnome-keyring ssh-agent
    xdg.configFile."autostart/gnome-keyring-ssh.desktop".text = ''
      ${lib.fileContents "${pkgs.gnome3.gnome-keyring}/etc/xdg/autostart/gnome-keyring-ssh.desktop"}
      Hidden=true
    '';
```

Note this is in a home-manager config.

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/21860 has ben merged since so `security.pam.services.login.enableGnomeKeyring = lib.mkForce false;` or even `services.gnome3.gnome-keyring.enable  = lib.mkForce false;` should work for you.
