### ISSUE TITLE
on darwin, curl uses system root certs

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#42317]
## Issue description

nixpkgs's `curl` relies on `/etc/ssl/cert.pem` instead of using `NIX_SSL_CERT_FILE`.

Looks like `curl`'s configure script tries a bunch of locations, finds a file at `/etc/ssl/cert.pem` and then hardwires that in preference to whatever logic involving `NIX_SSL_CERT_FILE`. If I rebuild `curl` locally without letting it see `/etc/ssl/cert.pem`, the resulting binary behaves as expected.

I suspect OSX started actually shipping that file at some point and the behavior of our builds silently changed, but I don't really know how OSX works. https://curl.haxx.se/mail/lib-2017-11/0070.html suggests we should pass `--without-ca-bundle --without-ca-path` to the configure script..

### Steps to reproduce

```
$ env | grep SSL
NIX_SSL_CERT_FILE=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt

$ readlink $(which curl)
/nix/store/6s7vvjdsrw24mf16rm1mzcz4dycqpj9g-curl-7.60.0-bin/bin/curl

# this works:
$ curl -Ss https://google.com >/dev/null

# this shouldn't work, but does:
$ NIX_SSL_CERT_FILE=/dev/null curl -Ss https://google.com >/dev/null

$ sudo rm -f /etc/ssl/cert.pem

# this should work, but doesn't:
$ curl https://google.com
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none

# this works I guess:
$ SSL_CERT_FILE=$NIX_SSL_CERT_FILE curl -Ss https://google.com >/dev/null
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixpkgs-18.09pre142966.91ca88b3e6b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by strager** [comment]
This fixed `go get` for me. Thanks a lot @LnL7!

```
$ # Reproduce the curl issue by running 'go get' on ArneVogel/concat's sources.
$ nix-env -i go
$ git clone https://github.com/ArneVogel/concat.git
$ cd concat/
$ go get
# cd .; git clone https://github.com/abiosoft/semaphore <snip>/go/src/github.com/abiosoft/semaphore
Cloning into '<snip>/go/src/github.com/abiosoft/semaphore'...
fatal: unable to access 'https://github.com/abiosoft/semaphore/': error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
package github.com/abiosoft/semaphore: exit status 128
$ cd ..

$ # Install go with LnL7's patch.
$ git clone https://github.com/LnL7/nixpkgs.git
$ cd nixpkgs/
$ git checkout 288939ce22a8d63077e888db227289d9e36d41e5
$ nix-env -i -f ./default.nix go
$ cd ..

$ # Try 'go get' again. Observe that it succeeds (kinda...).
$ cd concat/
$ go get
go get: no install location for directory <snip>/concat outside GOPATH
	For more details see: 'go help gopath'
```

**Comment by LnL7** [comment]
Great! We got some sporadic reports from people with cacert issues and from some debugging I knew the variables where getting ignored, but I didn't realise why.
