### ISSUE TITLE
More sensible /run/keys behavior in NixOS

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#42344]
Currently NixOS has some special `boot.specialFileSystems` support for creating a RAM FS for `/run/keys`. Unfortunately even though it lives in NixOS and NixOS includes a special "keys" group that is supposed to have access to that folder, support for the feature is sort of neutered without NixOps, which then applies this logic:

https://github.com/NixOS/nixops/blob/884d6c3994b227eb09c307e5d25d6885c9af8220/nixops/backends/__init__.py#L267-L269

To actually make the folder usable to members of the "keys" group. It seems like that logic should live on the NixOS side for those of us who want a reasonable place in RAM to drop certain keys, but don't use NixOps.

cc @edolstra @rbvermaa since I don't really understand the NixOS/NixOps intricacies.

**Comment by flokli** [comment]
Wow, stumbled over that just now.

Currently `/run/keys` is owned by `root:root`:

```
drwxr-x---  2 root  root      0 Jan 19 17:03 keys
```

This currently breaks some assumptions in the NixOS module system when not deployed with NixOps (like when deploying with morph, or autoscaling VMs at cloud providers setting up secrets in `/run/keys`).

It'll also become more and more of a problem if we run less services as root, and assume users in the `keys` group have access to some secrets.

I assume we might want to fix permission of the folder by adding a `tmpfiles` rule into nixpkgs - turning 2 of the three lines in nixops into a no-op.

cc @johanot @aanderse @andir @arianvp @zimbatm

**Comment by arianvp** [comment]
Totally agree. :+1: to add a tmpfiles rule and remove that thing from nixops.

**Comment by flokli** [comment]
I'd still like to find out what makes `boot.specialFileSystems` special, and if we can remove things there without breaking anything ;-)

**Comment by arianvp** [comment]
IIRC `specialFileSystems` are the things that are mounted in the `initrd`. i.e. they're used to generate the `earlyMountScript` in `stage-1-init.sh`

`/proc,/dev/*,/sys`  and for some arbitrary reason also `/run/keys` which seems the odd one out ;) Perhaps there is some usecase of loading secrets in initrd?

**Comment by flokli** [comment]
Yes, enabling sshd in initrd, unlock the root volume by having nixops send over the keys.

**Comment by flokli** [comment]
So, I did some digging. While assembling stage 1 and 2 scripts, the `earlyMountScript` generated already contains the `"gid=${toString config.ids.gids.keys}"` parameter. 

However, it seems like the kernel only honors this option for `tmpfs`, not `ramfs`.

I opened https://github.com/NixOS/nixpkgs/pull/79248 which removes this and uses tmpfiles to do the chgrp when necessary.
