### ISSUE TITLE
dirOf should work with relative paths

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixpkgs#42340]
## Issue description

nix's built-in function `dirOf` only works for strings which are absolute paths, for some reason. This looks like a completely arbitrary (and quite unfortunate) restriction, and the documentation doesn't mention it.

The related function `baseNameOf` does work for all kinds of strings.

### Steps to reproduce

```
nix-instantiate --eval --expr 'dirOf "dir/abc.txt"'                                                        ~
error: string 'dir/abc.txt' doesn't represent an absolute path, at (string):1:1
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.49, NixOS, 18.03.132687.14c248a4ab7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(paul): `""`
 - channels(root): `"nixos-18.03.132687.14c248a4ab7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by joachifm** [comment]
I think this belongs over at https://github.com/NixOS/nix/issues, it might receive more attention from the right people there.

**Comment by pvgoran** [comment]
This makes sense.

There is no way to transfer the issue to another repository, right?

**Comment by joachifm** [comment]
Not that I'm aware of, at least not for ordinary repo members/contributors.
