### ISSUE TITLE
Expose function 'step' in build process for debugging

### ISSUE THREAD

**Issue by campadrenalin** [NixOS/nixpkgs#4234]
In the interactive derivation building process, we ought to provide a shell function called "step" or "build-step", which runs the next build phase and (on success only) iterates the internal step counter.

The important thing is that one should be able to _perfectly_ emulate an automated build, by running 'step' until the entire build is complete (at which point the function should only emit a "You're done" message of some sort). If this does not reliably behave like an automated build does, it's nearly useless for debugging builds.

**Comment by Profpatsch** [comment]
(triage) still a thing?

**Comment by Profpatsch** [comment]
Closing because no reply.
