### ISSUE TITLE
nixos.tests.plasma5 test is broken in master

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#42341]
[`nixos.tests.plasma5`](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.plasma5.x86_64-linux) is broken in `master` according to https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents. This issue blocks channel updates of `nixos-unstable`.

**Comment by worldofpeace** [comment]
@peti He he, here's why https://github.com/NixOS/nixpkgs/issues/42315 and here's the fix https://github.com/NixOS/nixpkgs/pull/42327

**Comment by vcunat** [comment]
Hydra agrees: https://hydra.nixos.org/build/76290326

**Comment by vcunat** [comment]
Channel bumped just now :tada:

**Comment by peti** [comment]
Oh? That was easy!

:grinning:

**Comment by worldofpeace** [comment]
:raised_hands:
