### ISSUE TITLE
Quassel fails to build with Qt 5.11

### ISSUE THREAD

**Issue by lopsided98** [NixOS/nixpkgs#42352]
## Issue description

Quassel fails to build with Qt 5.11. A fix has been [committed upstream](https://github.com/quassel/quassel/commit/92f4dca367c3a6f0536a1e0f3fbb44bb6ed4da62), but it has not been backported to the release branch, and even then quassel has very infrequent releases, so it will likely be a while before the fix is released.

We can either apply the patch in nixpkgs, or build with Qt 5.9 for now.

cc @phreedom @ttuegel

**Comment by averelld** [comment]
Unlikely that #42351 gets merged fast, but an upgrade to 5.11.1 would also fix this issue, because qt5_use_modules was reintroduced.

**Comment by orivej-nixos** [comment]
Fixed in #42351
