### ISSUE TITLE
MultiMC v0.6.2 fails to build with Qt 5.11

### ISSUE THREAD

**Issue by Pneumaticat** [NixOS/nixpkgs#42387]
## Issue description

Errors with: `Unknown CMake command "qt5_use_modules".`

This error has already been fixed in `develop` by https://github.com/MultiMC/MultiMC5/commit/4d68c1b509cd289e9f02cbf258e69f2539349029. (See also MultiMC/MultiMC5#2291.) MultiMC successfully builds if you set the version to develop:

```nix
  src = fetchFromGitHub {
    owner = "MultiMC";
    repo = "MultiMC5";
    rev = "19bb50b872da2702b8e0b65f3f7b6b54c1c5b071";
    sha256 = "01frkk2klm1axr7ywnj23ikxn5pkgj8q6w8vqbslsvmh8bni8rk0";
    fetchSubmodules = true;
  };
```

### Steps to reproduce

Attempt to build MultiMC.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.2, NixOS, 18.09.git.403c947 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by averelld** [comment]
Would also be fixed by #42351

**Comment by Chiiruno** [comment]
Probably best to just patch the release.
I'll see if I can do anything about this.

**Comment by Chiiruno** [comment]
Patching doesn't work, and calling the commit directly results in this.
```
Submodule 'libraries/quazip' (https://github.com/MultiMC/quazip.git) registered for path 'libraries/quazip'
error: key does not contain a section: .url
```
Not sure what to do, if someone does fix this, please include `ln -sf $out/bin/MultiMC $out/bin/multimc` in `postInstall` to fix the desktop file.

**Comment by Pneumaticat** [comment]
I managed to fix it by using the unstable `develop` version, but I'm not sure if that's the right approach. I can make a pull request with that if you'd like.

**Comment by Chiiruno** [comment]
It should be fine, just note that it's a temporary workaround until MultiMC increments a release, since IIRC stable packages aren't generally supposed to be using non-stable repos.
