### ISSUE TITLE
jdk9 doesn't build

### ISSUE THREAD

**Issue by mightybyte** [NixOS/nixpkgs#42435]
## Issue description

Running `nix-shell -p jdk9` gives me the following error:

```
In file included from libattr.c:25:
../include/attr/xattr.h:23:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [../include/buildrules:52: libattr.lo] Error 1
make[2]: Leaving directory '/private/tmp/nix-build-attr-2.4.47.drv-0/attr-2.4.47/libattr'
make[1]: *** [include/buildrules:35: libattr] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-attr-2.4.47.drv-0/attr-2.4.47'
make: *** [Makefile:47: default] Error 2
builder for '/nix/store/pn7csdfykbbic378kw0ppk40d90a88nf-attr-2.4.47.drv' failed with exit code 2
cannot build derivation '/nix/store/zm1301bi262z8a6hxzjykih0i3mgq6w3-acl-2.2.52.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8bmwaskism0kvsz0sp48rr8qf5qndr4c-gnome-vfs-2.24.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/w52d7gxbb6v3v1fkmb9ci6gig72qrq2d-openjdk-9.0.4-b11.drv': 1 dependencies couldn't be built
```

### Steps to reproduce

Install nix on macOS and run `nix-shell -p jdk9`.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(mightybyte): `"darwin, nixpkgs-18.09pre143761.4756e6ff3b8"`
 - channels(root): `"darwin, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by volth** [comment]
["Java SE 9 has reached end of support"](http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html) and perhaps should be removed from nixpkgs

**Comment by vcunat** [comment]
There is no `jdk9` in master or 4756e6ff3b8 already.  It was removed in https://github.com/NixOS/nixpkgs/pull/38097

I assume you are pulling it from some other old channel by accident.
