### ISSUE TITLE
libtoxcore-0.1.11 fails to build (dependency for toxvpn-2018-04-17)

### ISSUE THREAD

**Issue by toonn** [NixOS/nixpkgs#42431]
## Issue description

`toxvpn` won't build on mac OS because the dependency `libtoxcore` fails to build.

```
ld: unknown option: -z
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

[libtoxcore_error.txt](https://github.com/NixOS/nixpkgs/files/2129921/libtoxcore_error.txt)

### Steps to reproduce

`nix-env -iA nixpkgs.toxvpn` on a darwin platform.
I assume trying to install `nixpkgs.libtoxcore` would result in the same error.

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.5.0, macOS 10.13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixpkgs-18.09pre140156.0e6fb50954b"`
 - channels(toonn): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by xeji** [comment]
cc libtoxcore maintainer @peterhoeg

**Comment by peterhoeg** [comment]
Latest toxvpn on unstable builds fine.
