### ISSUE TITLE
virt-manager: can't detect default hypervisor nor setting one

### ISSUE THREAD

**Issue by bricewge** [NixOS/nixpkgs#42433]
`virt-manager` always start with a warning message:
> Could not detect a default hypervisor. Make sure the appropriate virtualization packages containing kvm, qemu, libvirt, etc. are installed and that libvirtd is running.

So each time I start it I need to manually add a connection which annoy me. To avoid that I would like that it either automatically find an hypervisor or specifying my default hypervisor somewhere; [both behavior](https://libvirt.org/uri.html#URI_default) that `virt-manger` should do on any distro but that's not the case for NixOS.

I tried the following without  any successful results:
- `export LIBVIRT_DEFAULT_URI="qemu:///system"`
- adding `LIBVIRT_DEFAULT_URI="qemu:///system"` environment to `libvirtd.service`
- adding the line `uri_default = "qemu:///system"` to: 
  - `/etc/libvirt/libvirt.conf`
  - `/var/lib/libvirt/libvirt.conf`
  - `/var/lib/libvirt/libvirtd.conf`
  -  `~/.config/libvirt/libvirt.conf`
  - `~/.config/libvirt/libvirtd.conf`

For sure I can start it like this `virt-manager --connect qemu:///system` but that's only a workaround.

**Comment by emmanuelrosa** [comment]
What's the procedure for reproducing this error?

**Comment by bricewge** [comment]
I think the minimal setup you need is:
```
virtualisation.libvirtd.enable = true;
environment.systemPackages = [ pkgs.virtmanager ]; 
```
And then just start `virt-manager`.

**Comment by volth** [comment]
Try to add ```gnome3.dconf``` to ```environment.systemPackages```

Some python programs (```virt-manager```, ```meld```, ...) are using ```dconf``` to store the settings and do not behave well without it

**Comment by volth** [comment]
If it helps, then a fix like https://github.com/NixOS/nixpkgs/pull/30271/files might be useful

**Comment by bricewge** [comment]
Thanks @volth! WIth `dconf`, `virt-manager` now remember the last connection and don't te warning message at startup.

**Comment by jtojnar** [comment]
`gnome3.dconf` is a system service that needs to be added to `services.dbus.packages` by your desktop environment. If you create your own environment, you will need to add it yourself (adding `programs.dconf.enable = true;` to `configuration.nix` should work). Nix does not contain a mechanism for representing a dependency on a service.
