### ISSUE TITLE
Mouse not configurable on plasma 5.13

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#42548]
## Issue description

1. Open ```systemsettings5```
2. Go to Input -> Hardware Devices -> Mouse
3. Error message: "The shared library was not found."

Presumably this has to do with the kde mouse functionality now needing libinput - from the plasma 5.13 announcement:

```
The Mouse System Settings page has been rewritten for libinput support on X and Wayland.
```

Cc: @bkchr who has done great work on KDE!

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.2, NixOS, 18.09.git.02ea3cd39d9M (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`

**Comment by bkchr** [comment]
I don't get any error while opening the mouse dialog.

I have: `services.xserver.libinput.enable = true;`. Does this maybe fixes the problem? If yes, we need to activate that automatically, if you enable plasma5.

**Comment by peterhoeg** [comment]
I already have ```services.xserver.libinput.enable = true;``` as well.

**Comment by bkchr** [comment]
Hmm okay. Maybe I need to attach a mouse to see the error ^^

**Comment by bkchr** [comment]
On my other PC, I also do not get this error...

**Comment by peterhoeg** [comment]
This is super odd. I get the error on 2 different machines. I'll try to reproduce this in a VM with minimal config. According to ```ldd```, ```systemsettings5``` doesn't reference ```libinput``` which I would assume that it does.

**Comment by bkchr** [comment]
`ldd /nix/store/mafzvjphwlby6qbvf725ncp2zp9iwkf8-plasma-desktop-5.13.0/lib/qt-5.11/plugins/kcm_mouse.so`
Systemsettings only load the kcm modules. For me, ldd on this file does not show any dependency on `libinput`. But that is strange, because based on [this](https://github.com/KDE/plasma-desktop/blob/master/kcms/mouse/backends/x11.cmake) cmake file, it should be added.

**Comment by bkchr** [comment]
I looked into the code and the following line is responsible for selecting `libinput` or `evdev`:
https://github.com/KDE/plasma-desktop/blob/6a4b5870fb2ff918df9e5b8f708e8039b394177e/kcms/mouse/backends/x11/x11_backend.cpp#L56

Could you post your configuration.nix? I must be missing something and thus the libinput backend is not selected.

**Comment by peterhoeg** [comment]
No, I haven't had time to try it out.

**Comment by bkchr** [comment]
Okay, I verified that my kcm mouse also loads the libinput backend. I don't understand why you get this error.

Could you execute `kcmshell5 mouse` and try to find out which library is missing?

**Comment by peterhoeg** [comment]
Now it works on one machine but still not on the other. THey have almost identical configuration. This is the error:

```
peter@mildred:~ $ kcmshell5 mouse
org.kde.kcoreaddons: Error loading plugin "kcm_input" "The shared library was not found."
Plugin search paths are ("/home/peter/.cache/npm-packages/lib/qt-5.11/plugins", "/home/peter/.local/lib/qt-5.11/plugins", "/home/peter/.cache/npm-packages/lib/qt-5.11/plugins", "/home/peter/.local/lib/qt-5.11/plugins", "/home/peter/lib/qt-5.11/plugins", "/run/wrappers/lib/qt-5.11/plugins", "/home/peter/.local/share/flatpak/exports/lib/qt-5.11/plugins", "/var/lib/flatpak/exports/lib/qt-5.11/plugins", "/home/peter/.nix-profile/lib/qt-5.11/plugins", "/nix/var/nix/profiles/default/lib/qt-5.11/plugins", "/run/current-system/sw/lib/qt-5.11/plugins", "/etc/profiles/per-user/peter/lib/qt-5.11/plugins", "/nix/store/ara5mkscd313n3nhxn5602lp68qghcaf-kde-cli-tools-5.13.0/bin")
The environment variable QT_PLUGIN_PATH might be not correctly set
Error loading KCM plugin "kcm_input" "The shared library was not found."
```

**Comment by bkchr** [comment]
Could you maybe do a `strace` so that we see which shared library is not found? Or maybe already `ldd` reveals which is missing.

**Comment by bkchr** [comment]
Could you upload the strace output for me?

**Comment by peterhoeg** [comment]
Files were too big for pastebin, so I dropped them here: http://cdn.speartail.com/store/mouse_M2JlYmE1Yzk3NzJh.zip

There's a strace from the working machine as well as the non-working machine.

Thanks - *much* appreciated!

**Comment by bkchr** [comment]
Hmm weird, what did you change between the working and the non-working machine?

The non-working tries to load `libkcm-input.so`, but the KCM was renamed to `libkcm-mouse.so`, before the 5.13 release...: https://github.com/KDE/plasma-desktop/commit/8f7a827f70174e50f21a0af60cb8b17b91948d31#diff-42f1c9ddf5f75cbbcbf4ea2b5c5e49b2

Your working machine loads the correct kcm, the `libkcm-mouse.so`. I don't know why that is happening, maybe some configuration file somewhere?

**Comment by peterhoeg** [comment]
That's what so weird - apart from some minor hardware changes, those machines are otherwise built using the same ```configuration.nix```. Maybe there is a stray config file somewhere that makes it load the wrong file?

**Comment by bkchr** [comment]
@peterhoeg could you paste the content of the following file?
`~/.config/kcmshell5rc` 

This file does not exist for me, but your kcm loads that successfully.

**Comment by peterhoeg** [comment]
I think that's just a red herring:

```
[PlasmaRunnerManager]
LaunchCounts=
```

**Comment by bkchr** [comment]
Do you have the file `/run/current-system/sw/share/kservices5/mouse.desktop`?

Or maybe `/run/current-system/sw/share/kservices5/input.desktop`?

**Comment by peterhoeg** [comment]
```mouse.desktop```, yes, ```input.desktop```, no.

Contents without the translation entries:

```
[Desktop Entry]
Exec=kcmshell5 mouse
Icon=preferences-desktop-mouse
Type=Service
X-KDE-ServiceTypes=KCModule,KCModuleInit
X-DocPath=kcontrol/mouse/index.html

X-KDE-Library=kcm_mouse
X-KDE-Init-Symbol=mouse
X-KDE-ParentApp=kcontrol
X-KDE-Init-Phase=0

X-KDE-System-Settings-Parent-Category=input-devices
X-KDE-Weight=60

Name=Mouse
Comment=Mouse Controls
X-KDE-Keywords=Mouse,Mouse acceleration,Mouse threshold,Mouse buttons,Selection,Cursor Shape,Input Devices,Button Mapping,Click,icons,feedback,Pointers,Drag,mapping,right handed,left handed,Pointer Device,Mouse Wheel,Mouse Emulation,Mouse Navigation,Mouse Drag and Drop,Mouse Scrolling,Mouse Sensitivity,Move Mouse with Num Pad,Mouse Num Pad Emulation
Categories=Qt;KDE;X-KDE-settings-hardware;
```

**Comment by bkchr** [comment]
Really weird :/ And you still have one machine where it works and one where it does not work?

**Comment by peterhoeg** [comment]
Yep.

**Comment by bkchr** [comment]
Are both machines on the same version of nixpkgs?

**Comment by peterhoeg** [comment]
Yes as well. Apart from a few mounts and of course the hardware differences (but nothing USB/input related), they are *exactly* the same. 

But finally something - if I use a different user on the broken machine, it's working. So there is some left-over cruft that is causing this to break. I'm going to have to do some digging...

**Comment by bkchr** [comment]
Yeah, would be nice to know what causes the problem!

**Comment by bkchr** [comment]
One more random idea, could you execute `kbuildsycoca5` and see if that changes something?

**Comment by peterhoeg** [comment]
*That* did it! You're an absolute star.
