### ISSUE TITLE
python3 "ImportError: No module named site"

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#42561]
## Issue description

```
python3 "ImportError: No module named site"
```

### Steps to reproduce
Replace `27` by `3` in the below code
```
#! /usr/bin/env nix-shell
#! nix-shell -i python27 -p "python27.withPackages(ps: with ps;[jinja2 docopt])"
print("")
```

## Additional information
There are many results for this error on Google for this issue in other distributions too. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.git.91b286c (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by FRidh** [comment]
No further feedback so closing.

**Comment by coretemp** [comment]
On a newer system, I also cannot reproduce it again (but I didn't use the exact same version of nixpkgs, so we cannot expect the exact same result). 

Thank you for also testing this.
