### ISSUE TITLE
Package request: Rasdaemon

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#42592]
## Issue description

`mcelog` is available in `nixpkgs`, but the utility has been deprecated in favor of `rasdaemon`. In particular, Rasdaemon has better support for AMD cards. No `rasdaemon` package currently exists in `nixpkgs`.

There is a Arch Linux PKGBUILD [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rasdaemon).

Unfortunately, performing a manual install did not go well for me:
```
sudo make install
Making install in libtrace
make[1]: Entering directory '/home/matt/Downloads/rasdaemon-0.6.0/libtrace'
  AR       libtrace.a
make[1]: *** [Makefile:399: libtrace.a] Error 1
make[1]: Leaving directory '/home/matt/Downloads/rasdaemon-0.6.0/libtrace'
make: *** [Makefile:677: install-recursive] Error 1
```

**Comment by evils** [comment]
not stale, not easy to fix with confidence though
