### ISSUE TITLE
Package Request: ocserv

### ISSUE THREAD

**Issue by tenten8401** [NixOS/nixpkgs#42594]
`ocserv` is the server side of the openconnect client we already have.

It's in the Ubuntu repos by default and there's an AUR entry for it: https://aur.archlinux.org/packages/ocserv/

I'd love to see this as it's an excellent alternative to OpenVPN.

**Comment by Ma27** [comment]
this package looks quite interesting, as I'd like to try it out as well, I'll file a patch for this in the next time %)

**Comment by Ma27** [comment]
ok, I managed to create a basic, working derivation. However I need to catch some sleep, tomorrow I'll try to fix the remaining compiler errors %)

**Comment by tenten8401** [comment]
That was quick, thanks for having a look at it!

If you need anyone to test I'd be up for it.

**Comment by Ma27** [comment]
ok, there's a working derivation now:

``` nix
{ stdenv, fetchFromGitLab, autoreconfHook, pkgconfig, nettle, gnutls
, libev, protobufc, guile, geoip, libseccomp, gperf, readline
}:

stdenv.mkDerivation rec {
  name = "name-${version}";
  version = "0.12.1";

  src = fetchFromGitLab {
    owner = "openconnect";
    repo = "ocserv";
    rev = "ocserv_${stdenv.lib.replaceStrings [ "." ] [ "_" ] version}";
    sha256 = "0jn91a50r3ryj1ph9fzxwy2va877b0b37ahargxzn7biccd8nh0y";
  };

  nativeBuildInputs = [ autoreconfHook pkgconfig ];
  buildInputs = [ nettle gnutls libev protobufc guile.dev geoip libseccomp gperf readline.dev ];

  meta = with stdenv.lib; {
    homepage = https://gitlab.com/openconnect/ocserv;
    license = licenses.gpl2;
    description = "This program is openconnect VPN server (ocserv), a server for the openconnect VPN client.";
    maintainers = with maintainers; [ ma27 ];
  };
}
```
it seems to work, but I'd like to sufficiently test itbefore filing a patch. In case you'd like to try it out as well, go ahead %)

**Comment by Ma27** [comment]
@tenten8401 yeah indeed, some additional work is required, just the package itself might not be too helpful.
I'll start writing simple module for this tonight (including a NixOS test), then I may file a patch :)
However it would be cool if you could have a look at the package first :)

**Comment by tenten8401** [comment]
I'll see if I can test the basic package when I get some free time.

**Comment by Ma27** [comment]
I was fairly busy last week and didn/t have sufficient time to test this. I fixed the derivation locally to properly deliver man pages (the current ones are empty). I started working on a simple module, I hope that I can finish today, then I'd file a PR %)
