### ISSUE TITLE
Z3 Python bindings should have a Python 3 variant

### ISSUE THREAD

**Issue by MostAwesomeDude** [NixOS/nixpkgs#42603]
Placeholder for @thoughtpolice, mostly. We chatted on IRC about how there isn't a `python3Packages.z3-solver` and how Z3 bindings should be arranged.

> It's possible things might not work out this cleanly; but IIRC, Python's Z3 bindings use a separate libz3_python.so that's linked to libz3.so, and the python FFI code basically just talks to the public API. I don't think it digs into anything very deep. So I think it should be possible to just build the bindings, once against python3Packages and once against python2

**Comment by MostAwesomeDude** [comment]
Tried and failed:

    z3-solver = callPackage ../applications/science/logic/z3 { };

It would appear that I need to find a way to incant `buildPythonPackage` on the Z3 tree in some way.

**Comment by FRidh** [comment]
Fixed with https://github.com/NixOS/nixpkgs/commit/b21994d4ac9c2c8d372bf011668401ee31972c0b

**Comment by thoughtpolice** [comment]
@FRidh You are amazing, thank you! I had no idea how to convert a 'non-python' thing to a python thing and I was desperately confused.
