### ISSUE TITLE
Nixos does not ensure bashInteractive is installed when the default shell isn't bash

### ISSUE THREAD

**Issue by bmuk** [NixOS/nixpkgs#4260]
This issue presents itself if your default shell isn't bash (in my case zsh), and you attempt to use nix-shell. Nix-shell only calls bash from the user's PATH, as is explained [here](https://github.com/NixOS/nix/issues/355), and bash is expected to have readline support. However, this is not the case if bash is not the default shell - nixos simply ensures pkgs.bash is installed, not necessarily pkgs.bashInteractive. This is a problem because without readline support nix-shell does not behave as expected (notably the prompt is garbled and arrow key functionality is missing). All of these issues were fixed by me including bashInteractive in environment.systemPackages. It would be nice if nixos defaulted to keeping bashInteractive, even if it isn't the user's default shell.

**Comment by gurgeh** [comment]
I use zsh and I get this (= garbled prompt and no readline) when running nix-shell too. I have not been able to fix it by installing bashInteractive. It is quite annoying.

**Comment by iyzsong** [comment]
I haven't look into the detail, but `nix-shell --command $SHELL` work pretty good,
for both bash and zsh.

**Comment by gurgeh** [comment]
@iyzsong Yes, thanks, this is what I use now. When I tried it the first time, I used --pure which worked poorly.

**Comment by Ptival** [comment]
I have an even worse experience with all this.

The docs suggest that I can make zsh my default user shell by using the path:

`/run/current-system/sw/bin/zsh`

But when I do so, it seems nix-shell tries to run zsh by default and fails:

`/run/user/1001/nix-shell.whatever/rc: line 1: zsh: command not found`

**Comment by knedlsepp** [comment]
Could this possibly be closed after #27493 is closed?

**Comment by domenkozar** [comment]
This is now fixed in Nix 1.12, while for 1.11 there is a PR open at https://github.com/NixOS/nix/pull/1483
