### ISSUE TITLE
Module request: distcc

### ISSUE THREAD

**Issue by lemmarathon** [NixOS/nixpkgs#42604]
## Issue description
https://github.com/distcc/distcc

Proposed options:
- services.distcc.enabled (bool: `false`)
- services.distcc.port (signed integer: `3632`)
- services.distcc.hosts (list of strings: `[ "127.0.0.1,cpp,lzo" "192.168.0.0/24,cpp,lzo" ]`)

**Comment by wamserma** [comment]
Can you elaborate a bit more? Are you thinking of running a `distccd`? Or do you want to enable distcc as a client by default? In the first case you can easily define a systemd-service in nix, but across untrusted networks, you should run `distcc` over ssh (which does not need a permanently running daemon).
For a client, you can easily set up `distcc` in a shell.nix. Also have a look at `distccStdenv` and `distccWrapper`.

**Comment by lovesegfault** [comment]
I'm working on this.
