### ISSUE TITLE
How to clone private repos at evaluation time?

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#42608]
This is a write-up of a question I had, I will answer it myself below.

Some articles (like [this one](https://www.mpscholten.de/nixos/2016/07/07/private-github-repositories-and-nixos.html)) describe how to use private source code repositories in nix, e.g. with `fetchgitPrivate`.

The problem with this approach is that you have to give the `nixbld*` nix-daemon unix users access to an SSH key with which they can clone the private repo.

This doesn't work well if you just want to use your local user credentials (e.g. `ssh-agent`) to provide access to the repo.

Is there a way to clone at evaluation time, so that the SSH-agent works nicely?

**Comment by nh2** [comment]
Yes, I found that `builtins.fetchGit` can do that at evaluation time; for example a file `test.nix`:

```
let
  pkgs = import <nixpkgs> {};

  my_private_repo_contents = (builtins.fetchGit {
    url = ssh://git@github.com/nh2/test-private;
    rev = "a6f338e0f9bedba33f74f605c298623ed19fb8e7";
  });
in
  pkgs.writeText "mytext" "${toString my_private_repo_contents}"
```

and I could build it with `nix-build test.nix`.

Here I write a very boring package/derivation that just writes the path to the checked out repo to a file. But you could also use it in a real package that has e.g. `src = my_private_repo_contents;`.

Note that for me, trying this the first time didn't work, it just hung forever. In `strace` I could see that it was hanging at a `git fetch` command into the `~/.cache/nix/git` directory. I solved this by just deleting this cache directory and running again.

**Comment by CMCDragonkai** [comment]
What's that cache directory doing, and does this ensure we are not storing secrets into world readable `/nix/store`?

**Comment by nh2** [comment]
> What's that cache directory doing

I believe this is used when you do e.g. `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/2c07921cff84dfb0b9e0f6c2d10ee2bfee6a85ac.tar.gz nix-build ...`, it uses that cache directory to place the unpacked `.tar.gz` nixpkgs tree in there.

> does this ensure we are not storing secrets into world readable `/nix/store`?

No, this approach assumes full trust in the local machine.

**Comment by robinp** [comment]
See also https://github.com/NixOS/nix/issues/2431, TLDR always add `ref="mybranch"`.
