### ISSUE TITLE
wrapCC should use buildPackages

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#42601]
## Issue description

Currently we don't have good support for cross compiling when we use wrapCC. We should ensure that buildPackages is always used correctly here.

/cc @Ericson2314

**Comment by Ericson2314** [comment]
Right now, compilers and binutils are wrapped with libraries from the *next* stage (`targetPackages`), and `stdenv`s take all their tools from the previous stage (`buildPackages`). For the moment I think it's easiest to continue with that. But a super early cross attempt of mine https://github.com/NixOS/nixpkgs/pull/21268 put the wrapper in the middle stage instead.

Once `libc` is not special I was thinking it would be a good time to revisit such things.
