### ISSUE TITLE
vault: add ui

### ISSUE THREAD

**Issue by bricewge** [NixOS/nixpkgs#42614]
Since version `0.10.0` `vault` has a web ui which need `yarn` [to be build](https://github.com/hashicorp/vault/tree/master/ui#building-vault-ui-into-a-vault-binary). It looks like the derivation need to use `yarn2nix` but I can't wrap my head around how to do this inside this derivation. I didn't found any examples on doing this either.

Any help or orientation on how to achieve this is welcome.
This issue seems similar to #41378: `træfik` is written in go and also need `yarn` to build it's web ui.

**Comment by arianvp** [comment]
I have a solution in that PR that works, but we decided not to merge it into nixpkgs  because the yarn dependencies would add too much 'bloat' to nixpkgs. 

I wonder how we should handle this in the future, as more and more projects seem to bundle a JS web-ui these days, and building those with a fixed set of npm packages in nixpkgs is basically impossible.  

Does the code in #49082 answer your question @bricewge  because in that case we can close this.

**Comment by bricewge** [comment]
I have read your issues and PRs about JS assets a week or so  ago. Thanks to you I know how to bundle such a package now.

However I'm quite saddened by the answers on both sides of the aisle. [Upstream don't want](https://github.com/hashicorp/vault/issues/5622#issuecomment-433464768) to vendor in the assets for `vault` despite the fact that the organization that manage it, HashiCorp, does it for a similar project: `counsul`. And here we can't merge your PR because it's too bloated... This situation frustrate me because it looks like we will never get the web-ui for those kind of packages in NixOS when upstream don't want to compromise.

Writing this comment just made me realize that we didn't ask upstream to make available the compiled assets archive for each release. Maybe it's the way to go since it won't bloat either of the git repo.

Anyway I don't think this issue should be closed because it's not resolved.

**Comment by zimbatm** [comment]
> Writing this comment just made me realize that we didn't ask upstream to make available the compiled assets archive for each release, as Mic92 asked. Maybe it's the way to go since it won't bloat either of the git repo.

That's the best option really.

Another option is to create your own nixpkgs overlay for that type of packages. We have a few overlays appearing already, like nixpkgs-wayland.

**Comment by yorickvP** [comment]
Our current solution is https://github.com/obfusk/nix-vault-with-ui, which uses the hashes from yarn.lock to build the UI in the nix sandbox.

**Comment by PsyanticY** [comment]
There is also the possibility to use vault-binary that includes the UI ( [package](https://github.com/NixOS/nixpkgs/pull/65166))

**Comment by arianvp** [comment]
Given that this is now packaged, can we close this?

**Comment by Zhen-hao** [comment]
@PsyanticY  thanks for the work!
How can I get `services.vault` to use this `vault-binary`?

**Comment by PsyanticY** [comment]
use `services.vault.package = pkgs.vault-bin;`
