### ISSUE TITLE
ghcWithPackages broken with ghcjs80

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#42617]
## Issue description

#42191 was supposed to with `ghcWithPackages` for `ghcjs-ng` (i.e. GHCJS 8.2 and 8.4). As mentioned in #42032 it doesn’t actually fix the problem but for `ghcjs-ng` it also doesn’t make things work. However, I just noticed that this change has broken `ghcWithPackages` for GHCJS 8.0.
At this point, I propose that it should just be reverted since it seems to bring no benefit.
cc @matthewbauer 

### Steps to reproduce

```
> nix-shell -p "haskell.packages.ghcjs80.ghcWithPackages (pkgs: [pkgs.dlist])"
these derivations will be built:
  /nix/store/96a7pnx4rkgmb9iyrjw7f763yb4jrc22-ghcjs-0.2.020170323-with-packages.drv
building '/nix/store/96a7pnx4rkgmb9iyrjw7f763yb4jrc22-ghcjs-0.2.020170323-with-packages.drv'...
/nix/store/l6bpw4lvx3dhyh0qi31y5gi35pk5phic-ghcjs-0.2.020170323/nix-support:
propagated-build-inputs: /nix/store/0wvag9mywfzm1a5w6pwm18ykk9mv0zcg-dlist-0.8.0.2/nix-support/propagated-build-inputs
ghcjs-pkg-0.2.1-8.0.2.bin: /nix/store/s8m0vjvxhfni5q71s5gfsynl7kx7f4ac-ghcjs-0.2.020170323-with-packages/libexec/package.conf.d: getDirectoryContents:openDirStream: does not exist (No such file or directory)
builder for '/nix/store/96a7pnx4rkgmb9iyrjw7f763yb4jrc22-ghcjs-0.2.020170323-with-packages.drv' failed with exit code 1
error: build of '/nix/store/96a7pnx4rkgmb9iyrjw7f763yb4jrc22-ghcjs-0.2.020170323-with-packages.drv' failed
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.2-1-ARCH, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(moritz): `""`
 - channels(root): `"nixpkgs-18.09pre143801.5ac6ab091a4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Ok thanks for reminding me. I think I will have a better fix soon. I think we just need to make ghcjs use $out/lib instead of $out/libexec.

**Comment by cocreature** [comment]
@matthewbauer Thanks for the fast fix! That’s of course even better than just reverting the change :)
