### ISSUE TITLE
atom-beta: broken build of 1.29.0-beta

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/nixpkgs#42618]
## Issue description

The lines

      patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
        $out/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-linux

seem to be the problem. They were added recently (#41811). 

cc @Gerschtli, as the author of the PR added those lines.

### Steps to reproduce

Try to build atom-1.29.1 on current master

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.0, NixOS, 18.09pre143771.a8c71037e04 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - channels(synthetica): `"nixos-18.03pre119110.2ddcdcce26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by szeck87** [comment]
@Synthetica9 is this related to this error?

```
cannot find section .dynamic
stat: No such file or directory
builder for '/nix/store/rkqr75ydv1xa6qpc1iv6xl0vwbnhdmih-atom-beta-1.29.0-beta0.drv' failed with exit code 1
error: build of '/nix/store/rkqr75ydv1xa6qpc1iv6xl0vwbnhdmih-atom-beta-1.29.0-beta0.drv' failed
```

**Comment by Synthetica9** [comment]
@szeck87 Yep, that's the exact error you get.

**Comment by szeck87** [comment]
I've had issues since https://github.com/NixOS/nixpkgs/commit/2ad8e9a9782f8b208b4dc666b7e773e951f8d5e7#diff-49264938cf2713cdb620655b02061cfe.

`/nix/store/sl9zydhs79kaf5vs2fas4ig571shcrx5-atom-beta-1.29.0-beta0/bin/.atom-beta-wrapped: line 130: /tmp/atom-build/Atom/atom: No such file or directory`

`/nix/store/sl9zydhs79kaf5vs2fas4ig571shcrx5-atom-beta-1.29.0-beta0/bin/.atom-beta-wrapped: line 130: /tmp/atom-build/Atom/atom: No such file or directory`

**Comment by Synthetica9** [comment]
@szeck87 Ah, I see why that is happening. In atom.sh, there are the following lines:

```
case $(basename $0) in
  atom-beta)
    CHANNEL=beta
    ;;
  atom-dev)
    CHANNEL=dev
    ;;
  *)
    CHANNEL=stable
    ;;
esac
```

These lines are normally fine, but since we use `wrapProgram`, we overwrite the name of the executable being called, so the channel defaults to `stabel`. This causes problems further down in the script. You should probably open a new issue for this tbh.
