### ISSUE TITLE
Can't install any package: unexpected $undefined error

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#42642]
## Issue description

I can't install any package from the `nixpkgs` repository anymore. The culprit seems to be the `citrix-receiver` package.

### Steps to reproduce

```
% git checkout b0181718cb5b3f4
% cd nixpkgs/
% nix-env -f . -i hello
error: syntax error, unexpected $undefined, expecting IND_STR or DOLLAR_CURLY or IND_STRING_CLOSE, at /home/smaret/Dev/nixpkgs/pkgs/applications/networking/remote/citrix-receiver/default.nix:212:34
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 3.16.0-5-amd64, Debian GNU/Linux, 8 (jessie)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.2`
 - nixpkgs: `/nix/store/x3amdcd8jcc1n0p0kf6w85f8hyyvsh51-ciment-channel/ciment-channel`

**Comment by dtzWill** [comment]
I'm surprised by this, but even so it seems likely to be fixed by updating your version of Nix!

Nixpkgs releases and current nix version on the corresponding channel:

| Nixpkgs release | Nix Version |
|---|---|
| 17.09 | 1.11.16 |
| 17.03 | 1.11.14 |
| 16.09 | 1.11.8 |
| 16.03 | 1.11.4 |

1.11.2 is truly ancient! :innocent:

Nix 2.0 has had a few growing pains but even moving to latest 1.11 would jump you ahead a few years of development!

**Comment by dtzWill** [comment]
Modified the "one-liner" used to produce the above table to check if that version of nix could evaluate `citrix_receiver` -- looks like 16.09 and earlier produce the error you report.

**Comment by dtzWill** [comment]
Nixpkgs has a "minimum version" but that's currently set to "1.11" apparently.

Not sure who to ping on this, so @NixOS/nix-core I suppose (sorry):
* Should this be `1.11.14` (which might not be the precise version needed)
* Should this be `2.0`?

Anyway sorry for the problems @smaret hopefully we'll get a)you in a working state soon and/or b)start producing a more reasonable error message when trying to use a much-too-old Nix on recent Nixpkgs.

**Comment by matthewbauer** [comment]
Yeah we should stick to 1.11 compatibility until the nix installer finally supports upgrades.

**Comment by smaret** [comment]
Thanks for your answers. This explains why I don't get this error on Mac, which has nix `2.0`. The nix version on the Linux cluster is indeed fairly old. I'll ask the sys admin if it can be upgraded.

**Comment by smaret** [comment]
Upgrading to '2.0' solved the problem, so I'm closing this.
