### ISSUE TITLE
flask-restful tests fail broken with aniso8601 >3.0

### ISSUE THREAD

**Issue by xvapx** [NixOS/nixpkgs#42641]
## Issue description
Commit https://github.com/NixOS/nixpkgs/commit/142db78f08161a0f383d91b54c657f00ec16fe50 updated aniso from 3.0.0 to 3.0.2. 
flask-restful 0.3.6 has a broken test when using [aniso > 3.0.0](https://github.com/flask-restful/flask-restful/commit/54979f0a49b2217babc53c5b65b5df10b6de8e05).

### Steps to reproduce
Build flask-restful after commit https://github.com/NixOS/nixpkgs/commit/142db78f08161a0f383d91b54c657f00ec16fe50.
test ```tests.test_inputs.test_bad_isointervals``` fails.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.51, NixOS, 18.03.132768.94d80eb7247 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `""`
 - nixpkgs: `/nix/store/gsqxmqmpbq40d62z0fnbyih00lgzx0ac-nixexprs.tar.xz`

**Comment by xvapx** [comment]
cc @FRidh

**Comment by xvapx** [comment]
Disabling the failing check with:
```
preCheck=''
  sed -i "409i @unittest.skip(\"broken with aniso > 3.0.0\")" tests/test_inputs.py
  '';
```
works, but this depends on injecting ```@unittest.skip("broken with aniso > 3.0.0")``` exactly on the line above the test declaration, and will fail in the future if line number changes.

Alternatively, we can remove the entire ```tests/test_inputs.py``` file or update flask-restful to use a version with commit https://github.com/flask-restful/flask-restful/commit/54979f0a49b2217babc53c5b65b5df10b6de8e05, which fixes this bug (no version with this commit is avaliable on pypy).

**Comment by FRidh** [comment]
Use substituteInPlace to rename the test, removing test from the name. That way it won't be recognized as a test.

**Comment by xvapx** [comment]
Lol, perfect, i had no idea. I'm testing with nix-review, will PR soon.
