### ISSUE TITLE
Atom builds broken in CI environment

### ISSUE THREAD

**Issue by szeck87** [NixOS/nixpkgs#42730]
## Issue description
We've had issues with building atom-beautify since https://github.com/NixOS/nixpkgs/commit/2ad8e9a9782f8b208b4dc666b7e773e951f8d5e7.  This happens now in both Atom and Atom Beta channels.

Error for Atom:  `/nix/store/sl9zydhs79kaf5vs2fas4ig571shcrx5-atom-beta-1.29.0-beta0/bin/.atom-beta-wrapped: line 130: /tmp/atom-build/Atom/atom: No such file or directory`

Error for Atom Beta:  `/nix/store/y2pi0nfg6rdda9w92pnh1c8nc1jf9vik-atom-1.28.0/share/atom/atom: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

### Steps to reproduce
1. Clone https://github.com/Glavin001/atom-beautify
2. Setup Travis CI for your fork
3. Run Travis CI

or

1. Run a Docker image for nix
2. Clone and checkout master from https://github.com/Glavin001/atom-beautify
3. Install atom and atom-beta
4. Run `sh build-package.sh`

Last successful beta/stable build:  https://travis-ci.org/Glavin001/atom-beautify/builds/382822648
Last successful stable build:  https://travis-ci.org/Glavin001/atom-beautify/builds/393885921
Both failed:  https://travis-ci.org/Glavin001/atom-beautify/builds/394802214

**Comment by szeck87** [comment]
@Synthetica9 here is a new issue.  https://github.com/NixOS/nixpkgs/issues/42618#issuecomment-401056612

**Comment by Synthetica9** [comment]
Seems to be related to #27241

**Comment by szeck87** [comment]
For stable maybe, beta is slightly different error.

**Comment by szeck87** [comment]
https://github.com/NixOS/nixpkgs/pull/42769
