### ISSUE TITLE
Need help packaging ppxlib

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#42738]
Hey everyone involved with OCaml packaging.

I am trying to build a project that needs a ppx_driver version >= 0.10.1 because of some bug in 0.10.0.
I noticed that there is even a 0.11.0 version available, and have tried jumping to it, but the building phase failed saying that it cannot find ppxlib:

```
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/0aa1ngxygf1iqanfbpdb10klc7r343c0-bash-4.4-p19/bin/bash
jbuilder build @install
File "src/jbuild", line 4, characters 14-20:
Error: Library "ppxlib" not found.
Hint: try: jbuilder external-lib-deps --missing @install
```

I'm not very familiar with the OCaml ecosystem, but I tried and package `ppxlib`, like so:

```
{ stdenv, fetchFromGitHub, ocaml, findlib, ocamlbuild, jbuilder, result, ocaml-migrate-parsetree }:

if !stdenv.lib.versionAtLeast ocaml.version "4.04"
then throw "ppxlib is not available for OCaml ${ocaml.version}"
else

stdenv.mkDerivation rec {
  name = "ocaml${ocaml.version}-ppxlib-${version}";
  version = "0.3.0";

  src = fetchFromGitHub {
    owner = "ocaml-ppx";
    repo = "ppxlib";
    rev = version;
    sha256 = "1c7kvca67qpyr4hiy492yik5x31lmkhyhy5wpl0l0fbx7fr7l624";
  };

  buildInputs = [ ocaml findlib ocamlbuild jbuilder ];
  propagatedBuildInputs = [ ocaml-migrate-parsetree result ];

  installPhase = ''
    for p in *.install
    do
      ${jbuilder.installPhase} $p
    done
  '';

  meta = with stdenv.lib; {
    homepage = https://github.com/ocaml-ppx/ppxlib;
    description = "Base library and tools for ppx rewriters";
    license = licenses.mit;
    maintainers = [  ];
  };
}
```

(not sure about that 4.04 bound on OCaml, but I was being slightly conservative)

Anyway, while this derivation builds to success, derivations that I make depend on still fail with the same error about the library ppxlib not being found.

Is there an ongoing effort to update those libraries? If anyone has input on this, it'd be much appreciated!

**Comment by Ptival** [comment]
Paging @vbgl and @Zimmi48 who have been helpful in the past! :-)

**Comment by Zimmi48** [comment]
@Ptival I'm afraid I'm not knowledgeable enough of the OCaml ecosystem to be able to help, but could you share a link to a branch so that I can try to hack around it?

**Comment by vbgl** [comment]
The hash in the `src` attribute is wrong: you build a different library (`ppx_tools_versioned`).

To build `ppxlib`, it seems that updating the JaneStreet libraries first to version 0.11.0 is required.

**Comment by Zimmi48** [comment]
Ah! Ah! Be careful indeed that Nix will trust the hash you give and if it has already downloaded it, it will not download it again, so when you copy a hash from somewhere else, do not forget to change at least one character.

**Comment by Ptival** [comment]
@Zimmi48 ah indeed, I did not know this and was doing it wrong! I'm making a little progress now, I'll share a fork when I am stuck next.

**Comment by Zimmi48** [comment]
Note the following trick: use `nix-prefetch-url --unpack https://...` to download the file, store it in the Nix store, and get its hash. Then you can copy-paste it and you won't have to download it again.

**Comment by vbgl** [comment]
I’ve started the update of janestreet libraries. See that commit:

https://github.com/vbgl/nixpkgs/commit/37846680797ee1a8a8e354ebedb44f1008669df3

This is not ready for a PR yet.

**Comment by vbgl** [comment]
PR #43084 includes `ppxlib`.

**Comment by aanderse** [comment]
@Ptival looks like this has been packaged so please close the issue.
