### ISSUE TITLE
Networking broken on EC2 t2 instances

### ISSUE THREAD

**Issue by talyz** [NixOS/nixpkgs#42755]
## Issue description
Network access works well on a new instance booted from the stable AMIs listed on the website, but after running `nixos-rebuild --upgrade switch` and rebooting the instance, it is broken. More specifically, the host can no longer send packets with an MSS larger than 3836.

### Steps to reproduce
1. Create two EC2 instances from one of the 18.03 AMIs in the same VPC
2. Upgrade one of them latest stable with `nixos-rebuild --upgrade switch` and reboot
3. Configure the security group to allow internal VPC communication
4. Run `nix run nixpkgs.iperf -c iperf3 -s` on the host without the updates and `nix run nixpkgs.iperf -c iperf3 -c <ip of other host>` on the updated one

### Fix

As I was writing this, I dug a bit deeper and found out that this is a bug introduced in the 4.14.37 release of the kernel. It is fixed in master (commit 45c8184c1bed1ca8a7f02918552063a00b909bf5 and possibly cb257783c2927b73614b20f915a91ff78aa6f3e8.) Applying those patches to the 4.14.51 kernel in stable fixes this issue for me.

**Comment by adisbladis** [comment]
Fix is now backported to 18.03.
