### ISSUE TITLE
libcurl wrong config flags when cross compiling

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nixpkgs#42778]
This should be `--with-random=/dev/urandom`.

https://github.com/NixOS/nixpkgs/blob/8e78a9a68fea58147541444e9cd57d7043be3ee7/pkgs/tools/networking/curl/default.nix#L99

A similar issue happens for `curl` 7.59.

**Comment by dtzWill** [comment]
Ha! Yes! Currently this happens:

```
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /dev/urandom
```

Will submit a PR for this shortly, thanks!
