### ISSUE TITLE
How to run 32 bit programs on NixOS

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#42804]
Install `steam-run` or `steam-run-native` and run `steam-run ./whatever`.
For future inquiries.

**Comment by vcunat** [comment]
Well, that's more about requiring dependencies on FHS paths (like `/usr/lib/`) than about being 32-bit.

**Comment by Chiiruno** [comment]
Yes, but AFAIK `steam-run` is the only package that provides a fairly complete FHS for 32-bit programs.
I made this "issue" for someone who might be trying out NixOS and needs to be able to run some 32-bit custom program that they have not compiled without a lot of nix magic.

**Comment by Chiiruno** [comment]
It may be a good future project to introduce a package that takes everything you have installed, and gets the 32-bit versions which you can just nix-shell into.

**Comment by vcunat** [comment]
On many places you can switch via the `pkgsi686Linux` attribute or `--argstr system i686-linux`.

**Comment by hugbubby** [comment]
Why in god's name is this necessary
