### ISSUE TITLE
paraview-5.4.1 OpenGL version problem

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#42812]
## Issue description

```
ERROR: In /build/source/VTK/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 831
vtkXOpenGLRenderWindow (0x295a0f0): GL version 2.1 with the gpu_shader4 extension is not supported by your graphics driver but is required for the new OpenGL rendering backend. Please update your OpenGL driver. If you are using Mesa please make sure you have version 10.6.5 or later and make sure your driver in Mesa supports OpenGL 3.2.

ERROR: In /build/source/VTK/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 816
vtkXOpenGLRenderWindow (0x295a0f0): failed to create offscreen window

ERROR: In /build/source/VTK/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 819
vtkXOpenGLRenderWindow (0x295a0f0): GLEW could not be initialized.
```

### Steps to reproduce

Start paraview.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.14, NixOS, 18.09pre142796.4b649a99d84 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre142796.4b649a99d84"`
 - channels(turion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I'm running xmonad, if that matters at all.

**Comment by CrazedProgrammer** [comment]
I'm having the same issue on `nixos-18.09pre149415.8395f9aa85e` (latest channel as of a day ago). When running `glxinfo` it shows that it only supports OpenGL version 2.1, which is strange and might explain why programs won't launch:
```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.26.0, 4.18.1, LLVM 6.0.1)
OpenGL version string: 2.1 Mesa 18.1.5
OpenGL shading language version string: 1.40
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

This issue did not occur on `nixos-18.09pre147850.2428f5dda13` (a few weeks old).

**Comment by bcdarwin** [comment]
Closing as `paraview` appears to work fine now e.g. on NixOS 22.11.
