### ISSUE TITLE
Upgrade to Ceph 13

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#42830]
Ceph 13.2.0 stable has been released, would be cool to have it in nixpkgs soon.

I have it working locally with two caveats:

* Had to disable the new dashboard (`"-DWITH_MGR_DASHBOARD_FRONTEND=OFF"`)
* Had to disable `spdk` (`"-DWITH_SPDK=OFF"`)

I don't have time to PR my changes right now, and I had also made some modifications on top of Ceph 12 before which makes it slightly more effort, but I just wanted to already put out here that I have the build working and tested.

So please, ping me if you want to work on this so that you don't need to re-do work I've already done.

CC @lejonet @krav because you have made PRs for Ceph in the past and may be interested.

**Comment by krav** [comment]
I'm happy to pick up on this. Getting to 13 is a goal for august, but if most of the work is done that might advance things. Is your branch available online somewhere?

**Comment by nh2** [comment]
I have put my branch up on https://github.com/nh2/nixpkgs/commit/93a042d89e55d7fa9f8b0faa38a72bb5347de66f (for now just put all my current state into that commit).

I would appreciate an analysis of whether there are things current nixpkgs master has that I don't have yet.

**Comment by krav** [comment]
I made some progress on this. Took your patches onto the existing package, couldn't figure out how do debug yours with `nix-shell` on account of the python wrapping. More features are enabled, SPDK and the dashboard are building.

Remaining work:
* The dashboard is enablable but doesn't seem to start.
* The build process downloads all manner of things (including a copy of node) and breaks the sandbox. Reproducibility.

https://github.com/krav/nixpkgs/commit/8e37828d031d55075fdb5e062a8ac846ff7bc5cf

**Comment by aij** [comment]
@krav Are you still working on it? I might have a little time to poke at it this weekend.

**Comment by krav** [comment]
@aij Yes, I have everything reproducible in the sandbox except the dashboard. Currently trying to figure the whole node ecosystem out, would appreciate input on that. I'll clean up what I have and push it later today.

**Comment by krav** [comment]
@aij https://github.com/krav/nixpkgs/commit/8a70effffe0c2bbdd8721b4d8b725782a183e13c 

This should build, lots of node cruft left commented out. Thinking it should be possible to package the dashboard separately.

**Comment by aij** [comment]
Sorry, I ended up spending the whole weekend with family...

From what I can tell `node2nix` seems to be the way to go. I see you found it already. :smile: I was about to suggest using `package-lock.json` to get the exact versions upstream is using, but it seems they didn't include it until   
https://github.com/ceph/ceph/commit/7299ee3555d4101bb9848636706224405a054e99 (only on master currently). Hopefully `package.json` still resolves to usable versions...

**Comment by krav** [comment]
@aij Yeah, I somehow can't seem to point `node2nix` at a subdirectory of the repo. Is there a way to wrap it so there's just that directory is extracted?

**Comment by nh2** [comment]
Probably also relevant: Ceph `master` added an option

```
option(WITH_SYSTEM_NPM "Assume that dashboard build tools already installed through packages" OFF)
```

for the purpose of building the dashboard on FreeBSD, where npm Internet access isn't allowed during the build, like for us.

https://github.com/ceph/ceph/pull/22562/files

I've also taken a quick look at current Gentoo and Arch, both disable the dashboard for this reason.

**Comment by krav** [comment]
Good. I'll try to submit a PR for what I've got with the dashboard disabled, then we can revisit it when this makes it into a release.

**Comment by srhb** [comment]
Superceded by #65470

**Comment by nh2** [comment]
Update to https://github.com/NixOS/nixpkgs/issues/42830#issuecomment-435684031

> I've also taken a quick look at current Gentoo and Arch, both disable the dashboard for this reason.

Arch now has the dashboard enabled:

https://github.com/archlinux/svntogit-community/blob/7d175f33f27b21e2ecc17877bbf21822d8f621de/trunk/PKGBUILD#L185

but interestingly it [uses `-DWITH_SYSTEM_NPM=OFF`](https://github.com/archlinux/svntogit-community/blob/7d175f33f27b21e2ecc17877bbf21822d8f621de/trunk/PKGBUILD#L196).
