### ISSUE TITLE
csvkit doesn't build for python2

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#42867]
## Issue description

csvkit doesn't build for python2 - maybe it requires python3 now?  Should be marked if so. (EDIT: according to [this](https://github.com/wireservice/csvkit/blob/781f34f8debdde0c064080cffce9c2a63e50c97f/docs/tricks.rst#installation) 2.7 should work)

### Steps to reproduce

`nix-shell -p python2Packages.csvkit`
https://paste.pound-python.org/show/XOjrUoDgUFIuR0krSveO

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.09pre140958.696c6bed4e8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(ole): `"nixos-18.09pre144878.687f5d2fa17"`
 - channels(root): `"nixos-18.09pre140958.696c6bed4e8, oldnixos-16.09.1943.25f4906da6, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
I've opened https://github.com/wireservice/agate/pull/716.
