### ISSUE TITLE
Plank: Failed to get running applications

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#42873]
## Issue description

I installed plank from unstable into a 18.03 system. It fails to get running applications.

```
[davidak@nixos:~]$ plank 

(plank:18322): Gtk-WARNING **: 15:37:12.758: Locale not supported by C library.
	Using the fallback 'C' locale.
[WARN 15:37:12.814197] [Environment:161] XDG_SESSION_CLASS not set in this environment!
[WARN 15:37:12.860595] [Preferences:192] '/run/current-system/sw/share/themes/Greybird/plank/dock.theme' is read-only!
[WARN 15:37:12.892718] Failed to get running applications: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.ayatana.bamf was not provided by any .service files
[WARN 15:37:12.898993] (Services/Matcher.c:296):plank_matcher_active_launchers: runtime check failed: (_tmp3_ != NULL)
[WARN 15:37:12.924205] Failed to register favorites: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.ayatana.bamf was not provided by any .service files
[WARN 15:37:12.994058] Creating surface took WAY TOO LONG (51ms), enabled downscaling for this cache!
```

On a different machine, also 18.03, i installed it using `nix-env -i plank -f my-fork/` where i packaged it. There i don't have this problem.

Is there anything wrong with the method described below?

https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F

### Steps to reproduce

1. add unstable channel using `nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable`

2. include this into your `configuration.nix`
```
{ config, pkgs, ... }:

let
  unstable = import <nixos-unstable> {};
in
{
  environment.systemPackages = with pkgs; [
    unstable.plank
  ];
}
```
3. `nixos-rebuild switch --upgrade`
4. `[davidak@nixos:~]$ plank `

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.52, NixOS, 18.03.132803.2f06e04b74e (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132803.2f06e04b74e, nixos-hardware, nixos-unstable-18.09pre143771.a8c71037e04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by worldofpeace** [comment]
I think this is related to #38991

**Comment by worldofpeace** [comment]
@davidak This needs `bamf` in  `services.dbus.packages` postulated by @jtojnar 
If you could test that for me It would help me in mutually packaging elementary.

**Comment by worldofpeace** [comment]
So I've packaged gala and when it's running plank will start yet it still cannot get the current running applications. But I haven't tested it with what was postulated.

**Comment by jtojnar** [comment]
I am looking into this. One problem is incorrectly `sed`ed location of units, though fixing it does not seem to be enough either. I also opened an upstream issue about the hardcoded path https://bugs.launchpad.net/bamf/+bug/1780557

**Comment by worldofpeace** [comment]
So i added bamf and with gala running plank just works.

**Comment by worldofpeace** [comment]
![screenshot](https://user-images.githubusercontent.com/28888242/42412930-6c1cd49a-8205-11e8-9dbb-f1f0bea4b624.png)

**Comment by jtojnar** [comment]
How did you add bamf? I can run it manually and have plank work, but for some reason systemd does not see my user service even with the fixed package: https://github.com/jtojnar/nixpkgs/tree/bamf

**Comment by worldofpeace** [comment]
I added it the way you said and I rebooted.

**Comment by jtojnar** [comment]
Hmm, perhaps the restart is needed. I can run it fine in VM. Feel free to cherry-pick the commits to your branch.

**Comment by davidak** [comment]
I reproduced the issue on 18.09pre145524.2a8a5533d18 (Jellyfish).

It is fixed with the changes from @jtojnar and `services.bamf.enable = true;`.

Thank you very much!

(Would it be possible to enable it by default when plank is installed?)
