### ISSUE TITLE
On Mac allowUnfree doesn't work

### ISSUE THREAD

**Issue by mlieberman85** [NixOS/nixpkgs#42900]
## Issue description
Tried to install vscode via `nix-shell -p vscode` after putting `nixpkgs.config.allowUnfree = true;` in `~/.config/nixpkgs/config.nix` on mac and it still gives me an error.

### Steps to reproduce

```
nix-shell -p vscode
error: Package ‘vscode-1.24.0’ in /nix/store/gjlj6v7q9kwjp03gplv3f5v12dkfaznf-nixpkgs-18.09pre144939.14a9ca27e69/nixpkgs/pkgs/applications/editors/vscode/default.nix:88 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.
```

```cat ~/.config/nixpkgs/config.nix
{ nixpkgs.config.allowUnfree = true; }
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(michaellieberman): `""`
 - channels(root): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by anoother** [comment]
Why was this closed? It still seems to be an issue...
