### ISSUE TITLE
Package Request: termtosvg

### ISSUE THREAD

**Issue by Jumblemuddle** [NixOS/nixpkgs#42921]
I'm not sure how python packages are packaged nowadays.
I ran across a useful Python tool that I think would be worthwhile to package.
https://github.com/nbedos/termtosvg

**Comment by dotlambda** [comment]
Have a look at https://nixos.org/nixpkgs/manual/#developing-with-python and https://nixos.org/nixpkgs/manual/#building-packages-and-applications.

**Comment by Ma27** [comment]
@Jumblemuddle I'd volunteer to package this and I'd notify you in the PR, but python packaging wiht Nix isn't too hard, the core maintainers did a fairly good job to provide an API which works fine with `setup.py` to build modules from source.
