### ISSUE TITLE
Feature request: allow for binary caches that are not guaranteed to be available

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#42964]
I have a laptop and a desktop both running Nixos. To save downloads and building, I have the desktop configured to use `services.nix-serve`, and the laptop configured with the desktop's as a binary cache. This is only a local host name on my home network, since my desktop isn't globally available (and if I'm going to download something over the global internet, it might as well be from cache.nixos.org).

For the most part this works great; I make a point of running updates on the laptop when I'm at home, after updating the desktop.

The major pain point is when I need to update dev environments or use ad-hoc nix shells on the laptop while I'm away from home. Being unable to connect to my desktop's local hostname completely blocks realising nix store paths; it doesn't consider other binary caches or local building as a fallback. I have to either manually add `--option binary-caches https://cache.nixos.org/` to every nix command where I'm away from home, or list my desktop only in `nix.trustedBinaryCaches` and add `--option binary-caches https://my.desktop.machine` to every nix command when I am at home. 

One thing that would address this problem would be a way to disable a specific binary cache for each command without overriding the whole list of them, or a single flag to rest to the default list (so I don't have to remember the exact spelling of the binary cache names; the slash on the end of `https://cache.nixos.org/` gets me every time, for example).

But much better would be a way to mark a binary cache as *optional* in the nixos configuration (or another list of binary caches in between `nix.binaryCaches` and `nix.trustedBinaryCaches`). Such caches should be used by default if available, but unavailability should not be treated as an error.

Then I could have all of my nix machines running `services.nix-serve` and all listing each other as optional caches, and whichever ones happen to be powered on, reachable, and have the packages I'm installing would transparently speed up my installations on other machines, but I wouldn't have to manage the process at all.

**Comment by 7c6f434c** [comment]
At some point I used a following trick (which is also annoying to manage but oh well): I did SSH with port forwarding between the machines and listed the forwarded port on localhost as the binary cache; this way if there is no SSH it is at least a clear «binary cache down» outcome which  turned out simpler to handle.

**Comment by edolstra** [comment]
This is more of a Nix rather than Nixpkgs issue. See https://github.com/NixOS/nix/issues/1990.

**Comment by edolstra** [comment]
Yeah, the linked issue is sufficient.
