### ISSUE TITLE
register gitlab runner automatically if not registered

### ISSUE THREAD

**Issue by srghma** [NixOS/nixpkgs#43013]
## Issue description
having nixops config

```
let
  region  = "us-east-1";
  zone    = "${region}c";
in

with (import ./lib/keys.nix);

{
  network.description = "[Project nixops] network";
  network.enableRollback = true;

  # Provision an EC2 key pair.
  resources.ec2KeyPairs.backendKeyPair = {
    inherit region zone;
  };

  resources.ec2SecurityGroups.backendSecurityGroup = {
    inherit region zone;

    description = "[Project nixops] ssh security group";
    rules = [ {
      fromPort = 22;
      toPort   = 22;
      sourceIp = "0.0.0.0/0";
    } ];
  };

  stage =
    { resources, ... }@args:
    {
      deployment.targetEnv = "ec2";

      deployment.ec2 = {
        inherit region zone;

        instanceType             = "t2.large";
        keyPair                  = resources.ec2KeyPairs.backendKeyPair;
        associatePublicIpAddress = true;
        ebsInitialRootDiskSize   = 50;
        # spotInstancePrice        = 50;
        tags.Name                = "[Project nixops] tests runner";

        securityGroups = [
          resources.ec2SecurityGroups.backendSecurityGroup
        ];
      };

      virtualisation.docker.enable = true;

      services.gitlab-runner = {
        enable = true;
        configOptions = {
          concurrent = 2;
          runners = [{
            name = "project-nixops-spot-instance-gitlab-runner";
            url = "....";
            token = "....";
            executor = "docker";
            builds_dir = "";
            docker = {
              host = "";
              image = "ruby:2.4.2";
              privileged = true;
              disable_cache = true;
              cache_dir = "";
            };
          }];
        };
      };

      networking.firewall.enable = false;
      networking.firewall.allowPing = true;
      networking.firewall.allowedTCPPorts = [
        22 # ssh, required
      ];

      swapDevices =
        [ { device = "/var/swapfile"; size = 12 * 1024; }
        ];

      users.extraUsers.root.openssh.authorizedKeys.keys  = devKeys;
    };
}
```

does not registers gitlab runner automatically on instance setup, I had to login to instance and register myself running `gitlab-runner register`

Expected: registers using config automatically

possible implementation https://gitlab.com/nekroze/nixos-gitlab-runner/blob/master/default.nix#L52

**Comment by bachp** [comment]
There are some points that need to be clarified here:

1. Should we also automatically unregistered?
2. What happens if the unregistered get's lost for some reason? Will it register a new runner with the same name anyway?
3. Where to store the registration key?

It might be an option to use the Gitlab API [to register and unregister](https://docs.gitlab.com/runner/register/) runners.

**Comment by srghma** [comment]
> 1. Should we also automatically unregistered?

that's the point, if user changes configuration and runner is no longer in configuration - it should be unregistered from gitlab

> 2. What happens if the unregistered get's lost for some reason? Will it register a new runner with the same name anyway?

I think yes

> 3. Where to store the registration key?

one can use nixops keys module and store keys in /run/keys/FILE


P.S. I've tried https://gitlab.com/nekroze/nixos-gitlab-runner and it does exactly what I want, but needs better tests
Also missing features:
- support renaming - if user changes name of runner in configuration - runner should be updated on gitlab too

**Comment by bachp** [comment]
@srghma Did you do any further work in this direction?

**Comment by srghma** [comment]
@bachp sorry but no

**Comment by srghma** [comment]
Related https://gitlab.com/arianvp/nixos-gitlab-runner

**Comment by srghma** [comment]
I have forked https://gitlab.com/arianvp/nixos-gitlab-runner 

https://gitlab.com/srghma/nixos-gitlab-runner/commit/aa15bb1b670d1643652514233ddd6364a9f23ace

it works perfectly, can register gitlab-runner on first systemd job run, can't unregister, but this is trivially to do (I wrote in comments)

____

we can introduce this to nixpkgs and it would resolve the issue

**Comment by bachp** [comment]
@srghma Why not open a PR that adds the functionallity to nixpkgs? I think too that this would be nice to have in nixpkgs.

**Comment by srghma** [comment]
not sure, it will break current API. 

Will close this issue since it's resolved for me

**Comment by schneefux** [comment]
I'm interested in this too. Since there is no solution in nixpkgs yet, can you reopen?
