### ISSUE TITLE
teamviewer

### ISSUE THREAD

**Issue by SagnikSRHUSE** [NixOS/nixpkgs#43027]
teamviewer configuration files use the .deb, however, TV offers generic .tar.xz packages: 
https://download.teamviewer.com/download/linux/teamviewer_amd64.tar.xz
https://download.teamviewer.com/download/linux/teamviewer_i386.tar.xz

Also, the version 12 gives an unsupported error, and it forces me to upgrade to 13 (which is not possible in the current stable version).

**Comment by coretemp** [comment]
In `master` this is already fixed, which is what I have used a couple of times.

**Comment by SagnikSRHUSE** [comment]
Oh, maybe push the v13 to stable? Also, this comes up when I start v12. 
![screenshot_20180706_145748](https://user-images.githubusercontent.com/16162562/42371402-046c119a-812d-11e8-8ece-4ddcf595452c.png)
When I run the cmd listed,
![screenshot_20180706_145945](https://user-images.githubusercontent.com/16162562/42371489-3c8ce482-812d-11e8-884e-3603625eaa55.png)

**Comment by coretemp** [comment]
I would welcome a change to push v13 to stable, since I don't think v12 has any users.

**Comment by peterhoeg** [comment]
Please don't post screenshots of terminals - copy/paste the text instead. The ```teamviewerd.service``` error is because you didn't activate it via ```config.services.teamviewer.enable = true;```. 

Would any of you be interested in taking a shot at a PR that updates teamviewer?

**Comment by JohnAZoidberg** [comment]
Teamviewer is at version 15 now and properly starts without the warning about the daemon.
