### ISSUE TITLE
nixpkgs-unstable channel on nixos.org lags significantly behind git

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#43077]
## Issue description

https://nixos.org/channels/nixpkgs-unstable redirects to
https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.09pre143801.5ac6ab091a4 ,
which is at 5ac6ab091a4 (Jun 24)

while git channel https://github.com/NixOS/nixpkgs-channels/tree/nixpkgs-unstable is at 14a9ca27e69e33ac8ffb7 (Jul 1)

I'd expect them to be in sync (except maybe for a short delay updating the mirrors).

**Comment by szeck87** [comment]
Maybe https://github.com/NixOS/nixpkgs/issues/43015 is related?  Doesn't explain why all of the sudden it uses a build from 6/24.

**Comment by xeji** [comment]
Back in sync now, was probably a temporary issue.
