### ISSUE TITLE
patchelf/setup-hook.sh removes runtimeDependencies added by autoPatchelfHook

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#43082]
## Issue description

The `patchelf` setup hook removes the paths added by `autoPatchelfHook` via the `runtimeDependencies` attribute. One has to also add `dontPatchELF = true;` in order to preserve the RPATH.

It would be nice if `patchelf` had a flag to preserve specific RPATH entries when running `--shrink-rpath`. Failing that, `autoPatchelfHook` should probably disable the `patchelf` hook itself.

**Comment by bjornfor** [comment]
(notifying @aszlig)

**Comment by aszlig** [comment]
Mhm, I had that problem as well already so I usually use [`dontPatchELF`](https://github.com/openlab-aux/vuizvui/blob/753d37c21993283ac93352adb0c01a0cddce186d/pkgs/games/build-support/build-game.nix#L46).

Maybe the `patchelf` hook needs to check something like `keepRPaths` which then can be set by `autoPatchelfHook`.

**Comment by aszlig** [comment]
OTOH, forget that, that's too complicated, we just need to make sure the `autoPatchelfHook` runs after `patchelf`.

**Comment by dezgeg** [comment]
Shouldn't `patchelf --shrink-rpath` keep the rpath entry as long as there's a DT_NEEDED entry for that dynamic library?

**Comment by aszlig** [comment]
@dezgeg: Yep, that's what the case, but this is for `runtimeDependencies` which are additional paths so that they can be `dlopen`ed at runtime.
