### ISSUE TITLE
npm electron-packager build to /lib64 location

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#43098]
## Issue description 
i build we-chat project with npm: 
https://github.com/geeeeeeeeek/electronic-wechat  
when i build the binary execute using: npm run build:linux  
it produce the binary file linked to /lib64/ld-linux-x86-64.so.2  

### Steps to reproduce  
git clone https://github.com/geeeeeeeeek/electronic-wechat  
npm run build:linux

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.52, NixOS, 18.03.132803.2f06e04b74e (Impala)`

**Comment by peterhoeg** [comment]
I believe we are not patching npm in any way, so you will have to use something like ```node2nix``` to make a nodejs application behave.

**Comment by clojurians-org** [comment]
i switch to node2nix, it just build the result to /nix/store for linking, 
   but it produce still the /lib64  executable binary .
for this project: https://github.com/geeeeeeeeek/electronic-wechat,
it use scripts/build.sh to produce executable binary, that  turn over to electron-packager to built binary.

i notice nixpkgs contains "electron", but not electron-packager.

**Comment by peterhoeg** [comment]
I'm not familiar with electron packaging but ```nix-tour``` seems to be an electron application so maybe have a look at that for inspiration?

**Comment by clojurians-org** [comment]
thanks, it works now.

**Comment by peterhoeg** [comment]
If you have the packaging sorted out, please ping me in the PR so we can get it added to nixpkgs.
