### ISSUE TITLE
warning about inetutils vs net-tools ifconfig behaving differently

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#43105]
## Issue description

I've spent some time debugging a strange issue while packaging mininet so I thought I would leave a trace. To give mininet access to the telnet binary I wrapped it like this 
```
      makeWrapper ${pyEnv}/bin/mn $out/bin/mn \
       --prefix PATH : "${pkgs.telnet}/bin:${pkgs.which}/bin"
```

but this had the side effect of adding an alternative `ifconfig` binary in PATH. In fact, pkgs.telnet is an alias for pkgs.inetutils. Thing is inetutils' ifconfig doesn't behave the same as net-tools' ifconfig. The first one displays the interface configuration on `ifconfig lo up` while the second displays nothing. Mininet expects the latter (else it throws an error). I wonder if telnet should be in another output of inetutils to prevent this ? I think I will use the busybox binary for now (there also seems to be one in libtelnet)

## Technical details

nixos-unstable

**Comment by teto** [comment]
I tried using the busybox telnet version but seems like it lacks the "-e" flag required by mininet hence I ended up wrapping the telnet binary `makeWrapper ${pkgs.telnet}/bin/telnet $out/bin/telnet`

**Comment by matthewbauer** [comment]
The main reason for that alias was to make sure everything still works on Darwin (inetutils can be built on Darwin while nettools cannot). I think it might be best to just add unixtools.ifconfig in this case & report to mininet that it is incompatible with inetutils' ifconfig program.

```
makeWrapper ${pyEnv}/bin/mn $out/bin/mn \
       --prefix PATH : "${pkgs.unixtools.ifconfig}/bin:${pkgs.telnet}/bin:${pkgs.which}/bin"
```

I'm not sure if it's a good idea to rely on ifconfig existing (although on NixOS it will).
