### ISSUE TITLE
Perl5: it is not possible to access the gdbm library

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#4311]
There is program I want to install on nixos. The problem is that this program depends on `GDBM_File`, which is a perl module to  access the `gdbm` library. `GDBM_File` should be provided by the `perl` package.

I have tried to add `gdbm` as a build input dependency to `perl`, but it does not work. `nix-build` gives the error: `infinite recursion encountered`. So I do not know how to fix this.

Please, add support to `GDBM_File` in the `perl` package.

**Comment by Profpatsch** [comment]
Can probably be closed @jagajaga 

@romildo if you haven’t given up in the meantime, maybe we can help you still.

**Comment by jagajaga** [comment]
ping @romildo

**Comment by romildo** [comment]
As I stayed away from NixOS for some time, I do not remember the details of the issues anymore. I will close for now. In case this issue comes in again, I may reopen it.

**Comment by romildo** [comment]
I am back to this issue.

I wan to to run [fbmenugen](https://github.com/trizen/fbmenugen) which is perl application that depends on `GDBM_File`. Any clues on how to have this core perl module accessible?

cc @Profpatsch @jagajaga

**Comment by Profpatsch** [comment]
I’m sorry, I don’t have any experience with Perl, so all I can do it point you [to the nixpkgs manual section](https://nixos.org/nixpkgs/manual/#sec-language-perl).

**Comment by romildo** [comment]
cc @edolstra @jagajaga
Any clues on this?

**Comment by romildo** [comment]
Fixed upstream.
