### ISSUE TITLE
mpd doesn't build on darwin

### ISSUE THREAD

**Issue by anttih** [NixOS/nixpkgs#43118]
## Issue description

`mpd` doesn't build on my Mac. Looks to me like the other package managers have a patch for this, like in [here](https://github.com/Homebrew/homebrew-core/pull/26784).

```
In file included from src/output/plugins/OSXOutputPlugin.cxx:35:
include/boost/lockfree/spsc_queue.hpp:140:43: error: no member named 'next' in namespace 'boost'
        const ConstIterator last = boost::next(begin, input_count);
                                   ~~~~~~~^
include/boost/lockfree/spsc_queue.hpp:145:51: error: no member named 'next' in namespace 'boost'
            const ConstIterator midpoint = boost::next(begin, count0);
                                           ~~~~~~~^
src/output/plugins/OSXOutputPlugin.cxx:714:42: warning: cast from 'const void *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
        return od->ring_buffer->push((uint8_t *)chunk, size);
                                                ^
1 warning and 2 errors generated.
make[1]: *** [Makefile:13223: src/output/plugins/liboutput_plugins_a-OSXOutputPlugin.o] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-mpd-0.20.18.drv-0/source'
make: *** [Makefile:5325: all] Error 2
builder for '/nix/store/dp26x7a6v6gcqb7bhw674mfzw6lbqw7q-mpd-0.20.18.drv' failed with exit code 2
error: build of '/nix/store/dp26x7a6v6gcqb7bhw674mfzw6lbqw7q-mpd-0.20.18.drv' failed
```

### Steps to reproduce

`nix-env -i mpd`

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.6.0, macOS 10.13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - channels(aholvika): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Can you file this upstream? It looks like an incompatibility with Boost 1.67. You can also try setting ```boost = boost166;``` for mpd.

**Comment by aanderse** [comment]
@anttih is this still an issue with an up to date nixpkgs?

**Comment by smancill** [comment]
This should be closed: https://hydra.nixos.org/job/nixpkgs/trunk/mpd.x86_64-darwin
