### ISSUE TITLE
sddm: cannot login

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#43241]
## Issue description
After [this](https://github.com/NixOS/nixpkgs/pull/42768/commits/dbde7908c6b22f6b4b1ab3056829f47f44207315) got merged, and is in the nixos-unstable channel, I noticed after I rebuilt my system that when sddm starts and I type in my password it just goes black and restarts sddm. Meaning that I can never reach the desktop :(

I could also not find anything useful in the journal.

cc @peterhoeg @bkchr

**Comment by peterhoeg** [comment]
In a VT, try this as root:

```sh
rm -rf /var/lib/sddm/*
```

**Comment by worldofpeace** [comment]
Ahh that makes perfect sense and worked @peterhoeg  :hand:
Is there any real way to make sure this doesn't happen for someone else?

**Comment by peterhoeg** [comment]
There was a PR some time ago that was supposed to address this (it was merged) that would simply clear out the directory on start but it looks like that didn't do the trick. I don't remember which. IMHO, the proper way to handle this is something like this:

```
systemd.tmpfiles.rules = [
  "e ${config.users.users.sddm.home}/.cache - - - 0"
];
```

**Comment by bkchr** [comment]
I also often have this problem.. @peterhoeg could you open a pull request that removes the old solution and that adds your solution?

**Comment by peterhoeg** [comment]
The commit was dae260034ca - I'll PR this.
