### ISSUE TITLE
Is it possible to upgrade caddyserver?

### ISSUE THREAD

**Issue by allowthere** [NixOS/nixpkgs#43242]
## Issue description

caddy is currently at release 0.11.0 while 0.10.12.

Is there a reason that caddy wasn't upgraded?

I don't mind doing it myself, I just don't get how to get the `sha256` hash from a release (it doesn't seem to match the git commit hash).

**Comment by ikervagyok** [comment]
1. update the version in `/foo/nixpkgs/.../default.nix` and modify one or more characters in the sha256
2. run `nix-env -f /foo/nixpkgs -i package` or `nixos-rebuild -I nixpkgs=/foo/nixpkgs test`, depending on how you want to install this package
3. now it should complain about a sha256 mismatch and you just need to copy the new sha256 into `default.nix`
4. have fun

**Comment by brainrape** [comment]
Hi @allowthere. Looks like the above answers your question.
For more information, please check out the nixpkgs manual sections on [creating packages](https://nixos.org/nixpkgs/manual/#chap-quick-start) and [reviewing package updates](https://nixos.org/nixpkgs/manual/#reviewing-contributions-package-updates). If the update was successful, please consider submitting a pull request.
If that's satisfactory, can we close this issue? Thanks.

**Comment by aanderse** [comment]
@allowthere this package was updated for 18.09 so please close this issue.
