### ISSUE TITLE
texLive: xelatex should depend on lmodern fonts

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#4324]
I've encountered this error: https://tex.stackexchange.com/questions/652/xetex-not-working-on-ubuntu-10-04
I don't have time to dig deeper into this now, but it looks like lmodern fonts are needed for xelatex's fontspec to work. I've triggered this bug with just

```
\documentclass{article}

\usepackage{polyglossia}
```

**Comment by vcunat** [comment]
#287 shows no error on your input with just `texlive.combine { inherit (texlive) scheme-basic xetex; };`

**Comment by vcunat** [comment]
Hmm, actually it does produce problems when adding `\begin{document} \end{document`, as polyglossia isn't found. Adding just that one isn't enough, too. There do seem to be some underspecified dependencies, but I just took those from upstream... I know Fedora generator does try some automatic dependency detection when building the binary packages.

**Comment by vcunat** [comment]
So, do you know what extra TeX Live packages are needed for xelatex? I can add them to our overrides so that `texlive.combine` always includes them. I don't see what better to do right now about it.

**Comment by abbradar** [comment]
Sorry, I've forgotten about this issue.

With this;
```
  inherit (pkgs.texlive) scheme-basic xetex polyglossia euenc xunicode xetex-def;
```

The document builds fine, so `polyglossia` needs `euenc` but I'm unsure if `polyglossia` or `euenc` needs `xunicode`, same with `xunicode` for `xetex-def`.

**Comment by Profpatsch** [comment]
(triage) @abbradar any news? I recall @vcunat restructured the texlive packages, if you were using the old ones above maybe the problem is solved now.

**Comment by abbradar** [comment]
I can add several dependencies which we've more or less determined (`polyglossia` -> `euenc`, `euenc` -> `xunicode`) and close this later.

**Comment by siddharthist** [comment]
@abbradar Are you still intending on adding those dependencies?

**Comment by abbradar** [comment]
Ough, unfortunately I have several very tight deadlines approaching. Thank you for reminding (I forgot!) but I won't be able to look into this till 10/08...

**Comment by siddhanathan** [comment]
Ping @abbradar

**Comment by vcunat** [comment]
Right.

Oh, I haven't seen you here for a very long time :-)
