### ISSUE TITLE
unexpected EOF reading a line (new incarnation of old bug)

### ISSUE THREAD

**Issue by iblech** [NixOS/nixpkgs#43255]
## Issue description

On current nixpkgs unstable, `nix-build -vvvv nixpkgs.pkgsi686Linux.libdvdread_4_9_9` fails with `error: unexpected EOF reading a line` after having successfully built the library and even shrinked the binary outputs. This problem is not specific to `nixpkgs.pkgsi686Linux.libdvdread_4_9_9` (which is a dependency of `nixpkgs.pkgsi686Linux.mplayer`), but pertains to several other derivations as well, for instance `nixpkgs.pkgsi686Linux.gegl_0_4` (required by `nixpkgs.pkgsi686Linux.gimp`). On the other hand, there are many derivations for which there is no problem at all; I'm at a loss deciphering the underlying systematic.

The last couple of debug messages are as follows:

    post-installation fixup
    shrinking RPATHs of ELF executables and libraries in /nix/store/8wdz4w3m0y7wn13dhshv6f9cx801ix1p-libdvdread-4.9.9
    shrinking /nix/store/8wdz4w3m0y7wn13dhshv6f9cx801ix1p-libdvdread-4.9.9/lib/libdvdread.so.4.1.2
    strip is /nix/store/xq302517rp99n1b5p8n4if656pp1d139-binutils-2.30/bin/strip
    stripping (with command strip and flags -S) in /nix/store/8wdz4w3m0y7wn13dhshv6f9cx801ix1p-libdvdread-4.9.9/lib
    patching script interpreter paths in /nix/store/8wdz4w3m0y7wn13dhshv6f9cx801ix1p-libdvdread-4.9.9
    checking for references to /tmp/nix-build-libdvdread-4.9.9.drv-1 in /nix/store/8wdz4w3m0y7wn13dhshv6f9cx801ix1p-libdvdread-4.9.9...
    killing process 28434
    lock released on '/nix/store/8wdz4w3m0y7wn13dhshv6f9cx801ix1p-libdvdread-4.9.9.lock'
    building of '/nix/store/r8xkgbvwkxqvhwj03wg1k3cknnl94l32-libdvdread-4.9.9.drv': goal destroyed
    error: unexpected EOF reading a line

The bug described here previously surfaced with Nix 1.1.12. It was then fixed: https://github.com/NixOS/nixpkgs/issues/29257 Now it seems that the bug has returned.

### Steps to reproduce

Run `nix-build -vvvv nixpkgs.pkgsi686Linux.libdvdread_4_9_9`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.110, Debian GNU/Linux, 7 (wheezy)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(iblech): `"nixpkgs"`
 - nixpkgs: `/home/iblech/.nix-defexpr/channels/nixpkgs`

**Comment by aszlig** [comment]
The issue you linked looks like it's unrelated to that. Can you please retry by running the following:

```sh-session
$ nix-build -E '(import <nixpkgs> {}).pkgsi686Linux.libdvdread_4_9_9.overrideAttrs (drv: { preFixup = (drv.preFixup or "") + "set -x"; })'
```

This should print out what is executed in the shell.

**Comment by aszlig** [comment]
Other than that, an output of `strace -f nix-build '<nixpkgs>' -A pkgsi686Linux.libdvdread_4_9_9` (which should work here, because you seem to be running Nix in single-user mode instead of via daemon) would be helpful as well if the error wasn't apparent enough from `set -x`.

Another thing that could be useful to reproduce this is the revision of nixpkgs you're running.

**Comment by iblech** [comment]
Thank you for your help, @aszlig. Sorry that I didn't get to your feedback earlier.

I'm happy to report that I can no longer reproduce the error. So I regard this problem, whatever it was, to be fixed.
