### ISSUE TITLE
guessit 2.0 -> but uses 3.0

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#43252]
## Issue description

Flexget refused to work after upgrade. I noticed the problem was guessit. Having a look at the .nix files I noticed that https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/guessit/2.0.nix was actually updated to use guessit 3.0.

However guessit 3.0 uses different stuff and flexget breaks when using guessit 3.0.

For me, I can't really understand why a file named guessit/2.0.nix uses guessit 3.0. 

### Steps to reproduce

Try to install and run flexget from nixos unstable or nixos unstable small.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.53, NixOS, 18.09.git.fec309a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(hyper): `""`
 - channels(root): `"nixos-18.09pre145435.fec309aee46"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
Can you please check whether #43276 fixes your problem?

**Comment by FRidh** [comment]
That's because of an accidental version update. I'm merging #43276 because it's a step in the right direction and closing this.

**Comment by sjau** [comment]
yep, that works fine now. Thx @dotlambda
