### ISSUE TITLE
error: attribute 'linuxPackages_testing_bcachefs' missing

### ISSUE THREAD

**Issue by t184256** [NixOS/nixpkgs#43253]
## Issue description

Attempting to use `boot.supportedFilesystems = [ "bcachefs" ];` leads to

`error: attribute 'linuxPackages_testing_bcachefs' missing`

I strongly suspect that 298e170b36b79f4c6b19816a7abbf8392a490840 is to blame. What the?

@NeQuissimus, @vcunat, @samueldr

### Steps to reproduce

`boot.supportedFilesystems = [ "bcachefs" ];`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.03.132821.56fad146a12 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `"nixos-18.03, nixos-hardware, home-manager"`
 - channels(monk): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by samueldr** [comment]
Looks like you're right, `linux_testing_bcachefs` [was removed](https://github.com/NixOS/nixpkgs/commit/298e170b36b79f4c6b19816a7abbf8392a490840#diff-036410e9211b4336186fc613f7200b12L13569).

It looks like [it's still in unstable](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/linux-testing-bcachefs.nix), even on master.

I don't know if this was justified or an overzealous bit of cleanup. After all, it's a 4.15 kernel.

If you have everything setup to try with a git checkout, could you cherry-pick [this partial revert](https://github.com/NixOS/nixpkgs/pull/43235) to verify?

**Comment by t184256** [comment]
> I don't know if this was justified or an overzealous bit of cleanup. After all, it's a 4.15 kernel.

Definitely overzealous, bcachefs kernel always lags behind and there's no easy way around it for now.

> this partial revert

Wrong link?

> If you have everything setup to try with a git checkout

Checked out samueldr:fix/revert-bcachefs (#43257), rebuilt with `-I` pointing to it, the problem is gone, a kernel rebuild started. Please merge.

**Comment by samueldr** [comment]
Oopsie, wrong link indeed! It has been fixed.

**Comment by samueldr** [comment]
It seems github didn't auto-close this from the PR body. I believe this can be closed (as PR was merged, this will hit stable hopefully soon).

**Comment by vcunat** [comment]
(It's even in the channel already.)
