### ISSUE TITLE
qt5.11.1 no longer supports macOS with 10.10 SDK

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#43258]
## Issue description
It looks like Qt has broken support for SDK 10.10 in their latest release. Here is the log:

https://hydra.nixos.org/build/77013683

Any ideas on how we can fix this?

**Comment by orivej** [comment]
#43290 fixes this.

**Comment by LnL7** [comment]
We should probably keep this open tho, we can't keep using https://github.com/NixOS/nixpkgs/commit/4ed62d6b881241c3d0ed6ad62b0c0514734661bf.
