### ISSUE TITLE
pip2nix: package needs an older version of pip

### ISSUE THREAD

**Issue by haposik** [NixOS/nixpkgs#43275]
Hi, I've encountered a problem during installation of this package: [github](https://github.com/johbo/pip2nix). It requires pip>=8,<10 to be installed and as an option it tries to install pip-9.0.1 as you can see [here](https://github.com/johbo/pip2nix/blob/51e6fdae34d0e8ded9efeef7a8601730249687a6/python-packages.nix#L57).
I attach log of executing command `nix-shell release.nix -A pip2nix.python36 --verbose 2>&1 | tee nix.log`: 
[nix.log](https://github.com/NixOS/nix/files/2177040/nix.log)

As you can see it eveluates 2 files of lines 115-116: 
- [/nix/store/ig7r3d66my6d20xnjdfxwnd5p2gkrf8q-nixpkgs-18.09pre144939.14a9ca27e69/nixpkgs/pkgs/development/python-modules/pip/default.nix](https://github.com/NixOS/nix/files/2177060/pip-default.nix.log)
- [/nix/store/ig7r3d66my6d20xnjdfxwnd5p2gkrf8q-nixpkgs-18.09pre144939.14a9ca27e69/nixpkgs/pkgs/development/python-modules/bootstrapped-pip/default.nix](https://github.com/NixOS/nix/files/2177071/bootstrapped-pip-default.nix.log)

And after that, it downloads pip-10.0.1 from `cache.nixos.org`; lines: 245, 253, and says that they are going to be fetched below.

Also I attach result of `nix-shell -p nix-info --run "nix-info -m"`:
- system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-36-generic, Ubuntu, 16.04.4 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(user): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

I tried to make this experiment as clean as possible, so I executed all the process on VM Ubuntu without installing any extra packages

**Comment by FRidh** [comment]
If you look in the log, it says:
```
Collecting pip<10,>=8 (from pip2nix==0.8.0.dev1)
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
Requirement already satisfied: configobj>=5 in /nix/store/ssiv9prn6yrr011raa2i421jb9d6p9xr-python3.6-configobj-5.0.6/lib/python3.6/site-packages (from pip2nix==0.8.0.dev1) (5.0.6)
Requirement already satisfied: click in /nix/store/s9xyjg4igvlk8mi7d360yn6dpz7lm2rf-python3.6-click-6.6/lib/python3.6/site-packages (from pip2nix==0.8.0.dev1) (6.6)
Requirement already satisfied: contexter in /nix/store/awa95kyjljs2qdhm7prkyw4jc4lhd2qp-python3.6-contexter-0.1.3/lib/python3.6/site-packages (from pip2nix==0.8.0.dev1) (0.1.3)
Requirement already satisfied: jinja2 in /nix/store/fnag4q6ky71gd7wp2jdg50hkms7zz2pv-python3.6-jinja2-2.8/lib/python3.6/site-packages (from pip2nix==0.8.0.dev1) (2.8)
Requirement already satisfied: six in /nix/store/kakjx6jqbj6r7cnfcgr0vw2q6jbikdf9-python3.6-six-1.10.0/lib/python3.6/site-packages (from configobj>=5->pip2nix==0.8.0.dev1) (1.10.0)
Requirement already satisfied: MarkupSafe in /nix/store/6mrigadm1f5nsgslvjlh9vjgikbny43h-python3.6-MarkupSafe-0.23/lib/python3.6/site-packages (from jinja2->pip2nix==0.8.0.dev1) (0.23)
Installing collected packages: pip, pip2nix
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/nix/store/cgsn3d8rq42ijdk3z6lygkrx02msfhiv-python3.6-bootstrapped-pip-10.0.1/lib/python3.6/site-packages/pip-10.0.1.dist-info/LICENSE.txt'
Consider using the `--user` option or check the permissions.
```
The Nix function for installing Python packages uses a special version of `pip`. which is currently version 10. In your case, you apparently need an older `pip`. No idea why, and I suggest as a first step trying to modify the dependency so it is fine with version 10.

Also note that actually this is not a Nixpkgs issue either, but a question about the `pip2nix` tool. Did you choose this tool on purpose? Did you try `pypi2nix`? See also the `pip` expression in `python-modules/` which passes `installFlags = [ "--ignore-installed" ];`.

**Comment by haposik** [comment]
I think the problem is in these two lines (I am new to nix syntax, but I guess I right understand): [line37](https://github.com/johbo/pip2nix/blob/51e6fdae34d0e8ded9efeef7a8601730249687a6/default.nix#L37) [line45](https://github.com/johbo/pip2nix/blob/51e6fdae34d0e8ded9efeef7a8601730249687a6/default.nix#L45).

As far as I get it we explicitly declare an external dependency on pip (certainly for fetching python packages for building ourselves), but we say that we take it [pip] from _basePythonPackages_, which in turn is _python36Packages_ [line7](https://github.com/johbo/pip2nix/blob/51e6fdae34d0e8ded9efeef7a8601730249687a6/default.nix#L7) and [line2](https://github.com/johbo/pip2nix/blob/51e6fdae34d0e8ded9efeef7a8601730249687a6/default.nix#L2 ).

Thus at first we install pip-10 from _python36Packages_. Then we install the project dependencies using it. After that we bump into a pip==9.0.1, which we want to install too. Finally we are trying to do it and ooops! We have not enough permission to downgrade pip, since I guess we will just execute `pip install pip==9.0.1` without `--user` or whatever.

So now we have got a question. How can we build a project, which requires an old pip as a dependency, using nix if we cannot override the installed pip by default?

**Comment by FRidh** [comment]
As I wrote, pass on `installFlags = [ "--ignore-installed" ];.` to the `pip` expression.

**Comment by FRidh** [comment]
Closing this because it really is about `pip2nix`.
