### ISSUE TITLE
krb5 should support the kernel keyring

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#43289]
In an ideal world, this would be as simple as adding the following

```
    ++ optionals (stdenv.hostPlatform.isLinux) [ keyutils ]
```

to the `buildInputs`. Unfortunately, `krb5` seems to be a dependency of `curl` which causes an infinite recursion bug during the Linux `stdenv` bootstrapping. I'm pretty familiar with bootstrapping on Darwin, but am less confident around the Linux one. Anyone have any hints for how to disable `keyutils` support during the bootstrap with minimal mess?

**Comment by matthewbauer** [comment]
If you set ```fetchurl = fetchurlBoot``` for keyutils I think it will break this cycle.

**Comment by copumpkin** [comment]
Oh cool, thanks! I wonder if I should do that on this side though? Something like this:

```
    ++ optionals (stdenv.hostPlatform.isLinux) [ (keyutils.override { fetchurl = fetchurlBoot; }) ]
```

**Comment by copumpkin** [comment]
I'd imagine it has something to do with kerberos being an optional dependency of curl, and curl being involved in the bootstrap, but I haven't unraveled it enough to be more precise than that.

**Comment by copumpkin** [comment]
I ended up doing what you suggested on `keyutils`, @matthewbauer
