### ISSUE TITLE
electron stopped to work on nixos-unstable

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#43297]
## Issue description

On nixos-unstable
`electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.4, NixOS, 18.09pre145504.784f543cb76 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by gnidorah** [comment]
Electron expression hasn't changed since last time it worked.
Maybe its related to gtk changes? @jtojnar

**Comment by jtojnar** [comment]
Not aware of any changes in GTK2. Well, I played with GConf but that did not hit unstable yet..

**Comment by jtojnar** [comment]
Looking at the expression, electron gets its rpath from `atomEnv`

https://github.com/NixOS/nixpkgs/blob/629c9011b4e1f2192b19cb06b572a9fa3775a95c/pkgs/development/tools/electron/default.nix#L50

Which was updated to gtk3 in b95b410d43d1432f2dec821dd953ad468557baca. I guess that is the culprit.

**Comment by gnidorah** [comment]
@jtojnar Indeed. Thank you much!

**Comment by LeOtaku** [comment]
Can this be fixed by just adding both gtk2 and gtk3 to atomEnv?

**Comment by jtojnar** [comment]
It would make it work but updating/fixing electron is what we should do instead.
