### ISSUE TITLE
[package request] lollypop-portal

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#43292]
The `lollypop` music player which is already in `nixpkgs` requires [lollypop-portal](https://gitlab.gnome.org/gnumdk/lollypop-portal) for some features such as tag editing. I am not sure if it is even intended to be run without `lollypop-portal` as the README states “For packagers: You need to provide https://gitlab.gnome.org/gnumdk/lollypop-portal”. Archlinux just packages them together while Ubuntu seems to have separate packages but `lollypop` has a hard dependency on `lollypop-portal`.

I sadly don’t have any experience packaging python applications and couldn’t get it to work properly, so I am opening this request. CC @worldofpeace who packaged `lollypop` for nixpkgs.

**Comment by worldofpeace** [comment]
@cocreature 
This appears to be a dbus service? But it seems to be for flatpak(with or without sandbox).
I would assume if you were using lollypop, not the flatpak, that you wouldn't need this at all to use those features.

Can you verify if the tag editing feature is working currently?

**Comment by cocreature** [comment]
@worldofpeace It is not working currently and what I got from the source code, it tries to handle it via the dbus service.

**Comment by cocreature** [comment]
E.g. here it checks using the portal whether it can launch a tag editor to decide whether the menu item should be displayed https://gitlab.gnome.org/World/lollypop/blob/master/lollypop/pop_menu.py#L337

**Comment by worldofpeace** [comment]
This could be a case of just making the dbus service accessable to the program regardless to the confusing flatpak references in that readme? If so it should be trivial to do.

**Comment by cocreature** [comment]
Yeah that is my understanding. I just couldn’t quite get the python references right when I tried to do this myself and gave up eventually.

**Comment by worldofpeace** [comment]
I guess this would need a nixos module.

**Comment by cocreature** [comment]
I played around with this and it looks like I got it work with the following (at least to the point that the menu item for editing tags shows up and I can launch a tag editor using it):

```
      lollypop-portal = stdenv.mkDerivation rec {
        version = "0.9.7";
        name = "lollypop-portal-${version}";

        src = fetchgit {
          url = "https://gitlab.gnome.org/gnumdk/lollypop-portal.git";
          rev = "refs/tags/${version}";
          sha256 = "0rn5xmh6391i9l69y613pjad3pzdilskr2xjfcir4vpk8wprvph3";
        };

        nativeBuildInputs = with python36Packages; [
          gobjectIntrospection
          meson
          ninja
          pkgconfig
          wrapGAppsHook
          wrapPython
        ];

        buildInputs = with gst_all_1; [
          gtk3
          gst-plugins-base
        ];

        pythonPath = with python36Packages; [
          pygobject3
        ];

        postFixup = ''
          wrapPythonProgramsIn $out/libexec "$pythonPath";
        '';
      };
```

which I added to `systemPackages`. However, I don’t feel nearly confident enough enough that I did things properly and got all the dependencies right, so I’m not going to submit it for now but hopefully it’ll prove helpful for whoever does get around to doing that.

**Comment by worldofpeace** [comment]
Hah we ended up with basically the same thing. :rofl:

**Comment by cocreature** [comment]
Closing, since the PR has been merged. Thanks @worldofpeace!
