### ISSUE TITLE
Port nixos/dnscrypt-proxy to dnscrypt-proxy2

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#43298]
Port the NixOS service to dnscrypt-proxy2, deprecate the legacy package.

**Comment by yegortimoshenko** [comment]
Feel free to just copy over https://github.com/serokell/serokell-public-overlay/blob/public/modules/services/dnscrypt-proxy2.nix.

**Comment by Shados** [comment]
@yegortimoshenko that does not appear to be available any more?

FWIW I'm working on this currently, but if I haven't opened a PR within a couple of weeks then it means I probably won't get it done soon. If I have something working-but-not-great it'll end up [here](https://github.com/Shados/nixos-config/tree/master/bespoke/services) somewhere.

**Comment by bbigras** [comment]
Any progress?

**Comment by doshitan** [comment]
This looks to have been resolved by https://github.com/NixOS/nixpkgs/pull/78543.
