### ISSUE TITLE
FreeCAD does not build on unstable

### ISSUE THREAD

**Issue by matejc** [NixOS/nixpkgs#43305]
## Issue description

FreeCAD does not build on https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.freecad.x86_64-linux

### Steps to reproduce

Hydra does them, otherwise .. nix-env -iA freecad

## Technical details

(probably not needed)
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.4, NixOS, 18.09.git.58373c8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(matejc): `"nixos-17.03pre98682.f673243"`
 - channels(root): `"nixos-17.03pre98682.f673243"`
 - nixpkgs: `/home/matejc/workarea/nixpkgs`

## Problem

Boost is not build with python anymore.

## Solution
```
let
  boostWithPython = boost.override { enablePython = true; };
.
.
.
in
```

and then use `boostWithPython` instead of the `boost` in the buildInputs

Someone can use this for making PR, or wait for me until I get bored watching FreeCAD compile every time I upgrade the channel, which might be soon because it takes a long time to compile :)

**Comment by matejc** [comment]
Oh yea... forgot the logs https://nix-cache.s3.amazonaws.com/log/257qaqccpdj89h2a7knaqvlwdkkafglw-freecad-0.17.drv

**Comment by dtzWill** [comment]
Haha found this while checking no one already fixed the issue :D.  Should've checked *first*, thanks for the great issue! PR coming shortly!

**Comment by FRidh** [comment]
Pushed https://github.com/NixOS/nixpkgs/commit/f96c8496a70d8764e6dc3b19356f36f1b0f0fcd2
