### ISSUE TITLE
rPackages.reprex fails to install

### ISSUE THREAD

**Issue by iimog** [NixOS/nixpkgs#43326]
## Issue description
Installation of `rPackages.reprex` fails using the current `master` branch of `NixOS/nixpkgs` (18.03-beta-14746-g394ef824515). This causes installation of `rPackages.tidyverse` to fail as well as `reprex` is a dependency of that.

### Steps to reproduce
```bash
nix-build -E 'with import <nixpkgs> {}; rWrapper.override { packages = [rPackages.reprex]; }'
```

Running this command builds the packages `reprex` depends on fine but fails on `reprex` itself. Showing output of running the above command a second time (less output because dependencies have already been built and error message is the same).

```
these derivations will be built:
  /nix/store/hbij7lhgdwjnmr4ix4p25813pan43d5x-r-reprex-0.2.0.drv
  /nix/store/651yzgkjb2mik6h43hs15gpdk1sjashn-R-3.5.1-wrapper.drv
building '/nix/store/hbij7lhgdwjnmr4ix4p25813pan43d5x-r-reprex-0.2.0.drv'...
unpacking sources
unpacking source archive /nix/store/x3id8rn8lficzkjkv5dh258ymx5jc09d-reprex_0.2.0.tar.gz
source root is reprex
setting SOURCE_DATE_EPOCH to timestamp 1529710809 of file reprex/MD5
patching sources
configuring
building
running tests
installing
* installing *source* package 'reprex' ...
** package 'reprex' successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) :
  error in running command
Error : unable to load R code in package 'reprex'
ERROR: lazy loading failed for package 'reprex'
* removing '/nix/store/h56mgq3gr0fgw2nfgmldhkn07kvgir33-r-reprex-0.2.0/library/reprex'
builder for '/nix/store/hbij7lhgdwjnmr4ix4p25813pan43d5x-r-reprex-0.2.0.drv' failed with exit code 1
cannot build derivation '/nix/store/651yzgkjb2mik6h43hs15gpdk1sjashn-R-3.5.1-wrapper.drv': 1 dependencies couldn't be built
error: build of '/nix/store/651yzgkjb2mik6h43hs15gpdk1sjashn-R-3.5.1-wrapper.drv' failed
```

I'm stuck searching the cause for this problem. Using `--keep-failed` in the `nix-build` command above and searching for `system` (using ripgrep) does not reveal the error producing code in the package. Whats more I'm able to run the install step manually and it works:

```bash
nix-build --keep-failed -I nixpkgs=. -E 'with import <nixpkgs> {}; rWrapper.override { packages = [rPackages.reprex]; }'
cd /tmp/nix-build-r-reprex-0.2.0.drv-0
source env-vars
mkdir /tmp/test-reprex
$rCommand CMD INSTALL reprex -l /tmp/test-reprex
```

This produces the following output:
```
During startup - Warning message:
Setting LC_TIME failed, using "C" 
* installing *source* package ‘reprex’ ...
** package ‘reprex’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
During startup - Warning message:
Setting LC_TIME failed, using "C" 
* DONE (reprex)
```

Loading the library afterwards works as well (in `$rCommand`):
```R
library(reprex, lib.loc="/tmp/test-reprex")
```

Any help on debugging this further or fixing it is highly appreciated.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.46, NixOS, 18.03.132545.c40fdcd26c2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.132545.c40fdcd26c2"`
 - channels(user): `"nixpkgs-18.09pre140731.c29d2fde74d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mnacamura** [comment]
> Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) :
  error in running command

Probably `which` is required for installation.
