### ISSUE TITLE
floppyd.c fatal error

### ISSUE THREAD

**Issue by qrilka** [NixOS/nixpkgs#4332]
`floppyd.c` from mtools fails to build. Log could be found at http://lpaste.net/111847 (though it is not a 1st run)
error message says:
```
floppyd.c:44:22: fatal error: X11/Xlib.h: No such file or directory
```
I build it on Gentoo:
```
qrilka@qdesktop ~ $ uname -a
Linux qdesktop 3.12.21-gentoo-r1 #1 SMP Mon Sep 22 17:12:35 MSK 2014 x86_64 Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz GenuineIntel GNU/Linux
```

**Comment by pSub** [comment]
@qrilka I am unable to reproduce the error, neither is hydra (http://hydra.nixos.org/job/nixpkgs/trunk/mtools.x86_64-linux/all?page=1). Are you still able to reproduce the problem? (e.g. via `nix-build mtools`)

**Comment by qrilka** [comment]
Can't reproduce it either
