### ISSUE TITLE
Qutebrowser: H.264 videos don't work

### ISSUE THREAD

**Issue by afraidofmusic** [NixOS/nixpkgs#43363]
## Issue description
H.264 videos (at least in Youtube) don't work in Qutwbrowser.

### Steps to reproduce

1. Install Qutebrowser.
2. Go to https://www.quirksmode.org/html5/tests/video.html
3. You should see the H.264/MP4 video doesn't load but WebM and Ogg/Theora do.

## Technical details
```
qutebrowser v1.3.3
Backend: QtWebEngine (Chromium 61.0.3163.140)
CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10
```
Output of`nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.03.132835.e930c685d51 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```
results.

**Comment by dotlambda** [comment]
I can play the video on the version of qutebrowser on `nixos-unstable`:
```
qutebrowser v1.4.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.5
Qt: 5.11.1
PyQt: 5.10.1
```
However, I guess this is probably due to an upgraded version of Qt instead of qutebrowser. Might have to do `git-bisect` to find out.

**Comment by Enzime** [comment]
Quite possible you're running an old version of `qtwebengine` without proprietary codec support, try installing `qt5.qtwebengine` from `nixos-unstable` (see: #36729)
