### ISSUE TITLE
Concatenate types.listOf types.string to string

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#43362]
## Issue description
I want to convert a `types.listOf types.string` to just a regular string, probably by concatenating.
However, I run into this error no matter what I try, even with `lib.concatStrings`: `error: attempt to call something which is not a function but a set, at /mnt/hdd0/home/okina/Documents/Development/nixpkgs/nixos/modules/services/web-servers/hydron.nix:42:14`

Relevant code:
```
addTags = mkOption {
  type = types.nullOr types.listOf types.string;
  default = null;
  example = ''[ "a111e64e3c4bfe22f64ffd557fc2a80bcd26ac03 komeiji_koishi hat dance" ]'';
  description = "Add TAGS to file specified by hex-encoded SHA1 hash ID.";
};
```

```
${pkgs.hydron}/bin/hydron\
  ${optionalString (cfg.listenAddress != null) " -a ${cfg.listenAddress}"}\
  ${optionalString (cfg.import && cfg.importPaths != null) " import ${cfg.importPaths}"}\
  ${optionalString (cfg.fetchTags) " fetch_tags"}\
  ${optionalString (cfg.removeIDs != null) " remove ${cfg.removeIDs}"}\
  ${optionalString (cfg.addTags != null) " add_tags ${cfg.addTags}"}\
  ${optionalString (cfg.removeTags != null) " remove_tags ${cfg.removeTags}"} serve
```

### Steps to reproduce
N/A

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.4, NixOS, 18.09pre145524.2a8a5533d18 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos, nixpkgs"`
 - channels(okina): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
In your implementation, use `concatenateStringsSep`.

**Comment by Chiiruno** [comment]
Thank you! That did it!
