### ISSUE TITLE
Package `dhall-text` fails build

### ISSUE THREAD

**Issue by KirinDave** [NixOS/nixpkgs#43375]
## Issue description

Currently when requesting the package `dhall-text` be installed, it fails at build with the following error: 
````
Setup: Encountered missing dependencies:
dhall >=1.14.0 && <1.15
````
This is most likely bcause the dhall package itself is substantially out-of-date.

### Steps to reproduce

`nix-env -i dhall-text

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43-05062-g1048e72698de, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(redacted): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - nixpkgs: `/home/redacted/.nix-defexpr/channels/nixpkgs`

**Comment by dtzWill** [comment]
Looks like upstream fixed this: https://github.com/dhall-lang/dhall-text/pull/9

And subsequently made a new release.  Not sure the protocol for updating haskell packages but seems like we just need to bump the version we're using?

**Comment by dtzWill** [comment]
Fixed on latest master, try updating your channels! :grin:
