### ISSUE TITLE
emacsPackagesNg.overrideScope throws error: attribute 'fixed-points' missing

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#43398]
## Issue description

After updating to the latest nixos-unstable, my standard package set no longer evaluates. I tracked it down to my use of an override to an emacs package via overlay using `emacsPackagesNg.overrideScope`.

### Steps to reproduce

I can reproduce this without the specifics of my overlays, simply by calling `emacsPackagesNg.overrideScope`:

```
% NIX_PATH="nixpkgs-overlays=/var/empty:$NIX_PATH" nix repl
Welcome to Nix version 2.0.4. Type :? for help.

nix-repl> :l <nixpkgs>
Added 9157 variables.

nix-repl> emacsPackagesNg.overrideScope (super: self: {})
error: attribute 'fixed-points' missing, at /nix/store/ibgff69gncb7lf3cpi6180lzlsxn5lgw-nixos-18.09pre145679.dae9cf6106d/nixos/lib/customisation.nix:205:14
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.53, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - channels(cumber): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
I'm seeing this as well. Did you figure out what was going on?

**Comment by jhenahan** [comment]
Hit this as well. Looks like https://github.com/NixOS/nixpkgs/commit/4794aa5de233b5bf2d1c3245946379699d023467 fixes it.
