### ISSUE TITLE
How to get $buildPhase from a sub-shell of nix-shell

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#43405]
## Issue description
I would like to run `eval "$buildPhase"` within (neo)vim, ideally within the neomake plugin https://github.com/neomake/neomake/issues/1594. This would allow to populate the quickfix and click to jump on compilation errors.

After entering a nix-shell, I start vim but then `$buildPhase` is not defined anymore. 
I would like from within vim to launch a shell that runs `eval "$buildPhase"` with $buildPhase identical to the parent nix-shell.
Is any file I could source to setup these values ? I see the values are present in `nix show-derivation ` but not elsewhere.

NB: a solution could be to start a new nix-shell into the shell started from vim. But then I need to pass it the attribute name manually (maybe I can fetch it from some variables within the nix-shell but not sure how). Also it will be slower compared to just evaluating "$buildPhase"

**Comment by matthewbauer** [comment]
Could you just do ```nix-shell --run 'echo $buildPhase'``` ?

**Comment by teto** [comment]
Thanks for the answer. Ideally I would like not have to tell the plugin the attribute path "hello" so that neomake can run automatically without me specifying `Neomake hello`.
If I am already in a nix-shell, I can pick up the derivation name from "$name" (and still it's not an environment variable so once I launch nvim, the value disappears) but that's slow, is there a way to pick it up the attribute path instead ?
Maybe my best bet is to wrap nix-shell so that it exports its command line as an environment variable, I can then parse it later to get the attribute path and use your command to retrieve the buildPhase.

**Comment by teto** [comment]
Here is a maker for nix that kinda works https://github.com/neomake/neomake/pull/2070 (once in a nix-shell, run `:Neomake! nix`) but sometimes fails like it's missing environment variables :s
