### ISSUE TITLE
qt59.qtwebkit fails: getting wrong src param

### ISSUE THREAD

**Issue by dylex** [NixOS/nixpkgs#43401]
## Issue description

On current master, building qt59.qtwebkit fails with a bizarre error:

```
unpacking sources
unpacking source archive /nix/store/h65ibmjyrm432xbnxydc5xrc8sxwx8hq-src-1.18
source root is src-1.18
patching sources
applying patch /nix/store/fdmxq8vqaxz2isld3rq682v01fwcss18-qtwebkit.patch
can't find file to patch at input line 5
```

This is apparently because the src param to qtwebkit is coming from the new `version-management/src` package rather than the qt settings.

### Steps to reproduce

nix-build -A qt59.qtwebkit

Removing the `src ? null` param from the qtwebkit module fixes the problem (though may break other qt versions).

**Comment by veprbl** [comment]
Currently not it is not broken on stable or master:
https://hydra.nixos.org/job/nixos/release-19.09/nixpkgs.qt59.qtwebkit.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/qt59.qtwebkit.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/qt59.qtwebkit.aarch64-linux
