### ISSUE TITLE
Typo in httpd warning (minor)

### ISSUE THREAD

**Issue by BadDecisionsAlex** [NixOS/nixpkgs#43420]
Just something minor but it's worth fixing.
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/apache-httpd/default.nix
line 659
The warning mistakenly prints an extra double quote at the end of it's line.

**Comment by Infinisil** [comment]
Thanks! Fixed in b9c95c7d600e9a10e40a8a1de2504725602241b7
