### ISSUE TITLE
Package Control for Sublime Text 2/3 Requires Symlink

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#4343]
Package Control, a package for installing more packages for Sublime Text 2 and 3 looks for the SSL certificates in a specific place `/etc/ssl/certs/ca-certificates.crt`, whereas in NixOS it's in `/etc/ssl/certs/ca-bundle.crt`. Since many users of Sublime Text 2 and 3 install Package Control, it'd be nice if a proper symlink was put in place when installing either of these packages.

**Comment by Profpatsch** [comment]
(triage) @Havvy still a problem?

**Comment by Havvy** [comment]
I don't know, and it's non-trivial for me to test it.

**Comment by Profpatsch** [comment]
Then we can close @jagajaga
