### ISSUE TITLE
vimUtils.buildVimPluginFrom2Nix throw error: infinite recursion encountered, at undefined position

### ISSUE THREAD

**Issue by countoren** [NixOS/nixpkgs#43455]
## Issue description

vim utils buildVimPluginFrom2Nix throw error: infinite recursion encountered, at undefined position
in nix-repl 

### Steps to reproduce

this is my [config.nix]( https://github.com/countoren/nixpkgs/blob/835a6de55c6f4ecf536ee3cd6b29d4556b955a72/config.nix) .
in nix-repl :
```
nix-repl> :l <nixpkgs>       
nix-repl> vimUtils.buildVimPluginFrom2Nix { name = "vim-wombat-2017-12-22"; src = fetchFromGitHub { owner = "vim-scripts"; repo = "wombat256.vim"; rev = "8734ba45dcf5e38c4d2686b35c94f9fcb30427e2"; sha256 = "01fdvfwdfqn5xi88lfanb4lb6jmn1ma6wq6d9jj2x7qamdbpvsrg"; }; dependencies = []; }
```

returns:

`error: infinite recursion encountered, at undefined position`

**Comment by countoren** [comment]
one thing I noticed that if I change the vimrc derivation attribute name in the config.nix to myvimrc vimUtils.buildVimPluginFrom2Nix does not throw an error. I was trying to check why it happens (looking at buildVimPluginFrom2Nix) but I could not figure out why.

**Comment by timokau** [comment]
I've done some refactoring of the vim infrastructure recently and cannot reproduce the issue with `nix-repl` on current master. Please re-open if you can still reproduce on master (e.g. check out the nixpkgs repository, `cd` into it and replace `:l <nixpkgs>` with `:l .` or wait for the channels to update).

**Comment by countoren** [comment]
Ok thanks
