### ISSUE TITLE
mendeley 1.19.1 crash

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#43461]
## Issue description
for the past month, I haven't been able to open a pdf from mendey (installed through home-manager). I dunno if it's a mismatch between the system state and home-manager state (I've tried to rebuild both at the same time to no avail). I wonder if anyone has the same issue ?
```
QFSFileEngine::open: No file name specified
[0713/143902.966445:WARNING:stack_trace_posix.cc(699)] Failed to open file: /run/nscd/dbRYbR55 (deleted)
  Error: No such file or directory
[3468:3468:0713/143903.111115:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.
Received signal 11 SEGV_MAPERR 000005452b34
#0 0x7f596579719e <unknown>
#1 0x7f596411e07c <unknown>
#2 0x7f5965797687 <unknown>
#3 0x7f596b50df10 <unknown>
#4 0x7f5962d9a85e <unknown>
#5 0x7f5962d9a988 <unknown>
#6 0x7f5962d27577 QWidgetPrivate::inheritStyle()
#7 0x7f5962d273d7 QWidgetPrivate::setStyle_helper()
#8 0x7f5962d27651 QWidgetPrivate::inheritStyle()
#9 0x7f5962d273d7 QWidgetPrivate::setStyle_helper()
#10 0x7f5962d27651 QWidgetPrivate::inheritStyle()
#11 0x7f5962d273d7 QWidgetPrivate::setStyle_helper()
#12 0x7f5962d27651 QWidgetPrivate::inheritStyle()
#13 0x7f5962d273d7 QWidgetPrivate::setStyle_helper()
#14 0x7f5962d27651 QWidgetPrivate::inheritStyle()
#15 0x7f5962d273d7 QWidgetPrivate::setStyle_helper()
#16 0x7f5962d27651 QWidgetPrivate::inheritStyle()
#17 0x7f5962d37e8e QWidget::setParent()
#18 0x7f5962e97c50 <unknown>
#19 0x00000086b547 PdfViewerTab::stealDetailsPane()
#20 0x000000848edc MainWindowTabViewController::handleTabChange()
#21 0x00000075e84b <unknown>
#22 0x7f5961f8a84b QMetaObject::activate()
#23 0x7f5962e9abee QTabBar::currentChanged()
#24 0x7f5962e9f1bd QTabBar::setCurrentIndex()
#25 0x00000082a8d9 MainWindow::openViewerTab()
#26 0x00000075fb0c <unknown>
#27 0x7f5961f8a84b QMetaObject::activate()
#28 0x000000b4834a DocumentFileFetcher::fileForInternalViewer()
#29 0x000000a80204 DocumentFileFetcher::openLocalFile()
#30 0x000000a80c8c DocumentFileFetcher::open()
#31 0x00000081e25b MainWindow::openDocumentFile()
#32 0x00000081e308 MainWindow::openDocumentFile()
#33 0x00000075fbb8 <unknown>
#34 0x7f5961f8b372 QObject::event()
#35 0x7f5962d37223 QWidget::event()
#36 0x7f5962e3e2e0 QMainWindow::event()
#37 0x7f5962cf802c QApplicationPrivate::notify_helper()
#38 0x7f5962cff5df QApplication::notify()
#39 0x7f5961f5b608 QCoreApplication::notifyInternal2()
#40 0x7f5961f5e14d QCoreApplicationPrivate::sendPostedEvents()
#41 0x7f5961fb6113 <unknown>
#42 0x7f595ead3f47 g_main_context_dispatch
#43 0x7f595ead4180 g_main_context_iterate.isra.26
#44 0x7f595ead420c g_main_context_iteration
#45 0x7f5961fb573f QEventDispatcherGlib::processEvents()
#46 0x7f594d040461 <unknown>
#47 0x7f5961f5993a QEventLoop::exec()
#48 0x7f5961f62e00 QCoreApplication::exec()
#49 0x00000073d913 main
#50 0x7f5961005b8e __libc_start_main
#51 0x000000740379 _start
  r8: 0000000000000000  r9: ffffffffffffffff r10: 0000000000000000 r11: 0000000000000000
 r12: 0000000004db7ec0 r13: 0000000003647238 r14: 0000000000000208 r15: 0000000000000001
  di: 0000000000000000  si: 0000000000000000  bp: 00007fff9b2e9400  bx: 00000000036471b8
  dx: 0000000000000000  ax: 0000000005452b14  cx: 0000000000000000  sp: 00007fff9b2e9400
  ip: 00007f5962d9a85e efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000005452b34
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

### Steps to reproduce
Open mendeley and open a pdf.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.09.git.613a7ee (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by dtzWill** [comment]
I can confirm :(.

Folks over on Arch seem to be experiencing this too: https://aur.archlinux.org/packages/mendeleydesktop/

Tried using the 1.19.2 beta but doesn't help...

**Comment by teto** [comment]
Glad I am not alone (sorry). It's a boring but manageable problem hopefully they will solve it in next release.

**Comment by RodrigoHache** [comment]
I can confirm :(.
Folks over on Arch seem to be experiencing this too, 
Tried using the 1.19.2 beta as well, no results

**Comment by teto** [comment]
I had a problem with 1.19.2 opengl so I reinstalled 1.19.1 and the problem seems fixed on nixos-unstable for 1.19.1.

**Comment by teto** [comment]
nevermind...

**Comment by teto** [comment]
I've given up on mendeley

**Comment by tbenst** [comment]
@dtzWill appears that the Arch folks figured it out... https://aur.archlinux.org/packages/mendeleydesktop/. @teto perhaps reopen?

**Comment by teto** [comment]
I am in the process of moving to https://papis.readthedocs.io/en/latest/. As much as I liked mendeley I've had too many problems with it and also "proprietary". I reopen but unsubscribe from the issue.

**Comment by tbenst** [comment]
here's a solution for now @teto: use flatpak! add `services.flatpak.enable = true;` to 'configuration.nix', then:

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak update
flatpak install flathub com.elsevier.MendeleyDesktop
flatpak run com.elsevier.MendeleyDesktop
```

**Comment by teto** [comment]
thanks for the tip. Sadly with age, contrary to most, I have grown more and more radical :D
1/ I am philosophically against flatpacks/containers etc
2/ I prefer to use open source software so I've switched to papis (definitevely I hope). It has rough edges but a good core.

Plus mendeley have taken some doubtful decisions like cyphering the db so I am not confident for the software future.

**Comment by waynee95** [comment]
Is this error still present with version `1.19.5`? It works fine until I try to open a pdf, then it crashes. I wanted to ask here before creating a new issue, if this is a known problem still.

**Comment by tbenst** [comment]
@waynee95 Yes doesn't work for me either. I'd recommend using flatpak for now:

configuration.nix:
`services.flatpak.enable = true;`

and the command
`flatpak run --filesystem=/data/papers/ com.elsevier.MendeleyDesktop`

**Comment by rochdiboudjehem** [comment]
mendeleydesktop-1.19.4-linux-x86_64 on kubuntu 19.10 linux 5.3.0-55-generic
QFSFileEngine::open: No file name specified
Tried to access value of unset option
Received signal 6
#0 0x7f59d160b0a5 <unknown>
#1 0x7f59d034c141 <unknown>
#2 0x7f59d160b43d <unknown>
#3 0x7f59d6c6f540 <unknown>
#4 0x7f59cda153eb gsignal
#5 0x7f59cd9f4899 abort
#6 0x7f59cdfb005e QMessageLogger::fatal()
#7 0x7f59d6a2135f <unknown>
#8 0x000000b7adc5 GroupFolderMapper::fetchAllGroups()
#9 0x000000ae2dde RemoteDataStore::loadGroups()
#10 0x000000aed070 RemoteDataStore::RemoteDataStore()
#11 0x00000083741a MainWindow::openRemoteDataStore()
#12 0x000000837892 MainWindow::setupDataStore()
#13 0x000000838948 MainWindow::MainWindow()
#14 0x000000751e73 WidgetFactory::newMainWindow()
#15 0x000000751f94 WidgetFactory::createMainWindow()
#16 0x000000750495 StartupManager::createAndShowMainWindow()
#17 0x000000751981 StartupManager::restart()
#18 0x00000073f480 main
#19 0x7f59cd9f61e3 __libc_start_main
#20 0x000000742729 _start
  r8: 0000000000000000  r9: 00007ffd4ee5cbc0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffd4ee5d210 r13: 00007ffd4ee5d290 r14: 00007ffd4ee5d0b0 r15: 00007ffd4ee5d030
  di: 0000000000000002  si: 00007ffd4ee5cbc0  bp: 00007ffd4ee5d240  bx: 00007f59c9545880
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f59cda153eb  sp: 00007ffd4ee5cbc0
  ip: 00007f59cda153eb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by CNOT** [comment]
I can confirm that I'm getting almost the exact same error message as rochdiboudjehem on Ubuntu 20.04. The only semi workaround I found was to run it with administer permissions using 'sudo mendeleydesktop';  however it would have to download the entire database again and I don't feel safe trusting such a proprietary application with admin permissions.

**Comment by ajeytiwary** [comment]
I am having the exact same issue as  rochdiboudjehem  on Ubuntu 20.04. Is there a fix for this yet?

**Comment by gbinux** [comment]
I found [this](https://askubuntu.com/questions/1164672/running-mendeley-in-ubuntu-19-04) was helpful. 

`mendeleydesktop --reset`

After running this, now it's working

**Comment by teto** [comment]
since I dont use mendeley anymore, closing this to clean up my tracker. Please open a new ticket if you have a similar issue.
