### ISSUE TITLE
firejail --help doesn't work

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#43487]
## Issue description
```
Error mkdir: util.c:836 create_empty_dir_as_root: Permission denied
```

### Steps to reproduce
`firejail --help`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.git.411cc55 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by peterhoeg** [comment]
Could you try to strace this to see where it is trying to create directory? On unstable this works.

**Comment by coretemp** [comment]
Thanks for writing the module. I just need to figure out how to run modules from `master` on my stable configuration, which was documented recently. 

```
stat("/run", {st_mode=S_IFDIR|0755, st_size=720, ...}) = 0
stat("/run/firejail", 0x7ffecac10340)   = -1 ENOENT (No such file or directory)
stat("/run/firejail", 0x7ffecac10000)   = -1 ENOENT (No such file or directory)
mkdir("/run/firejail", 0755)            = -1 EACCES (Permission denied)
```

**Comment by peterhoeg** [comment]
Just out of curiosity, can you run firejail after manually creating /run/firejail as root?

**Comment by coretemp** [comment]
No, strace output:

```
mkdir("/run/firejail/network")
```
There is also the same (as network) for `bandwidth`, `name`,  `x11`, etc.

**Comment by peterhoeg** [comment]
I unfortunately will not have time to try this out these next couple of day but I will have a look at it later.

**Comment by andrewchambers** [comment]
same here, firejail not runnable at all.

**Comment by vandenoever** [comment]
After running firejail as root once, the error changes to
```$ firejail
Error: cannot create /run/firejail/profile/26961
```
The `suid` bit is missing on `/run/current-system/sw/bin/firejail` and `/nix/store/.....firejail-0.9.54/bin/firejail`.

**Comment by vandenoever** [comment]
Adding this to `/etc/nixos/configuration.nix` fixes it:

```
security.wrappers = {
  firejail = {
    source = "${pkgs.firejail.out}/bin/firejail";
  };
};
```

**Comment by peterhoeg** [comment]
Nice catch. 65eb3a590d8 was only merged to master, but not stable. This should work in 18.09 as it contains that commit. Closing as "fixed in new-stable".

**Comment by voidzero** [comment]
Just ran into this issue, not sure how to proceed - adding 'security.wrappers' seems to do nothing at all.
