### ISSUE TITLE
Cura "stable" should be called legacy, and Cura needs updating

### ISSUE THREAD

**Issue by tenten8401** [NixOS/nixpkgs#43499]
## Issue description
Cura "stable" should now be called Legacy, as the newer versions of Cura are the recommended version on Ultimaker's website, https://ultimaker.com/en/products/ultimaker-cura-software.
https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/misc/cura

I think it should be set to a separate package name, say `cura-legacy` that way cura legacy doesn't get installed over the latest cura because of the higher numbering system.

Also, it looks like the current Cura 3.3.1 is outdated, and should be replaced with Cura 3.4.1 (released 3 days ago)

**Comment by jfrankenau** [comment]
Just using a different package name wouldn't help as the binary and related files would need to be renamed as well if you are planning to install them side by side. They already have different attribute names such that there shouldn't be any mix-ups. However, `cura-legacy` would indeed be a better name.

The update for Cura 3.4.1 is on its way, see  #43541.

**Comment by gebner** [comment]
The `cura` attribute now points to cura 4.0.0, which is the latest upstream release.
