### ISSUE TITLE
Chromium set as default browser does nothing

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#43532]
## Issue description
As we all know, Chromium loves to give you the "set this browser as your default" prompt every time you start it up, and there's also a preferences option.
Unfortunately this button does nothing.

You can force it with KDE as your default browser, however Chromium does not recognize this and asks anyway.

### Steps to reproduce
Install Chromium, attempt to set it as your default browser from within the browser.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.5, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d, nixpkgs-18.09pre146002.d73fac6b102"`
 - channels(okina): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pkoch** [comment]
I think https://github.com/NixOS/nixpkgs/issues/4370 is relevant for this.

**Comment by emilylange** [comment]
I believe this has been fixed in #60499.

Closing.
