### ISSUE TITLE
Does nixos have libicu-dev?

### ISSUE THREAD

**Issue by YuMingLiao** [NixOS/nixpkgs#43555]
## Issue description

I would like to run [haskellers](https://github.com/snoyberg/haskellers) to learn how to javascript in yesod.
It says it needs `libicu-dev` in its description.

So I tried install `apt` first. After installed, I can't use it.
`apt`
`E: Unable to determine a suitable packaging system type`

And I searched libicu-dev in [website](https://nixos.org/nixos/packages.html#) and there is no libicu-dev in nixos.
So I installed icu4c
`nix-env -iA nixos.icu4c`

`nix-env -q`
there is `icu4c-59.1`

```
But I still get error message when I `stack exec -- yesod devel`:
    Process exited with code: ExitFailure 1
    Logs have been written to: /root/haskell/test/haskeller/haskellers/.stack-work/logs/text-icu-0.7.0.1.log

    Configuring text-icu-0.7.0.1...
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Missing dependencies on foreign
    libraries:
    * Missing C libraries: icuuc, icui18n, icudata
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
Type help for available commands. Press enter to force a rebuild.
```

### Steps to reproduce
`git clone https://github.com/snoyberg/haskellers.git`
`stack install yesod-bin cabal-install --install-ghc && stack build`
(and I haven't successfully follow the postgres part. So I just skip it.)
`nix-env -iA nixos.icu4c`
`stack exec -- yesod devel`
and get error message above.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.09pre139319.1d9330d63a5 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre139319.1d9330d63a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

---

Does nixos have libicu-dev?

**Comment by jtojnar** [comment]
Sure, it is `icu.dev` but installing it with `nix-env` will not do you much good:

> Don't install libraries through nix-env or systemPackages. See https://nixos.wiki/wiki/FAQ/Libraries for details.

**Comment by YuMingLiao** [comment]
Hi, @jtojnar Thank you very much for point it out!

**Comment by yuuyins** [comment]
@YuMingLiao so how did you get apt to work on nixos? `nix-shell -p apt icu.dev` doesn't fix the issue for me.

**Comment by YuMingLiao** [comment]
@yuuyins It has been a long time. But I do remember I had built haskellers successfully. I had the impression that I had `nix-shell -p apt` then `apt-get install libicu-dev` like in any linux os. No guarantees but you could try.

**Comment by yuuyins** [comment]
@YuMingLiao oh I didn't read the issue properly. I thought your objective was to run apt on NixOS, which is what I'm trying to do. Anyway, thanks for the answer!

**Comment by con-f-use** [comment]
This is the only issue that mentions the apt error `E: Unable to determine a suitable packaging system type`. All those years later it still occurs. Did somebody figure out how to circumvent it and use apt on NixOS?

**Comment by gnubufferoverflows** [comment]
@con-f-use Nope, I am trying to get ICU to work for a C# app image and I keep getting "Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information."

**Comment by jtojnar** [comment]
Not sure about C# but if it just does <code><a href="https://www.man7.org/linux/man-pages/man3/dlopen.3.html">dlopen</a>("libicui18n.so")</code>,  you will either need to do one of the following:
- patch the program to use the full path to the library ([example](https://github.com/NixOS/nixpkgs/blob/63efb7440ad36ef900e351e9575838623f4c3862/pkgs/development/compilers/dotnet/vmr.nix#L264-L267))
- add it to `DT_RUNPATH`[example](https://github.com/NixOS/nixpkgs/blob/63efb7440ad36ef900e351e9575838623f4c3862/pkgs/development/compilers/dotnet/build-dotnet.nix#L127-L132)  (only applicable to ELF programs)
- set `LD_LIBRARY_PATH` at runtime (e.g. [using a wrapper](https://github.com/NixOS/nixpkgs/blob/63efb7440ad36ef900e351e9575838623f4c3862/pkgs/tools/video/recyclarr/default.nix#L66-L68)).
