### ISSUE TITLE
gthumb does not play videos

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#43551]
## Issue description
gthumb is supposed to be able to play videos (the Nix package even has gstreamer in its build inputs), but it doesn't work.

### Steps to reproduce
1. Open gthumb
2. Navigate to a video file
3. Try to play it
4. Fail.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.132646.08d245eb31a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132646.08d245eb31a"`
 - channels(bfo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bjornfor** [comment]
I added gst-plugins-good/bad/ugly to gthumb and rebuilt.

```patch
diff --git a/pkgs/applications/graphics/gthumb/default.nix b/pkgs/applications/graphics/gthumb/default.nix
index 7dc69bceda9..028ffcb6ef0 100644
--- a/pkgs/applications/graphics/gthumb/default.nix
+++ b/pkgs/applications/graphics/gthumb/default.nix
@@ -18,6 +18,9 @@ in stdenv.mkDerivation rec {
 
   buildInputs = with gnome3; [
     glib gtk gsettings-desktop-schemas gst_all_1.gstreamer gst_all_1.gst-plugins-base
+    gst_all_1.gst-plugins-good
+    gst_all_1.gst-plugins-bad
+    gst_all_1.gst-plugins-ugly
     exiv2 libjpeg libtiff libraw libsoup libsecret libchamplain
     librsvg libwebp json-glib webkitgtk lcms2 defaultIconTheme
   ];
```

Tried the same .mp4 video (H.264 - MPEG-4 AVC (part 10)). Now I see media info in gthumb and am able to play/pause the video. But there is only audio, no picture! Totem player (gstreamer based) plays it fine.

**Comment by jtojnar** [comment]
Hmm, not sure why it does not work. Maybe it has something to do with the unending stream of critical errors that get printed in the console. Try asking upstream.

**Comment by Ekleog** [comment]
(triage) @bjornfor, did you try asking upstream? Also, can you upload a test video somewhere (or link to one already uploaded) that triggers the issue so that other people could easily reproduce?

**Comment by bjornfor** [comment]
No, I haven't asked upstream. (Too little time.)

To test:
1. Download short test video: ```$ youtube-dl https://www.youtube.com/watch?v=C0DPdy98e4c```
2. Check that video plays in totem: ```$ totem "TEST VIDEO-C0DPdy98e4c.mkv"```
3. Check that video plays in gthumb (WILL NOT WORK): ```$ gthumb "TEST VIDEO-C0DPdy98e4c.mkv"```

With the patch from https://github.com/NixOS/nixpkgs/issues/43551#issuecomment-405092213 it should play the audio, but still have no picture. (At least that's what it did on release-18.03 branch in july.)

**Comment by doronbehar** [comment]
FYI: https://github.com/NixOS/nixpkgs/pull/84092
