### ISSUE TITLE
Python environment with package collisions

### ISSUE THREAD

**Issue by haposik** [NixOS/nixpkgs#43573]
## Issue description
Is it possible in nix to create a python environment that includes two packages with one pname but different versions? For example I want to have scipy and numpy in my environment, but scipy will have the newest/default version of numpy in propagatedBuildInputs, but in runtime I will see and older version of numpy in my environment.

**Comment by FRidh** [comment]
Nix can technically have multiple versions in one environment, however, Python can't really. Both you and scipy will see the same version of numpy.

**Comment by haposik** [comment]
Actually it allows us to build something like this:
```
with import <nixpkgs> {};

( let
         scipy = pkgs.python36Packages.scipy.overridePythonAttrs(old: rec {
           numpy = default_numpy;

           pname = "scipy";
           version = "0.19.1";
           src = pkgs.python36Packages.fetchPypi {
             inherit pname version;
             sha256 = "a19a2ca7a7336495ec180adeaa0dfdcf41e96dbbee90d51c3ed828ba570884e6";
           };
         });

         default_numpy = pkgs.python36Packages.numpy.overridePythonAttrs(old: rec {

         });


         my_numpy = pkgs.python36Packages.numpy.overridePythonAttrs(old: rec {
           pname = "numpy";
           version = "1.13.3";
           src = pkgs.python36Packages.fetchPypi {
              inherit pname version;
              extension = "zip";
              sha256 = "36ee86d5adbabc4fa2643a073f93d5504bdfed37a149a3a49f4dde259f35a750";
           };
           catchConflicts = false;
         });

  in pkgs.python36.buildEnv.override rec {
    ignoreCollisions = true;
    extraLibs = with pkgs.python36Packages; [ my_numpy scipy ];
}
).env
```
Am I right that scipy uses default_numpy in build-time and my_numpy in runtime? If it's so, I guess it's a very cool feature for python development on nix. I've tested it with changing my_numpy versions and that didn't call any rebuild of scipy. It may be quite useful for playing around with versions of a certain package, not invoking rebuild of the whole project, isn't it?

**Comment by FRidh** [comment]
You'll most likely get a mixture, where some of the compiled code will look into the build-time numpy, and the rest in the run-time numpy. Just use grep to find references. This is asking for trouble.

**Comment by haposik** [comment]
By the way what is kind of dependencies, that pip installs while installing some package? As far as I get they can also be fetched by pip-compile from pip-tools, or by pip show, when a package is installed. Is it synonym to _propagatedBuildInputs_ but without C libraries? or What? Could it be that my_numpy will be considered as that kind of dependency?
