### ISSUE TITLE
build octave with glpk

### ISSUE THREAD

**Issue by nickbeljaev** [NixOS/nixpkgs#43585]
@lsix 
## Issue description
error: glpk: support for GNU Linear Programming Kit was unavailable or disabled when Octave was built

### Steps to reproduce
$ nix-env -iA nixos.octave
$ octave
> glpk ([1;2],[1,2;3,4],[600;800])

I'm tray rebuild octave with add nativeBuildInputs = [ glpk ];
This building but not have effect
If You see way, please tell me

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.51, NixOS, 18.03.132750.91b286c8935 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03"`
 - channels(nick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by lsix** [comment]
Hi @nickbeljaev

By default, octave is built without glpk. To have it, you have to override octave (see [the manual](https://nixos.org/nixpkgs/manual/#sec-modify-via-packageOverrides)), or use `octaveFull`.

If you want to just activate glpk, you could use this in `~/.config/nixpkgs/config.nix`:

```nix
{
  packageOverrides = pkgs: rec {
    octave = pkgs.octave.override { glpk = pkgs.glpk; };
  };
}
```
