### ISSUE TITLE
Updating flatpak breaks already installed flatpaks

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#43581]
## Issue description

When installing flatpaks the current flatpak binary is hardcoded in the application launchers, eg.:
```
/var/lib/flatpak/app/org.kde.krita/current/active/export/bin
❯ cat org.kde.krita 
#!/bin/sh
exec /nix/store/khqdfyd4ddlrssp0wdv8rvx7ry9yy3a8-flatpak-0.99.2/bin/flatpak run --branch=stable --arch=x86_64 org.kde.krita "$@"
```

When flatpak is upgraded (and the old one garbage collect) the launchers stop working due to the dead flatpak path. It's then necessary to reinstall the application to update the launchers.

The code that creates the launchers:
https://github.com/flatpak/flatpak/blob/master/common/flatpak-dir.c#L5470
https://github.com/flatpak/flatpak/blob/master/common/flatpak-dir.c#L6648

Looks like `FLATPAK_BINDIR` is configurable at build time, but not sure where it should point (I'm guessing we can assume flatpak is only useful on NixOS which might make this solvable).

cc @jtojnar  

### Steps to reproduce

1. Install some application using flatpak
2. Update the flatpak derivation (eg. via. nixos-rebuild)
3. Broken packges :cry: 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.6, NixOS, 18.09.git.be979263ece (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(hed): `"unstable-18.03pre126246.a4f433c03cc"`
 - channels(root): `"nixos-17.09.3254.967e40787c5"`
 - nixpkgs: `/home/hed/nixpkgs/channel`

**Comment by jtojnar** [comment]
What a fun thing. I think we cannot solve this any other way than patching the generator to use `/usr/bin/env`. At least for the interactively installed packages, which will be the majority even if we implement the declarative installation (https://github.com/NixOS/nixpkgs/issues/30336).
