### ISSUE TITLE
Add `private` option to `fetchFromGitLab`

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/nixpkgs#43583]
## Issue description

`fetchFromGitHub` has a `private` option, it would be nice if `fetchFromGitLab` did as well.

### Steps to reproduce

Attempt to use `fetchFromGitLab` with a private repo. Experience pain.

**Comment by srghma** [comment]
Currently, I'm using `fetchgitPrivate` (https://www.mpscholten.de/nixos/2016/07/07/private-github-repositories-and-nixos.html)

```
  backend = fetchgitPrivate {
    url    = "ssh://git@gitlab.MY_COMPANY.com:MY_COMPANY_PORT/MY_USERNAME/MY_REPO.git";
    rev    = "XXXXX";
    sha256 = "YYYY";
  };
```


I have makefile

```
copy_gitlab_MY_COMPANY_com_key:
	sudo cp ~/.ssh/id_rsa secrets/gitlab.MY_COMPANY.com/id_rsa
	sudo cp ~/.ssh/id_rsa.pub secrets/gitlab.MY_COMPANY.com/id_rsa.pub
	sudo chown nixbld1:nixbld -R secrets/gitlab.MY_COMPANY.com
	sudo chmod 600 secrets/gitlab.MY_COMPANY.com/*
	sudo chmod 644 secrets/gitlab.MY_COMPANY.com/*.pub
```

I have `shell.nix` with `NIX_PATH`

```
  NIX_PATH = concatStringsSep ":" [
    (let
      sshConfigFile =
        pkgs.writeText "ssh_config" ''
          Host gitlab.MY_COMPANY.com
          IdentityFile ${toString ../secrets/gitlab.MY_COMPANY.com/id_rsa}
          StrictHostKeyChecking=no
        '';
    in
      "ssh-config-file=${sshConfigFile}"
    )
  ];

```

But I dont like that, this approach doenst work with sandbox
_________________________________

It would be better to use `impureEnvVars` to pass gitlab [private token](https://docs.gitlab.com/ee/api/#personal-access-tokens) 

but I can't pass  `impureEnvVars` to builder, nor from current shell, nor from `/nix/configuration.nix` `nix.envVars`

https://github.com/NixOS/nixpkgs/issues/45404

Progress so far https://github.com/srghma/nixpkgs/commit/2e696aac6d4328be1afa5e9bedb9a0d02d423ca4

**Comment by srghma** [comment]
Update:

Instead of the solution above, I'm using `builtins.fetchGit` now, as @symphorien suggested.

And it works perfectly. Repo is downloaded at evaluation time and since it uses git of the current user it uses ssh keys of current user too.

https://github.com/NixOS/nix/blob/475a0a54a9c28c311f0c05d129bb165e7c215efb/src/libexpr/primops/fetchGit.cc#L38-L43

**Comment by aanderse** [comment]
@Fresheyeball I'm also using fetchGit with success on privately hosted GitLab. Please close this issue.

**Comment by spinus** [comment]
Could you guys put few words into the docs so new people could follow that? I found that quite a few people ask me over and over how to solve that issue and each time they are searching long hours over to find proper solution. Maybe we could have quite chapter in docs how to apply that within few minutes?

**Comment by tbenst** [comment]
@srghma found this thread while trying to figure out `fetchGit`. Right now I get `Could not create directory '/var/empty/.ssh'.` :/. Any tips?

**Comment by spinus** [comment]
@tbenst do you use keys or ssh agent?
do you have this error before or after `phases`? If during some phase, you could find some phase and create that directory manually.

**Comment by tbenst** [comment]
@spinus I just have the key in the default location `~/.ssh/id_rsa`, with default permissions. I do not use ssh-agent. I believe the error is happening before phases. 

```
{ lib, buildPythonPackage, fetchgitPrivate, setuptools, fetchgit
}:

buildPythonPackage rec {
  pname = "XXXX";
  version = "XXXX";
  src = fetchgit {
    url = "git@github.com:XXXX/${pname}.git";
    rev  = "XXXX";
    sha256 = "XXXX";
  };

  propagatedBuildInputs = [
    setuptools
  ];

  meta = with lib; {
    homepage = "https://github.com/XXXX";
    maintainers = with maintainers; [ tbenst ];
  };
}
```

**Comment by tbenst** [comment]
Let’s keep this one open

**Comment by srghma** [comment]
@tbenst looking at  https://github.com/NixOS/nixpkgs/issues/43583#issuecomment-509921959

you write

> found this thread while trying to figure out fetchGit. Right now I get `Could not create directory '/var/empty/.ssh'`

but I see in https://github.com/NixOS/nixpkgs/issues/43583#issuecomment-510665973 you are using `fetchgit` function from nixpkgs, it is not the same as `builtins.fetchGit`

As far as I know, You are getting this error, because `fetchgit` function from nixpkgs runs `git` command on behalf of `nixbuildXXX` user, but `builtins.fetchGit` runs `git` command on behalf of your current user, using `git` application from your `$PATH`

**Comment by tbenst** [comment]
Huh, thank you @srghma!! I had no idea about fetchgit vs fetchGit.

I think we should keep open as fetchFromGitLab having a private option is still valid

**Comment by AleXoundOS** [comment]
@srghma, it is related to caching, which is controlled with `tarball-ttl` nix option. There are another issues:
- paths fetched with builtins.fetchGit cannot be substituted from binary cache
- existing store path is not recognized by nix without a supplementing cache entry in ~/.cache/nix/*.sqlite in the absence of which a git clone will happen preventing offline workflow
