### ISSUE TITLE
Go will include windows-only files when compiling

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#43593]
## Issue description
Go will include windows-only files when compiling, and cause this error.

```
# github.com/bakape/hydron
/nix/store/360zh9xvnqzvzvl567b43960fhgq90dw-go-1.10.3/share/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/run/user/1000/go-link-113124839/000000.o: file not recognized: File format is ambiguous
/run/user/1000/go-link-113124839/000000.o: matching formats: coff-x86-64 pe-x86-64
collect2: error: ld returned 1 exit status
```

I have tested on another OS to ensure it wasn't the repo's problem, but instead this is Nix, or Nix's go expression that's the problem. Go will include a windows-only binary icon, and that will cause the above error.

### Steps to reproduce
`go get github.com/bakape/hydron`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.5, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d, nixpkgs-18.09pre146127.98792fe3515"`
 - channels(okina): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
This was fixed at some point.
