### ISSUE TITLE
add systemd unit boundBy option

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#43600]
## Issue description

There should be a boundBy option in modules/system/boot/systemd-unit-options.nix , this is the reverse of bindsTo which is present.

**Comment by peterhoeg** [comment]
Do you want to give a PR a go?

**Comment by andrewchambers** [comment]
sure, I can take care of it.

**Comment by peterhoeg** [comment]
Thanks. Please ping me in the PR.

**Comment by andrewchambers** [comment]
@peterhoeg this was more of a problem than I thought, will need to read some of the systemd docs. The main problem is that the current code uses nix to reverse the condition and then uses symlinks for requires/requiredby. I'll need to check the systemd docs if boundsBy relations can be added via symlinks.

**Comment by peterhoeg** [comment]
Please reopen @andrewchambers if you're still working on this.

**Comment by andrewchambers** [comment]
Sorry, this dropped off my radar, won't be continuing on that.

**Comment by sarcasticadmin** [comment]
I know this has been closed now but just in case someone else wanted to reopen it.

 `BoundBy` cant actually be defined in a unit file. From the [docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Mapping%20of%20unit%20properties%20to%20their%20inverses)
 
> Note: ConsistsOf=, BoundBy=, RequisiteOf=, ConflictedBy= are created implicitly along with their reverses and cannot be specified directly.

**Comment by haras-unicorn** [comment]
if anyone else stumbles upon this

> [@peterhoeg](https://github.com/peterhoeg) this was more of a problem than I thought. The main problem is that the current code uses nix to reverse the condition and then uses symlinks for requires/requiredby. I'll need to check the systemd docs if boundBy bindsTo relations can be added via symlinks.

from `man systemd.unit`

>       Note: WantedBy=, RequiredBy=, and UpheldBy= are used in the [Install] section to create symlinks in .wants/,
       .requires/, and .upholds/ directories. They cannot be used directly as a unit configuration setting.

       Note: ConsistsOf=, BoundBy=, RequisiteOf=, ConflictedBy= are created implicitly along with their reverses and cannot
       be specified directly.

so the main reason it seems is that the latter four options dont go by symlinks
i think this is a "limitation" in systemd so the current options in nixpkgs are to be expected
it s the same reason there are no `consistsOf`, `requisiteOf` and `conflictedBy` options
