### ISSUE TITLE
<nixpkgs-overlays> fails when it points to a file.

### ISSUE THREAD

**Issue by ju1m** [NixOS/nixpkgs#43636]
## Issue description
[Nixpkgs Manual](https://nixos.org/nixpkgs/manual/#sec-overlays-install) says that `<nixpkgs-overlays>` can point to a file, but this fails because nixpkgs fails to detect that a file is given and thus tries to open it as a directory.

### Steps to reproduce
```
% touch /tmp/test.nix
% nix eval -I nixpkgs-overlays=/tmp/test.nix  '(import <nixpkgs> {}).system'
error: opening directory '/tmp/test.nix': Not a directory
```
Because the `isDir` test is not working well:
```
% nix eval -I nixpkgs-overlays=/tmp/test.nix '(<nixpkgs-overlays> + "/.")'
/tmp/test.nix
```
The path is "simplified" and thus this is not `/tmp/test.nix/.`
## Possible fix
```
diff --git a/pkgs/top-level/impure.nix b/pkgs/top-level/impure.nix
--- a/pkgs/top-level/impure.nix
+++ b/pkgs/top-level/impure.nix
@@ -40,7 +40,7 @@ in
   # collections of packages.  These collection of packages are part of the
   # fix-point made by Nixpkgs.
   overlays ? let
-      isDir = path: pathExists (path + "/.");
+      isDir = path: pathExists (toPath path + "/.");
       pathOverlays = try <nixpkgs-overlays> "";
       homeOverlaysFile = homeDir + "/.config/nixpkgs/overlays.nix";
       homeOverlaysDir = homeDir + "/.config/nixpkgs/overlays";
```

## Technical details
`nix-shell -p nix-info --run "nix-info -m"`
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-6-amd64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(julm): `"nixos-1803-18.03.132865.411cc559c05, nixpkgs-18.03"`
 - nixpkgs: `/home/julm/.nix-defexpr/channels/nixpkgs`

**Comment by ryantrinkle** [comment]
I believe this has been fixed
