### ISSUE TITLE
staging can't build any NixOS test VM's? (extra-utils references libidn2 unexpectedly?)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#43650]
## Issue description

In trying to test some PR's I found I was unable to build NixOS test VM targets-- since they all require at least stage1 bits which currently fail to build.

### Steps to reproduce

```console
$  nix build -I testpkgs=https://github.com/NixOS/nixpkgs/archive/dca7b10fd52371548870f7a8aba90c39574ca89e.tar.gz  '(import <testpkgs/nixos/tests/bind.nix>)'
```

(current commit of 'staging')

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.6, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1dtz-mux-ec06e4f`
 - channels(will): `"allvm, nixos-1609-16.09.1943.25f4906da6, unstable-18.09pre144959.be1461fc0ab"`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
`staging` has now been "promoted" to `staging-next` so please target that branch for fixes.

**Comment by dtzWill** [comment]
I think merging master into staging did the trick, not sure which commit.  Looks good now! Thanks! :grin:

**Comment by bkchr** [comment]
Any ideas how we can fix that?

**Comment by dtzWill** [comment]
Yes will be submitting a PR shortly, although it's mostly a workaround until we can properly fix with newer meson.
