### ISSUE TITLE
bazel: builds twice, because cache is not shared

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#43654]
Currently (bazel `0.15.1`), it bootstraps (about 10–20 minutes on laptop hardware) and then the nix expression proceeds to build the bash completions, which start another complete build of the bazel project (same amount of targets, protobuf is rebuilt). This has lead to timeouts with ofborg.

The build cache should be shared between the two builds, and the bash completions might also be done in a different derivation. This might be doable by specifying `--disk-cache` with a cache directory for both builds.

Not very high priority for now. cc maintainer @mboes

**Comment by mboes** [comment]
Is this nixpkgs specific or likely an upstream bug?

**Comment by Profpatsch** [comment]
I suspect the reason is that these two commands don’t share their build cache: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/default.nix#L114-L117

**Comment by Profpatsch** [comment]
Closed in #44097.
