### ISSUE TITLE
Document usage of profiles

### ISSUE THREAD

**Issue by gavinrogers** [NixOS/nixpkgs#43674]
https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/nixos/modules/virtualisation/docker-image.nix#L5

It's not clear to me why it's wrong to include profiles... I was trying to create a custom OS image and reading through example code, was about to use this but I'm curious as to why the comment says we shouldn't? @edolstra 

Also, is there any documentation on this?

**Comment by matthewbauer** [comment]
There are some layers to NixOS that should only depend in one direction. Profiles are supposed to be collection of modules. The order of thingd goes something like this:

Profiles -> Modules -> Packages
