### ISSUE TITLE
Android Studio does not install a desktop file

### ISSUE THREAD

**Issue by IvanMalison** [NixOS/nixpkgs#43688]
@primeos Was this on purpose? Would you mind if I added one?

**Comment by primeos** [comment]
Yes, this wasn't on purpose (I tend to miss such things, as I'm using i3).

If you need an example you can have a look at the [desktop file from the Arch package](https://aur.archlinux.org/cgit/aur.git/tree/android-studio.desktop?h=android-studio):
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Exec=android-studio %f
Icon=android-studio
Comment=The official Android IDE
Categories=Development;IDE;
Terminal=false
StartupNotify=true
StartupWMClass=jetbrains-studio
MimeType=application/x-extension-iml;
```

And you can use the icon from `bin/studio.png`:
```
  # Add the icon and desktop file
  install -Dm644 bin/studio.png $pkgdir/usr/share/pixmaps/$pkgname.png
  install -Dm644 $srcdir/$pkgname.desktop $pkgdir/usr/share/applications/$pkgname.desktop
```

I assume the name of the files should depend on the channel (stable, beta, dev, canary) to avoid collisions. It would probably be the best to pass an additional attribute `channel` to `mkStudio`.

A PR would be very welcome :)

**Comment by IvanMalison** [comment]
> Yes, this wasn't on purpose (I tend to miss such things, as I'm using i3).

I use a tiling wm with no DE as well (xmonad), but it's still useful to have desktop files for things like rofi (provides launcher icons wm class name at startup etc.)
