### ISSUE TITLE
unable to install haskellPackages.greenclip, compilation error.

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#43684]
## Issue description

I'm trying to install `haskellPackages.greenclip` from unstable, but it's failing to compile.

I don't know enough about Haskell to debug it myself.

### Steps to reproduce

```sh-session
$  nix-env -f '<nixpkgs>' -iA haskellPackages.greenclip 
[...]
Preprocessing executable 'greenclip' for greenclip-2.0.1..
Building executable 'greenclip' for greenclip-2.0.1..
[1 of 2] Compiling Clipboard        ( src/Clipboard.hs, dist/build/greenclip/greenclip-tmp/Clipboard.o )

src/Clipboard.hs:51:3: warning: [-Wname-shadowing]
    This binding for ‘waitForEvent’ shadows the existing binding
      imported from ‘Graphics.X11.Xlib’ at src/Clipboard.hs:9:1-24
      (and originally defined in ‘Graphics.X11.Xlib.Event’)
   |  
51 |   waitForEvent display = do
   |   ^^^^^^^^^^^^ 
[2 of 2] Compiling Main             ( src/Main.hs, dist/build/greenclip/greenclip-tmp/Main.o )

src/Main.hs:74:48: error:
    Not in scope: type constructor or class ‘MonadCatch’
   |
74 | runDaemon :: (MonadIO m, MonadReader Config m, MonadCatch m) => m ()
   |                                                ^^^^^^^^^^
   
src/Main.hs:100:27: error:
    Ambiguous occurrence ‘timeout’
    It could refer to either ‘CP.timeout’,
                             imported from ‘ClassyPrelude’ at src/Main.hs:11:1-59
                             (and originally defined in ‘unliftio-0.2.7.0:UnliftIO.Timeout’)
                          or ‘System.Timeout.timeout’,
                             imported from ‘System.Timeout’ at src/Main.hs:21:38-44
    |                        
100 |     getSelectionFrom fn = timeout 1000000 fn <&> T.pack . fromMaybe mempty . join
    |                           ^^^^^^^ 
builder for '/nix/store/z5api0xikckxyknm9p2530rv9h2snmfd-greenclip-2.0.1.drv' failed with exit code 1
error: build of '/nix/store/z5api0xikckxyknm9p2530rv9h2snmfd-greenclip-2.0.1.drv' failed
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.5, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - channels(kalbasit): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
Apparently classy-prelude (https://hackage.haskell.org/package/classy-prelude) reexports UnliftIO, which apparently has its own timeout function: https://hackage.haskell.org/package/unliftio-0.2.4.0/docs/UnliftIO-Timeout.html

The fix is to override it to use a pinned classy-prelude at 1.3.1, which I don't know how to do (Ping @peti)

If you really wanna get it working, you can use an older nixpkgs version, specifically e4d49bcabc8389c34d43f6d4f6bde4be3b5d6ba3 will work

**Comment by peti** [comment]
Please report this issue upstream to @erebe so that he can release a new version of `greenclip` that builds successfully.

**Comment by kalbasit** [comment]
@peti v3 was released back in February, and I just noticed the build is using v2.0.1. Maybe we need to update the pkg here?

**Comment by peti** [comment]
2.0.1 is the latest version: http://hackage.haskell.org/package/greenclip

**Comment by kalbasit** [comment]
Oh /facepalm

I was looking on Github. Thx @peti, I'll follow up upstream.

**Comment by kalbasit** [comment]
@peti @erebe has pushed greenclip 3.1 which dependencies are fixed with ghc843. How frequently do the hackagePackages get updated? Can you trigger an update?

**Comment by teto** [comment]
note that the latest greenclip doesn't work either since it has a (new ?) dependency on  https://gitlab.freedesktop.org/xorg/lib/libxdmcp
