### ISSUE TITLE
Document GTK3 app dependencies

### ISSUE THREAD

**Issue by VShell** [NixOS/nixpkgs#4369]
GTK3 apps require at least gnome3.gnome_icon_theme to be installed into either the system, default, or user profile. This should, at the least, be documented somewhere, and potentially should be installed by default in NixOS with X11 enabled, or a wrapper should be created so that all GTK3 apps in nixpkgs are launched with GTK environment variables pointing into this package.

Where the theme is searched for depends on $XDG_DATA_DIRS.

**Comment by jtojnar** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/issues/16285
