### ISSUE TITLE
Eagle heavily outdated

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#43695]
## Issue description
Eagle is version 7.7.0, while the latest is 9.1.0. I tried fixing it myself ([expression](https://hastebin.com/qikiwaqofe.nix)), but I got an OpenGL error I couldn't fix. It runs with `steam-run-native`; perhaps it's best to use an FHS env?

### Steps to reproduce
Install Eagle(, run it as freeware), watch it tell you that it's out of date.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by rittelle** [comment]
I stumbled across the same problem and also tried fixing the expression myself.
With [this](https://gist.github.com/rittelle/ba54ea900f0a9497b0edca116ce13dec) I am running into a locale related error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```
The epression from above results in the same error.

If we upgrade eagle here, I'd consider providing the old `eagle` package as an `eagle7` if someone dose not want to upgrade to the versions after Cadsoft got acquired by Autodesk as they require you to create an account.

Maybe @bjornfor can help here?

**Comment by bjornfor** [comment]
+1 for keeping an eagle7 attribute. I'm afraid I can not help much with updaring to the latest version.

**Comment by rittelle** [comment]
This can be closed now as the Eagle (9) has landed (in master).

**Comment by bjornfor** [comment]
Ref. 9e4d2d723abbe76e02945e45d4024ad91d9bc63c.
