### ISSUE TITLE
Kubernetes: possible missing dependency

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#43708]
## Issue description

I've just enabled the default kubernetes services with:
```nix
   services.kubernetes.roles = [ "master" "node" ];
```
in `configuration.nix` on a new machine using unstable.
I've had a look at the log and I spotted the following line:
```
lug 18 02:05:03 ender.lan kube-addons[8483]: /nix/store/62fqqskmfgiihzq772rsx3d3bl60z6ph-kubernetes-1.10.5/bin/.kube-addons-wrapped: line 158: awk: command not found
```
### Steps to reproduce

Enable Kubernetes on unstable and add the configuration as described above. 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.5, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - channels(azazel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @srhb
cc @johanot

**Comment by johanot** [comment]
Confirmed. I have seen this a couple of times too.

Just haven't gotten around fixing it yet.
