### ISSUE TITLE
Prebuilt lxc/lxd images of nixos?

### ISSUE THREAD

**Issue by evelant** [NixOS/nixpkgs#43781]
I can't find much information about running nixos in an lxc container. Are there any images for nixos such as those found on https://us.images.linuxcontainers.org/ ? Would it be difficult to create and list an image there?

**Comment by samueldr** [comment]
Hi, #9735 has some discussion as to the past situation of LXC images of nixos.

Earlier this year I wrote [this hacky walkthrough](https://nixos.wiki/wiki/Proxmox_Linux_Container) to get an LXC container of NixOS going in Proxmox.

As far as distributing images *elsewhere*, it's kind of a hassle, just as our iso images aren't distributed and mirrored at many locations. This is because every time the nixos release updates, a new iso image (and container images) have been built for that new update. It would need a constant feed of not-that-long-lived images.

And as far as support? I don't know if the issues I had with `nixos-rebuild` were specific to how Proxmox works, but it works, if one were to disregard the warnings and errors on rebuild.

**Comment by asbachb** [comment]
I guess the most convenient way for now would be that hydra builds that image. This could be easily imported via `lxc import`.

**Comment by nathan-at-least** [comment]
This issue is not stale for me, a new-comer to nixos. I use lxd images for development and prototyping, so it would be my primary platform for a nixos installation.

**Comment by NULLx76** [comment]
I'm also still interested in using NixOS inside of LXC containers as the overhead compared to VMs is that much lower. A variety of issues I encountered are also mentioned in #9735

**Comment by mberry** [comment]
> I tried to get generating NixOS in distrobuilder

Could you post your distrobuilder yaml config? I was hoping to give this a try

**Comment by asbachb** [comment]
@mberry I don't think I still have it. Even if I find it it's not in a state of being used.

Your best chance of getting it to work you'll find here: https://discourse.nixos.org/t/running-nixos-18-09-in-an-lxd-3-8-container/1804

But I'm not sure it's still working tbh.

**Comment by adamcstephens** [comment]
There are hydra jobs that can be used to import a new image:
* https://hydra.nixos.org/job/nixos/release-22.05/nixos.lxdImage.x86_64-linux
* https://hydra.nixos.org/job/nixos/release-22.05/nixos.lxdMeta.x86_64-linux

I believe `security.nesting: true` is required, and you'll have to manually configure the container for now.

The distrobuilder config requires more work to get going. [matthewbauer has made an attempt](https://github.com/matthewbauer/distrobuilder/tree/add-nixos-support), and [so have I](https://github.com/lxc/distrobuilder/compare/master...adamcstephens:distrobuilder:nixos?expand=1). Neither are complete.

**Comment by asbachb** [comment]
This should work without `security.nesting: true`: 
```
lxc profile show nixos
```
```
config:
  raw.lxc: |-
    lxc.init.cmd = /sbin/init
    lxc.mount.entry = proc mnt/proc proc create=dir 0 0
    lxc.apparmor.profile = unconfined
```

**Comment by adamcstephens** [comment]
The container images have been renamed and VM images have been added, for both aarch64 and x86_64.

Container images should have `security.nesting: true` set

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdContainerImage.x86_64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdContainerMeta.x86_64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdContainerImage.aarch64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdContainerMeta.aarch64-linux

Virtual machines should have `security.secureboot: false` set

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdVirtualMachineImage.x86_64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdVirtualMachineImageMeta.x86_64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdVirtualMachineImage.aarch64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdVirtualMachineImageMeta.aarch64-linux

### custom images

You can also build your own images by importing the relevant LXD module (lxc-container or lxd-virtual-machine) and then building the necessary outputs.

#### container

import `modules/virtualisation/lxc-container.nix` and build `config.system.build.tarball` for the root tarball and `config.system.build.metadata` for the metadata

#### virtual-machine

import `modules/virtualisation/lxd-virtual-machine.nix` and build `config.system.build.qemuImage` for the root qcow2 image and `config.system.build.metadata` for the metadata
