### ISSUE TITLE
Nix commands randomly giving "error: opening file '[': No such file or directory"

### ISSUE THREAD

**Issue by mightybyte** [NixOS/nixpkgs#43796]
## Issue description

When I enable nix.sshServe in my `configuration.nix`, I start getting the following error:

    error: opening file '[': No such file or directory

I get this error when I run `nixos-rebuild switch` and also when I do `nix-env -i ...`.

### Steps to reproduce

Add the following to `configuration.nix`:

```
    nix.sshServe = {
      enable = true;
      keys = [
        "ssh-rsa ..."
      ];
    };
```

Then run `nixos-rebuild switch`.

Now run `nix-env -i ripgrep` (or some other package that you haven't installed)
Alternatively you could make another innocuous change to `configuration.nix` and you should get the same error when you do `nixos-rebuild switch`.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131792.becbe4dbe16 (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ckauhaus** [comment]
I'm not able to reproduce this problem on a recent 18.03 system (18.03.132821.56fad146a12).

Please verify that the problem is still present in recent builds.

If yes: please try to locate where in the activation script (?) the error message comes from.

**Comment by mightybyte** [comment]
Hmmm, starting from scratch with a fresh instance on the same NixOS version I was using before made the problem go away.  Closing, but wish I knew what was up.

**Comment by mightybyte** [comment]
Well, this issue came up again.  The new AWS instance that I mentioned in the above comment that didn't have the problem started having the problem after awhile.  I'm pretty sure that just about the only thing I did on the instance was edit `/etc/nixos/configuration.nix` and add more items to the `nix.sshServe.keys` list mentioned in the above config block.

I'm not exactly sure what a guaranteed steps to reproduce would be, but add a key, run `nixos-rebuild switch`, wash, rinse repeat a small number of times should do it.

**Comment by ckauhaus** [comment]
Do you have the possbility to run your instance on a locally modified nixpkgs checkout? 

If yes: it would be helpful to include shell tracing in the activation script. This means: insert a `set -vx` in nixos/modules/system/activation/activation-script.nix around line 77 and wait for the error to occur. Then save the output and attach it to the ticket. This would help other devs to spot the error.

If no: then we have to come up with another approach. :-)

**Comment by mightybyte** [comment]
Ok, I've got that change here: https://github.com/mightybyte/nixpkgs/commit/d501824bc1c26f706654588161d11575a22e27e9

How do I set my instance to use that modified version of the script?

**Comment by ckauhaus** [comment]
It depends on your deployment. Somehow <nixpkgs> has to point to the modified nixpkgs checkout.

**Comment by Ericson2314** [comment]
Seeing that this also occurs with `nix-env`, I think it's a Nix rather than NixOS issue. Something to do with buildenv, or even the `/bin/sh` impurities. I don't know much but hear Nix comes with some busybox things relating to `/bin/sh`. Maybe they did something POSIX-violating like remove the `[` executable because it was a shell builtin.

**Comment by mightybyte** [comment]
Yes, like I mentioned above the same problem occurs with both `nix-env` and with `nixos-rebuild`.  @ckauhaus does you `set -vx` suggestion above still apply?

**Comment by ckauhaus** [comment]
@mightybyte `set -vx` is a debugging tool that helps to locate the error. It may well be possible the the culprit is not in the activation script. `set -vx` gives you a trace of recently executed commands in order to spot the error site. A next try could be to instrument other scripts. 

@Ericson2314 Is it possible for you to drill down further? I am still not able to reproduce the error, so the detective work should be performed by the people who can.

buildEnv is not a likely candidate since it consists only of Nix and Perl code - no shell involved.

**Comment by mightybyte** [comment]
Now I'm starting to see this happen randomly for no apparent reason, and having nothing to do with `nix.sshServe`.  Still haven't been able to test with `set -vx` because I'm not sure how to do that on NixOS.

**Comment by mightybyte** [comment]
Finally isolated this to the following line in my `nix.conf` file:

```
secret-key-files = [ "/root/nix-cache-key.sec" ];
```

Bracket list syntax is not allowed in nix.conf.
