### ISSUE TITLE
Need to prevent a service with startAt from being started on configuration switch

### ISSUE THREAD

**Issue by bcc32** [NixOS/nixpkgs#43821]
## Issue description

I wrote a systemd service with a `startAt` attribute intended to be run hourly.  I only want it to run each hour, but when I run `nixos-rebuild switch` (even without touching any configuration options), the service is started (script gets run).  I need the script not to run when that happens, because it performs potentially-destructive operations.

I already tried `stopIfChanged = false` and `restartIfChanged = false`, but the service is started anyway.  I also tried adding and removing `wantedBy = [ "multi-user.target" ];`

### Steps to reproduce

Add the following service to configuration.nix:

```
  systemd.services.btrfs-snap =
    let subvol = "/mnt/pool/@${config.networking.hostName}/media"; in
    {
      startAt = "hourly";
      unitConfig = {
        RequiresMountsFor = subvol;
      };
      path = with pkgs;
        [
          btrfs-progs
          perl
        ];
      restartIfChanged = false;
      script = "/etc/admin/snap.pl ${subvol}";
      stopIfChanged = false;
      wantedBy = [ "multi-user.target" ];
    };
```

Run `sudo nixos-rebuild switch`—

```
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
setting up tmpfiles
the following new units were started: btrfs-snap.service
```

If I run `sudo nixos-rebuild switch` again, I get the same output, and `btrfs-snap.service` is run again.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.03.132865.411cc559c05 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132865.411cc559c05"`
 - channels(aaron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by bcc32** [comment]
I looked through the configuration options for `systemd.services.<name>` and I couldn't find anything else I thought would work.  If there is already an option for such a service to avoid being started except when the timer specifies, I wasn't able to find it.

**Comment by Infinisil** [comment]
How about using a systemd timer unit? Basic example: https://gist.github.com/Infinisil/e8c341eaf81e84df113265247164cc53

**Comment by bcc32** [comment]
I thought using `startAt` was supposed to be equivalent to creating a timer myself.

I think I found my problem though—somehow the link between my version-controlled configuration and the real one got broken.... d'oh! 🤦‍♂️
