### ISSUE TITLE
Document `allowUnfreePredicate` in NixPkgs manual

### ISSUE THREAD

**Issue by silverhook** [NixOS/nixpkgs#4389]
As requested in (and around):

https://github.com/NixOS/nixpkgs/issues/2188#issuecomment-57944606

I’m opening a new issue in order for the NixOS manual to be extended to include how `allowUnfree` and `allowUnfreePredicate` should be used.

Currently the manual only states how to enable `allowUnfree` for all packages, but completely omits the existence of `allowUnfreePredicate`. Adding the latter to the manual, would be very useful for anyone who might want more control over which unfree packages there are on their system and/or NixOS in general.

**Comment by matthiasbeyer** [comment]
I want to do this, (feel free to assign me,) if you can tell me where this documentation has to be located. It is not in `./doc` in this repo, is it?

**Comment by iElectric** [comment]
yes in `doc/` as part of stdenv documentation

**Comment by matthiasbeyer** [comment]
Really? There is no documentation about the `allowUnfree` feature at all in there... I think it belongs to the documentation of this feature, so it should be placed near that, right?

Actually there is no documentation in `./doc` about `allowUnfree`:

```bash
$ grep -rni allowUnfree ./doc/
$
```

**Comment by iElectric** [comment]
Yeah. You get error message explaining to set allowUnfree.

**Comment by matthiasbeyer** [comment]
Yes I know, I'm currently working on patches related to this (what brought me to this issue, actually). I just thought there would be any documentation for `allowUnfree` already, but if there is none I will add it, of course.

---

I will start this tomorrow, thought. Need some sleep now.

**Comment by vcunat** [comment]
@matthiasbeyer: github doesn't allow to assign you (perhaps it's limited to organization members).

**Comment by iElectric** [comment]
Done in #5953
