### ISSUE TITLE
hhvm doesn't build

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#43911]
## Issue description
hhvm doesn't build on current master.

Here's a build log: https://ptpb.pw/9W2z

### Steps to reproduce
I did a git clone of master that is on commit a8f2d1f92c955a3a4bc1dc7a4588983d9c918fc6 and then ran `nix-build -A hhvm`.

**Comment by aanderse** [comment]
@etu given hhvm is marked as broken can this issue be closed?

**Comment by etu** [comment]
@aanderse Sure
