### ISSUE TITLE
Bazel with rules_typescript does not work

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#43955]
## Issue description

I'm trying to use Bazel with a project that uses rules_typescript, but it's failing because it's not able to find `uname`, `tr`, and `grep`. It looks like it's not finding coreutils which indicate that it's not using the [custom bash](https://github.com/NixOS/nixpkgs/blob/0d8076b99cce5c6638abeb28153c42f698e1bc18/pkgs/development/tools/build-managers/bazel/default.nix#L52-L75), of course it's an assumption but I'll have to debug further to confirm it.

### Steps to reproduce

```sh-session
$ git clone --branch=test-bazel https://github.com/kalbasit/nixpkgs.git
$ cd nixpkgs/pkgs/test/bazel
$ nix-shell -p bazel go nodejs --run 'bazel build //rules_typescript:hello'
INFO: Analysed target //rules_typescript:hello (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/kalbasit/code/opensource/stories/test-bazel/src/github.com/NixOS/nixpkgs/pkgs/test/bazel/rules_typescript/BUILD.bazel:3:1: Compiling TypeScript (devmode) //rules_typescript:hello failed (Exit 1)
bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/bazel_tools/tools/bash/runfiles/runfiles.bash: line 60: uname: command not found
bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/bazel_tools/tools/bash/runfiles/runfiles.bash: line 60: tr: command not found
failed to load main  Error: ENOENT: no such file or directory, open '/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/sandbox/processwrapper-sandbox/1/execroot/nix_test/external/root_node_modules/node_modules/typescript/lib/lib.es5.d.ts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at UncachedFileLoader.loadFile (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/execroot/nix_test/external/build_bazel_rules_typescript/internal/tsc_wrapped/file_cache.ts:276:27)
    at /home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/execroot/nix_test/external/build_bazel_rules_typescript/internal/tsc_wrapped/compiler_host.ts:345:34
    at Object.wrap (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/execroot/nix_test/external/build_bazel_rules_typescript/internal/tsc_wrapped/perf_trace.ts:54:12)
    at CompilerHost.getSourceFile (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/execroot/nix_test/external/build_bazel_rules_typescript/internal/tsc_wrapped/compiler_host.ts:344:22)
    at findSourceFile (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/typescript/lib/typescript.js:75050:29)
    at args (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/typescript/lib/typescript.js:74987:85)
    at getSourceFileFromReferenceWorker (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/typescript/lib/typescript.js:74960:34)
    at processSourceFile (/home/kalbasit/.cache/bazel/_bazel_kalbasit/61aa1d2a671723c542d4a1c85ce4fd35/external/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/typescript/lib/typescript.js:74987:13)
Target //rules_typescript:hello failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.748s, Critical Path: 0.39s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

- system: `"x86_64-linux"`
 - host os: `Linux 4.17.8, NixOS, 18.09.git.7ffed91faf7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - channels(kalbasit): `"nixos-18.09pre145679.dae9cf6106d"`
 - nixpkgs: `/home/kalbasit/code/personal/base/src/github.com/kalbasit/system/external/nixpkgs`

cc @mboes @Profpatsch

**Comment by kalbasit** [comment]
@mboes any idea why this is happening?

**Comment by mboes** [comment]
The action that runs `tsc_wrapped_bin` probably needs to be patched to set `use_default_shell_env = True`.

**Comment by kalbasit** [comment]
@mboes looking at the [docs](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#action), this requires patching `rules_typesscript`, right? Can we do anything here instead of filing an upstream patch?

**Comment by kalbasit** [comment]
@mboes the following patch to `rules_typescript` worked, I will submit the patch upstream but I'm unsure if they will merge it.

```diff
diff --git a/internal/build_defs.bzl b/internal/build_defs.bzl
index ee3b32d..f3a01c2 100644
--- a/internal/build_defs.bzl
+++ b/internal/build_defs.bzl
@@ -74,6 +74,7 @@ def _compile_action(ctx, inputs, outputs, tsconfig_file, node_opts, description
         execution_requirements = {
             "supports-workers": str(int(ctx.attr.supports_workers)),
         },
+        use_default_shell_env = True,
     )

     # Enable the replay_params in case an aspect needs to re-build this library.
```

**Comment by mboes** [comment]
We could patch the runfiles.bash file. That one comes from Bazel, not rules_typescript, and it's arguably the correct thing to hardcode absolute paths in that file.

`use_default_shell_env = True` is scary, because it potentially hurts hermeticity, except when using `--experimental_strict_action_env` (which is slated to become the future in the next few releases of Bazel). So I guess patching `runfiles.bash` is the better long-term fix.

**Comment by mboes** [comment]
> We could patch the runfiles.bash file. It's arguably the correct thing to hardcode absolute paths in that file (or equivalently, hardcode `PATH` in that script).

@Profpatsch could you file a followup ticket about this and assign it to yourself?

**Comment by kalbasit** [comment]
@mboes I agree. I filed a [PR upstream](https://github.com/bazelbuild/rules_typescript/pull/235) but I doubt it will go through. But since `runfiles.bash` is used by many rules, we should probably patch it instead.

**Comment by kalbasit** [comment]
@mboes @Profpatsch with the above PR, Bazel works with rules_typescript unchanged.
