### ISSUE TITLE
libblockdev errors in journal

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#43989]
When I run new VM with `services.udisks2.enable = true`, I see the following error in the journal:

```
Jul 22 23:43:01 nixos udisksd[1102]: udisks daemon version 2.7.6 starting
Jul 22 23:43:01 nixos udisksd[1102]: Failed to load config files: Failed to get contents of the config dir (/etc/libblockdev/conf.d/)Error opening directory “/etc/libblockdev/conf.d/”: No such file or directory. Using the built-in config
```

We probably need either `environment.etc."libblockdev/conf.d/00-default.cfg".source = "${pkgs.libblockdev}/etc/libblockdev/conf.d/00-default.cfg";` or hardcode the path to the default config to the source code.

nixpkgs: dae9cf6106da19f79a39714f183ed253c62b32c5

**Comment by dtzWill** [comment]
(FWIW I'm seeing the same thing)

**Comment by bricewge** [comment]
The default path is defined [here](https://github.com/storaged-project/libblockdev/blob/e9229edfc454e76cb52fc14be0cddff7daf4b85c/src/lib/blockdev.c.in#L46) and used [there](https://github.com/storaged-project/libblockdev/blob/e9229edfc454e76cb52fc14be0cddff7daf4b85c/src/lib/blockdev.c.in#L106-L115).

**Comment by fishhead108** [comment]
Still relevant

**Comment by ParetoOptimalDev** [comment]
I'm affected by this.

I'm assuming maybe this doesn't break anything because the built-in config is used per the expanded message:

```
Aug 14 16:04:50 udisksd[54289]: Failed to load config files: Failed to get contents of the config dir (/etc/libblockdev/conf.d/)Error opening directory “/etc/libblockdev/conf.d/”: No such file or directory. Using the built-in config
```

Maybe this can be closed then?
