### ISSUE TITLE
Optcomp (and probably other camlp4 users) does not compile with ocaml 4.02

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#4398]
At least the package ocamlPackages.ocaml_optcomp does not compile with ocaml 4.02 . This is due to its build system searching for "-I +camlp4/Camlp4Parsers" ie, camlp4 within the compiler's directory. I'm not sure where in the buildsystem stack it gets generated (optcomp itself, oasis, ocamlbuild, …) and I suspect other packages are affected.

**Comment by Profpatsch** [comment]
Can be closed @jagajaga
