### ISSUE TITLE
NIX_CFLAGS_LINK doesn't have any effect anymore

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#43994]
## Issue description

This must have gone missing after some refactoring projects. We should either restore it or remove references to it.

**Comment by dezgeg** [comment]
I guess we need a testsuite for these kinds of things...

**Comment by matthewbauer** [comment]
Oops I guess it is still there. I was looking in the wrong place.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/cc-wrapper/add-flags.sh#L9
