### ISSUE TITLE
Errors with hashes for Node packages

### ISSUE THREAD

**Issue by ariutta** [NixOS/nixpkgs#44002]
## Issue description

Errors with hashes for Node packages:

> error: while evaluating the attribute ‘src’ of the derivation ‘node-node2nix-1.6.0’ at /nix/store/isv56cmyf2v2y3r89mpsr3yklr4kyhgr-stable-18.03.132915.d6c6c7fcec6/stable/pkgs/stdenv/generic/make-derivation.nix:148:11:
hash ‘MJY6SsQH3pN59R9N3nMz/L8BsbQ0DlvSF38mgg1fwfwgnaJ+y600s3Nd0vZ+cnETUH+4OPETc4QohflccjPUYw==’ has wrong length for hash type ‘sha512’

This applies to `https://nixos.org/channels/nixos-18.03` but not to `https://nixos.org/channels/nixos-17.09`. It may apply to `https://nixos.org/channels/nixpkgs-unstable`.

### Steps to reproduce

Install a Node package like `node-node2nix-1.6.0` using channel `https://nixos.org/channels/nixos-18.03`. I also got this error for `eslint` and `prettier`.

## Technical details

`nix-shell -p nix-info --run "nix-info -m"` yields:

> - system: `"x86_64-darwin"`
> - host os: `Darwin 16.7.0, macOS 10.12.6`
> - multi-user?: `yes`
> - sandbox: `no`
> - version: `nix-env (Nix) 1.11.16`
> - channels(andersriutta): `"stable-18.03.132915.d6c6c7fcec6, nixpkgs-18.09pre146471.d7d31fea7e7, unstable-18.09pre146471.d7d31fea7e7, nixos-17.09.3263.9e1d8b74706"`
> - channels(root): `"nixpkgs-18.03pre122585.b212125b541"`
> - nixpkgs: `/Users/andersriutta/.nix-defexpr/channels/nixpkgs`

ping @svanderburg

**Comment by svanderburg** [comment]
@ariutta This happens because node2nix 1.6.0 generates sha512 hashes in base64 format. Nix 2.0 and higher support base64 hashes, but it's not supported by any Nix 1.11.x versions.

You must either upgrade Nix to 2.0 or downgrade node2nix to 1.5.3.

**Comment by ariutta** [comment]
Thanks!

Is it better to rely on nix-channels instead of specifying versions like `1.5.3` or `1.6.0`?

If yes, it's easy to keep channels and `nix-env` in sync for a NixOS system: just use the preset `nixpkgs` channel.

But for Darwin or Ubuntu using Nix pkgs, it's a little more tricky. For these systems, I think `nixpkgs` tracks `https://nixos.org/channels/nixpkgs-unstable`. **If I update my channels, `nix-env` and `node2nix` will get out of sync.** So I need to use a channel corresponding to my version of `nix-env`  (for version `1.11.16`, it'd be `https://nixos.org/channels/nixos-17.09`). Then I must tell any node packages to use the nixos channel, e.g., `nixos.nodePackages.node2nix` and `nixos.nodePackages.eslint`.

**Comment by matthewbauer** [comment]
@svanderburg That is very bad if it is broken in Nix 1.11. That version is still officially supported in Nixpkgs. Is there a technical reason for not using the sha256 hashes?

**Comment by prusnak** [comment]
I guess this is not an issue anymore. If I am mistaken, please reopen.
