### ISSUE TITLE
Latest neomutt is unable to send email

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#44018]
## Issue description

The latest neomutt as introduced in 2ee14993255 is unable to send emails. With ```sendmail = path_to_msmtp_wrapper_script```, nothing happens when sending. The script is simply never called. Reverting that commit makes everything OK again.

@cstrahan @erikryb @jfrankenau @vrthra

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.4, NixOS, 18.09.git.ad8aa1afa76M (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`

**Comment by jfrankenau** [comment]
Does it work if your script is in PATH and you call it by its name instead of an absolute path? If so this could be caused by neomutt/neomutt@4c95290dc425770cf95f1dd72730a81e47f29a51. However the man page still has absolute paths in the examples, so I'm not sure.
