### ISSUE TITLE
NixOS hangs on shutdown

### ISSUE THREAD

**Issue by nulluminare** [NixOS/nixpkgs#44021]
## Issue description
OS hangs on shutdown forever. 
Same result for `shutdown` and `poweroff` 
The only way to turn the machine off is to press and hold power key.

Result of `poweroff` (few last messages) :
```
[ OK ] Reached target Unmount All Filesystems.
       Starting mdadm-shutdown.service…
[ OK ] Reached target Final Step. 
       Starting Power-Off...
```
Result of `shutdown now` (few last messages) :
```
[ OK ] Reached target Unmount All Filesystems.
       Starting mdadm-shutdown.service…
[ OK ] Reached target Final Step.
       Starting Power-Off...
[ OK ] Started mdadm-shutdown.service.
```
Nothing happens for about 10 minutes, I just press and hold power key. 
Result of `journalctl -n 10 -b -1` after `poweroff`:
```
systemd[1]: Deactivated swap /dev/disk/by-uuid/c1cadba7-8393-4a2c-bdcb-011b854775a4.
systemd[1]: Reached target Unmount All Filesystems.
systemd[1]: Reached target Final Step.
systemd[1]: Starting mdadm-shutdown.service…
systemd[1]: Shutting down.
kernel: systemd-shutdow: 36 output lines suppressed due to ratelimiting
systemd-shutdown[1]: Syncing filesystems and block devices.
systemd-shutdown[1]: Sending SIGTERM to remaining processes...
systemd-journald[399]: Journal stopped 
```

However `halt` works fine:
```
[ OK ] Reached target Final Step.
       Starting Halt...
[ OK ] Started mdadm-shutdown.service.
[24.191204] reboot: System halted
```
Rebooting with `reboot` turns everything off but after bootloader screen (with configuration options) nothing happens (black screen).

### Steps to reproduce
Install NixOS with default configure.nix 
Try `shutdown` or `poweroff`

## Technical details
```
system:          x86_64-linux
host os:         Linux 4.14.52, NixOS, 18.03.132797.0a70d65fd47 (Impala)
multi-user?:     no
sandbox:         yes
version:         nix-env (Nix) 2.0.4
nixpkgs:         /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```
Machine: old Acer Aspire 5560

**Comment by nulluminare** [comment]
@ikervagyok  thank you, I dodn't know about that. Also `systemctl hibernate` worked fine.
Turns out in my case problem was caused by BIOS/UEFI on my machine. It cannot handle GPT layout with some distributions properly.

**Comment by praduca** [comment]
This is marked as closed, but my system does the same, and it is a server (HP proliant DL360 g7).
It worked well until i upgraded to 19.3, so this (if caused by the same factor) is definitely not an BIOS issue...

**Comment by praduca** [comment]
The problem continues and i have confirmed that it is a nixos thing... I installed ubuntu and it works. I will upgrade to 19.09 to see if the problem is solved...

**Comment by praduca** [comment]
Today I upgraded my system to 19.09 and installed ubuntu as dual boot... same issue on nixOS, ubuntu reboots... Ubuntu doesn't do it smoothly although. I'm not really sure if Ubuntu is hacking something for this to work or this behaviour is expected...
Should I open a new bug report or we shoud reopen this one?

**Comment by saggzz** [comment]
Fresh installed nixos 19.09 with encrypted root. I am not able to shut down/restart. Could this be a problem of ```grub.boot.loader``` (2.02)?

**Comment by grische** [comment]
Same happening on NixOS 20.03, using Grub as well.

**Comment by praduca** [comment]
Hi, i just noticed that this is a problem with the video card (acpi with nva8 to be more specific).
Don't really expect it to be solved (it's upstream i guess and have been this way for some time now, apparently)
