### ISSUE TITLE
Hydra version is 8 months old.

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#44044]
The version of Hydra tracked in nixpkgs is 8 months behind Hydra master. Considering Hydra doesn't have a discrete release model, it seems nixpkgs ought to be rolling with `master` at least somewhat promptly. Is there a reason that it is so out of date, or does someone just need to send a PR bumping it?

**Comment by Ma27** [comment]
@FRidh I have a private Hydra and the module seems to work fine. However I’d be interested in an upgrade (and a release model 😅), so I’d give a bump a try next week:)

**Comment by Ma27** [comment]
FYI I just started working on the bump, I'll try keep this channel update :)
