### ISSUE TITLE
Separate, auto-updatable branch for unstable releases

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#4404]
I would like to have separate auto-updatable branch for unstable releases. We would need it for auto updatable docker builds on https://hub.docker.com/. Triggering rebuilds on every commit would be just too much. This would be also very usefull for builds of private projects on private hydra instances.

**Comment by vcunat** [comment]
Now we have https://github.com/NixOS/nixpkgs-channels/branches, so I think your use case is solved.
