### ISSUE TITLE
kicad fails to build

### ISSUE THREAD

**Issue by nek0** [NixOS/nixpkgs#44087]
## Issue description

Kicad build fails with an error from CMake:

```
CMake Error at CMakeModules/CheckCXXSymbolExists.cmake:41 (_CHECK_SYMBOL_EXISTS):
  Unknown CMake command "_CHECK_SYMBOL_EXISTS".
Call Stack (most recent call first):
  CMakeModules/PerformFeatureChecks.cmake:86 (check_cxx_symbol_exists)
  CMakeLists.txt:141 (perform_feature_checks)
```

### Steps to reproduce

invoke `nix-env -iA nixos.kicad`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.56, NixOS, 18.09pre146471.d7d31fea7e7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d, nixpkgs-18.09pre146471.d7d31fea7e7"`
 - channels(nek0): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by nek0** [comment]
can @viric or anybody else look into this and maybe even update kicad to version 5.0.0?

**Comment by coretemp** [comment]
@nek0 See https://lists.launchpad.net/kicad-developers/msg35240.html

**Comment by bgamari** [comment]
I have opened #44122 bumping Kicad to 5.0.0.

**Comment by brodul** [comment]
Workaround:
I have build kicad from  `90c01001396` one commit before  `cmake` was upgraded. Works fine.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/44122
