### ISSUE TITLE
Clang wrapper depends unnecessarily on gcc

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#4411]
In its builder, there's a command saying "Need libgcc until the llvm compiler-rt library is complete". It's from @shlevy in 2011, so I'm inclined to think it's out of date and that the dependency on gcc is spurious. Is that true?

**Comment by grahamc** [comment]
This story is quite old, is this still true?

**Comment by Profpatsch** [comment]
Closing because no reaction.
