### ISSUE TITLE
Distribute `nixos-rebuild` with non-nixos nix distribution

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixpkgs#44135]
I'm currently working on a web app project that is deployed to a NixOS server. Our deployment consists of running `nixos-rebuild --target-host` to push things to the server.

The problem is, `nixos-rebuild` is only available on NixOS proper, not on the standalone nix distribution. I had to deal with some grumpy people when I explained that they needed to get themselves a NixOS VM in order to run deployments.

I don't think there's anything preventing at least the `--target-host` part of `nix-rebuild` being available as part of the standard nix distribution.

**Comment by yegortimoshenko** [comment]
I think that at the very least we should expose it at top-level.

**Comment by srhb** [comment]
If it's interesting to you, `nixos` was recently exposed as a top level attribute, so you could do `nix-build -E 'let pkgs = import <nixpkgs> {}; in (pkgs.nixos {}).nixos-rebuild'`

**Comment by Mic92** [comment]
nix-shell version:

```
 nix-shell -E 'with import <nixpkgs> {}; stdenv.mkDerivation { name = "foo"; buildInputs = [ (nixos {}).nixos-rebuild ]; }'
```

**Comment by mkaito** [comment]
This does the job:

```
#!/usr/bin/env bash

nix-shell -E 'with import <nixpkgs> {}; stdenv.mkDerivation { name = "foo"; buildInputs = [ (nixos {}).nixos-rebuild ]; }' --run "nixos-rebuild $*"
```

Drop it in a file `nixos-rebuild`, put on path, done. Thanks @Mic92 !

**Comment by Mic92** [comment]
It can be even simplified:

```console
$ nix-shell -p '(nixos{}).nixos-rebuild'
```

**Comment by Mic92** [comment]
I backported d9f1e37ec72f0b4d55ef8d8f24aa4fc499fe878c:

Now you can do: 

```
$ nix-shell -p 'nixos-rebuild'
```

This will be part of the upcoming release 18.09.

**Comment by Mic92** [comment]
Makes sense. I was not aware of that. I also backported the revert: 51b62e6a8c9

However:

```
nix-shell -p '(nixos{}).nixos-rebuild'
```

should be easy enough.

**Comment by adrian-gierakowski** [comment]
@mkaito @Mic92 is this still working for you? 

when I run:
```
env NIXOS_CONFIG=$(pwd)/configuration.nix nix-shell -p '(nixos{}).nixos-rebuild' --run 'nixos-rebuild switch --target-host $MY_HOST'
```

I get the following error:
```
/nix/store/17843hfbsnyqxkjx6v7sdrln855npyll-nixos-rebuild/bin/nixos-rebuild: line 268: systemctl: command not found
building Nix...
unix_listener: path "/var/folders/dm/3dxc156d67l5241z0y2tt8h80000gn/T/nixos-rebuild.FS9L0q/ssh-130.211.114.86.iLXNmuqNiJwgmhy5" too long for Unix domain socket
/nix/store/17843hfbsnyqxkjx6v7sdrln855npyll-nixos-rebuild/bin/nixos-rebuild: line 343: /var/folders/dm/3dxc156d67l5241z0y2tt8h80000gn/T/nixos-rebuild.FS9L0q/nix/bin/nix-instantiate: cannot execute binary file: Exec format error
building the system configuration...
/nix/store/17843hfbsnyqxkjx6v7sdrln855npyll-nixos-rebuild/bin/nixos-rebuild: line 181: /var/folders/dm/3dxc156d67l5241z0y2tt8h80000gn/T/nixos-rebuild.FS9L0q/nix/bin/nix-instantiate: cannot execute binary file: Exec format error
```

looks to me like it might be similar to: https://github.com/NixOS/hydra/pull/641

**Comment by mkaito** [comment]
Currently using this:

```bash
nix-shell -E "with import <nixpkgs> {}; mkShell { buildInputs = [ (nixos {}).nixos-rebuild ]; }" --run "nixos-rebuild $*"
```

And yes, it works.

**Comment by Mic92** [comment]
> @mkaito @Mic92 is this still working for you?
> 
> when I run:
> 
> ```
> env NIXOS_CONFIG=$(pwd)/configuration.nix nix-shell -p '(nixos{}).nixos-rebuild' --run 'nixos-rebuild switch --target-host $MY_HOST'
> ```
> 
> I get the following error:
> 
> ```
> /nix/store/17843hfbsnyqxkjx6v7sdrln855npyll-nixos-rebuild/bin/nixos-rebuild: line 268: systemctl: command not found
> building Nix...
> unix_listener: path "/var/folders/dm/3dxc156d67l5241z0y2tt8h80000gn/T/nixos-rebuild.FS9L0q/ssh-130.211.114.86.iLXNmuqNiJwgmhy5" too long for Unix domain socket
> /nix/store/17843hfbsnyqxkjx6v7sdrln855npyll-nixos-rebuild/bin/nixos-rebuild: line 343: /var/folders/dm/3dxc156d67l5241z0y2tt8h80000gn/T/nixos-rebuild.FS9L0q/nix/bin/nix-instantiate: cannot execute binary file: Exec format error
> building the system configuration...
> /nix/store/17843hfbsnyqxkjx6v7sdrln855npyll-nixos-rebuild/bin/nixos-rebuild: line 181: /var/folders/dm/3dxc156d67l5241z0y2tt8h80000gn/T/nixos-rebuild.FS9L0q/nix/bin/nix-instantiate: cannot execute binary file: Exec format error
> ```
> 
> looks to me like it might be similar to: [NixOS/hydra#641](https://github.com/NixOS/hydra/pull/641)

I never tested this on non-Linux targets. This might require some other flags. Adding `--no-build-nix` might help.

**Comment by Mic92** [comment]
I think we gave enough work-arounds on how to achieve this.

**Comment by mkaito** [comment]
Well, that's a shame, but such is life.

**Comment by Mic92** [comment]
Sorry but apparently bringing nixos modules into all-packages scope apparently makes nix evaluation a lot slower. There are people who want to use nix on machines with little RAM. I don't think its too much to ask to use one of one-liners posted above. If you are interested in improving the situation consider making them more visible by adding them to the manual or the nixos wiki.

**Comment by kevincox** [comment]
It seems like bringing nixos into scope was a side effect of how it was implemented. Wouldn't it be possible to move nixos-rebuild into a regular nixpkgs package and reference that from nixos?

(On another note does anyone know how to install it using nix-env instead of nix-shell? I can't get it to work)

**Comment by Mic92** [comment]
> It seems like bringing nixos into scope was a side effect of how it was implemented. Wouldn't it be possible to move nixos-rebuild into a regular nixpkgs package and reference that from nixos?
> 
> (~On another note does anyone know how to install it using nix-env instead of nix-shell? I can't get it to work~ `nix-env -i -E 'e: ((e.nixpkgs {}).nixos{}).nixos-rebuild'`)

Yes. `nix-env` also works.
