### ISSUE TITLE
Nixos fail to boot on Raspberry pi 1 with Kernel Panic

### ISSUE THREAD

**Issue by Tomahna** [NixOS/nixpkgs#44184]
## Issue description
When trying to set up nixos on a raspberry pi 1 following instructions from https://nixos.wiki/wiki/NixOS_on_ARM, the boot process fail with a kernel panic.

The error seems to be:
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

### Steps to reproduce
Download https://www.cs.helsinki.fi/u/tmtynkky/nixos-arm/installer/sd-image-armv6l-linux.img
dd it on a sd card
try to boot

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by dezgeg** [comment]
I can't reproduce the problem. Which raspi model is this and how was the image copied to the card?

**Comment by Tomahna** [comment]
It's a Raspberry Pi Model B+ V1.2. 
I copied with a ```sudo dd if=sd-image-armv6l-linux.img of=/dev/sdc```
The image I copied to the card has f7647fe4bfec9801b1a7ac96bd319a331f2500e5a3cb06bdcca6690882d7c4b3 for sha256.

**Comment by dezgeg** [comment]
There's now a new version up at https://www.cs.helsinki.fi/u/tmtynkky/nixos-arm/installer/sd-image-armv6l-linux.img. It fixed the boot on that model for me.

**Comment by devhell** [comment]
Awesone! Thanks @dezgeg, I'll check it out as soon as possible and will report back.

**Comment by Tomahna** [comment]
I confirm that I can boot with the new image. Awesome, Thank you !

**Comment by devhell** [comment]
Can confirm too, thank you!

**Comment by dezgeg** [comment]
Good to hear. I'm not sure what actually was the cause/solution but there were various packaged updated like the kernel, firmware, U-Boot so presumably one of those.
