### ISSUE TITLE
reportlab is broken on current master

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#44204]
## Issue description

`nixos-rebuild test` is failing with the current master (at 1750e105ddfde799c2ac84aa037101a3eb31897f)

```
----------------------------------------------------------------------
Ran 268 tests in 23.185s

FAILED (errors=3, skipped=2)
builder for '/nix/store/awkp8lszcyxfn1p85h3pgrih5kcxc8xw-python2.7-reportlab-3.5.2.drv' failed with exit code 1
cannot build derivation '/nix/store/14k1jl9g0x0r5jsml09rgsl3zpjpmdkk-hplip-3.18.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/94wng2vs22zp69xk21akh97fdkf7kdx9-cups-progs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xi8miqnybw4kxnnaxylhndgssg48z4h8-cups-files.conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pl07szsc5df6cgjqdsi3bril19sd40zp-cups-progs.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/zafwj7qk78crhc2cb7lv3q6phq61rgxw-unit-script.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/n3jk0kkdfnkslb5d3mhlhj5fnys69m72-unit-cups.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6q4zzdjafxl1rf4cxnp3srk8fq6hb1xb-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/y0y1d7wcvd8bwwz874rn4z0sipvd65b3-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/75is1vqma9d109i6hw6qcjj23kksn0qb-nixos-system-hades-18.09.git.e46e7f44c22.drv': 1 dependencies couldn't be built
error: build of '/nix/store/75is1vqma9d109i6hw6qcjj23kksn0qb-nixos-system-hades-18.09.git.e46e7f44c22.drv' failed
```

The full log can be found [here](https://gist.github.com/kalbasit/85ef9de3b4238dbe9e354027e5a532b5)

When I reverted both 7babc81b07a7d24c61b1d42c212e7fb478ad32c1 and c53d60809649ad4a799acf343b921a2241075c27 it worked.

### Steps to reproduce

```sh-session
$ nixos-rebuild test
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.8, NixOS, 18.09.git.b64d3bb058a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - channels(kalbasit): `"nixos-18.09pre145679.dae9cf6106d"`
 - nixpkgs: `/code/personal/base/src/github.com/kalbasit/system/external/nixpkgs`

cc @FRidh

**Comment by FRidh** [comment]
Seems like the tests need fixing. I suggest you open a PR if you like to have this working.

**Comment by kalbasit** [comment]
@FRidh does `nix-build` the package work for you? I'm just wondering how it got to master if it's broken.

**Comment by kalbasit** [comment]
the tests seem to be working [upstream](https://bitbucket.org/rptlab/reportlab/commits/branch/default). I don't use it myself (probably a dependency of one my packages), but it's best to figure out what's wrong and fix it than to remove the tests.

**Comment by eadwu** [comment]
Looks like the problem of being unable to download the required files (`fopen`) for testing?

**Comment by kalbasit** [comment]
@FRidh can we revert back to version 3.4.0 until we can fix this?

**Comment by FRidh** [comment]
The update will be applied again on the next batch, which is beginning of next month, at which point we stabilize the package set for 18.09. Therefore, I would rather not and would actually like to see some activity from those that are interested in this package.
