### ISSUE TITLE
python36Packages.rlp fails to build

### ISSUE THREAD

**Issue by nek0** [NixOS/nixpkgs#44224]
## Issue description

Above mentioned package fails to build wiith following error:

```
Processing ./rlp-1.0.1-py2.py3-none-any.whl
Collecting eth-utils<2,>=1.0.2 (from rlp==1.0.1)
  Could not find a version that satisfies the requirement eth-utils<2,>=1.0.2 (from rlp==1.0.1) (from versions: )
No matching distribution found for eth-utils<2,>=1.0.2 (from rlp==1.0.1)
builder for '/nix/store/259lk8n561lxni9j6vpiwpcxlhiifdv9-python3.6-rlp-1.0.1.drv' failed with exit code 1
```

### Steps to reproduce

run `nix-env -iA nixos.python36Packages.trezor`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.56, NixOS, 18.09pre146471.d7d31fea7e7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d, nixpkgs-18.09pre147646.408bd2b80ed"`
 - channels(nek0): `""`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by nek0** [comment]
@np can you have a look at this?

**Comment by dotlambda** [comment]
Seems like `eth-utils` is not yet packaged in nixpkgs. It would be best to create a PR that adds that to nixpkgs and updates the expression for `python3Packages.rlp`.
Btw, last time `rlp` was updated to 1.0.1, it was first marked as broken in e00ddc62b2737304ade27d04da5a5d5751ae9ae6 by @FRidh and then reverted to 0.6.0 in 367a7ae138b55193d4ddea60940d01f2b10a5cb0 by @Profpatsch. However, packaging the new dependency is preferable.

**Comment by dotlambda** [comment]
I've began packaging the new dependencies over at https://github.com/dotlambda/nixpkgs/commits/fix-rlp.
However, I have no interest in running useless calculations on my graphics card so I'm not going to continue work on this. I hope someone of @nek0 @deepfire @gebner @Profpatsch finishes this.

**Comment by Enzime** [comment]
I'm not sure if `pypandoc` actually does not work with `pandoc>=2`.

From what I can tell, it looks to me like the Arch `python-pypandoc` package uses `pandoc>=2` however I have not tested that this package actually works: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-pypandoc

Also looking at the code for `pypandoc` it appears to be downloading `pandoc>=2`, so I'm guessing it might actually work with `pandoc>=2` to some degree:

https://github.com/bebraw/pypandoc/blob/master/pypandoc/pandoc_download.py#L24-L41

This is the error I get after adding `doCheck = false;` and letting it build `pypandoc`, when other libraries attempt to actually use `pypandoc`.

```
Traceback (most recent call last):
  File "/nix/store/ylybfm2wdy4npsiryzpn1vbpv3fagyix-python3.6-setuptools-markdown-0.2/lib/python3.6/site-packages/setuptools_markdown.py", line 22, in long_description_markdown_filename
    output = pypandoc.convert(markdown_filename, 'rst')
  File "/nix/store/yzm46clpxbdyc7drcmyn9grmg2wiqpzd-python3.6-pypandoc-1.4/lib/python3.6/site-packages/pypandoc/__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "/nix/store/yzm46clpxbdyc7drcmyn9grmg2wiqpzd-python3.6-pypandoc-1.4/lib/python3.6/site-packages/pypandoc/__init__.py", line 260, in _convert_input
    _ensure_pandoc_path()
  File "/nix/store/yzm46clpxbdyc7drcmyn9grmg2wiqpzd-python3.6-pypandoc-1.4/lib/python3.6/site-packages/pypandoc/__init__.py", line 544, in _ensure_pandoc_path
    raise OSError("No pandoc was found: either install pandoc and add it\n"
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.
```
