### ISSUE TITLE
hplipWithPlugin: ppdc not found

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44230]
## Issue description
I expect all of these to not return "No such file or directory" and I expect the "bad interpreter" to be patched.

I think it still "works", but compilation output should be clean such that when debugging something in the future there is not first a mess of other warnings to go through.

Multiple issues:

```
ppdc: Unable to find include file "<font.defs>" on line 261 of prnt/drv/hpcups.drv.
gzip: ppd/hpcups/*.ppd: No such file or directory
ppdc: Unable to find include file "<font.defs>" on line 60 of prnt/drv/hpijs.drv.
gzip: ppd/hpijs/*.ppd: No such file or directory
./createPPD.sh: ./hpijs-drv: /usr/bin/perl: bad interpreter: No such file or directory
./configure: line 16070: test: too many arguments
```

### Steps to reproduce
```
  services.printing = {
      enable = true;
      drivers = [ pkgs.hplipWithPlugin ];
  };
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.git.6115f47 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xeji** [comment]
cc maintainers @jgeerds @ttuegel

**Comment by ttuegel** [comment]
The build currently complains that `ppdc` is missing:

```
./createPPD.sh: line 82: ppdc: command not found
gzip: ppd/hpcups/*.ppd: No such file or directory
./createPPD.sh: line 88: ppdc: command not found
gzip: ppd/hpijs/*.ppd: No such file or directory
```

This program comes from `cups`; I believe `hplip` needs `cups` in `nativeBuildInputs`.

**Comment by ttuegel** [comment]
As above, I think this is just a matter of adding the right `nativeBuildInputs`.
