### ISSUE TITLE
BroadBand (Service prvider) info not available from network manager (modem/lte/gsm)

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#44253]
## Issue description

Cannot change APN in Network Manager

### Steps to reproduce

When I open Network Manager (from try) -> Edit Connection -> Select GSM connection -> Broadband connection tab -> API (field) -> Change (button) nothing happens.

In modem manager logs nothing happens.
In network manager logs:
```
Jul 31 07:46:40 zeppelin xsession[4274]: ** (nm-connection-editor:21957): WARNING **: 09:46:40.673: Cannot create mobile providers database: Could not read '/nix/store/fdpin1j7fffgpa06x30gkybqawk2hdk2-network-manager-applet-1.8.10/share/mobile-broadband-provider-info/serviceproviders.xml': No such file or directory
```
However serviceproviders.xml is in ``/nix/store/kv6r8h89ph0vmnjzbhfdxpn8p11g934m-mobile-broadband-provider-info-20151214/share/mobile-broadband-provider-info/serviceproviders.xml``
Looks like path to that file is not bound properly.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - channels(spinus): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Looks like this got broken when the package was switched to meson in https://github.com/NixOS/nixpkgs/pull/43087. The following change would fix it:

```patch
--- a/pkgs/tools/networking/network-manager/applet.nix
+++ b/pkgs/tools/networking/network-manager/applet.nix
@@ -43,8 +43,8 @@
     hicolor-icon-theme
   ];
 
-  NIX_CFLAGS = [
-    ''-DMOBILE_BROADBAND_PROVIDER_INFO=\"${mobile-broadband-provider-info}/share/mobile-broadband-provider-info/serviceproviders.xml\"''
+  NIX_CFLAGS_COMPILE = [
+    ''-DMOBILE_BROADBAND_PROVIDER_INFO="${mobile-broadband-provider-info}/share/mobile-broadband-provider-info/serviceproviders.xml"''
   ];
 
   postPatch = ''
```

However, this will not work in the newer nm-applet versions due to the following upstream change:
 https://gitlab.gnome.org/GNOME/network-manager-applet/commit/1f6331b2192eff72e4209eb063f244adcf3f0a5b. Opened an upstream issue: https://gitlab.gnome.org/GNOME/network-manager-applet/issues/14

**Comment by jtojnar** [comment]
I opened a merge request that will fix that: https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/18

**Comment by spinus** [comment]
@jtojnar thank you very much for that work! Great stuff with applet fix, cheers :-)
