### ISSUE TITLE
Package duplicate dependencies and overriding nixpkgs pkgs

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#44255]
I found that when attempting to build a complex Python application where itself and its dependencies uses matplotlib, it is possible to get this problem:

```
Found duplicated packages in closure for dependency 'matplotlib':
  matplotlib 2.1.2 (/nix/store/38fz59rmqxq1l43y0k2v40d36vv6hr5w-python3.6-matplotlib-2.1.2/lib/python3.6/site-packages)
  matplotlib 2.1.2 (/nix/store/bcrnikk3vfsl7vxzgvhjnlw7rlc72kkj-python3.6-matplotlib-2.1.2/lib/python3.6/site-packages)

Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
```

The main reason is when you use:

```
matplotlib.override { enableQt = true; }
```

In your `propagatedBuildInputs`.
The problem is that your dependencies may rely on the default `pkgs.matplotlib`, whereas your top level package may actually expect to use the `qt` backend.

I found that the solution to this was to create an override at the `nixpkgs` level:

```
  let
    pkgs = (import <nixpkgs>) {
      config = {
        packageOverrides = pkgs: {
          python36 = pkgs.python36.override {
            packageOverrides = self: super: {
              matplotlib = super.matplotlib.override { enableQt = true; };
            };
          };
        };
      };
    };
  in
    with pkgs;
```

From there, every subsequent expression will reuse the same `pkgs`, and all packages will be using the overridden matplotlib.

My question here is, is this way that's expected to work? Is there no better way to do this? It seems overly verbose to achieve this. Furthermore, this requires you to have the `nixpkgs` function, instead of the `pkgs` attribute. I could not find a way to override the `pkgs` attribute instead of passing it as a the `config` attribute to the `nixpkgs` function.

**Comment by CMCDragonkai** [comment]
This PR seems related: https://github.com/NixOS/nixpkgs/pull/44196

**Comment by FRidh** [comment]
> I found that when attempting to build a complex Python application where itself and its dependencies uses matplotlib, it is possible to get this problem:

What does the dependency tree look like?

> The problem is that your dependencies may rely on the default `pkgs.matplotlib`, whereas your top level package may actually expect to use the `qt` backend.

Right, that's quite common and why we put this check in here, just to make sure you don't accidentally end up with multiple versions in a closure. Python doesn't support multiple versions of a package, so one should indeed override the value for the *whole* package set.

> My question here is, is this way that's expected to work? Is there no better way to do this? 

Almost. This is documented in the Nixpkgs manual, so I am not going to repeat it here. 

> It seems overly verbose to achieve this. 

Yes, it is. Maybe it will get better with https://github.com/NixOS/nixpkgs/pull/44196.

**Comment by CMCDragonkai** [comment]
@FRidh thanks for the response.

I did find that PR.

Just regarding you saying there is an almost better way to do it, are you referring to:

```nix
  let
    pkgs_ = pkgs // {
      config = pkgs.config // {
        packageOverrides = pkgs: {
          python36 = pkgs.python36.override {
            packageOverrides = self: super: {
              matplotlib = super.matplotlib.override { enableQt = true; };
            };
          };
        };
      };
    };
  in
    with pkgs_;
```

Because I find that my `default.nix` takes a `pkgs` instead of the `nixpkgs` function, and I wanted to override the `pkgs` without having to reapply the `nixpkgs` function.

**Comment by CMCDragonkai** [comment]
Oh that method doesn't actually work.

I can't find a way to override the package set, when I already have the package set.

**Comment by CMCDragonkai** [comment]
I found that you can use `pkgs.path`. This was not recommended due to double imports. But appears to be the only way to propagate pkgs itself.
