### ISSUE TITLE
Keras broken with commit aaf4d12

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#44274]
## Issue description

@FRidh seem the Keras preprocessing routines were split off into their own package in 2.0.

The Nix version was then updated to 2.0 in commit aaf4d125ef55b596595ba7ff9ac6a07afd453e94 without verifying that it worked.  This broke the package as it is now necessary to also package the new `keras-preprocessing` package and provide it as a dependency to `keras`

### Steps to reproduce

```
...
Processing ./Keras-2.2.0-py2-none-any.whl
Requirement already satisfied: pyyaml in /nix/store/8lac5rzgwn3kp1vijmpykl6gc56fic2d-python2.7-PyYAML-3.13/lib/python2.7/site-packages (from Keras==2.2.0) (3.13)
Collecting keras-preprocessing==1.0.1 (from Keras==2.2.0)
  Could not find a version that satisfies the requirement keras-preprocessing==1.0.1 (from Keras==2.2.0) (from versions: )
No matching distribution found for keras-preprocessing==1.0.1 (from Keras==2.2.0)
builder for '/nix/store/s0cb3f99xvkbwlkjwscp9rbwbxajnx47-python2.7-Keras-2.2.0.drv' failed with exit code 1
```

https://hydra.nixos.org/build/78808924

**Comment by dotlambda** [comment]
We do semi-automatic batch upgrades to the Python packages because not all of them are well maintained. This also means we cannot fix all breakage that occurs during these batch upgrades, however we try to fix as much as possible.
If you have the time, please package the new dependency and make a pull request.

**Comment by twhitehead** [comment]
@dotlambda Thanks for taking care of that.
