### ISSUE TITLE
add custom certificates to firefox

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#44291]
## Issue description

I was recently given certificates to install in my browser (firefox). I managed to install the certificate manually but is there a way to automate that via nix ? My first idea was to look at the firefox wrapper but I am not sure what's the correct process to add a user certificate store to firefox, if there is any, if one should hack around or if installing it manually is just simpler.

I found that link  https://wiki.mozilla.org/CA:AddRootToFirefox

**Comment by kalbasit** [comment]
That article mentions [autoconfig.js](https://wiki.mozilla.org/CA:AddRootToFirefox#AutoConfig_via_JavaScript) as a possible solution, and this is doable. The article was last modified a year ago, so you should probably test it with the new firefox.

I am however concerned that this could be a security issue on a multi-seat system. One user could force another user to accept a certificate, so maybe this is more suited in [home-manager](https://github.com/rycee/home-manager)?

**Comment by teto** [comment]
thanks for the answer. Anyway my certificate asks for a password on install so it might be hard to automate. As it's not of great importance to me, I prefer to close issue.

**Comment by kalbasit** [comment]
@teto can you close it? :)

**Comment by teto** [comment]
arf right xD
