### ISSUE TITLE
Export buildRPackage

### ISSUE THREAD

**Issue by mnacamura** [NixOS/nixpkgs#44290]
## Issue description

I often make a local R package and use it with nix. To do this, every time I have to do something like
```
let
  buildRPackage = callPackage <nixpkgs/pkgs/development/r-modules/generic-builder.nix> {
    inherit (darwin.apple_sdk.frameworks) Cocoa Foundation;
  };
in
buildRPackage {
  name = "foo";
  src = ./.;
  ...
}
```

So I think it is convenient if `buildRPackage` in `pkgs/development/r-modules/default.nix` is exported.

**Comment by florianjacob** [comment]
For the next one finding this issue and wondering how to actually *use* the now exported `buildRPackages`, this nix code exemplarily shows how to install the patchwork package directly from github sourcess:

```nix
(pkgs.rWrapper.override {
  packages = with pkgs.rPackages; let
    patchwork = buildRPackage {
      name = "patchwork";
      src = pkgs.fetchFromGitHub {
        owner = "thomasp85";
        repo = "patchwork";
        rev = "fd7958bae3e7a1e30237c751952e412a0a1d1242";
        sha256 = "00fq520xwy1ysg4k8x48x9b0yy9wyi8y8zj6dvxjg4bwx0yyp6s4";
      };
      propagatedBuildInputs = [ ggplot2 ];
      nativeBuildInputs = [ ggplot2 ];
    };
  in [
    ggplot2
    patchwork
  ];
})
```
(not sure about `propagatedBuildInputs` / `nativeBuildInputs`, thas is copied from https://github.com/NixOS/nixpkgs/blob/7fcfbcdbc9646c74ee8e5da766217bbd56612d5b/pkgs/development/r-modules/default.nix#L33)
