### ISSUE TITLE
dwm configuration file

### ISSUE THREAD

**Issue by nulluminare** [NixOS/nixpkgs#44300]
## Issue description
I'm installing some software from [suckless.org](https://suckless.org/) and I want to include patches in configuration.nix and use custom configuration files (config.h). There are `conf` and `patches` variables in simple terminal [package](https://github.com/NixOS/nixpkgs/blob/aec217852f228fd6f923c0d32b94d78dee4ae5dc/pkgs/applications/misc/st/default.nix), so I can configure this package using `packageOverrides`. However [dwm](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/nixos/modules/services/x11/window-managers/dwm.nix) and [surf](https://github.com/NixOS/nixpkgs/blob/0fadb81af44fe7f43581a276d2ca863bdb64dd67/pkgs/applications/networking/browsers/surf/default.nix) packages include only `patches` variables. Is there a good way to use custom `config.h` files with this packages? For now I use `diff` tool with `config.def.h` and custom `config.h` to create patch with my custom settings and include it in patches variable. I think this is not the best way to do it.

**Comment by eadwu** [comment]
I just use a fork which I then set as the src in an overlay.

**Comment by nulluminare** [comment]
@eadwu, seems like the best solution for now. Thanks.
