### ISSUE TITLE
haskellPackages.sexpr: fails to build on Darwin

### ISSUE THREAD

**Issue by ariutta** [NixOS/nixpkgs#44324]
## Issue description

`haskellPackages.sexpr` fails to build on Darwin.

### Steps to reproduce

```
nix-env -iA nixos.haskellPackages.sexpr
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(andersriutta): `"nixos-17.09.3263.9e1d8b74706, nixpkgs-18.09pre146471.d7d31fea7e7"`
 - channels(root): `"nixpkgs-18.03pre122585.b212125b541"`
 - nixpkgs: `/Users/andersriutta/.nix-defexpr/channels/nixpkgs`

## Full build log

> building path(s) ‘/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1’, ‘/nix/store/ys2vz9a1vp3r93c0mrrw3nk55rz6qx5k-sexpr-0.2.1-doc’
setupCompilerEnvironmentPhase
Build with /nix/store/gcf25x8hdxby8pvzmcrpd9bhy8pqjq5w-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/vqwws99ymc3v2qpjrfp97z2mq54f9zp5-sexpr-0.2.1.tar.gz
source root is sexpr-0.2.1
setting SOURCE_DATE_EPOCH to timestamp 1241045466 of file sexpr-0.2.1/sexpr.cabal
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/tmp/nix-build-sexpr-0.2.1.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /private/tmp/nix-build-sexpr-0.2.1.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/ys2vz9a1vp3r93c0mrrw3nk55rz6qx5k-sexpr-0.2.1-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-sexpr-0.2.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --extra-include-dirs=/nix/store/ifqjyzz2paal834dj3kaxairjkhcnfg6-libc++-4.0.1/include --extra-lib-dirs=/nix/store/ifqjyzz2paal834dj3kaxairjkhcnfg6-libc++-4.0.1/lib
Configuring sexpr-0.2.1...
Flags chosen: testing=False
Dependency base -any: using base-4.9.1.0
Dependency base64-string -any: using base64-string-0.2
Dependency binary -any: using binary-0.8.3.0
Dependency bytestring -any: using bytestring-0.10.8.1
Dependency pretty -any: using pretty-1.1.3.3
Using Cabal-1.24.2.0 compiled by ghc-8.0
Using compiler: ghc-8.0.2
Using install prefix: /nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1
Binaries installed in:
/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1/bin
Libraries installed in:
/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1/lib/ghc-8.0.2/sexpr-0.2.1
Dynamic libraries installed in:
/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1/lib/ghc-8.0.2/x86_64-osx-ghc-8.0.2
Private binaries installed in:
/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1/libexec
Data files installed in:
/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1/share/x86_64-osx-ghc-8.0.2/sexpr-0.2.1
Documentation installed in:
/nix/store/ys2vz9a1vp3r93c0mrrw3nk55rz6qx5k-sexpr-0.2.1-doc/share/doc
Configuration files installed in:
/nix/store/14hnc5q71hn35hyswi7lgcfw0c79112r-sexpr-0.2.1/etc
No alex found
Using ar found on system at:
/nix/store/hx4n5nzjy21482vmfg43ykhjy8wvz4af-cctools-binutils-darwin/bin/ar
No c2hs found
No cpphs found
Using gcc version 4.2.1 given by user at:
/nix/store/dpdkysb9mj09c0ajcyjhvjrqp79xy824-clang-wrapper-4.0.1/bin/clang
Using ghc version 8.0.2 found on system at:
/nix/store/gcf25x8hdxby8pvzmcrpd9bhy8pqjq5w-ghc-8.0.2/bin/ghc
Using ghc-pkg version 8.0.2 found on system at:
/nix/store/gcf25x8hdxby8pvzmcrpd9bhy8pqjq5w-ghc-8.0.2/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.17.3 found on system at:
/nix/store/gcf25x8hdxby8pvzmcrpd9bhy8pqjq5w-ghc-8.0.2/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/gcf25x8hdxby8pvzmcrpd9bhy8pqjq5w-ghc-8.0.2/bin/hpc
Using hsc2hs version 0.68.1 found on system at:
/nix/store/gcf25x8hdxby8pvzmcrpd9bhy8pqjq5w-ghc-8.0.2/bin/hsc2hs
Using hscolour version 1.24 found on system at:
/nix/store/2771c35v6pkkwcg2ip7i5a43nnslkiml-hscolour-1.24.2/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/dpdkysb9mj09c0ajcyjhvjrqp79xy824-clang-wrapper-4.0.1/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip found on system at:
/nix/store/hx4n5nzjy21482vmfg43ykhjy8wvz4af-cctools-binutils-darwin/bin/strip
Using tar found on system at:
/nix/store/1d61rvl2vz19xrf6h5dazxks1wnpb2rg-gnutar-1.29/bin/tar
No uhc found
building
Building sexpr-0.2.1...
Preprocessing library sexpr-0.2.1...
>
> Codec/Sexpr/Printer.hs:1:33: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[1 of 4] Compiling Codec.Sexpr.Internal ( Codec/Sexpr/Internal.hs, dist/build/Codec/Sexpr/Internal.o )
>
> Codec/Sexpr/Internal.hs:29:1: error:
    Failed to load interface for ‘Test.QuickCheck’
    Use -v to see a list of the files searched for.
builder for ‘/nix/store/fqy54w9i3p08rga2li4da9sh92bib8lz-sexpr-0.2.1.drv’ failed with exit code 1
error: build of ‘/nix/store/fqy54w9i3p08rga2li4da9sh92bib8lz-sexpr-0.2.1.drv’ failed

**Comment by basvandijk** [comment]
`sexpr` is old, broken and has no issue-tracker. [I did manage to fix it](https://github.com/NixOS/nixpkgs/commit/3328ea77492edff2aed1827fb435ecceb68e430d).
