### ISSUE TITLE
upgrade systemd to 239

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#44338]
systemd 239 was released on Jun 22. Would be nice to upgrade before we fork off 18.09.

**Comment by jfrankenau** [comment]
@Mic92 has already opened a PR at NixOS/systemd#21.

**Comment by Mic92** [comment]
I am finished with the pull request. I will add it to nixpkgs, once my changes are merged into the fork.

**Comment by Mic92** [comment]
systemd is now in staging: https://github.com/NixOS/nixpkgs/pull/44451

**Comment by xeji** [comment]
Great, thanks! Let's keep this issue open until it hits master.

**Comment by flokli** [comment]
it's in master now, and did hit unstable channels too if I'm not mistaken.

**Comment by globin** [comment]
Not yet released to the channel, but on master which is enough to close this! :beers:
