### ISSUE TITLE
Please also check the log file at "/dev/null" for additional information.

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#44348]
## Issue description

My X server crashed during rebuild (https://github.com/NixOS/nixpkgs/issues/44344). While analyzing the situation, i found this funny, but not very helpful message.

Maybe there should actually be a log? Or do we have it in journal and the message is just broken and upstream has to fix it?

```
gdm-x-session[1473]: (EE) 19: /nix/store/5c0r5ysrx8w9c4mxr2mqpb8c69s34psz-xorg-server-1.19.6/bin/X (_start+0x2a) [0x4241ba]
gdm-x-session[1473]: (EE)
gdm-x-session[1473]: Fatal server error:
gdm-x-session[1473]: (EE) Caught signal 6 (Aborted). Server aborting
gdm-x-session[1473]: (EE)
gdm-x-session[1473]: Please consult the The X.Org Foundation support
gdm-x-session[1473]:          at http://wiki.x.org
gdm-x-session[1473]:  for help.
gdm-x-session[1473]: (EE) Please also check the log file at "/dev/null" for additional information.
...
gdm-x-session[4014]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
gdm-x-session[4014]: _XSERVTransMakeAllCOTSServerListeners: server already running
gdm-x-session[4014]: (--) Log file renamed from "/dev/null" to "/dev/null"
gdm-x-session[4014]: X.Org X Server 1.19.6
gdm-x-session[4014]: Release Date: 2017-12-20
gdm-x-session[4014]: X Protocol Version 11, Revision 0
gdm-x-session[4014]: Build Operating System: Linux 4.9.97 x86_64
gdm-x-session[4014]: Current Operating System: Linux nixos 4.14.55 #1-NixOS SMP Wed Jul 11 14:29:25 UTC 2018 x86_64

```
### Steps to reproduce

1. crash X11
2. see log

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133004.a1299c9951b (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03, nixos-hardware, nixos-unstable-18.09pre143771.a8c71037e04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xaverdh** [comment]
It should be all in the logs. See the commit d84741a4bfb6ed2531ec7154479c147d2c9a737c
Although unhelpful, the message about /dev/null is quite funny I agree :-)

**Comment by aanderse** [comment]
@davidak given this has been fixed can this issue be closed now?

**Comment by davidak** [comment]
Yes, the journal works.

Maybe there is a more elegant solution than `"-logfile" "/dev/null"` in 2019? Or should i report it upstream to get a better error message in case journald is used?

Like: "Please also check the logs in the journal."

Right now it's confusing for the user.

**Comment by aanderse** [comment]
Yeah seems like an upstream thing. Good to close?

**Comment by davidak** [comment]
Yes, thanks!

I created an upstream issue: https://gitlab.freedesktop.org/xorg/xserver/issues/634

**Comment by vcunat** [comment]
> We want the default log to stderr (systemd journal in our case), but we don't want an additional log file.

Using the `/dev/stderr` file should generally work for such purposes, but I haven't looked if there could be a problem in *this* case.
