### ISSUE TITLE
Hydra evals of nixpkgs:trunk fail (heap size error)

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#44354]
For over 24hrs now, hydra evals of  `nixpkgs:trunk` have failed due to what looks (again) like memory-related issues, see https://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-errors

```
hydra-eval-jobs returned signal -1:
restarting hydra-eval-jobs after job 'AMB-plugins.aarch64-linux' because heap size is at 10737418240 bytes
restarting hydra-eval-jobs after job 'AMB-plugins.x86_64-linux' because heap size is at 10737418240 bytes
restarting hydra-eval-jobs after job 'AgdaStdlib.x86_64-linux' because heap size is at 10737418240 bytes
restarting hydra-eval-jobs after job 'CoinMP.aarch64-linux' because heap size is at 10737418240 bytes
...
```

**Comment by matthewbauer** [comment]
That's really high! I think we may just have too many packages? Maybe need to remove a few ```recurseIntoAttrs```.

**Comment by xeji** [comment]
Update: evals seem to succeed occasionally (2 in the last 3 days - but they run every 4 hrs), likely depends on the machine running them. Unfortunately Hydra only shows the last evaluation's errors, I can't find stats on how many evals failed and why.

It does look like our repo has reached a critical size.

**Comment by vcunat** [comment]
Unless Hydra's evaluator is lacking physical RAM, I expect this would be fixed by using version with https://github.com/NixOS/nixpkgs/pull/43021

**Comment by vcunat** [comment]
Overall the evaluation on Hydra seems going too slow in the past few days &ndash; it easily goes over half an hour.  I hope there's not some hidden case of rebuild during evaluation.

**Comment by xeji** [comment]
This issue also affects `nixpkgs:staging`

**Comment by grahamc** [comment]
That error message isn't a failure IIRC, see: https://github.com/NixOS/hydra/commit/0882519b108e8549ae19cac558888d81ff062893 it trades memory for time.

**Comment by srhb** [comment]
Right, but all the evals end up with the usual, actual heap failure and a failed eval.

**Comment by xeji** [comment]
looks like `nixpkgs:trunk-combined` hasn't had an eval succeed in 4 days.

**Comment by vcunat** [comment]
Yes, unfortunately, and I forced lots of attempts in there.

**Comment by xeji** [comment]
https://github.com/NixOS/hydra/commit/4dca8fe14d3f782bdf927f37efce722acefffff3 introduced some  gradual heap size increase 3 days ago. That seems to have somehow improved the situation for `trunk` but not for `trunk-combined`.
