### ISSUE TITLE
konsole: segfault

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44388]
## Issue description

```
 konsole[18020]: segfault at 9 ip 00007f4f948b8b92 sp 00007ffd45213888 error 4 in libQt5XcbQpa.so.5.10.1[7f4f94875000+124000]
```

### Steps to reproduce
Unknown, but I closed around 20 terminals via `killall bash`. 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.git.d0c868e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dotlambda** [comment]
What makes you think that's NixOS's fault?

**Comment by coretemp** [comment]
That would require us to first agree on what that phrase means.

I  think it makes sense to track an issue at the origin, which is a system running NixOS. It might very well be that the same issue also occurs on Ubuntu/Red Hat/..., but that doesn't mean it's not useful to report the issue here, because if a NixOS user searches for an issue, they will find this issue.

**Comment by coretemp** [comment]
The ideal process would be for the maintainer now to report this upstream. Now, NixOS might not have the man power to do that, but that's the typical flow (see the recent systemd issue) .

**Comment by coretemp** [comment]
(You don't have to be able to reproduce things in order to fix issues. It's just *easier* and requires less knowledge and tooling. )

**Comment by aanderse** [comment]
@coretemp still an issue as of 18.09?

**Comment by FliegendeWurst** [comment]
Apparently no longer an issue.
