### ISSUE TITLE
perf can't find docs

### ISSUE THREAD

**Issue by greydot** [NixOS/nixpkgs#44393]
## Issue description
Perf report fails to run because it cannot find tips.txt
There's a similar bug in RedHat bugzilla (https://bugzilla.redhat.com/show_bug.cgi?id=1448402)

### Steps to reproduce
    >perf record ls
    ...
    >perf report perf.data
    <Cannot load tips.txt file, please install perf!>

## Technical details
    > nix-shell -p nix-info --run "nix-info -m"
     - system: `"x86_64-linux"`
     - host os: `Linux 4.14.59, NixOS, 18.03.133023.18401b99f3f (Impala)`
     - multi-user?: `yes`
     - sandbox: `no`
     - version: `nix-env (Nix) 2.0.4`
     - channels(void): `""`
     - channels(root): `"nixos-18.03.133023.18401b99f3f, nixpkgs-18.09pre144771.8e78a9a68fe"`
     - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by thoughtpolice** [comment]
Note: this is fixed in `-unstable` thanks to @Mic92 but these patches weren't backported to 18.03.

Probably 0e2b222c246b1b93619d8ff1ca8c0bbb082facad and f28bf68bc4f93193d296718a37f94189f91ab14d are the ticket.

**Comment by Mic92** [comment]
Should be safe to backport. I have extensively used perf since then.

**Comment by thoughtpolice** [comment]
This can be closed now, as 19.03 is out and this should be fixed. Please reopen if not.
