### ISSUE TITLE
soulseekqt: does not take keyboard input

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#44454]
## Issue description

The program SoulseekQt does not take keyboard input.

### Steps to reproduce

Open `soulseekqt` from the `soulseekqt` package. Mouse input, clicking at things, works properly. However, typing anything in a box or even trying to navigate (scrolling etc) or any other of keyboard interaction does not work -- i.e. the program seems to not receive the input at all.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133029.d0c868ec17c (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03, nixos-unstable-18.09pre147850.2428f5dda13"`
 - channels(raskolnikov): `"nixos-18.03.133029.d0c868ec17c, nixos-unstable, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by dotlambda** [comment]
Duplicate of #44419.

**Comment by arximboldi** [comment]
Ooops, I swear I did use the sear before :) Thanks @dotlambda!
