### ISSUE TITLE
Nvidia 396 Drivers

### ISSUE THREAD

**Issue by tenten8401** [NixOS/nixpkgs#44461]
The drivers in Nixpkgs need to be updated to 396 since it's been out of beta for some time now and comes with lots of performance and bugfixes. With this release nvidia is also dropping 32-bit support entirely so we may need to branch off the latest 390 drivers for 32-bit systems and 396 for 64-bit.

**Comment by baracoder** [comment]
There is a pull request here #45030 to add it as nvidiaBeta package.
On the NVIDIA website the 396 version is marked as short lived while 390 is long lived branch.

**Comment by vcunat** [comment]
18.09 default is on the 390.x branch.  According to [upstream web](https://www.nvidia.com/object/unix.html), that branch seems even supported as legacy, so I see no reason to switch the default on 18.09.  Maybe updating that `_beta` to it on 18.09, if you want.
