### ISSUE TITLE
How to show configs from `nested.clone` in the grub menu

### ISSUE THREAD

**Issue by vmandela** [NixOS/nixpkgs#44495]
## Issue description

I need to switch the proxy configuration of my system based on the network I am on. For this purpose, I have a defined a cloned configuration with the proxy set. When I need to switch, I use

>   $ sudo /run/current-system/fine-tune/child-1/bin/switch-to-configuration test

to switch to the configuration with proxy enabled.

Is there a way to select the configuration to use on boot through grub rather than using the command line after booting ? PR #23458 talks about using profiles to add entries to grub menu but it seems to require a separate nixos-rebuild with the required profile. 

On a side note, the documentation on `config.nested.clone` and `config.nested.children` is very sparse. The below link from the mailing list is the only one I found with an example. 

[1] [Nix-dev] nixos-rebuild without Internet - <https://nixos.org/nix-dev/2017-June/023965.html>

**Comment by worldofpeace** [comment]
I too have had this issue in the past and had to use profiles which didn't really work so great.
I'm not even sure if `config.nested.children` and `config.nested.clone` are working as intended also.

**Comment by vmandela** [comment]
Can anyone point out the last release with which `config.nested.clone` and `config.nested.children` worked?

This seems to be the last commit with an explicit mention on `nested.clone` and it removes support for this feature. :-(

https://github.com/NixOS/nixpkgs/commit/f07f221f0ee46e64bb8a51e04dec6bade8645cfa

**Comment by vmandela** [comment]
Closing as # 45345 adds support for this feature.
