### ISSUE TITLE
lldpd service is broken (NixOS 18.09)

### ISSUE THREAD

**Issue by yesbox** [NixOS/nixpkgs#44507]
## Issue description
On the nixpkgs master, the lldpd service will not run since upstream commit https://github.com/vincentbernat/lldpd/commit/b0ca585f627aad476604a11bd356b842c664fb84. It still works in NixOS 18.03.

### Steps to reproduce
The option "services.lldpd.enable = true;" will result in the lldpd service failing to start due to "ExecStartPre=/bin/mkdir -p /var/run/lldpd (code=exit, status=203/EXEC)".

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.09.git.cc1d821 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`

**Comment by yesbox** [comment]
Pinging maintainer @fpletz.

**Comment by yesbox** [comment]
This will be fixed upstream in the next lldpd release (after 1.0.1).

**Comment by flokli** [comment]
fix: https://github.com/vincentbernat/lldpd/commit/90a50860ebdcdeb5b7dc85790b18bed23c97ec32
