### ISSUE TITLE
akonadi_folderarchive_agent is not found in kdepim

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#4451]
/share/akonadi/agents/folderarchiveagent.desktop exists and points to akonadi_folderarchive_agent
Because akonadi_folderarchive_agent cannot be found, kmail will block the ui with a message that says that akonadi is not optional. The details dialog says 'no resource agents found' and the $HOME/.local/share/akonadi/akonadi_control.error says 'Executable "akonadi_folderarchive_agent" for agent "akonadi_folderarchive_agent" could not be found!'.

This is an issue for current master (kde 4.14.1).

**Comment by Profpatsch** [comment]
(triage) @vandenoever Can you still reproduce that?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.
