### ISSUE TITLE
manpages for clang/gcc

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#44531]
## Issue description

A regular painpoint with nixos is the absence of manpages. I've enabled most options but there are still cases where we miss important manpages (gcc/clang/cmake).

### Steps to reproduce
```
$ nix-shell -p gcc   
[nix-shell:~]$ LANG=C man gcc
No manual entry for gcc

[nix-shell:~]$ which gcc
/nix/store/wkfafgwgs1na5f808wybs8l6v8yjrvqz-gcc-wrapper-7.3.0/bin/gcc

[nix-shell:~]$ ls /nix/store/wkfafgwgs1na5f808wybs8l6v8yjrvqz-gcc-wrapper-7.3.0/
bin  nix-support
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.09.git.9e2ab74 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/home/teto/nixpkgs`
```

**Comment by teto** [comment]
arf didn't see https://github.com/NixOS/nixpkgs/issues/43547. CLosing as duplicate

**Comment by LinArcX** [comment]
`nix-shell -p stdenv.cc.man` works for gcc, but what about cmake and clang? (And other tools that normally doesn't have man pages)
