### ISSUE TITLE
NetworkManager 1.12.0 seems to not be able to connect to ethernet with e1000e

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#44537]
## Issue description
I've tried to rollback to dae9cf6106d and it worked at that commit. Then I rolled forward to 7c585235ff6 and it didn't work there. And then I upgraded to 2428f5dda13 and it was still broken there.

It just keeps on trying to connect and I get this over and over again in my log:
```
Aug 06 08:57:49 phouchg wpa_supplicant[1153]: enp0s31f6: Associated with XX:XX:XX:XX:XX:XX
Aug 06 08:57:49 phouchg wpa_supplicant[1153]: WMM AC: Missing IEs
Aug 06 08:57:49 phouchg wpa_supplicant[1153]: enp0s31f6: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
Aug 06 08:57:55 phouchg wpa_supplicant[1153]: enp0s31f6: CTRL-EVENT-DISCONNECTED bssid=01:80:c2:00:00:03 reason=3 locally_generated=1
Aug 06 08:57:56 phouchg kernel: e1000e: enp0s31f6 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
```

This is my PCI network card:
```
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection I219-V (rev 21)
        Subsystem: Lenovo Device 2233
        Kernel driver in use: e1000e
        Kernel modules: e1000e
```

#### Update:
I tried building a 4.14.54 kernel (the one that was default in dae9cf6106d) on 2428f5dda13. But it's still giving me the same errors. So now I'm on 4.14.59 again.

Another note is that I've tried to connect without PEAP to another network over cable and it still gave me the same errors.

#### Update 2:
Tried to `systemctl stop network-manager` and do a `dhcpcd enp0s31f6`. That way I got an IP by the network. But I need the PEAP thingys to access all things I need, so I need it through networkmanager (I also need cisco vpn thingys, so networkmanager is handy for that as well).

I also notice that f6e83edf36a1444e8fb57c787163b94a02584f13 seems to have happened which upgrades networkmanager. I haven't tried to build with an older networkmanager yet.

But: cc @jtojnar, any ideas?

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.09.git.2428f5dda13 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(etu): `"nixos-18.09pre147850.2428f5dda13"`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by etu** [comment]
Hmm, I've got it to connect again. Seems to have been weird settings in NetworkManagers config file.

**Comment by jtojnar** [comment]
Could you provide us with a details?

**Comment by etu** [comment]
Some odd fields in the file in `/etc/NetworkManager/system-connections/` seems to have caused this. But I don't know what exactly. But I made a new connection which worked, then I dropped the old one and renamed the new one.
