### ISSUE TITLE
blueman-applet missing icons

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#44548]
## Issue description

the `blueman-applet` GUI from the `blueman` package only shows half of the icons correctly, the rest is shown as `missing icon`:
![broken icons]( https://paste.krebsco.de/TWvUnh2u/+inline )

### Steps to reproduce
install via `configuration.nix`
```nix
environment.systemPackages = [ pkgs.blueman ]
```
start via:
```console
$ blueman-applet
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.17, stockholm/NixOS, 18.08.git.makefu-simple-vm-5830-g54990bce-dirty@x/18.03.git.14946ec (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `""`
 - nixpkgs: `/var/src/nixpkgs`

**Comment by makefu** [comment]
Issue still persists (18.09 stable). It seems like i would need some extra XDG things in my path but i am not totally sure what to do.

**Comment by gmarmstrong** [comment]
Adding `gnome3.adwaita-icon-theme` to the `bulidInputs` for blueman fixed this for me. This might need to be tweaked a bit for configuration.nix, but I put this in my home.nix (for home-manager):

```nix
{ nixpkgs.overlays = [
  (self: super: {
    blueman = super.blueman.overrideAttrs (oldAttrs: {
      buildInputs = oldAttrs.buildInputs ++ [ self.gnome3.adwaita-icon-theme ];
    });
  })];
}
```

**Comment by jtojnar** [comment]
You should install icon theme you prefer in `environment.systemPackages`, see the discussion in https://github.com/NixOS/nixpkgs/pull/43150#issuecomment-450056204
