### ISSUE TITLE
Plasma5 Present windows feature is broken

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44542]
## Issue description
The Present Windows feature does not work at all (the shortcuts (Control-F9, Control-F10) do not result in any visible action). 

### Steps to reproduce
I'd expect just installing Plasma5, since I didn't do anything special.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.git.d0c868e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bkchr** [comment]
Works for me too.

**Comment by worldofpeace** [comment]
@coretemp Does the hotcorner work?

**Comment by coretemp** [comment]
No, the hotcorner doesn't work (which is the feature I actually wanted to use and normally use quite a lot).

Please report a version when reporting "it works".

**Comment by coretemp** [comment]
The version of nixpkgs that is generated by the script that is recommended to be used when reporting issues is rather useless. As such, I didn't report my version correctly.

When asking for a version, I would expect a specific git version of nixpkgs in which the package of version 5.13 you are using is located. 

I am using 5.12.6 (which is also not in the format I would like to report it myself, but I would need to fix some scripts in order to do a better job in the future). I don't really get why the recommended instructions script isn't doing something a bit more intelligent, though. 

There are disadvantages to running an unstable version too. As such, switching between stable and unstable is not easily done. As such, the suggestion that it works in the unstable version is only of theoretical concern for me (because I am not actively developing Plasma). 

That being said, this information can be useful for the maintainer of Plasma5 on NixOS.

**Comment by bkchr** [comment]
I help maintaining the plasma/kde stuff. As far as I remember, the hot corner stuff also worked for me in 5.12, but I can not say for sure. 
Is there anything happening when you want to use the feature? Any error message? 
Is there any chance that you can try unstable with Plasma 5.13?
I'm not quite sure if that is an NixOS error or more an upstream error. Because I don't think that this feature is somehow configurable while building the packages.

**Comment by coretemp** [comment]
It was working fine 3 weeks ago. No, nothing is happening (which is already in the first message I had written in this issue). 

No, because I am not willing to do a potential data migration from 5.13 back to 5.12. If the standard solution is to "upgrade", then it means defacto that there is no stable branch anymore. 

The purpose of a stable branch is that people can use the operating system. Developers of NixOS or enthusiasts can run unstable. 

It should not be a normal part of the work flow to ask people to upgrade to unstable versions for packages with potentially complex data migration issues. 

When it concerns a package for which such migration issues do not exist, this is not an issue.

I'd expect there to be an API where you can trigger the event the hotcorner thing creates such that it becomes possible to get an actual error. Alternatively, running plasmashell in some debug mode with a *lot* of output. 

I think a maintainer should run plasma in debug mode all the time and systematically eliminate warnings such that when there is an issue, there is only *one* warning.

**Comment by coretemp** [comment]
Here is another part of the feature which isn't working (that loads forever).

![image](https://user-images.githubusercontent.com/34454443/43952063-1340d7ea-9c95-11e8-8212-990146724e4a.png)

**Comment by coretemp** [comment]
Compositor was not enabled. After enabling it, present windows was disabled(!). Then I enabled present windows again, logged out, logged in and it worked. Not sure whether logging in and out is required. I use the OpenGL 3.1 backend. 

This is a fairly bad user-experience bug. The only sane way I can see this working is that enabling Present Windows should automatically enable the compositor (perhaps with some message).  

I'd love to be able to configure such things via NixOS, such that I never have to navigate their silly widgets ever again for every computer I use. 

Thanks for making my use of Plasma5 normal again, @HappyEnte.

**Comment by bkchr** [comment]
I never had to do that manually. Weird that this option was disabled for you. Maybe you should fill an upstream bug.

I would also like to make more of plasma configurable with nixos. But I'm not sure how stable there configurations formats are.

**Comment by worldofpeace** [comment]
Apparently you can control various widgets and desktop configuration with their [Javascript api](https://userbase.kde.org/KDE_System_Administration/PlasmaDesktopScripting).
It would be cool to abuse this :)

**Comment by coretemp** [comment]
Certainly cool, but I think it makes more sense to work with them and ask what they consider to be an interface they promise to maintain essentially forever. 

If interfaces change every quarter, there is no time left for it to be actually used.

**Comment by jcrben** [comment]
As far as working with them on a configuration interface, here is a link to their open KConfig bugs: https://bugs.kde.org/buglist.cgi?bug_status=__open__&component=general&list_id=1581901&product=frameworks-kconfig

I filed this one: [Configuration files should contain only persistent configuration and not state](https://bugs.kde.org/show_bug.cgi?id=397602)

All the state in the config files (many of which live in the user's home directory) makes it hard to version control them and might make it difficult to generate them from nixos altho I'm not too sure.

@samueldr seems like this could be tagged qt/ke topic - and also seems like it might be addressed and closable.

**Comment by K900** [comment]
Seems resolved now, closing. Please open a new issue if you encounter this again.
