### ISSUE TITLE
pdns-recursor (api|dns).address is a string instead of a list

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#44557]
## Issue description
When looking at the options defined in the [pdns-recursor module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/pdns-recursor.nix#L30), I noticed that dns.address and api.address are strings, whereas dns.allowFrom is a list.

So, in order to listen on multiple interfaces, a string like "1.1.1.1, 1.1.1.2, 1.1.1.3" would need to be specified, which is quite inelegant.

This is obviously a very minor bug, but fixing it requires some backwards compatibility and deprecation warning stuff, which I do not know how to implement, otherwise I would have just submitted a pull-request.

### Steps to reproduce
Deploy pdns-recursor, notice this inconsistency.

**Comment by dasJ** [comment]
I'd say just break backwards compatibility and add it to the release notes :+1:
