### ISSUE TITLE
Hydra evals of nixpkgs:trunk take over 5 hours

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#44574]
Recent hydra evals of `nixpkgs:trunk` take over 5hrs if they succeed (they often fail due to #44354).

Last 7 successful evals (newest first):

| eval | duration |
| ------------- | ------------- |
| https://hydra.nixos.org/eval/1472236 | 21209s |
| https://hydra.nixos.org/eval/1472218 | 20221s |
| https://hydra.nixos.org/eval/1472045 | 19280s |
| https://hydra.nixos.org/eval/1472026 | 20757s |
| https://hydra.nixos.org/eval/1471874 | 156s |
| https://hydra.nixos.org/eval/1471851 | 233s |
| https://hydra.nixos.org/eval/1471814 | 137s |

Clearly something drastic happened - no idea what. This may or may not be related to #44354.

cc @matthewbauer @vcunat

**Comment by xeji** [comment]
Eval times for `nixos:trunk-combined` have also gone up from around 1900s to over 10000s 5 days ago.

**Comment by tkerber** [comment]
If this is caused by a nixpkgs commit, and `nixpkgs:trunk` and `nixos:trunk-combined` have the same culprit, it would have to be in the diff of `65c43b` and `2428f5`, which isn't too large. I've taken a quick look, but it seems rather innocuous.

**Comment by xeji** [comment]
A quick local test with `maintainers/scripts/test-eval-release.sh` shows no change between last fast eval 1471874 and first slow eval 1472026:

```
$ git rev-parse HEAD
65c43b44684506b629fd4effeeca59412344eea6

$ time maintainers/scripts/test-eval-release.sh
...
real    1m41.965s
user    2m14.220s
sys     0m4.032s

$ git rev-parse HEAD
89a89ddfb3665561a3410420634ada773dfea691

$ time maintainers/scripts/test-eval-release.sh
...
real    1m45.396s
user    2m15.783s
sys     0m3.974s
```

**Comment by xeji** [comment]
Same test after switching my system to `nixUnstable` (which is used on Hydra): no significant difference.

**Comment by edolstra** [comment]
This is caused by recent changes to hydra-eval-jobs.

**Comment by vcunat** [comment]
It seems to be fast again.  I assume Eelco reverted (deployment of) those changes.

**Comment by edolstra** [comment]
It's down to 220 seconds now (https://hydra.nixos.org/eval/1472345).
