### ISSUE TITLE
remove whitespace from pytidylib URL

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#44581]
## Issue description

https://repology.org/log/573

`2018-08-07 00:56   WARNING: sanity warning: python2.7-pytidylib: homepage contains whitespace: " http://countergram.com/open-source/pytidylib/"
`

I can't find the package with the GitHub search.

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/blob/4fbae5c3011e67964c08431424c44c17a4c8115c/pkgs/top-level/python-packages.nix#L12702

I think GitHub does not search long files.
