### ISSUE TITLE
caffe: make it build-able on OS X

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#44588]
## Issue description

Currently `caffe` derivation has:

```
platforms = platforms.linux;
```

https://github.com/nixos/nixpkgs/blob/master/pkgs/applications/science/math/caffe/default.nix#L91

But apparently it can be built on OS X:

http://caffe.berkeleyvision.org/install_osx.html

Would it be possible to adjust the code so OS X is supported?

### Steps to reproduce

Trying to build `caffe` on a Mac, I guess.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
warning: Nix search path entry '/home/mark/.nix-defexpr/channels' does not exist, ignoring
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by zimbatm** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/44616 once it gets merged
