### ISSUE TITLE
nginx module: listen directive

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44623]
## Issue description
I want `listen 443;` to end up in the generated string of the virtualhosts sections. However, the module *mandates* an "addr" being specified. As such the module does not expose enough functionality. 

Relevant code:
```
        listenString = { addr, port, ssl, ... }:
          "listen ${addr}:${toString port} "
          + optionalString ssl "ssl "
          + optionalString (ssl && vhost.http2) "http2 "
          + optionalString vhost.default "default_server "
          + ";";
```

## Versions
18.03 and `master`

**Comment by coretemp** [comment]
Technically, this is even undocumented behavior. 

Nginx documentation only specifies that it is possible to configure `listen 443;`, but not what its semantics are. 

https://nginx.org/en/docs/http/ngx_http_core_module.html#listen

**Comment by dotlambda** [comment]
Is there any advantage of having `listen 443` instead of `listen *:443`?
The only thing we might want to change in `vhost-options.nix` is setting `addr` to `*` by default, but we'll have to check whether that's compatible with Apache.

**Comment by coretemp** [comment]
No, I think they mean the same. In fact `listen *:443` has the advantage of it being documented.

**Comment by dotlambda** [comment]
If you think that's useful, please make a PR setting `addr = "*"` by default. Otherwise, please close this issue.
