### ISSUE TITLE
`PYTHONHOME` propagates to subprocesses, breaking Python scripts written against different versions

### ISSUE THREAD

**Issue by Warbo** [NixOS/nixpkgs#44648]
## Issue description

If we use `python3.withPackages`, the resulting `bin/python3` executable is a wrapper script, which sets the `PYTHONHOME` environment variable. The bare `python3` derivation isn't wrapped like that. If one Python script invokes another, e.g. using Python's `subprocess` module, that env var can affect the behaviour of the subprocess's interpreter.

### Steps to reproduce

The following example builds a Python script "parent", which invokes another Python script "child", sends `hello world` to its stdin and prints its stdout and stderr. The "child" script just echoes stdin to stdout, so the resulting script should echo `hello world`.

Both scripts hard-code their shebang, but this also happens if we use `makeWrapper ... --prefix PATH : ...`. The "parent" uses `python35.withPackages` (so its `PATH` contains a `python3` binary with the `PYTHONHOME` wrapper), whilst "child" uses `python34` without `withPackages` (so its `python3` binary is not wrapped):

```
with import <nixpkgs> {};
with rec {
  child = writeScript "child.py" ''
    #!${python34}/bin/python3
    import sys
    print(sys.stdin.read())
  '';

  parent = writeScript "parent.py" ''
    #!${python35.withPackages (p: [])}/bin/python3
    from subprocess import Popen, PIPE
    p = Popen(["${child}"], stdin=PIPE, stdout=PIPE, stderr=PIPE)
    (stdo, stde) = p.communicate(b"hello world")
    print(stdo + stde)
  '';
};
parent
```

I've tested this on NixOS 18.03. Running `nix-build` on this file should build the "parent" script. Running this script gives this error:

```
$ F=$(nix-build python.nix) && "$F"
these derivations will be built:
  /nix/store/z985l0qbh9xwk2dmdv0a6j6vlgqiprf2-child.py.drv
  /nix/store/198rfwg2z3qgmx55fhbiwqrz71d1pda2-parent.py.drv
building '/nix/store/z985l0qbh9xwk2dmdv0a6j6vlgqiprf2-child.py.drv'...
building '/nix/store/198rfwg2z3qgmx55fhbiwqrz71d1pda2-parent.py.drv'...
b"Fatal Python error: Py_Initialize: Unable to get the locale encoding\nImportError: No module named 'encodings'\n\nCurrent thread 0xb70d3480 (most recent call first):\n"
```

This is due to the `PYTHONHOME` variable of the "parent" script, which uses Python 3.5, being propagated to the "child" script which is using Python 3.4. This prevents the Python 3.4 interpreter from finding its built-in modules/packages, in this case 'encodings'.

Whilst this minimal example is rather useless, this cropped up for me in a project which uses many small scripts, in a mixture of languages. For robustness, I've been using `makeWrapper` to "bake in" their dependencies, and I ended up with a bunch of these `Py_Initialize` errors.

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"i686-linux"`
 - host os: `Linux 4.9.52, NixOS, 18.03.132803.2f06e04b74e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132803.2f06e04b74e"`
 - channels(chris): `"nixos-17.09.2875.c2b668ee726"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by Warbo** [comment]
Note that I've managed to avoid my particular problems, since all of these scripts/derivations are under my control. I've replaced uses of `python3` (and `python`) with `python3.withPackages (p: [])`, so that everything gets its own `PYTHONHOME` variable rather than using a propagated value.

Still, this came as a bit of a "gotcha" to me. It doesn't seem to be documented either; the only stuff I could find were [IRC logs](https://logs.nix.samueldr.com/nixos/2017-10-27#662036) of a user "joko" who seemed to hit this same issue.

**Comment by FRidh** [comment]
Yep, its a known issue and a reason why environment variables should be avoided. Note this problem exists not just with Python, but in many places in Nixpkgs where we use wrappers.

For creating an environment there are essentially two options:
1. set `$PYTHONHOME` so that all modules can be found relative to its value;
2. copy in `pythonX.Y`, and copy in all executable scripts, and patch their shebangs. 

Option 1) was chosen. There have been some experiments with other solutions, such as https://github.com/NixOS/nixpkgs/pull/25985.

Closing because it's a known issue. Adding, say, a warning to the docs wouldn't be a bad idea so a PR is  welcome!
