### ISSUE TITLE
fetchurl throws implementation cannot deal with > 32-bit integers

### ISSUE THREAD

**Issue by countoren** [NixOS/nixpkgs#44717]
## Issue description
fetch url returns : error: implementation cannot deal with > 32-bit integers

### Steps to reproduce

in nixrepl after loading <nixpkgs>
pkgs.fetchurl { url = "https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.2.zip"; sha256 = "07szhx043ixym8n15n5xn9g5mjf1r8zi28hgdbpyf07vrfymc0z1"; }
gives back:
error: implementation cannot deal with > 32-bit integers

my system is Darwin (macos 10.12.6)
unstable nix channel

**Comment by Artturin** [comment]
Doesn't repro on aarch64-darwin or x86_64-linux
