### ISSUE TITLE
Redshift, localtime can't talk to geoclue

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#44725]
## Issue description

I'm not entirely sure when this started happening, but I now see the following in my logs.

redshift:
```
Aug 08 17:07:30 clipper redshift[13309]: Using method `randr'.
Aug 08 17:07:30 clipper redshift[13309]: Waiting for initial location to become available...
Aug 08 17:07:33 clipper redshift[13309]: Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying.
Aug 08 17:07:33 clipper redshift[13309]: Unable to get location from provider.
Aug 08 17:07:33 clipper systemd[5545]: redshift.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 17:07:33 clipper systemd[5545]: redshift.service: Failed with result 'exit-code'.
```

localtime:
```
Aug 08 17:10:21 clipper localtimed[17261]: Failed to start GeoClue2 Client: 'localtimed' disallowed, no agent for UID 1001
Aug 08 17:10:21 clipper systemd[1]: localtime.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 17:10:21 clipper systemd[1]: localtime.service: Failed with result 'exit-code'.
```

This seems to be an old issue that's recurred, see e.g. https://github.com/jonls/redshift/issues/158. The last comment has this message, and suggests that the issue may have started between geoclue 2.4.7-1 and 2.4.10-1. Previous commenters seem to have a different issue (which it seems like we should also have, since I can't find that we install the `redshift` `.desktop` files anywhere, possibly because the module doesn't add `redshift` to `environment.systemPackages`).

The localtime dev also seems to have noticed this issue: https://github.com/Stebalien/localtime/issues/6

### Steps to reproduce

Try
```
services.redshift = {
  enable = true;
  provider = "geoclue2";
};
```
or
```
services.localtime.enable = true;
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.09pre147850.2428f5dda13 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(michael): `""`
 - channels(root): `"nixos-18.09pre147850.2428f5dda13"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by michaelpj** [comment]
Hm, some other people have reported (https://github.com/jonls/redshift/issues/636) that geoclue is crashing when redshift tries to connect with it. This is actually consistent with what I'm seeing - the geoclue service also seems to be restarting constantly, although I don't get any crash message.

**Comment by dtzWill** [comment]
Is whitelisting redshift the solution, or is it clear? I miss redshift :(.

**Comment by michaelpj** [comment]
There's some hope that upgrading geoclue might help, however I'm struggling to get the new version to build.

**Comment by michaelpj** [comment]
I managed to build the new version with the docs disabled, but it doesn't seem to change anything. 

For localtime, I don't believe the issue is the permissions one, but perhaps rather that they've started requiring an "agent" that we don't have (https://gitlab.freedesktop.org/geoclue/geoclue/commit/c0d987984fd709b4c1cf3cfdab08f813c7b119ee, perhaps?). It gives the corresponding error message that's in that commit.

I have no idea what's wrong with redshift, it could be a similar thing?

**Comment by michaelpj** [comment]
Here's what I've tried so far:
- Updating geoclue to 2.4.11.
- Adding a service that runs the geoclue demo agent.

Neither of these seem to have helped at all. The agent just sits there saying 
```
Aug 09 14:29:28 clipper geoclue-agent-start[18778]: Geolocation service not in use
```
regardless, and everything still fails :(

I am using KDE, possibly there should be a location services agent associated with that, but I'm not sure where to find that.

**Comment by michaelpj** [comment]
Some progress, enough to fix redshift at least: https://github.com/NixOS/nixpkgs/pull/44820

**Comment by michaelpj** [comment]
It's possible that this situation will get a bit better - a geoclue dev has popped up in https://github.com/jonls/redshift/issues/636 and seems to be somewhat aware of the problems this has caused.

**Comment by obadz** [comment]
So I have #44820 yet `localtime.service` still crashes for me with the above error. Any ideas?

**Comment by domenkozar** [comment]
I'm getting constantly message `Allow 'Redshift' ... information?`, is that a side-effect of this bug? :)

**Comment by michaelpj** [comment]
That's probably the geoclue default agent, which we're using because you have to have one, and which tries to ask for permission for an app to get the location. On KDE at least it displays a popup, possibly it doesn't work as well on your DE.

**Comment by chreekat** [comment]
> The maintainer has agreed, but hasn't done anything yet.

@michaelpj already knows this, but for everyone else playing along, the geoclue app-whitelist change has since been applied, which might open up the possibility for redshift and localtime to get fixed in NixOS.

**Comment by domenkozar** [comment]
1) this commit didn't make it in last release 
and could be potentially an issue https://gitlab.freedesktop.org/geoclue/geoclue/commit/c9f4dc72ccbc6cb18ab348f6a1a3f7937c4bc58f

2) I'm testing now backporting meson bump to 18.09 as it's required by latest geoclue2

**Comment by domenkozar** [comment]
Maybe for 18.09 best solution is to downgrade geoclue? It's nearly impossible to bump meson in a stable channel.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/pull/54005 for 18.09 reverts.
