### ISSUE TITLE
vscode package on mac didn't create a .app extension, macOS didn't recognize it as an app

### ISSUE THREAD

**Issue by leira** [NixOS/nixpkgs#44774]
I installed vscode 1.25.1 on macOS using nix-env, it eventually installed into:

/nix/store/nywspd7xg01a2alqma9m9cmywakcfnv7-vscode-1.25.1/lib/vscode

Though the vscode folder has the proper structure of a macOS app, but it doesn't have a .app extension, so it couldn't be launched by macOS with double click, or through spotlight.

Of course I can launch it using code command, but sometimes I need to launch it through macOS.

The fix seems to be as simple as " mkdir -p $out/lib/vscode.app". I'm new to nix, not sure if that's proper way to fix it.

```
    installPhase =
      if stdenv.system == "x86_64-darwin" then ''
        mkdir -p $out/lib/vscode $out/bin
        cp -r ./* $out/lib/vscode
        ln -s $out/lib/vscode/Contents/Resources/app/bin/code $out/bin
```

**Comment by jonringer** [comment]
The darwin build now creates a .app
