### ISSUE TITLE
nginx module: recommendedProxySettings has no rationale in source code

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44816]
## Importance
Low

## Issue description

In particular `proxy_http_version      1.0;` might be controversial. (E.g.: why not 1.1 for modern systems?) 
I think every line should either reference nginx documentation or document why it's being used. 

```
  ${optionalString (cfg.recommendedProxySettings) ''
        proxy_redirect          off;
        proxy_connect_timeout   90;
        proxy_send_timeout      90;
        proxy_read_timeout      90;
        proxy_http_version      1.0;
        include ${recommendedProxyConfig};
      ''}
```

Applicable to `18.03` and `master` .

**Comment by SuperSandro2000** [comment]
that is 1.1 by now https://github.com/NixOS/nixpkgs/blob/83801da137050a7c1b0242976c06a4d5e36f4402/nixos/modules/services/web-servers/nginx/default.nix#L166
