### ISSUE TITLE
Library function mapAttrsToList depends on implementation

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44814]
## Issue description
I believe `mapAttrsToList` cannot be implemented in a valid Nix implementation.

```
    mapAttrsToList (name: value: name + value)
          { x = "a"; y = "b"; }
       => [ "xa" "yb" ]
```

Let's recall what an attribute set is:

> Attribute sets are an association between string keys and a Nix values. Keys can only be strings. When writing attribute sets you can also use unquoted identifiers as keys.

Attribute sets have no defined order as such, it's impossible to write a function `maptAttrsToList` which would work against every possible implementation of `attrNames` (which only needs to return attribute names, but not in a particular order). 

My understanding of attribute sets is that it is fully legal for an implementation to evaluate: 
`builtin.attrNames {a=1;b=2;c=3;} `
to

`["c", "a", "b"]` and even evaluate to a different order every time the *program* is run (not within a single program to keep consistency). 

In the case of nginx configuration, which uses attrNames via some indirections, it means that the nginx module also has a correctness problem. 

If attribute sets are in fact *ordered* then this order would have to be added to the manual.

**Comment by dezgeg** [comment]
`builtins.attrNames` is documented to return the keys in alphabetical order: https://nixos.org/nix/manual/#ssec-builtins

**Comment by coretemp** [comment]
Thank you. Closing.
