### ISSUE TITLE
packageOverrides cannot override findutils.

### ISSUE THREAD

**Issue by zhou13** [NixOS/nixpkgs#44810]
## Issue description

`make test` in findutils does not pass on my rootless installation of nix.  So I need to override it to set `doCheck = false`.

### Steps to reproduce

1. Run `nix-env --dry-run -iA nixpkgs.findutils`. I get `/nix/store/bmagxzxiqida1ymfzfcjglipavvy00bx-findutils-4.6.0-info`

2.  Put the following into `.config/nixpkgs/config.nix`:
````
{
  allowUnfree = true;

  packageOverrides = pkgs: {
    findutils = pkgs.findutils.overrideAttrs(oldAttrs: {
      doCheck = false;
    });
  };
}
````

3.  Run `nix-env --dry-run -iA nixpkgs.findutils`.  I still get  `/nix/store/bmagxzxiqida1ymfzfcjglipavvy00bx-findutils-4.6.0-info`.  The hash does not change, which means that `packageOverrides` does not work for findutils.

**Comment by Artturin** [comment]
i can repro 

```
nix-repl> (import ./. { config = { packageOverrides = p: { findutils = p.findutils.overrideAttrs (_: { doCheck = false; }); }; }; }).findutils
«derivation /nix/store/bws1cf40ww41wdbmhbhkjvsknba7q7bs-findutils-4.9.0.drv»

nix-repl> (import ./. {}).findutils
«derivation /nix/store/bws1cf40ww41wdbmhbhkjvsknba7q7bs-findutils-4.9.0.drv»
```

but overlays work fine so just use those

```
nix-repl> (import ./. { overlays = [ (self: super: { findutils = super.findutils.overrideAttrs (_: { doCheck = false; }); }) ];}).findutils
«derivation /nix/store/94ya4rhyk66vvvjgs2szybm198s7j4ci-findutils-4.9.0.drv»

nix-repl> (import ./. { overlays = [ (self: super: { findutils = super.findutils.overrideAttrs (_: { doCheck = false; }); }) ];}).findutils.doCheck
false

nix-repl> (import ./. { }).findutils
«derivation /nix/store/bws1cf40ww41wdbmhbhkjvsknba7q7bs-findutils-4.9.0.drv»
```
