### ISSUE TITLE
mesa: reduce rebuild impact [plan]

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#44831]
Currently the rebuild impact is only due to libGL stubs pulling headers from the mesa build (I think), but upgrading the headers shouldn't be needed on every driver minor bump, as the API should be portable even to other libGL implementations, etc.

Plan: use headers from a fixed version, so that `mesa(_drivers)` can be changed much easier.

**Comment by vcunat** [comment]
It might actually reduce the rebuild impact of a few other packages, too, as `glvnd` has much smaller closure than `mesa`.

**Comment by corngood** [comment]
I think we could avoid this sort of mass rebuild by removing the `self` references in `mesa_noglu.stubs`.  It wouldn't help with version upgrades (unless we pin it, which I'm not sure is a good idea).  Maybe we should source the headers from khronos repositories?

**Comment by vcunat** [comment]
Well, yes, I meant whatever way to get suitable headers.  I have a feeling the khronos headers had been considered by us once, but I don't remember what's happened to that idea.

**Comment by vcunat** [comment]
Done in #118479, currently in `staging`.
