### ISSUE TITLE
Firefox isn't picking up mime type associations

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#44849]
## Issue description
This works:
```
> xdg-mime query filetype foo.pdf
application/pdf
> xdg-mime query default application/pdf
okularApplication_pdf.desktop
```
but attempting to open a downloaded PDF from firefox just gives me an application choice dialog. The firefox wrapper seems to have `XDG_DATA_DIRS` set correctly, so I don't know what's wrong here.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by vcunat** [comment]
A duplicate of https://github.com/NixOS/nixpkgs/issues/11355, I believe :-)

**Comment by michaelpj** [comment]
Should be fixed.
