### ISSUE TITLE
vdirsyncer: fails due to click-log

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#44856]
## Issue description

```
Processing ./vdirsyncer-0.17.0a2-py2.py3-none-linux_x86_64.whl
Requirement already satisfied: atomicwrites>=0.1.7 in /nix/store/vf7smgsf57mvbfkywbz7vfshwnay08vn-python3.6-atomicwrites-1.1.5/lib/python3.6/site-packages (from vdirsyncer==0.17.0a2) (1.1.5)
Collecting click-log<0.3.0,>=0.2.0 (from vdirsyncer==0.17.0a2)
  Could not find a version that satisfies the requirement click-log<0.3.0,>=0.2.0 (from vdirsyncer==0.17.0a2) (from versions: )
No matching distribution found for click-log<0.3.0,>=0.2.0 (from vdirsyncer==0.17.0a2)
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(philipp): `"nixpkgs-18.09pre146471.d7d31fea7e7"`
 - channels(root): `"nixos-18.09pre147850.2428f5dda13"`
 - nixpkgs: `/home/philipp/.nix-defexpr/channels/nixpkgs`

**Comment by teto** [comment]
vdirsyncer master released that constraint but one needs to wait for a release since the package is kinda special and tries to pick its version I don't remember how.

**Comment by pmiddend** [comment]
Okay, but having a broken version in nixpkgs isn't really desirable, isn't it? Can we `fetchpatch` certain commits from master to fix this, maybe?

**Comment by dotlambda** [comment]
Fixed on latest master.
