### ISSUE TITLE
blockhash: doesn't build on darwin

### ISSUE THREAD

**Issue by ariutta** [NixOS/nixpkgs#44851]
## Issue description

haskellPackages.blockhash fails to build on darwin.

### Steps to reproduce

```
nix-env -iA nixos.haskellPackages.blockhash
```

yields:

> Configuring blockhash-0.1.0.0...
Setup: Encountered missing dependencies:
optparse-applicative ==0.12.*, vector ==0.11.*
builder for ‘/nix/store/4al8n274lx860a7jzx4aq8f2w3j2lfd4-blockhash-0.1.0.0.drv’ failed with exit code 1

```
nix-env -iA nixpkgs.haskellPackages.blockhash
```

yields:

> Configuring blockhash-0.1.0.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
optparse-applicative ==0.12.*, vector ==0.11.*

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

  - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(andersriutta): `"nixos-17.09.3263.9e1d8b74706, nixpkgs-18.09pre146471.d7d31fea7e7"`
 - channels(root): `"nixpkgs-18.03pre122585.b212125b541"`
 - nixpkgs: `/Users/andersriutta/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
This should probably be opened as an issue in the blockhash repo.
