### ISSUE TITLE
nixos-rebuild build-vm-with-bootloader fails to build

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#44918]
### Steps to reproduce

```
nixos-generate-config --dir /tmp
nixos-rebuild -I nixos-config=/tmp/configuration.nix build-vm-with-bootloader
```

Result:
```
building Nix...                
building the system configuration...
these derivations will be built:
  /nix/store/fgfh17z0f6jvxz30hdi5zn1v34z6kxn3-nixos-boot-disk.drv
  /nix/store/fjixr42lz62rqima3nvdjkfzx9f4gbas-run-nixos-vm.drv
  /nix/store/a05dlllwxpsnflay3q3wllfynlrrr9r2-nixos-vm.drv
building '/nix/store/fgfh17z0f6jvxz30hdi5zn1v34z6kxn3-nixos-boot-disk.drv'...
Formatting '/nix/store/36n0g37j6n8ffjbwxxd141yq119i4wgh-nixos-boot-disk/disk.img', fmt=qcow2 size=41943040 cluster_size=65536 lazy_refcounts=off refcount_bits=16
QEMU 2.11.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: -serial pty: char device redirected to /dev/pts/0 (label serial0)
builder for '/nix/store/fgfh17z0f6jvxz30hdi5zn1v34z6kxn3-nixos-boot-disk.drv' failed with exit code 1
cannot build derivation '/nix/store/fjixr42lz62rqima3nvdjkfzx9f4gbas-run-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/a05dlllwxpsnflay3q3wllfynlrrr9r2-nixos-vm.drv': 1 dependencies couldn't be built
error: build of '/nix/store/a05dlllwxpsnflay3q3wllfynlrrr9r2-nixos-vm.drv' failed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.8, NixOS, 18.03.132915.d6c6c7fcec6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133065.e42c07d78a1, nixos-hardware, nixos-stable-17.09.3194.edf1079d43f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by srhb** [comment]
Removing `-serial pty` from `QEMU_OPTS` reveals `mknod: /dev/vda2: File exists`

Commenting out the `mknod` succeeds.

**Comment by samueldr** [comment]
Triage: the linked PR is closed, with resolution (PR squashed and reworked into https://github.com/NixOS/nixpkgs/commit/78fb4bd644dcb1dac30364ad04f16e4e28bc3669)

Is this still an issue, @symphorien ?

**Comment by symphorien** [comment]
The problem was only half fixed:
now building the vm works but booting it fails: qemu complains "boot failed: not a bootable disk".

**Comment by lheckemann** [comment]
Dup of #39036?

**Comment by symphorien** [comment]
I could boot a vm built with `nixos-rebuild build-vm-with-bootloader` on top of nixpkgs-unstable 135073a87b7e2c631739f4ffa016e1859b1a425e
