### ISSUE TITLE
dwarf-fortress-full package is mentioned in dwarf-fortress/default.nix but doesn't appear to be available

### ISSUE THREAD

**Issue by SongWithoutWords** [NixOS/nixpkgs#44944]
A package called dwarf-fortress-full is mentioned here:

https://github.com/NixOS/nixpkgs/blob/7c66a902ce342036a63146a9b7ebd92d9d9ad287/pkgs/games/dwarf-fortress/default.nix#L7-L8

And appears to be exported here:
https://github.com/NixOS/nixpkgs/blob/7c66a902ce342036a63146a9b7ebd92d9d9ad287/pkgs/games/dwarf-fortress/lazy-pack.nix#L19-L24

I'm on NixOS version 18.03 and just ran `nixos-rebuild switch --upgrade`, but this package doesn't appear to be available (I can't find it on the nix-package website either https://nixos.org/nixos/packages.html#dwarf-fortress). I don't know enough about the nix packaging system to know why this might be.

**Comment by SongWithoutWords** [comment]
cc @Baughn  and @volth if you guys are still maintaining this package :)

**Comment by Baughn** [comment]
Yeah, I noticed the documentation failure.

I've been on vacation for the last couple of weeks, but I still have some improvements in mind for this thing. I'll fix the bug while I'm at it.

**Comment by numinit** [comment]
Docs are improved; check master :-)

**Comment by kevincox** [comment]
This seems to be resolved as `dwarf-fortress-packages.dwarf-fortress-full` exists.
