### ISSUE TITLE
brightnessctl: udev process failed with exit code 1

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nixpkgs#44975]
## Issue description

`hardware.brightnessctl.enable = true` installed the udev rules of `brightnessctl`, which failed to process during boot but succeed running manually using `sudo`.

By the way, why not add `brightnessctl` to `environment.systemPackages` while this option is enabled? I found it a little bit confusing...

### Steps to reproduce

set `hardware.brightnessctl.enable = true` , rebuild and reboot.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.14, NixOS, 18.09pre148985.4af9ee49f1e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(mlatus): `"nixpkgs-18.09pre148985.4af9ee49f1e"`
 - nixpkgs: `/home/mlatus/.nix-defexpr/channels/nixpkgs`

**Comment by mweinelt** [comment]
As far as I can tell the chgrp target is not expanded by udev, while it is in a shell. Removing the wildcard substitute reverts it to `%k` and that makes it work for me.

```diff
diff --git a/pkgs/misc/brightnessctl/default.nix b/pkgs/misc/brightnessctl/default.nix
index b8821d335b2..332221443cd 100644
--- a/pkgs/misc/brightnessctl/default.nix
+++ b/pkgs/misc/brightnessctl/default.nix
@@ -16,7 +16,7 @@ stdenv.mkDerivation rec {
 
   postPatch = ''
     substituteInPlace 90-brightnessctl.rules --replace /bin/ ${coreutils}/bin/
-    substituteInPlace 90-brightnessctl.rules --replace %k '*'
+    #substituteInPlace 90-brightnessctl.rules --replace %k 'intel_backlight'
   '';
 
   meta = {

```

**Comment by andir** [comment]
Has been fixed on master since a while. I back ported the fixes yesterday. Closing.
