### ISSUE TITLE
pkgs.lib.cleanSourceFilter doesn't clean .git file (for sub-modules)

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#45027]
## Issue description

A Git submodule is a directory that also contains a `.git` *file* (not a directory). This may contain something like:

```
gitdir: ../../.git/modules/comparable-key
```

`pkgs.lib.cleanSourceFilter` only looks for `.git` directories, and won't clean this. However, Hydra Git checkouts will clean this.

I think `cleanSourceFilter` should remove `.git` nodes, directories or regular files.

**Comment by ryantm** [comment]
Looking at the source of `cleanSourceFilter`, I believe this has been fixed.
