### ISSUE TITLE
sdistTarball requires all dependencies to be built, but this is not necessary

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#45020]
## Issue description

`pkgs.haskell.lib.sdistTarball` overrides a package's derivation to have a build phase that simply calls `./Setup sdist`. However, all build inputs are retained, but these are not necessary. The current behavior means that `sdistTarball` cannot complete until all dependencies are built, but if you only need the tarball this delays the build.

I believe we can just add the following:

```nix
 configurePhase = ":";
 buildInputs = [];
 propagatedBuildInputs = [];
```

to `sdistTarball`.

**Comment by sternenseemann** [comment]
I would recommend using `haskell.packages.*.cabalSdist` added in #174176 for this purpose which avoids both building dependencies and even compiling `Setup.hs`.

**Comment by ocharles** [comment]
I don't have any need for this anymore so I'm going to close this issue. It sounds like there is a good solution/workaround now, too!
