### ISSUE TITLE
GLib setup hook does not move schemas

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#45043]
In https://github.com/NixOS/nixpkgs/commit/d2f75c32de78efb5be439e9826be6447efe0166d, I added a `lib` output to nm-applet. This caused the glib setup hook to no longer apply, since it expects the gsettings schemas in `lib` output:

https://github.com/NixOS/nixpkgs/blob/44a4370b1f3aa2b1b2416d8c09b8df6900f5c449/pkgs/development/libraries/glib/setup-hook.sh#L18

I wonder when this is applicable, since the schemas will only go to `!outputLib` when install flags set by the hook apply, but then they will already be in the correct directory.

cc @worldofpeace

**Comment by worldofpeace** [comment]
Here's the relevant discussions when that change was made. https://github.com/NixOS/nixpkgs/commit/653cdac274ef2ccb46712eea5e0b7dba6c30eb7e  https://github.com/NixOS/nixpkgs/issues/7325

**Comment by jtojnar** [comment]
I see the change from `$out` to ${!outputLib}` here: https://github.com/NixOS/nixpkgs/commit/55b7d3a181f644586bfc4c6ee5be0dd2a213a733

**Comment by jtojnar** [comment]
Fixed in #54130
