### ISSUE TITLE
LightDM: No such interface 'org.freedesktop.DisplayManager.AccountsService'

### ISSUE THREAD

**Issue by mnacamura** [NixOS/nixpkgs#45059]
## Issue description

LightDM seems not installing dbus interface of AccountsService.

Systemd journal:
```
lightdm[1335]: Error updating user /org/freedesktop/Accounts/User1000: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.DisplayManager.AccountsService'
```

In `lightdm` package, it is contained:
```
% nix build -f '<nixpkgs>' lightdm
% ls result/share/dbus-1/interfaces | grep -i accounts
org.freedesktop.DisplayManager.AccountsService.xml
```
But in the current system:
```
% ls /run/current-system/sw/share/dbus-1/interfaces | grep -i accounts
org.freedesktop.Accounts.User.xml@
org.freedesktop.Accounts.xml@
```

### Steps to reproduce

```
services.xserver.displayManager.lightdm.enable = true;
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0, NixOS, 18.09.git.8483983 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre148970.b5b11e9da43"`
 - channels(mnacamura): `"nixpkgs-18.09pre148461.bf1b50cbc8f"`
 - nixpkgs: `/home/mnacamura/repos/nixpkgs`

**Comment by jtojnar** [comment]
Hmm, apparently it is some kind of extension to `accountsservice`: https://github.com/CanonicalLtd/lightdm/commit/6015bce25f241e7580c03594d846769f8236232f

Weird that it is not linked – the lightdm module contains `services.dbus.packages = [ lightdm ]`.

**Comment by jtojnar** [comment]
Actually, the dbus module does not use `/run/current-system/sw/share/dbus-1/interfaces`, it creates a configuration file:

https://github.com/NixOS/nixpkgs/blob/cc288eef072c5feb6dd74740799a1349ef8fa58e/nixos/modules/services/system/dbus.nix#L13

The directory is probably just a side effect of something adding `/share` to `environment.pathsToLink`.

**Comment by mnacamura** [comment]
Ah I see. So, the `configDir` is put in `/etc`:
https://github.com/NixOS/nixpkgs/blob/cc288eef072c5feb6dd74740799a1349ef8fa58e/nixos/modules/services/system/dbus.nix#L69-L72

I examined `/etc/dbus-1/*.conf`:
```
% ls /etc/dbus-1/
session.conf  system.conf

% cat /etc/dbus-1/* | perl -pe 's/(\/?<\w+>)/\n$1/g' | grep -i lightdm
<servicedir>/nix/store/sx3mcl8cb2rk18imz9x740fixpvk4zkn-lightdm-1.26.0/share/dbus-1/services</servicedir>
<includedir>/nix/store/sx3mcl8cb2rk18imz9x740fixpvk4zkn-lightdm-1.26.0/etc/dbus-1/session.d</includedir>
<servicedir>/nix/store/sx3mcl8cb2rk18imz9x740fixpvk4zkn-lightdm-1.26.0/share/dbus-1/system-services</servicedir>
<includedir>/nix/store/sx3mcl8cb2rk18imz9x740fixpvk4zkn-lightdm-1.26.0/etc/dbus-1/system.d</includedir>
<includedir>/nix/store/sx3mcl8cb2rk18imz9x740fixpvk4zkn-lightdm-1.26.0/share/dbus-1/system.d</includedir>
```
I guess lightdm 's `$out/share/dbus-1/interfaces` should also be included in these paths?

**Comment by mnacamura** [comment]
```
% nix-shell -p dbus pkgconfig
[nix-shell:~]$ pkg-config --variable interfaces_dir dbus-1
/etc/dbus-1/interfaces
```
Probably, interfaces files should be linked in `/etc/dbus-1/interfaces`?

**Comment by jtojnar** [comment]
No idea – I thought the interface files were only for introspection or something. I tried linking to `/run/current-system` by adding it to `environment.systemPackages` but that does not seem to help. You can try the `/etc` route but I do not see it documented anywhere. Though, I do not see the one in data dirs documented either – perhaps it is really just for applications like d-feet. But the data should be available through dbus interface so I do not see the need for installing the XML files.

On a side note, [accountsservice looks](https://gitlab.freedesktop.org/accountsservice/accountsservice/blob/master/src/extensions.c#L93-114) for the interface symlinks in `$XDG_DATA_DIRS/accountsservice`, so something like the following might be good:

```patch
--- a/nixos/modules/services/desktops/accountsservice.nix
+++ b/nixos/modules/services/desktops/accountsservice.nix
@@ -43,6 +43,9 @@
     } // (mkIf (!config.users.mutableUsers) {
       environment.NIXOS_USERS_PURE = "true";
     });
+
+    # Extensions
+    environment.pathsToLink = [ "/share/accountsservice" ];
   };
 
 }
```

**Comment by mnacamura** [comment]
Thanks for suggestion. I tried this:
```
    environment.pathsToLink = [ "/share/accountsservice" ];
    environment.systemPackages = [ pkgs.lightdm ];
```
Apparently the interface file appears,
```
readlink -f /run/current-system/sw/share/accountsservice/interfaces/org.freedesktop.DisplayManager.AccountsService.xml 
/nix/store/sx3mcl8cb2rk18imz9x740fixpvk4zkn-lightdm-1.26.0/share/dbus-1/interfaces/org.freedesktop.DisplayManager.AccountsService.xml
```
but I still see the error.

**Comment by mnacamura** [comment]
Hopefully fixed by the above PR.
