### ISSUE TITLE
Document `packageOverrides` in ~/.nixpkgs/config.nix

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4505]
We have zero docs in manuals about ~/.nixpkgs/config.nix

Some hits from wiki:
- https://nixos.org/wiki/Nix_Modifying_Packages
- https://nixos.org/wiki/Howto_keep_multiple_packages_up_to_date_at_once

Along side, document: `allowUnfree`, `packageOverrides`

**Comment by iElectric** [comment]
Now that we have #5953, this can be easily expanded.

**Comment by iElectric** [comment]
`packageOverrides` is still missing in the docs.

**Comment by seppeljordan** [comment]
Say i want to write the section about `packageOverrides` in the manual.  Would it be okay to take parts from the wiki and put it into the nixpkgs-manual or would i (or the project) potentially get trouble because of weird copyright stuff?  Do I have to mention in some file where I stole stuff from if it would be okay?

**Comment by domenkozar** [comment]
That sounds good, we want to move good documentation to the manuals and reduce wiki noise.

**Comment by lethalman** [comment]
There's some little docs now about packageOverrides: http://nixos.org/nixpkgs/manual/#sec-modify-via-packageOverrides

**Comment by Profpatsch** [comment]
(triage) I wrote a little bit of docs for overriding as well: https://github.com/Profpatsch/nixpkgs-cheatsheet/blob/master/cheatsheet.org
But maybe it’s gotten better in the meantime?

**Comment by matthewbauer** [comment]
This seems to have been fixed:

https://nixos.org/nixpkgs/manual/#sec-modify-via-packageOverrides

Feel free to reopen if this is still an issue.
