### ISSUE TITLE
pytest doesn't find xdist

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#45060]
## Issue description

I'm trying to run pytest with the xdist plugin. I have a `default.nix` file which uses `pythonPkgs.buildPythonApplication` and has `pytest_xdist` in its `propagatedBuildInputs`. When I use `nix-shell` and run `py.test`, xdist is not listed in the "plugins" section.

Compare that to `pytestcov`, which is also in my `propagatedBuildInputs` and which /is/ found by `py.test` automatically. Am I missing something?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.62, NixOS, 18.09pre148985.4af9ee49f1e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(philipp): `"nixpkgs-18.09pre146471.d7d31fea7e7"`
 - channels(root): `"nixos-18.09pre148985.4af9ee49f1e"`
 - nixpkgs: `/home/philipp/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment]
I'm having a similar issue, but without Nix, and encountered the following which may apply here as well:
https://stackoverflow.com/questions/37058544/how-to-register-entry-points-for-network-python-package-installs

**Comment by pmiddend** [comment]
Yes, I was actually able to fix this.

**Comment by erikarvstedt** [comment]
It's still broken:
```
nix-build --no-out-link - <<'EOF'
with (import <nixpkgs-unstable> {});
let
  py = python3.withPackages (ps: with ps; [
    pytest
    pytest_xdist # broken
    pytestcov    # works
  ]);
in runCommand "_" { buildInputs = [ py ]; } ''
  pytest
''
EOF
```
Output: `plugins: cov-2.5.1`, xdist is missing.

**Comment by dotlambda** [comment]
I tried updating pytest-xdist to 1.25.0. However, that does not help either.

**Comment by FRidh** [comment]
cherry-picked to 18.09 as 76aafbf4bf4992c82da41ccefd8c6d481744524c
