### ISSUE TITLE
nginx module: misconfiguration

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#45074]
## Issue description

nginx documentation specifies:
```
keepalive_timeout 75s;
```

as a valid configuration. 

However, the module in master specifies
```
keepalive_timeout 65;
```

Note there is no "s". AFAIK, without the "s" it's undefined behaviour and in all cases it's less documented. Please add the letter "s".  

Applicable to master and 18.03.

**Comment by globin** [comment]
It is documented: https://nginx.org/en/docs/syntax.html

> A value without a suffix means seconds. It is recommended to always specify a suffix.

I'm closing as this is not a real issue, though I'd definitely accept and welcome a pull request adding the unit.
