### ISSUE TITLE
protonmail-bridge - impossible to add user without gnome-keyring 

### ISSUE THREAD

**Issue by karolchmist** [NixOS/nixpkgs#45070]
## Issue description

It's impossible to add a new user in protonmail-bridge 1.0.5

cc @LightDiscord 

### Steps to reproduce

0. Add protonmail-bridge to my nix configuration 
1. Open Desktop-Bridge
2. Click Add Account
3. Fill in the form (username/password)
4. There is a message "Adding account, please wait", then "No accounts added"
5. If I run Desktop-Bridge from the terminal, there is a message :

** Message: 11:04:59.032: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: No such interface „org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

I use xfce4 without desktop : 

                desktopManager.xfce = {
                        enable = true;
                        noDesktop = true;
                        enableXfwm = false;
                };

I found a solution by enabling gnome-keyring service and restarting NixOS :

services.gnome3.gnome-keyring.enable = true; 

Should gnome-keyring be added as a dependency to protonmail-bridge ? Is there a different solution?

## Technical details

➜  ~ nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                                    - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.09.git.6afd19e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(karol): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by LightDiscord** [comment]
Yeah, I forgot to add somewhere in a documentation that the service was required for the package to work properly.

On my side I activated it (the service) and I don't think adding it as a dependency will solve the problem.

**Comment by LightDiscord** [comment]
I can't find a way to run the package without the service, adding gnome-keyring as a dependency doesn't change anything

**Comment by karolchmist** [comment]
OK, I understand. I'll add some comment in a new MR. 

Thanks for adding the bridge btw, great work!

**Comment by apeyroux** [comment]
We could also take inspiration from that? 

https://github.com/NixOS/nixpkgs/blob/1a6af9f88ec2405334a9fd6a977ccbcb53472305/nixos/modules/programs/nylas-mail.nix#L9-L22
