### ISSUE TITLE
systemd: Specified group 'render' unknown

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#45071]
## Issue description
In journalctl, I see:
```
systemd-udevd[7440]: Specified group 'render' unknown
```
Same error for "kvm".

It doesn't seem to have any other effect, but it's just sloppy. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.57, NixOS, 18.03.git.5b8a24a (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by typetetris** [comment]
`/run/current-system/systemd/lib/udev/rules.d/50-udev-default.rules` contains the offending configurations.

What would be a reasonable thing to do? Create those groups or change the default udev rules?

**Comment by typetetris** [comment]
From systemd README (obtained via `nix-shell -E '(import <nixos> {}).systemd)'` and then run unpackPhase):

> USERS AND GROUPS:
>         Default udev rules use the following standard system group
>         names, which need to be resolvable by getgrnam() at any time,
>         even in the very early boot stages, where no other databases
>         and network are available:
> 
>         audio, cdrom, dialout, disk, input, kmem, kvm, lp, render, tape, tty, video

So those groups should probably exist.
