### ISSUE TITLE
systemd: Idempotency problem

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#45113]
## Issue description
`systemctl` outputs:

```
<snip>
● fooa.service                   not-found active exited    fooa.service    
● foo.service                     loaded    active exited    foo.service    
<snip>
```

The `fooa.service` was a misspelling. I expect that after a redeployment `systemctl` shows no evidence of `fooa.service`.

**Comment by danbst** [comment]
Can't reproduce with system services defined like this
```
  systemd.services.fooa = {
    script = "while true; do echo hello; sleep 10; done";
    wantedBy = [ "multi-user.target" ];
  };
```

**Comment by globin** [comment]
I cannot reproduce this either with a system service, @coretemp is that a user service? That would be fixed by #44990 as @jtojnar mentioned.

**Comment by Mic92** [comment]
The mentioned pull request was merged, please re-test.

**Comment by coretemp** [comment]
Thanks all.

It was a system service. If a fix for a user service has been made, then it has likely not been fixed.

**Comment by globin** [comment]
Can you provide a minimal reproducible test case? Otherwise I'm inclined to close this as nobody else could reproduce this.

**Comment by coretemp** [comment]
I will open a new issue when I find it again.
