### ISSUE TITLE
libpcap fails build on Darwin

### ISSUE THREAD

**Issue by ibeex** [NixOS/nixpkgs#4515]
building pcap-linux.o
	gcc -fno-common -arch x86_64 -arch i386 -I.  -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -g -O2 -c ./pcap-linux.c
	./pcap-linux.c:137:22: fatal error: linux/if.h: No such file or directory
	 #include <linux/if.h>
	                      ^
	compilation terminated.
	make: *** [pcap-linux.o] Error 1
	builder for ‘/nix/store/0vkmb47mya5r77afjgjwqjdnn07dgy25-libpcap-1.5.3.drv’ failed with exit code 2
	error: build of ‘/nix/store/0vkmb47mya5r77afjgjwqjdnn07dgy25-libpcap-1.5.3.drv’ failed

**Comment by gridaphobe** [comment]
@ibeex `libpcap` builds fine for me on master, can you check whether you still get the "CYCLE" not found error?

**Comment by edolstra** [comment]
The `CYCLE` thing was an unrelated bug in Nix that was a while back.

**Comment by gridaphobe** [comment]
Ok, thanks!
