### ISSUE TITLE
[closure size] X11 and OpenGL libs are always in closure

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#45222]
## Issue description

Even with ```environment.noXlibs = true;``` X11 and OpenGL libs are always in closure via

udisks -> libblockdev -> libbytesize -> gtk-doc -> dblatex -> texlive -> cairo

**Comment by volth** [comment]
Maybe ```environment.noDocs``` is to be introduced to rule out all the heavy ```gtk-doc```, ```pandoc```, ```texlive```
It is useful especially for the embedded targets (ARM/MIPS/i686)

**Comment by matthewbauer** [comment]
The libbytesize -> gtk-doc looks like it should be avoidable.

**Comment by dezgeg** [comment]
If you aren't running a graphical system, disabling udisks is probably the best solution. I did it for the minimal ISO today: 571fb74f449aa173e231166515b41feb778524b8

**Comment by volth** [comment]
> If you aren't running a graphical system, disabling udisks is probably the best solution. 

I ended up with
```
      services.udisks2.enable = lib.mkDefault (!config.environment.noXlibs);
      security.polkit.enable  = lib.mkDefault (!config.environment.noXlibs);
```

Perhaps these lines are candidates for inclusion to https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/no-x-libs.nix

**Comment by volth** [comment]
yes, that might only cross-compilation issue
close for a while
