### ISSUE TITLE
maxima has no readline support/strange configuration?

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#45268]
## Issue description
When I run maxima, I can't edit my input like in bash, octave etc.

### Steps to reproduce
run maxima, try to edit your input by using the arrow keys or so.
`(%i1) foobaar^[[D^[[D`

using any key combination for editing results in printed escape characters.
one exception ctrl-u. that does delete the whole line.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.62, NixOS, 18.03.133065.e42c07d78a1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(mcd): `""`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Mic92** [comment]
For readline support, use the `rmaxima` executable instead of `maxima`.

**Comment by castilma** [comment]
thanks. apparently didn't read the manual...
