### ISSUE TITLE
callHackage creates infinite recursion in package overrides

### ISSUE THREAD

**Issue by mkawalec** [NixOS/nixpkgs#45307]
## Issue description

When using `callHackage` in packageOverrides, `nix-env` goes into an infinite loop

### Steps to reproduce

Use a `config.nix` file like:
```


{
  allowUnfree = true;
  packageOverrides = super: let self = super.pkgs; in with self; rec {

    haskell843Packages = super.haskell.packages.ghc843.override {
      overrides = self: super: {
        time = super.callHackage "time" "1.6.0.1" {};
      };
    };

    haskellPackages = haskell843Packages;


    myPackages = super.buildEnv {
      name = "my-packages";
      paths = with haskellPackages; [
        hackage-server
      ];
    };
  };
}
```

Then apply it with `nix-env -i my-packages`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.03.133114.a4e068ff9c8 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133114.a4e068ff9c8"`
 - channels(michal): `"nixpkgs-18.09pre149508.5cb9703a8fa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by mkawalec** [comment]
Using 
```
let haskellPackages = (import <nixpkgs> {}).haskellPackages;
    time = haskellPackages.callHackage "time" "1.6.0.1" {};

    hp = haskellPackages.override {
      overrides = self: super: {
        time = time;
      };
    };
in

{...
```
and then using `hp.hackage-server` fixes it, I'm unsure why

**Comment by mpickering** [comment]
This happens because `cabal2nix` depends on time. There is then a cycle `time -> cabal2nix -> time`
because we need `cabal2nix` to build time because of using `callHackage`. I recently ran into this when trying to override `hpack`.

**Comment by mpickering** [comment]
Perhaps the problem is rather that `time` is a library which is bundled with GHC. 

This example also produces an infinite recursion error : https://gist.github.com/12d835929357758004ddb7e72bd1f4e3

Looking at the dependencies, it's clear why. `time` depends on `QuickCheck` which depends on `random` which depends on `time`. 

So, the way to fix this problem is to not run the tests for `time`.

```
 time = nixpkgs.haskell.lib.dontCheck (super.callHackage "time" "1.6.0.1" {});
```

**Comment by mkawalec** [comment]
Ah, good reasoning. I'll try to find the time to write a blog post to tell people to use the latter method, in case cabal2nix depends (transitively) on some other package they're overriding.

**Comment by mpickering** [comment]
I don't think this is a problem with `cabal2nix`. I could reproduce it without invoking `callHackage`.
