### ISSUE TITLE
recent `_module.args.pkgs` errors over missing `system.slice`

### ISSUE THREAD

**Issue by tycho01** [NixOS/nixpkgs#45308]
## Issue description
Pinning `_module.args.pkgs` on a nixpkgs commits from https://github.com/NixOS/nixpkgs/pull/43682/commits/7098b0fcdfd7fa4b82c036d8116b60b78f497316 I'm getting the following build error:
```
building '/nix/store/8pzgi5p8cskvhvznr1pzdra34rmqxcfv-system-units.drv'...
missing /nix/store/dsw42cg2n5qh5v6vxm9i1qh279fa4bw2-systemd-239/example/systemd/system/system.slice
builder for '/nix/store/8pzgi5p8cskvhvznr1pzdra34rmqxcfv-system-units.drv' failed with exit code 1
```
This seems related to the removal of `system.slice` in https://github.com/systemd/systemd/commit/d8e5a9338278d6602a0c552f01f298771a384798.

### Steps to reproduce
`sudo nixos-rebuild switch` using config in https://github.com/tycho01/nix-config/tree/pin/

## Technical details

`nix-shell -p nix-info --run "nix-info -m"` output:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.132646.08d245eb31a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132646.08d245eb31a"`
 - channels(tycho): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by primeos** [comment]
@tycho01 It seems like the `nixpkgs` version you're using doesn't contain 0ccab4946d5d0405ebced50a7b7f847730d502a9 (that was the commit that removed `system.slice` from `upstreamSystemUnits`) and you've pinned `_module.args.pkgs` to another version that does (i.e. `system.slice` is still expected but you're already using `systemd 238` or later.

I'm not sure if it's a good idea to pin `_module.args.pkgs` to a different version in general (could cause other problems like this one).

**Comment by tycho01** [comment]
Okay, I'll try channels then. Thanks!

**Comment by primeos** [comment]
Just to clarify: Pinning `nixpkgs` to a specific revision shouldn't cause any problems (at least if the `tested` job passed / it was released to a channel, e.g. `nixos-unstable`). But if I'm not mistaken you're pinning the `pkgs` attribute to a different revision than `<nixpkgs>`. This could cause problems because the system configuration won't necessarily be compatible with the pinned package versions (like in this case).

Also: Doing something like this should normally be fine as well:
```nix
environment.systemPackages = with (import /var/nixos-unstable {}).pkgs; [
  firefox chromium ...
];
```
