### ISSUE TITLE
Haskell / shellFor broken due to recent commit

### ISSUE THREAD

**Issue by choener** [NixOS/nixpkgs#45318]
## Issue description
```haskellPackages.shellFor``` now aborts with
```error: value is a list while a set was expected, at /home/choener/tmp/nix/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:236:47```

### Steps to reproduce
on ```release-18.03``` switch between commits
9cbc7363543ebeb5a0182aa171f23bb19332b99f (last working) and
66bd479f261152e99f609e8f6826f30dd13e1d8f (introduces the error for me)

use this ```default.nix``` and ```nix-shell --arg pkgs ~/tmp/nix/nixpkgs -A hsShell```
```
{ pkgs ? <nixpkgs> }:
with (import pkgs {});
with haskell.lib;
with builtins;

{
  hsShell = with haskellPackages; shellFor {
    packages = p: [ p.vector ];
  };
}
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133023.18401b99f3f (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133114.a4e068ff9c8"`
 - channels(choener): `"unstable-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by mpickering** [comment]
@shlevy
