### ISSUE TITLE
gvfs-trash needs gio on the PATH

### ISSUE THREAD

**Issue by kampka** [NixOS/nixpkgs#45344]
## Issue description

The `gvfs-trash` command is currently broken, as it relies on `gio` being on the PATH.
This in return breaks other packages that rely on `gvfs-trash` to work, like the Atom editor.

`gio` is currently shipped by `glib.dev`
Installing the `glib.dev` package (either via environment.systemPackages or nix) is a current workaround.

### Steps to reproduce

```shell
$ cat /run/current-system/sw/bin/gvfs-trash

replacement="gio trash"
help="gio help trash"
>&2 echo "This tool has been deprecated, use '$replacement' instead."
>&2 echo "See '$help' for more info."
>&2 echo
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  exec $help "$@:2"
else
  exec $replacement "$@"
fi
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.132865.411cc559c05 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixpkgs-unstable-18.09pre146103.d3ed77f1fb1, nixos-18.03.132865.411cc559c05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by hedning** [comment]
Relevant PR: #38486

**Comment by jtojnar** [comment]
Closing as gvfs executables were removed in https://github.com/NixOS/nixpkgs/pull/45950
