### ISSUE TITLE
dhcpcd prevents interface renaming from working

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#45346]
## Issue description
#44524 breaks the predictable interface naming in presence of eg. dhcpcd: https://hydra.nixos.org/build/79855242/nixlog/1

This blocks nixos-unstable.

### Steps to reproduce
`nix-build nixos/tests/predictable-interface-names.nix -A predictable`

## Technical details
Confirmed broken on 63d8458ee05592f2f3293703982031de9792c697

**Comment by srhb** [comment]
Should we just throw an `ExecStartPre = "udevadm settle"` at it?

**Comment by samueldr** [comment]
*Should this now be closed?*
