### ISSUE TITLE
Enabling ntp sync conflict with nixos-rebuild build-vm #2362

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#45368]
I enabled ntp sync by
```
services.timesyncd.enable = true
```
in my configure.nix
then nixos-rebuild build-vm does not work. it complains

```
$> nixos-rebuild build-vm
building Nix...
building the system configuration...
error: The option `services.timesyncd.enable' has conflicting definitions, in `/etc/nixos/services.nix' and `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix'.
(use '--show-trace' to show detailed location information)
```

(
originally submitted the issue in [nix](https://github.com/NixOS/nix/issues/2362)
As is suggested by @peterhoeg [](https://github.com/NixOS/nix/issues/2362#issuecomment-414205343) I resubmit the issue here.
)

**Comment by peterhoeg** [comment]
Have a look at ```qemu-vm.nix``` - https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/qemu-vm.nix#L531

You are setting a value that is already being set in that module.

**Comment by astrojhgu** [comment]
Yes, but if I want to use build-vm, I don't want to modify my configure.nix. Is there any way to solve this problem?

**Comment by peterhoeg** [comment]
You can use ```lib.mkForce```:

```
services.timesyncd.enable = lib.mkForce true;
```

**Comment by astrojhgu** [comment]
Thanks, solved.
