### ISSUE TITLE
conan doesn't build since it was updated to 1.6.0

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#45395]
Builds here: https://hydra.nixos.org/job/nixpkgs/staging/conan.x86_64-linux/all

It seems to be missing cmake and pythonPackages.pkgconfig.

cc @talyz

**Comment by arximboldi** [comment]
I might be hitting this. Is there a workaround?

**Comment by dotlambda** [comment]
I think there is simply noone who's willing to maintain conan. If nobody steps up, I suggest marking the package as broken.

**Comment by HaoZeke** [comment]
I have fixed and updated the package in https://github.com/NixOS/nixpkgs/pull/53380.
However there is actually not much use for `conan` environments with `nix` so I am not sure about mantaining it.

**Comment by arximboldi** [comment]
Yeah after trying to use Conan inside NixOS I am realising it is kinda hard since dependencies fetched through Conan often don't work because either a) if they are binaries, they have link time dependencies or b) when they are built from source they need patches to build inside Nixos (e.g. Qt).

**Comment by HaoZeke** [comment]
That aside, using Conan practically guarantees that you can't do a nix build, since that's done without network connectivity. 


________________________________

**Comment by arximboldi** [comment]
However, Nix does not work on Windows so some projects need something else. It'd be nice to be able to work on NixOS on projects that use Conan for this reason. My solution now is to have a duplicate Nix environment, but it might not be possible if the build system relies too much on Conan. But yeah that is another story...

**Comment by HaoZeke** [comment]
Does nix not work under the WSL distributions?

**Comment by HaoZeke** [comment]
I suppose you would need to modify the nix builds to cross compile the programs for windows.

**Comment by arximboldi** [comment]
Exactly, you need to redo Nixpkgs basically... :)
