### ISSUE TITLE
OpenSSL closure size increase

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#45460]
## Issue description

The closure size of `openssl` has increased from 79 MiB in NixOS 18.03 to 451 MiB on master. This appears to be due to the fact that `libcrypto.so` now has a reference to `gcc-wrapper`, which in turn pulls in `binutils` and `glibc.dev`:

```
$ nix why-depends -f . openssl glibc.dev
/nix/store/gmw7hcg1zjqzlbhwx89ldfb477jb4hi0-openssl-1.0.2p-bin
╚═══bin/c_rehash: … values...my $dir = "/nix/store/clp002qa61cjy9ab0zaasb9w97p4yyk2-openssl-1.0.2p/etc/ssl";.my $pr…
    => /nix/store/clp002qa61cjy9ab0zaasb9w97p4yyk2-openssl-1.0.2p
    ╚═══lib/libcrypto.so.1.0.0: …...........compiler: /nix/store/9z650yzczx5zyhcw5n36ya6x4jq436mr-gcc-wrapper-7.3.0/bin/gcc -I. -…
        => /nix/store/9z650yzczx5zyhcw5n36ya6x4jq436mr-gcc-wrapper-7.3.0
        ╚═══nix-support/libc-cflags: …2.27/lib/ -idirafter /nix/store/i4n918fnq0wgryan523pfbdck57fpqzc-glibc-2.27-dev/include -idiraft…
            => /nix/store/i4n918fnq0wgryan523pfbdck57fpqzc-glibc-2.27-dev
```

**Comment by Mic92** [comment]
This string should adapted to not include the full gcc wrapper path.
https://github.com/openssl/openssl/blob/8a8d9e190533ee41e8b231b18c7837f98f1ae231/crypto/cversion.c#L27

**Comment by Mic92** [comment]
It is generated here:

https://github.com/openssl/openssl/blob/8a8d9e190533ee41e8b231b18c7837f98f1ae231/util/mkbuildinf.pl#L12

**Comment by edolstra** [comment]
This is probably caused by the fact that `$CC` is now set to an absolute path rather than just `gcc`.

**Comment by edolstra** [comment]
I guess this is fixed by https://github.com/NixOS/nixpkgs/pull/45442.

**Comment by vcunat** [comment]
Sounds fairly good now.
```
$ nix path-info -f . openssl.out -r | xargs du -sc | sort -n
3616    /nix/store/9kr8r78bwk12050ppywfbhg1vrsd6dp8-openssl-1.0.2p
26428   /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27
30044   total
```
