### ISSUE TITLE
Paraview 5.5.2 aborts on startup

### ISSUE THREAD

**Issue by dksim** [NixOS/nixpkgs#45496]
## Issue description
Starting paraview 5.5.2 fails with an abort. 

### Steps to reproduce
Start paraview

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133004.a1299c9951b (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-unstable, nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by JohnAZoidberg** [comment]
Fixed by #72891
