### ISSUE TITLE
Steam's "Steam Play" feature does not work on NixOS

### ISSUE THREAD

**Issue by tgharib** [NixOS/nixpkgs#45492]
## Issue description

For background info, Steam Play is Valve's new compatibility layer that allows you to run any Windows-only game as long as you have Steam installed. [Here](https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561) is the announcement.

The feature partially works on NixOS. It allows you run a Windows game for about a minute but it eventually crashes with error `eventfd: Too many open files`. This issue is documented [here](https://github.com/ValveSoftware/Proton/issues/32) and is ultimately because the linux kernel is not configured to support enough file descriptors. Running `ulimit -Hn`, I get a result of 4096 file descriptors per process.

This is not the first time this issue has caused problems for NixOS. See https://github.com/NixOS/nix/issues/875 and https://github.com/NixOS/nixpkgs/issues/22454. For modules, I see [here](https://search.nix.gsc.io/?q=LimitNOFILE) that it is possible to increase the limit. Is this possible to do so on a per-package basis (for steam)? Or should this limit be increased globally for the entire distro?

### Steps to reproduce

1. Install steam
2. Try to run a windows-only game via Steam Play

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
[owner@Taha-Desktop-Linux:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(owner): `"nixos-18.09pre145524.2a8a5533d18, stable-18.03.132845.5e10df3982d"`
 - channels(root): `"nixos-18.09pre149415.8395f9aa85e, stable-18.03.133017.0e55dde2eaa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by puffnfresh** [comment]
I played Sonic Mania for a while (probs 40 minutes) and didn't hit this problem. Is it only certain games?

**Comment by tgharib** [comment]
According to this [document](https://github.com/zfigura/wine/blob/esync/README.esync), "esync creates one eventfd descriptor for each synchronization object". Honestly, I don't fully understand what a "synchronization object" is but it appears that some games require more synchronization objects. The game I tested was Quake Live.

**Comment by tadfisher** [comment]
Steam uses `buildFHSUserEnv` which internally creates a user namespace. This namespace will be limited to your user namespace's ulimit, so ultimately the fix is either to raise the ulimit globally in systemd or configure a separate user with a higher ulimit and run steam as that user.

**Comment by tadfisher** [comment]
Another option is to disable esync via `PROTON_NO_ESYNC=1`. You can set this per-game in Steam's launch options (`PROTON_NO_ESYNC=1 %command%`) or in Steam's environment.

**Comment by Wolfereign** [comment]
@tgharib Did you package the new version of steam yourself?  The version in the repo seems to be pretty far out of date.

**Comment by tadfisher** [comment]
@Wolfereign Steam installs itself to the user's home on first boot (`~/.local/share/Steam`) so the package version doesn't really matter.

Incidentally, I've found that Steam Play doesn't work at all unless I override with `steam.override { nativeOnly = true; }`.

**Comment by Wolfereign** [comment]
@tadfisher Thank you for the info.  I haven't tried to install Steam yet but that cleared up alot of confusion that I had.  My apologies for derailing the thread a bit.

**Comment by cpages** [comment]
> Incidentally, I've found that Steam Play doesn't work at all unless I override with steam.override { nativeOnly = true; }.

@tadfisher what nixos version are you on? I just found out native is marked broken both in master and 18.03. Still, I confirm it works for me and indeed I could play a game with steam play that was not working without the override

@abbradar is it still segfaulting for you?

**Comment by Chiiruno** [comment]
As for the ulimit issue, this works for me:
```
# Set limits for esync.
systemd.extraConfig = "DefaultLimitNOFILE=1048576";

security.pam.loginLimits = [{
    domain = "*";
    type = "hard";
    item = "nofile";
    value = "1048576";
}];
```

**Comment by davidak** [comment]
I have played some (older) games using Steam play and never had such problems. So it's not a general issue but affect only some games.

**Comment by xfix** [comment]
I also did not experience issues with Steam Play on NixOS. It's probably a very specific game that crashes without increasing the file handle limit.

**Comment by solson** [comment]
I can't remember why I subscribed to this issue a couple years ago, but I've also been using Steam Play on NixOS for quite a while now without this issue.

**Comment by xfix** [comment]
As I mentioned in #86480, I don't think `programs.steam.enable` should change file handle limit, if anything because Ubuntu has the same file handle limit as NixOS. If file handle limit causes issues on NixOS, it will also cause them on Ubuntu (which is officially supported by Valve).

**Comment by baracoder** [comment]
Great, looks like this issue is resolved :tada:
