### ISSUE TITLE
VLC segfaults on opening of a file

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#45508]
## Issue description

VLC segfaults on opening of a file.

### Steps to reproduce

With current `nixos-unstable`, run VLC and try to open a video file. Here is what it prints before dying:

```
[mark@nixos:~]$ vlc
VLC media player 3.0.3 Vetinari (revision 3.0.2-225-gc9e3360dd4)
[000000000070f5d0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[0000000000710ab0] main playlist: playlist is empty
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007f95c8019840] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007f95c8019840] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007f95c8019840] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Segmentation fault
```

Used to work.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6338_45bcf541`
 - channels(root): `"nixos-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by emmanuelrosa** [comment]
It works on my system:

```
VLC media player 3.0.3 Vetinari (revision 3.0.2-225-gc9e3360dd4)
[000000000126b5d0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.                                                                                 
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007f30c4004070] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007f30c4004070] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007f30c4004070] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory                                                                                        
QObject::~QObject: Timers cannot be stopped from another thread
```
My computer has an Intel GPU and is using the i965 driver. Are you using a Radeon GPU?

**Comment by mrkkrp** [comment]
Yes.

**Comment by emmanuelrosa** [comment]
Do you happen to know the NixOS version of when it used to work?

**Comment by mrkkrp** [comment]
It worked in July I think...

**Comment by emmanuelrosa** [comment]
What you can do is use a clone of this repo with `git bisect` to figure out which commit caused the problem. You already have a bad commit, but you'll need to find a good one manually. Once you have those you can use `git bisect` with `cvlc [file]` as your test. That would help automate the process.

**Comment by bjornfor** [comment]
VLC segfaults for me on NixOS 18.03 too.

**Comment by bjornfor** [comment]
Bisecting on release-18.03 points to d96ade368ca8cdebeb9b418c7bc23b54b20e20e7 ("vlc: 2.2.8 -> 3.0.3"). I find that weird, because I'm pretty sure I successfully ran VLC 3.x when it first hit NixOS 18.03.

**Comment by mrkkrp** [comment]
BTW, VLC now works for me after an update. I have no idea what is going on.

**Comment by bjornfor** [comment]
I think the segfault was due to conflicting libraries in my system and user profile. Uninstalled vlc ("nix-env -e vlc") and used the one in my system profile and now it works (on nixos 18.09.821.4dd9cd3f69e).

**Comment by shazow** [comment]
I believe this is related to the system's `hardware.opengl.extraPackages` options. I'm not sure which subset is required, but probably at least `vaapiVdpau`, possibly `libvdpau-va-gl` and others?

**Comment by volth** [comment]
I hit this on 19.03 -> 19.09 update

```
hardware.opengl.enable = true;
hardware.opengl.extraPackages = [
  pkgs.intel-ocl
  pkgs.vaapiIntel
  pkgs.vaapiVdpau
  pkgs.libvdpau-va-gl
];
```
did help (perhaps some of them are needless)

**Comment by Avaq** [comment]
This issue has started occurring for me after a recent update. I have been using vlc without issues for a few years. I tried the solution described here (https://github.com/NixOS/nixpkgs/issues/45508#issuecomment-478262448), which removes some of the errors being logged, but in the end vlc still segfaults.

**Comment by SuperSandro2000** [comment]
Closing this as the issue is very stale and this was likely a specific configuration issue.
