### ISSUE TITLE
Enable -O2 for haskell packages by default

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#45579]
Currently haskell packages are not built with any optimizations, that's a real shame, since GHC does a lot to improve peformance there.

**Comment by mpickering** [comment]
Is this actually true?  The interface files have unfoldings in.

**Comment by domenkozar** [comment]
I saw no `-O2` at configuration time, is it somehow implicit (default?).

**Comment by matthewbauer** [comment]
Cabal defaults to -O1.

**Comment by nh2** [comment]
> Currently haskell packages are not built with any optimizations

Certainly not, I would have noticed that by now. It is the case that

> Cabal defaults to -O1.

The confusing bit is that `ghc` (like GCC) defaults to `-O0` but `Cabal` defaults to `-01`. Crops up all the time.

I think the best idea is to keep it as is, letting cabal files of packages decide the optimisation level.

**Comment by ElvishJerricco** [comment]
Also don't a lot of libraries specify `-O2` in their cabal files?

**Comment by domenkozar** [comment]
Sounds good, usually compilers default to no optimizations, as @nh2 said. I was confusing to me that GHC defaults to `-O0`, while Cabal defaults to `-O1`. Anyway, nothing to fix in nixpkgs.
