### ISSUE TITLE
Backtick Glyph (`) overlapping/rendering error in Firefox

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#45621]
## Issue description

The backtick glyph (\`) is rendered in a strange way in some input forms in Firefox, esp. on Github, making it a bit weird when quoting stuff in Markup.

It on the one hand is rendered one character to the right overlapping the character at that position and looking like an accent, and it overlaps it self when adding several after another.

E.g. T\`est looks like Tèst.

On my system:

![example](https://user-images.githubusercontent.com/100848/44617820-3c82b980-a86a-11e8-9a8e-1b027673fb00.png)

Block quotes look like this in the Markup editor on github.

![blockquote](https://user-images.githubusercontent.com/100848/44617818-3096f780-a86a-11e8-8cb2-da0ccd96ccc6.png)

Note, that there are three backticks, but they are overlapping.

The issue is present since I set up my system, beginning with 17.03.

### Steps to reproduce

Running Firefox with my [NixOS config](https://github.com/Moredread/nixos-config)... XD

I'm not sure if this is a NixOS issue, but I never had it happen anywhere else

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.18, NixOS, 18.03.133157.fde20125199 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6338_45bcf541`
 - channels(root): `"nixos-18.03.133157.fde20125199, nixos-unstable-18.09pre149415.8395f9aa85e"`
 - channels(addy): `"nixos-18.03, nixos-unstable"` (Linked to root channels)
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
- graphics driver: intel X11 driver with i915 kernel driver

**Comment by symphorien** [comment]
Is backtick a dead key ? That is: two times backtick gives one backtick and backtick  + vowel makes an accentuated vowel ? if so try to change your keyboard layout to one where backtick is not a dead key.

**Comment by samueldr** [comment]
A weird way to check if the issue is with the inputted character, or with the rendering of the character could be to copy this sample backtick: <code>\`</code> and paste it in the same situations, where it would combine with a letter.

This strangely looks like a [combining grave accent](https://www.fileformat.info/info/unicode/char/0300/index.htm) <code>̀</code> which combines with the character to its left <code>è</code> instead of <code>e\`</code>.

> **NOTE** when saving the post, github *could* realistically replace the combining grave accent with a "real" backtick through unicode normalization. **Only** the first backtick is expected to stay valid after I press save.

**Comment by Moredread** [comment]
I finally found the culprit. It was `fonts.fontconfig.ultimate.enable`, which also caused other rendering issues.

`penultimate` in contrast seems to work fine.

**Comment by drupol** [comment]
Sorry to dig up such an old topic, but I currently have the same issue and I don't use the `ultimate` font.

**Comment by samueldr** [comment]
@drupol Please open a new issue instead of re-opening one that sounds similar.

Also explain details of your observations in full. Similar sounding symptoms could be different enough to matter.
