### ISSUE TITLE
OpenGL packages on master branch segfaulting when ~/.drirc is missing

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#45620]
## Issue description

Several packages using OpenGL segfault when I build them against the master branch and run them on a 18.03 system. I wanted to update `flightgear` and ran into this problem while testing.

I also get

`
traps: glxinfo[29912] general protection ip:7f0eba919320 sp:7fff011f8538 error:0 in libc-2.27.so[7f0eba7a4000+1aa000]
`

in the syslog.

### Steps to reproduce

run

```
nix-build -A glxinfo
./result/bin/glxinfo
```

in a checkout of `nixpkgs` on the `master` branch.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.18, NixOS, 18.03.133157.fde20125199 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6338_45bcf541`
 - channels(root): `"nixos-18.03.133157.fde20125199, nixos-unstable-18.09pre149415.8395f9aa85e"`
 - channels(addy): `"nixos-18.03, nixos-unstable"` (Linked to root channels)
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
- graphics driver: intel X11 driver with i915 kernel driver

**Comment by Moredread** [comment]
When running strace against glxinfo I get at the end

```
openat(AT_FDCWD, "/home/addy/.drirc", O_RDONLY) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV +++
```

After touching `~/.drirc`  glxinfo works.... oO

**Comment by Moredread** [comment]
It doesn't happen anymore on my 18.09 system... Closing it for now.

**Comment by vcunat** [comment]
It's possible we'll run into this once more after master diverges more sufficiently from stable.  The impurity we do with OpenGL might behave like that...
