### ISSUE TITLE
pygobject3 introspection typelib not found

### ISSUE THREAD

**Issue by kenogo** [NixOS/nixpkgs#45662]
## Issue description

I tried installing the pygobject3 package for python 3.6 and when I try to use it, I get the following error:
```
>>> from gi.repository import Gtk
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
AttributeError: 'DanymicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/bijj10xrw03pzc3f9i7zaiqj3bgzc2pf-python3-3.6.6-env/lib/python3.6/site-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Gtk, introspection typelib not found
```

### Steps to reproduce

Install the package `nixpkgs.python36Packages.pygobject3` and run the command above.

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m "
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(keno): `""`
 - channels(root): `"nixos-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hedning** [comment]
`nix-shell -p 'python3.withPackages (p: [p.pygobject3])' --run python` seems to work for me (though not very obvious that's a thing). Installing python libraries directly with eg. nix-env isn't really supported: https://nixos.wiki/wiki/Python

**Comment by kenogo** [comment]
@hedning Well I installed it by following that wiki article and puting the following in my `configuration.nix`:

```
{ config, pkgs, ... }:

with pkgs;
let
  my-python-packages = python-packages: with python-packages; [
    pygobject3
  ];
  python-with-my-packages = python3.withPackages my-python-packages;
in

{
  environment.systemPackages = with pkgs; [
    python-with-my-packages
  ];
}
```

Did I do anything wrong?

**Comment by FRidh** [comment]
This is an actual issue. I think `INTROSPECTION_TYPELIBDIR` or `GI_TYPELIB_PATH` needs to be set but I don't think we can or should do that in the library.

**Comment by FRidh** [comment]
@jtojnar knows more about gnome/gtk.

**Comment by jtojnar** [comment]
`pygobject3` is basically just a loader that tries to load whatever imported from `gi.repository` module. It looks the modules up in `GI_TYPELIB_PATH` environment variable. `gobjectIntrospection` package has a setup hook that sets the path from dependencies listed in `buildInputs` (or `-p` flags for `nix-shell`).

Using `nix-shell` is recommended for REPLs for testing libraries and you can do something like the following:

```
nix-shell -p 'python3.withPackages (p: [p.pygobject3])' -p gtk3 -p gobjectIntrospection --run python
```

If you really want to have the REPL installed, you will need to make the environment variable available at run-time – either by manually creating a wrapper script:

```nix
(writeScriptBin "python-with-gtk" ''
  #!/bin/sh
  export GI_TYPELIB_PATH=${lib.makeSearchPathOutput "lib" "lib/girepository-1.0" [ gtk3 pango gdk_pixbuf ]} # some others typelibs might be needed
  ${python3.withPackages (p: [p.pygobject3])}/bin/python
'')
```

or better, letting `gobjectIntrospection` populate the variable:


```nix
(runCommand "python-with-gtk" {
    buildInputs = [ gtk3 ];
    nativeBuildInputs = [ gobjectIntrospection ];
  }  ''
  echo "#!/bin/sh" >> $out/bin/python-with-gtk
  echo "export GI_TYPELIB_PATH=$GI_TYPELIB_PATH" >> $out/bin/python-with-gtk
  echo "${python3.withPackages (p: [p.pygobject3])}/bin/python" >> $out/bin/python-with-gtk
'')
```

or even better, letting `wrapGAppsHook` create the script for you:

```nix
(runCommand "python-with-gtk" {
    buildInputs = [ gtk3 ];
    nativeBuildInputs = [ gobjectIntrospection wrapGAppsHook ];
  } ''
  cp ${python3.withPackages (p: [p.pygobject3])}/bin/python $out/bin/python-with-gtk
'')
```

See the following files for deeper understanding what is happening here:
* https://github.com/NixOS/nixpkgs/blob/718ee42eb974c52e0e0c7b56c70cd7dabcaf09b7/pkgs/build-support/trivial-builders.nix
* https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gobject-introspection/setup-hook.sh
* https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/wrap-gapps-hook.sh

**Comment by symphorien** [comment]
See also the brief explanation here: https://nixos.wiki/wiki/Python#Gnome

**Comment by kenogo** [comment]
@jtojnar Thanks a lot for your reply! I'm new to nixos though, and I don't quite understand where to put your code.

**Comment by jtojnar** [comment]
@kenogo It should work in `environment.systemPackages`. All three expressions create a package containing `/bin/python-with-gtk` file.

**Comment by kenogo** [comment]
@jtjonar It gives me the error message:
```
cannot create regular file '/nix/store/...-python-with-gtk/bin/python-with-gtk': No such file or directory
```

**Comment by jtojnar** [comment]
Right, maybe add `mkdir -p $out/bin` before the `cp` command.

**Comment by kenogo** [comment]
@jtjonar Thank you very much. The third example with `wrapGappsHook` now installs but the resulting `python-with-gtk` still returns the same error about missing typelib. The second example installs (after also adding `chmod +x $out/bin/python-with-gtk` and works, except for some reason python only starts interactively. So running `python-with-gtk program.py` gives me an interactive shell instead of launching the program...

**Comment by kenogo** [comment]
It's because the file `python-with-gtk` calls `/nix/store/...-python3-3.6.6-env/bin/python` without passing parameters at the end. So all that was needed was adding `echo " \"\$@\"" >> $out/bin/python-with-gtk`

**Comment by gnidorah** [comment]
@jtojnar Do you know why this works
```
nix-shell -i python3 -p gobjectIntrospection "[ libnotify ]" "python3.withPackages (ps: with ps; [ pygobject3 ])"
```
while this raises error
```
#!nix-shell -i python3 -p "[ gobjectIntrospection libnotify ]" "python3.withPackages (ps: with ps; [ pygobject3 ])"
ValueError: Namespace Gtk not available
```

**Comment by jtojnar** [comment]
@gnidorah No idea, did not even know you can pass a list as package to `nix-shell`. You can try dumping the environment variables, though, I guess that would be more related to nix-shell and setup hooks than gobject-introspection anyway.

**Comment by timokau** [comment]
@jtojnar I still don't quite understand why we can't patch `pygobject` to set `GI_TYPELIB_PATH`. Maybe its because I don't know what a `gobject` is. Could you elaborate?

Maybe this guix patch is relevant: https://lists.gnu.org/archive/html/guix-devel/2016-03/msg00218.html

**Comment by jtojnar** [comment]
When you use `from gi.repository import Foo`, `pygobject` (well glib really) will search `GI_TYPELIB_PATH` and in each directory in the environment variable, it will try to find `Foo.typelib` file. We cannot hard-code any paths to `pygobject` because we do not know which typelibs will the user want. On the other hand, when we know which typelibs are needed, we can add their paths to the environment variable and that is exactly what `wrapGAppsHook` does. We even do it manually in code in places where wrapping is not possible like [GNOME Shell extensions](https://github.com/NixOS/nixpkgs/blob/ada7cf0c66e600f7479a7206f1677c5d5236c476/pkgs/desktops/gnome-3/extensions/system-monitor/paths_and_nonexisting_dirs.patch#L9-L10)

**Comment by jtojnar** [comment]
The patch does not really make much sense without context but I am guessing it does the same thing our `gobject-introspection.setupHook` does, maybe we could propagate that from `pygobject`.

For more information about the GNOME-related environment variables, see https://github.com/NixOS/nixpkgs/pull/43150

**Comment by timokau** [comment]
> We cannot hard-code any paths to `pygobject` because we do not know which typelibs will the user want

So if I want `graph-tool` to work (which fails because of `pygobject`), the right thing to do would be to hardcode the libraries in `graph-tool`?

**Comment by jtojnar** [comment]
Yup. If it is just a program, adding `wrapGAppsHook` to `nativeBuildInputs` is the thing to do. If it is a library, either the dependents will need to be wrapped, or the library patched like the extensions.
