### ISSUE TITLE
Firefox takes 30+ seconds to start if networking.hostName is not in DNS resolution

### ISSUE THREAD

**Issue by redfish64** [NixOS/nixpkgs#45671]
## Issue description

I believe this started happening with Firefox 60.0+. If networking.hostName in configuration.nix is set to a nonexistent name, firefox seems to try and resolve the hostname for 30 seconds before starting up. I have no addons or plugins installed.

I found a workaround, where if I add the following to configuration.nix (replacing "yellowhat" with whatever networking.hostName has been set to), will fix the problem:

  networking.extraHosts = ''
127.0.0.1   yellowhat
'';

Not sure what the fix should be. Maybe the networking.hostName should be automatically added to /etc/hosts?

### Steps to reproduce

Set networking.hostName in configuration.nix to a unresolveable hostname. 
Start firefox

## Technical details

I figured this out by running strace against firefox and getting:

connect(7, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.42.129")}, 16) = 0
poll([{fd=7, events=POLLOUT}], 1, 0)    = 1 ([{fd=7, revents=POLLOUT}])
sendto(7, "\232m\1\0\0\1\0\0\0\0\0\1\tyellowhat\0\0\1\0\1\0\0)\4\260"..., 38, MSG_NOSIGNAL, NULL, 0) = 38
poll([{fd=7, events=POLLIN}], 1, 5000)  = 0 (Timeout)
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 8
connect(8, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.0.1")}, 16) = 0
poll([{fd=8, events=POLLOUT}], 1, 0)    = 1 ([{fd=8, revents=POLLOUT}])
sendto(8, "\232m\1\0\0\1\0\0\0\0\0\1\tyellowhat\0\0\1\0\1\0\0)\4\260"..., 38, MSG_NOSIGNAL, NULL, 0) = 38
poll([{fd=8, events=POLLIN}], 1, 5000)  = 0 (Timeout)
poll([{fd=7, events=POLLOUT}], 1, 0)    = 1 ([{fd=7, revents=POLLOUT}])
sendto(7, "\232m\1\0\0\1\0\0\0\0\0\1\tyellowhat\0\0\1\0\1\0\0)\4\260"..., 38, MSG_NOSIGNAL, NULL, 0) = 38
poll([{fd=7, events=POLLIN}], 1, 5000)  = 0 (Timeout)
poll([{fd=8, events=POLLOUT}], 1, 0)    = 1 ([{fd=8, revents=POLLOUT}])
sendto(8, "\232m\1\0\0\1\0\0\0\0\0\1\tyellowhat\0\0\1\0\1\0\0)\4\260"..., 38, MSG_NOSIGNAL, NULL, 0) = 38

192.168.42.129 is my dns entry in /etc/resolv.conf and "yellowhat" is my chosen hostname

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

[tim@yellowhat:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(tim): `"nixpkgs-18.09pre149415.8395f9aa85e"`
 - channels(root): `"nixos-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/home/tim/.nix-defexpr/channels/nixpkgs`

**Comment by xaverdh** [comment]
I have the same issue with mutt.

**Comment by oxij** [comment]
Should be solved by #47241.

**Comment by oxij** [comment]
I believe this was solved by #47241.
