### ISSUE TITLE
git-annex: lost support for s3 remotes

### ISSUE THREAD

**Issue by bchallenor** [NixOS/nixpkgs#45686]
I expected git-annex to support S3 remotes out of the box, but it does not:

```
$ git annex version
git-annex version: 6.20180807
build flags: Assistant Pairing WebDAV Inotify DBus DesktopNotify ConcurrentOutput TorrentParser MagicMime Feeds Testsuite                                
dependency versions: bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.2 feed-1.0.0.0 ghc-8.4.3 http-client-0.5.13.1 persistent-sqlite-2.8.1.2 torrent-10000.1.1 uuid-1.3.13
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL     
remote types: git gcrypt p2p bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external                                              
operating system: linux x86_64
supported repository versions: 3 5 6
upgrade supported from repository versions: 0 1 2 3 4 5
```

I have not figured out the Haskell build system sufficiently to produce a PR, I'm afraid. But there should simply be an `s3` flag as mentioned on a [similar Homebrew issue](
https://github.com/Homebrew/legacy-homebrew/issues/47737).

*edit* The [Hackage page for git-annex](https://hackage.haskell.org/package/git-annex) says the flag is enabled by default, so I'm not sure what is going on here.

**Comment by bchallenor** [comment]
Note this seems to be a regression as the currently stable version includes the `s3` flag:

```
$ git annex version
git-annex version: 6.20180626
build flags: Assistant Webapp Pairing S3(multipartupload)(storageclasses) WebDAV Inotify DBus DesktopNotify ConcurrentOutput TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.18 bloomfilter-2.0.1.0 cryptonite-0.24 DAV-1.3.2 feed-1.0.0.0 ghc-8.2.2 http-client-0.5.10 persistent-sqlite-2.6.4 torrent-10000.1.1 uuid-1.3.13 yesod-1.4.5
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external
operating system: linux x86_64
supported repository versions: 3 5 6
upgrade supported from repository versions: 0 1 2 3 4 5
```

**Comment by xeji** [comment]
cc maintainer @peti

**Comment by peti** [comment]
S3 support has been disabled intentionally in https://github.com/NixOS/cabal2nix/commit/4702a5058f0a70fa910a3c9407ad18dbba370fe5 because we cannot compile `git-annex` with that feature enabled. If I recall it correctly, then the problem was that recent versions of `aws` conflict with all kinds of other dependencies from the `conduit` ecosystem. I'm not entirely sure, though, it's been a while.

**Comment by seanparsons** [comment]
This could do with being in the release notes for 18.09, I only stumbled on this because I tried to use it on my Macbook. @peti Is there a way of creating a separate derivation for it manually that I can do to get past this? I would expect a sizable number of those people using git annex use the S3 remotes.

**Comment by bchallenor** [comment]
For reference, this commit explains why it is hard to compile git-annex with S3 support right now: https://github.com/NixOS/nixpkgs/commit/dcd037c14aabfa879a92eb15556dd7208f8ed50a

**Comment by peti** [comment]
There is nothing we can do about this issue at the moment. This needs to be fixed in git-annex's dependency chain.

**Comment by seanparsons** [comment]
@peti As of 7.20181121 esqueleto is not a dependency of git-annex: http://hackage.haskell.org/package/git-annex-7.20181121/changelog

**Comment by peti** [comment]
935c1f7ccde5bb0752f285c366095e118e6cae0a will enable support for s3 remotes again when it reaches `master`. Should be there in a day or two.
