### ISSUE TITLE
fetchgitPrivate does not construct reproducible derivation

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nixpkgs#45694]
## Issue description

`fetchgitPrivate` takes in nix paths like `ssh-config-file` and `ssh-auth-sock`, both of which are essentially side effects leaking into the building process. It constructs irreproducible derivations when it is built against an alternative nix store location where references to `<ssh-config-file>` and `<ssh-auth-sock>` are shielded from the `chroot`ed building environment. This shows that `fetchgitPrivate` is **impure**.

What it should do is to take derivations for SSH config files and secret keys, and while building use the secret keys with right permissions set on them and the config files for `ssh`.

### Steps to reproduce

```
nix build -I ssh-config-file=... -I ssh-auth-sock=$SSH_AUTH_SOCK
```
with a `default.nix`
```nix
with import <nixpkgs> { };
fetchgitPrivate {
  url = "git@github.com ...";
  rev = "master";
  sha256 = "<some-sha256>";
}
```
will complain that the config file is not found in the build environment.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

`nix 2.0.4`

**Comment by leo60228** [comment]
Isn't the point to be impure? Trying to purely produce secrets isn't really possible.

**Comment by taktoa** [comment]
It's a fixed-output derivation, so it shouldn't matter if it is impure. Can we close this?
