### ISSUE TITLE
fwupd: fwupdx64.efi is improperly wrapped

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#45715]
## Issue description

`libexec/fwupd/efi/fwupdx64.efi` appears to be a shell-script wrapper, which is then copied to the ESP and cannot be booted for firmware updates.

```
[/nix/store/4nhrasbzgnixzbwffpslqz7n9l04j5ps-fwupd-1.1.1/libexec/fwupd/efi]$ l
total 76K
dr-xr-xr-x 1 root root   66 Dec 31  1969 .
dr-xr-xr-x 1 root root  148 Dec 31  1969 ..
-r-xr-xr-x 1 root root 7.2K Dec 31  1969 fwupdx64.efi
-r-xr-xr-x 1 root root  65K Dec 31  1969 .fwupdx64.efi-wrapped
```

This should definitely not be wrapped as it's not an ELF executable and is entirely static.

cc @jtojnar

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.1, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre149415.8395f9aa85e"`
 - channels(tad): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
That is quite bad. We will need to fix `wrapGAppsHook`.
