### ISSUE TITLE
datadog version 6: datadog API keys are not being used/are empty.

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#45739]
## Issue description

@tazjin, @rvl  I am using
```
      services.datadog-agent.apiKeyFile = "/run/keys/datadog_api_key"; 
```
  per https://nixos.org/nixops/manual/#idm140737318276736
(with 29929 being the pid of datadog):

`cat /proc/29929/environ`:
```
LANG=en_US.UTF-8INVOCATION_ID=59410c140d3f423b9626325cfc607f8bDD_API_KEY=USER=datadogTZDIR
```

One of the issues is that without a key set anywhere (there are two places to set a key, IIRC) it shouldn't even *start*. 

Another is that I don't know how to get a key in, since none of the documented methods work for me. 

and that clearly doesn't work or there is something which unsets the environment variable immediately after it has been loaded, but in that case I have no way to check whether an API key was actually set correctly, which is also an issue.

## Technical details

This applies to master.

**Comment by coretemp** [comment]
I think the core of the issue is that there is no support for NixOps `deployment.keys`. As a result there is a race condition in making the keys available. What is supposed to happen is that systemd waits for the key file to be present and then it would try to start the datadog-agent. In the current module, not such dependency is defined so that would have to be done by the user. 
 
```
 {
      datadog-agent = makeService {
        description = "Datadog agent monitor";
        preStart = ''
          chown -R datadog: /etc/datadog-agent
          rm -f /etc/datadog-agent/auth_token
        '';
        script = ''
          export DD_API_KEY=$(head -n 1 ${cfg.apiKeyFile})
          exec ${datadogPkg}/bin/agent start -c /etc/datadog-agent/datadog.yaml
        '';
        serviceConfig.PermissionsStartOnly = true;
      };
```

**Comment by rvl** [comment]
Yes that's a gotcha with NixOps `deployments.keys` in general.

I usually handle it like this:

```
  deployment.keys."myservice-password" = {
    text = builtins.readFile ../secrets/myservice-password;
    user = "myserviceuser";
    group = "myservicegroup";
    destDir = "/var/lib/keys"; # this will stay after rebooting
  };
  users.users.myserviceuser.extraGroups = ["keys"];
  systemd.services.myservice = {
    after = ["myservice-password-key.service"];
    wants = ["myservice-password-key.service"];
  };
```

**Comment by coretemp** [comment]
Yes, I just discovered that too :)

IMHO, the datadog service should have an option named `use_nixops_deployment_keys` and then do the right thing.

**Comment by rvl** [comment]
The same issue affects all NixOS services which depend on keys being present at start time. There is probably already a ticket open for this feature request.
