### ISSUE TITLE
crashplan is broken

### ISSUE THREAD

**Issue by xvapx** [NixOS/nixpkgs#45735]
## Issue description
Crashplan for home users has been shut down as of October 23, 2018.
Crashplan for small business current installer has been removed from download list, and needs to be updated.

### Steps to reproduce
Enable `services.crashplan` or `services.crashplansb`.

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.65, NixOS, 18.03.133126.4df3426f5a5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `""`
 - nixpkgs: `/nix/store/s7wklxxa5xw0sp1rmmgrck9vag7811ph-nixexprs.tar.xz`

**Comment by Mic92** [comment]
So `nixos/modules/services/backup/crashplan.nix` and `pkgs/applications/backup/crashplan/default.nix` can be removed?

**Comment by Mic92** [comment]
sounds like a plan.

**Comment by Mic92** [comment]
Can you have a look at the download:

```
trying https://web-eam-msp.crashplanpro.com/client/installers/CrashPlanSmb_6.7.0_1512021600670_4503_Linux.tgz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (22) The requested URL returned error: 404 Not Found
  error: cannot download CrashPlanSmb_6.7.0_1512021600670_4503_Linux.tgz from any mirror
cannot build derivation '/nix/store/lnsaiyhw828k9raifspcasrrncv6wpa0-CrashPlanSmb_6.7.0_1512021600670_4503.drv': 1 dependencies couldn't be built
```

It probably just needs an upgrade.

**Comment by xvapx** [comment]
Yep, they silently replace the installer with new versions. I'll fix and PR.

**Comment by Mic92** [comment]
Ok. I marked it as broken for the moment: https://github.com/NixOS/nixpkgs/pull/51618
