### ISSUE TITLE
open-vm-tools doesn't enable display autoscaling on Wayland

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#45751]
## Issue description

When you set `services.vmwareGuest.enable = true` on NixOS and then start a wayland display manager (in my case - sway) display autoscaling should be enabled (i.e. when you resize the VM window on VMWare it should stretch the display resolution out.)

That doesn't happen and when you try to run the `vmware-user-suid-wrapper` or `vmware-user` and instead you get the following error:

```
Xlib:  extension "VMWARE_CTRL" missing on display ":0".
```

### Steps to reproduce

1.) Enable `services.vmwareGuest.enable = true;`
2.) Rebuild `nixos-rebuild switch`
3.) Start sway (or alternative Wayland-Based DM)
4.) Start `vmware-user-suid-wrapper`
5.) See the error above.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.15, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
```

**Comment by Mic92** [comment]
Is this implemented for wayland even? `xlib` is x11 specific.

**Comment by Mic92** [comment]
Too me this sounds more like an upstream issue.

**Comment by cawilliamson** [comment]
You should @Mic92 Ok so yes they do "kinda" have Wayland support (they announce it as Wayland support but really it's Xwayland support.) I believe what's happening here is:

- vmware.service needs access to udev in order to load the resolutionSet.so and resolutionKMS.so plugins respectively.
- It currently does not have this in the "environment" part of the service file so I guess I need to figure out how to add that!

I think simply adding dbus to the above will enable the plugin to load and the issue to be resolved. I think that plugin is not needed for Xorg but *is* needed for Wayland support.

**Comment by aanderse** [comment]
@cawilliamson did the LD_LIBRARY_PATH suggestion help?

**Comment by laerlingSAP** [comment]
I'm experiencing the same issue with NixOS vmware guest running Gnome 3 under Wayland. I can reproduce what @cawilliamson described.

- In comparison: My Ubuntu vmware guest runs Gnome under Wayland and doesn't have any problem scaling the screen (as long as `libgtkmm3` is installed, which was a problem earlier. But I can see that it is in the closure of the nix `open-vm-tools` package).
- I can confirm that it is an issue with Wayland: When I start Gnome with X.org the display resizes correctly. (But then the mouse stops working for some reason)

@peterhoeg I was told on the IRC to ping you since you have worked on this NixOS module.

**Comment by laerlingSAP** [comment]
I switched channels to 20.09-beta and noticed something curious:
The screen scaling bug still occurs, but *only* when I have `displayManager.gdm.enable = true;`!

@hedning, @jtojnar, @worldofpeace, @dasj19, this seems to be an issue with gdm.

**Comment by kjeremy** [comment]
I can reproduce this on 20.09 but unfortunately if I disable wayland the mouse stops working for non-root users and gdm.

**Comment by kjeremy** [comment]
This gets around the display issue and somewhat fixes the mouse though it will won't move out of the guest window and is a little choppy.

```nix
# Fixup screen scaling in wayland for open-vm-tools
  nixpkgs.overlays = [
      (self: super: with super; {
        open-vm-tools = open-vm-tools.overrideAttrs (old: {
          postFixup = old.postFixup or "" + ''
            l=$out/lib/open-vm-tools/plugins/vmsvc/libresolutionKMS.so
            old_rpath="$(patchelf --print-rpath $l)"
            patchelf --set-rpath "$old_rpath:${systemd}/lib:${libdrm}/lib" $l
            l=$out/lib/open-vm-tools/plugins/vmusr/libresolutionSet.so
            old_rpath="$(patchelf --print-rpath $l)"
            patchelf --set-rpath "$old_rpath:${systemd}/lib:${libdrm}/lib" $l
            l=$out/lib/open-vm-tools/plugins/common/libvix.so
            old_rpath="$(patchelf --print-rpath $l)"
            patchelf --set-rpath "$old_rpath:${linux-pam}/lib" $l
          '';
        });
      })
    ];

    environment.etc."vmware-tools/tools.conf" = {
      mode = "0444";
      text = ''
        [resolutionKMS]
        enable=true
    ''; };

```

**Comment by Mic92** [comment]
Might be useful to have this fix in the actual nixpkgs than.

**Comment by SuperSandro2000** [comment]
To fix this issue also https://github.com/NixOS/nixpkgs/pull/138754 is required. If you are still on 21.05 please upgrade to 21.11 or pick the commit.

**Comment by hgl** [comment]
Doesn't seem to work for me (image stretched instead of resolution being updated). I have 3D acceleration enabled and use greetd, not sure if they matter.

My configuration.nix:

```nix
{ config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  virtualisation.vmware.guest.enable = true;
  networking.useDHCP = false;
  networking.interfaces.ens33.useDHCP = true;

  programs.sway.enable = true;
  services.greetd = let
    swayRunner = pkgs.writeShellScript "sway" ''
      export XDG_SESSION_TYPE=wayland
      export XDG_SESSION_DESKTOP=sway
      export XDG_CURRENT_DESKTOP=sway
      export WLR_NO_HARDWARE_CURSORS=1
      ${pkgs.sway}/bin/sway
    '';
  in {
    enable = true;
    settings = rec {
      initial_session = {
        command = swayRunner;
        user = "name";
      };
      default_session = initial_session;
    };
  };

  users.mutableUsers = false;
  users.users.name = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    hashedPassword = "<password>";
  };

  system.stateVersion = "22.11";
}
```

nix-channel --list
```
nixos https://nixos.org/channels/nixos-unstable
```
