### ISSUE TITLE
Request: Package for Lutris

### ISSUE THREAD

**Issue by Wolfereign** [NixOS/nixpkgs#45756]
Not sure if this is the right place but would it be possible to get a package for Lutris?

[https://github.com/lutris/lutris](https://github.com/lutris/lutris)
[https://lutris.net/](https://lutris.net/)

![image](https://user-images.githubusercontent.com/5723368/44800919-e3ba6600-ab74-11e8-959e-238be2f69b03.png)

**Comment by bkchr** [comment]
There is already an open pr for that: https://github.com/NixOS/nixpkgs/pull/42075

**Comment by Wolfereign** [comment]
Cool!  I searched the Issues but failed to look at pull requests.
