### ISSUE TITLE
linux_testing_bcachefs broken on commits earlier than 8/21

### ISSUE THREAD

**Issue by mfossen** [NixOS/nixpkgs#45769]
## Issue description

Older bcachefs kernels were writing invalid dirents which were broken on newer kernels up until recently when the following commit fixed the issue:

https://evilpiepirate.org/git/bcachefs.git/commit/?id=446219cb11af8b6a4c6b837e336bac45f43854c9

### Steps to reproduce

Create a bcachefs filesystem on the older Nixos version from the following link: https://github.com/NixOS/nixpkgs/commit/d043a30d62ad60bc7a1eb3d0f750a5b9c2d98936

Upgrade to more recent one, attempt to mount and use the filesystem. Get tons of errors and broken fsck attempts.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.03.133174.edd63e05d1e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03"`
 - channels(mitch): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Mic92** [comment]
Can you make a pull request?

**Comment by xeji** [comment]
cc @Chiiruno

**Comment by Chiiruno** [comment]
Well, that explains why my bcachefs partition was borked.
Thanks for pointing out that commit, I'll get this rolling here soon.
