### ISSUE TITLE
buildbot broken by pylint upgrade

### ISSUE THREAD

**Issue by ian-ross** [NixOS/nixpkgs#45782]
## Issue description

Following [this commit](https://github.com/NixOS/nixpkgs/commit/7f698253346ab5d24e2461ca86aad06a264ff70a) to upgrade `pylint`, `buildbot` no longer builds -- it uses Python 2.7, depends on `pylint`, and the latest `pylint` has `disabled = pythonOlder "3.4"`.

### Steps to reproduce

Try to install the `buildbot` package.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.5-arch1-1-ARCH, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(iross): `"nixpkgs-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/home/iross/.nix-defexpr/channels/nixpkgs`

**Comment by dotlambda** [comment]
It seems like it's time to move buildbot to python3: https://github.com/NixOS/nixpkgs/pull/45789.

**Comment by ian-ross** [comment]
Wow.  That was an awesomely quick response.  Thanks, @dotlambda!

**Comment by lopsided98** [comment]
Pylint 1.8/1.9 is still (maintained)[https://github.com/PyCQA/pylint/issues/1763#issuecomment-387697807] until 2020, so that is an alternative to maintain Python 2 support.

**Comment by vcunat** [comment]
Regardless, I wouldn't delay migration to python3 by default without a good reason.  (Even if the official un-supporting is a bit over a year away.)

**Comment by lopsided98** [comment]
Moving exclusively to Python 3 has the potential to break configurations, because they are written in Python. This might be fine, but we should be aware of it. See #45789 for more of this discussion.

**Comment by dotlambda** [comment]
I think we should provide indeed provide pylint 1.9 as `python2Packages.pylint` until support ends. I also think we should move buildbot to `pythonPackages` as @FRidh suggested.
@lopsided98 Do you want to continue my work?

**Comment by FRidh** [comment]
Please discuss ideas/plans and such on the issue (#45789), not the PR.

**Comment by lopsided98** [comment]
#45890 was merged a while ago, so this issue is resolved
