### ISSUE TITLE
emacs magit-todos: git not found

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#45868]
## Issue description
magit-todos needs the git command

### Steps to reproduce
```
nix-shell -p emacsPackagesNg.melpaPackages.magit-todo
```
results in:
> Searching for program: No such file or directory, git                                                                                                                                            
and the installation fails

## Technical details

 - system: `"x86_64-linux"`                                                                                                                                                                      
 - host os: `Linux 4.14.63, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`                                                                                                                       
 - multi-user?: `yes`                                                                                                                                                                            
 - sandbox: `yes`                                                                                                                                                                                
 - version: `nix-env (Nix) 2.0.4`                                                                                                                                                                
 - channels(IITaudio): `"master, nixos"`                                                                                                                                                         
 - channels(gitlab-runner): `"nixpkgs-18.03pre117013.aebdc892d6"`                                                                                                                                
 - channels(root): `"nixos-18.09pre149415.8395f9aa85e"`                                                                                                                                          
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by periklis** [comment]
This is a common pitfall with emacs packages missing build inputs others than emacs packages. Latter are identified by emacs2nix, but external dependencies. Please try out the following approach [like magit](https://github.com/NixOS/nixpkgs/blob/23340918d97df787735b62b50090db72a69c8dc4/pkgs/applications/editors/emacs-modes/melpa-stable-packages.nix#L151). A PR is always welcome ;)
