### ISSUE TITLE
byobu: wrong python path (python3)

### ISSUE THREAD

**Issue by vmandela** [NixOS/nixpkgs#45895]
## Issue description

Trying to reconnect to `byobu` returns an error:

~~~
/run/current-system/sw/bin/byobu-select-session: /nix/store/gibcpdj55srzw5rjq9f7k6vf99cdpwh2-byobu-5.127/lib/byobu/include/select-session.py: 
/usr/bin/python3: bad interpreter: No such file or directory
~~~

Attaching via `tmux attach-session` works.

This issue seems to be a variant of #9865 . Two files below have references to python3 outside of nix store.

~~~
lib/byobu/include/select-session.py
[3] 1: #!/usr/bin/python3

lib/byobu/include/config.py
[5] 1: #!/usr/bin/python3
~~~

### Steps to reproduce

1. Launch byobu, open some sessions, disconnect with F6.
2. Try to reconnect by launching byobu again.

## Technical details
~~~
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.09.git.526887b (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
~~~

**Comment by vhp1360** [comment]
hello
kindly, is there any solution
