### ISSUE TITLE
nixos-rebuild fails to reload user service files due to bug in switch-to-configuration.pl

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#45897]
## Issue description

Upon `nixos-rebuild switch --upgrade` I encountered an error and tracked it to the following:

In line 422 of `switch-to-configuration.pl` the line
`
system("su", "-l", $name, "-c", "XDG_RUNTIME_DIR=/run/user/$uid @systemd@/bin/systemctl --user daemon-reload");
`
tries to execute
`
XDG_RUNTIME_DIR=/run/user/1000 /nix/store/dzn7zyf1dhxlvrbpgnyn7di58zvfblrq-systemd-239/bin/systemctl --user daemon-reload
`
which apparently fails with:
`
fish: Unsupported use of '='. To run '/nix/store/dzn7zyf1dhxlvrbpgn
yn7di58zvfblrq-systemd-239/bin/systemctl' with a modified environment, please use 'env XDG_RUNTIME_DIR=/run/user/1000 /nix/store/dzn7zyf1dhxlvrbpgnyn7di58zvfblrq-systemd-239/bin/systemctl…'
`

The problem here is, that su will invoke the users default shell, which is fish in this case, while the shell command clearly was meant to be executed by a posix compliant shell.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.1, NixOS, 18.09pre150708.083220867c7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(pantarhei): `"nixos-18.09pre139749.17b2ef2461c"`
 - channels(root): `"nixos-18.09pre150708.083220867c7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Ma27** [comment]
Hi! I'm sorry that my change broke your setup! Would you mind checking if #45945 fixes your problem? :)

**Comment by xaverdh** [comment]
While #45945 does fix my problem, I also think its probably better to tell su to explicitly use bash. Fish is not the only potential login shell around, and the set of possible login shells may change in the future (adding shells with totally different syntax).
