### ISSUE TITLE
Steam play doesn't work

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#45927]
## Issue description
Not entirely sure why, and I don't have much information about it.
My best guess is there's some missing dependency in the steam runtime nix puts together.

### Steps to reproduce
Install Steam
Attempt to play a steam play game.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.5, NixOS, 18.09pre150708.083220867c7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos, nixpkgs"`
 - channels(okina): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Chiiruno** [comment]
@dywedir Yes, I believe so.
Although, I thought it was the opposite, and python2 was what needed to be added.

**Comment by jb55** [comment]
hmm just tested the witness, seemed to work fine (I have #45855 applied to be sure)

**Comment by jb55** [comment]
I also have #45030 applied because I believe they're required?

**Comment by cpages** [comment]
Dupe: #45492 though the info in both issues is different

**Comment by Nadrieril** [comment]
Those patches have now been merged, and steam play appears to work decently out-of-the-box for me. I think this issue can be closed.
