### ISSUE TITLE
Tiny Mouse Cursor in with HiDPI screen in clion/intellij/... 

### ISSUE THREAD

**Issue by kolloch** [NixOS/nixpkgs#45942]
## Issue description

When using the current unstable package for clion (same happend with intellij), the mouse cursor becomes tiny when hovering over the clion window. 

This seems to be a packaging issue because it does not occur when I download the clion archive directly from jetbrains, unpack & run it.

See the videos in the following file, screenshots hide the cursor unfortunately:

[clion.zip](https://github.com/NixOS/nixpkgs/files/2343185/clion.zip)

This was also reported to jetbrains, see [IDEA-186602](https://youtrack.jetbrains.com/issue/IDEA-186602).

### Steps to reproduce

* In Gnome, Start clion/intellij on a HiDPI screen with "200%" scaling enabled: 
    ![display-settings](https://user-images.githubusercontent.com/339354/44954888-213b2e00-aeaa-11e8-9216-72ab842b534d.png)

* Move cursor into the opened window

=> The cursor changes to a tiny size. Basically, it looks as if the scaling was not effective inside of that window. 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.19, NixOS, 18.03.133185.a960b87ac21 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133185.a960b87ac21, nixos-18.03-18.03, nixos-unstable-18.09pre150708.083220867c7"`
 - channels(peter): `"nixos-18.03.133185.a960b87ac21, nixos-unstable-18.09pre150708.083220867c7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ivan** [comment]
This is effectively a duplicate of #50344 (filed later) - the user cursor theme is responsible for making the cursor big enough.

**Comment by rnhmjoj** [comment]
Closing as #50344 has been fixed and the default cursor is also now scaled automatically if `services.xserver.dpi` and `hardware.video.hidpi.enable` are set.

**Comment by n0099** [comment]
For me, add [`-Dawt.toolkit.name=WLToolkit`](https://youtrack.jetbrains.com/issue/IJPL-178704/Linux-cursor-smaller-than-system-wide#focus=Comments-27-12158600.0-0) that introduced in [`2024.2`](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/) to JVM options will resize the cursor size according env var `$XCURSOR_SIZE`, but UI layout will be shifted.

**Comment by provokateurin** [comment]
Unfortunately it didn't help.
