### ISSUE TITLE
antibody-3.6.1 binary is broken

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nixpkgs#45965]
## Issue description
I use the antibody plugin manager for zsh because it is MUCH faster than other alternatives like oh-my-zsh and antigen. Unfortunately, the binary package available seems to be broken. I am still very new to Nix so I don't know how to debug or even build ( I tried ) the package to see if I can fix it.

### Steps to reproduce

Simply install the latest version from the nixos-unstable channel. It appears to work but its core functionality is broken. Namely, in order to use it you must call 'antibody bundle $some_zsh_plugin' and it normally downloads the plugin from github and then spits out a zsh script to stdout which can be redirected to a file or called in the zshrc directly. This script is essential to the operation of antibody as it cannot load the plugins without it. However the binary in the Nix package, although it downloads the plugins to the users cache dir as expected, no script is sent to stdout and therefore is completely unusable. I have build the 3.6.1 branch from github source and it does not have this issue, so it appears to be a problem with the nix package somehow.

I have tested the package both on arch linux with nix installed from the aur as well as a nixos virtual machine and it behaves the same in both environments.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.5-arch1-1-ARCH, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixpkgs-18.09pre149804.c268986263f"`
 - channels(eco): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by worldofpeace** [comment]
Just going to say for the record as its maintainer in nixpkgs, I've been using it since its inclusion in nixpkgs and I haven't had a problem.

**Comment by nrdxp** [comment]
yeah I was having a very strange environmental issue that randomly fixed itself. Sorry about this.

**Comment by worldofpeace** [comment]
Oh that's fine, happens to even the best of us :+1:
