### ISSUE TITLE
18.09 Zero Hydra Failures (aarch64)

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#45962]
![image](https://user-images.githubusercontent.com/132835/44961199-0f25b380-aedb-11e8-98ec-8e09d46a5573.png)

See the [generic issue](https://github.com/NixOS/nixpkgs/issues/45960). This is to discuss aarch64-specific issues for ZHF.

**Comment by andrew-d** [comment]
I _think_ that the Boost 1.55 issue here is that it's not getting properly detected as an ARM system; if you look at [the log](https://nix-cache.s3.amazonaws.com/log/xq8j8bcrkzihcs1m97yv6hwy3xha3dv9-boost-1.55.0.drv), you can see `arm                      : no`, whereas [on 1.59](https://nix-cache.s3.amazonaws.com/log/jn2a8w8c1dvim3f0bb9mdgjq735qlf4p-boost-1.59.0.drv), it correctly determines `arm                      : yes`.

Not 100% sure how to fix this yet, though.

**Comment by xeji** [comment]
I merged and backported #47564. Could someone with access rights please restart the bunch of timed-out aarch64 jobs on Hydra? Most of them seem kernel-related. @samueldr @vcunat
