### ISSUE TITLE
redshift doesn't work with geoclue location provider

### ISSUE THREAD

**Issue by furrycatherder** [NixOS/nixpkgs#45994]
## Issue description

`redshift` fails like this:
```
Sep 01 02:15:22 akita systemd[1046]: Started Redshift colour temperature adjuster.
Sep 01 02:15:22 akita redshift[9947]: Waiting for initial location to become available...
Sep 01 02:15:22 akita redshift[9947]: Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Agent r>
Sep 01 02:15:22 akita redshift[9947]: Access to the current location was denied by GeoClue!
Sep 01 02:15:22 akita redshift[9947]: Make sure that location services are enabled and that Redshift is permitted
Sep 01 02:15:22 akita redshift[9947]: to use location services. See https://github.com/jonls/redshift#faq for more
Sep 01 02:15:22 akita redshift[9947]: information.
Sep 01 02:15:22 akita redshift[9947]: Unable to get location from provider.
Sep 01 02:15:22 akita systemd[1046]: redshift.service: Main process exited, code=exited, status=1/FAILURE
```

### Steps to reproduce

```
redshift = {
  enable = true;
  provider = "geoclue2";
};
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.09pre150708.083220867c7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(sean): `""`
 - channels(root): `"nixos-18.09pre150708.083220867c7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by michaelpj** [comment]
This should be fixed on recent unstable.

**Comment by ma9e** [comment]
It's still not working for me.

**Comment by michaelpj** [comment]
What DE are you using? Do you get a notification asking you to allow redshift access to the location?

**Comment by ma9e** [comment]
I'm using awesome without a desktop environment. I would try to install one, but that seems to be broken as well:
```
~> nixos-option services.xserver.desktopManager
This attribute set contains:
error:
syntax
error,
unexpected
:,
expecting
```
```
error: The option `services.xserver.desktopManager.gnome' defined in `/etc/nixos/configuration.nix' does not exist.
```

Could this be done DE-agnostically by adding lines to `geoclue.conf`?

**Comment by michaelpj** [comment]
No. The breakage is due to geoclue now *requiring* an agent to be running. I have an issue open to allow the whitelist to work even if there is no agent running. Go comment on https://gitlab.freedesktop.org/geoclue/geoclue/issues/76 if you'd like this to work.

**Comment by worldofpeace** [comment]
@ma9e 
> error: The option `services.xserver.desktopManager.gnome' defined in `/etc/nixos/configuration.nix' does not exist.

That's because the option is called `services.xserver.desktopManager.gnome3.enable`
Also are you sure you did `services.geoclue2.enable = true;`?

@michaelpj Where is redshift being whitelisted?

**Comment by michaelpj** [comment]
You don't need to turn on the geoclue service, the redshift module does that.

Redshift isn't whitelisted because there's no point, because it doesn't work. If the issue I linked to is fixed, then we could do that.

**Comment by michaelpj** [comment]
@asymmetric there is no upstream release with the relevant commit yet. And yes, we would need to update the config file, ideally with something like https://github.com/NixOS/nixpkgs/pull/45306. Then we can get rid of most of https://github.com/NixOS/nixpkgs/pull/44820.

@rvolosatovs what DE are you using? You should get a notification asking you to give permission for redshift to access the location. Hopefully we'll be able to ditch this once upstream make an new release.

**Comment by rvolosatovs** [comment]
@michaelpj I'm not using a DE. I'm running `bspwm` via https://github.com/rycee/home-manager.
The implementation uses `~/.xsession` to run the WM.
Here's the `~/.xsession` generated by `home-manager`: https://github.com/rycee/home-manager/blob/0cfd21cc153775126e2deaa3d8689471fa5549bf/modules/xsession.nix#L133-L151
Here are the contents of `xsession.windowManager.command` in my case: https://github.com/rvolosatovs/infrastructure/blob/08558fd5e87b966a85aa6a4f8edc81e069d1eea1/home/graphical.nix#L234-L250
I also have this in my `nixos` config: https://github.com/rvolosatovs/infrastructure/blob/08558fd5e87b966a85aa6a4f8edc81e069d1eea1/nixos/graphical.nix#L57-L67

**Comment by michaelpj** [comment]
Well, my understanding of the geoclue dev's position was that it should only work in a desktop environment that can prompt the user for permission to access the location. I think that's crazy, but that's where we are right now. Hopefully once they release a version with that patch then we can do something more sensible.

**Comment by asymmetric** [comment]
From the dev's [blog](http://zee-nix.blogspot.com/2018/09/recently-in-geoclue.html):

> Drop all authorization from Geoclue and leave that to the geolocation portal. I've already dropped authorization for non-flatpak (i-e system) apps in git master. Once the portal is in place and GNOME shell and control-center have been modified to talk to it, we can drop all app authorizing code from Geoclue.

If I read this correctly, we'll still have to whitelist redshift and add `system=true`, to make sure it works for non-flatpak users.

**Comment by michaelpj** [comment]
Yes, see the PR I linked.

**Comment by asymmetric** [comment]
https://gitlab.freedesktop.org/geoclue/geoclue/issues/89#note_49869.

geoclue is not built with `mason`: any idea how to use `mason` in `nixpkgs`? I was looking for some supporting functions but couldn't find any.

**Comment by michaelpj** [comment]
Lots of the gnome packages are built with meson.

**Comment by asymmetric** [comment]
meson.build:1:0: ERROR:  Meson version is 0.46.1 but project requires >= 0.47.2.

but the upgrade is [blocked](https://github.com/NixOS/nixpkgs/pull/46020).

**Comment by michaelpj** [comment]
See https://github.com/NixOS/nixpkgs/pull/48438.

**Comment by asymmetric** [comment]
I've been away from this issue long enough to forget where the problem actually lies :)

@michaelpj, do you know what the status of this is?

**Comment by ma9e** [comment]
@asymmetric afaict, we want to add
```ini
[redshift]
allowed=true
system=false
users=
```
to `/etc/geoclue/geoclue.conf`. But I'm not seeing it in `/etc`, although it certainly exists:
```console
nix-repl> config.environment.etc."geoclue/geoclue.conf"
{ _module = { ... }; enable = true; gid = 0; group = "+0"; mode = "symlink"; source = "/nix/store/kw1nmi6vkbn3q41ngdsxh1dwsnqp1d8a-geoclue-2.5.1/etc/geoclue/geoclue.conf"; target = "geoclue/geoclue.conf"; text = null; uid = 0; user = "+0"; }
```

Aside from that, `config.environment.etc."geoclue/geoclue.conf"` is defined with the source attribute:
```
 64
 65     environment.etc."geoclue/geoclue.conf".source = "${package}/etc/geoclue/geoclue.conf";
 66   };
```

**Comment by ma9e** [comment]
I was really tired last night, lol... 18.09 doesn't have geoclue.conf and I was repl-ing from unstable.

So yeah, we just need to merge that configuration snippet into geoclue.conf somehow.

**Comment by worldofpeace** [comment]
The aforementioned change has been completed (https://github.com/NixOS/nixpkgs/pull/60681).

Pretty sure if you use the example in this commit https://github.com/NixOS/nixpkgs/commit/2d93f57db58f2631017714c4e28bf72c2c52c036 this can work as expected.
