### ISSUE TITLE
nix run fails from the console and ssh when using eg. ZSH

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#46091]
## Issue description

Thought I'd actually make an issue about this.

`nix run` starts a new interactive Bash shell, which will source `/etc/profile` if it's not already done. This is already done if the parent shell is Bash or when using a regular graphical session (we source `/etc/profile` there). If the parent shell isn't Bash however `/etc/profile` will be sourced and PATH will be reset, resulting in a useless `nix run` shell.

Fixed by #45784.

### Steps to reproduce

1. Use another default shell than bash, eg. ZSH
2. log in through the console, or ssh
3. run `nix run some.package`
4. observe that the path isn't modified

**Comment by xeji** [comment]
fixed in #45784
