### ISSUE TITLE
ms-python.python vscode extension stuck on "Installing" forever

### ISSUE THREAD

**Issue by oscarvarto** [NixOS/nixpkgs#46129]
## Issue description
After installing ms-python.python vscode extension, vscode seems to never finish to "Install" it.

![ms-python python](https://user-images.githubusercontent.com/1676245/45128189-46e26480-b142-11e8-8835-8f27a6bb4910.png)

**Could it be because `ms-python.python` extensions has some dependencies that should be explicitly installed?**

### Steps to reproduce

The following `home-manager` configuration <sup id="note1">[1](#f1)</sup> installs ms-vscode.cpptools, and  other extensions like `justusadam.language-haskell` without problems:

```nix
{
  nixpkgs.config.allowUnfree = true;

  home.packages = with pkgs; [
    vscode-with-extensions
    python2Full
    python3Full
  ];

  nixpkgs.overlays = [ (self: super: {
    vscode-with-extensions = super.vscode-with-extensions.override {
      # When the extension is already available in the default extensions set.
      vscodeExtensions = with super.vscode-extensions; [
        bbenoist.Nix
        ms-vscode.cpptools
        ms-python.python
      ]
      # Concise version from the vscode market place when not available in the default set.
      ++ super.vscode-utils.extensionsFromVscodeMarketplace [
        {
          name = "code-runner";
          publisher = "formulahendry";
          version = "0.6.33";
          sha256 = "166ia73vrcl5c9hm4q1a73qdn56m0jc7flfsk5p5q41na9f10lb0";
        }

        {
          name = "language-haskell";
          publisher = "justusadam";
          version = "2.5.0";
          sha256 = "10jqj8qw5x6da9l8zhjbra3xcbrwb4cpwc3ygsy29mam5pd8g6b3";
        }
      ];
    };
  } ) ];
}
```

## Technical details

Results of running `nix-shell -p nix-info --run "nix-info -m"`: http://ix.io/1m4j
or

```yaml
- system: `"x86_64-linux"`
- host os: `Linux 4.14.67, NixOS, 18.09pre150708.083220867c7 (Jellyfish)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.0.4`
- channels(root): `"nixos-18.09pre150708.083220867c7"`
- channels(oscarvarto): `""`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

<b id="f1">1</b> Eliding non-related details; see full `~/.config/nixpkgs/home.nix` contents here: http://ix.io/1m4i [↩](#note1)

**Comment by ua74e3dqka** [comment]
Problem still exists as the extension tries to extract `Python-Language-Server-linux-x64.*.nupkg` into `/nix/store/*-vscode-*extensions/share/vscode/extensions/ms-python.python/language` path, which is of course not possible. Guess there is something off with the extension itself

**Comment by veprbl** [comment]
cc @jraygauthier @eadwu

**Comment by eadwu** [comment]
Can't replicate this, and neither is `2018.7.0` the latest version for `master` and `release-19.03`.

**Comment by teto** [comment]
hard to replicate plus now it has its own package.
