### ISSUE TITLE
nginx module: missing resolve option

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#46147]
## Issue description

`server example.com resolve;`  is valid configuration syntax. The module however does not allow such options (other than `valid`). 

```
http {
    resolver 10.0.0.1;

    upstream u {
        zone ...;
        ...
        server example.com resolve;
    }
}
```

It should be possible to influence the configuration such that "resolve" can be specified.

## Technical details

Applies to `master` and `18.03`.

**Comment by coretemp** [comment]
Actually, this only applies to the commercial version. Still would be useful to also be able to configure the commercial version, but as such it's less pressing. 

Open-source Nginx seems to be crippleware given that it doesn't support such a feature.

**Comment by globin** [comment]
`services.nginx.proxyResolveWhileRunning = true;` works around this for you.

Also since we don't support the commercial version, I'm closing this. If you need support for it please open a PR :)
