### ISSUE TITLE
NetworkManager VPN plugins are broken

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#46197]
## Issue description

NetworkManager VPN plugins (such as `networkmanager-openvpn`) are no longer working in unstable.

It appears the link targets for `/etc/static/NetworkManager/VPN/nm-${plugin}-service.name` have changed from `/etc/NetworkManager/VPN/nm-${plugin}-service.name` to `/lib/NetworkManager/VPN/nm-${plugin}-service.name`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.68, NixOS, 19.03pre151837.ca2ba44cab4 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1`
 - channels(root): `"nixos-19.03pre151837.ca2ba44cab4"`
 - channels(tad): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by xeji** [comment]
fixed in #46201 , backported to 18.09 in https://github.com/NixOS/nixpkgs/commit/43c9869dc578d8d84efd34f5bb80ef33fecbe935
