### ISSUE TITLE
buildEnv: support force-creating all directories and symlinking only files

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#4621]
This would simplify, for example, https://github.com/NixOS/nixpkgs/pull/4577 expression (or maybe there is just another, better way?). Another (more grained) approach would be to add a list argument which specifies directories that should be created and not symlinked.

**Comment by abbradar** [comment]
For recent examples of workarounds see https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/dwarf-fortress/wrapper/default.nix#L23. I have quite a bit of those scattered across nixpkgs now.

**Comment by vcunat** [comment]
Dealing with https://github.com/NixOS/nix/issues/341 will require to implement `buildEnv` in C++. After that I assume nixpkgs will just directly use `buildEnv` from nix. (For now it isn't really important how exactly.)

Hopefully the issue won't be stranded for too long anymore.

**Comment by rasendubi** [comment]
I've opened a PR that creates directories for all pathsToLink (https://github.com/NixOS/nixpkgs/pull/16828). While it not exactly follows this proposal, it may fix the issue when names are known ahead of time (`pathsToLink = [ "/" "/real/directory" ]`).

**Comment by vcunat** [comment]
Note that we also have `symlinkJoin` function which is a thin wrapper around the `lndir` command.
