### ISSUE TITLE
Factorio downloads fail to login

### ISSUE THREAD

**Issue by brendan-hall** [NixOS/nixpkgs#46267]
## Issue description
I recently returned to Nixos after a break, and have been trying to update my packages. However, Factorio fails to download it's files from the game's fileserver.
I am using Nixos 18.03, with a nixos-unstable as a user channel.

Here is a typical attempt at installing Factorio (it doesn't matter which channel I build it with)
```
[OMITTED@nixos:~]$ nix-env -iA unstable.factorio
installing 'factorio-alpha-0.16.51'
these derivations will be built:
  /nix/store/b75nfira5bb2fxk54aby0wgmlrnji7fs-factorio_alpha_x64-0.16.51.tar.xz.drv
  /nix/store/kvs48bb8wa9kgj2nxra8sfwrf3q7hqhn-factorio-alpha-0.16.51.drv
building '/nix/store/b75nfira5bb2fxk54aby0wgmlrnji7fs-factorio_alpha_x64-0.16.51.tar.xz.drv'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8833  100  8833    0     0  11486      0 --:--:-- --:--:-- --:--:-- 11471
**** Processing: stdin:/// ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   353  100   192  100   161    252    211 --:--:-- --:--:-- --:--:--   464
Login failed
Please set username and password with config.nix,
or /etc/nix/nixpkgs-config.nix if on NixOS.

Example:
{
  packageOverrides = pkgs: rec {
    factorio = pkgs.factorio.override {
      username = "<username or email address>";
      password = "<password>";
    };
  };
}
builder for '/nix/store/b75nfira5bb2fxk54aby0wgmlrnji7fs-factorio_alpha_x64-0.16.51.tar.xz.drv' failed with exit code 1
cannot build derivation '/nix/store/kvs48bb8wa9kgj2nxra8sfwrf3q7hqhn-factorio-alpha-0.16.51.drv': 1 dependencies couldn't be built
error: build of '/nix/store/kvs48bb8wa9kgj2nxra8sfwrf3q7hqhn-factorio-alpha-0.16.51.drv' failed
```

The factorio attribute is overridden using the following overlay.
`~/nix-cherries/factorio` is just a copy of `unstable/pkgs/games/factorio` I made to help my investigations, the issue still exists with the stock derivation. 
```
self: super: {
    factorio = super.factorio.override {
        username = "nullvoid";
        password = "………………";
    };
}
```

Some fiddling with `fetch.sh` show that curl is giving the following output. I also able to see that the username and password ARE being passed correctly to `fetch.sh`.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```
I suspect the problem is that the login page has recaptcha on it, but I have no idea how to solve the issue either way.

### Steps to reproduce
1. Override the factorio derivation to set username and password
2. run `nix-env -iA nixos.factorio`
3. observe the failure to login (`fetch.sh` assumes all failures to login are because you haven't set your username and password)

## Technical details
```
[OMITTED@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133187.8c172c44265 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(OMITTED): `"unstable-18.09pre150708.083220867c7"`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

cc @Baughn @elitak since you're listed in maintainers for Factorio. Sorry if this is bad form!

**Comment by elitak** [comment]
I doubt fetch.sh can be modified to circumvent the new CAPTCHA. There's a token stored in `.factorio/player-data.json` that is normally used for the mod portal, that could maybe be used, but otherwise we will just have to advise the workaround, which is to download the release manually, then run something like `version=0.16.51; mode=alpha; nix-prefetch-url "file://$HOME/Downloads/factorio_${mode}_x64_${version}.tar.xz" --name factorio_${mode}_x64-${version}.tar.xz` before `nix-build -A factorio`.

I have tried petitioning the devs in the past for sha256 sums in the mod portal, but been more or less ignored. A token-authorized download is something they might be open to adding; I posted a request here:
https://forums.factorio.com/viewtopic.php?f=49&t=62410

**Comment by brendan-hall** [comment]
Just to collate information here, we now have the ability to download packages using a token based download link. Essentially, we just have to pass the username and token as URL-params now.

https://factorio.com/get-download/{version}/{build}/{distro}?username={username}&token={token}

Tokens can be obtained from the preexisting link:
https://auth.factorio.com/api-login?username={username}&password={password}&require_game_ownership={optional_bool}

More info on that on the [official wiki](https://wiki.factorio.com/Web_authentication_API) or on the [unofficial API wiki](https://artentus.github.io/FactorioApiDoc/auth-api/), (Also, the second website documents an API for downloading Mods if we weren't doing that already, though it only has SHA1's)

**Comment by brendan-hall** [comment]
I'd love to take a crack at implementing this. I'm thinking we switch to asking the end user to supply their token rather than their password, and simply point them to where they can find it (and/or provide a quick script alongside the rest of the packaging to get their current token for them)

**Comment by elitak** [comment]
They added auth via querystring to the download urls. Here's my quickly done set of changes: https://github.com/NixOS/nixpkgs/pull/46586
