### ISSUE TITLE
TOR service directory permissions

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#46271]
## Issue description
Certain services and programs require read access to the TOR base/data directory, and specifically in my case, the control authorization cookie (control_auth_cookie).

I'd like to request TOR base/data directory permissions be either automatically readable to the TOR group, including files in the top-level directory, or an extra option in the service to enable the aforementioned.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.6, NixOS, 19.03pre151837.ca2ba44cab4 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1`
 - channels(root): `"nixos-19.03pre151837.ca2ba44cab4, nixpkgs-18.09pre151052.4477cf04b67"`
 - channels(okina): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
Isn't that simply controlled by the `CookieAuthFileGroupReadable` setting? See https://www.torproject.org/docs/tor-manual.html.en?

**Comment by Chiiruno** [comment]
I didn't know about that.
To get access to (default) /var/lib/tor, we can set `CacheDirectoryGroupReadable` to 1.
Thank you so much!
