### ISSUE TITLE
Bump default LLVM to 6 (or maybe even 7?)

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#46326]
I'll probably need to regenerate a new set of bootstrap tools for darwin soon and was thinking of possibly bumping the default LLVM on Darwin to 6. 7 isn't packaged yet but I could also just hold off if we're likely to package it soon.

I'd rather not have a `llvm = if isdarwin then 6 else 5` but I could also do that.

cc @LnL7 @grahamc @vcunat @shlevy @edolstra

**Comment by dtzWill** [comment]
https://github.com/NixOS/nixpkgs/pull/39986

**Comment by copumpkin** [comment]
Oh nice!

**Comment by vcunat** [comment]
That isn't for nixpks-18.09-darwin, right?

**Comment by copumpkin** [comment]
Right, I'm working on master right now and am too ~~chicken~~responsible to try to make any of these changes to an upcoming release branch.

**Comment by FliegendeWurst** [comment]
Fixed by d4ff2313e69247afcf078536c65cd5f82751e1b8.
