### ISSUE TITLE
How would I go about packaging the unfree projects?

### ISSUE THREAD

**Issue by stites** [NixOS/nixpkgs#46322]
## Issue description

I'd like to try to package MKL but it isn't free and requires registration in order to get access to the build script. I could use my login, but it seems like a bit of a hack (and a maintaining nix-org, or myself, could get in trouble for this). MKL is one of the fastest LAPACK libraries and, if available, is used as a backend to caffe and pytorch.

How does nixpkgs usually handle this?

**Comment by 7c6f434c** [comment]
I would recommend to search for `requireFile` in Nixpkgs; for example it is used for `oraclejdk`. It is specifically for the case when you want to ask the user to download the source manually because of unclear legal status of direct links.

**Comment by stites** [comment]
Thanks @7c6f434c! I'll close this out and reopen if I run into any issues.
