### ISSUE TITLE
vulnix: broken build 1.7.1 on macos

### ISSUE THREAD

**Issue by periklis** [NixOS/nixpkgs#46360]
## Issue description
Master build seems to be broken due to missing python dependency:
```
uilder for '/nix/store/clyykklxyh65mqvjm107s3s3b8q3h520-python3.6-persistent-4.4.2.drv' failed with exit code 1; last 10 log lines:
      import manuel.capture
  ModuleNotFoundError: No module named 'manuel'
  ----------------------------------------------------------------------
  Ran 517 tests in 1.195s
  FAILED (errors=3)
  Test failed: <unittest.runner.TextTestResult run=517 errors=3 failures=0>
  error: Test failed: <unittest.runner.TextTestResult run=517 errors=3 failures=0>
cannot build derivation '/nix/store/zvpd30bz641804wmgacpi4hbbc8ymn1l-python3.6-ZODB-5.4.0.drv': 1 dependencies couldn't be built
building '/nix/store/1fsgng6q21g8x0w4srp9c7j6anpc0hhw-pythonTools.drv'...
cannot build derivation '/nix/store/f9lg48sr8x8fbhqfihbgpz8vidzam1fb-vulnix-1.7.1.drv': 1 dependencies couldn't be built
```

cc @ckauhaus 

## Technical details
```
nix-info -m 
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixpkgs-18.09pre149107.3878342ef02"`
 - nixpkgs: `/Users/USERNAME/projects/nix-config/nixpkgs
```

**Comment by xeji** [comment]
Same issue on all platforms, not just Darwin:
https://hydra.nixos.org/jobset/nixpkgs/trunk/jobs-tab?filter=vulnix

**Comment by xeji** [comment]
#46364 fixes the broken python dependency `python36Packages.persistent`, but now another python dependency fails. More work to do...

**Comment by ckauhaus** [comment]
vulnix is only indirectly broken. `python36Packages.BTrees` is broken.

See here: https://hydra.nixos.org/build/81027209

Currently BTree does not build with python36 and python27.

**Comment by ckauhaus** [comment]
@periklis: Looks like BTree has been fixed in the meantime. Please check if the bug is still relevant for you. I cannot reproduce the problem on current master or 18.09.

**Comment by xeji** [comment]
BTrees was fixed in #46588.

**Comment by periklis** [comment]
@ckauhaus & @xeji All fine on darwin again. Thanks for this remarkable piece of software. It is really an eye-opener when i can show people - hey look ma, we can have a list of all vulnerable software of a system/image/whatever in a shot.

**Comment by xeji** [comment]
Great, let's close it then.
