### ISSUE TITLE
glfw broken after move to libglvnd for opengl

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#46423]
Attempt to use libepoxy gives
```
Error: GLX: Failed to load GLX
```

See https://github.com/NixOS/nixpkgs/pull/37369#issuecomment-419715048

**Comment by andrewrk** [comment]
Repro:

```
wget https://ziglang.org/builds/zig-linux-x86_64-master.tar.xz
tar xvf zig-linux-x86_64-master.tar.xz
rm zig-linux-x86_64-master.tar.xz
cd zig-linux-x86_64-*
git clone git@github.com:andrewrk/tetris.git
cd tetris
nix-shell -p glfw -p epoxy -p libpng
../zig build play
```

**Comment by avnik** [comment]
That's not epoxy, but glfw problem.  ALthough I would like to make PR with fixing glfw, and bump epoxy version as well.

**Comment by Mic92** [comment]
Do we need this in 18.09 as well?

**Comment by andrewrk** [comment]
I just updated to `19.03pre158246.6141939d6e0 (Koi)` and the problem persists.
