### ISSUE TITLE
openbsm build is slightly impure

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#46429]
I'm in the midst of replacing old CF with new CF and am building a bunch of stuff. I was building Go, which depends indirectly on openbsm, and noticed it failing for seemingly unrelated reason to CF. I eventually compared my `./configure` run with a good one on Hydra and found a lone meaningful diff:

The successful one, at the very end of its configure run, says:

```
checking for /usr/include/mach/audit_triggers.defs... no
```

whereas my broken build said:

```
checking for /usr/include/mach/audit_triggers.defs... yes
```

The build then proceeded to do this and die:

```
Making all in audit
make[2]: Entering directory '/private/tmp/nix-build-openbsm-1.1.drv-1/source/bin/audit'
user auditd_controlUser.c -header auditd_control.h -server /dev/null -sheader /dev/null ../../bin/auditd/auditd_control.defs
/nix/store/vbci0jg8xaa6rphg412vmf3xmzw42114-bash-4.4-p23/bin/bash: user: command not found
make[2]: [Makefile:527: auditd_controlUser.c] Error 127 (ignored)
clang -DHAVE_CONFIG_H -I. -I../../config -I../.. -I../.. -I../../sys    -g -O2 -c auditd_controlUser.c
clang-5.0: error: no such file or directory: 'auditd_controlUser.c'
clang-5.0: error: no input files
make[2]: *** [Makefile:275: auditd_controlUser.o] Error 1
```

If you look at the source, it seems to be expecting mig. I'll probably fix it later but just wanted to record it so I don't forget.

cc @matthewbauer @LnL7

**Comment by copumpkin** [comment]
Ah, feeding the `openbsm` build `bootstrap_cmds` as `buildInput` "fixes" it (so I can continue testing), but it should still be grabbing the .defs file from Libsystem rather than an impure path.

**Comment by matthewbauer** [comment]
Yeah that is something we can probably create a PR for at https://github.com/openbsm/openbsm.

IIRC openbsm is just needed for one of the system_cmds like login or something. We can probably disable it just to get things working.

**Comment by matthewbauer** [comment]
@dhess what commit are you getting this on?

**Comment by dhess** [comment]
@matthewbauer It's f2a1a4e93be2d76720a6b96532b5b003cc769312 I believe. However, it appears to have been a transient failure, as I restarted the build and it completed the 2nd time.

**Comment by risicle** [comment]
For me it fails every time, macos 10.13, currently on 93580a122

**Comment by dhess** [comment]
@matthewbauer Nice catch!
