### ISSUE TITLE
RetroShare appimage fails with appimage-run: libtasn1.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by kliu128** [NixOS/nixpkgs#46447]
## Issue description

When running the latest RetroShare appimage (which I have to do, as the packaged retroshare in Nixpkgs no longer compiles), it errors with:

```
/home/kevin/.cache/appimage-run/83cfb5eb2a6f9083f1cd2510968e2e592c34de610075993526ea6730914246d9/squashfs-root/usr/bin/retroshare: error while loading shared libraries: libtasn1.so.6: cannot open shared object file: No such file or directory
```

Perhaps it's a case of a missing dependency in the appimage FHS env.

### Steps to reproduce

1. Run `appimage-run ./RetroShare-0.6.4.20180313.0e6d27ad-x86_64.AppImage`.
2. See error :(

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.6, NixOS, 19.03.git.ad13c08 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by bignaux** [comment]
Can we close this, i test latest retro with appimage-run, seems to work.

**Comment by bignaux** [comment]
You might be interesting by #82158 if you want to be maintainer for this appimage.

**Comment by ThibaultLemaire** [comment]
Appimage `retroshare-gui-0-Build22.8.glibc2.17-x86_64.AppImage` tested functional on `NixOS 20.09 (Nightingale) x86_64` with `bi97pa78v8j5s3hrd6p7lhywjbgwz2qf-appimage-run`.

I think we can close this issue.

**Comment by ThibaultLemaire** [comment]
Although for the record and after further testing, I'd like to add that even if it launches, the Retroshare AppImage cannot establish connectivity in any way.

Opening port 4757 on both TCP and UDP in NixOS's firewall has **failed to fix the issue**. (This is the port that Retroshare seems to use for peer discovery. I don't know the DHT connection mechanism.)

```nix
{
  networking.firewall = {
    allowedTCPPorts = [
      4757
    ];
    allowedUDPPorts = [
      4757
    ];
  };
}
```

This AppImage should therefore be considered **non-functional**.

**Comment by flexiondotorg** [comment]
As per the earlier comments, the RetroShare AppImage has been working with `appimage-run` for some time now.
