### ISSUE TITLE
Using overlays to change nixos module behaviour

### ISSUE THREAD

**Issue by netixx** [NixOS/nixpkgs#46464]
## Issue description
Hello,

I have been reading about overlays, and I wonder if it is possible to use them to override behaviour of one or more nixos modules. The only examples I have seen with overlays concerned packages (and not nixos modules).

Say for example, I wanted to implement [this PR](https://github.com/NixOS/nixpkgs/pull/35841) as an overlay because It is specific to my setup, could it be done with overlays ?

In more details, how could I change `nixos/modules/tasks/network-interfaces-systemd.nix` code (without having to rebase patches on top of nixpks) ? Could overlays do that ?

Thank you

**Comment by Moredread** [comment]
I'm not sure that you can do this with overlays, but you can disable a config module and import your own variant.

In your case you could copy `nixos/modules/tasks/network-interfaces-systemd.nix` to your nixos directory, make your changes and add this to your config:

```
imports = [ ./network-interfaces-systemd.nix  ];
disabledModules = [ "tasks/network-interfaces-systemd.nix" ];
```

**Comment by netixx** [comment]
Ok thank you, I didn't know about this option !

I guess I can also use `mkOverride` and other related constructs to alter config properties in my config, but doing this, I need to rebuild the code in the `let` section of the module myself...

By the way, is there an `mkSomething` construct to undefine a value (say it is set by the module and I want it unset) ?

**Comment by rhendric** [comment]
> By the way, is there an `mkSomething` construct to undefine a value (say it is set by the module and I want it unset) ?

I wanted this too, so: #63553
