### ISSUE TITLE
adding widevine CDM support for qutebrowser

### ISSUE THREAD

**Issue by furrycatherder** [NixOS/nixpkgs#46506]
## Issue description

I have a package, `widevine-cdm`, mostly taken from the Chromium plugin:

https://gist.github.com/73880669d67a02fcb64e447f8c077fc9

And an overlay for `qutebrowser`:

```nix
{ pkgs ? import <nixpkgs> {} }:

with pkgs;

rec {
  qutebrowser = pkgs.qutebrowser.overrideAttrs (super: {
    propagatedBuildInputs = super.propagatedBuildInputs ++ [ widevine-cdm ];
    postFixup = ''
      ${super.postFixup}
      wrapProgram $out/bin/qutebrowser --add-flags "--set qt.args [ppapi-widevine-path=${widevine-cdm}/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so]"
    '';
  });
}
```

But trying to watch Netflix gets me this error:

```
[1:1:0910/214639.789895:ERROR:ppapi_thread.cc(317)] Failed to load Pepper module from /nix/store/9mqb31wvfx7wqargrh245h33gp3myir0-widevine-cdm-18.0.0.233/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so (error: /nix/store/9mqb31wvfx7wqargrh245h33gp3myir0-widevine-cdm-18.0.0.233/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so: cannot open shared object file: Operation not permitted)
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.69, NixOS, 19.03.git.571c6c6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(sean): `"nixos-19.03pre151837.ca2ba44cab4"`
 - channels(root): `"nixos-19.03pre151837.ca2ba44cab4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pmiddend** [comment]
I'd also really like widevice (e.g. Netflix and stuff) support for qutebrowser. Can anyone help with this?

**Comment by colemickens** [comment]
relevant prior art to possibly borrow from: https://aur.archlinux.org/packages/qt5-webengine-widevine

**Comment by ma9e** [comment]
@colemickens, I've already done most of the work re: prior art. See the gist I linked in my OP.

I submitted the issue hoping that someone can tell us why we're getting "operation not permitted".

**Comment by colemickens** [comment]
@ma9e yeah, I did notice the gist last night. I spent a couple of hours trying to get your `widevine-cdm` to work with Falkon, but couldn't really figure it out...

**Comment by pmiddend** [comment]
@ma9e Just to make this easily reproducible, could you post your overlay with the widevine and qutebrowser packages?

**Comment by JustinLovinger** [comment]
Has there been any progress on this front? It looks like Qutebrowser still doesn't have support for drm content like Netflix and Spotify.

**Comment by xdefrag** [comment]
Hey.

Has anyone find solution to this problem? Still can't figure out how to overlay qutebrowser to play spotify.

**Comment by nrdxp** [comment]
Sorry everyone, didn't realize this issue was open but I have a working widevine package defined here:
https://github.com/nrdxp/devos/blob/nrd/pkgs/applications/networking/browsers/widevine/default.nix

Meant to upstream it at some point but time got away from me. One can use a nix snippet like the following in their qutebrowser config to make use of it:
```nix
c.qt.args.append('widevine-path=${pkgs.widevine-cdm}/lib/libwidevinecdm.so')
```

**Comment by jlamur** [comment]
FYI, I have opened a PR that basically imitates what was done on `chromium` with the flag `enableWideVine` : https://github.com/NixOS/nixpkgs/pull/194479.
