### ISSUE TITLE
Package datadog-process-agent

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#46520]

**Comment by coretemp** [comment]
@domenkozar Have you ever seen Live Process monitoring work on NixOS? If so, can you share your configuration?

**Comment by coretemp** [comment]
Great, looking forward to it.

**Comment by domenkozar** [comment]
Upstream issue: https://github.com/DataDog/datadog-process-agent/issues/182

**Comment by coretemp** [comment]
Great, this feature works on our systems.

**Comment by coretemp** [comment]
@domenkozar / @rvl Is the `process` module supposed to work (not Live Process Monitoring)?

I.e. configuration that ends up in `process.d/conf.yaml`?

I get "No module process" from `agent status`.

**Comment by domenkozar** [comment]
Haven't used that with agent v6.
