### ISSUE TITLE
open-vm-tools: /etc/os-release is too large

### ISSUE THREAD

**Issue by rawtaz** [NixOS/nixpkgs#46527]
## Issue description
The `vmwareGuest` service fails to start, giving the following error messages in ``/var/log/vmware-vmsvc.log``:
~~~
[Sep 11 14:50:09.578] [ warning] [vmsvc] HostinfoReadDistroFile: input buffer too small
[Sep 11 14:50:09.578] [ warning] [vmsvc] HostinfoOSData: Error: no distro file found
[Sep 11 14:50:09.578] [ warning] [guestinfo] Failed to get OS info.
~~~

### Steps to reproduce
- Install a fresh copy of NixOS 18.03 in a VM under VMware Fusion 10.1.3 on macOS 10.12.x.
- Configure relevant parts in `/etc/nixos/configuration.nix`, e.g.:
~~~
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  # boot.loader.grub.efiSupport = true;
  # boot.loader.grub.efiInstallAsRemovable = true;
  # boot.loader.efi.efiSysMountPoint = "/boot/efi";
  # Define on which hard drive you want to install Grub.
  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  # networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Select internationalisation properties.
  # i18n = {
  #   consoleFont = "Lat2-Terminus16";
  #   consoleKeyMap = "us";
  #   defaultLocale = "en_US.UTF-8";
  # };

  # Set your time zone.
  # time.timeZone = "Europe/Amsterdam";

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    mkpasswd
    vim
    rxvt_unicode
    firefox
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.bash.enableCompletion = true;
  # programs.mtr.enable = true;
  # programs.gnupg.agent = { enable = true; enableSSHSupport = true; };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable sound.
  # sound.enable = true;
  # hardware.pulseaudio.enable = true;

  # Enable the X11 windowing system.
  # services.xserver.enable = true;
  # services.xserver.layout = "us";
  # services.xserver.xkbOptions = "eurosign:e";

  # Enable touchpad support.
  # services.xserver.libinput.enable = true;

  # Enable the KDE Desktop Environment.
  # services.xserver.displayManager.sddm.enable = true;
  # services.xserver.desktopManager.plasma5.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.extraUsers.rawtaz = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = ["wheel"];
  };

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "18.03"; # Did you read the comment?

  services.vmwareGuest.enable = true;
  services.vmwareGuest.headless = true;
  services.xserver.enable = true;
  services.xserver.windowManager.i3.enable = true;
  services.xserver.displayManager.lightdm.enable = true;
}
~~~

## Technical details
~~~
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133192.45f52f765cd (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
~~~

## Further comments and workaround
Based on the code in https://github.com/vmware/open-vm-tools/blob/3a0205478e242bd672356d4eab6272d3b901fe6e/open-vm-tools/lib/misc/hostinfoPosix.c#L932 it seems that the contents of the file `/etc/os-release`, which is scanned by `open-vm-tools`, is simply too large:
~~~
NAME=NixOS
ID=nixos
VERSION="18.03.133192.45f52f765cd (Impala)"
VERSION_CODENAME=impala
VERSION_ID="18.03.133192.45f52f765cd"
PRETTY_NAME="NixOS 18.03.133192.45f52f765cd (Impala)"
HOME_URL="https://nixos.org/"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
~~~

I tested that by creating a file `/etc/release` (which is also scanned by `open-vm-tools`), with only part of the contents:
~~~
NAME=NixOS
ID=nixos
VERSION="18.03.133192.45f52f765cd (Impala)"
VERSION_CODENAME=impala
VERSION_ID="18.03.133192.45f52f765cd"
PRETTY_NAME="NixOS 18.03.133192.45f52f765cd (Impala)"
~~~

After a few seconds, when the `vmwareGuest` service tries to start again, there's only one of the previously three error messages in ``/var/log/vmware-vmsvc.log``:
~~~
[Sep 11 14:50:09.578] [ warning] [vmsvc] HostinfoReadDistroFile: input buffer too small
~~~

The `vmwareGuest` service started, the above error message is for the still remaining and too large `/etc/os-release` file (to verify, let the contents of `/etc/release` be identical to that of `/etc/os-release` and notice that the other error messages comes back in the log file).

**Comment by rawtaz** [comment]
@joamaki Ping, looks like you're the maintainer :)

**Comment by rawtaz** [comment]
FWIW, I also verified that it doesn't make a difference if the /etc/os-release file is a regular file or a symlink, same symptoms apply.

**Comment by aanderse** [comment]
My /var/log/vmware-vmsvc.log file is littered with the same errors as yours, but the vmware service is still running. I'll note I don't have any shared folders.

> systemctl status vmware.service
> vmware.service - VMWare Guest Service
> Active: active (running) since Thu 2018-09-06 12:37:51 EDT; 1 weeks 0 days ago

**Comment by rawtaz** [comment]
I guess I can do that, raising the question "shouldn't it be allowed to be bigger?".

Regardless of what it *looks* like, it is evidently too big for the vmware-vmsvc code to handle as it is now :/

I'm thinking of patching the vmware service in the Nix derivation, but it would of course be better to have it done upstream or that Nix generated a smaller file.

**Comment by aanderse** [comment]
I also ran the lsb release tool on NixOS in the VM and didn't get any output. Is that the expected result? I'm guessing not... If the lsb release tool worked on NixOS that might also solve the problem.

@rawtaz Can you let me know if running lsb_release has any output for you?

**Comment by rawtaz** [comment]
@aanderse Can you elaborate on how the `lsb_release` tool could solve the problem? AFAICT it just produces output. I assume you mean that if we take this output and put it in an `/etc/lsb-release` file, the problem is solved? But the file in question would still be restricted to the same size limitations as the other files that are scanned, or is there a difference in limitation between this one and other files?

FWIW, same here, not much info from `lsb_release`:
~~~
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	n/a
Description:	NAME=NixOS
Release:	n/a
Codename:	n/a
~~~

**Comment by aanderse** [comment]
@rawtaz I didn't review the openvm-tools closely enough to say but after a quick glance it appears that the source file you linked can use the output of lsb_release to identify the distro.

https://github.com/vmware/open-vm-tools/blob/3a0205478e242bd672356d4eab6272d3b901fe6e/open-vm-tools/lib/misc/hostinfoPosix.c#L1132

I wondered if adding a quick substitution in the source code to ${pkgs.lsb-release}/bin/lsb_release for /usr/bin/lsb_release might be enough to identify the distro.

**Comment by rawtaz** [comment]
Reported upstream, let's hope they increase the buffer, so we don't have to require additional binaries just to make this service work.
