### ISSUE TITLE
No obvious way to view manual in NixOS 18.09 VirtualBox image

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#46537]
## Issue description

Running the virtualbox image for NixOS 18.09, hit this usability issue.

### Steps to reproduce

1. Download the .ova file from
https://releases.nixos.org/nixos/18.09/nixos-18.09beta78.6f3bd5db2f4/nixos-18.09beta78.6f3bd5db2f4-x86_64-linux.ova
2. Start it up in VirtualBox.
3. Once logged in, click on the KDE menu.
4. Click "Applications" -> "System" -> "View NixOS documentation in a web browser".

KDE asks what to use to open the .html file. No real option is available, you will have to install it yourself.

### Possible solution

It would make sense to include a simple browser for graphical users. Alternatively, package documentation as a PDF and include a PDF reader.

**Comment by abloch** [comment]
@matthewbauer - isn't adding firefox to the graphical profile a bit too intrusive and unjustified?

I think [graphical](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/graphical.nix) should remain  very narrow (only a plasma5, sddm and pulseaudio). firefox is a web-browser, this far exceeds what I'd expect from a minimal graphical profile
