### ISSUE TITLE
tor-browser-bundle-bin 8.0 crashes when attempting to save a page/image (GLib-GIO-ERROR)

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#46587]
Cc @joachifm
 
## Issue description

With the latest `tor-browser-bundle-bin`, attempting to save (e.g. by hitting `Ctrl+S`) a web page crashes the browser with the below error:

```
(firefox:29801): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

### Steps to reproduce

Build (`/nix/store/gjbwaq6ldnm8k3iilnycvfnpxilnli27-tor-browser-bundle-bin-8.0`) and run:

 ```shell
$ nix-build https://github.com/NixOS/nixpkgs/archive/master.tar.gz -A tor-browser-bundle-bin
$ ./result/bin/tor-browser
```

Hit `Ctrl+S`

**Comment by joachifm** [comment]
Thank you for the report. I can reproduce this, working on a fix.

**Comment by joachifm** [comment]
5710ee3befcb9c707189d835bb23fb971f81dcf4 fixes the problem on my end.

**Comment by stefano-m** [comment]
Thanks for the quick fix!
I can confirm that the browser now works.

**Comment by joachifm** [comment]
Thank you for testing. I suspect there could be other issues with the update to gtk3, please let me know if you encounter any.
