### ISSUE TITLE
ISO boot: frequent graphics problems

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#4659]
People tend to report they fail to boot unless with ``nomodeset`` flag in grub. As modesetting is hardly important during installation, I think this should be the default.

I don't know why this happens. Maybe due to kernel being too old (for the HW in question).

**Comment by domenkozar** [comment]
Is this still an issue?

**Comment by vcunat** [comment]
I'm not knowledgeable at all in these things, but it seems possible the issues will get resolved by #8173.

**Comment by edolstra** [comment]
The ISOs now have `nomodeset` and blacklist the `nouveau` kernel module (6948c3ab80797770bc584e521b5c5a8ca02b495e).

**Comment by vcunat** [comment]
I assume these problems are gone. Feel free to reopen.
