### ISSUE TITLE
sqlitebrowser crashes when run nix-shell

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#46605]
## Issue description
```
nix-shell -p --pure sqlitebrowser --run sqlitebrowser
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
/tmp/nix-shell-16530-0/rc: line 1: 17015 Aborted                 sqlitebrowser
```

### Steps to reproduce
Full repro on my operating system: `nix-shell -p --pure sqlitebrowser --run sqlitebrowser`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.git.8b92a4e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/search?q=This+application+failed+to+start+because+it+could+not+find+or+load+the+Qt+platform+plugin+%22xcb%22&type=Issues
