### ISSUE TITLE
datadog 6: logging agent

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#46660]
## Issue description
Datadog6 also has a "logging agent" (see agent status) output, which returns: 
`Logs Agent is not running`. 

The expected response is that it is running when it is instructed to run via: 

```
    services.datadog-agent.extraConfig = {
      logs_enabled = true;
    };
```

### Steps to reproduce
```
agent status | grep 'Logs Agent is not running'
```

### Related people
@rvl @domenkozar 

## Technical details

`master`

**Comment by domenkozar** [comment]
this works in v7
