### ISSUE TITLE
Make cabal install fail

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#4666]
People try that and don't understand why it doesn't work. I don't blame them, as one can't directly see it shouldn't work. (AFAIK it shouldn't work.)

As @joelteon suggested, we could just patch it to print a big fat warning and fail if ``cabal install`` is used. And we could document haskell development in official nixpkgs docs, BTW.

**Comment by peti** [comment]
This issue hasn't seen any activity in the last couple of months. I'm closing it for the time being. If anyone has a concrete patch for `cabal-install`, then please re-open this issue (or just open a new PR).
