### ISSUE TITLE
diagrams-builder pgf backend

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#46672]
## Issue description
The diagrams-builder Haskell package (and the regular executable) don't include the pgf backend for some reason. What's needed is to add the `-fpgf` configure flag, add `diagrams-pgf` to `executableHaskellDepends`, and add `pgf` to the list of backends in the `diagrams-builder` package. I'm happy to make that pull request, but is there a reason this isn't default?

Also, if it's not default, is there an easy way to do it post-facto? When I try to modify the haskell `diagrams-builder` package with `diagrams-builder.overrideAttrs { ... }` it complains that `executableHaskellDepends` isn't an existing attribute.

### Steps to reproduce
Try to use `diagrams-builder-pgf` after installing the `diagrams-builder` package.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.09pre149415.8395f9aa85e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-19.03pre152504.56b9f6fc8e1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
`overrideAttrs` modifies `stdenv.derivation`; the Haskell package lives on a higher level, which can be changed with `overrideCabal`. See [conifguraton-nix.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-nix.nix) for some examples.

**Comment by Radvendii** [comment]
This seems to require `haskellLib`, which I can't tell how to get access to.

Also, is it possible this is an underlying problem with the `diagrams-pgf` package? It seems like something that `jailbreak=true;` might solve, but I'm not sure exactly how to use that.

**Comment by Radvendii** [comment]
Figured it out. I just needed to use `haskell.lib` instead of `haskellLib`, and `haskell.lib.doJailbreak` seems to do the trick

**Comment by Ekleog** [comment]
(triage) Suggest closing, as the question has been answered. A separate issue can be created for the broken package, with more details.
