### ISSUE TITLE
zfs urgent: 0.7.10 has a bug 

### ISSUE THREAD

**Issue by eighal** [NixOS/nixpkgs#46675]
## Issue description

A serious bug has just been announced for zfsonlinux version 0.7.10, which is currently included in NixOS unstable.

### Steps to reproduce

I haven't reproduced the bug myself, but there's a clear bug report at https://github.com/zfsonlinux/zfs/issues/7906, and I have a reliable report of the bug being observed by a NixOS user (@clever).

@clefru, could you please take the version of zfs in nixos-unstable back to 0.7.9 until this is resolved?  Thanks!

**Comment by eighal** [comment]
P.S. They've released zfs 0.7.11 to fix this bug, so upgrading to that would be another option.

**Comment by xeji** [comment]
cc @fpletz @Mic92. 
This also affects 18.09.

**Comment by xeji** [comment]
fixed in #46676

**Comment by fpletz** [comment]
Thanks!
