### ISSUE TITLE
Dell XPS 13 models need blacklisted Nouveau

### ISSUE THREAD

**Issue by alexameen** [NixOS/nixpkgs#46686]
## Issue description

Hey I have been stumbling around for a few weeks now trying to fix my wake from suspend issues.
It usually presents itself as closing and opening the lid, which results in the screen not waking properly.

This can be resolved by blacklisting "nouveau" from kernelModules.
Various other XPS issues are also present as a result of insufficient kernel modules being detected when creating hardware-configuration.nix
These can be fixed by adding the list of modules seen on Arch's XPS 13 page.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by erictapen** [comment]
Hey,

are you aware of [nixos-hardware](https://github.com/NixOS/nixos-hardware/tree/master/dell/xps/15-9550)? It already has a profile for the Dell XPS 15, maybe you could provide a module for your model? This way, people benefit from your knowledge more easily.

**Comment by eadwu** [comment]
Recently I've been having problems with suspend with the `nvidia` driver but not with it disabled. Though it seems to be a result of a failed wake up from Linux PM.
