### ISSUE TITLE
Can we get rid of qt4?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#46719]
It uses a deprecated API in CoreFoundation on Darwin in a nontrivial way and I'd rather not jump through a bunch of hoops to support ancient code when QT5 has been out for over half a decade now 😄

**Comment by jcumming** [comment]
... and qt4 has some parallel build bogons. 

I have CAD tools that depend on it, so I'd nees to keep it alive on linux.

**Comment by matthewbauer** [comment]
I think removal makes sense. We can do it in 19.03 and encourage people to use older channels for the couple of cases that need it.

**Comment by orivej** [comment]
> ... and qt4 has some parallel build bogons.

What do you mean?

**Comment by jcumming** [comment]
> > ... and qt4 has some parallel build bogons.
 
> What do you mean?

It randomly fails with parallel building enabled.

**Comment by copumpkin** [comment]
@jcumming the CAD tools are unmaintained? or why do they need such an old QT?

@matthewbauer 🍾

**Comment by jcumming** [comment]
> @jcumming the CAD tools are unmaintained? or why do they need such an old QT?

These are commercial tools, and maintenance is somewhat opaque to me. I don't oppose the removal from upstream nixpkgs, I'll just have to diverge farther from mainline.. :(

**Comment by copumpkin** [comment]
@jcumming you could also do something like `(import (builtins.fetchurl { url = "https://github.com/nixos/nixpkgs/archive/abcdef123456.tar.gz"; sha256 = "blahblah"; }) {}).qt4` in your expressions

**Comment by orivej** [comment]
I'd prefer to keep such core libraries as long as they are needed by the users of Nixpkgs and maintainable, and this means limiting Qt 4 platforms to Linux (unless somebody wants to update it for macOS).

> It randomly fails with parallel building enabled.

Could you report this with an error message? AFAIK qt48 has no issues with parallel building.

**Comment by copumpkin** [comment]
Sure, I'd be okay with removing macOS from its supported platforms too, although the main difference to me is that removing the package entirely forces us to go through its dependents and making sure that they don't actually need it, whereas changing platforms might just silently make packages disappear for macOS 😄

**Comment by orivej** [comment]
> to go through its dependents and making sure that they don't actually need it

This is being done in #33248.

**Comment by Ma27** [comment]
I agree with @orivej, removing `qt4` entirely will be quite hard.

I looked into most of the packages in #33248 some months ago and a lot of them are still used and maintained, but don't provide (or actively work on) QT5 support, so I'm not sure if we want to drop it for `linux` as well.

**Comment by vcunat** [comment]
Migrating individual packages using qt4 is the main point IMHO.  There was discussion about this around https://github.com/NixOS/nixpkgs/issues/33248#issuecomment-406859670

And the other part is removing darwin from qt4.meta.platforms &ndash; on the point where it's not really usable on Darwin anymore (I can't see from the description when that happens).

**Comment by copumpkin** [comment]
I added patches that made it work on Darwin again, so this is less pressing, but still should be a goal IMO.

**Comment by peterhoeg** [comment]
Closing in favour of #33248
