### ISSUE TITLE
network-manager-applet fails at importing .ovpn file

### ISSUE THREAD

**Issue by candeira** [NixOS/nixpkgs#46729]
## Issue description

I have some .ovpn files that import well using network-manager-applet on my up-to-date Debian system, but the import process (or possibly the graphical UI saving process) mangles the key/ca/cert when importing on NixOS 18.03.

Looks to me like a possible upstream regression, but I don't know how to deal with that, so...

Here are the versions running on the Debian system:

network-manager: 1.6.2-3
network-manager-openvpn: 1.2.8-2
network-manager-openvpn-gnome: 1.2.8-2

Here are the versions running on the NixOS 18.03 system:

network-manager: 1.10.2
network-manager-openvpn: 1.8.0

And on NixOS 18.09:

network-manager: 1.12.0
network-manager-openvpn: 1.8.4

### Steps to reproduce

Via the GUI:
- Using nm-applet, open "VPN Settings"
- On the VPN Settings window, click on the "+" symbol next to "VPN"
- On the Add VPN dialog, select "Import from file..."
- On the file dialog, select and open a known good .ovpn file
- At this point, the key/ca/cert seem fine on the configuration dialog. [1]
- Still in the configuration dialog, enter user and password, and hit 'Save'.
- Try to connect with the VPN. It will fail.
- Re-open the configuration dialog, and see how the key is now empty, and both the ca and the cert point to the ca. [2]
- Edit NetworkManager's openvpn configuration by hand in /etc/NetworkManager/system-connection/$yourconnectionname, to fix the ca/cert/key configuration.
- Re-open the configuration dialog, and see how it shows an empty key field, and the ca file for both the ca and the cert, as above.

[1]
![image](https://user-images.githubusercontent.com/91694/45593438-f7b1f480-b9c9-11e8-94a1-5b4f57e103b4.png)

[2]
![image](https://user-images.githubusercontent.com/91694/45593420-c507fc00-b9c9-11e8-9f05-b6321c8c4809.png)

## Technical details

[root@desire:/etc/nixos]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.68, NixOS, 18.03.git.dbdcdd3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(kandinski): `"nixos-18.09-18.09beta230.32c008a946c"`
 - channels(root): `"nixos-18.03.133224.5f59ab7d4e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
There were some VPN regressions in nm and nm-a, not sure if they affected 18.03.

**Comment by candeira** [comment]
Hi, @jtojnar 

I've now updated to 18.09, and this is what I see:

![image](https://user-images.githubusercontent.com/91694/46590262-40eef300-caf5-11e8-8c11-e2a32276a09f.png)

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/47212 might need backporting.

**Comment by prusnak** [comment]
I created a backport PR here: https://github.com/NixOS/nixpkgs/pull/48220

**Comment by prusnak** [comment]
https://github.com/NixOS/nixpkgs/pull/48220 is merged into release-18.09 now

**Comment by jtojnar** [comment]
Thanks.
