### ISSUE TITLE
texlive: changes trigger mass rebuilds

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#46740]
### Issue description

Pretty much any change to `texlive` or its packages triggers a mass rebuild (examples: #46376, #40232),  mainly because it is used to build documentation for many packages. 

This makes `texlive` difficult to maintain/bugfix as any change must go through a staging iteration.

My analysis (using `maintainers/scripts/rebuild-amount.sh`) indicates that the mass rebuild is mainly caused by `gtk-doc`, which depends on `texlive` via `dblatex`.

### How can we fix this? 

I see 2 possible solutions (of course, any fix will cause a mass rebuild :smile:):

1.  Build `gtk-doc` without `dblatex` by default, which removes the `texlive` dependency. It won't be able to generate pdf docs, but do we really need them? This is my recommendation.

2. Duplicate `texlive` as `texlive-for-docs`  and use that for `gtk-doc` and other packages generating docs. `texlive-for-docs` won't need frequent updates, it's good enough if it works.

---

cc  @vcunat @samueldr @jtojnar @pSub @veprbl @bhipple

**Comment by vcunat** [comment]
1. sounds OK to me.  Few people want docs in PDF nowadays, I believe, as few print it and other formats tend to be better on-screen.

Note: 2. wouldn't have to cause a mass rebuild, but I believe we can easily afford a "last" rebuilt this way.

**Comment by jtojnar** [comment]
:+1: for number one. Removing dblatex is required for building glib 2.58 docs: https://github.com/NixOS/nixpkgs/pull/45950#issuecomment-421545698

**Comment by bhipple** [comment]
Also :+1: for number 1.  In general I'd imagine almost nobody looks at PDF docs by default, and if they do they can just build them.

**Comment by xeji** [comment]
Should be fixed by #46761 (in staging now).
