### ISSUE TITLE
geoclue2 keeps restarting

### ISSUE THREAD

**Issue by furrycatherder** [NixOS/nixpkgs#46746]
## Issue description

```
Sep 16 10:50:53 akita systemd[1]: Starting Location Lookup Service...
Sep 16 10:50:53 akita systemd[1]: Started Location Lookup Service.
Sep 16 10:50:59 akita systemd[1]: Starting Location Lookup Service...
Sep 16 10:50:59 akita systemd[1]: Started Location Lookup Service.
Sep 16 10:51:06 akita systemd[1]: Starting Location Lookup Service...
Sep 16 10:51:06 akita systemd[1]: Started Location Lookup Service.
Sep 16 10:51:12 akita systemd[1]: Starting Location Lookup Service...
Sep 16 10:51:12 akita systemd[1]: Started Location Lookup Service.
Sep 16 10:51:19 akita systemd[1]: Starting Location Lookup Service...
Sep 16 10:51:19 akita systemd[1]: Started Location Lookup Service.
```
Trying to run it manually gives

```
(geoclue:12164): Geoclue-CRITICAL **: 10:59:11.310: Failed to acquire name 'org.freedesktop.GeoClue2' on system bus or lost it.
```
### Steps to reproduce
```
      redshift = {
        enable = true;
        provider = "geoclue2";
      };
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.69, NixOS, 19.03pre152634.218ce4de508 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(sean): `"nixos-19.03pre151837.ca2ba44cab4"`
 - channels(root): `"nixos-19.03pre152634.218ce4de508"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cyounkins** [comment]
This suggests you may need to run as root or adjust location permissions: https://github.com/jonls/redshift/issues/445
See also https://wiki.archlinux.org/index.php/redshift#Automatic_location_based_on_GeoClue2
