### ISSUE TITLE
switch-to-configuration.pl:"reload user units" does not execute in user shell

### ISSUE THREAD

**Issue by jamesbroadhead** [NixOS/nixpkgs#46750]
## Issue description
```
$ nixos-rebuild switch --upgrade

... 
activating the configuration...
setting up /etc...
reloading user units for jbo...
/home/jbo/.git-completion.bash: line 2715: complete: command not found
/home/jbo/.git-completion.bash: line 2715: complete: command not found
/home/jbo/.bash_profile: line 114: set: vi: invalid option name
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: polkit.service
starting the following units: accounts-daemon.service
$ 
```
`set -o vi` is valid bash, and `complete` is a bash shell builtin.
This implies to me that the 'reloading user units does not happen in the same shell the user has selected.

Looks like the perl script uses the system default shell from `pkgs.stdenv` -- instead, it should probably select the users' default shell. 

### Steps to reproduce
Add `set -o vi` to ~/.bashrc for a user, then run 
`nixos-rebuild switch --upgrade`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.69, NixOS, 19.03pre152634.218ce4de508 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-19.03pre152634.218ce4de508"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by xeji** [comment]
> This implies to me that the 'reloading user units does not happen in the same shell the user has selected. Looks like the perl script uses the system default shell from pkgs.stdenv 

Correct. That was recently changed in #46042 because using the user's default shell caused problems in other cases. So going back to that is not an option. 

What we want is a reproducible behavior independent of the user's config files. 
So we will probably want to suppress loading any user shell init files to fix this issue.

cc @Ma27  @etu

**Comment by etu** [comment]
@xeji So... `bash-from-nixpkgs --noprofile --norc` as shell should do it?

**Comment by xeji** [comment]
Yes, that should fix this error.

**Comment by Ma27** [comment]
first of all, I'm sorry for all of your issues with the login shell due to my `su -c $user` stuff!

@etu's fix seems reasonable, do you want to file a PR? Otherwise I could do this including the testing (with several shells and your cases included)

**Comment by etu** [comment]
@Ma27: But I don't know how to supply these flags to `su`. Because we use the `-s` flag to `su` to specify shell, and this for example doesn't work:
```
su -l etu -s "/run/current-system/sw/bin/bash --norc --noprofile" -c "XDG_RUNTIME_DIR=/run/user/1000 /run/current-system/sw/bin/systemctl --user daemon-reload"
```

It exits with the error:
```
Cannot execute /run/current-system/sw/bin/bash --norc --noprofile
```

It seems that `su` doesn't like me adding params to the shell that I'm specifying.
