### ISSUE TITLE
It takes two separate LLVM builds to build mesa

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#46768]
I'm doing some experimentation with the darwin stdenv and noticed that not only was I building LLVM 5, which is expected in my stdenv, but also LLVM 3.9 and LLVM 6. It turns out that mesa explicitly asks for LLVM 6 (which might be reasonable) and also depends on valgrind, which explicitly asks for 3.9.

This might all be reasonable in isolation (I'm not familiar with any of those packages), but the overall result is that it takes a really really really long time to experiment 😄

I'm marking this as closure size to indicate _build_ closure size, which feels excessive. Feel free to close if this is actually the best we can do.

**Comment by matthewbauer** [comment]
So this was reworked in https://github.com/NixOS/nixpkgs/pull/45635 to avoid the old Darwin specific stuff. I'm hoping this isn't causing any specific issue but it's definitely possible it could be related.

**Comment by copumpkin** [comment]
Hmm maybe that's it; there's nothing strictly _wrong_ with the current situation, it just feels frustrating to watch three LLVMs go by as I wait, each taking 2 hours 😄

I'm guessing that once we upgrade the default LLVM to 6, mesa itself won't need to build a new one, and then it looks like the valgrind lock might be accidental? @periklis added it in https://github.com/NixOS/nixpkgs/commit/7c980f5e9c2c9c6bc58a5bdbe4009458a38d9e84 apparently to support `dsymutil`, which is now in pretty much all recent LLVM releases. I'll take that out and see if it works.

**Comment by matthewbauer** [comment]
Yeah but maybe valgrind can be bumped? LLVM 5 & LLVM 6 seems probably inevitable.

**Comment by copumpkin** [comment]
Yeah, it seems to work fine. It just wanted dsymutil

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/a257d64f333caa50facc57c0e3fc6a64620ed348

**Comment by periklis** [comment]
Yeah this was indeed a desperately pending task for valgrind 👍 At the time of #23393 `llvm_39` was the only available option for `dsymutil` and afaik the stdenv was on 3.8 or 3.7

**Comment by copumpkin** [comment]
https://github.com/llvm-mirror/llvm/blob/release_70/tools/dsymutil/LLVMBuild.txt#L20 so when we get 7 in, we can start bundling a fully real `dsymutil` in the stdenv.
