### ISSUE TITLE
datadog 6: Sending flares does not work

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#46776]
## Issue description
Previously reported, but it didn't have a separate issue. Datadog has the concept of a flare (https://docs.datadoghq.com/agent/troubleshooting/?tab=agentv6#send-a-flare), which is just debugging information (logs, etc.) which in then compressed and sent to their company.

The likely cause is a bug in the upstream code (in that it assumes too much about the execution environment). As such the question naturally comes up as to what we should do with what are essentially non-portable broken products? Should we spend time on non-portable software? If so, where should we draw the line?   

### Steps to reproduce
Try to follow Datadog instructions for sending a flare and see it fail.

## Technical details

Applies to all versions of NixOS ever released.

**Comment by Artturin** [comment]
We don't have this package anymore i think
