### ISSUE TITLE
Minor documentation nitpick: Python development mode

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#46775]
## Issue description

The documentation for Python development mode says:

> If we create a shell.nix file which calls buildPythonPackage, and if src is a local source, and if the local source has a setup.py, then development mode is activated.

This sounds like you need a `shell.nix` file and you need to use `buildPythonPackage`. But is that really true? I have a project that only has a `default.nix` and uses `buildPythonApplication` and it still seems to call `setup.py develop`.

**Comment by jtojnar** [comment]
Right, the name of the Nix file is not important – you can use any name and then run `nix-shell yourfile.nix`. I would guess the important thing is that you ran the shell (that is `$IN_NIX_SHELL` environment variable is set) but I do not see any relevant mentions of `develop` in nixpkgs.

`buildPythonApplication` does basically the same thing as `buildPythonPackage` so it makes sense that they work similarly:

https://github.com/NixOS/nixpkgs/blob/f86e309a9415049d6b0e4ad67fcf16f80e8b087d/pkgs/top-level/python-packages.nix#L54-L67

**Comment by FRidh** [comment]
Correct, any `.nix` file works, it's just that by convention we call it `shell.nix` and `nix-shell` also chooses `shell.nix` over `default.nix`.

**Comment by pmiddend** [comment]
Okay, thanks for the clarification guys!
