### ISSUE TITLE
Ansible fails to run in `nix-shell`, when other package (`yq`) is also a dependency.

### ISSUE THREAD

**Issue by jwoudenberg** [NixOS/nixpkgs#46789]
## Issue description
When combining `ansible` and `yq` packages in a `nix-shell`, ansible commands will fail. This looks to be due to `ansible` (a `python2` project) attempting to use `pyyaml` pulled in with `yq` (a `python3` project).

### Steps to reproduce
The following works:

```sh
nix-shell --pure -p ansible --run 'ansible --version'
```

The following doesn't work:

```sh
nix-shell --pure -p ansible yq --run 'ansible --version'
```

It fails with the following error:

```
Traceback (most recent call last):
  File "/nix/store/a8rxqzhrhcq4y5ck67rh3ssm9kx81yyy-python2.7-ansible-2.6.2/bin/.ansible-wrapped", line 68, in <module>
    import ansible.constants as C
  File "/nix/store/a8rxqzhrhcq4y5ck67rh3ssm9kx81yyy-python2.7-ansible-2.6.2/lib/python2.7/site-packages/ansible/constants.py", line 17, in <module>
    from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
  File "/nix/store/a8rxqzhrhcq4y5ck67rh3ssm9kx81yyy-python2.7-ansible-2.6.2/lib/python2.7/site-packages/ansible/config/manager.py", line 14, in <module>
    from yaml import load as yaml_load
  File "/nix/store/d14wyhghrdkqr660hbcqmlvh6lkip80m-python3.6-PyYAML-3.13/lib/python3.6/site-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `""`
 - channels(jasper): `""`
 - nixpkgs: `/Users/jasper/dev/nixpkgs`
```

I'm running this against the latest `master` commit on `nixpkgs` at the time of writing (`463704a62e3564b951eff84909eeffea4d728130`).

**Comment by matthewbauer** [comment]
Yeah this is kind of awkward, but I don't think there is really an easy fix.

As a workaround, reseting PYTHONPATH should work:

```
nix-shell --pure -p ansible yq --run 'PYTHONPATH= ansible --version'
```

**Comment by FRidh** [comment]
`nix-shell` is intended for opening a shell to develop a package. In this case, you would like to simply have a shell with the listed packages on your `$PATH`. In that case, use `nix run`. Contrary to `nix-shell`, this won't execute any setup hooks, and thus `PYTHONPATH` won't be exported.

```
$ nix run nixpkgs.ansible nixpkgs.yq -c ansible --version
```
