### ISSUE TITLE
Attribute 'buildPythonApplication' missing in multibootusb

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#46798]
## Issue description

On MacOS, `nix-env -qc` gives the following error:

```
error: attribute 'buildPythonApplication' missing, at /nix/store/b4yn2qhc6hwmzbsq3qmmz6jldlpqzg4s-nixpkgs-19.03pre152754.f456d7f5753/nixpkgs/pkgs/applications/misc/multibootusb/default.nix:2:1
```

### Steps to reproduce

```
% nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
% nix-channel --update
unpacking channels...
% nix-env -qc
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(smaret): `"nixpkgs-19.03pre152754.f456d7f5753"`
 - nixpkgs: `/Users/smaret/.nix-defexpr/channels/nixpkgs`

**Comment by smaret** [comment]
@LnL7 @matthewbauer : any ideas of what may cause this issue? That's a blocker for me, it can't use `nix` anymore.

**Comment by LnL7** [comment]
nixpkgs-unstable has updated since and I can't reproduce it with the latest version.

```
nix-env -f channel:nixpkgs-unstable -qc
```

**Comment by smaret** [comment]
I found the problem: it was due to the following lines in my `config.nix`:

```nix
{
  packageOverrides = pkgs: with pkgs; {
    python36Packages.matplotlib = python36Packages.matplotlib.override { enableTk = true; }; # this causes the bug
    python3Env = python3.withPackages (ps: with ps; [ matplotlib ] );
  };
}
```

The package override was meant to enable the Tk backend in `matplotlib`, but somehow it screws things up.
