### ISSUE TITLE
Package LLVM 7

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#46805]
Gotta cache 'em all 😁

A big benefit is that it finally includes a fully functional `dsymutil` for Darwin. I might even be tempted to make it the default and skip 6.

**Comment by dtzWill** [comment]
I'm packaging up rc3 now, and even if hashes require rebuilding when final tarballs are posted the source is the same and so if we get things working with rc3 it'll be an easy transition.

**Comment by copumpkin** [comment]
Awesome, thank you! FWIW final is already tagged in SVN: https://llvm.org/svn/llvm-project/llvm/tags/RELEASE_700/final/

**Comment by dtzWill** [comment]
Yeah, they just delay for "reasons" actually making the final source tarballs available until the release-testers have all uploaded the binaries for all supported architectures.

I expect the reasons are mostly that that's the process that makes sense to them and no one's expressed problems, not anything technical. 

I'm not sure if the final tarball will be different in name or if there are other minor ways it will be changed.  I might check using the 6 release but more likely we'll just see when 7 is released :P.

**Comment by alyssais** [comment]
Final tarball is up: http://releases.llvm.org/download.html#7.0.0
