### ISSUE TITLE
CUPS usage with gutenprint should be more straightful

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#4680]
Current way to install new printers (https://nixos.org/wiki/Printers) is not really the thing user will figure out without a manual, and I think we might try to do better. Maybe add a list of installed PPDs to services.printing or something like that, but I don't really know how CUPS finds or stores PPDs, so I don't know if this really can be made better.

#enhancement please

**Comment by Profpatsch** [comment]
There are two things that tripped me:

1. No obvious way how to use gutenprint in the docs (for someone not familiar with how cups works)
   - the [wiki](https://nixos.org/wiki/Printers) helped
   - the naïve way (installing gutenprint as package) doesn’t work and it doesn’t tell you why

2. Manually generating the ppds is necessary.
   - If possible, this should be done automatically while realizing the derivation
   - Does it take too much storage?

**Comment by Profpatsch** [comment]
When I added my printer again recently, the gutenprint ppds where directly accessible from the interface, so all one has to do now is add gutenprint to `services.printing.drivers`.

I just noticed there is `services.printing.gutenprint` now. Huzzah!

**Comment by abbradar** [comment]
Oh, I fixed that by myself recently and forgot. Let's close!
