### ISSUE TITLE
GPG keeps asking for passphrase over and over

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixpkgs#46828]
## Issue description
After bumping my system from `6993f19098f121bb6ba2199896e5b9bcffd3cb9a` to `ad755cc59d4af394f35c0245d370a8a915696f65` this morning, several issues cropped up. This is one of them.

gpg-agent keeps asking to unlock my keys over and over instead of caching the unlock for the configured amount of time.

### Steps to reproduce
Rebuild your system on `ad755cc59d4af394f35c0245d370a8a915696f65`, then try to use gpg a few times to test passphrase cache.

gpg-agent.conf
```
❯ cat ~/.gnupg/gpg-agent.conf
default-cache-ttl 86400
default-cache-ttl-ssh 86400
max-cache-ttl 86400
max-cache-ttl-ssh 86400
write-env-file
enable-ssh-support
no-grab
display :0
```

## Technical details

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.7, NixOS, 19.03.git.ad755cc (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by xeji** [comment]
I cannot find any commit ad755cc59d4af394f35c0245d370a8a915696f65  (or anything starting ad755cc) in our repository (and neither can github, or the commits would be linked here). 
Please verify.

**Comment by mkaito** [comment]
I'm a derp, that's the merge commit rev of my own fork. I'm so embarrassed now.

Last commit from nixpkgs is 218ce4de508.

**Comment by mkaito** [comment]
https://github.com/NixOS/nixpkgs/issues/46826#issuecomment-422924859
