### ISSUE TITLE
`reboot` and `poweroff` don't work

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixpkgs#46827]
## Issue description
After bumping my system from `6993f19098f121bb6ba2199896e5b9bcffd3cb9a` to `ad755cc59d4af394f35c0245d370a8a915696f65` this morning, several issues cropped up. This is one of them.

```
❯ poweroff
Failed to set wall message, ignoring: Interactive authentication required.
Failed to power off system via logind: Interactive authentication required.
Failed to talk to init daemon.
```

If you're the only user on the system, polkit should give you some amount of root permissions, which allows for example to reboot or power the system down, for desktop user convenience. This worked before, and now doesn't.

### Steps to reproduce
Rebuild your system on `ad755cc59d4af394f35c0245d370a8a915696f65`, reboot, then try to `poweroff`.

## Technical details
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.7, NixOS, 19.03.git.ad755cc (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by xeji** [comment]
I cannot find any commit ad755cc59d4af394f35c0245d370a8a915696f65  (or anything starting ad755cc) in our repository (and neither can github, or the commits would be linked here). 
Please verify.

**Comment by mkaito** [comment]
I'm a derp, that's the merge commit rev of my own fork. I'm so embarrassed now.

Last commit from nixpkgs is 218ce4de508.

**Comment by xeji** [comment]
I just upgraded my system to 218ce4d (including a reboot) and cannot reproduce this. Works fine here.

**Comment by mkaito** [comment]
https://github.com/NixOS/nixpkgs/issues/46826#issuecomment-422924859
