### ISSUE TITLE
Error when cross-building append-initrd-secrets

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#46847]
## Issue description

I'm currently trying to deploy a aarch64 system from a x86_64 system, but it fails with:

> error: a 'x86_64-linux' is required to build '/nix/store/j16l9pjhcbjfjwrbcylwb36b2clll67k-append-initrd-secrets.drv', but I am a 'aarch64-linux'

### Steps to reproduce

```
$ nixos-rebuild -I nixos-config=./configuration.nix --build-host root@192.168.178.45 --target-host root@192.168.178.45 switch
```

#### Deploying system

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.70, NixOS, 18.03.133231.01f5e794913 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(janne): `""`
 - channels(root): `"nixos-18.03.133231.01f5e794913, nixos-unstable-18.09pre140958.696c6bed4e8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

#### System being deployed

```
 - system: `"aarch64-linux"`
 - host os: `Linux 4.18.7, NixOS, 19.03.git.56b9f6fc8e1 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-19.03.git.56b9f6fc8e1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dasJ** [comment]
I inspected the .drv and it seems the system is set incorrectly to x86_64. Not sure how to override that…

**Comment by matthewbauer** [comment]
Note that it's not really a cross build what you're doing. It's just a remote native build (build host == target host).

**Comment by dasJ** [comment]
Solved with `--option system aarch64-linux`
