### ISSUE TITLE
yabar: test and module are broken

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#46899]
## Issue description

`nixos/tests/yabar` fails intermittently on hydra: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.yabar.x86_64-linux/all .  Affects master and 18.09, cc #45960. 

From the logs, it looks like the `yabar` service exits because no bar is defined. But due to incorrect timing the test _accidentally_ :smile:  succeeds sometimes because the test vm shuts down before the `yabar` service exits.

A quick look into the `yabar` module also lets me suspect that the config files it generates are syntactically incorrect (semicolons which shouldn't be there according to upstream doc), but I didn't have time to investigate further.

cc maintainer @Ma27  - if you don't have time to fix it we should at least remove the yabar test from `release.nix` to disable it on Hydra, it's not helpful in the current state.

**Comment by Ma27** [comment]
I can have a look tonight (or tomorrow) and report back. IIRC the test wasn't entirely pure on Hydra (I never managed to reproduce it locally unfortunately).

**Comment by Ma27** [comment]
I just had a short look at this. The module works perfectly fine with `yabar-unstable`, the stable version seems to have several issues. Let's see if I can fix it or `yabar-stable` as well, otherwise we may need to restrict the module for `yabar-unstable` (which is fairly usable as well AFAIK).

**Comment by xeji** [comment]
Thanks. What about the test? It looked like you would have to define a config with at least one bar for the test to succeed.

**Comment by Ma27** [comment]
I had a short look at this yesterday, but I was way too tired to fix this.

Thanks a lot for finding the cause for the broken test, I'm still not sure why it succeeded from time to time though.

I found several segfaults when using `yabar` (I only use `yabar-unstable` which works **wayy** better), so I never noticed :/

I'll implement a warning in the module which recommends to use `yabar-unstable` for now and links to several issues upstream, let's see if this fixes the issue :)

**Comment by xeji** [comment]
> I'm still not sure why it succeeded from time to time though.

systemd starts `yabar.service`, `yabar` reads its config file and exits with an error because there's no bar defined. `waitForUnit('yabar.service')` can only check if the systemd unit is in active state, so it succeeds it the short interval between unit startup and unit failure.

Here's a fix for the non-deterministic success:
```
$yabar->waitForUnit("yabar.service", "bob");   # start the unit
$yabar->sleep(10); # give it some time to fail
$yabar->waitForUnit("yabar.service", "bob");   # see if it's still there
```
