### ISSUE TITLE
glibc 2.27 -> 2.27+fixes, 2.28?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#46890]
## Issue description

Looks like we haven't been keeping our glibc up-to-date? Various fixes (including security) are on the upstream 2.27 branch, and at some point we probably want to move to 2.28.

Not sure how this should be handled, I think previously patch stacks were created semi-manually? Commit history reveals all I'm sure :).

**Comment by pbogdan** [comment]
RE: patches best I could find is https://github.com/NixOS/nixpkgs/blob/release-18.03/pkgs/development/libraries/glibc/common.nix#L56-L59 (at least as far as the recent-ish glibc patch updates are concerned IIRC).

**Comment by pbogdan** [comment]
Sorry for bumping this without nothing useful to contribute for now; looking at the changes in glibc 2.28 it seems that some of the security issues are addressed by `getaddrinfo` being able to dynamically load system installed `libidn2` (via `dlopen`). With no notion of system installed libraries under Nix where / how would the programs linked against glibc locate the library?

**Comment by pbogdan** [comment]
Just dumping some notes here in case they are useful at all.

A simple reproducer for the above returns:

```
$ ./result
perror: getaddrinfo: Success
$ LD_LIBRARY_PATH="$(nix-build './.' -A libidn2.out --no-out-link)/lib" ./result
Host: българия.icom.museum
IPv4 address: 91.194.60.138 ((null))
```

Anything that bundles Electron prior to https://github.com/electron/electron/releases/tag/v2.0.8 segfaults immediately upon startup on glibc 2.28. That seems to include the current Slack version in nixpkgs, maybe some other things...

i686-linux stdenv doesn't appear to build with glibc 2.28, required adding an extra stage in stdenv to rebuild binutils with new glibc (instead the one from bootstrap tools) before they are used to build gcc...

Packages that I needed to patch so far:

- syslinux
- jfsutils
- reiserfsprogs
- squashfsTools
- qt5.qtbase *
- v4l_utils *
- parted
- ppp
- sharutils
- systemd
- findutils
- gzip
- bison2
- gnum4
- llvmPackages_5.compiler-rt
- gcc6
- gcc7

\* an official upstream update is available

On a more positive note my own, admittedly very simple, system would appear to be usable and the tested job in `release-small` and `release-combined` does pass under glibc 2.28.

**Comment by vcunat** [comment]
> how would the programs linked against glibc locate the library?

I have some ideas, involving `libc.so` being an ld script (it is already) and thus always adding the required libraries when linking with libc.  I'm not sure when I can make that workable, as (stdenv) bootstrapping complicates this.

**Comment by pbogdan** [comment]
Just noting that 2.29 is scheduled for release on the 1st of February. To make things more "interesting" re: bootstrapping notable changes include:

> Changes to build and runtime requirements:
> 
> * Python 3.4 or later is required to build the GNU C Library.

**Comment by dtzWill** [comment]
2.29 is out (as you indicated it would be):

https://www.sourceware.org/ml/libc-alpha/2019-01/msg00723.html

**Comment by vbrandl** [comment]
Are there plans on when to upgrade to 2.29 or even 2.30?

**Comment by vcunat** [comment]
@vbrandl: yes, see https://github.com/NixOS/nixpkgs/pull/66528

**Comment by vcunat** [comment]
We have glibc-2.30 in master now.  https://github.com/NixOS/nixpkgs/pull/66528

The [packages from above](https://github.com/NixOS/nixpkgs/issues/46890#issuecomment-441336254) are all resolved, I believe.  (Other issues like the broken cross-compilation will better be discussed elsewhere.)
