### ISSUE TITLE
SDDM Autologin issues after update

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixpkgs#46912]
## Issue description
After updating from 5d18f66ddd4 to 218ce4de508 I encountered the following issues, all traced back to the option `services.xserver.displayManager.sddm.autoLogin.enable`.

* XDG_RUNTIME_DIR was not set.
* `poweroff` and `reboot` stopped working.
* gpg-agent wouldn't cache my key, and kept asking for the passphrase over and over.

Setting the above option to `false` seems to work as a workaround, pointing at a pam/logind issue or a problem in SDDM itself.

See #46828, #46827, #46826, and https://github.com/NixOS/nixpkgs/issues/46826#issuecomment-422924859

### Steps to reproduce
Rebuild on 218ce4de508, set `services.xserver.displayManager.sddm.autoLogin.enable = true`, reboot. Then try `echo $XDG_RUNTIME_DIR`, it should be empty. Or try `reboot` or `poweroff`, which should give you an error about logind.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.7, NixOS, 19.03.git.ad755cc (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-19.03pre152634.218ce4de508"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jfrankenau** [comment]
I am experiencing this as well but can’t reproduce this every login altough I am using SDDM’s autologin function.

**Comment by Nadrieril** [comment]
I run into the same issues but with lightdm autologin. These logs look related:
```
lightdm[919]: pam_unix(lightdm-autologin:session): session opened for user nadrieril by (uid=0)
systemd[1]: Created slice system-user\x2druntime\x2ddir.slice.
systemd[1]: Created slice user-1000.slice.
systemd[1]: Started /run/user/1000 mount wrapper.
systemd-logind[837]: New session 1 of user nadrieril.
[bunch of wpa_supplicant logs...]
lightdm[919]: pam_systemd(lightdm-autologin:session): Failed to create session: Connection timed out
lightdm[919]: Failed to open CK session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
```
I don't understand why lightdm times out since the session seems to have been created correctly.

**Comment by larkery** [comment]
I also experience this problem with lightdm auto-login. I think the issue is that logind believes that I am logging out as soon as I have logged in:

```
$ loginctl session-status 1           
1 - hinton (1000)
           Since: Fri 2019-01-18 18:39:26 GMT; 3 days ago
          Leader: 1172 (lightdm)
            Seat: seat0; vc7
         Display: :0
         Service: lightdm-autologin; type x11; class user
         Desktop: none+i3
           State: closing
            Unit: session-1.scope
                  └─1172 lightdm --session-child 12 15

Jan 18 18:39:55 limiting-factor systemd[1]: Started Session 1 of user hinton.
```

If I disable autologin, it doesn't go into state:closing, and lists all the child processes in the session.

This degree of systemd/logind voodoo is beyond me, so I haven't been able to understand what it's doing.

**Comment by larkery** [comment]
Incidentally, the relevant config for me is 

```
services = {xserver = {
      displayManager.auto.enable = true;
      displayManager.auto.user = "hinton";
}; };
```

**Comment by larkery** [comment]
Furthermore, switching to 

```
      displayManager.slim = {
         enable = true;
         autoLogin = true;
         defaultUser = "hinton";
      };
```

Has made it work for me, so I'm alright now.

**Comment by Nadrieril** [comment]
In recent nixpkgs-unstable, the problem seems to be fixed for me now, still with lightdm autologin.

**Comment by Ekleog** [comment]
Looks like this was resolved, so let's close :)
