### ISSUE TITLE
e2fsprogs-1.44.4 fails to build under musl

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#46923]
## Issue description

Reported upstream by someone else at https://www.spinics.net/lists/linux-ext4/msg62290.html , essential information quoted here:

> Commit fddc423dc6353 [in musl, not nixpkgs] (Fix compile error and warnings for old gcc versions) introduced usage of __GNUC_PREREQ. musl libc does not provide this macro. So build with musl is broken.

### Steps to reproduce

This nix expression will fail to build:

```nix
let
  nixpkgs = import (builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/18.09-beta.tar.gz";
    sha256 = "147xyn8brvkfgz1z3jbk13w00h6camnf6z0bz0r21g9pn1vv7sb0";
  }) {};
in
  nixpkgs.pkgsMusl.e2fsprogs
```

`pkgsMusl` only runs on linux systems, and the above expression took a long time to run as it had to first build a musl toolchain.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133235.305f13d3d73 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133235.305f13d3d73, nixos-unstable-18.03pre124947.33a4de2941d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by endgame** [comment]
That's really good to know. I'm using the 18.09-beta nixpkgs just because it seemed convenient, but if that change has made it to some other recent nixpkgs branch (master?) then I'm happy to use that instead.

**Comment by endgame** [comment]
Given there's a fix already in-tree, when is it appropriate to close this issue?

**Comment by dtzWill** [comment]
I was waiting for it to reach 'master', which has happened.  Thanks, and good question :).
