### ISSUE TITLE
Provide `hunspell` dictionary with `fr_FR.dict`

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#46940]
In #46779 I packaged an ibus-based completion method which heavily relies on hunspell dictionaries.
During the review iterations we realized that french didn't work[1].

When running `nix-locate fr_FR.dict` I get the following result:

```
languagetool.out                              1,198,614 r /nix/store/ssrsnyqy0972r1ppmc56yvxn7n1adkl2-LanguageTool-4.1/share/org/languagetool/resource/fr/hunspell/fr_FR.dict
```

It obviously seems as `hunspellDicts` doesn't provide a derivation which ships `fr_FR.dict`. The hunspell dictionaries for french we use are distirbuted by [dicollecte.org](https://dicollecte.org) which provides the variants `classique`, `moderne`, `reforme1990` and `any`[2].

As none of the reviewers speaks french, the PR has been merged as we didn't know a suitable solution[3], but in the long term french should be supported as well.

I'll need the feedback of a french native speaker, but for now I see the following solutions:

* Link `fr_$variant.dict` to `fr_FR.dict` in each derivation
* Choose the variant which suits best as a default (don't know which) and make it available as `hunspellDicts.fr-fr`.
* Use a different `fr_FR.dict` as default  (again, I don't know french, so I'm not qualified to take such a decision)

[1] https://github.com/NixOS/nixpkgs/pull/46779#issuecomment-422586464
[2] https://github.com/NixOS/nixpkgs/blob/856868d72c06fdb47180ec78dc197c6afd406bac/pkgs/development/libraries/hunspell/dictionaries.nix#L427-L467
[3] https://github.com/NixOS/nixpkgs/pull/46779#issuecomment-422764601

**Comment by teto** [comment]
I am quite busy at the moment but next week, I will have a look (as a "modern" French speaker).

**Comment by symphorien** [comment]
The "any" dictionary is the union of all other dictionaries (which are more "opinionated"). For a spell checker I think it makes sense use the broadest dictionnary as the default, ie make fr_FR a symlink to fr-any.

**Comment by Ma27** [comment]
Thanks a lot for your elaboration. I'll file a PR to implement this (and fix this for `ibus-typing-booster`).

**Comment by jtojnar** [comment]
I find it weird that anyone would use the union dictionary – after all, one would want a consistent style.

Maybe this should be reported at ibus-typing-booster issue tracker.

**Comment by jtojnar** [comment]
By the way, Arch uses moderne variant https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/hunspell-fr

**Comment by Ma27** [comment]
That's certainly good to know.

But I don't think that it makes sense if I join the discussion, I don't speak french or know anything about the language's variants or history. I'd like to hear what @symphorien says about this though, when you have agreed on a solution, I'd change the PR accordingly:)

**Comment by symphorien** [comment]
So the context is: There was a spelling reform in 1990. Both the new and old spelling of words are considered correct. Only the new spelling has been taught in schools for a few years I think, but the new spelling of some words still feels completely wrong to a lot of people. It is not really a question of style, I think. It is just a question of "I wrote this word the way I was taught and the spell checker tells me I am wrong". So if you write by the reform, your text won't spellcheck unless you use either reforme1990 or any, and a book published nowadays won't spellcheck unless you use either classique or any (according to https://dicollecte.org/documentation.php?prj=fr#dicos)


Anyway it makes little difference actually. The number of contentious words is quite small. So if arch linux uses moderne, moderne is fine :) Let's not waste time on this.

**Comment by Ma27** [comment]
First of all, thanks a lot for your detailed elaboration @symphorien!

I had a look at Debian, they ship `hunspell-fr` as "dependency package", so it can depends on *one* of the available variants and is satisfied if one is installed (https://packages.debian.org/buster/hunspell-fr). When I try to install `hunspell-fr` on a fresh Debian VM, I get the classical variant which is declared at first in the package definition (https://salsa.debian.org/debian/hunspell-fr/blob/master/debian/control).

It seems as other distros don't share consensus about this either, however I'd change my PR to use `moderne` for now if both of you agree:)

**Comment by Ma27** [comment]
To avoid having another stalled PR, is `moderne` as proposed previously a viable alternative for all of you?

**Comment by symphorien** [comment]
lgtm

**Comment by teto** [comment]
agreed

**Comment by Ma27** [comment]
updated the PR, would you mind having a look?

**Comment by Ma27** [comment]
@teto @jtojnar @symphorien anything else from your side? I rebased the patch onto the current master, unless there's anything to add it would be awesome to see this on master :)

**Comment by Ma27** [comment]
As #47153 has been merged, we can close this.
