### ISSUE TITLE
binutils: upgrade to 2.31.x

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#47128]
## Issue description

Now that we've branched off 18.09, it's probably a good time to update binutils. There are quite a few CVEs open against binutils-2.30, but I think we should try to patch 18.03 and 18.09 and update master.

### Steps 

* [x] update on master to 2.31
* [ ] patch nixos-18.09
* [ ] ~patch nixos-18.03~ (support ended)

There is already an attempt to patch binutils-2.30 in #41042.

**Comment by ckauhaus** [comment]
For open advisories, see #47122, #47121, #42882, #41748, #40765, and #38993

**Comment by ckauhaus** [comment]
Cc @Ericson2314

**Comment by domenkozar** [comment]
Status?

**Comment by ckauhaus** [comment]
The question is if someone is stil willing to work on a backport for 18.09. Master has been fixed AFAICS.

**Comment by ckauhaus** [comment]
18.09 is EOL
