### ISSUE TITLE
Can't set RTC to local

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixpkgs#47165]
## Issue description
Setting the Linux clock to local instead of UTC is a common workaround for dual booting systems with windows. The alternative, configuring windows to use UTC, is not very well supported, and many applications that simply assume the system clock is local will just not work.

See [this link](https://www.howtogeek.com/323390/how-to-fix-windows-and-linux-showing-different-times-when-dual-booting/) for a blog post outlining this.

Given that...
```
❯ timedatectl set-local-rtc 1 --adjust-system-clock
Failed to set local RTC: Changing system settings via systemd is not supported on NixOS.
```

... and there is no NixOS option for this, what would the best approach be?

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.8, NixOS, 19.03.git.4f32521 (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-19.03pre152634.218ce4de508"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
I'd put `time.hardwareClockInLocalTime = true;` into your `configuration.nix`.

**Comment by mkaito** [comment]
Heh, I saw the module for it, saw that `hardwareClockInLocalTime` wasn't used anywhere, `rg`d the nixpkgs tree, didn't see anything super evident, and I guess I was wrong. Thanks!
