### ISSUE TITLE
cups printing: Cannot print with HPLIP and ghostscript 9.24

### ISSUE THREAD

**Issue by woffs** [NixOS/nixpkgs#47193]
## Issue description

see https://bugs.ghostscript.com/show_bug.cgi?id=699713
"Mismatch of ICC profiles and device color model" in cups logfile and no printing

### Steps to reproduce

Install NixOS 18.09 with a HP Deskjet F2400 series printer and

    services.printing = {
      enable = true;
      drivers = [ pkgs.hplip ];
    };
    services.colord.enable = true;

and try to print something.

### Solution
Apply the patch:

    nixpkgs.config.packageOverrides = pkgs: {
      ghostscript = pkgs.ghostscript.overrideAttrs (old: {
        name = old.name + "-cups";
        patches = old.patches ++ [
          (pkgs.fetchpatch {
            name = "cups.patch";
            url = "http://git.ghostscript.com/?p=ghostpdl.git;a=patch;h=bc3df0773fcc";
            sha256="1wh3nrk0gqxlac2chqsymhiyrz9acqwcsdkcx22p34zxq98an68z";
          }
        )];
      });
    };

Just overriding ghostscript in hplip did not help, it seems that cups / hplip is using the system gs and not the gs from the buildInput, but replacing gs globally works.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 18.09beta78.6f3bd5db2f4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6377_954d1f4d`
 - channels(woffs): `""`
 - channels(root): `"nixos-18.09beta78.6f3bd5db2f4, nixos1803-18.03.133188.8b92a4e6004"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by woffs** [comment]
found https://github.com/eadwu/nixpkgs/commit/023862872509edeb3997bf56d024cba6337047b2 related to that.

**Comment by eadwu** [comment]
https://github.com/NixOS/nixpkgs/pull/46216 in case you want to use a local nixpkgs.
