### ISSUE TITLE
Unable to use the docker daemon

### ISSUE THREAD

**Issue by abhi18av** [NixOS/nixpkgs#47201]
## Issue description

Here' the output of the `docker pull` command

```
[root@emilynabhinav:~]# sudo docker pull postgres
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```

And the output of `systemd` command

```
[root@emilynabhinav:~]# sudo systemctl start docker
Failed to start docker.service: Unit docker.service not found.


```
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
[root@emilynabhinav:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.03.132610.49a6964a425 (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.133245.d16a7abceb7, nixpkgs-19.03pre153155.93408aecc4a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`



```

**Comment by srhb** [comment]
Is this with `virtualisation.docker.enable = true;` ?

**Comment by abhi18av** [comment]
Nope. Actually, I installed the docker package using the following command

`nix-env -iA nixpkgs.doker`

Do I need to change the configs in nixes as well to accommodate this ?

**Comment by srhb** [comment]
@abhi18av Yes, this is normal behaviour. In order to enable the docker daemon, you need to enable the aforementioned option. :) Feel free to get back to us if that causes you any issues. :)

**Comment by jackTaw88** [comment]
@abhi18av  abhi18av hi, where I will put this config? "virtualisation.docker.enable = true;" 

I use nix package manager on Ubuntu 18.

**Comment by ORESoftware** [comment]
for nixos newbs, would help to inform the newbs where to put `virtualisation.docker.enable = true;`

**Comment by piq9117** [comment]
@jackTaw88 @ORESoftware did yall figure out where to put it?

**Comment by ThoenigAdrian** [comment]
@piq9117 @ORESoftware @jackTaw88  It's in **/etc/nixos/configuration.nix** . It's in the outermost layer for example you can just place it below: 

`services.xserver.enable = true
virtualisation.docker.enable = true;`

**Comment by piq9117** [comment]
Thanks! :tada:

**Comment by karthikiyengar** [comment]
Would it be possible to run the daemon on non NixOS systems?

**Comment by srhb** [comment]
@karthikiyengar I don't know of any problem running the nix-packaged docker daemon on a non-NixOS system, but you will end up configuring it in a very different way, because the nixified configuration options mentioned above are specific to the NixOS module system.

**Comment by wadewilliams** [comment]
Any hints as to what "configuring it in a very different way" would look like on a non-NixOS system???

**Comment by rounakdatta** [comment]
I'd love to run docker in rootless mode. I find that the docker systemctl service isn't enabled (after following the official steps), am I missing anything?

**Comment by justinTM** [comment]
```console
$ devbox add docker
Info: Package "docker@latest" already in devbox.json
✓ Computed the Devbox environment.
Info: Package "docker@latest" was already in devbox.json and was not modified
```

```console
$ docker build .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

hmm...

**Comment by alxthm** [comment]
I was able to run docker with nixpkgs on macOS by using [colima](https://github.com/abiosoft/colima) for the docker runtime (instead of the one provided by Docker Desktop). It is available in nixpkgs:

```
$ nix shell nixpkgs#colima nixpkgs#docker
$ colima start
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] creating and starting ...                     context=vm
> 405.01 MiB / 405.01 MiB (100.00%) 30.24 MiB/stime="2024-04-06T20:12:31+02:00" level=info msg="Downloaded the image from \"https://github.com/abiosoft/colima-core/releases/download/v0.6.8-2/ubuntu-23.10-minimal-cloudimg-arm64.qcow2\""
INFO[0177] provisioning ...                              context=docker
INFO[0177] starting ...                                  context=docker
INFO[0177] done
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by raphaklaus** [comment]
I ended up installing Colima as the Docker engine and it worked flawlessly. My config looks like:

```
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    # Docker
    colima
    docker
    docker-compose
  ];
}
```

And then I start the Colime service like: `colima start` and then use `docker` normally. :)
