### ISSUE TITLE
Adobe Blank selected over sensible fallback fonts

### ISSUE THREAD

**Issue by tkerber** [NixOS/nixpkgs#47213]
## Issue description

Adobe Blank appears to be prioritised over some fonts by default. Having a blank font be selected over fallback fonts leads to glyphs not rendering unexpectedly.

### Steps to reproduce

Install `google-fonts` and `noto-fonts-cjk`. For instance, the character `傻` will not render, as Adobe Blank is selected for it.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.9, NixOS, 19.03pre153134.e372ab46265 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.2`
 - channels(root): `"nixos-19.03pre153134.e372ab46265, nixos-stable-18.03.133245.d16a7abceb7"`
 - channels(tk): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tkerber** [comment]
This is definitely an issue with pango (tested with `pango-view`, `firefox`, and `ibus`). Honestly, I don't know much about font architecture, but it was my impression that the actual selection of the font was managed by fontconfig and doesn't differ by platform. I also experienced the issue in `kitty`, for example, which uses `fontconfig` and `harfbuzz` directly afaik.

**Comment by binarin** [comment]
That same funny font was making Emacs extremely slow - https://github.com/NixOS/nixpkgs/issues/101813#issuecomment-726183422

**Comment by tkerber** [comment]
I believe adobe-blank has been removed from google-fonts, so I'm closing this.
