### ISSUE TITLE
haskellPackages.conduit-extra broken on master

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#47218]
## Issue description

One test case fails in latest hydra eval on master (d9f7d27ef54): https://hydra.nixos.org/build/81861609
This breaks many other Haskell packages.

Failure looks non-deterministic, builds fine (in a sandbox) on my local x86_64-linux system, same nixpkgs revision.

**Comment by srhb** [comment]
That is bizarre. The test literally runs cat on `Changelog.md` and the failure looks as though cat received SIGTERM while running.

**Comment by xeji** [comment]
Maybe just a transient problem on the builder. Can you restart the job on Hydra?

**Comment by srhb** [comment]
I don't have the necessary access, but I'll try to poke some people that do and get back here.

**Comment by srhb** [comment]
It has been restarted. And yes, I can't really think of any other reason than transient builder issue. We'll see...

**Comment by xeji** [comment]
Restart was successful, so let's call it a transient builder issue. Thanks @srhb !

**Comment by cprussin** [comment]
I'm not convinced this is truly resolved @xeji and @srhb -- this exact failure was reported to me via https://github.com/cprussin/nixjs/issues/3 so I'm thinking this transient builder issue is somehow happening for some cases.  Also from https://github.com/snoyberg/conduit/issues/385 it seems others are starting to get more consistent failures, so I'm thinking nixpkgs might start seeing this issue again when the package needs to be rebuilt.  Would there be any way to disable the test in the package in nixpkgs or something similar?

**Comment by peti** [comment]
> Maybe just a transient problem on the builder.

Other people have [observed the same issue when compiling with `stack`](https://github.com/snoyberg/conduit/issues/385#issuecomment-450348192), so the failure is probably not specific to Nix. The problem has been reported in https://github.com/snoyberg/conduit/issues/385 a long time ago, but no fix has materialized yet.
