### ISSUE TITLE
nixos-rebuild does not install the lastes version of a package 

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#47215]
## Issue description

When I updated the system with `nixos-rebuild switch --update` plasmashell crashed on startup until I reinstalled it with `sudo nix-env -i plasma-workspace`,and the same with powerdevil.
Said commands updated the above programs from 5.13.0 to 5.13.5

### Steps to reproduce

1. Update to the lastest version with `sudo nixos-rebuild switch --upgrade`
2. Restart `plasmashell` and see it crash because of the usual qt versioning hell
3. Run `sudo nix-env -i plasma-workspace` and see it update from 5.13.0 to 5.13.5
4. Restart `plasmashell` without any problems

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 19.03pre153158.7df10f388da (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6377_954d1f4d`
 - channels(root): `"nixpkgs-19.03pre153158.7df10f388da"`
 - channels(pasquale): `"nixpkgs-19.03pre153158.7df10f388da"`
 - nixpkgs: `/home/pasquale/.nix-defexpr/channels/nixpkgs`

**Comment by vcunat** [comment]
The nixpkgs version in your "technical details" only contain one version - 5.13.5, so that will be installed unless you've done some hacks.  Possible problems I can anticipate:
1. you had also an older version installed via `nix-env`, or
2. we still have some qt/plasma plugin-like problems where absolute paths get cached by the packages.

**Comment by pasqui23** [comment]
```
sudo nix-env -q           
plasma-browser-integration-5.13.5
plasma-workspace-5.13.5
powerdevil-5.13.5
```

**Comment by vcunat** [comment]
Oh, you wrote
> Run sudo nix-env -i plasma-workspace and see it update from 5.13.0 to 5.13.5

If it printed something like that, you had 5.13.0 installed by `sudo nix-env -i` &ndash; otherwise it wouldn't mention 5.13.0 at all.

**Comment by pasqui23** [comment]
No,all my programs were installed via `configure.nix`.I discovered `nix-env` would install the correct version by accident

**Comment by Ekleog** [comment]
(triage) @pasqui23 What version of `plasmashell` do you end up if you uninstall it from `nix-env` with something like `nix-env -e plasma-workspace`?

**Comment by aanderse** [comment]
@pasqui23 any interest in further pursuing this issue?

**Comment by vcunat** [comment]
Well, reopen in that case.  As it is now, I can't see anything actionable.
