### ISSUE TITLE
Add option to automatically update the nix search cache

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#47225]
## Feature request

It would be cool to have an option nixSearch.auoUpdate which enables a service running nix search -u [...] on a regular basis. On a related note, nix search might profit from an option, which ONLY updates the cache (instead of searching).

**Comment by matthewbauer** [comment]
Yes definitely would be useful.

You really only need to update it when you run ```nix-channel --update```. I wonder if nix-channel could be made to run ```nix search -u``` automatically. Even better, just include the .json cache file in the channel tarball.

**Comment by xaverdh** [comment]
> Even better, just include the .json cache file in the channel tarball

Yes that sounds like the best approach to me. Should I open an issue against the nix repository?

**Comment by FRidh** [comment]
> Even better, just include the .json cache file in the channel tarball

Would that not assume one uses only a single channel?

**Comment by xaverdh** [comment]
This will be fixed by flakes I think?

**Comment by matthewbauer** [comment]
Yes - https://github.com/NixOS/nix/commit/b69323f8c93d5b067b6baaa0acbb93f800fcd9bd#diff-bb2710714072c32dc855c57c6661ced3 make it update anytime the Nixpkgs flake changes

**Comment by xaverdh** [comment]
Thanks for clarifying this @matthewbauer, will close this issue then.
