### ISSUE TITLE
Firefox extension that uses native messaging does not work

### ISSUE THREAD

**Issue by mickours** [NixOS/nixpkgs#47340]
I tried for a long time now to make browserpass and gnome-extensions firefox plugins to work in NixOS without success. I find out that these two extensions are using the Native Messaging interface, that is used by Firefox to interact with local applications. So, looking at the Firefox debug console, I get this error:

```
No such native application com.dannyvankooten.browserpass
```
It seems that the extension manifest was not found.

I finally find out where it comes from, thanks to this issue #33748. This comment is giving the problem cause and the workaround:
https://github.com/NixOS/nixpkgs/issues/33748#issuecomment-356978749

Basically, the problem comes from Firefox looking for a path in `/usr/lib/` that does not exist in NixOS and the workaround is to create a link in the user's home with:
```
mkdir ~/.mozilla/native-messaging-hosts/
ln -s $(nix-build '<nixpkgs>' -A chrome-gnome-shell)/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json ~/.mozilla/native-messaging-hosts/
ln -s $(nix-build '<nixpkgs>' -A browserpass)/lib/mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json ~/.mozilla/native-messaging-hosts/
```

A [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1318461) was open in the Firefox side two years ago, but maybe a small patch would do the trick ;)

I'm opening a new issue because the previous one was too specific on browserpass and closed because of another issue with gpg that was fixed.

**Comment by jtojnar** [comment]
You can add something like `nixpkgs.config.firefox.enableBrowserpass = true;` and  nixpkgs.config.firefox.enableGnomeExtensions = true; to your `configuration.nix`. You can even add arbitrary nmh packages by installing `(pkgs.firefox.override { extraNativeMessagingHosts = [ pkgs.gnomeExtensions.gsconnect ]; })`.

**Comment by mickours** [comment]
Sorry if I wasn't clear but this is the problem actually, both options were already set:
```
nixpkgs.config.firefox.enableBrowserpass = true; 
nixpkgs.config.firefox.enableGnomeExtensions = true; 
```
But the extensions were not working and Firefox was still complaining that it can't find the extensions with errors like:
```
No such native application com.dannyvankooten.browserpass
```

**Comment by hedning** [comment]
Just to be sure, are you using `firefox-bin`? That's the upstream build from mozilla and isn't patched to detect the nixpkgs config.

**Comment by mickours** [comment]
> Just to be sure, are you using `firefox-bin`? That's the upstream build from mozilla and isn't patched to detect the nixpkgs config.

I'm using the `firefox` package that contains the `nix-support` folder:
```sh
$ realpath $(which firefox)
/nix/store/3d10spgq6fc573ih4wpgjqn7x2iyr8b3-firefox-62.0/bin/firefox
$ l /nix/store/3d10spgq6fc573ih4wpgjqn7x2iyr8b3-firefox-62.0
total 16
dr-xr-xr-x 2 root root 4096  1 janv.  1970 bin
dr-xr-xr-x 3 root root 4096  1 janv.  1970 lib
dr-xr-xr-x 2 root root 4096  1 janv.  1970 nix-support
dr-xr-xr-x 4 root root 4096  1 janv.  1970 share
```

**Comment by coreyoconnor** [comment]
See also https://unix.stackexchange.com/questions/437248

I've done some tracing on this: Firefox is not looking in `MOZ_SYSTEM_DIR` for native messaging hosts. I suspect there was a change related to policies that disabled this.

Documentation is sparse on all fronts. I haven't determined what the correct directory should be. One reference said use `share` instead of `lib`. That did not work for me.

A temp workaround that did resolve the issue was to copy the manifest jsons under `~/.mozilla/native-messaging-hosts`.

**Comment by coreyoconnor** [comment]
Nice! Thanks for the tip.

The post-update issue, in my case, was observed as a "error" reported on accessing https://extensions.gnome.org/ .

**Comment by glasserc** [comment]
I decided to open https://bugzilla.mozilla.org/show_bug.cgi?id=1538954 to surface this discussion within Mozilla because the patch shipped in Nixpkgs only covers the `firefox` derivation (users of `firefox-bin` are left out in the cold).

**Comment by Infinisil** [comment]
Oh btw, I added better instructions to browserpass for Nix/NixOS recently, in https://github.com/browserpass/browserpass/pull/308: https://github.com/browserpass/browserpass#configuring-browserpass-on-nixos--for-nix

**Comment by worldofpeace** [comment]
This came up when I was helping someone on mastodon https://mastodon.social/web/statuses/103631567654364956.
We need to get some sort of warning or information about firefox vs firefox-bin, and in particular that the native messaging stuff doesn't work as expected.

**Comment by wakest** [comment]
thanks @worldofpeace for walking me through that. I was very confused why it wasn't working and had not even thought about checking with a different install of firefox. using the non bin version it now works as expected.

**Comment by eddyb** [comment]
So I have `firefox` (*not* `firefox-bin`, so this is unrelated to any of that discussion above) from `nix-env` (I've been meaning to switch to `home-manager` on this machine too, just didn't get around it) and I was a bit confused regarding the Plasma integration addon.

This seems to have done the job though, so [the note on the wiki](https://nixos.wiki/wiki/Firefox#nativeMessagingHosts_don.27t_work) seems incorrect:
```console
$ ls -l $(dirname $(readlink $(which firefox)))/../lib/mozilla/native-messaging-hosts/
total 0

$ nano ~/.nixpkgs/config.nix 

$ cat ~/.nixpkgs/config.nix
{
  firefox.enablePlasmaBrowserIntegration = true;

  # ... the rest of my `config.nix` file ...
}

$ nix-env -iA nixos.firefox
replacing old 'firefox-103.0.2'
installing 'firefox-103.0.2'
this path will be fetched (0.57 MiB download, 4.82 MiB unpacked):
  /nix/store/6c79h7gb5gvgpd4938yxg2zdffbd3h2j-firefox-103.0.2
copying path '/nix/store/6c79h7gb5gvgpd4938yxg2zdffbd3h2j-firefox-103.0.2' from 'https://cache.nixos.org'...
building '/nix/store/bqgyzgm7xpn5pgd9rnx3w7xrxw0m46ip-user-environment.drv'...

$ ls -l $(dirname $(readlink $(which firefox)))/../lib/mozilla/native-messaging-hosts/
total 9
lrwxrwxrwx 1 root root 152 Jan  1  1970 org.kde.plasma.browser_integration.json -> /nix/store/s718ag183gd8chm757gzy49i1wdh306p-plasma-browser-integration-5.25.4/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json
```

So it seems like `~/.nixpkgs/config.nix` plays *all* the roles of `nixpkgs.config` but for per-user `nix-env` - which makes perfect sense, but I wasn't sure until I tried. I assume that it would be easier to just add `firefox` to my system-wide packages (since then e.g. `enablePlasmaBrowserIntegration` is already automatically set).

Now to restart Firefox and see if it *really* works!

**Comment by huantianad** [comment]
Is `enablePlasmaBrowserIntegration` expected to work with`librewolf`?

**Comment by pasqui23** [comment]
> Is `enablePlasmaBrowserIntegration` expected to work with`librewolf`?

Yes, it should just be `config.librewolf.enablePlasmaBrowserIntegration=true` if it weren't for this bug.

**Comment by huantianad** [comment]
I managed to get it working on `librewolf` by overriding the package instead of using the config option, see #233568

**Comment by SuperSandro2000** [comment]
I think this commit https://github.com/SuperSandro2000/nixpkgs/commit/cb6a879f145aa8361c959f3d93bf07b5da3b6e53 fixes this. Can someone confirm this?

**Comment by SuperSandro2000** [comment]
@K900 @mweinelt what do you think about this?

I think this might be only necessary for users of firefox-bin thought.

**Comment by mickours** [comment]
FYI the workaround described [here](https://github.com/NixOS/nixpkgs/issues/47340#issuecomment-440645870) was not necessary in anymore in 23.05 but after updating to 23.11 browserpass seems to be broken again.
The debug console of the extension shows:
```
Error: No such native application com.github.browserpass.native
```
So I've re-enabled the workaround but the native extension name has changed. The new version is:
```nix
home.file.".mozilla/native-messaging-hosts/com.github.browserpass.native.json".source = "${pkgs.browserpass}/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json";
```

**Comment by SuperSandro2000** [comment]
Please test #303562

**Comment by mickours** [comment]
Sorry. I just tried, and the problem is still there even after restarting firefox. Same error:
```
Error: No such native application com.github.browserpass.native
```
I do have in my config:
```
programs.browserpass.enable = true;
programs.firefox.enable = true;
```

**Comment by honza** [comment]
> FYI the workaround described [here](https://github.com/NixOS/nixpkgs/issues/47340#issuecomment-440645870) was not necessary in anymore in 23.05 but after updating to 23.11 browserpass seems to be broken again. The debug console of the extension shows:
> 
> ```
> Error: No such native application com.github.browserpass.native
> ```
> 
> So I've re-enabled the workaround but the native extension name has changed. The new version is:
> 
> ```nix
> home.file.".mozilla/native-messaging-hosts/com.github.browserpass.native.json".source = "${pkgs.browserpass}/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json";
> ```

This works for me.
