### ISSUE TITLE
anyone know best practice for installing tmux plugins

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nixpkgs#47379]
I see there are a bunch of tmux plugins in the nix store, but I cannot seem to figure out how to get tmux to actually use them. What's the best way to configure the tmux plugins from the nix store in my configuration.nix file?

**Comment by mschonfinkel** [comment]
@nrdxp Did you manage to install the plugins? I'm also trying to find out btw.

**Comment by matthiasbeyer** [comment]
Same here. What's your solution to this problem?

**Comment by matthiasbeyer** [comment]
@mschonfinkel see https://github.com/NixOS/nixpkgs/pull/36790
