### ISSUE TITLE
Haskell project with freeglut gives error

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#47415]
## Issue description

When building a haskell project with stack and nix integration that depends on mesa and freeglut, it throws an error.

### Steps to reproduce

For example, this package uses `libGL`, `libGLU` and `freeglut`:
```
$ git clone https://www.github.com/turion/rhine
$ cd rhine/
$ cd rhine-gloss/
$ stack build
$ stack exec rhine-gloss-gears 
freeglut (rhine-gloss-gears):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
```
This used to work, until mesa was renamed to `libGL`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.69, NixOS, 19.03pre152634.218ce4de508 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(turion): `""`
 - channels(root): `"nixos-19.03pre152634.218ce4de508"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by turion** [comment]
For a MWE, consider the following:

Make sure you have cabal and stack installed. Then follow these commands:

    $ mkdir tempgloss
    $ cd tempgloss

Create two files with these contents:


    $ cat Main.hs 
    import Graphics.Gloss
    main = display (InWindow "Nice Window" (200, 200) (10, 10)) white (Circle 80)
    
    $ cat stack.yaml 
    resolver: lts-12.10
    nix:
      enable: true
      packages: [libGL libGLU freeglut]


Now execute:

    $ cabal init --is-executable -n --main-is=Main.hs -d gloss -d base -l MIT
    [...]
    $ stack build
    [...]
    $ stack exec tempgloss

**Comment by srhb** [comment]
fwiw, following your (excellent) MWE instructions and invoking `cabal2nix . --shell > shell.nix && $(nix-build shell.nix)/bin/tempgloss` works.

Looking at the ldd output from both executables, it appears that the stack-built executable is linked against fewer libraries, for instance, this is missing: `libglut.so.3 => /nix/store/3s4js4zvhv2cch75lkclhf3xnpa7j0h5-freeglut-3.0.0/lib/libglut.so.3 (0x00007f7d0c817000)`

Which seems a bit odd...

**Comment by turion** [comment]
Ah! That sounds a lot like `stack` is doing something wrong! Maybe I'll close here and reopen as a stack issue?

**Comment by qrilka** [comment]
I'm not sure that `stack` has anything to do with this issue (more or less all it does is invoking a `nix-shell` with some options), I don't no the details of OpenGL setup but I think this error is probably related:
```
$ nix-shell -p glxinfo --run glxinfo
name of display: :0.0
Error: couldn't find RGB GLX visual or fbconfig
```
I get this on non-NixOS distro (Gentoo in this case), while on NixOs I get a proper output from `glxinfo`

**Comment by srhb** [comment]
@qrilka That's related to the impurity of graphics drivers. I don't think it's related to this issue at all.

**Comment by vcunat** [comment]
That will probably work only if the OS is running on mesa drivers.  The point of libGL impurity is that the libGL implementation depends on the currently loaded in-kernel GPU code.

**Comment by srhb** [comment]
Yeah. I wonder why the libGL approach doesn't seem to link right.

**Comment by vcunat** [comment]
I'd hope this would also work with `pkgs.libGL` (i.e. the glvnd-provided stubs).

**Comment by srhb** [comment]
@vcunat It does not, that's what the issue is about. :)

**Comment by vcunat** [comment]
Ah, right :face_with_head_bandage:

**Comment by turion** [comment]
@srhb: You're my NixOS heroine now! Thanks!

**Comment by srhb** [comment]
Note that I still feel this is a wrong solution though. It really should work with LibGL! I just haven't figured out why it doesn't. :)

**Comment by turion** [comment]
Yes, it's the best workaround so far though

**Comment by turion** [comment]
@masaeedu Since cabal AFAIK hasn't got an explicit nix integration, you would have to add the nix dependencies yourself. They are needed for static or dynamic linking. So without stack, @srhb's approach with this command is the closest: `cabal2nix . --shell > shell.nix && $(nix-build shell.nix)/bin/tempgloss`

**Comment by masaeedu** [comment]
@turboMaCk Thanks. I'm already using `cabal2nix` (indirectly, via `callCabal2Nix` invoked by the `developPackage` thing in nixpkgs). But where would I make the adjustment analogous to the one suggested for the `packages` field (given that I don't have a `stack.yaml` file at all)?

**Comment by turboMaCk** [comment]
you probably wanted to thank to @turion not me @masaeedu.

**Comment by turion** [comment]
@masaeedu, two answers.

First of all, `cabal2nix` will generate a nix expression where your cabal project depends on _other Haskell packages_. If only these dependencies need external libraries, you don't need anything to do, because `nix` takes care of that already.

If you want to know how to depend on external libraries _in your own project_, just have a look at what `cabal2nix` does to a package with external library dependencies:

```
$ cabal unpack OpenGLRaw
Downloading  OpenGLRaw-3.3.3.0
Downloaded   OpenGLRaw-3.3.3.0
Unpacking to OpenGLRaw-3.3.3.0/
$ cd OpenGLRaw-*
$ cabal2nix .
{ mkDerivation, base, bytestring, containers, fixed, half, libGL
, stdenv, text, transformers
}:
mkDerivation {
  pname = "OpenGLRaw";
  version = "3.3.3.0";
  src = ./.;
  libraryHaskellDepends = [
    base bytestring containers fixed half text transformers
  ];
  librarySystemDepends = [ libGL ];
  homepage = "http://www.haskell.org/haskellwiki/Opengl";
  description = "A raw binding for the OpenGL graphics system";
  license = stdenv.lib.licenses.bsd3;
}
```
The relevant list you're looking for is `librarySystemDepends`.

**Comment by turion** [comment]
For me the `cabal` approach is now my preferred solution. I don't use `stack` anymore. If this is still a problem for someone, feel free to reopen and describe what doesn't work for you.

**Comment by mpardalos** [comment]
I am getting the same issue just using cabal and the derivation from cabal2nix.

Main.hs
<details>

```hs
import Graphics.Gloss
main = display (InWindow "Nice Window" (200, 200) (10, 10)) white (Circle 80)
```

</details>

nix-gloss-minimal.cabal
<details>

```cabal
cabal-version:      2.4
name:               nix-gloss-minimal
version:            0.1.0.0
author:             Michalis Pardalos
maintainer:         m.pardalos@gmail.com

executable nix-gloss-minimal
    main-is:          Main.hs
    build-depends:    
        base >= 4.7 && < 5,
        gloss == 1.13.*
    default-language: Haskell2010
```

</details>

Then run

```sh
cabal2nix . --shell > shell.nix
nix-shell
cabal new-run
```

Gives the error

```
freeglut (nix-gloss-minimal):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
```

**Comment by turion** [comment]
@mpardalos It works on my machine. Can you give more details on your setup? I.e. do you use NixOS or not, do you have GHC, cabal, gloss installed globally? Which channel do you use?
