### ISSUE TITLE
nixos-unstable advanced despite timeouts in tested

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#47419]
## Issue description
https://hydra.nixos.org/build/82148855#tabs-constituents
https://hydra.nixos.org/job/nixos/trunk-combined/tested/latest-finished

I don't see a good reason for this behaviour, and it appears that channels can potentially bump despite massive timeouts, which could mask failures. This appears to be critical.

Of note:

- There are no non-timeout failures. I believe this might be the culprit.
- All the timeouts happened on packet-t2-4

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by xeji** [comment]
I've noticed that sometimes Hydra shows jobs as timed out even after the same package was successfully built as a dependency of another job. Could that be related?

**Comment by srhb** [comment]
@xeji I don't *think* so in this case, due to the nature of the tested job?

**Comment by srhb** [comment]
Also thanks @etu for the heads-up.

**Comment by xeji** [comment]
All build steps show all as succededed: https://hydra.nixos.org/build/82148855#tabs-buildsteps

**Comment by srhb** [comment]
I guess we can check every out path to confirm that it's a false negative.

**Comment by srhb** [comment]
Checking the out-path of the tested aggregate:

`nix path-info /nix/store/qyvy2six4gb2r275g25whfgdzf2wf2fk-nixos-19.03pre153673.a70d3bab72d --store https://cache.nixos.org`

is a positive match, so the failures appear to be false negatives at least.

**Comment by xeji** [comment]
Looks like a Hydra bug.

**Comment by srhb** [comment]
I'll refile it later then.

**Comment by edolstra** [comment]
I assume somebody restarted the `tested` job without restarting the constituents. The fact that the former succeeded implies that all its dependencies succeeded as well.

**Comment by srhb** [comment]
Thank you for that explanation @edolstra
