### ISSUE TITLE
stack: Version is out of date (unsupported)

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#47423]
## Issue description

The supported stack version is 1.9, but nixpkgs still has version 1.7.

### Steps to reproduce

```
$ nix-shell -p stack --run "stack --version"
Version 1.7.1 x86_64
Compiled with:
[...]

Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.69, NixOS, 19.03pre153158.7df10f388da (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.2`
 - channels(turion): `""`
 - channels(root): `"nixos-19.03pre153158.7df10f388da"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by domenkozar** [comment]
https://hackage.haskell.org/package/stack still only lists 1.7.1?

**Comment by turion** [comment]
Whooops, maybe I've been fooled by github? If you open a new github issue for stack, it says that the current version is 1.9.1! But indeed, you're right, even the install script just installs 1.7.1.

**Comment by Ptival** [comment]
Stack 1.9.1 has now been released! I might work on an update if it's not more than a couple minutes of work, otherwise, I'll let someone skilled do it.
