### ISSUE TITLE
Shotcut does not find LADSPA plugins

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#47440]
## Issue description

Shotcut in theory supports LADSPA plugins. However, LADSPA plugins are not found by Shotcut on NixOS version

### Steps to reproduce

- Install a bunch of LADSPA plugins (by listing them in `systemPackages`)
- Open Shotcut
- Add effects to a track
- Look for audio effects: no LADSPA plugins are shown

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 18.03.133245.d16a7abceb7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03, nixos-unstable-19.03pre153158.7df10f388da"`
 - channels(raskolnikov): `"nixos-18.03.133029.d0c868ec17c, nixos-unstable, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by xeji** [comment]
cc maintainers @woffs @goibhniu.

**Comment by woffs** [comment]
found out why: configure is using `which`, which is not available, and therefore does disable ladspa. Preparing a PR.
