### ISSUE TITLE
how to build nix package with stack for running on other linux?

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#47454]
i use stack with nix enable to build an binary.
but  i  can't copy it to run on other platform.
so can you offer me an example to build nix-package with stack?

```
mkdir -p bin && stack install --local-bin-path bin
```

**Comment by emmanuelrosa** [comment]
Why can't you copy the binary? I believe the default stack configuration produces static binaries.

**Comment by clojurians-org** [comment]
the interpreter library and dependency library has different path between 
nixos => /nix/store/hwwqshlmazzjzj7yhrkyjydxamvvkfd3-glibc-2.26-131/lib/ld-linux-x86-64.so.2
and other linux(/lib64/ld-linux-x86-64.so.2)

i'm trying stack2nix to resolve it

**Comment by emmanuelrosa** [comment]
Oh, I see. You might be able to use `patchelf` to fix that.

**Comment by clojurians-org** [comment]
i have the haskell project source code. so i will use stack2nix.
patchelf have some bug always for rare case, i prefer build way.

**Comment by clojurians-org** [comment]
https://github.com/NixOS/cabal2nix
offical cabal2nix seems a good solution.

but some error happen：
```
[larluo@larluo-nixos:~/my-repo/HelloWorld]$ cat default.nix 
{ mkDerivation, aeson, base, bytestring, stdenv }:
mkDerivation {
  pname = "HelloWorld";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ aeson base bytestring ];
  executableHaskellDepends = [ base ];
  testHaskellDepends = [ base ];
  homepage = "https://github.com/githubuser/HelloWorld#readme";
  license = stdenv.lib.licenses.bsd3;
}


[larluo@larluo-nixos:~/my-repo/HelloWorld]$ nix-build -E "with import <nixos-unstable> {}; callPackage ./default.nix {}"
error: anonymous function at /home/larluo/my-repo/HelloWorld/default.nix:1:1 called without required argument 'mkDerivation', at /nix/store/jxh66xw69rwpmx9bakgq3h2i0wm8rxic-nixos-unstable/nixos-unstable/lib/customisation.nix:69:12
```

**Comment by clojurians-org** [comment]
resolved!
nix-build -E "with import <nixos-unstable> {}; pkgs.haskell.packages.ghc843.callPackage ./default.nix {}"
