### ISSUE TITLE
sshd does not start when listenAddresses is set to an bridge interface

### ISSUE THREAD

**Issue by robberer** [NixOS/nixpkgs#4748]
This applies only at boot because sshd is startet before the bridge interfaces are ready.

```
sshd[1822]: error: Bind to port 64022 on 1.1.1.1 failed: Cannot assign requested address.
sshd[1822]: error: Bind to port 22 on 192.168.77.222 failed: Cannot assign requested address.
sshd[1822]: fatal: Cannot bind any address.
systemd[1]: sshd.service never wrote its PID file. Failing.
systemd[1]: Failed to start SSH Daemon.
systemd[1]: Unit sshd.service entered failed state.
systemd[1]: Started X11 Server.
kernel: Bridge firewalling registered
systemd[1]: Found device /sys/subsystem/net/devices/br1.
systemd[1]: Starting Configuration of br1...
kernel: device eth0 entered promiscuous mode
kernel: device eth1 entered promiscuous mode
systemd[1]: Found device /sys/subsystem/net/devices/br0.
systemd[1]: Starting Configuration of br0...
br1-cfg-start[1847]: bringing up interface...
br0-cfg-start[1848]: bringing up interface...
```

**Comment by Profpatsch** [comment]
(triage) @lethalman What’s the status?

**Comment by qknight** [comment]
closing since inactive. @robberer please reopen if still interested.

**Comment by gspia** [comment]
I'm not sure if this same problem as #4748 but without listenAddresses in configuration.nix sshd status is ok and with listenAddresses with the proposed systemd-setting above nor without is it not working (on 17.03):

 > systemctl status sshd

The message:

>   ● sshd.service - SSH Daemon
>        Loaded: loaded (/nix/store/23ww1a7j0g98ym1896y4drcfn63gdynd-unit-sshd.service/sshd.service; enabled; vendor preset: enabled)
>        Active: failed (Result: exit-code) since Fri 2017-08-18 14:49:40 EEST; 1s ago
>       Process: 6677 ExecStart=/nix/store/vmisgqfbqywgsw9php70bbx90czr398i-openssh-7.4p1/bin/sshd -f /nix/store/lngl452hr12niq1gzjgjkgmi0c19xmdr-sshd_config (code=exited, status=255)
>      Process: 6673 ExecStartPre=/nix/store/39j4ry5wr9ppy0bi4x48qlr75v5vc6fz-unit-script/bin/sshd-pre-start (code=exited, status=0/SUCCESS)
>      Main PID: 6677 (code=exited, status=255)
 
and after that it says that "unit entered failed state" & "failed to start SSH daemon".
