### ISSUE TITLE
Request: fractal

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#47486]
Think it's new with 3.30 or so, hopefully nothing special ... well, for those familiar with gnome packaging anyway :).

Matrix client, linky: https://gitlab.gnome.org/World/fractal

cc @jtojnar who possibly already packaged it as part of awesome gnome update endeavors.

**Comment by dtzWill** [comment]
Well looking at release tags it sure doesn't seem new to 3.30 haha not sure where I got that from!

**Comment by yegortimoshenko** [comment]
I haven't used Fractal in a while because it doesn't support end-to-end encryption just yet, and that package is something to be improved upon as it deals with deps very poorly (builds them all in one go).

**Comment by yegortimoshenko** [comment]
Would like to start using Fractal again so assigning to myself.

**Comment by dtzWill** [comment]
https://github.com/dtzWill/nixpkgs/tree/experimental/fractal

Builds on a somewhat messy development branch but just the top ~4 commits are fractal-only and should be usable on something close to master.  You'll need libhandy at perhaps other things, I'm using bits from #45950 (not sure if I'm using latest iteration).

On that, while I'm pinging that PR: libhandy 0.0.4 is out in case that's useful.

Also you can "try" fractal if you'd like, store path is "/nix/store/265gxxz6ky8kcwi13xa2c72bvcc1vcdm-fractal-3.30.0-git" and should be available on https://allvm.cachix.org .

**Comment by jtojnar** [comment]
Hmm, I like “nullining the phases trick”, I will use it in Podcasts app added in the 3.30 PR.

Not sure what gladeui are you referring to, the PR already has libhandy 0.0.4.

**Comment by jtojnar** [comment]
Never mind, I was waiting for hydra to build the prerequisites and then forgot to test-build the upgraded library. `gladeui-2.0` dependency (from `gnome3.glade`) is required by the glade catalog. The catalog consists of XML description and a library that provides the widgets to Glade. Since we do not want to include Glade into libhandy’s closure and splitting the catalog files into a separate output would be difficult, let’s disable the catalogue for now. Will commit a fix soon.

**Comment by dtzWill** [comment]
On Thu, 01 Nov 2018 07:57:41 -0700, Jan Tojnar <notifications@github.com> wrote:
> Hmm, I like “nullining the phases trick”, I will use it in Podcasts app added in the 3.30 PR.

Excellent! Yeah I'm glad it worked as well as it did.
If it becomes more popular/useful it may be worthwhile for rust bits
to more directly support this with a flag or function or some such.


> 
> Not sure what gladeui are you referring to, the PR already has libhandy 0.0.4.

Not sure, that's what it complained about being unable to find when I
tried it.  But clearly I'm behind the latest work on the PR so probably
better to sync with that instead of investigating w/e my problem was :).

**Comment by jtojnar** [comment]
I pushed the fix to the branch, see 1c173700e55
