### ISSUE TITLE
nixos/syncthing: bad default settings (perms 700 on home)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#47513]
## Issue description
The NixOS syncthing service with default settings sets ```-home=$HOME``` (where $HOME is /var/lib/syncthing) and with that breaks upstream assumption: https://github.com/syncthing/syncthing/issues/3434#issuecomment-235401876.

The result is that you cannot run syncthing with (nixos) default settings and give access to various users with ACLs, as syncthing will set perms 700 on the directory passed in ```-home=``` each time it starts. And as ```-home=``` is the same as ```$HOME```, your default shared folders are now hidden behind 700 perms.

Workaround (hack):
```
  # Undo the 700 perms syncthing sets on /var/lib/syncthing on startup. Without
  # this the ACL entries stop working.
  # See https://github.com/syncthing/syncthing/issues/3434.
  systemd.services.syncthing.postStart = lib.mkForce ''
    sleep 10
    chmod g+rx "${config.services.syncthing.dataDir}"
  '';
```

Based on https://github.com/syncthing/syncthing/issues/3434#issuecomment-235401876, the fix seems to be simply setting ```-home=$HOME/.config/syncthing``` instead of ```-home=$HOME```.

### Steps to reproduce
1. Add ```services.syncthing.enable = true;``` and ```sudo nixos-rebuild switch```
2. Add ACL: ```sudo setfacl -m u:$USER:rx /var/lib/syncthing```
3. Check that your user has access: ```ls -l /var/lib/syncthing```
4. Restart syncthing: ```sudo systemctl restart syncthing```
5. You no longer have access to the share:
```
ls -l /var/lib/syncthing
ls: cannot open directory '/var/lib/syncthing/': Permission denied
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.70, NixOS, 18.03.133231.01f5e794913 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133231.01f5e794913"`
 - channels(bfo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
The fix is easy but it will break all existing setups. We could add a `if versionAtLeast config.system.stateVersion "18.09"`.
