### ISSUE TITLE
Question: why does /var/log/messages exist when running NixOS tests?

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#47522]
## Issue description
rsyslogd & syslog-nd are broken on NixOS 18.09 because at some point systemd stopped automatically forwarding messages to syslog. See explanation here: https://github.com/NixOS/nixpkgs/pull/47306

The fix for this should be simple enough and I have a working PR for it. The problem is that when running NixOS tests under qemu the file /var/log/messages seems to always exist. Why? /var/log/messages doesn't exist on any of the NixOS machines I run. On my system even when I turn rsyslogd on still nothing gets written to /var/log/messages unless I add ForwardToSyslog=yes to /etc/systemd/journald.conf.

Why do the NixOS qemu images automatically write to /var/log/messages? How do they write there if ForwardToSyslog isn't added to journald.conf? I checked in the qemu machine and journald.conf does not contain ForwardToSyslog at all. Do these qemu images use a syslog instead of journald?

I can't really write an effective test to ensure my code is working because a regular NixOS system is not reproducible in the qemu environment as far as whether /var/log/messages exists or not (what I'm testing for).

Any help on this one?

Thanks

### Steps to reproduce
nix-build '<nixpkgs/nixos/tests/atd.nix>' -A driver
./result/bin/nixos-run-vms

type "root" as a login name to the qemu machine that pops up

ls /var/log/messages

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.72, NixOS, 18.09beta609.3768913cc9e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09beta609.3768913cc9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fpletz** [comment]
`/var/log/messages` does not generally exist in NixOS test VMs as far as I can see from running other tests.

Note that if you use the driver manually, the state of the machines will be kept in `/tmp/vm-state-<name>`. This might just be left there from your earlier invocations of the VM driver when rsyslogd/syslog-nd created this file.

**Comment by aanderse** [comment]
I looked under /tmp and saw /tmp/vm-state-machine. I notice many tests use machine as the name. And yes I notice this when interactively running the test vm.

Thank you very much for explaining!
