### ISSUE TITLE
boost fiber: compile error stray '\357' in program

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#47537]
## Issue description

[nix-shell:~/dev/cpp/fiber/examples]$ g++ ping_pong.cpp 
In file included from include/boost/fiber/algo/work_stealing.hpp:26:0,
                 from include/boost/fiber/all.hpp:13,
                 from ping_pong.cpp:12:
include/boost/fiber/detail/context_spmc_queue.hpp:1:1: error: stray ‘\357’ in program
include/boost/fiber/detail/context_spmc_queue.hpp:1:2: error: stray ‘\273’ in program
include/boost/fiber/detail/context_spmc_queue.hpp:1:3: error: stray ‘\277’ in program

### Steps to reproduce

nix-shell -p boost
g++ ping_pong.cpp

When I download boost from their homepage, compile boost myself and then compile examples in fiber, all works as expected.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.12, NixOS, 18.09.git.dd3090f (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(milan): `"nixos-17.03pre96925.1c50bdd"`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by tex** [comment]
This is what vim shows:

```
#line 1 "include/boost/fiber/detail/context_spmc_queue.hpp"
<feff>﻿
//          Copyright Oliver Kowalke 2013.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
...
```

The <feff> seems wrong.

**Comment by xeji** [comment]
Thanks for spotting this bug! 
Results of a brief analysis: 
- I verified that `nix-build boost.src` produces a source tarball whose sha256 matches upstream data: https://www.boost.org/users/history/version_1_67_0.html, so we're downloading the correct source.
- The file `context_spmc_queue.hpp` is ok in the source tarball
- Build output (produced locally on x86_64-linux with `nix-build boost --check`) contains a broken version of `context_spmc_queue.hpp` with the `<feff>` character.

This means that the file gets messed up somehow during the build process. This might be a symptom of  a more general issue. 

cc maintainers @peti @wkennington 
cc @dtzWill

**Comment by tex** [comment]
I know that problem is in source package. Look at the file in hex editor, you will see the wrong bytes at beginning.

**Comment by tex** [comment]
Nix sed modification turns it to the visible <feff>, so modifying sed looks appropriate to me.

**Comment by xeji** [comment]
```
head -c 32 context_spmc_queue.hpp | od -xc -
0000000    bbef    0abf    2f2f    2020    2020    2020    2020    2020
        357 273 277  \n   /   /
0000020    6f43    7970    6972    6867    2074    6c4f    7669    7265
          C   o   p   y   r   i   g   h   t       O   l   i   v   e   r
0000040
```

So this source file starts with a UTF-8 byte order mark, which is turned into the broken `feff` during the build. 

> Nix sed modification turns it to the visible 'feff'

Do you know which part of the nix expression does that?

**Comment by xeji** [comment]
Yes, I can confirm it is. our sed script just inserts a new line in the beginning without deleting the byte order mark first, so the 3 bytes end up unchanged after new inserted line. So let's get back to your fix...

**Comment by tex** [comment]
Done. BTW, I'm trying to use boost in 32bit enviroment, do you have any idea how to do that? I'm using pkgsi686Linux.stdenv.mkDerivation. Compiler is 32bit but it cannot find 32bit boost libraries...

**Comment by xeji** [comment]
To build a 32 bit  package on a 64 bit system you can use the `system` argument like: `nix-build -A package --argstr system i686-linux`. This would automatically use all required 32bit libs. If you're looking for multilib on a 64 bit system, I heard it's possible but don't know how. Maybe ask around on IRC.

**Comment by xeji** [comment]
Fixed in #47540 (merged to staging)

**Comment by tex** [comment]
Done: https://github.com/boostorg/fiber/pull/182

**Comment by xeji** [comment]
Thanks!
