### ISSUE TITLE
Add 'newlib' libc as extra libc

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#47533]
## Issue description

This is the main difference between our GCC toolchains and the gcc-arm-embedded stuff. They use this target:

```
arm-none-eabi
```

and it should be about equivalent to this:

```
  arm-embedded = rec {
    config = "arm-none-eabi";
    platform = platforms.armv7l-hf-multiplatform;
    libc = "newlib";
  };
```

Related to #39087.

/cc @ericson2314

**Comment by Ericson2314** [comment]
Good call!

**Comment by dtzWill** [comment]
Is newlib a 'libc'? I thought it was more of a toolkit / collection of components for constructing your own libc-esque.... especially good for being able to operate in terms of a small set of primitives you implement.

Haven't looked at it in a while though, is it an actual target now?  The concern with the above is that if it's too customizable it's insufficient to say you're targetting "newlib" as opposed to "this platform's newlib-based libc-esque".

It was my impression no one really actually **used** newlib long-term, it was what you used early in your project to get things going before worrying about ALL the things.  An incredibly valuable use but I'm surprised it's used more permanently. Maybe I was talking to the wrong people or am remembering something else...

I'll look at it more if I get a chance--apologies if I'm spreading misinformation :) corrections welcome...
-----

But of course if it IS something it makes sense to target you know i'm in favor and would be interested in helping test ;).

**Comment by guibou** [comment]
@matthewbauer The removal of `gcc-arm-embedded` package introduced a regression for me.

How can I use this newly packaged `newlib` with hardware floating point support?

I have the following code example:

```nix
# The commit right before your removed gcc-arm-embedded: c327df544ae0875ce71b0a82ae7a650a8e34a268
with import (fetchTarball "https://github.com/nixos/nixpkgs/archive/aa4707fc3449192b961bfd2dfc16b9042df0d7f3.tar.gz") {};
rec {
  # This is a small c file which uses `log` from libm
  file = writeTextFile {
    name = "file.c";
    text = ''
      #include <math.h>
      int _exit(int i){};  # missing symbol during build, this can be ignored.
      int main()
      {
        float v = log(0.f);
        return 0;
      }
    '';
  };

  # my build command ligne, note the -mfloat-abi=hard
  cmd = ''arm-none-eabi-gcc -mfloat-abi=hard ${file} -o file -lm -o $out'';

  # a generic buider
  build = compiler : runCommand "foo" {
    allowSubstitutes = false;
    nativeBuildInputs = [compiler];
  }
  ''arm-none-eabi-gcc -mfloat-abi=hard ${file} -o file -lm -o $out'';

  # that one success
  success = build gcc-arm-embedded;
  # that one fails, with /nix/store/z6pvjan22wqxcg787kyw89jl64dhh2ks-arm-none-eabi-binutils-2.30/bin/arm-none-eabi-ld: error: /build/ccDue1Qh.o uses VFP register arguments, /nix/store/nwf9pkcgjlcympb2yfqwx2svim6w6sa9-foo does not
  failure = build pkgsCross.arm-embedded.buildPackages.gcc;
}
```

Please not the `-mfloat-abi=hard` flag. Apparently, by default, `newlib` is built without hardware floating point support. See https://sourceware.org/newlib/faq.html#q4 which discuss the build flag `--newlib-hw-fp`:

> The `newlib-hw-fp` option causes the library to use a set of math routines that use floating-point algorithms. By default, the newlib library math routines use integer-based algorithms to perform the desired functionality. For a platform that has fast floating-point support, the floating-point algorithms may be faster and smaller.

I'v tried to override `newlib` or `newlibCross` without success with an overlay:

```
 newlibCross = super.newlibCross.overrideAttrs (old : {
    configureFlags = old.configureFlags ++ ["--enable-newlib-hw-fp"];
  });
```

And I've tried to import my cross system using `import <nixpkgs> { crossSystem = { ...; float = "hard" }; }` without success either.

Thank you.

**Comment by matthewbauer** [comment]
Thanks for the report! I will look into a fix for this. I think the issue might actually be from GCC. We build GCC with "--disable-multilib" by default. But I think we will need multilib gcc here as not all platforms are going to support hardware floating point.

I've opened #51184 to track this.
