### ISSUE TITLE
slim themes lead to Xorg crash, when applied in displayManager.slim.theme

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#47548]
## Issue description

Tried to find a new SLiM theme, found some in nixpkgs (listed by `nox slim`). Edited my config to pick one, switched and got X crashed. The snippet below is from `systemctl status display-manager`.

```display-manager[853]: /nix/store/vgb1c2qj1pmdc7l9bnp2c5014kvrpw39-xsession "none+i3" - none+i3
display-manager[853]: slim: Failed to open default theme file /nix/store/31fk04vb48yph754r3wribxkpspdrx5p-slim-theme/default/slim.theme
systemd[1]: display-manager.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: display-manager.service: Failed with result 'exit-code'.
```

Yes, that was a silly thing, as I've already examined a theme package contents, it has global directory structure. I don't know a neat way to apply any theme from system-installed package (aren't they isolated?), and there's no close-available documentation about SLiM themes. I've had to find theme URL by myself, retrieve its SHA-256 and install it by `pkgs.fetchurl`. Not that handy, still.

### Steps to reproduce

* put something like `displayManager.slim.theme = pkgs.slimThemes.gentooSimple` in your configuration file
* `nixos-rebuild` and try starting SLiM
* enjoy the silence

## Technical details

Don't forget to eat your veggies and run `nix-shell -p nix-info --run "nix-info -m"`.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.66, NixOS, 18.03.133154.f094fd6379b (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133154.f094fd6379b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by prusnak** [comment]
SLIM is no longer in nixpkgs: ce26b3e
