### ISSUE TITLE
Clear reproduction of Qt versions mismatch causing plasma failure

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#47552]
First of all: ♥ nixos and the ability to create a self-contained configuration of a system which one can easily use to see a full system failure.

* * *

### What is this all about? 

Users may face issues when upgrading their system, if a Qt dependency was installed in their profile. Their user profile may be at a stale revision, which has a previous Qt version, and the system a newer, but at the same major version.

If the user uses `plasma` as their desktop, it could cause serious headaches, where their session decisively doesn't want to work anymore.

### But why?

This is because of how Qt loads its plugins. See #44047 where there is details about how Qt loads plugins.

### Reproducing

See [this gist](https://gist.github.com/samueldr/fae3aa2116c0380877d12287e7184412) which has a script (`./build.sh`) which can be used to build the VM represented in `configuration.nix`.

 1. Start the vm (`./build.sh`)
 1. Login as alice, password is `foobar`.
 1. Open `konsole` (type it in the app menu if you can't find it).
 1. Try starting `heimdall-frontend`. It should fail with: `qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.`
 1. Use the `break-env` script to install it "properly" (`nix-env -iA`)
 1. The script will tell you that `heimdall-frontend` should work, test it.
 1. Logout, (`loginctl terminate-user alice`)
 1. Try logging back in.

If the environment was broken as expected, it will restart sddm on login.

### What to do?

Ideally, fix this. See #44047 for an attempt at reviewing how nixpkgs-built Qt apps load their plugins.

Additionally, and for the current release, note in the release notes why plasma could be failing on upgrade, and how to resolve (update user environment OR uninstall Qt apps from there).

### What's left to check

Whether 17.09 -> 18.03 faced the same issue or if this is a regression. (Where a stale older minor version of Qt-latest would break plasma.)

### Related

 * An IRC user [faced the issue](https://logs.nix.samueldr.com/nixos/2018-09-29#1608324;).
 * if #44047 doesn't fix this, care should be taken so it does.
 * #47168 is a user facing a similar issue (but with less dire consequences.)

**Comment by jcrben** [comment]
fyi, followed your steps and it went down exactly as you described

**Comment by rileyinman** [comment]
Any updates on this? Facing the issue in a new (19.03) install and I'm not sure what to do other than give up on Plasma for now.

**Comment by samueldr** [comment]
Closing as it should be fixed by the new wrapping, but I haven't verified if it is actually fixed with the new wrapping.
