### ISSUE TITLE
[Visual Studio Code] Wrong / no icon and undiscoverable

### ISSUE THREAD

**Issue by screendriver** [NixOS/nixpkgs#47553]
## Issue description

I installed the [vscode](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/default.nix) Nix package on my MacBook with macOS Mojave. When I open it directly from my terminal via

```sh
~/Development
❯ code .
```

it opens but the icon and name in my dock is wrong

<img width="87" alt="screenshot 2018-09-30 at 11 38 16" src="https://user-images.githubusercontent.com/149248/46256065-d52dda00-c4a5-11e8-8c53-c9c4885c5891.png">

Additionally I can't find it in my spotlight search so it is just callable within my terminal. I tried to search for `vscode` | `code` | `visual studio`

### Steps to reproduce

Just install the Nix package via `nix-env -i vscode`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.0.0, macOS 10.14`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.2`
 - channels(foo): `"nixpkgs-19.03pre153939.0a784c094f2"`
 - nixpkgs: `/Users/foo/.nix-defexpr/channels/nixpkgs`
```

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/70486
