### ISSUE TITLE
haskellPackages.wx fails to build

### ISSUE THREAD

**Issue by bmueck** [NixOS/nixpkgs#47583]
## Issue description

The build of haskellPackages.wx failed because of a missing dependency on the process package.

### Steps to reproduce

$ nix-env -f '<nixpkgs>' -iA 'haskellPackages.wx'

This results in the following (abridged) output.
 
Setup: Encountered missing dependencies:
process >=1.1 && <1.5

builder for '/nix/store/h89vbw5is6d30bd7isniagg5hisjqya1-wxdirect-0.92.3.0.drv' failed with exit code 1
cannot build derivation '/nix/store/50vx1bjvjqdhy3l8k3c5brihanklxp6a-wxcore-0.92.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/q6135rk8y4zhaxs4ck33a59d28qqp6v0-wx-0.92.3.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/q6135rk8y4zhaxs4ck33a59d28qqp6v0-wx-0.92.3.0.drv' failed

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-34-generic, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(bmueck): `"nixpkgs-18.09pre151052.4477cf04b67"`
 - nixpkgs: `/home/bmueck/.nix-defexpr/channels/nixpkgs`

**Comment by ElvishJerricco** [comment]
See: https://github.com/NixOS/nixpkgs/issues/47585#issuecomment-431193770

**Comment by peti** [comment]
This an upstream issue. They do not support recent versions of the Haskell compiler.
