### ISSUE TITLE
Mixing per interface TCP firewall rules with global UDP rules fails

### ISSUE THREAD

**Issue by blaxill** [NixOS/nixpkgs#47580]
## Issue description

Mixing per interface TCP firewall rules with global UDP rules fails. This might be expected behavior but caught me by surprise. At least a warning noting the unused rules would help Nix newbies like me. A "workaround" is to just use interface specific rules for both TCP and UDP.

### Steps to reproduce

Relevant `/etc/nixos/configuration.nix` lines:

~~~nix
  networking.firewall.allowedUDPPorts = [12912];
  networking.firewall.allowedTCPPorts = [22];
~~~

Generates correct iptable dump (only showing relevant lines):

~~~bash
# iptables -S
...
   -A nixos-fw -p tcp -m tcp --dport 22 -j nixos-fw-accept
   -A nixos-fw -p tcp -m tcp --dport 22 -j nixos-fw-accept
   -A nixos-fw -p udp -m udp --dport 12912 -j nixos-fw-accept
...
~~~

Changed `/etc/nixos/configuration.nix` lines:

~~~nix
  networking.firewall.allowedUDPPorts = [12912];
  networking.firewall.interfaces = {
    "wg0" = { allowedTCPPorts = [22]; };
  };
~~~

Causes no UDP rules to be generated:

~~~bash
# iptables -S
...
  -A nixos-fw -i wg0 -p tcp -m tcp --dport 22 -j nixos-fw-accept
...
~~~

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.69, NixOS, 18.09beta446.ef450efb9df (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09beta446.ef450efb9df"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

#41459

**Comment by erictapen** [comment]
I was just surprised by a similar case, which locked me out of my server. I specified `22` only as a global option, not per interface.

Imo if global options are ruled inactive by interface specific options, evaluating a NixOS config with both global options and interface specific options present should fail.

**Comment by Moredread** [comment]
Just to let people know, I haven't gotten around to improve the test, so feel to work on it if you want :)
