### ISSUE TITLE
Tracking issue for partitioning instructions issues

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#47602]
This is a tracking issue created only to track the different issues and pull requests related to the partitioning instructions in the manual.

### The `fdisk` instructions in the manual may not be working right.

They may show more than one issue, the ordering of the partition may not match the expected ones for the following installation instructions, and the bootable flag might not be set properly.

 * https://github.com/NixOS/nixpkgs/issues/39354
 * https://github.com/NixOS/nixpkgs/pull/46309
 * https://github.com/NixOS/nixpkgs/pull/39942
 * https://github.com/NixOS/nixpkgs/pull/45478
 * https://logs.nix.samueldr.com/nixos/2018-10-01#1611513;
 * https://logs.nix.samueldr.com/nixos/2018-10-01#1538353591-1538353667;

* * *

This issue is meant to track the problem and ask for help in finding a proper resolution. Not asking for others to write up, but asking to see if there would be issues in recommending things other than `fdisk`.

I, myself, am extremely reluctant into fixing this using other `fdisk` incantations. They pretty much look like a self-selecting filter by obscurity. I would lean much more towards using `parted` commands, [like our installers tests do](https://github.com/NixOS/nixpkgs/blob/0ff4bb5f875afe8eb208bbabb3f52dc29539d2bc/nixos/tests/installer.nix#L280-L284). (Though, not using `--script`).

Interfaces like `parted` are probably easier to reason about than single-letter commands which's meaning may change again in the future. They would also reduce the verbosity of the steps; it would be a set number of instructions, one per actual action, instead of a list of commands. (One for the disk format, one for setting the boot flag, and one per partition.)

**Comment by vcunat** [comment]
\# 46309 is twice in the list &ndash; that means you meant to link another fourth issue?

**Comment by vcunat** [comment]
BTW, a couple weeks ago I successfully installed 18.09 (beta) on a machine for Hydra, and I followed our manual for partitioning via fdisk.  It was a simple setup, though, so I most likely missed any corner cases.

**Comment by grahamc** [comment]
`parted` is already in the closure https://github.com/NixOS/nixpkgs/blob/83fd9785f65b8fd4cbaa146270f90b2a0d74b5f3/nixos/modules/profiles/base.nix#L15 so we should probably just switch to that anyway, then we don't need to have janky comments describing what the terse commands do.

**Comment by 7c6f434c** [comment]
I think people who have a preference among these tools need only a line «if you prefer fdisk, it is also available» and maybe an internal link to instructions for installing extra tools in case someone wants sfdisk.

Parted probably has the lowest risk of instructions doing something but not
