### ISSUE TITLE
NixOS 18.09 boot failure

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#47637]
Hey, sorry for the very vague bug report, but I'm not sure what more information I can provide. When I try switching from 18.03 to 18.09, my system is no longer bootable. Some text flies by, then the screen blanks.

https://www.youtube.com/watch?v=88-z3AcsrK8 (apologies for the terribly dirty screen...)

My NixOS config: https://github.com/chris-martin/home/blob/c095e1430a27150d0c8190e86521d1f70c079af4/nix/os/cubby.nix

Reverting to an old build of 18.03 still works.

**Comment by jb55** [comment]
https://github.com/chris-martin/home/blob/c095e1430a27150d0c8190e86521d1f70c079af4/nix/os/cubby.nix#L55

this line looks suspicious, have you tried deleting/updating it?

**Comment by nyanloutre** [comment]
Isn't this used to prevent breaking changes between NixOS versions ?

**Comment by jb55** [comment]
@nyanloutre no idea, I just grepped it in nixpkgs and things seems to be switching off of it so I figure it would be worth a shot...

**Comment by nyanloutre** [comment]
More info here : https://nixos.org/nixos/options.html#system.stateversion

**Comment by vcunat** [comment]
I'd try getting logs.  From this I'd guess an X problem.

**Comment by primeos** [comment]
From the video the boot process looks fine, I agree with @vcunat that it's probably an X11 (/DE/WM) problem.

Have you tried to switch to another TTY (e.g. Ctrl+Alt+F2)? Maybe you can login there.
If that doesn't work you could e.g. try to set `services.xserver.autorun = false;` or change `systemd.defaultUnit` (only temporarily to analyze the issue).

**Comment by chris-martin** [comment]
I don't know why, but 18.09 is working for me now.
