### ISSUE TITLE
  systemd-boot-builder fails when fwupd is present

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#47640]
## Issue description

fwupd creates a directory at `<ESP path>/efi/nixos/fw`, for storing firmware updates pending installation.  systemd-boot-builder appears to assume that it can delete everything in `<ESP path>/efi/nixos`, which is probably true, but it also assumes that everything in that directory will be a plain file.  `fw/` is a directory.

### Steps to reproduce

Set `services.fwupd.enable` and run `fwupdmgr refresh; fwupdmgr get-updates` (or maybe `fwupdmgr update`?).  See that `/boot/EFI/nixos/fwupdx64.efi` and `/boot/EFI/nixos/fw/` have been created.  Now try doing a `nixos-rebuild boot` and you should get the following error message:

```
$ sudo nixos-rebuild boot
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/0ch4lbqi2ivwg1q0ii3hcjzh51ap5j1y-initrd.drv
  /nix/store/a66ravdrgsl22pn8qylp34r35cqfr7v0-nixos-system-mintaka-19.03.git.5abc64f.drv
building '/nix/store/0ch4lbqi2ivwg1q0ii3hcjzh51ap5j1y-initrd.drv'...
91441 blocks
building '/nix/store/a66ravdrgsl22pn8qylp34r35cqfr7v0-nixos-system-mintaka-19.03.git.5abc64f.drv'...
Traceback (most recent call last):
  File "/nix/store/qxhzmkkwwaln0wj8h3h8sl3jppijnmdm-systemd-boot-builder.py", line 211, in <module>
    main()
  File "/nix/store/qxhzmkkwwaln0wj8h3h8sl3jppijnmdm-systemd-boot-builder.py", line 196, in main
    remove_old_entries(gens)
  File "/nix/store/qxhzmkkwwaln0wj8h3h8sl3jppijnmdm-systemd-boot-builder.py", line 149, in remove_old_entries
    os.unlink(path)
IsADirectoryError: [Errno 21] Is a directory: '/boot/efi/nixos/fw'
warning: error(s) occurred while switching to the new configuration
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.7, NixOS, 19.03.git.5abc64f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `""`
 - nixpkgs: `/home/benley/p/nixpkgs`
```

**Comment by benley** [comment]
I'm doublechecking that this hasn't already been fixed; my nixpkgs is a couple of weeks out of date.

**Comment by rvolosatovs** [comment]
This happened to me yesterday after performing an update via `fwupdmgr update`(it seems that the directory is only created when updates are performed).
After getting this error during `nixops deploy` (I use `nixops` to manage my local machine and remote servers) I proceeded to reboot the machine only to find out that all valid boot entries were removed from the bootloader and I had to fix the install from a LiveUSB

**Comment by jtojnar** [comment]
This has been noticed [here](https://github.com/NixOS/nixpkgs/issues/39386#issuecomment-385342489), possible solution is outlined [here](https://github.com/NixOS/nixpkgs/issues/39386#issuecomment-385427627).

**Comment by turion** [comment]
So, to be sure, after having run `fwupdmgr update && nixos-rebuild switch`, the system is in an unbootable state?

**Comment by turion** [comment]
@jtojnar

> possible solution is outlined here.

What's a good workaround if one has already run `fwupdmgr update && nixos-rebuild switch`?

**Comment by turion** [comment]
@abbradar Isn't this resolved in your fa2e4bfb61cc5826d36833b12fda312ac1261137?

**Comment by abbradar** [comment]
Oh yes, this is.

**Comment by turion** [comment]
> What's a good workaround if one has already run fwupdmgr update && nixos-rebuild switch?

With clever's help on IRC, I managed to recover my system with these steps:

* Create an install medium
* Mount the system on `/mnt` and its boot partition on `/mnt/boot`
* Enter the system via `nixos-enter --root=/mnt`
* (Re)move `/boot/EFI/nixos/fw`
* `NIXOS_INSTALL_BOOTLOADER=1 /nix/var/nix/profiles/system/bin/switch-to-configuration boot`
* Reboot

**Comment by flokli** [comment]
It seems this is also broken on 19.03. I added https://github.com/NixOS/nixpkgs/pull/65414 to fix it. Could you please take a look?

**Comment by grahamc** [comment]
This is broken on 19.09 as of 19.09.736.9bbad4c6254.

**Comment by grahamc** [comment]
I'm lying, this is a problem from me using https://github.com/NixOS/nixpkgs/search?q=signed+systemd-boot&type=Issues
