### ISSUE TITLE
Customising path to executable in .desktop file

### ISSUE THREAD

**Issue by jrobinson-uk** [NixOS/nixpkgs#47685]
https://github.com/NixOS/nixpkgs/blob/a88b8da55436e4d74ff5fa50c5c20308966a34cb/pkgs/games/minecraft/default.nix#L8

What's the best way to override the desktop icon's exec parameter (I want to launch minecraft via padsp) is it via a package override, overlay or something else. Have tried a few options but without success

**Comment by peterhoeg** [comment]
Change to: ```exec = "@out@/bin/minecraft";```

And then use ```substituteInPlace --subst-var``` on the .desktop file.

**Comment by aanderse** [comment]
@jrobinson-uk seeing as the question was answered can you please close the issue?
