### ISSUE TITLE
nice to have: Zoom clickable links on NixOS

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#47799]
## Issue description
When clicking on a Zoom link in Slack, Zoom doesn't open. It would be nice if it would do this, like on e.g. a Mac or Windows.

Otherwise, Zoom on NixOS seems to actually *work* (since my upgrade to 18.09 and a new version of zoom), which is a pretty big deal as far as I am concerned. Good job everyone!

**Comment by flokli** [comment]
@coretemp We do already register a scheme handler for zoommtg:// urls, so zoom.us/test, then selecting "Use xdg-open" opens the meeting for me. What Links do you get from Slack?

**Comment by flokli** [comment]
I did try this on my own. Links from the Slack client open a website which redirects to a `zoommtg://` URL, Chrome asks me whether I want to use `xdg-open` to open it. Afterwards, Zoom boots up into that meeting, so I think this is fixed. Please comment if it's not the case.
