### ISSUE TITLE
user passwords dont get removed after removing it in configuration.nix

### ISSUE THREAD

**Issue by bernadinm** [NixOS/nixpkgs#47813]
## Issue description

Testing Nix functional approach and confirming the idempotency of the tool. 

### Steps to reproduce

1. Run this configuration.nix:

```
  users.extraUsers.mb =
  {
    isNormalUser = true;
    createHome = true;
    hashedPassword = "$6$<hash>.";
}
```
```
sudo nixos-rebuild switch
```
2. confirm user is created, then remove password

```
  users.extraUsers.mb =
  {
    isNormalUser = true;
    createHome = true;
    #hashedPassword = "$6$<hash>.";
}
```
```
sudo nixos-rebuild switch
```

3. then attempt to modify a file that requires credentials.
```
sudo vim /etc/nixos/configuration.nix
Password:
```
Log in with removed credentials. This should not work. If I remove the user mb entirely and create it without a hashpassword to begin with, this works but that is not ideal.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 18.03.133245.d16a7abceb7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133245.d16a7abceb7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by bernadinm** [comment]
Another thing I found was that if I change a users password directly using `passwd` and rerun `sudo nixos-rebuild switch` it doesn't change it back. 

What is the expected behavior for this? 

Thank you for help!

**Comment by bernadinm** [comment]
related to #20406

**Comment by symphorien** [comment]
Do you have disabled mutable users ? https://nixos.org/nixos/options.html#mutableusers
This is probably a requirement.

**Comment by bernadinm** [comment]
Wow! Thank you @symphorien. This worked. I wasn't aware of this flag and that it was set to true by default. Changing it to false worked. 

Marking this as closed.
