### ISSUE TITLE
security.wrappers should check if file exists

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#47839]
## Issue description

The suid wrappers configured via ```security.wrappers``` are not checking if a referenced file exists which leads to:

```
$ kcheckpass
kcheckpass: cannot run `/nix/store/gdfndzkmz221lnhfkfa1z7c2mdr0yqc7-plasma-workspace-5.13.5-bin/lib/libexec/kcheckpass': No such file or directory
```

For the case above, it's fixed in #47838 but we really should ```assert``` on file presence.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.10, NixOS, 19.03.git.1e7c1a82c6cM (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.2`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`

**Comment by peterhoeg** [comment]
I'll get around to it.

**Comment by peterhoeg** [comment]
keep

**Comment by rnhmjoj** [comment]
Implemented in https://github.com/NixOS/nixpkgs/pull/126289
