### ISSUE TITLE
How to propagate some binaries in haskell (bug ?)

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#47862]
## Issue description
ghcWithPackages doesn't seem to propagate correctly propagatedBuildInputs ? (this or I do something wrong but i looked fine to me).

### Steps to reproduce

I am trying to make ihaskell work with the jupyter service in a more straightforward way than now, the idea being to generate a ihaskell/kernel.json file and use load it in jupyter.service.
If I run
```
$ nix-shell -p 'haskellPackages.ghcWithPackages(p: with p; [ ihaskell ])' 
$ ihaskell install  --debug --prefix .
No Jupyter / IPython detected -- install Jupyter 3.0+ before using IHaskell.
ihaskell: 
Ran commands: 
which jupyter
which ipython

Exception: ExitFailure 1
```

so I've added in an overlay
```
  haskell = prev.haskell // {
    packageOverrides = hself: hprev: with prev.haskell.lib; rec {  

      ihaskell = overrideCabal (dontCheck hprev.ihaskell) ( drv: {
        executableToolDepends = [ prev.pkgs.jupyter ];
        executableHaskellDepends = [ prev.pkgs.jupyter ];
      });
    };
  }

```
This generates the same error but if I run
```
$ nix-shell -p haskellPackages.ihaskell
[nix-shell:~]$ jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
```
then jupyter is accessible.

## Technical details

I am at
```
commit 13b2903169f18ac98ed737effb36dabc48051978 (HEAD, channels/nixos-unstable)
Author: Jörg Thalheim <joerg@thalheim.io>
Date:   Mon Oct 1 12:08:02 2018 +0100

    alacritty: spell darwin platform correctly
```

**Comment by matthewbauer** [comment]
I think the overlay should be on haskell.packages.ghc843 not haskell. Try adding a trace to your overrideCabal to make sure it is being run.

**Comment by teto** [comment]
From what I read in the doc, the overlay on haskell works for all versions of compilers, on the contrary to 
`haskell.packages.ghc843`. I had tested before but added a trace to make sure and the override is picked up since I can see the trace call print sthg. Thanks for helping :)

**Comment by teto** [comment]
closing as I dont have time to follow up on this.
