### ISSUE TITLE
Norwegian kbd keymap defaults to dvorak instead of qwerty in NixOS

### ISSUE THREAD

**Issue by plutotulp** [NixOS/nixpkgs#47877]
## Issue description
Setting 

> i18n.consoleKeyMap = "no"; 

in configuation.nix gets me the dvorak mapping instead of the normal qwery one. This makes hard drive decryption just way too entertaining.

## Technical details
The kbd package comes with two "no" maps, one in qwery and one in dvorak. The dvorak one takes precedence.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 18.03.133245.d16a7abceb7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133245.d16a7abceb7, nixpkgs-19.03pre153701.46651b82b87"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vcunat** [comment]
Solved; described in #47878 thread.
