### ISSUE TITLE
[haskellPackages] pandoc-crossref updated to v0.3.3.0, when it shouldn't be

### ISSUE THREAD

**Issue by lierdakil** [NixOS/nixpkgs#47872]
Hi. Author of pandoc-crossref here.

Not sure why, but apparently pandoc-crossref was updated to v0.3.3.0, while pandoc is still sitting at 2.2.1. pandoc-crossref v0.3.3.0 explicitly requires pandoc v2.3. Hence, building pandoc-crossref is imposible atm.

So... what's going on here? Catastrophic constraint solver failure? Or is there no constraint solver at all?

**Comment by matthewbauer** [comment]
Actually that might not be true. I wonder if there is a way to get when pandoc 2.3 comes out?

**Comment by lierdakil** [comment]
Nixpkgs is broken though, so I'm not entirely sure why this is closed?

**Comment by lierdakil** [comment]
I mean, it's a valid concern that packages in `haskellPackages` aren't consistent, isn't it?

**Comment by lierdakil** [comment]
Do you check version constraints at all when bumping packages in `haskellPackages` by the way? Because if you do, this issue would indicate that something went terribly wrong there. And if you don't... just why?
