### ISSUE TITLE
spotify "login with facebook" unresponsive

### ISSUE THREAD

**Issue by jafonsor** [NixOS/nixpkgs#47885]
## Issue description

Login with facebook button does nothing.

### Steps to reproduce

Open spotify with the command line (no spotify app is listed on kde dash).

```
~$ spotify
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results:

```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev
copying path '/nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.72, NixOS, 18.09beta621.c922e20b5d3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(joao): `"nixos-19.03pre153701.46651b82b87"`
 - channels(root): `"nixos-18.09beta621.c922e20b5d3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jafonsor** [comment]
If there is a way to give you more information, like log files, please tell me where to find them ;)

**Comment by gallexme** [comment]
same issue

**Comment by timokau** [comment]
This is probably https://community.spotify.com/t5/Desktop-Windows/Log-In-with-Facebook-button-not-working/td-p/4487719.

https://community.spotify.com/t5/Desktop-Windows/Log-In-with-Facebook-button-not-working/td-p/4487719 may also be relevant.

**Comment by Anton-4** [comment]
This issue still occurs. For those looking for a workaround, you can also listen to spotify through the website: https://open.spotify.com

**Comment by pbsds** [comment]
`journalctl` output:

```
firefox.desktop[61578]: XPCOMGlueLoad error for file /nix/store/m0g4ical3chazg00s7zps4lvgpwlay9n-firefox-110.0.1/lib/firefox/libxul.so:
firefox.desktop[61578]: /nix/store/2wk1cfl5dldiz19yvvkdgy9cywwff3iw-nss-3.79.4/lib/libssl3.so: version `NSS_3.80' not found (required by /nix/store/m0g4ical3chazg00s7zps4lvgpwlay9n-firefox-110.0.1/lib/firefox/libxul.so)
firefox.desktop[61578]: Couldn't load XPCOM.
```

**Comment by Atemu** [comment]
Could y'all check whether https://github.com/NixOS/nixpkgs/pull/229165 has fixed this?

**Comment by pbsds** [comment]
works on my computer
