### ISSUE TITLE
Plasma does not support PulseAudio’s module-gsettings

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#47938]
## Issue description
Can't use virtual output device for output on all sound cards or automatically switching all running streams when a new output is available without it.

### Steps to reproduce
Use pulseaudio, attempt to do one of the above.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.12, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b, nixpkgs-19.03pre153206.f753852e11d"`
 - channels(okina): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
`module-gconf` was replaced with `module-dconf` in https://github.com/NixOS/nixpkgs/pull/43160. Not really sure how would I do the thing you describe with gconf module.

**Comment by Chiiruno** [comment]
@jtojnar I'm not really sure, honestly, I just know I get this message in KDE system settings.
![screenshot_20181005_174650](https://user-images.githubusercontent.com/30435868/46563376-a8732b80-c8c6-11e8-82dd-73265b3a8a6f.png)
Is there any way we can fix this? I tried loading module-dconf in `pactl` but of course, it didn't work.

**Comment by jtojnar** [comment]
At least the first option can be set in `paprefs`; not sure about the other one.

Actually, the module is named `module-gsettings`. KDE should be updated to use it.

**Comment by Chiiruno** [comment]
Well, I tried loading that module too, unfortunately no dice.
I was able to enable the first option in `paprefs`, but it didn't actually do anything.

**Comment by jtojnar** [comment]
You will probably need to be running `dconf` – try adding `programs.dconf.enable = true;` to your `configuration.nix`.

**Comment by Chiiruno** [comment]
Already enabled.

**Comment by jtojnar** [comment]
Not sure what would the issue be, I can only confirm it works for me in GNOME:

![virtual device disabled](https://user-images.githubusercontent.com/705123/46563899-5b15af00-c904-11e8-9e0e-754c19edec90.png)

![virtual device enabled](https://user-images.githubusercontent.com/705123/46563896-551fce00-c904-11e8-8d22-7a77ef27ce98.png)

Do you have any errors in journal or in console when running paprefs from there?

**Comment by jtojnar** [comment]
Just for reference: https://phabricator.kde.org/D14147

**Comment by Chiiruno** [comment]
Nothing in console, but I did find some related journal logs.
```
org.kde.kcoreaddons: Error loading plugin "kcm_pulseaudio" "The shared library was not found."
...
GConf Error: Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemon. See http://projects.gnome.org/gconf/ for information. (Details -  1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files)
Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemon. See http://projects.gnome.org/gconf/ for information. (Details -  1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files)
```

**Comment by Chiiruno** [comment]
My pulseaudio isn't system-wide, so I'm a bit confused too.
It's really strange that paprefs isn't working, especially if it's supposed to be in this case.

**Comment by jtojnar** [comment]
Let’s continue in a new issue about the paprefs not working.

**Comment by Chiiruno** [comment]
Okay.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/issues/47938#issuecomment-427523542

was mentioned two years ago, but now we have again something similar https://github.com/NixOS/nixpkgs/issues/102253

**Comment by FRidh** [comment]
Given we're two years further I have my doubts whether this issue still exists and will so close it. Please open a new issue in case it does with 20.09.

**Comment by haizaar** [comment]
Still exists - trying to click any of these two options doesn't do anything. They revert back to unchecked once I leave the screen.
![2022-06-28_01-49](https://user-images.githubusercontent.com/58201/175982364-e360f653-8c75-4555-9e25-858d76806823.png)

**Comment by jtojnar** [comment]
@haizaar Do you have `programs.dconf.enable = true;`? Anything in system journal?

**Comment by haizaar** [comment]
Thanks for follow up.
I now have `programs.dconf.enable = true;` and paprefs can enable virtual output successfully. However KDE config still have the checkbox unticked and does *not* see the virtual device (though the virtual device is visible and operational through pavucontrol)

Will open a new one.
