### ISSUE TITLE
[RFC] Adding a /opt symlink for easier installation of non-free, closed-source packages

### ISSUE THREAD

**Issue by bfortz** [NixOS/nixpkgs#47997]
## Issue description

Many unfree, closed-source packages are installed in /opt on other linux distributions, and assume all the files lie there with some paths hard coded. Although wrappers and substitutions can help in fixing this, sometimes it is very difficult or impossible to make changes because the paths are hard-encoded in binary files. I got into such problems with the closed-source driver for my printer (Brother DCP-J152W). On my system, I fixed the problem by:
- adding /opt to pathToLinks in my configuration.nix
- manually making a symlink from /run/current-system/sw/opt to /opt

I was wondering if we should not have this as a default, or at least have a config option to do that automatically. This would reduce the cost of porting non-free apps to nixos imo, without breaking too much of reproducibility.

(Sorry if this has been discussed elsewhere, I could not find anything)

**Comment by symphorien** [comment]
For problematic software you can use libredirect. There are several examples in nixpkgs, one at random:
https://github.com/NixOS/nixpkgs/blob/938a0ddf4a05137907ac019a793c26a29b13a1b9/nixos/modules/services/networking/pptpd.nix#L88-L90

**Comment by bfortz** [comment]
@symphorien thanks! That seems a good option but I'm still running into problems: first try was the approach above, but then I got the following error:
`ld.so: object \'/nix/store/7kp9vz0id1rnd8iqs8wsxyp4ysmgmlz3-libredirect-0/lib/libredirect.so\' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

Logical as the driver is 32-bit (stupid me). But then tried with:
`--set LD_PRELOAD "${pkgs.pkgsi686Linux.libredirect}/lib/libredirect.so"`
to force the 32 bit version of libredirect.so, same error message with ELFCLASS32 instead of ELFCLASS64!

What do I miss? For information, here is the result of file on the executable:
`brcupsconfpt1: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /nix/store/a0d6q18gxggcvb5x24nrdg6nvhbnipnb-glibc-2.27/lib/ld-linux.so.2, for GNU/Linux 2.2.0, stripped`

**Comment by symphorien** [comment]
It can be that brcupsconfpt1 is then calling 64bit executables, passing LD_PRELOAD to them.
Wrap them to unset LD_PRELOAD, probably.

**Comment by bfortz** [comment]
@symphorien that was my guess, but difficult to trace. But it was even more stupid... I did not wrap the right executable... Thanks again, I learned a lot today! (this libredirect should be documented somewhere).
