### ISSUE TITLE
Blank window when starting mumble-1.2.19

### ISSUE THREAD

**Issue by nek0** [NixOS/nixpkgs#48004]
## Issue description

When starting mumble 1.2.19 after a fresh install of the package, I get presented with a blank window and nothing else happens. When started from console nothing appears out of order.

### Steps to reproduce

* install mumble
* start mumble
* ????
* non-profit

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre154715.d29947c36a7 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b, nixpkgs-19.03pre154715.d29947c36a7"`
 - channels(nek0): `""`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by timokau** [comment]
Should be fixed in #48744 thanks to @thefloweringash.
