### ISSUE TITLE
Python PyFilesystem `fs` should be updated from 0.5.4 to PyFilesystem 2

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#48034]
## Issue description

The current `python3Packages.fs` is still currently set to 0.5.4. But this points to the `fs` package in https://pypi.org/project/fs/ which is no longer the same package. The Pypi `fs` package is now Pyfilesystem 2: https://github.com/PyFilesystem/pyfilesystem2

The API has changed and everything else.

So the `fs` package should be changed to the version 2 pyfilesystem. But the old `fs` package may require it's own alias if people are still using that version.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L5578-L5608

@lovek323

**Comment by FRidh** [comment]
Feel free to open a PR.

**Comment by costrouc** [comment]
@CMCDragonkai  do you have a suggestion as to what the old version of fs should be called? I am considering `fs_0_5_4`.

**Comment by CMCDragonkai** [comment]
Its Pyfilesystem 1. Then fs_1 is fine.

**Comment by costrouc** [comment]
I have removed `fs_0_5_4` from the PR. Now there is only one package `fs`. Should be ready for check and merge

**Comment by costrouc** [comment]
@CMCDragonkai @FRidh this issue is resolved. Can be closed.

**Comment by CMCDragonkai** [comment]
@costrouc Thank you very much!
