### ISSUE TITLE
wxmac fails to build due to missing CF functions

### ISSUE THREAD

**Issue by mikesperber** [NixOS/nixpkgs#48065]
## Issue description

The current wxmac port fails to build.

### Steps to reproduce

Build wxmac from latest git.

```
Undefined symbols for architecture x86_64:
  "_CFURLCreateFromFSRef", referenced from:
      wxMacFSRefToPath(FSRef const*, __CFString const*) in basedll_filefn.o
  "_CFURLGetFSRef", referenced from:
      wxMacPathToFSRef(wxString const&, FSRef*) in basedll_filefn.o
```

## Technical details

wxWidgets uses some deprecated CoreFoundation functions, which are no longer there.

Upstream version 3.0.4 still uses these functions.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.0.0, macOS 10.14`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.2`
 - channels(sperber): `"nixpkgs-16.03pre70724.d4bebcb"`
 - nixpkgs: `/afs/deinprogramm.de/home/sperber/build/nixpkgs`

**Comment by matthewbauer** [comment]
That's very annoying! There has been a recent update of CF by @copumpkin that uses CF from https://github.com/apple/swift-corelibs-foundation. We should be able to patch it to fix these references and use updated APIs.

For now though you will probably be stuck on 18.03 or 18.09 if you need wxmac.

**Comment by mikesperber** [comment]
Yeah, I looked into that for a while, but the references to the now-unsupported FSRef type are pretty widespread in the wxmac codebase. :-(

(I don't need wxmac directly, but erlang depends on it.)

**Comment by copumpkin** [comment]
Yeah, I patched those calls out of QT 4 but haven't gone and looked for other stuff that uses them.

**Comment by mikesperber** [comment]
I was thinking the same thing, but my impression was that these are part of the public API of wxWidgets.
