### ISSUE TITLE
Update Qt Creator from 4.6.2 to 4.7.1

### ISSUE THREAD

**Issue by hugues31** [NixOS/nixpkgs#48068]
## Issue description
Hello,
In the repository of NixOS, I found the Qt Creator in version 4.6.2. However I'd like to install the latest stable version (4.7.1). What are my options to install the latest Qt Creator (and Qt libs also...) please ?

I am new to NixOS but I heard that I can change this file : https://github.com/NixOS/nixpkgs/blob/617607e0437ff0ad34687498746e8970aae6d9bc/pkgs/development/tools/qtcreator/default.nix and set the number version here (and change the SHA256 obviously). Is it all ? How can I test this change locally before sending a pull request ?

Thanks in advance :)

**Comment by sengaya** [comment]
@hugues31 In many cases it's enough to change the version + checksum. See https://nixos.org/nixpkgs/manual/#chap-quick-start how to build/test locally.

**Comment by hugues31** [comment]
@sengaya Ok thanks for your help. I will try this and maybe send a PR. Have a nice day
