### ISSUE TITLE
nixos-option doesn't handle missing attributes

### ISSUE THREAD

**Issue by thefloweringash** [NixOS/nixpkgs#48060]
## Issue description

```
$ nixos-option services.foo 
error: attribute 'foo' missing
This attribute set contains:
/run/current-system/sw/bin/nixos-option: eval: line 319: syntax error near unexpected token `newline'
```

Running with verbose, produces
```
[...]
++ result='error: attribute '\''foo'\'' missing, at (string):6:55
(use '\''--show-trace'\'' to show detailed location information)'
++ exit_code=1
++ set -e
++ test 1 -eq 0
++ sed -n '
  /^error/ { s/, at (string):[0-9]*:[0-9]*//; p; };
  /^warning: Nix search path/ { p; };
'
error: attribute 'foo' missing
++ exit_code=1
+ result=
++ attrNames ''
+ names='<PRIMOP>'
+ echo 'This attribute set contains:'
This attribute set contains:
+ nixMap escapeQuotes '<PRIMOP>'
+ local fun=escapeQuotes
+ local 'list=<PRIMOP>'
+ local elem
+ for elem in $list
+ test '<PRIMOP>' = '[' -o '<PRIMOP>' = ']'
+ escapeQuotes '<PRIMOP>'
+ eval echo '<PRIMOP>'
/run/current-system/sw/bin/nixos-option: eval: line 319: syntax error near unexpected token `newline'

```

### Steps to reproduce

Run nixos-option on a config path that doesn't exist.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.git.2998eba (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(lorne): `""`
 - channels(root): `"nixos-18.09.783.299814b385d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Ma27** [comment]
yeah, IIRC `nixos-option` had several issues in handling several cases in the module system which lead to unexpected abortions or outputs.

Let's see if I memorize enough details about the script to properly fix it :)
