### ISSUE TITLE
spotify: icon is broken

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#48062]
## Issue description

Installed `.desktop` file contains absolute path to an icon, which is not available:

```
Icon=/usr/share/spotify/icons/spotify-linux-128.png
```

I suggest to change this line to:

```
Icon=spotify-client
```

The desktop environment should correctly guess the file extension.

Another, possibly unrelated issue is that I don't see the spotify directory in `$XDG_DATA_DIRS` variable.

**Comment by prusnak** [comment]
cc @eelco @ftrvxmtrx @sheenobu @mudri

**Comment by peterhoeg** [comment]
@prusnak, do you feel taking a stab at a PR?

**Comment by prusnak** [comment]
Will be fixed via https://github.com/NixOS/nixpkgs/pull/48208
