### ISSUE TITLE
net-snmp 5.8 is out

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#48099]
## Issue description

net-snmp 5.7.3 is pinned to an old perl but now that 5.8 is out, we should be able to drop that.

https://sourceforge.net/projects/net-snmp/files/net-snmp/5.8/

Cc: @wkennington

**Comment by xeji** [comment]
I don't understand. The pin to perl 5.22 was already dropped on master in #47373, and perl 5.22 and 5.24 were dropped in #47416.

**Comment by peterhoeg** [comment]
Looks like I wasn't paying attention. Thanks @xeji

**Comment by cyounkins** [comment]
Worked on this and found this was needed: https://github.com/NixOS/nixpkgs/pull/50933

**Comment by cyounkins** [comment]
Working on this and expect to be done tomorrow. WIP branch: https://github.com/cyounkins/nixpkgs/commits/net_snmp

**Comment by Ekleog** [comment]
Upgraded in https://github.com/NixOS/nixpkgs/pull/54616
