### ISSUE TITLE
aarch64 sd image build failing on hydra

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#48167]
## Issue description

The build [worked](https://hydra.nixos.org/job/nixos/release-18.03-aarch64/nixos.sd_image.aarch64-linux) for 18.03 (thanks to @dezgeg) but is failing for 18.09: https://hydra.nixos.org/job/nixos/release-18.09-aarch64/nixos.sd_image.aarch64-linux.

**Comment by vcunat** [comment]
Solved years ago.
