### ISSUE TITLE
git executables are missing PERL5LIB

### ISSUE THREAD

**Issue by manveru** [NixOS/nixpkgs#48199]
## Issue description

I found an issue while cloning repos, which was caused by `git-credential-netrc` not finding the `Git.pm` library.
Setting `PERL5LIB = "${git.outPath}/lib/perl5/site_perl/5.28.0"` in nix-shell fixed it.

### Steps to reproduce

`/nix/store/9gv8d1866f3xhr9d5p3zmp25xicic8rg-git-2.19.1/bin/ -f ~/.netrc example`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.776.6a3f5bcb061 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.776.6a3f5bcb061, nixpkgs-unstable-19.03pre154584.c65da8b5111"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by manveru** [comment]
@LnL7 @dtzWill maybe you wanna have a look?

**Comment by xeji** [comment]
cc @volth

**Comment by volth** [comment]
This seems to need a wrapper, something like

```
wrapProgram $out/bin/git-credential-netrc \
  --set PERL5LIB "${lib.makePerlPath [ git ]}"
````

**Comment by aanderse** [comment]
@manveru fixed so this issue can be closed.
