### ISSUE TITLE
JNI with jdk10 on macOS delegates to system installed jdk

### ISSUE THREAD

**Issue by uri-canva** [NixOS/nixpkgs#48197]
## Issue description

When creating a JVM via JNI using the `jdk10` nix derivation, the resulting code delegates the creation of the jvm to the system jdk.

### Steps to reproduce

Assuming you have jdk10 installed in a profile, and a working version of clang++ (clang installed from Nix into a profile requires some wrappers / extra flags to work):

```
$ clang -I/nix/var/nix/profiles/per-user/user/jdk10-profile/include -L/nix/var/nix/profiles/per-user/user/jdk10-profile/jre/lib/server -ljvm -Wl,-rpath,/nix/var/nix/profiles/per-user/user/jdk10-profile/jre/lib/server java.cpp
$ ./a.out
No Java runtime present, requesting install.
$ echo $?
97
```
`java.cpp`:
```
#include <jni.h>

int main(int argc, char* argv[])
{
  JavaVMInitArgs args;
  args.version = JNI_VERSION_1_8;
  args.ignoreUnrecognized = false;

  JNIEnv* env;
  JavaVM* jvmTemp;
  JNI_CreateJavaVM(&jvmTemp, (void **)env, &args);

  return jvmTemp->DestroyJavaVM();
}
```

<img width="440" alt="screen shot 2018-10-11 at 5 39 00 pm" src="https://user-images.githubusercontent.com/33242106/46785176-b3253900-cd7c-11e8-8be9-fbb87d5baa4c.png">

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.0.0, macOS 10.14`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(uri): `"nixpkgs-19.03pre152822.f1737fa6466"`
 - nixpkgs: `/Users/uri/.nix-defexpr/channels/nixpkgs`
```

**Comment by uri-canva** [comment]
The repro instructions omit building the binary within Nix for convenience, but the same reproes with `nix-shell -p clang jdk10`.

**Comment by uri-canva** [comment]
Also set the `PATH` to empty just to make sure it wasn't looking for the jdk by resolving `javac` or something.

**Comment by SergeevPavel** [comment]
Maybe linking with `libjli.dylib` will solve you problem. I'm not sure what the difference, but it also have `JNI_CreateJavaVM` function and it works for me.

**Comment by uri-canva** [comment]
Tested it with openjdk11 and this doesn't seem to be an issue anymore.
