### ISSUE TITLE
VirtualBox host extension broken on NixOS 18.09

### ISSUE THREAD

**Issue by shreyanshk** [NixOS/nixpkgs#48202]
## Issue description
VirtualBox host extensions are not installed (as visible in VBox's preferences > extension) even after having
```
virtualisation.virtualbox.host.enable = true;
nixpkgs.config.virtualbox.enableExtensionPack = true;
```
in configuration.nix file.
It used to work on NixOS 18.03

### Steps to reproduce
Install NixOS 18.03 and then switch to NixOS 18.09

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.810.59fe4c7f17a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.810.59fe4c7f17a"`
 - channels(shreyansh): `"nixuns-19.03pre154487.0a7e258012b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by xeji** [comment]
cc @flokli

**Comment by Yarny0** [comment]
I think this changed in NixOS 18.09, in a way that no longer requires downloading the extension pack manually (at least I had to do so before). Try these configuration settings:

```nix
{
  virtualisation.virtualbox.host.enable = true;
  virtualisation.virtualbox.host.enableExtensionPack = true;
  nixpkgs.config.allowUnfree = true;
}
```

**Comment by shreyanshk** [comment]
Can confirm this works. Closing this issue.
