### ISSUE TITLE
Certificates do not work inside Docker image inside nix-shell

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#48211]
## Issue description

I have an image based on https://github.com/LnL7/nix-docker. 

Script named `testme`, which does work on NixOS, but not inside a Docker image(!) even though it is "pure".

```
#!/usr/bin/env nix-shell
#!nix-shell -I nixpkgs=./nixpkgs --pure -i sh -p wget
wget https://curl.haxx.se/ca/cacert.pem
```
When .nixpkgs is pointing at commit 42725274ef0855ff28bf01cffc7953326ca58e5c (probably not relevant). 

```
$ ./testme
--2018-10-11 13:29:39--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... 151.101.2.49, 151.101.66.49, 151.101.130.49, ...
Connecting to curl.haxx.se (curl.haxx.se)|151.101.2.49|:443... connected.
ERROR: cannot verify curl.haxx.se's certificate, issued by 'CN=GlobalSign CloudSSL CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
To connect to curl.haxx.se insecurely, use `--no-check-certificate'
```

Expected output: 

`cacert.pem` should have been downloaded

## Technical details

```
these derivations will be built:
  /nix/store/8acv739qqabsvgzaczhbggg4az6aivqi-nix-info.drv
building '/nix/store/8acv739qqabsvgzaczhbggg4az6aivqi-nix-info.drv'...
unpacking sources
unpacking source archive /nix/store/wqkmmn6jqpbx348c8h85f2hm4m0rk92k-info.sh
source root is nix-info
/nix/store/15kgcm8hnd99p7plqzx7p4lcr2jni4df-set-source-date-epoch-to-latest.sh: line 13: [: : integer expression expected
patching sources
configuring
no configure script, doing nothing
building
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/z4g4vyiy1qc26x2zapllkphlg9yc60g6-nix-info
strip is /nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/z4g4vyiy1qc26x2zapllkphlg9yc60g6-nix-info/bin 
patching script interpreter paths in /nix/store/z4g4vyiy1qc26x2zapllkphlg9yc60g6-nix-info
checking for references to /tmp/nix-build-nix-info.drv-0 in /nix/store/z4g4vyiy1qc26x2zapllkphlg9yc60g6-nix-info...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.2`
 - nixpkgs: `/nix/store/ml2yq4cj4n234bp7srawm674b93sak4i-nixpkgs-unstable-2018-09-21`
```

**Comment by coretemp** [comment]
Adding `cacert` as dependency seems to work.

**Comment by nicknovitski** [comment]
All nix-docker images [set environment variables which point to cacert](https://github.com/LnL7/nix-docker/blob/8dcfb3aff1f87cdafeecb0d27964b27c3fb8b1d2/default.nix#L70-L71).  The use of `--pure` in your shebang means those won't be present in the script's environment.  You can either specify cacert as a dependency of the script, or use nix-shell's `--keep` option

```
$ docker run --rm lnl7/nix:2.1.2 env | grep ca-bundle
GIT_SSL_CAINFO=/nix/store/xdsqgqqn8lzcviqgz18fqm51x414nnby-nss-cacert-3.38/etc/ssl/certs/ca-bundle.crt
SSL_CERT_FILE=/nix/store/xdsqgqqn8lzcviqgz18fqm51x414nnby-nss-cacert-3.38/etc/ssl/certs/ca-bundle.crt
$ docker run --rm lnl7/nix:2.1.2 nix-shell -p wget --pure --command env | grep ca-bundle
these paths will be fetched (58.43 MiB download, 367.76 MiB unpacked):
# no matching output
$ docker run --rm lnl7/nix:2.1.2 nix-shell -p wget --pure --keep SSL_CERT_FILE --command env | grep ca-bundle
these paths will be fetched (58.43 MiB download, 367.76 MiB unpacked):
# ...
SSL_CERT_FILE=/nix/store/s1laimmr39q6vkqd7d001g65f1ghfqa9-nss-cacert-3.38/etc/ssl/certs/ca-bundle.crt
$  docker run --rm lnl7/nix:2.1.2 nix-shell -p wget --pure --keep SSL_CERT_FILE --command "wget https://curl.haxx.se/ca/cacert.pem"
these paths will be fetched (58.43 MiB download, 367.76 MiB unpacked):
# ...
--2018-10-29 22:19:56--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... 151.101.2.49, 151.101.66.49, 151.101.130.49, ...
Connecting to curl.haxx.se (curl.haxx.se)|151.101.2.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 209309 (204K) [application/x-pem-file]
Saving to: 'cacert.pem'

     0K .......... .......... .......... .......... .......... 24% 5.20M 0s
    50K .......... .......... .......... .......... .......... 48% 8.42M 0s
   100K .......... .......... .......... .......... .......... 73% 7.32M 0s
   150K .......... .......... .......... .......... .......... 97% 9.00M 0s
   200K ....                                                  100% 8399G=0.03s

2018-10-29 22:19:56 (7.31 MB/s) - 'cacert.pem' saved [209309/209309]
```

**Comment by coretemp** [comment]
Closing, because it works as designed.

Thank you @nicknovitski

**Comment by nicknovitski** [comment]
I thought you might like to know that I just had this same problem.  I spent a day and a half spent fixing things that didn't address the real problem I was having, and just now finally noticed a message buried in CI output that curl didn't have local certificates.  I was also running `nix-shell --pure` on an `lnl7/nix` (ie, nixos-like) container.

Thank you for prompting me to look into this a month ago and write up an explanation, and thank you github for having an interface to easily find closed issues that mentioned me.

**Comment by LnL7** [comment]
This usually works because distros (including nixos) will link the cert bundle in a global location that is found accidentally by things like curl. Using a pure shell is supposed to reproduce a build environment where you'd have the same problem so I don't think this is something nix should implicitly inherit from the parent shell.

**Comment by nicknovitski** [comment]
No, it definitely shouldn't.On Nov 29, 2018 12:17, Daiderd Jordan <notifications@github.com> wrote:This usually works because distros (including nixos) will link the cert bundle in a global location that is found accidentally by things like curl. Using a pure shell is supposed to reproduce a build environment where you'd have the same problem so I don't think this is something nix should implicitly inherit from the parent shell.
