### ISSUE TITLE
404 error with `fetchFromGitLab`

### ISSUE THREAD

**Issue by sballert** [NixOS/nixpkgs#48215]
## Issue description
I try to install emacs with the `shrink-path` package from melpa, which uses `fetchFromGitLab` to get the source, but it results in the following error:

`curl: (22) The requested URL returned error: 404 Not Found`
`error: cannot download source from any mirror`

When I use another emacs melpa package that uses `fetchFromGitLab` (e.g. `csv`), it results in the same error. 

### Steps to reproduce
I use the following nix expression:

```
{ pkgs ? import <nixpkgs> {} }:

let
  myEmacs = pkgs.emacs;
  emacsWithPackages = (pkgs.emacsPackagesNgGen myEmacs).emacsWithPackages;
in
  emacsWithPackages (epkgs: (with epkgs.melpaPackages; [
    shrink-path
  ]))
```

`https://gitlab.com/api/v4/projects/bennya%2Fshrink-path.el/repository/archive.tar.gz?sha=a94c80743280fe317cf56cd4d4cd6385ce9e3dfb` is the used source url of the package.

`curl https://gitlab.com/api/v4/projects/bennya%2Fshrink-path.el/repository/archive.tar.gz?sha=a94c80743280fe317cf56cd4d4cd6385ce9e3dfb` results also in a 404 error.

## Technical details

This is the expression that generates the url in `fetchFromGitLab`. Maybe this is wrong, but I don't know how to fix it.

`url = "https://${domain}/api/v4/projects/${lib.optionalString (group != null) "${group}%2F"}${owner}%2F${repo}/repository/archive.tar.gz?sha=${rev}";`

Output of `nix-shell -p nix-info --run "nix-info -m"`:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Infinisil** [comment]
Looks like a GitLab issue. There's some similar sounding issues, https://gitlab.com/gitlab-org/gitlab-ce/issues/47336#note_103430000

**Comment by sballert** [comment]
The Problem is the dot in the repository name. There is already an existing issue https://gitlab.com/gitlab-org/gitlab-ce/issues/38537. I think this issue can be closed then.

**Comment by puffnfresh** [comment]
Until that is fixed, we should either:

* Mark shrink-path as broken
* Change its URL to a mirror
