### ISSUE TITLE
AMI release for 18.09

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#48222]
## Issue description

We don't seem to have AMIs for NixOS 18.09. Have these been released?

 - [x] Upload AMIs
 - [x] Add AMI's to master branch `nixos/modules/virtualisation/ec2-amis.nix`
 - [ ] Backport to release-18.09

### Steps to reproduce

Have a look at [nixpkgs master](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix#L260)

This solves out of memory errors during copy-closure during deployment.

**Comment by roberth** [comment]
@vcunat do you think this should be added to the [release process](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/development/releases.xml)?

**Comment by roberth** [comment]
Looks like they [are "advertised"](https://nixos.org/nixos/manual/#sec-obtaining).
They are also important for correct operation of NixOps on AWS.

**Comment by edolstra** [comment]
Sorry, didn't see this before. I'll generate new AMIs.

**Comment by c0bw3b** [comment]
@roberth 47dfe25e1b17cd405b81052ffcdab6ca92b467fa should have taken care of this
\+ website is up-to-date

**Comment by vcunat** [comment]
And b5380ae736 on 18.09.  Thanks everyone!
