### ISSUE TITLE
Suggestion: Waffle.io for project kanban?

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#48254]
I recently discovered [waffle.io](https://waffle.io/) and found it very interesting service/tool to organize and coordinate a project in GitHub in kanban style. It is a bit similar to Projects in GitHub but much more feature-rich. One can use GitHub as before and waffle could already help a lot to get the big picture and organize cards. But it is also possible to define dependencies and groups to perhaps get better organization of the cards. I think it could be a great tool to see what's going on, what needs to be done, what's the progress etc.

Perhaps this isn't something that you find useful or you're already using some much better solution but I just wanted to bring it to your attention in case it is something you would find helpful.

Disclaimer: I noticed that the site was hacked a week ago or so. If connecting nixpkgs with waffle, I would maybe consider creating some specific dummy account for that purpose and giving only the minimal required permissions for that dummy account.

**Comment by Ma27** [comment]
I don't know if they changed their implementation, but they used to track the issue's status using labels and on GitHub only collaborators can add/change labels on issues, so only the NixOS/nixpkgs maintainers with access to the repository will benefit from this.

**Comment by jluttine** [comment]
Others can use it see the "status" of the project and understand what's happening in the bigger picture. But, yes, it would mainly serve those who maintain or coordinate the maintenance of NixOS/nixpkgs. I don't know how they currently keep track of all open issues and pull requests and which require reaction and who should do what etc. Also, for instance, if I now wanted to contribute something and started looking at issues for each I could contribute, I'd find the GitHub issue interface very cumbersome to get any understanding about the situation.

Comments in PRs/issues can be used to define various dependencies and groupings, so that is possible for anyone. I'm not very familiar with waffle because I haven't used it myself at all, I just found it a few weeks ago.

But yes, it is mainly a tool for those who maintain NixOS/nixpkgs but it might provide useful and interesting information for others too. If it is not something they find useful, then of course, it doesn't make sense. So this is just a suggestion that I thought could potentially be extremely useful.

**Comment by jluttine** [comment]
Waffle.io is dead.
