### ISSUE TITLE
gnome3 loses contents of "default" profile

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#48255]
My NixOS system has plenty of packages installed in `/nix/var/nix/profiles/default`. This used to work fine, i.e. the GNOME3 desktop always found those applications. After the recent switch to gdm, however, I regularly log in and all those applications have disappeared from the applications menu. At that point, the only thing that appears to help is to reboot the machine. Once the machine has restarted, all applications from that profile are visible again.

I use a current version of `nixos-unstable` @ 0a7e258012b.

**Comment by jtojnar** [comment]
I would say that has something to do with the way environment variables are set. I think I experience the same issue after restarting `display-manager.service`. 

cc @hedning, @oxij who touched that code in https://github.com/NixOS/nixpkgs/pull/45784

**Comment by oxij** [comment]
I don't see how #45784 could have broken something in such a non-deterministic way that reboots would help. That would be truly mysterious.

But assuming it did, does reverting it help in a deterministic way?

**Comment by hedning** [comment]
OK, I think I've figured things out somewhat. Reverting #45784 does indeed fix the issue. Using lightdm also avoids it.

The main ingredients:
- GDM imports a base environment for the user from systemd (ie. `systemctl --user show-environment`)
- GDM for some reason resets PATH when creating the environment for a session
- Gnome sessions exports its environment to systemd
- ssh/console log in persists the systemd --user process

So logging into a gnome session will populate the systemd user environment including `__NIXOS_SET_ENVIRONMENT_DONE=1`. Logging out of the gnome session while the same user is logged in with eg. ssh won't clear the systemd environment. Launching a new session will then have a good environment, but GDM comes in and clobbers PATH making the bug manifest.

I'd say the main problem here is GDM clobbering PATH.

**Comment by hedning** [comment]
The easiest fix might be to patch gdm to reset `__NIXOS_SET_ENVIRONMENT_DONE` when setting up the base environment for a new session. This has the benefit of redoing the environment in case the system have been rebuilt compared to eg. just fixing PATH. (I have a working patch for this).

An alternative would be to run `/etc/set-environment` manually in `xsession-wrapper`, but that will just force us to patch `gnome-session` when adding wayland support, so I don't quite see the point.

Reworking #45784 is possible, but might get kinda ugly. It would probably require us to force a reset of the environment when setting up login shells. That was the direction I took when making the shell environment fix in the first place, but the whole thing got quite complicated resulting the simpler fix.

Any preferences?
