### ISSUE TITLE
nix command shouldn't print escape sequence if $TERM is set to dumb

### ISSUE THREAD

**Issue by lufia** [NixOS/nixpkgs#48250]
## Issue description

Typically, if *TERM* environment variable is set to **dumb**, then some commands should not print escape sequence such as `ESC[31m`, `ESC[0m`.
`nix search` prints escape sequence even if set `TERM=dumb`.

### Steps to reproduce

```console
$ export TERM=dumb
$ nix search ansible
* ESC[0;1mnixpkgs.ESC[31;1mansibleESC[0;1mESC[0m (ESC[0;2mpython2.7-ESC[31;1mansibleESC[0;2mESC[0m)
  A simple automation tool

* ESC[0;1mnixpkgs.ESC[31;1mansibleESC[0;1m-lintESC[0m (ESC[0;2mpython2.7-
ESC[31;1mansibleESC[0;2m-lintESC[0m)
  Best practices checker for ESC[31;1mAnsibleESC[0m
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.0.0, macOS 10.14`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(kadota): `"nixpkgs-19.03pre154968.20249caf14e"`
 - nixpkgs: `/Users/kadota/.nix-defexpr/channels/nixpkgs`

**Comment by dtzWill** [comment]
Yep, please file over there! Hopefully isn't difficult to fix (without resorting to anything heavy-handed like termcap lookups... :)).

**Comment by lufia** [comment]
Thank you.
I will post this issue to nix repository.
