### ISSUE TITLE
musl packages cannot be cross-compiled

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#48265]
## Issue description

musl packages cannot be cross-compiled

### Steps to reproduce

@GrahamcOfBorg build pkgsCross.aarch64-multiplatform.pkgsMusl.busybox
fails on ```x86_64-linux``` with ```a 'aarch64-linux' is required to build ....```

https://github.com/NixOS/nixpkgs/pull/48246#issuecomment-429308419

**Comment by matthewbauer** [comment]
This might be more related to how pkgsMusl works than anything. While in theory it should work, you should have a much better time if you skip the two step process and do:

pkgsCross.aarch64-multiplatform-musl.buxybox

This should be much quicker.

**Comment by volth** [comment]
>> pkgsCross.aarch64-multiplatform-musl.busybox
> This avoids duplicating the cross steps.

It is not always possible to do this.
The full case which I have this problem: ```aarch64-multiplatform``` is ```crossSystem``` of the whole closure, which contains some ```musl``` programs (for example ```pkgsMusl.perl``` in initrd)

**Comment by matthewbauer** [comment]
Maybe try changing stdenv.hostPlatform to super.stdenv.hostPlatform here:

```
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/stage.nix#L136
```

**Comment by dtzWill** [comment]
For what it's worth, I don't think chaining any of the "pkgs*" really "works", unfortunately.  I want to say this was discussed when introduced but can't find it now :3.

Cool that you're using musl packages though! :grin:.  Hopefully we can get things working for you, but sounds more like general Nixpkgs build infrastructure problem vs musl-specific? Well other than you want to cross AND musl ;).

**Comment by matthewbauer** [comment]
I though pkgsMusl -> pkgsCross should work (just uses a musl-based toolchain)
