### ISSUE TITLE
Live CD on USB stick doesn't work on Mac

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#4828]
The 14.11 LiveCD, when written to a USB stick using the instructions at https://nixos.org/wiki/Installing_NixOS_from_a_USB_stick#Hybrid_image, doesn't boot. Holding Option at restart time doesn't show the USB disk as an option in the list.

Disk Utility says that the USB stick doesn't have a partition scheme, although the hybrid ISO is supposed to have one?

What does make it visible in the boot loader, is formatting a USB stick with GUID partition table and ExFAT, and copying the ISO contents onto it. I suppose that could be the permanent workaround?

Cc: @lethalman @bobvanderlinden @copumpkin

**Comment by mogorman** [comment]
the 15.09 version does not have these problems can we close this issue?

**Comment by bobvanderlinden** [comment]
This issue was brought up after #4678 was merged. I'd guess it is solved already.
The automated tests at least give an indication whether QEmu can boot from USB and CD on Uefi and legacy bios. All tests pass: http://hydra.nixos.org/eval/1236697?filter=nixos.tests.boot&compare=1236445&full=

**Comment by davidak** [comment]
I successfully booted NixOS 16.03 from a USB-stick created with dd on a MacBook.

**Comment by bobvanderlinden** [comment]
@davidak Thanks for the feedback. Just to have enough information for potential future boot problems, which MacBook did you try it on?

Apart form that, I would think this can be closed. @wmertens, agreed?

**Comment by wmertens** [comment]
Agreed! Thanks all! 🍻

**Comment by davidak** [comment]
@bobvanderlinden MacBook Pro Retina, 13", Ende 2012
