### ISSUE TITLE
zeromq4-haskell fails tests, fails to install on 18.09

### ISSUE THREAD

**Issue by GallagherCommaJack** [NixOS/nixpkgs#48296]
## Issue description
Tried to install ihaskell, it reliably fails to build due to zeromq4-haskell failing tests.
I was able to install on a machine running 18.03, but on my 18.09 machine it fails.
Output from the attempt [here](https://gist.github.com/GallagherCommaJack/0df39a26dba7331086ecc70c81baa74a)

### Steps to reproduce
`nix-shell -p haskellPackages.zeromq4-haskell`

## Technical details

nix-info results:
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.809.de37b4c18c0 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(jack): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by GallagherCommaJack** [comment]
Closing this issue - build succeeds after `nix-channel --update`

**Comment by alexvorobiev** [comment]
I am getting this error with the latest unstable channel.

**Comment by GallagherCommaJack** [comment]
I'm getting it on latest 18.09 too.

**Comment by rightfold** [comment]
Relevant issue: https://gitlab.com/twittner/zeromq-haskell/issues/63

**Comment by sorki** [comment]
Resolved upstream.
