### ISSUE TITLE
Upgrade xmr-stak to v2.5.0 urgent

### ISSUE THREAD

**Issue by kim0** [NixOS/nixpkgs#48294]
## Issue description
Monero is hardforking and changing the proof of work. xmr-stak must be upgraded to v2.5.0 before the 18th of Oct (Thu), or it will stop working

Thanks @fpletz

**Comment by kim0** [comment]
Thanks @rnhmjoj & @fpletz .. When can we expect this to land ? Thanks

**Comment by rnhmjoj** [comment]
It should be ready to merge already.
