### ISSUE TITLE
pantsbuild.pants-1.7.0 raise exception "invalid ELF header"

### ISSUE THREAD

**Issue by lgirault** [NixOS/nixpkgs#48300]
## Issue description
When trying to use pants with a command such as `pants goals`, I get 
```
Exception caught: (<type 'exceptions.ImportError'>)

Exception message: /tmp/tmpZpQw47/native_engine.so: invalid ELF header
```
### Steps to reproduce
nix-env -iA nixos.pants
touch pants
pants goals 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b"`
 - channels(lorilan): `"nixpkgs-18.09pre149508.5cb9703a8fa"`
 - nixpkgs: `/home/lorilan/.nix-defexpr/channels/nixpkgs`

**Comment by FliegendeWurst** [comment]
Package was removed in #152907
