### ISSUE TITLE
`vulkan-loader` doesn't build and breaks nixos-19.03pre155110.60ae563293e

### ISSUE THREAD

**Issue by chisui** [NixOS/nixpkgs#48311]
## Issue description

On the current `nixos-unstable-small` channel `vulkan-loader` doesn't build because of an assertion error. This prevents system upgrades altogether.

### Steps to reproduce

On the current `nixos-unstable-small` channel

```sh
$ sudo -i nixos-rebuild switch --upgrade
unpacking channels...
building Nix...
building the system configuration...
error: assertion failed at /nix/store/xlmja9agydii8nazmp5c9n40573kdpys-nixos-19.03pre155260.276b99a847e/nixos/pkgs/development/libraries/vulkan-loader/default.nix:4:1
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.75, NixOS, 19.03pre155110.60ae563293e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(chisui): `""`
 - channels(root): `"nixos-19.03pre155260.276b99a847e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by xeji** [comment]
vulkan-headers auto-update was reverted in ac6f4851480e3a7016a2257a62c34ed46dcea789, so this
should be fixed when the channel advances.

**Comment by fpletz** [comment]
I've just checked both packages. We might get away with just removing the assertion as it seems not to hold in general. It was only added in the last version bump.

**Comment by yegortimoshenko** [comment]
Oops, just merged bae3fd3d83cc9f227ae7974c32506afdda103ea6 which fixes vulkan-loader. @xeji, do you think I can re-revert https://github.com/NixOS/nixpkgs/commit/ac6f4851480e3a7016a2257a62c34ed46dcea789?

**Comment by yegortimoshenko** [comment]
Re-reverted in 45351e6916ac56a04b633b445e5f42a357d0437e, both packages are now on 1.1.85:

```
$ nix-build . -A vulkan-headers -A vulkan-loader
/nix/store/82b2k5ij7y6pibibb5gjgmn760bj30lp-vulkan-headers-1.1.85
/nix/store/s1vm5zzqgbmbi7idhl3znyw2gv9yk0nb-vulkan-loader-1.1.85
```

**Comment by xeji** [comment]
Thanks @yegortimoshenko  !

**Comment by matthew-piziak** [comment]
This is back today on the most recent `nixos-unstable-small`.

**Comment by jpotier** [comment]
Just ran into this too.

```
{
  "url": "https://github.com/NixOS/nixpkgs-channels",
  "rev": "fab6d810b5ac32f6d20fa2a77b97e8fbe0ffbd90",
  "date": "2019-04-18T10:14:50+02:00",
  "sha256": "1k5sgd3s6b1ka7fpssc0h8xv6jmgx7lfc8myczhsa1vkmga2kwvh",
  "fetchSubmodules": false
}
```
