### ISSUE TITLE
fwupd: Daemon configuration not found

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#48425]
## Issue description

`fwupd` tries to find the `daemon.conf` in the wrong path

```
Oct 14 19:13:02 ryzen .fwupd-wrapped[31046]: Daemon configuration /nix/store/r7xyjbgqzvzhd5m4i6mz0zdmh60vz4kp-fwupd-1.1.1/etc/fwupd/daemon.conf not found
^C
```

### Steps to reproduce
```
services.fwupd.enable  = true;
```

Type
```
sudo fwupdmgr get-devices
```
First time it works, second time it times out.

`fwupd` now starts spamming that it can't find the daemon config to the logs

## Technical details

```[arian@ryzen:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.12, NixOS, 18.09.884.d96c7a35638 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.884.d96c7a35638"`
 - channels(arian): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by davidak** [comment]
Still reproducible on 18.09.1829.0396345b794.

Can the fix (update) get backported?

**Comment by jtojnar** [comment]
This is not trivially backportable because it requires update of Meson and other packages.

**Comment by davidak** [comment]
OK for me. fwupd actually can't update my devices.
