### ISSUE TITLE
Gnome3 - Can't login google-account with online-accounts

### ISSUE THREAD

**Issue by bavramor** [NixOS/nixpkgs#48424]
## Issue description
When I try to log in to google under gnome-online-accounts, I can't see the login screen at all. The facebook login works, however. You can see this in my screenshots.

### Steps to reproduce
Users in gnome3 go to system settings, then go to online accounts and try to set up a google account. You can see the result in my screenshots.

## Technical details
GNOME Shell 3.28.3

![facebook-login](https://user-images.githubusercontent.com/1936649/46919796-f255c300-cfe4-11e8-95ce-f6b291f74fe6.png)
![google-login](https://user-images.githubusercontent.com/1936649/46919797-f255c300-cfe4-11e8-8775-91dd890ae0e2.png)

**Comment by jtojnar** [comment]
Do you use nVidia? It might be caused by https://github.com/NixOS/nixpkgs/issues/32580

**Comment by baracoder** [comment]
If you really want to, it is still possible: The fields are still there and you might see your mouse cursor change.  If you select all and drag it, you see the placement of the fields and buttons.

**Comment by bavramor** [comment]
Yes, I am using Nvidia. This helps: [#32580](https://github.com/NixOS/nixpkgs/issues/32580)
Thanks so much! This works:
{
environment.variables.WEBKIT_DISABLE_COMPOSITING_MODE = "1";
}

**Comment by jtojnar** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/32580
