### ISSUE TITLE
`signal-desktop` unstable version has expired

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#48436]
## Issue description

`signal-desktop` reports
> This version of Signal Desktop has expired. Please upgrade to the latest version to continue messaging."

### Steps to reproduce

Update `unstable` channel. Install `signal-desktop` on `unstable` channel. Run `signal-desktop`. See error message at top of screen.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.19, NixOS, 18.03.133308.e85e0c2cafd (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133308.e85e0c2cafd, unstable-19.03pre155123.32bcd72bf28"`
 - channels(matt): `"unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixpkgs`
```

**Comment by xeji** [comment]
cc maintainers @ixmatus @primeos

**Comment by primeos** [comment]
@matthew-piziak Thanks, I'll have a look. I assume that this is the version from the `18.03` channel though, the version from `19.03` and `nixos-unstable` should be recent enough. Wasn't aware that upstream deprecates old versions that fast...

**Comment by matthew-piziak** [comment]
@primeos This is on `unstable-19.03pre155123.32bcd72bf28`. Thanks for taking a look!

**Comment by matthew-piziak** [comment]
I get `/nix/store/nrc6psprb64nfvqmjkl84hz26v5mrkpx-signal-desktop-1.16.2/libexec/signal-desktop`.

**Comment by primeos** [comment]
That's strange...
Signal-Desktop 1.16.2 is the most recent (stable) version (https://github.com/signalapp/Signal-Desktop/releases/tag/v1.16.2). Do you still get that message if you execute `/nix/store/nrc6psprb64nfvqmjkl84hz26v5mrkpx-signal-desktop-1.16.2/libexec/signal-desktop` directly?

**Comment by matthew-piziak** [comment]
Whoops!! Running the binary directly works. Must be a stale shortcut in Xfce. Sorry about that! Closing now.

**Comment by primeos** [comment]
@matthew-piziak No problem and thanks for your report, I've backported 1.16.2 to `18.03` so it was still very helpful :)
