### ISSUE TITLE
FreeCAD narrowly misses the path of its help database

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#48448]
## Issue description

FreeCAD can't find its "help files", which it expects to be at the path `/nix/store/…-freecad-0.17/doc/freecad.qhc`. However, there is an SQLite database at the path `/nix/store/…-freecad-0.17/share/doc/freecad.qhc`, which I assume is the file FreeCAD wants.

(Edit: The correct path is `…/share/doc/freecad.qhc`, not `…/store/doc/freecad.qhc`.)

### Steps to reproduce

In FreeCAD, open the "Help" menu and select "Help". A message box should appear, saying "FreeCAD help files not found [...]".

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 19.03pre155123.32bcd72bf28 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre155123.32bcd72bf28"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lschuermann** [comment]
I can confirm the bug, looking into possible solutions.

**Comment by lschuermann** [comment]
My netbook can't build FreeCAD, so I'll need a few more days to work with a bigger machine. I guess we could just move the help database somewhere in the install-phase.

**Comment by luzpaz** [comment]
Docs have been separated out. 
Checkout the PPA https://launchpad.net/~freecad-community/+archive/ubuntu/ppa/+packages

**Comment by vcunat** [comment]
Fixed by #62442.
