### ISSUE TITLE
How to enforce ordering of programs.ssh.extraConfig ?

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#48456]
## Issue description

The ssh-config is not a commutative monoid,   You can't combine them in
arbitrary ways to get a valid config  
But currently they are considered like that ,and the configs get merged to a single string if
you define `programs.ssh.extraConfig` in multiple modules.
(e.g. https://unix.stackexchange.com/questions/16571/multiple-host-in-ssh-config).

Another example:

This 
```
Port 22
# merge happens here
Host github.com
Hostname ssh.github.com
Port 443
```

Is very different from:

```

Host github.com
Hostname ssh.github.com
Port 443
# merge happens here
Port 22
```

Is there a way we can force ordering of the `extraConfig` directives, such that when merging,
stuff from a certain modules `X` is always above stuff from another module `Y`? Are there
other examples of config files where these priorities matter?

**Comment by joachifm** [comment]
Have you looked at `mkOrder`? I don't know that it really scales but seems relevant nonetheless.

**Comment by arianvp** [comment]
Yes this seems to exactly solve the issue https://github.com/NixOS/nixpkgs/issues/1616
