### ISSUE TITLE
Dead URL for postman-6.25 on 18.09

### ISSUE THREAD

**Issue by Hodapp87** [NixOS/nixpkgs#48466]
## Issue description

Trying to install `postman` yields an error like this on 18.09:

```
installing 'postman-6.2.5'
these derivations will be built:
  /nix/store/6jqig7lnby1fms0v7ipbxmbcgk3y9j8m-postman-6.2.5.tar.gz.drv
  /nix/store/6iwyi7bccgcvrv67gfp6gzhpdf8hlfi5-postman-6.2.5.drv
building '/nix/store/6jqig7lnby1fms0v7ipbxmbcgk3y9j8m-postman-6.2.5.tar.gz.drv'...

trying https://dl.pstmn.io/download/version/6.2.5/linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download postman-6.2.5.tar.gz from any mirror
builder for '/nix/store/6jqig7lnby1fms0v7ipbxmbcgk3y9j8m-postman-6.2.5.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/6iwyi7bccgcvrv67gfp6gzhpdf8hlfi5-postman-6.2.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6iwyi7bccgcvrv67gfp6gzhpdf8hlfi5-postman-6.2.5.drv' failed
```

The issue doesn't appear on current Nixpkgs master, which uses 6.3.0 rather than 6.2.5, and the https://dl.pstmn.io/download/version/6.3.0/linux64 link is still valid.

### Steps to reproduce

`nix-env -i postman`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.821.4dd9cd3f69e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09"`
 - channels(hodapp): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by arianvp** [comment]
Was fixed here: https://github.com/NixOS/nixpkgs/pull/46771

Perhaps we can backport?
