### ISSUE TITLE
Uninformative error "operation is only supported by LocalStore" after 17.09->18.09 upgrade

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#48470]
## Issue description

After updating from 17.09 to 18.09, nix-env stopped working with a mysterious error message. ~~I resolved the problem by adding `trusted-users = james` (`james` is the user I run nix-env as) to `/etc/nix/nix.conf`.~~ EDIT: Actually, that didn't fix it; see next comment.

This is part bug report (the error message is kind of useless) and part question (~~what changed between 17.09 and 18.09?~~ how do I get it working again?).

Note 1: I'm running nix on Debian. My installation is intended to be multi-user, but it's likely something isn't quite right about it. E.g. after updating 17.09->18.09, `$HOME/.nix-profile/etc/profile.d/nix.sh`, which is called from my `.profile`, started complaining that it couldn't create `/nix/var/nix/gcroots/per-user/james`; I ended up having to manually create and chmodding that per-user directory.

Note 2: I didn't have this trouble after upgrading from nix 1 to nix 2. Specifically, as part of the 17.09->18.09 upgrade, I changed nix to nixStable2 in my package configuration, ran nix-env -u, and restarted nix-daemon*, and I didn't run into this problem. It only happened after I pulled the 18.09 channel, ran nix-env --always -u, and restarted nix-daemon again.

So, here's what happened after updating to 18:09: If I ran the command `nix-env --show-trace --always -u \* 2> tmp/f > tmp/f`, the contents of tmp/f were as as shown at the bottom of this post. Specifically, it ended in `error: operation is only supported by LocalStore`

After searching for similar issues, I tried adding myself as a trusted user ~~and the problem went away.  I don't understand why, though --- I thought this is only needed when running non-sandboxed bulids, and as far as I am aware, I haven't explicitly turned off sandboxing anywhere.~~ EDIT: no, it didn't go away; see next comment.

*I run nix-daemon by running 'sudo -E env PATH="$PATH" nix-daemon' as my non-root user.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```james copter ~ $ nix-shell -p nix-info --run "nix-info -m"
warning: unknown setting 'build-cache-failure'
warning: unknown setting 'signed-binary-caches'
warning: Nix search path entry '/home/james/.nix-defexpr/channels/nixpkgs' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
```

Trying again with `NIX_PATH` set:

```james copter ~ $ NIX_PATH=$HOME/.nix-defexpr/channels/nixos-18.09 nix-shell -p nix-info --run "nix-info -m"
warning: unknown setting 'build-cache-failure'
warning: unknown setting 'signed-binary-caches'
error: operation is only supported by LocalStore
(use '--show-trace' to show detailed location information)
```

(Note: that's not the only channel I have configured:

```james copter ~ $ ls .nix-defexpr/channels
binary-caches  manifest.nix  nixos-18.09  nixos-unstable
```
)

--- BEGIN output of nix-env

warning: unknown setting 'build-cache-failure'
warning: unknown setting 'signed-binary-caches'
error: while evaluating 'callPackageWith' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:108:35, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:470:9:
while evaluating 'makeOverridable' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:67:24, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:112:8:
while evaluating anonymous function at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/tools/security/afl/default.nix:1:1, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:69:12:
while evaluating the attribute 'cc.isClang' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/generic/default.nix:148:14:
while evaluating the attribute 'gcc' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:279:7:
while evaluating 'makeOverridable' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:67:24, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:279:13:
while evaluating anonymous function at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/build-support/cc-wrapper/default.nix:8:1, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:69:12:
while evaluating the attribute 'gcc-unwrapped' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:247:7:
while evaluating the attribute 'gcc-unwrapped.override' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:6528:3:
while evaluating 'lowPrio' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/meta.nix:52:13, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:6668:10:
while evaluating 'addMetaAttrs' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/meta.nix:15:28, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/meta.nix:52:18:
while evaluating 'wrapCC' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:7446:12, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:6668:19:
while evaluating 'wrapCCWith' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:7425:5, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:7446:16:
while evaluating 'callPackageWith' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:108:35, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:7434:7:
while evaluating 'makeOverridable' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:67:24, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:112:8:
while evaluating anonymous function at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/build-support/cc-wrapper/default.nix:8:1, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:69:12:
while evaluating the attribute 'cc.nativeTools' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/generic/default.nix:148:14:
while evaluating 'makeOverridable' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:67:24, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:92:19:
while evaluating anonymous function at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/build-support/cc-wrapper/default.nix:8:1, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:69:12:
while evaluating the attribute 'binutils' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:219:7:
while evaluating the attribute 'binutils.override' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:191:7:
while evaluating the attribute 'binutils_nogold' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:8113:3:
while evaluating 'lowPrio' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/meta.nix:52:13, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:8113:21:
while evaluating 'addMetaAttrs' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/meta.nix:15:28, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/meta.nix:52:18:
while evaluating 'wrapBintoolsWith' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:7451:5, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:8113:30:
while evaluating 'callPackageWith' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:108:35, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/top-level/all-packages.nix:7455:7:
while evaluating 'makeOverridable' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:67:24, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:112:8:
while evaluating anonymous function at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/build-support/bintools-wrapper/default.nix:8:1, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:69:12:
while evaluating the attribute 'cc.nativeTools' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/generic/default.nix:148:14:
while evaluating 'makeOverridable' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:67:24, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/linux/default.nix:92:19:
while evaluating anonymous function at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/build-support/cc-wrapper/default.nix:8:1, called from /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/lib/customisation.nix:69:12:
while evaluating the attribute 'args' of the derivation 'bootstrap-stage0-glibc' at /nix/store/jq2zax1hqmv6swj6kk6cnaq9rx8az1s7-nixos-unstable-19.03pre155123.32bcd72bf28/nixos-unstable/pkgs/stdenv/generic/make-derivation.nix:177:11:
operation is only supported by LocalStore

---- END contents of nix-env

**Comment by falsifian** [comment]
Whoops, actually, adding myself as a trusted user didn't work (I confused myself by redirecting the error output to a file). So I don't know how to get nix-env working now.

**Comment by falsifian** [comment]
Added output of `nix-info` as requested by the issue template.

**Comment by falsifian** [comment]
Removing nix-unstable from my nix channels seems to have fixed the problem.

**Comment by falsifian** [comment]
Er, never mind. After removing the unstable channel, I now see the forking behaviour of https://github.com/NixOS/nixpkgs/issues/48470#issuecomment-431719519 when I try to update packages with `nix-env -u --always --no-build-output \*`, instead of the `operation is only supported by LocalStore` error.

**Comment by prusnak** [comment]
@falsifian Is this still a problem?

**Comment by falsifian** [comment]
I re-installed nix on that machine, which fixed the problem, so I'm unfortunately unable to reproduce. I'll close this bug, but if anyone sees a similar issue maybe it could be re-opened. Thanks for checking in, @prusnak.
