### ISSUE TITLE
exa package is broken on nixos 18.09 channel

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nixpkgs#48489]
## Issue description
exa is not in path after installation on nixos 18.09. For some reason the binary ends up in the $out/lib directory instead of the $out/bin directory after installation. I was using nixos unstable until recently and this was not an issue there. This only seems to affect the latest release branch which is odd because the package has no major changes. 

I built the packages locally (without cache.nixos.org) just to test. Exa from "master" builds correctly, as does the "unstable-aarch64" branch and "release-18.03", but when I build it from the "release-18.09" branch I had the same result as described above. It must be caused by some change in the dependencies because the package has not changed from the "release-18.09" branch to the "master" branch.

### Steps to reproduce
Install exa from the nixos-18.09 channel and it will not be in your path. The binary will be located in /nix/store/$out/lib/exa instead

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.14, NixOS, 18.09.892.c06f5302f63 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(nrd): `"nixos-18.09.892.c06f5302f63"`
 - nixpkgs: `/home/nrd/.nix-defexpr/channels/nixos`

**Comment by erictapen** [comment]
This affected both master and nixos-18.09, see the fix in https://github.com/NixOS/nixpkgs/pull/48020.

You don't see this issue on master or nixos-unstable, as the fix is
already present on these branches/channels.

The fix requires a lot of rebuilds. For that it was applied to the
staging-18.09 branch and it looks like this branch wasn't merged into
release-18.09 yet.

**Comment by xeji** [comment]
The fix was merged to `staging-18.09` first because it causes a mass rebuild. We typically bundle several mass rebuilding changes and wait for the rebuilds to finish and succeed on `staging-18.09` before we merge them into `release-18.09`. This may take some time, please be patient.

**Comment by nrdxp** [comment]
Awesome I will go ahead and close the issue then. Much appreciated.

**Comment by petabyteboy** [comment]
This issue is still present.

**Comment by erictapen** [comment]
@petabyteboy Could you elaborate? I can't verify this on `nixos-18.09` as well as on `nixos-unstable`.

```shell
$ nix build nixpkgs.exa

$ exa -la result/bin/
.r-xr-xr-x 1.7M root  1 Jan  1970 exa
```

**Comment by petabyteboy** [comment]
Yesterday I installed a fresh 18.09 system and wondered why I couldn't use exa, and found that the binary was installed in lib/ instead of bin/. 
After rebuilding my systems today, everything works as expected.

**Comment by vcunat** [comment]
Right, installing from some older ISOs would still do that normally, I think.  It wouldn't have to be very old, due to the fix getting temporarily reverted by accident on 18.09 and re-added later #51281.
