### ISSUE TITLE
Document how to change a pr from master to staging

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#48491]
## Issue description

We often have contributors, who don't know how to switch a branch from master to staging.
We should add some documentation how to do that by rebasing and force pushing.
Examples:

 - https://github.com/NixOS/nixpkgs/pull/48471
 - https://github.com/NixOS/nixpkgs/pull/48434

**Comment by volth** [comment]
this https://stackoverflow.com/questions/10853935/change-branch-base ?

**Comment by Mic92** [comment]
Yes.

**Comment by Mic92** [comment]
Some of these might be also interesting for users: https://github.com/k88hudson/git-flight-rules

**Comment by Mic92** [comment]
I guess this could be added to [doc/submitting-changes.xml](https://github.com/NixOS/nixpkgs/blob/master/doc/submitting-changes.xml)

**Comment by Mic92** [comment]
it is still relevant.

**Comment by Mic92** [comment]
it is still relevant.
