### ISSUE TITLE
pythonPackages.libxml2: need Python3 support

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#48490]
## Issue description

For some reason ```pythonPackages.libxml2``` is available only for Python2
https://github.com/NixOS/nixpkgs/blob/8099538634718a5de81982e99d1522b797b4a84c/pkgs/top-level/python-packages.nix#L6512-L6513

It prevents updating of ```virt-manager``` as its new version (```2.0.0```) requires both ```Python3``` and ```pythonPackages.libxml2```

@FRidh

**Comment by FRidh** [comment]
I don't know whether/when libxml2 added Python 3 support.

**Comment by FRidh** [comment]
If it can handle Python 3, we should also use it by default.
