### ISSUE TITLE
Don't conflate depdencies in `setup.sh`

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#4855]
We currently have the confusing situation that the `buildInputs` attribute gets passed to the builder via the `nativeBuildInputs` environment variable:

```
$ nix-shell '<nixpkgs>' -A pan
[nix-shell:~]$ echo $buildInputs 

[nix-shell:~]$ echo $nativeBuildInputs 
/nix/store/aprw7bdaydpxcv6j3wlr9bnr2s061gq6-pkg-config-0.23 /nix/store/75kv0ac0zn6sxypqh4anwwfdmm3bcw35-gtk+-2.24.24 ...
```

(Pan declares a `buildInputs` attribute.)

Also, "native" is somewhat ambiguous: native to the build machine, or native to the target machine? However the GNU terminology (`build` and `host`) is not really better.

Maybe it would be better to always use `buildInputs` for the native (build machine) dependencies, and something like `targetBuildInputs` for the cross-built dependencies. Or not use `buildInputs` in setup.sh at all and use `nativeBuildInputs` and `targetBuildInputs` to prevent confusion.

Ping @viric

**Comment by iElectric** [comment]
Relevant: http://lists.science.uu.nl/pipermail/nix-dev/2015-March/016452.html

**Comment by edolstra** [comment]
To be honest, I think that renaming is going to cause too much work/breakage at this point. For the overrideDerivation issue, it would be enough to move the concatenating of `buildInputs` to `nativeBuildInputs` into the generic builder script.

**Comment by bjornfor** [comment]
Oh, don't say that! :-) What kind of breakage? Internal to nixpkgs or for users with out-of-tree expressions?

I'm very much in favor of a rename, some time in the future.

**Comment by akaWolf** [comment]
Any progress?

**Comment by lethalman** [comment]
Alternative thinking. Because packages like flex, pkgconfig, ecc. are usually (or always) used as nativeBuildInputs, what about setting for them a nix-support/native-build-input ?

We get rid of native vs cross build inputs, and instead each package declare itself as native vs cross build input, or in general its role in the build process.

Otherwise it's a maintainance burden to understand which package goes native vs cross, or also renaming this kind of variables.

In general tools are native, libraries are cross. The multi output branch should even help with this distinction.

**Comment by edolstra** [comment]
@lethalman :+1:

**Comment by nbp** [comment]
@lethalman :+1: I think this makes sense, but you probably want to consider the lack of the file as a proof of a native packages versus a cross-compiled package,

Thus having `nix-support/host-system` which contains name of the system on which these binaries/libraries can be executed safely, might makes more sense.  Note, that having the name of the host-system is better if we want to import these packages in the nix store of another computer.

Thus the rule would be that if the file does not exists, we assume that this is the same system, and if it does, then we check against the system on which we are building.

**Comment by dezgeg** [comment]
I don't see how this could be solved via `nix-support/*` files; it definitely needs to be done on the nix expression level. Consider that when cross compiling, `nativeBuildInputs = [foo]` and `buildInputs = [foo]` cause entirely different `foo` derivations to be added as dependencies.

**Comment by bjornfor** [comment]
A data point, how the Buildroot embedded build system solve this:

Buildroot has two types of dependencies, one for normal dependencies (for the target architecture) and one for the (build) host. Both go into the same dependency list:

```
# libfoo.mk
LIBFOO_DEPENDENCIES = host-libaaa libbbb
...
```

The package "expression" for libaaa (a Makefile snippet) decides what type of packages are created:

```
# libaaa.mk
... metadata and dependency info
$(eval $(autotools-package))  # create a normal (target) package
$(eval $(host-autotools-package))  # also create a build host package
```

I like the explicitness of this approach. I'd like to see this in nixpkgs:

```
  buildInputs = [ libfoo.hostDrv libbbb ];
```

**Comment by lethalman** [comment]
@bjornfor that doesn't change much the current state, you put everything in buildInputs instead of having two sets, but that's it.

@dezgeg it does, because `bison` will always be used as host dependency, and `glib` always as target dependnecy.

**Comment by bjornfor** [comment]
But some packages can be used both as target and host inputs. So I think there is value in having explicit distinction between host/target derivations (i.e. libfoo vs libfoo.hostDrv).

**Comment by lethalman** [comment]
@bjornfor that's the exception, and we already have that... it's called `.nativeDrv`.

**Comment by lethalman** [comment]
Btw if nix-support is not suitable (perhaps because we need the native drv), we can add a meta to the derivation, and that's it, at nix level, but packages define themselves as native or not.

**Comment by twhitehead** [comment]
+1 regarding fixing the overrideDerivation behaviour.  Just finished running into this adding *libibverb* as a dependency to *openmpi* to get infiniband support.

```nix
openmpi.overrideDerivation (oldattrs: {
  buildInputs = oldattrs.buildInputs ++ [ libibverbs ];
} )
```

gave a derivation with buildInputs set to the extra *libibverbs*

```
Derive(
  ...
, [ ("buildInputs", "/home/nixbld/store/3ygnx9458la0m22m7250j2qwkrsgzbxp-libibverbs-1.1.8")
    ...
  , ("nativeBuildInputs", "/home/nixbld/store/ww3a97ggvdck01kjmlffj3wb27gg7xqr-gfortran-wrapper-4.9.3")
  ...
  ]
)
```

while directly modifying `buildInputs` in the *openmpi/default.nix* file gave a derivation with nativeBuildInputs set with the extra *libibverbs*.

```
Derive(
  ...
, [ ("buildInputs", "")
    ...
  , ("nativeBuildInputs", "/home/nixbld/store/ww3a97ggvdck01kjmlffj3wb27gg7xqr-gfortran-wrapper-4.9.3 /home/nixbld/store/3ygnx9458la0m22m7250j2qwkrsgzbxp-libibverbs-1.1.8")
   ...
  ]
)
```

**Comment by dezgeg** [comment]
AFAICT solving https://github.com/NixOS/nixpkgs/issues/10721 will solve the `overrideDerivation` problem as well.

**Comment by domenkozar** [comment]
No consensus how to move forward here, bumping milestone.

**Comment by DamienCassou** [comment]
Any news?

**Comment by domenkozar** [comment]
This won't make it to 16.09

**Comment by aneeshusa** [comment]
#18660 adds a new `overrideAttrs` function, which is essentially a fixed version of `overrideDerivation`.

**Comment by Ericson2314** [comment]
In https://github.com/NixOS/nixpkgs/pull/26805 I do add two more sorts of dependencies giving us:

| Current name | Ideal name | Host is | Target is |
|--------------------|----------------|----------|-------------|
| `preNativeBuildInputs` | `preBuildInputs` | build platform | build platform |
| `nativeBuildInputs` | `buildInputs` | build platform | host platform |
| `buildInputs` | `hostInputs` | host platform | target platform
| `__targetBuildInuts` | `__targetInputs` | target platform | target platform |

`preNativeBuildInputs` are tools used to make programs used at build time.
`-__targetBuildInputs` are packages bundled with the programs the compiler produces (e.g. std lib dependencies). Packages do not care what the build platform of the dep is, because they merely need it to exist. In practice however, the build platform of the dep is the build platform of the consumer.

With my ideal names, the name matches which platform of the consumer is the host platform of the dep.

**Comment by ip1981** [comment]
The build-host-target triad is quite clear, but `target` is not applicable to the most of software, it's only relevant to compilers:

* **build** is where we build/compile software.
* **host** is where this software will run.
* **target** is where software built by this software will run :)

E. g. we can build  GCC on linux (_build_), which will run on Windows (_host_), but compile binaries for solaris (_target_).

**Comment by Ericson2314** [comment]
@ip1981 That's all true. Precisely because "target" is not applicable to most software, yet that's not clear from the name alone, I prefixed `__targetBuildInuts` with underscores to discourage accidental use.

**Comment by Ericson2314** [comment]
N.B. Editted my table now that #26805 now introduces even more dependencies.

**Comment by dezgeg** [comment]
FWIW, the original problem (`buildInputs` attribute gets passed to the builder via the `nativeBuildInputs` environment variable) by @edolstra has been solved by #23374 and #10721 for quite a while now. Should it be time to close this and split off the other cross naming issues into separate tickets?

**Comment by Ericson2314** [comment]
@dezgeg Sure, that makes sense to me.

**Comment by Ericson2314** [comment]
Remaining bike-shed is in https://github.com/NixOS/nixpkgs/issues/28327
