### ISSUE TITLE
Missing documentation of fetchpatch

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#48569]
`fetchpatch` has only basic documentation for its [options](https://github.com/NixOS/nixpkgs/blob/88ae8f7d55efa457c95187011eb410d097108445/pkgs/build-support/fetchpatch/default.nix#L8) so far.

For example, the `stripLen` and `includes`/`excludes` options aren't documented.

That makes it very error-prone to use.

---

For example, it would be useful to know that [`stripLen` to apply `-p`](https://github.com/NixOS/nixpkgs/blob/88ae8f7d55efa457c95187011eb410d097108445/pkgs/build-support/fetchpatch/default.nix#L22) runs _before_ [`includes` to apply `-i`](https://github.com/NixOS/nixpkgs/blob/88ae8f7d55efa457c95187011eb410d097108445/pkgs/build-support/fetchpatch/default.nix#L37). That means that if you have paths like

```
a/Cabal/Distribution/Simple/Configure.hs
...
a/cabal-install/Distribution/Client/Something.hs
```

and you try to keep only the `Cabal` parts using

```
          stripLen = 2; # strips of `a/Cabal/` (the nix derivation is already built from this subdir)
          includes = ["Cabal/*"];
```

then this won't work, because `stripLen = 2;` will already strip off `a/Cabal` and `a/cabal-install`, so your `includes` won't work and there is no `includes` you could possibly write to achieve the goal.

That would be nice to know ahead of time.

**Comment by xeji** [comment]
In addition to documenting the options, some guidelines on when to use `fetchpatch` and when to add a patch to the nixpkgs repo would be helpful. This question comes up frequently in PRs.

**Comment by flokli** [comment]
I still think this should be documented.

**Comment by nh2** [comment]
still

**Comment by flokli** [comment]
@nh2 would you be up to starting a PR on what you figured out so far? Happy to review what you come up with, and add notes :-)

**Comment by doronbehar** [comment]
Here's what we have currently documented, in https://github.com/NixOS/nixpkgs/blob/c7b3272ca9541392c73525967a5bffd2f08965d2/doc/contributing/coding-conventions.chapter.md#L529-L537 :

```md
If a patch is available online but does not cleanly apply, it can be modified in some fixed ways by using additional optional arguments for `fetchpatch`:

- `stripLen`: Remove the first `stripLen` components of pathnames in the patch.
- `extraPrefix`: Prefix pathnames by this string.
- `excludes`: Exclude files matching this pattern.
- `includes`: Include only files matching this pattern.
- `revert`: Revert the patch.

Note that because the checksum is computed after applying these effects, using or modifying these arguments will have no effect unless the `sha256` argument is changed as well.
```

It seems that the options are documented now, only the detail that if `includes` is used, it is handled before `stripLen`? I didn't quiet understand what you tried to explain @nh2.

**Comment by klemensn** [comment]
> It seems that the options are documented now, only the detail that if `includes` is used, it is handled before `stripLen`? I didn't quiet understand what you tried to explain @nh2.

Documented in bf7d13dc4f54561bb2d8b026e25bda70362b789e.

**Comment by flokli** [comment]
I think the confusing part here is that the arguments for `fetchpatch` are documented in `doc/contributing/coding-conventions.chapter.md`, not `doc/builders/fetchers.chapter.md`. I'll send a PR moving it to the latter location, and a hyperlink to the former.

**Comment by flokli** [comment]
PR up at https://github.com/NixOS/nixpkgs/pull/176082, PTAL.
