### ISSUE TITLE
nfs-utils package nfsiostat is broken

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#48599]
## Issue description

The `nfsiostat` command is a Python script that has not had its `python` interpreter remapped to the Nix store path. It still shows `#!/usr/bin/python` as its hashbang.

Running it results in:

```
zsh: /run/current-system/sw/bin/nfsiostat: bad interpreter: /usr/bin/python: no such file or directory
```

### Steps to reproduce

Install `nfs-utils` package and run `nfsiostat`.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.6, Form Bay ML, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/nixpkgs`
```

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/48611
