### ISSUE TITLE
nixos-option broken on lastest ustable

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#48655]
## Issue description
```
nixos-option programs.ipfs
This attribute set contains:
error:
syntax
error,
unexpected
:,
expecting

```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6377_954d1f4d`
 - channels(root): `"nixpkgs-19.03pre154487.0a7e258012b"`
 - channels(pasquale): `"nixpkgs-19.03pre153701.46651b82b87"`
 - nixpkgs: `/home/pasquale/.nix-defexpr/channels/nixpkgs`

**Comment by coretemp** [comment]
Output on my system (`18.09.git.c06f530 (Jellyfish)`):

```
nixos-option programs.ipfs
error: attribute 'ipfs' missing
This attribute set contains:
/run/current-system/sw/bin/nixos-option: eval: line 319: syntax error near unexpected token `newline'
```

**Comment by lheckemann** [comment]
Might be a dup of #47722, which is fixed in de93b32f. You don't seem to be on the latest nixos-unstable in fact, try rerunning `sudo nixos-rebuild switch --upgrade`.

**Comment by Ma27** [comment]
@coretemp this is a known issue when you run `nixos-option <invalid-option-name>` as `ipfs` is in the `services` namespace. I filed a patch (#48153) and it would be cool if it has more testers.

**Comment by Ma27** [comment]
*ping*. #48153 has fixed the issue for me, but I really don't want to merge it without any review :)
