### ISSUE TITLE
lxterminal: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#48657]
## Issue description
Running `lxterminal` in AwesomeWM (perhaps just any WM, without a DE) and attempting to open the Color Chooser window in settings crashes all running instances of `lxterminal` with the message from the issue title:

> (lxterminal:29942): GLib-GIO-Error **: 11:44:45:567: No GSettings schemas are installed on the system
> Trace/breakpoint trap

This error did not occur while using the MATE DE. I'm certain it needs to be wrapped with `wrapGAppsHook`.

### Steps to reproduce
- start an AwesomeWM session (or perhaps any other WM-only session)
- `lxterminal`-> Settings
- clicking on any colour button now will crash `lxterminal`. checking `journalctl` or starting it from another terminal program will reveal the quoted error message

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.12, NixOS, 18.09.892.c06f5302f63 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(bt1cn): `""`
 - channels(root): `"nixos-18.09.892.c06f5302f63"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Yes, wrapping with `wrapGAppsHook` is the correct solution.
