### ISSUE TITLE
GNOME: gio, gvfs-open and gnome-open are all absent

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#48677]
## Issue description
I can't use some GNOME functionality, like mailto links, because all GNOME tools to process xdg-email requests are absent from my system closure.

I want to use alot (which conveniently installs a desktop file that properly integrates into GNOME and **properly** processes all mailto syntax.

### Steps to reproduce
1. Install GNOME 3 system-wide
2. `grep "(gio|gnome-open|gvfs-open)" /run/current-system/sw/bin/xdg-email`
3. `which gio; which gvfs-open; which gnome-open`
By now, the issue should become obvious. If you're not understanding it, try to fire up Chromium and click on [this](mailto:nobody@example.com).

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.68, NixOS, 19.03pre151837.ca2ba44cab4 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1`
 - channels(root): `"nixos-19.03pre155123.32bcd72bf28"`
 - channels(kisik21): `"nixos-19.03pre151837.ca2ba44cab4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
`gio` program needs to be installed manually by adding `glib.dev` – apps should work without it installed, so I would call that Chromium packaging bug.

`gvfs-open` is deprecated and will be removed in https://github.com/NixOS/nixpkgs/pull/45950

Not sure what `gnome-open` is.

**Comment by hedning** [comment]
We should probably add `glib.bin` to gnome's core package set though, so that gapplication, gdbus, gio and gsettings are available by default?

**Comment by kisik21** [comment]
`glib.bin` does add `gio` to PATH. Adding to my system closure would fix the problem.

Leaving the issue open for discussion.

**Comment by jtojnar** [comment]
I believe this was fixed in https://github.com/NixOS/nixpkgs/pull/38486

**Comment by kisik21** [comment]
Should be. Closing.
