### ISSUE TITLE
Containers with unified cgroup hierarchy are broken on 18.09

### ISSUE THREAD

**Issue by uvNikita** [NixOS/nixpkgs#48749]
## Issue description

I was successfully using a unified cgroup hierarchy (cgroups v2) with declarative nixos containers on 18.03, but after upgrade to 18.09 none of my containers can boot with the following errors in the journal:

```
Oct 20 16:29:41 server systemd[5592]: container@dhcpd.service: Failed to attach to cgroup /system.slice/system-container.slice/container@dhcpd.service: Device or resource busy
Oct 20 16:29:41 server systemd[5592]: container@dhcpd.service: Failed at step CGROUP spawning /nix/store/5g66qi1k4pgc8xiyyv4yl1abigkimc0q-unit-script-container_dhcpd-post-start: Device or resource busy
```

The cgroup folder mentioned in the message exists.

### Steps to reproduce

Add kernel parameter in configuration.nix and create some containers:
```
boot.kernelParams = [ "systemd.unified_cgroup_hierarchy=1" ];
containers.dhcpd = {
  autoStart = true;
  privateNetwork = true;
  macvlans = [ "lan" ];
  config = {
    networking = {
      interfaces = {
        mv-lan.ipv4.addresses = [ { address = 192.168.1.10; prefixLength = 24; } ];
      };
      firewall = {
        enable = true;
        allowedUDPPorts = [ 67 68 ];
      };
    };
    services.dhcpd4 = {
      enable = true;
      interfaces = [ "lan" ];
    };
  };
};
```

Removing kernel parameter fixes the issue, all containers are booting.

## Technical details

system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-server-18.09.932.09195057114, nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos-server`

**Comment by arianvp** [comment]
Not sure if related, but just an observation.

I notice the containers aren't running in `machine.slice`, but in `system.slice/system-container.slice` ...  
Usually, `systemd-nspawn` puts things in `machine.slice`, but for some reason, in NixOS it puts it in a different one. I also can't really trace back why this is the case... I wonder if it's related in any way?

**Comment by arianvp** [comment]
See  `man machine.slice`:

> A unit configuration file whose name ends in ".slice" encodes information about a slice unit. A slice unit is a concept for hierarchically
 >managing resources of a group of processes. This management is performed by creating a node in the Linux Control Group (cgroup) tree.

...

>  By default, service and scope units are placed in system.slice, virtual machines and containers registered with systemd-machined(1) are found
>  in machine.slice, and user sessions handled by systemd-logind(1) in user.slice. See systemd.special(5) for more information.


The weird thing is. Nixos containers _are_ registered with `systemd-machined`  ,  but they don't show up in the `machine.slice` CGroup

**Comment by arianvp** [comment]
Okay, mystery solved:
Template units (like `container@` ) implicitly get assigned a cgroup that groups together all template instances. E.g.
```
           │   │ ├─hello.slice
           │   │ │ ├─hello@a.service
           │   │ │ │ └─2154 /run/current-system/sw/bin/yes a
           │   │ │ └─hello@b.service
           │   │ │   └─2155 /run/current-system/sw/bin/yes b

```

**So probably has nothing to do with our problem. Alas**

**Comment by arianvp** [comment]
I can't reproduce this issue on kernel `Linux 4.18.14` nor on  `Linux 4.14.76`  . Your  config works fine for me in both cases.

**Comment by arianvp** [comment]
Could you check whether the above PR fixes the problems for you, @uvNikita?  I'm suspecting that  nested Cgroup hierarchies are what are causing issues.

**Comment by uvNikita** [comment]
@arianvp Thank a lot for looking into this issue!

I just reproduced this issue on my laptop, here is a configuration that I added:
```
  boot.kernelParams = [ "systemd.unified_cgroup_hierarchy=1" ];
  containers.test = {
    autoStart = true;
    privateNetwork = true;
    config.services.dhcpd4.enable = true;
  };
```

I also had to restart my machine for `kernelParams` to take effect of course.

With this I'm seeing this errors in journal:

```
Failed to stop machine scope: Transaction is destructive.
```
together with already mentioned:
```
Oct 21 12:49:46 laptop systemd[4696]: container@test.service: Failed to attach to cgroup /system.slice/system-container.slice/container@test.service: Device or resource busy
Oct 21 12:49:46 laptop systemd[4696]: container@test.service: Failed at step CGROUP spawning /nix/store/vysanfmsmsdz9lpw7rv740aq5nc60g15-unit-script-container_test-post-start: Device or resource busy
```

**Comment by uvNikita** [comment]
I can try to test the PR. I guess to do this, I'll have to clone nixpkgs, merge your patch, and point nixos-rebuild to this folder by adding `-I` parameter?

**Comment by uvNikita** [comment]
No, doesn't seem like changes in the PR help, the error changed to `machine.slice`, but the behavior is the same:
```
Failed to attach to cgroup /machine.slice/container@test.service: Device or resource busy
```

**Comment by uvNikita** [comment]
Here is a minimal configuration example:

```
  boot.kernelParams = [ "systemd.unified_cgroup_hierarchy=1" ];
  containers.test.config.networking.hosts = {"0.0.0.0" = [ "test" ]; };
```

Since `autoStart` now defaults to `false`, to get an error I execute `$ sudo nixos-container start test` or `sudo systemctl start container@test`

**Comment by arianvp** [comment]
I can reproduce the issue now.Thanks for the minimal example.

**Comment by arianvp** [comment]
Apparently only the `post_start` script is failing,  `pre_start and `script` both succeed:

```
● container@test.service - Container 'test'
   Loaded: loaded (/nix/store/4vk4rvlgwyiicisdjqd8g1q76q384kvb-unit-container-test.service/container@test.service; linked; vendor preset: enabled)
   Active: deactivating (stop-sigterm) (Result: exit-code)
  Process: 23710 ExecStartPost=/nix/store/vysanfmsmsdz9lpw7rv740aq5nc60g15-unit-script-container_test-post-start (code=exited, status=219/CGROUP)
  Process: 23454 ExecStartPre=/nix/store/9z50azn3vlnxq1gpqdsy7w4wj4c05vba-unit-script-container_test-pre-start (code=exited, status=0/SUCCESS)

```

**Comment by arianvp** [comment]
Some more digging:

The presence of  a `PostStart` section in the unit file triggers the bug, no matter what the contents.

**Comment by arianvp** [comment]
My current theory is that it's related to this recent PR: https://github.com/NixOS/nixpkgs/commit/7eb1fa284589a604c420b156f97433c7d62fdaf0

I reverted it and am now rebuilding the world.

**Comment by arianvp** [comment]
Alas, reverting that commit did not fix the issue. I'm out of ideas for now. Hope somebody else can chime in

**Comment by arianvp** [comment]
I can now reproduce without `nixos-container` using just `systemd`'s upstream  `systemd-nspawn@.service`.    This means this is an upstream issue. I will file an issue with them:

```
mkdir -p /var/lib/machines
nix-shell -p debootstrap
sudo debootstrap jessie /var/lib/machines/jessie
```

Add the following line to your config:
```
systemd.services."systemd-nspawn@".postStart = "echo hey";
```

Then:

```
sudo systemctl start systemd-nspawn@jessie
sudo journalctl -xefu systemd-nspawn@jessie
```

And  it breaks:
```
Oct 21 22:07:11 ryzen systemd[25618]: systemd-nspawn@jessie.service: Failed to attach to cgroup /machine.slice/systemd-nspawn@jessie.service: Device or resource busy
Oct 21 22:07:11 ryzen systemd[25618]: systemd-nspawn@jessie.service: Failed at step CGROUP spawning /nix/store/flkkv70pc1sg5zfag05hq3pc60n75yxj-unit-script-systemd-nspawn_-post-start: Device or resource busy

```

**Comment by uvNikita** [comment]
@arianvp thank you for a thorough investigation and for creating an issue with upstream!

**Comment by arianvp** [comment]
A fix has landed upstream https://github.com/systemd/systemd/pull/10813/files

If we want to backport it, we also have to backport https://github.com/NixOS/nixpkgs/pull/48771

**Comment by arianvp** [comment]
The fix has been merged and released under version v240

**Comment by flokli** [comment]
@uvNikita did you try if this is fixed with latest nixos upstream (systemd 242 - https://github.com/NixOS/nixpkgs/pull/61321)?

If that's the case, we should backport #48771 and https://github.com/systemd/systemd/pull/10813 to 19.03.

**Comment by peterhoeg** [comment]
I'm happily running containers with a the unified hierarchy so this is safe to close.
