### ISSUE TITLE
GNOME: nautilus asks to install glib-networking to access HTTPS resources

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#48789]
## Issue description
Added Nextcloud account to my GOA section in GNOME. Trying to access the DAV resource results in an error "HTTP Error: TLS/SSL support not available, please install glib-networking".

I tried to rebuild the Nautilus with `gnome3.glib-networking` in `buildInputs`, tried to add it in nix-shell - no results. Same error.

### Steps to reproduce
1. `nix run nixpkgs.gnome3.nautilus`
2. Add any davs:// resource

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.75, NixOS, 19.03pre155751.45a419ab5a2 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre155751.45a419ab5a2"`
 - channels(kisik21): `"nixos-19.03pre151837.ca2ba44cab4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Did you close the previously running nautilus instance? Adding `glib-networking` to `buildInputs` should be sufficien.-

**Comment by jtojnar** [comment]
Pushed a fix in 467c459b9e907a397606857a671ba5c9867cfaad

**Comment by kisik21** [comment]
Well, is adding this to a personal overlay sufficient? I'm not sure I'm doing it right, but...
```
  gnome3                   = super.gnome3 // {
    nautilus = super.gnome3.nautilus.overrideAttrs(oldAttrs: rec {
      buildInputs = oldAttrs.buildInputs ++ [ super.gnome3.glib-networking ];
    }); 
  };  
```

**Comment by kisik21** [comment]
Also maybe I should relaunch gnome-shell?

**Comment by jtojnar** [comment]
Yes, that should work.

Though, if you want to override GNOME packages properly (for other packages in the `gnome3` attribute set to see the overriden package), I think you need something like:

```nix
(self: super: {
  gnome3 = super.gnome3.overrideScope (gsuper: gself: {
    nautilus = gsuper.nautilus.overrideAttrs (oldAttrs: {
      buildInputs = oldAttrs.buildInputs ++ [ super.glib-networking ];
    }); 
  });
})
```

IIRC, the order of arguments for `overrideScope` is swapped.

I am fairly certain `nautilus -q` should be enough after rebuild.

**Comment by kisik21** [comment]
Nope, that doesn't seem to work.

Also order of arguments isn't swapped, the swapped form is deprecated.

**Comment by jtojnar** [comment]
Can you try to run `nautilus -q; env $(nix-build -E 'with import <nixpkgs> {}; gnome3.nautilus.overrideAttrs (oldAttrs: { buildInputs = oldAttrs.buildInputs ++ [ glib-networking ]; })')/bin/nautilus` in your terminal?

**Comment by kisik21** [comment]
Actually, rebooting seemed to help. Issue is kinda irrelevant now, since I've switched to KDE. Closing, as you mentioned the fix is pushed.
