### ISSUE TITLE
Cannot open gnome-control-center

### ISSUE THREAD

**Issue by xurei** [NixOS/nixpkgs#48819]
## Issue description
After a upgrade, I cannot open the control center anymore.

### Steps to reproduce
```
$ gnome-control-center
/run/current-system/sw/bin/gnome-control-center: error while loading shared libraries: /nix/store/4wpcqa1y23rpqk5mpjl5yz86c4nc5hvg-clutter-gtk-1.8.4/lib/libclutter-gtk-1.0.so.0: invalid ELF header
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.03.133311.5d19e3e78fb (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133311.5d19e3e78fb, unstable-19.03pre155751.45a419ab5a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

Please tell me if you need any more information about this issue (gnome version etc.)

**Comment by jtojnar** [comment]
What is your hash of the library?

```
$ sha256sum /nix/store/4wpcqa1y23rpqk5mpjl5yz86c4nc5hvg-clutter-gtk-1.8.4/lib/libclutter-gtk-1.0.so.0
163a0de6ddf0519bb076792a43106261c3c7c2d91a39ecc468c0f97b45b46765  /nix/store/4wpcqa1y23rpqk5mpjl5yz86c4nc5hvg-clutter-gtk-1.8.4/lib/libclutter-gtk-1.0.so.0
```

**Comment by xurei** [comment]
`7f7ef6590ec1fdac8f98d28b33b280430ddd44a07ca846410318e983ada7dbb5  /nix/store/4wpcqa1y23rpqk5mpjl5yz86c4nc5hvg-clutter-gtk-1.8.4/lib/libclutter-gtk-1.0.so.0`

**Comment by jtojnar** [comment]
Did you build it yourself or fetched it from cache?

**Comment by xurei** [comment]
From cache I think. I'm using NixOS configuration :
```
  services.gnome3.chrome-gnome-shell.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
```

**Comment by jtojnar** [comment]
Then looks like your package is corrupted. Maybe someone on IRC will be more suited to help.

**Comment by xurei** [comment]
From cache I think. I'm using NixOS configuration :
```
  services.gnome3.chrome-gnome-shell.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
```

**Comment by symphorien** [comment]
Maybe running `sudo nix-store --verify --repair --check-contents` can help.

**Comment by xurei** [comment]
I finally solved this the hard way : reinstall NixOS completely.
I wish I saw @symphorien answer before doing that :-(

Anyways, reinstalling NixOS is just awesome : reinstall a minimal version, reboot, reload my original configuration.nix and BOOM, system restored as it was before !
This is why I love NixOS.
