### ISSUE TITLE
Linux kernel 4.19

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#48828]
I just added the kernel version 4.19 in 2bb68c7017a105c0c1e4d6460c8a625dc7ac92cf.

Since 4.19 is meant to become the next LTS kernel.
Because of this, we should keep track of the breakage the above commit causes to kernel modules etc.
I highly encourage testing with 4.19 and reporting back here.

Edit: Just updated my [P320 ThinkStation](https://github.com/NeQuissimus/DevSetup/blob/master/p320.nix) and everything looks good.

**Comment by dtzWill** [comment]
Been working well for me here -- Dell XPS 9560.

**Comment by NeQuissimus** [comment]
Any time is fine with me.

**Comment by c0bw3b** [comment]
One issue with `nvidiaLegacy340` : #50707

**Comment by aszlig** [comment]
We also have another issue with our tests that seems to have to do with the overlayfs changes in kernel 4.19. After a bisect, I found [this commit](https://github.com/torvalds/linux/commit/a6518f73e60e5044656d1ba587e7463479a9381a) to be the culprit and after reverting said commit plus fixing the arguments of `d_real()`, our `kernel-latest` test succeeds.

**Comment by aszlig** [comment]
Just reported this to the upstream maintainer.

**Comment by aszlig** [comment]
As a temporary mitigation to those who run into that issue, you can use [this NixOS module](https://gist.github.com/aszlig/ed853b2f37321f88b46913f06780e89d) which contains the revert (and fix of the `d_real` function args) of the commit introducing the issue.

**Comment by domenkozar** [comment]
4.19 was set as default in master, but we've missed the patch. @samueldr is investigating.

**Comment by ivan** [comment]
@samueldr you put some hard tabs into `patches.nix`

**Comment by periklis** [comment]
i can report having trouble with `i915` on my T480 with 4.19. CPU load peaks and makes the system unusable.

**Comment by gebner** [comment]
@periklis Are you using dmcrypt by chance?  I'm also experiencing high CPU loads which make the system unresponsive (mainly when running `nixos-rebuild`).  This feels a lot like the issue described here: https://bugzilla.kernel.org/show_bug.cgi?id=199857

**Comment by periklis** [comment]
@gebner Yes i've a luks encrypted zfs-formatted disk.

**Comment by periklis** [comment]
However i am not sure if it is an issue with the mentioned bug. I have not observed any dmcrypt process or so like hammering my CPU. Only some kworker processing events producing high load.

**Comment by ElvishJerricco** [comment]
@aszlig Can you link your bug report?

**Comment by vcunat** [comment]
I'd go here: https://github.com/NixOS/nixpkgs/issues/54509
