### ISSUE TITLE
nixos/acme: allowKeysForGroup has no effect after cert is already created

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#48845]
## Issue description

1.  Changing `group` or `user` will not do anything till the next round of refresh
2. Even after refresh, changes to `allowKeysForGroup` do not actually propagate. The permissions of the key are not changed. Only of the surrounding directory.

### Steps to reproduce
1. Create a cert with
  `security.acme.certs.<name>.group = "hello";`
2. Now change to : `security.acme.certs.<name>.group = "world";`
2.  Afterwards add `security.acme.certs.<name>.allowKeysForGroup =true;`
3.  Observe that the owner is still `hello` and that there are no group read permissions yet
4. Even after manually refreshing by calling the timer manually, the `group` did change, by the  permission bits still not allow read access to `group` even if `allowKeysForGroup` is set

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Infinisil** [comment]
Hey I made a PR that fixes this, would love to have somebody else make sure it fixes this problem: https://github.com/NixOS/nixpkgs/pull/72056

**Comment by arianvp** [comment]
Lets re-open this issue.

**Comment by arianvp** [comment]
wasnt this fixed by the recent bugfix round @m1cr0man ?

**Comment by m1cr0man** [comment]
Yeah, that option has been removed Infact :P

**Comment by m1cr0man** [comment]
This option is now gone in favour of always making the certificates group readable and owned by the acme user, and letting users change only the group that will be applied to them. Closing this issue.
