### ISSUE TITLE
Request to package visidata

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#48852]
## Issue description

http://visidata.org/ is a visual multitool for tabular data that runs inside at terminal. It's like a spreadsheet in the terminal.

If nobody gets around to packaging this, I may eventually to get to this. But it might be a while.

**Comment by teto** [comment]
Looks like sthg I could use, looking forward to your package.

**Comment by Ma27** [comment]
That has happened in 16c329f3da5fac6f19e4633b8e61c92310783e5a
