### ISSUE TITLE
Httpbin problem with static directory

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#48853]
## Issue description

This commit https://github.com/NixOS/nixpkgs/commit/b3eea7ab9c03495d81da9f72ab0905f9238d3a1a results in a problem where re-running httpbin application server on the same directory results in an error:

```
  File "/nix/store/aryfhy44wshkxdwdwbfvs0g28a2q3yhg-python3-3.6.5-env/lib/python3.6/site-packages/httpbin/core.py", line 65, in <module>
    os.mkdir('static')
FileExistsError: [Errno 17] File exists: 'static'
```

More details at: https://github.com/NixOS/nixpkgs/commit/b3eea7ab9c03495d81da9f72ab0905f9238d3a1a#commitcomment-31004160

You have to delete the `static` directory before rerunning.

I actually think that this package should come with an HTTP server as a command line executable, so you could just do `httpbin` and get a working server. Since it's built with Flask, it could just use flask server directly.

I'm not entirely sure what the static directory is for anyway? Is it even needed?

@FRidh 

### Steps to reproduce

Install with `nix-shell -p 'python3.withPackages (ps: with ps; [ flask httpbin ])'`.

Then run:

```
FLASK_APP=httpbin:app flask run
^C
FLASK_APP=httpbin:app flask run
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.6, Form Bay ML, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/nixpkgs`
```

**Comment by CMCDragonkai** [comment]
It appears the source of this problem patch flask-common is no longer used in the latest httpbin package anyway.

**Comment by FliegendeWurst** [comment]
Appears to be fixed by now.
