### ISSUE TITLE
hmatrix-quadprog depends on unpackaged system library

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#48895]
## Issue description
hmatrix-quadprog depends on https://github.com/liuq/QuadProgpp which is currently not packaged in nixpkgs

### Steps to reproduce
Try to build `haskellPackages.hmatrix-quadprog`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Fuuzetsu** [comment]
I'm going to package this up sooner than later (I want it) unless someone beats me to it.

**Comment by Fuuzetsu** [comment]
I packaged it, it's available as `QuadProgpp`. It now should just be made available to the hmatrix-quadprog Haskell package at generation time.

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/commit/7f68896dc52d0c38f4ef25e4bd44442372c96707 will be merged soon.

**Comment by Fuuzetsu** [comment]
Thanks!
