### ISSUE TITLE
mysql-workbench: Authentication plugin 'caching_sha2_password' cannot be loaded: /nix/store/72ma1cha9j8v3blvn23xdmxmn9l2is8r-mysql-5.7.20/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#48902]
## Issue description

I can't connect to a MySQL instance. It works with a Mariadb instance but maybe it's not using the same plugin.

![image](https://user-images.githubusercontent.com/24027/47378020-daf19680-d6c4-11e8-882e-6687b95fea7a.png)

### Steps to reproduce

Start a MySQL instance with docker:
`docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=some_long_password mysql`

Try to connect with mysql-workbench.

## Technical details

I installed mysql-workbench with home-manager.

I'm using mysql-workbench **6.3**.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.03.133311.5d19e3e78fb (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03, nixos-unstable-19.03pre155751.45a419ab5a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by bbigras** [comment]
I can't reproduce this with mysql-workbench 8.0.12 from the unstable channel.

**Comment by aanderse** [comment]
@bbigras it sounds like we can close this issue then?

**Comment by bbigras** [comment]
Yes. Thanks.
