### ISSUE TITLE
Qt Quick Designer is disabled in qtquick 3.2.x

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#4893]
The designer tool for qml files is broken in recent qtsdk and qtcreator installs. It still works in 
5c0816567d6b99bd2ef7c8ae5744f80a6a0372c4 when installing qtsdk-3.1.0-qt-5.2.1. The ChangeLog for QtCreator 3.2.0 still mentions features for Qt Quick Designer, so it has not been discontinued and should work. The patches to upgrade Qt and QtCreator are very straightforward:
  059681bc5de74289ce8720a24008ee03f0035f5a
  46d0ebca70112c73f43a67799a6966a9c566a2d2
so this regression is puzzling.

How to reproduce:
 - start qtcreator
 - press ctrl-n and choose 'Qt Quick Application'
 - fill in the wizard, now a new project is created and a file 'main.qml' is opened
 - press 'Design'. This button is only enabled in qtcreator 3.1.0, in 3.2.0 it is not enabed.

**Comment by bjornfor** [comment]
With qtsdk-3.2.1-qt-5.3.2 (in master now) the "Design" button is working (it takes you to the design view). However, the QML module is not found, so there is an error message pop-up. The same error prevents building QtQuick.

I'm currently attempting to fix doc/examples/qml in qt5SDK.

**Comment by bjornfor** [comment]
Uhm, now the "Designer" sidebar button is grayed out again...

**Comment by bjornfor** [comment]
No, never mind, it is only grayed out until a .ui file is opened.

**Comment by bjornfor** [comment]
QtCreator 3.6.x works on current stable release (NixOS 16.03). In particular, the UI Designer for QML is operational.
