### ISSUE TITLE
Use highlight.js (also supports Nix) inside manuals to highlight snippets

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4901]
To highlight languages inside the docbook, the easiest would be to implement support for highlight.js

https://highlightjs.org/usage/

**Comment by nslqqq** [comment]
@domenkozar I tried it, it doesn't worth it IMHO. Highlighting looks bad at short listings. Check it here: http://nslqqq.github.io/nixpkgs/

**Comment by domenkozar** [comment]
@nslqqq that's amazing! It would be most useful for nixpkgs manual.

**Comment by nslqqq** [comment]
@domenkozar I can make a PR if you want... Though I think bash's syntax highlight looks very weird(judging by class, it detects it righ). Also there are many different themes I wonder which should be used.

**Comment by domenkozar** [comment]
@nslqqq we can work those details out, probably best to pick a theme that goes together with twitter bootstrap design.

**Comment by Profpatsch** [comment]
(triage) has something come of this?

**Comment by grahamc** [comment]
It only took 33,000 issues & PRs, but we got this one.
