### ISSUE TITLE
add nautilus-dropbox nixpkg

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#49053]
I learned from https://github.com/NixOS/nixpkgs/issues/29504 that dropbox-cli strips out the nautilus plugin. Would it be possible to get a nixpkg that does not do this stripping? Happy to test/help if someone can point me in the right direction!

@the-kenny

**Comment by jtojnar** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/60752
