### ISSUE TITLE
NixOS manual has incorrect information regarding the configuration of the GRUB bootloader image

### ISSUE THREAD

**Issue by gabriel-laddel** [NixOS/nixpkgs#4911]
[from the manual](http://nixos.org/nixos/manual/#opt-boot.loader.grub.splashImage)

```
boot.loader.grub.splashImage

Background image used for GRUB. It must be a 640x480, 14-colour image in XPM format, optionally compressed with gzip or bzip2. Set to null to run GRUB in text mode.

    Example:

    ./my-background.png

    Declared by:
    <nixpkgs/nixos/modules/system/boot/loader/grub/grub.nix>
```

from the [GRUB manual](http://www.gnu.org/software/grub/manual/grub.html)

```
‘GRUB_BACKGROUND’

    Set a background image for use with the ‘gfxterm’ graphical terminal. The value of this option must be a file readable by GRUB at boot time, and it must end with .png, .tga, .jpg, or .jpeg. The image will be scaled if necessary to fit the screen.
```

I've tried both methods. The NixOS manual is wrong.

**Comment by Profpatsch** [comment]
(triage) Hasn’t been fixed. Should we just update the option to say what the manpage says? I’m not sure if the config really points to `GRUB_BACKGROUND`, I haven’t found traces of that. I think it quite literally compiles to an xml-tag `<splashImage>`.
