### ISSUE TITLE
Backport firefox 63.0 to release-18.09

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#49124]
## Issue description

IMHO firefox 63 shall be backported to the current stable release 18.09. Is @andir planning to do this or shall I start testing that version on a stable release?
I don't want to stress you but am just a bit unfamiliar with the backporting/ update process in nixpkgs, when it is done and what tests are required beforehands.

**Comment by andir** [comment]
There is already a PR for that. It will probably just be a few more hours
brfore it is beging merged.

**Comment by schmittlauch** [comment]
Great, didn't see that.
