### ISSUE TITLE
Please change name of FreeCAD-0.17 to FreeCAD-0.17.13541 and update unstable to 0.18_pre

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#49127]
## Issue description
When using repology we can track when distros are using the most up-to-date version of our stable and devel [FreeCAD] releases. This is tracked and illustrated in https://repology.org/metapackage/freecad/badges 
Example: 
[![Packaging status](https://repology.org/badge/vertical-allrepos/freecad.svg)](https://repology.org/metapackage/freecad/versions)

More specifically: 
[![nixpkgs stable package](https://repology.org/badge/version-for-repo/nix_stable/freecad.svg)](https://repology.org/metapackage/freecad/versions)
[![nixpkgs unstable package](https://repology.org/badge/version-for-repo/nix_unstable/freecad.svg)](https://repology.org/metapackage/freecad/versions)

Relevant links:
* [Upstream ticket](https://github.com/luzpaz/FreeCAD-dependencies/issues/6)
* https://github.com/luzpaz/FreeCAD-dependencies
* https://github.com/FreeCAD/FreeCAD/releases

**Comment by vcunat** [comment]
@luzpaz: it seems this is some misunderstanding.  The "stable" and "unstable" here refers to nixpkgs branches, not to (un)stability of freecad versions.  Why should 0.17 be a bad version number for the package built from https://github.com/FreeCAD/FreeCAD/releases/tag/0.17 ?

**Comment by luzpaz** [comment]
nvm this ticket is obsolete. cheers

**Comment by vcunat** [comment]
Oh, OK.
