### ISSUE TITLE
wrapGAppsHook gives unexpected GDK_PIXBUF_MODULE_FILE

### ISSUE THREAD

**Issue by ChengCat** [NixOS/nixpkgs#49132]
## Issue description
I use a custom modified Nix package. After I upgraded to NixOS 18.09, the icons don't show up.

I tried to narrow the cause down, and found that `wrapGAppsHook` works differently from 18.03 for the following Nix file. I don't understand `strictDeps`, and am not sure whether this is a bug.

### Steps to reproduce
1. Save the following as `test.nix`:
```
{ stdenv, gtkmm3, wrapGAppsHook }:

stdenv.mkDerivation rec {
  name = "test";

  nativeBuildInputs = [ wrapGAppsHook ];
  buildInputs = [ gtkmm3 ];
  strictDeps = true;

  phases = [ "installPhase" "fixupPhase" ];
  
  installPhase = ''
    mkdir -p $out/bin
    touch $out/bin/test
    chmod a+x $out/bin/test
  '';
}
```

2. Run:
```
nix-build -E --no-out-link 'with import <nixpkgs/nixos> {}; pkgs.callPackage ./test.nix { }'
```

3. The resulting wrapper script will contain something like:
```
export GDK_PIXBUF_MODULE_FILE='/nix/store/xxxxxxxxxxxxxxxxxxxxxxxxxx-gdk-pixbuf-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
```

But I expect `GDK_PIXBUF_MODULE_FILE` to point into `librsvg`, like what NixOS 18.03 does.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09"`
 - channels(cheng): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
We need to know how does `strictDeps` interact with setup hooks and propagated dependencies.

**Comment by Artturin** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/208537

**Comment by abathur** [comment]
Closing because the fix PR Artturin linked is present in master and channels. Happy to reopen if I'm overreaching.
