### ISSUE TITLE
Use nvidia_x11 from different channel on 1809

### ISSUE THREAD

**Issue by va1entin** [NixOS/nixpkgs#49139]
## Issue description
I want to use the latest nvidia drivers from master/unstable on 1809 without switching to unstable entirely.

I tried specifying it like I do with many other packages from unstable but it does not work. Using the same package from 1809 (pkgs.kernelPackages.nvidia_x11) works perfectly. There's no documentation about this that I am aware of.
@eadwu Do you know how to do this? I followed your work on getting the new 4xx.xx drivers into nixpkgs and would like to use those now without switching to unstable entirely.

### Steps to reproduce
`
let
  unstable = import <nixos-unstable> {config = config.nixpkgs.config;};                                            
in {
services.xserver.videoDrivers = [ unstable.kernelPackages.nvidia_x11  ]
};
`
<pre>
$ nixos-rebuild switch
error: infinite recursion encountered, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:336:9
</pre>

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.932.09195057114, nixos-unstable"`
 - channels(val): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ryanfitzsimon** [comment]
If you're still trying to figure this out, adding the following to configuration.nix should work.

```nix
{
  disabledModules = [
    "hardware/video/nvidia.nix"
  ];

  imports = [
    <nixos-unstable/nixos/modules/hardware/video/nvidia.nix>
  ];

  overlays = [
    (self: super:
    {
      linuxPackages_latest = super.linuxPackages_latest.extend (linuxSelf: linuxSuper:
      let
        generic = args: linuxSelf.callPackage (import <nixos-unstable/pkgs/os-specific/linux/nvidia-x11/generic.nix> args) { };
      in
      {
        nvidiaPackages.stable = generic {
          version = "410.73";
          sha256_64bit = "07pzq8rvbsx3v8rgz98amyw0k1mn5mkygpd1q5gfn6r0h7vrrg5y";
          settingsSha256 = "19xc10b0c074wb9fv9n04dvmi8hrwl6srvvyrjfyj92gch49x6hw";
          persistencedSha256 = "0vhr7pysv4vk7v96yima0i9zsvvgxaxihjzxlfifpsdki57n2jz7";
        };
      });
    })
  ];
}
```

The `nvidia-x11` package includes a reference to the kernel, so it's not possible to use the package from unstable without using its kernel version too. The above configuration gets around this by calling the generic Nvidia function itself.

If you have `boot.kernelPackages` set to `linuxPackages_latest` like me, just replace all the occurrences to match.

Of course, you'll have to be subscribed to `nixos-unstable` for all this to work.

```bash
$ sudo nix-channel --list 
nixos https://nixos.org/channels/nixos-18.09
nixos-unstable https://nixos.org/channels/nixos-unstable
```

Let me know if I've made any typos so I can fix them. Also, if anyone has a more elegant way to acheive this (#49703 is looking promising!) I'd love to hear it.

**Comment by va1entin** [comment]
@ryanfitzsimon Thx a lot! I didn't have more time for this lately but will try your suggestion asap. #49703 looks nice indeed!
