### ISSUE TITLE
Python 2.7 Full: sqlite3 module doesn't work in virtualenv

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#492]
```
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/yzj6p5f7iyh247pwxrg97y3klm6d0cni-python-2.7.3/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/nix/store/yzj6p5f7iyh247pwxrg97y3klm6d0cni-python-2.7.3/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

@chaoflow @garbas can you reproduce?

**Comment by copumpkin** [comment]
I'm getting this with just nix-shell and straight nix python (with no virtualenv). Should I open a separate ticket?

**Comment by copumpkin** [comment]
Oh never mind, I needed `pythonPackages.sqlite3`

**Comment by jgeerds** [comment]
This also affects the tox test runner (which uses an unpatched version of virtualenv internally). This means that it is not possible to execute python2.7 tests for a django project/app because of the missing _sqlite3 module.

**Comment by domenkozar** [comment]
I think we should include ncurses and sqlite by default. They're both very light and convenient.

**Comment by FRidh** [comment]
@jgeerds could you show an example of how you use the tox test runner with Nix?

**Comment by FRidh** [comment]
Since https://github.com/NixOS/nixpkgs/pull/19309 we don't have separate modules anymore except `tkinter`, which is like a 'normal' Python package: `pythonPackages.tkinter`.
