### ISSUE TITLE
systemd-logind problem?

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#4923]
I'm getting the following on staging (``/var/log/Xorg.0.log``):
```
(EE) systemd-logind: failed to get session: PID 13553 does not belong to any known session
```

**TL;DR of the discussion: it seems not to cause any problems.**

Any ideas if it's even a problem? @edolstra?

**Comment by domenkozar** [comment]
@rushmorem @vcunat is this still happening?

**Comment by vcunat** [comment]
I can still see the message on ~week old staging (around d35352142).

**Comment by rushmorem** [comment]
@domenkozar I'm still getting this error message in my logs. When starting up my laptop, if I try to log in right after the `kdm` login prompt appears, the login fails. Everytime I have to try twice. I always log in successfully on the second try. However if I wait a bit (say a minute or two) before trying to login, I can do so on first attempt. I'm using `kdm` as my display manager and `i3` as my window manager on `nixos-unstable`.

My guess is some systemd services are not starting up in the correct order. I haven't tried digging into this though, so I could be wrong.

**Comment by lethalman** [comment]
Is this still current?

**Comment by vcunat** [comment]
I'm still getting the message on recent 15.09, but it seems not to cause any problems.

**Comment by rushmorem** [comment]
I still see it in my logs as well but ever since I moved from `NetworkManager` to just `wpa_supplicant` and `wvdial` I can login on first attempt. Also it takes much less time to get to a usable state after entering login details.

**Comment by abbradar** [comment]
As @vcunat noticed, patch https://github.com/NixOS/nixpkgs/commit/b292e19fbddaddd4ada813965e3be3880f15fa7e seems to have fixed this problem for me. If someone still has this problem, please try it out.

**Comment by globin** [comment]
Closing this as it seems to be fixed, please reopen if you still experience this bug.
