### ISSUE TITLE
Allow custom hwdb.d entries

### ISSUE THREAD

**Issue by puffnfresh** [NixOS/nixpkgs#4924]
I've had a go at implementing this but haven't succeeded yet.

I have a keyboard with a scroll wheel thingo in it. The Internet tells me that I should add a `/etc/udev/hwdb.d/70-local.hwdb` entry containing the following:

```
# Microsoft Natural Ergonomic Keyboard 4000
keyboard:usb:v045Ep00DB*
 KEYBOARD_KEY_c022d=pageup
 KEYBOARD_KEY_c022e=pagedown
```

Looks like udev allows adding custom rules.d entries but the hwdb.d directory is special: its contents get compiled to a hwdb.bin file which is special in NixOS since it gets put in /var/lib/udev/hwdb.bin instead of /etc/udev/hwdb.bin

**Comment by dezgeg** [comment]
This is implemented now, isn't it?

**Comment by puffnfresh** [comment]
@dezgeg yes, I noticed this the other day. Was added in 7330bfe4648f8255e9481058ec7f8ef3fcf24a7e.

**Comment by puffnfresh** [comment]
Thanks @abbradar for #12724!
