### ISSUE TITLE
NixOS 18.09 incompatible with 18.03 ddclient configuration

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#49258]
## Issue description
ddclient.domain option was changed to ddclient.domains, but instead of maintaining backwards compatibility the type was changed to a list of strings, which also was not in the release notes, which makes this a bug.

I don't see why the type was not simply changed to an or of a string and a list of strings in order to maintain compatibility. 

### Steps to reproduce
Try to upgrade 18.03 with ddclient.domain = "foo.bar.com"; 

## Technical details
Any released 18.03 version.

**Comment by typetetris** [comment]
As this breakage already happened, would there be a point in doing a patch for 18.09? (I could provide one, but I don't know, wether it will be merged into a stable branch.)

**Comment by typetetris** [comment]
Not a problem, so I will just make the minimal possible change.

**Comment by coretemp** [comment]
This needs to be reopened, because of a failure to build:

> The option value `services.ddclient.domains' in `/home/coretemp/src/nixpkgs-channels/nixos/modules/rename.nix' is not of type `list of strings'.

**Comment by typetetris** [comment]
I'll take look.

Which commit did you use?

**Comment by coretemp** [comment]
Whatever was newest 15 hours ago in the release channel.

**Comment by typetetris** [comment]
Yes, the change wasn't backported to the release branch :(

**Comment by typetetris** [comment]
@joachifm : Could you please reopen this and merge the change into release-18.09 ?
