### ISSUE TITLE
singularity: upgrade to v3.0.0

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixpkgs#49269]
Currently, we have `singularity` v2.6.0:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/singularity/default.nix

Upstream has released a `v3.0.0`, with a number of new features, including support for OCI images, Docker images, and so on:
https://github.com/sylabs/singularity/blob/master/CHANGELOG.md

It looks like upstream has ported the code from C to go, so upgrading the package may require some effort.  Also, we're  using at least one of the removed API functions here, so we'll need some refactoring:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/singularity-tools/default.nix#L96

I haven't used singularity before, but I'm interested in its rootless no-daemon functionality, and some of its new features might help me test with my docker containers.  Any interest in helping out with the upgrade + testing, @jbedo?

**Comment by jbedo** [comment]
Yeah I'm keen. Doesn't look too difficult, in fact singularity-tools may be considerably simpler now. I'll take a look.

**Comment by jbedo** [comment]
I've made some progress on this (see jbedo/nixpkgs@235da00734867ccff548e256946cbf6daf066b1d). Everything compiles fine, and the build/pull commands work fine too. However, actually using a container seems broken:

```
DEBUG   [U=1000,P=30725]   create()                      Chroot into /var/singularity/mnt/session/final
DEBUG   [U=1000,P=30741]   Chroot()                      Change current directory to /var/singularity/mnt/session/final
DEBUG   [U=1000,P=30741]   Chroot()                      Hold reference to host / directory
DEBUG   [U=1000,P=30741]   Chroot()                      Called pivot_root on /var/singularity/mnt/session/final
DEBUG   [U=1000,P=30741]   Chroot()                      Change current directory to host / directory
DEBUG   [U=1000,P=30741]   Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=1000,P=30741]   Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=1000,P=30741]   Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=1000,P=30725]   create()                      Chdir into / to avoid errors
DEBUG   [U=1000,P=30740]   set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=1000,P=30740]   prepare_scontainer_stage()    Entering in scontainer stage 2
VERBOSE [U=1000,P=30740]   startup()                     Execute scontainer stage 2
FATAL   [U=1000,P=30740]   SContainer()                  exec /.singularity.d/actions/shell failed: no such file or directory
```

After messing around with this a fair bit, I think it's an upstream bug. I'll open an issue upstream and see if it can be resolved.
