### ISSUE TITLE
Please update uriparser to 0.9.0, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [NixOS/nixpkgs#49274]
Hi!

Just a quick heads up that [uriparser 0.9.0](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.0) with security fixes has been released.

Thanks for updating!

**Comment by periklis** [comment]
@hartwork i've created PR

**Comment by periklis** [comment]
@hartwork PR is merged, you can close this issue now.

**Comment by hartwork** [comment]
Thank you, that was quick! I'm unsure about the backport. Backport to where? 0.9.0 is the only version packaged see right now. (I'm rather new to NixOS.)

**Comment by periklis** [comment]
Backport for release 18.09

**Comment by hartwork** [comment]
If it has uriparser and receives security updates, maybe a good idea. I see you already added related labels.

**Comment by periklis** [comment]
@hartwork i opened a PR for backporting it to our fresh and stable release. This update pointed also to a build insufficiency in googletest - lacked provided support for pkgconfig - which will benefit other developers, too.

**Comment by vcunat** [comment]
Merged.
