### ISSUE TITLE
NixOS 18.09 htop incompatible with NixOS 18.03

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#49279]
## Issue description

[An almost 3 year old issue seen when using nixpkgs on Fedora 23](
https://github.com/NixOS/nixpkgs/issues/11631) has resurfaced on NixOS 18.09 in a release channel. 

Not sure whether anyone else is hitting this, but I have seen it on multiple systems. 

```
htop: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted
```

## Relevant system output

```
 locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```
env | grep LOCAL
LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
```

```
file /run/current-system/sw/lib/locale/locale-archive
/run/current-system/sw/lib/locale/locale-archive: locale archive 8848 strings
```

### Steps to reproduce
Upgrade a system from 18.03 to 18.09 and even reboot and then login as `root` and run`htop` . I don't know about the specific conditions.

## More information
https://unix.stackexchange.com/questions/444102/loadlocale-c-nl-intern-locale-data-assertion-error

## Incomplete workaround

`LANG=C htop`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.git.0919505 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`

**Comment by ckauhaus** [comment]
I'm experiencing the same problem after an upgrade from 18.03 to 18.09 (7e88992a8c7) with mercurial and vim.

**Comment by ckauhaus** [comment]
The culprit seems to be that there are still some old package versions installed in ~/.nix-profile.

Diagnose: `nix-env -q` shows some output

Fix: `nix-env --upgrade` or transfer everything show in `nix-env -q` to `environment.systemPackages`.

@coretemp Does that help?

**Comment by pSub** [comment]
I've the same issue. Sadly upgrading all packages installed via nix-env does not fix it.

**Comment by pSub** [comment]
@coretemp do you still have this issue?

**Comment by worldofpeace** [comment]
> @coretemp do you still have this issue?

They have been banned from the org so you're not going to get a response :rofl:

**Comment by pSub** [comment]
Oh, I remember… Then I'll close this issue. If anyone still suffers from this problem and is not able to fix it by updating packages in `~/.nix-profile` please reopen.

**Comment by worldofpeace** [comment]
> Oh, I remember… Then I'll close this issue.

Yeah, and there's still some pretty *pointed*  issues around.
