### ISSUE TITLE
Terraform.withPlugins does not work anymore

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#49316]
## Issue description

`terraform.withPlugins`  does generate a wrapper script, but it doesn't fool terraform anymore
in thinking the plugins are installed

### Steps to reproduce

```
[arian@ryzen:~/Projects/infra]$ nix-shell -p 'terraform.withPlugins (p: [p.digitalocean])'

[nix-shell:~/Projects/infra]$ terraform plan
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.digitalocean: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".


Error: error satisfying plugin requirements

```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.14, NixOS, 18.09.884.d96c7a35638 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.884.d96c7a35638"`
 - channels(arian): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by arianvp** [comment]
It works fine. I was using it incorrectly.

For the curious cat who runs into issues:
```
 nix-shell -p 'terraform.withPlugins (p: [p.digitalocean])'
```

**Comment by voobscout** [comment]
Please reopen this, it doesn't work. the wrapper is in-place and
```bash
nix-shell -p terraform-full
```
is unable to find any plugins, but they're all available in $NIX_TERRAFORM_PLUGIN_DIR according to 
```bash
cat $(which terraform)
```
