### ISSUE TITLE
fileSystems option does not change fstab outside of hardware-configuration.nix

### ISSUE THREAD

**Issue by va1entin** [NixOS/nixpkgs#49337]
## Issue description
I tried to use the `fileSystems` option in my configuration to add a device to `/etc/fstab`. On my machine the option has no effect if it's not applied in `/etc/nixos/hardware-configuration.nix` contrary to the manual and comment at the top of the file:
<pre>
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
</pre>

### Steps to reproduce
Snippet:
<pre>
fileSystems."/path" = {
  device = "/dev/device";
};
</pre>

- Add snippet to configuration.nix, rebuild
- Check `/etc/fstab` -> entry not added

- Add snippet to hardware-configuration.nix, rebuild
- Check `/etc/fstab` -> entry added

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.14, NixOS, 18.09.892.c06f5302f63 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.892.c06f5302f63, nixos-unstable-19.03pre155751.45a419ab5a2"`
 - channels(val): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by aanderse** [comment]
Was not able to reproduce. Steps taken:

- umount /opt
- cut & paste /opt mount from hardware-configuration.nix to configuration.nix:
  fileSystems."/opt" =
    { device = "extra/opt";
      fsType = "zfs";
    };
- nixos-rebuild test
- ls /opt # everything is there

Any other details you could provide?

**Comment by va1entin** [comment]
I just overlooked something very obvious. Sorry for bothering you!

**Comment by spikespaz** [comment]
@va1entin I wish you had shared your oversight four years ago

**Comment by va1entin** [comment]
> @va1entin I wish you had shared your oversight four years ago

I believe my oversight was that I added the entry to a copy of my configuration.nix, not the one NixOS actually consults.
That happened because I share a copy of it in a git repository called nixos-config.
I'm not using NixOS anymore for a few years already so I'm afraid I can't try and reproduce this issue.
