### ISSUE TITLE
nixos-unstable hasn't updated for 2 weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#49384]
The [`nixos-unstable` channel](https://github.com/NixOS/nixpkgs-channels/commits/nixos-unstable) has not updated for 2 weeks and according to https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents there are still plenty of test failures in current versions of `master` to prevent updates in the very near future.

**Comment by srhb** [comment]
The current failures seem strongly correlated with:

1) being "installer" tests (/rebooting internally)
2) timed out waiting for the VM to connect (300 sec timeout)
3) packet-epyc-1

They occur on release-18.09 as well, subjectively it looks like the same frequency of failures.

I also notice that error is occurring much, much more frequently after the new VM backdoor was added. I am not sure whether there *is* any correlation though, but maybe someone could proofread those changes.

I am unable to reproduce the failure locally unless I reduce the timeout to 5 seconds (from 300!)
The dmesg spam appears to suggest that the VMs tend to spend nowhere near as long (usually 30 seconds, still a factor of 10 off) starting up.

I personally don't feel that it's really a load/timeout issue, but the only idea I have for testing it out is to actually increase the timeout in `nixos/lib/test-driver/Machine.pm` to something obscene.

**Comment by srhb** [comment]
> 3. packet-epyc-1
I its frequency is likely to be because it just gets the jobs much more often

> I also notice that error is occurring much, much more frequently after the new VM backdoor was added.
@domenkozar @dezgeg Can you maybe help me convince myself this is just me being superstitious? :-) It's a little difficult to go through the older failures and see if this is really true, and I don't quite understand the actual changes in the test instrumentation.

**Comment by markuskowa** [comment]
I am not sure it this related to the delayed channel update but it seems hydra had a huge backlog of build jobs. It seem like it is still building a nixpkgs:trunk version from 4 days ago (https://hydra.nixos.org/jobset/nixpkgs/trunk/evals?page=2).

**Comment by vcunat** [comment]
The main blocker ATM seems [chromium](https://github.com/NixOS/nixpkgs/issues/49442).  It's even possible that _those_ builds exhaust some resources and consequently fail some nixos tests.  I assume just running a few chromium builds at once on a machine is quite a stress-test.

**Comment by srhb** [comment]
Ah, I understand now. It's the actual chromium build cycling, not the test.

**Comment by vcunat** [comment]
Yes, I meant chromium builds, not chromium tests.

**Comment by edolstra** [comment]
This is probably caused by https://github.com/NixOS/nix/issues/2493.

**Comment by dezgeg** [comment]
The debugging backdoor just adds a new virtualized serial port. It shouldn't affect the existing ports in any way. Of course if there is some race condition it could affect timings.

One thing that seems suspicious is that the dmesg timestamp sometimes jumps backwards, e.g in https://hydra.nixos.org/build/83162004 has:
````
machine# [    6.886877] mousedev: PS/2 mouse device common for all mice
machine# [   18.125198] powernow_k8: Power state transitions not supported
machine# [    8.761331] systemd[1]: Found device Virtio network device.
machine# [    8.769515] systemd[1]: Found device /dev/ttyS0.
machine# [   18.151414] EDAC MC: Ver: 3.0.0
machine# [   18.164716] MCE: In-kernel MCE decoding enabled.
machine# [   18.283728] [drm] Found bochs VGA, ID 0xb0c0.
machine# [   18.284843] [drm] Framebuffer size 16384 kB @ 0xfd000000, mmio @ 0xfebd0000.
machine# [    8.916688] systemd[1]: Found device /dev/hvc0.
machine# [    8.922226] systemd[1]: Found device /dev/hvc1.
machine# [   18.304981] [TTM] Zone  kernel: Available graphics memory: 508402 kiB
machine# [   18.306432] [TTM] Initializing pool allocator
machine# [   18.316878] [TTM] Initializing DMA pool allocator
machine# [   23.066463] ppdev: user-space parallel port driver
machine# [   28.684386] fbcon: bochsdrmfb (fb0) is primary device
machine# [   28.755161] Console: switching to colour frame buffer device 128x48
machine# [   28.823769] bochs-drm 0000:00:02.0: fb0: bochsdrmfb frame buffer device
machine# [   28.826605] [drm] Initialized bochs-drm 1.0.0 20130925 for 0000:00:02.0 on minor 0
machine# [   28.884951] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4
machine# [   10.361634] systemd[1]: Started Firewall.
machine# [   10.363826] systemd[1]: Reached target Network (Pre).
machine# [   10.824250] systemd[1]: Started udev Wait for Complete Device Initialization.
machine# [   10.827169] systemd[1]: Reached target System Initialization.
machine# [   10.835099] systemd[1]: Listening on D-Bus System Message Bus Socket.
machine# [   10.854768] systemd[1]: Listening on Nix Daemon Socket.
machine# [   10.885524] systemd[1]: Reached target Sockets.
machine# [   10.908122] n67lgc40cas892bsdb0llz0gkvwa5ljm-unit-script-network-addresses-eth1-start[585]: adding address 192.168.1.1/24... done
machine# [   10.919171] systemd[1]: Reached target Basic System.
machine# [   10.932285] systemd[1]: Starting Address configuration of eth1...
machine# [   10.937313] nscd[612]: 612 monitoring file `/etc/passwd` (1)
machine# [   10.944325] a1zbfqipa1sl4bnnayla17z5p48kxiza-audit-disable[587]: No rules
machine# [   10.950546] systemd[1]: Started NixOS Manual.
machine# [   34.394196] 8021q: 802.1Q VLAN Support v1.8
machine# [   34.395465] 8021q: adding VLAN 0 to HW filter on device eth1
machine# [   10.967222] nscd[612]: 612 monitoring directory `/etc` (2)
machine# [   10.979572] fmik28sp6likfml7gjcqxqaqrhk7s8qk-unit-script-network-link-eth1-start[592]: Configuring link...
machine# [   10.983993] fmik28sp6likfml7gjcqxqaqrhk7s8qk-unit-script-network-link-eth1-start[592]: bringing up interface... done
machine# [   11.508796] systemd[1]: Starting Kernel Auditing...
````

I don't know if that's expected behaviour but maybe we dropping this might affect things:
````
    boot.initrd.postDeviceCommands =
      ''
        # Using acpi_pm as a clock source causes the guest clock to
        # slow down under high host load.  This is usually a bad
        # thing, but for VM tests it should provide a bit more
        # determinism (e.g. if the VM runs at lower speed, then
        # timeouts in the VM should also be delayed).
        echo acpi_pm > /sys/devices/system/clocksource/clocksource0/current_clocksource
      '';
````

**Comment by vcunat** [comment]
After help from multiple people I now see just hibernation test failing reproducibly in both branches.

**Comment by dezgeg** [comment]
The error message is from systemd, and in https://hydra.nixos.org/api/scmdiff?rev2=d1de23b8302d02d4699e884533906a3992f370b6&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev1=89fb76c51ced36d1bc5821e51e7327b7150f25a2&branch=&type=git there is only one relevant change: d1de23b8302d02d4699e884533906a3992f370b6

**Comment by dezgeg** [comment]
Probably caused by https://github.com/NixOS/systemd/commit/6789dca0a26df0c44ff8020f0a4206bf21e52a7a#diff-897a4693906dd8751a19d0c70f1f4207

**Comment by vcunat** [comment]
Channel up to date :tada:

**Comment by davidak** [comment]
The last 8 builds on **nixos:release-18.09:tested** failed again with "error: timed out waiting for the VM to connect".

Mostly installer tasks and "nixos.tests.gnome3.x86_64-linux".

Latest: https://hydra.nixos.org/build/85309024#tabs-constituents

Last successful nixos-unstable update was 15 days ago.

Could it have the same reason?

**Comment by nyanloutre** [comment]
There previously was a bug with curl that made the ipv6 test failed for more than a week (until 2018-11-30).

Last job is today : https://hydra.nixos.org/build/85309672

The jobs with errors are seemingly random and the error is nearly every time "error: timed out waiting for the VM to connect"

**Comment by vcunat** [comment]
Lately I relatively often see transient nixos test errors from `packet-epyc-1`; I suspect it may get overloaded occasionally.

I can only guess why that happens.  One possibility: some derivations don't use `make -l$NIX_BUILD_CORES` or similar &ndash; I find that very annoying locally, as I have a cheap 16-threaded desktop and 16*16 is way too much (`--cores` + `--max-jobs`).

**Comment by markuskowa** [comment]
@vcunat an overload may not only be caused by improper make -j/-l flags but also by test routines. Numerical computing packages such as `arpack`, `openblas`, `scalapack`, etc. run multi-threaded tests, which use all cores in the system by default. 
The only safe, long-term solution to the overload problem is to constrain builds with cgroups?
