### ISSUE TITLE
Document use of Haskell packages in Nix(OS)

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#4941]
The Nixpkgs manual should explain how to install and use Haskell packages with Nix. We don't need to cover everything; but we should cover the basics and link to some additional blogs and Wiki pages that other people have written already.

Also: We need a ChangeLog for the 15.06 release in `nixos/doc/manual/release-notes/rl-unstable.xml`.

**Comment by peti** [comment]
- [A Journey into the Haskell NG infrastructure: Part I](http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015600.html)
- [A Journey into the Haskell NG infrastructure: Part II](http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015608.html)

**Comment by iElectric** [comment]
http://wiki.ocharles.org.uk/Nix#how-do-i-use-cabal2nix-for-local-projects

**Comment by peti** [comment]
@ocharles, I like your idea of running only `cabal configure` in the `nix-shell` environment. This works really well, and recent versions of `haskell-mode` handle this nicely in Emacs, too!

One thing that *might* not work is running `cabal test`. The `nix-shell` environment sets the environment variable `$NIX_GHC_LIBDIR` properly, and this allows tools like `doctest` to find the 3rd-party libraries that exist in this environment. Outside of the `nix-shell` environment, this might not work. This issue will affect only a fraction of the existing test suites, but I suppose it's good to know that this *might* happen.

**Comment by ocharles** [comment]
Ah, that's worth keeping in mind then.

About haskell-mode, I'm actually using it inside `nix-shell` - recent versions have direct support for `nix-shell`. I have the following:

```emacs
 '(haskell-process-type (quote cabal-repl))
 '(haskell-process-wrapper-function
   (lambda
     (argv)
     (append
      (list "nix-shell" "-I" "." "--command")
      (list
       (mapconcat
        (quote identity)
        argv " ")))))
```

That runs `cabal-repl` inside a `nix-shell`.

**Comment by peti** [comment]
The new haskell-mode is awesome. The only downside is that it doesn't seem to play nicely with ghc-mod. When I run both, my interaction sessions freeze ever minute or so, regardless of what I do or don't do.

**Comment by rzetterberg** [comment]
After digging around different wikis, mailing lists and looking at the nix source for haskell-ng I posted [a wiki question on Stackoverflow](http://stackoverflow.com/questions/29033580/how-do-i-use-the-new-haskell-ng-infrastructure-on-nixos/29033581) about how you use haskell-ng on NixOS.

Is there anything I could help with regarding the documentation? Maybe some of the information in my answer could be used?

**Comment by peti** [comment]
Document the findings from https://github.com/NixOS/nixpkgs/issues/7792, too.

**Comment by peti** [comment]
Thanks to the efforts of @garbas, we now have a video of a presentation that provides a gentle introduction to Haskell NG for beginners at https://www.youtube.com/watch?v=BsBhi_r-OeE. The slides are at http://cryp.to/nixos-meetup-3-slides.pdf, and all sample config snippets can be found at https://github.com/NixOS/cabal2nix/blob/master/doc/nixos-meetup-3-slides.md.

**Comment by Profpatsch** [comment]
Edited the Wiki page with a manual on how to work around the nondeterminism. https://nixos.org/wiki/Haskell#GHC_Nondeterminism

**Comment by peti** [comment]
https://github.com/NixOS/cabal2nix/blob/master/doc/user-guide.md is almost complete and about to be merged into the Nixpkgs documentation. If someone has a moment to spare and is willing to proofread the document for mistakes or omissions, then that would be very helpful!

**Comment by steshaw** [comment]
@peti, I just came across the user guide. Happy to proofread.
