### ISSUE TITLE
Incompatibility between nixpkgs.pkgs option and files from nixos-generate-config

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nixpkgs#49424]
nixos-generate-config can produce `hardware-configuration.nix` files that depend on `<nixpkgs>`, which can screw up evaluations that are using pinned versions of nixpkgs via the `nixpkgs.pkgs` option. If `<nixpkgs>` points to a version of nixpkgs that's significantly different than the one pinned via `nixpkgs.pkgs`, the evaluation can fail in spooky and byzantine ways.

Example:
```
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];
```

IMO this limits use of the `nixpkgs.pkgs` option to only extremely expert nix powerusers. There's no way an intermediate Nix or NixOps user would be able to discern what's wrong from the kinds of failures this can produce.

**Comment by Artturin** [comment]
Fixed because modulePath is being used now
