### ISSUE TITLE
Request to package dvc

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#49438]
## Issue description

dvc (https://github.com/iterative/dvc) is version control system for "biggish" data and code

It integrates with Git but offers a solution for managing and versioning big data sets that come with code commits.

Related technology (https://github.com/iterative/dvc#related-technologies) are like git annex and git lfs.

If nobody gets around to this, I may work on this later.

**Comment by CMCDragonkai** [comment]
Need to first package nanotime, grandalf and asciimatics dependencies first.

**Comment by CMCDragonkai** [comment]
Google cloud storage is packaged already here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/google_cloud_storage/default.nix

However `azure-storage-blob` is still not packaged as `azure-storage` is though. The pypi is: https://pypi.org/project/azure-storage-blob/

**Comment by CMCDragonkai** [comment]
Initial PR for azure-storage: https://github.com/NixOS/nixpkgs/pull/54261

**Comment by CMCDragonkai** [comment]
Inital PR for nanotime: https://github.com/NixOS/nixpkgs/pull/54399

**Comment by CMCDragonkai** [comment]
Initial PR for grandalf: https://github.com/NixOS/nixpkgs/pull/54403

**Comment by CMCDragonkai** [comment]
Initial PR for asciimatics: https://github.com/NixOS/nixpkgs/pull/54404

**Comment by worldofpeace** [comment]
@CMCDragonkai For the smaller dependent packages that are unrelated it would have been preferred to group them in one pr.

**Comment by worldofpeace** [comment]
However too late now :smile: so just to know in the future.

**Comment by CMCDragonkai** [comment]
@worldofpeace Yea that would have been better as I could have then worked on dvc commit as well, but now that all dependent packages are separated between different branches, that's not possible. So I'm just waiting for those to be merged to master.

**Comment by CMCDragonkai** [comment]
Initial PR for dvc: https://github.com/NixOS/nixpkgs/pull/54530
