### ISSUE TITLE
pgloader was removed without replacement

### ISSUE THREAD

**Issue by mguentner** [NixOS/nixpkgs#49478]
## Issue description

I want to use pgloader but I can't.

It was partly removed in cd7bfa6f48295f361c691a7520fb122938bd2a68

### Steps to reproduce

`nix-shell -p lispPackages.pgloader`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by xeji** [comment]
cc @7c6f434c

**Comment by 7c6f434c** [comment]
I am not sure it worked at the moment of removal… It's a bit of a showcase how _not_ to structure dependencies.

**Comment by mguentner** [comment]
Thanks. I hacked together a derivation that works without using this `lispPackages` madness.
I hope I can find time to upstream it with a pull request.

Until then and for the record here it is: https://gist.github.com/mguentner/a37d33185c6b85b9af01cdf4b6a8cdee

**Comment by 7c6f434c** [comment]
`lispPackages` are relatively straightforward… `quicklispPackages` try to get scalability of grabbing packages from Quicklisp, and there is a nasty price, sure.

As an application-only package your expression is fine (it would be nice to have `meta` before inclusion in Nixpkgs).

**Comment by mguentner** [comment]
@7c6f434c I am trying to work out how to get pgloader into NixOS again.
Currently (master) my derivation does not work because the created `bundle` w/ all quicklisp dependencies contains a library that uses an internal api of sbcl that was removed/changed in 1.4.11. 

You can follow the discussion here:

https://github.com/dimitri/pgloader/issues/832#issuecomment-436645680

From my current point of view, I will wait for the release of 3.6.1 and use the bundle as
I did not manage to create a `fixedOutputHash` derivation for the dependencies (I even wrote a custom Make step!) that is reproducible.

**Comment by 7c6f434c** [comment]
Oh well, I would accept a PR that would temporarily readd SBCL expression from an old expression as `sbcl_1_4_…` and use it for pgloader. Waiting for upstream is also a solid plan, of course.

**Comment by danbst** [comment]
@mguentner pgloader 3.6.1 is out and compiles when built via your expression

**Comment by mguentner** [comment]
@danbst Very well. I will upstream it soon.

**Comment by mguentner** [comment]
As promised :point_up_2:

**Comment by mguentner** [comment]
closed through #61702
