### ISSUE TITLE
Make "libc" overridable (like a normal library)

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#49481]
This is part of my roadmap for cross compilation. I've talked with @ericson2314 about this, and I think it solves some of the issues we have had with Musl. Here are the things to be done:

- [ ] Implement "crossOverlays" that use the cross stdenv without actually using a cross compiler (#48803). Packages overriden in crossOverlays take effect in the /target packages/ only.
- [ ] Add a "libc" attr that goes to the libc being used. (glibc on Linux, libSystem on macOS)
- [ ] Have pkgsMusl just use crossOverlays. This will hopefully avoid some of the awkwardness around https://github.com/NixOS/nixpkgs/commit/01dfe3f56019b0c330bc2e46da90146698844330. The implementation should be pretty straightforward. Just something like this:

```nix
{
  pkgsMusl = nixpkgsFun {
    inherit overlays config;
    crossOverlays = [
      (self: super: { libc = super.musl; })
    ];
  };
}
```

/cc @dtzWill

**Comment by dtzWill** [comment]
Neat! We will likely still want a way to check which libc is being used-- while we should avoid this where possible it's still needed in a number of places.  I'm not picky how this is addressed, perhaps a passthru on libc or something?

**Comment by Ericson2314** [comment]
Isn't just a dup of https://github.com/NixOS/nixpkgs/issues/26004 ? :D Feel free to amend that issue's OP.

**Comment by matthewbauer** [comment]
Oops forgot about that! I guess the added thing now is it could make things easier with musl and the cross vs. local distinction.
