### ISSUE TITLE
Research why was `pythonPath` parameter to `buildPythonPackage` introduced

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4949]
and remove it if redundant.

**Comment by iElectric** [comment]
Done. I'll look into `pythonPath` parameter and see if we can deprecate it.

**Comment by domenkozar** [comment]
So `pythonPath` is needed for `wrapPythonPrograms` bash function that wraps binaries in `bin`

**Comment by Profpatsch** [comment]
(triage) can probably be closed @domenkozar

**Comment by tadfisher** [comment]
(triage) any action needed?

**Comment by Profpatsch** [comment]
Will close now, reopen if needed @domenkozar
