### ISSUE TITLE
List of not up-to-date linux kernels in nixpkgs

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#49490]
## Issue description

- [x] linux_riscv: @shlevy (current: 4.16-rc6, latest: 4.17)
- [x] linux_beagleboard: @dhess (current: 4.14.12, latest: 4.19-ti-r1)
- [x] linux_samus:  @zohl  (current: 4.12.2, latest: 4.16)
- [x] linux_hardkernel: @qolii (current: 4.14.73-149, latest: 4.14.78-150)

**Comment by dhess** [comment]
Unfortunately I’m not able to maintain the BeagleBoard kernel anymore (no more access to hardware).

**Comment by qolii** [comment]
`linux-hardkernel` done! (#49535) Thanks for the nudge.

**Comment by Mic92** [comment]
@dhess apparently it is possible now to also use the beagle board with mainline kernels.
It should be a matter of copying the right dtb file.

**Comment by shlevy** [comment]
Fixed, thanks!

**Comment by Mic92** [comment]
Samus and beagleboard were removed as well.
