### ISSUE TITLE
SBCL Does not include Info manual

### ISSUE THREAD

**Issue by swflint** [NixOS/nixpkgs#49539]
## Issue description

SBCL currently does not ship with the manual in 'info' format.

### Steps to reproduce

`nix-shell -p sbcl --run 'info sbcl'` shows the man page, not the manual in 'info' format.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 19.03pre155751.45a419ab5a2 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(swflint): `"nixpkgs-18.09pre140158.640b6359ae3"`
 - channels(root): `"nixos-19.03pre155751.45a419ab5a2, unstable-18.09pre143771.a8c71037e04, nix1709-17.09.3263.9e1d8b74706, nix1803-18.03"`
 - nixpkgs: `/home/swflint/.nix-defexpr/channels/nixpkgs

**Comment by xeji** [comment]
cc maintainers @tohl @7c6f434c

**Comment by tohl** [comment]
https://github.com/NixOS/nixpkgs/pull/49555

**Comment by xeji** [comment]
fixed in 49555.
