### ISSUE TITLE
Please update to vtk 8.2.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#49531]
Current version is at 7.0.0 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/vtk/default.nix

**Comment by luzpaz** [comment]
@c0deaddict I started a PR at https://github.com/ANTsX/ANTs/pull/656
Feel free to mention any more blocking issues

**Comment by luzpaz** [comment]
New upstream release 8.2.0  
https://blog.kitware.com/vtk-8-2-0/

**Comment by luzpaz** [comment]
Can someone compile a list of packages that use a VTK as a dependency that will be impacted by this version bump ?

**Comment by luzpaz** [comment]
@c0deaddict is there a bot command that can check what other dependencies besides the above https://github.com/NixOS/nixpkgs/issues/49531#issuecomment-435128455 ANTsX dependency (which is now fixed btw) is breaking due to this update ?

**Comment by c0deaddict** [comment]
No idea if such a command exists, what I usually do is search through the nixpkgs repo: https://github.com/nixos/nixpkgs/search?p=1&q=vtk This shows vtk itself, and 11 other derivations that depend upon vtk.

**Comment by angus-g** [comment]
Would it make sense to leave the default version of VTK at 7.0.0, but add a vtk8 that can be switched to once dependencies don't break?

**Comment by luzpaz** [comment]
@angus-g This is what other package repos are doing as well.

**Comment by luzpaz** [comment]
bump
