### ISSUE TITLE
bitwig-studio1 is crashing since 18.09

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#49530]
## Issue description

Since 18.09 I can't use bitwig-studio1 anymore. I'm currently investigating. I opened this ticket to get ideas and maybe help other people who have similar issues.

### Steps to reproduce

* start jack
* use bitwig-studio1 (only by mouse) => everything is fine
* press a key (like `tab` or `a`) => crash

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 18.09.git.06fb025 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(palo): `""`
 - channels(root): `"nixos-18.03.133245.d16a7abceb7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mrVanDalo** [comment]
I had no time so far to fix it but this issue is not dead.

**Comment by Mic92** [comment]
you could try to open an issue here: https://github.com/xkbcommon/libxkbcommon/issues

**Comment by Mic92** [comment]
cc @abique @vosc

**Comment by abique** [comment]
Use the latest version of Bitwig Studio.

**Comment by Mic92** [comment]
Fair enough. @mrVanDalo are there any reason we keep bitwig1 in nixpkgs when we have bitwig 2 already?

**Comment by mrVanDalo** [comment]
@Mic92 @abique Yes, Bitwig lizenses cost money. Why we have different Bitwig versions is discussed here #32206

This issue is not about bitwig-studio1 or bitwig-studio2 it is about how is the standard way to build bitwig-studio1 with another library of libxkbcommon than the latest version.

**Comment by mrVanDalo** [comment]
This one is closed
