### ISSUE TITLE
Intel Wireless 7260 not detected

### ISSUE THREAD

**Issue by Vskilet** [NixOS/nixpkgs#49580]
## Issue description
I installed Nixos 18.09 on a Thinkpad T440p with the stable channel but my wifi card isn't detected.
with `lspci` I can see the interface but not with an `ip a`.
I tried different things like : 
```
boot.kernelModules = [ "iwlwifi" ];
boot.extraModprobeConfig = ''
  options iwlwifi bt_coex_active=0 power_save=Y
  options iwldvm force_cam=N
'';

```

### Steps to reproduce
```
# lscpi
[...]
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev bb)
```

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 68:f7:28:a7:d8:45 brd ff:ff:ff:ff:ff:ff
```

## Technical details

My system infos : 
```
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by emmanuelrosa** [comment]
Does the `iwlwifi` module need firmware? If so, you'll need to identify which package has the firmware you need and add it to `hardware.firmware` in `configuration.nix`.

**Comment by c0bw3b** [comment]
`# dmesg | grep wifi` ?

`$ nixos-option hardware.enableRedistributableFirmware`

**Comment by Vskilet** [comment]
Thanks @c0bw3b that was `hardware.enableRedistributableFirmware`. I didn't known this options.

**Comment by c0bw3b** [comment]
To be more complete if someone finds this issue later:
`hardware.enableRedistributableFirmware = true` allows your system to pull [`firmwareLinuxNonfree`](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/) which in turn gives you the firmware you want.
In this case you were probably missing was `iwlwifi-7260-17.ucode`

Also relevant:
https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi

**Comment by adc17** [comment]
I hope it's ok to resurrect this; I'm experiencing the same issue on the same device (but running nixos 19.09). `hardware.enableRedistributableFirmware = true` and here is my output from `dmesg | grep wifi`: 

```
[    3.187234] iwlwifi 0000:03:00.0: loaded firmware version 17.3216344376.0 op_mode iwlmvm
[    3.262851] iwlwifi 0000:03:00.0: Detected Intel(R) Wireless N 7260, REV=0x144
[    3.280326] iwlwifi 0000:03:00.0: base HW address: 5c:c5:d4:d2:bd:a6
[    3.948900] iwlwifi 0000:03:00.0 wlp3s0: renamed from wlan0
```

Does anyone know what I might be missing here?
