### ISSUE TITLE
atlas fails to build

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#49594]
`atlas` has been broken in master since 2018-10-18:

https://hydra.nixos.org/build/82965121

The last successful build was 2018-10-13:

https://hydra.nixos.org/build/82713877

Here's the log tail of the failed build:

https://hydra.nixos.org/build/82965121/nixlog/1/tail

**Comment by ttuegel** [comment]
I will investigate this issue, but in the mean time: ATLAS is not actively developed upstream; use OpenBLAS instead.

**Comment by bhipple** [comment]
I ran into this 6+ months ago, and remember using an overlay to use lapack without atlas for a dependency to get it to build.  Figured at the time it was just my weird setup failing!

**Comment by dhess** [comment]
@ttuegel It's a package I've created in an overlay for something that's not packaged by Nixpkgs. I don't object if you remove `atlas` from Nixpkgs.
