### ISSUE TITLE
Can not install Nix

### ISSUE THREAD

**Issue by s50600822** [NixOS/nixpkgs#49621]
## Issue description

Last login: Thu Nov  1 18:13:28 on ttys016
[Oh My Zsh] Would you like to update? [Y/n]: 	curl https://nixos.org/releases/nix/nix-2.0/install | shY
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local/Cellar/nvm/0.33.11/versions/node/v6.11.1"
Run `npm config delete prefix` or `nvm use --delete-prefix v6.11.1 --silent` to unset it.
➜  ~    curl https://nixos.org/releases/nix/nix-2.0/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2455  100  2455    0     0   1450      0  0:00:01  0:00:01 --:--:--  1450
downloading Nix 2.0 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-2.0/nix-2.0-x86_64-darwin.tar.bz2' to '/var/folders/hq/xc823d1x0y157v7k_swfl7wc0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.jNfpUE5I'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.0M  100 25.0M    0     0  1502k      0  0:00:17  0:00:17 --:--:-- 1775k
Switching to the Multi-User Darwin Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old one.

2. Show you what we are going to install and where. Then we will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what we will do?
No TTY, assuming you would say yes :)

We will:

 - make sure your computer doesn't already have Nix files
   (if it does, I  will tell you how to clean them up.)
 - create local users (see the list above for the users we'll make)
 - create a local group (nixbld)
 - install Nix in to /nix
 - create a configuration file in /etc/nix
 - set up the "default profile" by creating some Nix-related files in
   /var/root
 - back up /etc/bashrc to /etc/bashrc.backup-before-nix
 - update /etc/bashrc to include some Nix configuration
 - back up /etc/zshrc to /etc/zshrc.backup-before-nix
 - update /etc/zshrc to include some Nix configuration
 - load and start a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon

Ready to continue?
No TTY, assuming you would say yes :)

---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Normally, it would show you
exactly what commands it is running and why. However, the script is
run in a headless fashion, like this:

  $ curl https://nixos.org/nix/install | sh

or maybe in a CI pipeline. Because of that, we're going to skip the
verbose output in the interest of brevity.

If you would like to
see the output, try like this:

  $ curl -o install-nix https://nixos.org/nix/install
  $ sh ./install-nix

Password:

---- hardware report -----------------------------------------------------------
           Cores:	12

---- Nix config report ---------------------------------------------------------
        Temp Dir:	/var/folders/hq/xc823d1x0y157v7k_swfl7wc0000gn/T/tmp.XXXXXXXXXX.f29Khka6
        Nix Root:	/nix
     Build Users:	32
  Build Group ID:	30000
Build Group Name:	nixbld

build users:
    Username:	UID
     nixbld1:	30001
     nixbld2:	30002
     nixbld3:	30003
     nixbld4:	30004
     nixbld5:	30005
     nixbld6:	30006
     nixbld7:	30007
     nixbld8:	30008
     nixbld9:	30009
     nixbld10:	30010
     nixbld11:	30011
     nixbld12:	30012
     nixbld13:	30013
     nixbld14:	30014
     nixbld15:	30015
     nixbld16:	30016
     nixbld17:	30017
     nixbld18:	30018
     nixbld19:	30019
     nixbld20:	30020
     nixbld21:	30021
     nixbld22:	30022
     nixbld23:	30023
     nixbld24:	30024
     nixbld25:	30025
     nixbld26:	30026
     nixbld27:	30027
     nixbld28:	30028
     nixbld29:	30029
     nixbld30:	30030
     nixbld31:	30031
     nixbld32:	30032

Ready to continue?
No TTY, assuming you would say yes :)

~~> Setting up the build group nixbld
            Exists:	Yes

~~> Setting up the build user nixbld1
            Exists:	Yes
          IsHidden:	Yes
<main> attribute status: eDSPermissionError
<dscl_cmd> DS Error: -14120 (eDSPermissionError)

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org
➜  ~

### Steps to reproduce

curl https://nixos.org/releases/nix/nix-2.0/install | sh

## Technical details

➜  ~ nix-shell -p nix-info --run "nix-info -m"
zsh: command not found: nix-shell

XD

I'm on macOS Mojave 10.14

**Comment by FRidh** [comment]
Yep, this is the wrong repo.
