### ISSUE TITLE
google-chrome-unstable broken: error loading shared libraries: libatspi.so.0

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#49634]
## Issue description

`$ google-chrome-unstable`

`/nix/store/8qnr5zbdvip0wy7playvi52hhbwls1dj-google-chrome-dev-71.0.3559.6/share/google/chrome-unstable/google-chrome-unstable: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory`

nixpkgs rev = [c70ad805d216f18f91d2b0786b4ce248917153bb](https://github.com/nixos/nixpkgs/commits/c70ad805d216f18f91d2b0786b4ce248917153bb)

### Steps to reproduce

`nix-env -iA google-chrome-unstable`, then try to execute it.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.03.git.c78fbc91870 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by aij** [comment]
This affects `google-chrome-beta` too now (as of nixpkgs-unstable 19.03pre158246.6141939d6e0)

```
$ google-chrome-beta 
/nix/store/g4q6zwdcfgfcvjsjjkwn8xxj7bsq2hg7-google-chrome-beta-71.0.3578.20/share/google/chrome-beta/google-chrome-beta: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory
```

**Comment by sorenbug** [comment]
![image](https://user-images.githubusercontent.com/7751296/49226545-cd9e8a80-f39b-11e8-92a2-aabd6a2c7134.png)
I'm still getting this issue for some reason. Is there something I need to do to update my nix packages?

**Comment by kkweon** [comment]
Same issue for `google-chrome-stable`  I'm on nixos 18.09
Is there any workaround?

```
$ google-chrome-stable
/nix/store/c29a8jwi02jffc2xhlgk6xpm4x8wljnf-google-chrome-71.0.3578.80/share/google/chrome/google-chrome: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory
```

**Comment by peterhoeg** [comment]
#49636 has already hit stable. Can you confirm it's working for you @kkweon ?

**Comment by kkweon** [comment]
Confirmed it is fixed. Thank you!!
