### ISSUE TITLE
NixOS cross-compile support

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#4963]
There is good support for cross-compilation in nixpkgs, but as far as I can tell, none in NixOS. This has a drastic impact on the usefulness of cross-compiling within Nix.

Ideally one would be able to:
- Build a cross-compiled system configuration.
- Deploy the system to a local storage medium (like nixos-install).
- Deploy the system via nixops (basic ssh deployment).
- Build a target-specific firmware image (where applicable).

I am prepared to work on this, but I would first like some guidence from people familiar with the NixOS code.

**Comment by gitfoxi** [comment]
Did you ever come up with a way to cross-compile Nix?

If only Nix could be stripped of its many dependencies for the porting use-case. One idea I'm thinking about is to use Buildroot to build Nix's dependencies and Nix and then off to the races in the Qemu or maybe even compile on a development board with lots of RAM. If you had enough of them to use as build slaves it could go pretty quick to build a full NixOS.

**Comment by ambrop72** [comment]
I just installed ArchLinuxArm on my ARM boards (RPi, RPi2, BBB) and "manually" compiled Nix natively (with the AUR package really). Note, Nix depends on Perl so I think this is too much effort to be worth pursuing.

**Comment by gitfoxi** [comment]
ArchLinuxArm is something I didn't know about. FWIW Buildroot can build Perl. Sometimes.

**Comment by bjornfor** [comment]
Reminds me, I have an old WIP branch which pulls in the Perl cross-complie fixes from Buildroot:

https://github.com/bjornfor/nixpkgs/tree/cross-compile-fixes

**Comment by tomberek** [comment]
Duplicate? #14965 and others.

**Comment by Ericson2314** [comment]
CC @bgamari, who has made great progress here.

**Comment by Ericson2314** [comment]
@shlevy we can close this now, right?

**Comment by shlevy** [comment]
Haven't tried in a few months, but it was working for me a while back.

**Comment by Ericson2314** [comment]
Thanks @shlevy. I guess I'll leave open until we have CI.

**Comment by volth** [comment]
NixOS cross-compilation generally works, but there is an issue which might need continuous attention: huge closure sizes which often include build platform binaries.

Perhaps an alert of cross-platform dependencies should be added to ```stdenv``` and a cross-compilation test to the Hydra tests (because cross-compilation is not what people do often, it has been broken for a month and no one spotted).

This would allow to break unnecessary dependencies and reduce closure sizes even when cross-compilation is not involved. Cross-compilation just helps to see those unnecessary dependencies because they become cross-platform.

**Comment by Ericson2314** [comment]
Yes I think it high time we do proper CI for an entire cross package set.

**Comment by illegalprime** [comment]
are there updates / docs yet on how to cross compile nixos itself? I would be interested in furthering that goal..

**Comment by tomberek** [comment]
@illegalprime the last time I did this I had to cross-compile Nix, which then compiled (gcc itself, binutils, linux, everything) NixOS natively for a few days. I’m also interested in any progress in cross-compiling directly to NixOS and better binary cache support.

**Comment by bgamari** [comment]
I have uploaded the NixOS configuration that I have been trying to use for the MacchiatoBin AArch64 SBC [here](https://github.com/bgamari/mcbin.nix). It doesn't yet boot due to kernel issues but user-space (and consequently the NixOS configuration) is likely fine.

**Comment by illegalprime** [comment]
@bgamari I don't have that board available, but https://github.com/bgamari/mcbin.nix/blob/master/configuration.nix#L22 was really helpful to see how to get cross-compiled packages in a NixOS configuration. What I got is: Beaglebone Green, RPi 2, NanoPi M4, Odroid C1+, Odroid C2, RPi Zero.
I'll go try it on one of those & see!

**Comment by illegalprime** [comment]
I was able to cross compile a NixOS image for ARMv7 on my BeagleBone Green after quite a lot of cross-compilation fixes in `nixpkgs`:
```
<<< Welcome to NixOS 19.09.git.088cecc (armv7l) - ttyO0 >>>

Run `nixos-help` for the NixOS manual.

nixos-on-arm login: root (automatic login)


[root@nixos-on-arm:~]$ 
```

**Comment by illegalprime** [comment]
Here's the progress I've made so far: https://github.com/illegalprime/nixos-on-arm

**Comment by AleXoundOS** [comment]
Still important to me.

**Comment by stanipintjuk** [comment]
Me aswell

**Comment by Ericson2314** [comment]
@matthewbauer should we close this?
