### ISSUE TITLE
Cannot build bazel-deps

### ISSUE THREAD

**Issue by backuitist** [NixOS/nixpkgs#49640]
## Issue description

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
ERROR: error loading package '': Encountered error while reading extension file 'scala/scala.bzl': no such package '@io_bazel_rules_scala//scala': Traceback (most recent call last):
        File "/build/output/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
                _clone_or_update(ctx)
        File "/build/output/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_scala:
+ cd /build/output/external
+ rm -rf /build/output/external/io_bazel_rules_scala /build/output/external/io_bazel_rules_scala
+ git clone git://github.com/bazelbuild/rules_scala /build/output/external/io_bazel_rules_scala
Cloning into '/build/output/external/io_bazel_rules_scala'...
fatal: unable to look up github.com (port 9418) (Name or service not known)
```

### Steps to reproduce

`nix-env -iA nixpkgs.bazel-deps`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(bruno): `"nixpkgs-19.03pre156996.c70ad805d21, unstable-19.03pre157646.f129ed25a04"`
 - channels(root): `"nixos-18.09.932.09195057114"`
 - nixpkgs: `/home/bruno/.nix-defexpr/channels/nixpkgs`

**Comment by backuitist** [comment]
@uri-canva ^

**Comment by uri-canva** [comment]
Sorry about that, seems like I broke it when I update `bazel`, I guess something changed with how `bazel fetch` works. The new version of `bazel-deps` has dependencies declared in a way that interacts correctly with `bazel fetch` in the current version of `bazel`, so I updated it: #49738.
