### ISSUE TITLE
youtube-dl fails to build due to stdenv-linux

### ISSUE THREAD

**Issue by AveryLychee** [NixOS/nixpkgs#49667]
## Issue description

After trying to install the latest version (2018.10.29) of youtube-dl, I get the following error:

```
output '/nix/store/v5acham4yfws3hmychl3mh8rgjln3wqs-stdenv-linux' is not allowed to refer to the following paths:
      /nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox
    /nix/store/n9acaakxahkv1q3av11l93p7rgd4xqsf-bootstrap-tools
output '/nix/store/ww7996di1rai32l0c9gm46m2l126rxbp-stdenv-linux' is not allowed to refer to the following paths:
      /nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox
    /nix/store/n9acaakxahkv1q3av11l93p7rgd4xqsf-bootstrap-tools
cannot build derivation '/nix/store/c539jj0b89xc65nv0q4j76m8yvg0qhx2-python3.6-youtube-dl-2018.10.29.drv': 1 dependencies couldn't be built
error: build of '/nix/store/c539jj0b89xc65nv0q4j76m8yvg0qhx2-python3.6-youtube-dl-2018.10.29.drv' failed
```

### Steps to reproduce

The same issue occurs with both the master branch and the release-18.09 branch.

Type `nix-env -f 'path/to/nixpkgs' -iA youtube-dl`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 18.09.1023.06fb0253afa (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(avery): `""`
 - channels(root): `"nixos-18.09.1023.06fb0253afa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cpages** [comment]
I guess this can be closed now
