### ISSUE TITLE
Relaxng error output from xmllint is useless

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4966]
Example output:

```
$ nix-build -A manual pkgs/top-level/release.nix
these derivations will be built:
  /nix/store/4riykn8jv7mc5xwpb6rljspjax7zxl3b-nixpkgs-manual.drv
building path(s) ‘/nix/store/5fg5wy6gsz2sllkzyczzsfhbalipkr65-nixpkgs-manual’
building /nix/store/5fg5wy6gsz2sllkzyczzsfhbalipkr65-nixpkgs-manual
manual.xml:7: element para: Relax-NG validity error : Did not expect element para there
manual.xml:16: element section: Relax-NG validity error : Did not expect element section there
manual.xml:16: element section: Relax-NG validity error : Element chapter has extra content: section
manual.xml:4: element info: Relax-NG validity error : Element book has extra content: info
manual.xml fails to validate
builder for ‘/nix/store/4riykn8jv7mc5xwpb6rljspjax7zxl3b-nixpkgs-manual.drv’ failed with exit code 3
error: build of ‘/nix/store/4riykn8jv7mc5xwpb6rljspjax7zxl3b-nixpkgs-manual.drv’ failed
```

This happens when you mistype a tag name, place something in wrong part of the xml tree, etc.

cc @edolstra

**Comment by Profpatsch** [comment]
(triage) Has this improved in the meantime?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.

**Comment by domenkozar** [comment]
It hasn't improved and this needs to be fixed.

**Comment by Profpatsch** [comment]
I see I should @mention because you can disable notification for watched threads on GitHub (missed that).

**Comment by vcunat** [comment]
I scoured the internet for commands to debug invalid docbook documents. The best I've found is [MSV](https://msv.dev.java.net/), a java tool which we don't have in nixpkgs (yet). In my case it pointed me within a tag or two from the actual problem, and a reliable source [claims](http://docbook.org/tdg51/en/html/ch03.html#ch03-parseerr) that *it generally produces informative error messages*.

@thatdocslady: off the top of your head, do you know a better command/way?

A downside is that I can't see an option to process included files automatically, but one can just run it on the individual files, e.g. 
```
$ msv ${docbook5}/xml/rng/docbook/docbookxi.rng $(find -name '*.xml')
```

If we were to use it somehow in the official manual builds, we should probably separate building and MSV validation, as we shouldn't make nixos (manual) rebuilds depend on JRE.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/pull/14320
