### ISSUE TITLE
nvidiaLegacy390 Needed

### ISSUE THREAD

**Issue by sib-null** [NixOS/nixpkgs#49679]
## Issue description

Looks my graphics card (Nvidia GeForce GTX 560 Ti) has been moved to legacy status. However, the 390.xx legacy drivers are not available on NixOS yet:

![img_20181103_022008](https://user-images.githubusercontent.com/15665963/47950569-53e8bd80-df11-11e8-89f2-fa987524d461.jpg)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.03pre156996.c70ad805d21 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre156996.c70ad805d21"`
 - channels(bill): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by nek0** [comment]
I have the same Problem as described in this issue, but simply adding
```
hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable_390;
```
to my `configuration.nix ` yields following error:
```
error: The option `hardware.nvidia.package' defined in `/etc/nixos/configuration.nix' does not exist.
```
I need more Information to set this up correctly. Can anybody help me?

**Comment by eadwu** [comment]
Mind trying #51294 using `nvidiaLegacy390` in `videoDrivers` though FRidh's solution should work.

**Comment by sib-null** [comment]
I haven't done any development on nixos before, how would I test this?

**Comment by Mic92** [comment]
You can build packages from the repository by using the `-I` parameter:

```
$ cd nixpkgs
$ nix-build -I nixpkgs=$(realpath .) -A linuxPackages.nvidia_x11_legacy304
$ sudo nixos-rebuild switch -I nixpkgs=$(realpath .)
```

For more ad-hoc questions, you can also join IRC.

**Comment by Mic92** [comment]
According to the manual the following would load other nvidia packages:

```
services.xserver.videoDrivers = [ "nvidiaLegacy340" ];
services.xserver.videoDrivers = [ "nvidiaLegacy304" ];
```

https://nixos.org/nixos/manual/#sec-x11-graphics-cards-nvidia

**Comment by sib-null** [comment]
@Mic92 Thank you for your help!

I have successfully built the package, installed, and loaded `nvidiaLegacy390` via configuration.nix, and can confirm that #51294 do indeed solve my problem.
