### ISSUE TITLE
ripasso: package request

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#49681]
## Issue description
`ripasso` is a replacement for gopass that also comes with Qt5 and GTK3 UIs.

It's also written in Rust.

I'm going to try to package this in the next few days.

**Comment by colemickens** [comment]
`ripasso` hasn't had a stable release and is in fact a bit unstable. I've packaged it at https://github.com/colemickens/nixpkgs-colemickens for now. I'll send a PR here if and when it becomes appropriate to do so.

**Comment by adisbladis** [comment]
Ripasso is now in nixpkgs (and in 19.09).
