### ISSUE TITLE
alacritty: broken darwin build

### ISSUE THREAD

**Issue by periklis** [NixOS/nixpkgs#49693]
## Issue description
```
builder for '/nix/store/ajwnb79524qjli5wflfdhvxya2a9p13p-alacritty-unstable-0.2.1.drv' failed with exit code 101; last 10 log lines:
  thread 'src/meter.rs - meter (line 21)' panicked at 'couldn't compile the test', librustdoc/test.rs:332:13
  note: Run with `RUST_BACKTRACE=1` for a backtrace.


  failures:
      src/meter.rs - meter (line 21)

  test result: FAILED. 0 passed; 1 failed; 3 ignored; 0 measured; 0 filtered out

  error: test failed, to rerun pass '--doc'
[0 built (1 failed)]
error: build of '/nix/store/ajwnb79524qjli5wflfdhvxya2a9p13p-alacritty-unstable-0.2.1.drv' failed
```

### Steps to reproduce
`nix build alacritty`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.0.0, macOS 10.14`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixpkgs-18.09pre149107.3878342ef02"`
 - nixpkgs: `/Users/username/nixpkgs`
```

cc @Mic92

**Comment by Mic92** [comment]
Can you try to adapt for alacritty: https://github.com/NixOS/nixpkgs/pull/49661/files ? This might be the same regression here

**Comment by periklis** [comment]
i had hope that the regression is related to the the rust upgrade.

**Comment by Mic92** [comment]
mhm. I hope this is not due linking llvm against the system version: https://hydra.nixos.org/build/83279533/nixlog/1

**Comment by Mic92** [comment]
@jwilm Have this llvm linking been reported before? https://hydra.nixos.org/build/83279533/nixlog/1

**Comment by danieldk** [comment]
I don't think disabling tests is the solution. I get these linking problems when running tests of work-related Rust projects as well. This seems to have surfaced since the upgrade to Rust 1.30. Interestingly enough I get the same errors with Rust from Mozilla's nix overlay. But I can't find anything in the Rust bug tracker.

**Comment by danieldk** [comment]
Another interesting data point. Both in the trace above and in some work project that I tried, the linking error seems to occur in doc tests.

Maybe a temporary work around is not running doc tests for Rust derivations? (`cargo test --lib`)

**Comment by Mic92** [comment]
We could disable them globally instead of fixing each package.

**Comment by periklis** [comment]
@Mic92 can we close this since rust doctests and jemalloc fixes went in staging?
