### ISSUE TITLE
Python package set: normalize all attribute names

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#49691]
## Issue description

The convention in `python-packages.nix` is to use [normalized names](https://www.python.org/dev/peps/pep-0503/#normalized-names) although far from every attribute fulfills this requirement.

Having all packages conform will simplify things for automation.

Note that the scope is only the attribute names, and not the `pname` attributes.

cc @costrouc

**Comment by FRidh** [comment]
@costrouc in https://github.com/NixOS/nixpkgs/pull/49657#issuecomment-435589436

> I know this would require a lot of rebuilds and would possibly break people's configuration but I think that getting all the python package names in nixpkgs normalized is a first step before update automation could be considered.

Fixing the attribute names won't cause any rebuilds, but indeed, it will break people's configuration. 

> I think that a generated.nix is very doable and a great idea! With correct normalized package naming the only thing this tool this tool misses is extra packages and checkInputs. default.nix would get a lot shorter and simpler to write.
>
> I would be willing to work on normalizing package names.

We should look at adding a test to Nixpkgs so we can enforce this.

**Comment by costrouc** [comment]
Since I am quite new I am not aware of how to add a test to Nixpkgs would be done. Are you suggesting a `GrahamcOfBorg` check?

**Comment by costrouc** [comment]
After the 19.03 release I would like to work on this in an automated fashion to see how far it goes. Having normalized names would allow tools such as https://github.com/t184256/nixpkgs-python-importer and https://github.com/nix-community/nixpkgs-pytools to get the package name correct and in general not force users to guess on the name of a python package. @FRidh do you have suggestions on how this should be approached? Right now I am considering an adhoc approach manual/https://github.com/Mic92/pythonix to read the derivation names.

**Comment by FRidh** [comment]
Yes, use `pytho(nix)` to generate a list of attribute names, and check with the PyPI index whether a package exists with that name. If so, good. If not, then likely it needs to be fixed.

Furthermore, when checking this, it's possible to check whether the attribute name is normalized.

**Comment by costrouc** [comment]
How would we handle renaming? Obviously this would break a lot of packages if the transition was done immediately. Would there be a way to depreciate the attribute names?

**Comment by FRidh** [comment]
Deprecation is in my opinion just generating work. If we feel this is worth it we should do it and then I think it's best to just get it over with.

**Comment by costrouc** [comment]
Okay I will work on this in the coming weeks. With a goal of making it as automated as possible.

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/pull/96586
