### ISSUE TITLE
Fix services that have TimeoutStartSec=0

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#49700]
## Issue description

`TimeoutStartSec = 0` is likely wrong, it doesn't make much sense to expect that the service starts in 0 time. Perhaps `infinite` was meant?

Units we know we should investigate and fix:

* [`osquery`](https://github.com/NixOS/nixpkgs/commit/53426f6cb93f3fbaa2ad974659da271d08ea0594#diff-3da89d7acc8c0d15f621020b373fc492R81)
* [`consul`](https://github.com/NixOS/nixpkgs/commit/9ce0c1cb71138d0bb9f8ea314e65f084bb5095a1#r23138805)

**Comment by cyounkins** [comment]
Previous versions of systemd used `0` to disable the timeout logic.

Ref: https://github.com/systemd/systemd/blob/4f7dc24f8bbb3c312a46dc8d8f25658d02d47bfe/NEWS#L2798

The correct new value is `infinity`
