### ISSUE TITLE
nix-delegate: need fix for darwin build

### ISSUE THREAD

**Issue by periklis** [NixOS/nixpkgs#49709]
## Issue description
Missing dependencies for nix-delegate on darwin:
```
builder for '/nix/store/h9v3b1ksbmq7cyik3p9hlqr2240rv5zz-nix-delegate-1.0.0.drv' failed with exit code 1; last 10 log lines:
    die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
    configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
    configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple
    confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
    configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple
    defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple
    defaultMain, called at Setup.hs:2:8 in main:Main
  Setup: Encountered missing dependencies:
  foldl <1.4, turtle >=1.3.0 && <1.5
```

### Steps to reproduce
`nix build nix-delegate`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
- system: `"x86_64-darwin"`
 - host os: `Darwin 18.0.0, macOS 10.14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixpkgs-18.09pre149107.3878342ef02"`
 - nixpkgs: `/Users/username/path/to/nixpkgs`
```

**Comment by periklis** [comment]
cc @Gabriel439 according to `hackage-packages.nix` turtle is just too new for nix-delegate.

**Comment by Gabriel439** [comment]
@periklis: This should be fixed by `nix-delegate-1.0.1`, which I just uploaded

**Comment by Gabriel439** [comment]
@periklis: There is some process that updates [`hackage-packages.nix`](https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix).  See the commit history for that file:

https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/haskell-modules/hackage-packages.nix

I don't know what exactly triggers the update but I do know that the commits are generated by @peti so you can ask him.  Once it is updated, though, it should pick up the latest `nix-delegate`

**Comment by peti** [comment]
Updates take place by running https://github.com/NixOS/cabal2nix/blob/master/update-nixpkgs.sh once per day. The new versions go to the `haskell-updates` branch and are merged from there to `master` manually, whenever someone thinks of doing it.
