### ISSUE TITLE
ati_unfree + linux 4.9.x + GNOME3 = Unable to run X server

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#49726]
## Issue description

My iMac has a AMD Mobility Radeon HD 5850 GPU, so i want to benchmark if the proprietary driver has better performance for gaming.

It don't build with current kernel https://github.com/NixOS/nixpkgs/issues/36802
but also don't work anymore with 4.9 kernel.
Everything builds, but X can't start a GNOME3 session (other desktops might work?)

After the boot i see just a blinking cursor, but can't type anything.

journalctl -b > https://gist.github.com/davidak/cc3f9caabc53d55f0fc804ec1796a88c

### Steps to reproduce

```
  boot.kernelPackages = pkgs.linuxPackages_4_9;
  hardware.cpu.intel.updateMicrocode = true;
  services.xserver.videoDrivers = [ "ati_unfree" ];
  hardware.opengl.driSupport32Bit = true;
  nixpkgs.config.allowUnfree = true;
```

See complete config here: https://github.com/davidak/nixos-config/blob/69a516af83ec1093575a08ed363a7af13d79aee0/machines/imac/configuration.nix

## Technical details

My nixpkgs is on 18.09 channel with https://github.com/NixOS/nixpkgs/pull/49722 applied.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.135, NixOS, 18.09.git.06fb025 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.1023.06fb0253afa, nixos-hardware, nixos-unstable-19.03pre156996.c70ad805d21"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
Same problem with kernel 4.4.x

**Comment by rmorey** [comment]
I'm also experiencing this issue. Any known workaround?

**Comment by davidak** [comment]
On NixOS 19.03.172311.454eea84a75 with Linux 4.9.170, it builds.

I have lightdm and pantheon desktop configured.

I actually get the login screen, but then a black screen with a mouse cursor i can move.

There are some heavy errors in the syslog: [syslog.txt](https://github.com/NixOS/nixpkgs/files/3101827/syslog.txt)

**Comment by davidak** [comment]
It works with Linux 4.9, LightDM and **Xfce**!

But the benchmark was extremely bad!

With pantheon desktop and linux 4.14, the glmark2 Score is 3473.
With Xfce, linux 4.9 and ati_unfree, the glmark2 Score is 1043.

So with this setup, the open source driver has way better performance. Might be different with another GPU.

**Comment by vcunat** [comment]
Yes, I _expect_ the optimal choice depends on GPU generation, with newer ones shifting towards amdgpu(-pro), but I haven't investigated really.  I have a recent AMD GPU, and "amdgpu" seems quite fast there and without problems (but even general "modesetting" seemed the same, though I only used it shortly).

**Comment by Artturin** [comment]
ati_unfree removed https://github.com/NixOS/nixpkgs/commit/7117588d2666f975e8239d0aebd8a9dc7d73a7cf
