### ISSUE TITLE
Allow booting nixos from a subdirectory of the root device

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#4972]
This is a move of a pull request #3143 that stopped being a pull request and became a feature request. Implementation will probably use systemd in initrd.

Original attempt to implement was by @lethalman 

> Assuming we are installing nixos under /nixos, we mount --rbind /nixos /mnt and do the usual installation.
> Then in the configuration.nix:
> 
```
   boot.loader.grub.doInstall = false;
 ```
```
   fileSystems."/mnt/root" =
     { device = "/dev/foo";
       fsType = "bar";
       neededForBoot = true;
     };
```
 ```
   fileSystems."/" =
     { device = "/mnt/root/nixos";
       fsType = "none";
       options = "bind";
     };
```
> 
> Finally add a menu entry to the existing grub loader of your device with something like: configfile (hd0,...)/nixos/boot/grub/grub.cfg.

**Comment by Profpatsch** [comment]
(triage) Has this been fixed?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.
