### ISSUE TITLE
syncthing: hardcoded gui settings in unit file

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#49805]
## Issue description

I'm trying to set access to syncthing wui to listen to all ips and not just localhost. So I edite the syncthing config.xml. However, no matter what I do, nothing worked. It would always use 127.0.0.1:8384.

The problem is that this seems hardcoded in the provided systemd unit file.

```
ExecStart=/nix/store/zyz36q4vv9jhdm2l3qxcg9q3c9rz4srr-syncthing-0.14.51/bin/syncthing \
  -no-browser \
  -gui-address=127.0.0.1:8384 \
  -home=/home/hyper/Syncthing/.config/syncthing
```
So this is new, because before I upgraded my system it used to work just fine.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 19.03pre157893.1fe3328593e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(hyper): `""`
 - channels(root): `"nixos-19.03pre157893.1fe3328593e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by colemickens** [comment]
It's not hardcoded though, that's just how systemd units work in NixOS.

You shouldn't be editing the XML. You need to be setting the module's `guiAddress`: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/syncthing.nix#L158

**Comment by sjau** [comment]
Well, it breaks how it worked so far. Also wtf is this with the change of config file? And each syncthing has an xml file and that should be respected.

**Comment by colemickens** [comment]
If I were to guess, I guess that the command line flags take precedence over the config file, as is common for CLI tools.

It looks like this was a recent change, as part of https://github.com/NixOS/nixpkgs/pull/48119.

**Comment by mrVanDalo** [comment]
It is set to the default syncthing uses anyway : https://www.mankier.com/1/syncthing#-home

**Comment by mrVanDalo** [comment]
https://docs.syncthing.net/intro/getting-started.html#configuring the gui-address is set to the default syncthing.

**Comment by peti** [comment]
One problem that remains is the configuration for the listen address for data transfers. The choice of the port there is rather important (because it needs to interact with the firewall) yet this setting cannot be changed through the command line.

As far as I can tell, the only viable solution to make this stuff configurable via Nix is to manipulate the appropriate settings into the config file every time syncthing starts, which is easy enough considering it's a simple XML file.
