### ISSUE TITLE
new version of base-compat breaks cryptol build

### ISSUE THREAD

**Issue by GallagherCommaJack** [NixOS/nixpkgs#49804]
## Issue description

Cryptol 2.6.0 from Hackage requires base-compat < 0.10, but the latest version of base-compat is 0.10.
Note this isn't required for the latest version of Cryptol on github, which has updated the requirement to base-compat < 0.11.

I've tried building on both 18.09 and unstable, both have the same issue since they include base-compat 0.10 but build Cryptol from Hackage.

### Steps to reproduce

`nix-env -i cryptol`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(jack): `"nixpkgs-19.03pre157897.c9e13806267"`
 - channels(root): `"nixos-18.09.1195.bf7930d582b"`
 - nixpkgs: `/home/jack/.nix-defexpr/channels/nixpkgs`

**Comment by GallagherCommaJack** [comment]
Possible solutions:
1) add alternate base-compat package to nixpkgs, make cryptol package override with alternate version
2) make cryptol package use github instead of hackage
3) wait for cryptol 2.7 to hit hackage (by which point a different dependency might be too new)

**Comment by matthewbauer** [comment]
I would ask for a new release at https://github.com/GaloisInc/cryptol.

**Comment by langston-barrett** [comment]
Cryptol 2.7.0 is on [Hackage](https://hackage.haskell.org/package/cryptol) and [Github](https://github.com/GaloisInc/cryptol/releases/tag/2.7.0)

**Comment by Artturin** [comment]
cryptol was removed in 2020
