### ISSUE TITLE
dwarf-fortress: tileset regression

### ISSUE THREAD

**Issue by patrl** [NixOS/nixpkgs#49819]
## Issue description

Since commit 290dd06d1422fbac5c1439af6f55ddea3cb5f044 (fixing dfhack) setting a custom tilset via the documented method has no effect.

### Steps to reproduce

Add the following to your `environment.systemPackages`. `"gemset"` can be substituted for any custom tileset.

```
(pkgs.dwarf-fortress-packages.dwarf-fortress-full.override {
      theme = "gemset";
    })
```

run `dfhack`. The vanilla tileset is used, whereas gemset should be used.

ping @bendlas @Lassulus again (sorry guys).

**Comment by Lassulus** [comment]
I'm currently looking into it, but I don't have a good test to see if it's the default font?

**Comment by Lassulus** [comment]
Alright, I understand it know, but I'm not sure how this ever worked:
if theme is a attribute it's content is added to ~/.local/share/df_linux if it's a string is gets the attribute with it's name from themes and adds those contents to ~.local/... 
But it never actually copies the data/art directory where the fonts reside.
And it never changes the FONT value in data/init/init.txt.

**Comment by patrl** [comment]
Hmm weird. I'd like to dig into how the derivation works, but I'm not familiar with it, so it's going to take some time. Ideally, all of the files from the tileset dir should override those in ~/.local/share/df_linux. I was definitely working before the commit that broke dfhack, so I suspect it's something to do with 0d57159eca8f3bfc2d009da57a253298d127d0e4 -- probably the fixup step.

**Comment by Lassulus** [comment]
I will bisect it in a couple of hours and try to find out whats going on :)

**Comment by Lassulus** [comment]
yip yip yip, figured it out. The theme packages have their own init.txt.
Please test :)

**Comment by bendlas** [comment]
fixes the theme for me, thanks!

@patrl thanks again for the report and for your patience. Could you verify the fix and close the issue again?

**Comment by patrl** [comment]
@Lassulus @bendlas yep, themes are working now! Thanks for the quick support, I really appreciate it!
