### ISSUE TITLE
nixos-generate-config fails without swap

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#49826]
## Issue description

I'm reporting this for a friend of mine who wanted to install NixOS and ran into this issue. I hope that's okay.

The problem is: `nixos-generate-config` fails if you have `CONFIG_SWAP=n` in your host's kernel config (which, I think, is reasonable if you're compiling it yourself and don't need swap). I took a cursory look into `nixos-generate-config.pl` and saw that it reads from `/proc/swaps`. This fails, apparently, because the file doesn't exist on systems without swap support.

Can this be easily fixed by assuming there are no swap devices if the file cannot be found?

**Comment by Synthetica9** [comment]
> Can this be easily fixed by assuming there are no swap devices if the file cannot be found?

I'd say already assume this, but don't handle it gracefully.
