### ISSUE TITLE
qtbase: qmake binary is not linked to ~/.nix-profile/bin/

### ISSUE THREAD

**Issue by ilius** [NixOS/nixpkgs#49847]
## Issue description
I was trying to find a way to *install qmake*, until I found these files are already on my /nix

    /nix/store/860cxjhccavbcj64xxyaiansmqh8d3fq-qtbase-5.11.1-dev/bin/qmake
    /nix/store/91zq4cljlm8nbmrlryhxxccbbzj2a525-qtbase-5.11.1-dev/bin/qmake

But none of them is linked to ~/.nix-profile/bin/

    $ ls ~/.nix-profile/bin/qmake*
    ls: cannot access '/home/s/.nix-profile/bin/qmake*': No such file or directory

### Steps to reproduce

Run `nix-shell -p qt5.qtbase` or `nix-env -i qtbase`. Then try to run `qmake` or `type qmake`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-20-generic, Linux Mint, 19 (Tara)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(s): `"nixos-18.09.821.4dd9cd3f69e, nixpkgs-19.03pre155263.20c4986c4dd"`
 - nixpkgs: `/home/USER/.nix-defexpr/channels/nixpkgs`

**Comment by peterhoeg** [comment]
Try ```nix-shell -p qt5.qmake```

**Comment by ilius** [comment]
@peterhoeg No success, i get command not found.
My $PATH is not changed, and no sym link like ~/.nix-profile/bin/qmake is created with nix-shell

**Comment by ilius** [comment]
I guess build tools like qmake, make, gcc and g++ are not meant to be run outside nix packages in Nix world (like we compile programs in typical Linux distros)
I that correct?

**Comment by lheckemann** [comment]
Libraries and development tools should be used via nix-shell: https://nixos.wiki/wiki/FAQ/Libraries
