### ISSUE TITLE
QGroundControl .desktop does not work

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#49870]
## Issue description
In the file `/nix/store/**qgroundcontrol**/share/applications/qgroundcontrol.desktop` a non existing shell script is referenced as executable:
```
[Desktop Entry]
Type=Application
Name=QGroundControl
GenericName=Ground Control Station
Comment=UAS ground control station
Icon=qgroundcontrol
Exec=qgroundcontrol-start.sh
Terminal=false
Categories=Utility;
````
The binary in `bin` is called `QGroundControl`. Please change the `Exec=` line in the `.desktop` file accordingly.

### Steps to reproduce
+ install software
+ try to run it through a launcher

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0, NixOS, 18.09.1206.6d6e4e6b558 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.1206.6d6e4e6b558"`
 - channels(wucke13): `"nixos-unstable-small-19.03pre158251.50602de85e3, nixpkgs-unstable-19.03pre157897.c9e13806267"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
Do you feel like trying to fix this in the [installPhase](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/robotics/qgroundcontrol/default.nix#L36)?

**Comment by wucke13** [comment]
Sure
