### ISSUE TITLE
movit build fails

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#49883]
## Issue description

```
$ nix build -I nixpkgs=/home/davidak/nixpkgs nixpkgs.movit
builder for '/nix/store/33x5107hyrxrli244s0slnfjla9lzwgq-movit-1.5.1.drv' failed with exit code 2; last 10 log lines:
  /nix/store/hqxgpw62iyqylyxaq0h7ypsvyv215jjv-eigen-3.2.10/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:948:19: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
                     traits.acc(C0, alphav, R0);
                     ^~~~~~
  /nix/store/hqxgpw62iyqylyxaq0h7ypsvyv215jjv-eigen-3.2.10/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:951:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
           if(nr==4) traits.acc(C3, alphav, R3);
           ^~
  /nix/store/hqxgpw62iyqylyxaq0h7ypsvyv215jjv-eigen-3.2.10/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:953:19: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
                     pstoreu(r0, R0);
                     ^~~~~~~
  make: *** No rule to make target '/nix/store/q2q3kq71ggd8w10rhca1qhab08gjj7m5-gtest-1.8.1/src/gtest-all.cc', needed by 'gtest-all.o'.  Stop.
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/33x5107hyrxrli244s0slnfjla9lzwgq-movit-1.5.1.drv' failed
```

cc @cillianderoiste 

Also, new release is available. Maybe it already fixes this problem. But please check compatibility with Kdenlive and MLT where it is used.

### Steps to reproduce

`nix build -I nixpkgs=/home/davidak/nixpkgs nixpkgs.movit`

## Technical details

nixpkgs = master

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 19.03.git.b562dbc (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1023.06fb0253afa, nixos-hardware, nixos-unstable-19.03pre156996.c70ad805d21"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by coreyoconnor** [comment]
For reference: Here is an overlay that builds updated kdenlive, movit and mlt 

* https://github.com/coreyoconnor/nix_configs/blob/master/overlays/standard.nix#L56

Ignore the kdenlive version. The only odd part is `GTEST_DIR = "${self.gtest.src}/googletest";` in movit.
