### ISSUE TITLE
Our current (after-staging-merge) lacks CC environment  variable for the gcc variety

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#4997]
tex4ht used ```$CC -o …``` commands; now these work on clangStdenv, but not on gcc stdenv.

I fixed it to use ```${CC:-gcc}```. Is the ```CC``` environment variable situation intentional?

**Comment by vcunat** [comment]
`$CC` seems defined on master. I tested x86_64-linux:
```
$ nix-shell -p stdenv --pure
$ echo $CC
gcc
```

**Comment by ledettwy** [comment]
This doesn't appear to work anymore?

**Comment by vcunat** [comment]
@ledettwy: it still does work for me.  Can you provide more details?

**Comment by ledettwy** [comment]
Sure:
<pre>
[~]$ nix-shell -p stdenv --pure --run "echo \$SHELL"
/nix/store/hqi64wjn83nw4mnf9a5z9r4vmpl72j3r-bash-4.4-p12/bin/bash
[~]$ nix-shell -p stdenv --pure --run "echo \$CC"

[~]$ nix-shell -p gccStdenv --pure --run "echo \$CC"

[~]$ nix-shell -p clangStdenv --pure --run "echo \$CC"

[~]$ nix-shell -p nix-info --run nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.11.15, channels(root): "nixpkgs-17.09.2253.559ebb7ed02, nixos-17.09.2253.559ebb7ed02, unstable-18.03pre121843.4e7deb7100b", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
[~]$
</pre>

**Comment by globin** [comment]
@ledettwy this is only during nix builds not in your normal shell:
```
$ nix-shell -A hello '<nixpkgs>'    

[nix-shell:~]$ echo $CC
gcc
```

**Comment by vcunat** [comment]
Globin confuses me a bit.  I get this as it should be, I believe:
```
$ nix-shell -p --pure --run "echo \$CC"
gcc
```

I had tried it on the nixpkgs commits printed by nix-info above, too.
