### ISSUE TITLE
zathura-with-plugins fails: mupdfthird not found

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#50001]
## Issue description

With the latest `nixos-unstable`, I get the following error:

```
The Meson build system
Version: 0.46.1
Source dir: /build/zathura-pdf-mupdf-0.3.3
Build dir: /build/zathura-pdf-mupdf-0.3.3/build
Build type: native build
Project name: zathura-pdf-mupdf
Native C compiler: /nix/store/10yq7kwlvbc6h658izmrlsspry1g9f3c-gcc-wrapper-7.3.0/bin/cc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /nix/store/sbg7j9ghnhl3kiw5gck9khhr2wwd5y8f-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Native dependency zathura found: YES 0.4.1
Native dependency girara-gtk3 found: YES 0.3.1
Native dependency glib-2.0 found: YES 2.56.0
Native dependency cairo found: YES 1.15.14
Library mupdf found: YES

meson.build:23:0: ERROR:  C library 'mupdfthird' not found
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.03pre156996.c70ad805d21 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(philipp): `""`
 - channels(root): `"nixos-19.03pre156996.c70ad805d21"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by 7c6f434c** [comment]
Known problem, fix present in `master`.

Seems to have landed on Wednesday, while the channel has last upsdated on Thursday to a Tuesday's revision. nixos-unstable-small is fresh enough, though (but some large GUI things might still be in process of building on Hydra).

**Comment by pmiddend** [comment]
Alright then, thanks for the info!
