### ISSUE TITLE
ddclient wont start with DynamicUser

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#50011]
## Issue description

When ddclient is configured normally it refuses to start due to permission issues. I've traced this back to the use of DynamicUser in the systemd config.

### Steps to reproduce

1.) Setup ddclient with some sane settings
2.) `nixos-rebuild upgrade`
3.) You will see: `WARNING:  file /run/ddclient/ddclient.conf: Cannot open file '/run/ddclient/ddclient.conf'. (Permission denied)`

The workaround I've found is to use: `systemd.services.ddclient.serviceConfig.DynamicUser = lib.mkForce false;`

## Technical details

```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/1hmvnxp69a6x27cw0c9c8jnhjfcssbxh-bash-interactive-4.4-p23-dev
copying path '/nix/store/1hmvnxp69a6x27cw0c9c8jnhjfcssbxh-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.17, NixOS, 19.03pre158246.6141939d6e0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre158246.6141939d6e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by aanderse** [comment]
@arianvp is this fixed for 19.03?

**Comment by arianvp** [comment]
It should be! @cawilliamson  could you confirm?

**Comment by bjornfor** [comment]
It works now, so closing.

It outputs this though:

```
WARNING:  file /run/ddclient/ddclient.conf: file /run/ddclient/ddclient.conf must be accessible only by its owner.
```
