### ISSUE TITLE
Packaging request for Zoneminder 

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#5005]
@bjornfor  has already did some work on it last year, but it seems that it has never got merged: https://github.com/bjornfor/nixpkgs/tree/zoneminder 

I would really like to see Zoneminder become available.

**Comment by bjornfor** [comment]
@wwat wrote (pasted from obsolete issue #5575):
> @bjornfor 1.28.0 and I already fixed that polkit store path issue on one of my systems.

Ok. Me too. Here is my ugly WIP branch (may be rebased at any time): https://github.com/bjornfor/nixpkgs/commits/zoneminder3

> My latest
> issue is that zoneminder returns for zmc -m 1 the exit status 11 (and I haven't looked at what it
> means yet). I do think it's rather bad for an application to exit without a good reason (and listing
> that reason).

I agree.

**Comment by wwat** [comment]
@bjornfor Where are you going to store anything? The homedirectory of wwwrun is empty and you configured nobody as the ZM_WEB_USER. When it is running as a subservice, does that mean that the wwwrun user is finally still running everything (assuming httpd runs as wwwrun)? Is it possible to change that somehow? That is, run each subservice under a different user? 

I think it would be nice if /var/log/zm would hold log files, /var/zm would store images, and most code would run under the zoneminder user.

**Comment by bjornfor** [comment]
The plan is to eventually provide a NixOS service for zoneminder, which writes a new config file with ZM_WEB_USER etc. settings that come from the system configuration (e.g. configuration.nix). All paths (log, images etc) will be configured by NixOS, not at zoneminder package build time. The nobody/nogroup thing is just a dummy default value.

**Comment by bjornfor** [comment]
Persistent service state is typically stored in /var/lib/SERVICE/.

**Comment by bjornfor** [comment]
@wwat: Can you post a link to your tree?

**Comment by bjornfor** [comment]
Gaaah! zoneminder is really fighting back on the idea of having separate (read-only) package data and mutable service state.

It is really tempting to just rebuild the whole thing with ```--prefix=/usr```...

**Comment by wwat** [comment]
@bjornfor With your latest patch, what is the current status and can you also share your configuration.nix, if it works?

**Comment by bjornfor** [comment]
Here is my tree:

https://github.com/bjornfor/nixpkgs/commits/zoneminder3

Status is that it's still not working properly. There is a webui that talks to the backend, and my web camera seems active (LED is on), but I cannot get live preview in the webui. (And probably other issues I haven't gotten to yet.)

From one of my commit messages (regarding missing live preview in the webui):

```
I get this in the log:

  lighttpd[21443]: (mod_fastcgi.c.2695) FastCGI-stderr: PHP message: ERR [socket_sendto( /tmp/zm/zms-500183s.sock ) failed: No such file or directory]

And according to this[1], it's because zms (CGI script) isn't running.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741738
```

At that point I thought to contact upstream for help, but I haven't gotten to it yet.

The tree I linked to above currently adds zoneminder as a lighttpd sub-service. To test it you must add ```services.lighttpd = { enable = true; zoneminder.enable = true; }``` to configuration.nix.

**Comment by wwat** [comment]
For live video, you need to have the following (I haven't really setup github nicely to push this stuff to your repo, so you would just have to copy it). I have tested it, and it works (on my x86-64 hardware). To make it work on more hardware, read the live555 documentation (but I doubt any other hardware is currently useful). 

I hope this helps to complete your task (and then when it is done, also my task).  

default.nix for live555
```
{stdenv, coreutils, fetchurl}:
 stdenv.mkDerivation {
  name = "live555-2014-12-17";
  buildInputs = [ coreutils ];
  CFLAGS = "-fPIC";
  builder = ./build.sh;
  enableParallelBuilding = true;
  src = fetchurl { 
  url = http://www.live555.com/liveMedia/public/live.2014.12.17.tar.gz;
  sha256 = "33892797fb3a01d453f09c25be4408435211c6996e84c69e7d5b82031e1955af";
  };
}    
```

build.sh for live555
```
source $stdenv/setup

configurePhase(){
    env
    ls -lah
    rm configure
    sed -r -i 's|/bin/rm|rm|g' ./genMakefiles &&
    ./genMakefiles linux-64bit

    printf '$out directory: %s\n' "$out"
    
    for wrong_usr_local_file in $(grep -rl  /usr/local .); do
        printf 'Found wrong file: %s\n' "$wrong_usr_local_file"
        substituteInPlace "$wrong_usr_local_file" --replace /usr/local "$out"
    done
}

genericBuild

```

default.nix for vlc with live555
```
{ stdenv, fetchurl, xz, bzip2, perl, xlibs, libdvdnav, libbluray
, zlib, a52dec, libmad, faad2, ffmpeg, alsaLib
, pkgconfig, git, dbus, fribidi, qt4, freefont_ttf, libebml, libmatroska
, libvorbis, libtheora, speex, lua5, libnotify, libgcrypt, libupnp
, libcaca, pulseaudio, flac, live555, schroedinger, libxml2, librsvg
, mpeg2dec, udev, gnutls, avahi, libcddb, jack2, SDL, SDL_image
, libmtp, unzip, taglib, libkate, libtiger, libv4l, samba, liboggz
, libass, libva, libdvbpsi, libdc1394, libraw1394, libopus
, libvdpau
}:

stdenv.mkDerivation rec {
  name = "vlc-${version}";
  version = "2.1.5";

  src = fetchurl {
    url = "http://download.videolan.org/pub/videolan/vlc/${version}/${name}.tar.xz";
    sha256 = "0whzbn7ahn5maarcwl1yhk9lq10b0q0y9w5pjl9kh3frdjmncrbg";
  };

  buildInputs =
    [ xz bzip2 perl git zlib a52dec libmad faad2 ffmpeg alsaLib libdvdnav libdvdnav.libdvdread
      libbluray dbus fribidi live555 qt4 libvorbis libtheora speex lua5 libgcrypt
      libupnp libcaca pulseaudio flac schroedinger libnotify libxml2 librsvg mpeg2dec
      udev gnutls avahi libcddb jack2 SDL SDL_image libmtp unzip taglib
      libkate libtiger libv4l samba liboggz libass libdvbpsi libva
      xlibs.xlibs xlibs.libXv xlibs.libXvMC xlibs.libXpm xlibs.xcbutilkeysyms
      libdc1394 libraw1394 libopus libebml libmatroska libvdpau
    ];

  nativeBuildInputs = [ pkgconfig ];

  configureFlags =
    [ "--enable-alsa"
      "--with-kde-solid=$out/share/apps/solid/actions"
      "--enable-dc1394"
      "--enable-ncurses"
      "--enable-vdpau"
      "--enable-live555"

      
      
    ];

  preConfigure = ''
     sed -e "s@/bin/echo@echo@g" -i configure
     export LIVE555_PREFIX=${live555}
     echo 'Checking for right prefix...'
     env | grep LIVE555_PREFIX 
   '';

  enableParallelBuilding = true;

  preBuild = ''
    substituteInPlace modules/text_renderer/freetype.c --replace \
      /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf \
      ${freefont_ttf}/share/fonts/truetype/FreeSerifBold.ttf
  '';

  meta = with stdenv.lib; {
    description = "Cross-platform media player and streaming server";
    homepage = http://www.videolan.org/vlc/;
    platforms = platforms.linux;
    license = licenses.lgpl21Plus;
  };
}


```

**Comment by bjornfor** [comment]
@wwat: Well, I hope you will not be able to push to _my private nixpkgs fork_ just by configuring something at _your end_ :-) (That would scare me...)

Are you saying VLC without live555 is the (indirect) reason for ```lighttpd[21443]: (mod_fastcgi.c.2695) FastCGI-stderr: PHP message: ERR [socket_sendto( /tmp/zm/zms-500183s.sock ) failed: No such file or directory]```? Interesting.

Btw, I don't think you need that build.sh file; just put configurePhase = '' shell code here '' in the nix expression.

**Comment by wwat** [comment]
`libvlc` without that `live555` cannot display video using plain `vlc` from my camera. If at some point ZM wants to get those images, it also needs to use that library (libvlc and in turn live555) and otherwise it will fail certainly at some point. So, while it might not be a sufficient condition it is something which also needs to be fixed.

**Comment by joachifm** [comment]
Looks like this has been abandoned, I see no benefit to keeping this open.

**Comment by tibrown** [comment]
Noo, we all want zoneminder

**Comment by bjornfor** [comment]
I'll probably re-visit this eventually, but there are many issues I prioritize higher than this one.

@tibrown: You're welcome to pick up the pieces and try to make it work. ZoneMinder has probably made some new releases, hopefully cleaning up some stuff.

**Comment by tibrown** [comment]
I am working with @cleverca22  on it.  I have checked out your branch.

**Comment by bjornfor** [comment]
@tibrown, @cleverca22: Did you make any progress?
