### ISSUE TITLE
gitlab startup errors since eadb998

### ISSUE THREAD

**Issue by kyren** [NixOS/nixpkgs#50163]
## Issue description

I believe commit eadb9985819327f6bce7da87730d32e5018ee848 broke gitlab startup.

On [this line](https://github.com/NixOS/nixpkgs/commit/eadb9985819327f6bce7da87730d32e5018ee848#diff-a8187202c46aeec728e5b8818fdce3c8L569), the pre-start script attempts to link an smtp settings file into the 'initializers' subdirectory of '/var/gitlab/state/config/', but at the time the target directory doesn't exist so this errors.

Before eadb9985819327f6bce7da87730d32e5018ee848, [this line](https://github.com/NixOS/nixpkgs/commit/eadb9985819327f6bce7da87730d32e5018ee848#diff-a8187202c46aeec728e5b8818fdce3c8R571) would have created the 'initializers' directory, but it now happens too late.

I can make a PR that simply adds a 'mkdir' to make it work, if that's the right solution.

### Steps to reproduce

Enable the gitlab service in nixos, set `services.gitlab.smtp.enable` to `true`, and try to start gitlab.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(catherine): `"nixpkgs-18.09.810.59fe4c7f17a"`
 - channels(root): `""`
 - nixpkgs: `/home/catherine/.nix-defexpr/channels/nixpkgs`

**Comment by dywedir** [comment]
cc @globin
