### ISSUE TITLE
Harmonize nix and nixos "binaryCache" / "substituter" options

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#50165]
As far as I understand, nix configuration has deprecated usage of `binaryCaches` and `trustedBinaryCaches` in favor of `substituters` and `trustedSubstituters`.

Is there a reason this hasn't been reflected in the congruent NixOS `nix.*` options? Someone mentioned "not yet" in IRC some weeks ago, but I don't know if it's planned/blocked/etc.

Thanks.

**Comment by FintanH** [comment]
This change bit me since I'm not a regular user of nix so I wasn't aware of it. It would be super helpful to have some kind of warning/error if `binary-caches` is used and you're running with 2.0! It was very painful :sweat: :sweat_smile:

**Comment by Artturin** [comment]
fixed in 4a9d9928dc01421b878cfe4a16961c1e4862d846
