### ISSUE TITLE
Scripted network doesn't bring bridges up 

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#50208]
## Issue description

```
networking.bridges.arian.interfaces = {};
```

```
nixos-rebuild switch
```

Expected behaviour:  the bridge named `arian` appears in `ip link`

Actual behaviour:  The bridge doesn't appear

Manually restarting `network-setup.service` or _rebooting_ does cause the bridge to come up!

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by arianvp** [comment]
Changing the config to:

```
networking.interfaces.arian = {};
networking.bridges.arian.interfaces = {};
```

Fixes this issue.

Which I discovered by reading:
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/containers-bridge.nix


However, I don't understand why this is true. it seems a bit odd / a bug

**Comment by arianvp** [comment]
This pull request seems to be relevant: https://github.com/NixOS/nixpkgs/pull/47252

**Comment by volth** [comment]
> ```networking.bridges.arian.interfaces = {};```

Shouldn't there be a list ?
```networking.bridges.arian.interfaces = [];```

**Comment by arianvp** [comment]
It is a list. I typoed.

**Comment by volth** [comment]
As far as I understand it, ```networking.interfaces.arian``` is obligatory, it has settings like IP addresses, while ```networking.bridges.arian.interfaces``` is a list of enslaved interfaces. So the latter alone should not create a bridge.

**Comment by arianvp** [comment]
But it actually does on reboot. So I guess that is a bug then right?

**Comment by arianvp** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/42828
