### ISSUE TITLE
use of meta.tests causes evaluation errors

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#50230]
https://github.com/NixOS/nixpkgs/pull/44439 adds `meta.tests` to `dovecot`, but that attribute is not supported by Nix and causes evaluation errors, i.e.:

~~~
$ nix-env -qaP --meta --json  >/dev/null
derivation 'dovecot-2.3.3' has invalid meta attribute 'tests'
derivation 'opensmtpd-6.4.0p1' has invalid meta attribute 'tests'
~~~

This output breaks several scripts of mine (for updating the Haskell package set) and I would kindly request to make those warnings disappear one way or another.

Ping: @Ekleog, @timokau

**Comment by timokau** [comment]
This is weird since @Ekleog did add the `tests` attribute to `metaTypes` in `pkgs/stdenv/generic/check-meta.nix`.

**Comment by grahamc** [comment]
My guess is a derivations' meta can't contain derivations, but I'm not sure. I think this may be true because it raises this question: when evaluating and querying meta fields about a package (which is possible,) should the derivations be built or not? Yes, for consistency it should, but running a bunch of tests when querying packages doesn't make sense.

**Comment by Ekleog** [comment]
@timokau It appears to be also checked a second time in `nix` itself for *some* (but not all) operations: https://github.com/NixOS/nix/blob/f6a3dfe4e06980b2d060fd1a646cb5ca20f29779/src/nix-env/nix-env.cc#L872

This means either we need to change `nix`, or we need to use `passthru`. I'm opening an issue on `nix` for more thought on this.

**Comment by grahamc** [comment]
Probably should just use passthru.

**Comment by Ekleog** [comment]
This should be fixed in https://github.com/NixOS/nixpkgs/pull/50233

**Comment by Ekleog** [comment]
Feel free to react to https://github.com/NixOS/nix/issues/2532, which I opened as the issue seen from the nix point of view :)
