### ISSUE TITLE
unison should be upgraded to 2.51.2

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#50255]
## Issue description

The `unison` package is currently vending version 2.48.4 but the current version is 2.51.2.

This upgrade is critical for the functionality of Unison on APFS filesystems.

CC package maintainer @viric

**Comment by cyounkins** [comment]
Started working on this but the build for 2.51.2 is broken from https://github.com/bcpierce00/unison/issues/153 A fix was merged but a release hasn't happened yet.

My diff: https://github.com/cyounkins/nixpkgs/commit/8dd5eafe0bada3ede6c90bd135dad5c052c846cc

**Comment by lilyball** [comment]
This was done in #55697.

**Comment by lilyball** [comment]
To be clear, `nixpkgs.unison` is still tied to OCaml 4.05, because that apparently works. It won't compile (with `enableX11`) with OCaml 4.06. I'll file a separate issue to track that.

**Comment by lilyball** [comment]
I filed it as https://github.com/NixOS/nixpkgs/issues/61505.
