### ISSUE TITLE
GCE images for 18.09 missing

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#50259]
The latest image version is still 18.03:

https://github.com/NixOS/nixpkgs/blob/49df3150c71aee580c9a04c3482ad4b7d0552516/nixos/modules/virtualisation/gce-images.nix#L6

cc @rbvermaa

**Comment by AmineChikhaoui** [comment]
@Mic92 I think this can be closed now (https://github.com/NixOS/nixpkgs/blob/release-18.09/nixos/modules/virtualisation/gce-images.nix#L7)
