### ISSUE TITLE
DynamicUser is broken

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#50273]
## Issue description

Currently, `DynamicUser` seems to be broken.  I thought this was a systemd
issue, but they claim it's because we misconfigured `nss-systemd`. 
https://github.com/systemd/systemd/issues/10740

However, I thought we configured this correctly since `18.09` since this commit
https://github.com/NixOS/nixpkgs/commit/72a64ea4f1f32d77b1fd34eb07efc904ae415f6b

and 

```
[arian@t430s:~/Projects/rfcs]$ cat /etc/nsswitch.conf 
passwd:    files mymachines systemd
group:     files mymachines systemd
shadow:    files

hosts:     files mymachines dns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

seems to indeed confirm this. Yet `DynamicUser` is still currently broken in `18.09`.

I have a feeling `nscd` isn't correctly loading `nss_modules` that aren't shipped with `glibc`.
This would mean `mymachines` and `myhostname` aren't loaded either if that's the case

### Steps to reproduce

```
$ sudo systemd-run --pty --property=DynamicUser=yes --property=User=iamatest whoami
Running as unit: run-u347.service
Press ^] three times within 1s to disconnect TTY.
/run/current-system/sw/bin/whoami: cannot find name for user ID 63915

```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by arianvp** [comment]
Related #50011  #49228

**Comment by arianvp** [comment]
Also related: https://github.com/NixOS/nixpkgs/issues/36297

**Comment by arianvp** [comment]
Also related: https://github.com/NixOS/nixpkgs/pull/50042#issuecomment-437839238

It seems like `nscd` isn't properly loading all `nss_modules`

**Comment by arianvp** [comment]
When I run
```
sudo systemctl stop nscd
sudo strace nscd
```

It seems to try to load  all the `nss_modules` from a very _strange_ location:

```
openat(AT_FDCWD, "/run/opengl-driver/lib/libnss_mymachines.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libnss_mymachines.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = 4

```

Anything but the right place.   So loading  custom `nss` modules seems to be broken.

**Comment by arianvp** [comment]
Okay so it actually does seem to load the libraries, after suggestion from @dezgeg 

```
[arian@t430s:~]$ sudo strace -E LD_LIBRARY_PATH=/nix/store/pb1vvbzzm0q9axbcbv9989mbz10f881z-systemd-239/lib  nscd -d 2>&1 | grep nss
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/nix/store/pb1vvbzzm0q9axbcbv9989mbz10f881z-systemd-239/lib/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/nix/store/pb1vvbzzm0q9axbcbv9989mbz10f881z-systemd-239/lib/libnss_mymachines.so.2", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/nix/store/pb1vvbzzm0q9axbcbv9989mbz10f881z-systemd-239/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/nix/store/pb1vvbzzm0q9axbcbv9989mbz10f881z-systemd-239/lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/nix/store/pb1vvbzzm0q9axbcbv9989mbz10f881z-systemd-239/lib/libnss_myhostname.so.2", O_RDONLY|O_CLOEXEC) = 4
```

Then why  is `DynamicUser` not working?

**Comment by arianvp** [comment]
cc @Ekleog

**Comment by arianvp** [comment]
Also cc @peterhoeg who originally fixed this

**Comment by Mic92** [comment]
You can use `busctl` and watch out for dbus calls to `LookupDynamicUserByName`

https://github.com/systemd/systemd/blob/master/src/nss-systemd/nss-systemd.c#L190

**Comment by Mic92** [comment]
In `strace` you should see a unix socket connection opened to dbus follow by `sendmsg` systemcalls on the resulting file descriptor.

**Comment by arianvp** [comment]
The call is being made.  I more and more suspect this being a systemd issue

```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=2
  Sender=:1.49  Destination=org.freedesktop.systemd1  Path=/org/freedesktop/systemd1  Interface=org.freedesktop.systemd1.Manager  Member=LookupDynamicUserByName
  UniqueName=:1.49
  MESSAGE "s" {
          STRING "iamatest";
  };
```

**Comment by Mic92** [comment]
The response looks as expected.

**Comment by arianvp** [comment]
Indeed. so why is the systemd unit then failing on `whoami` ?

**Comment by arianvp** [comment]
Ah I also get this in the logs:

```
‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2232  ReplyCookie=2
  Sender=:1.0  Destination=:1.167
  ErrorName=org.freedesktop.systemd1.NoSuchDynamicUser  ErrorMessage="Dynamic user iamatest does not exist."
  UniqueName=:1.0
  MESSAGE "s" {
          STRING "Dynamic user iamatest does not exist.";
  };

```

**Comment by arianvp** [comment]
This error seems to be coming from
https://github.com/NixOS/systemd/blob/nixos-v239/src/core/dbus-manager.c#L1700-L1704

which leads us to:
https://github.com/NixOS/systemd/blob/nixos-v239/src/core/dynamic-user.c#L770

**Comment by arianvp** [comment]
After hacking around with @Mic92 this turns out to be a cache invalidation problem.
See https://github.com/systemd/systemd/issues/10740#issuecomment-438237734

Since we only use `nscd` for tricking `libc` to load nss modules from an absolute path, and actually
not for its caching behaviour  the recommended course of action seems to be to disable all caching that `nscd` provides (at least for passwd and group, perhaps not for host)

This is already disabled when `sssd` is enabled (https://github.com/NixOS/nixpkgs/blob/61d125b8425da501f07765197186ed7351a55f48/nixos/modules/services/misc/nscd-sssd.conf)

So the simplest option seems to be to also use this config when `sssd` is _disabled_.

**Comment by peterhoeg** [comment]
Awesome detective work!

**Comment by jameysharp** [comment]
Since upstream systemd merged their nscd cache invalidation fix and released it in v240, and we're on v242 now, should some caching be turned on again? Seems to me like it'd be nice, but I can't imagine getent lookups are hugely performance-critical. :man_shrugging:

Either way though, perhaps you folks would be good reviewers for my pull request #64268, which gets rid of various years-old cruft from the nscd module. If non-zero TTLs are still worth-while, I'd hope my patches would be merged first.
