### ISSUE TITLE
Image looks different in Chromium/GNOME Image Viewer and Firefox/Gimp

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#50297]
## Issue description

![screenshot from 2018-11-13 09-11-29](https://user-images.githubusercontent.com/91113/48399535-33481100-e724-11e8-89d0-0c13f7948bea.png)

Any idea what's the reason for this and how to solve it? Maybe it's related to color profiles or something like that.

It could be a problem for people who want to use NixOS for graphic design work.

### Steps to reproduce

The image is a screenshot i took using GNOMEs integrated screenshot shortcut.

Here it is:
![screenshot from 2018-11-13 08-50-18](https://user-images.githubusercontent.com/91113/48399723-b9645780-e724-11e8-8513-1f46be065106.png)

## Technical details

GNOME desktop. see whole config at https://github.com/davidak/nixos-config/blob/00108154648513d076bfc335f1cc94a1d4ccb869/machines/ethmoid/configuration.nix

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 18.09.1023.06fb0253afa (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.1023.06fb0253afa, nixos-hardware, nixos-unstable-19.03pre156996.c70ad805d21"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lprndn** [comment]
I'm not an expert of color management under linux but I think this is expected.
To my knowledge neither firefox, chrome nor Gnome image viewer have color management capabilities, do they? And if they have it should be configured manually anyway. Otherwise, as they use different drawing technologies, there have no reason to display anything correctly or even identically. 
I hope I'm not mistaking here.

**Comment by jtojnar** [comment]
Eog depends on lcms2 so it should have some colour management support. Since it renders correctly (same as in Firefox) in eog on Ubuntu, I assume it is a bug.

**Comment by jtojnar** [comment]
I am unable to reproduce this on unstable (EOG 3.28.4). The image renders in EOG in the same light blue like in Firefox and GIMP.

**Comment by davidak** [comment]
On NixOS 18.09.2390.40e716b92a7, it's still differerent. That's not a problem for me.

![Screenshot from 2019-03-25 16-19-14](https://user-images.githubusercontent.com/91113/54931788-fbdf4180-4f19-11e9-9742-6811ae30e93f.png)

I close the issue and retest when 19.03 is released.
