### ISSUE TITLE
pandoc: manpages missing

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#50325]
## Issue description

While in other distributions pandoc *does* have a man page, the nixpkgs one doesn't seem to be available. I could find it neither in the pandoc nor the pandoc-data store directories. The expression also does not provide a separate `man` output directory.

#### potential fix

If I knew the supposed output path for man pages, I'd try to set the `cabal configure --mandir=DIR` flag accordingly.

### Steps to reproduce

```
nix-shell -p pandoc --command "man pandoc"                                                                                                                                    
No manual entry for pandoc
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1228.a4c4cbb613c, nixos-unstable-19.03pre158246.6141939d6e0"`
 - channels(user): `"home-manager-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

**Comment by Mic92** [comment]
Currently it is in `data`:

```
nix-shell -p haskellPackages.pandoc.data --run 'find $buildInputs | grep man1'
/nix/store/aw0rg6zwq8g476899baxf6n4i2inwdqp-pandoc-2.2.1-data/share/ghc-8.4.4/man/man1
/nix/store/aw0rg6zwq8g476899baxf6n4i2inwdqp-pandoc-2.2.1-data/share/ghc-8.4.4/man/man1/pandoc.1
```

It could be moved to the man output instead.

**Comment by cyounkins** [comment]
I think this is what is needed but I am having trouble with `hackage2nix` (see https://github.com/NixOS/cabal2nix/issues/391)

```
diff --git a/pkgs/development/haskell-modules/configuration-common.nix b/pkgs/development/haskell-modules/configuration-common.nix
index 5f56dc3a9b6..4941c403e6c 100644
--- a/pkgs/development/haskell-modules/configuration-common.nix
+++ b/pkgs/development/haskell-modules/configuration-common.nix
@@ -1185,4 +1185,6 @@ self: super: {
   # });
   libnix = dontCheck super.libnix;

+  pandoc = appendConfigureFlag super.pandoc "--mandir=$out/share/man/man1";
+
 } // import ./configuration-tensorflow.nix {inherit pkgs haskellLib;} self super
```
