### ISSUE TITLE
No such interface 'org.freedesktop.DisplayManager.AccountsService

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#50330]
## Issue description
@jtojnar thought he had fixed the following issue in #45059, but that's not accurate. 

After a reboot of a 18.09 system, I see in `journalctl -xe`:

> lightdm[5227]: Error updating user /org/freedesktop/Accounts/User<XXXX>: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.DisplayManager.AccountsService'

### Steps to reproduce
Unknown, but enabling lightdm is relevant.

## Technical details
Channel `nixos-18.09`

**Comment by peterhoeg** [comment]
Is ```services.accounts-daemon.enable = true;``` ?

**Comment by voobscout** [comment]
Having the same issue and yes, all d-bus services including accounts-daemon are enabled.
`systemctl status accounts-daemon.service` shows no errors.

**Comment by joakim1999** [comment]
@coretemp I think i have been wrongly referenced in this issue. I don't know anything about this issue.

**Comment by worldofpeace** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/feda3999095869684900ea82078036e6c3c7fd49
