### ISSUE TITLE
automatically set nix.buildCores

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#50376]
Currently, we set `nix.maxJobs = lib.mkDefault 12;` for a 12 thread processor after hardware scan. I think we should also set `nix.buildCores = 12;` or else everything uses -j 1

**Comment by Mic92** [comment]
I currently have `nix.buildCores = 0;` which sets the cores automatically.

**Comment by tbenst** [comment]
Cool! I don’t know how these things are decided but would vote for 
@Mic92’s line to be the nixos default
