### ISSUE TITLE
ssh fails with packet_write_wait: Broken pipe after upgrade

### ISSUE THREAD

**Issue by juselius** [NixOS/nixpkgs#50389]
## Issue description
After the last ``nixos-rebuild switch --upgrade`` and ``home-manager switch`` ssh stopped working. All connections terminate with ``packet_write_wait: Connection to 10.10.10.1 port 22: Broken pipe``, with the exception of connection to loopback and the IP of my local machine. Running ssh with -vvv gives no clue to what is wrong and authentication succeeds. 

Using the previous ``openssh-7.7p1`` still works fine.

### Steps to reproduce

Not sure, installing openssh-7.9p1?

## Technical details
```
OpenSSH_7.9p1, OpenSSL 1.0.2p  14 Aug 2018 
/nix/store/x6zhfr43k3mndmy66rm84lyfk8y934zz-openssh-7.9p1/bin/ssh
```

```
  - system: `"x86_64-linux"`
 - host os: `Linux 4.18.17, NixOS, 19.03pre158246.6141939d6e0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(jonas): `"nixos-19.03pre158246.6141939d6e0"`
 - channels(root): `"nixos-19.03pre158246.6141939d6e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dtzWill** [comment]
Gah, this has got to be related to recent problems I've been having too.  Regardless, I just found this:

https://bbs.archlinux.org/viewtopic.php?id=239982

and many other similar threads/reports-- does setting IPQoS as suggested help your problem? And bonus question: is vmware in any way related to your setup? It shouldn't be for me but that seems bugged or something.

**Comment by juselius** [comment]
Thanks @dtzWill! Setting IPQoS sorted it. And yes, I'm running on top of vmware.
