### ISSUE TITLE
geckodriver version incompatible to Firefox version

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#50380]
## Issue description

nixos-18.09 (and nixpgks master and everything in-between) currently ships Firefox 63.0 and geckodriver "unstable-2018-02-24" (which claims to be 0.19.1 when called with `--version`).

According to https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html#supported-platforms geckodriver &ge; 0.21 is needed to be compatible with Firefox > 62.

### Steps to reproduce

1. `nix run nixpkgs.geckodriver nixpkgs.python36 nixpkgs.firefox`
2. `python3.6 -m venv virtualenv`
3. `source virtualenv/bin/activate`
4. `pip install "selenium<4"`
5. `python3.6 -c 'from selenium import webdriver; webdriver.Firefox()'`

#### Expected

* last command runs with exit code `0` and without any terminal output
* opens an empty firefox window:
    ![bildschirmfoto von 2018-12-10 11-17-55](https://user-images.githubusercontent.com/97746/49726079-7509a000-fc6d-11e8-8c55-0c7a18247e40.png)

#### Observed

* last command runs with exit code `0` and the following terminal output
    ```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/das-g/dev/tdd/python-tdd-book/virtualenv/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
        keep_alive=True)
      File "/home/das-g/dev/tdd/python-tdd-book/virtualenv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
        self.start_session(capabilities, browser_profile)
      File "/home/das-g/dev/tdd/python-tdd-book/virtualenv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "/home/das-g/dev/tdd/python-tdd-book/virtualenv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
        self.error_handler.check_response(response)
      File "/home/das-g/dev/tdd/python-tdd-book/virtualenv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: newSession
    ```
* no Firefox window is being opened

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1228.a4c4cbb613c"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by das-g** [comment]
I'm looking into updating the geckodriver derivation, but am unsure what source repo / revision to refer to. (See mozilla/geckodriver#1427.)

**Comment by Mic92** [comment]
We also have no newer version in master. If you update the package on master, I would backport it to 18.09 as well.

**Comment by Mic92** [comment]
We also should switch to a stable release so @r-ryantm would automatically upgrade to newer releases.

**Comment by erikarvstedt** [comment]
geckodriver still doesn't work, even with `0.22.0`.
I'd love to see a fix for this.
```bash
read -d '' tmpstr <<"EOF"
with (import ((import <nixpkgs> {}).fetchFromGitHub {
  owner = "NixOS";
  repo = "nixpkgs";
  # PR-#51725 (geckodriver 0.22.0)
  # https://github.com/NixOS/nixpkgs/pull/51725
  rev = "f4a98babffe9a335d68ce42f2d4f0e47c4f52d37";
  sha256 = "0062078jliav18by6kv314hdjccbjmfn1jzli2ypc0dx74i5l2l1";
}) {});
let
  py = python3.withPackages (ps: with ps; [
    selenium
  ]);
in
  mkShell {
    buildInputs = [ py firefox geckodriver ];
  }
EOF
nix-shell -E "$tmpstr" --run "python -c 'from selenium import webdriver; webdriver.Firefox()'"
```
Result:
```
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**Comment by das-g** [comment]
I can't reproduce that, @erikarvstedt. For me your series of commands "works"
- it opens an empty Firefox window
- it runs with exit code `0` and without any output except that caused by nix building/fetching

**Comment by erikarvstedt** [comment]
Yeah, right after my (deleted) post I noticed I forgot to setup the `DISPLAY` variable .
Sorry about that, it's indeed working great! :smiley_cat:
