### ISSUE TITLE
Journaldriver was not added into the module list

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nixpkgs#50390]
https://github.com/NixOS/nixpkgs/blob/06061b7188e6beafb9651dabdda316d19b9419a5/nixos/modules/services/logging/journaldriver.nix#L1

@tazjin 

`journaldriver` should be imported into the top-level module list, so that it is visible without manually importing this module.

Might be go if it goes in here.
https://github.com/NixOS/nixpkgs/blob/06061b7188e6beafb9651dabdda316d19b9419a5/nixos/modules/module-list.nix#L305

**Comment by tazjin** [comment]
Thanks for pointing this out! Didn't notice it because we import modules from pinned `nixpkgs` versions.
