### ISSUE TITLE
Can not use QtWebEngine QML plugin

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#50399]
## Issue description

The following error occurs:

```
 plugin cannot be loaded for module "QtWebEngine": Cannot load library /nix/store/wzh8v0b1ksl9jq9wjimgwhncs4bfn53p-qtwebengine-5.11.1-bin/lib/qt-5.11/qml/QtWebEngine/libqtwebengineplugin.so: (/nix/store/wzh8v0b1ksl9jq9wjimgwhncs4bfn53p-qtwebengine-5.11.1-bin/lib/qt-5.11/qml/QtWebEngine/libqtwebengineplugin.so: symbol _ZN22QWebEngineQuotaRequest16staticMetaObjectE version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference)
```

### Steps to reproduce

Run a qml file that does `import QtWebEngine 1.7`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1206.6d6e4e6b558 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(raskolnikov): `""`
 - channels(root): `"nixos-18.09.1206.6d6e4e6b558"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by arximboldi** [comment]
I did changes in my system and can't reproduce anymore. Probably related to not having a globally installed Qt version anymore. (Only nix-shell now)

**Comment by redonadmin** [comment]
Please tell me how you resolved that problem in build file am getting same error what you posted
