### ISSUE TITLE
numpy built against buggy OpenBLAS in 18.09 - should we follow numpy builds?

### ISSUE THREAD

**Issue by ilya-kolpakov** [NixOS/nixpkgs#50407]
While using numpy from 18.09 I noticed that `np.dot()` produces randomly-corrupted output under certain conditions ([numpy issue](https://github.com/numpy/numpy/issues/12394)). 

### Reasons

The problem is likely to be caused by OpenBLAS 0.3.1 which is [default in 18.09](https://github.com/NixOS/nixpkgs/blob/24da975834319efce3af4ef21db5be675d469b7f/pkgs/development/libraries/science/math/openblas/default.nix#L81-L82). This version is [known](https://github.com/numpy/numpy/issues/12394#issuecomment-439035003) to be buggy among numpy devs and they have been [building](https://github.com/numpy/numpy/blob/master/doc/release/1.15.4-notes.rst) all numpy 0.15.x releases (including the latest 0.15.4) against OpenBLAS 0.3.0.

In contrast, nixpkgs-unstable already packaged OpenBLAS [0.3.3](https://github.com/NixOS/nixpkgs/blob/acceb53c5b7c25dc8c820ef0c848a33bedb44300/pkgs/development/libraries/science/math/openblas/default.nix#L81-L82) and I guess is already being used for numpy builds.

### Proposal

I suggest that the versions of dependencies used by numpy/scipy derivations (by default) should exactly match the versions used in binary builds done by numpy/scipy communities. The possibility of basic linear algebra routines working incorrectly is simply unacceptable and I think this possibility is minimized if we use the same dependency versions.

@ttuegel @FRidh 

EDIT: ping maintainers

**Comment by coretemp** [comment]
Some scientific user should just setup some tests and based on those tests some set of candidate combinations of versions would be computed. Finally, a simple heuristic to compute a combination of versions compatible with all should be computed and outputted. That's the version that should end up in a release or in `master` generally. 

This procedure should be run every day in some CI system. 

Depending on others for such stuff is manual work and will never work in the long term. 

In scientific communities, it's unfortunately the case that newer versions don't always mean "better" versions. There are some other software ecosystems for which a similar thing holds.

**Comment by ilya-kolpakov** [comment]
The problem is indeed threading-related. I don't see errors if I tell OpenBLAS to use only one thread (`OMP_NUM_THREADS=1`).

**Comment by coretemp** [comment]
@ilya-kolpakov I never referred to the numpy test suite. I am talking about using an application specific test suite that fits your exact business goals. Such a test suite might contain as a part the numpy test suite, but that's it. 

For example, I would find a working version of numpy and compute your program with thousands of different inputs and make sure that the answers in new candidate production versions match the old ones.

**Comment by markuskowa** [comment]
Fixing the version of OpenBLAS does not seem to be practical in the long run. I propose to backport OpenBLAS 0.3.3 to 18.09, since this bug potentially also affects other applications.

**Comment by FRidh** [comment]
If there is a clear improvement, then I am not against backporting a newer version of OpenBLAS. However, from the linked numpy issue there is no clear improvement. It seems every release has its issues, and that we're trading one known issue (the one you're facing) for another threading issue. In that case I think it should be up to the user to choose the version that best suits them.

**Comment by ilya-kolpakov** [comment]
One could probably fix 18.03 without backporting by making OpenBLAS use only one thread by default. It's probably a reasonable default for upcoming 0.3.4 as well until there's solid evidence that threading bugs were resolved.

**Comment by FRidh** [comment]
> One could probably fix 18.03 without backporting by making OpenBLAS use only one thread by default. It's probably a reasonable default for upcoming 0.3.4 as well until there's solid evidence that threading bugs were resolved.

This sounds reasonable.

**Comment by ttuegel** [comment]
> I suggest that the versions of dependencies used by numpy/scipy derivations (by default) should exactly match the versions used in binary builds done by numpy/scipy communities.

With my OpenBLAS package maintainer hat on, I have no problem keeping around older versions for as long as they are used by current packages. My only cautionary note would be: this will make it more difficult to mix-and-match packages, since they might depend on different OpenBLAS versions. That won't be a problem for frameworks like numpy, but it may be a problem if we see many small libraries pinning versions. I don't think that potential problem is severe enough to forbid pinning, however.

**Comment by FRidh** [comment]
0.3.4 in #51467 for master

**Comment by FRidh** [comment]
Old issue so closing.
