### ISSUE TITLE
nixos/modules/security/pam_mount.nix

### ISSUE THREAD

**Issue by voobscout** [NixOS/nixpkgs#50400]
## Issue description
Unable to override environment.etc."security/pam_mount.conf.xml" because
https://github.com/NixOS/nixpkgs/blob/101133deaeea1194f4a915d8f27ad485d68e4e36/nixos/modules/security/pam_mount.nix#L54
is in the wrong place! It should be the last line in pam_mount.conf.xml, right after
https://github.com/NixOS/nixpkgs/blob/101133deaeea1194f4a915d8f27ad485d68e4e36/nixos/modules/security/pam_mount.nix#L66
Since this appears to  be the only interface to customize pam_mount, changes should stick imho
Certainly, one can mkForce the conf, but why if the module already appends lines, just in an odd place.

On the other hand i might be completely wrong, being nix noob and all. In case I'm please help me learn the correct way of accomplishing this with nix.

### Steps to reproduce
```nix
{
  security.pam.mount.enable = true;
  security.pam.mount.extraVolumes = [
    "<mkmountpoint enable=\"0\" remove=\"false\" />"
    "<path>/run/wrappers/bin:/run/current-system/sw/bin</path>"
    "<debug enable=\"1\" />"
    "<luserconf name=\".pam_mount.conf.xml\" />"
    "<fusemount>/run/current-system/sw/bin/mount.fuse %(VOLUME) %(MNTPT) -o %(OPTIONS) </fusemount>"
    "<fuseumount>/run/wrappers/bin/fuserumount -u %(MNTPT) </fuseumount>"
  ];
}
```

**Comment by NetaliDev** [comment]
The `pam_mount` module has gotten a lot of new options since 2018, allowing you to set everything you wanted to do there in the `extraVolumes` option. Therefore this should not be a problem anymore.
