### ISSUE TITLE
Linux packages on stable channels

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#50412]
cc @NeQuissimus 

Hi, opening this issue to get in touch with you @NeQuissimus.

New kernel releases don't reach stable channels, and it's kind of an issue. When 18.03 was the current stable, if memory serves, `linuxPackages_latest` was at one point downgraded since the version that was tracked as latest was EOL'd and the newer versions weren't added. See #43235.

There's no EOL date for 4.18 yet, but the situation will probably arise soon that on nixos-18.09 `latest` would need to be downgraded to the LTS (4.14).

In my opinion, and I believe some others too<sup>[who?]</sup>, it would be much better to keep `_latest` the latest release, and also backport all the new versions to the *current stable* branches. That is, without changing the default! Other than ensuring no downgrades, one advantage into adding new releases is that the stable channels keep being compatible with bleeding edge hardware more easily.

Is there anything causing issues with your (automated, I presume) updates with regards to adding new releases to the stable channels? Is there anything I can help with?

**Comment by NeQuissimus** [comment]
I have absolutely no issue with that.
My process is actually only semi-automatic, so it should be possible easily enough.

If I understand you correctly, you suggest to essentially keep the kernels between `master` and `release-XX.XX` the same; except no backports of removals, of course.
Is that correct?

**Comment by samueldr** [comment]
Removal for EOL'd kernels are not an issue IMHO, it's more about how a removal without a new kernel version causes a downgrade. And furthermore, new kernels are a generally (imho) good thing. Additionally, users seem [generally surprised](https://www.reddit.com/r/NixOS/comments/9x8kdr/why_the_latest_kernel_is_not_updated_in_repo/) that `_latest` doesn't point to the latest stable released kernel.

So:

  * For current stable minus 1 (e.g. 18.03 right now) once it's past our EOL I have no strong opinions out of anything. Your additional updates can continue as they do, without adding new kernels. They already exceed the minimum efforts :+1:.
  * For current stable (e.g. 18.09 right now) backporting all kernel updates and additions as they are on unstable is probably for the best.

And finally, thanks!

**Comment by NeQuissimus** [comment]
Bringing 4.19.x to `18.09`: 21146197c34 826e7b3bf0a a4d225c2784

I am going to cherry-pick all kernel updates into `18.09` from now on.

Note that 4.19 is actually going to become an LTS kernel, so this one especially makes sense to bring into the stable release.
