### ISSUE TITLE
firefox enable content sandbox

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#50428]
## Issue description
Firefox's `common.nix` includes this.

Can we enable the sandbox now?

```
  configureFlags = [
    ...
    #"--enable-content-sandbox" # TODO: probably enable after 54     
    ...
  ]
```

**Comment by S-NA** [comment]
That comment can be removed. From some investigating into [old-configure.in](https://github.com/mozilla/gecko-dev/blob/master/old-configure.in) that configure flag is seemingly gone. Also `Content Process Sandboxing` reports `true` in `about:support` which makes me believe that it has been folded into the default enabled sandbox.
