### ISSUE TITLE
browserpass not working ("Error: Specified native messaging host not found.")

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#50425]
## Issue description

I reported this for browserpass, but they think it's a bug in the package: https://github.com/browserpass/browserpass/issues/299

### Steps to reproduce

- Install browserpass through nixpkgs: https://github.com/browserpass/browserpass#installing-the-host-application
- Install the chrome plugin: https://github.com/browserpass/browserpass#installing-the-chrome-extension
- Press the icon to see the error message

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(simendsjo): `""`
 - channels(root): `"nixos-18.09.1228.a4c4cbb613c, nixos1803-18.03.133311.5d19e3e78fb, nixos1809-18.09.932.09195057114"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by maximbaz** [comment]
I'll add some details to help you investigate. You package installs [host.json](https://github.com/browserpass/browserpass/blob/master/chrome/host.json) file which defines `path` to the `browserpass` binary (in place of `%%replace%%` placeholder). The message "Specified native messaging host not found" very much suggests that the binary is not present at that location.

**Comment by hedning** [comment]
See https://github.com/NixOS/nixpkgs/issues/47340 and https://github.com/NixOS/nixpkgs/issues/33748. We patch firefox to look for the host.json manifest in the correct place, but it looks like the patch no longer works.

The workaround is adding the json manifest to `~/.mozilla/native-messaging-hosts`. Something like this should most likely do the trick:
```bash
mkdir -p ~/.mozilla/native-messaging-hosts
ln -s /run/current-system/sw/lib/mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json ~/.mozilla/native-messaging-hosts/

**Comment by maximbaz** [comment]
To clarify, the reported issue was for Chrome and/or Chromium, corresponding path is one of these instead of `~/.mozilla/native-messaging-hosts/`:

- `~/.config/google-chrome/NativeMessagingHosts`
- `~/.config/chromium/NativeMessagingHosts`

**Comment by hedning** [comment]
Yeah, sorry misread and assumed it was the same issue that've popped up a bunch of time with firefox. Chrome should indeed look for the manifest files under `/etc` so that's quite strange.

**Comment by simendsjo** [comment]
False alarm! Sorry! :(
I didn't enable the program, ref https://github.com/browserpass/browserpass/issues/299#issuecomment-439188599
