### ISSUE TITLE
`nix copy --to ssh` is slow on high-latency links

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#50466]
## Issue description
For links with a high bandwidth-delay product, e.g. when copying a Nix closure to a datacenter on the other side of the planet, the copy progresses far slower than expected.

Observed behaviour is that individual files are copied at the link speed, but each new file requires at least one roundtrip.

The copies should ideally be pipelined.

### Steps to reproduce

`nix copy /run/current-system --to ssh://<Anywhere with high latency and high bandwidth>`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 18.09pre-git (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/etc/nix-system-pkgs`

**Comment by Infinisil** [comment]
This is a Nix issue, not a nixpkgs one, so you should file this issue here instead: https://github.com/NixOS/nix/issues
