### ISSUE TITLE
NixOS services: When to have a package option

### ISSUE THREAD

**Issue by Infinisil** [NixOS/nixpkgs#50476]
## Issue description
It has become somewhat of a pattern to add a `package` option to NixOS service modules for selecting a package to use for the service. Doing a quick count, of the ~600 service modules in nixpkgs about 120 of them have a `package` option. For comparison, the total amount of options in nixpkgs is about 7000. Every new NixOS option increases evaluation time for all NixOS system evaluations, whether you use it or not. Adding an option just because other services do it doesn't sound sensible. I'd rather add this option only once a need for it arises.

This is an issue to track opinions about this.

### Alternative
In general, all packages can already be overridden via overlays. To override the package `foo` with `foo2`:
```nix
{
  nixpkgs.overlays = [(self: super: {
    foo = self.foo2;
  })];
}
```

### The need for such an option

The 3 uses I see for a package option are:

- There are alternate packages you would want to use and being able to use different packages is an integral part of the module. Having an option makes this possibility discoverable. `postgresql` is such an example (`postgresql_9_3`, ..., `postgresql_11`).
- Using an overlay for it would require a lot of rebuilds, because overlays not only change the package the service uses, but all the other parts of the system as well. curl would be such an example.
- Using an overlay for it would change some other part of the system you don't want to change. E.g. 2 services that need the same package but different versions of it. An overlay couldn't change just one of them.

### Related

For reference, I used this to find these:
```bash
while true; do firefox $(git blame $(fzf) | rg '([^ ]+) .*package = mkOption' -or 'https://github.com/NixOS/nixpkgs/commit/$1'); done
```

#### Related discussions

- @domenkozar @Phreedom and @offlinehacker discussing such an option: https://github.com/NixOS/nixpkgs/pull/1099#issuecomment-26735837
- @joachifm being agains this option and @yegortimoshenko being for it: https://github.com/NixOS/nixpkgs/pull/48289#issuecomment-432277496
- @Infinisil being against this option and @Ekleog being for it: https://github.com/NixOS/nixpkgs/pull/49228#discussion_r228766338
- @Infinisil being against this option: https://github.com/NixOS/nixpkgs/pull/48036#discussion_r228851466
- @fmthoma being against this option and @ericsagnes being for it: https://github.com/NixOS/nixpkgs/pull/20385#issuecomment-260564134
- @Profpatsch questioning @nckx adding the option: https://github.com/NixOS/nixpkgs/commit/24048fa226f3#r13375587
- @joachifm questioning @rnhmjoj adding the option: https://github.com/NixOS/nixpkgs/pull/15228#discussion_r62103727 followup.. https://github.com/NixOS/nixpkgs/pull/18398
- @joachifm questioning @makefu adding the option: https://github.com/NixOS/nixpkgs/pull/19176#discussion_r81480381

#### Justified addings of the option
- Because there are multiple asterisk versions now: https://github.com/NixOS/nixpkgs/pull/22358
- Because there are multiple btsync versions now: https://github.com/NixOS/nixpkgs/pull/7215
- Because there are multiple datadog versions now: https://github.com/NixOS/nixpkgs/pull/40399
- Because there are multiple foundationdb versions: https://github.com/NixOS/nixpkgs/commit/5a24d99fa628
- Because there are multiple gitlab-runner versions now: https://github.com/NixOS/nixpkgs/pull/24254
- Because there are multiple apacheHttpd versions: https://github.com/NixOS/nixpkgs/commit/52c97adaba852a612d801332ce84c503680ff497
- Because there are multiple quassel versions: https://github.com/NixOS/nixpkgs/pull/20159
- Because there are multiple radicale versions now: https://github.com/NixOS/nixpkgs/pull/27826
- Because there are multiple riak versions now: https://github.com/NixOS/nixpkgs/pull/7827
- Because there are multiple samba versions: https://github.com/NixOS/nixpkgs/commit/8ec82fcb18cb
- Because there are alternate sick... versions: https://github.com/NixOS/nixpkgs/pull/46607
- Because there are multiple softether versions now: https://github.com/NixOS/nixpkgs/pull/29781
- Because there are multiple syncthing versions now: https://github.com/NixOS/nixpkgs/pull/11329
- Because there are multiple upower versions now: https://github.com/NixOS/nixpkgs/commit/df95a8cc2f92
- Because there are multiple varnish versions now: https://github.com/NixOS/nixpkgs/pull/37412
- Because there are multiple bspwd versions: https://github.com/NixOS/nixpkgs/pull/20384

#### Commits/PRs that add the option without justification
Mostly these are probably just people not knowing they can use overlays to do it. I'm pinging all of you in the hopes that you see that overlays could have been used instead or to potentially find other reasons to introduce such an option.

- @shlevy https://github.com/NixOS/nixpkgs/commit/5ee75e236c0c
- @zimbatm https://github.com/NixOS/nixpkgs/pull/30614
- @sheenobu https://github.com/NixOS/nixpkgs/pull/21877
- @fpletz https://github.com/NixOS/nixpkgs/commit/ed979124cad7
- @edef1c https://github.com/NixOS/nixpkgs/pull/12223
- @mbbx6spp https://github.com/NixOS/nixpkgs/pull/9880
- @pacien https://github.com/NixOS/nixpkgs/pull/46741
- @copumpkin https://github.com/NixOS/nixpkgs/commit/ced27b2966ec
- @nckx https://github.com/NixOS/nixpkgs/commit/fa3d7ea77ba1
- @etu https://github.com/NixOS/nixpkgs/pull/40565
- @pstn https://github.com/NixOS/nixpkgs/pull/39681
- @offlinehacker https://github.com/NixOS/nixpkgs/commit/1cdb6cfb0095
- @earldouglas https://github.com/NixOS/nixpkgs/commit/aae32e15af60
- @offlinehacker https://github.com/NixOS/nixpkgs/commit/988ed87e70e8
- @aespinosa https://github.com/NixOS/nixpkgs/pull/41909
- @Ekleog https://github.com/NixOS/nixpkgs/pull/42153
- @thoughtpolice https://github.com/NixOS/nixpkgs/commit/59acfd4f16ea
- @dotlambda https://github.com/NixOS/nixpkgs/pull/34974
- @offlinehacker https://github.com/NixOS/nixpkgs/commit/4947bacd52c7
- @Profpatsch https://github.com/NixOS/nixpkgs/pull/22636
- @lsix https://github.com/NixOS/nixpkgs/pull/11870
- @rickynils https://github.com/NixOS/nixpkgs/commit/8fc777ffd6bb
- @bjornfor https://github.com/NixOS/nixpkgs/commit/a44de69d06e3
- @LnL7 https://github.com/NixOS/nixpkgs/pull/44848
- @lethalman https://github.com/NixOS/nixpkgs/commit/614162ee6c4e
- @dezgeg https://github.com/NixOS/nixpkgs/commit/69b4f427b67f
- @roblabla https://github.com/NixOS/nixpkgs/pull/18152
- @markus1189 https://github.com/NixOS/nixpkgs/pull/34655

**Comment by domenkozar** [comment]
I'd be happy to discuss this once we see how much impact do these 600 options have on evaluation time :)

**Comment by copumpkin** [comment]
My vote is to put it in for all services that have a relevant notion of packages backing them. The main reason for this is that it's not always clear which packages are being used by a service (e.g., we have `services.httpd` which uses `pkgs.apacheHttpd`; yes the module lives in `services/apache-httpd` but in general nothing requires them to line up) so unless someone pokes at the nixpkgs source code, they don't necessarily know which module to override and there's no real feedback to figure out which was overridden other than hoping to see the .service unit get rebuilt if you got it right.

The reasons you give in favor of the field also factor into my preference. I'm already frustrated at how "singleton"-flavored our services all are, so forcing all of them to go through a single registry of versions seems annoying.

**Comment by Infinisil** [comment]
@copumpkin That's a good point, I haven't thought of this.

Eventually I hope that we can have a generic service module creator function that contains stuff like `enable`, `user`, `group`, `package`, `extraArgs`, `configFile`, etc. (with some configurability)

**Comment by matthewbauer** [comment]
I favor the idea of using overlays here. You should be able to accomplish the same thing as the package option with a simple overlay of pkgs. This works without the extra code of implementing and documenting extra options.

**Comment by jtojnar** [comment]
> Because there are multiple upower versions now: df95a8c

Not anymore https://github.com/NixOS/nixpkgs/commit/2a2cb8354ecfada313dcdb36154000c7f7f74964#diff-0bcefda72ac48cd4aa6372226ec3f6a7

**Comment by 7c6f434c** [comment]
A bit more general question: so enable-guarding still pays the cost for the options inside the module? Can this problem be fixed globally? Maybe via some kind of conditional require-management, I am not sure.

**Comment by Ekleog** [comment]
@7c6f434c See also https://github.com/NixOS/rfcs/pull/22

**Comment by LnL7** [comment]
The package option isn't only useful for overrides or even using a different channel. Having to override the default attribute means there's no choice to do this in a contained way anymore. Even when using overlays I always do this instead.

```nix
{
  services.foo.package = pkgs.namespace.foo;
  nixpkgs.overlays = [(self: super: {
     namespace.foo = super.foo.override { withBar = true; };
  })];
}
```

**Comment by joachifm** [comment]
To me, the problem is mechanically adding options "just because" we can. Sure, there are cases where it makes sense to expose the underlying package but I simply do not understand the desire to clutter interfaces with what should be an implementation detail unless absolutely necessary. My view is that fewer options is better and no options is best (regardless of eval time).

**Comment by 7c6f434c** [comment]
@joachifm I guess a nontrivial subset of Nixpkgs/NixOS developers have experience that unchangeable defaults end up in a state not fitting our needs. This leads to the ideal of having a lot of knobs that can be ignored if everything acceptable, but provide an escape hatch if something exotic/complicated is desired. Then it turns out there are evaluation time issues…

I might be wrong, as I don't use NixOS proper anymore, and I use only a reasonably small subset of NixOS module code. (A few unchangeable defaults ended p annoying me too much).

**Comment by coretemp** [comment]
Essentially echoing @7c6f434c with some details:

The overlay system provides a single global overlay. There is no way to say that you want one service to use an overridden version and for another you don't, which is actually something I use currently. 

There are workarounds for that too, but your proposed solution is inferior. 

AFAIK, I need to fork the module in order to modify it to my needs in that case. Having a package option means I need to fork less often, which is what most people probably want. 

P.S. Kind of curious as to what @7c6f434c is using.

**Comment by joachifm** [comment]
@7c6f434c that's fair, but I take it you don't think we should add options willy nilly without any regard for whether they make sense? All I really ask is for *some* justification. It doesn't have to make sense for everybody, but it has to make sense (realistically) for somebody.

I see several general claims that overriding a specific package only for a specific module is useful but few concrete examples. For it to be a general policy I'd hope we could agree that it has to make sense more often than not.

Am I alone in thinking that there are real costs associated with greater variability implied by adding options beyond eval time?

**Comment by 7c6f434c** [comment]
@joachifm About overlays — maybe in general, given discussions like #43266 not everyone fully trusts overlays for all use cases. And we usually ship a single client+server package and people might want to override the two parts independently.

You are not alone in thinking there is a cost — different people get different levels of annoyance from having to deal with an interface with many optional knobs, and also from not having access to obvious knobs. I guess we never had a Nix* survery to know the local shape of the distribution (there is a weird enough selection criterion that I don't expect general population studies of option paralysis, cost of choice etc. to apply)

Of course, reminding people about `disabledModules` to replace a single module (like in https://github.com/NixOS/nixpkgs/issues/46464 discussion) is useful.

@coretemp I guess explicitly saying what service you are talking about might help to discuss specifics.

Re: P.S. — feel free to email me or open an issue about lack of documentation against my `lang-os` repo or something; by the way, there you can find an example of grabbing things out of a separate NixOS import — maybe this can be combined with overriding Nixpkgs in a reimport of NixOS for some intents.

**Comment by coretemp** [comment]
@7c6f434c For $CENSORED_REASONS I was vague on this topic. It was a fair question. Perhaps I can answer the question in a fairly long time.

**Comment by Shados** [comment]
@Ekleog 
> 
>     * Before, `9.47s user 0.68s system 133% cpu 7.599 total`
> 
>     * After, `9.11s user 0.56s system 135% cpu 7.118 total`

This is interesting, but for the results to be useful you'd really need to take some steps to exclude other factors from influencing the benchmark (e.g. by running each case many times over and looking at the distribution of results). 0.48s is a lot more of a change than I would expect for only 19 less options; it seems likely the difference has more to do with other things happening on the system during the tests.

-------

Some thoughts:
- A `package` option is the only visible thing blocking #48036 and #48289 from being merged, which is odd given this issue doesn't appear to have reached any kind of consensus.
- While it is true you can use overlays to override service packages, this becomes more problematic if you are sharing a nixpkgs build between several machines (e.g. because you're using nixops or morph) and only want to override the package on one of them ([example issue using morph](https://github.com/DBCDK/morph/issues/34)). This is an issue that could be fixed with nixpkgs changes, but is not at this point.
- The stated concerns are evaluation time, and "option bloat in general". Is impact on evaluation time significant? Is "option bloat" an issue for non-performance reasons? Will the answers to those questions still be true if/when either nix-flakes, or configurations as a language feature, are implemented?

**Comment by zimbatm** [comment]
I propose to close this issue and go toward adding `package` attribute to all the modules that are backed by a single package.

Without a proper benchmark it's not worth talking about hypothetical performance improvements. NixOS evaluation is highly sensitive to the disk cache and needs to be repeated many times.

On the other hand, having a consistent interface is useful on many levels. Like @copumpkin said, the user can rely on the option being there and not have to dig into the nixos source. Not everybody has write access to nixpkgs to add the package option "when needed".

**Comment by Infinisil** [comment]
I think the ideal way to solve this would be to add a generic `nixos.services.*` option (or `tasks.*` or `jobs.*` or whatever), defined somewhat like this:
```nix
{
  options.nixos.services = mkOption {
    type = types.attrsOf (types.submodule {
      options = {
        package = mkOption {
          type = types.package;
        };
        
        user = mkOption {
          type = types.str;
        };

        systemd = mkOption {
          type = /* ... */;
          description = "systemd.services.* link";
        };
      };
    });
  };
}
```

This is then like a layer on top of `systemd.services` which defines all the additional options NixOS services ought to have, like `package`, `user`, `group`, maybe even `dataDir`, `config` and/or `configFile`.

In this new abstraction layer we could define all these options without having to clutter all service definitions with duplicate definitions.

This would then be customizable like this:
```nix
{ pkgs, ... }: {
  services.foo.service.package = pkgs.foo_1;
  services.foo.someFooSpecificOption = 10;
  services.foo.service.systemd.preStart = "echo hi";
}
```

Where `services.foo.service` is a link to the corresponding `nixos.services.foo` option set.

**Comment by Infinisil** [comment]
I guess we can close this, most people seem to be for always having a package option. Previously I was against this, but I've since changed my opinion and think that it might very well be alright to always have it, even if it's not immediately useful.
