### ISSUE TITLE
Missing /run/opengl-driver/lib/dri/vboxvideo_dri.so

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#5051]
Don't know if expected or unexpected, but doing a `nixos-rebuild boot`, then reboot but the `/run/opengl-driver` is still the old one. Had to do `nixos-rebuild switch` to fix it.

**Comment by Profpatsch** [comment]
(triage) @lethalman can you still reproduce this?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.

**Comment by husnoo** [comment]
hi, how do you "put "virtualbox" in your drivers, "?

thanks

**Comment by vcunat** [comment]
`services.xserver.videoDrivers = [ "virtualbox" ]` but note that `virtualisation.virtualbox.guest.enable = true;` should include it automatically.

**Comment by husnoo** [comment]
Hmm.. unfortunately I have both, and it still didn't help...

`glxinfo| grep "renderer string"
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)
`

**Comment by rehno-lindeque** [comment]
@husnoo OpenGL acceleration has never worked as mentioned above. 

In trying to understand how everything fits together I've managed to get the `vboxvideo_dri.so` file to show up in my `/run/opengl-driver/lib/dri` folder using 

```
{ pkgs
, config
, ...
}:

let
  makeVideoDrivers = p: p.buildEnv {
    name = "mesa+vbox+txc-${p.mesa_drivers.version}";
    paths =
      [ p.linuxPackages.virtualboxGuestAdditions # for the DRI driver
        # p.mesa_drivers # (replaces this)
        p.mesa_drivers.out # mainly for libGL
        (if config.hardware.opengl.s3tcSupport then p.libtxc_dxtn else p.libtxc_dxtn_s2tc)
      ];
  };
in
{
  hardware = {
    opengl = {
      enable = true;
      extraPackages = [pkgs.linuxPackages.virtualboxGuestAdditions];
    };
  };
}
```

but I haven't yet clarified for myself what the relationship (if any) between the `vboxvideo_dri.so` and `VBoxOGL.so` / `libGL.so.1` is (which you mentioned in https://github.com/NixOS/nixpkgs/issues/18457#issuecomment-268750395) so I may well be grasping at straws.

**Comment by Profpatsch** [comment]
Please move discussions like those to new issues.
