### ISSUE TITLE
GTK3 apps have no widget themes

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#5053]
GTK3 apps have no themes when run outside of Gnome. For example, with `gnome_themes_standard` installed in the user profile and the theme set to Adwaita, running

```
evince
```

has no theming. If you set `GTK_DATA_PREFIX` instead,

```
GTK_DATA_PREFIX=$HOME/.nix-profile evince
```

it is themed correctly. If the theme is installed in the system profile, set `GTK_DATA_PREFIX` appropriately.

**Comment by Profpatsch** [comment]
(triage) @vcunat @lethalman This is probably fixed by now, right?

**Comment by vcunat** [comment]
I'm not sure. Xfce and e19 set `$GTK_DATA_PREFIX` to the system-env path, so that would e.g. prevent me experiencing the problem.

**Comment by Profpatsch** [comment]
Sounds to me like a workaround

**Comment by Mic92** [comment]
What would be the right place to document this workaround? I found it quite useful.

**Comment by Profpatsch** [comment]
Previously the wiki, but I’m not sure where something like that should go now (cc @garbas). We desperately need a cookbook.

**Comment by garbas** [comment]
there is already a section on [Qt](http://nixos.org/nixpkgs/manual/#sec-language-qt), i guess we can create one for GTK as well

**Comment by Mic92** [comment]
Mhm the headlines says `Nixpkgs Contributors Guide` but this looks this looks like a end-user problem, not related to package contribution. Probably I will write to the wiki anyway to avoid this docbook stuff.

**Comment by Profpatsch** [comment]
@Mic92 The wiki is in read-only mode and won’t be switched back.

**Comment by garbas** [comment]
@Mic92 yes, the title is misleading. we should also fix that. right now we need to collect all documentation resources in one place. then it will be much easier to create shape documentation which would target different audience.

**Comment by Profpatsch** [comment]
(triage) has it been fixed by now?

**Comment by peterhoeg** [comment]
I'm happily running gtk3 applications outside of gnome without issues, so I think this is safe to close.
