### ISSUE TITLE
staging-next: ghc fails to build

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#50569]
## Issue description
```
checking for references to /build in /nix/store/pnqzxhbr1ybj4rvzzgjxnn0ggs9r3lha-ghc-8.4.4-doc...
output '/nix/store/rrzz5sap3zg6n5xkmspj5asv0d8mqhpa-ghc-8.4.4' is not allowed to refer to the following paths:
 /nix/store/1dzsd6drn31dgp3hk74x2h87j6jdj55b-perl-5.28.0
```

### Steps to reproduce

https://hydra.nixos.org/build/83880491

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by FRidh** [comment]
cc  @peti @ryantm @basvandijk

**Comment by markuskowa** [comment]
ghc also fails to build particularly on aarch64 (but for a different reason?) e.g.: https://github.com/NixOS/nixpkgs/pull/50675#issuecomment-439787883

**Comment by FRidh** [comment]
issue is solved. On Aarch64 a lot is failing.
