### ISSUE TITLE
staging-next: not allowed to refer to the following paths

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#50570]
## Issue description

I've seen this now with multiple builds on `staging-next`.

### Steps to reproduce

ghc: https://github.com/NixOS/nixpkgs/issues/50569
inkscape: https://hydra.nixos.org/build/84085629

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by FRidh** [comment]
Related to https://github.com/NixOS/nixpkgs/pull/49742/commits/8dbfb61e4617050917ce6bb7c5f4efc902c2a36c, cc @matthewbauer

**Comment by FRidh** [comment]
Looks like perl needs to be moved from `nativeBuildInputs` to `buildInputs`.

**Comment by hedning** [comment]
Same issue with [`bc`](https://hydra.nixos.org/build/83679148/nixlog/2). Not sure why `flex` would end up in the RPATH though, as I assumed strictDeps would restrict nativeBuildInputs being added by eg. `ld-wrapper`.

**Comment by matthewbauer** [comment]
@hedning is it in the RPATH? This can also happen if there are just some random references to it in debugging, etc.
