### ISSUE TITLE
ntpd: insecure config, no way to modify it

### ISSUE THREAD

**Issue by reardencode** [NixOS/nixpkgs#50732]
## Issue description
The ntp.conf file generated by the ntpd.nix derivation has no default restriction, so is wide open if UDP port 123 is open in the firewall.

### Steps to reproduce
`services.ntp.enable = true;`

## Technical details

ntp.conf should include a default restriction along the lines of:
```
restrict    default limited kod nomodify notrap noquery nopeer
restrict -6 default limited kod nomodify notrap noquery nopeer
restrict    source  limited kod nomodify notrap noquery
```
Or at the very least have a way to specify extra config as a string.

**Comment by coretemp** [comment]
Thanks, please add some small notes as to why one would want this to the options for those people who don't know by heart what the restrictions are about.

**Comment by coretemp** [comment]
@reardencode Yes
