### ISSUE TITLE
nix-shell does not change current directory

### ISSUE THREAD

**Issue by s9gf4ult** [NixOS/nixpkgs#50778]
## Issue description

When I run `nix-shell -A hello '<nixpkgs>'` I get bash shell with current directory set to home

### Steps to reproduce

1. Open new terminal
2. `nix-shell -A hello '<nixpkgs>'`

#### Expected 
3. Shell opened in work directory of `hello` package

#### Got 
3. Shell with current directory set to `$HOME`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-gentoo, Gentoo, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(razor): `"nixpkgs-18.09.1228.a4c4cbb613c, nixos-18.09-18.09.1023.06fb0253afa"`
 - nixpkgs: `/home/razor/.nix-defexpr/channels/nixpkgs`
```

**Comment by matthewbauer** [comment]
I can't reproduce this. It has the same directory before and after the nix-shell call.

**Comment by siddharthist** [comment]
I also get the same working directory before and after the call to `nix-shell`, which I believe is the intended behavior. 

I think the "expected" behavior of this ticket is not the intent of the tool. It sounds like @s9gf4ult is running `nix-shell` from their `HOME` directory (see step 1, open a new terminal).

**Comment by orivej** [comment]
@s9gf4ult, it sounds like you need https://github.com/dezgeg/nix-debug-shell

(We should provide it Nixpkgs, after fixing [readlink](https://github.com/dezgeg/nix-debug-shell/blob/6036010a46710cb672af9c591c6fc6157f0aba75/nix-debug-shell#L3) incompatibility with Darwin.)

**Comment by s9gf4ult** [comment]
Yes, exactly. I've expected to get building environment with working directory, and built dependencies. @orivej maybe I need `nix-debug-shell`. Is it behaves like this?

**Comment by s9gf4ult** [comment]
Ok, if this is expected behaviour, then this is not an issue.
