### ISSUE TITLE
Nextcloud add `extraTrustedProxies` and/or `extraConfig` option

### ISSUE THREAD

**Issue by fkjogu** [NixOS/nixpkgs#50838]
## Issue description
In the nextcloud module, add an option to set the `trusted_proxies` [configuration option](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/reverse_proxy_configuration.html). It is needed when running the nextcloud service behind a reverse proxy.

Alternatively or additional add an `extraConfig` option to the module.

_I'm a nix learner; once I feel comfortable I'll implement this myself. Until then, feel free to implement it or just leave the issue as a reminder._

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.1379.04005e5f71a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1379.04005e5f71a, unstable-19.03pre155123.32bcd72bf28"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by flokli** [comment]
This has already been implemented in #77480, closing here :tada:
