### ISSUE TITLE
Installing nixos.way-cooler fails because of petgraph

### ISSUE THREAD

**Issue by loewenheim** [NixOS/nixpkgs#50847]
## Issue description
`way-cooler` depends on `petgraph 0.4.10`. Building the latter fails with multiple error messages like this one:
```
error[E0034]: multiple applicable items in scope
    --> src/graph_impl/stable_graph/mod.rs:1173:19
     |
1173 |         self.iter.find_map(|(i, node)| {
     |                   ^^^^^^^^ multiple `find_map` found
     |
```

`petgraph`'s [readme](https://github.com/bluss/petgraph) has this to say:
- 0.4.13
   - Fix clippy warnings by @jonasbb
   - Add docs for Csr by @ksadorf
   - Fix conflict with new stable method find_map in new Rust

The third point seems like it might be germane to this issue.

### Steps to reproduce
`nix-env -iA nixos.way-cooler`

## Technical details
```
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 19.03pre159472.80738ed9dc0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre159472.80738ed9dc0"`
 - channels(sebastian): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by backsy** [comment]
I was installing from arch linux Aur and ran into same errors.

**Comment by backsy** [comment]
I was installing from arch linux Aur and ran into same errors. I edited the Cargo.toml locally to use ver 0.4.13 which resulted in a successful build. I removed the build part from the PKGBUILD to use what i built and it succeeded. Not sure its fully functional but i could use dmenu and open firefox. Terminal seems to be missing but i might be doing something wrong...

**Comment by gnidorah** [comment]
@loewenheim Does the https://github.com/NixOS/nixpkgs/pull/53220 works for you?

**Comment by loewenheim** [comment]
@gnidorah Stupid question: what’s the easiest way to test it?

**Comment by gnidorah** [comment]
@loewenheim 
`nix-env -iA way-cooler -f https://github.com/nixos/nixpkgs/archive/143e4fb431226a25c0c99923a2a5788b35dad6b2.tar.gz`

**Comment by loewenheim** [comment]
Thank you, that did the trick! The installation worked.

**Comment by gnidorah** [comment]
@loewenheim Offtopic, but I've learnt more cool way to do that: `nix-review pr 53220` (nix-review should be in packages) :smile:
