### ISSUE TITLE
cantarell-fonts build broken (GNOME 3 dependency)

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#50855]
## Issue description

On the `release-18.09` branch, the `cantarell-fonts` package fails to build with the following errors:

```
building
build flags: -j4 -l4
[1/1] Generating org.gnome.cantarell.metainfo.xml_merge with a custom command.
FAILED: appstream/org.gnome.cantarell.metainfo.xml
/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/bin/python3.6m /nix/store/0wrv6cips8sfzk04ca67w6vlsgy4lb3z-meson-0.46.1/bin/meson --internal msgfmthelper ../appstream/org.gnome.cantarell.metainfo.xml.in appstream/org.gnome.cantarell.metainfo.xml xml ../appstream/./
msgfmt: cannot locate ITS rules for ../appstream/org.gnome.cantarell.metainfo.xml.in
ninja: build stopped: subcommand failed.
builder for '/nix/store/52vznnzqs7iz60w7a2wln0xg13w5nkhg-cantarell-fonts-0.100.drv' failed with exit code 1
error: build of '/nix/store/52vznnzqs7iz60w7a2wln0xg13w5nkhg-cantarell-fonts-0.100.drv' failed
```

### Steps to reproduce

Change the hash in `pkgs/data/fonts/cantarell-fonts/default.nix` and then:
`nix-build '<nixpkgs>' -A cantarell-fonts`

## Technical details

Hydra has a successful build of the `cantarell-fonts` package cached as of September 3rd (due to `cantarell-fonts` being a fixed-output derivation), but if you force it to build locally it will fail.

As far as I can tell, the build fails because the `GETTEXTDATADIRS` environment variable is not defined. Instead, there is a `GETTEXTDATADIRS_FOR_BUILD` variable defined (but it's not being used?).

If I add the following line to the `cantarell-fonts/default.nix` file it will build successfuly:
```
  preBuild = ''export GETTEXTDATADIRS="$GETTEXTDATADIRS_FOR_BUILD"'';
```

However, I'm pretty sure that this isn't the correct solution.

This seems related to #33524, #33458 and #40139.

cc @Ericson2314

**Comment by hedning** [comment]
I'm guessing `role_post` actually shouldn't be used here as `gettext` doesn't have a concept of `GETTEXTDATADIRS_FOR_BUILD`, as opposed to eg. `CC_FOR_BUILD` which is used for cross compilation: 
https://github.com/NixOS/nixpkgs/blob/03dc6471c12a0ef505ad8136ce07d47b332f2def/pkgs/development/libraries/gettext/gettext-setup-hook.sh#L5

Just like it's not used in gobject-introspection's setup-hook as there's no concept of `XDG_DATA_DIRS_FOR_BUILD`.
https://github.com/NixOS/nixpkgs/blob/03dc6471c12a0ef505ad8136ce07d47b332f2def/pkgs/development/libraries/gobject-introspection/setup-hook.sh#L4

Not sure why we're hitting this only with cantarell though.

**Comment by jtojnar** [comment]
Weird, `nautilus-sendto` has somehow the variable set:

```
  preConfigure = ''
    env | grep GETTEXTDATADIRS
  '';
```

**Comment by hedning** [comment]
Ok. `nautilus-sendto` has both variants defined, but `cantarell-fonts` has only the `_FOR_BUILD` variant. The plain variant is only added if `buildInputs` is defined (adding eg. glib to `buildInputs` fixes the build).

**Comment by hedning** [comment]
Hmm, so gobject-introspection's envHook might actually cause problems for cross compilation, at least when combined with `wrapGAppsHook`, as stuff in `nativeBuildInput` could end up in the wrappers.

While gettext should probably be safe, as that's all done at compile time?

**Comment by jtojnar** [comment]
I think it should not matter for cross-compilation, as `/share` typically contains architecture-independent data. There might be some problem with over-detecting dependencies https://github.com/NixOS/nixpkgs/issues/32293
We might fix it with https://github.com/NixOS/nixpkgs/issues/32790

**Comment by philiptaron** [comment]
This is definitely fixed.
