### ISSUE TITLE
docbook-xml 4.1.2 doesn't cross compile

### ISSUE THREAD

**Issue by eburimu** [NixOS/nixpkgs#50865]
## Issue description

```
 output '/nix/store/n3xkpg3mylsb279g8gvv2hb0gnh6da7v-docbook-xml-4.1.2-armv6l-unknown-linux-gnueabihf' is not allowed to refer to the following paths:
   /nix/store/mh8i211mffjaz3jparb0hagl8d4a3qjn-hook
```

Hello @matthewbauer, I have no idea how to solve this, any ideas? 
Im on nixpkgs/staging, thnx.

**Comment by eburimu** [comment]
```
  6   nativeBuildInputs = [ unzip gnused findXMLCatalogs ];
  7   # propagatedNativeBuildInputs = [ findXMLCatalogs ];            
```

The above seems to fix the problem but not sure about propagated stuff. Also, gnused is missing in deps.

**Comment by matthewbauer** [comment]
- gnused will alway be included in stdenv.mkDerivation calls. This is part of the common-path all stdenv's share: https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/common-path.nix.
- The propagatedNativeBuildInputs thing looks like a bug in #49417. We shouldn't disallow propagated things as they will end up in /nix-support/propagated-native-build-inputs.
