### ISSUE TITLE
autoconf 2.69 doesn't cross compile

### ISSUE THREAD

**Issue by eburimu** [NixOS/nixpkgs#50872]
## Issue description

```
 output '/nix/store/x98hmdqxhskcj4r7py8dpx5i92bjply3-autoconf-2.69-armv6l-unknown-linux-gnueabihf' is not allowed to refer to the following paths:
       /nix/store/3slr7z6s497z36x3dlkh6g8l7d8jkn6x-perl-5.28.0
       /nix/store/gbf0s6x2sg753k2km8p55nwfy53dx0s1-gnum4-1.4.18
```
Hello @matthewbauer ,

Thnx for the docbook quick fix, much appreciated. Last night I had the above.

Current drv is below:
```
  nativeBuildInputs = [ m4 perl ];
  buildInputs = [ m4 ];
```

Adding
```
 depsBuildBuild = [ buildPackages.perl buildPackages.m4 ];
```

seems to fix it. Im a little bit confused about nativeBuildInputs at this very moment, Why does it leak just like this? I hope this is particular to autoconf.

Maybe it is supposed to be propagatedNativeBuildInputs = [ m4 perl ]; ?

best.

**Comment by vcunat** [comment]
Side note: I find it likely that you do _not_ want to cross-compile autoconf, i.e. that some your derivation has it (transitively) in *non*-native input by mistake.

**Comment by eburimu** [comment]
Hey @vcunat, 

Thats very likely, it might not work on the target when I move it.
How do you compare the ramifications of depsBuildBuild and propagatedNativeBuildInputs in this case, any insights?
