### ISSUE TITLE
commit access

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#50889]
Hi @edolstra, can I get a commit access to the nixpkgs repo please? I have been using nix for 2.5 years and have around 200 commits to nixpkgs and few minor commits to nix. I'm looking to help with some of the PR pileup. I can't promise a very high bandwidth though. I also also not looking to do work for NixOS modules, only packages. Sorry for asking here, I don't use IRC.

**Comment by coretemp** [comment]
I don't see why it should take 5 days to process something like this.

**Comment by globin** [comment]
cc @domenkozar looks fine to me

@coretemp it probably hadn't been noticed by anyone who can give commit access so far. Also I'd prefer if you kept a little more less passive aggressive tone, I very much believe everyone working on Nix/NixOS/nixpkgs is doing so in good faith and with a lot of effort and spending a lot of their free time for it.

**Comment by domenkozar** [comment]
Granted. Welcome to the team and use your access wisely :)

**Comment by domenkozar** [comment]
@coretemp I'm giving you last warning for these comments before banning you on github. Ask yourself a simple question: `Is this comment going to be useful to anyone? Is it constructive?`. If you don't know how to answer it before you comment, I'm afraid we aren't the right community for you.

**Comment by veprbl** [comment]
@domenkozar Thank you! Will do my best.

@coretemp Thank you for your interest in my issue. I think there can be few reasons that are not obvious from the outside. There are some basic reasons, that were already mentioned, like lack of people's attention and time. There are also some downsides to making snap decisions when one have to take responsibility for consequences. This can be really frustrating for both users and maintainers. Overall, if you think something doesn't go the right way, a one effective way to resolve an issue is to put more work into it and exercise more patience. Though, complaining also works sometimes :)
