### ISSUE TITLE
Document meson setup hook in nixpkgs manual

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#50917]
Document existence / basic usage of these meson setup-hook options in the nixpkgs manual:

- mesonConfigurePhase
- mesonFlags
- dontUseMesonConfigure
- mesonCheckPhase
- dontUseMesonCheck

**Comment by jtojnar** [comment]
`mesonCheckPhase` is not there any more: https://github.com/NixOS/nixpkgs/pull/50527

**Comment by matthewbauer** [comment]
I added a short bit on meson recently:

https://hydra.nixos.org/build/84573227/download/1/nixpkgs/manual.html#ssec-setup-hooks

That whole section is still pretty rough though. Ideally we would have every setup hook documented here.
