### ISSUE TITLE
i3status needs a default configuration file

### ISSUE THREAD

**Issue by pharpend** [NixOS/nixpkgs#5093]
To reproduce:

1.  Install `i3status` by adding it to `environment.SystemPackages`.
2.  Run the command `i3status`.
3.  Observe this error:

    ```
    Unable to find the configuration file (looked at ~/.i3status.conf, $XDG_CONFIG_HOME/i3status/config, /etc/i3status.conf and $XDG_CONFIG_DIRS/i3status/config)
    ```

**Comment by anderspapitto** [comment]
Just hit this as well. The file exists, however i3status should be looking in ${i3status}/etc/i3status.conf, rather than /etc/i3status.conf as it currently does.
```
[anders@gurney:~]$ find / -name i3status.conf 2>/dev/null
/nix/store/0kfsm0p69280xs16kzg2jz9671n0rilp-i3status-2.8/etc/i3status.conf
```

**Comment by anderspapitto** [comment]
looking at the i3status codebase, it may be enough to set $SYSCONFDIR while compiling, though I'm not confident enough to implement that. See search result here

https://github.com/mloskot/i3status/search?utf8=✓&q=/etc/i3status

**Comment by BernardNotarianni** [comment]
Hi @anderspapitto,

I am newbie too with Nixos, but its look like we could try modifying the [installFlags](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/i3/status.nix#L15) used for building i3status.

Might be a good first step into contributing to NixOs :smile:

**Comment by BernardNotarianni** [comment]
After playing few days with Nixos I think I will not further investigage on this issue. I have the feeling the philosophy of the OS is to put the less possible in `/etc`.

However, after installing the package as user with `nix-env -i i3status` the file is available in `~/.nix-profile/etc`, hence we can either symlink it from here or copy it for customisation as suggested by @domenkozar.

**Comment by wmertens** [comment]
Does the default config file make sense in most cases? In that case you could patch i3status to look in `$out/etc` with something like `sed -i s: /etc/i3: $out/etc/i3:`

Since this is an old issue with behavior as more or less expected, I am closing this but feel free to reopen or create a PR :-)


On phone, sorry for brevity…
