### ISSUE TITLE
Add sqlite-web

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#50949]
sqlite-web is a nice quick web interface for sqlite, and it would be great if it was a `nix-shell` away.

It's a Python package, see https://github.com/coleifer/sqlite-web

/cc @costrouc

**Comment by costrouc** [comment]
Added a PR. I tried out `sqlite-web` and enjoyed using it on some of the sqlite databases that I had. I usually use `sqlitebrowser` but for remote machines I can see this being helpful.
