### ISSUE TITLE
discourse: Activating account

### ISSUE THREAD

**Issue by geopap12** [NixOS/nixpkgs#50946]
Hey guys, when activating a new account on discourse nixos, the banner is too big to click onto the activate account button, just thought I should let you know.

**Comment by FRidh** [comment]
cc @zimbatm

**Comment by zimbatm** [comment]
@geopap12 thanks for the report. Do you mind attaching a screenshot so I can see the issue?

**Comment by zimbatm** [comment]
I reduced the logo size a bit. A definitive fix has also been submitted upstream and in time will reach our instance: https://github.com/discourse/discourse/pull/6659

**Comment by 7c6f434c** [comment]
Thanks a lot for theme fix; now it works perfectly in the no-scripts mode..
