### ISSUE TITLE
Cassandra does not connect to service

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#50954]
## Issue description

I installed the cassandra service and the command line shell, but I can't connect to the service with the shell.

### Steps to reproduce

Set `services.cassandra.enable = true;` in your config. Then do:
```
$ nixos-rebuild switch
[...]
$ nix-env -iA nixos.cassandra
[...]
$ cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
```

To see the output of `strace cqlsh`:
https://paste.pound-python.org/show/caIloaMHt0Na6VA6asvY/

To see the output of `journalctl -u cassandra`:
https://paste.pound-python.org/show/KEibuPSbBBtXRlQZa5K8/

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.82, NixOS, 18.09.1399.51076ed20c5 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"musnix, nixos-18.09.1399.51076ed20c5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Config: https://gitlab.com/turion/enigmanix

**Comment by turion** [comment]
`ss -tlp`: https://paste.pound-python.org/show/s25u63xaeFMOP3yMe4hE/

**Comment by turion** [comment]
It seems I can work around this by adding:
```
    extraConfig = {
      start_native_transport = true;
    };
```

**Comment by turion** [comment]
Should this simply be added to the cassandra default options? (And removed from https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/cassandra.nix?)

**Comment by thoughtpolice** [comment]
Yes, this seems like an obvious oversight. Please submit a PR if you're willing to, thanks!
