### ISSUE TITLE
Impure GNU specific sed usage

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#50952]
## Issue description
For example `pkgs/build-support/fetchgit/nix-prefetch-git` contains the GNU extension of POSIX to use `+` as "one or more" of the preceding. 

Since not everyone has a working memory of POSIX, allow me to demonstrate: 

`echo a | sed --posix 's|[a]\+||'`
returns 
`a` instead of empty result (removing --posix would return an empty result). 

I don't mind using gnused, but I do mind such non portable usage patterns. 

The goal of this message is to align on what implementation of sed we support when the source file does not explicitly mention `gnused`. 

In particular, we should qualify all usages that are not compatible with POSIX to be bugs in any of the repositories under the NixOS organisation.

**Comment by Mic92** [comment]
On which platform do we use a non-gnused in nixpkgs?

**Comment by Mic92** [comment]
We depend on a lot bash-features in our stdenv infrastructure, that are non-posix.
It makes our code more robust, faster and maintainable I don't think we should drop that. I don't see how POSIX would provide us significant benefit in this area given that those tools are more portable then nix itself.

**Comment by matthewbauer** [comment]
sed should be an alias for gnused. But that is something that we should probably specify more specifically. I think the only times you have to worry about non-GNU tools is:

- In the unpack-bootstrap-tools.sh script
- Bootstrapping when using the native stdenv
