### ISSUE TITLE
updateScript: always pass in meta.position as first argument

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#50984]
## Issue description

What do you think of always passing in certain arguments to update scripts? I think passing `meta.position` is very helpful. Note I did this in https://github.com/NixOS/nixpkgs/pull/50983 in the `updateScript` itself, but I think it would be better to implement it in `update.nix`. It's trivial to implement (also in #50977), but it may break other update scripts.

**Comment by FRidh** [comment]
cc @matthewbauer @jtojnar

**Comment by FRidh** [comment]
No feedback, closing.

**Comment by jtojnar** [comment]
Personally, I do not need this but if someone finds this useful, we could always pass it in an environment variable.

**Comment by jtojnar** [comment]
We might implement it using features from https://github.com/NixOS/nixpkgs/pull/59372
