### ISSUE TITLE
Electron 3.0.5 crashes out with GLib-GIO-ERROR when launching open file dialog.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#50985]
## Issue description

Electron 3.0.5 from latest nixpkgs bombs out with the following error when the open file dialog is attempted to be displayed from within an Electron app:

`(electron:28153): GLib-GIO-ERROR **: 15:06:08.283: No GSettings schemas are installed on the system`

Previously with the 1.8.2 version this did not occur.

### Steps to reproduce

In my case I'm using a shell.nix file triggered from direnv to pull Electron onto my path for a particular shell session. An Electron application which uses the `showOpenDialog` function to trigger the open file dialog (I assume any dialog also triggers this) would be needed, as the Electron binary itself will start fine and load the web content with no problem.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.03.133295.c56ede78a08 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(sean): `""`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by jtojnar** [comment]
Electron now uses GTK3, which requires `${gtk3}/share/gsettings-schemas/${gtk3.name}` and `${gsettings-desktop-schemas}/share/gsettings-schemas/${gnome3.gsettings-desktop-schemas.name}` in `XDG_DATA_DIRS`. Adding `wrapGAppsHook` to `nativeBuildInputs` will do that for you.

**Comment by seanparsons** [comment]
@jtojnar That doesn't appear to be enough, I even tried adding it to `buildInputs` (replacing `makeWrapper`) and it still breaks.

**Comment by jtojnar** [comment]
Could you share the expression you have so far?

**Comment by seanparsons** [comment]
@jtojnar I could, but it's just the one in nixpkgs master with the change you suggested.

**Comment by seanparsons** [comment]
@jtojnar Here's the diff:
```
diff --git a/pkgs/development/tools/electron/default.nix b/pkgs/development/tools/electron/default.nix
index 8d0f85e2484..aa4f5e2b2c5 100644
--- a/pkgs/development/tools/electron/default.nix
+++ b/pkgs/development/tools/electron/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, libXScrnSaver, makeWrapper, fetchurl, unzip, atomEnv, gtk2, at-spi2-atk }:
+{ stdenv, libXScrnSaver, makeWrapper, wrapGAppsHook, fetchurl, unzip, atomEnv, gtk2, at-spi2-atk }:
 
 let
   version = "3.0.5";
@@ -36,7 +36,9 @@ let
       };
     }.${stdenv.hostPlatform.system} or throwSystem;
 
-    buildInputs = [ unzip makeWrapper ];
+    buildInputs = [ unzip wrapGAppsHook ];
+
+    nativeBuildInputs = [ wrapGAppsHook ];
 
     buildCommand = ''
       mkdir -p $out/lib/electron $out/bin
```

**Comment by jtojnar** [comment]
I suspect that is because the electron binary is in lib, while `wrapGAppsHook` [only searches](https://github.com/NixOS/nixpkgs/blob/aad3176fc3764be2b48a4bbf7feb31f10ad0eec6/pkgs/build-support/setup-hooks/wrap-gapps-hook.sh#L38-L49) `bin` and `libexec`. Try adding

```diff
--- a/pkgs/development/tools/electron/default.nix
+++ b/pkgs/development/tools/electron/default.nix
@@ -38,6 +38,8 @@
 
     buildInputs = [ unzip makeWrapper ];
 
+    dontWrapGApps = true; # electron is in lib, we need to wrap it manually
+
     buildCommand = ''
       mkdir -p $out/lib/electron $out/bin
       unzip -d $out/lib/electron $src
@@ -51,7 +53,8 @@
         $out/lib/electron/electron
 
       wrapProgram $out/lib/electron/electron \
-        --prefix LD_PRELOAD : ${stdenv.lib.makeLibraryPath [ libXScrnSaver ]}/libXss.so.1
+        --prefix LD_PRELOAD : ${stdenv.lib.makeLibraryPath [ libXScrnSaver ]}/libXss.so.1 \
+        "''${gappsWrapperArgs[@]}"
     '';
   };
 
```

**Comment by svalaskevicius** [comment]
I get similar for the save dialog: `(electron:6365): GLib-GIO-ERROR **: 18:15:01.693: Settings schema 'org.gtk.Settings.FileChooser' is not installed`

**Comment by jtojnar** [comment]
Yes, it uses the same file chooser dialogue. It needs to be fixed as pointed out above.

**Comment by svalaskevicius** [comment]
I've tried it to no effect. For some reason the generated wrapper does not include gtk paths

**Comment by svalaskevicius** [comment]
worked! will create a PR so others don't need to figure this out again :)

**Comment by worldofpeace** [comment]
I believe this is fixed for all versions of electron.
