### ISSUE TITLE
[ATI] X11 broken: display sleeps and won't wake

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#5101]
When my boot process reaches the starting-X11 phase, both my monitors go to sleep and won't wake up.

In my dmesg output I see many copies of this message:

    [  373.284719] [drm:cypress_dpm_set_power_state] *ERROR* rv770_restrict_performance_levels_before_switch failed

This happens as early as https://github.com/NixOS/nixpkgs/commit/2995072b53499db9fdf8e3c1c63d9412e58b76db and as recently as https://github.com/NixOS/nixpkgs/commit/acefc2220964f0b4cd94dda0fa852c3bdef30754.  I think it was working fine when I rebuild at https://github.com/NixOS/nixpkgs/commit/4b78eff026bae615423310e8b2fdeae451a1a23f, but I'm not 100% confident in my archaeology.

My graphics card is this one: http://www.newegg.com/Product/Product.aspx?Item=N82E16814129261 .  From lspci:

    01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series]

Unfortunately I might not have time to investigate this for a while, but if anyone has ideas I can try them.

**Comment by domenkozar** [comment]
Is this still an issue?

**Comment by falsifian** [comment]
Just enabled X11 again and everything works. Thanks for poking me :-)

Small configuration difference: I'm using only one monitor now. I'll re-open if I observe the problem with two.
