### ISSUE TITLE
plasma-browser-integration does not work with Firefox

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#51020]
## Issue description

`plasma-browser-integration` doesn't work with Firefox

### Steps to reproduce

1. Install `plasma-browser-integration`

2. Install Firefox

3. Install the plasma browser integration addon for Firefox

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 19.03pre159472.80738ed9dc0 (Koi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixpkgs-19.03pre159472.80738ed9dc0"`
 - channels(pasquale): `"nixpkgs-19.03pre153701.46651b82b87"`
 - nixpkgs: `/home/pasquale/.nix-defexpr/channels/nixpkgs`

**Comment by sib-null** [comment]
I'm running into the same problem.

Even when I manually launch plasma-browser-integration-host from the command line, the integration still does not work.

@bkchr , can you take a look at this?

**Comment by bkchr** [comment]
Hey, do you have `nixpkgs.config.firefox.enablePlasmaBrowserIntegration = true;` in your nixos config?
For me that is working and I'm using the Firefox integration without any problems.

**Comment by silverhook** [comment]
@bkchr, I did not know of that option, but even after I added it, it didn’t help.

**Comment by bkchr** [comment]
@silverhook Do you have the config option set, `plasma-browser-integration` in systemPackages and the firefox addon installed?
For me it works.

**Comment by sib-null** [comment]
@bkchr, I added the config option, the package, and the firefox addon, but still the same. Although I am using `firefox-devedition-bin` via `home-manager`. Does it has to be installed via configuration.nix?

**Comment by bkchr** [comment]
@sib-null I assume yes. Can you say me on which channel you are?

**Comment by silverhook** [comment]
I’m on
```
nixos https://nixos.org/channels/nixos-18.09
```

and use the following relevant parts in `configuration.nix`:

```nix
{
  nixpkgs.config.firefox.enablePlasmaBrowserIntegration = true;
  environment.systemPackages = with pkgs;
  [ 
    xdg-desktop-portal-kde
    plasma-browser-integration
    firefox-bin
  ];
}
```

**Comment by bkchr** [comment]
Why is the portal important? For what are you using it?
https://github.com/bkchr/nixos-config/blob/master/system-with-gui-configuration.nix this is my configuration.
Maybe you need to use `firefox` and not `firefox-bin`. I think the `firefox` derivation is doing more than `firefox-bin`, aka wrapping some further stuff.

**Comment by silverhook** [comment]
AFAIK the `xdg-desktop-portal-kde` is needed for open/save file dialogue. I don’t know if it’s already pulled in as a dependency or not.

Changing from `firefox-bin` to `firefox` did not seem to change much.

**Comment by silverhook** [comment]
AFAIK the `xdg-desktop-portal-kde` is needed for open/save file dialogue. I don’t know if it’s already pulled in as a dependency or not.

Changing from `firefox-bin` to `firefox` seems to enable the basic integration, yes. Thanks :)

**Comment by sib-null** [comment]
> @sib-null I assume yes. Can you say me on which channel you are?

@bkchr, I am using the `unstable` channel, which currently unfortunately doesn't build certain KDE apps (#53391) that I have specified in my `home-manager` configuration along with `firefox-devedition-bin`, so I'm just waiting it out before trying out which firefox package works with `plasma-browser-integration`.

**Comment by bkchr** [comment]
I think you can not use the `*-bin` versions, as they do not wrap the required stuff.

**Comment by pasqui23** [comment]
No,adding   `nixpkgs.config.firefox.enablePlasmaBrowserIntegration = true;` didn't solve the problem

**Comment by pasqui23** [comment]
And now it does
