### ISSUE TITLE
chmod cannot operate on dangling symlink

### ISSUE THREAD

**Issue by lightdiscord** [NixOS/nixpkgs#51025]
## Issue description

In the [Creating a NixOS live CD](https://nixos.wiki/wiki/Creating_a_NixOS_live_CD) wiki page we recommend importing [<nixpkgs/nixos/modules/installer/cd-dvd/channel.nix>](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/channel.nix) to get an initial copy of the channels. However, since yesterday *(I only noticed it yesterday)* when this import is added, I have an error `"chmod: cannot operate on dangling symlink"` preventing me from building my derivation (It works without the import).

I think I've identified the line causing the error.
https://github.com/NixOS/nixpkgs/blob/6c74e752280330afcdfbf400dc98c551d77bae50/nixos/modules/installer/cd-dvd/channel.nix#L20

### Steps to reproduce

Follow the guide, and make sure you have added the import.
*I had managed to reproduce the issue on a VPS with the latest version of the channels.*

## Technical details

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.2, NixOS, 19.03pre159472.80738ed9dc0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre159472.80738ed9dc0, nixpkgs-19.03pre159739.3ae0407d3c9"`
 - channels(arnaud): `"nixos-19.03pre159472.80738ed9dc0, nixpkgs-19.03pre159739.3ae0407d3c9"`
 - nixpkgs: `/home/arnaud/.nix-defexpr/channels/nixpkgs`
```

**Comment by matthewbauer** [comment]
Can you look at the NIX_PATH and verify none of paths are broken symlinks?

**Comment by c0bw3b** [comment]
I'm hitting this too on a freshly booted VBox OVA of nixos-unstable when I try my first nixos-rebuild.
Nothing special in my config, just the default `configuration.nix` of the demo VM + some keymap/locale/xserver resolution settings.

```shell
# nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 19.03pre159818.bac76e8a9ef (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

# nixos-rebuild boot
building Nix...
building the system configuration...
[...]
building '/nix/store/6jn1j9ryxrdvbi01nazakzx3s8yj5a8x-set-environment.drv'...
building '/nix/store/w4lrzblw5q2g747lnpkirkf24ddh9dib-nixos-19.03pre159472.80738ed9dc0.drv'...
chmod: cannot operate on dangling symlink '/nix/store/fas87vgv43ryxnmkilrkm0bg963rs7kx-nixos-19.03pre159472.80738ed9dc0/nixos'
builder for '/nix/store/w4lrzblw5q2g747lnpkirkf24ddh9dib-nixos-19.03pre159472.80738ed9dc0.drv' failed with exit code 1
building '/nix/store/h90ghh3jar3ng6dh7r8ids7rkza9nkk3-etc-profile.drv'...
cannot build derivation '/nix/store/ayhky4w3hvsn118f0169rv1wdzi216fj-local-cmds.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pfz685ixkdx9phny0iv9m610xqnicnz2-stage-2-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lvmbmv94mh5sn4swnximvnh74b7n3z2h-nixos-system-nixos-19.03pre159472.80738ed9dc0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lvmbmv94mh5sn4swnximvnh74b7n3z2h-nixos-system-nixos-19.03pre159472.80738ed9dc0.drv' failed

# echo $NIX_PATH
/root/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

All paths in my NIX_PATH points to an existing directory.

**Comment by matthewbauer** [comment]
We might be able to avoid this with:

```
chmod -R u+w $out/nixos || true
```

But it makes me wonder if the Git repo has a dangling symlink somewhere?

**Comment by matthewbauer** [comment]
Could you try:

```
symlinks -r /nix/var/nix/profiles/per-user/root/channels/nixos
```

?

**Comment by c0bw3b** [comment]
Sure. Nothing found:
```shell
[root@nixos:~]# symlinks -r /nix/var/nix/profiles/per-user/root/channels/nixos
[root@nixos:~]#
```

**Comment by c0bw3b** [comment]
I copied `virtualbox-demo.nix` and other imported .nix under my /etc/nixos and commented the `import ../installer/cd-dvd/channel.nix` 
--> rebuilds successfully

Uncommenting it and replacing the chmod with `chmod -R u+w $out/nixos || true` 
--> rebuild failing again with the error message `cannot operate on dangling symlink`

**Comment by dtzWill** [comment]
Maybe tools changed? Recent coreutils changed some behavior re:links, but just a possibility.  Here's the NEWS file in case it helps: https://github.com/coreutils/coreutils/blob/master/NEWS .

Dunno where that chmod comes from, maybe BusyBox...

**Comment by lheckemann** [comment]
May be related to @zimbatm's changes wrt channels and stuff? Just a guess though.

**Comment by LightDiscord** [comment]
I managed to rollback and use coreutils 8.29 and still have the "cannot operate on dangling symlink" error.

**Comment by LightDiscord** [comment]
By modifying the commands launched for the `channelSources` and testing two or three things, I realized that the `pkgs.path` (or `cleanSource pkgs.path`) could not be visited by the builder, and when I used `readlink -f` on it the script would stop (with no error).

```nix
channelSources = pkgs.runCommand "nixos-${config.system.nixos.version}"
	{ }
	''
		mkdir -p $out

		echo ------
		echo "Get the nixpkgs path"
		echo ${nixpkgs}

		echo "List files"
		ls ${nixpkgs}
		# It does not give me the content of the folder, as any other package would do.

		# Example
		echo "List file in any-other-package"
		ls ${pkgs.coreutils}

		echo "Follow symlink"
		readlink -f ${nixpkgs}
		echo ------
	'';
```

Then, when I look after the build (outside the builder) the symlink points me to the right place. I suppose that the error comes from the fact that the symlink does not yet point to anything during the build.

**Comment by zimbatm** [comment]
> May be related to @zimbatm's changes wrt channels and stuff? Just a guess though.

It touches the same files but none of my changes got in

**Comment by Shados** [comment]
@c0bw3b FWIW `|| true` is not sufficient to suppress the error, for some reason. Commenting out the `chmod` line entirely allows the build to proceed for me...

**Comment by matthewbauer** [comment]
Can someone try out #52594 and confirm this fixes their issue? Thanks

**Comment by c0bw3b** [comment]
I'll be able to test in a week after some holidays, if no one else test it before

**Comment by lightdiscord** [comment]
@matthewbauer I still have the issue with your merged commit. Should we reopen the issue ?

**Comment by pbogdan** [comment]
I've been seeing this issue as well and bisected it down to changes in 5f894a67f565129ac683434c3040ba85c2df3750, and indeed reverting that commit fixes the issue for me. Here's a small example I used to bisect this:

```
with import ./. {};
let nixpkgs = lib.cleanSource (import <nixpkgs/nixos> {}).pkgs.path;
in runCommandNoCC "test"  {} ''
  readlink -e ${nixpkgs.outPath}
  echo > $out
''
```

which was invoked with:

```
$ nix-build run.nix -I nixpkgs=$PWD/nixpkgs-symlink
```

from within my local checkout, where `$PWD/nixpkgs-symlinks` is a symlink pointing to said checkout.

The example does work as expected if I change:

```
lib.cleanSource (import <nixpkgs/nixos> {}).pkgs.path
```

to

```
lib.cleanSource (import <nixpkgs> {}).pkgs.path
```

It also works fine when `<nixpkgs>` is pointed to a directory directly without any symlinks. Otherwise it seems just the symlink is available within the build environment and it can't be dereferenced at build time (assuming sandboxing is on..).

Unfortunately I don't quite understand what the commit in question is doing exactly, what might be causing this difference in behaviour and whether that's expected or not.

/cc @roberth who authored the changes

**Comment by roberth** [comment]
That commit makes NixOS import Nixpkgs via `pkg/top-level/default.nix` instead of indirectly via `pkgs/top-level/impure.nix`, which makes sense because suppose new impurities are added to `impure.nix` they will not affect NixOS.

The reason why it fails becomes more visible when comparing the paths:

```
nix-repl> <nixpkgs>
/home/user/tmp/nixpkgs-51025/nixpkgs-symlink

nix-repl> (import <nixpkgs/nixos> {}).pkgs.path
/home/user/tmp/nixpkgs-51025/nixpkgs-symlink

nix-repl> (import <nixpkgs> {}).pkgs.path
/home/user/nixpkgs
```

Path is defined in `all-packages.nix` as `path = ../..;`, which clearly does not resolve the symlink by itself.
`import` does seem to [resolve symlinks](https://github.com/NixOS/nix/blob/6024dc1d97212130c19d3ff5ce6b1d102837eee6/src/libexpr/primops.cc#L92,L101).
[Guaranteed?](https://github.com/NixOS/nix/blob/875cd9da2b20a7228dd337aa007ae11ef02a220a/src/libexpr/eval.hh#L208) [Probably not](https://github.com/NixOS/nix/blob/c7bf1cdb4e98dcd845945374de97c3611401bc52/src/libexpr/eval.cc#L1638), [but maybe](https://github.com/NixOS/nix/blob/c7bf1cdb4e98dcd845945374de97c3611401bc52/src/libexpr/eval.cc#L346)

It seems that only the last path element gets resolved, which in the case of `../../..` is the symlink, but in case of `../../../pkgs/top-level/default.nix` it isn't.

@edolstra do you think that this is a behavior that should change? If not, perhaps we should have a builtin to explicitly canonicalize paths, in this case the `../../..` part of `../../../pkgs/top-level/default.nix`

**Comment by jokogr** [comment]
@roberth so what would be the proper way to import a file from `nixpkgs` after 5f894a6, e.g.

```
  imports = [
    <nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-base.nix>
  ];
```

**Comment by roberth** [comment]
@jokogr You should not have to change anything.

This seems to be a Nix problem.
 - Nix will copy dangling symlinks into the store instead of following them, issue: https://github.com/NixOS/nix/issues/1232
 - Surprising canonicalization behavior in evaluation masked this problem before 5f894a6

**Comment by Ravi9562** [comment]
Hi I am getting below error
"
 chmod 777 "D:\cygwin64\bin\python"
chmod: cannot operate on dangling symlink 'D:\cygwin64\bin\python'
"

Could you please let me know how can I clear this?

**Comment by roberth** [comment]
@Ravi9562 it looks like you are using Cygwin and not Nix. Nix (not "*nix", not UNIX) is an alternative package manager that is not available in the Cygwin package list. Unless you have consciously decided to use the Nix package manager (in which case I apologize for the lengthy answer), you should probably contact Cygwin people if this persists. That said, you'll have to replace the symlink or create the file that it points to. If you need help with the basics of UNIX commands, this is not the right place to ask; ask on stackoverflow.com instead.

**Comment by Ravi9562** [comment]
@roberth Thanks for your feedback. Will check with cygwin people
