### ISSUE TITLE
ghcHEAD seems to depend on ghc802 which is no longer in nixpkgs

### ISSUE THREAD

**Issue by toonn** [NixOS/nixpkgs#51042]
## Issue description

[This line in configuration-ghc-head.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghc-head.nix#L43) refers to `ghc802` but there's no `8.0.2.nix` in [.../compilers/ghc](
https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/ghc). This makes `nix-env -iA nixpkgs.ghcEnv` fail with a message along the lines of ``missing attribute `ghc802` in /longhashpath/configuration-ghc-head.nix line:...``

### Steps to reproduce

I ran `nix-channel --update` then `nix-env -u --leq`, however when running `nix-env -iA nixpkgs.ghcHEAD` the build simply started so the problem didn't seem to show up.

**Comment by alyssais** [comment]
[Upstream bug](https://github.com/peti/jailbreak-cabal/issues/13) looks like it's been fixed, so we should be good to just revert d13f7c54e30b5eb9e90f226d2a947f66a0ce1b38, which introduced that old GHC reference.
