### ISSUE TITLE
Package update required: Teamviewer 13 -> Teamviewer 14

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#51059]
## Issue description
Teamviewer has *no* backwards compatibility between releases, which means that if I upgrade Teamviewer on one operating system (because of other incompatibilities, not because I want to) I also require an upgrade on NixOS. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.82, NixOS, 18.09.git.51076ed (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/2a858b3f76620eb07230067f919ebf941e680e9a
