### ISSUE TITLE
Threats from @domenkozar

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#51078]
## Issue description
Dear @edolstra, 

User @domenkozar  threatens to ban me with some silly reason, while in fact for the simple reason that *I* directed attention to the issue, we now have an additional committer (@veprbl (hooray!)). See his comment here: https://github.com/NixOS/nixpkgs/issues/50889#issuecomment-441685329.

User @domenkozar seems to have great difficulty with understanding the difference between personal criticism (which is what I am giving him right now) and project management criticism, which is what I gave in the above issue. Note that nobody gave a reasonable excuse as to why it should take 5 days to do what should be considered a simple administrative action with perhaps a minor discussion.

I have explained on various occasions that the reason there are so many PRs is because commit access is considered some kind of God given right while in reality the risk that something goes wrong is small in for example this case. Almost *nobody* has an interest in secretly rewriting the whole of nixpkgs as a secret night time hobby, but somehow this escapes most people, including you @edolstra. At no point have you written down any reasonable explanation for why you run the things the way you do.  

The age old "security argument" is neither reasonable, because whatever imaginary enemy you are thinking of would simply be able to plant a row-hammer attack that would look like an innocent patch. If security would be a top priority, then why is even ntpd configured "insane" (paraphrasing someone who said that with his changes it would now be "sane")? Fact of the matter is that NixOS *is* not secure in some perfect ideal world and it will likely *never* be, because that's *not* what it is designed for. NixOS is a slightly smaller kludge than most other operating systems; that is it. You should find happiness in that, but I kindly ask you to undermine the project with your wrong ideas. It's hard to always be right. Here, I am giving you a fairly simple argument as to why you are wrong.   

Since this is supposed to be an *inclusive* community, I feel very much excluded by having such people (like @domenkozar)  with the apparent power to ban people, @edolstra. It creates an atmosphere in which disagreement on issues is impossible.  

I have the impression that @domenkozar is somehow jealous in some way and seems to have a rather weak control over his emotions. In a company @domenkozar's behaviour would not be tolerated, which is likely why he started his own business. Please think about that next time you give someone the power to ban people.   

Finally, consider that I have many responsibilities and that nixpkgs mostly takes up time due to the drama that @domenkozar makes over little things. Also note that @domenkozar repeatedly seems to take offense to what people say. I was banned from the Discourse forum, because @domenkozar got emotional again. Nobody else got emotional; just he did. I am getting a negative vibe from him, if anything.

Perhaps he is under financial stress of some kind, which is a sad state to be in, but you should not have that effect the NixOS brand. Essentially you are saying "if you are someone who commits more than others, you can bully everyone away". 

I would consider it absolutely terrible to work with @domenkozar and I would *never* run any of his business tools, because he seems to explode for no reason at all. There is professional help for such issues; even if his tools would be the absolute best on the market, I would *still* not use them, because he is a liability (if I would use his service, all that would happen is that if someday he disagrees, he just pulls the plug; there is zero basis for trust). So, instead of him trying to make himself look like an absolute fool by threatening someone who did write some commits in the past week and certainly has been making useful comments in various threads, perhaps consider he should consider a little bit of personal growth?    

### Steps to reproduce
1. Mistake the ability to write a patch with actual leadership
2. "Trust" people that do not control their emotions

## Solution
Understand that project management skills are not equally distributed among developers. In particular the removal of ban rights if that is possible from @domenkozar and similar people in the future.

## Technical details
I think I have given enough details to show beyond doubt what needs fixing, and it is *not* me. 

## TR;DR; 

I escalated an issue by replying to it (this increases the number of comments, which in turn increased the probability that someone was looking at it), which has solved an issue and @domenkozar thinks it's a good idea to start threatening me. :roll_eyes:

**Comment by zimbatm** [comment]
It would go a long way if you could also admit your own failures from time to time @coretemp.

Please explain to me how this comment is not passive-aggressive: https://github.com/NixOS/nixpkgs/issues/50889#issuecomment-441582728

**Comment by Profpatsch** [comment]
+1 for banning @coretemp, thanks for bringing this up. (scnr)

**Comment by coretemp** [comment]
@zimbatm I am how the project is mismanaged and specifically the onboarding of new committers. I don't see how it is a failure to do so. What needs to happen is that that someone acts as a *leader*. 

@Profpatsch Based on what exactly? Did I offend you in some way and are you just as emotional as @domenkozar?

**Comment by Infinisil** [comment]
I'm with @coretemp here. Yes their comment was a bit passive-aggressive, but that's no reason to ban somebody. We probably all have had such silly hickups occasionally, maybe when we've had a bad day or are frustrated. As long as it doesn't happen all the time. I don't see any other evidence other than mentioned comment, which is a very low basis to judge someone. If @domenkozar has other reasons for banning then I'd like to hear those.

@coretemp You mentioned that you got banned from the Discourse forum, what was the reason for that? Do you have a link to the discussion that caused this?

**Comment by grahamc** [comment]
https://github.com/NixOS/nixpkgs/search?q=involves%3Acoretemp&type=Issues

**Comment by domenkozar** [comment]
I'm going to post this issue for posterity https://github.com/mozilla/sops/issues/394#issuecomment-438746610, could probably fine a dozen more but I'd rather have a nice evening :)

There's not much I have to say besides I'm going to go ahead with the ban, we're here to create a welcoming community.

**Comment by coretemp** [comment]
@zimbatm Even if it was passive-aggressive, which I don't think it is, there still is the minor inconvenience that there is no code of conduct in nixpkgs to begin with. 

So, the extremely aggressive behavior that @Profpatsch shows (+1 for banning me), should certainly be met with an immediate ban according to that logic. 

Banning me is not even on the table; @domenkozar had a random thought supported by *nobody*. I am just bringing out the attention to the fact that I do not believe @domenkozar to be fit for his responsibilities. People can disagree on that. Perhaps *you* think he is fit for that job, I just don't share that opinion. How hard is it to accept that fact? 

It's not like I am the *only* person who believes this to be the case. People "accept" it, because he is doing it for "free" (at the cost of damaging the NixOS brand). I think it's better if he would not contribute anything to the project to remove the drama, but even I am not proposing to ban him. 

You all claim to be so inclusive, but in reality you are everything but that. 

@Infinisil I think that discussion has been censored (one of the disadvantages of using Discourse).

@grahamc I would like to nominate you for the position of passive-aggressive winner of the day.  

Is the definition of passive aggressive to be all behavior that doesn't agree with @domenkozar? 

In that case, just rename the project to be @domenkozar's cabal or something like that and remove any suggestion that this project allows outside involvement.  

I understand; it's not nice to hear this, but most people make it *so* easy to shoot holes in almost everything that they say that even for a troll (which I am not), it would not be entertaining. It's really just annoying and draining my energy to learn that this great project is under the influence of such unfriendly people.

The trend I see is that all the actually aggressive people are those of you whose livelihood depends partially on nixpkgs. It feels like nixpkgs has been corrupted.

**Comment by coretemp** [comment]
@domenkozar You are pointing at *another* project. Pathetic.

**Comment by Profpatsch** [comment]
> @domenkozar had a random thought supported by _nobody_.

I have found a new nickname.


> Pathetic.

:)

**Comment by vcunat** [comment]
@coretemp: this isn't just about that single comment (which wasn't constructive).  You know, it's not really a problem to criticize or disagree, but you need to do it in a way that does _not_ involve attacking people around (like you showed e.g. in this thread).
