### ISSUE TITLE
NixOS 18.09 font rendering issue in KDE Plasma 5 panel

### ISSUE THREAD

**Issue by fusion809** [NixOS/nixpkgs#51088]
## Issue description
The first time I booted my NixOS 18.09 system I see this font rendering issue in the plasma panel:

![screenshot_20181127_075540](https://user-images.githubusercontent.com/4717341/49044537-db2c0700-f219-11e8-8dad-8446e9b96c00.png)

Note how several letters are hidden in the plasma panel task manager. This is a completely fresh NixOS 18.09 install.

### Steps to reproduce
With my configs, which are in: https://github.com/fusion809/NixOS/tree/0a832bac4f787f88a2df3a69550513adefe90bae, install NixOS, reboot, set your password in TTY2 (after pressing Ctrl-Alt-F2), login as fusion809, open an application and lo and behold, you should see this bug. 

## Technical details

```bash
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev
copying path '/nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.800.21293d2576a (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

(Neofetch output appearing in the above screenshot is deliberate, I'm hoping it proves helpful). 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
This issue spontaneously disappeared when I changed window title fonts. What is even stranger is that when I reverted the font back to what it was originally (Noto Sans 12pt) the issue remained gone.

**Comment by aanderse** [comment]
@fusion809 no more font problems since your last post? Good to close the issue?

**Comment by fusion809** [comment]
Well I haven't tried re-installing NixOS, and this issue only occurs on a fresh install, so no.
