### ISSUE TITLE
Bluetooth audio not working in GNOME

### ISSUE THREAD

**Issue by mat8913** [NixOS/nixpkgs#51099]
## Issue description

My bluetooth headphones wont connect in GNOME. The solution described in the [Arch wiki](https://wiki.archlinux.org/index.php/Talk:Bluetooth_headset#GDMs_pulseaudio_instance_captures_bluetooth_headset) works for me, but it would be nice to have a fix included in NixOS.

### Steps to reproduce

Attempt to connect to bluetooth headphones and play audio through them in GNOME.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.4, NixOS, 18.09.1420.5d4a1a3897e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1420.5d4a1a3897e"`
 - nixpkgs: `/home/matthew/.nix-defexpr`

**Comment by Shou** [comment]
Looks like this was fixed in https://github.com/NixOS/nixpkgs/pull/61746
