### ISSUE TITLE
cURL 7.62 in nixpkgs 18.09 broke sssd build

### ISSUE THREAD

**Issue by sgraf812** [NixOS/nixpkgs#51106]
## Issue description

The stable branch seems to have upgraded `curl` to 7.62. This includes a [known breaking change with `sssd`](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913403), where [the fix](https://github.com/SSSD/sssd/commit/1ee12b05570fcfb8e4190c9ec704c5563138344d) isn't yet included in any 1.16.* release AFAICT.

### Steps to reproduce

`nix-channel --update && nix-env -i sssd`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-39-generic, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(sgraf): `"nixos-18.09.1420.5d4a1a3897e, nixpkgs-19.03pre160446.206a1c00bae"`
 - nixpkgs: `/afs/info.uni-karlsruhe.de/user/sgraf/.nix-defexpr/channels/nixpkgs`

**Comment by vcunat** [comment]
Thanks.

**Comment by sgraf812** [comment]
Any estimate on when this hits `release-18.09`?

**Comment by vcunat** [comment]
@sgraf812: it **is** in all 18.09 channels; you may see the tag info: https://github.com/NixOS/nixpkgs-channels/commit/56aac496ffd2d37639a3ebb0dbcfc0e3a25cb1ef

**Comment by sgraf812** [comment]
Then I'm at a loss as to why my home-manager config doesn't seem to pick up the patch... I `nix-channel --update`d multiple times since the last week. Argh. Well, thank you.

**Comment by sgraf812** [comment]
I did some digging. Apparently, the derivation for the patch is built, but the resulting `duplicate-case-value.diff` in the store is empty. I see that [`fetchpatch` should error out on empty patch files](https://github.com/NixOS/nixpkgs/blob/e814fba3168703eed6e2b67200299ea40beca418/pkgs/build-support/fetchpatch/default.nix#L13), which makes this even more surprising.

**Comment by vcunat** [comment]
That's not the main point.  If the file is empty, its hash surely doesn't match.

**Comment by sgraf812** [comment]
I don't know why, but although the derivation for `duplicate-case-values.diff` was 'compiled', it didn't actually build the derivation. Doing so manually with `nix-store -r /nix/store/<hash>-duplicate-case-value.diff.drv` does write the otherwise non-existent (not empty, that was an oversight) diff file.

But even when I restart the build for `sssd`, it doesn't seem to apply the patch. Here's the .drv for sssd, it doesn't even mention 'patch' or 'diff': https://pastebin.com/wn9YrpR0.

**Comment by sgraf812** [comment]
Well, I don't know why, but the issue went away and I could build my home-manager generation just fine. This probably was some local wibble.
