### ISSUE TITLE
gnome3.mutter does not compile on i686-linux

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#51133]
I recently tried to install NixOS with gnome on a i686 machine, but ran into trouble when `mutter` would not build. The issue does not seem to exist on x86_64. I see the following errors in both `release-18.09` and `master`:

~~~
  GISCAN   Clutter-2.gir
/nix/store/919xbryjwccvhdw1rf7z44bzia42ymqp-gcc-7.3.0/lib/gcc/i686-unknown-linux-gnu/7.3.0/include/stddef.h:435: syntax error, unexpected identifier in '  __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));' at '__float128'

  GISCAN   ClutterX11-2.gir
/nix/store/919xbryjwccvhdw1rf7z44bzia42ymqp-gcc-7.3.0/lib/gcc/i686-unknown-linux-gnu/7.3.0/include/stddef.h:435: syntax error, unexpected identifier in '  __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));' at '__float128'
/nix/store/919xbryjwccvhdw1rf7z44bzia42ymqp-gcc-7.3.0/lib/gcc/i686-unknown-linux-gnu/7.3.0/include/stddef.h:435: syntax error, unexpected identifier in '  __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));' at '__float128'

  CC       compositor/meta-surface-actor-wayland.lo
core/window.c: In function 'find_monitor_by_winsys_id':
core/window.c:3783:38: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       if (logical_monitor->winsys_id == winsys_id)
                                      ^~
core/window.c: In function 'meta_window_move_resize_internal':
core/window.c:4016:32: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       if (old_output_winsys_id != window->monitor->winsys_id &&
                                ^~
~~~

**Comment by jtojnar** [comment]
I would say this is upstream issue.

**Comment by Ekleog** [comment]
@peti Has this been reported upstream?

**Comment by vvs-** [comment]
It does compile on Fedora 29. Could it be related to this difference in configure flags: `--enable-compile-warnings=maximum`? Here is the link to full spec file: https://src.fedoraproject.org/rpms/mutter/blob/f29/f/mutter.spec

**Comment by vvs-** [comment]
Now NixOS rebuild went fine with modified mutter expression as above. There were several of such warnings which are related to difference of types on 32-bit and 64-bit architectures. GDM and Gnome are now working fine too. I can't tell the difference between Fedora and NixOS now, except desktop wallpaper. :smile:

But it would be better if this change would be applied in stable channel.
