### ISSUE TITLE
aarch64 raspberry pi sha256 hashes do not match

### ISSUE THREAD

**Issue by joehealy** [NixOS/nixpkgs#51149]
## Issue description

The nixos image for raspberry pi (https://www.cs.helsinki.fi/u/tmtynkky/nixos-arm/installer/sd-image-aarch64-linux.img) available from https://www.cs.helsinki.fi/u/tmtynkky/nixos-arm/installer/ has the following hash:

$ sha256sum sd-image-aarch64-linux.img 
9f96a8541c5a21e80ff6ef4f640627068d17a23bd6cf1ecc6ed92ed634ed733e  sd-image-aarch64-linux.img

whilst the has listed in https://www.cs.helsinki.fi/u/tmtynkky/nixos-arm/installer/SHA256SUMS

is 25492de7aaff2fd4f41670e19b3a99b600a5a197af50e0ff55f71fb561ce98ab *sd-image-aarch64-linux.img

**Comment by samueldr** [comment]
cc @Dezgeg

**Comment by samueldr** [comment]
*Closing since we now have upstream sd_image building for aarch64 on Hydra.*
