### ISSUE TITLE
Mumble doesn't display anything

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#51196]
## Issue description
When mumble is started, the window is entirely grey. The same happens with both mumble and mumble_git.

cc maintainers @jgeerds @wkennington 
cc @umazalakain who also experienced this

### Steps to reproduce

`nix-shell -p mumble --run mumble`
`nix-shell -p mumble_git --run mumble`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 18.09.1436.a7fd4310c0c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1436.a7fd4310c0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lheckemann** [comment]
The non-git mumble also complains about OpenGL stuff:
`Plugins: Failed to load libmumble.so.1.2.19: Cannot load library /nix/store/9nck97sy499g5r5rvpdhppp0hpcv7hbf-mumble-1.2.19/lib/libmumble.so.1.2.19: (/nix/store/9nck97sy499g5r5rvpdhppp0hpcv7hbf-mumble-1.2.19/lib/libmumble.so.1.2.19: undefined symbol: glPopClientAttrib)`

but this doesn't seem to be related, 6370fa197f40060e592cafc792e8150b641a4e81 fixes this error message but not the blank window issue.

**Comment by davidak** [comment]
I have the same error.

![screenshot from 2018-12-01 09-24-11](https://user-images.githubusercontent.com/91113/49334171-3faae580-f5cf-11e8-8ab8-e7db0304a11a.png)

So i used the package from unstable channel that has 2 newer commits. I will backport them to fix it.

https://github.com/NixOS/nixpkgs/commits/994826f6512c43ae3f4691b64c283a61259d91d1/pkgs/applications/networking/mumble/default.nix

**Comment by lheckemann** [comment]
Hm, I have the same problem with nixos-unstable mumble though.

**Comment by Mic92** [comment]
Does it work for you with https://github.com/NixOS/nixpkgs/pull/51361 applied?

**Comment by lheckemann** [comment]
`nix build -f https://github.com/nixos/nixpkgs/archive/65b2552.tar.gz mumble && ./result/bin/mumble` has the same problem for me (65b2552 is the current HEAD of that PR)

**Comment by Mic92** [comment]
Is your opengl version in /run incompatible with the binary? I can start mumble on unstable with this.

**Comment by thefloweringash** [comment]
> The non-git mumble also complains about OpenGL stuff:
> 
> ```
> Plugins: Failed to load libmumble.so.1.2.19: Cannot load library /nix/store/9nck97sy499g5r5rvpdhppp0hpcv7hbf-mumble-1.2.19/lib/libmumble.so.1.2.19: (/nix/store/9nck97sy499g5r5rvpdhppp0hpcv7hbf-mumble-1.2.19/lib/libmumble.so.1.2.19: undefined symbol: glPopClientAttrib)
> ```
> but this doesn't seem to be related, [6370fa1](https://github.com/NixOS/nixpkgs/commit/6370fa197f40060e592cafc792e8150b641a4e81) fixes this error message but not the blank window issue.

I don't think is is an error that needs to be fixed. See: https://github.com/mumble-voip/mumble/issues/3293#issuecomment-355061249

**Comment by Mic92** [comment]
So strace might reveal where it blocks.

**Comment by lheckemann** [comment]
I'm very confused, it's spontaneously started working.

**Comment by lheckemann** [comment]
Seems to be fixed.
