### ISSUE TITLE
Remove perl dependency in activation scripts

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#51198]
## Issue description

Approximately 10 percent of a minimal nixos install is perl, perhaps we could remove this somehow.

Not critical, feel free to close the issue if this is not the right place for that.

### Steps to reproduce

Use a config like:
```
{ config, lib, ... }:
{
    imports = [
        <nixpkgs/nixos/modules/profiles/minimal.nix>
        <nixpkgs/nixos/modules/profiles/headless.nix>
        <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

    fileSystems."/" = {
      device = "/dev/disk/by-label/nixos";
      autoResize = true;
    };

    boot.growPartition = true;
    boot.loader.grub.device = "/dev/sda";
    boot.kernelParams = [ "console=ttyS0" "panic=1" "boot.panic_on_fail" ];
    boot.initrd.kernelModules = [ "virtio_scsi" ];
    boot.kernelModules = [ "virtio_pci" "virtio_net" ];

}

```

Run 

```
nixos-rebuild build -I nixos-config="./configuration.nix"
du -sch $(nix-store -qR ./result) | sort -h
```
And see the second largest dependency is perl:

```
...
56M     /nix/store/q9ajsngf2w3r10dg7b1148wzq1avp4gj-perl-5.28.0
70M     /nix/store/cs0lixjvndy2z4gby1nvmnzdd4jkmi02-linux-4.14.81
597M    total
```

```
[ac@black:~/src/minimal-nixos]$ nix why-depends ./result /nix/store/q9ajsngf2w3r10dg7b1148wzq1avp4gj-perl-5.28.0
/nix/store/zazd30c454axi23z00qr5q7y3rvzzvvd-nixos-system-nixos-18.09pre-git
╚═══activate: …ll -m 0755 -d /home../nix/store/q9ajsngf2w3r10dg7b1148wzq1avp4gj-perl-5.28.0/bin/perl -w \.  -I/…
    => /nix/store/q9ajsngf2w3r10dg7b1148wzq1avp4gj-perl-5.28.0
```

Looking further, the two uses of perl are 

/nix/store/1hkp2n6hz3ybf2rvkjkwrzgbjkrrakzl-update-users-groups.pl
and /nix/store/vn1xs9s2akf79y1pbya2qldydbf2b22m-setup-etc.pl .

So a few hundred lines of perl are taking up 10 percent of the base install.

**Comment by jtojnar** [comment]
Is it really an issue? See also https://github.com/NixOS/nixpkgs/pull/48378 for similar discussion.

**Comment by andrewchambers** [comment]
It affects provisioning and boot times of VM's - Am investigating now to what degree, will report back with some results on google cloud platform and others using a tiny image I built today.

**Comment by xaverdh** [comment]
I made an attempt at rewriting `setup-etc.pl` in rust [here](https://gitlab.com/xaverdh/nixpkgs-rust/-/blob/master/setup-etc/src/main.rs). This is also my first program in rust *ever*, so please don't blindly run this on your system as root (just yet).
suggestions / help / reviews are welcome!

**Comment by xaverdh** [comment]
Ah the repository should be public now (I forgot about gitlab defaults to creates them as private..)

**Comment by Gaelan** [comment]
I'm all for Rust in general, but I'm not sure we want activation scripts in a compiled language.

Activation scripts are one of the few "moving parts" of a NixOS system, and I imagine there are a lot of situations where the ability to easily read, debug, and edit them would help with recovering from weird bugs. I've never personally ended up in such a situation, so it'd be interesting to hear from anyone who has.

**Comment by Gaelan** [comment]
I suppose this is less of a problem if it's just a prebuilt binary configured via arguments/environment/config file/etc instead of something like the current perl script that's partially dynamically generated.

**Comment by otavio** [comment]
I'd love to see this moving forward; this reduces the size of minimal images and helps to boost the maintenance in long term.

**Comment by zimbatm** [comment]
This is now possible thanks to nikstur's work. See #270727 and follow-ups.
