### ISSUE TITLE
Repackage rust nightly

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#51208]
I require to build rust nightly from source. This issue is simply for gathering willing comments/recommendations if there are any.

Do you consider the old nightly-rust expression to be a decent starting point, or was it a hacky mess?

Thanks in advance.

**Comment by alyssais** [comment]
You probably want to [use](https://nixos.org/nixpkgs/manual/#using-the-rust-nightlies-overlay) the [Mozilla Rust overlay](https://github.com/mozilla/nixpkgs-mozilla) for this.

**Comment by lifranc** [comment]
@alyssais No.

> I require to build rust nightly *from source*

**Comment by alyssais** [comment]
My mistake. I didn't realise the Mozilla overlay didn't build from source.

**Comment by symphorien** [comment]
I don't know about the nightly expression, but the stable expression should be enough: you just have to 
```
export RUSTC_BOOTSRAP=1
```
and a stable rust compiler will behave as a nightly one.

**Comment by abathur** [comment]
User deleted.
