### ISSUE TITLE
Pkgconfig not configured inside FHS shell

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#51211]
## Issue description

With the given pkgconfig, in a nix-shell, only the python libs are
installed properly (with pkg-config).

### Steps to reproduce

With the following config:
```
{ pkgs ? import <nixpkgs> {} }:

(pkgs.buildFHSUserEnv {
  name = "buildroot-fhs";
  targetPkgs = pkgs: (with pkgs;
    [
      gnumake
      which
      file
      gcc
      rsync
      flex
      bison
      ncurses
      binutils
      unzip
      cpio
      perlPackages.perl
      perlPackages.XMLParser
      patch
      wget
      python2
      bzip2
      lzma
      bc
      pkgconfig
    ]);
  runScript = "bash";
}).env
```

running nix-shell , then typing echo "$PKG_CONFIG_PATH" you expect to see the pkgconfig
for all the installed libs, instead you only see ```/usr/lib/pkgconfig``` and the contents of this directory are only ```python-2.7.pc  python2.pc  python.pc``` , I would expect bzip2 and lzma present for example.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.137, NixOS, 18.09pre-git (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.03, unstable"`
 - channels(ac): `""`
 - nixpkgs: `/nix/store/8926k8sf805f9qizl55cbqaj0s70ppms-nixpkgs`
```
Running my own snapshot of nixos 18.09 .

**Comment by laser-turtle** [comment]
Did you ever find a work around or fix for this?

**Comment by jtojnar** [comment]
Development files are not installed by default. You can enable them by adding:

```
  extraOutputsToInstall = [ "dev" ];
```

**Comment by laser-turtle** [comment]
Awesome! Thank you, this was my issue as well.
