### ISSUE TITLE
ghcWithPackages does not properly install aeson

### ISSUE THREAD

**Issue by BrianHicks** [NixOS/nixpkgs#51227]
## Issue description

I'm trying to add `aeson` to a derivation where we're using shake. The shake/haskell parts look like this:

```nix
let
  shakePkgs = pkgs.haskellPackages.ghcWithPackages (ps: with ps; [base directory extra shake text unix]);
in
  # ...
```

When I add `aeson` to that list, it's downloaded but never added to the packages available to GHC. I've tried nixpkgs at:

- 03dc6471c12a0ef505ad8136ce07d47b332f2def
- 9deeaa225b5cf78cc7e17207c0cff0cb7dd7158d

and both fail in the way listed below.

### Steps to reproduce

```
nix-shell -p "haskellPackages.ghcWithPackages (ps: [ps.aeson])" --run "ghc-pkg list aeson"
```

I expected something along the lines of:

```
/nix/store/23r8bnwv1bmzs4rcbjjjqyj9694hb2kr-ghc-8.4.3-with-packages/lib/ghc-8.4.3/package.conf.d
    aeson-1.3.1.1
```

I get:

```
/nix/store/23r8bnwv1bmzs4rcbjjjqyj9694hb2kr-ghc-8.4.3-with-packages/lib/ghc-8.4.3/package.conf.d
    (no packages)
```

(but it does work for other Haskell packages, like Shake)

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.2`
 - channels(brianhicks): `"nixpkgs-19.03pre155614.ac7bf94f6df"`
 - nixpkgs: `/nix/store/wrvjfvi4jv86w27nvx687r8siqhsrrs3-vr4rqp3s8fb3ifax20z0anc2n54izs64-source`

**Comment by mpickering** [comment]
What happens if you try to build just `haskellPackages.aeson`?

**Comment by BrianHicks** [comment]
TBQH I’m not sure how to test if that works or not… I am in over my head in Nix still

How would you recommend?

**Comment by mpickering** [comment]
`nix-shell -p "haskellPackages.aeson"`

**Comment by mpickering** [comment]
I can't reproduce this with a more recent commit on NixOS fwiw. I can try on a darwin system later.

**Comment by BrianHicks** [comment]
oddly, the same thing, including the store path being identical:

```
$ nix-shell -p "haskellPackages.aeson" --run "ghc-pkg list aeson"
/nix/store/23r8bnwv1bmzs4rcbjjjqyj9694hb2kr-ghc-8.4.3-with-packages/lib/ghc-8.4.3/package.conf.d
    (no packages)
```

makes me think the problem is elsewhere maybe? Where would you recommend I look?

**Comment by BrianHicks** [comment]
here's the repl session, thanks for adding that:

```
$ nix repl
Welcome to Nix version 2.1.2. Type :? for help.

nix-repl> :l <nixpkgs>
Added 9402 variables.

nix-repl> :b haskellPackages.aeson

this derivation produced the following outputs:
  doc -> /nix/store/qbkrxqqxzhw8wflddbcziwh3bwvyfw07-aeson-1.3.1.1-doc
  out -> /nix/store/4459ca3zhv80gbh5ql28r35lja9spn7b-aeson-1.3.1.1
```

**Comment by mpickering** [comment]
I tried this on my mac, at the commit you specified and can't reproduce it.

**Comment by BrianHicks** [comment]
A colleague found a solution to this within our environment. Turned out to be in the way we're using Shake to bootstrap things from direnv. Thank you both for your help in isolating our error to our own environment. ❤️
