### ISSUE TITLE
borgbackups.jobs.<name>.paths is mandatory, and shouldn't be

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#51267]
c.f. https://github.com/NixOS/nixpkgs/blob/c1acb5ce6d8472891d3748e86ac0ff0f17de4ed9/nixos/modules/services/backup/borgbackup.nix#L193

If using --patterns-from, all of the paths to back up are (or can be) read from the pattern file, and specifying paths on the command line is optional. But the nixos configuration won't let you omit the paths, and since they aren't stored in a variable you can't even do something awkward with preHook or preCreate to unset them.

**Comment by ToxicFrog** [comment]
While investigating this, I found the related issue that since it requires "paths" rather than "strings" it also only works for absolute paths; if you want to back up relative paths (using preHook to make sure they're relative to the right directory) this is impossible. Not sure if that's worth opening a separate issue for.

**Comment by dotlambda** [comment]
I changed ot to `str`.
