### ISSUE TITLE
Building OpenJDK fails when using non-standard store directory

### ISSUE THREAD

**Issue by atanasi** [NixOS/nixpkgs#5127]
Building OpenJDK fails if the store directory is different to /nix/store.
That is because the builder needs a bootstrap compiler (openjdk-bootstrap, currently http://tarballs.nixos.org/openjdk-bootstrap-x86_64-linux-2012-08-24.tar.xz), which is not relocatable to a different store directory. In particular, the binaries refer to the dynamic linker within /nix/store, and if the linker is not found there, the binaries are not executable, and the building of OpenJDK fails accordingly.
I suggest that building of nixpkgs should always be automatically tested with a non-standard store directory.

**Comment by Profpatsch** [comment]
(triage) @atanasi Can you still reproduce that?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.
