### ISSUE TITLE
nixos: sshd - pressing backspace produces a space

### ISSUE THREAD

**Issue by eyJhb** [NixOS/nixpkgs#51283]
## Issue description
When running the `sshd` service and connecting to it using a terminal emulator like `urxvt`, pressing backspace will produce a space instead of deleting a character.

### Steps to reproduce
Start `sshd`, open `urxvt` connect to the computer, type `something` now try to delete `something` using backspace.

Doing `TERM=vt100` will resolve it, and allow for backspace deletion.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.84, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
You have to add `rxvt_unicode.terminfo` to the server's `environment.systemPackages`. This will add urxvt to the terminfo DB.
