### ISSUE TITLE
A range of changes committed to staging-18.09/release-18.09 is lost

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#51281]
## A range of changes committed to `staging-18.09`/`release-18.09` is lost (from both branches) due to an incorrect attempt to "undo" a merge.

Commit 3d63c05ddf6c4a19a04aed70a5d02adcfb3c7645 reverted the changes brought in by the previous merge commit 3b2944dbcbbab759804b8159186115940a801032.  Simulating "merge reversion" is [more complicated][1] than this.  As a result, I expect all the changes committed to `staging-18.09` from df6d40feb61 to 9110d40d20a to be lost from both `release-18.09` and `staging-18.09` (because later on `release-18.09` was merged into `staging-18.09`).

I estimated the range of "lost commits" from df6d40feb61 to 9110d40d20a, including both, by navigating `git log`.  Probably it should be double-checked.

[1]: https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt

**Comment by FRidh** [comment]
cc @vcunat for input. I suppose we can revert the revert on staging, resolve potential conflicts, stabilize, and then merge into master for a 2nd try.

**Comment by alexeymuranov** [comment]
Can be closed, i suppose (c395d6250788686120aa1a00404b4de1a2fb547c).
