### ISSUE TITLE
mythes: doesn't build on master

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#51297]
## Issue description

See the issue title.

### Steps to reproduce

```
$ nix-build -A mythes
...
/nix/store/az8gqspcfqr3fdhkscz60qhjnxdh5ggs-bash-4.4-p23/bin/bash ./libtool --tag=CXX   --mode=link g++  -g -O2   -o example example.o libmythes-1.2.la -L/nix/store/ba81s8nwzg1i4qhzm1gmdfx839mfs5km-hunspell-1.7.0/lib -lhunspell-1.7
libtool: link: g++ -g -O2 -o .libs/example example.o  ./.libs/libmythes-1.2.so -L/nix/store/ba81s8nwzg1i4qhzm1gmdfx839mfs5km-hunspell-1.7.0/lib /nix/store/ba81s8nwzg1i4qhzm1gmdfx839mfs5km-hunspell-1.7.0/lib/libhunspell-1.7.so -ltinfo /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/../lib64/libstdc++.so -lm -Wl,-rpath -Wl,/nix/store/74f00y6mg28smgnxjb5q5f96knyprw86-mythes-1.2.4/lib -Wl,-rpath -Wl,/nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/../lib64 -Wl,-rpath -Wl,/nix/store/ba81s8nwzg1i4qhzm1gmdfx839mfs5km-hunspell-1.7.0/lib
/nix/store/6s8dkfj3irwv52cap2hd9k7gaddklfs1-binutils-2.30/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:383: example] Error 1
make[1]: Leaving directory '/build/mythes-1.2.4'
make: *** [Makefile:284: all] Error 2
builder for '/nix/store/hvng6msqls4rnqyx9mzndq23dnnj08qj-mythes-1.2.4.drv' failed with exit code 2
error: build of '/nix/store/hvng6msqls4rnqyx9mzndq23dnnj08qj-mythes-1.2.4.drv' failed
```

## Technical details

nixpkgs @ a296b6eda746c4e06986cb961a384f6fc99ed449

**Comment by hedning** [comment]
This looks like the same failure enchant was hit by https://github.com/NixOS/nixpkgs/pull/50876#issuecomment-440637356. Reverting the hunspell upgrade, #50736, fixes this build too.

I looked closer into it an found the upstream commit that breaks us: [Prefer tinfo over ncurses in the readline check](https://github.com/hunspell/hunspell/pull/567/commits/37ed3a88ac018f43b1db3f536b7e0a0f2199cd72). Reverting the patch fixed the mythes build.

cc hunspell maintainer @Fuuzetsu

**Comment by c0bw3b** [comment]
Shouldn't `ncurses` be a `propagatedBuildInputs` of `hunspell` then? @Fuuzetsu 

Then ltinfo would be accessible by anything depending on hunspell.

**Comment by pbogdan** [comment]
What I find odd is that from what I can tell nothing in `hunspell` seem to actually depend on `libtinfo`? Indeed, I've thrown `pruneLibtoolFiles` onto `hunspell` and everything still built but I don't really know enough about `hunspell` / `ncurses` to be certain that is a proper fix as there was probably a reason `libtinfo` is referenced.
While some sort of fix is needed for `hunspell` annoyingly `mythes` doesn't actually reference `hunspell` in any of its outputs, it seems it's only needed to built some sort of example executable which is not distributed as a part of the package :/.

**Comment by pbogdan** [comment]
Hmm, as it turns out `libtinfo` is actually a symlink to `libncursesw`. The binaries and libraries in `hunspell` are linked with the latter so there shouldn't be a need to also link `libtinfo` separately (in `hunspell` itself and / or in its downstream dependencies)?

**Comment by c0bw3b** [comment]
But if `mythes` or anything else tries to link to `libncursesw` or `libtinfo` they still need `ncurses` in their build inputs anyway.

**Comment by neilmayhew** [comment]
The error is coming from linking an executable called `example`, so I'm guessing this is just part of the test suite, and `ncurses` isn't actually a dependency of the built derivation. In fact, when I add `ncurses` to `nativeBuildInputs` I still get:

```
$ nix-store -q --references /nix/store/dh12k1y0067diql9wc7d7cc4c07i82mn-mythes-1.2.4
/nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27
/nix/store/isirn78igzhrpi0rsvjml26rm1hsbwqp-perl-5.28.0
/nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib
/nix/store/dh12k1y0067diql9wc7d7cc4c07i82mn-mythes-1.2.4
```

**Comment by pbogdan** [comment]
@c0bw3b What I'm trying to ask is why would they need to if they just want to link to `libhunspell`? I don't seem to understand why it would be needed.

**Comment by c0bw3b** [comment]
@avnik so adding `ncurses` to nativeBuildInputs of `mythes` should be enough.
Sorry it will make you rework your PR again and it was (almost) right the first time.

**Comment by neilmayhew** [comment]
I checked whether adding `doCheck = false` would solve the problem, but `example` is in `noinst_PROGRAMS` and not `check_PROGRAMS`, so it gets built whenever the library is built. A patch to change this would be more elegant and could be submitted upstream, but it's more work than a simple nix patch.

**Comment by pbogdan** [comment]
But nothing in `mythes` directly depends on `ncurses` and as far as I can tell there are no unresolved / undefined symbols in `libhunspell`. I'm still confused why it would need any additional dependencies.

**Comment by pbogdan** [comment]
Right, that's why I mentioned `pruneLibtoolFiles` further up the thread (`pruneLibtoolFiles` clears out `dependency_libs` from libtool files).

**Comment by neilmayhew** [comment]
This in turn seems to come from hunspell's `configure.ac` [here](https://github.com/hunspell/hunspell/blob/4ddd8ed5ca6484b930b111aec50c2750a6119a0f/configure.ac#L73). I assume the `-bin` output needs `-ltinfo` but the `-lib` output doesn't, but it still gets included as a dependency anyway.

**Comment by avnik** [comment]
Fixing hunspell's Makefile.am should be a proper solution, I think.
(As well, as ``sed -i Makefile.am "/noinst_PROGRAMS/d" `` in mythes)

(regarding .la files, I believe they can be just removed, as most major distros do)

I personally pushing some urgent fixes, because I won't have libreoffice build broken in master.
Now, let's do proper solution

**Comment by pbogdan** [comment]
In any case I believe the issue as reported has been resolved.
