### ISSUE TITLE
nix-shell creates invalid store paths which is inconsitent with nix-build behavior

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixpkgs#5132]
When I use `nix-shell` to debug a package, it creates an invalid path in the store which 
couldn't / wouldn't be reused when I perform subsequent `nix-build`. Here is a very simple
example of the problem:

~~~
nix-shell '<nixpkgs>' -A hello --pure
genericBuild
~~~

The build is successful and installed in `/nix/store/w08118q0kp26qdcz5cdl2rx6chghawam-hello-2.9/bin/hello` store path.

I then validate the store path with the following command:

~~~
nix-store --verify-path /nix/store/w08118q0kp26qdcz5cdl2rx6chghawam-hello-2.9
~~~

resulting in:

> error: path `/nix/store/w08118q0kp26qdcz5cdl2rx6chghawam-hello-2.9' is not valid

Now, I try to use the exact same command, but with nix-build. 

~~~
nix-build '<nixpkgs>' -A hello --pure
~~~

Again, the build is successful and installed in `/nix/store/w08118q0kp26qdcz5cdl2rx6chghawam-hello-2.9/bin/hello` store path.

Performing yet again the store path validation

~~~
nix-store --verify-path /nix/store/w08118q0kp26qdcz5cdl2rx6chghawam-hello-2.9
~~~

now, everything seems fine (no stderr).

Note that also that I would have assumed that as the path `/nix/store/w08118q0kp26qdcz5cdl2rx6chghawam-hello-2.9` was already in the store, it should have been
used by the `nix-build` command instead of restarting from scratch.

Is there something I do not understand there? Is there some other command to perform after
`genericBuild` to register the path with the nix store? 

To have this kind of workflow available would be of great help when you want to quickly experiment
on the sources of a package iteratively using the incremental build capability of `nix-shell` and once
satisfied, test the integration of this expression in a the system as a whole using `nix-build` in combination with `myEnvFun` without a whole restart of the package you just compiled minutes ago.

I know this kind of workflow may be reproduced in some way using only `myEnvFun` but then:

 -  `myEnvFun` target the development on a single package.
 -  You have to resort to direct use of the specific builder and parametrize it so that it matches current
     system configuration. Lead to stuff like 
     `cabal configure --enable-shared --enable-executable-dynamic --allow-newer`.
 -   You still have to find a yet specific way to install this package so that other packages
      are able to interact with it. This may imply setting some LD paths, changing PATH
      , registering a library to the compiler, etc... In other words, all of the stuff that comes
      for free using `nix-shell`'s generic phases.

**Comment by peti** [comment]
I suppose this issue can be closed ... please re-open otherwise.

**Comment by Laziemo** [comment]
had the same error. sudo reboot fixed it.
