### ISSUE TITLE
mumble: Failed to execute lsb_release

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#51321]
## Issue description

`OSInfo: Failed to execute lsb_release`

It would be nice that the anonymous usage statistics include NixOS, so people see that it exists and is used!

Depends on https://github.com/NixOS/nixpkgs/issues/22729

### Steps to reproduce

Start mumble the first time and allow anonymous usage statistics to be sent.

## Technical details

mumble is installed from unstable.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.84, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.09.1446.db561c90ef3, nixos-hardware, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Mic92** [comment]
Orthogonal to fixing lsb_release, we could also propose the mumble project to use `/etc/os-release`. It is standardized and easy to parse.

**Comment by davidak** [comment]
@Mic92 that might be an option here, but generally there might be projects that won't care, so supporting lsb_release would be good. Steam also don't detects the OS, but no idea how they try to detect it.

I will ask upstream.

**Comment by Mic92** [comment]
Upstream will provide a fix for this eventually I hope: https://github.com/mumble-voip/mumble/pull/3571/files
