### ISSUE TITLE
Package request: veonim

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nixpkgs#51322]
https://github.com/veonim/veonim
 
A GUI for Neovim built on electron.
I have tried to build it with `node2nix` but fails :( and I really don't know how to deal with electron applications in nix.

**Comment by emmanuelrosa** [comment]
I don't think there's a way to deal with electron yet. Instead you can package the distribution *.zip file.

**Comment by teto** [comment]
@Ninlives you might find some inspiration in https://github.com/NixOS/nixpkgs/issues/38231

**Comment by teto** [comment]
veonim repo was removed by the author but a fork of it https://github.com/smolck/uivonim is now available in master thus closing.
