### ISSUE TITLE
nix-shell slow for qt5.qtbase

### ISSUE THREAD

**Issue by nioncode** [NixOS/nixpkgs#51347]
## Issue description
When running `nix-shell -p qt5.qtbase`, it takes around 5-6 seconds on my machine. This is kind of annoying when going into / out of the nix-shell regularly.
When I switch to using `nix-shell -p qt5.full`, it only takes 1-2 seconds, which is acceptable.

What is the reason for qtbase being so much slower than full? I encountered this by accident when I switched my `shell.nix` to use the smaller qtbase package, because then I don't have such a big closure (and especially don't have to compile so many qt modules).

### Steps to reproduce
Measure time for `nix-shell -p qt5.qtbase` and compare it to `nix-shell -p qt5.full`.

## Technical details

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.17, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1228.a4c4cbb613c, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - channels(nion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
`nix-shell -p qt5.qtbase` is quick for me

`nix shell "nixpkgs#qt5.qtbase"` is even quicker
