### ISSUE TITLE
Installing `cask` erroneously installs `cask-package-toolset`

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#51357]
## Issue description
 
Installing package `cask` installs `cask-package-toolset` rather than `cask` itself.

### Steps to reproduce

Install `pkgs.cask`. Note that `cask badge` is available, but `cask init` is not. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.19, NixOS, 18.03.133381.a18112a7e8f (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03, nixos-18.03-18.03, nixos-unstable, unstable"`
 - channels(matt): `"unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixpkgs`

**Comment by bendlas** [comment]
I think this has been fixed, and https://github.com/NixOS/nixpkgs/pull/58635 is in the pipeline now
