### ISSUE TITLE
Cargo segfaults on master

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#51416]
Cargo segfaults while fetching git dependencies. This is due to a change in libgit2 0.26.8. I have upstream issues here: https://github.com/libgit2/libgit2/pull/4732#issuecomment-443452315 and here: https://github.com/rust-lang/cargo/issues/6365 but figured someone might come hunting here. A simple patch is locally reverting libgit2 to 0.26.6 or 0.26.7 - it doesn't involve many rebuilds.

**Comment by edolstra** [comment]
Let's revert libgit2, we can't have cargo segfaulting.
