### ISSUE TITLE
btrfsProgs fails to build on master

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#51413]
## Issue description

```
checking for a Python interpreter with version >= 3.4... none
configure: error: no suitable Python interpreter found
```

Full build logs: https://gist.github.com/delroth/c051107ca2523e8fe4a2e5dca0b480f2

### Steps to reproduce

nix-shell -I nixpkgs=/path/to/nixpkgs -p btrfsProgs

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.80-1-lts, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(delroth): `"nixpkgs-19.03pre159844.7a9acea944d"`
 - nixpkgs: `/home/delroth/.nix-defexpr/channels/nixpkgs`

**Comment by delroth** [comment]
Possibly caused by the fix for #50925 (cc @matthewbauer)

**Comment by delroth** [comment]
713f5e270b63c65120cea007d9f56f80f14323f4 reverted the problematic commit.

**Comment by eburimu** [comment]
reOpen https://github.com/NixOS/nixpkgs/issues/50925?
