### ISSUE TITLE
nixos-unstable channel has not updated for 2+ weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#51466]
The nixos-unstable channel has not updated since 2018-11-17 (80738ed9dc0ce48d7796baed5364eef8072c794d). https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents suggests that only a few tests are failing, but clearly those tests will need some attention to succeed again?

**Comment by markuskowa** [comment]
also mentioned here https://github.com/NixOS/nixpkgs/issues/49384

**Comment by vcunat** [comment]
It's up to date _now_.

**Comment by peti** [comment]
Very cool. Thanks!
