### ISSUE TITLE
Dropbox fails to start since update 62.4.103

### ISSUE THREAD

**Issue by lucasimi** [NixOS/nixpkgs#51468]
Dropbox fails to start on NixOS after update 63.4.103. After running `dropbox start` I got an error message suggesting a permission problem. However checking the error log the line which seemed to be relevant was the following one: `ImportError: libglapi.so.0: cannot open shared object file: No such file or directory`.

I fixed this problem by setting the correct LD_LIBRARY_PATH variable pointing to one of my system's `libglapi.so.0` inside `~/.dropbox-dist/dropbox-lnx.x86_64-62.4.103/dropboxd/`. By running again `dropbox start` I got a similar error complaining about a missing `libxshmfence.so.1`. Using the same trick I managed to solve the issue and now Dropbox starts correctly (I don't know is this is the right way to fix it, but I suspect that upcoming releases will overwrite dropboxd).

**Comment by dotlambda** [comment]
Can this be closed?

**Comment by agvozden** [comment]
apt install libc6 libglapi-mesa libxdamage1 libxfixes3 libxcb-glx0 libxcb-dri2-0 libxcb-dri3-0 libxcb-present0 libxcb-sync1 libxshmfence1 libxxf86vm1

**Comment by jvanlangen** [comment]
The problem still exists today
