### ISSUE TITLE
nsjail refers to missing binaries

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#51496]
## Issue description

nsjail tries to execute /usr/bin/newgidmap and /usr/bin/newuidmap 

### Steps to reproduce

run nsjail with the -U or -G command. 
From the source code:

```
user.cc:        std::vector<std::string> argv = {"/usr/bin/newgidmap", std::to_string(pid)};
user.cc:        std::vector<std::string> argv = {"/usr/bin/newuidmap", std::to_string(pid)};
```

**Comment by c0bw3b** [comment]
Thanks for th report. I'll look into it sometime soon.
(BTW you can mention the package's maintainers when you open an issue)

**Comment by andrewchambers** [comment]
Thank you very much. Will do next time.
