### ISSUE TITLE
Remove old Julia versions

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#51506]
## Issue description
Right now we have three different versions of julia (0.6.4, 0.7.0, 1.0.1) in nixpkgs-unstable. However, the latest arpack update broke julia-0.6.4. Are all those versions of julia required or is it possible to remove old version?

CC @7c6f434c, @rbvermaa, @garrison
### Steps to reproduce
This is the build that broke julia-0.6
https://hydra.nixos.org/build/82144097

**Comment by leo60228** [comment]
I don't know how to fix it, but I do need 0.6.4. I've just been pinning it for now.

**Comment by leo60228** [comment]
Many Julia packages aren't updated for 1.0, or even 0.7 (as it's a slightly more compatible version of 1.0).

**Comment by garrison** [comment]
> Many Julia packages aren't updated for 1.0, or even 0.7

Is this still true?  What packages, specifically?

In my opinion
- 1.0.1 should be made the default version immediately on nixpkgs master
- I would be fine with earlier versions being dropped as well on nixpkgs master.  Those that need them can install from older versions of nixpkgs
- julia 0.7 and 1.0 actually overspecify their dependencies, last I looked.  Many pieces of the standard library were moved to packages, so FFTW, arpack, and a few others are not actually required on 0.7 and higher.

**Comment by markuskowa** [comment]
If 1.0 and 0.7 are so similar is it really necessary to keep julia 0.7?
Looking ahead to release 18.09: what can we expect in terms of package support until February? Is it realistic to make 1.0 the main version until then?

**Comment by leo60228** [comment]
Julia 0.7 is just a compatibility version of 1.0. They released
simultaneously. I need 0.6 for a program I run, but AFAIK that program only
needs ImageMagick.jl, which is only broken on Windows and Mac. Though, does
the Nix package support Mac? ImageMagick.jl is pretty popular.

**Comment by leo60228** [comment]
Most packages that are no longer in development only support 0.6. 0.7 took a while to release.

**Comment by markuskowa** [comment]
According to hydra `julia_10` builds on darwin.

**Comment by 7c6f434c** [comment]
Do I understand correctly that the current proposal is (for master):

`julia` → `julia_1` → `julia_10`
`julia_0` → `julia_06` (if the build can be fixed with reasonable effort; please ping me if a PR with a fix exists/ever appears)
drop `julia_07`

**Comment by garrison** [comment]
> `julia` → `julia_1` → `julia_10`

Yes.

> `julia_0` → `julia_06` (if the build can be fixed with reasonable effort; please ping me if a PR with a fix exists/ever appears)

Actually, I don't think it makes sense to have a `julia_0` since each 0.x version is incompatible with others.  So just having `julia_06` is fine (for as long as julia 0.6 is kept in nixpkgs).

> drop `julia_07`

Julia 0.7 is essentially equivalent to julia 1.0, except it contains warnings rather than errors for most syntax/methods that worked in julia 0.6.  So the entire point of the release is to aid people in upgrading to julia 1.0.  In this sense, it would be "nice" if `julia_07` were also available in the first release of nixpkgs that defaults to julia 1.0.  But I have no personal stake in this.

**Comment by 7c6f434c** [comment]
OK, just changed the default to 1.0.1.

**Comment by leo60228** [comment]
It'd be nice if a less hacky version of this gist was in Nixpkgs master. https://gist.github.com/leo60228/24a12d56f69e654ddd0903c41fd137bf

**Comment by markuskowa** [comment]
Julia 0.6 is broken on master and release-19.03. This version is not supported by upstream anymore. Can it be removed? For everyone who still needs to run a legacy version can install it directly from the 18.09 channel.
(https://github.com/NixOS/nixpkgs/issues/56826)

**Comment by leo60228** [comment]
Sure.
