### ISSUE TITLE
bind: binaries missing in nix run vs nix-env

### ISSUE THREAD

**Issue by brendan-hall** [NixOS/nixpkgs#51522]
## Issue description
`nix-env` and `nix run` disagree on what binaries (outputs?) to install when called on `<nixpkgs>.bind`.
For instance, the `dig` binary is missing when using `nix run`, but `mdig` is available either way

`nix run nixpkgs.dnsutils` *does* make dig available, but not mdig 

### Steps to reproduce
````console 
$ dig
The program ‘dig’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.bind
$ mdig
The program ‘mdig’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.bind
````
````console 
$ nix run nixpkgs.bind
$ dig
The program ‘dig’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.bind
$ mdig
mdig: a server '@xxx' is required
````
````console 
$ nix run nixpkgs.dnsutils
$ dig

; <<>> DiG 9.12.2 <<>>
[...]
$ mdig
The program ‘mdig’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.bind
````
````console 
$ nix-env -iA nixos.bind
installing 'bind-9.12.2'
$ dig

; <<>> DiG 9.12.2 <<>>
[...]
$ mdig
mdig: a server '@xxx' is required
````

this is repeatable with `unstable` in place of `nixpkgs`/`nixos`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.84, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(nullvoid): `"unstable-19.03pre159472.80738ed9dc0"`
 - channels(root): `"nixos-18.09.1446.db561c90ef3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ryneeverett** [comment]
Superseded by #56576?

**Comment by wmertens** [comment]
definitely superseded by #56576
