### ISSUE TITLE
Customizing myEnvFun environment

### ISSUE THREAD

**Issue by jgeerds** [NixOS/nixpkgs#5153]
What is the proper way to customize an environment created by myEnvFun? For example, running ```load-env-foo``` changes my PS1 and unset my shell aliases. This behavior is different from using ```nix-shelll```, isn't it? Because with ```nix-shell``` everything works as expected. It saves my shell environment like PS1 and aliases.

Should I simply ```source ~/.bashrc``` inside my myEnvFun environment? However, even this approach doesn't fix all "issues" (like the missing ```__git_ps1``` function to get the current git branch I'm working on)

**Comment by timsears** [comment]
I just ran into the same issue with load-env-someenv. 

Spent an hour hunting for the 'which' command which it actually an alias to bash builtin 'type -P'. Make me wonder what else got wiped out from my environment.  How does nix-shell differ?

**Comment by Profpatsch** [comment]
(triage) I think this can be closed cc @bjornfor

**Comment by domenkozar** [comment]
Just a note that myEnvFun is deprecated and shouldn't be used.

To get similar behavior with nix-shell it should be possible in a few lines.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/issues/18315
