### ISSUE TITLE
Printing: use gutenprint by default

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#5155]
and run `cups-genppdupdate` to update DB. Update https://nixos.org/wiki/Printers

**Comment by Profpatsch** [comment]
Do you think it is okay to include that? `gutenprint` is quite a big package.
How about changing the example to `[ pkgs.sqlix pkgs.gutenprint ]` so users (who are probably familiar with the name immediately recognize it and also find it with a general search?

**Comment by Profpatsch** [comment]
There is a `gutenprint` option now, and it has been [clarified](https://github.com/NixOS/nixpkgs/pull/13763), so close @zimbatm.
