### ISSUE TITLE
appimage-run: will not run OpenRA mods, due to it failing to detect Mono, even when installed

### ISSUE THREAD

**Issue by fusion809** [NixOS/nixpkgs#51555]
## Issue description
[OpenRA](https://github.com/OpenRA/OpenRA) provides AppImages for its official mods and via their [SDK](https://github.com/OpenRA/OpenRAModSDK) they make it easier for developers of unofficial mods to distribute their mods as AppImages. 

The AppImages they provide are unusual in that they do have a host dependency, beyond FUSE and modern standard system libraries, Mono. Presently a compatible version of Mono is installed on my system, namely version 5.8.0.108 (which is the version `mono --version` gave me), but still I see this error dialog box appear:

![screenshot_20181205_161758](https://user-images.githubusercontent.com/4717341/49494664-1d091d00-f8ac-11e8-87e7-a7131a2be33e.png)

When I try to launch the official Red Alert mod using appimage-run. 

### Steps to reproduce
1. Install NixOS 18.09, using my configs: https://github.com/fusion809/NixOS-configs/tree/dc4954f15812bbb319fdcf7644646c9ed9fb968d).
2. Install Mono 5.8.0.108 and appimage-run with:

```bash
nix-env -f '<nixos-unstable>' -iA mono-5.8.0.108 appimage-run
```

(refer to [note 1](#note) for further details)

3. Obtain the official release-20180923 Red Alert AppImage from (and yes I have tested this on other AppImages belonging to OpenRA mods): https://github.com/OpenRA/OpenRA/releases/download/release-20180923/OpenRA-Red-Alert-x86_64.AppImage, e.g. by downloading it with wget:

```bash
wget -c https://github.com/OpenRA/OpenRA/releases/download/release-20180923/OpenRA-Red-Alert-x86_64.AppImage
```

4. Set its permissions to executable with:

```bash
chmod +x OpenRA-Red-Alert-x86_64.AppImage
```

5. Run `appimage-run` on it, with:

```bash
appimage-run OpenRA-Red-Alert-x86_64.AppImage
```

and Voila, you should see this error.

## Technical details
```bash
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.35 MiB download, 1.59 MiB unpacked):
  /nix/store/63j8mi5vjyxfc89rhjknwxaxqg3a2sx2-paxctl-0.9
  /nix/store/bqp3d4yhpx6h60fv8jww5id0nkm44034-patchelf-0.9
  /nix/store/i6vl5lwlz5jbkg4r6p340dwmj6fha3xq-stdenv-linux
  /nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev
  /nix/store/ql3azyviwyc6w73h6prk1j2945skfapf-gnumake-4.2.1
copying path '/nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/bqp3d4yhpx6h60fv8jww5id0nkm44034-patchelf-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/ql3azyviwyc6w73h6prk1j2945skfapf-gnumake-4.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/63j8mi5vjyxfc89rhjknwxaxqg3a2sx2-paxctl-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/i6vl5lwlz5jbkg4r6p340dwmj6fha3xq-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.85, NixOS, 18.09.1534.d45a0d7a4f5 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(fusion809): `""`
 - channels(root): `"nixos-18.09.1534.d45a0d7a4f5, nixos-unstable-19.03pre161545.7c73f53d836"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Notes:
1. `nixos-unstable` is the repo mentioned as it is what I was using when I noticed this error. By-the-way, I have also tried adding `mono` to my `systemPackages` array in `/etc/nixos/configuration.nix` and rebuilding. Even after this, and following steps 3-5, I receive this same error. I also tried adding both `mono` and `appimage-run` to this array and rebuilding, and after this I still received this error when trying to run the subsequent steps. In case you're wondering, I made sure to start new shells after rebuilding, so my environment variables should have been properly set up. I verified I was using system `appimage-run and `mono` by running `which mono appimage-run` which returned: 

```bash
/run/current-system/sw/bin/mono
/run/current-system/sw/bin/appimage-run
```

.

**Comment by fusion809** [comment]
Should probably cc @tilpner, as he seems like the lead dev of appimage-run.

**Comment by tilpner** [comment]
appimage-run doesn't use your system environment, you need to add mono to appimage-runs environment: 

```nix
# Something like this
appimage-run.override { extraPkgs = p: with p; [ mono ]; }
```

**Comment by fusion809** [comment]
I'm fairly new to NixOS, so I'm not sure what I'm meant to do with this. Guessing that's something I add to my /etc/nixos/configuration.nix file?

**Comment by tilpner** [comment]
That's a Nix expression describing a modified appimage-run that will include mono.
You can use that anywhere you can use Nix expressions, like nix-build, nix-instantiate, overlays, and of course your configuration.nix too.

```nix
# Here's a module that will install this modified appimage-run for the user "fusion"
{ pkgs, ... }: {
  users.users.fusion.packages = [
    (pkgs.appimage-run.override {
      extraPkgs = p: with p; [ mono ];
    })
  ];
}
```

**Comment by fusion809** [comment]
Aha it works now, thanks! I'm pleased I cc'ed ya. So this issue essentially now becomes an instruction manual for those experiencing the same issue.
