### ISSUE TITLE
Updated to pcl 1.9.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#51573]
## Issue description

[pcl](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/pcl/default.nix) is in need of an update.

https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.1

**Comment by cpages** [comment]
Fixed with c07783f37db3c133fee87e531f1cd509f29f10d7
