### ISSUE TITLE
supplicant service doesn't restart on resume

### ISSUE THREAD

**Issue by djahandarie** [NixOS/nixpkgs#51582]
## Issue description

The `supplicant` service in NixOS doesn't restart on resume, though the code seems to have the intent that it should.

In particular, see these lines:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/supplicant.nix#L43
```
        # Receive restart event after resume
        partOf = [ "post-resume.target" ];
```

### Steps to reproduce

Configure a supplicant service, sleep and resume laptop, observe that the service has been cleanly shutdown on resume instead of restarted.

## Technical details

The nix expression results in the following unit file for me:

```
After=sys-subsystem-net-devices-wlp4s0.device
Before=network.target
BindsTo=sys-subsystem-net-devices-wlp4s0.device
Description=Supplicant wlp4s0
PartOf=post-resume.target
Wants=network.target
```

There is the following description of "PartOf" in the systemd manual:

```
PartOf=
Configures dependencies similar to Requires=, but limited to stopping and restarting of units. When systemd stops or restarts the units listed here, the action is propagated to this unit. Note that this is a one-way dependency — changes to this unit do not affect the listed units.
```

Given this description, I would guess that the `post-resume.target` is stopping on resume, and that stop gets propagated to `supplicant`, which causes it to stop, instead of restart.

I'm not sure what the right fix is here. Other people seem to have had related issues: https://github.com/NixOS/nixpkgs/issues/19525

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.62, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09, nixos-unstable-19.03pre158246.6141939d6e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

cc @bennofs @groxxda

**Comment by bennofs** [comment]
Why do we even need to restart supplicant after resume?

**Comment by djahandarie** [comment]
FYI, I confirmed this hypothesis is correct via systemd debug logs:
> Given this description, I would guess that the post-resume.target is stopping on resume, and that stop gets propagated to supplicant, which causes it to stop, instead of restart.


So,

1. Removing the PartOf would at least prevent it from stopping on resume
2. We may not even need to restart on resume, it's quite likely wpa_supplicant will work just fine without that, since it notices the interface going away and coming back, which should be enough for it to reassociate quickly.

**Comment by 7c6f434c** [comment]
I guess `wpa_supplicant`-level correct approach could be `wpa_cli reassociate` (then again, if you suspend and resume in the same place relatively quickly — folding the laptop and going to the next office, for example — it would be better to do nothing; but reassociate is not much worse if the coverage is good, and I don't think we can distinguish to cases cheaply).

**Comment by bennofs** [comment]
The main problem is that as far as I know, it's not possible in systemd to reliably execute a command after resume.

**Comment by djahandarie** [comment]
@bennofs @7c6f434c Would one of you mind reviewing that PR? https://github.com/NixOS/nixpkgs/pull/83000 (Not sure if it's the ideal solution but it's at least better than wpa_supplicant shutting down on resume... :smiley:)
