### ISSUE TITLE
Support generating DSA-like DH parameters

### ISSUE THREAD

**Issue by 9ary** [NixOS/nixpkgs#51617]
The service provided in `security.dhparams` is very slow for large bit sizes.
[This SE answer](https://security.stackexchange.com/a/95184) explains that it's because OpenSSL tries by default to generate a "strong prime" which is very computationally expensive task. It suggests using the `-dsaparam` option which should be equally secure.
My experience shows that it's orders of magnitude faster (seconds instead of hours), so it would be useful to support that mode, possibly as an option.

**Comment by Mic92** [comment]
I not seen that it took hours to generate. Are you low on entropy?

**Comment by Lonami** [comment]
Did you read the linked answer @Mic92?

**Comment by Streetwalrus** [comment]
My situation is pretty much the same as the linked SE question: 4096 bit dhparam size, entropy is plentiful (tried with haveged as well), and quoting the answer again:
>If openssl uses a lot of CPU then it is not blocked waiting for "entropy". OpenSSL is actually sane in that respect, and uses a cryptographically secure PRNG to extend an initial seed into as many bits as it needs.

**Comment by Mic92** [comment]
According to https://www.openssl.org/news/secadv/20160128.txt this option should be only used for certain ciphers as the name suggests and is not safe in general.

**Comment by 9ary** [comment]
In that case, it would be nice to at least have this as an option.

**Comment by Mic92** [comment]
@9ary maybe just an option that allows to pass arbitrary options to `dhparam`. This options seems like an expert setting and should be only used by people that know what they are doing.

**Comment by 9ary** [comment]
That sounds reasonable.
