### ISSUE TITLE
vivaldi: hash changed

### ISSUE THREAD

**Issue by greydot** [NixOS/nixpkgs#51635]
## Issue description
This probably isn't a strictly NixOS issue, but nevertheless should be mentioned.
The hash for vivaldi-stable_2.1.1337.51-1 has changed. The old one in nixpkgs is 08x6abyz65vx4ycj8ys8sib9z1adb8ybmnrqjck69b30kbz78rj2, while nix-env reports 00rxp6rardxjg17g2b28y2rj8szqlainp4ga6c58z981zkxvdlls.

### Steps to reproduce
1. Switch to unstable channels.
2. nix-env -i vivaldi

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.85, NixOS, 19.03pre161545.7c73f53d836 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(void): `"nixpkgs-19.03pre160749.3a393eecafb"`
 - channels(root): `"nixos-19.03pre161545.7c73f53d836, nixpkgs-19.03pre160749.3a393eecafb"`
 - nixpkgs: `/home/void/.nix-defexpr/channels/nixpkgs`

**Comment by flokli** [comment]
@greydot unfortunately, sometimes software projects update different package sources with different sha256sums on their website, which will then error during build, until it gets fixed again

Can you add a Pull Request, updating the hash in pkgs/applications/networking/browsers/vivaldi/default.nix?
