### ISSUE TITLE
Filesystems assertion

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#5164]
We have to provide a way to check if `fsType` that was given can be supported.
I mean, that if we create smth like
```
  fileSystems."/ceph" = { 
      ...
      fsType = "ceph";
      ...
    };
```
And `ceph` isn't installed then this won't be mounted and system won't switch to a new generation and will go into systemd's rescue mode.

**Comment by jagajaga** [comment]
How can we get the list of filesystems supported by NixOS (to check if fs.fsType is supported)?
cc @edolstra 
Or maybe the only way is just to write module to `tasks/filesystems` to support?

**Comment by Profpatsch** [comment]
(triage) @jagajaga do you plan to work on this further?

**Comment by jagajaga** [comment]
Maybe someday...
