### ISSUE TITLE
binutils: drop the dtneeded.patch?

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#51647]
## Issue description

Nixpkgs appears to patch `binutils` so that the linker uses the `--copy-dt-needed-entries` option by default. This seems to have the effect of the linker being able to resolve dependencies via anything in the transitive dependencies chain. While that may work at build time it doesn't seem to work at run time as unless the dependency is declared explicitly Nix / nixpkgs ensures the dynamic loader won't be able to see it.
Conceptually `--no-copy-dt-needed-entries` behaviour seems closer to what would be the desired behaviour in Nix / nixpkgs. At the same time I don't have a great deal of understanding here so I may well be wrong. Just opening this issue for discussion as I would like to hear others' opinions and clear up my own misunderstandings.

### Steps to reproduce

Consider the following test program that references a symbol exported by `libgssapi_krb5` shared library:

```C
char gss_krb5_ccache_name ();
int main ()
{
    return gss_krb5_ccache_name ();
    return 0;
}
```

Build it but _don't link it_ against said library but something that has it in its transitive dependency chain:

```
$  gcc test.c -o test -Wl,--copy-dt-needed-entries -lldap_r
```

Observe the compilation succeeding but resulting in a runtime failure:

```
$ ./test: error while loading shared libraries: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
```

Now build the same program using `--no-copy-dt-needed-entries` linker option:

```
$ gcc test.c -o test -Wl,--no-copy-dt-needed-entries -lldap_r
/nix/store/ihi9rhwq22y92p9iay1mdvy0lr75wdh2-binutils-2.30/bin/ld: /run/user/1000/cc90p4Wk.o: undefined reference to symbol 'gss_krb5_ccache_name@@gssapi_krb5_2_MIT'
/nix/store/hr82iai25rdkgkgx7n1hv3p311hs1141-libkrb5-1.15.2/lib/libgssapi_krb5.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

## Technical details

Affects `binutils` on master, reproducer based on `staging-next`.

**Comment by vcunat** [comment]
Merged https://github.com/NixOS/nixpkgs/pull/51770; in staging-next ATM.
