### ISSUE TITLE
python3 captures references to build coreutils

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#51668]
Things like install prog, mv, and friends used during config are captured.

Eliminated via
```
find $out/lib/python*/config-*-* -type f -print -exec nuke-refs '{}' +
find $out/lib -name '_sysconfigdata_m*.py*' -print -exec nuke-refs '{}' +
```
but I'm sure that's too heavy handed.

For me, the above nuking also "fixes" https://github.com/NixOS/nixpkgs/issues/51465

**Comment by FRidh** [comment]
Pushed 2526f9f157465cfc66385ea3213ed833a3944c43 to staging.

**Comment by joachifm** [comment]
Thank you :)
