### ISSUE TITLE
Python SyntaxError when building python37Packages.robotframework-selenium2library

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#51727]
## Issue description

`python37Packages.robotframework-selenium2library` fails to build with a Python `SyntaxError`.

### Steps to reproduce (`master`)

(61c3169a0e17d789c566d5b241bfe309ce4a6275 when I tried)

1. `git clone https://github.com/NixOS/nixpkgs.git`
2. `cd nixpkgs`
3. `nix-build -A python37Packages.robotframework-selenium2library`

#### Expected
Build succeeds

#### Observed
Build fails with this output
```
these derivations will be built:
  /nix/store/jj08nah9ll8diwchdq0dkppfabykj8da-python3.7-robotframework-selenium2library-1.6.0.drv
building '/nix/store/jj08nah9ll8diwchdq0dkppfabykj8da-python3.7-robotframework-selenium2library-1.6.0.drv'...
unpacking sources
unpacking source archive /nix/store/f8416ljdwb511g8pysci2i0gha2hragk-robotframework-selenium2library-1.6.0.tar.gz
source root is robotframework-selenium2library-1.6.0
setting SOURCE_DATE_EPOCH to timestamp 1414981337 of file robotframework-selenium2library-1.6.0/src/robotframework_selenium2library.egg-info/top_level.txt
patching sources
configuring
building
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 7, in <module>
    from ez_setup import use_setuptools
  File "src/ez_setup.py", line 106
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax
builder for '/nix/store/jj08nah9ll8diwchdq0dkppfabykj8da-python3.7-robotframework-selenium2library-1.6.0.drv' failed with exit code 1
error: build of '/nix/store/jj08nah9ll8diwchdq0dkppfabykj8da-python3.7-robotframework-selenium2library-1.6.0.drv' failed

```

### Steps to reproduce (current channel)

(`nixos-18.09.1568.2dc559868c9` in my case)

1. `nix build nixpkgs.python37Packages.robotframework-selenium2library`

#### Expected
Build succeeds

#### Observed
Build fails with this output:
```
builder for '/nix/store/k4367q5xadp7pj1cpq6sazwyai6wydia-python3.7-robotframework-selenium2library-1.6.0.drv' failed with exit code 1; last 10 log lines:
  building
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 7, in <module>
      from ez_setup import use_setuptools
    File "src/ez_setup.py", line 106
      except pkg_resources.VersionConflict, e:
                                          ^
  SyntaxError: invalid syntax
[0 built (1 failed)]
error: build of '/nix/store/k4367q5xadp7pj1cpq6sazwyai6wydia-python3.7-robotframework-selenium2library-1.6.0.drv' failed

```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.86, NixOS, 18.09.1568.2dc559868c9 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1568.2dc559868c9"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

I ran into this when running `nix-shell -p nox --run "nox-review wip"` with a changed `pkgs/development/tools/geckodriver/default.nix` in preparation for PR #51725. I've filed the PR anyway, so another way to reproduce is now

1. `nix-shell -p nox --run "nox-review pr 51725"`

which will (among others) run `nix-build -A python37Packages.selenium -A bepasty -A geckodriver -A python27Packages.bokeh -A python27Packages.selenium -A python37Packages.robotframework-selenium2library -A python27Packages.robotframework-selenium2library -A python37Packages.splinter -A python37Packages.bokeh -A searx -A python27Packages.splinter /home/das-g/.nox/nixpkgs` which also fails with above error.

**Comment by FRidh** [comment]
that error indicates that robotframework-selenium2library is Python 2 only.

**Comment by das-g** [comment]
> that error indicates that robotframework-selenium2library is Python 2 only.

Ah, why is `nox-review` trying to build it for Python 3, then?

**Comment by FRidh** [comment]
because apparently the build had not been disabled for Python 3.
