### ISSUE TITLE
package and deps available as a substitutes can't be built from source

### ISSUE THREAD

**Issue by jncy** [NixOS/nixpkgs#51745]
## Issue description

As part of my effort to test nixpkgs reproducibility, I decided to choose a non-trivial package and see if I could get it to build at all, entirely from source.

Using a fresh install of nix with the stable 18.09 channel, I first disabled substitutes with "substitute = false" in nix.conf. After that, my attempt to install "firefox" eventually failed while building autoconf-2.64, presumably for the same reasons as described in #40782.

Of course, after re-enabling substitutes, firefox installed with zero problems.

This inconsistency would seem to suggest a problem in the nix toolset or release process. But if it's somehow expected behavior, could you please document it in a FAQ?

### Steps to reproduce

Using a fresh install of nixpkgs 2.1.3 on Debian 9, I first switched from the unstable channel to the latest release:

```
nix-channel --remove nixpkgs
nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs
nix-channel --update
```

I created the file ~/.config/nix/nix.conf and added a single line:
```
substitute = false
```
Finally, I attempted to install a large package with many deps:

```
nix-env -f '<nixpkgs>' -iA firefox
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-8-amd64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(nix): `"nixpkgs-18.09.1446.db561c90ef3"`
 - nixpkgs: `/home/nix/.nix-defexpr/channels/nixpkgs`

[EDIT: corrected the nix.conf snippet. 'substitute' was set to 'false' for this test.]

**Comment by FRidh** [comment]
Looks to me like this is simply due to not using sandboxed builds.

**Comment by matthewbauer** [comment]
It is a little bit surprising that something would work **with** sandboxing but not without it. I would expect everything that works with sandboxing to work without sandboxing, but not the other way around. I would assume it's picking up something in /usr?

**Comment by Ekleog** [comment]
I don't think that there is an effort trying to make everything build with sandboxing disabled -- sandboxing is also designed to give less opportunity for the software to be impure, and patching everything to respect purity without sandboxing would be too impractical even for nixpkgs.

Closing as a consequence, feel free to tell me if there's something actionable I've missed :)
