### ISSUE TITLE
borgbackup.jobs.* does not serialize access to the same repo

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#51778]
## Issue description
`borgbackup.jobs` lets you point multiple backup jobs at the same repo, which is useful to do as it allows deduplication across backups.

However,borg does not allow concurrent access to the same repo, and the automatically generated units and scripts do nothing to take this into account. So if you configure multiple borgbackup jobs that run at the same time (or have overlapping runs more generally), all but one of them will fail.

This can be mitigated somewhat by setting different start times for different backup jobs, but if one of the jobs runs long you're still going to have a bad time.

### Steps to reproduce

```
services.borgback.jobs = {
  test1 = {
    archiveBaseName = "test1";
    repo = "/tmp/borgrepo";
    paths = [ /etc ];
    encryption.mode = "none";
    startAt = ["*-*-* 07:00:00"];
  };
  test1 = {
    archiveBaseName = "test1";
    repo = "/tmp/borgrepo";
    paths = [ /etc ];
    encryption.mode = "none";
    startAt = ["*-*-* 07:00:00"];
  };
}
```

Change `*-*-* 07:00:00` to something more convenient as needed.
At the specified time, both units will activate, but one will immediately fail with "unable to acquire lock" as the other has won the race for access to the borg-repo.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 19.03pre161883.e85c1f58680 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre161883.e85c1f58680, nixos-17.03-17.03.1949.78e9665b48f, nixos-18.03-18.03.133381.a18112a7e8f, nixos-unstable-19.03pre161883.e85c1f58680"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by markuskowa** [comment]
Could you elaborate on a use-case where one would one want to run different backup jobs on the same repo at the same time?  If you want to backup different directories into the same repo you could just  list all directories in `path`. Those directories are then backed up one after another. 

A trick to get a serial behavior could be to define the dependencies manually in your config by setting: `systemd.services.borgbackup-job-test2.after = [ "borgbackup-job-test1" ];`

**Comment by ToxicFrog** [comment]
> Could you elaborate on a use-case where one would one want to run different backup jobs on the same repo at the same time?

I have multiple things to back up, not all of which have the same backup schedule and not all of which are (or, in some cases, can be) mounted at the same time. I want them all backed up to the same repo so that I get deduplication between them.

> If you want to backup different directories into the same repo you could just list all directories in path. Those directories are then backed up one after another.

Then they all end up in the same archive, which means everything being backed up needs to be mounted at once, and running different backup schedules for different datasets is impossible.

> A trick to get a serial behavior could be to define the dependencies manually in your config by setting: `systemd.services.borgbackup-job-test2.after = [ "borgbackup-job-test1" ];`

I think I'd also have to give it `Type=oneshot`, since otherwise "after" will just wait for the borg process to start up, not for it to finish running. It's also not clear to me how rigorously "after" ordering dependencies are respected when multiple independent timers are going off, possibly not all at quite the same time, and some of the services being activated them have ordering dependencies between them. I'll give that a shot and see if it works, though.

**Comment by dotlambda** [comment]
You can always set `startAt = [ ]` and have some other program start the backup jobs. This is definitely out of scope for the NixOS module.

**Comment by ToxicFrog** [comment]
Personally, I don't think this should be out of scope; specifying multiple backups targeting the same repo is a common and expected use of Borg, and it's one where NixOS will currently generate unit files that just don't work reliably.

That said, for anyone else running into the same issue: setting `After = [some other backup job]` and `Type = "oneshot"` for each generated service worked fine for me. I used the following:

```
let
  name-to-service = name: {
    name = name;
    "borgbackup-job-${name}" = {
      serviceConfig.Type = "oneshot";
    };
  };
  merge-and-order-services = first: second:
    if first.name == "" then second else
      lib.attrsets.recursiveUpdate
        (first // second)
        { "borgbackup-job-${second.name}".after = ["borgbackup-job-${first.name}.service"]; };
  borg-ordering = names:
    removeAttrs
      (builtins.foldl'
        merge-and-order-services
        { name = ""; }
        (map name-to-service names))
      ["name"];
in {
  systemd.services = borg-ordering [ "first-backup" "second-backup" "third-backup" ];
}
```

Where the names passed to borg-ordering match the names you've used in `services.borgbackup.jobs.<name>`.

I suspect this will still cause problems if it takes so long to run one of your backups that the timers for earlier backups fire again; you might want to put your slowest backups first.

**Comment by benneti** [comment]
Thanks for the snippet and I wanted to say that I agree that it would be a nice thing in nixos!
