### ISSUE TITLE
LVM installer test is broken on master

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#51790]
## Issue description

As @pbogdan [found in staging-next](https://github.com/NixOS/nixpkgs/pull/51444#issuecomment-445407559):
> The xfsprogs update seems to break the LVM installer test. Looks to be an instance of https://bugzilla.redhat.com/show_bug.cgi?id=1575797 that's been patched in grub http://git.savannah.gnu.org/cgit/grub.git/commit/?id=cda0a857dd7a27cd5d621747464bfe71e8727fff.

failure on hydra: https://hydra.nixos.org/build/85713125

**Comment by markuskowa** [comment]
I included the above mentioned patch in https://github.com/NixOS/nixpkgs/pull/51756. That unbreaks the LVM installer test.

**Comment by hedning** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/51756
