### ISSUE TITLE
KDE and PulseAudio Not Working

### ISSUE THREAD

**Issue by ruediger** [NixOS/nixpkgs#5180]
I'm trying to use KDE4 with PulseAudio but I won't get any sound. PulseAudio works fine with non-KDE applications, such as MPlayer, Flash, Steam. But if I try to use the test function in the "Device Preference" or "Audio Hardware Setup" sections in the Multimedia setting, I don't hear any sound. If run Clementine it crashes as soon as I try to play an audio file with the message

    (clementine:7560): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

I have tried using the vlc back end but the results are the same.  I'm not sure if gstreamer even comes with pulse support.  If I try

    $ gst-inspect pulsesink
    No such element or plugin 'pulsesink'

I'm using

    $ nixos-version
    14.11pre52840.c347f1c (Caterpillar)

but it has been broken for a while (not sure if it ever worked for me). The option `hardware.pulseaudio.enable` is set to `true`.

Another user confirmed the same behavior on IRC.

**Comment by iElectric** [comment]
Any luck on this?

**Comment by ruediger** [comment]
I have `15.05pre54730.cbe467e (Caterpillar)` now and `gst-inspect pulsesink` finds the `pulsesink`. Clementine plays audio without crashing. However it seems KDE itself still doesn't work. At least when I try to test my configuration in the "Multimedia" Settings I either won't get any audio or I get a Segfault.  Sadly there are no debug symbols installed (is there a way to install external debug symbols on NixOS?) and thus the backtrace is not very useful:

```
Application: System Settings (systemsettings), signal: Segmentation fault
[Current thread is 1 (process 4048)]

Thread 1 (process 4048):
#0  0x00007f6e72c30f7c in ?? ()
#1  0x0000000000000000 in ?? ()
```

I'm not sure if this is a bug in the systemsettings or an issue in Phonon. I'll be glad to provide any further information.

**Comment by YotaVGA** [comment]
I've the same problem, too. pulseaudio works perfectly, but KDE didn't emit any sound.

**Comment by ttuegel** [comment]
This was a Phonon/GStreamer issue. It has been fixed in master for some time.
