### ISSUE TITLE
syncthing package fails to build (regression from 79b94624)

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#51825]
## Issue description

The "syncthing" package fails to build after 79b94624 (identified by bisect).

### Steps to reproduce

nix-build -A syncthing

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.80-1-lts, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(delroth): `"nixpkgs-19.03pre160749.3a393eecafb"`
 - nixpkgs: `/home/delroth/.nix-defexpr/channels/nixpkgs`

**Comment by delroth** [comment]
FYI @Mic92 (author of the identified commit).

Build log: https://pastebin.com/6H3vBUeC

**Comment by cyounkins** [comment]
I'll take a look at this.

**Comment by cyounkins** [comment]
I can confirm the build fails in the sandbox.

But it builds in a `nix-shell`, then correctly installs in `nixos-rebuild` :scream:

Related: https://github.com/golang/go/issues/16445 and https://github.com/golang/go/issues/16395

I don't think I'll be able to fix this.

**Comment by Mic92** [comment]
The package should use `buildGoPackage`.

**Comment by Mic92** [comment]
Ok. This would still solve this concrete problem though.
