### ISSUE TITLE
nix-collect-garbage does not remove systemd-boot entries

### ISSUE THREAD

**Issue by cyounkins** [NixOS/nixpkgs#51834]
## Issue description

After running `nix-collect-garbage -d`, unbootable menu entries remain at `/boot/loader/entries/nixos-generation-*`

### Steps to reproduce

1. Have at least 2 generations
2. `nix-collect-garbage -d`
3. `cat /boot/loader/entries/nixos-generation-nixos-generation-1.conf`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

Currently unable to run this - system was built using local copy of `nixpkgs` on `master`. https://gist.github.com/cyounkins/ec58203f9f223a66f827e4debd9d6c2d

**Comment by cyounkins** [comment]
Ah, this is because nix-collect-garbage does not know it is on NixOS. `nixos-rebuild switch` will remove the entries. See #3542

**Comment by fourdragons** [comment]
nixos-rebuild switch isn't removing entries for me. I've tried everything I can think of. Even deleting the entries in /boot/loader/entries/ manually. They just come back on next rebuild.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 19.09.1693.eab4ee0c27c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1693.eab4ee0c27c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fourdragons** [comment]
Got it! FINALLY! Here goes:

`sudo rm /nix/var/nix/profiles/system-profiles/<entries>` (There will be two for each)
`sudo nix-collect-garbage -d`
`sudo nixos-rebuild switch`
`sudo rm /boot/loader/entries/<entry>`
`shutdown -r now`

Voila!

**Comment by krakjn** [comment]
Thank you @fourdragons 
The `-p` switch is what tripped me up as well. Thanks for posting the fix!
