### ISSUE TITLE
Emby license change, now proprietary

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#51832]
It seems that the Emby server has changed license from GPL-2 to "proprietary core with open-source components":

https://github.com/MediaBrowser/Emby/issues/3479#issuecomment-444985456

As such, it seems that the sources for the 3.6 version and onward won't be distributed. I'm not sure what needs to be done here, but since I haven't seen a discussion about it yet, I'm opening a new issue.

Thanks!

**Comment by minijackson** [comment]
Here is a discussion about Emby forks and alternatives:

https://github.com/nvllsvm/emby-unlocked/issues/28

And here is what looks to me as an active fork (but don't quote me on that):

https://github.com/jellyfin/jellyfin

**Comment by bachp** [comment]
Emby wasn't built from sources in nixpkgs anyway. So I think the first step would be to change the license to unfree with the 3.6 update.

If a fork gains traction I think it makes sense to package it.

**Comment by nyanloutre** [comment]
Jellyfin seems to gain traction, maybe we could package it ?

**Comment by minijackson** [comment]
Now that Jellyfin is packaged and has a module, I think it's safe to close this issue ^^
