### ISSUE TITLE
error: value is null while a set was expected, at pkgs/top-level/default.nix:63:5 (when nixops deploy)

### ISSUE THREAD

**Issue by YuMingLiao** [NixOS/nixpkgs#51858]
## Issue description
I am testing first example in [nixops] (https://nixos.org/nixops/)
nixops deploy successfully when I use nixos-18.09 channel.
The error occurs when I use nixos-unstable channel.

### Steps to reproduce
# nixops create -d simple network.nix
created deployment ‘7928a9c0-fcee-11e8-ba69-080027437e26’
7928a9c0-fcee-11e8-ba69-080027437e26
# nixops deploy -d simple
error: value is null while a set was expected, at /nix/store/hkc08vfykjn8nidf7q2zm1jka1r20rli-nixpkgs-19.03pre161883.e85c1f58680/nixpkgs/pkgs/top-level/default.nix:63:5
error: evaluation of the deployment specification failed

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 19.03pre158246.6141939d6e0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixpkgs-19.03pre161883.e85c1f58680"`
 - channels(demo): `"nixpkgs-19.03pre155767.8070a6333f3"`
 - channels(ted): `"nixos-19.03pre151837.ca2ba44cab4"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

And default.nix:63:5 is about a varaible 'localSystem'.

I try 'git clone nixpkgs' and 'git log --follow -p -- pkgs/top-level/default.nix', but nothing I can understand :p .

**Comment by robinp** [comment]
Based on `nixops deploy --show-trace`, pinpointed to issue to `config` being `null` in `pkgs/top-level/default.nix`:63, so set intersection fails.

I'm not sure what I'm doing, but replaced `config` with `(if config == null then {} else config)` and it got further.

```
diff --git a/pkgs/top-level/default.nix b/pkgs/top-level/default.nix
index dcd443a1c29..2f41b0a27ca 100644
--- a/pkgs/top-level/default.nix
+++ b/pkgs/top-level/default.nix
@@ -60,7 +60,7 @@ in let
   localSystem = lib.systems.elaborate (
     # Allow setting the platform in the config file. This take precedence over
     # the inferred platform, but not over an explicitly passed-in one.
-    builtins.intersectAttrs { platform = null; } config
+    builtins.intersectAttrs { platform = null; } (if config == null then {} else config)
     // args.localSystem);
```

You can checkout `nixpkgs-channel`'s `nixos-unstable` branch, apply the patch, and do `NIX_PATH=nixpkgs=/path/to/my/nixpkgs-channels nixops deploy`.

**Comment by palfrey** [comment]
This worked for me as well. Can we get this applied to the main tree?

**Comment by robinp** [comment]
Well, my quickfix applies the bandage at the surface, but I'm not sure if there's a more fundamental issue (maybe `config` shouldn't be null to begin with?).

It would be nice if someone could spare a little time to [git bisect](https://git-scm.com/docs/git-bisect) to see which commit introduced the bug?

**Comment by kristoff3r** [comment]
It comes from this commit, which fixed another (related) error: https://github.com/NixOS/nixpkgs/commit/56e12aae54bc67cabe5aa7c8d055438af4f62b5e

Based on the discussion in https://discourse.nixos.org/t/nixops-stopped-working/1527, it seems like a fix is already in nixops, and it worked for me when I updated to a newer nixops version.

**Comment by binaryphile** [comment]
I'm on a single-user nix install on ubuntu and getting the same error on nix deploy:

    error: value is null while a set was expected, at /nix/store/y5f3sd2cvir2h0psmc90zjbpcc2hzcmr-nixpkgs-19.03pre167327.11cf7d6e1ff/nixpkgs/pkgs/top-level/default.nix:63:5
