### ISSUE TITLE
google-chrome-stable segfaults on image upload

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#51870]
## Issue description

I installed `google-chrome` `Version 71.0.3578.80 (Official Build) (64-bit)`  (master), because google-chrome in 18.09 didn't work for another reason (it crashed on startup and the version in master was supposed to solve that), but when I tried to upload an image, I got an immediate segmentation fault.

### Steps to reproduce
Press Browse on https://imgur.com/upload.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.87, NixOS, 18.09.git.b352d47 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by srhb** [comment]
I cannot reproduce this on unstable. Maybe something is fishy with the dialog that pops up. I wonder if this is DE-specific. It looks like a GTK box.

**Comment by memberbetty** [comment]
It affects all Chromium based browsers, including opera. Any operation resulting in the display of a file dialog crashes. 

Firefox does not crash and shows a file dialog.

**Comment by memberbetty** [comment]
It looks like a null pointer dereference.

> [39113.163736] chrome[11002]: segfault at 0 ip 00007ff0ea0ba9fd sp 00007ffd748a81c8 error 6 in libc-2.27.so[7ff0e9f69000+1aa000]
> [40848.153486] opera[18375]: segfault at 0 ip 00007effeb66f9fd sp 00007fff82ed37b8 error 6 in libc-2.27.so[7effeb51e000+1aa000]
>

**Comment by memberbetty** [comment]
In `Version 72.0.3626.81 (Developer Build) (64-bit)` of chromium (not Google Chrome), it does work, but I see when I press the Browse button. 

> Gtk-Message: 17:34:03.414: GtkDialog mapped without a transient parent. This is discouraged.

In `Version 72.0.3626.81 (Official Build) (64-bit)` of Google Chrome it crashes.

Can someone share the exact setup they are using to run Google Chrome without such crashes?

**Comment by flokli** [comment]
@memberbetty can you try with 73.0.3683.27 (now in nixpkgs master and 18.09)?

**Comment by memberbetty** [comment]
@flokli Thanks for trying to help. Your instructions do not work on my system. 

In `configuration.nix`:
>  extra = import (
>         fetchTarball https://github.com/NixOS/nixpkgs/archive/master.tar.gz
>       ) {  config.allowUnfree = true; };
> 

and then
environment.systemPackages = [ <snip> extra.google-chrome <snip> ];
 
does not result in the version you said would exist. (I still get some version 72)

Am I doing something wrong?

**Comment by flokli** [comment]
you're right - I misread your text. I was referring to the chromium version bump on nixpkgs, which doesn't change anything with google-chrome obviously.

I'm currently running google-chrome-stable 72.0.3626.81 (from nixpkgs master) and didn't obsere such crashes.

Can you check if bumping google-chrome-stable to its latest version (72.0.3626.97) fixes it for you?

**Comment by memberbetty** [comment]
I can test things in `master`, but that version is not in master. 

I also tested this with just a simple xterm session and then chrome also crashes.

**Comment by memberbetty** [comment]
@flokli The most likely underlying bug is this one: https://gitlab.gnome.org/GNOME/glib/issues/1645. 

Do you know whether that is already fixed in any version of NixOS and whether Chrome dynamically links to that one?

**Comment by flokli** [comment]
@memberbetty upstream fixed this in glib 2.58.3.

nixpkgs master currently still is at 2.58.2, but the patch fixing that bug was applied in 462a6d32501b204944a9ef3f04a6d28f28c36cbc (from Jan 9)

nixpkgs 18.09 is at 2.56.0, the bug mentions it was introduced in 2.58.2.

Can you try if you can reproduce it on nixos-unstable?

**Comment by memberbetty** [comment]
I can now start `google-chrome-stable` on 18.09. I am closing this one.
