### ISSUE TITLE
remmina not usable as SSH client 

### ISSUE THREAD

**Issue by EASamuilov** [NixOS/nixpkgs#51897]
## Issue description
I am trying to use 'remmina' as a SSH client. 
But when I click "Create a new connection profile", there is no SSH plugin in the list of plugins.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.87, NixOS, 18.09.1642.f55c7cfa940 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1642.f55c7cfa940"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Shawn8901** [comment]
Hi,
i am new on nix and currently trying to setup a copy my current desktop in a vm with nix. 
so i came around this issue, as it got recently a label i hope that its not a nerco bump. 

Remmina is missing the ssh plugin as the compiler flags are disabling VTE.
See https://gitlab.com/Remmina/Remmina/-/blob/master/src/remmina_ssh_plugin.c#L41

So its needed to add vte as input for the build and change the build flag.

i did basically do the following override in my flake, which results in a remmina binary which is capable to be used as ssh client

```
{ prev, vte }:

prev.remmina.overrideAttrs (oldAttrs: rec {
  cmakeFlags = oldAttrs.cmakeFlags ++ [
    "-DWITH_VTE=ON"
  ];
  buildInputs = oldAttrs.buildInputs ++ [
    vte
  ];
})
```
Changing the default package should just need the import for vte, adding the buildInput and swich to `-DWITH_VTE=ON`.

Sadly i am not yet to familiar with the contributing rules here for a PR i am just dropping that comment.

Other distributions use remmina with SSH/VTE enabled (checked ubuntu on work machine and archlinux on private) and upstream advertise support as SSH client directly on the [page](https://remmina.org/remmina-features/) it sounds reasonable to activate it on default.

Current packaging includes `libssh` for SFTP support, which still gets enabled even when VTE is OFF.
