### ISSUE TITLE
kalarm cannot set alarms

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#51903]
## Issue description
KAlarm is a program that can be used to create a timed alarm. This feature does not work.

### Steps to reproduce
- Run `kalarm`
- Observe that the "New" button is greyed out/inactive.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.87, NixOS, 18.09.git.f55c7cf (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Works for me on NixOS 21.11.
