### ISSUE TITLE
GHC & LLVM versions

### ISSUE THREAD

**Issue by ip1981** [NixOS/nixpkgs#51952]
There are at least two places where llvmPackages defined: in compiler (ghc) definition
 and in per-compiler package configuration. They may be different by accident.

For example `self.llvmPackages` and `self.ghc.llvmPackages` may be different:
in https://github.com/NixOS/nixpkgs/blob/8e11a25d5f58bc40d90578f767140ae3bff3beaf/pkgs/development/haskell-modules/configuration-ghc-8.6.x.nix LLVM is set to version 5, while each GHC version has LLVM version defined in another place.

**Comment by sternenseemann** [comment]
This has been reduced to one place in d7ff8061beed.
