### ISSUE TITLE
NixOS 18.09: python.pkgs.pip 18.1 breaks pipenv before 2018.10.9

### ISSUE THREAD

**Issue by jameysharp** [NixOS/nixpkgs#51970]
Pip 18.1 was backported to release-18.09, but pipenv hasn't been upgraded past 2018.7.1, and pipenv versions before 2018.10.9 don't work with pip 18.1 or later. See pypa/pipenv#2924.

Please either backport current pipenv to release-18.09, or revert the backport of pip 18.1.

**Comment by dotlambda** [comment]
cc @FRidh who commited 1d61c41646bfd899683504bb9bdb81948173e9c6

**Comment by FRidh** [comment]
Yes, Python 3.7 support primarily. 

Packages should not depend on `pip` internals, but `pipenv` does. We could backport a newer version of it.

**Comment by davidak** [comment]
Current stable (NixOS 19.03) has pipenv 2018.11.26, so this issue should be fixed. (i get different issues)

**Comment by FRidh** [comment]
Old release so I am closing this.
