### ISSUE TITLE
GitLab does not pass gitlab:check

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#51982]
## Issue description

The NixOS GitLab service does not pass GitLab's `gitlab:check` application check rule. This rule must pass to receive support from GitLab.

### Steps to reproduce

Run:
```
nix run nixpkgs.gitlab -c sudo -u gitlab  gitlab-rake gitlab:check SANITIZE=true
```

A number of failures will be reported. These include:

* Numerous issues of the form:
```
3/2 ... wrong or missing hooks
  Try fixing it:
  sudo -u gitlab -H /nix/store/qx227lr5gya6f79v85fpbn2n98kqj2ah-gitlab-shell-8.4.1/bin/create-hooks /var/gitlab/state/repositories
  Check the hooks_path in config/gitlab.yml
  Check your gitlab-shell installation
  For more information see:
  doc/install/installation.md in section "GitLab Shell"
  Please fix the error above and rerun the checks.
```
Running the indicated command does not fix the issue.
* This:
```
Uploads directory tmp has correct permissions? ... no
  Try fixing it:
  sudo chown -R gitlab /var/gitlab/state/uploads
  sudo find /var/gitlab/state/uploads -type f -exec chmod 0644 {} \;
  sudo find /var/gitlab/state/uploads -type d -not -path /var/gitlab/state/uploads -exec chmod 0700 {} \;
  For more information see:
  doc/install/installation.md in section "GitLab"
  Please fix the error above and rerun the checks.
Init script exists? ... no
  Try fixing it:
  Install the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
Init script up-to-date? ... can't check because of previous errors
```
* `Redis version >= 2.8.0? ... no`
* `Ruby version >= 2.3.5 ? ... no`

## Technical details

 - system: `"aarch64-linux"`
 - host os: `Linux 4.14.76, NixOS, 19.03pre162412.6449501902c (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre162412.6449501902c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bgamari** [comment]
CC @fpletz @globin @krav

**Comment by krav** [comment]
I've been mostly able to reproduce this, but not seeing any errors in the form of "wrong or missing hooks". 

Hooks on my system is a symlink to the nix store, so I guess this is a case similar to `authorized_keys` where upgrading and garbage collection leads to a dead symlink.

The uploads permissions seems easy to fix, same with upgrading Redis and Ruby. Init scripts we don't have AFAIK, unless it refers to the systemd unit and the pre-start script?

I get an additional error, not sure what the "default" SSH configuration is:
```
Git user has default SSH configuration? ... no
  Try fixing it:
  mkdir ~/gitlab-check-backup-1545132645
  sudo mv /var/gitlab/state/home/.ssh/authorized_keys.bak2 ~/gitlab-check-backup-1545132645
  sudo mv /var/gitlab/state/home/.ssh/authorized_keys.bak ~/gitlab-check-backup-1545132645
  For more information see:
  doc/ssh/README.md in section "SSH on the GitLab server"
```

**Comment by flokli** [comment]
Gitlab probably doesn't officially support NixOS, even if we would pass this check.

If you really want to go down that path, best way forward might be to reach out to them, and see what their requirements for getting support on NixOS would be - there's not much we can change downstream at this time.
