### ISSUE TITLE
nixos/networkd: Blocking issues

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#5199]
I'm leaving this here so other developers are aware of the status of networkd work:
- Resolvconf integration is not ideal as systemd-resolved only triggers flatfile updates of `/run/systemd/resolve/resolv.conf`.
- SIT configuration in systemd is a bit lacking since networkd requires local addresses to be set.
- ~~The MTU and MACAddress cannot be set with the interface name alone.~~ This is handled by our scripts at the moment but it would be nice to see this in networkd.
- Ip addresses managed by networkd are not removed when doing a `nixos-rebuild switch`.
- Resolving myhostname is broken when using networkd.
- Networkd macvlan test is flaky.

**Comment by Profpatsch** [comment]
(triage) Have these problems been solved since you opened this issue?

**Comment by Profpatsch** [comment]
Closing since no reaction.
