### ISSUE TITLE
cmake fails to build without XCode installed

### ISSUE THREAD

**Issue by hesselink** [NixOS/nixpkgs#5206]
I only have the XCode command line tools installed, not XCode itself. This causes `cmake` to fail to build with

```
CMake Error at Modules/Platform/Darwin.cmake:211 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but CMAKE_OSX_SYSROOT:
 
   ""
 
  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
```

I've managed to build it by patching `Modules/Platform/Darwin.cmake` to unset `CMAKE_OSX_DEPLOYMENT_TARGET`. I've found a [similar issue on the macports trac](https://trac.macports.org/ticket/44581). They resorted to a [similar fix](https://trac.macports.org/changeset/127220): disabling the check if the deployment target wasn't explicitly set to something different from the current platform.

Should I make a pull request with that fix?

**Comment by Profpatsch** [comment]
(triage) @hesselink Do you still plan to create that PR? Or has it been fixed already?

**Comment by hesselink** [comment]
Sorry I didn't do this originally. I don't know if it's been fixed, and no longer have my patch either, so I'm afraid I won't be much help.

**Comment by Profpatsch** [comment]
Then we should close this issue, since it’s probably fixed by now (if it’s a dealbreaker on darwin). cc @jagajaga
