### ISSUE TITLE
Suggestion: add, to Firefox, a bookmark to a free web IRC client

### ISSUE THREAD

**Issue by fusion809** [NixOS/nixpkgs#52060]
## Issue description
Presently the NixOS live graphical image has Firefox, but no standalone IRC client. If users need help, but do not necessarily realize they can access a help IRC channel in their browser, they might get stuck. Plus, for those of us that already know there are web clients for IRC, it is still more convenient to be able to click on a bookmark to get there. 

Which IRC web client should Firefox bookmark to? Well, I personally use [KiwiIRC](https://kiwiirc.com/nextclient/), but as I was informed by srhb in the #nixos channel there is, in fact, an official web client for Freenode itself, here: https://webchat.freenode.net/, which seems more appropriate. 

As was also mentioned in #nixos, the channel itself requires users to be registered, but #nixos-unregistered for unregistered users is still better than nothing, IMO.

**Comment by fusion809** [comment]
Not sure what the "good-first-bug" label refers to, but this isn't my first bug in this repo: https://github.com/NixOS/nixpkgs/issues?utf8=%E2%9C%93&q=is%3Aissue+fusion809.

**Comment by jtojnar** [comment]
It means that it is a simple self-contained task that beginning contributors can tackle without much research.

**Comment by Synthetica9** [comment]
I think the freenode webchat would be the most "appropriate". However, if we want something a bit more full-featured, [IRCCloud](www.irccloud.com) might also be an option. 

That one is a bit more fully featured (I use it day-to-day), but it is also an external commercial party. However, other projects, such as [Idris](https://github.com/idris-lang/idris-dev#idris) also "endorse" it (by having a clickable invite button in their README.md)

**Comment by fusion809** [comment]
@Synthetica9 Ah, minor point but your IRCCloud link goes to the wrong place (https://github.com/NixOS/nixpkgs/issues/www.irccloud.com), so you may wish to remove the .../issues/ part of that link. 

Do most users really need all the features IRCCloud provides? KiwiIRC and Freenode's WebChat have more than enough features for me, at least. KiwiIRC is also open-source, if it matters.

**Comment by flokli** [comment]
Pointing to the freenode webchat seems to be most appropriate IMHO.

**Comment by davidak** [comment]
Wouldn't it be enough to just link to it on https://nixos.org/nixos/support.html?

**Comment by flokli** [comment]
Some work has already happened, and there's more work ongoing to improve the website and manual, to make these things better available.

Currently, the main website has a  "Community" tab, and that page a prominent green "Open Webchat" button. It's probably most sustainable in the long run to improve both website and documentation to better expose these channels, than adding more links to the installation ISO.
