### ISSUE TITLE
elm-format fails to install alongside elm (darwin)

### ISSUE THREAD

**Issue by robx** [NixOS/nixpkgs#52118]
## Issue description

Not sure whether this is darwin-specific. I cannot install `elm` next to `elm-format`, because both want link `/libHStransformers-compat-0.6.2-DR0vsQLKu2k3Tes0C8KQG1-ghc8.2.2.dylib`.

It seems wrong for either of the packages to link shared libraries. I suspect this is because e.g. `elm-format.nix` sets `isLibrary: true`. I'd be happy to submit a patch to change this, but there seems to be a stack of scripts that's meant to generate this that's too deep for me.

### Steps to reproduce

    nix-env -iA nixpkgs.elmPackages.elm
    nix-env -iA nixpkgs.elmPackages.elm-format

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(rob): `"nixpkgs-19.03pre161900.61c3169a0e1"`
 - nixpkgs: `/Users/rob/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Usually we need a ```justStaticExecutables``` for these to work currently. Not sure if that is currently possible? You can also set meta.priority to a different number for each (default is 5).

/cc @domenkozar @jerith666

**Comment by jerith666** [comment]
I think this must be darwin-specific; I have these packages happily coexisting alongside each other in `environment.systemPackages` on NixOS:

```
$ ls -l /run/current-system/sw/bin/elm*
lrwxrwxrwx 6 root root 62 Dec 31  1969 /run/current-system/sw/bin/elm -> /nix/store/cnl19cwicwlgnzf4fsprvs6z3rlfizmj-elm-0.19.0/bin/elm
lrwxrwxrwx 6 root root 75 Dec 31  1969 /run/current-system/sw/bin/elm-format -> /nix/store/v5dgvj1zms6h4yssg55mh3cvhlrwxpcd-elm-format-0.8.1/bin/elm-format
```

**Comment by robx** [comment]
Yes, looks darwin-specific, via https://github.com/NixOS/nixpkgs/blob/3504cfea6b0f6372df81bd62bb623fa0c3751a18/pkgs/development/haskell-modules/generic-builder.nix#L299

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/53326
