### ISSUE TITLE
clang on OSX doesn't output DWARF symbols like the one shipped with OSX

### ISSUE THREAD

**Issue by fghibellini** [NixOS/nixpkgs#52148]
## Issue description

clang installed through nix doesn't correctly output DWARF data.

### Steps to reproduce

```
$ cat > main.c <<EOF
#include <stdio.h>

int main() {
  printf("hello world");
}
EOF

$nix-shell -p clang --run 'clang --version'
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /nix/store/1vxvyrgjg869fh4makyzh7qjip96i1hv-clang-5.0.2/bin

$ nix-shell -p clang --run 'clang -g -o run main.c'
$ ls
main.c   run

$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ clang -g -o run main.c
$ ls
main.c   run   run.dSYM
```

## Technical details

- system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(fghibellini): `"nixpkgs-19.03pre160749.3a393eecafb, nixpkgs-darwin-18.09pre153120.8992f529d75"`
 - nixpkgs: `/Users/fghibellini/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
For reference, we use a dummy dsymutil script due to Apple not releasing the original source. This is found here:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/cctools/port.nix#L95-L100

and

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/binutils/default.nix#L30

.

llvm has its own version that should be available to us soon. I'm not sure which version it is first released in.

**Comment by fghibellini** [comment]
Thanks for the quick answer!

Based on https://stackoverflow.com/a/32299029 I would think dsymutil is supposed to be Apple specific.

Does the llvm release of dsymutil mean this (separate debug info linking) will become standard across operating systems or the llvm dsymutil is also supposed to be used only on OSX?

**Comment by matthewbauer** [comment]
dsymutil is for DWARF binaries only. I think OSX is the only place where those are used. You can do something similar on Linux with objcopy though:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/separate-debug-info.sh#L31

But this is a good reminder that we need to get the separate debug symbols to work on macos as well.
