### ISSUE TITLE
python3Packages.scrapy is broken

### ISSUE THREAD

**Issue by rasendubi** [NixOS/nixpkgs#52229]
## Issue description

python3Packages.scrapy fails to build on master. First failing commit is 
5db047243c92c92bfdbfe0933cedf49e5ec63120. 

### Steps to reproduce

```
nix-build -A python3Packages.scrapy
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.4, NixOS, 19.03.git.3a393eecafb (Koi)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/home/rasen/dotfiles/channels/nixpkgs`

/cc @FRidh

**Comment by marsam** [comment]
This is because the current Scrapy release (1.5.1) does not support python3.7; Scrapy master has python 3.7 support https://github.com/scrapy/scrapy/pull/3326; maybe you can ask upstream to make release

**Comment by rasendubi** [comment]
I should have paid more attention: it is actually `python3Packages.testfixtures` fails to build (scrapy fails because of a dependency failure).

I am not sure this is python 3.7 issue, as the bisected patch only updates pytest. (I have also tried applying https://github.com/Simplistix/testfixtures/pull/88 —that didn't help.)

**Comment by marsam** [comment]
python3Packages.testfixtures is failing because https://github.com/NixOS/nixpkgs/pull/51430 is not in master yet

**Comment by timokau** [comment]
Now in master.

**Comment by rasendubi** [comment]
`python3Packages.scrapy` is still broken. (Though, `python36Packages.scrapy` works.) Now because of python 3.7 support. scrapy/scrapy#3326 does not apply to the 3.5.1 release, so I have requested a release from upstream: https://github.com/scrapy/scrapy/issues/3539

**Comment by timokau** [comment]
It seems a little bit ridiculous to me that the 3.6->3.7 upgrade broke a couple of things. I wish they'd follow semver, but then again who knows how long it would take for anyone to adopt "python4".
