### ISSUE TITLE
sqlite: update release 18.09 to 3.26.0

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#52246]
SQLite < 3.26 is vulnerable to the [Magellan](https://blade.tencent.com/magellan/index_en.html) attack.

Release notes: https://www.sqlite.org/releaselog/3_26_0.html

**Comment by ckauhaus** [comment]
See also https://news.ycombinator.com/item?id=18685296 for discussion

**Comment by 7c6f434c** [comment]
`master` has it (I guess it was added when #51352 got merged), in #52141 there is a discussion whether `3.25.3` actually has enough of the fix. The expectation is to merge the bump unless someone raises a substantial obkection. (which is why I closed #52225 when I found out I missed #52141)

**Comment by obadz** [comment]
Dup;l

**Comment by obadz** [comment]
Closed with d683610
