### ISSUE TITLE
go: built-in cross compile not working for non-simple cases

### ISSUE THREAD

**Issue by jhillyerd** [NixOS/nixpkgs#52260]
## Issue description

Go has built-in cross-compilation support controlled via environment variables.

`GOOS=darwin GOARCH=amd64` and `GOOS=freebsd GOARCH=amd64` work fine for compiling hello world, but fail on more complex examples.

These builds succeed when running the pre-compiled go binaries from golang.org on Debian.

### Steps to reproduce

1. git clone https://github.com/jhillyerd/inbucket
2. cd inbucket
3. env GOOS=darwin GOARCH=amd64 go build ./cmd/inbucket

```
# os/user                                                                                                                                  
/nix/store/yh6p6ky7w2nfa64r3r7vhr5d5s1p87bk-go-1.11.2/share/go/src/os/user/getgrouplist_darwin.go: In function ‘mygetgrouplist’:           
/nix/store/yh6p6ky7w2nfa64r3r7vhr5d5s1p87bk-go-1.11.2/share/go/src/os/user/getgrouplist_darwin.go:16:11: warning: implicit declaration of function ‘getgrouplist’; did you mean ‘mygetgrouplist’? [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~
           mygetgrouplist
# net
/nix/store/yh6p6ky7w2nfa64r3r7vhr5d5s1p87bk-go-1.11.2/share/go/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
```

4. env GOOS=freebsd GOARCH=amd64 go build ./cmd/inbucket

```
# runtime/cgo                                                                                                                              
gcc_freebsd_amd64.c:7:10: fatal error: sys/signalvar.h: No such file or directory
 #include <sys/signalvar.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

## Technical details

 - system: `"x86_64-linux"`                                                                                                                
 - host os: `Linux 4.14.88, NixOS, 18.09.1676.7e88992a8c7 (Jellyfish)`                                                                     
 - multi-user?: `yes`                                                                                                                      
 - sandbox: `no`                                                                                                                           
 - version: `nix-env (Nix) 2.1.3`                                                                                                          
 - channels(root): `"nixos-18.09.1676.7e88992a8c7"`                                                                                        
 - channels(james): `""`                                                                                                                   
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jhillyerd** [comment]
This fails with `18.09` (go 1.11) and `master` (go 1.11.2)

**Comment by matthewbauer** [comment]
I am more surprised that this would work out of the box at all. You should have to provide the system headers. Does the prebuilt go ship with all of them?

**Comment by jhillyerd** [comment]
Does not appear to be the case:

```
$ tar tzf go1.11.4.linux-amd64.tar.gz |grep \\.h\$                                                                                        
go/misc/cgo/life/life.h                                                                                                                    
go/misc/cgo/test/gcc68255/c.h                                                                                                              
go/misc/cgo/test/issue20266/issue20266.h                                                                                                   
go/misc/cgo/test/issue26213/jni.h                                                                                                          
go/misc/cgo/test/issue4339.h                                                                                                               
go/misc/cgo/test/issue8331.h                                                                                                               
go/misc/cgo/testplugin/src/issue25756/plugin/life.h                                                                                        
go/misc/cgo/testsovar/cgoso_c.h                                                                                                            
go/misc/swig/callback/callback.h                                                                                                           
go/pkg/include/asm_ppc64x.h                                                                                                                
go/pkg/include/funcdata.h                                                                                                                  
go/pkg/include/textflag.h                                                                                                                  
go/src/debug/dwarf/testdata/line1.h                                                                                                        
go/src/debug/gosym/pclinetest.h                                                                                                            
go/src/runtime/asm_ppc64x.h                                                                                                                
go/src/runtime/cgo/libcgo.h                                                                                                                
go/src/runtime/cgo/libcgo_unix.h                                                                                                           
go/src/runtime/funcdata.h                                                                                                                  
go/src/runtime/go_tls.h                                                                                                                    
go/src/runtime/syscall_nacl.h                                                                                                              
go/src/runtime/textflag.h                                                                                                                  
go/src/runtime/tls_arm64.h                                                                                                                 
go/src/vendor/golang_org/x/crypto/curve25519/const_amd64.h
```

**Comment by jhillyerd** [comment]
Some hints here: https://dave.cheney.net/2015/03/03/cross-compilation-just-got-a-whole-lot-better-in-go-1-5

> In the second example, the go tool detects that all the dependencies of this program need to be built
> for the target platform before hello.go can be compiled and builds them, all the way back to the runtime
> package.

Using `env GOOS=darwin GOARCH=amd64 go build -v` on Debian, I can see it building much of the stdlib, including `os/user`.  That was running from https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz - so the prebuilt binaries don't include stdlib objects for other platforms.

**Comment by matthewbauer** [comment]
Ok that makes sense. I think it might be detecting that GOROOT is read only and not downloading anything more? This is definitely something we should figure out how to support.

**Comment by jhillyerd** [comment]
After more experimentation, this is expected if CGO is enabled during cross-compile build if you don't have the correct C cross-compiler installed:

https://github.com/golang/go/issues/22510

I need to experiment with debian some more to figure out if it's disabling CGO by default
