### ISSUE TITLE
Kodi: support aarch64

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#52263]
Seems like we need openjre to work on aarch64, which seems feasible: https://hub.docker.com/r/arm64v8/openjdk/

**Comment by bennofs** [comment]
I packaged adoptopenjdk binary for aarch64 builds in #52454.

**Comment by domenkozar** [comment]
Nice! That should be enough to get jre on aarch64 going?

**Comment by domenkozar** [comment]
also relevant https://github.com/NixOS/nixpkgs/pull/52534/files

**Comment by domenkozar** [comment]
2088ae10a312bd53cb6343e391dcf7368732c3af

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/52667
