### ISSUE TITLE
Package request: ballerina

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#52264]
[Ballerina](https://ballerina.io/) is a cloud-native programming language that makes it easy to write microservices that integrate APIs.

Source code available on GitHub here: https://github.com/ballerina-platform/ballerina-lang

Build dependencies: 
- Oracle JDK 8 or OpenJDK 8
- Maven 3.5.0 or later
- Node (v8.9.x) + npm (v5.6.0 or later)
- Docker

License: Apache 2.0

**Comment by pasviegas** [comment]
I am not a Nix expert, but this is what I personally use as my nix-shell for Ballerina.

I tried to follow the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ballerina.rb).
```nix
with import <nixpkgs> { };

let
  ballerina = stdenv.mkDerivation {
    name = "ballerina";

    src = fetchzip {
      url = "https://dist.ballerina.io/downloads/1.2.4/ballerina-1.2.4.zip";
      sha256 = "0lr0c7p2w04s9l48lhl39nz5s6fvq9ncq5l02jys7bx4mlqbca2z";
    };

    installPhase = ''
      # Make the output directory
      mkdir -p $out/bin

      # Remove windows files
      rm bin/*.bat

      # Copy the script there and make it executable
      cp -pR * $out
      chmod +x $out/bin/ballerina
    '';
  };
in mkShell { buildInputs = [ jdk8 ballerina ]; }
```
Hope this helps 😄

**Comment by JohnRTitor** [comment]
Added in #181319.
