### ISSUE TITLE
kernel panic booting 4.18 after crash 

### ISSUE THREAD

**Issue by DerSaidin** [NixOS/nixpkgs#52347]
## Issue description

Crashed (playing rocket league!), and had to hard reboot the system using the reset button.

Since crash, 4.18 kernel fails to boot (had booted several times before crash).
The boot does not reach the password prompt for the LUKS volume.

    ACPI BIOS Error (bug): Failure creating [\_SB.MACO], AE_ALREADY_EXISTS (20180531/dswload2-316
    ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20180531/psobject-221)

...timestamps jump to 0.2 seconds later ...

    AMD-Vi: Unable to write to IOMMU perf counter.
    Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
    CPU: 3 PID: 1 Comm: swapper/0 Not tainted 4.18.20 #1-NixOS
    Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./AB350 Pro4, BIOS P4.70 02/09/2018
    Call Trace:
     dump_stack+0x5c/0x7b
     panic+0xe4/0x242
     mount_block_root+0x27b/0x2ad
     ? set_debug_rodata+0x11/0x11
     prepare_namespace+0x160/0x196
     kernel_init_freeable+0x206/0x218
     ? rest_init+0xb0/0xb0
     kernel_init+0xa/0x111
     ret_from_fork+0x22/0x40
    Kernel Offset: 0x21a00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
    ---[ end Kernel panic - not syncing: VFS: Unableto mount root fs on unknown-block(0,0) ]---

Happily, my older 4.14 generation still boots fine.

    $ dosfsck -b /dev/sda1
    fsck.fat 4.1 (2017-01-24)
    0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
     Automatically removing dirty bit.
    Leaving filesystem unchanged.

    $ lsblk
    NAME                 MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
    sda                    8:0    0 465.8G  0 disk  
    ├─sda1                 8:1    0     1G  0 part  /boot
    └─sda2                 8:2    0 464.8G  0 part  
      └─root             254:0    0 464.8G  0 crypt 
        ├─nixos--vg-swap 254:1    0    16G  0 lvm   [SWAP]
        └─nixos--vg-root 254:2    0 448.8G  0 lvm   /

    $ df
    Filesystem     1K-blocks      Used Available Use% Mounted on
    devtmpfs          769676         0    769676   0% /dev
    tmpfs            7696732    125984   7570748   2% /dev/shm
    tmpfs            3848368      5452   3842916   1% /run
    tmpfs            7696732       432   7696300   1% /run/wrappers
    /dev/dm-2      462120824 131310692 307265916  30% /
    tmpfs            7696732         0   7696732   0% /sys/fs/cgroup
    /dev/sda1        1046512    177424    869088  17% /boot
    tmpfs            1539344         0   1539344   0% /run/user/175
    tmpfs            1539344        16   1539328   1% /run/user/1000

    $ mount | grep ^/dev
    /dev/mapper/nixos--vg-root on / type ext4 (rw,relatime,data=ordered)
    /dev/mapper/nixos--vg-root on /nix/store type ext4 (ro,relatime,data=ordered)
    /dev/sda1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

### Steps to reproduce

The crash seems to have put the disk in a weird state. No idea how to reproduce that.
Maybe try to setup the dirty bit thing?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

     - system: `"x86_64-linux"`
     - host os: `Linux 4.14.74, NixOS, 18.09.821.4dd9cd3f69e (Jellyfish)`
     - multi-user?: `yes`
     - sandbox: `yes`
     - version: `nix-env (Nix) 2.1.1`
     - channels(root): `"nixos-18.09.1676.7e88992a8c7"`
     - channels(myuser): `""`
     - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by DerSaidin** [comment]
Changing to 4.19 seems to have fixed this.

**Comment by FRidh** [comment]
4.19 is the new default, so closing.
