### ISSUE TITLE
package request: deepin-screenshot

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#52358]
## Issue description
It would be nice to have [deepin-screenshot](https://www.deepin.org/en/original/deepin-screenshot/) available for NixOS. I used to like it's cropping and editing capabilities a lot.

 - https://www.deepin.org/wp-content/uploads/2017/01/deepin-screenshot1.png
 - https://www.deepin.org/wp-content/uploads/2017/01/deepin-screenshot2.png

cc @romildo

**Comment by worldofpeace** [comment]
We have this now
