### ISSUE TITLE
Update Mono to 5.16

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#52438]
## Issue description
Mono is outdated.

### Steps to reproduce
Install mono.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

N/A

**Comment by jdanekrh** [comment]
This happened in https://github.com/NixOS/nixpkgs/commit/26e8258c41e46bcb22c9bf039d9d3fbd4581d0e4. Now we need to update to 5.18. That version of mono added some useful .NET 4.7.2 compatibility https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#bcl.

**Comment by JohnAZoidberg** [comment]
We've got `5.20.1.27` now, since ffc8ac2fad393182211f64ea8d9186ea9fe5b2ea.
