### ISSUE TITLE
aws-google-auth: secretstorage-3.1.0 not supported for interpreter python2.7

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#52445]
## Issue description
In a context where `pkgs` points to `master`, `pkgs.aws-google-auth` fails to build on my machine:

> secretstorage-3.1.0 not supported for interpreter python2.7

### Steps to reproduce
- Have a reference to master in your configuration.nix, 
- add `aws-google-auth` to environment.systemPackages
- `nixos-rebuild switch`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.87, NixOS, 18.09.git.7e88992 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fk-da** [comment]
backported in c595242ca9599279e0dfad84b62f53c7a965d558.

**Comment by flokli** [comment]
backported in c595242.
