### ISSUE TITLE
Use buildGoPackage for all go packages.

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#52469]
We should always use `buildGoPackage` for programs build with go for the following reason:

- we set GOOS and GOARCH, which is necessary for cross-compilation
- we remove references to the go compiler automatically
- it sets the GOPATH to a sane value, which avoids some manual boiler-code
- sets GOCACHE
- other fixes we might apply in future

There are still a some packages left that have `go` in its buildInputs and uses `stdenv.mkDerivation` (found by using `ag 'buildInputs.*=.*\[.* go .*\]'`)

- [x] openshift
- [x] cni
- [ ] dcrd
- [ ] dcrdwallet
- [ ] gitlab-shell
- [x] gitlab-workhorse
- [ ] docker
- [x] containerd
- [x] runc
- [ ] boringssl
- [x] localtime
- [ ] tmsu

Here some tips for migration. Many of these packages are using make for building.
It can be still used by overriding `buildPhase` like this:

```
goPackagePath = "github.com/<owner>/<project>";
buildPhase = ''
  cd "go/src/$goPackagePath"
  make
'';
installPhase = ''
  # copy the compiled binary here
'';
```

In future we should also support `make` out of the box in `buildGoPackage` to avoid the boiler-code mentioned here.
cc @vdemeester

**Comment by juaningan** [comment]
I think that this can be closed, buildGoModule is the new preferred way to build Go packages.

**Comment by Mic92** [comment]
Yes we want to switch to buildGoModule now.
