### ISSUE TITLE
aws-google-auth: U2F login unavailable

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#52471]
## Issue description
Even after #52445 is merged, 
starting aws-google-auth still returns:

> Failed to import U2F libraries, U2F login unavailable. Other methods can still continue.

### Steps to reproduce

`aws-google-auth`

## Technical details
Applies to a future version of `master` on NixOS.

**Comment by marsam** [comment]
you need to override the `withU2F` argument
```
pkgs.aws-google-auth.override { withU2F = true; }
```
