### ISSUE TITLE
ttyrec: open(fd, O_RDWR): Bad address

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#52491]
## Issue description

```
$ ttyrec 
open(fd, O_RDWR): Bad address
```

This problem was also mentioned earlier in https://github.com/NixOS/nixpkgs/issues/18460#issuecomment-245900775.

### Steps to reproduce

1. `nix run nixpkgs.ttyrec`
2. `ttyrec`

It's the same when you install it.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.87, NixOS, 18.09.1651.4f3446f2991 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1651.4f3446f2991, nixos-hardware, nixos-unstable-19.03pre162468.ad3e9191d16"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
I have read:

>ttyrec fails to properly record any terminal size other than 80x24 and it has issues with glitching

so i tried it in a terminal with that resolution, but still got the same problem. Seems like the tool is just too old.

```
[davidak@ethmoid:~]$ resize
COLUMNS=80;
LINES=24;
export COLUMNS LINES;

[davidak@ethmoid:~]$ ttyrec 
open(fd, O_RDWR): Bad address
```

**Comment by dtzWill** [comment]
May need some more investigation/touching up for use in nixpkgs proper,
but building it differently (modelled after either void or debian)
at least gets it to run for me without the mentioned error?

Might be worth a shot? If so we can sort out how to do this in master...

Debian patches version:
https://github.com/dtzWill/nixpkgs/blob/22f0dd07105a5f8961e22965a9eac0b9c354e057/pkgs/tools/misc/ttyrec/default.nix

And look at parent commit or two for less patch-intensive approach using
touchups used by void.

Hope this helps :)

~Will

**Comment by FliegendeWurst** [comment]
Works on 21.11.
