### ISSUE TITLE
libwacom udev rules missing

### ISSUE THREAD

**Issue by jigpu** [NixOS/nixpkgs#52490]
## Issue description
The libwacom sources include a `./tools/generate-udev-rules` script that produces udev rules for the devices contained in its database. The xf86-input-wacom driver expects these rules to be installed since they enable the "MatchIsTablet" predicate used in its [70-wacom.conf](https://github.com/linuxwacom/xf86-input-wacom/blob/master/conf/70-wacom.conf) configuration file to work properly. Without these rules present, the Xorg server may incorrectly categorize devices, such as described in https://github.com/linuxwacom/input-wacom/issues/58

See the ".spec" file inside the [libwacom src RPM](https://koji.fedoraproject.org/koji/buildinfo?buildID=1163488) or the "rules" file inside the [debian.tar.xz archive](https://packages.ubuntu.com/cosmic/libwacom-common) for how the "65-libwacom.rules" file is generated, installed, and packaged for Fedora and Ubuntu.

### Steps to reproduce
Based on the bug linked above, I believe the following should reproduce the issue.

1. Install NixOS
2. Connect a Wacom tablet with a "pad" device (e.g. Wacom Intuos Pro)
3. Run `xsetwacom list`
4. Observe that the "stylus" and "eraser" devices are listed, but not the "pad" device.

## Technical details
Not a NixOS user, so I don't have `nix-shell -p nix-info --run "nix-info -m"` results.

**Comment by jtojnar** [comment]
Apparently it needs to be generated manually in `postInstall`: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libwacom

And there might be some issue with cross-compilation, better do what glib does: https://github.com/NixOS/nixpkgs/pull/51824

**Comment by jigpu** [comment]
@jtojnar the udev rules are now automatically generated as part of the install process. Can you check if `65-libwacom.conf` gets properly installed as part of the current NixOS package?

**Comment by jigpu** [comment]
I *believe* this issue is resolved. I still have no idea how to use NixOS, but I see that a 65-libwacom.rules file can be found on the filesystem when the libwacom package is installed. Furthermore, adding `services.udev.packages = [ pkgs.libwacom ];` to my `/etc/nixos/configuration.nix` file and rebuilding / rebooting seems to be sufficient to to have udev actually read and process these rules (verified by checking that the `ID_INPUT_TABLET_PAD=1` is found in the output of `udevadm info -n <path to path device>`
