### ISSUE TITLE
Steam In-home-streaming has broken hardware decoding 

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#52496]
## Issue description
Steam ships with ffmpeg libraries (in `.local/share/Steam/ubuntu12_32/libav*`) that depend on `libva.so.1`. `libva.so.1` does not work on NixOS in its current form because when combined with `/run/opengl-driver-32/lib/dri`, the following happens:

```
ffmpeg verbose: Opened VA display via X11 display :0.
ffmpeg error: Failed to initialise VAAPI connectilibva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver-32/lib/dri/radeonsi_drv_video.so
libva error: /run/opengl-driver-32/lib/dri/radeonsi_drv_video.so has no function __vaDriverInit_0_32
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib32/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.4
```

`libva.so.1` tries to find the `__vaDriverInit_0_32` symbol in the driver.so and fails, as the mesa compilation that produced `radeonsi_drv_video.so` was compiled when libva with MAJOR=1 and MINOR=1 was in scope, resulting in a `__vaDriverInit_1_1` instead of the needed `__vaDriverInit_0_32`. The reason for this is `libva-minimal` being a [build input](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/mesa/default.nix#L152) to Mesa compilation instead of libva1-minimal. The logic for this madness is found [within Mesa](https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/state_trackers/va/Makefile.am#n32) and the `VA_DRIVER_INIT_FUNC` definition that steals the function name from the VA lib used for compilation.

### Steps to reproduce
Run steam and use in-home streaming. Turn on the in-home streaming diagnostics in the client steam settings and see that in the diagnostic you see the decoder library be "libavcodec software decoding". Also in the console of the steam invocation you will see the snippet above when starting to stream.

## Suggested fixes:
Instead pushing libva1 into the steam runtime, we should push an updated version of libav*.so in there that links against libva.so.2 not libva.so.1. In the overridePackages of runtime-wrapped.nix, including ffmpeg+libva instead of libva1 kind of works, when after starting Steam, you delete `$HOME/.local/share/Steam/ubuntu12_32/libav*`. Then starting streaming, and the streaming client picks up the updated libav*.so. However, on the next Steam restart, Steam detects missing files and reinstalls them. I have yet to find a way to make this permanent. And I have no idea how this affects other programs run in the context of the steam runtime.

**Comment by clefru** [comment]
Known issue: https://github.com/ValveSoftware/steam-for-linux/issues/5339

Failed attempts so far:
Set LD_LIBRARY_PATH to something with updated ffmpegs libs fails because steam.sh prepends .local/share/Steam/ubuntu12_32 to LD_LIBRARY_PATH giving the broken ffmpeg precedent. However, there is a steam debugger hook later than that in the steam.sh script. With a bit of trickery, I was able to do:
```
DEBUGGER=${writeScript "ld-setter.sh" ''
#!shell
export LD_LIBRARY_PATH=/path-with-ffmpeg-libs:$LD_LIBRARY_PATH
# this executes the steam binary
exec $*
''}
```
However, when I go and inspect /proc/$steambinarypid/environ, I see that /path-with-ffmpeg-libs is gone from LD_LIBRARY_PATH. I don't know how and when this gets reset.

**Comment by fidoboy** [comment]
Annoying issue. I can't get hardware decoding in Steam with Linux Mint 19 or latest Ubuntu cause this. Because it uses libva 2 and not the old libva library. There is no way to replace or install libva1 or libva-x11 into latest Linux distros and this is avoiding to get hardware decoding working

**Comment by Newk77** [comment]
could a symlink maybe work?
not sure though how to best do this

**Comment by davidak** [comment]
I also noticed this issue.

>There is no way to replace or install libva1 or libva-x11 into latest Linux distros

NixOS should make this easy. Or is a global install needed not just for steam?

**Comment by uvNikita** [comment]
@clefru I'm trying to get hardware decoding in steam streaming working, so I applied this patch to runtime-wrapped.nix as you suggected:

```patch
--- a/pkgs/games/steam/runtime-wrapped.nix
+++ b/pkgs/games/steam/runtime-wrapped.nix
@@ -8,7 +8,8 @@ let
     libpulseaudio
     alsaLib
     openalSoft
-    libva1
+    libva
+    ffmpeg
     libvdpau
     vulkan-loader
     gcc.cc.lib
```

Then I run `nix-build -A steam && ./result/bin/steam`, remove steam libraries `rm ~/.local/share/Steam/ubuntu12_32/libav*`, but I'm still getting this error in stdout:

```
ffmpeg verbose: Opened VA display via X11 display :0.
ffmpeg verbose: libva: VA-API version 1.4.0
ffmpeg verbose: libva: va_getDriverName() returns 0
ffmpeg verbose: libva: Trying to open /run/opengl-driver-32/lib/dri/i965_drv_video.so
ffmpeg verbose: libva: Trying to open /usr/lib/dri/i965_drv_video.so
ffmpeg verbose: libva: Trying to open /usr/lib32/dri/i965_drv_video.so
ffmpeg verbose: libva: va_openDriver() returns -1
ffmpeg error: Failed to initialise VAAPI connection: -1 (unknown libva error).
CVAAPIAccel: av_hwdevice_ctx_create() failed
libavcodec software decoding with 4 threads
```

Am I missing something?

**Comment by clefru** [comment]
@uvNikita: A bit more than that is required unfortunately. You have to launch steam and before you start streaming manually overwrite files in the steam-runtime directory (ubuntu12_32) with updated so files. Then launch steam streaming from the UI and this should work. Here is list of files that you need to replace with update versions:
```
+    ln -s /lib32/steam-runtime/lib/libavcodec*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libavutil*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libavresample*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libavformat*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libgpm*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libswscale*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libgmp*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libp11-kit*.so* /foo
+    ln -s /lib32/steam-runtime/lib/libvideo*.so* /foo
```
The fix will only be temporary and might screw up launching other games during that steam session. steam will also detect the changes on next launch and revert the modifications.

I do think the best strategy is to build a libva1 compatible compile of mesa.

Alternatively switch to parsec. I found it to work much better than steam streaming (no RX480 AMD encoding artefacts anymore, wohoo) and is available from my overlay here:
https://github.com/clefru/nur-packages/tree/master/pkgs/parsecgaming

**Comment by uvNikita** [comment]
Seems like the issue is finally fixed upstream: https://github.com/ValveSoftware/steam-for-linux/issues/5339#issuecomment-551350935.

**Comment by clefru** [comment]
This got fixed upstream.
