### ISSUE TITLE
geoclue fails to start "Failed to load configuration file 'etc/geoclue/geoclue.conf'"

### ISSUE THREAD

**Issue by wanderer** [NixOS/nixpkgs#52512]
## Issue description

geoclue fails to start "Failed to load configuration file 'etc/geoclue/geoclue.conf'"

```
Dec 19 01:49:38 b systemd[1]: Starting Location Lookup Service...
Dec 19 01:49:38 b .geoclue-wrappe[14819]: Failed to load configuration file 'etc/geoclue/geoclue.conf': No such file or directory
Dec 19 01:49:38 b systemd[1]: Started Location Lookup Service.
Dec 19 01:49:58 b .geoclue-wrappe[14819]: soup_message_new: assertion 'uri_string != NULL' failed
Dec 19 01:49:58 b .geoclue-wrappe[14819]: soup_message_set_request: assertion 'SOUP_IS_MESSAGE (msg)' failed
Dec 19 01:49:58 b systemd[1]: geoclue.service: Main process exited, code=killed, status=11/SEGV
Dec 19 01:49:58 b systemd[1]: geoclue.service: Failed with result 'signal'.
```

### Steps to reproduce

enabling geoclue2 vai ` services.localtime.enable = true;`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.88, NixOS, 19.03pre162671.44b02b52ea6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(null): `"nixos-19.03pre162412.6449501902c"`
 - channels(root): `"nixos-19.03pre162671.44b02b52ea6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
We will most likely need a patch like https://github.com/dtzWill/nixpkgs/blob/1b5de09e7f100b0413ef7e71827c6871e8295bc6/pkgs/os-specific/linux/firmware/fwupd/add-option-for-installation-sysconfdir.patch until meson supports setting different install options, see https://github.com/hughsie/fwupd/issues/800

**Comment by dtzWill** [comment]
I *think* I was able to fix this for geoclue2: https://github.com/dtzWill/nixpkgs/blob/eb3bc7f363dc56c6da4fa32769fb49554ac19cad/pkgs/development/libraries/geoclue/default.nix

I can't find how to get github to produce the diff I want easily, so here's the changes:

```diff
$ git diff origin/master --no-ext-diff -- pkgs/development/libraries/geoclue                              12:16:04 on 18-12-19
diff --git a/pkgs/development/libraries/geoclue/default.nix b/pkgs/development/libraries/geoclue/default.nix
index f2eeb9ae40b..c45c00ce146 100644
--- a/pkgs/development/libraries/geoclue/default.nix
+++ b/pkgs/development/libraries/geoclue/default.nix
@@ -35,7 +35,10 @@ stdenv.mkDerivation rec {
 
   mesonFlags = [
     "-Dsystemd-system-unit-dir=${placeholder "out"}/etc/systemd/system"
+    "-Dintrospection=true"
+    "-Dgtk-doc=true"
     "-Ddemo-agent=${if withDemoAgent then "true" else "false"}"
+    "-Dsysconfdir=${placeholder "out"}/etc"
   ] ++ optionals stdenv.isDarwin [
     "-D3g-source=false"
     "-Dcdma-source=false"
```

But I presently have it disabled and testing it is blocked on big rebuild :).

Might be worth a try if it's a quick test, otherwise maybe I was just trying to fix it and failed and that's why no PR ;).

**Comment by jtojnar** [comment]
This suffers the same issue fwupd did: only the bundled config is used, not the one created by NixOS module.

**Comment by dtzWill** [comment]
Ah, okay.  Darn. Thanks :).

**Comment by worldofpeace** [comment]
> This suffers the same issue fwupd did: only the bundled config is used, not the one created by NixOS module.

The [NixOS module](https://github.com/NixOS/nixpkgs/blob/65dfc2b272819760f7c7adf848ccff36390c0425/nixos/modules/services/desktops/geoclue2.nix#L43) doesn't create a config file yet, so that change should be fine.
