### ISSUE TITLE
azure-mgmt-* packages don't build

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#52547]
## Issue description

I've already worked through the update, but let's revert for now, because the newer `azure-mgmt-*` packages also break `nixops`.

cc @olcai @FRidh 

### Steps to reproduce

```
$ nix-build <nixpkgs> -A pythonPackages.azure-mgmt-storage
...
configuring
sed: can't read azure/mgmt/storage/storagemanagement.py: No such file or directory
...
```

**Comment by bendlas** [comment]
`nox-review` shows `nixops` and `nixopsUnstable` as the only dependencies, so I went ahead and pushed those reverts. I'll submit the updates as a separate PR.

**Comment by bendlas** [comment]
https://hydra.nixos.org/build/89652010 et al

**Comment by bendlas** [comment]
fixed and backported to 19.03

**Comment by ocharles** [comment]
I'm not convinced this is fixed in 19.03:

```
nix-build -E '(import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs-channels/archive/5c52b25283a6cccca443ffb7a358de6fe14b4a81.tar.gz") {}).pythonPackages.azure-mgmt-storage'

these derivations will be built:
  /nix/store/6vq212gk8fgg7nhdirz08yi4kxx1qgrd-python2.7-azure-mgmt-storage-3.1.1.drv
building '/nix/store/6vq212gk8fgg7nhdirz08yi4kxx1qgrd-python2.7-azure-mgmt-storage-3.1.1.drv'...
unpacking sources
unpacking source archive /nix/store/59g39l0hp98b0hvicad16fgx2rjfpcax-azure-mgmt-storage-3.1.1.zip
source root is azure-mgmt-storage-3.1.1
setting SOURCE_DATE_EPOCH to timestamp 1546468640 of file azure-mgmt-storage-3.1.1/setup.cfg
patching sources
configuring
sed: can't read azure/mgmt/storage/storagemanagement.py: No such file or directory
builder for '/nix/store/6vq212gk8fgg7nhdirz08yi4kxx1qgrd-python2.7-azure-mgmt-storage-3.1.1.drv' failed with exit code 2
error: build of '/nix/store/6vq212gk8fgg7nhdirz08yi4kxx1qgrd-python2.7-azure-mgmt-storage-3.1.1.drv' failed
```

5c52b25283a6cccca443ffb7a358de6fe14b4a81 is (as far as I can see) the latest 19.03 channel revision.

**Comment by asymmetric** [comment]
@ocharles hasn't landed in the channel yet: https://github.com/NixOS/nixpkgs/blob/5c52b25283a6cccca443ffb7a358de6fe14b4a81/pkgs/development/python-modules/azure-mgmt-storage/default.nix#L18-L22

**Comment by ocharles** [comment]
Thanks, I did have a look at some files and could see some of the above commits had been cherry picked. I'm also surprised that it hasn't hit the channel despite being merged over a month ago?

**Comment by asymmetric** [comment]
I'm also confused, given how https://github.com/NixOS/nixpkgs/commit/5c52b25283a6cccca443ffb7a358de6fe14b4a81 is 6 days old and is in the channel.
