### ISSUE TITLE
strongswan: doesn't build on master

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#52552]
## Issue description

https://hydra.nixos.org/build/86067092

This is addressed on staging by https://github.com/NixOS/nixpkgs/pull/51787 which doesn't seem appropriate for master due to the amount of rebuilds.

The build failure is blocking two tests on the `nixos-unstable` channel.

### Steps to reproduce

```
$ nix-build -A strongswan
```

## Technical details

master

**Comment by hedning** [comment]
There's also https://github.com/NixOS/nixpkgs/pull/51767 which turns on `pruneLibtoolFiles` by default, preventing these problems more generally (would also have to go through staging of course).

Hydra has almost nothing to do at the moment though https://hydra.nixos.org/queue-summary, so we should probably start up staging-next again.
