### ISSUE TITLE
calibre fails to build

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#52586]
## Issue description

The calibre build is currently (since the latest staging merge) [failing](https://hydra.nixos.org/build/86100027). I'm looking into it.

**Comment by timokau** [comment]
For reference, talking about this staging merge: https://github.com/NixOS/nixpkgs/pull/51444

**Comment by FRidh** [comment]
See #52613

**Comment by dotlambda** [comment]
It works again: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.calibre.x86_64-linux.
