### ISSUE TITLE
Rely on swap.target in tests once upstream bug in systemd is fixed

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#5258]
https://bugs.freedesktop.org/show_bug.cgi?id=86930

For discussion see #5202

**Comment by domenkozar** [comment]
Should be fixed as part of systemd upgrade, see #6671

**Comment by thoughtpolice** [comment]
systemd isn't making it this round; punting

**Comment by Mathnerd314** [comment]
It looks like this refers to [this line](https://github.com/NixOS/nixpkgs/blob/82af770fa6d3a6aa83eaf4fc5ef3b083401921f8/nixos/tests/installer.nix#L106); can someone uncomment it and test?
