### ISSUE TITLE
pdfjs doesn't work in qutebrowser

### ISSUE THREAD

**Issue by wedens** [NixOS/nixpkgs#52615]
## Issue description

pdf.js doesn't work in qutebrowser from unsable and 18.09 channels.

Looks like it expects pdf.js in  ` /nix/store/xd5zhx5dgcmkkqa9d3bfk9645f6wdlr9-pdfjs-1.10.100/`, but in reality it's located in `/nix/store/xd5zhx5dgcmkkqa9d3bfk9645f6wdlr9-pdfjs-1.10.100/brx1q7i84n9yzchl2yj8yz4r07862ann-source/`.

I don't know nix enough to understand where this `brx1q7i84n9yzchl2yj8yz4r07862ann-source` comes from.

### Steps to reproduce

- Install `qutebrowser`
- Run it
- type `:version`
- pdf.js support is not there

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.89, NixOS, 18.09.1763.fbb7dbdb95d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1763.fbb7dbdb95d, unstable-19.03pre162671.44b02b52ea6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

/cc @rnhmjoj  Looks like you were the latest person who touched related code https://github.com/NixOS/nixpkgs/commit/25b70085204e4324b7dc8e712735291cd6cf81ab :)

**Comment by wedens** [comment]
Just to improve my nix knowledge, how do I overwrite derivation specified in `let` in my config? https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/qutebrowser/default.nix#L13

**Comment by erictapen** [comment]
Thanks for investigating, this bugged me for quite a while.

With #52623 I still can't view PDFs in qutebrowser, but at least it is mentioned in `:version`:
```
...
pdf.js: 1.10.100 (/nix/store/y9g1nxinxlmwckaicm4vh2wi1qmmyk3l-pdfjs-1.10.100/build/pdf.js)
...
```

When enabling pdf.js support in the browser with `:set content.pdfjs true`, I get the warning `The content.pdfjs setting is not available with the QtWebEngine backend!`.

When starting qutebrowser with `--backend webkit` and `content.pdfjs` enabled, I can open PDF files, but it is shown totally broken (no CSS).

**Comment by erictapen** [comment]
> Just to improve my nix knowledge, how do I overwrite derivation specified in `let` in my config? https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/qutebrowser/default.nix#L13

I don't think you can do that…

**Comment by wedens** [comment]
> When enabling pdf.js support in the browser with :set content.pdfjs true, I get the warning The content.pdfjs setting is not available with the QtWebEngine backend!.

I also have qutebrowser 1.5.2 installed on Arch and pdfjs works with webengine without additional settings.

Which qutebrowser version do you use?

**Comment by erictapen** [comment]
@rnhmjoj It is fixed in `1.5.0`: https://github.com/qutebrowser/qutebrowser/issues/2330

**Comment by rnhmjoj** [comment]
Ah, nice to hear that.

**Comment by erictapen** [comment]
I just tested #52623 on `master` and it seems to work, even with the default backend. I'm able to view PDF files and they look good. I have no idea what is the problem on `nixos-18.09` though.

The simplest solution would probably be to backport the qutebrowser bumps to `nixos-18.09`. I won't invest any more time into fixing pdf.js on the old Qutebrowser version. Will remove the WIP label from the PR now.

I think my fix should still be backported, as it doesn't make the situation worse and it fixes a download link.

**Comment by veprbl** [comment]
This is now fixed on master, still a problem on release-18.09.

**Comment by tex** [comment]
Tried on master and confirm it works as expected.

**Comment by wedens** [comment]
Closing as fixed.
