### ISSUE TITLE
matrix-synapse wants prometheus-client < 0.4.0, we have 0.4.2 on master branch

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#52621]
## Issue description

The freshest currently released upstream Matrix Synapse version is 0.34.0 (we have 0.33.9), and it still wants `prometheus-client` with version `<0.4.0`. We currently have exactly one version of `pythonPackages.prometheus_client`, and it is `0.4.2`. What would be the best way for updating `matrix-synapse`? A privately cloned `prometheus-client` expression (which will probably then fall even more out of date than needed, but Matrix seems to still support quite old versions anyway)? Or should I try to remove the constraint and see if something clearly breaks?

@FRidh I am not fully sure from reading NixOS/RFCs#24 which option is better.

### Steps to reproduce

`nix build matrix-synapse`

**Comment by bachp** [comment]
There is already in issue on the synapse repository https://github.com/matrix-org/synapse/issues/4221

**Comment by 7c6f434c** [comment]
Oh well, I guess it replaces the second option «with break the pin and get breakage», so for this specific case there is a natural choice. Thanks.

**Comment by bachp** [comment]
@7c6f434c Will you come up with a PR to fix this issue?

**Comment by 7c6f434c** [comment]
No.

**Comment by 7c6f434c** [comment]
https://github.com/NixOS/nixpkgs/commit/35efbedce4cddd6d155fae30e33b023bdf4f11da and its parent must have been pushed before your comment…
