### ISSUE TITLE
ath10k WLAN broken on 18.09 between Dec 17 and Dec 21

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#52644]
## Issue description

After updating to 18.09.1777.8c6ab3c72f3 and rebooting into that generation, my wlan adapater is gone.
Symptoms:
# journalctl -b | fgrep ath10k
Linux yuna 4.14.89 #1-NixOS SMP Mon Dec 17 08:28:56 UTC 2018 x86_64 GNU/Linux
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: enabling device (0000 -> 0002)
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/pre-cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: qca9377 hw1.1 target 0x05020001 chip_id 0x003821ff sub 17aa:0901
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: kconfig debug 0 debugfs 0 tracing 0 dfs 0 testmode 0
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: firmware ver WLAN.TF.2.1-00021-QCARMSWP-1 api 6 features wowlan,ignore-otp crc32 42e41877
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: unable to read from the device
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: could not execute otp for board id check: -110
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: failed to get board id from otp: -110
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: could not probe fw (-110)

Booting back into the old generation yields a different output:
Dez 21 22:24:34 yuna kernel: ath10k_pci 0000:05:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/pre-cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/QCA9377/hw1.0/firmware-6.bin failed with error -2
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: qca9377 hw1.1 target 0x05020001 chip_id 0x003821ff sub 17aa:0901
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: kconfig debug 0 debugfs 0 tracing 0 dfs 0 testmode 0
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: firmware ver WLAN.TF.1.0-00002-QCATFSWPZ-5 api 5 features ignore-otp crc32 c3e0d04f
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: board_file api 2 bmi_id N/A crc32 8aedfa4a
Dez 21 22:24:36 yuna kernel: ath10k_pci 0000:05:00.0: htt-ver 3.44 wmi-op 4 htt-op 3 cal otp max-sta 32 raw 0 hwcrypto 1
Dez 21 22:24:36 yuna kernel: ath10k_pci 0000:05:00.0 wlp5s0: renamed from wlan0

Note the different API version.

### Steps to reproduce

Use affected hardware and update to affected 18.09 version.

## Technical details

I'm testing with the update to firmware-linux-nonfree reverted and will report.

**Comment by tokudan** [comment]
I had to revert fbb7dbdb95d04f1517ec8011a3332a8c4c0e86e6 and 7cf770ca93cad1b3c3bb464fd4e58db79419ac25.

**Comment by tokudan** [comment]
Seems to be this debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903437
In short: The new package is currently unusable for my system.

**Comment by dtzWill** [comment]
D'oh, sorry.  FWIW seems to work for my QCA6174, bummer broke QCA9377 :(.

**Comment by tokudan** [comment]
@dtzWill No hard feelings from me, updating things in general is good and NixOS allows a quick and fast undo :)

**Comment by dbwest** [comment]
This is impacting me as well.

**Comment by fpletz** [comment]
Seems a recent `linuxFirmwareNonfree` should fix that issue according to the Debian bug. Since we have at least that version on 19.03 and we're not maintaining 18.09 anymore I think we can close this.
