### ISSUE TITLE
GitLab does not include Rails console (gitlab-rails)

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#52656]
## Issue description

`gitlab-rails` is not exposed in `gitlab` derivation. This is important for [debuggability](https://docs.gitlab.com/ee/administration/troubleshooting/debug.html).

### Steps to reproduce

`nix run nixpkgs.gitlab -c gitlab-rails`. Find that the tool is not installed.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 19.03pre162671.44b02b52ea6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre162671.44b02b52ea6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by srhb** [comment]
I think this was fixed (by you) in https://github.com/NixOS/nixpkgs/pull/58284 :)
