### ISSUE TITLE
solaar: permissions error

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#52651]
## Issue description

Running [Solaar](https://nixos.org/nixos/packages.html#solaar) (to configure a [Logitech Unifying receiver](https://en.wikipedia.org/wiki/Logitech_Unifying_receiver)) produces a message:

> **Permissions error**
> 
> Found a Logitech Receiver (/dev/hidraw0), but did not have permission to open it.
> 
> If you've just installed Solaar, try removing the receiver and plugging it back in.

![solaar permissions error](https://user-images.githubusercontent.com/712698/50367256-3a620a80-057f-11e9-9ea0-6cb7f3068f63.png)

Removing and plugging the USB receiver back in does not help.

### Steps to reproduce

Install Solaar, plug in a Logitech Unifying receiver, run Solaar.

## Technical details

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.10, NixOS, 18.09.1763.fbb7dbdb95d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3238.e984f9e48e1"`
 - channels(root): `"nixos-18.09.1763.fbb7dbdb95d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ysndr** [comment]
Have you tried including the `logitech-udev-rules` package? This should make the USB hardware available to you.

**Comment by alexeymuranov** [comment]
Thanks for the idea, but i do not have the USB receiver with me now. I will try to test it when i have it.

**Comment by alexeymuranov** [comment]
@ysndr, how should i include it exactly?

**Comment by alexeymuranov** [comment]
The problem was solved by configuring
```nix
{ # ...
  hardware.logitech.enable = true;
  hardware.logitech.enableGraphical = true; # for solaar to be included
}
```
thanks @ysndr.

This issue can either be closed or marked as a documentation issue IMO.
