### ISSUE TITLE
Networking support in initrd

### ISSUE THREAD

**Issue by ehmry** [NixOS/nixpkgs#5265]
The initrd needs to initializing networking if there are network filesystems in 'boot.initrd.supportedFilesystems'.

If you look at some of the filesystem tasks it would look like they should work in the initrd, but alas it is not so.
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/filesystems/cifs.nix
I propose that these fs's flip an option like boot.initrd.networking.enable.

I've been able to configure the network in stage-1 with busybox and dhcp, but it could get messy if there is a static configuration, because during stage-1 because the interfaces haven't been renamed. The other thing that needs to be done is to include modules for hardware drivers, I'm not sure which drivers should be included at minimum but I could look at knoppix or systemrescuecd and see what they do. 

@lethalman would systemd in the initrd take care of networking?

**Comment by dezgeg** [comment]
This has been implemented in current NixOS unstable.

**Comment by grahamc** [comment]
Let's close this, since it was implemented at https://github.com/NixOS/nixpkgs/pull/10460.
