### ISSUE TITLE
suitesparse build failed on hydra (transiently)

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#52709]
## Issue description

Currently the suitesparse build on hydra is [failing](https://hydra.nixos.org/build/86145157). I cannot reproduce that failure locally.

**Comment by timokau** [comment]
CC @ttuegel

**Comment by timokau** [comment]
The log asks us to "Please submit a full bug report", but I don't see where such a report should be posted.

**Comment by timokau** [comment]
Here is a backup of the log since hydra overwrote it when the build was restarted: http://sprunge.us/iIoGnq

**Comment by ttuegel** [comment]
The full error message is:
```
[ 89%] Building C object CMakeFiles/graphblas_static.dir/Source/Generated/GB_AxB__times_isle_uint8.c.o
/build/SuiteSparse/GraphBLAS/Source/Generated/GB_AxB__times_isle_uint8.c: In function 'GB_AdotB__times_isle_uint8':
/build/SuiteSparse/GraphBLAS/Source/Generated/GB_AxB__times_isle_uint8.c:457:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```
So, GCC is asking for the bug report because the compiler has segfaulted. I don't think that's warranted here; it's probably a problem with Hydra.

**Comment by timokau** [comment]
Oh I didn't realize that error message was generated by gcc itself. What makes you think its a hydra issue?

**Comment by timokau** [comment]
This just happened again: https://hydra.nixos.org/build/86534672

**Comment by timokau** [comment]
Similar looking issue: https://github.com/JuliaLang/julia/issues/20123

I'm currently building suitesparse in a loop, trying to reproduce the issue. There is also a 5.4.0 release that has "GraphBLAS 2.2.2: many upgrades and new features, a few bug fixes" in its changelog. Maybe that'll fix it.

**Comment by timokau** [comment]
Worth noting that both instances of the failure occurred on the packet-epyc-1 machine.

**Comment by timokau** [comment]
For reference: https://logs.nix.samueldr.com/nixos-dev/2018-12-31#1835680;

Summary:
- failure is not reproducible on that machine
- plenty of ram

I'm upgrading suitesparse in #53128, maybe we get lucky.

**Comment by timokau** [comment]
The suitesparse build immediately failed again after the update. On the same machine.

https://hydra.nixos.org/build/86610012

**Comment by timokau** [comment]
It has been a while since I've seen a failure, I'm assuming this is resolved.
