### ISSUE TITLE
dockerTools.buildImageWithNixDb fails due to wrong permissions 

### ISSUE THREAD

**Issue by dgarzon** [NixOS/nixpkgs#52713]
## Issue description
When building a Docker image with `dockerTools.buildImageWithNixDb` it fails with the following error:
```
Generating the nix database...
Warning: only the database of the deepest Nix layer is loaded.
         If you want to use nix commands in the container, it would
         be better to only have one layer that contains a nix store.
error: creating directory '/tmp/nix-build-docker-layer-my-image.drv-0/layer/nix/store': Permission denied
```

### Steps to reproduce
```
dockerTools.buildImageWithNixDb {
  name     = project.name;
  tag      = project.version;
  created  = "now";
  contents = [
    bash
    binutils
    bootstrap
    cacert
    coreutils
    direnv
    docker
    findutils
    gnugrep
    gnused
    nix
    openssh
    rsyslog
    shadow
    tree
    utillinux
    which
  ] ++ cache;

  config = {
    Cmd     = [ "${bash}/bin/bash" "-c" "${bootstrap}/bin/bootstrap" ];
    Volumes = {
      "/var/lib/docker" = {};
    };
  };
}
```
Where `cache` is a list of derivation paths (~150). If I remove the `++ cache` the image builds as expected, so I am struggling to understand why concatenating a list of paths will result in the aforementioned error.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.93-linuxkit-aufs`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.2`
 - nixpkgs: `/nix/store/ml2yq4cj4n234bp7srawm674b93sak4i-nixpkgs-unstable-2018-09-21`
```

**Comment by nlewo** [comment]
I don't think it's due to concatenation.
Could you try to isolate the element in your `cache` list which is responsible of this error?
It would be nice if we could reproduce your issue.

**Comment by purefn** [comment]
@dgarzon did you find a fix for this issue? I am encountering the same error and I've tried finding a single derivation in `contents` that appears to cause the issue, but there doesn't seem to be one. I'm having a hard time pinning down what the possible cause and solution might be.

**Comment by shism2** [comment]
same problm here
