### ISSUE TITLE
plasma5: quick launch cannot execute anything

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#52739]
## Issue description
Open quicklaunch and typing e.g. firefox or even a complete path to a binary and pressing enter does not result in a program being started. This is not specific to firefox. 

### Steps to reproduce
On the system of a colleague it doesn't happen, so I don't know.

## Technical details
NixOS running nixpkgs nixos-18.09 release channel.

**Comment by peterhoeg** [comment]
Did you try this on 19.03?

**Comment by memberbetty** [comment]
On 19.03 it works.
