### ISSUE TITLE
perf-tools execsnoop does not work with 4.19 kernels

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#52752]
## Issue description

`execsnoop` appears to work with 4.14 kernels, but not with 4.19 kernels.

With `boot.kernelPackages = pkgs.linuxPackages_4_14;`, it works:

```
[root@nixos:~]$ nix-env -f ~/nixpkgs -iA perf-tools
replacing old 'perf-tools-20171219'
installing 'perf-tools-20171219'

[root@nixos:~]$ uname -a
Linux nixos 4.14.90 #1-NixOS SMP Fri Dec 21 13:13:19 UTC 2018 x86_64 GNU/Linux

[root@nixos:~]$ execsnoop
Tracing exec()s. Ctrl-C to end.
Instrumenting sys_execve
   PID   PPID ARGS
   840    836 gawk -v o=1 -v opt_name=0 -v name= -v opt_duration=0 [...]
   841    839 cat -v trace_pipe
```

With `boot.kernelPackages = pkgs.linuxPackages_4_19;`, it does not:

```
[root@nixos:~]$ nix-env -f ~/nixpkgs -iA perf-tools
replacing old 'perf-tools-20171219'
installing 'perf-tools-20171219'

[root@nixos:~]$ uname -a
Linux nixos 4.19.12 #1-NixOS SMP Fri Dec 21 13:15:25 UTC 2018 x86_64 GNU/Linux

[root@nixos:~]$ execsnoop
Tracing exec()s. Ctrl-C to end.
Instrumenting do_execve
   PID   PPID ARGS
```

(nothing is ever shown after the column headers, even when starting new processes)

### Steps to reproduce

1. Set `boot.kernelPackages = pkgs.linuxPackages_4_19;` in config

2. `nixos-rebuild switch --upgrade`

3. Reboot

4. Install `perf-tools`

5. Run `execsnoop` and observe nothing after the column headers

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 19.03.git.913aa6b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6340_71786cd4`
 - channels(root): `""`
 - nixpkgs: `/root/nixpkgs`

**Comment by Emantor** [comment]
Closing this for now, please comment if this reproduces on the latest stable kernel.
