### ISSUE TITLE
FR: Nextcloud: add more configurable options

### ISSUE THREAD

**Issue by ZoomRmc** [NixOS/nixpkgs#52764]
## Issue description
Nextcloud service config is too restrictive and doesn't allow migrating from existing manually set-up nextcloud instance.

- Nextcloud service doesn't allow usage with different servers, such as Caddy.
- User and Group used for nextcloud data are hardcoded, so a user can't integrate existing server setup.
- Data directory path is hardcoded and fixed inside nextcloud home directory.

Ping @Ma27 @globin

**Comment by Ma27** [comment]
There are indeed several cases including migration from a manually set up instance that are rather hard to cover. Unfortunately I lack time to start (another) big task right now, but if you want to file a patch (for one or all bullet points), feel free to ping me :)

**Comment by flokli** [comment]
This issue contains at least three different things, some only useful when initially migrating over.

I propose filing individual issues, so they're actionable - but as @Ma27 mentions, he probably won't be able to work on these, so contributions welcome :-)

**Comment by ZoomRmc** [comment]
I don't see what's not actionable about the FR. This is a regular tracking issue, describing a set of real problems stemming from the poor usability of Nextcloud service. Individual PR/issues may be linked here and acted upon. I don't mind spamming Issues with separate issues instead though, if you'd rather.

This inherently has nothing to do with migrating, by the way, just inflexibility with integrating into existing set-up.

**Comment by flokli** [comment]
The issue regarding being able to use it with different servers in front is probably best covered in https://github.com/NixOS/nixpkgs/issues/22067, as it's not nextcloud-specific at all.

The part of "initially migrating over" was mostly about the configurable system user and data directory location:
I don't think there's that many valid usecases of explicitly needing to configure this differently when creating a new instance - and existing installations can just be chowned and data be moved/mounted to the default location - which is probably simpler than increasing complexity in the module (and maybe a reason why no-one else did implement this so far).
If you have a different opinion, it's probably best to create a new issue/PR specific to that.

**Comment by ZoomRmc** [comment]
I generally agree, and thanks for the link. Although, data directory being hardcoded is not how most of the services in NixOS are implemented, so I see it as a genuine issue, so I'll probably create a PR/issue for this.
