### ISSUE TITLE
Backport python 3.6.8 and 3.7.2 to 18.09

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#52821]
## Issue description

741e00fd1051bf119c13704abaadc46f046baabf
552d8a70d4c47a6e52a8e0b26e3a2e33d5b94ca6

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by marsam** [comment]
python3 fixes https://github.com/NixOS/nixpkgs/pull/52941

**Comment by FRidh** [comment]
Backported fixes as well.

**Comment by vcunat** [comment]
> It's annoying not being able to test

As member you should be able to trigger darwin builds from @GrahamcOfBorg (appearing in the checks tab now).  It's not much testing usually and it won't manage most staging stuff, but it's something at least.
