### ISSUE TITLE
gfortran package unexpectedly also contains gcc, and g++

### ISSUE THREAD

**Issue by aherrmann** [NixOS/nixpkgs#5287]
[`gfortran`](https://github.com/NixOS/nixpkgs/blob/9768adaf1e91e223bf4f3b1a107463c758dff1c8/pkgs/top-level/all-packages.nix#L3199) is defined as an override of gcc with the following arguments:

```
langFortran = true;
langCC = false;
langC = false;
```

These are translated to entries in the configure flag `--enable-languages` of [gcc](https://github.com/NixOS/nixpkgs/blob/a0f3faf34e6b2f024ef86d84ad80c124c33b941a/pkgs/development/compilers/gcc/4.8/default.nix#L343). According to the gcc [documentation](https://gcc.gnu.org/install/configure.html) only compilers for languages in that list should be build. However, looking at the result of `nix-build -A gfortran '<nixpkgs>'` I find that not only Fortran, but also C, and C++ compilers are being built. If I check the `configureFlags` variable in a `nix-shell` then I find `--enable-languages=fortran` as expected.

The same is true if I define `gfortran49` as follows and build it.

```
  gfortran49 = wrapGCC (gcc49.gcc.override {
    name = "gfortran";
    langFortran = true;
    langCC = false;
    langC = false;
    profiledCompiler = false;
  });
```

I posted on the [mailing list](http://thread.gmane.org/gmane.linux.distributions.nixos/15087) before, to which @edolstra responded that it's probably a bug. So, I decided to open an issue about it.

**Comment by jagajaga** [comment]
Is it relevant today?

**Comment by vcunat** [comment]
It's still true on master.

**Comment by dezgeg** [comment]
https://gcc.gnu.org/ml/gcc-help/2015-11/msg00052.html claims that "C & C++ are mandatory for the build procedure."

**Comment by disassembler** [comment]
Closing this based on @dezgeg comment above from gcc mailing list.
