### ISSUE TITLE
unstable channels have not been updated in over 10 days

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#52929]
## Issue description
Both the `nixos-unstable` and `nixpkgs-unstable` have not been updated in over 10 days: https://howoldis.herokuapp.com/
However, there were at least some clean evaluations during that time. Any idea why the channels are stuck?

**Comment by jtojnar** [comment]
There really were no evaluations that succeeded – see the label at the top of the [linked page](https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents):

> This is an aggregate job: **its success or failure is determined entirely by the result of building its constituent jobs.** [emphasis mine] The table below shows the status of each constituent job for the 15 most recent builds of the aggregate.

**Comment by hedning** [comment]
Yeah, nixos-unstable seem to have been broken for one reason or another a while (though there's this eval https://hydra.nixos.org/build/86233229#tabs-constituents where I suspect the failing job was restarted, but the success not picked up).

The nixpkgs-unstable unstable job have been green a few times recently though: https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-status (as I understand it the nixpkgs-unstable channel should advance when this job passes, though I might be mistaken here).

**Comment by jtojnar** [comment]
python37 seems to have been broken by a patch not applying in https://github.com/NixOS/nixpkgs/commit/552d8a70d4c47a6e52a8e0b26e3a2e33d5b94ca6

**Comment by FRidh** [comment]
About python3 https://github.com/NixOS/nixpkgs/issues/52821

**Comment by FRidh** [comment]
I expect the `nixpkgs-unstable` channel to advance after 2534dddaa96af8faa442ba7ac360966c7990e773 is tested.

**Comment by markuskowa** [comment]
Some failures on `nixos-unstable` are more mysterious: https://hydra.nixos.org/build/86233229 ran all tests successfully (all green) but failed a depend installer test (https://hydra.nixos.org/build/86233229/nixlog/34). However, looking at the log of the test it is unclear why the test even failed. Every test within succeeded with `exit status 0`. Any ideas what goes wrong here?

**Comment by vcunat** [comment]
`nixpkgs-unstable` has had some successes of the job since the last update, so I gather it's again some "invisible" error happening in the script that updates channels.  @edolstra: can you post the error somewhere?  (not sure who else can see these)

**Comment by vcunat** [comment]
`nixos-unstable` got updated now.

**Comment by orivej** [comment]
Can we make `nixos-unstable` be dependent on `pandoc`? It is really unfortunate that it has advance with +10000 broken packages, all due to the `pandoc` failure.

**Comment by vcunat** [comment]
Maybe we'd better add a threshold on percentage o failures.

**Comment by vcunat** [comment]
All are up to date now.  No idea what was blocking the nixpkgs channels.

**Comment by markuskowa** [comment]
It looks some of the installer tests are failing again (?).
