### ISSUE TITLE
linuxPackages_latest doesn't work with nvidia driver

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#52947]
## Issue description

Similar to #33284 and #32330, the nVidia driver doesn't work out of the box with the 4.20 kernel. See https://devtalk.nvidia.com/default/topic/1044478/linux/is-this-patch-for-415-18-on-kernel-4-20-rcx-/

### Steps to reproduce

Check out 9d9a993b73316a19d7020f435eddb256777d94ca and try to build the nVidia driver with latest kernel.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.6, NixOS, 19.03.git.bf90c31 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-17.09.3269.14f9ee66e63"`
 - nixpkgs: `/home/shana/programming/nixpkgs`

**Comment by Fuuzetsu** [comment]
Relevant: https://devtalk.nvidia.com/default/topic/1044478/linux/is-this-patch-for-415-18-on-kernel-4-20-rcx-/

**Comment by eadwu** [comment]
#50861 should be what you're looking for.

**Comment by Fuuzetsu** [comment]
Seems so. I'll wait.
