### ISSUE TITLE
denemo "GLib-GIO - ERROR   : No GSettings schemas are installed on the system"

### ISSUE THREAD

**Issue by SmilingHorse** [NixOS/nixpkgs#52958]
0. Remove ~/.denemo-2.2.0
1. Start denemo
2. File -> Open -> Open
3. Crash. Console says "GLib-GIO - ERROR   : No GSettings schemas are installed on the system".

~~What's really weird is I found a way to circumvent this by opening an old file I cleaned up from all its previous content and saved in my home dir ($ denemo \~/start.xml.denemo ) and it doesn't crash: [https\:\/\/gist\.github\.com\/SmilingHorse\/33ebdaf3cf81f7a18109b77e6287b320\#file-start-xml-denemo](https://gist.github.com/SmilingHorse/33ebdaf3cf81f7a18109b77e6287b320)~~

~~No idea what's going :)~~

Ok so it's what you open denemo from that makes the difference: If I use a file manage like spacefm (that probably already has glib related env variables set) everything seems to be fine. So, using a gtk terminal / file manager / wm / dm to open denemo works while starting it off from some other terminal / file manager / wm / dm means when you try to use the browser popup widget (saving / loading) it crashes.

it's probably something like this: https://github.com/NixOS/nixpkgs/issues/26560

recent nixos stable.

**Comment by jtojnar** [comment]
There should be `wrapGAppsHook` in the `nativeBuildInputs`, see https://github.com/NixOS/nixpkgs/pull/43150
