### ISSUE TITLE
winemaker (part of wine) references /usr/bin/perl

### ISSUE THREAD

**Issue by tadeokondrak** [NixOS/nixpkgs#53020]
## Issue description

```
/nix/store/kvjkhj38wgb4gv1k0vdjzsv869lmkm7p-wine-3.0.2/bin/winemaker: /usr/bin/perl: bad interpreter: No such file or directory
```
### Steps to reproduce

`nix-shell -p wine --command winemaker`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.90, NixOS, 18.09.1810.c840631fe20 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1819.76aafbf4bf4"`
 - channels(tdeo): `"nixos-18.09.1819.76aafbf4bf4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
See: https://github.com/GloriousEggroll/wine-winehq-mirror/blob/0a72708126f5b8fc06698172d973bb529944c3bf/tools/winemaker/winemaker#L1

patchShebangs should get this when `perl` is in `buildInputs`.
