### ISSUE TITLE
buildRustCrate can cause huge closures

### ISSUE THREAD

**Issue by lopsided98** [NixOS/nixpkgs#53026]
## Issue description

Packages built with `buildRustCrate`/carnix contain a `lib` directory, which may contain files that reference many dependencies that are not needed at runtime. In my case, I have a dependency that uses CMake, which ends up pulling in `gcc` and `rustc`, as shown below:

```
/nix/store/8114klmg9g1s2haflfn9xs8hynfbz65h-rust_audio_server-0.3.0
╚═══lib/link: …-1.1.7/lib.-L native=/nix/store/i659rb63a87g5ksv8kslwq4w37issnga-rust_grpcio-sys-0.4.1/lib/grpci…
    => /nix/store/i659rb63a87g5ksv8kslwq4w37issnga-rust_grpcio-sys-0.4.1
    ╚═══lib/grpcio-sys.out/build/CMakeCache.txt: …COMPILER_AR:FILEPATH=/nix/store/sx0r6vg0xfn53437cxi15l79drzcz6jr-gcc-7.3.0/bin/gcc-ar..//A wrapp…
        => /nix/store/sx0r6vg0xfn53437cxi15l79drzcz6jr-gcc-7.3.0
```

```
/nix/store/8114klmg9g1s2haflfn9xs8hynfbz65h-rust_audio_server-0.3.0
╚═══lib/link: …-1.1.7/lib.-L native=/nix/store/i659rb63a87g5ksv8kslwq4w37issnga-rust_grpcio-sys-0.4.1/lib/grpci…
    => /nix/store/i659rb63a87g5ksv8kslwq4w37issnga-rust_grpcio-sys-0.4.1
    ╚═══lib/grpcio-sys.out/build/CMakeFiles/3.12.1/CMakeCCompiler.cmake: …IT_LINK_DIRECTORIES "/nix/store/blllhz96dyddlrmipjsniipb072nxh61-rustc-1.31.0/lib;/nix/store/799…
        => /nix/store/blllhz96dyddlrmipjsniipb072nxh61-rustc-1.31.0
```

I assume some of the files in the `lib` directory are needed when building dependent packages, but they should probably be moved to a separate output to prevent them from becoming part of the runtime closure.

I have been working around this by deleting the lib directory in my executable package, which makes the closure many times smaller.

cc @P-E-Meunier

**Comment by evanjs** [comment]
Might something like [cargo-udeps](https://crates.io/crates/cargo-udeps) help any?
Not sure what the current status quo is in terms of utilizing extra tools outside of Nix for cases such as this.

**Comment by lopsided98** [comment]
No, I don't think so, because the problem is that there are references to build tools (ie. compilers), not unused Cargo crates.

**Comment by evanjs** [comment]
Ah, got it! Sounds much more manageable in that case.

**Comment by evanjs** [comment]
I recently discovered https://github.com/kolloch/crate2nix and it filled in some gaps where carnix didn't do it for me. I also noticed the closure sizes are much more manageable. No gcc or rustc, etc.
Might there be a hint in the crate2nix repo on how we can solve this? Or is this another irrelevant item?

**Comment by andir** [comment]
@lopsided98 can you test this again on a current nixpkgs master? I think the out/lib split I added some time ago might solve this issue.

**Comment by lopsided98** [comment]
Yes, this is fixed.
