### ISSUE TITLE
haskellPackages.multistate fails because of missing dependencies

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#53082]
## Issue description

```
Setup: Encountered missing dependencies:
hspec >=2 && <2.6
```

### Steps to reproduce

`nix-build -A haskellPackages.multistate`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 19.03pre164581.ae002fe44e9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(philipp): `""`
 - channels(root): `"nixos-19.03pre164715.201d739b0ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vaibhavsagar** [comment]
This looks like an upstream problem with https://hackage.haskell.org/package/multistate-0.8.0.1.

**Comment by vaibhavsagar** [comment]
You can work around this for now with `nix-build -E 'with import <nixpkgs> {}; pkgs.haskell.lib.dontCheck (pkgs.haskellPackages.multistate)'`
