### ISSUE TITLE
Raspberry PI improvments

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#53096]
## Idea description

On the 35c3 I installed NixOS the first time on a Raspberry PI 3.
It is quite good documented on the nixos.wiki, but it bothered me
to need a keyboard + Monitor OR an UART-USB adapter, just to run `nixos-rebuild switch` right after booting the system.

Ideally I would like to just create a `img` on my NixOS machine,
`dd` it to a SD-Card and the Raspberry PI starts working right the first time I start the image.
But this is not possible (yet). 

A pleasant workaround would be : 
I `dd` the current image to an SD-Card and mount the root partition right after that, to copy
my configuration to `/etc/nixos/`. When done and the SD-Card is placed in the Raspberry the first thing the PI is doing is to run `nixos-rebuild switch` by a systemd service (maybe write the logs with a timestamp also to `/etc/nixos` for debugging).

This way we can configure an Image without the hassle of additional gear.
The first thing most of us after starting the PI is to run `nixos-rebuild switch`, but manually.
I think that more than 90% us (using a raspberry PI) would benefit from that (small) change.

I choose to use this github Issue because I couldn't figure our which channels are best to reach @dezgeg who seem to our ARM specialist. 

I would create a pull-request (I don't think it is hard to create a `systemd` service which does what I described), but it would be nice to get some feedback first.

Happy New Year.

**Comment by matthewbauer** [comment]
With #53065 you can cross compile raspberry pi images. That can get you at least a minimal image that will run on your raspberry pi.

It runs without issue right now. If you enable ssh and wlan for it, this should allow a headless install. There could be some issues if you lose openssh access at some point during installation, though. It also won't work if your raspberry pi doesn't have a built in wifi driver. You can use the dwc2 module to connect to the running raspberry pi over USB. I wasn't able to get this to work with NixOS though.

**Comment by mrVanDalo** [comment]
I think this makes my Idea obsolete :D
