### ISSUE TITLE
haskellPackages.wl-pprint-extras missing dependence

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#53119]
## Issue description

```
Setup: Encountered missing dependencies:
containers >=0.4 && <0.6
```

### Steps to reproduce

```
nix-build -A haskellPackages.dates
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 19.03pre164715.201d739b0ff (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre164715.201d739b0ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vaibhavsagar** [comment]
This looks like an upstream problem with https://hackage.haskell.org/package/dates-0.2.2.2.

**Comment by vaibhavsagar** [comment]
You can work around this for now with `nix-build -E 'with import <nixpkgs> {}; pkgs.haskell.lib.doJailbreak (pkgs.haskellPackages.wl-pprint-extras)'`

**Comment by vaibhavsagar** [comment]
You can work around this for now with `nix-build -E 'with import <nixpkgs> {}; pkgs.haskell.lib.doJailbreak (pkgs.haskellPackages.wl-pprint-extras)'`

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/c921228126d3b07af8aaec75f2b0aa57349410c8.
