### ISSUE TITLE
iso: error nixos-install

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#53188]
## Issue description
Error install nixos form iso rev NixOS 19.03pre164737.a4e098519b3

### Steps to reproduce
run command
`nixos-install --root /mnt`

## Technical details
error: opening file '/nix/store/203d2c87van4rvc855rjjshkjvfpdy1s-nixos-19.03pre164737.a4e098519b3/default.nix': No such file or directory
 - system: `0`
 - host os: `Linux 4.20.0, NixOS, 19.03pre164737.a4e098519b3 (Koi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre164737.a4e098519b3"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by fpletz** [comment]
Since 19.03 was released and this issue didn't occur again it was probably fixed?

Feel free to reopen with more information.
