### ISSUE TITLE
steam-run/steam-run-native can't be overriden

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#53259]
## Issue description

`nixpkgs.steam` can easily be override as in the below example, making it easier to add additional packages:

```nix
{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    (steam.override ({
      withPrimus = true;
      extraPkgs = pkgs: with pkgs; [
        bumblebee
        glxinfo
      ];
    }))
  ];
}
```
However `steam-run` and `steam-run-native` (the chroot that simulates a FHS environment) does not support `override` parameter. It used to support when `steam-run` was part of `steam` package, however since the separation it does not work anymore.

Since one of the objectives of the split between `steam` and `steam-run` was to allow people that want to run non-patched binaries in NixOS without installing the whole `steam` package, it would be interesting to support `override` in  `steam-run` too.

**Comment by cx405** [comment]
@thiagokokada Hello. I figured this out. "steam-run" as attribute name is only reference to "steam.run", which is part of "steam.meta". The "steam.run" actually physically writes the script with name "steam-run" on the filesystem, so you can use it this way:

```
{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    (steam.override {
      withPrimus = true;
      extraPkgs = pkgs: [
        bumblebee
        glxinfo
      ];
    }).run
  ];
}
```
Note the ".run".

Also see, I updated the [Wiki](https://nixos.wiki/wiki/Steam).

**Comment by thiagokokada** [comment]
Closing this issue since @cx405 found how to fix it. Thanks!
