### ISSUE TITLE
LibreOffice fails with FontConfig error

### ISSUE THREAD

**Issue by swflint** [NixOS/nixpkgs#53354]
## Issue description

LibreOffice fails to start, providing the following error:

`Fontconfig warning: FcPattern object weight does not accept value [40 210)
Application Error`

### Steps to reproduce

Start libreoffice with `soffice`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 19.03pre164715.201d739b0ff (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(swflint): `"nixpkgs-19.03pre158050.f319c7fc89c"`
 - channels(root): `"nix1709-17.09.3269.14f9ee66e63, nix1803-18.03.133389.b551f89e256, nix1809-18.09.1829.0396345b794, nixos-19.03pre164715.201d739b0ff, unstable-19.03pre164715.201d739b0ff"`
 - nixpkgs: `/home/swflint/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment]
cc maintainer @7c6f434c

**Comment by 7c6f434c** [comment]
Hmmm. What is the `libreoffice` store path? Could not reproduce with `/nix/store/62bvwgyz0f036msl93bayaa12cgi556s-libreoffice-6.0.7.3` and `nix-shell -I nixpkgs=… -p libreoffice --run soffice`

Not sure what to ask about global `fonts.conf`…

**Comment by swflint** [comment]
`/nix/store/xgh49szv90rr6khl6ak0xmgfnnl9s25h-libreoffice-5.4.5.1`

Go figure -- old version of libreoffice (had an issue a different issue a few months back, used version from old channel).

**Comment by 7c6f434c** [comment]
Ah, we do have some issues with fontconfig from old channel used on a system from fresh stable or unstable.
