### ISSUE TITLE
tasty-rerun build failure

### ISSUE THREAD

**Issue by abathur** [NixOS/nixpkgs#53384]
## Issue description
Setting up a new macos system (which defaults to unstable channel) tonight, but ran into a dependency build failure while building git-annex. Specifically, tasty-rerun build fails... `Encountered missing dependencies: tasty >=0.10 && <1.2`

My existing system is fine at `nixpkgs-19.03pre161900.61c3169a0e1`. The failing system is at `nixpkgs-19.03pre164964.b0f40b78513`

Looks related to #52995 and #52929. It looks like the patch in 2534dddaa96af8faa442ba7ac360966c7990e773 addresses the same problem.

### Steps to reproduce

nix-shell -p gitAndTools.gitAnnex

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(abathur): `"darwin, nixpkgs-19.03pre164964.b0f40b78513"`
 - nixpkgs: `/Users/abathur/.nix-defexpr/channels/nixpkgs`

**Comment by yurkobb** [comment]
Happens on Fedora as well.

**Comment by Nadrieril** [comment]
manually changing tasty-rerun to the next version makes it build, but then git-annex fails to build because of https://git-annex.branchable.com/bugs/No_MonadFail_instance :(

**Comment by Nadrieril** [comment]
`tasty-rerun` builds on master, so this should get fixed when the channel advances next. `git-annex` is a different issue: it won't build with ghc 8.6 until upstreams makes relevant changes. In the meantime, `haskell.packages.ghc844.git-annex` should build and work normally. This should probably be a separate issue.

**Comment by yurkobb** [comment]
With a recent `nix-channel --update`, `nix-env -u` runs successfully with `git-annex` in the profile. Should we close this issue?

**Comment by abathur** [comment]
I think so? :)
