### ISSUE TITLE
Racket doesn’t install on darwin

### ISSUE THREAD

**Issue by sellout** [NixOS/nixpkgs#53389]
## Issue description

The racket derivation claims to support darwin (https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/racket/default.nix#L105), but when installing, there are many errors like

> raco setup: error: during making for <pkgs>/htdp-lib/stepper
raco setup:   ffi-lib: couldn't open "libglib-2.0.0.dylib" (dlopen(libglib-2.0.0.dylib, 6): image not found)

In https://github.com/NixOS/nixpkgs/issues/11698#issuecomment-351469669, @gebner describes how the wrappers were added to the derivation to solve just this problem, however `LD_LIBRARY_PATH` doesn’t work on darwin. Perhaps adding `DYLD_LIBRARY_PATH` as well would fix it?

The racket-minimal derivation installs fine.

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(greg): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/nzp46vr21r7ha132b7spb0kgxwvwc782-nixexprs.tar.xz`

**Comment by marsam** [comment]
> Perhaps adding DYLD_LIBRARY_PATH as well would fix it?

I remember @clacke mentioning that those variables wouldn't work https://github.com/NixOS/nixpkgs/pull/35429#issuecomment-439310970

**Comment by clacke** [comment]
Yes, it's more complicated. Racket needs to have a `config.rktd` that defines `lib-search-dirs`.

Until then, it is a bug that `racket` claims to support darwin. `racket-minimal` does, but `racket` doesn't.

**Comment by sellout** [comment]
Yeah, I would accept the removal of darwin from `platforms` as a reasonable (if not ideal) resolution to this.

What I think I’d really like to see is the ability to do something like `racketWithPackages [drracket frtime pie]`, which I _think_ would be built on `racket-minimal` anyway. And it seems like that approach may already be feasible (modulo “a whole bunch of caveats”), given @clacke’s comment on the other issue.

**Comment by clacke** [comment]
Yes, `racketWithPackages` and making `racket` unnecessary (replaced with racket-minimal) is exactly where I want to take `racket2nix` and `buildRacket`. Still some work to do before that's a reality. Work out the kinks and those caveats.

Currently with racket2nix on Linux you can nix-build a drracket on racket-minimal (the default) and get the IDE up and running, but as soon as you try to do anything, it will try to write something to a path inside the store.
