### ISSUE TITLE
Question: Is adb really governed by the android sdk license?

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#53403]
Setting programs.adb.enable = true atm requires accepting the android sdk license.
Is that really necessary?
At least the code at `https://android.googlesource.com/platform/system/adb/`
appears to be under the apache license.

**Comment by xaverdh** [comment]
Ah ok. The programs.adb option actually includes `androidenv.androidPkgs_9_0.platform-tools`, which explains the license. Maybe this should be documented?

**Comment by primeos** [comment]
Yeah, that's a bit unfortunate, the source-code is actually free but Google's Android SDK is sadly proprietary.

https://wiki.debian.org/AndroidTools:
>The binaries for the Android SDK downloadable from Google have a proprietary license but the source code is free software so Debian is packaging it.

And AFAIK (didn't check the latest changes) we still don't build the components from the source-code (that would be great but unfortunately it's pretty difficult and AFAIK only Debian attempts to build them from the source-code).

**Comment by xaverdh** [comment]
Hmm, maybe `adb` should be added [here](https://github.com/NixOS/nixpkgs/projects/6) then? Just to document, that it should probably be built from source..

**Comment by primeos** [comment]
@xaverdh good idea, I've created an issue for this with some information from my failed attempts (never got that far, it's probably pretty time consuming as we're missing a lot of tooling/abstractions for it): #75603.
