### ISSUE TITLE
elmPackages.elm: broken dependencies on nixpkgs unstable

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#53438]
## Issue description

`elmPackages.elm` fails to build a number of dependent libraries:

* cereal-0.5.7.0 fails to build its test suite:
    tests/RoundTrip.hs:33:12: error:
    • The constructor ‘Success’ should have 6 arguments, but has been given 3
    • In the pattern: Success _ _ _
      In an equation for ‘RoundTrip.isSuccess’:
          RoundTrip.isSuccess (Success _ _ _) = True
* aeson-1.4.2.0 fails to configure:
    Setup: Encountered missing dependencies:
    contravariant >=1.4.1 && <1.6

### Steps to reproduce

```
nix-build -k -E 'let nixpkgs = import (builtins.fetchTarball { url = "https://github.com/NixOS/nixpkgs/archive/487cbfc5634e1f89eb4a72df9ce8e425a0c999f6.tar.gz"; sha256 = "1vw710y1g5b18xjiqhlc2pi3czr1b6zm8cqbigkqz9kxpqmb5awf"; }) {}; in nixpkgs.elmPackages.elm'
```

Run it twice: once to build everything you can, then future runs will show the failing aeson/cereal builds more clearly.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0-13-generic, Ubuntu, 18.10 (Cosmic Cuttlefish)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(endgame): `"nixpkgs-19.03pre164964.b0f40b78513"`
 - nixpkgs: `/home/endgame/.nix-defexpr/channels/nixpkgs`

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/53326
