### ISSUE TITLE
Enhance Firefox’ Plasma integration with file open/save dialogs

### ISSUE THREAD

**Issue by silverhook** [NixOS/nixpkgs#53454]
## Issue description

It is possible to use Plasma’s native file dialogues in Firefox 64 to open or save a file. Currently this feature is not working in NixOS, and it seems to me some small changes would need to be made to derivation in order to enable it.

I propose we include this option together with `plasma-browser-integration` as a Firefox option in NixOS (see also: https://github.com/NixOS/nixpkgs/issues/51020).

### Steps to reproduce

I followed the explanation on how to enable this feature as it was published on [KDE’s Planet](https://pointieststick.com/2018/12/16/this-week-in-usability-productivity-part-49/):

1. install Firefox (64 is current stable)
1. install `xdg-desktop-portal-kde`
1. run `GTK_USE_PORTAL=1 firefox` from a terminal emulator

But it produces the following error:

```
(firefox:2594): Gtk-WARNING **: 18:19:30.997: Theme parsing error: <data>:1:34: Expected ')' in color definition

(firefox:2594): Gtk-WARNING **: 18:19:30.997: Theme parsing error: <data>:1:77: Expected ')' in color definition

(firefox:2594): Gtk-WARNING **: 18:19:34.026: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

(/nix/store/hii22m1qbp4x5qsya5x5l04mnxln9s31-firefox-release-bin-unwrapped-64.0/usr/lib/firefox-bin-64.0/firefox-bin:2748): dconf-WARNING **: 18:19:34.253: Unable to open /run/opengl-driver/share/dconf/profile/user: Permission denied

(firefox:2594): Gtk-WARNING **: 18:19:49.681: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.91, NixOS, 18.09.1834.9d608a6f592 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1834.9d608a6f592"`
 - channels(hook): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by hedning** [comment]
You'll probably have to do something like this to expose the dbus service:
https://github.com/NixOS/nixpkgs/blob/7b207060f1673e1978ad26ffa94dafc18d4c8324/nixos/modules/services/desktops/flatpak.nix#L39

**Comment by silverhook** [comment]
@hedning Where? In:

```nix
nixpkgs.config.firefox.enablePlasmaBrowserIntegration = true;
```

**Comment by hedning** [comment]
It needs to go into a nixos module or your `configuration.nix`.
