### ISSUE TITLE
Huge font size in Anki 2.1

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#53464]
## Issue description

I switched from anki 2.0.52 in 18.09 to running anki 2.1.6 from `nixos-unstable`, and suddenly the fonts in most dialogs/windows look huge, making the app hard to use.

I know Anki 2.1 switched to Python 3.7, not sure if this is relevant but it seems so.

### Steps to reproduce

* Open Anki
* Help -> About Anki

or

* Browse and open a Note

## Technical details

```
❯ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/4m253khy42mqrv3l3kih6ar75fvi0wl5-bash-interactive-4.4-p23-dev
copying path '/nix/store/4m253khy42mqrv3l3kih6ar75fvi0wl5-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.91, NixOS, 18.09.1834.9d608a6f592 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1834.9d608a6f592, nixos-hardware"`
 - channels(asymmetric): `"home-manager-18.09, nixos-unstable-19.03pre165037.eebd1a92637"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by asymmetric** [comment]
Note: AFAICT this does not appen on other platorms. [Here](https://youtu.be/eHaCkDyMmPQ?t=98) on  macOS.

**Comment by veprbl** [comment]
Can you provide a screenshot?

**Comment by asymmetric** [comment]
![About window](https://user-images.githubusercontent.com/101816/50729920-99f51400-1142-11e9-8057-668c8e5956d7.png)

![Browse window](https://user-images.githubusercontent.com/101816/50729926-b42ef200-1142-11e9-863c-f0607a0e3cc5.png)

**Comment by veprbl** [comment]
Can't reproduce the problem. One of the things that happened since 2.0.52 is the switch from pyqt4 to pyqt5. You might want to look into how you set your font sizes (DPI?).

**Comment by asymmetric** [comment]
Seems to be a [known bug](https://apps.ankiweb.net/docs/knownissues21.html#text-size) in anki 2.1

The workaround for me is setting `ANKI_WEBSCALE=0.5`.

Seems like this is not something we can/should fix in nixpkgs, closing.
