### ISSUE TITLE
[18.09] python3.pkgs.txaio fails to build

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#53474]
## Issue description

magic-wormhole fails to build. Related hydra job: https://hydra.nixos.org/build/86452269

### Steps to reproduce

`nix-env -i magic-wormhole` (on latest stable, possibly affecting unstable as well)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.91, NixOS, 18.09.1834.9d608a6f592 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1834.9d608a6f592"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
This is actually a build failure of `python3.pkgs.txaio` and was introduced by 52571d750de0f90205db62afa50dbe723e42be33.
