### ISSUE TITLE
Nginx shouldn't use full.pem for ssl_trusted_certificate

### ISSUE THREAD

**Issue by Streetwalrus** [NixOS/nixpkgs#53493]
## Issue description
https://github.com/NixOS/nixpkgs/blob/be1c03ddaf867e9a58499cd790d5cd72cffc6fca/nixos/modules/services/web-servers/nginx/default.nix#L14-L24
full.pem = fullchain.pem + key.pem, but quoting the [documentation](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling_verify):
>For verification to work, the certificate of the server certificate issuer, the root certificate, and all intermediate certificates should be configured as trusted using the ssl_trusted_certificate directive.

This corresponds to just fullchain.pem, so the current value is not correct.

### Steps to reproduce
N/A

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.932.09195057114"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(I don't think this is relevant here)

**Comment by arianvp** [comment]
This sounds like a sane change. Would you be willing to send a PR for this? I'd be happy to review it.

**Comment by Streetwalrus** [comment]
Sure, that's a trivial change. I'll take a look in a moment.

**Comment by Lonami** [comment]
This can be closed now as the PR was merged.
