### ISSUE TITLE
zfs: not working with hardened kernel 4.20

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#53522]
## Issue description
With boot virtual pc output error 
`spl: version magic '4.20.0 SMP mod_unload modversions RANDSTRUCT_PLUGIN`

Channel nixos-unstable-small
### Steps to reproduce
My configuration
```
# hardware-configuration.nix
  imports = [
    <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    <nixpkgs/nixos/modules/profiles/hardened.nix>
  ];
 
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "ehci_pci" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
 
# configuration.nix
  boot.kernelPackages = pkgs.linuxPackages_latest_hardened;
 
# zfs.nix
  boot = {
    loader.grub.zfsSupport = true;
    supportedFilesystems = [ "zfs" ];
    zfs.forceImportRoot = true;
    zfs.forceImportAll = true;
    zfs.enableUnstable = true;
    zfs.devNodes = "/dev/disk/by-path";
  };
```
## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 19.03.git.a9689de (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-19.03pre165530.be1c03ddaf8, nixos-18.09-18.09.1834.9d608a6f592"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by Izorkin** [comment]
@joachifm

**Comment by joachifm** [comment]
In what circumstance does this occur exactly? RANDSTRUCT does mess up loading modules into a running kernel that was built against a different random seed, which I believe is what you're seeing.

See also https://github.com/NixOS/nixpkgs/commit/c68e8b05f005381ac1caf51bb28282b70242b77b#commitcomment-31850284

**Comment by qolii** [comment]
Wait, does zfs even build with 4.20? I don't think there has been a release that supports it yet.

**Comment by Izorkin** [comment]
This error occurs at boot system.
With kernelPackages = pkgs.linuxPackages_4_20; zfs normal worked.

**Comment by Izorkin** [comment]
Remove
```
${optionalString (versionAtLeast version "4.13") ''
  GCC_PLUGIN_RANDSTRUCT y # A port of the PaX randstruct plugin
  GCC_PLUGIN_RANDSTRUCT_PERFORMANCE y
''}
```
zfs worked.

**Comment by joachifm** [comment]
That's the feature I'm talking about reverting.

**Comment by Izorkin** [comment]
Thanks.

**Comment by delroth** [comment]
Just to link the two for future reference: tracking issue is #53592.
