### ISSUE TITLE
syncthing: systemd service files are not installed

### ISSUE THREAD

**Issue by f--t** [NixOS/nixpkgs#53538]
## Issue description
$out/lib/* paths are not being installed when the service is enabled or the package is added to the environment.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by f--t** [comment]
Nixos configurations

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/blob/release-18.09/nixos/modules/services/networking/syncthing.nix#L118 the syncthing module defines a `systemd.services.syncthing`, when you set `services.syncthing.enable` to `true` - I think this can be closed. If not, let me know!
