### ISSUE TITLE
go-ipfs can't get a MIME type list

### ISSUE THREAD

**Issue by yvt** [NixOS/nixpkgs#53550]
## Issue description

Go's standard function [`mime.TypeByExtension`](https://golang.org/pkg/mime/#TypeByExtension) uses a MIME type list loaded from standard locations to determine a MIME type from a file extension. The standard locations are [hard-coded in the standard library](https://github.com/golang/go/blob/05581fcc5c100cc2efa58355af8665cb93fed758/src/mime/type_unix.go#L19-L23). When a list is not found in these locations, it fallbacks to [a built-in database](https://github.com/golang/go/blob/05581fcc5c100cc2efa58355af8665cb93fed758/src/mime/type.go#L59-L71) which contains only a few entries. 

The IPFS gateway provided by `go-ipfs` relies on this standard library function to determine the MIME type of a requested path. Without `mime.types`, it fails to determine MIME types of not-so-common file types such as XHTML.

For instance, `/ipfs/Qmf2spkd2wGYHr5k2GGQmzgBfk5HF2wAT1cxam7RkvoftH/hello.fm.xhtml` is supposed to be served with a MIME type `application/xhtml+xml`. <https://ipfs.io> (a public IPFS gateway) [does it](https://ipfs.io/ipfs/Qmf2spkd2wGYHr5k2GGQmzgBfk5HF2wAT1cxam7RkvoftH/hello.fm.xhtml) as intended:

<img width="831" alt="screen shot 2019-01-07 at 16 38 54" src="https://user-images.githubusercontent.com/5253988/50754964-d0de3d80-129a-11e9-879a-787b6721af6e.png">

`go-ipfs` installed on NixOS doesn't have `mime.types` in an expected location, so the MIME type cannot be determined and the page isn't rendered correctly:

<img width="831" alt="screen shot 2019-01-07 at 16 39 17" src="https://user-images.githubusercontent.com/5253988/50754980-dc316900-129a-11e9-8a37-c51dfe6523cb.png">

### Steps to reproduce

1) Enable `go-ipfs`:

```nix
{ ... }:
{ services.ipfs.enable = true; }
```

2) Open <http://127.0.0.1:8080/ipfs/Qmf2spkd2wGYHr5k2GGQmzgBfk5HF2wAT1cxam7RkvoftH/hello.fm.xhtml>

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.91, NixOS, 18.09.1834.9d608a6f592 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1834.9d608a6f592"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rnhmjoj** [comment]
Other software in nixpkgs is simply patched to use `${mailcap}/etc/mime.types` but i'm not so sure this is a good idea: making go depend on mailcap or another mime package could trigger a mass rebuild frequently.
I'm pinging go maintainers for an opinion: @cstrahan @orivej @velovix @Mic92

**Comment by Mic92** [comment]
`mailcap` seems reasonable small to be patched into the the go compiler.
At runtime only programs that actually depends on it would depend on mailcap.

$ du -sh /nix/store/7mmn8ri08z48vfj69c2h66f3g349ilq1-mailcap-2.1.48
80K     /nix/store/7mmn8ri08z48vfj69c2h66f3g349ilq1-mailcap-2.1.48

We already trigger rebuilds when updating iana-etc, I don't consider this a problem.
Our go ecosystem does not take long to recompile and only a few applications outside
of go depend on go applications.

**Comment by rnhmjoj** [comment]
So, I patched the go library and rebuilt go-ipfs but the mimetype is still not correctly assigned.
@yvt are we sure that's function ipfs uses to get mimetypes? Something else must be missing.

**Comment by yvt** [comment]
@rnhmjoj I double-checked my notes and `go-ipfs`'s source code and I found out two things:

The first thing is that the source code I was looking at was from an ancient version of `go-ipfs`. The current version no longer includes code regarding MIME type detection by itself.

The second thing is that the current version instead [calls](https://github.com/ipfs/go-ipfs/blob/de0bbb00e224b2a597eeccdc72b8cd49dc2ca10f/core/corehttp/gateway_handler.go#L375) the standard library function `http.ServeContent`, which [uses](https://github.com/golang/go/blob/5538a9a34fc4e395967c0233aab5bdde0cebbf9b/src/net/http/fs.go#L194) `mime.TypeByExtension` internally to detect the MIME type of a given file name. So, in conclusion, `go-ipfs` still uses  `mime.TypeByExtension` for MIME type detection.

Also, `go-ipfs` correctly assigns MIME types after I manually create `/etc/mime.types` (which is the current work-around for me). The set of strings in the executable extracted by `strings` exactly matches the hard-coded locations of `mime.types`, so I think we are looking at the correct function.

**Comment by rnhmjoj** [comment]
Thank you, I'll double check everything.

**Comment by rnhmjoj** [comment]
Ok, so I did it correctly but forgot to preserve the filename when pinning the file.
I'll open a PR right away.
