### ISSUE TITLE
chromiumWrapper : Flash not found, garbage collected?

### ISSUE THREAD

**Issue by MP2E** [NixOS/nixpkgs#5355]
'Shockwave Flash has crashed' appears on the top whenever I visit almost any website, including github, I have 'enablePepperFlash = true;' set in my configuration.nix and it was working as of 3 weeks ago until I updated to the latest git HEAD yesterday

**Comment by aszlig** [comment]
This should have been addressed by 9343f6f4612301f9954ada94252701a2304c271c.
