### ISSUE TITLE
Package request: ungoogled chromium

### ISSUE THREAD

**Issue by grwlf** [NixOS/nixpkgs#53579]
Please, provide expression for ungoogled-chromium!

https://github.com/Eloston/ungoogled-chromium

**Comment by grwlf** [comment]
@worldofpeace good news! Closing this issue in favor of #51195

**Comment by grwlf** [comment]
To think about it.. Should I really close this issue before PR is merged? It could help bringing attention to this work.

**Comment by shirona** [comment]
The package just got merged to master. Hooray!
@grwlf @worldofpeace Could you mark this issue as closed?
