### ISSUE TITLE
nix-env fails in chroot if nix.useSandbox = true

### ISSUE THREAD

**Issue by alexandergall** [NixOS/nixpkgs#53576]
## Issue description
`nix-env` fails with `error: cloning builder process: Operation not permitted` when executed in a chroot (with `nixos-enter` in particular).

I'm aware that `clone(2)` is supposed to fail with `EPERM` when using `CLONE_NEWUSER`, which is what the builder is doing. But calling `nix-env` in a chroot seems like a legitimate use case to me.

### Steps to reproduce
```
$ mkdir /tmp/foo
$ NIXOS_CONFIG=/etc/nixos/configuration.nix nixos-install --root /tmp/foo/ --no-bootloader --no-root-passwd --no-bootloader --system /nix/var/nix/profiles/system
$ mkdir /tmp/foo/tmp
$ nixos-generate-config --root /tmp/foo
```
Add 
```
  boot.loader.grub.devices = [ "/dev/vda" ];
  fileSystems."/" =
    { device = "foo";
      fsType = "foo";
    };
```
to `/tmp/foo/etc/nixos/hardware-configuration.nix`
```
# nixos-enter --root /tmp/foo -c "/run/current-system/sw/bin/nix-env --substituters '' -p /nix/var/nix/profiles/system -f '<nixpkgs/nixos>' --set -A system"
[...]
error: cloning builder process: Operation not permitted
error: unable to start build process
```
The problem does not arise when `--option sandbox false` is passed to `nix-env`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 18.09.1834.9d608a6f592 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1834.9d608a6f592"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
I think this is a Linux issue. Nested chroot do not work. So you shouldn't be able to build anything within a chroot because it needs to create its own chroot.

**Comment by chkno** [comment]
Linux supports nested chroots, and they work fine in NixOS on x86_64-linux:
```
# static_bash="$(nix-build '<nixpkgs>' -A pkgsStatic.bashInteractive)/bin/bash"
# static_chroot="$(nix-build '<nixpkgs>' -A pkgsStatic.coreutils)/bin/chroot"
# mkdir -p 1/2/3/4/5
# cp "$static_bash" "$static_chroot" 1/2/3/4/5

# 1/2/3/4/5/chroot 1 2/3/4/5/bash
# pwd
/
# echo *
2

# 2/3/4/5/chroot 2 3/4/5/bash
# pwd
/
# echo *
3

# 3/4/5/chroot 3 4/5/bash
# pwd
/
# echo *
4

# 4/5/chroot 4 5/bash
# pwd /
/
# echo *
5

# 5/chroot 5 /bash
# pwd
/
# echo *
bash chroot
```

**Comment by alexandergall** [comment]
This issue is not about nested chroots but about calling `clone(2)` with `CLONE_NEWUSER` from within a chroot as explained in the initial post. There is no way around that on Linux but my hope was that maybe it could be considered to accommodate the use case discussed there (or similar ones) in the Nix tool chain (i.e. by avoiding that particular `clone()` under certain circumstances). This doesn't seem to be the case, closing this issue.
