### ISSUE TITLE
services.zfs.autoScrub.enable renders system unbootable

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#53583]
## Issue description

System hangs during boot when the timer configured via `services.zfs.autoScrub.enable` fires during the boot sequence.

### Steps to reproduce

1. Enable `services.zfs.autoScrub.enable` option.
2. Configure `services.zfs.autoScrub.interval` option such that the timer will be due to run immediately upon the next reboot of the system.
3. `nixos-rebuild boot`
4. Shutdown; allow sufficient amount of time to pass. Boot the system, observe the system to hang during the boot sequence.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.13, NixOS, 19.03.git.d1fff1e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(pbogdan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lheckemann** [comment]
Does setting `systemd.timer.zfs-scrub.after = ["multi-user.target"];` help?

**Comment by pbogdan** [comment]
`s/timer/timers` but otherwise yes, it does help, thank you.

**Comment by mlen** [comment]
Hi,

I reproduced this on 19.03 yesterday. The unit already contained `After=multi-user.target`, so it seems it is not sufficient to fix this. Some data about my system:
```
$ nixos-version 
19.03.172883.1601f559e89 (Koi)
$ uname -a
Linux crow 4.19.50 #1-NixOS SMP Tue Jun 11 10:20:57 UTC 2019 x86_64 GNU/Linux
$ readlink $(which zfs)
/nix/store/q4jv6p15j4mh2d9slahhak2b2znbfix4-zfs-user-0.7.13/bin/zfs
```
