### ISSUE TITLE
haskellPackages.gtk2hs-buildtools : failed with 'missing base >=4 && <4.12'

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#53619]
## Issue description

Update `unstable` channel, try to build `taffybar` but stuck on `gtk2hs-buildtools`. 
Check against latest `master`, also failed.

```
Setup: Encountered missing dependencies:
base >=4 && <4.12
```

### Steps to reproduce

```
nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/master.tar.gz" -p haskellPackages.gtk2hs-buildtools
````

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.88, NixOS, 19.03pre162671.44b02b52ea6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre165037.eebd1a92637"`
 - channels(wizzup): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by juselius** [comment]
I can confirm this.

**Comment by wizzup** [comment]
Close as no longer issue with current master.
