### ISSUE TITLE
Migrate mixxx to Qt5 in version 2.1.6 or 2.2  

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#53643]
https://mixxx.org/wiki/doku.php/compiling_on_linux#compiling_on_linux shows that v2.1.6 was migrated to Qt5 

https://github.com/mixxxdj/mixxx/releases/tag/release-2.1.6  
https://github.com/mixxxdj/mixxx/releases/tag/release-2.2.0  

pkg: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/mixxx/default.nix

This would move another package away for Qt4: (https://github.com/NixOS/nixpkgs/issues/33248)

FYI, in the [upcoming 2.3 release](https://github.com/mixxxdj/mixxx/commit/302779da2d7a52906356971e3c050fc8b66cf4bb) VAMP will not be a required dependency.

**Comment by luzpaz** [comment]
CC @willtim sorry to ping but perhaps you could take a look at this ?

**Comment by willtim** [comment]
Happy to take a look at this

**Comment by luzpaz** [comment]
@willtim hows the progress on this?

**Comment by willtim** [comment]
I did have a go at this and got it to compile and run successfully, but I have not had time for extensive testing. I will raise a PR though.

**Comment by willtim** [comment]
https://github.com/NixOS/nixpkgs/pull/59108

**Comment by peterhoeg** [comment]
The mentioned PR was merged to master, so let's close this.
