### ISSUE TITLE
Parallel Haskell build time regression with high core counts

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#53665]
GHC almost never provides any build time advantage with greater than `-j4`, and usually begins to regress between 5 and 10 cores. [Source](https://ghc.haskell.org/trac/ghc/ticket/9221). This is a problem on high core count systems, where it's often desirable to have Nix's `cores` setting quite high for the benefit of derivations that do scale well with more cores, like most packages written in C. Setting the `cores` setting too high means that Haskell derivations suffer, and setting it too low means that C derivations suffer. Having to switch between the two manually is cumbersome, and doesn't work when a derivation has both Haskell and C dependencies.

So I propose we artificially limit `NIX_BUILD_CORES` in Haskell's `generic-builder` to a number like 4 or 6.

/cc @peti @ryantm @basvandijk @dtzWill @grahamc

**Comment by peti** [comment]
Yes, that sounds like a good idea to me. It's a hack, but it addresses a real-world problem.

**Comment by domenkozar** [comment]
See also https://github.com/NixOS/nixpkgs/issues/35205

**Comment by ElvishJerricco** [comment]
@domenkozar Yea, hopefully someone can find a good way to measure these things and start tinkering. Until then, does this seems like a good compromise?

**Comment by bgamari** [comment]
Indeed I think this is a good compromise.
