### ISSUE TITLE
switch-to-configuration not interpreted using perl

### ISSUE THREAD

**Issue by eadwu** [NixOS/nixpkgs#53672]
## Issue description
Running it as an executable returns a bad interpreter error while running it explicitly with `perl` works fine. Running with `bash` also replicates the following error.

```
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 3: use: command not found
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 4: use: command not found
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 5: use: command not found
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 6: use: command not found
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 7: use: command not found
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 8: syntax error near unexpected token `('
/nix/store/v0ba874xw18j47f3hisk4130qll3wfrx-nixos-system-nixos-19.03.git.824a927/bin/switch-to-configuration: line 8: `use Sys::Syslog qw(:standard :macros);'
```

### Steps to reproduce
`nixos-rebuild switch`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.0-rc1, NixOS, 19.03.git.824a927 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-19.03pre165037.eebd1a92637"`
 - nixpkgs: `$HOME/Downloads/nixpkgs`
```

**Comment by dtzWill** [comment]
I encountered the same when trying out the new 5.0.0-rc1 (!!) kernel, and it appears to have been resolved when reverting.

Does that work for you? If so, then we need to sort out why it's acting this way (config? dunno!)....

**Comment by eadwu** [comment]
Seems like it is a problem with `5.0.0-rc1`, reverted to `4.20.1` and the error doesn't show anymore.

**Comment by matthewbauer** [comment]
Please report this upstream! I think https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/binfmt_script.c?id=c2315c187fa0d3ab363fdebe22718170b40473e3 is the culprit but don't know enough about the kernel to fix it.

**Comment by eadwu** [comment]
Both don't work if you run them through `bash`, running them through `perl` works though.

**Comment by Laaas** [comment]
This problem also applies to the command-not-found script. Also, for me running the scripts directly from fish (i.e. `/path/to/script` and not `fish /path/to/script`), it will give a more accurate error about the operating system not being able to execute the files. I will post the exact error I get once I can.

**Comment by Laaas** [comment]
This is what happens if I try to run the file directly from a fish shell:
```
Failed to execute process '/nix/store/8n8cvy1kbqzs13i5b8vnl55q50bjvr4h-nixos-system-las-19.03pre166308.626233eee6e/bin/switch-to-configuration'. Reason:
exec: Exec format error
The file '/nix/store/8n8cvy1kbqzs13i5b8vnl55q50bjvr4h-nixos-system-las-19.03pre166308.626233eee6e/bin/switch-to-configuration' is marked as an executable but could not be run by the operating system.
```

**Comment by dorianr666** [comment]
I confirm this bug as well, running linux 5.0.0-rc4.

**Comment by dorianr666** [comment]
So I noticed that the `switch-to-configuration` script has very long hashbang line and did some testing. I found out that kernel `5.0.0-rc1` - `5.0.0-rc4` (newest at this moment) starts to fail to execute a script if its hashbang line is longer than exactly **128 bytes** (newline included).

**Comment by dtzWill** [comment]
Looks like they're enforcing the limit that was supposed to already be applied?

https://github.com/pypa/pip/issues/1773#issue-32376582

And indeed looking at our headers I'm seeing:

```
/* sizeof(linux_binprm->buf) */
#define BINPRM_BUF_SIZE 128
```

Scrolling to the end it looks like this is getting attention elsewhere recently as well,
likely others encountering same?

I think the commit linked previously is indeed responsible-- or certainly rather relevant (see the commit message!).

Not sure where this leaves us.... :/

**Comment by samueldr** [comment]
Has anyone contacted upstream yet? Is there a report (maybe from another project) that is relevant to follow?

Fixing it in the nixos kernels *is probably not enough*; kernel 5.x from other distros may still have issues with Nixpkgs stuff.

**Comment by Laaas** [comment]
Well I made a [bug report](https://bugzilla.kernel.org/show_bug.cgi?id=202497) on bugzilla, hopefully I CC'ed the right guy.

**Comment by aszlig** [comment]
I've bisected this using [this VM test](https://gist.github.com/aszlig/10d4a8541826d7cc922bcc86476f5376) and the commit that causes the regression is https://github.com/torvalds/linux/commit/8099b047ecc431518b9bb6bdbba3549bbecdc343.

**Comment by dtzWill** [comment]
4.20.8 maybe has this behavior now too, maybe?

Anyway I did the obvious thing and patched `BINPRM_BUF_SIZE` and things
are good again--at least as long as I don't use non-NixOS machines or
something :P.

https://github.com/dtzWill/nixpkgs/commit/8dc14c61b9c414fdbfea7080a6da0c9221c8b07e
and parent (apologies).

Not suggesting nixpkgs should adopt this but thought I'd share in case
others found things acting strange after a recent update as well ;).

**Comment by samueldr** [comment]
This might be affecting the current LTS (4.19.21) in addition to 4.20.8 (as reported by @dtzWill) and 5.0-rc*.

Assuming [the commit tracked down by @aszlig](https://bugzilla.kernel.org/show_bug.cgi?id=202497#c1) is the right one:

 * [4.19.y](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.19.21&id=ab5f7407125778bb05274f4a6999c67c4a72d927)
 * [4.20.y](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=c3b081f9e2e3377af8c28336e23efab606268eb3)

Found also in

 * [4.14.y](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=56ade33b1bf76c243cd0da96701b06e2c42d5a45) (v4.14.99)

**Comment by grahamc** [comment]
Based on the documentation at https://www.kernel.org/doc/linux/REPORTING-BUGS and some extra courage from @mmlb, we've decided @samueldr will write a message to LKML and Linus. I'll send Oleg (author of that patch) an email now, though.

**Comment by samueldr** [comment]
Mailing list thread:

 * https://lkml.org/lkml/2019/2/13/853

**Comment by NeQuissimus** [comment]
@dtzWill Could we have a PR with the patch? Even if only as a temporary mediation?

**Comment by Laaas** [comment]
@samueldr I think you may want to CC Andrew Morton <akpm@linux-foundation.org>, since he signed off on the [commit](https://github.com/torvalds/linux/commit/8099b047ecc431518b9bb6bdbba3549bbecdc343). I'd like to CC him myself, but then I'd have to figure out how to send e-mails to the mailing list first.

**Comment by Laaas** [comment]
actually, one can just send him an e-mail regarding the matter now that I think about it.

**Comment by samueldr** [comment]
We probably won't need #55734 

 * https://lore.kernel.org/lkml/20190214012754.GA17326@beast/T/#u

**Comment by dtzWill** [comment]
On Wed, 13 Feb 2019 19:18:49 -0800, Samuel Dionne-Riel <notifications@github.com> wrote:
> We probably won't need #55734 

Great!

> 
>  * https://lore.kernel.org/lkml/20190214012754.GA17326@beast/T/#u

\o/

**Comment by vcunat** [comment]
> 4.14.y (v4.14.99)

Yes, I had to revert that bump in nixpkgs, for reference: https://github.com/NixOS/nixpkgs/commit/a260b5dbd5cf4bc4060778e09392b01af63c7699

**Comment by samueldr** [comment]
@vcunat only issue with the revert of 4.14 only is how users of _4_19 and _4_20 (or their aliases) may now be faced with the issue on their system once the channels pass :/

It's probably a tad late to revert the others too before an update, considering small channels updated, thus the full channels probably will update soon.

**Comment by NeQuissimus** [comment]
Building with the patch from https://lore.kernel.org/lkml/20190214012754.GA17326@beast/T/#u right now, I'll make a PR if this works fine

**Comment by samueldr** [comment]
@NeQuissimus you probably can make the PR while it builds; I used the patch within Nixpkgs and used the `switch-to-configuration` test (with #55744 applied) to validate the fix.

Though didn't think of contributing it as a patch as it's a transient issue, but then again I don't know how often the kernel do a release and how quickly they react to such situations.

**Comment by NeQuissimus** [comment]
Considering it has to go through the process, you never know :D

**Comment by vcunat** [comment]
I didn't realize the connection at that time; I agree we should somehow fix all the kernel versions fast.  It might be safer to revert the kernel commit that caused this for now;  I'm not sure how much review the patch has got so far.  _Right now I can't promise to work on any of this._

**Comment by NeQuissimus** [comment]
Those are the two options now:
- My PR above (#55763), which we can then pick into stable + I'll remove it again with the next round of updates
- Revert the 4.14, 4.19, 4.20 updates

I don't really care either way...

**Comment by vcunat** [comment]
I actually meant a third option: revert [the upstream commit](https://lore.kernel.org/lkml/20181112160931.GA28463@redhat.com/T/#u) or its equivalent.  (I'm not sure if it was backported without any modifications, though it seems likely.)

**Comment by NeQuissimus** [comment]
Oh, I see... Although from what I can tell, Kees' patch is more or less that

**Comment by grahamc** [comment]
Did any channel bump including these bad kernels?

**Comment by NeQuissimus** [comment]
The small channels have seen a bump (just looking at http://howoldis.herokuapp.com/)

**Comment by grahamc** [comment]
The nixos-unstable-small and nixos-18.09-small channel URLs are being rolled back.

**Comment by NeQuissimus** [comment]
I can now confirm that #55763 fixes the immediate issue. Built `4.20.8-hardened` and booted into it. `nixos-rebuild switch --upgrade -I nixpkgs=...` still runs fine.

**Comment by NeQuissimus** [comment]
Does anybody feel strongly about which fix we apply as long as we have something for the moment?

**Comment by grahamc** [comment]
I think we should do this multi-pronged:

1. fix our perl shebangs to not be massive: not everybody runs nix on nixos
2. apply what looks like the most likely upstream patch

**Comment by Laaas** [comment]
I think the safest choice should be taken, although a proper fix, i.e. [this patch](https://lore.kernel.org/lkml/20190214012754.GA17326@beast/T/#u) is preferable in the end.

**Comment by Laaas** [comment]
good point @grahamc, but how would you make the shebangs smaller?

**Comment by grahamc** [comment]
Hydra already does this with buildEnv. Nice perk of this is we get a much faster perl startup time: https://github.com/NixOS/hydra/blob/master/release.nix#L47

**Comment by NeQuissimus** [comment]
Somebody make an executive decision or I merge #55763 :D
I don't think we should just sit on this for too long...

**Comment by grahamc** [comment]
I'd like for at least one other person to take a look at #55763 -- kernel upstream or otherwise, but it is my preferred patch.

**Comment by grahamc** [comment]
Should we leave this one open and pinned for a bit, until channels advance?

**Comment by grahamc** [comment]
FYI: Our revert patch can be deleted, as upstream has released new, fixed kernels:

 - https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.158
 - https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.101
 - https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.23
 - https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.20.10

:)

**Comment by NeQuissimus** [comment]
I am on it!

**Comment by samueldr** [comment]
> Should we leave this one open and pinned for a bit, until channels advance?

I didn't know for sure, and when I saw the title of the issue, once pinned, I got cold feet in re-writing the title and editing the main post to make it more useful for external users. Though, I'm thinking it could be a good idea if done.

**Comment by NeQuissimus** [comment]
`master`: 50f518c93f4c55ca065573e3ffdcf7192a632f66 7954ec0ffdff541fcc27d89ac9b722d0505931fd 8c14948343fd678cbf639861e1792b2477a8d925 8c14948343fd678cbf639861e1792b2477a8d925

`release-18.09`: f0ce0f3149cdb7cf083e9a1ce93a68611c3aa13c 6e9074633490c3e8e288d73de1326f332e59344b 6da8b83c5e07a0c6a15055fd3f2ad624721ebd3b 0ba800c4b4b8f9d0cf3fc50ec2fcdf0954f04c9b

**Comment by vcunat** [comment]
Let me link the upstream summary of this: https://lwn.net/SubscriberLink/779997/11de2bdc8dbc0d69/ (taken from weekly.nixos.org)

**Comment by domenkozar** [comment]
I've seen this also with NixOS 20.09 and kernel 5.4.77.

**Comment by samueldr** [comment]
Many issues could end up causing similar behaviour. It might not be that the kernel *again* decided to stop interpreting the shebang in its entirety.

I guess you'll need to have a minimal repro, so we can see what's going on. Shouldn't it fail on Hydra too, if it is a reproducible issue? If it isn't it's likely to be a **new** issue, rather than linked to a now year old issue.

**Comment by domenkozar** [comment]
Repro is to deploy a new Hetzner machine with NixOS 20.09. 

I have only helped a friend get things going, so I didn't spend much time investigating what's going on this time.
