### ISSUE TITLE
toggldesktop: fails to build

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#53676]
## Issue description

`toggldesktop` fails to build.

### Steps to reproduce

https://hydra.nixos.org/job/nixpkgs/trunk/toggldesktop.x86_64-linux

## Technical details

The build error is in an internal dependency, `qt-oauth-lib`. The nix derivation uses the upstream version from Github but Toggl is actually using a vendored internal version that has a number of fixes in it. The build error is due to using the discontinued `QtWebKit` library. Toggl's internal version uses `QtWebEngine`. This problem has been noted in #53079.

**Comment by veprbl** [comment]
cc @yegortimoshenko

**Comment by yegortimoshenko** [comment]
Fixed in https://github.com/yegortimoshenko/qt-oauth-lib/commit/60576a470bee1c27c0a40893f56390dbadd6af88 (tagged `20190125.190943`).

See #54587 for Nixpkgs PR.
