### ISSUE TITLE
Commit access - danbst

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#53689]
## Issue description
I'm requesting commit access to Nixpkgs.

### Steps to reproduce
My field of interests include: module system, nixos refactorings, closure size reduction, containers stuff, fixing issues I have on my laptop/server, reducing nixpkgs PR count

To lesser extent: package updates, documentation, triage.

## Technical details
- use NixOS for 5 years
- PRs done: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Adanbst+is%3Aclosed
- PRs reviewed: https://github.com/NixOS/nixpkgs/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Adanbst+
- [Appreciated on Discourse](https://discourse.nixos.org/badges/36/appreciated): https://discourse.nixos.org/u/danbst/summary

**Comment by hedning** [comment]
ping @domenkozar

**Comment by domenkozar** [comment]
resolved :)
