### ISSUE TITLE
Bash autocomplete is too clever

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#5369]
See https://github.com/NixOS/nixpkgs/commit/ee8e15fe76a235ae3583d4e8cb4bb370f28c5eae

> Hm, not sure this is a good idea. The auto-completion does not seem to work very well. For instance:
```
$ mkdir "foo bar" "foo xyzzy"
$ cd foo<TAB>
=>
$ cd foo\ 
```
after which pressing `b<TAB>` does not complete to `foo bar`. With `enableCompletion = false`, it works fine.

> It's also annoying that completion tries to be too clever, e.g. `unzip foo<TAB>` will ignore `foo.cbz` (even though it's a zip file).

**Comment by stephenmw** [comment]
I cannot reproduce on 14.12.550.1f14275

    mkdir "foo bar" "foo xyzzy"
    ls f[tab] -> ls foo\ 
    ls foo\ b[tab] -> foo\ bar/

**Comment by Profpatsch** [comment]
(triage) So can we close this?
