### ISSUE TITLE
libmediaart: doesn't build on master

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#53701]
## Issue description

https://hydra.nixos.org/build/86805510/nixlog/2

/cc @jtojnar @hedning 

### Steps to reproduce

```
$ nix-build -A libmediaart
```

## Technical details

Nixpkgs master.

**Comment by pbogdan** [comment]
Build log with `G_MESSAGES_DEBUG=all` set - https://gist.github.com/pbogdan/b0f7a959c7aa0c05c53ace66fa80bc71
The test suite does seem to work without sandboxing enabled but I can't figure out why that might be.

**Comment by hedning** [comment]
Looks like an upstream issue with glib-2.58.2: https://gitlab.gnome.org/GNOME/glib/issues/1645

I'm testing the proposed fix at the moment: https://gitlab.gnome.org/GNOME/glib/merge_requests/578/diffs

**Comment by hedning** [comment]
Yep, that fixes the problem.

Though glib is a pretty big rebuild, so not sure if we want to apply a stop gap to libmediaart on master too? (as this blocks nixos-unstable due to gnome-music).

**Comment by hedning** [comment]
The stop gap is in master now, and the glib fix is in staging.
