### ISSUE TITLE
attr-2.4.48 causes various breakage due to deprecrated attr/xattr.h

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#53716]
## Issue description

`attr/xattr.h` was removed in attr-2.4.48: http://git.savannah.nongnu.org/cgit/attr.git/commit/?id=7921157890d07858d092f4003ca4c6bae9fd2c38

x86_64-linux packages who's build log complains about `attr/xattr.h:` in some way:
- [x] areca
- [x] aide
- [x] bcachefs-tools
- [x] diod
- [x] ima-evm-utils
- [x] haskellPackages.xattr
- [x] mhddfs
- [x] smbnetfs
- [x] xfstests

ping PR https://github.com/NixOS/nixpkgs/pull/51962
cc @vaibhavsagar

**Comment by pbogdan** [comment]
FWIW it seems that both Fedora and Gentoo are providing some sort of backward-compatibility shim for that header:

- https://src.fedoraproject.org/rpms/attr/blob/7244374ddecc5a63e336b6d3a96021c9fa14f4dd/f/attr.spec#_89
- https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/attr/attr-2.4.48-r3.ebuild?id=077738eb8a9905827e615ddb1ac2e788337b1291#n75

**Comment by pSub** [comment]
Build for smbnetfs was fixed in b7c146c08ef62bc02ac5ecc580163418f0f554e0 (and c4c92ec72613ae124e544d4f53cb872287be424c for 19.03).

**Comment by pSub** [comment]
I've created PRs to fix the remaining packages ima-evm-utils, haskellPackages.xattr, xfstests. Once they are merged all packages from the issue description should be fixed.

**Comment by pSub** [comment]
I've send patches for haskellPackages.xattr (already accepted) and areca to upstream. I wanted to do the same for mhddfs but I coun't find a ways to propose the fix. All other packages already have a patch upstream.

**Comment by pSub** [comment]
Everything is merged and fix. If there are more build failures due to missing `attr/xattr.h` please reopen.
