### ISSUE TITLE
Enable numpy on pypy

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#53752]
Numpy now supports pypy. However, one of it's dependencies, funcsigs, has it's test runner broken on pypy3 (the package itself works). Please use Gentoo's patch for funcsigs on pypy3 and reenable pypy for numpy.

**Comment by leo60228** [comment]
Upstream issue: https://github.com/testing-cabal/funcsigs/issues/10

**Comment by leo60228** [comment]
Patch: https://github.com/gentoo/gentoo/commit/fd9a5a0a3c15d7400b936ce0f0814fd4078e900c

**Comment by veprbl** [comment]
Would you like to make a PR?

**Comment by leo60228** [comment]
@veprbl Done. #53771

**Comment by veprbl** [comment]
Should be fixed by #64200
