### ISSUE TITLE
Unable to start display-server at the start of installation

### ISSUE THREAD

**Issue by eldracode** [NixOS/nixpkgs#53804]
## Issue description
When I tried to start the display server at the time of installation, Screen goes blank for 3 times and then back to the tty .

### Steps to reproduce
1. Boot using LiveUSB of NixOS
2. type "systemctl start display-server"

## Technical details
Here's the configuration of my laptop : 
MSI GF63-8RC
intel i5 8300H
NVidia Geforce GTX 1050
8GB RAM

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

I am also attaching the output of "systemctl status display-server"
https://imgur.com/a/t0AX5IG

**Comment by FliegendeWurst** [comment]
Please provide the output of `journalctl -b -e` if you still experience the issue
