### ISSUE TITLE
mate-panel build doesn't include gobject-introspection files

### ISSUE THREAD

**Issue by duairc** [NixOS/nixpkgs#53836]
## Issue description

The derivation of `mate-panel` in `nixos-unstable` does not include `gobject-introspection` files. This causes applets that use `gobject-introspection` to get bindings to the underlying `mate-panel` library to fail.

### Steps to reproduce

Build `mate-panel` in `nixos-unstable` and look at the `result/`. It should include the following files but doesn't.

 - `./lib/girepository-1.0/MatePanelApplet-4.0.typelib`
 - `./share/gir-1.0/MatePanelApplet-4.0.gir`

### Solution

The fix is simple: add `gobject-introspection` to the `buildInputs`. But I'm a bit hazy as to whether it should go in `buildInputs` or `nativeBuildInputs`... I don't know much about how gobjecty applications work, but I'm guessing those files are generated during the build process, right? That would mean it should be in `nativeBuildInputs`?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.13, NixOS, 19.03.git.acd2756 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(shane): `""`
 - channels(root): `"home-manager, nixos-19.03pre165037.eebd1a92637"`
 - nixpkgs: `/pkgs/nixpkgs`

**Comment by hedning** [comment]
Yep, you're correct it should go in `nativeBuildInputs`.

**Comment by worldofpeace** [comment]
I see
```
    ├── gir-1.0
    │   └── MatePanelApplet-4.0.gir
```

in the package's output now.
