### ISSUE TITLE
Create compilation database for C/C++ packages

### ISSUE THREAD

**Issue by deepankarsharma** [NixOS/nixpkgs#53832]
## Issue description
It would be very useful for developers to have a compilation database generated for C/C++ projects since having a compilation database allows many tools (like indexing, static analysis etc) to work seamlessly. More information about compilation databases can be found at https://clang.llvm.org/docs/JSONCompilationDatabase.html 

For packages using CMake as their build system generating a compilation database is as simple as adding CMAKE_EXPORT_COMPILE_COMMANDS as a cmake flag. Other build systems (like make) can generate compilation databases as well using a tool like https://github.com/nickdiego/compiledb

**Comment by lheckemann** [comment]
I'm not sure how helpful this would be since software is built in the sandbox and the source ends up being in `/build`, where it won't be found after the fact.

**Comment by deepankarsharma** [comment]
Could we make the compilation database for packages available in a central location? This would unlock developer productivity by making it easier to building an indexing layer on top for all packages.

**Comment by lheckemann** [comment]
I mean that the paths referred to by the compilation database won't exist, since they refer to /build which only exists in the build sandbox.

**Comment by deepankarsharma** [comment]
The use case I am going after is to have a trivial way to generate a callgraph for all code installed and in use on my machine. For instance when trying to use a QT API in application code, it would be useful for me to see how that API is used on any installed software on my machine (like in KDE for instance). Having the compilation databases available would make it trivial for tags to be generated for system installed packages, and would allow you to easily go to definition / find callers even for headers installed as system packages.

**Comment by orivej** [comment]
Currently Nix does not have an option to keep sources of built packages even when building without the sandbox, and compilation databases are not of much use without sources.
