### ISSUE TITLE
nix-2.2 breaks the metrics job (eg. in trunk)

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#53858]
## Issue description

`NIX_SHOW_STATS` now results in [json output](https://nixos.org/nix/manual/#ssec-relnotes-2.2):
> The evaluator now prints profiling statistics (enabled via the NIX_SHOW_STATS and NIX_COUNT_CALLS environment variables) in JSON format.

This breaks the [metrics](https://hydra.nixos.org/build/87134700) job, as it assumes the old format:
https://github.com/NixOS/nixpkgs/blob/6ca8443c3be92457ecd4f81532687f99281cbcae/pkgs/top-level/metrics.nix#L22

**Comment by vcunat** [comment]
Some of the aggregates used in the job aren't output directly by nix now, but I assume we want to sum these from the new output anyway to keep comparability.
