### ISSUE TITLE
nixos-unstable channel hasn't updated for 10+ days

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#53869]
The [last successful update](https://github.com/NixOS/nixpkgs-channels/tree/nixos-unstable) was https://github.com/NixOS/nixpkgs-channels/commit/eebd1a9263716a04689a37b6537e50801d376b5e.

The state of https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents looks somewhat inconclusive to me. A couple of tests fluctuate. Does anyone have an idea how to remedy that situation?

**Comment by vcunat** [comment]
nixos-unstable updated now, even with the new staging stuff in :tada:   Without manual test restarts we probably can't keep up reasonable channel update frequency.  On unstable it's common to have other regressions, too.

**Comment by vcunat** [comment]
Let's close this now that we have separate https://github.com/NixOS/nixpkgs/issues/53935
