### ISSUE TITLE
Rebuilding virtualbox while a virtual machine is running results into a freeze (of the host)

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#5391]
@Fuuzetsu also experienced the same. cc @aszlig

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by Profpatsch** [comment]
Closing because no reply.

**Comment by Fuuzetsu** [comment]
I haven't cared to try again because I refrain from updating while VMs are running anymore (in the first place it was only by mistake that I have done so anyway). Closing is fine with me.
