### ISSUE TITLE
overlays: not able to install derivations from an overlay

### ISSUE THREAD

**Issue by 6AA4FD** [NixOS/nixpkgs#53926]
## Issue description
Nix-env does not see overlays with normal $NIX_PATH, though they work fine when `:nixpkgs-overays=$HOME/.nixpkgs/overlays` is appended to $NIX_PATH.

### Steps to reproduce
Write 
```
self: super:
{
  overTest = mkDerivation rec {
    pname = "klfc";
    version = "1.5.3";
  };
}
```
to `~/.nixpkgs/overlays/test.nix`
run `nix-env -iA nixpkgs.overTest`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results:
```
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/dqjjvs2zaj7h454k7zr1lyd7mh95k1vm-nix-info
copying path '/nix/store/dqjjvs2zaj7h454k7zr1lyd7mh95k1vm-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.83-gentoo, Gentoo, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(quinn): `"nixpkgs-19.03pre165281.7d864c6bd63"`
 - channels(root): `"nixpkgs-19.03pre165281.7d864c6bd63"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

@lheckemann you asked to be tagged.

**Comment by matthewbauer** [comment]
The directory for overlays should be ```$HOME/.config/nixpkgs/overlays```

**Comment by lheckemann** [comment]
aaaaaaargh why didn't I see that at the time :man_facepalming:

**Comment by 6AA4FD** [comment]
man... do i feel foolish currently. thank you  for the help @matthewbauer @lheckemann
