### ISSUE TITLE
syncthing permission error 

### ISSUE THREAD

**Issue by Sathish-n** [NixOS/nixpkgs#53932]
## Issue description
* syncthing service starts but there is an issue with the permissions
  
 services.autofs.enable = true;
   services.syncthing.enable = true;
   services.syncthing.openDefaultPorts = true;
   services.syncthing.systemService = true;
   services.syncthing.user = "nusspc";
  services.syncthing.group = "wheel";
  services.syncthing.dataDir = "/home/nusspc/syncthing"

* Upon building the above configuration, it throws error on starting the syncthing service.
* If I comment the following lines about user, group and dataDir, then the service starts, but there is permission error upon creating a new folder

   services.syncthing.user = "nusspc";
  services.syncthing.group = "wheel";
  services.syncthing.dataDir = "/home/nusspc/syncthing"
  

### Steps to reproduce

* start syncthing service
* check permission upon creating a folder in synching web ui

**Comment by lheckemann** [comment]
What is the error?

**Comment by Sathish-n** [comment]
The syncthing dataDir by default is set in the /var/lib/syncthing directory.

When I try to create a folder in /home/user/Documents, it gives a permission error on not being able to  create .stignore file and other permission errors.

**Comment by rnhmjoj** [comment]
I can't reproduce this. I tried in a clean environment with this configuration and syncthing gives no error.
```nix
 { config, pkgs, ...}:

{
  imports = [
    <nixpkgs/nixos/modules/virtualisation/qemu-vm.nix>
  ];

  networking.hostName = "vmhost";
 
  users.users.vm = {
    isNormalUser = true;
    password     = "vm";
    extraGroups  = [ "wheel" ];
  };

  services.xserver = {
    enable = true;
    desktopManager.xfce.enable = true;
  };

  environment.systemPackages = with pkgs; [ qutebrowser ];

  security.sudo = {
    enable = true;
    wheelNeedsPassword = false;
  };

  services.syncthing = {
    enable = true;
    openDefaultPorts = true;
    systemService = true;
    user    = "vm";
    group   = "wheel";
    dataDir = "/home/vm/syncthing";
  };
}
```

![screenshot](https://maxwell.ydns.eu/ipfs/QmPTXFmidveL1kjcUaHyyY1wJrmxbf2pVTLiosFgz8eABT)

**Comment by Sathish-n** [comment]
Yes it doesn't with the dataDir pointing to a new user for syncthing. What if I want the dataDir to be my existing user home directory?

**Comment by Sathish-n** [comment]
I have an existing user and want syncthing datadir to be under its home directory like /home/electron/.

**Comment by Sathish-n** [comment]
It worked out in the end. I was able to set it up in configuration.nix by setting up valid dataDir. Thanks for helping out :+1: :
