### ISSUE TITLE
Error installing hledger and hledger-ui to the same env

### ISSUE THREAD

**Issue by develop7** [NixOS/nixpkgs#53936]
## Issue description

Unable to install `hledger` and `hledger-ui` in the same environment due to following error:

`error: packages '/nix/store/yfjgzma08j3f72jgkwnsjhpi3316c0ia-hledger-1.12.1/share/info/hledger-ui.info' and '/nix/store/wif0xf7j9jx4sgg05gb61944fgnvaw12-hledger-ui-1.12.1/share/info/hledger-ui.info' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)`

### Steps to reproduce

- `nix-env -i hledger hledger-ui`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12-1-default, openSUSE Tumbleweed, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(develop7): `"nixpkgs-19.03pre166308.626233eee6e"`
 - nixpkgs: `/home/develop7/.nix-defexpr/channels/nixpkgs`

**Comment by zarybnicky** [comment]
This seems like a packaging problem - the hledger package doesn't ship with the hledger-ui command and so it shouldn't have the hledger-ui manual.

The relevant code is https://github.com/NixOS/nixpkgs/blob/d637039acfae15295e288a55a73741b4561ef300/pkgs/development/haskell-modules/configuration-common.nix#L961, introduced in #34301.

**Comment by develop7** [comment]
Ya, the `embeddedfiles` piece seems to be the problem:

https://github.com/NixOS/nixpkgs/blob/d637039acfae15295e288a55a73741b4561ef300/pkgs/development/haskell-modules/configuration-common.nix#L972

**Comment by peti** [comment]
Fixed in 7a6bbb41ac81e5c0664b0a9ee9da027270c248fb.
