### ISSUE TITLE
Can't compile Firefox-64.0.2 on macos

### ISSUE THREAD

**Issue by liamdawson** [NixOS/nixpkgs#53979]
## Issue description
If I run `nix-env -iA nixpkgs.firefox` on my single-user install of Nix on my macos machine, it fails during the tests (reporting duplicate symbols during `test/writer`). [This gist is a full output of `nix-env -iA nixpkgs.firefox`](https://gist.github.com/liamdawson/62d968f04e16671bcf27752b54cbf52c).

### Steps to reproduce
`nix-env -iA nixpkgs.firefox`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(liamdawson): `"nixpkgs-19.03pre166316.15eb4c361c7"`
 - nixpkgs: `/Users/liamdawson/.nix-defexpr/channels/nixpkgs`
```

**Comment by vcunat** [comment]
That's nothing new, really &ndash; the last success I see on Hydra was a few months ago: https://hydra.nixos.org/job/nixpkgs/trunk/firefox-unwrapped.x86_64-darwin/all?page=3

**Comment by liamdawson** [comment]
I would volunteer, but access to a darwin machine is contingent on using my employee machine, so I can't make promises.

**Comment by veprbl** [comment]
So current fail is because of https://github.com/NixOS/nixpkgs/issues/53307 , so we would need to get rid of dconf dependency or fix it. And then firefox itself used to fail with
```
/nix/store/ky6lslcbxnqxx10hqzvayzkaakbk8i11-Toolchains/XcodeDefault.xctoolchain/bin/clang++ -std=gnu++14 -o nsLocalFileUnix.o -c  -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG=1 -DTRIMMED=1 -DOS_POSIX=1 -DOS_MACOSX=1 -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/xpcom/io -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/obj-x86_64-apple-darwin17.7.0/xpcom/io -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/obj-x86_64-apple-darwin17.7.0/ipc/ipdl/_ipdlheaders -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/ipc/chromium/src -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/ipc/glue -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/obj-x86_64-apple-darwin17.7.0/xpcom -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/xpcom/build -I/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/obj-x86_64-apple-darwin17.7.0/dist/include -I/nix/store/8v8qwz20qr31lvgsjx8v1cl4jjzfi1ca-nspr-4.20-dev/include -I/nix/store/238sfb51hw5q8nclawcjgz3r215l32lw-nss-3.40-dev/include/nss -I/nix/store/51326rsgszap76f79ddx1h5wzd2b4cx6-pixman-0.34.0/include/pixman-1 -fPIC -DMOZILLA_CLIENT -include /private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/obj-x86_64-apple-darwin17.7.0/mozilla-config.h -Qunused-arguments -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wunreachable-code -Wunreachable-code-return -Wwrite-strings -Wno-invalid-offsetof -Wclass-varargs -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wc++1z-compat -Wcomma -Wimplicit-fallthrough -Wstring-conversion -Wtautological-overlap-compare -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wformat -Wformat-security -Wno-gnu-zero-variadic-macro-arguments -Wno-unknown-warning-option -Wno-return-type-c-linkage -fno-sized-deallocation -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-exceptions -fno-strict-aliasing -stdlib=libc++ -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -I/nix/store/2pqaggw8iyky3was9rlcbrmpjx26zxl8-icu4c-59.1-dev/include -g -O3 -fomit-frame-pointer  -MD -MP -MF .deps/nsLocalFileUnix.o.pp   /private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/xpcom/io/nsLocalFileUnix.cpp
/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/xpcom/io/nsLocalFileUnix.cpp:2365:26: error: no member named 'CFURLCreateFromFSRef' in the global namespace
  CFURLRef newURLRef = ::CFURLCreateFromFSRef(kCFAllocatorDefault, aFSRef);
                       ~~^
/private/tmp/nix-build-firefox-unwrapped-63.0.3.drv-0/firefox-63.0.3/xpcom/io/nsLocalFileUnix.cpp:2401:11: error: no member named 'CFURLGetFSRef' in the global namespace
    if (::CFURLGetFSRef(url, aResult)) {
        ~~^
2 errors generated.
```
Which seems to be a just another "cf-private" issue.

**Comment by liamdawson** [comment]
Alright, I'm not very knowledgeable on this level of programming, is this a) likely to be fixed by someone else quite soon, or b) realistic to pick up without already possessing deep knowledge of how glibc works across platforms etc?

**Comment by veprbl** [comment]
@liamdawson Well, that depends on what your goals are. If you are looking to get a working Firefox on macOS, there are different ways other than using Nix. If you want to learn more about how these things work, you should definitely should give this a try. If you get some specific questions, you can get some help on discourse or on IRC channel.

**Comment by LnL7** [comment]
FYI https://github.com/NixOS/nixpkgs/pull/49226#issuecomment-433745808

**Comment by hedning** [comment]
There's fresh PR which should fix the dconf issue: #54007

**Comment by piotr-yuxuan** [comment]
Hello here. As I'm pretty new on nix / macOS, I'm just wondering what could be a guestimate about build fix general availability? No pressure here, just trying to get a rough idea about that from anybody knowledgable about it.

**Comment by thedavidmeister** [comment]
ah this, or something similar is tripping me up getting tests running across the team

**Comment by Atemu** [comment]
Still important to me.

**Comment by domenkozar** [comment]
@toonn Given how important firefox is, I'd put this on a list for https://opencollective.com/nix-macos

**Comment by toonn** [comment]
I'll put it on the list. Fwiw, if you don't care about building from source, [here's an expression I use](https://github.com/toonn/nix-config/blob/master/darwin/apps/firefox/default.nix).

**Comment by domenkozar** [comment]
I'd say spend a few hours on compiling from source if possible and share the results if you get stuck. 

Given that it used to build and prior art of homebrew formula, it gives me hope :)

**Comment by Atemu** [comment]
Btw, could that be upstreamed to the firefox-bin package @toonn? https://github.com/NixOS/nixpkgs/issues/71689

**Comment by toonn** [comment]
Not in a way that makes it equivalent I think. I don't see most of the binaries that provides inside the .app bundle. If simply getting the app from the dmg provided by Mozilla is considered sufficient, I'd be willing to refactor the expression.

**Comment by toonn** [comment]
I added my expression to NUR to make the workaround slightly easier to use. If you follow [these instructions](https://github.com/nix-community/NUR#how-to-use) you should be able to use `pkgs.nur.repos.toonn.apps.firefox` as a firefox package in your config.

I use it with Home-Manager's Firefox module for configuration. I think the Nixpkgs Firefox package has ways to configure Firefox too using policies but this expression doesn't provide that.
