### ISSUE TITLE
nix-store --query --deriver does not work as expected

### ISSUE THREAD

**Issue by msteen** [NixOS/nixpkgs#53983]
## Issue description
I wanted to validate the hash of the source of a package. If it is invalid I would recalculate it, but that might be expensive, so I rather only do it if truly necessary. Sometimes a hash is valid, but was used for an older version of the source, which causes `nix-store --realize` to not do anything, since it already exists in the nix store after all. That is the reason why you cannot just copy paste some hash from an existing package but have to make some adjustments or use a zeroed hash. I had hoped that this situation (reusing the hash of an already existing output for a different derivation) could be detected by a shell script along the lines of the following:

```bash
# $out = pkgs.test.src.out; $drv_path = pkgs.test.src.drvPath;
actual_drv_path=$(nix-store --query --deriver "$out") &&
[[ $drv_path == "$actual_drv_path" ]] && valid=true || valid=false
```

However after experimentation it seems like `nix-store --query --deriver` does not work at all as I expected:

```
> nix-store --query --deriver /nix/store/swzxzspyqad5qdbbpiwr20bg8p7nl0ph-test.txt
/nix/store/gz7dhy463jblpcy6f0rm6395lndxrpai-test.txt.drv
> nix-store --query --outputs /nix/store/gz7dhy463jblpcy6f0rm6395lndxrpai-test.txt.drv
/nix/store/676lfr1zpzhw2qiq843waxa1qs0xq0bn-test.txt
```
if the deriver of
`/nix/store/swzxzspyqad5qdbbpiwr20bg8p7nl0ph-test.txt` is
`/nix/store/gz7dhy463jblpcy6f0rm6395lndxrpai-test.txt.drv`, should
`/nix/store/gz7dhy463jblpcy6f0rm6395lndxrpai-test.txt.drv` not output
`/nix/store/swzxzspyqad5qdbbpiwr20bg8p7nl0ph-test.txt` rather than
`/nix/store/676lfr1zpzhw2qiq843waxa1qs0xq0bn-test.txt`?

Note that `/nix/store/gz7dhy463jblpcy6f0rm6395lndxrpai-test.txt.drv` is the derivation when using the first `url` with the zeroed `sha256` of below, i.e. a derivation that never actually produced the output.

If `/nix/store/swzxzspyqad5qdbbpiwr20bg8p7nl0ph-test.txt` actually exists as it does, I would have expected `nix-store --query --deriver` to return the deriver that actually produced it and not the first derivation to ever mention it, since in practice, considering TOFU (using the hash mismatch error to get the actual hash), that will always be an otherwise invalid derivation (one that will never build successfully).

### Steps to reproduce

```nix
{ stdenv, fetchurl }:

stdenv.mkDerivation rec {
  name = "${pname}-${version}";
  pname = "test";
  version = "0.1.0";

  src = fetchurl {
    # sha256 = "0000000000000000000000000000000000000000000000000000";
    url = https://gist.githubusercontent.com/msteen/fef0b259aa8e26e9155fa0f51309892c/raw/112c7d23f90da692927b76f7284c8047e50fdc14/test.txt;
    sha256 = "0jsvhyvxslhyq14isbx2xajasisp7xdgykl0dffy3z1lzxrv51kb";
    # url = https://gist.githubusercontent.com/msteen/fef0b259aa8e26e9155fa0f51309892c/raw/98170052fc54d3e901cca0d7d4a68e1424a58e94/test.txt;
    # sha256 = "0ddb2gn6wrisva81zidnv03rq083bndqnwar7zhfw5jy4qx5wwyl";
  };

  buildCommand = ''
    cp $src $out
  '';
}
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.13, NixOS, 18.09.git.c84355e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/wheel/fork/nixpkgs`

**Comment by FRidh** [comment]
Wrong repo. This is something for https://github.com/NixOS/nix.
