### ISSUE TITLE
profanity: build is broken on nixos-unstable

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#53993]
## Issue description

`git bisect` tells it is broken since 0a2caa41fe0da9e5c36f47994594650f00e1d111.

Log:

```
…
autoreconf: Leaving directory `.'
configuring
fixing libtool script ./build-aux/ltmain.sh
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/11gfbbzg66xqbi6s31qk5r7hsp7pam6a-profanity-0.5.1 --enable-c-plugins --enable-otr --enable-notifications --enable-icons --enable-pgp --enable-python-plugins
checking for a BSD-compatible install... /nix/store/lvhndwdy2q09fhwgzykjjigz7yxq5yiv-coreutils-8.30/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/lvhndwdy2q09fhwgzykjjigz7yxq5yiv-coreutils-8.30/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/build/source':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for '/nix/store/w85pc9za5gldp3fbzqmw9gnc5b1rqgs9-profanity-0.5.1.drv' failed with exit code 77
error: build of '/nix/store/w85pc9za5gldp3fbzqmw9gnc5b1rqgs9-profanity-0.5.1.drv' failed
```

### Steps to reproduce

`nix build nixpkgs.profanity` on master

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.93, NixOS, 18.09 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(justin): `"nixos-hardware, nixos-unstable-19.03pre166308.626233eee6e, nixos-18.03-18.03.133311.5d19e3e78fb"`
 - channels(root): `"nixos-hardware"`
 - nixpkgs: `/home/justin/nixpkgs`

**Comment by devhell** [comment]
Hey, sorry for the delay, I was really busy. I wasn't aware of this issue, so next time please feel free to mention me and I'll prioritize it accordingly. :smile:

**Comment by erictapen** [comment]
No problem, I'm using `nixos-18.09`, was just experiencing the issue when I tested to build my systems for the upcoming release. For some reason I forgot to ping you as the maintainer, usually I'd do this. Thanks for the fix.

**Comment by devhell** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/56118, can you or someone else please close this? Thank you :)

**Comment by erictapen** [comment]
Ouh, yeah of course.
