### ISSUE TITLE
anki: impossible to install add-ons

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nixpkgs#54009]
## Issue description

When trying to install an add-on, one gets a traceback ending with `SSL_CERTIFICATE_VERIFY_FAILED`.

This seems to happen for other OSes too, cf. https://ankiweb.net/shared/info/1710898344 . A solution appears to be available on this page by grepping for `Finally got it working on Mac OS High Sierra.`.

This solution appears to be using `python3` and setting the correct certificates for it.

### Steps to reproduce

Try to install add-on 969733775 (for instance)

cc @the-kenny

**Comment by JorisE** [comment]
@Ekleog I can't reproduce this. Is this still a bug?

**Comment by Atemu** [comment]
Anki is practically broken and anki-bin a mess. When the anki derivation get's re-made, we can see whether this is still an issue.
