### ISSUE TITLE
Publish ISO's for HURD edition

### ISSUE THREAD

**Issue by mcandre** [NixOS/nixpkgs#54004]
I see that the NixOS repositories now feature some early support for GNU/HURD, awesome! Could we create installer ISO's for easier access?

**Comment by veprbl** [comment]
According to #45721 the situation is the opposite.

**Comment by vcunat** [comment]
Right, there seems to be a misunderstanding.

**Comment by vcunat** [comment]
To be clear, I don't think there's really opposition against HURD, it's just that so far there's been apparently noone interested in supporting it &ndash; and you could change that.
