### ISSUE TITLE
cryptsetup open --type=tcrypt no longer works (regression)

### ISSUE THREAD

**Issue by hlandau** [NixOS/nixpkgs#54019]
## Issue description

Commit https://github.com/NixOS/nixpkgs/pull/38382 introduced `--disable-kernel_crypto` to the configuration of `cryptsetup`.

This causes `cryptsetup open --type=tcrypt` to no longer work, with the following message: `Required kernel crypto interface not available.`

### Steps to reproduce

Run `cryptsetup open --type=tcrypt ./x foo`, where `./x` is a truecrypt volume.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1898.001b34abcb4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1898.001b34abcb4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by schmittlauch** [comment]
The issue for re-enabling kernel_crypto is #42163

**Comment by zarelit** [comment]
It also breaks `cryptsetup benchmark`

**Comment by matthiasbeyer** [comment]
still important to me

**Comment by ajs124** [comment]
@matthiasbeyer are you sure this is still an issue? This seems to have been solved by #62838.

e.g. cryptsetup benchmark works just fine on my machine.

**Comment by matthiasbeyer** [comment]
I did not check and do not care anymore. Thanks!
