### ISSUE TITLE
User `pulse` is missing

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#5403]
Pulse audio [adds the `pulse` user](https://github.com/NixOS/nixpkgs/blob/d15cd4875f7d20f6e1db6fa83852da5af466d208/nixos/modules/config/pulseaudio.nix#L148) only when it is installed system-wide. But it ships a dbus config for its system service which gets included as `/nix/store/…-system-path/etc/dbus-1/system.d/pulseaudio-system.conf` unconditionally.

As a result:

```
dbus-daemon[1697]: Unknown username "pulse" in message bus configuration file
```

**Comment by joachifm** [comment]
Still a problem?

**Comment by siddharthist** [comment]
I can't seem to find any mention of `pulseaudio-sytem.conf`: https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pulseaudio-system.conf

**Comment by Mic92** [comment]
This user gets added to the system, if a systemwide pulseaudio daemon is activated: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/pulseaudio.nix#L259

One solution would be to only include this to only activate it, when the service is activated.

**Comment by kirelagin** [comment]
I’ll close this as I no longer have any idea about what is going on here :).
