### ISSUE TITLE
Group `netdev` is missing when using Avahi

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#5404]
Here is a snippet from `/nix/store/…-system-path/etc/dbus-1/system.d/avahi-dbus.conf`:

```
  <!-- Allow everything, including access to SetHostName to users of the group "netdev" -->
  <policy group="netdev">
    <allow send_destination="org.freedesktop.Avahi"/>
    <allow receive_sender="org.freedesktop.Avahi"/>
  </policy>
```

`netdev` is one of those groups used by all the distros, just like `video` and `plugdev` (the latter one, actually, also doesn’t get created by NixOS and I’m not sure what implications this has).

I think this group should be created in `config/users-groups.nix`. Your thoughts?

**Comment by bjornfor** [comment]
Relevant issue from Arch (about "plugdev" group): https://bugs.archlinux.org/task/35602

**Comment by kirelagin** [comment]
Right, it seems that `plugdev` is really evil and it is not needed, since NixOS uses systemd. But unfortunatelly there are still packages that ship udev rules with references to `plugdev`.

On the other hand, `netdev` group seems to be completely harmless. I don’t what it is used for nowadays, I think NetworkManager used to decide whether user was allowed to create wifi connections based on membership in this group, but I’m pretty sure that right now I can do whaterver I want with networking with an empty `netdev` group.
Based on this I assume that the only real use for `netdev` right now is this avahi dbus rule. Avahi package creates this group in distros I checked (Gentoo, Fedora), so we should do this too.

**Comment by kirelagin** [comment]
@bjornfor BTW apparently Fedora fixed your issue by replacing all the `plugdev` with `users` in the rules they ship.

**Comment by Profpatsch** [comment]
(triage) Do we really need another group? Has there been another issue about this? Maybe it’s getting replaced by systemd anyway.

**Comment by bjornfor** [comment]
It hasn't bothered me enough to do anything about it. My user is (overly) privileged, so I didn't have a use for the "netdev" group. But I can imagine there are use cases where it's useful. (Less privileged users that are allowed to do certain things with networking / avahi.

Also, I'm worried about exhausting the user/group namespace in NixOS :-)

**Comment by Profpatsch** [comment]
> Also, I'm worried about exhausting the user/group namespace in NixOS :-)

Yes, that could very well become a problem in the mid future.
Should this stay open?

**Comment by bjornfor** [comment]
For me, closing is fine. If this becomes an issue for me later I'll probably open a PR that adds the group.

CC @kirelagin.

**Comment by CMCDragonkai** [comment]
@Profpatsch What do you mean being replaced by systemd? There's still lots of modules and hardware devices that still advise udev rules that use the plugdev group. We should either document that users should probably have the plugdev group by default, or standardise the handling of USB device modules and the groups/authentication system they use.

**Comment by CMCDragonkai** [comment]
Are you talking about this kind of stuff: `TAG+="uaccess", TAG+="udev-acl”`?
