### ISSUE TITLE
oracle security fixes

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#54052]
https://www.oracle.com/technetwork/security-advisory/cpujan2019-5072801.html

I'm not really interested personally, but let me open a thread.  I've seen our Oracle MySQL version on the list, but there might be more.  (We use MariaDB by default.)

**Comment by danderson** [comment]
Both packaged versions of Oracle MySQL in nixpkgs have been updated past the version in this advisory. It's safe to close this issue.
