### ISSUE TITLE
ALSA permission errors after update

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#5408]
Often if I `nixos-rebuild switch` and something gets updated (kernel?), I end up with:

```
ALSA lib pcm_direct.c:1137:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=1,DEV=7,SUBDEV=0'
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to initialize poll_fd
[ao/alsa] Playback open error: Permission denied
```

The workaround is to reboot but it is very annoying to do so.

**Comment by jagajaga** [comment]
Do you still have this issue?

**Comment by Fuuzetsu** [comment]
Almost certainly unless something changed recently that would have fixed it. Do you know of such a thing?

**Comment by jagajaga** [comment]
Well, I was asking because I don't have such problem now.

**Comment by Fuuzetsu** [comment]
I can confirm that it still occurs.

**Comment by layus** [comment]
This bug really lacks information and is quite old.
I assume the problem still occurs, but is it worth keeping the bug open if no investigations are made ?

Just askin' :smile:

On the other hand, could you provide a more detailed description, or try to find the package whose update triggers the bug ?
Even a larger chunk of logs would help.

As this bug has been open for a while, I also assume that this is not a widespread bug, so it probably arises from specific hardware or configuration details, right ?

**Comment by thedebugger** [comment]
I restart the machine after the switch and run into the same problem. But I didn't see the permission denied message in the logs. These are my systemd logs when i ran into the problem -- https://gist.github.com/thedebugger/60a5e5b51339cc2c26d583fcf51de2da

Btw, restart did fix the problem.

**Comment by yshui** [comment]
Encountered same problem, reboot doesn't fix it for me.

strace shows:
```
open("/dev/snd/timer", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 14
fcntl(14, F_SETFD, FD_CLOEXEC)          = 0
ioctl(14, SNDRV_TIMER_IOCTL_PVERSION, 0x7ffde1b200ec) = 0
ioctl(14, SNDRV_TIMER_IOCTL_TREAD, 0x7ffde1b200f0) = 0
ioctl(14, SNDRV_TIMER_IOCTL_SELECT, 0x7ffde1b200f0) = -1 ENODEV (No such device)
close(14)                               = 0
stat("/nix/store/ndb29if274rmc8cc28n01zh5yw4nlh1m-alsa-lib-1.1.1/share/alsa/alsa.conf", {st_mode=S_IFREG|0444, st_size=9665, ...}) = 0
open("/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = 14
fcntl(14, F_SETFD, FD_CLOEXEC)          = 0
ioctl(14, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffde1b1fdc0) = 0
close(14)                               = 0
open("/dev/snd/timer", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 14
fcntl(14, F_SETFD, FD_CLOEXEC)          = 0
ioctl(14, SNDRV_TIMER_IOCTL_PVERSION, 0x7ffde1b200ec) = 0
ioctl(14, SNDRV_TIMER_IOCTL_SELECT, 0x7ffde1b200f0) = -1 ENODEV (No such device)
close(14)                               = 0
write(2, "ALSA lib pcm_direct.c:1165:(snd1"..., 64ALSA lib pcm_direct.c:1165:(snd1_pcm_direct_initialize_poll_fd) ) = 64
write(2, "unable to open timer 'hw:CLASS=3"..., 64unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0') = 64
```

**Comment by Profpatsch** [comment]
(triage) does this problem still pop up?

**Comment by Fuuzetsu** [comment]
I haven't been using a machine with NixOS for a while so I can't confirm nor deny either way.

**Comment by Ekleog** [comment]
(triage) More than 2 years since last occurrence and 4 months since the last explicit ping-for-occurence, I guess this problem is likely solved and can be closed.

**Comment by fpletz** [comment]
Also looks like an ALSA issue to me. Let's close for now.
