### ISSUE TITLE
DrRacket crashes when opening dialogs (?)

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#54085]
## Issue description
Operations like File -> Open crashes DrRacket with the error

`SIGSEGV MAPERR si_code 1 fault on addr (nil)`

EDIT: I installed from unstable
```
$ realpath $(which drracket)
/nix/store/404fxxa9hkpb46js2c7zwsy7kpsag33y-racket-7.1/bin/drracket
```

### Steps to reproduce

- Install `racket`
- Start `drracket`
- Press `File -> Open`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.93, NixOS, 18.09.1922.97e0d53d669 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1922.97e0d53d669"`
 - channels(simendsjo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Mic92** [comment]
I strongly suspect it needs `wrapGAppsHook`. I can take a quick look.
