### ISSUE TITLE
nixos/dconf: Allow creating custom databases

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#54150]
GLib’s [GSettings](https://developer.gnome.org/gio/stable/GSettings.html#GSettings.description) system stores application settings in one of supported backends and uses compiled schemas (located in `$XDG_DATA_DIRS/glib-2.0/schemas/gschemas.compiled`) to determine type and default value of configuration keys. The schemas are compiled from XML files provided by applications and optionally, the default value can be changed by _overrides_.

#### Current situation
At the moment, we [use](https://github.com/NixOS/nixpkgs/blob/cd29409a4594ce0fbe82e375ae921c1f6d41a7f6/nixos/modules/services/x11/desktop-managers/gnome3.nix#L26-L45) GSettings overrides to declaratively change settings for GNOME & co., relying on the overridden default value. While this is great for non-important things like distribution-default background image, it suffers from many problems and inconveniences:

- Since the compiled schemas are looked up in `XDG_DATA_DIRS` on [first come, first served basis](https://gitlab.gnome.org/GNOME/glib/blob/193cc669199a79c6db55396ccc4a89b4d1e6b4a0/gio/gsettingsschema.c#L351-360), we need to make sure our overrides are first in the chain. This is only possible by [patching GLib](https://github.com/NixOS/nixpkgs/blob/cd29409a4594ce0fbe82e375ae921c1f6d41a7f6/pkgs/development/libraries/glib/schema-override-variable.patch).
- Passing the `NIX_GSETTINGS_OVERRIDES_DIR` environment variable to applications is fragile. It does not really work for things like display managers, resulting in issues like https://github.com/NixOS/nixpkgs/issues/42053
- It is easy to change a setting key in the user interface, breaking the overrides.
- Compiling overridden schemas requires packages with matching XML definitions.
- `extraGSettingsOverrides` option needs to be written in keyfile syntax, it would be much more convenient if we could use Nix syntax.

The goal of this issue is to attack the problem from the other side: modifying the backend.

#### Going through the backend
On Linux, the [dconf](https://wiki.gnome.org/Projects/dconf) backend is commonly used. It will select a profile pointing to a list of binary databases that are used for retrieving settings, see [its overview](https://developer.gnome.org/dconf/unstable/dconf-overview.html) for the gory details. Since the database is binary, the attrsets serialized into keyfiles will need to be compiled with [`dconf compile`](https://developer.gnome.org/dconf/unstable/dconf-tool.html)

Our [dconf module](https://github.com/NixOS/nixpkgs/blob/cd29409a4594ce0fbe82e375ae921c1f6d41a7f6/nixos/modules/programs/dconf.nix) can create profiles, which GDM module is incorrectly [taking advantage of](https://github.com/NixOS/nixpkgs/blob/cd29409a4594ce0fbe82e375ae921c1f6d41a7f6/nixos/modules/services/x11/display-managers/gdm.nix#L157-L160). In order to be able to configure application declaratively, we would also need to generate keyfiles and compile them to databases.

We probably do not want people to have to spell everything out

```
programs.dconf.profiles.user = pkgs.writeText "dconf-user-profile" ''
  user-db:user
  system-db:nixos
'';
programs.dconf.systemDatabases.nixos.system.proxy.http.host = "172.16.0.1";
```
It is not clear to me how should we handle locking – do we allow users to change the keys set through the module? Do we add lock control in the module?

#### Interesting links
- https://wiki.gnome.org/Projects/dconf/SystemAdministrators
- https://github.com/rycee/home-manager/blob/master/modules/misc/dconf.nix
- https://github.com/NixOS/nixpkgs/issues/42053#issuecomment-426320671

cc @worldofpeace @hedning

**Comment by worldofpeace** [comment]
> It is not clear to me how should we handle locking – do we allow users to change the keys set through the module? Do we add lock control in the module?

I'd think if someone declared a key in the module that they'd want it to not change.

Though reading https://wiki.gnome.org/Projects/dconf/SystemAdministrators
>  Presently (as of dconf 0.7.4) lockdown is only supported on a per-key basis. Put another way: you may not yet lock entire subpaths. This is for performance reasons, but there are plans to address this in future releases.

So the lockdown feature needs improvement.

**Comment by jtojnar** [comment]
> Though reading [wiki.gnome.org/Projects/dconf/SystemAdministrators](https://wiki.gnome.org/Projects/dconf/SystemAdministrators)
> 
> > Presently (as of dconf 0.7.4) lockdown is only supported on a per-key basis. Put another way: you may not yet lock entire subpaths. This is for performance reasons, but there are plans to address this in future releases.
> 
> So the lockdown feature needs improvement.

I do not thin that would be an obstacle to

> I'd think if someone declared a key in the module that they'd want it to not change.

It would be useful for things like setting the NixOS wallpaper, which we want to be overridable.

**Comment by hedning** [comment]
So working from the code snippet from @jtojnar there would be two ways of specifying locks I think:
```nix
programs.dconf.dbs.<name> = {
  settings.<key> = "foo";
  locks = [];
  # Perhaps something like this too:
  lock = false; # whether to lock all keys
};
```
or
```nix
programs.dconf.dbs.<name>.<key> = {
  value = "foo";
  lock = true;
};
```

I don't think keys should be locked by default, as it's easy to revert keys back in eg. `dconf-editor`. As such putting all the locks in a separate array seems fine (though I guess we could support keys that are strings __or_ attrsets).

At that point we could build `gsettingsOverrides` on top of the dbs config.

Not sure if there's much point in supporting more than one setting file per db?

**Comment by jtojnar** [comment]
Initially, I was thinking about having options like `programs.dconf.dbs.<name>.org.gnome.desktop.background.picture-uri` but that would make `string + attrset` ambiguous. `<name>.<schema>.<key>` would probably be better, albeit the presence of periods would mean having to quote the schema id: `<name>."org.gnome.desktop.background".picture-uri`.

Personally, I like your second example (with the possibility of using the value directly when not locking) better, since I do not need many locks and think that having them next to the key they are locking would be most clear. But I can imagine someone wanting to lock everything, which would not be very comfortable this way.

Also note that GSettings values are typed so we might need to serialize arbitrary [GVariants](https://developer.gnome.org/glib/stable/glib-GVariantType.html#glib-GVariantType.description).

> Not sure if there's much point in supporting more than one setting file per db?

Perhaps if they came from a different source (network drive). I would not bother with that.

What we probably do want is the ability to specify name of the `user-db`. And maybe setting some extra `file-db` for special profiles like `gdm`.

**Comment by jtojnar** [comment]
> Not sure if there's much point in supporting more than one setting file per db?

Actually each database corresponds to a single binary file. (And possibly multiple source keyfiles in `<db>.d` directory but they are irrelevant for us.) Did you mean to write about profiles?

Hmm, using `file-db` pointing to a generated DB in Nix store might even be cleaner than using `system-db` and generating the file somewhere in `/etc`.

**Comment by hedning** [comment]
> And possibly multiple source keyfiles in <db>.d directory but they are irrelevant for us

Was referring to the source keyfiles, I can't come up with a reason to support more than one either.

**Comment by hedning** [comment]
> Personally, I like your second example

It does look cleaner, and perhaps optimal if we support strings and attrsets.

> albeit the presence of periods would mean having to quote the schema id

It looks like the keyfiles use the schema path, not id. Ie. `/`, though that still needs to be quoted.

**Comment by jtojnar** [comment]
> It looks like the keyfiles use the schema path, not id. Ie. /, though that still needs to be quoted.

Yeah, just realized that. dconf works on lower level so it cannot translate the ids. The benefit is that the keys are no longer demarcated.

**Comment by jtojnar** [comment]
There is now [a pull request](https://github.com/NixOS/nixpkgs/pull/63790) to create a dconf db in GDM module. If we could just generalize this.

**Comment by chkno** [comment]
Re: Per-value locks and mass-lock tedium: In the unlikely event that many locks are needed this seems easy enough to handle with `mapAttrs (_: v: { value = v; lock = true; })`

**Comment by chkno** [comment]
Please keep in mind list-valued configuration: Dconf does not support merging list-valued keys.  At least one important Gnome setting is list-valued: `/org/gnome/shell/enabled-extensions` .  To enable two extensions `a@a` and `b@b`, this must be set to `['a@a','b@b']`.  It is quite hard for `a@a` and `b@b` to be added by different modules & end up with `['a@a','b@b']` at the end if dconf values are nix strings, but very easy if dconf values can be nix lists.

**Comment by jtojnar** [comment]
Yet [another issue](https://discourse.nixos.org/t/firefox-crashes-when-opening-a-file-dialog-in-pantheon/5323/4) caused by `NIX_GSETTINGS_OVERRIDES_DIR`: When the overrides use older version of GTK schemas, it will crash newer GTK applications that require the new `show-type-column` key.

In the light of this and other issues like `NIX_GSETTINGS_OVERRIDES_DIR` not being composable (#64611), I would like to implement this even without the locks as an internal option subject to change and drop the gsettings overrides use in NixOS modules in favour of that. Until we decide the new options are stable, the `extraGSettingsOverrides` would still work but warn user about the issues and suggest to use either the internal option (subject to change) or home-manager.

I would like to base the new options on top of https://github.com/NixOS/rfcs/pull/42 but its custom writer story needs to be improved first in order to allow us to implement the full support for [`GVariant`-type system](https://developer.gnome.org/glib/stable/glib-GVariantType.html#glib-GVariantType.description) the dconf’s gvdb format uses.

I think the locks could be implemented on NixOS module level using something like `mkLocked = content: { _type = "annotation:dconf-locked"; inherit content; };` and  similarly for the types not supported by Nix `mkTuple = values: { _type = "gvariant:tuple"; inherit content; };`. Not sure if NixOS module system allows custom (how do you even call these?) fragment types. cc @Infinisil

**Comment by Infinisil** [comment]
@jtojnar I think that's out of scope for that RFC, but yeah something like that could work, it just needs to be implemented.

**Comment by bbigras** [comment]
Any progress on this?

**Comment by cab404** [comment]
Related issues like #94993 are starting to go stale. Any progress, @jtojnar ?

**Comment by jtojnar** [comment]
Not aware of any progress.

**Comment by Artturin** [comment]
using the formats.ini gets us close to making keyfiles (imo its fine like this afaik but we need to add `''` manually)
```nix
  settings = {
    "org/gnome/settings-daemon/plugins/power" = {
      sleep-inactive-ac-type = "'nothing'";
    };
  };
```
```
[org/gnome/settings-daemon/plugins/power]
sleep-inactive-ac-type='nothing'
```

`nix-build -E "with import <nixpkgs> {}; callPackage ./genfile.nix {}"`
```nix
{ lib, stdenv, formats }:

let 
  settings = {
    "org/gnome/settings-daemon/plugins/power" = {
      sleep-inactive-ac-type = "'nothing'";
    };
  };
  settingsFormat = formats.ini { };
  configFile = settingsFormat.generate "custom.conf" settings;
in

stdenv.mkDerivation rec {
  pname = "something";
  version = "0.0.1";
  src = configFile;
  dontUnpack = true;
  installPhase = ''
  cp ${src} $out
  '';
}
```

**Comment by Artturin** [comment]
https://github.com/nix-community/home-manager/blob/master/modules/lib/gvariant.nix

https://github.com/nix-community/home-manager/blob/master/tests/lib/types/gvariant-merge.nix

https://github.com/nix-community/home-manager/blob/master/modules/misc/dconf.nix

**Comment by Alizter** [comment]
Any news on this?

**Comment by linsui** [comment]
Since https://github.com/NixOS/nixpkgs/pull/234615 has been merged, can this be closed? What's the next step? Should we deprecate `extraGSettingsOverrides`?

**Comment by Thesola10** [comment]
Fixed by #234615

**Comment by bam80** [comment]
> Fixed by #234615

Not reflected in the https://nixos.org/manual/nixos/unstable/#sec-gnome-gsettings-overrides?

> Overrides really only change the default values for GSettings keys so if you or an application changes the setting value, the value set by the override will be ignored. Until [NixOS’s dconf module implements changing values](https://github.com/NixOS/nixpkgs/issues/54150), you will either need to keep that in mind and clear the setting from the backend using dconf reset command when that happens, or use the [module from home-manager](https://nix-community.github.io/home-manager/options.html#opt-dconf.settings).

**Comment by bam80** [comment]
> Since #234615 has been merged, can this be closed? What's the next step? Should we deprecate `extraGSettingsOverrides`?

Deprecate `extraGSettingsOverrides` in favor of what?
Sorry I couldn't find any documentation related to #234615

**Comment by rudra-code-creator** [comment]
> Should we deprecate extraGSettingsOverrides?

Yes. I think deprecating extraGSettingsOverrides is the goal. From my understanding

**Comment by jtojnar** [comment]
One thing that `extraGSettingsOverrides` does is schema validation. So ideally, we would have a high-level GSettings module, that checks provided settings against specified schemas.

Deprecation will also include writing docs.
