### ISSUE TITLE
Package request: nixos-generate-config

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#54174]
I would like to run `nixos-generate-config` outside the installer environment on non-NixOS distributions, to get the hardware configuration, particularly the list of kernel modules that should go into `boot.initrd.availableKernelModules`. (I am installing these machines with something similar to `nixos-infect` rather than `nixos-install`.)

`nixos-generate-config` is currently generated [only in a module](https://github.com/NixOS/nixpkgs/blob/3a6cd12a476ae9d9989e04fd2078fecd088eba16/nixos/modules/installer/tools/tools.nix#L36-L42).

The workaround I'm using on Debian because I can't `nix-env -iA` it:

```
apt-get install file-slurp
perl /nix/store/h3j6xqbzxl6wasxm0s61n5q3683ypfkp-nixpkgs-19.03pre166583.872502aa56b/nixpkgs/nixos/modules/installer/tools/nixos-generate-config.pl --show-hardware-config
```

update: now

```
apt-get install libfile-slurp-perl git
git clone --depth=1 https://github.com/NixOS/nixpkgs
perl nixpkgs/nixos/modules/installer/tools/nixos-generate-config.pl --show-hardware-config
```

**Comment by jtojnar** [comment]
This was previously done in https://github.com/NixOS/nixpkgs/pull/48122 but it was reverted.

As a hack, you can create the following `nixos-tools.nix`:

```nix
{ pkgs ? import <nixpkgs> {} }:
let
  config.nix.package = pkgs.nix;
  config.system.nixos = {
    release = "Koi";
    version = "19.03";
    codeName = "Koi";
    revision = "foo";
  };

  inherit (pkgs) lib;

  tools = import <nixpkgs/nixos/modules/installer/tools/tools.nix> { inherit pkgs lib config; };

in tools.config.system.build
```

and then run `nix-env -f nixos-tools.nix -iA nixos-generate-config`.

**Comment by roberth** [comment]
Done in the form of `nixos-install-tools`.
