### ISSUE TITLE
micro: -version commit hash missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#54192]
## Issue description

The [ISSUE_TEMPLATE](https://github.com/zyedidia/micro/blob/master/.github/ISSUE_TEMPLATE) of micro want's the commit hash. It is broken on NixOS!

### Steps to reproduce

```
$ nix run -f channel:nixos-unstable micro -c micro -version
Version: 1.4.1
Commit hash: Unknown
Compiled on Unknown
```

/cc maintainer @dtzWill 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.91, NixOS, 18.09.1853.c2950341d03 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1853.c2950341d03, nixos-hardware, nixos-unstable-19.03pre165037.eebd1a92637"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dtzWill** [comment]
Here's the current behavior:

```
$ nix run nixpkgs#micro -- --version
Version: 2.0.10
Commit hash: v2.0.10
Compiled on Unknown
```

And looking at the expression for it, yep we populate our source "revision" into the build, but here it's the git tag v2.0.10 (which in theory could change, more of a ref than a rev).

Anyway.

This seems sufficient for bug reporting, but if this seems like a disservice to our users/their developers, we can look into grabbing the git revision itself.  Offhand I think simplest would be to keep it alongside the source info and bump along with source info when updating to new version, but that's a bit of a pain and not really helpful unless they change their tags often.
(and helpful update bots may miss updating this)

Closing, but if this seems like a problem let me know! Thanks for reporting!

**Comment by davidak** [comment]
Not sure if that is of any help. It just duplicates the information from version and is not a hash.

A perfect solution would be to have the exact behavior as upstream builds.

There it looks like this: https://github.com/zyedidia/micro/pull/1862#issue-702564388
