### ISSUE TITLE
Single User Install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by lylemoffitt** [NixOS/nixpkgs#54214]
## Issue description

I was unable to perform a single-user install of Nix on my Ubuntu 16.04 computer. It repeatedly failed with error `unexpected EOF reading a line`. This was reproducible with every version of [nix-2+](https://nixos.org/releases/nix/). I tried using `bash` and `zsh` (my default shell) explicitly. 

The multi-user install worked fine, though.

```
$ curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2476  100  2476    0     0   1152      0  0:00:02  0:00:02 --:--:--  1152
downloading Nix 2.2.1 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.2.1/nix-2.2.1-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.yOEs7M2q4e'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.5M  100 22.5M    0     0  2985k      0  0:00:07  0:00:07 --:--:-- 2178k
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
performing a single-user installation of Nix...
copying Nix to /nix/store.................................
initialising Nix database...
Nix: creating /home/lyle/.nix-profile
installing 'nix-2.2.1'
error: unexpected EOF reading a line
/tmp/nix-binary-tarball-unpack.yOEs7M2q4e/unpack/nix-2.2.1-x86_64-linux/install: unable to install Nix into your default profile

```

### Steps to reproduce

On a normal Ubuntu 16.04 system run the prescribed install command: `curl https://nixos.org/nix/install | sh`

## Technical details

These are details as reported by the multi-user install after I couldn't get the single-user install to work.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-43-generic, Ubuntu, 16.04.5 LTS (Xenial Xerus)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(root): `"nixpkgs-19.03pre166613.c052da08dcb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by FRidh** [comment]
This is a https://github.com/NixOS/nix issue, so please raise a ticket there instead.

**Comment by lylemoffitt** [comment]
Moved to https://github.com/NixOS/nix/issues/2642. Waiting for a response.
