### ISSUE TITLE
wxPython-4.0 expression is not used

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#54235]
There is `pkgs/development/python-modules/wxPython/4.0.nix`, which however seems not to be used because `grep -r wxPython/4.0.nix pkgs/` yields no result. We should either make `pythonPackages.wxPython` point to it or remove the 4.0 expression.

**Comment by dotlambda** [comment]
cc @FRidh

**Comment by tbenst** [comment]
I also can't built wxPython-4.0, I get:

```
sh: which: not found
Error building
ERROR: failed building wxWidgets
Traceback (most recent call last):
  File "build.py", line 1321, in cmd_build_wx
    wxbuild.main(wxDir(), build_options)
  File "/build/wxPython-4.0.4/buildtools/build_wxwidgets.py", line 500, in main
    exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
  File "/build/wxPython-4.0.4/buildtools/build_wxwidgets.py", line 85, in exitIfError
    raise builder.BuildError(msg)
buildtools.builder.BuildError: Error building
```

Unfortunately, only version 4 supports python3+ so would be great to get working!

**Comment by deliciouslytyped** [comment]
Can this be closed?

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/64047
