### ISSUE TITLE
vala can't import GTK

### ISSUE THREAD

**Issue by kmarisa** [NixOS/nixpkgs#54248]
## Issue description
vala can't import GTK.

### Steps to reproduce
```
$ nix-shell --pure -p gnome3.gtk vala --run "echo 'using Gtk;' > /tmp/valatest.vala; valac /tmp/valatest.vala"
/tmp/valatest.vala:1.7-1.9: error: The namespace name `Gtk' could not be found
using Gtk;
      ^^^
Compilation failed: 1 error(s), 0 warning(s)
```

**Comment by kmarisa** [comment]
Problem was on my end, closed.

**Comment by jtojnar** [comment]
Yup, you need to pass `--pkg gtk+-3.0` to `valac`. But be aware that if you need to use Vala libraries whose vapi files are not shipped with Vala, you will also need to add `gobject-introspection`, which has a setup hook that will set the necessary environment variables for you:


```
nix-shell --pure -p libdazzle vala gobject-introspection --run "echo 'using Dazzle;' > /tmp/valatest.vala; valac --pkg libdazzle-1.0 /tmp/valatest.vala"
```
