### ISSUE TITLE
fetchgitPrivate - Can't open user config file ...ssh-config: No such file or directory

### ISSUE THREAD

**Issue by codemonkeylabs-de** [NixOS/nixpkgs#54274]
## Issue description

Hi. When building a derivation that attempts to clone source code from a private git repository (as in one that requires a private ssh key to access it), `fetchgitPrivate` appears to not be able to "see" the ssh configuration file the `NIX_PATH` points to.

### Steps to reproduce

    $ export NIX_PATH="ssh-config-file=/home/agent/ssh-config:ssh-auth-sock=$SSH_AUTH_SOCK:$NIX_PATH"

    $ nix-build -A heimdall1
    these derivations will be built:
      /nix/store/dxmr0d8jg6hzfcvszsirps7kidp4w40m-heimdall-cde279b.drv
      /nix/store/qk76xhqagb8ykvlpa6xw44hw1nmiyf7p-heimdall1-0.9.0.1.drv
    building '/nix/store/dxmr0d8jg6hzfcvszsirps7kidp4w40m-heimdall-cde279b.drv'...
    exporting git@gitlab.com:codemonkeylabs/heimdall.git (rev cde279bb8aa25b483e5d08bcd9b5baef5d4604ba) into /nix/store/3ymq8wjvzxml3asmf0zi19gmyk50as0x-heimdall-cde279b
    Initialized empty Git repository in /nix/store/3ymq8wjvzxml3asmf0zi19gmyk50as0x-heimdall-cde279b/.git/
**Can't open user config file /home/agent/ssh-config: No such file or directory**

    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Can't open user config file /home/agent/ssh-config: No such file or directory
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Unable to checkout cde279bb8aa25b483e5d08bcd9b5baef5d4604ba from git@gitlab.com:codemonkeylabs/heimdall.git.
    builder for '/nix/store/dxmr0d8jg6hzfcvszsirps7kidp4w40m-heimdall-cde279b.drv' failed with exit code 1
    cannot build derivation '/nix/store/qk76xhqagb8ykvlpa6xw44hw1nmiyf7p-heimdall1-0.9.0.1.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/qk76xhqagb8ykvlpa6xw44hw1nmiyf7p-heimdall1-0.9.0.1.drv' failed

the ssh config file does indeed exist and it is in that location:

    $ ls -l /home/agent/ssh-config
    -rw-rw-r-- 1 agent agent 54 Jan 18 14:15 /home/agent/ssh-config
    $ cat ssh-config 
    StrictHostKeyChecking=no
    UserKnownHostsFile /dev/null

I extracted the relevant nix code from our build files and I have included the simplified files in the technical section below. TIA for your help!

## Technical details

    $ nix-shell -p nix-info --run "nix-info -m"
    these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
      /nix/store/g070fb5ybax19d65x69jbbfzqb2b34dv-nix-info
    copying path '/nix/store/g070fb5ybax19d65x69jbbfzqb2b34dv-nix-info' from 'https://cache.nixos.org'...
     - system: `"x86_64-linux"`
     - host os: `Linux 4.15.0-1021-aws, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
     - multi-user?: `yes`
     - sandbox: `yes`
     - version: `nix-env (Nix) 2.2.1`
     - channels(agent): `"nixpkgs-19.03pre166683.088cb13aee0"`
     - nixpkgs: `/home/agent/.nix-defexpr/channels/nixpkgs`

    $ cat heimdall1.nix
    { mkDerivation, async, attoparsec, base, binary, bytestring
    , conduit, connection, containers, data-default, failable, hashable
    , hashtables, hedis, hslogger, iproute, libpcap, mtl, network
    , pretty-hex, process, stdenv, structured-cli, time, transformers
    , ttl-hashtables, tuple, vector, fetchgitPrivate
    }:
    let src = fetchgitPrivate {
      "url"= "git@gitlab.com:codemonkeylabs/heimdall.git";
      "rev"= "cde279bb8aa25b483e5d08bcd9b5baef5d4604ba";
      "sha256"= "0j1bd3y1qdwbg5c3diwa1ddkpa7p791bh7mzmb4qgdzhbwcj0vak";
      "fetchSubmodules"= true;
    }; in mkDerivation {
      pname = "heimdall1";
      version = "0.9.0.1";
      src = src;
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        async attoparsec base binary bytestring conduit connection
        containers data-default hashable hedis hslogger iproute mtl network
        time transformers vector
      ];
      executableHaskellDepends = [
        async attoparsec base binary bytestring containers data-default
        failable hashable hashtables iproute mtl network pretty-hex process
        structured-cli transformers ttl-hashtables tuple vector
      ];
      executableSystemDepends = [ libpcap ];
      testHaskellDepends = [ base ];
      homepage = "https://gitlab.com/codemonkeylabs/heimdall#readme";
      license = "LGPL";
    }

    $ cat default.nix 
    with (import <nixpkgs> {}) ;
      rec {
        heimdall1 =  pkgs.haskellPackages.callPackage ./heimdall1.nix { };
      }

ps: note that the repository above is currently public. I have used this and turned it private for test purposes and can do so upon request at any time and grant whomever private access should it be necessary for testing purposes etc. Thanks!

**Comment by codemonkeylabs-de** [comment]
@matthewbauer ... yes that did it. Thanks. Perhaps adding this bit of info to the warnings in `pkgs/build-support/fetchgit/private.nix` might not be a bad idea...

**Comment by turboMaCk** [comment]
is it possible to make this work on nixos?
