### ISSUE TITLE
Missing bluetooth firmware

### ISSUE THREAD

**Issue by geerds** [NixOS/nixpkgs#5427]
Bluetooth doesn't work on my Thinkpad T440s:

```
Dez 20 01:36:08 moon kernel: bluetooth hci0: Direct firmware load for intel/ibt-hw-37.7.10-fw-1.80.2.3.d.bseq failed with error -2
Dez 20 01:36:08 moon kernel: bluetooth hci0: Falling back to user helper
```
The needed firmware is part of the ```firmware-linux``` repository:
http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/tree/intel

In NixOS we're using Debians *.deb packages to get all ```firmware-linux``` files. The only exception is ```firmware-iwlwifi```. In case of iwlwifi we're downloading different packages directly from the iwlwifi project page. Unfortunately, these package doesn't include the bluetooth files (but debians ```firmware-iwlwifi``` package does)

Is there a reason to separate ```firmware-linux-nonfree``` and ```iwlwifi```? I find it easier to drop our iwlwifi derivation and use debians ```firmware-iwlwifi``` package in our ```firmware-linux-nonfree``` derivation. Do I miss something?

@wkennington

**Comment by thorhop** [comment]
Bump... I can do that here... right?

**Comment by wkennington** [comment]
debians firmware for iwlwifi was seriously out of date and didn't have firmware supported for new kernels. This is all fixed now by using the kernel firmware-linux git repo.

**Comment by wkennington** [comment]
Relevant commit: 650b2258f06a191409ea94ea2360644587d0e330

**Comment by pSub** [comment]
@geerds Can we close this issue?

**Comment by meteficha** [comment]
@geerds didn't say which card he had, but mine is loading `intel/ibt-hw-37.8.10-fw-1.10.3.11.e.bseq` and seems to be working fine.  I guess this issue can be safely closed, @pSub.

**Comment by vcunat** [comment]
He can reopen, if need be.
