### ISSUE TITLE
nix-specific overrides in bazel 0.21 broke java compilation

### ISSUE THREAD

**Issue by robinp** [NixOS/nixpkgs#54289]
https://github.com/NixOS/nixpkgs/commit/9e9fec640edab8b92e84b6dfd8ea01c585715cea sets the `default_java_toolchain` macro's default JVM settings to correspond to Java 8. But this breaks the toolchains defined, especially the embedded ones (which are Java 9) and are used to do host (tool) builds.

This practically broke compiling Kythe with Bazel for me. Removing override just works (what was the original problem why it was introduced?)

If we really want to use `--host_javabase="@local_jdk//:jdk` in order to avoid downloading the embedded jdk, the right way to configure it for Java 8 is to set  `--host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8` as well. See https://bazel.googlesource.com/bazel/+/master/tools/jdk/BUILD#221 - this just overrides the `jvm_opts` the proper way.

Note: In [this branch](https://github.com/TreeTide/nixpkgs/commit/3edcd17aa9c23ebc49928a80402897e88fb1954f) removed the `jvm_opts` override and the `javabase` settings from `bazel/default.nix` locally and bazel built and tested fine for me (should I get a warning about the embedded jdk download?). I did'nt try adding both options yet.

**Comment by robinp** [comment]
CC @Profpatsch

**Comment by Profpatsch** [comment]
> Removing override just works (what was the original problem why it was introduced?)

It cannot work, because there is no network in sandboxed nix builds. I’ll try it out with your proposal.

We should also add a simple compilation test for Java, as we did with python.

**Comment by Profpatsch** [comment]
@robinp Hm, replacing `host_javabase` with `host_java_toolchain` as you proposed makes the bazel build try to download some jdk again. I don’t know what the right solution is here.

**Comment by robinp** [comment]
@Profpatsch it shouldn't replace it. You can keep the `host_javabase`, and then specify `host_java_toolchain` to the `jdk8` one. The latter change replaces the need for the manual override hack of the `JVM` setting (which will in turn break other toolchains).

**Comment by Profpatsch** [comment]
Thanks, will take a look later today.

**Comment by robinp** [comment]
@Profpatsch so Bazel has 3 set of javas (well described in the well-hidden https://github.com/bazelbuild/bazel/issues/5594#issuecomment-407169981):
- `server`: used to run Bazel itself.
- `host`: used to build tools that are used during the build process. For example, a protobuf-glue-code generator written in Java will be compiled using the host conf.
- `target`: used to run the compilation results eventually.

The current nix config sets the `host` config in the `.bazelrc`, also hardcodes the `server` config in the generated bazel wrapper (controlled by the `runJdk` nix arg). The nix config also sets `buildJdk` as a `buildInput`, so that's what bazel will perceive under the target `@local_jdk//:jdk` (which is the "whatever jdk is on the path" target).

I assume the default `java_toolchain` (which is for the `target` conf) is a non-JDK8 one, that's why the wrong args get passed. Setting

```
build --java_toolchain='@bazel_tools//tools/jdk:toolchain_hostjdk8'
```

fixes it, though we might want to explicitly add

```
build --javabase='@local_jdk//:jdk'
```
for prudency, even if that is the default.

This plus the above mentioned `host`-config `host_javabase` and `host_java_toolchain` should fix it, "once and ∀".

**Comment by Profpatsch** [comment]
Okay, I pushed my fixes to https://github.com/NixOS/nixpkgs/pull/54780.

I haven’t added `--javabase` yet.

So

```
host_javabase: run tools that are used in the build
host_java_toolchain: build tools that are used in the build
javabase: run java programs built by bazel
java_toolchain: build java programs
```
?

**Comment by robinp** [comment]
Looks good.

The four arguments are not that orthogonal. As I understand, `*java_toolchain` provides the configuration for `*javabase`, latter being just the binary. Then host and target mode work as described in https://docs.bazel.build/versions/master/skylark/rules.html#configurations.

**Comment by Profpatsch** [comment]
Hm, as long as I don’t understand the semantics and it doesn’t pose a problem for a downstream user, I’d rather leave it out than add it.

**Comment by robinp** [comment]
I didn't mean it has to be added, just mentioned. Looks fine this way, thank you for the change.
