### ISSUE TITLE
Sources for ncurses-6.1-20181027 are no longer available on the mirror

### ISSUE THREAD

**Issue by DzmitrySudnik** [NixOS/nixpkgs#54288]
## Issue description

See pkgs/development/libraries/ncurses/default.nix in master or 18.09. Looks like they archive old versions and 20181027 is not there any more, the earliest is 20181110. So the version in ncurses derivation needs to be updated to at least 20181110, ideally newer to avoid hitting the same issue soon.
Ideally it would be backported to 18.09.

Thanks

**Comment by worldofpeace** [comment]
#54042 should fix this

**Comment by 7c6f434c** [comment]
On the other hand, switching to using a minor-release tarball + patchlevel patch could make this issue impossible in future and make it a bit easier to use old Nixpkgs checkouts if needed — please mention me if you get around to making such a PR.
