### ISSUE TITLE
nixos-rebuild still doesn't degrade well

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#54302]
## Issue description

I have 6 cachix servers enabled. Cachix is down. `nixos-rebuild switch` is trying every server, on every package, and the timeout is simply too high. I can't imagine how many days it would take to finish the update to complete at this rate.

`nixos-rebuild switch --option substituters https://cache.nixos.org` works around the issue, but this isn't necessarily a great UX to have to resort to.

It seems that some component could detect that a mirror is down on the first package, and then disregard it on subsequent requests. If it makes sense, it could even handle 404s differently than 500s or `connection refused`, etc, retrying servers on subsequent packages from a potentially transient 404, etc.

### Steps to reproduce

Use cachix, try to upgrade your system right now.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.2, NixOS, 19.03.git.be445a9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `""`
 - nixpkgs: `/home/cole/code/nixpkgs`
```

**Comment by Infinisil** [comment]
This is not a nixpkgs issue but a Nix one, can you transfer this issue to https://github.com/NixOS/nix/issues ?

**Comment by Infinisil** [comment]
Closing as this is a Nix or Cachix issue, see issues https://github.com/cachix/cachix/issues/221 and https://github.com/NixOS/nix/issues/3019
