### ISSUE TITLE
Wrong license tag for pyaxmlparser

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#54338]
https://github.com/NixOS/nixpkgs/blob/0f3758b5e6424292a79c16db6ecb71add42f4139/pkgs/development/python-modules/pyaxmlparser/default.nix#L31

This license is incorrect. The license in the upstream project is not correct, as there are files copied from Androguard that have the Apache 2 license:

https://github.com/appknox/pyaxmlparser/blob/master/pyaxmlparser/axmlparser.py

**Comment by dotlambda** [comment]
cc maintainer @Ma27

**Comment by Ma27** [comment]
I originally looked at https://github.com/appknox/pyaxmlparser/blob/master/LICENSE and https://pypi.org/project/pyaxmlparser/

I didn't know about the issue with the sourcefiles, but as the entire package is published as MIT, can we somehow pass both licenses to `meta.licenses`?

**Comment by dotlambda** [comment]
> can we somehow pass both licenses to meta.licenses?

That's what I did in 4e0f079.

**Comment by Ma27** [comment]
nvmd then, I just looked at the diff in the original comment, sorry!

**Comment by armijnhemel** [comment]
> I originally looked at https://github.com/appknox/pyaxmlparser/blob/master/LICENSE and https://pypi.org/project/pyaxmlparser/
> 
> I didn't know about the issue with the sourcefiles, but as the entire package is published as MIT, can we somehow pass both licenses to `meta.licenses`?

The upstream project didn't correctly identify the licenses used, so I filed an issue there as well.
