### ISSUE TITLE
consul: cluster encryption key ends up in world-readable /nix/store

### ISSUE THREAD

**Issue by majewsky** [NixOS/nixpkgs#54334]
Consul's configuration has the field `encrypt` where an encryption key can be given ([upstream documentation](https://www.consul.io/docs/agent/options.html#_encrypt)). This key can be given in `configuration.nix` as `services.consul.extraConfig.encrypt`, but this causes the key to end up in the `/nix/store`, as described in great detail in #24288. Following the mitigation suggested in there, there should be an option (e.g. `services.consul.encryptionKeyFile`) which allows to store the secret key in a not-world-readable file.

**Comment by jbboehr** [comment]
You might be better off using `services.consul.extraConfigFiles`. AFAICT from looking at the service module, it can be used at the same time as `services.consul.extraConfig`

**Comment by adamcstephens** [comment]
Using extraConfigFiles is in fact the correct solution.

**Comment by adamcstephens** [comment]
Here is an example using agenix.

create file

```
echo "{\"encrypt\": \"$(nix run nixpkgs#consul keygen)\"}" | ragenix --identity $AGE_IDENTITY_FILE --editor - --edit roles/grid/consul-gossip-encrypt.age
```

enable extraConfigFiles:

```nix
age.secrets."consul-gossip-encrypt.json" = {
  file = ./consul-gossip-encrypt.age;
  owner = "consul";
};

services.consul = {
  enable = true;

  extraConfigFiles = [
    config.age.secrets."consul-gossip-encrypt.json".path
  ];
};
```
