### ISSUE TITLE
pulseeffects requires gnome3-dconf

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#54341]
## Issue description
'''
dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
'''

I know about #41886, but this is not a service and it would be awesome if installing pulseaudio bring automaticaly that programs.dconf.enable = true.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by peti** [comment]
If `programs.dconf.enable = true` enough? I tried enabling it, but the error does not seem to go away. There's probably more that needs to be done to integrate `pulseeffects` into that whole GNOME/dbus/dconf zoo?

**Comment by jtojnar** [comment]
`programs.dconf.enable = true` should be sufficient. Particularly this line:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/dconf.nix#L35

If there is some other error, let me know.
