### ISSUE TITLE
tome4 1.5.10 fails to build

### ISSUE THREAD

**Issue by nviets** [NixOS/nixpkgs#54351]
## Issue description
Hello,

tome4 1.5.10 fails to build.  I tried to install on a couple of different machines and encountered the same outcome. Let me know if any other details from the installation would be helpful.

Thanks!

### Steps to reproduce

`nix-env -i tome4`

## Technical details

Output from build attempt:
...
==== Building luazlib (release) ====
Creating ../obj/Release/luazlib
lgzip.c
lzlib.c
Linking luazlib
==== Building luabitop (release) ====
Creating ../obj/Release/luabitop
bit.c
Linking luabitop
==== Building te4-bzip (release) ====
Creating ../obj/Release/te4-bzip
blocksort.c
bzlib.c
compress.c
crctable.c
decompress.c
huffman.c
randtable.c
Linking te4-bzip
==== Building TEngine (release) ====
Creating ../obj/Release/TEngine
SFMT.c
../src/SFMT.c:493:5: warning: 'idx' is static but used in inline function 'fill_array64' which is not static
     idx = N32;
     ^~~
../src/SFMT.c:492:5: warning: 'gen_rand_array' is static but used in inline function 'fill_array64' which is not static
     gen_rand_array((w128_t *)array, size / 2);
     ^~~~~~~~~~~~~~
../src/SFMT.c:457:5: warning: 'idx' is static but used in inline function 'fill_array32' which is not static
     idx = N32;
     ^~~
../src/SFMT.c:456:5: warning: 'gen_rand_array' is static but used in inline function 'fill_array32' which is not static
     gen_rand_array((w128_t *)array, size / 4);
     ^~~~~~~~~~~~~~
../src/SFMT.c:419:5: warning: 'idx' is static but used in inline function 'gen_rand64' which is not static
     idx += 2;
     ^~~
../src/SFMT.c:418:17: warning: 'idx' is static but used in inline function 'gen_rand64' which is not static
     r = psfmt64[idx / 2];
                 ^~~
../src/SFMT.c:418:9: warning: 'psfmt64' is static but used in inline function 'gen_rand64' which is not static
     r = psfmt64[idx / 2];
         ^~~~~~~
../src/SFMT.c:410:2: warning: 'idx' is static but used in inline function 'gen_rand64' which is not static
  idx = 0;
  ^~~
../src/SFMT.c:409:2: warning: 'gen_rand_all' is static but used in inline function 'gen_rand64' which is not static
  gen_rand_all();
  ^~~~~~~~~~~~
../src/SFMT.c:408:9: warning: 'idx' is static but used in inline function 'gen_rand64' which is not static
     if (idx >= N32) {
         ^~~
auxiliar.c
bspatch.c
../src/bspatch.c: In function 'bspatch':
../src/bspatch.c:76:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fopen(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:94:29: warning: too many arguments for format [-Wformat-extra-args]
   if (feof(f)) returnerr(1, "Corrupt patch", 0, 0);
                             ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:95:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fread(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:100:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "Corrupt patch", 0, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:107:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "Corrupt patch", 0, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:111:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fclose(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:113:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fopen(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:118:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "BZ2_bzReadOpen, bz2err = %d", cbz2err, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:120:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fopen(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:125:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "BZ2_bzReadOpen, bz2err = %d", dbz2err, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:127:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fopen(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:132:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "BZ2_bzReadOpen, bz2err = %d", ebz2err, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:139:32: warning: too many arguments for format [-Wformat-extra-args]
   (close(fd)==-1)) returnerr(1,"%s",infile, 0);
                                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:140:48: warning: too many arguments for format [-Wformat-extra-args]
  if((new=malloc(newsize+1))==NULL) returnerr(1,"not enough memory", 0, 0);
                                                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:149:18: warning: too many arguments for format [-Wformat-extra-args]
     returnerr(1, "Corrupt patch", 0, 0);
                  ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:155:17: warning: too many arguments for format [-Wformat-extra-args]
    returnerr(1, "Corrupt patch", 0, 0);
                 ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:161:17: warning: too many arguments for format [-Wformat-extra-args]
    returnerr(1, "Corrupt patch", 0, 0);
                 ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:174:17: warning: too many arguments for format [-Wformat-extra-args]
    returnerr(1, "Corrupt patch", 0, 0);
                 ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:180:17: warning: too many arguments for format [-Wformat-extra-args]
    returnerr(1, "Corrupt patch", 0, 0);
                 ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:192:16: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1, "fclose(%s)", patchfile, 0);
                ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
../src/bspatch.c:197:15: warning: too many arguments for format [-Wformat-extra-args]
   returnerr(1,"%s",outfile, 0);
               ^
../src/bspatch.c:57:46: note: in definition of macro 'returnerr'
 #define returnerr(ret, str, f1, f2) { printf(str, f1, f2); perror("\nError in bspatch\n"); return (ret); }
                                              ^~~
core_lua.c
In file included from ../src/tgl.h:12:0,
                 from ../src/display_sdl.h:26,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
/nix/store/h7z515bnj5bwx7swa66gwfr2024cl2vm-libGL-1.0.0-dev/include/GL/glext.h:12066:25: error: conflicting types for 'PFNGLFRAGMENTLIGHTFVSGIXPROC'
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, const GLfloat *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/display_sdl.h:25:0,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
../src/glew.h:13602:28: note: previous declaration of 'PFNGLFRAGMENTLIGHTFVSGIXPROC' was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, GLfloat* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/tgl.h:12:0,
                 from ../src/display_sdl.h:26,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
/nix/store/h7z515bnj5bwx7swa66gwfr2024cl2vm-libGL-1.0.0-dev/include/GL/glext.h:12068:25: error: conflicting types for 'PFNGLFRAGMENTLIGHTIVSGIXPROC'
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTIVSGIXPROC) (GLenum light, GLenum pname, const GLint *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/display_sdl.h:25:0,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
../src/glew.h:13604:28: note: previous declaration of 'PFNGLFRAGMENTLIGHTIVSGIXPROC' was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTIVSGIXPROC) (GLenum light, GLenum pname, GLint* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/tgl.h:12:0,
                 from ../src/display_sdl.h:26,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
/nix/store/h7z515bnj5bwx7swa66gwfr2024cl2vm-libGL-1.0.0-dev/include/GL/glext.h:12070:25: error: conflicting types for 'PFNGLFRAGMENTLIGHTMODELFVSGIXPROC'
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTMODELFVSGIXPROC) (GLenum pname, const GLfloat *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/display_sdl.h:25:0,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
../src/glew.h:13598:28: note: previous declaration of 'PFNGLFRAGMENTLIGHTMODELFVSGIXPROC' was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTMODELFVSGIXPROC) (GLenum pname, GLfloat* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/tgl.h:12:0,
                 from ../src/display_sdl.h:26,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
/nix/store/h7z515bnj5bwx7swa66gwfr2024cl2vm-libGL-1.0.0-dev/include/GL/glext.h:12072:25: error: conflicting types for 'PFNGLFRAGMENTLIGHTMODELIVSGIXPROC'
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTMODELIVSGIXPROC) (GLenum pname, const GLint *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/display_sdl.h:25:0,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
../src/glew.h:13600:28: note: previous declaration of 'PFNGLFRAGMENTLIGHTMODELIVSGIXPROC' was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTMODELIVSGIXPROC) (GLenum pname, GLint* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/tgl.h:12:0,
                 from ../src/display_sdl.h:26,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
/nix/store/h7z515bnj5bwx7swa66gwfr2024cl2vm-libGL-1.0.0-dev/include/GL/glext.h:12079:25: error: conflicting types for 'PFNGLGETFRAGMENTMATERIALFVSGIXPROC'
 typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALFVSGIXPROC) (GLenum face, GLenum pname, GLfloat *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/display_sdl.h:25:0,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
../src/glew.h:13611:28: note: previous declaration of 'PFNGLGETFRAGMENTMATERIALFVSGIXPROC' was here
 typedef void (GLAPIENTRY * PFNGLGETFRAGMENTMATERIALFVSGIXPROC) (GLenum face, GLenum pname, const GLfloat* data);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/tgl.h:12:0,
                 from ../src/display_sdl.h:26,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
/nix/store/h7z515bnj5bwx7swa66gwfr2024cl2vm-libGL-1.0.0-dev/include/GL/glext.h:12080:25: error: conflicting types for 'PFNGLGETFRAGMENTMATERIALIVSGIXPROC'
 typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, GLint *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/display_sdl.h:25:0,
                 from ../src/display.h:23,
                 from ../src/core_lua.c:21:
../src/glew.h:13612:28: note: previous declaration of 'PFNGLGETFRAGMENTMATERIALIVSGIXPROC' was here
 typedef void (GLAPIENTRY * PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, const GLint* data);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/core_lua.c:24:0:
../src/core_lua.c: In function 'lua_key_set_clipboard':
../src/luajit2/src/lauxlib.h:97:31: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 #define luaL_checkstring(L,n) (luaL_checklstring(L, (n), NULL))
                               ^
../src/core_lua.c:443:14: note: in expansion of macro 'luaL_checkstring'
  char *str = luaL_checkstring(L, 1);
              ^~~~~~~~~~~~~~~~
In file included from ../src/core_lua.c:32:0:
../src/core_lua.c: At top level:
../src/SFMT.h:74:6: warning: inline function 'fill_array64' declared but never defined
 void fill_array64(uint64_t array[], int size);
      ^~~~~~~~~~~~
../src/SFMT.h:70:6: warning: inline function 'fill_array32' declared but never defined
 void fill_array32(uint32_t array[], int size);
      ^~~~~~~~~~~~
../src/SFMT.h:66:10: warning: inline function 'gen_rand64' declared but never defined
 uint64_t gen_rand64(void);
          ^~~~~~~~~~
../src/SFMT.h:62:10: warning: inline function 'gen_rand32' declared but never defined
 uint32_t gen_rand32(void);
          ^~~~~~~~~~
In file included from ../src/display.h:23:0,
                 from ../src/core_lua.c:21:
../src/display_sdl.h:46:6: warning: inline function 'sdlDrawImage' declared but never defined
 void sdlDrawImage(SDL_Surface *dest, SDL_Surface *image, int x, int y);
      ^~~~~~~~~~~~
make[1]: *** [TEngine.make:165: ../obj/Release/TEngine/core_lua.o] Error 1
make: *** [Makefile:17: TEngine] Error 2
builder for '/nix/store/hx2wvfq456v0k84w12j9kz4ysbd5ky4x-tome4-1.5.10.drv' failed with exit code 2
cannot build derivation '/nix/store/ri117ss47zmf7nk40kvpzidpzzl749qn-all.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ri117ss47zmf7nk40kvpzidpzzl749qn-all.drv' failed
`

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

nathan@DESKTOP:~$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (1.51 MiB download, 8.11 MiB unpacked):
  /nix/store/00aqq7zm73ca5rck3k4yf4z339lxzy2w-bash-interactive-4.4-p23
  /nix/store/1f4cikmcp49zs9xsl3h7km9j0var9jhx-readline-7.0p5
  /nix/store/g070fb5ybax19d65x69jbbfzqb2b34dv-nix-info
  /nix/store/hzq8p4q2ndj4xd65isdd75lj477wn0j0-bash-interactive-4.4-p23-doc
  /nix/store/mbif1qshlhvyc95xnjhhrszfd5acqq63-bash-interactive-4.4-p23-man
  /nix/store/ycvi66455vwkb0azgn9a4y88l2rlgl71-bash-interactive-4.4-p23-info
  /nix/store/zqgiswxcs5714xgmrk69y1k67liqimg3-bash-interactive-4.4-p23-dev
copying path '/nix/store/hzq8p4q2ndj4xd65isdd75lj477wn0j0-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/ycvi66455vwkb0azgn9a4y88l2rlgl71-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/mbif1qshlhvyc95xnjhhrszfd5acqq63-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/g070fb5ybax19d65x69jbbfzqb2b34dv-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/1f4cikmcp49zs9xsl3h7km9j0var9jhx-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/00aqq7zm73ca5rck3k4yf4z339lxzy2w-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/zqgiswxcs5714xgmrk69y1k67liqimg3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-17763-Microsoft, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(nathan): `"nixpkgs-19.03pre166887.db8e3654e2c"`
 - nixpkgs: `/home/nathan/.nix-defexpr/channels/nixpkgs

**Comment by aanderse** [comment]
This was fixed and I had forgotten to mark is as resolved. Coincidentally `tome4` doesn't build on `master` again, but for entirely unrelated reasons. That new issue is resolved [here](https://github.com/NixOS/nixpkgs/pull/89517).

**Comment by nviets** [comment]
Thanks for the update @aanderse. I’ll watch out for the new issue to be resolved

**Comment by aanderse** [comment]
Cool. Merged :tada:
