### ISSUE TITLE
Darwin Go failure on staging-next

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#54363]
## Issue description

https://hydra.nixos.org/build/87605224

### Steps to reproduce

cc @NixOS/darwin-maintainers 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by LnL7** [comment]
I have a suspicion that's an intermittent issue: `pipe: too many open files`.

**Comment by LnL7** [comment]
I assume we can close this.
