### ISSUE TITLE
coredns: How to handle manual deps in parallel to vendored deps

### ISSUE THREAD

**Issue by periklis** [NixOS/nixpkgs#54369]
## Issue description
I am trying to update `coredns` to `v1.3.1` which is currently outdated in our repository. Although the package switched to vendored dependencies, some of them ae still installed manually with a extra make target `make godeps`:
```
.PHONY: godeps
godeps:
        @ # Not vendoring these, so external plugins compile, avoiding:
        @ # cannot use c (type *"github.com/mholt/caddy".Controller) as type
        @ # *"github.com/coredns/coredns/vendor/github.com/mholt/caddy".Controller like errors.
        (cd $(GOPATH)/src/github.com/mholt/caddy 2>/dev/null              && git checkout -q master 2>/dev/null || true)
        (cd $(GOPATH)/src/github.com/miekg/dns 2>/dev/null                && git checkout -q master 2>/dev/null || true)
        (cd $(GOPATH)/src/github.com/prometheus/client_golang 2>/dev/null && git checkout -q master 2>/dev/null || true)
        go get -u github.com/mholt/caddy
        go get -u github.com/miekg/dns
        go get -u github.com/prometheus/client_golang/prometheus/promhttp
        go get -u github.com/prometheus/client_golang/prometheus
        (cd $(GOPATH)/src/github.com/mholt/caddy              && git checkout -q v0.11.1)
        (cd $(GOPATH)/src/github.com/miekg/dns                && git checkout -q v1.1.3)
        (cd $(GOPATH)/src/github.com/prometheus/client_golang && git checkout -q v0.9.1)
```

My question is how to handle this corner case, since go2nix doesn't manage them?

cc @Mic92

**Comment by periklis** [comment]
Actually this seems to be a regular workflow even on `master`. I couldn't build the tag `v1.3.1` without running `make godeps` before `go build`

**Comment by Mic92** [comment]
You could try to add those dependencies to the `Gopkg` file and then use `dep2nix`.
If that works, just make a fork and add leave a comment in our nix file for the next person to update.

**Comment by periklis** [comment]
@DeltaEvo Amazing! Would you like to open two PRs for the above, one for the update and one for the module?

**Comment by DeltaEvo** [comment]
Done #54930, #54931
