### ISSUE TITLE
installer iso does not boot with AMD Ryzen 7 with Vega 10 integrated graphics

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#54378]
## Issue description

Using my new laptop
https://www.lenovo.com/us/en/laptops/thinkpad/thinkpad-e-series/ThinkPad-E585/p/22TP2TEE585

- AMD Ryzen™ 7 2700U quad-core (2.20GHz, up to 3.80GHz Max Boost, 4MB Cache)
- Integrated AMD Radeon™ Vega 10 Mobile Graphics

I tried using the 18.09 installer iso, the latest unstable 19.03 installer iso, the latest building `new-kernel` installer iso, and my own installer iso compiled with [nixos-generators](https://github.com/nix-community/nixos-generators) (nixos-generate -f installer-iso -c configuration.nix where configuration.nix was https://gist.github.com/ryantm/4756ab66852344007188c99a894aed51).

With all of these, grub loads, but after choosing any of the options (normal, nomodeset, debug), it freezes with a white underscore in the top left corner and no other output and no ability to change TTYs.

Any suggestions for how I can debug this more? Or, any suggestions for configuration to add to the installer iso to get it working?

cc @etu @samueldr since you were helping me on IRC with this.

**Comment by arianvp** [comment]
You will need at least kernel 4.17 to use Ryzen APUs.  You could try building a custom ISO image with a newer kernel (https://www.phoronix.com/scan.php?page=article&item=ryzen-2400g-may&num=1)

**Comment by ryantm** [comment]
@arianvp Yes, but that doesn't seem to be enough. The [new-kernel](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.iso_minimal_new_kernel.x86_64-linux/all) iso is on 4.20 and that doesn't work, and unstable iso is on 4.19.

**Comment by ryantm** [comment]
Additional information from the BIOS:
CPU Type: AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx
Machine Type Model: 20KVCT01WW
UEFI BIOS Version: R0UET65W

secure boot is turned off
AMD V(TM) Technology virtualization is enabled
TPM 2.0 security chip is enabled

**Comment by samueldr** [comment]
A random search of *Ryzen 7 2700U grub* thinking it might be grub failing to hand-off to the kernel 

`noapic` or `acpi=noirq` may be relevant, but that's a random guess coming from results for other laptops. though with the same CPU.

**Comment by ryantm** [comment]
adding `acpi=noirq` to the kernel params in grub worked (at least with my latest kernel with extra config mentioned above)! I'll try some other ISOs and report back.

**Comment by ryantm** [comment]
As others warned, the 18.09 installer fails even with this kernel param because of something about not finding the root disk of the installer ISO.

Using either `noapic` or `acpi=noirq` both seem to work; I didn't try using both at once.

**Comment by etu** [comment]
@ryantm Regarding your kernel config, I think you may need `DRM_AMD_DC_DCN1_01` to get a graphical system based on this: https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/display/Kconfig#L14-L22

**Comment by ryantm** [comment]
It seems like it freezes every time X starts. It freezes with either `DRM_AMD_DC_DCN1_01 y` set or `DRM_AMD_DC_DCN1_0 y` set.

The X log ends with:

```
(II) Initializing extension DRI2
(II) AMDGPU(0): Setting screen physical size to 508 x 285
```

**Comment by ryantm** [comment]
[ArchWiki to the rescue](https://wiki.archlinux.org/index.php/Laptop/Lenovo#E_series) 

>Missing IVRS map in ACPI Table, add amd_iommu=pt ivrs_ioapic[32]=00:14.0 in kernel parameters. In order to get X to work correctly, add iommu=soft in kernel parameters (Linux 4.20 only). In order to get microsd (SDHCI) working, echo 'options sdhci debug_quirks2="0x8000"' > /etc/modprobe.d/sdhci.conf and change module load order MODULES=(sdhci sdhci_pci) in /etc/mkinitcpio.conf (line 7). Don't forget to run mkinitcpio -p linux afterwards.

I was also able to remvoe `noapic` and it now boots to GNOME.

**Comment by ryantm** [comment]
This is resolved if you update the BIOS firmware now.
