### ISSUE TITLE
zip-archive update causing a runtime error in elm

### ISSUE THREAD

**Issue by tzemanovic** [NixOS/nixpkgs#54384]
## Issue description

An update of zip-archive package from 0.3.3 to 0.4 in https://github.com/NixOS/nixpkgs/commit/91ec96d77d146efa7595b6d3f12193a89958ec0a is causing a runtime error in elm compiler (https://github.com/elm/compiler/issues/1882). It would be good to set the elm's dependency on zip-archive to version < 0.4 until this gets fixed.

**Comment by domenkozar** [comment]
probably best to patch it

**Comment by jerith666** [comment]
I think https://github.com/jerith666/elm-compiler/commit/39d86a735e28da514be185d4c3256142c37c2a8a fixes it, will try to find more time to test tomorrow morning.

**Comment by jerith666** [comment]
Shoot, I forgot all about this -- I did confirm that commit fixes it, I will clean up and open a PR soon.
