### ISSUE TITLE
Missing CUDA .pc files

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#54395]
## Issue description

On my Ubuntu with CUDA installed I have:

```
/usr/lib/pkgconfig/cuda-8.0.pc
/usr/lib/pkgconfig/cudart-8.0.pc
```

There seems to be no nixpkgs equivalent of those.

That apparently makes packaging support for CUDA-capabale applications hard, e.g. I cannot manage to add a flag to `gstreamer`'s `gst-plugins-bad` because its Meson build system cannot find e.g. `cuda-9.2.so` and `cudart-9.2.so` in https://github.com/GStreamer/gst-plugins-bad/blob/f710b36ac4935bd6123df15a191c1fe089c4c233/sys/meson.build#L63-L84

## Possible solution

* `libcuda.so` is provided by the nvidia _driver_ in `linuxPackages.nvidia_x11`
* `libcudart.so` is provided by `cudatoolkit.lib` [see here](https://github.com/NixOS/nixpkgs/blob/2b0efd5c5ae36204dfe745b109f6a3baa99210c2/pkgs/development/compilers/cudatoolkit/default.nix#L104-L107)

We could generate `.pc` files ourselves, rough sketch:

```nix
  cuda-pc = writeTextFile {
    name = "cuda-9.2.pc"; # TODO unhardcode
    text = ''
      cudaroot=${cudatoolkit}
      libdir=''${cudaroot}/lib64
      includedir=''${cudaroot}/include

      Name: cuda
      Description: CUDA Driver Library
      Version: ${cudaPkgconfigVersionString}
      Libs: -L''${libdir} -lcuda
      Cflags: -I''${includedir}
    '';
  };

  cudart-pc = writeTextFile {
    name = "cudart-9.2.pc"; # TODO unhardcode
    text = ''
      cudaroot=${linuxPackages.nvidia_x11}
      libdir=''${cudaroot}/lib64
      includedir=''${cudaroot}/include

      Name: cudart
      Description: CUDA Runtime Library
      Version: ${cudaPkgconfigVersionString}
      Libs: -L''${libdir} -lcudart
      Cflags: -I''${includedir}
    '';
  };
```

or e.g. for the case of `installPhase` in `cudatoolkit/default.nix`:

```bash
        # Generate cudart-*.pc
        mkdir -p $lib/lib/pkgconfig
        cat > $lib/lib/pkgconfig/cudart-${cudaPkgconfigVersionString}.pc <<EOF
        cudaroot=$out
        libdir=''${cudaroot}/lib64
        includedir=''${cudaroot}/include

        Name: cudart
        Description: CUDA Runtime Library
        Version: ${cudaPkgconfigVersionString}
        Libs: -L''${libdir} -lcudart
        Cflags: -I''${includedir}
        EOF
```

with helper functions:

```nix
    let
      # Compute version for .pc file, like `cuda-9.2.pc`
      versionComponents = stdenv.lib.splitString "." version;
      major = builtins.elemAt versionComponents 0;
      minor = builtins.elemAt versionComponents 1;
      cudaPkgconfigVersionString = "${major}.${minor}";
```

**Comment by r-burns** [comment]
It looks like these .pc files are only introduced by downstream packagers, like Arch (https://aur.archlinux.org/cgit/aur.git/tree/cuda.pc?h=cuda-11.1) and Debian (https://salsa.debian.org/nvidia-team/nvidia-cuda-toolkit/-/blob/master/debian/cuda.pc.in). If that's enough to consider them a de facto standard, we can certainly do the same. However, I'd also say that gstreamer should be more distro-agnostic here.

Note that libcuda.so should be linked using the toolkit _stub_ at compile-time, and rpath-patched using addOpenGLRunpath so it picks up the correct cuda driver from the running system. So I think the correct libdir for cuda.pc would be more like `${cudatoolkit}/lib/stubs`

**Comment by SomeoneSerge** [comment]
The new redist packages (everything under `cudaPackages` that begins with `cuda_` or `lib`) ships `.pc` files. There's another issue with them, we do not yet patch the FHS paths out: tracking in https://github.com/NixOS/nixpkgs/issues/224119

Didn't check the old run-file based cudatoolkit, feel free to re-open
