### ISSUE TITLE
enable i3pystatus tests

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#54409]
## Issue description

I am trying to update/run i3pystatus tests that rely on pulseaudio. Upon install, I get:
```
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
error: libpulse.so.0: cannot open shared object file: No such file or directory
```
It says here https://freedesktop.org/software/pulseaudio/doxygen/ that pkg-config files should be provided yet I could not find them in /nix/store/j94m58hwh98whjnwz4snfji3pjg3yb9a-libpulseaudio-12.2 (current nixos-unstable).
The package seems kinda complex so I prefer to leave it to maintainers @lovek323 @wkennington .

**Comment by teto** [comment]
Renamed the issue to better reflect the problem at hand. According to python's documentation, CDLL uses dlopen. Wouldn't it be easier to wrap/modify LD_LIBRARY_PATH instead of patching the source ?

**Comment by jtojnar** [comment]
I find it quite easy to patch the source, it will also let us know when it is no longer necessary. But environment variables are also fine when they can be used (for programs).

**Comment by teto** [comment]
I am not fond of patches since it makes hacking on the program more complex (you can't use `git commit --all`). Will look into it when I get more time.

**Comment by teto** [comment]
not critical .
