### ISSUE TITLE
libreoffice build failure

### ISSUE THREAD

**Issue by hlandau** [NixOS/nixpkgs#54436]
https://hydra.nixos.org/build/87671155
https://hydra.nixos.org/build/87573744

This is causing autoupdates to try and build libreoffice locally on 18.09 (argh).

(The HSQLDB segfault in the logs is interesting w.r.t. https://github.com/NixOS/nixpkgs/issues/54100, although that issue relates to ODBC I had issues getting HSQLDB working too.)

**Comment by worldofpeace** [comment]
Just saw someone in #nixos seeing this too.

> I wonder if it is related to staging-18.09 merge…

Probably.

**Comment by vcunat** [comment]
I see [no relevant changes](https://hydra.nixos.org/api/scmdiff?uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev1=69c050c60b97f12283a229f4e8644e5c9db9754e&type=git&rev2=a16476a93507e10201636cd2207c590fcd984cc4&branch=), so I just restarted it.

**Comment by vcunat** [comment]
I hope it was some rare random problem.
