### ISSUE TITLE
resilio sync listen to 0.0.0.0 by default

### ISSUE THREAD

**Issue by apeyroux** [NixOS/nixpkgs#54482]
## Issue description

By default resilio listen to 0.0.0.0. I wanted to know if it would not be more reasonable to listen on 127.0.0.1

https://github.com/NixOS/nixpkgs/blob/b43c4d8b758a3965067b24f3796cdd532756a2ce/nixos/modules/services/networking/resilio.nix#L112 

It is only an admin interface that has no influence on the other components of the application.

**Comment by yesbox** [comment]
Perhaps. According to this article the application default is 127.0.0.1.

https://help.resilio.com/hc/en-us/articles/115001184490-Configuring-WebUI-

On the other hand we have the firewall enabled by default.

**Comment by apeyroux** [comment]
ping @Mic92

**Comment by Mic92** [comment]
Yes. `[::1]` would be more sensible.
