### ISSUE TITLE
services.samba.syncPasswordsByPam broken because pam_smbpass.so doesn't exist

### ISSUE THREAD

**Issue by telotortium** [NixOS/nixpkgs#54492]
## Issue description

I tried to enable syncing Unix passwords to Samba via PAM using the `services.samba.syncPasswordsByPam` option. However, I see a bunch of errors in the logs because the library PAM is looking for, `pam_smbpass.so`, doesn't exist.

```
Jan 22 21:22:50 knuth sudo[32758]: PAM unable to dlopen(/nix/store/ib5shcyxd5bhyj9p2s0iyf4lc0pc0nxl-samba-4.7.10/lib/security/pam_smbpass.so): /nix/store/ib5shcyxd5bhyj9p2s0iyf4lc0pc0nxl-samba-4.7.10/lib/security/pam_smbpass.so: cannot open shared object file: No such file or directory
Jan 22 21:22:50 knuth sudo[32758]: PAM adding faulty module: /nix/store/ib5shcyxd5bhyj9p2s0iyf4lc0pc0nxl-samba-4.7.10/lib/security/pam_smbpass.so
```

### Steps to reproduce

Use the following config:

```
cfg.services.samba = {
  enable = true;
  syncPasswordsByPam = true;
};
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.85, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(USER): `"nixpkgs-19.03pre166683.088cb13aee0"`
 - channels(root): `"nixos-19.03pre166987.bc41317e243, nixos-unstable-19.03pre161545.7c73f53d836"`
 - nixpkgs: `/home/USER/.nix-defexpr/channels/nixpkgs`

**Comment by evanjs** [comment]
Same issue here.

The folder it was searching pam_smbpass.so for (`/nix/store/...-samba-4.10.4/lib/security/`) only contains `pam_winbind.so` on my system.

Additionally, querying [nix-locate](https://github.com/bennofs/nix-index) for `pam_smbpass.so` presents no results.

**Comment by Gonzih** [comment]
Just experienced exactly same issue on 19.03. Is samba broken in this release?

**Comment by doronbehar** [comment]
It's still relevant now. I noticed this issue in my system logs as well. Samba is not broken, they've just deprecated this feature. See https://superuser.com/a/478527/430539 and https://bugzilla.samba.org/show_bug.cgi?id=10669#c10 . Here's a PR for us: https://github.com/NixOS/nixpkgs/pull/96672
