### ISSUE TITLE
teensyduino: Doesn't build

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#54500]
## Issue description
The package teensyduino uses some very shady and dark magic for it's install process that involves starting up an X11 instance to run a graphical installer to go through the installation process.

Here's the code for this:
https://github.com/NixOS/nixpkgs/blob/2b5659dc04c4d163aca087bb0653337845bbdf34/pkgs/development/arduino/arduino-core/default.nix#L137-L175

And based on the comments it seems to be based on this script:
https://aur.archlinux.org/cgit/aur.git/tree/teensyduino.sh?h=teensyduino&id=f77cdf6bff83bf9b0a8edd2073881745f39777ff

But AUR manage to install this without that hacky way of doing it anymore:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=teensyduino

So we should probably go through and migrate from the old hacky way of doing this.

Latest build of this on hydra was about 2 years ago so it seems to have been broken for a while now: https://hydra.nixos.org/job/nixos/staging/nixpkgs.teensyduino.x86_64-linux

### Steps to reproduce
```
nix-shell -p teensyduino
```

Here's a build log that was pasted on IRC by another user: https://paste.ee/p/hz6he

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.94, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(etu): `""`
 - channels(root): `"nixos-19.03pre166987.bc41317e243, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @eHammarstrom

**Comment by puffnfresh** [comment]
I think it's building fine now.

**Comment by etu** [comment]
Yeah, seems like it does

**Comment by etu** [comment]
@puffnfresh Thanks :)
