### ISSUE TITLE
Could not find the Qt platform (When I open speedcrunch)

### ISSUE THREAD

**Issue by jackTaw88** [NixOS/nixpkgs#54507]
Hi,

I installed nix today on my Ubuntu 18.04. I installed speedcrunch and I get this error when I open speedcrunch:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

Exactly same problem applicable for krename.

I would be happy if someone help me.

Thank you

**Comment by matthewbauer** [comment]
Discussion on this issue is in https://github.com/NixOS/nixpkgs/issues/42893.

**Comment by jackTaw88** [comment]
When this will be fixed on production?
