### ISSUE TITLE
netsurf: broken functionality

### ISSUE THREAD

**Issue by S-NA** [NixOS/nixpkgs#54506]
## Issue description

Get netsurf onto your machine and attempt to execute it, notice how it is broken. 

Specifically nothing happens, other than the terminal (ST in this case) displays a single `\`. Trying another terminal such as Kitty or the Linux console spews a sequence of characters onto the display. Neither behavior is correct.

### Steps to reproduce

```
$ nix-shell --pure -p netsurf.browser
$ netsurf https://www.google.com
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre166987.bc41317e243"`
 - channels(sna): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fgaz** [comment]
That's because by default it uses the framebuffer. Try `netsurf.browser.override { uilib="gtk"; }`

**Comment by S-NA** [comment]
I do have sixel support patched into ST so it should work using the framebuffer build. I tested #54610 in ST and the Linux console and it ended up working with some problems already mentioned in the PR.

**Comment by stuv** [comment]
@fgaz Does it still support the framebuffer? It seems to set the GTK3 as the default.

When I try to build `netsurf.browser.override { uilib="framebuffer"; }`, I get the following error:

```
/nix/store/dx8hynidprz3kf4ngcjipnwaxp6h229f-binutils-2.40/bin/ld: build/Linux-framebuffer/frontends_framebuffer_font_internal.o:/build/netsurf-3.10/build/Linux-framebuffer/font-ns-sans.h:29: multiple definition of `fb_regular_sections'; build/Linux-framebuffer/build_Linux-framebuffer_font-ns-sans.o:/build/netsurf-3.10/build/Linux-framebuffer/font-ns-sans.c:1348: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:715: nsfb] Error 1
```

**Comment by S-NA** [comment]
Framebuffer still works. What happened is [newer versions of Clang and GCC have made `-fno-common` as the default](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678). `env.NIX_CFLAGS_COMPILE = "-fcommon"` should fix your error.

**Comment by stuv** [comment]
@S-NA This unfortunately still gave me the same error, but perhaps I didn't set the environment variable right.

nix repl:
NIX_CFLAGS_COMPILE = "-fcommon"
:l <nixpkgs>
:b netsurf.browser.override { uilib="framebuffer"; } 

The error mentions certain fonts specifically, not sure what is up with that.

Thanks for the pointer though!

**Comment by S-NA** [comment]
```
(netsurf.browser.override { uilib = "framebuffer"; }).overrideAttrs (old: { env.NIX_CFLAGS_COMPILE = "-fcommon"; })
```

**Comment by fgaz** [comment]
@stuv does that work for you? If so, we could apply the fix in nixpkgs
