### ISSUE TITLE
haskellPackages.brittany fails to build

### ISSUE THREAD

**Issue by ar1a** [NixOS/nixpkgs#54534]
## Issue description

haskellPackages.brittany fails to build https://github.com/lspitzner/brittany

```
Setup: Encountered missing dependencies:
hspec >=2 && <2.6
```

### Steps to reproduce

nix-env -f "<nixpkgs>" -iA haskellPackages.brittany

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.3, NixOS, 19.03pre167225.1b3affcbaa8 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre167225.1b3affcbaa8"`
 - channels(aria): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dkellner** [comment]
Jailbreaking `brittany` and `ministat` allows the current `master` of `brittany` to compile and it appears to be working at first glance. IMO this is just a workaround, a proper fix would be to change/fix the dependency boundaries upstream.

```nix
# ~/.config/nixpkgs/overlays/haskell.nix
self: pkgs:

let
  doJailbreak = pkgs.haskell.lib.doJailbreak;
  dontCheck = pkgs.haskell.lib.dontCheck;
in {
  haskell = pkgs.haskell // {
    packages = pkgs.haskell.packages // {
      ghc863 = pkgs.haskell.packages.ghc863.override {
        overrides = self: super: {

          brittany = doJailbreak (self.callCabal2nix "brittany"
            (pkgs.fetchFromGitHub {
              owner  = "lspitzner";
              repo   = "brittany";
              rev    = "6c187da8f8166d595f36d6aaf419370283b3d1e9";
              sha256 = "0nmnxprbwws3w1sh63p80qj09rkrgn9888g7iim5p8611qyhdgky";
              }) {});

          multistate = doJailbreak super.multistate;

        };
      };
    };
  };

  haskellPackages = self.haskell.packages.ghc863;
}
```

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(dkellner): `"unstable-19.03pre166987.bc41317e243"`
 - channels(root): `"nixos-19.03pre166987.bc41317e243"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by garry-cairns** [comment]
I'm also affected by this upon trying to upgrade to 19.03. @dkellner you mentioned fixing the boundaries upstream. Am I understanding correctly that you mean version bounds in brittany's cabal file? I'll game for trying to help but my enthusiasm outweighs my expertise here.

**Comment by dkellner** [comment]
@garry-cairns  Yes, with upstream I meant Brittany itself.

**Comment by CMCDragonkai** [comment]
Can this be reported to brittany upstream?

**Comment by Infinisil** [comment]
I just pushed [a fix](https://github.com/NixOS/nixpkgs/commit/1cfa5edf5a138136cf2cb04156957d8b315074e1) to haskell-updates which fixes the build. The working build should be available soon in the unstable channels (after haskell-updates has been merged to master and the hydra evaluation succeeded).

**Comment by ghuntley** [comment]
Lovely. Thank-you.
