### ISSUE TITLE
aws-sdk-cpp build failure

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#54545]
## Issue description
Not the first time: https://github.com/NixOS/nixpkgs/issues/20817. 

> [----------] Global test environment tear-down
> [==========] 266 tests from 41 test cases ran. (397 ms total)
> [  PASSED  ] 257 tests.
> [  FAILED  ] 9 tests, listed below:
> [  FAILED  ] DirectoryTreeTest.TestManualDirectoryTraversal
> [  FAILED  ] DirectoryTreeTest.TestDirectoryTreeDepthFirstTraversal
> [  FAILED  ] DirectoryTreeTest.TestDirectoryTreeEqualityOperator
> [  FAILED  ] DirectoryTreeTest.TestDirectoryTreeDiff
> [  FAILED  ] DirectoryTreeTest.TestDirectoryTreeBreadthFirstTraversal
> [  FAILED  ] DirectoryTreeTest.TestDirectoryTreeBreadthFirstTraversalGetAllFiles
> [  FAILED  ] DirectoryTreeTest.TestPathUtilsGetFileNameWithExt
> [  FAILED  ] DirectoryTreeTest.TestPathUtilsGetFileNameWithoutExt
> [  FAILED  ] DirectoryTreeTest.CreateDirectoryIfNotExistedTest
> 
>  9 FAILED TESTS
> make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:602: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
> make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
> make[1]: *** [CMakeFiles/Makefile2:455: aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 99%] Linking CXX executable aws-cpp-sdk-s3-integration-tests
> [ 99%] Built target aws-cpp-sdk-s3-integration-tests
> make: *** [Makefile:130: all] Error 2
> builder for '/nix/store/4gnqd6cb3878lhzy26f00ni57qs1cvqj-aws-sdk-cpp-1.5.17.drv' failed with exit code 2
> 

### Steps to reproduce
Use NixOS 18.09 (the one in the release channel) in a Docker container and try to use `aws-sdk-cpp` (which instead of download it from the cache tries to build it and fails). 

### Preferred solution
 bump 1.5.17 to the 1.6.something version in master (which is also out of date).

**Comment by erictapen** [comment]
I think this can be closed. `aws-sdk-cpp` builds on `nixos-19.03` as well as on `nixos-unstable`.
