### ISSUE TITLE
pantheon.switchboard-plug-onlineaccounts is non-functional

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#54557]
#### Issue Description
This means it's impossible for a user to connect to any online service within this plugin.
Major blocker for getting `pantheon-mail` packaged as it is reliant on this plugin for setup.

After trying to add service in the plug I see
```
** (.io.elementary.switchboard-wrapped_:23773): DEBUG: 15:17:33.587: WebDialog.vala:145: Found OAUTH Response : http://elementaryos.org/?token=@redacted@
** (.io.elementary.switchboard-wrapped_:23773): DEBUG: 15:17:33.769: ../libsignon-glib/signon-identity.c:725: 
** (.io.elementary.switchboard-wrapped_:23773): DEBUG: 15:17:33.777: ../libsignon-glib/signon-identity.c:529: identity_new_from_db_cb

** (.io.elementary.switchboard-wrapped_:23773): WARNING **: 15:17:33.777: identity_registered: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.PermissionDenied: Can not read identity
** (.io.elementary.switchboard-wrapped_:23773): DEBUG: 15:17:33.777: ../libsignon-glib/signon-identity.c:770: identity_store_info_ready_cb 770
** (.io.elementary.switchboard-wrapped_:23773): DEBUG: 15:17:33.777: ../libsignon-glib/signon-identity.c:777: IdentityError: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.PermissionDenied: Can not read identity
** (.io.elementary.switchboard-wrapped_:23773): DEBUG: 15:17:33.778: ../libsignon-glib/signon-identity.c:620: identity_session_object_destroyed_cb 620

** (.io.elementary.switchboard-wrapped_:23773): CRITICAL **: 15:17:33.778: Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.PermissionDenied: Can not read identity
```

**Comment by kisik21** [comment]
I tried adding a Microsoft account, and it presumably works? Not sure if anything's changed though, but it seemed to remember my credentials. Should I see anything in Files or Calendar maybe?

**Comment by worldofpeace** [comment]
There's even reports upstream that things don't work even upstream (at unreleased version) https://github.com/elementary/switchboard-plug-onlineaccounts/issues/145. Owncloud and onedrive should be linked, so IIRC Files should have support for that.

**Comment by kisik21** [comment]
Should we place a "wait for upstream" label?

**Comment by worldofpeace** [comment]
Added, but I've never properly looked into this because of aforementioned.

**Comment by bobby285271** [comment]
The plugin has been rewritten from scratch in elementary OS 6 so I guess this issue should no longer applies.
