### ISSUE TITLE
callCabal2nix to use lightweight cabal2nix?

### ISSUE THREAD

**Issue by ip1981** [NixOS/nixpkgs#54551]
I'm not completely sure, but apparently `callCabal2nix` executes "full" version of `cabal2nix` which depends on git, mercurial, python, etc. This is not necessary because we run it on a local package.

Perhaps, we could save some time and storage, and avoid unrelated build failures, if a bare version of `cabal2nix` were used?

**Comment by madjar** [comment]
This has been done in #81125!
