### ISSUE TITLE
Package Request: lldb-vscode

### ISSUE THREAD

**Issue by jethrokuan** [NixOS/nixpkgs#54563]
## Issue description

Package request for providing `lldb-vscode`

https://github.com/llvm-mirror/lldb/tree/master/tools/lldb-vscode

This provides an interface that works with language server protocols, for debugging purposes.

**Comment by tadeokondrak** [comment]
added!

**Comment by jethrokuan** [comment]
Thanks! I ended up using ccls in the meantime, and that works great too. https://github.com/NixOS/nixpkgs/pull/53888
