### ISSUE TITLE
mediathekview depends on OracleJRE

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#54560]
## Issue description

No. I don't want to do that!

I just want to use some program written in java.

Could we use a different java variant by default?

Or is this a special case of mediathekview?

/cc maintainers @Moredread @chaoflow.

### Steps to reproduce

```
[root@imac:~]$ nix-env -i mediathekview -f /home/davidak/nixpkgs
warning: there are multiple derivations named 'mediathekview-13.2.1'; using the first one
installing 'mediathekview-13.2.1'
error: You must accept the Oracle Binary Code License Agreement for Java SE at
https://www.oracle.com/technetwork/java/javase/terms/license/index.html
by setting nixpkgs config option 'oraclejdk.accept_license = true;'
```

## Technical details

My nixpkgs is on branch staging.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03.git.8291376 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-18.09.1829.0396345b794, nixos-hardware, nixos-unstable-19.03pre164715.201d739b0ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by 7c6f434c** [comment]
```
   # mediathekview needs JavaFX, which currently only is available inside OracleJRE
  # we might be able to get rid of it, as soon as we have an OpenJRE with OpenJFX included
```

**Comment by Moredread** [comment]
Yes, sorry, that is a bit unfortunate at the moment. I thought it would be better to have a working package using OracleJRE in the meantime, as older versions of mediathekview don't work anymore.

qmediathekview might be an alternative, but I haven't tried playing a video yet.

**Comment by Moredread** [comment]
Still relevant
