### ISSUE TITLE
vim segfaults when executing python command

### ISSUE THREAD

**Issue by bawolk** [NixOS/nixpkgs#5457]
After installing  python and vim_configrable via
$ nix-env -iA nixos.pkgs.pythonFull
$ nix-env -iA nixos.pkgs.vimNox

I ran
$ vim
which seemed functional until I tried the command
:python print "Hi"
which immediatelty segfaulted

[bruce@nixos:~]$ vim
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault

**Comment by jagajaga** [comment]
Do you still have this issue?

**Comment by bawolk** [comment]
I found NixOS a little too frustrating so I gave up on trying to
    make things work.
    
    On 10/13/2015 03:16 PM, Arseniy Seroka
      wrote:
    
    
      
      Do you still have this issue?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jagajaga** [comment]
I do not have it, so I'll close.
