### ISSUE TITLE
undeclared identifier '__inline_isnanl' on Darwin

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#54586]
## Issue description

Compiling a C file with clang fails on Darwin if `__inline_isnanl` is used.
Other `__inline_isnan*` symbols can be found which is strange because they all are in the same math.h header file provided by the MacOS SDK (https://github.com/NixOS/nixpkgs/blob/c7ab795274fab9206de81f4ad81bc544d2c9fd1b/pkgs/os-specific/darwin/apple-sdk/default.nix)

### Steps to reproduce

Insert following code into file `test.nix` and run with `nix-build test.nix`.
The compilation fails because `__inline_isnanl` can not be found.

```
let
  nixpkgsRev = "6ad1271a4c285500268f3315f3f519ff6bedb8e5";
  nixpkgs = builtins.fetchTarball "github.com/NixOS/nixpkgs/archive/${nixpkgsRev}.tar.gz";
  pkgs = import nixpkgs {};

  file = pkgs.writeText "test.cpp" ''
    // From /nix/store/gxfgp163zd6v3jzksyg6rgxdjwlxhggc-MacOS_SDK-10.10/include/math.h
    #include <math.h>
    int test1(float r)
    {
      return __inline_isnanf(r);
    }
    int test2(double r)
    {
      return __inline_isnand(r);
    }
    int test3(long double r)
    {
      return isnan(r);
    }
    int test4(long double r)
    {
      // This fails
      return __inline_isnanl(r);
    }
  '';
in
  pkgs.runCommand "compile" {} ''
    mkdir $out
    cd $out
    pwd
    ${pkgs.clang}/bin/clang -c ${file} -o $out/test.o
  ''
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixpkgs-18.03-darwin"`
 - channels(thomad): `"nixpkgs-18.03-darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by matthewbauer** [comment]
We don't use the math.h from the SDK. We use the open source ones apple release which is called Libm. Unfortunately, they haven't made a release for Libm since 10.7.

https://news.ycombinator.com/item?id=8502968

**Comment by ThomasMader** [comment]
Why is `MACOSX_DEPLOYMENT_TARGET` set to `10.10` on my machine in the env-vars when running a build when `10.7` is the highest supported?
This is the reason the package I am building is trying to get this symbol as it thinks it's available. Otherwise it would have chosen a compatible symbol to the older version.

**Comment by matthewbauer** [comment]
Yeah most of our stuff is 10.10/10.11ish. libm is the main exception I think. We probably shouldn't set MACOSX_DEPLOYMENT_TARGET and make software rely on feature detection though.

We don't want users to have to accept the Xcode agreement. By using that header, I think it could make us technically fall under that agreement:

https://www.apple.com/legal/sla/docs/xcode.pdf

Maybe we can patch it though? I'm not sure what needs __inline_isnanl vs just plain old isnan though?

/cc @copumpkin

**Comment by matthewbauer** [comment]
We may be able to use freebsd's math.h as an alternative:

https://github.com/freebsd/freebsd/blob/1d6e4247415d264485ee94b59fdbc12e0c566fd0/lib/msun/src/math.h#L211

**Comment by ThomasMader** [comment]
It is fixed upstream now with std::isnan. (https://github.com/ldc-developers/ldc/pull/2986)
