### ISSUE TITLE
Can't figure out why nix does not try to fetch from hydra

### ISSUE THREAD

**Issue by netixx** [NixOS/nixpkgs#54589]
## Issue description
Hello,

Can you help me figure out out why nix rebuilds package locally instead of fetching from hydra for one single package (jre8_headless) in my nixos setup ? I didn't find any command that would tell me why that is...

## configuration and tests
I have a custom nixpkgs location (/var/nixpkgs) since (because I have some PR that are not merged yet).

Below are relevant extracts from my configuration.nix, where /var/nixpkgs is actually [this](https://github.com/netixx/nixpkgs/tree/nixos-stable-custom), which is current channels/nixos-18.09 + one commit.
```
services.unifi = {
    enable = true;
    jrePackage = pkgs.jre8_headless;
  };

nix.nixPath = [
    "nixpkgs=/var/nixpkgs"
    "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs"
    "nixos-config=/etc/nixos/configuration.nix"
    "/nix/var/nix/profiles/per-user/root/channels"
  ];
```

Here is the output of the upgrade (it's the same without `--upgrade`):
```
 # nixos-rebuild switch --upgrade 
unpacking channels...
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/cgyg73dig1f0b89m6vsiqg4znj1sw88i-openjdk-8u202bga.drv
  /nix/store/900bmc74kddj6ppr3wv65fqfxyzv3jp7-unit-unifi.service.drv
  /nix/store/biq51vv1k3ll5xaaxqvl0i8kxmn6s343-system-units.drv
  /nix/store/imbq3y7qlcpgm7fvvhm0yn56zkjcwfxg-etc.drv
  /nix/store/ixy4xkw8dj9bky9fss7974n46vxbc906-nixos-system-fw01-18.09pre-git.drv
building '/nix/store/cgyg73dig1f0b89m6vsiqg4znj1sw88i-openjdk-8u202bga.drv'...
unpacking sources
unpacking source archive /nix/store/2xma7kr68wp2kl68mr07lwa3hrwj2x5h-jdk8u202-ga.tar.gz
unpacking source archive /nix/store/n66f7k052r38gihyp8fhd5viza56m6an-jdk8u202-ga.tar.gz
unpacking source archive /nix/store/pwsnbn2jkxrcipl35np3a22nmp0yvrck-jdk8u202-ga.tar.gz
unpacking source archive /nix/store/r26p4jf666a4288njg8gp7hknc06czmp-jdk8u202-ga.tar.gz
unpacking source archive /nix/store/n2ndl23yzqnyjiyqgivhzf7jb3awvs8i-jdk8u202-ga.tar.gz
```

When I install it manually using nix-env, it **is** fetch from hydra:
```
# nix-env -iA nixos.jre8_headless
installing 'openjre-8u202bga-headless'
these paths will be fetched (78.05 MiB download, 185.24 MiB unpacked):
  /nix/store/g19k7faid8g14ar1czld5414mz0s05z5-openjdk-8u202bga-jre
  /nix/store/xwxaspmixi1q2i5wx9syzxvc55xl5qvg-openjdk-8u202bga
copying path '/nix/store/g19k7faid8g14ar1czld5414mz0s05z5-openjdk-8u202bga-jre' from 'https://cache.nixos.org'...
copying path '/nix/store/xwxaspmixi1q2i5wx9syzxvc55xl5qvg-openjdk-8u202bga' from 'https://cache.nixos.org'...
building '/nix/store/3986w1rcpmd75z9r0y9dly8w30fsx760-user-environment.drv'...
created 15 symlinks in user environment
```

```
# nix-channel --list
nixos https://nixos.org/channels/nixos-18.09
unstable https://nixos.org/channels/nixos-unstable
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 18.09pre-git (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1985.749a3a0d00b, unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/var/nixpkgs`

**Comment by seqizz** [comment]
You can use the nix-diff utility to check where 2 .drv files are different. Output won't be so pleasant, but it's a start to give some ideas. Maybe some option you thought it was unrelated is affecting. I had the same issue with libreoffice lately, yet couldn't determine the root of the issue.

**Comment by netixx** [comment]
Turns out `cups` is required even on for a headless build [...](http://cr.openjdk.java.net/~ihse/demo-new-build-readme/common/doc/building.html#external-library-requirements)

I guess the problem is that hydra does not build the package specified by the `nixos/modules/config/no-x-libs.nix` overlay.

Is there any way to make hydra build those package as well ?
Or can I force the use of the standard/x11 package for java (ignoring the overlay set by `noXlibs`) ?

**Comment by roberth** [comment]
@netixx you can force unset the overlay with `nixpkgs.overlays = lib.mkForce []`, although `environment.noXlibs = false` is a more reliable solution because it won't cause unexpected interactions between the rest of that module and the lack of an overlay.
Ideally we'd build this overlay on hydra, which was already requested here https://github.com/NixOS/nixpkgs/issues/29135#issuecomment-859685945

I believe this covers your issue. If I missed something, let me know or create a new issue (it's good to keep issues focused)
