### ISSUE TITLE
[nix] Useless usermod comment change in standard install script

### ISSUE THREAD

**Issue by bew** [NixOS/nixpkgs#54595]
Arriving user here, like most of you (I guess) I fell in love with nix (and soon with nixos too ^^)

OS: Archlinux
Linux version: `4.19.16-1-lts`

I noticed that during the standard installation using `sh <(curl https://nixos.org/nix/install) --daemon`, I get:
```
~~> Setting up the build user nixbld32

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo useradd --home-dir /var/empty --comment Nix build user 32 --gid 30000 --groups nixbld --no-user-group --system --shell /sbin/nologin --uid 30032 --password ! nixbld32

Creating the Nix build user, nixbld32

           Created:	Yes
            Hidden:	Yes
    Home Directory:	/var/empty

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo usermod --comment Nix build user 32 nixbld32

in order to give nixbld32 a useful comment

usermod: no changes
              Note:	Nix build user 32
   Logins Disabled:	Yes
  Member of nixbld:	Yes
    PrimaryGroupID:	30000
```

The 2 displayed commands are:
```
sudo useradd --home-dir /var/empty --comment Nix build user 32 --gid 30000 --groups nixbld --no-user-group --system --shell /sbin/nologin --uid 30032 --password ! nixbld32
sudo usermod --comment Nix build user 32 nixbld32
```

The second command is useless, since the comment was already set in the first command. And we can see in the output that the second command said `usermod: no changes`.

**Comment by joachifm** [comment]
Hi, I think you're more likely to catch the attention of the right people by moving this issue to the Nix issue tracker: https://github.com/NixOS/nix

**Comment by bew** [comment]
You're right, thanks! I made an issue there (https://github.com/NixOS/nix/issues/2659)
