### ISSUE TITLE
mutableUsers = false, but users can still set their passwords

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#5459]
I think this would be a good idea, since normally you still want to have declarative group management, but the user should be able to set their password without the help of root.

**Comment by copumpkin** [comment]
:+1:

**Comment by Profpatsch** [comment]
I “solved” it by:

```nix
rec {
  home = …
  passwordFile = "${home}/.config/passwd";
};
```

This enables changing the password on the next switch. The file contains a password hashed by `mkpasswd(1)`.
