### ISSUE TITLE
systemd resolved's resolvconf compatibility is broken

### ISSUE THREAD

**Issue by bchallenor** [NixOS/nixpkgs#54617]
systemd's resolvectl has a compatibility mode for resolvconf, if resolvectl is invoked via a symlink with that name. (resolvconf is usually provided by openresolv. It is used by e.g. vpnc and wireguard to add and remove nameservers.)

This is a [pretty new feature](https://github.com/systemd/systemd/issues/7202), though, and it is broken in the nixpkgs systemd fork. The bug is an [upstream issue](https://github.com/systemd/systemd/issues/9423) that has since been [fixed](https://github.com/systemd/systemd/commit/5a01b3f35d7b6182c78b6973db8d99bdabd4f9c3).

The fix we need is in fact [already cherry picked](https://github.com/NixOS/systemd/commit/d943caddd03db343e2f3217da40bf5754b865e11) into the nixos systemd repo, and it was briefly live before we switched to the Debian systemd patches. I can confirm that pinning to a [version](https://github.com/NixOS/nixpkgs/commit/a7912ecc85af6cd9091eb913a114a08baf5312e6) of nixpkgs that includes this commit fixes the issue - the problem is that these patches were reverted in favour of the Debian ones. 

Is there any way to get this fix into nixpkgs again, or do we have to wait until v240?

**Comment by bchallenor** [comment]
@fpletz @vcunat

**Comment by fpletz** [comment]
We're trying to get systemd 240 into 19.03 which seems to fix this.

**Comment by jameysharp** [comment]
I guess 19.03 still had systemd 239, but nixpkgs master now has systemd 242. So is this issue... resolved? (Pun intended)

**Comment by arianvp** [comment]
19.09 has `243` so I assume this is fixed

**Comment by bchallenor** [comment]
Yes, this is fixed with systemd 243, thanks:
```
$ resolvconf --version
systemd 243 (243)
+PAM +AUDIT -SELINUX +IMA +APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

$ grep nameserver /run/systemd/resolve/resolv.conf
nameserver 1.1.1.1

$ echo nameserver 8.8.8.8 | sudo resolvconf -a wlan0 

$ grep nameserver /run/systemd/resolve/resolv.conf
nameserver 8.8.8.8

$ sudo resolvconf -d wlan0 

$ grep nameserver /run/systemd/resolve/resolv.conf
nameserver 1.1.1.1
```
