### ISSUE TITLE
lightdm/plasma5: after suspend no username and password field is shown

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#54636]
## Issue description
After `sudo systemctl suspend`, and getting it out of sleep again, no username and password field is shown until I press `Control-Alt-F1` and then `Control-Alt-F7`. 

Any possible fix should be backported to `18.09`.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.93, NixOS, 18.09.git.749a3a0 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Please report whether this is still an issue.
