### ISSUE TITLE
Zoneminder auto-upgrades are not supported

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#54630]
## Issue description
https://github.com/NixOS/nixpkgs/pull/53495 added Zoneminder, but it seems there is no code that handles upgrades, while that is provided by upstream and for example the Ubuntu packaging.

It seems to be more of a developer preview version on NixOS than something that could be used by end-users in a production environment. I would have added a flag like `service.zoneminder.i_am_a_developer_and_know_this_breaks_on_upgrades` that needs to be set to true before it does something for that reason.   
 
I welcome the progress that has been made, but it doesn't appear to be in good enough shape to compete with other solutions. 

I will open another issue for adding declarative camera support (https://github.com/NixOS/nixpkgs/issues/54631), because there was another user who also wanted to have that, which should also make this issue smaller.

**Comment by veprbl** [comment]
Looking at zoneminder_1.30.4+dfsg-2.debian.tar.xz in debian/TODO.Debian it says:
```
### Run `zmupdate.pl` from service control scripts (init.d, service) on start?

 Automatic upgrade will break "one DB, many zoneminders" setup (unimportant?).
```
and no other mention of zmupdate.pl. Are you sure Ubuntu has support for this?

My personal opinion is that automatic upgrades are not such a great thing. While there are provided migrations to upgrade the database, there doesn't seem to be an official way to downgrade. This conflicts with the nature of Nix where we expect seamless version changes in any direction. Having user manually run zmupdate.pl ensures that they are aware of the upgrade and prepared for consequences.

**Comment by memberbetty** [comment]
https://zoneminder.readthedocs.io/en/stable/installationguide/ubuntu.html has recently changed, but I have seen it upgrade automatically and there was at some point some code for doing it automatically. 

The manual part here only seems to be the ppa configuration. 

The main point is that the effort required on Ubuntu is less than on NixOS.

**Comment by veprbl** [comment]
Yes, I see that this PPA with an unofficial zoneminder package (from Ubuntu standpoint) does indeed run zmupdate.pl in its zoneminder.postinst script.

**Comment by peterhoeg** [comment]
I wasn't aware of this issue until just now, hence the rather late reply.

> #53495 added Zoneminder, but it seems there is no code that handles upgrades, while that is provided by upstream and for example the Ubuntu packaging.

That is correct - so far we have only released a single version in nixpkgs but of course it will come back and bite us.

> It seems to be more of a developer preview version on NixOS than something that could be used by end-users in a production environment. I would have added a flag like service.zoneminder.i_am_a_developer_and_know_this_breaks_on_upgrades that needs to be set to true before it does something for that reason.

Things can break in unstable - nothing new there and unless we hit security issues, new versions will not be back-ported, so that at least gives us to 19.09 to sort out.

> I welcome the progress that has been made, but it doesn't appear to be in good enough shape to compete with other solutions.

What other options (packaged for NixOS) do we have? I personally have very strong reservations about the architectural choices the ZM developers have made, but I am not aware of any real alternative ATM.

> I will open another issue for adding declarative camera support (#54631), because there was another user who also wanted to have that, which should also make this issue smaller.

Declarative camera support is definitely a good idea. I added support for ZM because I needed it and it solves my problem right now (until we need to update of course), but any PR would be very much welcome.

**Comment by peterhoeg** [comment]
The ```zmupdate.pl``` is already part of the package - we just don't do anything with it and according to the comment in the header:

```
This script just checks what the most recent release of ZoneMinder is
at the the moment. It will eventually be responsible for applying and
configuring upgrades etc, including on the fly upgrades
```

But then of course it does have functionality for dealing with a number of changes.

So the short version - someone just has to write (and test) how it behaves when upgraded and ensure this runs. I am realistically not going to work on that right now though.
