### ISSUE TITLE
buildFHSUserEnv can't run installer

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#54647]
## Issue description

Unfortunately, sometimes there is no way to avoid proprietary software with a custom installer. Currently `buildFHSUserEnv` cannot accommodate such packages as it offers no way to allow the user to run the installer within the chroot during its construction.

Ideally `buildFHSUserEnv` would accept another attribute (call it `extraSetupCommands`) which would be run within the chroot after it has been built.

**Comment by bgamari** [comment]
ccing @abbradar, @yegortimoshenko due to their previous work on `buildFHSUserEnv`.

**Comment by yegortimoshenko** [comment]
`buildFHSUserEnv` can run installers, a la carte, if you consider proprietary software installer to be a kind of archive to be unpacked in `unpackPhase`. Here is an example: https://gitlab.com/yegortimoshenko/nixos-systems/blob/d9b9085ea10cbb4dd6fc6f8505ae458d874cf7bf/pkgs/excelsiorJET/default.nix#L18

**Comment by bgamari** [comment]
Interesting; this is indeed a viable path forward I think. Thanks, @yegortimoshenko.

**Comment by yegortimoshenko** [comment]
If you encounter any issues with this approach, I'll be happy to help!

**Comment by ryanfitzsimon** [comment]
@yegortimoshenko the example you linked to doesn't seem to be available (404 error).

Would it be possible to add a copy inline for people like myself finding this issue page when searching for a way to run installers?

**Comment by yegortimoshenko** [comment]
@ryanfitzsimon I updated the URL. Not sure what would be a good way to inline it if not the whole derivation.

```nix
{ stdenv, requireFile, buildFHSUserEnv, makeWrapper, patchelfUnstable
, libX11, libXext, libXi, libXrender, libXtst }:

stdenv.mkDerivation rec {
  name = "excelsiorJET-${version}";
  version = "12.0";

  src = requireFile rec {
    name = "jet-1200-eval-en-linux-amd64.bin";
    url = https://www.excelsiorjet.com/evaluate;
    sha256 = "1kfs55bp976b66h3qwi9fxv3jc2zn88xj5k8j7k2nni32x21v071";
  };

  nativeBuildInputs = [ makeWrapper ];
  buildInputs = [ patchelfUnstable ];
  phases = [ "unpackPhase" "installPhase" "fixupPhase" ];

  unpackEnv = buildFHSUserEnv {
    name = "${name}-unpackEnv";
    runScript = "./${src.name} -batch -no-aftrun";
  };

  unpackPhase = ''
    cp $src ${src.name}
    chmod +x ${src.name}
    ${unpackEnv}/bin/${unpackEnv.name}
  '';

  sourceRoot = "jet${version}-eval-amd64";

  installPhase = ''
    mkdir $out
    rm -f bin/{install.log,jetsetup,renameprofile,x{un,}inst*,uninstall,zip}
    mv bin lib profile* $out
  '';

  fixupPhase = ''
    makeWrapper() {
      echo -e "#!$SHELL\n$1 \$@" >> $2
      chmod +x $2
    }

    local ld=$(< $NIX_CC/nix-support/dynamic-linker)
    for f in $(find $out/bin ! -name \*.so -type f -exec patchelf {} \; -print); do
      patchelf --set-interpreter $ld $f || true
    done

    local awt=$out/bin/rt/lib/amd64/libawt_xawt.so
    patchelf --set-rpath $(patchelf --print-rpath $awt):${stdenv.lib.makeLibraryPath [
      libX11
      libXext
      libXi
      libXrender
      libXtst
    ]} $awt

    wrapProgram $out/bin/xlink
    echo "${patchelfUnstable}/bin/patchelf --set-interpreter $ld \$(basename \$1 .rsp)" >> $out/bin/xlink
  '';
}
```

**Comment by ryanfitzsimon** [comment]
@yegortimoshenko Awesome, thank you!

**Comment by yegortimoshenko** [comment]
https://youtu.be/2JxEyYQXA28 ^_^
