### ISSUE TITLE
gimp failed to build on macOS Mojave

### ISSUE THREAD

**Issue by asariley** [NixOS/nixpkgs#54642]
## Issue description

I tried to install gimp on Mac OS Mojave and got a build error. The error seems to be a similar flavor to the one found in #41071. However, I ran `nix-channel --update` to make sure the fix for that is in my version of nixpkgs and the actual error message is different so I am making a new issue. 

Error text:

      CC     unix_la-unix.lo
    /nix/store/9b5p08gmyh0p3vxy4zgnwb23k2d3k8fn-bash-4.4-p23/bin/bash ../libtool --silent --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I.. -I../glib -I../gobject -I/nix/store/b8y1f5r258lf4g1l7rffii89iwdnby40-python-2.7.15/include/python2.7  -I/nix/store/bxav0i5rf4mm4mr1v3xk4kj0gf5yj22f-glib-2.58.2-dev/include -I/nix/store/bxav0i5rf4mm4mr1v3xk4kj0gf5yj22f-glib-2.58.2-dev/include/glib-2.0 -I/nix/store/x685vpk75a3kad1kgy4axwxqdmqs9snx-glib-2.58.2/lib/glib-2.0/include   -I/nix/store/bxav0i5rf4mm4mr1v3xk4kj0gf5yj22f-glib-2.58.2-dev/include/gio-unix-2.0 -I/nix/store/bxav0i5rf4mm4mr1v3xk4kj0gf5yj22f-glib-2.58.2-dev/include -I/nix/store/bxav0i5rf4mm4mr1v3xk4kj0gf5yj22f-glib-2.58.2-dev/include/glib-2.0 -I/nix/store/x685vpk75a3kad1kgy4axwxqdmqs9snx-glib-2.58.2/lib/glib-2.0/include -g -O2 -Wall -fno-strict-aliasing -std=c9x -c -o unix_la-unix.lo `test -f 'unix.c' || echo './'`unix.c
    unix.override:27:10: fatal error: 'gio/gdesktopappinfo.h' file not found
    #include <gio/gdesktopappinfo.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make[2]: *** [Makefile:544: unix_la-unix.lo] Error 1
    make[2]: Leaving directory '/private/var/folders/sc/jqmq26wd7zzf_l8q1td0vs540000gn/T/nix-build-python2.7-pygobject-2.28.6.drv-0/pygobject-2.28.6/gio'
    make[1]: *** [Makefile:615: all-recursive] Error 1
    make[1]: Leaving directory '/private/var/folders/sc/jqmq26wd7zzf_l8q1td0vs540000gn/T/nix-build-python2.7-pygobject-2.28.6.drv-0/pygobject-2.28.6'
    make: *** [Makefile:376: all] Error 2
    builder for '/nix/store/pql3y84xy70rx7vs4l0m4m060bfa3xqp-python2.7-pygobject-2.28.6.drv' failed with exit code 2
    cannot build derivation '/nix/store/fspj3s522cf2czcpsc6wcbkz033l2l0x-python2.7-pygtk-2.24.0.drv': 1 dependencies couldn't be built
    cannot build derivation '/nix/store/gxfwwjvqapq8s1zvmm8nf8f3fzpla2qd-gimp-2.10.8.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/gxfwwjvqapq8s1zvmm8nf8f3fzpla2qd-gimp-2.10.8.drv' failed

### Steps to reproduce

    nix-env -i -A nixpkgs.gimp

## Technical details

     - system: `"x86_64-darwin"`
     - host os: `Darwin 18.2.0, macOS 10.14.2`
     - multi-user?: `no`
     - sandbox: `no`
     - version: `nix-env (Nix) 2.1.3`
     - channels(asariley): `"nixpkgs-19.03pre167327.11cf7d6e1ff"`
     - nixpkgs: `/Users/asariley/.nix-defexpr/channels/nixpkgs`

**Comment by jtojnar** [comment]
Yes, it is the same issue only in different package: https://gitlab.gnome.org/GNOME/pygobject/blob/pygobject-2-18/gio/unix.override
