### ISSUE TITLE
ardour reports wrong version number

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#5468]
Hi @cillianderoiste,

Even though we build from git tag 3.5.403, `ardour --version` reports
3.5-380-g2f6065b.

This is because we're building from a git tree, but without the .git/ directory, so our (manually cached) version info that is built into ardour has gotten out of sync.

Unfortunately the two version numbers have different format, so either we have to maintain two version numbers, or let ardour figure this out on its own by using a full/deep git clone and leaveDotGit.

Do you have any opinion on this?

I have a WIP commit to fix this here:

https://github.com/bjornfor/nixpkgs/commit/e267751dd145056ac012779e4032ba6fade1e46f

This issue is also why I created https://github.com/NixOS/nixpkgs/pull/5252, because there is currently no way to tell fetchgit to do a deep clone.

**Comment by bjornfor** [comment]
Fixed (worked around manually) in master (0e3007ec886948889bc634a88b3396b4ed01e7ee) and release-14.12 (3cb749f796307f007b119c95377dcd73f279289e).

**Comment by cillianderoiste** [comment]
Thanks @bjornfor. Sorry for not responding, I never noticed this ticket.

**Comment by bjornfor** [comment]
@cillianderoiste: No problem :-)
