### ISSUE TITLE
Building Firefox overlay fails on 18.09

### ISSUE THREAD

**Issue by kampka** [NixOS/nixpkgs#54714]
## Issue description

When trying to build Firefox using an overlay, the build fails with 
```
checking for references to /build in /nix/store/zncsw3cy28783r1fwaaxm6psqlcdw8i3-firefox-unwrapped-64.0...
running install tests
Mozilla Firefox 64.0
building '/nix/store/y7hpcn55yn23ayyh63a4v0r9qy5hrrs9-firefox-64.0.drv'...
output '/nix/store/dbhm9bzgps2957zmgxamz7mblvydsf2a-firefox-64.0' is not allowed to refer to the following paths:
      /nix/store/nwy73lby94rv8jql92xhxp0wx6gxwjb2-gcc-wrapper-7.3.0
cannot build derivation '/nix/store/hjd8fr6c7qdgvbc3pqqx4c59wznq341n-user-environment.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pa41fwq8cbgjk78xxn3zfxpn2yrlqp6i-etc.drv': 1 dependencies couldn't be built
```

### Steps to reproduce

Enable this overlay:
https://gist.github.com/kampka/73e9b20fc0419ae549a5ac508bcf578d

Run `nixos-rebuils switch`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.93, NixOS, 18.09.1985.749a3a0d00b (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1985.749a3a0d00b, nixos-hardware, unstable-19.03pre166987.bc41317e243"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
Well, that's a problem in the overlay, apparently :-)  We have a pre-caution check that the firefox output doesn't retain references to compiler, and that gets broken (looking at the error).

**Comment by vcunat** [comment]
I use stuff like
```
grep nwy73lby94rv8jql92xhxp0wx6gxwjb2 -R /nix/store/dbhm9bzgps2957zmgxamz7mblvydsf2a-firefox-64.0
```

**Comment by kampka** [comment]
If it were that easy... :)
Empty result of course, nothing points to or links with anything gcc or the mentioned derivation.

**Comment by FlorianFranzen** [comment]
If the result is empty, what triggers the error message?

**Comment by pschuprikov** [comment]
The problem is with `env-vars` being moved to the output of the `librefox` derivation, and later to `firefox`. If the issue is still relevant I could suggest replacing `setSourceRoot` with

```
preUnpack = ''
  mkdir src
  cd src
'';
sourceRoot = "."; 
```

**Comment by vcunat** [comment]
This does seem stale, and I don't think it was any issue with nixpkgs itself anyway... well the current wrapper isn't "designed" for this, but if it should cover librefox, the expression should be in nixpkgs.
