### ISSUE TITLE
how can i get chromium with widevine working?

### ISSUE THREAD

**Issue by gallexme** [NixOS/nixpkgs#54723]
## Issue description

> copying path '/nix/store/2jyg0cfjj7p6fb5li0bnvmx7i81asbsr-clang-wrapper-7.0.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/f8gb03c18f0klsrimx6xv2qb21n958sb-stdenv-linux' from 'https://cache.nixos.org'...
> building '/nix/store/9ixr3f53hb5awnw1bda0mrzij6vhivqs-chromium-binary-plugin-widevine.drv'...
> unpacking sources
> unpacking source archive /nix/store/4id4ni9vysxb665cwm6l9aj2p0j88kn0-google-chrome-stable_71.0.3578.98-1_amd64.deb
> tar: ./opt/google/chrome/libwidevinecdmadapter.so: Not found in archive
> tar: Exiting with failure status due to previous errors
> do not know how to unpack source archive /nix/store/4id4ni9vysxb665cwm6l9aj2p0j88kn0-google-chrome-stable_71.0.3578.98-1_amd64.deb
> builder for '/nix/store/9ixr3f53hb5awnw1bda0mrzij6vhivqs-chromium-binary-plugin-widevine.drv' failed with exit code 1
> cannot build derivation '/nix/store/nv36nc1xxf72zigqcmr5cfsz25fcf97b-chromium-71.0.3578.98.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/0vbgayd8ffdrnnlf4pplcmj1j6lidx9r-home-manager-path.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/g9wvwdas7r1v5w83fz84daac74wyki50-home-manager-generation.drv': 1 dependencies couldn't be built
> error: build of '/nix/store/g9wvwdas7r1v5w83fz84daac74wyki50-home-manager-generation.drv' failed
> 

### Steps to reproduce

```
nixpkgs.config = {
    allowUnfree = true;
    allowBroken=true;
    chromium = {
      enableWideVine = true;
    };
  };


```
```
  programs = {
    chromium.enable = true;
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 

> nix-shell -p nix-info --run "nix-info -m"
> these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
>   /nix/store/zqgiswxcs5714xgmrk69y1k67liqimg3-bash-interactive-4.4-p23-dev
> copying path '/nix/store/zqgiswxcs5714xgmrk69y1k67liqimg3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
>  - system: `"x86_64-linux"`
>  - host os: `Linux 4.19.16, NixOS, 19.03pre166987.bc41317e243 (Koi)`
>  - multi-user?: `yes`
>  - sandbox: `yes`
>  - version: `nix-env (Nix) 2.2`
>  - channels(fabi): `"nixos-unstable-19.03pre165037.eebd1a92637, nixpkgs-unstable-19.03pre165281.7d864c6bd63, stable-18.09.1853.c2950341d03"`
>  - channels(root): `"nixos-19.03pre166987.bc41317e243, home-manager"`
>  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bendlas** [comment]
Should work now
