### ISSUE TITLE
NixOS installer: ata5 error "READ DMA EXT" failed on healthy disk

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#5474]
# Description

When installing **NixOS 14.04.593** from an USB-stick I get an *ata5* error:

```
Dec 26 08:58:49 nixos kernel: ata5: lost interrupt (Status 0x7f)
Dec 26 08:58:49 nixos kernel: ata5: drained 65536 bytes to clear DRQ
Dec 26 08:58:49 nixos kernel: ata5.01: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x0 frozen
Dec 26 08:58:49 nixos kernel: ata5.01: failed command: READ DMA EXT
Dec 26 08:58:49 nixos kernel: ata5.01: cmd 25/00:08:80:df:42/00:00:25:00:00/f0 tag 0 dma 4096 in
                                       res 40/00:00:00:00:00/00:00:00:00:00/10 Emask 0x4 (timeout)
Dec 26 08:58:49 nixos kernel: ata5.01: status: { DRDY }
Dec 26 08:58:49 nixos kernel: ata5.00: hard resetting link
Dec 26 08:58:50 nixos systemd-udevd[2332]: worker [2344] /devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:1/4:0:1:0/block/sda/sda1 timeout; kill it
Dec 26 08:58:50 nixos systemd-udevd[2332]: seq 2043 '/devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:1/4:0:1:0/block/sda/sda1' killed
Dec 26 08:58:50 nixos systemd-udevd[2332]: worker [2345] /devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:1/4:0:1:0/block/sda/sda2 timeout; kill it
Dec 26 08:58:50 nixos systemd-udevd[2332]: seq 2044 '/devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:1/4:0:1:0/block/sda/sda2' killed
Dec 26 08:58:50 nixos kernel: ata5.01: hard resetting link
Dec 26 08:58:50 nixos kernel: ata5.00: SATA link down (SStatus 0 SControl 300)
Dec 26 08:58:50 nixos kernel: ata5.01: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
Dec 26 08:58:50 nixos kernel: ata5.01: configured for UDMA/133
Dec 26 08:58:50 nixos kernel: ata5.01: device reported invalid CHS sector 0
Dec 26 08:58:50 nixos kernel: ata5: EH complete
```

**[Full output from journalctl](http://pastebin.com/hX4evJJA)**

The first 5 lines of the error gets written to the console about every 30 - 40 
seconds after tty1 has been started.

My computer have two drives:

* /dev/sda 320 GB (Windows, GRUB installed in MBR)
* /dev/sdb 1 TB (Debian Jessie)

Judging from the output from journalctl it seems that it's */dev/sda* that the 
issue revolves around. Using */dev/sdb* in the installer works as expected.

Both drives are physically working and I'm using both everyday without any 
issues.

I have used the USB-stick recently without any problems to install NixOS on 
another device.

# What I have tried so far

Here's some more information about the issue to try to narrow the problem 
down. **I'd be happy to give more information if requested.**

## Outside the installer 

To double-check that the disk is healthy and can be used outside the installer
I performed these tasks:

#### Boot Windows installation 

**Result:** Windows boots up successfully, disk can be read and written to

#### List block devices (running Debian install)

```
$ fdisk -v
fdisk (util-linux 2.20.1)

$ sudo fdisk -l
Disk /dev/sda: 320.1 GB, 320072933376 bytes
255 heads, 63 sectors/track, 38913 cylinders, total 625142448 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0xe7e825dd

   Device Boot      Start         End      Blocks   Id  System
   /dev/sda1   *        2048      206847      102400    7  HPFS/NTFS/exFAT
   /dev/sda2          206848   625139711   312466432    7  HPFS/NTFS/exFAT

Disk /dev/sdb: 1000.2 GB, 1000204886016 bytes
255 heads, 63 sectors/track, 121601 cylinders, total 1953525168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk identifier: 0x000aa682

  Device Boot      Start         End      Blocks   Id  System
  /dev/sdb1   *        2048   195311615    97654784   83  Linux
  /dev/sdb2       195313662  1953523711   879105025    5  Extended
  Partition 2 does not start on physical sector boundary.
  /dev/sdb5       195313664   390623231    97654784   83  Linux
  /dev/sdb6       390625280   394919935     2147328   82  Linux swap / Solaris
  /dev/sdb7       394921984  1953523711   779300864   83  Linux
```

**Result:** The command is successful and all drives show up

#### Mount drive with error (running Debian install)

```
$ sudo mount /dev/sda1 /mnt/win1
$ cd /mnt/win1
$ ls -la
total 1893
drwxrwxrwx 1 root root   4096 Jan 22  2011 .
drwxr-xr-x 5 root root   4096 Dec 26 09:41 ..
drwxrwxrwx 1 root root   4096 Jan 22  2011 Boot
-rwxrwxrwx 1 root root 383562 Jul 14  2009 bootmgr
-rwxrwxrwx 1 root root   8192 Jan 22  2011 BOOTSECT.BAK
-rwxrwxrwx 2 root root   8192 Jan 22  2011 bootsect.lxe.bak
-rwxrwxrwx 1 root root 383592 Jan 22  2011 gdrop
-rwxrwxrwx 1 root root 220049 Jan 22  2011 grldr
-rwxrwxrwx 1 root root    103 Jan 22  2011 menu.lst
drwxrwxrwx 1 root root      0 Jan 19  2011 System Volume Information
-rwxrwxrwx 1 root root 171136 Jan 22  2011 w7ldr
-rwxrwxrwx 1 root root     10 Jan 22  2011 win7.ld
-rwxrwxrwx 1 root root 571792 Jan 22  2011 wow7.img
-rwxrwxrwx 1 root root 171136 Jan 22  2011 xeldr
```

**Result:** Mount succesfull, can read and write to disk.

## In the NixOS installer

To compare the results of using the drive with the error in my Debian 
installation I tried the same commands in the NixOS installer.

#### List block devices

```
$ fdisk -l
```

**Result:** Nothing happens and the program becomes unresponsive. 

#### List mountpoints

```
$ mount
```

**Result:** Correctly shows all mountpoints!

#### Mount partition from disk with error

```
$ mount /dev/sda1 /mnt
```

**Result:** Nothing happens and the program becomes unresponsive. 

#### Mount home partition from disk without error

```
$ mount /dev/sdb5 /mnt
```

**Result:** Mount succesfull, can read and write to disk.

**Comment by Baughn** [comment]
It could be a regression in the kernel. I severely doubt this is a NixOS bug, in any case, but what are the respective kernel versions of your Debian and NixOS installs?

**Comment by rzetterberg** [comment]
@Baughn Sorry, I no longer have the installs, so I don't know the specific kernel versions.

But, If memory serves me correctly I was using Debian 8.0 and NixOS 14.04.

However, the same computer I had these issues on was reinstalled with NixOS 16.03 a month ago without any problems :) So by all means, this issue can be closed on my behalf.
