### ISSUE TITLE
package update: papis

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#54821]
## Issue description
I was really excited to discover another option than mendeley/zotero: papis but couldn't install it on nixos-unstable bcause of the following error...

### Steps to reproduce
```
note: keeping build directory '/tmp/nix-build-python3.7-dateparser-0.7.0.drv-0'
builder for '/nix/store/c30nlyv9wjwzizd7x37hvh4cmqn4k8ma-python3.7-dateparser-0.7.0.drv' failed with exit code 1; last 10 log lines:
  - M
  + Miércoles 31 Diciembre 2014
  
  
  ----------------------------------------------------------------------
  Ran 23161 tests in 436.774s
  
  FAILED (failures=3, skipped=7)
  Test failed: <unittest.runner.TextTestResult run=23161 errors=0 failures=3>
  error: Test failed: <unittest.runner.TextTestResult run=23161 errors=0 failures=3>
cannot build derivation '/nix/store/dpvjy2zrn6px51j9kg64vrpnpi32ljgq-python3.7-maya-0.3.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d1pmqfwddlw0627vgi2hli14168d6x5g-python3.7-Flask-Common-0.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r6w3vdf98wbwd4b67x1cqbbj62d0c1lq-python3.7-httpbin-0.6.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/c24lh992njn2534iv57ykkmknii7wayf-python3.7-pytest-httpbin-0.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p6lhmcprvvh6smy4hy3cnk7vr46lmlkw-python3.7-vcrpy-2.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/afk0dgp0khpd3qkxlgmv6f5sx78420x7-python3.7-habanero-0.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4c4cxz0vw15qbqi8hsksam6gpbrmly3a-papis-0.6.drv': 1 dependencies couldn't be built

```
@nico202 would it be possible to bump the package please ? seems like 0.6 is old (0.7.4 available)

**Comment by dtzWill** [comment]
https://github.com/dtzWill/nixpkgs/commits/nixos-dtz/pkgs/tools/misc/papis -- sorry for not sending upstream "yet", but might help even if a bit messy :).

Definitely was building previously, but am mid-rebuild so can't attest to it right this moment.

Hope it helps!

**Comment by teto** [comment]
@dtzWill you knew I was having difficulties with zotero/mendeley and didn't share with me this little gem ? I thought we had a connection ! Thanks for the link, definitely appreciated. I am really eager to test the software but I have some more pressing bugs to attend to. Hoping the maintainer can jump in.

**Comment by dotlambda** [comment]
@teto Unrelated to this issue, but you could also have a look at [pubs](https://github.com/pubs/pubs).

**Comment by dotlambda** [comment]
Regarding the dateparser test failures, there are https://github.com/scrapinghub/dateparser/issues/489, https://github.com/scrapinghub/dateparser/issues/490 and https://github.com/scrapinghub/dateparser/pull/493.
We can build papis using `python36` as long as these are not resolved.

**Comment by dotlambda** [comment]
Our issue tracking the dateparser test failures: https://github.com/NixOS/nixpkgs/issues/52766.

**Comment by teto** [comment]
@dotlambda thanks for your commitment on this issue, I noticed you've been very active.
@dtzWill so I tried to merge changes from your branch but it got a bit out of hand so I tried to install from your branch but either I have a problem with click or with dateparser tests. What do you say we split the upstreaming load with I upstream filetype and you upstream libisbn (or vice-versa) ?
