### ISSUE TITLE
sudo crontab -e doesn't work.

### ISSUE THREAD

**Issue by allowthere** [NixOS/nixpkgs#54827]
## Issue description

When I run `sudo crontab -e", I get 

    no crontab for root - using an empty one
    /bin/sh: /usr/bin/vi: No such file or directory
    crontab: "/usr/bin/vi" exited with status 127

Now I agree that I probably shouldn't do that (I should keep my crontab in `configuration.nix`), but a better error message would probably be better.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 
- system: `"x86_64-linux"`
- host os: `Linux 4.14.95, NixOS, 18.09.1985.749a3a0d00b (Jellyfish)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.1.3`
- channels(root): `"nixos-18.09.1985.749a3a0d00b"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by aanderse** [comment]
I also have this issue. Current work around is `sudo EDITOR=vi/nano/whatever crontab -e` but this needs to be fixed.

See https://github.com/NixOS/nixpkgs/issues/7730#issuecomment-384589262

**Comment by aanderse** [comment]
@allowthere Please feel free to close as this issue has been fixed.
