### ISSUE TITLE
Does it make sense for propagatedBuildInputs to get written out in fixupPhase?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#5483]
The nixpkgs documentation says it does typical fixuppy things, like stripping executables. I was very confused when my `propagatedBuildInputs` specification turned out to be a no-op when I disabled `fixupPhase` in my expression. I eventually figured it out, but it seems counterintuitive and like a questionable place for that behavior to happen. Is there somewhere better for it?

**Comment by shlevy** [comment]
IMO having a separate `nix-support` output, and not having it be part of a phase at all (instead just hard-coding it in the generic builder) is the right thing to do here.

**Comment by vcunat** [comment]
The way we do propagation in stdenv (so far), it's in fact a per-output property. I think in some cases it might be useful to have different stuff propagated in different outputs.

*In the multiple-output progress I was putting ``propagatedBuildInputs`` into the default -dev output (only).*

**Comment by shlevy** [comment]
Ah, fair enough. So I retract the thing about a different output, but I still don't think it should be part of a phase.

**Comment by Profpatsch** [comment]
(triage) Has a solution been reached?

**Comment by Profpatsch** [comment]
(triage) ping.
