### ISSUE TITLE
enableParallelBuilding should be enabled by default

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#5489]
I proposed to go from whitelisting to blacklisting. Possible advantages

* Speedups for local builds (and hydra builds if we had the capacity)
* Easier to find non-parallelizable builds (i.e. seeing [enableParallelBuilding = false] -> [parallel build breaks] vs. seeing [nothing] -> [parallel builds may or may not work])

[Feedback requested]

**Comment by peti** [comment]
I'm closing this issue because it's been thoroughly stalled by lack of consensus. If we'd like to go forward with any of this stuff, then it's probably best to submit a concrete PR.

**Comment by nh2** [comment]
For posterity, some build-managers build in parallel by default, for example:

* cmake (#32271)

**Comment by Ericson2314** [comment]
I wonder if this should be reconsidered. We're only getting more cores!

**Comment by Nyabinary** [comment]
I think it def should be reconsidered now tbh
