### ISSUE TITLE
minio regression OSX

### ISSUE THREAD

**Issue by peterromfeldhk** [NixOS/nixpkgs#54919]
## Issue description
minio-2018-12-27T18-33-08Z stoped working on osx
```
go/src/github.com/minio/minio/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51: cannot use refZero (type *_Ctype_struct___CFAllocator) as type _Ctype_CFAllocatorRef in argument to func literal
```

(previous working version is minio-2018-07-31T02-11-47Z - `nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/4927a248b57efbebac03c1a21f904e281d0b95ed.tar.gz -p minio`)
### Steps to reproduce

```
nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/0abf1810668ec8df0321156b0675519610513100.tar.gz -p minio
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(peter): `""`
 - channels(root): `"nixpkgs-19.03pre167327.11cf7d6e1ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by adisbladis** [comment]
I don't have the ability to build on OSX at the moment but I have a hunch. Could you try this expression and see if that fixes things for you:
`nix-shell -p 'minio.overrideAttrs(_: { propagatedBuildInputs = [ darwin.libobjc darwin.apple_sdk.frameworks.IOKit ]; })'`

I'm not even sure `libobjc` is required or not, this is just copied from another expression so please also try: ``nix-shell -p 'minio.overrideAttrs(_: { propagatedBuildInputs = [ darwin.apple_sdk.frameworks.IOKit ]; })'`` and see if that works for you.

**Comment by adisbladis** [comment]
Also try the latest minio from master, it may not have this same regression.

**Comment by peterromfeldhk** [comment]
yup you corrent @adisbladis newest version works fine
```
nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/b61797baf3d9bf41c3f0767e809fc97157b1624e.tar.gz -p minio
```
