### ISSUE TITLE
How to properly search for latest successful hydra build snapshot for a package?

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#54924]
## Issue description
`haskellPackages.brittany` on `master` is currently failed from missing `hspec` dependency.

```
$ nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/master.tar.gz" -p haskellPackages.brittany


Setup: Encountered missing dependencies:
hspec >=2 && <2.6

builder for '/nix/store/jj7y7l2fdjy17m82chnvrwq4izyzcqd6-multistate-0.8.0.1.drv' failed with exit code 1
cannot build derivation '/nix/store/sx3b52dsl4lanvxaplac91b7ygx9gqvh-brittany-0.11.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/sx3b52dsl4lanvxaplac91b7ygx9gqvh-brittany-0.11.0.0.drv' failed
```

I try to search for `haskellPackages.brittany` on https://hydra.nixos.org/ but there are too many [results](https://hydra.nixos.org/search?query=haskellPackages.brittany) and I don't know how to read it. 

I pick the top one from [18.09](https://hydra.nixos.org/job/nixos/release-18.09/nixpkgs.haskellPackages.brittany.x86_64-linux), is it the latest one?

```
$ nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/52571d750de0f90205db62afa50dbe723e42be33.tar.gz" -p haskellPackages.brittany

[nix-shell:~]$ 
```

### Questions
1. If I want to use the latest success build of a package, how should I do a search for it?
2. I can't find any documentation on this issue, is there any that I miss?
3. Is there any tool that do the search like this but for `shell.nix` instead of a single package (searching for latest snapshot which able to build the entire expression build dependencies )?

**Comment by danbst** [comment]
I hope this is what you search for:

https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.haskellPackages.brittany.x86_64-linux/latest

Just replace `haskellPackages.brittany` with any other attribute to get latest Hydra build.
