### ISSUE TITLE
octave cannot read image (imread)

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#54929]
## Issue description

When I call the `imread` function:

```matlab
imread('image.png')
```

I get the following error

```
error: imfinfo: support for Image IO was unavailable or disabled when Octave was built
error: called from
    __imread__ at line 80 column 10
    imageIO at line 118 column 26
    imread at line 106 column 30
```

`octave` and `octaveFull` both produce the same error.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

``` 
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 19.03pre164581.ae002fe44e9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(gui): `"nixpkgs-18.03pre118061.69607d7662"`
 - channels(root): `"nixos-19.03pre164581.ae002fe44e9"`
 - nixpkgs: `/home/gui/.nix-defexpr/channels/nixpkgs`
```

**Comment by MasseGuillaume** [comment]
Related: https://github.com/NixOS/nixpkgs/commit/ba274e578c8f42d0f02005e9e2dfef7dfbe08e93#diff-c61b215e708159c7d44048ac48c88bd1

**Comment by Quarub** [comment]
I am also experiencing this problem.
One of the first results searching for the error message was that that probably graphicsmagick is missing and that [this should be reported during the build.](https://savannah.gnu.org/bugs/?45569)
Indeed, searching for `GraphicsMagick` in `nix log nixpkgs.octave` yields
`configure: WARNING: GraphicsMagick++ library not found.  The imread, imwrite, and imfinfo functions for reading and writing image files will not be fully functional.`
Looking at the `default.nix` of octave shows that [`graphicsmagick` is in the `buildnputs`](https://github.com/NixOS/nixpkgs/blob/92a047a6c4d46a222e9c323ea85882d0a7a13af8/pkgs/development/interpreters/octave/default.nix#L29). 
Running `nix-shell '<nixpkgs>' -A octave` and inside the nix-shell `echo $buildInputs | grep magick` prints nothing. Where did `graphicsmagick` go?

**Comment by Quarub** [comment]
I managed to get a working version by simply saving the `default.nix` of octave and building it myself.
When doing
```
nix repl
nix-repl> :l <nixpkgs>
nix-repl> octave.drvAttrs.buildInputs
```
I get a `null` where the derivation for `graphicsmagick` should be. When looking at it via 
```
nix repl
nix-repl> (import ./pack.nix).myoctave.drvAttrs.buildInputs
```
where `pack.nix` is 
```
with import <nixpkgs> {};
{
  myoctave = pkgs.callPackage ./default.nix {};
}
```
and  `default.nix` is the one of octave, then the  `graphicsmagick` derivation is in the `buildInputs`.

What causes this behaviour?

**Comment by doronbehar** [comment]
Octave has been through some changes since the issue was created and graphicsmagick is in the `buildInputs` of the default build. So this works for me now:

```
octave --eval 'imread("me.jpg");'
```

I do get a warning though:

```
warning: your version of GraphicsMagick limits images to 8 bits per pixel
```

I'm not sure why is that, as we are using the latest GraphicsMagick but anyway that's a topic for a different issue which I hope to remember to test on the next update. I'm closing, reopen if you my observation is incorrect.

**Comment by pca006132** [comment]
> 
> 
> Octave has been through some changes since the issue was created and graphicsmagick is in the `buildInputs` of the default build. So this works for me now:
> 
> ```
> octave --eval 'imread("me.jpg");'
> ```
> 
> I do get a warning though:
> 
> ```
> warning: your version of GraphicsMagick limits images to 8 bits per pixel
> ```
> 
> I'm not sure why is that, as we are using the latest GraphicsMagick but anyway that's a topic for a different issue which I hope to remember to test on the next update. I'm closing, reopen if you my observation is incorrect.

This is due to the default `quantumdepth` being set to 8 in the graphics magick, modifying that could solve the issue. I just got this issue today when I was doing my computer vision homework for a course and spent 1 hour recompiling octave from source. I wonder if this is a common issue for others, and should I post a PR to set the `quantumdepth` to 16/32, but idk what is the commonly used number in other distributions. 

https://github.com/NixOS/nixpkgs/blob/04cea8b44a65a9cbb515b5d1996ccbe80088a84a/pkgs/applications/graphics/graphicsmagick/default.nix#L3

**Comment by doronbehar** [comment]
So @pca006132 did you test overriding `graphicsmagick` for `octave`?

**Comment by pca006132** [comment]
> So @pca006132 did you test overriding `graphicsmagick` for `octave`?

```nix
    (octaveFull.override {
      graphicsmagick = (graphicsmagick.override {
        quantumdepth = 32;
      });
    })
```
I did this in my package list and fixed the problem.

**Comment by doronbehar** [comment]
This `quantomdepth` flag was added in 2013: https://github.com/NixOS/nixpkgs/commit/8f583cced9baffd717309f685714db799dea687c. I don't think anyone will object to defaulting to 32 - makes sense to me to default to the greatest value. Let's open a PR and iterate the changed paths - build each with `@GrahamcOfBorg build`, there are not too many of them according to `git grep`.

**Comment by JunadMQ** [comment]
> > So @pca006132 did you test overriding `graphicsmagick` for `octave`?
> 
> ```nix
>     (octaveFull.override {
>       graphicsmagick = (graphicsmagick.override {
>         quantumdepth = 32;
>       });
>     })
> ```
> 
> I did this in my package list and fixed the problem.

I am having the same issue, I used conda to install the octave on MacOS, octave version is 6.2.0.May I know In which directory should I create the file to override graphicsmagick` for `octave`. if you could elaborate on the steps, that would be helpful. Thanks. Really appreciate your help.
