### ISSUE TITLE
Remove pythonPackages.django_2_0 before 19.03 release

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#54943]
According to https://www.djangoproject.com/download/#supported-versions, Django 2.0 will reach EOL in April 2019, i.e. just after the release of 19.03. Better not include it in the first place.

cc @georgewhewell @lsix

**Comment by lsix** [comment]
agreed. For 19.03 we will only support 1.11 and 2.1 (and probably port 2.2 when it gets available).
