### ISSUE TITLE
backport fixed port for nfs mountd to 14.04

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#5498]
Could this patch
  a735c308b69f4809eada30622279ae9fff03b016
be backported to nfsd.nix in release-14.04?

A similar patch for lockd was also backported:
https://github.com/NixOS/nixpkgs/commits/master/nixos/modules/services/network-filesystems/nfsd.nix
https://github.com/NixOS/nixpkgs/commits/release-14.04/nixos/modules/services/network-filesystems/nfsd.nix

**Comment by domenkozar** [comment]
14.04 is EOF
