### ISSUE TITLE
Plasma5 device notifier with FAT32 usb stick

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#54992]
## Issue description
When I input a USB stick with FAT32 (as determined by gparted) file system Plasma5 does not recognize it via the Device Notifier. 

With other file systems,  Device Notifier offers to mount the filesystem, etc. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.95, NixOS, 18.09.git.7f3df85 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Works for me on NixOS 21.11
