### ISSUE TITLE
mpv + youtube-dl: Failed to initialize a decoder for codec 'av1'

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#54990]
## Issue description
YouTube has recently begun serving some videos as AV1. Today I came across one that looks like it can't be decoded by ffmpeg.
Using just youtube-dl to download the same video, I'm seemingly served a VP9 version. Strange.

### Steps to reproduce
```
$ nix run -f https://github.com/NixOS/nixpkgs/archive/e6293287f6f44af22b478ee852461345174a0a01.tar.gz mpv -c mpv "https://www.youtube.com/watch?v=MRqWaRMFsPs"
Driver 'opengl' has been replaced with 'gpu'!
Driver 'opengl' has been replaced with 'gpu'!
Playing: https://www.youtube.com/watch?v=MRqWaRMFsPs
 (+) Video --vid=1 (*) (av1 1280x720 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
Failed to initialize a decoder for codec 'av1'.
Video: no video


Exiting... (Errors when loading file)
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.5, NixOS, 19.03pre167858.f2a1a4e93be (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre167858.f2a1a4e93be"`
 - channels(rschuetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matu3ba** [comment]
You seem to have an old version of ffmpeg not supporting av1.
Check by `ffmpeg -codec`.

Modifying your youtube-dl accordingly still works, here a quick and dirty fix for both programs in .config:
youtube-dl/conf:
`-f 'bestvideo[height<=720]+bestaudio/best[height<=720]'`
mpv/mpv.conf
`ytdl-format=bestvideo[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best`

As youtube will most likely recode all its higher quality videos (above HD quality) into vp9 and av1 (which you can see by youtube-dl -F in the note field,
you should change to a newer ffmpeg version in the longterm.
Note, that vp9 uses webm as extension, so it is not identified easily by mpv/youtube-dl anymore.

Please close this issue, if this resolves your question.

**Comment by matu3ba** [comment]
Interestingly enough I did not find support for av1 codec in mpv.
`mpv -ovc help -ovcopts help -oac help -oacopts help -of help -ofopts help | less `

I would suggest you to use vp9. They finally backported supported for old hardware and it works very good now.
`ytdl-format=bestvideo[height<=?720][fps<=?30][vcodec^=vp9]+bestaudio/best`

**Comment by ln-nl** [comment]
Just in case. Currently, only ffmpeg-full is compiled with libaom (av1) support enabled.

**Comment by Ekleog** [comment]
The command on the top post appears to work properly with current `channel:nixos-unstable`, or at least it starts reading the video properly (which I assume would already fail if it's for a codec error).

Closing as the issue appears to have already been solved in master. :)

**Comment by dotlambda** [comment]
It has not been fixed:
```
$ nix run -f https://github.com/NixOS/nixpkgs/archive/0fc80a5.tar.gz mpv -c mpv "https://www.youtube.com/watch?v=MRqWaRMFsPs"
[15.9 MiB DL]
Driver 'opengl' has been replaced with 'gpu'!
Driver 'opengl' has been replaced with 'gpu'!
Playing: https://www.youtube.com/watch?v=MRqWaRMFsPs
 (+) Video --vid=1 (*) (av1 1280x720 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
Failed to initialize a decoder for codec 'av1'.
Video: no video


Exiting... (Errors when loading file)
```
I'm regularly seeing this with many different YouTube vids.

**Comment by dotlambda** [comment]
cc @adisbladis @Infinisil

**Comment by ln-nl** [comment]
For better repro you can use this command:
```
nix run -f https://github.com/NixOS/nixpkgs/archive/0fc80a5.tar.gz mpv -c mpv --ytdl-raw-options=format=397 "https://www.youtube.com/watch?v=MRqWaRMFsPs"
```

For me, `mpv` compiled with `ffmpeg-full` outputs this: 
```
Error while decoding frame!
[ffmpeg/video] libaom-av1: Failed to decode frame: Bitstream not supported by this decoder
[ffmpeg/video] libaom-av1:   Additional information: Buffer -1 does not contain a decoded frame
```

**Comment by primeos** [comment]
#66527 should fix this (if we decide to merge it, it's just a proposal for now), reviews and tests would be welcome :)

**Comment by d3rped** [comment]
As ghost already (kind of) mentioned `libaom` is currently broken.
Bumping `ffmpeg-full` to 4.2 and adding `libdav1d/dav1d` as an additional dependency at least solves the decoding problem (haven't tried to encode anything with `libaom` yet).

I guess it would be sensible to update that package as well in #66527 .

Depending on how broken `libaom` actually is it would be also sensible to comment the relevant section in `ffmpeg-full` as at least mpv tries to use `libaom` first (-> mpv has to be run with `--vd=libdav1d`)

**Comment by primeos** [comment]
> I guess it would be sensible to update that package as well in #66527 .
>
> Depending on how broken libaom actually is it would be also sensible to comment the relevant section in ffmpeg-full as at least mpv tries to use libaom first (-> mpv has to be run with --vd=libdav1d)

Totally forgot about this comment :o
I've just created a PR for `ffmpeg-full` as well since no one else did it yet: https://github.com/NixOS/nixpkgs/pull/67205
I've included a patch to prefer libdav1d over libaom for decoding as I also had problems with libaom.
