### ISSUE TITLE
Why does `gcc` from `gcc-wrapper-7.4.0` not accept `-no-pie`? (darwin)

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#55006]
## Issue description

`gcc` and `g++` do not recognize options such as `-no-pie` or `-stdlib=libc++`, while both GNU GCC and clang ought to recognize them. I don't think I understand how the nix setup makes it so that those options are not recognized... It prevents me from building certain personal packages that expect `g++` to accept those flags.

### Steps to reproduce

```
nix-shell -p gcc
$ gcc -no-pie
gcc: error: unrecognized command line option '-no-pie'
$ gcc -stdlib=libc++
gcc: error: unrecognized command line option '-stdlib=libc++'
```

## Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(val): `"nixpkgs-19.03pre167327.11cf7d6e1ff"`
 - nixpkgs: `/Users/val/.nix-defexpr/channels/nixpkgs`
```

**Comment by matthewbauer** [comment]
stdlib is clang only. I'm not sure about -no-pie though.

**Comment by Ptival** [comment]
Oh yeah, forget about `stdlib`, but `-no-pie` should work yeah... :-(

**Comment by matthewbauer** [comment]
Does this work on regular gcc? The macOS linker calls it ```-no_pie```. I think you need to pass it as a linker flag like this:

```
gcc -fno-PIE -Wl,-no_pie
```

**Comment by abathur** [comment]
Closing since it sounds like Matthew answered the question and this has been stale for a while, but I'm happy to reopen if this answer doesn't work.
