### ISSUE TITLE
Build of NixPkgs manual is broken

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#55014]
## Issue description

[Curently](https://github.com/NixOS/nixpkgs/tree/f89f2478b89c3293d342b17efca3c6c559f52b68) with new versions of deps - build is broken.

Example of error instance:
```
Line 6592:
  6589	 <!-- These docs are generated via nixdoc. To add another generated
  6590	      library function file to this list, the file
  6591	      `lib-function-docs.nix` must also be updated. -->
  6592	 <xi:include href="./library/generated/strings.xml"/>
  6593	 <xi:include href="./library/generated/trivial.xml"/>
  6594	 <xi:include href="./library/generated/lists.xml"/>
  6595	 <xi:include href="./library/generated/debug.xml"/>
     error: element "xi:include" not 
    allowed here; expected the element 
    end-tag or element "bibliography", 
    "glossary", "index", "section", 
    "simplesect" or "toc"
```

Full log:
[NixPkgsManualMakeDebug.log](https://github.com/NixOS/nixpkgs/files/2818916/NixPkgsManualMakeDebug.log)

This creates a blocker for contributors to the manual.
To contribute to NixPkgs manual, it is required to build the manual ([link](https://nixos.org/nixpkgs/manual/#chap-contributing)) before creating a pull request.
I want to contribute some section. By the process - I need to pass a successful build. The manual on the master branch is currently broken, building it on my setup. Errors ask me to make changes, which doc maintainers probably know what to do about.

### Steps to reproduce

```
git pull
# currently f89f2478b89c3293d342b17efca3c6c559f52b68
cd doc
nix-shell
[nix-shell]$ make
# observe log and Error 1 result 
[nix-shell]$ make debug
# observe full log
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre166987.bc41317e243, unstable-19.03pre166987.bc41317e243"`
 - channels(pyro): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Anton-Latukha** [comment]
Maybe this is due to manual being build on the current stable branch?

**Comment by vcunat** [comment]
Even on f89f2478 the job builds and most likely will build for you as well
```
$ git checkout f89f2478
$ nix build -f nixos/release-combined.nix nixpkgs.manual
```
but I confirm that `make` in `nix-shell` indeed is broken.

**Comment by vcunat** [comment]
BTW, I believe this earlier message is closer to the root of the problem:
```
warning: failed to load external entity "functions/library/generated/strings.xml"
functions/library.xml:19: element include: XInclude error : could not load functions/library/generated/strings.xml, and no fallback was found
```

**Comment by jtojnar** [comment]
Yes, this was added to 

https://github.com/NixOS/nixpkgs/blob/c0d3182f79101ab28ac67d7f39ef62f7b101786c/doc/default.nix#L32-L37

in https://github.com/NixOS/nixpkgs/pull/53055 but the `Makefile` was forgotten.

**Comment by samueldr** [comment]
@Anton-Latukha if you are still having issues on master (or a revision where #55040 is merged) make sure you `make clean` before using `make`, and otherwise, re-open with more details.
