### ISSUE TITLE
"git-gui" is not inside gitAndTools.gitFull package

### ISSUE THREAD

**Issue by jackTaw88** [NixOS/nixpkgs#55071]
Hi,

I installed gitandtools.gitfull package:

https://nixos.org/nixos/packages.html#gitandtools.gitfull

It does not include "git-gui" which is coming with all other download packages from: https://git-scm.com/download/linux

source:
https://git.wiki.kernel.org/index.php/InterfacesFrontendsAndTools#git-gui_.28distributed_with_Git.29

> Stable versions are shipped with Core Git since version 1.5. 

1- Why it is not included?
2- Is there any another nix package where I can find it?

Thanks in advance

**Comment by jackTaw88** [comment]
@hedning 

when I type:

> git gui

It prints:

```
git: 'gui' is not a git command. See 'git --help'.

The most similar commands are
	gc
	grep
	init
	pull
	push
```

I have the same package as yours:

>  nix-env -iA nixos.gitAndTools.gitFull (NixOS channel) 
version is: 2.19.2

Are you sure you did not type any other command?

"git --help" does not show any parameter to open any GUI.

**Comment by hedning** [comment]
Hmm, that's strange. `git gui` does work here. Do you have `gitk` (which I think is the binary `git gui` actually calls)? Is there a possibility that you've accidentally turned off `guiSupport` in your config? https://github.com/NixOS/nixpkgs/blob/2d381653e280c9b4907620b7dfa5e036edd143b7/pkgs/applications/version-management/git-and-tools/default.nix#L44

Here's a list of the `gitFull`'s bin on my system:
```
❯ ls $(nix path-info nixpkgs.gitFull)/bin
git                       git-credential-netrc  git-http-backend  git-receive-pack  git-upload-archive
git-credential-libsecret  git-cvsserver         gitk              git-shell         git-upload-pack

**Comment by jackTaw88** [comment]
@hedning 

- I have gitk and it works.

- gitk and git-gui are different: https://git-scm.com/docs/git-gui#_description

- I have also your "git-*" binaries on my path (git, gitk, git-shell ...)

- I don't know how to change the config "guiSupport = true;". I just install on my ubuntu 18.04 by this command:

> nix-env -iA nixpkgs.gitAndTools.gitFull

**Comment by hedning** [comment]
Hmm, that's pretty strange, I'm guessing `ls $(nix path-info nixpkgs.gitFull)/libexec/git-core/git-gui` is also successful. Not sure what's up then (I'm on NixOS so the difference could be due to that, but seems weird).

**Comment by jackTaw88** [comment]
@hedning the file /libexec/git-core/git-gui exist. How I did not found this before. Thank you. I will create a symbolic link to desktop. But I think there is a bug here. Because I installed gitfull on my 2 machines. The same problem exist.

Thank you

**Comment by hedning** [comment]
> But I think there is a bug here.

Yeah, I'd double check that `type git` actually points to `~/.nix-profile/bin/git` (should've thought of that before), but if it does then this sure looks like a bug.

**Comment by jackTaw88** [comment]
> > But I think there is a bug here.
> 
> Yeah, I'd double check that `type git` actually points to `~/.nix-profile/bin/git` (should've thought of that before), but if it does then this sure looks like a bug.

Omg :/ my "git" points to /usr/bin/git. I did not installed git. /var/log/apt/history.log not have any git command. I think I have local problems. Sorry about that. :( Thank you for your help.
