### ISSUE TITLE
tor-browser-bundle-bin: does not start as root

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#55082]
## Issue description

```tor-browser-bundle-bin``` does not start as root
It fails with
```
/run/current-system/sw/bin/tor-browser: line 59: DBUS_SESSION_BUS_ADDRESS: unbound variable
```

![](http://i.imgur.com/RCLMfaE.png)

```tor-browser``` works well as regular user
 ```firefox``` works well as root and as regular user.

Issue is the same with XFCE and IceWM

**Comment by volth** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/20157

When started as ```DBUS_SESSION_BUS_ADDRESS="" tor-browser``` it claims about ```$DISPLAY```, so ```XAUTHORITY="$HOME/.Xauthority"``` does help (as suggested in https://github.com/NixOS/nixpkgs/issues/20157#issuecomment-272767442)

So running it as
```DBUS_SESSION_BUS_ADDRESS="" XAUTHORITY="$HOME/.Xauthority" tor-browser```
does work

Perhaps we should adjust ```tor-browser``` wrapper to add some defaults for ```DBUS_SESSION_BUS_ADDRESS``` and ```XAUTHORITY```

**Comment by joachifm** [comment]
The wrapper now sets defaults.
