### ISSUE TITLE
libreoffice icons are missing

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#5509]
No icon is seen in desktop menu (or, it shows just a generic icon for an executable). Further, there doesn't seem to be any icon files in libreoffice store path. I searched for "*.png" and "*.svg" but found nothing relevant. So it's not just that the .desktop file has bad ```Icon=``` setting.

**Comment by iElectric** [comment]
Should be fixed in master.

**Comment by bjornfor** [comment]
I only see icon for "Calc". The other apps have the dummy/executable icon still. Weird.

**Comment by Henry-Hiles** [comment]
> I only see icon for "Calc". The other apps have the dummy/executable icon still. Weird.

Same here. I'm on nixpkgs unstable, idk if that has an effect.

**Comment by Henry-Hiles** [comment]
Nevermind, I'm sorry, logging out and back in after rebuilding fixed it. :+1:
