### ISSUE TITLE
Recent kerberos changes do not work on Darwin

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#5512]
In afeef240dce28f1de4c6d5a29ce5c23e562c53a4, the way that kerberos is referenced changed, and also several packages were changed to now build with kerberos support.  These changes break several deviations on Darwin, because neither heimdal nor krb5 builds there (at least, this is true on Yosemite).

**Comment by jwiegley** [comment]
There is at least one package that depends on `kerberos` being a string, and not `null`.

**Comment by jwiegley** [comment]
Or rather, it does: `GSSAPI="${kerberos}"`, which fails if it is just `null`.

**Comment by wkennington** [comment]
I'll see if I can work on making it so that we can null out the kerberos dependency then.

**Comment by wkennington** [comment]
Hopefully cd833ea6ddae0a0d57077b56d0ddeef30587a9ef fixes it for now.

**Comment by jwiegley** [comment]
No, I still get:

```
while evaluating the attribute ‘buildPhase’ of the derivation ‘serf-1.3.7’ at "/Users/johnw/src/nixpkgs/pkgs/development/libraries/serf/default.nix":4:3:
cannot coerce null to a string, at "/Users/johnw/src/nixpkgs/pkgs/development/libraries/serf/default.nix":19:16
```

**Comment by jwiegley** [comment]
@wkennington How does this change look?

``` patch
diff --git a/pkgs/development/libraries/serf/default.nix b/pkgs/development/libraries/serf/default.nix
index fb01f17..df87496 100644
--- a/pkgs/development/libraries/serf/default.nix
+++ b/pkgs/development/libraries/serf/default.nix
@@ -18,9 +18,11 @@ stdenv.mkDerivation rec {
 
   buildPhase = ''
     scons PREFIX="$out" OPENSSL="${openssl}" ZLIB="${zlib}" APR="$(echo "${apr}"/bin/*-config)" \
-        APU="$(echo "${aprutil}"/bin/*-config)" GSSAPI="${kerberos}" CC="${
+        APU="$(echo "${aprutil}"/bin/*-config)" CC="${
           if stdenv.isDarwin then "clang" else "${stdenv.cc}/bin/gcc"
-        }"
+        }" ${
+          if stdenv.isDarwin then "" else "GSSAPI=\"${kerberos}\""
+        }
   '';
 
   NIX_CFLAGS_COMPILE = stdenv.lib.optionalString stdenv.isDarwin "-L/usr/lib";
```

**Comment by wkennington** [comment]
Yeah that looks fine, I thought I changed serf to incorporate that
change.....

**Comment by gridaphobe** [comment]
@jwiegley is this still a problem for you on master?

**Comment by domenkozar** [comment]
still an issue?

**Comment by joachifm** [comment]
darwin builds for serf appear to be working on current master
