### ISSUE TITLE
[grub] "set gfxmode=640x480" should become "set gfxmode=auto"

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#5514]
- test that background image scales
- consider using text mode for minimal installer

**Comment by iElectric** [comment]
Currently live iso cd doesn't have the grub background image. I think removing unionfs broke that. cc @edolstra

**Comment by vcunat** [comment]
Done in 159fed47b. Probably tested, too.

**Comment by domenkozar** [comment]
\o/

**Comment by obadz** [comment]
Is there some other option I can use to go back to the vga mode? I have a HiDPI screen and rendering the grub prompt screen takes several 4-5 seconds (even with the splashImage set to null)

**Comment by vcunat** [comment]
I did notice a split-second slowing even on my 1366x768. But what to have as the default? We could have something like ``GRUB_GFXMODE=1024x768,800x600,640x480``, but IMHO the point is that ``auto`` *should* actually select a sane option itself...

**Comment by obadz** [comment]
That sounds reasonable, but can we expose that as an option so that those with hidpi can do grub.gfxmode = "640x480" or something of that sort?

**Comment by wkennington** [comment]
It is an option

**Comment by obadz** [comment]
Which one is it?
```
$ nixos-option boot.loader.grub
This attribute set contains: bootDevice configurationLimit configurationName copyKernels default device devices efiSupport enable enableCryptodisk extraConfig extraEntries extraEntriesBeforeNixOS extraFiles extraPerEntryConfig extraPrepareConfig fsIdentifier ipxe memtest86 mirroredBoots splashImage timeout version zfsSupport
```

**Comment by obadz** [comment]
Nevermind, looks like it came in a later commit c891134b77c05b98d1fc89f2bac394dbe4382fe8
