### ISSUE TITLE
Firejail drops OpenGL support

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#55191]
## Issue description
When Firefox is run from within Firejail, even with the --noprofile flag, it drops WebGL support.

### Steps to reproduce
1. Run `firejail --noprofile {path-to-your-firefox-nixstore-folder}/bin/firefox`
2. Go to any WebGL-using site. I use https://threejs.org/examples/#webgl_interactive_voxelpainter
3. Receive an error message

According to the issue I opened in the firejail repo (netblue30/firejail#2351), this problem is not affecting others, so I am going to assume it is due to the way NixOS handles some things.

### Extra information
When running Firefox from a console, it spews the following:
```
* Refused to create native OpenGL context because of blacklist entry: 
* Exhausted GL driver options.
JavaScript warning: https://threejs.org/build/three.js, line 22284: Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting.
JavaScript warning: https://threejs.org/build/three.js, line 22284: Error: WebGL warning: <SetDimensions>: Refused to create native OpenGL context because of blacklist entry: 
JavaScript warning: https://threejs.org/build/three.js, line 22284: Error: WebGL warning: <SetDimensions>: Failed to create WebGL context: WebGL creation failed: 
```

I have double checked my Firefox settings and all seems clear. WebGL is enabled, the gfx.blacklist option that's often mentioned does not even exist anymore (or at least on my build), tried force-enabling WebGL with webgl.force-enable, but it just refuses to run. It just works whenever I run Firefox without Firejail, so I know it can run just well. 

@SkewedZeppelin mentioned --noprofile applies minimal restrictions, such as process namespacing. Could it be related to this?

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.15, NixOS, 19.03pre167858.f2a1a4e93be (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre167858.f2a1a4e93be"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 - firejail version 0.9.56
 - Firefox version aniwhere from 64 to 65 (tested)
 - Mesa 18.3.1, amdgpu. Probably not specific to this since I have tested on a nouveau machine and the result is the same.

**Comment by shirona** [comment]
@matthewbauer I have checked from both the file browser and a terminal I used to join the Firefox jail, and it seems to be accessible from there. In fact, the whole /run/ directory seems fully accessible, with full execution privileges on the binaries.

Searching around, I found netblue30/firejail#1098, which I thought may be related to this, but then I found out NixOS already configures that option by default, so I am not sure what could be happening.

I have tried out to `firejail --noprofile glxgears`, and to my surprise, it doesn't work. It throws a `Error: couldn't get an RGB, Double-buffered visual` message before exiting. `firejail --noprofile glxinfo` shows a similar error: 
`name of display: :0
Error: couldn't find RGB GLX visual or fbconfig`

Weird thing is I can use Steam just fine. I guess it has to do with the weird chroot things it does.

**Comment by shirona** [comment]
Small update: just tried to firejail Retroarch. It SIGSEGV as soon as it generated  the window. Tried changing Retroarch to use the Vulkan driver, and then it started to work under firejail. So, OpenGL and firejail don't mix well, but Vulkan and firejail do, somehow.

**Comment by stigtsp** [comment]
Passing in LD_LIBRARY_PATH seems to work around the problem as indicated here https://github.com/netblue30/firejail/issues/2351

glxgears:
```sh
$ firejail --env=LD_LIBRARY_PATH="$LD_LIBRARY_PATH" glxgears
```
And firefox in wrappedBinaries:

```nix
{
  programs.firejail.wrappedBinaries.firefox = "--env=LD_LIBRARY_PATH=\\$LD_LIBRARY_PATH ${lib.getBin pkgs.firefox}/bin/firefox";
}
```

**Comment by probonopd** [comment]
Getting `Error: invalid --env setting`. Which version of Firejail is needed for this to work?

**Comment by onny** [comment]
Hm unfortunately specifying `LD_LIBRARY_PATH` doesn't seem to work for me
```
  programs.firejail = {
    enable = true;
    wrappedBinaries = {
      librewolf = {
        executable = "${lib.getBin pkgs.librewolf}/bin/librewolf";
        profile = "${pkgs.firejail}/etc/firejail/librewolf.profile";
        extraArgs = [
          # Required for U2F USB stick
          "--ignore=private-dev"
          # Enforce dark mode
          "--env=GTK_THEME=Adwaita:dark"
          # Required to get WebGL to work
          "--env=LD_LIBRARY_PATH=/nix/store/mwk5yih4kyyjpxpqa06n0f7fih3r3gwv-opengl-drivers/lib"
        ];
      };
    };
  };
``` 
OpenGL is still broken inside Firejail :(

**Comment by onny** [comment]
Hopefully this is fixed with whitelisting `/run/opengl-drivers`. For me it worked :)

Fixed upstream https://github.com/netblue30/firejail/pull/5132
and downstream https://github.com/NixOS/nixpkgs/pull/171933
