### ISSUE TITLE
Files with names matching "nix-shell*" with shebangs exhibit unexpected behaviour

### ISSUE THREAD

**Issue by antislava** [NixOS/nixpkgs#55239]
For example, none of the examples of nix-shell shebangs usage from the `nixpkgs` manual work as expected if put in a file matching `nix-shell*` (usually with `error: undefined variable ...`)

The problems disappear after the name is changed to any other. 

$ nixos-version
19.03pre167858.f2a1a4e93be (Koi)
$ nix --version
nix (Nix) 2.2

**Comment by Artturin** [comment]
can't repro
