### ISSUE TITLE
provide nss modules globally instead of hacking them with nscd

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#55276]
We currently proxy all nss requests through nscd so we can add nss modules (see https://github.com/NixOS/nixpkgs/pull/50316/commits/1d5f4cbb784904e0a6420cc62b0b24ca0873abc5)

This is bad, as glibc quickly falls back to resolving locally if resolution through nscd takes too long, and in that case without custom nss modules loaded.

Not relying solely on nscd, but rather assembling together an nss modules path, and writing that nix store path into `/etc/ld.so.conf` seems to be a better solution and should work.

Using the actual path instead of a symlink should also avoid most problems with binaries and ABI breakages of glibc as described in https://github.com/NixOS/nixpkgs/pull/50316#issuecomment-460343238 that might occur when switching to a more recent glibc - at least it should be better than the half-broken state with nscd timing out that we currently might have.

cc @arianvp @Mic92

**Comment by Mic92** [comment]
I don't think this is a good solution to the problem as it can likely make mixing applications linked against different glibc versions impossible. This is in my opinion worse then breaking mdns resolver.

**Comment by edolstra** [comment]
:-1: since this adds yet another bit of ad hoc global state, and breaks the case of running 32-bit binaries on 64-bit systems.

**Comment by edolstra** [comment]
I mean, `nscd` *is* how we provide NSS modules globally, in a standard, ABI-neutral way.

**Comment by flokli** [comment]
I was only thinking about adding a path to additional nss modules (and only those not provided via glibc itself).

About being able to run 32bit binaries, I need to read on on how that works on other distros - they should have a global `/etc/ld.so.conf`.

This is not only to fix mdns resolving, but also about other resources provided via additional nss modules, like ldap user lookup through nss.

I'd be fine with proxying things through nscd, but glibc falling back to local resolving which does things differently is really inconsistent too.

If I find the time, I might dig into glibc and whether there is some keepalive mechanism.

**Comment by flokli** [comment]
After some thinking, I guess using nscd is fine for resolving - couldn't find extremely short fallback timeouts either.

**Comment by flokli** [comment]
In the meantime, I could spot the "resolve-via-nscd" timeouts - see https://gitlab.com/freedesktop-sdk/mirrors/sourceware/glibc/-/blob/master/nscd/nscd_helper.c#L216. (5secs)

If these timeout, glibc gives up waiting for nscd and tries to resolve locally (without having nss modules available, so it'll likely fail as well).

5 seconds is at least more time than Microsoft is willing to wait for slow lookups like LLMNR (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn305896(v=ws.11) - so it should be enough for us as well.

What do others think?

**Comment by arianvp** [comment]
The assessment that putting nss modules in a global path leads to issues seems to be debunked.

`dlsym/dlopen`'ing nss modules from different versions of Glibc should just work; and is ABI-stable according to the glibc developers:

https://sourceware.org/legacy-ml/libc-help/2016-12/msg00006.html

**Comment by arianvp** [comment]
Aha; but further in the thread it reads:

https://sourceware.org/legacy-ml/libc-help/2016-12/msg00008.html


> in general it is not possible to update glibc safely because it
> consists of multiple shared libs without stable abi between them
> and the update cannot be done atomically, with runtime loaded
> components even atomic file system update does not help: existing
> process with old libc may load a new libc component after the
> update (even if the loaded module has stable abi, it may depend
> on a not yet loaded libc component that does not).

> the safe way to implement extensible libc behaviour is to have it
> in a separate component (daemon) with stable interface (name lookup
> protocol) that survives independent updates of the two sides
> (you only need to make sure that the daemon is not loading libc
> components during libc update and that it can reexec itself without
> dropping connections for daemon update).

Which is exactly what we're doing.

I'm just leaving these comments here for historical context in case somebody stumbles over this issue too

i don't know how hard this is to do with nscd, but currently the
only hope to have a system with safe live update and nss is via
glibc nscd on a musl libc based system (musl is safe to update).

which is a long way to say that i think nss modules should support
nscd and sssd should be fixed to work with it.

**Comment by arianvp** [comment]
However; the issue that is being described the the problem of updating _glibc_ in place;  (which we never do; as each glibc version lives in a different nix store path) whilst the issue we're trying to solve here is updating _nss modules_ in place .  This still sounds safe to do to me.

**Comment by flokli** [comment]
So what you're saying is if we'd patch glibc to also discover other nss modules from a "mutable" `/run/glibc-nss-modules/` (or similar), like we have for opengl drivers, even if built with another glibc version, the `dlsym` abstraction should be stable enough?

I'm no fan of just adding it into `LD_LIBRARY_PATH` globally, as this won't necessarily update for all new processes.

**Comment by flokli** [comment]
Let's give this some more thought and experimentation.

Maybe the ABI is stable enough, at to support this as a separate option when nscd is disabled.

There's valid usecases where people do not want to use nscd, for example when having a separate network namespace with a default gateway via a VPN tunnel. In the current setup, host lookups are done through nscd in the main network namespace, possibly leaking DNS lookups.

**Comment by flokli** [comment]
As can be seen in https://github.com/NixOS/nixpkgs/issues/135888, nscd seems to do some caching (at least recently), and doesn't just proxy requests through, so it might make sense to get rid of nscd, and try a path as outlined in https://github.com/NixOS/nixpkgs/issues/55276#issuecomment-735465873.

I did a quick hack on this some months ago, but got stuck somewhere. I'll try to resurrect and push it somewhere.

**Comment by flokli** [comment]
As can be seen in https://github.com/NixOS/nixpkgs/issues/135888, nscd seems to do some caching (at least recently), and doesn't just proxy requests through, so it might make sense to get rid of nscd, and try a path as outlined in https://github.com/NixOS/nixpkgs/issues/55276#issuecomment-735465873.

I did a quick hack on this some months ago, but got stuck somewhere. I'll try to resurrect and push it somewhere.

**Comment by Mic92** [comment]
> So what you're saying is if we'd patch glibc to also discover other nss modules from a "mutable" `/run/glibc-nss-modules/` (or similar), like we have for opengl drivers, even if built with another glibc version, the `dlsym` abstraction should be stable enough?
> 
> I'm no fan of just adding it into `LD_LIBRARY_PATH` globally, as this won't necessarily update for all new processes.

A profile in the `/nix/var/nix/profiles/system` could be nicer as it might better with unprivileged nix on non-nixos systems.
Maybe we should even do the same with opengl.

**Comment by flokli** [comment]
> A profile in the /nix/var/nix/profiles/system could be nicer as it might better to integrate with unprivileged nix on non-nixos systems. Maybe we should even do the same with opengl.

I don't think this applies to non-NixOS a lot - I'd assume we want to stick with the distros NSS modules and `nsswitch.conf` there, like we do with fontconfig, too.

I would find it very confusing if `nix-env -iA systemd` on non-NixOS would suddenly cause nix-built applications to use another NSS module.

**Comment by Mic92** [comment]
I don't think nss modules from a different distro would work at all same reason, unless one uses LD_LIBRARY_PATH, which causes different issues. On the other hand having a path in the nix store would allow to building something similar like https://github.com/guibou/nixGL without root permissions. This would be always explicit however if there is nothing that creates `/nix/var/nix/profiles/system` than it would not be used. The same logic also applies to `/run/glibc-nss-modules/` btw except that one needs to own an additional directory.

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/pull/138178 now uses `/run/nss-modules`, and lookup for that path is patched into glibc, in addition to LD_LIBRARY_PATH.

I don't think we should use `nix` to manage NSS modules on non-NixOS systems, but load the ones provided by the distro, as it's distro configuration.

This doesn't really change any behaviour on non-NixOS compared to before right now.

We could add `/usr/lib` into that patch as well (only for NSS module loading, to make nix-built binaries and NSS behave better on non-NixOS without nscd running), but that should be a followup.

**Comment by abbradar** [comment]
While working on https://github.com/NixOS/nixpkgs/pull/154320 I found out that Fedora deprecated nscd because of [slow maintenance and existing serious issues](https://fedoraproject.org/wiki/Changes/DeprecateNSCD#Benefit_to_Fedora). These issues sound serious enough for us to also consider it a problem.

**Comment by Mic92** [comment]
There is also https://busybox.net/~vda/unscd/ which seems to be still maintained.

**Comment by veprbl** [comment]
> We could add `/usr/lib` into that patch as well (only for NSS module loading, to make nix-built binaries and NSS behave better on non-NixOS without nscd running), but that should be a followup.

Would be nice to have something like that working, however, how can that work if the NSS modules in `/usr/lib` are built with a different glibc?

**Comment by flokli** [comment]
Yet another issue caused by this: https://github.com/NixOS/nixpkgs/issues/55276

**Comment by flokli** [comment]
I think for now we need to have a stable interface. https://github.com/NixOS/nixpkgs/pull/196917 is probably the better alternative to glibc-nscd.
