### ISSUE TITLE
stat: unrecognized option '--printf'

### ISSUE THREAD

**Issue by Vskilet** [NixOS/nixpkgs#55272]
## Issue description
Hi !
When I do a `nix-rebuild` I have a strange output about 
```
stat: unrecognized option '--printf'
[...]
WARNING: bad ownership on /nix/var/nix/gcroots/per-user/vskilet, should be 1111
```

### Steps to reproduce
`nixos-rebuild switch -I nixpkgs=/home/vskilet/nixpkgs/`

## Technical details

- system: `"x86_64-linux"`
- host os: `Linux 4.14.96, NixOS, 18.09.git.1a69533 (Jellyfish)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.1.3`
- channels(victor): `""`
- channels(root): `"nixos-18.09.2030.06808d4a140, nixos-unstable-19.03pre155751.45a419ab5a2"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matthewbauer** [comment]
This usually happens because the stat from busybox does not accept all of the options of the one from coreutils. Not sure why busybox is getting into the path here though.

**Comment by Vskilet** [comment]
Mmmmh, It seems that I installed busybox in a configuration file ...
