### ISSUE TITLE
Steam Runtime requires refreshing

### ISSUE THREAD

**Issue by shirona** [NixOS/nixpkgs#55274]
## Issue description
The Steam Runtime has been updated by Valve recently. Last NixOS update caused a rebuild of the `steam-runtime` package, and as such, most downloads from http://repo.steampowered.com/steamrt/ return 404. The https://appradar.net mirror is still working, but it's outdated, and takes quite a while to download stuff.

### Steps to reproduce
Attempt to upgrade or download `steam`. The `steam-runtime` package depends on it, and will fail on most downloads.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.18, NixOS, 19.03pre167858.f2a1a4e93be (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre168279.3bd7a3b3b96"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
results.

Since last time the issue was solved by @Synthetica9 , @Infinisil and @c0bw3b, I will mention them here just in case.

**Comment by christoph00** [comment]
i made a pr #55269

**Comment by ivan-m** [comment]
The https://appradar.net mirror seems to be down now.

**Comment by shirona** [comment]
Closing issue since this has been solved by #55269. Thanks, @christoph00
