### ISSUE TITLE
localtimed user can't set timezone

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#55288]
## Issue description

I've just set `services.localtime.enable = true` on my laptop while on holiday. The timezone never updates (tried restarting, waiting a while).

Running `journalctl -b -u localtime` I see:

```
-- Logs begin at Thu 2018-12-27 01:52:52 NZDT, end at Wed 2019-02-06 12:17:39 NZDT. --
Feb 06 12:02:39 sima systemd[1]: Started localtime service.
Feb 06 12:03:02 sima localtimed[804]: Failed to set timezone: Pacific/Auckland
Feb 06 12:03:03 sima localtimed[804]: Failed to set timezone: Pacific/Auckland
```

I see in https://github.com/NixOS/nixpkgs/blob/release-18.09/nixos/modules/services/system/localtime.nix that the `localtimed` service is run as the `localtimed` user.

If I run: `sudo -u localtimed localtimed` I also see the message `Failed to set timezone: Pacific/Auckland`.

Whereas if I run `sudo localtimed` there is no output and the timezone immediately updates (as shown by an immediate change in the time in my status bar, and confirmed by running `timedatectl`).

It seems that the `localtimed` user just doesn't have permission to set the timezone.

### Steps to reproduce

1. Set `services.localtime.enable = true` in `/etc/nixos/configuration.nix` (and unset `time.timeZone`)
2. `sudo nixos-rebuild switch`
3. Wait to see if timezone changes
4. `journalctl -b -u localtime`, look for messages with "Failed to set timezone" (will only appear if the timezone it would need to set is different than the current timezone)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre166987.bc41317e243"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vlaci** [comment]
It worked for me after a reboot. Maybe the polkit rules are not getting appliead during a `nixos-rebuild switch`?
