### ISSUE TITLE
gnome-keyring test failure on staging

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#55293]
## Issue description
See: https://hydra.nixos.org/build/88208186

**Comment by hedning** [comment]
I'm not able to reproduce the exact test failure. The first build I tried failed a test, the second passed. So that should confirm our suspicion that the tests can fail sometimes.

**Comment by worldofpeace** [comment]
> I'm not able to reproduce the exact test failure. The first build I tried failed a test, the second passed. So that should confirm our suspicion that the tests can fail sometimes.

I guess that means they're pretty flaky, and something we should be fixing upstream.

If they cause consistent problems we should just disable them.

**Comment by worldofpeace** [comment]
Ah looks like we've seen this before in: 
- https://github.com/NixOS/nixpkgs/pull/45950#issuecomment-438295424

**Comment by hedning** [comment]
Looks like [fedora](https://src.fedoraproject.org/rpms/gnome-keyring/blob/master/f/gnome-keyring.spec) doesn't run the check phase, arch runs it but doesn't record the failure. So I'm guessing we should turn checking off.

**Comment by worldofpeace** [comment]
I agree, also looks like checks for gcr and libsecret are disabled in nixpkgs also.

This change is incoming shortly.
