### ISSUE TITLE
nix upgrade-nix downgrades nix

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#55360]
## Issue description
`nix upgrade-nix` downgraded nix from 2.2.1 to 2.2.

### Steps to reproduce
1. Use `curl https://nixos.org/nix/install | sh` to install nix on a new linux system (aarch64 in my case). It downloads and installs nix 2.2.1.
2. Run `nix upgrade-nix`: it installs nix 2.2.

**Comment by matthewbauer** [comment]
This is because no one has updated Nix in Nixpkgs! /cc @edolstra

**Comment by Thra11** [comment]
The versions involved in the original issue (which, if I remember correctly, was particularly annoying because 2.2 had a nasty bug which 2.2.1 fixed) are history now.

It looks like the install script will currently install Nix 2.3.5, and `nix upgrade-nix` keeps the same version. I don't know whether the versions are likely to get out of sync again in the future, but I guess we can close this.
