### ISSUE TITLE
unifi module doesn't open port 6789

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#55377]
## Issue description

`nixos/modules/services/networking/unifi.nix` opens most of the ports required for the Unifi controller, except it's missing port 6789, which is used for the UniFi mobile speed test.

/cc @erictapen

**Comment by erictapen** [comment]
Hey @lilyball, I took the maintainership for `unifi` only recently, so could you elaborate on what the UniFi mobile speed test is? I can't find good info about that on UBNT's support site.

`services.unifi.openPorts` includes only the minimum required ports. Depending on wether 6789 is strictly required for operation, I'd add it [there](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/unifi.nix#L128) or if not, it could be mentioned in the [doc](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/unifi.nix#L89) of `openPorts`, as 8443 is.

**Comment by lilyball** [comment]
The UniFi iOS app has 2 features that rely on this port. The first is the WiFi Throughput test and the second is the Heatmap overlay.

IMO all L3 ports should be opened except for 8443, and the only reason to exclude 8443 by default is because the operator may wish to configure a server on port 443 to proxy the unifi controller (which is exactly what I’m doing, using `caddy`), which would make port 8443 redundant. But the other ports (including 6789) don’t have the potential for being proxied like the web GUI does.

**Comment by erictapen** [comment]
Thanks for elaborating, I think that makes sense.

Would you mind to provide a PR to add 6789 to the open ports? If yes I can do it as well.

**Comment by lilyball** [comment]
PR submitted as #55416. Untested, but this change is pretty safe.
