### ISSUE TITLE
systemd: Empty name in error message

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#55382]
## Issue description
When rebuilding the system, I see: 

> Failed to start local-fs.target: Unit -.mount is masked.

I'd expect to see something like "the unit specified on [line:column] is masked" or something that outright forbids to have empty names.

### Steps to reproduce

?

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.95, NixOS, 18.09.git.8008d0b (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
That's no empty name, the name is `-`, `-.mount` to be exact. And that's the root mount point, as you can see in `systemctl --all` or documented in `man systemd.special`
