### ISSUE TITLE
LLVM package missing targets which are supposed to be enabled by default

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#55397]
#52031 broke the LLVM package. Previously all the LLVM default targets were built, now we have only these targets built (on my machine):

```
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

LLVM is a general purpose library for compiler frontends, you can't just delete target backends from it.

**Comment by matthewbauer** [comment]
This was fixed in d6f401e132ebc9083c64dc2d7a7574344c49a9c9.

**Comment by andrewrk** [comment]
Ahh really happy to hear that. Thanks! I was worried that I was going to get push back on this.

**Comment by dtzWill** [comment]
Nope! Conceivably a platform's bootstrap and base compiler (when clang or llvm-based) might eventually elide these but for anything using 'llvm' as a dependency (like zig) wouldn't be impacted, for he reasons you say. :).

And this isn't currently part of anyone's plans AFAIK anyway :). Glad it works now!
