### ISSUE TITLE
module kernel_config uses removed attribute option

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#55415]
## Issue description
With PR #54637 the attribute option was removed. The module nixos/modules/system/boot/kernel_config.nix still uses that attribute.
That module is used to set custom kernel configuration via overriding structuredExtraConfig.

### Steps to reproduce
Example nix expression
```
mylinux = pkgs.linuxPackages.kernel.override {
  structuredExtraConfig.SND = "n";
};
```

```
$ nix-build -A mylinux
error: The option value `settings.SND' in `<unknown-file>' is not of type `submodule'.
(use '--show-trace' to show detailed location information)
```

## Technical details

 - system: `"aarch64-linux"`
 - host os: `Linux 4.20.3, NixOS, 19.03pre166987.bc41317e243 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre168320.2d6f84c1090"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ck3d** [comment]
@danbst could you please have a look.

**Comment by danbst** [comment]
@ck3d yes, sure. Works for me with
```
  boot.kernelPackages = pkgs.linuxPackages_latest.extend (lib.const (ksuper: {
    kernel =
      with import <nixpkgs/lib/kernel.nix> { inherit lib; version = ksuper.kernel.version; };
      ksuper.kernel.override {
        structuredExtraConfig.SND = no;
      };
  }));
```
or
```
  boot.kernelPackages = pkgs.linuxPackages_latest.extend (lib.const (ksuper: {
    kernel =
      ksuper.kernel.override {
        structuredExtraConfig.SND.freeform = "n";
      };
  }));
```
Please, confirm if this solves your problem.

**Comment by ck3d** [comment]
Both ways worked for me. Thanks for the fast help!

The reason I described in the issue description seems to be wrong, as kernel_config.nix don't need to be changed. Sorry for that!
