### ISSUE TITLE
Paraview: version bump

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#55427]
https://github.com/Kitware/ParaView/archive/v5.6.0.tar.gz
sha256: e1fb86a5158d7335fe76bdf81be50ccf50e3af022974c8ea13b15f60bbe2e443
Release notes: https://blog.kitware.com/paraview-5-6-0-release-notes/

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/paraview/default.nix

CC @acowley

**Comment by acowley** [comment]
I was able to build this, but it's crashing on startup with OpenGL problems. Have you had any luck with it?

Here is [my branch](https://github.com/acowley/nixpkgs/tree/paraview-5.6.0) with the update.

**Comment by cpages** [comment]
In master since 8839a613d7ebe04fc62766ac59ed45248a7f65ef. Thanks.
