### ISSUE TITLE
Request for `nix-build` to have a flag that disables the `checkPhase`.

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#55425]
This is a feature request. I would find it quite useful to have a flag with `nix-build` to skip the `checkPhase`. I know this is possible by overriding the derivation, wouldn't having a flag for this be way more convenient so that it can be done on the command line instead.

The main reason for this is that in some cases tests cannot be run on the machine where the build is occurring. For example I have an application that has a `checkPhase` running tests that involve the GPU. But on machines without the GPU they can still build the output, but cannot run the tests.

**Comment by matthewbauer** [comment]
This will probably require changing how Nix works. Right now if you set ```doCheck = false``` everywhere, Nix will try to rebuild all of your packages with ```doCheck = true``` and you can't use the binary cache. We need a way to tell Nix that some attrs are "impure" and to not put them in the .drv file.

**Comment by FRidh** [comment]
Probably best then to move the tests into a separate derivation and use `requiredSystemFeatures` in that one.

Anyway, this is a Nix issue, not Nixpkgs, so closing.

**Comment by CMCDragonkai** [comment]
What do you mean `requiredSystemFeatures`?

**Comment by FRidh** [comment]
@CMCDragonkai please check the Nix manual...

**Comment by CMCDragonkai** [comment]
@FRidh So I see that `requiredSystemFeatures` can be used in conjunction with `system-features` of the `nix.conf`. This basically allows us to state that a derivation can only run on a system with given set of features. Are these features just arbitrary strings? Is there a way to say `nvidia` and for something to actually check if an NVIDIA GPU exists?

**Comment by FRidh** [comment]
These are indeed just strings. No, there is no way to check for this, it's all declarative.

**Comment by raboof** [comment]
(sorry to revive such an old issue, but it seems it's still well-indexed by search engines)

> I have an application that has a `checkPhase` running tests that involve the GPU. But on machines without the GPU they can still build the output, but cannot run the tests.

Where possible it's preferable to move those from `checkPhase` (or `installCheckPhase`) to `passthru.tests` - more details in https://nixos.org/manual/nixpkgs/unstable/#var-meta-tests

**Comment by hraban** [comment]
> Anyway, this is a Nix issue, not Nixpkgs, so closing.

I thought the very concept of the checkPhase, or just phases in general, was not just nixpkgs but stdenv specific. How is it a nix issue?

A work-around for anyone who needs to rebuild an entire system from stdenv as fast as possible without checks:

```
nix build --impure --expr '
let
  disableCheckIfDeriv = deriv: (deriv.overrideAttrs or (_: deriv)) {doCheck = false;};
  p = import /your/nixpkgs {
    config = {replaceStdenv = {pkgs}: pkgs.fastStdenv; };
    overlays = [(self: builtins.mapAttrs (name: disableCheckIfDeriv))];
  };
in
  p.hello
'
```
