### ISSUE TITLE
Dead links to Disnix

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5543]
On https://nixos.org/disnix/ there are various dead links, of which this one is just one example. 
http://hydra.nixos.org/job/disnix/HelloWorldExample-simple-trunk/doc/latest/download-by-type/doc/manual

Recommended solution: use a crawler which reports these dead links automatically.

**Comment by svanderburg** [comment]
Yeah, I'll fix these soon

**Comment by pSub** [comment]
The links seem to be fixed.

**Comment by svanderburg** [comment]
Yes that's right. Forgot about this issue though, but thanks for checking
it!
