### ISSUE TITLE
jetbrains.rider: debugger won't start for dotnet project

### ISSUE THREAD

**Issue by jirkadanek** [NixOS/nixpkgs#55435]
## Issue description

The rider gui prints "One or more errors occurred." when I attempt to start project binary in debug mode. The binary is not started.

### Steps to reproduce

1. Create .Net Core project from template.
2. Put a breakpoint in code.
3. Try to run it in debug mode.

Open Idea logs, notice the following in ~/.Rider2018.3/system/log/DebuggerWorker/JetBrains.Debugger.Worker.2019_2_08_10_35_13/

```
10:35:16.516 |V| DebugSessionFrontend          | Debugger worker MTA main thread:3 | Breakpoint /home/jdanek/projects/djObik-trigger/Program.cs, line 56 status changed: NotBound Not found associated module for breakpoint Program.cs:56,14
10:35:16.521 |V| DebugSessionFrontend          | Debugger worker MTA main thread:3 | Exception breakpoint added, exception System.Threading.ThreadAbortException
10:35:17.494 |V| CoreClrDebuggerUtil_Nojif     | :26                | Got CLR load callback from the debugger. The operation failed. The error code is CORDBG_E_DEBUG_COMPONENT_MISSING, or 0x80131C3C.
10:35:17.509 |V| CoreClrDebuggerUtil_Nojif     | Thread Pool Worker:24 | Done awaiting. Got CLR Callback? True! Timeout expired? False!
10:35:17.514 |V| DebugSessionFrontend          | Debugger worker MTA main thread:3 | Event from debugger: type TargetExited
10:35:17.701 |W| DebuggerWorker                | Debugger worker MTA main thread:3 | Failed to startup debugger. Fire terminating One or more errors occurred. CLR load callback is already in error state. The operation failed. The error code is CORDBG_E_DEBUG_COMPONENT_MISSING, or 0x80131C3C.

--- EXCEPTION #1/5 [COMException]
Message = “CLR load callback is already in error state. The operation failed. The error code is CORDBG_E_DEBUG_COMPONENT_MISSING, or 0x80131C3C.”
ExceptionPath.1 = Root.InnerException.InnerException.InnerException.InnerException
ExceptionPath.2 = Root.InnerException.InnerException.InnerExceptions.#0.InnerException
ExceptionPath.3 = Root.InnerException.InnerException.InnerException.InnerExceptions.#0
ExceptionPath.4 = Root.InnerException.InnerException.InnerExceptions.#0.InnerExceptions.#0
ClassName = System.Runtime.InteropServices.COMException
HResult = CORDBG_E_DEBUG_COMPONENT_MISSING=80131C3C
Source = JetBrains.Debugger.CorApi
StackTraceString = “at JetBrains.Debugger.CorApi.Pinvoke.CoreClrDebuggerUtil.RuntimeLoadCallback (System.Int32 hr, System.Void* pCordb, System.Threading.Tasks.TaskCompletionSource`1[TResult] taskWaitForStartup, System.Action`1[T] corDebugLoadhandler, System.UInt32 procId, JetBrains.Util.ILogger logger) [0x00014] in <3e14868adbae498dad98d2cd39c6659e>:0”

--- Outer ---

--- EXCEPTION #2/5 [AggregateException]
Message = “One or more errors occurred.”
ExceptionPath.1 = Root.InnerException.InnerException.InnerException
ExceptionPath.2 = Root.InnerException.InnerException.InnerExceptions.#0
[...]
```

## Workaround

Start rider in a shell with

    export LD_LIBRARY_PATH=/nix/store/l2yzllcn2injxx4qs21f2703ia56nqz8-dotnet-sdk-2.2.103/shared/Microsoft.NETCore.App/2.2.1/

in addition to that, I am also doing

    export MSBuildExtensionsPath=/home/jdanek/Downloads/msbuild/Extensions

as a workaround for issue discussed on https://github.com/NixOS/nixpkgs/pull/43680 (still open). I downloaded that `msbuild` directory from mono project.

**Comment by masaeedu** [comment]
Thanks for the workaround btw. This affects VS Code as well, and the same workaround applies.

**Comment by baracoder** [comment]
Maybe we can package this workaround for now with rider, until we have a properly packaged msbuild. What do you think?

**Comment by jdanekrh** [comment]
Possibly got fixed by upgrading dotnet-sdk. I now use version 2.2.401 from https://github.com/NixOS/nixpkgs/pull/66057 and debugger starts for me without the workaround.

**Comment by baracoder** [comment]
Works for me on unstable with rider 2019.2.1

**Comment by husseinraoouf** [comment]
still not working for vscode

**Comment by husseinraoouf** [comment]
after some search, I now think my problem is related to https://github.com/OmniSharp/omnisharp-vscode/issues/3676
not related to nixos

**Comment by baracoder** [comment]
Original issue seems to be solved, closing this one

**Comment by danverde** [comment]
I'm experiencing the same issue on Rider 2020.2.2 & MacOS 10.15.6

**Comment by ueatsomen** [comment]
Same thing
