### ISSUE TITLE
update canon-cups-ufr2 

### ISSUE THREAD

**Issue by cptMikky** [NixOS/nixpkgs#55447]
Canon UFRII driver is outdated (nixpkgs version is at 2.90).

Newer version (currently 3.70) with broader hardware support is available: 

http://gdlp01.c-wss.com/gds/8/0100007658/08/linux-UFRII-drv-v370-uken-05.tar.gz

**Comment by kylesferrazza** [comment]
5.00 available, arch PKGBUILD may help with the upgrade: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cnrdrvcups-lb
