### ISSUE TITLE
haskellPlatform not found on NixOS

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5545]
`nix-channel --list`
```
nixos https://nixos.org/channels/nixos-14.12

```
`nix-channel --update` runs OK
`nix-env -iA nixos.pkgs.haskellPlatform` returns
```
error: attribute `haskellPlatform' in selection path `nixos.pkgs.haskellPlatform' not found
```
This used to work fine on 14.04. I was able to install firefox on the same machine via `nix-env -i firefox` and `nix-env -qaP | grep haskell` does return a lot of packages. 

Nix version: 1.7

**Comment by lethalman** [comment]
haskellPlatform has been dropped, see https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg13621.html . Closing.
