### ISSUE TITLE
Home-assistant setup

### ISSUE THREAD

**Issue by M-Gregoire** [NixOS/nixpkgs#55479]
## Issue description

Hi,

I'm trying to setup an home-assistant server using NixOS (cc @dotlambda @peterhoeg ). I'm using the package `home-assistant` from the channel `unstable` (also tested on the release channel).

My configuration is the following:

```
{ config, pkgs, ... }:
{
  services.home-assistant = {
    enable = true;
    port = 8123;
    config = {
      homeassistant = {
        name = "Home";
        time_zone = "Europe/Paris";
        latitude = 1;
        longitude = 1;
        elevation = 1;
        unit_system = "metric";
        temperature_unit = "C";
      };
      # Enable the frontend
      frontend = { };
    };
  };
}
```

The resulting config, `/var/lib/hass/configuration.yaml` is the following:
```
frontend: {}
homeassistant:
  elevation: 1
  latitude: 1
  longitude: 1
  name: Home
  temperature_unit: C
  time_zone: Europe/Paris
  unit_system: metric
http:
  server_port: '8123'
```

I have no experience with home-assistant but I believe that:
- The `frontend` field should be empty, not `{}`
- The `server_port` should be an integer not between quote

Finally, I have no access to the frontend, `ip:8123` results in a timeout.

`systemctl status home-assistant.service` gives me:
```
home-assistant.service - Home Assistant
   Loaded: loaded (/nix/store/y95lbh8k79wa7kji6f4s3cj8a4w57w5j-unit-home-assistant.service/home-assistant.service; linked; vendor preset: enabled)
   Active: active (running) since Sat 2019-02-09 14:59:03 CET; 9min ago
  Process: 3297 ExecStartPre=/nix/store/5xvk246sl8gp6bjpl303iw2jlyq1nhaf-unit-script-home-assistant-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 3308 (.hass-wrapped)
    Tasks: 12 (limit: 4915)
   Memory: 37.9M
   CGroup: /system.slice/home-assistant.service
           └─3308 /nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/bin/python3.7 /nix/store/m05yyxd8n6k0fywjvh7bf1r91flxsyfh-homeassistant-0.86.4/bin/>

Feb 09 14:59:06 hostname hass[3308]: 2019-02-09 14:59:06 INFO (MainThread) [homeassistant.setup] Setting up auth
Feb 09 14:59:06 hostname hass[3308]: 2019-02-09 14:59:06 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
Feb 09 14:59:06 hostname hass[3308]: 2019-02-09 14:59:06 INFO (MainThread) [homeassistant.setup] Setting up onboarding
Feb 09 14:59:06 hostname hass[3308]: 2019-02-09 14:59:06 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds.
Feb 09 14:59:06 hostname hass[3308]: 2019-02-09 14:59:06 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.0 seconds.
Feb 09 14:59:06 hostname hass[3308]: 2019-02-09 14:59:06 INFO (MainThread) [homeassistant.setup] Setting up frontend
Feb 09 14:59:07 hostname hass[3308]: 2019-02-09 14:59:07 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 1.0 seconds.
Feb 09 14:59:07 hostname hass[3308]: 2019-02-09 14:59:07 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 1.65s
Feb 09 14:59:07 hostname hass[3308]: 2019-02-09 14:59:07 INFO (MainThread) [homeassistant.core] Starting Home Assistant
Feb 09 14:59:07 hostname hass[3308]: 2019-02-09 14:59:07 INFO (MainThread) [homeassistant.core] Timer:starting
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.git.3acebb03952 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
```

Thank you for any information or lead you could provide to make this work as intended. I'd be happy to help fix the issue if the problem is confirmed and not from a mistake of mine.

**Comment by dotlambda** [comment]
> * The `frontend` field should be empty, not `{}`

You specified `frontend = { }` in your `config`. You can alternatively specify `frontend = null`, but there seems to be no way to make remarshal produce `frontend: `. However, this shouldn't make any difference to Home Assistant.

> * The `server_port` should be an integer not between quote

Indeed. This should be an integer: https://www.home-assistant.io/components/http#server_port. I have pushed efe98cbdc891b45ec780d57c9debfb091d18461f.

**Comment by M-Gregoire** [comment]
Thanks a lot for your quick answer.

Do you have any idea of what could explain the timeout when trying to access the frontend on `ip:8123`? I waited more than an hour to be sure everything was correctly setup but always ended up with the same result.

Apart from the systemctl logs, is there anything I could check?

`/var/lib/hass/home-assistant.log` only contains the following
```
2019-02-09 14:59:06 WARNING (MainThread) [homeassistant.bootstrap] Skipping pip installation of required modules. This may cause issues
```

**Comment by dotlambda** [comment]
@M-Gregoire I'm trying to reproduce that timeout and I have no idea what's causing it. Can you try building the whole system from the unstable channel?

**Comment by dotlambda** [comment]
I also built your configuration on release-18.09, just using the home-assistant package from the unstable channel. I'm sorry but I couldn't reproduce the timeout.

**Comment by M-Gregoire** [comment]
Might it be that I'm missing something in my config?

When running `curl 127.0.0.1:8123` from the host where hass is install, i get 
> INFO (MainThread) [homeassistant.components.http.view] Serving / to 127.0.0.1 (auth: False)
in the log, however, curl returns nothing.

Running `curl ip-server:8123` from another machine lead to a timeout with nothing in the log. There is no firewall on the host.

**Comment by M-Gregoire** [comment]
@dotlambda Side note: In order to debug my config, I tried `./hass --script check_config -c /var/lib/hass/` but `ERROR:homeassistant.util.package:Unable to install package colorlog==4.0.2: /nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/bin/python3.7: No module named pip`

Should we either add `pip` or `colorlog` to the dependencies ?

**Comment by M-Gregoire** [comment]
I've been trying a few things to investigate the problems. Here is a full recap of what is wrong and what I did to try to fix it.

### Current config

```
  services.home-assistant = {
    enable = true;
    package = pkgs.home-assistant.override {
      extraPackages = ps: with ps; [ colorlog ];
    };
    port = 8123;
    config = {
      homeassistant = {
        name = "Home";
        time_zone = "Europe/Paris";
        latitude = config.resources.geo.latitude;
        longitude = config.resources.geo.longitude;
        elevation = config.resources.geo.elevation;
        unit_system = "metric";
        temperature_unit = "C";
      };
      # Enable the frontend
      frontend = {};
      http = {};
    };
  };
```

### Problems

- I'm trying to use the `check_config` script to test the generated config. I'm using `/nix/store/<hash>-python3-3.7.2/bin/python3.7 /nix/store/<hash>-homeassistant-0.86.4/bin/hass --script check_config -c /var/lib/hass/` but this results in
```
  File "/nix/store/<hash>-homeassistant-0.86.4/bin/hass", line 2
    export PATH='/nix/store/<hash>-python3-3.7.2/bin:/nix/store/<hash>-homeassistant-0.86.4/bin:/nix/store/<hash>-python3.7-setuptools-40.6.2/bin:/nix/store/<hash>-python3.7-chardet-3.0.4/bin:/nix/store/<hash>-python3.7-PyJWT-1.6.4/bin:/nix/store/<hash>-python3.7-pip-18.1/bin:/nix/store/<hash>-python3.7-python-slugify-1.2.6/bin:/nix/store/<hash>-python3.7-Unidecode-1.0.23/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax

```
Simply running `./hass --script check_config -c /var/lib/hass/` from the store path lead to `ERROR:homeassistant.util.package:Unable to install package colorlog==4.0.2: /nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/bin/python3.7: No module named pip`

Am i missing something here?

- Second problem, frontend is not working. From an external machine, I get a timeout and from localhost just nothing (`curl localhost:8123` returns a blank line).

### What I tried

- Changing the port used by home-automation
- Triple-checked firewall (every other service works perfectly fine on this server)
- Disabled everything but home-assistant
- Checked server has access to internet with correct DNS
- Tried to look more closely in the log (but can't due to bug number 1)
- Walk-through the documentation in case I was missing something


I'm out of idea, if the problem persists I will probably go with a docker installation instead. Any help/advice is welcome and appreciated!

**Comment by dotlambda** [comment]
> I'm trying to use the `check_config` script to test the generated config. I'm using `/nix/store/<hash>-python3-3.7.2/bin/python3.7 /nix/store/<hash>-homeassistant-0.86.4/bin/hass --script check_config -c /var/lib/hass/`

The `hass` executable is a wrapper around `.hass-wrapped` written in bash. Good luck interpreting that as Python. What you'll want to do to use `check_config` is `nix-shell -E`. I do not currently have time to look into it.

**Comment by M-Gregoire** [comment]
Okey, I finally got it working (and feel a bit dumb about the problem)!

I thought the firewall was disabled by default in NixOS but it's not, only port 22 is open if OpenSSH is enabled. Simply adding `networking.firewall.allowedTCPPorts = [ 8123 ];` fixed my problem.

Sorry about this long issue for such a problem. Thanks a lot for spending some of you time to help me :+1: .

**Comment by dotlambda** [comment]
I'm glad you were able to solve it!
Btw, you can use the `openFirewall` option to open the port.
