### ISSUE TITLE
jq manpage not linked

### ISSUE THREAD

**Issue by robx** [NixOS/nixpkgs#55478]
## Issue description

I just installed jq version 1.6 on macOS. The man page makes it to the nix store, but not into the nix profile.

### Steps to reproduce

    $ nix-env -iA nixpkgs.jq
    $ man jq
    No manual entry for jq

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.3`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(rob): `"nixpkgs-19.03pre167327.11cf7d6e1ff"`
 - nixpkgs: `/Users/rob/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
I believe this was fixed with https://github.com/NixOS/nixpkgs/pull/35884.

**Comment by robx** [comment]
Oh good. Should have run `nix-channel --update` before reporting, can confirm it works now. Sorry for the noise.
