### ISSUE TITLE
nix-env -i perl-DBD-mysql runs tests!?

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5549]
I had expected `nix-env -i perl-DBD-mysql` to download a bunch of code and just put that into my store, but that's not what's happening. Instead, it tries to connect to mysql for which it apparently needs some credentials. I could not care less about these tests, currently. 

So, all I want is `nix-env -i perl-DBD-mysql` to just download a precompiled expression and if that's not possible, disable the tests (or have the tests written in such a way that they actually work). The point of packaging something is automation and if the tests fail or depend on something stupid as giving a 'sekrit' user (or something similar) access to every table, then something is seriously wrong.

**Comment by bjornfor** [comment]
If it runs some tests, it means you didn't get the precompiled binaries.

I believe there is a flag you can set to not build locally if there are no precompiled binaries. Look in man pages.

I'm not really a mysql user, but I've noticed that the perl DBD mysql module runs some tests that may succeed or not (or skipped... don't remember), depending on whether your machine runs mysql or not.

Maybe it's better that we disable these tests?

**Comment by iElectric** [comment]
You can disable tests via `~/config/.nixpkgs/config.nix`

**Comment by wwat** [comment]
https://nixos.org/nixos/options.html searching for test does not return anything of interest. In general, you cannot really give too much information.

**Comment by bjornfor** [comment]
@wwat: I guess @iElectric refers to the possibility to override derivation attributes in ```~/.nixpkgs/config.nix```:
http://nixos.org/nixos/manual/ch-options.html#opt-nixpkgs.config

So you could disable the tests yourself, by setting ```doCheck = false``` for the perl DBD mysql derivation.

But if the tests are broken/bad from a distro perspective, I think we should disable them.

Your issue title is about nix-env not being supposed to run tests. That's a misunderstanding. If a package has no binaries, it will be built locally. And building may include running tests.
