### ISSUE TITLE
Missing hyper links to wpa_supplicant.conf(5) in manual

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55505]
## Issue description

References to wpa_supplicant.conf(5) should have hyperlinks to the article/section.

> You should edit this file yourself to define wireless networks, WPA keys and so on (see wpa_supplicant.conf(5)).

**Comment by rycee** [comment]
These are references to man pages so there can't easily be a hyperlink. I made a PR that makes sure these are referenced to using `<citerefentry>`, though. So that they at least carry some semantic meaning.

**Comment by AMDphreak** [comment]
My bad I didn't think about the man pages. There are man pages online, too. 

I found this site: https://linux.die.net/man/5/wpa_supplicant.conf

but it'd be nice to have a programmatically-included version in the NixOS documentation. Having the man page sources piped into HTML would be useful I suppose...if not a huge space waster.
