### ISSUE TITLE
Syntax errors in manual: {} without ; after

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55506]
## Issue description

Throughout the manual there are lines that have {} blocks followed by ; to close each block, but there are also {} blocks with no ; to close each block. Isn't this a syntax error?

Example:

> ```
> { echelon = {
>     psk = "abcdefgh";
>   };
>   "free.wifi" = {};
> }
> ```

https://nixos.org/nixos/manual/options.html#opt-networking.wireless.networks

**Comment by rycee** [comment]
Leaving out the outermost `;` is a syntax error in some contexts but not all, for example, when used in a list or inside a parenthesized expression. I therefore prefer to leave it out in the documentation, primarily for esthetic reasons.
