### ISSUE TITLE
[RFC] NixOS Xorg service: should we remove `intel` from default `videoDrivers`

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#55520]
Right now NixOS puts a lot of Xorg-level video drivers into the default configuration. It looks like having `intel` creates problems now that we have Xorg 1.20.

(I am not using NixOS but I do use the NixOS `xorg.conf` generation code)

Xorg 1.20 has updated many things. In particular it broke Nvidia binary driver ABI compatibility (to the surprise of no one) and a popular suggestion on the forums is «just use Nouveau». On my Intel+Nvidia Thinkpad I have happily used Nouveau for a long time already with XRandR offload, but Xorg 1.20 still broke my configuration. After some more debugging and log-comparing and web-searching, it looks like:

`i915/intel` for Intel card + `nouveau/modesetting` for Nvidia leads to working built-in display, but broken VGA output (offloading doesn't work properly, although the colour range of the garbage on the screen seems roughly correct, and the mouse pointer works for some weird reason).

`videoDrivers = mkForce ["modesetting"];` solves the visible problems, `modesetting` is used correctly for both outputs, `xrandr` works.

(as a side note: when building _only_ the Xorg service, apparently two LLVM builds are necessary — maybe it was fixed since Xorg 1.20 bump, though)

**Comment by vcunat** [comment]
I _think_ I heard some year ago (roughly) that distributions tend to shift to use "modesetting" by default for Intel cards, so I suppose it wouldn't cause many problems.

**Comment by 7c6f434c** [comment]
Oh, I found some specifics, I think…

Ubuntu and Debian switched by mid-2016 (speaking of unstable repositories) for «newer» GPUs, apparently «newer» means 2007 and later. Fedora followed in January 2017.

Is it OK to just put a footnote in release notes and not even try recognising the 2007-and-older Intel GPUs?

**Comment by vcunat** [comment]
Sounds OK to me.

**Comment by dtzWill** [comment]
Arch's wiki mentions a few things we may wish to confirm/check-if-still-accurate:

https://wiki.archlinux.org/index.php/intel_graphics

For example the wiki claims:

> Also, the modesetting driver will not be benefited by Intel GuC/HuC/DMC firmware.

Presumably this is a limitation and not a feature ("no extra firmware bits needed, yay!").

---

Regardless I've been just using `modesetting` by itself for a while now.  xf86-video-intel HAS been receiving updates lately (last few weeks), so I'm honestly not sure what Intel is expecting folks to be using? And there's the tearing issue w/chrom{e,ium}, although maybe there's a good solution there :).

Yes users can specify the previous behavior but it'd be nice to provide best out-of-the-box experience possible! :)

**Comment by 7c6f434c** [comment]
I am not sure anymore if we want to provide the best out of the box experience or the most stable out of the box experience. A gap where using the latest `intel` driver means that connecting projectors to Thinkpad is black magic sounds like an argument for `modesetting` by default — maybe with a better list of tradeoffs in documentation.

**Comment by dtzWill** [comment]
On Mon, 11 Feb 2019 21:31:41 -0800, Michael Raskin <notifications@github.com> wrote:
> I am not sure anymore if we want to provide the best out of the box experience or the most stable out of the box experience.

"best" is perhaps in need of a clear definition,
to some "best" does mean "stable" :).

IMO "best" certainly includes stability as a leading consideration :).
(especially "best out-of-the-box",
tweaking for features >>> tweaking to not crash)

> A gap where using the latest `intel` driver means that connecting
> projectors to Thinkpad is black magic sounds like an argument for
> `modesetting` by default — maybe with a better list of tradeoffs in
> documentation.

:+1: to documentation being important, either way :).

I think we are agreeing? ^_^

**Comment by 7c6f434c** [comment]
Technically, attaching a projector to Thinkpad doesn't _crash_ with the new X.org and old `intel` driver, it just doesn't produce any readable text on the projector.

Re: documentation — I think the details should be discussed in the PR as change requests. My values are «Firefox and terminal and PDF viewers work on all screens > XScreenSaver hacks LavaLite & Menger work acceptable > what else is there to wish?», so I am not sure what are the main tradeoffs to document (and advice on placement is welcome, right now I only put a release note about the change)

**Comment by obadz** [comment]
So #55583 caught me by surprise as output names in xrandr changed from `{ DP1, DP2, HDMI2 }` ⇒ `{ DP-1, DP-2, HDMI-2 }` which broke my X session script:

```nix
  services.xserver.displayManager. sessionCommands = ''
    ${pkgs.xorg.xrandr}/bin/xrandr --output DP1 --right-of HDMI2 --primary
    ${pkgs.xorg.xrandr}/bin/xrandr --output DP2 --right-of DP1
  '';
```

As well as my i3 bar setup:

```
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status --config ~/.i3/status.conf
        position top
        output LVDS1
        output DP1
        output eDP1
}
```

Might be worth mentionning this specifically in `nixos/doc/manual/release-notes/rl-1903.xml` ?

**Comment by 7c6f434c** [comment]
>So #55583 caught me by surprise as output names in xrandr changed from `{ DP1, DP2, HDMI2 }` ⇒ `{ DP-1, DP-2, HDMI-2 }` which broke my X session script:

My bad re: not mentioning this in the release notes (I did notice it, but my scripts adapt to this automatically so I didn't think about writing this down)

>Might be worth mentionning this specifically in `nixos/doc/manual/release-notes/rl-1903.xml` ?

Done.

**Comment by timokau** [comment]
Another regression is that `xbacklight` doesn't work with the `modesetting` driver:

```
xbacklight -set 10
No outputs have backlight property
```

There is a 3 year old ticket for this: https://bugs.freedesktop.org/show_bug.cgi?id=96572#c15

A [workaround](https://bugs.freedesktop.org/show_bug.cgi?id=96572#c15) is to use the `/sys` interface directly. Another one is using `brightnessctl`.

**Comment by 7c6f434c** [comment]
500d61560fb 97464d087ec

**Comment by vcunat** [comment]
I think we should close this ticket.  Discussion about improvements sure can continue here...

**Comment by timokau** [comment]
Should we maybe include a link to this issue? Someone experiencing issues is likely to want more details as to why they should care about intel vs. modesetting and how to work around issues.

**Comment by 7c6f434c** [comment]
I do not object but also am not sure enough to actually write the line with the link.

**Comment by timokau** [comment]
Any particular reason to be hesitant?

**Comment by 7c6f434c** [comment]
No arguments against — just not sure if the benefit is worth the effort of trying to add this line in a sane way. The release not in question is already losing readability a bit…
