### ISSUE TITLE
[RFC] makeInitrd main derivation name

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#55523]
## Issue description

`pkgs.makeInitrd` always has the same `name`, and the same filename inside.

### Steps to reproduce

Build NixOS with `copyKernels`, look into `/boot/kernels`

I think it would be sometimes more convenient if the kernel version would be clear for each `initrd` (which is actually initramfs). I think it would be better to literally include the `kernel.name` as a suffix to `name`.

**Comment by nh2** [comment]
This sounds like a sane idea to me.
