### ISSUE TITLE
`ocropus-ltrain` fails with `ImportError: No module named clstm`

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nixpkgs#55537]
## Issue description

`ocropus-ltrain` fails with `ImportError: No module named clstm`

### Steps to reproduce

`nix-shell -p ocropus --run ocropus-ltrain`

## Technical details

On nixpkgs commit `749a3a0d00b`. Also reproduces on `master` and on `17.09` that I had at hand.

cc @domenkozar

**Comment by FliegendeWurst** [comment]
Package was removed in #170176
