### ISSUE TITLE
Long term reproducibility, archival

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#55588]
I'm not in the right mindset right now to really start thinking about this deeply, but I would like to start the discussion.

Nixpkgs and the reproducibility it provides seems possibly advantageous for archival or whatever other reasons, but it "only" provides the general build environment descriptions, however it seems one-of-a-kind in providing at least that.

What happens in general, in 3, 5, 10, 20 years, when some code archaeologist comes back wanting something?

What happens with nix artefact descriptions a researcher provides with his work for later reproducibility?

Is this something deemed worth considering?

**Comment by teto** [comment]
I guess one would need to create a subsituter will all sources. Then in 20 years, is the hardware going to be able to run this old software ? You may already know but this kind of question is the pet subject of https://en.wikipedia.org/wiki/Vint_Cerf

**Comment by FRidh** [comment]
Related discussion about Software Heritage #53653

**Comment by deliciouslytyped** [comment]
Use case https://www.youtube.com/watch?v=Ee8k97Rx3DA

**Comment by FRidh** [comment]
It's an interesting topic but I don't think it's worth keeping it open as an issue.
