### ISSUE TITLE
Unset `GUILE_LOAD_PATH` (and probably other environment variables)

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#5558]
I started to use Nix on my Gentoo laptop.
Now, I installed `xbindkeys` and when I launched it I got this:

```
;;; note: source file /usr/share/guile/1.8/ice-9/boot-9.scm
;;;       newer than compiled /nix/store/h3lrkgm3jd241hby5vkj35na95a52p6g-guile-2.0.11/lib/guile/2.0/ccache/ice-9/boot-9.go
Throw without catch before boot:
Throw to key syntax-error with args ("memoization" "In file ~S, line ~S: ~A ~S." ("/usr/share/guile/1.8/ice-9/boot-9.scm" 101 "Bad defin
zsh: abort      xbindkeys
```

As I had no idea what guile was it took some time to figure out that it was looking for `boot-9` and it found it in `/usr/share/…`. As all the dates are reset in nix store, it thought that the compiled version of the library was older then the source it found and, I think, tried to use the source version.

For me this behaviour doesn’t make much sense, expecially in context of Nix.
Turns out the problem was the `GUILE_LOAD_PATH` environment variable which wasn’t empty in my case. In Nix the compiled binary should never try to recompile something or do other weird things.

So my question is: what do you think, might it be a good idea to wrap all the guile executables and unset `GUILE_LOAD_PATH`? Or maybe even patch guile libs or something (I don’t know what exactly causes this behaviour) not to check this environment variable?

**Comment by joachifm** [comment]
Still a problem?

**Comment by kirelagin** [comment]
No idea :/.
