### ISSUE TITLE
Would rather not type `pkgs.` for each package I install

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55623]
## Issue description

The manual describes no way to put packages inside a block so I can type `packagename` instead of `pkgs.packagename`.

Either this is a feature request, or a request to update documentation. Please label accordingly.

**Comment by srhb** [comment]
It's not completely clear what you're asking for (what is a block) nor which manual you'd like to be updated (nixpkgs? NixOS? Nix?). Can you make suggestions as to where exactly you'd like to see this information?

Also, are you talking about opening the scope of an attributeset like this? https://nixos.org/nix/manual/#idm140737317846928

**Comment by OPNA2608** [comment]
I believe what you're looking for is [`with`](https://nixos.org/nixos/manual/index.html#module-services-input-methods-ibus), as was pointed out above.

Example:
```
environment.systemPackages = with pkgs; [
  firefox
  thunderbird
  #...
];
```

**Comment by AMDphreak** [comment]
@srhb yeah my example isn't good, in retrospect. I'm following the NixOS manual.
@OPNA2608 egads! so that's what the `with` statement does. Thank you. This explanation is glaringly missing from the NixOS Manual Sec 6.1. This needs to be there.
