### ISSUE TITLE
pycurl tests fail on master

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#55637]
## Issue description
installing pycurl fails with test not running properly

if i have time tonight, i'll look into it.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.7, NixOS, 19.03.git.20e2f83 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre152924.5664e64a015"`
 - channels(bali): `"nixos-19.03pre165037.eebd1a92637"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ikervagyok** [comment]
@dtzWill could be this: https://github.com/NixOS/nixpkgs/commit/42446b15a7ff8a3135abb6091b71c646a7238417

**Comment by ikervagyok** [comment]
skipping the tests works, but i don't know if pycurl behaves correctly.

**Comment by dotlambda** [comment]
Even though the build failed on Hydra (https://hydra.nixos.org/build/88665904), I have no problem building `python3.pkgs.pycurl` locally.
@vcunat If I'm not mistaken, you're able to restarts build on Hydra, aren't you?

**Comment by vcunat** [comment]
Restarted.  I believe we should just systematically give this right to all who have push access.

**Comment by vcunat** [comment]
@ikervagyok: did you reproduce the error locally?  It succeeded also on Hydra now.

**Comment by ikervagyok** [comment]
@vcunat yes, i did reproduce this issue on two machines. but since it's fine now i'll close this and reopen if i run into this again.
