### ISSUE TITLE
ghc 8.4.4 broken by recent `staging` merge

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#55662]
The recent merge of `staging` into `master` broke the build of the GHC 8.4.4 Haskell compiler. See https://hydra.nixos.org/build/88256874 for details.

**Comment by xaverdh** [comment]
I just ran into the same issue when building ghc 8.4.4 locally (current nixos-unstable).

**Comment by jwiegley** [comment]
I ran into this as well yesterday.
