### ISSUE TITLE
Please update Steam

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#55675]
## Issue description

Newest version is 1.0.0.59, we have 1.0.0.56.

http://repo.steampowered.com/steam/pool/steam/s/steam/?C=M;O=D
https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/steam/steam.nix

cc @nyanloutre @abbradar

**Comment by FlorianFranzen** [comment]
This should not matter much. As far as I know, Steam copies itself to your home folder an then updates itself once you run it. Can you actually confirm that steam stays at that older version once you start it?

**Comment by nyanloutre** [comment]
Can you also check if there is any difference in the udev rule file ?

**Comment by davidak** [comment]
@FlorianFranzen yes, steam does some updates...

![screenshot from 2019-02-14 19-49-12](https://user-images.githubusercontent.com/91113/52809989-d9901380-3091-11e9-8328-3cb4091a0faf.png)

![screenshot from 2019-02-14 19-50-31](https://user-images.githubusercontent.com/91113/52810004-de54c780-3091-11e9-8d61-de18aa93ba7a.png)

But the versions have different schemes.

@nyanloutre there is one:

```
[davidak@X230:~/Downloads]$ diff steam/lib/udev/rules.d/60-steam-vr.rules steam2/lib/udev/rules.d/60-steam-vr.rules 
21a22
> KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="28de", ATTRS{idProduct}=="2102", TAG+="uaccess"

```

**Comment by cpages** [comment]
Updated in master, thanks!
