### ISSUE TITLE
Packages can't be built with GHC > 7.8

### ISSUE THREAD

**Issue by puffnfresh** [NixOS/nixpkgs#5568]
Filing an issue to be more accessible.

Using GHC > 7.8 to build packages results in:

```
haddock: internal error: ./package.cache: openBinaryFile: does not exist
```

This is because lots has changed, even in 7.10-RC1:

https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg13895.html

@peti has already solved this problem with haskell-ng branch:

https://github.com/peti/nixpkgs/tree/haskell-ng

It seems like it needs some more work before it's ready to merge, though.

**Comment by peti** [comment]
Haskell NG can compile with GHC 7.10.1-rc1 fine. The name of the package set is `haskell-ng.packages.ghcHEAD.<hackage-package-name>`. This is all available in the current `master` branch.

**Comment by puffnfresh** [comment]
Thank you :+1:
