### ISSUE TITLE
pandas failure on nixos-unstable: bump package ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#55684]
## Issue description
pandas seem to fail on nixos-unstable:
https://hydra.nixos.org/build/88550739

Also it would be nice to get pandas 0.24 since they now support nan integers .

### Steps to reproduce

CC @7c6f434c @FRidh @knedlsepp

**Comment by 7c6f434c** [comment]
Python2 version builds.

 I am not against a bump, but maybe @FRidh already knows that it should be done together with some other bumps.

**Comment by teto** [comment]
looks like tests need "hypothesis". I disabled the checks (as a quickfix)
and I can build pandas 0.24.1 for python3.

Le mer. 13 févr. 2019 à 16:52, Michael Raskin <notifications@github.com> a
écrit :

**Comment by FRidh** [comment]
bump is part of https://github.com/NixOS/nixpkgs/pull/55757

**Comment by FRidh** [comment]
also pushed the update to master as 4aaa34f7244126c31af23cb92850981715f71557
