### ISSUE TITLE
KDAB GammaRay package (WIP)

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#55682]
Tracking issue.

**Comment by solson** [comment]
Has there been any progress on this, or is anything blocking it?

**Comment by deliciouslytyped** [comment]
No, I haven't had time to work on this at all. I would be delighted if you would take it up!

**Comment by deliciouslytyped** [comment]
I've picked this up again and should hopefully have some at least minimally working code up soon.

**Comment by deliciouslytyped** [comment]
Please ping this issue if you want the nix expression for it, I need to clean it up a little before posting.

**Comment by deliciouslytyped** [comment]
I have no idea why I didn't post this here at least; this is how I run gammaray
```
#With a recent nixpkgs.
#If you run into errors like `Cannot mix incompatible Qt library (version 0x50c06) with this library (version 0x50c07)`, try a --pure shell
{ pkgs ? import <nixpkgs> {}
, fetchFromGitHub ? pkgs.fetchFromGitHub
, needsGLFix ? false #I needed this at some point but it seems fine now?
}:
let

  #Not sure why i need this, probably old nixpkgs thing - i need to parametrize this over qt versions
  nixGL = (import (fetchFromGitHub {
    owner = "guibou";
    repo = "nixGL";
    rev = "04a6b0833fbb46a0f7e83ab477599c5f3eb60564";
    sha256 = "0z1zafkb02sxng91nsx0gclc7n7sv3d5f23gp80s3mc07p22m1k5";
    }) { }).nixGLIntel;

  gammaray' = { mkDerivation, lib, fetchFromGitHub, cmake, qtbase }: mkDerivation {
    name = "Gammaray";
    src = fetchFromGitHub {
      owner = "KDAB";
      repo = "GammaRay";
      rev = "4245ead89ff7cdc613f69d1d6a9192a5b054695e"; #outdated now probably
      sha256 = "1wk6lsfflz00is33kncjh62c8w7c3gzj8898kakh58m5wbid9c9v";
      };
    buildInputs = [ qtbase ];
    nativeBuildInputs = [ cmake ]; 
    };

  gammaray = pkgs.libsForQt5.callPackage gammaray' {}; #TODO clarify docs
in {
  inherit gammaray nixGL pkgs;
  integrated =
    if needsGLFix
      then
        pkgs.runCommand "gammaray" { buildInputs = [ pkgs.makeWrapper ]; } ''
          makeWrapper ${nixGL}/bin/nixGLIntel $out/bin/gammaray \
            --add-flags "${gammaray}/bin/gammaray"
          ''
      else
        gammaray;
  }
```

**Comment by deliciouslytyped** [comment]
Actually the only thing I seem to be able to get it to do right now is crash applications, not sure whats up with that...

**Comment by deliciouslytyped** [comment]
The short story seems to be that it's quite sensitive to having the right version of Qt.

**Comment by asdf8dfafjk** [comment]
I need to get gamma ray working. I'm going to proceed with what you posted above (or please post anything newer you have) and if I will post my own progress here, and perhaps a PR if it works well.

**Comment by deliciouslytyped** [comment]
IIRC it should work, but you have to be careful about the Qt versions of things matching up.

**Comment by asdf8dfafjk** [comment]
Thank you for responding. I was able to run a bare GammaRay GUI but then learnt that using it with PyQt apps (what I'm writing now) isn't supported so I'm not going to do anything about this.

**Comment by deliciouslytyped** [comment]
It might not be supported but does it actually not work? :(
I used it with some haskell stuff I wrote, but the internals of that probabyl work very different from the PyQt stuff.

**Comment by asdf8dfafjk** [comment]
I looked again after your comment and now I found github.com/KDAB/GammaRay/issues/515 which says at least 1 person have successfully used GammaRay with Python Qt apps. However, for me, when I launch Gamma ray, it shows other Qt applications but not my (running) PyQt application. I then try to "launch" app by putting Python in the executable field and setting `working directory` and `args` to directory of the python file and the python file itself. At this point the Launch button is greyed out. I didn't investigate further because I read about it not being supported (until your nuanced point made me look again today). 

Thank you for trying to help.

**Comment by deliciouslytyped** [comment]
The most likely issue is a Qt version mismatch.

**Comment by scherzocrk** [comment]
Hi @asdf8dfafjk 
In the end, were you able to use GammaRay with Python Qt apps? I'm facing a similar problem. I'm using PySide2 5.15.2 and I build GammaRay with Qt 5.15.2 as well. I'm facing the same issue, my app is not in the list of Qt apps and launch button is greyed out using python executable and the right args.

**Comment by asdf8dfafjk** [comment]
@scherzocrk No, so ultimately I decided to rewrite it in cpp (python was too slow for me). I remember I read user:deliciouslytyped's useful comment about qt version mismatch but was a bit daunted so I didn't try further.

**Comment by solson** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/221141 & https://github.com/NixOS/nixpkgs/pull/253353, I think.
