### ISSUE TITLE
zsh : promptinit and compinit definition files not found

### ISSUE THREAD

**Issue by MP2E** [NixOS/nixpkgs#5571]
Upon updating to the newest nixpkgs this evening I now receive warnings when I open zsh

```
/etc/zshrc:12: promptinit: function definition file not found
/home/cray/.zshrc:15: compinit: function definition file not found
/home/cray/.zshrc:16: promptinit: function definition file not found
```

Here is my configuration.nix : https://github.com/MP2E/nix-projects/blob/master/nixos-config/configuration.nix

Perhaps related to 766207ca1d52db37df5ca17b9bd3bd21a03dfafd? I'll do some bisecting and report back.

**Comment by jagajaga** [comment]
When I was merging that PR, I've tested it locally and everything was ok...
cc @kirelagin

**Comment by MP2E** [comment]
Hm, confirmed with the bisect. Very strange! I don't see how adding a path could break anything... The change looks good to me.

**Comment by jagajaga** [comment]
Can you post 
echo $FPATH
Before that commit and after?

**Comment by MP2E** [comment]
Before (working):
/usr/local/share/zsh/site-functions:/nix/store/z2acn6qlpjr3jigkgdg4c75b58bmf9n7-zsh-5.0.7/share/zsh/site-functions:/nix/store/z2acn6qlpjr3jigkgdg4c75b58bmf9n7-zsh-5.0.7/share/zsh/5.0.7/functions

After:
/home/cray/.nix-profile/share/zsh/site-functions:/nix/var/nix/profiles/default/share/zsh/site-functions:/run/current-system/sw/share/zsh/site-functions

**Comment by kirelagin** [comment]
Hm, sorry for that, my NixOS box is broken right now, so I couldn’t test the changes thoroughly.

This default value of `$FPATH` gets hardcoded during build of `zsh` (by the way, surprisingly, there is no easy way to get rid of `/usr/local/share/zsh/site-functions`). Of all the default paths only `/nix/store/…-zsh-5.0.7/share/zsh/5.0.7/functions` (which they call `fndir`) is interesting for us, because the other one is already handled by `profileRelativeEnvVars`.

Right now I see two possible solutions (in order of preference):

1. Make `profileRelativeEnvVars` _prepend_ paths. Why does it _overwrite_ the variable, anyway? Is that a feature or a bug? (/cc @oxij @edolstra @nbp).
2. Append this per-zsh-instance path separately during shell initialization.

**Comment by MP2E** [comment]
#1 sounds good to me, I think prepending is better behavior in this case

**Comment by RafalBabinicz** [comment]
Bump.
Today I upgraded to *nixos-15.05pre55818.173f41c* (and after that to *15.05.git.c68ed69M*). Unfortunately, I forgot to check Issues page before that.

This is what I have:

## zsh’s FPATH

[zsh: profile-relative functions path · 766207c · NixOS/nixpkgs · GitHub](https://github.com/NixOS/nixpkgs/commit/766207ca1d52db37df5ca17b9bd3bd21a03dfafd)
gives **'/etc/zshrc:12: promptinit: function definition file not found'**

### Investigating (after reverting 766207c)

    echo $FPATH

    ls /home/kmicu/fpath
    /home/kmicu/fpath:/usr/local/share/zsh/site-functions:/nix/store/m6xrbr4p1nkd9zirdi3gnpjwqmy6yax1-zsh-5.0.7/share/zsh/site-functions:/nix/store/m6xrbr4p1nkd9zirdi3gnpjwqmy6yax1-zsh-5.0.7/share/zsh/5.0.7/functions

Checking each path:

     ls /usr/local/share/zsh/site-functions
gives no such directory.

    ls /nix/store/m6xrbr4p1nkd9zirdi3gnpjwqmy6yax1-zsh-5.0.7/share/zsh/site-functions
gives empty directory.

    ls -all /nix/store/m6xrbr4p1nkd9zirdi3gnpjwqmy6yax1-zsh-5.0.7/share/zsh/5.0.7/functions

gives

    total 5508
    dr-xr-xr-x 1 root root  17412 Jan  1  1970 .
    dr-xr-xr-x 1 root root     40 Jan  1  1970 ..
    -r--r--r-- 1 root root   2809 Jan  1  1970 _a2ps
    -r--r--r-- 1 root root    487 Jan  1  1970 _a2utils
    …
    -r--r--r-- 1 root root   1939 Jan  1  1970 prompt_fire_setup
    -r--r--r-- 1 root root   5942 Jan  1  1970 promptinit
    -r--r--r-- 1 root root   3307 Jan  1  1970 promptnl
    …
    -r--r--r-- 1 root root   6093 Jan  1  1970 _zypper


### Workaround

For now just revert 766207c

    environment.profileRelativeEnvVars =
    { FPATH = [ "/share/zsh/site-functions" ]; };

### Additional info
    nixos-version
    15.05.git.c68ed69M (Dingo)

    zsh --version
    zsh 5.0.7 (x86_64-unknown-linux-gnu)

**Comment by jagajaga** [comment]
@kirelagin @MP2E so reverting for now.

@oxij @edolstra what about the real workaround? https://github.com/NixOS/nixpkgs/issues/5571#issuecomment-68631912 has good suggestions.

**Comment by tomberek** [comment]
For those who might need it:
```
print -r /nix/store/*zsh-5.0.7/share/zsh/5.0.7/functions([-1]) 
```
Should give you a  path to put into a configuration.nix:
```
environment.interactiveShellInit =  ''
export FPATH=/nix/store/LONG HASH-zsh-5.0.7/share/zsh/5.0.7/functions:$FPATH
""
```
`nixos-rebuild switch` and you have a usable system until 766207c is reverted.

**Comment by jagajaga** [comment]
@tomberek https://github.com/NixOS/nixpkgs/commit/4f596fb93fa241444e1299ebdbf5859a2002b71e

**Comment by MP2E** [comment]
This issue has been fixed for me, so I'll close this.

Is there need for a more proper solution? If so comment/reopen
