### ISSUE TITLE
Emacs daemon doesn't see SSH_AUTH_SOCK from gnupg

### ISSUE THREAD

**Issue by shosti** [NixOS/nixpkgs#55733]
## Issue description

Since https://github.com/NixOS/nixpkgs/pull/48772, emacs run through `services.emacs` doesn't see `SSH_AUTH_SOCK` set by `programs.gnupg.agent.enableSSHSupport`. This is problematic because packages like magit will not use the correct SSH agent.

`SSH_AUTH_SOCK` does work correctly in 18.09; this is a regression on `master`.

### Steps to reproduce

1. Put the following in your config:

```
programs.gnupg.agent = {
  enable = true;
  enableSSHSupport = true;
}

services.emacs.enable = true;
```

2. `emacsclient -e '(getenv "SSH_AUTH_SOCK")'`

The result will be `nil`. (Note that if you start `emacs` from a shell and evaluate the above expression, the result will be correct.)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.20, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FlorianFranzen** [comment]
Does ```systemctl --user import-environment SSH_AUTH_SOCK``` help with the issue?

**Comment by shosti** [comment]
The root cause is clear: the above PR swapped `extraInit` with `interactiveShellInit`, which isn’t sourced for systemd daemons. I added the `SSH_AUTH_SOCK` portion to `extraInit` in my configuration.nix, which fixes the issue, but it’s pretty clear to me that `SSH_AUTH_SOCK` should be set in both interactive shells and systemd daemons.

**Comment by shosti** [comment]
PR to fix open at https://github.com/NixOS/nixpkgs/pull/56254, does that seem like a reasonable approach?
