### ISSUE TITLE
systemd/zfs checking was requested for <device>, but it is not a device.

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5574]
I prefer to run warning free systems, so how do I get this out of dmesg? 
```
systemd-fstab-generator[20527]: Checking was requested for "zpool/root/nixos", but it is not a device.
```

**Comment by wizeman** [comment]
Either wait until #5499 gets merged, or if you don't want to wait, you can add the option `noCheck = true` to the respective filesystem, e.g. like this:

```
fileSystems."/nixos".noCheck = true;
```

(if the mountpoint of your `zpool/root/nixos` dataset is not `/nixos`, make sure to use the actual mountpoint).

**Comment by wizeman** [comment]
#5499 has been merged, so I guess this can be closed now.

If you are still seeing this problem, feel free to reopen this issue.
