### ISSUE TITLE
haskellPackages.reflex does not build due to bounds on "these"

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#55758]
## Issue description

nixpkgs currently contains `these-0.7.7` from hackage, which is not out of bounds for `reflex-0.5`.
We would probably need a (tiny) patch for `reflex`, as a jailbreak is not sufficient.
Upstream bug: https://github.com/reflex-frp/reflex/issues/270

### Steps to reproduce

`nix-shell -p haskellPackages.ghcWithPackages(p: [p.reflex])`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0-15-generic, Ubuntu, 18.10 (Cosmic Cuttlefish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(endgame): `"nixpkgs-19.03pre169106.1a88aa9e0cd"`
 - nixpkgs: `/home/endgame/.nix-defexpr/channels/nixpkgs`

**Comment by peti** [comment]
It would be best if upstream could simply release a fixed version of their package.
