### ISSUE TITLE
Pulseaudio option extraModules does not exist

### ISSUE THREAD

**Issue by AlyMoh** [NixOS/nixpkgs#55761]
## Issue description
When trying to add extra modules for Pulseaudio (for aptx support and so on) as described in the manual [here](https://nixos.wiki/wiki/Bluetooth), NixOS complains on `sudo nixos-rebuild switch` that the option `hardware.pulseaudio.extraModules` does not exist.

### Steps to reproduce
Add the option `extraModules` to `hardware.pulseaudio` in `/etc/nixos/configuration.nix` with value `[ pkgs.pulseaudio-modules-bt ]`, then try to rebuild the system using `sudo nixos-rebuild switch` (as described in the manual as well).

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.2137.168cbb39691 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(alymoh): `""`
 - channels(root): `"nixos-18.09.2137.168cbb39691"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Here is the stack trace for when trying to run `sudo nixos-rebuild switch --show-trace`:

building Nix...
building the system configuration...
error: while evaluating the attribute 'config.system.build.toplevel' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:273:5:
while evaluating 'foldr' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:39:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:137:12:
while evaluating 'fold'' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:42:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:46:8:
while evaluating 'showWarnings' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:100:18, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:107:16:
while evaluating 'foldr' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:39:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:100:23:
while evaluating 'fold'' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:42:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:46:8:
while evaluating the attribute 'warnings' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:336:9:
while evaluating the option `warnings':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:232:58:
while evaluating the attribute 'config.warnings' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/systemd.nix:707:5:
while evaluating 'mapAttrsToList' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:224:23, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/systemd.nix:707:29:
while evaluating the attribute 'services' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:336:9:
while evaluating the option `systemd.services':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:349:62:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'enable' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:336:9:
while evaluating the option `services.dbus.enable':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:349:62:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'enable' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:336:9:
while evaluating the option `services.avahi.enable':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:349:62:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:502:14:
while evaluating the attribute 'hardware.pulseaudio' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating 'yieldConfig' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:74:29, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:77:16:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:80:24, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:80:11:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:81:26, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:81:13:
The option `hardware.pulseaudio.extraModules' defined in `/etc/nixos/configuration.nix' does not exist.

**Comment by FlorianFranzen** [comment]
What you are referring is not the manual but the unofficial wiki, which is often out of date. Please file an issue with them instead.

**Comment by AlyMoh** [comment]
> What you are referring is not the manual but the unofficial wiki, which is often out of date. Please file an issue with them instead.

I may be wrong here, but I checked the current `pulseuaudio.nix` file in the GitHub Repo for nixpkgs and an extraModules option has indeed been defined (starting line 157). Regardless whether the wiki (sorry, not manual) is right or wrong, I should still be capable of setting a value for that option, or am I missing something here?

**Comment by eadwu** [comment]
`18.09` is based upon it's own branch, not `master`, namely https://github.com/NixOS/nixpkgs-channels/tree/nixos-18.09. What you want is present in `master` whose channel "equivalent" is the `unstable` series. So to use `hardware.pulseaudio.extraConfig` you would switch to one of the `unstable` channels.

Though if you really prefer the stable channel, you can try disabling the module(s) in `<nixpkgs>` while importing the new ones from your own nixpkgs, though this might not be a plug and play since there might have been other imports needed.

**Comment by AlyMoh** [comment]
> `18.09` is based upon it's own branch, not `master`, you can find it's current status in https://github.com/NixOS/nixpkgs-channels/tree/nixos-18.09. What you want is present in `master` whose channel "equivalent" is the `unstable` series. So to use `hardware.pulseaudio.extraConfig` you would switch to one of the `unstable` channels.
> 
> Though if you really prefer the stable channel, you can try disabling the module(s) in `<nixpkgs>` while importing the new ones from your own nixpkgs, though this might not be a plug and play since there might have been other imports needed.

Ah OK, understood. Thank you so much for the help!

**Comment by taohansen** [comment]
> What you are referring is not the manual but the unofficial wiki, which is often out of date. Please file an issue with them instead.

This feels like passing the buck. People looking to enable these modules are going to end up on that wiki page and they're going to get confused and end up right here just like I did. Why is the wiki unofficial? Maybe stewardship should be offered so two minds can become one.
