### ISSUE TITLE
Error when using resolvectl

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#55765]
## Issue description

```
❯ resolvectl status
Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.
```

Any `resolvectl` produces this error.

### Steps to reproduce

See above.

## Technical details

❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.2127.5225d4bf019 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2137.168cbb39691, nixos-hardware"`
 - channels(asymmetric): `"home-manager-18.09, nixos-unstable-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ck3d** [comment]
I think your resolved is not running and I exspect that following command tells that the unit is not found:
`
sudo systemctl status systemd-resolved
`

If so, the you should set following NixOS option in case you using networkmanager
`
networking.networkmanager.dns = "systemd-resolved";
`
or if not then following option
`
services.resolved.enable = true
`

**Comment by asymmetric** [comment]
Thanks, I'll move this to the forum then as it looks like a local issue.
