### ISSUE TITLE
Fujitsu Touchpad works only while ZFS supported

### ISSUE THREAD

**Issue by haslersn** [NixOS/nixpkgs#55806]
## Issue description

The touchpad on a Fujitsu Lifebook U748 works only with

```
boot.supportedFilesystems = [ "zfs" ];
```

configured.

### Steps to reproduce

* Install NixOS on Fujitsu Lifebook U748
* Be surprised that the touchpad doesn't work
* Add `boot.supportedFilesystems = [ "zfs" ];` to the `configuration.nix`
* Now also add `networking.hostId = lib.mkDefault "8425e349";` because it doesn't build otherwise
* Now it works, but why?

## Technical details: `nix-shell -p nix-info --run "nix-info -m"`

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.2137.168cbb39691 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2137.168cbb39691"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Further remarks
This is *not* a joke.

**Comment by 7c6f434c** [comment]
>* Now also add `networking.hostId = lib.mkDefault "8425e349";` because it doesn't build otherwise
>* Now it works, but why?

>This is *not* a joke.

The first question that comes to my mind — if you keep `hostId` but drop ZFS, does the tuochpad still work?

**Comment by haslersn** [comment]
No, it doesn't

**Comment by 7c6f434c** [comment]
Hm. Could you diff `lsmod` output with and without `zfs` enabled (with no other changes)? Maybe ZFS happens to pull in some driver that helps discovery of the touchpad?

Does loading the extra modules manually (instead of enabling ZFS) help?

(Just in case: I have no idea and no plan, I am just trying to locate the relevant change)

**Comment by haslersn** [comment]
> Could you diff `lsmod` output with and without `zfs` enabled (with no other changes)?
https://gist.github.com/haslersn/9d4054cde7bc59fdc10b422afc938c10

**Comment by 7c6f434c** [comment]
Hmm. I wonder whether adding the ZFS module packages to extra kernel module packages, then loading just icp and spl would help.

Or whether just loading random mainline modules would help — apparently no extra relevant modules are loaded, but maybe there is some timing mechanism…

What `lspci -k` says about the touchpad with/without ZFS?

**Comment by haslersn** [comment]
Update: Even with ZFS support enabled, it *sometimes* doesn't work but then works after rebooting a few times. Without ZFS enabled, it never worked.

I currently don't have time to debug it further.

**Comment by 7c6f434c** [comment]
Thanks for the interesting observation… (stil no idea, obviously)

**Comment by haslersn** [comment]
Closing this now, because I will not reproduce this in the future and don't know anybody else who had this issue.
