### ISSUE TITLE
Gparted unable to locate theme engine adwaita

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55811]
## Issue description

What do I install to get the KDE environment to supply theme data to a GTK app? Ideally would like the GTK app to inherit KDE theme and settings.
```
[root@nixos:/drives]# gparted
Unit tmp.mount does not exist, proceeding anyway.

(gpartedbin:6329): Gtk-WARNING **: 03:01:51.602: Unable to locate theme engine in module_path: "adwaita",

(gpartedbin:6329): Gtk-WARNING **: 03:01:51.605: Unable to locate theme engine in module_path: "adwaita",
======================
libparted : 3.2
======================

** (gpartedbin:6329): WARNING **: 03:02:04.998: Invalid borders specified for theme pixmap:
        /run/current-system/sw/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
borders don't fit within the image
```

## Technical details

```
[root@nixos:/drives]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 18.09.2108.8008d0bbc69 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2108.8008d0bbc69"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
If you have KDE5 enabled, your $HOME/.gtkrc-2.0 should look like this:

```
# Default GTK+ 2 config for NixOS KDE 5
include "/run/current-system/sw/share/themes/Breeze/gtk-2.0/gtkrc"
style "user-font"
{
  font_name="Sans Serif Regular"
}
widget_class "*" style "user-font"
gtk-font-name="Sans Serif Regular 10"
gtk-theme-name="Breeze"
gtk-icon-theme-name="breeze"
gtk-fallback-icon-theme="hicolor"
gtk-cursor-theme-name="breeze_cursors"
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-menu-images=1
gtk-button-images=1
```

This uses breeze which is the default them for KDE. Are you logged in to KDE as root? There could be some issues with doing that.

**Comment by AMDphreak** [comment]
> If you have KDE5 enabled, your $HOME/.gtkrc-2.0 should look like this:
> 
> ```
> # Default GTK+ 2 config for NixOS KDE 5
> include "/run/current-system/sw/share/themes/Breeze/gtk-2.0/gtkrc"
> style "user-font"
> {
>   font_name="Sans Serif Regular"
> }
> widget_class "*" style "user-font"
> gtk-font-name="Sans Serif Regular 10"
> gtk-theme-name="Breeze"
> gtk-icon-theme-name="breeze"
> gtk-fallback-icon-theme="hicolor"
> gtk-cursor-theme-name="breeze_cursors"
> gtk-toolbar-style=GTK_TOOLBAR_ICONS
> gtk-menu-images=1
> gtk-button-images=1
> ```
> 
> This uses breeze which is the default them for KDE. Are you logged in to KDE as root? There could be some issues with doing that.

I'm not logged into KDE as root. I do not have a `.gtkrc-2.0` file. My expectations are probably too high. KDE can't even get their desktop functioning without obvious bugs.

**Comment by jtojnar** [comment]
GParted is GTK 3 now so theme engines are thing of a past.
