### ISSUE TITLE
NixOS base images seem awfully big

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#5581]
The minimal 64-bit 14.12 image on nixos.org is 315 MB. Intuitively (and perhaps naively), it doesn't feel like the minimal one _needs_ to be much larger than the bootstrap-tools.tar.gz (24 MB) that underlies nixpkgs, along with the contents of nixpkgs itself (a few MB) and the nix toolset. Any subsequent needs can be retrieved from the binary cache, I think?

Is there a reason the image is so much larger than that? Is there a breakdown of what eats up most of the space?

I was mostly just taken aback by the size of the Amazon AMIs and Vagrant boxes for NixOS, since it feels like lightweight provisioning of new boxes can be yet another place where NixOS really shines.

**Comment by iElectric** [comment]
List of packages that take the most space: http://i.imgur.com/hLyl7W5.png

**Comment by copumpkin** [comment]
Thanks! It looks like around 115M of that linux package is drivers. I was thinking that NixOS would boot to a minimal state (with almost no interesting drivers) and then `nixos-switch` itself to a reasonably usable state. Not sure how feasible/idealistic that is.

Given an assumed reachable binary cache, it seems like many of those other packages are not essential. Python, gcc, and so on could easily be omitted and retrieved separately when something needed them, right?

**Comment by geerds** [comment]
Python is required to generate boot entries on UEFI/gummiboot machines:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/gummiboot/gummiboot-builder.py

-- 
  Jascha Geerds
  jg@ekby.de

**Comment by offlinehacker** [comment]
Yeah, I have similar issues while woking on service abstraction layer
docker. We should start doing something on reducing the size of the
packages with multiple outputs.

Nixos is currently not best tunned for small space usage. The real question
might be what we, as developers/maintainers, could do to reduce the size of
the packages?

**Comment by iElectric** [comment]
There are currently almost no optimizations (Besides trying to keep the package set minimal). 

What you can disable:

- all hardware switch
- vim
- spidermonkey (probably compiled for javascript support in elinks or w3m)
- python (non-uefi)

You could go one step further and remove all `$out/include`, `$out/share` directories and see if they are needed at all.

See `nixos/modules/profiles/base.nix`

**Comment by edolstra** [comment]
Yeah, multiple outputs will reduce closure sizes a lot. For instance, it will allow us to get rid of most of GCC in the ISO. 

In the meantime, I notice that the linux-dev output is present in the ISO, which should not be the case. Getting rid of it would save 38 MB.

+1 on removing vim, it doesn't sound like something that should be included in a minimal CD. We have nano after all :-)

**Comment by vcunat** [comment]
For reference, this-year multiple-output status & progress: https://gist.github.com/vcunat/6139ee17ae1dec684fd3#comment-1318994. I expect to go back to it this month and hopefully integrate it into master in February.

**Comment by domenkozar** [comment]
We have a separate PR for multiple-outputs now, this can be closed (until we have more ideas what to do)

**Comment by twhitehead** [comment]
Ouch. Somehow, despite multiple output support, this appears to be getting worse... :grimacing: 

* 14.12 - 315 MB minimal image
...
* 20.09 - 571 MB minimal image

**Comment by gytis-ivaskevicius** [comment]
![Screenshot_20230224-130500.jpg](https://user-images.githubusercontent.com/23264966/221163841-d6f4d1af-5490-4127-92c5-a39f71fe0e9f.jpg)

This issue did not age well 😅
