### ISSUE TITLE
Regression caused by "xorg-server: enable DRI3 (close #5381)"

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#5583]
Tonight I git bisected, on branch release-14.12, an issue that turned
out to be caused by commit 9ec8d3e0ac978b4a69570cc395c9e979d10770b8
("xorg-server: enable DRI3 (close #5381)").

Input from the keyboard (and mouse wheel) seem "delayed" somehow. It
affects the GUI terminals; I tested 'gnome-terminal' and 'terminator'. The
virtual consoles (ctrl-alt-f1 etc.) are not affected. Neither are GUI
programs. I tested both chromium and gedit and they both receive input
characters without any "delays".

The delays hold back input characters a little, making them first appear
either after an idle time of about 1 second, or that another input
character "pushes through the pipe".

It seems that the delay is based on a window of two characters; the
first character typed is delayed for up to 1 sec, but the next one is
immediately displayed. So char N is delayed, N+1 is immediate. And N+1
possibly brings with it the previous character, if it wasn't already
shown.

Continuously holding down a key, I notice that updates come in groups of
two, instead of normal continuous flow of (single) chars.

This happens on both my machines, which both have Intel graphics.

While bisecting, I also tested with "nixos-rebuild build-vm". The issue is not reproducible in the VM, making it clear to me that this has something to do with (Intel?) hardware. (I run GNOME 3 desktop if that matters.)

Does anyone else have this issue?

PS: A small  input delay like this may seem insignificant, but believe me, it makes working on the terminal a real pain :-)

**Comment by wizeman** [comment]
When you experience those issues, does `dmsg` show anything afterwards? Alternatively, does `journalctl -u display-manager-start -b` show anything strange?

I experienced somewhat similar issues on #5272.

**Comment by bjornfor** [comment]
Nothing special in dmesg.

But ```sudo journalctl -u display-manager -b``` contained interesting info. (Thanks for the tip!)

Booting good config gives something like this:

```
[snipped]
(++) Using config file: "/nix/store/6vi4p15aabkj5vlwcjz3i543yxcrc7mw-xserver.conf"
(==) Using system config directory "/nix/store/8wwsjly5ydfc10c8y90nnzllskdy6jag-xorg-server-1.16.2.901/share/X11/xorg.conf.d"
(==) ServerLayout "Layout[all]"
(**) |-->Screen "Screen-ati[0]" (0)
(**) |   |-->Monitor "<default monitor>"
(**) |   |-->Device "Device-ati[0]"
[snipped lots more info]
```

But a bad one:

```
[snipped]
(++) Using config file: "/nix/store/4an3iyh95nwzi6p550aavv0s4y94pd3v-xserver.conf"
(==) Using system config directory "/nix/store/v0ic3nz2qkz30pgcllrgdrb4hrk05vs5-xorg-server-1.16.2.901/share/X11/xorg.conf.d"
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
[THE END]
```

**Comment by bjornfor** [comment]
Reverting that commit doesn't change the display-manager log (still has that XKEYBOARD warning). (Weird, I thought I had checked that while git bisecting...)

Also, just now I had fully responsive terminal but lagging keyboard in put in gedit. Which is opposite to what I experienced when bisecting. I really don't see the pattern here :-/  I'm wondering whether the issue may come and go also _while_ the computer is running...

I will run my system with the commit reverted for a while and see if the keyboard input latency is stable (over time).

**Comment by bjornfor** [comment]
It seems to be fixed in master. Still an issue on release-14.12 though.

**Comment by vcunat** [comment]
Maybe there has been some maintenance bump that fixes the problem, but if it's difficult to reproduce reliable, it won't be easy to find which one. We/I could try picking all xorg minor bumps, which should be relatively safe, I hope.

**Comment by bjornfor** [comment]
If you can pick some maintenance bumps into release-14.12, that's be great! I can also try some bisecting on master.

I see in my comment above, https://github.com/NixOS/nixpkgs/issues/5583#issuecomment-70321666, that I said it wasn't deterministic. But since then, it's been consistently broken, as far as I've noticed. I don't know what happened back then.

**Comment by bjornfor** [comment]
@vcunat: Thanks! I've been bisecting since yesterday, but it was going really slow. Had to backport some patches and rebuilding from source is sloooow. I'll test latest release-14.12 with your bumps before doing more bisecting.

**Comment by bjornfor** [comment]
@vcunat: Hurray! Now the issue is gone! Thanks!

**Comment by vcunat** [comment]
:-) I've been lax &ndash; most of my (non-security) maintenance updates weren't picked to release.
