### ISSUE TITLE
darcs build broken by sandi update

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#55840]
`darcs` no longer compiles in Nixpkgs `master`, because the package set has updated to the latest version of `sandi`. The package is now at 0.5, but `darcs` supports only 0.4.x: https://hydra.nixos.org/job/nixpkgs/haskell-updates/darcs.x86_64-linux.

@hsenag, is there any chance that simply relaxing the constraint in `darcs`'s Cabal file solves this issue?

**Comment by hsenag** [comment]
Yes, looks like it's fine. I've bumped the dependency on hackage.

**Comment by peti** [comment]
`darcs` build is fixed: https://hydra.nixos.org/job/nixpkgs/haskell-updates/darcs.x86_64-linux. Thank you very much.
