### ISSUE TITLE
can't use `encoding-io` in `ghcWithPackages`

### ISSUE THREAD

**Issue by samuelrivas** [NixOS/nixpkgs#55854]
## Issue description

the version of `encoding-io` available in `nixpkgs` seems to depend on an outdated version of `base`

### Steps to reproduce
For example:

    nix-shell -p "pkgs.haskell.packages.ghc862.ghcWithPackages (pkgs: [pkgs.encoding-io])"

This will eventually fail with

```
[...]
Setup: Encountered missing dependencies:
base >=4.8 && <4.10

builder for '/nix/store/b6p75ns9ympbfr2bcrmwqp992ji5ibzz-encoding-io-0.0.1.drv' failed with exit code 1
cannot build derivation '/nix/store/91x0ydjj4zjf39x2wr73c4zacga6jcvg-ghc-8.4.3-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/91x0ydjj4zjf39x2wr73c4zacga6jcvg-ghc-8.4.3-with-packages.drv' failed
```
## Technical details

I found this to work with `ghc802`, I haven't tried extensively, but all more modern versions of GHC that I have tried failed with the same issue

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 18.09.1363.b37872d4268 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(samuel): `""`
 - channels(root): `"nixos-18.09.1363.b37872d4268"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by xaverdh** [comment]
Jailbreaking, i.e.
`nix-shell -p "haskell.packages.ghc863.ghcWithPackages (ps: with ps; [ (haskell.lib.doJailbreak encoding-io) ])"`
works for me.

The code probably works, but doesn't look like its actively maintained.
Still you can try file an [upstream](https://github.com/TerrorJack/encoding-io) issue.

**Comment by xaverdh** [comment]
Well its quite a large package set, so its quite hard to guarantee that _every_ package will build.
@peti can you give a more satisfactory answer?
Also there is a list of [workarounds](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix), if it matters to you, you can add it there I guess.

**Comment by peti** [comment]
The upstream package does not support building with ghc-8.6.x. Therefore, I don't think one can reasonably expect it to build with ghc-8.6.x in Nixpkgs. That's not Nixpkgs responsibility. This issue should be fixed by upstream.

**Comment by samuelrivas** [comment]
Sure, but my question is what could I expect from `nixpkgs`. That I get  a `haskellPackages` with things that don't build is a bit surprising to me, compared to, for example, finding out that `encoding-io` is not part of `haskellPackages` any longer because it doesn't build (which is what *I* was kind of expecting)

Don't take this as criticism, I am just trying to understand what is fair to assume.

**Comment by peti** [comment]
For every package `foo` on Hackage, you can expect `haskellPackages.foo` to exist. You have a pretty good chance that it will build if the upstream package builds, too, but you cannot expect that.

**Comment by samuelrivas** [comment]
Ok, thanks. It seems I got my assumptions reversed then :)

For what is worth, I opened an issue upstream, but there is a good chance that this project is not actively maintained. It is very little code though, so is probably not a major disaster if it is not fixed...

**Comment by peti** [comment]
OK. :-)
