### ISSUE TITLE
all-packages.nix has an invalid kde declaration. Broke nix-env -qa.

### ISSUE THREAD

**Issue by lfont** [NixOS/nixpkgs#5589]
Ubuntu 14.04
Nix 1.8
nixpkgs-unstable (14.12 seems to have the same issue).

`nix-env -qa`
*error: attribute ‘rekonq’ missing, at "/nix/store/i99ncvcy3p4awz7b0m35gcknkizzrpag-nixpkgs-15.05pre55083.597373b/nixpkgs/pkgs/top-level/all-packages.nix":12861:15*

The problem is that rekonq is not found in kde4.

I can get `nix-env -qa` to work by explicitly use kde414 (I almost be sure that this is not the good way of doing it but I'm new to nix):
`rekonqWrapper = wrapFirefox {
  browser = kde414.rekonq; browserName = "rekonq"; desktopName = "Rekonq";
};`

Now I can list some packages but all kde packages are missing.
`nix-env -qa 'kde.*'`
*error: selector 'kde.*' matches no derivations*

The definition of kde4 in all-packages.nix does not work.

**Comment by vcunat** [comment]
I'm unable to reproduce any of the problems on 14.12, master, or that particular 597373b version. I wonder what's different.

**Comment by lfont** [comment]
Hum, I'm sorry but this is not a bug.
I used a stupid *packageOverrides* in my *~/.nixpkgs/config.nix* that broke the kde definition.
