### ISSUE TITLE
qt5.full package not installable on macOS due to dependency on bluez by qtconnectivity

### ISSUE THREAD

**Issue by pedropombeiro** [NixOS/nixpkgs#55892]
Just getting started with nix, and came across a problem installing `qt5.full` on macOS, caused by this line:

https://github.com/NixOS/nixpkgs/blob/6dce69e47536568700951a71e417a9c93f8c9448/pkgs/development/libraries/qt-5/modules/qtconnectivity.nix#L6

This problem was already mentioned in https://github.com/NixOS/nixpkgs/issues/52434, but that issue was closed without the underlying problem being fixed. I believe that if `qt5.full` is marked as installable on macOS then it should be able to complete installation and not depend on any Linux-only packages.

**Comment by veprbl** [comment]
The issue as described here was resolved. However, `qtwebkit` and `qtwebengine` are broken, so `qt5.full` remains unavailable on darwin.

**Comment by wegank** [comment]
#183383
