### ISSUE TITLE
iOS building is broken

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#55917]
## Issue description

Our cctools don’t support the tbd files in the recent sdks. This commit needs to be reverted:

https://github.com/NixOS/nixpkgs/commit/ac682e362c07929b2b30bfdf4f75cd1c5250d3e7#diff-2d184a749b2f39281af10a27f385264f

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by arximboldi** [comment]
```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(raskolnikov): `"darwin, nixpkgs-22.05pre374749.abfd3117917"`
 - nixpkgs: `/Users/raskolnikov/.nix-defexpr/channels/nixpkgs`
```
