### ISSUE TITLE
Curated package collections, called "channels"

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55924]
### Basis

I want to install a set of items that are commonly installed on KDE desktop environments, such as a calculator, text editor, and more. Typically, the user agrees to this set of software when they choose their distribution. In a sense, distributions are just curated collections of software. This should actually be done on top of a base system (NixOS/Archlinux/etc), and users should not need to change distros just to get a system that is optimized for Digital Audio production or Video production or Office Workstation use or a Server environment.

### Idea

Software packages that make sense together should be offered in curated "streams" or "channels". Yes, I know "channels" currently means something different. The current concept of software channels should be renamed to "software sources" (aka "repositories").

#### Isn't this the same as a meta-package? Why or why not?
The current meaning of "meta-packages" is similar to what the new "channels" means. "Channels" borrows the nomenclature from popular software and services like music websites and video websites that users are familiar with. Similar to those services, when you tune into these software channels, you will be subject to the curator's choices about what is appropriate and what makes sense together. This requires a distinction between basic meta-packages and the new idea of channels. The software in a basic meta-package is whatever is dictated by the project's developers and what they choose to release as a complete project. On the other hand, channels contain packages that depend on each other for an overall subjective experience for the end-user.

#### Browsing channels
Channels should be listed and browsed separately from the basic packages. These are completely different things with different purposes. Do not mix them together.

#### Why is this NixOS's problem and not KDE's or GNOME's?
In a sense, these "channels" should be a feature within the Desktop Environment itself, but it has to be implemented at the level of the package manager, so the KDE/GNOME developers will never be able to implement this themselves.

**Comment by matthewbauer** [comment]
We have something called profiles in nixos that do basically what you are describing. They are just base configurations that you can build on top of. This is much more powerful than metapackages as they can also include configuration as well. We don’t have quite as opinionated as you are describing but it should be possible.

I have thought for a while that we may need a polished desktop oriented distro built on top of NixOS similar to how Manjaro builds on Arch Linux. Haven’t had time to figure it out but it shouldn’t be much harder than writing a really good NixOS configuration.

**Comment by 7c6f434c** [comment]
>I have thought for a while that we may need a polished desktop oriented distro built on top of NixOS similar to how Manjaro builds on Arch Linux. Haven’t had time to figure it out but it shouldn’t be much harder than writing a really good NixOS configuration.

It might still be — it includes not only writing a good configuration, but also picking the better one out of alternative options, repeatedly and consistently… It is easier, say, to write a good `nvidia`-based or `nouveau`-based configuration, given some known priorities, than to decide in advance which of these paths to take (better multi-monitor support or less fuss from Chomium?)

Maybe the reason there are such polished spinoffs is that the polished versions compromise desirable technical qualities that always happen to be important to people who work on packaging the core.

**Comment by AMDphreak** [comment]
> We have something called profiles in nixos that do basically what you are describing. They are just base configurations that you can build on top of. This is much more powerful than metapackages as they can also include configuration as well. We don’t have quite as opinionated as you are describing but it should be possible.

This is funny. I almost called them that as well, but the channel metaphor came to mind first. How come these profiles are not alluded to in the NixOS Manual? This seems a pretty key concept in setting up the system.

> I have thought for a while that we may need a polished desktop oriented distro built on top of NixOS similar to how Manjaro builds on Arch Linux. Haven’t had time to figure it out but it shouldn’t be much harder than writing a really good NixOS configuration.

Yes. Yes, there needs to be an easier way to get from zero to desktop. However, if you're thinking of imitating the Archlinux/Manjaro split (not saying you are, since it isn't clear), I'd advise against it. It is bad to pollute the global namespace of OS's and particularly Linux distributions. It is already a headache trying to orient oneself in the Linux world with all these distro variants out there that are largely duplicative but *could be* completely different under the hood or *could be* just the same with a few odd tweaks but feel entirely different, and *could* have their own idiosyncratic way of managing x or y, meaning that whatever tutorial or Q/A website you found on the internet *could be* partially or entirely wrong. Giving people too many things to think about and compare, and splitting their attention and efforts is a huge problem with Linux. I call it ***distro-itis***. Users will constantly have to think "what's the difference between x and y", and it'll generate a whole slew of duplicate and disorganized questions on help forums.

**Comment by vcunat** [comment]
> How come these profiles are not alluded to in the NixOS Manual?

It's just [NixOS modules](https://nixos.org/nixos/manual/#sec-modularity).  You can use them to add whatever config or packages you like.  We have [a few](https://github.com/nixos/nixpkgs/tree/master/nixos/modules/profiles) of these kinds called "profiles", but it isn't really used much.

I think it would be nice to have a structured library of ready profiles for most common use cases.

**Comment by 7c6f434c** [comment]
>Yes. Yes, there needs to be an easier way to get from zero to desktop. However, if you're thinking of imitating the Archlinux/Manjaro split (not saying you are, since it isn't clear), I'd advise against it. It is bad to pollute the global namespace of OS's and particularly Linux distributions.

I think it only pollutes the global namespace if the name is too different; Ubuntu's larger spinoffs seem to be quite easy to identify.

(and yes, there will be differences under the hood between «Gnomish NixOS» and mainline NixOS with Gnome installed in the natural way, that's unlikely to be avoidable)

**Comment by suhr** [comment]
This reminds me of [Funtoo profile system](https://www.funtoo.org/Funtoo_Profiles).
