### ISSUE TITLE
GNOME 3 needs boltd for Thunderbolt 3 support

### ISSUE THREAD

**Issue by callahad** [NixOS/nixpkgs#55938]
## Issue description

As described in [this blog post](https://christian.kellner.me/2017/12/14/introducing-bolt-thunderbolt-3-security-levels-for-gnulinux/), GNOME 3 needs the [bolt daemon](https://gitlab.freedesktop.org/bolt/bolt) to handle authenticating Thunderbolt 3 devices.

This is not yet packaged for NixOS.

I've [attempted to package](https://gist.github.com/callahad/c9808a9bb85d8dcc0338d93eeef0bae0) bolt myself but have thus far been unsuccessful.

### Steps to reproduce

- Start a Gnome 3 session
- Navigate to Settings → Devices → Thunderbolt

__Expected Results:__ A nice GUI as [described here](https://christian.kellner.me/2018/04/23/the-state-of-thunderbolt-3-in-fedora-28/).

__Actual Results:__ An error message:

![screenshot of the error message transcribed below](https://user-images.githubusercontent.com/24193/52911932-4a0d7f00-32a2-11e9-99ae-f9fe9409dc6d.png)

> No Thunderbolt support
>
> Thunderbolt could not be detected.
> Either the system lacks Thunderbolt support, it has been disabled in the BIOS, or is set to an unsupported security level in the BIOS.

(Note: The error message is slightly misleading. Thunderbolt 3 *is* supported and working on my laptop, albeit with authorization disabled, but without `bolt` GNOME doesn't know that.)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.7, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Can you share the errors you have encountered when packaging? Perhaps we can point you to solution.

**Comment by callahad** [comment]
Right now I'm hitting two roadblocks with bolt itself:

1. Building the man pages fails somewhere inside asciidoc:

```
[21/94] Generating boltctl-man with a custom command.
FAILED: boltctl.1
/nix/store/nh2pywspgv2m7sn9c8nhjb59rs31x0pm-asciidoc-8.6.9/bin/a2x -d manpage -f manpage -D . -a 'manmanual=bolt Manual' -a mansource=bolt -a revnumber=0.7 ../docs/boltctl.1.txt
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xmllint" --nonet --noout --valid "/build/source/build/boltctl.1.xml" returned non-zero exit status 4
```

I'm not sure how to get more information / further work on that.

2. If I disable manpage generation (`mesonFlags = [ "-Dman=false" ]`), everything compiles and links just fine but then fails with:

```
[91/92] Linking target test-udev.
[92/92] Linking target test-sysfs.
glibPreInstallPhase
glibPreInstallPhase
installing
install flags: install
[0/1] Installing files.
pkexec must be setuid root
FAILED: meson-install
/nix/store/y6jq0jwxhzjackxp6bsyh93v9s6bnpa6-meson-0.49.0/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
builder for '/nix/store/clxfzrq236dw0sqc6imvn0lqmpbyzcfb-bolt-0.7.drv' failed with exit code 1
error: build of '/nix/store/clxfzrq236dw0sqc6imvn0lqmpbyzcfb-bolt-0.7.drv' failed
```

**Comment by hedning** [comment]
Yeah, meson sometimes gives incredibly useless error messages. The problem is the build trying to install files in `${udev}` and `${systemd}`, which it looks up through pkgconfig. Adding these fixes these:
```
  PKG_CONFIG_SYSTEMD_SYSTEMDSYSTEMUNITDIR = "${placeholder "out"}/lib/systemd/user";
  PKG_CONFIG_UDEV_UDEVDIR = "${placeholder "out"}/lib/udev";
```

We'll also need to knock out `scripts/meson-install.sh` as it tries to create a directory in `/var`.

This fixed the build for me:
```nix
  postPatch = ''
    echo '#!/bin/sh' > scripts/meson-install.sh
    patchShebangs tests/test-integration scripts/meson-install.sh
  '';

  PKG_CONFIG_SYSTEMD_SYSTEMDSYSTEMUNITDIR = "${placeholder "out"}/lib/systemd/user";
  PKG_CONFIG_UDEV_UDEVDIR = "${placeholder "out"}/lib/udev";

```

**Comment by jtojnar** [comment]
You can try to add `--verbose` flag to the asciidoc command in the meson file (I recommend setting `src` to the local checkout of the project in question).

As for the second error, Meson only calls `pkexec` when it fails to write to install destination, which means that some `install_dir` is probably wrong.

**Comment by jtojnar** [comment]
There ought to be a message https://github.com/mesonbuild/meson/blob/da34bea893b3b309800e0f03021a99ee58c599d6/mesonbuild/minstall.py#L353
Perhaps you can find it in build directory  under `build/meson-logs` if you run `nix-build` with `-K`.

**Comment by callahad** [comment]
Woohoo!

![screenshot from 2019-02-18 11-56-36](https://user-images.githubusercontent.com/24193/52949513-62e66500-3374-11e9-9a54-5c5a3c9c049a.png)

Now I just have to:
1. Clean things up
2. Figure out how to get the systemd unit file linked
3. Figure out how to properly test a patch against this repo
4. Pull request!

**Comment by hedning** [comment]
> Figure out how to get the systemd unit file linked

We'll have to make module, something like this:

https://github.com/NixOS/nixpkgs/blob/107215c1d0cf485de1e15b58404e732e9e58148a/nixos/modules/services/desktops/gnome3/evolution-data-server.nix#L35

Will probably need `services.udev.packages = [ pkgs.bolt ];` too.
