### ISSUE TITLE
Games don't work on sway-beta

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#55932]
## Issue description

Don't know whether this is a sway issue or packaging issue. Starting from nixpkgs.

Games work on sway 0.15.2 but not on sway-beta 1.0-rc2

cc @primeos

### Steps to reproduce

`nix run nixpkgs.extremetuxracer -c etr`

```
----------- Extreme Tux Racer 0.7.5 ----------------
----------- (C) 2010-2018 Extreme Tuxracer Team  --------

The requested video mode is not available, switching to a valid mode
fish: 'nix run nixpkgs.extremetuxracer…' terminated by signal SIGSEGV (Address boundary error)
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.20, NixOS, 19.03.git.36f3160 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(gnidorah): `""`
 - channels(root): `"nixos-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by primeos** [comment]
Hm, strange, it works on my system with both `nix-shell` and `nix run` and I've also tested it on 36f316007494c388df1fec434c1e658542e3c3cc.

I guess it either depends on other NixOS configuration settings, environment variables or the hardware.
Have you tried running `strace etr`? Maybe that outputs something useful.

**Comment by gnidorah** [comment]
@primeos Issue fixed after I've added a line describing external monitor configuration:
```
-output eDP-1 pos 1920,0 res 1920x1080 scale 1.5
+output HDMI-A-2 pos 0 0 res 1920x1200
+output eDP1 pos 1920 0 res 1920x1080 scale 1.5
```
