### ISSUE TITLE
Python: support for PEP 517 (`build-backend` in `pyproject.toml`)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#55961]
## Issue description

[PEP 518](https://www.python.org/dev/peps/pep-0518/) introduces the `pyproject.toml` format for specifying minimum build system requirements, specifically, it introduces a common interface for declaring dependencies of a build system. [PEP 517](https://www.python.org/dev/peps/pep-0517/) introduces a field specifying how said build system is invoked. `pip` now supports PEP 517 and 518  and will, when a `pyproject.toml` with the required keys are present, invoke the build using this method, and otherwise fall back to `distutils`/`setuptools`.

Because this is the new standard, we need to adapt our builder, `buildPythonPackage`. Currently, this function can handle three "formats", `setuptools` (default), `flit`, and `wheel`. We now need to add support for `pyproject`, and aim at making it the default. To not break 2500 derivations, we will continue assuming `setuptools` is present. Long-term it should become an explicit native build input so we can drop support for `setuptools` as `format`.. Support for `flit` as `format` can be dropped almost immediately because very few packages use it.

### Split building from installing? (out of scope)

Why not have one function for building a wheel, and another for installing it and testing the installation? This would be nice, but likely requires quite some duplication when writing expressions.

```nix

buildPythonPackage rec {

  wheel = buildWheel {
    src = fetchPypi {
      pname = "foo";
      version = "1.2.3";
      sha256 = "acdefg";
      meta.license = lib.maintainers.mit;
    };
    nativeBuildInputs = [ setuptools wheel ];
  };
  installInputs = [ pandas traceback2 ];

  meta.maintainer = lib.maintainers.fridh;  
}
```

### Generating Nix expressions (out of scope)

...

**Comment by lheckemann** [comment]
Do you think this will be ready for the branch-off next Monday?

**Comment by FRidh** [comment]
Initial support, yes. But I won't change the default yet.

**Comment by FRidh** [comment]
Just pushed this to `staging-next` (could have gone to master as well because it's actually not yet used)

**Comment by FRidh** [comment]
In 19.09 this will likely become the default.
