### ISSUE TITLE
Instructions for local haskell packages don't seem to work

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#55969]
I wanted to modify a couple of hackage packages, `hsqml`, and `hsqml-demo-morris` which depends on `hsqml`.

I took a copy of the sources, made my modifications and followed the instructions in [the docs](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.section.md#how-to-create-nix-builds-for-your-own-private-haskell-packages) to create `default.nix`, `shell.nix` and `hsqml.nix` in `/path/to/local/HsQML`. and `default.nix`, `shell.nix` and `hsqml-demo-morris.nix` in `/path/to/local/hsqml-demo-morris`. I also created `~/.config/nixpkgs/config.nix` as described in the docs. The only changes I made were to replace the example package names `foo` and `bar` with `hsqml` and `hsqml-demo-morris`, and to replace `ghc7102` with `ghc863`.

If I run `nix build nixpkgs.haskellPackages.hsqml`, the override appears to work: It builds the local HsQML sources.

However, if I run `nix build nixpkgs.haskellPackages.hsqml-demo-morris`, it tries to satisfy the `hsqml` dependency by building `hsqml` from nixpkgs, ignoring the override in `~/.config/nixpkgs/config.nix`.

(A simple example modification is to change the HsQML version in the local sources, so that it's obvious which sources nix is building)

I don't know why it isn't working, so I can't say whether the docs are incorrect / outdated, or whether the docs are correct and the override is broken.

Results of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"aarch64-linux"`
 - host os: `Linux 3.10.104, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - nixpkgs: `/home/thrall/nixpkgs`

**Comment by xaverdh** [comment]
Can you post the precise nix expressions that you have?

**Comment by Thra11** [comment]
Fetch HsQML and hsqml-demo-morris sources:
`darcs get https://hub.darcs.net/komadori/HsQML`
`darcs get https://hub.darcs.net/komadori/hsqml-demo-morris`
Edit `~/HsQML/hsqml.cabal` to change the version from 0.3.5.1 to 0.3.5.2 (So we can tell which sources it's building)
Additional files in `~/HsQML`:
default.nix:
```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc863" }:
nixpkgs.pkgs.haskell.packages.${compiler}.callPackage ./hsqml.nix { }
```
hsqml.nix (generated by cabal2nix):
```
{ mkDerivation, base, c2hs, Cabal, containers, directory, filepath
, qt5, mesa, QuickCheck, stdenv, tagged, template-haskell, text
, transformers
}:
mkDerivation {
  pname = "hsqml";
  version = "0.3.5.2";
  src = ./.;
  setupHaskellDepends = [ base Cabal filepath template-haskell ];
  libraryHaskellDepends = [
    base containers filepath tagged text transformers
  ];
  libraryPkgconfigDepends = [ qt5 mesa ];
  libraryToolDepends = [ c2hs ];
  testHaskellDepends = [
    base containers directory QuickCheck tagged text
  ];
  doCheck = false;
  homepage = "http://www.gekkou.co.uk/software/hsqml/";
  description = "Haskell binding for Qt Quick";
  license = stdenv.lib.licenses.bsd3;
}
```
shell.nix:
```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc863" }:
(import ./default.nix { inherit nixpkgs compiler; }).env
```

Additional files in `~/hsqml-demo-morris`:
default.nix:
```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc863" }:
nixpkgs.pkgs.haskell.packages.${compiler}.callPackage ./hsqml-demo-morris.nix { }
```
hsqml-demo-morris.nix (generated by cabal2nix):
```
{ mkDerivation, base, containers, deepseq, directory, hsqml
, OddWord, stdenv, text
}:
mkDerivation {
  pname = "hsqml-demo-morris";
  version = "0.3.1.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  enableSeparateDataOutput = true;
  executableHaskellDepends = [
    base containers deepseq directory hsqml OddWord text
  ];
  homepage = "http://www.gekkou.co.uk/software/hsqml/";
  description = "HsQML-based implementation of Nine Men's Morris";
  license = stdenv.lib.licenses.bsd3;
}
```
shell.nix:
```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc863" }:
(import ./default.nix { inherit nixpkgs compiler; }).env
```

Finally, `~/.config/nixpkgs/config.nix`:
```
{
  packageOverrides = super: let self = super.pkgs; in
  {
    haskellPackages = super.haskellPackages.override {
      overrides = self: super: {
        hsqml = self.callPackage ~/HsQML { qt5 = super.qt5Full; };
        hsqml-demo-morris = self.callPackage ~/hsqml-demo-morris {};
      };
    };
  };
}
```

**Comment by Thra11** [comment]
Revisiting this, I think it might be something to do with how the command is told about nixpkgs. The docs don't mention `nix build` at all, only `nix-build` and `nix-shell`. I think `nix build` is getting nixpkgs from the environment variable, NIX_PATH.

These work:
```
nix-build "<nixpkgs>" -A haskellPackages.hsqml-demo-morris
nix-shell "<nixpkgs>" -A haskellPackages.hsqml-demo-morris.env
```

Bizarrely, after running those successfully, `nix build nixpkgs.haskellPackages.hsqml-demo-morris` starts working as well. I have no idea what's going on anymore.

**Comment by Anton-Latukha** [comment]
`nix build` still very WIP MVP, and for today not really replacing `nix-build`, or in nearest time for the majority.

Also it has puzzling CLI: https://youtu.be/XVIKScU7Uf4?t=417

No wonder you confused by `nix-build` and `nix build`. It is also logical that latter is a successor. And it is a successor, but WIP. In Nix world it is a definitive tendency (was a really strong trend) to shadow and overload everything. There were such old contributors that overloaded everything with everything other. In `nixpkgs` I consider that rewriting a very bad code style, but in tooling, it is much more understandable. Thou that feature probably should had some 0.x version, `new-*` addition, like done in Cabal, or was done in Docker long ago, or WIP or beta mark somewhere, at least inside `--help`.
Because `nix build --help` not helping with information me also.

You are right that `nix build` mainly designed with `NIX_PATH` in mind. At least it is how I would use it, `env ... nix build ...`.
