### ISSUE TITLE
ethereum parity is too old to sync

### ISSUE THREAD

**Issue by thedavidmeister** [NixOS/nixpkgs#55984]
## Issue description

current stable version of parity is `2.2.10-stable`

https://github.com/paritytech/parity-ethereum/releases

current version in nix pkgs as `altcoins.parity` is `1.11.8`

this version is so old that running `parity --no-warp` dies around block `7079993` and cannot validate (at least i _hope_ that is why it cannot validate)

i see a lot of debug output, but this seems relevant as some Rust debug output:

```
2019-02-18 14:48:50  Stage 3 block verification failed for #7080000 (0x30f1…ebc9)
Error: Error(Block(InvalidDifficulty(Mismatch { expected: 2584251159642656, found: 2584526037287456 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2019-02-18 14:48:50  
Bad block detected: Error(Block(InvalidDifficulty(Mismatch { expected: 2584251159642656, found: 2584526037287456 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

### Steps to reproduce

- `nix-shell -p parity --run 'parity --no-warp'`
- wait...
- see the error validating blocks ~7079993

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
[thedavidmeister@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.7, NixOS, 19.03pre161883.e85c1f58680 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre165037.eebd1a92637, nixpkgs-19.03pre160749.3a393eecafb"`
 - channels(thedavidmeister): `"nixos-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by asymmetric** [comment]
@thedavidmeister the version has been updated in the upcoming [19.03 release](https://github.com/NixOS/nixpkgs/tree/release-19.03/pkgs/applications/altcoins/parity).

I think this can be closed?

**Comment by thedavidmeister** [comment]
yes, i am syncing again by updating to latest unstable
