### ISSUE TITLE
cabal-install can't find ar

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#55995]
## Issue description

The cabal-install binary calls out to the ar archive tool, which it can't find.

### Steps to reproduce

For example when building unordered-containers-0.2.10.0
`cabal get unordered-containers-0.2.10.0; cd unordered-containers-0.2.10.0; cabal new-build`
cabal emits the error
`cabal: The program 'ar' is required but it could not be found.`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.7, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre169108.36f31600749"`
 - channels(pantarhei): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by chrissound** [comment]
I just ran into this error but when rerunning `nix-build` the error seems to have gone away?

```
Loading cabal v2-repl app ...
Resolving dependencies...
Build profile: -w ghc-8.6.3 -O1
In order, the following will be built (use -v for more details):
 - split-0.2.3.3 (lib) (requires download & build)
 - utf8-string-1.0.1.1 (lib:utf8-string) (requires download & build)
 - string-conversions-0.4.0.1 (lib) (requires download & build)
 - niobiumcoconut-0.1.0.0 (exe:app) (first run)
Downloading  split-0.2.3.3
Downloaded   split-0.2.3.3
Downloading  utf8-string-1.0.1.1
Starting     split-0.2.3.3 (lib)
Building     split-0.2.3.3 (lib)
Downloaded   utf8-string-1.0.1.1
Downloading  string-conversions-0.4.0.1
Starting     utf8-string-1.0.1.1 (all, legacy fallback)
Building     utf8-string-1.0.1.1 (all, legacy fallback)
Downloaded   string-conversions-0.4.0.1

Failed to build split-0.2.3.3.
Build log (
/home/chris/.cabal/logs/ghc-8.6.3/split-0.2.3.3-54503dcc4a22b92dd63f5943f28c98238757ac8e59e0ecdb9e993b8a4c8ff567.log
):
Configuring library for split-0.2.3.3..
Preprocessing library for split-0.2.3.3..
Building library for split-0.2.3.3..
[1 of 2] Compiling Data.List.Split.Internals ( src/Data/List/Split/Internals.hs, dist/build/Data/List/Split/Internals.o )
[2 of 2] Compiling Data.List.Split  ( src/Data/List/Split.hs, dist/build/Data/List/Split.o )
cabal: The program 'ar' is required but it could not be found.


Failed to build utf8-string-1.0.1.1.
Build log (
/home/chris/.cabal/logs/ghc-8.6.3/utf8-string-1.0.1.1-16682a11f7e38fa4563b198e014b20fbc7e4c60dd5cd0ece6709ec5d27952a81.log
):
Configuring utf8-string-1.0.1.1...
Preprocessing library for utf8-string-1.0.1.1..
Building library for utf8-string-1.0.1.1..
[1 of 5] Compiling Codec.Binary.UTF8.String ( Codec/Binary/UTF8/String.hs, dist/build/Codec/Binary/UTF8/String.o )
[2 of 5] Compiling Codec.Binary.UTF8.Generic ( Codec/Binary/UTF8/Generic.hs, dist/build/Codec/Binary/UTF8/Generic.o )
[3 of 5] Compiling Data.ByteString.Lazy.UTF8 ( Data/ByteString/Lazy/UTF8.hs, dist/build/Data/ByteString/Lazy/UTF8.o )
cabal: Failed to build split-0.2.3.3 (which is required by exe:app from
[4 of 5] Compiling Data.ByteString.UTF8 ( Data/ByteString/UTF8.hs, dist/build/Data/ByteString/UTF8.o )
niobiumcoconut-0.1.0.0). See the build log above for details.
[5 of 5] Compiling Data.String.UTF8 ( Data/String/UTF8.hs, dist/build/Data/String/UTF8.o )
Failed to build utf8-string-1.0.1.1 (which is required by exe:app from
cabal: The program 'ar' is required but it could not be found.
niobiumcoconut-0.1.0.0). See the build log above for details.


Command "cabal v2-repl app" exited unexpectedly
```

**Comment by xaverdh** [comment]
Yes, running in nix-shell fixes the issue. But why is the behaviour in nix-shell different from what you get by putting cabal-install in `environment.systemPackages` ? Is that intentional?

**Comment by chrissound** [comment]
I suppose it depends on the nix file the shell is loading? In my case I'm using `nixpkgs.pkgs.haskell.packages.ghc864.callPackage` which probably has `ar` defined as a build input.

**Comment by xaverdh** [comment]
Actually `ar` gets pulled in by nix-shell independent of what you tell nix-shell to do. Even `nix-shell -p bash` will pull in `binutils` and `ar` along with it.
Still as cabal-install is in the global package set, I guess it ought to work without entering a nix-shell first.

**Comment by itmuckel** [comment]
Run `nix-env -iA nixpkgs.binutils-unwrapped` and it should be fine.

**Comment by xaverdh** [comment]
I opened a pr which tries to fix this. Not sure if its the accepted / right approach though.

**Comment by xaverdh** [comment]
still an issue, but hopefully fixed by #101860

**Comment by TerrorJack** [comment]
iiuic `cabal` calls `ghc --info` and uses whatever `ar` command specified there, so the real problem is: `ghc` in `nixpkgs` isn't properly built to capture the `ar` executable at its build time.

Run `nix run nixos.ghc -c ghc --info`, and notice

```
,("ar command","ar")
```

which is definitely incorrect. It should be an absolute path pointing into the nix store.

So, the `ghc` build script in `nixpkgs` should be fixed. Just pointing the direction for anyone interested :)

**Comment by poscat0x04** [comment]
relevant ghc sources:
https://gitlab.haskell.org/ghc/ghc/-/blob/master/aclocal.m4#L533-585
https://gitlab.haskell.org/ghc/ghc/-/blob/master/includes/ghc.mk#L232

**Comment by xaverdh** [comment]
This was was indeed solved in https://github.com/NixOS/nixpkgs/commit/643169bbb48126a3b6ec3c4a32bbbe7a815d11c8.
Thanks to @TerrorJack and @peti!
