### ISSUE TITLE
python develop mode in mkShell ? and add warning over shellHook

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#55990]
## Issue description
I used to be adept of develop mode on ubuntu. I overrode the shellHook of a python package (a few months ago) and realized it removed the develop mode.
Shouldn't we add a trace/warning when shellHook is overriden here:
pkgs/development/interpreters/python/build-python-package-setuptools.nix
That would help prevent this kind of scenario.

Also I wonder how I can run the develop mode within a mkShell ? Like I want to pass a custon neovim etc for just that environment.  I suppose I should let the python derivation believe it's in a nix-shell but how can I do that ?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by FRidh** [comment]
> Shouldn't we add a trace/warning when shellHook is overriden here:

No, every attribute can be overridden.

**Comment by FRidh** [comment]
Closing because I don't see anything reasonable that can be done here.
