### ISSUE TITLE
glib out of date

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#55999]
## Issue description
We currently have 2.58.2 in master.
We need to have 2.58.3, because of https://gitlab.gnome.org/GNOME/glib/issues/1645. 

I don't know about the impact of having 2.58.3 also in 18.09, but if that's possible that would be better. 

### Steps to reproduce
It breaks various applications currently, including Google Chrome.

**Comment by hedning** [comment]
We have the fix for the issue backported, but we should of course update.

**Comment by hedning** [comment]
2.58.3 is now in staging, and the upstream fix for the reported issue was backported long ago, so closing this.
