### ISSUE TITLE
Allow passing compiler options to writeHaskell?

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#56000]
## Issue description

writeHaskell from nixpkgs/pkgs/build-support/writers/default.nix currently does not allow passing options to the compiler (ghc). Is this deliberate (because writeHaskell should be compiler agnostic)?

I find that I often need to compile with -threaded for example in my own nix code.

**Comment by RubenAstudillo** [comment]
Can that be done via overriding `mkDerivation`?

**Comment by xaverdh** [comment]
> Can that be done via overriding `mkDerivation`?

Unfortunately not (at least not without rewriting half of the derivation).

**Comment by xaverdh** [comment]
closed by #97380
