### ISSUE TITLE
[help] chromium with source from different fork

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#56016]
## Issue description
Hi. I need some help.

I'm modifying the Chromium package definition:
* enabling `use_vaapi=true` on newer 73+ builds to enable video accelerated playback
* enabling `use_ozone` and friends to get Wayland enabled builds

However, using both at the same time is broken in Chromium upstream and is resolved by a patch that is currently in a tagged igalia release (corresponding to the 74.x dev channel release)

My only remaining issue is that the nixpkgs chromium definition is rather complicated and it doesn't seem trivial to point to another chromium mirror. If I replace the entire `src` attribute, the build fails because Chromium's special `.DEPS.git` file isn't handled and some third_party repos are then missing.

Can someone help me figure out how to build Chromium from another fork? I'm okay with carrying some patches on nixpkgs for a while, though my goal is to get these changes upstreamed, even if they're not enabled by default.

cc: @bendlas @aszlig from a quick peek at git log and @volth since I've seen PRs in this area previously

**Comment by volth** [comment]
We could add ```chromium-git```, it might be even simpler that current ```chromium``` derivation.
Something like in https://github.com/volth/nixpkgs-windows/tree/4bb9e4b4c2f2cf0336ced92fdeadd9263812f7a3/pkgs/applications/networking/browsers/chromium-git/

**Comment by colemickens** [comment]
I'd be interested in maintaining that in my overlay but I don't have the time to write a derivation for chromium git linux right now. (I'm quite curious if there's a README about nixpkgs-**windows** now too)

**Comment by ckauhaus** [comment]
I think this should be continued on https://discourse.nixos.org

**Comment by volth** [comment]
There is already chromium-git for linux
https://github.com/NixOS/nixpkgs/pull/66438
