### ISSUE TITLE
Cura is missing dependency on Qt5 stuff

### ISSUE THREAD

**Issue by lambdafu** [NixOS/nixpkgs#56039]
## Issue description

Cura does not start if Qt is not installed, but aborts after the spash screen. The log includes an error about missing QtQuick.controls.

```
QQmlApplicationEngine failed to load component
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:8 module "QtQuick.Dialogs" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:6 module "QtQuick.Controls.Styles" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:5 module "QtQuick.Controls" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:8 module "QtQuick.Dialogs" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:6 module "QtQuick.Controls.Styles" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:5 module "QtQuick.Controls" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:8 module "QtQuick.Dialogs" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:6 module "QtQuick.Controls.Styles" is not installed
file:///nix/store/11iwwhkk2a6ccq4lz4338xa3mjmlwjia-cura-3.6.0/share/cura/resources/qml/Cura.qml:5 module "QtQuick.Controls" is not installed
```

### Steps to reproduce

nix-shell -p cura --run "cura"

Workaround:

nix-shell -p cura qt5.full --run "cura"

## Technical details

I don't run a complete desktop environment, but use i3 and a minimal installation. I would like to run qt apps once in a while, though, usually in a nix shell. It would be nice if that were supported without knowing about the secret sauce :)

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 19.03.git.36f3160 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - nixpkgs: `/home/marcus/nixpkgs`

**Comment by ertw** [comment]
Hi, I wasn't able to reproduce this in 19.03 with `nixos.cura` (cura version: 3.6.0), but did encounter it with `nixos-unstable.cura` (cura version: 4.1.0). I just installed the qt components globally with `nix-env -iA nixos-unstable.qt5Full`, and that fixed the issue.

**Comment by Artturin** [comment]
this should have been fixed by https://github.com/NixOS/nixpkgs/pull/66378
comment if still relevant
