### ISSUE TITLE
Why are there two attribute paths for yarn?

### ISSUE THREAD

**Issue by manvithn** [NixOS/nixpkgs#56038]
## Issue description
I currently see two attribute paths for yarn: `nixpkgs.yarn` and `nixpkgs.nodePackages.yarn`. The first seems to come from `pkgs/development/tools/yarn` while the second comes from `pkgs/development/node-packages`. I'm not sure I understand why we need both of these.

### Steps to reproduce
`nix-env -qaPA 'nixpkgs.yarn'`
`nix-env -qaPA 'nixpkgs.nodePackages.yarn'`

## Technical details
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.3`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(manvithn): `"nixpkgs-19.03pre168808.b8d7c0cab5e"`
 - nixpkgs: `/Users/manvithn/.nix-defexpr/channels/nixpkgs`

**Comment by marsam** [comment]
from the PR https://github.com/NixOS/nixpkgs/pull/21892 which introduced
> [...] this allows to install with any npm residuals, amen.

note also that yarn developers recommend against using npm to install it https://github.com/yarnpkg/website/issues/650
