### ISSUE TITLE
krita python bindings

### ISSUE THREAD

**Issue by f--t** [NixOS/nixpkgs#56042]
## Issue description

the python binding for krita are not build correctly.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by teto** [comment]
more details wouldn't hurt...

**Comment by f--t** [comment]
well I don't exactly know what is happening here,
to build the python binding, it requires ```pyqt5``` and ```sip```. So when 
```
 ++ (with python3.pkgs; [ pyqt5  sip ])
```
are added to the buildInputs, cmake finds all the dependencies correctly; however, at around 98% the compilation fails due to not finding some sip bindings. Alternatively, if 
```
 (python3.withPackages(ps: with ps; [sip pyqt5]))
```
is added to the buildInputs, everything works fine as intended. But the python interpreter overwrite the python interpreter in the nix-env, so that doesn't  seem to be the right fix.

**Comment by f--t** [comment]
also tried setting the variable, but that didn't work either.
```-DPYQT5_SIP_DIR_OVERRIDE=${python3Packages.pyqt5}/share/sip/PyQt5```

**Comment by FRidh** [comment]
cc @orivej who worked on `pyqt5`/`sip`
