### ISSUE TITLE
networking.firewall.allowed{TCP,UDP}Ports should not generate duplicate filtering rules

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#56086]
## Issue description

    networking.firewall.allowedTCPPorts = [ 443 443 ];

Seems to generate two identical iptables rules instead of just one. This kind of configuration can easily happen when multiple independent modules append the same port to the list.

IMO it would be worth de-duplicating ports (and maybe sorting?) so that the generated firewall configuration is easier to read.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 19.03.git.4f4ff1b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(delroth): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
Great idea - want to take a stab at a PR?

**Comment by delroth** [comment]
#57139
