### ISSUE TITLE
New package: nltk data?

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#56094]
While reading the derivation for the Python NLP module NLTK, I came across these lines: 

https://github.com/NixOS/nixpkgs/blob/44aca430c3745c8a5de75afc7b170f5dc0e21bd0/pkgs/development/python-modules/nltk/default.nix#L16

Wouldn't it be nice to be able to run the tests (and actually use the NLTK), by installing the data, as well? Contrary to the comments in the above link, I suspect there's nothing terribly magic about the NLTK downloader. It seems to just pull packages from [this GitHub repo](https://github.com/nltk/nltk_data) and unzip them. 

I'm really new to Nix, so this might be out of my league, but could someone else help me with this?

**Comment by JonathanReeve** [comment]
[Maybe this could help: it's how the spacy package allows for data download.](https://github.com/NixOS/nixpkgs/blob/2059bf9e39bef62e9386291e1041371bdd8036ab/pkgs/development/python-modules/spacy/models.nix)

**Comment by costrouc** [comment]
Is this the data that it downloads? https://github.com/nltk/nltk_data I could be possible to turn this into a package and then feed it in for tests.

**Comment by JonathanReeve** [comment]
Indeed, that's the data. It looks like there's [a shell script](https://github.com/nltk/nltk_data/blob/gh-pages/tools/download.sh) in that repo, too, that might be a good builder.

**Comment by JonathanReeve** [comment]
That'd be great if you could figure it out!

**Comment by JonathanReeve** [comment]
@FRidh or @rvl, maybe one of you could give this a shot?

**Comment by rvl** [comment]
Hi @JonathanReeve, what part are you having trouble with?
Is there any other reason that `nltk.download()` is not good enough?
How large is `nltk_data`?

**Comment by JonathanReeve** [comment]
I'm just new to writing nix packages, is all. `Nltk.download()` isn't deterministic, so it'd be nice to have Nix download and install `nltk_data`. I imagine it's large-ish, but it can't be too big, since it fits in a Github repo.

**Comment by costrouc** [comment]
The issue with `Nltk.download()` in a nix derivation is that that script is downloading files from multiple urls. Nix would need to know the hash of each archive being copied and be updated each time it changes. This would be tedious as it looks like there are many items. See here https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml. But yes it is completely possible.

**Comment by costrouc** [comment]
Here is an example to get you started. Happy to help you along the way if you would like to create a PR. 

```nix
{ pkgs ? import <nixpkgs> { } }:

let packages = {
      perluniprops = pkgs.fetchzip {
        url = https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/misc/perluniprops.zip;
        sha256 = "00dblv8whpkdrfar5fngs4i7p48yl4k3wn3dndy2djyb1gbw1qd0";
      };
      bllip = pkgs.fetchzip {
        url = https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/models/bllip_wsj_no_aux.zip;
        sha256 = "00h91fwlhb9dghia0wg1m39laci75rgw4w3yhl0i9gv5bw4hgnnx";
      };
  };
in
pkgs.runCommand "nltk-download" {} ''
    mkdir -p $out
    ln -sf ${packages.perluniprops}/ $out/perluniprops
    ln -sf ${packages.bllip}/ $out/bllip
  ''
```

**Comment by JonathanReeve** [comment]
I'm going to take a look at this again, now that my nix skills are slightly better. It'd be really nice to have this, since we already have the SpaCy models.

**Comment by p-h** [comment]
```nix
{ stdenv, lib, fetchFromGitHub, bash, python2, unzip }:
stdenv.mkDerivation rec {
  pname = "nltk_data";
  version = "3a486db7729373e7982eda3f7e6e6572c532d06c";
  src = fetchFromGitHub {
    owner = "nltk";
    repo = pname;
    rev = version;
    sha256 = "1ag0d2gxi74dsg01fnkc8fr1d5s5drvnqy389hv7zigwcxlmxdn5";
  };

  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    export NLTK_DATA_DIR=$out/share/nltk_data
    export PATH=${lib.makeBinPath [ python2 unzip ]}:$PATH
    bash tools/download.sh all
  '';
}
```
I quickly put this together. It puts all of nltk_data into a single derivation, should it be split up? nltk_data is not versioned, I wonder how such packages need to be versioned. I'm also not sure whether or not this use of export is the proper way to pass environment variables and runtime dependencies to the install script

**Comment by rvl** [comment]
Nice one @p-h - that works for me.

I can't find a link to the nixpkgs versioning guidelines but I believe that in these circumstance the convention is something like `version = "git-2020-01-12";`.

For me, that package consumes 3.9G in the nix store.
I think if this data package is added to nixpkgs, it should not be built by nixos hydra and not mirrored in the hydra cache. Too big!

Is there any reason to split it up? I can't think of any.

**Comment by khaneliman** [comment]
Resolved by https://github.com/NixOS/nixpkgs/pull/248675 ?
