### ISSUE TITLE
systemctl - degraded (failed to start user* services)

### ISSUE THREAD

**Issue by eyJhb** [NixOS/nixpkgs#56130]
## Issue description
At boot `user-runtime-dir@*.service` and `user@*.service` will fail to start randomly.
But after a couple of steps it will work, and not be degraded anymore.

Logs can be found here: https://gist.github.com/eyJhb/55a345d5f5afd29150c03d9c8889298e
My configuration here: https://github.com/eyJhb/dot/blob/master/dotfiles/nixos/configuration.nix
My nixpkgs (tracking stable channel): https://github.com/eyJhb/nixpkgs/tree/release-18.09

Any ideas what the problem might be?

### Steps to reproduce
Reboot and see if systemctl fails

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.101, NixOS, 18.09.git.649d462 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixpkgs-18.09, nixos-hardware"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

**Comment by eyJhb** [comment]
Trying nixos-unstable for a while, and will see if that fixes the issue.

**Comment by eyJhb** [comment]
Still persist on the unstable channel.. Any inputs would be appreciated!

**Comment by teto** [comment]
I noticed that for some boots, network-manager won't work and firefox will launch but with a disabled UI ( https://github.com/NixOS/nixpkgs/issues/49039). I usually reboot.

**Comment by eyJhb** [comment]
@teto rebooting seems like a windows way of solving things... Something underlying must be wrong :)

**Comment by teto** [comment]
I dont see it anymore. Feel free to reopen in the contrary.
