### ISSUE TITLE
postgresql 11.1 -> 11.2 changes storage dir, breaks applications

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#56134]
## Issue description

#55860 updates postgresql_11 from 11.1 to 11.2. 
<del>It seems like this includes breaking changes, since neither my Gitea nor my Quassel servers can properly work with 11.2.</del>
When upgrading, the new service is configured to use a different storage directory, because the psqlSchema version was changed: /var/lib/postgresql/11.2/ instead of /var/lib/postgresql/11.1/. This means when upgrading to 11.2, the data is not transferred and applications crash because their databases don't exist anymore.
<del>I'm also confused as to why postgresql_96 has an own package as a minor version, while postgresql 11.x share one package. Shouldn't there be postgresql_111 and postgresql_112 if 11.2 includes breaking changes?</del>

### Steps to reproduce
Rebuild a system with postgresql with the current unstable channel. postgresql 11.1 will be updated to postgresql 11.2, and all databases will not exist with the new versions, applications will crash.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 19.03.fa82ebc-nixcloud_master (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(pbb): `""`
 - channels(root): `"nixos-19.03pre169895.fa82ebccf66, nixos-unstable-19.03pre164715.201d739b0ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by danbst** [comment]
Thanks for report. PG changed it's version schema since v10. Previously v9.6.1 and 9.6.2 were considered compatible, but 9.5 and 9.6 - not compatible. Now 11.1 and 11.2 are considered compatible, but 10 and 11 - are not.

In case they really have introduced a breaking change, it should be reported upstream. We can add old PG as workaround. Can you describe what exactly was broken (test case)?

**Comment by petabyteboy** [comment]
I was running Quassel and Gitea with postgresql_11 pinned in my config. Last night the nixos-upgrade ran and updated from 11.1 to 11.2. After restarting, both Gitea and Quassel could not access their databases properly. 

For Gitea it just looked like the database was empty, all repositories and users were missing. I could not see any related messages in the log.

For Quassel, the log looked like this:
```
Feb 21 04:44:21 pbb4.pbb.lc systemd[1]: Started Quassel IRC client daemon.
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error] unhandled Error in QSqlQuery!
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                   last Query:
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:  SELECT value FROM coreinfo WHERE key = 'schemaversion'
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]               executed Query:
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:  SELECT value FROM coreinfo WHERE key = 'schemaversion'
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                 bound Values:
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                 Error Number: 42601
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                Error Message: ERROR:  syntax error at end of input
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: LINE 1: EXECUTE
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:                 ^
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: (42601) QPSQL: Unable to create query
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]               Driver Message: QPSQL: Unable to create query
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                   DB Message: ERROR:  syntax error at end of input
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: LINE 1: EXECUTE
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:                 ^
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: (42601)
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error] unhandled Error in QSqlQuery!
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                   last Query:
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:  SELECT MAX(version) FROM coreinfo
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]               executed Query:
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:  SELECT MAX(version) FROM coreinfo
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                 bound Values:
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                 Error Number: 42601
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                Error Message: ERROR:  syntax error at end of input
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: LINE 1: EXECUTE
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:                 ^
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: (42601) QPSQL: Unable to create query
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]               Driver Message: QPSQL: Unable to create query
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error]                   DB Message: ERROR:  syntax error at end of input
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: LINE 1: EXECUTE
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]:                 ^
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: (42601)
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Error] Storage Schema is missing!
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Info ] Core is currently not configured! Please connect with a Quassel Client for basic setup.
Feb 21 04:44:21 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:21 [Info ] Listening for GUI clients on IPv4 0.0.0.0 port 4242 using protocol version 10
Feb 21 04:44:38 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:38 [Info ] Client connected from 95.91.246.145
Feb 21 04:44:38 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 04:44:38 [Info ] Closing server for basic setup.
Feb 21 09:11:50 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 09:11:50 [Info ] Caught signal 15
Feb 21 09:11:50 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 09:11:50 [Info ] Quitting...
Feb 21 09:11:50 pbb4.pbb.lc quasselcore[25330]: 2019-02-21 09:11:50 [Info ] Core shutting down...
Feb 21 09:11:50 pbb4.pbb.lc systemd[1]: Stopping Quassel IRC client daemon...
```

**Comment by petabyteboy** [comment]
As a quickfix I have added my own postgresql_11_1 package in my system configuration.
https://git.pbb.lc/petabyteboy/nixfiles/commit/a65a55983762941a1aae896d59021766a73cd164

**Comment by petabyteboy** [comment]
Okay, I can now tell what causes this behaviour: When upgrading, the new service is configured to use a different storage directory: /var/lib/postgresql/11.2/ instead of /var/lib/postgresql/11.1/. This means when upgrading to 11.2, the data is not transferred.

**Comment by petabyteboy** [comment]
Probably the psqlSchema version for 11.1 and 11.2 should be 11.0.
