### ISSUE TITLE
cracklib "error loading dictionary"

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#56179]
## Issue description
Just after installing cracklib on two different NIXOS computers the following result is showing on each of them:

/nix/store/nck25bk78fhrx70fs8v80hmr0k1z3b39-cracklib-2.9.6/share/cracklib/pw_dict.pwd.gz: No such file or directory
123456: error loading dictionary

### Steps to reproduce
echo "123456" | cracklib-check

## Technical details PC #27:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.33, NixOS, 18.09pre135256.6c064e6b1f3 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-19.03pre155751.45a419ab5a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

## Technical details PC #26:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 19.03pre169895.fa82ebccf66 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre169895.fa82ebccf66"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by dtzWill** [comment]
I was just looking at this while upgrading to 2.9.7-- AFAICT we 1)don't generate dictionary using small builtin list 2)don't generate dictionary using the accompanying wordlist ('cracklist-words') which is what I think we should do.

The biggest barrier to submitting a fix is that I'm trying to see how/if this ever worked... :).  If anyone knows or has thoughts, please share! :)

**Comment by jtojnar** [comment]
Perhaps no-one used `pam_cracklib`. I am not sure how libpwquality since it uses the cracklib dictionary [by default](https://github.com/libpwquality/libpwquality/blob/7c142370ea6fc6467bfae25fc7ff8fa12105591d/src/pwqprivate.h#L45) and [propagates the error](https://github.com/libpwquality/libpwquality/blob/a29312f21c2012c2bb0a67dd5558ad713b0fe12f/src/check.c#L680-L687).

**Comment by tohl** [comment]
still broken on nixos1909 

<pre>
$ nix-shell -p cracklib --run 'echo "password" | cracklib-check'
 /nix/store/fclk0xgxj2z2ynxfx72amjpwp77w65rh-cracklib-2.9.6/share/cracklib/pw_dict.pwd.gz:
 No such file or directory
 password: error loading dictionary

$ nix-shell -p libpwquality --run 'pwscore <<<"password"'
 /nix/store/fclk0xgxj2z2ynxfx72amjpwp77w65rh-cracklib-2.9.6/share/cracklib/pw_dict.pwd.gz:
 No such file or directory
 Password quality check failed:
  The password fails the dictionary check - error loading dictionary

$ ls -l  /nix/store/fclk0xgxj2z2ynxfx72amjpwp77w65rh-cracklib-2.9.6/share/cracklib
total 492
-r--r--r-- 1 root root    360 Jan  1  1970 cracklib.magic
-r--r--r-- 1 root root 492822 Jan  1  1970 cracklib-small
</pre>

**Comment by tohl** [comment]
from https://linux.die.net/man/3/fascistcheck

On a Debian system the database is located in the directory defined by the static constant CRACKLIB_DICTPATH and is set to /var/cache/cracklib/cracklib_dict. None of the subroutines in the cracklib libraries have this location hard-coded into their implementations. It is generated daily with the program /etc/cron.daily/cracklib.

on Ubuntu 14.04.6 LTS:
<pre>
$ find /var/cache/cracklib/ -ls
 34422    4 drwxr-xr-x   2 root     root         4096 Okt 30 10:22 /var/cache/cracklib/
 34525    4 -rw-r--r--   1 root     root         1024 Okt 30 10:22 /var/cache/cracklib/cracklib_dict.hwm
 34517  408 -rw-r--r--   1 root     root       412696 Okt 30 10:22 /var/cache/cracklib/cracklib_dict.pwd
 34518   24 -rw-r--r--   1 root     root        22968 Okt 30 10:22 /var/cache/cracklib/cracklib_dict.pwi
 34553    4 -rw-r--r--   1 root     root           65 Okt 30 10:22 /var/cache/cracklib/src-dicts
</pre>

those files look different from what we have in nixos

**Comment by jtojnar** [comment]
Seems to work on nixos-unstable:

```ShellSession
$ nix-shell -I nixpkgs=$PWD -p cracklib --run 'echo "password" | cracklib-check'
password: it is based on a dictionary word
$ nix-shell -I nixpkgs=$PWD -p libpwquality --run 'pwscore <<<"password"'
Password quality check failed:
 The password fails the dictionary check - it is based on a dictionary word
$ ls -l (nix-build -A cracklib)/share/cracklib
total 9536
-r--r--r-- 1 root root     360 Jan  1  1970 cracklib.magic
-r--r--r-- 1 root root  492822 Jan  1  1970 cracklib-small
-r--r--r-- 1 root root    1024 Jan  1  1970 pw_dict.hwm
-r--r--r-- 1 root root 8779387 Jan  1  1970 pw_dict.pwd
-r--r--r-- 1 root root  478024 Jan  1  1970 pw_dict.pwi
```
