### ISSUE TITLE
KDE App Launcher not showing installed apps

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#56176]
## Issue description

The nvidia proprietary driver's settings app does not show up in the KDE App Launcher. The app is `nvidia-settings`.

I have `switch`ed and rebooted many times and still do not see it listed in KDE's App Launcher.

**Comment by worldofpeace** [comment]
Please see https://github.com/NixOS/nixpkgs/issues/20776#issuecomment-465930850

Try invalidating the cache by removing `$HOME/.cache/ksycoca5_*`. I don't think this is an issue on master.

**Comment by sondr3** [comment]
As mentioned in the linked issue, `kbuildsycoca5` should work.

**Comment by AMDphreak** [comment]
> As mentioned in the linked issue, `kbuildsycoca5` should work.

I'll give it a go. This is poor design if this is necessary. This should not be a thing. Apps that rely on invalid caches should be self-healing.

**Comment by matthewbauer** [comment]
Yeah I got that too. I think you can do this:

```
rm -f $HOME/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu
```

and the run kbuildsyscoca5.

**Comment by matthewbauer** [comment]
Potential fix here: https://github.com/NixOS/nixpkgs/pull/57037
