### ISSUE TITLE
wire-desktop: Only blank window shown

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#56224]
## Issue description

wire-desktop is non-functional, as after start only a blank window is displayed and nothing except quitting it works.
This happens no matter whether the package is run from a nix-shell ow whether it's installed into an environment.

### Steps to reproduce

`nix-shell -p wire-desktop --command "wire-desktop"`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.20, NixOS, 18.09.2137.168cbb39691 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2247.3276e04a39e, nixos-unstable-19.03pre170194.2a81eceeba6"`
 - channels(user): `"home-manager-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Are you using `wire-desktop` installed from unstable on `18.09`?

Things that could be helpful are the following for me to help are:
1. pasting the output of running the application with `strace`
2. run `wire-desktop` with `--devtools` and inspect if there's an errors in the console

**Comment by schmittlauch** [comment]
@worldofpeace No, I ran wire-desktop from stable. But I can provide you with the logs you want.
Or shall I try the unstable version right away?

**Comment by schmittlauch** [comment]
Update: The version from nixos-unstable _does_ work

**Comment by worldofpeace** [comment]
> Update: The version from nixos-unstable _does_ work

Yeah, mixing applications like this from unstable will usually never work.

**Comment by schmittlauch** [comment]
"mixing"? I'm using release-18.09 as my base system.

**Comment by worldofpeace** [comment]
"mixing" meaning using `18.09` as your base system and then using patched applications like this from unstable. But you said you weren't doing that so it's a non-issue.

Also, was this sudden or did it happen after like a system rebuild?

**Comment by schmittlauch** [comment]
Interestingly, the "mixed" version is the one that does work, while the wire-desktop from release-18.09 does *not* work.
I never used wire before, so I cannot say when it stopped working. It never did for me.

**Comment by worldofpeace** [comment]
> Interestingly, the "mixed" version is the one that does work, while the wire-desktop from release-18.09 does _not_ work.

Sorry, *does* can sometimes appear like *doesn't* :smile: 

I think it's just out of date so I'll backport the updates.

**Comment by worldofpeace** [comment]
Done this in 23453d2d8c7189d479e26de0cf87906cb5189870...8ee1cdde2200d8a70d42199dedf1769d12047ed7

I could reproduce your issue and doing this fixed it for me.

**Comment by schmittlauch** [comment]
I'l probably have another crash issue for wire-desktop, but I'm going to take care of this later =)

**Comment by worldofpeace** [comment]
btw if you want to check if that fixed it you can do
```
nix run -f "https://github.com/NixOS/nixpkgs/archive/release-18.09.tar.gz" wire-desktop
```

**Comment by arianvp** [comment]
FYI, I can not reproduce this. Wire seems to start fine for me on `release-18.09`

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.109, NixOS, 18.09.2456.43ba99fa035 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2456.43ba99fa035"`
 - channels(arian): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by worldofpeace** [comment]
Yep, the updates fixed it when I backported them.

Just left it open for reporter feedback, but I guess it's properly solved.
