### ISSUE TITLE
`sudo kate configuration.nix &` not asking for sudo permissions

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#56230]
## Issue description

`sudo kate configuration.nix &` does not ask for sudo permissions before detaching from terminal, resulting in not running any process.

**Comment by dtzWill** [comment]
Consider:
* Running `sudo -v` first, so your credentials are cached
* `sudo -b kate configuration.nix` -- runs the cmand in the background, but the job won't be controllable with normal shell job control.  I'd guess that's okay for this usage.
* `sudo -A kate configuration.nix` -- untested but idea is it'll prompt you via graphical method so being unable to prompt you on your terminal isn't fatal.

Anyway this is expected behavior-- sudo can't ask for your password in the usual way because it's backgrounded.  I am a bit surprised it doesnt complain or something? Anyway hope this helps, let us know if there's still a problem.

**Comment by AMDphreak** [comment]
> Consider:
> 
>     * Running `sudo -v` first, so your credentials are cached
> 
>     * `sudo -b kate configuration.nix` -- runs the cmand in the background, but the job won't be controllable with normal shell job control.  I'd guess that's okay for this usage.
> 
>     * `sudo -A kate configuration.nix` -- untested but idea is it'll prompt you via graphical method so being unable to prompt you on your terminal isn't fatal.
> 
> 
> Anyway this is expected behavior-- sudo can't ask for your password in the usual way because it's backgrounded. I am a bit surprised it doesnt complain or something? Anyway hope this helps, let us know if there's still a problem.

that's interesting. sudo or the terminal design should be more intelligent than to detach before running the `sudo` portion of the command.

I bet I could just use `su -c kate configuration.nix`

`su` is much better designed imo.

**Comment by jtojnar** [comment]
I do not think this is NixOS issue, I can reproduce it on Ubuntu. Either way, you should not try to run graphical applications with `sudo`: https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root

**Comment by AMDphreak** [comment]
> I do not think this is NixOS issue, I can reproduce it on Ubuntu. Either way, you should not try to run graphical applications with `sudo`: https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root

Thank you for the info.

From the archlinux page:

> Warning: All of the following methods have security implications that users should be aware of. As put by Emmanuele Bassi, a GNOME developer: "there are no *real*, substantiated, technological reasons why anybody should run a GUI application as root. By running GUI applications as an admin user you're literally running millions of lines of code that have not been audited properly to run under elevated privileges; you're also running code that will touch files inside your $HOME and may change their ownership on the file system; connect, via IPC, to even more running code, etc. You're opening up a massive, gaping security hole [...]."[1]

This is a massive design flaw in UNIX. The need for a better text editor than `nano`, combined with the absence of a default method for copying a system file to a temporary file and then edit it in a GUI pushes users in the direction of running a GUI as root. Whenever a system forces users to do something a certain way despite the obvious alternative use cases for the sake of not potentially breaking the system, this is a sign of a bad design. Microkernel architectures ftw.

**Comment by jtojnar** [comment]
The GVFS solution sounds good to me https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root#GVFS
