### ISSUE TITLE
Visual Studio Code is broken after an update

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#56236]
## Issue description

![2019-02-23-131900_1920x1080_scrot](https://user-images.githubusercontent.com/65870/53285149-458b0f80-3755-11e9-94f8-9305116bf10d.png)

### Steps to reproduce

`nixos-rebuild switch --upgrade`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.102, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre170194.2a81eceeba6, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by eadwu** [comment]
On my local nixpkgs and on rev `2a81eceeba6`, the output produced by `nix build nixpkgs.vscode` works fine.

What's the output of `code --verbose --log trace`?

**Comment by suhr** [comment]
https://gist.github.com/suhr/2e4754539e5fa1dcca80f6ac2ccfd5c5

**Comment by suhr** [comment]
A yet another system update fixed the issue.

**Comment by admercs** [comment]
The same problem occurs with the latest NixOS 23.05.1501 on kernel 6.1.36 and VS Code 1.78.2 on amd64 x86_64.
