### ISSUE TITLE
aarch64: llvm 7 fails to build on `staging-next`

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#56245]
## Issue description

Failing test:
```
Testing: 0 .. 
FAIL: LLVM-Unit :: tools/llvm-exegesis/./LLVMExegesisTests/PerfHelperTest.FunctionalTest (2933 of 27000)
******************** TEST 'LLVM-Unit :: tools/llvm-exegesis/./LLVMExegesisTests/PerfHelperTest.FunctionalTest' FAILED ********************
Note: Google Test filter = PerfHelperTest.FunctionalTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PerfHelperTest
[ RUN      ] PerfHelperTest.FunctionalTest
/build/llvm/unittests/tools/llvm-exegesis/PerfHelperTest.cpp:37: Failure
      Expected: CallbackEventName
      Which is: ""
To be equal to: "CYCLES:u"
/build/llvm/unittests/tools/llvm-exegesis/PerfHelperTest.cpp:38: Failure
Value of: CallbackEventNameFullyQualifed
Expected: isn't empty
  Actual: ""
[  FAILED  ] PerfHelperTest.FunctionalTest (3 ms)
[----------] 1 test from PerfHelperTest (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PerfHelperTest.FunctionalTest

 1 FAILED TEST
invalid event attribute - cannot create event CYCLES:u

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 

1 warning(s) in tests.
Testing Time: 108.19s
********************
Failing Tests (1):
    LLVM-Unit :: tools/llvm-exegesis/./LLVMExegesisTests/PerfHelperTest.FunctionalTest

  Expected Passes    : 25609
  Expected Failures  : 141
  Unsupported Tests  : 1249
  Unexpected Failures: 1
make[3]: *** [CMakeFiles/check-all.dir/build.make:58: CMakeFiles/check-all] Error 1
make[3]: Leaving directory '/build/llvm/build'
make[2]: *** [CMakeFiles/Makefile2:365: CMakeFiles/check-all.dir/all] Error 2
make[2]: Leaving directory '/build/llvm/build'
make[1]: *** [CMakeFiles/Makefile2:372: CMakeFiles/check-all.dir/rule] Error 2
make[1]: Leaving directory '/build/llvm/build'
make: *** [Makefile:251: check-all] Error 2
builder for '/nix/store/4kq72x6ahrigryr6yjjj7c7ayqy8z2sl-llvm-7.0.1.drv' failed with exit code 2
```

(we should have a `NixOS/aarch-maintainers` group)

### Steps to reproduce

https://hydra.nixos.org/build/89374036

`staging-next` PR https://github.com/NixOS/nixpkgs/pull/56200

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by dtzWill** [comment]
Slightly related: #56156 (llvm test failures on aarch64).

Hydra indicates this worked previously, so certainly needs fixing! :)

**Comment by FRidh** [comment]
Seems resolved so closing.

**Comment by tomfitzhenry** [comment]
This has re-occurred: https://hydra.nixos.org/build/90521563

**Comment by wizeman** [comment]
This issue also occurred when I tried to build llvm 7.0.1 on a Raspberry Pi 3.

**Comment by wizeman** [comment]
This test failure may happen because perf events are disabled in userspace, see https://github.com/llvm-mirror/llvm/blob/6b547686c5410b7528212e898fe30fc7ee7a70a3/tools/llvm-exegesis/lib/PerfHelper.cpp#L100-L102

**Comment by wizeman** [comment]
This can probably be worked around by setting `enablePFM` to `false` in `llvm.nix`, which would likely disable the `llvm-exegesis` tool.

**Comment by vcunat** [comment]
It's still happening repeatedly, at least on Hydra's `packet-c2-large-arm`, [here](https://hydra.nixos.org/build/95375417#tabs-buildsteps) three instances on release-19.03 branch and llvm 7.0.1, [here](https://hydra.nixos.org/build/95139702#tabs-buildsteps) one instance on staging-next branch and llvm 7.1.0.

**Comment by vcunat** [comment]
Any other idea than to disable this particular test? (on aarch64 at least)

**Comment by grahamc** [comment]
It seems c2.large.arm, which is Ampere eMAG hardware consistently fails. I've shared this with some people in the Arm ecosystem, maybe they have some insight.

**Comment by grahamc** [comment]
This same tests fails for llvm8 on these machines. According to LebedevRI in #llvm on OFTC, llvm assumes libpfm knows how to measure cycle counters for each CPU. On this machine, it evidently doesn't know how. I'm giving it a go with enablePFM set to false.

**Comment by vcunat** [comment]
Yes, I also had the impression that it's failing to find some hardware counter, which is why the test didn't seem important to me (for the distro level at least).

**Comment by grahamc** [comment]
Disabling libpfm did the trick.  I wonder what the consequences are of removing libpfm on aarch64?
