### ISSUE TITLE
luakit won't work with https

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#56266]
## Issue description
Error message appears and refuses to load webpages:

```TLS/SSL support not available; install glib-networking```

### Steps to reproduce

1. install luakit (18.10 profile)
2. start it.

**Comment by jtojnar** [comment]
That was fixed in https://github.com/NixOS/nixpkgs/pull/52865

**Comment by vcunat** [comment]
Thanks for contributing!
