### ISSUE TITLE
Try to package gaminganywhere

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#56273]
I tried first to adapt the hello.nix from the nixos documentation but then it wanted libX11 and if I add libX11 to the inherit line it does not work.

The buildscript:
```
export PATH="$gnutar/bin:$gcc/bin:$gnumake/bin:$coreutils/bin:$gawk/bin:$gzip/bin:$gnugrep/bin:$gnused/bin:$binutils/bin"
tar -xzf $src
cd gaminganywhere-0.8.0/ga
# ./configure --prefix=$out
make
make install
```
the current version of my nix file looks like that:
```
{ stdenv, fetchurl, libX11}:
stdenv.mkDerivation {
  name = "ge-0.8.0";
  builder = ./ga-builder.sh;
  inherit  libX11;
  # buildInputs = [gnutar gzip gnumake gcc coreutils gawk gnused gnugrep libX11];
  src = fetchurl { ￼
    url = https://github.com/chunying/gaminganywhere/archive/v0.8.0.tar.gz;
    sha256 = "1md7jsfd8pa45z73bz1kszpp01yw6x5ljkjk2hx7wl800any6465";
  };
}
```
when I try to build with nix-build -A I get following error:
error: cannot auto-call a function that has an argument without a default value ('stdenv')

Can somebody explain to me what that means?

**Comment by jtojnar** [comment]
That just means you are not passing the `stdenv` argument to the function on line 1.

You can set the arguments like this:

```
nix-build gaming.nix --arg stdenv '(import <nixpkgs> {}).stdenv' --arg fetchurl '(import <nixpkgs> {}).fetchurl' --arg libX11 '(import <nixpkgs> {}).libX11'
```

or better

```
nix-build -E 'with import <nixpkgs> {}; callPackage ./gaming.nix {}'
```

**Comment by spiderbit** [comment]
yes that helped a bit but now I get:
```
error: undefined variable 'tar' at /home/black/tmp/GA/default.nix:2:22
```
adding gnutar to inherit and or the first line inside the {} doesn't make this build-dependency available?

**Comment by jtojnar** [comment]
Try using `gnutar` then.

**Comment by jtojnar** [comment]
And you need to accept it as an argument like you do with `fetchurl`.

**Comment by spiderbit** [comment]
Well I used the "or better" line so I do no fetchurl stuff.
```
nix-build -E 'with import <nixpkgs> {}; callPackage ./gaming.nix {}'
```

and yes I tried gnutar, or do you mean in the buildscript? I think only the package name is gnutar as command you use still tar right?

**Comment by jtojnar** [comment]
One of the things `callPackage` does is that it calls the function in the file with attributes from `nixpkgs` as the arguments. If you want to use `gnutar` in the expression, you need to accept is as argument (the first line). Then you can go forward with the actual usage like one of these:

- `inherit` it in `mkDerivation` so that the builder sees it as an environment variable
- add it to `buildInputs` so that `mkDerivation` passes it in `PATH` variable to builder

I recommend reading [`nix-pills`](https://nixos.org/nixos/nix-pills/) if you want to learn how `mkDerivation` works.

**Comment by spiderbit** [comment]
Yes I read yesterday the pills and looked over it again, rewrite it a bit more general:

But then I fall back to the beginning:

```
with (import <nixpkgs> {});
derivation {
  name = "ge-0.8.0";
  builder = "${bash}/bin/bash";
  args = [ ./ga-builder.sh ];
  buildInputs = [ gnutar gzip gnumake gcc binutils-unwrapped coreutils gawk gnused gnugrep pkgconfig];
  src = ./v0.8.0.tar.gz;
  system = builtins.currentSystem;
}
```
In what package is the libswscale stuff in nixos there seems no seperate package for it?
`
Package libswscale was not found in the pkg-config search path.`

**Comment by jtojnar** [comment]
It is part of ffmpeg package.

**Comment by spiderbit** [comment]
he still don't finds it is the code to set the path wrong?

```
set -e
unset PATH
for p in $buildInputs; do
  export PATH=$p/bin${PATH:+:}$PATH
done
```

`buildInputs = [ffmpeg gnutar gzip gnumake gcc binutils-unwrapped coreutils gawk gnused gnugrep pkgconfig];`

```
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
```

**Comment by jtojnar** [comment]
For `pkg-config` based libraries, you need to do something similar: `s/PATH/PKG_CONFIG_PATH/` and `s/bin/lib\/pkgconfig/`. Many packages also have the `lib/pkgconfig` directory under dev output (eg `glib.dev` instead of `glib`) so you will need to handle that as well.

**Comment by spiderbit** [comment]
Can you try to be a bit more specific and show me the export command you have in mind? 

I don't think I can do that right, somethnig like that?

`export PATH=$p/bin${PATH:+:}$PATH:s/PATH/PKG_CONFIG_PATH/
`

**Comment by jtojnar** [comment]
That is sed command`s/pattern/replacement/`. I meant for you to do the same as for the `bin` directory but with the environment variable and subdirectory changed.

**Comment by spiderbit** [comment]
Sorry I am not so fit with sed pattern and not with the nix language to make get that adapted, I only try to package that because I could not get the binaries running that they provide.

I don't know which is easier I tried to do the patchelf stuff on it but the furthest it got was that:
```
$ patchelf --print-interpreter ga-client 
Symbol’s function definition is void: cat
```
and the wiki page didn't describe how you could solve that. I mean it would be better to have nix package in the nixos repos for it so investing time to build it would probably better, but if that's easier to do and there is no big interest in getting that into nixos maybe that would be the easier approach?

I don't mind investing a bit time in trying to get that run, but I am a bit stuck here and you getting not concrete enough to get over this step.

**Comment by jtojnar** [comment]
If the project has makefile, using the default builder provided by `stdenv.mkDerivation` might be easier. Try to check some other packages in nixpkgs. You might also get more timely help on IRC.

**Comment by spiderbit** [comment]
So I did read today all the language specific pills about the nix language. It's a bit much but a more or less understand it's concepts.

But in the end it comes mostly done to the builder file at the moment. I got rid of all build warnings except that one:

```
ga-common.cpp:43:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
```

Had to add the nix file with:
```
buildInputs = [xlibs.libX11.dev SDL2_ttf SDL2.dev ffmpeg.dev gnutar gzip gnumake gcc coreutils gawk gnused gnugrep pkgconfig];
```
And set the paths variable a bit ugly but works for the PKG_CONFIG_PATH:

```
export PKG_CONFIG_PATH=/nix/store/rmvvp7khclajwnv617w4m0r6mwji8rcc-ffmpeg-3.4.4-dev/lib/pkgconfig:/nix/store/41822jf8477cm43q2s3dsh9l1k06c7j9-SDL2-2.0.8-dev/lib/pkgconfig:/nix/store/3vxr6519dsf5k8dbd61jbjrn5pz0gv3k-SDL2_ttf-2.0.14/lib/pkgconfig

export CPLUS_INCLUDE_PATH=/nix/store/73qmcm16ykpmjvx0dni8r8yqbdiwf4bx-libX11-1.6.7-dev/include
```

Sadly I don't get it to recognise the include path for the Xlibs header file. Any ideas?

**Comment by spiderbit** [comment]
ok use no builder that seems to work better solves the xlib.h issue.

And changed lots of code like that:
```
vsource.cpp:479:27: note: suggested alternative: 'AV_PIX_FMT_YUV420P'
  if(frame->pixelformat == PIX_FMT_YUV420P) {
                           ^~~~~~~~~~~~~~~  
```

But now I am stuck here:
```
ga-liveserver.h:24:10: fatal error: liveMedia.hh: No such file or directory
 #include "liveMedia.hh"
          ^~~~~~~~~~~~~~
```

installed it with that:
```
{ stdenv, lib, fetchurl, libX11, gnutar, gzip, gnumake, gcc, coreutils, gawk, gnused, gnugrep, ffmpeg, pkgconfig, SDL2_ttf, SDL2, alsaLib, libXext, libXtst, x264, libXi, live555}:
with lib;
stdenv.mkDerivation rec {
...
  buildInputs = [libX11.dev SDL2_ttf SDL2.dev ffmpeg.dev gnutar gzip gnumake gcc coreutils gawk gnused gnugrep pkgconfig alsaLib.dev libXext.dev libXtst x264 libXi.dev live555];
```
the livemedia.hh is in the live555 package included but nix don't fixe the environment that this include works.

**Comment by spiderbit** [comment]
Here is what I have at the moment:

https://ufile.io/18xwm
https://uploadfiles.io/hmuc4

**Comment by spiderbit** [comment]
Lol just saw that there are 150 forks of that software on github the one that is linked frome the website is not the one with the newest patches:

https://github.com/nonameino/gaminganywhere

This seems to be better, with patches from 2019 including:
nonameino/gaminganywhere@4de0759dd1de16d06b419b41ca0dbf6c176b731c

**Comment by spiderbit** [comment]
Ok this forks seem to create more problems than they solve so I stick with the original for now, because it's nearly done.

In theory it should not be rocket science to get the current thing fixed livemedia.hh is in the repo I just need the include function find it.

**Comment by jtojnar** [comment]
You could try using all-in-one package provided on their website. That should hopefully contain all the required headers:

http://www.gaminganywhere.org/dl/gaminganywhere-0.8.0-all-in-one.tar.bz2

Though they are probably vendored, which is not welcome in linux distros.

**Comment by jtojnar** [comment]
This looks wrong:

https://github.com/chunying/gaminganywhere/blob/a8e1e2f1904ac0244033e1acb1c98afbb654c16e/ga/module/server-live555/Makefile#L4

Try adding `CXXFLAGS = "-I${live555}/include/path/to/the/header";` to the package expression.

**Comment by spiderbit** [comment]
That worked here:

```
CFLAGS	+= -I/nix/store/88hiwjz0j0379p9mpixr1xmaqwcbzlc7-live555-2018.10.17/include/liveMedia -I/nix/store/88hiwjz0j0379p9mpixr1xmaqwcbzlc7-live555-2018.10.17/include/groupsock/ -I/nix/store/88hiwjz0j0379p9mpixr1xmaqwcbzlc7-live555-2018.10.17/include/UsageEnvironment/ -I/nix/store/88hiwjz0j0379p9mpixr1xmaqwcbzlc7-live555-2018.10.17/include/BasicUsageEnvironment/
LDFLAGS	+= -L/nix/store/88hiwjz0j0379p9mpixr1xmaqwcbzlc7-live555-2018.10.17/lib ....
```
Now I am in the '/build/ga/client' directory first some easy errors give a update when I am stuck next time.

**Comment by spiderbit** [comment]
Lol it finished but:

```
~/tmp/GA $ ls /nix/store/fv2x8b23ma1nvmjcw94jwls0cbzxjfj1-ga-0.8.0/
~/tmp/GA $
```

```
make[1]: Leaving directory '/build/ga/server'
make -C client install
make[1]: Entering directory '/build/ga/client'
mkdir -p ../../bin
cp -f ga-client ../../bin
cp -f *.ttf ../../bin
make[1]: Leaving directory '/build/ga/client'
cp -fr config ../bin/
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/fv2x8b23ma1nvmjcw94jwls0cbzxjfj1-ga-0.8.0
```

Is there somewhere the build path? rofl it just compiled the bins and then > /dev/null -ed em :D

**Comment by jtojnar** [comment]
Bah, their build system is terrible:

They expect the dependencies to be installed in their own directory:

https://github.com/chunying/gaminganywhere/blob/a8e1e2f1904ac0244033e1acb1c98afbb654c16e/deps.src/Makefile.ubuntu#L36

And then they install the package to build directory:

https://github.com/chunying/gaminganywhere/blob/a8e1e2f1904ac0244033e1acb1c98afbb654c16e/ga/server/periodic/Makefile#L37

You will need something like

```nix
postInstall = ''
    cp -r bin $out/bin
```

**Comment by spiderbit** [comment]
ok that worked:
```
  postInstall = ''
    cp -r ../bin $out/
  '';
```

now I have to test the program the binaries are there.

**Comment by spiderbit** [comment]
yeah works, tested it with the desktop config and shares my windows screen could play a round Legend of Grimrock (had to remove fullscreen mode) but for fast paced stuff it has a small delay which makes it not viable for e-sports even on local lan, that said there is some tweeking with game specific config files possible.

That said my gaming rig is very ancient fx6300 maybe it would work better on a better server I will dumb the work I done in a github repos probably even as fork of the original so that everybody can see my work as a patch / commit.

I have mixed feelings about that software but learned a lot about nixos packaging and thank you for helping teaching me @jtojnar

**Comment by spiderbit** [comment]
Well I uploaded my changes, sadly I must have fucked up something because there are bigger changes mixed in with my changes maybe I deleted in my root some paths and add it later in another commit again, not sure but at least there are all files nessasary to make the build.

If I find time I might look it up again and maybe get the patches smaller but for now the files are here:

https://github.com/spiderbit/gaminganywhere/tree/v0.8.8-nixos

**Comment by spiderbit** [comment]
Ok just as for now last update, cleaned up the commits.

Had some file copies that did overwrite symlinks therefor the commit was thousands of lines. Now it's transparent what the changes are.

There are 1 2 lines with absolute Paths that would need to be fixed but apart from that it should be fine and transparent what I had to do to make it work. Most of it seems to me not nixos specific but because I use the newer libs in nixos instead of the bundled old deps.

I guess that can be closed, I probably create a new Issue on their github site, so they maybe can backport parts of it.
