### ISSUE TITLE
Update sonic-visualiser to 4.0.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#56299]
4.0.1 released
https://github.com/sonic-visualiser/sonic-visualiser/releases/tag/sv_v4.0.1  
Changelog: https://github.com/sonic-visualiser/sonic-visualiser/blob/master/CHANGELOG  

~~3.3 was released
https://code.soundsoftware.ac.uk/attachments/download/2491/sonic-visualiser-3.3.tar.gz
Changelog: https://code.soundsoftware.ac.uk/projects/sonic-visualiser/repository/entry/CHANGELOG~~

~~3.2.1 was released 
https://code.soundsoftware.ac.uk/attachments/download/2434/sonic-visualizer-3.2.1.tar.gz  
Changelog: https://code.soundsoftware.ac.uk/projects/sonic-visualiser/repository/entry/CHANGELOG~~

~~version in repo: 2.4.1  
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/sonic-visualiser/default.nix~~

**Comment by luzpaz** [comment]
@ttuegel care to update this? :smile:

**Comment by luzpaz** [comment]
@goibhniu would you mind updating this package ?

**Comment by luzpaz** [comment]
@cillianderoiste perhaps you could update this package?

**Comment by vandenoever** [comment]
here is an update https://github.com/NixOS/nixpkgs/pull/80318

**Comment by luzpaz** [comment]
Thanks!
 fc592a5
