### ISSUE TITLE
Remove winstone package and module?

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#56294]
The winstone package and module were used to to serve up solr before 19.03. As of 19.03 this is no longer true, and winstone isn't used anywhere else in nixpkgs that I can see. This software hasn't seen an upstream release/update in over 10 years now, so I'm thinking it is time to remove this from nixpkgs. Maybe mark as going to be removed for 19.03 and then remove for 19.09?

Any thoughts from @rickynils or @pSub on this?

**Comment by aanderse** [comment]
I stumbled upon https://github.com/geronimo-iia/winstone which *appears* to be the continued development of winstone after the original author stopped working on it. I would suggest that this package should either be updated or dropped.

**Comment by c0bw3b** [comment]
Though even that fork has not seen new commits for the last 4 years.
Plus nowadays Jetty/Tomcat/Undertow can also stay light(er)weight so I'm not sure there is still a use case for Winstone out there.. I'd vote for removal.

**Comment by pSub** [comment]
I think it can be removed, too.
