### ISSUE TITLE
Flashplayer needs update to 32.0.0.142 for chromium on stable

### ISSUE THREAD

**Issue by tollb** [NixOS/nixpkgs#56310]
## Issue description
In release-18.09, pkgs/applications/networking/browsers/chromium/plugins.nix, the flash plugin is still at version 32.0.0.114, but I believe it should be updated to 32.0.0.142, as on master.

See: #55669 and #55707
cc: @srhb @7c6f434c @averelld  @taku0 @NeQuissimus 

I'm happy to open a PR for this, but thought it made sense to coordinate with the individuals involved in the earlier flashplugin 32.0.0.142 updates. Please advise.
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.24, NixOS, 18.09.git.2354875 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by bendlas** [comment]
Thanks for getting this taken care of.
