### ISSUE TITLE
openssh: listenAddresses is ignored when startWhenNeeded is set

### ISSUE THREAD

**Issue by uvNikita** [NixOS/nixpkgs#56325]
## Issue description
I just noticed that my laptop was listening on port 22 on all interfaces even though I configured it to listen only on the loopback interface.

When `startWhenNeeded` parameter from `services.openssh` is set to true, `listenAddresses` parameter is ignored when configuring systemd socket.

### Steps to reproduce
configuration.nix:

```nix
  services.openssh = {
    enable = true;
    listenAddresses = [
      { addr = "127.0.0.1"; port = 22; }
    ];
    startWhenNeeded = true;
  };
```

Check listening sockets:

```bash
sudo ss -ntl | grep 22
LISTEN  0        128             *:22              0.0.0.0:*       users:(("systemd",pid=1,fd=44))                             
```

Instead, the socket should be listening only on `127.0.0.1`.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.101, NixOS, 18.09.2211.19a0543c628 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-laptop-18.09.2211.19a0543c628, nixos-unstable-19.03pre166987.bc41317e243"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos-laptop`
```

**Comment by xeji** [comment]
Thanks you for reporting and fixing this bug.
