### ISSUE TITLE
Please package CudaText

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#56339]
Cross-platform text editor, written in Lazarus

> CudaText is like an open source Sublime Text. Its core is written in Object Pascal, which makes it fast and agile and its plug-in system ist based on Python, which makes it qickly extensible. The developers are very responsive and kind.

From: https://www.slant.co/topics/12/viewpoints/74/~best-programming-text-editors~cudatext

Repository: https://github.com/Alexey-T/CudaText
Mirror: http://uvviewsoft.com/cudatext/download.html

Development seems very active (last commit 15 minutes ago).

Might be a nice open source alternative to SublimeText.

**Comment by sikmir** [comment]
Still important to me.
