### ISSUE TITLE
Redshift temperature.day and night are swapped

### ISSUE THREAD

**Issue by cvoges12** [NixOS/nixpkgs#56333]
## Issue description

The options for redshift temperature day and night are switched. 

### Steps to reproduce

Include `services.redshift.temperature.day` and `services.redshift.temperature.night` in your configuration. This persists with using `services.redshift.latitude` and `services.redshift.longitude` so this should not be in any way relating to #45994 as this happens when the location is specified manually.

## Technical details

* System: NixOS 18.09.1853.c2950341d03 (Jellyfish)
* Nix version: nix-env 2.1.3
* Nixpkgs version: 18.09.1853.c2950341d03

**Comment by eadwu** [comment]
I don't see any issue with `temperature.{day,night}`

`redshift -h`
```
...
  -b DAY:NIGHT  Screen brightness to apply (between 0.1 and 1.0)
...
  -l LAT:LON  Your current location
...
  -t DAY:NIGHT  Color temperature to set at daytime/night
...
```

`redshift.nix`
```
{ ... }:

{
  services.redshift = {
    enable = true;
    latitude = "4";
    longitude = "-2";

    brightness = {
      day = "1";
      night = "0.8";
    };

    temperature = {
      day = 6504;
      night = 2700;
    };
  };
}
```

`systemctl --user cat redshift`
```
...
ExecStart=/nix/store/r0xj05im4gs8sp9wm895mzn54wfmynqh-redshift-1.12/bin/redshift \
  -l 4:-2 \
  -t 6504:2700 \
  -b 1:0.8 \
...
```
