### ISSUE TITLE
nixos-generate-config should ensure that nix.nrBuildUsers >= autodetected nix.maxJobs

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#5637]
My computer supports 12 hardware threads (6 core CPU + hyperthreading). This lead to nixos-generate-config producing a hardware-configuration.nix containing `nix.maxJobs = 12;`. `nix.nrBuildUsers` defaults to 10, so this produced a configuration which fails to complete large builds without "-j 10".

**Comment by rbvermaa** [comment]
In stead of 10 we should perhaps have a default value that is dependent on nix.maxJobs, e.g. minimum of 10 and nix.maxJobs.

**Comment by rbvermaa** [comment]
Or we should add a check on nix.nrBuildUsers to complain that the config is wrong.
