### ISSUE TITLE
NixOS image missing from GNOME Boxes

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#56427]
GNOME Boxes offers a feature to quickly instantiate a virtual machine from ISO of many Linux distributions but NixOS is not among them.

We probably need to add it to [osinfo-db](https://gitlab.com/libosinfo/osinfo-db).

This might help upstream developers to better debug issues with their software on NixOS. Especially with https://github.com/NixOS/nixpkgs/pull/10288

**Comment by worldofpeace** [comment]
:+1: Yeah we totally should have this.
Any way we can enable upstream devs or users to test our platform will benefit us.

**Comment by mmilata** [comment]
FTR once the [osinfo-data entries](https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/107) are in place we should also add [the logo](https://github.com/NixOS/nixos-artwork/tree/master/logo) to [gnome-boxes-logos](https://gitlab.gnome.org/GNOME/gnome-boxes-logos/) and reference to it to [the gnome-boxes repo](https://github.com/GNOME/gnome-boxes/blob/mainline/data/osinfo/manjaro-19.0.xml).

**Comment by worldofpeace** [comment]
We now have nixos in osinfo-db https://gitlab.com/libosinfo/osinfo-db/-/commit/ab0ae67cf3df4ff6abd7ced9b482902bf04071eb

**Comment by mmilata** [comment]
Logo merged, [GNOME Boxes change](https://gitlab.gnome.org/GNOME/gnome-boxes/-/merge_requests/309) uderway, looks like this is gonna be part of GNOME 3.38.

**Comment by piegamesde** [comment]
It seems to be part of Gnome 3.36.6. Can this be closed?

![image](https://user-images.githubusercontent.com/14054505/95581213-e74d9600-0a38-11eb-8731-a75419e63273.png)
