### ISSUE TITLE
Brave browser does not start

### ISSUE THREAD

**Issue by acyuta108** [NixOS/nixpkgs#56431]
## Issue description
Brave browser installation succeeds but cannot start:
```
$ journalctl -b | grep [b]rave
Feb 26 14:57:36 acyuta-nixos0 kernel: traps: brave[2446] trap int3 ip:555883b8e8e7 sp:7fff20e26400 error:0 in brave[55587fedc000+6962000]
```
### Steps to reproduce
```
$ nix-env -i brave
warning: there are multiple derivations named 'brave-0.59.34'; using the first one
installing 'brave-0.59.34'

$ ls -la `which brave`
lrwxrwxrwx 1 root root 67 Dec 31  1969 /home/acyuta/.nix-profile/bin/brave -> /nix/store/2sh5sjlxsivni380xhd27n9wk3bzha47-bra
$ brave
Trace/breakpoint trap
```

## Technical details
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre169108.36f31600749"`
 - channels(acyuta): `"nixos-18.09-18.09.2203.9bd45dddf81, nixpkgs-19.03pre169106.1a88aa9e0cd"`
 - nixpkgs: `/home/acyuta/.nix-defexpr/channels/nixpkgs`

**Comment by worldofpeace** [comment]
I can't reproduce this on master or with the version you have installed.

I think the issue might be with  `nix-env` because of the warning
```
warning: there are multiple derivations named 'brave-0.59.34'; using the first one
```

**Comment by emmanuelrosa** [comment]
I've been using Brave successfully on Koi and now on Loris. However, I install it via `configuration.nix`. Try using the `nix-shell` verbosity options to troubleshoot further.

**Comment by acyuta108** [comment]
Nope. Reinstalled from configuration.nix did not work and install into nix-shell no difference either:
```
$ nix-shell '<nixpkgs>' -i brave --verbose --pure
.... # a lot of out put from installation
$ brave
Trace/breakpoint trap
```
I'm total Nix noob so I'm not sure how to troubleshoot this further and I'm not sure what you mean by 

> Try using the `nix-shell` verbosity options to troubleshoot further.

Thanks for your help

**Comment by acyuta108** [comment]
Bam! Fixed it:
```
strace /nix/store/2sh5sjlxsivni380xhd27n9wk3bzha47-brave-0.59.34/bin/brave
...
stat("/home/acyuta/.config/BraveSoftware/Brave-Browser", 0x7fff2669a870) = -1 EACCES (Permission denied)
...
```
Fixed permissions: `sudo chown acyuta: ~/.config/BraveSoftware`
Not sure how the permissions where messed up but this fixed it.
