### ISSUE TITLE
Collision between btrfs-progs and dosfstools, prevents nixos-rebuild

### ISSUE THREAD

**Issue by callahad** [NixOS/nixpkgs#56432]
## Issue description

`nixos-rebuild switch` fails with:

```
building '/nix/store/1hj0as7nxvp8ygi2g64p9cyd0wypggbh-system-fish-completions.drv'...
collision between `/nix/store/8pjk8dan7n882bdabz0fz5lgir7xqhri-btrfs-progs-4.20.1-fish-completions/mkfs.fish' and `/nix/store/fjqabfg5nwj3313c828ikvhm443n6iay-dosfstools-4.1-fish-completions/mkfs.fish'
builder for '/nix/store/1hj0as7nxvp8ygi2g64p9cyd0wypggbh-system-fish-completions.drv' failed with exit code 25
cannot build derivation '/nix/store/2qr8mqnjws0gw3y37zn9zy1nndd5zgsv-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h6mn1vkyy1b1182mvwnybmfhnpn1dprc-nixos-system-meta-19.09pre170705.1233c8d9e9b.drv': 1 dependencies couldn't be built
error: build of '/nix/store/h6mn1vkyy1b1182mvwnybmfhnpn1dprc-nixos-system-meta-19.09pre170705.1233c8d9e9b.drv' failed
```

### Steps to reproduce

With fish, btrfs-progs, and dosfstools all installed:

1. nix-channel --update
2. nixos-rebuild switch

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.11, NixOS, 19.03pre170287.19eedaf867d (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre170705.1233c8d9e9b"`
 - channels(dan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matthewbauer** [comment]
Probably from 5cc63776472effb04ad3a472e48e37577243c133. I think we can just do ```ignoreCollisions = true``` in the buildEnv.

/cc @hyperfekt

**Comment by hyperfekt** [comment]
Working on this. Looks like the output of the completion generation script includes the path of the input file, meaning completions that are actually equivalent collide in buildEnv.

**Comment by hyperfekt** [comment]
Sorry about that, the revert should have gotten (or will get) rid of the error and I fixed this bug in the PR. Thanks for your report!

**Comment by dotlambda** [comment]
> Someone should also revert the commit in the 19.03 branch so other people don't get the same unwelcome surprise.

Done
