### ISSUE TITLE
LLVM 8 (currently on -rc3)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#56490]
## Issue description

It would be good to get started on this so as to provide feedback upstream and so we're ready when the release is made.

I'm not sure if this release will build in the same way as the previous versions, or if it's time to use `runtimes` and similar directories as upstream increasingly prefers (and possibly single unified tree).

Unfortunately I don't think I'll have time to tackle this in the near-ish future, so flagging it in case someone else wants to take on this task :).

As usual LLVM and NixOS releases are close but not quite close enough to easily include the LLVM release in 19.03 (but new versions can be backported so not a big deal perhaps).

**Comment by dtzWill** [comment]
This looks to have been already tackled as part of https://github.com/NixOS/nixpkgs/pull/56555 -- modulo bumping to rc3 but that's generally easy once the new version is otherwise working :).

**Comment by vcunat** [comment]
There's a [separate PR](https://github.com/NixOS/nixpkgs/pull/56645), so let's move discussion in there.
