### ISSUE TITLE
NixOS Live media on Dell XPS 15 9570. 18.09 and 19.09pre won't boot. 17.09 boots but cannot start display manager.

### ISSUE THREAD

**Issue by djrollins** [NixOS/nixpkgs#56514]
## Issue description
I've been excited to try out NixOS but I seem to have gotten stuck almost immediately.

NixOS 18.09 and 19.09pre won't boot at all. When I select the USB UEFI partition in my BIOS I am greeted a black screen with a static cursor in the top left corner. I cannot even seem to get to a boot loader.

I am getting the above issues with the following versions:

- 18.09 Graphical
- 18.09 Minimal x64
- 19.09pre Graphical

I have tried with two different USB sticks and have tried booting Arch again with the same sticks which boot successfully.

I then tried to use the 17.09 Graphical version which would boot into the successfully into the tty. When trying to start the display-manager with `systemctl start display-manager`, I would get the same black screen with static cursor in the top left. It would flick between this and the tty 3 times before returning the tty. `systemctl status display-manager` would suggest the the xserver failed to start, but there's so much info there that I cannot pinpoint what exactly is causing it.

I also tried the `nomodeset` boot option, which also failed to start display-manager in the same manner.

I am going to try some of the other kernel parameters on this version, but I am unsure how to do the same for versions 18+ as I cannot even get into the bootloader.

### Steps to reproduce

Attempt to boot the NixOS live media on a Dell XPS 15 9570 laptop.

(Sorry for the lack of specifics here...)

## Technical details

I used `dd` to create the live media. I have also tried `cp`ing to the device directly. I have also tried using Rufus on a Windows installation. All exhibit the same issues.

I am trying to do this on a Dell XPS 15 9570 which has the following hardware:

CPU: Intel Core i7-8750H @ 12x 4.1GHz [49.0°C]
GPU: GeForce GTX 1050 Ti with Max-Q Design (Optimus)

**Comment by vcunat** [comment]
My first tip would be around Optimus.  Judging from memory of past posts, it often doesn't work on NixOS default config.

**Comment by djrollins** [comment]
I can understand that being the case - there are always so many issues with Optimus on Linux. I'm leaning towards the idea of installing NixOS from some other live media that will actually boot, but the fact that live-media doesn't work out of the box is a little worrisome. Especially if I need to boot a live medium to fix an update that breaks my system in the future.

**Comment by vcunat** [comment]
Updates are easier, as long as you always keep at least one generation that works (fairly easy).

**Comment by djrollins** [comment]
Ok, thanks @vcunat. In which case, I'll installing from another distro a go. I'll keep the issue open a little longer just in case any one else has anything to add.

**Comment by OPNA2608** [comment]
You could install NixOS from the installer in text mode to at least get a running system on it to experiment with. Just skip the `systemctl start display-manager` and proceed as if you picked the minimal installer.

For getting graphics running later on, going Intel-only and switching to an nvidia configuration once the Xserver is running seems to work on an [XPS 15 9560](https://github.com/NixOS/nixpkgs/issues/24711#issuecomment-300718852).

**Comment by djrollins** [comment]
@OPNA2608 Thank you for the reply. That's a fair point, though I would have to use the 17.09 version as with the later versions I can't event get to the bootloader let alone the tty. This is arguably 'better' than installing from a non-NixOS distro, though.

**Comment by vcunat** [comment]
I think it's possible that you can work around the problem by some GPU setting in BIOS (though <50% probability I guess).

**Comment by eadwu** [comment]
Try enabling Legacy Boot for USB in the BIOS.

**Comment by tomvonclef** [comment]
I am having the exact same issue (Dell 9570, USB UEFI w/ black screen with a static cursor in the top left corner).

Legacy Boot did not help at all.

**Comment by JosephLucas** [comment]
I managed to boot the live NixOS, from a USB stick, on my dell XPS 15 9750. Have a look at [my install guide](https://github.com/JosephLucas/nixos).

> On hardware config menu (F2 while booting):
> * Deactivate RAID and activate AHCI instead. Otherwise the live NIXOS won't see the RAID device before installation.
> * For recent BIOS version (e.g. 1.8.1) _Enable Legacy Option ROMs_ in _Settings -> General -> Advanced Boot Options_.
> * Switch off secure boot.
> 
> In some cases, _legacy mode_ might be useful to boot on the live USB.
> 
> You may need to boot twice to see the USB in the list of bootloaders, first boot seems to detect the USB bootloader but do not show it.
> 
> On bootloader menu (F12 while booting), select the USB stick.

**Comment by tomvonclef** [comment]
I ended up putting 17.09 on my USB stick, installing that, then upgrading.

**Comment by casidiablo** [comment]
I also had problems with the stable version of the USB boot. It worked with the unstable version.

I then had troubles making the display manager work with the nvidia drivers, but copying @tomvonclef configuration worked:

```nix
  # GPU
  #https://github.com/NixOS/nixpkgs/issues/24711#issuecomment-401630839
  # > 10000 FPS with glmark2
  hardware.nvidia = {
    modesetting.enable = true;
    optimus_prime = {
      enable = true;
      nvidiaBusId = "PCI:1:0:0";
      intelBusId = "PCI:0:2:0";
    };
  };
```

**Comment by Atemu** [comment]
I don't think this is a NixOS issue. If the kernel/mesa don't support your hardware properly, there's little we can do about that. We also can't ship a proprietary driver.
