### ISSUE TITLE
trackpoint not configured at boot

### ISSUE THREAD

**Issue by ashkitten** [NixOS/nixpkgs#56512]
## Issue description

on my t450s, udev rules for the trackpoint device generated by the trackpoint module do not affect its attributes due to the issue mentioned [here](https://wiki.archlinux.org/index.php/TrackPoint#systemd.path_unit) where the files appear too late in the boot process. the activation script seems to also execute too early to take care of this issue, meaning that the trackpoint device does not get configured until a `nixos-rebuild switch`.

this can be solved by adding a systemd path unit and a matching service to watch for the device files and trigger udev to configure them, but you will need to know the path of the device files beforehand. the arch linux wiki says it is usually `/sys/devices/platform/i8042/serio1/serio2/` or `/sys/devices/platform/i8042/serio1/serio3/`, but on my machine it shows up as `/sys/devices/rmi4-00/rmi4-00.fn03/serio2`.

here is what i am using for the moment:

```nix
{
  systemd.paths.trackpoint = {
    pathConfig = {
      PathExists = "/sys/devices/rmi4-00/rmi4-00.fn03/serio2";
      Unit = "trackpoint.service";
    };
  };

  systemd.services.trackpoint.script = ''
    ${config.systemd.package}/bin/udevadm trigger --attr-match=name="${config.hardware.trackpoint.device}"
  '';
}
```

### Steps to reproduce

- in `configuration.nix`, add `hardware.trackpoint = { enable = true; speed = 70; }`
- `nixos-rebuild switch` and reboot

the speed of the trackpoint should still be default

- `nixos-rebuild switch`

the speed of the trackpoint is now correct as configured

- add above snippet to `configuration.nix` (modifying device path for your machine) and reboot

trackpoint should be configured correctly at boot now

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.103, NixOS, 19.09.git.1233c8d (Loris)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre170705.1233c8d9e9b"`
 - channels(ash): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by erictapen** [comment]
Hey, are you aware of [`nixos-hardware`](https://github.com/NixOS/nixos-hardware)? Your solution looks like it's general enough to be submitted there in the [t450s](https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/t450s/default.nix) module.

**Comment by ashkitten** [comment]
thank you, @erictapen
