### ISSUE TITLE
coreutils fails to build with assertion failures in check phase

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#5652]
When trying to update from 84d6debf46a22cf08710e094dce0bfc652f729d3 to 388848fa9f188f25286b62e013609df337174c5c (both completed with green check marks in the `nixos:trunk-combined:tested` hydra job), I'm not being able to build coreutils.

Here is the complete log file (search for `FAIL:`): https://gist.github.com/wizeman/bbef3cec1f8917fbd600

**Comment by wizeman** [comment]
Specifically, all the assertion failures seem to be of the form:
```
test-utimens.h:39: assertion '0 <= utimecmp (BASE "file", &st2, &st1, UTIMECMP_TRUNCATE_SOURCE)' failed
```

**Comment by wizeman** [comment]
This actually seems to be a bug in gnulib.
This thread some discussion: http://comments.gmane.org/gmane.comp.lib.gnulib.bugs/19067

**Comment by wizeman** [comment]
This appears to be a bug in ZFS.
Test case here: https://gist.github.com/wizeman/91d5d0a118fcd179119f

**Comment by wizeman** [comment]
Since this is not a bug in NixOS itself, I'm going to close this.

**Comment by vcunat** [comment]
I think it's good to apply patches to fix/avoid filesystem-dependent tests. Recently I also encountered some test problems with btrfs (about holey files IIRC).

**Comment by wizeman** [comment]
Ok, when there is an official patch for ZFS I will apply it.
