### ISSUE TITLE
fusermount suid wrapper not in PATH in builds

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#5654]
I'm trying to package the tup build system, which uses FUSE to hook filesystem accesses. My current efforts are at https://github.com/Ralith/nixpkgs/tree/tup .

After bootstrapping, the tup build process invokes the bootstrapped binary to do a complete build of itself. As per its normal operation, it attempts to mount a FUSE filesystem. Since fusermount is not suid, this is impossible, and the build fails.

**Comment by Ralith** [comment]
I've came up with a satisfactory workaround for my use case in #5720 . It still seems like this problem shouldn't arise, but it's no longer a major obstacle.

**Comment by cstrahan** [comment]
Yeah, we don't allow for installing suid programs in the nix store. I just pulled #5720 - is this good to close?

**Comment by Ralith** [comment]
I no longer have a pressing need for a solution, but my workaround is definitely a compromise. As far as I can tell, this issue still represents a limitation of nix that isn't strictly necessary. There exists a whitelist of suid-safe programs which is used to make them available in a normal NixOS environment, right? Is there any reason that same whitelist couldn't be used to provide suid wrappers in a build environment in the same manner?

**Comment by lethalman** [comment]
I think this is more of a linux issue. If user x has mounted a filesystem she should be able to umount without the need of suid. Anyway, apart that, that list of suid-safe programs makes things very hard from a trusting perspective. The problems are: where to define such a list and who defines such a list, and who takes care of ensuring every new version of that suid program is safe. Etc. etc.

**Comment by Ralith** [comment]
The problem is mounting a filesystem in the first place. Whatever difficulties the whitelist may represent, it does already exist and is used for a similar purpose.

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by Ralith** [comment]
As far as I know this hasn't been fixed, but I haven't been watching closely, as I no longer personally need it. Whether it should be, and how exactly, seem to be a not totally clear design concern.

**Comment by Profpatsch** [comment]
I suggest we close, we should try to avoid suid at all costs. nix will never allow suid bits in the store, since it’s a security risk (and whitelisting is just a workaround of a bad design).
