### ISSUE TITLE
Make it easy for nix-copy-closure copy all contents of /nix/store

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nixpkgs#56574]
Currently in order to copy all contents of my `/nix/store` to another machine I have to do a clumsy:
```
find /nix/store/ -mindepth 1 -maxdepth 1 -not -name '.links' | \
  xargs nix-copy-closure --to user@host.example.org
```
Something like a special `--all` or positional `all` argument to copy all contents of the store would make things much simpler. I'm just guessing but this is probably the main use case of `nix-copy-closure`.

**Comment by FRidh** [comment]
`nix-copy-closure` has been replaced by the `nix copy` command, and what you're looking for exists there: `nix copy --all`.
