### ISSUE TITLE
gnutar in the stdenv links against impure frameworks on darwin

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#56591]
## Issue description

In sandbox mode on Darwin, unpacking sources with `tar` gives the following error:

```
unpacking sources
unpacking source archive /nix/store/13ajwrwf4jwnfmki5xdhcyqi7xih6cd2-readline-7.0.tar.gz
dyld: Library not loaded: @rpath/CoreFoundation.framework/Versions/A/CoreFoundation
  Referenced from: /nix/store/64v13d0ggyw7gy0aym562xnrcvg97vs5-gnutar-1.31/bin/tar
  Reason: no suitable image found.  Did find:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation: file system sandbox blocked stat()
/nix/store/qi0rhf1l808n0aqrmlfqbkniyys838dq-stdenv-darwin/setup: line 842: 91524 Abort trap: 6           tar xf "$fn"
```

### Steps to reproduce

Build any package in the sandbox, e.g:

```
% nix-shell -p curl
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.3`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.1`
 - channels(smaret): `"nixpkgs-19.03pre170546.0f43790d2ce"`
 - nixpkgs: `/nix/store/p7z0k1cpakbsz71qsjxv8k7scd7ba324-master.tar.gz`

**Comment by smaret** [comment]
@matthewbauer @LnL7 Can you reproduce this?

**Comment by LnL7** [comment]
Yes, the way impure system frameworks currently work breaks with sandboxing. Anything with impure runtime dependencies will break. I've been using a slightly more relaxed sandbox for a while which avoids this issue.

```
extra-sandbox-paths = /System/Library/Frameworks /System/Library/PrivateFrameworks /usr/lib /private/tmp /private/var/tmp /usr/bin/env
```

However this particular case shouldn't be using impure frameworks at all, tar from the stdenv doesn't link against swift-corefoundation for some reason.

```bash
# pkgs.gnutar
$ otool -l /nix/store/pcqwzk22fsf4c90fhc5iwayqkhwy6aba-gnutar-1.31/bin/tar
Load command 15
          cmd LC_RPATH
      cmdsize 96
         path /nix/store/mnr82qqf4pkwbvzpvkzp9lcxb6f0b456-swift-corefoundation/Library/Frameworks (offset 12)
```
```bash
# pkgs.stdenv.__bootPackages.gnutar
$ otool -l /nix/store/64v13d0ggyw7gy0aym562xnrcvg97vs5-gnutar-1.31/bin/tar
 
```

**Comment by matthewbauer** [comment]
Yeah it shouldn't need CF at all. Can you try this patch:

```
diff --git a/pkgs/tools/archivers/gnutar/default.nix b/pkgs/tools/archivers/gnutar/default.nix
index a6f5052ad08..d3fbb02f122 100644
--- a/pkgs/tools/archivers/gnutar/default.nix
+++ b/pkgs/tools/archivers/gnutar/default.nix
@@ -13,6 +13,7 @@ stdenv.mkDerivation rec {
   configureFlags = stdenv.lib.optionals stdenv.isDarwin [
     "gt_cv_func_CFPreferencesCopyAppValue=no"
     "gt_cv_func_CFLocaleCopyCurrent=no"
+    "gt_cv_func_CFLocaleCopyPreferredLanguages=no"
   ];
 
   # gnutar tries to call into gettext between `fork` and `exec`,
```

**Comment by LnL7** [comment]
Oh, well no CoreFoundation is even better. 😄

**Comment by matthewbauer** [comment]
Yeah for reference here is the commit that adds it:

https://github.com/coreutils/gnulib/commit/36d719cb8d00ef417278a70c1cee37e00fc61a17

Maybe we should set it everywhere? Not sure how important these locales are.

**Comment by smaret** [comment]
> Can you try this patch:

@matthewbauer Your patch fixes this issue, thanks! Can you apply it to nixpkgs?

**Comment by matthewbauer** [comment]
It's in this pr for now: https://github.com/NixOS/nixpkgs/pull/56744

We can pull it out if that one gets stalled though.
