### ISSUE TITLE
Setting buildMachines without distributedBuilds = true should throw an error

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#56593]
## Issue description

This surprised me when I set ```buildMachines``` to some local machines but no builders were being detected. This was very weird because /etc/nix/machines was generated correctly. Apparently, you also need to set ```distributedBuilds = true``` otherwise Nix won't pick up on /etc/nix/machines. Even if this is expected behavior, it should at least throw an error when you set ```buildMachines``` but not ```distributedBuilds = true```.

/cc @edolstra

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by xaverdh** [comment]
Correct me if I am misunderstanding.
Doesn't it make sense to have a simple on/off switch for using the builders?
(e.g. if something goes wrong, you don't have to comment out all the builders)

**Comment by hyperfekt** [comment]
If that change is made we lose the ability to use the module to specify build machines but only enable them when wished by setting the builders parameter to.
