### ISSUE TITLE
ibus-table needs gsettings

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#56621]
## Issue description

Input methods based on `ibus-table` do not work as of 1a8c98fe5c6f425ea1ffc50c7a821e1d5dba51bf, at least on my machine as it is now. Upstream, I think the change comes from [this commit](https://github.com/mike-fabian/ibus-table/commit/f9195f877c5212fef0dfa446acb328c45ba5852b), which made `ibus-table` start using `gsettings`. Other IBus input methods still work (mozc, hangul, Anthy).

It feels as if this should have an easy solution amounting to “do what worked for other packages using `gsettings`”, but I can't work out what it is that they do that makes them work. It's also believable that `install-data-hook` from `Makefile.am` is not being run.

### Steps to reproduce

1) `$ ibus-daemon -rxv`
```

(ibus-dconf:2207): dconf-WARNING **: 00:44:04.045: unable to open named profile (ibus): using the null configuration.

(ibus-ui-gtk3:2208): IBUS-WARNING **: 00:44:04.070: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:2208): IBUS-WARNING **: 00:44:04.140: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:2208): Gdk-CRITICAL **: 00:44:04.213: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```
2) Switch to an `ibus-table`-base input method (example: `ipa-x-sampa` from `ibus-table-others`).

Then, the input method is not changed, and the rest of the output is:
```
(ibus-ui-gtk3:2208): IBUS-WARNING **: 00:44:35.000: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: GDBus.Error:org.freedesktop.DBus.Error.Failed: Cannot find engine table:ipa-x-sampa

(ibus-ui-gtk3:2208): IBUS-WARNING **: 00:44:35.000: panel.vala:1064: Switch engine to table:ipa-x-sampa failed.
```

Alternatively:

1) `$ibus-setup`
2) Try to open the preferences for an `ibus-table`-based input method.

No preferences are shown. The following error message is printed.

```
(ibus-setup-table:3479): GLib-GIO-ERROR **: 00:51:41.715: Settings schema 'org.freedesktop.ibus.engine.table' is not installed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.102, NixOS, 19.03.git.2a81ece (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `""`
 - nixpkgs: `/home/james/nixpkgs`

**Comment by laMudri** [comment]
So, adding `wrapGAppsHook` to `nativeBuildInputs` stops the `ibus-setup` error message, but preference dialogs still do not show and all of the problems with actually using `ibus-table` remain.

**Comment by jtojnar** [comment]
How did you install and activate the input method?

    i18n.inputMethod.enabled = "ibus";
    i18n.inputMethod.ibus.engines = with pkgs.ibus-engines; [ table ];

does not seem to be enough.

**Comment by laMudri** [comment]
Change `[ table ]` to `[ table table-others ]` (ibus-table acts like a framework within a framework, and `table-others` provides some actual input methods using it). Then, use `ibus-setup` -> Input Method -> Add -> More... -> Others -> IPA-X-SAMPA (and maybe another to see the switching behaviour). Then, switch using the key combination from the preferences (I forget what the default is; maybe Ctrl-space).

**Comment by laMudri** [comment]
@jtojnar Have you managed to reproduce this problem?

**Comment by jtojnar** [comment]
I can confirm your observations in https://github.com/NixOS/nixpkgs/issues/56621#issuecomment-485086623

Maybe this could be the culprit:

```ShellSession
$ cat ~/.cache/ibus-table/setup-debug.log 
--- 2019-04-29: 23:35:41 ---
Cannot open database file /usr/share/ibus-table/tables/ipa-x-sampa.db
Traceback (most recent call last):
  File "/nix/store/361kyblf3b0pgrvj56w0i15vjajql123-ibus-table-1.9.21/share/ibus-table/setup/../engine/tabsqlitedb.py", line 158, in __init__
    self.db.execute('PRAGMA encoding = "UTF-8";')
AttributeError: 'TabSqliteDb' object has no attribute 'db'
Error while initializing database.
Traceback (most recent call last):
  File "main.py", line 570, in <module>
    main()
  File "main.py", line 563, in main
    PreferencesDialog().run()
  File "main.py", line 554, in run
    self.get_default_options_from_database()
  File "main.py", line 196, in get_default_options_from_database
    create_database=False)
  File "/nix/store/361kyblf3b0pgrvj56w0i15vjajql123-ibus-table-1.9.21/share/ibus-table/setup/../engine/tabsqlitedb.py", line 171, in __init__
    self.db.executescript(
AttributeError: 'TabSqliteDb' object has no attribute 'db'
```

**Comment by jtojnar** [comment]
```
$ rg /usr/share result
result/share/ibus-table/engine/ibus_table_location.py
55:        IBUS_TABLE_LOCATION['data'] = "/usr/share/ibus-table/"

result/share/ibus-table/engine/factory.py
71:                        db_dir = "/usr/share/ibus-table/tables"
```

**Comment by jtojnar** [comment]
```ShellSession
$ cat ~/.cache/ibus-table/debug.log
--- 2019-04-29: 23:51:37 ---
Compatible database /home/jtojnar/.local/share/ibus-table/tables/ipa-x-sampa-user.db found.
Connect to the database /home/jtojnar/.local/share/ibus-table/tables/ipa-x-sampa-user.db.
failed to create engine ipa-x-sampa
Traceback (most recent call last):
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/factory.py", line 84, in do_create_engine
    self.dbdict[engine_name])
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 1545, in __init__
    self.db)
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 358, in __init__
    orientation=self._orientation)
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
    round=True)
TypeError: gobject `IBusLookupTable' doesn't support property `page_size'
Traceback (most recent call last):
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/factory.py", line 84, in do_create_engine
    self.dbdict[engine_name])
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 1545, in __init__
    self.db)
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 358, in __init__
    orientation=self._orientation)
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
    round=True)
TypeError: gobject `IBusLookupTable' doesn't support property `page_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ipq8rj2ppbl9x9idxl0saiy8ikh9gvhd-ibus-table-1.9.21/share/ibus-table/engine/factory.py", line 92, in do_create_engine
    raise Exception("Cannot create engine %s" %engine_name)
Exception: Cannot create engine ipa-x-sampa
```

**Comment by laMudri** [comment]
I've found what appears to be a solution, but it's in some sense weird. Looking at other input methods, they seem to use `IBus.LookupTable.new()` rather than `IBus.LookupTable()`. Replacing the latter with the former on [line 407 of `$out/share/ibus-table/engine/table.py`](https://github.com/mike-fabian/ibus-table/blob/master/engine/table.py#L406) seems to fix the issue. I have no idea, though, why `ibus-table` isn't broken on other platforms.

[Here](https://gist.github.com/laMudri/4712bfe20985c0f3636e21f35911ad2e) is the new package description.
