### ISSUE TITLE
kgpg segfaults when clicking on "Configure KGpg..." in the menu

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#5664]
Hi.

I had this issue with a fresh nixos installation. I reported the [issue upstream](https://bugs.kde.org/show_bug.cgi?id=342634), it was marked as duplicate of a already solved issue. My solution was to add the unstable channel and install kgpg from there, which solved the whole issue.

I'd like to back-port the `nixos-unstable` version of `kgpg` to the `nixos-14.12` branch, but I don't know how, as I'm a newbie here. If you guys would guide me, I'd love to do it, though!

**Comment by Phreedom** [comment]
I have just pushed the whole kde4 update

**Comment by matthiasbeyer** [comment]
You mean to the nixos-14.12 channel? If so, this issue can be closed (I can test this if you want me to, and if you tell me how to - is removing the unstable channel enough?)
