### ISSUE TITLE
multimc: directory heirarchy is confusing

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#56684]
## Issue description
As you can see from https://github.com/NixOS/nixpkgs/pull/55701#issuecomment-464402622
somehow `.so` libs are installed to `bin/` and a `jars` directory as well.

Not sure if this is intentional, but it isn't correct.

Note I'm also assuming that the jars in `bin` are meant for internal use.

**Comment by globin** [comment]
closed by #65550
