### ISSUE TITLE
Update afuse

### ISSUE THREAD

**Issue by StijnDW** [NixOS/nixpkgs#5670]
Regarding the following package:
nixpkgs/pkgs/os-specific/linux/afuse/default.nix

The homepage of afuse is now seems to be:
https://github.com/pcarrier/afuse
The latest version is 0.4.1

**Comment by ryantm** [comment]
http://sourceforge.net/projects/afuse/?source=navbar says "Development is no longer proceeding on SourceForge and has moved to https://github.com/pcarrier/afuse ."

**Comment by ryantm** [comment]
@StijnDW I updated the build configuration to be afuse 0.4.1 . Can you please test my update?

**Comment by StijnDW** [comment]
Hi, sorry for the late reply.
Your update seems to work perfectly, thank you.
