### ISSUE TITLE
Terraform out of date

### ISSUE THREAD

**Issue by gurjeet** [NixOS/nixpkgs#56762]
## Issue description
`terraform version` reports it is out of date.

```
$ terraform version
Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.11. You can update by downloading from www.terraform.io/downloads.html
```

/cc @jgeerds @zimbatm @peterhoeg @kalbasit, since you guys are listed as maintainers on the package.
### Steps to reproduce

`terraform version`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(gurjeetsingh): `"nixpkgs-19.03pre154774.cefd0f7e86b"`
 - nixpkgs: `/Users/gurjeetsingh/.nix-defexpr/channels/nixpkgs`
```

**Comment by kalbasit** [comment]
it was already updated [on master](https://github.com/NixOS/nixpkgs/blob/16c74f7eea1f17aad67d8b023e98709c56a72ae4/pkgs/applications/networking/cluster/terraform/default.nix#L91) in fb66e2d7926eae8765b3dbbf11b385112174198b. Try running `nix-channel --update` to update your channels.
