### ISSUE TITLE
Request for new package: vimpager

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#56768]
## Issue description

vimpager is a project to use vim as a pager. As can be seen by the repository, it's quite popular. Useful for when you want to do mouseless copy from the terminal.

https://github.com/rkitover/vimpager

**Comment by teto** [comment]
did you compare with https://github.com/lucc/nvimpager ? Any winner ?

**Comment by CMCDragonkai** [comment]
I don't use neovim so it's strange for me to get a pager to use neovim. But I haven't compared.

**Comment by bemeurer** [comment]
nvimpager and vimpager are separate and distinct projects. I use both depending on the box. It'd be nice to add both to nixpkgs.
