### ISSUE TITLE
nixpkgs channel binary-cache-url still plain HTTP

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#5677]
[cache.nixos.org] now supports HTTPS under its own name, and the
`nixos` channels (except `nixos-13.10`) now list their
`binary-cache-url`s as <https://cache.nixos.org>:

    % echo $(curl -Ls 'https://nixos.org/channels/nixos-14.04/binary-cache-url')
    https://cache.nixos.org
    % echo $(curl -Ls 'https://nixos.org/channels/nixos-14.12/binary-cache-url')
    https://cache.nixos.org
    % echo $(curl -Ls 'https://nixos.org/channels/nixos-unstable/binary-cache-url')
    https://cache.nixos.org

However, the `nixpkgs-unstable` channel — which seems to be the
default for non-NixOS Nix installations — still uses unsecured HTTP
for its `binary-cache-url`:

    % echo $(curl -Ls 'https://nixos.org/channels/nixpkgs-unstable/binary-cache-url')
    http://cache.nixos.org

I request that
<https://nixos.org/channels/nixpkgs-unstable/binary-cache-url> be, if
possible, updated to use HTTPS.

[cache.nixos.org]: <https://cache.nixos.org>

**Comment by iElectric** [comment]
cc @edolstra

**Comment by edolstra** [comment]
Should be fixed on the next channel update.
