### ISSUE TITLE
rapid-photo-downloader / rawkit: fails to build

### ISSUE THREAD

**Issue by callahad** [NixOS/nixpkgs#56815]
## Issue description

Rapid Photo Downloader depends on the Python library rawkit for bindings to libraw.

Rawkit fails to build due to test failures.

### Steps to reproduce

1. nix-shell -p rapid-photo-downloader

Rawkit's check phase blows up with:

```
[...]
tests/unit/options_test.py:62: RuntimeError
===================== 1 failed, 52 passed in 0.30 seconds ======================
builder for '/nix/store/zqgarbyc2f930h3gdw438zpd87nn6abv-python3.7-rawkit-0.6.0.drv' failed with exit code 1
cannot build derivation '/nix/store/z6hljn124mjnry4iigja9mcj4jfjwpi4-rapid-photo-downloader-0.9.13.drv': 1 dependencies couldn't be built
error: build of '/nix/store/z6hljn124mjnry4iigja9mcj4jfjwpi4-rapid-photo-downloader-0.9.13.drv' failed
```

## Proposed Fix

Rawkit is unmaintained, but has merged fixes into its master branch since its last release.

Using the current `master` branch of https://github.com/photoshell/rawkit works.

Note, rawkit's master branch also requires adding the Python package `numpy` to `buildInputs`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.13, NixOS, 19.09.git.80812af (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre170705.1233c8d9e9b"`
 - channels(dan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
We can either use the master branch or apply https://github.com/photoshell/rawkit/commit/663e90afa835d398aedd782c87b8cd0bff64bc9f as a patch.

**Comment by callahad** [comment]
No preference on my end; pulling in that commit as a patch would keep things smaller by avoiding NumPy...

**Comment by dotlambda** [comment]
I fixed rawkit in 35848d284b4d2ff8b5ebbb788104d2c170f76578.
However, rapid-photo-downloader still fails, probably due to the changes made in https://github.com/NixOS/nixpkgs/pull/54182. I do not currently have time to fix this.
cc @jfrankenau

**Comment by callahad** [comment]
Thanks! Moving necessary `buildInputs` one by one into `nativeBuildInputs` results in this patch, which build and runs:

```diff
diff --git a/pkgs/applications/graphics/rapid-photo-downloader/default.nix b/pkgs/applications/graphics/rapid-photo-downloader/default.nix
index 36087aa84bb..718246109c1 100644
--- a/pkgs/applications/graphics/rapid-photo-downloader/default.nix
+++ b/pkgs/applications/graphics/rapid-photo-downloader/default.nix
@@ -1,7 +1,7 @@
 { stdenv, fetchurl, python3Packages
 , file, intltool, gobject-introspection, libgudev
-, udisks, glib, gnome3, gst_all_1, libnotify
-, exiv2, exiftool, qt5, gdk_pixbuf
+, udisks, gexiv2, gst_all_1, libnotify
+, exiftool, gdk_pixbuf
 }:
 
 python3Packages.buildPythonApplication rec {
@@ -23,20 +23,20 @@ python3Packages.buildPythonApplication rec {
       --replace "import problemnotification" "import raphodo.problemnotification"
   '';
 
-  nativeBuildInputs = [ file intltool gobject-introspection ];
-
-  buildInputs = [
-    libgudev
-    udisks
-    glib
-    gnome3.gexiv2
-    gst_all_1.gstreamer
-    libnotify
-    exiv2
+  nativeBuildInputs = [
     exiftool
-    qt5.qtimageformats
+    file
     gdk_pixbuf
-  ] ++ (with python3Packages; [
+    gexiv2
+    gobject-introspection
+    gst_all_1.gstreamer
+    intltool
+    libgudev
+    libnotify
+    udisks
+  ];
+
+  buildInputs = with python3Packages; [
     pyqt5
     pygobject3
     gphoto2
@@ -54,7 +54,7 @@ python3Packages.buildPythonApplication rec {
     requests
     colorlog
     pyprind
-  ]);
+  ];
 
   makeWrapperArgs = [
     "--set GI_TYPELIB_PATH \"$GI_TYPELIB_PATH\""
```

*However* on launch Rapid Photo Downloader complains:

```
ERROR    pymediainfo is installed, but the library libmediainfo appears to be missing
```

...still working on figuring out that one.

**Comment by dotlambda** [comment]
> _However_ on launch Rapid Photo Downloader complains:
> 
> ```
> ERROR    pymediainfo is installed, but the library libmediainfo appears to be missing
> ```
> ...still working on figuring out that one.

That might be due to https://github.com/NixOS/nixpkgs/commit/4c0f0a014b067e47d4d940aee470fb9397ee8d13.

**Comment by dotlambda** [comment]
Btw, Python dependencies should be put into `propagatedBuildInputs`.
