### ISSUE TITLE
cmus: MPRIS is disabled

### ISSUE THREAD

**Issue by callahad** [NixOS/nixpkgs#56813]
## Issue description

cmus supports remote control via MPRIS, but that support is disabled on NixOS because systemd is not present as a native build input.

### Steps to reproduce

1. Run cmus
2. Play a song
3. Notice that there's no indication of the current song in, e.g., the GNOME notification drawer.

### Workaround

The following in an overlay works as expected:

```
cmus = super.cmus.overrideAttrs (oldAttrs: {
  nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ self.systemd ];
});
```

**Comment by aanderse** [comment]
@callahad I've made the same mistake on nativeBuildInputs before and was told this:
> Dependencies that are run during build should go to nativeBuildInputs, runtime dependencies go to buildInputs

**Comment by callahad** [comment]
I wasn't entirely sure on `buildInputs` vs `nativeBuildInputs` in this case because MPRIS is an optional runtime feature, but it's only available if `systemd/sd-bus.h` is there at compile time.

If I understand things correctly, putting systemd into `nativeBuildInputs` results in something like: "We aren't forcing people to run systemd, but if it's already there, cmus can take advantage of it to support MPRIS."

Does that make sense?

**Comment by aanderse** [comment]
From the nixpkgs manual under the nativeBuildInputs:

> But since these packages only are guaranteed to be able to run then (at build time), they shouldn't persist as run-time dependencies.

We want systemd as a runtime dependency so this states we should not use nativeBuildInputs. I added the "(at build time)" for context.

So why does your code work? The very next sentence might explain that:

> This isn't currently enforced, but could be in the future.

Make sense?

**Comment by aanderse** [comment]
@callahad the PR to add support was merged so this issue can be closed now.

**Comment by callahad** [comment]
Oh, hey, thanks! I thought I was subscribed to that PR, but apparently not :-)
