### ISSUE TITLE
NixOS 19.03 manual does not note changes to kernel configuration

### ISSUE THREAD

**Issue by CrazedProgrammer** [NixOS/nixpkgs#56827]
## Issue description
I was going to test out NixOS 19.03 (`nixos-19.03`) after reading the release notes.
I stumbled upon an issue similar to https://github.com/NixOS/nixpkgs/issues/55415.
This seems to be a backwards-incompatible change, and is not noted in the release notes for 19.03.

### Steps to reproduce
Same as https://github.com/NixOS/nixpkgs/issues/55415.

The release notes in the manual: https://github.com/NixOS/nixpkgs/blob/768336a74b95f24c7b33daf8905bd822be03c78e/nixos/doc/manual/release-notes/rl-1903.xml
Search for "linux", "kernel" or "structuredExtraConfig" and find nothing.

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.26, NixOS, 18.09.2292.4c0be408155 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03.170684.07e2b59812d, nixos-unstable-19.09pre171582.26d8a8c0eb2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by teto** [comment]
There is not a definite way yet to configure the `structuredExtraConfig` https://github.com/NixOS/nixpkgs/pull/55755 so I didn't feel like documenting it as:
- it's a new mechanism on top of extraConfig
- I would like to make some progress on https://github.com/NixOS/nixpkgs/issues/55415, which may influence the way we configure the `structuredExtraConfig`.

Meanwhile you can have a look at pkgs/os-specific/linux/kernel/hardened-config.nix or my supermessy repo https://github.com/teto/home/blob/1b60389b9f9e097a2fc213be512da0b528dcde57/nixpkgs/overlays/kernels.nix#L48

**Comment by CrazedProgrammer** [comment]
I understand, thanks for the response. Now that I look at it, the previous incompatible changes in 18.09 (extraConfig -> structuredExtraConfig) weren't mentioned in the release notes for 18.09 either.

This is how I got it working again in my config, in case anyone's interested: https://github.com/CrazedProgrammer/nix/commit/2d13a24bdb0ba2cf346d9fb57d435c0492b87cf7.

**Comment by matthewbauer** [comment]
I think we definitely want to put it in the release notes. It's kind of on the edge between Nixpkgs and NixOS but might as well make it available in NixOS release notes.

**Comment by teto** [comment]
My idea was to  expose the structured config and get rid of extraConfig as strings after https://github.com/NixOS/nixpkgs/pull/70157 so that I can finally document the thing but it's harder than I had anticipated...
