### ISSUE TITLE
Latest sha256 for git-annex appears to be out of date

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#56836]
I see the following when trying to update `git-annex` today:

```
Vulcan ~/Products $ nix build --option build-use-substitutes false darwin.pkgs.gitAndTools.git-annex
hash mismatch in fixed-output derivation '/nix/store/r71i5anr7k7514rq0rzx8bjdybjfj5sa-git-annex-7.20190219-src':
  wanted: sha256:1v2v6cwy957y5rgclb66ia7bl5j5mx291s3lh2swa39q3420m6v0
  got:    sha256:00k31p06pmzsd1gm3yw6b6sj06q9cj9cccxhqjqpzgyf1y5mjv2a
cannot build derivation '/nix/store/6c3mcr2sznbpdjb59a72vni5q3k3lmnx-git-annex-7.20190219.drv': 1 dependencies couldn't be built
```

@peti Is it safe to just update, or is this possibly a Darwin-related thing?

**Comment by peti** [comment]
If this problem still exists in recent versions of the master branch, then it's appropriate to update the sha265 value in the configuration-common.nix. this phenomenon has nothing to do with gammon. It's a consequence of the fact, that we cannot use the source tarball for git-annex from Hackage, so we cannot auto detect the appropriate hash value easily when an update comes out.

**Comment by jwiegley** [comment]
I ran into the problem on the unstable channel.

**Comment by peti** [comment]
The SHA mismatch does not exist in `master`-
