### ISSUE TITLE
Standard library headers are not found with ccls

### ISSUE THREAD

**Issue by vlaci** [NixOS/nixpkgs#56841]
## Issue description
I am unable to get standard library header files to resolve in ccls.

### Steps to reproduce
I have installed ccls from unstable and configured neovim (LanguageClient-neovim) to use it. Language server starts fine and diagnostics work. However system includes are unresolved as can be seen on the screenshot.
![image](https://user-images.githubusercontent.com/1771332/53759147-ee590d80-3ebf-11e9-8059-2198f2bc451f.png)
ccls is running with the following arguments (from ps output):
```
/nix/store/bz7y1yvg1a9m46cc6rwiz5j6w49p975d-ccls-0.20181225.8/bin/ccls --init={"clang":{"extraArgs": ["-isystem", "/nix/store/l3cyb00caxmrzdb538lar13piq0xw1nv-glibc-2.27-dev/include", "-isystem", "/nix/store/77xiz4g7b7diby4hc75rj3ain0w5kf0c-libc++-7.0.1/include/c++/v1", "-isystem", "/nix/store/2idc1cgwsk820q6fpfbqyhnpx228dy4s-compiler-rt-5.0.2-dev/include", "-isystem", "/nix/store/2idc1cgwsk820q6fpfbqyhnpx228dy4s-compiler-rt-5.0.2-dev/include"]}}
```
I got exactly the same result in Emacs (lsp-mode).

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.19, NixOS, 18.09.2292.4c0be408155 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2292.4c0be408155, home-manager-18.09, mozilla, nixos-unstable-19.03pre169108.36f31600749, blox, nixos-hardware"`
 - channels(vlaci): `"nixos-unstable-19.03pre169108.36f31600749, mozilla"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vlaci** [comment]
It works fine after uodating to `19.03beta171516.52565a88187`

**Comment by HankelBao** [comment]
Hi! I am on current nixos-unstable channel and encountered the same problem.
What extra settings did you do except for installing ccls from nix-env?

**Comment by vlaci** [comment]
I have not done anything other then adding a package override to use ccls from unstable.
