### ISSUE TITLE
texlive.combine: Allow specification of dependencies

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#56840]
## Issue description

It is possible to install a custom subset of the texlive distribution using `texlive.combine`. But currently dependencies between LaTeX classes don't seem to be taken into account.

I particularly ran into it with `biblatex`, which also needs `logreq` as its dependency. But the latter class wasn't installed, causing my LaTeX document builds to fail. I had to mention `logreq` explicitly as an argument to `texlive.combin` (see example below).

After seeing that no texlive class in `pkgs/tools/typesetting/tex/texlive/pkgs.nix` specifies any dependencies I suspect that dependency resolution is currently not supported by `texlive.combine`.

### Steps to reproduce

1. Add the following to your environment (in my case using home-manager):
  ```nix
  (texlive.combine {
    inherit (texlive)
    scheme-medium
    biblatex;
  })
  ```
2. Try compiling a LaTeX document using the biblatex class (if needed I can create a minimal sample document). You get an error message about `logreq.sty` not being found.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.26, NixOS, 18.09.2274.dc4823f6032 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2274.dc4823f6032, nixos-unstable-19.09pre170705.1233c8d9e9b"`
 - channels(user): `"home-manager-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
It seems like texlive doesn't provide information about the dependencies of individual packages. I also don't think any other distro packages texlive at a such small granularity as we do, so it might be that nobody else had to solve this problem before.

**Comment by xeji** [comment]
In texlive the user has to install dependencies of individual packages manually  unless they use one of the predefined schemes.

I see no practical way to add this feature until texlive provides full dependency information for each package in an easily parseable way. And even then I'm not quite sure it would be worth the effort.

So I propose to close this issue as "won't fix".

**Comment by JohnAZoidberg** [comment]
> It seems like texlive doesn't provide information about the dependencies of individual packages. I also don't think any other distro packages texlive at a such small granularity as we do, so it might be that nobody else had to solve this problem before.

Gentoo does that even for non-Tex dependencies. For example the `minted` Tex package requires the Python dependency `minted` and they include this in their build file: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-tex/minted/minted-2.4.1.ebuild#n19

I think this would be quite useful. Shouldn't be that hard to maintain - I don't expect Tex packages to change their dependencies quite often.

**Comment by veprbl** [comment]
We are looking to add external dependencies for some of the texlive packages (#55933, #59537). These special cases should be relatively rare. At the same time there will be much more interdependencies between the texlive packages. We are talking thousands of packages here. Where do we get that information from?

**Comment by veprbl** [comment]
There is a current upstream discussion about this: https://tug.org/pipermail/tex-live/2019-November/044274.html
Whatever dependencies that will be added to upstream, we are going to be able to pick up on next update automatically since we parse their tlpdb file. We can pick those up even sooner by making an override at
https://github.com/NixOS/nixpkgs/blob/2e52f98ddbe9ddd91f65f8df471d84e1e4077bdf/pkgs/tools/typesetting/tex/texlive/default.nix#L39

Also, people who don't mind using XeTeX could try `tectonic` (can be installed from nixpkgs), it does dependency download "on the fly".

**Comment by veprbl** [comment]
Judging by a recent response [1] (read the last paragraph), the upstream is not looking to provide full coverage for dependencies.

[1] https://tug.org/pipermail/tex-live/2019-December/044520.html

**Comment by FRidh** [comment]
Could one not download all packages, and search for `\usepackage`, `\RequirePackage` and `\ProvidesPackage` to build up a tree of tex-dependencies? I suppose one will miss some in case aliases are used.

**Comment by veprbl** [comment]
> Could one not download all packages, and search for `\usepackage`, `\RequirePackage` and `\ProvidesPackage` to build up a tree of tex-dependencies? I suppose one will miss some in case aliases are used.

I suppose that could work. However, there are dependencies that are optional. AFAIK upstream's policy regarding those was to not install and to not specify those. Also, from what I understand, `tectonic` is downloading missing packages on the fly as it compiles the documents. This is not the Nix way, but I thought I would mention.

**Comment by JohnAZoidberg** [comment]
> @AndersonTorres closed this 5 hours ago 

Why?

**Comment by AndersonTorres** [comment]
> > @AndersonTorres closed this 5 hours ago
> 
> Why?

Cleanup. Four months as "wontfix".
