### ISSUE TITLE
Missing man pages for passExtensions packages?

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#56850]
## Issue description

I've added `pass-import`  and other extensions to `pass` by following the example of `pass-otp` in the `aliases.nix` file

https://github.com/NixOS/nixpkgs/blob/9bc5c624e5b6ccf0d7b5acb5b6e75be3ea9115d1/pkgs/top-level/aliases.nix#L222

by adding 

```
pass-custom = pkgs.pass.withExtensions (ext: [ext.pass-audit ext.pass-genphrase ext.pass-update ext.pass-otp ext.pass-import]);
````

to an package overlay in my `home-manager` config.

I can call `pass import` just fine, but running `man pass-import` fails. The man page is referenced at the end of `pass import -h` :

```
(...)
More information may be found in the pass-import(1) man page.
```

The same is likely through for other `passExtensions`, but I haven't checked them.

### Steps to reproduce

- Add `pass-custom = pkgs.pass.withExtensions (ext: [ext.pass-audit ext.pass-genphrase ext.pass-update ext.pass-otp ext.pass-import]);` to an overlay.
- Install `pass-custom`
- Run `pass import -h`
- Run `man pass-import`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.12, NixOS, 19.03.170684.07e2b59812d (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.170684.07e2b59812d, nixos-unstable-19.09pre171582.26d8a8c0eb2, nixpkgs-19.03.170684.07e2b59812d"`
 - nixpkgs: `/home/addy/.nix-defexpr/channels/nixpkgs`

**Comment by Moredread** [comment]
cc-ing the maintainers: @lovek323 @the-kenny @fpletz  @tadfisher @seqizz

**Comment by seqizz** [comment]
Hmm, I realized even my packaged extension has a man page installed, it's not linked to current system's man directory. Do we have a documentation about that? I can scan the extensions and include if documentation is available:

```
~> find /nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/   
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib/password-store
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib/password-store/extensions
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib/password-store/extensions/genphrase-resources
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib/password-store/extensions/genphrase-resources/_phrase.py
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib/password-store/extensions/genphrase-resources/eff_large_wordlist.txt
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/lib/password-store/extensions/genphrase.bash
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/share
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/share/man
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/share/man/man1
/nix/store/nmbfax24yjw97mqh0rrqw1zqphhcc24p-pass-genphrase-0.1/share/man/man1/pass-genphrase.1.gz

```

**Comment by kamidon** [comment]
I tried to look into this a bit. With this in  `environment.systemPackages`:

```
(pass.withExtensions (ext: [  # Base pass secret mgr + extensions
        ext.pass-genphrase # generate memorable passphrases
        ext.pass-import    # import from other password managers
        ext.pass-update    # helpful password change workflow
      ]))
```

Then `man pass-genphrase` gives `No manual entry for pass-genphrase`. However, if I do:

```
nix run nixpkgs.passExtensions.pass-genphrase
```

Then `man pass-genphrase` does show the corresponding manual page.

I then tried adding `passExtensions.pass-genphrase` to my `environment.systemPackages` directly in addition to configuring it as an extension and after switching to the new configuration `man pass-genphrase` also worked.

If my quick attempt to follow the logic in the main `pass` derivation is correct, it uses `buildEnv` to produce a store path that contains all of the files installed by all selected extensions, this is depended on as a `buildInput` so it is available in the main pass derivation, and then that derivation manually links the extensions directory of the `buildEnv` store path into the extensions directory location in the man pass derivation output. 

It makes sense to me that the manual pages and other files of a `buildInput` of a derivation that is in the system environment packages would not themselves be made available in the system environment, so I think the right thing to do here might be for the main pass derivation to also link the man pages of extensions into its own output manual directory, but I have run out of time to try that today.

**Comment by Moredread** [comment]
I agree with your proposed solution for copying man pages in buildEnv (and maybe also checking if we currently missing other files we want to include)

**Comment by kamidon** [comment]
Submitted this: https://github.com/NixOS/nixpkgs/pull/58187

I verified that the only files missing the `password-store` out directory from `pass-extensions-env` were the man pages that this commit links in.

**Comment by Moredread** [comment]
Closing in favor of PR #58187
