### ISSUE TITLE
Dynamic libraries are not linked in ghci when using `nix-shell --run cabal new-repl`

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#56860]
## Issue description
When using a haskell library that has a dynamically linked C dependency, the dependency is not found by ghci.

### Steps to reproduce
Clone [this library](https://github.com/meditans/haskell-z3/tree/show-nix-shell-problem) which contains a functioning `default.nix` and `shell.nix`. Observe the behaviour:

```
$ nix-shell --run "cabal new-repl"         

Build profile: -w ghc-8.6.3 -O1
In order, the following will be built (use -v for more details):
 - z3-4.3 (lib) (ephemeral targets)
Preprocessing library for z3-4.3..
GHCi, version 8.6.3: http://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (libz3.so: cannot open shared object file: No such file or directory)
Whilst trying to load:  (dynamic) z3
Additional directories searched: (none)
cabal: repl failed for z3-4.3.
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.09pre171582.26d8a8c0eb2 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(carlo): `""`
 - channels(root): `"nixos-19.09pre171582.26d8a8c0eb2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cleverca22** [comment]
i suspect the problem is caused by ghci not obeying `NIX_LDFLAGS` and it may need some cc-wrapper like changes done to the ghc wrappers
though i wonder why ghci fails, but ghc (for building with cabal) works

**Comment by matthewbauer** [comment]
I think you need to pass ```--extra-lib-dirs``` and ```--extra-include-dirs``` into new-repl. So something like this:

```
$ nix-shell --run "cabal new-repl --extra-lib-dirs=$(nix-build "<nixpkgs> -A z3.lib)/lib"
```

But, we probably need to properly expose the extra-*-dirs in nix-shell.

**Comment by meditans** [comment]
Thank you @matthewbauer, this command works indeed:
```
nix-shell --run "cabal new-repl --extra-lib-dirs=$(nix-build '<nixpkgs>' -A z3.lib)/lib"
```
How would one properly expose the required directories in nix-shell?

**Comment by matthewbauer** [comment]
They should be put in ```configureFlags``` during a normal build, but it looks like they are missing with shellFor?? I am not very familiar with how shellFor works though, so it may be in some other variable.

/cc @peti @Infinisil @ElvishJerricco

**Comment by Infinisil** [comment]
I just checked, the changes in https://github.com/NixOS/nixpkgs/pull/46453 have nothing to do with this failure, it didn't work before either.

The generic Haskell build seems to add `--extra-lib-dirs` to the `configureFlags`, later to be used by `cabal configure`, which Haskell nix-shell's don't do: https://github.com/NixOS/nixpkgs/blob/6a69ce97506d5a3801418a8872fb73f52efe2b46/pkgs/development/haskell-modules/generic-builder.nix#L286-L288

I guess that's a problem with how Haskell nix-shell's work differently in that they are totally separate from the package itself, so they also don't export the appropriate `configurePhase`, which would solve this problem.

**Comment by ElvishJerricco** [comment]
And in principle, that's a really hard problem, since `shellFor` is designed to work for multiple packages.

**Comment by peti** [comment]
The interactive shell environment does not call `cabal configure` for you. It just gives you an environment in which *you* can call `cabal configure`, so arguably the fact that those libraries are not detected automatically is by design.

**Comment by Infinisil** [comment]
@peti But even `cabal configure` won't be enough, you'll have to pass all the --extra-lib-dirs arguments manually, which would be really painful. If the shell would export a `configurePhase` that contains the appropriate `cabal configure` command to set up a working build environment (and also `configureFlags` while we're at it) that would solve the problem.

**Comment by peti** [comment]
It's not that simple, unfortunately. A `configurePhase` won't help people using `cabal new-build` or `stack` or Autoconf or any number of other schemes one could use to configure additional paths in a build tool.

**Comment by Infinisil** [comment]
@peti Yeah, so `configureFlags` might work better. In any case, we should definitely export at least `configureFlags` to enable stuff like this, even though it won't be perfect.

**Comment by peti** [comment]
Yes, it would be cool if that env variable were set properly. The same flags that work for `cabal configure` also work for `cabal new-build` and `stack build`, if I'm not mistaken, so that would be pretty useful. Of course, the next best thing would  be an alias / function / whatever that writes those settings into a `cabal.project` or `stack.yaml` file, too,  so that users don't have to remember adding that variable to the command line every time. Any such improvement would be welcome.

**Comment by expipiplus1** [comment]
FWIW I use:

`cabal configure $(tr <<< "$NIX_LDFLAGS" ' ' '\n' | sed  's|-L|--extra-lib-dirs=|;t;d')`

**Comment by asheshambasta** [comment]
This is still an issue, not sure why this issue has been closed though.
