### ISSUE TITLE
wireshark crashes on closing of window

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#56876]
## Issue description
wireshark crashes on closing of window

### Steps to reproduce
1. Add user foo to group wireshark
2. Run `wireshark` # in a shell as user foo
3. Use mouse to close window
4. See "segmentation fault" output on shell

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.git.e542fc2 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by teto** [comment]
could it be a wireshark bug ? don't happen on unstable. You could try https://github.com/NixOS/nixpkgs/pull/56776

**Comment by memberbetty** [comment]
It correlated with the broken screen saver bug I opened and closed recently. I can't reproduce it anymore.

**Comment by teto** [comment]
Maybe you can close then ? wireshark 3 was merged.

**Comment by teto** [comment]
I use wireshark regularly and didn't have the bug. I believe it might be sthg else. Feel free to reopen.
