### ISSUE TITLE
smartgithg: install_freedesktop_items.sh: Permission denied

### ISSUE THREAD

**Issue by baracoder** [NixOS/nixpkgs#56878]
## Issue description

The same build worked before. Now the bundled script is not executable. I would know a workaround, but I would like to know why it stopped working.

I will try to bisect it when I have time today

### Steps to reproduce

1. Checkout master branch of nixpkgs
2. Try to build `smartgithg`
```
nix-build /path/to/nixpkgs -A smartgithg --arg config '{ allowUnfree = true; }'
...
/nix/store/63karsgdg7fm3q0if4zfd7apbd8ac1ci-stdenv-linux/setup: line 1299: /nix/store/kzlgjv3xscc9g6ix38lflh1gz6hghvhn-install_freedesktop_items.sh: Permission denied
builder for '/nix/store/49f6csj2dyasslg9fxrkb2slpf1ay8xc-smartgithg-18.2.4.drv' failed with exit code 126
error: build of '/nix/store/49f6csj2dyasslg9fxrkb2slpf1ay8xc-smartgithg-18.2.4.drv' failed
```
The script is executable:
```
ls -l ./pkgs/applications/version-management/smartgithg
total 8
-rw-r--r-- 1 bara bara 1910 Mar  5 10:40 default.nix
-rwxr-xr-x 1 bara bara  524 Mar  5 10:40 install_freedesktop_items.sh
```

The stored file isn't
```
ls -l /nix/store/kzlgjv3xscc9g6ix38lflh1gz6hghvhn-install_freedesktop_items.sh
-r--r--r-- 1 root root 582 Jan  1  1970 /nix/store/kzlgjv3xscc9g6ix38lflh1gz6hghvhn-install_freedesktop_items.sh
```

The file is added like this
```
    install_freedesktop_items = substituteAll {
      inherit (stdenv) shell;
      src = ./install_freedesktop_items.sh;
    };

```
and then referenced in the build script
```
    ${install_freedesktop_items} "${pkg_path}/bin" "$out"
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.7, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(bara): `""`
 - channels(root): `"nixos-19.03pre169108.36f31600749, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by baracoder** [comment]
Result of bisect:
```
# only skipped commits left to test
# possible first bad commit: [d531da6f8ae7a8dab806bcd3211cd84d2d189d24] Merge pull request #54094 from rnhmjoj/shell
# possible first bad commit: [4eca960cb4ed5e68b93d112fd90623a5a2bae433] Merge #53946: attr: fix issues with 2.4.48
```

**Comment by rnhmjoj** [comment]
I'll make a PR as soon as possible to fix this. I didn't realize substituteAll does not preserve the file permissions.

**Comment by baracoder** [comment]
Thank you, for the response and the PR. It looks good so I will already close this issue.
I have learned something while searching for the cause.
