### ISSUE TITLE
Flit command not found when buildPythonPackage format='flit'

### ISSUE THREAD

**Issue by costrouc** [NixOS/nixpkgs#56917]
## Issue description

I am getting an error when using the most recent of nixpkgs with building flit packages. I get the following error (also this is not the first time I've had the error). 

```
/nix/store/63karsgdg7fm3q0if4zfd7apbd8ac1ci-stdenv-linux/setup: line 1312: flit: command not found
```

Looking at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/build-python-package-flit.nix we see the following build process.

```
buildPhase = attrs.buildPhase or ''
    runHook preBuild
    flit build --format wheel
    runHook postBuild
  '';
```

This fixed the issue for me but I am not sure if it is the correct approach

```
buildPhase = attrs.buildPhase or ''
    runHook preBuild
    ${python.interpreter} -m flit build --format wheel
    runHook postBuild
  '';
```

The example where I got this to fail (you won't be able to run this...)

```
  tableau = pythonPackages.buildPythonPackage rec {
    name = "tableau";
    format = "flit";

    src = builtins.filterSource
             (path: _: !builtins.elem  (builtins.baseNameOf path) [".git" "result"])
             ./.;

    checkInputs = testRequirements;
    propagatedBuildInputs = buildRequirements;

    buildPhase = ''
      ${pythonPackages.python.interpreter} -m flit build --format wheel
    '';

    checkPhase = ''
      pytest --ignore=tests/test_reader.py
    '';
  };
```

**Comment by FRidh** [comment]
Thanks for reporting. Fixed in a2736d27d16aecd1f2179e07db23bf1b6c0c4c46.
Note that your solution works, but most likely won't when cross-compiling.
