### ISSUE TITLE
The installation of linux kernel 5.0 hardened is broken

### ISSUE THREAD

**Issue by SchrodingerZhu** [NixOS/nixpkgs#56931]
## Issue description
The compilation of kernel source is stopped of an error:
```
modDirVersion 5.0.0-rc8 specified in the Nix expression is wrong, it should be: 5.0.0-rc8-hardened
```
Also Nvidia-beta falied to compile. seems that a CONSTANT `AS_***` should be changed.
### Steps to reproduce

Just compile it.

**Comment by KaiHa** [comment]
Similar problem here, the following workaround has solved it for me:
```
nixpkgs.overlays = [( self: super: rec {
    linux_5_0 = super.linux_5_0.override { modDirVersion = "5.0.7-hardened"; };
})];
```

**Comment by joachifm** [comment]
I believe this has been fixed
