### ISSUE TITLE
Terminator doesn't work

### ISSUE THREAD

**Issue by karolchmist** [NixOS/nixpkgs#56934]
## Issue description

Terminator doesn't work on latest `nixos-unstable`. It used to work until the last update of my NixOS.

### Steps to reproduce

While trying to run `terminator`, I get 
```
You need to install the python bindings for gobject, gtk and pango to run Terminator.
```

My terminator links to 
```
/nix/store/wqlm1fi4d50wzzqan3bq4hqskrckxzhy-terminator-1.91/bin/terminator
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.09.git.34aa254 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(karol): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by karolchmist** [comment]
Pinging @bjornfor or @globin , could you have a look please ?

**Comment by jtojnar** [comment]
Yeah, this is probably the same as https://github.com/NixOS/nixpkgs/issues/56943

**Comment by borisbabic** [comment]
Adding `gobject-introspection` to `propagatedBuildInputs` got it working for me.

**Comment by jtojnar** [comment]
Closing as a duplicate of #56943
