### ISSUE TITLE
bpython depends on which

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#56941]
## Issue description

>  File "/nix/store/80qva2zal82njkg4zvb7xg94mnikqksd-python3-3.6.8/lib/python3.6/subprocess.py", line 1364, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'which': 'which'
> 

### Steps to reproduce
Create a pure nix shell with `python36Packages.bpython` and execute `bpython`.

## Technical details
18.09.

**Comment by dotlambda** [comment]
We should patch the call of `which` in https://github.com/bpython/bpython/blob/0.17.1-release/bpython/clipboard.py using `substituteAll`.
cc maintainer @flokli

**Comment by flokli** [comment]
@dotlambda it also tries to also call out to at least xclip (on Linux), pbcopy (on Darwin), and less - should we patch these in, too?

**Comment by dotlambda** [comment]
I don't think so as bpython shouldn't depend on X.

**Comment by memberbetty** [comment]
On Linux it should have `xclip` in its dependencies. Otherwise `--pure` is still going to fail. 

The whole point of being able to run something via `nix-shell --pure` is that *all* dependencies are in, and if you have to know about random run-time dependencies that are not obvious, some advantages are nullified.

**Comment by dotlambda** [comment]
However, the whole point of bpython calling which is to make the dependency on xclip optional. It will hence *not* fail without it.

**Comment by memberbetty** [comment]
Fair point, but I prefer to have programs that are fully featured by default. People that run on limited platforms can make a more complicated expression optimized for their use cases.

**Comment by dotlambda** [comment]
@memberbetty If you do the PR, I won't reject patching in the path to xclip.

**Comment by flokli** [comment]
I prefered not dragging in `xclip` and all its dependencies by default and opened https://github.com/NixOS/nixpkgs/pull/89439. On systems with `xclip` in `$PATH`, this should do the right thing - PTAL.
