### ISSUE TITLE
openblas: build broken on aarch64 (master & release 19.03)

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#56949]
## Issue description
It looks like that https://github.com/NixOS/nixpkgs/pull/56216 broke the build on aarch64:
```
gfortran: error: unrecognized command line option '-m64'
```

### Steps to reproduce
For example see https://hydra.nixos.org/build/89399945 for a build log.

CC @ttuegel @dtzWill

**Comment by ingenieroariel** [comment]
I stumbled onto this when trying to build postgis on master.
