### ISSUE TITLE
Automatically execute user specific configuration

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5695]
I would like to execute the following as the wwat user when applying a configuration (that is, have it part of some .nix file).
```
git config --global user.email "wwat@users.noreply.github.com
```
How can I accomplish that? 

Ideally, this should also work without having root.

**Comment by bjornfor** [comment]
You can use activationScripts (git grep in nixpkgs).

**Comment by wwat** [comment]
I added this to configuration.nix, but the change is not reflected when I later log in as user `wwat` (it should show `wwat2`.
```
    system.activationScripts.git_user_setup =
        ''
          sudo -u wwat git config --global user.email "wwat@users.noreply.github.com"
          sudo -u wwat git config --global user.name "wwat2"
        '';
```

**Comment by wwat** [comment]
Never mind, I got it to work (there were proper messages being displayed and the solution was easy).
