### ISSUE TITLE
nix-env -iA nixos.python36Packages.cozy fails to install

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#57028]
## Issue descriptionf
fails in igraph

testMSTofGRG (igraph.test.homepage.HomepageExampleTests) ... ok

======================================================================
ERROR: testFormula (igraph.test.generators.GeneratorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/test/generators.py", line 72, in testFormula
    g = Graph.Formula(formula)
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: invalid token found in edge specification: A

======================================================================
ERROR: testCohesiveBlocks2 (igraph.test.decomposition.CohesiveBlocksTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/test/decomposition.py", line 329, in testCohesiveBlocks2
    g = Graph.Formula("1-2:3:4:5:6, 2-3:4:5:7, 3-4:6:7, 4-5:6:7, "
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: invalid token found in edge specification: 1-2:3:4:5:6

----------------------------------------------------------------------
Ran 307 tests in 8.022s

FAILED (errors=2, skipped=3)
Test failed: <unittest.runner.TextTestResult run=307 errors=2 failures=0>
Build type: dynamic extension
Include path: /nix/store/mqwgb89qhw6bzpnz6y8ck0axz5brqy4l-igraph/include/igraph
Library path: /nix/store/mqwgb89qhw6bzpnz6y8ck0axz5brqy4l-igraph/lib
Runtime library path:
Linked dynamic libraries: igraph
Linked static libraries:
Extra compiler options:
Extra linker options:
error: Test failed: <unittest.runner.TextTestResult run=307 errors=2 failures=0>
builder for '/nix/store/vrwaljq2dvbzlsd993f24cl6bxpbpvm2-python3.6-python-igraph-0.7.1.post6.drv' failed with exit code 1
cannot build derivation '/nix/store/pnwybfk338gfl00snnrf9n2980cwk58s-python3.6-cozy-2.0a1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/pnwybfk338gfl00snnrf9n2980cwk58s-python3.6-cozy-2.0a1.drv' failed

### Steps to reproduce

nix-env -iA nixos.python36Packages.cozy

## Technical details
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.26, NixOS, 18.09.2318.4c089d328fe (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2318.4c089d328fe"`
 - channels(mog): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
Both 3.6 and 3.7 versions are broken firstly since b4acd9772975d549f491d48debb679cf4ec78133 in https://github.com/NixOS/nixpkgs/pull/55757 with the error

```
Cannot find the C core of igraph on this system using pkg-config.
We will now try to download and compile the C core from scratch.
Version number of the C core: 0.7.1.post6
We will also try: 0.7.1

Version 0.7.1.post6 of the C core of igraph is not found among the nightly builds.
Use the --c-core-version switch to try a different version.

Could not download and compile the C core of igraph.

builder for '/nix/store/v1pifjfjpbbbf8848rh855wmr1fl4izy-python3.7-python-igraph-0.7.1.post6.drv' failed with exit code 1
```

Before that commit, 3.6 fails with the following error since the 3.6.7 update 241bab3a5ed2f21d544dc66144f08f9ae203beb4:
```
======================================================================
ERROR: testFormula (igraph.test.generators.GeneratorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/test/generators.py", line 72, in testFormula
    g = Graph.Formula(formula)
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: invalid token found in edge specification: A

======================================================================
ERROR: testCohesiveBlocks2 (igraph.test.decomposition.CohesiveBlocksTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/test/decomposition.py", line 329, in testCohesiveBlocks2
    g = Graph.Formula("1-2:3:4:5:6, 2-3:4:5:7, 3-4:6:7, 4-5:6:7, "
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "/build/python-igraph-0.7.1.post6/build/lib.linux-x86_64-3.6/igraph/formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: invalid token found in edge specification: 1-2:3:4:5:6

----------------------------------------------------------------------
Ran 307 tests in 3.785s

FAILED (errors=2, skipped=3)
Test failed: <unittest.runner.TextTestResult run=307 errors=2 failures=0>
Build type: dynamic extension
Include path: /nix/store/4y0v437kyxyrhgkn197xfbbrqarrqwmm-igraph-0.7.1/include/igraph
Library path: /nix/store/4y0v437kyxyrhgkn197xfbbrqarrqwmm-igraph-0.7.1/lib
Runtime library path:
Linked dynamic libraries: igraph
Linked static libraries:
Extra compiler options:
Extra linker options:
error: Test failed: <unittest.runner.TextTestResult run=307 errors=2 failures=0>
builder for '/nix/store/1zv1j3pl0wb5rqxg90lynmpb0c6zmm0b-python3.6-python-igraph-0.7.1.post6.drv' failed with exit code 1
```

While 3.7 started failing with the same error since the 3.7.1 update in e4d84434a70fe33f1839b3ad1d0b129e6bd62f9a

Ping @FRidh

**Comment by MostAwesomeDude** [comment]
Refreshed. My PR will fix the build and allow installation, but Z3 is still a temperamental package and Cozy fails to start for me.
