### ISSUE TITLE
Qt: update to 5.12.3

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#57042]
## Issue description

https://blog.qt.io/blog/2019/02/01/qt-5-12-1-released/

Unfortunately it appears non-trivial to update, but seems like something we should tackle soon.

Has anyone looked into this, or might be in a good position to put together an upgrade?
Also thoughts on the priority this effort should have, are appreciated :).

**Comment by vandenoever** [comment]
In the meantime 5.12.3 has been released.

https://blog.qt.io/blog/2019/04/17/qt-5-12-3-released/

 Simply adapting `pkgs/development/libraries/qt-5/5.12/fetch.sh` and running

```bash
maintainers/scripts/fetch-kde-qt.sh pkgs/development/libraries/qt-5/5.12
```

is not enough. Many patches do not apply anymore.

**Comment by vandenoever** [comment]
Here is a first stab at upgrading qt 5.12.0 to 5.12.3. The patches for base are adapted to apply. However, qtbase does not compile yet: it fails at the configuration step.

Qt 5.12.1 has removed the `-xkbcommon_evdev` flag. See c3226bd5cc6bf009d2fb3c233a09f3ef5cf618e9 and 28fd625873f9bb191cb10a2a36a1b974c6e8c97e and QTBUG-65503.

https://github.com/vandenoever/nixpkgs/commit/8bf128e075c4ee537bebd7ef366007eb994cab73

I'm stuck but perhaps you or @ttuegel have a clue how to continue.

**Comment by vandenoever** [comment]
I've opened an editable pull request here: https://github.com/NixOS/nixpkgs/pull/60119

**Comment by petabyteboy** [comment]
This is done, but we need a new issue for 5.12.4 maybe?

**Comment by dtzWill** [comment]
Or perhaps 5.13.1? https://www.qt.io/blog/qt-5.13.1-released

**Comment by petabyteboy** [comment]
Either one would be great
