### ISSUE TITLE
Provide regulatory.db info via /lib/firmware when supported

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#57053]
## Issue description

Newer kernels (4.15+) can look for wireless regulatory info from `/lib/firmware` (for us this is `/run/current-system/firmware`  I think?),
replacing the need for user-space helper like `crda`.
(at least in the common case, I believe)

## Links to resources/related info

* https://git.kernel.org/pub/scm/linux/kernel/git/mcgrof/crda.git/commit/ <-- latest CRDA git adds note about this
* Not the same as the `internal` regdb, although I'm not sure the difference is as important for NiXOS'ers compared to other distributions. Info on internal: https://wireless.wiki.kernel.org/en/developers/regulatory/crda#config_cfg80211_internal_regdb
* https://bugs.archlinux.org/task/57563

**Comment by teto** [comment]
I don't want to hijack the thread but my problem may be related.
Recently, not sure why, I can't connect to an AP I previously could connect to so I suspect it's my machne (my phone can still access it), thus I've been looking at wifi information.
I used to have a plain error then I added `udev.packages = [ pkgs.crda ];` while now it at least attempt to connect:
```
[    5.428896] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    5.428898] cfg80211: failed to load regulatory.db
```
so I wonder if it's expected on nixos ?

NB: it's annoying all these errors when building kernels. do others have it too (I should probably look at hydras rather...
```
modinfo: ERROR: Module alias enable_fbc=1 not found.
modinfo: ERROR: Module alias enable_psr=2 not found.
depmod: WARNING: could not open modules.order at /nix/store/2bavdfzx904lyxzyj79avw111sgd1k78-linux-4.19.40-modules-shrunk/lib/modules/4.19.40: No such file or directory
depmod: WARNING: could not open modules.builtin at /nix/store/2bavdfzx904lyxzyj79avw111sgd1k78-linux-4.19.40-modules-shrunk/lib/modules/4.19.40: No such file or directory
building '/nix/store/hrqmhqypk383229adsv79h07g3cv4gdh-stage-1-init.sh.drv'...
```

**Comment by samdoshi** [comment]
To get the `regulatory.db` file loaded, you need to add `wireless-regdb` to `hardware.firmware`.

```
hardware.firmware = with pkgs; [ wireless-regdb ];
````

`ls -l $(nix path-info nixpkgs.wireless-regdb)/lib/firmware` to see the files.


Then you should see the following in `dmesg`:

```
[    2.532137] cfg80211: Loading compiled-in X.509 certificates for regulatory database
```

I haven't quite figured out what the best way to set the correct regulatory domain is however... short of just using `iw`.

**Comment by teto** [comment]
oh great thanks ! that was not obvious. I was looking for a setting to set on boot as a kernel parameter but haven't found it yet. Some interesting read https://wireless.wiki.kernel.org/en/developers/regulatory#kernel_integration suggests one can embed the kernel in the db as well ?!

**Comment by edolstra** [comment]
@samdoshi Something like this should work:
```
  boot.extraModprobeConfig = ''
    options cfg80211 ieee80211_regdom="NL"
  '';
```
Admittedly not ideal since it only works at module load time though.

**Comment by samdoshi** [comment]
Thanks @edolstra 

Setting the following gives me the correct wifi config (check with `iw reg get`):

```
hardware.firmware = with pkgs; [ wireless-regdb ];
boot.extraModprobeConfig = ''
  options cfg80211 ieee80211_regdom="GB"
'';
```

Looking through the documents on:

https://wireless.wiki.kernel.org/en/developers/regulatory
https://wireless.wiki.kernel.org/en/developers/regulatory/crda

It seems to be a bit of a mess.... `ieee80211_regdom` is an 'old' option, but NetworkManager has no support for setting the reg domain.

I think having a module (`hardware.wirelessRegulatoryDomain`?) might be a very good idea, and such an option should be added to`nixos-generate-config`.

ArchLinux deals with it by using a custom `udev` rule to run `iw` when `cfg80211` is loaded ([source][al]).

[al]: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/crda

Another idea would be to added a `networking.wireless.networks.<name>.country` option, though that doesn't fix NetworkManager.

**Comment by Kloenk** [comment]
This should not be stale I think.

Should NixOS just add `wireless-regdb` to `hardware.firmware` as default?

**Comment by symphorien** [comment]
cc #121530
