### ISSUE TITLE
nvidia building failure for linux 5

### ISSUE THREAD

**Issue by SchrodingerZhu** [NixOS/nixpkgs#57062]
```
/build/kernel/nvidia/os-interface.c: In function 'os_get_current_time':
/build/kernel/nvidia/os-interface.c:432:5: error: implicit declaration of function 'do_gettimeofday'; did you mean 'efi_gettimeofday'? [-Werror=implicit-function-declaration]
     do_gettimeofday(&tm);
     ^~~~~~~~~~~~~~~
     efi_gettimeofday
  CC [M]  /build/kernel/nvidia/nv-kthread-q.o
  CC [M]  /build/kernel/nvidia/nv-kthread-q-selftest.o
  CC [M]  /build/kernel/nvidia/nv-memdbg.o
  CC [M]  /build/kernel/nvidia/nv-ibmnpu.o
  CC [M]  /build/kernel/nvidia/nv-report-err.o
  CC [M]  /build/kernel/nvidia/nv-rsync.o
  CC [M]  /build/kernel/nvidia/nv-msi.o
  CC [M]  /build/kernel/nvidia/nv_uvm_interface.o
  CC [M]  /build/kernel/nvidia/nvlink_linux.o
  CC [M]  /build/kernel/nvidia/linux_nvswitch.o
  CC [M]  /build/kernel/nvidia-uvm/uvm8_turing.o
  CC [M]  /build/kernel/nvidia-uvm/uvm8_turing_mmu.o
cc1: some warnings being treated as errors
make[3]: *** [/nix/store/1zs02axvl269z99r1c3wc0mbvw2y2dj7-linux-5.0-rc8-dev/lib/modules/5.0.0-rc8/source/scripts/Makefile.build:277: /build/kernel/nvidia/os-interface.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/build/kernel/nvidia/nvlink_linux.c: In function 'nvlink_sleep':
/build/kernel/nvidia/nvlink_linux.c:555:5: error: implicit declaration of function 'do_gettimeofday'; did you mean 'efi_gettimeofday'? [-Werror=implicit-function-declaration]
     do_gettimeofday(&tm_aux);
     ^~~~~~~~~~~~~~~
     efi_gettimeofday
cc1: some warnings being treated as errors
make[3]: *** [/nix/store/1zs02axvl269z99r1c3wc0mbvw2y2dj7-linux-5.0-rc8-dev/lib/modules/5.0.0-rc8/source/scripts/Makefile.build:276: /build/kernel/nvidia/nvlink_linux.o] Error 1

```

**Comment by SchrodingerZhu** [comment]
Consider changes from 
https://github.com/aesycos/Patches/blob/abbd750ece78d323806559f8c49d790608a785c8/gentoo/x11-drivers/nvidia-drivers-390.87/nvidia-drivers-390.87-kernel-5.0.0-rc1.patch

**Comment by eadwu** [comment]
Fixed in master, though it hasn't been backported.

**Comment by srid** [comment]
It is failing on nixos-unstable (has 415.27) as well.

**Comment by eadwu** [comment]
Should still be fixed in master, although with the `418.43` release.

**Comment by SchrodingerZhu** [comment]
Is there a way to install `418.43` now? I really need an upgrade now. @eadwu

**Comment by eadwu** [comment]
Either switch to a channel that has the commit or see here [1].

[1] https://github.com/NixOS/nixpkgs/issues/51768#issuecomment-446859746

**Comment by SchrodingerZhu** [comment]
checked. `418.43` in `nixos-unstable-small` works well.

**Comment by matthew-piziak** [comment]
I know how to switch to unstable for specific packages, but not for services. I'm assuming that what I need to update is `services.xserver.videoDrivers = [ "nvidia" "intel" ];`. But I only know how to get `unstable-pkgs = import <unstable> {};`. How do I get `unstable-services`?

**Comment by eadwu** [comment]
The services used by the channel should be fine since I believe there hasn't really been any major changes [1].

[1] https://github.com/NixOS/nixpkgs/commits/master/nixos/modules/hardware/video

**Comment by matthew-piziak** [comment]
Yeah, I moved to 18.09 and now I'm just getting this.

```
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7f8af443c700, resourceid: 0, serial: 6a
[vo/gpu/x11] Error code: 2, request code: 9a, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7f8af44e87f0, resourceid: 0, serial: 6a
[vo/gpu/x11] Error code: 2, request code: 9a, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
```

**Comment by eadwu** [comment]
Where are you seeing the errors? While `vdpau` still works for hardware acceleration, I believe NVDEC is the recommended way by NVIDIA.

**Comment by matthew-piziak** [comment]
@eadwu Rebooted and they're gone. Classic.

> A novice was trying to fix a broken Lisp machine by turning the power off and on.
> 
> Knight, seeing what the student was doing, spoke sternly: “You cannot fix a machine by just power-cycling it with no understanding of what is going wrong.”
> 
> Knight turned the machine off and on.
> 
> The machine worked.

**Comment by matthew-piziak** [comment]
This were showing up in `mpv` after upgrading to 18.09 from 18.03.

**Comment by unode** [comment]
Seeing the `do_gettimeofday` error also in `19.03` when using `kernelPackages = pkgs.linuxPackages_latest;` (which pulls `nvidia-x11-415.27`).

**Comment by eadwu** [comment]
See https://github.com/NixOS/nixpkgs/issues/57062#issuecomment-472600820.

**Comment by shosti** [comment]
Are there plans to backport the 418 driver to 19.03? (I'm not sure what the stability policy is around nvidia drivers...)

**Comment by eadwu** [comment]
See https://github.com/NixOS/nixpkgs/issues/19955#issuecomment-257012909, normally I send a backport request since I don't keep track of the branches.

**Comment by shosti** [comment]
If I’m reading correctly, 418 is the long-lived version so it should be in the release branch (i.e. 19.03)?

**Comment by nek0** [comment]
There is also an issue for me building nvidiaLegacy390 with the current linux_latest kernel...

**Comment by haslersn** [comment]
Is this still up to date?

**Comment by nek0** [comment]
@haslersn yes

**Comment by vcunat** [comment]
This has long been solved.  5.0 kernels are gone and nvidia builds fine up to 5.6.  But nvidia will probably always lag behind a bit, e.g. currently it won't build with 5.7: https://github.com/NixOS/nixpkgs/issues/90459
