### ISSUE TITLE
exfat-nofuse building failure for linux 5

### ISSUE THREAD

**Issue by SchrodingerZhu** [NixOS/nixpkgs#57063]
There is a patch for linux 5 in the repo of exfat-nofuse. Consider patch it.

**Comment by SchrodingerZhu** [comment]
https://github.com/dorimanx/exfat-nofuse/issues/145

**Comment by rycee** [comment]
CC: @makefu

**Comment by bricewge** [comment]
PR https://github.com/NixOS/nixpkgs/pull/68647 should fix this.

**Comment by rycee** [comment]
Neat. Btw. I retried the patch I gave above and now everything worked fine and I'm able to mount an exfat sd card on a system running Linux 5.2.16.

**Comment by Mic92** [comment]
This package has been updated now in https://github.com/NixOS/nixpkgs/pull/68647
