### ISSUE TITLE
Prosody encrypted s2s requires specifying cafile in virtualhost

### ISSUE THREAD

**Issue by t184256** [NixOS/nixpkgs#57086]
## Issue description
In order to use encrypted s2s in prosody, one has to specify
```
ssl.extraOptions.cafile = "/etc/ssl/certs/ca-bundle.crt";
```
in the virtualhost configuration (not the `extraConfig`, `virtualHosts.*.ssl.extraOptions.cafile`). This is quite non-intuitive, not readily discoverable and should at least be documented, at most fixed.

### Steps to reproduce

```
  services.prosody = {
    enable = true;
    ...
    s2sSecureAuth = true;
  };
```
without `ssl.extraOptions.cafile = "/etc/ssl/certs/ca-bundle.crt";` in the `virtualHost` entry results in

```
certificate error(s) at depth 1: unable to get local issuer certificate
```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"                                                              ~
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.15, NixOS, 18.09.2323.fef0aaaaab4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(monk): `""`
 - channels(root): `"home-manager, nixos-18.09.2323.fef0aaaaab4, nixos-hardware, nixos-mailserver, nixos-unstable-19.09pre171786.34aa254f9eb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mmilata** [comment]
Appears to be fixed 5a93f6149abb404e053f3759e64e93f20de312da (i.e. since 19.03) - can we close this one?
