### ISSUE TITLE
Virtualbox test is failing

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#5708]
cc @aszlig Me and another person using latest unstable release at commit 173f41c, when building with `virtualboxHost.enable = true` get this out path: `/nix/store/mjbidb54wmmga9wym3mvvn05rchvppdr-virtualbox-4.3.20-3.14.27`

But on hydra the build is http://hydra.nixos.org/build/18579210 and the path `/nix/store/glzyvwqarn9h6596daj1qm1nxiaykhc5-virtualbox-4.3.20-3.14.27`

Now investigating what's the possible difference.

**Comment by iElectric** [comment]
Do you have hardening enabled?

**Comment by lethalman** [comment]
@iElectric don't know, is that enabled by default?

**Comment by iElectric** [comment]
Yes and it rebuilds VirtualBox in NixOS.

**Comment by lethalman** [comment]
@iElectric so why should hydra have a different hash? What's your hash with latest unstable?

**Comment by iElectric** [comment]
I'm using 14.12
branch: /nix/store/cr6vs68r1qxr83v9ngrvs9xrcfvlppi8-virtualbox-4.3.20-3.17.6

**Comment by lethalman** [comment]
I did a diff between the closure of my vbox and the hydra one, the runtime paths are all the same except for vbox. So the difference must be in the vbox contents itself.
Now I'd need the .drv of hydra, how would I get it?

**Comment by lethalman** [comment]
Did a diff and I get exactly the vbox hardened patch diff. For example:
```
--- /nix/store/glzyvwqarn9h6596daj1qm1nxiaykhc5-virtualbox-4.3.20-3.14.27/libexec/virtualbox/additions/src/vboxsf/include/iprt/mangling.h	1970-01-01 01:00:01.000000000 +0100
+++ /nix/store/mjbidb54wmmga9wym3mvvn05rchvppdr-virtualbox-4.3.20-3.14.27/libexec/virtualbox/additions/src/vboxsf/include/iprt/mangling.h	1970-01-01 01:00:01.000000000 +0100
@@ -1051,6 +1051,7 @@
 # define RTPathStripExt                                 RT_MANGLER(RTPathStripExt)
 # define RTPathStripFilename                            RT_MANGLER(RTPathStripFilename)
 # define RTPathStripTrailingSlash                       RT_MANGLER(RTPathStripTrailingSlash)
+# define RTPathSuidDir                                  RT_MANGLER(RTPathSuidDir)
 # define RTPathTemp                                     RT_MANGLER(RTPathTemp)
 # define RTPathTraverseList                             RT_MANGLER(RTPathTraverseList)
 # define RTPathUnlink                                   RT_MANGLER(RTPathUnlink)
@@ -1088,6 +1089,7 @@
 # define RTProcGetAffinityMask                          RT_MANGLER(RTProcGetAffinityMask)
 # define RTProcGetExecutablePath                        RT_MANGLER(RTProcGetExecutablePath)
 # define RTProcGetPriority                              RT_MANGLER(RTProcGetPriority)
+# define RTProcGetSuidPath                              RT_MANGLER(RTProcGetSuidPath)
 # define RTProcIsRunningByName                          RT_MANGLER(RTProcIsRunningByName)
 # define RTProcQueryParent                              RT_MANGLER(RTProcQueryParent)
 # define RTProcQueryUsername                            RT_MANGLER(RTProcQueryUsername)
```

So it appears that hydra does not build the hardened version.

**Comment by lethalman** [comment]
Ah because the virtualbox test failed.

**Comment by aszlig** [comment]
The reason for the different hashes is that VirtualBox built for the NixOS service module has hardening enabled by default, while the package itself by default does not have it enabled in order to make it usable without the host's kernel kernel additions.

As for the tests, I'm going to look into this...
