### ISSUE TITLE
Make a common mkOverride for python 

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#57124]
It would be nice if these were moved into a common general (python) use component:
https://github.com/NixOS/nixpkgs/blob/777e94d903795d5028865d0bb0b76fef330eabb7/pkgs/servers/home-assistant/default.nix#L80-L88
https://github.com/NixOS/nixpkgs/blob/2fcb11a2442b27834db87b2f62511037c31b5e36/pkgs/applications/misc/octoprint/default.nix#L4-L12

**Comment by FRidh** [comment]
Having a function like that will imply that changing version is sufficient to get a working package, while that is not true at all. Therefore, I am against exposing such a common function.

**Comment by deliciouslytyped** [comment]
In my case this was mostly useful for downgrades because nixpkgs keeps only a single version of everything. I used it in a package that pulls in a lot of old dependencies. Just changing the version *does* seem to be sufficient for most things, but as always you have to look at what that version of your package wants if you expect it to behave reasonably.

Minor sidenote: for a lot of downgrades you can look at the package's history in nixpkgs to see what worked. I suppose I should look into trying a simple fetch + callpackage combo for old commits, hmm.

**Comment by dotlambda** [comment]
I'm also against adding this to `pythonPackages` since it's really not very general (it requires the use of `fetchPypi`) and very easy to write yourself.
