### ISSUE TITLE
appimage-run can't run digikam

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#57127]
## Issue description

I tried to run [digikam](https://files.kde.org/digikam/digikam-6.0.0-beta3-20181228T114626-x86-64.appimage) using `appimage-run`. I noticed two things:

- `libgpgerror` was missing. Adding it to `targetPkgs` fixes that issue. Is `appimage-run` supposed to be able to run all appimages? Should we add `libgpgerror`?
- command line arguments aren't passed on to the appimage

CC @tilpner

**Comment by tilpner** [comment]
I haven't decided yet. Common libraries currently not available to appimage-run should be added to the list, but I think unreasonable libraries that are only used by a single application shouldn't be added.

Oh right, I noticed that a while ago, and then forgot to fix it.

**Comment by timokau** [comment]
That is a useful list. I used a bash monster to look for libraries missing in our `appimage-run`:

```bash
$ sed -e 's/#.*//' -e '/^\s*$/d' excludelist | while read line; do nix-locate $line | grep 'appimage-run'>/dev/null || echo "$line"; done
libthai.so.0
libharfbuzz.so.0
libcom_err.so.2
libgpg-error.so.0
libkeyutils.so.1
libp11-kit.so.0
libgpg-error.so.0
libjack.so.0
libfribidi.so.0
```

**Comment by timokau** [comment]
Of those the following are available in nixpkgs:

```
harfbuzz -> libharfuzz.so.0
e2fsprogs -> libcom_err.so.2
libgpgerror -> libgpg-error.so.0
keyutils.lib -> libkeyutils.so.1
libjack2 -> libjack.so.0
fribidi -> libfibidi.so.0
```
