### ISSUE TITLE
fontforge needs libpng at runtime

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#5716]
When a font is opened in fontforge or fontimage from the package fontforce, this message is shown:
   libpng: libpng.so.2: cannot open shared object file: No such file or directory
Try e.g.:
   fontimage -o test.png DejaVuSans.ttf
fontforge is a dynamic executable but it does not link to libpng.so.2 but loads it on demand.

**Comment by vcunat** [comment]
Would you test this patch: 27a5365648e61?

**Comment by vandenoever** [comment]
This patch build the package fine, but the issues is still exactly the same.
Did the sample cmdline work for you?

$  fontimage -o test.png DejaVuSans.ttf
Copyright (c) 2000-2011 by George Williams.
 Executable based on sources from 13:48 GMT 22-Feb-2011-TtfDb-NoPython.
 Library based on sources from 13:48 GMT 22-Feb-2011.
This font contains both a 'kern' table and a 'GPOS' table.
  The 'kern' table will only be read if there is no 'kern' feature in 'GPOS'.
Use-my-metrics flag set on at least two components in glyph 685
The glyph named mu is mapped to U+00B5.
  But its name indicates it should be mapped to U+03BC.
The glyph named Delta is mapped to U+2206.
  But its name indicates it should be mapped to U+0394.
libpng.so.2: cannot open shared object file: No such file or directoryCould not write out.png

**Comment by vcunat** [comment]
Hmm, I see, it's opened by ``libgutils.so`` and not by ``bin/fontforge`` directly. That's easy to work around, but most other libs are only dlopened as well, which will cause problems (it retains references to almost none of the libs detected in configure phase). I found the ``--with-regular-link`` configure option that should fix that, but for some reason fontforge fails to build with it.

The source is quite old, so I tried updating to the latest release (20141230), but it's really adverse to nix-like packaging, trying to download git sources for its tools, etc. I haven't managed to make it configure yet....

**Comment by vcunat** [comment]
I think I've got it now. I'll do some more polishing and testing.

**Comment by vcunat** [comment]
It got more complex than anticipated, but now the package should really work.

**Comment by vandenoever** [comment]
works for me too.

**Comment by bjornfor** [comment]
Cherry-pick to release-14.12?

**Comment by vcunat** [comment]
Hmm, it's a rather large update, but considering it didn't work well before and few things depend on it, I'll pick it.
