### ISSUE TITLE
monero has hard forked, daemon no longer syncs

### ISSUE THREAD

**Issue by thedavidmeister** [NixOS/nixpkgs#57210]
## Issue description

monero forked at 1788000 so `monerod` is stuck at block 1788011 now

https://www.reddit.com/r/Monero/comments/ap6iiw/monero_will_fork_at_block_1788000_march_9th/

note when upgrading that there is a serious looking bug with the 0.14 client and ledger nano

https://www.reddit.com/r/Monero/comments/ax0pqt/alert_stop_using_ledger_with_014_client/

update: bug fixed in `1.2.1` and looks like it needs to be updated on the ledger itself:

- https://github.com/LedgerHQ/ledger-app-monero/commit/09927cfcce827bc238d73820d17b20ac36a0b63d
- https://www.reddit.com/r/Monero/comments/ax0pqt/alert_stop_using_ledger_with_014_client/ei73rtz
- https://github.com/monero-project/monero/pull/5236

### Steps to reproduce

`nix-shell -p monero --run monerod`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Infinisil** [comment]
Is this resolved with https://github.com/NixOS/nixpkgs/pull/58250 merged now?

**Comment by rnhmjoj** [comment]
#57921 is next.

**Comment by rnhmjoj** [comment]
Ok, looks like everything is set.
