### ISSUE TITLE
avahi-daemon does not start at boot

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#5721]
Since NixOS 14.12, setting `services.avahi.enable = true` does not start `avahi-daemon` at boot. I must manually run `systemctl start avahi-daemon` after every boot. One other user complained to me about this on IRC, but I cannot recall who.

**Comment by ttuegel** [comment]
Fix in latest master.

**Comment by bjornfor** [comment]
What about the stable branch? Is there something we can backport?

**Comment by ttuegel** [comment]
I will investigate if this can be backported, but right now I don't even know what commit fixed it!

**Comment by bjornfor** [comment]
I rebooted both my machines 2 times just now. Avahi-daemon started every time. I'm on release-14.12 branch. So if there still is an issue, it's not deterministic... Closing for now.
