### ISSUE TITLE
remove carnix from the nixpkgs manual

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixpkgs#57235]
Running `carnix -o hello.nix --src ./. Cargo.lock --standalone` as described in `rust.section.md` yields
```
error: Found argument '-o' which wasn't expected, or isn't valid in this context
```
Environment: carnix version 0.9.8 (`nixpkgs-unstable.carnix`).

cc @P-E-Meunier

**Comment by P-E-Meunier** [comment]
It's not broken, it just changed syntax, as indicated by `carnix --help`.

**Comment by P-E-Meunier** [comment]
I did update the manual at some point on my machine, but an unfortunate git rebase got rid of my changes, sorry about that.

**Comment by erikarvstedt** [comment]
The issue hasn't been fixed yet, I think this should be reopened.

**Comment by Infinisil** [comment]
This is not a nixpkgs issue, as @P-E-Meunier elaborated. If you don't like that carnix changed the syntax you should [file an issue for carnix](https://nest.pijul.com/pmeunier/carnix:master/discussions)

**Comment by erikarvstedt** [comment]
The outdated command is from the nixpkgs docs ([rust.section.md](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md)), so that makes it a nixpkgs issue.

**Comment by Infinisil** [comment]
Oh I didn't see you mention that, sorry!

**Comment by mkaito** [comment]
@P-E-Meunier don't suppose you've found some time to update those docs yet?

**Comment by p-alik** [comment]
While the issue primarily about [rust.section.md](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md), and `carnix` seems to be a stumbling block for many I'll add unopinionated [recomenation](https://discourse.nixos.org/t/how-to-do-carnix-rust-build/4495) to use `crate2nix` instead of `carnix`.

**Comment by uri-canva** [comment]
Carnix hasn't been updated in over a year, and the pijul nest repository linked in https://crates.io/crates/carnix is not available anymore.

**Comment by uri-canva** [comment]
@P-E-Meunier are you still maintaining `carnix`? Have you switched to use something else instead?

**Comment by Artturin** [comment]
[carnix](https://github.com/nix-community/carnix) has been archived so it should be removed from the manual
the most popular ones for out of nixpkgs usage are [naersk](https://github.com/nix-community/naersk) and [cargo2nix](https://github.com/cargo2nix/cargo2nix) while `rustPlatform.buildRustPackage` is used in nixpkgs

https://nixos.org/manual/nixpkgs/unstable/#compiling-rust-crates-using-nix-instead-of-cargo

**Comment by figsoda** [comment]
I am working on a pr to remove carnix completely, but I'm not sure who should be the replacement

Some possible candidates I found:
- [crate2nix](https://github.com/kolloch/crate2nix) - this is the one I'm leaning towards, already packaged in nixpkgs and seems to integrate with buildRustCrate
- [cargo2nix](https://github.com/cargo2nix/cargo2nix) - looks similar to crate2nix, not sure how they compare
- [naersk](https://github.com/nix-community/naersk) - no code generation, seems to be very popular
- [crane](https://github.com/ipetkov/crane) - looks similar to naersk, seems to have grown in popularity recently

**Comment by Artturin** [comment]
> I am working on a pr to remove carnix completely, but I'm not sure who should be the replacement
> 
> Some possible candidates I found:
> 
> * [crate2nix](https://github.com/kolloch/crate2nix) - this is the one I'm leaning towards, already packaged in nixpkgs and seems to integrate with buildRustCrate
> * [cargo2nix](https://github.com/cargo2nix/cargo2nix) - looks similar to crate2nix, not sure how they compare
> * [naersk](https://github.com/nix-community/naersk) - no code generation, seems to be very popular
> * [crane](https://github.com/ipetkov/crane) - looks similar to naersk, seems to have grown in popularity recently

I'm using naersk in all my rust projects and have had no issues with it, I especially like that it doesn't generate any files

For outside of nixpkgs usage we should point to naersk while for in nixpkgs usage we should just keep using cargoSha256
IMHO

**Comment by figsoda** [comment]
So do you think we should just remove this section?
[compiling rust crates using nix instead of cargo](https://github.com/NixOS/nixpkgs/blob/30a59652168bb1a2222f0b6b9504137fbf6c71c1/doc/languages-frameworks/rust.section.md#compiling-rust-crates-using-nix-instead-of-cargo-compiling-rust-crates-using-nix-instead-of-cargo)
