### ISSUE TITLE
Poor signal-to-noise ratio in nix build log

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#5723]
This all falls under the nix usability umbrella, but it would be nice if by default most packages hid command output unless something went wrong, only giving me high-level feedback unless I asked for more verbosity. The log output currently makes it almost impossible to figure out what's going on unless you use search functionality to skip over all the noise.

I imagine fixing this would amount to wrapping the calls to the various `*phase` values in buffering wrappers that save their subprocess output but discard it if there are no errors (or write it to a log file). Not sure if some people like seeing all that output, but it doesn't seem like a great default.

**Comment by edolstra** [comment]
This is probably something better fixed in Nix than in Nixpkgs. For instance, Nix could hide build output by default, and only show the last N lines if a build fails.

**Comment by 7c6f434c** [comment]
It would be very nice to have this configurable in nix.conf, though: 
I do use the output to monitor the build progress when testing updates.

**Comment by vcunat** [comment]
Yeah, to me it seems just a matter of suitable UI (not how logs are gathered). Reminds me: that UI work of @qknight is stalled, right?

**Comment by iElectric** [comment]
Unfortunately, I liked that output as it's way more higher level :(

**Comment by Profpatsch** [comment]
(triage) Unless someone has a concrete proposal I suggest closing this. cc @domenkozar @vcunat

**Comment by vcunat** [comment]
The new `nix` command is silent by default https://github.com/NixOS/nix/commit/ca9de88a51c, but we still don't officially recommend using that tool.

**Comment by yegortimoshenko** [comment]
`nix` is now installed by default.
