### ISSUE TITLE
docs: add examples of overriding attrsets and functions

### ISSUE THREAD

**Issue by maxxk** [NixOS/nixpkgs#5725]
Is it possible to override xorg packages in `packageOverrides`?

I was trying to get git version of ati driver with:

```
nixpkgs.config.packageOverrides = pkgs: {
    xorg.xf86videoati = pkgs.lib.overrideDerivation pkgs.xorg.xf86videoati (attrs: attrs // {
      name = "xf86-video-ati-7.5.99";
      src = pkgs.fetchgit {
        url = "git://anongit.freedesktop.org/xorg/driver/xf86-video-ati";
        rev = "04da199231bb3f11cf17f94574a8df05855a7b82";
        sha256 = "45a76a7019ef503617c58218ced8308ef4fa4355218596ef4d8ea7ecfcb14c5e";
      };
      preConfigure = ''
        ./autogen.sh
      '';
      buildInputs = attrs.buildInputs ++ [ pkgs.autoreconfHook pkgs.xorg.utilmacros ];
    });
};
```

but `nix-rebuild` shows an error:

``` shell
$ sudo nixos-rebuild switch --cores 8
building Nix...
error: attribute ‘libXinerama’ missing, at "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/development/libraries/gtk+/2.x.nix":7:27
(use ‘--show-trace’ to show detailed location information)
```

Forking nixpkgs and changing `pkgs/servers/x11/xorg/overrides.nix` instead of overriding works fine.

**Comment by vcunat** [comment]
Well, ``packageOverrides`` is rather tricky when used on attribute sets (such as ``xorg``). The above erases whole ``xorg`` attrmap and puts only that one driver into it. I think this should do what you meant (just two lines added):

```
  packageOverrides = pkgs: {
    xorg = pkgs.xorg // {
    xf86videoati = pkgs.lib.overrideDerivation pkgs.xorg.xf86videoati (attrs: attrs // {
      name = "xf86-video-ati-7.5.99";
      src = pkgs.fetchgit {
        url = "git://anongit.freedesktop.org/xorg/driver/xf86-video-ati";
        rev = "04da199231bb3f11cf17f94574a8df05855a7b82";
        sha256 = "45a76a7019ef503617c58218ced8308ef4fa4355218596ef4d8ea7ecfcb14c5e";
      };
      preConfigure = ''
        ./autogen.sh
      '';
      buildInputs = attrs.buildInputs ++ [ pkgs.autoreconfHook pkgs.xorg.utilmacros ];
    });
  };
  };
```

**Comment by saidai-no** [comment]
Thank you, it works! :) Is it possible to mention this in the manual?

**Comment by vcunat** [comment]
Maybe we should change ``packageOverrides`` semantics to handle such things automatically, but it would make its behavior more complex (and thus more difficult to understand). I don't know.

**Comment by ardumont** [comment]
Answering myself here:

No need for the extra `attrs //`

So:

```nix

  nixpkgs.config = {
    packageOverrides = pkgs: {
      gitAndTools = pkgs.gitAndTools // {
        git-remote-hg = pkgs.lib.overrideDerivation pkgs.gitAndTools.git-remote-hg (attrs: {
          src = pkgs.fetchgit {
            url = "https://github.com/fingolfin/git-remote-hg.git";
            sha256 = "7c61c8f2be47d96c4244f0f8a3c8f9b994994b15dbe1754581f746888d705463";
          };
        });
      };
    };
  };
```

Thanks.

Cheers,

**Comment by Profpatsch** [comment]
(triage) what is the status in the manual? I have a little cheatsheet [here](https://github.com/Profpatsch/nixpkgs-cheatsheet/blob/master/cheatsheet.org), but it only scratches the surface I’m afraid.

**Comment by spacekitteh** [comment]
Bump!

**Comment by spinus** [comment]
is this obsolete because of overlays?

**Comment by Profpatsch** [comment]
> is this obsolete because of overlays?

Overlays extend the `packageOverrides` mechanism to encompass the whole of `pkgs`.
There has also been an improvement of `overrideDerivation`, `overrideAttrs`.

It might be nice to update my cheatsheet, but afaik the manual has improved a bit (I think?).

**Comment by CMCDragonkai** [comment]
I've been playing around with `overrideAttrs`, and I noticed that changing 1 small thing in a package such as adding an extra `postPhases` involves rebuilding the whole thing from scratch.

```
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/be1461fc0ab29c45c69e7b2c2097c887750e4fe0.tar.gz) {}
}:
  with pkgs;
  let
    stack-nix = stack.overrideAttrs (oldAttrs: {
      postPhases = [ "stackNixWrapPhase" ];
      stackNixWrapPhase = ''
        ${pkgs.makeWrapper}/bin/wrapProgram $out/bin/stack --add-flags '--nix'
      '';
    });
    # stack-nix = stack;
  in
    (haskell.lib.buildStackProject.override { stack = stack-nix; }) {
      name = "stack-test";
      buildInputs = [];
    }
```

**Comment by jonringer** [comment]
docs have been updated with an overrideAttrs section here: [nixpkgs manual, overrideAttrs](https://nixos.org/nixpkgs/manual/#sec-pkg-overrideAttrs)

should this be closed?

cc @vcunat @worldofpeace @maxxk

**Comment by worldofpeace** [comment]
I believe so, we could have more complicated examples, but we have examples here.

> https://github.com/NixOS/nixpkgs/commits/master/doc/functions/overrides.xml
