### ISSUE TITLE
usability: django, pytest-pythonpath; unhelpful test-time dependency management

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#57265]
I'm not sure what to do with this but I feel like I should at least put it somewhere;

It's possible to waste a lot of time trying to figure out when packaging something, and not intimately familiar with the stuff, why django tests fail with some weird ImportErrors when a project uses pytest-pythonpath.

I ran into this for packaging cuckoo sandbox: https://github.com/cuckoosandbox/cuckoo/issues/2676

I'm not sure what to do about this, but at the least, it's not helpful if packages don't warn about missing 
dependencies. So maybe it should be documented to check extra carefully about missing test infrastructure dependencies, because pytest will not warn you if you're missing any pytest plugins.

**Comment by FRidh** [comment]
If a package requires certain test dependencies, but does not declare them, then indeed you'll get errors. Nothing we can do about this.
