### ISSUE TITLE
Pantheon not working

### ISSUE THREAD

**Issue by aaronduino** [NixOS/nixpkgs#57327]
## Issue description
I've tried several times in the past to get pantheon working, to no avail.

Until this morning, I booted to a very old generation and was pleasantly surprised with a working installation of Pantheon. Once I rebooted, booting into the same generation, it no longer worked.

Every time I've attempted to boot Pantheon, except for that one time this morning, I am greeted by a black/light-gray screen, a cursor, and nothing else.

I've shrunk down my config to the smallest I could reasonably make it, and the problem has not gone away. I don't have any other hardware to test this on.

### Steps to reproduce
1. `sudo nixos-rebuild boot` using my [configuration.nix](https://gist.github.com/aaronduino/28d72b1f91afaa4a728df7e13ac88899)
2. Boot into generation
3. Enter password into login manager
4. Say hello to a black/gray screen, cursor, and nothing else.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 19.03.git.72ad05b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(ajanse): `"nixos-19.03beta171547.72ad05bfc06"`
 - channels(root): `"nixos-19.03beta171547.72ad05bfc06"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

[configuration.nix](https://gist.github.com/aaronduino/28d72b1f91afaa4a728df7e13ac88899)

[/var/log/lightdm/seat0-greeter.log](https://gist.github.com/aaronduino/9a446ce47d0ba5b6e7024b514c43b649)

**Comment by worldofpeace** [comment]
Weird, the `seat0-greeter.log` says we're starting an old session plasma5
https://gist.github.com/aaronduino/9a446ce47d0ba5b6e7024b514c43b649#file-seat0-greeter-log-L26

I think there's a bug in the greeter, and unfortunately we won't be able to fix it because of their recent rewrite on master.

Running the following in a tty
```
dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.Accounts /org/freedesktop/Accounts/User$UID org.freedesktop.Accounts.User.SetXSession string:
```

and then running `sudo systemctl restart display-manager.service` might fix it for you.

**Comment by aaronduino** [comment]
I did as you instructed. After logging in, I was greeted with a light grey screen with cursor instead of a black screen with cursor.

[/var/log/lightdm/seat0-greeter.log](https://gist.github.com/aaronduino/fd19c57c21baee59ecb3da06c4987960) (after running your commands and logging into the latter light grey screen with cursor)

**Comment by worldofpeace** [comment]
I've been able to reproduce this everytime in a vm when using pantheon's greeter.
This would be a pretty nasty problem for anyone wanting to switch to using this.

The quickest fix that I could produce was just not using their greeter
```
services.xserver.displayManager.lightdm.greeters.pantheon.enable = false;
```

Or you could do
```
dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.Accounts /org/freedesktop/Accounts/User$UID org.freedesktop.Accounts.User.SetXSession string:pantheon
```

Which will force the default to pantheon.

**Comment by hedning** [comment]
Looks like lightdm _really_ prefers the last used session stored in `~/.dmrc`, choosing it even if it doesn't exist (and dosen't bother invalidating it either when things fails).

Remove `~/.dmrc` and start up pantheon again, that should make it work (at least it ran without any problems in a VM after I cleared out an old dmrc).

**Comment by worldofpeace** [comment]
Right, forgot about the .dmrc.
Even mentioned that in the op of https://github.com/NixOS/nixpkgs/pull/48637

I think maybe we could patch lightdm to forget about `.dmrc`?
Think fedora has one too.

**Comment by worldofpeace** [comment]
Testing if using that patch does the trick now, probably should though.

**Comment by aaronduino** [comment]
Just a heads up: on my machine, I don't have a .dmrc in my home directory.

I even tried removing .gtk* and that didn't work either.

**Comment by aaronduino** [comment]
[/var/log/lightdm/seat0-greeter.log](https://gist.github.com/aaronduino/a09a2f1b18508a216ab5165ea629295c)

```
** Message: 14:11:32.256: Starting lightdm-gtk-greeter 2.0.6 (Sep 10 2018, 09:58:27)
** Message: 14:11:32.258: [Configuration] Reading file: /etc/lightdm/lightdm-gtk-greeter.conf

** (lightdm-gtk-greeter:2775): WARNING **: 14:11:32.333: [PIDs] Failed to execute command: /usr/lib/at-spi2-core/at-spi-bus-launcher

** (lightdm-gtk-greeter:2775): WARNING **: 14:11:32.334: [PIDs] Failed to execute command: upstart
```

**Comment by worldofpeace** [comment]
> Just a heads up: on my machine, I don't have a .dmrc in my home directory.
> I even tried removing .gtk* and that didn't work either.

Seems that the problem with the `.dmrc` is just another one that came out of the fountain of issues :smile:

And one that could be most easily be produced.

@aaronduino Are you on IRC/Freenode or Matrix?
I could be more help to you there, where passing around logs like this might not
produce results in a timely matter for the both of us.

---
##### Notice to maintainers

Completely unrelated to this, but I caught it from the latest lightdm-gtk-greeter logs.

we should probably add these flags to `lightdm-gtk-greeter`
```
--disable-indicator-services-command
--disable-at-spi-command
```

or instead of `--disable-at-spi-command`
```
 --enable-at-spi-command=${at-spi2-core}/libexec/at-spi-bus-launcher
```

But that would change the current behavior to actually starting it, and maybe it shouldn't.

**Comment by jtojnar** [comment]
Is not starting the accessibility bus necessary to allow accessibility functions in the greeter? I would consider the unavailability of a11y bus to be a bug.

**Comment by worldofpeace** [comment]
> Is not starting the accessibility bus necessary to allow accessibility functions in the greeter? I would consider the unavailability of a11y bus to be a bug.

I can enable the `Large Font` and `High Contrast` features in that greeter. 
Are their other one's for that greeter?

**Comment by aaronduino** [comment]
@worldofpeace my matrix account is `@aaronduino:matrix.org`

**Comment by worldofpeace** [comment]
Ok found out there was an `.xsession` script so it took precedence and failed in a particularly interesting appearance.

So it seems a lot of our users like a lightweight windowmanager, (i3 in this case) and DE.


Also noticed that  `org.freedesktop.Accounts.User.Session` was `== plasma5` from a last session?
Don't know about that, but not using an `.xsesison` script fixed this, so I think it's safe to close.

**Comment by erobl** [comment]
I just updated to 19.03 and tried to set up both `pantheon.elementary-greeter` and `lightdm-enso-os-greeter`. It keeps freezing whenever they load up. I deleted `.dmrc` and made sure to not have any `.xsession` scripts or any startup scripts other than whatever i3 does. I am using i3, if that is relevant.

**Comment by worldofpeace** [comment]
I've disabled pantheon's greeter because it's problematic when switching desktopManagers
* https://github.com/NixOS/nixpkgs/commit/9fa96de60990a99757a1d14cdf75e131e0c2b649
* https://github.com/NixOS/nixpkgs/commit/c7de6984f5c35e135dae6f8602cfd5b8c5d17702
* https://nixos.org/nixos/manual/release-notes.html#note

Do you have those commits, and have you tried just using the default gtk lightdm greeter?

Beyond that I can't help much more without logs.

**Comment by aaronjanse** [comment]
Heads up I've never been able to get Pantheon to work with i3.

If it's not expected to work, maybe there should a nix assertion that says so?

-------- Original Message --------

**Comment by worldofpeace** [comment]
Yeah there's no configuration for i3+pantheon.
Someone could do gnome-flashback and i3. but we can't use it without gnome-shell yet #54415

> If it's not expected to work, maybe there should a nix assertion that says so?

I don't think there's anything to assert on. If someone enables pantheon and also i3 windowmanager
they could start either session interchangeably. Wasn't made to intersect.

Though it seems a lot of nixos users want things like https://github.com/NixOS/nixpkgs/blob/2fcb11a2442b27834db87b2f62511037c31b5e36/pkgs/desktops/gnome-3/misc/gnome-flashback/default.nix so maybe we should make that generic to make any gnome-session.

**Comment by erobl** [comment]
> Do you have those commits
No idea, I'm on the 19.03 channel with nonlocal nixpkgs
> have you tried just using the default gtk lightdm greeter?
That's what I'm using currently, I wanted to try out something that looked a bit nicer, but gtk works fine.
