### ISSUE TITLE
nginx: non-HTTPS vhosts are broken

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#57324]
04425c62230a1c8e60e61c9c0d4c564d40ebd263 broke all of my nginx vhosts that serve content on port 80 and do not automatically redirect the client to port 443. This includes all of my sites that use auto-ACME renewal from Let's Encrypt.

Listen directives that used to look like this:

```listen 0.0.0.0:80 ;```

now look like this:

```listen 0.0.0.0:80 http2 ;```

Clients such as `wget` and the Let's Encrypt certbot don't seem to support/expect http2 on port 80.

To confirm that this is the issue, I've disabled the nginx NixOS module from nixpkgs master and replaced it with a version identical to the NixOS module prior to 04425c62230a1c8e60e61c9c0d4c564d40ebd263, and port 80 vhosts work again.

[edit for clarity]

**Comment by w4** [comment]
Looks like this is as simple as changing http2 to default to false in [vhost-options] (https://github.com/NixOS/nixpkgs/blob/04425c62230a1c8e60e61c9c0d4c564d40ebd263/nixos/modules/services/web-servers/nginx/vhost-options.nix#L142) or setting it yourself in your vhost block.

Is there a way we can make this default to true if we're using SSL and default to false if we're not but **not** override it like the previous functionality?

**Comment by ArdaXi** [comment]
I feel like the simplest way to support this would be to have a separate setting to specifically indicate whether you want http2 where `ssl = false`.

I'm not aware of any major browser that supports HTTP/2 without encryption, so for most users a listen directive without ssl but with http2 is highly undesirable. Given that consideration, having to put an extra option in each vhost when http2 is wanted without encryption does not seem unreasonable.

I would do something like

```
+ optionalString (ssl && vhost.http2) "http2 "
+ optionalString (!ssl && vhost.http2-plain) "http2 "
```
