### ISSUE TITLE
nix-build Cargo.nix fails

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#57379]
## Issue description

Running `nix-build Cargo.nix -A hello` following the "User's Guide to the Rust Infrastructure" in Nix Manual fails regarding pkg-config (https://gist.github.com/573/bfed92ee79c7658708557618c93f3786#file-logfile-L91) although "missing library" is installed (https://gist.github.com/573/bfed92ee79c7658708557618c93f3786#file-logfile-L115).

### Steps to reproduce

https://gist.github.com/573/bfed92ee79c7658708557618c93f3786#file-readme-md

## Technical details

> $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-17134-Microsoft, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(dkahlenberg): `"nixpkgs-19.03pre167327.11cf7d6e1ff"`
 - nixpkgs: `/home/dkahlenberg/.nix-defexpr/channels/nixpkgs`

**Comment by samhug** [comment]
I found this issue while trying to package the same crate. [This](https://github.com/samhug/nixos-overlay/tree/6e11e1a01d4f2ba61408494e1fde73e5dde891e7/pkgs/evcxr_jupyter) is what I came up with. The key for me was https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#handling-external-dependencies

**Comment by 573** [comment]
@samhug I am still not yet there. Can you outline shortly what you did to make it working or how to use your overlay to build the crate "the nix way"?
I have generated the Cargo.nix and the crates-io.nix as outlined in the docs.
What now instead of the nix-build call?
(when running nix-build with the default.nix from your overlay repository I get an error but even when changing the default.nix header to standalone I have no luck)

**Comment by samhug** [comment]
Running the following should work without installing my overlay.
```
$ mkdir evcxr_jupyter
$ cd evcxr_jupyter

$ wget https://raw.githubusercontent.com/samhug/nixos-overlay/6e11e1a01d4f2ba61408494e1fde73e5dde891e7/pkgs/evcxr_jupyter/Cargo.nix
$ wget https://raw.githubusercontent.com/samhug/nixos-overlay/6e11e1a01d4f2ba61408494e1fde73e5dde891e7/pkgs/evcxr_jupyter/crates-io.nix
$ wget https://raw.githubusercontent.com/samhug/nixos-overlay/6e11e1a01d4f2ba61408494e1fde73e5dde891e7/pkgs/evcxr_jupyter/default.nix

$ nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'

$ ./result/bin/evcxr_jupyter --help
```

I bumped the version in my overlay prematurely without fully testing it. The above references the older version that's been working for me.

The way I came up with that is by running the following
```
$ git clone https://github.com/google/evcxr.git
$ cd evcxr
$ git checkout v0.3.5

$ cargo generate-lockfile
$ nix-shell -p carnix --command 'carnix generate-nix --src ./.'
```
Then I took the generated `Cargo.nix` and `crates-io.nix` and using existing rust packages in nixpkgs as examples created the `default.nix` file.
```nix
{ callPackage, fetchFromGitHub, pkgconfig, buildRustCrateHelpers, defaultCrateOverrides, zeromq }:
with buildRustCrateHelpers;
let
  evcxr-src = fetchFromGitHub {
    owner = "google";
    repo = "evcxr";
    rev = "f375d872bb8560117780e7b9b83e9692e2cebb0e";
    sha256 = "19yaamv10dzgknjpwsilxd0s2hq60qxgjlcwsvvz63cxr6q3mjbh";
  };

  cratesIO = callPackage ./crates-io.nix {};

  _crates = callPackage ./Cargo.nix { inherit cratesIO; };

  evcxr_jupyter = (_crates.evcxr_jupyter {}).override {
    crateOverrides = defaultCrateOverrides // {
      evcxr = attrs: { src = evcxr-src; };
      evcxr_jupyter = attrs: { src = evcxr-src; };
      zmq-sys = attrs: { buildInputs = [ zeromq pkgconfig ]; };
    };
  };
in
  evcxr_jupyter
```

The overrides were what I struggled with. The derivation that `carnix` generates doesn't fetch the source of the crate you're building so you have to override the derivation and insert the source. Based on the error messages I was getting and looking at other rust packages in nixpkgs I found out I also needed to override the `zmq-sys` crate and add the `zeromq` and `pkgconfig` build dependencies.

**Comment by 573** [comment]
That is really compehensive @samhug, exactly what I was looking for! Now I got it to work. Thank you so much!
