### ISSUE TITLE
tig doesn't depend on git

### ISSUE THREAD

**Issue by maxigit** [NixOS/nixpkgs#5741]
I'm new to nixos and I tried to install `tig` (a `git` CLI). Surprisingly, installing `tig` doesn't install `git`.
I know technically, you don't need to `git` to build `tig`, but you can't run `tig` without `git`. Moreover some version of `tig` might expect some version of `git` to work.
So one can say that there is a "soft runtime dependency" between the to software.

So my question is, is the fact that there is no dependency between `tig` and `git` and mistake or a design choice ?

**Comment by rycee** [comment]
Seems like a mistake to me. I gave fixing it a go in the above pull request.

**Comment by maxigit** [comment]
Thanks.
