### ISSUE TITLE
relax platform definition for smenu?

### ISSUE THREAD

**Issue by abathur** [NixOS/nixpkgs#57410]
[Smenu](../blob/master/pkgs/tools/misc/smenu/default.nix) is currently set to just `platforms.linux`, but I was able to build it fine with `allowUnsupportedSystem = true` on macos (10.14.3) and haven't run into any issues running very basic commands so far.

**Comment by veprbl** [comment]
Would you mind making a pull request?

**Comment by abathur** [comment]
I don't, but I'm not in the loop and won't be of much use if it's any more involved than changing it to `platforms.all`.

**Comment by veprbl** [comment]
> smenu can be built on every system where a working terminfo development platform is available. This includes every Unix and Unix-like system I am aware of.

So perhaps should be just `platforms.unix`.
