### ISSUE TITLE
Pytorch doesn't build on unstable channel

### ISSUE THREAD

**Issue by Kjuvi** [NixOS/nixpkgs#57420]
## Issue description

python37Packages.pytorch don't build on the unstable channel (I think the problem comes from ```which```, which should be a ```nativeBuildInput```). I tried to build it with ```nix-build -A python37Packages.pytorch``` on the master branch, and everything seems fine here.

Is it possible to backporting it ?

### Steps to reproduce

```nix-env -i python3.7-pytorch```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 19.09pre172038.5d3fd3674a6 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(kjuvi): `""`
 - channels(root): `"nixos-19.09pre172038.5d3fd3674a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Yes, we're currently stabilizing the release, and any fixes that fix build will be backported.

**Comment by worldofpeace** [comment]
Seems to build on master and 19.03
- https://hydra.nixos.org/job/nixpkgs/trunk/python37Packages.pytorch.x86_64-linux
- https://hydra.nixos.org/job/nixos/release-19.03/nixpkgs.python37Packages.pytorch.x86_64-linux
