### ISSUE TITLE
termtosvg: tests are now available from pypi

### ISSUE THREAD

**Issue by nmattia** [NixOS/nixpkgs#57433]
## Issue description

Apparently the `termtosvg` tests are now available through pypi (see [this comment](https://github.com/nbedos/termtosvg/issues/91#issuecomment-468906950)). I don't exactly understand what this means but thought I'd forward to @Ma27 !

**Comment by jtojnar** [comment]
That means we can now use `fetchPypi` instead of `fetchFromGitHub`, which is preferred for Python packages:

https://github.com/NixOS/nixpkgs/blob/c6ed0f964bdfb322fc19f1b2bb1f787119f54738/pkgs/tools/misc/termtosvg/default.nix#L8-L13
