### ISSUE TITLE
SSL certificate issues on unstable/19.09

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#57467]
## Issue description

Since updating to nixos-unstable 19.09 (commit 5d3fd3674a66c5b1ada63e2eace140519849c967), I can no longer use `nixos-rebuild` to update my system, or `nix-channel` to switch to the 19.03 branch.

The errors are all the same:

```
$ nix-channel --update
unable to download 'https://nixos.org/channels/nixos-19.03': Problem with the SSL CA cert (path? access rights?) (77)
```

Curl itself emits that same error when fetching the channel tarball manually.

I've tried all permutations of the `NIX_SSL_CERT_FILE`, `SSL_CERT_FILE`, and `CURL_CA_BUNDLE` environment variables with both `/etc/ssl/certs/ca-bundle.crt` and `/etc/ssl/certs/ca-certificate.crt`.

I've tried setting these for the command invocation via bash, through exporting, and through `systemctl set-environment`.

Please let me know if I can provide more information.

### Steps to reproduce

- `nix-channel --add https://nixos.org/channels/nixos-unstable nixos`
- `nixos-rebuild switch --upgrade`

## Technical details

I cannot run `nix-info` as `nix-channel --update` deletes the channel if the update fails, so I no longer have channels on NIX_PATH.

**Comment by FRidh** [comment]
Do you have `cacert` installed in your system-wide profile?

**Comment by tadfisher** [comment]
@FRidh I do not have it explicitly installed (it's not in `environment.systemPackages`, and not explicit via `nix-env -i`).

The certificates do exist in `/etc` and `/run/current-system/etc` though.

**Comment by tadfisher** [comment]
@FRidh I believe I have fixed the cause of the problem by running the following:

```
# NIX_SSL_CERT_FILE=/root/cacert.pem nixos-rebuild switch --upgrade --repair
```

There were several paths that ended up being repaired, and now `nix-channel` and other commands work again without the env var set, so I think we can chalk this up to store corruption.

**Comment by lheckemann** [comment]
>I think we can chalk this up to store corruption.

:)
