### ISSUE TITLE
gst_plugins_good doesn't have libsoup support

### ISSUE THREAD

**Issue by puffnfresh** [NixOS/nixpkgs#5749]
It looks like libsoup is not added to the `PKG_CONFIG_PATH` during the build. How are paths put on there usually?

**Comment by vcunat** [comment]
- For gst-1 the logs show libsoup is detected and used,
- for gst-0.10 it isn't in ``buildInputs``.

**Comment by puffnfresh** [comment]
I just noticed that:

```
gst_plugins_good = callPackage ../development/libraries/gstreamer/legacy/gst-plugins-good {};
```

So we have two different expressions for the same package. I'm guessing libsoup isn't an input on the legacy one.

**Comment by puffnfresh** [comment]
@vcunat thank you!
