### ISSUE TITLE
sqlite manager doesn't contain sqlite

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#57564]
## Issue description

sqlite manager doesn't contain sqlite :s 
```
nix run nixos-unstable.sqliteman
$ sqliteman
Checking for  sqlite3 : 
Sqlite3 executable '%1' is not found in your path. Some features will be disabled. 
Checking for Qt version:  4.8.7 
Initial DB:  "" 
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
```
I think it's strange, any reason why not ? @eikek 
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.70, NixOS, 19.09.git.15b2ad5 (Loris)`

**Comment by eikek** [comment]
Oh… :-) I had no reason; just lack of knowledge on my site at that time. I gues one can add the current `sqlite3` in nixpkgs as an option or such to the build.

**Comment by teto** [comment]
I ended up using sqlitebrowser which is the one I was looking for but couldn't remember the name ty
