### ISSUE TITLE
update.nix: Allow creating commits

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#57609]
Since we [parallelized](https://github.com/NixOS/nixpkgs/pull/50977) update.nix, the update scripts can no longer commit. This is annoying with large attrsets like `gnome3`. Adding files to index, writing a commit message header (`pname: old → new`) is a lot of automatable effort.

Ideally, the script would even allow to create squash commits when new version is released before the branch is merged to master.

cc @worldofpeace

**Comment by worldofpeace** [comment]
Yeah I totally agree that we should spend time getting this, as to not waste time with manually doing all of that. It's also more prone it human error due to the drone like nature of it.

> Ideally, the script would even allow to create squash commits when new version is released before the branch is merged to master.

Yep also a chore too automate :+1:

**Comment by worldofpeace** [comment]
Btw, I can't find the discussion with why we couldn't do this because of the parallelization?

**Comment by jtojnar** [comment]
Git does not like it when you run multiple commands simultaneously.

**Comment by jtojnar** [comment]
Still on my to-do list. WIP: https://github.com/NixOS/nixpkgs/pull/59372
