### ISSUE TITLE
common-updater-scripts: add fetchgit support

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#57610]
When I try to update some package that uses `fetchgit`, it fails.

```ShellSession
$ update-source-version volume_key 0.3.12
error: attribute 'urls' missing, at (string):1:37
update-source-versions: error: Couldn't evaluate source url from 'volume_key.name'!
```

**Comment by jtojnar** [comment]
This was fixed by @NeQuissimus in https://github.com/NixOS/nixpkgs/commit/cce486838b6c52dedfec1c93f60ebadb72c48431

**Comment by NeQuissimus** [comment]
My bad, I had not even seen this issue before :)
I did run into the same thing and just fixed it :D
