### ISSUE TITLE
Invalid syntax of GDM dconf profile

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#57616]
As mentioned in https://github.com/NixOS/nixpkgs/issues/54150, https://github.com/NixOS/nixpkgs/commit/1af8f3a980bb8ac92f5c09ac23cca4781571bcd1 broke the syntax of GDM dconf profile.

* https://developer.gnome.org/dconf/unstable/dconf-overview.html#id-1.2.5
* https://gitlab.gnome.org/GNOME/dconf/blob/9c4a4f2baef7c35934a8b05fb61148f0a356940d/engine/dconf-engine-profile.c#L110-138
* https://gitlab.gnome.org/GNOME/dconf/blob/9c4a4f2baef7c35934a8b05fb61148f0a356940d/engine/dconf-engine-source.c#L74-128

https://github.com/NixOS/nixpkgs/blob/cd29409a4594ce0fbe82e375ae921c1f6d41a7f6/nixos/modules/services/x11/display-managers/gdm.nix#L157-L160

```
Mar 14 01:18:29 nixos .gsd-color-wrap[866]: unknown dconf database description: /nix/store/95j1l8952q7k4k1dpx0ah3rv8vh90csk-gdm-3.30.3/share/dconf/profile/gdm
Mar 14 01:18:29 nixos .gsd-color-wrap[866]: unable to open file '/etc/dconf/db/local': Failed to open file “/etc/dconf/db/local”: open() failed: No such file or directory; expect degraded performance
```

**Comment by jtojnar** [comment]
We should probably concatenate our `system-db` definition with the original profile. And only when we are creating the database.

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/63790 fixed this
