### ISSUE TITLE
OBS Studio not providing full source in `include`

### ISSUE THREAD

**Issue by skwerlman** [NixOS/nixpkgs#57627]
## Issue description
Only the `libobs` source is included in `${obs-studio}/include`.

### Steps to reproduce
Install obs-studio

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.1, NixOS, 19.09.git.2556b7b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre172038.5d3fd3674a6"`
 - channels(skw): `"nixos-19.09pre171945.b36dc66bfea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

I am currently trying to compile the [Advanced Scene Switcher](https://github.com/WarmUpTill/SceneSwitcher/) plugin. This plugin requires access to parts of OBS's UI source code, specifically `UI/obs-frontend-api/`. This folder is located at the root of the repo and so doesnt get copied with the rest of the sources.

**Comment by NilsIrl** [comment]
CC @jb55 @MP2E

**Comment by NilsIrl** [comment]
I'm trying to upgrade obs-wlrobs and I get the following error:

```
Run-time dependency libobs found: NO
```

**Comment by NilsIrl** [comment]
For it to work, libX11 has to be used as buildInput. This isn't a proper solution as the whole point of wlrobs is to not use X but wayland

**Comment by fpletz** [comment]
The obs source is available as `obs-studio.src` if needed. The new OBS major version changed some packaging infrastructure stuff. Please reopen if this is still an issue.
