### ISSUE TITLE
Changing requiredSystemFeatures changes hash

### ISSUE THREAD

**Issue by timor** [NixOS/nixpkgs#57649]
In our setup, a hydra instance provides pre-built packages for all our necessary NixOS configuration, CI, etc...

We encountered a problem when we needed finer control over which build host gets assigned certain build steps.  Specifically rustc was repeatedly assigned to a machine that could not handle it.  (`big-parallel` had not been added to `rustc` on that nixpkgs channel).  To work around that, we changed the `requiredSystemFeatures` attribute in an overlay, to make sure the build does not fail because of resource restrictions.

Unfortunately, this changes the hash of the derivation, and thus all downstream dependencies.  This means that the official binary cache cannot serve these packages anymore, as only our local binary cache produces them, although nothing in the final artifacts is different from the original package(s).

As far as I can tell, `requiredSystemFeatures` should not have any influence on the artifact itself, only on the way it is built.  If that is the case, would it be feasible to have it not influence the resulting hash?

If not, is there any other way to influence per-package hydra behavior?

Possibly related: #16263

**Comment by timor** [comment]
cc @spacefrogg

**Comment by 7c6f434c** [comment]
>As far as I can tell, `requiredSystemFeatures` should not have any influence on the artifact itself, only on the way it is built.  If that is the case, would it be feasible to have it not influence the resulting hash?

If you pass it to `mkDerivation`, it is a variable available to the build script via environment.

Maybe this indeed should be changed (but this would also be a Hydra change, I guess)

**Comment by matthewbauer** [comment]
This is a Nix issue.

**Comment by timor** [comment]
Done.
