### ISSUE TITLE
haskellngPackages: Should `env` provide `cabal-install`?

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#5764]
The new `haskellngPackages` gives us the very nice `env` attribute, and when combined with `cabal2nix --shell` it's trivial to enter a build environment for projects. However, the build environment doesn't contain `cabal` itself, which means that we have to manually edit the `shell.nix` to bring that tool in.

@peti, what do you think about having `env` always depend on `cabal-install`?

**Comment by peti** [comment]
IMHO it's better to install `cabal-install` into your normal profile and to start `nix-shell` without `--pure`. That works fine for me, and the generated environment doesn't befenit on the `--pure` flag. Adding `cabal-install` into the generated expression would cause all kinds of trouble for packages that are dependencies of `cabal-install`, obviously, and I woudn't know to resolve that.

I suppose we could add some boolean flag to the generated `shell.nix` file, say `withCabal`, and include `cabal-install` when the user specifies that flag on the command line. Then the choice is up to the user ...

**Comment by ocharles** [comment]
I see [here](http://article.gmane.org/gmane.linux.distributions.nixos/15524) you demonstrate just building `Setup.hs`, but for day-to-day Haskell development this isn't particularly standard.

**Comment by ocharles** [comment]
Heh, nice timing! Using a non-pure enivorment could work, but I've had problems in the past with other Haskell executables I use interfering with my build env. However, now that we're not relying on the wrapper - maybe all those problems are solved?

**Comment by peti** [comment]
Yes, those problems are solved. The `nix-shell` environment does essentially nothing except prepending the new `ghc` binary to your `$PATH` so that it's found before the one you normally use.

**Comment by ocharles** [comment]
Awesome, in that case lets close this - I'm happy with that solution. Thanks for helping (and all the awesome work you're doing at the moment!)

**Comment by peti** [comment]
You're welcome. :-)
