### ISSUE TITLE
Google Chrome missing glyphs

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#57643]
## Issue description
In Google Chrome, I seem to be missing some glyphs. 

![image](https://user-images.githubusercontent.com/45791182/54368667-d9753a80-4674-11e9-84d1-846938540993.png)

How can I resolve that? 

### Steps to reproduce
Go to https://www.nginx.com/free-trial-request 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.git.4c089d3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Works here. Please provide more details if the issue persists
