### ISSUE TITLE
How do I regenerate hackage-packages.nix?

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#5765]
Hi @peti,

How does one regenerate `hackage-packages.nix`? I'm at `nixpkgs` 50640b18faa427890835fa3595317546c376243d and I've installed `cabal2nix` from this checkout. I see this gives me a `hackage2nix`, but when I run this I get a lot of differences that aren't just version changes. E.g.,

```diff
   "ALUT" = callPackage
-    ({ mkDerivation, base, freealut, OpenAL, OpenGL }:
+    ({ mkDerivation, alut, base, OpenAL, OpenGL }:
      mkDerivation {
        pname = "ALUT";
        version = "2.3.0.2";
        sha256 = "02kfyb4g7sfjfzqlddxqbjffrj4a0gfrzkisdpbj2lw67j1gq5dp";
        buildDepends = [ base OpenAL OpenGL ];
-       extraLibraries = [ freealut ];
+       extraLibraries = [ alut ];
        configureFlags = [ "-fusenativewindowslibraries" ];
        homepage = "https://github.com/haskell-openal/ALUT";
        description = "A binding for the OpenAL Utility Toolkit";
        license = stdenv.lib.licenses.bsd3;
-     }) { inherit (pkgs) freealut;};
+     }) { alut = null; };
```

Any idea what I'm doing wrong?

**Comment by ocharles** [comment]
Ok, I installed `cabal2nix-dirty` - and that fixes the `alut` changes and I think it's just updates now.

**Comment by peti** [comment]
Detailed usage instructions for `hackage2nix` including a sample command line how to run it can be found here: https://github.com/NixOS/cabal2nix/blob/master/src/hackage2nix.hs#L1 :smile:

**Comment by ocharles** [comment]
There's certainly no room for interpretation error, that's for sure :)
