### ISSUE TITLE
Difference between python3Packages & python37Packages

### ISSUE THREAD

**Issue by freezeboy** [NixOS/nixpkgs#57654]
## Issue description

In unstable and nixos-19.03, `python3Packages` is defined as follows:

```nix
python3Packages = python3.pkgs;
```

But ` python37Packages` is defined differently :

``` nix
python37Packages = recurseIntoAttrs python37.pkgs;
```

I don't really understand why this difference

as a result we don't find the same package sets in both attribute-sets

**Comment by xeji** [comment]
cc @FRidh

**Comment by dotlambda** [comment]
If I'm not mistaken, the only difference is that everything using `recurseIntoAttrs` will be shown by `nix-env -qa` and built by Hydra. For you, specifying `python3Packages.somepkg` versus `python37Packages.somepkg` won't make any difference until we update our default Python 3 version.
