### ISSUE TITLE
davmail crash on startup on master

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#57673]
## Issue description
When I try to run davmail from nixos-unstable it crashes immediately after executing.

Looks similar to https://github.com/NixOS/nixpkgs/issues/52302

ping @Infinisil simply because he said this on IRC:
[18:03] \<infinisil\> aanderse: That doesn't look good, seeing that libc there makes me think it's a libc problem, I think there's been some problems with that in the past

### Steps to reproduce
$(nix-build --no-out-link channel:nixos-unstable -A davmail)/bin/davmail
unpacking 'https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz'...

(java:2454): Gtk-WARNING **: 17:58:11.204: Unable to locate theme engine in module_path: "adwaita",

(java:2454): Gtk-WARNING **: 17:58:11.210: Unable to locate theme engine in module_path: "adwaita",
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  SIGSEGV (0xb) at pc=0x00007faece0274bd, pid=2454, tid=0x00007faea671d700
\#
\# JRE version: OpenJDK Runtime Environment (8.0_202) (build 1.8.0_202-ga)
\# Java VM: OpenJDK 64-Bit Server VM (25.202-bga mixed mode linux-amd64 compressed oops)
\# Problematic frame:
\# C  [libc.so.6+0x9f4bd]  __memcpy_sse2_unaligned_erms+0xfd
\#
\# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
\#
\# An error report file with more information is saved as:
\# [/home/aaron/hs_err_pid2454.log](https://github.com/NixOS/nixpkgs/files/2968802/hs_err_pid2454.log)
\#
\# If you would like to submit a bug report, please visit:
\#   http://bugreport.java.com/bugreport/crash.jsp
\# The crash happened outside the Java Virtual Machine in native code.
\# See problematic frame for where to report the bug.
\#
Aborted

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 18.09.2327.37694c8cc0e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2327.37694c8cc0e, nixos-unstable-19.09pre172038.5d3fd3674a6"`
 - channels(aaron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
As already mentioned on IRC, I can't reproduce this, it launches just fine for me.

What does `nix-instantiate --eval '<nixpkgs/nixos>' -A pkgs.glibc.name` evaluate to for you? It's "glibc-2.27" for me.

**Comment by aanderse** [comment]
@Infinisil I get the same value on my system.

**Comment by bbigras** [comment]
I have the same problem when trying to start unstable.android-studio.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 18.09.2327.37694c8cc0e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(bbigras): `"home-manager-18.09, unstable-19.09pre172038.5d3fd3674a6"`
 - channels(root): `"nixos-18.09.2327.37694c8cc0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by aanderse** [comment]
Is there a java issue with mixing stable and unstable channels I have to wonder. I'll upgrade a box to run only unstable and see if davmail runs without crashing.

**Comment by aanderse** [comment]
strace of output: [davmail.txt](https://github.com/NixOS/nixpkgs/files/2998879/davmail.txt)

**Comment by aanderse** [comment]
@samueldr says (on irc) https://github.com/NixOS/nixpkgs/issues/54278 is the cause of this.

**Comment by samueldr** [comment]
* https://logs.nix.samueldr.com/nixos/2019-03-23#1553304234-1553304449;

**Comment by aanderse** [comment]
This isn't an issue for me anymore and I was able to run `davmail` on the latest stable release of nixos so closing.
