### ISSUE TITLE
mkl: incorrect install_name on Darwin

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#57697]
## Issue description

On Darwin, build `numpy` with `mkl` support fails with the following error message:

```
running install tests
/private/var/folders/r2/zwnv7zsd4bd99mqkn4mhqxn800034l/T/nix-build-python3.7-numpy-1.16.1.drv-0/numpy-1.16.1/dist /private/var/folders/r2/zwnv7zsd4bd99mqkn4mhqxn800034l/T/nix-build-python3.7-numpy-1.16.1.drv-0/numpy-1.16.1
Traceback (most recent call last):
  File "/nix/store/hkc0b2xa80jwahgbpc1hnlizhn2fs79k-python3.7-numpy-1.16.1/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/nix/store/hkc0b2xa80jwahgbpc1hnlizhn2fs79k-python3.7-numpy-1.16.1/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/nix/store/hkc0b2xa80jwahgbpc1hnlizhn2fs79k-python3.7-numpy-1.16.1/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/nix/store/hkc0b2xa80jwahgbpc1hnlizhn2fs79k-python3.7-numpy-1.16.1/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libmkl_rt.dylib
  Referenced from: /nix/store/hkc0b2xa80jwahgbpc1hnlizhn2fs79k-python3.7-numpy-1.16.1/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: image not found
```

### Steps to reproduce

Create the following overlay (as per the documentation):

```
self: super: {
  python37 = super.python37.override {
    packageOverrides = python-self: python-super: {
      numpy = python-super.numpy.override {
        blas = super.pkgs.mkl;
      };
    };
  };
}
```

and then build the package:

```
nix-build '<nixpkgs>' -A python3Packages.numpy
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.3`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(smaret): `"nixpkgs-19.03pre170546.0f43790d2ce"`
 - nixpkgs: `/nix/store/pinfra2z615k0452ya61daqcdg9vxidm-master.tar.gz`

**Comment by smaret** [comment]
CC @costrouc @FRidh

**Comment by LnL7** [comment]
The `@rpath` probably indicates an invalid install_name for libmkl_rt.dylib nothing with the numpy build itself.

**Comment by smaret** [comment]
Indeed, the install_name is `@rpath/libmkl_rt.dylib`. I was able to fix it with the following `postInstallPhase` in the mkl package:

```
  postInstallPhase = if setdenv.isDarwin then ''
      for f in $out/lib/*.dylib; do
          install_name_tool -id $out/lib/`basename $f` $f
      done
  '';
```

CC @bhipple

**Comment by smaret** [comment]
With the `postInstallPhase` above, `numpy` build phase succeeds, but the check phase fails:

```
/private/var/folders/r2/zwnv7zsd4bd99mqkn4mhqxn800034l/T/nix-build-python3.7-numpy-1.16.1.drv-0/numpy-1.16.1/dist /private/var/folders/r2/zwnv7zsd4bd99mqkn4mhqxn800034l/T/nix-build-python3.7-numpy-1.16.1.drv-0/numpy-1.16.1
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
builder for '/nix/store/kkdqqdgvsjq461yb0vxy2pz004d8h3qc-python3.7-numpy-1.16.1.drv' failed with exit code 2
error: build of '/nix/store/kkdqqdgvsjq461yb0vxy2pz004d8h3qc-python3.7-numpy-1.16.1.drv' failed
```

**Comment by LnL7** [comment]
Perhaps libmkl_intel_thread.dylib isn't located in $out/lib and not patched because of that? Using `buildInputs = [ fixDarwinDylibNames ];` will do about the same thing as your snipped, but also just looks at `/lib` and might not be usable if that's the issue. Incorrect install_names are often a problem, I described it briefly here https://nixos.org/nixpkgs/manual/#sec-darwin.

**Comment by smaret** [comment]
I didn't know about `fixDarwinDylibNames`, thanks for pointing it to me. It does not seem to work in `stdenvNoCC` that `mkl` is using. Is it intended, or is it a bug?

**Comment by LnL7** [comment]
That's unexpected, but I guess it might depend on one of the tools omitted in the stdenv without cc.

**Comment by matthewbauer** [comment]
You can use install_name_tool with ```${darwin.cctools}/bin/install_name_tool```. Maybe we should hardcode it in fixDarwinDylibNames for this case?

**Comment by matthewbauer** [comment]
Although the same thing would probably happen with autoPatchelf
