### ISSUE TITLE
ghidra: "Problem launching decompiler"

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#57769]
## Issue description

When analyzing a binary, ghidra repeatedly pops "Problem launching decompiler" error messages, due to the following issue:

```
java.io.IOException: Cannot run program "/nix/store/c9wx72a373syghznsj5w2vkm6v66kcwf-ghidra-9.0/lib/ghidra/Ghidra/Features/Decompiler/os/linux64/decompile": error=2, No such file or directory
```

Seems like a packaging issue of some sort with the decompiler. It's distributed as an ELF blob and likely needs some interpreter path patching.

### Steps to reproduce

Try using ghidra.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.1-hardened, NixOS, 19.09.git.53bbb34 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(delroth): `""`
 - nixpkgs: `/home/delroth/work/nixpkgs`

**Comment by markuskowa** [comment]
CC @ck3d
