### ISSUE TITLE
Vulkan applications no longer work

### ISSUE THREAD

**Issue by shirona** [NixOS/nixpkgs#57770]
## Issue description
Ever since I updated to `19.09pre172943.da1a2b1eeaf (Loris)`, none of my Vulkan-rendered applications will render anything. Last known working version was `19.03pre169108.36f31600749 (Koi)`. The following are the results of my "tests", both in Loris and Koi.

| Program | Loris | Koi |
| --- | --- | --- |
| DotA 2 run with parameter `-vulkan` | Gets stuck on the gray pre-loading screen after setting the hardware cursor | Works flawlessly |
| DotA 2 run with the vanilla OpenGL renderer | Works flawlessly | Works flawlessly |
| The Elder Scrolls Online, via Proton with DXVK (Vulkan), any Proton version | Music plays, but doesn't render anything. The game runs, but doesn't seem to react to input | Works flawlessly |
| The Elder Scrolls Online, via Proton with WINED3D (OpenGL), Proton 3.16-8 | Runs with a few graphical glitches | Runs with the same graphical glitches |
| Dolphin Emulator with Vulkan backend | First time looked like it was about to render something, but the textures were corrupted and stopped updating the frame soon afterwards | Doesn't seem to work, even in the older version |
| RetroArch with Vulkan backend | Renders the "wave" in the background of RetroArch's launcher over a black window. It stops rendering soon afterwards | Works flawlessly |
| RetroArch with OpenGL backend | It seems not even the OpenGL background works in the latest version. Doesn't have quite the same "frame freeze" as with the Vulkan engine, but for all intents and purposes it is the same behaviour | Works flawlessly |

I am not quite sure Vulkan is the culprit here, as Dolphin never worked with the Vulkan backend in my configuration, and neither does RetroArch work at all in Loris, but I suspect the issue is indeed with Vulkan, or at the very least, the Mesa drivers, which updated from 18.3.1 to 18.3.4 in that time period. LLVM also made the jump to 7.0.1 from 6.0.1 in that time period.

If you can think of any other Vulkan tests I can run (preferably in the Nix repositories), please let me know.

## Technical details
- Linux 4.14.98, 4.14.106 in Loris.
- AMD R9 380 with amdgpu drivers.
- Mesa 18.3.1 in Koi, 18.3.4 in Loris.
- RetroArch 1.7.5 in both generations.
- i3 WM 4.16.1 in both generations.

**Comment by arianvp** [comment]
Is this on NixOS, or just nix on another distro?

**Comment by arianvp** [comment]
> If you can think of any other Vulkan tests I can run (preferably in the Nix repositories), please let me know.
Install `vulkan-tools` . it comes with two test binaries:

```
$ vulkaninfo  # dumps a lot of info about your vulkan install. please paste this here
$ cube # runs a vulkan 3d app that rotates a cube
```

**Comment by worldofpeace** [comment]
>```
>$ cube # runs a vulkan 3d app that rotates a cube
> ```

Binary is actually `vkcube`.

**Comment by shirona** [comment]
@arianvp Yes, it is on NixOS Unstable. I ran your tests, and I am quite surprised to see that vkcube does actually work, both in Loris and Koi. Maybe only some instructions are failing in the latest versions? For the record, glxgears also works well in both generations. Should we update the title of the issue to leave clear it is not an issue affecting all/exclusively Vulkan applications?

I uploaded both outputs of vkinfo to a Gist, because they are huge. I also included a diff between both at the beginning. The most glaring issues are different driver versions, and different LLVM versions.
https://gist.github.com/shirona/8309e09ea15f4d99243b540e7702a3fe

**Comment by arianvp** [comment]
Could you just to be sure check out `linuxPackages_latest` as your Linux kernel?

**Comment by shirona** [comment]
@arianvp I have listed `linuxPackages_latest` (5.0.2 according to uname) as my `boot.kernelPackages`, and the result is interesting, to say the least. The table in the first post still applies to a T, but vkcube no longer works as intended. The cube renders as usual, but it doesn't spin, and can't be closed via i3's window close (it's as if it was capturing window input). They can be closed via xkill (which causes a SIGSEGV), kill (SIGTERM), and Ctrl  + C in the terminal it was executed, so it is not that the program has actually crashed.

All of this makes me think none of the programs are actually unable to render at all, but that they get stuck on the first one or two frames, which for many games happens to be a black frame. It's as if the "stream" became non-writable after the first frame.

Is anyone else experiencing the same issue?

**Comment by shirona** [comment]
Just solved my own question. I have a laptop with near identical configuration to my desktop (obviously, hardware-configuration.nix is different, as well as some other minor differences), and both vkcube and both modes of RetroArch work flawlessly in there, so it may have something to do with the GPU drivers or the CPU. My desktop has a FX-8350 with an AMD R9 380, while my laptop has a 7th Gen Intel (don't remember the exact model right now) and an Nvidia GTX 1050 running Nouveau.

**Comment by arianvp** [comment]
`radv`, the vulkan impl that ships with `mesa` might be the culprit.

AMD also has their own vulkan implementation called `amdvlk`  for linux which is open source
https://www.phoronix.com/scan.php?page=article&item=amdvlk-radv-okt18&num=1

perhaps switching to that fixes the issues?  im not sure how to do so though.  would have to research that a bit

**Comment by shirona** [comment]
@arianvp I have found a [thread on Reddit](https://www.reddit.com/r/archlinux/comments/9ckot5/vulkan_how_to_use_amdvlk_instead_of_radv/e5bcczv) where they mention how to do so. Apparently, you can use an environment variable to load a different driver, like:
```
export VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd64.json"
```
Problem is, when going to `/run/opengl-driver/share/vulkan/icd.d`, the only two files there belong to the Intel implementation, and the "Radeon" (probably `radv`) implementation. Opening ` radeon_icd.x86_64.json` shows a short json, which points to the actual driver at `/nix/store/l82ykh9qpal4yr2szpafiklppwrrbxsk-mesa-noglu-18.3.4-drivers/lib/libvulkan_radeon.so`. Opening said directory shows that there are only shared objects for the Intel implementation and the Radeon implementation, so it seems NixOS doesn't ship `amdvlk` at all.

Given the way Vulkan drivers seem to work, it may be worth trying to just make a package for https://github.com/GPUOpen-Drivers/AMDVLK to make some quick tests. Sadly, from what I am seeing, both Steam and Proton seem to include their own Vulkan drivers, so this may not be the Panacea, but at least it would be the beginning of a patch.

**Comment by arianvp** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/mesa/default.nix seems to have an option to pass the `vulkanDrivers` list which will build up the `icd` path.

**Comment by shirona** [comment]
Small and silly update: using the `VK_ICD_FILENAMES` to load the `radeon_icd.x86_64.json` of Mesa 18.3.1 makes all tests (yes, even the Steam ones, by launching Steam with the environment variable) run without a single issue, and doing the same with the one found in Mesa 18.3.4 causes the same issues. So yes, `radv` seems to be the culprit here, or at the very least, something in Mesa's latest Vulkan drivers. Packaging `amdvlk` and somehow allowing the users to select it as the default might mitigate this.

Looking at Mesa's Bugzilla, nobody seems to have filled a bug similar to mine, so I am not convinced it is a bug upstream, but it's definitely something with the `mesa-noglu-18.3.X-drivers` package.

@arianvp From my understanding, `amdvlk` is not part of the Mesa project. How could it be packaged?

**Comment by arianvp** [comment]
@shirona good question.  I think we should make something like a NixOS module that would set up  `/run/opengl-driver/share/vulkan/` with optional drivers? This is currently done by the rather confusingly named https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/opengl.nix module, which populates it with the drivers from `pkgs.mesa_drivers` for originally opengl but also for vulkan

I don't think it would hurt to make a separate vulkan NixOS module that can load drivers that are not shipped with `mesa`, which the current `opengl` module doesn't seem to allow.

but we should probably let someone who maintains the graphics stuff from NixOS chime in. Though it is not very clear from that module who is normally responsible for that

**Comment by arianvp** [comment]
@shirona oh  in the `opengl` module there seems to be an option that sort of does what we want:

```
      extraPackages = mkOption {
        type = types.listOf types.package;
        default = [];
        example = literalExample "with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau intel-ocl ]";
        description = ''
          Additional packages to add to OpenGL drivers. This can be used
          to add OpenCL drivers, VA-API/VDPAU drivers etc.
        '';
      };
```

However what it currently doesn't do is rewrite the `icd.json` to add the included packages to the vulkan search path

**Comment by arianvp** [comment]
AMDVLK is not really packaged by any other distro yet.  https://repology.org/project/amdvlk/versions  so i'm not very enthusiastic (yet) about including it in NixOS. maybe our safer bet is to figure out what is wrong with `radv` in `mesa`.

**Comment by shirona** [comment]
@arianvp Sorry, been busy these last days. Is there any way I can help debugging this? Right now, I am just getting by setting the `VK_ICD_FILENAMES` variable to the old driver, but it's a flimsy patch. 

Ran some tests by using `--rollback` between the old and new versions, and I can confirm the issue is not with the kernel, or at least per se. Using the newest drivers in the newest kernel, or the older drivers in the newest kernel just produces the same result. 

Some further tests reveal as well that my patch to augment the `DefaultLimitNOFILE` variable only causes a rendering crash with the newest driver on the newest kernel, but using the older drivers with the newest kernel works just right. Funnily enough, the newer drivers with the older kernel with the patch in place still work badly (expected behaviour of the newest drivers, regardless of configuration), but at least they do not cause a crash.

**Comment by arianvp** [comment]
@shirona  Could you try out MESA 19? it is out and seems to have quite some fixes for `radv` https://www.mesa3d.org/relnotes/19.0.1.html

**Comment by arianvp** [comment]
@shirona I Think I have potentially found the cause of your issues in a comment on the PR that bumped the `mesa` and `llvm` versions

Could you try out the following steps and see if it fixes anything?:

> With the AMDGPU driver, I noticed that any program that used Vulkan was crashing for mysterious reasons due to the LLVM version bump, but after looking into it, it turns out this is due to an old file in ~/.cache named radv_builtin_shaders64
> 
> If you simply delete this file, or the 32 bit equivalent on 32-bit OSes, everything goes back to working as normal.
> 
> I'm not sure where to document this bug but I figured if I mention it here it will hopefully help any AMDGPU users who run into this issue

https://github.com/NixOS/nixpkgs/pull/56022#issuecomment-465531259

**Comment by shirona** [comment]
> @shirona I Think I have potentially found the cause of your issues in a comment on the PR that bumped the `mesa` and `llvm` versions. Apparently `radv` leaves a shader cache in `~/.cache` around that doesn't get invalidated when the version bumps...
> 
> Could you try out the following steps and see if it fixes anything?:
> 
> > With the AMDGPU driver, I noticed that any program that used Vulkan was crashing for mysterious reasons due to the LLVM version bump, but after looking into it, it turns out this is due to an old file in ~/.cache named radv_builtin_shaders64
> > If you simply delete this file, or the 32 bit equivalent on 32-bit OSes, everything goes back to working as normal.
> > I'm not sure where to document this bug but I figured if I mention it here it will hopefully help any AMDGPU users who run into this issue
> 
> [#56022 (comment)](https://github.com/NixOS/nixpkgs/pull/56022#issuecomment-465531259)

Yes! That did work! Vulkan programs now run flawlessly with the `mesa'  18.3.4 `radv` drivers, or at least so it seems. I will run more extensive tests today, but at first glance, it seems it has worked.

For the record, and if someone finds this issue and has the same problem as me:
- In `~/.config`, I had `radv_builtin_shaders64`, `radv_builtin_shaders32`, `radv_builtin_shaders`, and `mesa_shader_cache/`. I don't know if `radv_builtin_shaders` and `mesa_shader_cache/`had to be deleted, but I just moved them all.
- If you are using some program like `firejail` with the `private-home` option, or anything that makes a certain directory be mounted as your home folder, remember to remove the files in that directory's `~/.config` as well. I know it sounds obvious, but it took me a while to recall I was running `steam` that way, so just in case, this should save you those seconds of frustration and confusion.

Will comment in some hours if there are any further issues, then I will close the issue. Many thanks for your help, @arianvp!

**Comment by shirona** [comment]
Sorry for commenting so late. Games seem to work well now, even though I am having some weird minute-long stuttering issues from time to time in certain games. I suspect it may be some shader recompiling now that the cache has been deleted, but I will open another issue if it persists, since it's a completely different problem to this one.

Again, many thanks for your help!

**Comment by ikervagyok** [comment]
@shirona can you elaborate on what you needed to do to get `nixos.steam` work with vulkan? i tried deleting `~/.cache/...` and `VK_ICD_FILENAMES=...` as mentioned above. but testing with dota2 only uses opengl for rendering. i believe it worked earlier, but i don't remember. My hardware is a lenovo thinkpad e485 with an amd apu with linux_latest on nixpkgs master/unstable.
Thank you

**Comment by shirona** [comment]
@ikervagyok Did you set the `-vulkan` parameter in `Dota 2`'s launch parameters? This is done by right-clicking on top of its entry in the Steam library, then going `Properties > General tab > Set launch options...`, and adding `-vulkan` to the dialog that pops up.

**Comment by ikervagyok** [comment]
@shirona Thank you and never mind - `Dota 2` needs a `Vulkan DLC`, after installing that this worked.
