### ISSUE TITLE
fetchgit is non-deterministic when given leaveDotGit = true and fetchSubmodules = false

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#5777]
`nix-prefetch-git` is non-deterministic if given both `leaveDotGit = true` and `fetchSubmodules = false`.

Here are a couple runs back-to-back:

    ~/src/nixpkgs (pleasant-ruby) λ nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    d77a4f6c4f57af463bb481c9ea54ad059434e79f7fbfdd4b5a7f71208f2e8383
    
    ~/src/nixpkgs (pleasant-ruby) λ nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    2816a1f50ec43a30c2c01f9e4ac4121f2b6f07e5d5abf2191b960d8865eb8afb
    
    ~/src/nixpkgs (pleasant-ruby) λ nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    ddc4ae29374585987a1e6cf0a8e66ba96bb690bd474a887caef2dce0b3b0f9a7

However, when I make this `leaveDotGit = true` and `fetchSubmodules = true`:

    ~/src/nixpkgs (pleasant-ruby) λ nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit --fetch-submodules 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    34caf39724cfa72a136869d97aa74eacca9f9fb16a1e335e7fa6158aad38f1e4
    
    ~/src/nixpkgs (pleasant-ruby) λ nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit --fetch-submodules 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    34caf39724cfa72a136869d97aa74eacca9f9fb16a1e335e7fa6158aad38f1e4
    
    ~/src/nixpkgs (pleasant-ruby) λ nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit --fetch-submodules 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    34caf39724cfa72a136869d97aa74eacca9f9fb16a1e335e7fa6158aad38f1e4

**Comment by cstrahan** [comment]
Interestingly, `fetchgit` itself *is* deterministic, despite `nix-prefetch-git` being *non*-deterministic (at least from the command line).

This is pretty curious.

**Comment by copumpkin** [comment]
Perhaps environment variables come into play? Does the shell script take care to clear the environment like a nix build does?

**Comment by cstrahan** [comment]
So, I tried diffing two of the outputs:

    ~/src/bundix ((detached from fa9302f)) λ diff -rq /nix/store/fh3hmfij0pgwl9fxba96wn8dxz69q73l-git-export /nix/store/wybf5dkiiilhqzz4vxqr3cag60m6dwh4-git-export
    Only in /nix/store/fh3hmfij0pgwl9fxba96wn8dxz69q73l-git-export/.git: tags.17333
    Only in /nix/store/wybf5dkiiilhqzz4vxqr3cag60m6dwh4-git-export/.git: tags.17419

That looks an awful lot like part of my git hooks that automatically generate tags. Sure enough:

    ~/src/bundix ((detached from fa9302f)) λ HOME=/homeless-shelter nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    20167f627ad30a90324a6d35b19f189672889fd9462f6df0988a6762b3d411b8
    
    ~/src/bundix ((detached from fa9302f)) λ HOME=/homeless-shelter nix-prefetch-git https://github.com/bundler/bundler.git a2343c9eabf5403d8ffcbca4dea33d18a60fc157 --hash sha256 --leave-dotGit 2>/dev/null
    git revision is a2343c9eabf5403d8ffcbca4dea33d18a60fc157
    20167f627ad30a90324a6d35b19f189672889fd9462f6df0988a6762b3d411b8

I'm of the opinion that we should override `$HOME` in the `nix-prefetch-scripts` package, to prevent these kinds of problems.

Thoughts?

**Comment by copumpkin** [comment]
Seems like those `nix-prefetch-*` scripts in general should almost completely clear out your environment

**Comment by cstrahan** [comment]
Yeah, I don't know how much to get rid of, considering that someone may want to get the hash of their private repos or something.
