### ISSUE TITLE
[nixpkgs-manual] wrapProgram needs clarification about required build input

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#57792]
## Issue description

The section [3.6. Shell functions](https://nixos.org/nixpkgs/manual/#ssec-stdenv-functions) of the nixpkgs manual says

> The standard environment provides a number of useful functions.

This reads like all functions were included into stdenv by default and could just be used.
But when trying to use the `wrapProgram` function in a postInstall script, I get the following error: `/nix/store/k6abmi6ksv6w12mg0kw14i18qpxzsdap-stdenv-linux/setup: line 99: wrapProgram: command not found`

When looking at other derivations in nixpkgs, it turns out that they have added `makeWrapper` to their nativeBuildInputs.

I want to get confirmation that I didn't miss anything here and would then volunteer to fix the docs.
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.27, NixOS, 18.09.2327.37694c8cc0e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2327.37694c8cc0e, nixos-unstable-19.09pre172038.5d3fd3674a6"`
 - channels(user): `"home-manager-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Yup, that looks like a docs bug.

**Comment by schmittlauch** [comment]
I'm willing to take this on, but am struggling to find a good section of the nixpkgs docs to move the documentation on `makeWrapper` to:

Currently, section 3.6 is a subsection of *stdenv* and contains notes about makeWrapper and substitute functions. While the substitute functions are indeed part of stdenv, the wrapper functions are not and require the nativeBuildInput of `wrapProgram`.

So from my perspective there are 3 ways of fixing that:

1. Keep documentation of *substitute* in section 3.6 and move documentation of *wrapProgram* somewhere else – but to which section?  
  This is structurally correct, as *makeWrapper* isn't part of stdenv and doesn't belong in that section then.
1. Keep documentation for both in 3.6, just add the remark that wrapper functions require an additional build input.  
  This is structurally wrong, but maintains a semantic cohesion.
1. Make *makeWrapper* part of *stdenv* and keep documentation unchanged.
