### ISSUE TITLE
obnam benchmark does not function

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#578]
nix-env -i obnam && mkdir -p "$HOME"/test/obnam && \
    TMPDIR="$HOME"/test/obnam  obnam-benchmark                                           
replacing old `obnam-1.4'
installing `obnam-1.4'
bzr: ERROR: Not a branch: "/home/aragnon/".
ERROR: bzr failed

**Comment by rycee** [comment]
I think this issue can be closed since obnam version 1.7 the `obnam-benchmark` tool is no longer installed. From `obnam-1.8/NEWS`:
> The `obnam-benchmark` program got rewritten so that it'll do something useful, but at the same time, it is no longer useful as a general tool. It is now expected to be run from the Obnam source tree (a cloned git repository), and isn't installed anymore.

**Comment by aragnon** [comment]
The KDE method of bug fixing; just deprecate the feature! (Mostly directed at the author of obnam in this case.)
