### ISSUE TITLE
libreoffice 6.2 supports qt5/kde

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#57846]
## Issue description

Would be great if LO could be compiled with plasma integration

https://wiki.documentfoundation.org/ReleaseNotes/6.2#KDE_5_.2B_Qt5

Cc: @7c6f434c

**Comment by 7c6f434c** [comment]
I do not object, but cannot easily test it so probably I won't investigate it myself.

**Comment by peterhoeg** [comment]
Fixed with the introduction of `libreoffice-qt`.
