### ISSUE TITLE
Support npm 2.0 to build npm packages

### ISSUE THREAD

**Issue by valeriangalliat** [NixOS/nixpkgs#5787]
Hi,

Some npm packages require npm 2.0 to build, and the npm version shipped with Node in NixOS is 1.4.9, so building such a npm package will fail (in my case I'm trying to build [SassDoc](https://www.npmjs.com/package/sassdoc) in version 2.0.0-rc.16).

I slightly modified [`build-node-package.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/nodejs/build-node-package.nix) to allow injecting a custom npm (so we can pass `nodePackages.npm` to get npm 2.0 instead of the npm packaged with Node). Here's the patch:

```patch
diff --git a/pkgs/development/web/nodejs/build-node-package.nix b/pkgs/development/web/nodejs/build-node-package.nix
index 8aae538..6408dc8 100644
--- a/pkgs/development/web/nodejs/build-node-package.nix
+++ b/pkgs/development/web/nodejs/build-node-package.nix
@@ -1,4 +1,4 @@
-{ stdenv, runCommand, nodejs, neededNatives}:
+{ stdenv, runCommand, nodejs, npm ? nodejs, neededNatives}:
 
 args @ { name, src, deps ? {}, peerDependencies ? [], flags ? [], preShellHook ? "",  postShellHook ? "", resolvedDeps ? {}, bin ? null, ... }:
 
@@ -161,7 +161,7 @@ let
       fi
 
       # Install package
-      (cd $HOME && npm --registry http://www.example.com --nodedir=${sources} install $src ${npmFlags})
+      (cd $HOME && ${npm}/bin/npm --registry http://www.example.com --nodedir=${sources} install $src ${npmFlags})
 
       runHook postBuild
     '';
```

I'm then building my package with the following script and expression:

```sh
# build.sh
echo '["sassdoc"]' > packages.json
npm2nix packages.json packages.nix
nix-build sassdoc.nix
```

```nix
# sassdoc.nix
let
  pkgs = import <nixpkgs> {};

  packages = pkgs.callPackage ./packages.nix {
    self = packages // {
      buildNodePackage = import <nixpkgs/pkgs/development/web/nodejs/build-node-package.nix> {
        inherit (pkgs) stdenv nodejs runCommand;
        inherit (pkgs.nodePackages) npm;

        # I don't know how to avoid repeating this from `pkgs/top-level/all-packages.nix`
        neededNatives = with pkgs;
          [ python ] ++ lib.optional (lib.elem system lib.platforms.linux) utillinux;
      };
    };
  };
in
  packages.sassdoc
```

It works fine, but I think Nix needs a more generic way to build Node packages requiring npm 2.0, that's why I'm opening this issue.

We can't make `nodePackages.npm` the default npm for all packages because `nodePackages.npm` itself *have* to be installed with the npm provided by Node.

**Comment by lethalman** [comment]
cc @svanderburg

**Comment by valeriangalliat** [comment]
Update: the package that was requiring npm 2 did this because npm 2 uses [semver](https://github.com/npm/node-semver) 4 while npm 1 uses semver 2, [and they don't resolve dependencies the same way](http://blog.npmjs.org/post/98131109725/npm-2-0-0), especially for `0.*` versions (and this could cause dependency conflicts for certain packages assuming semver 4 behavior).

But npm2nix don't rely on npm to extract dependencies, and it currently uses semver 2 regardless of the global npm version, so injecting npm 2 in the build process don't help in any way, except muting the error message (but the dependencies are stll resolved according to semver 2 rules).

So a simple way to fix this issue would be to ignore `engineStrict` in `package.json`; the package archive have to be extracted in order to patch the `package.json`, then install package from the extraction directory.

**Comment by offlinehacker** [comment]
Ok, thanks, will fix this, now we support per package overrides, so this
shouldn't be a problem.
