### ISSUE TITLE
buildPythonPackage sets LANG unconditionally

### ISSUE THREAD

**Issue by glasserc** [NixOS/nixpkgs#57911]
## Issue description

As of #55826, all invocations of `buildPythonPackage` on NixOS set the `LANG` environment variable to `C.UTF-8`. However:

- At present, this locale does not appear to exist on NixOS (unstable).
- When developing Python modules, it's natural to use `nix-shell`, which (because `buildPythonPackage` inherits this `LANG`) changes the locale from the developer's normal one.

I can think of some workarounds but I don't really have enough information to figure out which one is the best.

- What is the point of setting `LANG` in this way? The release notes at https://github.com/NixOS/nixpkgs/blob/59c5630f605255e7c514062993c29abe4c328a4b/nixos/doc/manual/release-notes/rl-1903.xml explain that setting it's done to enable Unicode support. Is this necessary for all Python packages or just the interpreter? Why is it sufficient for this to happen at build time and not at runtime too?
- Is there an alternative to using `buildPythonPackage` when developing something in Python? It seems like the answer is no, eventually all Python code goes through `buildPythonPackage`.
- Is it OK for `nix-shell` to alter the developer's `LANG`? I have been using `nix-shell` as almost a lightweight `virtualenv` so this is surprising behavior to me, but maybe my expectations are wrong and `nix-shell` is first and foremost meant to create build environments (cf. https://github.com/NixOS/nix/pull/545).

### Steps to reproduce

`nix-shell '<nixpkgs>' -A python37.pkgs.pytest --command locale` produces:

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

## Technical details

> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 19.03beta171721.e0e29a5996e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(ethan): `""`
 - channels(root): `"nixos-19.03beta171721.e0e29a5996e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
>At present, this locale does not appear to exist on NixOS (unstable).

Quite sure this is due to https://github.com/NixOS/nixpkgs/issues/57974, and we should fix that.

> When developing Python modules, it's natural to use nix-shell, which (because buildPythonPackage inherits this LANG) changes the locale from the developer's normal one.

`nix-shell` is supposed to create an environment that resembles the `nix-build` environment as much as possible. Therefore, that can indeed change your locale settings.

> Is this necessary for all Python packages or just the interpreter? 

It is needed for a significant amount of Python 3 packages. At first I was hesitant to including this in `buildPythonPackage`, but especially now with Python 3.7 I think it should.

> Why is it sufficient for this to happen at build time and not at runtime too?

By default `stdenv.mkDerivation` exports `C` locale, but as mentioned many packages on Python 3 require a UTF-8 locale. Users typically have a UTF-8 language during run-time already.

> Is it OK for nix-shell to alter the developer's LANG

Yes, it should resemble the build environment. If you only want to use a tool/environment (e.g. using `nix-shell -p`) then use `nix run` instead.

**Comment by glasserc** [comment]
> Yes, it should resemble the build environment. If you only want to use a tool/environment (e.g. using `nix-shell -p`) then use `nix run` instead.

Specifically, I'm using [pypi2nix](https://github.com/garbas/pypi2nix) to generate derivations for the dependencies for a Python project I'm developing, and then using `nix-shell requirements.nix` to produce an environment that has all of them. This isn't exactly "the build environment" because I'm actually looking for a development environment, but it's not exactly `nix-shell -p` either.

Using `nix run` is an effective workaround but I'm not crazy about it because of https://github.com/NixOS/nix/issues/2020.

I think you've answered the question in this issue and even provided a workaround, so I'm going to close the issue. Just to restate what I understood the answer to be:

- Python packages rely on having a UTF-8 locale in order to function correctly. We set this at build time to make sure that these packages function correctly at build time. Users can set whatever non-UTF-8 locale they like at runtime and break their packages, but that's not our responsibility -- our responsibility is to ensure the package builds correctly.
- We set C.UTF-8 because it's a locale that we know will be UTF-8. In principle it would be possible to use whatever UTF-8 locale we happen to be in, but the code to implement this would be much more work.

> By default `stdenv.mkDerivation` exports C locale

I couldn't find where this happens in the code, and I'm having difficulty proving it empirically. For example, if I do the same command using a derivation defined using `stdenv.mkDerivation`, I get different results:

```
> nix-shell '<nixpkgs>' -A hello --command locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by FRidh** [comment]
> I couldn't find where this happens in the code, and I'm having difficulty proving it empirically.

Seems like I was wrong there. By default we export `LANG=`. Add `--pure` to your command.

> At present, this locale does not appear to exist on NixOS (unstable). 

This has now been fixed.
