### ISSUE TITLE
Difference between `pkgs/applications/misc` and `pkgs/tools/misc`?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#5791]
What is the difference between `pkgs/applications/misc` and `pkgs/tools/misc`? Could these subdirectories be merged, maybe?

I'd happily provide patches for this, if there is no semantical difference between the two directories!

Edit: Maybe in `pkgs/misc/tools/` ?

**Comment by pSub** [comment]
Citing http://nixos.org/nixpkgs/manual/#idm140351253089584:

  "A tool is a relatively small program, especially one intented to be used non-interactively."
  "A (typically large) program with a distinct user interface, primarily used interactively."

I hope this explains the difference. If you find packages that are in the wrong place according to the nixpkgs manual, feel free to open a PR.

**Comment by matthiasbeyer** [comment]
Ah, I'm sorry, I havn't seen this before. Just checked my package contributions, but I think they are in the right places, so no problem here.

Just curious: `A (typically large program` - ncurses applications are classified as "typically large" here, right? :smile: Because they are used interactively?

**Comment by iElectric** [comment]
Yup.
