### ISSUE TITLE
rename std._debug  / std.normalize

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#57944]
## Issue description
@lblasc @Mic92  luaPackages.std._debug was introduced in 2f0ff59d892b786b075d686c5cbe885a472db141 but I can't find the associated PR. 

The names with a dot pose problem when passed as parameter. For instance, I am trying to do:
`  luaposix = callPackage ({ std.normalize, bit32 }: buildLuaPackage rec { ...`
but nix would complain with `syntax error, unexpected ',', expecting '.' or '=',  `

My lua generator replaces `.` into `_` in the name. Would it be ok to rename   std.normalize to std_normalize for instance ? nothing seems to depend on it yet.

**Comment by lblasc** [comment]
I'm fine with the rename, luaposix has dependency on std.normalize, so please update.

**Comment by teto** [comment]
@lblasc could you check https://github.com/NixOS/nixpkgs/pull/57945 works for you ?

**Comment by lblasc** [comment]
Fine with me, you can add me to maintainers when you add support for it. Those packages I only needed as luaposix dependencies, I don't use them directly so naming doesn't matter to me.

**Comment by teto** [comment]
Pr was merged. Closing
