### ISSUE TITLE
Albert out of date

### ISSUE THREAD

**Issue by ManuelSchneid3r** [NixOS/nixpkgs#57960]
## Issue description
[albert](https://github.com/NixOS/nixpkgs/blob/8751edf7b841eaae611fb147f176b3dfcb4977f9/pkgs/applications/misc/albert/default.nix#L6) is out of date. Current version is 0.16.1

**Comment by Infinisil** [comment]
Was updated in https://github.com/NixOS/nixpkgs/pull/55341, so the fix is both in the unstable channels and will be in the 19.03 release :)
