### ISSUE TITLE
Installing NixOS in a Macbook Pro Retina using unetbootin results in a boot error message. 

### ISSUE THREAD

**Issue by viclib** [NixOS/nixpkgs#5798]
Can't paste for obvious reasons, so here is a picture:

http://imgur.com/dp543ZY,CdJ83UO

I used unetbootin to format my pen drive on a Windows XP VM. I used disk utils to format a 128gb partition on my Macbook Pro Retina, using OSX Yosemite. I've downloaded the graphical disk, from the official site: nixos-graphical-14.12.315.d9de59a-x86_64-linux.iso. I've tried the "continue anyway" option, but it resulted in a "panic" message and got stuck there.

**Comment by puffnfresh** [comment]
I don't think you can use UEFI with unetbootin.

Use the instructions in the manual for preparing media for UEFI booting:

http://nixos.org/nixos/manual/sec-installation.html#sec-booting-from-usb

**Comment by cillianderoiste** [comment]
You can use unetbootin alright, but you need to follow the instructions in section 2.2 of the manual.

**Comment by cillianderoiste** [comment]
Having re-read the instructions, I believe they don't make much sense. 

AFAIK, the second part refers to the a file that you can edit after using unetbootin to prepare the usb stick:
"Edit loader/entries/nixos-livecd.conf on the drive and change the root= field in the options line to point to your drive (see the documentation on root= in the kernel documentation for more details)."

I don't have access to a system with UEFI, but I'm sure I've used unetbooting and edited this file previously when helping others to install NixOS on a system using UEFI. It would be great if someone could clarify the situation.

**Comment by iElectric** [comment]
cc @shlevy

**Comment by shlevy** [comment]
@iElectric @cillianderoiste I've never gotten UEFI booting working with unetbootin, if you can please update the docs. I've documented what has worked for me.

**Comment by shlevy** [comment]
@cillianderoiste what "doesn't make much sense" about the instructions?

**Comment by cillianderoiste** [comment]
Sorry, I must be mistaken.

**Comment by iElectric** [comment]
All in all, we should really look into unifying this as UEFI is still a big pain on NixOS. I wonder what other distros use for booloader on UEFI

**Comment by cstrahan** [comment]
NixOS's use of gummiboot has been working well for me (I triple boot OSX, NixOS and WIndows).

I didn't use unetbootin: I just copied the files from the iso directly onto a FAT32 formatted USB stick.

**Comment by paholg** [comment]
@shlevy @puffnfresh Using unetbootin and then labeling my usb drive "NIXOS_ISO" (as outlined in the guide) worked fine for me with UEFI.

**Comment by shlevy** [comment]
@paholg Cool! Would you mind updating the docs explaining what you did?

**Comment by iElectric** [comment]
@paholg any progress? I can document it if you tell me that you did different

**Comment by cillianderoiste** [comment]
I'll close this since it doesn't seem to be a problem anymore.
