### ISSUE TITLE
tomb doesn't work with bash shell

### ISSUE THREAD

**Issue by bricewge** [NixOS/nixpkgs#57986]
## Issue description
`tomb` doesn't work under `bash` shell but it does with `zsh` andI don't understand the cause of it. I was working on #57946 when I encountered this.

### Steps to reproduce
1. Start a bash sell with `nix-shell --pure -p tomb zsh` or `env -i bash --noprofile --norc`
2. Run `tomb -h`, it returns:
```
tomb [E] Missing required dependency pinentry.  Please install it.

```
3. Start a `zsh` shell in the same `nix-shell`
4. `tomb -h` now correctly return it's usage

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.28, NixOS, 18.09.2360.8751edf7b84 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2360.8751edf7b84, nixos-hardware, nixpkgs-unstable-19.03pre169106.1a88aa9e0cd"`
 - channels(bricewge): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by Mic92** [comment]
Does adding the pinentry package help?

**Comment by bricewge** [comment]
Unfortunately no. You can try it yourself with `nix-shell --pure -p tomb pinentry --command "tomb -h"`

**Comment by bricewge** [comment]
I don't think is still relevant any more, I have updated the PR with an install check which work.

So it seems that the issue only manifest itself when using `nix-shell`.
