### ISSUE TITLE
texlive: TEXMFLOCAL should not point to TEXMFDIST

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#58026]
TEXMF defines the order in which files are read in texmf.cnf

```
TEXMF = {
  $TEXMFAUXTREES$TEXMFCONFIG,
  $TEXMFVAR,
  $TEXMFHOME,
  !!$TEXMFLOCAL,
  !!$TEXMFSYSCONFIG,
  !!$TEXMFSYSVAR,
  !!$TEXMFDIST}
```
The idea is that TEXMFSYSVAR and TEXMFCONFIG files take precedence over files distributed with TEXMFDIST, so there is a way for the user to override configuration files. Our texmf.cnf lists:

```
% The main tree of distributed packages and programs:
TEXMFDIST = $TEXMFROOT/texmf
% TEXMFSYSVAR, where *-sys store cached runtime data.
TEXMFSYSVAR = $TEXMFROOT/texmf-var
% TEXMFSYSCONFIG, where *-sys store configuration data.
TEXMFSYSCONFIG = $TEXMFROOT/texmf-config
```
This seems all fine, except that our derivation also makes TEXMFLOCAL point to TEXMFDIST as well, and this destroys override-ability.
```
% Local additions to the distribution trees.
TEXMFLOCAL = /nix/store/hd53vrfqj7j3cb178x5zk5019kf7dc5g-texlive-combined-2018/share/texmf
```
My suggestion is to use a separate and empty $out/share/texmf-local for TEXMFLOCAL.

**Comment by veprbl** [comment]
Could you please provide an example of the override that doesn't work?

**Comment by clefru** [comment]
I dropped my customization here:
https://gist.github.com/clefru/9ed1186bf0b76d27e0ad20cbd9966b87

It boils down to adding a custom package (minionpro availble for my [NUR overlay](http://github.com/clefru/nixover-clefru)) and running:
```
perl `type -P updmap.pl` --sys --enable Map=MinionPro.map --enable Map=MyriadPro.map
```
in postBuild.

**Comment by veprbl** [comment]
I investigated your override. I see that you sneak the original updmap.cnf, then add your font to it and regenerate the mappings which go to share/texmf-var. At the same time our texlive setup just reuses prebuilt maps provided by `texlive.updmap-map` (for pdftex), individual font packages and others and those are installed into share/texmf which happens to be also pointed by TEXMFLOCAL. I also now discover that the line
https://github.com/NixOS/nixpkgs/blob/19030473ba07f23483fc84db11b92131d0c03f39/pkgs/tools/typesetting/tex/texlive/combine.nix#L218
does nothing for us.

Your change makes sense to me. Makes me wonder if we could do better. For example, *not* deleting `share/texmf/web2c/updmap.cnf` should not hurt anything. I could not find any way to automatically scan for new entries for updmap.cnf. The Gentoo documentation mentions [1] concatenating it from /etc/texmf/updmap.d.

[1] https://wiki.gentoo.org/wiki/Project:TeX/Tex_Live_Migration_Guide#updmap.cfg

**Comment by clefru** [comment]
@veprbl First of all thank you for taking such a careful look at my code snippet. I really appreciate it!

First, yes, I sneak out and later sneak updmap.cfg back in. I do think that there are no adverse side-effects from not deleting updmap.cfg in texlive.combine. I will submit a PR to remove it.

This will remove my postBuild override to just:
```
updmap --sys --syncwithtrees --force #  I am not sure if this is necessary still.
updmap --sys --enable MinionPro.map --enable MyriadPro.map
updmap --sys
```
That looks much cleaner :)

As there is no real "hooks" functionality in our texlive package derivation, it seems to be a good idea to optimistically merge (by concatenation) separate updmap.cfg snippets. I will file a separate issue to discuss this.

**Comment by clefru** [comment]
@veprbl Thank you!
