### ISSUE TITLE
haskellPackages.hfsevents fails to build on darwin

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#58028]
## Issue description

```
error: Package ‘hfsevents-0.1.6’ in /nix/store/i9q775988fzd4iz6p62b6i9p8ygcqrmf-source/pkgs/development/haskell-modules/hackage-packages.nix:111221 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.
```

The issue is due to an inverted logic error marking `hfsevents` not supported on darwin when it should be marked as only supported darwin instead.

https://github.com/NixOS/nixpkgs/blob/4708d3f84bce8c6bec0d989df1b33c59beb97821/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L2477

https://github.com/NixOS/nixpkgs/commit/7a67c9da33ebdf158a8291bbed09120f4dd7e29f#diff-d9687f7c9d1aceca689b0868d33211eeR2531

cc @peti

### Steps to reproduce

`nix-build` an expression depending on `hfsevents`

## Technical details

Nix 2.0.4 on x86_64-darwin on Travis

**Comment by tg-x** [comment]
Tried this again with travis with nixpkgs pinned to this commit, but it still fails for some reason, any ideas?

```
trying https://github.com/NixOS/nixpkgs/archive/ce5504bc7492269538a7ba4d3c78a39d43684878.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   155    0   155    0     0    679      0 --:--:-- --:--:-- --:--:--   679
100 15.6M    0 15.6M    0     0  6091k      0 --:--:--  0:00:02 --:--:-- 7589k
unpacking source archive /private/tmp/nix-build-source.drv-0/ce5504bc7492269538a7ba4d3c78a39d43684878.tar.gz
error: Package ‘hfsevents-0.1.6’ in /nix/store/ggjhzgrr4p6wxr6srqvh8fd6lsq37g8c-source/pkgs/development/haskell-modules/hackage-packages.nix:111221 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.
```

**Comment by peti** [comment]
That commit configures `hackage2nix` which generates that file, so it takes another run of that tool before the configured changes take effect. b23f9e540fd84a0238752050af94372b025abc6a has the update.

**Comment by srhb** [comment]
@peti Is a full regen expected on 19.03 as well before release? Right now, the `darwin-tested` job does not eval because of this, but I guess we don't need to manually poke it if it's going to be regenerated. :)

**Comment by peti** [comment]
@srhb, I don't think we'll re-generate `hackage-packages.nix` on the release branch any time soon, so manually submitted changes there are probably the way to go. I might do a complete update at some point in the future, but I can't say for sure. Updating a branch that's supposed to be stable is a lot of work.
