### ISSUE TITLE
VirtualBox display fails when `VMSVGA` Graphics Controller

### ISSUE THREAD

**Issue by marler8997** [NixOS/nixpkgs#58070]
## Issue description

Installing NixOS on virtualbox with the minimal install CD.  If I chose the default boot option, graphics would stop working around "NixOS Stage 1.  Changing it to the (nomodeset), graphics started working.

After installing NixOS and rebooting, graphics stopped working again at some point during systemd boot.

I messed around with the graphics settings, changing the Graphics Controller from `VMSVGA` to `VBoxSVGA` fixed both issues.  I was able to boot with the CD with the default GRUB boot option and I was able to boot using NixOS that was installed to the drive.

### Steps to reproduce

* Setup a VirtualBox Machine.
  * I used 4096 MB or RAM.
  * I set the CPU count to 4.
  * You can double check that the problematic `VMSVGA` graphics controller is being used
* Download the NixOS minimal install  CD, add it to the VirtualBox machine
* Start the machine
* Let it boot with the default boot option
* Graphics will stop working around NixOS Stage 1

You can workaround the issue in this case by selecting the `(nomodeset)` option.  Otherwise, you can change the Graphics Controller to `VBoxSVGA` and that should also fix it.

### Notes

My guess is that the default linux kernel doesn't support the VMSVGA graphics controller.  The fix is probably just an extra config option in NixOS's default kernel config.

**Comment by marler8997** [comment]
I booted with the `VMSGA` graphics controller and the `VBoxSVGA` controller and captured the kernel log by adding `console=ttyS0` to the kernel command line.  I'm attaching both log files here.

Even though the `VMSVGA` continued to boot...the graphics were completely hosed in the "NixOS State 1" part of boot, whch is near the beginning of the log file.

The most noteworthy lines that could indicating what is happening are these 2 lines in the `VMSVGA` logfile that don't appear in the `VBoxSVGA` logfile:
```
[    0.423014] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send log
[    0.423497] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send log
```

As it's related to DRM seems like it's likely reporting an error related to why graphics completely stop working.
[nixos-serial-VMSVGA.txt](https://github.com/NixOS/nixpkgs/files/2999060/nixos-serial-VMSVGA.txt)
[nixos-serial-VBoxSvga.txt](https://github.com/NixOS/nixpkgs/files/2999061/nixos-serial-VBoxSvga.txt)

**Comment by macalinao** [comment]
I'm getting the same issue with a Macbook pro.
