### ISSUE TITLE
vnstat wants to access files in `/var/lib`

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#5807]
Just played around with `vnstat`. It wants to open `/var/lib/vnstat`, which, obviousely, did not exist. It exited afterwards with an error.

Maybe this should be fixed by patching it?

**Comment by pSub** [comment]
This is no bug in nixpkgs. The directory `/var/lib/vnstat` is created by `vnstatd` (the vnstat daemon).
