### ISSUE TITLE
ssh server secure configuration

### ISSUE THREAD

**Issue by user318** [NixOS/nixpkgs#5809]
Currently, by default only DSA and ECDSA host keys are generated for ssh server. But this schemes are considered less secure than RSA or ED25519.
This is good overview article:
https://stribika.github.io/2015/01/04/secure-secure-shell.html
Points there are:
* DSA have weak 1024-bit key
* ECDSA is using suspicious curve

This is interesting too:
http://security.stackexchange.com/questions/5096/rsa-vs-dsa-for-ssh-authentication-keys
It referes that DSA and ECDSA keys in some situation can lead to leakage of private key.

**Comment by wkennington** [comment]
My personal defaults are an rsa4096 key with ed25519 preferred. I wouldn't
mind this kind of change. It would be nice if we also tightened down cipher
suites / kex / macs. These would need to be made into options though.

**Comment by user318** [comment]
In addition, services.openssh.hostKeys option in configuration.nix requires bits parameter, but it is not necessary or even ignored for some types.
Also I will like if there will be the ability to provide custom "ssh/moduli" file.

**Comment by wkennington** [comment]
The moduli is irrelevant if you use an ed25519-sha256(or any ecdhe) kex,
but it would be nice to specify

**Comment by user318** [comment]
> My personal defaults are an rsa4096 key with ed25519 preferred.

I have changed this too. It is easy. But I do not like that default configuration is worst case.

> The moduli is irrelevant if you use an ed25519-sha256(or any ecdhe) kex

I know.

> but it would be nice to specify

That is my point. :)

**Comment by arno01** [comment]
I've just created a PR for stronger moduli https://github.com/NixOS/nixpkgs/pull/5870

**Comment by user318** [comment]
> I've just created a PR for stronger DH prime moduli #5870

I think ability to provide custom moduli file is more general approach.

**Comment by peti** [comment]
I've read this thread and most of the material surrounding this subject, but I still have a hard time figuring out a concrete list of actionable items that describe changes we can make to improve security.

Can someone please suggest concrete tasks that we could do to close this issue?

**Comment by user318** [comment]
Here is part of my configuration.nix:
<pre>
  programs.ssh.extraConfig = ''
    Host *
      HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-ed25519,ssh-rsa
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
  '';
  services.openssh.hostKeys = [
    { type = "rsa"; bits = 4096; path = "/etc/ssh/ssh_host_rsa_key"; }
    { type = "ed25519"; bits = 256; path = "/etc/ssh/ssh_host_ed25519_key"; }
  ];
  services.openssh.extraConfig = ''
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
  '';
</pre>
Also, as I said it will be good to do something with moduli file. For example allow to pass custom file.
And "bits" configuration on keys should be optional, I think.

**Comment by peti** [comment]
@user318, your configuration file is very reasonable, but we cannot ship that kind of default, because users may need to connect to a NixOS server using ancient software, and then they'll need the full spectrum of algorithms enabled. It would be great to extend the documentation of the relevant options in `configuration.nix`, though, to suggest secure defaults. Would you mind creating a PR that does that based on your personal configuration choices?

As for the `moduli` file, I'll make the necessary changes as part of https://github.com/NixOS/nixpkgs/pull/5870.

**Comment by user318** [comment]
Yes, most of configuration may be too strong. But main part there is server ssh keys. Which now already customized by default to DSA and ECDSA, which is not good. I offer to change it to RSA4096 and ED25519 by default.

> As for the moduli file, I'll make the necessary changes as part of #5870.
Cutting small primes is good. But there still open question for trusting default moduli provided by openssh/distribution/etc. So I think there should be possibility to customize this file too.

**Comment by peti** [comment]
Yes, switching the generated default keys to RSA4096 and ED25519 sounds reasonable to me. I suppose we're not creating any glaring incompatibilities with older clients by choosing those algorithms.

**Comment by peti** [comment]
Closed in favor of https://github.com/NixOS/nixpkgs/pull/7939.
