### ISSUE TITLE
git build is failing on darwin

### ISSUE THREAD

**Issue by ggPeti** [NixOS/nixpkgs#58129]
## Issue description
Git build is failing on darwin
https://hydra.nixos.org/build/90923911
https://hydra.nixos.org/job/nixpkgs/trunk/git.x86_64-darwin

**Comment by ggPeti** [comment]
could not reproduce on darwin (no sandbox, 1ad3f34, `nix build -f . git`)

**Comment by ggPeti** [comment]
seems like it's 6 tests failing in this file: https://github.com/git/git/blob/master/t/t5523-push-upstream.sh

**Comment by srhb** [comment]
Suspected transient failure, rebuilding: https://hydra.nixos.org/build/90942037

**Comment by ggPeti** [comment]
That build succeeded, closing this.
