### ISSUE TITLE
modprobe vboxsf breaks boot

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#58127]
## Issue description
I am occasionally running NixOS unstable in VirtualBox but after I updated (2018-07-06 → 2019-03-22), it no longer boots:

```
Mar 22 14:39:17 nixos stage-1-init: loading module vboxsf...
Mar 22 14:39:17 nixos kernel: vboxsf: loading out-of-tree module taints kernel.
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTMemTmpFree (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuestIDC (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTSemFastMutexRequest (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTSemFastMutexRelease (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTLogRelGetDefaultInstanceEx (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTStrCopy (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTErrConvertToErrno (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTSemFastMutexCreate (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTSemFastMutexDestroy (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTAssertShouldPanic (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTLogLoggerEx (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTMemTmpAllocTag (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTAssertMsg1Weak (err -2)
Mar 22 14:39:17 nixos kernel: vboxsf: Unknown symbol VBoxGuest_RTAssertMsg2Weak (err -2)
Mar 22 14:39:17 nixos stage-1-init: modprobe: ERROR: could not insert 'vboxsf': Unknown symbol in module, or unknown parameter (see dmesg)
```

## Possible cause

Recent Alpine ML post suggests it might be a collision with linux-virt:

https://lists.alpinelinux.org/alpine-devel/6417.html

## Configuration

```nix
{ config, pkgs, ...}: {
  boot.loader.grub.device = "/dev/sda";

  services.openssh = {
    enable = true;
    permitRootLogin = "no";
    passwordAuthentication = false;
  };
  virtualisation.virtualbox.guest.enable = true;

  services.xserver.enable = true;
  services.xserver.layout = "cz";
  services.xserver.xkbVariant = "qwerty";
  services.xserver.xkbOptions = "compose:caps";

  # Enable the Desktop Environment.
  services.xserver.displayManager.gdm = {
    enable = true;
    autoLogin = {
      enable = true;
      user = "moi";
    };
  };
  services.xserver.desktopManager.gnome3 = {
    enable = true;
  };

  environment.gnome3.excludePackages = with pkgs.gnome3; builtins.filter (x: x != nautilus && x != gedit) optionalPackages;

  environment.systemPackages = with pkgs; [
    firefox
    gnome3.gnome-tweaks
    gnome3.gedit
    sublime3
    gitAndTools.diff-so-fancy
    gitAndTools.gitFull
    gitg
    gnomeExtensions.dash-to-dock
    sequeler
  ];

  fileSystems = {
    "/" = {
      label = "nixos";
    };

    "/home/moi/Documents" = {
      fsType = "vboxsf";
      device = "Documents";
      options = ["rw" "uid=1000"];
      noCheck = true;
    };
  };

  # system.fsPackages = [
  #  config.boot.kernelPackages.virtualboxGuestAdditions
  # ];

  users = {
    extraUsers.moi = {
      isNormalUser = true;
      uid = 1000;
      extraGroups = [ "vboxsf" "wheel" "networkmanager" ];
      useDefaultShell = true;
      openssh.authorizedKeys.keys = [
      ];
      password = "";
    };
  };

  programs = {
    fish = {
      enable = true;
    };
  };


  nixpkgs = {
    config = {
      allowUnfree = true;
    };
  };

  system.stateVersion = "18.03";

  users.defaultUserShell = pkgs.fish;
  users.mutableUsers = false;
}
```

**Comment by jtojnar** [comment]
They seem to have fixed it using https://git.alpinelinux.org/aports/commit/main/linux-vanilla/config-virt.x86_64?id=bccb4334186cbdc9edecc7ab896e85671da35487 but I see no such thing in nixpkgs

**Comment by jtojnar** [comment]
I am trying the following now:

```
  boot.kernelPatches = [
    {
      name = "vbox-virt-conflict-config";
      patch = null;
      extraConfig = ''
        VBOXGUEST n
      '';
    }
  ];
```

**Comment by Moredread** [comment]
Doesn't that disable the support in the guest? I think disabling virtualisation.virtualbox.guest.enable already should prevent loading the module.

**Comment by jtojnar** [comment]
As I understand it, there are two sources providing `vboxguest.ko`. This will disable the one from kernel and allow us to use the external one.

**Comment by Moredread** [comment]
Oh that makes sense. Didn't know it was in mainline.

**Comment by Yarny0** [comment]
This also happens with release-19.03 , at least since the update of kernel 4.14 to 4.19.

Here's my `configuration.nix` :

```nix
{ pkgs, ... }: {
  imports = [ ./hardware-configuration.nix ];
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda";
  environment.systemPackages = with pkgs;
    [ vim socat git ];
  system.stateVersion = "19.03";
}
```

...and my `hardware-configuration.nix` :

```nix
{ config, lib, pkgs, ... }: {
  imports = [ ];
  boot.initrd.availableKernelModules = [ "ata_piix" "xhci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f1686da0-a9c8-4be3-a095-653ee6f5321c";
    fsType = "btrfs";
  };
  swapDevices = [ ];
  nix.maxJobs = lib.mkDefault 4;
  virtualisation.virtualbox.guest.enable = true;
}
```

Interestingly, it does *not* happen when I use ext4 for the root-fs. Maybe loading the btrfs kernel module causes something that breaks vboxsf.

**Comment by angryzor** [comment]
Having this issue as well, though my boot process is not halted. I am using ext4.

```
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2ea1045c-aa12-4c1f-926e-602fad6611df";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C17E-F91E";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 1;
  virtualisation.virtualbox.guest.enable = true;
}
```

**Comment by lodi** [comment]
I'm having the exact same issue, VirtualBox on Windows host (Win7 and Win10 as host OS), version 5.2.18, 5.2.28, and 6.0.6.  Ext4 filesystem on the guest.  

jtojnar's kernel patch [above](https://github.com/NixOS/nixpkgs/issues/58127#issuecomment-475668077) works to resolve the issue, but forces a full kernel recompile.

**Comment by ambrop72** [comment]
I spent quite some time investigating these errors while packaging VirtualBox 6, and finally figured it out and that it's not specific to VirtualBox 6. The precise problem seems to be that `vboxguest` module from the kernel (which apparently has priority over the `vboxguest` modules from additions) does not provide the symbols needed by the `vboxsf` module from the additions (the kernel has no `vboxsf` yet). I don't see any way to fix it other than disable the mainline modules (also `vboxvideo`) - until the kernel also has `vboxsf` and we no longer need modules from additions. Note that blacklisting `vboxguest` would not solve the problem.

**Comment by ambrop72** [comment]
However I don't understand why people are having boot failures. For me this just resulted in the error shown in the top post, and inability to use `vboxsf`, the system still booted.

**Comment by lodi** [comment]
ambrop72, it turns out I was missing the "nofail" option.

```
  fileSystems."/shared" = {
    fsType = "vboxsf";
    device = "shared";
    options = [ "rw" "nofail" ];
  };
```

Now it'll at least boot, but then fail to mount my /shared folder.

**Comment by bb2020** [comment]
Have the same issue on 18.09 with 19.03.172530 guest. Prints error message during stage1 and then boots normally. Shared folders does not work.

Running `modprobe vboxsf` results with this:
`modprobe: ERROR: could not insert 'vboxsf': Unknown symbol in module, or unknown parameter (see dmesg)`

**Comment by Yarny0** [comment]
For me, https://github.com/NixOS/nixpkgs/pull/60938 and https://github.com/NixOS/nixpkgs/commit/bfdb124045bb68015a4f16a871c740b2e64c1685 solved this issue. If no one else is experiencing this, we can probably close it. Thanks for fixing!

**Comment by flokli** [comment]
closing.
