### ISSUE TITLE
Slack new release available

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#58124]
## Issue description
Slack has new release (3.3.8) https://slack.com/release-notes/linux.
Master has 3.3.7.

## Technical details
Backport requested for 18.09 and 19.03 too.

**Comment by srhb** [comment]
Is there any usability issue with the current 18.09 version? It seems to work, so I am a little disinclined to backport such a large version bump. master and 19.03 done, however.

**Comment by memberbetty** [comment]
I can live with the limited issues I have in 18.09 until 19.03 is released. The glib crashes *are* a major pain in comparison. I am currently running the 18.09 version again, because it's the only version which doesn't crash (you have seen the reported issues).

**Comment by JohnAZoidberg** [comment]
Seems like it's been backported: https://github.com/NixOS/nixpkgs/commit/ff9c3f0f26de1cc750867f3eca62a64faca34bf0

Is this issue still relevant?

**Comment by memberbetty** [comment]
If there is any user that can confirm it works on 19.03, yes. I still run 18.09.

**Comment by JohnAZoidberg** [comment]
In which situations does it crash? How can I could I test it? (I do have an account but I'm not a regular Slack user)

**Comment by memberbetty** [comment]
Uploading an image by pressing the '+'-symbol. The file selector would not come up.

**Comment by baracoder** [comment]
Is this still relevant?
I am on NixOS unstable and have the version 3.4.2, the file selector seams to work.

**Comment by nh2** [comment]
Closing, as NixOS 20.03 has Slack 4.*.
