### ISSUE TITLE
package request: yuzu

### ISSUE THREAD

**Issue by tycho01** [NixOS/nixpkgs#58176]
[yuzu](https://github.com/yuzu-emu/yuzu) is a Nintendo Switch Emulator

**Comment by delroth** [comment]
I'll give it a shot. Will likely just pin to a random git revision since it doesn't seem like Yuzu has any official releases at this point.

**Comment by delroth** [comment]
#58312

**Comment by IvarWithoutBones** [comment]
#84117

**Comment by IvarWithoutBones** [comment]
I would like to add that I've added an [NUR repo](https://github.com/IvarWithoutBones/NUR/) which contains always up-to-date versions of yuzu (both early-access and mainline). It also has a binary cache, so you don't have to wait for it to build yourself.

The package updates once a day at 8AM ECT.

**Comment by aanderse** [comment]
@IvarWithoutBones awesome! I'll look into that.

You still plan to bump `yuzu-mainline` in nixpkgs once in a while too, though... right? :smile:

**Comment by IvarWithoutBones** [comment]
> You still plan to bump `yuzu-mainline` in nixpkgs once in a while too, though... right?

Of course! I just wanted to have the absolute latest version also readily available. In fact, I'm working on some patches for it right now :)

**Comment by aanderse** [comment]
That is fantastic. Thank you for your efforts.
