### ISSUE TITLE
sdl2-config: command not found

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#58177]
Some programs are impossible to build without sdl2-config, and there seems to be no sdl2-config in Nixpkgs.

**Comment by matthewbauer** [comment]
This should be provided by SDL2.dev.

**Comment by suhr** [comment]
Indeed. It is hard to discover though.

**Comment by jtojnar** [comment]
We have [nix-index](https://github.com/bennofs/nix-index). You can also use it by sending `,locate sdl2-config` on our IRC channels.

**Comment by suhr** [comment]
Oh, that tool that OOMs on my machine when indexing. Didn't know it has a bot on IRC.

**Comment by jtojnar** [comment]
Please open an issue with that tool if it does not work for you.

**Comment by vvs-** [comment]
I'm at loss here. `nix-index` shows that there is `nixos.SDL2.dev` attribute and even a name with a hash. I can see that directory in my /nix/store. But `nix-env -iA nixos.SDL2.dev` ignores `dev` suffix and installs `nixos.SDL2` instead. How can I install `SDL2.dev`?

**Comment by jtojnar** [comment]
Don't install libraries through nix-env or systemPackages, use nix-shell instead. See https://nixos.wiki/wiki/FAQ/Libraries for details.
