### ISSUE TITLE
package request: gamehub

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#58189]
## Issue description

repo: https://github.com/tkashkin/gamehub

originally mentioned at https://github.com/NixOS/nixpkgs/pull/42075#issuecomment-460632423.

**Comment by florianjacob** [comment]
still important to me

**Comment by RPGHank** [comment]
Still important to me

**Comment by RPGHank** [comment]
There is a PR open at #99957

**Comment by TheOddler** [comment]
> There is a PR open at #99957

The PR has sadly been closed :(
