### ISSUE TITLE
Installation over serial via syslinux is unecessarily fiddly

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#58198]
Installing nixos over serial via syslinux is fiddly, because:
* serial terminals aren't enabled by default on all stages
* on the boot stages that do have serial terminals enabled, they use inconsistent bitrates

| Stage | Bitrate |
| ---- | ---- |
| BIOS | 115200 (typically) |
| syslinux | ~38400~ 115200 (fixed in https://github.com/NixOS/nixpkgs/pull/58196)  |
| Linux boot | serial terminal not enabled |
| Linux login | 115200 (see `stty`) |

In practice this means the user must either patch their image, or perform an installation while switching bitrates and adding serial terminals to kernel boot parameters.

We can make this smoother, by enabling serial on all stages, and ensuring they use the same bitrate.

- [x] Change syslinux's bitrate to 115200: **DONE** https://github.com/NixOS/nixpkgs/pull/58196
- [ ] Enable kernel serial console by default, by adding `console=tty0 console=ttyS0,115200` to all boot entries.
    * PR pending: https://github.com/NixOS/nixpkgs/pull/91086

**Comment by tomfitzhenry** [comment]
My reading of the GRUB2 config suggests in GRUB2 the serial terminal isn't enabled by default: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L311-L317

What's the rationale for this, and does this apply for syslinux?

**Comment by tomfitzhenry** [comment]
The remaining step is step 2.

> Step 2: Enable kernel serial console by default, by adding console=tty0 console=ttyS0,115200 to all boot entries.

This is just a matter of copying the existing serial boot entry for GRUB ( https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L325-L330 ) and adapting it to be a boot entry for syslinux: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L120-L146

I'll do this when I have time to test it.

**Comment by sneak** [comment]
This would be very useful to me, as I'm trying to install nixos via virt-install without vnc (headless, serial console).

**Comment by sneak** [comment]
Actually, I think just spawning a getty on the serial console after boot would be fine for my use case.

**Comment by tomfitzhenry** [comment]
sneak@, if you're able to test github.com/NixOS/nixpkgs/pull/91086 that'd be much appreciated. It should make installation easier for you.

**Comment by sneak** [comment]
Do you have an ISO I can download for that?  Happy to test out.

**Comment by sneak** [comment]
FYI I started a thread about this here: https://discourse.nixos.org/t/feature-request-spawn-getty-on-serial-console-in-installer-iso/9195/2

**Comment by tomfitzhenry** [comment]
> Do you have an ISO I can download for that? Happy to test out.

https://github.com/NixOS/nixpkgs/pull/91086 has instructions on building an ISO. See "I tested this change by building the image".

**Comment by tomfitzhenry** [comment]
> Actually, I think just spawning a getty on the serial console after boot would be fine for my use case.

FWIW, I think the installer already does this. You just have to sit through a blank Linux boot process. If the boot succeeds, getty should open on the serial console. If the boot fails, getty won't get chance and it's hard to diagnose the boot failure since the Linux boot doesn't write to the serial console (that's what https://github.com/NixOS/nixpkgs/pull/91086 aims to fix).

**Comment by samueldr** [comment]
Stage-1 doesn't support multiple consoles yet.

#42255 was a first draft towards supporting this.

"Just" adding `console=*` here won't exactly help as only the last one will have the initial boot messages.

I mean to eventually get back to this problem and properly implement tests for [bootlogd](https://github.com/NixOS/mobile-nixos/blob/8ee49d935d5d63588fc73fa8b8cea6aa8e439f37/overlay/bootlogd/default.nix), in use in [Mobile NixOS](https://github.com/NixOS/mobile-nixos/blob/8ee49d935d5d63588fc73fa8b8cea6aa8e439f37/modules/initrd-logs.nix#L48-L66).

**Comment by sneak** [comment]
> FWIW, I think the installer already does this. 

It does not.  VNCing in and running `systemctl start serial-getty@ttyS0` makes it show up, though.  

The only output from the system via serial is:

```
Loading /boot/bzImage... ok
Loading /boot/initrd...ok
```

...and that's it.
