### ISSUE TITLE
/etc/ethertypes missing

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#58200]
## Issue description
My libvirt setup invokes ebtables in the context of the clean-traffic filter and fails because /etc/ethertypes is expected by the ebtables binary.

### Steps to reproduce
Run
```
$ ebtables -A foobar -p ipv4 -j RETURN
Problem with the specified Ethernet protocol 'ipv4', perhaps /etc/ethertypes is missing.
$ strace -etrace=file !! 2>&1 | tail -5
strace -etrace=file ebtables -A foobar -p ipv4 -j RETURN 2>&1 | tail -5
openat(AT_FDCWD, "/nix/store/ndqs999n0zxyc3aivxg0kl73hpmzkvmn-iptables-1.8.2/lib/xtables/libxt_standard.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/etc/ethertypes", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ethertypes", O_RDONLY) = -1 ENOENT (No such file or directory)
Problem with the specified Ethernet protocol 'ipv4', perhaps /etc/ethertypes is missing.
+++ exited with 255 +++
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.2, NixOS, 19.03.git.ef5adfa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `""`
 - nixpkgs: `/nix/nixpkgs`

**Comment by clefru** [comment]
Tracing this a bit further shows that despite the source code of ebtables containing /etc/ethertypes as a string, the ebtables binary doesn't contain "/etc/ethertypes" when being strings-ed. The offending string is hardcoded inside libxtables.so.12 which comes from the iptables derivation.

/etc/ethertypes feels like /etc/protocols and /etc/services. Do we want to promote it to that level or do we want to fix the hardcoded path in iptables?

**Comment by ambrop72** [comment]
For anyone suffering from this, the workaround is: `environment.etc.ethertypes.source = "${pkgs.iptables}/etc/ethertypes";`

**Comment by prih** [comment]
Debian 10, KVM, Libvirt...

`apt install ebtables`

**Comment by c0bw3b** [comment]
@clefru are you using the `virtualisation.libvirtd` service module?

**Comment by clefru** [comment]
@c0bw3b Yes
