### ISSUE TITLE
LaTeX Error: File `lmodern.sty' not found.

### ISSUE THREAD

**Issue by shakthimaan** [NixOS/nixpkgs#5822]
I am trying to use pandoc with PDF output on NixOS 14.12, but, I am getting the following error:

    $ pandoc foo.md -o foo.pdf
    ! LaTeX Error: File `lmodern.sty' not found.

    Type X to quit or <RETURN> to proceed,
    or enter new name. (Default extension: sty)

    Enter file name: 
    ! Emergency stop.
    <read *> 
         
    l.3 \usepackage

I have the following in /etc/nixos/configuration.nix:

    environment.systemPackages = with pkgs; [
        wget emacs24 git python gnuplot notmuch
        haskellPackages.pandoc texLive tetex lmodern
    ];

Also

    $ nix-env -qa \* | grep modern
    lmodern-2.004.4
    moderncv-1.5.1
    moderntimeline-0.7

**Comment by iElectric** [comment]
https://nixos.org/wiki/TexLive_HOWTO#..._using_.2Fetc.2Fnixos.2Fconfiguration.nix

**Comment by earldouglas** [comment]
> https://nixos.org/wiki/TexLive_HOWTO#..._using_.2Fetc.2Fnixos.2Fconfiguration.nix

This worked for me when I added `lmodern` to `texLiveAggregationFun`:

*/etc/nixos/configuration.nix:*

```
  # ...
  environment.systemPackages = with pkgs; [
    # ...
    (texLiveAggregationFun { paths = [ texLive texLiveExtra texLiveBeamer lmodern ]; })
  ];
```

**Comment by MarkusWotringer** [comment]
Added this valuable information to the wiki:

https://nixos.org/wiki/TexLive_HOWTO
