### ISSUE TITLE
Chromium missing desktop actions

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#58226]
We are creating chromium desktop file ourselves:

https://github.com/NixOS/nixpkgs/blob/5699e8edc7243fce3ed2332e76c04c7469f78d4b/pkgs/applications/networking/browsers/chromium/default.nix#L45-L68

But we are not adding desktop actions (_Open new anonymous window_, etc.).

Perhaps we should use the upstream file like Arch does:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/chromium&id=b466f9b266526b4524861bb61df6c7ff63b994b1#n204

**Comment by JohnAZoidberg** [comment]
I wish I didn't have to recompile chromium to test that. Would it be possible without, somehow? :thinking:

**Comment by JohnAZoidberg** [comment]
Should `Exec=` maybe contain the path to the binary in the nix-store?
Upstream has it like: `Exec=/usr/bin/chromium %U`
