### ISSUE TITLE
Packaging gxi in NixOS

### ISSUE THREAD

**Issue by Cogitri** [NixOS/nixpkgs#58227]
Hello there,

there has been an attempt to package gxi in #57878, but that has been closed due to problems with its postinstall script. I basically just want to ask if I can change something upstream to better accommodate for NixOS in [my postinstall script](https://github.com/Cogitri/gxi/blob/master/meson_post_install.sh). It does seem like [Fractal's postinstall script](https://gitlab.gnome.org/GNOME/fractal/blob/master/scripts/meson_post_install.py) works fine for you thought, so I'm kind of puzzled what's going wrong (I don't think any of the postinstall script should even be run in NixOS, or should it? At least other distros handle it in their own ways, hence it is guarded under '-z "$DESTDIR"', but it seems like NixOS doesn't set that?

**Comment by lheckemann** [comment]
I don't understand what's wrong with just setting DESTDIR for the postinstall script to work with no problems.

**Comment by Cogitri** [comment]
Sure, setting DESTDIR to an empty string makes it work, but it doesn't seem like that's being done for Fractal?

**Comment by lheckemann** [comment]
It was set to `/` in the PR you mentioned, which worked. I think that PR was closed in favour of @dtzWill's approach to plugin management, which is currently available in his NUR repository.

**Comment by jansol** [comment]
More like closed due to uncertainty about what the upstream favoured solution would be as well as the required overall readiness of packages to be included in nixpkgs.

**Comment by Cogitri** [comment]
Alright. I've just allowed update-desktop-database to error out in the postinstall script, it not only fails on NixOS but also if one does unprivileged installs without setting DESTDIR (e.g. into $HOME) because it always tries to update /usr/{,local}/share/applications, instead warning if it doesn't work. I'll close this then, maybe gxi will be ready for packaging in NixOS in the future.

FWIW, Xi upstream is currently working on making Xi better usable as a library and to add a way to build plugins into editors as static lib. Plugins & Xi-core can't really be shared well across editors yet due to not having a stable API (and some plugins have to be built of the same git rev as Xi)
