### ISSUE TITLE
nix-info: multi-user? "no" when run as root

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#58254]
## Issue description

Does that makes sense?

### Steps to reproduce

```
[root@ethmoid:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.108, NixOS, 18.09.2390.40e716b92a7 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2390.40e716b92a7, nixos-hardware, nixos-unstable-19.09pre173166.373488e6f4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```
[davidak@ethmoid:~]$ nix-shell -p nix-info --run "nix-info -m"
/nix/store/a6rf8a474z5y01w4ld2v54d24kyqcxag-stdenv-linux/setup: line 784: /run/user/1000/env-vars: Permission denied
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.108, NixOS, 18.09.2390.40e716b92a7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2390.40e716b92a7, nixos-hardware, nixos-unstable-19.09pre173166.373488e6f4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Technical details

See above ;)

**Comment by 7c6f434c** [comment]
Yes, for some values of «yes» — requesting a Nix build as root does not go through the daemon.

Maybe it should be a separate answer. Multi-user? `yes`/`no`/`root`

**Comment by davidak** [comment]
I interpret the question as "Is Nix installed in multi-user mode?" and that should be "yes" also as root.

Isn't that the information that is usefull in a bugreport?

**Comment by 7c6f434c** [comment]
Hard to say — if you treat that question as «is the build invoked via daemon», the current `nix-info` answer is more likely to be relevant…

**Comment by davidak** [comment]
@grahamc what do you think?

**Comment by 7c6f434c** [comment]
Hm. I think the `master` version indeed checks for `nixbld` and works the same for user and for root.
