### ISSUE TITLE
security.sudo.extraRules doesn't work correctly

### ISSUE THREAD

**Issue by cmacrae** [NixOS/nixpkgs#58276]
## Issue description
When using `security.sudo.extraRules` to generate a `sudo` expression, its result; although correct, is ineffective (I think due to its position in the `/etc/sudoers` file).

The *exact* same resulting `sudo` expression can be implemented using `security.sudo.extraConfig` and works as expected.  

The only difference between the two is:  
- When `extraRules` is used, its resulting `sudo` expression is placed *before* the following line in `/etc/sudoers`
- When `extraConfig` is used, its resulting `sudo` expression is placed *after* the following line in `/etc/sudoers`
```
%wheel	ALL=(ALL:ALL)	SETENV: ALL
```

### Steps to reproduce
As a user in the `wheel` group:  

#### Using `extraRules`
1. Generate a `NOPASSWD` `sudo` expression to run `whoami` as `root` for any user in the `wheel` group, *using extraRules*:  
```nix
  security.sudo.enable = true;
  security.sudo.extraRules = [{
    runAs = "root";
    groups = [ "wheel" ];
    commands = [{
      command = "/run/current-system/sw/bin/whoami";
      options = [ "NOPASSWD" ];
    }];
  }];
```
2. Evaluate and switch to the new build with `sudo nixos-rebuild switch`
3. Ensure your `sudo` session is absent with `sudo -k`
4. Try and run `sudo whomi` - according to the `sudo` expression in place, you should not have to enter a password. However, you should find that you *are* prompted for a password

#### Using `extraConfig`
1. Now take the exact `whoami` `sudo` expression generated from the last step (copy from `/etc/sudoers`)
2. Replace your `security.sudo.extraRules` expression with a `security.sudo.extraConfig` expression with the rule:
```nix
  security.sudo.extraConfig = ''
    %wheel	ALL=(root)	NOPASSWD: /run/current-system/sw/bin/whoami
  '';
```
3. Evaluate and switch to the new build with `sudo nixos-rebuild switch`
4. Ensure your `sudo` session is absent with `sudo -k`
5. Try and run `sudo whoami`, you should see `root` returned to stdout, without being prompted for a password, *as expected*.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.3, NixOS, 19.09pre173166.373488e6f4c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre173166.373488e6f4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cmacrae** [comment]
Taking a stab at fixing this myself.  
Looking at the expressions for how `security.sudo.extraRules` is evaluated in `nixos/modules/security/sudo.nix`, you can see here that it's used to generate the `%wheel	ALL=(ALL:ALL)	SETENV: ALL` line.  

I believe, if there's a means of ensuring the `%wheel	ALL=(ALL:ALL)	SETENV: ALL` rule results first, before any user defined `extraRules`, this should solve it. But, I'm not sure how/if we can do that :thinking: 

```nix
    security.sudo.extraRules = [
      { groups = [ "wheel" ];
        commands = [ { command = "ALL"; options = (if cfg.wheelNeedsPassword then [ "SETENV" ] else [ "NOPASSWD" "SETENV" ]); } ];
      }
    ];

    security.sudo.configFile =
      ''
        # Don't edit this file. Set the NixOS options ‘security.sudo.configFile’
        # or ‘security.sudo.extraRules’ instead.

        # Keep SSH_AUTH_SOCK so that pam_ssh_agent_auth.so can do its magic.
        Defaults env_keep+=SSH_AUTH_SOCK

        # "root" is allowed to do anything.
        root        ALL=(ALL:ALL) SETENV: ALL

        # extraRules
        ${concatStringsSep "\n" (
          lists.flatten (
            map (
              rule: if (length rule.commands != 0) then [
                (map (user: "${toUserString user}	${rule.host}=(${rule.runAs})	${toCommandsString rule.commands}") rule.users)
                (map (group: "${toGroupString group}	${rule.host}=(${rule.runAs})	${toCommandsString rule.commands}") rule.groups)
              ] else []
            ) cfg.extraRules
          )
        )}

        ${cfg.extraConfig}
      '';
```

**Comment by cmacrae** [comment]
Testing locally with these changes resolves the issue (though, obviously this is just to prove my theory):
```diff
modified   nixos/modules/security/sudo.nix
@@ -171,11 +171,11 @@ in
 
   config = mkIf cfg.enable {
 
-    security.sudo.extraRules = [
-      { groups = [ "wheel" ];
-        commands = [ { command = "ALL"; options = (if cfg.wheelNeedsPassword then [ "SETENV" ] else [ "NOPASSWD" "SETENV" ]); } ];
-      }
-    ];
+    # security.sudo.extraRules = [
+    #   { groups = [ "wheel" ];
+    #     commands = [ { command = "ALL"; options = (if cfg.wheelNeedsPassword then [ "SETENV" ] else [ "NOPASSWD" "SETENV" ]); } ];
+    #   }
+    # ];
 
     security.sudo.configFile =
       ''
@@ -189,6 +189,7 @@ in
         root        ALL=(ALL:ALL) SETENV: ALL
 
         # extraRules
+        %wheel	ALL=(ALL:ALL)	SETENV: ALL
         ${concatStringsSep "\n" (
           lists.flatten (
             map (
```

This shows that the placement of the generated `%wheel	ALL=(ALL:ALL)	SETENV: ALL` is what's causing the problem

**Comment by cmacrae** [comment]
As above, I've opened https://github.com/NixOS/nixpkgs/pull/58396

**Comment by cmacrae** [comment]
:mega: I've updated #58396 after a long hiatus. It works :smile: Would be nice to get this merged, if someone has the time to review :pray:

**Comment by dmadisetti** [comment]
Unable to replicate this in 2023

**Comment by mhuesch** [comment]
I am also unable to replicate this - just rewrote the workaround to use `extraRules` and everything works as expected. yay :tada: 

I seem to be tracking nixos-22.11 on [this commit](https://github.com/NixOS/nixpkgs/commit/9d692a724e74d2a49f7c985132972f991d144254) from my flake.
