### ISSUE TITLE
Slack depends on wget

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#58274]
## Issue description
Slack misses dependency `wget` (it also seems to reference an absolute path, which might have to be patched out depending on how Slack works internally).

### Steps to reproduce
First make it crash:

> /run/current-system/sw/bin/slack
> (electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
> Creating Slack Application
> Cannot upload crash dump: cannot exec /usr/bin/wget
> Failed to get crash dump id.
> Report Id:
> Segmentation fault

Observe there is a dependency on `wget`. Also check that default.nix in the slack Nix expression does not contain `wget`.

## Technical details

Applies to all versions of nixpkgs.

**Comment by Infinisil** [comment]
How do you make it crash? I can start it just fine

**Comment by samueldr** [comment]
AFAIUI, #58273 is the issue about the crash itself.

This issue looks like it is about how their crash handler is hardcoded to use `/usr/bin/wget` which isn't part of the dependencies.

**Comment by SebTM** [comment]
Hey, thanks for the report as this is stale for longer time and I confirmed its working on stable and unstable and the message is not present anymore.
