### ISSUE TITLE
Slack crashes on upload

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#58273]
## Issue description
Slack crashes when trying to open the window that one can use to upload a file. 

> /run/current-system/sw/bin/slack
> (electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
> Creating Slack Application
> Cannot upload crash dump: cannot exec /usr/bin/wget
> Failed to get crash dump id.
> Report Id: 
> Segmentation fault
> 

### Steps to reproduce
Press the '+'-button and select 'Your computer' in a chat.

## Technical details
This happens with the `master` version of Slack that was updated a few days ago.

> slack[14978]: segfault at 0 ip 00007f553a42a9fd sp 00007ffd5424ea18 error 6 in libc-2.27.so[7f553a2fa000+13d000]

cc: @dtzWill (author), @srhb (person who merged)

**Comment by srhb** [comment]
I cannot seem to reproduce this, but possibly that's because of some other impurity that's present. I'll keep trying.

**Comment by memberbetty** [comment]
My host operating system is still `18.09`, so I referred to this master version as: 
`environment.systemPackages = [checkout_of_master.slack]`

Perhaps that helps?

**Comment by dtzWill** [comment]
Works here? Just uploaded file in chat with myself xD.

Not sure why that would be happening... maybe it needs some gtk bits in
profile/env that I happen to have but you don't? :/

**Comment by srhb** [comment]
GTK impurity sounds like a likely suspect indeed.

**Comment by samueldr** [comment]
I lost the ability to reproduce #54278, but from a cursory look at `strace -fo slack.strace result/bin/slack` from master, I'm pretty sure it would be it.

**Comment by wil3** [comment]
I am having the same problem. I was finally able to isolate the issue. It occurs for me if the directory contains a gif. 

To reproduce,
* Download gif to directory, e.g. [fast parrot](https://emojis.slackmojis.com/emojis/images/1471119456/981/fast_parrot.gif?1471119456)
* Click paper clip -> Add file from your computer
* Navigate to directories without gif --> ok
* Navigate to directory with gif --> slack crashes

I have slack for ubuntu 18.04 e0514fa-s@1586890343

**Comment by jakewc** [comment]
Same problem here.

**Comment by rjmill** [comment]
Uninstalling and reinstalling slack fixed this problem for me (`nix-env --uninstall slack; nix-env -iA nixpkgs.slack`).

It looks like slack was looking for some things in the wrong place:
```
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /nix/store/mm9ck1cv7zygpylzzfgfc2laphi8kxpl-librsvg-2.48.8/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/mm9ck1cv7zygpylzzfgfc2laphi8kxpl-librsvg-2.48.8/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /nix/store/mm9ck1cv7zygpylzzfgfc2laphi8kxpl-librsvg-2.48.8/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/mm9ck1cv7zygpylzzfgfc2laphi8kxpl-librsvg-2.48.8/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
```

**Comment by ahmad-elkomey** [comment]
I suffered from the same issue. It happened to me twice and each time I tackled it differently.

Note: I'm using GNU/Linux Ubuntu 18.04, slack installed by snap.

First time, it was because of navigating to a directory with a gif file, as mentioned by the folks here. If this is the case, you can solve this by editing `~/.config/Slack/Preferences`. You will find there the path containing the gif file. Change the path to anywhere not containing the git file. Save the file, restart slack. It should work just fine now.

Second time, it wasn't because of a gif file. It just happened that I opened slack one day and the upload file window will cause slack to crash. I stopped slack, removed the cache directory: `~/snap/slack/common/.cache`, and launched slack again. Everything is back to normal.

**Comment by medienlampe** [comment]
> I stopped slack, removed the cache directory: `~/snap/slack/common/.cache`, and launched slack again. Everything is back to normal.

I encountered this issue today, too.
Also with Slack installed as Snap (v4.19.2) on an Ubuntu 20.04 LTS.

@ahmad-elkomey: Deleting the cache directory did the trick for me. Thanks for sharing!

**Comment by juuuuuu** [comment]
> @ahmad-elkomey: Deleting the cache directory did the trick for me. Thanks for sharing!

It did the trick for me too! :+1:

**Comment by 7hibault** [comment]
I got the same issue and deleting the cache did the trick for me as well !

Snap 4.19.2 64-bit
Ubuntu 20.04.3 LTS

**Comment by MariaKokshaikina** [comment]
I faced this issue all of a sudden today too. Thanks, @ahmad-elkomey. Your solution with deleting the cache directory worked for me too

**Comment by luizsgpetri2** [comment]
Deleting the cache files did the trick as described on https://github.com/NixOS/nixpkgs/issues/58273#issuecomment-904615219

**Comment by IsmiKin** [comment]
Deleting the cache as @ahmad-elkomey didn't work for me, but doing it through the app it worked, thank you for the tip! :smile: 

`Help -> Troubleshooting -> Clear Cache and Restart`

Ubuntu 18.04.5 LTS

**Comment by sobi3ch** [comment]
Same problem here
```
Snap 4.19.2 64-bit
Ubuntu 20.04.3 LTS
```
..and same solution works like a charm
> _I stopped slack, removed the cache directory: `~/snap/slack/common/.cache`, and launched slack again. Everything is back to normal._

Thanks @ahmad-elkomey

**Comment by stkrelax** [comment]
> I suffered from the same issue. It happened to me twice and each time I tackled it differently.
> 
> Note: I'm using GNU/Linux Ubuntu 18.04, slack installed by snap.
> 
> First time, it was because of navigating to a directory with a gif file, as mentioned by the folks here. If this is the case, you can solve this by editing `~/.config/Slack/Preferences`. You will find there the path containing the gif file. Change the path to anywhere not containing the git file. Save the file, restart slack. It should work just fine now.
> 
> Second time, it wasn't because of a gif file. It just happened that I opened slack one day and the upload file window will cause slack to crash. I stopped slack, removed the cache directory: `~/snap/slack/common/.cache`, and launched slack again. Everything is back to normal.

@ahmad-elkomey 
TRIPPLE Thanks for the cache clean idea !! works like charm

**Comment by dr-ganesan** [comment]
Had the same problem.  Deleting the cache directory didn't work.
This solved it for me.
Attach file (chat with yourself ) --> View all your files --> Upload a file --> change directory (where there are no gifs) and upload something.  
Next time 'Attach File' works normal

**Comment by serhii-zasulskyi** [comment]
Thanks @ahmad-elkomey , cache cleaning solved the issue

**Comment by bledi1985** [comment]
for me too

**Comment by zdhamasha** [comment]
same issue here

**Comment by joshuafishman** [comment]
Cache clearing doesn't work for me.

**Comment by Aubreymcfato** [comment]
Cache clearing doesn't work for me, neither uninstall/reinstall through snap does. :(
Do I have to manually remove the `~/snap/slack/common/.cache` folder?

**Comment by SebTM** [comment]
Hey, thanks for the report as this is stale for longer time and I confirmed its working on stable and unstable.

**Comment by Systho** [comment]
I still had the issue today.
clearing the cache from the menu did not work, deleting the cache manually with slack closed worked.
I'm on 4.36.140

**Comment by SebTM** [comment]
Can't reproduce on latest unstable with 138, where did you got 140? Is it beta? If I try to download latest release from slack I get 138-0.1 still

**Comment by Systho** [comment]
I might be on beta indeed. To be honest I'm not sure since I installed a while back and just keep the auto updates
