### ISSUE TITLE
Port GHCJS to Haskell NG package set

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#5828]
```
nix-shell -I /home/ollie -E 'with import <nixpkgs> { }; runCommand "a" { buildInputs = haskell-ng.packages.ghcjs.ghcWithPackages (hs: with hs; []); } ""'
error: attribute ‘version’ missing, at /home/ollie/nixpkgs/pkgs/development/haskell-modules/with-packages-wrapper.nix:4:39
(use ‘--show-trace’ to show detailed location information)
```

Does `haskell-ng` support GHCJS yet, or is that still to come?

**Comment by peti** [comment]
There is no ghcjs support in NG yet. I created a package set, but the compiler itself doesn't build. The ghcjs expression was handwritten and needs to be ported to function without the wrapper. I can probably fix the ghcjs build; I don't think that would be hard. But I don't know much beyond that.

Cc: @cstrahan, who did most of the work in the existing ghcjs code.

**Comment by ocharles** [comment]
Ah, ok. Thanks for the update

**Comment by cstrahan** [comment]
@ryantrinkle and I were talking about this a day or two ago; he's working on adding Haskell-NG support.

**Comment by conklech** [comment]
What's the status of this issue? I've been eyeing it as a potential learning-the-codebase project for a few days, but I'm hesitant to dive in if someone else (@ryantrinkle?) has a patch almost ready.

**Comment by ryantrinkle** [comment]
I've got hacked-up (but working, i think) haskell-ng port of ghcjs available at https://github.com/ryantrinkle/ghcjs-setup

I'll work on moving things upstream as soon as I get some time.  This version should also work on Mac OS.

**Comment by ocharles** [comment]
I can confirm @ryantrinkle's stuff works a treat! Look forward to seeing it come to master :)

**Comment by cstrahan** [comment]
I've extracted @ryantrinkle's work here: https://github.com/NixOS/nixpkgs/pull/6786
