### ISSUE TITLE
terraform and terragrunt fail to build on darwin

### ISSUE THREAD

**Issue by jcpetruzza** [NixOS/nixpkgs#58297]
## Issue description

`terraform` fails on darwin since the the `libvirt` plugin is not supported there. One can workaround this by restricting the set of plugins with `terraform.withPlugins (...)`. However, `terragrunt` uses `terraform.full` and will fail for the same reason. Couldn't workaround this one easily.

### Steps to reproduce

On Darwin: `nix-env -iA nixpkgs.terragrunt`

## Technical details

Seen at work, can paste the output of  `nix-shell -p nix-info --run "nix-info -m"` later if needed.

**Comment by Veske** [comment]
I would concur - annoying issue

**Comment by forficate** [comment]
I think terragrunt should not explicitly call `terraform.full`.

`terraform` is a argument to the derivation so if the user want's terragrunt to use `terraform.full` they should pass it in as an argument.

Here's a custom derivation I use that works on darwin, not the `postInstall`:
```
# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchFromGitHub, fetchhg, fetchbzr, fetchsvn, makeWrapper, terraform }:

buildGoPackage rec {
  name = "terragrunt-${version}";
  version = "0.19.19";

  goPackagePath = "github.com/gruntwork-io/terragrunt";

  src = fetchFromGitHub {
    owner = "gruntwork-io";
    repo  = "terragrunt";
    rev   = "v${version}";
    sha256 = "0j7287g9lw06xvbxv9xi0g8zib0fbkihy67g7n1yygh9c3dbdxxi";
  };

  goDeps = ./deps.nix;

  buildInputs = [ makeWrapper ];

  preBuild = ''
    buildFlagsArray+=("-ldflags" "-X main.VERSION=v${version}")
  '';

  postInstall = ''
    wrapProgram $bin/bin/terragrunt \
      --set TERRAGRUNT_TFPATH ${terraform}/bin/terraform
  '';

  meta = with stdenv.lib; {
    description = "A thin wrapper for Terraform that supports locking for Terraform state and enforces best practices.";
    homepage = https://github.com/gruntwork-io/terragrunt/;
    license = licenses.mit;
  };

}
```

**Comment by zimbatm** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/106572 . You'll have to install terraform side-by-side with terragrunt now.
