### ISSUE TITLE
dovecot service doesn't start on reboot

### ISSUE THREAD

**Issue by arno01** [NixOS/nixpkgs#5830]
dovecot service doesn't start on reboot (valid for `NixOS release-14.12`)

```
Jan 18 20:21:06 mail dovecot2-start[1416]: Error: bind(#ipv4-address#, 993) failed: Cannot assign requested address
Jan 18 20:21:06 mail dovecot[1416]: master: Error: bind(#ipv4-address#, 993) failed: Cannot assign requested address
Jan 18 20:21:06 mail dovecot2-start[1416]: Error: service(imap-login): listen(#ipv4-address#, 993) failed: Cannot assign requested address
Jan 18 20:21:06 mail dovecot[1416]: master: Error: service(imap-login): listen(#ipv4-address#, 993) failed: Cannot assign requested address
```

Someone had the same issue which was resolved in Red Hat https://bugzilla.redhat.com/show_bug.cgi?id=871623#c7

I've checked how, seems the PreStart script checks until NetworkManager is started with 30sec timeout and then it starts dovecot
```
~/tmp $ wget http://mirror.vutbr.cz/fedora/development/rawhide/x86_64/os/Packages/d/dovecot-2.2.15-2.fc22.x86_64.rpm
~/tmp $ rpm2cpio dovecot-2.2.15-2.fc22.x86_64.rpm |cpio -idmv
~/tmp $ find . |grep service
./usr/lib/systemd/system/dovecot.service

~/tmp $ cat ./usr/libexec/dovecot/prestartscript
#!/bin/sh
/bin/systemctl -q is-enabled NetworkManager.service >/dev/null 2>&1 && /usr/bin/nm-online -q --timeout 30 ||:
```

I would suggest to add similar check with small timeout which would ensure that interfaces are UP.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/mail/dovecot.nix

**Comment by lethalman** [comment]
Timeouts are a ugly hack. With systemd you should be able to wait for a specific interface instead using /sys.

**Comment by arno01** [comment]
For sure timeouts are an ugly hack, that's why I opened an issue :-) No more pull-requests for me, hehe

**Comment by arno01** [comment]
Following patch worked for me:

```
[root@mail:~/nixpkgs]# git diff
diff --git a/nixos/modules/services/mail/dovecot.nix b/nixos/modules/services/mail/dovecot.nix
index e4daf64..b7d1e5d 100644
--- a/nixos/modules/services/mail/dovecot.nix
+++ b/nixos/modules/services/mail/dovecot.nix
@@ -148,10 +148,11 @@ in
         gid = config.ids.gids.dovecot2;
       };
 
-    jobs.dovecot2 =
+    systemd.services.dovecot2 =
       { description = "Dovecot IMAP/POP3 server";
 
-        startOn = "started networking";
+        after = [ "network.target" ];
+        wantedBy = [ "multi-user.target" ];
 
         preStart =
           ''
@@ -159,7 +160,12 @@ in
             ${pkgs.coreutils}/bin/chown -R ${cfg.user}:${cfg.group} /var/run/dovecot2
           '';
 
-        exec = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
+        serviceConfig = {
+          ExecStart = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
+          Restart = "always";
+          RestartSec = "5s";
+        };
+
       };
 
     environment.systemPackages = [ pkgs.dovecot ];
```

Note, that the above patch applied onto https://github.com/arno01/nixpkgs/commit/49450c633e5b646fdd775ff8190193a1a2f3777c


So would it be good enough for the pull request?

**Comment by lethalman** [comment]
Weird that it has a dependency on network. This part is inconsistent among most of our services, we should write down a policy.

Rather than `always` I'd use `on-failure`. I'm still uncertain about the `RestartSec`, you can always override such stuff. Again we don't have any policy about this. Since it's overridable easily by the user I have not strong feeling. cc @viric @edolstra

**Comment by 7c6f434c** [comment]
>-        startOn = "started networking";
>+        after = [ "network.target" ];
>+        wantedBy = [ "multi-user.target" ];

>-        exec = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
>+        serviceConfig = {
>+          ExecStart = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
>+          Restart = "always";
>+          RestartSec = "5s";
>+        };
>+

Do I understand correctly that the first part on its own is not enough?
So it is introducing a timeout but tries to ensure the timeout is not 
abused?

**Comment by arno01** [comment]
@lethalman, @7c6f434c absolutely `on-failure` and with the start limit interval/timeout, I had both options in mind, but was in hurry to draw this quick fix.

So here is updated patch for the dovecot.nix

```
[root@mail:~/nixpkgs]# git diff
diff --git a/nixos/modules/services/mail/dovecot.nix b/nixos/modules/services/mail/dovecot.nix
index e4daf64..dbbe97b 100644
--- a/nixos/modules/services/mail/dovecot.nix
+++ b/nixos/modules/services/mail/dovecot.nix
@@ -148,10 +148,11 @@ in
         gid = config.ids.gids.dovecot2;
       };

-    jobs.dovecot2 =
+    systemd.services.dovecot2 =
       { description = "Dovecot IMAP/POP3 server";

-        startOn = "started networking";
+        after = [ "network.target" ];
+        wantedBy = [ "multi-user.target" ];

         preStart =
           ''
@@ -159,7 +160,13 @@ in
             ${pkgs.coreutils}/bin/chown -R ${cfg.user}:${cfg.group} /var/run/dovecot2
           '';

-        exec = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
+        serviceConfig = {
+          ExecStart = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
+          Restart = "on-failure";
+          RestartSec = "10s";
+          StartLimitInterval = "1min";
+        };
+
       };

     environment.systemPackages = [ pkgs.dovecot ];
```

The timeout values can be discussed. I was thinking between 1 or 5 mins.

@lethalman  one question, as you mentioned `>Since it's overridable easily by the user`,  did you mean that there is another way I can specify `serviceConfig.` values to any service I want via `/etc/nixos/configuration.nix` ?

**Comment by arno01** [comment]
@lethalman and regarding the `network.target`, why do you think it's bad? dovecot needs the network, isn't it?  nginx has the same dependency.

**Comment by lethalman** [comment]
Every service can usually run on loopback.

**Comment by arno01** [comment]
@lethalman right, it's also up to the SW developer how to handle/wait for the network interfaces to bind as per `What does this mean for me, a Developer?` section from http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

however, in reality not every SW Dev follows these advices, that's why we wait for the `network.target` ;-)
