### ISSUE TITLE
nginx service doesn't start on reboot

### ISSUE THREAD

**Issue by arno01** [NixOS/nixpkgs#5832]
nginx service doesn't start on reboot as it can't bind.
once solution is found, it might be also applied to the dovecot service https://github.com/NixOS/nixpkgs/issues/5830

```
[root@www:~]# systemctl status nginx.service
● nginx.service - Nginx Web Server
   Loaded: loaded (/nix/store/hsmfgxipqhc5sx2zcxs89rb8yzdnjn5c-unit-nginx.service/nginx.service)
   Active: failed (Result: exit-code) since Sun 2015-01-18 02:36:12 CET; 1min 15s ago
  Process: 1305 ExecStart=/nix/store/3d84smddcfa8k3kr73sagvqap8w8vz1p-nginx-1.6.2/bin/nginx -c /nix/store/l0qz6acr98xg0w7k5prw8w8gwvxgzn0v-nginx.conf -p /var/spool/nginx (code=exited, status=1/FAILURE)
  Process: 1292 ExecStartPre=/nix/store/pdfqw0qjr19fvbzfpxwyjhdlaiafxcy5-unit-script/bin/nginx-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 1305 (code=exited, status=1/FAILURE)

Jan 18 02:36:12 www systemd[1]: Started Nginx Web Server.
Jan 18 02:36:12 www nginx[1305]: nginx: [emerg] bind() to #ipv4-address#:80 failed (99: Cannot assign requested address)
Jan 18 02:36:12 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 18 02:36:12 www systemd[1]: Unit nginx.service entered failed state.
Jan 18 02:36:12 www systemd[1]: nginx.service failed.
```

**Comment by bjornfor** [comment]
Nginx works for me (NixOS 14.12). What is your config?

**Comment by arno01** [comment]
I've also got NixOS 14.12.

My config is probably special as I'm setting the IPv6 address and the IPv6 GW manually, as follows



#### main config

```
[root@www:~]# cat /etc/nixos/configuration.nix 
...
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      ./nginx-config.nix
      ./postfix-config.nix
    ];
...
  networking = {
    hostName = "www";
    domain = "####";
    hostId = "####";

    firewall.allowedTCPPorts = [ 25 80 443 587 ];
    firewall.allowPing = true;  # probably important for recieving emails *****

    #
    # manually setup IPv6
    # IPv6 address: ####:####:#:###::####/64
    # IPv6 gateway: ####:####:#::1
    #
    localCommands = 
    ''
    ip -6 addr add ####:####:#:###::####/64 dev eth0
    ip -6 route add ####:####:#::1 dev eth0
    ip -6 route add default via ####:####:#::1 dev eth0
    '';
  };
```


#### nginx config

```
[root@www:~]# cat /etc/nixos/nginx-config.nix
{ config, pkgs, ... }:

{
  services.nginx.enable = true;

  services.phpfpm.poolConfigs = {
...
  };

  #services.nginx.config = pkgs.lib.readFile /etc/nginx.conf;
  services.nginx.config =
''
pid /var/run/nginx.pid;

worker_processes 1;

events {
        worker_connections 512;
        multi_accept on;
        use epoll;
}

http {
        include ${pkgs.nginx}/conf/mime.types;
        default_type application/octet-stream;
...
        ##
        # by default return 444 (== The connection was reset)
        ##
        server {
            listen ##.##.###.###:80 default;
            listen [####:####:#:###::####]:80 default;
            return 444;
        }

        server {
            listen ##.##.###.###:443 ssl default;
            listen [####:####:#:###::####]:443 ssl default;
            return 444;
        }
...

}
```

**Comment by arno01** [comment]
Again, after the server reboot:

```
[root@www:~]# systemctl status nginx.service
● nginx.service - Nginx Web Server
   Loaded: loaded (/nix/store/1g3dbqzryg1l2fzqnblabb9imkk838k0-unit-nginx.service/nginx.service)
   Active: failed (Result: exit-code) since Sun 2015-01-18 22:46:45 CET; 38s ago
  Process: 1296 ExecStart=/nix/store/3d84smddcfa8k3kr73sagvqap8w8vz1p-nginx-1.6.2/bin/nginx -c /nix/store/50yx9bqzivmjkm20aspxfw22y6cc5kwa-nginx.conf -p /var/spool/nginx (code=exited, status=1/FAILURE)
  Process: 1281 ExecStartPre=/nix/store/pdfqw0qjr19fvbzfpxwyjhdlaiafxcy5-unit-script/bin/nginx-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 1296 (code=exited, status=1/FAILURE)

Jan 18 22:46:45 www systemd[1]: Started Nginx Web Server.
Jan 18 22:46:45 www nginx[1296]: nginx: [emerg] bind() to ##.##.###.###:80 failed (99: Cannot assign requested address)
Jan 18 22:46:45 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 18 22:46:45 www systemd[1]: Unit nginx.service entered failed state.
Jan 18 22:46:45 www systemd[1]: nginx.service failed.

[root@www:~]# journalctl -b |grep -v 'rejected connection' |less
...
Jan 18 22:46:45 www systemd[1]: Started Networking Setup.
Jan 18 22:46:45 www systemd[1]: Starting Extra networking commands....
Jan 18 22:46:45 www dhcpcd[1261]: eth0: soliciting an IPv6 router
Jan 18 22:46:45 www systemd[1]: Started Extra networking commands..
Jan 18 22:46:45 www systemd[1]: Starting Network.
Jan 18 22:46:45 www systemd[1]: Reached target Network.
Jan 18 22:46:45 www systemd[1]: Starting Postfix mail server...
Jan 18 22:46:45 www systemd[1]: Starting Execute /etc/rc.local...
Jan 18 22:46:45 www systemd[1]: Starting Nginx Web Server...
Jan 18 22:46:45 www systemd[1]: Started Execute /etc/rc.local.
Jan 18 22:46:45 www kernel: io scheduler deadline registered
Jan 18 22:46:45 www systemd[1]: Started Nginx Web Server.
Jan 18 22:46:45 www nginx[1296]: nginx: [emerg] bind() to ##.##.###.###:80 failed (99: Cannot assign requested address)
Jan 18 22:46:45 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 18 22:46:45 www systemd[1]: Unit nginx.service entered failed state.
Jan 18 22:46:45 www systemd[1]: nginx.service failed.
...
```

Apparantly it didn't start after server reboot, so I started it manually.

```
[root@www:~]# systemctl start nginx.service

[root@www:~]# systemctl status nginx.service
● nginx.service - Nginx Web Server
   Loaded: loaded (/nix/store/1g3dbqzryg1l2fzqnblabb9imkk838k0-unit-nginx.service/nginx.service)
   Active: active (running) since Sun 2015-01-18 22:47:29 CET; 3s ago
  Process: 1492 ExecStartPre=/nix/store/pdfqw0qjr19fvbzfpxwyjhdlaiafxcy5-unit-script/bin/nginx-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 1496 (nginx)
   CGroup: /system.slice/nginx.service
           ├─1496 nginx: master process /nix/store/3d84smddcfa8k3kr73sagvqap8w8vz1p-nginx-1.6.2/bin/nginx -c /nix/store/50yx9bqzivmjkm20aspxfw22y6cc5kwa-nginx.conf -p /var/spool/nginx
           └─1499 nginx: worker process

Jan 18 22:47:29 www systemd[1]: Starting Nginx Web Server...
Jan 18 22:47:29 www systemd[1]: Started Nginx Web Server.
```

**Comment by arno01** [comment]
And my nginx config should be OK as it was serving for almost 2 years on Debian 7 and CentOS (in early beginning).
Might be the NixOS config should be tuned (order?) or something has to be fixed (network script?).
And I prefer not to use sleep timeouts :-)

**Comment by lethalman** [comment]
You could try something like:

```
systemd.services.nginx = {
  after = [ "sys-subsystem-net-devices-<interface>.device" ];
  wants = [ "sys-subsystem-net-devices-<interface>.device" ];
}
```

And see if it solves the problem at startup.

On Sun, Jan 18, 2015 at 11:01 PM, Andrey Arapov <notifications@github.com>
wrote:

> And my nginx config should be OK as it was serving for almost 2 years on
> Debian 7 and CentOS (in early beginning).
> Might be the NixOS config should be tuned (order?) or something has to be
> fixed (network script?).
> And I prefer not to use sleep timeouts :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/5832#issuecomment-70428405>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by arno01** [comment]
@lethalman just tried, unfortunately it didn't help :-/  
however if I put "sleep 5" to preStart for the `systemd.services.nginx`, then it starts on reboot



```
Jan 18 23:51:03 www systemd[1]: Started Networking Setup.
Jan 18 23:51:03 www systemd[1]: Starting Extra networking commands....
Jan 18 23:51:03 www dhcpcd[1267]: DUID 00:01:00:01:##:##:##:##:##:##:##:##:##:##
Jan 18 23:51:03 www dhcpcd[1267]: eth0: IAID ##:##:##:##
Jan 18 23:51:03 www systemd[1]: Started Extra networking commands..
Jan 18 23:51:03 www systemd[1]: Starting Network.
Jan 18 23:51:03 www systemd[1]: Reached target Network.
Jan 18 23:51:03 www systemd[1]: Starting Postfix mail server...
Jan 18 23:51:03 www systemd[1]: Starting Execute /etc/rc.local...
Jan 18 23:51:03 www systemd[1]: Starting Nginx Web Server...
Jan 18 23:51:03 www kernel: io scheduler deadline registered
Jan 18 23:51:03 www systemd[1]: Started Execute /etc/rc.local.
Jan 18 23:51:04 www dhcpcd[1267]: eth0: soliciting an IPv6 router
Jan 18 23:51:04 www postfix/postfix-script[1383]: starting the Postfix mail system
Jan 18 23:51:04 www systemd[1]: Started Postfix mail server.
Jan 18 23:51:04 www postfix/master[1384]: daemon started -- version 2.8.12, configuration /var/postfix/conf
Jan 18 23:51:04 www kernel: NET: Registered protocol family 17
Jan 18 23:51:04 www dhcpcd[1267]: eth0: rebinding lease of ##.##.###.###
Jan 18 23:51:06 www ntpd[1113]: Listen normally on 4 eth0 [####:####:#:###::####]:123
Jan 18 23:51:06 www ntpd[1113]: Listen normally on 5 eth0 [fe80::###:####:####:####%2]:123
Jan 18 23:51:06 www ntpd[1113]: new interface(s) found: waking up resolver
Jan 18 23:51:06 www ntpd[1113]: 18 Jan 23:51:06 ntpd[1113]: Listen normally on 4 eth0 [####:####:#:###::####]:123
Jan 18 23:51:06 www ntpd[1113]: 18 Jan 23:51:06 ntpd[1113]: Listen normally on 5 eth0 [fe80::###:####:####:####%2]:123
Jan 18 23:51:06 www ntpd[1113]: 18 Jan 23:51:06 ntpd[1113]: new interface(s) found: waking up resolver
Jan 18 23:51:08 www dhcpcd[1267]: eth0: leased ##.##.###.### for 21600000 seconds
Jan 18 23:51:08 www dhcpcd[1267]: eth0: adding route to ##.##.###.0/24
Jan 18 23:51:08 www dhcpcd[1267]: eth0: adding default route via ##.##.###.1
Jan 18 23:51:08 www systemd[1]: Started Nginx Web Server.
Jan 18 23:51:08 www systemd[1]: Starting Multi-User System.
Jan 18 23:51:08 www systemd[1]: Reached target Multi-User System.
```


between `Jan 18 23:51:03 www systemd[1]: Starting Nginx Web Server...` and
`Jan 18 23:51:08 www systemd[1]: Started Nginx Web Server.` I can see these important lines:

```
Jan 18 23:51:04 www dhcpcd[1267]: eth0: soliciting an IPv6 router

Jan 18 23:51:04 www kernel: NET: Registered protocol family 17
Jan 18 23:51:04 www dhcpcd[1267]: eth0: rebinding lease of ##.##.###.###

Jan 18 23:51:08 www dhcpcd[1267]: eth0: leased ##.##.###.### for 21600000 seconds
Jan 18 23:51:08 www dhcpcd[1267]: eth0: adding route to ##.##.###.0/24
Jan 18 23:51:08 www dhcpcd[1267]: eth0: adding default route via ##.##.###.1
```

**Comment by lethalman** [comment]
Oh perhaps the interface is up but it's not bound to any ip address. Wondering how one could wait this properly with systemd.

**Comment by arno01** [comment]
Just wondering.. maybe changing `Type=forking` to `Type=simple` of the `systemd.dhcpcd.service` would make `systemd` wait until `dhcpd` finishes, and then will start the other services? :P

**Comment by lethalman** [comment]
@arno01 eh eh no, services should not hang until they become fully operative but as long as they are started. That's the definition of "active" in systemd. Waiting for an ip is a different kind of signal.

**Comment by lethalman** [comment]
I think systemd-networkd solves this somehow, but I didn't learn anything about it yet.

**Comment by arno01** [comment]
@lethalman yeah, it looks like there is something ..

```
[root@www:~]# systemctl status systemd-networkd-wait-online.service
● systemd-networkd-wait-online.service - Wait for Network to be Configured
   Loaded: loaded (/nix/store/m0icqj9ix19jpggj6iy6jj8gd8dbqc3l-systemd-217/example/systemd/system/systemd-networkd-wait-online.service)
   Active: inactive (dead)
     Docs: man:systemd-networkd-wait-online.service(8)

```
http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

**Comment by arno01** [comment]
Ok adding `Restart` and `RestartSec` resolved the problem.

```
[root@www:~/nixpkgs]# git diff
diff --git a/nixos/modules/services/web-servers/nginx/default.nix b/nixos/modules/services/web-servers/nginx/default.nix
index 7c2d3a4..3029c96 100644
--- a/nixos/modules/services/web-servers/nginx/default.nix
+++ b/nixos/modules/services/web-servers/nginx/default.nix
@@ -99,6 +99,8 @@ in
         '';
       serviceConfig = {
         ExecStart = "${nginx}/bin/nginx -c ${configFile} -p ${cfg.stateDir}";
+        Restart = "always";
+        RestartSec = "5s";
       };
     };
```


```
[root@www:~/nixpkgs]# journalctl -b |grep -v 'rejected connection' |grep -E "DHCP|Nginx"
Jan 19 01:12:02 www systemd[1]: Starting DHCP Client...
Jan 19 01:12:02 www systemd[1]: Started DHCP Client.
Jan 19 01:12:02 www systemd[1]: Starting Nginx Web Server...
Jan 19 01:12:02 www systemd[1]: Started Nginx Web Server.
Jan 19 01:12:08 www systemd[1]: Stopping Nginx Web Server...
Jan 19 01:12:08 www systemd[1]: Starting Nginx Web Server...
Jan 19 01:12:08 www systemd[1]: Started Nginx Web Server.

[root@www:~/nixpkgs]# date
Mon Jan 19 01:14:02 CET 2015
```

systemd doc http://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by arno01** [comment]
Is it good enough for the pull request?

**Comment by lethalman** [comment]
We have support for networkd thanks to @wkennington . However until we have that online service you can workaround with a `Restart = on-failure`.

**Comment by arno01** [comment]
Updated patch for the nginx.nix

```
[root@www:~/nixpkgs]# git diff
diff --git a/nixos/modules/services/web-servers/nginx/default.nix b/nixos/modules/services/web-servers/nginx/default.nix
index 7c2d3a4..a99cd20 100644
--- a/nixos/modules/services/web-servers/nginx/default.nix
+++ b/nixos/modules/services/web-servers/nginx/default.nix
@@ -99,6 +99,9 @@ in
         '';
       serviceConfig = {
         ExecStart = "${nginx}/bin/nginx -c ${configFile} -p ${cfg.stateDir}";
+        Restart = "on-failure";
+        RestartSec = "10s";
+        StartLimitInterval = "1min";
       };
     };
```

The timeout values can be discussed. I was thinking between 1 or 5 mins.

**Comment by bluescreen303** [comment]
you don't need systemd-networkd for this.

there are very fine-grained units available to `depend`/`after` on.
There's `network-addresses-[interfacename].service` which completes once the interface is up and has an address. If you just want to wait for all interfaces to be up (and configured), there's `network-interfaces.target`. On top of that there's `network-setup.target` which performs some additional setup like setting routes/gateway/dns, which are not immediately needed for running services like nginx. And finally there's network.target, which only finishes when every networking part has successfully started.

The problem with all the above is the fact that this only works for interfaces that have a static configuration. The rest is managed through `dhcpcd`, which - by default - works for all unconfigured interfaces and just forks immediately on startup (which to systemd means it's ready/done). There's a `-w` option which we don't use, which would wait for an ip address to be assigned first before forking. 

This sounds like a nice default, but unfortunately we have a bit too much requiring/depending on `network.target` currently. Using `-w` would mean that on a laptop without network (for example when working in public transport), you wouldn't be able to boot to graphical login, as `graphical.target` requires `multi-user.target`, while `network.target` needs to complete _before_ it. With `dhcpcd` waiting for an ip address before forking, this will take until it gives up (30 seconds timeout). 

Basically our current dependencies are a bit messy. I don't think a multi-user (or graphical) environment really needs a (non-local) ip address so some discussion about our defaults might be useful. In the mean time, having `-w` available as an option would be nice though.

A complication is that we use 1 dhcpcd to handle all interfaces. Configured like this, dhcpcd will always fork (on success, but also on timeout), so there's no way for systemd (and depending services) to know if an interface is up now (apart from putting small tasks after dhcpcd to check and fail). When using a one-dhcpcd-instance-per-interface setup, this will improve (dhcpcd will fail on timeout and only fork on success), but such a setup implies explicitly mentioning all (dhcp) interfaces in configuration.nix, which is hard to do with the new dynamic interface-names and even without that, it's impossible to have a good default (`eth0` won't cut it for laptops which mainly use wireless). Another problem with 1-dhcpcd-per-interface is that there should be a retry-strategy. Our current (1 instance per system) dhcpcd will hang on listening for "link available" messages from the network card and retry. That behaviour is not available with a 1-dhcp-per-interface setup.

dhcpcd does provide hooks to notify the system when a lease is received (or an interface disconnects), but there aren't really good ways to hook these into systemd. Of course you can call `systemctl start [some-task]` in there, but that's a bit backwards (pushing instead of pulling). Probably we _can_ have a task create/destroy some directory (per interface) below `/run`. As systemd is capable of efficiently monitoring for paths/directories to become available, and having other units depend on that, these hooks can be made into (pull-based) triggers. A possible solution would be to write such a hook and add some nixos option `networking.required-dhcp-interfaces` that would make `network.target` depend on such files/directories. That way we can handle dhcp interfaces the same as static ones and properly wait/depend on them to come up.

All in all, I think we should redesign our dependency-graph a bit to properly support services on dhcp interfaces without getting 30sec+ wait times on boot if no cable is plugged.

**Comment by arno01** [comment]
@bluescreen303 many thanks for these details, I believe it will take some time to redesign the dependency-graph.

As a simple and painless solution why not to merge the https://github.com/NixOS/nixpkgs/pull/5846  ?  Pretty simple and safe implementation I think.  @lethalman already merged similar to master https://github.com/NixOS/nixpkgs/pull/5845

**Comment by lethalman** [comment]
Until we have proper dependency for networking I think a Restart on-failure with 1sec delay shouldn't hurt anyone, yes.

**Comment by bluescreen303** [comment]
@lethalman curently, network.target _does_ wait for (statically configured) interfaces to get assigned an ip address (they use a `Before` on network.target), so I think it is fair to expect the same for dhcp-enabled interfaces as well for consistency.  I agree however that network.target should just signal the starting of the network-stack, not its completion.

If `NetworkManager-online` and `networkd-online` are meant to signal "interface + IP up", then nginx should probably require+after that, right? As that's exactly what nginx needs to wait for, not just "stack started" as it obviously needs a configured (ip assigned) interface to listen on.

However, as NetworkManager and networkd are not enabled by default, it would be nice if this can be abstracted a bit, as dhcpcd _is_ capable of signaling "interface + IP running" and obviously some "networking completed" event/target is needed for many (non-local) services.

**Comment by lethalman** [comment]
@bluescreen303 depends on how nginx is configured. Mine doesn't need any ip to be up because it binds to 0.0.0.0. 

However yes, there's certainly room for improvement and nix here can shine thanks to the fact that we can actually check the ip address and in turn wait or not for the network event.

**Comment by bluescreen303** [comment]
@lethalman I know, using 0.0.0.0 works fine.
But as nixos does not know about this, we cannot cleverly depend on either network.target or network-online.target. Of course adding options to all services to choose whether to wait for an ip is an option.

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by fpletz** [comment]
I haven't seen this issue. I'm running nginx in different virtualization and networking environments.

Feel free to reopen if this issue persists.

**Comment by coretemp** [comment]
@fpletz Can you reopen this? 

I have the following in my configuration, which is otherwise a correct configuration (i.e. stopping and starting nginx does work):

```
   listen ${config.networking.privateIPv4}:${toString 10000};
```

I suspect the error is triggered when the nginx package is upgraded. 

```
Jul 23 10:05:06 webserver systemd[1]: Starting Nginx Web Server...
Jul 23 10:05:06 webserver nginx-pre-start[6991]: nginx: the configuration file /nix/store/cjm33ybxlh678fpn7sslxn6c5p51clqv-nginx.conf syntax is ok
Jul 23 10:05:06 webserver nginx-pre-start[6991]: 2018/07/23 10:05:06 [emerg] 7003#7003: bind() to 172.31.49.74:10000 failed (99: Cannot assign requested address)
Jul 23 10:05:06 webserver nginx-pre-start[6991]: nginx: configuration file /nix/store/cjm33ybxlh678fpn7sslxn6c5p51clqv-nginx.conf test failed
Jul 23 10:05:06 webserver systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 23 10:05:06 webserver systemd[1]: nginx.service: Failed with result 'exit-code'.
Jul 23 10:05:06 webserver systemd[1]: Failed to start Nginx Web Server.
Jul 23 10:05:16 webserver systemd[1]: nginx.service: Service hold-off time over, scheduling restart.
Jul 23 10:05:16 webserver systemd[1]: nginx.service: Scheduled restart job, restart counter is at 1.
```

**Comment by Profpatsch** [comment]
@coretemp Please open a new issue with your description, let’s not dig up zombie issues. :)
