### ISSUE TITLE
vlc: Add chromecast support

### ISSUE THREAD

**Issue by shazow** [NixOS/nixpkgs#58365]
The current vlc derivation does not include chromecast support.

I believe we need to add the flags `--enable-sout --enable-chromecast` during the configuration step to enable it by default, which I think is a reasonable thing to do.

I tried to do the minimal change myself, but looks like we need some new dependencies that don't exist in nixpkg yet:

```diff
diff --git a/pkgs/applications/video/vlc/default.nix b/pkgs/applications/video/vlc/default.nix
index cd3999e38c0..777e302e8e5 100644
--- a/pkgs/applications/video/vlc/default.nix
+++ b/pkgs/applications/video/vlc/default.nix
@@ -76,6 +76,8 @@ stdenv.mkDerivation rec {
   # "--enable-foo" flags here
   configureFlags = [
     "--with-kde-solid=$out/share/apps/solid/actions"
+    "--enable-sout"
+    "--enable-chromecast"
   ] ++ optional onlyLibVLC "--disable-vlc";
```

```
$ nix-env -i vlc -f $PWD
...
checking for protoc... no
checking for protobuf-lite >= 2.5.0... no
configure: error: Library protobuf-lite >= 2.5.0 needed for chromecast was not found
builder for '/nix/store/n8ky60h4n2r67agrgag5m5znijk2df59-vlc-3.0.6.drv' failed with exit code 1
```

I'm still fairly new so it will take some learning to figure out what needs to be done to package protobuf-lite (not sure I'll get around to it anytime soon).

If anyone else is into making these changes, it would be much appreciated. Or please let me know if I'm off-track here and there's a better way to do this.

**Comment by spencerjanssen** [comment]
You're on the right track.  This should work:

```diff
diff --git a/pkgs/applications/video/vlc/default.nix b/pkgs/applications/video/vlc/default.nix
index cd3999e38c0..f917a3c745b 100644
--- a/pkgs/applications/video/vlc/default.nix
+++ b/pkgs/applications/video/vlc/default.nix
@@ -13,6 +13,7 @@
 , jackSupport ? false
 , fetchpatch
 , removeReferencesTo
+, protobuf
 }:
 
 with stdenv.lib;
@@ -40,6 +41,7 @@ stdenv.mkDerivation rec {
     xorg.xlibsWrapper xorg.libXv xorg.libXvMC xorg.libXpm xorg.xcbutilkeysyms
     libdc1394 libraw1394 libopus libebml libmatroska libvdpau libsamplerate
     fluidsynth wayland wayland-protocols
+    protobuf
   ] ++ optional (!stdenv.hostPlatform.isAarch64) live555
     ++ optionals withQt5    [ qtbase qtsvg qtx11extras ]
     ++ optional jackSupport libjack2;
@@ -76,6 +78,8 @@ stdenv.mkDerivation rec {
   # "--enable-foo" flags here
   configureFlags = [
     "--with-kde-solid=$out/share/apps/solid/actions"
+    "--enable-sout"
+    "--enable-chromecast"
   ] ++ optional onlyLibVLC "--disable-vlc";
 
   # Remove runtime dependencies on libraries
```

**Comment by shazow** [comment]
@spencerjanssen Ah, now it builds, and I can see the relevant chromecast features, but it's still not finding the chromecast.

```
...
[00007faaac5d5b50] main probe debug: looking for renderer probe module matching "any": 0 candidates
[00007faaac5d5b50] main probe debug: no renderer probe modules
```

Sounds like that happens when microdns is not available. I tried adding nssmdns to the derivation but that didn't do the trick. `avahi.nssmdns` is enabled. Hmmmm.

**Comment by dtzWill** [comment]
https://github.com/NixOS/nixpkgs/pull/53184 FWIW (mostly because I like linking things together), but sounds like you're past what is useful from that :).

I frequently find chromecast programs on NixOS don't work... especially scanning support... with the firewall enabled.  #49630.  Should only need mdns support for discovery/scanning, I think :).

**Comment by shazow** [comment]
Yea I did see that. I don't think it's the firewall, as google-chrome chromecasts fine. Even VLC via flatpak manages to connect to the chromecast (but fails to encode due to some other error).

**Comment by arianvp** [comment]
Make sure avahi is running and that mdns is set in resolvconf

**Comment by shazow** [comment]
@arianvp Avahi is running and nssmdns is enabled, if that's what you mean. Is it working for you?

Reading an older VLC PR: https://github.com/NixOS/nixpkgs/pull/35124#issuecomment-385791097

Sounds like we need VLC's own libmicrodns packaged before this will work: https://github.com/videolabs/libmicrodns

**Comment by shazow** [comment]
I managed to package up libmicrodns and it's working now! I'll clean up and send a PR. :)

Thanks for the help everyone.
