### ISSUE TITLE
ghcHEAD isn't HEAD

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#5836]
I was starting to build the `ghcHEAD` derivation but noticed that the date seemed quite old. Looking at the source it appears to actually build `ghc-7.10.20141222` which I think is the first release candidate for `ghc-7.10`. 

Maybe this package could have a better name or am I missing the intended purpose?

**Comment by peti** [comment]
Well, if there is a newer version of GHC that you'd like to see, then you can always submit a PR. It seems that most users were happy with 7.10.1-rc1 for the time being and no-one bothered to update the expression so far.

**Comment by mpickering** [comment]
I don't mind too much. I just expected `ghc-7.11-20150118` to be built (ie by `git clone ..; perl boot; etc`). Feel free to close the issue if you like.
