### ISSUE TITLE
doc missing: How to use releaseTools.debBuild?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#58379]
## Issue description

I'm trying to build a debian package out of a nix package. I have:

```nix
let
  pkgs = (import ./default.nix);
  vm   = pkgs.vmTools.diskImageFuns.debian8x86_64 {};
  args = {
    diskImage = vm;
     src  = pkgs.vim;
   };
in
pkgs.releaseTools.debBuild args
```

but I get:

`error: value is a function while a set was expected, at /home/user/nixpkgs/vimdeb.nix:11:2`

I feel that documentation is missing on how to properly use that function (also same for `releaseTools.rpmBuild`.

### Steps to reproduce

Save the above expression as `vimdeb.nix` and call it with `nix-build ./vimdeb.nix`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-957.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(user): `"nixpkgs-19.09pre173445.796a8764ab8"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

---

Also: Can someone help me building direct and transitive dependencies from nixpkgs package expressions as deb or rpm packages?

**Comment by Infinisil** [comment]
You're missing a `{}` :)

```nix
let
  pkgs = import ./default.nix {}; # Compare with `import <nixpkgs> {}`
  vm   = pkgs.vmTools.diskImageFuns.debian8x86_64 {};
  args = {
    diskImage = vm;
     src  = pkgs.vim;
   };
in
pkgs.releaseTools.debBuild args
```

**Comment by matthiasbeyer** [comment]
Oh that's embarrasing.

But now I get this output (only the last few lines):

```
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
running tests
no Makefile or custom buildPhase, doing nothing
installing

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.

The checkinstallrc file was not found at:
/nix/store/wa35g83h4xpv0nadq688hgn2r90ay06l-checkinstall-1.6.2/sbin/../checkinstallrc

Assuming default values.


*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values:

0 -  Maintainer: [ root@(none) ]
1 -  Summary: [ Package created with checkinstall 1.6.2 ]
2 -  Name:    [ openssl-1.0.2r ]
3 -  Version: [ 0.0.0 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ amd64 ]
8 -  Source location: [ openssl-1.0.2r-bin ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ openssl-1.0.2r ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue:

Installing with /bin/sh -c make install...

========================= Installation results ===========================
make: *** No rule to make target 'install'.  Stop.

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

[   28.254749] reboot: Power down
```

**Comment by apeyroux** [comment]
`src  = pkgs.vim.src;`

**Comment by matthiasbeyer** [comment]
Jup that helps a bit. I'm currently trying to build the whole chain of dependencies recursively, which is a whole lot more complex.

**Comment by matthiasbeyer** [comment]
btw, this is WIP here: https://nixos.wiki/wiki/Nixpkgs/Building_RPM_DEB_with_nixpkgs

**Comment by Infinisil** [comment]
Seems resolved
