### ISSUE TITLE
clblas is not buildable

### ISSUE THREAD

**Issue by Shimuuar** [NixOS/nixpkgs#58427]
## Issue description

clblas is not buildable 

### Steps to reproduce

1. `nix-shell -p clblas` which will fail with obscure compile error

Build fails because of some incompatibility of gtest but if one uses vendored version build succeed without any problem. To do so one need to remove cmake's flag `-DUSE_SYSTEM_GTEST=ON` from derivations. So if one overrides clblas like this it builds fine:

```
    clblas = self.lib.overrideDerivation super.clblas (oldAttrs: {
      cmakeFlags = [];
    });
```

I only tested it on 18.09 but according to hydra 19.03 suffers from same problem

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.108, NixOS, 18.09.2394.2d656a97297 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"home-manager-18.09, nixos-18.09.2394.2d656a97297"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

P.S. I run into this issue while trying to install PyMC3

**Comment by markuskowa** [comment]
It broke with the update of gmock 1.8.0 -> 1.8.1:
https://hydra.nixos.org/api/scmdiff?rev1=0a308534615dc3cbb37f3c9400323a9089083343&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev2=a83d61b70864e7b539e129faa8842113b5a55716&branch=&type=git
