### ISSUE TITLE
Gogs missing sqlite by default

### ISSUE THREAD

**Issue by neonfuz** [NixOS/nixpkgs#58462]
## Issue description
Ever since PAM was added to gogs, the nix file has been written in a way that disables sqlite if PAM is enabled (including by default). I fixed the issue in a PR here: https://github.com/NixOS/nixpkgs/pull/58290

### Steps to reproduce
Enable gogs as a service. It will NOT include sqlite unless you explicitly disable PAM.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.29, NixOS, 19.09pre173166.373488e6f4c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(sage): `"nixpkgs-19.09pre173445.796a8764ab8"`
 - channels(root): `"nixos-19.09pre173166.373488e6f4c"`
 - nixpkgs: `/home/sage/.nix-defexpr/channels/nixpkgs`

**Comment by c0bw3b** [comment]
#58290 is merged
