### ISSUE TITLE
cloud-utils includes qemu; package qemu-utils?

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#58469]
## Issue description

I'm working on #58464 and realizing that 90% of the image being uploaded is a copy of `qemu`:

`image -> cloud-init -> cloud-utils -> qemu`

It looks like the referenced upstream package now uses `qemu-utils`. We should consider packaging it and using it instead and see if it cuts down on image size:

https://git.launchpad.net/cloud-utils/tree/debian/control

**Comment by colemickens** [comment]
https://packages.debian.org/unstable/qemu-utils

**Comment by colemickens** [comment]
On first impression, it looks like a sizeable reduction for images that include `cloud-init`:

```
595M     /nix/store/nmn798kahfqf47d4j6zfqwvy7m678hd0-digital-ocean-image
331M     /nix/store/kvq58qn9iqgpgr4v3dq9vk5zd05jz2ml-digital-ocean-image
```

**Comment by colemickens** [comment]
I sent a fix for this, btw: https://github.com/NixOS/nixpkgs/pull/58471

**Comment by hyperfekt** [comment]
#58471 is merged, can this be closed or is there still something to do?
