### ISSUE TITLE
h5py fails to build, but hasn't been changed

### ISSUE THREAD

**Issue by aherrmann** [NixOS/nixpkgs#5854]
Hi,

the package [h5py](https://github.com/NixOS/nixpkgs/blob/master/pkgs%2Fdevelopment%2Fpython-modules%2Fh5py%2Fdefault.nix) recently started [failing](http://hydra.nixos.org/build/18891013) with the following [error message](http://hydra.nixos.org/build/18891013/nixlog/1/tail-reload):

```
cc -pthread -shared -lgcc_s build/temp.linux-x86_64-2.7/h5py/defs.o -L/nix/store/zaxw7m6ja5zl09czszh4kdrmp878vlwc-hdf5-1.8.14/lib -L/nix/store/zaxw7m6ja5zl09czszh4kdrmp878vlwc-hdf5-1.8.14/lib64 -L/nix/store/l8rhnzq9yxqhv3il4kmzqhkx8q06jzgv-python-2.7.9/lib -R/nix/store/zaxw7m6ja5zl09czszh4kdrmp878vlwc-hdf5-1.8.14/lib -R/nix/store/zaxw7m6ja5zl09czszh4kdrmp878vlwc-hdf5-1.8.14/lib64 -lhdf5 -lhdf5_hl -lpython2.7 -o build/lib.linux-x86_64-2.7/h5py/defs.so
gcc: error: unrecognized command line option '-R'
gcc: error: unrecognized command line option '-R'
error: command 'cc' failed with exit status 1
builder for ‘/nix/store/1nihc066mlh070qbgnmm30k49bjfg6xr-python2.7-h5py-2.3.1.drv’ failed with exit code 1
```

The expression has not been changed, so some external change must have broken it. Updating h5py to the most recent version 2.4.0 didn't fix the issue either.

Does anyone know why the build is trying to pass the option `-R` to `cc`? I thought that was a linker option.

**Comment by aherrmann** [comment]
Okay, mid last year [someone else had the same issue](https://groups.google.com/forum/#!topic/h5py/lNXBrqJj8kc). Apparently it is related to how runtime dependencies are handled in distutils. H5Py [uses the `runtime_library_dirs` option](https://github.com/h5py/h5py/blob/9bd0310102335440241ca876920c6410815995bc/setup_build.py#L98) to make hdf5 a runtime dependency. Distutils interprets this option differently for different compilers. In the case of GCC [it should use the proper `-Wl` flags](https://github.com/python/cpython/blob/c7688b44387d116522ff53c0927169db45969f0e/Lib/distutils/unixccompiler.py#L235-L245). However, distutils tries to [identify GCC](https://github.com/python/cpython/blob/c7688b44387d116522ff53c0927169db45969f0e/Lib/distutils/unixccompiler.py#L207) simply by [comparing against the value of `$CC`](https://github.com/python/cpython/blob/c7688b44387d116522ff53c0927169db45969f0e/Lib/distutils/unixccompiler.py#L224). However, it seems like [this commit](https://github.com/NixOS/nixpkgs/commit/3e1fdb7a35369440dc624f74af24a13fb2be7708) made it so that `$CC` will be set to `cc`. Meaning that distutils [will default to the `-R` flag](https://github.com/python/cpython/blob/c7688b44387d116522ff53c0927169db45969f0e/Lib/distutils/unixccompiler.py#L250). Am I right with that assessment?

Is this now a distutils issue for mis-identifying GCC, or is this an h5py issue for relying on distutils through `runtime_library_dirs`, or is this a nixpkgs issue for seting `$CC=cc`?

---

Anyway, [someone else found a work-around](http://bytes.com/topic/python/answers/23331-rpath-setup-py) which is to scrap the `runtime_library_dirs` option, and instead supply `extra_link_args` manually. The following patch applies that work-around.

```
diff --git a/setup_build.py b/setup_build.py
index 7a73379..1f39243 100644
--- a/setup_build.py
+++ b/setup_build.py
@@ -95,7 +95,8 @@ class h5py_build_ext(build_ext):
 
         # TODO: should this only be done on UNIX?
         if os.name != 'nt':
-            settings['runtime_library_dirs'] = settings['library_dirs']
+            settings['extra_link_args'] = map(lambda lib: '-Wl,-rpath,' + lib,
+                                              settings['library_dirs'])
         
         def make_extension(module):
             sources = [localpath('h5py', module+'.pyx')] + EXTRA_SRC.get(module, [])
```

**Comment by iElectric** [comment]
See https://github.com/NixOS/nixpkgs/issues/5655

**Comment by aherrmann** [comment]
@iElectric Thanks, I wasn't aware of that issue/pr.
