### ISSUE TITLE
bazel: 0.22.0 doesn't build in Darwin sandbox

### ISSUE THREAD

**Issue by groodt** [NixOS/nixpkgs#58558]
## Issue description
bazel: 0.22.0 doesn't build in Darwin sandbox

### Steps to reproduce
Take a look and build the Bazel derivation in this PR:
https://github.com/NixOS/nixpkgs/pull/58557

`nix-build -A bazel`

It will fail on Darwin with `sandbox = true` and succeed with `sandbox = false`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by groodt** [comment]
Turns out that Hydra doesn't run with `sandbox = true` for Darwin. So Ofborg sandbox failures are "expected" sometimes and shouldn't be blockers for merging into master. Closing.

**Comment by LnL7** [comment]
This is still a valid issue

**Comment by LnL7** [comment]
Oh, I didn't realise you got it working for 0.24.0.

**Comment by groodt** [comment]
> Oh, I didn't realise you got it working for 0.24.0.

I did. That's why I closed this issue. It was my misunderstanding of Hydra vs Ofborg, but also I feel like you (or somebody else), must have changed something back in Ofborg, because now Sandbox builds of bazel for Darwin are working. I'm not sure how or why, unless you enabled those `extra-sandbox-paths = /System/Library/Frameworks /System/Library/PrivateFrameworks /usr/lib`

You can try kick-off https://github.com/NixOS/nixpkgs/pull/58557 and see what happens. Take a look at the Check for Darwin: https://github.com/NixOS/nixpkgs/pull/58557/checks?check_run_id=88804307

It's a "timeout", but it should have been a clear sandbox failure.

**Comment by LnL7** [comment]
The timeout was caused by something that got blocked by the sandbox, I didn't change anything on the build machine. I can reproduce the timeout locally with https://github.com/NixOS/nixpkgs/commit/bd1eb2654ad551e9f60f6beed5459c646f513a29. Not sure what changed, but it got stuck in `gettimeofday()` loop for some reason.

```
$ nix-build -A bazel
configuring
fixing libtool script ./third_party/protobuf/3.6.1/ltmain.sh
fixing libtool script ./third_party/protobuf/3.6.1/third_party/googletest/googlemock/build-aux/ltmain.sh
fixing libtool script ./third_party/protobuf/3.6.1/third_party/googletest/googletest/build-aux/ltmain.sh
no configure script, doing nothing
preBuildPhase
building
...
```

```
$ log stream | grep 'sandboxd'
-bash-3.2$ sudo log stream | grep 'sandbox'
sandboxd: [com.apple.sandbox.reporting.violation] SandboxViolation: javac(54391) deny mach-lookup com.apple.system.notification_center
sandboxd: [com.apple.sandbox.reporting.violation] SandboxViolation: javac(54391) deny file-read-data /dev/autofs_nowait
sandboxd: [com.apple.sandbox.reporting.violation] SandboxViolation: javac(54391) deny mach-lookup com.apple.system.opendirectoryd.membership
sandboxd: [com.apple.sandbox.reporting.violation] SandboxViolation: javac(54391) deny mach-lookup com.apple.bsd.dirhelper
```

```
$ ps aux | grep java
nixbld1         54391   0.0  0.3  5963812  27648   ??  S     4:17PM   0:00.06 /nix/store/9qyzw01bnla43457iwp6l9r6fbp7gk4y-zulu1.8.0_121-8.20.0.5/bin/javac -version

$ dtruss -p 54391
dtrace: system integrity protection is on, some features will not be available
SYSCALL(args)            = return
gettimeofday(0x7000091D7AF8, 0x0, 0x0)           = 0 0
psynch_cvwait(0x7FA343D12968, 0x100000100, 0x0)          = -1 Err#316
gettimeofday(0x7000091D7AF8, 0x0, 0x0)           = 0 0
psynch_cvwait(0x7FA343D12968, 0x100000100, 0x0)          = -1 Err#316
gettimeofday(0x7000091D7AF8, 0x0, 0x0)           = 0 0
psynch_cvwait(0x7FA343D12968, 0x100000100, 0x0)          = -1 Err#316
gettimeofday(0x7000091D7AF8, 0x0, 0x0)           = 0 0
...
```

**Comment by groodt** [comment]
Ok, that's interesting. My local build got stuck in a similar place, but it crashed hard, rather than looping forever. @uri-canva experiences the same crash as I do.

It's the same `javac -version` call which would cause sandboxing to fail that is mentioned in the thread, but I'm unable to reproduce it locally on my Mac. Maybe it's a different version of something on the host OS? Or a local nix config difference?

```
++ test -z /nix/store/9qyzw01bnla43457iwp6l9r6fbp7gk4y-zulu1.8.0_121-8.20.0.5
++ JAVAC=/nix/store/9qyzw01bnla43457iwp6l9r6fbp7gk4y-zulu1.8.0_121-8.20.0.5/bin/javac
++ [[ -x /nix/store/9qyzw01bnla43457iwp6l9r6fbp7gk4y-zulu1.8.0_121-8.20.0.5/bin/javac ]]
+++ /nix/store/9qyzw01bnla43457iwp6l9r6fbp7gk4y-zulu1.8.0_121-8.20.0.5/bin/javac -version
++ JAVAC_VERSION='dyld: Library not loaded: /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
  Referenced from: /nix/store/9qyzw01bnla43457iwp6l9r6fbp7gk4y-zulu1.8.0_121-8.20.0.5/bin/javac
  Reason: no suitable image found.  Did find:
        /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa: file system sandbox blocked stat()
        /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa: file system sandbox blocked stat()'
+ run_atexit_handlers 134
+ local exit_code=134
```

**Comment by flokli** [comment]
Is this still an issue on master?

**Comment by LnL7** [comment]
Not sure, I get this with the latest version.

```
/nix/store/bjcxmvjg4lakp0assgl9wl6g5zacr9ws-bash/bin/bash: /sbin/md5: Operation not permitted
```

**Comment by flokli** [comment]
Hm, this is clearly because of https://github.com/bazelbuild/bazel/blob/master/src/BUILD#L40-L42. I fear these things need to be hunted down one by one.

I do lack a environment to test this. Mac users welcome ;-)

**Comment by flokli** [comment]
@groodt has this been fixed somehow in the meantime, or why was it closed?
