### ISSUE TITLE
vdirsyncer fails to sync

### ISSUE THREAD

**Issue by loewenheim** [NixOS/nixpkgs#58563]
## Issue description
`vdirsyncer sync` fails with the vdirsyncer version from nixos-unstable. it works if I install vdirsyncer with pip.

```
$ vdirsyncer -vdebug sync 
debug: Using 1 maximal workers.
debug: Fetching value for password.fetch with command strategy.
Syncing contacts/32
error: Unknown error occurred for contacts/32: Server did not return etag.
error: Use `-vdebug` to see the full traceback.
debug:   File "/nix/store/y9qgx26b2w2lzqhqb7sd9cb6cz8dj7pa-vdirsyncer-unstable-2018-08-05/lib/python3.7/site-packages/vdirsyncer/cli/tasks.py", line 69, in sync_collection
debug:     partial_sync=pair.partial_sync
debug:   File "/nix/store/y9qgx26b2w2lzqhqb7sd9cb6cz8dj7pa-vdirsyncer-unstable-2018-08-05/lib/python3.7/site-packages/vdirsyncer/sync/__init__.py", line 143, in sync
debug:     b_nonempty = b_info.prepare_new_status()
debug:   File "/nix/store/y9qgx26b2w2lzqhqb7sd9cb6cz8dj7pa-vdirsyncer-unstable-2018-08-05/lib/python3.7/site-packages/vdirsyncer/sync/__init__.py", line 60, in prepare_new_status
debug:     if prefetch else ()):
debug:   File "/nix/store/y9qgx26b2w2lzqhqb7sd9cb6cz8dj7pa-vdirsyncer-unstable-2018-08-05/lib/python3.7/site-packages/vdirsyncer/storage/base.py", line 149, in get_multi
debug:     item, etag = self.get(href)
debug:   File "/nix/store/y9qgx26b2w2lzqhqb7sd9cb6cz8dj7pa-vdirsyncer-unstable-2018-08-05/lib/python3.7/site-packages/vdirsyncer/storage/_rust.py", line 42, in get
debug:     native.check_error(e)
debug:   File "/nix/store/y9qgx26b2w2lzqhqb7sd9cb6cz8dj7pa-vdirsyncer-unstable-2018-08-05/lib/python3.7/site-packages/vdirsyncer/native.py", line 35, in check_error
debug:     errors.check_exception(e[0])
debug:   File "/nix/store/4xg6a6pqm9v3b1vfmjncqy0w18iqfrhj-python3.7-shippai-0.3.2/lib/python3.7/site-packages/shippai/__init__.py", line 150, in check_exception
debug:     raise exc
error: 1 out of 2 tasks failed.
```

## Technical details

Output of `nix-shell -p nix-info --run "nix-info -m"`:
```
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.30, NixOS, 19.09pre173349.07b42ccf2de (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre173349.07b42ccf2de"`
 - channels(****): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by gebner** [comment]
Which `vdirsyncer` do you get via `pip`?  Is it the old 0.16 branch or the new 0.17 one (which was mostly rewritten in rust)?  We have the latest git version of 0.17 in nixpkgs.  Unfortunately, [vdirsyncer is currently looking for a maintainer](https://github.com/pimutils/vdirsyncer/issues/790) so it might be some time before this bug is fixed.

**Comment by loewenheim** [comment]
`--version` outputs this:
```
$ ~/.local/bin/vdirsyncer --version
vdirsyncer, version 0.16.7
```

**Comment by fritz-k** [comment]
Same problem here. Was there any reason to go for an alpha release except for the issue referenced in #33050? If not, a downgrade to 0.16.7 should be fine, since the original bug is still open and probably won't be fixed for a while without anyone maintaining vdirsyncer.

**Comment by gebner** [comment]
There are [a few bugs that](https://github.com/pimutils/vdirsyncer/issues/740#issuecomment-395047933) [are fixed](https://github.com/pimutils/vdirsyncer/issues/745#issuecomment-396934915) [in master](https://github.com/pimutils/vdirsyncer/issues/761#issuecomment-408588673), so I'd rather not downgrade.  I'd be happy with a `vdirsyncerStable` package for the 0.16 branch though.

**Comment by fritz-k** [comment]
That'd be great! I haven't looked into packaging yet, so it would take some time if I tried. Would you mind helping out?

**Comment by loewenheim** [comment]
I just opened a PR. It’s my first time contributing to `nixpkgs`, so I hope it’s up to snuff.
