### ISSUE TITLE
Provide a texlive collection with everything needed by sphinx

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#58571]
I a trying to use nixpkgs to build sphinx documentation, including pdf output, and I am currently writing an expression
```
      tex = pkgs.texlive.combine {
        inherit (pkgs.texlive) scheme-basic latexmk cmap collection-fontsrecommended fncychap titlesec tabulary;
      };
```
by trial and error, adding one package at a time.

This is a bit silly, and I feel that if I call `sphinx latexpdf`, then I should not be concerned with the internal dependencies of sphinx, which are an implementation detail. Also, as sphinx evolve, this will break.

It would be nice therefore if there was a ready-made derivation or texlive package set for “all things needed by sphinx”.

**Comment by nomeata** [comment]
I ended up with
```
      tex = pkgs.texlive.combine {
        inherit (pkgs.texlive)
          scheme-basic latexmk cmap collection-fontsrecommended
          fncychap titlesec tabulary varwidth framed fancyvrb float parskip
          wrapfig upquote capt-of needspace;
      };
```

**Comment by veprbl** [comment]
The latex output of sphinx can be extended [1] with arbitrary packages, so this is not going to cover the most general case. Ideally the list of packages would need to be sourced not from a trial and error, but from the source code or from the documentation (maybe [2]) to be more maintainable.

[1] http://www.sphinx-doc.org/en/master/latex.html
[2] https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.latex.LaTeXBuilder

**Comment by FRidh** [comment]
I agree with @veprbl and am going to set this as `wontfix`. The Sphinx package itself should also remain lightweight and not include all dependencies of every possible output format.

**Comment by FRidh** [comment]
Note we could add a minimum latex derivation as a `passthru` attribute.

**Comment by nomeata** [comment]
I didn’t know about `passthru`, but I think it is precisely what I had in mind: Not a dependency that everyone that installs Sphinx has to install, but easily can opt into.

**Comment by vcunat** [comment]
Right, the default sphinx will better be without TeX.  `sphinx.foo` added by `passthru` might be a nice way to expose the most commonly useful list of TeX packages.  At a quick look, [1] and [2] aren't very helpful, because Debian/Ubuntu split the whole TeX Live _only_ in a few big packages.

_The advantage of `passthru` is that it wouldn't affect `sphinx` itself in any way except for adding the attribute(s)._
