### ISSUE TITLE
mktexpk tries to write to HOME

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#58697]
## Issue description
```
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 0+420/600 --dpi 420 ifsym10
mkdir: cannot create directory '././homeless-shelter': Permission denied
mktexpk: /nix/store/syvf8qqn9ns8msf8rr3sxwa338qkg6s4-texlive-combined-2018/share/texmf/web2c/mktexdir /homeless-shelter/.texlive2018/texmf-var/fonts/pk/ljfour/public/ifsym failed.
```

Setting `HOME` to `$TMPDIR` before my build works, but isn't great.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.106, NixOS, 19.09pre172943.da1a2b1eeaf (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(michael): `""`
 - channels(root): `"nixos-19.09pre172943.da1a2b1eeaf, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by michaelpj** [comment]
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1010909 suggests it writes to `$TEXMFVAR`, which looks like it's getting set to something using `$HOME` by default. Maybe we need to set it?

**Comment by michaelpj** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive/bin.nix#L326 suggests @vcunat at least encountered this before.

**Comment by vcunat** [comment]
IIRC these were typically a symptom of some packages missing.  I don't know if these regenerations serve as some kind of fallback or what.  I never got to understand most TeX Live internals.

**Comment by michaelpj** [comment]
Hm, in this case I have `collection-fontsextra` which allegedly includes the font in question. I think it may actually be trying to generate them in the system conf dir, which is read only, and then falling back to the home dir.

Not really sure what should be happening here, e.g. whether these should exist at build time already.

**Comment by veprbl** [comment]
This should be fixed in some cases by #83816.

**Comment by imsekun** [comment]
@veprbl I ran into a similar issue except for a package I'm trying to make. Thanks so much. That PR was really helpful. <3

**Comment by michaelpj** [comment]
I came back to this because a colleague hit the same issue, but he's using an old nixpkgs. I think this is fixed today, so I'll close it.
