### ISSUE TITLE
insecure nokogiri and sanitize gem versions

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#58709]
## Issue description

Some of our packages use vulnerable versions of nokogiri and sanitize.

CCing maintainters.

 - [x] html-proofer by @primeos (nokogiri)
 - [ ] mikutter by @midchildan  (nokogiri)
 - [x] gollum by @jgillich and @primeos  (nokogiri, sanitize)
 - [ ] pt by @ebzzry (nokogiri)

Patches for this should probably go to master, 19.03, and 18.09 depending on when they land. Some of them have not been updated / touched in quite a long time -- so maybe a thing to do is mark them vulnerable and then eventually remove them.

**Comment by primeos** [comment]
Well, that's embarrassing, I also forgot to subscribe to updates for `html-proofer` :o

I've just pushed the fixes for `html-proofer` and `gollum` to `master` (both are now using `nokogiri 1.10.2`) and will backport them ASAP. Gollum is still using `sanitize 2.1.1` but that version should be fine ("LTS" branch - https://github.com/rgrove/sanitize/releases - but I should double-check that).

**Comment by Mindavi** [comment]
Probably not relevant anymore?

https://github.com/NixOS/nixpkgs/pull/119454
