### ISSUE TITLE
start display-manager doesn't do anything

### ISSUE THREAD

**Issue by garegin16** [NixOS/nixpkgs#5872]
after you start from the CD and type in root, start display-manager just returns you back to the prompt. I am running this on Hyper-V/Windows 8.

**Comment by edolstra** [comment]
Can you show the contents of `/var/log/X.0.log`?

**Comment by garegin16** [comment]
/var/log only has journal (which is a directory), lastlog, wtmp

**Comment by lewisl9029** [comment]
Seeing the same issue even after installing to disk on Windows 10 Hyper-V. Any workarounds?

**Comment by alexvorobiev** [comment]
Confirming the issue for 16.03 iso and Windows 10. I knew about issues with Gen. 2 VMs and selected Generation 1. Still X does not start.

**Comment by alexvorobiev** [comment]
I managed to find a workaround. The trick was to add the "RemoteFX 3D Video Adapter" to the VM. Now KDE starts as expected.

**Comment by garegin16** [comment]
I wonder why some distros have this problem in hyper-v, while others don’t.

**Comment by peterhoeg** [comment]
Doubt this is still a problem.

**Comment by Firehawke** [comment]
This just bit me in 2024, so Gen-2 Hyper-V is still problematic and RemoteFX is deprecated so the workaround isn't feasible on a Windows 11 host. Guess I'll see if WSL2 can work for what I'm trying to do.
