### ISSUE TITLE
Meson overrides compiler, ignoring stdenv

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#58831]
When I build a meson package (e.g. gnome-builder) with changed `stdenv` (e.g to `gcc8Stdenv`) it still builds with the compiler used by Meson:

https://github.com/NixOS/nixpkgs/blob/7c337cc807f2618e5f162a647e974cffcda86122/pkgs/development/tools/build-managers/meson/default.nix#L60

cc @Ericson2314

**Comment by matthewbauer** [comment]
That should only be used when cross compiling. It's maybe this line that we need to fix:

https://github.com/NixOS/nixpkgs/blob/7c337cc807f2618e5f162a647e974cffcda86122/pkgs/development/tools/build-managers/meson/setup-hook.sh#L27

**Comment by Ericson2314** [comment]
Yeah the stuff we do is just problems waiting to happen. I feel like I'm getting pretty close to making MESON use the env vars normally so we can just drop all that. :crossed_fingers::crossed_fingers::crossed_fingers:

**Comment by matthewbauer** [comment]
Can't we drop it now? CC and CXX should be set by stdenv right?

**Comment by nh2** [comment]
> Can't we drop it now?

Let's do it, I also just ran into this again: #80598

**Comment by nh2** [comment]
Wait in #59041 you decided to not do it?

If this needs an upstream fix we should do it, this totally breaks reasonable behaviour.

**Comment by vcunat** [comment]
> I feel like I'm getting pretty close to making MESON use the env vars normally so we can just drop all that.

@Ericson2314: can you provide a link or something?  I don't think I understand what you referred to.

**Comment by jtojnar** [comment]
I believe that referred to https://github.com/mesonbuild/meson/issues/3969

**Comment by Ericson2314** [comment]
Yes please make some noise in https://github.com/mesonbuild/meson/pull/6363 . I think it would be more persuasive if someone other than me explains the issue or it's ramifications, as I've sort of made my case.

**Comment by Ericson2314** [comment]
I suppose that would get more in the way without `strictDeps`, but with `strictDeps` it only effect `CC_FOR_BUILD`.

https://github.com/mesonbuild/meson/pull/6512 just got merged, so we can remove the  hack next release!

**Comment by leotaku** [comment]
@Ericson2314 Is removing the below workaround the only thing that needs to be done now? Or will individual package expressions have to be edited to accommodate this change? If we only need to remove the workaround, maybe someone can create a PR.

https://github.com/NixOS/nixpkgs/blob/703f052de185c3dd1218165e62b105a68e05e15f/pkgs/development/tools/build-managers/meson/default.nix#L66-L68

**Comment by Ericson2314** [comment]
Just that!

**Comment by leotaku** [comment]
@Ericson2314 From what I can tell, we do have the latest version. #98228

**Comment by Ericson2314** [comment]
Oh, great!

**Comment by vcunat** [comment]
But the above meson PR isn't contained in any release yet, it seems.

**Comment by Ericson2314** [comment]
Oh, right that's a `55.n+1` not `56`

**Comment by vcunat** [comment]
I always click the commit and watch the tag-set containing it.

**Comment by leotaku** [comment]
Sorry, I naively assumed that the PR was already in the 0.55.3 release because it was older than the release date shown on GitHub.
