### ISSUE TITLE
Link to mailing list in readme seems broken

### ISSUE THREAD

**Issue by nomosyn** [NixOS/nixpkgs#5884]
use:
    http://lists.science.uu.nl/mailman/listinfo/nix-dev

using: https://lists.science.uu.nl/mailman/listinfo/nix-dev gives:
![capture d ecran 2015-01-21 a 11 14 30](https://cloud.githubusercontent.com/assets/2693150/5834511/c6091332-a15e-11e4-93d2-d0685e28af9d.png)

**Comment by iElectric** [comment]
Fixed in 5a3a3c5e8f966483caa17741374c643452e7667f
