### ISSUE TITLE
Only set NIX_ENFORCE_PURITY when NIX_IGNORE_SYMLINK_STORE is unset

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#5888]
When using `NIX_IGNORE_SYMLINK_STORE`, one probably doesn't want to use `NIX_ENFORCE_PURITY`, because that will always fail because the symlinks get resolved. Should we avoid setting `NIX_ENFORCE_PURITY` in this case?

**Comment by edolstra** [comment]
`NIX_IGNORE_SYMLINK_STORE` is not passed to builders, so they can't ignore it. I guess they could check if `$(realpath $NIX_STORE) = $NIX_STORE`. However, it's really better to use a bind mount for /nix/store.

**Comment by bennofs** [comment]
My use case is that I want to use nix on a hosted CI system where I have access to a cache directory to save files between builds, but I'm not allowed to do a bind mount. I'd like to avoid having to copy the nix store between the cache directory and /nix, so I'd like to use a symlink.

**Comment by bennofs** [comment]
Ok, I don't need this anymore.
