### ISSUE TITLE
every firefox build gets its own profile by default (FF67+)

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#58923]
## Issue description
Every new firefox update/rebuild generates its own (new) profile. This is annoying, as we rebuild firefox whenever any of its dependencies changes. See: https://blog.nightly.mozilla.org/2019/01/14/moving-to-a-profile-per-install-architecture/

### Workaround:
Start with the profile manager `firefox -P` or with a custom profile `firefox --profile <PROFILE_PATH>`

### Steps to reproduce

configuration.nix
```
...
  environment.systemPackages = [
    pkgs.firefox-beta-bin
    ...
  ];
...
```

```
$ cd /nixpkgs
$ git pull upstream master
$ nixos-rebuild -I nixpkgs=/nixpkgs switch
$ firefox
```
## Technical details
```
nix-shell -I nixpkgs=/nixpkgs -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.5, NixOS, 19.09.git.5811d27 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre165037.eebd1a92637"`
 - channels(bali): `"nixos-18.03-18.03.133389.b551f89e256"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Should not it be just one profile per branch – one for stable, one for beta, one for nightly? Updating should not change the branch.

**Comment by ikervagyok** [comment]
I thought that too, but at least for me it created 4 profiles already - could be, that the FF beta is not smart enough (yet). Anyway, now it's documented, so people hopefully won't get as confused as I've been when/if they reproduce this.

**Comment by coreyoconnor** [comment]
Can repro as well. Unfortunate!

**Comment by coreyoconnor** [comment]
Not explicit above, but the workaround is:

1. If you see "this firefox uses a fresh profile"... quit
2. Start firefox profile manager with `firefox -P`
3. select an older profile and "use as default profile"
4. continue as normal until the next update

**Comment by dywedir** [comment]
Related [issue](https://github.com/mozilla/nixpkgs-mozilla/issues/163) and [workaround](https://github.com/rail/nixos-configs/commit/1ff8b6c3d8b98d0695045eedb97ce135025c36a1)

**Comment by wkral** [comment]
Firefox 67 is now the stable release, when I upgraded unstable this morning I got hit with this issue, I'd guess a lot of other folks will shortly as well. 

Could the SNAP_NAME workaround be incorporated into the derivation until there is a fix from Mozilla? If there is a better fix out there then maybe that.

**Comment by andir** [comment]
Just got made aware of the issues as well. I'd sway te SNAP_NAME workaround is okayish for now. I will try to get a patch made so that we do not need that in the future and have a proper kill-switch for that... Sorry for the troubles. I missed that during testing the latest release :'(

**Comment by andir** [comment]
I opened a PR to add the workaround https://github.com/NixOS/nixpkgs/pull/61980

Will do the backport as soon as someone else can confirm that it works as expected.

**Comment by wkral** [comment]
Looks like the more general solution has been merged into Firefox and will be deployed with 68+. 

From https://bugzilla.mozilla.org/show_bug.cgi?id=1528082

> Tested the implementation using latest Firefox 69.0a1, Firefox 68.0b14, Firefox 68.0 ESR (intermediary build from treeherder) on Ubuntu 18.04, macOS 10.14 and Windows 10 x64.
The dedicated profiles feature is off when MOZ_LEGACY_PROFILES is set to 1 at environment level, while the downgrade protection is still enabled. 

Probably should coordinate a change to that environment variable name with the release of 68, though it looks like the SNAP version would work for a while after as well.

**Comment by worldofpeace** [comment]
Can we set `MOZ_LEGACY_PROFILES` in the latest firefox now?

**Comment by andir** [comment]
We could do that but that wouldn't work with former ESR / tor browser and probably a few other things. In the long run that probably makes sense.

I am not sure it is worth the extra code to use the newer (equivalent) option for newer versions and the old one for older versions. There are constantly users that want older firefox versions because of plugins, java, … so we shouldn't just remove them?!

**Comment by ikervagyok** [comment]
this hasn't popped up in my daily usage for a while now - please comment/reopen if it's still an issue.
