### ISSUE TITLE
structured-haskell-mode doesn't compile with haskell-src-exts

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#5894]
Any chance of adding a workaround for that? See https://github.com/chrisdone/structured-haskell-mode/issues/90
The compile error is
```
src/Main.hs:172:21:
    Not in scope: data constructor ‘IHead’
    Perhaps you meant ‘DHead’ (imported from Language.Haskell.Exts.Annotated)

src/Main.hs:173:21:
    Not in scope: data constructor ‘IHead’
    Perhaps you meant ‘DHead’ (imported from Language.Haskell.Exts.Annotated)
```
Edit:
This seems to be a haskellngPackages only problem, I guess the stable one does still use haskell-src-exts 0.15

**Comment by peti** [comment]
I'll commit a fix later today.
