### ISSUE TITLE
NixOS image with latest kernel & ZFS Support

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#58959]
## Issue description

The minimal image uses the `latest` kernel for maximum hardware support. Unfortunately this causes periodic problems with having ZFS enable. In general, ZFS's releases don't guarantee support for the latest kernel release.

A currently relevant issue is https://github.com/zfsonlinux/zfs/issues/8545

I propose we disable support for ZFS in the latest-kernel minimal ISO.

cc @vcunat

**Comment by grahamc** [comment]
cc @samueldr

**Comment by jdanekrh** [comment]
Will there still be a (documented) path to install NixOS with ZFS /? Possibly install minimal system into what will be swap partition, and then do reinstall from this partition? Because ZFS / is what I am now using and want to continue to use.

**Comment by vcunat** [comment]
The default ISO will keep ZFS support &ndash; I don't think anyone here means to change that.  AFAIK it's just about the non-default latest-kernel ISO.

**Comment by grahamc** [comment]
these extra pings are because of packages being defined in all-packages.nix, instead of their own file:

### gap-libgap-compatible
```
  gap-libgap-compatible = let
    version = "4r8p6";
    pkgVer = "2016_11_12-14_25";
  in
    (gap.override { keepAllPackages = false; }).overrideAttrs (oldAttrs: {
      name = "libgap-${oldAttrs.pname}-${version}";
      src = fetchurl {
        url = "https://www.gap-system.org/pub/gap/gap48/tar.bz2/gap${version}_${pkgVer}.tar.bz2";
        sha256 = "19n2p1mdg33s2x9rs51iak7rgndc1cwr56jyqnah0g1ydgg1yh6b";
      };
      patches = (oldAttrs.patches or []) ++ [
        # don't install any packages by default (needed for interop with libgap, probably obsolete  with 4r10
        (fetchpatch {
          url = "https://git.sagemath.org/sage.git/plain/build/pkgs/gap/patches/nodefaultpackages.patch?id=07d6c37d18811e2b377a9689790a7c5e24da16ba";
          sha256 = "1xwj766m3axrxbkyx13hy3q8s2wkqxy3m6mgpwq3c3n4vk3v416v";
        })
      ];
  });
  libgap = callPackage ../development/libraries/libgap { };
```

### portaudio2014
```
  portaudio = callPackage ../development/libraries/portaudio {
    inherit (darwin.apple_sdk.frameworks) AudioToolbox AudioUnit CoreAudio CoreServices Carbon;
  };

  portaudio2014 = portaudio.overrideAttrs (oldAttrs: {
    src = fetchurl {
      url = http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz;
      sha256 = "0mwddk4qzybaf85wqfhxqlf0c5im9il8z03rd4n127k8y2jj9q4g";
    };
  });
```
### sqlite-replication
```
  sqlite-replication = sqlite.overrideAttrs (oldAttrs: rec {
    name = "sqlite-${version}";
    version = "3.24.0+replication3";
    src = pkgs.fetchFromGitHub {
      owner = "CanonicalLtd";
      repo = "sqlite";
      rev = "version-${version}";
      sha256 = "19557b7aick1pxk0gw013cf5jy42i7539qn1ziza8dzy16a6zs8b";
    };
    nativeBuildInputs = [ pkgs.tcl ];
    configureFlags = oldAttrs.configureFlags ++ [
      "--enable-replication"
      "--disable-amalgamation"
      "--disable-tcl"
    ];
    preConfigure = ''
      echo "D 2018-08-01T13:22:18" > manifest
      echo -n "c94dbda1a570c1ab180e7694afd3cc7116268c06" > manifest.uuid
    '';
  });
```

### libyamlcpp_0_3

```
  libyamlcpp = callPackage ../development/libraries/libyaml-cpp { };

  libyamlcpp_0_3 = pkgs.libyamlcpp.overrideAttrs (oldAttrs: rec {
    src = pkgs.fetchurl {
      url = "https://github.com/jbeder/yaml-cpp/archive/release-0.3.0.tar.gz";
      sha256 = "12aszqw6svwlnb6nzhsbqhz3c7vnd5ahd0k6xlj05w8lm83hx3db";
      };
  });
```

By all accounts, these packages should have pinged: the file they are defined in was changed, and their output paths were changed. The solution is to move these out of all-packages.nix and in to their own .nix files.

**Comment by NeQuissimus** [comment]
IMO, the ISO should be using the latest LTS kernel, not the latest kernel.

**Comment by samueldr** [comment]
I think that this is about the [`_new_kernel`](https://hydra.nixos.org/search?query=_new_kernel) variants which are built on hydra, but not published on the nixos.org website. They are often useful to kickstart an installation with really-new hardware (or yet unmainlined hardware for aarch64) at the tail end of a release. For both 18.03 and 18.09 I've personally recommended that variant of the iso for users which were unable to use the regular LTS iso.

And yes, I do agree, the regular ISOs should be using the latest LTS kernel, as they are currently.

**Comment by siraben** [comment]
Any updates on this?

**Comment by domenkozar** [comment]
I've hit this on latest 21.05:

```
error: Package ‘zfs-kernel-2.0.5-5.13.6’ in /home/ielectric/dev/nixpkgs/pkgs/os-specific/linux/zfs/default.nix:175 is marked as broken, refusing to evaluate.
```

**Comment by shanoaice** [comment]
I do agree that there is a need to keep a working ISO image with latest kernel, as some new hardware (such as Intel AX210 which happens to be the WiFi card of my laptop) isn't supported on the LTS kernel.

**Comment by samueldr** [comment]
This issue can be closed. The issue is resolved since `latest` isn't enabling ZFS anymore for this purpose exactly.
