### ISSUE TITLE
Quite a few packages have unnecessarily large runtime closures due to persisted build config

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#5895]
For example, perl, on my Mac OS system, keeps a `lib/perl5/5.20.1/darwin-2level/Config_heavy.pl` and `Config.pl` that refers to all sorts of unnecessary stuff, like the path to the `clang` that built it. This means that the closure for nix (which depends on perl modules, which depend on perl) balloons from fairly small to include clang, llvm, and other stuff stemming from those. 

I've noticed it in several other packages like gmp, curl, and probably others. Can we devise a clever/principled mechanism to kill these spurious references? I thought of nuking all references in that perl directory, but there's plenty of other meaningful stuff in there.

**Comment by vcunat** [comment]
Perl in particular tries to collect lots of information (and store it in the output), e.g. system admin's e-mail address, etc. I still wasn't able to make it completely pure on Linux, but there it depends "just" on gcc, coreutils, and glibc (as of master).

For necessary build dependencies, I see no better way than changing the config files after installation.

**Comment by copumpkin** [comment]
I was thinking that perhaps we could have a `nukeReferences` attribute that gets applied in `fixupPhase`, allowing me to instruct the script that the listed attributes should definitely _not_ be in the references after building. It would then behave like the regular `nuke-refs` script, except only on the store paths you specify. It wouldn't be fully automatic, but would save us from having to track down specific paths, and would allow us to make a clear assertion that some things should not be needed at runtime.

**Comment by vcunat** [comment]
There are attributes like ``allowedReferences`` which just make the build fail if the result contains unwanted references. I don't see a universally *safe* way of nuking references (so that the output still makes sense).

**Comment by vcunat** [comment]
For perl-5.22 in particular, I removed the compiler dependency at least https://github.com/NixOS/nixpkgs/issues/10244 (tested on Linux only ATM).

**Comment by copumpkin** [comment]
cc @edolstra 

This (the perl 5.20 issue) is causing the Nix installer closure to be painfully large in the upcoming Nix release. I'll patch perl 5.20 after work tonight (US Eastern) if nobody gets to it first.

**Comment by vcunat** [comment]
I had backported that change to 5.20 on the closure-size branch, so it no longer depends on gcc. I think those changes could be picked to staging, after a little testing.

**Comment by copumpkin** [comment]
@vcunat oh damn, I already wrote my own different patch for just perl-5.20, modeled on `nuke-refs`, and put it in staging. At some point I'll try to reconcile the two and see which is cleaner.

**Comment by vcunat** [comment]
Best do that as conflict resolution after merging to closure-size. According to my tests, both leave references only to libc and binutils, so they likely work the same.

**Comment by vcunat** [comment]
For now for closure-size I preserved the solution that was there before (i.e. deleted your change), but now didn't investigate deep enough to be able to form any strong opinion.

**Comment by Profpatsch** [comment]
I’ll close since the mentioned perl problem seems to be fixed and the state of closure-size minimization seems to have imroved.
