### ISSUE TITLE
R: Sys.which function fails

### ISSUE THREAD

**Issue by rhokue** [NixOS/nixpkgs#58963]
## Issue description

When running `Sys.which` function, an error occurs.

Apparently [`which` is a run-time dependency of R](https://github.com/HenrikBengtsson/Wishlist-for-R/issues/36). But [`which` is also defined as `buildInputs` in the nixpkgs-declaration of R](https://github.com/NixOS/nixpkgs/blob/8dcba2b842259b8b747dba6a4891b8cad3e4c03f/pkgs/applications/science/math/R/default.nix#L23). So I don't know why it doesn't work.

### Steps to reproduce

```sh
$ nix-env -iA nixpkgs.R
$ R
> Sys.which("sh")
Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) : 
  error in running command
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(username): `"nixpkgs-19.09pre170739.1a95a36dbf1"`
 - nixpkgs: `/Users/username/.nix-defexpr/channels/nixpkgs`

**Comment by rhokue** [comment]
I reproduced the issue on another machine:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.30, NixOS, 18.09.2366.45456fecc74 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(user): `"user-nixos-stable-18.09.2327.37694c8cc0e, user-nixos-unstable-19.09pre171786.34aa254f9eb"`
 - channels(root): `"nixos-18.09.2366.45456fecc74, nixos-unstable-19.09pre171786.34aa254f9eb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rhokue** [comment]
Using `strace` to debug:

```
$ strace -e execve -f R
> Sys.which("which")
strace: Process 13973 attached
[pid 13973] execve("/bin/sh", ["sh", "-c", "/nix/store/h0j0a5aq3yivkxz181ll2"...], 0x24a9e30 /* 87 vars */) = 0
strace: Process 13974 attached
[pid 13974] execve("/nix/store/h0j0a5aq3yivkxz181ll2sphqhm0si4c-which-2.21/bin/which", ["/nix/store/h0j0a5aq3yivkxz181ll2"..., "which"], 0x261d008 /* 88 vars */) = -1 ENOENT (No such file or directory)
[pid 13974] +++ exited with 127 +++
[pid 13973] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13974, si_uid=1000, si_status=127, si_utime=0, si_stime=0} ---
[pid 13973] +++ exited with 127 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13973, si_uid=1000, si_status=127, si_utime=0, si_stime=0} ---
Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) :
  error in running command
```

**Comment by rhokue** [comment]
Thanks @cleverca22 in #nixos@freenode :-)

**Comment by rhokue** [comment]
[Here](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/statistics.scm?id=v0.16.0-4337-gd8bead6c5d#n337) is how R is packaged for purely-functional Guix package manager (which is very advanced with packaging R and its libraries). Could be interesting and inspiring for a solution but in fact I don't see anything refering to `which` except that it's an input dependency.

**Comment by rhokue** [comment]
[This is where the `@WHICH@` string will be replaced during buildPhase.](https://github.com/wch/r-source/blob/tags/R-3-5-1/share/make/basepkg.mk#L76)

**Comment by rhokue** [comment]
@peti, as you're the maintainer of this package, I'd very much appreciate your help! :blush:

**Comment by rhokue** [comment]
@cleverca22 told me that `postInstall = "echo ${which} > $out/nix-support/ugly-hack";` could be a dirty workaround and in fact, it works!

**Comment by rhokue** [comment]
Should we use this dirty workaround? I could submit a pull request.

**Comment by peti** [comment]
I cannot reproduce this issue. `Sys.which()` works just fine for me (even if `which` is not in `$PATH`):

~~~ bash
$ nix-shell --pure -p R
nix-shell:~ $ type -pa which
nix-shell:~ $ type -pa R
/nix/store/s0hgph4sy28dybd4sf97z949bkdcdyh3-R-3.5.3/bin/R
nix-shell:~ $ Rscript --vanilla -e 'Sys.which("R")'
                                                          R 
"/nix/store/s0hgph4sy28dybd4sf97z949bkdcdyh3-R-3.5.3/bin/R" 
nix-shell:~ $ Rscript --vanilla -e 'Sys.which("sh")'
                                                                           sh 
"/nix/store/mcyvp1s45scjkkhyb1m16aqlsb8wr6hs-bash-interactive-4.4-p23/bin/sh" 
~~~~

That is using a current version of Nixpkgs `master` @ ca494bf6c3881124ced632f7b4072e8d1cee0bd3.

**Comment by peti** [comment]
OK, I think I found out what is going on. The store path for `which` *is* baked into R's base library, but the installed file is compiled and compressed, which obscures the path to Nix. Therefore, `which` ends up being unrecognized as a run-time dependency.

**Comment by rhokue** [comment]
Thank you very much :)
