### ISSUE TITLE
Haskell package sets should use mirrors when hackage is down

### ISSUE THREAD

**Issue by DanBurton** [NixOS/nixpkgs#58971]
## Issue description

During Hackage downtime, nix builds are needlessly broken. There are mirrors available; we should use them.

https://github.com/NixOS/nixpkgs/blob/b306b4cf1a9709dd8e671af6ebf75151e359e54f/pkgs/development/haskell-modules/make-package-set.nix#L186

See: https://www.reddit.com/r/haskell/comments/b99cef/hackage_downtime/

Mirrors include:
* http://objects-us-east-1.dream.io/hackage-mirror/
* http://hackage.fpcomplete.com/

### Steps to reproduce

I'm a third party reporting errors I've heard of, so I don't have precise repro steps.
Do certain Haskell-related build stuff during Hackage downtime, I guess?

**Comment by llelf** [comment]
Mirror list is  available at /mirrors.json
E. g. https://objects-us-east-1.dream.io/hackage-mirror/mirrors.json

**Comment by matthewbauer** [comment]
https://github.com/NixOS/nixpkgs/pull/59024
