### ISSUE TITLE
discord-haskell marked as broken, dependencies too strict?

### ISSUE THREAD

**Issue by ar1a** [NixOS/nixpkgs#58987]
## Issue description

discord-haskell is marked as broken. The most recent log I found was https://hydra.nixos.org/build/81859619/nixlog/1 and you can see the dependencies are too strict. I tried to install this package a few months ago before it was marked as broken and had the same issue.

### Steps to reproduce

create haskell project with `cabal init`. add discord-haskell to the dependencies, and set up a default.nix and whatnot. Observe.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.3, NixOS, 19.09pre173349.07b42ccf2de (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre173349.07b42ccf2de, nixos-stable-18.09.2243.63a09881b67"`
 - channels(aria): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ar1a** [comment]
i cloned discord-haskell 1.0, and managed to compile it OOTB with cabal2nix. I think the package can be unmarked as broken once 1.0 hits nixpkgs!

**Comment by ar1a** [comment]
@Infinisil is it possible you could unmark is as broken? I'm unsure as to where to move discord-haskell inside configuration-hackage2nix.yaml

**Comment by Infinisil** [comment]
Thanks, I unmarked it as broken in 7da906c0d39ad85e71c0a02dd761f3173fa6f620, which will make its way to master eventually :)

**Comment by ar1a** [comment]
so it **was** as easy as removing the line! thanks @Infinisil
