### ISSUE TITLE
Add per-package whitelisting for non-free packages

### ISSUE THREAD

**Issue by wolftune** [NixOS/nixpkgs#5899]
This is unlike https://github.com/NixOS/nixpkgs/pull/5892 which is about licenses.

I appreciate that Nix blacklists non-free packages by default, but it's really unfortunate to have a single action to remove that blacklist, even on a per-license basis. Anyone who isn't 100% hard-core software freedom person will choose to remove the blacklist and then all packages will seem similar.

The ideal behavior is that the user should have to take some action each and every time they want to install a non-free package. That way, they receive warning about packages being non-free. I may decide that accepting non-free terms is ok for one particular package and would not want to otherwise ignorantly install anything else non-free.

Please support one-by-one whitelisting of non-free packages so that everyone can choose to install particular non-free packages but still be warned / blocked about any other non-free packages in the future.

**Comment by matthiasbeyer** [comment]
This is actually supported, but undocumented. There is an option to white-list packages even if they are unfree, called `allowUnfreePredicate` in the code.

Look [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/default.nix#L26)

**Comment by matthiasbeyer** [comment]
There is actually an issue (#4389) about this. I want to solve that issue after #5892 or maybe in one step with #5892.

**Comment by dezgeg** [comment]
Seems like `allowUnfreePredicate` is documented now, so nothing left to do here.
