### ISSUE TITLE
Update sysdig to 0.25 to support Linux 5.0

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#59007]
## Issue description

Current sysdig version 0.24.2 is broken when used together with Linux Kernel 5.0. However a new version has been [released](https://github.com/draios/sysdig/releases/tag/0.25).

### Steps to reproduce

Use Linux 5.0 and try to enable sysdig.
```
boot.kernelPackages = pkgs.linuxPackages_latest;
boot.extraModulePackages = [
  config.boot.kernelPackages.sysdig
];
```

## Technical details

I am currently attempting to upgrade the version, but ran into some issues as they have added new dependencies:
#59006

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.33, NixOS, 19.09.git.d956f2279b8 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - nixpkgs: `/home/terje.larsen/src/github.com/terlar/nix-config/nixpkgs`

**Comment by bjornfor** [comment]
sysdig is updated on both master and release-19.03. Closing.
