### ISSUE TITLE
[Haskell NG] GHC 7.10 rc not in nixpkgs

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#5901]
GHC 7.10 RC would be quite useful for those of us that want our software to work with it when it comes out.

There is 7.8.4 and GHC HEAD (7.11) but no 7.10.

cc @peti

**Comment by peti** [comment]
GHC 7.10.1-rc-1 was added in 134d1a80c6a9dbdfb34c01dfb6850b254872994e:

    $ nix-build --no-out-link '<nixpkgs>' -A haskell-ng.compiler.ghc7101
    /nix/store/3iz6dxsamn2srkxrakrkj8775d7y3snh-ghc-7.10.0.20141222

    $ nix-build --no-out-link '<nixpkgs>' -A haskell-ng.packages.ghc7101.ghc
    /nix/store/3iz6dxsamn2srkxrakrkj8775d7y3snh-ghc-7.10.0.20141222

The HEAD expression now refers to 7.11.x.

**Comment by Fuuzetsu** [comment]
Oops, you're correct, I just spotted ghc7101 attribute. Still getting used to at where to look for this stuff.
