### ISSUE TITLE
eventstore: support on Darwin

### ISSUE THREAD

**Issue by fghibellini** [NixOS/nixpkgs#59015]
## Issue description

the package `evenstore` currently doesn't support Darwin although the the application itself is available for the system.

As you can see below I tried to fix it myself but I don't have much experience with Nix and I have no knowledge about v8,xcode,...

### Apparent cause

- the  eventstore nix expression [depends](https://github.com/NixOS/nixpkgs/blob/d97776b10504750c5889e42796813965541b0c12/pkgs/top-level/all-packages.nix#L13583) on [v8_6_x](https://github.com/NixOS/nixpkgs/blob/58efb6980fb02764153bc0b70f6e02b8890931f1/pkgs/development/libraries/v8/6_x.nix) which itself doesn't have support for Darwin.
- v8 seems to not support darwin because the v8 build infrastructure [requires xcode sdk >=10.12](https://chromium.googlesource.com/chromium/src/build.git/+/48a2b7b39debc7c77c868c9ddb0a360af1ebc367/config/mac/mac_sdk_overrides.gni#12) but nixpkgs uses xcbuild which provides sdk 10.10 (see `Steps to reproduce`).

I cannot find any information about what is the nixpkgs roadmap in terms of v8.

### Steps to reproduce

List xcbuild provided sdks:

```
$ export NIX_PATH="nixpkgs=https://releases.nixos.org/nixos/19.03/nixos-19.03beta171840.23fd1394dc6/nixexprs.tar.xz"
$ xcpath=$(nix-build -A xcbuild '<nixpkgs>')
$ ls ${xcpath}/Platforms/MacOSX.platform/Developer/SDKs
MacOSX.sdk  MacOSX10.10.sdk
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/4lpsw31ld1wvrwxwdpmpij2yv2380a5d-DarwinTools-1
  /nix/store/slknm0hlpm0k4x59fxhwlmik9alp6d7n-nix-info
copying path '/nix/store/4lpsw31ld1wvrwxwdpmpij2yv2380a5d-DarwinTools-1' from 'http://cache.nixos.org'...
copying path '/nix/store/slknm0hlpm0k4x59fxhwlmik9alp6d7n-nix-info' from 'http://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(fghibellini): `"nixpkgs-19.09pre170896.6e5caa3f8ac, nixos1709, nixpkgs-darwin-18.09pre153492.0b471f71fad"`
 - nixpkgs: `/Users/fghibellini/.nix-defexpr/channels/nixpkgs`
```

## Notes

1 .  `eventstore 4.1.1` actually requires `v8 ver. 5.2` and from `5.x.x` it requires `v8 ver. 7.0` as stated [here](https://eventstore.org/blog/20190218/event-store-5.0.0-release/)

**Comment by veprbl** [comment]
10.12 will come with #56744
