### ISSUE TITLE
Packaging the Deepin Desktop Environment

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#59023]
The [Deepin Desktop Environment (DDE)](https://www.deepin.org/en/) is an elegant and easy to use desktop environment of the Chinese [Deepin](https://en.wikipedia.org/wiki/Deepin) Linux distribution.

The purpose of this issue is to list the packages needed to have DDE in NixOS, as well as to discuss ideas on the process of packaging them.

Some of them have already been packaged.

**Packages**:
- [x] dbus-factory
- [x] dde-api
- [x] dde-calendar
- [x] dde-control-center
- [x] dde-daemon
- [x] dde-dock
- [x] dde-file-manager
- [x] dde-launcher
- [x] dde-network-utils
- [x] dde-polkit-agent
- [x] dde-qt-dbus-factory
- [x] dde-session-ui
- [ ] deepin-account-faces
- [x] deepin-anything
- [x] deepin-desktop-base
- [x] deepin-desktop-schemas
- [x] deepin-gettext-tools
- [x] deepin-gtk-theme
- [x] deepin-icon-theme
- [x] deepin-image-viewer
- [ ] deepin-manual
- [x] deepin-menu
- [x] deepin-metacity
- [x] deepin-mutter
- [ ] deepin-screensaver
- [x] deepin-screenshot
- [x] deepin-shortcut-viewer
- [x] deepin-sound-theme
- [ ] deepin-system-monitor
- [x] deepin-turbo
- [x] deepin-wallpapers
- [x] deepin-wm
- [x] dpa-ext-gnomekeyring
- [x] dtkcore
- [x] dtkwidget
- [x] dtkwm
- [x] go-dbus-factory
- [x] go-dbus-generator
- [x] go-gir-generator
- [x] go-lib
- [x] qcef
- [x] qt5dxcb-plugin
- [x] qt5integration
- [x] udisks2-qt5
- [ ] startdde

**Extra packages**:
- [x] deepin-calculator
- [ ] deepin-editor
- [x] deepin-movie-reborn
- [x] deepin-screenshot (dbus)
- [x] deepin-terminal

**Services**;
- [x] dde-api (dbus, systemd, user)
- [x] dde-calendar (dbus)
- [x] dde-control-center (dbus)
- [x] dde-daemon (dbus, systemd, user)
- [x] dde-dock (dbus)
- [x] dde-file-manager (dbus, systemd)
- [x] dde-launcher (dbus)
- [x] dde-session-ui (dbus)
- [x] deepin-anything (dbus, systemd, kernel module, user)
- [x] deepin-image-viewer (dbus)
- [ ] deepin-manual (dbus)
- [x] deepin-menu (dbus)
- [ ] deepin desktop environment
- [ ] deepin-screensaver (dbus)
- [x] deepin-turbo (user systemd)

**Debugging**:

**Issues**:
- dde-daemon: https://github.com/NixOS/nixpkgs/pull/59520#pullrequestreview-226418737
  - [ ] install image files at `/var/cache/appearance/thumbnail/backgrounds/`. This is not allowed because it is outside of the Nix store. [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html) says that _`/var/cache` is intended for cached data from applications. Such data is locally generated as a result of time-consuming I/O or calculation. The application must be able to regenerate or restore the data. Unlike `/var/spool`, the cached files can be deleted without data loss._ Maybe they are generated by `lib/deepin-daemon/theme-thumb-tool` and can be omitted from the installation. Let's see when testing DDE...
  - [x] `/var/lib/polkit-1/localauthority/10-vendor.d/`
  - [ ] configuration for `dde-authority-pam`: `share/pam-configs` `etc/pam.d`. `pam-configs` seems to be documented at https://wiki.ubuntu.com/PAMConfigFrameworkSpec
- [ ] dde-dock: investigate `share/polkit-1/actions/com.deepin.dde.dock.overlay.policy` (see https://github.com/NixOS/nixpkgs/pull/59244#issuecomment-485375376)
- [ ] dde-dock: wrapper for plugins (dde-file-manager, ...)
- [ ] deepin-anything: wrapper for plugins (dde-file-manager, ...) (see https://github.com/NixOS/nixpkgs/pull/59378#issuecomment-482765464)
- [ ] deepin-mutter: wrapper for plugins
- [ ] deepin-wm: wrapper for plugins (currently no other DDE component installs a plugin)
- [ ] dde-polkit-agent: wrapper for plugins ([`dpa-ext-gnomekeyring`](https://github.com/linuxdeepin/dpa-ext-gnomekeyring))
- [ ] dde-file-manager: wrapper for plugins (, ...)
- [ ] Deepin settings schemas (provided by [`deepin-desktop-schemas`](https://github.com/linuxdeepin/deepin-desktop-schemas)) are used by `dtkwidget` and its dependencies, so it may need wrapping (see https://github.com/NixOS/nixpkgs/pull/61366#issuecomment-493761858).

cc @worldofpeace

**Comment by romildo** [comment]
#59038 adds `dde-network-utils`.

**Comment by romildo** [comment]
https://github.com/NixOS/nixpkgs/pull/59092 adds deepin.qcef (Qt5 binding of Chromium Embedded Framework), a dependency for the forthcoming deepin manual.

**Comment by worldofpeace** [comment]
@romildo Do you have an expression for `deepin-screenshot`?

Just checking so I don't duplicate one if you have it and just haven't pr'd it.

**Comment by romildo** [comment]
Yes, I have. I will open a PR for it.

**Comment by romildo** [comment]
@worldofpeace When a package has associated dbus services, systemd services, kernel modules, and/or specific groups and users, it deserves a NixOS module, like I have been doing, right?

The alternative would be having a unique module for the entire DDE, which would enable those services and kernel modules, and create groups and users for all deepin packages in a single place.

It seems that GNOME is going from something like this second alternative to the first one alternative.

**Comment by worldofpeace** [comment]
> The alternative would be having a unique module for the entire DDE, which would enable those services and kernel modules, and create groups and users for all deepin packages in a single place.

> It seems that GNOME is going from something like this second alternative to the first one alternative.

So with GNOME, lots of the pieces need to be shared. For example, gnome-settings-daemon has many forks so it has a [`package` option](https://github.com/NixOS/nixpkgs/blob/1a66e1dd276940e9666ff5fee1f1a739f3a55736/nixos/modules/services/desktops/gnome3/gnome-settings-daemon.nix#L24). Plus lots of optional services. That's why we're planing on having https://github.com/NixOS/nixpkgs/pull/54415

Now with deepin I think there should be individual modules for applications if needed (deepin-screenshot, etc.).
But for the really lower level services, (dde-api, dde-daemon), they only make sense to be enabled if you're using the DE. It's just not flexible like that. And if someone would disable them it would just break, so having an individual options isn useful.


So having
> The alternative would be having a unique module for the entire DDE, which would enable those services and kernel modules, and create groups and users for all deepin packages in a single place.

for the tightly coupled stuff makes sense to me.

**Comment by worldofpeace** [comment]
##### Note: discussion on IRC is convenient to me for further discussion

**Comment by worldofpeace** [comment]
I've drafted a `dde-control-center` expression
* https://github.com/worldofpeace/nixpkgs/commit/b13a16d65c05de8d93be9109d054e332c3557378

but haven't had time to make it build.

###### perhaps it has to do with this https://src.fedoraproject.org/rpms/deepin-control-center/blob/master/f/deepin-control-center.spec#_49 ?

**Comment by romildo** [comment]
> I've drafted a `dde-control-center` expression [...] but haven't had time to make it build.

I have tried your expression, and it fails to build for me too.

> ###### perhaps it has to do with this https://src.fedoraproject.org/rpms/deepin-control-center/blob/master/f/deepin-control-center.spec#_49 ?

I think this is not related. This is just Fedora fixing the `lib` dir fit its file system layout.

I have found that somehow `dtkcore` is installing a older version of the library:

``` c
$ grep VERSION /nix/store/8kpivw2m04mx1p7ja1b8fgr3bxbw0lmv-dtkcore-2.0.14/include/libdtk-2.0.6/DCore/dtkcore_config.h
#define DTK_VERSION_MAJOR 2
#define DTK_VERSION_MINOR 0
#define DTK_VERSION_PATCH 6
#define DTK_VERSION_BUILD 0
#define DTK_VERSION_STR "2.0.6"
```
and as a consequence the test at https://github.com/linuxdeepin/dde-control-center/blob/master/src/frame/modules/sound/soundworker.h#L121 is evaluating to true, and an adicional header file is included, exactly where an error is being reported:

```
In file included from /nix/store/bzh7jppvdzbqscw7zl40w467ljik5ivk-qtbase-5.12.0-dev/include/QtCore/qobject.h:54:0,
                 from /nix/store/bzh7jppvdzbqscw7zl40w467ljik5ivk-qtbase-5.12.0-dev/include/QtWidgets/qwidget.h:45,
                 from /nix/store/bzh7jppvdzbqscw7zl40w467ljik5ivk-qtbase-5.12.0-dev/include/QtWidgets/QWidget:1,
                 from /build/source/src/frame/widgets/contentwidget.h:29,
                 from /build/source/src/frame/settingswidget.h:29,
                 from /build/source/src/frame/settingswidget.cpp:26:
/build/source/src/frame/modules/sound/soundworker.h:122:5: error: redefinition of 'struct QMetaTypeId<Dtk::Widget::DDesktopServices::SystemSoundEffect>'
```

**Comment by romildo** [comment]
With https://github.com/NixOS/nixpkgs/pull/63795 `dde-control-center` building succeeds locally.

**Comment by worldofpeace** [comment]
> With #63795 `dde-control-center` building succeeds locally.

Cool, I should be able to pr that properly now :+1:

**Comment by romildo** [comment]
> > With #63795 `dde-control-center` building succeeds locally.
> 
> Cool, I should be able to pr that properly now +1

Remeber to add the dbus service to the nixos module:
``` patch
 nixos/modules/services/desktops/deepin/deepin.nix | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/nixos/modules/services/desktops/deepin/deepin.nix b/nixos/modules/services/desktops/deepin/deepin.nix
index d9d5d539e42..d45fa638ef4 100644
--- a/nixos/modules/services/desktops/deepin/deepin.nix
+++ b/nixos/modules/services/desktops/deepin/deepin.nix
@@ -33,6 +33,7 @@
       environment.systemPackages = [
         pkgs.deepin.dde-api
         pkgs.deepin.dde-calendar
+        pkgs.deepin.dde-control-center
         pkgs.deepin.dde-daemon
         pkgs.deepin.dde-dock
         pkgs.deepin.dde-file-manager
@@ -45,6 +46,7 @@
       services.dbus.packages = [
         pkgs.deepin.dde-api
         pkgs.deepin.dde-calendar
+        pkgs.deepin.dde-control-center
         pkgs.deepin.dde-daemon
         pkgs.deepin.dde-dock
         pkgs.deepin.dde-file-manager
-- 
2.22.0
```

**Comment by worldofpeace** [comment]
@romildo I think this could be a very informative read for us https://github.com/linuxdeepin/developer-center/issues/1093 (particularly on there frequent releases)

They seem to move at a very fast rate and I'm wondering how we can align this in our release process for the best experience for the end user.

**Comment by romildo** [comment]
> @romildo I think this could be a very informative read for us [linuxdeepin/developer-center#1093](https://github.com/linuxdeepin/developer-center/issues/1093) (particularly on there frequent releases)
> 
> They seem to move at a very fast rate and I'm wondering how we can align this in our release process to get the best experience for the end user.

Summarizing: they release new versions of packages very fast, without any indication of stability. Sometimes the released code is unstable. That is making packagers (mainly of archlinux derivative distributions) unhappy.

If there was a way of telling which releases are stable, it would be simpler. For now we can complete the packaging of DDE so that we can use it ourselves for testing, and fixing packaging issues. We can try to update frequently and test the desktop environment to check that it mostly works.

**Comment by romildo** [comment]
@worldofpeace Any idea on how to handle a package that originally install files at `/var`?

All files installed by [`dde-account-faces`](https://github.com/linuxdeepin/dde-account-faces) are placed at `/var/lib/AccountsService/icons/`.

Other packages look for them at that location:
```
$ grep --color -r '/var/lib/AccountsService'
dde-daemon/accounts/manager.go:	actConfigDir       = "/var/lib/AccountsService"
dde-daemon/accounts/user.go:	defaultUserIcon          = "file:///var/lib/AccountsService/icons/default.png"
dde-control-center/src/frame/modules/accounts/modifyavatarpage.cpp:        if (avatar.startsWith("file:///var/lib/AccountsService/icons/local"))
dde-session-ui/global_util/constants.h:static const QString CONFIG_FILE("/var/lib/AccountsService/users/");
```

**Comment by worldofpeace** [comment]
So I'm half guessing that they want you to be able to modify the user icon in `dde-control-center` using the icons there. And `dde-daemon` wants to set their default icon.

I don't think any of these things would require them to install files to `/var/lib/AccountsService/icons` because the dbus api has `SetIconFile`.

**Comment by worldofpeace** [comment]
It looks like wrappers for qt have been merged #54525.
When that hits master we should probably wrap the qt applications in deepin.

**Comment by Ninlives** [comment]
Is this still under development?

**Comment by worldofpeace** [comment]
The final piece should be here https://github.com/NixOS/nixpkgs/pull/63813, through since the switch to kwin it's no longer working.

**Comment by romildo** [comment]
Still in progress.

**Comment by romildo** [comment]
Packaging of the Deepin Desktop Environment has been cancelled (https://github.com/NixOS/nixpkgs/issues/94870).
Closing.
