### ISSUE TITLE
Package VSCodium

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#59028]
## Issue description
Package VSCodium. https://github.com/VSCodium/vscodium

Multiple reasons:
1. OSS is good. Building from source seems ideologically good.

2. The VSCode binary releases from Microsoft have unfavorable licensing terms: https://github.com/VSCodium/vscodium#why

3. Potentially makes it easier to test unreleased features, and/or do things like used patched versions of Chromium for Wayland, etc.

**Comment by tadeokondrak** [comment]
related: #26698
