### ISSUE TITLE
Add perl.withPackages function

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#59042]
## Issue description
Currently perl has no way to build an environment like python.withPackages does.

@volth As the resident NixOS perl expert do you have any motivation to add this? I was digging through the python code for withPackages and it is fairly involved...

**Comment by volth** [comment]
The latest discussion: https://github.com/NixOS/nixpkgs/pull/55786 https://github.com/NixOS/nixpkgs/pull/55786#issuecomment-464144459
