### ISSUE TITLE
Update deadbeef to 1.8.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#59135]
> It's been almost 3 years since the previous release, but the new one is finally here! It was a lot of effort to make it happen.

http://deadbeef.sourceforge.net/posts/deadbeef_1.8.0_is_out.html  
https://github.com/DeaDBeeF-Player/deadbeef  
https://github.com/NixOS/nixpkgs/blob/release-19.03/pkgs/applications/audio/deadbeef/default.nix

Related to #52617

**Comment by JohnAZoidberg** [comment]
It has been updated on master. I think what you want is a backport. Seems reasonable.

**Comment by jtojnar** [comment]
Here is the PR that upgraded it: https://github.com/NixOS/nixpkgs/pull/59187

**Comment by luzpaz** [comment]
@jtojnar thanks! btw, it's at 1.8.3 currently: https://deadbeef.sourceforge.io/posts/deadbeef_1.8.3_is_out.html  
Could you bump it to that ?

**Comment by jtojnar** [comment]
We already did #83693
