### ISSUE TITLE
systemd-timesyncd timesync services crashes with failed assertion

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#5913]
I set `services.timesyncd.enable = true` in my `configuration.nix` and switched, but the new timesync services crashes: 

    # SYSTEMD_LOG_LEVEL=debug /run/current-system/sw/lib/systemd/systemd-timesyncd 
    Added new server time1.google.com.
    Added new server time2.google.com.
    Added new server time3.google.com.
    Added new server time4.google.com.
    Removed server time1.google.com.
    Removed server time2.google.com.
    Removed server time3.google.com.
    Removed server time4.google.com.
    Assertion 'm' failed at src/libsystemd/sd-network/sd-network.c:301, function sd_network_monitor_unref(). Ignoring.
    Failed to allocate manager: No such file or directory

According to the source code, this might be caused by the fact that `/run/systemd/netif/links/` doesn't exist. Does anyone know what that path is and why `systemd` seems surprised that it's not there?

I'm running NixOS 15.05pre56489.0e8187b (Dingo).

**Comment by dezgeg** [comment]
I don't know what that directory does but it is created in the upstream systemd-tmpfiles configuration, which wedoesn't use. I suppose we should.

**Comment by dezgeg** [comment]
The commit 5d02c02a9bfd6912e4e0f700b1b35e76d1d6bd3f has been in master for quite a while, and timesyncd seems to work fine now (At least my ARM boards with no battery-backed RTCs are still telling the correct time). This can be closed now.

**Comment by dezgeg** [comment]
@peti wanna close this?
