### ISSUE TITLE
haskell-ng: extend generic-builder to export shell-hook and $configureFlags

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#5916]
Provide a `shellHook` in normal builds that runs our non-standard setup phases:

    runHook setupCompilerEnvironmentPhase && runHook jailbreakPhase && runHook compileBuildDriverPhase

We also might want to re-consider use of `local` in these hooks, which prevents them from being run via `eval`.

Furthermore, the interactive `env` environment should define meaningful `$configureFlags` that users can pass to `./Setup configure` to configure the build the same way we to in Nixpkgs.

**Comment by puffnfresh** [comment]
I have a shell.nix generated by the new cabal2nix and I don't have an easy way to run the right patchPhase. I have to enter another shell with jailbreak-cabal and manually run it. Then I can `cabal build` my project.

Is there a better solution?

**Comment by peti** [comment]
No, not yet I'm afraid. 'cabal2nix' should generate a more convenient environment; it's just not implemented yet.

**Comment by Fuuzetsu** [comment]
cc self

**Comment by Profpatsch** [comment]
(triage) was this addressed in the meantime? cc @peti @Fuuzetsu
