### ISSUE TITLE
Add mirror for Flash Player plugin files

### ISSUE THREAD

**Issue by zookatron** [NixOS/nixpkgs#59276]
## Issue description

It appears that every time Adobe releases a new version of the Flash Player NPAPI plugin, the old versions are deleted from their server. This causes the NixOS stable channels to suddenly stop building any configuration that includes the `pkgs/applications/networking/browsers/mozilla-plugins/flashplayer` derivations because it can't download the binary files from Adobe. This appears to happen [pretty frequently](https://github.com/NixOS/nixpkgs/issues?utf8=%E2%9C%93&q=Flash+player) and every time it happens it's a really annoying experience where I either need to manually change my version of that package that I'm using or wait for a backport to fix it on the stable channel.

It would be really great if we could have some kind of mirror for these files so these updates by Adobe don't randomly break system builds before the flashplayer derivations are patched. Frankly I don't really know what would be involved in setting something like this up correctly for NixOS, but I thought it might be good to start off a discussion about how this is affecting the user experience on NixOS.

### Steps to reproduce

1. Add to `etc/nixos/configuration.nix`
```
environment.systemPackages = [ ... pkgs.firefox ... ];
nixpkgs.config = { ... firefox.enableAdobeFlash = true; ... };
```

2. Wait for Adobe to update Flash Player plugin

3. `nixos-rebuild build` and get error `error: cannot download flash_player_npapi_linux.x86_64.tar.gz from any mirror`

### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.32, NixOS, 19.03beta172025.91fa6990b25 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by zookatron** [comment]
Would it be possible instead of downloading from Adobe directly to change the derivation to instead get the files from another package repository that keeps old binary versions around like the Arch Archive? https://archive.archlinux.org/packages/f/flashplugin/

**Comment by AleXoundOS** [comment]
It also affects flashplayer-standalone.

I see the problem is that there is the same upstream url for different releases. Maybe it's better to link to specific releases in [Flash Player archives](https://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html)? Every single archive contains a big bundle of adobe flash flavors so the size is big (425 MiB for the latest release). But at least the url does not change.

**Comment by AleXoundOS** [comment]
Currently, if not updating the whole system, I resort to [pinning recent unstable nixpkgs with flashplayer](https://github.com/NixOS/nixpkgs/issues/18527#issuecomment-609482564) which has relevant url.

**Comment by AleXoundOS** [comment]
Was hit again (had to _re-pin_ on top of f63bc540cbd).
Btw, what is the reason not to populate https://cache.nixos.org with store paths of unfree derivations?

**Comment by AleXoundOS** [comment]
Still important for me.

**Comment by Shados** [comment]
The Flash Player archive page has apparently been decommissioned due to Flash's upcoming EOL.

**Comment by sid-cypher** [comment]
Oh, then we should definitely back up and/or collect last versions of plugin, standalone and debugger, and keep them safe after Adobe drops them.

No more maintenance automatically means that this issue will no longer be applicable, just need to preserve what's already there.

**Comment by Shados** [comment]
On that note: There's a kill-switch in more recent versions of Flash, which will disable playback after the EOL date. There are 'Enterprise Enablement' configuration options that can override this based on a URL pattern whitelist.

**Comment by sid-cypher** [comment]
That is very good to know. The kill switch was probably added in the February 2020 release, together with the EnableAllowList setting.

According to the Adobe Flash Player 32.0 Administration Guide (August 20, 2020) the player will read /etc/adobe/mms.cfg configuration file with following relevant settings:
`EOLUninstallDisable=1`
`AllowListRootMovieOnly=1`
`EnableAllowList=1`
`AllowListUrlPattern = <scheme> ://<host>:<port>/<path>` 
`  <scheme> = '*' | 'http' | 'https' `
`  <host> = <any char except '.' and '*'> `
`  <port> (optional) = '*' | <any valid port number> `
`  <path> = '/' <any chars>`
NOTE: The wildcard must be followed by at least two labels, so `http://*/` is not valid, nor is `http://*.com/`.
NOTE: `http:*`, `https:*` and `*:*` are not permitted as they are overly general.

**Comment by Shados** [comment]
Also of note is the [Flashpoint](https://bluemaxima.org/flashpoint/) project, which is an attempt to preserve Flash games in light of the EOL.

**Comment by zookatron** [comment]
Closing this issue as Firefox no longer supports the Flash NPAPI plugin.
