### ISSUE TITLE
nextcloud acme bot doesn't work 

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#59288]
## Issue description
The acme bot doesn't work with the nextcloud service . The reason is the nginx rule defined here:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/nextcloud.nix#L434
It denys access to all folders prefixed with a dot. And it is a rule that has a higher binding value even if it comes after the other rules because of the ~ ^ at the beginning of the rule.
You could fix the rule in nextcloud or make the default rule of the acme bot get prefixed with ~ ^ which I think is better.

**Comment by bachp** [comment]
@Luis-Hebendanz Is this still the case? Don't observe this issue on master anymore.
