### ISSUE TITLE
netdata temperature plugin broken

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#59287]
## Issue description

The temperature plugin is broken called: sensors
The reason is located in the first few lines of 

> libexec/netdata/python.d/python_modules/third_party/lm_sensors.py

to be exact here:

```from ctypes import *
import ctypes.util

_libc = cdll.LoadLibrary(ctypes.util.find_library("c"))
_libc.free.argtypes = [c_void_p]
_hdl = cdll.LoadLibrary(ctypes.util.find_library("sensors"))
```

It searches for the libc library and the sensors c library with ctypes which doesn't succeed.
The fix is to define an environment variable in the service called LD_LIBRARY_PATH that points to the needed library directories. For more information look here:
https://docs.python.org/3.7/library/ctypes.html#finding-shared-libraries

## Possible solution
Not tested but this could resolve the problem:
```
serviceConfig = {
Environment="LD_LIBRARY_PATH=${pkgs.lm_sensors}/lib:${pkgs.libgcc}/lib:$LD_LIBRARY_PATH";

};

```

**Comment by ldesgoui** [comment]
Looks like this issue is solved https://github.com/NixOS/nixpkgs/commit/df885360a6d30f1c2a30deb45bee4ed070f5cef3#diff-c080a3ec04b35f95254741800e1a3697

**Comment by oliverpool** [comment]
With the switch to the go plugin, the temperature is missing again.

I documented my workaround in a dedicated issue: #376795
