### ISSUE TITLE
sh: ps: command not found on darwin

### ISSUE THREAD

**Issue by sheeldotme** [NixOS/nixpkgs#59289]
## Issue description

`sh: ps: command not found` when using CMake derivation.  Possible regression of: https://github.com/NixOS/nixpkgs/issues/2561

### Steps to reproduce

`git clone https://github.com/sheeldotme/reproduction-nix-59289.git`
`cd reproduction-nix-59289`
`nix-build`

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(sheelpatel): `"nixpkgs-19.09pre174594.0c0954781e2"`
 - nixpkgs: `/Users/sheelpatel/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Don’t you just need to add darwin.ps to your buildInputs? It’s propagated by cmake if you use the normal stdenv.

**Comment by sheeldotme** [comment]
That seems to do the trick!  As cmake seems to rely on ps being available (or else it outputs that message) should it not be specified as an input to cmake?

**Comment by matthewbauer** [comment]
It is: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/cmake/default.nix#L63

But you need to use Nixpkgs stdenv for propagation to work.

**Comment by sheeldotme** [comment]
That makes sense, thanks for taking the time to explain!
