### ISSUE TITLE
remove -msse2 flag from haskell vector for current GHC head onwards

### ISSUE THREAD

**Issue by cartazio** [NixOS/nixpkgs#59291]
## Issue description
so currently in 
nixpkgs theres
```
/.nix-defexpr/channels/nixpkgs/pkgs/development/haskell-modules/configuration-common.nix:
  149    # sse2 flag due to https://github.com/haskell/vector/issues/47.
  150    # dontCheck due to https://github.com/haskell/vector/issues/138
  151:   vector = dontCheck (if pkgs.stdenv.isi686 then appendConfigureFlag super.vector "--ghc-options=-msse2" else super.vector);
  152  
```
a patch I wrote thats now in ghc master  as of today, https://gitlab.haskell.org/ghc/ghc/commit/42504f4a575395a35eec5c3fd7c9ef6e2b54e68e, 

removes x87 support from ghc, and thus on all intel platforms sse2 support is assumed! 

so future ghc releases and future nix snapshots of head neednt set the flag, because its always there already. (i did set it up so that it wont complain/error out if you still set the flag, but seems like good to remove over time). 

this is an FYI, because i'm not sure how one would rearrange the applicable nix code for this..

**Comment by cartazio** [comment]
@peti @ttuegel ?

**Comment by ttuegel** [comment]
We can probably proceed by moving that override into the compiler-specific overrides, so it would not be ported forward when GHC is released with that patch.

**Comment by cartazio** [comment]
Awesome.  It’s slated for 8.10 release https://gitlab.haskell.org/ghc/ghc/issues/8949

-Carter

________________________________

**Comment by FliegendeWurst** [comment]
This was done at some point.
