### ISSUE TITLE
No manpage for weechat

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#59300]
## Issue description

There is no manpage for weechat

### Steps to reproduce
`nix run nixpkgs.weechat -c man weechat`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.09.git.c141839 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(teto): `""`
 - channels(root): `""`
 - nixpkgs: `/home/teto/nixpkgs`
```

**Comment by Ma27** [comment]
The `weechat` expression itself contains a `man` output, however `pkgs.weechat` is a wrapper which doesn't load this. I'm not sure yet how to add the output to `buildEnv` (I assume we want segregated outputs here as well), but I'll probably provide a fix for this tomorrow.

A possible workaround for this is to install `weechat-unwrapped.man`.

**Comment by FRidh** [comment]
> I'm not sure yet how to add the output to buildEnv (I assume we want segregated outputs here as well)

This is a good one.  Currently, `buildEnv` links them in the same output `out` when using `extraOutputsToInstall`. I suppose that makes sense when installing an environment, but for wrappers not so much.

Note one could add the outputs to the `passthru` of the wrapper derivation.

**Comment by Ma27** [comment]
> This is a good one. Currently, buildEnv links them in the same output out when using extraOutputsToInstall. I suppose that makes sense when installing an environment, but for wrappers not so much.

That's more or less what I did in the end :)

See #59487 for the patch.

**Comment by teto** [comment]
thanks
