### ISSUE TITLE
Multipath TCP

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#59301]
## Issue description
This is a nice to have feature and would help give NixOS some credibility for high performance use cases: 

NixOS is missing from this list: https://multipath-tcp.org/pmwiki.php/Users/Distributions. 

The way to go would be to have a boolean NixOS module option with `multipath_tcp` in its name. After that works, some documentation could be written, and then it could be submitted to that website.

**Comment by teto** [comment]
actually I have a module I intended to propose a PR soonthat does just that:
 https://github.com/teto/nixpkgs/blob/nixos-unstable/nixos/modules/services/networking/mptcp/default.nix
I also have packaged mptcpanalyzer/mptcptrace/mptcpplot if you are interested.

**Comment by teto** [comment]
I have extracted this from my main branch, you might want to try it https://github.com/NixOS/nixpkgs/pull/59342

**Comment by teto** [comment]
it is of value.

**Comment by teto** [comment]
mptcp is in upstsream kernel . I've moved some other mptcp utilitis to this flake https://github.com/teto/mptcp-flake
