### ISSUE TITLE
[19.03] bluetoothd segfault

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#59329]
## Issue description
When turning on my bluetooth headset and connecting to it bluetoothd segfaults

```
[   16.327080] virbr0: port 1(virbr0-nic) entered listening state
[   16.352808] virbr0: port 1(virbr0-nic) entered disabled state
[   18.641488] Bluetooth: RFCOMM TTY layer initialized
[   18.641492] Bluetooth: RFCOMM socket layer initialized
[   18.641495] Bluetooth: RFCOMM ver 1.11
[   37.429935] NET: Registered protocol family 38
[   52.064692] Bluetooth: hci0: SCO packet for unknown connection handle 0
[   52.064697] Bluetooth: hci0: SCO packet for unknown connection handle 0
[   52.064698] Bluetooth: hci0: SCO packet for unknown connection handle 0
[   52.072769] show_signal_msg: 8 callbacks suppressed
[   52.072771] bluetoothd[1101]: segfault at 10 ip 000055c29171ab80 sp 00007fff73620ff8 error 4 in bluetoothd[55c29170e000+93000]
[   52.072776] Code: 08 00 48 89 c6 31 c0 e8 5e 73 02 00 44 8b 5c 24 0c e9 09 fe ff ff e8 af 43 ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 <4c> 8b 47 10 49 39 78 50 74 06 31 c0 c3 0f 1f 00 41 55 41 54 49 89
[   52.074690] Bluetooth: hci0: SCO packet for unknown connection handle 0
[   52.097381] Bluetooth: hci0: SCO packet for unknown connection handle 258
```

A few reboots and git bisect later I identified d28aedd77e32f0a0dfe420aebc7f059a13a04034 as the first bad commit

(for completeness sake my journey to the commit)
```
602c2b40e7c: good
2f980e45986: good
4fe8a27cfea: bad
de216e66fc8: good
608461e398f: good
db4bdf1fe4e: good
d28aedd77e3: bad
52c2e78aede: good
```

### Steps to reproduce
* boot laptop (Thinkpad X270)
* run `bluetoothctl`
* Execute command `connect 2C:41:A1:XX:XX:XX` (previosly paired headset)
* wait a moment
* see bluetoothd segfault in dmesg, pavucontrol showed new input and output devices for a short moment

I tried reverting d28aedd77e32f0a0dfe420aebc7f059a13a04034 but the problem persists. I am not sure if/how it is related. I made sure to check the last good and first bad commit identified by git-bisect multiple times and do not seem to have mistakenly identified the wrong commit.

## Technical details

Hardware: Thinkpad X270
Intel USB Bluetooth: Bus 001 Device 003: ID 8087:0a2b Intel Corp. 

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.git.ed07f05 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a, nixos1809-18.09.2505.46d3867a08a"`
 - channels(tristan.helmich): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

/cc @worldofpeace

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/commit/d28aedd77e32f0a0dfe420aebc7f059a13a04034 is only used for gala in Pantheon and their greeter.

So that's not even part of bluetoothd clousure, so I'm not sure what the problem is here.

**Comment by fadenb** [comment]
@worldofpeace I have absolutely no clue why but I can no longer reproduce the issue.
I tried it yesterday for hours but even the builds that segfaulted every single time (verified with the logs I saved) do no longer segfault.

Sorry to have pinged you on this prematurely. I am closing the issue until I encounter it again.

**Comment by worldofpeace** [comment]
> @worldofpeace I have absolutely no clue why but I can no longer reproduce the issue.
> I tried it yesterday for hours but even the builds that segfaulted every single time (verified with the logs I saved) do no longer segfault.
> 
> Sorry to have pinged you on this prematurely. I am closing the issue until I encounter it again.

Did you stop all the bluetooth services and then somehow run them manually to test?
That could have been why.

Though I've seen reports of segfaults for autoconnecting bluetooth headsets. So It could be an upstream issue if you're able to investigate further.
