### ISSUE TITLE
evil-escape lacks a package header

### ISSUE THREAD

**Issue by garry-cairns** [NixOS/nixpkgs#59348]
## Issue description

Builds with `evil-escape` built in to emacs will fail because the package lacks a header. The error message is as follows:

    Warning: (error "Package lacks a file header")
    installing
    Package lacks a file header
    builder for '/nix/store/vjb2bdgz6pa5yl53mag5a2xg2335sk78-emacs-evil-escape-20180910.534.drv' failed with exit code 255

### Steps to reproduce

Build a wrapped emacs in your configuration on 19.03 similar to [mine](https://gitlab.com/garry-cairns/nixos-config/blob/master/emacs.nix), which includes `evil-escape` in its melpa packages.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.111, NixOS, 19.03.172138.5c52b25283a (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a"`
 - channels(garry): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by nagy** [comment]
This has since been repaired.
