### ISSUE TITLE
nvidiaLegacy304: dead link (again)

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#59354]
## Issue description

The Debian archive containing the patches for the nvidiaLegacy304 package doesn't exist anymore.

```
trying http://httpredir.debian.org/debian/pool/non-free/n/nvidia-graphics-drivers-legacy-304xx/nvidia
-graphics-drivers-legacy-304xx_304.137-5.debian.tar.xz                                              
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                     
                                 Dload  Upload   Total   Spent    Left  Speed                       
100   407  100   407    0     0   8659      0 --:--:-- --:--:-- --:--:--  8847                      
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                      
curl: (22) The requested URL returned error: 404 Not Found
```

https://github.com/NixOS/nixpkgs/blob/928d51a9cbb3fee296da23fe297737147eb9bb05/pkgs/os-specific/linux/nvidia-x11/default.nix#L65-L66

The closest matching files are either `nvidia-graphics-drivers-legacy-304xx_304.137-5~bpo9+1.debian.tar.xz` or `nvidia-graphics-drivers-legacy-304xx_304.137-5~deb9u1.debian.tar.xz`.

I'm unable to compute the hashes for those file as the `nix-prefetch-url` command line tool returns an error:

```
nix-prefetch-url 'http://cdn-fastly.deb.debian.org/debian/pool/non-free/n/nvidia-graphics-drivers-legacy-304xx/nvidia-graphics-drivers-legacy-304xx_304.137-5~deb9u1.debian.tar.xz'
error: invalid character '~' in name 'nvidia-graphics-drivers-legacy-304xx_304.137-5~deb9u1.debian.tar.xz'
```

### Steps to reproduce

```
  services.xserver.videoDrivers = [ "nvidiaLegacy304" ];
  nixpkgs.config.allowBroken = true;
```

on NixOS 19.03.

## Technical details

NixOS 18.09 being upgraded to 19.03.

**Comment by veprbl** [comment]
cc @baracoder @eadwu

**Comment by eadwu** [comment]
The invalid character can be fixed by just passing a value to `--name` since the "basename" is invalid.

```
➜ nix-universal-prefetch fetchurl --url 'mirror://debian/pool/non-free/n/nvidia-graphics-drivers-legacy-304xx/nvidia-graphics-drivers-legacy-304xx_304.137-5~deb9u1.debian.tar.xz' --name test.debian.tar.xz
0wy135nfkqcygl16nljr335x3fp0r0qm7npx5ywbyy85lbwa62q6
```

**Comment by baracoder** [comment]
Sorry for my inactivity. I have created a branch https://github.com/baracoder/nixpkgs/tree/nvidia304patchfix
 which fixes the build ( `linuxPackages_4_14.nvidia_x11_legacy304` builds) but I can not test if it really works as my card is not compatible with this version.
Btw as I understand we are only interested in one patch from that archive, so would it make sense to copy the file over to nixpkgs?

**Comment by veprbl** [comment]
@baracoder Regarding your last question, it depends on how big is the patch. We would generally prefer to fetch it from somewhere. Also we probably are using quite a few other debian/ubuntu patches already. I wonder how do we solve the issue of link stability. Perhaps we download from archive.debian.org?

**Comment by pacien** [comment]
@baracoder wrote:
> I have created a branch https://github.com/baracoder/nixpkgs/tree/nvidia304patchfix
> which fixes the build ( `linuxPackages_4_14.nvidia_x11_legacy304` builds) but I can not test if it really works as my card is not compatible with this version.

Thanks for the patch.
I've rebased it on `19.03` and attempted a build, but it seems to fail.
Here's the build log: https://paste.gnugen.ch/raw/eTVL

**Comment by baracoder** [comment]
@pacien It looks like you are trying to build it for kernel 4.19.34 (Most probably the default one for 19.03)
It seams, the driver is marked as broken for kernels >= 4.18 for a reason
```
    broken = stdenv.lib.versionAtLeast kernel.version "4.18";
```
This steams still to apply even with the `-7` version of the patch, though there is something about improving kernel compatibility in the [changelog](https://metadata.ftp-master.debian.org/changelogs//non-free/n/nvidia-graphics-drivers-legacy-304xx/nvidia-graphics-drivers-legacy-304xx_304.137-7_changelog)

I have also found this bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925340 for Linux 5.0 kernel compatibility so we might be out of luck here.

**Comment by volth** [comment]
Any idea where to find the original `nvidia-graphics-drivers-legacy-304xx_304.137-5.debian.tar.xz` ?
Maybe inside old Debian .iso ?

**Comment by FliegendeWurst** [comment]
Driver version 304 was dropped in #122540
