### ISSUE TITLE
Environment variables and ~/.xsession regression on 19.03

### ISSUE THREAD

**Issue by jabranham** [NixOS/nixpkgs#59360]
## Issue description
After upgrading to 19.03, Emacs can't find `SSH_AUTH_SOCK` set by gpg-agent if started from `~/.xsession`.

In Emacs, M-x `getenv SSH_AUTH_SOCK` returns no match. However, in M-x shell, `printenv SSH_AUTH_SOCK` finds it. It's set properly in non-graphical shells too. However, processes started by Emacs (e.g. git) can't find the ssh agent.

This is a change/regression from 18.09.

### Steps to reproduce
```
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };
  services.xserver.enable = true;
```

~/.xsession:
```
exec emacs -q
M-x getenv SSH_AUTH_SOCK (no match)
M-x shell printenv SSH_AUTH_SOCK
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172138.5c52b25283a (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a"`
 - channels(alex): `"unstable-19.09pre174426.acbdaa569f4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Infinisil** [comment]
I think https://github.com/NixOS/nixpkgs/pull/56254 fixes this

**Comment by jabranham** [comment]
@Infinisil I'm not running Emacs as a daemon. And that PR is already contained in 19.03, right?

**Comment by Infinisil** [comment]
It is not, I haven't backported it (yet). Does that PR fix the problem for you?

**Comment by jabranham** [comment]
@Infinisil Yes, that appears to fix the issue. Thanks!

**Comment by Infinisil** [comment]
Alright, I backported the PR to 19.03 in https://github.com/NixOS/nixpkgs/commit/8bb9a8addaddf8d090e530cc31b28f2efd73f667 :)

**Comment by jabranham** [comment]
Thanks!
