### ISSUE TITLE
Installation on Docker image (derived from ubuntu:18.04) does not set NIX_PATH

### ISSUE THREAD

**Issue by michaelochurch** [NixOS/nixpkgs#59370]
## Issue description

Version is 2.2.1. It's in a docker container derived from `ubuntu:18.04`.

I can't run a number of the nix-related calls (e.g. `nix-env` to install Obsidian's obelisk project) because `$NIX_PATH` is not properly set. I don't know what it's supposed to be set to, and I believe other things are not being properly set up by the installation script. 

### Steps to reproduce

Installation is from source, because other modes of installation ran in to the same problem. I run `bootstrap.sh` (even though I believe it's not needed), then `./configure`, then `make` and `make install`. 

## Technical details

```
root@b99e6c4f2829:/nix-2.2.1# nix-shell -p nix-info --run "nix-info -m"
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
```

**Comment by FRidh** [comment]
For issues with or questions about Nix, please go to the Nix issue tracker. This tracker is for the Nixpkgs package set.

**Comment by Anton-Latukha** [comment]
You need to re-login the shell or source:
```shell
. nix-profile
```
See:
https://github.com/NixOS/nix/blob/master/scripts/nix-profile.sh.in

So much for Docker.

I covered some of Docker issues in https://youtu.be/hhgrCV_r7YE?t=7162.

It is a Nix installer thing, I'd had supported it, covered all these reports, if my PR of new installer was merged https://github.com/NixOS/nix/pull/1565

**Comment by Anton-Latukha** [comment]
But you would need to do `. nix-profile` anyway.
Because I just improved the quality of the installer more and more until it become a rewrite. I not added very much functionality there beyond better it's robustness, for the purpose to be drop-in mergeable.

**Comment by Anton-Latukha** [comment]
If you serious - you can patch upstream with my code.

Or look through the code to understand the problems, it is very well structured and documented inside.
