### ISSUE TITLE
Can't move windows using KDE with nvidiaLegacy390 on 19.03

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#59403]
## Issue description

I'm using `nvidiaLegacy390` because my video card isn't supported by the current NVIDIA driver, and using KDE I can't seem to move my windows.

### Steps to reproduce

1. Use `nvidiaLegacy390`.
2. Use KDE.

## Technical details

(Can't open a browser on the machine in question)

**Comment by vaibhavsagar** [comment]
I moved `~/.kde` out of the way and that didn't seem to change anything.

**Comment by vaibhavsagar** [comment]
Hmm, I removed all NVIDIA-specific configuration from my `configuration.nix` and I'm still experiencing the same issue with resizing, could it be something else?

**Comment by worldofpeace** [comment]
> Hmm, I removed all NVIDIA-specific configuration from my `configuration.nix` and I'm still experiencing the same issue with resizing, could it be something else?

I don't know what it is with plasma and nixos sometimes, but maybe try moving out like all of your dotfiles?
(.cache .local etc.)

**Comment by vaibhavsagar** [comment]
I tried again after removing `.cache` and `. local`, same results.

**Comment by vaibhavsagar** [comment]
I think this was something in `.config`, I deleted that directory and things seem to work again.
