### ISSUE TITLE
llvmGeneral links against the wrong llvm

### ISSUE THREAD

**Issue by tel** [NixOS/nixpkgs#5945]
Right now the most up-to-date released llvm-general package links against llvm-3.4, but as nixpkgs' default llvm is llvm-3.5 it can't build. Changing line [1641](https://github.com/NixOS/nixpkgs/blob/b96edd41a51491317e5522967b1d353dff57d2e5/pkgs/top-level/haskell-packages.nix#L1641) 

    -llvmGeneral = callPackage ../development/libraries/haskell/llvm-general { llvmConfig = pkgs.llvm; };
    +llvmGeneral = callPackage ../development/libraries/haskell/llvm-general { llvmConfig = pkgs.llvmPackages_34.llvm; };

is all that's required to patch it until the llvm-general package catches up to llvm-3.5.

**Comment by vcunat** [comment]
On nixpkgs master I can only see llvm-3.4 (and 3.3). AFAIK 3.5 is still only in the darwin WIP (outside official repo).

**Comment by tel** [comment]
Ah, that's where I picked it up. Sorry for the confusion.
