### ISSUE TITLE
systemd: system units picked up from user path and user units picked up from system path

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#59473]
## Issue description

There seems to be a bug in the following commit: https://github.com/NixOS/systemd/blob/9e238521511993f5f766310e8d00894b2fe08ce0/src/core/systemd.pc.in#L18-L19

It adds `/nix/var/nix/profiles/default/lib/systemd/user` to the `system` path and `/nix/var/nix/profiles/default/lib/systemd/system` to the `user` path whilst it needs to be the other way around.

Do we even use `/nix/var/nix/profiles/default/lib/systemd` anywhere? Considering this bug has been present for at least 5 years.

Wondering if we can drop this patch entirely. Everything is in `/etc/systemd/system` these days through `environment.etc` if I recall correctly.

cc @Mic92 @flokli

**Comment by flokli** [comment]
Something to consider while preparing the next systemd version bump: https://github.com/NixOS/nixpkgs/pull/56184

**Comment by arianvp** [comment]
After further inspection, this file seems purely informational and is actually not consulted anywhere in the rest of the systemd source code I think...  The patch that introduced the change _does_ do the ordering correctly in the systemd source code.  but still doesn't hurt to flip them around =)

**Comment by flokli** [comment]
`systemd.pc.in` will result in `${pkgs.systemd.dev}/share/pkgconfig/systemd.pc`, which will be added to `PKG_CONFIG_PATH` by `pkgs/development/tools/misc/pkg-config/setup-hook.sh`, so available in other build processes that query pkgconfig for these paths:

```
$ pkg-config --variable systemduserunitpath systemd 
/etc/systemd/user:/etc/systemd/user:/etc/systemd-mutable/user:/nix/var/nix/profiles/default/lib/systemd/system:/run/systemd/user:/nix/store/5wfca03x78xsxpnf0hcsyqln852pibm2-systemd-239.20190219/lib/systemd/user

$ pkg-config --print-variables systemd 
binfmtdir
catalogdir
containeruidbasemax
containeruidbasemin
dynamicuidmax
dynamicuidmin
modulesloaddir
pcfiledir
prefix
sysctldir
systemdshutdowndir
systemdsleepdir
systemdsystemconfdir
systemdsystemgeneratordir
systemdsystempresetdir
systemdsystemunitdir
systemdsystemunitpath
systemduserconfdir
systemdusergeneratordir
systemduserpresetdir
systemduserunitdir
systemduserunitpath
systemdutildir
systemgidmax
systemuidmax
sysusersdir
tmpfilesdir
```

**Comment by flokli** [comment]
I opened a PR at https://github.com/NixOS/nixpkgs/pull/89441 fixing the paths in the `systemd.pc` file.

`pkgs/os-specific/linux/systemd/0005-Add-some-NixOS-specific-unit-directories.patch` already documents why we currently want to look in these paths.
