### ISSUE TITLE
Cross compilation regression due to CC and CXX being set

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#5949]
It seems that commit 28b6fb61e651a3e2cca57d087781e7ba6ab45e7c broke cross compilation for the majority of packages, by setting CC and CXX to native compilers. In particular I'm getting an error in bash. It doesn't matter what the error is but it is clear that it's not using the right compiler from the configure output:

```
configure flags: --disable-static --prefix=/nix/store/jqpxcv13araqrsv54rwsq2qxg763qlfy-bash-4.3-p30-armv6l-unknown-linux-gnueabi --disable-readline bash_cv_job_control_missing=nomissing bash_cv_sys_named_pipes=nomissing --build=x86_64-linux --host=armv6l-unknown-linux-gnueabi 
configure: WARNING: unrecognized options: --disable-static
checking build system type... x86_64-pc-linux-gnu
checking host system type... armv6l-unknown-linux-gnueabi

Beginning configuration for bash-4.3-release for armv6l-unknown-linux-gnueabi

checking for armv6l-unknown-linux-gnueabi-gcc... cc
checking whether the C compiler works... yes
```

The problematic change is in `pkgs/build-support/gcc-wrapper/setup-hook.sh` where CC and CXX environment variables are assigned.

Note: there are other issues currently in nixpgks that are preventing actually testing this one.

**Comment by viric** [comment]
@shlevy why was export CC & CXX required?

**Comment by shlevy** [comment]
@viric I'm not sure, pinging the people who have been doing the work in this area ( @joelteon @jwiegley @copumpkin @gridaphobe @edolstra )

@ambrop72 assuming these variables have to be set (and I don't know if they do), what should they be set to in the cross-compilation case? Note that staging has https://github.com/NixOS/nixpkgs/commit/7dc57a389e3d3eb5b5e8de3b02dfe469496fad1a , so we can refine this logic further if needed.

**Comment by shlevy** [comment]
@ambrop72 Also, please check against staging, as perhaps `CC=gcc` will be enough (as opposed to `CC=cc`)

**Comment by ambrop72** [comment]
The code in staging seems OK to me *for non-cross builds*. For cross builds it is incorrect to set CC/CXX to native-compilers, because configure-scripts usually understand them as cross-compilers. In the cross-compile scenario, I think that it is most common to see BUILD_CC/BUILD_CXX used as native-compilers. So, I would do this:

- In cc/gcc-wrapper setup-hook.sh, make the CC/CXX export conditional under `if [ -z "$crossConfig" ]`, and in the else case, set BUILD_CC/BUILD_CXX instead.
- In cross-gcc-wrapper setup-hook.sh, export CC/CXX to cross-compilers:
```
export CC=${crossConfig}-gcc
export CXX=${crossConfig}-g++
```

**Comment by viric** [comment]
Cross compiling, the native and cross compilers usually have to coexist. That's
why I asked why setting CC/CXX started to be required.

What was the problem solved by setting CC/CXX?

**Comment by copumpkin** [comment]
@viric, as far as I know, the main thing is that many builds assume CC=gcc
unless told otherwise. Given that clang isn't gcc and doesn't have a script
called gcc, that's problematic when we have a clang stdenv. Less
importantly, there's also the fact that a whole bunch of packages store
their CC value in their $out directory under *-config scripts that will
tell you what the package was built with. If you leave CC unset in these
cases, the configure script finds an absolute path to the compiler and then
retains a runtime dependency on it due to the script.

There might be other reasons to set it, but that's what comes to mind.

**Comment by gridaphobe** [comment]
As @copumpkin says, the issue is that CC is often assumed to be gcc unless we specify otherwise. This causes major issues for the upcoming darwin-clang stdenv. 

Conditionally setting CC in the setup-hook seems like a reasonable solution to me.

**Comment by ambrop72** [comment]
This patch seems to have fixed the issue that I was getting. Note that I here don't set BUILD_CC as  suggested since testing that would need even longer.

```
diff --git a/pkgs/build-support/gcc-cross-wrapper/setup-hook.sh b/pkgs/build-support/gcc-cross-wrapper/setup-hook.sh
index ce5f6e5..599954b 100644
--- a/pkgs/build-support/gcc-cross-wrapper/setup-hook.sh
+++ b/pkgs/build-support/gcc-cross-wrapper/setup-hook.sh
@@ -85,3 +85,6 @@ if test "$NIX_NO_SELF_RPATH" != "1"; then
         export NIX_CROSS_LDFLAGS="-rpath $out/lib64 -rpath-link $out/lib $NIX_CROSS_LDFLAGS"
     fi
 fi
+
+export CC=${crossConfig}-gcc
+export CXX=${crossConfig}-g++
diff --git a/pkgs/build-support/gcc-wrapper/setup-hook.sh b/pkgs/build-support/gcc-wrapper/setup-hook.sh
index f0034fe..b6552dc 100644
--- a/pkgs/build-support/gcc-wrapper/setup-hook.sh
+++ b/pkgs/build-support/gcc-wrapper/setup-hook.sh
@@ -34,5 +34,7 @@ if [ -n "@coreutils@" ]; then
     addToSearchPath PATH @coreutils@/bin
 fi
 
-export CC=cc
-export CXX=c++
+if [ -z "$crossConfig" ]; then
+    export CC=cc
+    export CXX=c++
+fi
```

**Comment by copumpkin** [comment]
I don't know much about cross-compilation in nix (that should probably change) but is it regularly tested as part of hydra builds? if not, it probably should be, to prevent things like this from happening again.
