### ISSUE TITLE
home-assistant: generated config file is invalid

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#59526]
## Issue description

On nixos-unstable if you use the services.home-assistant.config value and set it to something like:

```
config = { };
frontend = { };
```

You used to get (and should still get) the following in the config file:

```
config:
frontend:
```

Instead you now get:

```
config: {}
frontend: {}
```

Home-assistant seems to tolerate this (for now) but it's something we should probably fix to generate valid syntax.

### Steps to reproduce

1.) Install home-assistant
2.) Use the option services.home-assistant.config and try to create an entry like "frontend:" without any characters following it.

## Technical details

```
[root@server:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.6, NixOS, 19.09pre174426.acbdaa569f4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre174426.acbdaa569f4, nixos-small-19.09pre175334.bbe83c05205"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment]
cc  maintainer @dotlambda

**Comment by dotlambda** [comment]
This is valid YAML and will always work fine.
