### ISSUE TITLE
Nvidia driver fails to build on linux kernels greater than 4.19

### ISSUE THREAD

**Issue by josephsdavid** [NixOS/nixpkgs#59529]
## Issue description

The Nvidia driver does not build with the lates linux kernel. It does build with kernel 4.19

### Steps to reproduce

In configuration.nix:

```nix
{ config, pkgs, ... }:
{
imports = [
  ./hardware-configuration.nix
  ];

boot.kernelPackages = pkgs.linuxPackages_latest;
services.xserver.videoDrivers = [ "nvidia" ];
system.stateVersion = "19.03";
}
```
## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172138.5c52b25283a (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a, nixpkgs-19.09pre174594.0c0954781e2"`
 - channels(david): `"home-manager, nixpkgs-19.09pre174594.0c0954781e2"`
 - nixpkgs: `/home/david/.nix-defexpr/channels/nixpkgs`

**Comment by eadwu** [comment]
Looks like #57062.

**Comment by josephsdavid** [comment]
Hey it worked! just switching to small and then switch --upgrade did it for me! Thank you!
