### ISSUE TITLE
Hardcoded user and group in openldap.nix

### ISSUE THREAD

**Issue by baccenfutter** [NixOS/nixpkgs#5955]
While studying openldap.nix I stumbled across what appears to be a bug:

https://github.com/NixOS/nixpkgs/blob/release-14.12/nixos/modules/services/databases/openldap.nix#L66

Same goes for lines 70 and 76.

If it is a bug, it was introduced by: https://github.com/NixOS/nixpkgs/commit/cb691265b65bd207741dc2798ff3cc911ff01437

**Comment by offlinehacker** [comment]
Can you explain this a little bit more. What's wrong with running openldap under openldap user and group?

**Comment by offlinehacker** [comment]
Ok, I can see it now. User and group parameter are non affective.

**Comment by robberer** [comment]
@baccenfutter 

Did you gave #5982 a try. Does that PR solve this issue for you ?

**Comment by baccenfutter** [comment]
Solved by #5982
