### ISSUE TITLE
bitcoin-0.9.3 fails on test suite (release-14.12)

### ISSUE THREAD

**Issue by sfultong** [NixOS/nixpkgs#5957]
Running 115 test cases...
transaction_tests.cpp(91): error in "tx_valid": [[["60a20bd93aa49ab4b28d514ec10b06e1829ce6818ec06cd3aabd013ebcdc4bb1",0,"1 0x41 0x04cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaff7d8a473e7e2e6d317b87bafe8bde97e3cf8f065dec022b51d11fcdd0d348ac4 0x41 0x0461cbdcc5409fb4b4d42b51d33381354d80e550078cb532a34bfa2fcfdeb7d76519aecc62770f5b0e4ef8551946d8a540911abe3e7854a26f39f58b25c15342af 2 OP_CHECKMULTISIG"]],"0100000001b14bdcbc3e01bdaad36cc08e81e69c82e1060bc14e518db2b49aa43ad90ba26000000000490047304402203f16c6f40162ab686621ef3000b04e75418a0c0cb2d8aebeac894ae360ac1e780220ddc15ecdfc3507ac48e1681a33eb60996631bf6bf5bc0a0682c4db743ce7ca2b01ffffffff0140420f00000000001976a914660d4ef3a743e3e696ad990364e555c271ad504b88ac00000000",true]
transaction_tests.cpp(91): error in "tx_valid": [[["60a20bd93aa49ab4b28d514ec10b06e1829ce6818ec06cd3aabd013ebcdc4bb1",0,"1 0x41 0x04cc71eb30d653c0c3163990c47b976f3fb3f37cccdcbedb169a1dfef58bbfbfaff7d8a473e7e2e6d317b87bafe8bde97e3cf8f065dec022b51d11fcdd0d348ac4 0x41 0x0461cbdcc5409fb4b4d42b51d33381354d80e550078cb532a34bfa2fcfdeb7d76519aecc62770f5b0e4ef8551946d8a540911abe3e7854a26f39f58b25c15342af 2 OP_CHECKMULTISIG"]],"0100000001b14bdcbc3e01bdaad36cc08e81e69c82e1060bc14e518db2b49aa43ad90ba260000000004A0048304402203f16c6f40162ab686621ef3000b04e75418a0c0cb2d8aebeac894ae360ac1e780220ddc15ecdfc3507ac48e1681a33eb60996631bf6bf5bc0a0682c4db743ce7ca2bab01ffffffff0140420f00000000001976a914660d4ef3a743e3e696ad990364e555c271ad504b88ac00000000",true]
transaction_tests.cpp(91): error in "tx_valid": [[["b464e85df2a238416f8bdae11d120add610380ea07f4ef19c5f9dfd472f96c3d",0,"DUP HASH160 0x14 0xbef80ecf3a44500fda1bc92176e442891662aed2 EQUALVERIFY CHECKSIG"],["b7978cc96e59a8b13e0865d3f95657561a7f725be952438637475920bac9eb21",1,"DUP HASH160 0x14 0xbef80ecf3a44500fda1bc92176e442891662aed2 EQUALVERIFY CHECKSIG"]],"01000000023d6cf972d4dff9c519eff407ea800361dd0a121de1da8b6f4138a2f25de864b4000000008a4730440220ffda47bfc776bcd269da4832626ac332adfca6dd835e8ecd83cd1ebe7d709b0e022049cffa1cdc102a0b56e0e04913606c70af702a1149dc3b305ab9439288fee090014104266abb36d66eb4218a6dd31f09bb92cf3cfa803c7ea72c1fc80a50f919273e613f895b855fb7465ccbc8919ad1bd4a306c783f22cd3227327694c4fa4c1c439affffffff21ebc9ba20594737864352e95b727f1a565756f9d365083eb1a8596ec98c97b7010000008a4730440220503ff10e9f1e0de731407a4a245531c9ff17676eda461f8ceeb8c06049fa2c810220c008ac34694510298fa60b3f000df01caa244f165b727d4896eb84f81e46bcc4014104266abb36d66eb4218a6dd31f09bb92cf3cfa803c7ea72c1fc80a50f919273e613f895b855fb7465ccbc8919ad1bd4a306c783f22cd3227327694c4fa4c1c439affffffff01f0da5200000000001976a914857ccd42dded6df32949d4646dfa10a92458cfaa88ac00000000",true]
transaction_tests.cpp(91): error in "tx_valid": [[["b464e85df2a238416f8bdae11d120add610380ea07f4ef19c5f9dfd472f96c3d",0,"DUP HASH160 0x14 0xbef80ecf3a44500fda1bc92176e442891662aed2 EQUALVERIFY CHECKSIG"],["b7978cc96e59a8b13e0865d3f95657561a7f725be952438637475920bac9eb21",1,"DUP HASH160 0x14 0xbef80ecf3a44500fda1bc92176e442891662aed2 EQUALVERIFY CHECKSIG"]],"01000000023d6cf972d4dff9c519eff407ea800361dd0a121de1da8b6f4138a2f25de864b4000000008a4730440220ffda47bfc776bcd269da4832626ac332adfca6dd835e8ecd83cd1ebe7d709b0e022049cffa1cdc102a0b56e0e04913606c70af702a1149dc3b305ab9439288fee090014104266abb36d66eb4218a6dd31f09bb92cf3cfa803c7ea72c1fc80a50f919273e613f895b855fb7465ccbc8919ad1bd4a306c783f22cd3227327694c4fa4c1c439affffffff21ebc9ba20594737864352e95b727f1a565756f9d365083eb1a8596ec98c97b7010000008a4730440220503ff10e9f1e0de731407a4a245531c9ff17676eda461f8ceeb8c06049fa2c810220c008ac34694510298fa60b3f000df01caa244f165b727d4896eb84f81e46bcc4014104266abb36d66eb4218a6dd31f09bb92cf3cfa803c7ea72c1fc80a50f919273e613f895b855fb7465ccbc8919ad1bd4a306c783f22cd3227327694c4fa4c1c439affffffff01f0da5200000000001976a914857ccd42dded6df32949d4646dfa10a92458cfaa88ac00000000",true]

*** 4 failures detected in test suite "Bitcoin Test Suite"

**Comment by copumpkin** [comment]
Paging @roconnor

**Comment by falsifian** [comment]
https://github.com/NixOS/nixpkgs/pull/5694 is probably related.

**Comment by falsifian** [comment]
NB: If it is #5694, then disabling tests is *not* a good solution, as it could fork the blockchain. (Not that anyone has suggested it.)

**Comment by roconnor** [comment]
I'll try to prepare a patch that will build bitcoin against OpenSSL 1.0.1j.

**Comment by roconnor** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/af3c4a2744bf1b9adc1c2ff56fe7f8266ddb4192

**Comment by sfultong** [comment]
Thanks @roconnor $2 @ChangeTip

**Comment by changetip** [comment]
Hi @roconnor, @sfultong sent you a Bitcoin tip worth 9,094 bits ($2.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/434540)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by roconnor** [comment]
Although I appreciate the sentiment behind your tip, I'm afraid I'm not authorized to accept it.  If you have a way of reversing the transaction, I suggest you do so.

**Comment by sfultong** [comment]
Very well. Are you paid to work on nixos?

**Comment by roconnor** [comment]
My employer lets me work 20% of my time on NixOS.
