### ISSUE TITLE
Can't detect kit when create new qtquickapplication

### ISSUE THREAD

**Issue by LinArcX** [NixOS/nixpkgs#59582]
## Issue description
I can create console and widget based applications in qt creator(actually it can detect kit successfully), but if i want to choose qtquickapplication,there is no kit to selection:

https://raw.githubusercontent.com/LinArcX/Ganje/master/Images/LinArcx/Screenshot%20from%202019-04-15%2013-26-39.png

Also in Qt Versions tab, i have one warning:
> abi detection failed make sure to use a matching compiler when building

https://raw.githubusercontent.com/LinArcX/Ganje/master/Images/LinArcx/Screenshot%20from%202019-04-16%2011-54-50.png

### Steps to reproduce

install direnv and create shell.nix in the root of your project and paste these lines into it:
```
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    buildInputs = [
                    pkgs.qt5.full
                    pkgs.gcc
                    pkgs.qt5.qtquickcontrols2
                    pkgs.qt5.qtquickcontrols
                    pkgs.qtcreator
                    pkgs.qt5.qtdoc
                    pkgs.clang-analyzer
                    pkgs.clang-tools
                  ];
}
```
and then run qtcretor.

Also i tested it with nix-shell with same behavior:

nix-shell -p qt5Full -p qtcreator --run qtcreator

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.33, NixOS, 19.09pre174426.acbdaa569f4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre174426.acbdaa569f4"`
 - channels(linarcx): `"nixos-19.09pre174426.acbdaa569f4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by LinArcX** [comment]
Up!
I want to help to fix these kinds of issues, but i don't know how/where to start.
If anybody that know how qt works in nixos, it will be good to get me some advise to fix these issues.

**Comment by bitmappergit** [comment]
I am also experiencing this issue.

**Comment by LinArcX** [comment]
I update my system today and this issue disappeared and i can find kits for qt-quickapplications too. but that warning still exist. So i close this issue. it fixed for me. anyone that encounter this issue feel free to re-open it.

**Comment by VergeDX** [comment]
I'm building [lirios/fluid](https://github.com/lirios/fluid) and meet the same issues...
