### ISSUE TITLE
Openldap service not starting with extraConfig options

### ISSUE THREAD

**Issue by baccenfutter** [NixOS/nixpkgs#5960]
There seems to be even more wrong with openldap as mentioned in #5955

When I declare openldap as follows:
```
    services.openldap.extraConfig = ''
      include ${pkgs.openldap}/etc/openldap/schema/core.schema
      include ${pkgs.openldap}/etc/openldap/schema/cosine.schema
      include ${pkgs.openldap}/etc/openldap/schema/nis.schema
      include ${pkgs.openldap}/etc/openldap/schema/inetorgperson.schema
      pidfile ${pkgs.openldap}/var/run/slapd.pid
      argsfile ${pkgs.openldap}/var/run/slapd.args
      database    bdb
      suffix      "dc=domain,dc=tld"
      rootdn      "cn=root,dc=domain,dc=tld"
      rootpw      secret
      directory   ${pkgs.openldap}/var/openldap-data
      index       objectClass eq
    '';
```
The service won't start due to:

    /nix/store/2qv4s7jvnfm6rvanijf09bqd8c5h6d2n-slapd.conf: line 11: invalid path: Read-only file system

Shouldn't the slapd.conf be linked to /etc? It is not.

**Comment by iElectric** [comment]
Set `directory` to something else: `directory /var/run/slapd`

**Comment by baccenfutter** [comment]
Still not working:

    ● openldap.service - LDAP server
       Loaded: loaded (/nix/store/c36x701z167axr3p4v8cqgj0fgcg0gph-unit-openldap.service/openldap.service)
       Active: failed (Result: exit-code) since Sun 2015-01-25 21:49:38 CET; 1min 57s ago
      Process: 3826 ExecStart=/nix/store/zvd9hjw3b4s6y89522czlnhq07xydgby-openldap-2.4.40/libexec/slapd -u openldap -g openldap -d 0 -f /nix/store/hppj54nm26f2q7lv0x1j55k9mm3mfgmn-slapd.conf (code=exited, status=1/FAILURE)
      Process: 3809 ExecStartPre=/nix/store/a2r34lnfz8izdl573yc6gsmc7w7g2w9g-unit-script/bin/openldap-pre-start (code=exited, status=0/SUCCESS)
     Main PID: 3826 (code=exited, status=1/FAILURE)
    
    Jan 25 21:49:38 openmailbox systemd[1]: Started LDAP server.
    Jan 25 21:49:38 openmailbox slapd[3826]: @(#) $OpenLDAP: slapd 2.4.40 (Jan 01 1970 00:00:01) $
                                                     @localhost:/tmp/nix-build-openldap-2.4.40.drv-0/openldap-2.4.40/servers/slapd
    Jan 25 21:49:38 openmailbox slapd[3826]: /nix/store/hppj54nm26f2q7lv0x1j55k9mm3mfgmn-slapd.conf: line 11: invalid path: No such file or directory
    Jan 25 21:49:38 openmailbox slapd[3826]: DIGEST-MD5 common mech free
    Jan 25 21:49:38 openmailbox slapd[3826]: slapd stopped.
    Jan 25 21:49:38 openmailbox slapd[3826]: connections_destroy: nothing to destroy.
    Jan 25 21:49:38 openmailbox systemd[1]: openldap.service: main process exited, code=exited, status=1/FAILURE
    Jan 25 21:49:38 openmailbox systemd[1]: Unit openldap.service entered failed state.
    Jan 25 21:49:38 openmailbox systemd[1]: openldap.service failed.

**Comment by robberer** [comment]
`invalid path: No such file or directory`

I guess you have to create this directory with proper permissions. And yeah, I wouldn't use /var/run for databases.  ;-)

**Comment by robberer** [comment]
Hmm, looking at the module I would suggest using `directory /var/db/openldap`. This directory is automatically created by systemd service and gets the right permissions.
