### ISSUE TITLE
nixos services.restya-board: restya-board-init.service failure

### ISSUE THREAD

**Issue by gbiscuolo** [NixOS/nixpkgs#59636]
## Issue description

`restya-board-init.service` fails when installing service.restya-board using a custom `database.name` option; this is the service status:

```
[root@SWboard:~]# sudo systemctl status restya-board-init.service
● restya-board-init.service - Restya board initialization
   Loaded: loaded (/nix/store/bn4ljg4bn631ly2ii5vni3qckl7zwg0r-unit-restya-board-init.service/restya-board-init.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-04-15 20:17:01 UTC; 6s ago
  Process: 3561 ExecStart=/nix/store/yzid87chgwsswjlc5q4rvwmmvk9qhlnh-unit-script-restya-board-init-start (code=exited, status=2)
 Main PID: 3561 (code=exited, status=2)

Apr 15 20:16:54 SWboard sudo[3591]:     root : TTY=unknown ; PWD=/ ; USER=postgres ; COMMAND=/nix/store/igsfm3nkiqf0wgrhvi49mgmfc7n1290x-postgresql-9.6.12/bin/psql -U postgres -c CREATE DATABAS>
Apr 15 20:16:54 SWboard sudo[3591]: pam_unix(sudo:session): session opened for user postgres by (uid=0)
Apr 15 20:17:01 SWboard yzid87chgwsswjlc5q4rvwmmvk9qhlnh-unit-script-restya-board-init-start[3561]: CREATE DATABASE
Apr 15 20:17:01 SWboard sudo[3594]:     root : TTY=unknown ; PWD=/ ; USER=restya-board ; COMMAND=/nix/store/igsfm3nkiqf0wgrhvi49mgmfc7n1290x-postgresql-9.6.12/bin/psql -U restya_board -d restya>
Apr 15 20:17:01 SWboard sudo[3594]: pam_unix(sudo:session): session opened for user restya-board by (uid=0)
Apr 15 20:17:01 SWboard yzid87chgwsswjlc5q4rvwmmvk9qhlnh-unit-script-restya-board-init-start[3561]: psql: FATAL:  Peer authentication failed for user "restya_board"
Apr 15 20:17:01 SWboard sudo[3594]: pam_unix(sudo:session): session closed for user restya-board
Apr 15 20:17:01 SWboard systemd[1]: restya-board-init.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 15 20:17:01 SWboard systemd[1]: restya-board-init.service: Failed with result 'exit-code'.
Apr 15 20:17:01 SWboard systemd[1]: Failed to start Restya board initialization.
```

The issue is caused by the hardcoded database name in [`postgres.authentication` definition](https://github.com/NixOS/nixpkgs/blob/fd05e3407ea1acea58b73e3a699ba35375343e65/nixos/modules/services/web-apps/restya-board.nix#L379): the database name should be ` ${cfg.database.name}`.

I have not tested it directly but looking at the module source code I'm almost sure this also applies to  `database.user` and `user` options.

### Steps to reproduce

Use this service declaration:

```
  services.restya-board = {
       enable = true;
       virtualHost.listenHost = "192.168.200.13";
       virtualHost.serverName = "xtboard.MASKED.TLD";
       database.name = "restya_xtboard";
       timezone = "CET";
  };
```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/9z1b1ldrhxh7brsi6fxnyjm7gk8kiynv-bash-interactive-4.4-p23-dev
copying path '/nix/store/9z1b1ldrhxh7brsi6fxnyjm7gk8kiynv-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.03.172138.5c52b25283a (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aanderse** [comment]
@gbiscuolo thanks for reporting this. I've never used this service, but I would be willing to take a look and fix this if you were willing to test it for me. Sound good?

**Comment by gbiscuolo** [comment]
Hello Aaron,

Aaron Andersen <notifications@github.com> writes:

> @gbiscuolo thanks for reporting this. I've never used this service,
> but I would be willing to take a look and fix this if you were willing
> to test it for me. Sound good?

yes! thank you for your offer

In the next couple of weeks I'll be pretty busy, but I should be able to
test later on

I'd also like to learn how to test local defined (i.e. in a git branch)
changes to the packages/services: do you have a pointer to the relevant
documentation please, just a pointer: I'll do my homework :-)

Thanks! Gio'

[...]

-- 
Giovanni Biscuolo

Xelera IT Infrastructures

**Comment by aanderse** [comment]
@gbiscuolo I've found a few issues. The `restya-board` package in nixpkgs hasn't been updated in over 2 years. It also looks like the module author has likely moved on, so the module hasn't seen any support or maintenance in the last 2 years either.

Generally at this point if no one is willing to take over maintenance of at least the package we would want to remove this from nixpkgs because this is a web application and we shouldn't have users thinking they are using something up to date and secure when it is actually lagging 7 releases (2 years) behind upstream.

That being said I really don't enjoy removing software from nixpkgs that people are using, or want to use... If you're really keen on using this software on NixOS I suggest we look for a new package/module maintainer. **Please let me know if you want to pursue this.**
