### ISSUE TITLE
qsynth broken in 19.03

### ISSUE THREAD

**Issue by SmilingHorse** [NixOS/nixpkgs#59672]
@magnetophon 
hydra seems to be trying to compile the older version so I'm guessing your recent 0.5.5 update wasn't merged/back-ported to stable properly/yet?
https://hydra.nixos.org/job/nixos/release-19.03/nixpkgs.qsynth.x86_64-linux

btw, 0.5.6 was released a few days ago too.

p.s. to clarify, unstable is fine.

**Comment by magnetophon** [comment]
@SmilingHorse Thanks for the heads up!
@worldofpeace Thanks for the solution!

**Comment by SmilingHorse** [comment]
Closing the issues in advance.

Thanks everyone.
