### ISSUE TITLE
nano/nix highlighting barely legible under solarized light

### ISSUE THREAD

**Issue by goertzenator** [NixOS/nixpkgs#59721]
## Issue description
Nix syntax highlighting in nano in a solarized light terminal has some barely legible colors (light gray)
Screenshot:
![image](https://user-images.githubusercontent.com/605072/56221128-46db0900-602f-11e9-9d36-ebcff5c36dc9.png)

There was no nix syntax highlighting prior to 19.03.

### Steps to reproduce
1. Install nixos 19.03.
2. Install Konsole.
3. Set color scheme to Solarized Light.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172138.5c52b25283a (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a, unstable-19.03pre164964.b0f40b78513"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
I've had this same problem with light color themes in NixOS.
It it isn't limited to just nano, it was anything that had colors.
(think bat's hightlighting as well)

**Comment by worldofpeace** [comment]
Hmm, after inspection I think it's just `.nix` files.

**Comment by aanderse** [comment]
Is this a nix issue or an upstream issue? You could install a different nano colour scheme: https://github.com/scopatz/nanorc

**Comment by pschuprikov** [comment]
@goertzenator you might want to file the issue against https://github.com/seitz/nanonix, which is the source repo for [nano nix highlighting](https://github.com/seitz/nixpkgs/blob/9b30f324783f7e9daab717133fe8d6838c4e575c/pkgs/applications/editors/nano/default.nix#L14-L19)

**Comment by aanderse** [comment]
Upstream issue.
