### ISSUE TITLE
VSCode: No such file or directory with User Env

### ISSUE THREAD

**Issue by maxkrieger** [NixOS/nixpkgs#59725]
## Issue description

I have the latest version of VSCode installed (`nixpkgs` channel). I tried running `code` in my shells (zsh, bash, sh) and all of them failed with this error:

```
$ ~/ code
-f: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
/nix/store/nhfb7dsg4h010nqh7a64cd3v96yvjp9v-vscode-1.33.0/bin/.code-wrapped: line 35: /../code: No such file or directory
```

My `dirname` version: `dirname (GNU coreutils) 8.29`.

**However**, `nix-shell -p vscode --run "code"` runs fine. What could possibly be interfering?

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.107, NixOS, 18.09.2367.15f08994517 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(max): `"nixpkgs-19.09pre174594.0c0954781e2"`
 - channels(root): `"nixos-18.09.2505.46d3867a08a, nixos-hardware, unstable-19.03pre166740.422b6bd489a"`
 - nixpkgs: `/home/max/.nix-defexpr/channels/nixpkgs`
```

**Comment by veprbl** [comment]
cc @eadwu

**Comment by Synthetica9** [comment]
I've ran into this before, and I thought I had fixed it: https://github.com/NixOS/nixpkgs/pull/56885 . This fix didn't actually work it turns out, but the gist of it is correct: you want to set `VSCODE_PATH` to a predetermined value instead of "deducing" it.

**Comment by eadwu** [comment]
Unable to replicate this, my output derivation is `/nix/store/901iijdz4v0sc1nvj30iqx7cxpbm97h3-vscode-1.33.1`.

**Comment by maxkrieger** [comment]
@eadwu strange, I ran `nix-channel --update` and my vscode version remains `1.33.0`.

@Synthetica9 if this isn't reproducible, any pointers to restoring the environment's integrity?

**Comment by Synthetica9** [comment]
@eadwu Yeah, it seems to be kinda finicky, it also randomly fixed itself again on my device. However, I still think this is a problem we should solve. 

@maxkrieger I opened #59766, could you check if that fixes your problem?

**Comment by maxkrieger** [comment]
This feels like a recurring design issue in Nix from personal experience. A similar situation for me is occurring with my LaTeX path interacting with Anki in #59091. Are there any broader discussions about the conflict between environments being at odds with reproducibility and declarativeness? What's the heuristic for solving issues where packages launch *perfectly fine* in `nix-shell`, and fail in `nix-env`?

@Synthetica9 thanks, will try later this week.

**Comment by eadwu** [comment]
In terms of conflicts, `meta.priority` could be used, though it would be better to figure out which packages are causing the conflict before adding the attribute randomly.
