### ISSUE TITLE
linuxPackages_hardened fails to build on 19.03

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#59771]
## Issue description
Having this in my config:
> boot.kernelPackages = mkDefault pkgs.linuxPackages_hardened;

Errors out to:
```
make[1]: Leaving directory '/build/linux-4.19.34/build'
Error: modDirVersion 4.19.34 specified in the Nix expression is wrong, it should be: 4.19.34-hardened
builder for '/nix/store/7slfrhibgfsdvx4zn3yi37k448iq3knx-linux-4.19.34.drv' failed with exit code 1
```
Complete Error: https://gist.github.com/Luis-Hebendanz/237f1b0aff6dc2c1051fbeeadc61d4b8

### Steps to reproduce

$ nix-channel --add https://nixos.org/channels/nixos-19.03 nixos
$ nixos-rebuild switch --upgrade

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172231.7b36963e7a7 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172231.7b36963e7a7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by joachifm** [comment]
Should be fixed on next channel update

**Comment by NeQuissimus** [comment]
Why did this break? Do you know?
