### ISSUE TITLE
perlPackages.libapreq2 does not install perl module

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#59773]
## Issue description
The `perlPackages.libapreq2` package does not include the perl modules which are part of the upstream source code.

The missing modules are:
https://metacpan.org/source/ISAAC/libapreq2-2.13/glue/perl/lib/Apache2
https://metacpan.org/source/ISAAC/libapreq2-2.13/glue/perl/xsbuilder/APR

When building locally I see `./configure --enable-perl-glue ...` which leads me to believe the issue might be in the custom `installPhase`:
```
    installPhase = ''
      mkdir $out
      make install DESTDIR=$out
      cp -r $out/${pkgs.apacheHttpd.dev}/. $out/.
      cp -r $out/$out/. $out/.
      rm -r $out/nix
    '';
```

@volth do you have any ideas?

### Steps to reproduce
Install `perlPackages.libapreq2` and note there are no perl modules included.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172205.ea497998e4b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172205.ea497998e4b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by volth** [comment]
No idea.
It is from https://github.com/NixOS/nixpkgs/pull/9194
One of those unreviewed PR merged immediately by the author with empty Github profile

**Comment by aanderse** [comment]
@ts468 any ideas on the `installPhase` and getting the perl modules included with this package?

**Comment by aanderse** [comment]
`libapreq2` is made up of a c library, a perl module, and an apache module. In nixpkgs `libapreq2` does not include the perl or apache modules.

Proposed fix to `libapreq2` in nixpkgs: https://github.com/NixOS/nixpkgs/compare/master...aanderse:libapreq2

@volth how does this look to you?

**Comment by volth** [comment]
LGTM, if it works

**Comment by aanderse** [comment]
> LGTM, if it works

Thank you for taking a look @volth!
