### ISSUE TITLE
ZFS unstable fails to build with latest Kernel

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#59770]
## Issue description
On upgrading my 18.09 zfs encrypted base system with 
```
zfs.enableUnstable = true;
zfs.requestEncryptionCredentials = true;
boot.kernelPackages= pkgs.linuxPackages_latest;
```
I got the following error:

```
cc1: some warnings being treated as errors
make[7]: *** [/nix/store/zqcvpqpl1vy3pjiw9imkapj5n1cpp868-linux-5.0.7-dev/lib/modules/5.0.7/source/scripts/Makefile.build:277: /build/source/module/icp/illumos-crypto.o] Error 1
make[6]: *** [/nix/store/zqcvpqpl1vy3pjiw9imkapj5n1cpp868-linux-5.0.7-dev/lib/modules/5.0.7/source/scripts/Makefile.build:492: /build/source/module/icp] Error 2
make[5]: *** [/nix/store/zqcvpqpl1vy3pjiw9imkapj5n1cpp868-linux-5.0.7-dev/lib/modules/5.0.7/source/Makefile:1576: _module_/build/source/module] Error 2
make[4]: *** [Makefile:171: sub-make] Error 2
make[3]: *** [Makefile:15: __sub-make] Error 2
make[3]: Leaving directory '/nix/store/zqcvpqpl1vy3pjiw9imkapj5n1cpp868-linux-5.0.7-dev/lib/modules/5.0.7/build'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/build/source/module'
make[1]: *** [Makefile:799: all-recursive] Error 1
make[1]: Leaving directory '/build/source'
make: *** [Makefile:668: all] Error 2
builder for '/nix/store/b811aynkhvf34pgdlhs5y40vc7xphgwg-zfs-kernel-0.8.0-rc3-5.0.7.drv' failed with exit code 2
cannot build derivation '/nix/store/fwiygb7j4d8isajr8znm8qbyd46f5i97-kernel-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nmwr49gfsq26qm7xzrsa0k75wj9i97d2-nixos-system-home-server-19.03.172205.ea497998e4b.drv': 1 dependencies couldn't be built
error: build of '/nix/store/nmwr49gfsq26qm7xzrsa0k75wj9i97d2-nixos-system-home-server-19.03.172205.ea497998e4b.drv' failed
```

Full output: https://gist.github.com/Luis-Hebendanz/333ca4eb855cf9d2889b7386a6477456

### Steps to reproduce
```
$ nix-channel --add https://nixos.org/channels/nixos-19.03 nixos
$ nixos-rebuild switch --upgrade
```

## Reason (thanks @Ashy)
https://www.phoronix.com/scan.php?page=news_item&px=ZFS-On-Linux-5.0-Workaround

## Workaround
Not using the latest kernel

> #boot.kernelPackages= pkgs.linuxPackages_latest;

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 18.09.2519.2aa505b77c0 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2519.2aa505b77c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

**Comment by tilpner** [comment]
This is because [zfs-0.8.0-rc3 doesn't support Linux 5](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0-rc3):

> Supported Kernels
>    Compatible with 2.6.32 - 4.20 Linux kernels.

**Comment by Luis-Hebendanz** [comment]
Thanks! Maybe adding an "these two options are incompatible with each other" would help. Or a kernel version check in zfs package

**Comment by tilpner** [comment]
They are not always incompatible, just with this specific combination versions. Modules usually don't depend too much on package versions, and the warning would probably be removed soon, possibly before that warning reaches the people who could benefit from it, so I'm not sure that'd be worth it.

**Comment by AshyIsMe** [comment]
Wow, with surprisingly good timing it looks like zfs-0.8.0-rc4 has just dropped and adds support for the 5.0 kernel:
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0-rc4

**Comment by adisbladis** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/59791
