### ISSUE TITLE
rygel fails to build

### ISSUE THREAD

**Issue by lightbulbjim** [NixOS/nixpkgs#59815]
## Issue description

rygel fails to build due to a valadoc error when generating docs. The error is:
`error: Package 'gupnp-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories`

This prevents gnome3 from being built unless `services.gnome3.rygel.enable` is set to `false`.

### Steps to reproduce

`nix-build '<nixpkgs>' -A gnome3.rygel ~/repos/nixpkgs`

Tested against `7f2f8f359fe`, which at the time of writing is the HEAD of `nixos-unstable-small`.

## Technical details

System info:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.35, NixOS, 19.09pre176459.7f2f8f359fe (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre176459.7f2f8f359fe"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Yeah the api docs have references to [`gupnp-1.0`](https://gitlab.gnome.org/GNOME/rygel/blob/master/doc/reference/librygel-core/meson.build#L11).

So we could drop `api_docs=true` or just  patch to `gupnp-1.2`.

Needs an installation sysconfidir patch as well.
```
PermissionError: [Errno 13] Permission denied: '/etc/rygel.conf'
```
