### ISSUE TITLE
unity3d webgl build module error.

### ISSUE THREAD

**Issue by PlumpMath** [NixOS/nixpkgs#59830]
## Issue description
building webgl..
occur wasm & clang error.

welll build good in ubuntu.

### Steps to reproduce
unity-hub too. same problem

## Technical details
# installed package list
unity3d
emscripten emscriptenPackages.json_c emscriptenPackages.libxml2 emscriptenPackages.xmlmirror emscriptenPackages.zlib emscriptenfastcomp
ncurses ncurses6 ncurses5
cquery
gnome2.GConf

**Comment by PlumpMath** [comment]
In fact, Unity in the Unity Hub and Knicks package is a bit different.

If you install Unity as a Unity hub, the webgl build module is installed (and you get an error when you use it).
Contrary..
If you install Unity with nix pkgs, you will notice that there is no webgl build module at all.

I will look at it too,
I'm currently trying to use the unreal unity houdini set,
houdini was installable.
However, both unreal and unity failed.

**Comment by PlumpMath** [comment]
[https://gist.github.com/PlumpMath/933c619160ecdbc9777bc41a7928c4ea](url)

**Comment by PlumpMath** [comment]
TIP: 
Install unity-hub as flatpak flathub.
that's available~ :)

**Comment by PlumpMath** [comment]
https://github.com/NixOS/nixpkgs/pull/65391

Still can't WebGL Build, Flatpak has the same problem.

**Comment by gustawdaniel** [comment]
No. @stable. It is not stable. It does not work.

I have Ubuntu 20.04 and I can't export webgl from unity 3d and have the same error.
