### ISSUE TITLE
siji font is installed but not available

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#59847]
## Issue description

`fc-list siji` finds nothing.

```nix
{
  fonts.fonts = with pkgs; [
    # ...
    siji
  ];
}
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.09pre175916.1fc591f9a5b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre175916.1fc591f9a5b, home-manager"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by JohnAZoidberg** [comment]
I can confirm. When running `nixos-rebuild` with `siji` installed the log shows this:
```
/nix/store/jiihakhvhd0nqbslk59h3j5ib0948bfm-siji-2016-05-13: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/jiihakhvhd0nqbslk59h3j5ib0948bfm-siji-2016-05-13/share: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/jiihakhvhd0nqbslk59h3j5ib0948bfm-siji-2016-05-13/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/jiihakhvhd0nqbslk59h3j5ib0948bfm-siji-2016-05-13/share/fonts/pcf: caching, new cache contents: 0 fonts, 0 dirs
/nix/store/c3ln5nlqc6adja44ka8vrrz3g645pv1f-font-bh-lucidatypewriter-100dpi-1.0.3: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/c3ln5nlqc6adja44ka8vrrz3g645pv1f-font-bh-lucidatypewriter-100dpi-1.0.3/lib: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/c3ln5nlqc6adja44ka8vrrz3g645pv1f-font-bh-lucidatypewriter-100dpi-1.0.3/lib/X11: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/c3ln5nlqc6adja44ka8vrrz3g645pv1f-font-bh-lucidatypewriter-100dpi-1.0.3/lib/X11/fonts: caching, new cache contents: 0 fonts, 1 dirs
/nix/store/c3ln5nlqc6adja44ka8vrrz3g645pv1f-font-bh-lucidatypewriter-100dpi-1.0.3/lib/X11/fonts/100dpi: caching, new cache contents: 28 fonts, 0 dirs
```

fontconfig sees the directory but not the file inside. See lucida below for how it should look like: `28 fonts`.
Lucida is recognized later on by `fc-list`. The difference between both fonts, that I can see and think is relevant is that lucida is gzipped. I'm not sure if that is what breaks things.

**Comment by JohnAZoidberg** [comment]
Gzipping doesn't help either. Seems that there are some problems with `pcf` fonts.
Maybe this is contributing to the issue https://lists.freedesktop.org/archives/fontconfig/2005-April/001324.html but I don't know how to check for that.

Users of other distributions also have problems using the font and their problem is solved by using the `bdf` font file instead: https://github.com/stark/siji/issues/28

I added the `bdf` file and now it works for me:

```
fc-list siji
/nix/store/gq7hnv21hqg8yhzmj3b2xynh5mjx8zwj-siji-2016-05-13/share/fonts/bdf/siji.bdf: Siji:style=Regular
```

See: #59859
