### ISSUE TITLE
moviepy is broken in 19.03

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#59857]
## Issue description
`python3Packages.moviepy` is broken in current 19.03 nixpkgs: https://hydra.nixos.org/build/91932416

### Steps to reproduce
Attempt to build `python3Packages.moviepy`, this also fails if I pull in the `python3Packages.requests` with something like `nix-shell`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172231.7b36963e7a7 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172231.7b36963e7a7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by JohnAZoidberg** [comment]
Seems like the package was updated in #55757 but the list of its dependencies was not.
I fixed it in #59862
