### ISSUE TITLE
[ruby] Document new ruby infrastructure

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#5985]
nixpkgs documentation is outdated: http://nixos.org/nixpkgs/manual/#ssec-language-ruby

Announcement for new ruby infrastructure: http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015780.html

I have one question: how do we handle packages that depend on a single rubt lib? See 9a5b521

**Comment by dredozubov** [comment]
Anything happenning here? Current state of affairs seems very frustrating to me from a user perspective.

**Comment by iElectric** [comment]
cc @cstrahan

**Comment by dredozubov** [comment]
I'll be willing to help with bundix and ruby infrastructure tools if someone is willing to get me up to speed with this.
cc @cstrahan

**Comment by cstrahan** [comment]
Hey,

Here's a PR to bring back `rubyLibs`, along with my thoughts (and open questions) on the subject: https://github.com/NixOS/nixpkgs/pull/6580

I'm `cstrahan` on `#nixos` - could we perhaps chat over IRC?

**Comment by cstrahan** [comment]
> Anything happenning here? Current state of affairs seems very frustrating to me from a user perspective.

@dredozubov: Is it the outdated documentation that's frustrating, or the requirement to use `bundix` that you find frustrating? If it's the latter, why?

**Comment by ryantm** [comment]
I linked to the mailing list announcement on https://nixos.org/wiki/Ruby page as a stop-gap.

**Comment by ctheune** [comment]
I just worked with this yesterday and I'm happy to update the documentation to reflect that status quo. Not sure about the rubyLibs thing. Even if you depend on only a single package: using bundix is quite straight forward and there is no reason not to use it even in that situation. 

I'll try to work on this today.
