### ISSUE TITLE
nixops: remove pinned azure-mgmt-* libraries

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#59868]
## Issue description

After [azure support has been disabled](https://github.com/NixOS/nixops/issues/1065#issuecomment-484716162) in nixops, we can remove the locally pinned version in nixpkgs.

**Comment by AmineChikhaoui** [comment]
Not yet, I would like to keep those for building nixops v1.6.1 for any users of the Azure backend.
