### ISSUE TITLE
Gnome 3.32: cycle-windows / cycle-windows-backwards stopped working

### ISSUE THREAD

**Issue by sboehler** [NixOS/nixpkgs#59877]
## Issue description

I have just upgraded to Gnome 3.32 (NixOS Unstable) and seem to be unable to switch windows using the 'org/gnome/desktop/wm/keybindings/cycle-windows' and 'org/gnome/desktop/wm/keybindings/cycle-windows-backwards' actions. The default shortcut is Alt-Escape, but customizing this shortcut does not work either. Resetting my dconf state did not help.

Other similar actions (cycle-group etc) do work as expected. 

Not sure whether this is an upstream issue, however both actions work as expected in Ubuntu 19.04 with Gnome 3.32, and I didn't find a relevant issue or commit upstream.

### Steps to reproduce

- Install Gnome 3.32
- Hit Alt-Escape
- Observe windows do not switch

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 5.0.7, NixOS, 19.09.git.1fc591f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `""`
 - nixpkgs: `/nix/nixpkgs`

**Comment by hedning** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1064

fixed in gnome-shell-3.32.1: #59829

**Comment by sboehler** [comment]
Thank you!
