### ISSUE TITLE
[request] sclack (CLI slack client)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#59900]
https://github.com/haskellcamargo/sclack

Still under development, but already looks usable and possibly better than other solutions!

**Comment by teto** [comment]
Have you tried the weechat/slack interface already ? I wonder if I should give it a try (slack is so slow and memory hungry I usually have to shut it down when I am doing serious work xD)

**Comment by FliegendeWurst** [comment]
sclack wasn't updated in over three years. It doesn't work at the moment
