### ISSUE TITLE
fixDarwinDylibNames fails for some libraries

### ISSUE THREAD

**Issue by jacereda** [NixOS/nixpkgs#59925]
## Issue description
While trying to fix the samba build for Darwin I found that it installs some libraries without write permissions. `fixDarwinDylibNames` won't help for those.

Could it do a `chmod u+w` prior to `install_name_tool`?

**Comment by flokli** [comment]
@jacereda stdenv setup hook already [makes everything writable in fixupPhase for similar reasons](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L1113-L1117).

Can you move whatever call of `fixDarwinDylibNames` into that phase?

**Comment by jacereda** [comment]
I see, I noticed some libraries in samba were read-only and I assumed they were like that at fixup time. So the issue is elsewhere, I think I know the real problem. I'll open a separate issue, thanks.
