### ISSUE TITLE
Filtering src recursively when creating a derivation

### ISSUE THREAD

**Issue by lippirk** [NixOS/nixpkgs#59928]
I'm creating a derivation using items in a big folder, but I only actually want to use a few files to create the derivation. These files are nested in various directories. So I thought I could use `sourceByRegex` to select those files. But unfortunately `sourceByRegex` only seems to search through the top level of a folder.

For example:

```
$ tree
.
├── 1
├── 2
├── 3
├── default.nix
├── folder
│   ├── 1
│   └── 2
└── result -> /nix/store/951h922h1cx55703yk5fqj1l059d7kvg-my-drv

2 directories, 6 files

```
```
$ cat default.nix
{pkgs ? import <nixpkgs> {}}:
pkgs.stdenv.mkDerivation {
  name = "my-drv";
  src = pkgs.lib.sources.sourceByRegex ./. ["2" "folder\/.*"];
  installPhase = ''
    set -e
    mkdir -p $out/bin
    cp -r $src/* $out/bin/
    '';
}

$ ls /nix/store/951h922h1cx55703yk5fqj1l059d7kvg-my-drv/bin
2
```

I hoped to see the both the file `2` and also `folder` in that last output, but only `2` was copied.

Is there another way to achieve this?

**Comment by Infinisil** [comment]
Check out https://github.com/NixOS/nixpkgs/pull/56985, which adds a function to make this pretty easy
