### ISSUE TITLE
xbacklight reports "No outputs have backlight property"

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#59927]
## Issue description
The xbacklight utility errors out on 19.03 with:

```
 $ xbacklight -set 800  
No outputs have backlight property
```
And if I specifically define the Monitor following error happens:
```
xbacklight -d eDP-1 -set 800                                                                   
RANDR Query Version returned error -1
```
I noticed that after upgrading to 19.03 my monitor device names changed from eDP1 to eDP-1 and so on. It probably has something to do with that.
I used the 5.0 Kernel and the 4.19.35-hardened Kernel both had the same issue.

On Debian there is anopen issue on that from 2016:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833508

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.8, NixOS, 19.03.172286.8ea36d73256 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172286.8ea36d73256, nixos-unstable-19.09pre175916.1fc591f9a5b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Luis-Hebendanz** [comment]
I fixed it. The solution is to use `acpilight` which has a binary with the same name called xbacklight so the old `xorg.xbacklight` has to be removed. On top of that   `hardware.brightnessctl.enable = true;` has to be enabled and your user has to be added to the "video" group. After that `xbacklight -list` should return all controllable displays

**Comment by erikarvstedt** [comment]
A much faster alternative to the `acpilight` package is `light`.

**Comment by StephenWithPH** [comment]
For future searchers... @Luis-Hebendanz 's [comment above](https://github.com/NixOS/nixpkgs/issues/59927#issuecomment-485141310) got me 90% there, but I initially received the error:

```
/run/current-system/sw/bin/xbacklight: [Errno 13] Permission denied: '/sys/class/backlight/intel_backlight/brightness'
```

It was easy enough to `chown` the file to `root:video` and `chmod` it to `0664`. This, combined with the above, solved the problem for me.
