### ISSUE TITLE
*.drv is not valid

### ISSUE THREAD

**Issue by matejc** [NixOS/nixpkgs#5996]
I saw this kind of error the third time, it only shows itself on Travis and in some other cases that I do not know understand

 - I am talking about this:

https://travis-ci.org/NixOS/nixpkgs/builds/48054896

```
error: cannot import ‘/nix/store/zapaadgbk6pbfbxdiq1pk6ax62dra3b0-nixui/default.nix’, since path ‘/nix/store/01rsibv0w4h8yhcm8fv0qfv0p3sw655v-nixui.drv’ is not valid, at "/home/travis/.nox/nixpkgs/pkgs/tools/package-management/nixui/default.nix":13:12
```
and this fixes it:
https://github.com/NixOS/nixpkgs/pull/5921
```
- nodePackages = import "${pkgs.path}/pkgs/top-level/node-packages.nix" {
+ nodePackages = import ../../../top-level/node-packages.nix {
```

 - Exactly the same error happened before with Zed, and there was the same fix.

 - in NixUI I am experimenting with configurations and I got the same error when this is set: `nixpkgs.config.chromium.enablePepperFlash = true;`
the code:
https://github.com/NixOS/nixpkgs/blob/9343f6f4612301f9954ada94252701a2304c271c/pkgs/applications/networking/browsers/chromium/plugins.nix#L89

```
      getNix = plugin: import "${plugin}/nix-support/chromium-plugin.nix";
```

and the error seems very similar:

```
while evaluating ‘getNix’ at "/home/matej/workarea/nixpkgs/pkgs/applications/networking/browsers/chromium/plugins.nix":88:16, called from undefined position:
cannot import ‘/nix/store/77vm2bqpphps5d8ij578iwp32a965ws2-chromium-binary-plugins-flash/nix-support/chromium-plugin.nix’, since path ‘/nix/store/jy2i9pjxmjwdnix8v0r1282gpd0l3wdn-chromium-binary-plugins.drv’ is not valid, at "/home/matej/workarea/nixpkgs/pkgs/applications/networking/browsers/chromium/plugins.nix":88:24
```

Probably on Hydra/Travis we never set `nixpkgs.config.chromium.enablePepperFlash = true;`, so it never gets there, therefore there is no error, building chromium or plugin separately works as expected.

I would really like to know what is going on, so I can fix it (at least this chrome plugin problem).

**Comment by edolstra** [comment]
When you do `"${pkgs.path}/bla"`, it will cause Nixpkgs to be copied to the Nix store. As a workaround, you can say `"${builtins.toString pkgs.path}/bla"` instead. However, there is really no reason to use `pkgs.path` inside Nixpkgs itself since you can use a relative path.

**Comment by matejc** [comment]
@edolstra  thanks for the explanation, and I fixed nixui, it was some other issue with configuration reading. Closing now.
