### ISSUE TITLE
switchboard crash when click on "Security & Privacy"

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#59984]
## Issue description

```
[davidak@X230:~]$ io.elementary.switchboard

** (.io.elementary.switchboard-wrapped_:7560): CRITICAL **: 22:38:13.259: polkit_unix_process_set_property: assertion 'val != -1' failed

** (.io.elementary.switchboard-wrapped_:7560): CRITICAL **: 22:38:13.325: file /build/source/src/Views/LockPanel.vala: line 33: uncaught error: Failed to open file “/nix/store/79n8yx4gzhz0wbp6arwqhzcxq9k5i22f-light-locker-1.9.0/share/gsettings-schemas/light-locker-1.9.0/glib-2.0/schemas/gschemas.compiled”: open() failed: No such file or directory (g-file-error-quark, 4)

(.io.elementary.switchboard-wrapped_:7560): GLib-GIO-CRITICAL **: 22:38:13.325: g_settings_schema_source_lookup: assertion 'source != NULL' failed

(.io.elementary.switchboard-wrapped_:7560): GLib-GIO-CRITICAL **: 22:38:13.325: g_settings_new_full: assertion 'schema != NULL' failed
Segmentation fault
```

### Steps to reproduce

1. open switchboard
2. click on "Security & Privacy"
3. :boom: 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172311.454eea84a75 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.172311.454eea84a75, nixos-hardware, nixos-unstable-19.09pre175916.1fc591f9a5b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
I need to add
```
postInstall = ''
    ${glib.dev}/bin/glib-compile-schemas $out/share/glib-2.0/schemas
'';
```
to `lightlocker`.

Fix incoming.

**Comment by worldofpeace** [comment]
Fixed in
* master ce14f9a9befd7fc3e24b14a8cd52383acacf0b13
* 19.03 330b9fac6000ced90756d56fdbaab1ded58a13cb

Thank you for reporting @davidak :sparkle:
