### ISSUE TITLE
Pantheon uses icons and settings from previous GNOME session

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#59982]
## Issue description

I upgraded to 19.03 and switched from GNOME 3 to Pantheon.

I noticed that the elementary icons are not used.

![Screenshot from 2019-04-21 22-01-17](https://user-images.githubusercontent.com/91113/56474915-06d9b300-6481-11e9-83c0-1bccdb0be9c8.png)

the menu icons are also strange:
![Screenshot from 2019-04-21 21-41-44](https://user-images.githubusercontent.com/91113/56474929-3e485f80-6481-11e9-9820-aa20be78628e.png)

and the window decoration is huge for some apps:
![Screenshot from 2019-04-21 22-07-04](https://user-images.githubusercontent.com/91113/56474967-dba39380-6481-11e9-9849-e834bff41bb1.png)

With gnome-tweaks you see, that the default gnome theme and icons are used. I can set them to Elementary.

![Screenshot from 2019-04-21 22-15-00](https://user-images.githubusercontent.com/91113/56475053-56b97980-6483-11e9-9418-f34c70153b25.png)

![Screenshot from 2019-04-21 22-15-45](https://user-images.githubusercontent.com/91113/56475056-5a4d0080-6483-11e9-86e7-291bcf324a45.png)

@worldofpeace can you provide a one-liner to reset the settings and add it to the NixOS manual?

### Steps to reproduce

1. use gnome
2. then use pantheon

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172311.454eea84a75 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.172311.454eea84a75, nixos-hardware, nixos-unstable-19.09pre175916.1fc591f9a5b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Pantheon has the exact code hidden that would fix this instantly https://github.com/elementary/switchboard-plug-about/blob/eb81a4a69e4ffde0995f4e64e8089d9aae1dd78b/src/Plug.vala#L306

Simply open `Switchboard` and go to the `About` plug and select
![Screenshot from 2019-04-21 19 27 00](https://user-images.githubusercontent.com/28888242/56476810-75ac1180-646b-11e9-9d0f-bcfab51a564f.png)
The desired effect should be immediate.

**Comment by davidak** [comment]
Works perfectly. Thanks!
