### ISSUE TITLE
plymouth shows NixOS version only at shutdown, not at start (when GRUB is used)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#59992]
## Issue description

It should always show the NixOS version.

Reproducible on:

- Lenovo Thinkpad X230 with **grub**

Not reproducible on:

- Apple iMac 11,3 with systemd-boot (EFI)
- Thinkpad L470 with systemd-boot (EFI)

### Steps to reproduce

1. boot system
2. shut down system

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172311.454eea84a75 (Koi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.172311.454eea84a75, nixos-hardware, nixos-unstable-19.09pre175916.1fc591f9a5b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
I can second this. It's been the case for *ages*.

**Comment by michaelpj** [comment]
Yes, I'm not sure why this is. It used to show it at startup, and I don't think anything much has changed there.

**Comment by davidak** [comment]
I did an update yesterday and bootet the system today and the version was shown. It's a Thinkpad L470. I will see if it fixes it also on the system i used when reporting this issue.

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.03.173202.31d476b8797 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173202.31d476b8797, nixos-hardware, nixos-unstable-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
Doesn't work here on latest unstable.

**Comment by davidak** [comment]
Seems to be a problem specifically with GRUB.

**Comment by peterhoeg** [comment]
>   Seems to be a problem specifically with GRUB.

I'm using systemd-boot, not GRUB.

**Comment by peterhoeg** [comment]
Problem persists.

**Comment by andersk** [comment]
This is because the Plymouth `label` plugin is missing from the initrd, along with a font with which to render the text. See #99011.
