### ISSUE TITLE
Atom on Pantheon: can't delete file

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#60000]
## Issue description

![Screenshot from 2019-04-21 23-24-31](https://user-images.githubusercontent.com/91113/56479414-9a2cdb80-64b5-11e9-8284-99457fe059fd.png)

`Is gvfs-trash installed?`

Should it get added to the runtime dependencies?

cc @worldofpeace 

### Steps to reproduce

1. open atom
2. try to delete a file

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172311.454eea84a75 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.172311.454eea84a75, nixos-hardware, nixos-unstable-19.09pre175916.1fc591f9a5b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
It seems that these specific conditions need to be met to see that error message
* https://github.com/atom/atom/issues/17452#issuecomment-409518547

Very confusing error message as that tool is now long gone.

Glazed the thread and saw someone doing
```
export ELECTRON_TRASH=gio
```
so you can still delete things.

But this is an actual bug in atom.

**Comment by worldofpeace** [comment]
In newer `atom` https://github.com/atom/atom/pull/19419 this issue should be fixed because `electron 3` doesn't use `gvfs-trash` for this.

**Comment by davidak** [comment]
I can confirm that it is fixed on NixOS stable 20.03.2141.8b071be7512 (Markhor).
