### ISSUE TITLE
perl.withPackages: strategy to resolve collisions

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#60025]
## Issue description

```perlPackages``` has some libraries (```ArchiveTar```, ```Encode```, ```JSONPP```, ```CPAN```, ```ExtUtilsMakeMaker```, ```IOCompress```, ```PodChecker```, ```PodParser```, ```PodPerldoc```, ```podlators```) whose older versions are included in ```perl```.

```nix
perl.withPackages(p: with p; [ArchiveTar Encode JSONPP CPAN ExtUtilsMakeMaker
 IOCompress PodChecker PodParser PodPerldoc podlators])
```
fails because some files exist in more than one package passed to ```buildEnv```.

Possible ways to fix:

1. by deleting conflicting files from the packages (like it was done with ```Encode``` in
https://github.com/NixOS/nixpkgs/pull/59215#issuecomment-481485707 https://github.com/NixOS/nixpkgs/pull/59215/commits/f73eb61113998952f742e3c542a9e95d9791abd4). The disadvantage is: in the final environment we get the files from the library included in ```perl```, usually the oldest of the conflicting libraries.

2. pass ```ignoreCollisions=true``` to ```buildEnv``` hoping the newest of the conflicting libraries will win

3. assume that ```perl.withPackages(p: [p.ArchiveTar])``` means not to add a library but to upgrade (or to downgrade) the library included in ```perl```, so ```withPackages``` should be smart enough to **remove** the library included in ```perl``` and use the library from the right hand side instead.

4. forcingly upgrade libraries in ```perl``` to the latest versions in ```perlPackages``` and remove the libraries from ```perlPackages```

@aanderse

**Comment by aanderse** [comment]
My initial thought was that #3 sounds the most ideal. What is your choice?

I'd like to clarify that the problem you mention does not apply to any use case which existed before perl.withPackages, correct? I don't want people getting the wrong impression that this breaks backwards compatibility.

**Comment by volth** [comment]
Actually the collision is only files in ```$out/bin``` and ```$out/share/man/man1```.
So it is not about the libraries but only about the supplemental CLI tools

**Comment by aanderse** [comment]
Now that you've added #4 that sounds like a great option... In that scenario we would just alias the package to null like other perlPackages have done in the past? This option also sounds like very low impact, right?

**Comment by volth** [comment]
I'm sort of leaning towards №2 with adjusting ```perl.meta.priority``` so it will give up to the libraries.
№3 is more fair but it would require forking+patching ```buildEnv``` only for few CLI utilities and their man pages that perhaps no one ever launches)

**Comment by aanderse** [comment]
@volth Given we're talking about collisions only occurring in `$out/bin` and `$out/share/man/man1` <span>#</span>2 sounds perfectly reasonable to me as well :+1:
