### ISSUE TITLE
nikola auto fails

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#60034]
## Issue description

```
ERROR: Nikola: In order to use the "auto" command, you must install the "aiohttp" and "watchdog" Python packages.
ERROR: Nikola: Exiting due to missing dependencies.
```

### Steps to reproduce

`nikola auto`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172311.454eea84a75 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.172311.454eea84a75, nixos-hardware, nixos-unstable-19.09pre175916.1fc591f9a5b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
Feel free to make a PR adding these two as dependencies.
