### ISSUE TITLE
Update prl-tools to new version on NixOS

### ISSUE THREAD

**Issue by Vonfry** [NixOS/nixpkgs#60077]
## Issue description

Now, version of prl-tools in nixpkgs cannot work in kernel 4.19.

I try to make a pr on prl-tools(#59817), but it failed.  Some binary files  use `/usr/bin/<sth>` in their code, I have no idea to fix them.

### Steps to reproduce

see: #59817

## Technical details

prl-tools __log__: [gist](https://gist.github.com/Vonfry/58098e51ac7d888d2335cd307ea0d3b4)

Some of them can be used, but some not. 

For example, prlcc is one which cannot be run. prlcp is the one which can bu run.

**Comment by mikroskeem** [comment]
Any updates on this?

**Comment by Vonfry** [comment]
@mikroskeem Nothing. Would you like to fix this?

**Comment by mikroskeem** [comment]
I would, but I need to figure out how nixpkgs works before I can get my hands on it.

However I'm not sure how I should test the package building... thought about using overlay but not sure if it's the right way (and I couldn't even get it working properly).

Any help & pointers for beginner like me is appreciated though 😄

**Comment by sandangel** [comment]
should be closed now

**Comment by mikroskeem** [comment]
Solved in #179582
