### ISSUE TITLE
haskell-ng: fix naming conflicts between buildDepends and pkgconfigDepends

### ISSUE THREAD

**Issue by k0ral** [NixOS/nixpkgs#6007]
In (the automatically generated) `hackage-packages.nix`, some packages won't build because of improper naming of their dependencies.
For example, the `gio` package is defined as follows:

```nix
  "gio" = callPackage
    ({ mkDerivation, array, base, bytestring, containers, glib
     , gtk2hs-buildtools, mtl
     }:
     mkDerivation {
       # (...)
       buildDepends = [ array base bytestring containers glib mtl ];
       buildTools = [ gtk2hs-buildtools ];
       pkgconfigDepends = [ glib ];
       # (...)
     }) { inherit (pkgs) glib;};

```

Here, the name `glib` is used in both `pkgconfigDepends` and `buildDepends`, which is wrong since the former expects the C library derivation, while the latter expects the haskell package derivation. I guess the intention was to let `callPackage` look-up the `glib` haskell derivation, but here it is explicitly fed with `pkgs.glib`.
There are multiple other impacted packages, but since fixing the `hackage-packages.nix` generator should fix them all, I won't bother enumerating them :) .

**Comment by peti** [comment]
Yes, you are right. This issue is recorded in https://github.com/NixOS/cabal2nix/issues/136 and I'm working on a fix.
