### ISSUE TITLE
It's not clear how to enable core dumps

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#60088]
## Issue description

In best case `systemd.coredump.enable = true;` would be enough.

But the description says: "Note that this alone is not enough to enable core dumps."

https://nixos.org/nixos/options.html#coredump

So when it's not possible to extend this option, please add a section to the manual with detailed instructions and code.

I tried this, but `coredumpctl` still shows no coredumps. But i'm not sure it should.

```
  # enable core dumps
  systemd.coredump.enable = true;
  security.pam.loginLimits = [
    { domain = "*"; item = "core"; type = "soft"; value = "unlimited"; }
  ];
  systemd.extraConfig = "DefaultLimitCORE=1000000";
```

I have rebootet after the rebuild.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172312.330b9fac600 (Koi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172312.330b9fac600, nixos-hardware, nixos-unstable-19.09pre176329.d2602779281"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
The option was always sufficient for me. Did you try to run `coredumpctl` with sudo if the crashing process is not your own?

**Comment by peterhoeg** [comment]
> The option was always sufficient for me.

Same here. And running ```coredumpctl``` should list all dumps even those you don't have access to inspect without sudo.

**Comment by davidak** [comment]
There was just no crash. I tested with `kill -SIGSEGV 12420` and got a core dump.

**Comment by jtojnar** [comment]
I understand the sentence to refer to the limits, linking to the relevant docs appropriately.

P.S. Jonathan has a [new GitHub account](https://github.com/glines), though this one does not seem to be active either.

**Comment by baracoder** [comment]
Any updates on this?

**Comment by jtojnar** [comment]
`systemd-coredump` [now](https://github.com/NixOS/nixpkgs/pull/66482) handles coredumps by default.
