### ISSUE TITLE
Boot freezes on starting udev after 18.09 => 19.03 upgrade

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#60158]
## Issue description

I'm using an encrypted root partition and after entering my passphrase, selecting the first option in grub the boot freezes on loading udev - right before the second passphrase normally appears. 

I'm not sure how to troubleshoot, since the boot freezes so early. If anyone have any ideas on how to debug, please let me know and I'll try. 

## Technical details

**Computer:** HP x360 Envy 15"

Encrypted partition for `/` with the following configuration: 

```nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e9a6a904-cf3a-4f6e-ade6-52905f9a98ce";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/f25a7f52-9ebd-4c30-83c6-d1f531b151f0";

  swapDevices = [ ];

  boot.kernelPackages = pkgs.linuxPackages_latest;

  # https://askubuntu.com/a/1053349
  boot.kernelParams = [
    "idle=nomwait"
    "pcie_aspm=off"
    # https://github.com/NixOS/nixpkgs/issues/44183#issuecomment-408669458
    "amdgpu.dc=1"
  ];
}
```

```bash
$ lsblk -f 
NAME        FSTYPE      LABEL UUID                                 MOUNTPOINT
nvme0n1                                                            
└─nvme0n1p1 crypto_LUKS       f25a7f52-9ebd-4c30-83c6-d1f531b151f0 
  └─crypted ext4              e9a6a904-cf3a-4f6e-ade6-52905f9a98ce /
```

**Comment by rzetterberg** [comment]
Just rebuilt with the latest changes on 19.03 so that I would get kernel `5.0.13`, but I still have the same problem as before. 

However, when I made the following change:

```diff
+boot.kernelPackages = pkgs.linuxPackages_4_19;
-boot.kernelPackages = pkgs.linuxPackages_latest;
```
 
I was able to boot `4.19.39` without any problems.

**Comment by chrissound** [comment]
Does the machine actually hang or can you possibly try logging in via SSH?

**Comment by chrissound** [comment]
Possible the same issue: https://github.com/NixOS/nixpkgs/issues/54050

**Comment by rzetterberg** [comment]
> Does the machine actually hang

Yes, this happens before I get to type in the password for my encrypted root.

**Comment by Atemu** [comment]
I don't think this is relevant anymore.
