### ISSUE TITLE
Can't install Jupyterlab with python 3.7

### ISSUE THREAD

**Issue by tcosmo** [NixOS/nixpkgs#60154]
## Issue description

Jupyterlab builder fails on python37 with the error:

`Collecting jupyterlab-server<0.3.0,>=0.2.0 (from jupyterlab==0.35.4)
  Could not find a version that satisfies the requirement jupyterlab-server<0.3.0,>=0.2.0 (from jupyterlab==0.35.4) (from versions: )
No matching distribution found for jupyterlab-server<0.3.0,>=0.2.0 (from jupyterlab==0.35.4)
builder for '/nix/store/cjb48hbc1x4k5y9wd9r0s52basz0xjz5-python3.7-jupyterlab-0.35.4.drv' failed with exit code 1
`

Any ideas?

### Steps to reproduce

` nix-shell -p python37Packages.jupyterlab`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.09pre176329.d2602779281 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre176329.d2602779281"`
 - channels(cosmo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
@matthiasbeyer Why did you merge https://github.com/NixOS/nixpkgs/commit/f753a106f259f0edb46384817a7120009c8a3296 even though it breaks jupyterlab?

**Comment by dotlambda** [comment]
We can either apply https://github.com/jupyterlab/jupyterlab/commit/3b8d451e6f9a4c609e60cde5fbb3cc84aae79951 using `fetchpatch` or revert f753a10.

**Comment by matthiasbeyer** [comment]
Fix incoming.

**Comment by tcosmo** [comment]
Thank you very much!
