### ISSUE TITLE
Google Cloud image breaks sudo on upgrade to 19.03

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#60177]
## Issue description

I booted the latest 18.09 image for Google, switched to my branch of nixpkgs (riding on top of `nixos-unstable`). Upon a `switch`, I became unable to elevate to root and was locked out of my instance.

Upon rebuilding, I paid closer attention, the Google Accounts service is not dropping the sudoers configuration bits into the right /run/ directory, and so my user being in the `google-sudoers` group is appearing to have no effect.

```
$ sudo ls /run/google-sudoers.d

```

cc: @adisbladis 
ref: https://github.com/NixOS/nixpkgs/pull/51566

**Comment by matthewbauer** [comment]
Could you also post what your config looked like before the ```nixos-rebuild switch```? It may have been missing the ```security.googleOsLogin.enable``` option.

**Comment by colemickens** [comment]
@matthewbauer I'm not sure I understand. I'm just using a pre-built image, where the configuration.nix is just including the `google-image-config.nix` file (which does specify that option in the `nixos-unstable` branch, it's part of the commit that removes the Google Accounts service).

**Comment by dingxiangfei2009** [comment]
@colemickens Have you enabled [Google OS Login](https://cloud.google.com/compute/docs/instances/managing-instance-access) on your instance?

**Comment by colemickens** [comment]
@dingxiangfei2009 you have correctly diagnosed and provided a workaround that seems to work (though I didn't see your edit til now, I never clicked through the mail!). Thank you.
