### ISSUE TITLE
Awesome Window Manager appends same options to command line upon restarts

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#60229]
## Issue description
On NixOS 19.03

When running the Awesome Window Manager, if it's restarted within the same X session (e.g. by sending a `SIGHUP` or with the default shortcut `Ctrl+Mod4+R`), the same `--search` options are added to the command line.

Example of relevant NixOS configuration:

```nix
services.xserver = {
      enable = true;

      displayManager = {
      sddm.enable = true;
     };

      desktopManager = {
            default = "none";
            xterm.enable = true;
     };

      windowManager.awesome.enable = true;
};
```

### Steps to reproduce

1. Login using `sddm` into an X session that uses the `awesome+none`
2. Open a terminal and run `ps aux | grep awesome | grep --color lgi`
3. Observe that `lgi` is highlighted twice in line with https://github.com/NixOS/nixpkgs/blob/1746dc22e6db8fdf840717ea7800bacfc2f3f199/pkgs/applications/window-managers/awesome/default.nix#L51 https://github.com/NixOS/nixpkgs/blob/1746dc22e6db8fdf840717ea7800bacfc2f3f199/pkgs/applications/window-managers/awesome/default.nix#L52
4. Restart awesome, e.g. by pressing `Ctrl+Mod4+R`
5. Run `ps aux | grep awesome | grep --color lgi`
6. Observe that the number of times that `lgi` is highlighted has doubled, i.e. the `--search` options have been appended to the previous command.

Note that `windowManager.awesome.luaModules` is not affected, i.e. the `--search` options for those modules is not re-appended on restarts:

https://github.com/NixOS/nixpkgs/blob/b3d9da5f0a3d2e967ce9a6f7b349150964a14493/nixos/modules/services/x11/window-managers/awesome.nix#L58

## Technical details
NixOS
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36-hardened, NixOS, 19.03.172312.330b9fac600 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172312.330b9fac600"`
 - channels(user): `"unstable-19.09pre176329.d2602779281"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

awesome 4.3 (Too long)
 - Compiled against Lua 5.2.4 (running with Lua 5.2)
 - D-Bus support: ✔
 - execinfo support: ✔
 - xcb-randr version: 1.6
 - LGI version: 0.9.2

**Comment by psychon** [comment]
AwesomeWM restarts via `execvp(argv[0], argv)`. In NixOS, `wrapProgram` is used to generate a wrapper around the real binary. `wrapProgram` calls `makeWrapper` with `--argv0 '$0'`. I guess this is what makes awesomeWM run the wrapper again on restart. Without this `--argv0`
1. awesomeWM would directly restart itself instead of the wrapper, I think.
2. the output in tools like `top` would change, showing the real binary instead of the wrapper as the command being run (this could be an unintended side effect of dropping the `--argv0` argument).

**Comment by stefano-m** [comment]
I see. I am not sure about actual consequences of this behavior, but it seems to worth a fix.

Would using `makeWrapper` directly rather than `wrapProgram` help?

**Comment by stefano-m** [comment]
@psychon I have tried this out and

> 1. awesomeWM would directly restart itself instead of the wrapper, I think.

That is correct, and in fact the issue of the repeated `--search` options disappears altogether

> 2. the output in tools like top would change, showing the real binary instead of the wrapper as the command being run (this could be an unintended side effect of dropping the `--argv0` argument).

This does not happen with my patch (see below) where I rename the executable the same way `wrapProgram` does, but I use `makeWrapper` *without* the `--argv0` argument.

(Incidentally, I have discovered that calling `awesome-client` creates a file `~/..awesome-client-wrapped_history`, obviously because of the wrapper)

```diff
diff --git a/pkgs/applications/window-managers/awesome/default.nix b/pkgs/applications/window-managers/awesome/default.nix
index fa86257a1a9..d18fe85e891 100644
--- a/pkgs/applications/window-managers/awesome/default.nix
+++ b/pkgs/applications/window-managers/awesome/default.nix
@@ -48,7 +48,10 @@ with luaPackages; stdenv.mkDerivation rec {
   LUA_PATH  = "${lgi}/share/lua/${lua.luaversion}/?.lua;;";
 
   postInstall = ''
-    wrapProgram $out/bin/awesome \
+    # Don't use wrapProgram or awesome will duplicate its arguments at every
+    # restart
+    mv "$out/bin/awesome" "$out/bin/.awesome-wrapped"
+    makeWrapper "$out/bin/.awesome-wrapped" "$out/bin/awesome" \
       --set GDK_PIXBUF_MODULE_FILE "$GDK_PIXBUF_MODULE_FILE" \
       --add-flags '--search ${lgi}/lib/lua/${lua.luaversion}' \
       --add-flags '--search ${lgi}/share/lua/${lua.luaversion}' \
```

What do you think? @dtzWill could this be merged (I already have the commit so submitting a PR would be quick)

**Comment by psychon** [comment]
> or awesome will duplicate its arguments at every

Well, I'd prefer a version that sounds less like "awesome is doing something wrong". How about "or the wrapper will duplicate the --search arguments every restart"?

**Comment by stefano-m** [comment]
> How about "or the wrapper will duplicate the --search arguments every restart"?

Sure, your wording make definitely more sense and is more accurate.

If that's OK, I can prepare a PR.
