### ISSUE TITLE
NixOS 19.03: Awesome Window Manager exposes lgi incorrectly in its LUA_PATH (regression)

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#60232]
Cc @psychon and @blueyed who might have some insights in regard

## Issue description

Since NixOS 19.03 the environment in the Awesome Window Manager exposes lgi incorrectly in its LUA_PATH (I think).

The problem was solved in NixOS 18.09 in https://github.com/NixOS/nixpkgs/commit/5465d6f7ded73a815b4ed3953f6d00d0aa563ac3 but the the code was added again in NixOS 19.03 in https://github.com/NixOS/nixpkgs/commit/17d3eb2c9af719eac3668e7b88d65eca93750b41.

It seems to me that the correct way of adding lgi to `LUA_PATH` (if at all needed) would be something like:

```nix
--prefix LUA_PATH ';'  "${lgi}/share/lua/${lua.luaversion}/?/init.lua;${lgi}/share/lua/${lua.luaversion}/?.lua"
```

This is because lgi's modules are supposed to be imported using the lgi "namespace", e.g.

```lua
lgi_enum = require('lgi.enum')  -- OK
lgi_enum = require('enum')      -- NOT OK
```

A negative side effect is that there may be name clashes with other lua modules.

I have come across this because I use a widget that has a transitive dependency on a module named `enum.lua`, and unfortunately lgi has a file with the same name that appears in the `LUA_PATH` before it, causing an error when I start Awesome. At the moment I have a rather drastic workaround where I rewrite `package.path` in my `~/.config/awesome/rc.lua` so that the correct library can be found.

### Steps to reproduce

1. Configure NixOS 19.03 with awesome and extra lua modules that have a name conflict with lgi's modules

```nix
 services.xserver = {
   windowManager = {
      awesome = {
        enable = true;
        luaModules = with pkgs.extraLuaPackages; [ # need overalys for this to work!
          dbus_proxy
          enum
          power_widget
          upower_dbus
        ];
      };
    };
};

  nixpkgs.overlays = with builtins; [
    (
      import (fetchGit {
        url = "https://github.com/stefano-m/nix-stefano-m-nix-overlays.git";
        rev = "9e489c50134b58fb9c4d14142c474ff792856146";
      })
    )
  ];
```

2. Configure `~/.config/awesome/rc.lua` to use the modules

```lua
local power = require("power_widget")
```

3. Start awesome by logging in with your display manager (I use `sddm`)
4. Observe that Awesome fails to start with  `attempt to call field 'new' (a nil value)`. In this case this is because `power_widget` transitively calls https://github.com/stefano-m/lua-upower_dbus/blob/8ef01571d13c3dd17e87e6ccec9aaccea22dd710/src/upower_dbus/init.lua#L74 `upower.enums.DeviceType = enum.new("DeviceType", DeviceType)` but lgi's `enum` module is found instead.

## Technical details
NixOS 19.03
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36-hardened, NixOS, 19.03.172312.330b9fac600 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172312.330b9fac600"`
 - channels(stefano): `"unstable-19.09pre176329.d2602779281"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

awesome 4.3 (Too long)
- Compiled against Lua 5.2.4 (running with Lua 5.2)
- D-Bus support: ✔
- execinfo support: ✔
- xcb-randr version: 1.6
- LGI version: 0.9.2

**Comment by teto** [comment]
the best way would be to use lua environments I had some code somewhere I could push for you to test.

**Comment by dtzWill** [comment]
>  lua environments

This seems like the way to solve #60229 as well.  Would `lua.withPackages` do the trick, or does a "lua environment" do something more?

**Comment by teto** [comment]
they are equivalent in my head :p I have yet to upgrade some of my old lua changes so this might not be enough (I had some changes for the lua module but it's 1 year old) but that was the spirit: https://github.com/teto/nixpkgs/commit/01fa2bcd0a6b64fda57446deea7f3840963b2db3

**Comment by psychon** [comment]
> Cc @psychon and @blueyed who might have some insights in regard

Well... I wrote  5465d6f so that one looks fine to me, of course. ;-)
No idea what changed so that 17d3eb2 is necessary or why things would fail without it. Especially the `?.lua` that it adds to `LUA_PATH` during the build seems fishy to me. Does this perhaps simply want to append `;;` to the env var instead? This is interpreted by Lua as "add the default search path here" (which does indeed contain `?.lua`, but also contains more).
Also no idea why 17d3eb2 has to add `LUA_PATH` and `LUA_CPATH` to the wrapper to make things work. `--search` is supposed to handle this and from the top of my head, the only difference should be in `awesome --version` (this tries to `require("lgi.version")`, but does not honor `--search`, so this `require` could fail; everything else is "normal startup" and that definitely honors `--search`).

> the best way would be to use lua environments I had some code somewhere I could push for you to test.

Uhm. So what exactly does `lua.withPackages` do?
https://github.com/NixOS/nixpkgs/blob/e52396ce2c046014314749dc77f695f5c9d8eb47/pkgs/development/interpreters/lua-5/with-packages.nix
Does it simply add something to the env during build? If so, I do not understand what difference that could make here.

**Comment by stefano-m** [comment]
Not sure what lua environments are and how they could help here.

@psychon is an authoritative source regarding Lua and Awesome, so I'd follow his advice.

Would you be willing to accept a PR with the changes suggested to restore the previous behaviour?

Thanks

**Comment by dtzWill** [comment]
That would be great, yes! I expect accepting it to be no problem, but will want to take a look at it first ;).
The `?.lua` added during the build was my non-lua-expert attempt to fix build failure that occurred without it re:finding files in the awesome source itself.
It's possible I was overestimating the significance of awesome's self-diagnostics as you mention, sorry.  Fixes welcome, thanks!

**Comment by stefano-m** [comment]
@dtzWill I will see what I can do, I will ping back once I have something.

**Comment by stefano-m** [comment]
Although PR #60329 has been merged to master, I'd like to wait that the change is ported back to the 19.03 branch before closing this issue.

If there's anything I can do in regard, please do let me know,

Thanks
