### ISSUE TITLE
[Discussion] gzip and brotli for webapps

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#60230]
## Issue description

nginx supports serving static [gzip](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) and [brotli](https://github.com/google/ngx_brotli#brotli_static) files.
Essentially, when opening a file, it looks for the corresponding `.gz` or `.br` file and serves this instead.
This means the file can be served compressed without the overhead of on-the-fly compression.

Currently, these files don't exist in our webapp packages. Generating them for every package would probably introduce a high load to Hydra, so compressing them by default might be a bad idea.
So having a `compressBrotli` and `compressGzip` option per package (default: `false`) could solve this problem. Administratrators could override the corresponding packages if they's like to (building webapps locally should not be too expensive).
Of course, this only makes sense for static assets (.css, .js, .xml, .json).

So what do you think about this? Is it worth it? Do you see problems with this approach?

**Comment by symphorien** [comment]
If I understand the problem right, a function like this could be enough (untested)
```nix
{
compressAssets = drv: runCommand "${drv.name}-compressed" {} ''
cp -r ${drv} $out
chmod +w -R $out
find $out -type f -exec ${gzip}/bin/gzip '{}' \;
'';
}
```
You would then use `compressAssets foo` instead of `foo`.
