### ISSUE TITLE
FSharp is out of date

### ISSUE THREAD

**Issue by brettgilio** [NixOS/nixpkgs#60242]
## Issue description

FSharp has two outputs, one for 4.0.0 and one for 4.1

I do not know enough about Nix at the present to try and make a new output for the most recent 4.5. If somebody is free, could this be done?

Thanks.

## Technical details

brettg@guixsd ~/Repos/fst [env]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/n8ryapl9c33h9w7ffrk7s592ah38a7cj-nix-info
copying path '/nix/store/n8ryapl9c33h9w7ffrk7s592ah38a7cj-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36-gnu`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(brettg): `"nixpkgs-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/home/brettg/.nix-defexpr/channels/nixpkgs`

**Comment by c0bw3b** [comment]
ping @7c6f434c @thoughtpolice  as maintainers

**Comment by 7c6f434c** [comment]
Hm. Mono packaging has changed a lot since I last touched fsharp…

**Comment by delneg** [comment]
Any progress on this ?
I've tried compiling https://github.com/fsharp/fsharp/archive/4.5.0.tar.gz with pkgs.mono , but had not luck.
Seems like the packaging has changed a lot.

**Comment by Rizary** [comment]
still important to me

**Comment by p-h** [comment]
The old fsharp/fsharp repo is deprecated. As I understand it, F# is now shipped as part of the standard dotnet-sdk. Maybe we should remove the fsharp package altogether?

**Comment by samuela** [comment]
F# 5.0 is also out as of Nov 2020. It would be great if we could package it.

**Comment by samuela** [comment]
> The old fsharp/fsharp repo is deprecated. As I understand it, F# is now shipped as part of the standard dotnet-sdk. Maybe we should remove the fsharp package altogether?

Is there a reason to keep `fsharp`? I can't really think of one. Also the new `dotnet-sdk_5` ships with F# 5.0!

**Comment by 7c6f434c** [comment]
Maybe make it a deprecated alias to `dotnet-sdk_5`?

**Comment by delneg** [comment]
Definitely should be closed due to dotnet 5 & 6 releases

**Comment by ruuda** [comment]
The `fsharp` package is still there though, and it confused me at least. It may be good to remove, or at least add a comment to tell people that `dotnet-sdk` is more likely what they want.
