### ISSUE TITLE
[19.03] buildPythonPackage/buildPythonApplication no longer provides pip nor other CLI executables in buildInputs or propagatedBuildInputs

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#60243]
Since upgrading to using 19.03, nix-shells that previously worked no longer did.

I discovered that first pip was missing. And to bring pip back you need to explicitly put it in `nativeBuildInputs`. Furthermore to get any CLI executables out like the executables in `csvkit`, you also have to put that into `nativeBuildInputs` or `propagatedNativeBuildInputs`.

Packages that provide executables to be used cannot just be put into `propagatedBuildInputs` as they could be before, they now have to be also in `nativeBuildInputs` as well. If they are python packages, and you want to use their CLI executables and libraries, where are you meant to put them? The manual does not explain this. https://nixos.org/nixpkgs/manual/#building-packages-and-applications

Also why was this change made? Normal stdenv.mkDerivation still ensures that CLI executables are usable when they are inside the `buildInputs`.

**Comment by CMCDragonkai** [comment]
This might be related: https://github.com/NixOS/nixpkgs/issues/28325

But that issue hasn't been closed yet. Does that mean that change has already been applied to the python utilities in Nix but not to `mkDerivation` by default?

**Comment by dotlambda** [comment]
That's intentional and due to https://github.com/NixOS/nixpkgs/pull/54182. Nix-shell should resemble as closely as possible to what you get when building the derivation. If you want to disable it, look at https://github.com/NixOS/nixpkgs/pull/60178.

**Comment by dotlambda** [comment]
Btw, this is mentioned in https://nixos.org/nixos/manual/release-notes.html#sec-release-19.03-incompatibilities.

**Comment by CMCDragonkai** [comment]
@dotlambda So what does that mean for Python dependencies that have both library and executables? Does that mean you have to duplicate them into the `nativeBuildInputs` and `propagatedBuildInputs`?

**Comment by CMCDragonkai** [comment]
@dotlambda Do you know the answer to that question?
