### ISSUE TITLE
windowmaker not properly defined

### ISSUE THREAD

**Issue by bstrik** [NixOS/nixpkgs#6025]
New user of NixOS so bare with me.

I've noticed that I can not use: "services.xserver.windowManager.windowmaker.enable = true".
I get the following error:

error: The option `services.xserver.windowManager.windowmaker' defined in `/etc/nixos/configuration.nix' does not exist.
(use ‘--show-trace’ to show detailed location information)

I've tried to do some research and I think this is because in the following file:

nixpkgs/nixos/modules/services/x11/window-managers/default.nix

windowmaker is not defined in the imports.

Can someone please look into this problem or help me find a solution.

**Comment by lethalman** [comment]
Comment here to ask attention from committers: https://github.com/NixOS/nixpkgs/commit/c6f28f988c930329db62cd3054c206d515b2ecb3

**Comment by bstrik** [comment]
I will do that, thanks!!

**Comment by vcunat** [comment]
It is still a valid bug.

**Comment by bstrik** [comment]
Thank you for re-opening.

**Comment by layus** [comment]
Seems like this was closed by  #6072 or #4066, right ?

@bstrik, could you confirm it work correctly now and close the issue ?

**Comment by layus** [comment]
@vcunat, do you think this bug is _still_ valid ?

**Comment by bstrik** [comment]
This bug is fixed now. Thank you.
