### ISSUE TITLE
nodejs 12 missing

### ISSUE THREAD

**Issue by janat08** [NixOS/nixpkgs#60266]
## Issue description
nodejs version 12 missing

**Comment by janat08** [comment]
I'm not sure where it gets the sha number for package releases. I imagine you could pretty much set up CD machine to keep it up to date.

**Comment by marsam** [comment]
Nodejs 12 is already in staging (See: https://github.com/NixOS/nixpkgs/pull/60130), eventually it will land to master

**Comment by FRidh** [comment]
Closing because it's in staging.
