### ISSUE TITLE
matterbridge service does not allow package to be overriden

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#60269]
Usually, services allow overriding the package they use. The Matterbridge service lacks this feature, which would be quite useful to allow user patching of the Matterbridge source.

Tentative patch (not tested):
```patch
diff --git a/nixos/modules/services/networking/matterbridge.nix b/nixos/modules/services/networking/matterbridge.nix
index 1fd63348c16..d1389bb89b2 100644
--- a/nixos/modules/services/networking/matterbridge.nix
+++ b/nixos/modules/services/networking/matterbridge.nix
@@ -19,6 +19,13 @@ in
     services.matterbridge = {
       enable = mkEnableOption "Matterbridge chat platform bridge";
 
+      package = mkOption {
+        type = types.path;
+        default = pkgs.matterbridge;
+        defaultText = "pkgs.matterbridge";
+        description = "The Matterbridge package.";
+      };
+
       configPath = mkOption {
         type = with types; nullOr str;
         default = null;
@@ -109,7 +116,7 @@ in
       serviceConfig = {
         User = cfg.user;
         Group = cfg.group;
-        ExecStart = "${pkgs.matterbridge.bin}/bin/matterbridge -conf ${matterbridgeConfToml}";
+        ExecStart = "${cfg.package.bin}/bin/matterbridge -conf ${matterbridgeConfToml}";
         Restart = "always";
         RestartSec = "10";
       };

```

Cc @ryantm

**Comment by ryantm** [comment]
Sure @sbourdeauducq a tested patch like would be a good PR.

**Comment by JohnAZoidberg** [comment]
There was a discussion a while back about whether we want to add `package` options to all modules or only allow override using overlays and package overrides.
Has that been resolved and we're now in favor of adding these options?

**Comment by ryantm** [comment]
@Infinisil , do you know the answer to @JohnAZoidberg 's question?

**Comment by Infinisil** [comment]
That was https://github.com/NixOS/nixpkgs/issues/50476

There were a lot of people who were for *always* adding such an option. Some people agreed with it having to have at least a good reason (including me).

In this particular case you could just use an overlay to change the package:
```nix
{
  nixpkgs.overlays = [(self: super: {
    matterbridge = super.matterbridge.overrideAttrs (old: {
      patches = old.patches or [] ++ [ ... ];
    });
  })];
}
```

And because nothing other than the service depends on that package, this won't cause any rebuilds other than for matterbridge itself.

But if you feel like an option would be worthwhile, feel free to PR it.

**Comment by sbourdeauducq** [comment]
> There were a lot of people who were for always adding such an option. Some people agreed with it having to have at least a good reason (including me).

Okay, fair enough. Thanks for the detailed answer.
