### ISSUE TITLE
Enhance the Agda builder

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#60271]
For my sins, I'm trying to integrate some Agda code into the testing part of a production system. I'd like to use the Agda builder from Nixpkgs, but it could do with a few enhancements. I thought I'd open an issue discussing those so I can see whether other people agree before I try to actually implement anything.

Things I would like:
- Support for library files.
    - The current builder passes all dependencies using `-i`, we could probably use `AGDA_DIR` or `--library-file` now for many libraries.
    - Would need to think of how to handle fallback for libraries that don't use library files yet.
- `agdaWithPackages`
    - Obviously we'd want to preserve the existing ability for emacs to pick things up, but I think might be easier with `AGDA_DIR` now.
- Easier configuration of build flags.
    - It's a bit annoying to try and override `buildFlags` at the moment.
- Some simple enable/disable options for generating html/latex literate Agda output, and for producing compiled outputs via one of the backends.

Mentioning some people who seem to be involved: @Fuuzetsu @siddharthist

**Comment by Fuuzetsu** [comment]
I haven't used Agda for few years so I'm not really up to date on the current build system in nix but the suggestions sound fine I think.

**Comment by siddharthist** [comment]
See also: https://github.com/srdqty/nix-agda-with-packages

**Comment by turion** [comment]
@langston-barrett can your project be merged into `nixpkgs`? Also, there is a PR here: https://github.com/NixOS/nixpkgs/pull/39318
