### ISSUE TITLE
gnome-software: Failed to activate service 'org.freedesktop.PackageKit': timed out

### ISSUE THREAD

**Issue by angristan** [NixOS/nixpkgs#60274]
## Issue description

Opening gnome-softwares shows this:

<img width="1440" alt="Screenshot 2019-04-26 at 18 12 56" src="https://user-images.githubusercontent.com/11699655/56822005-1a559700-6850-11e9-9cb1-c528a81fa5ae.png">

And the whole app is empty.

Journald logs:

```
Apr 26 18:18:35 nixos dbus-daemon[778]: [system] Failed to activate service 'org.freedesktop.PackageKit': timed out (service_start_timeout=25000ms)
Apr 26 18:18:35 nixos .gnome-software[1533]: not GsPlugin error g-dbus-error-quark:20: Error calling StartServiceByName for org.freedesktop.PackageKit: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.PackageKit': timed out (service_start_timeout=25000ms)
```

### Steps to reproduce

Use GNOME (3.32.1) on unstable.

My GNOME-related config:

```nix
  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.displayManager.gdm.wayland = false;
  environment.gnome3.excludePackages = with pkgs.gnome3; [
    epiphany
    evolution
    gnome-maps
    accerciser
  ];
  services.gnome3.gnome-keyring.enable = true;
  services.gnome3.chrome-gnome-shell.enable = true;
  services.gnome3.gvfs.enable = true;
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.9, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1"`
 - channels(stanislas): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by hedning** [comment]
Probably fixed by https://github.com/NixOS/nixpkgs/pull/60146

**Comment by angristan** [comment]
Thanks. I searched for packagekit but didn't find this PR.

**Comment by worldofpeace** [comment]
Yes https://github.com/NixOS/nixpkgs/pull/60146 fixed this issue, one of things I tested.

Though there's a new error now
![Screenshot from 2019-04-30 14 43 21](https://user-images.githubusercontent.com/28888242/56985562-9e609500-6b56-11e9-8235-351d207343af.png)
But I'm pretty sure that's expected because the backend does not support that.
