### ISSUE TITLE
Unable to reset password from Spotify app

### ISSUE THREAD

**Issue by scalavision** [NixOS/nixpkgs#60306]
## Issue description

When pressing reset password button, nothing happens. When running Spotify from command line, these errors occurs:

```bash
/nix/store/9iyjbk83bi8fn4ydf9v2hjasgy33nv3m-curl-7.64.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0427/071846.984588:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process
```
People can always reset their password through the web site, so I guess this issue is not too severe though ..

### Steps to reproduce

Open the Spotify app, without being already logged in

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev
copying path '/nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.110, NixOS, 18.09.2474.222950952f1 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2474.222950952f1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
Cc @timokau

**Comment by timokau** [comment]
There is some bug with spotify for linux that makes some buttons inaccessible by mouse. The dropdown menu that gives access to settings is affected by this. That might also cause this issue, although I haven't tested it.

One workaround is to instead navigate by keyboard: Highlight the button using the arrow keys, then press enter. There is already an issue somewhere that mentions the workaround, but I can't find it right now.

**Comment by scalavision** [comment]
I am closing this, seems not related to NixOS.
