### ISSUE TITLE
1Password doesn't build due to hash mismatch

### ISSUE THREAD

**Issue by kevingriffin** [NixOS/nixpkgs#60317]
## Issue description
1Password 0.5.5 (the latest version as of issue creation) doesn't install on Darwin due to a hash mismatch.

Addressed in https://github.com/NixOS/nixpkgs/pull/60316

### Steps to reproduce

`nix-env -iA nixpkgs._1password` on Darwin.

## Technical details
```nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixpkgs-19.09pre175347.02bb5e35eae"`
 - channels(kevin): `"darwin, nixpkgs-unstable-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/Users/kevin/.nix-defexpr/channels/nixpkgs````

**Comment by marsam** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/60316
