### ISSUE TITLE
better support for customization of CXXFLAGS and debugging

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#6033]
Currently NixOS builds all packages without debug symbols. I do some development in NixOS and it is very inconvenient that gdb can not even show backtraces right. Currently I do some hacks to specify NIX_CFLAGS_COMPILE/NIX_LDFLAGS on per package basis.

Other distributions strips debug symbols into separate packages (-dbg) that can be installed separately. It would be great if NixOS had a parameter of a package whether to build with debug symbols or not.

Probably it would be even better if it is allowed to override in NixOS specific compiler flags. Here is a list of options I think are useful to override:

```
-g/-g0 -- for debug symbols
-Og -- for better debugging
-fno-omit-frame-pointer -- for tools that don't support dwarf
-fsanitize=address/-fsanitize=memory/... -- for debugging
```

Also I think it would be useful to have a option that puts source files that are referenced in debug info into /nix/store, so user is able to step in debugger a code of libraries.

**Comment by copumpkin** [comment]
I don't know what it's like in linux land, but on Mac OS, debug builds produce separate .dSYM packages of DWARF info. In a nix + Mac OS world, those DWARF files could be in a separate output of a derivation, so they could be GC'd independently.

**Comment by jagajaga** [comment]
Why can't you use `overrideDerivation`?

**Comment by jagajaga** [comment]
Issue solved?

**Comment by Profpatsch** [comment]
Can be closed @jagajaga

**Comment by gleber** [comment]
ping?
