### ISSUE TITLE
meta.platforms is broken

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#60345]
Once upon a time, `meta.platforms` contained more-or-less sensible information:
```
$ nix-env -f channel:nixos-17.09 -qaA geeqie --json | jq .[].meta.platforms
[
  "aarch64-linux",
  "armv5tel-linux",
  "armv6l-linux",
  "armv7l-linux",
  "mips64el-linux",
  "i686-linux",
  "x86_64-linux"
]
```

Now, however, it contains a lot of irrelevant information, and **omits the thing that matters**, namely the platform names (e.g. `x86_64-linux`):
```
$ nix-env -f channel:nixos-19.03 -qaA geeqie --json | jq .[].meta.platforms
[
  {
    "abi": {
      "_type": "abi",
      "name": "gnu"
    },
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  },
  {
    "abi": {
      "_type": "abi",
      "float": "soft",
      "name": "gnueabi"
    },
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  },
  {
    "abi": {
      "_type": "abi",
      "float": "hard",
      "name": "gnueabihf"
    },
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  },
  {
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  }
]
```

This broke the display of supported platforms at https://nixos.org/nixos/packages.html. It also seems horribly over-engineered to me. (I mean, it's one thing to be able to map platform types to information like executable formats, but it's going rather too far to use that information to *identify* the platform.)

**Comment by samueldr** [comment]
PR #34444 has the commit changing the behaviour for meta.platforms. Precisely c26252af3e8a102e8ac7ab67ae3ceb2c19845cac

cc @Ericson2314

**Comment by matthewbauer** [comment]
https://github.com/NixOS/nixpkgs/pull/60349 should fix this

**Comment by Ericson2314** [comment]
This was done because we needed finer-grained filters than what the `system` attribute provides. I reused how the `is*` attributes are made to get something sufficiently expressive and still reflectable. (C.f. how screwed the website would be if we used arbitratry functions—no way to reflect.)

I'm opening to changing to something else, but it can't go back to a simple list. There are wayyyy to many platforms (combinatorial explosion) for that to work.

On the other hand, given a fixed list of, say, cached platforms, I can filter them. That would give the website something to display again.

**Comment by samueldr** [comment]
Would it be possible to have a function with inputs a list of human-friendly platforms, which would be used to list the "non-encompassing" platforms only?

e.g.

```
repl> plats = ["all" "unix" "x86_64-linux" "i686-linux" "aarch64-linux" "x86_64-darwin"]
repl> humanisePlatforms plats platforms.unix
["unix"]
repl> humanisePlatforms plats platforms.all
["all"]
repl> humanisePlatforms plats [ platforms.linux ]
["x86_64-linux" "i686-linux" "aarch64-linux"]
repl> humanisePlatforms plats [ "x86_64-linux" "x86_64-darwin" ]
["x86_64-linux" "x86_64-darwin"]
```

The main idea being that if it is one of those "big" platforms which brings in all, only list the bigger one. Not sure if the demo entirely makes sense, and how much of this is possible or not.

Such a function would be used to directly map into the user-friendly list for the website.

Additionally, it would be nice to have a `mechanisedPlatforms` with the same inputs, but returning *all* matching platforms, not only the minimum set to represent them. This could be used in a next iteration of the package search to filter e.g. by `x86_64-darwin` and show only the packages matching it, without the website having to know about how platforms map.
