### ISSUE TITLE
Can we make "mtr" use a setuid wrapper?

### ISSUE THREAD

**Issue by ctheune** [NixOS/nixpkgs#6034]
I guess the change would basically mean:

```
security.setuidPrograms = [ "mtr" ];
```

Is there anything speaking against this?

**Comment by wkennington** [comment]
I'd prefer to leave as few setuid binaries as possible on the system and
let individuals enable setuid for things like MTR.

**Comment by ctheune** [comment]
Your answer tells me there's an option for me to make it setuid that I'm not aware of a way to customize this per installation.

I'm currently using nix / nixpkgs on OS X. I saw the helper code but I'm not good enough yet to infer how to apply this for an installation I did via 'nix-env -i mtr'. Mind pointing me in the right direction for individually enabling setuid?

**Comment by wkennington** [comment]
As far as I am aware setuid is only something that can be done in NixOS by
creating wrappers in /var/setuid-wrappers using the setting you were
talking about in your previous message.

**Comment by iElectric** [comment]
You could refactor nixos/modules/security/setuid-wrappers.nix to get that support outside of NixOS, but  the wrappers would have to be stored outside /nix/store

**Comment by volth** [comment]
```mtr``` does not required setuid to work, ```CAP_NET_RAW``` capability should be enough: https://lists.opensuse.org/opensuse-packaging/2014-01/msg00125.html
