### ISSUE TITLE
virtualbox source and extension pack download site down

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/nixpkgs#60350]
## Issue description

The virtualbox download site is apparently down:

https://forums.virtualbox.org/viewtopic.php?f=1&t=92880

As a workaround, you can use an `http` URL instead of `https`.  For instance, to download the extension pack from 19.03, normally you'd use the following URL:

```console
$ nix-prefetch-url https://download.virtualbox.org/virtualbox/5.2.26/Oracle_VM_VirtualBox_Extension_Pack-5.2.26.vbox-extpack
```

Instead, you can use the following URL:

```console
$ nix-prefetch-url http://download.virtualbox.org/virtualbox/5.2.26/Oracle_VM_VirtualBox_Extension_Pack-5.2.26.vbox-extpack
```

### Steps to reproduce

Hopefully this will be fixed on Monday when people at Oracle come back to work.

**Comment by geekware** [comment]
@cdepillabout thx!

**Comment by volth** [comment]
It makes questionable the recent treewide ```s/http/https/g```

**Comment by cdepillabout** [comment]
@volth I'm not aware of the recent treewide change from `http` URLs to `https` URLs, but in this case it really does just seem like a mistake at Oracle.

The "correct" url is https://download.virtualbox.org.  But apparently the people at Oracle renewed the SSL cert incorrectly or something.  It seems like everyone is hoping it gets fixed sometime this week.

**Comment by 1000101** [comment]
Yeah, they seem to have used certificate valid for download.oracle.com not for download.virtualbox.org domain.

> The "correct" url is https://download.virtualbox.org. But apparently the people at Oracle renewed the SSL cert incorrectly or something. It seems like everyone is hoping it gets fixed sometime this week.

**Comment by 1000101** [comment]
Ok, they've fixed the certificate, this issue can be closed.
