### ISSUE TITLE
Opera web browser is outdated

### ISSUE THREAD

**Issue by jackTaw88** [NixOS/nixpkgs#60369]
Hi,

Opera web browser is outdated. Thus it's vpn does not work. The vpn API has been changed on new years. I am reading from reddit: https://www.reddit.com/r/operabrowser/comments/bfk1ba/vpn_not_working_to_anyone_else/

I will be happy if someone will update it.

Thank you

**Comment by c0bw3b** [comment]
There is PR #58735 but it needs some more work
