### ISSUE TITLE
gnucash: cannot open help files

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixpkgs#60361]
## Issue description

`gnucash` application can't find help files

### Steps to reproduce

Install `gnucash` from nixos release channel, go to main application screen, click on Help menu and select either "tutorial and concepts guide" or "contents". Application complains with a modal reporting "GnuCash could not find the files for the help documentation. This is likely because 'gnucash-docs' package is not installed."

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172361.cf3e277dd0b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172361.cf3e277dd0b, nixos-hardware"`
 - channels(zarel): `"nixpkgs-19.09pre174594.0c0954781e2"`
 - nixpkgs: `/home/zarel/.nix-defexpr/channels/nixpkgs`

**Comment by zarelit** [comment]
As a workaround: the very same documentation is available online at this address: https://gnucash.org/docs.phtml

**Comment by zarelit** [comment]
As a workaround: the very same documentation is available online at this address: https://gnucash.org/docs.phtml

**Comment by zarelit** [comment]
still happening

**Comment by ehmry** [comment]
Pinging maintainers @peti @domenkozar

**Comment by balodja** [comment]
There is more to it. Gnucash installs its document files into plain `/usr/share/doc` without `gnucash` subdirectory. Because of that common files like `AUTHORS` do have collisions with analogous files in other packages.

**Comment by balodja** [comment]
Documentation for Gnucash is a separate project: https://github.com/Gnucash/gnucash-docs

It should be separately build and installed in order for help files to be available.

**Comment by zarelit** [comment]
I've built the documentation and put the documentation in the XDG_DATA_DIRS. I can browse the manual and the tutorial via `yelp` but running gnucash in debug mode says "Unsupported action" and according to strace the application doesn't try to open the documentation directories... and the same happens for evince (can see the documentation in yelp but the application won't display it), maybe it's the same issue

**Comment by sersorrel** [comment]
issue remains.

**Comment by zarelit** [comment]
@nevivurn Thank you for the fix! Do you think is there a way to warn the user about not having yelp in a profile?

**Comment by nevivurn** [comment]
> @nevivurn Thank you for the fix! Do you think is there a way to warn the user about not having yelp in a profile?

I don't think there are any convenient/good ways to tell the user about it. At best, we could add it to the description?

**Comment by winny-** [comment]
If gnucash documentation depends on yelp, would it make sense to express this dependency in the gnucash derivation?

**Comment by Atemu** [comment]
Apparently, it must also be in MIME. This sort of stupid behaviour looks like an upstream bug to me.

**Comment by sersorrel** [comment]
If an application shipped its help files as HTML and required you to have a web browser installed to view them, I think it would be silly to add a dependency on any specific web browser. Likewise with help files - if (at least theoretically) Yelp is just one of several possible help file viewers, I don't think it makes sense to add a dependency on it.

A better indication of what's wrong ("you need to install a help viewer" rather than "couldn't find the docs") *would* be nice, though, which I presume is only really doable upstream.
