### ISSUE TITLE
Blueman should have a NixOS module service

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#60413]
## Issue description

Blueman package cannot just be used from when installing it from user. It is expected to be an OS level service. See: https://github.com/rycee/home-manager/issues/84

We should have a NixOS module for it: `services.blueman.enable = true;`.

### Steps to reproduce

Try installing blueman using nix-env and then run `blueman-applet`.

**Comment by emmanuelrosa** [comment]
`blueman` should work when `hardware.bluetooth.enable` is enabled. Have you tried it?

**Comment by emmanuelrosa** [comment]
`blueman` should work when `hardware.bluetooth.enable` is enabled. Have you tried it?

**Comment by CMCDragonkai** [comment]
When did this happen? I had the same problem as rycee/home-manager#84

**Comment by CMCDragonkai** [comment]
@emmanuelrosa Where does this mention blueman? https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/bluetooth.nix
