### ISSUE TITLE
plex-media-player has 2 .desktop files

### ISSUE THREAD

**Issue by angristan** [NixOS/nixpkgs#60437]
## Issue description

This is pretty confusing:

![Screenshot from 2019-04-29 23-15-09](https://user-images.githubusercontent.com/11699655/56927690-1be3c100-6ad5-11e9-931b-546e26c91a7b.png)

```sh
stanislas@nixpsla ~> find /nix/store/d50hm4vhyw0nib9zflf6nqsqyw5l7rql-plex-media-player-2.23.0.920/ -name "*.desktop"
/nix/store/d50hm4vhyw0nib9zflf6nqsqyw5l7rql-plex-media-player-2.23.0.920/share/applications/plex-media-player.desktop
/nix/store/d50hm4vhyw0nib9zflf6nqsqyw5l7rql-plex-media-player-2.23.0.920/share/applications/plexmediaplayer.desktop
```

```sh
stanislas@nixpsla ~> cat /nix/store/d50hm4vhyw0nib9zflf6nqsqyw5l7rql-plex-media-player-2.23.0.920/share/applications/plex-media-player.desktop
[Desktop Entry]
Type=Application
Exec=plexmediaplayer
Terminal=false
Name=Plex Media Player
Categories=AudioVideo;Video;Player;TV;
Icon=plex-media-player
Comment=View your media
GenericName=Media Player
```

```sh
stanislas@nixpsla ~> cat /nix/store/d50hm4vhyw0nib9zflf6nqsqyw5l7rql-plex-media-player-2.23.0.920/share/applications/plexmediaplayer.desktop
[Desktop Entry]
Version=1.0
Name=Plex Media Player
GenericName=Media Player
Comment=View your media
Exec=plexmediaplayer --fullscreen --tv
Icon=plexmediaplayer
Terminal=false
Type=Application
Categories=AudioVideo;Video;Player;TV;

Actions=TV;DesktopF;DesktopW;

[Desktop Action TV]
Name=TV
Exec=plexmediaplayer --fullscreen --tv

[Desktop Action DesktopF]
Name=Desktop [Fullscreen]
Exec=plexmediaplayer --fullscreen --desktop

[Desktop Action DesktopW]
Name=Desktop [Windowed]
Exec=plexmediaplayer --windowed --desktop
```

### Steps to reproduce

Install `plex-media-player` and try to launch it from your DE. Which icon do you click on? They both do the same thing anyway.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.9, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1, nixos-hardware"`
 - channels(stanislas): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by alexarice** [comment]
I can reproduce this issue.
I think it is caused by this line https://github.com/NixOS/nixpkgs/blob/5f4a4e938ff4f87dc048689ef360dd43dea9ac42/pkgs/applications/video/plex-media-player/default.nix#L75
Would need to have more of a look but at least one of the desktop items is coming from this line and removing it would likely solve the problem

**Comment by angristan** [comment]
Thanks! I submitted a PR to remove the custom desktop file.
