### ISSUE TITLE
Android-Studio cannot GPG sign

### ISSUE THREAD

**Issue by joncojonathan** [NixOS/nixpkgs#60433]
## Issue description
When using Android Studio it's not possible to commit to a `git` repo if your system is configured to GPG sign commits.  The commit fails with:

>0 files committed, 1 file failed to commit: Correct typo
>cannot run gpg: No such file or directory gpg failed to sign the data failed to write commit object

(Exact quote.) 

This may be related to #12551 as the behaviour is similar.

### Steps to reproduce
1. Edit file in Android Studio
1. From the VCS > Git menu choose _Commit file_
1. Add commit message
1. Click _commit_

Interestingly, the commit succeeds if done using Jetbrains IntelliJ IDEA on which Android Studio is based.

Using the _terminal_ built in to Android Studio to run `gpg` results in `bash: gpg: command not found`.  Taking `$PATH` from a shell outside of Android Studio and exporting it as `$PATH` in Android Studio allows `gpg` to be found but the commit still fails.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tadfisher** [comment]
Android Studio runs in an FHS environment, and IDEA doesn't. The derivation needs `gpg` in its inputs in order to run it within the FHS env.

**Comment by joncojonathan** [comment]
Thanks for the tip. I started to look at the differences but didn't get
very far. I might look at supplying a patch.

**Comment by primeos** [comment]
As soon as #61839 hits `nixos-unstable` this should be fixed (I quickly verified it - just in case).

Thanks for your report and feel free to reopen, if I missed something.

**Comment by joncojonathan** [comment]
Excellent, this seems to have fixed the issue.  Many thanks.
