### ISSUE TITLE
Kupfer 319 fails to build in unstable

### ISSUE THREAD

**Issue by Dema** [NixOS/nixpkgs#60498]
## Issue description

Kupfer 319 fails to build with
```
Python module gi.repository.Gtk          : not found
Could not find the python module 'gi.repository.Gtk'
```

### Steps to reproduce
Run `nix-shell -p kupfer`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(dema): `""`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos```

I'm really new to NixOS, not sure how even start to try to fix it.. :)

**Comment by aanderse** [comment]
This appears to be a symptom of https://github.com/NixOS/nixpkgs/issues/56943.

Unfortunately simply applying the suggested fix did not make `kupfer` build again as there was *another* separate issue with the `kupfer` build which if I had to guess is a symptom of https://github.com/spacetelescope/hstcal/issues/359?

@jtojnar does https://github.com/NixOS/nixpkgs/commit/8b6ad155adce592fc09745999c9ddf120964f4eb seem like a reasonable fix as I don't have the time to dig into the `waf` with `python37` issue?

**Comment by jtojnar** [comment]
@aanderse Use `strictDeps = false` instead of incorrectly placing the GI to `buildInputs`. Also add a comment next to `python36Packages`.

**Comment by aanderse** [comment]
@Dema You should see the fix for this show up in the next few days after you run a system update. Thank you for reporting!
