### ISSUE TITLE
joplin-desktop is not installable

### ISSUE THREAD

**Issue by cinemast** [NixOS/nixpkgs#60533]
## Issue description
joplin-desktop is not installable resulting in the error message:

`error: selector 'joplin-desktop' matches no derivations`

### Steps to reproduce
`nix-env -i joplin-desktop`

## Technical details
```
these paths will be fetched (0.06 MiB download, 0.31 MiB unpacked):
  /nix/store/1gw1mzd1dgxv9jl9292cy89agkn6igcw-bash-interactive-4.4-p23-dev
  /nix/store/v0kpr6h52a8wl07krzm65p3r74cpvmra-stdenv-linux
copying path '/nix/store/1gw1mzd1dgxv9jl9292cy89agkn6igcw-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/v0kpr6h52a8wl07krzm65p3r74cpvmra-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.9, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1, nixpkgs-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dtzWill** [comment]
I'm not sure what'd cause that-- not using a recent channel, perhaps needing to update or something?

**Comment by JohnAZoidberg** [comment]
Do you have a channel for your user?
What does `nix-channel --list` show?

Does `nix-shell -p joplin-desktop` work?

**Comment by cinemast** [comment]
Thanks, my bad. I only had channels listed for the root user. After adding the channel to my user account and running `nix-channel --update` I could install it with `nix-env -i joplin-desktop`.
