### ISSUE TITLE
Error setting facl: Operation not permitted returned trying to USB redirect in GNOME Boxes

### ISSUE THREAD

**Issue by diamondburned** [NixOS/nixpkgs#60594]
## Issue description

Cannot USB forward to a VM in GNOME Boxes. Console returned 

```
(gnome-boxes:9974): GSpice-WARNING **: 23:31:04.839: pa_context_connect() failed: Connection refused
spice-client-glib-usb-helper: Error setting facl: Operation not permitted
```

### Steps to reproduce

1. Install `gnome3.gnome-boxes` in `environment.systemPackages`
2. Add the following to `configuration.nix`:

```nix
	security.polkit.enable = true;
```

3. Run `gnome-boxes`, install a VM and go to Properties
4. USB forward, error returned in console, Boxes said failed.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172392.6d7ed964296 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(diamond): `"nixpkgs-19.09pre177248.ed1b59a98e7"`
 - channels(root): `"nixos-19.03.172392.6d7ed964296, nixpkgs-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/home/diamond/.nix-defexpr/channels/nixpkgs`

My `configuration.nix` file: https://gitlab.com/diamondburned/dotfiles/blob/master/Scripts/nix/configuration.nix

**Comment by worldofpeace** [comment]
Problem sounds to be in `spice-gtk`.

There's this comment in the expression that sounds relevant
```
# If this package is built with polkit support (withPolkit=true),
# usb redirection reqires spice-client-glib-usb-acl-helper to run setuid root.
# The helper confirms via polkit that the user has an active session,
# then adds a device acl entry for that user.
# Example NixOS config to create a setuid wrapper for the helper:
# security.wrappers.spice-client-glib-usb-acl-helper.source =
#   "${pkgs.spice-gtk}/bin/spice-client-glib-usb-acl-helper";
# On non-NixOS installations, make a setuid copy of the helper
# outside the store and adjust PATH to find the setuid version.
```

So I guess you need an `setuid` wrapper, though I don't see where in the expression it's ensured to use this (guess we just hope that one's in PATH)

#39618 is relevant so maybe try adding
```
security.wrappers.spice-client-glib-usb-acl-helper.source = "${pkgs.spice-gtk}/bin/spice-client-glib-usb-acl-helper";
```

Looks like fedora uses `setuid` https://src.fedoraproject.org/rpms/spice-gtk/blob/master/f/spice-gtk.spec#_160
also a meson flag for the helper directory https://src.fedoraproject.org/rpms/spice-gtk/blob/master/f/spice-gtk.spec#_128.

###### Next [todo](https://gitlab.freedesktop.org/spice/spice-gtk/blob/v0.36/NEWS#L4)

**Comment by diamondburned** [comment]
This worked! Is there any ETA to a fix for this? Will this be fixed in SPICE or in Nixpkgs?

**Comment by worldofpeace** [comment]
The process outlined in that comment just needs to be turned into a module as mentioned in https://github.com/NixOS/nixpkgs/issues/39618

For people who want to use this now, they just need
```
environment.systemPackages = [ pkgs.spice-gtk ];
security.wrappers.spice-client-glib-usb-acl-helper.source = "${pkgs.spice-gtk}/bin/spice-client-glib-usb-acl-helper";
```

If they're using polkit.

If not they'll have to do what's outlined in https://github.com/NixOS/nixpkgs/blob/3e950d584c8186239809e4d101e70e083ea9e9e0/pkgs/development/libraries/spice-gtk/default.nix#L17

> Is there any ETA to a fix for this?

Not really. Usually someone has to lead and correct the issue for themselves in cases like this.
