### ISSUE TITLE
Creating a package that add a console keymap

### ISSUE THREAD

**Issue by Mayeu** [NixOS/nixpkgs#6060]
Hi,

I am currently playing around with NixOS in a VM, and one of the things that I really need before switching to it is the dvorak programmer key mapping for console (X has this keymap by default, but not kbd).

I tried to create my own little [package for it](https://github.com/Mayeu/nixpkgs/blob/add_dvp/pkgs/data/keymaps/dvp/default.nix) but the keymap is not availlable after install with `loadkeys dvp`. Obvisouly there is some kbd configuration going on that I do not know about that only check its own store path.

My other solution was to patch kbd to add the keymap, but I think it would be better to have it in a separate package.

Any idea how can I package a console keymap and make it loadable with `loadkeys keymap_short_name` ?

Edit: I know I can do `loadkeys full_path_of_the_keymap`, but that will mean upgrading this nix-store path in my `/etc/nixos/configuration.nix` every time the keymap is upgraded. Which is less obvious and easy than simply provide the name of the keymap.

**Comment by vcunat** [comment]
That dvorak isn't included in the standard available keymaps in the option ``i18n.consoleKeyMap`` in configuration.nix? I'm using ``consoleKeyMap = "colemak/en-latin9";``, so I think dvorak variants should be there as well.

**Comment by Mayeu** [comment]
From `ls /nix/store/4x0shsb64vxdimk8cpp0v4gd8lfk9kv6-kbd-1.15.3/share/keymaps/i386/dvorak/`:
```
ANSI-dvorak.map.gz  dvorak-l.map.gz  dvorak-r.map.gz   no.map.gz
dvorak-fr.map.gz    dvorak.map.gz    dvorak-ru.map.gz
```
There is only language variant of the keymap. I also check the sources of `kbd` and it is not present by default.

**Comment by vcunat** [comment]
I think it will be best to add that tiny file to our default ``kbd``.

**Comment by Mayeu** [comment]
Ok, going to try this way then :)

**Comment by Mayeu** [comment]
Closing the issue, since I have submitted a patch in #6068 for it.
