### ISSUE TITLE
nix-env -i openshift # no derivations - on non NixOS system (ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by aeat** [NixOS/nixpkgs#60609]
## Issue description
nix-env -iA nixpkgs.openshift  works
but not 

nix-env -i openshift
error: selector 'openshift' matches no derivations

never the less it is in the pkg search 
nixpkgs.minishift               minishift-1.33.0
nixpkgs.openshift               openshift-origin-3.11.0
nixpkgs.redshift                redshift-1.12

No issues with minishift and redshift.

### Steps to reproduce
execute 
nix-env -i openshift 
on non NixOS system like ubuntu 16.04 LTS

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-26-generic, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(ug): `"nixpkgs-19.09pre177683.5d09420337f"`
 - nixpkgs: `/home/ug/.nix-defexpr/channels/nixpkgs`

**Comment by vbgl** [comment]
The name of the package seems to be “openshift-origin”, therefore you should try `nix-env -i openshift-origin`, or better, use the attribute path: `nix-env -iA nixpkgs.openshift`.

Do you suggest that the package should be named “openshift” rather than “openshift-origin”?

**Comment by bachp** [comment]
@vbgl I think it might be better to name the package just `openshift` as the upstream project is no longer called "Openshift Origin" but "OKD" now. So just naming it `openshift` might be less confusing.

**Comment by Artturin** [comment]
-iA should be used instead of -i
