### ISSUE TITLE
Missing dependency for haskell-aeson-ghc7.8.3-0.7.0.4-shared: scientific package

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixpkgs#6062]
When installing haskell-aeson-ghc7.8.3-0.7.0.4-shared

    Configuring aeson-0.7.0.4...
    Setup: At least the following dependencies are missing:
    scientific ==0.2.*

Adding haskell-scientific-ghc7.8.3-0.2.0.2 to the install list fixes the error

**Comment by domenkozar** [comment]
still an issue?

**Comment by peti** [comment]
I think it's safe to say that this issue is obsolete.
