### ISSUE TITLE
ghcWithPkgs tries to rm on read-only filesystem

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixpkgs#6063]
Expression in systemPkgs list:

      (haskellPackages_ghc783.ghcWithPackages(self : [
        zlib
        pcre ]))

nixos-rebuild output:
 
    $ nixos-rebuild switch
    building Nix...
    building the system configuration...
    these derivations will be built:
      /nix/store/7hdlyd0wpmd13glaj6ryna75gwvax7va-haskell-env-ghc-7.8.3.drv
      /nix/store/wfm73n25ryxaix8ibhv47ry9wp32vqrn-system-path.drv
      /nix/store/iw4qs4aidh9m2jmrlvbgqbxyqkv9aa1h-dbus-conf.drv
      /nix/store/99f51921g3iyqr0mg1nysv86bjq18msh-xsession.drv
      /nix/store/4p5n727bji8bwsma16yfpwrj60njwkym-desktops.drv
      /nix/store/k5h4viasivh4vifjq0dkbbgwjfx9dix1-unit-display-manager.service.drv
      /nix/store/lzpax9rlpfq3hmb0i3y5m3jfl81nw2f1-system-crontab.drv
      /nix/store/h20km63gad1hh8nlnxfr15d1zx2d2vz3-unit-script.drv
      /nix/store/p5zlzn6ilj8vi1agig0kzr1yzfrp8mvr-unit-cron.service.drv
      /nix/store/wh54b6fnyfw4vckbbz7sl144g5ygzkzz-unit-polkit.service.drv
      /nix/store/wm0ymhxbjg792l2faxnh492jd87sffl3-system-units.drv
      /nix/store/p936l0gy6q6bflrvar2nybpibyi8ikkf-etc.drv
      /nix/store/1wgxfrqdk1xjav09nygkvya468g0xzg2-nixos-14.12.335.676e8d7.drv
    these paths will be fetched (0.50 MiB download, 2.29 MiB unpacked):
      /nix/store/hqzvkxgg1v9fy6n2a3n5pra1kkh3974f-automake-1.12.6
    building path(s) ‘/nix/store/igdigi0pbczs4p8hdi72qaj85n0szjnd-haskell-env-ghc-7.8.3’
    fetching path ‘/nix/store/hqzvkxgg1v9fy6n2a3n5pra1kkh3974f-automake-1.12.6’...
    building /nix/store/igdigi0pbczs4p8hdi72qaj85n0szjnd-haskell-env-ghc-7.8.3
    created 3 symlinks in user environment
    rm: cannot remove '/nix/store/igdigi0pbczs4p8hdi72qaj85n0szjnd-haskell-env-ghc-7.8.3/bin/ghc': Permission denied
    builder for ‘/nix/store/7hdlyd0wpmd13glaj6ryna75gwvax7va-haskell-env-ghc-7.8.3.drv’ failed with  exit code 1
    killing process 11274
    cannot build derivation ‘/nix/store/wfm73n25ryxaix8ibhv47ry9wp32vqrn-system-path.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/1wgxfrqdk1xjav09nygkvya468g0xzg2-nixos14.12.335.676e8d7.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/1wgxfrqdk1xjav09nygkvya468g0xzg2-nixos-14.12.335.676e8d7.drv’ failed

**Comment by peti** [comment]
`pcre` is not a valid Haskell package name.

You might want to consider switching to the `haskell-ng` package set, which doesn't have these problems anmore.

**Comment by peti** [comment]
Fixed in `haskellngPackages.ghcWithPackages`.
