### ISSUE TITLE
Can't activate php in httpd

### ISSUE THREAD

**Issue by maxigit** [NixOS/nixpkgs#6073]
I'm trying to setup a LAMP machine using NixOs. I've managed to install/activate mysql and apache (httpd). However I can't figure out how to activate PHP. I tried `enablePHP=true` in the `service.httpd` sections but it's not recognize. Can someone help or provide me with an example of a working configuration. (I've been trying for 2 days and close to give up on NixOS ..)

**Comment by robberer** [comment]
Do you have `services.httpd.extraModules = [ { name = "php5"; path = "${pkgs.php}/modules/libphp5.so"; } ];` in your configuration.nix ?

**Comment by robberer** [comment]
Maybe you want to take a look at http://blog.lastlog.de/posts/advanced_webservices_on_nixos_revisited/

**Comment by maxigit** [comment]
I added this line and its working now. Thank you very much.

**Comment by maxigit** [comment]
That's exactly what `enablePHP` should do (see in nixpkgs/nixos/modules/services/web-servers/apache-httpd/default.nix:338)

 ++ optional enablePHP { name = "php5"; path = "${php}/modules/libphp5.so"; }

However, `enablePHP` is not available when  I do services.httpd.enablePHP = `true`.
(It doesn't appear either when I do `man configuration.nix`).

**Comment by maxigit** [comment]
Found the problem. I was using version 14.04 whereas enablePHP has been added in 14.12.
