### ISSUE TITLE
update ipython-kernel, ghc-parser, ihaskell to latest versions

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#60825]
## Issue description

What's the process for including the latest `ghc-parser`, `ipython-kernel`, and `ihaskell` in `hackage-packages.nix`? AFAICT it involves editing `configuration-hackage2nix.yaml` but I'm not sure what edits to make. They're included in the latest Stackage `nightly` resolvers if that helps.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by teto** [comment]
hi @vaibhavsagar there is nothing to do apart from pushing them on hackage.
There is a regular automatic update from hackage (every day ?) available at https://github.com/NixOS/nixpkgs/tree/haskell-updates .
Otherwise you should read the readme of cabal2nix. I've recently experimented a bit with this so https://github.com/NixOS/nixpkgs/pull/62105 may help you

**Comment by peti** [comment]
@vaibhavsagar, the latest version of every Hackage package *is* in `haskell-packages.nix`. If these packages you've mentioned are in Stackage Nightly, then we have them. If think that a specific version of any of those packages is missing, then please make sure to include that information in your bug report.

Looking at `ghc-parser` as an example, the latest version is 0.2.0.3 -- and that is the version Nixpkgs `master` has, too. I notice that `ghc-parser` is marked "broken", though. Apparently, the build in Nixpkgs did not succeed?

**Comment by evanjs** [comment]
Any news on this? Checking the last example from @peti, it seems like ghc-parser installs fine and likewise, is no longer marked as broken.  Came across ihaskell recently and I'd love to see it fixed on nixpkgs.

**Comment by wmertens** [comment]
triage: @vaibhavsagar is this still a problem?

**Comment by vaibhavsagar** [comment]
No longer an issue, thanks for your help!
