### ISSUE TITLE
Gimp plugin "resynthesizer2" is not actually installed

### ISSUE THREAD

**Issue by typedfern** [NixOS/nixpkgs#60834]
## Issue description

Installing the gimpPlugins.resynthesizer2 package does not result in a working plugin; the python scripts are installed, but not the two native executables it depends on (called "resynthesizer" and "resynthesizer"

### Steps to reproduce

Try to install the package "gimpPlugins.resynthesizer2".

Expected result:
There should be a few new menu options in the Gimp, amongst them "Filter -> Enhance -> Heal Selection..."

Actual result:
No new menu options; python scripts cannot find the executables.

Possible solution:

I made it work by creating a derivation that adds a the following postInstall:

postInstall = "installPlugins src/resynthesizer/resynthesizer src/resynthesizer-gui/resynthesizer_gui";

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.90, NixOS, 18.09.1806.928ff62213b (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(cable): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
You need to make the plugins available to GIMP, not install it locally. The following should work:

```nix
(gimp-with-plugins.override { plugins = [ gimpPlugins.resynthesizer2 ]; }')
```

**Comment by typedfern** [comment]
> You need to make the plugins available to GIMP, not install it locally. The following should work:
> 
> ```nix
> (gimp-with-plugins.override { plugins = [ gimpPlugins.resynthesizer2 ]; })
> ```

Just tried it (on a nix shell) - but same result; the resulting installation of gimp-with-plugins links to a resynthesizer2 package that lacks the native executables, only has the python scripts (which don't work without the executables)

**Comment by jtojnar** [comment]
Hmm, there was an issue with `makeFlags`, `placeholder` saves us.
