### ISSUE TITLE
configureFlags needed for compiling Haskell readline on Mac OS X

### ISSUE THREAD

**Issue by andreasfrom** [NixOS/nixpkgs#6085]
I'm unsure how to add this myself, so here's the issue.
`nixpkgs.haskellngPackages.readline` fails to install on Mac OS X because the following `configureFlags` are missing:

    --extra-include-dirs=${pkgs.readline}/include
    --extra-lib-dirs=${pkgs.readline}/lib
    --configure-option=--with-readline-includes=${pkgs.readline}/include
    --configure-option=--with-readline-libraries=${pkgs.readline}/lib

**Comment by kirelagin** [comment]
This is not and OS X specific issue. I mean, not surprisingly, haskell-readline needs readline on all platforms, and it can’t find it.

**Comment by kirelagin** [comment]
BTW this didn’t help me to get haskell-readline find readline…

**Comment by kirelagin** [comment]
The problem is that it is not even trying to use `-lreadline` if it can’t find ncurses (or curses or termcap), so those are also needed. And I can’t really figure out how to tell `configure` where to look for them. /CC @peti

**Comment by kirelagin** [comment]
@peti I thought this file was generated automatically?

What is the easiest way to do similar changes (override `extraLibraries`) locally (i.e. in `~/.nixpkgs/config.nix`)?

**Comment by peti** [comment]
@kirelagin, `hackage-packages.nix` *is* generated automatically. The source of these changes is here: https://github.com/NixOS/cabal2nix/commit/bfc0e4c2e7d7011c24ebaac6310dcbff588eb16b.

If you want to achieve the same thing with a local override, then
 
  readline = overrideCabal super.readline (drv: { extraLibraries = drv.extraLibraries ++ [pkgs.readline]; })

would do the trick.

**Comment by kirelagin** [comment]
@peti Awesome, thanks!
