### ISSUE TITLE
usb_modeswitch_data udev rules aren't applied

### ISSUE THREAD

**Issue by nyanloutre** [NixOS/nixpkgs#60878]
## Issue description

Hello, I am using a Logitech G920 which should be configured by usb_modeswitch.

I added usb-modeswitch-data to the udev rules, it shows up in /etc/udev but nothing gets applied.

By looking at how the package is made it seems it is incorectly patching the udev file: originally it would call a script (`/lib/udev/usb_modeswitch`) but it is replaced by the usb_modeswitch executable (`/bin/usb_modeswitch`) without changing the arguments.

But the script will not work as it is because `/bin/usb_modeswitch_dispatcher` (which is called by `/lib/udev/usb_modeswitch`) will try to access a lot of hardcoded paths (like `/usr/share/usb_modeswitch` or `/usr/sbin/usb_modeswitch`).

### Steps to reproduce

`hardware.usbWwan.enable=true;`

**Comment by michalrus** [comment]
I think this can be closed — after #60981 everything seems to work.
