### ISSUE TITLE
services.httpd.phpOptions doesn't seem to work.

### ISSUE THREAD

**Issue by maxigit** [NixOS/nixpkgs#6089]
I'm using 14.12 and try to enable APC by using services.httpd.phpOptions. According to the code it's supposed to generate a php.ini by appending the content of this variable to php-recommended.ini.

I can't see any php.ini generated. Am I missing something ?

**Comment by robberer** [comment]
AFAIK phpOptions and enablePHP does only work on submodules.

I do not use any of these options to get a working php.ini because I had the same issue 1 year ago

```
{config, pkgs, ...}:

let

phpOptions = pkgs.writeText "php.ini" ''
  date.timezone = "Europe/Berlin"
'';

in

with pkgs.lib;

{
  environment.etc.phpIniFile = {
    source = phpIni;
    target = "php.ini";
  };
}
```

This writes a /etc/php.ini file which is used by PHP automatically.

**Comment by robberer** [comment]
I mean subservices not submodules.

**Comment by robberer** [comment]
This seems to be a good resource (untested) if want to try out subservices:

http://nixos.org/~eelco/pubs/servicecm-scm12-final.pdf

**Comment by maxigit** [comment]
Thanks. I'll have a look. However, if the options is not use, wouldn't that be better to remove it ?
