### ISSUE TITLE
setting fonts.fontconfig.dpi gives coerse error

### ISSUE THREAD

**Issue by geraldus** [NixOS/nixpkgs#6091]
I've tried to set DPI for my monitor
```nix
{
  fonts.fontconfig = {
    dpi = "102";
    hinting.autohint = false;
    ultimate.rendering = pkgs.fontconfig-ultimate.rendering.ubuntu;
  };
}
```
This gives me following error:
> cannot coerce an integer to a string, at "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/config/fonts/fontconfig.nix":204:52

```nix
# fontconfig.nix source cut
${optionalString (fontconfig.dpi != 0) ''
  <match target="pattern">
    <edit name="dpi" mode="assign">
      <double>${fontconfig.dpi}</double>
    </edit>
  </match>
''}
```
If I change `dpi` to sting, this unsurprisingly gives another error:
> The option value `fonts.fontconfig.dpi' in `/etc/nixos/fonts-configuration.nix' is not a integer.

pinging @ttuegel

**Comment by ttuegel** [comment]
Fixed in 0fee7a2b214ad80823df547861814bbdc6edab80. The option remains an `int`, we just call `toString` on it before interpolating it into the config files.

**Comment by geraldus** [comment]
Great! How should I bring this changes to my NixOS?

**Comment by geraldus** [comment]
How could I use this changes? I've tried to modify `fontconfig.nix`, but it's readonly.
