### ISSUE TITLE
Gimp: Unable to locate theme engine in module_path: "adwaita",

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#60918]
## Issue description

I ran gimp from terminal and noticed that it prints out following warnings:

```
(.gimp-2.10-wrapped_:26825): Gtk-WARNING **: 18:07:38.285: Unable to locate theme engine in module_path: "adwaita",
```

I don't see anything clearly broken in the UI, but just thought that probably this is some issue that could be fixed.

### Steps to reproduce

Run Gimp from a terminal.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.09.git.3d081ed (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by jluttine** [comment]
Oh, and in case it makes a difference, I'm not running GNOME but i3+none.

**Comment by jtojnar** [comment]
Try installing `gnome3.gnome-themes-extra`, GTK 2 is  weird.

**Comment by jluttine** [comment]
Thanks for the suggestion. I still get the warnings:

```
$ nix-shell -p gnome3.gnome-themes-extra gimp
$ gimp

(gimp:736): Gtk-WARNING **: 19:18:45.188: Unable to locate theme engine in module_path: "adwaita",

(gimp:736): Gtk-WARNING **: 19:18:45.192: Unable to locate theme engine in module_path: "adwaita",
GIMP-Warning: Bad interpreter referenced in interpreter file /nix/store/m1ywvz46c5g0n6gbf846d1zgdivky7qy-gimp-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp: python2

GIMP-Warning: Bad binary format string in interpreter file /nix/store/m1ywvz46c5g0n6gbf846d1zgdivky7qy-gimp-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp
```

I also noticed it warns about interpreters. Maybe those should be fixed too? I have some issues with one plugin, not sure if that interpreter issue is related to that.

**Comment by jtojnar** [comment]
Yeah, you would need to install it globally, so that GTK can find it under `/run/current-system/sw/lib/gtk-2.0/`. Alternately, adding it to `GTK_PATH` env var should also work.

**Comment by jluttine** [comment]
@jtojnar Thanks, that fixed the theme issue! So maybe that should be added as a propagated build input for gimp?

The interpreter warnings are still there. Should I open another issue for those?

**Comment by jtojnar** [comment]
Propagating will not do anything. You would need to add it to the wrapper is citrix does.

**Comment by jtojnar** [comment]
Yeah, please open a new issue for the interpreters.

**Comment by jluttine** [comment]
Thanks! I made a pull request. Seems to fix the issue.
