### ISSUE TITLE
Pantheon: shutdown always times out

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#60955]
## Issue description
Seems cerbere and systemd have a [bit of a quarrel](https://github.com/elementary/cerbere/issues/6)
and we usually have to wait the default `DefaultTimeoutStopSec` which is pretty long (90s).

As a workaround I think we can do what they've done upstream with systemd's config
```nix
systemd.extraConfig = ''
  DefaultTimeoutStopSec=25s
'';
```

Or any lower value that you think is appropriate.

I'm avoiding putting that kind of configuration in the Pantheon module because it should
be up to the user to do this.

**Comment by davidak** [comment]
I'm able to reproduce it on unstable. Will test if the the linked update fixes it.

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.09pre186857.239fffc90d7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre186857.239fffc90d7, nixos-hardware, nixos-unstable-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
