### ISSUE TITLE
Installing make

### ISSUE THREAD

**Issue by ProgrammingHider** [NixOS/nixpkgs#60997]
Hello,
I just did a clean install of NixOS 19.03(Koi) and wanted to compile dwm, but make was missing, so i typed in `sudo nix-env -i make`, and got an error. After doing `sudo nix-env -qa make`, make wasn't there. Does anyone know what package i have to install?

Thanks in Advance

**Comment by jbboehr** [comment]
Perhaps the attribute you want is `gnumake`?

```
[nix-shell:~]$ nix search gnumake
* nixpkgs.gnumake (gnumake)
  A tool to control the generation of non-source files from sources
[nix-shell:~]$ nix-shell -p gnumake
[nix-shell:~]$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by angristan** [comment]
I was also struggling to find `make` at first, and `gnumake` what was I was searching for.
