### ISSUE TITLE
Please update to Firefox 66.0.4 (master and release branches) to fix broken addons

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#61005]
## Issue description

As many already know, an issue with expired certificates made all Firefox addons suddenly "untrusted" by the browser:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Apparently a new release of Firefox with updated certificates has been published:

https://ftp.mozilla.org/pub/firefox/releases/66.0.4/

Would it be possible to update master and appropriate release branches please?

See also #60916 

Thanks

**Comment by edolstra** [comment]
The master and 19.03 branches have Firefox 66.0.4 now. The channels should update shortly.
