### ISSUE TITLE
Failed to install pipenv on unstable

### ISSUE THREAD

**Issue by greydot** [NixOS/nixpkgs#61027]
## Issue description
Pipenv fails to install due to "No matching distribution found for virtualenv-clone>=0.2.5 (from pipenv==2018.11.26)"
Full output is here https://bpaste.net/show/d6941ff5a447

### Steps to reproduce
Run `nix-shell -p pipenv`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 19.09pre178260.190727db4ea (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(void): `"nixpkgs-19.09pre178484.8bc70c937b3"`
 - channels(root): `"nixos-19.09pre178260.190727db4ea, nixpkgs-19.09pre178484.8bc70c937b3"`
 - nixpkgs: `/home/void/.nix-defexpr/channels/nixpkgs`

**Comment by greydot** [comment]
Could be related to https://github.com/NixOS/nixpkgs/pull/60045. Partially reverting it allows me to install pipenv just fine.

```
diff --git a/pkgs/development/tools/pipenv/default.nix b/pkgs/development/tools/pipenv/default.nix
index f51ce6fcfab..7e0f756845f 100644
--- a/pkgs/development/tools/pipenv/default.nix
+++ b/pkgs/development/tools/pipenv/default.nix
@@ -15,9 +15,9 @@ buildPythonApplication rec {
     flake8
     invoke
     parver
+    pew
     pip
     requests
-    virtualenv
   ];
 
   doCheck = false;
```

**Comment by nklops** [comment]
I'm having this on stable as well.

**Comment by greydot** [comment]
@nklops does my patch fix it for you?

**Comment by greydot** [comment]
@berdario

**Comment by nklops** [comment]
Sorry, it was unstable for me as well. Yup, the patch fixed the installation of pipenv.

**Comment by berdario** [comment]
Virtualenv-clone was a transitive dependency provided by pew.

I'm away from my laptop, ping @dgarzon

**Comment by greydot** [comment]
Yup, adding virtualenv-clone fixes it for me.
```
diff --git a/pkgs/development/tools/pipenv/default.nix b/pkgs/development/tools/pipenv/default.nix
index f51ce6fcfab..681e0685f80 100644
--- a/pkgs/development/tools/pipenv/default.nix
+++ b/pkgs/development/tools/pipenv/default.nix
@@ -18,6 +18,7 @@ buildPythonApplication rec {
     pip
     requests
     virtualenv
+    virtualenv-clone
   ];
 
   doCheck = false;
```
