### ISSUE TITLE
Binary-cache-less folk suffers from source repository availability/structure variance

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#6102]
Repositories don't have perfect availability, and even if so, directory layouts change -- ergo, during large rebuild-switch-es it is more of a rule that some source URLs mentioned in the Nix package descriptions become unavailable.

The situation somewhat fits within the tolerance margins on master.. but when one is unable to build a release branch.. it makes one sad indeed.

A global source repository caching layer, that would be tracking central branches would serve a lot of good to those poor souls who insist on compiling from source..

**Comment by vcunat** [comment]
Some hash-addressed fetchurl sources are cached on http://tarballs.nixos.org, but I'm unsure what is stored in there.

**Comment by shlevy** [comment]
Another thing that could help here is to have a way for hydra to rebuild some newly chosen portion of the fixed output derivations every eval, to ensure we're testing these regularly. @edolstra is that something we might want?

**Comment by edolstra** [comment]
@vcunat Turns out the tarball mirror was still stuck on mirroring 14.04 tarballs. I've updated it to 14.12 now. This has added about ~2800 tarballs to the cache.

@shlevy I don't see an easy way to do that.

**Comment by vcunat** [comment]
Good. That's quite some nontrivial mirroring, which fixes most of this issue, I guess.

**Comment by deepfire** [comment]
I still see mirror failures fairly often -- the latest example being `ftp.videolan.org` being down, which rendered `libbluray` unbuildable.  No mirror was queried.

**Comment by vcunat** [comment]
I tweaked videolan mirrors in 1e04d875db7b1.

**Comment by Profpatsch** [comment]
I guess there is no real action item that can be addressed here, please reopen if you don’t think so.
