### ISSUE TITLE
statik doesn't evaluate for some reason

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#61106]
## Issue description
meguca, which relies on it builds fine, but when using say, `nix-shell -p go nodejs emscripten gcc gnumake cmake pkgconfig go-bindata easyjson quicktemplate ffmpeg-full graphicsmagick ghostscript opencv statik`, we get this `error: undefined variable 'statik' at (string):1:251`

I can't figure out why this is happening, as it's properly defined, or at least it seems to be in all-packages.nix

### Steps to reproduce
See above.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.13, NixOS, 19.09pre178795.2ec5e9595be (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre178795.2ec5e9595be, nixpkgs-19.09pre178484.8bc70c937b3"`
 - channels(okina): `"nixos-19.03pre166449.be445a9074f, nixpkgs-19.03pre166583.872502aa56b"`
 - nixpkgs: `/home/okina/.nix-defexpr/channels/nixpkgs`

**Comment by vcunat** [comment]
It was added very recently, so I believe `nix-shell` uses older nixpkgs than you expect it to.

**Comment by Chiiruno** [comment]
That shouldn't be the case, because my channels are on unstable.

**Comment by vcunat** [comment]
This certainly doesn't seem fresh enough:
>  - channels(okina): `"nixos-19.03pre166449.be445a9074f, nixpkgs-19.03pre166583.872502aa56b"`

**Comment by Chiiruno** [comment]
Oh no, I think I might be dumb.
Thanks for pointing that out, sorry for wasting any time.
