### ISSUE TITLE
X fails to start with modeset(0): failed to set mode: Invalid argument 

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#61125]
## Issue description

This is an upstream issue, so I am logging it here in case others are having the same problem.

Due to changes in X 1.20 and recent kernels, X will in some cases fail to start with ```modeset(0): failed to set mode: Invalid argument ```.

The workaround: use ```intel``` instead of ```modesetting``` (on intel hardware).

The kernel is being fixed so 5.1.x should be getting the fix.

We definitely shouldn't do https://github.com/NixOS/nixpkgs/issues/55520 right now...

Reference:
- https://bugs.freedesktop.org/show_bug.cgi?id=109806
- https://gitlab.freedesktop.org/xorg/xserver/issues/542

### Steps to reproduce

1. Upgrade to latest ```nixos-unstable``` (2019-05-07)
2. Use the ```modesetting``` driver
3. Try to run ```sddm```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by rimmington** [comment]
Ran into the same error message with 19.09 on a Dell XPS 15 9560, which has a couple of video devices (Intel + NVIDIA GP107M). Had to fall back to 19.03.

This could be a separate issue, since the kernel patch identified as the root cause the FDO bug doesn't appear to be applied to the upstream 4.19.84 kernel.

**Comment by peterhoeg** [comment]
This is no longer an issue on unstable. @rimmington - fixed on 19.09?

**Comment by rimmington** [comment]
Issue no longer exists on latest 19.09, didn't have to alter my config.

(Unrelated: [ran into this](https://github.com/NixOS/nixpkgs/issues/30789#issuecomment-339378300) also).

Thanks for the ping @peterhoeg.
