### ISSUE TITLE
Package request: Koka

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#61167]
[Koka](https://github.com/koka-lang/koka) is a function-oriented language that separates pure values from side-effecting computations (The word ‘koka’ (or 効果) means “effect” or “effective” in Japanese). Koka is also flexible and fun: Koka has many features that help programmers to easily change their data types and code organization correctly even in large-scale programs, while having a small strongly-typed language core with a familiar JavaScript like syntax.

**Comment by siraben** [comment]
Still important to me

**Comment by anka-213** [comment]
Looks like issue is resolved now: https://github.com/NixOS/nixpkgs/pull/117447
