### ISSUE TITLE
bash: words: bad array subscript

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#6117]
Everytime I press TAB in an empty command prompt I get the error:
```
    bash: words: bad array subscript
```
I think this is related to https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1289597

**Comment by sorokin** [comment]
Note, that 14.12 is affected by this bug too. In bash-completion git repository there is a commit a9c556ccad819869a6a5d932aac0a75a99372f08 that fixes this issue.

**Comment by iElectric** [comment]
Needs bash-completion from master branch http://anonscm.debian.org/cgit/bash-completion/bash-completion.git
