### ISSUE TITLE
nginx mime types

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#61186]
## Issue description

The nginx config generated by the nginx module does not set a default mime type, resulting in many binary files (.opus, .mkv, .pkg) being displayed as text (text/plain).
I suggest using the mime types list from mailcap, like ArchLinux does, and adding "default_type: application/octet-stream". 

I fixed this for my setup temporarily like this: https://git.pbb.lc/petabyteboy/nixfiles/commit/21ee8ed7f87571353df5b86c4cd1bc7478fddcc0

### Steps to reproduce

Set up a basic nginx server on NixOS. Put a .mkv or .opus file in the served directory. Try to download it. Its content will be shown as text in the browser.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.10, NixOS, 19.09pre177651.aeb464dfd37 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by angristan** [comment]
Let's make a PR with your patch? :slightly_smiling_face:

**Comment by petabyteboy** [comment]
Yeah, but I think the mime types should be customizable in the nginx module. I will take a look and make a draft PR at some point.
