### ISSUE TITLE
Atom don't see branch of new git repo

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#61189]
## Issue description

cc @ysndr  @NeQuissimus 

### Steps to reproduce

0. open Atom editor in a directory
1. open git panel by clicking on the bottom right
2. initialize repo using Atom
3. Atom sais "Not on branch"

![Screenshot from 2019-05-09 16-12-48](https://user-images.githubusercontent.com/91113/57460401-538cfe80-7275-11e9-84ed-80faaf3baae8.png)

But git on CLI sais:

```
$ git status
On branch master
```

Restart of Atom don't helps.

Even when i init the repo on CLI, Atom sees no branches! (not a problem in order repos)

It's normal after the first commit using CLI.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.40, NixOS, 19.03.172496.3e7300cf049 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172496.3e7300cf049, nixos-hardware, nixos-unstable-19.09pre178795.2ec5e9595be"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by BenBals** [comment]
While I can in fact reproduce this issue, i am not sure this is an issue with nixpkgs. This is most likely an issue with atom itself. Remember: Nix only packages existing software.

**Comment by BenBals** [comment]
I just booted up my Windows partition: The Windows version suffers from the exact same defect. Please file an issue with [atom/atom](https://github.com/atom/atom/issues).

**Comment by IMPVT** [comment]
Have exactly the same problem. Just cloned the repository within Atom, not seeing any branches to select.
