### ISSUE TITLE
Dejavu-fonts failing to build when cross-compiling

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/nixpkgs#61212]
## Issue description

Dejavu-fonts failing to build when cross-compiling

Seems to be related to (but distinct from) https://github.com/NixOS/nixpkgs/issues/32909

Buildlog: https://gist.github.com/Synthetica9/f5b3345a784b558c2ef47d43aefe588e

### Steps to reproduce

Minimal failing example:

```nix
let
  commit = "8e1852ac7e7827f740555f669b1551f814f3b2cc";
  repo = builtins.fetchTarball "https://github.com/nixos/Nixpkgs/archive/${commit}.tar.gz";
  pkgs = import repo {
    crossSystem = {
      config = "armv7l-unknown-linux-gnueabi";
    };
  };
in pkgs.dejavu_fonts
```

Build with `nix-build dejavunocrosscompile.nix`

## Technical details

Don't think this is relevant, but:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.40, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03pre167877.4a200fbbf0a"`
 - channels(synthetica): `"nixos-19.03pre162590.562b7a7702c"`
 - nixpkgs: `/nix/store/96izcwffci82k01pq3g0g1pw67aybj2l-nixos-unstable-small-2019-05-05-1e8cf45`

**Comment by Synthetica9** [comment]
cc @volth, who fixed it last time

**Comment by volth** [comment]
The fonts are very different indeed:
![](http://i.imgur.com/nNZkYiG.png)

probably the difference is in how ```fontforge``` was build

**Comment by volth** [comment]
Or maybe just a difference between fontforge ```20190317``` and ```20190413```

**Comment by volth** [comment]
yes, apparently the hash mismatch is caused by ```fontforge``` evolution
fontforge-20170730: ```sha256:1cxprzsr826d888ha4zxx28i9jfj1k74q9kfv3v2rf603460iha9```
fontforge-20190317: ```sha256:1az7yzrf155rn7wjk5sj4gnw9v5wlqx1h94g358x4j0cn12hcjwp```
fontforge-20190413: ```sha256:0l9kp8dh59rsf54by2z58nhmhikpr5jjqy6mxlylil2g7af6zcmi```

other fonts might be affected as well.

The options are:
 1. To remove ```outputHash``` from all the fonts (it will result not only on different fonts for each CPU but also in font recompilation/redownload on each change in any library ```fontforge``` depends on)
 2. To update it to the results of compilation using the latest ```fontforge``` and forbid @r-ryantm update ```fontforge``` automatically, at least without trying to build all the fonts

What should we do?

**Comment by Synthetica9** [comment]
Option 2. is pretty trivial to implement (just add the string `nixpkgs-update: no auto update` tot the derivation), so we could do that until we find a new solution.

@ryantm, is @r-ryantm capable of running post-update scripts?

**Comment by ryantm** [comment]
@Synthetica9 It doesn't currently run scripts. Is there a standard post-update script in nixpkgs?

**Comment by Synthetica9** [comment]
@ryantm no, I was thinking we could write a post-update script for fontforge to update the hashes for the fonts that would be affected.

**Comment by volth** [comment]
@veprbl ```6.topic: cross-compilation``` is not relevant, it is just coincidence

**Comment by volth** [comment]
I updated hashes in #61212
Probably we should decide to remove them, there are not so many fonts
I marked the affected hashes with a comment line "# hash depends on fontforge version"

**Comment by volth** [comment]
Well, the hashes are different even between ```@ofborg``` and my local machine.
That makes living on ```master``` near two upgrades of ```fontforge``` is difficult with FO fonts :(
