### ISSUE TITLE
dotnet cannot find libX11.so.6

### ISSUE THREAD

**Issue by jpgneves** [NixOS/nixpkgs#61229]
## Issue description

When attempting to run the default application created by one of the Avalonia templates (e.g. `dotnet new avalonia.mvvm -o dotnet-example`), `dotnet` fails to find `libX11.so.6` despite `xorg.libX11` being installed. For example:

```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'libX11.so.6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11.so.6.so: cannot open shared object file: No such file or directory
   at Avalonia.X11.XLib.XInitThreads()
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options) in D:\a\1\s\src\Avalonia.X11\X11Platform.cs:line 31
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at dotnet_example.Program.Main(String[] args) in /home/jneves/proj/dotnet-example/Program.cs:line 14
```

### Steps to reproduce

1. `nix-shell -p dotnet-sdk xorg.libX11 dotnetPackages.Nuget`
2. Install the Avalonia UI templates: `git clone https://github.com/AvaloniaUI/avalonia-dotnet-templates.git && dotnet new --install avalonia-dotnet-templates`
3. Create a new Avalonia UI app: `dotnet new avalonia.mvvm -o dotnet-example`
4. Try to run the app: `cd dotnet-example && dotnet run -f netcoreapp2.1`
5. You should now get the error as described above.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 19.03.172396.d740b2ee855 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172396.d740b2ee855"`
 - channels(jneves): `"nixpkgs-19.09pre178895.9ebc6ad944c, unstable-19.09pre179224.8e1852ac7e7"`
 - nixpkgs: `/home/jneves/.nix-defexpr/channels/nixpkgs`
```

**Comment by jpgneves** [comment]
Looks similar to https://github.com/NixOS/nixpkgs/issues/15097 so maybe there's a similar fix to be had?

**Comment by mtrsk** [comment]
Can confirm this while working on a F# project!

**Comment by mtrsk** [comment]
@jpgneves I've managed to solve this in [this issue](https://github.com/AvaloniaUI/Avalonia/issues/3020#issuecomment-533881126), the package works fine now.

**Comment by jpgneves** [comment]
> @jpgneves I've managed to solve this in [this issue](https://github.com/AvaloniaUI/Avalonia/issues/3020#issuecomment-533881126), the package works fine now.

Thanks, I'll give it a try soon and close the issue if nothing goes wrong!

**Comment by PlumpMath** [comment]
~]$ dotnet build ; dotnet run
Microsoft ® Build Engine version 16.4.0+e901037fe for .NET Core
Copyright © Microsoft Corporation. All rights reserved.

Restore completed in 25.9 ms for /home/user/Proj.csproj.
Proj -> /home/user/Proj/bin/Debug/netcoreapp3.1/Proj.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:00.86
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.DoDispose()
at Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.Finalize()

**Comment by nph278** [comment]
I am having this same issue while using [piston](https://www.piston.rs/) in a Rust project.

**Comment by mdarocha** [comment]
When running on NixOS, dotnet programs can find native dependencies in the standard paths (`/usr/lib` etc), and that's why you have to set `LD_LIBRARY_PATH`. 

If packaginging for `nixpkgs`, use `buildDotnetModule` and set the `runtimeDeps` attribute. This will ensure the libraries set in `runtimeDeps` will be visible to the built package (it sets `LD_LIBRARY_PATH` in a wrapper script under the hood).

If working on a package in a `shell.nix` environment, you can set `LD_LIBRARY_PATH` using `shellHook`:

```
pkgs.mkShell {
        buildInputs = with pkgs; [ dotnet-sdk ];
        shellHook = ''
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${
            with pkgs;
            lib.makeLibraryPath [ libGL xorg.libX11 xorg.libXi ]
          }"
        '';
      };
```

Hope this helps, I'll close this issue now since this isnt an actual bug in dotnet or its nix packaging.
