### ISSUE TITLE
Kitty wrapper does not work on MacOS

### ISSUE THREAD

**Issue by rvolosatovs** [NixOS/nixpkgs#61231]
## Issue description
Due to MacOS oddities `kitty` does not work when executed as symlink(https://github.com/kovidgoyal/kitty/issues/1539) and hence, the wrapper installed via https://github.com/NixOS/nixpkgs/blob/48a65ef9e62142712ca7e91d472787554a32649b/pkgs/applications/misc/kitty/default.nix#L93
cannot work on MacOS.
In fact, `${pkgs.kitty}/bin/kitty` is unusable on MacOS whatever the content is.

Any idea what could be done about this?
Should we remove the `bin` directory altogether from the build output to prevent confusion?

**Comment by matthewbauer** [comment]
I think the best thing to do here is just remove the symlink and use Applications/kitty.app

**Comment by kovidgoyal** [comment]
If you wish to use a symlink, use one that points to kitty-deref-symlink https://github.com/kovidgoyal/kitty/commit/bdeec612667f6976109247fe1750b10dda9c24c0
