### ISSUE TITLE
Feature Request: Provide QEMU presets for binfmtMiscRegistrations

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/nixpkgs#61248]
## Issue description

See: https://github.com/cleverca22/nixos-configs/blob/76260ad60cd99d40ab25df1400b0663d48e736db/qemu.nix

It would be nice if a config option like that would be provided in stock NixOS.

**Comment by Synthetica9** [comment]
cc @cleverca22

**Comment by matthewbauer** [comment]
Could you try out this: https://github.com/NixOS/nixpkgs/pull/61257
