### ISSUE TITLE
ldc checkPhase fails

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#61316]
## ldc checkPhase fails
See [build log](https://nix-cache.s3.amazonaws.com/log/hxzygqhkhg4kqs2wdcmim65lp20vwbq3-ldc-1.15.0.drv)

```
1600:  ... fail_compilation/testhtml2.html -O (-d -dw)
1600:  ... fail_compilation/testhtml3.html -O (-d -dw)
1600:  ... fail_compilation/testhtml.html -O (-d -dw)
1600: make: Leaving directory '/build/ldc-1.15.0-src/tests/d2/dmd-testsuite'
4/4 Test #1600: dmd-testsuite ....................   Passed  193.09 sec

The following tests passed:
        clean-dmd-testsuite-debug
        clean-dmd-testsuite
        dmd-testsuite-debug
        dmd-testsuite

100% tests passed, 0 tests failed out of 4

Total Test time (real) = 193.14 sec
Test project /build/ldc-1.15.0-src/build
    Start 1: build-ldc2-unittest
1/2 Test #1: build-ldc2-unittest ..............   Passed   40.02 sec
    Start 2: ldc2-unittest
2/2 Test #2: ldc2-unittest ....................Child aborted***Exception:   0.03 sec
Fatal error in EH code: DWARF header has unexpected format 2


50% tests passed, 1 tests failed out of 2

Total Test time (real) =  40.08 sec

The following tests FAILED:
          2 - ldc2-unittest (Child aborted)
Errors while running CTest
builder for '/nix/store/hxzygqhkhg4kqs2wdcmim65lp20vwbq3-ldc-1.15.0.drv' failed with exit code 8
```

It seems to have been [disabled on darwin](https://github.com/NixOS/nixpkgs/commit/0695b7da24b20c3654e42be597740bcd50defd4b) but now fails on all platforms.

According to @ThomasMader this was introduced in https://github.com/NixOS/nixpkgs/pull/56744.
See https://github.com/NixOS/nixpkgs/pull/61222#issuecomment-491443085 for more details.

Interestingly enough the same failure was seen with  `LLVM 7` in https://github.com/ldc-developers/ldc/issues/2954

cc @matthewbauer

**Comment by ThomasMader** [comment]
I think I was wrong. I guess the problem is the switch to llvm 7 from llvm 5 as a default.
I will try it out and follow up with a PR if everything works.

**Comment by ThomasMader** [comment]
That was the problem this issue can be closed with https://github.com/NixOS/nixpkgs/pull/61354.
