### ISSUE TITLE
lz4 is broken on darwin until next release

### ISSUE THREAD

**Issue by jhenahan** [NixOS/nixpkgs#61319]
## Issue description
From [the 1.9.1 release notes](https://github.com/lz4/lz4/releases/tag/v1.9.1):

> Note: this release has an issue when compiling liblz4 dynamic library on Mac OS-X. This issue is fixed in: https://github.com/lz4/lz4/pull/696.

This breaks things like `gitAndTools.gitFull`, `gitSVN`, and `nix-prefetch-scripts`.

### Steps to reproduce

Attempt to build lz4-1.9.1 (tracking `nixos-unstable`).

Observe:

```
building
build flags: -j8 -l8 SHELL=/nix/store/5544q4fyc2cr0raqv6c6xhx6d9z1ccdj-bash-4.4-p23/bin/bash PREFIX=\$\(out\) INCLUDEDIR=\$\(dev\)/include LD=\$CC
make[1]: Entering directory '/private/tmp/nix-build-lz4-1.9.1.drv-0/source/lib'
compiling static library
compiling dynamic library 1.9.1
ld: unknown option: -soname=liblz4.so.1
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:113: liblz4.so.1.9.1] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-lz4-1.9.1.drv-0/source/lib'
make: *** [Makefile:52: lib-release] Error 2
builder for '/nix/store/1p6amz4jbw2lqp3bsd89kxifxc4n2s9p-lz4-1.9.1.drv' failed with exit code 2
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixpkgs-19.03pre164964.b0f40b78513"`
 - nixpkgs: `/Users/JHENAHAN/src/dotnix/nixpkgs`

## Remedy

Until that PR lands in a release, it is sufficient to use an overlay like

```nix
self:
  super:
    {
      lz4 = super.lz4.overrideDerivation (attrs:
        {
          src = super.fetchFromGitHub {
            sha256 = "09c8g708gcnah5nd0m64dym17m10vg101yv2867lyp2mna7rsvh7";
            rev = "02914300185515097cdbebcd95c379508b5d3053";
            repo = "lz4";
            owner = "lz4";
          };
        });
    }
```

**Comment by marsam** [comment]
the fix is already in staging https://github.com/NixOS/nixpkgs/pull/60849

**Comment by jhenahan** [comment]
Closing and waiting around for #60849 to hit nixos-unstable :)
