### ISSUE TITLE
nixOS: keyboard not working after boot

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#6132]
I tried to install nixos via uefi installation and a usb stick, following this guide: http://nixaid.com/usb-bootable-nixos-uefi/

It starts correctly until the point in which I'm expected to login as root with an empty password. At that point, my keyboard seems incapable of input, so I can't login and have to reboot.

I tried the procedure with nixos 14.12 (both minimal and graphical stable cds) and the current snapshot of 15.05 minimal (nixos-minimal-15.05pre57108.96d6344). My machine is a Sony Vaio Duo 11.

What should I add to the setup to make the keyboard work?

**Comment by iElectric** [comment]
What keyboard do you use?

**Comment by meditans** [comment]
Well, it's the integrated keyboard of the laptop.. is there a command that I can use to give you more data?

**Comment by edwtjo** [comment]
Can you try adding:
```
boot.kernelPackages = pkgs.linuxPackages_3_18;
nixpkgs.config.packageOverrides = pkgs: 
  { linux_3_18 = pkgs.linux_3_18.override {
      extraConfig =
        ''
          SONY_LAPTOP y
        '';
    };
  };
```
To your configuration.nix.

**Comment by meditans** [comment]
Do you mean to add it into the configuration.nix in the iso, before I
transform it to make it bootable with UEFI?

2015-02-04 20:42 GMT+01:00 Edward Tjörnhammar <notifications@github.com>:

**Comment by meditans** [comment]
Hi all, I asked around in #nixos channel, and it seems that the file I should modify is
 
    nixpkgs/nixos/modules/installer/cd-dvd/iso-image.nix

Howevew, trying to insert the snippet @edwtjo suggested in the

    config = {

section, results in this error:

    Error in reading or end of file.
    make[1]: write error
    make: *** [sub-make] Error 1
    make: write error
    builder for ‘/nix/store/pryk82qm7fgbs15vw42sffa06w3n7lnf-linux-config-3.18.3.drv’ failed with exit code 255
    cannot build derivation ‘/nix/store/mcyab0rch9psj7mqfyk5r3vdi57pmagm-linux-3.18.3.drv’: 1 dependencies couldn't be built
    building path(s) ‘/nix/store/307i1l72nkh0fw9n2l8pcmmdly8bym8k-local-cmds’
    killing process 6337
    cannot build derivation ‘/nix/store/6fl70d5nx21kh8ys48c45g6c208xi360-iso9660-image.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/7qfgj1gpj0qvswd4rl195y3z7mh75h6z-nixos-iso-15.05pre56789.gfedcba.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/7qfgj1gpj0qvswd4rl195y3z7mh75h6z-nixos-iso-15.05pre56789.gfedcba.drv’ failed

So, the question is, where should I put the snippet?

**Comment by edwtjo** [comment]
Well if you don't have a keyboard you need to make it work as soon as possible, it seems that the ISO doesn't pick up the `sony_laptop` kernel module in time, or at all, which makes it incompatible with your hardware. So the answer is just "Yes". Another alternative might be to not compile it into the kernel but just add it to `boot.kernelModules = [ "sony_laptop" ] ` and `boot.initrd.kernelModules = [ "sony_laptop" ]` in your `configuration.nix`. Also I don't own or buy Sony products and the CONFIG_SONY_LAPTOP is just a guess from my part, you need to verify what kernel modules you need. If you are on ubuntu you should be able to use `lspci -v | grep Kernel` to see what kernel modules you need in order to yield a working system, disregarding any firmware blobs.

Irregardless, you "should" be able to build the ISO using `export NIXOS_CONFIG="/path/to/my/configuration.nix"` and it should work fine using it both for the ISO and your final `/etc/nixos/configuration.nix`

**Comment by meditans** [comment]
I should add that I'm able to use the keyboard when selecting whether to try the nixOS live cd, or to boot to my usual EFI. The keyboard just mutes when I enter the nixos bootstrap, and this makes me think that it's a nixos error, more than an unsupported device. Moreover, the device works fine with all of the others linux distros (up to my knowledge).

**Comment by wmertens** [comment]
@meditans this is very odd, I'd suggest looking at lsusb and loaded kernel modules on livecds of distros that do work.

**Comment by nigelgbanks** [comment]
I've encountered the same problem but with a Acer C720 Chromebook, and an alternative install method documented here: https://nixos.org/wiki/Installing_NixOS_from_a_USB_stick#Alternate_method

**Comment by puffnfresh** [comment]
@nigelgbanks I'm hitting the same problem with an Acer CB3-111 Chromebook. Using a Unetbootin USB drive (had to toggle the bootable flag on the partition using fdisk for John Lewis' coreboot to boot it)

**Comment by puffnfresh** [comment]
@nigelgbanks I downloaded unstable: https://nixos.org/releases/nixos/unstable/nixos-16.03pre67851.0392197/

Keyboard works and it's now as simple as `dd if=/tmp/nixos-minimal-16.03pre67851.0392197-x86_64-linux.iso of=/dev/sdb bs=10M` to make the USB!

**Comment by zimbatm** [comment]
I wonder if it's possible to detect the sony laptop in nixos-generate-config to load the right module. It would be helpful to get the `lsusb -vvvv` (install the usbutils package) and `lspci -vvvv` outputs so we can add the detection.

**Comment by Profpatsch** [comment]
triage: I think the original issue has been fixed. If you have a follow-up you want to be implemented, please open a new issue/pull request.

**Comment by wpcarro** [comment]
I'm unsure I'm having the same issues or not. My NixOS was working for a few versions after `nixos-install`, but recently the laptop keyboard and trackpad stopped working. I rolled back versions, but the problem persists.

Right now, my workaround is to plugin an external keyboard.

Does anyone have any recommended advice for troubleshooting this? I can't think of much at the moment other than installing `xev` to see if any of the laptop key events are firing.

**Comment by Profpatsch** [comment]
Can you open a new issue (and maybe link to this one?)

**Comment by wpcarro** [comment]
Sure. #65630
