### ISSUE TITLE
Wrong resynthesizer Gimp plugin is used by default

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#61341]
## Issue description

If I install all Gimp plugins, an old and badly working resynthesizer (v 0.16) is used instead of the current working version (2.x).

(See: https://github.com/bootchk/resynthesizer/issues/63#issuecomment-491502679)

### Steps to reproduce

Install `gimp-with-plugins`. Using resynthesizer (e.g., heal selection) in Gimp seems to trigger version 0.16 resynthesizer. If I modify nixpkgs so that I just remove the version 0.16 from nixpkgs altogether, then the same commands use the recent version and everything works.

Should we just remove v 0.16 or is there some reason to keep it? At least it seems to me they cannot co-exist (or it requires some fixing).

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.41, NixOS, 19.09.git.bc94dcf (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by 7c6f434c** [comment]
I think I remember some situation where the old resynthesizer allowed to use a combination of settings impossible with resynthesizer2 (and yielded better results in a specific case). Removing the old one from the default set while is OK, though.

**Comment by jtojnar** [comment]
This was fixed by https://github.com/NixOS/nixpkgs/pull/61365
