### ISSUE TITLE
Derivation fails, seems to be location-sensitive

### ISSUE THREAD

**Issue by mkovaxx** [NixOS/nixpkgs#61357]
## Issue description

A derivation (to build CGAL) seems to be sensitive to where it is located in the file system.

Context: I'm trying to patch CGAL (with the changes below) so that I can proceed with my work before its next release is published.
https://github.com/CGAL/cgal/pull/3876

### Steps to reproduce

```
git clone git@github.com:mkovacs/repro-cgal-nef3-triangulation-bug.git
cd repro-cgal-nef3-triangulation-bug
nix-build
```

The subfolder `CGAL` contains the same derivation as `nixpkgs`:
https://github.com/mkovacs/repro-cgal-nef3-triangulation-bug/blob/46237630df558e77005a850ed2e109c74448bfba/CGAL/default.nix
https://github.com/NixOS/nixpkgs/blob/01e2e11ea5fb67f028abc01851772d3baba3a4b3/pkgs/development/libraries/CGAL/default.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-17763-Microsoft, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(mate): `"nixpkgs-19.03pre167327.11cf7d6e1ff"`
 - nixpkgs: `/home/mate/.nix-defexpr/channels/nixpkgs`

**Comment by msteen** [comment]
It is not location-sensitive or anything, if I clone the project and modify `CGAL/default.nix` as it was per `4.13` your project builds without any errors. So it has to be changes made in 4.14 that influence the cmake build and cause it to report those double paths. That's all the help I can give, good luck!
