### ISSUE TITLE
NVidia 418.74 hashes changed

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#61367]
## Issue description

While trying to update nvidia to 418.74 in 19.03, I got hash errors. It seems like the hashes for `nvidia-settings` and `nvidia-persistenced` have changed.

Old hashes and currently in master:
```
    settingsSha256 = "15mbqdx5wyk7iq13kl2vd99lykpil618izwpi1kfldlabxdxsi9d";
    persistencedSha256 = "0442qbby0r1b6l72wyw0b3iwvln6k20s6dn0zqlpxafnia9bvc8c";
```

New hashes:
```
$ nix-prefetch-url https://download.nvidia.com/XFree86/nvidia-settings/nvidia-settings-418.74.tar.bz2
path is '/nix/store/hbzjcq4viav4l47vz4d20qa2bharycdx-nvidia-settings-418.74.tar.bz2'
01xl5a41qq7iv4d8lf324andy0j96im5rkqzzryp230likfh694n
$ nix-prefetch-url https://download.nvidia.com/XFree86/nvidia-persistenced/nvidia-persistenced-418.74.tar.bz2
path is '/nix/store/dcrbczdw17xh35ass01ma1vmqjjzdcah-nvidia-persistenced-418.74.tar.bz2'
0knl3j43xllv25xgkhvlrbbnqip713yhajjd2kvyvlc2ggq1ap50
```

Does anyone have the old versions available to check what changed?

**Comment by eadwu** [comment]
This has to do with the release of `430.09`, when it was released (or when I was updating it), I couldn't get a valid download link so the source was fetched from Github instead.

**Comment by ambrop72** [comment]
I see, I'm resolving this then.
