### ISSUE TITLE
Run tests when hostPlatform.system == buildPlatform.system

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#61414]
## Issue description

Right now, we run tests only when ```hostPlatform == buildPlatform```:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/make-derivation.nix#L96-L97

This is a little too strict of a condition. We should be able to run tests when the CPU and Kernel match. This impacts things like pkgsStatic where we aren't running tests at all. So, I would like to change the condition to:

```
stdenv.hostPlatform.system == stdenv.buildPlatform.system
```

to allow some differences.

/cc @Ericson2314 

Somewhat related to this, it would be nice to build pkgsStatic in ```release-cross.nix```, or perhaps just build some cross jobs statically.

**Comment by Ericson2314** [comment]
> May be resolved by #140271

That is the right approach.
