### ISSUE TITLE
unifi frequently gives errors on `nixos-rebuild switch`

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#61424]
## Issue description

When running a `nixos-rebuild switch` that updates the unifi controller service, I frequently get errors during the process that look like

```
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, firewall.service, sys-kernel-debug.mount, var-lib-unifi-bin.mount, var-lib-unifi-data.mount, var-lib-unifi-dl.mount, var-lib-unifi-lib.mount                                               
var-lib-unifi-lib.mount is not active, cannot reload.
var-lib-unifi-dl.mount is not active, cannot reload.
var-lib-unifi-data.mount is not active, cannot reload.
var-lib-unifi-bin.mount is not active, cannot reload.
restarting the following units: dhcpcd.service, sshd.service, systemd-journald.service                                                 
```

These errors appear to be harmless as the new unifi controller seems to be running just fine, but it means I get a warning about errors when switching to the new configuration and it's rather irritating. I'm also mildly concerned that this is indicative of a problem of some sort.

### Steps to reproduce

I get this frequently when updating unifi, but I feel like I've updated it at least once without getting these errors (but I can't be certain). My configuration looks like

```nix
{
  config = {
    services.unifi = {
      enable = true;
      unifiPackage = pkgs.unifiStable;
      openPorts = true;
    };
  };
}
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 19.03.172582.7ab08db51ad (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172582.7ab08db51ad, nixos-unstable-19.09pre177262.fc48e74127c"`                                       
 - channels(lily): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lilyball** [comment]
CC @erictapen

**Comment by 0x4A6F** [comment]
These systemd mountpoints might not support a reload.
A rebooted system shows all *.mount* services as active.
`systemctl restart var-lib-unifi-$mpath.mount` seems to work.

@lilyball, you can check the output of `mount | grep unifi` and for each *var-lib-unifi-$mpath.mount* run the appropriate command (i.e. $mpath=lib):
`systemctl status var-lib-unifi-lib.mount`

**Comment by lilyball** [comment]
I just checked, all 4 of those mounts are currently mounted and status says they were mounted 18 hours ago (when I did my `nixos-rebuild switch`).

So it seems like the error is basically "hey, these aren't mounted right now, so being asked to reload doesn't work" and then they mount anyway.

So I guess the question is, why weren't they mounted at the point where they were asked to reload? Is something unmounting them prior to the attempted reloads?

**Comment by lilyball** [comment]
This issue is still important to me. However I don't know if it still occurs since I switched over to using `system.autoUpgrade.enable = true` instead of updating by hand. I just did a `nixos-rebuild switch` right now and didn't see the issue, but it was never 100% reproducible to begin with.

**Comment by lilyball** [comment]
Are there logs for the auto-upgrades anywhere I can check to see if this has still been happening?

**Comment by erictapen** [comment]
To me it looks like `nixos-upgrade.service` is doing the upgrades. So `journalctl -u nixos-upgrade.service`?

**Comment by bachp** [comment]
I haven't seen any issues since https://github.com/NixOS/nixpkgs/commit/3e7d650bcca2fb18cc05468878cbccfb06096f7b was merged

**Comment by benpye** [comment]
Unfortunately I still see the following:

```
reloading the following units: var-lib-unifi-dl.mount, var-lib-unifi-lib.mount
var-lib-unifi-dl.mount is not active, cannot reload.
var-lib-unifi-lib.mount is not active, cannot reload.
starting the following units: unifi.service
```

**Comment by lilyball** [comment]
I just ran that `journalctl` command on my auto-updating server, and the last time I see it reloading any `var-lib-unifi*` unit was June 7, 2020. This was before 3e7d650bcca2fb18cc05468878cbccfb06096f7b was merged. I’m rather surprised that it hasn’t had to reload more recently, since I do see more recent rebuilds of the associated derivation.

**Comment by lilyball** [comment]
Oh, apparently I’m still on 20.03. That might explain it.

**Comment by lilyball** [comment]
I just updated to 20.09 and immediately got the `var-lib-unifi-*.mount is not active, cannot reload` errors. I don’t know if the alleged fix requires the current setup to have it, or just the new setup.

**Comment by lilyball** [comment]
I just updated to nixos-21.05-small and got the same errors.

```
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, firewall.service, sys-kernel-debug.mount, var-lib-unifi-bin.mount, var-lib-unifi-data.mount, var-lib-unifi-dl.mount, var-lib-unifi-lib.mount
var-lib-unifi-bin.mount is not active, cannot reload.
var-lib-unifi-data.mount is not active, cannot reload.
var-lib-unifi-dl.mount is not active, cannot reload.
var-lib-unifi-lib.mount is not active, cannot reload.
```
