### ISSUE TITLE
SHA hash incorrect for ghcjs-boot

### ISSUE THREAD

**Issue by tel** [NixOS/nixpkgs#6143]
Or at least they're arbitrarily not matching. The following patch appears to work, but it ought to be diagnosed as to why the mismatch occurred.

```
diff --git a/pkgs/development/compilers/ghcjs/default.nix b/pkgs/development/compilers/ghcjs/default.nix
index e6798be..d2ee712 100644
--- a/pkgs/development/compilers/ghcjs/default.nix
+++ b/pkgs/development/compilers/ghcjs/default.nix
@@ -18,7 +18,7 @@ let
   ghcjsBoot = fetchgit {
     url = git://github.com/ghcjs/ghcjs-boot.git;
     rev = "5c7a71472d5a797e895914d3b82cea447a058793";
-    sha256 = "0dp97bgbnlr3sd9yfnk27p6dfv46fi26sn6y6qv1wxs5i29kmjav";
+    sha256 = "1c39qn5klcbpjdjwqqwkg4kn3frz5vpchv10rrd1awvlamx5ff0x";
     fetchSubmodules = true;
   };
   shims = fetchgit {
```

**Comment by peti** [comment]
Cc: @cstrahan

**Comment by copumpkin** [comment]
We talked about this a bit at compose conf this weekend. I think it's due to one or more files inside the repo differing only in case, so when you clone it onto Mac OS (default case-insensitive filesystem), those files overlap and you get a different output hash. Here's one of them that we found: https://github.com/basvandijk/case-insensitive/issues/17#issuecomment-72467114

**Comment by copumpkin** [comment]
cc @ryantrinkle @jwiegley

**Comment by tel** [comment]
Ha, on `case-insensitive` of all places. Good catch, though!

As `case-insensitive` itself is a submodule of ghcjs-boot it could be nothing more than getting ghcjs-boot to pull a version past that fix.

**Comment by ryantrinkle** [comment]
Luite bumped it: ghcjs/ghcjs-boot@16af87d7d8ba8c53511c11ca6ae75138550d6211

**Comment by copumpkin** [comment]
Cool, so we just need to bump the revision ghcjs-boot points at now?

**Comment by ryantrinkle** [comment]
Yep; I tried it locally and it worked for me on linux, but I haven't tried
on darwin.

**Comment by peti** [comment]
What is the state of this issue? Can we close it?

**Comment by ryantrinkle** [comment]
We will need a PR to actually bump the ghcjs-boot version.  I'm working on this, but with haskell-ng.  Do we want to try to maintain the old haskellPackages-based version?

**Comment by peti** [comment]
The old Haskell code is going to be removed from Nixpkgs, eventually; at latest when we switch to GHC 7.10.x because it doesn't support that compiler. Personally, I wouldn't bother trying to support it.

**Comment by ryantrinkle** [comment]
OK.  I will submit my haskell-ng ghcjs PR as soon as it's ready, and I won't worry about old-style.  Also, I'm using GHC 7.10 for that, anyway, because that's what Luite's focusing on for GHCJS itself.

**Comment by peti** [comment]
It feels alright to close this issue in favor of https://github.com/NixOS/nixpkgs/issues/5828.
