### ISSUE TITLE
Justify and document use of repositories.git meta attribute or remove it

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#61435]
## Issue description
There's a slew of [undocumented meta attributes](https://github.com/NixOS/nixpkgs/blob/76e2a964750802a93d9f33692acfe63d1df3035e/pkgs/stdenv/generic/check-meta.nix#L187) and one of them that has "68" occurrences is `repositories.git`.

Semantically one can discern that it's probably a link to a git repository, but its purpose and meaning is undocumented so it's left up in the air what or when to use it.
Because of this I don't want to introduce or merge any change in nixpkgs that uses this attribute
unless we **formally ratify it**.

This topic was catalyzed for me in https://github.com/NixOS/nixpkgs/pull/60176#discussion_r278285920 and https://github.com/NixOS/nixpkgs/pull/60198#discussion_r283153287.

My personal stance as of writing is that perhaps there's a need to have a meta attribute when somethings explicitly a source repository. But currently many `homepage` attributes are exactly that.

**Comment by jtojnar** [comment]
Also https://github.com/NixOS/nixpkgs/pull/60176#discussion_r278321164

**Comment by JohnAZoidberg** [comment]
nixpkgs-monitor checks if a newer version is available either by looking at the tags of the repo or the latest commit if its not using a release. (From what I can gather by quickly skimming the source)

**Comment by Artturin** [comment]
removed them in https://github.com/NixOS/nixpkgs/pull/165512
