### ISSUE TITLE
Haskell library system-fileio tests fail

### ISSUE THREAD

**Issue by tel** [NixOS/nixpkgs#6144]
Seems like a hardcoded path problem? The log is below.

```
Preprocessing test suite 'filesystem_tests' for system-fileio-0.3.16...
running tests
Running 1 test suites...
Test suite filesystem_tests: RUNNING...
[ ABORT ] posix.copyFile.iso8859
  Test aborted due to exception: /private/var/folders/lj/655x29_s66718hvw6bdcvy1w0000gn/T/nix-build-haskell-system-fileio-ghc7.8.4-0.3.16-shared.drv-0/tests.iso8859.48795/old_¡¢£.txt: openBinaryFile: does not exist (No such file or directory)

[ ABORT ] posix.withFile.read.iso8859
  Test aborted due to exception: /private/var/folders/lj/655x29_s66718hvw6bdcvy1w0000gn/T/nix-build-haskell-system-fileio-ghc7.8.4-0.3.16-shared.drv-0/tests.read.iso8859.48795/¡¢£.txt: openBinaryFile: does not exist (No such file or directory)

[ ABORT ] posix.withTextFile.iso8859
  Test aborted due to exception: /private/var/folders/lj/655x29_s66718hvw6bdcvy1w0000gn/T/nix-build-haskell-system-fileio-ghc7.8.4-0.3.16-shared.drv-0/tests.iso8859.48795/¡¢£.txt: openFile: does not exist (No such file or directory)

FAIL: 81 tests run, 66 tests passed, 12 tests skipped, 3 tests aborted
Test suite filesystem_tests: FAIL
Test suite logged to: dist/test/system-fileio-0.3.16-filesystem_tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

For now, I'm able to build with `doCheck = false`, though.

```
diff --git a/pkgs/development/libraries/haskell/system-fileio/default.nix b/pkgs/development/libraries/haskell/system-fileio/default.nix
index cf3dcee..5f5aa4c 100644
--- a/pkgs/development/libraries/haskell/system-fileio/default.nix
+++ b/pkgs/development/libraries/haskell/system-fileio/default.nix
@@ -17,4 +17,5 @@ cabal.mkDerivation (self: {
     license = self.stdenv.lib.licenses.mit;
     platforms = self.ghc.meta.platforms;
   };
+  doCheck = false;
 })
```

**Comment by peti** [comment]
Have you reported this issue to the library authors?

**Comment by tel** [comment]
I haven't. My nix-fu is weak, but it appears to be a nix packaging issue?

Or is the policy to try to convince library authors to ensure that all of their extra files are properly caught by cabal2nix?

A similar problem was occuring with `shake` a little while back, but I haven't tested it recently.

**Comment by peti** [comment]
What makes you think that this might be a Nix packaging issue?

Note that `cabal2nix` doesn't package anything. We build the distribution tarballs from Hackage.

**Comment by tel** [comment]
Because it appears to be failing to find a file `¡¢£.txt` in the location the test expects it to be. I suppose I'm working on the assumption that this test passes if you were to just `cabal fetch` it. I can confirm that.

**Comment by peti** [comment]
Again, we download release tarballs from Hackage, just like `cabal get` does. The environment this package builds in Nix is identical to that in which it builds on any other platform. There are no extra files, nor are there any files missing.

**Comment by peti** [comment]
Also, note that the test suite succeeds just fine when run on our CI: http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.system-fileio.x86_64-linux.

**Comment by tel** [comment]
Interesting, I'll dig in more and open the issue for the library itself.

**Comment by peti** [comment]
To me, it looks like the weird file name is causing trouble on your system, maybe because your file system or locale environment doesn't support it. I'm just guessing, though.

**Comment by peti** [comment]
Tests succeed on Hydra; seems to be an issue with the machine running the build that ought to be fixed upstream.

**Comment by tel** [comment]
Yep—I agree. Closing here.

**Comment by tel** [comment]
Thanks!

**Comment by jml** [comment]
I ran into this issue. @tel did you discover what it was about your system that made it fail? Is there an upstream bug I can follow?

**Comment by jml** [comment]
Never mind, found fpco/haskell-filesystem#5 which is the upstream bug.

**Comment by tel** [comment]
Yeah, I've been just sitting on it since then. It seems like a Mac+Unicode kind of thing.

**Comment by peti** [comment]
0af520573205a681545f9ef898158f5c84d92126 re-enables the test suite on Darwin.
