### ISSUE TITLE
Support for private subversion repositories

### ISSUE THREAD

**Issue by xbreak** [NixOS/nixpkgs#61457]
### Background

We have the need to use private svn repositories with Nix (and we don't have svn+ssh access). This means of course that we need to provide authentication credentials to `svn` in some way.
The most straight-forward alternatives, that are also supported without modifying subversion build, are to either use 

- single username/password or
- pre-populated simple authentication cache (`~/.subversion/auth`).

Both are insecure and should not represent best practice, but are nevertheless viable options.

Nix svn also has by default support for `gpg-agent`, which for credentials like this does not provide a password store afaik, but sort of acts as a in-memory cache of already provided credentials. This is not really what we need so I haven't pursued this much.

### WIP Implementation

I'm currently playing with and implementing support for this in `fetchsvn` and `nix-prefetch-svn` (if you agree I'll create a WIP PR after taking your comments into consideration).

The solution I used was inspired by `fetchgithub`, and uses impure environment variables to communicate to `fetchsvn`.

#### Example using `--username` and `--password`:

```nix
src = fetchsvn {
  privateSvnAuthEnvVar = "NIX_SVN_AUTH_MYREPO";
  url = "https://my.repo/trunk";
  rev = "1234";
  sha256 = "16121ws0c6wv52nwncrmwrfn5qw1az9sh20ij3bm0x3c0nhprh84";
};
```
Here I specify to use `NIX_SVN_AUTH_MYREPO` as a basename for `<basename>_USERNAME` and `<basename>_PASSWORD` and will be used with svn like (exposition): 

```sh
svn export --username=$NIX_SVN_AUTH_MYREPO_USERNAME --password=$NIX_SVN_AUTH_MYREPO_PASSWORD $url ...
```
#### Example of authentication cache

```nix
src = fetchsvn {
  privateSvnAuthCacheEnvVar = "NIX_SVN_AUTH_CACHE";
  url = "https://my.repo/trunk";
  rev = "1234";
  sha256 = "16121ws0c6wv52nwncrmwrfn5qw1az9sh20ij3bm0x3c0nhprh84";
};
```
Here I specified to use the env. variable `$NIX_SVN_AUTH_CACHE` to specify a svn auth cache location (e.g. a copy from an already populated `~/.subversion/auth`).
If cache is found, I copy the files in the `builder.sh` script to a temporary `HOME` to be used by svn (this is also already done for http-proxy settings).

`nix-prefetch-svn` essentially works the same way, but is refactored to take optional command line arguments for this instead of env. vars.

### Open Questions

1. Is this something that could potentially be accepted in Nixpkgs? I don't think this will introduce any backward incompatible changes.
2. Is there a more "nix-onic" approach to this that I should use instead? I'd love if there was a more unified secrets management solution that could be adopted for example.
3. For my uses I'd also need JSON output from `nix-prefetch-svn` like `nix-prefetch-git`. Can I do this in the same PR or should I do that separately?
4. If someone has positive experience with using svn with e.g. gnome-keyring in "batch" mode, I'd be very interested in hearing it.
5. Can I assume the current output of `nix-prefetch-svn` is "porcelain" and not meant for machine parsing?
6. Any other thoughts?

**Comment by edolstra** [comment]
I'm not really keen on adding more private repo fetchers because they are a pain-in-the-ass to configure/use. In particular, they don't work very well in conjunction with multi-user builds and the Nix daemon (since the nixbld* users somehow need access to the user's credentials).

Adding a `builtins.fetchSubversion` function (similar to `builtins.fetchGit`) would be better, because then fetching is done in the context of the calling user, so there are no issues with access to credentials.

**Comment by xbreak** [comment]
@edolstra: That's understandable. It's also not a big problem either for us since we can provide a solution in our overlay in the meantime.

When you say "fetching is done in the context of the calling user", how does that work with the nixbld* users? Wouldn't the credentials have to be provided to all of them?

Thanks!

**Comment by FRidh** [comment]
Closing because this fits better in the Nix repo.
