### ISSUE TITLE
Memtest86+ 5.01 reboots when started

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nixpkgs#6145]
This first occurred in #4678, but after testing it seems that this is an issue unrelated to the syslinux bootloading since it also occurs in grub with iso_minimal on commit 2d19af8.

I see 3 possible solutions:

1. Fixing memtest86+ 5.01 somehow
2. Reverting to memtest86+ 4.20
3. Switching the ISO to memtest86 instead of memtest86+

**Comment by lethalman** [comment]
cc @edolstra

**Comment by Profpatsch** [comment]
(triage) fixed?

**Comment by bobvanderlinden** [comment]
Yes, #6593 fixed the issue. Thanks for the notification.
