### ISSUE TITLE
`kitty` complains about missing EGL under Wayland

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#61470]
## Issue description

```
$ kitty
[133 14:00:58.682327] [glfw error 65542]: EGL: Library not found
[133 14:00:58.682352] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

This is despite OpenGL and glfw already being the package's buildInputs.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by colemickens** [comment]
It looks like Wayland support in GLFW is experimental, and not currently enabled in nixpkgs. I'll experiment with this a bit.

**Comment by danieldk** [comment]
Interestingly enough, Kitty worked fine for me on my machine with Wayland until the last batch of updates. Seems like the update to Kitty 0.14.0 has broken Kitty on Wayland for me (the same error as you are getting).

**Comment by danieldk** [comment]
I've found the problem: Kitty 0.14.0 has switched to the Wayland backend by default on Wayland. Setting

~~~
export KITTY_DISABLE_WAYLAND=1
~~~

makes Kitty work again.

**Comment by colemickens** [comment]
Yeah, but I specifically am running Wayland and expect it to work in
Wayland.

**Comment by danieldk** [comment]
It seems that Kitty uses its own copy of glfw, which dynamically loads `libEGL.so.1`, which cannot be found. With the following change to the derivation, the error goes away and Kitty runs with the Wayland backend. Though, window controls are missing in GNOME and attempting to resize or drag the window causes a lot of flickering.

https://gist.github.com/danieldk/aff114edfaa6673271ca7e6646066f7a

**Comment by colemickens** [comment]
@danieldk Interesting, good finds! I had noticed GLFW was involved, but it seemed like I could only build it with X11 or Wayland support, not both. Clearly I don't understand how it works.

Anyway, I use sway, so I'd be fine to not have window controls. I would've expected them to sniff that they were in a DE that wants window decorations and enable them, but maybe the Wayland support just isn't that mature yet. As for flickering, I'm not sure, I know of some Sway bugs around client redraws, but don't really know what the situation or expectations are under GNOME these days.

**Comment by Luflosi** [comment]
Is your patch still required in the latest version? That may have changed because of https://github.com/kovidgoyal/kitty/commit/277f43aed6760d652e0e4dd741a5ce326bdad3b1. If it is still required, then you may want to make it available for all users installing kitty using nix.

**Comment by danieldk** [comment]
The patch should still be relevant outside GNOME. I'll try to look at making a PR later today.

**Comment by Luflosi** [comment]
I think this issue can be closed now as the PR has been merged.

**Comment by Luflosi** [comment]
I'm closing this issue, since the PR has been merged.
