### ISSUE TITLE
Sublime 3 is broken

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#61488]
Sublime 3 output: https://gist.github.com/suhr/c4a5f12e3101627435dbd557bbf71ff8

**Comment by suhr** [comment]
@wmertens

**Comment by ivan** [comment]
Sublime Text 3 is working in nixpkgs master for me, what are you running?

**Comment by suhr** [comment]
NixOS, channel: nixos-unstable (current).

**Comment by angristan** [comment]
I can reproduce this on unstable (same output).

**Comment by angristan** [comment]
The latest commit to sublime3 is pretty heavy, it might be related? https://github.com/NixOS/nixpkgs/commit/148119b9a6636a4fdfbdc1cc0dcbf268d523008d#diff-47ffe5ddc921c71b88117a8e1627fcb9

**Comment by worldofpeace** [comment]
Please see https://github.com/NixOS/nixpkgs/issues/60807#issuecomment-489327589.

This issue has been fixed in staging.
