### ISSUE TITLE
Adding a Postgres plugin restarts Postgres

### ISSUE THREAD

**Issue by jamessewell** [NixOS/nixpkgs#61480]
## Issue description
Using the new Postgresql design when extensions are added to Postgresql using extraPlugins a new `postgresql-and-plugins` derivation is created. 

While this solves a lot of other issues, one it creates is that adding extensions causes the Postgresql service to be restarted (which isn't strictly needed).

### Steps to reproduce

Start a postgresql service, add

```
extraPlugins = [ pg_hll ] 
```

to the config and switch to it - a new `postgresql-and-plugins` derivation will be created and activated, which will cause a service stop / start.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 19.09pre179307.bc94dcf5002 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(jirotech): `""`
 - channels(root): `"nixos-19.09pre179307.bc94dcf5002"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jbboehr** [comment]
You can probably disable this behavior for your own use case by setting `systemd.services.postgresql.restartIfChanged = false`. I believe this will apply to any change that would normally restart the service, however.

Example current usage:
https://github.com/NixOS/nixpkgs/blob/3464b50c618931bd8259c830ee2fd734aeab38f9/nixos/modules/services/security/vault.nix#L133

**Comment by volth** [comment]
I guess without restarting no plugin would be added, because the running ```postgresql-and-plugins``` has no plugin

**Comment by danbst** [comment]
@jamessewell unfortunately, this would be left as by-design for now.

There are a few problems, some PG related, some Nix related.
- not every plugin can be added without restart (`shared_preload_libraries`). We want to distinguish "requires restart" event during normal activation, but NixOS doesn't handle this very good now. For example, I don't want PG restarts, but if I have to, I want to be notified. NixOS doesn't notify about this currently
- the design of Nix and NixOS is to be purely functional/atomic, but reloadable PG can only be implemented with some kind of state. Currently, the only place in NixOS which manages state correctly, is `environment.etc`, or `/etc/static` directory. So the implementation should put plugins there and then wrap PG with `NIX_PGLIBDIR=/etc/static/pg-plugins/...`. :/

So stick to restarts for now. I've created meta-issue https://github.com/NixOS/nixpkgs/issues/65296 to track this
