### ISSUE TITLE
regression in clang 8 package with regards to -cc1as parameters

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#61501]
## Issue description

After updating to `19.09pre178260.190727db4ea (Loris)`, the [Zig](https://ziglang.org/) self-hosted compiler fails to build from source using the nixpkgs clang package (although it works fine with clang built from source).

This is a regression, which did not exist in a previous version of the clang/llvm 8 nixpkgs package.

### Steps to reproduce

```nix
with import <nixpkgs> {}; {
  tmpAoeu = stdenv.mkDerivation {
    name = "tmpAoeu";

    hardeningDisable = [ "all" ];
    buildInputs = [
      cmake
      llvmPackages_8.clang-unwrapped
      llvm_8
    ];
  };
}
```

```
$ nix-shell the_above_file.nix
$ git clone https://github.com/ziglang/zig
$ mkdir zig/build
$ cd zig/build
$ cmake ..
$ make
./zig -cc1as -triple x86_64-unknown-linux-gnu a.s
```

Expected output, and the output you get if you use llvm/clang built from source:

```
clang -cc1as: error: error reading 'a.s'
```

Actual output:

```
clang -cc1as: error: unknown target triple 'unknown', please use -triple or -arch
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 19.09pre178260.190727db4ea (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(andy): `""`
 - channels(root): `"nixos-19.09pre178260.190727db4ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

cc @dtzWill

**Comment by matthewbauer** [comment]
Do you know the last good commit? It's possible some of the Clang cross compilation changes effect this, but I didn't think they touched clang-unwrapped at all.

**Comment by andrewrk** [comment]
Is there a command I can run to find out the previous version before I did `nixos-rebuild switch --upgrade` ?

**Comment by matthewbauer** [comment]
> Is there a command I can run to find out the previous version before I did `nixos-rebuild switch --upgrade` ?

Yes, you can get your channels history with:

```
sudo nix-env --list-generations --profile /nix/var/nix/profiles/per-user/root/channels
```

and try to figure out what channel number N you have. Then get the hash with:

```
cat /nix/var/nix/profiles/per-user/root/channels-N-link/nixos/.git-revision
```

**Comment by andrewrk** [comment]
Previous version was acbdaa569f4ee387386ebe1b9e60b9f95b4ab21b

**Comment by matthewbauer** [comment]
Is there a way to dump what flags zig is passing? I tried doing this, and it seems to work as expected:

```
touch a.s
nix run -f https://github.com/NixOS/nixpkgs-channels/archive/190727db4ea.tar.gz llvmPackages_8.clang-unwrapped -c clang -cc1as -triple x86_64-unknown-linux-gnu a.s
```

**Comment by andrewrk** [comment]
I just tried to reproduce this in a separate gist and I was unable to. There's still a mysterious difference between the nixos package and a build from source, but I'll close this until I can come back with an easier repro. Thanks for your time
