### ISSUE TITLE
unison: currently tied to OCaml 4.05, should switch to OCaml 4.06

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#61505]
The `unison` package is currently being pulled from the `ocaml-ng.ocamlPackages_4_05` set because it won't compile (with `enableX11`) when using OCaml 4.06. This was fixed in unison trunk but the latest release (2.51.2) does not include it. At such time as unison puts out a new release, we should change the top-level `unison` package to come from `ocamlPackages` instead of `ocaml-ng.ocamlPackages_4_05`.

See https://github.com/bcpierce00/unison/issues/245 for tracking the release of a new unison version.

**Comment by vbgl** [comment]
Closed by #82619.
