### ISSUE TITLE
Update far2l to use newer llvmPackages

### ISSUE THREAD

**Issue by thoughtpolice** [NixOS/nixpkgs#61511]
## Issue description

Assuming https://github.com/NixOS/nixpkgs/pull/61509 is merged, `far2l` is currently the only package that still uses `llvmPackages_4`, meaning it can be removed once it is no longer needed by this expression. It would be excellent to remove older LLVM builds if we can, since they're expensive to maintain (code wise) and take up plenty of resources on the builders.

Currently it seems `far2l` only uses `llvmPackages_4.stdenv` if the `stdenv` is set to using Clang; in other words, I assume this is a fix for building it on Darwin.

/cc @volth, who maintains `far2l`

**Comment by volth** [comment]
1. I cannot test it, because ```far2l``` uses ```llvmPackages_4.stdenv``` only on Darwin. At least, feel free to remove Darwin from the supported ```meta.platforms``` of ```far2l```.
2. I do not like idea of removing ```Clang 3.5``` ... ```Clang 4.0```; They are needed quite often to compile some random project found on Github. Same of ```GCC 4``` ... ```GCC 6```

**Comment by volth** [comment]
I meant I am not ready to maintain Darwin ports of the packages I maintain.
A co-maintainer is required here, if there will be no one, then just remove all ```"x84_64-darwin"``` and ```if isDarwin``` and it should solve the llvm problem.

**Comment by volth** [comment]
@LnL7  for https://github.com/NixOS/nixpkgs/commit/879f144d7fb4d49cf2afacbc4e84e045d519c792

**Comment by LnL7** [comment]
The older llvm might not be necessary anymore if the package has updated since then or using `gccStdenv` instead could also work.

**Comment by FliegendeWurst** [comment]
This was fixed eventually.
