### ISSUE TITLE
file builds fine on OS X

### ISSUE THREAD

**Issue by tel** [NixOS/nixpkgs#6151]
No troubles identified so far

```
diff --git a/pkgs/tools/misc/file/default.nix b/pkgs/tools/misc/file/default.nix
index 0158209..ae7b628 100644
--- a/pkgs/tools/misc/file/default.nix
+++ b/pkgs/tools/misc/file/default.nix
@@ -13,6 +13,6 @@ stdenv.mkDerivation rec {
   meta = {
     homepage = "http://darwinsys.com/file";
     description = "A program that shows the type of files";
-    platforms = with stdenv.lib.platforms; allBut darwin;
+    platforms = with stdenv.lib.platforms; all;
   };
 }
```

**Comment by copumpkin** [comment]
Perhaps open things like this as a PR?

**Comment by tel** [comment]
I can do that. I kept it as an issue mostly due to uncertainty about the best way to contribute to Nix broadly and this whole "Nix on OS X" push specifically.

**Comment by copumpkin** [comment]
Ah, I think it's good to do PRs against master for things like this. I
merge regularly into pure-Darwin, so I'll get it. Would only make PRs
against PD if they don't work on master yet :)

**Comment by tel** [comment]
Alright. Closing this to move to a PR.

Also, I suppose this should just be `stdenv.lib.platforms.all`.
