### ISSUE TITLE
Biber shebang error

### ISSUE THREAD

**Issue by alexarice** [NixOS/nixpkgs#61520]
## Issue description
Biber throws the following error
```
/usr/bin/env: ‘perl -I/nix/store/jq7q89w657sh98mgzqmlby25nagp80ak-perl-5.28.2/lib/perl5/site_perl -I/nix/store/sla00g54d3nwmdd0’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

### Steps to reproduce
Install `texlive.combined.scheme-full`
run `biber` from command line or emacs

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.41, NixOS, 19.09pre179307.bc94dcf5002 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(alex): `""`
 - channels(root): `"nixos-19.09pre179307.bc94dcf5002"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Just noticed this with `po4a-translate ` as well.

**Comment by alexarice** [comment]
any idea what is causing it?

**Comment by worldofpeace** [comment]
Nope, probably someone will have to bisect. 

cc @volth

**Comment by volth** [comment]
Works ok on my ```<nixpkgs>```, which is 2 weeks behind master but it has all Perl-related PRs cherry-picked

**Comment by alexarice** [comment]
Happy to have a go at bisecting this later today if no one else does

**Comment by alexarice** [comment]
Haven't finished yet but https://github.com/NixOS/nixpkgs/commit/a1533dfc414961bb723937c111f5fe0925411f75 is likely the culprit

**Comment by alexarice** [comment]
So 61bc03c017f18e2fe54d209ae8ba8a42033b9564 doesn't build
a1533dfc414961bb723937c111f5fe0925411f75 This one I haven't tried
ec7d72a57d5ba18a35451b174e2f3c8d4a425b94 This one is bad

@matthewbauer Can you remember what these commits do and have any idea why this is causing problems

**Comment by matthewbauer** [comment]
Thanks for tracking this down!  I think we can modify the perl builder to address this:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/perl-modules/generic/default.nix#L39

by adding perl to buildInputs. I'm hoping that perl is the only thing effected...

**Comment by teto** [comment]
arg I lost much time before a deadline before realizing biber failed. Vimtex hid the error from me. guess that's part of the fun being on unstable xD

**Comment by worldofpeace** [comment]
Guess this is the proper way to fix this then https://github.com/worldofpeace/nixpkgs/commit/d8d2231f3ef792ad04594c921762369459a09a43.

Haven't tested it though.

**Comment by alexarice** [comment]
> Guess this is the proper way to fix this then [worldofpeace@d8d2231](https://github.com/worldofpeace/nixpkgs/commit/d8d2231f3ef792ad04594c921762369459a09a43).
> 
> Haven't tested it though.

Fixes the problem for me

**Comment by teto** [comment]
I haven't had any problem recently so I think this is fixed. Feel free to reopen

**Comment by worldofpeace** [comment]
I haven't either, pretty sure it should be fixed too.
