### ISSUE TITLE
network-manager doesn't work

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#61531]
## Issue description

On nixos-unstable network stop to work after `nixos-rebuild switch`. Only `systemctl restart network-manager` makes it work again. Does anybody knows what is the issue?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by worldofpeace** [comment]
Can we get your nixpkgs revisions before and after the rebuild switch?

**Comment by samdoshi** [comment]
This happens to me too, I believe the issue is a duplicate of #61490

**Comment by teto** [comment]
closing as duplicate of #61490
