### ISSUE TITLE
devede broken on 19.03

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#61578]
## Issue description
The `devede` package is broken in 19.03.

### Steps to reproduce
~> nix-shell -p devede --run devede_ng.py
Traceback (most recent call last):
  File "/nix/store/545kqgnp1qaz9fx5lh1vjq2341h26mps-devede-4.8.8/bin/..devede_ng.py-wrapped-wrapped", line 22, in <module>
    gi.require_version('Gtk', '3.0')
  File "/nix/store/9jyqlkf8q1disirs79pqh5pwcdxhmd9f-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.03.172347.7936400662b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172347.7936400662b"`
 - channels(aaron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
@aanderse See https://github.com/NixOS/nixpkgs/issues/56943.

You need to disable `strictDeps` like the commits that reference the issue until we can fix it.

**Comment by aanderse** [comment]
Yeah I have seen one of these already and didn't have time to test/fix this tonight so just wanted to get it logged. I'll self assign and circle back to this hopefully in the next few days.

**Comment by aanderse** [comment]
@worldofpeace in this case adding `strictDeps = false;` did not fix the issue, but adding `gobject-introspection` to `buildInputs` did.
