### ISSUE TITLE
pulseaudio module broken on aarch64

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#61571]
## Issue description
`Package ‘aften-0.0.8’ in /nix/store/7psnkxhzzjxw504kj4z9fi1m41s8yjqr-nixos-19.09pre179307.bc94dcf5002/nixos/pkgs/development/libraries/aften/default.nix:16 is not supported on ‘aarch64-unknown-linux-gnu’, refusing to evaluate.`

aften was always broken on aarch64. In this commit, aften is added as a dependency for jack2 also on Linux:
https://github.com/NixOS/nixpkgs/commit/6e7cc807ffa7549ea089a9599d1d73536365fbdd
The pulseaudio module uses alsaPlugins in its config file, which in turn depends on jack2 which depends on aften.

### Steps to reproduce

`hardware.pulseaudio.enable = true;` on an aarch64 linux machine

## Technical details

 - system: `"aarch64-linux"`
 - host os: `Linux 4.14.98, NixOS, 19.09pre179307.bc94dcf5002 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172619.f5493bf6145, stable-19.03.172619.f5493bf6145"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by petabyteboy** [comment]
My suggestion: Either fix aften build on aarch64 before the next release, or try to build jack2 without aften on linux again.

**Comment by petabyteboy** [comment]
For those looking for a quick fix:
```
  nixpkgs.overlays = [
    (self: super: {
      alsaPlugins = super.alsaPlugins.override {
        libjack2 = null;
      };
    })
  ];
```
Not a lot of packages depend on alsaPlugins, so it will not recompile your entire system.

**Comment by lopsided98** [comment]
Using the latest upstream commit fixes the build. We could try to backport a patch or just use the latest commit. There are no tagged versions so it is hard to figure out which commit corresponds to the 0.0.8 release. Also, the project is abandoned, with no commits since 2011.

**Comment by worldofpeace** [comment]
> Using the latest upstream commit fixes the build. We could try to backport a patch or just use the latest commit. There are no tagged versions so it is hard to figure out which commit corresponds to the 0.0.8 release. Also, the project is abandoned, with no commits since 2011.

It seems ubuntu just builds from latest in the repo https://packages.ubuntu.com/source/eoan/aften.

We should try to drop abandoned software as much as possible, so I'm in favor of just removing it from nixpkgs and jackaudio completely.

**Comment by worldofpeace** [comment]
Pretty sure this is fixed now.
