### ISSUE TITLE
Security: Intel Microarchitectural Data Sampling aka Zombieload

### ISSUE THREAD

**Issue by brainrape** [NixOS/nixpkgs#61599]
## Issue description

A new vulnerability was discovered in Intel processors, requiring a kernel update.
https://www.intel.com/content/www/us/en/architecture-and-technology/mds.html
https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html
http://lkml.iu.edu/hypermail/linux/kernel/1905.1/05371.html

### Steps to reproduce

`uname -a`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.43, NixOS, 19.09pre179853.bc9df0f6611 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre179853.bc9df0f6611"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lopsided98** [comment]
All kernels appear to have been updated, on unstable and 19.03. In fact, the kernel you are running right now (4.19.43) is not vulnerable. I believe this issue can be closed.

**Comment by vcunat** [comment]
I picked the updates to 18.09, too.  There are some less-maintained kernel patch-sets lying in nixpkgs, e.g. `linux_hardkernel_4_14` (.102), but I'm not sure if it's worth keeping this issue open just because of those...

**Comment by brainrape** [comment]
Thanks!

**Comment by lopsided98** [comment]
#61715 updates `linux_hardkernel_4_14`.
