### ISSUE TITLE
nmap broken on new Darwin stdenv

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#61595]
`nmap` broke with the new Darwin stdenv changes. See log file here:

https://gist.github.com/dhess/6036918826b8fc97ac38947b082a75e3

This is a bit odd because Homebrew doesn't appear to be doing anything special to compile it:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/nmap.rb

**Comment by matthewbauer** [comment]
I think we can use llvm 6 here to fix this. It is weird homebrew doesn’t hit this though. I wonder if the SDKs are still on libcxx 6?
