### ISSUE TITLE
docker-machine-xhyve 0.4.0 was just released

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#61601]
## Issue description

Docker-machine 0.4.0 was just released upstream: [Compare](https://github.com/machine-drivers/docker-machine-driver-xhyve/compare/v0.3.3...v0.4.0).

This version resolves the issue with the driver when Virtualbox 6 is installed. See https://github.com/machine-drivers/docker-machine-driver-xhyve/pull/214 for context.

Assigning to @periklis listed as the maintainer for the package.

**Comment by lasers** [comment]
Please revisit this again. This should be fixed already by 475bf6d2a5f3ba2e4c3d2b31b6e54f26e1aa7163.

**Comment by SuperSandro2000** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/75432
