### ISSUE TITLE
mkForce on environment.etc.*.source does not have "forcing" effect

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#6161]
(@nbp, here is the issue/reminder you asked for.)

From the nix-dev mailing list (http://lists.science.uu.nl/pipermail/nix-dev/2015-February/016039.html):

@bjornfor wrote:
> @nbp wrote:
>> The following should work:
>>
>>   environment.etc."ssl/certs/ca-bundle.crt".source = lib.mkForce ...;
>
> Unfortunately it does not. That also results in "mismatched duplicate
> entry ..." error.

**Comment by nbp** [comment]
I am working on this issue.

**Comment by nbp** [comment]
I am adding tests cases, and so far I was not able to reproduce this issue on top of master.
Can you mention which version of nixos you are based on, and possibly other parts of your configurations such that I can reproduce.

I tried redefining inputrc, and failed to reproduce the above issue on 15.05.
Are you sure this error message was related to this option definition?

**Comment by bjornfor** [comment]
I'm on nixos-version 14.12.374.61adf9e (Caterpillar).

My full config is here[1], but I don't think my other settings are relevant.

If I add

```
  # /etc/hosts was the first file I found and its content is irrelevant for this test :-)
  environment.etc."ssl/certs/ca-bundle.crt".source = lib.mkForce "/etc/hosts";
```

I get

```
$ nixos-rebuild build
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/03sb9cxrqi24zsh84gqjln7f69ki9nwy-etc.drv
  /nix/store/q8lnh5031yqivrj4af3nbqghwvgcz90p-nixos-14.12.374.61adf9e.drv
building path(s) ‘/nix/store/979fja3n3bgmrxkg3wgjypvvv729h2cz-etc’
duplicate entry ssl/certs/ca-bundle.crt -> /nix/store/axlmi5nry426xzq62v62j75v9rdv74za-cacert-20140715/etc/ca-bundle.crt
mismatched duplicate entry /etc/hosts <-> /nix/store/axlmi5nry426xzq62v62j75v9rdv74za-cacert-20140715/etc/ca-bundle.crt
builder for ‘/nix/store/03sb9cxrqi24zsh84gqjln7f69ki9nwy-etc.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/q8lnh5031yqivrj4af3nbqghwvgcz90p-nixos-14.12.374.61adf9e.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/q8lnh5031yqivrj4af3nbqghwvgcz90p-nixos-14.12.374.61adf9e.drv’ failed
```

[1] https://github.com/bjornfor/nixos-config/blob/master/configuration.nix

**Comment by bjornfor** [comment]
@nbp: I was just testing, now at 14.12.471.1f09b77 (Caterpillar), and the issue is gone: mkForce really does force that value :-)

Did you fix it? Where? I don't see anything relevant in range https://github.com/NixOS/nixpkgs/compare/61adf9e27fca4dc44d25c0925b52841f92cfa37a...1f09b7763408792fcbbb6fd57aced09ebbb558c4. Now I'm confused as to what happened with my system earlier...

**Comment by nbp** [comment]
No I did not change anything.
I do not see any modification which could explain such difference.

**Comment by bjornfor** [comment]
I cannot reproduce it.
