### ISSUE TITLE
Package Request: Scribes

### ISSUE THREAD

**Issue by MicrosoftTakeover** [NixOS/nixpkgs#61638]
Scribes is a simple yet powerful text editor for GNOME

http://scribes.sourceforge.net

https://launchpad.net/scribes/

**Comment by jtojnar** [comment]
Also https://github.com/mystilleef/scribes

Scribes was amazing editor. Unfortunately, it is no longer maintained and depends on some ancient abandoned libraries like pygtk and gconf :crying_cat_face:

**Comment by MicrosoftTakeover** [comment]
@jtojnar I've discovered the editor 'howl' which reminds me of Scribes. You might want to check it out.

**Comment by MicrosoftTakeover** [comment]
Since this software is no longer maintained I'm going to close this issue for now.
