### ISSUE TITLE
libtool on darwin

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#6163]
In order to build `crypto++` on darwin, I had to override `nativeBuildInputs` to use `binutils` instead of `libtool`. The problem, I think, is that the `libtool` dependency pulls in GNU libtool which takes different flags than Apple's `libtool`. Tweaking the definition of `libtool` in `all-packages` is tricky as it tends to run into infinite recursion.

**Comment by wmertens** [comment]
@copumpkin how is this handled in pure-darwin? If the package uses Apple
libtool on Darwin and GNU libtool elsewhere that should be codified or
patched, right?

**Comment by copumpkin** [comment]
It's kind of annoying: darwin's cctools (which contains most of the binutils equivalents for darwin) contains its own libtool, but is missing other things you'd find in binutils. This means that you get things like libtool that you didn't ask for, and not other things that you might expect (like c++filt).

I finally got the gnu binutils build working on darwin yesterday so things should improve soon, and I'll mix and match the tools to get something that closely resembles binutils on linux, except with proper darwin tools where applicable. 

My current plan is to try to get as much of pure-darwin upstream as possible (in the next few days), and then fix this issue once it's there. If someone wants to go for it sooner I'm happy to advise.

**Comment by Profpatsch** [comment]
(triage) solved?

**Comment by safareli** [comment]
can you clarify how did you fixed the issue @acowley? I have sort of similar issue

**Comment by acowley** [comment]
I don't know what's changed in the intervening years. I see that `crypto++` has a darwin-specific patch that might help in a similar situation.

```
-AR = libtool
-ARFLAGS = -static -o
+AR = ar
+ARFLAGS = cru
```
