### ISSUE TITLE
nix-prefetch-url: URLs containing special characters are not supported

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixpkgs#6165]
Using either `nix-prefetch-url` or directly using `fetchurl` from withing a derivation, I get an error.

~~~
$ nix-prefetch-url http://www.youneedabudget.com/CDNOrigin/download/ynab4/liveCaptive/Win/YNAB%204_4.3.656_Setup.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.1M  100 20.1M    0     0  2318k      0  0:00:08  0:00:08 --:--:-- 2529k
invalid character â%â in name âYNAB%204_4.3.656_Setup.exeâ at /run/current-system/sw/bin/nix-prefetch-url line 124.
~~~

It seems to have a hard time with the space character (`%20`). I also tried to replace the encoded
space with a normal space but it still fail.

Also, `wget` is perfectly capable of fetching the file. Browsers have no trouble either.

**Comment by CestDiego** [comment]
I have this problem as well when trying to download a single file out of a github repository (the spaces) 

https://raw.githubusercontent.com/CestDiego/nerd-fonts/0.4.1/patched-fonts/SourceCodePro/Sauce%20Code%20Powerline%20Plus%20Nerd%20File%20Types%20Mono%20Plus%20Font%20Awesome%20Plus%20Octicons%20Plus%20Pomicons.otf

it has the same error about invalid characters.

**Comment by vcunat** [comment]
`fetchurl` is perfectly fine with such, only you need to also specify `name` of the *output* path which is what mustn't contain some characters. I don't know if `nix-prefetch-url` has a parameter for that.

**Comment by CestDiego** [comment]
@vcunat nix-prefetch-url doesn't have a parameter for that and that's because that saves the downloadied item into the nix store with a predefined hash prepended. maybe we could sanitize the filename so that the new generated output file in the nix store replaces `spaces` with `-` (dashes) ?

**Comment by vcunat** [comment]
Predefined hash?? Both tools use the basename of the URL as the default suffix after the dash. `nix-prefetch-url` doesn't (yet) allow you to override it.

We could alternatively agree on some sanitizing algorithm for both. (And this isn't just about spaces.)

**Comment by CestDiego** [comment]
I'm sorry ye..the hash is determined by the basename of the URL.... I need my coffee... we could just look at what wget or curl use and go with that.

**Comment by vcunat** [comment]
You just assumed that. The hash of the output is truncated sha1 of the **content** of the file in base32.

**Comment by rasendubi** [comment]
(triage) still an issue

```
rasen@Larry ~ % nix-prefetch-url http://www.youneedabudget.com/CDNOrigin/download/ynab4/liveCaptive/Win/YNAB%204_4.3.656_Setup.exe
downloading ‘http://www.youneedabudget.com/CDNOrigin/download/ynab4/liveCaptive/Win/YNAB%204_4.3.656_Setup.exe’... [0/0 [19395/20656 KiB, 2690.8 KiB/s]
error: invalid character ‘%’ in name ‘YNAB%204_4.3.656_Setup.exe’
```

**Comment by edolstra** [comment]
Fixed in NixOS/nix@f08449ccbd2009b858aae18341aedf3d0829b91a.

**Comment by jraygauthier** [comment]
thanks.

**Comment by ashgillman** [comment]
Just to confirm I understand, every time you wish to include such a url, you must prefetch it first using --name. You can't change the name within fetchurl?

**Comment by vcunat** [comment]
`fetchurl` had the optional `name` parameter before, but `nix-prefetch-url` knows nothing about the expression you want to use.

**Comment by 573** [comment]
Is [this](https://nest.pijul.com/pmeunier/carnix/discussions/29) a related question?
