### ISSUE TITLE
MATE keyboard shortcuts settings incomplete

### ISSUE THREAD

**Issue by smithtim** [NixOS/nixpkgs#61677]
## Issue description

Using MATE, under Keyboard Shortcuts, the only two categories are "Sound" and "Desktop". I do not see "Window Management", "Accessibility", or any other categories.

There was a similar issue with GNOME: #19590.

### Steps to reproduce

In MATE, go to System -> Preferences -> Hardware -> Keyboard Shortcuts.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 18.09.2096.2ff7ef373e5 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
This has been fixed in on master in https://github.com/NixOS/nixpkgs/pull/60401.
Your host appears to be on `18.09` so it will be broken there because it doesn't have this fix.

**Comment by smithtim** [comment]
I am on the `unstable` channel, so after a `nix-channel --update` and `nixos-rebuild switch`, I now see the missing shortcuts.  Thanks!
