### ISSUE TITLE
rev different betwen nix-prefetch-git and prefetch-github

### ISSUE THREAD

**Issue by Rizary** [NixOS/nixpkgs#61678]
Hi, if I am running `nix-prefetch-github --nix` without specify `--rev` option, why the result is different from `nix-prefetch-git` command?

`nix-prefetch-github` seems prefetch old `rev` instead of newest like `nix-prefetch-git` did. Can you explain about this?Is this intended result from `nix-prefetch-github`?

**Comment by worldofpeace** [comment]
This appears to be detail in a `nix-prefetch-github` as you've reported https://github.com/seppeljordan/nix-prefetch-github/issues/9

and not an issue with `nix-prefetch-git` which is maintained in nixpkgs.
