### ISSUE TITLE
Cannot override zlib with .extend overlay

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#61682]
Current nixpkgs `master`, this should break (because I set `zlib = 1`) but has no effect:

```
nix-build --no-link -E '((import <nixpkgs> {}).extend (final: previous: { zlib = 1; })).zlib'
```

In contrast, this breaks as expected:

```
nix-build --no-link -E '((import <nixpkgs> {}).extend (final: previous: { git = 1; })).git'
```

Why does overriding `zlib` specifically have no effect?

I found this problem because my override for `zlib` does absolutely nothing.

**Comment by nh2** [comment]
@tilpner found the reason:

`bootstrap-stage4` of `pkgs/stdenv/linux/default.nix` sets `zlib` and a few others:

https://github.com/NixOS/nixpkgs/blob/96e513df82579114bb95f899d7dae7b8eefb9219/pkgs/stdenv/linux/default.nix#L279

And over in `stage.nix` we have:

https://github.com/NixOS/nixpkgs/blob/96e513df82579114bb95f899d7dae7b8eefb9219/pkgs/top-level/stage.nix#L230-L244

Here `stdenvOverrides` is applied _last_:

```nix
  # The complete chain of package set builders, applied from top to bottom.
  # stdenvOverlays must be last as it brings package forward from the
  # previous bootstrapping phases which have already been overlayed.
  toFix = lib.foldl' (lib.flip lib.extends) (self: {}) ([
    # ...
  ] ++ overlays ++ [ stdenvOverrides ]);
```

I think this means that none of `gettext gnum4 bison gmp perl texinfo zlib linuxHeaders` are overridable.

**Comment by tilpner** [comment]
Might also be

https://github.com/NixOS/nixpkgs/blob/96e513df82579114bb95f899d7dae7b8eefb9219/pkgs/stdenv/linux/default.nix#L376-L381

instead of stage 4.

**Comment by nh2** [comment]
What can we do about it?

Overriding `zlib` is very useful, and necessary for some use cases.

**Comment by matthewbauer** [comment]
I think we can fix this by adding a stage 5 that sets ```overrides = _: _: {}``` and ```allowedRequisites = null``` /cc @ericson2314

This can also be avoided by using crossOverlays which has higher precedence than the stdenvOverrides:

```
nix-build -E '(import <nixpkgs> {crossOverlays = [ (_: _: { zlib = 1; }) ]; }).zlib'
```

**Comment by nh2** [comment]
@matthewbauer @Ericson2314 Do you think we can do this for 19.09?

It would remove a big section of hacks in `static-haskell-nix`.

**Comment by nh2** [comment]
I discovered a new odd nuance of this, where overriding it in an overlay _does_ have an effect: https://github.com/nh2/static-haskell-nix/blob/9a3e919a91e98a66e749a8aa9bdd2c353f210e57/survey/default.nix#L523-L532

If anybody understands what's going on there, please let me know!

**Comment by nh2** [comment]
If found that a recent `master` commit 39769df9dfa63263850e9c4f6f771873b89198b5 by @domenkozar makes all my checks in

https://github.com/nh2/static-haskell-nix/blob/3d49955bc05ddeac9cfd620e5f9eaf299f89a5df/survey/default.nix#L565-L579

trigger.

That is not so good for me, because I added those checks to ensure I don't accidentally use the non-overridden packages.

**Comment by nh2** [comment]
Turns out it's `cachix` in https://github.com/nh2/static-haskell-nix/blob/3d49955bc05ddeac9cfd620e5f9eaf299f89a5df/survey/default.nix#L1140 that triggers this.

@domenkozar How does it depend on this busybox change?

**Comment by domenkozar** [comment]
Yes, busybox is added as default shell for nix-shell and it's compiled statically with musl.

**Comment by nh2** [comment]
@Ericson2314 says that https://github.com/NixOS/nixpkgs/pull/34332 is at fault for this; it switched the order.

**Comment by tilpner** [comment]
This doesn't seem solved yet. (stale-pong)

**Comment by nh2** [comment]
Still relevant

**Comment by Artturin** [comment]
looks fixed

```sh
$ nix-build --no-link -E '((import ./. {}).extend (final: previous: { zlib = 1; })).zlib'
error: expression does not evaluate to a derivation (or a set or list of those)
$ nix-build --no-link -E '((import ./. {}).extend (final: previous: { zlib = previous.zlib; })).zlib'
/nix/store/mg9l7phyhvi16p9g8g3g8fbyj4mr79gq-zlib-1.2.13
```
