### ISSUE TITLE
NixOS release lifecycle

### ISSUE THREAD

**Issue by jnetod** [NixOS/nixpkgs#61694]
## Issue description

How do NixOS release lifecycle works?

**Comment by joachifm** [comment]
See https://nixos.org/nixos/manual/index.html#ch-releases

**Comment by vcunat** [comment]
I'm not sure what you're asking.  If it's about length of support, every six months we make a release (.03 and .09) and there's at least one month of overlap in the support (mainly backporting security fixes).  Very critical fixes usually get backported for longer time.

**Comment by jnetod** [comment]
I'm asking about general NixOS release life cycle.

joachifm lead me towards some documentation, but I'm also interested in maintenance/security support time (at least one month after current release, like you said) and EOL of a release.

Asking because 18.09 (I'm on it) is open to recent intel flaws.

**Comment by vcunat** [comment]
I posted that.  First line of 18.09 release notes: https://nixos.org/nixos/manual/release-notes.html#sec-release-18.09-highlights

> End of support is planned for end of April 2019, handing over to 19.03.

**Comment by vcunat** [comment]
I picked updates to latest Linux kernel to 18.09, as that's fairly easy and cheap, and perhaps the mitigations are critical to some.  I think this thread is answered now.
