### ISSUE TITLE
LLVM 3.5 incompatible with GHC

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#6169]
LLVM 3.5 became the default in https://github.com/NixOS/nixpkgs/pull/6133. This change breaks GHC: https://ghc.haskell.org/trac/ghc/ticket/9142.

Cc: @shlevy

**Comment by vcunat** [comment]
It seems easiest to do something like define ``llvm = llvm_34;`` in the shared scope of haskell packages. It's just about changing this bit isn't it?
```
  haskell = let pkgs_       = pkgs // { gmp = gmp.override { withStatic = true; }; };
```

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/pull/6713 will allow us to implement a proper fix.

**Comment by peti** [comment]
Fixed in `master`.
