### ISSUE TITLE
teamviewer 14 shows black screen for incoming connections

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#61712]
## Issue description
Connect TO teamviewer 14 on Nixos 19.03 Koi - it shows black screen with control elements, similar to this: https://i.imgur.com/tObHogP.png providing no control.

Connecting OS plays no role (connected FROM teamviewer 14 on Nixos 19.03 Koi and FROM teamviewer 14 on Ubuntu 16.04;  to teamviewer 14 on Nixos 19.03 Koi - same result).

There are no errors or warnings in the log, except this entry:

StartServiceByName: com.teamviewer.TeamViewer.Desktop - DBus: 'org.freedesktop.DBus.Error.ServiceUnknown' (The name com.teamviewer.TeamViewer.Desktop was not provided by any .service files) when calling 'org.freedesktop.DBus.StartServiceByName' on '/org/freedesktop/DBus', Errorcode=11

### Steps to reproduce
in /etc/nixos/configuration.nix:
services.teamviewer.enable = true; 
...
environment.systemPackages = with pkgs; [
...
teamviewer
];

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.1, NixOS, 19.03.172655.705986f5a98 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(userp): `""`
 - channels(root): `"nixos-19.03.172655.705986f5a98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jraygauthier** [comment]
@cx405: Fix now available in `master`.

**Comment by wamserma** [comment]
@cx405 / @mmahut  Would you mind closing this issue? Seems solved.

**Comment by cx405** [comment]
@wamserma Thank you! Because of mentioned problem I had to switch to alternative software, thus was distracted from issue.

@jraygauthier Beautiful work, thank you very much for your time and support!! Closing issue.
