### ISSUE TITLE
pstree is no longer supported on Darwin

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#61725]
## Issue description

#60994 removed the old `pstree` package and aliased it to `psmisc` instead. The problem is, `psmisc` is specifically only supported on Linux (it even lives in the `pkgs/os-specific/linux/` subdirectory), whereas the old `pstree` was supported on Darwin.

### Steps to reproduce

On macOS, run `nix-env -iA nixpkgs.pstree`.

This used to work, but now it tries to install `psmisc` and throws an error.

**Comment by veprbl** [comment]
cc @c0bw3b

**Comment by c0bw3b** [comment]
I was convinced `psmisc` was enabled on all unix platforms too but I fooled myself.
I'll revive classic pstree (with more stable sources) later today and remove the alias.
Thanks for raising the issue @lilyball

**Comment by lilyball** [comment]
The description of `psmisc` says it uses the `/proc` filesystem so it sounds like there's no chance it will ever support macOS.
