### ISSUE TITLE
PostgresQL built without SSL support

### ISSUE THREAD

**Issue by bergey** [NixOS/nixpkgs#6174]
I was surprised today that postgres doesn't seem to have SSL.  @ocharles I can try to fix this and open a PR, but figured I would check first if there's a reason it's this way.

**Comment by ocharles** [comment]
I can't see a good reason why - go ahead and open a pull request :)

**Comment by aflatter** [comment]
Would this need a feature flag or can we agree to generally enable openssl with postgres?

**Comment by edolstra** [comment]
I think enabling it unconditionally is fine, OpenSSL is a pretty common dependency.

**Comment by lethalman** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/6953
