### ISSUE TITLE
UEFI-booted NixOS keeps at least 2 generations in the boot table

### ISSUE THREAD

**Issue by hellominotaur** [NixOS/nixpkgs#6175]
I had an identical issue outlined in #3542, where generations were being kept on the boot table. Calling `nix-collect-garbage -d` then `nixos-rebuild switch` would purge most of the generations from the boot table, but (I expect) since the generation that called for the rebuild is still being held at this point, it doesn't get purged, leaving a minimum of two generations in your boot table.

**Comment by peti** [comment]
I think that garbage collecting the system from which the machine has been booted is a wee bit aggressive. After all, that profile contains stuff `nixos-rebuild switch` cannot replace, i.e. kernel modules.

**Comment by iElectric** [comment]
You can not garbage collect the profile that you're currently running. It's active.

**Comment by edolstra** [comment]
The configuration from which the system was booted is not garbage-collected due to the existence of the symlink `/run/booted-system` (which is in turn symlinked from `/nix/var/nix/gcroots/`).

**Comment by hellominotaur** [comment]
I can appreciate that the previous generation wouldn't be garbage collecting the creator system for as long as it is active – I suppose I was trying to illustrate that there is no way to erase the boot entry from the nix's garbage collection command.

Perhaps I should rephrase the issue – should there be an option in `nixos-rebuild` that removes that previous entry out of the boot table on as well? Is there enough confidence that NixOS's system building is reliable enough to boot into the newest system config without needing to fall back to the previous?

**Comment by iElectric** [comment]
You can't delete the current running profile. Excluding it from grub doesn't make any sense since it doesn't solve anything (except from not having an option to boot current system).

**Comment by hellominotaur** [comment]
While I had stated before that I wasn't actually interested in deleting the running profile, I've managed to get the desired response I had needed by setting the `boot.loader.timeout` option in the config to 0, so it's reasonable to close
