### ISSUE TITLE
buildBazelPackage does not work with sandbox for projects with external dependencies

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#61760]
## Issue description

Given a builder with sandbox enabled and a project with [external dependencies](https://docs.bazel.build/versions/master/external.html), `buildBazelPackage` will fail to build packages during its fetch "phase".

This is because sandbox disables network access, while the `bazel fetch` command will attempt to access network for each relevant `http_archive` rule.

An error will look like this:

```
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz, https://github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz] to /build/output/external/io_bazel_rules_closure/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.bazel.build]
```

### Steps to reproduce

Try building [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/tensorflow/default.nix) derivation.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.9, NixOS, 19.09pre178158.8141d5b21cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre178158.8141d5b21cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment]
Unfortunately @abbradar hasn't been around anymore lately, and I don't think anyone else maintains those expressions, nor really knows how Bazel works.

Bazel attempts to fetch and install https://github.com/bazelbuild/rules_closure. Our `buildBazelPackage` function has an attribute, `fetchAttrs`, which is fixed-output derivation; there's a fetcher that fetches everything needed, and puts it in an output and verifies it against a hash. These components should also be fetched, but if I understand correctly, this `rules_closure` is not just a package, it actually provides Bazel expressions and thus works similar as our `builtins.fetchTarball` and `builtins.fetchGit`.

**Comment by nagisa** [comment]
Even if `rules_closure` is patched out to be retrieved from the nix-store, there are more `http_archive`s triggered later on by `bazel fetch` which still trigger wrath of the sandbox.

For bazel packages to work correctly it is necessary to somehow run `bazel` fetch from outside of the sandbox, similar to how e.g. `fetchGit` is run outside of the sandbox. Is it possible at all to change the `buildBazelPackage` to support such mechanism?

**Comment by abbradar** [comment]
Sadly I don't remember much about Bazel from several years ago but `buildBazelPackage` actually has support for `bazel fetch`. Check out `tensorflow` derivation which has `fetchAttrs.sha256` defined. It works in two steps:

1. First a fixed-output derivation builds outside of sandbox which runs `bazel fetch`;
2. Then an actual derivation builds which runs `bazel build`.

**Comment by nagisa** [comment]
@abbradar this issue is specifically about the current implementation in `buildBazelPackage` not interacting well with the sandbox – the since `bazel fetch` goes out into the internet (potentially) and `fetchAttrs` is run as part of regular build, these calls are terminated and build fails.

If we want to keep the current set-up working we need to run the derivation generated from `fetchAttrs` outside of the sandbox.

**Comment by abbradar** [comment]
What I meant is because `deps` runs as a separate fixed-output derivation it should already run outside of sandbox (at least I always tested it with sandbox enabled in the past), so it's strange that there are any problems with that.

I'll test if tensorflow in particular builds when I get home ; maybe you have any smaller examples?

On May 25, 2019 12:43:35 PM GMT+03:00, Simonas Kazlauskas <notifications@github.com> wrote:
>@abbradar this issue is specifically about the current implementation
>in `buildBazelPackage` not interacting well with the sandbox – the
>since `bazel fetch` goes out into the internet (potentially) and
>`fetchAttrs` is run as part of regular build, these calls are
>terminated and build fails.>
>>
>If we want to keep the current set-up working we need to run the
>derivation generated from `fetchAttrs` outside of the sandbox.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/NixOS/nixpkgs/issues/61760#issuecomment-495897637

-- 
Nikolay.

**Comment by FRidh** [comment]
@nagisa have you tried setting a bogus sha256, because I have the impression there is a misunderstanding here.

**Comment by FRidh** [comment]
:wave: @abbradar

**Comment by abbradar** [comment]
@FRidh long time no see ;)

**Comment by abbradar** [comment]
Right now tensorflow doesn't build at all. The latest 1.13.1 version needs older Bazel than we have in nixpkgs. That'll take more time to fix, most likely by adding older Bazel as solving compatibility problems between them is a gigantic pain for Tensorflow.

**Comment by nagisa** [comment]
> I'll test if tensorflow in particular builds when I get home ; maybe you have any smaller examples?

I do not have a smaller example – I am encountering this issue with a somewhat customised tensorflow derivation.

This is what en excerpt of my `buildBazelPackage` looks like:

```nix
buildBazelPackage rec {
    name = "libtensorflow-${version}";
    version = "1.12.0";
    src = fetchFromGitHub {
      owner = "tensorflow";
      repo = "tensorflow";
      rev = "v${version}";
      sha256 = "0sy0jc1fg7rg8rzxfzlgkfk40ng0f6s0snixy35h91naaw6ijb95";
    };

    nativeBuildInputs = [ swig which pypkgs.wheel pypkgs.scipy ];

    buildInputs = [
      jemalloc openmpi glibcLocales python_with_deps getopt pypkgs.bootstrapped-pip
    ];

    bazelTarget = [
        "//tensorflow/tools/pip_package:build_pip_package"
        # snip
    ];

    fetchAttrs = {
      inherit preConfigure;

      # Something about the tensorflow build scripts makes this step non-deterministic across machines
      sha256 = null;
      outputHashAlgo = null;

      configurePhase = ''
          runHook preConfigure
          ./configure
          runHook postConfigure
      '';

      preInstall = ''
          # Unnecessary and fails installPhase because of permissions.
          rm -rf $bazelOut/external/embedded_jdk
      '';
    };
    # snip
}
```

Then I run `nix-build my_packages.nix -A libtensorflow.deps` and get the following output:

```
these derivations will be built:
  /nix/store/klin934i2p6fb15l7hycfmykhjif8g46-libtensorflow-1.12.0-deps.drv
building '/nix/store/klin934i2p6fb15l7hycfmykhjif8g46-libtensorflow-1.12.0-deps.drv'...
unpacking sources
unpacking source archive /nix/store/1li83lwh7njipy70ipwg42c7w2i0q9ja-tensorflow-v1.12.0-src
source root is tensorflow-v1.12.0-src
patching sources
applying patch <snip>
configuring
patching script interpreter paths in configure
configure: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/a9i0a06gcs8w9fj9nghsl0b6vvqpzpi4-bash-4.4-p23/bin/bash"
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.16.1- (@non-git) installed.
Found possible Python library paths:
  /nix/store/1b4w41dwalbry5848f3i168lgx5fvx2z-python3-3.6.4-env/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/nix/store/1b4w41dwalbry5848f3i168lgx5fvx2z-python3-3.6.4-env/lib/python3.6/site-packages]
Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: Apache Ignite support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: No ROCm support will be enabled for TensorFlow.

NCCL found at /nix/store/15nsj8jgcgzs8dg3c468sdf31gpc6q1m-cudatoolkit-9.0-nccl-2.3.7/lib/libnccl.so.2
Assuming NCCL header path is /nix/store/15nsj8jgcgzs8dg3c468sdf31gpc6q1m-cudatoolkit-9.0-nccl-2.3.7/lib/../include/nccl.h
Do you want to use clang as CUDA compiler? [y/N]: nvcc will be used as CUDA compiler.

Please specify the MPI toolkit folder. [Default is /nix/store/y661mhi6yqq959m65iw1rykkn0ydfjl3-openmpi-1.10.7]:

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
Configuration finished
building
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz, https://github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz] to /build/output/external/io_bazel_rules_closure/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.bazel.build]
builder for '/nix/store/klin934i2p6fb15l7hycfmykhjif8g46-libtensorflow-1.12.0-deps.drv' failed with exit code 2
error: build of '/nix/store/klin934i2p6fb15l7hycfmykhjif8g46-libtensorflow-1.12.0-deps.drv' failed
```

Running `sudo nix-build --option sandbox false packages.nix -A libtensorflow.deps` works perfectly fine. So I’m fairly confident that my description of the issue is accurate.

**Comment by abbradar** [comment]
The problem is that you've set:

```
      sha256 = null;
      outputHashAlgo = null;
```

, thereby making `deps` derivation non-fixed-output. There are two types of derivations in Nix:

* Usual ones, which are fully sandboxed and don't have Internet access for ensuring determinism;
* Fixed output ones, which are verified against checksums but are not sandboxed. `fetchurl` is an example of it -- it can download files precisely because it has a checksum.

Instead of setting these to `null` we need to find and fix the source of nondeterminism so that checksums will be accurate. This is how Nix enforces deterministic builds.

**Comment by abbradar** [comment]
One possible way to do this is to print `sha256` sums of all files in `$out`. Also watch out for symlinks to local dependencies, like `@local_foo`. These should be removed too.

**Comment by nagisa** [comment]
Okay, thank you for insight. There are indeed differences in 3 of the generated files. Some checksum differences in a few of the marker files and this:

```
--- /nix/store/arsb1i1q5fy06gj6lm67276yfkkg0w7j-libtensorflow-1.12.0-deps/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py	1970-01-01 03:00:01.000000000 +0300
+++ /tmp/msvc_wrapper_for_nvcc.py	2019-05-26 02:50:24.682900298 +0300
@@ -35,7 +35,7 @@
 
 NVCC_PATH = '/nix/store/59m016kxvv9dvh4mglcmcd3fwkiv5mpx-cudatoolkit-9.0.176.4/bin/nvcc'
 NVCC_VERSION = '9.0'
-NVCC_TEMP_DIR = "/build\\nvcc_inter_files_tmp_dir"
+NVCC_TEMP_DIR = "/tmp/nix-build-libtensorflow-1.12.0-deps.drv-0\\nvcc_inter_files_tmp_dir"
 supported_cuda_compute_capabilities = [ "3.7", "5.2", "6.1", "7.0" ]
 
 def Log(s):
```

I think I’ll figure things out by myself a this point, thanks for the assistance!

**Comment by abbradar** [comment]
You can freely just remove `local_*` files, they will be regenerated by `build`. In fact I already do this in our Tensorflow derivation. 

On May 26, 2019 2:59:17 AM GMT+03:00, Simonas Kazlauskas <notifications@github.com> wrote:
>Okay, thank you for insight. There are indeed differences in 3 of the
>generated files. Some checksum differences in a few of the marker files
>and this:>
>>
>```>
>---
>/nix/store/arsb1i1q5fy06gj6lm67276yfkkg0w7j-libtensorflow-1.12.0-deps/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py	1970-01-01
>03:00:01.000000000 +0300>
>+++ /tmp/msvc_wrapper_for_nvcc.py	2019-05-26 02:50:24.682900298 +0300>
>@@ -35,7 +35,7 @@>
> >
>NVCC_PATH =
>'/nix/store/59m016kxvv9dvh4mglcmcd3fwkiv5mpx-cudatoolkit-9.0.176.4/bin/nvcc'>
> NVCC_VERSION = '9.0'>
>-NVCC_TEMP_DIR = "/build\\nvcc_inter_files_tmp_dir">
>+NVCC_TEMP_DIR =
>"/tmp/nix-build-libtensorflow-1.12.0-deps.drv-0\\nvcc_inter_files_tmp_dir">
> supported_cuda_compute_capabilities = [ "3.7", "5.2", "6.1", "7.0" ]>
> >
> def Log(s):>
>```>
>>
>I think I’ll figure things out by myself a this point, thanks for the
>assistance!>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/NixOS/nixpkgs/issues/61760#issuecomment-495956805

-- 
Nikolay.

**Comment by samuela** [comment]
I just came across this issue myself. Turns out that I forgot to update `fetchAttrs.sha256` in `buildBazelPackage`, so it was just using the outdated fetch'd libs from a previous build. Putting fake values in there and forcing a refetch does the trick 👍
