### ISSUE TITLE
bash 5 & nix-info: unrecognized flag '-m'

### ISSUE THREAD

**Issue by abathur** [NixOS/nixpkgs#61777]
## Issue description

Not certain this is a real issue. Test-driving bash 5 (`5.0.2(1)-release`) on darwin, and got a failure trying to run the usual issue-template nix-info command for another report.

Also not quite sure if it's helpful to report these before there's any real effort to move to bash 5. Asked on #nixos but didn't get a response; feel free to set me straight :)

### Steps to reproduce

in darwin-configuration.nix:

    nixpkgs.overlays = [
        (self: super: {
          bashInteractive = super.bashInteractive_5;
        })
    ];

then 

    $ nix-shell -p nix-info --run "nix-info -m"
    error: unrecognised flag '-m'
    Try '/Users/abathur/.nix-profile/bin/nix-shell --help' for more information.

## Technical details

Info (run separately from bash 4 shell...):

nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(abathur): `"nixpkgs-19.09pre174594.0c0954781e2, darwin"`
 - nixpkgs: `/Users/abathur/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
I'm not getting this on linux:

```
mjbauer95@penguin:~ $ nix build nixpkgs.bashInteractive_5
mjbauer95@penguin:~ $ ./result/bin/bash
mjbauer95@penguin:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.34-04457-g5b63d4390e96, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(mjbauer95): `"nixpkgs-19.09pre180301.650a295621b"`
 - nixpkgs: `/home/mjbauer95/.nix-defexpr/channels/nixpkgs`
mjbauer95@penguin:~$ echo $BASH_VERSION
5.0.7(1)-release
```

**Comment by abathur** [comment]
Still seeing after a channel update. I think this is just a quoting issue with something in my bashrc. Sorry for the pointless report; closing for now.
