### ISSUE TITLE
haskell-ng: nix-build using old cabal version

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#6181]
I generated a simple .nix file using `cabal2nix .`. Now when I try to build this using `nix-build -E 'with (import <nixpkgs> {} ); haskellngPackages.callPackage ./structured-haskell-mode.nix {}'` it tries to use Cabal 1.18 by default. This seems strange because otherwise 1.22 seems to be the default and also causes breakage because you don't seem to be able to compile something with Cabal 1.18 that links to libs built with 1.22. Adding an explicit Cabal_1_22_0_0 to the arguments and buildDepends fixes this problem.

**Comment by peti** [comment]
I'm not sure what you mean. Builds in `haskellngPackages` always use the native version of `Cabal` that comes with the compiler -- and that would be 1.8.x in case of GHC 7.8.x. Cabal 1.22.x isn't used.

**Comment by cocreature** [comment]
Ok, looks like I missread the source when I had a quick look earlier. I guess what was confusing me is that cabal-install is using cabal 1.22 (line 11 in configuration-common.nix).
