### ISSUE TITLE
fetchgit: fetchSubmodules is not recursive

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#61820]
## Issue description
I'm trying to build Pytorch 1.1, which has a git submodule FBGEMM which in turn has a git submodule asmjit.

It'd be great for this to be fixed, or a new option `recursizeFetchSubmodules` added.

### Steps to reproduce
```
nix-prefetch-git --fetch-submodules https://github.com/pytorch/pytorch
```
Note that https://gist.github.com/tbenst/fdf9426d7d6aadd7c1b59e010ebe423e#file-pytorch-fetchgit-L196 does not download asmjit

## Technical details
Effectively, we want the equivalent of `git submodule update --init --recursive` or `git submodule foreach --recursive git submodule update --init` or simply `git clone --recurse-submodules https://github.com/pytorch/pytorch.git`

Edit: better description

**Comment by tbenst** [comment]
This issue is related to https://github.com/NixOS/nix/issues/2151.

@zimbatm git blame shows you added the submodule feature, any ideas how to fix? Thanks!

**Comment by stites** [comment]
This is blocking #65041.

That said, I've tried to simulate the behavior with a test repository[1] that mimics pytorch's submodule layout, but I am getting the expected behavior.

My test was building with `nix-build -I nixpkgs=$(pwd) gitfetchtest.nix` with the following `gitfetchtest.nix`:

```
let
  pkgs = import ./. {};
in
with pkgs;

stdenv.mkDerivation {
  name = "x";
  src = fetchgit {
    url = https://github.com/stites/nix-recursive-prefetch-git-submodule-test-parent.git;
    sha256 = "1gawxwrm4jd6srh3s6mffdr0w0w7vl2zhfrj0lc86p8x86clq3av";
  };
  phases = [ "buildPhase" ];
  buildPhase = ''
    ls $src/third_party
    ls $src/third_party/middle/
    ls $src/third_party/middle/third_party/nix-recursive-prefetch-git-submodule-test-child
    echo "hello world"
    mkdir $out
    touch $out/foobar
  '';
}
```

[1]: https://github.com/stites/nix-recursive-prefetch-git-submodule-test-parent

**Comment by tbenst** [comment]
@stites great detective work!
