### ISSUE TITLE
vim-plugin-names-to-nix bug

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#6183]
@MarcWeber 
Just used `vim-plugin-names-to-nix` and got that there are no `sha256` for plugins with `fetchgit`.

**Comment by MarcWeber** [comment]
https://github.com/NixOS/nixpkgs/pull/6186, prefetch-git echoed the 'git hash ..' line to stderr. Don't know when this behaviour changed.

**Comment by jagajaga** [comment]
Thank you.
