### ISSUE TITLE
haskellPacakges.diagrams-{gtk,canvas} broken.

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#61855]
## Issue description
`haskellPackages.diagrams-gtk` and `haskellPackages.diagrams-canvas` is broken on current master

### Steps to reproduce
```
$ nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/master.tar.gz" -p haskellPackages.diagrams-gtk
these derivations will be built:
  /nix/store/img3n0swrkjiwwf1r2yx9frcjw5jr10v-diagrams-gtk-1.4.drv
building '/nix/store/img3n0swrkjiwwf1r2yx9frcjw5jr10v-diagrams-gtk-1.4.drv'...

Setup: Encountered missing dependencies:
base >=4.2 && <4.12, gtk >=0.12.0 && <0.15

$ nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/master.tar.gz" -p haskellPackages.diagrams-canvas
these derivations will be built:
  /nix/store/lxj7daxgngv3035hbc2m58vrvzx8gi77-diagrams-canvas-1.4.1.drv
building '/nix/store/lxj7daxgngv3035hbc2m58vrvzx8gi77-diagrams-canvas-1.4.1.drv'...

Setup: Encountered missing dependencies:
base >=4.6 && <4.12,
blank-canvas >=0.5 && <0.7,
containers >=0.3 && <0.6,
lens >=4.0 && <4.17
```

## Technical details
- system: `"x86_64-linux"`
- host os: `Linux 4.19.40, NixOS, 19.09pre178895.9ebc6ad944c (Loris)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.2.2`
- channels(root): `"nixos-19.09pre178895.9ebc6ad944c"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cdepillabout** [comment]
No updates on this in a few years, I'll go ahead and close.

Feel free to send a PR to `haskell-updates` if you're trying to unbreak this.
