### ISSUE TITLE
We have several ruby_2_1_* minor versions for no apparent reason

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6188]
I'm not too tuned into how the ruby ecosystem works in nix, but it strikes me as unusual to have that many minor revisions of the same program.

As of right now, we have these:
- ruby_1_8_7
- ruby_1_9_3
- ruby_2_0_0
- ruby_2_1_0
- ruby_2_1_1
- ruby_2_1_2
- ruby_2_1_3
- ruby_2_2_0

Do we really want to keep them all around? I need to patch some for some darwin work and it's kind of annoying to have to go change all of them in the same way. If we do need all those versions, perhaps we can factor out the common behavior?

**Comment by copumpkin** [comment]
Calling @cstrahan

**Comment by copumpkin** [comment]
I'm tempted to just delete `ruby_2_1_0`, `ruby_2_1_1`, and `ruby_2_1_2` unless people object. I'm getting sick of applying the same fixes to all of them, and don't see much point in keeping them all around (if I did, I'd just factor out the common behavior).

**Comment by edolstra** [comment]
:+1:

**Comment by aflatter** [comment]
:+1:

**Comment by rushmorem** [comment]
+1 Considering how easy it is to rollback or override nix packages, I don't see any point in keeping around old minor versions.

**Comment by peti** [comment]
:+1:

**Comment by cstrahan** [comment]
I don't personally mind pruning the versions. The Ruby community tends to do things like lock down their applications to precise Ruby versions (and then stick to those versions for way too long), but I suppose we can work around that in our packages, and tell prospective NixOS users to do a better job at maintaining their software.

:+1:

**Comment by copumpkin** [comment]
We seem to have grown even more!

```
    ruby_1_9_3
    ruby_2_0_0
    ruby_2_1_0 ruby_2_1_1 ruby_2_1_2 ruby_2_1_3 ruby_2_1_6 ruby_2_1_7
    ruby_2_2_0 ruby_2_2_2 ruby_2_2_3
```

Looks like many of the new ones came from (or perhaps were just merged into one file by) @pikajude. Any reason to keep them around? I don't really know which ones are worth pruning anymore, but it still seems worth doing.

**Comment by globin** [comment]
I've had a commit lying around removing the unused version :+1:

**Comment by grahamc** [comment]
bump 😂

**Comment by globin** [comment]
We only have one minor each, that isn't too bad.
