### ISSUE TITLE
overrideScope on haskell-ng packages only passes in Haskell package arguments

### ISSUE THREAD

**Issue by joelteon** [NixOS/nixpkgs#6192]
If a Haskell package expression accepts anything that isn't a Haskell package in its argument list, it won't be passed in:

```
error: while evaluating anonymous function at /Users/joelteon/.dev/Haskell/webapp2/shell.nix:1:1, called from undefined position:
while evaluating the attribute ‘build."${ghc}"."${(builtins).currentSystem}"’ at /Users/joelteon/.dev/nixpkgs-dev/lib/attrsets.nix:135:44:
while evaluating anonymous function at /Users/joelteon/.dev/Haskell/webapp2/shell.nix:10:27, called from /Users/joelteon/.dev/nixpkgs-dev/lib/attrsets.nix:135:52:
while evaluating ‘overrideDerivation’ at /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:34:29, called from /Users/joelteon/.dev/Haskell/webapp2/shell.nix:25:10:
while evaluating ‘addPassthru’ at /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:109:22, called from /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:37:8:
while evaluating ‘overrideScope’ at /Users/joelteon/.dev/nixpkgs-dev/pkgs/development/haskell-modules/default.nix:46:25, called from /Users/joelteon/.dev/Haskell/webapp2/shell.nix:13:20:
while evaluating ‘callPackageWithScope’ at /Users/joelteon/.dev/nixpkgs-dev/pkgs/development/haskell-modules/default.nix:45:42, called from /Users/joelteon/.dev/nixpkgs-dev/pkgs/development/haskell-modules/default.nix:46:28:
while evaluating ‘callPackageWith’ at /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:104:35, called from /Users/joelteon/.dev/nixpkgs-dev/pkgs/development/haskell-modules/default.nix:45:49:
while evaluating ‘makeOverridable’ at /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:56:24, called from /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:106:5:
anonymous function at /Users/joelteon/.dev/Haskell/webapp2/default.nix:3:1 called without required argument ‘stdenv’, at /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:58:12
```

With `default.nix` starting with this:

``` nix
{ mkDerivation, aeson, asn1-types, attoparsec, base, blaze-builder
, blaze-html, bytestring, conduit, data-default, directory
, esqueleto, fast-logger, file-embed, filepath, highlighter, hjsmin
, hspec, http-conduit, http-types, lens, lifted-base, markdown
, monad-control, monad-logger, MonadRandom, network, network-uri
, old-locale, path-pieces, pcre-light, persistent
, persistent-postgresql, persistent-template, process-extras
, resourcet, shakespeare, stdenv, system-filepath, template-haskell
, text, thyme, transformers, wai, wai-extra, wai-logger, warp, yaml
, yesod, yesod-auth, yesod-core, yesod-form, yesod-newsfeed
, yesod-pagination, yesod-static, yesod-test
}:
```

and using:

``` nix
let pkg = pkg_.overrideScope (self: super: {
  mkDerivation = expr: super.mkDerivation (expr // {
    enableLibraryProfiling = true;
  });
});
```

**Comment by peti** [comment]
The override you've posted should work fine. Could you please post a complete example -- say, on pastebin or as a gist -- so that I can try to re-produce exactly what you're doing?

**Comment by joelteon** [comment]
``` nix
let
  pkg = { mkDerivation, stdenv }: mkDerivation {
    pname = "foobar";
    version = "1.0";
    license = stdenv.lib.licenses.bsd3;
  };
  calledPackage = (import <nixpkgs> {}).haskellngPackages.callPackage pkg {};
in calledPackage.overrideScope (self: super: {
  mkDerivation = expr: super.mkDerivation (expr // {
    enableLibraryProfiling = true;
  });
})
```

```
$ nix-instantiate --eval test.nix
error: ‘pkg’ at /Users/joelteon/test.nix:2:9 called without required argument ‘stdenv’, at /Users/joelteon/.dev/nixpkgs-dev/lib/customisation.nix:58:12
```

**Comment by peti** [comment]
The error message 

> called without required argument ‘stdenv’

seems to indicate a problem. :smile: This version works fine:

    let
      nixpkgs = import <nixpkgs> {};
      pkg = { mkDerivation, stdenv, hsdns, Agda }: mkDerivation {
        pname = "foobar";
        version = "1.0";
        license = stdenv.lib.licenses.bsd3;
      };
      calledPackage = nixpkgs.haskellngPackages.callPackage pkg { inherit (nixpkgs) stdenv; };
    in calledPackage.overrideScope (self: super: {
      mkDerivation = expr: super.mkDerivation (expr // {
        enableLibraryProfiling = true;
      });
    })

**Comment by joelteon** [comment]
So I have to explicitly `inherit` anything that's not a Haskell package, and only when using `overrideScope`? Is that by design?

**Comment by peti** [comment]
No, I guess not. I'll commit a fix.

**Comment by peti** [comment]
Okay, here is the problem: https://github.com/peti/nixpkgs/commit/bbb422af92305137a12e898c406a3b11371c264c fixes the scope lookup, but with that patch applied `nix-env` generates lots of warning because of freaky memory consumption:

    $ nix-env -qaP -A haskellngPackages 2>&1 | head -n 10
    GC Warning: Repeated allocation of very large block (appr. size 192512):
            May lead to memory leak and poor performance.
    GC Warning: Repeated allocation of very large block (appr. size 192512):
            May lead to memory leak and poor performance.
    GC Warning: Repeated allocation of very large block (appr. size 188416):
            May lead to memory leak and poor performance.
    GC Warning: Repeated allocation of very large block (appr. size 307200):
            May lead to memory leak and poor performance.
    GC Warning: Repeated allocation of very large block (appr. size 192512):
            May lead to memory leak and poor performance.

So what do we do now? :confused:
