### ISSUE TITLE
passthru.updateScript is a little hard to use

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#61935]
## Issue description

`passthru.updateScript` is documented as being an executable file, but what's not immediately obvious is that this file is copied into the nix store and therefore if it does anything relative to its own location, that's not going to be very effective.

Looking through the repo I found at least one script that appears to be broken by this behavior; namely, the `dwarf-fortress` update script writes to `$(dirname "$0")/game.json`, which presumably will fail if it's actually attempted because that path is going to be in the nix store when it really wants to write to the nixpkgs working copy.

It would have been nice if `updateScript` had a mechanism by which the current directory could be set to the package's directory, but there's no existing means to do that. After some experimentation I determined that I could write something like the following:

```nix
passthru.updateScript = writeScript "update-package" ''
  #!${runtimeShell}
  set -e
  cd ${lib.strings.escapeShellArg ./.}
  ./update.sh
'';
```

This writes a new file to the nix store whose only job is to `cd` back to the working tree so it can run the real update script from the correct directory. I feel like this sort of hack really shouldn't be necessary.

I feel like the ideal behavior here is for the update script to be invoked with the current directory set to the containing directory of the file that set the `passthru.updateScript` attribute (using `builtins.unsafeGetAttrPos`). However this would likely be a backwards-incompatible change as there probably exist some update scripts that assume the current directory is the root of the repo (even though that's not at all guaranteed as I could run the update script from a subdirectory; I haven't actually confirmed but I assume the current directory is whatever the current directory was when I ran `nix-shell`). I did find at least one script that uses `git rev-parse --show-toplevel` so that script wouldn't be broken by this, but I haven't done an exhaustive survey of update scripts.

**Comment by lilyball** [comment]
It occurred to me this morning that if I set the `updateScript` to a string, it won't be moved into the nix store. Experimentally, the following seems to work:

```nix
passthru.updateScript = toString ./update.sh;
```

Of course, the script itself still needs to handle the `$PWD` being some arbitrary location, but at least it can then use `"$(dirname "${BASH_SOURCE[0]}")"` to find its containing folder.

In any case, this is non-obvious. It might be worth updating the manual to mention the behavioral distinction between providing a path and providing a string.

**Comment by FRidh** [comment]
In `buildPythonPackage` we have essentially
```
passthru.updateScript = let
    filename = builtins.head (lib.splitString ":" self.meta.position);
  in [ update-python-libraries filename ];
```
where `update-python-libraries` is defined in `all-packages.nix`.

**Comment by flokli** [comment]
Another itch is the way we use nix-shell shebangs in a lot of the updater scripts - the nix-shell invoked there might use another `<nixpkgs>`.

In my case, I ended up with an `update-source-version` that didn't know how to parse nix 2.0-style hash output, resulting in

```
sha256 = "  got:    sha256:…";
```

lines.

I guess we should add some documentation/examples about how things should be used, and update the existing scripts to honor these recommendations.

**Comment by jtojnar** [comment]
Sorry, wanted to reply sooner but did not have time and then forgot about this.

> `passthru.updateScript` is documented as being an executable file, but what's not immediately obvious is that this file is copied into the nix store and therefore if it does anything relative to its own location, that's not going to be very effective.

Yeah, this is something we are so accustomed that we do not even realize someone might not know that.

IMHO this feature of Nix makes sense to ensure consistency of build trees but benefits are dubious in case of single-file update scripts.

> Looking through the repo I found at least one script that appears to be broken by this behavior; namely, the `dwarf-fortress` update script writes to `$(dirname "$0")/game.json`, which presumably will fail if it's actually attempted because that path is going to be in the nix store when it really wants to write to the nixpkgs working copy.

Hmm, can confirm `nix-shell maintainers/scripts/update.nix --argstr path dwarf-fortress` produces an error. Apparently, it is a side effect of JSONification from https://github.com/NixOS/nixpkgs/pull/50977/files#diff-068de29b3fc79aa673d4a7f25f8ee9fbR142 Maybe we should stringify the paths there first.

> It would have been nice if `updateScript` had a mechanism by which the current directory could be set to the package's directory, but there's no existing means to do that. After some experimentation I determined that I could write something like the following:
> 
> ```nix
> passthru.updateScript = writeScript "update-package" ''
>   #!${runtimeShell}
>   set -e
>   cd ${lib.strings.escapeShellArg ./.}
>   ./update.sh
> '';
> ```

Yeah, using Nix’s script-relative semantics would work for individual packages but not for high-order updaters (e.g. the one used by GNOME packages).

> I feel like this sort of hack really shouldn't be necessary.

Indeed, update scripts and other service info should be as minimal as possible.

> I feel like the ideal behavior here is for the update script to be invoked with the current directory set to the containing directory of the file that set the `passthru.updateScript` attribute (using `builtins.unsafeGetAttrPos`).

Actually, I would expect a bash script to work relative to `PWD` when run manually. But I can see how the knowledge of `PWD` can become blurred when it is invoked by another program.

> However this would likely be a backwards-incompatible change as there probably exist some update scripts that assume the current directory is the root of the repo (even though that's not at all guaranteed as I could run the update script from a subdirectory; I haven't actually confirmed but I assume the current directory is whatever the current directory was when I ran `nix-shell`).

`update-source-version` expects to be called from nixpkgs root so this would break almost every update script. Though I am not against making `common-updater-scrips` work in subdirs and break BC if we specify the expected behaviour and fix all the in-tree `updateScript`s. If we do not want to introduce BC break, we could implement it using `features` from https://github.com/NixOS/nixpkgs/pull/59372.

> I did find at least one script that uses `git rev-parse --show-toplevel` so that script wouldn't be broken by this, but I haven't done an exhaustive survey of update scripts.

Ideally, `update.nix` would work anywhere in the tree but since 99.9% of people will probably call it from the root, I am not sure making the scripts more robust will be worth the effort.

> In any case, this is non-obvious. It might be worth updating the manual to mention the behavioral distinction between providing a path and providing a string.

It is documented in the [manual](https://nixos.org/nix/manual/#ssec-derivation):

> - Every attribute is passed as an environment variable to the builder. Attribute values are translated to environment variables as follows:
>   - Strings and numbers are just passed verbatim.
>   -  A _path_ (e.g., `../foo/sources.tar`) causes the referenced file to be copied to the store; its location in the store is put in the environment variable. The idea is that all sources should reside in the Nix store, since all inputs to a derivation should reside in the Nix store.

I see this issue quite frequently: people miss some detail in Nix manual and then a part of nixpkgs that relies on that knowledge confounds them. Unfortunately, I do not see a solution; the Nix manual is huge and many people did not read it cover to cover (I certainly did not not). And you need to know 90% of Nix manual so we cannot just copy the relevant parts to nixpkgs manual.

----

> Another itch is the way we use nix-shell shebangs in a lot of the updater scripts - the nix-shell invoked there might use another `<nixpkgs>`.

I have `nixPath` set up to point to my nixpkgs checkout and I actually had the opposite problem – some update scripts depended on a package I updated previously so building the `updateScript` was blocked until everything built. Then I was glad that `updateScript`s depended on `NIX_PATH` so I could point it to a cached revision. I agree though, that this behaviour is unintuitive and catering to my minor issue is probably not necessary.

> I guess we should add some documentation/examples about how things should be used, and update the existing scripts to honor these recommendations.

:yes:

**Comment by lilyball** [comment]
It's probably safe to say that we should stringify all `updateScript` paths when converting to JSON; I can't imagine any scenario where we'd actually want the update script to be copied into the Nix store, given that we're invoking it immediately (if we're invoking it at all) and so long-term storage or consistency is unnecessary.

On another note, I realized today that `maintainers/scripts/update.nix` doesn't provide overlays when it imports the nixpkgs root, meaning this script will go ahead and try to invoke any `updateScript` attributes defined in overlays. This isn't objectively a bad thing, but I'm inclined to say that the nixpkgs maintainer update script shouldn't be touching overlays.

**Comment by jtojnar** [comment]
> It's probably safe to say that we should stringify all `updateScript` paths when converting to JSON; I can't imagine any scenario where we'd actually want the update script to be copied into the Nix store, given that we're invoking it immediately (if we're invoking it at all) and so long-term storage or consistency is unnecessary.

https://github.com/NixOS/nixpkgs/pull/62478

> On another note, I realized today that `maintainers/scripts/update.nix` doesn't provide overlays when it imports the nixpkgs root, meaning this script will go ahead and try to invoke any `updateScript` attributes defined in overlays. This isn't objectively a bad thing, but I'm inclined to say that the nixpkgs maintainer update script shouldn't be touching overlays.

Yeah, it was designed before the advent of overlays. I can reproduce it by creating `over/default.nix`

```nix
self: super: {
  pkmbr = with super; stdenv.mkDerivation rec {
    version = "3.32.1";
    pname = "pkmbr";

    src = fetchurl {
      url = "mirror://gnome/sources/libdazzle/${stdenv.lib.versions.majorMinor version}/libdazzle-${version}.tar.xz";
      sha256 = "0wprqgn480r31pcgmpyk9l6cfvlczfcx10fpqaq9pbn3vjgs3393";
    };

    passthru = {
      updateScript = gnome3.updateScript {
        packageName = "libdazzle";
        attrPath = pname;
      };
    };
  };

}
```

and then running `env NIX_PATH="$NIX_PATH:nixpkgs-overlays=$PWD/over" nix-shell maintainers/scripts/update.nix --argstr path pkmbr`

**Comment by jtojnar** [comment]
I realized there are some uses of `passthru.updateScript` outside of `nixpkgs`: https://github.com/mozilla/nixpkgs-mozilla/blob/2ff87ba7e9c2cea747a88545dfe13702e7386628/pkgs/servo/default.nix#L96-L101

so perhaps we do not want to limit `maintainers/scripts/update.nix` to `nixpkgs` as in https://github.com/NixOS/nixpkgs/commit/36b2012447b936a1a638e2ddae17507bab8fc839.

What do you think @garbas?

**Comment by lilyball** [comment]
I realized the overlay updateScript issue tonight because I was writing my own command to update my overlays. I ended up picking a different attribute name to avoid problems, but my solution to detecting just the overlay update scripts was to reimport nixpkgs with every overlay wrapped in a function that copied the overlay attributes into a brand new top-level attribute set, so I could examine them later.

That said, if someone does want to update overlays with the maintainer script, maybe we could disable that by default but add a new argument that means “update overlays too”?

**Comment by jtojnar** [comment]
Apparently they use [custom copy](https://github.com/mozilla/nixpkgs-mozilla/blob/2ff87ba7e9/update.nix) of `maintainers/scripts/update.nix` so we probably do not need to worry about overlays.

**Comment by lilyball** [comment]
#62478 looks great and will solve most of this. I would still like the manual to explicitly mention that `updateScript` will be run from an arbitrary PWD (frequently, but not always, the root of `nixpkgs`).

**Comment by lilyball** [comment]
I believe this was fixed by https://github.com/NixOS/nixpkgs/pull/62478. The script name is stringified and the manual was updated to note that it may be run from arbitrary locations.
