### ISSUE TITLE
tinc module fails if private key missing

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#6195]
@wkennington (Thanks for making a tinc module!)

The tinc module won't start, and gives the following error message:

```Feb 05 22:13:49 angel-nixos tinc.falsifian-pre-start[1513]: /nix/store/44hna616h8c70lr6mcqlyjjynrvkyp5a-unit-script/bin/tinc.falsifian-pre-start: line 5: tinc: command not found```

I am pretty sure the trouble is this line in /nixos/modules/services/networking/tinc.nix:

    [ -f "/etc/tinc/${network}/ed25519_key.priv" ] || tinc -n ${network} generate-ed25519-keys

This should call ```${data.package}/bin/tinc``` or something like that.

**Comment by wkennington** [comment]
But data.package is in the path. The tinc binary should be in the preStart
then......

**Comment by falsifian** [comment]
Okay, I dug a little deeper by adding an "echo $PATH" to the preStart and looking there. It looks like the module is using tinc-1.0.25 by default, which doesn't have a tinc command (only tincd).

pkgs.tinc_pre is the more recent tinc-1.1preae5b56c.

**Comment by falsifian** [comment]
In any case, it's probably better to give an absolute path, so we can take advantage of nix's purity and avoid bugs like this :-)

**Comment by wkennington** [comment]
3e280f20898e344c3a0258b54ffeaa3b91936074

**Comment by falsifian** [comment]
Okay, that successfully creates the ```ed25519_key.priv``` file, but it does so even if I already have an ```rsa_key.priv``` file. Tinc seems to work besides that.

Note: I do see this new error (or warning?) in my system log:

    Feb 10 08:19:36 angel-nixos tinc.falsifian-start[1601]: Parsing Ed25519 public key file `/etc/tinc/falsifian/hosts/sylph' failed.

That file only has an RSA key, not an ED25519 key... so I guess all I'm saying is annoying messages appear when you go ahead and create the ```ed25519_key.priv``` after I already have a working RSA configuration.

**Comment by falsifian** [comment]
Correction to what I wrote before: I had to set the tinc package to ```pkgs.tinc``` to get my configuration working. But I'm not sure it's related to this module.

I'm closing this bug because I'm not sure tinc_pre works with my tinc network with any configuration at all, but please consider my note in the previous comment about not creating an ED25519 key if there's already an RSA key :-)
