### ISSUE TITLE
openBinaryFile permission error when compiling haskell derivation

### ISSUE THREAD

**Issue by david-janssen** [NixOS/nixpkgs#61963]
## Issue description
Trying to build a simple hello-world style haskell package, in preparation of building a static-website generator using Hakyll. 

This is the derivation:
```nix
{ stdenv, pkgs }:

stdenv.mkDerivation rec {
  name        = "cv-website-generator";
  version     = "0.0.0";
  src         = ../generator;

  buildInputs = [ (pkgs.haskellPackages.ghcWithPackages (p: with p;
                    [ hakyll
                      hakyll-sass
                      hlibsass
                      filepath]))
    ];

  installPhase = ''
    # Make the output directory
    mkdir -p $out/bin

    # Test stuff
    ghc --make $src/Main.hs -o $out/bin/generate-site
  '';
}
```

Trying to build this derivation I run into:
```
  [1 of 1] Compiling Main             ( /nix/store/6kpq3yv30iwh1jvgvisfh5nfxc5pf91d-generator/Main.hs, /nix/store/6kpq3yv30iwh1jvgvisfh5nfxc5pf91d-generator/Main.o )
  /nix/store/6kpq3yv30iwh1jvgvisfh5nfxc5pf91d-generator/Main.hi: openBinaryFile: permission denied (Permission denied)
```

This seems to happen when trying to open intermediate file `Main.hi`. I checked afterwards, but the file does exist with read permissions.

The content of `Main.hs` is extremely minimal, and compiling it manually by calling `ghc --make generator/Main.hs -o test` works fine and generates the binary without any issues.
```haskell
module Main where

main :: IO ()
main = putStrLn "hello"
```

This whole thing might be me being a huge nincompoop, in which case I apologize. And if this isn't the right place to ask for help, please point me in the right direction. I have been trying to figure this out by myself for the last few hours and I am very stuck.

### Steps to reproduce

Try to build the above derivation using `nix build -f derivation_file.nix`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.101, NixOS, 18.09.2203.9bd45dddf81 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(david): `"nixpkgs-18.09.2532.571b40d3f50, nixos-18.03-18.03.133361.21b7f59ae12"`
 - channels(root): `"nixos-18.09.2203.9bd45dddf81, unstable"`
 - nixpkgs: `/home/david/.nix-defexpr/channels/nixpkgs`

**Comment by erictapen** [comment]
I can reproduce your issue on `nixos-19.03` and fixed it by using this build command:

```
ghc --make Main.hs -o $out/bin/generate-site
```

The difference lies in not explicitly referencing the full path of Main.hs, but just to assume it in the current directory (which is the case).

**Comment by david-janssen** [comment]
Hey thanks, that's great!
