### ISSUE TITLE
Firefox 67 prefers-color-scheme does not match chosen theme

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#61965]
## Issue description

Firefox 67 introduces support for the [prefers-color-scheme media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

With the dark theme selected:

![Screenshot_2019-05-23_11-40-39](https://user-images.githubusercontent.com/106511/58266456-a8d60f00-7d4f-11e9-84a3-58b2e07b241d.png)

I see the light theme activated according to the media query:

![Screenshot_2019-05-23_11-40-59](https://user-images.githubusercontent.com/106511/58266461-abd0ff80-7d4f-11e9-99b8-d6f40e07544e.png)

Expected behavior would be this (screenshot taken from Firefox 67 for Windows):

![dark](https://user-images.githubusercontent.com/106511/58266630-0f5b2d00-7d50-11e9-9be4-7172cfe90446.png)

Perhaps this is an upstream issue; however since the behavior is different across Windows/NixOS I thought it best to start with filing a bug report for NixOS package maintainers.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 19.09pre180443.4dd5c93998d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(andy): `""`
 - channels(root): `"nixos-19.09pre180443.4dd5c93998d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @shawnl

**Comment by shawnl** [comment]
Upstream https://bugzilla.mozilla.org/show_bug.cgi?id=1553610

**Comment by shawnl** [comment]
This is really an upstream bug.

**Comment by wamserma** [comment]
@andrewrk Can this be closed?

**Comment by andrewrk** [comment]
Yeah sure I agree with @shawnl that it is an upstream bug.
