### ISSUE TITLE
`signal-desktop` on 19.03 expired

### ISSUE THREAD

**Issue by freddie-freeloader** [NixOS/nixpkgs#61962]
## Issue description

The current version of `signal-desktop` distributed by 19.03 is showing an expired warning. The user cannot send messages with this version anymore.

**Comment by primeos** [comment]
Thanks for the report and sorry for the inconveniences.

@flokli already fixed it with #61886 and it should work again after the next channel update.

**Comment by freddie-freeloader** [comment]
Thanks, Michael! I just searched through the issues, next time I'll have a look at the PRs as well. Just getting slowly back into the workings of Nix*. :relaxed:
