### ISSUE TITLE
haskellng.packages.*.mysql will fail to build, needs mysql_config in build environment

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixpkgs#6201]
When attempting to build a Haskell environment that includes the mysql package:

    Setup: The program mysql_config is required but it could not be found

**Comment by peti** [comment]
I believe that this issue has been fixed a few days ago: http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.mysql.x86_64-linux. Current versions of Nixpkgs should compile these packages fine.
