### ISSUE TITLE
Channel update goes back in time

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#6203]
Repo: https://github.com/NixOS/nixos-channel-scripts

Check how to elimnate the problem when updated channel gets a build restarted and thus channel update script pulls older channel and marks it as the latest one

**Comment by dezgeg** [comment]
This seems to be fixed: https://github.com/NixOS/nixos-channel-scripts/commit/a441c018e28ae453d440774ec4c105e78b6a4760
