### ISSUE TITLE
Networkd cannot set hostname from DHCP

### ISSUE THREAD

**Issue by rileyinman** [NixOS/nixpkgs#62034]
## Issue description
I'm trying to migrate a machine from using NetworkManager and dhcpcd to networkd and iwd. However, this seems to break my hostname being assigned by DHCP on boot.

### Steps to reproduce
Set `network.hostName = ""`, `networking.useNetworkd = true`, and `systemd.network.enable = true`. Upon rebuild and reboot, hostname will be "localhost" and the output of `systemctl status systemd-networkd` ends with `Could not set hostname: Changing system settings via systemd is not supported on NixOS.`

## Technical details
- system: `"x86_64-linux"`
- host os: `Linux 4.19.45, NixOS, 19.03.172731.3efdf45dbd1 (Koi)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.2.2`
- channels(root): `"nixos-19.03.172731.3efdf45dbd1" `
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by arianvp** [comment]
Interesting. This will require some patches on our systemd fork. (We currently patched out changing hostname altogether. But perhaps we should do the hostname syscalls, but not write to disk, or something along those lines. Given we're planning to move to networkd for 20.03, we should fix this somehow.

**Comment by flokli** [comment]
This is still important, it just hasn't happened yet.

**Comment by flokli** [comment]
Might be solved by https://github.com/NixOS/nixpkgs/issues/74847#issuecomment-646160363.

**Comment by mweinelt** [comment]
@flokli Fixed by https://github.com/NixOS/nixpkgs/pull/91232?

**Comment by flokli** [comment]
I think so, yes.
