### ISSUE TITLE
Cannot respond to prompt in stage1

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#62049]
## Issue description

I have a VM on Vultr, and when I get to [the `fail` function](https://github.com/NixOS/nixpkgs/blob/cc97412a2663fd8ee606098f20a37c1b7a817454/nixos/modules/system/boot/stage-1-init.sh#L47) of stage1, I cannot use the keyboard on the remove console to select an item.

Oddly though, Grub works.

### Steps to reproduce

* Run Nixos on Vultr
* edit the boot command from grub with 'e'
* add `boot.debug1` to the linux command line, boot with ctrl-x
* You'll see the menu for `fail`, but no response to keyboard input

It seems as if the keyboard input is intercepted somewhere.

It would be great if `boot.debug1` would directly start a shell instead of prompting. Perhaps that won't make a difference though if input doesn't work…

**Comment by teto** [comment]
I was advised boot.debug1 on irc once but try with boot.debug1devices (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-1-init.sh#L158), it will load more modules including the keyboard driver I think. At least it worked in my case.

**Comment by teto** [comment]
still active via https://github.com/NixOS/nixpkgs/pull/89365

**Comment by wmertens** [comment]
merged
