### ISSUE TITLE
move ./pkgs/misc/vim-plugins/update.py to maintainers/scripts/ ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#62062]
## Issue description
move ./pkgs/misc/vim-plugins/update.py to maintainers/scripts/ for consistency ? 

also it would be nice to be able to remove the generated file pkgs/misc/vim-plugins/generated.nix while still having the script functional ? I often have some changes in it and when rebasing I just want to skip this file but I end up doing repeated `git checkout channels/nixos-unstable -- pkgs/misc/vim-plugins/generated.nix; git rebase --continue`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by FRidh** [comment]
Suggest you cc the vim maintainers

**Comment by teto** [comment]
good idea /cc @mic92 @timokau

**Comment by timokau** [comment]
I think its a little more discoverable to have it in `vim-plugins`, but I don't care very strongly either way.

> also it would be nice to be able to remove the generated file pkgs/misc/vim-plugins/generated.nix

I wasn't aware it doesn't work like that currently. Would be a welcome change.

**Comment by Mic92** [comment]
I also think it is more discoverable in vim-plugins. I am not sure, what the second part regarding removing `generated.nix` exactly means.

**Comment by teto** [comment]
It means that removing pkgs/misc/vim-plugins/generated.nix shouldn't prevent nixpkgs evaluation (like for haskell or lua generated file). It makes some tasks faster (when the file generated is not valid nix or when rebasing for instance)

**Comment by Mic92** [comment]
So it should fallback to an empty set if the file does not exists?

**Comment by teto** [comment]
I think so.

**Comment by teto** [comment]
Nothing of importance and opinions are split, let's not change things if there is no clear advantage. Closing.
