### ISSUE TITLE
Abstract services.foo.database?

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#62073]
More than a few services have a `services.foo.database` option which generally includes a few options like `type`, `host`, `port`, `user`, `password`/`passwordFile`, `socket`, and maybe `createDatabase`/`createLocally`.

Should we abstract this so module writers can take advantage of this and users have a more consistent experience?

cc @flokli @globin @Infinisil @aszlig @florianjacob @Ma27 @etu @danbst @peterhoeg as potentially interested parties

**Comment by Ma27** [comment]
I'm definetely in favor that idea! This is one the problems that cause (IMHO) too much duplications in our modules and I had to fix issues with units relying on `postgresql.service` too often when using a database on a different machine :+1:

**Comment by aanderse** [comment]
I should really get around to doing this...

**Comment by peterhoeg** [comment]
I know I plus-one'd the original post, but yes, this would be fantastic.

**Comment by florianjacob** [comment]
@aanderse …do we really have a database abstraction now that I miss? :monocle_face:

**Comment by aanderse** [comment]
no, but i never got around to it and lost interest in implementing it 🤷‍♂️

still a pretty good idea, in my opinion, if anyone else wanted to tackle it
