### ISSUE TITLE
Is the nixos/gui folder still alive?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6207]
It looks like it hasn't been touched in over a year

**Comment by offlinehacker** [comment]
I think you should use nixui now: https://github.com/matejc/nixui

**Comment by nbp** [comment]
No this was an early attempt that I made while we were still using the svn repository.  It depends on an old version of xulrunner, and as we did not had any JSON output at the time, I made it such that it parse the xml output of nixos-option (which was made for it).

It used to worked, but I failed at communicating about it:
http://old.nabble.com/NixOS%3A-Graphical-User-Interface-td31467386.html
http://nbp.name/img/nixos-gui.png

**Comment by copumpkin** [comment]
I see. TBC, I'm asking more from the angle of "is this dead code in the repo that we could remove" than "what should I do instead"?

**Comment by nbp** [comment]
Yes, this is dead code.
And if you don't mind I will remove it ;)

**Comment by copumpkin** [comment]
:+1:

**Comment by vcunat** [comment]
:+1:

**Comment by iElectric** [comment]
Done

**Comment by copumpkin** [comment]
Thanks!
