### ISSUE TITLE
Control+letter doesn't work in terminal

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#62092]
## Issue description

Control+letter doesn't work in terminal. For example if I press `Ctrl+L` `^L` is printed and no cleaning of screen takes place. It may be related to behavior of the `readline` library but I lack expertise to say for sure.

In addition, my prompt is displayed in the following fashion:

```
\[\][\[\]mark@nixos:~]$\[\]
```

The two issues may be related.

### Steps to reproduce

I'm on `f52505fac8c82716872a616c501ad9eff188f97f` 19.03. It should be enough to switch to that version of NixOS and open any terminal emulator. I tried with `cool-retro-term` and `konsole`.

## Technical details

> Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the results.

Here we go:

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.git.f52505f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6631_e58a7144`
 - channels(mark): `"nixos-18.09.2337.5d972dd2c94"`
 - nixpkgs: `/home/mark/nixpkgs`

**Comment by mrkkrp** [comment]
I found that this is in fact something bash-specific. `fish` works just fine. Also, the problem is there even if I drop all bash-specific configuration from my `configuration.nix` file.

**Comment by Atemu** [comment]
You need to use `bashInteractive`; `bash` is non-interactive.
