### ISSUE TITLE
Dropbox doesn't use a hash to verify its installer download

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#62108]
## Issue description

Using fetchurl to download the Dropbox installer along with a hash of the installer would be nice, because it would help verify that the installer being used is what the packagers intended on using.

Is there some reason not to do this? Like, maybe Dropbox regularly replaces the binary at a certain URL.

ref https://github.com/NixOS/nixpkgs/blob/d5dbfad91add6a0e51fd7619322b5382b8ad7074/pkgs/applications/networking/dropbox/default.nix#L17

@siddharthist @ttuegel

**Comment by siddharthist** [comment]
Looks like this commit removed the hashes from the file: https://github.com/NixOS/nixpkgs/commit/9a9ea65de9a80772dc3c385b7cd2c29a4ae1122

**Comment by peterhoeg** [comment]
Dropbox was a royal pain to deal with as alluded to in the referenced commit message:

```
The client's automatic updater is fixed; this obviates the need to
update Dropbox in Nixpkgs every time the client is updated upstream!
```

DB would stop working when it detected a new version, downloaded it and then tried auto-updating (which obviously doesn't work with a RO /nix/store).

**Comment by siddharthist** [comment]
@peterhoeg I dont understand what the self-updating has to do with whether or not we use a SHA256 hash to verify the installer download, can you expand on your comment?

**Comment by peterhoeg** [comment]
Because dropbox will update itself anyway there is no point having to manually update the list of checksums - the version you are running 5 minutes after you installed dropbox will not be the same.

**Comment by siddharthist** [comment]
@peterhoeg Ok, thanks for clarifying!

**Comment by ryantm** [comment]
@peterhoeg isn't it still important to make sure the first one is verified? Otherwise, how can you trust the updates?

**Comment by peterhoeg** [comment]
The sha256 doesn't really buy us anything in this case.

1. We're fetching via https so we're sure that we are getting it from the owner of the dropbox.com domain
2. It's closed source so we have no way of verifying if this is "proper" or not.

It simply adds to the maintenance burden for no gain.
