### ISSUE TITLE
A stop job is running for Container

### ISSUE THREAD

**Issue by valeriangalliat** [NixOS/nixpkgs#6212]
Hi,

I'm using declarative NixOS containers, and everytime I reboot, systemd waits 1min 30s with the following message:

```
A stop job is running for Container '{name}' ({elapsed} / 1min 30s)
```

However if I run `nixos-container stop {name}; reboot`, it's instantaneous.

I'm using the `unstable` channel. Here's the minimal configuration to reproduce:

```nix
{ config, pkgs, ... }: {
  # Hardware, GRUB, networking, users.

  containers.web = {
    autoStart = true;

    config = { config, pkgs, ... }: {
      services.httpd = {
        enable = true;
        adminAddr = "admin@example.com";
      };
    };
  };
}
```

**Comment by edolstra** [comment]
Yeah, I've noticed this as well...
