### ISSUE TITLE
Fixed derivation build error for jre on aarch64

### ISSUE THREAD

**Issue by netixx** [NixOS/nixpkgs#62148]
## Issue description
Error while building/downloading jre on aarch64:
```
trying https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jre_aarch64_linux_hotspot_11.0.3_7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
copying path '/nix/store/z39750n18nyhw7048ds8zpsgjs0ccdsn-gpgme-1.12.0' from 'https://cache.nixos.org'...
100   643    0   643    0     0   1432      0 --:--:-- --:--:-- --:--:--  1432
building '/nix/store/sf46lc0xzj3mkbc83wpnlzchj9l2m3ga-container-init.drv'...
building '/nix/store/9biqlgm8db790xr5x33349dxs4rqkr4x-dbus-catalog.xml.drv'...
copying path '/nix/store/n8b5350v0xswvl08mlra5asyy8nfsrdl-volume_key-0.3.11' from 'https://cache.nixos.org'...
building '/nix/store/wgyac8d2yi0phyfbaq13rj2w7chg5mlp-etc-10-nixos.rules.drv'...
building '/nix/store/lks66gm13aj64zw9qclj8vy213ra47lh-etc-bashrc.drv'...
100 38.8M  100 38.8M    0     0  7149k      0  0:00:05  0:00:05 --:--:-- 9334k
hash mismatch in fixed-output derivation '/nix/store/pc2krcggyflqbgpz6zlpzxr7hjyfdlif-OpenJDK11U-jre_aarch64_linux_hotspot_11.0.3_7.tar.gz':
  wanted: sha256:0hisjzgv29x2af0wvpy1c9j027qvv08cd9r9f0hg40wdczbbgxaa
  got:    sha256:0r45f358ih5xmygqm91g6nkq9d6nnjl8zz75kl4xbij00svzlcfy
cannot build derivation '/nix/store/qcnj8vqvf5p11s4421j3rjbby7qn2hn5-adoptopenjdk-jre-hotspot-bin-11.0.3.drv': 1 dependencies couldn't be built
```

### Steps to reproduce
The error occured when I added `services.xserver.desktopManager.kodi.enable = true;`. But any use of the jre under aarch64 should give the same result as long as free packages are used (i.e. not using the oracle jre build).

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"aarch64-linux"`
 - host os: `Linux 5.0.12, NixOS, 19.03.172463.6e29f22551d (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172753.f197f57bd33"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by netixx** [comment]
@domenkozar @taku0

**Comment by taku0** [comment]
Maybe it is fixed by b67f792793ebe49fbaf0fe63fe946d69cd05f742 and 069e1a7402e89aea2f4a792fc71c900c15e02e17.  It should be backported to the stable branch.

**Comment by taku0** [comment]
@netixx the patches are merged into the stable branch. Could you try it and close the issue if it works?

**Comment by netixx** [comment]
I used the following code (unstable being https://nixos.org/channels/nixos-unstable):

```nix
let
unstable = import <unstable> {};
in
 nixpkgs.overlays = [
    (self: super: {
      kodi = unstable.pkgs.kodi;
    })
  ];
```

and the build succeeded. Thank you for your help !

However the video driver is now missing... Do any of you have previous experience with running xserver on `odroid-c2` by any chance ?

**Comment by vcunat** [comment]
Original problem is fixed (apparently), so better create a separate thread for new ones (unless you immediately solve them).
