### ISSUE TITLE
The MySql 5.5.40 download URL is broken for me

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6219]
Not sure anyone notices when there are pervasive binary caches, but I've been getting 404s for a few days now.

**Comment by copumpkin** [comment]
It looks like the website links to http://cdn.mysql.com/archives/mysql-5.5/mysql-5.5.40.tar.gz now. I'm not sure how best to update the mirrors file to point at the new location without rebuilding the world, though. I can change it to a fixed url for now. Anyone have opinions?

**Comment by vcunat** [comment]
Changes in mirrors and URLs don't cause any rebuilds. That's the main point why fetchurl is a fixed-output derivation.
