### ISSUE TITLE
add a callNode2nix similar to callCabal2nix

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#62219]
## Issue description
I am trying to package https://github.com/iamcco/markdown-preview.nvim (tried another preview plugin before but it would show an empty preview ;s ). This one relies on node packages so I've dived into the node ecosystem (also because I would be interested in fetching node packages for coc.nvim ).

My understanding (since the doc is so short: https://nixos.org/nixpkgs/manual/#node.js-packages) is that one needs to write a generate.sh and pkgs.json  (taking pkgs/development/web/remarkjs/ as an example) and calling generate.sh will generate nodepkgs.nix node-env.nix.

My question is then:
- can I just skip the previous steps and do node.withPackages(p: [] ) ?
- would it be possible to add a callNode2nix as callCabal2nix ? this would allow to alleviate some workload and generate the code from the source pacakges.json instead of providing ours ?

**Comment by svanderburg** [comment]
@teto No specific reason. It's just I'm not completely familiar with `callCabal2nix` and what it offers.

But I assume your use case is to add an NPM package as a dependency to another project?

**Comment by teto** [comment]
callCabal2nix is just a convenience, what I am really interested in is to be able to generate a node environments based on vim plugin requirements. All the popular `coc-*` and all the markdown viewers involve node packages. Due to the difficulty of creating an environment from them, we are limited to build only tagged releases as opposed to from source, and even then I still have problems such as https://github.com/iamcco/markdown-preview.nvim/issues/168.
There is also https://github.com/NixOS/nixpkgs/pull/84225

**Comment by Pablo1107** [comment]
No related to the issue but to markdown-preview, did you manage to package it @teto ?

I actually don't have my vim config on nix, and I found that I can't use this plugin because it requires running the plugin binary. Completely off topic, but can NixOS run binaries without relying on `patchelf`?

**Comment by teto** [comment]
@Pablo1107 I kinda avoid any node related packages since I found them hard to use/package on nixos. I've packaged https://github.com/NixOS/nixpkgs/pull/84213 instead.

**Comment by gvolpe** [comment]
@teto any ideas on how I could make this work? https://discourse.nixos.org/t/how-to-override-coc-vim-plugin/7991 

It is somewhat similar and I'm kind of running in circles at the moment... :|

**Comment by mikelpr** [comment]
I found [this implementation](https://github.com/eviefp/roll/blob/5bcb0371fcae26b773573bafa9509429e59f30e0/nix/callNode2Nix.nix) of callNode2Nix searching on github, but there's no LICENSE on that project. it's basically it calls node2nix on the buildPhase and copies to $out on installPhase

**Comment by teto** [comment]
I suppose buildNpmPackage fills the role. closing.
