### ISSUE TITLE
sane backends: libusb libraries are not visible

### ISSUE THREAD

**Issue by bstrik** [NixOS/nixpkgs#6223]
After a build of libusb (libusb-compat) the package is correctly created in the /nix/store. The libraries are indeed present.
However they are not accessible in the nix environment.
I get: libusb-0.1.so.4 => not found
The only libraries visible are those of the libusb1 (libusb) package.
I think this is a bug in the build process or the way the package is constructed.
I desperately need the libusb-compat libraries for my software.
Can someone have a look at this.

**Comment by vcunat** [comment]
I checked the package provides libusb.so, usb.h, libusb.pc, etc. I suspect you attempt to use it in a wrong way - e.g. the fact that something is in your nix store doesn't make it automatically visible (that's intentional). *How* are you searching for it?

**Comment by bstrik** [comment]
Well, I made a package for a Brother scanner(A). This package needs libusb and is correctly stored in the nix-store. I made package (A) known to sane (B) by using:

hardware.sane.extraBackends = [ pkgs.A ];

I can see that some so-files (from A) are present in the directories (of B) as expected.
The point is that those so-files need libusb-compat (libusb) which is a buildInput in pkg A.
But pkg A is not referenced in the buildInputs of pkg B. Pkg B is linked against libusb1.

  saneBackends = callPackage ../applications/graphics/sane/backends.nix {
    gt68xxFirmware = config.sane.gt68xxFirmware or null;
    snapscanFirmware = config.sane.snapscanFirmware or null;
    hotplugSupport = config.sane.hotplugSupport or true;
    libusb = libusb1; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<!!!!!!!!!!!!!!!!!!!!
  };

And here we have our problem.

How can I solve this?
Eagerly awaiting your response.

Btw I have the same problem with printdrivers in relation to cups.

**Comment by vcunat** [comment]
I don't know in what way sane accesses the backends. I see the ``hardware.sane.extraBackends`` option causes some files from the packages symlinked, so sane uses those files somehow. CC @peti (sane maintainer).

Note that libusb (compat version) is just a thin wrapper around libusb1 (consequently libusb propagates libusb1, so both are available at once). Therefore I *expect it doesn't have to* be a problem when a backend uses libusb and frontend uses libusb1 directly.

**Comment by bstrik** [comment]
Question: Did you already notify @peti or should I do this myself. This was not clear to me from your answer.

**Comment by vcunat** [comment]
Github automatically notifies mentioned people (in a way they select).

**Comment by peti** [comment]
I have no definite answer either, I'm afraid. I never had to use any non-standards backends with SANE and thus have no experience doing that. I am sorry I can't be more helpful.

**Comment by bstrik** [comment]
Then I will investigate this further. Thanks for the help sofar.

**Comment by bstrik** [comment]
I finally solved it! The software was distributed from Brother and was made up of precompiled binaries.
All I had to do was change the rpath with patchelf.
Thought I should let you know, sorry for taking your time.
I really start to appreciate this distribution.!!
