### ISSUE TITLE
nixos/wireguard: should use WG_ENDPOINT_RESOLUTION_RETRIES

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#62288]
## Issue description

In https://github.com/NixOS/nixpkgs/pull/61971 there was an option introduced that indefinitely tries to restart the wireguard service until all
peer hostnames are resolved. Instead it should use `WG_ENDPOINT_RESOLUTION_RETRIES`
as introduced by 
https://git.zx2c4.com/WireGuard/commit?id=a1a1c1723b6423e43d71cfa52862fad9bbcd265b
instead. This feature will be available in the next snapshot release of wireguard.
cc @sjau @Ma27 @zx2c4

**Comment by zx2c4** [comment]
Alright 0.0.20190531 has been released for the purpose of this disaster being fixed. @sjau care to cleanup the mess?

**Comment by sjau** [comment]
I fail to see what mess/disaster you're refering to.
