### ISSUE TITLE
nodejs missing icu- internalization

### ISSUE THREAD

**Issue by janat08** [NixOS/nixpkgs#62365]
## Issue description

https://nodejs.org/docs/latest-v11.x/api/intl.html#intl_internationalization_support
Appears to compile with non-default no icu option even if the option doesn't appear to be passed in build.

### Steps to reproduce

```js
const january = new Date(9e8);
const english = new Intl.DateTimeFormat('en', { month: 'long' });
const spanish = new Intl.DateTimeFormat('es', { month: 'long' });

console.log(english.format(january));
// Prints "January"
console.log(spanish.format(january));
// Prints "M01" on small-icu
// Should print "enero"
```
prints January for spanish

## Technical details
tested with 11, already uninstalled. system/OS has icu installed.

**Comment by matthewbauer** [comment]
Could you try out this pr:

https://github.com/NixOS/nixpkgs/pull/62447

?

It looks to use icu correctly:

```
January
enero
```

(but this is on macOS)

**Comment by janat08** [comment]
I don't know how to test pull requests, I see they assigned someone. It's pure, so I imagine it should work on linux if it works on macOS. I just realized why the default option didn't work with nix being pure.

**Comment by janat08** [comment]
There're apparently versions of ICU, with required versions for node. I think it might be ideal to just pass the option that the full ICU version be bundled, instead of system one.
