### ISSUE TITLE
Emacs custom initialization not working?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#62361]
## Issue description

[Configuring Emacs](https://nixos.org/nixpkgs/manual/#sec-emacs-config) does not seem to work as described in the manual. Specifically, custom initialization code such as in this [gist](https://gist.github.com/grahamc/2daa060dce38ad18ddfa7927e1b1a1b3) by @grahamc does not seem to actually execute.

### Steps to reproduce

1. Download expression from the [gist](https://gist.github.com/grahamc/2daa060dce38ad18ddfa7927e1b1a1b3).
2. `nix-shell emacs-init-as-a-package.nix --run emacs`
3. `M-: (fboundp 'loader-after-plugins)` evaluates to `nil` but woudl be `t` if the init script had run.

I have not been able to understand how the `default.el` file is supposed to be evaluated at startup time. I see `site-init.el` adding directories to `load-path` but not actually loading anything.

## Technical details

```

[luke@interlaken:~]$ nix-shell -p nix-info --run "nix-info -m"
bash: warning: setlocale: LC_ALL: cannot change locale (en)
/nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en)
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.35, NixOS, 19.03.172286.8ea36d73256 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(luke): `"nixos-18.09.2565.6cd0603d758, nixos-unstable-19.09pre179307.bc94dcf5002"`
 - channels(max): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
You need to invoke it like this:

```
nix-shell -p '(import ./emacs-init-as-a-package.nix {})' --run emacs
```

or alternatively:

```
nix run '(import ./emacs-init-as-a-package.nix {})' -c emacs
```

**Comment by lukego** [comment]
Thank you @matthewbauer!
