### ISSUE TITLE
ghcid is not working 

### ISSUE THREAD

**Issue by paolino** [NixOS/nixpkgs#62375]
## Issue description

in a fresh project with at least one compilation error, running ghcid I get

*ghcid: fd:16: hGetLine: invalid argument (invalid byte sequence)*

using stack-compiled (whatever version or packaging) ghcid from lts-13.23, the command  works fine

### Steps to reproduce

stack new test
cd test
echo "foo" > src/Lib.hs
ghcid

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-693.11.6.el7.x86_64, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(developer): `"nixpkgs-19.09pre181045.61f0936d1cd"`
 - nixpkgs: `/home/developer/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Could you try setting `LC_ALL=C.UTF-8`?

**Comment by paolino** [comment]
It solved! Still wonder how it's working with the stack-compiled one. 
Btw, thanks a lot!
