### ISSUE TITLE
nix-env -u replaced go with go-yaml

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#6243]
I just ran nix-env -u --always \* and saw this:

upgrading ‘go-1.4.1’ to ‘go-1.4.1-yaml-v1-b0c168a’

Paging @lethalman because you made the yaml expression... I don't know whether this was a pre-existing problem though. I don't really use go.

**Comment by wmertens** [comment]
This is due to the version number being before the rest of the package name. I wonder if nix-env can be made to store attribute names instead of looking up names.

**Comment by vcunat** [comment]
IMO the best solution is to have it named "go-yaml-1.4.1-...".

**Comment by lethalman** [comment]
Blame me, going to fix this.

**Comment by lethalman** [comment]
Btw python does something similar, e.g. `python3.4-Pillow-2.3.0`. So I guess I'm going to remove the dash between go and the version, but not putting it after the package name. Otherwise you get the same behavior except with go 1.4 and go 1.3 for the same package.
