### ISSUE TITLE
xdg-icon-resource install: cannot touch '/homeless-shelter/.local/share/icons/hicolor/.xdg-icon-resource-dummy'

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#62495]
I'm packaging phoronix-test-suite.

I get this error in the install process:

```
mkdir: cannot create directory '/homeless-shelter': Permission denied
mkdir: cannot create directory '/homeless-shelter': Permission denied
touch: cannot touch '/homeless-shelter/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
```

It's probably caused by this command: `xdg-icon-resource install --context mimetypes --size 64 pts-core/static/images/openbenchmarking.png application-x-openbenchmarking`

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/8ef44f39baf65e7473ce4670189ff64cd09113e9/install-sh#L106

Any idea why `/homeless-shelter` is used here?

Do i have to do something like this to fix the error? https://github.com/NixOS/nixpkgs/blob/32767d139f28fd3c00d687c04ec406258f7341e7/pkgs/applications/version-management/smartgithg/install_freedesktop_items.sh#L7

**Comment by jtojnar** [comment]
`HOME=/homeless-shelter` by default. You can try to set `HOME=$TEMPDIR` or `XDG_DATA_HOME=$TEMPDIR` to avoid this issue.

**Comment by jtojnar** [comment]
You can also use `DESTDIR=/.` or not provide xdg tools to use the chroot branch: https://github.com/phoronix-test-suite/phoronix-test-suite/blob/8ef44f39baf65e7473ce4670189ff64cd09113e9/install-sh#L102

**Comment by davidak** [comment]
@jtojnar thanks! Does the chroot branch has any disadvantages in this case?

**Comment by jtojnar** [comment]
Mostly that the `cp` command, unlike the `xdg-tools` will not rebuild relevant caches:

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/8ef44f39baf65e7473ce4670189ff64cd09113e9/install-sh#L123-L124

But we have setup hooks that would clean them up anyway.

**Comment by davidak** [comment]
I understand. Thanks!
