### ISSUE TITLE
KDE plasma5 does not work in 19.03-release

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#62587]
## Issue description
When logging in, krunner works, but nothing else (e.g. desktop with background, menu bar, etc.) does. 

### Steps to reproduce
Unknown, but I'd expect that anyone using KDE in its default configuration would experience this. 

## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 5.1.3, NixOS, 19.03.git.606306e (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-18.09.1571.7795a7ad5f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by memberbetty** [comment]
A reboot fixed the issue, but I'd expect that after a suspend to RAM and logging back in the system would work.

**Comment by FRidh** [comment]
Unless it's not encountered more often it's not worth investigating so closing.
