### ISSUE TITLE
p11-kit does not pass check on macOS

### ISSUE THREAD

**Issue by Kaali** [NixOS/nixpkgs#62614]
## Issue description

p11-kit checks fail on macOS. I think they never passed on macOS, but commit c739b09d85d0dab23a9d6ffaef2ec525c28e7086
 enabled checking and now they are failing.

Test log included [p11-test.log](https://github.com/NixOS/nixpkgs/files/3248086/p11-test.log)

### Steps to reproduce

1. Fetch nixpkgs master (37e4161535649b8c09d67cf87e2b1c4decea7f16)
2. ```nix-build '<nixpkgs>' -A p11-kit```
3. Fail

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.6.0, macOS 10.14.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(kaali): `"nixpkgs-19.09pre172680.92ec809473e"`
 - nixpkgs: `/Users/kaali/dev/nix/nixpkgs`

**Comment by matthewbauer** [comment]
A pr just setting `doCheck = !stdenv.isDarwin` would definitely be okay!
