### ISSUE TITLE
X11 user session is not initialized correctly using lightdm

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#62639]
## Issue description
The user session (systemd-logind) is often not initialized correctly. I don't understand exactly what's broken but the results are:
- audio doesn't work as the user lacks permission to access the mixer (alsa)
- systemd user services are not working
- some application are not working because $XDG_RUNTIME_DIR is not set
- $XDG_SESSION_ID is not set

More info:
```
$ loginctl show-session 5
Id=5                                  
User=1000                             
Name=my-user                              
Timestamp=Mon 2019-06-03 21:44:56 CEST
TimestampMonotonic=5898518836         
VTNr=7                                
Seat=seat0                            
Display=:0                            
Remote=no                             
Service=lightdm                       
Desktop=none+bspwm                    
Scope=session-5.scope                 
Leader=17083                          
Audit=5                               
Type=x11                              
Class=user                            
Active=yes                            
State=opening                         
IdleHint=no                           
IdleSinceHint=0                       
IdleSinceHintMonotonic=0              
LockedHint=no                         

$ systemctl --user status                                                           
Failed to read server status: Process org.freedesktop.systemd1 exited with status 1 
```

### Steps to reproduce
The session is `none+bspwm`, affects both slim and lightdm.

## Technical details
- system: `"x86_64-linux"`                                                               
- host os: `Linux 5.1.4, NixOS, 19.03.172725.a59b6608f97 (Koi)`                          
- multi-user?: `yes`                                                                     
- sandbox: `yes`                                                                         
- version: `nix-env (Nix) 2.2.2`                                                         
- channels(root): `"nixos-19.03.172786.606306e0eaa, unstable-19.09pre181629.ae71c13a92f"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`                          

---
#33451 may be related

**Comment by peterhoeg** [comment]
Could you try with sddm?

**Comment by rnhmjoj** [comment]
So, I have been trying sddm for a while and it seems to have stopped. I guess it could be something in the way sddm starts X.

**Comment by ashkitten** [comment]
i've been having this issue for quite a while with lightdm. possibly relatedly, lightdm also does not pre-fill the login prompt with my user anymore.

**Comment by rnhmjoj** [comment]
@ashkitten can you check wether the environment variables I mentioned are unset?

**Comment by ashkitten** [comment]
@rnhmjoj correct, and setting them manually lets me use `systemctl --user`

**Comment by peterhoeg** [comment]
It's our PAM settings that are wrong:

```sh
$ grep systemd /etc/pam.d/{lightdm,sddm}
/etc/pam.d/sddm:session optional /nix/store/wzrglgf7i2zajmm5k53hypgnv3n0z3v6-systemd-242/lib/security/pam_systemd.so
```

We need to load pam_systemd.so for the proper session variables to be set.

**Comment by rnhmjoj** [comment]
@peterhoeg I'm not familiar with PAM: can you tell me what to try exactly?
Note: the issue is present with slim also.

**Comment by worldofpeace** [comment]
I've recently rewritten lightdm's PAM config, and committed a better nixos global pam config.
Is this issue reproducable on nixos-unstable?

**Comment by xavierzwirtz** [comment]
I think I was having the same issue, swapped over to nixos-unstable and it is not happening.

**Comment by rnhmjoj** [comment]
It seems it's no longer an issue. Closing.
