### ISSUE TITLE
virt-manager: Error opening Spice console, SpiceClientGtk missing

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#62647]
## Issue description

Running Nixos Unstable I "recently" got an error that virt-manager can't open display anymore for VMs. It pops up with the error:

`Error connecting to graphical console:
Error opening Spice console, SpiceClientGtk missing`

### Steps to reproduce

I have the following in my configuration.nix:

```
[...]
    # Enable libvirtd daemon
    virtualisation.libvirtd = {
        enable = true;
#        enableKVM = true;
        qemuPackage = pkgs.qemu_kvm;
    };
    services.spice-vdagentd.enable = true;
    # Make smartcard reader and label printer accessible to everyone, so they can be passed to the VM
    services.udev.extraRules = ''
        SUBSYSTEM=="usb", ATTR{idVendor}=="072f", ATTR{idProduct}=="90cc", GROUP="users", MODE="0777"
        SUBSYSTEM=="usb", ATTR{idVendor}=="04f9", ATTR{idProduct}=="2043", GROUP="users", MODE="0777"
        KERNEL=="zd*", SUBSYSTEM=="block", GROUP="users", MODE="0660"
    '';
[...]
        extraGroups = [ "networkmanager" "vboxusers" "wheel" "audio" "cdrom" "kvm" "libvirtd" "adbusers" "docker" ]; # wheel is for the sudo group
[...]
        spice
        spice-gtk
        win-spice
        [...]
        virt-viewer
        virtmanager
```

I open virt-manager, start a vm and try to connect to the screen in virt-manager. That's when I get the error. However virtviewer can still display it.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.6, NixOS, 19.09pre181346.b3dd39ca0e9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(hyper): `"nixos-19.09pre179853.bc9df0f6611"`
 - channels(root): `"nixos-19.09pre181346.b3dd39ca0e9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
It sounds like the executable doesn't have `GI_TYPELIB_PATH` wrapped with the typelibs from `spice-gtk`.
Sounds like maybe https://github.com/NixOS/nixpkgs/issues/56943

**Comment by worldofpeace** [comment]
Perhaps your channel, etc is behind because this appears to have already been fixed https://github.com/NixOS/nixpkgs/pull/57385

**Comment by sjau** [comment]
it's Nixos Unstable - it's not that much behind. That fix was released in april.

**Comment by worldofpeace** [comment]
Yep that is correct
```
❯ git show b3dd39ca0e9
commit b3dd39ca0e9a8da121154e59fea86143232c0ab7
Merge: a41b38eb266 1de35c7f5ec
Author: Florian Klink <flokli@flokli.de>
Date:   Fri May 31 23:17:18 2019 +0200
```

**Comment by sjau** [comment]
ok.... but still weird, because the last two rebuilds were on june 1:

```
submenu "NixOS - All configurations" {
menuentry "NixOS - Configuration 528 (2019-06-01 - 19.09pre181346.b3dd39ca0e9)" {
search --set=drive1 --fs-uuid 9bcbc94c-0cf5-4196-8743-30cff4da376a
  linux ($drive1)//kernels/m1jycll1xqg44dprfvhax8inryl137il-linux-5.1.6-bzImage systemConfig=/nix/store/05i2j5vih2x8l15lc2kdjga0m08z02db-nixos-system-subi-19.09pre181346.b3dd39ca0e9 init=/nix/store/05i2j5vih2x8l15lc2kdjga0m08z02db-nixos$
  initrd ($drive1)//kernels/cayzkfpc15cz9ix9slj3b0gsagzac37w-initrd-linux-5.1.6-initrd
}

menuentry "NixOS - Configuration 527 (2019-06-01 - 19.09pre180814.28b4f7b6ace)" {
search --set=drive1 --fs-uuid 9bcbc94c-0cf5-4196-8743-30cff4da376a
  linux ($drive1)//kernels/2z3wi3jnz5njx20lhfaf71ij362lfjva-linux-5.1.4-bzImage systemConfig=/nix/store/8rm6m5d1f4ssgs6fl97k2pqncg1xmhcb-nixos-system-subi-19.09pre180814.28b4f7b6ace init=/nix/store/8rm6m5d1f4ssgs6fl97k2pqncg1xmhcb-nixos$
  initrd ($drive1)//kernels/b6zwlcady1i822k5127kj8ck1234z452-initrd-linux-5.1.4-initrd
```

I didn't expect unstable to be that old.

**Comment by sjau** [comment]
so that means, I already have those patches and the problem is elsewhere.

**Comment by ivan** [comment]
I have the same problem on NixOS master and reverting https://github.com/NixOS/nixpkgs/commit/b6ddecf2b2f4816b8d1d3a83495fca57422b5971 fixes it.

**Comment by JohnAZoidberg** [comment]
I have the same problem on unstable (`nixos-19.09pre182429.98e3b90b6c8`).
As a workaround I connect using virt-viewer.

**Comment by ivan** [comment]
This can be closed as it is working now.

**Comment by JohnAZoidberg** [comment]
Yes it works now on i3.
However virt-manager doesn't seem to save the connections anymore, even though I have `gnome3.dconf` installed.

**Comment by worldofpeace** [comment]
> However virt-manager doesn't seem to save the connections anymore, even though I have gnome3.dconf installed.

That should be another issue.

Closing.
