### ISSUE TITLE
CONFIG_IRQ_REMAP in default kernel configuration

### ISSUE THREAD

**Issue by dwe11er** [NixOS/nixpkgs#6264]
Is there any particular reason why interrupt remapping isn't enabled by default?

There is workaround by using  allow_unsafe_interrupts=1 option of vfio_iommu_type1, but it's not ideal and can lead to crash of the host or escalate their privileges on the host (VM's on NixOS are running as root user; it can be changed in qemu.conf).

**Comment by iElectric** [comment]
cc @edolstra

**Comment by edolstra** [comment]
@iElectric I don't really know what this does, but it seems fine to enable it...

**Comment by Profpatsch** [comment]
(triage) updates?

**Comment by joachifm** [comment]
I believe this can be closed:

> $ grep IRQ_REMAP $(nix-build -A linux.configfile)      
CONFIG_IRQ_REMAP=y
