### ISSUE TITLE
Failing `nixos-rebuild switch` because of long networking.extraHosts

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#6276]
My `networking.extraHosts` has about 900,000 entries, which caused the `nixos-rebuild switch` command to fail because somewhere the bash gets too many arguments.

I guess you guys should know that...

**Comment by dwe11er** [comment]
It's bash limitation. Also, its better to use **dnsmasq** for hosts filters instead hammering all the entries into */etc/hosts*.

**Comment by lethalman** [comment]
Well given it's a bash limitation we must fix the way we create that file.

**Comment by edolstra** [comment]
See https://github.com/NixOS/nix/issues/473.

But in this case we should be able to use `builtins.toFile`, given that hosts entries are unlikely to depend on derivations.

**Comment by matthiasbeyer** [comment]
@dwe11er I just tried it with dnsmasq, it fails with the same error!

**Comment by matthiasbeyer** [comment]
Any updates on this or how to do this properly? I really would like to block connections to facebook, you know? :smile:

**Comment by copumpkin** [comment]
@matthiasbeyer we had someone with the same issue on IRC just now and got it working by setting

```nix
{
  environment.etc."hosts".source = /path/to/your/hosts;
}
```

You lose the automatic merging with 127.0.0.1 but it should otherwise be fine. You could also make the `/path/to/your/hosts` into a derivation and construct the file yourself as you see fit.

**Comment by matthiasbeyer** [comment]
Solved this issue for me. Thanks a lot!
