### ISSUE TITLE
mpd: directory /var/lib/mpd cannot be created due to permission errors

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#6277]
Hi.

When enabling mpd, it tells me that it can't create `/var/lib/mpd` due to `Permission denied`.

How to fix this?

**Comment by matthiasbeyer** [comment]
Just noticed the same issue with `rsnapshot`, it want's to write a logfile `/var/log/rsnapshot` for writing logs, but can't because of permissions.

**Comment by joachifm** [comment]
Just a guess, but the problem might be that mpd's preStart script is executed as the mpd user. Enable PermissionsStartOnly in the mpd service configuration to execute preStart as root instead.

**Comment by lethalman** [comment]
Didn't test the fix, but looks quite trivial. For rsnapshot I think it's a little more complicated. Feel free to open a different issue, thanks.
