### ISSUE TITLE
Package/Service: Pleroma

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#62820]
## Issue description

(I think) We want a plemora package and service.

This is the tracking issue.

* (Relevant) Topics: elixir, postgres, 
* URL: https://pleroma.social/

**Comment by yegortimoshenko** [comment]
Buildable with https://gist.github.com/yegortimoshenko/0b6987ed3fafb93fa47a6985cda0aa8f but not appropriate for Nixpkgs import due to heavy use of eval-time fetches.

**Comment by matthiasbeyer** [comment]
Plemora got released as 1.0.0 just yesterday. It's about time we ship it!

**Comment by ehmry** [comment]
Blocked by stale hex packages in beam-modules, see #63930.

**Comment by bqv** [comment]
Hasn't been blocked for a while now. I have a working derivation for pleroma-be, and pleroma-fe is just a node package so it'll work with enough frobnicating

**Comment by ncryptid** [comment]
Care to share your derivation?

**Comment by NinjaTrappeur** [comment]
Hey, I created a derivation and NixOS module on top of the OTP release (binary release).

I'm using it to run my personal Pleroma instance. It's not perfect yet but it does the job for me.

The code lives here for now: https://git.alternativebit.fr/NinjaTrappeur/pleroma-otp-nixos

I'm planning to upstream that to Nixpkgs in a near future, any feedback is welcome, especially on the open questions listed here: https://git.alternativebit.fr/NinjaTrappeur/pleroma-otp-nixos/src/commit/75ef83fc3c9a2024bdbab98524be69987c470560/readme.md#user-content-open-questions

**Comment by matthiasbeyer** [comment]
Feel free to dump everything into an PR. With 2.2k PRs open, nobody cares about one more or less!

**Comment by NinjaTrappeur** [comment]
It's not about dumping code, it's about maintaining it if it lands on Nixpkgs.

I'm not really willing to maintain a module without a VM test, it's too much friction. 

I'll PR the module in Nixpkgs when I'll overcome the procrastination of writing the said test.

**Comment by NinjaTrappeur** [comment]
FYI, procrastination has been overcome.

Writing the test was more painful than expected.

The PR is ready for review: https://github.com/NixOS/nixpkgs/pull/103138

**Comment by NinjaTrappeur** [comment]
For posterity sake, @petabyteboy has a source build there: https://git.petabyte.dev/petabyteboy/nixfiles/src/branch/master/pkgs/pleroma

See https://github.com/NixOS/nixpkgs/pull/103138#issuecomment-726503350 where they explain why they couldn't upstream that to nixpkgs yet.

**Comment by NinjaTrappeur** [comment]
Implemented as a bindist by https://github.com/NixOS/nixpkgs/pull/103138

------------

Source build welcome!
