### ISSUE TITLE
nixos/dhcpd fails with networkd if interface has no carrier

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#62844]
## Issue description

The `dhcpd` service fails to start when the NixOS networking is managed by `systemd-networkd` and the interface `dhcpd` is listening on has "no carrier", e.g. there is no cable plugged in.

```
...
Jun 08 00:36:27 dhcpd[973]: No subnet declaration for br0 (no IPv4 addresses).
Jun 08 00:36:27 dhcpd[973]: ** Ignoring requests on br0.  If this is not what
Jun 08 00:36:27 dhcpd[973]:    you want, please write a subnet declaration
Jun 08 00:36:27 dhcpd[973]:    in your dhcpd.conf file for the network segment
Jun 08 00:36:27 dhcpd[973]:    to which interface br0 is attached. **
Jun 08 00:36:27 dhcpd[973]: Not configured to listen on any interfaces!
...
```

### Steps to reproduce

To reproduce this you would need an interface without carrier, e.g. an unplugged ethernet interface on a laptop.

```nix
# NixOS 19.03
{ pkgs, lib, ... }:{

  networking.useNetworkd = true;

  services.dhcpd4 = {
    enable = true;
    interfaces = [ "yourinterface" ];
    extraConfig = ''
      subnet 192.168.0.0 netmask 255.255.255.0 {
        range 192.168.0.100 192.168.0.200;
        option subnet-mask 255.255.255.0;
        # option broadcast-address 192.168.0.255;
        option routers 192.168.0.1;
      }
    '';
  };

}
```

## Technical details

The problem seems to be, that Networkd only assigns IP addresses if an interface has a carrier. As I don't see any solution on the side of ISC DHCP, I guess it needs to be solved in the Networkd config. Originally I thought setting `ConfigureWithoutCarrier=true` would solve the problem, but it didn't. `IgnoreCarrierLoss=true` looks more promising, but is [only available](https://github.com/systemd/systemd/pull/9262) in Systemd 242.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.48, NixOS, 19.03 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `nixos-19.03`

**Comment by Ma27** [comment]
cc @fpletz

**Comment by erictapen** [comment]
I don't use networkd atm, so it's not easy for me to check if the issue persists. Therefore I'll close and reopen whenever I give networkd another try.
