### ISSUE TITLE
BCC causes kernel panic on kernel 4.19.48

### ISSUE THREAD

**Issue by mkmodrzew** [NixOS/nixpkgs#62865]
## Issue description
[BCC](https://github.com/NixOS/nixpkgs/tree/master/pkgs/os-specific/linux/bcc) causes kernel panic while trying to run tools that uses kprobes.

### Steps to reproduce
Install NixOS
nix-env -e linuxPackages.bcc
opensnoop

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.7, NixOS, 19.03.172844.caacbe98ce1 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172844.caacbe98ce1, unstable-19.09pre182256.168d1031af4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## My observations

BCC installed directly through nix-env (or configuration.nix and nixos-rebuild) installs previous version (0.8.0). Installing BCC as a dependency of bpftrace install current version (0.9.0).

## My workaround

It took my a while to make it work properly and with quite a few hacks I was able to. First, I upgraded kernel to the newest version. Second, I installed bpftrace to receive newest BCC. Third, problem with running BCC was linking to wrong kernel version. Trying to run any tool resulted in error "chmod(/nix/store/gh7859s2i0lr1y8rppp28n63gpvngds4-linux-4.19.48-dev/lib/modules/5.1.7/) no such file or directory". To avoid that I created symbolic link from `/nix/store/gh7859s2i0lr1y8rppp28n63gpvngds4-linux-4.19.48-dev/lib/modules/5.1.7` to `/nix/store/gh7859s2i0lr1y8rppp28n63gpvngds4-linux-4.19.48-dev/lib/modules/4.19.48/`. Forth, now I was able to run tools without kernel panic, but with warning in python script:
`
...
File "/nix/store/jz3h2qlk0lww3p3zrjqak557qyjy01ph-bcc-0.9.0/lib/python3.7/site-packages/bcc/table.py", line 625, in _get_event_class
    m = re.match(r"(.*)#(.*)", field)
  File "/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
`
, so I replaced `field` with `field.decode()`. And voila, everything started to work as it supposes in the first place.

**Comment by ivan** [comment]
I believe the kernel panic is resolved by upgrading from 4.19.48 to 4.19.49.

unstable channel doesn't have the 4.19.49-compatible bcc 0.10.0 at the moment, but it should be there soon.

**Comment by Emantor** [comment]
Closing this for now, please comment if this reproduces on the latest stable kernel.
