### ISSUE TITLE
displaylink: broken on xorg.server > 1.19.6

### ISSUE THREAD

**Issue by eyJhb** [NixOS/nixpkgs#62871]
## Issue description
Displaylink is broken as of b981b8e0feffbc12baa68294bb3a291c2f96cffe, which updates xorg.server to be 1.20.3.

This is a known issue both on the evdi driver (part of DisplayLink) - https://github.com/DisplayLink/evdi/issues/133 and on the official website https://support.displaylink.com/knowledgebase/articles/1181623-displaylink-ubuntu-driver-after-recent-x-upgrades .

I have tried applying the fix the suggest on there site 
```
services.xserver.config = 
  ''
    Section "Device"
      Identifier "DisplayLink"
      Driver "modesetting"
      Option "PageFlip" "false"
    EndSection  
  '';
```

But that still does not fix the problem, the only solution I have gotten to work is downgrading to 1.19.6.

I have tried running the latest version of evdi (1.6.1) and Dispalylink (5.1.26), but that still does not solve the problem.

### Steps to reproduce
-

## Technical details
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

Currently running on 19.03 using commit 00322ccb73ed5d5204b7d9e4fad41573337f1470 on nix-channels nixos-19.03.

**Comment by eyJhb** [comment]
Using these files - https://gist.github.com/eyJhb/b44a6de738965a3e895f456be2683b50 and importing into my configuration.nix.

**Comment by nshalman** [comment]
CC @peterhoeg based on #72404

I'm trying to get displaylink working myself and not even getting prompted to go download the displaylink zip file, so additional documentation would also be welcome (even just pointers; I'm happy to write up more detailed instructions once I get it working myself....)

**Comment by peterhoeg** [comment]
What I did (with the PR which has now been merged):

1. 
```
 services.xserver.videoDrivers = [ "displaylink" ];
```
2. ```nixos-rebuild boot``` and reboot
3. run ```xrandr --listproviders``` and verify that you are seeing 2 providers
4. run ```xrandr --output DVI-I-I-1 --right-of eDP-1``` (or whatever your displays are called)
 

But some documentation would be fantastic!

**Comment by nshalman** [comment]
@eyJhb I was able to get it working with the current nixos-unstable channel. (I was having trouble in a Virtualbox VM, but got it to work on a laptop and on a different hypervisor... thanks @peterhoeg!)

Any chance you could try unstable as a test?
Also, what specific hardware model are you using?

**Comment by eyJhb** [comment]
I will try using #72404 as well, and see if that works for me. I previously couldn't get it to work using the method in the PR. But I might have done something wrong...

**Comment by nshalman** [comment]
Given that #72858 was merged, you might also try the latest nixos-unstable channel...

**Comment by eyJhb** [comment]
Tried picking out displaylink and evdi from unstable to my stable build (overriding them using overlays -> did not work).

Currently trying to rebuild against unstable, but will take some time as it has been quite a while since I was on unstable...

**Comment by eyJhb** [comment]
@nshalman tested using `commit e89b21504f3e61e535229afa0b121defb52d2a50 (HEAD -> nixos-unstable, origin/nixos-unstable, origin/HEAD)`, but the result is a non-working monitor as shown below

![Ydn23kQ](https://user-images.githubusercontent.com/25955146/69439170-b001c800-0d46-11ea-8455-35030a4ab440.jpg)

Using a x230 USB 3.0 official docking station for that model and a DVI output.
Using it to get a third display (hooked two other up, using the normal docking station).

So I would still consider it broken sadly. What errors did you experience before the fixes you applied? The same ones as me?

**Comment by eyJhb** [comment]
Closing for now.
