### ISSUE TITLE
rsnapshot fails due to no permission to write /var/log/rsnapshot

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#6289]
This issue is simalar to #6277.

`rsnapshot -v -c /nix/store/<hash>-gen-rsnapshot.conf hourly` fails with:

```
Could not open logfile /var/log/rsnapshot for writing
Do you have write permission for this file?
```

**Comment by matthiasbeyer** [comment]
Modifying the configuration to write the logfile to `/home/<myuser>/.rsnapshot.log` fails then with:

```
echo 22090 > /run/rsnapshot.pid
----------
rsnapshot encountered an error! The program was invoked with these options:
/run/current-system/sw/bin/rsnapshot -v -c ./gen-rsnapshot.conf hourly
----------
ERROR: Could not write lockfile /run/rsnapshot.pid: Permission denied
```

(The file is `./gen-rsnapshot.pid` because I manually copied the config out of
the nix store to modify it, because rsnapshot fails to build because the hash
does not match in the lastest nixpkgs)

**Comment by lethalman** [comment]
The problem is that rsnapshot.pid should not go under /run, because it has no permission to write new files there. Rather, create a directory such as /run/rsnapshot like any other service, and change the permissions in systemd prestart like any other service.
