### ISSUE TITLE
Enable grub debug output by default

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#62905]
Apparently grub has a `grub_dprintf`function that's used for some manner of debug output. I Could we enable showing it by default?

**Comment by davidak** [comment]
I think most desktop users want a start without annoying messages. So i would not enable it by default, at least when `boot.plymouth.enable = true;`. But an option to enable it is useful.

**Comment by deliciouslytyped** [comment]
I don't mean this to sound snarky: Should we hide the nixos stage1/etc loader output as well then?

**Comment by deliciouslytyped** [comment]
My rationale is that it's usually harder to enable boot debug stuff when your system is failing to boot - but if you've explicitly chosen boot eye candy over boot output, sure why not I guess. The ideal case would be if the eye candy can fall back to showing the failure information on failure.

**Comment by davidak** [comment]
>Should we hide the nixos stage1/etc output as well then?

sure (https://github.com/NixOS/nixpkgs/issues/32556)

>The ideal case would be if the eye candy can fall back to showing the failure information on failure.

yes, it would be useful when the system fails to boot. but on NixOS you can just start with previous configuration, so less important than with other distros.

**Comment by deliciouslytyped** [comment]
Rollbacks don't necessarily fix filesystem configuration issues. E.g. when you're migrating to ZFS.

**Comment by deliciouslytyped** [comment]
FWIW I haven't actually had a chance to test this functionality, which would be important in this going forward in any case.

**Comment by samueldr** [comment]
It's unclear in what way this is printed, from my research, it might expect to be printed to a serial port. I haven't been able to find documentation as [apparently some of these things are willfully undocumented](https://lists.gnu.org/archive/html/grub-devel/2010-06/msg00139.html).

Configuring it to use debug print by default is probably a bad idea. The main issue would be the firehose of debugging text, which is not necessarily helpful.

Another issue, yet untested, is that when grub prints things, like error messages, it will do it in an intrusive way. When developing the installer image's boot menu, I found out that *any* error print in their script will pause the menu to show you the errors, even if they are expected and benign under `if`conditionals. **If** they are printed using the same system, it would likely be an issue to users.

What could be done, instead, is to simplify installation of a debug-enabled grub to the system. Either as configured in the NixOS configuration, or even out-of-band by replacing a Grub from the ESP/legacy offsets. (The latter allowing one not to mount a complex system in the installer only to switch to debug mode.)
