### ISSUE TITLE
[sourceforge down] netcat-0.7.1 sha256 differs from the real thing

### ISSUE THREAD

**Issue by letac** [NixOS/nixpkgs#6291]
i'm using master git nixpkgs
part of nixos-rebuild output:	

    output path `/nix/store/kjir2lgljin2i8i5j77pi9d3r9m6bsrk-netcat-0.7.1.tar.bz2' should have sha256 hash `1frjcdkhkpzk0f84hx6hmw5l0ynpmji8vcbaxg8h5k2svyxz0nmm', instead has `0b0l0lbmv7svj36b7j0l3yi74s8qg85bf04a95jivji3f51z96jc'
    building path(s) `/nix/store/0d58a7hydv1a7xz51bn1s6kqc27yh6z7-usbutils-007.tar.xz'
    cannot build derivation `/nix/store/38wzhjvmiam3zmvafzf1gvpkpmdx02ha-netcat-gnu-0.7.1.drv': 1 dependencies couldn't be built
    building path(s) `/nix/store/fazbvaf4hwsk1y9v7pl89kwsa1v6vgp6-xterm-312.tgz'
    cannot build derivation `/nix/store/i14hkv8ziyznsbgdwllh6r6xv0b56mb2-system-path.drv': 1 dependencies couldn't be built
    cannot build derivation `/nix/store/651k60aa4gd0vc4mcr1960rldir3dzcg-nixos-15.05.git.acbd272.drv': 1 dependencies couldn't be built
    error: build of `/nix/store/651k60aa4gd0vc4mcr1960rldir3dzcg-nixos-15.05.git.acbd272.drv' failed

**Comment by peti** [comment]
Interesting. The web site says:

> The sourceforge.net website is temporarily in static offline mode. Only a very limited set of project pages are available until the main website returns to service.

When I try to download the tarball, the first URL gives me "permission denied", and the second URL returns a tarball with a hash different from the one we expect. This looks odd.

**Comment by puffnfresh** [comment]
SourceForge is broken. Homebrew is having the same problems:

https://github.com/Homebrew/homebrew/issues/36703

**Comment by virtustilus** [comment]
Can somebody check any tarball for difference with someone downloaded before?

**Comment by virtustilus** [comment]
Got package with correct sum. Just replaced first part of download link with "http://tenet.dl.sourceforge.net/project/..."
Checking for differences.

**Comment by virtustilus** [comment]
Ok, packages with wring sha1 sum is just have html like "We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later."

**Comment by peti** [comment]
I guess this means the problem will go away once sf.net is back online and operating normally.

**Comment by vcunat** [comment]
SF downloads work fine for me now. Reopen in case of persisting problems.
