### ISSUE TITLE
udocker seems to not work

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#62959]
## Issue description

I just discovered `udocker` and i can't use it on NixOS

### Steps to reproduce

Pulling image seems good

```sh
udocker pull alpine
Warning: no engine available and autoinstall disabled
Downloading layer: sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
```

Trying to run image fail because it try to mount some specials folders

```sh
udocker run alpine
Warning: no engine available and autoinstall disabled
Error: invalid host volume path: /lib/modules
```

The [documentation says](https://indigo-dc.gitbooks.io/udocker/doc/user_manual.html):

> `--nosysdirs` prevent udocker from mapping /proc /sys /run and /dev inside the container

Trying without mounting folder fail because it can't find `proot`

```sh
udocker run --nosysdirs alpine
Warning: no engine available and autoinstall disabled
Error: proot executable not found
```

Start a shell with `proot` still fail because it can't find `proot`

```sh
nix-shell --command fish --packages proot
udocker run --nosysdirs alpine
Warning: no engine available and autoinstall disabled
Error: proot executable not found
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.48, NixOS, 19.03.172844.caacbe98ce1 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(pinage404): `"home-manager-19.03, nixos-19.03.172852.5121b483edc, nixos-unstable-19.09pre182256.168d1031af4"`
 - channels(root): `"nixos-19.03.172852.5121b483edc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ShamrockLee** [comment]
It could still be important.
