### ISSUE TITLE
Conflicting documentation about wpa_supplicant.conf

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#6298]
The options documentation in ```nixos/modules/services/networking/wpa_supplicant.nix``` says two contradictory things:
* NixOS currently does not generate ```wpa_supplicant.conf```.
* If ```userControlled.enable``` is true, be sure not to create ```wpa_supplicant.conf```

Probably the first message should be updated to say under what conditions ```wpa_supplicant.conf``` will be auto-generated, but I don't know how this works.

Paging @edolstra, who seems to be the only one editing ```wpa_supplicant.nix``` (sorry!)

**Comment by edolstra** [comment]
The `userControlled.enable` option was actually added by @bluescreen303 :smiley:
