### ISSUE TITLE
cabal-install doesn't find ghc

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#6299]
When I try to run `cabal init` I get the error `cabal: The program 'ghc' version >=6.4 is required but it could not be found.`. I am using haskellngPackages.cabal-install (just did a git pull but it doesn't seem to have changed). It used to work fine the last time I tried it (a few days ago). I tried going back a few generations where I am pretty sure that it worked but it keeps complaining. I am using cabal with nix-env instead of inside a shell environment.

**Comment by cocreature** [comment]
Just tried using `nix-shell -p haskellngPackages.cabal-install` with the exact same result.

**Comment by cocreature** [comment]
Ah `nix-shell -p haskellngPackages.ghc` work, but shouldn't cabal install also work outside of nix-shell?

**Comment by bennofs** [comment]
I don't see why cabal-install should also bring `ghc` into the user environment. Parts of cabal-install work just fine without GHC, and you might not even need ghc to use cabal install (it also supports other compiler)

**Comment by cocreature** [comment]
Fair enough, closing.
