### ISSUE TITLE
Crystal: Missing YAML dependency

### ISSUE THREAD

**Issue by alexherbo2** [NixOS/nixpkgs#63039]
[Crystal] requires [LibYAML] for its [YAML][Crystal/YAML] module.

[Crystal]: https://crystal-lang.org
[Crystal/YAML]: https://crystal-lang.org/api/YAML.html
[LibYAML]: https://pyyaml.org/wiki/LibYAML

**Comment by FRidh** [comment]
Please use the issue template, it's there for a reason.
