### ISSUE TITLE
failing test in coreutils

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#6306]
The test for dd/sparse.sh fails when building coreutils in 77f160e
***
building tests/dd/sparse.log
FAIL: tests/dd/sparse.sh
***
https://gist.github.com/vandenoever/816b177b0c4ba99c5477
I've tried finding the offending commit with git bisect, but this did not lead me to the offending commit.

I'm running NixOS 14.12 on btrfs with kernel 3.18.0.

**Comment by vandenoever** [comment]
aea1254f96b068d370cb0dbc16638e7cef8ba84c seems to be the first problematic commit. The preceding commit, c45372f038bc89c69390bdbc6a4b0bfdb63b1423 can install coreutils, but it might have been retrieved from a binary cache.

**Comment by vcunat** [comment]
I'm certain I've seen this already, but I can't find what I did about it (probably just disabled checks temporarily). I guess it's a bug in the tests when running on some filesystems, as it was in other cases https://lists.fedoraproject.org/pipermail/scm-commits/Week-of-Mon-20140407/1223907.html.

**Comment by dwe11er** [comment]
It's failing on **btrfs** too. Disabling checks do the job.

**Comment by vcunat** [comment]
A fix is in staging, only disabling the dd/sparse test instead of all.
