### ISSUE TITLE
Cannot bind port in sandbox on macOS

### ISSUE THREAD

**Issue by nmattia** [NixOS/nixpkgs#63072]
## Issue description

It's not possible to bind a localhost port in the sandbox on macOS. The permissions is denied for `localhost`, `127.0.0.1` and `::1`. According to [bazel people](https://source.bazel.build/bazel/+/6b8c7ca48e9e48a9906c031346dc4a924b7ef559:src/main/java/com/google/devtools/build/lib/server/GrpcServerImpl.java;l=691) it should work with IPv6, however for me it fails as well.

Is there any known workaround?

### Steps to reproduce

``` nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.runCommand "sandbox-test" { buildInputs = [ pkgs.haskellPackages.wai-app-static ]; }
''
  warp -p 3000 --host ::1 # same with localhost, 127.0.0.1, 0.0.0.0
  touch $out
''
```

gives

```
warp: Network.Socket.bind: permission denied (Operation not permitted)
```
## Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.6.0, macOS 10.14.5`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(nicolas): `"nixpkgs-19.09pre181045.61f0936d1cd"`
 - nixpkgs: `/nix/store/4xv5p5hjlnqvkx1k73vgm3cn6xiar0wr-source`
```

**Comment by matthewbauer** [comment]
I think you also need to set __darwinAllowLocalNetworking:

https://github.com/NixOS/nix/blob/5f6840fbb49ae5b534423bd8a4360646ee93dbaf/src/libstore/build.cc#L2961

**Comment by smaret** [comment]
Out-of-curiosity: Hydra build don't seem to be affected by this issue. Aren't packages in Darwin build in sandbox mode on Hydra?

**Comment by nmattia** [comment]
> I think you also need to set __darwinAllowLocalNetworking:

Correct!
