### ISSUE TITLE
cannot compile ceph-0.92

### ISSUE THREAD

**Issue by letac** [NixOS/nixpkgs#6308]
cannot compile ceph-0.92

building librbd_replay.la
  CXXLD    librbd_replay.la
libtool: link: warning: `/nix/store/blyb4nanz9qdwgjqd0x49ghw15lnhd7v-gcc-4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/../../../../lib64/libstdc++.la' seems to be moved
libtool: link: warning: `/nix/store/blyb4nanz9qdwgjqd0x49ghw15lnhd7v-gcc-4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/../../../../lib64/libstdc++.la' seems to be moved
libtool: link: warning: `/nix/store/blyb4nanz9qdwgjqd0x49ghw15lnhd7v-gcc-4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/../../../../lib64/libstdc++.la' seems to be moved
copying selected object files to avoid basename conflicts...
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib: .libs/librbd_replay.a: No space left on device
make[3]: *** [librbd_replay.la] Error 1
make[3]: Leaving directory `/tmp/nix-build-ceph-0.92.drv-0/ceph/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/nix-build-ceph-0.92.drv-0/ceph/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/nix-build-ceph-0.92.drv-0/ceph/src'
make: *** [all-recursive] Error 1
builder for `/nix/store/fh8iwak3pw6fkflaclsj4yyw189n6gnx-ceph-0.92.drv' failed with exit code 2

**Comment by wkennington** [comment]
You ran out of space in /tmp.

**Comment by letac** [comment]
Sorry :(
