### ISSUE TITLE
libreoffice-fresh: doesn't build on unstable

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#63110]
## Issue description

As the title says. Been like that for a week or so.

On unstable as of 2019-06-14

Cc: @pbogdan @7c6f434c

**Comment by 7c6f434c** [comment]
https://hydra.nixos.org/build/94400462

Immediate problem: `#include <mysql.h>` — file not found

Probable cause: `mariadb` update moved `mysql.h` to `mysql/mysql.h`. I guess there are various standard ways to get this back into the include path…

Unsure why this doesn't affect the Still version.

But I am unlikely to rebuild LibreOffice today.

**Comment by peterhoeg** [comment]
>   But I am unlikely to rebuild LibreOffice today.

Ahh, your laptop can't finish building LO in a day either - thought it was just mine... ;-)

**Comment by 7c6f434c** [comment]
>Ahh, your laptop can't finish building LO in a day either - thought it was just mine... ;-)

It can do it faster than one day if everything goes perfectly, but I don't want to do it today anyway…

**Comment by vcunat** [comment]
>  I guess there are various standard ways to get this back into the include path

I'd recommend the `pkg-config` command.

**Comment by peterhoeg** [comment]
>   I'd recommend the pkg-config command.

It's already a buildInput.

**Comment by jokogr** [comment]
@peterhoeg libreoffice-fresh is now properly being built on my machines, please close this if it's the same case for you now.

**Comment by vcunat** [comment]
It also builds [on Hydra](https://hydra.nixos.org/build/94891639), so rather reopen in case it of further problems.
