### ISSUE TITLE
gcc8 should be the default compiler

### ISSUE THREAD

**Issue by tobim** [NixOS/nixpkgs#63126]
## Issue description
#53760 was merged into staging, but somehow got dropped.

It would be helpful if the process with the `staging` and `staging-next` branches was documented better. In case it already is documented, that should be more discoverable.
Maybe the [manual section](https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch) could be extended a little?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by vcunat** [comment]
**staging-next**: Things get merged to staging (basically always), and staging-next is there to make things smoother when getting the stuff to master.  Some more details were described [in an RFC](https://github.com/NixOS/rfcs/pull/26), but so far it's been mostly just two people actively taking part in this, so there hasn't been need for much coordination.

**Comment by vcunat** [comment]
That PR was not really merged (in current state of history, at least); I don't know what's happened there.  In any case it's a relatively intrusive change, so it needs stabilizing on a separate branch with separate Hydra jobset before getting merged to staging.

**Comment by tobim** [comment]
Thanks, that clears things up.
Maybe a little seo for NixOS/rfcs would help.

> That PR was not really merged (in current state of history, at least)

That is mostly what i'm wondering about, and the description in the rfc doesn't help either. I just want to know why it was removed, so a "revert"-commit would have helped. It may well be that the occasional force-push lessens the burden of maintenance, and I can't blame anyone for that though.
