### ISSUE TITLE
gnome3 settings doesn't open anymore

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#63123]
## Issue description

It crashes with:
```
Jun 14 14:54:01 t490s .gnome-control-[32688]: Settings schema 'org.gnome.mutter.wayland.keybindings' is not installed

```

### Steps to reproduce

Open the Keyboard settings option through the search bar.  Gnome control center won't start up.
Any subsequent starts will also crash.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.39, NixOS, 19.03pre-git (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172880.49dc8087a20"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by arianvp** [comment]
This _seems_ to be the same issue as https://github.com/NixOS/nixpkgs/issues/19590  but that is supposed to be fixed.

**Comment by jtojnar** [comment]
That is similar issue but this would not be fixed by that. We need to add mutter to `buildInputs` as well.

**Comment by jtojnar** [comment]
Hmm, looks like it was already [reported](https://github.com/NixOS/nixpkgs/issues/19590#issuecomment-401621180) in the thread and I [suggested the fix](https://github.com/NixOS/nixpkgs/issues/63123#issuecomment-401629772) but for some reason I forgot to include it in the PR.

**Comment by arianvp** [comment]
Any idea how I unbrick this in 19.03 ? I can't open gnome control center at all anymore since I triggered this. reboots don't seem to help

**Comment by jtojnar** [comment]
Either try to backport this, or open a different section of settings (from Shell or command line `gnome-control-center wifi`).

**Comment by arianvp** [comment]
Recompiling the world now for backport. hope it works :) PR incoming if it does

**Comment by pmarreck** [comment]
Is this related?

```
bash> gnome-control-center
10:25:11.6788                  Gtk[3268830]: WARNING: Theme parser error: gtk.css:5626:3-9: No property named "height"
10:25:11.7598 cc-firmware-security-panel[3268830]: WARNING: system bus not available: GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of active connections for UID 1000 has been reached
**
cc-object-storage:ERROR:../shell/cc-object-storage.c:167:cc_object_storage_add_object: assertion failed: (G_IS_OBJECT (object))
Bail out! cc-object-storage:ERROR:../shell/cc-object-storage.c:167:cc_object_storage_add_object: assertion failed: (G_IS_OBJECT (object))
Aborted (core dumped)
```

**Comment by jtojnar** [comment]
@pmarreck No. The error looks nothing like the reported in the OP. Please do not post to ancient issues that were already resolved.
