### ISSUE TITLE
Enabling `services.restya-board` results in type error for `phpfpm.poolConfigs`

### ISSUE THREAD

**Issue by Slabity** [NixOS/nixpkgs#63128]
## Issue description
```
error: The option value `services.phpfpm.poolConfigs.restya-board' in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/web-apps/restya-board.nix' is not of type `strings concatenated with "\n"'.
```

### Steps to reproduce
Set `services.restya-board.enable = true;` in a NixOS configuration.

## Technical details
It looks like #56625 changed the type of `services.phpfpm.poolConfigs.restya-board` from a string to a set, which the configuration does not see as compatible.

**Comment by Slabity** [comment]
I have opened #63339 to fix this.

**Comment by Ekleog** [comment]
Looks like #63339 has been merged, so I assume this is fixed.
