### ISSUE TITLE
Parallel building of sqlite does not necessarily build

### ISSUE THREAD

**Issue by praetorg** [NixOS/nixpkgs#63157]
## Issue description

commit 93982349c8ed4ddc88e62cb970ac6fdd331ee766 unbuildable on my machine. sqlite3.h cannot be found (race?). Zen architecture, 6c 12t. I reverted to previous commit and it built without issue.

### Steps to reproduce

Build sqlite on zen architecture. I can't test whether zen+ or further works.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.0, NixOS, 19.09.git.318355d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre180355.64248ab967d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
It's disabled in 2a3488a (currently in staging-next branch, soon to get in master).

_This wouldn't reproduce for me on a few tries with 16-threaded Ryzen, but that doesn't really need to mean anything._

**Comment by angristan** [comment]
Is this in master? I still get:

```
builder for '/nix/store/z3jd1h9q68ks77633gfavx0c6dwz31x0-sqlite-3.27.2+replication3.drv' failed with exit code 2
```

So I can't update my system :smile:

**Comment by vcunat** [comment]
It is.  BTW, when you click a commit on GitHub, it will show from which branches it's reachable.

**Comment by angristan** [comment]
Thanks! Now how can I know the status of the nixos-unstable channel?
