### ISSUE TITLE
Zoneminder doesn't start mysql

### ISSUE THREAD

**Issue by JohnAZoidberg** [NixOS/nixpkgs#63152]
## Issue description
Zoneminder needs mysql to work at all but the service config doesn't start it.

I would either add
```
  services.mysql = {
    enable = true;
    package = pkgs.mysql;
  };
```

to the zoneminder service or tell people to start mysql themselves in the documentation.

I thought something was broken because I expect a service to start all its integral dependencies.

cc @peterhoeg @amazari 

### Steps to reproduce
```
  services.zoneminder = {
    enable = true;
    database = {
      createLocally = true;
    };
  };
```

Can't connect to database as shown at https://localhost:8095.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.5, NixOS, 19.09.git.98e3b90 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/store/y337wsnm6rkkcbhhljs0asc97s79m209-source`

**Comment by peterhoeg** [comment]
When I used ZM, it was with the DB on a different host - I think it's fairly safe to assume that not all components will be running on the same host.

**Comment by JohnAZoidberg** [comment]
> or tell people to start mysql themselves in the documentation

But if I say "createLocally" it is running on the same host and is adding to the config on my current host.

**Comment by peterhoeg** [comment]
Yes, you are absolutely right. PR?

**Comment by aanderse** [comment]
This is what I typically do:
```
 	    services.mysql = mkIf cfg.database.createLocally {
		      enable = true;
		      package = mkDefault pkgs.mariadb;
		      ensureDatabases = [ cfg.database.name ];
		      ensureUsers = [
		        { name = cfg.database.user;
		          ensurePermissions = { "${cfg.database.name}.*" = "ALL PRIVILEGES"; };
		        }
		      ];
		    };
```

**Comment by peterhoeg** [comment]
>   This is what I typically do:

Looks good - PR? ;-)

**Comment by aanderse** [comment]
Tomorrow. :sleeping:

**Comment by aanderse** [comment]
@peterhoeg I noticed another issue while I was in there. From https://nixos.org/nixos/options.html#services.mysql.initialdatabases
> List of database names and their initial schemas that should be used to create databases on the first startup of MySQL. The schema attribute is optional: If not specified, an empty database is created.

Please see mentioned PR for fixes.
