### ISSUE TITLE
64-bit wine prefix creation fails to copy 32-bit libraries due to wrapper

### ISSUE THREAD

**Issue by joakim1999** [NixOS/nixpkgs#63170]
Referencing issue #60260 point 5. I have encountered issues with wine due to this on several occasions. The most severe is that when you create a 64-bit wine prefix with the package wineWowPackages.full it will create a prefix with ONLY 64-bit dlls. The syswow64 folder is completely empty. This may cause alot of issues and needs to be dealt with.

If you want to see this yourself I have made a nix-shell command that reproduces and logs only 64-bit dlls being copied and the error where wine can't be loaded as an ELF executable:
`nix-shell -p wineWowPackages.full --run "WINEPREFIX=$HOME/.problematicwine WINEDEBUG=+wineboot,+setupapi wineboot 2>&1 | grep -e fakedlls -e ELF -A 5 -B 5"
`

_Originally posted by @joakim1999 in https://github.com/NixOS/nixpkgs/issues/60260#issuecomment-502386680_

**Comment by joakim1999** [comment]
It seems that gstreamerSupport is the only thing that makes wine needed to be wrapped. Installing wineWowPackages.base is a workaround for this issue.

**Comment by ambrop72** [comment]
I have an old patch for this that involves setting WINELOADER, I'll make a PR.

**Comment by ambrop72** [comment]
Opened #63817 which fixes this.
