### ISSUE TITLE
Could an interrupted nixos-rebuild fail to release locks, preventing future rebuilds?

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#63183]
## Issue description

I ran `nixos-rebuild switch --upgrade` and it seemingly hung for hours at "created 16760 symlinks in user environment", late in the rebuild process, until I interrupted it with Control-C. I then tried to run it again, and it hung much earlier in the process, with the message "waiting for locks or build slots...", just after printing a list of the derivations that would be built. I interrupted and re-ran it again, and I get the same result: seemingly hanging at "waiting for locks or build slots...".

Is it plausible that my interrupting the first invocation of `nixos-rebuild` caused it to exit without releasing necessary locks, thereby preventing future rebuilds from succeeding? If so, how could I fix the locks in question so that I can rebuild?

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.33-hardened, NixOS, 19.09pre182256.168d1031af4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre182743.7815c86c104"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
It seems `nixos-rebuild` was quit, but the build that was started by the daemon was not. Maybe restarting the daemon is sufficient.

**Comment by 8573** [comment]
What's the proper way to restart the daemon? Just `systemctl restart`?

**Comment by 8573** [comment]
I don't know whether it was safe, but `systemctl restart`ing the daemon seemed to work. I don't recall having had this problem again.

**Comment by samueldr** [comment]
(Triaging)

Closing, there's not much actionable here.

The underlying "problem" was that a given build for a given output was still running, despite the process asking the daemon for the build having been killed. The observation that the build was "hanging" comes from Nix not being able to attach to the log of a currently running build.

Unless there was an unrelated bug to this, and a build was actually stuck, restarting only led to some builds needing to be started from scratch again.

And yes, restarting the daemon that way is the correct way.
