### ISSUE TITLE
bundler: hash mismatch of source

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#6326]
When activating the gitlab service and rebuilding:

```
    services.gitlab = { 
      enable = true;
      databasePassword = "removed-for-issue-report";
    }; 
```

```
[zed@nixos-workstation:~]$ sudo nix-channel --update
[zed@nixos-workstation:~]$ sudo nixos-rebuild switch --upgrade --verbose
```

Fails with:

```
trying https://rubygems.org/downloads/mysql2-0.3.16.gem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    131      0  0:00:01  0:00:01 --:--:--   131Receiving objects:  77% (84150/109285), 16.73 MiB | 494.00 KiB/s   
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0scanning for references inside ‘/nix/store/p65pkq14sdjb6vq7clpwyv3qqj7x9718-bundler-a2343c9’
output path ‘/nix/store/p65pkq14sdjb6vq7clpwyv3qqj7x9718-bundler-a2343c9’ should have r:sha256 hash ‘1l4r55n1wzr817l225l6pm97li1mxg9icd8s51cpfihh91nkdz68’, instead has ‘0l9ghs6xg0pv3ssik807jcvai3f0w83cskx7ymq6kr8f1h8lqbp0’
building path(s) ‘/nix/store/34n6wbchzi8fvskxarsj8wd979j902zk-mysql2-pre-install’
cannot build derivation ‘/nix/store/l248881kizq0wm296syb0g0ck0rpfppg-ruby-2.1.3-p0-bundler-HEAD.drv’: 1 dependencies couldn't be built
```

## System specs

```
[zed@nixos-workstation:~]$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
[zed@nixos-workstation:~]$ uname -a
Linux nixos-workstation 3.14.29 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
```

## Misc

For convenience here is the link to the latest commit to ruby-bundler: https://github.com/NixOS/nixpkgs/commit/7d8b2f0d60caea47b26692c94f86af70cec5bd20#diff-7cde46455d84d468d1a1b9c57fc96287

I does not seem like that commit introduced the problem. The hash was changed from `1f0isjrn4rwak3q6sbs6v6gqhwln32gv2dbd98r902nkg9i7y5i0` to `1l4r55n1wzr817l225l6pm97li1mxg9icd8s51cpfihh91nkdz68`, but the actual output on my machine was `0l9ghs6xg0pv3ssik807jcvai3f0w83cskx7ymq6kr8f1h8lqbp0`.

cc @cstrahan 

I can provide more information on request. I'm still pretty new to NixOS so I'm not sure what kind of information is relevant for creating issues.

**Comment by rzetterberg** [comment]
An update on this issue, I just reproduced the bug on my machine. *This time the output hash was different* from the first time I tried:

```
output path ‘/nix/store/p65pkq14sdjb6vq7clpwyv3qqj7x9718-bundler-a2343c9’ should have r:sha256 hash ‘1l4r55n1wzr817l225l6pm97li1mxg9icd8s51cpfihh91nkdz68’, instead has ‘1fywz0m3bb0fmcikhqbw9iaw67k29srwi8dllq6ni1cbm1xfyj46’
building path(s) ‘/nix/store/04h4awa2x6v697kfpdzbbzkr3q2r45ga-gon-5.0.1.gem’
cannot build derivation ‘/nix/store/l248881kizq0wm296syb0g0ck0rpfppg-ruby-2.1.3-p0-bundler-HEAD.drv’: 1 dependencies couldn't be built
```

**Comment by cstrahan** [comment]
@rzetterberg Are you on Linux or Darwin?

**Comment by cstrahan** [comment]
@rzetterberg Do you have chroot builds enabled? (`nix.useChroot = true;` in `/etc/nixos/configuration.nix`)

I forget just how impure non-chroot builds are... but a hunch is that custom git hooks could be polluting the checkout. (I think that `$HOME` is set either way, so I sorta doubt this hunch of mine.)

**Comment by rzetterberg** [comment]
@cstrahan I have not set `useChroot`, so it's using the default value. Should I set it to `true` and try again?

**Comment by vcunat** [comment]
Chrooting is irrelevant, as AFAIK fixed-output derivations are never chrooted, and they have network access, etc. Better discuss this just on #6409, as there are some more relevant discussions about leaveDotGit.

**Comment by rzetterberg** [comment]
After c00d36f6c1189a612b27a613f20af4f9b8993c79 this is problem was resolved for me. Can I close this issue? @vcunat

**Comment by vcunat** [comment]
That probably wasn't commit affecting this. Anyway, if it works now...

**Comment by anderspapitto** [comment]
I'm seeing this same issue today, on the latest unstable

**Comment by vcunat** [comment]
That's what `fetchgit` with `leaveDotGit` currently does: #8567.
