### ISSUE TITLE
warning: Option `virtualisation.qemu.program' has no description

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#63299]
## Issue description

I get lots of warnings while evaluating nixos/release-combined.nix on nixos-unstable a1dd419c1ff:
```
trace: warning: Option `virtualisation.qemu.program' has no description.
```

### Steps to reproduce

nix-instantiate nixos/release-combined.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-51-generic, Ubuntu, 18.04.2 LTS (Bionic Beaver)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/home/local/ck/code/nixpkgs`

**Comment by rnhmjoj** [comment]
```
  # This option is a dummy that if used in conjunction with
  # modules/virtualisation/qemu-vm.nix gets merged with the same option defined
  # there and only is declared here because some modules use
  # test-instrumentation.nix but not qemu-vm.nix.
  #
  # One particular example are the boot tests where we want instrumentation
  # within the images but not other stuff like setting up 9p filesystems.
  options.virtualisation.qemu.program = mkOption { type = types.path; };
```
This must the source of the warning:  the original option has been removed (aad5d1f9a7b933442c646f1f1d69b5d9df0ffbcf) so now only the dummy option is left and has no description. I don't see any other occurance of `qemu.program` so I guess it's safe to remove.

**Comment by rnhmjoj** [comment]
@edolstra Is this correct?
