### ISSUE TITLE
Incorrect information in `nix-channel --help`

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#6330]
Hi,
in `nix-channel --help`, the quick overview of the options, on the top, mentions (incorrectly) that the option `--remove` has to be used with an `url`.

In the complete explanation of the options, however, it correctly mentions that `--remove` has to be used with the `name` of the channel (like nixpkgs).

**Comment by edolstra** [comment]
This was fixed a few weeks ago, see NixOS/Nix@c23d67920ec1d96b930106b256e37b75e6151a19.
