### ISSUE TITLE
[Package request]: WriteFreely

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#63335]
## Issue description

We should package [WriteFreely](https://writefreely.org/).

It is a federated blogging engine and written in Golang.

**Comment by teodorlu** [comment]
The [AUR package][1] may be of help.

[1]: https://aur.archlinux.org/packages/writefreely/

**Comment by matthiasbeyer** [comment]
Waiting on https://github.com/adisbladis/vgo2nix/issues/23

**Comment by tokudan** [comment]
I've managed to get a running binary with version 0.11.2 on https://codeberg.org/tokudan/nur/src/branch/master/pkgs/writefreely/default.nix

**Comment by tokudan** [comment]
my nur repo contains a working version now, but it's still kind of ugly, as it builds the go binary and then imports the assets from their pre-built binaries.

**Comment by davidak** [comment]
a

**Comment by dali99** [comment]
b
