### ISSUE TITLE
error: all build users are currently in use; consider creating additional users and adding them to the ‘nixbld’ group

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#6341]
This error message is very bad. 
```error: all build users are currently in use; consider creating additional users and adding them to the ‘nixbld’ group```

It should list which configured build users exist (with a count too) it then should display what those are doing, and finally it should output the code required to add a nixbld group. 

In this particular case, I think it's a bug... because no builds are in progress in the first place. But really such error messages ... an "error path" of a program should still generate proof that it cannot do something and as such it cannot just create existential output. Computation is constructive, so ... output that. 

So, I now have a broken version of Nix on my laptop (with some wrong instructions on a wiki), and a broken version of NixOS on my server (no idea on what can possibly have caused that). Good going guys! 

This even happens after a reboot and running `nixos-rebuild switch` as the first command. WAT. 

Ok, so we here even have a counter-example that whatever `nixos-rebuild switch` is saying is complete bullshit.  
```
for u in {1..10}; do ps -U  nixbld$u; done
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
```

So, can you please fix what you release?

**Comment by wwat** [comment]
I fixed this for my situation by doing the simplest thing possible (adding more build users). I now have 100, but this still remains a bug; if you have every user add random hacks to make stuff work, you don't have an OS, you have a kludge. Long term this will create a segregation between those who added all the random hacks to make it workable and those who didn't. While this situation also exists for tons of other operating systems, that doesn't mean that it needs to be this way.

**Comment by wmertens** [comment]
@wwat You're free to not use NixOS if you don't like it, however you're
more likely to see fixes to problems if they are reported in a courteous
and productive manner. We all like to help and you're getting it for free,
no reason for the tone of entitlement in your communications.

In this case, it would be nice to know more about the system, I suppose you
told nix to run e.g. 16 build jobs where there are only 10 build users? And
what is wrong with Nix on your laptop? Different problem right?

Indeed, adapting the error message with more information might be good,
that could be a nice PR :-)

**Comment by wwat** [comment]
@wmertens My time is not free. 

And, it's probably the case that indeed I told nix to run more build jobs than that there are build users, but that just shows a design flaw in the semantics. 

If the semantics of that variable would change to be a *maximum* of the number of jobs running, then this failure condition wouldn't exist in the first place. There could be a warning explaining why it is limited to N jobs while the maximum is configure to be M > N jobs. 

The thing with nix on my laptop is documented in another Issue. Should be easy to find.

**Comment by wmertens** [comment]
@wwat Indeed your time is not free, but you choose to spend it on trying Nix and notifying the community of issues. Likewise, I choose to spend it answering you :grin:. Therefore, a way of reporting issues that results in maximum efficiency for all parties involved is optimal, and that way probably does not include being grumpy about things.

You're right, the semantics you propose would indeed be better. I opened #6357, would that work for you?

**Comment by edolstra** [comment]
Dupe of #5637.
