### ISSUE TITLE
hardware.acpilight wants to be installed as root

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#63467]
## Issue description
on current nixos-unstable a1dd419c1ffacea87eba066a2bb332e03cb68f66, 
`hardware.acpilight.enable = true;` triggers an error , the Makefile wants to be run as root.

I can't fix it right now hence the report.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by JohnAZoidberg** [comment]
Was fixed by #63670.

**Comment by teto** [comment]
thanks !
