### ISSUE TITLE
Aerc puts store references into the default config

### ISSUE THREAD

**Issue by tadeokondrak** [NixOS/nixpkgs#63499]
## Issue description

`aerc` has custom filters, and the default behaviour on first launch is to put the data directory in the ~/.config/aerc/aerc.conf file, like so:

```
...
[filters]
subject,~^\[PATCH=/nix/store/kvgcaxjq8z2va3i7dplwrxrvyrv5dxfi-aerc-0.1.1/share/aerc/filters/hldiff.py
text/html=/nix/store/kvgcaxjq8z2va3i7dplwrxrvyrv5dxfi-aerc-0.1.1/share/aerc/filters/html
text/*=/nix/store/kvgcaxjq8z2va3i7dplwrxrvyrv5dxfi-aerc-0.1.1/share/aerc/filters/plaintext.py
```

These paths will break on an update to aerc.

I'm the maintainer, but I'm not exactly sure what the best way to fix this with Nix is.

**Comment by worldofpeace** [comment]
It's part of the build
https://git.sr.ht/~sircmpwn/aerc/tree/master/config/aerc.conf.in#L77

A level of function and structure would probably need to be changed to remove this.

**Comment by arnarg** [comment]
Currently, `$out/share/aerc/filters` is put in `PATH` for aerc so in the case for text/html you can simply do `text/html=html`: https://github.com/NixOS/nixpkgs/blob/8d1510abfb592339e13ce8f6db6f29c1f8b72924/pkgs/applications/networking/mailreaders/aerc/default.nix#L41-L42

But as for `subject,~^\[PATCH` and `text/*` the default config now uses `awk -f /nix/store/.../share/aerc/filters/[hldiff,plaintext]` respecively which will need a different solution.
