### ISSUE TITLE
PayPal Adaptive Hoops is going to fail tests

### ISSUE THREAD

**Issue by seagreen** [NixOS/nixpkgs#6350]
@peti I just added remote integration tests to [paypal-adaptive-hoops](https://github.com/fanjam/paypal-adaptive-hoops), so you probably want to switch it from running all tests to just `cabal test local`. I would have done it for you, but I couldn't find it in nixpkgs/master and wasn't sure where else to look.

**Comment by peti** [comment]
Fixed in 580dad5; thank you very much for the heads up!

**Comment by peti** [comment]
Nevermind, I made the small change myself. Pushed in 1fc7f01.

**Comment by peti** [comment]
Oops, disregard my last comment, please, I accidentally posted that to the wrong PR.

**Comment by seagreen** [comment]
No problem! Let me know if you need any changes on my end, and feel free to close this.
