### ISSUE TITLE
ghc debug RTS should not be stripped of debug symbols

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#63511]
## Issue description

`libHSrts_debug-ghc8.6.4.so` is meant for debugging and hence is built with `-g3`. It seems
all the debug information is stripped when the library is installed as `dwarfdump` reports that
there are no debug symbols. THe installation process shouldn't strip any of the debug rts builds.

### Steps to reproduce

```
> ghc --print-libdir
/nix/store/kdvixnzqq44qnvcryxrispasfl7b335k-ghc-8.6.4/lib/ghc-8.6.4
> dwarfdump /nix/store/kdvixnzqq44qnvcryxrispasfl7b335k-ghc-8.6.4/lib/ghc-8.6.4/rts/libHSrts_debug-ghc8.6.4.so
```

Output should contain debugging symbols, but there is nothing.

**Comment by mpickering** [comment]
I built a version of GHC with the following config:

https://gist.github.com/mpickering/b5dbe374393fb316f616b2111963f2fb

and the debug RTS has the correct dwarf information.

**Comment by angerman** [comment]
`dontStrip` will leave `ghc`, `ghc-pkg` and `hsc2hs` referencing the build compiler.

**Comment by angerman** [comment]
@mpickering how about we change
`dontStrip = true` to `stripDebugList = [ "lib/${name}/bin" ];`?
That is only stripping the executables?
