### ISSUE TITLE
Get qt512.x86_64-darwin (and qt513.x86_64-darwin)

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#63528]
## Issue description

We are currently stuck on qt 5.11 on darwin/macOS. To get things consistent, this should update to qt 5.12 (or even 5.13) soon.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by veprbl** [comment]
If qt512 builds on darwin we  should change the default version:
https://github.com/NixOS/nixpkgs/blob/0ce30f8c67db15ae312f1e27f9228468bbdbb528/pkgs/top-level/all-packages.nix#L13284-L13286

**Comment by veprbl** [comment]
`qt512.qtbase` is currently broken: https://hydra.nixos.org/job/nixpkgs/trunk/qt512.qtbase.x86_64-darwin/all

**Comment by veprbl** [comment]
Fixed in #72999
