### ISSUE TITLE
darwin.adv_cmds.x86_64-darwin

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#63546]
## Issue description

This was broken recently:

https://hydra.nixos.org/job/nixpkgs/trunk/darwin.adv_cmds.x86_64-darwin

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Qyriad** [comment]
Thankfully, this is no longer broken 🎉 https://hydra.nixos.org/build/256994412
