### ISSUE TITLE
Conflict between IDEA packages

### ISSUE THREAD

**Issue by smola** [NixOS/nixpkgs#6354]
IDEA packages (pycharm, idea-ultimate, idea-community, etc) have a conflict on fsnotifier/fsnotifier64.

idea-community and idea-ultimate also conflict because both create "idea" wrapper.

pycharm-professional and pycharm-community have the same conflict.

**Comment by edwtjo** [comment]
Fixed via 17e6dd2da347f3b8ef44e9693068c5f8c3788579
