### ISSUE TITLE
Package Request: intel/compute-runtime

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [NixOS/nixpkgs#63568]
## Issue description

compute-runtime, also known as Intel NEO, is an updated OpenCL driver for Broadwell+ Intel processors. It is available here: https://github.com/intel/compute-runtime

Beignet and intel-ocl has been deprecated for all newer Intel processors (Broadwell+) in favor of compute-runtime. For legacy hardware, beignet is required.

For newer hardware, this package is a requirement for OpenCL functionality. For instance, Ice Lake processors will not be supported on beignet, but are fully supported by Intel NEO.

See the ebuild for https://packages.gentoo.org/packages/dev-libs/intel-neo and the PKGBUILD for https://www.archlinux.org/packages/community/x86_64/intel-compute-runtime/

**Comment by gloaming** [comment]
I've been working on this for a couple of weeks now. I'll land a WIP soon but it's not building yet

**Comment by OpenSourceAnarchist** [comment]
That's great! It seems to update once a week... quite a fast pace. Hopefully once it builds it won't be difficult to maintain, just a simple version bump and hash update :)

**Comment by gloaming** [comment]
Having packaged it, I don't share your optimism :P

**Comment by gloaming** [comment]
Draft PR at https://github.com/NixOS/nixpkgs/pull/63705

**Comment by gloaming** [comment]
Package was added in #63705
