### ISSUE TITLE
Update Singularity to 3.2.x or 3.3.0-rc1

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#63571]
## Issue description

Singularity is currently at 3.0.1 in nixpkgs; as advised upstream (https://github.com/sylabs/singularity/issues/3764#issuecomment-503908802), 3.0.x has many bugs and 3.1.x has severe security issues. The upstream issue also points out an issue I had, which *may* be fixed by updating.

**Comment by markuskowa** [comment]
Resolved with this PR: https://github.com/NixOS/nixpkgs/pull/63409
