### ISSUE TITLE
libvisual for darwin blocks nixpkgs-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#63617]
## Issue description

The `libvisual` build is failing, and seems to block the nixpkgs-unstable channel.
https://hydra.nixos.org/build/95015893

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

cc @NixOS/darwin-maintainers

**Comment by matthewbauer** [comment]
libvisual was added to gstreamer in https://github.com/NixOS/nixpkgs/commit/1a6e572529595d146a259fa433785ebb3215d8d2#diff-18b2b0b3820cecdee57ce115e1afbc70

**Comment by matthewbauer** [comment]
This fix has only revealed another issue:

https://hydra.nixos.org/build/95173721/nixlog/2/tail

If anyone has time to look into that, it would be greatly appreciated!
