### ISSUE TITLE
buildbot: hash mismatch

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#63611]
## Issue description

It seems like some of the buildbot python modules were updated silently, without a change in the version number.

```
hash mismatch in fixed-output derivation '/nix/store/klp31bajf9ngfg6clxprpcnva98lyg62-buildbot-console-view-2.3.1.tar.gz':
  wanted: sha256:1yh8xij3wizz0f88chjpdijm7i35ql87g84ph3f76sqyr6aj6ckw
  got:    sha256:1y523hadw3398jwfpmi2f4g0s6dp9y191qzycrsbvbj147dp0qra

hash mismatch in fixed-output derivation '/nix/store/053sp3s749ldnl37g9xgyw5v3hp94vkc-buildbot-wsgi-dashboards-2.3.1.tar.gz':
  wanted: sha256:13lr7lzi9sv0s6xrfalq0dkcys6fp7hn0787rjhnz9gc7x83aqjv
  got:    sha256:1jhvq61x0bzh03nd2ac11swdjn0ndnx3ac7x9v3m3v0pgr08rc28

hash mismatch in fixed-output derivation '/nix/store/ikgybjqcys4csd5blmx90icpq52yd3x8-buildbot-waterfall-view-2.3.1.tar.gz':
  wanted: sha256:04iihy1s9r4n5jlk57pdjy3yvp6zym2iv2bgqjhw6fy0hff5j8ys
  got:    sha256:1prfr03igcmagydvxqhrh6k6wz16vk6fwgrm143jh3xmml6f16ll
```

and possibly more

### Steps to reproduce

`nix-shell -p python3.pkgs.buildbot-full`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
pbb@onyx ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.11, NixOS, 19.09pre183392.83ba5afcc96 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre183392.83ba5afcc96, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by veprbl** [comment]
This is not seen on hydra https://hydra.nixos.org/job/nixpkgs/trunk/python37Packages.buildbot-full.x86_64-linux, the last update was back in May: f6d2df3f2ab4e7b52bc8b570ca79a1fc5cfe1435

**Comment by veprbl** [comment]
Can reproduce locally:
```
 nix-build . -A python3Packages.buildbot-plugins.wsgi-dashboards.src
these derivations will be built:
  /nix/store/mxcl16dyy1z39sxgr03kifrdaar3p9c1-buildbot-wsgi-dashboards-2.3.1.tar.gz.drv
building '/nix/store/mxcl16dyy1z39sxgr03kifrdaar3p9c1-buildbot-wsgi-dashboards-2.3.1.tar.gz.drv'...

trying https://files.pythonhosted.org/packages/source/b/buildbot-wsgi-dashboards/buildbot-wsgi-dashboards-2.3.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  577k  100  577k    0     0  2662k      0 --:--:-- --:--:-- --:--:-- 6100k
hash mismatch in fixed-output derivation '/nix/store/053sp3s749ldnl37g9xgyw5v3hp94vkc-buildbot-wsgi-dashboards-2.3.1.tar.gz':
  wanted: sha256:13lr7lzi9sv0s6xrfalq0dkcys6fp7hn0787rjhnz9gc7x83aqjv
  got:    sha256:1jhvq61x0bzh03nd2ac11swdjn0ndnx3ac7x9v3m3v0pgr08rc28
error: build of '/nix/store/mxcl16dyy1z39sxgr03kifrdaar3p9c1-buildbot-wsgi-dashboards-2.3.1.tar.gz.drv' failed
```

cc @lopsided98 @nand0p @ryansydnor

**Comment by petabyteboy** [comment]
> This is not seen on hydra https://hydra.nixos.org/job/nixpkgs/trunk/python37Packages.buildbot-full.x86_64-linux, the last update was back in May: [f6d2df3](https://github.com/NixOS/nixpkgs/commit/f6d2df3f2ab4e7b52bc8b570ca79a1fc5cfe1435)

why do you think this is not seen on hydra?
https://hydra.nixos.org/build/95015125/nixlog/2

**Comment by veprbl** [comment]
Ah, I confused grey "x" (propagated build failure) with red "x" (cancelled build). Also missed the culprit: https://github.com/NixOS/nixpkgs/commit/038794dd731409aac1a7a066ea7d1e4f09f8f9cb

**Comment by veprbl** [comment]
Fixed in 847f677b56642bdb9ae40280dab21bb72d0ecad8 and cd1bc951936d1648239d5fed19efaecebeaecdcd

**Comment by veprbl** [comment]
I hope someone can do the work needed to do a proper upgrade to 2.3.1.

@FRidh Perhaps you could add `buildbot`, `buildbot-pkg` and `buildbot-worker` to your blacklist?

**Comment by veprbl** [comment]
cc #63483

**Comment by lopsided98** [comment]
This is not [the](https://github.com/NixOS/nixpkgs/pull/39679) [first](https://github.com/NixOS/nixpkgs/pull/42899) [time](https://github.com/NixOS/nixpkgs/pull/52536) this has happened, and I [asked that the package not be automatically updated](https://github.com/NixOS/nixpkgs/pull/41894#issuecomment-401631859), but I never got any response.

I should be able to correctly update it tonight.
