### ISSUE TITLE
cool-retro-term doesn't start

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#63619]
## Issue description

```
nix-shell -p cool-retro-term --run cool-retro-term

QQmlApplicationEngine failed to load component
qrc:/main.qml:24 module "QtGraphicalEffects" is not installed

Cannot load QML interface
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.51, NixOS, 19.09pre182971.a1dd419c1ff (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(philipp): `""`
 - channels(root): `"nixos-19.09pre182971.a1dd419c1ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
AFAIK some QT stuff won't run unless installed in NixOS `systemPackages` or via `nix-env`.  We touched it just recently again: https://github.com/NixOS/nixpkgs/issues/12027#issuecomment-501236677

**Comment by pmiddend** [comment]
Ah, I see. I'll close this then.
