### ISSUE TITLE
Missing symbol for glxinfo

### ISSUE THREAD

**Issue by berdario** [NixOS/nixpkgs#6364]
It never worked on my machine... this is a bit weird, since I cannot find anyone else with the same issue by googling

```glxinfo: relocation error: /nix/store/la5imi1602jxhpds9675n2n2d0683lbq-glibc-2.20/lib/libpthread.so.0: symbol __libc_vfork, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference```

**Comment by peti** [comment]
Do you have `$LD_LIBRARY_PATH` configured?

**Comment by berdario** [comment]
It contains these 2 directories:

```/run/opengl-driver/lib /run/opengl-driver-32/lib```

**Comment by peti** [comment]
Interesting ... this looks like a problem with the opengl driver rather than glxinfo.

**Comment by berdario** [comment]
The hardware is a Dell precision M4800, lspci says:

```00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Venus XT [Radeon HD 8870M / R9 M270X]```

By default nixos seems to use the radeon driver (but I wanted to use glxinfo to verify exactly that information), but even if I rmmod it (thus relying on the i915 driver) the error is the same

**Comment by vcunat** [comment]
This seems due to some kind of glibc mismatch - when binaries depending on different glibc versions are dynamically linked together. A comment with a hint https://bugs.archlinux.org/task/42188#comment128158.

I no longer remember the linking mechanisms to see how to avoid the problem, and it might be nontrivial, as using multiple glibc versions on one system isn't too common AFAIK.

**Comment by wmertens** [comment]
(triage) @berdario I am closing this issue as it is over a year old and likely fixed by updates in the mean time.

If it is still not fixed, it looks like the fix involves not loading different glibc versions in the same binary, which will need further investigation into what is linked where.

**Comment by berdario** [comment]
I don't have that hardware anymore, so I'm unable to test. Agree that closing this might be the best if it cannot be reproduced anymore.
