### ISSUE TITLE
syncthing: remote devices lost on reboot

### ISSUE THREAD

**Issue by smithtim** [NixOS/nixpkgs#63662]
## Issue description

All remote devices that I have added to syncthing disappear when I reboot my machine.

### Steps to reproduce

Add a remote device to syncthing.  Reboot.  The remote device has disappeared from the syncthing GUI and is no longer synced.

### More information

Syncthing config is stored in `/var/lib/syncthing/config.xml`.  This file includes a list of all remote devices that have been added.  Restarting syncthing with `systemctl restart syncthing` preserves the list of remote devices, as expected.  But rebooting the machine causes them to disappear from the file.

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.44, NixOS, 19.09pre180443.4dd5c93998d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre180443.4dd5c93998d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ikervagyok** [comment]
try these options, they fixed something similar for me:

```
services.syncthing.declarative.overrideDevices = false;
services.syncthing.declarative.overrideFolders = false;
```

**Comment by smithtim** [comment]
That worked, thanks!

Maybe these options should default to `false`?  I did not even know about the accompanying options `services.syncthing.declarative.devices` and `services.syncthing.declarative.folders`, and had not set them.

**Comment by rnhmjoj** [comment]
ping @Lassulus
I think this be disabled by default or mentioned in the release changes.

**Comment by Lassulus** [comment]
yes, this was a bug, which was introduced by the declarative changes.
It should be fixed by 0a2b9719fd82fdd4dc3267da80a941777e4e4a4a though

**Comment by Lassulus** [comment]
I will close this, as this should be fixed. If this issue still remains feel free to reopen it (if you can, otherwise just message me)

**Comment by Hubro** [comment]
I'm having this exact issue. Every time I reboot, all my shared folders are lost. When I open the syncthing UI I'm greeted with a bunch of popups informing me that my remote machine wants to share folders with me.

This is my NixOS config:

```nix
syncthing = {
  enable = true;
  user = "tomas";
  dataDir = "/home/tomas/syncthing";
  configDir = "/home/tomas/.config/syncthing";
  overrideDevices = true;
  settings = {
    devices = {
      "<retracted>" = {
        id = "<retracted>";
        addresses = [ "<retracted>" ];
      };
    };
  };
};
```

Is it intentional that if I override devices I also have to override folders, or is this a bug?
