### ISSUE TITLE
mkAliasOptionModule doesn't work if the newly created option doesn't have any definitions

### ISSUE THREAD

**Issue by j-piecuch** [NixOS/nixpkgs#63693]
## Issue description

The value of an option created using `mkAliasOptionModule` throws an error when evaluated if the newly created option doesn't have any definitions, even if the target option (the one that the newly created option is an alias of) is defined.

### Steps to reproduce

test.nix:
```nix
lib:

with lib;

let

  someModule = {
    options.foo = mkOption {
      type = types.bool;
      default = true;
    };
  };

in

evalModules {
  modules =
    [ someModule
      (mkAliasOptionModule [ "bar" ] [ "foo" ])
    ];
  check = false;
}
```

Let's load it in the REPL:
```
nix-repl> :l <nixpkgs>
Added 10082 variables.

nix-repl> cfg = import ./test.nix lib

nix-repl> cfg.config.foo
true

nix-repl> cfg.config.bar
error: The option `bar' is used but not defined.
```

## Comments

Here's what I think is going on:
1. `mkAliasOptionModule` sets the `apply` attribute of the newly created option ([code](https://github.com/NixOS/nixpkgs/blob/80172aa0a6fad62d1371dee8318725573e7ac808/lib/modules.nix#L721)), so that when its value is computed, it evaluates to the value of the target option. So, in principle, evaluating `cfg.config.bar` should evaluate to **exactly** the same thing as `cfg.config.foo`.
2. This doesn't happen, because the option `bar` does not have any definitions, and the `apply` attribute of the option isn't used ([code](https://github.com/NixOS/nixpkgs/blob/80172aa0a6fad62d1371dee8318725573e7ac808/lib/modules.nix#L330)).

~~A workaround would be for `mkAliasOptionModule` to define the newly created option, but give it a very high priority number (so that its priority is very low) and a value that throws an error when evaluated.~~
The solution is to add an additional flag, `applyOptional`, that tells whether to apply the `apply` function to an optional value of the option.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.50, NixOS, 19.03.172883.1601f559e89 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(kuba): `"home-manager-19.03"`
 - channels(root): `"home-manager-19.03, nixos-19.03.172883.1601f559e89"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by nbp** [comment]
`MkAliasOptionModule` *should not* be bidirectional. The reason for that is that one option input might be valid for the renamed option but the opposite might not be true, and the original option input might break if it were to be computed with the newly added value.

This matters if some module code needs time to migrate from one option name to another.
I suggest to close this issue

**Comment by Infinisil** [comment]
@nbp So we should replace this: https://github.com/NixOS/nixpkgs/blob/aa9d7eedf255724eab6a086a8a81dfd23a805c4b/lib/modules.nix#L721

With something like
```nix
{
  apply = x: throw "Option ${showOption from} has been renamed to
    ${showOption to}, which you should reference instead.";
}
```

?

So this would forbid the *use* of the original option (in addition to it already warning when the original option is defined). I think that would make sense, though it might have some annoying consequences for third-party modules (and our own too, because it might be hard to get rid of all original option usages).

So maybe something like this instead:
```nix
{
  apply = x: lib.warn "Option ${showOption from} has been renamed to
    ${showOption to}, which you should reference instead." (use (toOf config));
}
```

This then at least suggests that there might be some problems with the config (the potential non-bidirectional equality of renamed options).

Ping @rycee @Profpatsch

**Comment by j-piecuch** [comment]
@nbp I'm not sure I get this bidirectionality thing.

I think the current intuitive effect (i.e. not what actually happens in the code) of `mkAliasOptionModule` is for two option _names_ to "point" to the same _option_ -- basically the same thing as pointer aliasing in C.
For example, assume we have `mkAliasOptionModule [ "bar" ] [ "foo" ]`. If we think of `bar` and `foo` as just option _names_ pointing to the same underlying _option_, then this means:
1. All definitions of `bar` and `foo` are pooled together when determining the final value of the underlying option.
2. Evaluating `bar` should always yield the same result as evaluating `foo`, which should yield the value of the underlying option.

What happens in the actual code doesn't directly reflect what I've just written, but I think it has the same visible effect. Here's why:

Point 1 is achieved by the following code in `doRename`:
https://github.com/NixOS/nixpkgs/blob/aa9d7eedf255724eab6a086a8a81dfd23a805c4b/lib/modules.nix#L729
This has the effect of making every definition of `bar` count as a definition of `foo`.

Point 2 is achieved by the following code in `doRename`:
https://github.com/NixOS/nixpkgs/blob/aa9d7eedf255724eab6a086a8a81dfd23a805c4b/lib/modules.nix#L721
Since `use` is `id` in the case of `mkAliasOptionModule`, evaluating `bar` should yield __exactly__ the same result as evaluating `foo`. This doesn't happen in practice because of the bug this whole issue is about, which is fixed by #66407.

**Comment by Infinisil** [comment]
I think @nbp means a scenario like this, first we have a single option `foo` of type `int`:
```nix
{
  options.foo = mkOption { type = types.int; };
}
```

Then at some point we introduce `bar` which replaces foo, but newly also allows `null`:
```nix
{
  imports = [ (mkAliasOptionModule [ "foo" ] [ "bar" ]) ];
  options.bar = mkOption { type = types.nullOr types.int; };
}
```

The code that used `foo` previously expected it to be of type `int`, but now that the value of `bar` gets mirrored to `foo`, it suddenly can be `null` as well, which it maybe can't handle.

So essentially we should disallow referring to the old option entirely, such that all modules have to switch to the non-renamed/non-aliased one instead.

**Comment by Infinisil** [comment]
Or maybe even only disallow referring to the old option if it has a different type than the new one

**Comment by j-piecuch** [comment]
These all seem like sensible things to do, but I don't think they belong in `mkAliasOptionModule`.
`mkRenamedOptionModule` already issues a warning if the old option is used, and `mkChangedOptionModule` handles the use case where the new option has a different type.
So in the end, the purpose of `mkAliasOptionModule` seems to be the creation of a literal __alias__ of another option.

**Comment by Infinisil** [comment]
Yeah that sounds reasonable, maybe we should have another function like `mkChangedOptionModule` but without it issuing a warning
