### ISSUE TITLE
Use -isystem for dependency headers

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#63712]
## Issue description

Our usage of ```-I``` instead of ```-isystem``` can lead to weird errors like in https://github.com/NixOS/nixpkgs/issues/59929. Basically, we GCC emits warnings from headers included with ```-I```, but not with those included with ```-isystem```. We probably don't want to include warnings from headers included as dependencies. This should make logs a lot easier to read. Likewise, we should always use ```-iframework``` for framework directories.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by ambrop72** [comment]
As far as I can tell, `cc-wrapper` uses `-isystem` for depencency includes and `-F` for frameworks: https://github.com/NixOS/nixpkgs/blob/c438c0e0b71c3b4be174486b0a5f60c67dd09721/pkgs/build-support/cc-wrapper/setup-hook.sh#L74

The problem in #59929 was that a dependency was being picked up using `pkg-config`, and the `.pc` file specified `-I` flags.
