### ISSUE TITLE
mariadb: duplicating binary files in client and server packages

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#63723]
## Issue description
https://github.com/NixOS/nixpkgs/commit/1db3a91bab24e2e6ec3fa78de5be8b6c938cb0c0#commitcomment-34044268
mysql_upgrade requires availability of mysqlcheck, which is in the package mariadb.client
In other operating systems they are separated - mysql_upgrade -> mariadb.server, mysqlcheck -> mariadb.client. And when the server is installed the client is automatically installed.

**Comment by gloaming** [comment]
Hmm, is there a reason _not_ to make the client a dependency of the server? The only dependencies the client has that the server doesn't are `openssl` and `zlib` which any server should have (via openssh). How much space is saved by removing the client binaries?

**Comment by gloaming** [comment]
So it seems the mysql_upgrade binary is hardcoded to expect the other binaries in the same directory:

```
$ PATH=/nix/store/58imvk1bcbamifbrblmbaiqqzn0gwxmb-mariadb-client-10.3.15/bin /nix/store/qmiz7b38a8kw2pcdpzys2kvxl4v8d8pb-mariadb-10.3.15/bin/mysql_upgrade 
FATAL ERROR: Can't execute '/nix/store/qmiz7b38a8kw2pcdpzys2kvxl4v8d8pb-mariadb-10.3.15/bin/mysqlcheck

$ cp /nix/store/qmiz7b38a8kw2pcdpzys2kvxl4v8d8pb-mariadb-10.3.15/bin/mysql_upgrade .
$ ./mysql_upgrade 
FATAL ERROR: Can't execute './mysql'

$ cp /nix/store/qmiz7b38a8kw2pcdpzys2kvxl4v8d8pb-mariadb-10.3.15/bin/mysql .
$ ./mysql_upgrade 
FATAL ERROR: Can't execute './mysqlcheck'

```

Probably the splitting works on other distros because the binaries all end up in /usr/bin anyway.

**Comment by Izorkin** [comment]
Need to build the package with server+client and only client?
Is this variant bad?
```
  environment.systemPackages = with pkgs; [
    mariadb.server mariadb.client
  ];
```

**Comment by gloaming** [comment]
I'm not sure what you mean.

Can you check to see if the project cmake allows you to configure a different install PREFIX for the client/server?

**Comment by Izorkin** [comment]
Should I change the build of MariaDB, so that one package includes files for both server and client, and the other package only includes client files?

> Can you check to see if the project cmake allows you to configure a different install PREFIX for the client/server?

I don't know how to configure this

**Comment by gloaming** [comment]
@FRidh 19.09 milestone? If this and https://github.com/NixOS/nixpkgs/issues/64132 aren't resolved by then we will have to add the client binaries back into the server package.

**Comment by Izorkin** [comment]
https://github.com/Izorkin/nixpkgs/commit/b24bce7903084272841e9e2260cc6bf044769890 - this variant optimal?

**Comment by Izorkin** [comment]
https://github.com/NixOS/nixpkgs/pull/63355 update MariaDB configuration, please check this variant.

**Comment by Izorkin** [comment]
Fixed, mariadb package includes server and client binaries.
https://github.com/NixOS/nixpkgs/pull/63355
