### ISSUE TITLE
buildRustPackage uses different compilation options for tests

### ISSUE THREAD

**Issue by nmattia** [NixOS/nixpkgs#63730]
## Issue description

https://github.com/NixOS/nixpkgs/blob/57b1f5386289dbe4be14ac8960687c12334d6dfb/pkgs/build-support/rust/default.nix#L105-L106

https://github.com/NixOS/nixpkgs/blob/57b1f5386289dbe4be14ac8960687c12334d6dfb/pkgs/build-support/rust/default.nix#L124

By defaul buildRustPackage runs
 * cargo build --release
 * cargo test
Which means that
 1. All libraries must be recompiled for the tests to run
 2. The code being tested has different compilation options

It'd be nicer to use `cargo test --${buildType}`

**Comment by Valodim** [comment]
just for the record, this is addressed in #82342

**Comment by Ma27** [comment]
Just realized that this issue is still open, but it's in fact fixed -> closing.
