### ISSUE TITLE
rtl8723de

### ISSUE THREAD

**Issue by rndd-AK** [NixOS/nixpkgs#63741]
## wifi is dead

I really apologies is this is a dumb issue. But during two weeks I've tried to set up this wifi driver https://github.com/smlinux/rtl8723de

### Steps to reproduce

here is my configuration.nix     https://github.com/rndd-AK/configs/tree/master/nixos

## Technical details

[rndd@core:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.11, NixOS, 19.09pre183392.83ba5afcc96 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre183392.83ba5afcc96"`
 - channels(rndd): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
How are you building the kernel module?

**Comment by peterhoeg** [comment]
Couple of things:

1. How are you building the kernel module? Take a look at this for reference: https://github.com/nixos/nixpkgs/blob/master/pkgs/os-specific/linux/ixgbevf/default.nix
2. ```networking.wireless.driver``` has nothing to do with the kernel module. That's the driver for ```wpa_supplicant``` which currently supports the following 3: nl80211, wext and wired

**Comment by rndd-AK** [comment]
1) Really, don't know how to build kernel modules. In other distributions it was just dkms and depmod. Well, maybe there any guide of how to build in nixos. Didn't find any.
2) Well, don't really get it. If my laptop have a wifi module, then I have to install appropriate driver (module) for my os to be able to connect through wifi. Well, how I can learn how to build modules in nixos?

**Comment by peterhoeg** [comment]
The link above shows how it is done for the ixgbevf driver. 

I suggest you do the following:

1. Check out a local version of nixpkgs
2. Create a new branch of channels/nixos-unstable
3. Add a new derivation for your driver similar to how it's done for ixgbevf
4. I'm assuming the kernel module is automatically loaded if the required hardware is present. If not, you can do the following in your config: ```boot.kernelModules = [ "rtl8723de" ];```
5. ```nixos-rebuild -I nixpkgs=path_of_your_nixpkgs_fork test```

**Comment by peterhoeg** [comment]
You got it working?

**Comment by rndd-AK** [comment]
Went to debian

**Comment by peterhoeg** [comment]
Out of curiosity - due to this issue or for other reasons?

**Comment by rndd-AK** [comment]
I use nixos on my laptop (that have an Intel wifi), and I like to use it for programming. I like the way nixpkg deals with libraries. But, when you need to do something simple like an installation of ready kernel module from github where you need to just copy paste two-three lines of commands -It becomming frustrating

**Comment by teal77** [comment]
I got rtl8723de working succesfully
https://github.com/NixOS/nixpkgs/issues/65435#issuecomment-570039807
