### ISSUE TITLE
fix haskellPackages.c2hsc tests: Cannot find executable '/usr/bin/gcc'

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#63764]
## Issue description

on nixos-unstable, all tests fail with the same error

```

  ./Data/C2Hsc.hs:76:21:
  126) sanity check processes smoke.h
       uncaught exception: ErrorCall
       Cannot find executable '/usr/bin/gcc'
       CallStack (from HasCallStack):
         error, called at ./Data/C2Hsc.hs:76:21 in c2hsc-0.7.1-3JuJhZH6Z289AkCUwvWCmG:Data.C2Hsc

  To rerun use: --match "/sanity check/processes smoke.h/"

Randomized with seed 1538989878

Finished in 0.0204 seconds
126 examples, 126 failures
Test suite test: FAIL
Test suite logged to: dist/test/c2hsc-0.7.1-test.log
0 of 1 test suites (0 of 1 test cases) passed.
note: keeping build directory '/tmp/nix-build-c2hsc-0.7.1.drv-1'
builder for '/nix/store/48scdj7crhfipy3v20cw9jc3qc9fxlrd-c2hsc-0.7.1.drv' failed with exit code 1
cannot build derivation '/nix/store/n5ybp0q7fxkpvaq1jvxcrb2aliifd69q-ghc-8.6.5-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/n5ybp0q7fxkpvaq1jvxcrb2aliifd69q-ghc-8.6.5-with-packages.drv' failed
```

### Steps to reproduce
`nix build haskellPackages.c2hsc`

## Technical details
 current unstable

**Comment by gloaming** [comment]
Offending line: https://github.com/jwiegley/c2hsc/blob/acae60b64b828407211e09e82c30306fe156e4f9/Data/C2Hsc.hs#L51

Quick bodge:
```
preBuild = ''
  substituteInPlace Data/C2Hsc.hs --replace '"/usr/bin/gcc"' '"gcc"'
'';
```

I have a possible fix for the upstream package: https://github.com/gloaming/c2hsc/commit/0173aff4d970a8cb3c8a8c64486815c1540eb4fe

But to run without `gcc` already on the path, it also needs a wrapper:
```
buildTools = [ pkgs.makeWrapper ];
postInstall = ''
  wrapProgram $out/bin/c2hsc --prefix PATH : ${pkgs.gcc}/bin
'';
```
But `haskell-packages.nix` says that's it's auto-generated. Where are these instructions supposed to be placed?

**Comment by teto** [comment]
overrides for generated packages should go into pkgs/development/haskell-modules/configuration-common.nix
c2hsc looks for gcc via findExecutable and I believe this function is used by other packages too. so putting gcc in path could be a solution ?

**Comment by gloaming** [comment]
The problem is the current c2hsc looks for `/usr/bin/gcc` only, nowhere else. So that needs to be substituted out or fixed upstream before anything will work.

**Comment by gloaming** [comment]
Upstream fix merged. I wonder if we should still provide a wrapper, though, so that it will work even if the user doesn't have `gcc` installed in their profile?

**Comment by teto** [comment]
this should probably be fine now. ty
