### ISSUE TITLE
On unstable channel GRUB failed with ZFS root/boot

### ISSUE THREAD

**Issue by caadar** [NixOS/nixpkgs#63765]
## Issue description

GRUB can't boot system on ZFS root/boot partitions when on unstable channel.

Boot info on console:

```GRUB loading…
Welcome to GRUB!

Attempting to decript master key…
Enter passphrase for hd0,gpt3 (.....):
Slot 0 opened
error: symbol 'grub_file_filters' not found.
Entering rescue mode…
grub rescue>
```

### Steps to reproduce
`````
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
$ sudo nixos-rebuild switch --update
...
updating GRUB menu...
...
Installing for i386-pc platform.
You have a memory leak (not released memory pool):
[0xebb8b0] dtree
Internal error: Unreleased memory pool(s) found.
...
Installation finished. No error reported.
Warning: the new NixOS configuration has an init that is incompatible
with the current configuration.
The new configuration won't take effect until you reboot the system.
warning: error(s) occurred while switching to the new configuration
`````

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
`````
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/sy0n5vqn2l16hb3w0yjxkixbfdmsvabk-bash-interactive-4.4-p23-dev
copying path '/nix/store/sy0n5vqn2l16hb3w0yjxkixbfdmsvabk-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.47, NixOS, 19.03.172783.a0b7a7913c4 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(scr): `""`
 - channels(root): `"nixos-19.09pre183392.83ba5afcc96"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
`````

Some relevant settings:
```
boot.loader.grub.enable = true;
boot.loader.grub.version = 2;
boot.loader.grub.enableCryptodisk = true;
boot.loader.grub.copyKernels = true;
boot.supportedFilesystems = [ "zfs" ];
boot.zfs.enableUnstable = false;
boot.zfs.forceImportAll = false;
boot.zfs.forceImportRoot = false;
```
EFI not used.

ZFS version: stable or unstable
GRUB: 2.02 (works), 2.04-rc1 (seems doesn't work)

**Comment by Radvendii** [comment]
I'm having a similar issue but for me there's no option to boot the updated system, so I run `sudo nixos-rebuild switch --upgrade` and it gives me the warning about incompatible init, and then I reboot and it's still on the old build.

I also tried running just `sudo nixos rebuild boot --upgarde` and then rebooting, and the same thing happened.

**Comment by Radvendii** [comment]
For me this problem was caused by a hack I did ages ago to get nixos booting after some other upgrade.

I had commented out the following lines from `hardware-configuration.nix`, and I just had to uncomment them (and delete the contents of the directory `/boot/`, which had been created)

```
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E8FE-BC22";
      fsType = "vfat";
    };
```

**Comment by caadar** [comment]
From Debian bug [#931896](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931896#10) discussion:

> This means that your GRUB installation is misconfigured: in particular,
it means that the GRUB core image that your firmware is configured to
boot from is not the one that grub-install is writing to on upgrade,
which means that the core image and the loadable modules in /boot/grub/
are incompatible and you get this failure mode.

> This is not a bug in the new version of GRUB; any upgrade at all that
changed the interface between the core image and modules (which is not a
stable interface) would have exposed this.  Rather, it's a bug in the
way your system was installed or possibly in the way it has been
maintained since then...

**Comment by caadar** [comment]
Seems same as #61718.

**Comment by caadar** [comment]
Solved by setting device with boot directory as ```boot.loader.grub.device```.
