### ISSUE TITLE
gildas: Gtk-WARNING **: cannot open display

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#63779]
## Issue description

On Darwin, `gildas-20190601_b` gives the following error at run time:
```
Gtk-WARNING **: 20:55:03.666: cannot open display
``` 
and then it hangs. The bug occurred for the first time around June, 19th. Older generations work fine. `gildas` version hasn't changed meanwhile, so I suspect a problem with one of it dependency (`gtk2-x11`?).

### Steps to reproduce

```
% nix-shell -p gildas --run astro
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.6.0, macOS 10.14.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(smaret): `"nixpkgs-19.03pre170546.0f43790d2ce"`
 - nixpkgs: `/nix/store/yhgaaym5g59wf4b0dh453n9yw4i1xwhw-master.tar.gz`

**Comment by smaret** [comment]
Any idea @matthewbauer? Can this be caused by the recent update of stdenv on Darwin?

**Comment by matthewbauer** [comment]
do you have xquartz installed?

**Comment by smaret** [comment]
> do you have xquartz installed?

Yes I do, and it works fine for other X11 apps. Also as said in the issue description, when I switch nix-env generations back to June , 19th, I don't get the error anymore. So I don't think this is related to XQuartz.

**Comment by matthewbauer** [comment]
I can't think of anything recently that would have effected this. Those were merged into master in early april. Could you try to track down when this was first introduced?

**Comment by smaret** [comment]
I'm running a `git bisect`, but it takes a while because there was several mass rebuild since the beginning of January.

**Comment by smaret** [comment]
Here what I get (all of these commits were skipped by `git bissect` because one of the dependencies could not be built):

> The first bad commit could be any of:
84e34cbde2ea8dfcb2e853a61c5e7c5b39413525
ee86a325dd067df0da827c2044e8f6e39ffbfed6
2812b5ce392370ca671a1f371904a12aa3c6db13
7508490770ba490ad767d230241822129da70672
dcd42d35dcace8a6d6ef5ae181c9495a7bc27d1d
9077623324d9366041bb6628be1a5cffb7bc815d
0f93834c5e6e1e7489ab4be55c38cb1d4b9d325f
dc423728091b9b4a9b16e6b54e13721ab16e5d18
81f390d2e3f0b297e7b50c779b49babcd6a1fa7e
c782fe1edc1b775e75655ec9b032f8b3b057c076
d436ab07182ffee2b3447df892828137fc3767e8
024a383d64036dab02157927369ca680427aa61d
c057ef62ad8c32f069af820ba32d846b5d9e06c0
bc71b6eaf6ff9451cbbaa3e62aa200845d12f4e3
1b7b1dbe2f88a3c8f0c5416d4e43de10977915cc
8ef8fd06bd03a8bbbf39805c0b7d967b3b8790fa
aceffe6f0c0c9fdadbb85b86cb0896b8ab7fcf4e
d600da70457a8ca8d9543eb48b73e7c5eae1656f
a32cd7d84a7c832574ef0f09862e41bf84709baf
b4fa23991b46310979d667e1253eed2544f18f89
137a63f9f63cb95473b1e67b04fd73c634bfb14d
4743ad7392152d3745dee552aebe8a6b67e189a1
1f03f6fc43a6f71b8204adf6cd02fb3685261add
eb7c14fad15e4762a0f54a83decc964b3ae77409
8c7e588362e708ade5e782c09dbdf84d06ab4254
c0ccf42c69845b10c1acd98e93f2d427d429250a
2a0f85d882621c28b7bcfc8cbd0c9069c60bbd09
5b0db07ee1c86376755a7e91fc4d1cfda2a7cff6
7c53ac01845a63f27ff5281c1b4c344eb406512a
5ccacc251426d1c5bf295487fb01f266b871c8b7
6d99421a11f9eb854e18bae3534a49196cc862d0
26f728ed89caf9795a6e67296ae68360755b6afc
49eac6aebdf22e0280c4cf9c5d9db764e63ca7a6
f5e7e1c24b020e786053e852bb35d8df7ae0a097
01390dcef27cdb8207edd2a22d5aa7d511e0a862
77e1967dcd7cbb764de7617acf2da2dce77ee3ab
87a69edf672be2d09fd742cc8c036ec697299e7f
1012c31526ed55afee4d0ec01b0cf543c77e1ff7
be2d9a5a8e8417fed2a21fbbd1cf6a76d2db2b67
b837e4afee6f81351ae33efd7466b3f8d21dfadc
9b65cb17190986f3cb13b6dd8fb5af61e7a705f7
27a3c5d7f2a1dbe8da2546ba4c9a700edc0ba138
558c4ce462586459a0a9326dd5e4d17e70dcb1c9
872100cf4129758917dfef9c0ebe4d8e9fa1ce28
c70260eea70ef3e6dce9928e4b68fef5523fcc30
989d7f8d2c044950466b9df59dd12fd26a151d1b
dbd1a4481fca373b4a13d052c7c45075d8d5f143
ff3049f67de99c90f4ca10609eb21e5c6eea84a6
476c580605c071cbadbd8715984b7da08f58d303
682bc7ce1c66bdb461d73f0bdba636b44f11dff5
cd76032c1bb4e15a298155202e579ec00c3ddf02
daf8b6897180e8a54b7b1f71da8fa0fcebe5764f
642c9a7e743a080a6eac168fed755c7af251c6ad
7c3d7521f0d3e1a2562b0b341be52639248811bb
9096648a2e6aa21e3c6a6ee5b114daed58701d5e
922589053724885437b2c75257ab36383f95c378
2703d285bfe6e5ae2eb8cc4a1716791433d9ab85
4a1e51f957b57f781fbdd2e40ca48ebac886e974
4acc4348476faf5f9c93429e561c3d99024239d9
93cac33f95e5cb0312db366c48f6c163abcd0b0a
eaaea97d8702134f53078f5f74a0e9867090d86d
f6297de3bc930c8e7573e8ad90975f636f796c75
1671eeda2d5c14f44052d8938130f8959d1f0b42
208fbe20ad05098d42457cb81b1cbddd67bd4509
3313c5e3f55675efe1b8f2d2213976735933d3e3
3b215985ee054cb12db3a62c1759d9d6ded0378a
50ba595d2c131f7a52b8cf3942326a01b34dd9ad
7d1ac249dfce996a8287eddbe24812d650e0dd6c
7f91e5fb037298c0cfd3f2899461e891cfae77b8
81d3bd60a46d0f3eba92ca2659b4cbef50745368
98bdeb049df2adc49c2b8b9650da1349103c0916
c0af744b18a588aa8d5789cc9cdac074b7f007c7
c83b9bb6aaceeece94dab4df0c5040fcf847fc16
d41c43e4a9e8968b0078dc2279b40b34d5bd9498

**Comment by smaret** [comment]
I've updated `nixpkgs` today and `gildas` now work fine. Something must have changed with one of the dependency but I don't know what.

Closing this.

**Comment by matthewbauer** [comment]
very weird! let me know if it shows up again. it's possible there was some gtk bug that has been since fixed
