### ISSUE TITLE
KiCad 5 Simulator Fails to run

### ISSUE THREAD

**Issue by letres** [NixOS/nixpkgs#63798]
## Issue description
The simulator is unable to run and when attempted it has a segmentation fault.
(ngspice is installed)

### Steps to reproduce
Start kicad from terminal
Open Eeschema under tools select simulate.
It opens a kicad error window that says 
"libngspice.so.0.0.0: cannot open shared 
object file: No such file or directory"
Click okay then open Eeschema which has a Warning window open that says
"Missing ngspice shared library"
After clicking Ok it closes and the terminal only has Segmentation Fault showing after the call.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.6, NixOS, 19.03.172801.1a27474d474 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172801.1a27474d474"`
 - channels(emmer): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
@berce

**Comment by tokudan** [comment]
Did a bit of testing. If the wrapper adjusts the LD_LIBRARY_PATH to include libngspice, the SPICE GUI opens, but running a simulation immediately crashes kicad again:
`wrapProgram "$out/bin/kicad" "''${gappsWrapperArgs[@]}" --prefix LD_LIBRARY_PATH : "${libngspice}/lib"
There is nothing obvious I can find in the strace output, so I'm not sure what exactly is breaking there.

**Comment by SnVIZQ** [comment]
I'm using this overlay to get ngspice simulator working in kicad:

[kicad.nix.txt](https://github.com/NixOS/nixpkgs/files/3705901/kicad.nix.txt)

Which requires following patch to kicad:

[kicad-ngspice.patch.txt](https://github.com/NixOS/nixpkgs/files/3705906/kicad-ngspice.patch.txt)

and using `kicad-stable` in `environment.systemPackages` list in my `configuration.nix`.

I am not sure if following two are required, but adding them for completeness (they enable open-mp):

[ngspice.nix.txt](https://github.com/NixOS/nixpkgs/files/3705923/ngspice.nix.txt)
[libngspice.nix.txt](https://github.com/NixOS/nixpkgs/files/3705925/libngspice.nix.txt)

With these overlays and  the patch to kicad, I'm able to use ngspice simulator in kicad (as well as seeing 3D models, but that might have been resolved in original kicad/default.nix file already). Maybe it's not ideal solution but it seems working fine.

Hope that helps.

**Comment by tokudan** [comment]
I've got it working in #69584 now, only thing left is an aarch64 build issue.

**Comment by gebner** [comment]
This should work now after #74259, please reopen if there are still problems with the simulator.
