### ISSUE TITLE
sddm doesn't start at boot when I enable plymouth

### ISSUE THREAD

**Issue by allowthere** [NixOS/nixpkgs#63818]
## Issue description

When I enable plymouth in my configuration.nix (`plymouth = {enable = true;theme = "breeze";};`), sddm fails to start.

## Technical details

journalctl says:

EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

...

(EE) Screen 0 deleted because of no matching config section.

...
(EE) Screen 0 deleted because of no matching config section.

...

(EE) modeset(0): drmSetMaster failed: Invalid argument

Fatal server error:

(EE) AddScreen/ScreenInit failed for driver 0

I disabled plymouth and sddm starts again at boot.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.03.172979.8634c3b6199 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172979.8634c3b6199"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SuperSamus** [comment]
I use both Plymouth and SDDM and have no such issue.
This can be closed.
