### ISSUE TITLE
python.pkgs.pytest-mock bulid fails

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#63826]
## Issue description

Caused by the pytest update in 1a7ffb4140b8fff7a0a23d261be17533fa97d978. Upstream issue filed at https://github.com/pytest-dev/pytest-mock/issues/149.

**Comment by teto** [comment]
Adding this from my overlay solves it (but still waiting for a release):

```
        pytest-mock = pythonsuper.pytest-mock.overrideAttrs(oa: {
          src = super.fetchFromGitHub {
            rev = "189cc599d3bfbe91a17c93211c04237b6c5849b1";
            owner = "pytest-dev";
            repo = "pytest-mock";
            sha256 = "1p33zz11kk5qfwyaqgzwil5p555n29qrcb770rn3pa7cy8ncnxqk";
          };
          SETUPTOOLS_SCM_PRETEND_VERSION="1.10.5";
        });

```

**Comment by timokau** [comment]
Couldn't we just backport that [one commit](https://github.com/pytest-dev/pytest-mock/pull/151/commits/970e4b1f8cfd6bd750b4c8240efad378cbf049c2) for now instead of bumping the whole package?

**Comment by teto** [comment]
I was mentioning this as a quickfifx, backporting the commit seems more sensible. Let's ask the maintainer @nand0p
