### ISSUE TITLE
Steam: unable to input umlauts and €

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#63832]
## Issue description

I can't type öäüß€ in Steam (for example in store search box or chat).

Maybe related:

```
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
```
### Steps to reproduce

My localization settings: https://github.com/davidak/nixos-config/blob/master/services/localization.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.03.172979.8634c3b6199 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172979.8634c3b6199"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cizra** [comment]
Steam apps somehow drop locales. The `LOCALE_ARCHIVE` env variable is not set in games launched by Steam. `Half-Life: Source` runs but complains, `Torchlight 2` doesn't even start because of this.

**Comment by baracoder** [comment]
Thank you for the information. As a workaround, I was able to start Torchlight 2 setting Launch options for the game to
```
LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive %command%
```

**Comment by davidak** [comment]
The issues i reported are fixed in NixOS 19.09.1451.b2448a9fde1 with latest Steam.

![Screenshot from 2019-12-06 15-55-35](https://user-images.githubusercontent.com/91113/70332551-1fe17980-1842-11ea-9391-9c0a49bd3db7.png)

![Screenshot from 2019-12-06 15-59-52](https://user-images.githubusercontent.com/91113/70332556-24a62d80-1842-11ea-96a5-f4cb6c045c16.png)

I remember that Half Life (1) showed a warning that locales are missing at the start. That is also gone.

@cizra do you still have issues with locales?

**Comment by cizra** [comment]
I'm not running NixOS at moment, so I cannot test, unfortunately.

**Comment by davidak** [comment]
Then i close it for now. Just open a new issue when there are still problems.
