### ISSUE TITLE
can't build clippy for rust development

### ISSUE THREAD

**Issue by thedavidmeister** [NixOS/nixpkgs#63852]
## Issue description

want to be able to build clippy so that it is available in nix-shell

currently i have cargo in the nix shell by using the mozilla overlay

### Steps to reproduce

i tried following the steps here: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md

i forked the clippy repo to be able to build a Cargo.lock but natively nix can't build using a specific nightly or configure rust flags (or can it with the overlay?)

i tried carnix over the same Cargo.lock but it only prefetched everything then spat out an empty `Cargo.nix` file

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by ln-nl** [comment]
Hmm, clippy should go with mozilla overlay, if a particular version has it (you can check [there](https://rust-lang.github.io/rustup-components-history/))

```which cargo-clippy
/nix/store/q1qh2rdww92abl63hblsgcm2nqd0y6x0-rust-1.35.0-2019-05-20-3c235d560/bin/cargo-clippy
```

Not sure whats wrong with `carnix`,

**Comment by thedavidmeister** [comment]
yeah i found that thanks!
