### ISSUE TITLE
Make nix package easier to override

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#63857]
Currently you (apparently) can't easily override `nix` with your own patched version by overriding `src` to your git fork.

That is because that needs setting `fromGit = true` as an argument to the `common` function in https://github.com/NixOS/nixpkgs/blob/5f78fa399da1cbca3591930d58e2c2a68c8c8a44/pkgs/tools/package-management/nix/default.nix#L11

and you can't get at that because `common` is in a `let` block and not exported.

---

Would anyone mind if that was rewritten, so that we can use normal `.override`s for things like `fromGit`?

Also, please let me know if this is already possible and I just haven't figured out how.

**Comment by gloaming** [comment]
But `fromGit` is an argument to the package function just the same as `src`:

https://github.com/NixOS/nixpkgs/blob/5f78fa399da1cbca3591930d58e2c2a68c8c8a44/pkgs/tools/package-management/nix/default.nix#L22

And this package is what is exported from the `nix/default.nix`.

```
[craig@nixos:~]$ nix repl
Welcome to Nix version 2.2.2. Type :? for help.

nix-repl> :l <nixpkgs>
Added 10082 variables.

nix-repl> nix
«derivation /nix/store/zhbk6vplc30ilng4fxh67ci01gadasl1-nix-2.2.2.drv»

nix-repl> nix.override { fromGit = true; }   
«derivation /nix/store/fn4lvdydc2v11flqfkqqbqxxbdnxvsfk-nix-2.2.2.drv»
```

:)

**Comment by nh2** [comment]
I must be doing something wrong in my overlay then, will double-check ...

**Comment by matthiasbeyer** [comment]
Is this resolved?

**Comment by nh2** [comment]
Hmm, this seems to be due to my nixpkgs version.

In current 19.03 I get

```
nix-repl> nix.override { fromGit = true; }   
«derivation /nix/store/fgwdylhwqar9k3gb2mals714rfkhqsr1-nix-2.2.2.drv»
```

In my older nixpkgs version based on 18.03, I get

```
nix-repl> nix.override { fromGit = true; }    
error: anonymous function at /home/niklas/.../nixpkgs/pkgs/tools/package-management/nix/default.nix:1:1 called with unexpected argument 'fromGit', at /home/niklas/.../nixpkgs/lib/customisation.nix:129:65
```

Did anything change there?

They look pretty similar.

**Comment by matthiasbeyer** [comment]
Well no, in 18.03 the argument was not there apparently.

**Comment by nh2** [comment]
It's here in 18.03 though:

https://github.com/NixOS/nixpkgs/blob/28a84599249cf5994b4c563fdc057bfa0ec755f2/pkgs/tools/package-management/nix/default.nix#L15

But I think I found the commit that fixed it:

https://github.com/NixOS/nixpkgs/commit/bfc72142e0b05ce103988baf4d8cff602c132a4d

Closing.
