### ISSUE TITLE
mopidy-gmusic: failed with exit code 25

### ISSUE THREAD

**Issue by codedmart** [NixOS/nixpkgs#63861]
## Issue description
Can't install mopidy-gmusic seeing a collision message and fails with exit code 25
```
collision between `/nix/store/aksq045jzpi0yyxhlcmya3myzki28rsd-python2.7-backports.ssl_match_hostname-3.7.0.1/lib/python2.7/site-packages/backports/__init__.pyc' and 
builder for '/nix/store/byfhf2k3l2z9c8ql147kppmz2f78kfs5-mopidy-with-extensions-2.2.2.drv' failed with exit code 25
```

### Steps to reproduce
`/etc/nixos/configuration.nix`
```
services.mopidy = {
  enable = true;
  extensionPackages = [ pkgs.mopidy-gmusic ];
};
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.03.173000.1c6bdbc766e (Koi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173000.1c6bdbc766e"`
 - channels(codedmart): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by codedmart** [comment]
What more should I provide to help move this along?

**Comment by cstich** [comment]
I have the same issue, but for what it's worth 
```
nix-shell --pure -p mopidy mopidy-mopify mopidy-spotify --run mopidy
```
works.

**Comment by leo60228** [comment]
Mopidy-GMusic 3.0.0 doesn't work due to API changes, and 4.0.0 isn't on PyPi. We should either remove it or update it to master.

**Comment by cstich** [comment]
> Mopidy-GMusic 3.0.0 doesn't work due to API changes, and 4.0.0 isn't on PyPi. We should either remove it or update it to master.

Maybe I am missing something but how can `nix-shell --pure -p mopidy mopidy-mopify mopidy-gmusic --run mopidy` work?

**Comment by leo60228** [comment]
@cstich I was referring to changes in the Google Play Music API, not the Mopidy API.

**Comment by Redcroft** [comment]
This issue is still occuring on 19.09, any workaround rather than running in nix-shell?

**Comment by NickHu** [comment]
I think this can be closed now that Google Music is dead
