### ISSUE TITLE
Add luna

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#63895]
Luna is a functional programming language and graphical tool for data analysis. I would expect it to become sort of popular amongst Haskellish and Nixish people, therefore it sounds like a good idea to add it to `nixpkgs`.

There is an issue to make Luna more nix-friendly: https://github.com/luna/luna-manager/issues/127

But it seems like we need some more hands to make it work.

**Comment by turion** [comment]
There is some effort by @mulderr and me:

https://github.com/turion/luna-platform
https://github.com/mulderr/luna-platform

But this is far from complete and help is direly needed.

**Comment by matthew-piziak** [comment]
Still important to me. Luna has been renamed "Enso".

**Comment by turion** [comment]
Enso is developed in Scala, which is harder to integrate in nix. I'm not spending any more effort in that direction.

**Comment by matthew-piziak** [comment]
@turion Fair enough!

**Comment by turion** [comment]
I'd rather close, since enso is pretty much a rewrite, it seems. Feel free to open a new issue to package enso.
