### ISSUE TITLE
Drop way-cooler?

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#63914]
## Issue description

Could we drop way-cooler package? I've tested it and it doesn't look like a finished product at this moment. Any users that will be against that? I'm for to re-add it once they make a new release.

Currently way-cooler is in a mass rewrite state. New version will use wlroots library instead of deprecated wlc, but what's more it will not be compatible with old version (in behaviour and Lua libraries). See https://github.com/way-cooler/way-cooler#development

cc @primeos @yrashk @miltador 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by vcunat** [comment]
An alternative could be to mark it with `meta.broken = true;`, it's relatively easy to access in case someone really wants it.  (But I don't know the particular situation of _this_ package.)

**Comment by gloaming** [comment]
I think `meta.broken` is a better idea; we don't want to prevent any diehard users(?) from upgrading their system.

Is it actually broken, or do you just mean it's not very good?

**Comment by matthiasbeyer** [comment]
From the readme of the project:

```
Master is not usable for production. There are old versions of Way Cooler that do work, however:

    They use an old framework, wlc, and thus are very limited and buggy.
    Was not designed to emulate Awesome, but instead has i3 tiling and its own (very incomplete) Lua libraries.
```

I'd vote for marking it as broken.
