### ISSUE TITLE
macOS Catalina 10.15 Beta

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#63918]
So, I have just updated to macOS 10.15, and my `/nix` directory is gone. Thanks, apple!

I’ll keep you posted :/.

**Comment by kirelagin** [comment]
Found it in `/Users/Shared/Relocated Items/Security/`

**Comment by kirelagin** [comment]
So the `/Users/Shared/Relocated Items` directory seems to contain files that the installer wasn’t sure what to do with. For me it has two directories: `Quarantine.lpdf` and `Security`. The first one appears to be a “localised pdf” bundle, and it contains PDFs in multiple languages with the following text:

> During your last Upgrade or Migration, some content could not be automatically moved into its expected location. When possible, we've preserved those documents in this folder.
>
> The following conditions occurred:
During the most recent Migration, we had some difficulty transferring certain files. Below is the list of files which encountered problems. Please review this list to see if any of these paths or documents are important to you, and if so, consider transferring them with AirDrop or a USB Stick.
>
> * Some files from "/private/var/empty" could not be transferred

The `Security` directory has the entire `/nix` in it, together with a couple of other files from `/usr` and `/System`.

**Comment by kirelagin** [comment]
New disk layout:

```
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *251.0 GB   disk0
   1:                        EFI EFI                     314.6 MB   disk0s1
   2:                 Apple_APFS Container disk1         250.0 GB   disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +250.0 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD - Data     221.4 GB   disk1s1
   2:                APFS Volume Preboot                 22.9 MB    disk1s2
   3:                APFS Volume Recovery                527.0 MB   disk1s3
   4:                APFS Volume VM                      1.1 GB     disk1s4
   5:                APFS Volume Macintosh HD            10.6 GB    disk1s5
```
```
› mount
/dev/disk1s5 on / (apfs, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s1 on /System/Volumes/Data (apfs, local, journaled, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, journaled, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
```

There is some sort of overlayfs going on, i. e. the data in the actual root partition and in the data partition is merged. But I am not sure how exactly it works. Some directories seem to be “bind-mounted”, some are merged, but only somehow selectively (?).

```
› ls /usr/share
<...>                        snmp                        <...>
› ls /System/Volumes/Data/usr/share
snmp
› sudo touch /System/Volumes/Data/usr/share/hi
› ls /usr/share/hi
ls: /usr/share/hi: No such file or directory
› sudo rm /System/Volumes/Data/usr/share/hi
```
```
› ls /System/Volumes/Data/usr/local
Caskroom      Cellar        Frameworks    Homebrew      bin           etc           include       lib           lmm           opt           remotedesktop sbin          share         var
› sudo touch /usr/local/hi
› ls /System/Volumes/Data/usr/local/hi
/System/Volumes/Data/usr/local/hi
› sudo rm /System/Volumes/Data/usr/local/hi
```

**Comment by kirelagin** [comment]
Oh, ok, after a reboot `/` is now mounted read-only. Had to remount it rw to remove all the trash I left there.

In any case, having `/nix` on the root partition is not longer an option because a) Read-only by default; b) Not enough space anyway.

**Comment by kirelagin** [comment]
Aha, the relevant keywords seem to be “Volume Group” (see `man diskutil`) and “Firmlink”.
(This issue is turning into a non-Nix-specific macOS digging thing...)

**Comment by kirelagin** [comment]
AHA!

```
› cat /usr/share/firmlinks
/AppleInternal	AppleInternal
/Applications	Applications
/Library	Library
/System/Library/Caches	System/Library/Caches
/System/Library/Assets	System/Library/Assets
/System/Library/PreinstalledAssets	System/Library/PreinstalledAssets
/System/Library/AssetsV2	System/Library/AssetsV2
/System/Library/PreinstalledAssetsV2	System/Library/PreinstalledAssetsV2
/System/Library/CoreServices/CoreTypes.bundle/Contents/Library	System/Library/CoreServices/CoreTypes.bundle/Contents/Library
/System/Library/Speech	System/Library/Speech
/Users	Users
/Volumes	Volumes
/cores	cores
/home	home
/mnt	mnt
/opt	opt
/private	private
/sw	sw
/usr/local	usr/local
/usr/libexec/cups	usr/libexec/cups
/usr/share/snmp	usr/share/snmp
```

**Comment by kirelagin** [comment]
>Question: Can firmlinks be created by endusers, or are they reserved to the system? If they can be created by the enduser, what commands are used to create them?
>
>Answer: No, firmlinks can't be created by endusers. This is reserved currently to the system. There will be synthetic firmlinks coming, which can be used as mount points for network resources.

([from here](https://forums.developer.apple.com/message/363444))

Ok, cool, we are fucked 😒.

**Comment by kirelagin** [comment]
Time to move `/nix` to `/opt/nix`? 🤷‍♂

**Comment by kirelagin** [comment]
(cc @LnL7 @copumpkin @dhess @matthewbauer) (sorry if I forgot someone who might be interested)

**Comment by dhess** [comment]
See https://github.com/NixOS/nix/issues/2925

**Comment by kirelagin** [comment]
Ah, thanks, then, I guess, I’ll close this one.

**Comment by kirelagin** [comment]
So, for future reference, the steps to recover after an upgrade are:

1. `mv "/Users/Shared/Relocated Items/Security/nix" /opt/`
2. `sudo mount -o rw /` (this throws errors but works)
3. `ln -s /opt/nix /nix`

**Comment by callahad** [comment]
⚠️ The steps above do not work ⚠️ 

From [this comment](https://github.com/NixOS/nix/issues/2925#issuecomment-522482497) on #2925, we need to avoid symlinking `/nix`: "Some builds apparently resolve symlinks, so impure paths end up in build results."

Current instructions are provided in that thread.
