### ISSUE TITLE
Steam + Bumblebee?

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#63940]
## Issue description

Seems to be different to #32550

Game fails to start with error
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  22
  Current serial number in output stream:  23
```

### Steps to reproduce

1.
```nix
hardware.bumblebee.enable = true;
environment.systemPackages = with pkgs; [ steam ];
environment.variables = {
  # to fix "X Error of failed request: BadMatch (invalid parameter attributes)"
  __GLVND_DISALLOW_PATCHING = "1";
};
```
2. Start Steam from console

3. Set launch options of the game to `primusrun %command%` https://support.steampowered.com/kb_article.php?ref=6316-GJKC-7437

4. Run the game

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.09.git.20b993e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(gnidorah): `""`
 - channels(root): `"nixos-19.09pre172038.5d3fd3674a6"`
 - nixpkgs: `/home/gnidorah/tmp/nixpkgs`

**Comment by gnidorah** [comment]
cc @abbradar

**Comment by abbradar** [comment]
Unfortunately I don't have Optimus hardware nowadays, so I can't test it. Can you run `steam-run bash` and try various combinations of `optirun`, `primusrun` etc with `glxgears`?

**Comment by gnidorah** [comment]
@abbradar Thanks! Maybe someone else could help.
```
$ nix run nixpkgs.steam-run-native nixpkgs.glxinfo -c steam-run bash
$ optirun glxgears
```
works
```
$ __GLVND_DISALLOW_PATCHING=1 primusrun glxgears
```
only works when __GLVND_DISALLOW_PATCHING=1 is set, otherwise `X Error of failed request: BadMatch (invalid parameter attributes)` error is shown (which is not error seen in Steam #48795)

The error in description is only shown under Steam

**Comment by abbradar** [comment]
@gnidorah Have you tried optirun with Steam? BTW I pushed https://github.com/NixOS/nixpkgs/commit/b1fc8e24a29376af830b7caf4a0838f4d9fe902f.

**Comment by gnidorah** [comment]
@abbradar Same issue as with primusrun
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  22
  Current serial number in output stream:  23

```

**Comment by gnidorah** [comment]
Closing. There is no much need for bumblebee, since nvidia finally implemented prime solution and there is a working PR https://github.com/NixOS/nixpkgs/pull/66601
