### ISSUE TITLE
fetchgit needs a 'deepClone' parameter

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#6395]
The fetchgit expression has an option for "deep cloning" the full history, but there seems to be no way to actually *set* that option. Am I missing something?

**Comment by bjornfor** [comment]
I think you are right. I wrote https://github.com/NixOS/nixpkgs/pull/5252, but later decided it's probably better to have explicit deepClone argument (because it's less intrusive). Just like you suggest.
