### ISSUE TITLE
Brave Browser and Pulse Audio : No Sound

### ISSUE THREAD

**Issue by BadDecisionsAlex** [NixOS/nixpkgs#63966]
## Issue description

This happens from time to time with various Pulse Audio stuff but it's particularly annoying for a browser :(
I usually just have to open up Firefox or Chrome if I want to do anything with sound.

As an added note I am experiencing the issue using `home-manager`, but I have the exact same problem when installing with `nix-env`, `nix-shell`, and through `configuration.nix`, so I don't think the issue is `home-manager` related (although it is certainly possible).

Pulse's `pavucontrol` does not detect Brave at all, but I do sometimes get audio through my headphones or speakers randomly (regardless of what is set as the default sink). I think it is probably falling back to Alsa or something as the audio controller.

### Steps to reproduce

```nix
# /etc/nixos/configuration.nix
{ config, pkgs, ... }:
{
    # Various config stuff ...

    hardware.pulseaudio.enable = true;
    
    # Various config stuff ...
}
```

```nix
# ~/.config/nixpkgs/home.nix
{ config, pkgs, ... }:
{
    # Various config stuff ...

    home.packages = with pkgs; [
        # Various packages ...

        brave       

        # Various packages ....
    ];
    
    # Various config stuff ...
}
```

## Technical details

```sh
λ nix-shell -p nix-info --run "nix-info -m"                                                                             
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.52, NixOS, 19.09pre183392.83ba5afcc96 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(camus): `"home-manager, nextbookit, nixos-mio"`
 - channels(root): `"home-manager, nixos-19.09pre183392.83ba5afcc96, nixos-hardware, nixos-stable-18.09.2574.a7e559a5504"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by gloaming** [comment]
Not surprising, our copy of Brave is built with `alsaLib` instead of `libpulseaudio`.
Chromium is built with PA, so presumably Brave supports it also.

**Comment by gloaming** [comment]
@BadDecisionsAlex you might find you have some other problem with your PulseAudio though. When I tried Brave with only `libAlsa` I found that sound worked fine.

**Comment by BadDecisionsAlex** [comment]
@worldofpeace
Y'all are the best.
