### ISSUE TITLE
Static linking haskell binaries?

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#6399]
With:

```nix
haskellPackages.override {
  extension = self: super: {
    cabal = super.cabal.override {
      enableSharedExecutables = false;
      enableSharedExecutables = false;
    };
  };
}
```
, building the `optparse-applicative` package fails with:

> Loading package transformers-compat-0.3.3 ... <command line>: can't load .so/.DLL for: libHStransformers-compat-0.3.3.so (libHStransformers-compat-0.3.3.so: cannot open shared object file: No such file or directory)

How am I meant to do this?

@peti

**Comment by peti** [comment]
This question refers to the old package set, right? I am a little confused, because `optparse-applicative` doesn't define an executable to begin with, so I'm not sure what you're trying to achieve?

**Comment by shlevy** [comment]
Yes, the old package set. The real use case is a proprietary binary depending on optparse-applicative, but I need that to build first :smile:

**Comment by peti** [comment]
I can re-produce the problem, but I'm not sure what's causing it. If I had to guess, then my money would be on https://github.com/NixOS/nixpkgs/commit/db4cb021c024b65c08a3791edf2d4c613e8d44d8#diff-398fce2e9f7a8a55bb55ff6988d6aa08L21, which removed the `DYNAMIC_BY_DEFAULT = NO` setting from the compiler configuration. 

@joelteon, just out of curiosity, is there any particular reason why you've made that change? Is it required to build on Darwin?

**Comment by joelteon** [comment]
Right, the compiler can't build with that setting on Darwin. I didn't know there was any use for it, but I'll investigate later today if necessary

**Comment by peti** [comment]
@joelteon, I'm running test builds right now to determine whether the setting actually makes a difference. For the moment, I'm just guessing ...

**Comment by joelteon** [comment]
@peti So you can add that back in, I just ran the build again and there was no failure

**Comment by peti** [comment]
b8bf8e5 (in `staging`) fixes this issue.

**Comment by shlevy** [comment]
Thanks!

**Comment by k0001** [comment]
I'm seeing the same issue with `ghc-7.10.3`. It looks like the `DYNAMIC_BY_DEFAULT = no` flag is missing in `pkgs/development/compilers/ghc/7.10.3.nix`. Should it be there?

**Comment by peti** [comment]
I am a little confused. The package set that had this problem doesn't exist in any version of Nixpkgs that has GHC 7.10.3. That code has been deleted well over a year ago.
