### ISSUE TITLE
D-Bus connection created before QCoreApplication

### ISSUE THREAD

**Issue by geerds** [NixOS/nixpkgs#6405]
I just noticed this message in my `~/.xsession-errors` while starting different KDE applications:

```
$ konsole
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
```

Good news is that applications seems to work without problems. Does anyone have the same warn message?

**Comment by wizeman** [comment]
I also have those warning messages.

I am experiencing a problem, in that `konsole` forgets my custom keyboard shortcuts when I close it. But I don't know if it has anything to do with that message.
I have also experienced some crashes in the past, but again, I don't know if it's related.

**Comment by vcunat** [comment]
I'm getting these for a very long time. This suggests it's a harmless Qt-4.8 problem: https://bugs.kde.org/show_bug.cgi?id=297020

**Comment by ttuegel** [comment]
I am closing this because it's a harmless message related to an issue upstream won't fix.

**Comment by bsfc1685** [comment]
I fixed it under openSUSE by uninstalling QT5 wich in turn uninstalls KDE and Plasma5. Reinstalling the whole made my konsole work
