### ISSUE TITLE
Clean up GitHub releases and tags

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#64077]
We link to GitHub releases on https://nixos.org/nixpkgs/download.html now. (last section)

So i would like to have a clean list of just official releases. (to improve user experience and be more professional)

So i suggest to remove tags and GitHub releases like these:

- backups/* (https://github.com/NixOS/nixpkgs/releases/tag/backups%2Fstdenv-updates%4034093)
- program@version https://github.com/NixOS/nixpkgs/releases/tag/black%402016-05-13
- *-beta (?) (https://github.com/NixOS/nixpkgs/releases/tag/15.09-beta)
- https://github.com/NixOS/nixpkgs/releases/tag/last-glibc-2.13

The question is, are these still useful for anyone or where they just temporary tags?

@kamilchm @domenkozar

**Comment by matthiasbeyer** [comment]
I want to not that removing published tags from a repository is considered bad. Also, because people still have push access to this repo (AFAIK), they might re-appear anyways!

**Comment by worldofpeace** [comment]
I think `*-beta` tags are important milestones in the release process 
* https://nixos.org/nixos/manual/index.html#at-beta-release-time

So we shouldn't remove those at least.

**Comment by Atemu** [comment]
I don't think this is relevant anymore.

**Comment by davidak** [comment]
the repo and github project is still a mess. nothing seem to have been cleaned up. so the decision is to keep it that way?

**Comment by Atemu** [comment]
We don't link the releases on the home page anymore. If you think this is still important, feel free to re-open.

I'm just going through stale issues that have seen no progress or interest for 3 years.
