### ISSUE TITLE
Login issues with KDM

### ISSUE THREAD

**Issue by geerds** [NixOS/nixpkgs#6407]
It happens from time to time that KDM asks me a second time for my login credentials. I've no idea how to debug this issue. Any ideas?

**Comment by rzetterberg** [comment]
@geerds I could try and see if I can reproduce the problem on my machine.

What does you `/etc/nixos/configuration.nix` look like? Also what nix channel are you on?

**Comment by geerds** [comment]
I think this issue was because of #6037. KDM worked for me the last two weeks or so
