### ISSUE TITLE
python3Packages.praw fails to build on nixos-unstable

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#64086]
## Issue description

I had i3pystatus fail to build because of a pytest error with praw on unstable.
I tried to bump praw from 6.0.0 to 6.3.1 but it requires a new dep websocket-client that doesn't look packaged thus I ended up ditching it from i3pystatus dependencies. Maybe we should do the same upstream and provide a leaner i3pystatus as it's not a core plugin anyway (and fails https://github.com/NixOS/nixpkgs/issues/51810).
https://github.com/praw-dev/praw

### Steps to reproduce
nix build python3Packages.praw -f channel:nixos-unstable

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.0, NixOS, 19.09.git.0a7b2ab (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(teto): `""`
 - channels(root): `""`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by teto** [comment]
CC @igsha ? what do you think of removing it from i3pystatus default ?

**Comment by igsha** [comment]
Agree. A user can add `praw` manually by overriding of `extraLibs` parameter.

**Comment by jonringer** [comment]
@teto is this still relevant now? or can it be closed?

**Comment by teto** [comment]
I just removed praw it from i3pystatus default dependencies but python3Packages.praw itself still won't build.
So it makes sense to keep the issue open even if I have no personal interest in praw.

**Comment by jonringer** [comment]
it was irritating me, so i updated it.
