### ISSUE TITLE
Plex can't utilize hardware acceleration

### ISSUE THREAD

**Issue by apvodney** [NixOS/nixpkgs#64098]
## Issue description
While I have hardware that supports video processing acceleration, plex can't access it.

### Steps to reproduce
1) Have hardware that supports video acceleration (["Using Hardware-Accelerated Streaming--1. Check the system requirements"](https://support.plex.tv/articles/115002178853-using-hardware-accelerated-streaming/))
2) Try to enable "Use hardware acceleration when available" in Plex settings (["Using Hardware-Accelerated Streaming--2. Enable hardware acceleration"](https://support.plex.tv/articles/115002178853-using-hardware-accelerated-streaming/))

## Technical details

```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/zqabb6j60agkcqp5izyqm12gl5k7spcf-bash-interactive-4.4-p23-dev
copying path '/nix/store/zqabb6j60agkcqp5izyqm12gl5k7spcf-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.56, NixOS, 19.09.git.cc83a0d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

The solution to this issue may be the same as [adding hardware acceleration to dockerized Plex](https://forums.plex.tv/t/using-hardware-acceleration-in-docker/229702), possibly just linking /dev/ to the userenv, if that's possible.

**Comment by bachp** [comment]
Can you give some more information about your setup. What kind of hardward do you have? GPU or Intel QuickSync CPU, etc.?

I remember that I had both working Nvidia GPU and Intel QuickSync. I can confirm that quick sync is still working as I use it daily. I don't use a GPU anymore so I can't check.

**Comment by apvodney** [comment]
My CPU is an i7-3615QM (according to /proc/cpuinfo) which has QuickSync and the /dev/dri device is available from a shell, which from my understanding is used by Plex to access QuickSync. I don't have a dedicated GPU.

**Comment by lheckemann** [comment]
It's unfortunately quite easy to confuse graphics acceleration with video (decoding/encoding) acceleration…

Video acceleration is enabled by the VDPAU API, which is configured on NixOS using the [hardware.opengl.extraPackages](https://nixos.org/nixos/manual/options.html#opt-hardware.opengl.extraPackages) (bit of a misnomer) option. Try setting yours to the example provided and see if that helps.

**Comment by onajimaru** [comment]
Also not seeing hardware acceleration using plex. I'm using the configuration below
  `hardware.opengl = {
    driSupport32Bit = true;
    extraPackages = with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau intel-ocl ];
    extraPackages32 = with pkgs.pkgsi686Linux; [ libva vaapiIntel libvdpau-va-gl vaapiVdpau ];
  };
  services.plex = {
    enable = true;
    openFirewall = true;
  };`
I have a 970gtx which should be capable of NVENC

**Comment by apvodney** [comment]
I think this should be closed, either I misremembered, or Plex's policy changed, but the free version of Plex does not support hardware acceleration.

**Comment by ilya-fedin** [comment]
I have the same problem. I believe hardware acceleration is present in the free version and the problem is due to the lack of VA-API drivers built with Plex libc.
