### ISSUE TITLE
libXNVCtrl fails building on nixos unstable

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#64135]
## Issue description

With current unstable `nixos-rebuild` fails with the error messages:

```
   AR           _out/Linux_x86_64/libXNVCtrl.a
ar: `u' modifier ignored since `D' is the default (see `U')
ar: creating _out/Linux_x86_64/libXNVCtrl.a
installing
cp: cannot stat 'libXNVCtrl.a': No such file or directory
builder for '/nix/store/zs8r0ldjmaf5q7p8y5paywacdcmkyddi-libXNVCtrl-430.26.drv' failed with exit code 1
```

cc @abbradar 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.15, NixOS, 19.09pre184290.460136f8a3a (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre184359.73392e79aa6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
cc @eadwu @baracoder
