### ISSUE TITLE
arrow-cpp uses @rpath/libarrow.13.dylib rather than /nix

### ISSUE THREAD

**Issue by ktf** [NixOS/nixpkgs#64133]
## Issue description

On macOS arrow-cpp produces a library which has "id" "@rpath/libarrow.13.dylib". This seems to be different from all the other libraries I have which use an actual path starting with "/nix" and an executable linking against such a library fails to load at runtime.

Fixing by hand the path with:

```
install_name_tool -id /nix/path/to/libarrow.13.dylib /nix/path/to/libarrow.13.dylib
```

fixes the issue and the executable linking to it works as expected.
Is there anything particular which should be done to relocate the id of a dynamic library which needs to be explicitly done in nix?

**Comment by veprbl** [comment]
@ktf Good catch! I've opened a PR to fix this.
