### ISSUE TITLE
Where did mysqldump go?

### ISSUE THREAD

**Issue by schneefux** [NixOS/nixpkgs#64132]
## Issue description
I can't find `mysqldump` after #44343. There is no `mysqldump` package and no `mariadb.client` or `mariadb-client` package.
I don't know how to install it. I think that this is a usability issue and it should be documented or important admin tools should be added back.

cc @Izorkin
### Steps to reproduce
NixOS configuration:
```
services.mysql.enable = true;
services.mysql.pkg = pkgs.mysql;
```
Bash:
`mysqldump` yields "command not found".
`nix-env -i mariadb-client` matches no derivations.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.56, NixOS, 19.09pre184242.1ab2e927a63 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre184383.e8d00113e23"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Izorkin** [comment]
The binary file is fully migrated to the mariadb.client package. Set by the command `nix-env -iA nixos.mariadb.client`.

I opened the discussion to return the old version, or leave the separation of packages on the client and server parts - https://github.com/NixOS/nixpkgs/issues/63723

**Comment by Izorkin** [comment]
Added relese notes - https://github.com/NixOS/nixpkgs/pull/63355/commits/63ff6427749aab7702a727d5a82de6a9520fd086

**Comment by schneefux** [comment]
Cool! Will the package appear on https://nixos.org/nixos/packages.html?

**Comment by Izorkin** [comment]
> Will the package appear on https://nixos.org/nixos/packages.html?

I do not know.

**Comment by gloaming** [comment]
No, I don't think so. Because of https://github.com/NixOS/nixpkgs/commit/b94559dc7f88d52faf4b48ef94fd2837941fd13e the `mysql` attribute is a derivation by itself, so the tooling won't look inside it for other derivations.

With the way the package has been split now, this arrangement is rather unfortunate. We could turn `mariadb` into a package set instead, but that means finding all existing uses of `mysql` and replacing them with `mysql.server` or `mysql.client` (or both) as necessary.

I guess the other option is to create new `mariadb-client` and `mysql-client` top-level attributes.

@vcunat ?

**Comment by lheckemann** [comment]
+1 for top-level client attrs

**Comment by Izorkin** [comment]
https://github.com/Izorkin/nixpkgs/commit/b24bce7903084272841e9e2260cc6bf044769890 - this variant optimal?

**Comment by gloaming** [comment]
Oh, you didn't need to split them into separate files. I just meant we could add
```
mysql-client = mysql.client;
```
in either `all-packages.nix` or `aliases.nix`.

**Comment by Izorkin** [comment]
https://github.com/NixOS/nixpkgs/pull/63355 update MariaDB configuration, please check this variant.

**Comment by Izorkin** [comment]
Fixed, mariadb package includes server and client binaries.
https://github.com/NixOS/nixpkgs/pull/63355
