### ISSUE TITLE
Issue  when writing a test

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#64142]
## Issue description

(asked on IRC)
I am trying to write a nixos test with 2 multihomed machines and the nixpkgs multipath TCP kernel but I systematically get an oom (out of memory) panic even though I tried on 2 different computers with 16GB ram.

Here is the full log of the test session:
https://paste.ubuntu.com/p/cSB2wTWCT5/

I intend to look into but if anyone has any hindsight I am happy to take any advice. Also I am curious if it oom's for others ? the test looks pretty simple

### Steps to reproduce

Get this nixpkgs (small fork of current nixos-unstable):
https://github.com/teto/nixpkgs/blob/nixos-unstable/nixos/tests/networking-mptcp.nix
and run
`nix build -f ./nixos/tests/networking-mptcp.nix`

**Comment by markuskowa** [comment]
Line 13 in your test causes the the memory problem: `virtualisation.memorySize = 128;` 128 MB is a bit tight. I could launch the tests with 512.

**Comment by teto** [comment]
aaaah how could I miss that ?! Thanks that indeed solves it.
