### ISSUE TITLE
Python: bluetooth support is missing

### ISSUE THREAD

**Issue by mvcisback** [NixOS/nixpkgs#6414]
> self.conn = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM,
> AttributeError: 'module' object has no attribute 'AF_BLUETOOTH'

Have not tested with other python versions.

I have `hardware.bluetooth.enable = true` and the modules seem to be loaded

**Comment by iElectric** [comment]
python needs to be compiled with bluez headers, but bluez depends on python. The effort is to refactor bluez to optionally support python, bootstrap python with it and then build bluez with python support.

This is needed for all python interpreters.

**Comment by armijnhemel** [comment]
bluez 5.45 only depends on Python for the tests, so if the tests are skipped, then this should not be a problem.

**Comment by DiThi** [comment]
Any news on this? ds4drv has this exact problem once it has established connection with the gamepad.

**Comment by oxzi** [comment]
#91281 closes this issue by introducing Bluetooth support for `pythonFull`.
