### ISSUE TITLE
Vagrant is out-of-date (2.2.3 -> 2.2.5)

### ISSUE THREAD

**Issue by angristan** [NixOS/nixpkgs#64243]
I'm creating this issue in case anyone wants to take a look.

In the expression there is written:

```
  # NOTE: bumping the version and updating the hash is insufficient;
  # you must use bundix to generate a new gemset.nix in the Vagrant source.
```

I've already used bundix to update a gem, but I don't see a Gemfile in the vagrant folder (only a gemset.nix), so I'm lost 😔

**Comment by veprbl** [comment]
cc @aneeshusa

**Comment by angristan** [comment]
Context + update script: https://github.com/NixOS/nixpkgs/pull/47519#issuecomment-425645412

I'll give it a try
