### ISSUE TITLE
Keybase out of date, KBFS severely out of date

### ISSUE THREAD

**Issue by heronhaye** [NixOS/nixpkgs#64248]
## Issue description
Hi, I'm a Keybase developer and some of our users reported that the Nix packages were out of date.

Keybase 4.1.0 was released a while ago, so I believe these need to be updated: https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/security/keybase.

Additionally, the KBFS nix should point to the new remote, `github.com/keybase/client` with `subPackages = [ "go/kbfs/kbfsfuse" "go/kbfs/kbfsgit/git-remote-keybase" ]`, and be on the same version as the other packages (4.1.0).

Please let me know if you have any questions, happy to answer! Thanks.

### Steps to reproduce
N/A

## Technical details
N/A

**Comment by jonringer** [comment]
@heronhaye if the users are using the stable branch, then the update will need to be backported. Otherwise if they are unstable then it should be just a few short moments ;)

**Comment by worldofpeace** [comment]
KBFS has not been updated as directed here.

**Comment by jonringer** [comment]
@worldofpeace did you want to cherry-pick my commits into yours. Doesn't really make sense for them to exist separately

And I need to read more carefully :)
