### ISSUE TITLE
gnome-control-center crashes when connecting to new hidden network.

### ISSUE THREAD

**Issue by pinkisemils** [NixOS/nixpkgs#64269]
## Issue description
Trying to connect to a new hidden network with `gnome-control-center` crashes `gnome-control-center`.

### Steps to reproduce
1. Run `gnome-control-center`.
2. Navigate to WiFi settings.
3. Click `Connect to Hidden Network` from the burger menu icon thing.
4. Enter new SSID without selecting a known network.
5. Click `Connect`.
6. Get `free(): invalid pointer`, or `munmap_chunk(): invalid pointer`, or some other seemingly random assertion failure.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.56, NixOS, 19.03.173028.7152cb297ad (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173028.7152cb297ad, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pinkisemils** [comment]
In case one needs a workaround to connect to a new hidden network, you can use `nmcli`
```bash
 nmcli connection add type wifi ssid $SSID ifname $IF-NAME wifi-sec.psk $PASSWORD wifi-sec.key-mgmt wpa-psk
```
Works fine for most common networks. Consult the manpages for `nm-settings` and `nmcli` for more advanced setups. NetworkManager might not connect to the new network _immediately_, but in this case, you can use the _Connect to Hidden Network_ dialog just fine if you select an existing connection profile.

**Comment by yurenchen000** [comment]
ubuntu 20  also meet gnome-control-center crash, 
  when add hidden wifi, wpa/psk2

**Comment by jtojnar** [comment]
I am unable to reproduce this. Assuming fixed. Please reopen with a debug symbols if you can still reproduce.
