### ISSUE TITLE
Set maxJobs (and others?) to lower priority in generated hardware-configuration.nix

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#6429]
From the mailing list:

>> I can't set nix.maxJobs in configuration.nix, because it is set in
>> hardware-configuration.nix:
>>
>> error: The unique option `nix.maxJobs' is defined multiple times, in
>> `/etc/nixos/hardware-configuration.nix' and
>> `/etc/nixos/configuration.nix'.
>>
>> Of course, I could work around this by editing
>> hardware-configuration.nix, but then the change would be lost the next
>> time I run nixos-generate-config. Is there a better way to do this?
>
>This should work:
>
>  nix.maxJobs = mkForce 4;
>
>**I guess the option definition in hardware-configuration.nix should be given a
lower priority to prevent this problem.**

**Comment by wmertens** [comment]
No time to work on this right now, feel free to take it or I'll take it later this week.

**Comment by zimbatm** [comment]
How should this be tackled, should the generated hardware-configuration.nix use a mkDefault ?

**Comment by vcunat** [comment]
Yes, I think so.
