### ISSUE TITLE
su problem

### ISSUE THREAD

**Issue by rndd-AK** [NixOS/nixpkgs#64307]
## Issue description

[rndd@core:~]$ su
Password: 
gpg-connect-agent: failed to create temporary file '/roo
gpg-connect-agent: can't connect to the agent: No such f
gpg-connect-agent: error sending standard options: No ag

**Comment by Infinisil** [comment]
Please fill out the [Issue Template](https://github.com/NixOS/nixpkgs/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by rndd-AK** [comment]
[rndd@core:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.14, NixOS, 19.09pre183832.20b993ef2c9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre183832.20b993ef2c9"`
 - channels(rndd): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
Fill out the *full* issue template, there is a section called "Steps to reproduce". Provide as much info as possible, this includes your system config, shell config, whatever you think is relevant. The less info you provide the more likely it is that nobody can help you.

**Comment by rndd-AK** [comment]
"Steps to reproduce":
1) type "su" in console
2) enter your root pass
3) profit

my system config https://github.com/rndd-AK/configs_for_Acer_Swift_SF113-31_V1.13/tree/master/nixos
other configs are default
