### ISSUE TITLE
package request: btcpay

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#64330]
## Issue description

BTC Pay lets you take payments online for free: https://en.bitcoin.it/wiki/BTCPay

Supports bitcoin and other alt coins.

I'll be trying to package this today, but I think it's .NET and have no experience packaging dotnet apps for nixpkgs...

**Comment by prusnak** [comment]
Already packaged in https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/blockchains/btcpayserver
