### ISSUE TITLE
Python: withPackages and overrides does not result in correct `passthru`

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#64334]
## Issue description
Using `withPackages` together with `overrides` currently does not work as expected.
Overrides does not propagate to withPackages. 

### Steps to reproduce
We can demonstrate this easily in the repl:

This works exactly as expected
```
nix-repl> (python3.override { packageOverrides=(self: super: { requests="hello"; }); }).passthru.pkgs.requests  
"hello"
```

This does not:
```
nix-repl> ((python3.override { packageOverrides=(self: super: { requests="hello"; }); }).withPackages(ps: [ps.requests])).passthru.pkgs.requests
«derivation /nix/store/qfnz62wvq8xbmf6zldxqfa205rklhwmv-python3.7-requests-2.21.0.drv»
```
I would expect the second case to also evaluate to my overriden package.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

cc @FRidh

**Comment by FRidh** [comment]
See "9.14.2.2.1.2. Overriding Python packages" in the Nixpkgs manual, rewritten as
```
with import <nixpkgs> {};

(let
  python = let
    packageOverrides = self: super: {
      foo = super.numpy.overridePythonAttrs(old: rec {
        name = "foo";
      });
    };
  in pkgs.python3.override {inherit packageOverrides;};

in python.withPackages(ps: [ps.foo])).env
```
The composition does function, however, the `passthru` seems to be incorrect. Just replace `.env` with  `.passthru.pkgs.foo `.

**Comment by FRidh** [comment]
Using the following solves the issue:
```
with import <nixpkgs> {};

(let
  python = let
    packageOverrides = self: super: {
      foo = super.numpy.overridePythonAttrs(old: rec {
        name = "foo";
      });
    };
  in pkgs.python3.override {inherit packageOverrides; self = python;};

in python.withPackages(ps: [ps.foo])).passthru.pkgs.foo
```
Note the `self = python`.

**Comment by FRidh** [comment]
I've updated the example in f1ff85e61df0401ec1baabe4d33aee35f7bc42e0. There's not much else I think we can do here.

**Comment by adisbladis** [comment]
Ok, updating the example is good enough :) 
Thanks
