### ISSUE TITLE
Python wheels cannot be built to nix stores containing a minus

### ISSUE THREAD

**Issue by cdyson37** [NixOS/nixpkgs#64340]
There's a bash substitution in the unpack phase that looks for the first `-` and discards everything leading up to it:
https://github.com/NixOS/nixpkgs/blob/8f5edef47e2d7d3667148d7ea8122fb4ec6794d1/pkgs/development/interpreters/python/build-python-package-wheel.nix#L11

This works fine if you use `/nix`
```
$ src=/nix/store/0g9g34xk8qy80dsz248jkwqx5xw5600c-user-environment
$ echo ${src#*-}
user-environment
```

But if you install nix somewhere unusual, with a minus in it, the output has slashes in in and the `cp` fails.
```
$ src=/custom-prefix-foo/nix/store/0g9g34xk8qy80dsz248jkwqx5xw5600c-user-environment
$ echo ${src#*-}
prefix-foo/nix/store/0g9g34xk8qy80dsz248jkwqx5xw5600c-user-environment
```

A possible fix is to put a call to `basename` in there, so that we only look at the name of the file (not the complete path to `$src`). So the unpack phase could be replaced with
```
unpackPhase = "mkdir dist; bn=$(basename $src); cp $src dist/\${bn#*-}"
```

Happy to prepare a PR to do this if it's considered sensible.

If anyone reads this and needs a workaround, something like this should do it:
```
let
  fixWheel = pkg: pkg.overrideAttrs (old: {unpackPhase = "mkdir dist; bn=$(basename $src); cp $src dist/\${bn#*-}";});

  overlay = self: super: {

    python37 = let
      packageOverrides = pyself: pysuper: {
        tensorflow-estimator = fixWheel pysuper.tensorflow-estimator;
    };
    in super.python37.override {inherit packageOverrides;};
  };

  pkgs = import <nixpkgs> { overlays = [overlay]; };
in
  pkgs.python37.withPackages (ps: [ps.tensorflow-estimator])
```

**Comment by FRidh** [comment]
This code path is encountered when installing a pre-built wheel. The motivation for purging everything before the dash is because we're only interested in the name of the wheel, and not the store path hash. 

Using the basename should be fine. Please open a PR.
