### ISSUE TITLE
Cannot import opencv python module

### ISSUE THREAD

**Issue by OmnipotentEntity** [NixOS/nixpkgs#64363]
## Issue description

When attempting to run a minimal python file:

    import cv2

While having the python package `opencv` installed, I receive 

    ModuleNotFoundError: No module named 'cv2'

### Steps to reproduce

    $ nix-shell -p "python3.withPackages(ps: with ps; [ opencv ])"
    $ echo "import cv2" | python3 -

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 19.03.173054.754763ff4ba (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173054.754763ff4ba"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by OmnipotentEntity** [comment]
IRC Logs as I sifted through stuff.

    <omnipotententity> I'm having what is probably an easy to solve issue.  I'm trying to run a python script that is importing opencv using the module 'cv2'.  I attempted to add pythonPackages37.opencv to my nix.shell file (along with other dependencies) and the module cv2 is still not being found.  Furthermore, $PYTHONPATH doesn't seem to contain a path to the package folder in /nix/store and /nix/store itself doesn't seem to have a folder for the python package.  
    <omnipotententity> Any hints?
    <omnipotententity> ok, I've figured out why there isn't a python37 folder for it in the nix store.  It's because python37Packages.opencv chain calls into the standard opencv install process with a python flag set.  And I do have two opencv folders in nix store, one for the runtime one for the package.
    <omnipotententity> But I can't figure out where the built module lives in either of these folders.
    <omnipotententity> however, it seems like toPythonModule is supposed to name things properly?
    <omnipotententity> According to https://github.com/NixOS/nixpkgs/issues/45506 I should always use python.withPackages.  This does not seem to help me at the moment though.  I get the same behavior.
    <{^_^}> #45506 (by tolstikh, 45 weeks ago, closed): Cannot have OpenCV binding for python 2 and python 3 active at the same time

**Comment by FRidh** [comment]
We currently have 2.4.13. When checking the build log `nix log -f . python3.pkgs.opencv` I noticed some SyntaxError. Testing now with the latest, 2.4.13.7.

**Comment by FRidh** [comment]
Even with 2.4.13.7 the following files have Python 2 syntax. Is OpenCV 2 even supposed to work with Python 3?

```
/nix/store/69s3k8kz5q51h5f2w575pxirm3ijs2kd-source/modules/python/CMakeLists.txt:execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import distutils.sysconfig; print distutils.sysconfig.get_config_var('SO')"
/nix/store/69s3k8kz5q51h5f2w575pxirm3ijs2kd-source/cmake/OpenCVDetectPython.cmake:      execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "from distutils.sysconfig import *; print get_python_lib()"
/nix/store/69s3k8kz5q51h5f2w575pxirm3ijs2kd-source/cmake/OpenCVDetectPython.cmake:        execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import os; os.environ['DISTUTILS_USE_SDK']='1'; import numpy.distutils; print numpy.distutils.misc_util.get_numpy_include_dirs()[0]"
```

**Comment by doronbehar** [comment]
Are you trying to essentially use opencv version 2.4.8 ? It's from 2017 right? https://opencv.org/opencv-2-4-8/

As for opencv _stable_ (4.1.0) , it's python interface seems to support python 3.7, see https://pypi.org/project/opencv-python/ .

**Comment by OmnipotentEntity** [comment]
I seem to have made a poor assumption.  I assumed `cv2` meant literally version 2, instead `cv2` covers every version of CV after a certain point (I had assumed they went from `cv` to `cv2` to `opencv` through releases, but they actually kept `cv2` around for legacy reasons.)

From further research OpenCV2 does not officially support python3, and unofficially it does not even compile as observed by @FRidh 

Should attempting to install this package as a python37Package throw an error?  Or is the current behavior as expected?  What is normative in this case?

**Comment by FRidh** [comment]
> Should attempting to install this package as a python37Package throw an error? Or is the current behavior as expected? What is normative in this case?

No, we should disable it then in case of Python 3.

**Comment by doronbehar** [comment]
If so, I think it shouldn't be included in `python3Packages`s attributes. Could you give perhaps more links proving the python versions support state from opencv's website Bug tracker, for reference please?

**Comment by OmnipotentEntity** [comment]
@doronbehar I got my information from an unofficial source: https://pypi.org/project/opencv-python/ I will attempt to find an official source.
