### ISSUE TITLE
arangod default config tries to write into nix store

### ISSUE THREAD

**Issue by SitiSchu** [NixOS/nixpkgs#64406]
## Issue description
The default config file generated by arangodb in `<path-to-arangodb>/etc/arangodb3/arangod.conf` is configured in a way that the log file and the database file would be located inside the Nix store. This causes an error when trying to run arangodb without any additional configuration:

```
cannot write to file '/nix/store/pic4da770rv8y50irj48rk9lif7xdgqy-arangodb-3.3.19/var/log/arangodb3/arangod.log': Read-only file system
{startup} caught exception during prepare of feature 'Logger': cannot write file
arangod terminated because of an exception: cannot write file

```
### Steps to reproduce
Install arangodb
Run `arangod` on the command line

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.03.172979.8634c3b6199 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(sitischu): `""`
 - channels(root): `"nixos-19.03.172979.8634c3b6199"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by aanderse** [comment]
@SitiSchu to be fair if we switched these directories to the appropriate `/var/*/arangodb` directories this would also cause an error based on permissions, requiring manual intervention. I think the solution to this PR is to finish and merge https://github.com/NixOS/nixpkgs/pull/40167. Do you agree?

**Comment by SitiSchu** [comment]
Ah, I see, yep this would work as well.
