### ISSUE TITLE
Consider bundling the .config file used to build the kernel as part of the linux-$(uname -r) package

### ISSUE THREAD

**Issue by mbsulliv** [NixOS/nixpkgs#6444]
I'm trying to reproduce the exact kernel build that was distributed as part of NixOS 14.12 so that I can build a kernel module and have the modversion information match up.  However, I don't know the exact settings that were used.

Can the .config file that was used to build the kernel be bundled inside future linux-$(uname -r) packages to make this process easier in the future?  In other words, currently in my /nix/store/...linux-3.14.29 package I have three top-level items: lib/, bzImage, and System.map.  I'd like to see the .config (possibly renamed to "config.txt" or similar) as the fourth top-level item in the package.

On a related note, can someone publish what .config file was actually used to generate the 14.12 (kernel 3.14.29) release?

**Comment by wizeman** [comment]
One workaround is to do `modprobe configs`. You will then find the config file in `/proc/config.gz`.

But this only works if the system is running and you are logged into it as root.

**Comment by mbsulliv** [comment]
Thanks for the awesome workaround!  It worked exactly as you described and I was able to build the kernel module with the correct modversion information.

I still think there is value in adding the information to the package so that you don't have to be on a running system.

**Comment by garbas** [comment]
@mbsulliv i think this issue was adressed in #10912. please reopen if i misunderstood it.
