### ISSUE TITLE
datadog 6: config files saved as JSON instead of YAML

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#64449]
## Issue description
When configuring DataDog with custom checks they configuration is saved as JSON but in YAML files. It seems the DataDog Agent v6 only support YAML files and ignore badly formatted ones (e.g. JSON).

> ... from version 6.0.0, the Agent loads any valid YAML file contained in the folder:
> `/datadog-agent/conf.d/<CHECK_NAME>.d/`.

See:
- https://docs.datadoghq.com/agent/guide/agent-configuration-files/?tab=agentv6#checks-configuration-files-for-agent-6
- https://github.com/NixOS/nixpkgs/blob/f56d507e064d847057e2c81af5b53053e40c8ca0/nixos/modules/services/monitoring/datadog-agent.nix#L145-L182

### Steps to reproduce

```
{
  services.datadog-agent = {
    apiKeyFile = secrets/datadog.api_key;
    enable = true;
    enableLiveProcessCollection = true;
    enableTraceAgent = true;
    checks = {
      docker_daemon = {
        init_config = null;
        instances = [
          {
            url = "unix://var/run/docker.sock";
          }
        ];
      };
    };

    diskCheck = {
      init_config = null;
      instances = [
        {
          mount_point_blacklist = [
            "/var/lib/docker/(containers|overlay2)/./(shm|merged)"
            "/run/docker/netns."
            "/sys/kernel/debug/"
            "/run/user/1000/"
          ];
        }
      ];
    };
  };
}
```

Then see the generated files in `/etc/datadog-agent/conf.d/*/*.yaml`. The content will be JSON as specified within the datadog-agent.nix expression in the checks documentation.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.15, NixOS, 19.09.git.656dcc036fc (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-18.09.2574.a7e559a5504"`
 - nixpkgs: `/home/terje.larsen/src/github.com/terlar/nix-config/nixpkgs` (656dcc0)

**Comment by cransom** [comment]
https://github.com/NixOS/nixpkgs/pull/63864 has a snippet for correctly configuring a datadog plugin. It's currently broken due to a subtlety in the python that gets injected, but after merge, and you enable the python packages required for the docker plugin, should work as well.  json being used as yaml in this context works.

**Comment by terlar** [comment]
Thanks for the info, this is first time I use Datadog under nix so I just presumed this was the case. But happy that you had tracked down the actual issue. 👍
