### ISSUE TITLE
AMD Ryzen 3000 RDRAND Workaround

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#64443]
## Issue description
Early adopters of the new Ryzens CPUs might find themselves in front of an unbootable system, even though the workaround is already upstream (https://github.com/systemd/systemd/pull/12536/commits/1c53d4a070edbec8ad2d384ba0014d0eb6bae077)

Does not (yet) affect me, but it seems to be affecting every Ryzen-Linux-review.

see: 
https://www.phoronix.com/scan.php?page=article&item=ryzen-3700x-3900x-linux&num=2
(german) https://www.heise.de/newsticker/meldung/Ryzen-3000-Bekannter-Fehler-bringt-viele-Linux-Distributionen-zu-Fall-4465220.html

I'd make a PR, if i'd knew the caveats of nixos' systemd fork.

**Comment by worldofpeace** [comment]
I'm pretty sure if you were to submit a pr that just cherry-picked that commit it would probably be accepted
:+1:

**Comment by goertzenator** [comment]
As a data point, I've been running NixOS on a 3900x for a several weeks and haven't seen any issues.  Motherboard is Taichi x470 and 2 days ago upgraded the BIOS to include AGESA Combo-AM4 1.0.0.3 ABB... still no issues.

**Comment by worldofpeace** [comment]
That's because we have this commit :sparkles: 
* https://github.com/NixOS/systemd/commit/5fb35fbc783516e2014115c3488134a2afb8494c

closing.
