### ISSUE TITLE
python2.7-suds-jurko-0.6 broken by recent update of pluggy

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#64440]
`python27Packages.suds-jurko` fails its test suite in current versions of `master` and therefore no longer compiles. According to `git bisect`, the commit that broke the build is aad6f1ca903a82be5b0a5f0d267b3abd801834ef from @marsam: 

~~~
commit aad6f1ca903a82be5b0a5f0d267b3abd801834ef
Author: Mario Rodas <marsam@users.noreply.github.com>
Date:   Fri May 24 20:00:00 2019 -0500

    pythonPackages.pluggy: 0.8.1 -> 0.11.0
~~~

`python2.7-suds-jurko-0.6` is a dependency of `python2.7-pytest-3.10.1`, so this build failure breaks quite a few packages.

**Comment by peti** [comment]
Well, now what?

**Comment by marsam** [comment]
Later today, I'm going to create a PR to drop pytest_3

**Comment by FRidh** [comment]
Either attempt to use the current `pytest`, or disable tests altogether.
