### ISSUE TITLE
Coreutils build fails with ZFS filesystem

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#64459]
## Issue description
Coreutils build fails when building in a ZFS filesystem (at least I highly suspect that to be the cause), due to a test failure:
```
FAIL: tests/du/basic
====================

--- exp 2019-07-08 20:30:19.141329213 +0000
+++ out 2019-07-08 20:30:19.124329113 +0000
@@ -1,7 +1,7 @@
 1      d/sub/2
 2      d/sub
-9      d/1
-12     d
+1      d/1
+4      d
 ===
 2      d/sub
 10     d
FAIL tests/du/basic.sh (exit status: 1
```

### Steps to reproduce
Try to build coreutils such that the build directory is in ZFS.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.57, NixOS, 19.09.git.d543e4f (Loris)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by lheckemann** [comment]
> ```
> # Perform this test only if "." is on a local file system.
> # Otherwise, it would fail e.g., on an NFS-mounted Solaris ZFS file system.
> ```

https://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=blob;f=tests/du/basic.sh;h=7d82e16bc18078712a102db601ba051121a2b306;hb=HEAD#l61

Well… Points for trying, I guess? We should probably skip the test since it makes a bunch of not-necessarily-appropriate assumptions.

**Comment by lheckemann** [comment]
Seems to be fixed.
