### ISSUE TITLE
curaLulzbot version

### ISSUE THREAD

**Issue by jrobinson-uk** [NixOS/nixpkgs#64469]
https://github.com/NixOS/nixpkgs/blob/9ec7625cee5365c741dee7b45a19aff5d5d56205/pkgs/applications/misc/cura/lulzbot.nix#L8

Is there a way to install a more recent version of cura-lulzbot edition?

**Comment by teto** [comment]
I guess the pool of people that could update and test this is very limited so feel free to tackle it yourself :) 
We can help. How old is the current nixpkgs version vs upstream ? https://code.alephobjects.com/w/cura-lulzbot/

**Comment by gebner** [comment]
Can you test #61054?

**Comment by jrobinson-uk** [comment]
Happy to, not 100% sure on the process for testing that pull request. do in build off a local version of nixpkgs with that pull applied. Can you point me in the right direction?

**Comment by gebner** [comment]
@jrobinson-uk The one-line command to try this out would be:
```
nix run -f https://github.com/charles-dyfis-net/nixpkgs/archive/modernize-cura-lulzbot.tar.gz curaLulzbot -c cura
```
You could also manually clone the git repository of the PR and build it:
```
git clone https://github.com/charles-dyfis-net/nixpkgs
cd nixpkgs
git checkout modernize-cura-lulzbot
nix-build -A curaLulzbot
./result/bin/cura
```
But `curaLulzbot` [failed to build when I just tried it](https://github.com/NixOS/nixpkgs/pull/61054/files#r303207234), so please wait a bit.

**Comment by charles-dyfis-net** [comment]
@jrobinson-uk, ...if you want to try the instructions gebner provided, I just updated the PR to roll the patch behind the now-broken link inline.

**Comment by charles-dyfis-net** [comment]
@jrobinson-uk, ...FYI, the PR is now updated to 3.6.15.

I'm using it happily myself, but reports (of success or failure) would be very welcome.
