### ISSUE TITLE
Cannot invoke gccN in nix-shell, where N = 5, 6, 8.

### ISSUE THREAD

**Issue by kindaro** [NixOS/nixpkgs#64557]
## Issue description

I've been [told](https://github.com/NixOS/nixpkgs/issues/64530) that I should use `nix-shell` when I want to do programming, so that all the libraries are visible and could be linked. I also [discovered][1] that I can use "hidden" versions of some packages, such as `gcc`. Unfortunately, I notice that whatever `gccN` I pick, the `gcc` executable available is always the same, `7.4.0`.

[1]: https://unix.stackexchange.com/q/529065

### Steps to reproduce

    % nix-shell --packages gcc5 --command 'sh -c "command -v gcc"'
    /nix/store/gzx96ys6wczvafmg3p57s9zc6q4xpkzz-gcc-wrapper-7.4.0/bin/gcc
    % nix-shell --packages gcc6 --command 'sh -c "command -v gcc"'
    /nix/store/gzx96ys6wczvafmg3p57s9zc6q4xpkzz-gcc-wrapper-7.4.0/bin/gcc
    % nix-shell --packages gcc7 --command 'sh -c "command -v gcc"'
    /nix/store/gzx96ys6wczvafmg3p57s9zc6q4xpkzz-gcc-wrapper-7.4.0/bin/gcc
    % nix-shell --packages gcc8 --command 'sh -c "command -v gcc"'
    /nix/store/gzx96ys6wczvafmg3p57s9zc6q4xpkzz-gcc-wrapper-7.4.0/bin/gcc
    % nix-shell --packages hello --command 'sh -c "command -v gcc"'
    /nix/store/gzx96ys6wczvafmg3p57s9zc6q4xpkzz-gcc-wrapper-7.4.0/bin/gcc

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.16-arch1-1-ARCH, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(kindaro): `"nixpkgs-19.09pre184803.d567c486ca5"`
 - nixpkgs: `/home/kindaro/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment]
Yes, this is silly. When not given a Nix expression, `nix-shell` will use the `-p` arguments and a default expression (https://github.com/NixOS/nix/issues/726) which uses `runCommand` which includes the default `stdenv`. 

The only way around this is by using your own expression that does not include the default `stdenv`, e.g.:
```
$ nix-shell -E 'with import <nixpkgs> {}; runCommandNoCC "name" { buildInputs = [ gcc8 ]; } ""'
```
I strongly recommend writing a `shell.nix` in this case.

Apparently `mkShell` uses `runCommand` by default as well. That's unfortunate, I think.

**Comment by matthewbauer** [comment]
It actually does work as expected with *nativeBuildInputs* but not buildInputs:

```
$ nix-shell -E 'with import <nixpkgs> {}; runCommandCC "name" { nativeBuildInputs = [ gcc8 ]; } ""' --run 'gcc -version'
```

nativeBuildInputs get precedence over buildInputs, and "gcc" is considered a native build inputs. But, nix-shell -p only does buildInputs. See https://github.com/NixOS/nix/pull/2504

**Comment by FRidh** [comment]
Closing because we can't do more here.
