### ISSUE TITLE
go build seems to operate entirely in its $out directory, preventing debugging

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6462]
If the build fails (as it is for me), I typically run with `-K` and then poke around the build directory. Unfortunately, it has nothing in it, because I think most of the work happens in `$out`, which gets cleared out on a failed build regardless of `-K`.

**Comment by copumpkin** [comment]
cc @cstrahan

**Comment by copumpkin** [comment]
I run `nix-build -K -A go`, then the build fails (that's an issue with my setup, and not what I'm reporting here). 

When the build fails, it says 

```
note: keeping build directory '/path/to/your/tmp'
```

so I `cd` into there. I usually find extract build files in there and `env-vars`, and can poke around the broken build to find out what's wrong.

The go build, on the other hand, only has `env-vars` in there, because it does all its work in the `$out` directory. 

Does that make more sense?

**Comment by lethalman** [comment]
Yes, it makes sense to move everything to the tmpdir and at the end mv to $out.

**Comment by copumpkin** [comment]
This is go itself, not a go package, and at least in my branch (up to date with master as of yesterday), `1.4.nix` doesn't use `buildGoPackage` for the compiler itself.

**Comment by lethalman** [comment]
Ah ok, confused because buildGoPackage does something similar.

**Comment by copumpkin** [comment]
Ah, so they should probably both be fixed. I won't have time to put against this for a while (still spending most of my time on the darwin stdenv improvements) but will take it if nobody gets to it in the next few weeks :smile:

**Comment by Profpatsch** [comment]
(triage) still a problem? cc @copumpkin @lethalman

**Comment by jb55** [comment]
(triage) 👋 checking in again. status of this? @copumpkin @lethalman @cstrahan

**Comment by Profpatsch** [comment]
I can only say that `buildGoPackage` is broken anyway and should probably receive an overhaul.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by Profpatsch** [comment]
Closing, no reaction for too long.
