### ISSUE TITLE
ffmpeg-full does not build on macOS

### ISSUE THREAD

**Issue by bdesham** [NixOS/nixpkgs#64651]
## Issue description

ffmpeg-full does not build on my machine (macOS 10.13). If I add

```
{
  packageOverrides = pkgs: {
    ffmpeg-full = pkgs.ffmpeg-full.override {
      nvenc = false;
    };
  };
}
```

to my config.nix then I’m able to build the package.

This issue is fixed in PR #63643, which I opened, but there hasn’t been any activity on that for a while.

### Steps to reproduce

1. `nix-env -iA nixpkgs.ffmpeg-full`

<details>
<summary>The output of that command</summary>
<pre>
installing 'ffmpeg-full-4.1.3'
these derivations will be built:
  /nix/store/sn1bf1yh0hfsx4b3qpv791szw2q6xdfk-ffmpeg-full-4.1.3.drv
these paths will be fetched (0.05 MiB download, 0.30 MiB unpacked):
  /nix/store/spmc8abdq71kc6miq0304nyvgrzj7pzj-nv-codec-headers-9.0.18.1
copying path '/nix/store/spmc8abdq71kc6miq0304nyvgrzj7pzj-nv-codec-headers-9.0.18.1' from 'https://cache.nixos.org'...
building '/nix/store/sn1bf1yh0hfsx4b3qpv791szw2q6xdfk-ffmpeg-full-4.1.3.drv'...
unpacking sources
unpacking source archive /nix/store/x6zd823d3492y1j22plij99gdbylkc2g-ffmpeg-4.1.3.tar.xz
source root is ffmpeg-4.1.3
setting SOURCE_DATE_EPOCH to timestamp 1554117394 of file ffmpeg-4.1.3/libavformat/movenc.c
patching sources
patching script interpreter paths in .
./tools/clean-diff: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/libav-merge-next-commit: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/make_chlayout_test: interpreter directive changed from "/usr/bin/env perl" to "/nix/store/mq5a6ab8828baq55xy4z7089jkmfqmgf-perl-5.28.2/bin/perl"
./tools/cl2c: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/unwrap-diff: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/gen-rc: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/plotframes: interpreter directive changed from "/usr/bin/env perl" to "/nix/store/mq5a6ab8828baq55xy4z7089jkmfqmgf-perl-5.28.2/bin/perl"
./tools/patcheck: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/murge: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/missing_codec_desc: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tools/dvd2concat: interpreter directive changed from "/usr/bin/env perl" to "/nix/store/mq5a6ab8828baq55xy4z7089jkmfqmgf-perl-5.28.2/bin/perl"
./tools/bisect-create: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./compat/cuda/ptx2c.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./compat/windows/mslink: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./compat/windows/makedef: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./compat/solaris/make_sunver.pl: interpreter directive changed from "/usr/bin/env perl" to "/nix/store/mq5a6ab8828baq55xy4z7089jkmfqmgf-perl-5.28.2/bin/perl"
./configure: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tests/copycooker.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tests/fate.sh: interpreter directive changed from " /bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tests/lavf-regression.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tests/fate/source-check.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tests/regression-funcs.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./tests/fate-run.sh: interpreter directive changed from " /bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./ffbuild/pkgconfig_generate.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./ffbuild/version.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
./doc/doxy-wrapper.sh: interpreter directive changed from "/bin/sh" to "/nix/store/mlsjkws5zc9dja87npqy8g1vrfx1rf23-bash-4.4-p23/bin/sh"
configuring
configure flags: --disable-static --prefix=/nix/store/jsakjji01na8rjjl21n80b3hmcanppld-ffmpeg-full-4.1.3 --target_os=darwin --arch=x86_64 --enable-gpl --enable-version3 --disable-nonfree --enable-shared --disable-static --enable-pic --cc=clang --disable-small --enable-runtime-cpudetect --disable-lto --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --enable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --enable-doc --disable-htmlpages --enable-manpages --disable-podpages --disable-txtpages --enable-bzlib --enable-libcelt --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --disable-frei0r --enable-libfribidi --disable-libgme --enable-gnutls --enable-libgsm --enable-ladspa --enable-libmp3lame --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --disable-libdc1394 --enable-iconv --disable-libmfx --disable-libmodplug --enable-libmysofa --enable-libopus --enable-libssh --enable-libtheora --disable-libv4l2 --disable-vaapi --enable-vdpau --enable-libvorbis --enable-libvpx --enable-libwebp --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-lzma --enable-nvenc --disable-openal --enable-libopencore-amrnb --disable-opengl --enable-libopenjpeg --disable-openssl --disable-libpulse --enable-librtmp --enable-sdl2 --enable-libsoxr --enable-libspeex --disable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libx264 --disable-libx265 --disable-libxavs --enable-libxvid --enable-libzmq --enable-zlib --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
ERROR: nvenc requested, but not all dependencies are satisfied: ffnvcodec

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
builder for '/nix/store/sn1bf1yh0hfsx4b3qpv791szw2q6xdfk-ffmpeg-full-4.1.3.drv' failed with exit code 1
error: build of '/nix/store/sn1bf1yh0hfsx4b3qpv791szw2q6xdfk-ffmpeg-full-4.1.3.drv' failed
</pre>
</details>

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(bdesham): `"nixpkgs-19.09pre184803.d567c486ca5"`
 - nixpkgs: `/Users/bdesham/.nix-defexpr/channels/nixpkgs`

**Comment by vcunat** [comment]
Should be fixed now by your 2d2a3dcffb.
