### ISSUE TITLE
haskellMode ghci-ng: <command line>: cannot satisfy -package-id

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#6466]
Hi, I'm trying to use ghci-ng (compiled from chrisdone's github repo in a ghcWithPackages environment) with haskell-mode in emacs. To be sure that the error doesn't reside in my particular config, I'm trying also the one suggested by @chrisdone at https://github.com/chrisdone/emacs-haskell-config.

So, either way, when I try to start a repl, using cabal-repl as the value for haskell-process-type, I get the error in http://lpaste.net/120787

Note that in the specific case it was complaining about the package foldl, but it always complains about a valid installed library (even base).

Also, when I load a library in simple ghci-ng (command line, not emacs), I get errors like:

    SubTranslate.hs:5:8:
        Could not find module ‘Data.Text’
        Perhaps you meant Data.Set (from containers-0.5.5.1)
        Use -v to see a list of the files searched for.

It seems that it can't see the other packages, but why should that be the case?

**Comment by chrisdone** [comment]
Hmm, does the version of GHC that ghci-ng is built with match the version of GHC that your package set (and possible sandbox) was made with?

**Comment by meditans** [comment]
This is a good question. I think that the ghc versions coincide, but there could be a mismatch between the cabal versions. Anyway, this is a conjecture: how can I be sure?

**Comment by meditans** [comment]
This is the output of `cabal repl --with-ghc=ghci-ng -v`:

    /home/meditans/.nix-profile/bin/ghci-ng --numeric-version
    creating dist/build
    creating dist/build/autogen
    Preprocessing library subTranslate-0.0.0...
    /home/meditans/.nix-profile/bin/ghci-ng --info
    /home/meditans/.nix-profile/bin/ghci-ng --info
    creating dist/build
    /home/meditans/.nix-profile/bin/ghci-ng --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -Idist/build/autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -package-name subTranslate-0.0.0 -hide-all-packages -package-db dist/package.conf.inplace -package-id base-4.7.0.2-cb23b5265b6e147094c0cd9ac819acb1 -package-id foldl-1.0.7-3fec37e2aa835572fc0afc661c5086cb -package-id subtitleParser-0.5-9216ec2ebd5976101525102b393ac88e -package-id turtle-1.0.1-679436c94e36feb45583648eb4350951 -XHaskell2010 SubTranslate SubTranslate.Internal -Wall
    <command line>: cannot satisfy -package-id foldl-1.0.7-3fec37e2aa835572fc0afc661c5086cb
    (use -v for more information)

**Comment by peti** [comment]
Have you configure the `$NIX_GHC`, `$NIX_GHCPKG`, ... variables in your shell environment?

**Comment by peti** [comment]
I assume that the lack of these variables was the problem.

**Comment by meditans** [comment]
For future users having this problem: the problem was generated by the fact that I was starting emacs from a shortcut, and it didn't pick up the right shell variables.
Starting emacs from shell was fine. Thanks @peti.
