### ISSUE TITLE
Alacritty fails with: [ERROR] pw not found

### ISSUE THREAD

**Issue by rhajdacki** [NixOS/nixpkgs#64666]
## Issue description

Alacritty when executed via nixGLNvidia fails with error: `[ERROR] pw not found`

### Steps to reproduce

- Install single user Nix on Ubuntu 16.04 using nix-user-chroot method.
- Install nixGL: https://github.com/guibou/nixGL
- Install alacritty
- Run `nixGLNvidia alacritty`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-151-generic, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(rafalh): `"nixpkgs-19.09pre185219.ed86bbad84c"`
 - nixpkgs: `/home/rafalh/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment]
From #64665. I have in my `~/.bashrc`:
```
export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_sss.so.2
```
According to @rhajdacki this solved the issue.
