### ISSUE TITLE
Using ssh fails with: No user exists for uid 17342423423

### ISSUE THREAD

**Issue by rhajdacki** [NixOS/nixpkgs#64665]
## Issue description

Using ssh (and git via ssh) results in error: `No user exists for uid 17342423423`

### Steps to reproduce

- Install single user Nix on Ubuntu 16.04 using nix-user-chroot method.
- Execute command `ssh git@github.com`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-151-generic, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(rafalh): `"nixpkgs-19.09pre185219.ed86bbad84c"`
 - nixpkgs: `/home/rafalh/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment]
I encountered this at work where the host operating system used SSSD for authentication. If I recall correctly I had to `LD_PRELOAD` a certain library. If you think this is your issue, I can come back with the solution on Monday.

**Comment by rhajdacki** [comment]
Yeah, seems like this might be it.

**Comment by FRidh** [comment]
I have in my `~/.bashrc`:
```
export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_sss.so.2
```

**Comment by rhajdacki** [comment]
This is it. Solved the problem. Thanks a lot. 
Additional this fixes #64666

**Comment by pavel-kru** [comment]
Hi, guys. Please, help. What I need to do?

**Comment by rgoulter** [comment]
@pavel-kru It's likely you've got the same error as above. First thing to try would be FRidh's solution. Look for a file like `libnss_sss.so.2` in your system. Its name might be different. It might be in a different location than `/lib/x86_64-linux-gnu/`.

Once you know the location of that file, you can try setting the `LD_PRELOAD` environment variable to point to that. e.g. in your shell running:

```
export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_sss.so.2
```

**Comment by pavel-kru** [comment]
> @pavel-kru It's likely you've got the same error as above. First thing to try would be FRidh's solution. Look for a file like `libnss_sss.so.2` in your system. Its name might be different. It might be in a different location than `/lib/x86_64-linux-gnu/`.
> 
> Once you know the location of that file, you can try setting the `LD_PRELOAD` environment variable to point to that. e.g. in your shell running:
> 
> ```
> export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_sss.so.2
> ```

Thank you for answering!
