### ISSUE TITLE
buildkite service fails to start when secrets aren't globally readable

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#64670]
## Issue description

This is a simple one:

The `preStart` script in https://github.com/NixOS/nixpkgs/blob/f62f744ac2e7650dd458a9474005e5d5eae18617/nixos/modules/services/continuous-integration/buildkite-agent.nix#L210-L227

runs as `User = "buildkite-agent";` further down, and it can't do its `cat`ing of e.g. the private key file if that one doesn't have `chmod o+r`.

To fix that, this should have `PermissionsStartOnly=true` so that the `preStart` runs as `root`, and the script should `chown` the created directories to `buildkite-agent`.

### Steps to reproduce

```nix
  services.buildkite-agent = {
    enable = true;
    tokenPath = "/var/lib/buildkite/secret-agent-token";
    openssh.privateKeyPath = "/var/lib/buildkite/ssh/id_rsa";
    openssh.publicKeyPath = /var/lib/buildkite/ssh/id_rsa.pub;
  };
```

where `/var/lib/buildkite/ssh/id_rsa` has permissions

```
-rw------- 1 buildkite-agent root 1.8K Jul 12 12:07 /var/lib/buildkite/ssh/id_rsa
```

**Comment by nh2** [comment]
CC @rvl @deepfire @zimbatm

**Comment by rvl** [comment]
It looks like `PermissionsStartOnly=true` been used in #59358, so it should be fixed once that's merged.

**Comment by pasqui23** [comment]
Unfortunately it has been superceded by https://github.com/NixOS/nixpkgs/pull/68378 ,which does not use `PermissionsStartOnly=true`

**Comment by zimbatm** [comment]
There is no obvious solution here.

Either override the service and set `PermissionsStartOnly=true` or chown the files to be owned by the service UID.
