### ISSUE TITLE
mpd fails to install with a permission error

### ISSUE THREAD

**Issue by nkaretnikov** [NixOS/nixpkgs#6470]
If I add this option to `configuration.nix`:
```
  services.mpd.enable = true;
```
I'll get the following on `nixos-rebuild switch`:
```
warning: the following units failed: mpd.service

● mpd.service - Music Player Daemon
   Loaded: loaded (/nix/store/46dfbqlv6rqnx22sayhqdszx8sj18l3i-unit-mpd.service/mpd.service)
   Active: failed (Result: exit-code) since Fri 2015-02-20 11:39:39 MSK; 81ms ago
  Process: 14751 ExecStartPre=/nix/store/dkmlhml38rcybc1fdkf4g1fq1rawi26b-unit-script/bin/mpd-pre-start (code=exited, status=1/FAILURE)

Feb 20 11:39:39 mu systemd[1]: mpd.service: control process exited, code=exited status=1
Feb 20 11:39:39 mu systemd[1]: Unit mpd.service entered failed state.
Feb 20 11:39:39 mu systemd[1]: mpd.service failed.
Feb 20 11:39:39 mu mpd-pre-start[14751]: mkdir: cannot create directory ‘/var/lib/mpd’: Permission denied
warning: error(s) occured while switching to the new configuration
```

The current workaround (suggested in [this thread](http://article.gmane.org/gmane.linux.distributions.nixos/16210)):

1. Install mpd and mpc (or any other client) by adding them to `environment.systemPackages`.
2. Create a config file for mpd with the needed options, for example: `echo "music_directory \"/home/nikita/music\"" > mpd.conf`.
3. Start mpd: `mpd mpd.conf`.
4. The client should be able to list your music, e.g., `mpc ls`.

**Comment by kirelagin** [comment]
And the problem, obviously, is that `ExecStartPre` is executed as `User`.
The proper way to do this is `tmpfiles.d`.

**Comment by lethalman** [comment]
Why not `PermissionsStartOnly=true` like any other service?

**Comment by falsifian** [comment]
Thanks for filing this, @nkaretnikov. Later in the e-mail thread, @qknight (?) pointed out this issue: https://github.com/NixOS/nixpkgs/issues/6277

It was fixed in a recent comment (11 days ago), so probably this should be closed, but I have one more question (for @lethalman?): is this fixed in the release-14.12 branch?

**Comment by lethalman** [comment]
The systemd service in 14.12 runs as root (don't be confused, mpd runs as mpd user, but not defined in systemd).

**Comment by falsifian** [comment]
Cool, I will close this. @nkaretnikov, please re-open if you update and still see this.
