### ISSUE TITLE
hdajackretask issue

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#64717]
hdajackretask from alsa-tools doesn't work on NixOS

**Comment by lasers** [comment]
Please revisit this again.

* `nix-shell -p alsaTools --run hdajackretask` displays a configuration box for me.
* `alsaTools` version likely was at `1.1.6` (2019). This got updated to `1.1.7` then `1.2.2`.
* Not enough information in this issue.
* Possible segfault duplicate https://github.com/NixOS/nixpkgs/issues/25558.

**Comment by lasers** [comment]
@SuperSandro2000

**Comment by SuperSandro2000** [comment]
Closing because it issue does not contain all required information and author is a ghost now.
