### ISSUE TITLE
npm2nix should be removed from nixpkgs

### ISSUE THREAD

**Issue by chaoflow** [NixOS/nixpkgs#64739]
## Issue description

[npm2nix](https://github.com/NixOS/npm2nix) is unmaintained, superseded by node2nix and should therefore be removed from nixpkgs

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by teto** [comment]
@chaoflow seems LGTM. Wanna open a PR ?
