### ISSUE TITLE
stack is broken on Nixos

### ISSUE THREAD

**Issue by greydot** [NixOS/nixpkgs#64746]
## Issue description
See https://github.com/commercialhaskell/stack/issues/4864 for more info. This bug is fixed in stack v2.1.3, while nixpkgs still has v2.1.1.1.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by rnhmjoj** [comment]
pkgsStatic seems pretty broken: I have just tried building a go executable and it came dynamically linked against glibc. Perhaps there should be an issue (or project maybe) tracking this problems.

**Comment by greydot** [comment]
@rnhmjoj are you sure this is related to the haskell-stack bug?

**Comment by rnhmjoj** [comment]
Oops, I replied to the wrong issue.

**Comment by traleig1** [comment]
This looks like it should have been resolved now by https://github.com/NixOS/nixpkgs/commit/020685de8524bf2eada49fe080e33ea3f178a2fa
