### ISSUE TITLE
Hydra build broken on master

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#64838]
## Issue description
hydra seems to no longer build due to a dependency test failure on master.

Perl is outside my comfort area, so hoping someone else will pick this up :)

Seems the ` /nix/store/6r001iyf6yypg48xcsgd2324mh137mbm-perl5.28.2-Email-Sender-1.300031.drv` derivation fails to build, with the following error:

```
Test Summary Report
-------------------
t/sendmail.t         (Wstat: 512 Tests: 2 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 5 tests but ran 2.
Files=18, Tests=127,  7 wallclock secs ( 0.07 usr  0.03 sys +  2.43 cusr  2.19 csys =  4.72 CPU)
Result: FAIL
Failed 1/18 test programs. 0/127 subtests failed.
```

### Steps to reproduce
`$ nix-build default.nix -A hydra`
or
`$ nix-build default.nix -A perl528Packages.EmailSender` for the dependency that is failing.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.57, NixOS, 19.09pre184855.beff2f8d75e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre184855.beff2f8d75e"`
 - channels(jon): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/64157#issuecomment-510473907

**Comment by marsam** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/64736
