### ISSUE TITLE
Move /pkgs/development/web/nodejs/ to /pkgs/development/interpreters/js/nodejs

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#6488]
I'd expect to find nodejs as a javascript interpreter, not inside the vaguely defined "web" directory. I'd send a pull request that moves the directory, but I don't know enough about Nix to know whether that'd introduce any bugs.

**Comment by offlinehacker** [comment]
Just check all the paths, and then send some pull request, and we will review it and should be fine :)
