### ISSUE TITLE
ghc-mod not currently compatible with Cabal 1.22 

### ISSUE THREAD

**Issue by miguel-negrao** [NixOS/nixpkgs#6496]
https://github.com/kazu-yamamoto/ghc-mod/issues/417

Currently in haskellng cabal-install is v1.22 , this means if a project folder has the files created by cabal configure, ghc-mod will not work due to a bug. Perhaps the default version of cabal-install should be 1.20  until this is fixed ? I didn't find a way to specify a previous version of cabal-install in the shell.nix using the new haskellng syntax without camel case.

**Comment by peti** [comment]
My understanding is that `ghc-mod` doesn't care what version of `cabal-install` is used; what matters is the version of `Cabal`. IMHO, a simple fix should be to run `cabal configure --cabal-lib-version=1.18.1.5` to force use of the native version.

**Comment by miguel-negrao** [comment]
if I do that, then when I do 'cabal build' I get

```
cabal build
cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.18.1.5, now Cabal-1.22.0.0)
```
although ghc-mod then works...

**Comment by peti** [comment]
`haskellngPackages` is now set at GHC 7.10.x, so this particular issue should be fixed. If in doubt, it's also possible to downgrade to `cabal-install_1_18_0_8` for GHC 7.8.x support.

**Comment by gilligan** [comment]
Sorry to comment on a closed ticket but I am facing this exact problem and I am somewhat lost. I am using haskellng with ghc7.8.4 which per se seems to work but I would like to install cabal 1.20. How is that currently possible ?

**Comment by gilligan** [comment]
@peti @miguel-negaro so what is the solution/fix here? Tried for a good while to find some solution yesterday and asked on nix-dev with no solution in sight.

**Comment by miguel-negrao** [comment]
I'm also clueless, I just stopped using cabal altogether and compile with GHC at the moment...

**Comment by jagajaga** [comment]
We just need ghc-mod update like
https://github.com/jagajaga/my_configs/blob/master/.nixpkgs/common.nix#L7

**Comment by peti** [comment]
@gilligan, install `cabal-install` like so:

    $ nix-env -iA haskell-ng.packages.ghc784.cabal-install_1_18_0_8

You can see the list of available packages by running

    $ nix-env -qaP -A haskell.packages.ghc784

**Comment by gilligan** [comment]
@peti thanks
