### ISSUE TITLE
KMail/Akonadi major memory leak and CPU usage in NixOS 19.03

### ISSUE THREAD

**Issue by silverhook** [NixOS/nixpkgs#65019]
## Issue description

When running an up-to-date NixOS 19.03 (current stable), KMail/Akonadi starts and never stops eating up a huge amount of CPU, leaks memory and eventually stops showing e-mails, but the “loading e-mail” page.

This may be related to https://bugs.kde.org/show_bug.cgi?id=397316 and/or the bugs and patches referenced therein.

### Steps to reproduce

0. (be on stable)
1. install kmail and make sure you have an IMAP resource connected to it
2. open kmail and wait for a minute or two

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173147.77295b0bd26 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173147.77295b0bd26"`
 - channels(hook): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Chiiruno** [comment]
I've had a pretty bad memory leak, perhaps related to this, since 19.09 update.

**Comment by Chiiruno** [comment]
Actually in my case, it's probably just baloo.

**Comment by silverhook** [comment]
As a follow-up, I cannot say if this is solved in 19.09, because in 19.09 Akonadi does not connect with MySQL/MariaDB and therefore I cannot even get to the stage to see if the bug persists or not.
