### ISSUE TITLE
Darwin bootstrapping fails on staging-next

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#65136]
## Issue description

https://hydra.nixos.org/build/96404229

### Steps to reproduce

cc @NixOS/darwin-maintainers 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by matthewbauer** [comment]
This appears to be caused by 3e867d16cde4ecf81d04d41acb99ea464f5c4663.

**Comment by FRidh** [comment]
Thank you for investigating. Then we'll revert it.

**Comment by FRidh** [comment]
Reverted in 835f6b6.
