### ISSUE TITLE
nixpkgs search hanging the system

### ISSUE THREAD

**Issue by guyzmo** [NixOS/nixpkgs#6515]
I saw #3594, but I believe it should be made as another issue, as first I can't tell whether this is a regression as I'm not a long term user of nix, and secondly the issue is not a few seconds of wait, but a system freeze for a few minutes.

I'm not using a standalone nixos, I'm running nixpkgs on top of a Debian Wheezy, running X.Org X Server 1.12.4 and gnome-shell 3.4.2. My system is not really recent, but decent enough to not feel the need to upgrade for many years (quad-core 2.4GHz, 4GB in dual-channel, WD Black Caviar 10kRPM disks). But whenever I do `nix-env -qa` or have `nox` updating the cache, I'm sure I can go get a coffee, take a shower or do something else, because I know my computer is hanging for about 10 minutes, that ends with gnome-shell getting killed, and all operations back to normal. During that hanging, there's no way to interact with the computer and it's impossible to ssh in. 

I did not do all the tests I might think of (like keeping a ssh session opened and see what happens), I've heard from some that going back and forth to the console restores it (though I'd have to restart Xorg, as for an unknown reason I need to restore the console switching keybinds)... Because I need to crack on working on my current project, and waiting for the system to pass the hanging for 10 minutes for each test is not negligible :-)

So I wonder whether this is a known issue with a known solution that I could have found if my duckduck-fu was better? Or is it something related to my system configuration, like some dbus mess (because when you don't know, it's always dbus' fault!) happening making both nix-env and gnome-shell angry at each other for ten minutes? Or is my hardware too crappy to run nix-env?

Even a `find` or a `grep -r` within the nixpkgs takes less time and does not hang my system! So I tend to believe there's more to that than just an I/O issue.

That said, nix is really being the missing tool on my debian to have both a stable/simple system for everyday use, with the ability to have up to date version of packages finely managed for development purposes! For that, thanks a lot! ;-)

**Comment by vcunat** [comment]
Hmm, that behavior sounds like running out of RAM, which can cause heavy lags and killing of larger programs. However, it should only need half a gigabyte (x86_64-linux, nix-1.8, recent nixpkgs):
```
$ command time nix-env -qa > /dev/null
11.38user 0.77system 0:15.58elapsed 78%CPU (0avgtext+0avgdata 573664maxresident)k
58976inputs+0outputs (12major+144836minor)pagefaults 0swaps
```

The real timing I measured is irrelevant to you, as it's on an SSD (and maybe with partially hot cache).

**Comment by guyzmo** [comment]
ok, below is me installing an updated avr package. I went out for 45 minutes, so I'm sorry for the delay, and I used `nox` because when it's not refreshing, it's lightning fast.

```
% command time nox avr
Refreshing cache
1 avr8-burn-omat-2.1.2 (nixpkgs.avr8burnomat)
    GUI tool for avrdude
2 avra-1.3.0 (nixpkgs.avra)
    Assember for the Atmel AVR microcontroller family
3 avrdude-6.1 (nixpkgs.avrdude)
    Command-line tool for programming Atmel AVR microcontrollers
4 avrdudess-2.2.20140102 (nixpkgs.avrdudess)
    GUI for AVRDUDE (AVR microcontroller programmer)
5 avr-gcc-libc (nixpkgs.avrgcclibc)
    AVR development environment including binutils, avr-gcc and avr-libc
6 pypy2.4-avro-1.7.6 (nixpkgs.pypyPackages.avro)
    A serialization and RPC framework
7 python2.7-avro-1.7.6 (nixpkgs.python27Packages.avro)
    A serialization and RPC framework
8 python3.3-avro3k-1.7.7-SNAPSHOT (nixpkgs.python33Packages.avro3k)
    A serialization and RPC framework
9 python3.4-avro3k-1.7.7-SNAPSHOT (nixpkgs.python34Packages.avro3k)
    A serialization and RPC framework
Packages to install: 5
replacing old ‘avr-gcc-libc’
installing ‘avr-gcc-libc’
13.99user 7.57system 37:45.85elapsed 0%CPU (0avgtext+0avgdata 2128584maxresident)k
1829624inputs+19168outputs (26090major+814086minor)pagefaults 0swaps
```

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by guyzmo** [comment]
sadly yes, it still is… and I have not a clue of what would be causing this. I guess it could be system related, having it hang the system on heavy I/O. 

But if I'm right, why would `nix-env` do such a heavy I/O burden at each call? I mean, no other package manager is causing this hang, only nix. Eventually, if someone could help me split the process of `nix-env` step by step so we could identify which part of the search is causing this, I might discover what is causing the hang (and discover what is causing the I/O load).

**Comment by Profpatsch** [comment]
Did you try removing nix completely and installing a recent version? It’s been nearly two years, a lot has changed in the meantime.

**Comment by guyzmo** [comment]
not removing and reinstalling (feels too windowsy), but I did upgrade it regularly. Do you think a reinstall is a better idea than upgrading?

**Comment by Profpatsch** [comment]
Hm, it sounds to me like the database is blown up or something; on the other hand I haven’t used `nix-env` in quite a while; it has never performed very well, since it needs to evaluate everything in nixpkgs to list anything.
e.g. installation should be done with the attribute name (`-iA`) instead of the derivation name, then it is instantaneous.

**Comment by guyzmo** [comment]
so, how do you look up the "attribute" names without evaluating everything in nixpkgs?

**Comment by Profpatsch** [comment]
@guyzmo Ah, there’s two ways I use:
1. Install `nix-repl` and use auto-completion
2. Use search-tool of your choice (`grep -r`, `ack`, `ag`)  on nixpkgs to find good candidates (tip: `packagename.=` as regex string)

If we want to make that more end-user friendly:
3. Write a small script that automates the second trick and prints possible matches.
4. Write a caching package tool that only evaluates everything if that changed. Similar to `locate`. It should be easy, since is already added to the store and the backend for the tool could generate the indexing database in a nix expression.

I actually quite like the approach of 4.

There’s also an [online search](https://nixos.org/nixos/packages.html), but I don’t particularly like that, since a) it doesn’t reflect the local nixpkgs and b) it needs network access.

**Comment by Profpatsch** [comment]
I’m gonna close now.
