### ISSUE TITLE
option to disable the initrd

### ISSUE THREAD

**Issue by acertain** [NixOS/nixpkgs#6520]
Since I'm using a custom kernel with everything needed to boot compiled in, I'd like to disable the initrd.

**Comment by iElectric** [comment]
Just a tip: such edge case issues normally get resolved only if you submit a PR :)

**Comment by lethalman** [comment]
How do you activate the system without initrd? E.g. symlinking /etc,
setting booted-system, etc.

On Sun, Feb 22, 2015 at 6:54 PM, Carter Charbonneau <
notifications@github.com> wrote:

> Since I'm using a custom kernel with everything needed to boot compiled
> in, I'd like to disable the initrd.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/6520>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by edolstra** [comment]
Currently initrd generation is already disabled for containers (see `system/boot/stage-1.nix`). This could be turned into an explicit option.

**Comment by Profpatsch** [comment]
@fread2281 are you interested in creating a pull request? I can help you implement it if you have any questions.
