### ISSUE TITLE
Update Unity3D to 2019.x

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#65229]
## Issue description
As of Unity 2019.1, the Linux editor has moved from experimental to preview support, and is planned to be fully supported by 2019.3. 2018.3 is currently packaged. 

### Steps to reproduce
N/A

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
N/A

**Comment by leo60228** [comment]
Note that Unity is now installed via the Unity Hub AppImage, which downloads an editor for Ubuntu to a user-specified directory, and .tar.xz downloads are no longer available. I'm not sure how this should be packaged.

**Comment by zimbatm** [comment]
maintainer: @tesq0
