### ISSUE TITLE
Document propagatedBuildInputs

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#65242]
## Issue description
I cannot find a reference to `propogatedBuildInputs` in any manual. I also do not fully understand what it does.

**Comment by FRidh** [comment]
Derivations in `propagatedBuildInputs` are add to the `buildInputs` of any reverse dependency. This can be convenient when you know that any reverse dependency always needs a certain dependency. We typically try to use this only when really needed.

**Comment by FRidh** [comment]
The [Specifying dependencies](https://nixos.org/nixpkgs/manual/#ssec-stdenv-dependencies) section in the Nixpkgs manual describes it, however, the section is not very clear, especially not for newcomers.

**Comment by tbenst** [comment]
Thanks for the link! Would have helped my ctrl-f if I spelled it correctly 🤦‍♂. Have a derivation to fix...
