### ISSUE TITLE
Document build-support package for substituteAll and substitute

### ISSUE THREAD

**Issue by ar1a** [NixOS/nixpkgs#65252]
the shell command substituteAll is documented, but the [build-support package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/substitute/substitute-all.nix) isn't. This is especially useful in situations like [this](https://github.com/NixOS/nixpkgs/pull/65250#discussion_r305708095)

cc @worldofpeace

**Comment by worldofpeace** [comment]
I did a breakdown on how someone can produce patches for this purpose in https://github.com/NixOS/nixpkgs/pull/70512#pullrequestreview-297842523.

I'm guessing I should document this when time permits.
And probably reference it in the Gnome nixpkgs documentation since it's a frequent task.

**Comment by flokli** [comment]
I still think this is useful to document. @worldofpeace, could you get to this?

**Comment by flokli** [comment]
still relevant.

**Comment by flokli** [comment]
still relevant.

**Comment by Fresheyeball** [comment]
FOR THE LOVE OF GOD SOMEONE DOCUMENT BECAUSE I AM TOO LAZY

**Comment by nrdxp** [comment]
whoever does eventually document this, please also document #73712 while you are at it :+1:

**Comment by hacker1024** [comment]
Still relevant.

**Comment by n8henrie** [comment]
I'm happy to try to help with this, but it will be my first documentation contribution.

For my future convenience:
- `substituteAll` function: <https://github.com/NixOS/nixpkgs/blob/4d968c70fb320edbe0a94d6a6a834d9ed2de351f/pkgs/stdenv/generic/setup.sh#L938>
- `substituteAll` documentation: <https://github.com/NixOS/nixpkgs/blob/4d968c70fb320edbe0a94d6a6a834d9ed2de351f/doc/stdenv/stdenv.chapter.md#substituteall-infile-outfile-fun-substituteall>
- `substitute` packages: <https://github.com/NixOS/nixpkgs/tree/4d968c70fb320edbe0a94d6a6a834d9ed2de351f/pkgs/build-support/substitute>


Reading through [the nixpkgs contributing buide](https://github.com/NixOS/nixpkgs/blob/de20681ff7cb84daea4d85630a6a59f2eacf265e/CONTRIBUTING.md?plain=1) and [the manual's section on contributing to documentation](https://nixos.org/manual/nixpkgs/stable/#chap-contributing), I'm guessing this would go into something like... `nixpkgs/doc/packages/stdenv.section.md`? Or maybe `nixpkgs/doc/packages/substitute.section.md`?
