### ISSUE TITLE
nixos-unstable blocked on broken boot tests

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#65256]
**Describe the bug**

Eg. nixos:trunk-combined:nixos.tests.boot.uefiUsb.x86_64-linux:

```
running the VM test script
machine: starting vm
machine# sh: syntax error: unexpected "("
building of '/nix/store/kmh86jrg61cmjzl9hif98zm1n546xldj-vm-test-run-boot-uefi-usb' timed out after 7200 seconds of silence
```

**To Reproduce**

`nix-build nixos/release.nix --arg supportedSystems '["x86_64-linux"]' -A tests.boot.uefiUsb`

**Additional context**

The cause appears to be #64815, as reverting b392c5ab4decc1a74e83b8614ff9ea9da9fee8be fixes the issue.

**Comment by srhb** [comment]
cc @abbradar

**Comment by abbradar** [comment]
On it, see #65214 and #65212. I'll be less hasty next time and run more tests except added ones ~_~

**Comment by srhb** [comment]
Thanks! :smile:

**Comment by abbradar** [comment]
I merged both fixes and will keep eye on Hydra.

**Comment by abbradar** [comment]
https://hydra.nixos.org/build/96729017 it's good now.

Sorry again for the breakage ;_;

**Comment by srhb** [comment]
No worries! Thank you again :D Sorry I didn't notice PRs were already open.
