### ISSUE TITLE
the future of npm tooling in nixpkgs (yarn2nix)

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#65274]
In my opinion nixpkgs needs to have some tooling to fetch dependencies from npm. 
In the past there was yarn2nix, which was removed, but not quite, because riot-desktop still has it's own version of it in the tree.
In my custom packages I have been using the out-of-tree solution https://github.com/moretea/yarn2nix with little hassle, but it has a few problems when used in nixpkgs:

1. The lack of recursive nix or IFD in Hydra requires the yarn.nix file to be manually generated and added to nixpkgs which makes packages hard to maintain and bloats nixpkgs with unnecessary data
2. The hashes for git dependencies are not contained in yarn.lock, which yarn2nix works around by using the builtin fetchGit function, which is not an option in nixpkgs since it is not available in Hydra
3. It has been discussed in the past if the yarn2nix project should be part of nixpkgs, since it has a relatively large, active code base, and nixpkgs was not keeping up with upstream development. 

- Possible solution for 1. and 2.: Download the dependencies during build in a fixed-output derivation like buildRustPackage does it. The requirement is that yarn is reproducible, and it has been discouraged by some folks to use fixed-output derivation like this, because it might mask impurity introduced by the tool, in this case yarn.
- Possible solution for 3.: Split yarn2nix into two parts, like bundix and bundlerEnv. The js part generating yarn.nix from yarn.lock is maintained outside nixpkgs, the nix part using yarn.nix to build a node_modules directory is maintained in nixpkgs, so that other packages in nixpkgs can use it.

Now if you ask me, yarn2nix is a well-built tool like it is, and I would opt for solving 3. like mentioned above and adding it to nixpkgs again. This could be improved upon once the general underlying problem of 1. and 2. is solved in general, since the same problem applies to bundix and bundlerEnv.

**Comment by petabyteboy** [comment]
A competent npm tooling is a requirement for #60788

**Comment by zimbatm** [comment]
Another approach which is interesting is @nmattia's https://github.com/nmattia/napalm which doesn't try to place files on disk but instead spawns a fake NPM registry. It only works for NPM but I assume that it could be adapted for yarn as well. The advantage is that it requires much less nix code and we don't have to depend on undocumented disk locations.

**Comment by nmattia** [comment]
note: I axed the NPM registry, I'm now putting the packages directly in npm's cacache

**Comment by petabyteboy** [comment]
With yarn2nix-moretea added back to nixpkgs this issue is solved for me.
This time I hope it will stay up-to-date and it will not be necessary to remove it again. 
The generate.sh script provided will make it very easy to pull new changes from upstream.
