### ISSUE TITLE
python3Packages.moto's dependencies collide with each other

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#65287]
**Describe the bug**

python3Packages.moto depend on:
- python3Packages.jsondiff provides `/bin/.jsondiff-wrapped`.
- python3Packages.cfn-lint which depends on jsonpatch which also provides `/bin/.jsondiff-wrapped`.

**To Reproduce**
1. `nix-shell --show-trace -E '(with import ./. {}; (python3.withPackages(ps: [ ps.moto ])).env)'`

**Expected behavior**
A shell with the library `moto` available to Python scripts.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.11, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `""`
 - channels(kalbasit): `"home-manager-18.09, nixpkgs-18.09.932.09195057114"`
 - channels(yl): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

AND

 - host os: `Darwin 18.6.0, macOS 10.14.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(yl): `"darwin, nixpkgs-19.09pre185256.5b8b5a694c7"`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.moto
```

cc @FRidh @jonringer

**Comment by kalbasit** [comment]
@FRidh do you have an ETA on this issue? Workaround perhaps?

**Comment by FRidh** [comment]
Apparently the `jsondiff` executable in the `jsondiff` package is deprecated. I therefore suggest patching out the entry from the entry points:
https://github.com/xlwings/jsondiff/blob/v1.2.0/setup.py#L24

**Comment by FRidh** [comment]
Another solution is to increase (or was it decrease?) the priority of the `jsonpatch` package so it takes precedence.

**Comment by kalbasit** [comment]
@FRidh removing the `jsondiff` binary has fixed this particular issue. However, there's another collision now.

```
collision between `/nix/store/ns2w9qjcac97iw3j8sn1ygnmcxlhjgw8-python3.7-backports.weakref-1.0.post1/lib/python3.7/site-packages/backports/__pycache__/__init__.cpython-37.pyc' and `/nix/store/0v89qm932fmifhib68nlimwzlzr6bnyq-python3.7-backports.tempfile-1.0/lib/python3.7/site-packages/backports/__pycache__/__init__.cpython-37.pyc'
```

What to do with this one? I'm filing the PR to fix the first issue.

**Comment by FRidh** [comment]
Having a collision between `__init__` files in the backports package implies that one or more of those packages is using the wrong namespaces convention. See e.g. https://bitbucket.org/ambv/configparser/issues/17/importerror-when-used-with-other-backports

**Comment by jonringer** [comment]
or if they are namespace packages, then they shouldn't be installing the `__init__.py` there altogether for python3, because they should be adhering to [PEP420](https://www.python.org/dev/peps/pep-0420/)

That seems to be the case:
```
$ cat /nix/store/0v89qm932fmifhib68nlimwzlzr6bnyq-python3.7-backports.tempfile-1.0/lib/python3.7/site-packages/backports/__init__.py
# See https://pypi.python.org/pypi/backports

from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

Taking another step back, for python3, this module shouldn't be needed as python3x will use the `tempfile` module

**Comment by kalbasit** [comment]
@jonringer would you be able to help me get this fixed in #65316. You seem to have more Python knowledge than myself :smile:

**Comment by kalbasit** [comment]
hmmm this worked

```patch
diff --git a/pkgs/development/python-modules/moto/default.nix b/pkgs/development/python-modules/moto/default.nix
index 65663c3e3f6..3a7f6316033 100644
--- a/pkgs/development/python-modules/moto/default.nix
+++ b/pkgs/development/python-modules/moto/default.nix
@@ -1,4 +1,4 @@
-{ buildPythonPackage, fetchPypi, jinja2, werkzeug, flask, cfn-lint
+{ buildPythonPackage, fetchPypi, jinja2, werkzeug, flask, cfn-lint, lib, isPy3k
 , requests, pytz, backports_tempfile, cookies, jsondiff, botocore, aws-xray-sdk, docker, responses
 , six, boto, httpretty, xmltodict, nose, sure, boto3, freezegun, dateutil, mock, pyaml, python-jose }:
 
@@ -33,14 +33,15 @@ buildPythonPackage rec {
     xmltodict
     mock
     pyaml
-    backports_tempfile
     cookies
     jsondiff
     botocore
     docker
     responses
     python-jose
-  ];
+  ] ++ (lib.optionals (!isPy3k) [
+    backports_tempfile
+  ]);
 
   checkInputs = [ boto3 nose sure freezegun ];
```

Is this an acceptable fix?

**Comment by kalbasit** [comment]
I made it work with Python3, but it's still broken for Python2 (see #65316).

https://github.com/spulec/moto/blob/d82423788cf372134a9c7d055c8293b281e61803/setup.py#L63

**Comment by jonringer** [comment]
I'm trying to make a pr now :)

**Comment by jonringer** [comment]
For python2, you will need to do something similar to https://github.com/NixOS/nixpkgs/issues/36368 where you do  `python.mkEnv { .... , ignoreCollisions = true; };`

Unfortunately with namespace packages and python2, there's no way to avoid this :(

**Comment by jonringer** [comment]
@kalbasit you should be able to rebase on top of master now that #65318 has been merged
