### ISSUE TITLE
CouchDB service does not start

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#6534]
I have enabled the CouchDB service in NixOS like so:

/etc/nixos/configuration.nix:
  services.couchdb.enable = true;

When I reboot my system, the CouchDB service does not start correctly; the pre-start script throws errors:

● couchdb.service - CouchDB Server
   Loaded: loaded (/nix/store/lp706fcng23pys4h1fa79hlmf60xhbj0-unit-couchdb.service/couchdb.service)
   Active: failed (Result: exit-code) since Sun 2015-02-22 20:59:39 EST; 9h ago
  Process: 1530 ExecStartPre=/nix/store/4ldw1jy2f0sqb8yqgqpi8asydkws197q-unit-script/bin/couchdb-pre-start (code=exited, status=1/FAILURE)

Feb 22 20:59:39 aching systemd[1]: Starting CouchDB Server...
Feb 22 20:59:39 aching couchdb-pre-start[1530]: chown: cannot access ‘/var/run/couchdb/couchdb.uri’: No such file or directory
Feb 22 20:59:39 aching systemd[1]: couchdb.service: control process exited, code=exited status=1
Feb 22 20:59:39 aching systemd[1]: Failed to start CouchDB Server.
Feb 22 20:59:39 aching systemd[1]: Unit couchdb.service entered failed state.
Feb 22 20:59:39 aching systemd[1]: couchdb.service failed.

My pull request, #6283 should resolve this issue.

**Comment by offlinehacker** [comment]
This seems to ne fixed now, reopen if you still have problems.
