### ISSUE TITLE
Package calls for the Librem 5 phone

### ISSUE THREAD

**Issue by craigem** [NixOS/nixpkgs#65361]
**Project description**

Calls:

A phone dialer and call handler.

Written specifically for the Librem 5 although it could no doubt be used elsewhere.

**Metadata**

* homepage URL: https://source.puri.sm/Librem5/calls/
* source URL: https://source.puri.sm/Librem5/calls/
* license: gpl3+
* platforms: linux

**Comment by worldofpeace** [comment]
See https://github.com/NixOS/nixpkgs/pull/57614

**Comment by craigem** [comment]
Noted. I'll check it out.

Thanks!

**Comment by davidak** [comment]
The 0.0.1 PR was merged, so this is solved.

Updating it to the latest release is a different topic. Work on that is being done in https://github.com/NixOS/nixpkgs/pull/107681.
