### ISSUE TITLE
Octave packages documentation missing

### ISSUE THREAD

**Issue by matthuszagh** [NixOS/nixpkgs#65398]
Has anyone worked on using Nix for octave package management? I'd like to get this working, but if there's previous work I can piggyback on that would be great. Any thoughts on what a good solution to this might look like? For instance, something like emacsWithPackages or pythonPackages.

**Comment by FRidh** [comment]
I suggest to indeed take a similar approach

- create a store path per package
- use `octave-home/share/octave/site/m/startup/octaverc` similar to how Python uses `sitecustomize.py` to introduce an env var to add to the search path using `addpath`
- composition using a `buildEnv` function that utilizes that env var.

**Comment by doronbehar** [comment]
That's certainly a nice idea. The popular octave package `symbols` for example requires some python libraries and they aren't loaded if octave doesn't have the correct `PYTHONPATH` in it's environment.

**Comment by doronbehar** [comment]
I'm planning to work on this with the upcoming Octave 6 release, along with other improvements to the derivation.

**Comment by doronbehar** [comment]
I had hopes that the Octave 6 release will come before my semester will start, but it didn't, and now I'm more then busy. I'll note here though that there are a few related PRs I'd like to get in, for the sake of improving the derivation in general:

- https://github.com/NixOS/nixpkgs/pull/98500
- https://github.com/NixOS/nixpkgs/pull/98485

Other then that, I experimented a bit with the idea of fetching all octave packages from octave forge and even fetching the dependencies of each, by scraping the website. The idea is documented here:

https://github.com/NixOS/nixpkgs/compare/master...doronbehar:pkg/octave/pkgs

It's a rough sketch, and the idea is to write a script that will create a list of sources and their deps to generate (perhaps only initially) a list of Nix expressions - sources and their deps & descriptions, a bit like how the lua modules list is generated. If anyone here has more motivation * time you are welcome to work on this.

**Comment by doronbehar** [comment]
Octave 6.1.0 was released and it landed in Nixpkgs (noticed it after I wrote my previous comment) and https://github.com/NixOS/nixpkgs/pull/98485 was merged thanks to it's suitesparse's maintainer.

**Comment by KarlJoad** [comment]
I have started working on this issue as well. 
I have started by addressing the first point mentioned in: https://github.com/NixOS/nixpkgs/issues/65398#issuecomment-515668263

The commits can be found here: [KarlJoad:octave-modules](https://github.com/KarlJoad/nixpkgs/tree/octave-modules/)

I am still working on getting an octave-packages.nix going in `/pkgs/top-level/` going.

**Comment by doronbehar** [comment]
I also made progress, though with a slightly different approach towards the definition of all packages. In anyway, I think we need https://github.com/NixOS/nixpkgs/pull/106586 in order make the packages get the right arguments if octave is overridden - with the extended passthru defined there - for safer usage of blas, lapack and libraries alike.

**Comment by doronbehar** [comment]
Still an issue.

**Comment by KarlJoad** [comment]
Initial documentation has been merged. If something is lacking, please let me know.

**Comment by doronbehar** [comment]
> Initial documentation has been merged. If something is lacking, please let me know.

This is great! Thanks a lot @KarlJoad for maintaining this!
