### ISSUE TITLE
Updated Realtek wifi codes (rtlwifi_new-extended)

### ISSUE THREAD

**Issue by bloomvdomino** [NixOS/nixpkgs#65435]
**Project description**
The extended branch of the rtlwifi_new project contains a lot of new kernel modules for realtek wifi cards released after 2018!

**Metadata**

* homepage URL: https://github.com/lwfinger/rtlwifi_new/
* source URL: https://github.com/lwfinger/rtlwifi_new/tree/extended
* license: gpl
* platforms: linux

**Comment by teal77** [comment]
```
(linuxPackages.rtlwifi_new.overrideAttrs (oldAttrs: rec {
      src = fetchFromGitHub {
    owner = "lwfinger";
    repo = "rtlwifi_new";
    rev = "83fc4fc1245e672e9dc9240c668175ae09b753d5";
    sha256 = "09pnv2scamlnb80kpj4kfizhb18fs4gp58ld4pxy0png7fcwssvz";
  };
    }))
```

I tried to override src attribute to point to a commit in extended branch. I can see it build the driver I want in logs but the build outputs don't get copied to kernel module dir.

**Comment by teal77** [comment]
```
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = with config.boot.kernelPackages;[ (rtlwifi_new.overrideAttrs (oldAttrs: rec {
      src = pkgs.fetchFromGitHub {
    "owner" = "lwfinger";
    "repo" = "rtlwifi_new";
    "rev" = "e3260995279100d7ec9addc407922ce895a93cea";
    "sha256" = "19hhjzjlwpg3bk4fr3sl0lbrwnn24ccxxfmrrbh0zkhh4ppds05k";
  };
    })) ];

  #optionally set any extra config for your drivers
  boot.extraModprobeConfig = ''
    options rtl8723de ant_sel=2
  '';
```

Solved it. The override I made in general packages list didn't apply to kernel packages. Also I was using `linuxPackages_latest` kernel and the override was for the default kernel.
As the [wiki](https://nixos.wiki/wiki/Linux_kernel#Custom_kernel_modules) says, you need to be careful when using a different kernel.

**Comment by kisik21** [comment]
Well, guess what, the repo was deleted. I was using the repo with my overlay to get the driver for rtl8723de, but now I don't know if it'll work without it. If I don't report in 30 minutes, this means my Wi-Fi card is dead :heart_eyes:

**Comment by teal77** [comment]
Drivers got upstreamed in 5.8 kernel. WiFi now works out of the box.

**Comment by bloomvdomino** [comment]
I think I will keep this packaging request open, as for now not all drivers got upstreamed to rtw88!
