### ISSUE TITLE
mesa: building HEAD w/ changes to libglvnd

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#65441]
This shouldn't be an issue until 19.2, if I had to guess, but since I'm trying to build it, I figued I'd open an issue.

It looks like mesa 19.2 will change how it handles `egl.pc` with regards to `libglvnd`:
* https://gitlab.freedesktop.org/mesa/mesa/commit/1a25980c469b38d2c6456344fe538ad1bcb47f63
* https://github.com/NVIDIA/libglvnd/pull/86

I'm not sure, but I'd guess that libglvnd and mesa will need to update in step, and at least some changes might need to happen with the mesa derivation to handle the lack of `egl.pc`, if that's how it's meant to be built.

**Comment by colemickens** [comment]
Looks like it's as simple as changing a `rm` to `rm -f` in mesa's derivation, though that's a bit of a lazy hammer. I've also had to update `mesa-glu` as well.

**Comment by Artturin** [comment]
mesa is now at 22.1.7
