### ISSUE TITLE
"nix-review wip" fails intermittently

### ISSUE THREAD

**Issue by steshaw** [NixOS/nixpkgs#65459]
**Describe the bug**

The `nix-shell -p nix-review --run 'nix-review wip'`command that is used as part of the pull request process sometimes fails.

**To Reproduce**

1. Create a branch for your change.
2. Run  `nix-shell -p nix-review --run 'nix-review wip'.

**Expected behaviour**

I expect it not to throw an exception intermittently.

I'm new to contributing so I haven't seen the command do anything but throw an exception or seemingly run okay and exit with a 0 exit status.

**Screenshots**

![image](https://user-images.githubusercontent.com/45735/61992228-d9fbf400-b09e-11e9-9ea0-3880080eebe0.png)

Sorry, my `nix-build-dependents` scripts is simply:

```bash
#!/usr/bin/env bash

set -euo pipefail

nix-shell -p nix-review --run 'nix-review wip'
```

**Additional context**

None.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173116.f4fcdac99fa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173116.f4fcdac99fa"`
 - channels(steshaw): `"nixpkgs-19.09pre186574.88d9f776091"`
 - nixpkgs: `/home/steshaw/.nix-defexpr/channels/nixpkgs`

Maintainer information:

- nix-review

**Comment by FRidh** [comment]
cc @Mic92

**Comment by worldofpeace** [comment]
Why is this a nixpkgs issue when it's a problem in https://github.com/Mic92/nix-review/issues ?

**Comment by steshaw** [comment]
@worldofpeace, well I didn't know that it was considered an externally maintained tool. The reason I raised the issue is that it's part of the [pull-request process/template](https://github.com/NixOS/nixpkgs/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by worldofpeace** [comment]
> well I didn't know that it was considered an externally maintained tool. The reason I raised the issue is that its part of the pull-request process/template.

Yeah I think it would be best to transfer the issue there, since the source isn't in this repo.

> Perhaps a note should be added to the pull request template to simply try the command again if there's a Python exception?

I think I might have noticed this occasionally, but I think it's a problem if a program is regularly encountering an exception.

**Comment by steshaw** [comment]
No worries, will raise upstream :+1:

**Comment by Mic92** [comment]
Is it possible that you have committed all changes on your current branch already?

**Comment by Mic92** [comment]
Does `nix-review rev HEAD` work for you?

**Comment by steshaw** [comment]
Hi @Mic92, thanks for following up here. IIRC, I had committed all my changes to the branch I was working on as I was following the advice in the pull request template which says:

> Tested compilation of all pkgs that depend on this change using nix-shell -p nix-review --run "nix-review wip"

I imagine that needs updating to `nix-review rev HEAD`.

I tried `nix-shell -p nix-review --run "nix-review rev HEAD"` on one of my old branches and I'm still getting intermitent failures. It's almost like it toggles between a failed run and a successful one. This time the exception was a little different: "error: cannot lock ref 'refs/nix-review/0': unable to resolve reference 'refs/nix-review/0'". On a second run the output ends with:

```
Nothing changed
No packages were successfully build, skip nix-shell
$ git worktree prune
```

On a third run I got the exception/error: "fatal: Needed a single revision". The fourth run looked okay, with output the same as the 2nd run.

I'm new to contributing to `nixpkgs` so I'm not really sure what the appropriate output of `nix-review` should be. I haven't had the time to raise this upstream yet. I ran the following command to attempt to get the version of the nixpkgs channel that I'm using:

```sh-session
 nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"19.09pre186574.88d9f776091"
```

**Comment by Mic92** [comment]
By `old` branches you mean branches that have been already merged to nixpkgs?
In that cases there would be no package rebuilds.

**Comment by steshaw** [comment]
Yes, I switched to a branch that had already been merged into nixpkgs. Should I do something else?

**Comment by Mic92** [comment]
It does not work in that case because your branch does not change any packages.

**Comment by steshaw** [comment]
Okay, no worries — user error :disappointed:. I'll raise an issue over at https://github.com/Mic92/nix-review/issues if it comes up again when I'm working on another contribution.
