### ISSUE TITLE
Teamspeak crash when open options

### ISSUE THREAD

**Issue by Luraktinus** [NixOS/nixpkgs#65481]
**Describe the bug**
If i open the options, it crashes.

**To Reproduce**
1. open teamspeak (ts3client)
2. open the options

**Expected behavior**
i want to see the options

**TerminalOutput**
'''
QMetaObject::connectSlotsByName: No matching signal for on_queued_open_dialog()
QMetaObject::connectSlotsByName: No matching signal for on_account_created(QString,QString)
QLayout: Attempting to add QLayout "" to ProfileManager "", which already has a layout
QLayout: Attempting to add QLayout "" to ProfileManager "", which already has a layout
QLayout: Attempting to add QLayout "" to ProfileManager "", which already has a layout
[0727/235810.228865:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/lue/#5126273 (deleted)
  Error: No such file or directory
QPaintDevice: Cannot destroy paint device that is being painted
Received signal 11 SEGV_MAPERR 000000000018
Segmentation fault
'''

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.61, NixOS, 19.03.173189.bdebbbe9598 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173189.bdebbbe9598"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Atemu** [comment]
This bug has cropped up from time to time but it's not happening at the minute.
