### ISSUE TITLE
python-packages: Sphinx 1.2.3 - pypy 2.4 & 2.5 - ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by desiderius** [NixOS/nixpkgs#6548]
The package **pypy2.4-Sphinx-1.2.3** appears to be broken in the stable channel (as well as in the master branch of the repository with pypy 2.5).

My config.nix:

    {
        packageOverrides = pkgs: with pkgs; {
            pypySphinxEnv = pkgs.myEnvFun {
            name = "pypySphinx";
            buildInputs = [
                pypy
                pypyPackages.sphinx
                ];
            };
        };
    }

$ load-env-pypySphinx
$ sphinx-quickstart 

    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "/nix/store/9c3qjvkgpn34kvvg0zd3g46bjqdnxyb2-pypy2.4-Sphinx-1.2.3/bin/sphinx-quickstart", line 5, in <module>
    from pkg_resources import load_entry_point
    ImportError: No module named pkg_resources

**Comment by iElectric** [comment]
Interesting, only happens on pypy

**Comment by iElectric** [comment]
Fixed hopefully.

**Comment by desiderius** [comment]
Tested with pypy 2.5. The sphinx-quickstart works and building a non trivial set of documentation also.
Thank you.
