### ISSUE TITLE
`su` causes PAM error: "illegal module type: window=5"

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#6551]
I am experiencing the following PAM errors in my system log when I run `su`:

```
Feb 24 17:27:48 wizylap su[2892]: PAM (su) illegal module type: window=5
Feb 24 17:27:48 wizylap su[2892]: PAM pam_parse: expecting return value; [...usersfile=/etc/users.oath]
Feb 24 17:27:48 wizylap su[2892]: PAM (su) no module name supplied
Feb 24 17:27:48 wizylap su[2892]: PAM (su) illegal module type: window=5
Feb 24 17:27:48 wizylap su[2892]: PAM pam_parse: expecting return value; [...usersfile=/etc/users.oath]
Feb 24 17:27:48 wizylap su[2892]: PAM (su) no module name supplied
```

It seems to have been caused by 4e9990196104eb670d3e5108bde0666575b0f47e

@viric?

**Comment by wizeman** [comment]
BTW, I have **not** set `security.pam.enableOATH = true;` in my config.

**Comment by wizeman** [comment]
Look what happens when I run this:
```
# cat /etc/pam.d/* | grep window
 window=5 usersfile=/etc/users.oath
 window=5 usersfile=/etc/users.oath
 window=5 usersfile=/etc/users.oath
```

It seems to have been a typo in the commit. This should probably fix it:

```diff
-              "auth sufficient ${pkgs.oathToolkit}/lib/security/pam_oath.so"} window=5 usersfile=/etc/users.oath
+              "auth sufficient ${pkgs.oathToolkit}/lib/security/pam_oath.so window=5 usersfile=/etc/users.oath"}
```

**Comment by viric** [comment]
Oops! I pushed a fix.

On Tue, Feb 24, 2015 at 08:46:51AM -0800, Ricardo M. Correia wrote:
> BTW, I have **not** set `security.pam.enableOATH = true;` in my config.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/issues/6551#issuecomment-75793705

-- 
Escriu-me sempre xifrat / Write always ciphered
PGP key D4831A8A - https://emailselfdefense.fsf.org/

**Comment by wizeman** [comment]
The fix works. Thanks!
