### ISSUE TITLE
VBoxClient --clipboard terminates silently

### ISSUE THREAD

**Issue by RumataEstor** [NixOS/nixpkgs#65542]
**Describe the bug**
I'm running NixOS as a VirtualBox guest on Windows 10. Around a week ago I think I upgraded NixOS and also VirtualBox to version 6.0.10. Can't say for sure which of those caused the issue in the subject but it results in no clipboard integration between the guest and host systems.

**To Reproduce**
Hopefully it's reproducible with:
VirtualBox 6.0.10 r132072
NixOS channel manifest [ { meta = { }; name = "nixos-19.09pre186563.b5f5c97f7d6"; out = { outPath = "/nix/store/lzl6l2kg3ary8nmsdspsfyfqibz47k98-nixos-19.09pre186563.b5f5c97f7d6"; }; outPath = "/nix/store/lzl6l2kg3ary8nmsdspsfyfqibz47k98-nixos-19.09pre186563.b5f5c97f7d6"; outputs = [ "out" ]; system = "x86_64-linux"; type = "derivation"; } ]

Execute "VBoxClient --clipboard -d; echo $?" and see it terminates immediately with success.

**Expected behavior**
The "VBoxClient --clipboard" must not terminate but should stay and process clipboard events.

**Additional context**

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.60, NixOS, 19.09pre186563.b5f5c97f7d6 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre186563.b5f5c97f7d6"`
 - channels(rumata): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WhittlesJr** [comment]
Same problem here. I noticed that I also have duplicate VBoxClient processes running with --display, --seamless, and --draganddrop. I think there's supposed to only be one of each...

**Comment by WhittlesJr** [comment]
This has been broken for me for a long time actually

**Comment by PierreR** [comment]
Same problem after trying  [19.09](https://releases.nixos.org/nixos/unstable/nixos-19.09pre191505.7d5375ebf4c/nixos-minimal-19.09pre191505.7d5375ebf4c-x86_64-linux.iso).

Clipboard integration is not working in current19.09 (quite a big deal for me).

**Comment by zimbatm** [comment]
Have you tried to search the upstream bug-tracker yet? VirtualBox is not necessarily the most stable software in my experience.

**Comment by zimbatm** [comment]
The nixos module is executing `"${config.boot.kernelPackages.virtualboxGuestAdditions}/bin/VBoxClient-all`. Maybe try to kill all the VBoxClient processes, run that command directly and report the outputs?

**Comment by flokli** [comment]
I cannot really debug this. My desktop manager isn't GNOME/KDE, and the clipboard used in my setup probably never worked.

cc @ambrop72, maybe he can reproduce.

**Comment by ambrop72** [comment]
I don't use NixOS as a guest but I'll try to reproduce with a NixOS VM that I have for occasional testing of such things.

**Comment by ambrop72** [comment]
Yeah it does not work. Using strace reveals that it's because it can't find `libXfixes`. Submitted https://github.com/NixOS/nixpkgs/pull/69306 to fix it.

**Comment by PierreR** [comment]
@ambrop72 Thanks so much for taking the time to fix this issue. 

Is there something to do to ensure it is integrated in `19.09` ?

**Comment by flokli** [comment]
I already backported this to 19.09 in https://github.com/NixOS/nixpkgs/pull/69306#issuecomment-534912599.
