### ISSUE TITLE
Jenkins plugins should be copied as .jpi

### ISSUE THREAD

**Issue by WhittlesJr** [NixOS/nixpkgs#65580]
**Describe the bug**
Jenkins seems to want its packages in `.jpi` format, which is purely a rename from `.hpi`. See https://issues.jenkins-ci.org/browse/JENKINS-54466. 

I tried adding plugins straight from `jenkinsPlugins2nix`, and while all of them are downloaded *and copied over to JENKINS_HOME*  as `.hpi`, some of them at some point got mysteriously renamed to `.jpi`. It is these packages that fail to initialize, usually with permissions-related issues, and cause my jenkins service to never come up. 

I tried changing `.hpi` to `.jpi` [here](https://github.com/NixOS/nixpkgs/blob/dbb5044408347e3b69dfdea7ffe29f5f62a650fe/nixos/modules/services/continuous-integration/jenkins/default.nix#L196), and lo and behold everything suddenly worked! The plugins and the jenkins service all come up nicely.

Is that safe? Should I create a PR, or would someone else like to make that change?

**To Reproduce**
1. Add the following config:
```nix
{
  services.jenkins = {
    enable = true;
    plugins = (import ./jenkinsPlugins.nix {inherit (pkgs) fetchurl stdenv;});
  };
}
```
2. Add [this](https://pastebin.com/AUHUaNuQ) as `jenkinsPlugins.nix`
3. `nixos-rebuild switch`

**Expected behavior**
Jenkins comes up with the given plugins

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.09.git.bf39fc1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  - services.jenkins.plugins
```

**Comment by coreyoconnor** [comment]
This is safe. The extension is indeed a rename and jenkins should load either `jpi` or `hpi` equivalently. It is odd that you ran into an issue tho. Any particular plugins?

For reference, jenkins normalizes to `jpi` when copying:

* https://github.com/jenkinsci/jenkins/blob/701d00c9ed7dec35147cee1ea3ac50fe57b5b721/core/src/main/java/hudson/PluginManager.java#L1039
