### ISSUE TITLE
Handle Hydra evaluation errors gracefully

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#6561]
Currently there are two problems that occur if a package fails to evaluate (on purpose):

a) "broken" or "disabled" package is not propagated to reverse dependencies. If a package A depends on package B and B is marked as broken/disabled,
package A will still be evaluate-able and will result in an evaluation error

b) evaluation errors spams the hydra error tab page

---

Proposal to fix b)
- provide high-level `throw` function that prefixes the error message with something that will indicate the error is supposed to happen
- document the function
- make sure Python and meta.broken uses it
- handle such errors in `pkgs/top-level/release-lib.nix` by regexing them out from the output

Previous discussions:
- http://lists.science.uu.nl/pipermail/nix-dev/2015-February/016381.html
- https://github.com/NixOS/nixpkgs/commit/b653e3f6614fbe2664b1fd09d3baf5222b4de7f2

**Comment by zimbatm** [comment]
It's still an issue right ?

**Comment by joachifm** [comment]
Looks like it

**Comment by zimbatm** [comment]
It's not the same but similar to https://github.com/madjar/nox/issues/40. It would be nice to have a function that filters out all the invalid builds recursively from a set.

**Comment by Profpatsch** [comment]
@domenkozar iirc this discussion moved to other issues, would it bother you closing this instance?
