### ISSUE TITLE
haskell-cuda cannot find cuda headers.

### ISSUE THREAD

**Issue by sheganinans** [NixOS/nixpkgs#6562]
checking for cuda.h... no
configure: error: could not find CUDA headers
********************************************************************************

The configuration process failed to locate your CUDA installation. Ensure that
you have installed both the developer driver and toolkit, available from:

  http://developer.nvidia.com/cuda-downloads

and make sure that "nvcc" is available in your PATH. Check the above output log
and run the command directly to ensure it can be located.

If you have a non-standard installation, you can add additional search paths
using --extra-include-dirs and --extra-lib-dirs. Note that 64-bit Linux flavours
often require both "lib64" and "lib" library paths, in that order.

********************************************************************************
builder for ‘/nix/store/5avwz2kvlws6xzrbb7h8djjnci4qbqcj-haskell-cuda-0.6.5.1.drv’ failed

~~~

Attempted to fix this with nix-shell -p cudatoolkit6, but no help. Using haskellngPackages.

**Comment by peti** [comment]
This error occurs because http://hackage.haskell.org/package/cuda/ doesn't specify a dependency on the these system headers / libraries in its cabal file. As a result, the necessary packages aren't included in the build environment. IMHO, this is a bug that should be fixed upstream.

Anyway, I'll commit a work-around for Nix momentarily.

**Comment by sheganinans** [comment]
Perfect! Worked first try! Thanks!

**Comment by sheganinans** [comment]
Really quickly, I was wondering how it could access this in ghci or cabal repl after I install it with nix-env -f -iA haskellngPackages.accelerate-cuda?

**Comment by peti** [comment]
Please have a look at the "A Journey into the Haskell NG infrastructure" documents from https://github.com/NixOS/nixpkgs/issues/4941. There's further material there that you may find interesting. If in doubt, the best place to ask for help is the `#nixos` IRC channel on freenode and/or the [nix-dev](http://lists.science.uu.nl/mailman/listinfo/nix-dev) mailing list.

**Comment by sheganinans** [comment]
Peti, thank you so much! I'm in the #nixos channel right now, you can probably see me asking questions! :)

**Comment by sboosali** [comment]
btw, can nixpkgs automatically create the right nix file for a package if its cabal file (via cabal2nix?) lists the c libs? If this is still being worked around manually, I can file a ticket. 

I glanced at

http://hackage.haskell.org/package/cuda-0.9.0.0/src/cuda.cabal

And it doesn't seem to mention any cuda Libraries / headers.

**Comment by peti** [comment]
> Can [cabal2nix] automatically create the right nix file for a package if its cabal file lists the c libs? 

Yes. The cuda package is a special case, unfortunately, because the system headers live in a non-standard location, so the needs special patching anyhow.
