### ISSUE TITLE
Jupyterlab 1.0.4 fails to build, citing missing `tornado` version which exists 

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#65625]
**Describe the bug**

When trying to install the latest version of jupyterlab, nix fails, complaining about a missing library `tornado`, so long as it isn't 6.0 or above. Yet `tornado` installs just fine, and with a version of 5.X. Here's the error: 

```
/build/jupyterlab-1.0.4/dist /build/jupyterlab-1.0.4
Processing ./jupyterlab-1.0.4-py2.py3-none-any.whl
Collecting tornado!=6.0.0,!=6.0.1,!=6.0.2 (from jupyterlab==1.0.4)
  Could not find a version that satisfies the requirement tornado!=6.0.0,!=6.0.1,!=6.0.2 (from jupyterlab==1.0.4) (from versions: )
No matching distribution found for tornado!=6.0.0,!=6.0.1,!=6.0.2 (from jupyterlab==1.0.4)
builder for '/nix/store/bigclz0i9ld7dxj33vw1c8kyiwdrimjd-python3.7-jupyterlab-1.0.4.drv' failed with exit code 1
cannot build derivation '/nix/store/9vk437k3q0w79r1f6phxwhcap083j813-python3-3.7.3-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/9vk437k3q0w79r1f6phxwhcap083j813-python3-3.7.3-env.drv' failed

```

**To Reproduce**

1. Try to run `nix-shell` with this file: 

```
with import <nixpkgs> {};

( let
    my_jupyterlab = python37.pkgs.buildPythonPackage rec {
      pname = "jupyterlab";
      version = "1.0.4";

      src = python37.pkgs.fetchPypi {
        inherit pname version;
        sha256 = "0vhdbzrphirl3x37d4zh0gaxhs6f7wj0i30wy4878yjkmlr219rj";
      };

      doCheck = false;
    };

  in python37.withPackages (ps: [ps.jupyter ps.tornado my_jupyterlab])
).env

```
2. Note that it fails with the error above. 

**Expected behavior**
It would finish building the environment with Jupyterlab 1.0.4

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.4, NixOS, 19.09pre186857.239fffc90d7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(jon): `"home-manager, nixpkgs"`
 - channels(root): `"nixos-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - python37Packages.jupyterlab
# a list of nixos modules affected by the problem
module:
```

**Comment by JonathanReeve** [comment]
Related to #65586

**Comment by veprbl** [comment]
@JonathanReeve Your expression for jupyterlab is incomplete. `jupyterlab` expression in nixpkgs depends on `tornado` via `notebook`.

**Comment by JonathanReeve** [comment]
@veprbl Do you know how I can do that? I tried adding `  propagatedBuildInputs = [ jupyterlab_server notebook ];` but I get: `error: undefined variable 'jupyterlab_server' ...`

I think I have to import that variable somehow, but I don't know how.

**Comment by veprbl** [comment]
@JonathanReeve You should be able to access those as `python37.pkgs.jupyterlab_server` and `python37.pkgs.notebook`. Or can omit the full path if you prefix your expression with `with python37.pkgs;`.

**Comment by JonathanReeve** [comment]
@veprbl, Great, that seems to help. But it still fails with this error: 

```
  Could not find a version that satisfies the requirement jupyterlab-server~=1.0.0 (from jupyterlab==1.0.4) (from versions: )
No matching distribution found for jupyterlab-server~=1.0.0 (from jupyterlab==1.0.4)

```

**Comment by veprbl** [comment]
@JonathanReeve This should mean that you need an appropriate version of jupyterlab-server as well. We now have:
https://github.com/NixOS/nixpkgs/blob/525eaf407d4edb329ea48f6dc9c6590fb73c779a/pkgs/development/python-modules/jupyterlab_server/default.nix#L12-L13

FYI: There is another attempt at updating jupyterlab to 1.0.4 in #65824 . Turns out, we need to also update the `jsonschema` package.

**Comment by JonathanReeve** [comment]
@veprbl, Great, it looks like I'm getting closer. I now have: 

```
with import <nixpkgs> {};

(let
    my_jupyterlab = python37.pkgs.buildPythonPackage rec {
      pname = "jupyterlab";
      version = "1.0.4";

      src = python37.pkgs.fetchPypi {
        inherit pname version;
        sha256 = "0vhdbzrphirl3x37d4zh0gaxhs6f7wj0i30wy4878yjkmlr219rj";
      };

      propagatedBuildInputs = with python37.pkgs; [ notebook ];
      doCheck = false;
    };
    my_jupyterlab_server = python37.pkgs.buildPythonPackage rec {
      pname = "jupyterlab_server";
      version = "1.0.0";
      src = python37.pkgs.fetchPypi {
        inherit pname version;
        sha256 = "06hsyk0nrikcmqgv3l29bhgdmvdls1d9bfdwnl1pvxwkizp66zm7";
      };
      propagatedBuildInputs = with python37.pkgs; [ notebook jsonschema ];
    };

  in python37.withPackages (ps: [ps.jupyter ps.tornado my_jupyterlab_server my_jupyterlab])
).env

```

Although now it complains that it doesn't have a `json5` package, but I can't find that in nixpkgs. Any ideas about how to proceed from here?

**Comment by veprbl** [comment]
@JonathanReeve 
It might be a new dependency, so you might need to package it yourself. Just define it the same way with `buildPythonPackage`.

**Comment by JonathanReeve** [comment]
@veprbl Ah cool. This is what I have so far: 

https://gist.github.com/JonathanReeve/f8168baf2e9415c3536a73affa7528b7 

But it seems like it's still failing, citing a missing `setuptools_scm`: 

```
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
builder for '/nix/store/5c17w7jv4ia1an0jm7i2i38h6pi9mqfx-python3.7-jsonschema-3.0.2.drv' failed with exit code 1
```
I tried adding that as a dependency everywhere I could think to. Should that be build separately, too?

**Comment by veprbl** [comment]
There are couple minor issues with your current gist. There is a typo in definition of `my_jsonschema`: `propogatedBuildInputs` should read `propagatedBuildInputs` instead. There is also some problem with build inputs order. You need to understand that in most of the cases the dependencies of a python packages need to be present already at the time the package is being built. For instance `my_jupyterlab` will require `my_jupyterlab_server`, so it should include it in its `propagatedBuildInputs`. Including both packages in `python37.withPackages` is not effective because the build of `my_jupyterlab` derivation will fail before you can build derivation returned by the `python37.withPackages` function.

There were some other minor problems with your definition. I decided it would be simpler and more robust to turn your expressions into a nixpkgs overlay:
```nix
self: super:

let
  pythonOverrides = python-self: python-super: {

    jupyterlab = python-super.jupyterlab.overrideAttrs (old: rec {
      name = "${pname}-${version}";
      pname = "jupyterlab";
      version = "1.0.4";

      src = python-super.fetchPypi {
        inherit pname version;
        sha256 = "0vhdbzrphirl3x37d4zh0gaxhs6f7wj0i30wy4878yjkmlr219rj";
      };
    });

    jupyterlab_server = python-super.jupyterlab_server.overrideAttrs (old: rec {
      name = "${pname}-${version}";
      pname = "jupyterlab_server";
      version = "1.0.0";

      src = python-super.fetchPypi {
        inherit pname version;
        sha256 = "06hsyk0nrikcmqgv3l29bhgdmvdls1d9bfdwnl1pvxwkizp66zm7";
      };

      propagatedBuildInputs = old.propagatedBuildInputs ++ (with python-self; [ json5 ]);
    });

    json5 = python-super.buildPythonPackage rec {
      pname = "json5";
      version = "0.8.5";

      src = python-super.fetchPypi {
        inherit pname version;
        sha256 = "1c3k5blbhq7g2lnbap26a846ag5x19ivisd3wfzz6bzdl46hyjqj";
      };

      doCheck = false;
    };

    jsonschema = python-super.buildPythonPackage rec {
      pname = "jsonschema";
      version = "3.0.2";

      src = python-super.fetchPypi {
        inherit pname version;
        sha256 = "03anb4ljl624lixrsaxfi7i1iwavw39sd8cfkhcy0dr2dixjnjld";
      };

      propagatedBuildInputs = with python-self; [ attrs pyrsistent setuptools_scm ];
      doCheck = false;
    };

  };
in
  {
    python3 = super.python3.override { packageOverrides = pythonOverrides; };
    python3Packages = self.python3.pkgs;
    python37 = super.python37.override { packageOverrides = pythonOverrides; };
    python37Packages = self.python37.pkgs;
  }
```
This one seems to provide a working jupyterlab 1.0.4

**Comment by JonathanReeve** [comment]
@veprbl, Thanks for that. Although I can't get it to work. I saved it as jupyterlab.nix, and put it in ~/.config/nixpkgs/overlays/, after creating that folder, but when I rebuild my system, nothing seems to be different; jupyterlab is still the same old version. Am I doing something wrong?

**Comment by JonathanReeve** [comment]
Ok, I'm starting to figure this out. I added the path to that overlay to my configuration.nix, in the option nixpkgs.overlays, but when it builds it gives me this error: 

```
ERROR: No matching distribution found for jsonschema~=2.6 (from aws-sam-translator==1.11.0)
builder for '/nix/store/6kavds28mhh453923xy3097j511q6lyi-python3.7-aws-sam-translator-1.11.0.drv' failed with exit code 1
cannot build derivation '/nix/store/h6j2j1saxrz7pwk649x1wj66321jh0nm-python3.7-cfn-lint-0.19.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fr8lyy4rdczrzlsvwhfxszql9gnchlc0-python3.7-moto-1.3.10.drv': 1 dependencies couldn't be built
```

**Comment by averelld** [comment]
Looks similar to the problem here: https://github.com/NixOS/nixpkgs/pull/65824#issuecomment-517885153 which is probably why the nixpkgs jupyterlab is stuck at a pre-1.0 version.

**Comment by veprbl** [comment]
Yes, the bump of jsonschema might not be compatible with the rest of the system. But you still should be able to run just the jupyterlab from overlay in isolated environment (like with nix-shell).

E.g. you can always import a copy of nixpkgs with a certain set of overlays:
```nix
(import <nixpkgs> { overlays = [ (import ./myoverlay.nix) ]; }).python3Packages.jupyterlab
```

**Comment by evanjs** [comment]
I was able to get the overlay provided by @veprbl working... though I had to install it from the repl (`:i`)
In addition, when evaluating from the repl, it seemed to only be accessible from `python37.pkgs` and not `python37Packages`
Any thoughts on why this is the case, and why the packages in the overlay might not have propagated?
[Here](https://github.com/evanjs/nixos_cfg/commit/a7813beb3019bc39fcd6e2738342a876f9aabb0a) is my overlay setup

**Comment by FRidh** [comment]
1.2.2 is in master https://github.com/NixOS/nixpkgs/commit/4eed2a56e6a512b184bb614ebfd26658ed11eef4
