### ISSUE TITLE
Anki fails to launch with "No module named 'PyQt5.QtWebEngineWidgets'"

### ISSUE THREAD

**Issue by ivan-timokhin** [NixOS/nixpkgs#65623]
**Describe the bug**
Attempting to run anki installed from the latest unstable fails with
```
Traceback (most recent call last):
  File "/nix/store/97mg8zflvngmnxvbiv9habr82njn2w8a-anki-2.1.11/bin/..anki-wrapped-wrapped", line 4, in <module>
    import aqt
  File "/nix/store/97mg8zflvngmnxvbiv9habr82njn2w8a-anki-2.1.11/lib/python3.7/site-packages/aqt/__init__.py", line 14, in <module>
    from aqt.qt import *
  File "/nix/store/97mg8zflvngmnxvbiv9habr82njn2w8a-anki-2.1.11/lib/python3.7/site-packages/aqt/qt.py", line 17, in <module>
    from PyQt5.QtWebEngineWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

**To Reproduce**
```
nix-shell --pure -p "(import <nixpkgs-unstable> {}).anki" --command anki
```
(depends on channel naming, I suppose)

**Expected behavior**
Anki launches successfully

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.03.173202.31d476b8797 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173202.31d476b8797"`
 - channels(ivan): `"nixpkgs-unstable-19.09pre186574.88d9f776091"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: anki
# a list of nixos modules affected by the problem
module:
```

**Comment by timokau** [comment]
CC maintainers @the-kenny, @Profpatsch, @Enzime

**Comment by timokau** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/33a876e61955e641bd805b187bf164df60e15644.

**Comment by timokau** [comment]
... only to be apparently replaced by https://github.com/NixOS/nixpkgs/issues/65399, although at least now it works when launched with

```
nix-shell -I nixpkgs=. -p qt5Full -p anki --run anki
```

**Comment by timokau** [comment]
Will be resolved by https://github.com/NixOS/nixpkgs/pull/66796.
