### ISSUE TITLE
fwupd: Can't find efibootmgr

### ISSUE THREAD

**Issue by baracoder** [NixOS/nixpkgs#65658]
**Describe the bug**

As I am trying to upgrade my XPS 13, fwupd can't find `efibootmgr`
```
Failed to execute child process “efibootmgr” (No such file or directory)
```

**To Reproduce**

```
# fwupdmgr update
Downloading 0.1.5.0 for XPS 13 9380 System Firmware...
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Updating XPS 13 9380 System Firmware…                            ]
Scheduling…              [***************************************]
Failed to execute child process “efibootmgr” (No such file or directory)
```

**Expected behavior**
Update completes

**Additional context**
I am using nixos-unstable

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.0, NixOS, 19.09pre185259.362be9608c3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre186460.c4fec1c6314, nixos-19.03-19.03.173182.96151a48dd6, nixos-unstable-19.09pre186460.c4fec1c6314"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Looking back at this patch
* https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/firmware/fwupd/fix-paths.patch#L42

that's probably not right.

Probably all calls to `fu_common_find_program_in_path` need to be removed and it should just
be a string to the executable.

**Comment by tadfisher** [comment]
If we're already wrapping the executables with `wrapProgram`, why not set the `PATH` instead of patching?
