### ISSUE TITLE
nylas-mail is broken (and should be replaced by mailspring)

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#65657]
**Describe the bug**
The `nylas-mail-bin` package does not work anymore<sup>1</sup> as nylas-mail has been [abandoned](https://github.com/nylas/nylas-mail/blob/master/README.md)<sup>2</sup> by the developers in favor of [Mailspring](https://getmailspring.com/).

1. > Could not reach https://billing.nylas.com/onboarding?utm_medium=N1&utm_source=OnboardingPage&N1_version=2.0.32&client_edition=basic. The server's response was insecure (e.g. there was a cert error).
2. > :warning: Nylas Mail was initially released and open-sourced in early 2015 and was maintained by Nylas until Spring 2017. While Nylas no longer supports Nylas Mail, you can download the latest release or build it from source. There are also several forks that are being actively developed and maintained.

**To Reproduce**
1. Install and run `nylas-mail-bin`, observe that clicking through the dialogs eventually results in reported error

**Expected behavior**
A working mail client.

**Screenshots**
![Screenshot_20190731_092059](https://user-images.githubusercontent.com/7755101/62215227-888c8700-b374-11e9-8659-fcb92e1b40e6.png)

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173165.55b8860aa20 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173165.55b8860aa20, nixos-unstable-19.09pre185259.362be9608c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nylas-mail-bin
# a list of nixos modules affected by the problem
module: nylas-mail
```

@johnramsden Do you have any interest in replacing this package/module with Mailspring?

**Comment by johnramsden** [comment]
I'm afraid I don't have a Nix system up and running, nor am I using mailspring. It might be best for someone else to take on the package who is actively using it, or for it to be dropped completely If there's no interest.
