### ISSUE TITLE
Firefox tries to set itself as a default browser on every run

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#65679]
Firefox is run with `GTK_USE_PORTAL=0`.

Console output:

```
Extension error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/formautofill@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) resource://gre/modules/Extension.jsm:466 :: readJSON/</<@resource://gre/modules/Extension.jsm:466:18
onStopRequest@resource://gre/modules/NetUtil.jsm:123:17

1564594967521	addons.xpi	WARN	Exception running bootstrap method startup on formautofill@mozilla.org: Error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/formautofill@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:466:18) JS Stack trace: readJSON/</<@Extension.jsm:466:18
onStopRequest@NetUtil.jsm:123:17
Extension error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/fxmonitor@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) resource://gre/modules/Extension.jsm:466 :: readJSON/</<@resource://gre/modules/Extension.jsm:466:18
onStopRequest@resource://gre/modules/NetUtil.jsm:123:17

1564594967524	addons.xpi	WARN	Exception running bootstrap method startup on fxmonitor@mozilla.org: Error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/fxmonitor@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:466:18) JS Stack trace: readJSON/</<@Extension.jsm:466:18
onStopRequest@NetUtil.jsm:123:17
Extension error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/screenshots@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) resource://gre/modules/Extension.jsm:466 :: readJSON/</<@resource://gre/modules/Extension.jsm:466:18
onStopRequest@resource://gre/modules/NetUtil.jsm:123:17

1564594967527	addons.xpi	WARN	Exception running bootstrap method startup on screenshots@mozilla.org: Error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/screenshots@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:466:18) JS Stack trace: readJSON/</<@Extension.jsm:466:18
onStopRequest@NetUtil.jsm:123:17
Extension error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) resource://gre/modules/Extension.jsm:466 :: readJSON/</<@resource://gre/modules/Extension.jsm:466:18
onStopRequest@resource://gre/modules/NetUtil.jsm:123:17

1564594967529	addons.xpi	WARN	Exception running bootstrap method startup on webcompat-reporter@mozilla.org: Error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:466:18) JS Stack trace: readJSON/</<@Extension.jsm:466:18
onStopRequest@NetUtil.jsm:123:17
Extension error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/webcompat@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) resource://gre/modules/Extension.jsm:466 :: readJSON/</<@resource://gre/modules/Extension.jsm:466:18
onStopRequest@resource://gre/modules/NetUtil.jsm:123:17

1564594967531	addons.xpi	WARN	Exception running bootstrap method startup on webcompat@mozilla.org: Error: Error while loading 'jar:file:///nix/store/wflrb79xhkl5gx7sxm9si3bpf48k0dbq-firefox-unwrapped-67.0/lib/firefox/browser/features/webcompat@mozilla.org.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:466:18) JS Stack trace: readJSON/</<@Extension.jsm:466:18
onStopRequest@NetUtil.jsm:123:17
```

**Comment by worldofpeace** [comment]
Disabling it asking this should quiet the issue until it's resolved.
I can confirm that the associations are at least correct.

**Comment by gloaming** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1516290

**Comment by worldofpeace** [comment]
So I guess they should be doing the same as for snap?
* https://dxr.mozilla.org/mozilla-central/rev/cb5734727c0a9d88e3e236a3e4a741a051509e0e/browser/components/shell/nsGNOMEShellService.cpp#188

In this case, I noticed that doing
```
optional cfg.gtkUsePortal "1";
```

will still return an empty list so it ends up doing
```
export GTK_USE_PORTAL=
```

By using `lib.mkIf` we can prevent that.

**Comment by gloaming** [comment]
I don't think that's quite it. There seems to be a fundamental confusion; the [flatpak docs say](http://docs.flatpak.org/en/latest/desktop-integration.html#portals) that:
> Portals are the framework for securely accessing resources from outside an application sandbox.

But of course you don't need to be running in a sandbox to use the functionality they provide. Yet firefox is using the presence of `GTK_USE_PORTAL` to determine if the application is running in a flatpak container. This isn't going to work if people use portals for other reasons.

What they _should_ be doing, I think, is the same as for snap, if the program is running [in a flatpak](https://dxr.mozilla.org/mozilla-central/rev/5f8aeb02af2259acfceed9e1abe987849fbb67ca/toolkit/system/gnome/nsGIOService.cpp#31-32).

They probably also need a more fine-grained way to instruct firefox to use a portal for the file chooser without affecting other functionality:
> Setting GTK_USER_PORTAL=1 [sic] to get KDE native dialog is generally not a good idea. The GTK_USER_PORTAL variable is used to detect if the app runs as a flatpak and that means it cannot use the native print dialog and look for mimetype handlers in Firefox.

(Here's why it doesn't actually check the value of GTK_USE_PORTAL:
https://dxr.mozilla.org/mozilla-central/rev/5f8aeb02af2259acfceed9e1abe987849fbb67ca/toolkit/system/gnome/nsGIOService.cpp#35)

**Comment by worldofpeace** [comment]
`GTK_USE_PORTAL` isn't a value that modifies any functionality within firefox.
It's in gdk
* https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/gdk.c#L497

**Comment by worldofpeace** [comment]
> I don't think that's quite it.

That doesn't fix the issue in firefox, in the report this behavior was triggered even if the variable was set in the environment. And in general that probably shouldn't be happening so I fixed that.

**Comment by gloaming** [comment]
Not sure what you mean, but I wasn't disagreeing with the `mkIf` thing, just bouncing ideas about how Firefox could improve their behaviour. I'll take the suggestions upstream if I find the time.

**Comment by jbaum98** [comment]
I still have this issue. Is there a workaround?

**Comment by starcraft66** [comment]
I am experiencing this issue atm. Every link I click tries to open in firefox but ends up doing nothing and firefox prompts me to set it as the default browser on every run.

**Comment by Congee** [comment]
Also have this issue after setting `xdg.portal.gtkUsePortal = true;` for firefox-wayland

**Comment by aciceri** [comment]
Stupid workaround for lazy home-manager users:
add `"browser.shell.checkDefaultBrowser" = false;` to `programs.firefox.profiles.<name>.settings`.

**Comment by TLATER** [comment]
This is an upstream bug that was linked to earlier in the thread, right? Do we need to track that bug downstream?
