### ISSUE TITLE
fcitx-qt5 fails to build on stable

### ISSUE THREAD

**Issue by nezumi1503** [NixOS/nixpkgs#65716]
fcitx-qt5 fails to build on stable, similarly to bug #65547 . Solution by @worldofpeace will probably work. See the attached file ([fcitx-build.log](https://github.com/NixOS/nixpkgs/files/3456022/fcitx-build.log)) for a tail snippet of the build log.
Note that I have a following setting in configuration.nix:
`environment.extraOutputsToInstall = ["out"]; environment.pathsToLink = [ "/share/locale" ];`

**Comment by worldofpeace** [comment]
It seems to have popped up again on master, needed a further fix
* https://github.com/NixOS/nixpkgs/pull/65571#issuecomment-518231834

**Comment by gebner** [comment]
Oops, did not mean to close this issue.

@nezumi1503 Can you clarify what you mean by "stable"?  `fcitx-qt5` builds fine for me on the `release-19.03` branch.

**Comment by JohnAZoidberg** [comment]
Doesn't build for me on the latest unstable 52f3c28df2300c60ca015fc39d48c10f09b8c5ef

**Comment by nezumi1503** [comment]
@gebner Please find my [configuration.nix](https://github.com/NixOS/nixpkgs/files/3488742/configuration.nix.txt) and additional files [emacs.nix](https://github.com/NixOS/nixpkgs/files/3488744/emacs.nix.txt) and [python.nix](https://github.com/NixOS/nixpkgs/files/3488745/python.nix.txt) (with the most of the options unchanged) attached. It could be that printer drivers that I pull from the unstable channel introduce some dependencies that cause the bug. I managed installing fcitx on another computer without problems, indeed.

**Comment by nezumi1503** [comment]
@gebner So I removed the nixos-unstable lines, installed printer drivers from stable, removed the unstable channel, did garbage collection and did ` nixos-rebuild --upgrade switch` and still it fails building. If I remove the fcitx.engine like this:
    inputMethod = {
                 enabled = "fcitx";
\#                 fcitx.engines = with pkgs.fcitx-engines; [ hangul ];
                  };
Upgrade proceeds without issues but as soon as I uncomment it, it fails.

**Comment by JohnAZoidberg** [comment]
Can you please provide the logs of `nixos-rebuild`?

**Comment by nezumi1503** [comment]
@JohnAZoidberg , I am sorry, I tried, but suddenly it builds without failure. I did not keep the whole log from before. As far as I remember, it used to pull fcitx from unstable (even though I do not remember specifying so) so that was the issue, maybe. I was stupid not to save the log. Now I have a working system so I would prefer not to examine sources of the error any more, sorry.
