### ISSUE TITLE
backintime: can't choose udev schedule

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#6572]
Trying to choose the schedule option 'when drive get connected (udev)' backintime is trying to create udev rules under /etc:

```
Automatic backup: When drive get connected (udev)
cp: cannot create regular file ‘/etc/udev/rules.d/99-backintime-root.rules’: Read-only file system
Command "cp "/tmp/tmp4lwwhqcc" "/etc/udev/rules.d/99-backintime-root.rules"" returns 256
```

**Comment by lethalman** [comment]
I believe dynamic udev rules should be added to `/run/udev/rules.d`, or something like that.

**Comment by joelmo** [comment]
Files I put there disappear when I reboot, it may be hard to fix but wouldn't it be good if those files was saved to the current profile?

**Comment by joelmo** [comment]
Closing this because it's old. Haven't checked if it works at current unstable.
