### ISSUE TITLE
Pueue

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#65723]
**Project description**
Pueue is a command line queue management tool for sequential and parallel execution of long running tasks.

![](https://raw.githubusercontent.com/Nukesor/images/master/pueue.png)

**Installation Vector**

This package is conventionally installed through `pip install pueue` or `python setup.py install`, so it should be packaged like other Python programs. 

**Metadata**

* homepage URL: https://github.com/Nukesor/pueue
* source URL: https://github.com/Nukesor/pueue
* license: MIT
* platforms: Unix

**Comment by Nukesor** [comment]
Hey. Maintainer from pueue.
Pueue has been rewritten in Rust. It can now easily be deployed via binary or clean installed via cargo.

**Comment by matthew-piziak** [comment]
Hi @Nukesor, great to hear from you! And it's nice to hear that Pueue has been rewritten in Rust. It would be easier to package if it had an upstream `Cargo.lock` file. Would you be willing to provide one?

**Comment by Nukesor** [comment]
Hey @matthew-piziak 
Sorry for the delay, I wanted to release a new version that fixes some things before pinging you.

Cargo.lock is added.

**Comment by matthew-piziak** [comment]
Wow, thanks @Nukesor, much appreciated.

Here's the expression I'm using:
```nix
pueue = pkgs.rustPlatform.buildRustPackage rec {
  pname = "pueue";
  version = "0.1.2";
  src = pkgs.fetchFromGitHub {
    owner = "Nukesor";
    repo = "pueue";
    rev = "b0f7015b155a03d961c30e484476f3fc23f256db";
    sha256 = "0hp5ri8mcvbmnwprsfqwprr31xv0qpd0ack96zs3nj0lf2l14g2p";
  };
  cargoSha256 = "1idjl1qlln5db1fs4dpsisymsxfz2s7qgzc0pkx8i6y415nvvwaw";
  verifyCargoDeps = true;
  meta = with pkgs.stdenv.lib; {
    description =
      "A command-line task management tool for sequential and parallel execution of long-running tasks.";
    homepage = "https://github.com/Nukesor/pueue";
    license = licenses.mit;
    platforms = platforms.unix;
  };
};
```

When I build it I get a build failure in the `bytes` dependency of all things:
```
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /build/pueue-0.1.2-vendor/bytes/src/bytes.rs:130:18
    |
130 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It looks like `pueue` CI is red for this build too, but for a different reason: [build #81](https://travis-ci.org/nukesor/pueue/builds/625977667)

**Comment by Nukesor** [comment]
Travis' pipeline failed on the old python version :D Totally forgot this still existed.
The Github Actions pipeline is working for both rust stable and nightly (just added a badge to the Readme)

I just looked at the Nixpkg rust section and it looks like there is an option to set the Rust version:
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#controlling-rust-version-inside-nix-shell

Stable should do just fine.

Thanks for packaging this to NixOs. I'm kind of honored :)

**Comment by matthew-piziak** [comment]
Aha, I just used `pkgs.unstable.rustPlatform` so that I got the `unstable` channel instead of NixOS 19.09. This works!
```
pueue = pkgs.unstable.rustPlatform.buildRustPackage rec {
  pname = "pueue";
  version = "0.1.3";
  src = pkgs.fetchFromGitHub {
    owner = "Nukesor";
    repo = "pueue";
    rev = "0e22b660c90a5ab83613af1166c94ce0b457f044";
    sha256 = "1665jcibq5kpz6prmk26zj9w0rb3zw9rlrzml0vmqys121x55phs";
  };
  cargoSha256 = "1gjamwxvr6hfv4iija16k1f9cw6jmry833p4fhq4gshz2kb6bbmh";
  verifyCargoDeps = true;
  meta = with pkgs.stdenv.lib; {
    description =
      "A command-line task management tool for sequential and parallel execution of long-running tasks.";
    homepage = "https://github.com/Nukesor/pueue";
    license = licenses.mit;
    platforms = platforms.unix;
  };
};
```
