### ISSUE TITLE
(WIP) Package Gnome-Pie

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#65737]
Icon loading is quite broken for the application switcher per https://github.com/Simmesimme/Gnome-Pie/issues/170
```nix
#TODO some kind of assert for the bamf service if useBamf is true?
{ stdenv
, lib
, fetchFromGitHub
, wrapGAppsHook

, useBamf ? false #TODO

, pkgconfig
, cmake
, vala
, gnome3
, gnome-menus
, xorg
, libwnck3
, libarchive
, bamf
, libxml2
, libgee
, libappindicator
, gtk3
, cairo
#, glib
}:
  stdenv.mkDerivation {
    pname = "gnome-pie";
    version = "0.7.2";

    # TODO why is this broken
    # nix-shell -p nix-prefetch-github --run "nix-prefetch-github --rev refs/tags/v0.7.2 Simmesimme Gnome-Pie > gnome-pie.json"
    #src = fetchFromGitHub (lib.importJSON ./gnome-pie.json);
    src = fetchFromGitHub {
      owner = "Simmesimme";
      repo = "Gnome-Pie";
      rev = "refs/tags/v0.7.2";
      sha256 = "048im563qmizgwaj8z71nl6ppsfmp5wqyw4bbv5p6314nanhqqpp";
      };

    # TODO this just copies some functionality from make.sh
    # add hash check or something on make.sh to make sure behavior hasn't changed
    preConfigure = ''
      patchShebangs .
     ./resources/locale/compile-po.sh #hacking in what make.sh does
     '';

    #TODO fix this upstream
    postInstall = ''
      cp -rpf ../resources $out/bin/
      '';

    nativeBuildInputs = [ pkgconfig cmake vala wrapGAppsHook libxml2 ];

    buildInputs = [
      gnome-menus libwnck3 libarchive libgee libappindicator gtk3 libXtst
      ] ++ (lib.optional useBamf bamf);
    }
```

There is also some weirdness in the build output.
A bunch of spam about missing things that don't actually seem to break the build, such as:
```
Package libpcre was not found in the pkg-config search path.                                                                                                                            
Perhaps you should add the directory containing `libpcre.pc'                                                                                                                                              
to the PKG_CONFIG_PATH environment variable
Package 'libpcre', required by 'glib-2.0', not found
```
and 
```
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
```

**Comment by jtojnar** [comment]
The libpcre warning is glib/cmake issue, see https://github.com/NixOS/nixpkgs/pull/15046
The CMake warnings are again unrelated, see https://github.com/NixOS/nixpkgs/pull/52859#issuecomment-449875911 for a possible solution.

**Comment by jtojnar** [comment]
Also, did not we already have a PR for this? Cannot find it though. cc @worldofpeace

**Comment by worldofpeace** [comment]
> Also, did not we already have a PR for this? Cannot find it though. cc @worldofpeace

I think that might have been ulauncher, easy to mix up though since they offer similar functionality.

> The libpcre warning is glib/cmake issue, see #15046

Nice find, I've always wondered what that was.

**Comment by jtojnar** [comment]
Yeah, you are probably right. Though I am pretty sure someone from the community was looking into packaging into it as I already had links like the following in my browser history:

- https://github.com/Simmesimme/Gnome-Pie/issues/137
- https://github.com/Simmesimme/Gnome-Pie/blob/master/make.sh
- https://github.com/Simmesimme/Gnome-Pie/blob/master/resources/locale/compile-po.sh
- https://github.com/Simmesimme/Gnome-Pie/blob/6c57eb7df894812bfbe9a6a545c1573d0072e168/src/utilities/paths.vala#L145
- https://github.com/Simmesimme/Gnome-Pie/blob/6c57eb7df894812bfbe9a6a545c1573d0072e168/src/gui/indicator.vala#L82

**Comment by deliciouslytyped** [comment]
I gave a shot at it a while back but this time around I reused some code that didn't feel like it was mine, so, maybe something...somewhere...

**Comment by georgewsinger** [comment]
> If this is still important to you, we ask that you leave a comment below. Your comment can be as simple as "still important to me". This lets people see that at least one person still cares about this. Someone will have to do this at most twice a year if there is no other activity.

Still important to me. : ]

**Comment by Aleksanaa** [comment]
Upstream repo is archived.
