### ISSUE TITLE
haskellngPackages.ghcWithPackages is removed by `nix-env -u`

### ISSUE THREAD

**Issue by gridaphobe** [NixOS/nixpkgs#6575]
@peti I think this is due to a name clash. `haskellngPackages.ghcWithPackages` produces a derivation called `ghc-7.8.4`, but `nix-env -u` "upgrades" it to `ghc-7.8.4-wrapper`, which is not only missing the additional packages, but is from the original `haskellPackages` as far as I can tell.

**Comment by peti** [comment]
The only viable solutions to fix this issue appear to be:

1. remove the "-wrapper" suffix from the obsolete ghc wrapper,
2. attach the wrapper suffix to the `name` field, i.e. rename the wrapper to `ghc-wrapper-7.8.4`, or
3. add a suffix to the wrapper that's generated `ghcWithPackages`. 

I'm unsure what approach would be best.

**Comment by gridaphobe** [comment]
I haven't tried implementing any of these, but (3) sounds the most sensible to me.

**Comment by gridaphobe** [comment]
I've worked around this for the moment with
```
(haskellngPackages.ghcWithPackages cabalPackages).overrideDerivation (drv: { 
  name = "haskell-env";
})
```

**Comment by peti** [comment]
Just for kicks, `lib.setName` is probably a neater way to accomplish the same thing. I also append a "-0" to the name just so that there is some version number.

**Comment by peti** [comment]
I've decided to deal with this issue by sticking my head firmly into the sand and pretending it doesn't exist. That seems like a good-enough solution until 15.05 comes out. By then, the old Haskell code will be removed from Nixpkgs and the issue will, in fact, cease to exist.
