### ISSUE TITLE
New major release of TLA+ Toolbox

### ISSUE THREAD

**Issue by lemmy** [NixOS/nixpkgs#65760]
**Describe the bug**
A new major version of the TLA+ Toolbox has been [released](https://github.com/tlaplus/tlaplus/releases/tag/v1.6.0).  The [package instructions](https://github.com/NixOS/nixpkgs/blob/44884cdf291d8436fb473907994bda65450de468/pkgs/applications/science/logic/tlaplus/toolbox.nix#L6-L28) need an update.

The 1.6.0 has changed in that the Toolbox now comes with its on Java Runtime Environment.

@badi @vcunat 

Note that I'm the upstream developer.

**Comment by vcunat** [comment]
Merged.
