### ISSUE TITLE
nixos-generate-config generates duplicate fileSystems entries and swapDevices

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#65773]
I've set up the following in my configuration.nix:

```
  fileSystems = {
    "/".device = "/dev/mapper/vg-root";
    "/home".device = "/dev/mapper/vg-home";
  };
  swapDevices = [ { device = "/dev/mapper/vg-swap"; } ];
```

`sudo nixos-generate-config` creates duplicate entries for these in /etc/nixos/hardware-configuration.nix:

```
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1f7ecf35-bebe-4655-8de0-4f0648b8bb35";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a2a744ac-923e-4217-b77e-e6c8e39e0f28";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/50a66e47-cde9-4aa5-a3f9-9500b5aa1d8f"; }
    ];
```

This means I have to go against the advice in /etc/nixos/hardware-configuration.nix to make my modifications in /etc/nixos/configuration.nix.

**Metadata**
```
$ nix run nixpkgs.nix-info --command nix-info --markdown # package metadata 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.03.173210.b978a94c8f9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173210.b978a94c8f9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by danbst** [comment]
You're right, options in `hardware-configuration.nix` should be set with `lib.mkDefault`: https://github.com/NixOS/nixpkgs/issues/33018#issuecomment-435437270

Until this is fixed, you can use
```
{ lib, config, pkgs, ... }: {
...
  fileSystems = {
    "/".device = lib.mkForce "/dev/mapper/vg-root";
    "/home".device = lib.mkForce "/dev/mapper/vg-home";
  };
  # this may break zramSwap module if you use it, so uncomment with care
  # swapDevices = lib.mkForce [ { device = "/dev/mapper/vg-swap"; } ];
...
}
```

**Comment by Aleksanaa** [comment]
The hardware-configuration.nix you generate depends on how you mount the root partition. `nixos-generate-config` currently does not read the configuration in configuration.nix. Also, if you really know what you're doing and `nixos-generate-config` doesn't generate what you expected, you can certainly modify hardware-configuration.nix.
