### ISSUE TITLE
Thunar settings are not saved

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#65771]
**Describe the bug**
I've tried changing several settings in Thunar, such as the date format and view, but when I reopen Thunar they have been reset.

**To Reproduce**
1. Start Thunar as a normal desktop user
2. Go to Edit → Preferences…
3. Select a different date format or some other setting
4. Restart Thunar

**Expected behavior**
The settings should be retained.

**Workaround**

`services.xserver.desktopManager.xfce.enable = true;` combined with `services.xserver.desktopManager.xfce.noDesktop = true;` seems to do the trick.

**Screenshots**
The settings are back to the default - "View as Icons", date format "Today", etc..

**Additional context**
I am not running a full XFCE desktop, but rather Awesome WM. I did have XFCE enabled before, but not anymore.

The command produces absolutely no output to the command line to indicate what the problem is.

**What I've tried**

I get the same result when running `thunar --daemon` in the background.

Ditto after [`chmod 755 $HOME/.config/xfce4/xfconf/xfce-perchannel-xml`](https://askubuntu.com/a/406565/10371), [unsetting "Automatically expand columns as needed"](https://askubuntu.com/a/896319/10371), `rm -rf ~/.config/xfce4/xfconf/xfce-perchannel-xml`, and `rm -rf ~/.config/Thunar`.

**Metadata**

```
$ nix run nixpkgs.nix-info --command nix-info --markdown # package metadata 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.03.173210.b978a94c8f9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173210.b978a94c8f9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
installing xfconf fixes this

**Comment by SuperSamus** [comment]
I think that this should be reopened. A user shouldn't have to install a separate package for such a core feature.

**Comment by romildo** [comment]
It depends on a dbus service provided by `xfconf` and should be enabled in the configuration:

```[nix]
  services.dbus.packages = with pkgs; [
    xfce.xfconf
  ];
```

I do not think that it is possible to accomplish this without a module. Maybe we can add an option `programs.thunar.enable`.
