### ISSUE TITLE
Ruby-1.9.3 and bundler install issues

### ISSUE THREAD

**Issue by KaiSforza** [NixOS/nixpkgs#6577]
So I was working on installing ruby for a development environment, and it requires ruby 1.9.x, which is fine because nixos has a 1.9.3 version available to install. However, this comes with an issue.

The `ruby-1.9.3-p547` package works fine, contains `bin/ruby` as expected. But as soon as I ran `nix-env -u` to upgrade, things got weird.

There's another package, `ruby-1.9.3-p547-bundler-1.7.9`. Now in nix package specifications, this is the same package as `ruby-1.9.3-p547`, just with a different version number. The `bundler` part of this package *needs* to be specified before the version number 1.9.3, or `ruby-$VERSION` needs to become `ruby$VERSION`.

Correct me if I'm wrong, but those are the two real solutions for this issue here...

**Comment by KaiSforza** [comment]
And the second solution (removing the `-`) doesn't seem to follow how nix packages are set up. But then there is the issue of specifying the version the `ruby-bundler` depends on.

**Comment by KaiSforza** [comment]
This also only seems to be an issue with `ruby-1.9.3`. The other ruby versions do not have the `-bundler...` part appended to their versions.

**Comment by iElectric** [comment]
cc @cstrahan

**Comment by cstrahan** [comment]
First, I think we ought to remove the patch level from the Ruby name. Regarding the real issue at hand, I'd suspect removing the Ruby version from the libs should be alright. I don't personally use `nix-env` much, so I'd be interested to hear what others think, or draw inspiration for however things are handled in e.g. Python libraries in NIx.

**Comment by KaiSforza** [comment]
If I am not mistaken, Python libraries use `python3.3`, `python3.4` or `python2.7` prepended to their module names. Seems to be the case with both lua and python that they do `$langname$langver-$module-$modulever` as their naming scheme, however the languages themselves are `$langname-$langver` in lua and `$langname$majorver-$langver` in python.

**Comment by KaiSforza** [comment]
The lua naming scheme would probably work better for Ruby, since the main divide isn't between 1.x.y and 2.x.y, it's between sub-version's too.

**Comment by vcunat** [comment]
We no longer have those `ruby-*-bundler*` names, or at least not visible by nix-env. (This is on 15.09 already.) I think that makes this issue resolved, or at least the main part of it.
