### ISSUE TITLE
Love 0.7 broken on master and 19.03

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#65786]
**Describe the bug**

Love 0.7 doesn't build at the moment.

```
nix build -f channel:nixos-19.03 love_0_7
builder for '/nix/store/givchn1sx30qh0swhga4rsprqnzg6w6v-love-0.7.2.drv' failed with exit code 1; last 10 log lines:
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking for library containing sqrt... -lm
  checking for library containing SDL_Init... -lSDL
  checking for library containing glLoadIdentity... -lGL
  checking for library containing alSourcePlay... -lopenal
  checking for library containing lua_pcall... -llua
  checking for library containing ilInit... -lIL
  checking for library containing mng_initialize... no
  configure: error: DevIL needs MNG
[0 built (1 failed)]
error: build of '/nix/store/givchn1sx30qh0swhga4rsprqnzg6w6v-love-0.7.2.drv' failed
````

After adding libmng it fails during compiling.

**To Reproduce**

`nix build -f channel:nixos-19.03 love_0_7`

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 19.03.173214.4cc5592fe2d (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"home-manager-19.03, nixos-19.03.173202.31d476b8797, nixos-unstable-19.09pre186857.239fffc90d7, nixpkgs-19.03"`
 - channels(addy): `"nixos-19.03.173214.4cc5592fe2d, nixos-unstable-19.09pre186857.239fffc90d7, nixpkgs-19.03.173214.4cc5592fe2d"`
 - nixpkgs: `/home/addy/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: love_0_7 rimshot
# a list of nixos modules affected by the problem
module:
```

**Comment by Infinisil** [comment]
Why do we have 5 versions of this interpreter?? 0.7 is at least 8 years old by now. I think we can probably remove all but the latest. People can use an older nixpkgs version if they need ancient software

**Comment by Moredread** [comment]
I think  the only package that depends on it is rimshot. I guess in that case we should remove it too.

**Comment by Moredread** [comment]
On the other hand that package shows, that there is still software out there that depends on that old version of love.
