### ISSUE TITLE
fetchFromGitLab does not know how to unpack source

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#65796]
**Describe the bug**

```nix
fetchFromGitLab {
  domain = "salsa.debian.org";
  owner = "games-team";
  repo = "xteddy";
  rev = "debian/${version}";
  sha256 = "0rm7w78d6qajq4fvi4agyqm0c70f3c1i0cy2jdb6kqql2k8w78qy";
}
```
fails with `do not know how to unpack source archive /build/2.2-5`.
Manually unpacking with tar works just fine.

Any suggestions on how to fix this?

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.4, NixOS, 19.09pre186857.239fffc90d7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre186857.239fffc90d7"`
 - channels(pantarhei): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
i notice that sometimes the unpack fails if more than one output is produced. You may need to override the unpack phase.

```
unpackPhase = ''
  tar xf $src
'';
```

**Comment by xaverdh** [comment]
That doesn't seem to fix this case. If I understand the code for [fetchFromGitLab](https://github.com/NixOS/nixpkgs/blob/d16e0f8dc3b600a5d501d31bb5e87bf000a51ae3/pkgs/build-support/fetchgitlab/default.nix) and [fetchzip](https://github.com/NixOS/nixpkgs/blob/d16e0f8dc3b600a5d501d31bb5e87bf000a51ae3/pkgs/build-support/fetchzip/default.nix) correctly, these bypass the unpack phase.

**Comment by jonringer** [comment]
interesting, I haven't used fetchFromGitLab yet, sorry :(

**Comment by marsam** [comment]
This is an issue with archiving api GitLab See: https://github.com/NixOS/nixpkgs/issues/48215 https://gitlab.com/gitlab-org/gitlab-ce/issues/38537. As a workaround can you try the following?
```diff
--- /tmp/orig.nix	2019-08-02 15:02:03.000000000 -0500
+++ /tmp/new.nix	2019-08-02 15:02:44.000000000 -0500
@@ -2,6 +2,6 @@
   domain = "salsa.debian.org";
   owner = "games-team";
   repo = "xteddy";
-  rev = "debian/${version}";
+  rev = "debian%2F${version}"; # %2F = urlquote("/")
   sha256 = "0rm7w78d6qajq4fvi4agyqm0c70f3c1i0cy2jdb6kqql2k8w78qy";
 }
```

**Comment by worldofpeace** [comment]
@marsam I can confirm that this would fix the issue (i've had it before). 
Eventually it would be nice if `fetchFromGitLab` could url encode `rev`.

**Comment by xaverdh** [comment]
That did indeed work. Is it a good idea to use this workaround in a package? If url quoting gets implemented one day, that piece might get double quoted (I could go with `fetchgit` instead).

**Comment by worldofpeace** [comment]
It should check if it's already url encoded. Should be fine to do this.

**Comment by xaverdh** [comment]
Ok, thanks :-)
I will keep this open just in case someone hits this..

**Comment by xaverdh** [comment]
In https://github.com/NixOS/nixpkgs/pull/104657 it was noted that this issue appears fixed for some reason or another, so I am closing this. Anybody feel free to reopen it, if it should occur again.
