### ISSUE TITLE
What's the difference between utillinux-1003.1-2008 and util-linux-2.33.1?

### ISSUE THREAD

**Issue by zaoqi** [NixOS/nixpkgs#65812]

**Comment by JohnAZoidberg** [comment]
Can you please explain where you found those names?
`utillinux` is the attribute of the package. I.e. when you clone nixpkgs and run `nix-build -A utillinux` you build it.
`util-linux` is the name of the package. It's defined inside its derivation and thus will be used as the name for the derivation and output files.

See:
```
$ nix-build -A utillinux
/nix/store/fp3byq8v647xdydsqh1xpls4sm5v4vbg-util-linux-2.33.2-bin
```

**Comment by zaoqi** [comment]
@JohnAZoidberg 
https://nixos.org/nixos/packages.html#utillinux

nixos.utillinux  / nixos.unixtools.utillinux

**Comment by matthewbauer** [comment]
Yeah this is confusing, but basically "util-linux-2.33.1" is the Linux upstream version, while "utillinux-1003.1-2008" is a compatibility package that is meant to work on non-Linux systems. This is mostly useful on macOS where we can't actually build the real util-linux, so we use a compatiblity version. Probably should update the name to be consistent.
