### ISSUE TITLE
Plasma 5 Kicker is missing a dependency

### ISSUE THREAD

**Issue by ajgrf** [NixOS/nixpkgs#6581]
Attempting to use kicker in plasma 5 gives an error complaining that the qml module QtGraphicalEffects is not installed (this is the cascading application menu, not the default kickoff launcher).

**Comment by iElectric** [comment]
cc @ttuegel

**Comment by ttuegel** [comment]
This is a consequence of the new split Qt 5.4 expressions. Upstream isn't very good about checking for specific Qt submodules, so we sometimes have missing dependencies. I will go ahead and make all the packages depending on Qml or Quick require GraphicalEffects.

**Comment by ttuegel** [comment]
Fixed in master.
