### ISSUE TITLE
ghc-android

### ISSUE THREAD

**Issue by wavewave** [NixOS/nixpkgs#6582]
I think that now it is a good time to try to build [ghc-android](https://github.com/neurocyte/ghc-android) using nix. Docker build on top of debian docker image is now also under development:  see [docker-build-ghc-android](https://github.com/sseefried/docker-build-ghc-android)

How may I start? Currently ghc build in nixpkgs support cross compiling strategy? Please give your opinion. Any rough ideas will be greatly helpful. Thanks

**Comment by peti** [comment]
I'm closing this issue because of several months of inactivity.

**Comment by wavewave** [comment]
I've succeeded in making ghc cross-compiler for android. tested with LG G4 phone. Please see https://github.com/wavewave/nix-build-ghc-android
