### ISSUE TITLE
CadQuery, CQ-editor and cqparts

### ISSUE THREAD

**Issue by marcus7070** [NixOS/nixpkgs#65830]
**Project description**

CadQuery is a Python package for generating Cad models. It's similar to OpenSCAD, except it uses Python instead of a limited scripting language and it uses the Opencascade kernel, meaning it offers the modelling features and performance of a professional CAD package. 

CQ-editor is a QT based graphical interface for CadQuery.
![](https://github.com/CadQuery/CQ-editor/raw/master/screenshots/screenshot3.png)

cqparts is a wrapper for CadQuery objects to create the traditional parts/assembly hierarchy of other CAD software. 

The developers strongly recommend installing through Anaconda, which [has been successfully used under NixOS](https://discourse.nixos.org/t/running-a-qt-application-that-has-been-installed-by-anaconda/3527). But it would be better if it was packaged with nix. 

**Metadata**

* homepage & source URLs:
  * [CadQuery](https://github.com/CadQuery/cadquery)
  * [CQ-editor](https://github.com/CadQuery/CQ-editor)
  * [cqparts](https://github.com/cqparts/cqparts)
* license: All Apache 2.0
* platforms: linux

**Comment by marcus7070** [comment]
** Progress **
* Some dependencies were packaged and merged by @gebner https://github.com/NixOS/nixpkgs/pull/61812
* @costrouc did some further work in https://github.com/NixOS/nixpkgs/pull/65378 
* I've taken it further in https://github.com/marcus7070/nixpkgs/tree/python-cq-editor-init

CadQuery is currently working. CQ-editor is mostly there but there are some errors related to pyqt5 and qtconsole. I haven't had a go at cqparts yet, but that should be pretty trivial. 

I'll keep on working on this.

**Comment by marcus7070** [comment]
So pyqtgraph in [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/) currently depends upon pyqt4: https://github.com/NixOS/nixpkgs/blob/caa9018846045cfacc5682216e0d2c374e1505c1/pkgs/development/python-modules/pyqtgraph/default.nix

[From their page](https://github.com/pyqtgraph/pyqtgraph#qt-bindings-test-matrix), pyqtgraph can use a heap of different bindings and pyside2 works with the most versions of Python.

I feel like I would have less issues if pyqtgraph used pyqt5, like the other dependencies. Should I just override it with a `let ... in` in the cq-editor expression, or should the nixpkgs' pyqt5 expression be changed in some way to allow different QT bindings? 

Or do I not know enough about Python QT bindings, and it's not an issue to have pyqt4 and pyqt5 both being used in the same Python app?

**Comment by FRidh** [comment]
pyqt5 is a bit messy and broken currently. I am looking into that at the moment.

**Comment by marcus7070** [comment]
Just tried pulling in master after #65836 was merged and cq-editor now works! Thanks so much @FRidh! 
I'll clean up my stuff and open a pull request tomorrow.

**Comment by marcus7070** [comment]
I don't think cqparts is ready for packaging just yet. It currently imports FreeCAD, with a comment [`# FIXME: remove freecad dependency from this module... right now I'm just trying to get it working.`](https://github.com/cqparts/cqparts/blob/61fa9753d1b875fc7ebcba37c57dbada3b7e7a82/src/cqparts/utils/geometry.py#L4).
I'll have another go at it when they get around to removing FreeCAD as a dependency. 
As a note for either myself or anyone else who picks cqparts up, it's going to need a preconfigure phase something like
```
cd source/deployment
python3 make-setup.py --lib cqparts
```
The [readme in the deployment directory](https://github.com/cqparts/cqparts/tree/20180530/deployment) has more info.

**Comment by marcus7070** [comment]
No idea how I got it cq-editor working. Rebased against master, reset my laptop, and it all fell apart. Now qt is back to whining about 
```
[nix-shell:~/tempbuild/nixpkgs]$ QT_QPA_PLATFORM= QT_DEBUG_PLUGINS=1 cq-editor
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/w7gsq8v86hni4ynaqgwwlnlny115ylng-python3-3.7.4/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/gya8i7afpmgvnz2bkkdipllf2sifm504-cq-editor-0.1RC1/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/hy0z060pmjwrdrbb0qrii7hnwif8cz1y-qtbase-5.12.0-dev/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/3dmdzlqhwgykbh0c1jf1bc59alsm1gik-libxml2-2.9.9-dev/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/is6cqm7lk6gnmqy0bmr0x94cy63cmsnl-libxml2-2.9.9-bin/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/l4fhdrgznbav2zxqgz5801ryairpd093-libxslt-1.1.33-dev/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/p0rlywxvmwjdv21wjqhgmsr4wq9rz7gq-libxslt-1.1.33-bin/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/1z0jyl97lka71av44ki7bnxridw8vdd1-openssl-1.0.2s-bin/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/gqmcgk749sp5a8dl3bjv2i6xxli0sm6z-sqlite-3.28.0-bin/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/vr66xrj0lazm6n4jidvw2wfn3lpzbanr-harfbuzz-icu-2.5.3-dev/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/q0zndgkxqrzj47dg7msifg3wkms9cd34-graphite2-1.3.6/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/11ngz9irxr4mrp936xavckfrrbpb5b04-icu4c-64.2-dev/lib/qt-5.12/plugins/platforms" ...
# snipped many many more paths
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/xnk229qan97prxmwfsgm65py2qpca109-gnutar-1.32/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/rgb9bhwzwijg87jy1kcd88ixdzg91hjy-gzip-1.10/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/6g1vx8239mrxa1apicld1nbihminadsx-gnumake-4.2.1/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/xfghy8ixrhz3kyy6p724iv3cxji088dx-bash-4.4-p23/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/iyz25vfk5f0w5kfrsx3z9il60dv9nhyn-patch-2.7.6/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/k5vgmfzyzx2ax392m23nx1p92lvik020-swaybg-1.0/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/marcus/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/run/wrappers/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/marcus/.nix-profile/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/var/nix/profiles/default/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/run/current-system/sw/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/etc/profiles/per-user/marcus/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/marcus/.local/lib/qt-5.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/w7gsq8v86hni4ynaqgwwlnlny115ylng-python3-3.7.4/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted
```

This QT stuff is incredibly frustrating. I'm not sure what QT is looking for. I've lost motivation for the moment, I'll get back to it in a few days.

**Comment by gebner** [comment]
I think the Qt stuff is due to https://github.com/NixOS/nixpkgs/issues/65399

**Comment by marcus7070** [comment]
Thanks @gebner. I had already tried conforming with the `libsForQt5.callPackage ...` and `mkDerivationWith python3Packages.buildPythonApplication` style [described in the manual](https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt) and it didn't change the error. ([my cq-editor/default.nix](https://github.com/marcus7070/nixpkgs/blob/cadquery-and-friends-init-dirty/pkgs/applications/graphics/cq-editor/default.nix))

But rereading #65399 and following the trail of breadcrumbs led me to [this comment](https://github.com/NixOS/nixpkgs/issues/65623#issuecomment-517987934). 

So if I run `nix-shell -I nixpkgs=/home/marcus/tempbuild/nixpkgs -p cq-editor` it gives the error in my previous comment, if I run `nix-shell -I nixpkgs=/home/marcus/tempbuild/nixpkgs -p qt5Full -p cq-editor` it works. 

I'm finished for the day now, but that's a good starting point for my next run at it.

**Comment by marcus7070** [comment]
sweet: https://github.com/NixOS/nixpkgs/issues/65399#issuecomment-519183900

**Comment by PlumpMath** [comment]
>>> import cadquery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/j5kki2qzj0svbhs5pw0fj0wydphl115w-python3-3.7.5-env/lib/python3.7/site-packages/cadquery/__init__.py", line 2, in <module>
    from .occ_impl.geom import Plane, BoundBox, Vector, Matrix
  File "/nix/store/j5kki2qzj0svbhs5pw0fj0wydphl115w-python3-3.7.5-env/lib/python3.7/site-packages/cadquery/occ_impl/geom.py", line 3, in <module>
    from OCC.Core.gp import gp_Vec, gp_Ax1, gp_Ax3, gp_Pnt, gp_Dir, gp_Trsf, gp, gp_XYZ
ModuleNotFoundError: No module named 'OCC.Core'
>>>

**Comment by marcus7070** [comment]
> hmm;;; help me~*

Hi @PlumpMath, were you using all the code from this branch? https://github.com/NixOS/nixpkgs/pull/66254

PythonOCC comes from the let statement in pkgs/development/python-modules/cadquery/default.nix

**Comment by PlumpMath** [comment]
my configuration.nix

          marcus7070 = import (fetchFromGitHub {
            owner = "marcus7070";
            repo = "nixpkgs";
            rev = "07abf0a8723cae353e65a89259462966fe681c98";
            sha256 =
"143bl8n4fcz21dwkc5jq3j8jf7jcf683901ni11nvr34hffsv47i";
          }) {  config.allowUnfree = true;  };

marcus7070.cq-editor

====================================++ cadquery building now.. (opencascade)

I didn't see detail the code  because I'm tired at yesterday so late subway.
I'm trying now (building...)
I wish success...
I'm korean 3d BEMS related programmer. so next ifcopenshell g,.g  Thanks.




2019년 11월 20일 (수) 오후 12:04, Marcus Boyd <notifications@github.com>님이 작성:

**Comment by marcus7070** [comment]
#66254 has been merged, providing CadQuery can CQ-editor. cqparts is not ready to be packaged yet.

**Comment by PlumpMath** [comment]
Thanks~! good day everyone.

2019년 12월 1일 (일) 오후 12:49, Marcus Boyd <notifications@github.com>님이 작성:
