### ISSUE TITLE
haskell-ng: 'amazonkaEnv' is broken

### ISSUE THREAD

**Issue by fmap** [NixOS/nixpkgs#6584]
Given this minimal arrangement:

https://gist.github.com/fmap/f8bdc0c731cf9b45763a

`nix-shell` fails citing a collision:

```
% nix-shell 
these derivations will be built:
  /nix/store/b1wy90qsbl77y6679fq69w9c90l2xzv5-ghc-7.8.4.drv
building path(s) ‘/nix/store/hbx5wsd7cghkycfrawc88sbmkx4b9xz8-ghc-7.8.4’
collision between `/nix/store/d2hs4w7hhf7kj9c61q78w8b0z73zm5f1-ghc-7.8.4/lib/ghc-7.8.4/directory-1.2.1.0/libHSdirectory-1.2.1.0-ghc7.8.4.so' and `/nix/store/vir49a9c5znyq42nw27nqsfs84vmbcr0-haskell-directory-1.2.1.0/lib/ghc-7.8.4/directory-1.2.1.0/libHSdirectory-1.2.1.0-ghc7.8.4.so' at /nix/store/9z6d76pz8rr7gci2n3igh5dqi7ac5xqj-builder.pl line 72.
builder for ‘/nix/store/b1wy90qsbl77y6679fq69w9c90l2xzv5-ghc-7.8.4.drv’ failed with exit code 2
error: build of ‘/nix/store/b1wy90qsbl77y6679fq69w9c90l2xzv5-ghc-7.8.4.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

Cc: @peti @shlevy

**Comment by fmap** [comment]
> Given this minimal arrangement:

Or more trivially:

```
% nix-shell ~/root/code/nixos/nixpkgs/ -A haskellngPackages.amazonka.env 
these derivations will be built:
  /nix/store/w7hsvgn7gkcv2l3bynm0h1a4sm5vab9i-ghc-7.8.4.drv
building path(s) ‘/nix/store/p07zqz3y3y3b4h1kci1471wlj2wkm12n-ghc-7.8.4’
collision between `/nix/store/d2hs4w7hhf7kj9c61q78w8b0z73zm5f1-ghc-7.8.4/lib/ghc-7.8.4/directory-1.2.1.0/libHSdirectory-1.2.1.0-ghc7.8.4.so' and `/nix/store/vir49a9c5znyq42nw27nqsfs84vmbcr0-haskell-directory-1.2.1.0/lib/ghc-7.8.4/directory-1.2.1.0/libHSdirectory-1.2.1.0-ghc7.8.4.so' at /nix/store/9z6d76pz8rr7gci2n3igh5dqi7ac5xqj-builder.pl line 72.
builder for ‘/nix/store/w7hsvgn7gkcv2l3bynm0h1a4sm5vab9i-ghc-7.8.4.drv’ failed with exit code 2
error: build of ‘/nix/store/w7hsvgn7gkcv2l3bynm0h1a4sm5vab9i-ghc-7.8.4.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

**Comment by peti** [comment]
I don't know how to use the `amazonka` packages, to be honest. Those builds replace GHC core libraries, which is why those collisions occur, I suppose.

@shlevy, how do you build an environment than contains these packages? Can help us out?

**Comment by shlevy** [comment]
I've only ever tested that they build individually, haven't yet used them in envs. It may be that for deep overrides like this the best thing to do is to define a whole new haskell package set. @peti Do you have any ideas for how we might easily create new sets with "chaining", so I can say "take the default haskell package set (including any overrides etc), add these overrides for core and other packages, and that's your amazonka set"?

**Comment by shlevy** [comment]
Oh, hm, the env thing is a bit different actually. Probably we need some way to exclude core packages from the built env, or if not exclude let other things take priority. I don't really know the details about how envs are built, @peti do you know how this might be done easily? If not I'll take a look, please let me know.

**Comment by peti** [comment]
@shlevy, when you develop code with `amazonka` packages, how do you use them?

One way to "remedy" the collision in the env builder is to configure

    ghcEnv.override { ignoreCollisions = true; };

where `ghcEnv` is the `ghcWithPackages` environment. This gets rid of the error. I'm not sure whether the environment that comes out of this is safe to use though.

**Comment by shlevy** [comment]
Will dig into this in detail tomorrow.

**Comment by peti** [comment]
Any news on this? I wonder how you are using these amazonka packages, @shlevy?

**Comment by peti** [comment]
Maybe we should remove the `amazonka` overrides from `master`? Publishing that code there comes with an implicit promise that it can be used, and it appears we cannot keep that promise as the moment?

**Comment by shlevy** [comment]
OK, so basically we need a) to have the non-core version of the library override the core version and b) to build all packages in the env against the non-core version (that is, the package set chaining stuff I was talking about in my earlier comment). `ignoreCollisions` does fix a), but it fixes too much, as it won't catch cases where b) matters until run time (but it does work when no other packages in the env depend on the overridden core packages, or when all packages in the env are properly built from the same set).

I think the ideal thing to do would be to have each core package in a separate output of ghc, which would then not be part of the env unless explicitly requested. This also dovetails with the "reduce ghc closure size" investigation I did: Even with `lib` in a separate output, with all of the core libraries (in all of their forms, shared and static and debug etc.) together with librts there was pretty much no savings relative to single output.

@thoughtpolice not sure how involved you are in the build system of ghc, but do you know offhand if it's possible to configure the ghc installation to put different packages in different prefixes?

@edolstra Any reason to expect problems from a derivation having dozens of outputs?

**Comment by peti** [comment]
@shlevy, when you develop code with `amazonka` packages, how do you use them?

**Comment by shlevy** [comment]
As I said above, I've only tested that they built. @fmap is a co worker of mine who is the first to start using them in a nix context.

**Comment by peti** [comment]
@shlevy, maybe we should remove the `amazonka` overrides from `master`? Publishing that code there comes with an implicit promise that it can be used, and it appears we cannot keep that promise as the moment?

**Comment by shlevy** [comment]
I'd prefer something like `meta.broken`, as we do have a hacky solution that works in some cases (ignoreCollisions = true) and have an idea for what a real solution would look like, but in the end it's not a big deal I suppose.

**Comment by peti** [comment]
I believe it's fine it have that code in `master` once a real solution is implemented. For the time being, however, I'd rather not advertise packages that seemingly replace GHC core libraries with other versions when, in fact, we have no idea how to use those packages reliably.
