### ISSUE TITLE
vim-terraform plugin breaks neovim's manifest generation.

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#65894]
**Describe the bug**
When I try to build Neovim with the `vim-terraform` plugin, neovim is started with a minimal configuration to generate the manifest of the remote plugins [here](https://github.com/NixOS/nixpkgs/blob/1c709e0e6c037961cea0b3206d1f850e2e1ad636/pkgs/applications/editors/neovim/wrapper.nix#L94-L118). Vim terraform recently [received a change](https://github.com/hashivim/vim-terraform/commit/657cf09ff3a53388cee2cfabdbe44512f9f60e4d) that's breaking because the event was not found.

**To Reproduce**
1. `nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { vam.pluginDictionaries = [ "vim-terraform" ]; }; }' --show-trace`

**Expected behavior**
NeoVim with the terraform plugin built

**Additional context**
<details>
<summary>error log</summary>

```
 λ  nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { vam.pluginDictionaries = [ "vim-terraform" ]; }; }' --show-trace
these derivations will be built:
  /nix/store/ychncgzlm68fvwvfrnw19fliy5p040dz-vimrc.drv
  /nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv
building '/nix/store/ychncgzlm68fvwvfrnw19fliy5p040dz-vimrc.drv'...
building '/nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv'...
Generating remote plugin manifest
Error detected while processing /nix/store/dkns06xxx69b9fzsxsk3505wpl7rky5l-vimplugin-vim-terraform-2019-06-20/share/vim-plugins/vim-terraform/ftdetect/terraform.vim:
line    2:
E216: No such group or event: filetypedetect BufRead,BufNewFile *.tf
remote/host: generated rplugin manifest: /nix/store/fnspsjif1dm824va81hbl3v3iy65krna-neovim-0.3.7/rplugin.vim
Generating rplugin.vim failed!
builder for '/nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv' failed with exit code 1
error: build of '/nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv' failed

```
</details>

<details>

<summary>Reversal patch confirming the cause</summary>

```diff
diff --git a/pkgs/misc/vim-plugins/overrides.nix b/pkgs/misc/vim-plugins/overrides.nix
index 5ee03077d71..500c1944c6b 100644
--- a/pkgs/misc/vim-plugins/overrides.nix
+++ b/pkgs/misc/vim-plugins/overrides.nix
@@ -42,6 +42,10 @@ self: super: {
     src = skim.vim;
   };
 
+  vim-terraform = super.vim-terraform.overrideAttrs(oa: {
+    patches = (oa.patches or []) ++ lib.singleton ./vim-terraform-remove-invalid-event.patch;
+  });
+
   LanguageClient-neovim = let
     version = "0.1.146";
     LanguageClient-neovim-src = fetchurl {
diff --git a/pkgs/misc/vim-plugins/vim-terraform-remove-invalid-event.patch b/pkgs/misc/vim-plugins/vim-terraform-remove-invalid-event.patch
new file mode 100644
index 00000000000..e45bb0ed554
--- /dev/null
+++ b/pkgs/misc/vim-plugins/vim-terraform-remove-invalid-event.patch
@@ -0,0 +1,18 @@
+commit 04621b386dbee77921c989156194f280445d45ce
+Author: Wael M. Nasreddine <wael.nasreddine@gmail.com>
+Date:   Sat Aug 3 19:32:13 2019 -0700
+
+    Revert "Remove Vim's default filetype detection for .tf files"
+    
+    This reverts commit 657cf09ff3a53388cee2cfabdbe44512f9f60e4d.
+
+diff --git a/ftdetect/terraform.vim b/ftdetect/terraform.vim
+index 5919422..467351e 100644
+--- a/ftdetect/terraform.vim
++++ b/ftdetect/terraform.vim
+@@ -1,5 +1,3 @@
+-" By default, Vim associates .tf files with TinyFugue - tell it not to.
+-autocmd! filetypedetect BufRead,BufNewFile *.tf
+ autocmd BufRead,BufNewFile *.tf set filetype=terraform
+ autocmd BufRead,BufNewFile *.tfvars set filetype=terraform
+ autocmd BufRead,BufNewFile *.tfstate set filetype=json
```

</details>

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.11, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `""`
 - channels(kalbasit): `"home-manager-18.09, nixpkgs-18.09.932.09195057114"`
 - channels(yl): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
```

**Comment by kalbasit** [comment]
The original PR upstream: https://github.com/hashivim/vim-terraform/pull/93

cc @timokau the [author of the manifest generation](https://github.com/NixOS/nixpkgs/commit/ab22e8cc9c8f667c09f54f82fcb88f9732c54dfc).

**Comment by timokau** [comment]
I think this is at least close to being an upstream bug. They should wrap it in a proper `augroup` that won't complain when the group doesn't exist already.

Still, I wonder why the group isn't created in the minimal configuration we launch for plugin manifest generation.

**Comment by kalbasit** [comment]
> I think this is at least close to being an upstream bug. They should wrap it in a proper `augroup` that won't complain when the group doesn't exist already

I agree, but I did not know the specifics as to why it's failing to make that decision.

> Still, I wonder why the group isn't created in the minimal configuration we launch for plugin manifest generation.

Could it be that we don't have syntax enabled in the minimal configuration?

**Comment by timokau** [comment]
> Could it be that we don't have syntax enabled in the minimal configuration?

Apparently that group is defined in [filetype.vim](https://github.com/neovim/neovim/blob/7e8dbb5958505f5b5960add91a032cd1de26586a/runtime/filetype.vim) which does not get loaded if you have disabled both syntax highlighting and filetype detection.

I'm still not quite sure what's happening though, since neovim is supposed to (`:help initialization`) enable both of them except if you explicitly disable them.

**Comment by gloaming** [comment]
It does, but only _after_ the `vimrc` is loaded: https://github.com/neovim/neovim/pull/6596

> Perhaps the conclusion is that we simply should not advise users to remove filetype/syntax calls from their configs. The main utility of the existing logic is for users without configs.

The fix is to move `syntax on` before the plugins in the generated config. In fact, unlike most plugin managers, for some reason `vam` recommends doing `filetype` before plugin load as well: https://github.com/MarcWeber/vim-addon-manager/tree/d9e865f3c2de5d9b7eabbc976f606cf1b89e29ea#recommended-setup
