### ISSUE TITLE
Any chances to reduce verbosity of `nixos-rebuild switch`?

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#6592]
Can we make the list of downloaded files less verbose, is spirit of `pacman`? One line per downloadable, not 7-8

**Comment by copumpkin** [comment]
I think this ties into my ticket https://github.com/NixOS/nix/issues/443, to some extent. The entire nix ecosystem is extremely chatty and reduces/eliminates our ability to discern the important information from pointless log messages.

**Comment by vcunat** [comment]
Yes, this is just a subproblem of that one.
