### ISSUE TITLE
Speed up `nix-env -i`

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#6594]
Currently when you run

`nix-env -i chromium`

it waits for a long time. What about try `nixos.pkgs.chromium` as hotcheck, and if that fails, do the full search?

**Comment by wmertens** [comment]
Good idea! But can you open this issue on Nix instead? That's where the
nix-env code lives...

**Comment by vcunat** [comment]
It's slightly tricky that ``nix-env -i foo`` might refer to a different package version than ``nix-env -iA nixos.pkgs.foo`` (even discounting the case when you have a differently-named channel or multiple channels).

It typically comes from the fact that defaults for package builders (using attribute names) are sometimes different than defaults for interactive usage (using package name), e.g. ``bash`` and ``bashInteractive`` attributes.

A general way to do this would be a supposedly easy extension of our ``command-not-found`` database.

**Comment by danbst** [comment]
One issue I encountered in my setup, was that `nix-env -i virtualbox` installed `nixos.pkgs.virtualboxUnstable` instead of `nixos.pkgs.virtualbox`. So now I definitly do not understand how `nix-env -i` works

@wmertens ok, I'll reopen in Nix

**Comment by wmertens** [comment]
Nix-env -i foo should first check if the attribute "foo" resolves to the
derivation named "foo". If not, it should do the normal search.

**Comment by vcunat** [comment]
@wmertens: that would break the same-name priority semantics we had until now.

**Comment by wmertens** [comment]
:-( then there's no solution?

How about trying all attributes that have the given name as a substring?
