### ISSUE TITLE
sshguard has a startup race condition

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#65985]
**Describe the bug**

the sshguard module includes a post-start script that adds firewall rules to match the `ipset` that sshguard creates on startup. This script races with sshguard actually creating the `ipsets`s, and when it loses, the entire unit fails to start with:

```
Aug 04 14:27:06 iris systemd[1]: Starting SSHGuard brute-force attacks protection system...
Aug 04 14:27:06 iris pbb1a60wshiwn3k25zxxhdqaml752l67-unit-script-sshguard-post-start[32088]: iptables v1.8.2 (legacy): Set sshguard4 doesn't exist.
Aug 04 14:27:06 iris pbb1a60wshiwn3k25zxxhdqaml752l67-unit-script-sshguard-post-start[32088]: Try `iptables -h' or 'iptables --help' for more information.
Aug 04 14:27:06 iris systemd[1]: sshguard.service: Control process exited, code=exited status=2
```

This leads sshguard to crashloop a non-deterministic number of times before starting correctly. If especially unlucky, it crashloops enough times that systemd gives up trying to start it, and sshguard doesn't come up at all until an admin fixes it.

**To Reproduce**

1. Add `services.sshguard.enable = true;` to `configuration.nix`.
2. `nixos-rebuild test`
3. Using `systemctl status sshguard` and `journalctl -u sshguard`, observe crashloop. It may take a few attempts to trigger depending on your machine and luck.

**Expected behavior**

sshguard should start cleanly without relying on winning races.

**Additional context**

This is a secondary effect of fixing #62874 with aeeb30a3b298d4b3ff930f55cb278f8d6c232da2 . In the old world, sshguard didn't create the ipset so nixos's post-start script did both the ipset creation and firewall config. Now, sshguard creates the ipset itself, but we still rely on a post-start script to create firewall rules that depend on the ipsets existing.

I believe a correct fix would be to go back to creating the ipset from outside sshguard, and putting both ipset creation and firewall configuration in pre-start, rather than post-start. This way, the system state would already be satisfactory to sshguard, and it would not need to do anything itself.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.21, NixOS, 19.03.173230.90b1b55e3e1 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173230.90b1b55e3e1, nixos-unstable-19.09pre187507.525eaf407d4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services/security/sshguard.nix
```

**Comment by R-VdP** [comment]
I am experiencing the same issue on several servers running 19.03.

**Comment by R-VdP** [comment]
@mmahut will this be backported to 19.03?
