### ISSUE TITLE
Docker: fails because no /var/run/docker.sock

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#6616]
I'm not sure about this one:

```bash
$ nix-env -iA nixpkgs.docker
installing ‘docker-1.4.1’
building path(s) ‘/nix/store/bcrdv9sqsby0x3y4z2m5dp5y3yhhwz1z-user-environment’
created 147 symlinks in user environment
$ docker pull diet/docker-chromium
FATA[0000] Post http:///var/run/docker.sock/v1.16/images/create?fromImage=diet%2Fdocker-chromium%3Alatest: dial unix /var/run/docker.sock: no such file or directory
```

**Comment by joachifm** [comment]
I believe you must enable the docker daemon for this to work (i.e., virtualisation.docker.enable = true).

**Comment by matthiasbeyer** [comment]
Does not work (same error) after I did this..

**Comment by joachifm** [comment]
Is your login user a member of the "docker" group?

**Comment by matthiasbeyer** [comment]
Ah, now it works!

**Comment by copumpkin** [comment]
This seems like a usability issue. Is there a way for us to warn (with suggestions on what to do) if the setting is incorrect, on NixOS only?

**Comment by matthiasbeyer** [comment]
Actually, I couldn't start the container after I pulled it. :cry:

**Comment by matthiasbeyer** [comment]
So, here I am again.

I'm in the "docker" group and I've added `virtualisation.docker.enable = true;` to my configuration.

I'm getting this error:

```
FATA[0000] Post http:///var/run/docker.sock/v1.16/containers/create?name=chrome: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?
```

When running this docker call:

```bash
docker run -it \
    --net host \
    --cpuset 0 \
    --memory 512mb \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix$DISPLAY \
    -v $HOME/Downloads:/root/Downloads \
    -v $HOME/.config/google-chrome/:/data \
    -v /dev/snd:/dev/snd --privileged \
    --name chrome \
    jess/chrome
```

I have it from [here](https://blog.jessfraz.com/posts/docker-containers-on-the-desktop.html) (for reference)

**Comment by matthiasbeyer** [comment]
Starting the container with `sudo` works.

---

Started:

```bash
$ docker run -it \
    --name lynx \
    jess/lynx
```

successfully, but I guess I shouldn't do this with root, should I?

**Comment by matthiasbeyer** [comment]
Solved it.

The problem was that I had to re-login after my user got the "docker" group. Everything works like a charm now! 

Yaaay, running insecure apps (chromium, skype, firefox) in a container makes my life much better now!

**Comment by joachifm** [comment]
@matthiasbeyer you probably know this, but just in case: you should not rely on docker for security, especially if the application running within the container can access your X server.

**Comment by matthiasbeyer** [comment]
@joachifm ah, you're right. Thanks!

**Comment by relief-melone** [comment]
While usually signing off is enough in my case I had to restart nixos after adding me to the docker group again with

```nix
users.users.<username>.extraGroups = [ "docker" ];
```
