### ISSUE TITLE
arduino: fails to build

### ISSUE THREAD

**Issue by truh** [NixOS/nixpkgs#66176]
**Describe the bug**
When I'm trying to install he arduino or ino package on MacOS I get the error message *has wrong length for hash type 'sha256'*.

https://github.com/NixOS/nixpkgs/blob/92a047a6c4d46a222e9c323ea85882d0a7a13af8/pkgs/development/arduino/arduino-core/downloads.nix#L135, one of the MacOS entries has a hash that is longer than all the other hashes. 

**To Reproduce**

Run: `nix-shell -p arduino --show-trace`

**Expected behavior**

Arduino is installed in a nix shell.

**Screenshots**

![Screenshot 2019-08-06 at 10 25 08](https://user-images.githubusercontent.com/1183303/62523670-99397300-b834-11e9-91c7-a97bdd515620.png)

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
[21 copied (37.5 MiB), 8.2 MiB DL]
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(jakob): `"home-manager-19.03, nixpkgs-19.03pre173243.9ef3cb9b0ba, nixpkgs-19.03-darwin-19.03pre173243.9ef3cb9b0ba"`
 - nixpkgs: `/Users/jakob/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
ino
arduino
```

**Comment by gazally** [comment]
@truh In the pull request mentioned above I have corrected the obvious error in the hash.  I don't have Nix on Darwin to try it on, can you?
