### ISSUE TITLE
Resume from Hibernation Fails

### ISSUE THREAD

**Issue by cillianderoiste** [NixOS/nixpkgs#6617]
I haven't been able to resume from hibernation since 3bcd3ed01 and 448c6fc317 (I tried setting the resumeDevice to /dev/sdb3 and leaving it empty). Reverting these commits and using the device major and minor numbers works for me. It would be great to restore the option to specify the resumeDevice by major and minor numbers and also to support specifying the device by path. 

@abbradar have you got some thought on this?

Related to #5219 #4995

**Comment by abbradar** [comment]
I can't remember specifics, but I recall although I wanted to maintain backwards compatibility as much as could, in the end it proved to be just too hard. I'll check if it works for me a bit later (I need another laptop to do this);  if not, I'll ask you to provide some details and maybe rebuild and test your system with patches for additional debugging information, if you don't mind.

**Comment by cillianderoiste** [comment]
Thanks! I would be happy to test.
