### ISSUE TITLE
Doc: use authentic example for cherry-picking for stable

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#66207]
Current example is "nixos: Refactor the world."

I think such a change should in most cases not be backported. I think most of the time, backports are fixes or package updates which fixes problems.

Also use a reason in example that can in most cases just be copy and pasted, like:

"Reason: Fix needed in stable release too"

The current example says that, but in a funny or offensive manner:

"Reason: I just had a gut feeling that this would also be wanted by people from
the stone age."

This don't add any value here, might even confuse users and should probably not be accepted in a real PR.

https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches

**Comment by pwetzel** [comment]
I just stumbled across this. This is fixed in current documentation, this issue can be closed.

**Comment by davidak** [comment]
oh yeah, i fixed that :smile:
