### ISSUE TITLE
virtualbox: fails to start, Qt error

### ISSUE THREAD

**Issue by angristan** [NixOS/nixpkgs#66200]
**Describe the bug**

Cannot start Virtualbox:

```
août 06 13:41:06 nixpsla virtualbox.desktop[2469]: Qt WARNING: Could not find the Qt platform plugin "xcb" in ""
août 06 13:41:06 nixpsla virtualbox.desktop[2469]: Qt FATAL: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**To Reproduce**
1. Open virtualbox

**Expected behavior**

Virtualbox should start

**Additional context**

I saw this mentioned here: https://github.com/NixOS/nixpkgs/issues/65448#issuecomment-515971498

But the related fixes have been pushed to master a week ago, I think?

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.21, NixOS, 19.09pre187507.525eaf407d4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre187507.525eaf407d4, home-manager, nixos-hardware"`
 - channels(stanislas): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
The issues are https://github.com/NixOS/nixpkgs/issues/65399.
That issue should have many linked examples and documentation on how this can be fixed.

**Comment by angristan** [comment]
Thanks! Shall we close this one then?

**Comment by worldofpeace** [comment]
> Thanks! Shall we close this one then?

No, we should keep it open so someone can act on it specifically.

**Comment by angristan** [comment]
OK :) I don't really understand what all these issues are about so I will let someone else fix this

**Comment by angristan** [comment]
Thanks @worldofpeace!

**Comment by turion** [comment]
@worldofpeace @angristan This issue is open for me again at least since b839d4a8557adc80e522f674529e586ab2a88d23.
