### ISSUE TITLE
haskell-ng: taglib: pkg-config dependency taglib_c not found

### ISSUE THREAD

**Issue by JLimperg** [NixOS/nixpkgs#6622]
When attempting to install `nixpkgs.haskellngPackages.taglib`, the build fails with the following output:

```
Setup: The pkg-config package taglib_c is required but it could not be found.
```

As far as I can tell, the C/C++ taglib is installed correctly on my system and has pkg-config files in `/nix/store/...-taglib-1.9.1/lib/pkgconfig`.

Possible reason: The pkg-config dependency is called `taglib_c` because `taglib` has two different pkg-config targets. Therefore, the auto-generated derivation seems to set `taglib_c = null`. Curiously, the derivation doesn't show up in Hydra at all from what I can tell.

**Comment by peti** [comment]
I committed a fix in https://github.com/NixOS/cabal2nix/commit/aeacd345c9bb877dcafc84e41167169ffda29883.

**Comment by JLimperg** [comment]
Fix works for me. Thank you very much for the quick response!
