### ISSUE TITLE
GHC 8.6.5 does not build on Darwin

### ISSUE THREAD

**Issue by bdesham** [NixOS/nixpkgs#66221]
**Describe the bug**

I’m trying to build the ghc package (currently at version 8.6.5) on Darwin but building fails with the error

```
Configuring ghc-prim-0.5.3...
ghc-cabal: Cannot find the program 'ld'. User-specified path
'/nix/store/fhhahhv5jdh6rvwz42b8a2rr955ll580-cctools-binutils-darwin-wrapper/bin/ld.gold'
does not refer to an executable and the program is not on the system path.

make[1]: *** [libraries/ghc-prim/ghc.mk:5: libraries/ghc-prim/dist-install/package-data.mk] Error 1
make: *** [Makefile:125: all] Error 2
builder for '/nix/store/c7dfl0k04fbw80ghrwcirpc6yq2f50s2-ghc-8.6.5.drv' failed with exit code 2
```

[Full console output](https://github.com/NixOS/nixpkgs/files/3473368/Log.at.2019-08-06.10-05-29.AM.txt) (warning: almost 2 MB)

**To Reproduce**

1. `cd .../my-clone-of-nixpkgs`
2. `git checkout 0f6faf630ff` (this is the exact revision I’m using; it’s the Nixpkgs `master` as of this writing)
3. `nix-build -A ghc`

**Metadata**

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(besham): `"nixpkgs-19.09pre187222.002b853782e"`
 - nixpkgs: `/Users/besham/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ghc
```

**Comment by matthewbauer** [comment]
This is most likely from https://github.com/NixOS/nixpkgs/commit/29f2f04ded458e298e70884c2fd10e05e336f598
