### ISSUE TITLE
Systemd fails to start anything with unstable live usb

### ISSUE THREAD

**Issue by Sciencei** [NixOS/nixpkgs#66239]
**Describe the bug**
When attempting to install nixos from a live usb built off of any of `master` (here; the other two are from `nixpkgs-channels`), `nixos-unstable`, or `nixpkgs-unstable`, systemd fails to start everything, including Emergency mode.

**To Reproduce**
1. Checkout any of the above channels
2. `cd nixos; nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-minimal-new-kernel.nix default.nix`
3. `dd` the iso onto a usb drive
4. Boot into the image, presumably on a specific unfortunate hardware configuration
5. Boot into any of the nixos installers

**Expected behavior**
Systemd starts things up successfully and I get a prompt.

**Screenshots**
Here are the errors. Nothing works at the end, so I'm unable to run systemctl status on anything as it suggests. https://imgur.com/a/hiSIPKF

**Additional context**
Hardware:
  CPU: Ryzen 7 3700x
  GPU: RTX 2070 super
  MB: MPG X570 Gaming Plus
  NIC: Intel Wifi 6 AX200
 
I am able to boot an iso built off of the 19.03 branch (with the kernel set to 5.1.21)

I am able to boot an Arch iso with the 5.2.5 kernel

Changing the kernel of the unstable iso to be 5.1.21 results in the same failure as with the 5.2 kernel.

**Metadata**

I can't run it on the actual iso for obvious reasons. In the repo for building, in this instance in the `master` branch, I get:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.5-arch1-1-ARCH, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(sciencei): `"nixos-19.09pre187731.40e3191a6a0, nixpkgs-19.09pre187222.002b853782e"`
 - nixpkgs: `/home/sciencei/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by andir** [comment]
I Installed a system from master just yesterday. Are you still able to reproduce this?

**Comment by Sciencei** [comment]
No, it seems to work now.
