### ISSUE TITLE
wpa_gui broken at run-time: Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#66259]
Attempts to run `wpa_gui` from the package `wpa_supplicant_gui` fail in recent versions of `master`, i.e. 8ac6b77eff2975f4d0fef2d8c8f6b927cdd300ed:

~~~
$ wpa_gui
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      wpa_gui
~~~

Probably an issue similar to https://github.com/NixOS/nixpkgs/issues/65776.

**Comment by xaverdh** [comment]
This is due to #65399 cc @MarcWeber . Fix is probably to just replace `stdenv.mkDerivation` by an explicitly imported  `mkDerivation`.

**Comment by xaverdh** [comment]
Ok, opened #66262

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/66262.
