### ISSUE TITLE
Moving tt-rss root after setting up service fails because of existing role

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#66260]
**Describe the bug**

After setting up tt-rss I'm unable to change the root path of the service. Subsequent rebuilds are failing.

**To Reproduce**
1. Set up tt-rss with defaults:

    ```
      services = {
        tt-rss = {
          enable = true;
          selfUrlPath = "http://localhost/";
          singleUserMode = true;
        };
    ```
1. `sudo nixos-rebuild switch`
1. Add `root = ''${config.users.users.username.home}/.config/tt-rss'';` to the `tt-rss` dictionary.
1. `sudo nixos-rebuild switch`

**Expected behavior**
The service should start successfully.

**Actual behavior**
```
Job for tt-rss.service failed because the control process exited with error code.
See "systemctl status tt-rss.service" and "journalctl -xe" for details.
warning: the following units failed: tt-rss.service

● tt-rss.service - Tiny Tiny RSS feeds update daemon
   Loaded: loaded (/nix/store/8waydn7vx3cj78fsrbc8fwgpqkh94q3n-unit-tt-rss.service/tt-rss.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-08-07 21:31:48 NZST; 16ms ago
  Process: 10761 ExecStartPre=/nix/store/dav2l4i9yz182i8lv0mhbmbns3ilamh3-unit-script-tt-rss-pre-start (code=exited, status=1/FAILURE)
 Main PID: 5193 (code=killed, signal=TERM)

Aug 07 21:31:47 l0b0land systemd[1]: Starting Tiny Tiny RSS feeds update daemon...
Aug 07 21:31:48 l0b0land sudo[10768]:     root : TTY=unknown ; PWD=/ ; USER=postgres ; COMMAND=/nix/store/7wl70h47ncx0g9syslw09k27f4vplvvj-postgresql-9.6.14/bin/createuser tt_rss
Aug 07 21:31:48 l0b0land sudo[10768]: pam_unix(sudo:session): session opened for user postgres by (uid=0)
Aug 07 21:31:48 l0b0land dav2l4i9yz182i8lv0mhbmbns3ilamh3-unit-script-tt-rss-pre-start[10761]: createuser: creation of new role failed: ERROR:  role "tt_rss" already exists
Aug 07 21:31:48 l0b0land sudo[10768]: pam_unix(sudo:session): session closed for user postgres
Aug 07 21:31:48 l0b0land systemd[1]: tt-rss.service: Control process exited, code=exited status=1
Aug 07 21:31:48 l0b0land systemd[1]: tt-rss.service: Failed with result 'exit-code'.
Aug 07 21:31:48 l0b0land systemd[1]: Failed to start Tiny Tiny RSS feeds update daemon.
warning: error(s) occurred while switching to the new configuration
```

**Additional context**
I doubt it's relevant, but at first I set `selfUrlPath = "http://[hostname]/tt-rss";` (with my actual local hostname instead of `[hostname]`), which installed properly but returned a 404. After going to http://[hostname] and seeing the error message there I changed the setting to `selfUrlPath = "http://[hostname]/";` and re-ran successfully, before finally changing the `root` setting and encountering this issue.

**Workaround**

This at least makes `nixos-rebuild` work again:

```
sudo -u postgres dropdb tt_rss
sudo -u postgres dropuser tt_rss
```

I didn't realize of course the service would not have access to my home directory running as another non-root user, so I've removed the `root` property. I've removed the `root` setting, but I'm not sure whether the failure was caused by access right issues or whether relocating it really is an issue.

**Metadata**
```
$ nix run nixpkgs.nix-info --command nix-info --markdown # package metadata 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.03.173210.b978a94c8f9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173210.b978a94c8f9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:

```yaml
attribute: services.tt-rss.root
```

PS: Would it be OK to clarify exactly what "attributes" and "modules" mean in the above, and exactly how I'm meant to populate those lists?

**Comment by aanderse** [comment]
ping @Nadrieril @telotortium @tek @Mic92 as people who have had some experience with this service/package and may have some ideas.

**Comment by Nadrieril** [comment]
Ok I see the issue. The module knows that the database has been created by leaving an empty file at `${cfg.root}/.db-created`. So if it can't find it, it will try to create the user and database, but in your case that fails. So to fix it, just run `touch /path/to/root/.db-created` and restart the service. Otherwise moving the root should pose no problem as it's recreated every time anyways.
Note that the version of this service currently on master does the check differently so it won't need this hack.

**Comment by Mic92** [comment]
Does this solve the issue for you?

**Comment by l0b0** [comment]
I worked around it manually *somehow,* but I don't think I used @Nadrieril's workaround. Anyway, it's been fixed on master, so we can probably just close this.
