### ISSUE TITLE
Setting CPU freq has no effect

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#66278]
**Describe the bug**

I have a newer Intel CPU (i5-5250U). The p_state driver is used.

I want to set a static frequency to benchmark the performance of a program with a given frequency to see which CPU i need in production.

I followed this https://askubuntu.com/a/702862

I set min and max percent to 10, which results in the minimal value of 18.

```
echo 10 >/sys/devices/system/cpu/intel_pstate/min_perf_pct
echo 10 >/sys/devices/system/cpu/intel_pstate/max_perf_pct

cat /sys/devices/system/cpu/intel_pstate/max_perf_pct
18
cat /sys/devices/system/cpu/intel_pstate/min_perf_pct 
18
```
But the CPU still runs with same frequency as with 100%!

![Screenshot from 2019-08-07 17-41-02](https://user-images.githubusercontent.com/91113/62636829-91fc8d00-b93a-11e9-8d9b-dc8ff71181be.png)

lscpu also shows the default values for min and max:
<details>
  <summary>Click to expand!</summary>
  
```
[root@nuc-dkleuker:~]# lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       39 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
Stepping:            4
CPU MHz:             1670.889
CPU max MHz:         2700.0000
CPU min MHz:         500.0000
BogoMIPS:            3192.81
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap intel_pt xsaveopt dtherm ida arat pln pts
```
</details>

Is it possible that this feature don't work with an i5? I will test with a Xeon later.

**To Reproduce**
1. run mprime

`nix run nixpkgs.mprime -c mprime -t`

(allow unfree packages)

1. see current cpu freq

`lscpu | grep "CPU MHz"`

2. set cpu freq percent to 10%

```
echo 10 >/sys/devices/system/cpu/intel_pstate/min_perf_pct
echo 10 >/sys/devices/system/cpu/intel_pstate/max_perf_pct
```

3. see current cpu freq again

`lscpu | grep "CPU MHz"`

(it's still the same as before)

**Expected behavior**
only 18% of the max GHz should be used

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.56, NixOS, 19.03.173000.1c6bdbc766e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173000.1c6bdbc766e, nixos-hardware, nixos-unstable-19.09pre183832.20b993ef2c9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: linuxPackages
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
It works with a i7-7500U (2.70GHz base freq, 3.50GHz turbo boost).

11% -> 400 MHz (min freq)
20% -> 700 MHz
40% -> 1400 MHz
60% -> 2100 MHz
80% -> 2800 MHz
100% -> 2630 - 2750 MHz (base freq)

I think it should be documented somewhere which CPUs support that. I havn't found anything on the internet. Probably in the linux kernel doc.

So, can someone confirm that i'm right that lower-end Intel CPUs don't support this or is it a bug that we can fix?

**Comment by danbst** [comment]
I don't think this is a kind of problems we want to solve in Nixpkgs (currently). It's hardware, it may work, it may not.

I've had once built a NixOS module for managing this pstate frequency (https://github.com/NixOS/nixos-hardware/pull/101/files#diff-b3acb2a24fc098d15130f0261a43ed78R7). It worked for me.
