### ISSUE TITLE
Java version shipped with android studio not runnable

### ISSUE THREAD

**Issue by Enteee** [NixOS/nixpkgs#66293]
**Describe the bug**
When running a gradle builds in android-studio I get:

```
Process 'command '/nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java'' finished with non-zero exit value 1
```

Running this very same executable in a shell gives me:
```
$ /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java
bash: /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java: No such file or directory
```

which I only ever encountered when the executable is compiled for the wrong architecture or not some shared libraries are missing. But:

```
$ file /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java
/nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, not stripped

$ ldd /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java
	linux-vdso.so.1 (0x00007ffe2191e000)
	libpthread.so.0 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libpthread.so.0 (0x00007fba9ffdf000)
	libjli.so => /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/../lib/amd64/jli/libjli.so (0x00007fba9ffc9000)
	libdl.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libdl.so.2 (0x00007fba9ffc4000)
	libc.so.6 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libc.so.6 (0x00007fba9fe0e000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007fbaa0002000)
```

So I am a bit lost here...

**To Reproduce**

1. `git clone git@github.com:Enteee/Universe.git`
2. `cd Universe`
3. `git reset --hard 827a81d0b862ca596cb783478361c59b879e0f77`
4. `nix-shell`
5. `android-studio`
6. build

**Expected behavior**
Java binary should run

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.136, NixOS, 19.09pre188002.e275a6c2f38 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188002.e275a6c2f38, nixos-hardware, nixpkgs-19.09pre187222.002b853782e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Enteee** [comment]
I might be on the complete wrong path here, but when I did compare the `java` binary in android-studio with the one installed in my user environment I found that the one major difference is that the user environment `java` has a dependency on

```
libz.so.1 => /nix/store/iiymx8j7nlar3gc23lfkcscvr61fng8s-zlib-1.2.11/lib/libz.so.1 (0x00007f51c05ce000)
```

And I have had similar issues I never quite got to the bottom of, involving libz with another binary. Strange enough that `java` version which loads `libz` dynamically seems to work just fine..

_________
```
$ ldd $(which java)
	linux-vdso.so.1 (0x00007ffdcaf4e000)
	libpthread.so.0 => /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libpthread.so.0 (0x00007f1792c6f000)
	libz.so.1 => /nix/store/iiymx8j7nlar3gc23lfkcscvr61fng8s-zlib-1.2.11/lib/libz.so.1 (0x00007f1792c50000)
	libjli.so => /nix/store/4ybi3p3b1llb54kh043s0p6pnp8qisyf-openjdk-8u202bga-jre/lib/openjdk/jre/lib/amd64/jli/libjli.so (0x00007f1792c3d000)
	libdl.so.2 => /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libdl.so.2 (0x00007f1792c38000)
	libc.so.6 => /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6 (0x00007f1792a82000)
	/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/ld-linux-x86-64.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f1792c92000)

$ ldd /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java
	linux-vdso.so.1 (0x00007ffef4efb000)
	libpthread.so.0 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libpthread.so.0 (0x00007f5a7df62000)
	libjli.so => /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/../lib/amd64/jli/libjli.so (0x00007f5a7df4c000)
	libdl.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libdl.so.2 (0x00007f5a7df47000)
	libc.so.6 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libc.so.6 (0x00007f5a7dd91000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f5a7df85000)
```

**Comment by averelld** [comment]
That java executable is run in an FHS environment (it's own chroot env, where lib paths and such look like a normal linux and don't have to be patched). Inside that environment, the java executable runs fine (the problem is the interpreter), you can see this in the segment you pasted:
```
$ file /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java
/nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, not stripped
```
And you can probably just run it inside the android-studio terminal.

Why it doesn't compile is probably a different issue, it could be for example env variables like JAVA_HOME or such leaking which gradle might pick up, or a gradle.properties or other gradle config misconfiguration, or your SDK installs might not be "nix compatible" (I'm not certain non-nix android-studio SDK installs can be shared).  

My suggestion is to try with a fresh android-studio config (eg .Android-Studio*) and clean env and probably a dummy project and see if it still fails.

Also, those reproduction steps are nice, however not exactly reproducible because "with import <nixpkgs> {}" depends on your system configuration, it would be better to provide a fixed revision of that, or just use/mention the latest 19.03 or whichever channel.

**Comment by Enteee** [comment]
thank you for your answer. Just for my understanding: how can I enter such a FHS environment? I thought when I am running `nix-shell` I am already in this environment.

> My suggestion is to try with a fresh android-studio config (eg .Android-Studio*) and clean env and probably a dummy project and see if it still fails. 

I will try that and report back.

> Also, those reproduction steps are nice, however not exactly reproducible because "with import {}" depends on your system configuration, it would be better to provide a fixed revision of that, or just use/mention the latest 19.03 or whichever channel.

I am sorry for this, I thought with the root channel Informtaion: `nixos-19.09pre188002.e275a6c2f38`, this would be the case.

**Comment by averelld** [comment]
It's not usually meant for user-interaction, but you could enter it like this (or use the built-in shell in android-studio):
```
[nix-shell:~/nixpkgs]$ cat $(which android-studio)
#!/nix/store/xfghy8ixrhz3kyy6p724iv3cxji088dx-bash-4.4-p23/bin/bash
/nix/store/86dvnjwrfs9vvwdn77gvs2r6b0ni6jjg-android-studio-stable-3.4.2.0-fhs-env/bin/android-studio-stable-3.4.2.0-fhs-env /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/bin/studio.sh

[nix-shell:~/nixpkgs]$ /nix/store/86dvnjwrfs9vvwdn77gvs2r6b0ni6jjg-android-studio-stable-3.4.2.0-fhs-env/bin/android-studio-stable-3.4.2.0-fhs-env
android-studio-stable-3.4.2.0-fhs-env-chrootenv:ec@reidar:~/nixpkgs$ /nix/store/nzk9d8lrf834rpnf6kyfnx9p2llhxf1g-android-studio-stable-3.4.2.0/jre/bin/java -version
openjdk version "1.8.0_152-release"
```

Ah yes, that channel tag is enough, so I take everything back :)

**Comment by Enteee** [comment]
After I removed all my profile relevant files I am having a hard time reproducing this myself. I'll poke a bit around, but if I can't get the error to trigger again I'll close this issue later.

**Comment by Enteee** [comment]
can not reproduce this anymore. I still struggle to run my application, because libgdx comes with a per-compiled version of libwjgl which does not find it's X-dependencies. But that's probably an other issue which might be fixable by some `LD_PRELOAD` / `patchelf` magic..

**Comment by SRGOM** [comment]
I have a similar issue for me, build tools inside the android sdk downloaded by Android Studio fail to find libraries, among which `zlib` (`libz`) is prominent. Trying to find a way here to make things work.

**Comment by SRGOM** [comment]
Asked here- https://discourse.nixos.org/t/help-understanding-linking-in-nixos/4359
