### ISSUE TITLE
memtest fails with unetbootin

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#6630]

**Comment by Profpatsch** [comment]
(triage) solved?

**Comment by magnetophon** [comment]
If it's the same issue I'm having, it seems unrelated to unetbootin.

When I run memtest (either from usb or from grub), it starts giving errors once it arrives at 53%.
I tested on 3 different PC,s with 5 different ram sticks. 

When I run memtest86+ 5.01 (same version as nixos) from an arch install usb, all is fine.

**Comment by vcunat** [comment]
IIRC my experience was that it didn't even start.

**Comment by magnetophon** [comment]
@vcunat Could you give it a try again?
