### ISSUE TITLE
systemd timer units should be started / restarted on switch

### ISSUE THREAD

**Issue by teh** [NixOS/nixpkgs#6632]
I have a systemd timer which I'm deploying via nixops. So I have a line like this:

```nix
        require = [ ./sentry/module.nix ./backups.nix ];
```

and [2]  is my backups.nix module. I'd argue that new timer units should be started the same way .service units are started which I believe happens in [1].

I can have a look but wanted to record this so I won't forget.

[1]
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/switch-to-configuration.pl

[2]
```nix
{
  options = {};
  config = {
    systemd.timers."backups" = {
      timerConfig.OnBootSec = "15min";
      timerConfig.OnUnitActiveSec = "70min";
      timerConfig.Unit = "backups.service";
    };
    systemd.services."backups" = {
      path = [
        pkgs.nixops
        pkgs.openssh
        pkgs.nix
      ];
      serviceConfig.ExecStart = "/bin/sh ls";
    };
  };
}
```

**Comment by edolstra** [comment]
You should make your timer wanted by `timers.target`. Then it will be started automatically by `switch-to-configuration`.

**Comment by teh** [comment]
Apologies, I figured that out just now while trying to fix the issue. Thanks!

In case someone fins this, the section should look like this:

```
    systemd.timers."backups" = {
      wantedBy = [ "timers.target" ];
      timerConfig.OnBootSec = "15min";
      timerConfig.OnUnitActiveSec = "70min";
      timerConfig.Unit = "backups.service";
    };
```
