### ISSUE TITLE
llvmPackages.lldb is broken in master

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6636]
Looks like the hash for 3.5 is just a copy of the the hash for 3.4, which means it's a mismatch. Fixing that leads to a big string of variations on

```
CMake Error at /nix/store/0w3jjmx6zll8kx1fmvwryz2iib9xp0h0-llvm-3.5.0/share/llvm/cmake/AddLLVM.cmake:282 (set_output_directory):
  set_output_directory Function invoked with incorrect arguments for function
  named: set_output_directory
Call Stack (most recent call first):
  CMakeLists.txt:230 (llvm_add_library)
  source/Plugins/Instruction/ARM64/CMakeLists.txt:3 (add_lldb_library)
```

which I'm not sure how to fix, so I'm leaving this here. 

Calling @shlevy :smile:

**Comment by shlevy** [comment]
Crossing my fingers that 3.6 Just Fixes It, @Ralith might be giving the upgrade a shot soon :smile: But I'll take a look at this too.

**Comment by copumpkin** [comment]
Even if 3.6 does fix it, we probably want to retain support for 3.5 for a while still, right? At some point we should probably kill some of the older LLVM bundles though!

**Comment by vcunat** [comment]
3.5.1 update doesn't fix it by itself.

**Comment by shlevy** [comment]
Dug through the cmake code and I have no idea here, sorry.

**Comment by Ralith** [comment]
lldb 3.6 appears to build fine in #6668, though we won't know for sure until the tests pass.

**Comment by shlevy** [comment]
@copumpkin Do we need `lldb` specifically on 3.5? If it's working on 3.6 I'm not sure we need to ensure it is on all versions, you know?

**Comment by copumpkin** [comment]
Nope, not needed, just a nice-to-have :)

**Comment by vcunat** [comment]
We should at least mark the broken packages as broken. Currently we fail on download, which is misleading.
