### ISSUE TITLE
Freeze after "Starting reboot"

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#66367]
**Describe the bug**
When running the `reboot` command on my laptop it hangs at what looks like the last step of the shutdown process. My desktop machine with almost identical configuration reboots fine.

**To Reproduce**
1. Start desktop environment
2. Run `reboot`

**Expected behavior**
The laptop should reboot

**Additional context**
My laptop is a Samsung NP940X3L.

**Metadata**
```
$ nix run nixpkgs.nix-info --command nix-info --markdown | sed "s/$USER/username/" # package metadata 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.61, NixOS, 19.03.173198.aeeb30a3b29 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173198.aeeb30a3b29"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by angristan** [comment]
Does it just hangs are does it reboot after a few minutes?

**Comment by l0b0** [comment]
@angristan I tried waiting for longer, and yes, it does eventually reboot.

**Comment by angristan** [comment]
Then I have the same issue on my XPS 13, but my guess is that it's a systemd issue since I experienced this on Arch, Ubuntu and Fedora too

**Comment by angristan** [comment]
Although I'm not sure if it was at the last step of the process or because of another service. So it may be NixOS specific.

**Comment by l0b0** [comment]
No longer happening.
