### ISSUE TITLE
Chez and Haskell packages have no derivations

### ISSUE THREAD

**Issue by Apropheci** [NixOS/nixpkgs#66383]
I've installed nixpkgs ontop of my MX Linux install. But when I try to install Chez or any of the Haskell packages (haskellPackages.hoogle), I get an error that it was unable to find any derivations.

I've tried using `nix-env -i chez` as well as `nix-env -qa chez` but it still doesn't find anything.

**Comment by alexarice** [comment]
try ` nix-env -iA nixos.chez` instead of `nix-env -i chez`. In general `nix-env -i` can be a bit funny. (It uses package name instead of attribute name)
Similarly for hoogle `nix-env -iA nixos.haskellPackages.hoogle` should do the trick

**Comment by alexarice** [comment]
For a bit of added explanation, the chez package has it's name defined as `chez-scheme` https://github.com/NixOS/nixpkgs/blob/4a3aa14c32cc8e78f35431eb43bc132cc7e2e36d/pkgs/development/compilers/chez/default.nix#L7
so `nix-env -i chez-scheme` would also work

**Comment by Jessie-Park** [comment]
Unfortunately it doesn't seem to have worked. Even trying to update my channels presented the same error.

```
aprophecy@TheBoi:~
$ nix-env  -iA nixos.chez
error: attribute 'nixos' in selection path 'nixos.chez' not found
aprophecy@TheBoi:~
$ nix-env  -iA chez-scheme
error: attribute 'chez-scheme' in selection path 'chez-scheme' not found
aprophecy@TheBoi:~
$ nix-env  -i chez-scheme
installing 'chez-scheme-9.5.2'
these paths will be fetched (2.38 MiB download, 4.69 MiB unpacked):
  /nix/store/lrabzp3xp0bj60gz3j4324b1z3qlyppf-chez-scheme-9.5.2
copying path '/nix/store/lrabzp3xp0bj60gz3j4324b1z3qlyppf-chez-scheme-9.5.2' from 'https://cache.nixos.org'...
error: cloning builder process: Operation not permitted
error: unable to start build process
aprophecy@TheBoi:~
$ nix-channel --update
unpacking channels...
error: cloning builder process: Operation not permitted
error: unable to start build process
error: program '/nix/store/hbhdjn5ik3byg642d1m11k3k3s0kn3py-nix-2.2.2/bin/nix-env' failed with exit code 1
```

**Comment by alexarice** [comment]
Think it might be nixpkgs.chez instead of nixos.chez if you're not on nixos. You're other error looks unrelated, are you able to install anything?

**Comment by Ekleog** [comment]
Closing for lack of answer. Feel free to reopen with additional details!
