### ISSUE TITLE
Identical outputs despite different outputHashes?

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#66409]
The problem as a screenshot so that the colour of `nix-diff` can be seen:

![image](https://user-images.githubusercontent.com/399535/62814490-7a2b3180-bb11-11e9-9a10-6d367fb9a013.png)

Here it says that the two `.drv`s have different `outputHash`es. But when `nix-store -r`'d, the they return the same file.

Is that expected?

Or is our reproducibility being subverted by Cabal revisions somehow?

Thanks!

**Comment by cdepillabout** [comment]
I guess no one was able to figure this out.  I'll go ahead and close, but if anyone is able to reproduce this, feel free to leave a comment and we can re-open.
