### ISSUE TITLE
Aether client

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#66414]
**Project description**
[Aether](https://getaether.net/) is a peer-to-peer network of independent, self-moderated communities.

It keeps _6 months of posts_ by default. It's gone after. If something is worth keeping, someone will save it within six months – but not from beyond that.  

It's _peer-to-peer,_ and it has no servers. It's privacy sensitive because of that, source IP of any specific public post cannot (easily) be determined. 

Actions of moderators are visible to users. _No content can just 'disappear'_, if something gets deleted, you'll know who did it, why they did it, and if you want, how to get it back. 

Communities can _elect and impeach their own mods by voting_. If a mod behaves inappropriately, users can disable that mod locally as well. 

**Metadata**

* homepage URL: https://getaether.net/
* source URL: https://github.com/nehbit/aether
* license: GNU Affero General Public License v3.0
* platforms: Unix

**Comment by matthew-piziak** [comment]
The client hosted at getaether.net is downloaded in the form of a snap file. If that is the only available format, this issue may be blocked by https://github.com/NixOS/nixpkgs/issues/30336.

**Comment by Parasrah** [comment]
Still important to me

**Comment by maxhille** [comment]
They also have a tarball available. I tried to make a package for it but Nix packaging is too confusing for me. 

I posted my progress at 
 https://github.com/maxhille/nixpkgs/commit/23c34edaf3a3840281bdc41020d6d90deb771fd0

Obviously not a long term solution but enough for trying it out.

**Comment by matthew-piziak** [comment]
Still important to me

**Comment by maxhille** [comment]
Hey folks

By now I am a bit better with NixOS and was able to make a working (at least for me) package. The PR is at https://github.com/NixOS/nixpkgs/pull/130105.

It is my first package addition so let's see how it goes.

**Comment by maxhille** [comment]
Update: Aether is now available in `nixos-unstable`.

@nehbit Do you need anything?

@matthew-piziak I think this issue can be closed now.

**Comment by matthew-piziak** [comment]
@maxhille Agreed. Fabulous work, thank you!
