### ISSUE TITLE
dovecot-pigeonhole: tries to recompile sieve scripts in /nix/store

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#66410]
**Describe the bug**
If sieve scripts are used from /nix/store, dovecot tries to recompile them on every invocation, leading to errors like the following in syslog:
```
Aug 10 00:39:11 myserver dovecot[5683]: lmtp(myaccount@example.com)<19692><Y4JMKw/2TV3sTAAA45U+EQ>: Error: open(/nix/store/8irfvi2zn565s98ybm8bwd2xzc82ki4l-sieve-after/junk-folder.svbin.myserver.19692.48257058e580fb83) failed: Read-only file system
Aug 10 00:39:11 myserver dovecot[5683]: lmtp(myaccount@example.com)<19692><Y4JMKw/2TV3sTAAA45U+EQ>: Error: sieve: binary save: failed to create temporary file: open(/nix/store/8irfvi2zn565s98ybm8bwd2xzc82ki4l-sieve-after/junk-folder.svbin.) failed: Read-only file system
```

**To Reproduce**
1. Add/Set the following on a working mailserver:
```
    services.dovecot2.modules = [ pkgs.dovecot_pigeonhole ];
    services.dovecot2.configFile = ''
      ...
      plugin {
      sieve_after = ${(pkgs.callPackage ./sieve-after.nix {}) }
      ...
      '';
```
2. Watch the syslog for every incoming mail to cause the errors

**Expected behavior**
Dovecot should either accept files with the exact same timestamp to be identical or at least support an option for this.

**Additional context**
There is already a PR for dovecot-pigeonhole at https://github.com/dovecot/pigeonhole/pull/4 that could be merged or added as a patch to the pigeonhole derivation in NixOS to avoid this issue.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.64, NixOS, 19.03pre-git (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173243.9ef3cb9b0ba"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dovecot_pigeonhole
# a list of nixos modules affected by the problem
module: dovecot
```

**Comment by griff** [comment]
When I originally made dovecot/pigeonhole#4 I also made a PR #35536 which includes that patch. But it got stuck and now needs a rebase.
