### ISSUE TITLE
`boot.crashDump.enable = true` severely overheats CPU

### ISSUE THREAD

**Issue by aaronjanse** [NixOS/nixpkgs#66464]
**Describe the bug**
On NixOS generations with boot.crashDump.enable = true, my CPU temperature is consistently > 99° C (and fans at 100%) while my "CPU usage" (according to polybar) is <10%.

I'd provide more debugging information but I'm currently too afraid of damaging my hardware to explore without a plan in mind (CPU temps were peaking at 105° C).

**To Reproduce**  
(I am using a Macbook Pro 12,1)
1. add `boot.crashDump.enable = true` to `configuration.nix`
2. `sudo nixos-rebuild boot`
3. Boot to new generation
4. CPU is severely overheating
5. Boot to previous generation (the one w/out crashDump)
6. Everything is working normally

**Expected behavior**
I expected a NixOS generation with `crashDump` installed to only slightly slow down my system, without causing overheating.

**Additional context**
I am trying to use `crashDump` in an attempt to debug #61851.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.19, NixOS, 19.03.173172.a607a931f6f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(ajanse): `"unstable-19.09pre185259.362be9608c3"`
 - channels(root): `"nixos-19.03.173172.a607a931f6f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- boot.crashDump
```

(I'm not sure if I populated the above code block correctly)

**Comment by vcunat** [comment]
The `"idle=poll"` parameter passed in the module (`nixos/modules/misc/crashdump.nix`) sounds like it might stress the CPU (on a quick glance).  The commit introducing them (a9e5d1ab5) doesn't offer much explanation; perhaps it will be fine without the parameter, at least in your case.  Other than that, I don't think I'm able to help with this.

**Comment by aaronjanse** [comment]
> perhaps it will be fine without the parameter, at least in your case.

Quick question: how can I tell `nixos-rebuild` to use a local nixpkgs repo?

**Comment by thefloweringash** [comment]
> The `"idle=poll"` parameter passed in the module (`nixos/modules/misc/crashdump.nix`) sounds like it might stress the CPU (on a quick glance).

I've also experienced this. `"idle=poll"` [documentation][] says:

```
	idle=		[X86]
			Format: idle=poll, idle=halt, idle=nomwait
			Poll forces a polling idle loop that can slightly
			improve the performance of waking up a idle CPU, but
			will use a lot of power and make the system run hot.
			Not recommended.
			idle=halt: Halt is forced to be used for CPU idle.
			In such case C2/C3 won't be used again.
			idle=nomwait: Disable mwait for CPU C-states
```

[documentation]: https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt

> Quick question: how can I tell `nixos-rebuild` to use a local nixpkgs repo?

```nixos-rebuild -I nixpkgs=./path/to/nixpkgs ...```
