### ISSUE TITLE
Disable cursor theme?

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#66477]
## Issue description

I use `gnome3.adwaita-icon-theme`, but I need only icons, not cursor theme from it. What would be correct solution to disable cursor theme? Currently I just override package derivation, but that takes time to build package on system upgrade
```nix
  adwaita-icon-theme = pkgs.gnome3.adwaita-icon-theme.overrideAttrs (oldAttrs: rec {
    postInstall = ''
      ${oldAttrs.postInstall}
      rm -rf "$out/share/icons/Adwaita/cursors"
    '';
  });
```

## Technical details

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

**Comment by worldofpeace** [comment]
Well I'm pretty sure you need some sort of cursor theme, is it that the cursor theme you've configured doesn't persist or isn't in use?

What DE or WM are you using?

**Comment by gnidorah** [comment]
@worldofpeace I use either sway or i3. So either no DM or default slim
I want to use default cursor theme, and not the one provided by `adwaita-icon-theme`
All I want from `adwaita-icon-theme` is icon theme

**Comment by tadfisher** [comment]
@gnidorah See https://wiki.gentoo.org/wiki/Cursor_themes

**Comment by gnidorah** [comment]
@tadfisher What exactly?

**Comment by gnidorah** [comment]
The solution is to do `rm -r ~/.icons`
