### ISSUE TITLE
nix-prefetch-git produces different store paths from fetchgit

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6651]
It looks like `nix-prefetch-git` always produces `<hash>-git-export` (i.e., `name = "git-export"`), whereas `fetchgit` tries to do fancy things with the basename of the repo URL and the git revision.

**Comment by copumpkin** [comment]
To be clear, the annoyance here is that `nix-prefetch-git` can tell me the hash of the result, but it won't actually prefetch it for a build that uses `fetchgit`, because `fetchgit` won't notice that the work has already been done.

**Comment by zimbatm** [comment]
Do you think we should adopt the same naming heuristic in `nix-prefetch-git` or just use "git-export" everywhere ?

**Comment by zimbatm** [comment]
@copumpkin I got both versions ^ I think the second-one is the nicest because it's still possible to infer what the derivation is based on it's name when looking at /nix/store. In exchange we have that heuristic that might not be 100% equivalent between nix and bash.
