### ISSUE TITLE
pyprof2calltree is hard-coded to Python 2, fails for Python 3 profile results

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#66511]
**Describe the bug**
Not really a "bug", but pyprof2calltree is hard-coded to `pythonPackages` and fails for Python 3 profile results with

```
ValueError: bad marshal data (unknown type code)
```

This can be fixed by changing the expression to `python3Packages.callPackage ...`. Not sure what to do here, move the program to `python3Packages` since Python 2 will be EOL anyway?

**Comment by pmiddend** [comment]
Pinging the maintainer, @sfrijters

**Comment by adisbladis** [comment]
As `pyprof2calltree` can also be used as a library it would make sense to move it into `python3Packages` and let the default `pyprof2calltree` attribute be Python 3.

**Comment by SFrijters** [comment]
@pmiddend My PR has been merged, does this solve the issue for you?
