### ISSUE TITLE
Enable loadable sqlite extensions in Python interpreters in NixOS

### ISSUE THREAD

**Issue by svniemeijer** [NixOS/nixpkgs#66526]
## Issue description

Python comes with its own version of sqlite3 but this not [compiled with loadable sqlite extensions enabled](https://docs.python.org/3/library/sqlite3.html#f1). Having an sqlite3 version with loadable extension support is especially important for modules such as mod_spatialite.

For Python2 there was the alternative of using [pysqlite](https://github.com/ghaering/pysqlite), but since this package is not support for Python3, the only known approach for Python3 is to build python with loadable sqlite extensions enabled.

The request is therefore to have the Python interpreters in NixOS build with loadable sqlite extensions enabled.

As is also explained in [this thread](https://groups.google.com/forum/#!msg/spatialite-users/o0jUwMUqx_g/pfZBDTrWAAAJ) most linux distributions apparently already take this approach.

### Steps to reproduce

```
import sqlite3 
conn = sqlite3.connect(':memory:') 
conn.enable_load_extension(True) 
conn.execute("SELECT load_extension('mod_spatialite')") 

# just a stupid test to check if SpatiaLite really works 
for row in conn.execute("SELECT ST_AsText(MakePoint(11.5, 42.5, 4326))"): 
    print(row)
```

Running this python script will give a ```AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'``` if extensions are not enabled.

If extensions are enabled you will either get the response ```('POINT(11.5 42.5)',)``` if mod_spatialite is available, or an 'image not found' ```sqlite3.OperationalError``` otherwise.

**Comment by FRidh** [comment]
this is in staging-next so closing
