### ISSUE TITLE
`aa-genprof` is broken

### ISSUE THREAD

**Issue by aaronjanse** [NixOS/nixpkgs#66549]
**Describe the bug**
`aa-genprof` is broken due to referencing `/sbin` instead of `${apparmor-parser}/sbin` (I suspect that other apparmor tools are also affected)

**To Reproduce**
1. add `security.apparmor.enable = true` to `configuration.nix`
2. `sudo nixos-rebuild switch` (using master of nixpkgs, roughly a0c413f71d0d8bee11529e22e2d06ec47d1e2a75 at the time of writing
3. `aa-genprof firefox` outputs `ERROR: Can't find apparmor_parser at /sbin/apparmor_parser`

**Expected behavior**
I was expecting `aa-genprof firefox` to generate a profile for firefox.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.3, NixOS, 19.09.git.a0c413f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(ajanse): `"unstable-19.09pre185259.362be9608c3"`
 - channels(root): `"nixos-19.03.173172.a607a931f6f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- apparmor-utils
# a list of nixos modules affected by the problem
module:
```

---

I would `git bisect` to find the offending commit, but my current config rebuilds the kernel often (long story, but each rebuild feels like an hour of compiling).

**Comment by Artturin** [comment]
fixed in https://github.com/nixos/nixpkgs/commit/372edacef218efe37e222ada723e100e43ba272f i think
