### ISSUE TITLE
Emacs irony doesn't build

### ISSUE THREAD

**Issue by multun** [NixOS/nixpkgs#66556]
**To Reproduce**
1. force install the irony emacs package with allowBroken
2. 
```
[...]
no Makefile or custom buildPhase, doing nothing
installing
Parsing tar file...
Parsing tar file...done
Wrong type argument: arrayp, nil
builder for '/nix/store/8mwsvlc8lw10rbpfcqsgb435y0qkdghd-emacs-irony-20190703.1732.drv' failed with exit code 255
```

**Expected behavior**
The package builds and works

**Additional context**
It has been introduced by https://github.com/NixOS/nixpkgs/pull/65874/commits/978b34622bccce24f179ffaf4475544dbe2e61dd#diff-b1864d4e308e56ef358dd33142771718R380

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.65, NixOS, 19.09pre188498.4557b9f1f50 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188498.4557b9f1f50"`
 - channels(multun): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

@adisbladis 

I tried to debug this but couldn't figure it out :(

**Comment by matthewbauer** [comment]
Seeing this too. Not sure what is happening though

/cc @adisbladis @bandlas

**Comment by multun** [comment]
got it, I'll make a pull request tomorrow.

**Comment by matthewbauer** [comment]
It looks like irony-pkg.el is missing from that .tar file, which is causing the error. But why is it not showing up in tar-mode, but is still in the tar file?
