### ISSUE TITLE
nix-prefetch-all-fixed?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6658]
I'm not sure how best to implement this, but say I'm about to fly around the world and want to do some nix work. What I would like is to be able to say "prefetch me all the fixed-output dependencies of this build" and have it do sensible things.

Is there already a nix incantation that will do that? If not, how painful would one be?

**Comment by edolstra** [comment]
https://nixos.org/wiki/Download_all_sources

**Comment by copumpkin** [comment]
Cool! Seems worth packaging into its own little command, right? Wiki discoverability is low, and it'd be nice to be able to tell someone, "just use command X"

**Comment by bjornfor** [comment]
+1. Being able to guarantee that the next build operation will complete without requiring internet access is a really cool feature.

**Comment by Profpatsch** [comment]
(triage) have you created such a command (or a helper)?

**Comment by AleXoundOS** [comment]
Important for me. But seems to be solved in a [separate ad-hoc project](https://github.com/AleXoundOS/nix-mirror) by me.

**Comment by Profpatsch** [comment]
Closing because nobody has been taking it up.
