### ISSUE TITLE
A hydra-managed unstable branch?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6659]
I'm wondering if we could have hydra bump a branch whenever it would update the unstable channel, so we have an easy way to refer to a near-master state with proper binary artifacts.

**Comment by vcunat** [comment]
There was a script somewhere to do that locally. I guess you do know about it.

**Comment by spwhitt** [comment]
Duplicate of #3609 . Also note that if you're impatient you can use my branch here: https://github.com/spwhitt/nixpkgs/tree/channel-unstable or set up your own with the script I use, located here: https://github.com/spwhitt/nix-channel-branches

**Comment by copumpkin** [comment]
Ah yeah, duplicate, I'll tag along there.
