### ISSUE TITLE
System packages before per-user profiles?

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#66625]
When I show `PATH` on nixos, the system packages come before the per-user packages.

```
$ echo $PATH
/home/syd/bin:/run/wrappers/bin:/home/syd/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/syd/bin
```

Is this intended? Is there a way to switch those two around?

(Context: I'd like a system-wide vim without much config, and a per-user preconfigured vim, and I'd like the per-user package to take precedence.)

**Comment by NorfairKing** [comment]
cc @nh2

**Comment by matthewbauer** [comment]
I think this was fixed in https://github.com/NixOS/nixpkgs/pull/66425

**Comment by NorfairKing** [comment]
Alright, I better upgrade then. Thanks.
