### ISSUE TITLE
Use our lsb_release instead of workarounds

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#66636]
We finally have a working `lsb_release` thanks to PR https://github.com/NixOS/nixpkgs/pull/64258. The issue https://github.com/NixOS/nixpkgs/issues/22729 was known since 2017!

When you search in this repo for "lsb_release", you find a lot of workarounds that are probably not needed anymore. And when there are still issues, we should solve them in our lsb_release implementation.

https://github.com/NixOS/nixpkgs/search?q=lsb_release&unscoped_q=lsb_release

I have implemented a fix for Steam (https://github.com/NixOS/nixpkgs/pull/65822).

It would be great to test and fix other applications before the next stable release of NixOS!

**Comment by timsears** [comment]
Just here to say THANK YOU!

**Comment by davidak** [comment]
still needed

**Comment by prusnak** [comment]
I found only 2 instances of working around lsb_release:
* megasync
* ssm-agent

Sent a PR here: https://github.com/NixOS/nixpkgs/pull/120938

**Comment by Artturin** [comment]
looks like ssm-agent module and package are the only ones left that use a workaround
