### ISSUE TITLE
Use nixpkgs v8 for nodejs

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6667]
[A while ago](https://github.com/NixOS/nixpkgs/commit/925c75c68d72a51c858e59351e7b2b59affe9e5e), we commented out `inherit v8` from nodejs. 

I'm not an expert on node so I'm not clear when that's safe to uncomment, but it seems unfortunate that we have to build a separate v8 package just for node. Can someone who knows more weigh in on whether it's safe to uncomment, or leave more commentary in the package describing when it will be (or that it never will be and why)?

**Comment by lethalman** [comment]
The comment says the reason, v8 3.x is no more maintained.

**Comment by copumpkin** [comment]
Yeah, but it wasn't clear to me whether there was a migration path away from that in the long run or whether it was a short-term hack.

That is, outside of nix, does node just run its own old version of v8? That seems weird if so.

**Comment by lethalman** [comment]
@copumpkin in such cases best look at distros like fedora and debian.

**Comment by Profpatsch** [comment]
looks like it has been on v8 by default for a long time @copumpkin

**Comment by spacekitteh** [comment]
So does this still apply? Can we still make it use nixpkg's v8?

**Comment by Profpatsch** [comment]
No, this isn’t even referenced anymore. I’ll close.

**Comment by spacekitteh** [comment]
Oh, because I was gonna say it should be pursued.

**Comment by Profpatsch** [comment]
@spacekitteh Do you see a point that should be improved still? I’d open a new pull request.
