### ISSUE TITLE
mtr 0.92 -> 0.93 breaks darwin build

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#66688]
The commit 32526e65bd94535194dd74a912dbdb71e3992712 by @peterhoeg introduces a dependency on a Linux-only library, `libcap`. The previous version was working fine on darwin, so at the very least should be offered if 0.93 no longer functions there.

**Comment by 7c6f434c** [comment]
Does overriding with `libcap=null` let you build `0.93`?

**Comment by peterhoeg** [comment]
Yeah, this isn't the first time I break stuff on Darwin - apologies.

**Comment by jwiegley** [comment]
Thanks, @peterhoeg! :)
