### ISSUE TITLE
package request: yaru theme (communitheme) from ubuntu

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#66698]
**Project description**

https://github.com/ubuntu/yaru

**Metadata**

* homepage URL: https://github.com/ubuntu/yaru
* source URL:
* license: lgpl2/lgpl3
* platforms: linux

**Comment by dtzWill** [comment]
Previously: #51153 (which I never finished, sorry, but linking in case helps anyone tackle this).
