### ISSUE TITLE
No archive context menu after installing thunar-archive-plugin

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#66735]
**Describe the bug**
Installing thunar-archive-plugin, either via `environment.systemPackages` or `services.xserver.desktopManager.xfce.thunarPlugins`, does not change the context menu when right-clicking .tar.gz files.

**To Reproduce**
1. Install thunar-archive-plugin as mentioned above
2. Restart Thunar
3. Right-click an archive file

**Expected behavior**

An option to decompress the archive should show up in the context menu.

**Screenshots**

![2019-08-17-100307_3200x1800_scrot](https://user-images.githubusercontent.com/168301/63200969-69f9f000-c0d7-11e9-858e-3442f9e7884a.png)

**Metadata**

```
$ nix run nixpkgs.nix-info --command nix-info --markdown | sed "s/$USER/username/" # package metadata 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.61, NixOS, 19.03.173198.aeeb30a3b29 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173198.aeeb30a3b29"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: xfce.thunar-archive-plugin
```

**Comment by l0b0** [comment]
Still no context menu in 20.03pre196836.1c40ee6fc44

**Comment by Fidgetcetera** [comment]
Getting the same behavior in 21.05, presumably this just never really got touched. In my "advanced" preferences menu, when volman is added to the `thunarPlugins` array, enabling/disabling volume management is an option, but not archive manager. Presumably the archive manager plugin isn't actually installing...? I lack the experience in digging into the technical side of this to answer that more fully.

**Comment by l0b0** [comment]
Unsubbing since I'm no longer using Thunar.

**Comment by pjstadig** [comment]
This seems to be fixed now with the `programs.thunar.plugins` option. I was able to add the archive plugin and get a context menu.

**Comment by minikN** [comment]
> This seems to be fixed now with the `programs.thunar.plugins` option. I was able to add the archive plugin and get a context menu.

@pjstadig Could you post your config? This is mine and it's not working for me (no context menu)

```nix
  config = {
    os.file-manager = "${pkgs.xfce.thunar}/bin/thunar";

    ## Enabling thunar related services
    services.gvfs.enable = true; # Mount, trash, and other functionalities
    services.tumbler.enable = true; # Thumbnail support for images

    ## Installing thunar with some plugins
    programs.thunar = {
      enable = true;
      plugins = with pkgs.xfce; [
        thunar-archive-plugin
        thunar-volman
      ];
    };
  };  
```
