### ISSUE TITLE
libav install fails due to conflict ("out" vs "tools")

### ISSUE THREAD

**Issue by drdaeman** [NixOS/nixpkgs#6682]
I've tried to install libav on a fresh NixOS install, but failed:

    $ nix-env -i libav
    installing ‘libav-11’
    building path(s) ‘/nix/store/jwwf7fgbgs39qwq92bvffmas1jvqvf92-user-environment’
    Wide character in die at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
    collision between ‘/nix/store/zn7270yhlh93r6lii6kkf81nr83s6nrs-libav-11-tools/bin/avconv’ and ‘/nix/store/bxx0iawlw60gmh1v6pwg95fr4152r85j-libav-11/bin/avconv’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
    builder for ‘/nix/store/r7bj3apbvd9xgx9qd7wh9i17rfh31l3p-user-environment.drv’ failed with exit code 255
    error: build of ‘/nix/store/r7bj3apbvd9xgx9qd7wh9i17rfh31l3p-user-environment.drv’ failed

I'm complete newbie to Nix and NixOS, but I suspect this happens due to `cp -s "$out"/bin/* "$tools/bin/"` in `postInstall` ([line 85 in libav/default.nix](https://github.com/NixOS/nixpkgs/blob/c8f2a31de34e43094fd3d7ea9711893152eaa392/pkgs/development/libraries/libav/default.nix#L85)), so libav-11 and libav-11-tools both got the same binary. Maybe I'm wrong, though - I'm really new to this stuff.

I've also tried to install `libav-9.17`, with the same effect and error message (except for different paths in nix store, obviously). Installing by listing `libav` in `environment.systemPackages` helped, as it seems to treat collisions as non-fatal issues (or something like this).

Thanks!

**Comment by vcunat** [comment]
Thanks, I fixed this now on master and 14.12. There was a misunderstanding of mine about interaction of multiple-outputs with nix-env installation by name (maybe it has changed,  I don't know). Anyway, now it installs both outputs, so there's even no point in having those symlinks (at least with installation by name).
