### ISSUE TITLE
Channels not advancing

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#66823]
## Issue description

The `nixpkgs-unstable` channel does not seem to be advancing despite being in good state.

https://howoldis.herokuapp.com/

**Comment by vcunat** [comment]
I saw a couple of stuck jobs (queued) up to 5 days old evals, and I cancelled them.  I assume that was the blocker.

**Comment by danbst** [comment]
@vcunat is "cancelling queued jobs" happening often enough to introduce some automation for that? Is there an issue open for Hydra?

**Comment by vcunat** [comment]
Sometimes it happens that I see a [job "executing"](https://hydra.nixos.org/machines) for several days, which is clearly some kind of stuck state, and not even cancelling will stop the state (but it removes the job from "queued" status).  Normally Hydra does apply a timeout and cancels stuff &ndash; actually the limit is now often too short for us on some aarch64 builds (ghc, llvm, fortran).

**Comment by danbst** [comment]
@vcunat I see there that machine `d3bcab1f` is executing lots of jobs for 1d 6h already. Is that stuck as well?

Also, in case of timeout, is build retried on another, more powerful machine? Is build timeout same for all machines? (yeah, those aarch GHC builds)

**Comment by vcunat** [comment]
IIRC we can increase timeouts per-job from the nix expressions, so I suppose we'll do that for some of the expensive builds, regardless of platform.  _We might also mark them as big-parallel, but that won't make much difference on our current Hydra setup._

**Comment by grahamc** [comment]
I found several jobs hanging on the hydra server, and I've since terminated them.

**Comment by grahamc** [comment]
I just verified that the channel advancement tooling is not having  problems, so presumably it is just the hydra jobs at the moment.

**Comment by vcunat** [comment]
Yes, the channel did update quite fast after I cancelled the laggards, so that part is probably OK.  Some automatic avoidance of these occasional problems would sure be nice, but it doesn't seem to cause too much trouble so far.

**Comment by grahamc** [comment]
One reason we don't automatically do that is usually it represents bugs in Nix, so I try to capture some stack traces to investigate.

**Comment by vcunat** [comment]
Yay, with nix you can dare to debug in production... I guess? (sometimes?)

**Comment by globin** [comment]
It has advanced, nixos-unstable hasn't yet but it looks to be running fine.

**Comment by mmahut** [comment]
It's published.
