### ISSUE TITLE
firefox: Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

### ISSUE THREAD

**Issue by blueyed** [NixOS/nixpkgs#6698]
I am trying to use Firefox in a non-NixOS environment (`Ubuntu 14.04.2 LTS`), but it fails to locate the murrine theme engine.

From strace:

    open("/home/user/.gtkrc-2.0", O_RDONLY) = 6
    open("/usr/share/themes/Ambiance/gtk-2.0/gtkrc", O_RDONLY) = 7

    (firefox:15975): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

`~/.gtkrc-2.0` contains:

> include "/usr/share/themes/Ambiance/gtk-2.0/gtkrc"

And this one is based on the murrine engine.

I have installed `gtk-engine-murrine-0.98.2`, which does not make a difference.

**Comment by blueyed** [comment]
This can be fixed by setting:

    GTK_PATH=~/.nix-profile/lib/gtk-2.0

The firefox wrapper contains this line:

> export GTK_PATH=$GTK_PATH${GTK_PATH:+:}/nix/store/v6advmc32999b2ckg43v9q8klz2agdc2-libcanberra-0.30/lib/gtk-2.0/

**Comment by blueyed** [comment]
This patch makes Firefox pick up the theme engine's path.

This is probably not the correct approach, but maybe in the right direction?

    diff --git i/pkgs/misc/themes/gtk2/gtk-engine-murrine/default.nix w/pkgs/misc/themes/gtk2/gtk-engine-murrine/default.nix
    index 81609ef..9eab270 100644
    --- i/pkgs/misc/themes/gtk2/gtk-engine-murrine/default.nix
    +++ w/pkgs/misc/themes/gtk2/gtk-engine-murrine/default.nix
    @@ -10,6 +10,11 @@ stdenv.mkDerivation {
     
       buildInputs = [ pkgconfig intltool gtk2 ];
     
    +  # For pkgs/applications/networking/browsers/firefox/wrapper.nix.
    +  passthru = {
    +    gtkModule = "/lib/gtk-2.0/";
    +  };
    +
       meta = {
         description = "A very flexible theme engine";
         license = stdenv.lib.licenses.lgpl3;
    diff --git i/pkgs/top-level/all-packages.nix w/pkgs/top-level/all-packages.nix
    index 04a592a..0c11971 100644
    --- i/pkgs/top-level/all-packages.nix
    +++ w/pkgs/top-level/all-packages.nix
    @@ -11628,7 +11628,7 @@ let
           libs = [ gstreamer gst_plugins_base ] ++ lib.optionals (cfg.enableQuakeLive or false)
                  (with xlibs; [ stdenv.cc libX11 libXxf86dga libXxf86vm libXext libXt alsaLib zlib ]);
           gst_plugins = [ gst_plugins_base gst_plugins_good gst_plugins_bad gst_plugins_ugly gst_ffmpeg ];
    -      gtk_modules = [ libcanberra ];
    +      gtk_modules = [ libcanberra gtk-engine-murrine ];
         };
     
       retroArchCores =

**Comment by vcunat** [comment]
Well, having absolute references to ``/usr/*`` paths in your config files isn't a good thing. However, I don't know myself how gtk theme engines can be located (with nix or generally). @lethalman might know better.

**Comment by blueyed** [comment]
@vcunat 
IIRC the path in `passthru` is not absolute, but relative to the derivation.
(regarding my patch above)

**Comment by vcunat** [comment]
@blueyed: I meant the reference from your ``~/.gtkrc-2.0``.

**Comment by FRidh** [comment]
This is quite an old issue. If the issue is still present, please reopen.
