### ISSUE TITLE
fetchgit: use leaveDotGit as input for the hash, i.e. rebuild if it changes

### ISSUE THREAD

**Issue by blueyed** [NixOS/nixpkgs#6700]
Changing the `leaveDotGit` argument to fetchgit (and probably likewise for `fetchSubmodules`) does not cause the source to be re-fetched / rebuild.

~~I could imagine using these in the (internal) `outputHash` maybe?~~

**Comment by jagajaga** [comment]
Works fine for me
```bash
$ nix-prefetch-git --url  https://github.com/kien/ctrlp.vim
Initialized empty Git repository in /tmp/git-checkout-tmp-cQbXx1px/git-export/.git/
.....
path is /nix/store/v08x4g7mdwxvqf7xy8p6kjw1mfw825x4-git-export
...
$ nix-prefetch-git --leave-dotGit --url  https://github.com/kien/ctrlp.vim
Initialized empty Git repository in /tmp/git-checkout-tmp-9fGInkgp/git-export/.git/
.....
path is /nix/store/8kcrqy9mcpvc4h1jzmar42rmvwcr2dpb-git-export
```

**Comment by blueyed** [comment]
Yes, but that fetches it always anyway ( - which is good to know as a workaround).

I am meaning "fetchgit" as uses in derivations:

    with import <nixpkgs> {};

    pkgs.lib.overrideDerivation pkgs.awesome (attrs: {
      name = "awesome-git";

      src = fetchgit {
        name = "awesome-git";
        url = "git://github.com/awesomeWM/awesome.git";
        rev = "4636b111b444c874f1f5f41427f8f5d2a9bae556";
        sha256 = "1p2i8bazn7hi7c1dzhnbkxzfisyzaaqwhlwkfnpqszvc23i1w5bz";
        # Keep .git dir for `git describe` during build.
        leaveDotGit = true;
      };
    })


The only way appears to be using this in the `name`. From the nix manual:

> For fixed-output derivations, on the other hand, the name of the output path only depends on the outputHash* and name attributes, while all other attributes are ignored for the purpose of computing the output path. (The name attribute is included because it is part of the path.)

But because of limiting the `git fetch` to `depth 1` it's not possible for the build to properly use `git describe` anyway..

**Comment by nbp** [comment]
Is the sha256 identical when you add the `leaveDotGit` or the `fetchSubmodules` arguments?  I can understand that if you leave the same sha256 fixed output, Nix will assume that we already have resolve this derivation, and that you have no need for fetching the same content.

**Comment by blueyed** [comment]
> Is the sha256 identical when you add the leaveDotGit or the fetchSubmodules arguments?

It wouldn't be, because the contents differs.  But there's no check, because the hash is fixed and provided.

**Comment by Profpatsch** [comment]
(triage) what’s the status?

**Comment by grahamc** [comment]
The problem is you're telling nix exactly what to expect and sees it already has it. I think there is a usability issue around this problem in a greater sense.
