### ISSUE TITLE
Please create a new repository nixpkgs-draft for imperfect packages

### ISSUE THREAD

**Issue by SRGOM** [NixOS/nixpkgs#67026]
I have submitted a new package in the past https://github.com/NixOS/nixpkgs/pull/60666 and the amazingly nice maintainers @teto @symphorien  @alexarice  spoon fed me the steps which will make the PR worthy of inclusion. I couldn't afford to spend any more time on the project and hence I had to leave it there. I am also on a limited data and learned only yesterday from irc user spharelite that the repo could be upto 1.8GB. While I think that the current monorepo approach is probably *the* best approach by far, and responsible for rank #1 on repology, I also think that nix makes packaging too simple and hence there might be people besides me who don't go the extra mile to make it perfect. 

Two more examples of this- https://www.reddit.com/r/NixOS/comments/cq8zdj/gtick_metronome/ and https://discourse.nixos.org/t/where-to-submit-nixpkgs-patch/3735 

Besides, I have two other packages, both of which are in arch official repositories and not in nixpkgs lying in my custom nix config (because I cannot afford to spend any more time). 

If there were a repository which would accept draft (under a free-for-all license), I think a lot of custom packages people have built using `import <nixpkgs>`  would show up. 

The repository would have a very loose structure- 

1) License in root dir. 

2) User created directory per project. Someone in their free time could go and take on, fix it and make it movable to nixpkgs and then delete it from there. The user created directory could have a README in a fixed format so it's easy to glance what needs to be done. 

I have created a repository with points I mentioned above- see- https://github.com/srgom/nixpkgs-draft. Please feel free to copy paste stuff from it into the new repo if you agree to create one. 

I don't have a discourse account so unforunately cannot discuss this idea there.

**Comment by teto** [comment]
There is https://github.com/nix-community/NUR that groups up some user overlays.

Nix will receive soon (I hope) a mechanism ("flakes") that should make dealing with 3rd parties easier.

**Comment by SRGOM** [comment]
Thanks, this was new (and nice) for me. It seems to me that this serves as a replacement for AUR- packages that will never be in official Nixpkgs repository are enumerated there. 

What I was proposing is packages that are cool and useful (2 (gpick, ttf-indic-otf) of the 3 I have created belong to Arch official repository, one (gtick) from reddit belongs to Debian stable) and eventually need to find their way into nixpkgs but need effort could be committed there for somebody to pick up. 

I know it may seem like 10 minutes of work but I have lost all motivation after battling the gpick issue...

**Comment by teto** [comment]
having lingering PRs creates a burden on maintainers too, if you want people to discover your current packages, then NUR might be the best way to allow for a centralized search. 
The gtick example looks simple so in that case, I wouldn't worry about people writing a package from scratch.

**Comment by SRGOM** [comment]
Fair point. My intention though wasn't for maintainers to pick up those from draft, it was for other volunteers... Maintainers are already overburdened as I see... 

Thank you for the discussion and your help with NixOS in general

**Comment by jtojnar** [comment]
> It seems to me that this serves as a replacement for AUR- packages that will never be in official Nixpkgs repository are enumerated there.

I do not see why packages from NUR, when mature enough, could not be promoted to nixpkgs. I believe they do that in Arch land too.

> it was for other volunteers... Maintainers are already overburdened as I see...

People who volunteer are usually overburdened too, as there is so much work to volunteer for.

-----

I personally do the following: I open a draft PR, and when I lose interest, I close it and invite others to take over if they feel like it, in a comment. That way people can find that someone already attempted to package it and can decide to continue from there. Maybe we should add a new tag `9.needs: takeover` to make them even easier to find.

**Comment by SRGOM** [comment]
I like the idea of `9.` Pretty much resolves my issue...
