### ISSUE TITLE
gnupg package does not provide gpg program

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#6706]
despite the bash hook suggesting that it should. 

```
[anders@gurney:~] $ gpg
The program ‘gpg’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -i gnupg
  nix-env -i gnupg1compat
[anders@gurney:~] $ nix-env -i gnupg
installing ‘gnupg-2.1.2’
[anders@gurney:~] $ gpg
The program ‘gpg’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -i gnupg
  nix-env -i gnupg1compat
[anders@gurney:~] $ nix-env -e gnupg
uninstalling ‘gnupg-2.1.2’
[anders@gurney:~] $ nix-env -i gnupg1compat
installing ‘gnupg1compat-0’
[anders@gurney:~] $ gpg
gpg: Go ahead and type your message ...
^C
gpg: signal Interrupt caught ... exiting

```

**Comment by wkennington** [comment]
That's because there are multiple derivations called gnupg. Any 2.x gnupg
provides only thr gpg2 binary while gnupg 1.4 provides gpg. Gnupg1compat
provides gpg2 as gpg.

**Comment by copumpkin** [comment]
It seems like sticking a version number into a binary name is a very "un-nixy" thing to do, even if they do so by default. Can we just change it? It seems like an artifact of a world where all packages share the same namespace.

**Comment by the-kenny** [comment]
That might create issues where programs who think they need gnupg-2 try to call ```gpg2```. As long as it's common (as of https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG.html) to name the binary in a gnupg-2 installation ```gpg2```, we should stick to it

**Comment by wkennington** [comment]
For reference #1126

**Comment by anderspapitto** [comment]
#1126 seems to be exactly the same as what I'm reporting. Feel free to close as a dup.

**Comment by wkennington** [comment]
Duplicate
