### ISSUE TITLE
Add corresponding llvm to ghc's PATH

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#6707]
I just got bitten by having LLVM 3.5 in PATH and attempting to build with `-fllvm`. That led me to a thought -- why don't we add a wrapper to ghc which would prefix needed llvm version? IIRC there are even proposals to embed "recommended" version of llvm within GHC build (3.4, 3.5 and 3.6, again incompatible, in the future). This wrapper would also simplify things later when 7.10 is released for those who want to use latest possible LLVM for each compiler.

Upside is `-fllvm` working out of the box and different llvm version in PATH not messing with compilation.
One possible downside is that we gain another dependency on all the Haskell libraries (it can be avoided on GHC itself, however, by having wrapper in an another derivation).

cc @peti

**Comment by peti** [comment]
IMHO, it's quite feasible to add a flag to the `ghcWithPackages` derivation that allows users to include `llvm` into the generated environment if they want. We cannot depend on `llvm` unconditionally, though, because the derivation is too large to include it for everyone, even if they don't use it.

**Comment by abbradar** [comment]
Good idea, let's have it this way. I'll come up with a patch later, if you don't mind.

**Comment by peti** [comment]
Merged to `master`.
