### ISSUE TITLE
nixos/tests/containers-imperative.nix broken

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#67174]
**Describe the bug**
Imperative container test broken
https://hydra.nixos.org/build/98994622

**To Reproduce**
`nix-build nixos/tests/containers-imperative.nix`

**Additional context**
Bisect reveals #66846 as the cause

cc @uvNikita

**Comment by uvNikita** [comment]
@srhb Thanks for noticing and creating an issue!
