### ISSUE TITLE
viber -- wrong sha256

### ISSUE THREAD

**Issue by gabysbrain** [NixOS/nixpkgs#67185]
**Describe the bug**

When installing viber, the download step won't complete because the package has an incorrect sha256. My nixos version is 19.03.173335.5e5a51f7868 (Koi)

**To Reproduce**
Ensure that you can install non-free packages:
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

then:
`nix-env -iA nixos.viber`

**Expected behavior**

Viber should install

**Screenshots**

```
building '/nix/store/rpz3rsrgy1kmqn65ajws3msvx1s9lkhc-viber.deb.drv'...

trying https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.0M  100 80.0M    0     0  49.4M      0  0:00:01  0:00:01 --:--:-- 49.3M
hash mismatch in fixed-output derivation '/nix/store/d8fa5z2rl1sf5v29ixyz6vh26rfrgp7c-viber.deb':
  wanted: sha256:06mp2wvqx4y6rd5gs2mh442qcykjrrvwnkhlpx0lara331i2p0lj
  got:    sha256:0z7ykrhj3iq4y319c614yh2whkwwfaj54c9rs51nc64czjddkmx5
```

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by kisik21** [comment]
This is still reproducible. Is there an archive of Viber versions anywhere so we can pin Viber versions or do we have to constantly play catch-up with them?

**Comment by alexandru-bitlan** [comment]
I have the same issue, but in my case the SHA got is different:
```
trying https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.0M  100 95.0M    0     0  10.7M      0  0:00:08  0:00:08 --:--:-- 11.0M
hash mismatch in fixed-output derivation '/nix/store/gb3nafqslnmmrz3853wxll4k4vdjj68b-viber.deb':
  wanted: sha256:06mp2wvqx4y6rd5gs2mh442qcykjrrvwnkhlpx0lara331i2p0lj
  got:    sha256:0rs26x0lycavybn6k1hbb5kzms0zzcmxlrmi4g8k7vyafj6s8dqh
```
