### ISSUE TITLE
simutrans prints errors (it couldn't load wav files)

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#6719]
All I know:

```
could not load wav (Couldn't open /nix/store/fcx78g7di8vcbwpi3a6g7i7979adaaq2-simutrans-112.3/share/simutrans//nix/store/chx28dwb988m1y7hys7vq13qk63wkrcb-simutra)
```

It's not that important to me... but should be reported, I guess.

**Comment by vcunat** [comment]
That's probably why it's without sound.

**Comment by matthiasbeyer** [comment]
I guess, yes. I don't care that much about sound when playing this game, but I guess someone else does, so I reported this error.

Maybe this should have a label "nice2have" or something...

**Comment by vcunat** [comment]
We have "enhancement" label, but this *is* a bug, although I agree the sound isn't important for me.
