### ISSUE TITLE
python.withPackages: propagatedBuildInputs don't populate site-packages

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#67211]
**Describe the bug**
I wanted to use `fire`, but it didn't work out of box. I've made an override (using `python.override`) and created an environment with `myPyEnv.withPackages (p: [ p.fire ])`. However, still got an error
```
ModuleNotFoundError: No module named 'termcolor'
```
Which is strange, as I've explicitly added `self.termcolor` to `propagatedBuildInputs` of `fire`.

When running with `myPyEnv.withPackages (p: [ p.fire p.termcolor ])`, all works fine.

**To Reproduce**
```
with import <nixpkgs> {};
let
    py = python3.override {
        self = py;
        packageOverrides = self: super: {
            fire = super.fire.overrideAttrs (old: rec {
                version = "0.2.1";
                src = super.fetchPypi {
                    inherit version;
                    inherit (old) pname;
                    sha256 = "6865fefc6981a713d2ce56a2a2c92c56c729269f74a6cddd6f4b94d16ae084c9";
                };
                propagatedBuildInputs = old.propagatedBuildInputs ++ [
                    self.termcolor
                ];
                patches = [];
                doCheck = false;
            });
        };
    };
    pyEnv = py.withPackages (p: with p; [ fire ]);
    example = pkgs.writeScript "example.py" ''
        import fire
        def main():
            pass
        fire.Fire()
    '';
in runCommand "fire-build" {} ''
    ${pyEnv}/bin/python ${example}
''
```

**Expected behavior**
Well, I've expected propagatedBuildInputs are propagated to `withPackages` env as well.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.4, NixOS, 19.09.git.a99a93b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixpkgs-19.09pre178281.76fad451105, calibre-nixpkgs, nixos-19.03pre155751.45a419ab5a2"`
 - channels(danbst): `"nixpkgs-master"`
 - nixpkgs: `/home/danbst/dev/nixpkgs`

**Comment by danbst** [comment]
cc @FRidh

**Comment by FRidh** [comment]
Only libraries are included.

**Comment by danbst** [comment]
@FRidh I assume, it is wrong to assume that `propagatedBuildInputs` will ever be propagated to `.withPackages` environment? It isn't urgent, I'll change to `question` then.

**Comment by FRidh** [comment]
`overridePythonAttrs` needs to be used instead of `overrideAttrs` so `toPythonModule` gets called again and `passthru.requiredPythonModules` is updated.
