### ISSUE TITLE
SSL certificate not OK for cache.nixos.org installing nixos from Fedora

### ISSUE THREAD

**Issue by caaaaaa** [NixOS/nixpkgs#67210]
**Describe the bug**
I am installing NixOS from a running Fedora installation as is described in chapter 2.5.4 of the manual. 
After issuing 

    bash-5.0$ sudo PATH="$PATH" NIX_PATH="$NIX_PATH" `which nixos-install` --root /mnt 

the installer tries to get binaries from the cache, but fails.

    warning: unable to download 'https://cache.nixos.org/nix-cache-info': SSL peer certificate or SSH remote key was not OK (60); retrying in 340 ms
    warning: unable to download 'https://cache.nixos.org/nix-cache-info': SSL peer certificate or SSH remote key was not OK (60); retrying in 523 ms
    [...]

It then continues to build some 2000 packages, which is all good, but might be improved by using the cache. 

**To Reproduce**
1. Follow the instructions on https://nixos.org/nixos/manual/index.html#sec-installing-from-other-distro (using Fedora 30)
2. Start the Installation
3. Wait

**Expected behavior**
I could not find any information where the keys were supposed to come from, or might be acquired, so either the documentation should be updated to include steps to get them, or they should be installed automatically. 

**Additional context**
I install NixOS for the first time, and so don't know much about what i am doing, but thought, since those that use it already probably don't test the installation so often, a bug report might be helpful. Feel free to close if not. 

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
Sorry, nixos-install is running for probably some days

**Comment by mightybyte** [comment]
I'm also seeing this issue.  I installed nix in multi-user mode on Fedora.  The install seemed to go fine but now I can't get any packages.

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/issues/70939 seems to be the same issue, with some pointers and possible fixes.
