### ISSUE TITLE
Default window manager (pantheon) not found.

### ISSUE THREAD

**Issue by aaronjanse** [NixOS/nixpkgs#67224]
**Describe the bug**

**To Reproduce**
1. Add `services.xserver.desktopManager.pantheon.enable = true` to `configuration.nix`
2. `sudo nixos-rebuild switch` errors `Default window manager (pantheon) not found.`

**Expected behavior**
NixOS starts using Pantheon, probably requiring a reboot.

**Additional context**
I recall getting around this issue in the past, but either way the error message is unhelpful.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.8, NixOS, 19.03.git.e36f91f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(ajanse): `"unstable-19.09pre188690.8746c77a383"`
 - channels(root): `"nixos-19.03.173172.a607a931f6f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- nixos/modules/services/x11/window-managers
```

**Comment by worldofpeace** [comment]
Do you mean this `trace`?
```
trace: Default desktop manager (pantheon) not found at evaluation time.
These are the known valid session names:
  services.xserver.desktopManager.default = "xterm";
  services.xserver.desktopManager.default = "none";
It's also possible the default can be found in one of these packages:
  elementary-session-settings-5.0.3
```

That's a known issue with using the upstream xsessions.

**Comment by worldofpeace** [comment]
I can reproduce this when using
``` 
services.xserver.windowManager.default = "pantheon";
```

and Pantheon is a **desktopManager** not a `windowManager`.

The pantheon module already does this
```
services.xserver.desktopManager.default = mkForce "pantheon";
```

**Comment by aaronjanse** [comment]
Ah, okay, that seems to be the problem. I didn't catch this because Nix didn't complain about me specifying conflicting values across my files. Thanks!
