### ISSUE TITLE
Problem starting chromium

### ISSUE THREAD

**Issue by MasseR** [NixOS/nixpkgs#67234]
**Problem starting chromium**
Starting chromium ends with "undefined symbol".

**To Reproduce**

```
$ nix run nixpkgs.chromium -c chromium
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
/nix/store/ypm0s05hl2cxicy5nwgqh96nrp0cjabq-chromium-unwrapped-76.0.3809.100/libexec/chromium/chromium: symbol lookup error: /nix/store/hx3mk2bnjp4vlqfwzmycvdq3hh6vf71j-libselinux-2.7/lib/libselinux.so.1: undefined symbol: pcre_free_study
```

**Expected behavior**
I would expect chromium to start.

**Screenshots**

**Additional context**
If I check what the actual binary is from `readlink -f $(which chromium)`, I can start the browser, so the problem is one of the environment variables.

I tried commenting out the exports and I could "fix" the problem locally by commenting out the `LD_LIBRARY_PATH`.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.9, NixOS, 19.09pre189585.1412af4b2cf (Loris)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"home-manager, nixos-19.09pre189585.1412af4b2cf, unstable-19.09pre186574.88d9f776091"`
 - channels(masse): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ivan** [comment]
I can't reproduce this by running `nix run nixpkgs.chromium -c chromium` on NixOS master.

The error message indicates that this is a problem with grep. Does `grep` work for you elsewhere?

Are you still seeing this? Do you have any relevant system configuration or bashrc/zshrc?

**Comment by MasseR** [comment]
Yeah, grep works elsewhere. And even chromium starts, if I copy the wrapper script to my home, modify the `LD_LIBRARY_PATH` line and only then call it.


`nix-store --verify --check-contents` was clean.

I tried within a "clean" bash shell (I usually use zsh so the bash config should be somewhat empty, unless some transient derivation modifies it)

**Comment by ivan** [comment]
Thanks for investigating, I have reproduced this with:

```
# touch libpcre.so.1
# chmod +x libpcre.so.1
# chromium --user-data-dir=/tmp/deleteme
grep: error while loading shared libraries: libpcre.so.1: file too short
/nix/store/pzx588yd5799gc5f9sysh41xzqf7vd4x-chromium-unwrapped-76.0.3809.87/libexec/chromium/chromium: error while loading shared libraries: libpcre.so.1: file too short
```

and I'll have a PR soon.

**Comment by MasseR** [comment]
Great! Thank you
