### ISSUE TITLE
NixOS install in VMWare VM print_req_error: I/O error

### ISSUE THREAD

**Issue by razvan-panda** [NixOS/nixpkgs#67248]
**To Reproduce**

* have a VMWare VM
* install NixOS in the VM using the MBR instructions

**Expected behavior**

NixOS to boot.

**Screenshots**

![](https://i.imgur.com/sOKtmWa.png)

**Comment by emmanuelrosa** [comment]
Why is your NixOS installation attempting to read from the CDROM/DVDROM (sr0) during boot?

**Comment by razvan-panda** [comment]
@emmanuelrosa I did not create NixOS or Linux so I have no idea. Good question though!

**Comment by razvan-panda** [comment]
After a reboot the system worked without any issues.
