### ISSUE TITLE
apr doesn't cross-compile

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#67259]
**Describe the bug**
apr doesn't cross-compile. That's all. Apache and PHP depend on it (though PHP may be compiled without it).

The reasons need to be debugged by someone who's familiar with this software, I couldn't fix this myself. When I tried to fix the configureFlags to go around some tests, it spewed some cryptic-looking errors to me.

**To Reproduce**
`nix-build '<nixpkgs>' -A apr --arg system builtins.currentSystem --arg crossSystem '{ system = "armv7l-linux"; }'`

**Expected behavior**
apr should be cross-compiled successfully.

**Additional context**
This could be a serious issue for cross-compiling server systems, as Apache is very popular.

Here's how Gentoo solved this problem: https://github.com/gentoo/gentoo/blob/master/dev-libs/apr/apr-1.6.5-r1.ebuild (look for sections under `tc-is-cross-compiler` conditional)
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.09pre186857.239fffc90d7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"cleveca22, nixos-19.09pre186857.239fffc90d7"`
 - channels(kisik21): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - apr
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
static musl build that uses cross infra now functions with https://github.com/NixOS/nixpkgs/pull/76827.

**Comment by FRidh** [comment]
> Here's how Gentoo solved this problem: https://github.com/gentoo/gentoo/blob/master/dev-libs/apr/apr-1.6.5-r1.ebuild (look for sections under tc-is-cross-compiler conditional)

Indeed need to add a couple more of those flags to make cross-compilation work.

**Comment by kisik21** [comment]
Still reproducible under Nixpkgs flake `github:NixOS/nixpkgs-channels/b3251e04ee470c20f81e75d5a6080ba92dc7ed3f`.

Tries to execute a foreign architecture binary. Gentoo ebuild had a workaround by using the natively-compiled binary in the build process instead - their output is identical.

**Comment by Artturin** [comment]
a patch that fixes it has been made
