### ISSUE TITLE
haskell-ng (ghc 7.10): profunctors fails with oom

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#6726]
profunctors fails to compile because it gets killed by linux because it uses up too much memory (about 14gb before it got killed). This is probably related to the occasional case where compiling with -O 2 causes this. Not quite sure how to disable this with haskell-ng.

**Comment by cocreature** [comment]
Upstream issue: https://github.com/ekmett/profunctors/issues/20

Not sure if I should leave this open? There doesn't seem to be anything we can do about it.

**Comment by peti** [comment]
This is an issue upstream will fix, IMHO.
