### ISSUE TITLE
How to install latest version of aws-cli?

### ISSUE THREAD

**Issue by ORESoftware** [NixOS/nixpkgs#67285]
I am having trouble installing the latest version of aws-cli

after installing with `nix-env -i awscli` the problem is that aws is still pointing to the old install:

```
[root@ip-172-31-0-27:~/.nix-profile/bin]# readlink aws
/nix/store/a2cx0hyg40ifcxyl33bgd6r5lic5xqj5-aws-1.75/bin/aws
```

that's an old version

**Comment by FRidh** [comment]
Install attributes using the attribute names, so `nix-env -iA awscli`. Ensure your channel is up to date as well.
