### ISSUE TITLE
Using PROMP_COMMAND in programs.bash.promptInit stopped working in vte terminals

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#67312]
After the changes in https://github.com/NixOS/nixpkgs/pull/66990 my bash prompt stopped working. It is set in `configuration.nix` with `programs.bash.promptInit`. It sets the environment variable `PROMPT_COMMAND`.

It happens that `${pkgs.vte}/etc/profile.d/vte.sh`, now automatically run for vte terminals, also sets `PROMPT_COMMAND`,  but does not preserve any previous value it may have. As a consequence the setting done in `programs.bash.promptInit` is discarded by `${pkgs.vte}/etc/profile.d/vte.sh`.

**Comment by worldofpeace** [comment]
`interactiveShellInit` happens after `cfg.promptInit` so it can override existing settings.

I noticed that for zsh the ordering is different and `promptInit` comes at the end.
Perhaps that's what needs to be done here, it shouldn't be possible to override a setting that a user makes for their prompt.

**Comment by worldofpeace** [comment]
The script does
```
PROMPT_COMMAND="__vte_prompt_command"
```

Should it do `PROMPT_COMMAND+=`?

**Comment by worldofpeace** [comment]
Ahh this is unexpected because profile.d scripts are sourced before the bashrc file and PROMPT_COMMAND setting.

**Comment by romildo** [comment]
> The script does
> 
> ```
> PROMPT_COMMAND="__vte_prompt_command"
> ```
> 
> Should it do `PROMPT_COMMAND+=`?

I think this is the best solution. But it would require a change in `vte` upstream.
