### ISSUE TITLE
Package request: ClassiCube

### ISSUE THREAD

**Issue by klorophatu** [NixOS/nixpkgs#67378]
**Project description**
ClassiCube is an open source sandbox block game similar to Minecraft Classic
It has a singleplayer mode and a multiplayer mode, there are many servers available on the public server list for anyone to join and you can host your own server

**Metadata**

* homepage URL: https://www.classicube.net/
* source URL: https://github.com/UnknownShadow200/ClassiCube
* license: https://github.com/UnknownShadow200/ClassiCube/blob/master/license.txt.
* platforms: Linux, Windows, OSX, BSD, Solaris

**Comment by marius851000** [comment]
I'm working on it.

**Comment by marius851000** [comment]
Packaged it: https://github.com/NixOS/nixpkgs/pull/67569

**Comment by klorophatu** [comment]
> Packaged it: #67569

Well, since that's done, I don't want to leave this issue floating around for no reason, so I'll close it.

**Comment by klorophatu** [comment]
> Packaged it: #67569

Well, since that's done, I don't want to leave this issue floating around for no reason, so I'll close it.
