### ISSUE TITLE
Package request: gotify

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#67384]
**Project description**
A simple server for sending and receiving messages in real-time per WebSocket. Includes a web UI, also has an Android client for receiving notifications and an optional CLI program (distributed separately) for sending notifications.

**Metadata**

* homepage URL: https://gotify.net/
* source URL: https://github.com/gotify/server
* license: MIT
* platforms: anything Go runs on

**Comment by Ma27** [comment]
I started an attempt locally, however it failed due to some timeouts while fetching Go dependencies... will retry during this week :)

**Comment by kisik21** [comment]
I think the main difficulty is the UI, which needs to be compiled with NPM. In essence, I think the build is three-staged: fetch UI dependencies, fetch Go dependencies, do the actual build.

**Comment by Ma27** [comment]
You may want to take a look at #70441.
