### ISSUE TITLE
nix-build -A ignore overlays

### ISSUE THREAD

**Issue by Alkeryn** [NixOS/nixpkgs#67397]
so i have an overlay for sdrangel, and when doing nix-build -A sdrangel, it builds my overlay instead of the derivation i'm making in a nixpkgs fork

It is annoying since i have to comment out my sdrangel overlay for testing in the meanwhile

**Comment by dasJ** [comment]
`nix-build -I nixpkgs-overlays=` could help here

**Comment by Alkeryn** [comment]
> `nix-build -I nixpkgs-overlays= -A sdrangel` could help here

An empty line don't work, setting it to a random dir does but it is not the most elegant fix ^

**Comment by teto** [comment]
see https://github.com/NixOS/nixpkgs/issues/34410

**Comment by lheckemann** [comment]
`--arg overlays []` should do the trick.

**Comment by FRidh** [comment]
This impurity during evaluation has been a design choice. Not much we can do here aside from offering solutions how *not* to use it.

**Comment by Alkeryn** [comment]
@FRidh just a --pure option would have been nice tho

**Comment by FRidh** [comment]
Check the Nix manual for pure evaluation.

**Comment by FRidh** [comment]
https://github.com/NixOS/nix/commit/d4dcffd64349bb52ad5f1b184bee5cc7c2be73b4
