### ISSUE TITLE
KeePassXC a year out of date

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#67430]
**Describe the bug**

The version of KeePassXC in nixpkgs is 2.3.4, released 2018-08-24. The last release is 2.4.3. There are many usability improvements in the 2.4 series.

**Comment by gloaming** [comment]
It's already in unstable: https://github.com/NixOS/nixpkgs/pull/66572

**Comment by mmahut** [comment]
Indeed, it's in ``unstable`` and will reach 19.09.
