### ISSUE TITLE
fetchFromGitlab results in 404 for at least shrinkpath.el when trying to build doom-modeline

### ISSUE THREAD

**Issue by jappeace** [NixOS/nixpkgs#67434]
**Describe the bug**
If I try to build doom-modeline for emacs it can't find shrinkpath.el with 404.

**To Reproduce**

nix-build this file:
```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.emacsWithPackages (epkgs:
    (with epkgs.melpaStablePackages; [
	doom-modeline
    ])
)
```

**Expected behavior**
It builds

**Additional context**
Looking at the resulting derivation it seems that the generated url from fetchFromGitlab is wrong:
https://gitlab.com/api/v4/projects/bennya%2Fshrink-path.el/repository/archive.tar.gz?sha=a94c80743280fe317cf56cd4d4cd6385ce9e3dfb

This does work however:
https://gitlab.com/bennya/shrink-path.el/repository/archive.tar.gz?sha=a94c80743280fe317cf56cd4d4cd6385ce9e3dfb

Is the fetcher broken? (https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgitlab/default.nix)
Or is the generated derivation broken? 

Possibly related: https://github.com/NixOS/nixpkgs/issues/65796

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.118, NixOS, 19.03.173135.58b68770692 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2574.a7e559a5504, nixos-18.09-18.09, nixos-19.03-19.03.173135.58b68770692"`
 - channels(jappie): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by adisbladis** [comment]
Where are you getting this rev from? It's not in any currently supported channel.

**Comment by jappeace** [comment]
It exists here: https://releases.nixos.org/nixos/19.03/nixos-19.03.173135.58b68770692

Pinned like this:
```nix
  system = {
    # to update:
    # sudo nix-channel --update
    # sudo nix-channel --list
    # click nixos link, and in title copy over the hash
    nixos.version = "19.03.173135.58b68770692";

    # to upgrade, add a channel:
    # $ sudo nix-channel --add https://nixos.org/channels/nixos-18.09 nixos
    # $ sudo nixos-rebuild switch --upgrade
    stateVersion = "19.03"; # Did you read the comment?
  };
```

**Comment by adisbladis** [comment]
I cannot reproduce this at all, even on 19.03 with the pinned rev in question:

`$ nix-build tst.nix`
``` nix
let
  pkgs = import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs-channels/archive/58b68770692.tar.gz") {};
  epkgs = pkgs.emacsPackagesNg;
in {
  spS = epkgs.melpaStablePackages.shrink-path;
  sp = epkgs.melpaPackages.shrink-path;
  dmS = epkgs.melpaStablePackages.doom-modeline;
  dm = epkgs.melpaPackages.doom-modeline;
}
```

If you could produce a minimal example like above for reproduction that would be helpful.

**Comment by jappeace** [comment]
Hi, appearanlty I was using a different version of nix packages in the module, fixed here:

https://github.com/jappeace/linux-config/commit/ac977d86f5627315349e69be07f627b90e2e575d

It's strange because I would've expected to use the same nixpkgs as the parent project:
here:https://github.com/jappeace/linux-config/blob/bto/configuration.nix#L23

Doesn't modules autoamtically fill in that argument?

Anyway fixed for me now.
