### ISSUE TITLE
Package Commento and create NixOS module

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#67524]
**Project description**
Commento is a fast, privacy-focused commenting platform

It should be a good alternative to Isso which still misses a module https://github.com/NixOS/nixpkgs/pull/34296#issuecomment-381929965

**Metadata**

* homepage URL: https://commento.io/
* source URL: https://gitlab.com/commento/commento
* license: mit
* platforms: unix, linux, darwin(?), ... it's a Go program, so it should work on every platform Go supports

**Comment by davidak** [comment]
Commento is still good, but i plan to use static comments for my websites.

https://github.com/davidak/davidak.de/issues/7#issuecomment-526677453

**Comment by AndersonTorres** [comment]
Is someone interested?

**Comment by davidak** [comment]
it also has a hard dependency on postgres. since i already have mysql on my server, that is too much. sqlite should be enough for a personal website with 1k visitors a month

https://gitlab.com/commento/commento/-/issues/226

so i'm not interested anymore and close. if you are, feel free to reopen or comment
