### ISSUE TITLE
gnome-panel should recognize installed applets

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#67545]
Panel applets are being picked up from `GNOME_PANEL_APPLETS_DIR` environment variable in [one place](https://gitlab.gnome.org/GNOME/gnome-panel/blob/b25f16c6077f383a2876512d280f20be10d5ac9a/gnome-panel/libpanel-applet-private/panel-applets-manager-dbus.c#L192-195) and a completely hardcoded path in [another](https://gitlab.gnome.org/GNOME/gnome-panel/blob/b25f16c6077f383a2876512d280f20be10d5ac9a/gnome-panel/libpanel-applet-private/gp-applet-manager.c#L114).

First, we will need to patch the latter manager to use an environment variable as well.
Second, we will need to do something similar to what [MATE is doing](https://github.com/NixOS/nixpkgs/blob/0b96dc87406327b715dfc64bfb89f137a4425bbd/nixos/modules/services/x11/desktop-managers/mate.nix#L83). Or better, create [`gnome-panel-with-plugins`](https://github.com/NixOS/nixpkgs/issues/59344) derivation.

_Originally posted by @jtojnar in https://github.com/NixOS/nixpkgs/issues/47451#issuecomment-452955745_

**Comment by chpatrick** [comment]
@jtojnar I'd like to tackle this, do you have any pointers? We need to get it to pick up `gnome-applets` at least right?
