### ISSUE TITLE
nixos/tests/systemd.nix is broken

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#67555]
**Describe the bug**
The nixos systemd test currently is broken.

**To Reproduce**
1. `nix-build nixos/tests/systemd.nix`

**Additional context**
```
error: command `dumpe2fs /dev/vdb | grep -q "^Last mount time: *n/a"' unexpectedly succeeded at /nix/store/39fb7m572abixj1qi7ddzx5lp3k64lw2-nixos-test-driver/lib/perl5/site_perl/Mach
ine.pm line 376, <__ANONIO__> line 194.                                                                                                                                               
(12.12 seconds)  
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: systemd nixosTests.systemd
# a list of nixos modules affected by the problem
module: systemd
```

cc @aszlig (88530e02b6fa9b5429dc09972b599e7b0a3af569), @Mic92, @andir, @arianvp

**Comment by aszlig** [comment]
@flokli: Is this regarding #66984 and/or did you bisect already? Nevertheless, I'll look into this later...

**Comment by flokli** [comment]
#66984 is unrelated, but by adding a new subtest for the things introduced in this PR we noticed the other subtest was broken in master. I didn't bisect yet.

**Comment by flokli** [comment]
@aszlig did you get a chance to bisect already? Otherwise, I might give it a try…

**Comment by aszlig** [comment]
@flokli: Hm, I guess you can't bisect, because this looks more like a race condition and a flaky test, currently working on it, sorry for the delay.

**Comment by aszlig** [comment]
Well, or flaky behaviour of the implementation:

```
Remounting '/test-x-initrd-mount' read-only in with options 'errors=continue,user_xattr,acl'.
Unmounting '/test-x-initrd-mount'.
```
