### ISSUE TITLE
Python: how to get a Python packages set that uses an overriden interpreter?

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#6756]
Context: I'd like to define a python environment with some predefined python packages from nixpkgs, but with a custom configured python (e.g. without tk to make the resulted closure more lightweight).

```
    with import <nixpkgs> {};

    python34.buildEnv.override {                                                    
        extraLibs = [ pkgs.python34Packages.pyramid ];
        ignoreCollisions = true;
    }
```

Question: How to override python34 so that it gets applied also to pkgs.python34Packages and how to disable tk in that override?

**Comment by domenkozar** [comment]
Python 3.x is not modular yet so we'll have to get that done first.

**Comment by FRidh** [comment]
`tkinter` is not build anymore by default. If you need `tkinter` you can use the package `pythonXX.pkgs.tkinter` like any other Python library.
If you want to have a full Python build that includes `tkinter` you can use `pythonXXFull`.

The Python package set is now available as an attribute of the interpreter (`pythonXX.pkgs`). Therefore, if you correctly override the interpreter, the packages will use that version of the interpreter. We should stop using the alias `pythonXXPackages`.

The following `shell.nix` modifies the default Python 2.7 `numpy` used throughout Nixpkgs:
```
let
  pkgs = import <nixpkgs> {
    config = {
      packageOverrides = pkgs: {
        python27 = let
          packageOverrides = self: super: {
            numpy = super.numpy_1_10;
          };
        in pkgs.python27.override {
          inherit packageOverrides;
        };
      };
    };
  };
in pkgs.inkscape
```
I will update the examples in the docs.

**Comment by mmahut** [comment]
I assume this is no longer valid.
