### ISSUE TITLE
PowerDNS builds broken

### ISSUE THREAD

**Issue by Shados** [NixOS/nixpkgs#67601]
I've found powerdns builds are currently broken in unstable, due to a test failure. Bisecting shows c18167cd9eb7cda09070a5d0fd8a6d42a2c46c48 to be the culprit.

Changing it to use `openssl_1_0_2` again would be the obvious fix, but powerdns has apparently had OpenSSL 1.1.0 compatibility since 2016, so it appears something else is going on here. Any ideas @mic92 @disassembler?

**Comment by Shados** [comment]
Or, actually, it's not built against openssl to begin with, but libressl... why is changing the default openssl causing it to fail tests, then...?

**Comment by rnhmjoj** [comment]
I guess libressl is based on an older openssl version, which doesn't have whatever breaking change is causing that build to fail agains openssl 1.1

**Comment by Mic92** [comment]
I think @andir was changing it from `openssl` to `libressl` because some crypto algorithm where not implemented in `openssl`.

**Comment by andir** [comment]
I have no recollection of doing so… I quick search through the commit log brought up:
15c629334d8fc83bed9e0b683556fbfd4defb622

Turns out @flokli is responsible…

**Comment by vcunat** [comment]
When I build with plain `openssl`:
```
configure: Features enabled
configure: ----------------
configure: Built-in modules: bind gmysql geoip godbc gpgsql gsqlite3 ldap lua mydns opendbx pipe random remote
configure: Dynamic modules: pipe
configure: 
configure: OpenSSL ecdsa: yes
configure: ed25519: yes
configure: ed448: no
configure: gost: yes
configure: SQLite3: yes
configure: Lua: lua5.2
configure: systemd: no
```
i.e. all important algos are shown there (ed448 is quite rare in practice).  13=ECDSAP256SHA256 mentioned in that PR is especially important &ndash; I think it's the most popular choice for new deployments now.

BTW, interested people might consider the `systemd: no` part.

**Comment by Mic92** [comment]
@vcunat sounds reasonable to me.
