### ISSUE TITLE
Openssl should not have runtime dependency on perl

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#6763]
According to this commit, openssl should not have runtime dependency on perl

https://github.com/NixOS/nixpkgs/commit/3f05ed581fb203987fb31733422e0490cedef5ec#diff-d6435511b194efc1d3b6e3276b7f4bdfR39

Yet, when I build
```
with import <nixpkgs> {};

buildEnv {
  name = "openssl";
  paths = [ openssl ];
}
```

It results the following graph with ``nix-store -q result --graph | dot -Tpng``

![openssl nix](https://cloud.githubusercontent.com/assets/160447/6603548/83bd4054-c82b-11e4-9b74-15a75d9bab66.png)

That causes the closure for openssl to be pretty much bigger than necessary.

**Comment by datakurre** [comment]
In case that I've understood something wrong and openssl must depend on perl, I'd be interested in learning, how to override it to not depend.

**Comment by copumpkin** [comment]
Perhaps related to https://github.com/NixOS/nixpkgs/issues/5895?

**Comment by vcunat** [comment]
It installs perl scripts:
```
$ nix-build -Q -A openssl
/nix/store/g2x8nb50bj0ysf7k3kxzm9axgx4hyk4j-openssl-1.0.1l
$ nix-store -q --references ./result
/nix/store/7yvf54nxwmaslcgyqfghqsqr1dwmr8ld-glibc-2.20
/nix/store/c8phpzx00hrfpbjwih1czsag0zgxrs51-bash-4.3-p33
/nix/store/py2az85s8vfbi26pc9mxcp2q2686gkiv-perl-5.20.1
/nix/store/g2x8nb50bj0ysf7k3kxzm9axgx4hyk4j-openssl-1.0.1l
$ grep py2az85s8vfbi26pc9mxcp2q2686gkiv -Rl ./result
./result/bin/c_rehash
./result/etc/ssl/misc/CA.pl
./result/etc/ssl/misc/tsget
```

After splitting into multiple outputs, probably only libs should be in the default one, so that would get rid of the perl runtime dependency.

**Comment by lethalman** [comment]
Remember openssl has a cool openssl executable :)

On Thu, Mar 12, 2015 at 10:03 PM, Vladimír Čunát <notifications@github.com>
wrote:

> It installs perl scripts:
>
> $ nix-build -Q -A openssl
> /nix/store/g2x8nb50bj0ysf7k3kxzm9axgx4hyk4j-openssl-1.0.1l
> $ nix-store -q --references ./result
> /nix/store/7yvf54nxwmaslcgyqfghqsqr1dwmr8ld-glibc-2.20
> /nix/store/c8phpzx00hrfpbjwih1czsag0zgxrs51-bash-4.3-p33
> /nix/store/py2az85s8vfbi26pc9mxcp2q2686gkiv-perl-5.20.1
> /nix/store/g2x8nb50bj0ysf7k3kxzm9axgx4hyk4j-openssl-1.0.1l
> $ grep py2az85s8vfbi26pc9mxcp2q2686gkiv -Rl ./result
> ./result/bin/c_rehash
> ./result/etc/ssl/misc/CA.pl
> ./result/etc/ssl/misc/tsget
>
> After splitting into multiple outputs, probably only libs should be in the
> default one, so that would get rid of the perl runtime dependency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/6763#issuecomment-78616167>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by datakurre** [comment]
@vcunat In some conditions the current packaging has post_install to remove those scripts, but I'm not familiar enough with nixpkgs conventions to understand, what those conditions are (and why remote them only sometimes).

**Comment by datakurre** [comment]
@copumpkin Agreed. I feel that gcc is always a shady runtime dependency.

**Comment by edolstra** [comment]
Fixed in a5fb18473e4178221e6a7a2264308678bd8234e3 and 283164779b9671517cfa9155abf57492129c95ad.

**Comment by domenkozar** [comment]
Yup, looks good now 

```
$ nix-store -qR /nix/store/3pp90k06zpfv52yn1k2w1yffg93rn8m1-openssl-1.0.1p
/nix/store/3f16d9vkd4bg9d8jfd7n73znm6v6j1d1-linux-headers-3.12.32
/nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21
/nix/store/3pp90k06zpfv52yn1k2w1yffg93rn8m1-openssl-1.0.1p
```

**Comment by datakurre** [comment]
Very nice :)

**Comment by vcunat** [comment]
@domenkozar: amazing how many open issues have been solved long ago :+1:
