### ISSUE TITLE
Package request: imgbrd-grabber

### ISSUE THREAD

**Issue by klorophatu** [NixOS/nixpkgs#67632]
**Project description**
Imageboard/booru downloader which can download thousands of images from multiple boorus very easily.

**Metadata**

* homepage URL: https://bionus.github.io/imgbrd-grabber/
* source URL: https://github.com/Bionus/imgbrd-grabber
* license: Apache-2.0
* platforms: Windows, Mac, and Linux

**Comment by toyo-chi** [comment]
Still not packaged for NixOS. So still important (at least to me).

I'm trying to package it myself, but it doesn't work due to dependencies on packages from NPM.

**Comment by evanjs** [comment]
Going to take a look at this after I open a PR for [hydrus](https://github.com/hydrusnetwork/hydrus/).
