### ISSUE TITLE
TexLive's updmap fails with "can't locate TeXLive/TMUtils.pm" in @INC

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#6764]
Steps to reproduce.

* Install `texLiveFull`
* run `updmap`

Exact error message:
```
$ updmap
Can't locate TeXLive/TLUtils.pm in @INC (you may need to install the TeXLive::TLUtils module) (@INC contains:
/nix/store/qxxh0dlc6rzrvi380fhq73rpjsd45v0b-TeXLive-linkdir/tlpkg
/home/sven/.nix-profile/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi
/home/sven/.nix-profile/lib/perl5/site_perl/5.20.1
/home/sven/.nix-profile/lib/perl5/site_perl
/nix/var/nix/profiles/default/lib/perl5/site_perl
/run/current-system/sw/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi
/run/current-system/sw/lib/perl5/site_perl/5.20.1
/run/current-system/sw/lib/perl5/site_perl
/nix/store/g9ybksy400pfn7fncw8dqfnz6m7fdyrk-perl-5.20.1/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi
/nix/store/g9ybksy400pfn7fncw8dqfnz6m7fdyrk-perl-5.20.1/lib/perl5/site_perl/5.20.1
/nix/store/g9ybksy400pfn7fncw8dqfnz6m7fdyrk-perl-5.20.1/lib/perl5/5.20.1/x86_64-linux-thread-multi
/nix/store/g9ybksy400pfn7fncw8dqfnz6m7fdyrk-perl-5.20.1/lib/perl5/5.20.1 .) at
/nix/store/c6hly1c9dqps8h31a6qd26djv2lxfh7f-texlive-core-2014/bin/updmap line 47.
BEGIN failed--compilation aborted at /nix/store/c6hly1c9dqps8h31a6qd26djv2lxfh7f-texlive-core-2014/bin/updmap line 47.
```

Probably `updmap` just needs to be wrapped with the right perl include paths.

Best,
Sven

**Comment by svenkeidel** [comment]
The path `/nix/store/qxxh0dlc6rzrvi380fhq73rpjsd45v0b-TeXLive-linkdir/tlpkg` doesn't exist, but I found `TeXLive/TLUtils.pm` in `texlive-core-2014/tlpkg` directory.

**Comment by 7c6f434c** [comment]
>The path `/nix/store/qxxh0dlc6rzrvi380fhq73rpjsd45v0b-TeXLive-linkdir/tlpkg` doesn't exist, but I found `TeXLive/TLUtils.pm` in `texlive-core-2014/tlpkg` directory.
Well, TeXLive aggregation could include tlpkg then. Do you expect this to help?

**Comment by svenkeidel** [comment]
These are the first few lines of `updmap`.

```perl
my $TEXMFROOT;

BEGIN {
  $^W=1;
  $TEXMFROOT = `kpsewhich -var-value=TEXMFROOT`;
  if ($?) {
    print_error("Cannot find TEXMFROOT, aborting!\n");
    exit 1;
  }
  chomp($TEXMFROOT);
  unshift (@INC, "$TEXMFROOT/tlpkg");
}
```

Dynamic dependency resolution does not conform to the nix philosophy anyway. My proposal is to replace `kpsewhich -var-value=TEXMFROOT` with the appropriate `nix/store/...` value. And yes, I think the TeXLive aggregation directory should contain tlpkg.

**Comment by svenkeidel** [comment]
I tried to use `substituteAllInPlace $out/libexec/*/updmap ...` in `aggregate.nix`, but I got a permission error.

**Comment by svenkeidel** [comment]
I figured out why I can't edit updmap in the aggregation directory. It is a symlink:
`TexLive-linkdir/updmap -> /nix/store/1kg8p9jbznpwx7vmv1gr710pp3m4gx9g-texlive-core-2014/share/texmf-dist/scripts/texlive/updmap.pl`. What do you think about copying with the symlink follow flag `-H` and then fixup the updmap file in the aggregation directory.

**Comment by svenkeidel** [comment]
@lovek323, @7c6f434c, @jwiegley, @pSub, I could use some help.

**Comment by vcunat** [comment]
I believe this works well now with the new [texlive](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L1). Reopen if you find a similar problem in there.
