### ISSUE TITLE
Request: Bump to rustc stable 1.37.0 (eae3437df 2019-08-13)

### ISSUE THREAD

**Issue by uHOOCCOOHu** [NixOS/nixpkgs#67649]
## Issue description

Simply bumping versions in `pkgs/development/compilers/rust/{bootstrap.nix,rustc.nix}` and specifying `CARGO_HOME=$TMPDIR` (#61194) will cause build failure related to LLVM.

**Comment by marsam** [comment]
Rust 1.37.0 is already in staging https://github.com/NixOS/nixpkgs/pull/66686, it will eventually land into master
