### ISSUE TITLE
systemd-timedated can't start because of missing /etc/localtime

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#67673]
**Describe the bug**
Setting `services.localtime.enable = true;` does not do [what it says](https://nixos.org/nixos/options.html#services.localtime.enable) out of the box. After starting the log says

> Failed to get target of /etc/localtime: No such file or directory

(I get the same error message after a reboot.)

**To Reproduce**
1. Set `services.localtime.enable = true;`
2. Run `sudo nixos-rebuild switch`

**Expected behavior**

systemd-timedated should start successfully.

**Metadata**
```
$ nix run nixpkgs.nix-info --command nix-info --markdown | sed "s/$USER/username/"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.61, NixOS, 19.03.173198.aeeb30a3b29 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173198.aeeb30a3b29"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by domenkozar** [comment]
Try setting `time.timeZone = "Europe/Paris";` as a dummy value.

**Comment by l0b0** [comment]
@domenkozar Now the service starts, but there's no useful log message and the time zone stays the same. I'll try rebooting to see if that solves it.

**Comment by l0b0** [comment]
Reopening since the `time.timeZone` workaround should not be necessary. Sorry for the noise.

**Comment by bbarker** [comment]
still important to me - ran into this issue I think as singularity expects /etc/localtime: https://github.com/hpcng/singularity/issues/5465

**Comment by l0b0** [comment]
Still broken in 22.11.

**Comment by TheoOliveira** [comment]
Still relevant. In fact I am getting mismatched warning in apps on my browser seems due to that, but i wasn't able to track that back to it.

**Comment by l0b0** [comment]
In NixOS 23.05 `services.localtime.enable` seems to be gone, and setting [`services.localtimed.enable = true;`](https://search.nixos.org/options?channel=23.05&show=services.localtimed.enable&from=0&size=50&sort=relevance&type=packages&query=services.localtimed.enable) seems to work, so we can probably just close this.

**Comment by behrica** [comment]
Issue is still present in  23.11.

I needed to do various settings, to get it working:
```
 
services.localtimed.enable = true;
  services.geoclue2.enable = true;
  services.avahi = {
    enable = true;
     };
time.timeZone = "Europe/Amsterdam";     
```

not sure, if all are needed, at least time.timeZone" was required to get a `/etc/localtime`.
The other I put in to get rid of errors, in starting of services
