### ISSUE TITLE
add share path to XDG_DATA_DIRS for citrix-receiver

### ISSUE THREAD

**Issue by BrunoChevalier** [NixOS/nixpkgs#67689]
**Describe the bug**
The installation path's share folder (f.e. /nix/store/lm0plpk26dxj3bqgis2r16gx5xqyy7s9-citrix-receiver-13.10.0/share/) should be added to XDG_DATA_DIRS.

**To Reproduce**
1. try to open an ica file with xdg-open
2. fail to find wfica.desktop
3. use the wrong program to open the ica file

**Expected behavior**
wfica.desktop should be able to be found by xdg-open

**Additional context**
google chrome uses xdg-open to open ica files.
I would like to be able to automatically start citrix receiver when clicking an ica link.

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/remote/citrix-receiver
```

**Comment by aanderse** [comment]
cc @Ma27

**Comment by Ma27** [comment]
May I ask, how you install `citrix-receiver`? I currently install it into `~/.nix-profile` and `~/.nix-profile/share` is part of `XDG_DATA_DIRS`. This is also the reason why I recommended to install it globally or via `nix-env -iA` (https://nixos.org/nixpkgs/manual/#sec-citrix-base)

**Comment by BrunoChevalier** [comment]
I installed it from `/etc/nixos/configuration.nix`
Then I debugged the `xdg-open` call. I followed the calls from both google-chrome and chromium.
I found a bug in [xdg-mime](https://gitlab.freedesktop.org/xdg/xdg-utils/blob/master/scripts/xdg-mime.in#L76) too while stepping through it. 
If none of `gio`, `gvfs-info` or `gnomevfs-info` are present, `$?` will be 0 because of the last if-check.
Anyway, that's a different issue.

xdg-open [iterates](https://gitlab.freedesktop.org/xdg/xdg-utils/blob/master/scripts/xdg-open.in#L349) over all share folders from `$XDG_DATA_DIRS` looking for the correct `.desktop` file when it needs to execute [open_generic_xdg_mime](https://gitlab.freedesktop.org/xdg/xdg-utils/blob/master/scripts/xdg-open.in#L337) from [open_generic](https://gitlab.freedesktop.org/xdg/xdg-utils/blob/master/scripts/xdg-open.in#L403) when `gio` and `gvfs-info` weren't found in [open_gnome3](https://gitlab.freedesktop.org/xdg/xdg-utils/blob/master/scripts/xdg-open.in#L161)

It should somehow be possible to add the install path's `share` folder to $XDG_DATA_DIRS, no?
It seems like other packages are doing this.

**Comment by Ma27** [comment]
Well, but if `citrix_receiver` is part of `environment.systemPackages` (and therefore the `/share` path from `citrix_receiver` is linked to `/run/current-system/sw/share`) it's part of `$XDG_DATA_DIRS`, right?

Or am I missing something? :)

**Comment by Ma27** [comment]
@BrunoChevalier can you give me some brief feedback if you still have this issue (on a recent NixOS version)?

I couldn't reproduce it back then, I'm happy to retry, but if it's not reproducible for me, I'd consider closing this.

**Comment by BrunoChevalier** [comment]
@Ma27 I stopped using NixOS so I would need to put in more effort than I care to spend to verify if the issue still exists.
The bug was there, I spent a couple of hours debugging it, and I ran into more bugs in xdg-mime.

Anyway, if nobody else is experiencing the bug, it must have been specific to my configuration.
I'm going to close this issue.
