### ISSUE TITLE
Ceph error

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#6773]
Hello!
Using `unstable-small` channel.
Have
```nix
  fileSystems."/ceph" = { 
      device = "192.168.0.81:/";
      fsType = "ceph";
      options = "name=admin,secretfile=/root/admin.key";
    };
  environment.systemPackages = with pkgs; [ ceph ];
``` 
in my `configuration.nix`
But it doesn't mount. Getting 
```systemd
● ceph.mount
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Mar 12 08:19:07 kraken systemd[1]: Mounting /ceph...
Mar 12 08:19:07 kraken mount[52235]: sh: /sbin/modprobe: No such file or directory
Mar 12 08:19:59 kraken systemd[1]: Unmounting /ceph...
Mar 12 08:19:59 kraken systemd[1]: ceph.mount mount process exited, code=exited status=32
Mar 12 08:19:59 kraken systemd[1]: Unmounted /ceph.
Mar 12 08:19:59 kraken systemd[1]: Unit ceph.mount entered failed state.
Mar 12 08:19:59 kraken umount[52451]: umount: /ceph: not mounted
Mar 12 08:20:07 kraken mount[52235]: failed to load ceph kernel module (127)
Mar 12 08:20:07 kraken mount[52235]: mount error 5 = Input/output error
Mar 12 08:21:19 kraken systemd[1]: Unmounted /ceph.
```
Using `14.12` channel and everything works fine.
cc @wkennington

**Comment by wkennington** [comment]
We could patch the ceph mounter will a path to the modprobe utility, or you
could use boot.kernelModules = [ "ceph" ]

**Comment by jagajaga** [comment]
If I use `boot.kernelModules = [ "ceph" ]` I dont have to have ceph in systemPackages?

**Comment by wkennington** [comment]
No, you need that too to provide the mount.ceph binary.

**Comment by wkennington** [comment]
We could write a nixos module which checks for any ceph fs mountpoints and
adds both the module and package.

**Comment by jagajaga** [comment]
Added `boot.kernelModules = [ "ceph" ]` but still nothing :(
Don't I have to add something to `boot.initrd.avaliableKernelModules` or `boot.extraModulePackages`?

**Comment by jagajaga** [comment]
`lsmod | grep ceph` gives me
```
ceph                  148666  0 
libceph               126803  1 ceph
libcrc32c               1018  1 libceph
fscache                35445  1 ceph
```

**Comment by wkennington** [comment]
Well, you probably dont want ceph to be mounted at boot. You probably want
neededForBoot = false or something. I do systemd mounts personally

**Comment by jagajaga** [comment]
So what do I have to do?

**Comment by wkennington** [comment]
This is what I do

https://github.com/wkennington/nixos/blob/master/common/ceph.nix

**Comment by jagajaga** [comment]
You don't have anything related to kernel modules..
