### ISSUE TITLE
Specifying VIM plugins using strings is deprecated, found "vim-airline", "vim-airline-themes" as strings.

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#67750]
**Describe the bug**
In my package list, I have 
      vimPlugins.vim-airline
      vimPlugins.vim-airline-themes

Both works well no issues so far
Recently starting from a few days back I start getting the warning on
```sh
nixos-rebuild switch --upgrade

unpacking channels...
building Nix...
building the system configuration...
trace: warning: mudrii profile: Specifying VIM plugins using strings is deprecated, found "vim-airline", "vim-airline-themes" as strings.

updating GRUB 2 menu...
activating the configuration...
setting up /etc...
reloading user units for mudrii...
setting up tmpfiles
```

**To Reproduce**
1. Add packages vimPlugins.vim-airline and vimPlugins.vim-airline-themes
2. Run nixos-rebuild switch --upgrade

Note: Maybe other vimPlugins are affected didn't try.

**Expected behavior**
No worrying or solution to be provided

**Metadata**

`nix run nixpkgs.nix-info -c nix-info -m`

```sh
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.03.173408.bd6ba87381e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173408.bd6ba87381e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

What is the solution for VIM plugins using strings is deprecated? Can't find any documentation or referance.

**Comment by eadwu** [comment]
Wrong repository, see https://github.com/rycee/home-manager/commit/f1146a1fef60b5455cff473a5e92acab378da236.

**Comment by mudrii** [comment]
@eadwu Thank you for reply and link.
Please would you able to elaborate more on the "Wrong repository,"?

Thx

**Comment by mudrii** [comment]
Solved in https://github.com/rycee/home-manager/pull/792
