### ISSUE TITLE
Better error reporting for androidenv when changing abiVersion

### ISSUE THREAD

**Issue by teh** [NixOS/nixpkgs#6783]
I'm recording this as an issue in case anyone else hits this. Using 

```nix
androidenv.emulateApp {
  name = "TomApp";
  app = theapp;
  platformVersion = "19";
  useGoogleAPIs = false;
  package = "com.example.tomapp";
  activity = ".MainActivity";

  enableGPU = true;
  abiVersion = "x86";

  avdHomeDir = "/tmp/.app";
}
```

works fine. If you now change the `abiVersion` though you will get 

> emulator: ERROR: This AVD's configuration is missing a kernel file!!

The reason is that the emulator wrote `/tmp/.app/.android/avd/device.avd/config.ini` with the x86 ABI version and runs the emulator as x86 but the SDK environment built contains the system image for a different ABI. The fix is to move to a new `avdHomeDir`.

I'm not sure how to detect this but a better error message or a Google result would have saved me two hours or so :)

Maybe for @svanderburg?

**Comment by garbas** [comment]
@teh would a solution be to clean ``avdHomeDir`` everytime you run nix-build? or maybe create a unique tmp folder for it each time.

**Comment by teh** [comment]
I think there is an inherent tension here between wanting to cache for speed reasons and purity. The nix way would be to make `avdHomeDir` derivation somehow so we only generate it once, but IIRC the issue was that the emulator wants to write to it.

I'm closing this because it's clearly a weird corner case and not really worth fixing in code. Google picked this bug up if someone searches for the issue they'll find it along with the solution, and that's a reasonable fix IMO.
