### ISSUE TITLE
Problem attempting to mkMultiInstance

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#6784]
Proposal of a helper function to make services run multiple instances with little effort. The interface of the default service won't change, and an "instances" submodule will be added for further instances.

However I'm getting a problem, explained below :(

```
diff --git a/lib/types.nix b/lib/types.nix
index 1e7abf3..ba0f9a5 100644
--- a/lib/types.nix
+++ b/lib/types.nix
@@ -227,4 +227,19 @@ rec {

   };

+  mkMultiInstance = path: args: f:
+    let
+      def = f (args // { name = "default"; config = getAttrFromPath path args.config; });
+    in {
+      options = setAttrByPath path (def.options // {
+        instances = mkOption {
+          type = types.attrsOf (types.submodule f);
+          default = {};
+          description = "Additional instances of this service";
+        };
+      });
+
+      config = def.config;
+    };
+
 }
diff --git a/nixos/modules/services/web-servers/nginx/default.nix b/nixos/modules/services/web-servers/nginx/default.nix
index 0af1b58..38f87da 100644
--- a/nixos/modules/services/web-servers/nginx/default.nix
+++ b/nixos/modules/services/web-servers/nginx/default.nix
@@ -1,9 +1,12 @@
-{ config, lib, pkgs, ... }:
+{ config, lib, pkgs, ... }@args:

 with lib;

+let topconfig = config;
+in mkMultiInstance [ "services" "nginx" ] args ({ config, name, ... }:
+
 let
-  cfg = config.services.nginx;
+  cfg = config;
   nginx = cfg.package;
   configFile = pkgs.writeText "nginx.conf" ''
     user ${cfg.user} ${cfg.group};
@@ -20,7 +23,6 @@ in

 {
   options = {
-    services.nginx = {
       enable = mkOption {
         default = false;
         type = types.bool;
@@ -82,15 +84,13 @@ in
         description = "Group account under which nginx runs.";
       };

-    };
-
   };

   config = mkIf cfg.enable {
     # TODO: test user supplied config file pases syntax test

-    systemd.services.nginx = {
-      description = "Nginx Web Server";
+    systemd.services."nginx-${name}" = {
+      description = "Nginx Web Server - ${name}";
       after = [ "network.target" ];
       wantedBy = [ "multi-user.target" ];
       path = [ nginx ];
@@ -108,12 +108,12 @@ in
     users.extraUsers = optionalAttrs (cfg.user == "nginx") (singleton
       { name = "nginx";
         group = cfg.group;
-        uid = config.ids.uids.nginx;
+        uid = topconfig.ids.uids.nginx;
       });

     users.extraGroups = optionalAttrs (cfg.group == "nginx") (singleton
       { name = "nginx";
-        gid = config.ids.gids.nginx;
+        gid = topconfig.ids.gids.nginx;
       });
   };
-}
+})
```

I've tried this patch with the following config:

```
  services.nginx = {
    enable = true;

    instances.foo = {
      enable = true;
    };
  };
```

However it's like the submodules are called as "default" module, or anyway only the default nginx instance is running, and not the foo instance.

**Comment by lethalman** [comment]
Pushed a branch for preview here (1 commit on top of master): https://github.com/lethalman/nixpkgs/commits/multiservice

**Comment by nbp** [comment]
This patch expects that all options used by the nginx are declared in the submodule.  This is not the case, and if the content of the instances were evaluated you will have noticed that many options are not defined.

Also, this patch expects that all definitions made within the submodule are visible into the parent module, but this is unfortunately impossible without an infinite recursion in the evaluation.

Also, as the instances config is never used, nor implicitly used, the result is that only the top-level expression is used.

So, to make it clear, if the nginx submodule defines `systemd.services`, the top-level should forward this option definition of each instance to the top-level option `systemd.services`.

The good news is that I might have a solution for this problem, the sad news, is that we would have to enumerate options which are visible within the instances.

**Comment by zimbatm** [comment]
I doesn't look like we have a way to declare multiple instances of a service yet so this could still be useful.

Is the work going to be pursued or should I close the issue ?

**Comment by zimbatm** [comment]
Maybe this should be done the other way around. `nginx` would act as a template and if you want multiple instances of it you call `mkInstance name: template:`.

**Comment by grahamc** [comment]
Closing the issue after almost 2 years of no discussion. FWIW, I've implemented duplicate services by using nixos containers. This has worked fairly nicely for me.
