### ISSUE TITLE
mac os x gitkraken support

### ISSUE THREAD

**Issue by thedavidmeister** [NixOS/nixpkgs#67867]
**Project description**

`gitkraken` is already on linux

currently there is no mac support

**Metadata**

* homepage URL: https://www.gitkraken.com/
* source URL: https://www.gitkraken.com/download/mac
* license: proprietary
* platforms: windows/mac/linux

**Comment by thedavidmeister** [comment]
from support

```
This should be what you need:
https://release.gitkraken.com/darwin/GitKraken-v4.1.1.zip

Reminder that we do not support older versions of the tool.

Have a wonderful day!
```

**Comment by evanjs** [comment]
This is something I've been interested in doing for various apps such as GitKraken, Postman, etc, that are also available on Darwin upstream.

My MacBook is a little outdated but I'm tempted to see how much work adding [support](https://nixos.org/nixpkgs/manual/#sec-darwin) might be...

At any rate, it looks like it has version parity with Linux (6.2.1), so I figure we could keep the version in sync, at least.

**Comment by thedavidmeister** [comment]
yeah i had a bit of a look, i think it's just a matter of carefully reviewing all the dependencies and using the above link to get the zip :man_shrugging:

**Comment by arkivm** [comment]
with #143065, osx support is added @thedavidmeister

**Comment by bobby285271** [comment]
Closing as the package has darwin support.
