### ISSUE TITLE
meson: cross-compilation breaks when not using callPackage

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#67880]
**Describe the bug**

Cross-compilation will break for derivations that depend on Meson unless wrapped in `callPackage`. Derivations that use `callPackage` work fine.

**To Reproduce**

Create `default.nix`:

```
let
  pkgs = (import <nixpkgs> {}).pkgsCross.musl64;
in

with pkgs;

stdenv.mkDerivation {
  name = "example";
  nativeBuildInputs = [ meson ninja ];
}
```

Run `nix-build`. It will fail with:

```
error: attribute 'targetPlatform' missing, at /nix/store/jc62lsfijc5qab87yrbi6aag67jd0lr8-source/pkgs/development/tools/build-managers/meson/default.nix:82:17
```

Which points to: https://github.com/NixOS/nixpkgs/blob/8de795e22f026a75fceecd1792ced68cbf046e45/pkgs/development/tools/build-managers/meson/default.nix#L82

**Expected behavior**

If you modify `default.nix` to wrap derivation in `callPackage`, like this, you can successfully cross-compile a package that depends on Meson:

```
let
  pkgs = (import <nixpkgs> {}).pkgsCross.musl64;
in

with pkgs;

callPackage ({ stdenv, fetchFromGitHub, meson, ninja }: stdenv.mkDerivation {
  name = "example";
  # This can be any Meson project, providing one without deps as an example:
  src = fetchFromGitHub {
    owner = "transumption-unstable";
    repo = "subnetgen";
    rev = "f386dacfb54db2302c0b6905edfd486e94adf42c";
    sha256 = "0szsmzgsrkkm56d37qp9inj06ik71hkn64fnims2wjn9izk3fpq2";
  };
  nativeBuildInputs = [ meson ninja ];
}) {}
```

**Additional context**

Seems that `targetPackages.stdenv.targetPlatform` is missing for `pkgsCross.*` unless using `callPackage`. I wonder if it's always true that `stdenv.targetPlatform == targetPackages.stdenv.targetPlatform`.

**Metadata**

Reproducible in the latest `nixos-unstable`:

```nix
import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/tarball/8d1510abfb592339e13ce8f6db6f29c1f8b72924";
  sha256 = "0i4jscq2qy2vn9kr8ix9gr8ncf9dss24y09jrqhlpcpryi4i98dc";
})
```

Maintainer information:
```yaml
attribute: meson
module:
```

cc @jtojnar @Ericson2314

**Comment by symphorien** [comment]
This looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/49526

**Comment by yegortimoshenko** [comment]
Hm, interesting. This might be possible to fix in isolation without changing splicing, though.

**Comment by dkudriavtsev** [comment]
I am also experiencing this issue.

**Comment by Ericson2314** [comment]
This is expected. See splice.nix (no link cause on phone sorry). It is evil but I know no alternative other than a big refactor. Without splicing you need to explicitly use `pkgs*` to take packages from the right package set. There's nothing wrong with that, except that it's possible to forget.

**Comment by Ericson2314** [comment]
I think this is fixed; stuff still breaks without callPackage because evil splicing, but there's nothing Meson specific about it.
