### ISSUE TITLE
please create a "fetchgitee"

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#67883]
**Project description**
Gitee is a clone of GitHub with a very strong focus on China.

**Metadata**

* homepage URL: https://gitee.com/

**Comment by dasJ** [comment]
Try if you can use fetchFromGitHub. Gitee (of which I have never heard) looks pretty similar to gitea (which I use).
Gitea is compatible with fetchFromGitHub, so it might also work for you. The expression I use in my overlay is:
```nix
{
  fetchFromGitea = { ... }@args: super.fetchFromGitHub ({ githubBase = "git.example.com"; } // args);
}
```

**Comment by dasJ** [comment]
I just checked and it seems to be more complicated than that. fetchFromGitHub uses `${baseUrl}/archive/${rev}.tar.gz`. Gitee uses `${baseUrl}/archive/${rev}?format=.tar.gz`. Also, it seems to require authentication to download public repos

**Comment by armijnhemel** [comment]
That's odd. Regular Git cloning seems to work.

**Comment by edolstra** [comment]
Not sure it makes sense to add such a function if nothing in Nixpkgs needs it.

**Comment by armijnhemel** [comment]
It is fairly new, but seems to be getting a lot of traction in China because of trade wars. Just flagging.

**Comment by prusnak** [comment]
I agree this should be closed and reopened only if there is a package that requires this functionality.
