### ISSUE TITLE
python3Packages.flask-caching: build failure

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#67927]
**Describe the bug**
I just updated to the latest master commit and now flask-caching fails to build:
```
these derivations will be built:
  /nix/store/064ycl7jrpjdxix3slk7ahjqrhkki401-python3.7-Flask-Caching-1.7.2.drv
building '/nix/store/064ycl7jrpjdxix3slk7ahjqrhkki401-python3.7-Flask-Caching-1.7.2.drv'...
builder for '/nix/store/064ycl7jrpjdxix3slk7ahjqrhkki401-python3.7-Flask-Caching-1.7.2.drv' failed with exit code 1; last 10 log lines:
  flask_caching/backends/null.py             4      4     0%   1-12
  flask_caching/backends/rediscache.py     106    106     0%   1-237
  flask_caching/backends/simple.py          53     53     0%   1-86
  flask_caching/backends/uwsgicache.py      30     30     0%   1-75
  flask_caching/jinja2ext.py                35     35     0%   2-103
  --------------------------------------------------------------------
  TOTAL                                   1014   1014     0%
  
  ================= 4 skipped, 102 deselected, 61 error in 7.97s =================
  Coverage.py warning: No data was collected. (no-data-collected)
error: build of '/nix/store/064ycl7jrpjdxix3slk7ahjqrhkki401-python3.7-Flask-Caching-1.7.2.drv' failed
```

**To Reproduce**
1. Checkout master at 4e60699fa72
2. `nix-build --no-build-output -A python3Packages.flask-caching`

**Expected behavior**
The build should be working.

**Additional context**
Noticed this when trying to build the package `buku`.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.9, NixOS, 19.09.git.67f76933ed5 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-18.09.2574.a7e559a5504"`
 - nixpkgs: `/home/terje.larsen/src/github.com/terlar/nix-config/nixpkgs`

Maintainer information:
```yaml
module:
- buku
```

**Comment by teto** [comment]
fixed by upgrading flask https://github.com/NixOS/nixpkgs/pull/67925

**Comment by terlar** [comment]
Verified that it is fixed, thanks!
