### ISSUE TITLE
testdisk/photorec packaged twice

### ISSUE THREAD

**Issue by d-goldin** [NixOS/nixpkgs#67953]
Looks like we have testdisk/photorec packaged twice.

* https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/testdisk/default.nix
* https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/testdisk-photorec/default.nix

Unless I'm mistaken and they do somehow differ, we should probably ditch one of those. The first listed one is also misnamed to testdisk-7.1, while it downloads 7.0.

CC respective maintainers @eelco @fgaz

**Comment by fgaz** [comment]
My bad I think. My search for "photorec" returned nothing so I assumed the whole testdisk-photorec package was missing and added it.

What about pointing both attrs to the first one and updating its description to include the photorec part? We should also actually update it to 7.1 while we are at it (it's stable now)

**Comment by d-goldin** [comment]
@fgaz: my two cents: I'm not sure it's worth pointing the "less desirable" one (which-ever that is) and maybe instead throw a deprecation warning on that one pointing to the correct one, which could convince people to migrate away quicker, so the old attribute could be ditched sooner. 

I am not aware if there is any proper deprecation process, but for the packages in question, which are not likely to be super-core components, a more lightweight approach could be just fine. 

Are you planning to tackle this, or should I give it a shot?

**Comment by fgaz** [comment]
Please go ahead, just make sure that both names (testdisk and photorec) appear either in the name or the short description, so that searches for "photorec" can return it as a result.
