### ISSUE TITLE
DHCP gives ip to bridges

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#67966]
**Describe the bug**
Under NixOS the dhcp server is configured in a way that dhcp configures every interfaces available. Even bridge interfaces like macvtap. Which creates very very very confusing and had to debug ARP and network errors. Like described here: https://serverfault.com/questions/959667/kvm-bridge-networking-first-arp-packet-gets-answered-by-wrong-host

**To Reproduce**
Enable KVM create a virtual machine with bridged interface. You will see that the macvtap@interface will get an ip.

**Comment by arianvp** [comment]
One fix is mentioned in this comment: https://github.com/NixOS/nixpkgs/issues/18962#issuecomment-526193023

I would want to introduce an option `networking.allowedInterfaces` or similar that explicitly whitelists what interfaces are managed by the networking module; such that it doesn't randomly enable DHCP on new interfaces.     the fact that the `networking.useNetworkd` backend tries to emulate this misfeature from the `networking` module is causing issues in `resolved` so now we have another reason to introduce such an option.

**Comment by arianvp** [comment]
This is fixed in https://github.com/NixOS/nixpkgs/pull/69302
