### ISSUE TITLE
libcxxStdenv on staging uses libstdc++

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#6797]
`clang++ -E -x c++ - -v < /dev/null 2>&1 |grep libc++` inside a myEnvFun with libcxxStdenv in buildInputs returns nothing. Grepping for gcc instead shows libstdc++ include paths.

cc @shlevy

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by Ralith** [comment]
I believe this has been fixed. Will reopen if not.
