### ISSUE TITLE
Package request: mkldnn

### ISSUE THREAD

**Issue by stites** [NixOS/nixpkgs#67982]
**Package request: mkldnn**

Discovered by @wavewave and @tscholak while working on https://github.com/hasktorch/hasktorch/pull/162.

mkldnn is used by hasktorch, as well as pytorch, mxnet, tensorflow (I think), etc. These library files are not found in `mkl` derivation and are open-source.

When introduced it would be nice if this library could be added to the `nativeBuildInputs` of pytorch : )

**Metadata: mkldnn**

* homepage URL: https://intel.github.io/mkl-dnn/dev_guide_transition_to_dnnl.html
* source URL: https://github.com/intel/mkl-dnn
* license: apache-2.0
* platforms: unix, linux, darwin

**Comment by yorickvP** [comment]
```
{ stdenv, fetchFromGitHub, cmake, doxygen, graphviz, git, mkl }:
stdenv.mkDerivation rec {
  pname = "mkl-dnn";
  version = "0.21";
  src = fetchFromGitHub {
    owner = "intel";
    repo = pname;
    rev = "v${version}";
    sha256 = "1b7nb28spxvphw1gfq2bmjn1kgpi718piskzzc4ldwrczxq9ykvh";
  };
  postPatch = ''
    sed -i 's$ /bin/bash$ ${stdenv.shell}$g' tests/CMakeLists.txt
  '';
  cmakeFlags = "-DCMAKE_PROJECT_VERSION=v${version}";
  nativeBuildInputs = [ cmake doxygen graphviz ];
  buildInputs = [ mkl ];
}
```

**Comment by stites** [comment]
Thanks, @yorickvP -- this will likely be useful for backwards support of mkldnn! I believe #74893 should be the NixOS-endorsed derivation to close this issue, however.
