### ISSUE TITLE
Cannot update to vault-1.2.2 on OSX

### ISSUE THREAD

**Issue by lutnos** [NixOS/nixpkgs#67995]
**Describe the bug**
After a channel update I now cannot update packages because vault cannot be updated to 1.2.2, I see a build error:

> go: git.apache.org/thrift.git@v0.12.0: unknown revision v0.12.0
> go: error loading module requirements
> builder for '/nix/store/x82vqflw6c75kcw73blp5pgdsfvn6cbv-vault-1.2.2-go-modules.drv' failed with exit code 1
> cannot build derivation '/nix/store/gaaq83isgdmm334g820nb6x58wjgd7cf-vault-1.2.2.drv': 1 dependencies couldn't be built

**To Reproduce**
1. nix-channel --update
2. nix-env -u

**Expected behavior**
Update vault to 1.2./2 and emacs to 26.3

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

> Daves-MacBook-Pro:.nix dave$ nix run nixpkgs.nix-info -c nix-info -m
> [2 copied (0.0 MiB), 0.0 MiB DL]
>  - system: `"x86_64-darwin"`
>  - host os: `Darwin 18.7.0, macOS 10.14.6`
>  - multi-user?: `no`
>  - sandbox: `no`
>  - version: `nix-env (Nix) 2.2.2`
>  - channels(dave): `"nixpkgs-19.09pre191265.c4adeddb5f8"`
>  - nixpkgs: `/Users/dave/.nix-defexpr/channels/nixpkgs`
> 

Daves-MacBook-Pro:.nix dave$ 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by arianvp** [comment]
`git.apache.org` is down. Not much we can do here.

**Comment by lutnos** [comment]
I see, thanks

**Comment by marsam** [comment]
FWIW vault vendorizes its dependencies, hence it should use `buildGoPackage` instead of `buildGoModule` which is a fixed-output derivation

**Comment by lutnos** [comment]
I note from https://blogs.apache.org/infra/entry/subversion-to-git-service-git on the 10th September that:

> There will no longer be a git.apache.org  URL for git mirrors, to lessen the confusion with gitbox.apache.org.  Projects wishing to point to a git copy of their subversion repository should use their respective GitHub URLs. 

FWIW

**Comment by eraserhd** [comment]
They've fixed it upstream, but not released a new version: https://github.com/hashicorp/vault/commit/61ff0fd8699dfe9efb9b014df8e9aff86a0aa924#diff-37aff102a57d3d7b797f152915a6dc16

**Comment by lutnos** [comment]
That is, Nixpkgs has not yet been updated to the vault 1.2.3 release https://github.com/NixOS/nixpkgs/commits/69d58ee24506e2b3b5aff347ae3b0791110340ec/pkgs/tools/security/vault/default.nix . Thanks

**Comment by arianvp** [comment]
Thanks @lutnos . I am bumping the package to 1.2.3 for the 19.09 release

**Comment by lutnos** [comment]
Cheers @arianvp

**Comment by simonswine** [comment]
I have hit this issue as well, not knowing much about the nixos golang build processes, but I was able to pull the dependencies through a go proxy with go 1.12+:

```
export GO111MODULE=on
export GOPROXY=https://goproxy.io
```

**Comment by marsam** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/69229

**Comment by turion** [comment]
@simonswine How do I use the go proxy? I entered both commands and did (in my case) `home-manager switch`, but the error stays the same.

**Comment by simonswine** [comment]
@turion Not too sure what `home-manager switch` is doing, for go proxy you need quite recent Go versions.

Maybe some more context can be found here https://arslan.io/2019/08/02/why-you-should-use-a-go-module-proxy/
