### ISSUE TITLE
nvidia_x11: Vulkan functionality is broken in nixos-unstable channel

### ISSUE THREAD

**Issue by alapshin** [NixOS/nixpkgs#67997]
Recent update to `nixos-unstable` broke vulkan functionality. `vulkaninfo` fails with error message
```
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
/build/source/vulkaninfo/vulkaninfo.c:923: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

I'm using nvidia driver 435.21

**To Reproduce**
1. Install vulkan-tools
2. Run vulkaninfo

**Expected behavior**
`vulkaninfo` should not fail with error.

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.2.11, NixOS, 19.09pre191505.7d5375ebf4c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6895_84de821`
 - channels(root): `"nixos-19.09pre191505.7d5375ebf4c"`
 - channels(alapshin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alapshin** [comment]
Looks like problem affects native applications as well. 
vulkaninfo fails with
```
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
/build/source/vulkaninfo/vulkaninfo.c:923: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

I will update bug description to remove Steam mention because it looks like Steam is not a culprit.

**Comment by primeos** [comment]
Might be related to #67919, but it's strange that you're not getting the assertion error (I didn't have a closer look at the Git history).

**Comment by alapshin** [comment]
Maybe, I'm not sure.
I worked around assertion error using local overlay with
```
  vulkan-tools = super.vulkan-tools.overrideAttrs (oldAttrs: rec {
    version = "1.1.114.0";
  });
  vulkan-headers = super.vulkan-headers.overrideAttrs (oldAttrs: rec {
    version = "1.1.114.0";
  });
```

I'm thinking it may be caused by nvidia driver update at https://github.com/NixOS/nixpkgs/commit/4b67e77e1596c0e3bccedf408c6674054a6b302d

Will try to downgrade driver, rebuild system and verify this.

**Comment by primeos** [comment]
You're right, in that case it isn't related to the other issue.

> Will try to downgrade driver, rebuild system and verify this.

Thanks :)

**Comment by alapshin** [comment]
Downgrading nvidia driver to 430.40 fixed problem.

**Comment by primeos** [comment]
cc #67762, @baracoder, @eadwu: FYI ;)

Maybe someone has the time and experience to have a closer look at this issue? (I don't have an Nvidia GPU)
