### ISSUE TITLE
gpg compatibility issues with password-store

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#6808]
I have a big problem with `pass` ("password-store") and gpg, which seems to be related to gpg version incompatibilities. I reported to the password-store ML and we debugged the problem.

From what I can see, password-store calls GPG2.0.26 while my gpg version is 2.1.2.

[Here](http://lists.zx2c4.com/pipermail/password-store/2015-March/001410.html) is the ML archive thread, ~~whereas [this]() is the mail where we found out.~~ (Mail not in the archives yet)

---

How can I debug this even further/fix this? Shall I override the `pass` package to use my gnupg version? Shall I file an update for the `pass` package?

How can we force `pass` to use the installed gnupg version? Or: can we actually do this?

**Comment by peti** [comment]
The GPG version used by password-store is determined at build time. If you want to use a different version, then you must add an override to `~/.nixpkgs/config.nix`:

    {
      packageOverrides = super: let self = super.pkgs; in
      {
        pass = super.pass.override { gnupg = self.gnupg21; };
      };
    }

**Comment by matthiasbeyer** [comment]
Solved with the `packageOverrides` @peti suggested.

**Comment by matthiasbeyer** [comment]
Just for reference and completeness:

If one wants to have the override globally, add this as `pass` package to your `systemPackages`:

```nix
let
    pass = pkgs: pkgs.pass.override { gnupg = pkgs.gnupg21; }; # or your gnupg version
in
environment.systemPackages = [
    # ...
    (pass pkgs)
];
```
