### ISSUE TITLE
 nixpkgs/pkgs/os-specific/linux/pcmciautils/default.nix in 14.12 pointing to .tar.bz, not .tar.gz

### ISSUE THREAD

**Issue by phryneas** [NixOS/nixpkgs#6809]
Hi, the download link given in https://github.com/NixOS/nixpkgs/blob/release-14.12/pkgs/os-specific/linux/pcmciautils/default.nix is not correct any more - this is fixed in master but leaves this un-installable in 14.12. For reference see:
https://www.kernel.org/pub/linux/utils/kernel/pcmcia/

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/abed7e7171d066525bd74c794b46b4e01b04f2e8.
