### ISSUE TITLE
Steam: OpenGL seems to have been accidentally broken

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#6812]
It seems that commit e01cd8f214644f5e0fb877965c3344d6aceaec9b broke all games due to removing the related setting of LD_LIBRARY_PATH. I have tested that function is restored by adding this like (without the `:/lib:/lib32:/lib64`):

```
export LD_LIBRARY_PATH=/run/opengl-driver/lib:/run/opengl-driver-32/lib
```

**Comment by vcunat** [comment]
CC @abbradar: did you remove those lines because of some reason?

**Comment by abbradar** [comment]
Hm, it works for me -- the line was moved to https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-fhs-chrootenv/env.nix#L76 . I'll test it, maybe

**Comment by abbradar** [comment]
I've forgotten to import /etc/profile or something else (sorry, missend).

**Comment by abbradar** [comment]
`glxinfo` works within the environment, and `echo $LD_LIBRARY_PATH` yields correct values. Do you have latest master or have you cherry-picked things (maybe you've forgotten to pick previous commits)?

**Comment by ambrop72** [comment]
Ah yes, it works after also cherry picking the three recent chroot-env commits. Thanks!
<insert rant about incomplete commit messages>
