### ISSUE TITLE
epson epkowa drivers: previous tarballs unavailable

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#68133]
Epson has updated many scanner drivers recently. Packages other than the latest release have been removed from their website, which causes the build of `pkgs.epkowa` to fail.

CC package maintainer: @symphorien

**Comment by symphorien** [comment]
thanks for the head up; can you try your device with #68225 ?

**Comment by pacien** [comment]
Thank you for the quick update :+1: 
It works fine with my device. I've approved the pull request.
