### ISSUE TITLE
Samba server cannot find users when using the valid users field.

### ISSUE THREAD

**Issue by mtetreault** [NixOS/nixpkgs#6816]
ie.

The connection is rejected everytime I try to connect to the share with the valid user.
When I remove the valid users field, samba still asks for my username and password and it works. The user exist in the Linux environment, and have also been created with smbpasswd.
I pasted the samba log and the samba config.
## Log

[2015/03/14 03:51:43.073527,  5] passdb/pdb_tdb.c:562(tdbsam_getsampwnam)
  pdb_getsampwnam (TDB): error fetching database.
   Key: USER_my_samba_user
[2015/03/14 03:51:43.073555,  4] smbd/sec_ctx.c:422(pop_sec_ctx)
  pop_sec_ctx (0, 0) - sec_ctx_stack_ndx = 0
[2015/03/14 03:51:43.073572,  3] auth/check_samsec.c:399(check_sam_security)
  check_sam_security: Couldn't find user 'my_samba_user' in passdb.
## Config

 services.samba = {
    enable = true;

```
extraConfig = ''
  workgroup = WORKGROUP
  netbios name = desktop
  server string = %h
  comment = Samba

  log file = /var/log/samba/log.%m
  log level = 10
  max log size = 50000
  security = user
  client lanman auth = yes

  [samba_share]
  comment = samba private share
  valid users = my_samba_user
  create mask = 770
  path = /path/to/share
  guest ok = no
  read only = no
  public = no
  browsable = yes
'';
```

  };

**Comment by Profpatsch** [comment]
(triage) what’s the status?
