### ISSUE TITLE
No icons display in Inkscape, causes crash on opening dialogs

### ISSUE THREAD

**Issue by rileyinman** [NixOS/nixpkgs#68185]
**Describe the bug**
After installing inkscape either in the user or system profile, no icons are found. When opening dialogs such as "Fill and stroke" or "Layers" the program crashes. I've confirmed this on two of my machines.

**To Reproduce**
1. `nix-shell -p inkscape`
2. Run inkscape
3. Note that all icons display incorrectly
4. Navigate to Object -> Fill and Stroke
5. Observe crash

**Expected behavior**
Inkscape should have the full set of icons and dialogs should be accessible.

**Screenshots**
![2019-09-06-01:19:08](https://user-images.githubusercontent.com/37246692/64402905-7c1ade80-d044-11e9-92ea-cc76005bba79.png)

**Additional Context**
<details>
<summary>Console log</summary>

```
[~] inkscape
terminate called after throwing an instance of 'Gtk::IconThemeError'

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at www.inkscape.org
with a detailed description of the steps leading to the crash, so we can fix it.
zsh: abort      inkscape
```
</details>

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.03.173408.bd6ba87381e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173408.bd6ba87381e"`
 - channels(riley): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
I think you can easily fix this issue by installing an icon theme to your system.

**Comment by jtojnar** [comment]
I believe these icons are part of Inkscape. Possibly issue with gdk-pixbuf loaders – though, I cannot reproduce it within plain xterm session.

What desktop environment are you running? Does adding `wrapGAppsHook` to Inkscape’s `nativeBuildInputs` help?

**Comment by rileyinman** [comment]
@jtojnar Sorry, I should have mentioned - I already tried the following overlay for inkscape
```
self: super:
{
  inkscape = super.inkscape.overrideAttrs(old: rec {
    nativeBuildInputs = old.nativeBuildInputs ++ [ super.wrapGAppsHook ];
    buildInputs = old.buildInputs ++ [ super.gdk_pixbuf ];
  });
}
```
after reading the gdk-pixbuf issue and related ones. Unfortunately it didn't seem to change anything after rebuilding and compiling.

One of my computers is running sway (launched via startx) and the other i3 + sddm.

**Comment by symphorien** [comment]
Maybe `wrapGAppsHook` does not work because of `strictDeps`: https://github.com/NixOS/nixpkgs/blob/8d1510abfb592339e13ce8f6db6f29c1f8b72924/pkgs/applications/graphics/inkscape/default.nix#L25

**Comment by rileyinman** [comment]
@symphorien That worked! I rebuilt it with `strictDeps = false` and all the icons show up, and dialogs work. I tried looking up docs on `strictDeps` but I couldn't find much about it, what does it do exactly?

**Comment by worldofpeace** [comment]
:confused: I thought the issue with strictDeps only touched gobject-introspection
* https://github.com/NixOS/nixpkgs/issues/56943

**Comment by jtojnar** [comment]
IIRC, it might also affect hook’s `deps` not being picked up correctly. Does the following work with `strictDeps` enabled?

```nix
self: super:
{
  inkscape = super.inkscape.overrideAttrs(old: rec {
    nativeBuildInputs = old.nativeBuildInputs ++ [ super.wrapGAppsHook ];
    buildInputs = old.buildInputs ++ [ super.gdk_pixbuf super.librsvg ];
  });
}
```

**Comment by rileyinman** [comment]
@jtojnar Yes, that worked! Would the best workaround for now be to add those inputs to the derivation?
