### ISSUE TITLE
Wrong Nix expression URL for rxvt_unicode-with-plugins

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#68202]
**Describe the bug**

[rxvt_unicode-with-plugins](https://nixos.org/nixos/packages.html?attr=rxvt_unicode-with-plugins&channel=nixos-19.03&query=rxvt) links to [pkgs/build-support/trivial-builders.nix](https://github.com/NixOS/nixpkgs/blob/bd6ba87381ef6274a830253b60e481209d4d7c7d/pkgs/build-support/trivial-builders.nix#L7), which looks completely wrong. There's no reference to rxvt in that file.

Maintainer information:
```yaml
attribute:
  - rxvt_unicode-with-plugins
```

**Comment by worldofpeace** [comment]
Interesting, it doesn't seem to have any meta data and `symlinkJoin` (which it uses) is in that directory.

Though I believe this is a bug in nixos-homepage.

**Comment by worldofpeace** [comment]
There's a similar situation with mpv-with-scripts
* https://nixos.org/nixos/packages.html?channel=nixos-19.03&query=mpv-with-scripts

It seems that `meta.position` evaluates to `pkgs/build-support/trivial-builders.nix:7`
If I inherit the metadata from `mpv` the position is correct. So I'm think that for expressions that don't have any defined meta data this will happen.

**Comment by worldofpeace** [comment]
cc @samueldr

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/203778
