### ISSUE TITLE
cmake does not build libraries with fully-specified install name (Darwin)

### ISSUE THREAD

**Issue by giogadi** [NixOS/nixpkgs#6821]
This issue only affects Darwin.

Currently, nix's cmake derivation builds libraries without a fully specified install name. This makes it difficult to link to these libraries and can cause problems, such as issue #2800. This particular issue was fixed by patching the library's CMakeLists.txt file to fully specify the library's install name.

This will continue to be an issue for any nix package built with cmake on Darwin. How should this be addressed? One potential solution would be to generalize the solution to #2800 to all cmake derivations by adding this line to cmake/setup_hook.sh:

```
cmakeFlags="-DCMAKE_INSTALL_NAME_DIR=$prefix/lib $cmakeFlags"
```

This might work just fine, but could cause issues if library authors instead install the library to lib64 or some other non-standard directory.

Does anyone have any ideas? Pinging @jwiegley since he has dealt with this issue before.

**Comment by giogadi** [comment]
BTW, if anyone on Darwin wants to verify that this is indeed an issue, try checking the install name of a cmake-built package, such as `ilbc` for instance:

```
$ nix-build -A ilbc
$ otool -D result/lib/libilbc.dylib
```

The second command above will output `libilbc.dylib` as the install name, which is the problem I'm referring to. This install name means that executables can only load this library if they're in the same directory as the library.

**Comment by gridaphobe** [comment]
@copumpkin any thoughts? I don't know much about cmake our how we deal with it.

**Comment by copumpkin** [comment]
I don't either :( it's mostly voodoo to me

**Comment by giogadi** [comment]
In case it helps, I'll try to clarify the problem:

When Darwin builds a shared library `foo.dylib`, it also embeds a path called an "install name". Let's say you linked an executable `my_app` to this library `foo.dylib`. When you run `my_app`, Darwin uses the install name of `foo.dylib` to find this library at runtime. If the install name of `foo.dylib` is just `<absolute/path/to>/foo.dylib`, the executable will run with no problems (as long as no one moved `foo.dylib` from the path reflected by its install name). If the install name is something else, like a relative path, then Darwin looks through a particular set of directories (like /usr and /usr/local) for the shared library.

It's typically seen as more flexible to just give the install name a relative path (i.e., the install name for `foo.dylib` is simply `./dylib`) so that the library can be found either in system paths or in the same directory as the executable. Cmake does this by default. However, this does not work with Nix because the Nix package directories are not searched at runtime for shared libraries.

For example: say I build `foo.dylib` using cmake in Nix. Next, I successfully compile and link `my_app` to `foo.dylib`. However, when I try to run `my_app`, it'll error out because it can't find the `foo.dylib` at runtime. So, a binary linked to a library built with cmake in Nix will not be found at runtime.

So, another option is to just use full absolute paths as library install names. This makes sense in Nix because we do not expect libraries to move around from their installed locations. The proposed idea I gave above is a hack that forces cmake to do exactly this.

Admittedly, I'm not an expert in Darwin shared library linking, and I could be missing a much simpler solution to this. [Here's a link](http://www.cmake.org/Wiki/CMake_RPATH_handling) that explains how Cmake handles some of this stuff.

**Comment by henrytill** [comment]
I believe I encountered this problem when debugging #7047.

See here: https://gist.github.com/henrytill/728c40c48e750da28f73

The offending libs in on lines 42, 48, 54, and 56 all use `cmake`: 
* `x265` 
  * https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/x265/generic.nix
* `vid-stab`
  * https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/vid-stab/default.nix
* `open_jpeg`
  * https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/openjpeg/generic.nix
* `game-music-emu`
  * https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/game-music-emu/default.nix

We disabled them for now in the aforementioned PR (along with several other fixes to get it working on Darwin), but it would be nice to address this problem so that we could re-enable them, and deal with other `cmake`-related breakage on Darwin.

**Comment by jwiegley** [comment]
@giogadi Can you please verify if this helps:

http://www.cmake.org/Wiki/CMake_RPATH_handling#Always_full_RPATH

**Comment by giogadi** [comment]
@jwiegley I have also tried that solution, and I think I remember it also
working. However, to be honest, I don't know exactly what all those cmake
commands are doing, so for my PR (#6947) I went with the simpler (and
seemingly sufficient) solution of setting the CMAKE_INSTALL_NAME_DIR
variable. If you believe there's a good reason to go with the full RPATH
solution, let me know and I can kick off a rebuild to verify that it works.

**Comment by jwiegley** [comment]
It would be great if there was a nixpkgs unit test that could verify that things like this are being done correctly, ideally before a stdenv build begins.

**Comment by henrytill** [comment]
Relevant docs: 
* http://www.cmake.org/cmake/help/v2.8.12/cmake.html#variable:CMAKE_INSTALL_NAME_DIR

**Comment by henrytill** [comment]
Can confirm @giogadi's findings on Darwin:

Current state of things:
```
$ nix-build -A vid-stab
...
$ otool -D ./result/lib/libvidstab.dylib
./result/lib/libvidstab.dylib:
libvidstab.0.9.dylib
```
After applying fix from #6947, rebased against master:
```
$ nix-build -A vid-stab
...
$ otool -D ./result/lib/libvidstab.dylib
./result/lib/libvidstab.dylib:
/nix/store/f52sh3rw21p949yc66dppbkkkaqzbcgn-vid-stab-0.98b/lib/libvidstab.0.9.dylib
```
And, after re-enabling `vid-stab` in the `ffmpeg` expression, it now finds `libvidstab.dylib`:
```
$ nix-build -A ffmpeg
...
$ otool -L ./result/bin/ffmpeg
./result/bin/ffmpeg:
...
        /nix/store/f52sh3rw21p949yc66dppbkkkaqzbcgn-vid-stab-0.98b/lib/libvidstab.0.9.dylib (compatibility version 0.9.0, current version 0.0.0)
...
```

**Comment by cstrahan** [comment]
Another option is modifying the dylibs after the fact, which may or may not be easier than trying to coax build-tools (like CMake) into doing "the right thing". A couple useful tips:

* [`install_name_tool`](http://www.unix.com/man-page/osx/1/install_name_tool/) can be used to change the id/rpaths of a dylib
* Passing `-headerpad_max_install_names` to the linker will leave some extra padding so that `install_name_tool` has enough room to add/replace the paths

**Comment by henrytill** [comment]
@shlevy has also raised the point that #6947 doesn't address the case of multiple output derivations where libs aren't in the same output as `$prefix`.

**Comment by cstrahan** [comment]
@henrytill @shlevy Does CMake even support such a scenario (aside from manually moving the dylibs over)? If it doesn't, then #6947 might still be a good default, since you'd still have to manually `mv` the files over.

**Comment by shlevy** [comment]
Yeah it looks like cmake doesn't support multiple prefixes, so that's not a problem. I say we go for that PR for now.

**Comment by giogadi** [comment]
Is it appropriate to close this if a potential fix has been merged into staging?

**Comment by gridaphobe** [comment]
Yep, thanks!
