### ISSUE TITLE
Hydra broken and blocking channels -- aborted tested jobs on Packet hosts

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#68247]
The most common issue affecting the tested jobs appears to be this:

> Aborted: cannot connect to ‘root@67c9c299.packethost.net’: Warning: Permanently added the ED25519 host key for IP address '147.75.33.175' to the list of known hosts. error: could not set permissions on '/nix/var/nix/profiles/per-user' to 1777: No space left on device

**Comment by andir** [comment]
It has been going on for ~5 days now. @edolstra knows about it.

**Comment by vcunat** [comment]
Very stale issue.
