### ISSUE TITLE
appimage-run can't run pennywise

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#68267]
**Describe the bug**
Can't run [Pennywise's AppImage](https://github.com/kamranahmedse/pennywise)

**To Reproduce**
1. download Pennywise's Appimage https://github.com/kamranahmedse/pennywise/releases/download/v0.8.0/pennywise-0.8.0-x86_64.AppImage
2. try to run it
```
appimage-run ~/Download/pennywise-0.8.0-x86_64.AppImage
/nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/home/pinage404/.cache/appimage-run/781bcc576d55ae99bbe7f988eb259b7a21c584c925a5f7181578a81ccc0bb50d//squashfs-root/pennywise: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.67, NixOS, 19.03.173322.67135fbcc5d (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(pinage404): `"home-manager-19.03, nixos-19.03.173450.609fe21661d, nixos-unstable-19.09pre191617.4e60699fa72"`
 - channels(root): `"nixos-19.03.173453.0d79decdb3b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

don't know, but it should be here https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/appimage/default.nix

**Comment by lattfein** [comment]
This is due to missing `at-spi2-core` dependency. I also encountered some AppImage applications which require `at-spi2-core`.

Should we add `at-spi2-core` to `appimageTools.defaultFhsEnvArgs.multiPkgs`?

cc @tilpner

**Comment by tilpner** [comment]
The [exclude list](https://github.com/AppImage/pkg2appimage/blob/master/excludelist) doesn't mention any `libat*` libraries, but as there seem to be multiple AppImages requiring it, we already have `at-spi2-atk` in the list, and it doesn't increase closure size by much, so go ahead and add it. :)
