### ISSUE TITLE
cyrus_sasl pkgconfig is broken

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#6827]
```
Variable 'exec_prefix' not defined in '/nix/store/4qavw8p26qya69ijw5pic657ijf0cdsk-cyrus-sasl-2.1.26/lib/pkgconfig/libsasl2.pc'
```

macports patch: https://trac.macports.org/browser/trunk/dports/security/cyrus-sasl2/files/patch-libsasl2.pc.in.diff?rev=114886

**Comment by cstrahan** [comment]
I'm curious how our packages find cyrus_sasl's headers... unless this is a problem with a relatively new release of cyrus.

**Comment by domenkozar** [comment]
Reported upstream: https://bugzilla.cyrusimap.org/show_bug.cgi?id=3891

**Comment by Profpatsch** [comment]
(triage) upstream will resolve eventually, so close? @dom

**Comment by pSub** [comment]
This ticket should remain open until upstream provided a fix and that fix landed in nixpkgs.

**Comment by domenkozar** [comment]
2.1.27rc3 was released two months ago, so maybe in 2018 we can close this :)
