### ISSUE TITLE
nix-prefetch-url fails to fetch local file (1.5G)

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#6828]
```
$ nix-prefetch-url file:///home/ielectric/Downloads/PA_Linux_79317.tar.bz2                                                                                                                                                        
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 52 1463M   52  767M    0     0   519M      0  0:00:02  0:00:01  0:00:01  520M
curl: (23) Failed writing body (12256 != 16383)
/run/current-system/sw/bin/nix-prefetch-url: download of ‘file:///home/ielectric/Downloads/PA_Linux_79317.tar.bz2’ failed
```

**Comment by vcunat** [comment]
Do you know about this: https://nixos.org/wiki/How_to_add_large_files_to_the_nix-store? BTW, it's more of a nix issue, not nixpkgs.

**Comment by iElectric** [comment]
Yeah. I used `sha256sum /home/ielectric/Downloads/PA_Linux_79317.tar.bz2` to get the hash and `nix-store --add-fixed` to get the file inside the store. But why does curl bark? I have 8G of memory and the file is only 1.5G so this shouldn't be a problem.

**Comment by iElectric** [comment]
Figured it out, it's because of tmpfs

```
tmpfs           768M   20K  768M   1% /run/user/499
```

Running it as root results into:

```
$ nix-prefetch-url file:///home/ielectric/Downloads/PA_Linux_79317.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1463M  100 1463M    0     0   514M      0  0:00:02  0:00:02 --:--:--  479M
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

$  nix-env --version
nix-env (Nix) 1.9pre4045_bd91064
```

cc @edolstra

**Comment by vcunat** [comment]
It seems the file can't fit into your ``/tmp/``.

**Comment by iElectric** [comment]
Yeah, I figured. This should be better documented.

**Comment by vcunat** [comment]
I don't get what you want to document. Printing a better error message in this case?

**Comment by iElectric** [comment]
Clearly, curl failing is not a good error message if the file doesn't fit into `/tmp`. Ideally we could handle `file://` as a special case.

**Comment by vcunat** [comment]
Ah, yes: that way we would avoid the double copying.

**Comment by Profpatsch** [comment]
(triage) @vcunat @domenkozar solved?

**Comment by vcunat** [comment]
I don't think so, looking at git log for `<nix/src/nix-prefetch-url/>`.

**Comment by domenkozar** [comment]
Moved to https://github.com/NixOS/nix/issues/1014
