### ISSUE TITLE
Request: Update v8 to 7.6.48+

### ISSUE THREAD

**Issue by jollheef** [NixOS/nixpkgs#68290]
Hello,

I'm working on the packaging of [frida](https://github.com/frida/frida) for Nix, and one of the frida projects (frida-gum) requires the newer v8 ([version: '>=7.6.48'](https://github.com/frida/frida-gum/blob/186435fe16abebd0cf445b334e37dd4e046a3820/meson.build#L248)).
```
Dependency v8-7.0 found: NO (tried pkgconfig)
```
Unfortunately, it appears non-trivial to update – I tried to run update.sh on default.nix, but the result was not built successfully.

cc v8 maintainers: @cstrahan @proglodyte @matthewbauer

**Comment by matthewbauer** [comment]
The version in master is 7.4.255. But it looks like we are missing the pkgconfig file. Should be easy to fix.

**Comment by matthewbauer** [comment]
https://github.com/NixOS/nixpkgs/pull/68292

**Comment by jollheef** [comment]
> The version in master is 7.4.255.

Oh yes, I missed that It was already 7.* before update.sh.

I was confused by `v8_6_x = v8;` in [all-packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L13935).

**Comment by jollheef** [comment]
frida-gum requires [version: '>=7.6.48'](https://github.com/frida/frida-gum/blob/186435fe16abebd0cf445b334e37dd4e046a3820/meson.build#L248), so I still need an update of v8.

**Comment by Mic92** [comment]
I found frida quite hard to package in a pure way. I ended up with this: https://nixos.wiki/wiki/Frida

**Comment by jollheef** [comment]
> I found frida quite hard to package in a pure way.

Currently, I'm building each of submodules separately (not using main repo Makefile). In this way, there will be (at least, there's no right now) no purity issues.

> I ended up with this: https://nixos.wiki/wiki/Frida

Thanks, it'll be helpful till I'll get Frida to nixpkgs.

**Comment by FliegendeWurst** [comment]
By now v8 version 8.4.255 is packaged.
