### ISSUE TITLE
NixOS and changing nameservers in configuration.nix

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6830]
I just had an issue where I changed my configuration.nix to point at different nameservers (that resolved things that are not otherwise available) and also made some config changes in services to use those nameservers. That failed saying that it couldn't resolve my new names. I can probably make my particular service happen after the nameserver updates, but it seems in general like changing DNS settings should happen as early as possible in the update process, because everything else assumes it can resolve names properly.

**Comment by earldouglas** [comment]
I just ran into this one as well.

**Comment by copumpkin** [comment]
@edolstra is there currently a way to "jump in" ahead of binary cache resolution to change a setting like this?

I'm thinking of this kind of scenario:
1. User changes basic networking settings like nameservers or defaultGateway, while also specifying a custom binary cache or channel setting. The binary cache and/or channel are only accessible/resolvable once the networking settings apply.
2. User runs `nixos-rebuild switch`
3. User expects sensible things to happen.

My understanding is that right now the user would need to do the above in two stages, first changing the basic networking settings and then making changes that rely on those changes. Is that correct?

**Comment by Profpatsch** [comment]
(triage) any updates?

**Comment by copumpkin** [comment]
No changes, nope. I talked with @edolstra a bit at NixCon about this issue and he said a likely solution would have to do special handling for settings like this that affect everything else. So `nixos-rebuild switch` would have to manually extract out the core network settings from your configuration, manually apply it, then run the rest of the build. Unfortunately that breaks the atomicity of the update, so I'm still not sure how to do it sensibly.

Open to ideas!

**Comment by cleverca22** [comment]
in the case of dns servers, you could provide an alternative /etc/resolv.conf for the chroot'd builds that should have network access, then the host resolv.conf wont change and will remain atomic

**Comment by Profpatsch** [comment]
(triage) there were to references, any progress?
