### ISSUE TITLE
glibc cross aarch64-linux fails to build with gcc 8

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#68395]
**Describe the bug**
Seeing this in logs:

https://hydra.nixos.org/build/100198848

Appears to be from updating to gcc 8.

**Comment by vcunat** [comment]
I suppose we can [patch it](https://sourceware.org/git/?p=glibc.git;a=commit;h=780684eb04298977bc411ebca1eadeeba4877833) for 19.09 and [upgrade](https://github.com/NixOS/nixpkgs/pull/66528) for master.  _I haven't tested either for this bug so far._

**Comment by matthewbauer** [comment]
Fixed  in https://github.com/NixOS/nixpkgs/commit/3fcc4441d7ab18d10694a3dce3c8644339bcaf9d
