### ISSUE TITLE
wrapQtAppsHook fails to wrap PIEs

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#68404]
**Describe the bug**
Unfortunately, as I just discovered, some executables are built as PIEs (e.g. keepassxc) and these won't be wrapped after this change: https://github.com/nixos/nixpkgs/commit/88146a095f5040b5beb9612c63604493aefa9fd2. PIEs are technically isELFDyn, not isELFExec. Without wrapping, the programs won't start.

Ref. https://github.com/NixOS/nixpkgs/issues/65399.

**To Reproduce**
```
$ nix-build -A keepassxc && ./result/bin/keepassxc
[...]
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
[...]
Aborted (core dumped)
```

**Expected behavior**
PIEs would be wrapped too, and keepassxc would not abort startup.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.09.git.1a1a7ed (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.03.173426.541d9cce8af"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Guess the most obvious way to fix it properly is to get a function to detect if something is a position independent executable and use that in wrapQtAppsHook. A simpler alternative, since there shouldn't be too many occurrences, is to just wrap them manually with
```
dontWrapQtApps = true
preFixup = ''
  wrapQtApp $out/wherever
'';
```
