### ISSUE TITLE
[Feature request] Nightly  tagging

### ISSUE THREAD

**Issue by SRGOM** [NixOS/nixpkgs#68437]
Hello, I wanted to suggest/request a feature- tagging nightly github revisions. 

This request is motivated by my encountering https://github.com/NixOS/nixpkgs/issues/65399 (and coming on here to find a `rev` before the bug came up. Such tagging would help users move quickly to a known-working version. (I know I know, local download + git bisect... is one pretty-good way to achieve this).

The tagging could look like this: `n2019.04.01`. To be clear, I'm not asking for any stability guarantees, nor does the name signify anything as such. If nightly is too frequent and creates the risk of overtagging leading to difficulty in finding other tags, perhaps consider a weekly or fortnightly tagging? (Tagging would be auto).

There is one downside, a user using this for pinning internet facing software puts himself at risk. But I think anybody using a nightly version would know the risks.

**Comment by bjornfor** [comment]
If the nightly tag is just a tag every night(?), what is the value in that?

In the case of that issue, someone would in either case have to provide the rev/ref of a working version before that change, be it a commit id or a tag.

**Comment by FRidh** [comment]
I also fail to see the value of what you're proposing, especially as you describe a motivating issue but also do not expect any stability guarantees. At that point you can just take an arbitrary commit.

Now, you will probably want to have binary substitutes. In that case, all channel updates are recorded. E.g., see https://channels.nix.gsc.io/nixpkgs-unstable/history

**Comment by SRGOM** [comment]
@fridh this link pretty much solves what I'm trying to achieve.
