### ISSUE TITLE
Remove unnecessary uses of static ids

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#6843]
See previous discussion here https://github.com/NixOS/nixpkgs/pull/6722

Briefly, static ids should be used only for users/groups that have data portability requirements, otherwise the uid/gid may as well be dynamically allocated at system activation.

The purpose of this issue is tracking down services which do not require data portability and replace uses of static ids with `null`, causing the id to be dynamically allocated.

**Comment by wizeman** [comment]
What if a service doesn't write anything to disk (and therefore we assign a `uid` dynamically), but in a later update it *does* start writing things to disk and we miss it during the update? I'd guess that most maintainers, when updating a package, don't actually review the code changes.

Wouldn't it be safer to just statically assign uids? Or are we running out of numbers or something?

**Comment by joachifm** [comment]
@wizeman you're right. Removing static ids is a bit risky and has no immediate benefit that I can think of. The policy set out in ids.nix states that you shouldn't use numbers above 399, but there's still quite a bit to go.

Some services are by their nature unlikely to ever produce data anyone would care about moving between systems, though: nscd, rtkit, polkituser, dnsmasq, dhcpcd (this uid isn't even used, as far as I can tell) are some obvious candidates.

I personally don't care too much about removing static ids, so if there's a consensus that this brings more risk than benefit or a is complete waste of time, then by all means close this issue.

**Comment by peti** [comment]
I am in favor or removing unnecessary ids.

At the same time, I don't believe that we should have an issue for that subject. That kind of house-keeping is a continuous effort; it's not a one-time task that someone does and then it can be closed.

Just my 2 cents.

**Comment by joachifm** [comment]
Okay, I will close this issue at day's end if nobody has anything more to add. Hopefully, this issue will at least have made it a little bit easier for people to find information about this topic, should they care to look.

**Comment by wizeman** [comment]
If a `uid` is dynamically assigned, does it stay the same `uid` permanently in that system, even if the user disables a service and then enables it again (possibly also enabling other services in-between)?

**Comment by edolstra** [comment]
No, the name/uid mapping is forgotten when you run nixos-rebuild after removing it from the configuration. So there is a possibility that another user name might re-use the uid.

**Comment by wizeman** [comment]
Then the problem is not only if you move data between systems.

Since usernames may get reassigned new `uids`, and since removing a service from `configuration.nix` does not remove any potential on-disk data that the service wrote, then using dynamically-assigned `uids` may cause permission denied errors as long as a service writes *any* data to disk (even if that data never gets copied to another system).

**Comment by vcunat** [comment]
I don't see what's the advantage of non-static IDs. (We don't seem close to running out of available IDs.)

**Comment by rushmorem** [comment]
I think we have to be careful here. Not only will using dynamic `uids` for any services that store data on disk cause annoying permission problems in future if the service is reactivated; it might have security implications as well. New services will automatically own any data generated by a different old service. Now if this new service is malicious and your old service contained important and/or sensitive data, that will be a big problem.

**Comment by joachifm** [comment]
Seems like there are good reasons to not do this without careful consideration, if at all. Thanks for the feedback.
