### ISSUE TITLE
Adapt the Amazon CloudWatch Monitoring Scripts for Linux to NixOS

### ISSUE THREAD

**Issue by mdallali** [NixOS/nixpkgs#6848]
AWS have created some scripts that allow us to push some unavailable-to-CloudWatch custom linux metrics.

AWS only shares how this can be done in some Linux ditributions and does not include NixOS.

The documentation about this can be found here : http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/mon-scripts-perl.html

I have been trying to follow some of the cases described in the link above but ran into some issues installing the needed perl dependencies.

It would be awesome if we can add NixOS to the list of OS that allow us to use this feature.

**Comment by benley** [comment]
I have a use for this too, and might get around to it soon. I've got the CloudWatch Logs daemon packaged up already, if that's something you're also looking for.

**Comment by shyam-urolime** [comment]
commentedcommented

**Comment by ORESoftware** [comment]
Yeah I am personally looking to have NixOS added to this list:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html

**Comment by benley** [comment]
Is this still relevant?

**Comment by mipmip** [comment]
we are working on https://github.com/wearetechnative/amazon-cloudwatch-agent-nix
