### ISSUE TITLE
getent, getconf fail to build with musl

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#68482]
**Describe the bug**
When building with musl, the netbsd getent and getconf fail. It would probably be more elegant to use [the versions that are included with alpine](https://github.com/alpinelinux/aports/tree/master/main/musl).

**To Reproduce**
1. `nix build pkgs.pkgsCross.musl64.getent`

Current attempt: https://gist.github.com/yorickvP/be90114b26384c671c2ce69009f01fed

@dtzWill @domenkozar @shlevy @rasendubi

**Comment by jonringer** [comment]
using the `pkgsMusl` overlay seems to work for me...
```
$ nix-build -A pkgsMusl.getent
/nix/store/bx3cggx7r9dkj3d1dnj2arrd7af69sjf-getent-1003.1-2008
```

**Comment by Enteee** [comment]
@yorickvP  I am struggling to reproduce this.  Please provide the error that you are getting as well as the version of nixpkgs you see this happening. If you can not reproduce this yourself I'd suggest closing this issue.

**Comment by yorickvP** [comment]
My testcase works now, so yes, this is resolved.
