### ISSUE TITLE
bloomrpc - A UI for working with grpc services alternative to grpcui

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#68526]
**Project description**
BloomRPC aim to give the simplest and efficient developer experience for exploring and querying your GRPC services. 

**Metadata**

* homepage URL: https://github.com/uw-labs/bloomrpc
* source URL: https://github.com/uw-labs/bloomrpc
* license: LGPL-3.0
* platforms: unix, linux, darwin, windows

**Comment by kalbasit** [comment]
still important to me. I’ll see if I can package it myself over the weekend.

**Comment by abathur** [comment]
This appears to have been added in:
- https://github.com/NixOS/nixpkgs/pull/120292
