### ISSUE TITLE
libwebsockets 3.2.0 breaks Mosquitto

### ISSUE THREAD

**Issue by ralight** [NixOS/nixpkgs#68588]
libwebsockets 3.2.0 changed its behaviour in a way that breaks all versions of Mosquitto that use websockets, resulting in incoming connections being intermittent and very slow. It is fixed in their repository and will be in the next release presumably, but for now 3.2.0 is no good.

If Mosquitto is the only other package using libwebsockets, I would suggest downgrading to 3.1.0, which behaves fine. Mosquitto 1.6.5, which should be released today, will refuse to compile with libwebsockets 3.2.0.

**Comment by veprbl** [comment]
cc @peterhoeg

**Comment by peterhoeg** [comment]
mosquitto 1.6.5 fixes it - just haven't packaged it yet.

**Comment by ralight** [comment]
Mosquitto 1.6.5 does not fix this. There is a changelog entry which was written prior to this issue that is probably why you think it does have the fix. Sorry about that, I changed the changelog on the website post but not in the repo. The only fix for this is in libwebsockets itself.

**Comment by peterhoeg** [comment]
@ralight, it's pretty awesome having upstream providing proactive updates like this - much appreciated!
