### ISSUE TITLE
my-env sets TZ variable to "" even if it was not set to any value before

### ISSUE THREAD

**Issue by yvesf** [NixOS/nixpkgs#6859]
In file nixpkgs/pkgs/misc/my-env/loadenv.sh  `"$TZ"` should be only set if it was set before. 

Setting TZ to `""` is different from not setting it at all.

```bash
[ -n "$OLDTZ" ] && export TZ="$OLDTZ"
```

**Comment by joachifm** [comment]
Please submit a pull request
