### ISSUE TITLE
alsa-lib looking for plugin .so in the wong derivation

### ISSUE THREAD

**Issue by bencef** [NixOS/nixpkgs#6860]
I get errors like:

> [AO_ALSA] alsa-lib: dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /nix/store/608381h0c3ilqfdajrfn0f5gwlr58pmc-alsa-lib-1.0.28/lib/alsa-lib/libasound_module_pcm_jack.so

This shared object is provided by `alsa-plugins` derivation, not `alsa-libs`
i.e:

> /nix/store/xbnx8klb6jkadsl85sy9lhb6rmw4x7ar-alsa-plugins-1.0.28/lib/alsa-lib/libasound_module_pcm_jack.so

**Comment by bencef** [comment]
Just some additional info: using the wrapper script provided by `alsaPluginWrapper` doesn't solve it either.

**Comment by bencef** [comment]
I would like to hear from someone more experienced, but maybe an aggregate package (like for texLive) could solve this.

**Comment by kirelagin** [comment]
@bencef You are right. I was talking about the PulseAudio plugin simply because I believe that it is the only plugin used by almost everyone. Other plugins are kind of “special”, or “professional” and can be dealt with on per-expression basis, but the PulseAudio plugin should work out of the box without any extra configuration from the user or the expression maintainer.

**Comment by kirelagin** [comment]
BTW I just found this topic from 2009 with a relevant discussion: http://permalink.gmane.org/gmane.linux.distributions.nixos/2693.

An aggregate package seems to be a viable solution. The problem with this (which seems to be the one concerning @MarcWeber in the ML) is that adding plugins won’t be possible without rebuilds.

**Comment by bencef** [comment]
It's really tricky because ALSA_PLUGIN_DIRS is a compiletime constant in alsa-lib. (so the env-var approach won't work) I tried to add a lib for plugins like for the graphics drivers to /run/alsa-plugins.
The problem with this is that alsa-lib builds smixer into ALSA_PLUGIN_DIRS so it has to be inside the derivation. You can pass the configure flag --disable-mixer an then alsa-lib will build, but then gstreamer won't build anymore (i guess it tries to link against the smixer in alsa-lib).

I haven't tried the aggregate package yet becaouse I'm not sure how to make everything use the aggregate derivation instead of the alsa-lib.

**Comment by kirelagin** [comment]
By the way, looks like `alsaPluginWrapper` should be removed. Looks like there used to be a [patch](https://github.com/NixOS/nixpkgs/commit/862fcb0) in Nixpkgs that made `alsa-lib` respect this environment variable, but now it is [gone](https://github.com/NixOS/nixpkgs/commit/ab8ef63).

**Comment by kirelagin** [comment]
Shouldn’t the commit that removed the “unused” variable be reverted? I mean, we need a beautiful solution, but at least it worked before that. @aristidb @MarcWeber

**Comment by vcunat** [comment]
All the plugin so-files are relatively small in comparison to libasound (<300 kB together vs. ~1.4 MB), so we might consider having the default ``alsaLib`` attribute contain the plugins needed for pulseaudio playback. Our ``libpulseaudio`` attribute no longer needs ``alsaLib`` to build, so we should be able to reverse the dependency and make ``alsaLib`` depend on ``libpulseaudio``.

/cc @wkennington should know more about pulseaudio packaging. Perhaps it's a similar situation in there.

**Comment by bencef** [comment]
I was thinking about integrating the alsaPlugins into the alsaLib derivation altogether. (I need the jack plugin as well) It may not be an elegant solution but it's not that big an overhead (maybe some dependencies will need adjustments) And build all the plugins that are buildable.

Also I think the workaround was removed in official alsa project. See _Dynamic Loader helpers_ section here: http://www.alsa-project.org/main/index.php/Detailed_changes_v1.0.27_v1.0.27.1

**Comment by bencef** [comment]
I'm using this workaround right now:
https://github.com/bencef/nixpkgs/commit/7eba59dc47c16b6073dd176918a54b9bf1599bb4

**Comment by wizeman** [comment]
Also see #10848, which maybe adds more complexity to this issue because of a 32-bit library / 64-bit plugin mismatch.

**Comment by Profpatsch** [comment]
(triage) status?

**Comment by seanparsons** [comment]
I think I'm seeing an effect of this in attempting to update the Factorio derivation, but master nixpkgs has a more up to date version of alsaLib, but it appears to be trying to load the plugins from the system installed version of alsaPlugins.

**Comment by edom** [comment]
I also got hit by this issue while trying to run Nix-installed Audacity 2.2.2 (from nixpkgs master) on Ubuntu 14.04. Audacity playback doesn't make any sound because, it seems, `alsa-lib` hardcodes its plugin search directory.

```
ALSA lib dlmisc.c:254:(snd1_dlobj_cache_get) Cannot open shared library /nix/store/39ifv3aw047n5igdss5ymzsrwz2vql4h-alsa-lib-1.1.5/lib/alsa-lib/libasound_module_pcm_pulse.so
```

**Comment by edom** [comment]
I worked around this by creating a directory containing a symbolic link to `/usr/lib/x86_64-linux-gnu/libasound.so.2` and adding that directory to `LD_LIBRARY_PATH`.

**Comment by gnidorah** [comment]
I've found a workaround in Guix manual https://www.gnu.org/software/guix/manual/en/html_node/Sound-Services.html
1. Install alsaPlugins
2. Add the following lines to ~/.asoundrc or `sound.extraConfig`
```
pcm_type.jack {
  lib "/run/current-system/sw/lib/alsa-lib/libasound_module_pcm_jack.so"
}
```

**Comment by bencef** [comment]
Wow.  Thanks for the tip

**Comment by MDeltaX** [comment]
Still relevant in 19.09 :/

Does anyone know the syntax for importing rate conversion plugins ("speexrate", "samplerate", etc.) directly inside "asound.conf", or if there's a method without hackery by now?

Btw, @gnidorah https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/audio/jack.nix#L131-L134
seems to be affected by this, I'm using your workaround from here right now, together with `services.jack.alsa = false`.

**Comment by MDeltaX** [comment]
https://discourse.nixos.org/t/trying-to-include-custom-firmware-but-it-doesnt-appear-under-run-current-system/3044/2

**Comment by calbrecht** [comment]
> It's really tricky because ALSA_PLUGIN_DIRS is a compiletime constant in alsa-lib. (so the env-var approach won't work) I tried to add a dir for plugins like for the graphics drivers to /run/alsa-plugins.

Meanwhile it is even ALSA_PLUGIN_DIR instead of ALSA_PLUGIN_DIRS (notice the missing plural 'S')
https://github.com/michaelwu/alsa-lib/search?q=ALSA_PLUGIN_DIR

**Comment by calbrecht** [comment]
we could patch `alsa-lib` like so. But beware, this is actually only for the the second time that i am patching c code. I tried it with `aplay` and the `speexrate_best` converter and it's working so far.
<details><summary>environment-plugin-dir.patch</summary>

```patch
diff --git a/src/control/control.c b/src/control/control.c
index 33650155..935b0203 100644
--- a/src/control/control.c
+++ b/src/control/control.c
@@ -1333,13 +1333,17 @@ static int snd_ctl_open_conf(snd_ctl_t **ctlp, const char *name,
 			build_in++;
 		}
 		if (*build_in == NULL) {
-			buf1 = malloc(strlen(str) + sizeof(ALSA_PLUGIN_DIR) + 32);
+			char *path = getenv("ALSA_PLUGIN_DIR");
+			if (!path)
+				path = ALSA_PLUGIN_DIR;
+
+			buf1 = malloc(strlen(str) + strlen(path) + 32);
 			if (buf1 == NULL) {
 				err = -ENOMEM;
 				goto _err;
 			}
 			lib = buf1;
-			sprintf(buf1, "%s/libasound_module_ctl_%s.so", ALSA_PLUGIN_DIR, str);
+			sprintf(buf1, "%s/libasound_module_ctl_%s.so", path, str);
 		}
 	}
 #ifndef PIC
diff --git a/src/dlmisc.c b/src/dlmisc.c
index 012e61bc..a1b8fe96 100644
--- a/src/dlmisc.c
+++ b/src/dlmisc.c
@@ -82,9 +82,13 @@ void *snd_dlopen(const char *name, int mode, char *errbuf, size_t errbuflen)
 	char *filename = NULL;
 
 	if (name && name[0] != '/') {
-		filename = alloca(sizeof(ALSA_PLUGIN_DIR) + 1 + strlen(name) + 1);
+		char *path = getenv("ALSA_PLUGIN_DIR");
+		if (!path)
+			path = ALSA_PLUGIN_DIR;
+
+		filename = alloca(strlen(path) + 1 + strlen(name) + 1);
 		if (filename) {
-			strcpy(filename, ALSA_PLUGIN_DIR);
+			strcpy(filename, path);
 			strcat(filename, "/");
 			strcat(filename, name);
 			handle = dlopen(filename, mode);
diff --git a/src/pcm/pcm.c b/src/pcm/pcm.c
index 3a71d79b..a6ca6f3d 100644
--- a/src/pcm/pcm.c
+++ b/src/pcm/pcm.c
@@ -2495,13 +2495,17 @@ static int snd_pcm_open_conf(snd_pcm_t **pcmp, const char *name,
 			build_in++;
 		}
 		if (*build_in == NULL) {
-			buf1 = malloc(strlen(str) + sizeof(ALSA_PLUGIN_DIR) + 32);
+			char *path = getenv("ALSA_PLUGIN_DIR");
+			if (!path)
+				path = ALSA_PLUGIN_DIR;
+
+			buf1 = malloc(strlen(str) + strlen(path) + 32);
 			if (buf1 == NULL) {
 				err = -ENOMEM;
 				goto _err;
 			}
 			lib = buf1;
-			sprintf(buf1, "%s/libasound_module_pcm_%s.so", ALSA_PLUGIN_DIR, str);
+			sprintf(buf1, "%s/libasound_module_pcm_%s.so", path, str);
 		}
 	}
 #ifndef PIC
diff --git a/src/pcm/pcm_rate.c b/src/pcm/pcm_rate.c
index 5dc8a927..ed8d49fc 100644
--- a/src/pcm/pcm_rate.c
+++ b/src/pcm/pcm_rate.c
@@ -1263,7 +1263,7 @@ static const char *const default_rate_plugins[] = {
 
 static int rate_open_func(snd_pcm_rate_t *rate, const char *type, const snd_config_t *converter_conf, int verbose)
 {
-	char open_name[64], open_conf_name[64], lib_name[128], *lib = NULL;
+	char open_name[64], open_conf_name[64], lib_name[PATH_MAX + 1], *lib = NULL;
 	snd_pcm_rate_open_func_t open_func;
 	snd_pcm_rate_open_conf_func_t open_conf_func;
 	int err;
@@ -1271,8 +1271,11 @@ static int rate_open_func(snd_pcm_rate_t *rate, const char *type, const snd_conf
 	snprintf(open_name, sizeof(open_name), "_snd_pcm_rate_%s_open", type);
 	snprintf(open_conf_name, sizeof(open_conf_name), "_snd_pcm_rate_%s_open_conf", type);
 	if (!is_builtin_plugin(type)) {
-		snprintf(lib_name, sizeof(lib_name),
-				 "%s/libasound_module_rate_%s.so", ALSA_PLUGIN_DIR, type);
+		char *path = getenv("ALSA_PLUGIN_DIR");
+		if (!path)
+			path = ALSA_PLUGIN_DIR;
+
+		snprintf(lib_name, PATH_MAX, "%s/libasound_module_rate_%s.so", path, type);
 		lib = lib_name;
 	}
 

```

</details>

**Comment by kirelagin** [comment]
Or we could just bring back the original patch.

> By the way, looks like `alsaPluginWrapper should be removed. Looks like there used to be a [patch](https://github.com/NixOS/nixpkgs/commit/862fcb0) in Nixpkgs that made `alsa-lib` respect this environment variable, but now it is [gone](https://github.com/NixOS/nixpkgs/commit/862fcb0).

**Comment by calbrecht** [comment]
@kirelagin i guess it is still there https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/alsa-lib/alsa-plugin-conf-multilib.patch but it is doing nothing for loading rate converters since they are neither loaded through patched `snd_ctl_open_conf` from `src/control/control.c` nor through `snd_pcm_open_conf` from `src/pcm/pcm.c` but through `rate_open_func` from `src/pcm/pcm_rate.c`

**Comment by bencef** [comment]
Since I opened this issue I'm not sure what to do with it, but since learning more about alsa config this is no longer an issue for me.  I'll post my config hoping it helps people:

I have `(alsaPlugins.override {inherit libjack2;})` in my `environment.systemPackages`

And my config looks like this:

```
  sound.extraConfig =
    ''
        pcm.!default {
            type plug
            slave.pcm {
              @func getenv
              vars [ ALSAPCM ]
              default "rawjack"
            }
        }

        ctl.!default {
            type hw
            card 1
        }

        pcm_type.jack {
          lib "${pkgs.alsaPlugins}/lib/alsa-lib/libasound_module_pcm_jack.so"
        }

        # Routing ALSA to jack:
        # <http://jackaudio.org/faq/routing_alsa.html>.
        pcm.rawjack {
          type jack
          playback_ports {
            0 system:playback_1
            1 system:playback_2
          }

          capture_ports {
            0 system:capture_1
            1 system:capture_2
          }
        }

        #asym fun start here. we define one pcm device called "dmixed"
        pcm.dmixed {
            ipc_key 1025
            type dmix
            slave {
              pcm "hw:1,0"
              period_time 0
              period_size 1024
              buffer_size 4096
              rate 44100
            }
        }

        #one called "dsnooped" for capturing
        pcm.dsnooped {
            ipc_key 1027
            type dsnoop
            slave.pcm "hw:1,0"
        }

        #and this is the real magic
        pcm.asymed {
            type asym
            playback.pcm "dmixed"
            capture.pcm "dsnooped"
        }

        #a ctl device to keep xmms happy
        ctl.pasymed {
            type hw
            card 1
        }

        #for aoss:
        pcm.dsp0 {
            type plug
            slave.pcm "asymed"
        }

        ctl.mixer0 {
            type hw
            card 1
        }
  '';
```

This finds the jack plugin just fine due to the 
```
pcm_type.jack {
  lib "${pkgs.alsaPlugins}/lib/alsa-lib/libasound_module_pcm_jack.so"
}
```

If I want to run something (for example steam) that won't be able to run with jack then I just fallback to my mixing PCM with
- stopping jack
- exporting `ALSAPCM=asymed`

**Comment by jahkeup** [comment]
This still needs to be addressed (either by the wrapper or by patching the package, maybe both).

I've been using the same trick as @bencef and it works well enough, but it'd have been great to have the package itself or the wrapper handle users' additional plugin paths out of the box.

**Comment by jamesluke** [comment]
With the release of v1.2.4 on 19 Oct, alsa-lib gained official support for an `ALSA_PLUGIN_DIR` environment variable. It was added in [this commit](https://github.com/alsa-project/alsa-lib/commit/8580c081c25678d11278efcb61bd15cf44d0a225), following [this discussion](https://github.com/alsa-project/alsa-lib/issues/82) with some Guix folks.

Note that this environment variable only supports a single directory, unlike the (effectively unused?) alsa-plugin-conf-multilib.patch which provided a plural `ALSA_PLUGIN_DIRS` environment variable.

One nice effect is that we don't have to patch alsa-libs any more.

Thoughts on how to best take advantage of the new feature?

**Comment by jahkeup** [comment]
> Thoughts on how to best take advantage of the new feature?

Without writing an updated patch for multiple plugin directory support, the upstream's `ALSA_PLUGIN_DIR` can probably be put to use immediately by pointing to symlink farm of plugins. Haven't tried this, but I suspect it (or something similar) would do the trick.

The linked GUIX thread included review of a patch for multiple plugin directory support. It looked promising but its growing stale with outstanding feedback.

They've not responded to news of upstream `ALSA_PLUGIN_DIR`; I do wonder if they'd consider contributing their multi-directory patch or not - especially given that there's now *some* kind of upstream support.

**Comment by mbakke** [comment]
> Without writing an updated patch for multiple plugin directory support, the upstream's `ALSA_PLUGIN_DIR` can probably be put to use immediately by pointing to symlink farm of plugins. Haven't tried this, but I suspect it (or something similar) would do the trick.

Guix's `search-path` property will automatically create a create a symlink union of the relevant plugins for single-entry search paths.  It's how Chromium extensions and `pass` plugins are discovered, for example.

> They've not responded to news of upstream `ALSA_PLUGIN_DIR`; I do wonder if they'd consider contributing their multi-directory patch or not - especially given that there's now _some_ kind of upstream support.

It's just because we haven't gotten around to update alsa-lib yet, as it missed the latest 'staging' cycle.

**Comment by lfam** [comment]
Hi,

I'm the author of that patch from Guix, although it grew out my reading of the old unused nixpkgs patch.

I ran out of energy for keeping track of all the "C issues" one has to think about... if alsa-lib's new ALSA_PLUGIN_DIR meets our needs then I'll be glad to leave the patch behind.

Feel free to use the patch in any way you like — it does work fine and, as a part of Guix, the license is GPL3+.

**Comment by zeuner** [comment]
> An aggregate package seems to be a viable solution

I implemented the aggregate package approach (https://github.com/NixOS/nixpkgs/pull/277180) and appreciate your thoughts on it.
