### ISSUE TITLE
haskell hosc

### ISSUE THREAD

**Issue by miguel-negrao** [NixOS/nixpkgs#6864]
Perhaps I'm doing something wrong, but I can't seem to build hosc. I'm trying from a clone of the github nixpkgs on which I did a 'git pull' just now:

```
nix-build ~/Development/Haskell/nix/nixpkgs --option extra-binary-caches http://hydra.nixos.org --option extra-binary-caches http://hydra.cryp.to -A haskellngPackages.hosc

...
Dependency binary -any: using binary-0.7.1.0
...

[ 6 of 20] Compiling Sound.OSC.Coding.Decode.Binary ( Sound/OSC/Coding/Decode/Binary.hs, dist/build/Sound/OSC/Coding/Decode/Binary.o )

Sound/OSC/Coding/Decode/Binary.hs:88:23: Not in scope: ‘G.isolate’
builder for ‘/nix/store/qijllhq8d4gb099mb5vcc14j8nb1y92v-haskell-hosc-0.15.drv’ failed with exit code 1
```

It is using the wrong version of the 'binary' package, I think. I don't understand why since in  nixpkgs/pkgs/top-level/haskell-packages.nix it has

```
 hosc = callPackage ../development/libraries/haskell/hosc {
    binary = self.binary_0_7_2_2;
     dataBinaryIeee754 = self.dataBinaryIeee754.override { binary = self.binary_0_7_2_2; };
};
```

**Comment by peti** [comment]
The overrides from `pkgs/top-level/haskell-packages.nix` apply only to the old package set. Haskell NG's configuration lives in `pkgs/development/haskell-modules/configuration-*`, and those files lacked the necessary overrides, indeed.
