### ISSUE TITLE
dockerTools.buildLayeredImage fails while building bulk-layers.drv

### ISSUE THREAD

**Issue by toelke** [NixOS/nixpkgs#68672]
**Describe the bug**
When trying to delve into using nix to build docker images, I tried building the example:
```
pkgs.dockerTools.buildLayeredImage {
  name = "hello";
  contents = [ pkgs.hello ];
}
```

It fails with:
```
$ nix-build test.nix
these derivations will be built:
  /nix/store/50jhzs5gjlxjyrkz5c7ikmza84m5qlr0-bulk-layers.drv
  /nix/store/xi89g2zr5rw175bvmc6ipigpzlhjfimy-closure.drv
  /nix/store/7p6wg7xiv3wi4fnybaby0k8whf29ic26-closure-paths.drv
  /nix/store/bcg2rgzk48imzxvvqwfw7zwyhsrs1926-hello-granular-docker-layers.drv
  /nix/store/vd38yvwczspa9137l956sxvmnghbjplv-hello-customisation-layer.drv
  /nix/store/la0nnj2f3qh9687hkk0012vn2k6zvh5k-docker-image-hello.tar.gz.drv
building '/nix/store/50jhzs5gjlxjyrkz5c7ikmza84m5qlr0-bulk-layers.drv'...
unpacking sources
variable $src or $srcs should point to the source
builder for '/nix/store/50jhzs5gjlxjyrkz5c7ikmza84m5qlr0-bulk-layers.drv' failed with exit code 1
cannot build derivation '/nix/store/xi89g2zr5rw175bvmc6ipigpzlhjfimy-closure.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vd38yvwczspa9137l956sxvmnghbjplv-hello-customisation-layer.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/la0nnj2f3qh9687hkk0012vn2k6zvh5k-docker-image-hello.tar.gz.drv': 1 dependencies couldn't be built
error: build of '/nix/store/la0nnj2f3qh9687hkk0012vn2k6zvh5k-docker-image-hello.tar.gz.drv' failed
```

I can reproduce the issue on another machine.

**Metadata**
```
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-18362-Microsoft, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(me): `"nixpkgs-20.03pre192821.b425012fdf4"`
 - nixpkgs: `/home/me/.nix-defexpr/channels/nixpkgs`
```
on one machine and
```
$ nix run nixpkgs.nix-info -c nix-info -m
error: attribute 'nixpkgs' in selection path 'nixpkgs.nix-info' not found
```
(???) on the other.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by danieldk** [comment]
I cannot reproduce this issue with the current nixpkgs:

```
% cat default.nix
{ dockerTools, hello }:

dockerTools.buildLayeredImage {
  name = "hello";
  contents = [ hello ];
}
% nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
[...]
Finished building layer 'hello-granular-docker-layers'
building '/nix/store/la0nnj2f3qh9687hkk0012vn2k6zvh5k-docker-image-hello.tar.gz.drv'...
Cooking the image...
Finished.
/nix/store/2z47145w71ihvricdj3ka7x2h4qsighw-docker-image-hello.tar.gz
```

What does your full `test.nix` look like?

**Comment by toelke** [comment]
```
{ pkgs ? import <nixpkgs> {} }:
pkgs.dockerTools.buildLayeredImage {
  name = "hello";
  contents = [ pkgs.hello ];
}
```

**Comment by toelke** [comment]
I'll try tomorrow if updating the nixpgs help (it did not on Friday).

Thanks for helping!

**Comment by toelke** [comment]
Hi,

using "your" default.nix and command, I get the same error.

Please not that I use a clean and never-used installation of nix -- perhaps I am missing something?

Thanks again for the help!

**Comment by toelke** [comment]
I know that this worked earlier this year. I tried downgrading the nixpks which did not work. So I assume that something else has changed...

**Comment by toelke** [comment]
I still have not gotten this to work, but do not have time to pursue this futher. I am very sorry about that. Thanks for the help!

**Comment by danieldk** [comment]
I am sorry to hear that it still doesn't work! I just noticed the kernel version `Linux 4.4.0-18362-Microsoft`. Is this on Windows Subsystem for Linux? I don't have a Windows machine to test this there, but I think it would be a useful data point in case someone else runs into this problem in the future.

**Comment by danieldk** [comment]
The derivation that fails, `bulk-layers` uses `symlinkJoin`. There is another issue with regards to `symlinkJoin` on WSL (assuming that you are using WSL):

https://github.com/NixOS/nixpkgs/issues/26506

**Comment by toelke** [comment]
Yes, I used windows but had exactly the same error-messages with a "real" Linux.

**Comment by thmzlt** [comment]
I'm getting this error as well when trying to build a layered image from Nix running in a Docker image created with `buildImageWithNixDb`.
