### ISSUE TITLE
gitlab module permission denied after upgrade

### ISSUE THREAD

**Issue by schneefux** [NixOS/nixpkgs#68696]
**Describe the bug**
#66274 breaks existing GitLab installations.
In a 19.03 GitLab installation, in the state directory…
  * `/gitlab_shell_secret` is owned by root and writable by only root
  * `/config/secrets.yml` and `/config/database.yml` are linked to the nix store

The new startup script from #66274 attempts to write all of these files, but has insufficient permissions because it is running as `gitlab` and the two ymls are read only.

In order to upgrade, you have to:
* `chown gitlab:gitlab /gitlab_shell_secret`
* `rm /config/database.yml`
* `rm /config/secrets.yml`

This change should be backwards compatible or the migration path should be documented.

cc @talyz @flokli 

Great work by the way, my store does not have any secrets anymore :)

**Comment by aanderse** [comment]
Was mostly just testing out assigning issues to people with non commit access as we never used to be able to do that :tada:

@talyz if you're unable to take this on please mention and we can remove your name as assignee.

**Comment by talyz** [comment]
@schneefux Thanks for testing and reporting this! I believe #68721 would solve this, but if you could test it, that would be great. Thanks! :)

@aanderse Ah, cool! I can even see an `unassign me` option next to my name, so I guess I could do so myself, if I wanted to. :)
