### ISSUE TITLE
nix-copy-closure problem was really a user nixos setup problem!

### ISSUE THREAD

**Issue by ardumont** [NixOS/nixpkgs#6879]
Hello,

I'm trying to copy a closure from a nixos box to another but I'm unable to make it work.

I've built a new `haskellPackages.xmonad` (0.12) on my lenovo machine and I want to copy the closure on my dagobah machine.

```sh
# tony at lenovo in ~/repo/perso/nixpkgs on git:update-xmonad x [20:05:23]
$ nix-copy-closure --to tony@dagobah  /nix/store/d5vgamnf1hhqd8pz8xp9vnasj4kv7xz8-haskell-xmonad-ghc7.8.4-0.12-shared
zsh:1: command not found: nix-store
unable to connect to ‘tony@dagobah’; falling back to old closure copying method
zsh:1: command not found: nix-store
Died at /nix/store/ffig6yaggbh12dh9y5pnf1grf5lqyipz-nix-1.8/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi/Nix/CopyClosure.pm line 100.
```

Note:
- both machines are on nixos 14.12 
- lenovo and dagobah are on the same network and see each other
- I connect from lenovo to dagobah
- I use ssh-agent and ssh connection is ok:

```sh
# tony at lenovo in ~/repo/perso/nixpkgs on git:update-xmonad x [20:09:58]
$ ssh tony@dagobah
Last login: Wed Mar 18 19:38:31 2015 from 192.168.0.15
Syndaemon already running...
 ____________________________________
 / I wonder if I should put myself in \
 \ ESCROW!!                           /
  ------------------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                   ||----w |
                   ||     ||

# tony at dagobah in ~ [20:10:04]
$
```

Is there something I do wrong?

Thanks.

Cheers,

**Comment by spwhitt** [comment]
Make sure you can run nix commands through ssh:

```
ssh tony@dagobah nix-env -h
```

**Comment by vcunat** [comment]
The problem might be related to the fact that the default shell is zsh (apparently).

**Comment by spwhitt** [comment]
Ahh I didn't see the zsh. @ardumont, simply source `.nix-profile/etc/profile.d/nix.sh` from `~/.zshenv`. `zshrc` is only used for interactive shells, and as such is not sourced before running remote commands through ssh non-interactively (as nix-copy-closure does).

**Comment by ardumont** [comment]
> Make sure you can run nix commands through ssh:
>     ssh tony@dagobah nix-env -h

Right, baby steps!

> If the above fails make sure you're sourcing .nix-profile/etc/profile.d/nix.sh in your shell init file (bashrc)

```sh
# tony at lenovo in ~ [22:57:51]
$ ssh tony@dagobah nix-env -h
zsh:1: command not found: nix-env
```

Indeed, it fails.

> The problem might be related to the fact that the default shell is zsh (apparently).

Yes, I use zsh as my default shell.
It seems to be the reason indeed.

> zshrc is only used for interactive shells, and as such is not sourced before running remote commands
> through ssh non-interactively (as nix-copy-closure does).

I did not know that, thanks!

> Ahh I didn't see the zsh. @ardumont, simply source .nix-profile/etc/profile.d/nix.sh from ~/.zshenv.

I do not have such file as `~/.nix-profile/etc/profile.d/nix.sh` (I did not install nix, I use the one that comes along nixos, so nix 1.8).
There exists a file on my system though `/nix/store/ffig6yaggbh12dh9y5pnf1grf5lqyipz-nix-1.8/etc/profile.d/nix.sh`.

--

After forcing a nix install on my dagobah box using nix-env:

```sh
nix-env -i nix
```

The link `nix.sh` appears where it's supposed to (not sure this is the way though).

Also after adding a new file `~/.zshenv` file in my dagobah box with this content:

```sh
[ -f ~/.nix-profile/etc/profile.d/nix.sh ] && . ~/.nix-profile/etc/profile.d/nix.sh
```

I have a new error which seems promising.

```sh
# tony at lenovo in ~ [23:17:41]
$ ssh tony@dagobah nix-env --help
error: command ‘man nix-env’ failed: No such file or directory
```

--

Trying out nix-copy-closure again, I got also another error:

```sh
# tony at lenovo in ~ [23:23:56]
$ nix-copy-closure --to tony@dagobah /nix/store/d5vgamnf1hhqd8pz8xp9vnasj4kv7xz8-haskell-xmonad-ghc7.8.4-0.12-shared
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
unable to connect to ‘tony@dagobah’; falling back to old closure copying method
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
Died at /nix/store/vgs2asxq5ldha99s98jx6d4wldj9wdpv-nix-1.9pre4045_bd91064/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi/Nix/CopyClosure.pm line 100.
```

Thanks for your time guys.

**Comment by ardumont** [comment]
Ok.

I found something that worked.

What I understood from the error I showed you is that the `PATH` is not rightly set once ssh connected to the dagobah box.

So, I updated my dagobah's `~/.zshenv`:

```sh
source /etc/profile

[ -f ~/.nix-profile/etc/profile.d/nix.sh ] && . ~/.nix-profile/etc/profile.d/nix.sh
```

And now, `ssh tony@dagobah nix-env --help` works (I won't copy paste the too long result).

And also nix-copy-closure command is now working (running right now).

```sh
# tony at lenovo in ~ [23:46:18]
$ nix-copy-closure --to tony@dagobah /nix/store/d5vgamnf1hhqd8pz8xp9vnasj4kv7xz8-haskell-xmonad-ghc7.8.4-0.12-shared
copying 13 missing paths (854.87 MiB) to ‘tony@dagobah’...
exporting path ‘/nix/store/c6qx0qffanfzrygw26k3wh8xn586dn5h-ghc-7.8.4’
```

I suppose I can close this as this is finally a problem of box setup.

What do you think?

Thanks for the help!

**Comment by spwhitt** [comment]
I didn't realize this was a NixOS machine. I foolishly assumed it wasn't because I'd encountered the same problem with non-nixos installs. Are you using `program.zsh.enable = true` in your configuration.nix?  If yes, this could be a bug in that NixOS module. If no, try it out and you might no longer need ~/.zshenv

**Comment by ardumont** [comment]
> Are you using program.zsh.enable = true in your configuration.nix? 
> If no, try it out and you might no longer need ~/.zshenv

No.
Trying right now!

**Comment by ardumont** [comment]
>>    Are you using program.zsh.enable = true in your configuration.nix?
>>   If no, try it out and you might no longer need ~/.zshenv

> No.
> Trying right now!

It works!

Here are my steps, on dagobah box:
- remove ~/.zshenv
- update configuration.nix to add the attribute you mention.
- rebuild nixos configuration 

On lenovo, trigger nix-copy-closure command.

And it works!

So definitely a problem on my side!

Thank!
Definitely a better approach!
