### ISSUE TITLE
request: update TuxGuitar to 1.5

### ISSUE THREAD

**Issue by userabc123xyz** [NixOS/nixpkgs#68814]
The current version of TuxGuitar is 1.2, which is old. It would be good to have a newer 1.5 TuxGuitar available in nixpkgs.

**Comment by prusnak** [comment]
Package update in pull request https://github.com/NixOS/nixpkgs/pull/72081

**Comment by bjornfor** [comment]
Closing since https://github.com/NixOS/nixpkgs/pull/72081 was merged.
