### ISSUE TITLE
builtins.fetchGit cannot find git binary

### ISSUE THREAD

**Issue by timstott** [NixOS/nixpkgs#68828]
**Describe the bug**
I am experimenting with NixOS on a clean VirtualBox install ([nixos-19.03.173489.af5481e9b77-x86_64-linux](https://releases.nixos.org/nixos/19.03/nixos-19.03.173489.af5481e9b77/nixos-19.03.173489.af5481e9b77-x86_64-linux.ova)) and running into issues with `builtins.fetchGit`.

According to the `nixos-rebuild test` output it  appears `builtins.fetchGit`` is unable to find the `git` binary.

```nix
# configuration.nix

{ config, pkgs, ... }:

let 
  unstable = import(builtins.fetchGit {
    name = "nixpkgs-unstable-2019-09-09";
    url = "https://github.com/NixOS/nixpkgs-channels";
    ref = "nixpkgs-unstable";
    rev = "e19054ab3cd5b7cc9a01d0efc71c8fe310541065";
  }) {};
in
{
  imports = [ 
    <nixpkgs/nixos/modules/installer/virtualbox-demo.nix>
  ];

  environment.systemPackages = [
    pkgs.wget
    pkgs.vim
    unstable.tree
  ];
}
```

```
# rebuild output

sudo nixos-rebuild test
...
fetching Git repository 'https://github.com/NixOS/nixpkgs-channels'...
error: executing 'git': No such file or directory
error: program 'git' failed with exit code 1
```

**To Reproduce**
1. Download VirtualBox image [nixos-19.03.173489.af5481e9b77-x86_64-linux](https://releases.nixos.org/nixos/19.03/nixos-19.03.173489.af5481e9b77/nixos-19.03.173489.af5481e9b77-x86_64-linux.ova)
2. Boot virtual machine with the downloaded image
3. Copy & Paste `configuration.nix` provided above
4. Run `sudo nixos-rebuild test`

**Expected behavior**
I would expect `builtins.fetchGit` to have the `git` package available.

**Screenshots**
<img width="498" alt="image" src="https://user-images.githubusercontent.com/1334474/64918219-37551d00-d793-11e9-84c3-accf11361297.png">

**Additional context**
-

**Metadata**
```
[demo@nixos:~]$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.72, NixOS, 19.03.173491.48d2e27b746 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173491.48d2e27b746"`
 - channels(demo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
git is an impure dependency of Nix and needs to be installed additionally, as you've found out.

> I would expect builtins.fetchGit to have the git package available.

It was decided not to because minimal systems may not need git.

**Comment by FRidh** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/46603
