### ISSUE TITLE
ibus with libpinyin stopped working after upgrade to nixos-19.09 channel

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#68837]
**Describe the bug**
I configured https://nixos.org/channels/nixos-19.09 to be my new nixos channel and ran `nixos-rebuild switch` followed by a manual reboot.

My ibus was configured so that I can switch between three input methods (“Chinese - Bopomofo”, “Chinese - Intelligent Pinyin”, and “German - German” with <Super>y / Windows-Y.

The Windows-Y key combination doesn't seem to have an effect anymore. Nothing gets changed, when I press the Windows key and Y, no small window indicating the selected input method gets shows (this was done before the change to 19.09).

Here are the relevant parts of my `configuration.nix`:

```nix
{
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "de";
    defaultLocale = "zh_TW.UTF-8";
    inputMethod = {
      enabled = "ibus";
      ibus.engines = with pkgs.ibus-engines; [ libpinyin mozc ];
    };
  };

  environment.systemPackages = with pkgs; [
    wget vim lvm2 cryptsetup emacs firefox mutt git bash-completion dmenu xorg.xmodmap xorg.libXinerama rxvt_unicode ibus ibus-engines.libpinyin libpinyin ibus-engines.mozc xorg.xev file anki libreoffice-fresh unzip evince patchelf gnome3.gnome-terminal feh nixops usbutils w3m html-tidy haskellPackages.stack leiningen mercurial clojure openjdk gnumake aspell aspellDicts.de slack gimp gnuplot whois gcc dia xournal killall tree cmake binutils-unwrapped openssl gcc-arm-embedded-7 rustup gnupg gnome3.vte manpages pmutils numlockx udev signal-desktop nomacs x2goclient drone-cli pwgen gdb bind.dnsutils haskellPackages.xmobar haskellPackages.xmonad haskellPackages.xmonad-contrib haskellPackages.xmonad-extras eagle exercism clang-tools hlint pavucontrol weechat yubioath-desktop yubikey-manager yubikey-manager-qt yubikey-personalization yubikey-personalization-gui gnucash libchipcard aqbanking gwenhywfar
    (texlive.combine {
      inherit (texlive)
      scheme-medium a4wide bclogo changebar csquotes ctex dinbrief enumitem environ fandol fourier framed mdframed multirow needspace noto todonotes trimspaces xecjk xpinyin zhnumber wrapfig capt-of;
    })
  ];
}
```

When I run `ibus-setup` and select one of the input methods then pressing the Preferences button, nothing opens but I get the following message on the terminal window from which I started `ibus-setup`:

```
Traceback (most recent call last):
  File "main2.py", line 32, in <module>
    from gi import require_version as gi_require_version
ModuleNotFoundError: No module named 'gi'
```

**Expected behavior**
I would expect to be able to switch keyboard layouts as before with the Windows-Y key combination.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.13, NixOS, 19.09beta181.64e38f246ae (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta181.64e38f246ae, unstable-19.09pre192418.e19054ab3cd"`
 - channels(matthias): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute:
- ibus
- ibus-engines.libpinyin
- ibus-engines.mozc
module:
- i18n.inputMethod
```

**Comment by jtojnar** [comment]
Could you please check if #71442 fixes the issue for you?
