### ISSUE TITLE
optimus-manager GPU switching on Optimus laptops with a dual Nvidia/Intel GPU configuration

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#68849]
**Project description**
This Linux program provides a solution for GPU switching on Optimus laptops (i.e laptops with a dual Nvidia/Intel GPU configuration).
Supported display managers are : SDDM, LightDM, GDM.

**Metadata**

* homepage URL: https://github.com/Askannz/optimus-manager
* source URL: https://github.com/Askannz/optimus-manager
* license: mit
* platforms: linux

**Comment by eadwu** [comment]
Won't be implemented, at least by me. PRIME sync and offload should cover all use cases for most NVIDIA GPUs as of this point. If the GPU is too old to support PRIME offload, at that point it might be better to use Bumblebee.

**Comment by mudrii** [comment]
Thank you @eadwu for the update I will test  PRIME sync and offload from Nvidia and see how system behaves.
