### ISSUE TITLE
throttled Fix Intel CPU Throttling on Linux

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#68846]
**Project description**
The CPU package power limit (PL1/2) is forced to a value of 44 W (29 W on battery) and the temperature trip point to 95 'C (85 'C on battery) by overriding default values in MSR and MCHBAR every 5 seconds (30 on battery) to block the Embedded Controller from resetting these values to default.

**Metadata**

* homepage URL: https://github.com/erpalma/throttled
* source URL: https://github.com/erpalma/throttled
* license: mit
* platforms: linux

**Comment by periklis** [comment]
The package and an nixos module are already included in nixpkgs:
Package: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/throttled/default.nix
Module: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/throttled.nix
