### ISSUE TITLE
turbostat — Report processor frequency and idle statistics

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#68847]
**Project description**
turbostat — Report processor frequency and idle statistics

**Metadata**

* homepage URL: https://www.kernel.org
* source URL: https://github.com/torvalds/linux/tree/master/tools/power/x86/turbostat
* license: gpl2+
* platforms: linux

**Comment by dtzWill** [comment]
Happened to put together a turbostat expression just a day or so ago, see the PR! :)
