### ISSUE TITLE
alacritty reports strange error message on startup (unstable)

### ISSUE THREAD

**Issue by gregor-alexandru** [NixOS/nixpkgs#68854]
**Describe the bug**
Alacritty starts with this error message:
```
[2019-09-15 19:05] [WARN] Config window.start_maximized is deprecated; please use window.startup_mode instead
[2019-09-15 19:05] [WARN] Config render_timer is deprecated; please use debug.render_timer instead
[2019-09-15 19:05] [WARN] Config persistent_logging is deprecated; please use debug.persistent_logging instead
```
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.13, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd, nixpkgs-20.03pre193019.a26445a2ddf"`
 - channels(earendil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: alacritty
```

**Comment by mimame** [comment]
Hi @gregor-alexandru 

Don't worry, that messages are warning about deprecated variables in the configuration file
You can check that changes in the release changelog here: https://github.com/jwilm/alacritty/releases/tag/v0.3.3
And you can use the configuration file from the official repository as reference to do the changes https://github.com/jwilm/alacritty/blob/v0.3.3/alacritty.yml

Don't hesitate to ask if you find any kind of problem

**Comment by mimame** [comment]
When you update a program with a configuration file the default behaviour is update the file manually manually according to the updates.
But when you install that program from zero, of course, the last configuration file is installed.

**Comment by gregor-alexandru** [comment]
Thanks a lot!
