### ISSUE TITLE
Icons doens't showed in Eolie

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#68851]
**Describe the bug**
Eolie doesn't show icons

**To Reproduce**
Run Eolie
![image](https://user-images.githubusercontent.com/6325757/64924139-7611c400-d7e1-11e9-8745-79fc4d517b17.png)

**Expected behavior**
Eolie with icons like in [the website's screnshot ![](https://wiki.gnome.org/Apps/Eolie?action=AttachFile&do=get&target=screenshot.jpg)](https://wiki.gnome.org/Apps/Eolie)

**Additional context**
When i start Eolie from the console, i have this output

```
eolie
GLib-GIO-Message: 17:38:23.068: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[INFO] 2019-09-15 17:38:23 PyFxA missing: pip3 install --user pyfxa
[INFO] 2019-09-15 17:38:23 Cyrpto missing: pip3 install --user pycrypto

(org.gnome.Eolie:18381): Gtk-WARNING **: 17:38:23.195: Could not find the icon 'go-previous-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
Could not initialize PyGObjectGLib-GIO-Message: 17:38:23.686: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[ERROR] 2019-09-15 17:38:28 DatabasePhishing::__save_rules():Expecting value: line 1 column 1 (char 0) -> b'You have exceeded the request rate limit for this method. Please see the response headers for usage stats. For more information about rate limiting on Phishtank, please see our developer site: http://www.phishtank.com/developer_info.php'
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.03.173453.0d79decdb3b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(pinage404): `"home-manager-19.03, nixos-19.03.173450.609fe21661d, nixos-unstable-19.09pre191617.4e60699fa72"`
 - channels(root): `"nixos-19.03.173495.7339bd47600"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

i don't know how to fill the previous fields but it should be there https://github.com/NixOS/nixpkgs/blob/4d4b67b65e831159430a036f64d323e3cc007701/pkgs/applications/networking/browsers/eolie/default.nix

**Comment by worldofpeace** [comment]
Please install an icon theme like `adwaita-icon-theme` along with `hicolor-icon-theme` to your machine.

**Comment by pinage404** [comment]
It works if i start it from KDE menu (or Krunner) :tada: 

But if i run it with Konsole, it still does not have icons :confused: 

```
eolie
**GLib-GIO-Message: 21:59:09.242: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[INFO] 2019-09-15 21:59:09 PyFxA missing: pip3 install --user pyfxa
[INFO] 2019-09-15 21:59:09 Cyrpto missing: pip3 install --user pycrypto

(org.gnome.Eolie:8339): Gtk-WARNING **: 21:59:09.384: Could not find the icon 'go-previous-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
Could not initialize PyGObjectGLib-GIO-Message: 21:59:10.016: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[ERROR] 2019-09-15 21:59:10 DatabasePhishing::__save_rules():Expecting value: line 1 column 1 (char 0) -> b'You have exceeded the request rate limit for this method. Please see the response headers for usage stats. For more information about rate limiting on Phishtank, please see our developer site: http://www.phishtank.com/developer_info.php'**
```


Another bug (i don't know if i should open another issue), the parameters are lost at each new session :confused:

**Comment by worldofpeace** [comment]
> It works if i start it from KDE menu (or Krunner) tada
> But if i run it with Konsole, it still does not have icons confused

I believe there's something wrong with the child environment konsole produces
* #67691

> Another bug (i don't know if i should open another issue), the parameters are lost at each new session confused

Is that an issue in Eolie? If so, it's kinda out of date. Perhaps we should update it.

**Comment by pinage404** [comment]
i tried with Xterm and QtTerm, and i don't have icons issue

---

I don't know if it's a bug with Eolie that is solved with new version, i just tried this browser for the first time today

It could be a good idea to upgrade it (i don't know how to do it)

---

For the parameters issue, i can see this in the console output when i start Eolie

Something related to `memory` with the message

> Your settings will not be saved or shared with other applications.

```
GLib-GIO-Message: 22:25:48.261: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Could not initialize PyGObjectGLib-GIO-Message: 22:25:48.980: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

An error
```
[ERROR] 2019-09-15 22:25:49 DatabasePhishing::__save_rules():Expecting value: line 1 column 1 (char 0) -> b'You have exceeded the request rate limit for this method. Please see the response headers for usage stats. For more information about rate limiting on Phishtank, please see our developer site: http://www.phishtank.com/developer_info.php'
```

When i quit Eolie, i have this error
```
[ERROR] 2019-09-15 22:27:33 Application::__on_forms_filled(): g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Eolie.Proxy.Page1" does not exist (3)
```

**Comment by pinage404** [comment]
@worldofpeace do you have the same errors when you run eolie like this ?

```
nix-shell --packages eolie --command eolie
```

**Comment by worldofpeace** [comment]
I've updated eolie https://github.com/NixOS/nixpkgs/commit/4a7964614f146aa2de0ebfeecb66714e0744297c. Perhaps it fixed some issue you were having.

**Comment by worldofpeace** [comment]
Actually you could test with 
```
nix run -f https://github.com/NixOS/nixpkgs/archive/release-19.09.tar.gz eolie -c eolie
```

**Comment by pinage404** [comment]
It works ! thanks =)
