### ISSUE TITLE
cryptokit shared object file isn't in $CAML_LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by endorphin** [NixOS/nixpkgs#68874]
Ocaml programs depending on cryptokit crash at runtime, because the linker can't find the shared object file (ie it's not in `$CAML_LD_LIBRARY_PATH`).

**To Reproduce**
1. `nix-shell -p ocamlPackages.findlib ocamlPackages.ocaml ocamlPackages.cryptokit`
2. compile and run an ocaml project that depends on cryptokit (with `ocamlfind`)

**Additional context**
I tried refactoring the package to use `buildOcaml`, but it didn't fix the issue.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.44, NixOS, 19.03.172657.cdec6217d98 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(endorphin): `""`
 - channels(root): `"nixos-19.03.173251.56d94c8c69f, unstable-19.09pre187222.002b853782e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ocamlPackages.cryptokit
```

@ericbmerritt

**Comment by vbgl** [comment]
@endorphin Could you please test #68925? Thanks.

**Comment by endorphin** [comment]
Yep, fixes it. Thanks
