### ISSUE TITLE
GHC 8.8.1 haskell package set refers to undefined variables

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#68879]
**Describe the bug**

The Haskell package set for GHC 8.8.1 refers to things in the configuration which don't exist.

**To Reproduce**

```
$ nix-shell -p '(import <unstable> {}).haskell.packages.ghc881.ghcWithPackages (hs: [ hs.comonad ])'
error: attribute 'cabal-doctest_1_0_7' missing
```

**Expected behavior**

For the example above, a shell is entered where `comonad` is usable.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.72, NixOS, 19.03.173481.8a30e242181 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173506.2dfae8e22fd, nixos-hardware, unstable-20.03pre193309.c4196cca9ac"`
 - channels(ollie): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ocharles** [comment]
@vaibhavsagar looks like you added this change in https://github.com/NixOS/nixpkgs/commit/5e91bfa80acea3dabca7034f8a517044965b6270 - is there anything missing from that commit?

**Comment by vaibhavsagar** [comment]
Hmm, maybe the package set has been updated since I made that change so that `cabal-doctest_1_0_7` should now be `cabal-doctest` instead?

**Comment by cdepillabout** [comment]
I think the correct solution here is just to remove the following line:

https://github.com/NixOS/nixpkgs/blob/054f01ee1ba7ea86f8442b7dcc9d99b8aece5427/pkgs/development/haskell-modules/configuration-ghc-8.8.x.nix#L77

**Comment by luc-tielen** [comment]
I ran into the same problem and tried fixing it: https://github.com/NixOS/nixpkgs/pull/68935
This probably needs some cleaning up, but it can build ghc881.

**Comment by luc-tielen** [comment]
@ocharles this should be fixed now on haskell-updates branch.

**Comment by cdepillabout** [comment]
This was originally about ghc881, but we're now up to ghc883, and it is used in the main haskell package set, so I imagine this is no longer a problem.
