### ISSUE TITLE
GnuCash cannot connect to German banks since 2019-09-14

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#68880]
**Describe the bug**
PSD2 got active in Germany on 2019-09-14. Since then all banking software has to identify itself to the banking servers with a registration number. Without this the server of German banks reject the login.

To fix this, updates of the following software are required:
* gwenhywfar
* aqbanking at least version 5.8.1
* GnuCash at least version 3.7

See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934905 and https://wiki.gnucash.org/wiki/Release_Schedule

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.13, NixOS, 19.09beta181.64e38f246ae (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta181.64e38f246ae, unstable-19.09pre192418.e19054ab3cd"`
 - channels(matthias): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute:
- gwenhywfar
- aqbanking
- gnucash
```

**Comment by thorstenweber83** [comment]
i'm working on updating aqbanking (and it's dependency gwenhywfar) for use with kmymoney: https://github.com/NixOS/nixpkgs/pull/71304

GnuCash seems to be at 3.7 already.

**Comment by mawis** [comment]
With GnuCash in 20.03beta the problem still exists:

```
HBCI: 9050 - Die Nachricht enthält Fehler. (M)
HBCI: 9800 - Dialog abgebrochen (M)
HBCI: 3079 - Bitte wenden Sie sich an den Hersteller des Banking-Programms. (S)
HBCI: 9078 - Dialog abgebrochen - Banking-Programm ist nicht registriert. (S)
HBCI: 9010 - Der Auftrag wurde nicht ausgeführt. (S)
```
