### ISSUE TITLE
[xmonad] Update to latest xmonad

### ISSUE THREAD

**Issue by ardumont** [NixOS/nixpkgs#6890]
Hello,

I'd like to (try and) update xmonad to the latest version.
In latest cabal, a 0.12 version has been released!

If you were interested by this, what would be the right path?

I'm confused by all the xmonad derivations we can find in nixpkgs.

Thanks for your pointers.

Cheers,

**Comment by joachifm** [comment]
The xmonad window manager module refers to xmonad-with-packages, which in turn refers to applications/window-manager/xmonad/wrapper.nix, which is parameterised over ghcWithPackages. As far as I can tell, xmonad uses ghcWithPackages from the NG branch, which means xmonad will get updated automatically when the NG package set is re-generated from Hackage. @peti will know the actual answer, I think.

**Comment by ardumont** [comment]
Well, this makes complete sense now.
Thanks a lot for clarifying.

So i believe there is nothing to do but wait then ;)

**Comment by peti** [comment]
Where do you see xmonad version 0.12? http://hackage.haskell.org/package/xmonad doesn't seem to have that.

**Comment by ardumont** [comment]
I ran a

```sh
cabal update
cabal list xmonad
```

And saw 0.12.

**Comment by joachifm** [comment]
There's xmonad-extras 0.12, could that be what you saw?

**Comment by ardumont** [comment]
After cross checking, I misread!

I must have read the xmonad-extras version.
And as I have read last week on the xmonad mailing list that they were discussing about a new release... I must have been too excited! 

@joachifm @peti Sorry for the noise.

@joachifm Still I learn some interesting things. Thanks for that.

**Comment by ardumont** [comment]
> There's xmonad-extras 0.12, could that be what you saw?

Yes, that must be it

**Comment by ardumont** [comment]
Here is the thread about it https://mail.haskell.org/pipermail/xmonad/2015-March/014593.html.
But indeed, nothing was released yet.
