### ISSUE TITLE
Duplicate package for Apache Kafka

### ISSUE THREAD

**Issue by ragnard** [NixOS/nixpkgs#6892]
Hi,

While updating the version for the Apache Kafka package that I maintain, I noticed a duplicate of this package was added recently.

apache-kafka (original):
https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/apache-kafka/default.nix
(also used by the nixos service: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/apache-kafka.nix)

kafka (duplicate):
https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/kafka/default.nix

The latter was added in this PR:
https://github.com/NixOS/nixpkgs/pull/6121

I'm not sure what the policy for this is but having duplicate packages seem confusing.

**Comment by iElectric** [comment]
Actually it's in `pkgs/servers/apache-kafka/default.nix` and `pkgs/servers/kafka/default.nix`.

**Comment by ragnard** [comment]
@iElectric Yeah, original issue had incorrect link, have updated since.

**Comment by lethalman** [comment]
Reverting servers/kafka.
