### ISSUE TITLE
Package Request: ibus-libthai

### ISSUE THREAD

**Issue by foxmean** [NixOS/nixpkgs#68975]
**Project description**
IBus-LibThai is a Thai input method engine for IBus, based on the LibThai
library.

Currently, it provides 3 keyboard layouts internally:
  - Ketmanee
  - Pattachote
  - TIS-820.2538
(Thai XKB symbols are also supported.)

The input method also filters out invalid input sequences with 3 levels of
strictness:
  - Passthrough (no check)
  - Basic Check
  - Srict Check

For applications that support surrounding text retrieval/deletion,
it can also correct the invalid input sequences.

**Metadata**

* homepage URL: https://linux.thai.net/projects/ibus-libthai
* source URL: 
Git: https://github.com/tlwg/ibus-libthai
FTP: ftp://linux.thai.net/pub/thailinux/software/libthai
* license: GNU General Public License v2.0
* platforms: GNU/Linux

**Comment by SuperSandro2000** [comment]
I am currently packaging libthai. Going to add this one to that list.

**Comment by onny** [comment]
Looks like this is packaged and therefore solved :)
