### ISSUE TITLE
after upgrading to XFCE 4.14, themes no longer have effect

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#68977]
```
services.xserver.desktopManager.xfce4-14.enable = true;
```

Here you can see a light theme chosen:
![Screenshot_2019-09-17_14-01-16](https://user-images.githubusercontent.com/106511/65067201-f5270980-d953-11e9-9522-158471eafa15.png)

Next I choose a dark theme, and the only thing that changes is the CPU usage plugin. The main windows, panels, and buttons are not affected:
![Screenshot_2019-09-17_14-01-09](https://user-images.githubusercontent.com/106511/65067202-f5270980-d953-11e9-8565-1f5284f4ebf1.png)

With XFCE 4.12, all the UI becomes dark with a dark theme chosen.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.13, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @worldofpeace

**Comment by worldofpeace** [comment]
Have you tried logging out and back in @andrewrk?

**Comment by andrewrk** [comment]
I did a hardware reboot after `nixos-rebuild switch`. Are you suggesting to log out and back in after selecting a different theme in the appearance user interface? I will try that, but I will note that was not required in 4.12.

**Comment by worldofpeace** [comment]
So I tried it in a VM and I guess I can't switch between any of the `Xfce-$varient` themes on demand.
But switching between the Adwaita and Adwaita-dark themes worked.

**Comment by andrewrk** [comment]
How did you get Adwaita and Adwaita-dark themes to show up in the list? All I have are `Xfce-$variant` themes in the list.

**Comment by worldofpeace** [comment]
@andrewrk After inspecting the output of `/run/current-system/sw/share/themes/Xfce-dusk/` it's a gtk 2 theme. And most of Xfce is ported to gtk3. So I can probably switch to the Adwaita themes because they're for gtk3.

> How did you get Adwaita and Adwaita-dark themes to show up in the list? All I have are Xfce-$variant themes in the list.

I launched the desktop item for Appearance settings in the default menu.

![Screenshot from 2019-09-17 15 41 13](https://user-images.githubusercontent.com/28888242/65073840-a1bbb800-d961-11e9-9ba2-7dc71c5f5212.png)

It appears to be sorted at the top of the list.

**Comment by andrewrk** [comment]
![Screenshot_2019-09-17_15-46-41](https://user-images.githubusercontent.com/106511/65074212-5ce45100-d962-11e9-8fd7-ba187be423ce.png)

The only xfce related settings in my conf are:

```
  services.xserver.desktopManager.xfce4-14.enable = true;
...
  environment.systemPackages = with pkgs; [
...
    xfce4-14.thunar-volman
    xfce4-14.xfce4-cpufreq-plugin
    xfce.xfce4-cpugraph-plugin
    xfce4-14.xfce4-power-manager
    xfce4-14.xfce4-taskmanager
...
```

I also tried adding `xfce4-14.xfwm4-themes`; no effect.

**Comment by andrewrk** [comment]
It looks like this is due to these Xfce themes being gtk2 based. A workaround is to install `gnome-themes-standard`. This makes Adwaita themes available, which are gtk3 based, and therefore work with xfce's appearance GUI.

**Comment by worldofpeace** [comment]
Note that most of the gtk3 themes in nixpkgs support Xfce now.

**Comment by andrewrk** [comment]
thanks @worldofpeace :heart: :v:
