### ISSUE TITLE
Difficulties installing kdeApps_latest or kdeApps_stable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#6899]
I'm following an [howto](https://nixos.org/wiki/KDE#How_to_install_KDE_5) for installing KDE5.
I'm able to install 4 or 5, but I seem to be unable to install the applications.

```
  # Enable the KDE Desktop Environment.
  services.xserver.displayManager.kdm.enable = true;
  services.xserver.desktopManager.kde5.enable = true;

  environment.systemPackages = [
    pkgs.firefox
    pkgs.chromium
    pkgs.mendeley
    pkgs.spotify
    pkgs.vlc
    pkgs.openttd
    pkgs.kdeApps_stable
  ];

```
This fails with
```
building Nix...
building the system configuration...
error: cannot coerce a set to a string, at "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix":103:79
(use ‘--show-trace’ to show detailed location information)
```
The howto states that one should append
```
filter isDerivation (builtins.attrValues kdeApps_stable);
```
to environment.systemPackages

I'm unfamiliar with the Nix language but I would expect the filter to return a list or iterable, however
```
  environment.systemPackages = [
    pkgs.firefox
    pkgs.chromium
    pkgs.mendeley
    pkgs.spotify
    pkgs.vlc
    pkgs.openttd
  ];

  environment.systemPackages ++ filter isDerivation (builtins.attrValues kdeApps_stable);
``` 
fails with
```
building Nix...
error: syntax error, unexpected CONCAT, expecting '.' or '=', at "/etc/nixos/configuration.nix":85:30
(use ‘--show-trace’ to show detailed location information)
error: syntax error, unexpected CONCAT, expecting '.' or '=', at "/etc/nixos/configuration.nix":85:30
(use ‘--show-trace’ to show detailed location information)
building the system configuration...
error: syntax error, unexpected CONCAT, expecting '.' or '=', at "/etc/nixos/configuration.nix":85:30
(use ‘--show-trace’ to show detailed location information)
```

What am I doing wrong here? :-)

**Comment by ttuegel** [comment]
The correct syntax is
```
environment.systemPackages = [
    pkgs.firefox
    pkgs.chromium
    pkgs.mendeley
    pkgs.spotify
    pkgs.vlc
    pkgs.openttd
  ] ++ filter isDerivation (builtins.attrValues kdeApps_stable);
```
Nix is a functional language, so you cannot modify values after they are set. Instead, this concatenates the two lists of packages, your own and the list in `kdeApps_stable`, and then sets `environment.systemPackages` to the concatenation. By the way, we can abbreviate this somewhat using `with`:
```
environment.systemPackages = with pkgs; [
    firefox
    chromium
    mendeley
    spotify
    vlc
    openttd
  ] ++ filter isDerivation (builtins.attrValues kdeApps_stable);
```

**Comment by ttuegel** [comment]
I forgot to add: this will install *all* of the packages in `kdeApps_stable`! This is probably not what you want. You can pick and choose which apps to install by adding them to your list explicitly, e.g.
```
environment.systemPackages = with pkgs; [
    firefox
    chromium
    mendeley
    spotify
    vlc
    openttd
    kdeApps_stable.okular
  ];
```

**Comment by FRidh** [comment]
Thank you. I can install individual packages, however, I wasn't able to get it to work with `filter`
I get 
```
error: undefined variable ‘filter’ 
```
In the Nix manual I saw that the function can be accessed as builtins.filter . So I tried that instead, but now got a 
```
error: undefined variable ‘isDerivation’
```
I couldn't find anything further about isDerivation in the manual. It doesn't seem to be part of builtins.

**Comment by ttuegel** [comment]
Sorry, you're right, that should be `builtins.filter` and `stdenv.lib.isDerivation`.

**Comment by kapralVV** [comment]
Hi, 
I cannot install all kde5 application. Seem the instruction does not work again 
I configured :
 environment.systemPackages = [ some packages ] ++ builtins.filter stdenv.lib.isDerivation (builtins.attrValues kdeApps_stable);

got an error: 
error: undefined variable ‘stdenv’

Could you please help me.

**Comment by johnramsden** [comment]
I'm wondering the same as @kapralVV

**Comment by ttuegel** [comment]
The NixOS Wiki is defunct and should not be used as a source of any information.

KDE applications are available individually by name. Installing all applications is not a supported configuration.

**Comment by johnramsden** [comment]
I see @ttuegel . That's actually what I have already done. I wonder if an option that lets you install all of them should be looked into?

**Comment by FRidh** [comment]
@johnramsden the applications are actually available as a set, `kdeApplications`. But, as @ttuegel mentioned it is not supported so who knows how long that set will remain available. Because this set currently exists you could append the values with `environment.systemPackages = [ ... ] ++ lib.attrsets pkgs.kdeApplications;`

**Comment by johnramsden** [comment]
@FRidh I get the following when I try that.

> error: attempt to call something which is not a function but a set

**Comment by sneak** [comment]
```
  config.environment.systemPackages = with pkgs; [
    ...
  ]
   ++ builtins.filter (p: lib.isDerivation p && !(p.meta.broken or false)) (builtins.attrValues kdeApplications)
   ++ builtins.filter (p: lib.isDerivation p && !(p.meta.broken or false)) (builtins.attrValues kdeFrameworks)
   ++ builtins.filter (p: lib.isDerivation p && !(p.meta.broken or false)) (builtins.attrValues plasma5);
```

This is what I've used presently.
