### ISSUE TITLE
GHC can no longer any link executables

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#69023]
Our `ghc` can no longer link executables. For example:

~~~
$ nix-env -iA ghc
$ cat test.hs
import System.IO

main :: IO ()
main = putStrLn "Hello, world."
$ ghc test.hs
Linking test ...
/nix/store/cl1i6bfqnx48ipakj4px7pb1babzs23j-binutils-2.31.1/bin/ld: cannot find -lelf
/nix/store/cl1i6bfqnx48ipakj4px7pb1babzs23j-binutils-2.31.1/bin/ld: cannot find -ldw
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)
~~~

This issue is present in current versions of `master`. Compiling and linking works fine with an older revision, say 1a1a7ed26652545dc6a2e2bd02f7812e1b37d196.

It looks like this might be related to some change in binutils, maybe?

**Comment by matthewbauer** [comment]
This is probably from https://github.com/NixOS/nixpkgs/commit/f4316473d94e0e5eff2736bd24dc802e09752771

**Comment by peti** [comment]
Yes, it is. `git bisect` came to the same conclusion.

**Comment by matthewbauer** [comment]
This probably is GHC bug though. Things like gmp and libiconv get their paths hardcoded so this isn't a problem. I would expect the same treatment for elfutils.

**Comment by domenkozar** [comment]
I guess now I know why there's a patch in @nh2 branch.

**Comment by domenkozar** [comment]
I'll reopen the PR fixing the linking issues.

**Comment by domenkozar** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/69552 while we wait on upstream fix.

**Comment by nh2** [comment]
> I guess now I know why there's a patch in @nh2 branch.

@domenkozar Which one, `./ghc-Require-libdw-for-enable-dwarf-unwind-fixed-comma.patch` from https://github.com/NixOS/nixpkgs/pull/52255/files#diff-c90b207a56851dba68c66cf16a911e8eR167?

**Comment by domenkozar** [comment]
Yes, although it doesn't help. See https://gitlab.haskell.org/ghc/ghc/issues/17255

**Comment by nh2** [comment]
Yes, it would have surprised me a bit if it helped against that symptom -- my patch fixes that DWARF-enabling is skipped completely.

**Comment by domenkozar** [comment]
I'm surprised this worked for you back then and now there are linking errors.
