### ISSUE TITLE
Grsecurity does not work in virtualbox

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#6905]
So, i wanted to test grsecurity in virtualbox, but it does not seem to boot. This is my config

```
    security.grsecurity = {
      enable = true;
      stable = true;
      config = {
        system = "server";
        hardwareVirtualisation = false;
        virtualisationSoftware = "virtualbox";
      };
    };
```

Kernel crashes at boot with some error indicating that execution of init is not possible for some reason, but i did not investigate this problem future.

@thoughtpolice do you have any idea what could be the problem?

**Comment by thoughtpolice** [comment]
Hrm, last time I tried this in vbox the problem was `GRKERNSEC_RANDSTACK`, which messed things up. I'll look into this one, thanks.

**Comment by zimbatm** [comment]
@thoughtpolice ping ?

**Comment by joachifm** [comment]
Virtualbox is officially unsupported currently, so this is not expected to work. To use virtualbox, override the stock NixOS grsec kernel with a suitable kernel config, as in
```nix
linux_grsec_nixos.override {
  extraConfig = ''
    # ...
  '';
}
```
