### ISSUE TITLE
Emoji Fonts Crash st

### ISSUE THREAD

**Issue by gyroninja** [NixOS/nixpkgs#69073]
**Describe the bug**
Due to #67667  being merged st now tries to load `/nix/store/hash-noto-fonts-emoji-2018-08-10-unicode11/share/fonts/noto/NotoColorEmoji.ttf` and then "crashes" with
```X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  15
  Current serial number in output stream:  29
```

A related upstream issue is https://gitlab.freedesktop.org/xorg/lib/libxft/issues/6

Preferably this can be fixed by removing emojis from default fonts.

**To Reproduce**
Paste  🤣 into st and it will happen.

**Expected behavior**
St should remain open and possibly just print a missing symbol symbol.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd"`
 - channels(redacted): `"home-manager, redacted"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Emoji fonts aren't going to be removed from the defaults because one application crashes trying to load them.

What you can instead do is just disable including default fonts
```
fonts.enableDefaultFonts = false;
```

and probably add the following fonts because they won't be included anymore
```
fonts.fonts = [ 
   pkgs.xorg.fontbhlucidatypewriter100dpi
   pkgs.xorg.fontbhlucidatypewriter75dpi
   pkgs.dejavu_fonts
   pkgs.freefont_ttf
   pkgs.gyre-fonts # TrueType substitutes for standard PostScript fonts
   pkgs.liberation_ttf
   pkgs.xorg.fontbh100dpi
   pkgs.xorg.fontmiscmisc
   pkgs.xorg.fontcursormisc
   pkgs.unifont
];
```

**Comment by gyroninja** [comment]
>because one application crashes trying to load them.

Perhaps, this issue was filed poorly. It is an issue with xorg.libXft which several packages in NixOS use. Since enableDefaultFonts is by default off I guess it is my fault that it's pulling it in, but it is still annoying that this change cause a regression for me even though I changed nothing on my end in my config.

**Comment by worldofpeace** [comment]
I guess we could use a font with fallbacks, though I'm not sure I can produce a change like that in a timely fashion. And `enableDefaultFonts` is enabled when `xserver` is enabled.

**Comment by jtojnar** [comment]
It is unfortunate, but choosing between triggering a bug in few programs and eschewing a feature in most of others, I think we should choose the former.

We should mention the issue in the release notes.

Possible hacks:
* disabling `enableDefaultFonts`
* installing font with fallback glyphs (e.g. `twemoji-color-font`) and setting it as default. Though, I am not actually sure the font will be picked up when it does not contain colour glyphs in supported format. And unfortunately, we do not have any supported colour font with fallback glyphs.
* Modifying the fontconfig configuration not to use emoji points in libXft (not sure if there is a property allowing to detect it.)

**Comment by gyroninja** [comment]
I am going to close this since this is an upstream bug which is not present by default.

**Comment by jtojnar** [comment]
Confirmed that installing fallback emoji font that contains black-and-white glyphs will fix the crash, while color emoji still being used in applications that support them.

```
{
  fonts = {
    fonts = with pkgs; [
      twemoji-color-font
    ];
  };
  fonts.enableDefaultFonts = true;
}
```

**Comment by jtojnar** [comment]
But `noto-fonts-emoji` should already contain black and white glyph font `Noto Emoji`, so I wonder why is not it picked up as a fallback font.

**Comment by gyroninja** [comment]
@jtojnar The problem is that the black and white version is not a true fallback font. The color version of the font supports more emoji characters.

As simple proof of why the emoji from the OP fails.

```
hb-shape NotoEmoji-Regular.ttf $(echo -e "\U1F923")
[.notdef=0+2600]
```

```
hb-shape NotoColorEmoji.ttf $(echo -e "\U1F923")
[gid1076=0+2550]
```

Obviously, since the color version is the only font that offers the character it will be the one that is used. Ideally we should have parity between the black and white and color fonts (or at least the color ones being a subset of the black and white ones). If this was the case then this issue would not pop up.  I'm not that knowledgeable about the about the current emoji fonts out there as I do not personally have a need for them so I'm not sure if there exists a font where this is true. There's always the option of manually chopping off the extra color fonts that don't have a fallback, but that is extra work. Or the reverse where you put dummy symbols in the black and white font so that it at least falls back to something and does not crash an application using libXft.

**Comment by gyroninja** [comment]
https://github.com/googlefonts/noto-emoji/blob/master/README.md
>B/W emoji font
>The black-and-white emoji font is not under active development. Its repertoire of emoji is now several years old, and the design does not reflect the current color emoji design. Currently we have no plans to update this font.
Perhaps NixOS should use an emoji font which actually supports a black and white version on emoji characters.

**Comment by jtojnar** [comment]
https://openmoji.org/ seems to support wide range of emoji so maybe we could add it in addition to Noto Emoji. Unfortunately, we cannot use it alone because it only provides SVGinOT variant of colour font.

**Comment by jtojnar** [comment]
@worldofpeace do we want to apply https://gitlab.freedesktop.org/xorg/lib/libxft/merge_requests/1 for 20.03?

**Comment by worldofpeace** [comment]
> @worldofpeace do we want to apply https://gitlab.freedesktop.org/xorg/lib/libxft/merge_requests/1 for 20.03?

Sounds good to me :+1: I can PR since I have the moment.

**Comment by wmertens** [comment]
Not sure if tangential: DejaVu seems to contain mono emoji, and they cause Chrome to render mono emoji. When I remove dejavu from the font styling on pages showing mono emoji, they work.
