### ISSUE TITLE
Unstable channel hasn't updated for 10+ days

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#69079]
It's been a while since we've had an update of the `nixos-unstable` channel. According to https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents, there have been plenty of problems with Hydra, but the failure of [nixos.tests.containers-imperative.x86_64-linux](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.containers-imperative.x86_64-linux) seems legit. Does anyone know why that test is broken?

**Comment by alexarice** [comment]
I have bisected this and very confusingly it seems to be caused by 456c42c3e8787d83d577526af90263de9b3d512d

If I revert this commit on master the test passes
