### ISSUE TITLE
libressl: no static archives generated

### ISSUE THREAD

**Issue by nmattia** [NixOS/nixpkgs#69104]
**Describe the bug**

`libressl` builds do not produce static libraries (`.a` files).

**Additional context**

This is due to [`"-DBUILD_SHARED_LIBS=ON"`](https://github.com/NixOS/nixpkgs/blob/6ff8b675e0c2730e54f95d232a93e5b01813f389/pkgs/development/libraries/libressl/default.nix#L18). Ideally we should have both `.a` and `.so/dylib`.

A workaround:

``` nix

  # These are used by various targets
libressl.overrideAttrs (oldAttrs: {
      cmakeFlags =
        self.lib.filter (f: f != "-DBUILD_SHARED_LIBS=ON") oldAttrs.cmakeFlags;
    }
  )
```

**Comment by matthewbauer** [comment]
The policy of Nixpkgs is generally to only build dynamic libraries of everything. This avoids getting all of the .a files in our runtime closures. In the past, we have gotten around this with custom "static" outputs, but this has its own issues, where things like pkgconfig won't find the right library. To get around those two issues, we now have ```pkgsStatic``` that is a fully static overlay. It can be used for both static libraries and executables. With (https://github.com/NixOS/nixpkgs/pull/69107), you can do:

```
nix build nixpkgs.pkgsStatic.libressl
```

**Comment by FliegendeWurst** [comment]
This was fixed by the linked PR
