### ISSUE TITLE
`gitignoreSource` reproducibility issue 

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#69138]
### Issue

The output path name produced by `gitignoreSource` utility depends on the name of the imported directory. So, if the name of the directory to be imported is not stable, the output path will change and all reverse dependencies also.

### Example

This is especially true when Hydra fetches a repository:
- on my machine, the repository directory is named `my-repository`. The produced output path lookgs like `/nix/store//nix/store/nd60zwhsq5hwqjywp1m1jjhiny2dy9sv-my-repository`.
- when this repository is fetched by Hydra (as jobset input), the name of the repository will be something such as `/nix/store/cqpfbg9q7hhv078p8sdch5sb2wlwnm74-sysy2va0fr6qgikdgx9xsxa1af1dp5np-source`

Note the content is however identical.

### Proposed solution

`builtins.path` as a `name` attribute to explicitly set the name of the output path. It would be nice to have such kind of attribute for the `gitignoreSource` function as well. Maybe we just need to replace `builtins.filterSource` with `builtins.path` [here](https://github.com/NixOS/nixpkgs/blob/d8a7a01fecb4dd05dead58f70ea4bfd0b8336459/pkgs/build-support/nix-gitignore/default.nix#L159).

cc @siers

**Comment by siers** [comment]
Isn't this PR about the same issue? https://github.com/siers/nix-gitignore/pull/26

**Comment by FRidh** [comment]
Related https://github.com/NixOS/nixpkgs/pull/67996

**Comment by FRidh** [comment]
Closing because this is indeed siers/nix-gitignore#26
