### ISSUE TITLE
In haskell-ng, support multiple revisions in a more robust way

### ISSUE THREAD

**Issue by kosmikus** [NixOS/nixpkgs#6914]
See my comment on https://github.com/NixOS/nixpkgs/commit/c7d3f6021707ce18690a0f59807c02cae38b8338 (which equivalently applies to `generic-builder.nix`, I think).

**Comment by peti** [comment]
Thank you for the bug report! Fixed in https://github.com/peti/nixpkgs/commit/5a27fbaa1c85cb8a687c36a56f0d21d403a17292. Test builds are running ... I'll merge to `master` once I'm sure everything works as expected.
