### ISSUE TITLE
Why is our default PostgreSQL version 9.6? Shouldn't it be version 11?

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#69141]
I am by no means an expert on database systems, so this may be a stupid question ... but I can't help wondering why `postgresql` does not refer to PostgreSQL version 11 on current versions of `nixos-unstable`? Is there a reason we haven't updated yet?

**Comment by aanderse** [comment]
Maybe @danbst or @aszlig can answer this... :thinking:

**Comment by aszlig** [comment]
@peti: Good question. In my case I'm not using PostgreSQL 9 by myself and switched to 10 and 11 a long time ago, but I also wasn't aware of this because I'm not using the module from NixOS in my deployments.

**Comment by danbst** [comment]
Made a PR for that... If you think it's too rush to include it to 19.09, then I can delay it to 20.03

As for `pkgs.postgresql`, it really shouldn't be used. It should be split to `server`, `client` and `libpq`, and `client`/`libpq` may be continuosly updated, but `server` should be used only with explicit version.

But this server/client split is not straightforward, so it was not yet done.
