### ISSUE TITLE
Package pythonPackages.elpy: please reistate

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#69159]
The packages `pythonPackages.elpy` was dropped without any apparent explanation in commit 4bd7e963b349d4f98e8047509e3fd9b6d4b009cf . As a user of this package, can I ask it to be reinstated?

cc @costrouc,  @jonringer, @FRidh

**Comment by jonringer** [comment]
From my understanding, it was abandoned upstream and replaced with stub setup.py to prevent installations from failing. Does the package actually give you any real value?

It was even removed from pypi at one point.

see jorgenschaefer/elpy#1583

**Comment by azazel75** [comment]
Your're right and I'm sorry for the noise but why couldn't you add your very useful comment to the commit?

**Comment by jonringer** [comment]
You're right, I should have written the intent of removing the pack into the commit message. Next time I will :)
