### ISSUE TITLE
Unable to adjust laptop monitor brightness with plasma 5.16

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#69150]
**Describe the bug**
After the move to plasma 5.16, I am no longer able to adjust the laptop monitor brightness which was fine before on plasma 5.15.

Neither using the shortcut key (Fn-F11/12 on a Lenovo Yoga 2 Pro), nor using the "Battery and Brightness" icon in the system tray.

There used to be a slider under "Battery and Brightness" which could be used in addition to the hotkeys but it is simply missing.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.13, NixOS, 19.09.git.3b071913413M (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `""`
 - channels(peter): `"home-manager"`
 - nixpkgs: `/home/peter/src/active/nixpkgs_unstable`

Cc: @ttuegel @dtzWill @bkchr

**Comment by peterhoeg** [comment]
I'll see what I can figure out over the weekend - I just wanted to get the issue up here in case others have the same problem.

**Comment by Anton-Latukha** [comment]
Comment is for likes: "Everything works on my laptop":

**Comment by Anton-Latukha** [comment]
What video drivers/setup you have?

**Comment by mudrii** [comment]
do you have udev rule in place?
I am using i3 and what worked for me is 

```sh
  #  environment.systemPackages = with pkgs; [ xorg.xbacklight ];
    services.udev = {
        extraRules = ''
          ACTION=="add", SUBSYSTEM=="backlight", RUN+="${pkgs.coreutils}/bin/chgrp video %S%p/brightness", RUN+="${pkgs.coreutils}  /bin/chmod g+w %S%p/brightness"
        '';
    };   
```

**Comment by peterhoeg** [comment]
> What video drivers/setup you have?

It's onboard intel graphics but that shouldn't change anything - it used to work with plasma 5.15

> do you have udev rule in place?

This should not be necessary. KDE should handle it.

**Comment by bkchr** [comment]
@peterhoeg thanks for the issue. I just realized that it also does not works for me. Did you had any luck on finding a solution?

**Comment by 1000101** [comment]
Same here. Dell Latitude 5490, Intel UHD Graphics 620. It works with GNOME but not with KDE (5.16). It previously worked fine, stopped working a few days ago when I switched from 19.03 to nixos-unstable. All people with this laptop experience the same issue.

**Comment by Anton-Latukha** [comment]
Is brightness sliders present in "Settings -> Power Management -> Energy saving"?

**Comment by bkchr** [comment]
No, only for keyboard backlight.

**Comment by 1000101** [comment]
> Is brightness sliders present in "Settings -> Power Management -> Energy saving"?

![bat](https://user-images.githubusercontent.com/791309/65419976-34e06c00-de00-11e9-91ff-d2954d90b019.png)

![bat2](https://user-images.githubusercontent.com/791309/65420014-5b060c00-de00-11e9-8629-4eecffcf9860.png)

**Comment by Anton-Latukha** [comment]
I see there is external monitor seems connected. At least - there is definitely setup for it. Maybe it is related to that, it should be relayted to some kind of a hardware state.

I used to debug X11 Desktop issues, by looking into `jounalctl -b`, `jounalctl -f` logs, maybe filtering by syslog message severity levels `-p 0...7`, filter by `-g X`, `-g xsession` `-g powerdevil`.

...

Well. I found a cause. It is an upstream issue:
https://bugs.kde.org/show_bug.cgi?id=398890

Somebody - mark it `upstream` and discussion should happen in that old bug trekker.

**Comment by peterhoeg** [comment]
This is the relevant upstream issue: https://bugs.kde.org/show_bug.cgi?id=410044

**Comment by Mounium** [comment]
I experience the same issue on a Thinkpad T480.

**Comment by peterhoeg** [comment]
Doesn't seem to be hardware related.

**Comment by 1000101** [comment]
Has there been any progress? It seems like nobody from the kde org ever replied to that report.

**Comment by Anton-Latukha** [comment]
They opened GitLab recently - you probably can gather all relevant date, reopen and do clean issue in relevant project on https://invent.kde.org, and it would be the first bug report there.

**Comment by Anton-Latukha** [comment]
Also:
```
hardware.brightnessctl.enable
---
Enable brightnessctl in userspace. This will allow brightness control from users in the video group.


services.illum.enable
--- 
Enable illum, a daemon for controlling screen brightness with brightness buttons.

hardware.acpilight.enable
---
Enable acpilight. This will allow brightness control via xbacklight from users in the video group
```

I just use:
```
services.redshift.brightness.day/night
```
myself.

BTW, are your users indeed in `video` group?

**Comment by peterhoeg** [comment]
The issue isn't that it is not possible to adjust brightness as normal users. The issues is that plasma 5.15 used to be able to do it out of the box whereas with 5.16 that is no longer the case.

**Comment by Anton-Latukha** [comment]
They unifying the UI right now.

Thee issue is that on some system it shows the settings (I and many users have everything working).

If internal system was changed, and there new system requires or check some permissions, before enabling/displaying the feature. Ir is or setup, or the rights management issue. Why the belonging to `user` gounp can not be the cause for example? I had a lot of such things before.

**Comment by Anton-Latukha** [comment]
Like, _mudrii_ just above:
```
          ACTION=="add", SUBSYSTEM=="backlight", RUN+="${pkgs.coreutils}/bin/chgrp video %S%p/brightness", RUN+="${pkgs.coreutils}  /bin/chmod g+w %S%p/brightness"
```
I mean, that he has `chgrp video`.

**Comment by Anton-Latukha** [comment]
@bkchr That very can be a standard 30s timeout of waiting on some not working (or not reachable, like because of right) system to respond. Then timeout goes off, and it goes into `else` case. I am just guessing using probability here of course.

**Comment by bkchr** [comment]
For me it works again, but I don't know what changed :woman_shrugging:

**Comment by 1000101** [comment]
Same for me, it now works without the illum but I'm not sure when it changed.

**Comment by Anton-Latukha** [comment]
I observed recently that related bug reports in KDE bug tracker were closed, maybe that was a fix.

**Comment by peterhoeg** [comment]
My display brightness slider is back now on latest unstable but it has no effect when I slide it around. Does it actually work for you guys?

**Comment by 1000101** [comment]
Yes, it works just fine (both hw keys and sw slider).

**Comment by Mounium** [comment]
It works here again as well

**Comment by peterhoeg** [comment]
Turns out that the ```ideapad_laptop``` module created a 2nd brightness device in addition to ```intel_backlight```. Moving the slider made ```ideapad/brightness``` change which meant that the actual brightness didn't change. The fix:
```
boot.blacklistedKernelModules = [ "ideapad_laptop" ];
```

**Comment by Anton-Latukha** [comment]
This ideally should resolve into https://github.com/NixOS/nixos-hardware.
