### ISSUE TITLE
a2j_control fails because dbus is not in the python path

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#6916]
`a2j_control` is an executable of the a2jmidid project. The exact error message is

```
Traceback (most recent call last):
  File "/home/sven/.nix-profile/bin/a2j_control", line 11, in <module>
    import dbus
ImportError: No module named dbus
```

I suggest changing `stdenv.mkDerivation` to `buildPythonPackage` and add `pythonDBus` to the `pythonPath`. @cillianderoiste can you please comment on my suggestion?

Best,
Sven

**Comment by cillianderoiste** [comment]
@svenkeidel I don't think you can use buildPythonPackage for this one since it actually uses waf for building and installing (rather than the setup.py). How about just wrapping a2j_control with the relevant python modules?

**Comment by svenkeidel** [comment]
Whatever works.

**Comment by svenkeidel** [comment]
Have a look at the nix package for [jack](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/jackaudio/default.nix#L35), they use `wrapProgram`:

```
wrapProgram $out/bin/jack_control --set PYTHONPATH $PYTHONPATH
```

**Comment by cillianderoiste** [comment]
Exactly, can you test that out and open a PR?

**Comment by svenkeidel** [comment]
Thanks for the discussion, the PR is https://github.com/NixOS/nixpkgs/pull/6931,

Best,
Sven
