### ISSUE TITLE
avr-gcc can't find limits.h

### ISSUE THREAD

**Issue by matthuszagh** [NixOS/nixpkgs#69172]
**Describe the bug**
avr-gcc is unable to find and include the header `<limits.h>`. Based on my limited understanding, it seems that avr-gcc does not provide this header itself, and instead delegates to the main system installation of gcc to include this header

from (avr-gcc's limits.h line 192):
```
#ifdef _GCC_NEXT_LIMITS_H
#include_next <limits.h>		/* recurse down to the real one */
#endif
```

**To Reproduce**
Create shell.nix:
```
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs.pkgsCross; [
    avr.buildPackages.binutils
    avr.buildPackages.gcc
  ];
}
```
Create file.c:
```
#include <limits.h>
#include <stdio.h>

int main() { printf("%d\n", UINT_MAX); }
```
Enter nix shell with: `$ nix-shell shell.nix`

attempt compilation with: `$ avr-gcc file.c`

output:
```
In file included from /nix/store/sxdn938zndxp3jbj6qk29v4dp1z4v5l0-gcc-debug-8.3.0-avr-stage-final/lib/gcc/avr/8.3.0/include-fixed/syslimits.h:7,
                 from /nix/store/sxdn938zndxp3jbj6qk29v4dp1z4v5l0-gcc-debug-8.3.0-avr-stage-final/lib/gcc/avr/8.3.0/include-fixed/limits.h:34,
                 from file.c:1:
/nix/store/sxdn938zndxp3jbj6qk29v4dp1z4v5l0-gcc-debug-8.3.0-avr-stage-final/lib/gcc/avr/8.3.0/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
               ^~~~~~~~~~
compilation terminated.
```

**Comment by matthuszagh** [comment]
Note that it looks like we removed the test for the existence of limits.h based on [this comment](https://github.com/NixOS/nixpkgs/pull/48286#issuecomment-430380041). However, it sounds like maybe avr-gcc needs some way of finding limits.h?

**Comment by matthewbauer** [comment]
I suspect that gcc7 will work. I think we just need this set:

https://github.com/NixOS/nixpkgs/pull/48286/commits/412093994b9a4fe0fa7da99d1947effc85d9070b#diff-b1a3f1225fcb3cbbdfdfa5759b979f7dR198

**Comment by matthuszagh** [comment]
that does indeed work.
