### ISSUE TITLE
Cannot build pim-data-exporter

### ISSUE THREAD

**Issue by billksun** [NixOS/nixpkgs#69188]
**Describe the bug**
When upgrading `pim-data-exporter` to 19.08.1, the build fails.

**To Reproduce**
1. `nix-env -i pim-data-exporter`
2. Observe the build error:
```
CMake Error at CMakeLists.txt:82 (find_package):
  Could not find a package configuration file provided by "KF5CalendarCore"
  (requested version 5.12.1) with any of the following names:

    KF5CalendarCoreConfig.cmake
    kf5calendarcore-config.cmake

  Add the installation prefix of "KF5CalendarCore" to CMAKE_PREFIX_PATH or
  set "KF5CalendarCore_DIR" to a directory containing one of the above files.
  If "KF5CalendarCore" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/build/pim-data-exporter-19.08.1/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/75dcxsxdvcm3fnfdvpfq4gipm372immk-pim-data-exporter-19.08.1.drv' failed with exit code 1
```

**Expected behavior**
Installation of pim-data-exporter should be successful and without errors.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.16, NixOS, 20.03pre193781.d484f2b7fc0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre193781.d484f2b7fc0"`
 - channels(bill): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Works on NixOS 21.11
