### ISSUE TITLE
Package Request: powerline-hs

### ISSUE THREAD

**Issue by billksun** [NixOS/nixpkgs#69192]
**Project description**
A lightning fast reimplementation of the Powerline prompt generator in Haskell.

**Metadata**

* homepage URL: https://github.com/rdnetto/powerline-hs
* source URL: https://github.com/rdnetto/powerline-hs
* license: Apache 2.0. https://github.com/rdnetto/powerline-hs/blob/master/LICENSE
* platforms: linux

**Comment by cdepillabout** [comment]
@worldofpeace Could you add the `haskell` tag?

**Comment by cdepillabout** [comment]
@billksun Are you interested in trying to package this?  It will probably need to be packaged similarly to the other Haskell tools that don't come from Hackage.  So basically things in this directory: `pkgs/development/tools/haskell/`

If you're not interested in trying to package this, I (or someone else) could try to take a stab at it.

----------------------------------------------------------------------

However, it would be easier to package in nixpkgs if it was actually released to Hackage (and even better, stackage).  Would you be interested in trying to persuade the author to make a release to Hackage?

**Comment by teto** [comment]
some initative https://github.com/rdnetto/powerline-hs/issues/15. I've recently been using https://starship.rs/config/#command-duration

**Comment by billksun** [comment]
@teto, wow thanks for letting me know about `starship`! I've been using it for the past few days and I like it better than the `powerline` variants! Much cleaner and minimal design. I'll close this request, since I think `starship` fits my preference better.
