### ISSUE TITLE
xfce4-14 cannot be enabled alongside some other desktop environemnts

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#69208]
**Describe the bug**

I use to enable more than one window manager and/or desktop environment on my NixOS system, and the user is free to choose which one he desires at login time. One of those is xfce.

When xfce4-14 and gnome3 are both enabled, the following error is reported:
```
error: The unique option `networking.networkmanager.basePackages.crda' is defined multiple times, in:
 - /alt/nixpkgs-channels/nixos/modules/services/x11/desktop-managers/gnome3.nix
 - /alt/nixpkgs-channels/nixos/modules/services/x11/desktop-managers/xfce4-14.nix.
```

When xfce4-14 and lxqt are both enabled, the following error is reported:
```
error: The unique option `services.gvfs.package' is defined multiple times, in:
 - /alt/nixpkgs-channels/nixos/modules/services/x11/desktop-managers/lxqt.nix
 - /alt/nixpkgs-channels/nixos/modules/services/x11/desktop-managers/xfce4-14.nix.
```

When xfce4-14 and pantheon are both enabled, the following error is reported:
```
error: The unique option `networking.networkmanager.basePackages.crda' is defined multiple times, in:
 - /alt/nixpkgs-channels/nixos/modules/services/x11/desktop-managers/pantheon.nix
 - /alt/nixpkgs-channels/nixos/modules/services/x11/desktop-managers/xfce4-14.nix.
```

Can something be done to avoid fix this?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0, NixOS, 20.03pre193722.a7f002ac41d (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre193781.d484f2b7fc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.xfce4-14
```

**Comment by worldofpeace** [comment]
@romildo I noticed this also and it's indeed not correct. I'll see if I can think a way to change the options so they can be used together. I know the one for networkmanager is a bit of an ugly hack to use the gnome3 package set for networkmanager packages.

**Comment by worldofpeace** [comment]
For `services.gvfs.package` xfce uses a special build of gvfs without samba and lxqt just uses the toplevel one. So perhaps we can make `lxqt` setting have lower priority.

**Comment by worldofpeace** [comment]
@Infinisil Any ideas on how we can eliminate this option?
* https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/networkmanager.nix#L179

It only exists because there's [gnome3 variants](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/gnome3.nix#L215) of the following packages
```
networkmanager-openvpn 
networkmanager-vpnc
networkmanager-openconnect 
networkmanager-fortisslvpn
networkmanager-l2tp 
networkmanager-iodine
```

**Comment by worldofpeace** [comment]
This actually wasn't fixed completely.

**Comment by romildo** [comment]
It is not fixed completely yet.

**Comment by romildo** [comment]
Still an issue.
