### ISSUE TITLE
zoom-us can't start failed dependency

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#69235]
**Describe the bug**
Install zoom-us pkgs and can't start
Error during launch
```sh
zoom-us
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
fish: “zoom-us” terminated by signal SIGABRT (Abort)
```

**To Reproduce**
Install zoom-us

**Expected behavior**
Start the application

**Additional context**
Latest update of the NIxOS 19.09 and tried bot stable and unstable package with the same result.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```sh
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0, NixOS, 19.09beta304.b66fb91f170 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta304.b66fb91f170"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by worldofpeace** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/69173
