### ISSUE TITLE
Try zfsUnstable or set the NixOS option boot.zfs.enableUnstable.

### ISSUE THREAD

**Issue by rndd-AK** [NixOS/nixpkgs#69240]
**Describe the bug**
Tried to upgrade my nixos

**To Reproduce**
1. set boot.zfs.enableUnstable = true; in your config
2. run  sudo nixos-rebuild --upgrade switch

**Expected behavior**
An upgrade

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.16, NixOS, 19.03.173522.021d733ea3f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(rndd): `""`
 - channels(root): `"nixos-20.03pre193781.d484f2b7fc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
A this moment both stable and unstable attributes are the same version (0.8.1).  I don't know why, though.

**Comment by rndd-AK** [comment]
maybe i can give any additional info to solve this problem?

**Comment by vcunat** [comment]
To be clear, I don't see a problem.  Currently for our ZFS it holds that "unstable" is the same as "stable", so it makes sense to me that flipping among them does nothing.

**Comment by rndd-AK** [comment]
Well, ok, will try to fix it youself

**Comment by vcunat** [comment]
Well, I just don't understand what's wrong about your situation.  I can't promise that I would work on the problem once I understand it, but someone else might help with it regardless of me.

**Comment by DavidDudson** [comment]
This is the real problem.

https://github.com/zfsonlinux/zfs/issues/9332

We need patches for Linux 5.3 for zfs to work.

Apparently this is the fix, but we will need to wait for the merge.

https://github.com/zfsonlinux/zfs/pull/9161

**Comment by DavidDudson** [comment]
The temperary solution is to remove:

**Comment by rndd-AK** [comment]
Ok, thanks for info
