### ISSUE TITLE
qtbase depends on mariadb-server

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#69257]
This increases the closure size of anything depending on `qtbase` by about 200 MiB, relative to NixOS 19.03.

```
# nix why-depends /nix/store/47si3j8shlq7qm66bhdlwwc4r7s046xn-nixos-system-hagbard-19.09.20190922.16fc57b /nix/store/6mw46b8fi7jwhiwjk9jhm1ispcy7bcar-mariadb-server-10.3.18
/nix/store/47si3j8shlq7qm66bhdlwwc4r7s046xn-nixos-system-hagbard-19.09.20190922.16fc57b
╚═══activate: …art_kdeinit.echo -n "/nix/store/hqbzf9k4chwn4ch8naka5c4r6mpa5gqv-kinit-5.61.0/libexec/kf5/start_…
    => /nix/store/hqbzf9k4chwn4ch8naka5c4r6mpa5gqv-kinit-5.61.0
    ╚═══bin/.kdeinit5-wrapped: …gk1-libX11-1.6.8/lib:/nix/store/6a40srfrb6j4dn9dmf2rknarivd0anrk-qtbase-5.12.3/lib:/nix/store/ni…
        => /nix/store/6a40srfrb6j4dn9dmf2rknarivd0anrk-qtbase-5.12.3
        ╚═══lib/libQt5AccessibilitySupport.la: …ups-2.2.12-lib/lib -L/nix/store/6mw46b8fi7jwhiwjk9jhm1ispcy7bcar-mariadb-server-10.3.18/lib -L=/…
            => /nix/store/6mw46b8fi7jwhiwjk9jhm1ispcy7bcar-mariadb-server-10.3.18
```

**Comment by dtzWill** [comment]
Still building to confirm, but something like b128dc0fb6c29c43d7b30a7ad16d0997ffc8af30 might do the trick?

**Comment by dtzWill** [comment]
Yep, looks like that fixes the dep on the server!

**Comment by dtzWill** [comment]
Actually, this may already be fixed on staging: 329a88efa78126ae7413807ce58000eab49e82d9 (#65222).

**Comment by lheckemann** [comment]
Taking the liberty of removing blocker tag, because while annoying, it doesn't completely break anything. Would be happy to backport the fix once it's proven itself on master (the relevant staging merge seems to have been undone in f8a8fc6c7c079de430fa528f688ddac781bcef16).

**Comment by edolstra** [comment]
329a88e helps but IMHO qtbase shouldn't depend on mysql at all.

**Comment by edolstra** [comment]
Reinstated blocker label. Massive, unintended closure size increases *should* be considered serious regressions.

**Comment by vcunat** [comment]
I just re-checked quickly.  The dependency still holds on 19.09 but not on master anymore.  `du` size of `qt5.qtbase`: 460 MiB on 19.09, 180 MiB on master.
