### ISSUE TITLE
Duplicated XDG_DATA_DIRS in Qt applications

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#69277]
**Describe the bug**

Further to #54525 and relevant to #69272, ```XDG_DATA_DIRS``` is inflated by duplicate store paths:

```sh
$ echo $XDG_DATA_DIRS | sed -e 's/:/\n/g' | grep kwallet | sort
/nix/store/34bl44sm6fyn7qzmj0yl6w4dsxr46718-kwallet-5.61.0-bin/share
/nix/store/34bl44sm6fyn7qzmj0yl6w4dsxr46718-kwallet-5.61.0-bin/share
/nix/store/34bl44sm6fyn7qzmj0yl6w4dsxr46718-kwallet-5.61.0-bin/share
/nix/store/sr02l2rbmkp8mqqbn0v98xxhrdq0lch5-kwallet-5.61.0/share
/nix/store/sr02l2rbmkp8mqqbn0v98xxhrdq0lch5-kwallet-5.61.0/share
/nix/store/sr02l2rbmkp8mqqbn0v98xxhrdq0lch5-kwallet-5.61.0/share
```

Essentially all dependencies are there 3 times.

**To Reproduce**
1. Launch konsole
2. Run the command mentioned above

**Expected behavior**
Each store path should only be listed once.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0, NixOS, 20.03.git.48ca992ad6bM (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre188608.984851a9bfa"`
 - channels(peter): `"home-manager"`
 - nixpkgs: `/home/peter/src/active/nixpkgs_unstable`

Cc: @ttuegel

**Comment by ttuegel** [comment]
The responsible setup hook [specifically checks](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh#L79) that it is not adding duplicate paths, so I don't understand why this happens.

**Comment by ttuegel** [comment]
The `konsole` wrapper only includes the `kwallet` paths once.

> Each store path should only be listed once.

This is a known issue with `makeWrapper`: Running a wrapped program inside another wrapped program compounds their environments. In this case, probably, `konsole` forks and re-execs itself.

I am open to suggestions about how to fix the underlying problem in `makeWrapper`.

(This is probably not related to #69272.)

**Comment by matthewbauer** [comment]
Related to https://github.com/NixOS/nixpkgs/issues/67691

**Comment by lheckemann** [comment]
Is this fixed by #69426/#69427?

**Comment by ivan** [comment]
@lheckemann not in 19.09 at least, I commented on https://github.com/NixOS/nixpkgs/issues/67691#issuecomment-551448824

**Comment by peterhoeg** [comment]
Not fixed on unstable either.

**Comment by peterhoeg** [comment]
Very much still an issue.

**Comment by peterhoeg** [comment]
I am no longer seeing this on unstable.
