### ISSUE TITLE
Thinkpad E495 does not shutdown

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#69289]
**Describe the bug**
The Thinkpad E495 does not shutdown properly after a normal Nixos installation. The OS
shuts down but a lit screen and a working keyoard is still there.

**To Reproduce**
Just follow a normal NixOS install guide on a Thinkpad E495

**Metadata**
system: "x86_64-linux"
channels: "nixos-19.03"
Kernel: 4.2
CPU: AMD Ryzen 7 3700U

**Solution**
A Kernel newer then 5.x has to be used and redistributable firmware has to be enabled.
```
hardware.enableRedistributableFirmware = true;
boot.kernelPackages = pkgs.linuxPackages_5_2;
```

@Mic92

**Comment by Mic92** [comment]
@Luis-Hebendanz could add a profile on [nixos-hardware](https://github.com/NixOS/nixos-hardware)?
