### ISSUE TITLE
tamarin-prover doesn't compile: No instance for (Bin.Binary ZonedTime)

### ISSUE THREAD

**Issue by dsprenkels** [NixOS/nixpkgs#69292]
**Describe the bug**
`tamarin-prover` does not compile. The compiler errors on `src/Web/Types.hs` with a `No instance for (Bin.Binary ZonedTime)` error.

**To Reproduce**
1. Execute `nix-env --install tamarin-prover`

**Expected behavior**
The tamarin prover application should be successfully be installed.

**Additional context**

- Building the same version of the package, using the [build-from-source](https://tamarin-prover.github.io/manual/book/002_installation.html#sec:LinuxSrcInstall) method works fine.
- This error has also been [found](https://hydra.nixos.org/build/100468880/nixlog/1) by hydra.
- The reported error is:

```
[12 of 18] Compiling Web.Types        ( src/Web/Types.hs, dist/build/tamarin-prover/tamarin-prover-tmp/Web/Types.o )

src/Web/Types.hs:172:24: error:
    • No instance for (Bin.Binary ZonedTime)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Bin.Binary TheoryInfo)
    |
172 |   } deriving (Generic, Bin.Binary)
    |                        ^^^^^^^^^^

src/Web/Types.hs:185:24: error:
    • No instance for (Bin.Binary ZonedTime)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Bin.Binary DiffTheoryInfo)
    |
185 |   } deriving (Generic, Bin.Binary)
    |                        ^^^^^^^^^^

builder for '/nix/store/vcxb0jbqhzbfv0wyhrsnx07psrs7qh3v-tamarin-prover-1.4.1.drv' failed with exit code 1
error: build of '/nix/store/vcxb0jbqhzbfv0wyhrsnx07psrs7qh3v-tamarin-prover-1.4.1.drv' failed
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
$ nix run nixpkgs.nix-info -c nix-info -m
error: attribute 'nixpkgs' in selection path 'nixpkgs.nix-info' not found
```
^ `nix-env` was installed in userspace.

Cc @thoughtpolice

**Comment by thoughtpolice** [comment]
http://hackage.haskell.org/package/binary-orphans as of 1.0 no longer exports instances for `ZoneTimed` like it did before. We now need `binary-instances`. Ugh.

See https://hydra.nixos.org/build/98703924/nixlog/4 vs https://hydra.nixos.org/build/98551915/log
