### ISSUE TITLE
linuxPackages_5_1.rtlwifi_new fails to build

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#69291]
**Describe the bug**
The packages rtwifi_new do not build for the 5.x Kernel. Which is a bummer because I can't use an older Kernel because of driver issues https://github.com/NixOS/nixpkgs/issues/69289

**To Reproduce**
```
boot.extraModulePackages = [ pkgs.linuxPackages_5.1.rtlwifi_new ];
boot.kernelPackages = pkgs.linuxPackages_5_1;
```
$ nixos-rebuild switch

@Mic92

**Comment by Mic92** [comment]
Fixed in master and 19.09. Does this also affect 19.03?

**Comment by Luis-Hebendanz** [comment]
Yes it does!

**Comment by Mic92** [comment]
Should be fixed.
