### ISSUE TITLE
wafHook imports python2

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#69305]
wafHook imports python2 in a way that is slightly obfuscated (my progrma relied on python3 but wafHook pulled a python2 interpreter), should we move it to pythonPackages instead to make the interpreter more explicit ?

**Comment by matthewbauer** [comment]
wafHook should probably not depend on python2. Or at least it should just be used as a fallback. The way waf works, the "waf" script is vendored in, and we have no guarantee if it is for python2 or python3. See something like this:

https://github.com/NixOS/nixpkgs/compare/master...matthewbauer:waf-python3?expand=1

**Comment by jtojnar** [comment]
Ugh.

**Comment by rgrunbla** [comment]
Hi,

Any news concerning this issue?

Thanks

**Comment by FRidh** [comment]
PR decoupling python from the wafHook https://github.com/NixOS/nixpkgs/pull/106533.

**Comment by teto** [comment]
PR merged => closing.
