### ISSUE TITLE
Package youtube-dl-gui

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#69334]
**Project description**
A cross platform front-end GUI of the popular youtube-dl written in wxPython.

This makes the awesome commandline tool usable for more people!

Most repositories use the package name **youtube-dl-gui**, so i recommend to use it tool. https://repology.org/project/youtube-dl-gui/versions

Schould be quiet easy to package.

**Metadata**

* homepage URL: https://mrs0m30n3.github.io/youtube-dl-gui/
* source URL: https://github.com/MrS0m30n3/youtube-dl-gui
* license: The Unlicense
* platforms: unix, linux, darwin, ... (Python)

**Comment by davidak** [comment]
Sadly the project is not maintained anymore and has issues. We shouldn't add it.

**Comment by quantenzitrone** [comment]
There is an active fork: https://github.com/oleksis/youtube-dl-gui
