### ISSUE TITLE
Zoom-us SSO open empty browser page

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#69352]
**Describe the bug**
zoom-us package for Single Sign On opening empty web browser page browser tested Firefox and Chromium with the same result.

**To Reproduce**
1. Start zoom-us
2. Try to login with "Sign in with Google" or "Sign in with Facebook"

**Expected behavior**
Clicking the link for SSO should open the web page where user can be selected Ex. Google

**Additional context**
Tested in Archlinux with the same version of zoom and SSO work fine

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0, NixOS, 19.09beta317.88f32cca5a4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta317.88f32cca5a4, unstable-20.03pre193781.d484f2b7fc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by veprbl** [comment]
cc @danbst @tadfisher

**Comment by danbst** [comment]
set in your `~/.config/zoomus.conf`:
```
embeddedBrowserForFacebookLogin=true
embeddedBrowserForGoogleLogin=true
embeddedBrowserForSSOLogin=true
```
I'm not sure why it doesn't work by default.

**Comment by tadfisher** [comment]
Something's up with `xdg-open` in general, especially on Gnome. I can't open Zoom anymore from Chromium, for instance. The embedded browser workaround avoids the URL handler (e.g. xdg-open or gio) entirely and allows SSO to work.

**Comment by mudrii** [comment]
@danbst Thx this fixed SSO logged in.
Why we do not have these options by default?

**Comment by baracoder** [comment]
The workaround did not work for me on current unstable: Enabeling embedded browser options, if I click on login with google, the window just minimizes and nothing else happens.

**Comment by danbst** [comment]
@baracoder this is different issue, tracked in https://github.com/NixOS/nixpkgs/issues/73532
