### ISSUE TITLE
NetworkManager fails to autoconnect on login

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#69368]
**Describe the bug**

When I log into my desktop environment (i3), the network manager tries to connect to my home wlan but fails. If I then manually click to connect, it succeeds. For some reason it fails only when trying to connect automatically at the first login after a boot.

I've noticed that this happens on my home wlan that has a password but on some public wlans without passwords. I haven't tested other networks, but I'm guessing it fails on password-secured wlans but not on passwordless open wlans. This might be related to the gnome keyring (I assume the network manager is using that, but I'm not sure).

These might be useful lines from journalctl logs:
```
Sep 24 19:40:34 leevi kernel: IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
Sep 24 19:40:34 leevi dbus-daemon[7319]: [session uid=1000 pid=7317] Activating service name='org.freedesktop.secrets' requested by ':1.4' (uid=1000 pid=7377 comm="/nix/store/djflnag4w55jmiaz1fz2pqbjq51i3jlz-networ")
Sep 24 19:40:34 leevi dbus-daemon[7319]: [session uid=1000 pid=7317] Successfully activated service 'org.freedesktop.secrets'
Sep 24 19:40:34 leevi NetworkManager[1084]: <warn>  [1569343234.1288] device (wlp3s0): no secrets: No agents were available for this request.
Sep 24 19:40:34 leevi NetworkManager[1084]: <warn>  [1569343234.1295] device (wlp3s0): Activation: failed for connection 'Kotiloinen'
Sep 24 19:40:34 leevi kernel: IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
```

**To Reproduce**
1. Reboot
2. Log in to the desktop environment
3. Network manager tries to automatically connect to a familiar wlan and fails.

I'm not using any existing desktop manager. I'm using i3 with my own simple "desktop environment". FWIW, here's the how it's defined:

```
    systemd.user.targets.vaakko = {
      requires = [ "graphical-session.target" ];
      unitConfig = {
        RefuseManualStart = false;
        StopWhenUnneeded = false;
      };
    };

    services.xserver.enable = true;
    services.xserver.desktopManager.session = lib.singleton {
      manage = "desktop";
      name = "vaakko";
      bgSupport = false;
      start = ''
        ${pkgs.i3}/bin/i3 &
        waitPID=$!

        until ${pkgs.i3}/bin/i3-msg
        do
          echo "Waiting for i3 socket.."
        done

        systemctl --user start vaakko.target
      '';
    };
```

Any other information I should provide?

**Expected behavior**

Network manager should connect automatically and successfully to the wlan.

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03.git.d484f2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: `networking.networkmanager`
```

**Comment by mudrii** [comment]
I do 't have this issue with i3 and network manager connects automatically to known networks.
I use below config

```
    networking = {
      hostName = "nixos";
      networkmanager.enable = true; # enable network manager to start during boot
      nameservers = [ "8.8.8.8" "8.8.4.4" ];
      enableIPv6 = false;
      nat = {
        enable = true;
        internalInterfaces = ["ve-+"];
        externalInterface = "enp0s31f6"; # eth interface
      };
    };
``` 

Note: I didn't install NetworkManager as separate pkgs.

**Comment by jluttine** [comment]
@mudrii Does it connect to wlan with a password that's stored in some keyring (e.g., gnome keyring)? I guess the problem is that the secrets service isn't up yet, then network manager requests it and it gets up, but for some reason network manager doesn't get the secrets.. If I just restart the network manager after login (`sudo systemctl restart NetworkManager`), it connects automatically. So I believe it's somehow related to not finding the password at first..

**Comment by mudrii** [comment]
I am not using Gnome and can't confirm but seems Network Manager needs to start after gnome keyring.

I am not familiar with gnome keyring if is a service may need to be started 1st before network manager

**Comment by xaverdh** [comment]
I also had this issue with `networkmanager` until I tried the `iwd` backend from this [pr](https://github.com/NixOS/nixpkgs/pull/68147). You may want to do this as well to work around the issue.

**Comment by jluttine** [comment]
@xaverdh Thanks, that indeed fixes the issue. Weird. :slightly_smiling_face: 

Not sure if I should thus close this issue or is there still some underlying bug that needs fixing and this was just a workaround to avoid it.

**Comment by xaverdh** [comment]
I would consider this a workaround. `networkmanager` definitely is supposed to work with `wpa_supplicant` as backend.

**Comment by jluttine** [comment]
Still important to me. The root cause is most likely #69788.

**Comment by prasannavl** [comment]
Cause: https://unix.stackexchange.com/questions/534439/networkmanager-fails-to-auto-connect-to-wifi-network-when-the-password-is-kept-i

**Comment by jluttine** [comment]
I'm not using Gnome Keyring anymore but Pass Secret Service. With that, I don't have the issue anymore. Can't say if the issue with Gnome Keyring and NetworkManager still exists though.

**Comment by jluttine** [comment]
I'll close this but someone can comment if the issue still exists and I'll reopen this.
