### ISSUE TITLE
Go fails to init a new module in nix-shell

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#69401]
**Describe the bug**

I am trying to create a new Go module and it seems that `go mod init` is broken:

```
warning: GOPATH set to GOROOT (/nix/store/50d4z6i73rkb9wc7qh1083csxsxws7gk-go-1.12.9/share/go) has no effect
go: creating new go.mod: module foo
go: failed to create cache directory /nix/store/50d4z6i73rkb9wc7qh1083csxsxws7gk-go-1.12.9/share/go/pkg/mod/cache: mkdir /nix/store/50d4z6i73rkb9wc7qh1083csxsxws7gk-go-1.12.9/share/go/pkg/mod: permission denied
```

Unsetting `GOPATH` seems to fix the problem.

I have absolutely no idea about Go, but from what I understand, `GOPATH` is not needed when using Go modules and, according to the Nixpkgs manual, the default way of building packages now relies on modules, so I think the fact that nix-shell sets `GOPATH` is some sort of legacy behaviour which can be dropped.

**To Reproduce**

1. `mkdir /tmp/test && cd /tmp/test`
2. `nix-shell -p go`
3. `go mod init foo`

**Expected behavior**

A `go.mod` file is created.

**Metadata**

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.0.0, macOS 10.15`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(kirelagin): `"nixpkgs-20.03pre193309.c4196cca9ac, darwin"`
 - nixpkgs: `/Users/kirelagin/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - go
# a list of nixos modules affected by the problem
module:
```

**Comment by deviant** [comment]
I believe this has been fixed as of #87758 and #87913.
