### ISSUE TITLE
nixos/dbus: snapper CLI fails because of failed dbus system-service discovery

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#69404]
**Describe the bug**
The nixos snapper tests fails to run (mentioned in [ZHF 19.09](https://github.com/NixOS/nixpkgs/issues/68361)). 
Further inspection shows that this seems to be a DBUS problem. Running the snapper CLI results in
```
Failure (org.freedsktop.DBus.Error.Spawn.ServiceNotFound)
```
The journal indicates that dbus can not find `org.opensuse.Snapper`, even though the snapper module makes bus definitions available to dbus via `services.dbus.packages`.

Further inspecting the failure reveals that the problem started with commit ccd8421dc9da745c2d44013e8f9eccd78cdf5bdc, which was introduced in https://github.com/NixOS/nixpkgs/pull/67363. Reverting the patch on master seems to resolve the problem (reintroduce `"--datadir=/etc"` to dbus).

Note this may affect other tools too that communicate via dbus.

@worldofpeace may be able to help?

**To Reproduce**
1. `nix-build nixos/tests/snapper.nix` on master or 19.09

Thanks to @ck3d for helping to  track down the problem.

**Comment by worldofpeace** [comment]
Perhaps try this commit https://github.com/NixOS/nixpkgs/commit/5e55f20ebe01a787ac1182d2350e72eee017f667? (in staging)

**Comment by worldofpeace** [comment]
Also, in `/etc/dbus-1/session.conf` or `system.conf` do you see entries with `snapper` in it?

**Comment by markuskowa** [comment]
> Also, in /etc/dbus-1/session.conf or system.conf do you see entries with snapper in it?

Yes, when I inspect test everything looks OK:
* ` /etc/dbus-1/session.conf` mentions snapper includes
* even `/etc/dbus-1/system.d` contains the snapper file.

> Perhaps try this commit 5e55f20? (in staging)

Unfortunately that commit does not resolve the problem. The snapper test is still broken on staging (broken at HEAD de034181c95b6ee3e1b7086e724e0808df0728dc, for 5e55f20 testing is broken in general since it can't find `/dev/vda/`).

**Comment by worldofpeace** [comment]
So I'm guessing the dbus service can't activate, which runs `snapperd`.
```
# DBus service activation config
[D-BUS Service]
Name=org.opensuse.Snapper
Exec=/nix/store/9s1g1kbxsvp7gx8wdz37dz5nq0vvdzsq-snapper-0.8.3/sbin/snapperd
User=root
```

Does running `snapperd` as root cause any exceptions etc. ?

**Comment by markuskowa** [comment]
Starting `snapperd` manually works fine without any errors or even warnings.

To add some more details of the bug itself: after running a command on the cli (and fail) the journal shows:
```is
dbus-daemon: [system] Activating service name='org.opensuse.Snapper' requested by ':1.18' (uid=0 ...)
dbus-daemon: [system] Activated service 'org.opensuse.Snapper' failed: Bus name not found in systems service directory
````
I can not see any reason why dbus can not find the service but I can really pin down that error to this one commit ccd8421dc9da745c2d44013e8f9eccd78cdf5bdc. This changes if it runs or not. Could this be a bug in dbus which is triggered by removing `--datadir=/etc` from the `configureFlags`?

**Comment by ck3d** [comment]
The journal tells that the service was not found:
```
dbus-daemon[1112]: [system] Activated service 'org.opensuse.Snapper' failed: Bus name not found in system service directory
```

I found the same problem e.g. for _org.opensuse.CupsPkHelper.Mechanism_.

**Comment by worldofpeace** [comment]
Hmm, after reading dbus source code and how it looks through directories. Pretty sure this was used so we always use the configs at `/etc` even if they're legacy, and I think for `system-services` it doesn't use `XDG_DATA_DIRS`? The embedded configs already include those legacy configs, so probably why it didn't appear immediately broken.

I think I'll just revert that, any other intricacy I won't have the time to help ATM.

**Comment by markuskowa** [comment]
@worldofpeace thanks a lot for looking into the problem!
