### ISSUE TITLE
protonmail-bridge 1.2.2-1 doesn't start in GUI - QML not loaded properly

### ISSUE THREAD

**Issue by karolchmist** [NixOS/nixpkgs#69402]
**Describe the bug**
protonmail-bridge GUI stoped working when updated to version 1.2.2-1 (presumably after this PR: https://github.com/NixOS/nixpkgs/pull/68274). The console version works fine (`protonmail-bridge --cli`).

Pinging the maintainer: @lightdiscord

**To Reproduce**
1. Run `protonmail-bridge --level debug`

An error is produced:
```
➜  ~ protonmail-bridge --log-level debug                                                                                                                                                                          ~
DEBU[Sep 25 08:55:04.061] Frontend will use qt                          pkg=main
DEBU[Sep 25 08:55:04.061] Initializing bridge...                        pkg=main
DEBU[Sep 25 08:55:04.061] creating pass                                 pkg=bridgeUtils/keychain
DEBU[Sep 25 08:55:04.061] creating secretservice                        pkg=bridgeUtils/keychain
DEBU[Sep 25 08:55:04.088] Requesting  POST /auth/refresh                pkg=pmapi 
INFO[Sep 25 08:55:04.304] Saving refresh token for user 
DEBU[Sep 25 08:55:04.304] Requesting  GET /users                        pkg=pmapi 
INFO[Sep 25 08:55:04.394] update user: 
DEBU[Sep 25 08:55:04.394] Requesting  GET /addresses                    pkg=pmapi 
INFO[Sep 25 08:55:04.682] Autostart /nix/store/qg8zs2vyan227vp97g3qllrzi36l7mga-protonmail-bridge-1.2.2-1/lib/protonmail-bridge  pkg=frontend-qt
DEBU[Sep 25 08:55:04.682] Starting bridge...                            pkg=main
DEBU[Sep 25 08:55:04.682] Starting frontend...                          pkg=main
INFO[Sep 25 08:55:04.682] IMAP server listening at 127.0.0.1:1143       pkg=imap
INFO[Sep 25 08:55:04.683] SMTP server listening at 127.0.0.1:1025       pkg=smtp
INFO[Sep 25 08:55:04.683] API listening at 127.0.0.1:1042               pkg=api
WARN[Sep 25 08:55:04.713] QQmlApplicationEngine failed to load component  pkg=frontend-qml
WARN[Sep 25 08:55:04.714] qrc:/ui.qml:9 module "QtQuick.Controls" version 2.1 is not installed  pkg=frontend-qml
ERRO[Sep 25 08:55:04.714] Frontend failed with error: QML not loaded properly  pkg=main
```

(I deleted some sensitive informations.)

It seems like some "QML" Qt module is missing.

**Expected behavior**
A window of protonmail-bridge should open.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03.git.bccdb75 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(karol): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

Maintainer information:
```yaml
attribute:
  - protonmail-bridge
module:
```

**Comment by worldofpeace** [comment]
Likely adding `qtquickcontrols2` to `buildInputs` will fix this.

**Comment by worldofpeace** [comment]
Hmm, it appears to already be there.

After inspecting the binary, it wasn't wrapped with `wrapQtAppsHook`.
I believe https://github.com/NixOS/nixpkgs/commit/15e99a06a8d06f992ff4b148ee2cbeaf763a674f fixed this, and on latest master I cannot reproduce the issue.

**Comment by lightdiscord** [comment]
I can't reproduce the issue either

**Comment by karolchmist** [comment]
I'll wait for 15e99a0 patch  to arrive in `nixos-unstable`, using the cli version for now. Thanks you both for your help!
