### ISSUE TITLE
Gtk2 themes don't work in KDE unless gtk2 package is installed explicitly

### ISSUE THREAD

**Issue by alapshin** [NixOS/nixpkgs#69455]
**Describe the bug**
After update to nixos-unstable Gtk2 themes that use pixbuf engine (breeze-gtk, adwaiita) don't work in KDE unless gtk2 package is installed explicitly.

**To Reproduce**
1. Install gtk2 theme that uses pixbuf engine. I tried both breeze-gtk and adwaitta
2. Select installed theme as gtk2 theme. I tried both KDE's GTK application style module and lxappearance
3. Selected theme is not working. Instead default motif-like theme  is used.
4. When running lxappearance from console we can see warnings like
```
(lxappearance:17802): Gtk-WARNING **: 08:18:34.629: Unable to locate theme engine in module_path: "pixmap",
```

**Expected behavior**
Gtk2 themes should work correctly.

**Screenshots**
![Screenshot_20190926_082529](https://user-images.githubusercontent.com/321946/65660513-9a6a6d80-e037-11e9-9abf-0848fbba9a7c.png)

![Screenshot_20190926_082629](https://user-images.githubusercontent.com/321946/65660535-a8b88980-e037-11e9-98ae-734dca12a3a0.png)

**Additional context**
Explicit installation of `gtk2` package solves this issue. 
Issue was not present in nixos-19.03pre version until recent update to nixos-unstable.

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.3.0, NixOS, 20.03pre193829.f0fec244ca3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre193829.f0fec244ca3"`
 - channels(alapshin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - gtk2
# a list of nixos modules affected by the problem
module:
```

**Comment by michaelpj** [comment]
Hmmm, what do you see if you do `env | grep PIXBUF`?

My spider senses wonder whether this could be related to https://github.com/NixOS/nixpkgs/pull/68492. As a complete shot in the dark, I wonder if https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/gdk-pixbuf.nix#L42 needs to be changed to be a `sessionVariable`.

cc @worldofpeace

**Comment by alapshin** [comment]
> Hmmm, what do you see if you do env | grep PIXBUF?

There is no difference. In both cases (with explicitly installed gtk2 package and without) after `nixos-rebuild switch` followed by system reboot value remains the same
```
GDK_PIXBUF_MODULE_FILE=/nix/store/bj40icb9kwcv8nhq68h2amcs9w5cwd2d-gdk-pixbuf-loaders.cache
```

**Comment by michaelpj** [comment]
I'm not sure, then. (Also, I misread the error, which complains about pix*map* not pix*buf*, so I have even less idea what's going on!)

**Comment by worldofpeace** [comment]
Could be https://github.com/NixOS/nixpkgs/pull/68492/commits/cc125810cb4f305c5bcee937648ff3704f13c472 or https://github.com/NixOS/nixpkgs/pull/68492/commits/6663a795a3da44555f01cc04b90edd4157306bbb.

I  believe that changes makes it want to lookup the theme engines from the system path, which aren't installed with the Plasma5 module.

**Comment by prusnak** [comment]
I see the same issue when using GIMP (also a GTK2 app) under Gnome3 in `nixos-20.03pre196586.b943338ea58`.

Installing `nixos.gtk2` package manually helps.

**Comment by worldofpeace** [comment]
@prusnak Those commits were reverted https://github.com/NixOS/nixpkgs/commit/dd050270c78a0e214ed7cb9e25bae43b45406473 so I believe this should be fixed.
