### ISSUE TITLE
2 network manager services linked - network manager does not start

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#69547]
**Describe the bug**
There seems to be a bug with the network manager on the latest unstable channel, which prevents the network manager service from startup

**To Reproduce**
1. boot the system
2. systemctl status network-manager
```
● network-manager.service - Network Manager
   Loaded: error (Reason: Unit network-manager.service failed to load properly: File exists.)
   Active: inactive (dead)
     Docs: man:NetworkManager(8)

Sep 26 17:47:17 foo systemd[1]: network-manager.service: Two services allocated for the same bus name org.freedesktop.NetworkManager, refusing operation.

```
**Expected behavior**
The network manager starts.

**Additional context**
relevant entries in nix conf:
```nix
    networkmanager = { 
      # enable the network manager
      enable = true; 
      appendNameservers = [ "censored1" "censored2" ];
      unmanaged = [ 
        "interface-name:usbbr0"
        "interface-name:virbr*"
        "interface-name:vnet*"
        "interface-name:ve-*"
        "interface-name:inetVL*"
      ];  

    };  
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.16, NixOS, 20.03pre193829.f0fec244ca3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(foo): `""`
 - channels(root): `"nixos-20.03pre193829.f0fec244ca3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- networkmanager

```

**Comment by d4g** [comment]
I found some additional information:

There are 2 services defining the name "org.freedesktop.NetworkManager":
```
cd /etc/systemd
grep -R  'BusName=org.freedesktop.NetworkManager'
system/NetworkManager.service:BusName=org.freedesktop.NetworkManager
system/network-manager.service:BusName=org.freedesktop.NetworkManager
md5sum system/NetworkManager.service                                                                                                                                /etc/systemd
ccd57956db610a7be9f7ec48ef177d90  system/NetworkManager.service
md5sum system/network-manager.service                                                                                                                               /etc/systemd
ccd57956db610a7be9f7ec48ef177d90  system/network-manager.service


```
They do contain the same content.

**Comment by worldofpeace** [comment]
I believe f99bdb2b615 fixes this.

Can you check if you have this commit?

**Comment by d4g** [comment]
I don’t know how to verify that. How can I see if the commit is on the channel and version of the channel that I am using? The channel is noted in my original post.

**Comment by worldofpeace** [comment]
I've checked, that commit hasn't made its way to master out of staging yet. So you won't have it, but I'm certain it fixes this issue.

**Comment by mudrii** [comment]
Is it any way to apply specific commit from staging to the stable version?

**Comment by worldofpeace** [comment]
> Quick Comment
> Why these obvious changes pass the testing and go into the stable?

I don't think we have any nixos tests for networkmanager, which is a definite issue.
And when I wrote
> I've checked, that commit hasn't made its way to master out of staging yet. So you won't have it, but I'm certain it fixes this issue.

I was expressing its integration status for master. This change was backported to stable and is currently present in the release branch.

**Comment by worldofpeace** [comment]
This is the workflow we had to follow for NetworkManager
* https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md

That's because it causes a rebuild of so many changes. For release branches we follow a similar format, just with out `-next` branches.
