### ISSUE TITLE
ati_unfree: /etc/ati/amdpcsdb cannot be created or modified

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#6954]
The unfree ATI driver maintains a configuration file that is used to store settings for the graphic card. The file in question is `/etc/ati/amdpcsdb`. The problem is, the nix package for the unfree ATI driver symlinks the whole `.../etc/ati` directory from the nix store to the `/etc` directory, i.e. `/etc/ati/amdpcsdb` cannot be created or modified. One possible solution would be to generate the file from Nix configuration options, but if you take a look at its template file `/etc/ati/amdpcsdb.default`, you really don't want to do that. The way `amdpcsdb` can be created and modified is with the tool `amdcccle` that is included in the package.

So my suggestion is to copy the whole `/ati` configuration directory to `/etc` such that `amdcccle` can  apply modifications to this file. I know, this is not the Nix way to do things, but if you have a better idea, I'm happy to hear it. @MarcWeber, @offlinehacker, @geerds, what do you suggest?

Best,
Sven

**Comment by svenkeidel** [comment]
The configuration files are copied over [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/ati-drivers/builder.sh#L157-L158).

**Comment by svenkeidel** [comment]
Maybe symlinking individual files from `.../etc/ati/` to `/etc/ati/` instead of linking the directory. Is this possible somehow?

**Comment by blueberry** [comment]
Is there anyone that has multiple monitors and/or multiple GPUs setup? I tried everything possible that I could find, but couldn't make it work. On Arch, I had it set up through amdcccle. I suspect this is because of amdpcsdb but am not sure... Anyone knows how to enable multiple cards?

**Comment by jagajaga** [comment]
Ping all.

**Comment by pSub** [comment]
I won't have time to work on this issue any time soon.

**Comment by devoid** [comment]
I have multiple monitors and an AMD RX460. I'm not seeing any /etc/ati directory though. This is on the 16.03 channel.

**Comment by svenkeidel** [comment]
I don't own an ATI card anymore. Feel free to close this issue.
