### ISSUE TITLE
Does the EC2 image builder need to run in a VM?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6956]
Currently `amazon-image.nix` contains

``` nix
      pkgs.vmTools.runInLinuxVM (
```

but only seems to be doing simple mount and copy operations inside it. It seems like it would be a bit simpler if there were no VM in the picture, but I'm probably missing something.

**Comment by copumpkin** [comment]
It's also not clear to me why the `system.build.amazonImage` derivation needs to be in config, as opposed to just letting me generate the AMI from an arbitrary linux installation.

**Comment by copumpkin** [comment]
Oh I see, it uses the closure of `config.system.build.toplevel` :frowning: 

Is there no way to get what the closure of a NixOS box would look like without being on it?

**Comment by Profpatsch** [comment]
(triage) probably not a problem anymore, right?

**Comment by copumpkin** [comment]
It is, but I'm starting to fix it in #21943 #23026 #23052

**Comment by copumpkin** [comment]
#24964 is going to fix this.

**Comment by puffnfresh** [comment]
Pretty sure this can be closed.

**Comment by FRidh** [comment]
Closing since #24964 was merged.
