### ISSUE TITLE
Wifi issues with NixOS USB installation on new XPS 13 7390 (mid 2019)

### ISSUE THREAD

**Issue by jkarni** [NixOS/nixpkgs#69583]
**Describe the bug**
Cannot connect to WiFI after booting into 20.03 unstable (nixos-20.03pre193829.f0fec244ca3) image.

**To Reproduce**
1. Create 20.03 USB
2. Boot into it
3. Run `iwconfig`

Result: `lo no wireless extensions`. Trying to use `wpa_supplicant` as suggested in the guide of course doesn't work

**Expected behavior**
I expect other interfaces besides `lo`, and for `wpa_supplicant to work.

**Additional context**
`ifconfig`/`ip addr show` also only shows loopback. `dmesg | grep wifi` is empty.

Now, 20.03 isn't released yet, so why use it? Well, 19.03 (and 18.03) *don't boot at all*. I don't even get to the GRUB screen - when I select the USB to boot from, I just see the Dell screen forever. This is fairly new hardware (the new XPS 13, with Comet Lake and Killer Wi-Fi 6 AX1650) so I thought I'd try fairly new *software*, and that got me to at least boot.

It seems (from the [discussion on the Arch linux forum](https://bbs.archlinux.org/viewtopic.php?id=247705)) that I should use a kernel >= 5.2.2, but I don't really know how to do that - the way I know of updating the kernel (`boot.kernelPackages`) requires internet. I guess I could try building my own ISO image with that kernel, but the only *other* computer I currently have access to is not going to handle a nixpkgs install.

**Comment by worldofpeace** [comment]
Here's a link to a minimal install iso with the latest kernel
* https://hydra.nixos.org/build/100951153/download/1/nixos-minimal-new-kernel-19.09beta181.64e38f246ae-x86_64-linux.iso

Note that its nixpkgs revision is isn't what is the latest on the 19.09 beta because it appears to be failing to build.

**Comment by worldofpeace** [comment]
Oh it seems you were using 20.03 unstable and I've provided a 19.09 beta image.
I recommend not using unstable if you'd like a working experience right away, 19.09 is due to release very soon, and it should have a new enough kernel anyway. 
(we've branched off from unstable earlier this month)

**Comment by jkarni** [comment]
Ah perfect. I ended up finding a way to build an ISO myself, but 19.09 with the 5.2 kernel worked for me. 

Should I close? I imagine it might be a bit annoying for people that the ISO they are directed to download won't in the near future work for them if they have similar hardware; on the other hand, searching for this issue should already help.

**Comment by worldofpeace** [comment]
I think the actual issue here is we don't expose ISO's with newer kernels. And having these images clearly helps people, so I'll pursue it separately.

And yes, I think we can close this a it is resolved :+1: .
