### ISSUE TITLE
services.httpd: Improve virtualHosts and subservices.

### ISSUE THREAD

**Issue by nbp** [NixOS/nixpkgs#6960]
Currently `services.httpd` is complex and messy.  The biggest problem is that `subservices` are lazily added based on an attribute set which name which sub-services should be available.  This forbid the generation of any documentation for the subservices.  Users should be able to figure out their configuration from the manual without looking at the sources nor reading some wiki page (https://nixos.org/wiki/MediaWiki).

A long time ago, I already started to work on this issue (https://github.com/NixOS/nixos/compare/httpd-services), and failed at making a system which was easy enough to manipulate for somebody who does not know anything about NixOS module system.  I also failed at making it backward compatible, but I think this last idea is just a dead-end.

Now that more persons are looking at the multi-instances issues — which is the case of `virtualHosts` and `subservices` — I think I might have found a better way to address the user experience of module system users.

The idea is to remove the need for the per-server-options file, and automatically alias options which are useful inside the `virtualHosts` submodule (which was done manually in my previous attempt).  The second is to use `mkAliasDefinitions` to forward options definitions from the submodule into the parent module (while paying attention to keep the locations from the submodule).

To do so, we should duplicate `services.httpd` and create a new service, such as `services.apache` or `services.httpd_v2`, which would first be experimental, and then move as the only way to use it while we gradually get rid of current implementation.

**Comment by offlinehacker** [comment]
I think we also need an abstraction that would not only work with apache
but maybe also with other webservers like nginx. I especially don't like
that PHP services are apache only, i use nginx most of the time.

**Comment by edolstra** [comment]
Why should we get rid of per-server options?

We should get rid of `subservices` though. Those should be implemented as regular modules.

**Comment by domenkozar** [comment]
My biggest complain is the lack of documentation from options in the manual.

**Comment by edolstra** [comment]
Yeah, if `subservices` were to use the regular module system, then then would show up in the manual.

**Comment by nbp** [comment]
@edolstra , `per-server-option.nix` is not a limitation, but it is in the way, and duplicating the documentation sounds like too much documentation.  I would prefer to alias the option declarations to the one define in the main config, such as the documentation is not duplicated, and the documentation reads  "Same as `services.httpd_v2.adminAddr`."

**Comment by nbp** [comment]
@offlinehacker , I don't know how nginx nor PHP subservice are working, but it seems that it might be easier to integrate as soon as PHP subservice becomes a module.

**Comment by edolstra** [comment]
That's just a matter of hiding them from the documentation (e.g. using some flag).

**Comment by jagajaga** [comment]
ping

**Comment by Profpatsch** [comment]
Closing because no reaction; please reopen if still relevant.
