### ISSUE TITLE
Add bisq

### ISSUE THREAD

**Issue by cyplo** [NixOS/nixpkgs#69807]
**Project description**
It's a p2p marketplace for crypto currencies.

**Metadata**

* homepage URL: https://bisq.network/
* source URL: https://github.com/bisq-network/bisq
* license: AGPL 3
* platforms: linux, mac

**Comment by prusnak** [comment]
I read somewhere that @jb55 was trying to package it, is it still the case?

**Comment by jb55** [comment]
I had it running at one point but ran into issues with Tor. I should try again with a newer version...

**Comment by cyplo** [comment]
Heya, any luck with the newer version @jb55 by any chance ? :)

**Comment by jb55** [comment]
nope

**Comment by emmanuelrosa** [comment]
Good news!

Bisq now runs on NixOS :)

It was an... adventure getting it to work. Phew!
![bisq-screenshot](https://user-images.githubusercontent.com/13485450/77318733-1ff97c80-6d40-11ea-8a2a-a9b50bb5fd13.png)

**Comment by cyplo** [comment]
Awesome work ! Do you need any help to get it to the PR stage in nixpkgs ?

**Comment by emmanuelrosa** [comment]
There are three known run-time issues that need to be worked out:

1. An upstrem library has an embeded tor binary which gets extracted within the user's $HOME. I patchelf'ed the binary, though now I'm using the tor package in Nixpkgs instead. But the problem remains that Nix is unaware of this runtime dependency. I think the best solution is to patch the upstream library and get Gradle to use it instead of upstream. I think that can be done with Gradle repo priority.
2. The JVM crashes hard when trying to set a wallet passphrase.
3. The app launches fine the first time, but subsequent runs fail with an error about being unable to read an RSA key. I think it's referring to the Tor hidden service private key.

I was going to tackle the above, until I noticed the poor liquidity. It doesn't make much sense to put in the hours and then not be able to transact.

**Comment by cyplo** [comment]
Thanks for the update @emmanuelrosa  ! :)
The poor liquidity problem you mention, just to make sure -  is this an issue with the market conditions themselves/number of people on the application, or there something technical to fix there that creates this problem ?

**Comment by emmanuelrosa** [comment]
It's an issue with the market conditions. I didn't get any indication that the problem was technical in nature.

**Comment by cyplo** [comment]
I would love for this to land, I don't think it's stale, if that's okay

**Comment by juaningan** [comment]
I have Bisq compiling and working in my laptop since some time ago. The only caveat is that I launch tor manually. But maybe @emmanuelrosa you are interested in my nix file.

**Comment by emmanuelrosa** [comment]
I'm absolutely intetested, @juaningan

**Comment by juaningan** [comment]
Hi,

I share it here: https://gist.github.com/juaningan/903e633c7c7f4b4fda9e53ca74bb0810

**Comment by emmanuelrosa** [comment]
If you don't mind @juaningan, I want to add your package to my NUR.

**Comment by juaningan** [comment]
Great!! ideally debug and improve and send upstream also.

**Comment by emmanuelrosa** [comment]
I finally got around to working on the Bisq package some more.

The `bisq-desktop` package in my NUR (https://nur.nix-community.org/repos/emmanuelrosa/) is based on @juaningan 's work. It uses a launcher script which runs a Tor instance in the background on a random port. Said Tor instance is killed once Bisq exits.

There's also a .desktop file, so it can be launched from a desktop environment, dmenu, etc.

Let me know how it works out for you all.

**Comment by cyplo** [comment]
will test in a bit !

**Comment by cyplo** [comment]
getting 
```
BUILD SUCCESSFUL in 9m 48s
27 actionable tasks: 27 executed
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/la2swj7xp6z9qp49xm57mhvc6pbpqic4-bisq-desktop-deps
patching script interpreter paths in /nix/store/la2swj7xp6z9qp49xm57mhvc6pbpqic4-bisq-desktop-deps
checking for references to /build/ in /nix/store/la2swj7xp6z9qp49xm57mhvc6pbpqic4-bisq-desktop-deps...
hash mismatch in fixed-output derivation '/nix/store/88sc1p59vvrjx26fhp6jak07y1549zvp-bisq-desktop-deps':
  wanted: sha256:0z58kymzgrp6qhyfl8yqnw20glmdjv1wcysiidxv1acrghs6zwh0
  got:    sha256:122da0gkv94kdiz2j9drycdgp214l15lc94yxi4iwcn8djp8v435
error: build of '/nix/store/fh7rycx11ryam3xn700x71fdyarkb1ab-bisq-desktop-deps.drv' on 'ssh://nix-builder@brix.vpn' failed: hash mismatch in fixed-output derivation '/nix/store/88sc1p59vvrjx26fhp6jak07y1549zvp-bisq-desktop-deps':
```
when installing from scratch

**Comment by emmanuelrosa** [comment]
That fixed-point business is proving to be unreliable. It certainly won't be acceptable for Nixpkgs.

Perhaps we can use upstream's .dep package instead of building from source.

**Comment by emmanuelrosa** [comment]
I changed the package such that the end-user build is reproduceable, which should eliminate the _hash mismatch_ problem.

In a nutshell, the fixed-point "fake build" is now a separate Nix package only meant to be used by package maintainers. This new "package" called _mkdeps.nix_ does the "fake build" and produces a script, which when executed generates a fixed-point derivation for all of the Java dependencies; A file named _deps.nix_. The Bisq package uses _deps.nix_, effectively "pinning" the Java dependencies and making the Bisq package reproduceable.

Let's see how this works out.

**Comment by cyplo** [comment]
Seems working, good job ! Haven't done transactions, but just clicking around seems okay ? can port wallet over later and try more things, but this may take some time

**Comment by emmanuelrosa** [comment]
I successfully completed a transaction!

**Comment by cyplo** [comment]
I was able to make a transactions, everything seem to be working ! :)
Thanks for your hard work :)

Would it make sense to part to package into nixpkgs now ? 
This could lower maintenance burden on you specifically, we could ask for more maintainers maybe ? 
Asking because I think there's a new version of bisq available already

**Comment by emmanuelrosa** [comment]
Right now there's a lot of duplicated code, so I need to refactor it to get it ready for Nixpkgs. I plan to compare the current implementation (refactoring needs considered) with `gradle2nix`. If the latter can reduce the amount of code that needs to be maintained, I'll submit that implementation. If not, I'll submit a refactored version of the current implementation.

As for the new version of Bisq, it's already available in my NUR. So far it's working too.

**Comment by cyplo** [comment]
awesome, thanks for that, really good work :)

**Comment by nozpheratu** [comment]
@emmanuelrosa I tried using your package:

```nix
 { config, pkgs, ... }:
   
   let
     unstable = import <nixos-unstable> { config = { allowUnfree = true; }; };
     
   in {
     environment.systemPackages = with pkgs; [
       nur.repos.emmanuelrosa.bisq-desktop
       ...
    ];
 }

```


 but got this error:

```
error: anonymous function at /nix/store/y4m88kr7q6m2fgx9qkbjl571bifi8r8b-source/pkgs/applications/blockchains/bisq-desktop/default.nix:1:1 called without required argument 'copyDesktopItems', at /nix/store/7zh35957bxlgpl9hf7phv9pqsc202z0k-nixos-20.03.3324.929768261a3/nixos/lib/customisation.nix:69:16
(use '--show-trace' to show detailed location information)
```

**Comment by emmanuelrosa** [comment]
`copyDesktopItems` is not available on the stable branch yet, so you need to get NUR use unstable:

```
nixpkgs.config = {
    ...
    packageOverrides = pkgs: {
      nur = ... { pkgs = unstable; };
    };
  };
```

**Comment by nozpheratu** [comment]
@emmanuelrosa Weird, I tried that and now I get a different error:

```
{ config, pkgs, ... }:
   
   let
     unstable = import <nixos-unstable> { config = { allowUnfree = true; }; };
     
   in {
     environment.systemPackages = with pkgs; [
       unstable.repos.emmanuelrosa.bisq-desktop
       ...
    ];
 }
 
 nixpkgs.config = {
    packageOverrides = pkgs: {
      nur =  { pkgs = unstable; };
    };
  };
```

```error: attribute 'repos' missing```

**Comment by emmanuelrosa** [comment]
You can pin it to commit f0efbe21f9ae1e17d1aca922708f1bdef605039d

**Comment by nozpheratu** [comment]
Hmmm, I can't seem to get the package pinning working for nur. I guess I'll just wait until this makes it into the main package listing.

**Comment by emmanuelrosa** [comment]
Something is missing in your NUR definition. You first need to import the NUR so that you get a function. Then, apply the function. Like this:

```
nixpkgs.config = {
    packageOverrides = pkgs: {
      nur = import (builtins.fetchTarball {
          url = "https://github.com/nix-community/NUR/archive/a7542645ecbbdec548e22c16753ce51377ed5f64.tar.gz";
          sha256 = "0gvfpjbjid812gj9dkgb1i9p09idh3v0z2xam8i3qv6k1yhhwa41";
      }) { pkgs = unstable; };
    };
  };
```

**Comment by cyplo** [comment]
@emmanuelrosa - would the referenced commits be good to be included in nixpkgs or is something missing ? I've tested 1.6.4 from your recent commit and it just works :)

**Comment by emmanuelrosa** [comment]
The commits are ready.

**Comment by cyplo** [comment]
Is there a PR we could try to push through ?

**Comment by emmanuelrosa** [comment]
The PR is https://github.com/NixOS/nixpkgs/pull/119038

**Comment by felipelalli** [comment]
We need upgrade to v2 because v1 soon will be deprecated.

**Comment by emmanuelrosa** [comment]
Bisq 2 is on the way: https://github.com/NixOS/nixpkgs/pull/347160
