### ISSUE TITLE
Renoise 3.2 removed 32 bit support

### ISSUE THREAD

**Issue by HappyEnt** [NixOS/nixpkgs#69873]
## Issue description
With the new 3.2 update to Renoise support for 32 bit was dropped.

32 Bit packages of Renoise-3.1.0 are still available from the [archive mirror](https://files.renoise.com/demo/archive/). 
We could keep x86 support by offering a package fixed at Renoise-3.1.0
 and an up to date package tracking the latest release.

Though I wonder, does anybody even have demand for Renoise on x86?

**Comment by Artturin** [comment]
looks like there's no demand for this
