### ISSUE TITLE
GCE NixOS image improvements

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nixpkgs#6991]
To be able to get NixOS listed in Google Cloud Compute Engne, we will need to make sure we implement the following list:

Test Cases
- [x] Does the virtual machine boot successfully?
- [x] Does SSH work correctly?
- [x] Do Google tools/scripts work correctly?
- [ ] Does the virtual machine reach the “running” state within a hard cutoff time?
- [ ] Can users send/receive data from an external IP?
- [ ] Can users SSH into the virtual machine within a hard cutoff time?
- [ ] Can only authorized users SSH into the virtual machine?
- [ ] Google Daemon
  - [x] Is the Google Daemon installed?
  - [x] When an SSH key is added to the metadata, is a new user account created for the image? For each SSH key in the metadata, is there exactly one user account?
- [x] Is the image configured with the proper options?
- [x] Are the correct packages installed?
  - [x] Is the account manager job running?
  - [x] Is the address manager job running?
- [ ] Google Startup Scripts
  - [x] Are the Google Startup Scripts installed?
  - [x] Do the Google Startup Scripts work?
  - [x] Can user startup scripts be downloaded and run successfully?
- [ ] Image Bundle
  - [x] Is the Image Bundle installed?
  - [x] Does the image bundle work with basic options?
  - [x] Does the image bundle work with all options?
- [ ] Are the recommended options in the Building a Google Compute Engine Image guide set correctly?
- Note: This test case is Linux­specific.
- [ ] Python 2.6+: Is this installed?
- [x] Sshd: Is this installed?
- [ ] ISC DHCP Client: Is this installed? Is the set­hostname hook set?
- [ ] gcloud [Cloud SDK]: Is this installed? Can this run successfully?
- [ ] GSUtil: Is this installed? Can this run successfully?
- [ ] Are important packages at the correct versions?
- [x] Ssh: Is this installed?
- Note: Individual CLI tools such as gcloud/gsutil will be eventually be deprecated in favor of the unified Cloud SDK CLI tool.
- [ ] Are gcloud/gsutil at the correct version we intend to ship with the image?
- [ ] Do gcloud/gsutil version upgrades work with the image?
- [x] Is the image ​sparse​?
- Continuous Validation Process
  - [x] Is network performance acceptable?
  - [x] Is boot time acceptable?
  - [x] Is SSH time acceptable?
  - [ ] Does networking performance exceed the maximum acceptable threshold?
  - [ ] Does networking performance over time (week over week) stay acceptable?
  - [ ] Does boot time exceed the maximum acceptable threshold?
  - [ ] Does boot time stay low for X% of boots?
  - [ ] Does boot time over time (week over week) stay acceptable?
  - [ ] Do SSH connections succeed within the maximum acceptable threshold?
  - [ ] Does SSH connection time stay low for X% of SSH connections?  
  - [ ] Does SSH connection time over time (week over week) stay acceptable?

This ticket is to track the progress on this issue. @roconnor

**EDITED** by @obadz to get github friendly checkboxes. I've assumed that the filled dots were done and the translucid ones weren't but feel free to adjust as you see fit if that was wrong. The indentation was also hard to infer.

**Comment by copumpkin** [comment]
If you write 

```
 - [ ] foo
 - [x] bar
```

You'll get proper checkboxes that can actually be updated sensibly as follows:

 - [ ] foo
 - [x] bar

**Comment by wmertens** [comment]
What a wonderful list! Is there an automated test bench or are these
questions answered manually?
If we could mock the GCE api we might be able to test a bunch of these from
the nixos tests? (and other images too)

**Comment by Magnap** [comment]
The URL used to access metadata has changed, and `google-compute-image.nix` hasn't been updated to follow. It appears that all the files mentioned in the `fetch-ssh-keys` script have changed to a single file: `http://metadata.google.internal/computeMetadata/v1/project/attributes/sshKeys`. Unfortunately, I don't know enough to fix this properly.

**Comment by jagajaga** [comment]
ping :)

**Comment by obadz** [comment]
I've edited the original post to get Google friendly checkboxes. Pasting the original here in case there was some loss of information.

    Test Cases
    
    ● Does the virtual machine boot successfully?
    
    ● Does SSH work correctly?
    
    ● Do Google tools/scripts work correctly?
    
    ○ Does the virtual machine reach the “running” state within a hard cutoff time?
    
    ○ Can users send/receive data from an external IP?
    
    ○ Can users SSH into the virtual machine within a hard cutoff time?
    
    ○ Can only authorized users SSH into the virtual machine?
    
    ○ Google Daemon
    
    ■ Is the Google Daemon installed?
    
    ■ When an SSH key is added to the metadata, is a new user account
    
    created for the image? For each SSH key in the metadata, is there
    
    exactly one user account?
    
    ● Is the image configured with the proper options?
    
    ● Are the correct packages installed?
    
    ■ Is the account manager job running?
    
    ■ Is the address manager job running?
    
    ○ Google Startup Scripts
    
    ■ Are the Google Startup Scripts installed?
    
    ■ Do the Google Startup Scripts work?
    
    ■ Can user startup scripts be downloaded and run successfully?
    
    ○ Image Bundle
    
    ■ Is the Image Bundle installed?
    
    ■ Does the image bundle work with basic options?
    
    ■ Does the image bundle work with all options?
    
    ○ Are the recommended options in the Building a Google Compute Engine Image
    
    guide set correctly?
    
    Note: This test case is Linux­specific.
    
    ○ Python 2.6+: Is this installed?
    
    ○ Sshd: Is this installed?
    
    ○ ISC DHCP Client: Is this installed? Is the set­hostname hook set?
    
    ○ gcloud [Cloud SDK]: Is this installed? Can this run successfully?
    
    ○ GSUtil: Is this installed? Can this run successfully?
    
    ● Are important packages at the correct versions?
    
    ○ Ssh: Is this installed?
    
    Note: Individual CLI tools such as gcloud/gsutil will be eventually be deprecated
    
    in favor of the unified Cloud SDK CLI tool.
    
    ○ Are gcloud/gsutil at the correct version we intend to ship with the image?
    
    ○ Do gcloud/gsutil version upgrades work with the image?
    
    ● Is the image ​sparse​?
    
    Continuous Validation Process
    
    ● Is network performance acceptable?
    
    ● Is boot time acceptable?
    
    ● Is SSH time acceptable?
    
    ○ Does networking performance exceed the maximum acceptable threshold?
    
    ○ Does networking performance over time (week over week) stay acceptable?
    
    ○ Does boot time exceed the maximum acceptable threshold?
    
    ○ Does boot time stay low for X% of boots?
    
    ○ Does boot time over time (week over week) stay acceptable?
    
    ○ Do SSH connections succeed within the maximum acceptable threshold?
    
    ○ Does SSH connection time stay low for X% of SSH connections?
    
    ○ Does SSH connection time over time (week over week) stay acceptable?

**Comment by jpierre03** [comment]
@rbvermaa is there some updates ?

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by zimbatm** [comment]
Let's close this issue. I have been using the GCP images and they work for my use-cases. There are always things that can be improved.
