### ISSUE TITLE
option is already decklared

### ISSUE THREAD

**Issue by rndd-AK** [NixOS/nixpkgs#69913]
## Issue description

can't change "programs.bash.promptInit"

error: The option `programs.bash.promptInit' in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/programs/bash/bash.nix' is already declared in `/etc/nixos/bashrc.nix'.

**Comment by Ma27** [comment]
Would you mind sharing your config and the rev of nixpkgs you use to build your system?

**Comment by rndd-AK** [comment]
my actual config here - https://github.com/rndd-AK/configs_for_laptop/tree/master/nixos

-bash-4.4$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.16, NixOS, 19.03.173522.021d733ea3f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173522.021d733ea3f"`
 - channels(rndd): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Your module appears to provide the same options we have in nixpkgs causing this collision
* https://github.com/rndd-AK/configs_for_laptop/blob/9d23103c41105d85ae3b836eeb800e08f581fa08/nixos/bashrc.nix

**Comment by rndd-AK** [comment]
ok, my goal is modifying $PS1 :/

**Comment by Ma27** [comment]
The `promptInit` option has the `types.lines` type which means that multiple configurations can assign values and those will be concatenated in the end. If you want to ensure that your config actually overrides `PS1`, you may want to use `mkAfter`:

``` nix
{ lib, ... }:
{
  programs.bash.promptInit = lib.mkAfter '' 
    export PS1='...'
  '';
}
```

It's also possible to completely override an option value using `mkForce`:

``` nix
{ lib, ... }:
{
  programs.bash.promptInit = lib.mkForce ''
    # now everything else will be discarded.
    export PS1='...'
  '';
}
```

Apart from that I'd recommend to take a closer look at the resources from the following Discourse thread to get a more detailed explanation of the module system: https://discourse.nixos.org/t/best-resources-for-learning-about-the-nixos-module-system/1177/4

**Comment by rndd-AK** [comment]
well, it really works =)
But what if I want different $PS1 for different users?

**Comment by Ma27** [comment]
>  But what if I want different $PS1 for different users?

The NixOS module system is responsible for system-wide configuration. You *could* implement this with some hacks like `if [ "$(whoami)" = "foo" ]; then export PS1='bar'; fi`, but I'd actually recommend  to define a PS1 for each user locally. If you'd like to manage this with Nix as well, you might want to take a closer look at home-manager: https://github.com/rycee/home-manager
