### ISSUE TITLE
scylladb don't compile on nixos

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#70049]
```
[larluo@nixos-larluo:~]$ nix-env -f '<nixpkgs-unstable>' -iA scylladb
installing 'scylladb-3.0.5'
these derivations will be built:
  /nix/store/lp8phrjp1g1fmmh1cfp8jrz7q3a7f505-scylladb-3.0.5.drv
building '/nix/store/lp8phrjp1g1fmmh1cfp8jrz7q3a7f505-scylladb-3.0.5.drv'...
unpacking sources
unpacking source archive /nix/store/2nr9978qp56qnmrl4phm1d8p9l4dhkp3-scylla-403f66e
source root is scylla-403f66e
patching sources
applying patch /nix/store/4s4hblyppc69qjk8133ahx9p4xsf9s0z-seastar-configure-script-paths.patch
patching file seastar/configure.py
patching script interpreter paths in ./configure.py
./configure.py: interpreter directive changed from "/usr/bin/python3" to "/nix/store/swy0p01xr0wyh907d67hkxr1g0kngcpn-python3-3.7.4/bin/python3"
configuring
Traceback (most recent call last):
  File "./configure.py", line 38, in <module>
    for line in open('/etc/os-release'):
FileNotFoundError: [Errno 2] No such file or directory: '/etc/os-release'
builder for '/nix/store/lp8phrjp1g1fmmh1cfp8jrz7q3a7f505-scylladb-3.0.5.drv' failed with exit code 1
error: build of '/nix/store/lp8phrjp1g1fmmh1cfp8jrz7q3a7f505-scylladb-3.0.5.drv' failed

[larluo@nixos-larluo:~]$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="19.09pre177248.ed1b59a98e7 (Loris)"
VERSION_CODENAME=loris
VERSION_ID="19.09pre177248.ed1b59a98e7"
PRETTY_NAME="NixOS 19.09pre177248.ed1b59a98e7 (Loris)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

**Comment by erictapen** [comment]
`scylladb` seems to be broken in more than one way. I get (also on `nixos-unstable`)

```
...
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j4 -l4
[1/577] SWAGGER build/release/gen/api/api-doc/storage_service.json.hh
FAILED: build/release/gen/api/api-doc/storage_service.json.hh
seastar/json/json2code.py -f api/api-doc/storage_service.json -o build/release/gen/api/api-doc/storage_service.json.hh
/bin/sh: seastar/json/json2code.py: not found
[2/577] SWAGGER build/release/gen/api/api-doc/lsa.json.hh
FAILED: build/release/gen/api/api-doc/lsa.json.hh
seastar/json/json2code.py -f api/api-doc/lsa.json -o build/release/gen/api/api-doc/lsa.json.hh
/bin/sh: seastar/json/json2code.py: not found
[3/577] SWAGGER build/release/gen/api/api-doc/commitlog.json.hh
FAILED: build/release/gen/api/api-doc/commitlog.json.hh
seastar/json/json2code.py -f api/api-doc/commitlog.json -o build/release/gen/api/api-doc/commitlog.json.hh
/bin/sh: seastar/json/json2code.py: not found
[4/577] SWAGGER build/release/gen/api/api-doc/gossiper.json.hh
FAILED: build/release/gen/api/api-doc/gossiper.json.hh
seastar/json/json2code.py -f api/api-doc/gossiper.json -o build/release/gen/api/api-doc/gossiper.json.hh
/bin/sh: seastar/json/json2code.py: not found
ninja: build stopped: subcommand failed.
```

Pinging maintainer: @workflow

**Comment by workflow** [comment]
Noted! I'm pretty swamped at the moment, but hoping to look into it during the weekend.

It's a complex build with lots of dependencies.

**Comment by workflow** [comment]
Confirm this is happening, but only with `sandbox = true`

**Comment by workflow** [comment]
That is, a build against current `nixpkgs` master with `nix-build -A scylladb --option sandbox false` succeeds for me on NixOS 18.09

Will work on fixing that, but in the meantime you have a workaround.

**Comment by workflow** [comment]
> `scylladb` seems to be broken in more than one way. I get (also on `nixos-unstable`)
> 
> ```
> ...
> @nix { "action": "setPhase", "phase": "buildPhase" }
> building
> build flags: -j4 -l4
> [1/577] SWAGGER build/release/gen/api/api-doc/storage_service.json.hh
> FAILED: build/release/gen/api/api-doc/storage_service.json.hh
> seastar/json/json2code.py -f api/api-doc/storage_service.json -o build/release/gen/api/api-doc/storage_service.json.hh
> /bin/sh: seastar/json/json2code.py: not found
> [2/577] SWAGGER build/release/gen/api/api-doc/lsa.json.hh
> FAILED: build/release/gen/api/api-doc/lsa.json.hh
> seastar/json/json2code.py -f api/api-doc/lsa.json -o build/release/gen/api/api-doc/lsa.json.hh
> /bin/sh: seastar/json/json2code.py: not found
> [3/577] SWAGGER build/release/gen/api/api-doc/commitlog.json.hh
> FAILED: build/release/gen/api/api-doc/commitlog.json.hh
> seastar/json/json2code.py -f api/api-doc/commitlog.json -o build/release/gen/api/api-doc/commitlog.json.hh
> /bin/sh: seastar/json/json2code.py: not found
> [4/577] SWAGGER build/release/gen/api/api-doc/gossiper.json.hh
> FAILED: build/release/gen/api/api-doc/gossiper.json.hh
> seastar/json/json2code.py -f api/api-doc/gossiper.json -o build/release/gen/api/api-doc/gossiper.json.hh
> /bin/sh: seastar/json/json2code.py: not found
> ninja: build stopped: subcommand failed.
> ```
> 
> Pinging maintainer: @workflow

Not sure how to replicate this one yet

**Comment by erictapen** [comment]
Mh yeah I wrote a patch for `scylladb` to handle the case of `/etc/os-release` not being present and after that, this error log showed up. Unfortunately I lost that patch but it was something like

```python
try:
  ...
except:
  os_id = "linux"
```

**Comment by clojurians-org** [comment]
i build scylladb under redhat7(3.10.0-693.17.1.el7.x86_64)
it fail with following information:
```
[576/577] LINK (stripped) build/release/tests/perf/perf_checksum
[577/577] LINK (strippe) build/release/tests/perf/perf_idl
installing
cp: error writing '/nix/store/ckj609hn6clxk9nh5d7dwjqvzfzg608a-scylladb-3.0.5/build/release/tests/partitioner_tests.o': No space left on device
```

i have enough disk for it, but i don't understand why it occupy so huge size.
```
$ df -h
FileSystem                            Size    Used    Avail
/dev/mapper/rhel-root                  50G     33G     18G

$ du -sh /nix/store/ckj609hn6clxk9nh5d7dwjqvzfzg608a-scylladb-3.0.5/build/release
6.1G /nix/store/ckj609hn6clxk9nh5d7dwjqvzfzg608a-scylladb-3.0.5
```

**Comment by workflow** [comment]
@clojurians-org The final build is `18GB` for me. Haven't looked into why that is, yet.

**Comment by clojurians-org** [comment]
#70825
