### ISSUE TITLE
NVidia with GRUB/Luks

### ISSUE THREAD

**Issue by bakhtiyarneyman** [NixOS/nixpkgs#70050]
## Issue description

I have a workstation with 
1) Sabretooth Z77 motherboard which sports an integrated Intel graphics. 
2) NVidia GTX 1080 

The disk is encrypted via luks. I want to 
1) Hookup my monitors to the NVidia card
2) Power on the machine
3) Select the NixOS generation
4) Enter the disk password  
5) Have the system boot. 

Unfortunately, my monitor stays dark for (3) - (5).

I once was able to skip to (5) by typing the password in the dark, but couldn't repeat that. 

I will be super grateful for a workaround tip. Here's what I unsuccessfully cargo-culted in attempt to skip to (4):
```
boot.initrd.kernelModules = [ "nvidia" "nvidia_drm" "nvidia_modeset" "nvidia_uvm" ];
hardware.nvidia.modesetting.enable = true;
boot.initrd.extraUdevRulesCommands = ''
        KERNEL=="nvidia", RUN+="mknod -m 666 /dev/nvidiactl c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255"
        KERNEL=="nvidia_modeset", RUN+="mknod -m 666 /dev/nvidia-modeset c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 254"
        KERNEL=="card*", SUBSYSTEM=="drm", DRIVERS=="nvidia", RUN+="mknod -m 666 /dev/nvidia%n c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) %n"
        KERNEL=="nvidia_uvm", RUN+="mknod -m 666 /dev/nvidia-uvm c $(grep nvidia-uvm /proc/devices | cut -d \  -f 1) 0"
      '';
```
### Steps to reproduce

https://github.com/niobium0/nixos-configs/blob/master/hosts/iron.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.75, NixOS, 19.03.173553.6420e2649fa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173553.6420e2649fa"`
 - channels(bakhtiyar): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by eadwu** [comment]
With 19.03, the recommended way you should be using NVIDIA is through Prime Sync. Or if you really want "offloading", get a bootable system by disabling the NVIDIA GPU first before hacking a Bumblebee approach. By 20.03, Prime Offloading should be in the stable nixpkgs tree.

**Comment by niobium0** [comment]
Thank you Edmund! Prime is workable (although now I either have to plug/unplug some cables or type in the dark).

I never tried Prime because I was thrown off by "Only for laptops" line on Nixos wiki, which I now changed to "Mostly useful for laptops".
https://nixos.wiki/wiki/Nvidia
