### ISSUE TITLE
texlive: Armenian hyphenation (loadhyph-hy.tex) is missing

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#70175]
Ok, so, this is more of a help request rather than a bug report, I guess, as I am totally confused.

I am trying to build a bunch of LaTeX files which come with a complicated build system, I honestly have no idea how it works, but it seems to use some standard TeX-related tools that I am not familiar with (all I know how to do is run `pdflatex`). During the build process I get this weird error:

```
! I can't find file `loadhyph-hy.tex'.
<to be read again>
                   \relax
l.169   \repeat

(Press Enter to retry, or Control-D to exit)
Please type another input file name:
! Emergency stop.
<to be read again>
                   \relax
l.169   \repeat

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on pdflatex.log.
mktexfmt [ERROR]: running `pdftex -ini   -jobname=pdflatex -progname=pdflatex -translate-file=cp227.tcx *pdflatex.ini >&2 </dev/null' return status 1
mktexfmt [ERROR]: return error due to options --strict
mktexfmt [INFO]: Disabled formats: 6
mktexfmt [INFO]: Not selected formats: 43
mktexfmt [INFO]: Failed to build: 1 (pdftex/pdflatex)
mktexfmt [INFO]: Total formats: 50
mktexfmt [INFO]: exiting with status 1
I can't find the format file `pdflatex.fmt'!
```

(It is worth mentioning that the files I am trying to build have nothing to do with Aremenian. In fact, they don’t even use hyphenation.)

So I tried to figure out what is going on and ended up in `/nix/store/[...]-texlive-combined-full-2018/share/texmf/tex/generic`, where there is a file called `config/language.dat` which contains:

```
armenian loadhyph-hy.tex
```

A little bit of searching told me that `loadhyph-*.tex` files are all located in `hyph-utf8/loadhyph/`, so my natural instinct was to count them:

```
› find hyph-utf8/loadhyph -name 'loadhyph-*' | wc -l
      76
```

and

```
› cat config/language.dat | grep 'loadhyph-.*\.tex' | wc -l
      77
```

Hmmmmm...

Sure enough, on a closer inspection, it turns out that the only missing file is the `-hy` one. At the same time I can clearly see it in the [texlive distribution](http://www.tug.org/texlive//Contents/live/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-hy.tex).

Is this because the texlive scheme I installed does not contain the armenian hyphenation package or is there something wrong with the armenian hyphenation package in nixpkgs?

**Comment by kirelagin** [comment]
Hm, so here is another data point:

```
› nix build '(let tl = (import <nixpkgs> {}).texlive; in tl.combine { inherit (tl) scheme-basic hyphen-english; })'
› cd result/share/texmf/tex/generic
› cat config/language.dat | grep 'loadhyph-'
ukenglish loadhyph-en-gb.tex
usenglishmax loadhyph-en-us.tex
› ls hyph-utf8/loadhyph
loadhyph-en-gb.tex loadhyph-en-us.tex
```

```
› nix build '(let tl = (import <nixpkgs> {}).texlive; in tl.combine { inherit (tl) scheme-basic hyphen-armenian; })'
› cat config/language.dat | grep 'loadhyph-'
armenian loadhyph-hy.tex
› ls hyph-utf8/loadhyph
ls: hyph-utf8/loadhyph: No such file or directory
```

So, looks like it is the `hyphen-armenian` package indeed that does something wrong.

**Comment by kirelagin** [comment]
cc @veprbl

**Comment by veprbl** [comment]
Can't reproduce on master (f349aa3e5e8a74440ea8e697777500580e9d99ee) and release-19.03 (f9206f287e75df018726cca7ce3b0e55140f1134).
```
% nix build '(let tl = (import <nixpkgs> {}).texlive; in tl.combine { inherit (tl) scheme-basic hyphen-armenian; })'
[2 built]
% cd result/share/texmf/tex/generic
% cat config/language.dat | grep 'loadhyph-'
armenian loadhyph-hy.tex
% ls hyph-utf8/loadhyph
loadhyph-hy.tex
```

**Comment by kirelagin** [comment]
Weird, I’m on a slightly old unstable (c4196cca9ac).

**Comment by kirelagin** [comment]
Ok, sorry for the noise, probably the store path somehow got corrupted :/. Deleting it and rebuilding helped.
