### ISSUE TITLE
AppCenter for Pantheon desktop with our Flatpak backend

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#70214]
Elementary's AppCenter will use Flatpak in the future for their packages.

https://twitter.com/DanielFore/status/1179086985299779585
https://github.com/elementary/appcenter/issues/1076

Since we support Flatpak, we would be able to support AppCenter.

If we support PackageKit, it would even be possible to install Nix packages with AppCenter. (Needs https://github.com/NixOS/nixpkgs/issues/21230) In that case native Nix packages should be preferred.

I think AppCenter would be perfect for elementary's Pantheon desktop and we should support it (if possible). That way we would also be able to install all Apps from their store and even pay the developers. It would be great to be able to pay-what-you-want even for native Nix packages installed with AppCenter!

@worldofpeace what do you think?

Related to https://github.com/NixOS/nixpkgs/issues/58161

**Comment by worldofpeace** [comment]
Sounds great @davidak, I believe to start I can just package Appcenter.
I'll do that as a part of https://github.com/NixOS/nixpkgs/pull/69052

**Comment by worldofpeace** [comment]
It seems fedora gave up on Appcenter
* https://src.fedoraproject.org/rpms/appcenter/c/fc122bee492d6574f44cae28d2b809afaa043efa?branch=master

But I think with flatpak they've given it some future in other distributions.

**Comment by davidak** [comment]
would still be nice

**Comment by wmertens** [comment]
I used the Software app in gnome3 and the flatpacked software is pretty meh.
I could replace all the ones I was interested in with native NixPkgs.

I think it's achievable for us to have a packagekit backend again, listing all the packages that have .desktop files in them.

This would have many advantages over flatpack and give NixPkgs a chance at mainstream success.

**Comment by davidak** [comment]
@wmertens while i agree with your long term goal, this is probably easier to achieve. And the elementary AppCenter has only original programs designed for elementary OS mostly not packaged for Nix. https://appcenter.elementary.io/

**Comment by wmertens** [comment]
Having had a look at it, I wouldn't object to having the appcenter in nixpkgs, but I won't be the one packaging it :)

**Comment by davidak** [comment]
@wmertens you don't have to :)

another idea i had was to automatically package all AppCenter apps for Nix (https://github.com/NixOS/nixpkgs/issues/90244).

To have a great desktop experience with a graphical package manager, a packagekit backend would be perfect. That way we don't have to develop our own GUI and it's perfectly integrated in the desktop. (https://github.com/NixOS/nixpkgs/issues/21230)

**Comment by bobby285271** [comment]
I am not sure about the status of appcenter before my last push in #130380, and I am not sure if [the push](https://github.com/NixOS/nixpkgs/compare/f224aa89b9448c0c2097a1db76ab695f832d02a5..e63803494e4a96e37e64008b683c29e8a76292a0) can solve something (because this does not actually clean up *everything* related packagekit). But I am able to install some apps from it now (you can try by adding https://flatpak.elementary.io/repo.flatpakrepo or https://flathub.org/repo/flathub.flatpakrepo).

![2021-08-29 08-10-58 的屏幕截图](https://user-images.githubusercontent.com/20080233/131234567-8a2a2080-5547-410b-9776-0e7be2974e53.png)

![2021-08-29 08-20-59 的屏幕截图](https://user-images.githubusercontent.com/20080233/131234565-4b772468-975f-4527-a9f1-0fb78b306bfa.png)

**Comment by davidak** [comment]
I would say this works now. I can install, update and remove flatpaks.

![Screenshot from 2021-09-19 13-08-05](https://user-images.githubusercontent.com/91113/133925332-7211eeda-eaf9-49d9-966e-a9968b788eec.png)

I just had to enable flatpak support and install appcenter.

```
  services.flatpak.enable = true;
  xdg.portal.enable = true;
  xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];

  environment.systemPackages = with pkgs; [
    pantheon.appcenter
  ];
```

And add the elementary repo:

`flatpak remote-add --if-not-exists appcenter https://flatpak.elementary.io/repo.flatpakrepo`

@bobby285271 should we document these steps?

**Comment by bobby285271** [comment]
Yeah the manual needs update (https://nixos.org/manual/nixos/unstable/index.html#sec-pantheon-faq), I didn't noticed that when doing #130380. I am also thinking of whether we should make appcenter installed by default in fact.

**Comment by davidak** [comment]
>I am also thinking of whether we should make appcenter installed by default.

We should do that only when it's usable. So we would have to enable flatpak too, but i think most nixos users wouldn't want that by default. It also should add the elementary repo automatically.

I would like to have appcenter installed by default when it supports nix packages via packagekit.

**Comment by bobby285271** [comment]
I am trying to upstream my patch.

**Comment by bobby285271** [comment]
Hope this works... Not familiar with appcenter's code base and cannot do more so far...

- https://github.com/elementary/appcenter/pull/1739

**Comment by bobby285271** [comment]
92a6ad8626eb08dbf76fa389d595c7ac7accd70e is just merged, I will see if the patch is still needed.

**Comment by jtojnar** [comment]
Probably still need https://github.com/NixOS/nixpkgs/issues/15932 for the appcenter to display stuff (at least I assume that is why nothing is displayed in GNOME Software).

**Comment by bobby285271** [comment]
I just realized that I am stupid and did not enable `services.packagekit.enable` in previous testing. 🤦

The (only) motivation of patch is to prevent the non-working packagekit backend from blocking the flatpak backend functioning, after some testing I came to the conclusion that it should only be the case when `services.packagekit.enable` is not enabled.

I will make a pull request soon.
