### ISSUE TITLE
Add coz profiler

### ISSUE THREAD

**Issue by wykurz** [NixOS/nixpkgs#70221]
**Project description**
Coz is a new kind of profiler that unlocks optimization opportunities missed by traditional profilers. Coz employs a novel technique we call causal profiling that measures optimization potential. This measurement matches developers' assumptions about profilers: that optimizing highly-ranked code will have the greatest impact on performance. Causal profiling measures optimization potential for serial, parallel, and asynchronous programs without instrumentation of special handling for library calls and concurrency primitives. Instead, a causal profiler uses performance experiments to predict the effect of optimizations. This allows the profiler to establish causality: "optimizing function X will have effect Y," exactly the measurement developers had assumed they were getting all along.

**Metadata**

* homepage URL: https://github.com/plasma-umass/coz
* source URL: https://github.com/plasma-umass/coz
* license: BSD 2-clause
* platforms: linux

**Comment by dtzWill** [comment]
#68981
