### ISSUE TITLE
Nautilus: all files in sftp mountpoint are application/octet-stream

### ISSUE THREAD

**Issue by emanueleperuffo** [NixOS/nixpkgs#70236]
**Describe the bug**
I'm running NixOS 19.09.
All files inside sftp mountpoints in nautilus have content-type application/octet-stream.
This way, all files have the same icon, and I always need to right-click 'Open With Another Application'.
It's been like this for about 2 releases of NixOS.
I've tried with a fresh installation of NixOS 19.03 in VirtualBox and the issue is there as well.

Dolphin instead shows the files with the correct content-type.
Nautilus on Ubuntu shows the files with the correct content-type as well.

**To Reproduce**
1. Open Nautilus
2. Click 'Other Locations'
3. Enter an sftp:// location
4. Find some file with a known type (PDF, PNG, JPG, ...etc) in the new mounted filesystem
5. Right-click on the file and select Properties
6. File type is Program (application/octet-stream)

**Expected behavior**
We should see the proper content-type and not the type application/octet-stream (which is the fallback type for unknown content types)

**Screenshots**
![Screenshot from 2019-10-02 11-14-02](https://user-images.githubusercontent.com/5085029/66033363-685d7d80-e507-11e9-9a1f-fb71729311c5.png)

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.1, NixOS, 19.09beta521.7a3083fef83 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(manu): `""`
 - channels(root): `"nixos-19.09beta521.7a3083fef83, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
cc @jtojnar @hedning 

###### Note: If we get a fix I'd for sure want to backport it

**Comment by worldofpeace** [comment]
I'm not getting everything being `applications-octet-stream` over an sftp connection.
Actually everything has the proper mime-types.

Though I can still reproduce a similar issue like https://github.com/NixOS/nixpkgs/issues/53631.

@emanueleperuffo What's your configuration.nix? 
(this might be one of those global environment things)

**Comment by emanueleperuffo** [comment]
My configuration is split into multiple files.
I couldn't attach .nix files, so I created a zip with configuration.nix and a few other configuration files I import which I think might be useful for this issue.

@worldofpeace  Do you notice any difference with your configuration? Like some missing packages for gnome?

[nixos-gnome-issue.zip](https://github.com/NixOS/nixpkgs/files/3683170/nixos-gnome-issue.zip)

**Comment by emanueleperuffo** [comment]
I don't know if this can help, but Files from the pantheon desktop environment shows all files correctly.

**Comment by worldofpeace** [comment]
@emanueleperuffo Yeah I'm pretty stumped here, I can't reproduce.
This also works fine in Pantheon for me.

I guess I have to figure a way to test this in a vm today.

**Comment by emanueleperuffo** [comment]
I've tried it with the virtualbox image you can find in the downloads page.
I booted it, created a swap file and substituted kde with gnome. The issue
is there for me.

**Comment by emanueleperuffo** [comment]
I don't think this is a Nautilus issue.
See the below, content-type is wrong here as well.

```bash
$ gio info sftp://manu@******/home/manu/mirrored/Pictures/signature/signature.png

display name: signature.png
edit name: signature.png
name: signature.png
type: regular
size:  35977
uri: sftp://manu@******/home/manu/mirrored/Pictures/signature/signature.png
attributes:
  standard::type: 1
  standard::name: signature.png
  standard::display-name: signature.png
  standard::edit-name: signature.png
  standard::icon: application-octet-stream, application-x-generic, application-octet-stream-symbolic, application-x-generic-symbolic
  standard::content-type: application/octet-stream
  standard::fast-content-type: application/octet-stream
  standard::size: 35977
  standard::symbolic-icon: application-octet-stream-symbolic, application-x-generic-symbolic, application-octet-stream, application-x-generic
  etag::value: 1428150303
  id::filesystem: sftp:host=******,user=manu
  access::can-read: TRUE
  access::can-write: TRUE
  access::can-execute: FALSE
  access::can-trash: FALSE
  time::modified: 1428150303
  time::access: 1436873436
  unix::mode: 33188
  unix::uid: 1001
  unix::gid: 1001
```

**Comment by worldofpeace** [comment]
I've tried this with a host that was not linux and I could reproduce the issue.

**Comment by emanueleperuffo** [comment]
I came across issue #48665.

I tried, as suggested, to close all network shares, run `systemctl --user stop gvfs-daemon.service` and reopen the network shares. After this everything works as expected.

**Comment by bjornfor** [comment]
Tried NixOS master just now (20.03.git.804fbc9) and this appears fixed!
