### ISSUE TITLE
Emacspeak

### ISSUE THREAD

**Issue by symbiont-matthew-piziak** [NixOS/nixpkgs#70261]
**Project description**

Emacspeak is a speech interface that allows visually impaired users to interact independently and efficiently with the computer. 

Audio formatting—a technique pioneered by AsTeR—and full support for W3C's Aural CSS (ACSS) allows Emacspeak to produce rich aural presentations of electronic information. By seamlessly blending all aspects of the Internet such as Web-surfing and messaging, Emacspeak speech-enables local and remote information via a consistent and well-integrated user interface. Available free of cost on the Internet, Emacspeak has dramatically changed how the author and thousands of blind and visually impaired users around the world interact with the personal computer and the Internet. A rich suite of task-oriented tools provides efficient speech-enabled access to the audio desktop and evolving semantic WWW. When combined with Linux running on low-cost PC hardware, Emacspeak/Linux provides a reliable, stable speech-friendly solution that opens up the Internet to visually impaired users around the world.

**Metadata**

* homepage URL: http://emacspeak.sourceforge.net/
* source URL: https://github.com/tvraman/emacspeak
* license: GPL
* platforms: Linux

**Comment by Dema** [comment]
@symbiont-matthew-piziak I've created a derivation but I don't use emacspeak. There're lot of irrelevant files it the sources, I copied what I think is important.

Could you try to install it and test if it works?

**Comment by matthew-piziak** [comment]
Hi @Dema! Thank you so much. I've tried installing it, and I get `emacspeak` and `espeak` in `/nix/store`, though not on my PATH. The `espeak` executable, when invoked directly, works as expected. Moreover, loading the `emacspeak-setup.el` leaves Emacs in a state of `buffer has no process` errors on most actions—presumably the ones that are supposed to create sounds. This feels like an issue where Emacs is not able to start and communicate with the `espeak` speech server.

**Comment by Dema** [comment]
@matthew-piziak Could you, please retest it? I think I managed to make it work. if I launch `./run` or do 
`export DTK_PROGRAM=$(which espeak)` it works.

**Comment by matthew-piziak** [comment]
@Dema What do you do after `DTK_PROGRAM`?

Should `run` get put onto the PATH as `emacspeak` or something?

**Comment by Dema** [comment]
I'm not sure how it supposed to work. Looks like "run" is just an example and you just need to add `emacspeak-setup.el` in you .emacs. My emacs skill are a bit rusty :smile: I could try to rename `run` as `emacspeak` and put it into $PATH..

**Comment by matthew-piziak** [comment]
This is silly question...but how do I know which `emacspeak-setup.el` in my `/nix/store/` is the most recently built one?

**Comment by Dema** [comment]
I think you need the one that is in `/run/current-system/sw/share/....`

**Comment by matthew-piziak** [comment]
Hmmm. I still get `buffer has no process` when I load `emacspeak-setup.el`. 

I'm sorry I'm probably doing something wrong here. :/

**Comment by Mic92** [comment]
Using `nix-shell -p emacsPackages.emacspeak --run "emacspeak"` it should start emacs correctly configured for reading.
