### ISSUE TITLE
GTK 3.24.11: pkg-config file has wrong version information

### ISSUE THREAD

**Issue by vbgl** [NixOS/nixpkgs#70308]
Running `pkg-config --modversion gtk+-3.0` returns “3.24.10” and prevents some packages from building (e.g., “ocamlPackages.lablgtk3”).

This is an upstream bug: https://gitlab.gnome.org/GNOME/gtk/issues/2136

It might be fixed in nixpkgs by applying the following patch: https://gitlab.gnome.org/GNOME/gtk/commit/70c4b66d99f66b9da27ded63f2c26e3c13ce07f8 (not tested).

**Comment by worldofpeace** [comment]
Will fix @vbgl. 

Hmm, guess Emmanuele Bassi says the meson build isn't considered stable.
Though it's too late for me to even try to revert this, I'll just take special care to maintain it upstream whenever there's updates :smile:.
