### ISSUE TITLE
RaspberryPi 3 aarch64 image doesn't boot

### ISSUE THREAD

**Issue by Vourhey** [NixOS/nixpkgs#70320]
**Describe the bug**
I got the image from https://www.cs.helsinki.fi/u/tmtynkky/nixos-arm/installer/ aarch64 version and wrote it on a SD card, but it doesn't boot

**To Reproduce**
1. Write the image on a SD card
```
dd if=sd-nixos.img of=/dev/sda
```
2. Insert to RaspberryPi 3 Model B
3. Connect UART cable as described [here](https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi)
4. See

```
U-Boot 2018.07 (Jul 09 2018 - 14:24:14 +0000)

DRAM:  948 MiB
RPI 3 Model B (0xa02082)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from FAT... *** Warning - bad CRC, using default environment

Failed (-5)
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   No ethernet found.
starting USB...
USB0:   scanning bus 0 for devices... 3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
804 bytes read in 2 ms (392.6 KiB/s)
------------------------------------------------------------
1:      NixOS - Default
Enter choice: 1:        NixOS - Default
Retrieving file: /extlinux/../nixos/4n8f7w3zvin3fxvs5km8qmypc9a92lca-initrd-initrd
6853747 bytes read in 291 ms (22.5 MiB/s)
Retrieving file: /extlinux/../nixos/zbpbdvcazhh44sfzv9rgy9wllnab66v5-linux-4.18.7-Image
30059008 bytes read in 1255 ms (22.8 MiB/s)
append: systemConfig=/nix/store/sy8zfls2p4g2p7wjls4vyw487a794bkz-nixos-system-nixos-19.03.git.56b9f6fc8e1 init=/nix/store/sy8zfls2p4g2p7wjls4vyw487a794bkz-nixos-system-nixos-19.03.git.56b9f6fc8e1/init loglevel=7 cma=32M console=ttyS0,115200n8 console=ttyAMA0,115200n8 console=tty0 console=ttyS1,115200n8
Retrieving file: /extlinux/../nixos/zbpbdvcazhh44sfzv9rgy9wllnab66v5-linux-4.18.7-dtbs/broadcom/bcm2837-rpi-3-b.dtb
13265 bytes read in 4 ms (3.2 MiB/s)
## Flattened Device Tree blob at 02600000
   Booting using the fdt blob at 0x2600000
   reserving fdt memory region: addr=0 size=1000
   Using Device Tree in place at 0000000002600000, end 00000000026063d0

Starting kernel ...
```

And it doesn't boot. All I can see is `Starting kernel...` and nothing happens 

**Expected behavior**
RaspberryPi boots and I can connect via UART

**Comment by markuskowa** [comment]
That image you mention seems to be quite old. Have you seen this page https://nixos.wiki/wiki/NixOS_on_ARM?
The latest stable image can be found here:
https://hydra.nixos.org/job/nixos/release-19.03/nixos.sd_image.aarch64-linux

**Comment by tobiasBora** [comment]
Also, maybe a stupid question, but are you sure UART is enabled also in the kernel? I think to remember that I had similar issues at some point, and in fact the raspberry was booting fine, but UART was only configured in uboot (or similar) but not in the kernel itself, so I was just seeing `Starting kernel...`. Maybe try to use something like `nmap 192.168.1.0/24` to see if the raspberry pi appears on the network, and eventually change the UART parameters on the kernel line.

When I come back to my rasp I can try to see if I can find the options again.

**Comment by Vourhey** [comment]
Ok, I tried to use the latest image as @markuskowa suggested and saw the same
I also added `console=ttyS1,115200n8` but it didn't help. Unfortunately I can't connect the board via ethernet cabble so my only option is to use UART -> USB cabble. 

The green LED on the board constantly blinks 2 times in a row. I checked the sd card with this [tool](https://github.com/AltraMayor/f3) and it showed 0 errors

**Comment by markuskowa** [comment]
Setting `console=ttyS1,115200n8` in `/boot/extlinux/extlinux.conf` works for me to get a serial console.

**Comment by Vourhey** [comment]
Yeah, thanks, I finally got the output from the UART by adding `console=ttyS1,115200n8`. That's wierd, at the beginning it didn't work

**Comment by doronbehar** [comment]
So is this resolved now?

**Comment by saltdotac** [comment]
@Vourhey Did you change the location of `console=ttyS1,115200n8`? I'm having the same problem with the latest release (nixos-sd-image-20.03.3244.3b28e23a04c-aarch64-linux.img). I see it's already in your output above, at the end of "append" so I'm curious what changed.

**Comment by tobiasBora** [comment]
@saltdotac: note that the very last image does not boot with the latest Linux kernel. You need an older kernel to boot, there is another related issue, will try to find it.
