### ISSUE TITLE
Can't install next package in i686 nixos

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#70360]
When I try to install/pin the next browser package from master in my i686 nixos it won't install. 

1. adding:
```
    (let newpkgs = import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz)	{};
    in
      newpkgs.next
    )
```
to my configuration.nix

2. run nixos-rebuild switch:

> error: Package ‘next-1.3.1’ in /nix/store/yzp6fbwsrklmy433icw1zc4kasgprd84-source/pkgs/applications/
> networking/browsers/next/default.nix:74 is not supported on ‘i686-linux’, refusing to evaluate.    
> 
> a) For `nixos-rebuild` you can set
>   { nixpkgs.config.allowUnsupportedSystem = true; }
> in configuration.nix to override this.

3. I add this line to my config, but nothing changes, same message.

**Metadata**
 - system: `"i686-linux"`
 - host os: `Linux 4.14.108, NixOS, 18.09.2394.2d656a97297 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2574.a7e559a5504"`
 - channels(black): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Btw side question when I try to upgrade to 19.03 I get the message no tarball found for architecture i686-linux?

**Comment by jonringer** [comment]
when it was packaged, it was specifically added as a x86_64 package, it's to be building fine using the i686 overlay, when I have my desktop again, I'll see if it builds, if it does, then we can add that as a supported platform

**Comment by spiderbit** [comment]
That would be great, maybe you also can update the package also in the process current version is 1.3.4

**Comment by jonringer** [comment]
unfortunately, it seems that the webkitgtk package fails to build for i686:
```
lib/libWTFGTK.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::setTimeScale(unsigned int, WTF::MediaTime::RoundingFlags): error: undefined reference to '__mulodi4'
lib/libWTFGTK.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::operator*(int) const: error: undefined reference to '__mulodi4'
lib/libWTFGTK.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::operator*(int) const: error: undefined reference to '__mulodi4'
lib/libWTFGTK.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::compare(WTF::MediaTime const&) const: error: undefined reference to '__mulodi4'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
builder for '/nix/store/riigpncjzllb77s1syj0a580ylhwj6m5-webkitgtk-2.26.1.drv' failed with exit code 1
cannot build derivation '/nix/store/kbfwxz489yhbxl002k50m41s5y1k9m8l-next-gtk-webkit-1.3.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/akb1xi9rp9dlwczj4vzf16gfzjzdvl6w-next-1.3.4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/akb1xi9rp9dlwczj4vzf16gfzjzdvl6w-next-1.3.4.drv' failed
```

**Comment by spiderbit** [comment]
I switched the netbook to guix otherwise I have no i686 cpus anymore.

**Comment by jonringer** [comment]
doesn't seem to be relevant anymore
