### ISSUE TITLE
package request: RTL8812BU wireless driver

### ISSUE THREAD

**Issue by IvarWithoutBones** [NixOS/nixpkgs#70408]
**RTL8812BU wireless driver**
This is the wireless driver for the wifi card i use, and i can't seem to install existing drivers from github. (New to Nix, not quite sure how i would go about it). [There are several packages available on Github](https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959), like [this one](https://github.com/its-izhar/rtl88x2bu-driver). The issue i had with installing any of these that it could not seem to find the build directory for kernel modules. When specifying this with `make -C $(nix-build -E '(import <nixpkgs> {}).linux.dev' --no-out-link)/lib/modules/*/build` as described on the [Wiki](https://nixos.wiki/wiki/Linux_kernel), i got errors about this being a read-only file system. A NixPackage for this would be much appreciated

**Comment by mogria** [comment]
maybe this helps: this is a similar driver and may therefore be packaged similarly: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/rtl8812au/default.nix

Then there are the boot.kernelPackages & boot.kernelModules nixoa options

**Comment by IvarWithoutBones** [comment]
still important to me
