### ISSUE TITLE
How to install systemctl service on nixos

### ISSUE THREAD

**Issue by ORESoftware** [NixOS/nixpkgs#70437]
If I do this:

```bash

#!/usr/bin/env bash

set -eo pipefail;

cd "$(dirname "$BASH_SOURCE")"

ln -sf "$(pwd)/interos-es-mdb.service" '/etc/systemd/system/interos-es-mdb.service'

systemctl enable interos-es-mdb.service && systemctl start interos-es-mdb.service

```

then I get this error:

> ln: failed to create symbolic link '/etc/systemd/system/interos-es-mdb.service': Read-only file system

**Comment by Ma27** [comment]
`.service` files from derivations can be added using [`systemd.packages`](https://nixos.org/nixos/options.html#systemd.packages) as well.

**Comment by jonringer** [comment]
looks like the stackoverflow answer was  pretty spot on. You take some derivation of your package, add it to [`systemd.packages`](https://nixos.org/nixos/options.html#systemd.packages), then when you do `nixos-rebuild`, it should give you a new systemd configuration which includes your package.

```
trace: Systemd Service field `Restart' cannot have value `Always'.
```
I think you want `always`, lower-case
It's failing validation from this assertion https://github.com/NixOS/nixpkgs/blob/1a27482a6ce3e14dab274ef55051111b25a33cff/nixos/modules/system/boot/systemd-unit-options.nix#L12

**Comment by aanderse** [comment]
@ORESoftware it seems to me like this issue is resolved and you have received the advice needed. If that is not the case please reopen the issue. Thanks!
