### ISSUE TITLE
shotwell: Segmentation fault on current master

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#70435]
**Describe the bug**

```
$ nix-shell --pure -p shotwell --run shotwell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz

(shotwell:15669): dbind-WARNING **: 04:47:47.933: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(shotwell:15669): GLib-CRITICAL **: 04:47:48.013: g_strsplit: assertion 'string != NULL' failed
/tmp/nix-shell-15188-0/rc: line 1: 15669 Segmentation fault      (core dumped) shotwell
```

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03pre193829.f0fec244ca3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre193829.f0fec244ca3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
We upgraded vala so that might have something to do with it.
Looking over https://gitlab.gnome.org/GNOME/shotwell/commits/master, there's many crash fixes.
Though I am surprised it even succeeds to compile :smile:

**Comment by Kjuvi** [comment]
Is it possible that #70635 solved this issue ? I just have tried and I don't have any seg fault.

**Comment by worldofpeace** [comment]
Possibly @Kjuvi, but without a backtrace with debug symbols I don't think we could tell.
Looking at their upstream tracker there's some serious issues
* https://gitlab.gnome.org/GNOME/shotwell/issues/164

Not sure if that's resolved, but with raw files there seems to be issues.

I'd just recommend people to use elementary-photos, it was fork of shotwell at some point anyway that for sure has feature parity (and CSD).

**Comment by bjornfor** [comment]
shotwell runs for me on master and release-20.03. But not with `nix-shell --pure ...` though, since then it cannot open the display (missing env vars).
