### ISSUE TITLE
nixos manpages contain stray (?) double underscore for some reason

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#70468]
**Describe the bug**

Noticed when using `man configuration.nix` and other NixOS manpages, not sure when this started but this looks wrong:

```
NAME
       configuration.nix __ - NixOS system configuration specification
```

What's the `__` after "configuration.nix" and before the hyphen??

**To Reproduce**
1. ...`man configuration.nix`
2. ...Observe underscores
3. ...Check hydra's builds contain same artifact: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.manpages.x86_64-linux#tabs-status -- currently the latest store path is `/nix/store/7civ66nqxb4dn9a0zcv2hdvcdnpwalrl-nixos-manpages` if that helps

**Expected behavior**

```
NAME
       configuration.nix - NixOS system configuration specification
```

**Comment by dtzWill** [comment]
FWIW not just a rendering glitch AFAICT, snippet from inspecting raw manpage:

```
.SH "NAME"                                                                                                                            
configuration.nix
__ \- NixOS system configuration specification
.SH "DESCRIPTION"
.PP
```

**Comment by xzfc** [comment]
#70475

**Comment by dtzWill** [comment]
<3, thanks!
