### ISSUE TITLE
virtualBox guest additions won't build *on Hydra*

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#70470]
**Describe the bug**
A few days ago these builds started regressing, apparently on all our branches, e.g. very stable 19.03 https://hydra.nixos.org/job/nixos/release-19.03/nixos.ova.x86_64-linux  &ndash; and they are blocking the big channels.

**To Reproduce**
I'm unable to reproduce the problem locally, and Hydra fails repeatedly with a consistent (but weird) message
```
isoinfo: Warning: Joliet escape sequence uses illegal space at offset 3
Creating directory install
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.28 Guest Additions for Linux
Not enough space left in . (3226427648 KB) to decompress ./VBoxLinuxAdditions.run (7212 KB)
builder for '/nix/store/xsvgy5mnpnnl1zf9n9mxz7gcwsv93az6-VirtualBox-GuestAdditions-5.2.28-4.19.76.drv' failed with exit code 1
```

As the problem seems Hydra-specific, I suspect it's related to the way the cloud instances are set up, so perhaps @grahamc might have an idea?

I tested locally with `nix build -f nixos/release.nix ova.x86_64-linux`, but that's probably overkill and `nix build -f . linuxPackages.virtualboxGuestAdditions` [is enough](https://hydra.nixos.org/build/102650738).

**Comment by matthewbauer** [comment]
Is this the same as https://github.com/NixOS/nixpkgs/issues/70442?

**Comment by vcunat** [comment]
No, that one is only on master and affects directly the OVA build.

**Comment by lheckemann** [comment]
I can reproduce this in a VM with a 4TB disk. There must be some overflow or something in the guest additions extractor tool.

**Comment by lheckemann** [comment]
Fix above.
