### ISSUE TITLE
19.09 TeXstudio doesn't start 

### ISSUE THREAD

**Issue by DunkleCat** [NixOS/nixpkgs#70511]
**Describe the bug**

Trying to start `texstudio` led to an abort with this error
`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`
This happened after the 19.03 to 19.09 update.

**To Reproduce**
1. Use 19.09 channel
2. Install texstudio
3. Try to start it

**Expected behavior**

The application starts without problems

**Metadata**

`▶ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.2, NixOS, 19.09beta606.3ba0d9f75cc (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta606.3ba0d9f75cc, nixos1903-19.03.173553.6420e2649fa, nixos1909-19.09beta606.3ba0d9f75cc"`
 - channels(dunklecat): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos``

**Comment by veprbl** [comment]
cc #65399

**Comment by johannesloetzsch** [comment]
I had the same problem, installing `qt5Full` solved it. You may want try:

> nix-shell -p texstudio -p qt5Full --run texstudio

**Comment by DunkleCat** [comment]
Report:

On 19.03 the package works as expected
On 19.09 the package works as expected if `qt5.full` is declared, too

**Comment by bb010g** [comment]
This is fixed for `master` in #73484, but not yet for `release-19.09`.

**Comment by bjornfor** [comment]
Should be fixed now with b926503738cc5b19f3ee66f8a5745c41318a82ff and parent on release-19.09 branch.
