### ISSUE TITLE
Get rid of the BEAM package set

### ISSUE THREAD

**Issue by DianaOlympos** [NixOS/nixpkgs#70524]
## Issue description

Right now the BEAM package set snapshot is left without maintenance and update since 2018. The BEAM community have move to lock files handled by its build tool (mainly mix and rebar3). With the deployment of sandboxing, the hermetic build of rebar3 patched for Nix has been abandoned and deleted in #54115 .

Following #54115 and #53834 and also https://discourse.nixos.org/t/state-of-the-beam-ecosystem-in-nix/4202/, it seems obvious that the BEAM community do not expect this to continue. There have been multiple tentative and work in progress to build a tool to incorporate these build tools lockfile into nix. And flakes may help on the long run.

While the community is coalescing around a long run solution, I would like to get rid of the package set and the associated functions, and update the documentation to explicitly state that you need to download dependencies by hand without sandboxing. This is already what everyone is doing due to the age of the snapshot of hex. Better get rid of the maintenance burden.

I am interested in hearing reasons to not do so and help around how to word this and alert users of possible break in their build. I doubt it will affect too many people.

**Comment by DianaOlympos** [comment]
cc @ankhers @gleber possibly ?

We are using the BEAM on Nix in production right now and we would like to help the state of the ecosystem to be a bit nicer for everyone :smiley:

**Comment by gleber** [comment]
@DianaOlympos I support this step. That's the right thing to do.

**Comment by ankhers** [comment]
I agree. It should be removed.

**Comment by DianaOlympos** [comment]
Ok i will take a try at it later this week and open a PR. I bet this one is going to be painful...

**Comment by DianaOlympos** [comment]
https://github.com/NixOS/nixpkgs/pull/71393
