### ISSUE TITLE
bzflag: Failing to start

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#7052]
All I know:

```
$ bzflag 
[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
bzflag: xcb_io.c:576: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
Aborted
```

After installing with `nix-env -iA` in my user environment.

**Comment by matthiasbeyer** [comment]
Issue remains on latest unstable:

```bash
$ nixos-version 
16.03pre73316.93d8671 (Emu)
```

**Comment by kevincox** [comment]
@Phreedom Do you know anything about this package. You're the only person in the blame that I can track down.

Since this package has no maintainer it might be worth consider removing it (or marking it as broken) unless someone shows up.

**Comment by matthiasbeyer** [comment]
Closing because too old to get addressed IMO.
