### ISSUE TITLE
Hibernate acts the same as shut down

### ISSUE THREAD

**Issue by vanceism7** [NixOS/nixpkgs#70548]
**Describe the bug**
Hibernating my computer seems to act the same as shutting down. It goes through the process like its going to hibernate, but upon turning back on the computer, it just goes through a standard startup sequence as if I had just selected the `shut down` option

**To Reproduce**
Just using the xfce whisker menu, I click `log out` -> `hibernate`

**Expected behavior**
The computer hibernates and resumes where I left off when I turn it back on

**Additional context**
I don't think its my computer itself that is the problem, I moved over from arch linux (manjaro) and hibernate worked fine on there.

**Metadata**
 - Laptop Make/Model: `Acer Aspire E 15 (E5-573-5653)`
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.75, NixOS, 19.03.173547.2c61951df92 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I do have a swap partition (not sure if that matters but I saw swap mentioned in other issues relating to hibernate). 
Also, my main hdd is a solid state drive

Thanks!

**Comment by worldofpeace** [comment]
@vanceism7 I noticed you said it was with xfce's whisker menu.

Here's the code that does this
* https://github.com/gottcode/xfce4-whiskermenu-plugin/blob/fae01b6e1bb35a6fd631919886cf5386b1d1ec6b/panel-plugin/settings.cpp#L163 (hibernate)
* https://github.com/gottcode/xfce4-whiskermenu-plugin/blob/fae01b6e1bb35a6fd631919886cf5386b1d1ec6b/panel-plugin/settings.cpp#L151

So this interacts with `xfce4-session`
Glancing xfce4-session's code, it appears it should be interacting completely with systemd for this purpose.

What does this command return?
```
dbus-send --system --print-reply --dest="org.freedesktop.login1" /org/freedesktop/login1 org.freedesktop.login1.Manager.CanHibernate
```

And does this hibernate your system?
```
dbus-send --system --print-reply --dest="org.freedesktop.login1" /org/freedesktop/login1 org.freedesktop.login1.Manager.Hibernate boolean:true
```

**Comment by vanceism7** [comment]
The output for the first command is this:
```
method return time=1570419833.287655 sender=:1.10 -> destination=:1.51 serial=93 reply_serial=2
   string "yes"
```

The second command seems to be going through the motions of hibernate (similar to the whisker menu), but turning back on is still going through a regular start up sequence

**Comment by vvs-** [comment]
I had similar experience on Fedora. It didn't find my swap while booting from initrams and before switching to new root filesystem. Another possible reason might be silent kernel crash at a booting stage. So, this might be specific to your setup. You'll need more debugging to find a real cause.

**Comment by worldofpeace** [comment]
Yeah, if the second command produces this it's likely, as @vvs- pointed out, there's a silent kernel crash at the booting stage related to hibernation.

@vanceism7 You did mention this worked in Manjaro, it's likely they held newer package versions than 19.03 and perhaps used a newer kernel. Have you tried using a newer kernel?

**Comment by vanceism7** [comment]
So I checked my kernel and it was on 4.19.75. I upgraded to 5.2 but behavior seems to be the same. Is there a way to check hibernate logs?

**Comment by vvs-** [comment]
I don't know if that's possible at all without some ad hoc trickery like serial console. But you could search your boot logs for something suspicious. Does at least suspend/wake-up work? If there is a crash there is a good chance that it happens there too.

**Comment by vvs-** [comment]
Also, you might find that useful: https://01.org/blogs/rzhang/2015/best-practice-debug-linux-suspend/hibernate-issues

**Comment by vanceism7** [comment]
Suspend/wake-up works fine. Thanks! I'll check out the link and see what I can find

**Comment by vanceism7** [comment]
So I found this website: https://www.kernel.org/doc/Documentation/power/basic-pm-debugging.txt

I went through some of the basic hibernate tests using the `pm_test` file as described in the above. Basically, your computer goes through all the processes of hibernating without actually fully shutting down (it saves an image of current system state, and resumes from it, etc). All of these tests worked without any issue, so it seems that the actual problem has to do with the act of booting up.

I did notice the presence of some extra logs during the nixos startup sequence when booting back up from a hibernation. During `NixOS Stage 1`, these extra logs appear
```
nixos: recovering journal
nixos: Clearing orphaned inode (a bunch of numbers) (uid=1000, gid=100...)
```
There are 5 entries in the log for clearing orphaned inodes. Might that be related to the resume not working?

**Comment by vvs-** [comment]
Yes, that just means that it didn't restored from hibernated image but ordinary booted instead. In that case file system was not clean of course, that's expected. It is a strong sign that something went wrong during initial boot just after hibernation. There might be something wrong with the kernel or with NixOS scripts, e.g. swap partition was not found for some reason. In my case on Fedora there were no early initramfs LVM support (my swap is on LVM volume).

**Comment by vvs-** [comment]
Here's the snippet from stage-1-init.sh which supposed to restore from hibernated image:
```
if test -e /sys/power/resume -a -e /sys/power/disk; then
    if test -n "" && waitDevice ""; then
        resumeDev=""
        resumeInfo="$(udevadm info -q property "$resumeDev" )"
    else
        for sd in /dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; do
            # Try to detect resume device. According to Ubuntu bug:
            # https://bugs.launchpad.net/ubuntu/+source/pm-utils/+bug/923326/comments/1
            # when there are multiple swap devices, we can't know where the hibernate
            # image will reside. We can check all of them for swsuspend blkid.
            if waitDevice "$sd"; then
                resumeInfo="$(udevadm info -q property "$sd")"
                if [ "$(echo "$resumeInfo" | sed -n 's/^ID_FS_TYPE=//p')" = "swsuspend" ]; then
                    resumeDev="$sd"
                    break
                fi
            fi
        done
    fi
    if test -n "$resumeDev"; then
        resumeMajor="$(echo "$resumeInfo" | sed -n 's/^MAJOR=//p')"
        resumeMinor="$(echo "$resumeInfo" | sed -n 's/^MINOR=//p')"
        echo "$resumeMajor:$resumeMinor" > /sys/power/resume 2> /dev/null || echo "failed to resume..."
    fi
fi
```
It should print a message on the console if something went wrong. Did you see it? Can you confirm that uuid above (which was replaced by x's here) is correct and corresponds to your swap?

**Comment by vvs-** [comment]
Never mind. I can confirm that I can reproduce it. Here is the stage-1 log:
```
kernel: PM: Image signature found, resuming
kernel: PM: resume from hibernation
kernel: Freezing user space processes ... (elapsed 0.001 seconds) done.
kernel: OOM killer disabled.
kernel: PM: Marking nosave pages: [mem 0x00000000-0x00000fff]
kernel: PM: Marking nosave pages: [mem 0x0009f000-0x000fffff]
kernel: PM: Basic memory bitmaps created
kernel: PM: Using 1 thread(s) for decompression
kernel: PM: Loading and decompressing image data (138941 pages)...
kernel: PM: Image loading progress:   0%
kernel: PM: Image loading progress:  10%
kernel: PM: Image loading progress:  20%
kernel: PM: Image loading progress:  30%
kernel: PM: Image loading progress:  40%
kernel: PM: Image loading progress:  50%
kernel: PM: Image loading progress:  60%
kernel: PM: Image loading progress:  70%
kernel: PM: Image loading progress:  80%
kernel: PM: Image loading progress:  90%
kernel: PM: LZO decompression failed
kernel: PM: Read 555764 kbytes in 5.77 seconds (96.31 MB/s)
kernel: PM: Error -4 resuming
kernel: PM: Failed to load hibernation image, recovering.
```

**Comment by vanceism7** [comment]
Oh so is this actually an issue with nix then?

**Comment by vvs-** [comment]
I'm not sure. In some sense this could be an issue with NixOS kernel. AFAIK every distribution has its own kernel variant. Is there any distribution that uses vanilla kernel? Different versions, different patches, even different compiler versions. And vanilla kernel has its own set of bugs, of course, which might have some unofficial patches somewhere.

**Comment by vanceism7** [comment]
Hey wanted to report in, I managed to get hibernate working. For me, I had to add my swap device to the `boot.resumeDevice` entry in my `configuration.nix` file

e.g: (I followed the nix installation tutorial, so my swap is on `/dev/sda2`)
```
boot.resumeDevice = "/dev/sda2";
```

And now my hibernate is working fine

**Comment by vvs-** [comment]
Congrats. Then your bug is different from mine because according to my log above my swap _was_ used to restore hibernated image but the data were corrupt.

BTW, while testing you could use `resume=/dev/sda2` on a kernel command line even without specifying it explicitly in `configuration.nix`. This won't persist, though.
