### ISSUE TITLE
No kodi desktop manager option

### ISSUE THREAD

**Issue by stephenmw** [NixOS/nixpkgs#7057]
XBMC has services.xserver.desktopManager.xbmc.enable. XBMC was renamed to kodi with the release of version 14.0 and while there is now a kodi package, a desktop manager option has not been added for it.

**Comment by vcunat** [comment]
We seem to keep two versions in nixpkgs. Perhaps we do not need both options (anymore), at least for the desktop manager; but maintainers should know better than me: /cc @domenkozar, @titanous, @edwtjo.

**Comment by edwtjo** [comment]
As you said; there is a desktopManager in nixpkgs right now for both. There isn't one for kodi on any release channel though. I, at least, haven't made any deprecations yet as I think it would be prudent to keep both alongside for one major release.

**Comment by domenkozar** [comment]
+1 to remove xbmc if all plugins now work on kodi

**Comment by edwtjo** [comment]
All right, please review PR https://github.com/NixOS/nixpkgs/pull/7066.

The plugins work on Kodi, I use them all on my HTPC, where I run Kodi as a displayManager.

**Comment by edwtjo** [comment]
Will be included in the next release
