### ISSUE TITLE
tensorflow 2.0.0

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#70605]
Tensorflow 2.0 has been [released](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0). Unfortunately I don't have the compute resources to make the update and debug it myself. @jyp @abbradar is one of you up for the challenge?

**Comment by danieldk** [comment]
It would be nice if 1.14 was still available as well. 1.x -> 2.0 is quite a big transition due to the removal of tf.contrib. There will also be another 1.x release:

https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0-rc2

**Comment by lovesegfault** [comment]
Tensorflow 1.15 will be the last release in the 1.x series, and it should be kept in the tree since 2.x is a major breaking change.

**Comment by timokau** [comment]
WIP PR [here](https://github.com/NixOS/nixpkgs/pull/70910), help and comments welcome.
