### ISSUE TITLE
perl-PerlMagick-6.87 doesn't compile

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7077]
Citing from http://hydra.cryp.to/build/700620/nixlog/1/raw:

    cc  -L/usr/local/lib -lMagickCore-6.Q16 -shared -O2 -L/nix/store/6k9z1sfl7kghmagwd205k3i81pbcw57s-glibc-2.21/lib -fstack-protector  Magick.o  -o blib/arch/auto/Image/Magick/Magick.so 	\
       -lm  	\

    /nix/store/1j0vizfh6kalnkxjbchladh2f2q3wrgf-binutils-2.23.1/bin/ld: cannot find -lMagickCore-6.Q16
    collect2: error: ld returned 1 exit status

**Comment by wkennington** [comment]
Fixed via b058f829d2ffd48d51d03761300d18742835fca1
