### ISSUE TITLE
LXQt has wrong/invalid defaults

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixpkgs#70780]
## Issue description
 
LXQt has invalid default default settings, giving it a black-on-black theme, e.g. the clock in the panel is not readable (black font on black bg) and the background image is missing.
(default points to /nix/store/w2xzdhvlq9bz4kd6s298gjy6dlssdq37-lxqt-build-tools-0.6.0/share/lxqt/themes/frost/lxqt-origami-light.png while it should be sth matching /nix/store/*-lxqt-themes-0.14.0/share/lxqt/themes/frost/lxqt-origami-light.png)
Further, Themes are not listed and changing the panel theme has no effect.

The issue reminds of https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1781392 though I am not knowledgeable enough to confirm this.

### Steps to reproduce

configuration.nix:
```
  # Enable the LXQt Desktop Environment.
   services.xserver.displayManager.sddm.enable = true;
   services.xserver.desktopManager.lxqt.enable = true;
   services.xserver.autorun = true;
```
`lxqt.lxqt-themes` is listed in `environment.systemPackages`

## Technical details

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.76, NixOS, 19.09beta606.3ba0d9f75cc (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta606.3ba0d9f75cc, unstable-20.03pre194293.2436c27541b"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Known issue @wamserma, see https://github.com/NixOS/nixpkgs/pull/65482 (just forgot to report it :sweat_smile:)

**Comment by wamserma** [comment]
Ah, I only searched for open PRs..
Let's also Cross-Ref https://github.com/NixOS/nixpkgs/issues/65399 here.

**Comment by wamserma** [comment]
Fixed the wallpaper, panel/theme issue still applies (LXQt 0.15.0)

**Comment by tpwrules** [comment]
Have you discovered a way to fix this? The issue also applies using lightdm.

**Comment by romildo** [comment]
I would like to ask maintainers of the Qt libraries in nixpkgs to take a look at this issue, if possible. Maybe they can help in fixing this issue, which exists since LXQt was changed to use qt5's `mkDerivation` (https://github.com/NixOS/nixpkgs/pull/65482).

cc @ttuegel @periklis @bkchr @qknight @doronbehar @FRidh
