### ISSUE TITLE
boot.initrd.prepend fails to find file

### ISSUE THREAD

**Issue by parenthetical** [NixOS/nixpkgs#70810]
**Describe the bug**
Including files in the initrd via `boot.initrd.prepend` doesn't seem to work.

**To Reproduce**
I have the following to load a patched DSDT as described in #38352.
```
boot.loader.systemd-boot.enable = true;
boot.initrd.prepend = [ "/boot/s3_fix" ];
...
```
However, `nixos-rebuild --install-bootloader switch` fails with the following:
```
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/lmb1a0qd52cldg93z507bmbdvlrnk4lm-systemd-boot-builder.py.drv
  /nix/store/s6x7nyln3z9bh5yf0rmxa5bm85smiyak-initrd-linux-5.3.5.drv
  /nix/store/vw677xn4472ql4nwvyp3pdjvipi66m2b-nixos-system-crablet-20.03pre196201.07d4df59626.drv
building '/nix/store/lmb1a0qd52cldg93z507bmbdvlrnk4lm-systemd-boot-builder.py.drv'...
building '/nix/store/s6x7nyln3z9bh5yf0rmxa5bm85smiyak-initrd-linux-5.3.5.drv'...
cat: /boot/s3_fix: No such file or directory
builder for '/nix/store/s6x7nyln3z9bh5yf0rmxa5bm85smiyak-initrd-linux-5.3.5.drv' failed with exit code 1
cannot build derivation '/nix/store/vw677xn4472ql4nwvyp3pdjvipi66m2b-nixos-system-crablet-20.03pre196201.07d4df59626.drv': 1 dependencies couldn't be built
error: build of '/nix/store/vw677xn4472ql4nwvyp3pdjvipi66m2b-nixos-system-crablet-20.03pre196201.07d4df59626.drv' failed
```
The file is there:
```
 $ ls -l /boot/s3_fix 
-rwxr-xr-x 1 root root 166912 Oct  8 23:53 /boot/s3_fix
```
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5, NixOS, 20.03pre196201.07d4df59626 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre196201.07d4df59626"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mogorman** [comment]
have same bug

**Comment by mogorman** [comment]
I was able to solve it by doing ${pathtofile} I think it would help if more examples explained this. but not really a bug.

**Comment by parenthetical** [comment]
That worked, thanks.

**Comment by parenthetical** [comment]
That worked, thanks.

**Comment by SaltyKitkat** [comment]
> I was able to solve it by doing ${pathtofile} I think it would help if more examples explained this. but not really a bug.

I've met the same problem while I'm new to nixos and have no idea about "doing ${pathtofile}".
Would you please give more information about that?

**Comment by SaltyKitkat** [comment]
It seems that I've got it.
I'm doing something like this now, and it works!
```nix
{pkgs, ...}:
{
  nixpkgs = {
    overlays = [
      my_patch = {
        initrd = /etc/nixos/patch_initrd;
      };
    ];
  };
  boot.initrd.prepend = ["${pkgs.my_patch.initrd}"];
  # other things...
}
```

**Comment by akaihola** [comment]
@SaltyKitkat there's a syntax error in your example – the equals sign inside the list.

**Comment by itsfarseen** [comment]
For newbies like me:  `${pathtofile}` means `${"/boot/s3_fix"}`.
