### ISSUE TITLE
Java and Java applications fail due to flaky java agents in JAVA_TOOL_OPTIONS

### ISSUE THREAD

**Issue by berdario** [NixOS/nixpkgs#7082]
This is an issue that affects out-of-the-box Ubuntu+Nix installations. `java -version` fails, `lein repl` fails, other things fail as well (weirdly, `scala` doesn't fail... maybe it explicitly ignore Java agents?)

The latest version of Ubuntu ships with jayatana: a .jar that integrates java apps in the Ubuntu global menu bar... it depends on libX11.so.6, which is not directly available to Nix's Java and thus cause it to fail

```
dario@curie /tmp> java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jayatana/libjayatanaag.so: libX11.so.6: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at com.jarego.jayatana.Agent.premain(Agent.java:85)
    ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
fish: Job 1, “java -version” terminated by signal SIGABRT (Abort)
dario@curie /tmp [134]> 
```

So, the problem is quite straightforward, and can be worked around with `env JAVA_TOOL_OPTIONS="" java -version`. But it'd be best to find a way to leave an usable Java for the user right away.

Maybe, the Nix-installed java could deploy a wrapper that checks and sanitize such java-agents (reporting warnings when needed). After all Nix should make every dependency explicit, and if java agents are used as a way to add optional dependencies, these should be disabled.

That wrapper wouldn't affect java agents manually specified on the command line, and if an user explicitly specified some agents to be loaded in JAVA_TOOL_OPTIONS, those could always be moved to an explicit command line invocation, or by defining a nix expression that installs Java and includes that java agent in a location accessible to Nix.

**Comment by berdario** [comment]
FYI, I checked with the old Ubuntu 14.10, and I confirmed that jayatana was not shipped with it. When I found this bug Ubuntu 15.04 was still in Alpha, but it's now out officially. I fear that now it'll be more likely for new users to stumble upon this issue.

**Comment by teymuri** [comment]
i get also errors while i try to use seesaw in lein repl (the problem is described here: http://stackoverflow.com/questions/31632675/geting-error-using-seesaw-on-the-lein-repl?noredirect=1#comment51256967_31632675) Is there a way to fix this? I am using ubuntu 15.

**Comment by kno10** [comment]
Stupid Ubuntu bug that breaks many many many Java applications:

https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1441487
https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1427280

Uninstall jayatana, and encourage the Ubuntu people to get rid of this broken package.

**Comment by Profpatsch** [comment]
(triage) is this still a problem?

**Comment by berdario** [comment]
@Profpatsch 

[Ubuntu disabled jayatana by default](http://www.webupd8.org/2015/10/ubuntu-1510-and-1504-update-disables.html) (luckily they still ship it in `/usr/share/java/jayatanaag.jar`, which is useful for deb-installed Java applications, so they have less of an ugly UI by manually enabling the agent for them)

My comment still stands:

> the Nix-installed java could deploy a wrapper that checks and sanitize such java-agents (reporting warnings when needed). After all Nix should make every dependency explicit, and if java agents are used as a way to add optional dependencies, these should be disabled.

**Comment by Profpatsch** [comment]
(triage) maybe it has been implemented by now? I not, would you be interested in preparing a pull request?
