### ISSUE TITLE
perl5.30.0-Gtk2-1 fails to build

### ISSUE THREAD

**Issue by username1001101** [NixOS/nixpkgs#70829]
**Describe the bug**
```
Test Summary Report                                                                                                                                                                       
-------------------                                                                                                                                                                       
t/GdkPixbuf.t                    (Wstat: 256 Tests: 112 Failed: 1)                                                                                                                        
  Failed test:  44                                                                                                                                                                        
  Non-zero exit status: 1                                                                                                                                                                 
Files=228, Tests=1094, 65 wallclock secs ( 0.87 usr  0.30 sys + 32.58 cusr 22.25 csys = 56.00 CPU)                                                                                        
Result: FAIL                                                                                                                                                                              
Failed 1/228 test programs. 1/1094 subtests failed.                                                                                                                                       
make: *** [Makefile:3704: test_dynamic] Error 255                                                                                                                                         
builder for '/nix/store/b5lr3y61mcwgsycdrfav9hd59psmclkq-perl5.30.0-Gtk2-1.24992.drv' failed with exit code 2                                                                             
cannot build derivation '/nix/store/8pjhy6cmv29p2nm2jwwncld0cck0ygmz-pcsc-tools-1.5.4.drv': 1 dependencies couldn't be built                                                              
cannot build derivation '/nix/store/wvs1a0c915dx5lk73pwanw23v492vnc8-system-path.drv': 1 dependencies couldn't be built                                                                   
cannot build derivation '/nix/store/5by25115x5mrlm82wdvaaxlrdw75hqy3-nixos-system-subi-20.03.git.c67a7b0.drv': 1 dependencies couldn't be built                                           
error: build of '/nix/store/5by25115x5mrlm82wdvaaxlrdw75hqy3-nixos-system-subi-20.03.git.c67a7b0.drv' failed
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`                                                                                                                                                               
 - host os: `Linux 5.3.1, NixOS, 20.03pre194828.4c07c0fdf03 (Markhor)`                                                                                                                    
 - multi-user?: `yes`                                                                                                                                                                     
 - sandbox: `yes`                                                                                                                                                                         
 - version: `nix-env (Nix) 2.3`                                                                                                                                                           
 - channels(hyper): `"nixos-19.09pre185402.5eac339829b"`                                                                                                                                  
 - channels(root): `"nixos-20.03pre196308.a795e561f76"`                                                                                                                                   
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jerith666** [comment]
I've also encountered this.  I bisected it to 9baa018e2370dbd71e4dafc9d1393b9b0bb17fcb.

https://metacpan.org/release/Gtk2 says there's a newer version (1.24993) whose release notes say "Fix two test failures on newer versions of gtk+/gnome-shell/mutter".  However, updating to it does not fix this test failure.  :(

With 1.24993, the exact failure I'm getting is:

```
t/GdkPixbuf.t ...................... 1/112 
#   Failed test 'Don't crash on partial pixmap data'
#   at t/GdkPixbuf.t line 126.
GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at t/GdkPixbuf.t line 185.
GdkPixbuf-LOG **:       Encoding rle at t/GdkPixbuf.t line 185.
GdkPixbuf-LOG **:       Dimensions: 4 x 5 at t/GdkPixbuf.t line 185.
GdkPixbuf-LOG **:       Rowstride: 16, Length: 91 at t/GdkPixbuf.t line 185.
GdkPixbuf-LOG **:       Copy pixels == true at t/GdkPixbuf.t line 185.
# Looks like you failed 1 test of 112.
```

**Comment by worldofpeace** [comment]
When updating to GNOME 3.34 I did indeed notice this and tried the exact things @jerith666 did.
We probably need to report it so it can be fixed, I just didn't have the time to do this.

Guess the testsuite could be disabled.

**Comment by jerith666** [comment]
Disabling tests got it to build for me.  I'll try to find some time to open a PR for that, and to report it upstream.

**Comment by jerith666** [comment]
Reported upstream: https://rt.cpan.org/Public/Bug/Display.html?id=130742
