### ISSUE TITLE
Initrd size regression

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#7085]
The initial ramdisk has gotten much bigger between 14.12 and 15.05.

14.12:
```
$ du $(nix-build nixos/tests/login.nix -A nodes.machine.config.system.build.initialRamdisk)
5852    /nix/store/y2zbpv2iff1r593j36wgmddzlbrajj30-initrd
```

15.05:
```
$ du $(nix-build nixos/tests/login.nix -A nodes.machine.config.system.build.initialRamdisk)
18880   /nix/store/v0vgkqf5dqay9cmvygmnh1q2xdsyb574-initrd
```

**Comment by domenkozar** [comment]
What commit did you use for 15.05?

**Comment by wkennington** [comment]
At first I thought this was due to my initrd changes but the size barely
changes after reverting. It seems to have happened in the past week of
commits though.

**Comment by edolstra** [comment]
`linux-headers` and `glibc` are in the initrd now.

**Comment by edolstra** [comment]
Aha, it's caused by mdadm.

**Comment by edolstra** [comment]
See 666cf992f05d20c537da7f495afe3622023495d2, I reverted the mdadm update to 3.3.2 a few months ago for exactly this reason.

**Comment by wkennington** [comment]
Why are linux-headers in the initrd?

**Comment by edolstra** [comment]
Because glibc depends on them.

**Comment by wkennington** [comment]
I don't really see why the self reference would cause glibc to be pulled
into the initrd? What does the dependency resolution here? Also, shouldn't
this have been caught in stage-1.nix line 33?

Because glibc depends on them.

—
Reply to this email directly or view it on GitHub
<https://github.com/NixOS/nixpkgs/issues/7085#issuecomment-87746869>.

**Comment by domenkozar** [comment]
@wkennington: glibc->linux headers dependency is solved in closure-size branch, I think we should start cherry-picking stuff :)

**Comment by vcunat** [comment]
Right now it reports ``11296``, which is not so bad (on recent master, f93a8ee1).

**Comment by edolstra** [comment]
Closing as the initrd on master is now 5.7 MB.
