### ISSUE TITLE
Package request: cargo-udeps

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#70892]
**Project description**
cargo-udeps finds unused dependencies in Cargo.toml.

**Metadata**

* homepage URL: https://github.com/est31/cargo-udeps
* source URL: https://github.com/est31/cargo-udeps
* license: MIT or Apache License 2.0
* platforms: all

If we continue not packaging Rust nightly, this will only be possible after https://github.com/est31/cargo-udeps/issues/4 is fixed.

**Comment by B4dM4n** [comment]
I packaged the latest release of `cargo-udeps`.
Despite the mentioned issue still not being resolved, `cargo-udeps` compiles and runs fine with current stable rust (`rustc-1.38.0`).

To try the package you can use:
```shell
nix run -f https://github.com/B4dM4n/nixpkgs/archive/cargo-udeps.tar.gz cargo-udeps -c cargo-udeps
```

**Comment by ivan** [comment]
This was added in #73259
