### ISSUE TITLE
19.09 qsynth

### ISSUE THREAD

**Issue by kisacokac** [NixOS/nixpkgs#70901]
```
$ qsynth
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

Probably: https://github.com/NixOS/nixpkgs/issues/65399
See: https://nixos.wiki/wiki/Qt#qt.qpa.plugin:_Could_not_find_the_Qt_platform_plugin_.22xcb.22_in_.22.22

**Comment by bjornfor** [comment]
Thanks for reporting. Fixed in master (3fc66462dee4f90608b25b0db8950230906bdf5b) and release-19.09 (dbad7c7d59f12e81032bc3100e3d9fa44b6d4e70).
