### ISSUE TITLE
Bazel does not read /etc/bazelrc

### ISSUE THREAD

**Issue by guibou** [NixOS/nixpkgs#70911]
**Describe the bug**

By default and according to bazel documentation (https://docs.bazel.build/versions/master/guide.html#where-are-the-bazelrc-files), bazel is looking for a system-wide configuration is `/etc/bazel.bazelrc`.

In ba327a54b67732a715cc4237f5de20411b635319 I decided to override this path and make it point in `$out/etc/bazelrc`. It was the easiest solution to pass arguments to bazel in order to fix a few runtime issues.

However it breaks the assumption that user can configure bazel using `/etc/bazel.bazelrc`.

**To Reproduce**

- Use bazel from nixpkgs with `nix run nixpkgs.bazel`.
- Set some bazel settings in your `/etc/bazel.bazelrc` file
- Observe that bazel ignores this file

**Expected behavior**

I'm opening this bug report to discuss what should be the expected behavior here? Should we respect the `/etc/bazel.bazelrc`? If yes, I'll open a pull request to restore the previous behavior.

**Comment by flokli** [comment]
I'll be in favour of keeping support for all paths specified in the documentation - having a system-wide `/etc/bazel.bazelrc` is something people might want to make use of, so we shouldn't take away that possibility.

We currently set the following options in bazelrc:
```
      build --distdir=${distDir}
      fetch --distdir=${distDir}
      build --copt="$(echo $NIX_CFLAGS_COMPILE | sed -e 's/ /" --copt="/g')"
      build --host_copt="$(echo $NIX_CFLAGS_COMPILE | sed -e 's/ /" --host_copt="/g')"
      build --linkopt="-Wl,$(echo $NIX_LDFLAGS | sed -e 's/ /" --linkopt="-Wl,/g')"
      build --host_linkopt="-Wl,$(echo $NIX_LDFLAGS | sed -e 's/ /" --host_linkopt="-Wl,/g')"
      build --host_javabase='@local_jdk//:jdk'
      build --host_java_toolchain='${javaToolchain}'
```

We should either patch these as defaults into nixos, or introduce reading from a distro-provided location (should be coordinated with bazel upstream).

I think adding a wrapper is a bit too much for all these options.
