### ISSUE TITLE
GTK3 / XFCE 4.14 Adwaita and Adwaita-dark theme has colors mixed up

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#70922]
Maybe related to #68977.

![Screenshot_2019-10-10_13-33-30](https://user-images.githubusercontent.com/106511/66594369-0506c780-eb67-11e9-9e3c-a3330f5d4ee4.png)

If you look at this screenshot you can see that the hexchat text box has a blue color, which is supposed to be the "selection" color. When I select text in the text box, I cannot see it, because it is the same color as the background.

Further, if you look at the task bar, that is a CPU graph, and you can see that one of the bars is 100%. However it is difficult to see because instead of being the blue color, it is the gray color. In fact these colors are exactly swapped - the hexchat text box should be the color of the cpu graph bar and vice versa.

This is a regression after doing a `nixos-rebuild switch --upgrade` in the unstable channel, from `19.09pre192418.e19054ab3cd` to `20.03pre196201.07d4df59626`.

**To Reproduce**
1. `services.xserver.desktopManager.xfce4-14.enable = true;`
2. add hexchat and     xfce.xfce4-cpugraph-plugin to system packages
3. select Adwaita-dark in the Appearances settings

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.20, NixOS, 20.03pre196201.07d4df59626 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre196201.07d4df59626"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by symphorien** [comment]
On 19.09beta644.4382a143214 (Loris) with xfce-4.14 (no desktop) I get black text on white background, even with adwaita-dark selected (thunar has white text on dark background text entries, as expected).

**Comment by andrewrk** [comment]
I get the same behavior as you with thunar. I tried deleting `.config/hexchat/colors.conf` and restarting hexchat, and now it has black text that turns white when selecting, but the black text is difficult to see because of the blue selection.

![Screenshot_2019-10-10_14-34-48](https://user-images.githubusercontent.com/106511/66596575-25d11c00-eb6b-11e9-98e1-3b81b718db1b.png)

Here I have selected the second half of the input box. The problem goes away when the box is not focused.

Did you try the CPU Graph plugin?

**Comment by symphorien** [comment]
> Did you try the CPU Graph plugin?

I use xfce with i3 and without the desktop part of xfce, so I "can't".

**Comment by worldofpeace** [comment]
It should also be noted we upgraded to GNOME 3.34 on master.

**Comment by jtojnar** [comment]
I see this issue in file chooser dialogue in Inkscape (the only other GTK 2 app I use is GIMP, which ships a custom theme so it is not affected).

**Comment by worldofpeace** [comment]
@jtojnar Did you mention this had something to do with `GTK_PATH`?

**Comment by jtojnar** [comment]
Yup, unsetting `GTK_EXE_PREFIX` and `GTK_DATA_PREFIX` will fix that.

**Comment by worldofpeace** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/dd050270c78a0e214ed7cb9e25bae43b45406473

**Comment by andrewrk** [comment]
Confirmed, fixed! Whew, what a relief.
