### ISSUE TITLE
Upgrade 19.03 -> 19.09: udev-rules fails to build

### ISSUE THREAD

**Issue by tmplt** [NixOS/nixpkgs#70934]
**Describe the bug**
Upgrading from 19.03 to 19.09 building `udev-rules` fails:
```
output '/nix/store/mvr7sarg9xg7m3bcglb1wdl9a1xnfais-udev-rules' is not allowed to refer to the following paths:
  /nix/store/2i0zwf4ax58799sd5smswn2r2wxrgxyh-mdadm-4.1
  /nix/store/8h3bgs39dhwkbyb8ii1fbb6zrcp4kd1p-coreutils-8.31
  /nix/store/a06zhnqhx12g4kyfcf1zyca9bhsaspc2-util-linux-2.33.2-bin
```
I have not applied any explicit settings to `services.udev`.

**Additional context**
System configuration I'm building: https://github.com/Tmplt/nixos-config/blob/19.09/systems/perscitia.nix

Full output of `nixops deploy`: https://gist.github.com/Tmplt/f595b0d8adab22729796bcaf9d24d31a

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173165.55b8860aa20 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173165.55b8860aa20, nixos-hardware"`
 - channels(tmplt): `"nixos-19.03.173553.6420e2649fa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
but the upgrade is pinned to https://github.com/NixOS/nixpkgs-channels/commit/9bbad4c6254513fa62684da57886c4f988a92092

**Comment by Tmplt** [comment]
This issue persists with https://github.com/NixOS/nixpkgs-channels/commit/8bf142e001b6876b021c8ee90c2c7cec385fe8e9.

**Comment by tmplt** [comment]
Unless I had a version missmatch between the pinned nixpkgs and `nix-channel`, my system now builds with https://github.com/NixOS/nixpkgs-channels/commit/c75de8bc12cc7e713206199e5ca30b224e295041.
