### ISSUE TITLE
race conditions from simultaneous autologin of nixos user in the install ISO

### ISSUE THREAD

**Issue by CMB** [NixOS/nixpkgs#70945]
This issue applies specifically to release 19.09 of the NixOS minimal
installation CD.  I have not noticed it in previous releases.

While remastering the NixOS 19.09 installation ISO to work under a Xen
environment for Prgmr.com customers,
I noticed that the nixos user was automatically logged in to three separate
consoles: ttyS0, hvc0, and tty1. Code in `/etc/profile` is ran at login for the
nixos user, and there are race conditions when this code is executed
concurrently for multiple simultaneous logins.
This leads to some baffling error messages like:

    ln: failed to create symbolic link '/home/nixos/.nix-profile': File exists
    rm: cannot remove '/home/nixos/.nix-defexpr': Is a directory

I did not notice that the races resulted in anything destructive happening,
but the error messages were enough to convince me that I should prevent the
nixos user from being logged in automatically on more than one console.
Since only the serial console is available to the sort of VPSes that will be
using the remastered CD, I worked around the issue by preventing autologin on
the extra consoles. It can be done by adding extra command line parameters to
the kernel command line, such as:

    systemd.mask=getty@tty1.service systemd.mask=serial-getty@hvc0.service

**Comment by CMB** [comment]
@zimbatm mentioning you here as requested.

**Comment by zimbatm** [comment]
Thanks for the report @CMB.

## Analysis

I can see the race condition in my [/etc/profile](https://gist.github.com/zimbatm/991883c07704f9c5f47c83a581812b3b). For example here:
```sh
  if ! [ -L "$HOME/.nix-profile" ]; then
      if [ "$USER" != root ]; then
          ln -s "$NIX_USER_PROFILE_DIR/profile" "$HOME/.nix-profile"
      else
          # Root installs in the system-wide profile by default.
          ln -s /nix/var/nix/profiles/default "$HOME/.nix-profile"
      fi
  fi
```
it's possible for two concurrent login shells to not have `$HOME/.nix-profile`, and then rate to create the symlink.

Same here:
```sh
  # Set up a default Nix expression from which to install stuff.
  if [ ! -e "$HOME/.nix-defexpr" -o -L "$HOME/.nix-defexpr" ]; then
      rm -f "$HOME/.nix-defexpr"
      mkdir -p "$HOME/.nix-defexpr"
      if [ "$USER" != root ]; then
          ln -s /nix/var/nix/profiles/per-user/root/channels "$HOME/.nix-defexpr/channels_root"
      fi
  fi
```

The source of this file seems to be coming from nix itself: https://github.com/NixOS/nix/blob/7d5716aeb9509615eb344d9d305902bfa8ee22f2/scripts/nix-profile.sh.in#L18-L52

And has been removed entirely in master as part of https://github.com/NixOS/nix/pull/3136

## Conclusion

Luckily the race-conditions only seem to cause error outputs but still produce correct results in both cases. I believe that this will be fixed automatically on the next nix 2.3 release.

/cc @grahamc

**Comment by CMB** [comment]
Thank you for looking into this @zimbatm.  I'm assuming it can probably be
closed.

**Comment by zimbatm** [comment]
yes let's close this
