### ISSUE TITLE
bash completion errors when completing systemd units

### ISSUE THREAD

**Issue by stephenmw** [NixOS/nixpkgs#7096]
I have bash completion enabled: programs.bash.enableCompletion = true;

When I type "sudo systemctl status ssh[tab]" the output is:

sudo systemctl status sshFailed to list unit files: Too many levels of symbolic links
d.service

While it printed that error to stderr, it still completed the rest (d.service). Press enter and it works. The issue is just the error appearing, everything else works.

**Comment by jeaye** [comment]
I'm having this issue as well, unfortunately. Any updates, @stephenmw?

**Comment by Profpatsch** [comment]
(triage) can you try again? the symbolic link problem should have been solved a while ago.

**Comment by 0xABAB** [comment]
@Profpatsch This is broken in another way now. 

`journalctl -u zf<press tab>` results in an unresponsive shell for at least 1 minute (until Control-C is pressed) on an otherwise fast system (and never returning the completions).

17.03.git.81fceb2 (Gorilla)

**Comment by c0bw3b** [comment]
Can't reproduce on 17.09 with any of these :
- `sudo systemctl status <tab>` -> warning to ask if I want to display all possibilities
- `sudo systemctl status a<tab>` -> propose acpid.service / alsa-store.service / atd.service ...      
- same two without sudo
- `journalctl -u <tab>`
- `journalctl -u u<tab>`
- those last two with sudo
