### ISSUE TITLE
issue conventions for indicating version bumps

### ISSUE THREAD

**Issue by itcowed** [NixOS/nixpkgs#7098]
as a nixpkgs user who is often interested in latest architectural changes and new packages, version bumps on issues and pull requests come across as spam. it would be great if there was a convention so one could easily filter them away

**Comment by vcunat** [comment]
We have labels ``new-package`` and ``update-package``. You can use those to filter things out, after someone applies the labels (I heard only those with push access can label issues/PRs, so the submitter typically can't).
