### ISSUE TITLE
spyder exec python processes which don't inherit the python path

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#70986]
**Describe the bug**

Spyder is unable to start IPython console because it cannot find the `spyder_kernel` module.

The exact error message is

```
/nix/store/...‑python3𔂭.7.4/bin/python3.7: Error while finding module specification for 'spyder_kernels.console' (ModuleNotFoundError: No module named 'spyder_kernels')
```

Digging into this reveals the issue is that the python module path for spyder3 is set by the injection of some python specific code at the start of it

```
import sys
import site
import functools
sys.argv[0] = '/nix/store/...-spyder-3.3.3/bin/spyder3'
functools.reduce(lambda k, p: site.addsitedir(p, k), [...big long list of paths...], site._init_pathinfo())
```

Paths set this way are not inherited by the python processes that the spyder3 program executes python process. Specifically, `strace -o log -ff -s 4096 spyder3` reveals

```
execve("/nix/store/...-python3-3.7.4/bin/python3.7", ["/nix/store/...-python3-3.7.4/bin/python3.7", "-m", "spyder_kernels.console", "-f", "/run/user/1000/jupyter/kernel-5a6e5c644048.json"], 0x4b2f4b0 /* 104 vars */) = 0
```

**To Reproduce**

```
$ nix run nixpkgs.spyder
$ spyder3
```

The IPython console window will come up with a bright red box with the error message

```
/nix/store/...‑python3𔂭.7.4/bin/python3.7: Error while finding module specification for 'spyder_kernels.console' (ModuleNotFoundError: No module named 'spyder_kernels')
```

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.03.173408.bd6ba87381e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173408.bd6ba87381e, unstable-19.09pre182724.3674ff05ecd"`
 - channels(tyson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by twhitehead** [comment]
I've been digging into this some more. I believe a reasonable way forward would be to patch the [`get_python_executable` function](https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/misc.py#L156) in `spyder/utils/misc.py`, which
 I believe this provides the [default python program for launching the kernel](https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/ipython/kernelspec.py#L37), to return a nix appropriate python wrapper.

A further idea  would be to make the package set this kernel uses be specified in the derivation (either by specifying the entire thing or a package selection lambda) so users to specify the package set they want to use inside of spyder.

The downside would be you would get an entire new spyder install everytime. Unfortunately there doesn't seem to be any way to specify it on the command line though. An optimization might then be to patch this function to pull it from an environment variable. Top-level `spyder3` could then just be a wrapper that sets this environment variable before calling the real `spyder3`.

Anyways, should probably worry about walking before running.

**Comment by twhitehead** [comment]
[Here is an example](https://github.com/twhitehead/nixpkgs/commit/21c3fcd9e38819588531fc459563fd3aaa78267d) of what I was thinking of. I can't actually test this against the `19.09` or `master` branches as the `spyder` no longer compiles due to `pyqt` having been moved  to 5.13.

```
  Collecting pyqt5<=5.12; python_version >= "3" (from spyder==3.3.3)
    ERROR: Could not find a version that satisfies the requirement pyqt5<=5.12; python_version >= "3" (from spyder==3.3.3) (from versions: none)
  ERROR: No matching distribution found for pyqt5<=5.12; python_version >= "3" (from spyder==3.3.3)
```

I tested something similar against the 19.03 branch, and it worked okay though.

**Comment by FRidh** [comment]
For Jupyter we have a function to compose kernels. I suppose we should do something similar with Spyder.

**Comment by twhitehead** [comment]
I think that sounds like a reasonable thing. I've been checking a bit on the pyqt 5.13 restriction. Looks like it is a known works and not a known doesn't work thing. There is no next release yet with a lesser restriction, so I'm just going to remove this one and see if it works. I expect it will.

**Comment by twhitehead** [comment]
All right. Seems I must have been crossing my versions somewhere as the pyqt 5.13 restriction has already been addressed in master.

I've now fixed my changes to the point were they build a valid spyder. I've verified the `withPackages` override works in the sense the resulting package has the intended change in it.

Unfortunately I can't run it without (I expect) upgrading my system to something closer to master due what looks like some variant of this older #24256 issue.

**Comment by twhitehead** [comment]
I updated my system, cleaned it up a bit more, and verified that it works. I'll submit a pull request.

**Comment by FRidh** [comment]
In `spyder/utils/misc.py` the function `sys.executable` is used to obtain the path to the interpreter. This used to be problematic  for us, however, nowadays we actually set `sys.executable` in a `sitecustomize.py`. With 6e9743f120548a614cbba21ba1ff9fc06bca3a8b I get a functioning spyder and IPython shell
```sh
nix run "(import ./. {}).python3.withPackages(ps: with ps; [ spyder ])"
```

**Comment by FRidh** [comment]
I've backported the fix to 19.09 as well.

**Comment by twhitehead** [comment]
Thanks. The other issue would then be, what is a user suppose to do if the modules they need for their python code aren't included by spyder.?

For example, say I was writing some code that uses NLTK (native language toolkit). I put the following into the editor 

```
from nltk.tokenize import word_tokenize
 
print(word_tokenize("All work and no play makes jack dull boy. All work and no play makes jack a dull boy."))
```

and press the run button. The console says

```
runfile('/home/tyson/untitled0.py', wdir='/home/tyson')
Traceback (most recent call last):

...

  File "/home/tyson/untitled0.py", line 1, in <module>
    from nltk.tokenize import word_tokenize

ModuleNotFoundError: No module named 'nltk
```

**Comment by FRidh** [comment]
`nix run "(import ./. {}).python3.withPackages(ps: with ps; [ spyder nltk])"` ?

**Comment by twhitehead** [comment]
Ah right. Because it launches the sessions using the python on the path. Didn't think of that. :+1:
