### ISSUE TITLE
bazel: tests on macos fail

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#70994]
**Describe the bug**
Currently, `bazel.tests` fails (only on macOS):

```
src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/local_config_cc/cc_wrapper.sh, ...)": No such file or directory
INFO: Elapsed time: 3,476s, Critical Path: 0,06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
builder for '/nix/store/lzii536cvmaix1bnavmwwn5liha3vjl8-bazel-test-cpp.drv' failed with exit code 1
```

This was uncovered in https://github.com/NixOS/nixpkgs/pull/66723 and https://github.com/NixOS/nixpkgs/pull/69252, but seems to have been the case already earlier.

**To Reproduce**
`nix-build -A bazel.tests` on `x86_64-darwin`.

cc @kalbasit @uri-canva

**Comment by kalbasit** [comment]
I remember fixing this error in #63879, perhaps the patch is not longer working?

**Comment by flokli** [comment]
@kalbasit not sure if I understand the question. https://github.com/NixOS/nixpkgs/pull/71612 reads like all macos tests now run, so can this be closed?

**Comment by kalbasit** [comment]
@flokli actually Darwin was [skiped in that PR](https://github.com/NixOS/nixpkgs/pull/71612/files#diff-4746b81564a01e241a84d455575437e7R225).

I was running into this error before, the `No such file or directory` for an execvp call. When debugging that one, I found that it was an empty string `''`as the last argument which the call was parsing as a file. I'm wondering if this the same situation, passing [the flag `--verbose_failures` should reveal that](https://github.com/NixOS/nixpkgs/pull/63879#issuecomment-506584735).

**Comment by Profpatsch** [comment]
Successful on 1.1 https://logs.nix.ci/?key=nixos/nixpkgs.71612&attempt_id=ba03fe5f-1796-4924-99d5-5fb056866a7b
