### ISSUE TITLE
Unable to import xapian bindings in python.

### ISSUE THREAD

**Issue by cwoac** [NixOS/nixpkgs#7105]
Running 14.12 current. Relevant parts of configs:

````
  environment.systemPackages = with pkgs; [
    python27
    xapian
    xapianBindings
  ];

  nixpkgs.config =
  {
    xapian = {
      python = true;
      php = false;
      ruby = false;
    };
  };
````

The xapian modules have built OK, but when I run python and do `import xapian` I get a module not found. Looking through a strace of python I see it isn't looking in the xapian store directory.

Looking at the nix file for xapian I can see it is doing something that looks like it is trying to add itself to a search path, but my environment lacks anything that seems relevant. - Have I missed something I need to include in my environment / config somewhere? I couldn't see anything on the wiki...

**Comment by domenkozar** [comment]
It's because Python modules don't pollute the global `PYTHONPATH`. We'll have to document this better and provide instructions how to proceed from here on.

**Comment by bjornfor** [comment]
I still feel we should be able to have python pick up modules from system/default/user profiles. We just have to make sure that e.g. python2.7 only sees the 2.7 modules and so on. It doesn't have to use PYTHONPATH to do that.

**Comment by bjornfor** [comment]
To get a pure environment we can use ```nix-shell --pure```.

**Comment by domenkozar** [comment]
This is an issue of documentation. @cwoac did you read documentation in nixpkgs manual about Python?

**Comment by cwoac** [comment]
Okay, I'd read the python + pythontalk, but managed to miss the development environment section.
