### ISSUE TITLE
`No module named 'pkg_resources'` when running pwndbg

### ISSUE THREAD

**Issue by n4074** [NixOS/nixpkgs#71071]
**Describe the bug**
`pwndbg` fails to run because setuptools is no longer propagated implictly. If `pwndbg` were purely a python application built with `buildPythonApplication` then we would just need to add `setuptools` to propagatedBuildInputs and be done. However, `pwndbg` is not simply a Python application, but a wrapper around `gdb`, and isn't built using`buildPythonApplication`. The derivation patches the `gdbinit.py` script as follows:

```nix
 preFixup = ''
    sed -i "/import sys/a import sys; sys.path[0:0] = '$PYTHONPATH'.split(':')" \
      $out/share/pwndbg/gdbinit.py
  '';
```

This does result in the site-packages directories from all python packages ending up in sys.path, including setuptools (e.g. `/nix/store/03rhr26hsrkz9hbcqqyb84zhiiprl5d9-python3.7-setuptools-41.2.0/lib/python3.7/site-packages`). I'm not that familiar with Python packaging but from experimenting I found that the full path to the Python egg needs to be included (e.g. `/nix/store/03rhr26hsrkz9hbcqqyb84zhiiprl5d9-python3.7-setuptools-41.2.0/lib/python3.7/site-packages/setuptools-41.2.0-py3.7.egg`) in order for this method to work.

I made an attempt at resolving the issue but being new to Python packaging in Nix, neither are likely to be ideal:

We could use buildPythonPackage in place of mkDerivation, using `format = "other"` and use 

```nix
preFixup = ''
  patchPythonScript $out/share/pwndbg/gdbinit.py
'';
```

Or continue to use mkDerivation and manually set `program_PYTHONPATH` for patchPythonScript:

```nix
preFixup = ''
  program_PYTHONPATH=$PYTHONPATH patchPythonScript $out/share/pwndbg/gdbinit.py
'';
```
I'm happy to submit a PR but I'm not sure what the recommended solution is here.

**To Reproduce**
```shell
❯ nix-shell -p pwndbg

[nix-shell:~]# pwndbg
Traceback (most recent call last):
  File "/nix/store/18c6hhprssnjpp6yf7gh5gbrw1ih5h22-pwndbg-2019.01.25/share/pwndbg/gdbinit.py", line 37, in <module>
    import pwndbg # isort:skip
  File "/nix/store/18c6hhprssnjpp6yf7gh5gbrw1ih5h22-pwndbg-2019.01.25/share/pwndbg/pwndbg/__init__.py", line 13, in <module>
    import pwndbg.arch
  File "/nix/store/18c6hhprssnjpp6yf7gh5gbrw1ih5h22-pwndbg-2019.01.25/share/pwndbg/pwndbg/arch.py", line 12, in <module>
    from capstone import *
  File "/nix/store/p477mn568d5byj67khyf833pz3qm9l03-python3.7-capstone-3.0.5.post1/lib/python3.7/site-packages/capstone/__init__.py", line 201, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(gdb) 
```

**Expected behavior**
`gdb` should launch with the `pwndbg` extension loaded: 
```shell
❯ pwndbg                                 
pwndbg: loaded 167 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg>
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5, NixOS, 19.09.741.dbad7c7d59f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
 - pwndbg
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
It seems `pwndbg` is normally used by adding a `source $pwndbg/gdbinit.py` to `~/.gdbinit`, or calling `gdb` with `-q -x path/to/gdbinit.py` (what the wrapper registered in `installPhase` does).

This script then just does some `sys.path` addition calculations to register itself (we probably don't that at all) and some python 2 specific fixups, and then calls `import pwndbg`, which starts executing some code on import.

I'd suggest to package it as a regular python application first (via `buildPythonApplication`), so you can successfully import it inside a `python3.withPackages (ps: with ps; [ pwndbg ])`.

The python tooling should automatically take care of patching the python shebang properly if you make `$out/share/pwndbg/gdbinit.py` script executable.

**Comment by FRidh** [comment]
proposed fix https://github.com/NixOS/nixpkgs/pull/71219
