### ISSUE TITLE
Switching to 19.09 produces unpredictable interface names

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#71082]
**Describe the bug**
I recently switched from `nixos-19.03` to `nixos-19.09`, and my wireless network interface got renamed from `wlp3s0` to `wlan0`.

Wireless networking via `iwctl` stopped working after the switch.

Notice I didn't reboot, don't know if this would've helped things. Instead I reverted back to 19.03.  

**To Reproduce**

0. `ip l`
1. `nix-channel --remove nixos`
2. `nix-channel --add https://nixos.org/channels/nixos-19.09 nixos`
3. `nixos-rebuild --upgrade test`
4. `ip l`

**Expected behavior**
The interface retains its predictable name.

**Screenshots**

**Additional context**

**Metadata**
```
[root@foobar:/home/asymmetric/code/nixpkgs]# nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.78, NixOS, 19.03.173592.e758436f986 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173592.e758436f986, nixos-hardware"`
 - channels(asymmetric): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
It might not be related at all, but I'd personally recommend against using `nixos-rebuild switch` for large OS changes &ndash; in favor of `nixos-rebuild boot` (and reboot).  My experience is that it's significantly more difficult to apply large OS changes on a running system (and thus more buggy), and in any case I want to update the kernel from time to time :-)

**Comment by matthewbauer** [comment]
This may be caused by https://github.com/NixOS/nixpkgs/commit/1f03f6fc43a6f71b8204adf6cd02fb3685261add#diff-c1c886b16586c62e53e0d38c07f9bb6d. It's actually a fix for `networking.usePredictableInterfaceNames = true` (the default) not working properly, but may be surprising.

**Comment by flokli** [comment]
@asymmetric while `iwd` itself is quite experimental, they also mention iwd actively started managing network interfaces by themselves (removing and recreating as it pleases), so there's no guarantees these interface names stay stable:

https://iwd.wiki.kernel.org/interface_lifecycle

**Comment by flokli** [comment]
If not caused by iwd, I'd say this should be solely tracked in https://github.com/NixOS/nixpkgs/issues/71086.
