### ISSUE TITLE
libressl: pkg-config file has incorrect libdir

### ISSUE THREAD

**Issue by nmattia** [NixOS/nixpkgs#71107]
**Describe the bug**
The `pkg-config` files of libressl have an incorrect `libdir` which means that libressl libraries cannot be found when using `pkg-config --libs ssl`

**To Reproduce**

```
$ cat $(nix-build -A libressl.dev --argstr system x86_64-linux)/lib/pkgconfig/libssl.pc | head -n 5
#libssl pkg-config source file

prefix=/nix/store/n88xs31kc58m0j3sn6zxn1mz7a2pp5i2-libressl-2.9.2
exec_prefix=${prefix}
libdir=${exec_prefix}//nix/store/n88xs31kc58m0j3sn6zxn1mz7a2pp5i2-libressl-2.9.2/lib
```

note how `libdir` will expand to `/nix/store/n88xs31kc58m0j3sn6zxn1mz7a2pp5i2-libressl-2.9.2//nix/store/n88xs31kc58m0j3sn6zxn1mz7a2pp5i2-libressl-2.9.2/lib` whereas it should be `/nix/store/n88xs31kc58m0j3sn6zxn1mz7a2pp5i2-libressl-2.9.2/lib`.

CC @thoughtpolice @fpletz

**Comment by fpletz** [comment]
Also backported to 19.09.

**Comment by nmattia** [comment]
Yep, works like a charm. Thanks!
