### ISSUE TITLE
Brightness control broken in kde plasma on master

### ISSUE THREAD

**Issue by madhukar93** [NixOS/nixpkgs#71102]
# Missing brightness control in KDE
I can't control screen brightness in KDE(power management is enabled, but I don't see the brightness control in the power management widget. The brightness keys used to work as well, but now they aren't).
<img width="341" alt="kde-powermanagement" src="https://user-images.githubusercontent.com/7714050/66727419-9f635580-ee5c-11e9-9e4c-9a6eeb9dc484.png">

```
 powerManagement.enable = true;
 services.xserver.desktopManager.plasma5.enable = true;
```

Powerdevil, upower seem to be running without errors, although on startup -
```
journalctl -xb | grep brightness
Oct 09 08:47:25 blackbox kernel: thinkpad_acpi: This ThinkPad has standard ACPI backlight brightness control, supported by the ACPI video driver
Oct 09 08:47:25 blackbox kernel: thinkpad_acpi: Disabling thinkpad-acpi brightness events by default...
Oct 09 08:47:43 blackbox xsession[1343]: invalid metadata "/run/current-system/sw/lib/qt-5.12.3/plugins/powerdevilkeyboardbrightnesscontrolaction_config.so"
Oct 09 08:47:43 blackbox xsession[1343]: invalid metadata "/run/current-system/sw/lib/qt-5.12.3/plugins/powerdevilbrightnesscontrolaction_config.so"
Oct 09 08:47:45 blackbox xsession[1343]: powerdevil: Falling back to helper to get brightness
Oct 09 08:47:45 blackbox xsession[1343]: powerdevil: "DBus Backend error: service start org.kde.powerdevil.backlighthelper failed: Bus name not found in system service directory"

```
This seems like the relevant bit -
**powerdevil: "DBus Backend error: service start org.kde.powerdevil.backlighthelper failed: Bus name not found in system service directory"**

A **workaround** is to just specifically install powerdevil as a system package which installs a different version of the package that works

**system information**
```
nix-info
system: "x86_64-linux",
multi-user?: yes, 
version: nix-env (Nix) 2.3,
channels(root):
"nixos-20.03pre196201.07d4df59626, home-manager, nixos-hardware"

neofetch --stdout
xxx@blackbox
-----------------
OS: NixOS 20.03pre196201.07d4df59626 (Markhor) x86_64
Host: 20KGSBP200 ThinkPad X1 Carbon 6th
Kernel: 4.19.75
Uptime: 1 day, 4 hours, 16 mins
Packages: 1005 (nix-system), 1152 (nix-user)
Shell: zsh 5.7.1
Resolution: 2560x1440
DE: Plasma
WM: KWin
Theme: Breeze [GTK2]
Icons: breeze [GTK2]
CPU: Intel i5-8350U (8) @ 3.600GHz
Memory: 3920MiB / 15919MiB
```

**Comment by madhukar93** [comment]
PS: also been trying to understand the `xsession: invalid metadata` log lines

**Comment by worldofpeace** [comment]
Possibly related to #69150, though the error message makes me suspect it isn't.
#69150 never did provide any journal logs...

**Comment by madhukar93** [comment]
```
Oct 10 13:44:00 blackbox kernel: thinkpad_acpi: This ThinkPad has standard ACPI backlight brightness control, supported by the ACPI video driver
Oct 10 13:44:00 blackbox kernel: thinkpad_acpi: Disabling thinkpad-acpi brightness events by default...
Oct 10 13:45:30 blackbox xsession[2291]: invalid metadata "/run/current-system/sw/lib/qt-5.12.3/plugins/powerdevilkeyboardbrightnesscontrolaction_config.so"
Oct 10 13:45:30 blackbox xsession[2291]: invalid metadata "/run/current-system/sw/lib/qt-5.12.3/plugins/powerdevilbrightnesscontrolaction_config.so"
Oct 10 13:45:31 blackbox xsession[2291]: powerdevil: Falling back to helper to get brightness
Oct 10 13:45:31 blackbox xsession[2291]: powerdevil: current screen brightness value:  318
```
Don't see the DBus error after installing the package.
Invalid metadata error persists, though I don't see what effect they're having

**Comment by Vskilet** [comment]
Based on this https://wiki.archlinux.org/index.php/backlight I had my user (which is also a sudoers) in the video group. The slider and the ability to change brightness has returned. However, I'm not sure what the side effects can be, and if it's a good solution.

**Comment by worldofpeace** [comment]
I think that's expected @Vskilet if you're not in the video group. So I think your issue was different than this one.

**Comment by jerith666** [comment]
Yeah, I recently added myself to the `video` group so that I could use `acpilight` on the command line to work around this issue.  It did not fix this issue for me though.

**Comment by peterhoeg** [comment]
#69150 has fixed itself - assuming this has been fixed as well.
