### ISSUE TITLE
It’s easy to miss that nix-channel has different contexts

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#7113]
It took me a few hours of head scratching to find out, that nix-channel needs to be called as root to change the system channel. In hindsight that’s obvious, but it seems easy to miss.

I’m aware that this is a nix thing, but it mostly is of concern to NixOS I guess.

How about a message “switched to / added channel foo for user bar”? Since it’s an instant command I think it makes sense to break the rule of silence for that.

**Comment by jagajaga** [comment]
I can't understand your problem. If you have systemwide channel - surely you need to call `nix-channel` as root..

**Comment by globin** [comment]
I think this should be moved to https://github.com/nixos/nix

**Comment by Profpatsch** [comment]
You are right.
