### ISSUE TITLE
Update Fwupd

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#71140]
**Describe the bug**
We had to revert a patch because it doesn't apply to the current version https://github.com/NixOS/nixpkgs/commit/283ef6bc6d075f85f049299b11c0f5ef417a9553. 
And it's probably a good idea to do this anyway, fwupd moves pretty quickly.

Newest looking tag is https://github.com/fwupd/fwupd/releases/tag/1.3.2, though I don't I've seen them doing release simultaneously to https://github.com/fwupd/fwupd/releases/tag/1.2.11.

Changes can be found at https://github.com/fwupd/fwupd/blob/master/data/org.freedesktop.fwupd.metainfo.xml.

**Additional info**
Current Version: 1.2.10
Version to update to: 1.3.2

As previously mentioned, not sure what's going on with the `1.2.*` series.

**Comment by worldofpeace** [comment]
see also #71114

**Comment by jtojnar** [comment]
1.3 is a new stable series, 1.2.11 is a backport to a old stable branch.
