### ISSUE TITLE
Make `ec2.metadata = true` by default

### ISSUE THREAD

**Issue by onetom** [NixOS/nixpkgs#7115]
As suggested by @rbvermaa this option could be true by default. It isn't clear that this option is needed as it isn't documented anywhere.

It's useful because `awcli` or any custom developed services could automatically query http://169.254.169.254/latest/meta-data/iam/security-credentials/ for AWS credentials.

**Comment by copumpkin** [comment]
:+1: 

Keeping secrets in userdata is probably something we shouldn't encourage, and although there are cases where locking down access to the instance credentials makes sense, it's probably not the common case.

**Comment by Profpatsch** [comment]
triage: has this been changed?
