### ISSUE TITLE
haskellPackage.blas-ffi: wrong dependency of blas package

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#71182]
**Describe the bug**

The package `nixpkgs.haskellPackage.blas-ffi` has an Pkgconfig dependency to `pkgs.blas` 
([PkgConfig-Depends: blas](https://hackage.haskell.org/package/blas-ffi-0.1/blas-ffi.cabal)). But the dependency which gets injected is `pkgs.haskellPackage.blas`, which of course results in a failing build.

I used `pkgs.openblas` to make it kinda work. The author said, there are functions still missing. Anyway I'm not an expert here, maybe somebody else knows more about the way on how to use `blas` implementations and link them properly. 

[Here](https://github.com/mrVanDalo/haskell-lapack-nixos/blob/master/default.nix#L4) is my repository where I fiddled around with that topic. Originally I tried to fix `pkgs.haskellPackages.lapack`.

**Expected behavior**
`pkgs.haskellPackages.blas-ffi` should depend on `pkgs.blas` or `pkgs.openblas` (or maybe another blas implementation).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - haskellPackage.blas-ffi
  - haskellPackage.lapack
```

**Links**
* #42780 might be related to that issue.

**Comment by jonringer** [comment]
the expression seems to be pulling from pkgs.blas
```
  "blas-ffi" = callPackage
    ({ mkDerivation, base, blas, netlib-ffi }:
     mkDerivation {
       pname = "blas-ffi";
       version = "0.1";
       sha256 = "1zmw1x37ayssplj8w01ivfyh2jjg906c389cjah4hpn5dpb7p9w5";
       isLibrary = true;
       isExecutable = true;
       libraryHaskellDepends = [ base netlib-ffi ];
       libraryPkgconfigDepends = [ blas ];
       description = "Auto-generated interface to Fortran BLAS";
       license = stdenv.lib.licenses.bsd3;
       hydraPlatforms = stdenv.lib.platforms.none;
       broken = true;
     }) {inherit (pkgs) blas;};
```

**Comment by mrVanDalo** [comment]
True, but when I try to build it, I still get the error : 
`Setup: The pkg-config package 'blas' is required but it could not be found.`
When I replace `{inherit (pkgs) blas;}` with `{blas = pkgs.openblas;}` it compiles.

Maybe the header files are missing in `pkgs.blas` or not at the expected place.

**Comment by cdepillabout** [comment]
@mrVanDalo On my machine, this appears to be working on `master`?  Maybe someone fixed this in the last couple days?

```console
$ cd /some/path/to/nixpkgs/
$ git checkout master
$ git pull
$ nix-build -A haskellPackages.blas-ffi --arg config '{allowBroken=true;}'
...
/nix/store/nfl0q1xpqpf1rmnaih2c8zpd3invgil2-blas-ffi-0.1
```

**Comment by mrVanDalo** [comment]
Ok will try that out, but I currently have no time for creating such a pull request. I think I watched the video some weeks ago. But I have to watch it again of course.

**Comment by svmhdvn** [comment]
This builds on haskell-updates and isn't marked broken, can this issue be closed?

**Comment by jonringer** [comment]
@svmhdvn I agree, this  currently solved
