### ISSUE TITLE
Add a stdenv that doesn't depend on GCC

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#7118]
And use this in trivial builders like `writeText`. This will prevent commands like `nixos-rebuild switch` from pulling in GCC when nothing actually needs to be compiled.

The only problem is what to do with `runCommand`, since there might be a few uses that actually invoke gcc.

**Comment by copumpkin** [comment]
Yes! :+1: :+1: :+1:

**Comment by copumpkin** [comment]
@edolstra this isn't ideal, but it might be nicer than alternatives: adopt the Apple approach of putting a dummy `gcc` (or just `cc`) and related build tools in the path that do nothing but fail and tell you what to do if you want a proper environment. Not the best user experience, but better than a failure without help.

**Comment by Profpatsch** [comment]
(triage) was such a stdenv implemented in the meantime?

**Comment by cleverca22** [comment]
i can also see this being of use for situations like building a x86_64-linux derivation from darwin, writeText doesnt care about what os it gets ran on

**Comment by copumpkin** [comment]
@Profpatsch nope 😢

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/commit/0cb16a6955 this can be closed now?

**Comment by Ericson2314** [comment]
From @copumpkin also 97bfc2fac92d90c668ae1ec078356d0bd0a9ddb7

**Comment by Profpatsch** [comment]
Yes! I like this very much.
