### ISSUE TITLE
services.xserver.synaptics.enable=true causes exception while upgrading to 19.9

### ISSUE THREAD

**Issue by p-alik** [NixOS/nixpkgs#71194]
My first attempt to upgrade to 19.9 ended in exception while `nixos-rebuild switch --upgrade`:
https://github.com/NixOS/nixpkgs/blob/fa456e42094ad1f0b11bc07ce9800e3c6cd2bf54/nixos/modules/services/x11/hardware/synaptics.nix#L207
because I used synaptics driver only. Agains exception's message `libinput` was disabled at the rebuild time:
```
# nixos-option services.xserver.libinput.enable       
Value:
false
...
```

The issue could be solved by replacing `synaptics` with `libinput` `services.xserver.libinput.enable=true`

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.03.173592.e758436f986 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09.809.5000b1478a1"`
 - channels(palik): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by worldofpeace** [comment]
This means a module automatically enables it @p-alik.

Could you try?
```
services.xserver.libinput.enable = false;
services.xserver.synaptics.enable = true;
```

**Comment by p-alik** [comment]
> Could you try?
> 
> ```
> services.xserver.libinput.enable = false;
> services.xserver.synaptics.enable = true;
> ```

No exception if both are set explicitly as suggested. It seems [libinput's default](https://nixos.org/nixos/options.html#libinput.e) causes the exception, because without explicit `services.xserver.libinput.enable = false;` `nixos-rebuild` fails.
