### ISSUE TITLE
Package request: LibreDWG

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#71192]
**Project description**
> LibreDWG is a free C library to read and write DWG files.  This program is
part of the GNU project, released under the aegis of GNU.  
>  
> DWG is a file format created in the 70's for the emerging CAD applications.
Currently it is the native file format of AutoCAD, a proprietary CAD program 
developed by AutoDesk.

**Metadata**

* homepage URL: https://www.gnu.org/software/libredwg/  
* source URL: https://github.com/LibreDWG/libredwg/releases/tag/
* changelog: https://raw.githubusercontent.com/LibreDWG/libredwg/master/NEWS
* license: gplv3
* platforms: unix, linux, darwin, windows

**Comment by thorstenweber83** [comment]
I'm currently working on adding the package.
Would you be willing to be named as a maintainer?

**Comment by luzpaz** [comment]
Thanks!  
I can't, have too many other things on my plate.

**Comment by luzpaz** [comment]
bump
