### ISSUE TITLE
[19.09] swapDevices.*.randomEncryption possible entropy starvation during boot

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#71204]
**Describe the bug**
Since upgrading to 19.09, my laptop's boot process is delayed by about one minute due to entropy starvation during the boot process

**To Reproduce**
1. swap configuration:
 { device = "/dev/disk/by-id/yadayada-part2"; randomEncryption.enable = true; randomEncryption.source = "/dev/random"; }
2. [possibly configure other services that also need entropy during boot]
3. reboot

**Expected behavior**
A quick boot as in 19.03 with max 1 second used by the swap initalization.

**Screenshots**
$ systemd-analyze plot | fgrep mkswap
  <text class="left" x="1018.920" y="694.000">mkswap-dev-disk-byx2did-nvmex2dSamsung_SSD_970_EVO_2TB_S464NB0M401994Dx2dpart2.service (1min 723ms)</text>

**Additional context**
This is on physical hardware, not on VM. Replacing random with urandom leads to instant boot, but has the obvious problem with the missing entropy.

**Metadata**
# nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.09.830.496bdc7e334 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.830.496bdc7e334"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
swapDevices.*.randomEncryption
# a list of nixos modules affected by the problem
module: nixos/modules/config/swap.nix
```

**Comment by tokudan** [comment]
Basically there are two ways to fix this issue:
1) Find out why 19.03 had enough entropy but 19.09 seems to lack entropy during swap initialization and mitigate this
2) setup swap at a later time during boot, which obviously only works if the swap is not critical to the boot process

I'm going to work on this later, but if you have any ideas or suggestions, feel free to comment.

**Comment by teto** [comment]
I had a similar issue. it might be related to changes in the kernel ? I had a similar problem in VMs, managed to work around it with via `security.rngd.enable` (+virtio but you should only need this setting)

**Comment by tokudan** [comment]
rngd cannot solve this, as it starts after swap configuration and thus after the long delay.
It may be possible to move it to an earlier point in the boot process, as it just requires hardware devices that should be available before swap.
