### ISSUE TITLE
nftables: iif/oif startup problems

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#71227]
## Issue description

After upgrading to 19.09 my nftables based firewall wouldn't come up because interfaces were missing. Among these were my networkd based wireguard tunnels, which existed when I logged in. This is a regression from 19.03, probably because the `nftables.service` is started too early.

```
Oct 16 00:49:48 juno systemd[1]: Starting nftables firewall...
Oct 16 00:49:49 juno y5f8j3xifprskgby3k4c85p7v0h5qckh-nftables-check[487]: In file included from /nix/store/a4byfg2v2kpbh587aw50w5a0vz6lnylb-nftables-rules:3:1-69:
Oct 16 00:49:49 juno y5f8j3xifprskgby3k4c85p7v0h5qckh-nftables-check[487]: /nix/store/hq9yd8z7fgx2gmdg1m610c7zvfira58c-nftables-rules:19:19-31: Error: Interface does not exist
Oct 16 00:49:49 juno y5f8j3xifprskgby3k4c85p7v0h5qckh-nftables-check[487]:     iif { "ens3", "wg-ganymede", "wg-io" } meta l4proto { udp, tcp } @th,16,16 53 counter accept
Oct 16 00:49:49 juno y5f8j3xifprskgby3k4c85p7v0h5qckh-nftables-check[487]:                   ^^^^^^^^^^^^^
Oct 16 00:49:49 juno systemd[1]: nftables.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 00:49:49 juno systemd[1]: nftables.service: Failed with result 'exit-code'.
Oct 16 00:49:49 juno systemd[1]: Failed to start nftables firewall.
```

I found that post that describes the issue well:

> Please note that oif is in reality a match on the integer which is the index of the interface 
> inside of the kernel. Userspace is converting the given name to the interface index when the 
> nft rule is evaluated (before being sent to kernel). A consequence of this is that the rule can 
> not be added if the interface does not exist.
>
> An other consequence, is that if the interface is removed and created again, the match will 
> not occur as the index of added interfaces in kernel is monotonically increasing. Thus, oif is a 
> fast filter but it can lead to some issues when dynamic interfaces are used.
>
> It is possible to do a filter on interface name but it has a performance cost because a string 
> match is done instead of an integer match. To do a filter on interface name, one has to use
> oifname:

via https://home.regit.org/netfilter-en/nftables-quick-howto/

So in addition to the unit ordering issue mentioned above unless we restart `nftables.service` each time a new interface appears `oif` and `iif` matching is unreliable.

I migrated to `oifname` and `iifname` for now, which are a bit more expensive, but work reliably.

### Steps to reproduce

1. Use nftables for firewalling
```
{
  networking.nftables = {
    enable = true;
    ruleset = ''
      table inet filter {
        chain input {
          type filter hook input priority 0;
          iif lo accept
          ct state established,related accept
          ip6 protocol icmpv6 accept
          ip protocol icmp accept
          tcp dport ssh ct state new accept

          iif { "ens3", "wg-a", "wg-b" } meta l4proto { udp, tcp } @th,16,16 53 counter accept
        }
      }
    '';
  };
}
```

2. Create wireguard tunnels using systemd-networkd.
3. Reboot
4. The `nftables.service` will be started before the wireguard interfaces exist

## Technical details

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3, channels(root): "nixos-19.09.809.5000b1478a1, nixos-unstable-19.09pre192418.e19054ab3cd", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

**Comment by mweinelt** [comment]
> I migrated to oifname and iifname for now, which are a bit more expensive, but work reliably.

This is my takeaway. Just don't use `iif` and `oif`.

**Comment by openalmeida** [comment]
hi, @mweinelt 

use `iff` instead of `oif` not works for all, please check a situation below about ingress hook, the device option is required but NIC may bootup after nftables.service.

```
# nft
table netdev filter {
    chain wan_input {
        type filter hook ingress device "a_slow_nic" priority filter; policy accept;
        # all *wan interface should refuse dport 67 to avoid dhcp leaks
        udp dport 67 drop comment "proof dhcp service leaks to wan"
    }
}
```

I've got an urgly method when I found
`After=sys-subsystem-net-devices-_a_show_nic.device` was useless
and
`After=...-online.service` will leak connection which nft as a firewall is used to reject/drop.

```
# call `systemctl edit nftables.service` and apply content of these
[Service]
ExecStartPre=/bin/bash -c 'while ! /usr/sbin/ip link show a_slow_nic 2>/dev/null 1>&2; do sleep 0.03; done'
Restart=on-failure
RestartSec=5
TimeoutStartSec=10
# Type= set to oneshot is not allowed
# cos of systemd oneshot unit is a blocked opeartion which may hang up forever
Type=simple
```

**Comment by megheaiulian** [comment]
I think a better solution would be to have 2 firewalls. 
First start a basic more restrictive firewall  before 'network-pre.target'. Optionally this could have some anti-lockout fallback rules.
After network-online or wireguard or pppoe start the real firewall and that and can use iif, oif  and ingress or flowtable.

**Comment by paigeadelethompson** [comment]
Alternatively you can use wildcard names with `iifname` and `oifname` however it's the difference between using numeric indices for interface names (iif) and a string compare /  string expression. A third alternative: 

```
set fast_in_private_interfaces { 
  type iif; 
}

chain dont_you_love_my_chain_mane { 
  iif @slow_in_private_interfaces accept
  iifname "wlp*" accept
}
```

then later you can add iif's to the set from the command line as you please, but sets can be empty I made this work once but decided I didn't care about making the ruleset this abstract. It's still nice to know though and handy to say the least. 

Disclaimer: 
last I checked if you try to use wildcards in a set (eg a typeof iifname, nftables will sefault upon parsing; they may or may not have fixed this, but if you try to do that you definitely should check and make sure it's intended to work that way I don't think it is, it doesn't make a whole lot of sense to use a wildcard as a set element IMHO, but curiosity got the better of me once. 

Asides from the obvious difference in iif and iifname you also have to use typeof for iifname which I believe implies a higher level of abstraction is used; I could be mistaken but this might be the difference between a 5 tuple element (iif) which might be less expensive than unpacking to something more extract. I saw the information about the difference between the two somewhere but I can't find it at the moment. If it works for your purposes, cool I just thought I'd point this out in any case.

**Comment by paigeadelethompson** [comment]
Also my understanding is that if expense ever does become a deal killer for nftables, they have something called flowtables which helps you offload with cards that support fastpath though it may not be the solution you're looking for depending on what your needs are.
