### ISSUE TITLE
freeoffice: unable to unlock

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#71228]
**Describe the bug**

When `freeoffice` is run it asks to unlock the software, but the unlocking fails, as can be seen in the screenshots.

cc @danieldk 

**Screenshots**
![unlock1](https://user-images.githubusercontent.com/1217934/66917874-97d6b480-eff4-11e9-8a58-b93a028fc871.png)

![unlock2](https://user-images.githubusercontent.com/1217934/66917063-061a7780-eff3-11e9-8602-8bad94614d4f.png)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5, NixOS, 20.03pre196725.94500c93dc2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre196836.1c40ee6fc44"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by danieldk** [comment]
It's indeed `/bin/ls`. If I make a `/bin/ls` symlink, registration works. I get an error again when I remove the symlink.

**Comment by romildo** [comment]
It seems that this issue is back on unstable nixpkgs.

I am getting the following message with freeoffice-2018.978:

![Screenshot from 2020-10-16 15-55-10](https://user-images.githubusercontent.com/1217934/96297902-fd72cd80-0fc7-11eb-807a-51d55cc90fed.png)


cc @danieldk
