### ISSUE TITLE
python3: switch to python38 for 20.09

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#71220]
**Describe the bug**
Use `python38` as `python3` for 20.03.

1. Let Hydra build `python38Packages`
2. If sufficient packages work for 20.03 we can switch, otherwise we remain at 3.7.

**Comment by worldofpeace** [comment]
Also, a call to python package maintainers, we need to make sure your packages work with python38 for 20.03.

If you have PRs fixing this please reference this issue, or if you open an issue to reference it also.
That way we can track the status of this by viewing one long-running thread, or you can be notified here.

**Comment by jonringer** [comment]
For cross reference: https://github.com/NixOS/nixpkgs/pull/71222

**Comment by FRidh** [comment]
2dc4ab36772dfaf124af4d90e99c68038f46baa0

**Comment by jonringer** [comment]
@FRidh There's still plenty of the python ecosystem which doesn't support 3.8. Personally, I think this should have waited another month.

**Comment by FRidh** [comment]
Looking at `python37Packages` and `python38Packages` there wasn't much of a difference. Given the upcoming 20.03 release I do not want to wait another month with making such change or it would get too close to branch-off. Now we can see how many applications are compatible, and if its too few, we can always revert before branch-off.

**Comment by FRidh** [comment]
If we manage to have another staging cycle before branch-off, then we could give it another try, otherwise, we should postpone this to 20.09.

**Comment by jonringer** [comment]
There was quite a bit of deprecation that took place in python3.8. Personally I'm fine with floating python3 as python3.7 until 20.09

**Comment by FRidh** [comment]
This has been done. Need to check the documentation and changelog.

**Comment by schmittlauch** [comment]
@FRidh From the 20.03 changelog:

> Python 3 now defaults to Python 3.8 instead of 3.7. 

So I guess this can be closed.
