### ISSUE TITLE
/etc/sane.d/net.conf path collision

### ISSUE THREAD

**Issue by multun** [NixOS/nixpkgs#71236]
**Describe the bug**
sane-backends provides a /etc/sane.d/net.conf configuration file, which is also produced by https://github.com/NixOS/nixpkgs/blob/076860e0340a5e4a909b9a710e186508b14d1c90/nixos/modules/services/hardware/sane.nix#L20

**To Reproduce**
1. `hardware.sane.enable = true;`
2. `nixos-rebuild switch`
3. ```collision between `/nix/store/cji2dqdf44wz4vwml7h63p6w9dm1gq4c-net.conf/etc/sane.d/net.conf' and `/nix/store/l6wr98y9nvxmi6xy4v5xjwr80jg6n639-sane-backends-1.0.27/etc/sane.d/net.conf'```

**Expected behavior**
No file conflict

**Additional context**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.09pre191617.4e60699fa72 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-20.03pre196836.1c40ee6fc44"`
 - channels(multun): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sane-backends
# a list of nixos modules affected by the problem
module: modules/services/hardware/sane.nix sane
```

**Comment by peti** [comment]
Something isn't right there. I have `hardware.sane.enable = true` in my `configuration.nix`, but I have no `/etc/sane.d` whatsoever:

~~~
$ ls /etc/san*
zsh: no matches found: /etc/san*
~~~

**Comment by symphorien** [comment]
The sane config is not written to /etc but only pointed at by the `$SANE_CONFIG_DIR` environment variable.

**Comment by worldofpeace** [comment]
This is really just us being noisy about collisions, this one is harmless.

**Comment by multun** [comment]
@worldofpeace Even if it's harmless, what would be the preferred way of getting rid of this warning?

**Comment by worldofpeace** [comment]
It doesn't really serve any purpose for nixos users, so it was fine to remove.
