### ISSUE TITLE
Python 2.7.9 urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#7124]
I'm on OSX with the latest unstable nixpkgs release.

I'm getting the following error from a python script build with the default nixpkgs python (using buildPythonPackage):

```
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

How should I proceed to debug the issue? I guess changing to Python 2.7.8 (without SSL verification) would be a temporary fix, but I don't know how to change the default python version and cannot find a working documentation for it.

**Comment by domenkozar** [comment]
How can I reproduce?

**Comment by datakurre** [comment]
@domenkozar I'm sorry for not having a minimal case for this.

I have to following expression installed into my env to provide ``fullrelease`` cmd from ``zest.releaser``, and I get the error when I try to publish a package to pypi. This used to work and I'm not sure what has changed. I had to fallback to system python based virtualenv to get work done :(

```
with import <nixpkgs> { };

let dependencies = rec {
  zest_releaser = buildPythonPackage {
    name = "zest.releaser-3.52";
    src = fetchurl {
      url = "https://pypi.python.org/packages/source/z/zest.releaser/zest.releaser-3.52.zip";
      md5 = "8740e9cc58d794135cc540d7b168f24e";
    };
  };
  zest_pocompile = buildPythonPackage {
    name = "zest.pocompile-1.4";
    src = fetchurl {
      url = "https://pypi.python.org/packages/source/z/zest.pocompile/zest.pocompile-1.4.zip";
      md5 = "a40b0384d2f5dceb374170d7afc8e559";
    };
    propagatedBuildInputs = [
      python27Packages."python-gettext-1.2"
    ];
  };
  gocept_zestreleaser_customupload = buildPythonPackage {
    name = "gocept.zestreleaser.customupload-1.4";
    src = fetchurl {
      url = "https://pypi.python.org/packages/source/g/gocept.zestreleaser.customupload/gocept.zestreleaser.customupload-1.4.zip";
      md5 = "13383cb434c4f4a4c4e77db2b2d8df8a";
    };
    propagatedBuildInputs = [
      zest_releaser
    ];
  };
};

in with dependencies; buildPythonPackage {
  name = "zest.releaser-3.52";
  src = fetchurl {
    url = "https://pypi.python.org/packages/source/z/zest.releaser/zest.releaser-3.52.zip";
    md5 = "8740e9cc58d794135cc540d7b168f24e";
  };
  propagatedBuildInputs = [
    zest_pocompile
    gocept_zestreleaser_customupload
  ];
}
```

**Comment by domenkozar** [comment]
@datakurre I'll take a look once I get a chance. Thanks!

**Comment by domenkozar** [comment]
@datakurre what happens if you do `export SSL_CERT_FILE = ~/.nix-profile/etc/ca-bundle.crt`

**Comment by rushmorem** [comment]
@domenkozar I have just run into this issue while packaging `aurora`. The error still persists with `SSL_CERT_FILE` set. I'm running latest `nixos-unstable-small (15.06pre63074.6276eba)` so I don't think this is platform specific.

**Comment by domenkozar** [comment]
How can I reproduce?

**Comment by rushmorem** [comment]
Sorry, false alarm. For me this error was triggered by cache issues. Once I solved those, `aurora` builds fine using Python 2.7.9.
