### ISSUE TITLE
zathura: cannot open links

### ISSUE THREAD

**Issue by jlesquembre** [NixOS/nixpkgs#71249]
**Describe the bug**
After my last nixos update (I'm on nixos-unstable) I cannot open hyperlinks anymore with zathura, I get this error on the console: 
```
xdg-open: no method available for opening 'http://www.amazon.com/'
```

**To Reproduce**
1. Open a pdf with an hyperlink, e.g.: https://www.southcentralric.org/Downloads/Dos%20and%20Donts%20of%20ADA%20Compliant%20Hyperlinks.pdf
2. Try to open the link (press `f` and then `1`)
3. Nothing happens and there are some errors on the console

**Additional context**
Some months ago, I fixed the same issue on this PR:
https://github.com/NixOS/nixpkgs/pull/57291
but this time looks like the issue is cause for other reason and I don't know how to fix it

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.78, NixOS, 20.03.git.94500c9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-16.09.1787.e1874d0"`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by rnhmjoj** [comment]
Does executing `xdg-open` directly work?

**Comment by jlesquembre** [comment]
@rnhmjoj yes, executing `xdg-open 'https://www.amazon.com'` from the terminal works

**Comment by rnhmjoj** [comment]
I tried building zathura from nixpkgs master and running it (from 19.09) and it works.
It does so even when `BROWSER` is unset. This probably means it's either an issue in a recent version of `xdg-open` or something else in your setup but zathura looks fine.

**Comment by jlesquembre** [comment]
@rnhmjoj thanks a lot for testing, but I'm still getting the same issue.
There is something that works for me, I uncommented this line:

https://github.com/NixOS/nixpkgs/blob/d0d5884ba5695c16bae169598a792d93b2f67bc5/pkgs/applications/misc/zathura/core/default.nix#L27

and set it to `disable`, and now I can open the links. I don't understand why we get different results. I'm also using nixpkgs master.

**Comment by jlesquembre** [comment]
@rnhmjoj I think I know why, do you have 
```
set sandbox none
```
in your `zathurarc`?

**Comment by rnhmjoj** [comment]
> @rnhmjoj I think I know why, do you have [...] in your zathurarc?

No, sorry, I do not.

I've just built a NixOS VM and run zathura (so default config) in it: still works as expected.
If I were you I'd try to reproduce the bug by either stripping down your setup or by builting it gradually in a VM.

**Comment by jlesquembre** [comment]
@rnhmjoj thanks for your help, since looks like the problem is something with my configuration, I'm closing this issue.
For reference, in case someone else finds the same issue, `set sandbox none` has fixed it for me
