### ISSUE TITLE
nssTools seems to be the same package as nss

### ISSUE THREAD

**Issue by philandstuff** [NixOS/nixpkgs#71267]
**Describe the bug**
`nix-env -iA nixos.nss` and `nix-env -iA nixos.nssTools.tools` seem to install the exact same package.

I expect them to be different, and in particular, I expect `nssTools` to contain the `certutil` binary.

**To Reproduce**
1. Install `pkgs.nss`
2. Install `pkgs.nssTools.tools`
3. Observe that the second package replaces the first, at the same store path.

**Expected behavior**
I expect these to be distinct packages, with `nssTools` containing at least `certutil`.

**Additional context**
It looks like this has been confusing people for a while.  See for example [this IRC log from a year ago](https://logs.nix.samueldr.com/nixos/2018-10-10#1539154275-1539154769;).

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.66, NixOS, 19.09pre188498.4557b9f1f50 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188498.4557b9f1f50"`
 - channels(philandstuff): `"dhall, latest, nixos-stable-19.03.173077.28e64db237d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Unfortunately, the nss package does not have any listed maintainers.

**Comment by philandstuff** [comment]
I think this might be my confusion with how `nix-env` works with multi-output derivations.  If I do `nix-env -iA nixos.nss.tools` I install a store path which corresponds to the `$out` path, not the `$tools` path; but if I manually build `nss` myself, I can find an nss-tools install path and directly install that with nix-env.  This way I can get `certutil` onto the command line.

Closing as the issue isn't what I thought it was (even though there's still something horribly surprising here).

**Comment by CMCDragonkai** [comment]
I don't think you should be closing this. If `nssTools` package is meant to supply `certutil` compared to `nss`, then the `nssTools` attribute should be updated to get the actual tools.

**Comment by CMCDragonkai** [comment]
You can get it into your nix environment by using `config.nix`. Then `nss.tools` actually installs what is expected.
