### ISSUE TITLE
NixOS 19.09 upgrade breaks outbound IPv6 on Linode cloud host

### ISSUE THREAD

**Issue by rbrewer123** [NixOS/nixpkgs#71273]
**Describe the bug**
I upgraded a Linode cloud VM from NixOS 19.03 to 19.09.  After the upgrade, initiating ping and ssh over IPv6 from that host no longer worked.  However, I was still able to ping that host and ssh into it over IPv6.

**To Reproduce**
1. Start host on NixOS 19.03 channel
2. ping ipv6.google.com works
3. Update channel to 19.09
4. nixos-rebuild boot
5. Reboot into 19.09
6. ping ipv6.google.com.  This now fails.
7. Revert to NixOS 19.03.  IPv6 works fine again.

**Expected behavior**
ping ipv6.google.com should continue to work across an upgrade to 19.09.

**Additional context**
I have 2 other physical hosts (a desktop and laptop) that I upgraded to 19.09 that have no issues with IPv6.  They share a lot of the same NixOS configuration as the Linode host.  

The Linode host is on kernel 4.19.  I tried switching it to unstable 5.3 while running 19.09 and that did not fix the issue.

The Linode host default route for IPv6 looked ok, and I was able to `ping -6 fe80::1`, which is the default router.  But traceroute to ipv6.google.com got nowhere.

I'm willing to flip the Linode host back to 19.09 to perform further troubleshooting of this issue if anyone has any ideas for me to try.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.03.173592.e758436f986 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(rbrewer): `""`
 - channels(root): `"nixos-19.03.173592.e758436f986, nixos-unstable-20.03pre196586.b943338ea58"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by rbrewer123** [comment]
@rnhmjoj you nailed it on the first try!  That fixed it for me.  Linode must be filtering the temporary IPs or something.

**Comment by rnhmjoj** [comment]
It looks like it: https://www.linode.com/docs/networking/an-overview-of-ipv6-on-linode.
