### ISSUE TITLE
The version of cabal in 'master' is unsupported by ghc-mod under ghc 7.8

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#7133]
https://github.com/kazu-yamamoto/ghc-mod/issues/429

**Comment by deepfire** [comment]
s/cabal-install/cabal/, sorry for the confusion.

**Comment by deepfire** [comment]
@peti, only an enhancement and not a bug?  It breaks emacs (at least) integration..

**Comment by deepfire** [comment]
..and it constitutes a regression from haskellpackages-OldG

**Comment by peti** [comment]
Well, the bug is in `ghc-mod`. What are we supposed to do about it? As far as I can tell, the only thing we could do is downgrade to an old version of `cabal-install`. That's hardly desirable, is it?

**Comment by deepfire** [comment]
The desirability depends on one's values, I guess, as you get to weigh emacs integration against "latest and greatest" features of cabal that were added in the span.

I know nothing about the added features in cabal, and so I am unqualified to judge in general.

Personally, the inability to use emacs in haskellng is.. a bit sad : -)

**Comment by peti** [comment]
I use Emacs for Haskell development all time and the current git version of haskell-mode that we have in Nixpkgs works great. I don't miss ghc-mod much, to be honest. I guess we could provide cabal-install 1.18.x optionally for those who want it, though.

**Comment by deepfire** [comment]
Do you get error message overlays and type hinting with haskell-mode?

**Comment by peti** [comment]
Sure. haskell-mode also integrates nicely with flycheck.
