### ISSUE TITLE
phantomjs: provide builds for 2.0?

### ISSUE THREAD

**Issue by blueyed** [NixOS/nixpkgs#7136]
PhantomJS isn't built currently, but uses the binary builds.

There are no (official) binary builds available though currently, because of
internal issues (https://github.com/ariya/phantomjs/issues/12948).

Since building PhantomJS from source is rather intense, I was hoping for nixpkgs
to provide it.

From https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/phantomjs/default.nix:

    # I chose to use the binary build for now.
    # The source version is quite nasty to compile
    # because it has bundled a lot of external libraries (like QT and Webkit)
    # and no easy/nice way to use the system versions of these

Would it be possible and feasible to have a nixpkg which doesn't use the system versions of the libraries?

/cc @bluescreen303

**Comment by aflatter** [comment]
I'm also interested. :+1:

**Comment by aflatter** [comment]
Just a note: Preliminary builds are available here: https://github.com/bprodoehl/phantomjs/releases

**Comment by dezgeg** [comment]
Seems like we have it now that #8683 was merged.
