### ISSUE TITLE
How to use haskell-ng's new support for GHCJS?

### ISSUE THREAD

**Issue by k0001** [NixOS/nixpkgs#7137]
Since the recent support for GHCJS in `haskell-ng` I haven't been able to get an environment where GHCJS is available.

These examples are using `nixpkgs` as of `d080a94b57c064636b0d08416c1d7b4d386cee13` (April 2nd 2015).

Here's something that works OK using GHC 7.10.1:

```
k@z0 ~ 0 % nix-shell -p "haskell-ng.packages.ghc7101.ghcWithPackages (p: [ ])" --command 'echo "OK"'
OK
```

Now, a similar scenario using GHCJS doesn't work:

```
nix-shell -p "haskell-ng.packages.ghcjs.ghcWithPackages (p: [ ])" --command 'echo "OK"'
error: assertion failed at "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/with-packages-wrapper.nix":6:1
(use ‘--show-trace’ to show detailed location information)
```

Again for GHCJS, with `--show-trace`:

```
nix-shell -p "haskell-ng.packages.ghcjs.ghcWithPackages (p: [ ])" --command 'echo "OK"' --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘shell’ at "/home/k/q/nixpkgs.git/pkgs/build-support/trivial-builders.nix":10:14:
while evaluating ‘ghcWithPackages’ at "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/default.nix":57:27, called from "(string)":1:66:
while evaluating ‘callPackage’ at "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/default.nix":50:26, called from "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/default.nix":57:33:
while evaluating ‘callPackageWithScope’ at "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/default.nix":45:42, called from "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/default.nix":50:32:
while evaluating ‘callPackageWith’ at "/home/k/q/nixpkgs.git/lib/customisation.nix":103:35, called from "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/default.nix":45:49:
while evaluating ‘makeOverridable’ at "/home/k/q/nixpkgs.git/lib/customisation.nix":56:24, called from "/home/k/q/nixpkgs.git/lib/customisation.nix":107:8:
while evaluating anonymous function at "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/with-packages-wrapper.nix":1:1, called from "/home/k/q/nixpkgs.git/lib/customisation.nix":58:12:
assertion failed at "/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/with-packages-wrapper.nix":6:1
```

Line 6 of `/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/with-packages-wrapper.nix` says:

```
assert lib.versionOlder "6.12" ghc.version;
```

Is it me doing something wrong in the way GHCJS is supposed to be used or an issue that needs to be fixed?

Morevover, what's the basic layout that a `shell.nix` file using `haskell-ng`'s `GHCJS` support should have? Up to some days ago I succesfully used `shell.nix` files similar to [this one](https://github.com/ocharles/virtual-dom/blob/0be06f553f9d4ba6a5d7b1db68e00fee246cda87/shell.nix), intended to be used with @ryantrinkle's work on [`ghcjs-setup`](https://github.com/ryantrinkle/ghcjs-setup), but that isn't working anymore due to the very same assertion failure in line `6` of `/home/k/q/nixpkgs.git/pkgs/development/haskell-modules/with-packages-wrapper.nix`.

**Comment by peti** [comment]
Cc: @cstrahan

**Comment by cstrahan** [comment]
@k0001 I fixed the assertion responsible for the failure you're seeing. This should be fixed now.

**Comment by k0001** [comment]
Thank you for the quick answer!
Il 03/apr/2015 19:57, "Charles Strahan" <notifications@github.com> ha
scritto:
