### ISSUE TITLE
Support launching gnome-shell with RT scheduling

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#71381]
#### Background

Capability wrappers are somewhat limited. They require the capability be part of the ambient set for it to survive execv's, ie. when the wrapper executes the source binary (https://github.com/NixOS/nixpkgs/pull/16654). This means any program spawned from a wrapped binary will also inherit the capabilities.

We really don't want programs launched from gnome-shell to inherit cap_sys_nice obviously. In particular bubblewrap fails to work if it possess any extra caps, breaking at least flatpaks and epiphany.

#### Our options
So as far as I can see we have two options:

- Actually copy `.gnome-shell-wrapped` to wrapperDir and set cap_sys_nic=+ep. This should be pretty easy, but also quite ugly (see [this comment](https://github.com/NixOS/nixpkgs/issues/6768#issuecomment-84016619) for context).
- Patch mutter to drop inheritable, we could probably adopt [this unmerged commit](https://gitlab.gnome.org/GNOME/mutter/merge_requests/460/diffs?commit_id=c53c47ae123b03cc66044d2b846342123ecb3a01). This should probably work as the ambient set only propagates if inheritable is set.

cc @jtojnar @worldofpeace

**Comment by hedning** [comment]
Patching mutter to drop inheritable works :tada:, will make a PR :)

**Comment by jtojnar** [comment]
Does not the rationale for not merging it not apply to us? https://gitlab.gnome.org/GNOME/mutter/merge_requests/460?commit_id=c53c47ae123b03cc66044d2b846342123ecb3a01#note_508092

**Comment by hedning** [comment]
No it shouldn't. We only drop inheritable to prevent the ambient set being passed on, while keeping effective and permitted for gnome-shell. (it might be possible to drop the ambient set with `prctl`, but I went with just clearing inheritable): 
```
  capng_clear(CAPNG_SELECT_BOTH);
  capng_update(CAPNG_ADD, CAPNG_EFFECTIVE|CAPNG_PERMITTED, CAP_SYS_NICE);
  capng_apply(CAPNG_SELECT_BOTH);
```
