### ISSUE TITLE
Home assistant hangs on second onboarding screen indefinitely 

### ISSUE THREAD

**Issue by denibertovic** [NixOS/nixpkgs#71382]
**Describe the bug**

I'm using the `home-assistant` service module to install home-assistant on my intel NUC running NixOS 19.09. 
The installation works fine and I can visit `IP:8123` where I'm presented with the `first` onboarding screen which is creating my account. I fill in the form and click next. On the next screen there's just a spinner that keeps loading forever. The chrome debug console does not appear to report anything useful (ie. I don't see any non 2xx responses).

**To Reproduce**
This is my config:

```
# Home Assistant
  services.home-assistant = {
    package = pkgs.home-assistant.override {
      extraPackages = ps: with ps; [ colorlog ];
    };
    enable = true;
    openFirewall = true;
    configWritable = true;
    port = 8123;
    config = {
      homeassistant = {
        name = "Name";
        time_zone = "Europe/Amsterdam";
        latitude = ....;
        longitude = ...;
        elevation = 1;
        unit_system = "metric";
      };
      # Enable the frontend
      frontend = {};
      lovelace = { mode = "yaml"; };
    };
  };
```

I tried disabling the firewall altogether, thinking that might be the problem, but it didn't help. 

**Expected behavior**

I've tested the hass docker image locally with the same config and with that, on the second screen I get a map to choose my location and an option to pick metric vs imperial. And after clicking next I'm presented with the main dashboard. There's a question of why it's prompting me for this info if I already defined it in the config file but this might be a separate issue. 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.09.840.8bf142e001b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.840.8bf142e001b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

ping @dotlambda

**Comment by waldheinz** [comment]
Maybe this is fixed with #71400?

**Comment by waldheinz** [comment]
I just checked, this is working as of `19.09.907.f6dac808387`.

**Comment by bjornfor** [comment]
Closing, since this seems fixed. (Ping me if not.)

**Comment by denibertovic** [comment]
@bjornfor @waldheinz Yes, this does solve the issue for me as well! Thanks for pointing this out! 
And thanks @sweber83 for the fix! :cake:
