### ISSUE TITLE
Connecting an Android MTP device fails

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#71509]
Using Nixos 19.09 with KDE.

When trying to browse an android smartphone (MTP) via the KDE gui it fails with the error:
"The file or folder udi=/org/kde/solid/udev/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/ does not exist."
Same problem is already being discussed here since 2 years ago: https://bugs.kde.org/show_bug.cgi?id=387454

I did not have this problem in NixOS version 19.03

**Comment by 1000101** [comment]
I'm experiencing the same issue since 19.09 (I'm currently on unstable)

```
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.1, channels(root): "nixos-20.03pre196836.1c40ee6fc44", channels(b1000101): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by matthewbauer** [comment]
This sounds like a udev rules issue? Could you try adding this to your config:

```
services.udev.packages = [ pkgs.android-udev-rules ];
```

**Comment by DavHau** [comment]
Thanks, but error still persists even after adding the android-udev-rules.

**Comment by 1000101** [comment]
> This sounds like a udev rules issue? Could you try adding this to your config:
> 
> ```
> services.udev.packages = [ pkgs.android-udev-rules ];
> ```

Same, the error persists, though my device is not covered by the android-udev-rules. Nevertheless, it's in /etc/udev/rules.d/69-libmtp.rules

```
ATTR{idVendor}=="2717", ATTR{idProduct}=="ff40", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"
```

**Comment by shatsky** [comment]
It works in PCManFM but fails in Dolphin. Also, I think I've got the problem even before I upgraded to 19.09, after I installed 5.3-rc7 kernel in 19.03...

**Comment by 1000101** [comment]
> It works in PCManFM but fails in Dolphin. Also, I think I've got the problem even before I upgraded to 19.09, after I installed 5.3-rc7 kernel in 19.03...

It is broken in 4.19.81 as well. I think it broke sometime (roughly 1-2 weeks) before 19.09 became stable.

**Comment by 1000101** [comment]
#73926 fixes it. Thanks @mmahut !!!
