### ISSUE TITLE
libcutl fails to evaluate

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#71544]
**Describe the bug**
Cannot evaluate libcutl on HEAD(0ee02a9d42b5fe1825b0f7cee7a9986bb4ba975d)

**To Reproduce**
1. try to build `libcutl`
```
$ nix-build -A libcutl
error: invalid regular expression '([[:digit:]].[[:digit:]]*+).*', at /Users/marsam/code/nix-config/nixpkgs/pkgs/development/libraries/libcutl/default.nix:21:28
(use '--show-trace' to show detailed location information)
```

**Expected behavior**
Able to build `libcutl`

**Screenshots**

**Additional context**
I think the offending commit is https://github.com/NixOS/nixpkgs/commit/67aa40139ba

cc: @c0bw3b

**Comment by c0bw3b** [comment]
It is indeed my change. I'll revert it ASAP to unbreak Darwin.

I could eval and build on x86 when testing it.. So `builtins.match` has a different behavior on different platforms or ..?!

**Comment by marsam** [comment]
seems to the the asterisk character, I'm not sure why only fails on darwin though
```diff
diff --git i/pkgs/development/libraries/libcutl/default.nix w/pkgs/development/libraries/libcutl/default.nix
index 9abd3b7ccc1..b13805aa37a 100644
--- i/pkgs/development/libraries/libcutl/default.nix
+++ w/pkgs/development/libraries/libcutl/default.nix
@@ -18,7 +18,7 @@ stdenv.mkDerivation rec {
     license = licenses.mit;
   };
 
-  majmin = builtins.head ( builtins.match "([[:digit:]]\.[[:digit:]]*+)\.*" "${version}" );
+  majmin = builtins.head ( builtins.match "([[:digit:]]\.[[:digit:]]+)\.*" "${version}" );
   src = fetchurl {
     url = "https://codesynthesis.com/download/${pname}/${majmin}/${pname}-${version}.tar.bz2";
     sha256 = "070j2x02m4gm1fn7gnymrkbdxflgzxwl7m96aryv8wp3f3366l8j";
```

**Comment by c0bw3b** [comment]
I've pushed 8e5de3a
@marsam are you able to test eval on Darwin or should I ask for a retry in #71264 ?

**Comment by c0bw3b** [comment]
(even weirder -> there was a successful darwin build on hydra)
https://hydra.nixos.org/build/103689807

**Comment by c0bw3b** [comment]
OfBorg evals and darwin builds are successful on most recent PRs so master should be fine on Darwin now

**Comment by marsam** [comment]
I can confirm it works on darwin and NixOS. Thank you @c0bw3b
