### ISSUE TITLE
pip2nix doesn't find pip module

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#71545]
On NixOS 19.09 package pip2nix throws:
ModuleNotFoundError: No module named 'pip'

$ nix-env --install python3.7-pip2nix-0.7.0
$ echo requests > requirements.txt
$ pip2nix generate -r requirements.txt

**Comment by FRidh** [comment]
The expression was broken because it did not include pip. I added it, however, it needs an older version of pip. I've now marked it as broken and will close this because upstream should really make it compatible with a newer pip.
