### ISSUE TITLE
eagle package broken

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#71649]
**Describe the bug**
Eagle does not start anymore. When starting it from the command line I get the following message:

```
$ eagle
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**To Reproduce**
1. Install eagle
2. Start it by calling `eagle`

**Expected behavior**
Instead of getting an error message on the console, I'd expect the software to show a graphical window.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.09.809.5000b1478a1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.809.5000b1478a1, unstable-19.09pre192418.e19054ab3cd"`
 - channels(matthias): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute: [ eagle ]
module:
```

**Comment by veprbl** [comment]
cc #65399

**Comment by jonringer** [comment]
I noted this as well #71549

**Comment by bjornfor** [comment]
CC maintainer @rittelle.

**Comment by jonringer** [comment]
it has to do with the qt wrapping, and i keep forgetting the best practices

**Comment by jonringer** [comment]
I tried that, but it needs some non-qt libraries, and felt like i was wasting too much time on it, so i moved on

**Comment by rittelle** [comment]
Hmm, I'll try to look into the issue this week.

**Comment by bjornfor** [comment]
I think this should fix it:

```patch
diff --git a/pkgs/applications/science/electronics/eagle/eagle.nix b/pkgs/applications/science/electronics/eagle/eagle.nix
index 7789f4cf8ba..a0eec53ce0b 100644
--- a/pkgs/applications/science/electronics/eagle/eagle.nix                                                            
+++ b/pkgs/applications/science/electronics/eagle/eagle.nix                                                            
@@ -1,4 +1,4 @@                                            
-{ stdenv, fetchurl, makeDesktopItem
+{ stdenv, fetchurl, makeDesktopItem, mkDerivation
 , libXrender, libXrandr, libXcursor, libX11, libXext, libXi, libxcb                                                   
  , libGL, glib, nss, nspr, expat, alsaLib
 , qtbase, qtdeclarative, qtsvg, qtlocation, qtwebchannel, qtwebengine                                                 
@@ -11,7 +11,7 @@ let                                      
       qtbase qtdeclarative qtsvg qtlocation qtwebchannel qtwebengine                                                  
     ];                                                    
   in                                                      
-  stdenv.mkDerivation rec {                               
+  mkDerivation rec {                                      
     pname = "eagle";                                      
     version = "9.5.0";                                    
                                                           
```

**Comment by jonringer** [comment]
It's probably going to be wrapped several times because of the old logic

**Comment by mawis** [comment]
How can I apply this patch locally? I tried to load eagle from nixos-unstable, but that patch isn't there yet.

**Comment by mawis** [comment]
Thanks for merging it :)
