### ISSUE TITLE
Useless warnings like File format not recognized

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#7166]
Likely strip should never be called in the first place. 

```
# nix-env --upgrade output
strip:/nix/store/rbrjd2yp28r7qqzpy75x88kyxwvp4z0v-calibre-2.20.0/lib/calibre/calibre/utils/ipc/worker.py: File format not recognized
```

Builds should be _quiet_ and without warnings.

**Comment by vcunat** [comment]
The thing is that it's not so easy to find (in a shell) whether a file is strippable or not. Our stdenv tries it on any executable. (BTW, I do recommend the ``-Q`` option regardless of fixing this.)

**Comment by aragnon** [comment]
Perhaps I am being ignorant here, but aren't .py files always text files and thus not strippable? If you consider that to be a hack, then I suppose there would be somewhat of an argument to just close this issue or to do what you said. 

Perhaps there are other tools which have a shorter run-time than strip which can be used to test for this; for example a command which extracts symbols and doesn't find any could be used to do do a test before strip runs. Similarly, the amount of times the tool gets called might be optimized, but I did not check that.

**Comment by vcunat** [comment]
We might exclude files that start with a shebang (just check the fist two bytes). I'm not certain it would catch all cases, but AFAIK we either have ELF executables or shebanged scripts.

**Comment by nslqqq** [comment]
:+1: for checking for schebang. its very annoying sometimes

**Comment by dezgeg** [comment]
Well, you could relatively easily read the first 4/4/2 bytes in bash and look for ELF/Mach-O/PE header:
````
read -n 4 magic </bin/sh
test "$magic" = $'\x7fELF'; echo $? # prints 0
````

That shouldn't be too ugly.

**Comment by vcunat** [comment]
Yes, `.a` as well, and those aren't even executable, but they also [have magic](https://en.wikipedia.org/wiki/Ar_(Unix)#Global_header).

**Comment by Profpatsch** [comment]
This should be renamed to something like `improve stripping logic`.

**Comment by Profpatsch** [comment]
(triage) has this been fixed?
