### ISSUE TITLE
Pantheon test broken on master

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#71725]
**Describe the bug**

Looks like there were some pantheon breakage that passed through staging-next:
https://hydra.nixos.org/build/104001348

cc @worldofpeace

**Comment by worldofpeace** [comment]
See https://github.com/elementary/files/issues/1081, worked around in https://github.com/NixOS/nixpkgs/commit/404f148e086db81316d8ca3b4a41ae38c53af535.

Vala has had some more release as well that should probably get queued into staging.
