### ISSUE TITLE
any example of compiling python3 in NixOS?

### ISSUE THREAD

**Issue by rndd-AK** [NixOS/nixpkgs#71801]
trying to compile some stuff, dont know how to do it using nix

**Comment by FRidh** [comment]
What is it you want to compile? Do you want to build the interpreter? Or do you want to transpile and compile Python code?

**Comment by rndd-AK** [comment]
I want to generate C code with cython and compile with gcc. Maybe there any ready examples

**Comment by FRidh** [comment]
Then just follow the cython examples on how to create a `setup.py` Python package. There isn't anything different here with Nix, aside from using `buildPythonPackage` that than packages and builds your Python package.

**Comment by rndd-AK** [comment]
ok
