### ISSUE TITLE
nixos-rebuild switch causes my gnome wayland session to restart

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#71818]
**Describe the bug**
Previously I ran Xorg and xfce on top of nixos, I have since upgraded to gnome and wayland. When I issue a nixos-rebuild switch --upgrade and it updates something to wayland or gdm I assume it causes the session to restart. I understand why it would do that but I think everyone would prefer the behavior we had with X before.

**To Reproduce**
1. Install nixos 19.09 wayland and gnome from cd
2.  do a nixos-rebuild switch --upgrade from a terminal 

**Expected behavior**
I think it should just not restart the service, or fail to switch saying it couldnt do it because doing so would cause wayland to restart.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
- system: `"x86_64-linux"`
 - host os: `Linux 5.3.6, NixOS, 19.09.907.f6dac808387 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.907.f6dac808387, oldstable-19.03.173619.d15a31f88a2, unstable-20.03pre197685.f35f0880f2c"`
 - channels(mog): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by glasserc** [comment]
I think I've experienced the same thing. It isn't every single `nixos-rebuild switch`, but it happened two nights in a row at 4:48 AM (the time that the `autoUpgrade` happens), and I am concerned it will happen again. I'd guess it's something to do with the NixOS release number -- switching from `/nix/store/ahac32l0lsyy28h2qf66irg208cqnrs5-nixos-system-golden-cloud-19.09.907.f6dac808387` to `/nix/store/ss6ly6cqg6482pj6m08dglq2k63906iy-nixos-system-golden-cloud-19.09.891.80b42e630b2`, or back, kills the GNOME session. Maybe some GNOME updates recently rolled out and I just got unlucky that it happened two nights in a row?

**Comment by hedning** [comment]
I'm fairly certain this is a general issue with `nixos-rebuild switch` unfortunately, see eg. https://github.com/NixOS/nixpkgs/issues/40218 where it happens with i3 and slim. My hunch is also that there are certain system upgrades which forces a service to restart which shouldn't, while others work fine by not touching these.

This is obviously not ideal, and we do have some guards in place to prevent it (eg. the display-manager is asked not to restart on changes IIRC), but I think this one requires some more digging to fix entirely :(

@glasserc if you're on nixos-unstable you might've hit some breakage that made any nixos-rebuild switch crash gnome/GDM, this should be fixed now fortunately.

**Comment by glasserc** [comment]
@hedning Am I on nixos-unstable? nixos.org says "NixOS 19.09 “Loris” has been released, the twelfth stable release branch." How do I get on that? My `nix-info` says:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.907.f6dac808387 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(ethan): `""`
 - channels(root): `"nixos-19.09.907.f6dac808387"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by hedning** [comment]
@glasserc `nixos-unstable`, or just unstable, refers to the rolling nixos release, as opposed to the 6 months stable releases (eg. 19.09) (see https://nixos.wiki/wiki/Nix_channels for the different channels/releases).

On unstable we had `nixos-rebuild switch` consistently crash the session (https://github.com/NixOS/nixpkgs/issues/70954), even by switching to the same configuration. So in case you were running unstable I just wanted to give you a heads up that you might've hit a resolved issue. But seeing that you're running stable it looks like you're seeing a variant of the more generic and stubborn `nixos-rebuild switch` problem.

**Comment by worldofpeace** [comment]
Can this be closed? I believe the recent issue was solved.

**Comment by mogorman** [comment]
i dont believe the issue has been resolved. it hasnt happened to me again,but im fairly sure the next time i upgrade and there is something that will call wayland/gnome to restart it will.

**Comment by glasserc** [comment]
Yeah, my GNOME session restarted overnight, probably in between these two profiles:
```
/nix/var/nix/profiles/system-380-link -> /nix/store/8ikhkp93pzjv3zn494xn93ws2n7mifqr-nixos-system-golden-cloud-19.09.976.c75de8bc12c
/nix/var/nix/profiles/system-381-link -> /nix/store/ipzsmyskl239b82vqizzmai64ym1lfzx-nixos-system-golden-cloud-19.09.1019.c5aabb0d603
```

Is this amount of churn typical for a stable release? I could have sworn that 19.03 was not this turbulent.

**Comment by mogorman** [comment]
Happened for me the otherday. i assumed this had something to do with gnome or wayland, as my setup hasnt changed other than that and ive nevre had this issue with graphic session being reset

**Comment by chpio** [comment]
Yeah, to me too. im running gnome3 + X. It would be really nice to have an option to do a "boot" instead of "switch" in the autoupdater.

**Comment by mogorman** [comment]
you can do nixos-rebuild boot, that puts you on new os next boot. but would still like this fixed.

**Comment by chpio** [comment]
yeah, but... i'm thinking about building a nixos-rig for my grandma, so it need to be a stable system, a crashing DM is not an option & manual updating is not an option too. Also updating on boot is good enough. So i would like to see an option for switching to "boot" autoupgrade for stability reasons (not only related to this issue).

**Comment by onny** [comment]
I have these session restarts after I installed and used GDM as a display/login manager. But I use sway as a graphical session and I'm able to switch back to the old session, running on a different tty. I would be glad that propably the GDM service won't be restarted with ``nixos-rebuild --switch``.

**Comment by mogorman** [comment]
I don't seem to have this problem since I moved to unstable
