### ISSUE TITLE
Nix error: undefined variable 'goPackages'

### ISSUE THREAD

**Issue by rndd-AK** [NixOS/nixpkgs#71848]
i was reading some guides from 2014 about writing in go within nixos. I suppose it's a little bit outdated. Where go packages?

**Comment by rnhmjoj** [comment]
Not a go programmer but I have packaged some Go program: there's no such attribute, not anymore at least.

The preferred method to package Go programs are Go *modules* and Nix takes care of gathering all the depedencies , so I don't think a set of packages is even needed. Same for Legacy Go programs, which use a `deps.nix` generated file with dependencies.
