### ISSUE TITLE
Python:  `python setup.py test` is deprecated

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#71897]
**Describe the bug**
The `test` command of `setuptools` has been [deprecated](https://github.com/pypa/setuptools/pull/1878). Packages should stop using it, we should stop using it as a default `checkPhase`.

**Additional context**
The command is currently used as the default `checkPhase`. It was not uncommon that we had to set a custom `checkPhase`, typically `pytest` or `nosetests`. Now that the command is being deprecated/removed, we can expect more variation in commands to be used. Upstream does encourage the use of `tox`, although I think we should generally avoid it because it's a relatively heavy. (OK, not very heavy, but because it has Python deps we can't use it for core packages because of the DAG)

**Related**
- https://github.com/pypa/setuptools/pull/1878
- https://github.com/pypa/setuptools/issues/1684
- https://discuss.python.org/t/proposal-for-tests-entry-point-in-pyproject-toml/2077

**Comment by wamserma** [comment]
From what I've seen (very subjective), most packages are moving to either tox or pytest (without tox). The choice should be detectable with a few checks in the default checkPhase. For all others we could omit a warning requesting customization of the checkPhase.

**Comment by jonringer** [comment]
this is only ran today if `format = "setuptools";` is set, which is no longer the default since https://github.com/NixOS/nixpkgs/pull/254136.

I think we can close this, but I'll defer to @FRidh 's judgement
