### ISSUE TITLE
mate-settings-daemon-1.22.1 not building on unstable

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#71950]
builder for '/nix/store/6d56bl3qxhr6123khhq2k5bxc1p2cc37-mate-settings-daemon-1.22.1.drv' failed with exit code 2

**To Reproduce**

1. in /etc/nixos/configuration.nix:  services.xserver.desktopManager.mate.enable = true;

2. nixos-rebuild switch 

**Additional context**
...
...
  CC       libclipboard_la-xutils.lo
  CC       libclipboard_la-list.lo
  CCLD     libclipboard.la
LC_ALL=C /nix/store/4azg93cwh1hxn2aqfgpakq8pxpd65l81-intltool-0.51.0/bin/intltool-merge -d -u -c ../../po/.intltool-merge-cache ../../po clipboard.mate-settings-plugin.in clipboard.mate-settings-plugin
Found cached translation database
Merging translations into clipboard.mate-settings-plugin.
make[3]: Leaving directory '/build/mate-settings-daemon-1.22.1/plugins/clipboard'
Making all in datetime
make[3]: Entering directory '/build/mate-settings-daemon-1.22.1/plugins/datetime'
 cd ../.. && /nix/store/v2x1ks46fq3yn8c94qfv38wrvmr5xn5r-bash-4.4-p23/bin/bash /build/mate-settings-daemon-1.22.1/missing automake-1.16 --gnu plugins/datetime/Makefile
/build/mate-settings-daemon-1.22.1/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make[3]: *** [Makefile:454: Makefile.in] Error 127
make[3]: Leaving directory '/build/mate-settings-daemon-1.22.1/plugins/datetime'
make[2]: *** [Makefile:444: all-recursive] Error 1
make[2]: Leaving directory '/build/mate-settings-daemon-1.22.1/plugins'
make[1]: *** [Makefile:500: all-recursive] Error 1
make[1]: Leaving directory '/build/mate-settings-daemon-1.22.1'
make: *** [Makefile:432: all] Error 2
builder for '/nix/store/6d56bl3qxhr6123khhq2k5bxc1p2cc37-mate-settings-daemon-1.22.1.drv' failed with exit code 2
cannot build derivation '/nix/store/s33xdksnx083n64ak6wxcs7jhjczlq45-hwdb.bin.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rr6sm6vy7ggn7h2gkrfqg2fbcq23jbb6-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/9fj12zwajp3pj3ivn310vsq18dpc6pcg-udev-rules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zpgdspgbsi1vgggs9ylrnnn85waxi7dw-unit-systemd-udevd.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xskns62y5vmps1wczng18j5zfr30nq46-xsession.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bkzaqdyjb1cpvqaby3nmirj5mff5m4zi-nixos-system-bx26-20.03pre197685.f35f0880f2c.drv': 1 dependencies couldn't be built
error: build of '/nix/store/bkzaqdyjb1cpvqaby3nmirj5mff5m4zi-nixos-system-bx26-20.03pre197685.f35f0880f2c.drv' failed

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03pre194293.2436c27541b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre197685.f35f0880f2c, nixpkgs-20.03pre192821.b425012fdf4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

**Comment by worldofpeace** [comment]
Will fix.
