### ISSUE TITLE
Package Request: Mindustry

### ISSUE THREAD

**Issue by MicrosoftTakeover** [NixOS/nixpkgs#72001]
**Project description**
A sandbox tower defense game written in Java.

**Metadata**

* homepage URL: https://mindustrygame.github.io/
* source URL: https://github.com/Anuken/Mindustry
* license: gpl3
* platforms: linux

Looks to be a high quality game that has great reviews on Steam, let's package it!

**Comment by davidak** [comment]
It's already packaged in https://github.com/NixOS/nixpkgs/pull/72306

Just needs to get merged.

**Comment by DrPyser** [comment]
@davidak Hi. I'm on nixos.
I can't seem to install the package.
```
$ nix-env -f "<nixpkgs>" -qaP mindustry
error: selector 'mindustry' matches no derivations
$ nix search -u mindustry
error: no results for the given search term(s)!
```

**Comment by peterhoeg** [comment]
It's not in 19.09. Either wait for 20.03 or switch to unstable.

**Comment by DrPyser** [comment]
@peterhoeg Thanks. How do I "switch to unstable"? You mean using an unstable channel?

**Comment by peterhoeg** [comment]
Either the 20.03 channel or the unstable channel, yes.

Take a look at the wiki - https://nixos.wiki/wiki/Nix_channels

**Comment by DrPyser** [comment]
Thanks, got it, now enjoying the game!
