### ISSUE TITLE
haskellngPackages.Agda won't build (demands cpphs < 1.19)

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#7201]
Running ```nix-build -A haskellngPackages.Agda``` at 7626674 results in

    ...
    Dependency zlib -any: using zlib-0.5.4.2
    Setup: The program cpphs version >=1.18.6 && <1.19 is required but the version
    found at
    /nix/store/lnfjbhqsqa279v0bm76afhy73bz0fnmn-haskell-cpphs-1.19/bin/cpphs is
    version 1.19
    builder for ‘/nix/store/288airpbdqncn0994qw16jqd5zm21pbm-haskell-Agda-2.4.2.2.drv’ failed with exit code 1

Maybe this can be fixed in a way similar to https://github.com/NixOS/nixpkgs/commit/6644bca846a8b67fe2ba4c3a9de51009e84c37fa which fixed https://github.com/NixOS/nixpkgs/issues/7014 (before I re-opened it).

Paging @peti and @ocharles because they seem to know what's going on with haskell-ng and versions :-)

**Comment by phile314** [comment]
There is probably going to be a new Agda minor release soon, which should fix the cpphs version problem (and add GHC 7.10 support):
https://code.google.com/p/agda/issues/detail?id=1482

Jailbreaking the build-tools cpphs dependency of Agda should also work for the time being.

**Comment by peti** [comment]
I'm not particularly happy about the fact that thw fix for Agda is mixed up with a structural change of the default builder that -- when  merged -- causes a complete re-build of every single Haskell package.

**Comment by peti** [comment]
Ah, disregard my earlier comment please. It was meant to go to https://github.com/NixOS/nixpkgs/pull/7172.

**Comment by falsifian** [comment]
Thanks for the quick fix!
