### ISSUE TITLE
Meld crashed on startup 

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#72030]
On nixos-unstable, Meld immediately crashes. Something about gsettings schemas according to backtrack, but no message in the console.

Possibly strictDeps striking again?

**Comment by worldofpeace** [comment]
@jtojnar I believe I fixed the strictDeps issue in https://github.com/NixOS/nixpkgs/commit/64c8f268df0dcda215b0f57a7150d1b87d2af690.

I tried running it on 4c0afa17702c32f40c70482bd16e47b37b30214e without issues, though perhaps if actually used it the crash could be produced.

**Comment by jtojnar** [comment]
I cannot reproduce this any more.
