### ISSUE TITLE
postfix 2.8.x is out of support since Feb/2015

### ISSUE THREAD

**Issue by arno01** [NixOS/nixpkgs#7205]
Postfix 2.8.x is out of support since Feb/2015. And the latest patchlevel 20. However current postfix patchlevel is far not the latest, it is 12.
http://cdn.postfix.johnriley.me/mirrors/postfix-release/index.html

I think we should make postfix 2.11.x the default in stable release-14.12 merging this commit 9b50ef3c69b60c95625feeb4cd4e7ae9947e6605

This commit also makes postfix "SDD-friendly":
http://postfix.cs.utah.edu/source/official/postfix-2.10.0.RELEASE_NOTES
```
[Feature 20120924] the default master.cf file now uses "unix" instead
of "fifo" for the pickup and qmgr services. This avoids periodic
disk drive spin-up.
```

I have applied this commit on my personal server where I'm running my own email services for 2+ years, no impact.

**TOFIX**
One thing that has to be changed is `recipientDelimiter` to be switched to `recipient_delimiter` in `nixos/modules/services/mail/postfix.nix` at the `mainCf` section.

**Comment by peti** [comment]
Going from 2.8 to 2.11 is a fairly bug jump for a stable release branch. I'm not sure that's appropriate.

**Comment by arno01** [comment]
I've mentioned 2.11.x as there already was commit, but 2.9.x would be just fine too IMHO :-)
And 2.10.x would be SSD friendly :)

It's good to gather some more feedback though.
Preliminary we can look at Debian, they've got postfix 2.9.x in stable (wheezy) and in couple of weeks they will have postfix 2.11.x in stable (jessie)
https://packages.debian.org/search?keywords=postfix

Also, based on http://www.postfix.org/announcements.html every postfix <2.11.x is a legacy release since Jan/2014

**Comment by peti** [comment]
Personally, I see no  reason to bump postfix in the existing stable branch. Everybody who wants the newer version can easily have it simply by configuring a package override. IMHO, it's fine to ship 2.11 as default in the next release, which is due in May.

**Comment by Profpatsch** [comment]
(triage) resolved?

**Comment by gebner** [comment]
@peti removed the old postfix versions in 24fe7bab087a6302671511e24fa49130985b8c29.
