### ISSUE TITLE
Acme staging still uses the ACMEv1

### ISSUE THREAD

**Issue by thelegy** [NixOS/nixpkgs#72067]
**Describe the bug**
Acme staging still uses the ACMEv1 and thus fails

**To Reproduce**
1. on a recent nixos machine with a channel that already includes https://github.com/NixOS/nixpkgs/pull/71291
2. set `security.acme.production = false;`
3. Enable any acme service. for example:
`services.nginx = {
    enable = true;
    virtualHosts.default = {
      default = true;
      enableACME = true;
      addSSL = true;
    };
  };`

**Expected behavior**
The acme service should create a new certificate.

**Additional context**
The logs say that simp_le connects to `https://acme-staging.api.letsencrypt.org:443 "GET /directory HTTP/1.1"` with would be the ACMEv1 api. The problem will be https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme.nix#L201 still using it falsely. The correct server option should be `https://acme-staging-v02.api.letsencrypt.org/directory`.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7, NixOS, 19.09.972.3de2a6aace8 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.972.3de2a6aace8, nixos-unstable-20.03pre198214.4cd2cb43fb3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
cc @abbradar @fpletz @globin

**Comment by fpletz** [comment]
Thanks! Also backported to 19.09.
