### ISSUE TITLE
Could not resolve flake reference 'null'

### ISSUE THREAD

**Issue by haslersn** [NixOS/nixpkgs#72083]
When I try to build my system using the new Nix flakes, I get the error

```
building the system configuration...
error: could not resolve flake reference 'null'
```

**To Reproduce**

1. My system is on the following nixpkgs revision: `nixos-unstable` @ 4cd2cb43fb3a87f48c1e10bb65aee99d8f24cb9d with `edolstra/master` @ 153ca089f43018310ff6edd6d2286819a4800af8 merged into it.
2. Add the following to your NixOS configuration and `nixos-rebuild switch`:
```
  nix.package = pkgs.nixFlakes;
  nix.extraOptions = ''
    experimental-features = nix-command flakes
  '';
``` 
3. Have the following `flake.nix` (I removed stuff and that didn't change the error):

```
{
  edition = 201909;

  outputs = { self, nixpkgs }: {
    nixosConfigurations.beaver = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [];
    };
  };
}
```

4. Execute `nixos-rebuild build --flake .`

**Expected behavior**
With the full `flake.nix` actually containing my configuration modules (which I didn't post here), I expect it to run without error.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.6, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20191022_9cac895`
 - nixpkgs: `/nix/store/ncg8lg0iyh1vxkfhafxh53n8m9lbrv73-nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nixFlakes
# a list of nixos modules affected by the problem
module:
```

**Comment by haslersn** [comment]
@edolstra We talked about this at NixCon 2019.

**Comment by Artturin** [comment]
assuming this is no longer relevant
