### ISSUE TITLE
Python: support poetry as a build system

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#72103]
**Describe the bug**
[https://github.com/sdispater/poetry](Poetry) can also be used as a PEP 517 build system. We could add a setup hook to support it.

**Comment by adisbladis** [comment]
This is actually already supported, all you need to do is to add `format = "pyproject";` and add `poetry` as a build input to the derivation.

**Comment by FRidh** [comment]
Doh, of course, I forgot that would already work. Thanks!
