### ISSUE TITLE
`dust` errors with `which: no rlwrap` on PATH

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#72129]
Running `dust` reports: 
```
which: no rlwrap in <path>: line 29: /nix/store/s3s2algxdazksmakbsrln394m9ahk5m8-pixie-0-r1364-jit/bin/pixie-vm:
```

**To Reproduce**

1. Install `dust` on NixOS 19.09.
1. Invoke `dust`.

**Metadata**
I ran `nix run nixpkgs.nix-info -c nix-info -m` but got `error: attribute 'nixpkgs' in selection path 'nixpkgs.nix-info' not found`.

**Comment by JustinLovinger** [comment]
I'm seeing a same issue on the latest unstable:
```
which: no rlwrap in <path> line 29: /nix/store/s7fgkys6b7r1v91bcb14rw2fcksgadzg-pixie-0-r1364-jit/bin/pixie-vm: No such file or directory
```

Interestingly, `dust` works fine when installed with `nix run`.

**Comment by bbigras** [comment]
I had this same problem today.

**Comment by srid** [comment]
Not stale; this is still a problem on a flakes based NixOS system using 432fc2d9a67f92e05438dff5fdc2b39d33f77997
