### ISSUE TITLE
gnutls-kdh-1.0.drv doesn't build

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#72123]
**Describe the bug**

See the [attached log](https://github.com/NixOS/nixpkgs/files/3776432/build.log); the relevant issue seems to be here:

```text
aes-padlock.c:96:29: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                             ^~~~
                             key_size
aes-padlock.c:96:45: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                                             ^~~~
                                             key_size
aes-padlock.c:97:22: error: 'struct aes_ctx' has no member named 'rounds'
   pce->ks.rounds = nc.rounds;
                      ^
```

Most of [my configuration](https://gitlab.com/victor-engmark/root/blob/b586ec1cf0606b9c558061b81020fde0b44533d2/configuration.nix) is online verbatim.

**To Reproduce**
1. `sudo nixos-rebuild switch --upgrade`

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.78, NixOS, 20.03pre196725.94500c93dc2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre198214.4cd2cb43fb3"`
 - channels(username): `"nixpkgs-20.03pre193309.c4196cca9ac"`
 - nixpkgs: `/home/username/.nix-defexpr/channels/nixpkgs`

**Comment by prusnak** [comment]
I confirm I see the same issue here.

**Comment by prusnak** [comment]
It seems the only package that needs `gnutls-kdh` is `tlspool`. Do you need `tlspool` or `gnutls-kdh` specifically?

**Comment by jonringer** [comment]
i bisect'ed it to https://github.com/NixOS/nixpkgs/commit/6153f6d89f5232feb082e84cc5e0978508b9b3bd

**Comment by jonringer** [comment]
lutris has it as a transitive dependency

**Comment by jonringer** [comment]
```
builder for '/nix/store/mvmsb14xgprpq96slnmic8jnwh95rznl-gnutls-kdh-1.0.drv' failed with exit code 2
cannot build derivation '/nix/store/0s5b8l613qp7p8p2vkzc7f3rxhzq3nnh-lutris-usr-target.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dqgc4qlkfbfigq1lh3gx66byd0lksfic-lutris-fhs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0zrdnj9cwk6cb3si43jz94yvi7zkg658-lutris-init.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vqalyfbcvpzs1x2gr2f7dyn4ck68miyb-lutris.drv': 1 dependencies couldn't be built
error: build of '/nix/store/vqalyfbcvpzs1x2gr2f7dyn4ck68miyb-lutris.drv' failed
```

**Comment by jonringer** [comment]
I guess it's used by dolphin

**Comment by jonringer** [comment]
to follow up, gnutls-kdh doesn't build with nettle-3.5.1. Seeing as the repo is quite inactive, either we get rid of it, or freeze nettle. 

I'm personally in favor of getting rid of it
