### ISSUE TITLE
please help: how to pin the kernel version?

### ISSUE THREAD

**Issue by tscholak** [NixOS/nixpkgs#72130]
Hi, what follows is not necessarily an issue with nixos, but with my inability to figure out a workaround for a kernel issue. Sorry to put this here in a GitHub issue, I'm not sure where else to put it.

I'm on nixos 19.09, and my Broadcom wifi adapter doesn't work reliably with the latest 4.19 kernel, that is, 4.19.80. the problem did not exist with kernel 4.19.78.

So, to work around the issue, I'm trying to pin the kernel version to 4.19.78 using `callPackage` on https://raw.githubusercontent.com/NixOS/nixpkgs/3eeea86ac344062ef3b6e5d167e9c888884495d4/pkgs/os-specific/linux/kernel/linux-4.19.nix in the overlay section of my `configuration.nix`.
however, I'm presented with this stack trace:

```
# nixos-rebuild dry-build --upgrade --show-trace --keep-going
unpacking channels...
building the system configuration...
error: while evaluating the attribute 'config.system.build.toplevel' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:274:5:
while evaluating 'foldr' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:52:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:138:12:
while evaluating 'fold'' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:55:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:59:8:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:131:50, called from undefined position:
while evaluating the attribute 'assertion' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/loader/systemd-boot/systemd-boot.nix:123:9:
while evaluating the attribute 'boot.kernelPackages.kernel.features' at /nix/store/v7xfpd8prkr672y1spihyl6m5nqhn5sc-nixos-19.09.941.27a5ddcf747/nixos/pkgs/os-specific/linux/kernel/generic.nix:175:5:
while evaluating 'foldr' at /nix/store/v7xfpd8prkr672y1spihyl6m5nqhn5sc-nixos-19.09.941.27a5ddcf747/nixos/lib/lists.nix:52:20, called from /nix/store/v7xfpd8prkr672y1spihyl6m5nqhn5sc-nixos-19.09.941.27a5ddcf747/nixos/pkgs/os-specific/linux/kernel/generic.nix:63:20:
while evaluating 'fold'' at /nix/store/v7xfpd8prkr672y1spihyl6m5nqhn5sc-nixos-19.09.941.27a5ddcf747/nixos/lib/lists.nix:55:15, called from /nix/store/v7xfpd8prkr672y1spihyl6m5nqhn5sc-nixos-19.09.941.27a5ddcf747/nixos/lib/lists.nix:59:8:
value is a set while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/kernel.nix:43:27
```

Does anyone know how to do this properly?

I was working under the assumption that overriding `pkgs.linux_4_19` is enough, cf. https://github.com/NixOS/nixpkgs/blob/nixos-19.09/pkgs/top-level/all-packages.nix#L15886 

Thank you very much!

**Comment by jonringer** [comment]
The offending line is:
```
assertion = (config.boot.kernelPackages.kernel.features or { efiBootStub = true; }) ? efiBootStub;
```
kernel.features contains a set initially, so when the merge takes place, it's trying to concatenate a list and set.

**Comment by asymmetric** [comment]
For anyone stumbling onto this from DDG, [this post](https://discourse.nixos.org/t/override-kernel-version/3638/5?u=asymmetric) explains how to pin a kernel version.

**Comment by abathur** [comment]
Closing since it sounds like asymmetric answered the question, but I'm happy to reopen if I'm overreaching :)
