### ISSUE TITLE
AMI release for 19.09

### ISSUE THREAD

**Issue by DzmitrySudnik** [NixOS/nixpkgs#72132]
**Describe the bug**
There is no AWS AMI for NixOS 19.09.

**To Reproduce**
1. Check https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix
or
2. Try find it in AWS AMI console

**Expected behavior**
19.09 is created and uploaded to AWS

**Additional context**
I built my own AMI for 19.09 and it behaves weird: can't connect with openssl to any hosts with AWS certificates. I might create a separate issue for this case when I get more information, but at first I just wanted to test it from an official NixOS 19.09 AMI and was surprised that it doesn't exist.

**Comment by FRidh** [comment]
cc @disassembler I think this was mentioned on IRC as well.

**Comment by Atemu** [comment]
19.09 has been EOL for years.
