### ISSUE TITLE
busybox 1.31.1

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#72137]
https://git.busybox.net/busybox/log/?h=1_31_stable

https://busybox.net

I don't have the build bandwidth to submit a PR for this presently, but in case anyone else does (or we do as a community) wanted to bring attention to this.

Particularly pay attention to the 1.31.0 notes as they may contain important details re:compatibility concerns.

**Comment by clkamp** [comment]
It was updated in 7b599dc25ec455ec4bab26ec2c5e099868201d73, so please close.
