### ISSUE TITLE
Darwin breakage is blocking nixpkgs-unstable and staging-19.09

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#72146]
**Describe the bug**
Certain core packages don't build for Darwin, blocking the `nixpkgs-unstable` channel from advancing.

https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents

cc @NixOS/darwin-maintainers

**Comment by domenkozar** [comment]
To save time for others, here's a segfault that blocks the channel https://nix-cache.s3.amazonaws.com/log/nyr6298pi9zgnlpchv2g8gcsgkfd77ly-swift-corefoundation.drv

**Comment by sylvainf911** [comment]
I see the build of nixpkgs-unstable seems ok now. But https://nixos.org/channels/nixpkgs-unstable still redirects to https://releases.nixos.org/nixpkgs/nixpkgs-20.03pre197736.91d5b3f07d2. Is this normal?

**Comment by sylvainf911** [comment]
It seems the nixpkgs-unstable is now redirecting to a recent build.

**Comment by vcunat** [comment]
Seems fine now.

**Comment by FRidh** [comment]
I noticed that already on last staging next cycle the issue was happening again
https://hydra.nixos.org/build/108024951

**Comment by LnL7** [comment]
I wasn't able to reproduce the problem easily locally so I only verified the condition with false https://github.com/NixOS/nixpkgs/pull/73572/files#diff-5d73b7be42e81b19a11c4b19c688ae96R79. Apparently functions in an if condition in combination with `set -e` behaves not at all as I was expecting.

Removed ninjaBuildPhase in #75528.

**Comment by vcunat** [comment]
Now it [succeeded](https://nix-cache.s3.amazonaws.com/log/zpaf5padcz7d2lv6ag0pgcwy2mvmknv2-swift-corefoundation.drv).  It doesn't seem the retry happened, but I'll hope it works; let's close until we encounter the issue again.
