### ISSUE TITLE
netdata: Python.d plugins are all broken

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#72163]
**Describe the bug**
It's impossible to load any Python.d plugin due to the header of those scripts which uses `which` to find a path to python or python2 or python3, it throws a `which: command not found` in the error.log.

**To Reproduce**
1. Install netdata, enable Python plugins.
2. Set an error log.
3. Run. Look at the error log and look at the web interface, no Python.d plugins and the above-mentioned error.

**Expected behavior**
Netdata should run Python.d plugins fine.

**Additional context**

It seems like previous issues like this already existed, I suppose this behavior was introduced during an unproperly tested upgrade of the package. I don't know how to rollback nixpkgs easily so I cannot bisect to find the root cause.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7-arch1-1-ARCH, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixpkgs-20.03pre197736.91d5b3f07d2"`
 - channels(raito): `"nixpkgs-20.03pre197736.91d5b3f07d2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
attribute: netdata
```

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/72187
