### ISSUE TITLE
Package request: ray (python package)

### ISSUE THREAD

**Issue by rht** [NixOS/nixpkgs#72175]
**Project description**

Ray is a fast and simple framework for building and running distributed applications.
It is packaged with RLlib, a scalable reinforcement learning library.

The project provides a `manylinux1` wheel at https://ray.readthedocs.io/en/latest/installation.html, but according to https://github.com/NixOS/nixpkgs/issues/43468#issuecomment-404817423 NixOs is by default not `manylinux1` compatible.

**Metadata**

* homepage URL: https://ray.readthedocs.io/en/latest/
* source URL: https://github.com/ray-project/ray
* license: apache2
* platforms: unix, linux

**Comment by rht** [comment]
#71935

**Comment by mjlbach** [comment]
This seems to be more important now; I was formerly able to run ray prior to version 0.8.4 via pip installing into a nix-shell environment, but now I get errors trying to launch redis-server.

**Comment by rht** [comment]
I haven't tested, but @mjlbach, since manylinux1 is available by default now (https://github.com/NixOS/nixpkgs/issues/71935#issuecomment-570049693), does it work on your machine on the latest unstable?

**Comment by mjlbach** [comment]
I still have the issue with redis unfortunately

**Comment by mjlbach** [comment]
@rht this seems to work

shell.nix
```
let
  pkgs = import <nixpkgs> {};
in
pkgs.mkShell {
  buildInputs = (with pkgs.python3.pkgs; [
    pip
    setuptools
    pyopengl
    opencv4
  ]) ++ (with pkgs ; [
    glxinfo
    cmake
    gdb
    binutils
    stdenv
    wget
    dpkg
    nix-index
  ]);
  shellHook = ''
    export LD_LIBRARY_PATH=${pkgs.libGL}/lib:${pkgs.libGLU}/lib:${pkgs.freeglut}/lib:${pkgs.xorg.libX11}/lib:${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.cudatoolkit_10_1}/lib:${pkgs.cudnn_c    udatoolkit_10_1}/lib:${pkgs.cudatoolkit_10_1.lib}/lib:$LD_LIBRARY_PATH
    alias pip="PIP_PREFIX='$(pwd)/_build/pip_packages' TMPDIR='$HOME' \pip"
    export PYTHONPATH="$(pwd)/_build/pip_packages/lib/python3.7/site-packages:$PYTHONPATH"
    export TMPDIR=$HOME/.cache
    export PATH="$(pwd)/_build/pip_packages/bin:$PATH"
    unset SOURCE_DATE_EPOCH
  '';
}
```

```
nix-shell
pip install ray
```

```
patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" ./_build/pip_packages/lib/python3.7/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server
patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" ./_build/pip_packages/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server
patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" ./_build/pip_packages/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet
patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" ./_build/pip_packages/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet_monitor
patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" ./_build/pip_packages/lib/python3.7/site-packages/ray/core/src/plasma/plasma_store_server
```
```
python
import ray
ray.init()
```

**Comment by rht** [comment]
I see, the `patchelf`s fixed it.

**Comment by siraben** [comment]
Still important to me.

**Comment by TheAncientGoat** [comment]
In case anyone is still looking for this - it is packaged in python-on-nix https://python.on-nix.com/projects/ray-latest-python39/
