### ISSUE TITLE
Kicad: pcbnew segfault when searching for a footprint.

### ISSUE THREAD

**Issue by Evils-Devils** [NixOS/nixpkgs#72248]
**Describe the bug**
As originally reported by @Kiwi on IRC:
Kicad's pcbnew segfaults without indication of reason, when searching for a footprint.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `nix-shell  -p kicad --pure --command pcbnew`
2. Place -> Footprint -> click in the workspace -> search for "dip 14"
  (this term seems very reliable in inducing the issue, but is not guaranteed to work every time)
3. observe a segmentation fault.

**Expected behaviour**
Search should return a list of footprints matching the term, with a preview of the top result.

**Additional context**
@tokudan on IRC was unable to reproduce the issue on the same package (same hash)

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 20.03.git.2d5fd65 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.03.173522.021d733ea3f"`
 - channels(evils): `"nixos-19.09-19.09.907.f6dac808387, nixpkgs-20.03pre197736.91d5b3f07d2"`
 - nixpkgs: `/home/evils/.nix-defexpr/channels/nixpkgs`
```
Maintainer information:
i am unsure what to fill in here
CC @berce though they seem inactive, they're listed as the maintainer

**Things tried**
- Fix all the warnings that occurred between starting pcbnew and the segmentation fault
- Use python3
- Tried wxGTK31 (introduced another issue but didn't solve this one)
- Added a debug build option and had a look at it with `gdb`

all [here](https://github.com/Evils-Devils/nixpkgs/blob/kicad-unstable/pkgs/applications/science/electronics/kicad/unstable.nix).

I also tried kicad from nix on debian, this fails as well, but immediately on starting pcbnew, with a bunch of fontconfig warnings and errors followed by `ImportError: No module named _sysconfigdata_nd` and segmentation fault, this is probably a separate issue.

And i asked on IRC #kicad, someone else reported having this issue on debian10 when using xfwm. (i use `i3`)

**Comment by Kiwi** [comment]
I have (at this time) only one thing to add. If you manage to place a footprint successfully, either by not searching and instead scrolling through the list to the one you want, or if it happens to be a rare time it doesn't crash while searching; I don't think I've had any experiences where it did not crash on the next action, give or take. I'm quite confident I've never been able to place 2. If I have I wasn't able to save before it did crash, that's for sure :<

**Comment by matthuszagh** [comment]
I've submitted a [PR updating KiCad to Python 3](https://github.com/NixOS/nixpkgs/pull/72813#issue-336578249). I'm not sure this will fix your issue, but might be worth giving it a shot.

**Comment by Evils-Devils** [comment]
thanks for letting me know
it unfortunately does not fix this issue
