### ISSUE TITLE
redshift service not working

### ISSUE THREAD

**Issue by StillerHarpo** [NixOS/nixpkgs#72270]
**Describe the bug**
When i try to start the redshift service i got the error

``Failed to start redshift.service: Unit redshift.service not found.``

The service file exists in /run/current-system/etc/systemd/user/redshift.service

relevant part in nixos config

```nix
redshift = {
      enable = true;
      brightness = {
        day = "0.8";
        night = "0.7";
      };
      temperature.night = 1501;
    };

```

**To Reproduce**
1. enable redshift in nixos config
2. run ``sudo nixos-rebuild test``
2. run ``systemctl --user start redshift.serice``

**Expected behavior**
redshift is starting

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.941.27a5ddcf747 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.941.27a5ddcf747, nixos-unstable-19.09pre183832.20b993ef2c9"`
 - channels(florian): `"home-manager, nixos-19.03.173489.af5481e9b77, nixos-unstable-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: redshift
```

**Comment by prusnak** [comment]
cc maintainers @yegortimoshenko @globin

**Comment by ajs124** [comment]
Weird, this works for me. Do you have `location` set?

**Comment by StillerHarpo** [comment]
Yes, `location` is set. The right coordinats are also in `/run/current-system/etc/systemd/user/redshift.service`

**Comment by rnhmjoj** [comment]
@StillerHarpo can you post the log `journalctl --user -u redshift`?

**Comment by rnhmjoj** [comment]
Does the directory `/nix/store/g5gp928z33yl0mxhg5prgq0cp5ky2vgw-unit-redshift.service/` exists?
If it does not then I'd say it has been garbage-collected but your systemd configuration still points to that one.

**Comment by StillerHarpo** [comment]
No, it doesn't exist.

**Comment by rnhmjoj** [comment]
Do you have any symlink that points to the nix store in `~/.config/systemd/user/default.target.wants/`?

**Comment by StillerHarpo** [comment]
No, i don't have the directory but i had symlinks in ```~/.config/systemd/user```. One of them was redshift.service.  All services in this directory didn't work.  After i deleted the links the problem was solved. Thanks for the help.
