### ISSUE TITLE
appimage-run: GLib-GIO-ERROR**: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by Vonfry** [NixOS/nixpkgs#72282]
**Describe the bug**

I run pCloud.appimage with `appimage-run <path-to-this>` and get an error with `GLib-GIO-ERROR**: No GSettings schemas are installed on the system` when I do some action such as add a sync path.

I have tried to add `gsettings-desktop-schemas` and other packages such as `fuse` into `extraPkgs` by using `appimage-run.override`, but this problem is continuous.

This problem may appear on other appimages which use gsetting schemas.

**To Reproduce**
1. Download pCloud.appimage from [here](https://www.pcloud.com/en/download-free-online-cloud-file-storage.html)
2. override appimage-run with the necessary packages such as `fuse gsettings-desktop-schemas`
3. run this appimage and click sync -> add folder

**Expected behavior**

Open a diaglog.

**Additional context**
My desktop manager is just sddm which is used on login, and run softwares in xmonad. Something like Gnome or KDE isn't used but the qt and gtk lib is installed by nix with dependencies automatically.

**Metadata**
`nix run nixpkgs.nix-info -c nix-info -m`
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.941.27a5ddcf747 (Loris)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.941.27a5ddcf747, nixos-unstable-20.03pre198214.4cd2cb43fb3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matthewbauer** [comment]
Just adding gsettings-desktop-schemas is probably not enough. You will also need to append `${pkgs.gsettings-desktop-schemas}/share` to `XDG_DATA_DIRS`. I'm not sure if we have an easy way to do that in appimage though.

**Comment by Vonfry** [comment]
@matthewbauer I have tried to add `${pkgs.gsettings-desktop-schemas/share` to `XDG_DATA_DIRS` in xsession and my shell profiles, but this problem is still after restarting display-manager.

**Comment by jtojnar** [comment]
It will be `${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}` or something like that.

**Comment by Vonfry** [comment]
@jtobin Thanks, it can work now. I get a reference from [here](https://github.com/NixOS/nixpkgs/blob/2e87260fafdd3d18aa1719246fd704b35e55b0f2/pkgs/applications/misc/joplin-desktop/default.nix#L16).

And I write a script to automatically export these variables of gtk and gsettings-schemas which are linked by appimage).

**Comment by piotr-szegda** [comment]
@Vonfry: Would you kindly share whole pCloud config? In my case pCloudDrive is empty and don't have any error message. Including fuse to appimage don't help.

**Comment by Vonfry** [comment]
@piotr-szegda Could you choose the sync dir? The following script maybe works for you. But I also cannot choose a pCloudDirver, and that dir is empty. I have moved my data from it and use syncthing instead.

```
if [ -f /etc/NIXOS ];then
    requisites=$(nix-store --query --requisites --quiet --quiet $(which appimage-run))
    gsettings_schemas_path=$(echo $requisites | grep gsettings-desktop-schemas | head -n1)
    gtk_path=$(echo $requisites | grep gtk+3 | head -n1)
    eval $(nix-store --print-env $(nix-store -qd $gsettings_schemas_path) | grep "export name")
    gsettings_schemas_name=$name
    eval $(nix-store --print-env $(nix-store -qd $gtk_path) | grep "export name")
    gtk_name=$name
    export XDG_DATA_DIRS=$gsettings_schemas_path/share/gsettings-schemas/$gsettings_schemas_name:$gtk_path/share/gsettings-schemas/$gtk_name:$XDG_DATA_DIRS
    unset name
    unset requisites
    unset gsettings_schemas_path
    unset gtk_path
    unset gsettings_schemas_name
    unset gtk_name
fi
```

**Comment by piotr-szegda** [comment]
@Vonfry  Yes, I was able to choose sync directory thanks to your previous comment. I was hoping you manage to run fuse based pCloudDrive directory.
For now I use rclone fuse adapter but it is much slower then pCloud app adapter. Now I can test sync directory option.

Any way thanks for script because is much better than my. :+1:

**Comment by DavHau** [comment]
@Vonfry could you share the exact nix expression needed to make this work? I'm facing the same issue. Maybe this should be upstreamed?

**Comment by Vonfry** [comment]
Sorry, I don't use appimage any longer. 

And in the past, I just pack appimage with its dependencies and export environment in shell script to make it running.

**Comment by AleXoundOS** [comment]
@Vonfry, I had to fix the script, otherwise it didn't work:

```shell
requisites=$(nix-store --query --requisites --quiet --quiet $(readlink -f $(type -p java)))
gsettings_schemas_path=$(echo $requisites | grep -o -E [^[:space:]]*gsettings-desktop-schemas[^[:space:]]*)
gtk_path=$(echo $requisites | grep -o -E [^[:space:]]*gtk\\+3[^[:space:]]*)
eval $(nix-store --print-env $(nix-store -qd $gsettings_schemas_path) | grep "export name")
gsettings_schemas_name=$name
eval $(nix-store --print-env $(nix-store -qd $gtk_path) | grep "export name")
gtk_name=$name
export XDG_DATA_DIRS=$gsettings_schemas_path/share/gsettings-schemas/$gsettings_schemas_name:$gtk_path/share/gsettings-schemas/$gtk_name:$XDG_DATA_DIRS
unset name
unset requisites
unset gsettings_schemas_path
unset gtk_path
unset gsettings_schemas_name
unset gtk_name

java -jar circuit.jar
```

_In my case it's a java program, but it doesn't matter (just a different binary name)._

**Comment by AleXoundOS** [comment]
Small update, because `nix-store -qd` fails for some reason on Nix 2.11.1, but `nix show-derivation` works fine.
```bash
requisites=$(nix-store --query --requisites --quiet --quiet $(readlink -f $(type -p java)))
gsettings_schemas_path=$(echo $requisites | grep -o -E [^[:space:]]*gsettings-desktop-schemas[^[:space:]]*)
gtk_path=$(echo $requisites | grep -o -E [^[:space:]]*gtk\\+3[^[:space:]]*)
eval $(nix-store --print-env $(nix show-derivation $gsettings_schemas_path | tail -n+2 | head -n1 | cut -d\" -f2) | grep "export name")
gsettings_schemas_name=$name
eval $(nix-store --print-env $(nix show-derivation $gtk_path | tail -n+2 | head -n1 | cut -d\" -f2) | grep "export name")
gtk_name=$name
export XDG_DATA_DIRS=$gsettings_schemas_path/share/gsettings-schemas/$gsettings_schemas_name:$gtk_path/share/gsettings-schemas/$gtk_name:$XDG_DATA_DIRS
echo "$XDG_DATA_DIRS"
unset name
unset requisites
unset gsettings_schemas_path
unset gtk_path
unset gsettings_schemas_name
unset gtk_name

java -jar circuit.jar
```
