### ISSUE TITLE
Anki 2.1.15 fails to launch on 19.09 with “Error loading graphics driver…”

### ISSUE THREAD

**Issue by ninjin** [NixOS/nixpkgs#72311]
**Describe the bug**
When you launch Anki (2.1.15) on 19.09 it crashes with “Error loading graphics driver…” and you are left with the following in your terminal:

```
> anki
qt: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Aborted (core dumped)
```

**To Reproduce**
1. Run NixOS 19.09
2. Install and launch Anki
3. Observe crash

**Expected behavior**
Launching Anki successfully.

**Additional context**
Just to make sure I removed my local Anki decks, but this had no effect on the issue.

**Metadata**

```
> nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.976.c75de8bc12c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ivan** [comment]
anki starts on 19.09 for me with NVIDIA.

Which graphics driver are you using?

Does WebGL work in your browser?

Does this go away if you reboot? After upgrading, sometimes there are kernel module mismatches until you reboot.

**Comment by ninjin** [comment]
@ivan I am on the NVIDIA drivers as well and you are correct, it was indeed most likely a kernel module mismatch that not get corrected until I performed a reboot. Thank you, lesson learned (reboot desktops after an upgrade), and closing the issue.

**Comment by Leo3965** [comment]
I am on the AMD drives, and I'm having this issue as well

**Comment by ninjin** [comment]
On Sun 04 Jul 2021, Léo Freitas wrote:
> 
> I am on the AMD drives, and I'm having this issue as well

@Leo3965 Did a reboot resolve it? If not, I suspect the cause of your issue is different than what I observed back in Autumn 2019.
