### ISSUE TITLE
Package libabigail

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#72341]
**Project description**
Framework which aims at helping developers and software distributors to spot some ABI-related issues like interface incompatibility in ELF shared libraries by performing a static analysis of the ELF binaries at hand.

**Metadata**

* homepage URL: https://sourceware.org/libabigail/
* source URL: http://mirrors.kernel.org/sourceware/libabigail/libabigail-1.6.tar.gz
* license: `lgpl3Plus`
* platforms: linux or unix

**Comment by prusnak** [comment]
I created the initial packaging here: https://github.com/prusnak/nixpkgs/commit/5b4cc24fd865571891cbe3572f4181300db0e67a

The configuration is here:

```
    Prefix                                         : /nix/store/zalymvcg1s62hizva6918b5m5jjp3ajq-libabigail-1.6
    Source code location                           : .
    C Compiler                                     : gcc
    C++ Compiler                                   : g++
    GCC visibility attribute supported             : yes
    Python                                         : no

 OPTIONAL FEATURES:
    Enable zip archives                            : no
    Use a C++-11 compiler                          : no
    libdw has the dwarf_getalt function            : yes
    Enable rpm support in abipkgdiff               : no
    Enable deb support in abipkgdiff               : no
    Enable GNU tar archive support in abipkgdiff   : yes
    Enable bash completion                         : no
    Enable fedabipkgdiff                           : no
    Enable python 3                                : no
    Enable running tests under Valgrind            : no
    Generate html apidoc                           : no
    Generate html manual                           : no
```

but still the build ends up with:

```
g++: error: /usr/lib/rpm/redhat/redhat-hardened-ld: No such file or directory
```

**Comment by jtojnar** [comment]
Thank you for taking a look at this. Bash-completions would be nice. I do not also see a reason not to use C++11, looking at the source code it might add some extra tools for visualization. I have no idea why it fails with the error but since I cannot grep hardened in git://sourceware.org/git/libabigail.git, perhaps it is an artefact of the tarball. Perhaps try adding `autoreconfHook` to `nativeBuildInputs` to re-generate the `configure` script. And while at it, could you move `pkg-config` there as well?

**Comment by prusnak** [comment]
@jtojnar I won't have time for any changes until the end of this week, so in case you need it sooner, I suggest you take what I already have and build on top of that.
