### ISSUE TITLE
AccountsService in NixOS ignores vendor extensions

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#72396]
**Describe the bug**
AccountsService refuses to read the extensions files, and emits this warning
```
Found accounts service vendor extension symlink /nix/store/vp9g8f3467sf8s18v8aahmfkghpf6l3k-system-path/share/accountsservice/interfaces/io.elementary.pantheon.AccountsService.xml, but it must be exactly equal to '../../dbus-1/interfaces/io.elementary.pantheon.AccountsService.xml' for forwards-compatibility reasons.
Found accounts service vendor extension symlink /nix/store/vp9g8f3467sf8s18v8aahmfkghpf6l3k-system-path/share/accountsservice/interfaces/org.freedesktop.DisplayManager.AccountsService.xml, but it must be exactly equal to '../../dbus-1/interfaces/org.freedesktop.DisplayManager.AccountsService.xml' for forwards-compatibility reasons.
```

This why I believe people noticed https://github.com/NixOS/nixpkgs/issues/45059 issue, because `org.freedesktop.DisplayManager.AccountsService` from lightdm won't exist because of this.

This is particularly problematic for Pantheon, which plans to use AccountsService extensions for a variety of things, and currently for a harmonized time_format setting.

The actual warning in the source code is at
* https://gitlab.freedesktop.org/accountsservice/accountsservice/blob/master/src/extensions.c#L130

and it's because this
```
if (g_str_has_prefix (symlink, prefix) && g_str_equal (symlink + strlen (prefix), name))
```

returns false.

These symlinks checks are tricky for NixOS, where the symlink they expect is a symlink to a symlink to a... :smile:

**Comment by worldofpeace** [comment]
cc @jtojnar.

**Comment by jtojnar** [comment]
I would just drop the checks. The assumptions might not make sense even with FHS systems, since AccountsService uses XDG_DATA_DIRS to find the extensions.

**Comment by worldofpeace** [comment]
@jtojnar I think we could drop the `/* Ensure it looks like "../../dbus-1/interfaces/${name}" */`  then.
