### ISSUE TITLE
Doc: How to check that "all depending packages build"

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#72403]
**Describe the bug**

The documentation states that i should check that "all depending packages build". But how?

https://nixos.org/nixpkgs/manual/#chap-reviewing-contributions

The "Building the package locally." point has two options: doing it manually and rebasing onto nixos-unstable or using nix-review.

The manual part leaves you with a nixpkgs checkout. Please explain how to build a package (nix build ...) AND how to build all depending packages.

Does nix-review build all depending packages? If so, please add that information there! Of not, explain how to do it.

**Comment by jonringer** [comment]
nix-review will evaluate all of nixpkgs before and after the changes. Then for the the derivations that differ, it will build them, effectively testing all derivations what get recursed into.

**Comment by Enteee** [comment]
I am not quite sure what's todo here. Checked the documentation and for me the section is pretty clear about how and when to do what. If you could maybe make a suggestion what and how you would improve the doc @davidak. Otherwise I'd suggest closing this issue.

**Comment by jonringer** [comment]
The line you're referring to is for adding a new package, and if that's the case, there's no dependent packages.

Also, the PR template now includes the `nix-review` command as one of the checklist items
