### ISSUE TITLE
Thunderbird has no Wayland support

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#72405]
**Describe the bug**
Thunderbird supports Wayland upstream, as well as in other distros such as Gentoo[1], but that support is disabled in NixOS. 

\[1\]: https://gitweb.gentoo.org/repo/gentoo.git/tree/mail-client/thunderbird/thunderbird-68.2.1.ebuild#n512

**To Reproduce**
1. Setup / use Wayland WM (such as Sway)
2. Install pkgs.thunderbird
3. See that it runs on xWayland and is blurry on HiDPI displays.

**Expected behavior**
I expected Thundrbird to respect `MOZ_ENABLE_WAYLAND` and launched in wayland-native form.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 20.03pre199922.2f92befaf36 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre199922.2f92befaf36"`
 - channels(bemeurer): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute: thunderbird
```

**Comment by layus** [comment]
From what I can tell, thunderbird is already built with wayland support in nixpkgs. However, for it to actually use the wayland backend, you need to start it with `MOZ_ENABLE_WAYLAND=1`. Would you mind testing if adding MOZ_ENABLE_WAYLAND works for you ?
In that case we could add MOZ_ENABLE_WAYLAND to the wrapper.

**Comment by lovesegfault** [comment]
I fixed this myself in https://github.com/NixOS/nixpkgs/pull/75328 and forgot to close the issue. Thanks for the reminder!
