### ISSUE TITLE
setBlocking on Node 0.12.2

### ISSUE THREAD

**Issue by bflyblue** [NixOS/nixpkgs#7243]
I'm not sure if this is a problem upstream with Node 0.12.2 or with nixpkgs..

Trying to install purescript fails during the check phase with:
```
net.js:164
        throw errnoException(err, 'setBlocking');
              ^
Error: setBlocking ENOSYS
```

The change to Node shows line 164 should be wrapped in a `process.platform === 'win32'` condition and yet this is failing on NixOS and nixpkgs on Darwin for me.

Related Node commit (lib/net.js): https://github.com/joyent/node/commit/20176a98416353d4596900793f739d5ebf4f0ee1

Using 0.12.1 correctly installs purescript.

**Comment by obadz** [comment]
Latest unstable release ( 6ad8fab785695d04a6925e8b3464ca7c71a85c3f ) has this issue.
