### ISSUE TITLE
Bluetooth headsets require manual restart of daemon-reload/pulseaudio

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixpkgs#72436]
**Describe the bug**
This bug report is to solve the issue described in the NixOS wiki here https://nixos.wiki/wiki/Bluetooth, specifically

> You will need to restart PulseAudio; try systemctl --user daemon-reload; systemctl --user restart pulseaudio. 

This issue occurs when you try and connect headsets via bluetooth when using pulseaudio. Sometimes you can't hear anything and running

```sh
systemctl --user daemon-reload; systemctl --user restart pulseaudio. 
```

temporarily solves the issue.

**To Reproduce**
1. Connect bluetooth earphones
2. Sometimes audio does not play through the earphone

**Expected behavior**
For bluetooth earphones/headphones to consistently work pairing them without manually having to run `systemctl --user daemon-reload; systemctl --user restart pulseaudio` as a workaround.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7, NixOS, 20.03pre198214.4cd2cb43fb3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre198214.4cd2cb43fb3, nixpkgs-unstable-20.03pre197053.d08a7431561"`
 - channels(mdedetrich): `"nixpkgs-19.09pre188239.c0e56afddbc"`
 - nixpkgs: `/home/mdedetrich/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
Relevant nix configuration
```
  hardware.pulseaudio = {
    enable = true;
    support32Bit = true;
    extraModules = [ pkgs.pulseaudio-modules-bt ];
    package = pkgs.pulseaudioFull;
    tcp = {
      enable = true;
      anonymousClients.allowedIpRanges = ["127.0.0.1"];
    };
  };

  hardware.bluetooth = {
    enable = true;
  };

```

**Comment by adisbladis** [comment]
I believe your issue may be fixed by https://github.com/NixOS/nixpkgs/pull/69460

**Comment by mdedetrich** [comment]
Yes I suspect thats the case, I will try out the new bluez once its in nixos-unstable

**Comment by adisbladis** [comment]
I'm closing this as it's marked as stale and possibly already fixed. Feel free to reopen or drop a comment so I can reopen.
