### ISSUE TITLE
Disabling ipv6 globally does not apply to all adapters

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#72451]
NixOS version: 19.09

I disabled ipv6 via `networking.enableIPv6 = false;` like described in the manual, but it doesn't apply for my wifi adapter as you can see:

```
$ sudo sysctl -a | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.br-7e76217ab500.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.docker0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.tun0.disable_ipv6 = 1
net.ipv6.conf.tun1.disable_ipv6 = 1
net.ipv6.conf.vboxnet0.disable_ipv6 = 1
net.ipv6.conf.virbr0.disable_ipv6 = 1
net.ipv6.conf.virbr0-nic.disable_ipv6 = 1
net.ipv6.conf.wlp2s0.disable_ipv6 = 0

```

The interface has ipv6 addresses and when I try to ping google it uses ipv6.

**Comment by jwygoda** [comment]
I'm experiencing the same issue. I had to apply a manual fix on a single interface using a normal sysctl.
`net.ipv6.conf.wlp2s0.disable_ipv6`

**Comment by DavHau** [comment]
Still an issue in nixos 20.03 as of now

**Comment by DavHau** [comment]
Closing in favor of duplicate issue: https://github.com/NixOS/nixpkgs/issues/87802
