### ISSUE TITLE
Packaging requests: IfcOpenShell (python module)

### ISSUE THREAD

**Issue by PlumpMath** [NixOS/nixpkgs#72468]
**Project description**
Open source IFC library and geometry engine
base c++
http://ifcopenshell.org/python.html

**Metadata**

* homepage URL: http://ifcopenshell.org/
* source URL: https://github.com/IfcOpenShell/IfcOpenShell
* license: lgpl 3.0
* platforms: linux

**Comment by luzpaz** [comment]
This package would be great to have

**Comment by luzpaz** [comment]
soft bump

**Comment by PlumpMath** [comment]
Hello @luzpaz & nix community.

I'm open ifcopenshell build code. :)
linux (compile master source version). 
& 
MacOS + nix (binary version)
but, I don't know GitHub PR :b 
help me~*.
(comment is I study nix code.)
-----------------------------------------

    ifcopenshell = if (!stdenv.isDarwin) then (toPythonModule (stdenv.mkDerivation rec {
      pname = "ifcopenshell";
      version = "master";
      src = fetchFromGitHub {
        owner = "IfcOpenShell";
        repo = "IfcOpenShell";
        rev = version;
        sha256="12f9vg2rbld3gzjqiw7bb2p0m2sq2aqps1fgzdyyab3qqfficsr5";
      };
      propagatedBuildInputs = [ python37  ];
      buildInputs = with xorg; [ cmake  opencascade opencollada pcre boost icu swig ]; #python37 gcc8
      # https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/cmake/setup-hook.sh
      dontUseCmakeBuildDir = true; # build 폴더를 만들고 들어가서, cmake ../cmake 명령을 날리므로.
      # dontStrip = true;                
      # /MakeTEMP
      cmakeFlags = [
        "-DCMAKE_BUILD_TYPE=Release"
        "-DOCC_LIBRARY_DIR=${opencascade}/lib"
        "-DOCC_INCLUDE_DIR=${opencascade}/include/oce"
        "-DOPENCOLLADA_LIBRARY_DIR=${opencollada}/lib/opencollada"
        "-DOPENCOLLADA_INCLUDE_DIR=${opencollada}/include/opencollada"
        "-Wno-dev"
	    ];
      # "-DCMAKE_INSTALL_PREFIX=$(pwd)/bTEMP"
      # mkdir -pv build/distPY
      CONF = "/ASDF";        
      preConfigure = ''
        mkdir -pv build/Install
        pushd build
        # ---------------------------
        # cmakeDir=../cmake    # USE below & USE only "cmakeFlags"
        # ---------------------------
        cmake ../cmake \
        -DCMAKE_INSTALL_PREFIX=${CONF} \
        $cmakeFlags
      '';
      # -DCMAKE_INSTALL_PREFIX=$(pwd)/Install \
      # #
      PREV="${python37}/${python37.sitePackages}";
      # AF="${python37.sitePackages}";        
      # ${python37.sitePackages}  lib/python3.7/site-packages
      # ${python37}    /nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5
      # ---------------------------
      # mkdir -p $out/IFC-PY        
      installPhase = ''        
        mkdir -p $out
        mkdir -pv $out/${python37.sitePackages}
        # ---------------------------
        sed -i "s|${CONF}|$out|g" $(pwd)/cmake_install.cmake
        sed -i "s|${CONF}|$out|g" $(pwd)/examples/cmake_install.cmake
        # ---------------------------
        sed -i "s|${PREV}|$out/${python37.sitePackages}|g" $(pwd)/ifcwrap/cmake_install.cmake
        # ---------------------------
        make install
      '';
      # cd $(pwd)/Install
      # cp -rf ./* $out/
      # ---------------------------    
      # cp -r $(pwd)/Install/* $out
      # cp -rf $(pwd)/distPY/* $out/IFC-PY
      # ---------------------------
      # Reference: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libjson-rpc-cpp/default.nix>
      enableParallelBuilding = true;
      # "-DBoost_INCLUDE_DIR=${boost.dev}/include"
      # "-DPCRE_LIBRARY_DIR=${pcre}"
      # ---------------------------
      #   mkdir -pv $out/${python37.sitePackages}/ifcopenshell
      #   ln -sf $out/!(bin|lib) $out/bin/
      #   ln -sf $out/lib/ifcopenshell/ifcwrap/* $out/${python37.sitePackages}/ifcopenshell/
    })) else (
      buildPythonPackage rec {
        pname = "ifcopenshell";
        version = "0.6.0";
        src = fetchurl {
          url = "https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-e9a9c1a-macos64.zip";
          sha256 = "1c52wpw3j3l6j5drvg0iqj3b3h5vlcy1lbpha05rggiwfsxqbvvx";
        };
        dontBuild = true;
        doCheck = false;
        setSourceRoot = "sourceRoot=`pwd`"; # unzip 바이너리 패키지 참조:      
        buildInputs = with pkgs; [  unzip ];      # makeWrapper
        installPhase = ''
          mkdir -pv $out/${python37.sitePackages}
          unzip $src -d $out/${python37.sitePackages}
        '';        
      });
