### ISSUE TITLE
Packaging requests: CadQuery (python module)

### ISSUE THREAD

**Issue by PlumpMath** [NixOS/nixpkgs#72466]
**Project description**
A parametric CAD scripting framework based on PythonOCC

**Metadata**

* homepage URL: https://github.com/CadQuery/cadquery
* source URL: https://github.com/CadQuery/cadquery
* license: Apache 2.0
* platforms: cross-platform python

**Comment by marcus7070** [comment]
I've packaged CadQuery in https://github.com/NixOS/nixpkgs/pull/66254, just waiting for it to be merged. I'd appreciate some attention on the PR, it's been open for 3 months now.

**Comment by PlumpMath** [comment]
https://github.com/marcus7070/nixpkgs/blob/cadquery-and-friends-init/pkgs/development/python-modules/cadquery/default.nix

can't still import cardery with Python module, 
but maybe someday :)

**Comment by PlumpMath** [comment]
I success!!. Import cadquery;;;

Phew~ It was hard. I did it in a slightly different way~*
It's too hard. nixOS but I like it..;

after... I will try to install ifcOpenShell-python...soon.
Darkness. Y,.y

Either way, cadquery & cq-editor
Thank you so much for installing help me.
Thanks a lot. :) good day~*

2019년 11월 20일 (수) 오후 12:07, Marcus Boyd <notifications@github.com>님이 작성:

**Comment by marcus7070** [comment]
#66254 has been merged, this can be closed.
