### ISSUE TITLE
Update systemd oneshot Restart warning on next systemd release

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#72515]
We currently have this logic

https://github.com/NixOS/nixpkgs/blob/f2f36822ca740292f6005fe29e0fe2eddfb949c9/nixos/modules/system/boot/systemd.nix#L786-L787

that emits

```
trace: warning: Service ‘consulReady.service’ with ‘Type=oneshot’ must have ‘Restart=no’
```

if you have `Restart = "no"` on a `type = "oneshot"` service.

With the upstream change https://github.com/systemd/systemd/pull/13754 that restriction will be relaxed.

We should update the warning once that lands as part of the next systemd release.

**Comment by nh2** [comment]
The upstream change was released as part of systemd `v244`. Right now nixpkgs is still on `v243`: https://github.com/NixOS/nixpkgs/blob/7f2ce879d2058951e579ebf19bb8ea5dfca8fe5f/pkgs/os-specific/linux/systemd/default.nix#L33

**Comment by flokli** [comment]
@maralorn this has been implemented in https://github.com/NixOS/nixpkgs/pull/90604, hasn't it?

**Comment by maralorn** [comment]
Yes, this is fixed on master.

**Comment by maralorn** [comment]
But I don‘t have the rights to close this issue. :-(

**Comment by flokli** [comment]
Alright, closed :-)
