### ISSUE TITLE
google-chrome-stable crashes when interacting with filesystem

### ISSUE THREAD

**Issue by Sophia-Gold** [NixOS/nixpkgs#72512]
**Describe the bug**
`google-chrome-stable` 77.0.3865.120 crashes when attempting to interact with the filesystem. Appears to be the same as in https://github.com/NixOS/nixpkgs/issues/51870. 

**Steps to reproduce the behavior:**
Attempt to upload, download, or print a file from Chrome.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.10, NixOS, 19.09.840.8bf142e001b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.840.8bf142e001b, nixos-hardware, unstable-20.03pre196836.1c40ee6fc44"`
 - channels(sophia): `"nixos-19.09pre174426.acbdaa569f4, nixos-18.09-18.09.2505.46d3867a08a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
@Sophia-Gold Can you run the executable in a terminal and paste the output?

And if I'm understanding correctly, the program crashes when opening some sort of file dialog?

**Comment by Sophia-Gold** [comment]
Hmm...I don't have this issue when it's launched from terminal. Might be a problem with either `gnome3` or `i3`? I also cannot launch some applications from GNOME that work fine from terminal.

**Comment by angordeyev** [comment]
I do not have this issue on KDE either. Can you paste your minimal config that causes the issue?

**Comment by FliegendeWurst** [comment]
Works for me on NixOS 21.11
