### ISSUE TITLE
Make journald restart unconditionally when it crashes

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#72510]
## Issue description

When the system is under memory pressure, `systemd-journald` often fails because is `malloc()`s fail, and shuts down (not this is diffent from the Linux OOM killer).

Then I observe on my system that it dies and is never restarted by systemd; I cannot see any logs because, well, journald is dead.

`systemctl cat systemd-journald.service` shows that it has `Restart = always` by default as provided by upstream systemd, but contrary to the name that is not enough to make a systemd service restart forever; it will give up after a couple of tries.

It needs `StartLimitIntervalSec = 0` in the unit config, otherwise the restart counter will prevent the service from retrying to restart indefinitely after a few tries.

Many NixOS services have this problem, but for `journald` it's especially severe because you can't investigate what is going on when `journald` itself stops working.

### Steps to reproduce

`for i in {1..50}; do kill $(pidof systemd-journald); sleep 0.1; echo $i; done`

After this, `systemctl status systemd-journald.service` will show that it's dead, and logging on the system will cease.

**Comment by nh2** [comment]
I propose that we fix it in NixOS by adding to the default config:

```nix
# ensure Restart=always is always honoured
systemd.services.systemd-journald.unitConfig.StartLimitIntervalSec = 0;
```

**Comment by nh2** [comment]
CC @flokli

**Comment by flokli** [comment]
Did you check how other distros handle this?

Would they experience similar behaviour in your system configuration?

Maybe it'd make sense to fix this in upstream systemd...

**Comment by nh2** [comment]
> Did you check how other distros handle this?

I've checked on Ubuntu, which uses the same upstream-provided [`systemd-journald.service.in`](https://github.com/systemd/systemd/blob/df957acc6603a04e62dee7e911c65dc7dbcb6208/units/systemd-journald.service.in), so will suffer from the same symptoms.

> Maybe it'd make sense to fix this in upstream systemd...

I've asked upstream at #13922.

**Comment by lovesegfault** [comment]
@nh2 I think your link should be: https://github.com/systemd/systemd/issues/13922

**Comment by flokli** [comment]
As upstream replied in https://github.com/systemd/systemd/issues/13922#issuecomment-549163561, we shouldn't change StartLimitIntervalSec:

> If journald keeps restarting in a busy loop, then we should eventually give up. There's no value in consuming all CPU with constant restarting, if it never works.
> 
> so, I am strongly against dropping the start limit. If anything we might consider bumping it a bit, but quite frankly I am not sure this is worth it, given that your example is synthetic and memory pressure won't trigger this at all...

If you want something like this, it should be part of your configuration, but we shouldn't add it to NixOS.
