### ISSUE TITLE
Request to package jupyter-contrib-nbextensions

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#72750]
**Project description**

The jupyter-contrib-nbextensions adds a lot of unofficial notebook extensions to the jupyter environment. One of the useful ones the table of contents extension. There's already a vega extension in Nixpkgs, so we should add this one as well.

**Metadata**

* homepage URL: https://github.com/ipython-contrib/jupyter_contrib_nbextensions
* source URL: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html
* license: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/COPYING.rst
* platforms: unix, linux, darwin, ...

**Comment by teto** [comment]
Have you checked https://github.com/tweag/jupyterWith ? they have something called jupyter_nbextensions_configurator in nix/python-overlay.nix

**Comment by CMCDragonkai** [comment]
Interesting. I'm just following how the existing jupyter extensions are packaged.

**Comment by linminhtoo** [comment]
any fixes ?

**Comment by natsukium** [comment]
introduced in https://github.com/NixOS/nixpkgs/pull/243220
