### ISSUE TITLE
fwupdmgr  Failed to connect to daemon: Error calling StartServiceByName for org.freedesktop.fwupd:

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#72775]
**Describe the bug**
Error during a run of the fwupdmgr
**Failed to connect to daemon: Error calling StartServiceByName for org.freedesktop.fwupd: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit fwupd.service not found.**

**To Reproduce**
Steps to reproduce the behaviour:
1. install package fwupd
2. run fwupdmgr

**Expected behaviour**
run the application

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 19.09.1019.c5aabb0d603 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1019.c5aabb0d603, home-manager, unstable-20.03pre196586.b943338ea58"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
@jtojnar

The fix is to explicitly enable fwupd.enable = true;  in service
```
services.fwupd.enable = true;
```

**Comment by jtojnar** [comment]
Fwupd requires a global DBus service so it needs to be added to `services.dbus.packages` in addition to `environment.systemPackages`.the module does that for you.

**Comment by worldofpeace** [comment]
This looks resolved, closing.

**Comment by mudrii** [comment]
> services.dbus.packages

Thank you @jtojnar I was looking for more clear documentation for this and was unable to find any reference to additional entry needed. maybe make sense to update ...../fwupd/default.nix and add some comments on changes requiered to make it work.

**Comment by onny** [comment]
Created a wiki page for it https://nixos.wiki/wiki/Fwupd
