### ISSUE TITLE
Attribute nodejs.interpreterName doesn't exist

### ISSUE THREAD

**Issue by KaiSforza** [NixOS/nixpkgs#7279]
Was just doing some testing with the git repo and noticed that the nodejs package uses the attribute `nodejs.interpreterName` three times. In `pkgs/development/web/nodejs/build-node-package.nix`, `nodejs/default.nix` and `iojs/default.nix`. It seems to be being used in the first file, and set based on the nodejs implementation in the `default.nix` files. Currently this causes nix commands to fail when using the whole package derivation, as this attr is not defined.

```
# nix-env -I nixpkgs=/root/nixpkgs/ -qaP --show-trace
error: attribute ‘interpreterName’ missing, at "/root/nixpkgs/pkgs/development/web/nodejs/build-node-package.nix":7:16
```

**Comment by KaiSforza** [comment]
Commit where it was added: 97ea4ab54ed645dc0448

**Comment by KaiSforza** [comment]
And wrong flag.

**Comment by Balletie** [comment]
I have this error too, is there a reason that you closed this?

**Comment by KaiSforza** [comment]
I was using `-I...` when I was supposed to use `-f...`

**Comment by Balletie** [comment]
Thanks :)

**Comment by obadz** [comment]
I'm getting this error with NIX_PATH set to nixos-config=~/src/nix/config/configuration.nix:nixpkgs=~/src/nix/pkgs:nixos=~/src/nix/pkgs/nixos running nix-env -qa. Am I doing something wrong or does this need to be reopened?

**Comment by KaiSforza** [comment]
Are you using the latest git revision? I'm no longer getting this error with `-I` or with `NIX_PATH`.

**Comment by obadz** [comment]
I was using nixos-unstable channel (from git) so it's entirely possible they've fixed it since.

**Comment by offlinehacker** [comment]
Okay, so if it's not fixed in next unstable release, i will investigate
this problem.

**Comment by seppeljordan** [comment]
The issue persists for me

```
$ nixos-version 
15.06pre62649.f93a8ee (Dingo)
```

**Comment by obadz** [comment]
@seppeljordan - could you post the trace? thx!

**Comment by seppeljordan** [comment]
Here is the output:

```
$ nix-env -qa
error: attribute ‘interpreterName’ missing, at "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/development/web/nodejs/build-node-package.nix":7:16
```

Here is the output with `--show-trace`:

```
$ nix-env -qa --show-trace
error: attribute ‘interpreterName’ missing, at "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/development/web/nodejs/build-node-package.nix":7:16
```

**Comment by lethalman** [comment]
@seppeljordan I'm sure you are still using an old nixpkgs repo, either you are a wrong environment or you think you are pointing to the right repo or whatever. Perhaps dive more into understanding how nix-env and NIX_PATH work. Works for me on master.

**Comment by seppeljordan** [comment]
OK, I do not understand why this worked, but would be interested to know:

I noticed that the `nix-env -qa` worked just fine, when I was `root`.  So I figured that it had something to do with the nix expressions in my users profile.  I unsubscribed from stable and unstable-small
```
$ nix-channel --remove stable
$ nix-channel --remove unstable-small
```
After this everything worked just fine.  I always thought that the expressions in the several channels are self-contained and would not effect each other, so either I was wrong with that assumption or this is a bug.

**Comment by lethalman** [comment]
Wrong assumption, nix-env just chosen one of the derivation randomly.

On Wed, May 20, 2015 at 8:32 PM, Sebastian Jordan <notifications@github.com>
wrote:

> OK, I do not understand why this worked, but would be interested to know:
>
> I noticed that the nix-env -qa worked just fine, when I was root. So I
> figured that it had something to do with the nix expressions in my users
> profile. I unsubscribed from stable and unstable-small
>
> $ nix-channel --remove stable
> $ nix-channel --remove unstable-small
>
> After this everything worked just fine. I always thought that the
> expressions in the several channels are self-contained and would not effect
> each other, so either I was wrong with that assumption or this is a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/7279#issuecomment-103987909>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by obadz** [comment]
That would explain why this bug is so hard to reproduce..
