### ISSUE TITLE
19.09 OpenJDK8: wrong setup for /lib/openjdk/jre/lib/cmm directory causes NullPointerException from ICC_Profile

### ISSUE THREAD

**Issue by andrei-ilyin-mh** [NixOS/nixpkgs#72832]
**Describe the bug**
`[JDK]/lib/openjdk/jre/lib/cmm` is a symlink to `[JRE]/lib/openjdk/jre/lib/cmm` directory which causes to fail standard java.awt.color.ICC_Profile functionality under JDK.

**To Reproduce**
1. Checkout the latest 19.09 branch commit
2. Create file Test1.java with next content:
```java
import java.awt.color.ColorSpace;
import java.awt.color.ICC_Profile;

public class Test1 {
    public static void main(String[] args) {
        ICC_Profile iccProfile = ICC_Profile.getInstance(ColorSpace.CS_sRGB);
        try {
            byte[] iccData = iccProfile.getData();
            System.out.println("Data size is " + iccData.length);
        } catch (Exception e) {
            System.out.println("Failed.");
            e.printStackTrace(System.out);
        }
    }
}
```
3. Compile it using jdk
`[nix-shell]$ /nix/store/v305cmq8jm2g95a7pzwnc0khhhqxbjvl-openjdk-8u222-ga/bin/javac Test1.java`

4. Run it using java from jdk (Failed, `lib/openjdk/jre/lib/cmm/sRGB.pf` is a symlink)
```
[nix-shell]$ /nix/store/v305cmq8jm2g95a7pzwnc0khhhqxbjvl-openjdk-8u222-ga/bin/java -classpath ./ Test1
Failed.
java.lang.NullPointerException
	at sun.java2d.cmm.lcms.LCMS.getProfileSize(LCMS.java:67)
	at java.awt.color.ICC_Profile.getData(ICC_Profile.java:1330)
	at Test1.main(Test1.java:8)
```
5. Run it using jre (Success, `lib/openjdk/jre/lib/cmm/sRGB.pf` is a real file)
```
[nix-shell:~/jtests]$ /nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/bin/java -classpath ./ Test1
Data size is 6876
```

**Expected behavior**
This should run without errors under both JDK and JRE.

**Additional context**
The root cause is that `/nix/store/v305cmq8jm2g95a7pzwnc0khhhqxbjvl-openjdk-8u222-ga/lib/openjdk/jre/lib/cmm` is symlink for `/nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/lib/openjdk/jre/lib/cmm`.

```
[nix-shell:~/jtests]$ ls -a -l /nix/store/v305cmq8jm2g95a7pzwnc0khhhqxbjvl-openjdk-8u222-ga/lib/openjdk/jre/lib/cmm
lrwxrwxrwx 1 root root   98 Dec 31  1969 CIEXYZ.pf -> /nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/lib/openjdk/jre/lib/cmm/CIEXYZ.pf
lrwxrwxrwx 1 root root   96 Dec 31  1969 GRAY.pf -> /nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/lib/openjdk/jre/lib/cmm/GRAY.pf
lrwxrwxrwx 1 root root  102 Dec 31  1969 LINEAR_RGB.pf -> /nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/lib/openjdk/jre/lib/cmm/LINEAR_RGB.pf
lrwxrwxrwx 1 root root   96 Dec 31  1969 PYCC.pf -> /nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/lib/openjdk/jre/lib/cmm/PYCC.pf
lrwxrwxrwx 1 root root   96 Dec 31  1969 sRGB.pf -> /nix/store/hfh418izpgj7hx3xd6j099vyszqrrlxf-openjdk-8u222-ga-jre/lib/openjdk/jre/lib/cmm/sRGB.pf
```
For color profiles standard Java library requires real files but not symlinks. ICC_Profile resolving real file path of *.pf and skipping initialization if it is under another directory. Skipped initialization causes NullPointerException on later use of ICC_Profile functionality.

This could be fixed by additional setup of cmm directory in `pkgs/development/compilers/openjdk/8.nix`. I.E.
```sh
rm -rf $out/lib/openjdk/jre/lib/cmm
mkdir -p $out/lib/openjdk/jre/lib/cmm
cp $jre/lib/openjdk/jre/lib/cmm/* $out/lib/openjdk/jre/lib/cmm
```

**Comment by DzmitrySudnik** [comment]
Looks like the profile files handling was dropped in https://github.com/NixOS/nixpkgs/pull/65247/files#diff-85711e3c2edf6bf5c640a4fe1904daa5L176.
@lopsided98 , was there a particular reason to drop it? Can it be restored safely?

**Comment by lopsided98** [comment]
See #72843
