### ISSUE TITLE
Apache Spark

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#7286]
I'm looking for a package for Apache Spark

https://spark.apache.org/downloads.html

**Comment by spwhitt** [comment]
There's one in `pkgs/applications/networking/cluster/spark` available under the name `spark`.

**Comment by MasseGuillaume** [comment]
Thanks !
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/spark/default.nix
