### ISSUE TITLE
AArch64: latest kernel not binary-cached

### ISSUE THREAD

**Issue by MarSoft** [NixOS/nixpkgs#72880]
**Describe the bug**
I am on `nixos-19.09` channel. And I use `linuxPackages_latest.kernel` kernel on my `aarch64` board.
After I updated channel with `nixos-rebuild --upgrade`, it started building the `5.3.8` kernel from sources rather than fetching it from the binary cache.
Some other software is also affected, but kernel is the worst one because it takes ages to compile on the weak aarch64 board.
According to what I have read about NixOS channels, the “stable” channels like 19.09 should have almost all their packages pre-built.
I looked at [Hydra logs](https://hydra.nixos.org/jobset/nixos/release-19.09-aarch64), and it shows that many packages on release-19.09-aarch64 jobset are failing due to timeout (4 hours). Linux kernel package is among these failing ones.
Shouldn't the channel update be postponed if critical packages linke Linux kernel failed to build? I understand that currently the "recomended" kernel is LTS one, but my board does not work properly with it, and even the [arm/arch wiki](https://nixos.wiki/wiki/NixOS_on_ARM#NixOS_installation_.26_configuration) suggests using the latest kernel.

Probably related: #72159, #72717

**To Reproduce**
1. On aarch64 setup using `linuxPackages_latest` kernel, update to latest version of 19.09 channel
2. Start system rebuild
3. Linux kernel will start building from source

**Expected behavior**
Linux kernel should be cached.

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.3.7, NixOS, 19.09.891.80b42e630b2 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1019.c5aabb0d603, unstable-20.03pre197685.f35f0880f2c"`
 - channels(mars): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
Indeed a duplicate so closing.

**Comment by MarSoft** [comment]
@FRidh, which issue is this one duplicate of? I could not find. 
The #72717 I mentioned has similar problem with different package, but it was "fixed" by workaround (disabling done tests). That "fix" does nothing for the problem with kernel.
