### ISSUE TITLE
wine: clean up versions

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#72914]
**Describe the bug**
repology reports some issues with the package name and version.

```
2019-11-04 12:10:39   wine-staging: ERROR: name "wine-4.17-staging" does not end with version "4.17"
2019-11-04 12:10:39   winePackages.staging: ERROR: name "wine-4.17-staging" does not end with version "4.17"
2019-11-04 12:10:39   wineWowPackages.staging: ERROR: name "wine-wow-4.17-staging" does not end with version "4.17"
```

It should end with the version, not "staging".

So we could just call the package `wine-staging-4.17`. But we should be consistent here!

All the wine versions and attribute names are messed up.

https://nixos.org/nixos/packages.html?channel=nixos-19.09&query=wine

wine-4.0.2 | wine
wine-4.0.2 | winePackages.stable
wine-4.14 | winePackages.unstable
wine-4.14-staging | wine-staging
wine-4.14-staging | winePackages.staging

Why is "staging" in the package name but "unstable" not? Is there even a difference?

So i would remove "staging" from "wine-4.14-staging".

**Metadata**
master

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: wine
# a list of nixos modules affected by the problem
module:
```

**Comment by pstn** [comment]
Adding to this: I locally built `wine-staging-4.18` and `wine-staging-4.19` without issues with the current packages but I'm not sure what's actually required for a PR here. Seems odd that it was so easy and nobody else already PRed it.

**Comment by veprbl** [comment]
@pstn Mind doing the PR then? :)

**Comment by davidak** [comment]
>I'm not sure what's actually required for a PR here.

I also don't know what the wine maintainers want.

My motivation is to get the repology error fixed.

So i would remove "staging" from "wine-4.14-staging".

>Seems odd that it was so easy and nobody else already PRed it.

There is a lot that can be improved in nixpkgs that is quiet easy! For example i'm currently fixing package versions that produce errors in repology. https://github.com/NixOS/nixpkgs/pull/72922

There are 586 known problems left to fix: https://repology.org/repository/nix_unstable/problems

There are 4997 outdated packages in nixpkgs unstable: https://repology.org/projects/?inrepo=nix_unstable&outdated=1

Most of them probably quiet easy to update, but someone has to invest the time. Maybe there is already a PR that is not merged yet. A review can help to speed it up!

But we are already the best distro when it comes to up-to-date packages! https://repology.org/repositories/graphs

And we might supersede AUR in the future with total number of packages. But at the same time, many common packages are not in nixpkgs...

**Comment by davidak** [comment]
issue still exists

cc maintainers @avnik @7c6f434c @bendlas

**Comment by 7c6f434c** [comment]
There is a difference between unstable and staging. Staging is the staging patches on top of unstable.

**Comment by davidak** [comment]
That makes sense. Can we add it to Long description?

Repology seem to recognise the version now:

![Screenshot from 2020-06-11 19-36-42](https://user-images.githubusercontent.com/91113/84420993-361a2900-ac1b-11ea-945a-256197fb6a2a.png)

**Comment by 7c6f434c** [comment]
>That makes sense. Can we add it to Long description?

Added to description, but if you think longDescription is better, or think the wording is not clear — please comment or PR.
