### ISSUE TITLE
Grub from release-19.09 fails to load on Dell XPS 7390 Developer Edition; grub from master works

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#72936]
**Describe the bug**

(Note: I've assigned this to myself since I'm still trying to find a solution. I have a work-around using Ubuntu's `grub-mkimage`.)

Booting from a NixOS live CD fails on my Dell XPS 7390 Developer Edition, but works on my old Thinkpad.

I have found a work-around: in the Ubuntu installation that comes with the laptop, I ran the following command to generate a new grub image:

    sudo grub-mkimage -o fromub.efi -p /EFI/boot -O x86_64-efi fat iso9660 part_gpt part_msdos normal boot linux configfile loopback chain halt efifwsetup efi_gop ls search search_label search_fs_uuid search_fs_file gfxmenu gfxterm gfxterm_background gfxterm_menu test all_video loadenv exfat ext2 ntfs btrfs hfsplus udf videoinfo png echo serial

I told the bios to boot from "fromub.efi", and I saw the grub menu and was able to successfully boot into the NixOS installer.

PopOS seems to have the same issue: https://github.com/pop-os/pop/issues/730

**To Reproduce**
1. I downloaded the "minimal installation CD" from [here](https://releases.nixos.org/nixos/19.09/nixos-19.09.1019.c5aabb0d603/nixos-minimal-19.09.1019.c5aabb0d603-x86_64-linux.iso) (linked from the [Getting NixOS 19.09 page](https://nixos.org/nixos/download.html)), and flashed it to a USB stick using dd.

2. I inserted the USB into my laptop (using a USB A-to-C adapter), turned it on, pressed F12 to tell the BIOS I wanted to choose a different boot device.

3. Two different boot options appear for the USB stick (probably because it has two partitions). I click one of them (I tried both with the same result).

4. I see an empty screen with a "dell" logo in the middle and a text cursor in the upper-left corner.

**Expected behavior**
The Grub menu appears, showing NixOS boot options.

**My next steps**
1. Running `grub-mkimage --version` on the Ubuntu 18.04 installation I used to work around the problem shows 2.02-2ubuntu8.13, and I think NixOS 19.09 has 2.02.  I think I'll try the latest Grub version on NixOS, and if that doesn't work, look into whether there's anything special about Ubuntu's version of Grub.

2. It might be unrelated to the grub version. I might try my workaround using the grub-mkimage I already have on nixos 19.09, and see whether that works as well as the Ubuntu workaround.

**Comment by falsifian** [comment]
Update: it looks like Grub 2.04 works but 2.02 doesn't.

Details:

* I tried my workaround with grub installed using `nix-build -A grub2_efi` using two different nixpkgs revisions. With the 19.09 channel, git revision c5aabb0d603, it hangs, and `grub-mkimage --version` shows 2.02. With master, git revision 2e52f98dd, it works, and the version is 2.04.

**Comment by falsifian** [comment]
Note: it looks like 19.09 was going to have grub 2.04, but it was reverted back to 2.02 due to https://github.com/NixOS/nixpkgs/issues/61718

**Comment by falsifian** [comment]
Just asked help-grub@gnu.org for advice on patching Grub 2.02 to fix the issue. If there's a simple fix, it would probably make sense to apply it to 19.09.

**Comment by falsifian** [comment]
No response on the help-grub mailing list. I don't think I will have time to figure out on my own how to patch grub 2.02 to work, so I will unassign myself.

I'm not sure whether to close this issue. I'm tempted to close it because I don't see who will have time to work on it, but on the other hand, judging by the fact that three users have commented on pop-os/pop#730, it might affect others.

**Comment by mradke** [comment]
I can confirm this issue. My workaround was to format the drive with archlinux (since mkfs.ext4 was broken on the 20.03-pre iso) and to install 19.09 by switching the channel while installing from the 20.03-pre.iso...

Although I have not had success to start the x server afterwards. 😦

**Comment by falsifian** [comment]
@mradke the X server didn't work for me until I switched to the latest kernel (`boot.kernelPackages = pkgs.linuxPackages_5_3`). This is on master; I haven't even tried with a release branch.

**Comment by mradke** [comment]
Ah nice. Thanks for letting me know. Then not all hope it lost it seems 😄
