### ISSUE TITLE
Remove `nightly` `iojs` builds.

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#7293]
The `iojs` package (`nixpkgs.iojs`) has an option to build nightly or not.

Given that the package is only updated every once in a while, it's not truly building tonight's nightly but a random nightly that isn't going to be useful to anybody.

It also complicates the structure of the derivative for what I perceive to be no gain.

As such, I'd like to clean up the derivation and remove the nightly stuff. Any objections?

**Comment by Havvy** [comment]
JagaJaga suggested that I add a note about this change to:

https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-unstable.xml

But this package was added after the 14.12 release, so it was never in any official NixOS release.

**Comment by MP2E** [comment]
This issue is now resolved, no idea why the nightly and stable packages were combined.

If someone wants a nightly derivation of iojs, please make a seperate .nix file for it.
