### ISSUE TITLE
nixos/dysnomia is out of date/broken

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#72962]
`services.mysql.rootPassword` was removed from NixOS, but `dysnomia` still references it.
```
    // lib.optionalAttrs (config.services.mysql.enable) { mysql-database = {
        mysqlPort = config.services.mysql.port;
      } // lib.optionalAttrs cfg.enableAuthentication {
        mysqlUsername = "root";
        mysqlPassword = builtins.readFile (config.services.mysql.rootPassword);
      };
    }
```

@svanderburg are you maintaining `dysnomia` in NixOS? I have some changes I would like to push to the `services.httpd` module which will require at least some minimal changes to your module. I'm planning on changing `services.httpd.virtualHosts` to an attribute set instead of list, like `nginx` does, as well as removing the ability to define a host outside of the set of virtual hosts.

Since this module appears to be broken in the `19.09` release I wanted to make sure you were still interested in maintaining it in nixpkgs before I proceed.

**Comment by aanderse** [comment]
Still relevant.

**Comment by aanderse** [comment]
Still relevant @svanderburg.

**Comment by ajs124** [comment]
Assuming this is still broken after over a year, we might want to consider dropping the module, if it's not being maintained.
