### ISSUE TITLE
zola 0.9.0 doesn't build on darwin

### ISSUE THREAD

**Issue by killercup** [NixOS/nixpkgs#72972]
**Describe the bug**
Tried upgrading to zola 0.9.0, but it errored out.

**To Reproduce**
```
$ nix-env -iA nixpkgs.zola
[...]
copying path '/nix/store/cprhinjsxmklg0hyx3d5x67wj2y4flyx-zola-0.9.0-vendor' from 'https://cache.nixos.org'...
creating directory '/nix/store/cprhinjsxmklg0hyx3d5x67wj2y4flyx-zola-0.9.0-vendor/sass-sys/libsass/test/e2e/unicode-pwd/Sáss-UŢF8': File exists
copying path '/nix/store/ca22h96ag2fq0laa8v91vnv0pyy87sfc-cctools-binutils-darwin' from 'https://cache.nixos.org'...
cannot build derivation '/nix/store/wrf12lgzp853qh9i4mhl5kk6crcq42q0-zola-0.9.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wrf12lgzp853qh9i4mhl5kk6crcq42q0-zola-0.9.0.drv' failed
```

**Expected behavior**
Zola 0.9 can be installed.

**Additional context**
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G4015
$ uname -a
Darwin ph-mbp.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- zola
# a list of nixos modules affected by the problem
module:
```

cc @dywedir (maintainer of the package)

**Comment by dywedir** [comment]
@killercup thanks for the report!
It seems like we need to do something like this: https://github.com/NixOS/nixpkgs/blob/06d3491d2a3acbff4af34c2c5b14e7f8a2f5a0ae/pkgs/development/libraries/libsass/default.nix#L12-L16
I'll have a look later today.

**Comment by dywedir** [comment]
The only idea I've come up with, at this point, is to fork https://github.com/compass-rs/sass-rs and remove the "sass-sys/libsass" directory.

**Comment by killercup** [comment]
Oh, that goes in the right direction, @dywedir! But it might be easier: cargo also has a mechanism of excluding files!

@Keats, I'm pinging you because zola fails to build on macOS with vendored dependecies. This is because sass-sys includes the original `libsass/test/e2e/unicode-pwd` files which happen to conflict after the unicode normalization that macOS applies.

Could I trouble you to release a new patch release of sass-sys that [excludes](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional) this `libsass/test` directory in the Cargo.toml so it won't be part of the artifact on crates.io? If we then bump this dependency in zola (can be a local patch here first), it should build again.

**Comment by killercup** [comment]
Submitted a quick fix that patches the lock file to bump sass-sys version: #73985

This fixes the build on macOS for me.
