### ISSUE TITLE
pythonPackages.thumbor broken on macos

### ISSUE THREAD

**Issue by emptyflask** [NixOS/nixpkgs#73001]
**Describe the bug**
Thumbor will not install on MacOS due to:
```
nix-env -iA nixpkgs.pythonPackages.thumbor
installing 'python2.7-thumbor-6.7.0'
error: Package ‘opencv-2.4.13’ in /nix/store/zsdz67zd8db6cljgilawifrwaxsd0ny6-nixpkgs-20.03pre197736.91d5b3f07d2/nixpkgs/pkgs/development/libraries/opencv/default.nix:88 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

**To Reproduce**
1. `nix-env -iA nixpkgs.pythonPackages.thumbor`

**Additional context**
`opencv3` is specified as a dependency, but another dependency, `remotecv`, requires `opencv` (v2) which is the version marked as not supported. I attempted to change its dependency to `opencv3` as well, but the installation process hung after running a lengthy Redis test suite and other `pythonImportsCheckPhase` operations.

Anyway, I'm hoping someone with more Python experience can look into this further.

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(jon): `"nixpkgs-20.03pre197736.91d5b3f07d2"`
 - nixpkgs: `/Users/jon/.nix-defexpr/channels/nixpkgs`

**Comment by Artturin** [comment]
There's no thumbor in nixpkgs anymore
