### ISSUE TITLE
Aarch hydra packages are backed up

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#73022]
There's several thousand aarch64 hydra jobs that aren't being processed :(

see:
https://hydra.nixos.org/jobset/nixpkgs/trunk

cc @grahamc @FRidh

**Comment by grahamc** [comment]
https://status.nixos.org/grafana/d/MJw9PcAiz/hydra-jobs?orgId=1&from=1573030762914&to=1573203562915&refresh=30s&var-machine=All&panelId=15&fullscreen

sent from the sky

**Comment by grahamc** [comment]
There are actually more x86-64 jobs, and they’re all building okay as far as I can see. https://status.nixos.org/grafana/d/MJw9PcAiz/hydra-jobs?orgId=1&from=1573192987991&to=1573203787992&refresh=30s&var-machine=All&panelId=2&fullscreen

**Comment by jonringer** [comment]
oh, i guess it's just chugging along then, sorry for bothering you :)

**Comment by jonringer** [comment]
that's a beautiful ui
