### ISSUE TITLE
tor-browser: Installation fails because all mirrors are down for 8.5.5

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#73021]
NixOS ver: 19.09
The tor-browser package is broken. The installation fails, since the tor project took down the mirrors for version 8.5.5.

**Comment by veprbl** [comment]
Perhaps need to backport #71839
cc @offline @matejc @doublec @thoughtpolice @joachifm

**Comment by joachifm** [comment]
I've picked https://github.com/NixOS/nixpkgs/pull/71839 to release.
