### ISSUE TITLE
Firefox failing to build due to rustc update

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#73023]
Firefox is faililng to build due to log limit being exceeded.

see: https://hydra.nixos.org/build/105989750/nixlog/1

cc @worldofpeace @taku0

**Comment by jonringer** [comment]
very likely, also broke rustbindgen

**Comment by taku0** [comment]
Made PR #73039 for rustc.

**Comment by oscarvarto** [comment]
Firefox keeps failing to build even after #73039

**Comment by taku0** [comment]
`firefox` package is not updated yet. Made PR #73050.

**Comment by worldofpeace** [comment]
@edolstra Shouldn't we be updating rustc on staging on not master?

**Comment by taku0** [comment]
https://github.com/NixOS/nixpkgs/pull/73050 is merged. @jonringer could you check build and close if succeeds?

**Comment by jonringer** [comment]
launches fine, thank you all ;)
