### ISSUE TITLE
Make shell-conduit depend on PATH

### ISSUE THREAD

**Issue by berdario** [NixOS/nixpkgs#7305]
One nice feature of `shell-conduit` is that it builds the list of available programs at build time, this could stop the build and avoid a runtime error in case the user doesn't have that external program available.

Nix obviously can take care of this with `propagatedBuildInputs` and the like, but it'd be nice to add support for this feature, so that an haskell program could have this guarantee even when run on a non-nix system. Unfortunately at the moment developing such software in Nix is not a good experience, because if you realize that you need a new program to shell-out and modify your `shell.nix`, `shell-conduit` is not automatically rebuild to expose this change.

I'm not aware of a way to easily rebuild/invalidate a dependency like `shell-conduit`. I guess that the proper approach is to make it depend on `PATH` (actually, its contents)... so that if a new (propagated?) build dependency is added to the `PATH` of a `nix-shell`, the rebuild of `shell-conduit` will get retriggered.

`shell-conduit`'s code that looks at the `PATH` at build time is [here](https://github.com/chrisdone/shell-conduit/blob/20eab534596b970ba9d7cc6c2e15758fc533d38c/src/Data/Conduit/Shell/TH.hs#L65), and I guess that the `getAllBinaries` function could be, in some way, reused in the nix expression for the package

**Comment by Profpatsch** [comment]
triage: can you still reproduce this issue?
