### ISSUE TITLE
passff-host: incorrect location for Firefox native messaging host manifest

### ISSUE THREAD

**Issue by starcraft66** [NixOS/nixpkgs#73090]
**Describe the bug**
The native messaging host manifest is installed into `/lib/mozilla/native-messaging-hosts/` but this path is nowhere to be found in mozilla's documentation which states that native messaging host manifests should be globally installed in `/usr/{lib,lib64,share}/mozilla/native-messaging-hosts/`.

**To Reproduce**
1. Install and configure pass
2. Install passff-host and the passff browser plugin in firefox
3. Open the passff extension, an error will appear saying it can't communicate with the native messaging host.

**Expected behavior**
I expect the passff extension to communicate with passff-host and show a list of available passwords.

**Screenshots**

**Additional context**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 19.09.1098.821c7ed030b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by starcraft66** [comment]
It appears that this path may indeed be correct but firefox isn't loading the messaging host if this package is installed system-wide. I was only able to get it to work by insatlling it via `nix-env`.

**Comment by Avaq** [comment]
I'm also running into this issue. Installing with `nix-env` did not appear to change anything. I don't understand how the wiring between firefox wrapper and passff-host works, and how Firefox is supposed to discover the manifest file by finding one of these paths:

```
/nix/store/[...]-passff-host-1.2.1/share/passff-host/passff.json
/nix/store/[...]-passff-host-1.2.1/lib/mozilla/native-messaging-hosts/passff.json
/nix/store/[...]-user-environment/lib/mozilla/native-messaging-hosts/passff.json
```

**Comment by Avaq** [comment]
I just found the following firefox package config:

https://github.com/NixOS/nixpkgs/blob/ba4e5a3f640a4a88a7d81d7a7ea84cfbdd31adf7/pkgs/applications/networking/browsers/firefox/wrapper.nix#L67-L75

I'm going to continue exploring down this avenue.

**Comment by Avaq** [comment]
I got this working like this:

```nix
with pkgs; [
  (firefox.override { extraNativeMessagingHosts = [ passff-host ]; })
]
```

No need to install `passff-host` directly. Perhaps this issue can be closed?

**Comment by starcraft66** [comment]
@Avaq I can confirm that your solution works.
