### ISSUE TITLE
Mathematica 12.0.0 `ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by nezumi1503** [NixOS/nixpkgs#73125]
**Describe the bug**
When I run mathematica 12.0.0, following error occurs:
> /nix/store/7l7mjyck0390zymiqmn32c8m7lc28v2n-mathematica-12.0.0/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica: /nix/store/7l7mjyck0390zymiqmn32c8m7lc28v2n-mathematica-12.0.0/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/libz.so.1: version `ZLIB_1.2.9' not found (required by /nix/store/bcw1cimbj66vlck3lv3hh770cqhxp1zb-libpng-apng-1.6.37/lib/libpng16.so.16)

**To Reproduce**
1. `nix-env -iA nixos.mathematica` as a normal user.
2. Run mathematica in the shell.
3. The error occurs.

**Expected behavior**
Should run without errors.
**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.3.9, NixOS, 19.09.1155.bae4d7daa01 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1155.bae4d7daa01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
cc @herberteuler

**Comment by herberteuler** [comment]
Sorry about the delay, I was super busy. I have reproduced the issue and will create a PR later.
