### ISSUE TITLE
qscintilla and dependencies are marked broken on stable

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#73148]
**Describe the bug**
* As of commit 653c9e2c "qscintilla: 2.9.4 -> 2.11.2" pkgs.qscintilla is marked as broken on stable.
* This commit got apparently merged into nixos-19.09 via #72249.
* This breaks all dependencies like the fairly widely used octave.

**To Reproduce**
1. checkout nixos-19.09
2. `nix build -f . qscintilla`
3. `error: Package ‘qscintilla-qt4-2.11.2’ in <..>/pkgs/development/libraries/qscintilla/default.nix:56 is marked as broken, refusing to evaluate.`

**Additional context**
See here, that hydra stopped building 'qscintilla' when the PR got merged: https://hydra.nixos.org/job/nixos/release-19.09/nixpkgs.qscintilla.x86_64-linux

It seems like other packages appeared at the same time. Maybe octave can be fixed by choosing a different dependency? 

Ironically the pr specifically talks about the dangers of backporting …

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qscintilla, octave
```
/cc @peterhoeg, @lsix, @jonringer, @FRidh

**Comment by lsix** [comment]
That's pretty odd, I was sure I did fix that.

It has been fixed on master with eb1cd0d27d42f5a3d969a5a87330d1322812b09c, which I was pretty sure I backported to release-19.09. But apparently not…

Let me see if this backport goes smoothly, and prepare a PR for it.

Sorry for thatk

**Comment by maralorn** [comment]
@lsix Thank you very much!

It seems to be a cherry-pick/rebase issue. The line where you add the patch is backported but the line where you remove the broken attribute isn‘t.

**Comment by maralorn** [comment]
Thanks @lsix it‘s fixed for me.
