### ISSUE TITLE
Steam adds support for Linux namespaces

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#73191]
Valve released Linux namespace (container) support for the steam-runtime as beta.

Official announcement: https://steamcommunity.com/app/221410/discussions/0/1638675549018366706/

Phoronix article: https://www.phoronix.com/scan.php?page=news_item&px=Steam-Linux-Exp-Containers

This issue if for discussion and maybe implementing this feature in our package.

I start with a question: Will this help us to have a cleaner package?

cc @abbradar @jagajaga @tadfisher @Synthetica9

**Comment by wucke13** [comment]
When running steam beta (which includes support for the namespacing you mentioned) on NixOS, I receive the following errors:

```
Running Steam on nixos 19.09.1125.d628521d0b7 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Error: You are missing the following 32-bit libraries, and Steam may not run:
libva.so.2
libva.so.2
libva-x11.so.2
/home/wucke13/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1573176642)
Installing breakpad exception handler for appid(steam)/version(1573176642)
Installing breakpad exception handler for appid(steam)/version(1573176642)
Failed to load steamui.so - dlerror(): libva.so.2: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1573176642)
Installing breakpad exception handler for appid(steam)/version(1573176642)
[2019-11-11 14:24:14] Startup - updater built Nov  7 2019 23:57:30
[2019-11-11 14:24:14] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-11-11 14:24:14] Checking for update on startup
[2019-11-11 14:24:14] Checking for available updates...
[2019-11-11 14:24:14] Downloading manifest: client-download.steampowered.com/client/steam_client_publicbeta_ubuntu12
[2019-11-11 14:24:14] Download skipped by HTTP 304 Not Modified
[2019-11-11 14:24:14] Nothing to do
[2019-11-11 14:24:14] Verifying installation...
[2019-11-11 14:24:14] Performing checksum verification of executable files
[2019-11-11 14:24:15] Verification complete
[2019-11-11 14:24:17] Shutdown
```
So we probably should add `libva.out`  to the steam derivation.

**Comment by davidak** [comment]
@wucke13 that's probably fixed with https://github.com/NixOS/nixpkgs/pull/73108.

I think you must enable the namespacing manually for each game.

That might cause problems since we already use namespacing...

But i have no idea about such low level details. Waiting for some feedback from the maintainers.

**Comment by matthew-piziak** [comment]
If anyone is bouncing off of a `libva.so not found` error, `pkgs.steam.overrideAttrs (orig: { extraPkgs = with pkgs; [ libva ]; });` might work around it for you, as it did for me.

**Comment by jonringer** [comment]
this has been fixed, steam removed their "crash if libva.so (32bit) isn't available."

**Comment by jonringer** [comment]
oh, original issue is about namespaces

**Comment by davidak** [comment]
this is still relevant for better compatibility i think

**Comment by Atemu** [comment]
This has been working for a few years now.

**Comment by Atemu** [comment]
For reference https://github.com/NixOS/nixpkgs/pull/114024
