### ISSUE TITLE
lutris: TLS not working because 'gnutls' cannot be loaded

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#73205]
**Describe the bug**
When using blizzard's Battle.net client through lutris/lutris-free, the login doesn't work. The debug log points out that gnutls cannot be loaded.

**To Reproduce**
1. Install lutris or lutris-free from nixpkgs 19.09 and run it
2. Toggle the search bar by clicking the `Search Games` button in the title bar
3. Search for 'battle.net' and install it. The installation will fail (I think this is expected by the way the installer works)
4. Exit the search menu by clicking again on `Search Games` in the title bar
5. To finish the previously aborted installation click on the Battle.net logo and select `Run EXE inside wine prefix` to manually run `GAMEDIR/drive_c/ProgramData/Battle.net/Setup/battle.net/Battle.net Setup.exe`.
6. After the installation has finished, the battle.net login menu will appear automatically (otherwise double click on the app inside lutris). One can already see that something is wrong because the menu displays some error message, stating that cookies couldn't be loaded. Trying to login will fail offering the user to continue in offline mode.

**Expected behavior**
The Battle.net login window displays correctly and logging in leads to the next screen showing the available games.

**Screenshots**
![image](https://user-images.githubusercontent.com/42246742/68572133-8e5a3400-045c-11ea-9f3b-6dbbbd5f1fac.png)

**Logs**
To get the logs the debug logging for the game must be enabled by right clicking the app in lutris and setting `Configure/Runner Options/Output debugging info` to `Enabled`. This is the relevant part of the logs:
```
00a9:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
00a9:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
00a4:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
00a9:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
00a9:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
00a4:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
```

**Possible Solution**
I already checked if #72280 caused this issue because the gnutls-kdh dependency was removed from 'targetPackages' of buildFHSUserEnv, but this is not the cause. Even after adding gnutls to targetPackages, the problem still occurs.
I could solve it by adding gnutls to 'multiPkgs' instead of 'targetPackages'. I will make a PR with the fix.
Still wine will complain about missing 'Kerberos SSP support', but this doesn't seem to be required by the game and it wouldn't be fixable anyways without reviving the recently abandoned 'gnutls-kdh' package.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 19.09.1098.821c7ed030b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1098.821c7ed030b"`
 - channels(grmpf): `"nixos-19.09.1019.c5aabb0d603"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - lutris
  - lutris-free
# a list of nixos modules affected by the problem
module:
```

**Comment by frio** [comment]
This will also fix https://github.com/NixOS/nixpkgs/issues/65416.  Thanks for this!

For context, I tried the suggested fix in that ticket (add glib-networking to the package) without joy, and was attempting to add gnutls directly to the package but received errors about gnutls/Python 3 being incompatible.  I didn't think to change the chrootenv, doh.
