### ISSUE TITLE
Confusing error during upgrade from 18.09 to 19.09

### ISSUE THREAD

**Issue by betawaffle** [NixOS/nixpkgs#73221]
**Describe the bug**
I decided to upgrade my router from 18.09 to 19.09, and I got what seemed like an unclear error message.

```
trace: Systemd Link has extra fields [Name].
error: The option value `systemd.network.links.10-att.linkConfig' in `/etc/nixos/att.nix' is not of type `attribute set of systemd options'.
```

I eventually worked around it, though I don't know if my workaround produced the desired networkd behavior or not.

**To Reproduce**
Try to apply a configuration with something like the following:

```
 systemd.network.links."10-att".linkConfig = {
   Name = "att";
   Description = "AT&T Router (for 802.1x auth)";
};
```

My workaround was to comment out `Name` and use `extraConfig` to set the name. The systemd-networkd documentation _seems_ to indicate it is still a valid option for the `[Link]` section.

**Expected behavior**
I expected the error message to more obviously indicate what I was doing wrong. I suspect the `trace:` message was more useful to highlight than the part after `error:`.

**Screenshots**
~If applicable, add screenshots to help explain your problem.~

**Additional context**
I may be the only person trying to use systemd-networkd in this way on a router with NixOS.

**Metadata**
This is from **after** the workaround, but I was on 18.09 before.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 19.09.1172.2d896998dc9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1172.2d896998dc9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Not sure what I'm supposed to do with the `Maintainer information` section above.

cc @flokli, who asked to be highlighted about this.

**Comment by flokli** [comment]
This should have been fixed since 943508a7fa95ce6aa8f14a9a717881e436b3816e. Can you check if cherry-picking that commit works for you?

We might want to backport that.

cc @fpletz @andir

**Comment by betawaffle** [comment]
Neat, how do I switch to a non-release nixpkgs such that I can cherry-pick and test that?

**Comment by flokli** [comment]
You simply pass the path to the git clone while doing the `rebuild-switch`

```
sudo nixos-rebuild switch -I nixpkgs=/path/to/nixpkgs/checkout
```

**Comment by betawaffle** [comment]
Looks like I didn't even need to cherry-pick, the relevant change is already in the release, and seems to have worked.

**Comment by flokli** [comment]
This was backported to 19.09 in 76049ce4ef9cec38e4c661f93ae68026f1738a54 Nov 5 - which explains why it's part of the release by now.
