### ISSUE TITLE
Packaging requests: eddie-ui

### ISSUE THREAD

**Issue by tgys** [NixOS/nixpkgs#73233]
**Project description**
eddie-ui is the official client for AirVPN
It's written in C# with .Net/Mono framework and supports multiple architectures: x64, x86, armv7i
for reference, there's an arch pkgbuild here (there might be an easier way in nix): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=eddie-ui 

**Metadata**

* homepage URL: https://airvpn.org/
* source URL: https://github.com/AirVPN/Eddie
* license: gpl3+
* platforms: multiplatform

**Comment by returnofblank** [comment]
still important to me

**Comment by h4rldev** [comment]
+1
