### ISSUE TITLE
Independent applications actually conflict

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#7325]
What should be independent applications actually conflict:
```
Wide character in die at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
collision between ‘/nix/store/7vkigwpw7qkvwpki8yqd4p7sf1ak0gxw-virt-manager-1.0.1/share/glib-2.0/schemas/gschemas.compiled’ and ‘/nix/store/1l57xj9mi30a5dd9zbzdqsrqr3l7ckar-meld-3.12.3/share/glib-2.0/schemas/gschemas.compiled’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
```
Then doing something which appears to be conforming to the grammar of PKGNAME, does not work:
```
nix-env --set-flag priority 1 meld-3.12.3                         
error: selector ‘meld-3.12.3’ matches no derivations
```
`nix-env --upgrade` should simply outputs the two pieces of valid code to resolve this situation. 
So, it should not refer to a rather badly defined non-terminal of some badly specified grammar, in this case the symbol PKGNAME, but it should just have done the substitution already in the error message. If *then* it doesn't work, there is less discussion about who is wrong.

I also think it's rather bad to refer to the symbol PKGNAME in the output, but then when you input that, that the program returns that the thing one has input is suddenly a "selector". While I understand that from an implementation point of view it is indeed a selector, it's rather silly to let the user know about that. It's just leaking implementation details. Similarly, for referring to the word "derivation". A derivation is a concept which only exists *within* the implementation of the tool. 

In any case, the program could also output something like. "The package FOO does not exist. If you want to list all the packages which do exist according to this particular tool, run command BAR". The tool now behaves as some autistic child; not the way to go.

**Comment by vcunat** [comment]
/cc @lethalman. This concerns the gschemas handling: the hook in glib tries to make packages install the gschemas in a different location to avoid this, in particular, it sets
```bash
installFlagsArray+=("gsettingsschemadir=$out/share/gsettings-schemas/$name/glib-2.0/schemas/")
```

For some reason it seems to fail for meld and virt-manager.

**Comment by vcunat** [comment]
I'm considering automatically moving gschemas if they happen to be on the usual path. That should protect us against most causes of this issue. Also, this might make it work better with multiple-output stuff later.

```diff
diff --git a/pkgs/development/libraries/glib/setup-hook.sh b/pkgs/development/libraries/glib/setup-hook.sh
index f173744..120b494 100644
--- a/pkgs/development/libraries/glib/setup-hook.sh
+++ b/pkgs/development/libraries/glib/setup-hook.sh
@@ -11,7 +11,14 @@ make_glib_find_gsettings_schemas() {
 envHooks+=(make_glib_find_gsettings_schemas)
 
 glibPreFixupPhase() {
-    addToSearchPath GSETTINGS_SCHEMAS_PATH "$out/share/gsettings-schemas/$name"
+    # Move gschemas in case the install flag didn't help
+    if [ -d "$prefix/share/glib-2.0/schemas" ]; then
+        mkdir -p "$prefix/share/gsettings-schemas/$name/glib-2.0"
+        mv "$prefix/share/glib-2.0/schemas" "$prefix/share/gsettings-schemas/$name/glib-2.0/"
+    fi
+
+    addToSearchPath GSETTINGS_SCHEMAS_PATH "$prefix/share/gsettings-schemas/$name"
 }
 
-preFixupPhases="$preFixupPhases glibPreFixupPhase"
+fixupOutputHooks+=(glibPreFixupPhase)
+
```

**Comment by vcunat** [comment]
Now the ``$out/share/glib-2.0/schemas/gschemas.compiled`` files are moved away automatically, so this won't happen anymore. (Pushed to staging.)
