### ISSUE TITLE
modifying a service in systemd.user.services does not cause daemon-reload

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#7326]
I went through this process
- modified existing systemd user service description in `/etc/nixos/configuration.nix`
- ran `nixos-rebuild switch`
- as user, ran `systemctl --user start $MYSERVICE`
  it failed, due to a misconfiguration in the old description
- ran `systemctl --user daemon-reload`
- again ran `systemctl --user start $MYSERVICE`
  this time it worked

daemon-reload should probably run automatically when a service is changed. there may be an analogous problem for systemwide services as well

**Comment by joachifm** [comment]
Another systemd user service UX problem, see also https://github.com/NixOS/nixpkgs/issues/7329

**Comment by ctheune** [comment]
I actually just wrote an activation script that does the following for all users that have lingering enabled:

```            ${pkgs.systemd}/bin/systemd-run --setenv=XDG_RUNTIME_DIR="/run/user/${toString user.uid}" --uid ${user.name}  ${pkgs.systemd}/bin/systemctl --user daemon-reload
```

**Comment by edwtjo** [comment]
@ctheune submit the lingering/reload thing as a pull request?

**Comment by ctheune** [comment]
I'm going to try this out in our environment first and see how it behaves over time. If that works reasonably well I'll be happy, to. Otherwise it's more of a "hack" at the moment. Also, systemd could do a lot better on managing this out of the box. I'm thinking of contacting them, too.

**Comment by Profpatsch** [comment]
`restartIfChanged` should be made working as well for user services.

**Comment by jb55** [comment]
weird daemon-reload isn't even working for me now.

**Comment by Ma27** [comment]
this should be fixed now. Since #44990 `switch-to-configuration.pl` performs a `daemon-reload` for user services.

**Comment by Ma27** [comment]
ack, closing for now :+1:

**Comment by Profpatsch** [comment]
If there’s a follow up issue, it should be created before the old issue is closed. I added one.

**Comment by arianvp** [comment]
Thanks! Good catch
