### ISSUE TITLE
Symbolic links should be checked for validity

### ISSUE THREAD

**Issue by bb010g** [NixOS/nixpkgs#7327]
When fixing `firefoxWrapper`'s (lack of an) icon, I found that the problem was a broken symlink generated by the package ([line](https://github.com/NixOS/nixpkgs/blob/6a6470b79386c6c8710380fbbe7a665b5f1beee3/pkgs/applications/networking/browsers/firefox/wrapper.nix#L62), should be `${browserName}${nameSuffix}` in the source). @ttuegel suggested on IRC that a check be put in for such problems, "something like `if [[ ! -f $(readlink -f $symlink) ]]; then echo "Icon symlink missing!"; exit 1; fi` in the postInstall phase". I figured such a check would be useful for all packages, as it's rare that we want to make a broken symlink. I don't know enough to know if it would be plausible to do such a check on all the symlinks generated by packages, or just the ones the Nixexpr makes on its own, but this is mainly to get the idea flowing around.

**Comment by vcunat** [comment]
Yes, I think we can do that. We pass the output a few times already, and another pass probably won't slow us down too much.

**Comment by nbp** [comment]
Maybe we should use `cp -s` instead of `ln` to create symlinks.

**Comment by ttuegel** [comment]
> Maybe we should use cp -s instead of ln to create symlinks.
That would be a good start, but we don't have control over what `make`, etc. are doing.

**Comment by Profpatsch** [comment]
(triage) Anyone interested? Otherwise I suggest we close.
