### ISSUE TITLE
Netalyzr closed down in March 2019

### ISSUE THREAD

**Issue by ifatuus** [NixOS/nixpkgs#73308]
## Issue description
Under packages networking->netalyzr

This service is no longer available.

## Technical details

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

**Comment by veprbl** [comment]
cc @peterhoeg

**Comment by peterhoeg** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/77620.
