### ISSUE TITLE
Emojis too big in gnome-terminal

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#73303]
**Describe the bug**
When I have emojis on the terminal inside gnome-terminal, these are shown by far too big. Their height is about 6 to 7 lines of characters.

**To Reproduce**
1. Configure NixOS like shown below
2. Open gnome-terminal
3. Press several times the return key
4. Copy the character “💩” into the console
5. Press several more times the return key

**Expected behavior**
I would expect the Emojis being shown at the size of a double width character (i.e. same height as text, double the width of typical western characters.

**Screenshots**
![Big_Emoji](https://user-images.githubusercontent.com/2042030/68701567-5c91bc00-0587-11ea-9eeb-7422561aafbc.png)

**Additional context**
The font “Noto Emoji” is installed in `/etc/nixos/configuration.nix` like that:

```
  fonts.fonts = with pkgs; [ noto-fonts noto-fonts-cjk noto-fonts-emoji liberation_ttf fira-code fira-code-symbols mplus-outline-fonts dina-font proggyfonts roboto roboto-mono dejavu_fonts carlito source-code-pro ];
  fonts.fontconfig.ultimate.enable = true;
  fonts.fontconfig.defaultFonts = {
    monospace = ["Noto Sans Mono" "Noto Sans Mono CJK TC Regular"];
    sansSerif = ["Noto Sans" "Noto Sans CJK TC Regular"];
    serif = ["Noto Serif" "Noto Sans CJK TC Regular"];
  };
```

No other font related settings I am aware of have been done.

My locale is:

```
LANG=zh_TW.UTF-8
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC="zh_TW.UTF-8"
LC_TIME="zh_TW.UTF-8"
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY="zh_TW.UTF-8"
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER="zh_TW.UTF-8"
LC_NAME="zh_TW.UTF-8"
LC_ADDRESS="zh_TW.UTF-8"
LC_TELEPHONE="zh_TW.UTF-8"
LC_MEASUREMENT="zh_TW.UTF-8"
LC_IDENTIFICATION="zh_TW.UTF-8"
LC_ALL=
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.82, NixOS, 19.09.1172.2d896998dc9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1172.2d896998dc9, unstable-20.03pre199897.471869c9185"`
 - channels(matthias): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- gnome3.gnome-terminal
- noto-fonts-emoji
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
We've actually dropped `fonts.fontconfig.ultimate.enable = true;` on master because it's seriously outdated. Can you try disabling it? When we added a default emoji font to NixOS we had to switch to using default fontconfig configuration.

**Comment by mawis** [comment]
Thanks @worldofpeace 

I removed this line and I can confirm, that this fixes the problem.

(I added this setting on 2019-09-15 to fix a problem I had with terminal fonts after switching the channel to nixos-19.09. But the problems I had in September don't exist anymore even with this setting removed. So I agree, that its better to disable fontconfig-ultimate.)
