### ISSUE TITLE
pdfpc fails to play video

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#73321]
**Describe the bug**
pdfpc can't play example video, it freezes instead.

**To Reproduce**

1.
```bash
wget https://github.com/pdfpc/pdfpc/releases/download/v4.3.0/pdfpc-video-example.zip
nix run nixpkgs.unzip -c unzip pdfpc-video-example.zip
cd pdfpc-video-example
nix-shell -p pdfpc -p gst_all_1.gst-plugins-base -p 'gst_all_1.gst-plugins-good.override {gtkSupport=true;}' -p gst_all_1.gst-plugins-bad -p gst_all_1.gst-plugins-ugly -I nixpkgs=channel:nixpkgs-unstable --run "pdfpc -wS video-example.pdf"
```
2. Go to slide 5
3. Click on the video

**Expected behavior**

**Additional context**
I'm able to play the video using the gstreamer:
```
nix-shell -p pdfpc -p gst_all_1.gst-plugins-base -p 'gst_all_1.gst-plugins-good.override {gtkSupport=true;}' -p gst_all_1.gst-plugins-bad -p gst_all_1.gst-plugins-ugly -I nixpkgs=channel:nixpkgs-unstable --run "gst-launch-1.0 filesrc location=apollo17.avi ! decodebin ! videoconvert ! gtksink"
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.90, NixOS, 18.09.1810.c840631fe20 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - pdfpc
# a list of nixos modules affected by the problem
module:
```

Possibly related to #43551
cc @pSub

**Comment by KnairdA** [comment]
I just encountered the same problem. I was able to fix it locally by changing the build inputs of the derivation to:

```nix
  buildInputs = with pkgs; [
    gtk3 libgee poppler librsvg pcre
  ] ++ (with pkgs.gst_all_1; [
    gstreamer
    gst-plugins-base
    (gst-plugins-good.override { gtkSupport = true; }) 
    gst-libav
  ]);
```

Just enabling the GTK support was not sufficient, I also had to add the `gst-libav` package.

**Comment by veprbl** [comment]
@KnairdA This is great! Would you mind submitting a PR?

**Comment by KnairdA** [comment]
Sure!
