### ISSUE TITLE
Upgrade OpenJDK to 13

### ISSUE THREAD

**Issue by Sir4ur0n** [NixOS/nixpkgs#73335]
Following #73330 which was incorrectly tagged as a bug (and users can't change labels)

**Metadata**
The current [OpenJDK version](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/default.nix) is 12 (GA) while the 13 (GA) was [released on the 2019-09-17](https://openjdk.java.net/projects/jdk/13/).

It would be great to provide the 13 version.

The default is OpenJDK13, or at least, the version 13 is available somewhere (e.g. as package `openjdk13`).

JDK 13 provides several useful changes, including an improved switch syntax, a better GC, and a [major fix on HttpClient](https://bugs.openjdk.java.net/browse/JDK-8221395).

**Comment by juaningan** [comment]
Maybe we can try to get rid of gnome2 dependencies, or set enableGnome2 false as default.
related: #73246

**Comment by cust0dian** [comment]
Was done in #70983 (also, 13 -> 14 is in #83116)

**Comment by Sir4ur0n** [comment]
Awesome, thank you!
