### ISSUE TITLE
emacs: seq imported from ELPA while already provided by Emacs

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#73346]
**Describe the bug**

Packages with potentially newer versions available inside Emacs will be overriden by ELPA
packages.

I am running an overlay with Emacs (27) built from master. On Emacs (27) master the
package `seq` has the built-in version `2.21`. The `seq` package provided by ELPA is
`2.20`.

This is currently not an issue since Emacs has not been upgraded to 27. But when it does,
this is going to cause a nasty "issue":
https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-11/msg00918.html

**To Reproduce**

1. `nix-shell --pure -p 'emacs26WithPackages (p: [p.melpaPackages.beacon])' --run 'emacs -Q --batch --eval "(princ load-path)"'`
2. Inspect the load-path and notice that it includes the seq-2.20 elpa package.

**Expected behavior**

Perhaps not `seq-2.20` not included in the load-path...

This is kind of the expected behavior, but I am raising this issue as from next version if
not a new seq package is released to ELPA, people will end up in an infinite loop.

**Additional context**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.10, NixOS, 20.03.git.7def2eb1207 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - nixpkgs: `master @ 85f3d86bea7`

**Comment by terlar** [comment]
Any ideas what to do about this case, is there any other packages where there potentially is a later version contained within Emacs and an older one available in ELPA?

**Comment by adisbladis** [comment]
`elpa-packages.nix` already contains a few things mapping builtins that used to be separate packages to `null`.
This ensures that anything depending on `seq` will get the correct dependency graph while actually using the emacs builtins.

The correct fix here is to map `seq` to `null`, maybe with a conditional checking the emacs version.

**Comment by acowley** [comment]
I've been using a locally patched nixpkgs to remove those seq dependencies, but the solution suggested here by @adisbladis is so much better that I went ahead and implemented it. Please @terlar can you also take a look at the PR to see if it resolves things for you? For me the breakage was pretty severe, so easy to notice (the `dashboard` package did not work; so I saw the problem at startup).

**Comment by terlar** [comment]
Thank you, I can verify that this is working for me as well. I am sorry to let more people experience this and not patching it earlier. I already spent some initial time finding the issue and then I made a patch within my own overlay like you. Glad to see it fixed, thanks :+1:

**Comment by terlar** [comment]
I just discovered we have the same case for `project.el`. Should that perhaps also be under a conditional? I guess if you are on an older version of Emacs you want to use the ELPA version, but if you are on the latest version you want the one bundled with Emacs as the version is more recent.
