### ISSUE TITLE
Cannot create DB with services.mysql.initialDatabases.

### ISSUE THREAD

**Issue by Kazimazi** [NixOS/nixpkgs#73352]
**Describe the bug**
Title describes it well. Mysql service installs and starts well except for I get these warnings on rebuild: 
```
> sudo nixos-rebuild switch
[sudo] password for kazimazi:
building Nix...
building the system configuration...
activating the configuration...
warning: not applying GID change of group ‘mysql’ (1000 -> 84)
warning: not applying UID change of user ‘mysql’ (498 -> 84)
setting up /etc...
reloading user units for kazimazi...
setting up tmpfiles
```
Not sure if it has anything to do with my problem, anyways it's noteworthy.

I have something like this in `configurations.nix`
```nix
services.mysql = {
      enable = true;
      package = pkgs.mariadb; # or mysql, neither worked
      initialDatabases = [ { name = "somekindofname"; } ];
};
```
Checked DBs with: `> mysql`

**Expected behavior**
DB gets created.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.10, NixOS, 19.09.1208.ef8c34c4721 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1208.ef8c34c4721, nixos-unstable-20.03pre200231.7827d3f4497"`
 - channels(kazimazi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aanderse** [comment]
https://nixos.org/nixos/options.html#services.mysql.initialdatabases
> List of database names and their initial schemas that should be used to create databases **on the first startup of MySQL.** The schema attribute is optional: If not specified, an empty database is created.

You're looking for `ensureDatabases`.
