### ISSUE TITLE
network-manager: missing directory in etc

### ISSUE THREAD

**Issue by sargon** [NixOS/nixpkgs#7338]
After installing network-manager, it refuses to establish any wired or wireless connection with following warning. 
```
NetworkManager[6604]: <warn> couldn't save default wired connection 'Ethernet DHCP': 0 / writer.c.1061: error writing to file '/etc/NetworkManager/system-connections/Ethernet DHCP': Failed to create file '/etc/NetworkManager/system-connections/Ethernet DHCP.Y0NRWX': No such file or directory
```
Creation of /etc/NetworkManager/system-connections/ fixes the problem.

**Comment by bjornfor** [comment]
Did you enable it in configuration.nix like this?

```networking.networkmanager.enable = true;```

Or did you install it with nix-env? The latter is unsupported, AFAIK.

**Comment by bjornfor** [comment]
I mean, nix-env only manages packages (/nix/store), not files outside of the store like /etc/*. That's something only NixOS does.

**Comment by sargon** [comment]
I have installed it via configuration.nix with the given line.

I removed the directory for testing and it seems it is created on next boot?!

**Comment by domenkozar** [comment]
Cool, closing then.
