### ISSUE TITLE
Handbrake: problems updating to 1.3.0

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#73399]
#### Description

As a maintainer of `handbrake` I open this issue before some user would open it or would try to solve issue.

Handbrake is a pretty messy build project. There are strange issues updating to `1.3.0`, not counting some moments they not put into documentation. `nix` build system is not designed for such messy drag-everything-home and "do not respect package managers" build project. For example, now project requires and checks for the `autoconf, autotools, cmake, meson, ninja` all at the same time, but project builds through `autoconf, autotools` and everything other is required as dependency because they blob-in, copy and patch tens of other multimedia upstreams and use those only their-own patched versions for their builds. When I show them code they freak out that we are using dependency management and upstream projects for work with their project. And `handbrake` upstream does not expect to be working in `nix` clean conditions and does not care for it, they only expect everyone to be using their Flatpack, regarding my work on Nix - phrases "this is only another package manager after 100 of other ones, there are already Flatpacks, Snaps and Docker..." phrases was tossed to me (ironically, I am silent with them that they tell this to the person that much before Flatpacks, Snaps was first heard of, was trying to improve Nix adoption by work on improving Nix installation on all platforms, but that work ironically was not accepted, so that my agenda was not met), that is what was drawn by me from several previous discussions. Some main upstream dev is pretty toxic and hard to keep any healthy dialog with. I am very careful in my words, especially with them. I would try to build a dialog, but every time I talk with them, some of their dev escalates the situation to unreasonable proportions and starts to make technical threats to pull off and ruin any support and more-over veto and block Nix on their side, it is when I came to help them, do work and have a dialog on a technical question.

So don't hold your breath.

**Syndrome**
```
  : /nix/store/ngg9lxh4xpnwdidv9sc98dg83vypm78k-binutils-2.31.1/bin/ld: /build/HandBrake-1.3.0/build//libhb/libhandbrake.a(ports.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
  : /nix/store/ngg9lxh4xpnwdidv9sc98dg83vypm78k-binutils-2.31.1/bin/ld: /nix/store/qb6k4hp7gk331x9fydw0w7qj4dv09bwz-glibc-2.27/lib/libdl.so.2: error adding symbols: DSO missing from command line
  : collect2: error: ld returned 1 exit status
  : make[3]: *** [Makefile:623: ghb] Error 1
  : make[3]: Leaving directory '/build/HandBrake-1.3.0/build/gtk/src'
  : make[2]: *** [Makefile:445: all-recursive] Error 1
  : make[2]: Leaving directory '/build/HandBrake-1.3.0/build/gtk'
  : make[1]: *** [Makefile:377: all] Error 2
  : make[1]: Leaving directory '/build/HandBrake-1.3.0/build/gtk'
  : make: *** [../gtk/module.rules:30: gtk.build] Error 2
-------------------------------------------------------------------------------
time end: Thu Nov 14 14:55:37 2019
duration: 50 seconds (50.64s)
result: FAILURE (code 2)
-------------------------------------------------------------------------------
Build is finished!
You may now cd into ./build and examine the output.
building
build flags: -j1 -l8
ninja: error: loading 'build.ninja': No such file or directory
builder for '/nix/store/n5z3ragd8as8hwy8maj20bdj2yp3ik7h-handbrake-1.3.0.drv' failed with exit code 1
error: build of '/nix/store/n5z3ragd8as8hwy8maj20bdj2yp3ik7h-handbrake-1.3.0.drv' failed
```

So far extending with which seems asked `ell` lib and extending build config flags with "LIBS='-ldl'" did not help.

**Comment by ckauhaus** [comment]
Side questions: Is packaging Handbrake really worth the hassle given the fact that devs are uncooperative? There are other options like ffpeg...

**Comment by jtojnar** [comment]
```
  : make[3]: *** [Makefile:623: ghb] Error 1
  : make[3]: Leaving directory '/build/HandBrake-1.3.0/build/gtk/src'
  : make[2]: *** [Makefile:445: all-recursive] Error 1
  : make[2]: Leaving directory '/build/HandBrake-1.3.0/build/gtk'
  : make[1]: *** [Makefile:377: all] Error 2
  : make[1]: Leaving directory '/build/HandBrake-1.3.0/build/gtk'
  : make: *** [../gtk/module.rules:30: gtk.build] Error 2
```

Wait, is it trying to build GTK?

Weirdly, it does not seem to require any special treatment in Arch.

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/handbrake

```
ninja: error: loading 'build.ninja': No such file or directory
```

You will want to disable ninja setup hook using

```
dontUseNinjaBuild = true;
dontUseNinjaInstall = true;
dontUseNinjaCheck = true;
```
