### ISSUE TITLE
 nixos-rebuild fails with "gitolite-init Fatal: fingerprinting failed for..."

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#7340]
I don't know much more than this:

```
Apr 12 18:37:13 lucy gitolite-init-start[28302]: FATAL: fingerprinting failed for 'keydir/<somehash>-gitolite-admin.pub'
```

and [some stackoverflow thread](http://stackoverflow.com/questions/10736767/getting-fatal-object-is-corrupted-when-pushing-to-a-remote-repo/10744027#10744027) but I don't know how to fix this.

**Comment by abbradar** [comment]
I was bit by this as well. It fails on other key for me -- looks like it would fail on any.

**Comment by matthiasbeyer** [comment]
How did you solve this issue?

**Comment by matthiasbeyer** [comment]
Can someone tell me where this "keydir" should be located? I cannot find it in my `/nix/store`!

**Comment by Lassulus** [comment]
The keydir should be in your gitolite datadir, which is /var/lib/gitolite in the default settings.

**Comment by matthiasbeyer** [comment]
Okay.

My `/var/lib/gitolite` shows:

```
projects.list 
repositories
```

**Comment by Lassulus** [comment]
oh it should be in "/var/lib/gitolite/.gitolite/keydir", my bad.

**Comment by matthiasbeyer** [comment]
Okay, everything is there. How to check why it fails?

**Comment by Lassulus** [comment]
It failed for me for every key on v3.6.2. So, besides upgrading gitolite to v3.6.3, there is not really much you can do.

**Comment by matthiasbeyer** [comment]
Update solved the issue.
