### ISSUE TITLE
meson builds failing on i686-linux

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#73417]
**Describe the bug**
The channel is currently blocked on the i686-linux minimal ISO not building.
https://hydra.nixos.org/build/106718862

It's both failing at `xorg.xorgproto` and `gtk-doc`

Both of these packages use the meson build system and produce a similar output on failure
```
Project name: xorgproto
Project version: 2019.1

meson.build:21:0: ERROR: Unknown compiler(s): [['/nix/store/38rh09iclvs97fisbgy8fg6wxr33ijr1-gcc-wrapper-8.3.0/bin/cc']]
```

```
Project name: gtk-doc
Project version: 1.32

meson.build:1:0: ERROR: Unknown compiler(s): [['/nix/store/38rh09iclvs97fisbgy8fg6wxr33ijr1-gcc-wrapper-8.3.0/bin/cc']]
```

cc @jtojnar @Ericson2314 @matthewbauer 

---

It's another topic entirely if i686-linux should be able to block channels.
In my opinion, it's not at the same tier of support to be able to have a channel blocking job like this.

**Comment by jtojnar** [comment]
Re channel dependency: https://github.com/NixOS/nixpkgs/commit/93aa83deb4923a2362814d952495aeab3ec49288

**Comment by worldofpeace** [comment]
Git bisect said this was at fault cd87f1ba239b79eb69ba86938644a1307243f45d ??

**Comment by jtojnar** [comment]
I got d0c73e88b3f9a50356f50c5d2db9a93b579139df, damn the merge commits.

**Comment by jtojnar** [comment]
That is just weird. On `cd87f1ba^` (3cf749b5) I see the following in logs:

```
C compiler for the host machine: /nix/store/d915ffl08q1yckm2laqwvjj55ykjq6vd-gcc-wrapper-8.3.0/bin/cc (gcc 8.3.0 "gcc (GCC) 8.3.0")
```

Comparing the two does not show anything suspicious:

/nix/store/d915ffl08q1yckm2laqwvjj55ykjq6vd-gcc-wrapper-8.3.0/bin/cc
/nix/store/38rh09iclvs97fisbgy8fg6wxr33ijr1-gcc-wrapper-8.3.0/bin/cc

**Comment by jtojnar** [comment]
Applying the following to Meson

```patch
diff --git a/mesonbuild/environment.py b/mesonbuild/environment.py
index dc8f099b..66a30754 100644
--- a/mesonbuild/environment.py
+++ b/mesonbuild/environment.py
@@ -678,6 +678,7 @@ class Environment:
 
             try:
                 p, out, err = Popen_safe(compiler + [arg])
+                print('::::::::::::', compiler, [arg], '++++', out, err)
             except OSError as e:
                 popen_exceptions[' '.join(compiler + [arg])] = e
                 continue
```

revealed

```
:::::::::::: ['/nix/store/38rh09iclvs97fisbgy8fg6wxr33ijr1-gcc-wrapper-8.3.0/bin/cc'] [''] ++++  gcc: error: : No such file or directory
```
That pointed me to:

https://github.com/mesonbuild/meson/blob/07389e23bc225adb9f9462e2fec1272ee24062e9/mesonbuild/environment.py#L862-L864

The hash contains `icl` so it matches some obscure compiler!

**Comment by worldofpeace** [comment]
Ewwwww :rofl: This is actually rather funny.
I can assume what the folllow-up PR to this will be doing to meson...
