### ISSUE TITLE
add introspection files to the libpulseaudio package

### ISSUE THREAD

**Issue by feijoas** [NixOS/nixpkgs#73463]
As I am trying to port the budgie desktop form the abandoned PR https://github.com/NixOS/nixpkgs/pull/12150. 

A `nix-build` of my port results in the error:

```
error: Package `libpulse-mainloop-glib' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `libpulse' not found in specified Vala API directories or GObject-Introspection GIR directories
```

@jtojnar mentioned this may be due to missing introspection files in the libpulseaudio package.

The relevant part of the derivation is:
```
{ stdenv, meson, ninja, fetchurl, makeWrapper, pkgconfig, libuuid, clutter,
  glib, gobjectIntrospection, gnome3, libpulseaudio, alsaLib, libwnck3, vala,
  intltool, libxml2, gettext, librsvg, gdk_pixbuf, polkit, gtk-doc, upower, sassc, ibus, libnotify, accountsservice }:

stdenv.mkDerivation rec {
  pname = "budgie-desktop";
  version = "10.5.1";

  src = fetchurl {
    url = "https://github.com/solus-project/budgie-desktop/releases/download/v10.5.1/${pname}-${version}.tar.xz";
    sha256 = "0rg5ma2rrc85n9ls0zljbncw15m2mfvaw494hcm754q09rvfqdfh";
  };

  buildInputs = [ meson ninja makeWrapper pkgconfig clutter libuuid glib
                  gtk-doc upower sassc ibus libnotify
                  gobjectIntrospection gnome3.gtk gnome3.defaultIconTheme gnome3.gnome-settings-daemon
                  gnome3.libpeas gnome3.mutter gnome3.gnome_desktop
                  gnome3.gnome-menus gnome3.gnome_session gnome3.gnome-bluetooth librsvg gdk_pixbuf
                  libpulseaudio libwnck3 vala intltool libxml2
                  gettext polkit accountsservice alsaLib];
}
```

**Comment by jtojnar** [comment]
Dobrý t might be sufficient to add `gobject-introspection` to PulseAudioʼs `nativeBuildInputs` and `--enable-introspection` to `configureFlags`.

**Comment by jtojnar** [comment]
Apparently, libpulse is not based on GObject so it does not provide introspection. It should install VAPIs though, not sure why it is not happening.

**Comment by alex5nader** [comment]
I've recently been trying to build budgie as well, and have run into the same issue. Was any solution found? Here's my derivation: https://gist.github.com/alex5nader/fbd1fc48693459b6d2bd39e02833178f.

**Comment by jtojnar** [comment]
Looking at it again, the issue is that the vapi files (in `$out/share/vala/vapi`) are removed here:

https://github.com/NixOS/nixpkgs/blob/f188138af3ebfd2f4d3c87f591b23b98396424f9/pkgs/servers/pulseaudio/default.nix#L114

**Comment by alex5nader** [comment]
Would a fix in nixpkgs just be removing all of $out/share except for any .vapi (and possibly .deps) files?

**Comment by jtojnar** [comment]
Correct. Or rather, the whole `share/vala/vapi` directory should be preserved.
