### ISSUE TITLE
NixOS RPi4 after reloading new config would still keep things from the installer config

### ISSUE THREAD

**Issue by diamondburned** [NixOS/nixpkgs#73487]
## Description
Right now, the [sd-image-raspberrypi4.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/sd-image-raspberrypi4.nix) imports [installation-device.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/installation-device.nix), which does multiple things, such as enabling the `nixos` user or disabling SSH and wpa_supplicant autostart.

According to https://github.com/NixOS/nixpkgs/issues/63576, the end-user should `nixos-generate-config` and `nixos-rebuild switch` to that new config. However, after a reboot, I saw both new config attributes (my created user was there) and old attributes (the nixos user was there, SSH was not autostarted, ...). 

During the config switch, errors were spotted. However, later switches on the same config did not really do anything (seemingly like the last switch was successful).

Since `sd-image-raspberrypi.nix` also imports what `sd-image-raspberrypi4.nix` imports, it's likely that other Raspberry Pis would have the same issue.

## Reproducing
1. Create a NixOS image which imports `sd-image-raspberrypi4` [refer to "Creating an image"]
2. Flash the image to a micro SD card and plug it into the Raspberry Pi 4
3. Go to the Pi's tty/console
4. Generate a new `configuration.nix` and switch:

```sh
sudo nixos-generate-config
sudo nixos-rebuild switch
```

## Expected Behavior
There should've been no traces of the `installation-device.nix` file, meaning the `nixos` user shouldn't be there.

## Screenshots
![](https://media.discordapp.net/attachments/361910177961738244/645166397294510080/unknown.png)

## Metadata
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.75, NixOS, 20.03pre201329.f1682a7f126 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre201329.f1682a7f126"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### Addendum: Creating an Image (has to be done on an aarch64 machine)

1. Save this file as `./sd-image.nix`
```nix
{ config, pkgs, lib, ... }:

{
	imports = [
		<nixpkgs/nixos/modules/installer/cd-dvd/sd-image-raspberrypi4.nix>
	];
}
```

2. Run this command
```sh
nix-build '<nixpkgs/nixos>' -A config.system.build.sdImage -I nixos-config=./sd-image.nix
```

**Comment by diamondburned** [comment]
I have some sort of clues right now. The generation in `/boot` is up to date, but the generation in the `FIRMWARE` partition is still the old one. 

I'm thinking a fix would be to change [this line](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/sd-image.nix#L115) to `"/boot"`

**Comment by diamondburned** [comment]
Another update, seems like `populateRootCommands` in `sd-image.nix` is never used?

**Comment by diamondburned** [comment]
Got SSH working AND config reload working with ```nix
{
	sdImage.populateFirmwareCommands = ''
		${config.system.build.installBootLoader} ${config.system.build.toplevel} -d ./
	'';
	sdImage.populateRootCommands = ''
		mkdir -p ./files/var/empty
	'';

	fileSystems = lib.mkForce {
		"/boot" = {
			device = "/dev/disk/by-label/FIRMWARE";
			fsType = "vfat";
			# we NEED this mounted
		};
		"/" = {
			device = "/dev/disk/by-label/NIXOS_SD";
			fsType = "ext4";
		};
	};
}
```

I'll make a PR soon.

**Comment by mmahut** [comment]
@diamondburned awesome work!

**Comment by Renha** [comment]
Could you please give a link to your PR?

**Comment by cmacrae** [comment]
@diamondburned :wave: I built an image with your above method (fixes for `/var/empty` & `/boot` mount/population included). It did indeed seem to fix the `sshd` issue, as `/var/empty` was now present, however when I generate a config, switch to that, after reboot it seems I'm chucked back to the boot configuration of the installer.  

Would you mind sharing the `configuration.nix` you're using for your RPi4? I'm not sure what I'm missing :thinking:

**Comment by diamondburned** [comment]
Regarding this: with the burden of my procrastination and me keep making new projects, I'm afraid I can't make a PR.

Though I still have my working config; if someone could pick this up, I would really appreciate it: https://gitlab.com/diamondburned/nix-rpi4

@cmacrae ^

**Comment by cmacrae** [comment]
Cheers @diamondburned :pray: Sure, I'll happily pick this up.  
I'll try and get a PR in tonight :)

**Comment by Renha** [comment]
@cmacrae can you please provide a link to your PR?

**Comment by cmacrae** [comment]
@Renha I haven't had the time to open it yet, I'm afraid. Free weekend ahead of me though, so I'll set a reminder up!

**Comment by cmacrae** [comment]
@Renha There you go :point_up: :slightly_smiling_face:

**Comment by Artturin** [comment]
Reply if still relevant.
