### ISSUE TITLE
Lean can't be built on i686

### ISSUE THREAD

**Issue by vvs-** [NixOS/nixpkgs#73493]
**Describe the bug**
Lean needs gcc6 override on i686 because of `__divmoddi4` bug.

**To Reproduce**
1. nix-env -iA nixos.lean on i686 platform.

**Additional context**
upstream: ~~https://github.com/leanprover-community/lean/issues/84~~

**Metadata**
```
 - system: `"i686-linux"`
 - host os: `Linux 5.2.17, NixOS, 19.03.173553.6420e2649fa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173553.6420e2649fa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by veprbl** [comment]
Also see #36947

**Comment by vvs-** [comment]
> Also see #36947

This issue is different. The problem here stems from the fact that Lean tries to link against `libgcc.a` in gcc instead of `libgcc_s.so` in gcc-lib. The question is why it is so?

**Comment by vvs-** [comment]
Here is a test case:
```
extern long long xxx(long long a, long long b);

int main()
{
   xxx(1LL,2LL);
   return 0;
}
```
```
long long __attribute__ ((visibility("hidden"))) xxx(long long a, long long b)
{
   long long x1, x2;
   x1 = a / b;
   x2 = a % b;
   return x1+x2;
}
```
Compiling the second into DSO and linking with the first gives similar error message using g++. In this case failed linking is justified, but the error message is completely misleading. I believe that any hidden function can trigger it if by coincidence it contains division and remainder of 64-bit integers.

But this also makes this issue even more mysterious to me. The only idea that comes to mind is that Nix passes `-fvisibility=hidden` to g++ somewhere.

**Comment by vvs-** [comment]
Oh, so it #36947 after all! `libgcc_s.so` in glibc is in path before gcc's and it's still broken.

**Comment by vvs-** [comment]
Depends on #36947.

**Comment by vvs-** [comment]
Builds without override on 20.09.
