### ISSUE TITLE
CodiMD does not provide options for storing db password outside the Nix store

### ISSUE THREAD

**Issue by gbiscuolo** [NixOS/nixpkgs#73502]
I'm going to use the [CodiMD](https://nixos.org/nixos/options.html#services.codimd) service but AFAIU there is no way to store the database password outside the store (see #24288).

Is it please possible to add an option - e.g. `services.codimd.configuration.dbURLFile` - that reads del database URL (and password) from a file?

Something like `services.nextcloud.config.adminpassFile`?

Thanks! Gio'

**Comment by gbiscuolo** [comment]
This is a related topic I started on Discourse: [In configuration.nix can I read a value from a file?](https://discourse.nixos.org/t/in-configuration-nix-can-i-read-a-value-from-a-file/4809)

**Comment by aanderse** [comment]
Seems doable. Could create a set of `database` options, [much](https://nixos.org/nixos/options.html#services.moodle.database.) [like](https://nixos.org/nixos/options.html#services.zabbixserver.database.) [some](https://nixos.org/nixos/options.html#services.gitea.database.) [other](https://nixos.org/nixos/options.html#services.redmine.database.) [services](https://nixos.org/nixos/options.html#services.grafana.database.) [have](https://nixos.org/nixos/options.html#services.wordpress.%3Cname%3E.database.) and then use `jq` to patch in the `database.passwordFile` in the `systemd` `preStart` script.

**Comment by aanderse** [comment]
@gbiscuolo do you have any interest+time+ability to work on this?

**Comment by gbiscuolo** [comment]
Hello Aaron,

thank you for your interest in this issue

Aaron Andersen <notifications@github.com> writes:

> @gbiscuolo do you have any interest+time+ability to work on this?

I surely have interest but right now I still miss some ability and
needed time to work on this (means also acquire new capabilities).

Maybe I'll try in a feew weeks but please do not count on me for this,
sorry

Thanks! Gio'

[...]

-- 
Giovanni Biscuolo

Xelera IT Infrastructures

**Comment by aanderse** [comment]
Understood. Thank you for reporting the issue. Leave it to me. :+1:

**Comment by aanderse** [comment]
Sorry, I haven't got around to this. Still relevant I believe.

**Comment by aanderse** [comment]
this service doesn't exist anymore
