### ISSUE TITLE
gdal-1.11.2 recipe should countain openssl as a dependency

### ISSUE THREAD

**Issue by rudregues** [NixOS/nixpkgs#7352]
I was failing to compile gdal, it was complaining about bin/ld being not able find -lssl and -lcrypto

 ttuegel helped me on irc and pointed out openssl as a dependency.

Here you can see the recipe at master:
https://github.com/NixOS/nixpkgs/blob/release-14.12/pkgs/development/libraries/gdal/default.nix#L29

Obs.: I just added openssl between {} and inside buildInputs as a parameter and gdal builded.

Obs2: this is my first bug login in github and first Nix usage and I could not miss the opportunity to say congrats for this nice piece of software.

**Comment by michelk** [comment]
This has been fixed with 2ed90cd27fa9059d783889bc05617b11b3ca6498. Could this be closed?
