### ISSUE TITLE
zoom-us: Sign In with SSO hangs on "Connecting..."

### ISSUE THREAD

**Issue by rossabaker** [NixOS/nixpkgs#73532]
**Describe the bug**
After entering the domain for Sign In with SSO and clicking "Continue", the zoom window turns white with message "Connecting...", and never finishes.  After closing and restarting zoom, the application starts back up as "Connecting..." until the `~/.zoom` directory is removed.  Sign In with SSO still doesn't work.

**To Reproduce**
1. Run `zoom-us`
2. Click "Sign in"
3. Click "Sign in with SSO"
4. Enter domain and click "Continue"
5. Observe "Connecting..."
6. Close zoom window.
7. Run `zoom-us`
8. Observe "Connecting..."
9. Close zoom window.
10. `rm -r ~/.zoom`
11. Run `zoom-us`
12. Back to Step 2: Sign In button is available, but won't work.

**Expected behavior**
After step 4, a browser should launch to complete the single sign in.

**Additional context**
`embeddedBrowserForSSOLogin` in ~/.config/zoomus.conf defaults to `true`. The behavior is unchanged if I set this variable to false and relaunch.  `xdg-open` is never called.

`embeddedBrowserForFacebookLogin` and `embeddedBrowserForGoogleLogin` both default to false.  When clicked, the Facebook and Google signins invoke `xdg-open http://`, resulting in an empty browser window.  When those variables are set to true, `xdg-open` is not invoked, and the zoom window closes without presenting a browser.  The application remains open and the tray is responsive, but there is no signin.  The workaround in #69352 does not work for me.

All three login methods work on Debian Stable.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 20.03.git.c1966522d7d (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/4pir570j86g0byq1pchcgfh845gigihx-nixpkgs`
```

My `nixpkgs` is pinned to c1966522d7d5fa54db068140d212cba18731dd98.

**Comment by veprbl** [comment]
cc @danbst @tadfisher

**Comment by danbst** [comment]
Confirmed. My best guess is that we should use back the provided Qt libraries (currently we use Nixpkgs Qt).

**Comment by danbst** [comment]
A bit of progress. Figured out this is because Zoom requires Qt 5.9, but it was removed entirely in https://github.com/NixOS/nixpkgs/pull/73261. The last working remnants of Qt 5.9 are left in nixos-19.09, which can be used to resurrect Zoom:
```
  # suitable for overlay
  zoom-us-resurrected = let
    oldpkgs = import (fetchTarball "https://github.com/nixos/nixpkgs/archive/release-19.09.tar.gz") {};
    qt59 = oldpkgs.qt59;
    mkLibsForQt5 = oldpkgs.mkLibsForQt5;
    libsForQt59 = recurseIntoAttrs (lib.makeScope qt59.newScope mkLibsForQt5);
  in libsForQt59.callPackage <nixpkgs/pkgs/applications/networking/instant-messengers/zoom-us> { };
```
I'm pretty sure that [fix](https://github.com/NixOS/nixpkgs/pull/74289) for https://github.com/NixOS/nixpkgs/issues/74273 is incorrect, because it should rather use Qt 5.9, not latest Qt. @adisbladis I think this is exactly the case when compatibility unexpectedly breaks.

**Comment by adisbladis** [comment]
@danbst Qt has a stable ABI, any binary linked against a 5.x release is compatible with newer 5.x releases, re-linking Zoom against 5.12 is fine.

**Comment by dtzWill** [comment]
On Mon, 16 Dec 2019 03:47:37 -0800, adisbladis <notifications@github.com> wrote:
> @danbst Qt has a stable ABI, any binary linked against a 5.x release is compatible with newer 5.x releases, re-linking Zoom against 5.12 is fine.

I'm not saying you're wrong,
and I don't know what the explanation is "yet",
but something is going on...

I can confirm that while zoom-us on nixos-unstable
doesn't work w/SSO (this issue) the proposed overlay-esque
produced a zoom-us that *does* work. (?!)

Here's what I used succcessfully this morning
(for a meeting ending ~10 min ago :D):

```nix
{
  # suitable for overlay
  zoom-us-resurrected = let
    oldpkgs = import (fetchTarball channel:nixos-19.09) {};
    qt59 = oldpkgs.qt59;
    mkLibsForQt5 = oldpkgs.mkLibsForQt5;
    libsForQt59 = oldpkgs.recurseIntoAttrs (oldpkgs.lib.makeScope qt59.newScope
mkLibsForQt5);
  in libsForQt59.callPackage
<nixpkgs/pkgs/applications/networking/instant-messengers/zoom-us> { };
}
```

Which I put in a file `zoom.nix` and built it with `nix build -Lf zoom.nix`.
(I think it could be dropped in an overlay folder, but didn't try yet)

My `<nixpkgs>` is my own tree (eep), actually but is largely `master` but messier O:).

(given it worked for person posting the snippet, I doubt the differences matter?
but LMK if re-testing would help anything :))

**Comment by pbogdan** [comment]
Was looking into a different issue today (https://github.com/NixOS/nixpkgs/issues/75903)  but FWIW from a quick check I can also confirm what poster above is seeing when comparing latest zoom linked against QT 5.9 libraries from current 19.09 vs zoom from unstable.

**Comment by rossabaker** [comment]
Trying again, on zoom 3.5.361976.0301 from nixpkgs a2e06fc3423c4be53181b15c28dfbe0bcf67dd73, I can set `embeddedBrowserForSSOLogin=false` in ~/.config/zoomus.conf and sign in through Chrome. The xdg-open dialog pops up in Chrome, but the Zoom window continues to spin on "Connecting..."

I can then kill zoom, and run `xdg-open $ZOOMMTG`, where $ZOOMMTG is the zoommtg:// URI from the "Launch Zoom" button in the browser.  

xdg-open through the browser works following calendar invites to join meetings, but not yet on this.  But I can successfully sign in now, with those workarounds.

**Comment by ConnorNovak** [comment]
I had this same issue:
- Ubuntu 16.04
- Latest Zoom .deb file for Ubuntu (as of 2020-04-01)
When I tried to sign in with SSO, Zoom window would switch to "Connecting" and open a new window with a long random alphanumeric key printed in it, but hang there.
**Solution:**
Set `embeddedBrowserForSSOLogin` in ~/.config/zoomus.conf to false. Able to log in with SSO.

**Comment by felixgolcher** [comment]
rossabaker's proposal works for me with zoom 3.5.385850.0413 on ubuntu 19.04. Thank you so much.

**Comment by kennyballou** [comment]
I'm still having this issue with the zoom-us version 5.3.469451.0927 and the work around using `xdg-open` is not working either.

In the latter case, I receive the following error after my token address: "The specified location is not supported".

I have not tried creating a custom override for `zoom`, but I may try that later.

**Comment by kennyballou** [comment]
`zoom-us` from nixpkgs.unstable (cfed29bfcb28259376713005d176a6f82951014a) seems to work for me.

The option for toggling the embedded browser does not seem to do anything.

**Comment by SebTM** [comment]
@kennyballou @rossabaker Seems to be not an issue anymore, don't have a SSO account to check again on stable and unstable but would close it up on your feedback if your are fine with that? :)

**Comment by rossabaker** [comment]
I'm no longer running Zoom on my NixOS machine, but it was working fine for me for quite a while.  I'm good with closing.

**Comment by dunnl** [comment]
Signing in with Zoom via SSO works for me on 22.11.

**Comment by SebTM** [comment]
Seems ok so far so closed for now 👍🏻

**Comment by cxandru** [comment]
This is again an issue for me

**Comment by cxandru** [comment]
I see the following error in the logs, though I can't confirm it's related:
```
QProcess: Destroyed while process ("./zopen") is still running.
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
