### ISSUE TITLE
nextcloud not compatible with nginx acme

### ISSUE THREAD

**Issue by lambdafu** [NixOS/nixpkgs#73585]
I had a hard time to set up letsencrypt with nextcloud in nixos, because the acme-challenge location is matched with "(none)" like this: "location /.well-known/acme-challenge", while nextcloud adds a rule that matches with "^~" for the "." route: "location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console)" which has "deny all" in it.  The effect is that all acme-challenges are disallowed with 403.

As a work around, I could get it to work with this setting (note the "^~" match; also, I had to use a / at the end to avoid a duplicate rule error, but the / is not needed otherwise).

```
    locations."^~ /.well-known/acme-challenge/" = { extraConfig = "allow all; root /var/lib/acme/acme-challenge; auth_basic off;"; };
```

I used this configuration:

```
  services.nginx.virtualHosts."censored.somenet" = {
    forceSSL = true;
    enableACME = true;
  };

  networking.firewall.allowedTCPPorts = [ 80 443 ];

  services.nextcloud = {
    enable = true;
    https = true;
    hostName = "censored.somenetwork";
    nginx.enable = true;
    config = {
      adminpassFile = "/etc/nixos/nextcloud-pass.txt";
    };
  };
```

**Comment by jeremypenner** [comment]
Just ran into this exact bug and got stuck on it for an hour or two before eventually coming to the same workaround described above.

**Comment by tobiasBora** [comment]
I just tried with Nixos 20.03 (commit [925ae0dee63](https://github.com/NixOS/nixpkgs/archive/925ae0dee63.tar.gz)), and I didn't get this problem... Don't know why it worked for me.

**Comment by keithy** [comment]
closable? works for me in 21.11

**Comment by RonnyPfannschmidt** [comment]
just ran into this on 22.5 and unstable

**Comment by RonnyPfannschmidt** [comment]
turns out in my case, i didnt forward http via the router, thus acme would fail

**Comment by Enzime** [comment]
Works for me :)
