### ISSUE TITLE
nixos-generate-config omits swapDevices

### ISSUE THREAD

**Issue by jamescostian** [NixOS/nixpkgs#73596]
**Describe the bug**

I have installed NixOS on a desktop I built, a Dell Inspiron 15 7591, and a Thinkpad X1 Carbon. Each time, I used the graphical live CD for 19.09, followed [the UEFI partitioning instructions](https://nixos.org/nixos/manual/#sec-installation-partitioning-UEFI) and [the formatting instructions](https://nixos.org/nixos/manual/#sec-installation-partitioning-formatting) from the official NixOS manual. On each machine, `nixos-generate-config` made a `hardware-configuration.nix` with an empty `swapDevices`, despite me making and formatting a swap partition just like how the manual told me to.

**To Reproduce**

1. Start the live cd (not sure if this only happens on graphical variants)
2. Follow [the installation guide](https://nixos.org/nixos/manual/index.html#sec-installation) from the NixOS manual
3. Note that `/mnt/etc/nixos/hardware-configuration.nix` has an empty `swapDevices`

**Expected behavior**

I expect the swap partitions I made to be used in `swapDevices`. At the very least, the manual should be updated to explicitly tell me to put the swap partition in `swapDevices`, but IMO this would be a poor UX.

**Additional context**

I set `swapDevices` using this:

```
lsblk --output="fstype,uuid" | grep '^swap' | awk '{print "swapDevices = [ { device = \"/dev/disk/by-uuid/" $2 "\"; } ];"}'
```

I would send a PR, but [when I searched](https://github.com/NixOS/nixpkgs/search?q=nixos-generate-config&unscoped_q=nixos-generate-config) for the source code, I couldn't find it. Sorry

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.82, NixOS, 19.09.1258.07e66484e67 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1258.07e66484e67"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by eadwu** [comment]
I personally never had a problem with it, do you just run `mkswap` or do you also run `swapon`?

**Comment by jamescostian** [comment]
@eadwu you're completelyed right, for some reason I've always ignored swapon! Sorry, my bad
