### ISSUE TITLE
dante: client not built with preloading support. 

### ISSUE THREAD

**Issue by xwvvvvwx** [NixOS/nixpkgs#73697]
**Describe the bug**

Running the `socksify` binary from the [dante](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/dante/default.nix) package produces the following error message:

`socksify: error: dante client not built with preloading support.`

**To Reproduce**

1. `nix run nixpkgs.dante -c socksify`

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(me): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/yhwija7420fay3zmqskmywbnyr143221-nixpkgs`

Maintainer information:
```yaml
attribute:
- dante
```

**Comment by xwvvvvwx** [comment]
cc @Shados

**Comment by Shados** [comment]
It's caused by the same breakage I mentioned [here](https://github.com/NixOS/nixpkgs/pull/68418#discussion_r343625853). I've set a reminder to PR a fix for it once I'm home tonight, but here's the fix in overlay format if you like:
```nix
(self: super: {
  dante = super.dante.overrideAttrs(oa: {
    configureFlags = if !super.stdenv.isDarwin
      then [ "--with-libc=libc.so.6" ]
      else [ "--with-libc=libc${super.stdenv.targetPlatform.extensions.sharedLibrary}" ];
  });
})
```
