### ISSUE TITLE
NixOS "auto-update" feature

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#7369]
I could see some people wanting their NixOS instance to automatically run `nixos-rebuild switch --upgrade` on some schedule. Doing the obvious thing (creating a systemd job that runs periodically and runs that command) fails because you can't sensibly run `nixos-rebuild` inside a systemd job (see #6662).

Is there a nice way to get this behavior? The idea is that given a fixed configuration and a channel, you don't want to have to worry about keeping yourself up to date with patch releases.

**Comment by jagajaga** [comment]
Maybe use cron? Or I didn't get your question..

**Comment by copumpkin** [comment]
Is cron independent of systemd on NixOS? If it runs inside a systemd service, I'll have the same problem I describe in #6662.

**Comment by jagajaga** [comment]
My fault.

**Comment by copumpkin** [comment]
:heart:
