### ISSUE TITLE
password-store derivation does not properly allow overriding

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#73701]
If you create an overlay for the `pass` derivation, this works, but it fails to apply that override to the `pass` which is used by `pass.withExtensions`. This is due to `pass` being defined as such (where `generic` is a function that produces the derivation):

```
generic (env (_: [])) {
  withExtensions = extensions: generic (env extensions) {};
}
```

So when you overlay `pass`, you affect the outer derivation, but not the inner one brought into scope using `pass.withExtensions`.

**Comment by abathur** [comment]
It looks like this was probably fixed in the course of #82691
