### ISSUE TITLE
services.nginx.preStart has bad UX

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#73742]
**Describe the bug**
The option `services.nginx.preStart` contains bootstrap code necessary for the first run on nginx to succeed, but it's defined with option default priority, so setting the option without manually prepending the option default or using priority 1500 breaks the first startup.

It should probably be created with normal config priority instead.

**Comment by danbst** [comment]
Related - https://github.com/NixOS/nixpkgs/pull/56255 emptifies `preStart` default.

**Comment by SuperSandro2000** [comment]
The preStart option no longer contains anything with default priority.
