### ISSUE TITLE
`documentation.nixos.includeAllModules = true` breaks local module building

### ISSUE THREAD

**Issue by SRGOM** [NixOS/nixpkgs#73743]
**Describe the bug**

Using a local module with the said option causes failed `nixos-rebuild`

```
.
.
.
documentation.nixos.includeAllModules = true;
.
.
.
	imports =
	[
		   /home/UJAH/STUFF/nixpkgs/nixos/modules/programs/onedrive.nix
.
.
.

```

**To Reproduce**
1. Above two lines! 
2. build!

**Comment by d-goldin** [comment]
Is the error in queston sth like the following?

```
error: in 'toFile': the file 'options.xml' cannot refer to derivation outputs, at /home/dmi/projects/nixpkgs/nixos/lib/make-options-doc/default.nix:89:16
```

**Comment by SRGOM** [comment]
Sorry my computer died. I should have noted the error ...

**Comment by d-goldin** [comment]
> Sorry my computer died. I should have noted the error in my original post

Is the one I posted close to what you have been observing?

**Comment by SRGOM** [comment]
Attached is the error- its about using local path ...

```
building '/nix/store/ck0dfbxr38mj1qpr85zsg2283i434m3v-options-docbook.xml.drv'...
          <string value="/home/zx/workspace/git/nixpkgs/nixos/modules/programs/onedrive.nix" />
The manual appears to depend on the location of Nixpkgs, which is bad
since this prevents sharing via the NixOS channel.  This is typically
caused by an option default that refers to a relative path (see above
for hints about the offending path).
```

**Comment by d-goldin** [comment]
Ok, I see. That's rather working as intended, also see [19.09 release notes](https://nixos.org/nixos/manual/release-notes.html#sec-release-19.09-notable-changes) for a short note about this option. Since this file seems to be under your control it's probably best to just fix it up.

**Comment by SRGOM** [comment]
> working as intended.

Thanks for looking!
