### ISSUE TITLE
ktorrent fails to start on 19.09

### ISSUE THREAD

**Issue by ivanovsaleksejs** [NixOS/nixpkgs#73760]
**Describe the bug**
On 19.09 ktorrent fails to start, it dumps an error:

> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**To Reproduce**
1. Install ktorrent on 19.09.
2. Launch ktorrent.

**Expected behavior**
ktorrent should run without problems. It worked on 19.03.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 19.09.1292.e1843646b04 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1292.e1843646b04"`
 - channels(aleksejs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
fixed with 0afec75e0cdf4d77cf36db749acfdad35a1d95b2
