### ISSUE TITLE
DBIx::Class fails to build (breaks Hydra)

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#7376]
`perlPackages.DBIxClass` fails to build on `nixpkgs` master or latest unstable channel (see build log [1]). Simple package update yields another test error, which I have no idea how to fix. This breaks Hydra builds. @edolstra ? 

[1]: http://pastebin.com/RAhmTwSP

**Comment by wizeman** [comment]
Duplicate of #6837?

**Comment by abbradar** [comment]
Right, thanks -- haven't used right keywords for search.
