### ISSUE TITLE
Discourse is down

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#73774]
I get:
```
Corrupted Content Error

The site at https://discourse.nixos.org/t/moving-gcroots-handling-to-nix-daemon/4850 has experienced a network protocol violation that cannot be repaired.
```
whenever I try to load anything on discourse

not really sure who to contact
@grahamc @FRidh

**Comment by falsifian** [comment]
https://discourse.nixos.org/ works for me. Is it still down for you?

**Comment by jonringer** [comment]
I'll have to check when i get home, but it seems to be working fine agian
