### ISSUE TITLE
Package request:hastecli

### ISSUE THREAD

**Issue by mortim59** [NixOS/nixpkgs#73782]
Project description
hastecli is CLI for https://hasteb.in client written in Haskell.

I built with stack and ghc compilator.

Metadata
    repos:https://github.com/mortim59/hastecli
    license: bsd-3-clause
    platforms: unix

**Comment by cdepillabout** [comment]
@mortim59 If you upload hastecli to Hackage, it will automatically be available in nixpkgs.

**Comment by mortim59** [comment]
Oh okay thanks.
