### ISSUE TITLE
[Installation Failed]: Running the install script for nix fails on centos 7

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#73783]
**Describe the bug**
I am trying to install the nix on a freshly install centos 7. However, it fails complaining that it cannot find boehm-gc-8.0.2. Whereas when I look at the /nix/store that particular version is there in the archive.

**To Reproduce**
More on this in the Screenshots section below.

**Expected behavior**
It should lead to a regular single-user installation of nix as described here:
- https://nixos.org/nix/manual/#chap-installation

**Screenshots**
```bash
bash <(curl https://nixos.org/nix/install) --no-daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2399  100  2399    0     0   3115      0 --:--:-- --:--:-- --:--:--  3111
downloading Nix 2.3.1 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.3.1/nix-2.3.1-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.COSQCOWEXM'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.2M  100 15.2M    0     0   207k      0  0:01:15  0:01:15 --:--:-- 94057
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
performing a single-user installation of Nix...
copying Nix to /nix/store................................
error: path '/nix/store/27il0yv1qzxlgx5pq25463lxn0h9c014-boehm-gc-8.0.2' is not in the Nix store
/tmp/nix-binary-tarball-unpack.COSQCOWEXM/unpack/nix-2.3.1-x86_64-linux/install: unable to register valid paths
```
**Additional context**

**Metadata**
- Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
- Cannot run the above command, as the nix is not installed yet.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
This issue is with Nix and not Nixpkgs, so it should be filed to https://github.com/NixOS/nix/issues

**Comment by rowhit** [comment]
I apologize. Apparently, there some mixup. I had one earlier custom location non-standard nix location. And in the installation toolchain, may be some binary from the /non/standard/nix/store was causing issue.

**Comment by veprbl** [comment]
@rowhit If the other nix installations interfere with the install script, then this is a bug. If the problem is reproducible don't hesitate to file an issue about that.
