### ISSUE TITLE
Package request: topmenu-gtk

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#73811]
**Project description**
Gtk+ module and Mate/Xfce panel applets for a global menubar
Please also include wrappers for firefox,thunderbird and  zotero

**Metadata**

* homepage URL:https://git.javispedro.com/cgit/topmenu-gtk.git/about/
* source URL:https://git.javispedro.com/cgit/topmenu-gtk.git/
* license:  gpl2
* platforms: unix

**Comment by Mindavi** [comment]
I'm sorry nobody picked this up. Since upstream seems unmaintained and interest otherwise seems low for this, I'm gonna close this.

Please resubmit or reopen if this is still relevant.
