### ISSUE TITLE
[20.03] Remove `sd_image_raspberrypi4` from branch

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#73828]
This image is not a "release worthy" image. To reduce risks of users relying on such an image, it should be removed from 20.03 when 20.03 is forked.

The `sd_image_raspberrypi4` only exists due to the difficulties mainline Linux have with integrating the Raspberry Pi 4 within the mainline kernel. This image is expected to be removed the moment mainline can be used with the Raspberry Pi 4.

Nixpkgs only targets the generic aarch64 image as a build product. No device-specific image is desired, nor desirable. This image is only produced as a best-effort for one of the most popular aarch64 platform.

(Ping me at release time if you're not sure what this all means.)

**Comment by worldofpeace** [comment]
Thanks for opening this in advance @samueldr. 
I expect a PR when we branch off?
