### ISSUE TITLE
openvpn: update-resolve-conf.sh not found

### ISSUE THREAD

**Issue by pirboazo** [NixOS/nixpkgs#73822]
**Describe the bug**
The script update-resolv-conf is not in the path /etc/openvpn 

**To Reproduce**
1. install openvpn
2. install  update-resolv-conf
3 .launch openvpn openvpn.config

trace : 

> openvpn fr.protonvpn.com.udp.ovpn
> Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
> Options error: Please correct this error.
> Use --help for more information.
> 

The config file include the pass on the script as it is
 describe in https://github.com/alfredopalhares/openvpn-update-resolv-conf and in the script
```
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

This is the standard location .

I can't modify because i have no path on this.

> [root@nixos-1909:~]# which update-resolv-conf
> which: no update-resolv-conf in (/root/bin:/run/wrappers/bin:/root/.nix-profile/bin:/etc/profiles/per-user/root/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin)
> 

**Expected behavior**
Have a script in /etc/openvpn

**Additional context**
It will be possible to modify the config file but several service provide many configfile.

**Metadata**
 nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 19.09.1223.cb2cdab7136 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1223.cb2cdab7136"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:

**Comment by d-goldin** [comment]
I'm not sure this would be such a great idea. Nix/OS already does quite a few things differently from other distributions, so this is not unique. Usually it would be a module's responsibility to set links in `/etc` and not the package's. 

For instance, on my system, I don't even have an `/etc/openvpn` directory and the config is loaded from the nix store.

Especially in the case of configuration files, which are meant to be adjusted to the environment, I don't see a strong case linking to this script from /etc just because it's a convention. Not sure I understand the part about several services providing many configuration files - could you explain?

If the issue is to reliably find the location of the script, one can use sth like;
```
> nix-instantiate --eval '<nixpkgs>' -A pkgs.update-resolv-conf.outPath                                                                   
"/nix/store/j2rz5ibq4idfgg015xwrkdjqc9kxc8z5-update-resolv-conf-2017-06-21"
```

If one were to use a module (like the openvpn module) to generate the config, it's quite straight-forward to point to the location doing sth like;

```
services.openvpn.servers.myvpn.config = ''
  [...]
  up ${pkgs.update-resolv-conf}/libexec/openvpn/update-resolv-conf
  [...]
'';
```

cc @abbradar as the maintainer

**Comment by pirboazo** [comment]
Hi @d-goldin,
 
I think there are two problems.

1. The link to /etc/openvpn
this can be easily bypassed by this command in configuration.nix

`
environment.etc.openvpn.source = pkgs.update-resolv-conf;
`

but currently this command is creating:
the following path: /etc/openvpn/libexec/openvpn


2. The presence of libexec/openvpn directories

A modification in the package like this one

```
installPhase = ''''.
    install -Dm555 update-resolv-conf.sh $out/update-resolv-conf
    install -Dm555 update-systemd-network.sh $out/update-systemd-network
    for i in $out/*; do
      wrapProgram $i --prefix PATH : ${binPath}
    done
  '';
```
would resolve the issue.

However, I don't see the impact on other applications.

ProtonVpn propose several > 550 configuration files, actually to use this file we must modify the path ( up and down)


Pierre

cc @abbradar as the maintainer

**Comment by d-goldin** [comment]
Hi again,

I will leave the question of whether adding a somewhat impure link to `/etc` from the package is a good idea or not aside.

But I'd like to note that the following:
> [...]
> `environment.etc.openvpn.source = pkgs.update-resolv-conf;`
> 
> but currently this command is creating:
> the following path: /etc/openvpn/libexec/openvpn

Can be addressed by doing something like:

```
environment.etc."openvpn/update-resolv-conf".source = "${pkgs.update-resolv-conf}/libexec/openvpn/update-resolv-conf";
```

**Comment by pirboazo** [comment]
HI 
Thank you for the discussion. 
Finally I used the following expression:
`environment.etc.openvpn.source = "${pkgs.update-resolv-conf}/libexec/openvpn";`

I will make one last comment once I have gone through the major distributions.

redhat
debian 
arch

& guix ;-)

Have a good day to you.
Pierre

cc @abbradar

**Comment by alexkutsan** [comment]
Last recipe works. 
Is there any more cute way to use openvpn with custom configs in NixOS?

**Comment by d-goldin** [comment]
@alexkutsan: I'm not sure what qualifies as cute in that regard, but I'm using [`services.openvpn.servers`](https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/services/networking/openvpn.nix#L81)

**Comment by tslug** [comment]
> HI
> Thank you for the discussion.
> Finally I used the following expression:
> `environment.etc.openvpn.source = "${pkgs.update-resolv-conf}/libexec/openvpn";`
> 
> I will make one last comment once I have gone through the major distributions.
> 
> redhat
> debian
> arch
> 
> & guix ;-)
> 
> Have a good day to you.
> Pierre
> 
> cc @abbradar

I had a similar issue, but this fix didn't work for me, even even on today's unstable branch.

I consistently got the same error about not being able to find /etc/openvpn/update-resolv-conf, but worse, it would then alter /etc/resolv.conf to strip my actual DHCP-assigned nameserver out of it, making all my attempts to resolve hostnames fail.

My fix in the end was to remove these two lines from my <vpn_name>.conf file:
`up /etc/openvpn/update-resolv-conf`
`down /etc/openvpn/update-resolv-conf`

And then add this to my configuration.nix:
`services.openvpn.servers.<vpn_name>.updateResolvConf = false;`

**Comment by xyakimo1** [comment]
@tslug thank you, it was my case too (i.e. the .ovpn file itself contained the `up` and `down` commands)
