### ISSUE TITLE
source-sans-pro font is broken after version upgrade

### ISSUE THREAD

**Issue by ivanovsaleksejs** [NixOS/nixpkgs#73830]
**Describe the bug**
Probably caused by  [07753d8](https://github.com/NixOS/nixpkgs/commit/3d8e8cb2baf5857402ee08b71a19f542c261b002). When printing, some of the characters are broken (replaced by ☒ symbol). Also, all regular characters are replaced by italic. Bold characters are not affected. Characters look good in editors or PDF viewers - they are broken only when printed out. Tested the older version of this font - it works properly.

**To Reproduce**
1. Install source-sans-pro font.
2. Print a document that contains text with this font.

**Expected behavior**
Fonts should work properly.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 19.09.1292.e1843646b04 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1292.e1843646b04"`
 - channels(aleksejs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
cc @dywedir @ttuegel

**Comment by ttuegel** [comment]
Which programs are you using to print? Is the printing issue also present if you "print to PDF"?

**Comment by ivanovsaleksejs** [comment]
Sorry for the long delay. The problem was with several programs including LibreOffice. Printing into PDF was without bug but when I tried to print that PDF the bug reappeared.

However, this bug disappeared some time ago. Everything works fine now.
