### ISSUE TITLE
firefox,thunderbird: add the option for libmenu based patch

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#73860]
**Project description**
Appmenu extra patch for firefox/thunderbird from the ubuntu team

**Metadata**

* homepage URL:
* source URL:https://launchpad.net/ubuntu/+source/firefox/ , https://launchpad.net/ubuntu/+source/thunderbird/
* license: GPL, MPL, LGPL 
* platforms: unix

**Comment by worldofpeace** [comment]
What patch? Can you provide a link?

**Comment by pasqui23** [comment]
https://aur.archlinux.org/packages/firefox-appmenu/,https://aur.archlinux.org/cgit/aur.git/tree/unity-menubar.patch?h=firefox-appmenu
I think that it also adds extra dependencies

**Comment by pasqui23** [comment]
still important to me

**Comment by pasqui23** [comment]
I still want this

**Comment by alexhulbert** [comment]
I'd also like this. There are many packages on AUR that all add the libmenu patch, including firefox-ubuntu-bin, firefox-kde-opensuse, firefox-appmenu, and plasmafox.

**Comment by pasqui23** [comment]
The relevant path from the aur is https://aur.archlinux.org/cgit/aur.git/tree/unity-menubar.patch?h=firefox-appmenu
https://aur.archlinux.org/cgit/aur.git/tree/unity-menubar.patch?h=thunderbird-appmenu

However I don't know the origin for those patches

**Comment by pasqui23** [comment]
Ok the source for firefox kde integration is https://build.opensuse.org/package/view_file/mozilla:Factory/MozillaFirefox/mozilla-kde.patch?expand=1 while for thunderbird https://build.opensuse.org/package/view_file/mozilla/thunderbird91/mozilla-kde.patch?expand=1

**Comment by dr460nf1r3** [comment]
I'm also interested in this. Basically very important if using KDE + appmenu applet.

**Comment by NovaViper** [comment]
Is there any progress on this? I'm willing to give it a test if necessary.

**Comment by tomodachi94** [comment]
Pinging maintainers @mweinelt (Firefox) and @lovesegfault, @nbp, and @vcunat (Thunderbird).

I'm not sure what our stance is on applying non-upstreamed nonessential(?) feature patches.

**Comment by mweinelt** [comment]
Not going to happen under my maintainership. I'm not going to just carry a 5k LoC downstream patch that has no chance of being accepted upstream.

**Comment by tomodachi94** [comment]
Closing at `wontfix` then. If anyone desperately wants it, you can add it using an override. 

Something like this:
```nix
with pkgs;
firefox.override (previous: {
  patches = (previous.patches or [ ]) ++ [
    fetchpatch
    {
      url = "...";
      hash = "...";
    }
  ];
})
```
