### ISSUE TITLE
Package request: graphql-engine

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#73877]
**Project description**

[Hasura GraphQL Engine](https://github.com/hasura/graphql-engine) is a GraphQL server that exposes data stored in PostgreSQL.

**Metadata**

* homepage URL: https://github.com/hasura/graphql-engine
* source URL: https://github.com/hasura/graphql-engine
* license: asl20, mit for community/
* platforms: all

**Comment by jonringer** [comment]
interesting, haskell backend, go cli, and javascript console...

**Comment by hlolli** [comment]
wow +1, I don't have experience with go or haskell, so I'm not a good candidate to make a nix expression for it.

**Comment by danbst** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/75527

**Comment by ivan** [comment]
Re-opening because it was removed in 008570968ca42afa078c54cde3a3b3c650c6c3b9

**Comment by datakurre** [comment]
@ivan Does this work for you https://github.com/NixOS/nixpkgs/pull/95369

**Comment by datakurre** [comment]
Seeing this now in master and nixos-20.09.

**Comment by jonringer** [comment]
there's now a `hasura-graphql-engine` package available. So I think the purpose of this package requests has been fulfilled
