### ISSUE TITLE
Package request: rosie

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#73921]
**Project description**
A supercharged alternative to regular expressions (regex), matching patterns against any input text.

**Metadata**

* homepage URL: https://rosie-lang.org/
* source URL: https://gitlab.com/rosie-pattern-language/rosie
* license: mit
* platforms: unix

PS: this may be relevant: https://gitlab.com/rosie-pattern-language/rosie/issues/102

**Comment by KoviRobi** [comment]
This is a cool program, I'll have a go at packaging :)

**Comment by KoviRobi** [comment]
Hmm, this will require upstream changes too, as it doesn't seem that amenable to packaging as is. It'll take a bit longer than I hoped, I'll see if I have some quiet time over the holiday period to work on it.

**Comment by KoviRobi** [comment]
But while I do that, you can have a play with https://github.com/KoviRobi/nixpkgs/tree/rosie-init-at-1.2.1 (it's a hack of a package, but it seems to work, let me know if things are broken)

**Comment by Enteee** [comment]
I think this can be closed since there is a pull request open for this now.

**Comment by suhr** [comment]
Add `fixes <issue link>` to the pr message so github will close the issue automatically when the pr is merged.
