### ISSUE TITLE
Use git submodules for nix packages

### ISSUE THREAD

**Issue by adithyaov** [NixOS/nixpkgs#73944]
## Issue description

Currently, the `nixpkgs` repository is a little over 1 GB. If I want to make a small PR for adding a simple package, I'll have to clone the entire repository of 1 GB. Of course, this would be done only once and it's not a big deal but I wonder how scalable this is. In the future, there could be a lot more packages increasing the size of this repository. Isn't it better to use git submodules for individual packages?

It is obviously tiresome to create git repositories for each package now. But every new package from here on can be made a git submodule. All the packages currently available can slowly be shifted to their own git submodules with time.

**Comment by adithyaov** [comment]
It may be the case that this is an overkill and is not required at all or is being done in some places. If so, please feel free to close this issue.

**Comment by veprbl** [comment]
You might want to check out https://github.com/nix-community/NUR and https://github.com/tweag/rfcs/blob/flakes/rfcs/0049-flakes.md . Also note that it used to be that NixOS and nixpkgs used to be separate repositories in the distant past and that didn't work out.

**Comment by adithyaov** [comment]
@veprbl Thank you for the links. I will check them out. I'll close this issue for now.
