### ISSUE TITLE
linuxsampler needs build-use-chroot to build

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#7397]
When building linuxsampler on debian 7, without build-use-chroot, I get:

nix-env -iA linuxsampler -f /home/bart/source/nixpkgs-goibhniu/ replacing old ‘linuxsampler-svn-2340’ installing ‘linuxsampler-svn-2340’ root@studio:/home/bart# nix-build --check /home/bart/source/nixpkgs-goibhniu -A linuxsampler checking path(s) ‘/nix/store/k62s5fg0si8zlinggidm9pijxdb48yh1-linuxsampler-svn-2340’ building /nix/store/1j3cidyjwmbxkjijy5jaffagkvb93r3k-linuxsampler-svn-2340 unpacking sources unpacking source archive /nix/store/40b49892i77k5lfz0sc0a5j3qjb8jf91-linuxsampler-r2340 source root is linuxsampler-r2340 patching sources applying patch /nix/store/42dbxlaw5vfbpcdglhx2hblmzsb0pllp-linuxsampler_lv2_sfz_fix.diff patching file src/hostplugins/lv2/PluginLv2.cpp Hunk #2 succeeded at 104 (offset -16 lines). Hunk #3 succeeded at 134 (offset -16 lines). configuring building configure .aclocal-wrapped: warning: autoconf input should be named 'configure.ac', not 'configure.in' libtoolize: putting auxiliary files in `.'. libtoolize: copying file `./ltmain.sh' libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.in and libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree. libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am. automake: warning: autoconf input should be named 'configure.ac', not 'configure.in' configure.in:1313: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see: configure.in:1313: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_INIT_AUTOMAKE-invocation configure.in:42: installing './config.guess' configure.in:42: installing './config.sub' configure.in:1313: installing './install-sh' configure.in:1313: installing './missing' automake: warning: autoconf input should be named 'configure.ac', not 'configure.in' src/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/Makefile.am: installing './depcomp' src/common/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/db/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/drivers/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/drivers/audio/Makefile.am:60: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/drivers/midi/Makefile.am:53: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/effects/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/engines/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/engines/common/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/engines/gig/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/engines/sf2/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/engines/sfz/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/hostplugins/au/Makefile.am:7: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/hostplugins/dssi/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/hostplugins/lv2/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/hostplugins/vst/Makefile.am:5: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/network/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/plugins/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') src/testcases/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS') Searching for a parser generator...Error: You need yacc (or bison) to generate the LSCP parser ! scripts/generate_parser.sh: 18: exit: Illegal number: -1 make: *** [configure] Error 2 builder for ‘/nix/store/354g2kwnliz2jvq4ddcv3dyrbrzb0854-linuxsampler-svn-2340.drv’ failed with exit code 1 error: build of ‘/nix/store/354g2kwnliz2jvq4ddcv3dyrbrzb0854-linuxsampler-svn-2340.drv’ failed

@falkTX got a similar error on KXStudio, also missing yacc or bison.

On NixOS or with build-use-chroot, it builds fine.

**Comment by joachifm** [comment]
Don't see how this is a problem
