### ISSUE TITLE
beegfs is broken

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#73998]
While working on https://github.com/NixOS/nixpkgs/issues/72828, I noticed beegfs is marked as broken and unfree. Even when I flip the necessary bits, I can't get the kernel module to compile.

@markuskowa, you seem to have added it, but marked it as broken in August. Do you still use it somewhere? Otherwise, I'd propose to remove it.

Also cc @Mic92.

**Comment by markuskowa** [comment]
@flokli I am not using it anymore. My initial proposal was to remove it  since one of the server components was unstable in production. We decided to just mark it broken for now (https://github.com/NixOS/nixpkgs/pull/66352).
