### ISSUE TITLE
chessx fails to start `because it could not find or load the Qt platform plugin "xcb" in "".`

### ISSUE THREAD

**Issue by jfaure** [NixOS/nixpkgs#74020]
nix-env -i chessx && chessx

**Comment by jfaure** [comment]
I'm getting the same error after updating the https://nixos.org/channels/nixos-unstable channel and upgrading, am I missing something ?

**Comment by worldofpeace** [comment]
See `How does a channel update` at https://howoldis.herokuapp.com for how changes move to a channel. 

If you want to be able to run the fixed program now you can do 
```
nix run -f https://github.com/NixOS/nixpkgs/archive/release-19.09.tar.gz chessx
```
