### ISSUE TITLE
nixos.iso_minimal has a nondeterministic disk guid

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#74047]
**Describe the bug**

When building `nixos.iso_minimal.x86_64-linux` twice, the GPT partition has a different GUID.

**To Reproduce**
1. `nix-build ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux`
2. `nix-build ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux --check --keep-failed`
3. use `gdisk` to see the GUID is not consistent (or `diffoscope` at `0x00000238`, https://en.wikipedia.org/wiki/GUID_Partition_Table)

**Expected behavior**
A deterministic GUID

**Additional context**
For additional background on why it's helpful for builds to be reproducible, see https://reproducible-builds.org/

I'd be happy to help hunt down and fix this problem further, but this is rather new territory for me, so I'd appreciate any help

**Comment by flokli** [comment]
@raboof Thanks for taking a look at this!
I'd suggest to trace it down from `nixos/modules/installer/cd-dvd/iso-image.nix`, and how things are passed down to `make-iso9660-image.nix` - but I'm not exactly sure WHAT creates the GPT partition.

**Comment by raboof** [comment]
Thanks for the encouragement!

Looking closer, it *seems* the GPT is written by `xorriso` as invoked in `make-iso9660-image.sh`.

Unfortunately, while manually invoking `xorrito` with fewer flags and `-boot_image any gpt_disk_guid=9b332887141c401f89b654dae2524a82` indeed has the expected effect, adding that flag to the invocation `make-iso9660-image.sh` doesn't. Some more digging to do! :)

**Comment by raboof** [comment]
Ah it's somehow the `isohybrid --uefi` post-processing... indeed that seems to generate a new random UUID with `uuid_generate`. Without `--uefi` it keeps it intact. I wonder if we need the `--uefi`, given `xorriso` already seems to do quite a bit of the work.

**Comment by flokli** [comment]
Shouldn't this be testable by trying to boot an image without that flag being set on a pure UEFI system?

**Comment by raboof** [comment]
I tested this by copying the ISO built without that flag to an USB disk, and booting my laptop with the "UEFI: USB disk" selected in the boot priorities. That worked fine.

I'll try to prepare a PR that makes the GPT disk GUID static (based on the derivation hash or `SOURCE_DATE_EPOCH`) and skips the `--uefi`. (though not sure when I'll get to it, if someone wants to beat me to it, feel free ;) )

**Comment by flokli** [comment]
Cool, this sounds very promising, also is one more step towards https://r13y.com :-) cc @grahamc 

yeah, just hashing over the input hash and converting that to the uuid format somehow sounds reasonable.
