### ISSUE TITLE
chirp: No module named gtk

### ISSUE THREAD

**Issue by hax404** [NixOS/nixpkgs#74079]
**Describe the bug**
After building chirp from master or release-19.09 branch, chirpw does not start and throws
```
WARNING: python-future package is not available; chirp.drivers.tk8180 requires it
Traceback (most recent call last):
  File "/nix/store/9xis5b779bn696vhqs6za4a9r5rh69zr-chirp-daily-20190925/bin/.chirpw-wrapped", line 131, in <module>
    from chirp.ui import mainapp
  File "/nix/store/9xis5b779bn696vhqs6za4a9r5rh69zr-chirp-daily-20190925/share/chirp/chirp/ui/mainapp.py", line 26, in <module>
    import gtk
ImportError: No module named gtk
```

**To Reproduce**
1. Check out the master branch. I did git bisect and found out the following:
   - The lastest known working commit is 7d3b44c9be008a34a3f36a0303fd8d3f20191244
   - Then there are some commits where the build is broken
   - The first known commit where chirpw breaks is 0570a6b1268
2. build and execute chirpw with ``$ nix-shell -I nixpkgs=. -p chirp --run chirpw``
3. chirpw does not start and gives the error message above.

**Expected behavior**
I would expect that chirpw starts and shows me a gui.

**Additional context**
If this is fixed, this should be also backported to release-19.09. In master the package python27Packages.future may be also included as dependency for compatibility with additional radio devices.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.891.80b42e630b2 (Loris)
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.891.80b42e630b2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc: @the-kenny

**Comment by jonringer** [comment]
this builds for me on master and release.

can you ensure you ahve the latest nix-channels, and that you don't have an overlay affecting the build please :)

**Comment by worldofpeace** [comment]
@jonringer, I believe this issue here is with its runtime.


It sounds like https://github.com/NixOS/nixpkgs/issues/56943, or maybe it's not wrapped correctly.

**Comment by jonringer** [comment]
ah, i ran chirp as well, and it was able to load fine :/

**Comment by hax404** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/f9dd4b27f168b32bf2c2ed3db4c09af9f0d836fc
