### ISSUE TITLE
pcsx2 fails to build

### ISSUE THREAD

**Issue by ilikeavocadoes** [NixOS/nixpkgs#74132]
**Describe the bug**
pcsx2 fails to build on master, unstable and stable.

**To Reproduce**
In nixpkgs repo:
```
git checkout master
git pull
nix-build . -A pcsx2
```

**Expected behavior**
The app should build without an error.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 19.09.1300.08e503bac6d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1300.08e503bac6d, nixos-unstable-20.03pre200231.7827d3f4497, nixos-previous-18.09.2519.2aa505b77c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by aanderse** [comment]
After reading through some issue threads it looks like there are a number of problems with modern (versions `7` through `9`) `gcc` and `pcsx` on the `1.4.0` release. It looks like a bit of a nightmare that I'm personally not interested in digging into...

I took a quick pass and came up with [this](https://github.com/NixOS/nixpkgs/compare/master...aanderse:pcsx2?expand=1) as a solution to make `pcsx2` build again. With this change the program builds & runs, but the `gtk` UI looks like garbage and I'm not convinced game controllers work.

@ilikeavocadoes are you interested in digging a bit deeper?

**Comment by ilikeavocadoes** [comment]
I would be interested, but unfortunately I don't think I have the skills to solve this. I know nothing about `gtk` things or controllers.

**Comment by aanderse** [comment]
Actually I verified that controllers **are** working, but the ui still looks like a disaster. I'm not sure if that is expected, or because of my setup... Do you want to build my branch and see if the ui renders any better for yourself?

**Comment by ilikeavocadoes** [comment]
The UI doesn't react to mouse clicks so I cannot test the menus. The font is not smoothed, and the app is in addition to its window spawning some kind of console where it logs errors. Here's a screencap of the main window:
![PCSX2  1 5 0-0 (git)_007](https://user-images.githubusercontent.com/36193715/70450262-13f8f000-1aac-11ea-9591-dadf01ec0552.png)

**Comment by neonfuz** [comment]
This issue can definitely be closed, there have been several changes pushed to pcsx2 since it has been opened and it builds fine now.
