### ISSUE TITLE
Nix-managed mutable state?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#7420]
This might be a poor place to collect general ideas on the topic, but I'm going to try anyway:

It seems like a fairly common pattern is to need a place to store mutable data. Perhaps you're spinning up a NixOS service that needs a state directory, or a user's home folder, or even `/var/log`. It seems like we could capture the "essence" of what characteristics each of those needs and make another hash-flavored name for it in a "mutable nix store", along with policies for how to initialize the state, back it up, upgrade it, etc.

It makes me pretty sad right now to have my services need a random unmanaged location on disk to store things which have data that can be succinctly described as "only myservice.service needs read/write access, it can live on a noexec partition, and it should be initialized to be empty, and it can be recreated on the fly so there's no need to back it up". Of course, it would be in a separate location than the usual store because the current one can be safely assumed to be read-only.

Has someone already thought about these sorts of questions? It feels like there's a lot of potential here.

**Comment by vcunat** [comment]
About the location: just specify a unique tag (string) for the instance, so two evaluations get the same directory iff the specify the same tag (concatenated with the name of service, for example). You don't really need to hash the tag(+service) string, as it probably won't be too long anyway.

The rest seems just about coding what to do if that path is in some particular state (and needs to be created/upgraded/etc). Note: I only thought about all this for five minutes or so.

**Comment by copumpkin** [comment]
@edolstra, I, and a few others (whose usernames I don't recall) talked about this at NixCon and came up with a few ideas. I'll try to write them up over the next few days if nobody beats me to it.

**Comment by copumpkin** [comment]
Actually, here are some preliminary thoughts based on what we discussed and other things that have crossed my mind since then:

The ultimate goal is to give the computer some degree of knowledge about the mutable state handled by a service. This would allow us to better isolate services (containers/namespaces to prevent them from touching things at runtime), capture their current state, back it up, restore it, upgrade it, and generally abstract over other annoyances in that space.

At the highest level, we break state into providers and consumers. Consumers request a place (or many) of tagged/named state to store things from the provider, which is managed by NixOS (or something related).

Examples of potential state providers:
* Filesystems (lots of different flavors)
* Temporary storage (different flavors with different properties)
* Postgresql (provides SQL databases/schemas, consumes filesystem state)
* Mysql
* Cassandra
* Proxies for remote versions of the above (i.e., I should be able to say that my postgresql lives elsewhere and have things work sensibly)

Consumers should be obvious.

At a minimum, a state provider should be able map a "tag" to a meaningful and stable domain-specific identifier structure. For example, the filesystem provider might take the tag "foo" and map it to `"/nix/state/fs/foo"` (TODO: think harder about mount points and multiple filesystems). A postgres provider would take a tag "foo" and give me some sort of attrset containing a domain+port and a DB name within it, or possibly a local unix socket also with a DB name. These state "pseudo-derivations" should also be enumerable from an evaluation, so that I can ask what state my `nixos-rebuild switch` is using.

Once we have a couple of basic providers in place, we can start taking a NixOS module attribute like `services.postgresql.dataDir` and have it default to an expression that looks something like `state.fs "postgresql.default"`, instead of `/var/db/postgresql` (TODO: think about migration path for people who never overrode the default value and don't want their DB to disappear when they upgrade NixOS).

Once we have that basic mechanism in place and a few things using it, we can start adding functionality to it. Key aspects I can think of:
* "Version"/upgrades/downgrades: consumers might be able to compute some sort of version of the state they store in a given producer. This version indicator could be valuable input for a `nixos-rebuild switch`, since perhaps it's non-trivial/impossible to switch back after upgrading to a new state version. We'd likely want `nixos-rebuild` to warn us that a downgrade is not possible or will break in such scenarios. Or perhaps run an upgrade/downgrade process if one is defined! This would be defined on the consumer level because different services use different processes to determine what version they're at and how to upgrade/downgrade their data.
* Backup/restore: a producer can capture a bundle of the data used by a process for backup and restore purposes
* Is the consumer's data inherently consistent? If not, perhaps let consumers provide a way to specify how to lock/unlock/sync their data so that a backup can be performed.
* Is the consumer's data shared? or is it wholly owned by the service? That might be the case for a remote database server, in which case we know that we shouldn't allow people to blindly restore database backups, for example, and restore procedures might be more complicated.
* Is the consumer's data a cache that can be regenerated? Might be good to know that when backing things up, and would also help people get a good overview of how state works on their system.
* Does the data provider support cheap snapshots? That might change our backup strategy. This is the case for e.g., cassandra or ZFS/btrfs-based filesystem providers.
* How do you initialize the state when you first set up the service?

Not every state provider would need to provide all (or any) of these features, but they could get layered on as we get better understanding of how the state flows across these things.


These tagged state "receptacles" (trying to avoid calling them containers) would not go away if unreferenced in a given configuration. You should be able to ask for all of the state the Nix state manager knows about and optionally collect it if you don't use a service anymore.


That's all for now, but please comment/add feedback! I'll write more when I've thought more about what it should look like implementation-wise.

**Comment by copumpkin** [comment]
Also wondering if we could treat UID mappings as state in this sense.

**Comment by copumpkin** [comment]
More radical yet, the Nix store itself is a piece of (heavily controlled) mutable state that can be GC'd.

**Comment by copumpkin** [comment]
@edolstra do you recall the name of the person who seemed very passionate about managing mutable state at NixCon? I'd like to highlight him on here but I don't know his name or his handle.

**Comment by Mathnerd314** [comment]
This sounds similar to what Disnix accomplishes; there's the [separation of concerns](https://github.com/svanderburg/disnix-proxy-example/blob/master/deployment/DistributedDeployment/services-with-proxy.nix), the [automated provisioning of databases](https://github.com/svanderburg/disnix-stafftracker-dotnet-example/blob/master/deployment/DistributedDeployment/services.nix), the dump/restore, and the focus on services. I guess we want a mini-Disnix that only supports deploying to one machine (the local one), integrated with the system activation scripts. cc @svanderburg if that's the case.

**Comment by svanderburg** [comment]
Hmm, I haven't noticed this issue so far, but I have created something called Dysnomia (https://github.com/svanderburg/dysnomia) that is primarily used by Disnix to take care of deployment of mutable components, such as databases. 

Although Dysnomia (previously called: Disnix activation scripts) was originally designed as a plugin system for Disnix, it can also be used as a stand-alone tool. (In theory) it can also be integrated into the appropriate NixOS modules to take care of deploying units of mutable state.

In Dysnomia, I have tried to map many Nix concepts to units of mutable state. For example, there is a system that marks state as obsolete and a garbage collector that removes units of obsolete state.

Moreover, there is a snapshot store (that shares concepts with the Nix store) in which snapshots can be stored and uniquely addressed.

I have given the NixOS integration some thought (already in my PhD thesis) but never made any serious efforts in doing so, although I don't think it would be that difficult to do. It's just simply that I never reserved any time for it.

Although Dysnomia is conceptually nice in some ways, it may not always be the best fit. For example, serializing the snapshot of the full state of a database and writing it to the file system can be quite costly. In such cases, database replication engines or filesystem-level snapshot solutions would be a better fit, although these solutions have drawbacks as well.

Because of the costs of serializing snapshots to the filesystem, Disnix does not use snapshotting by default -- it must be explicitly enabled by annotating a subset of services.

Maybe it would be a nice thing to provide Dysnomia integration into NixOS, but for similar reasons as Disnix, I would not recommend to enable this functionality by default.

Moreover, the ideal way to manage state generically (with similar quality attributes as Nix) is an open question that remains difficult to answer IMO. I haven't found an optimal solution -- Dysnomia is a solution that works in some cases, but it's definitely not the best.

**Comment by svanderburg** [comment]
@copumpkin Btw, there approach you described looks similar to something a master's student did years ago:

http://foswiki.cs.uu.nl/foswiki/Stc/ManagingStateInAPurelyFunctionalDeploymentModel

**Comment by CMCDragonkai** [comment]
I am packaging up libpostal which relies on a mutable state directory to load data. The package even exposes a command to update its data files. Usually these sorts of packages store their state in the HOME directory. But this package isn't associated to being part of a user. So I'm wondering whether it's possible to setup a stateful directory in /var for this package. Note that the location of the data directory must be set at the `configure` command which means at build time.

**Comment by CMCDragonkai** [comment]
Libpostal also isn't a service. It's just a set of libraries. The data files appear to be necessary for its inference engine to work. (Model weights and classification metadata).

**Comment by atanasi** [comment]
A simple solution for a package-specific state directory is making a subdirectory under `/var/state/nixstore/`, for example. The subdirectory would have the same name as the package directory under `/nix/store`. The garbage collection of the state directory could be done by checking if the corresponding store path is valid, and if it is not valid, the state directory can be removed.

**Comment by danbst** [comment]
I'm closing this as a stuck historical issue. Feel free to open new RFEs and RFCs with new ideas.
