### ISSUE TITLE
Example in nixos-container docs is broken

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#7421]
In https://nixos.org/releases/nixos/14.12/nixos-14.12.374.61adf9e/manual/ch-containers.html, this example doesn't work (curl hangs).

```
$ nixos-container update foo --config 'services.httpd.enable = true; \
  services.httpd.adminAddr = "foo@example.org";'

$ curl http://$(nixos-container show-ip foo)/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">…
```

It can be fixed by adding `networking.firewall.enable = false;` inside the container config.

**Comment by copumpkin** [comment]
It's probably better to add `networking.firewall.allowedTCPPorts = [ 80 ];`

**Comment by joachifm** [comment]
Please submit a PR if this is still a problem
