### ISSUE TITLE
update libvdpau to add VP9 decoding support

### ISSUE THREAD

**Issue by FelschR** [NixOS/nixpkgs#74211]
Recently `libvdpau` 1.3 with support for VP9 decoding has been released:
https://gitlab.freedesktop.org/vdpau/libvdpau/-/releases

This could present a very interesting improvement for video streaming performance in general and might be especially useful for Google Stadia as it relies on quick video decoding to be playable.
Though I don't even know if chromium's `useVaapi` flag currently works with an NVIDIA GPU.

`vdpauinfo` was also updated to support the changes but there hasn't been an official release yet:
https://gitlab.freedesktop.org/vdpau/vdpauinfo/commits/master

The `nvidiaBeta` drivers might be required to test VP9 support:
https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-440.26-Linux-Driver

**Comment by FelschR** [comment]
`vdpauinfo` has now also seen a new release with support for `libvdpau` 1.3:
https://gitlab.freedesktop.org/vdpau/vdpauinfo/-/releases

**Comment by vcunat** [comment]
The PR is in master now.
