### ISSUE TITLE
Define Fay with Fay Packages

### ISSUE THREAD

**Issue by mschristiansen** [NixOS/nixpkgs#7422]
I've just started using Nixos and have an existing Yesod project using Fay and the Fay packages fay-base, fay-text, and fay-jquery.

There are options to use the Fay compiler with commandline arguments `--fay-base` and `--include`, but this doesn't work well with auto compile infrastructure in Yesod.

One solution would be to define a combined package similar to how hoogleLocal is defined. E.g.
```
fayWithPackages = pkgs.haskellPackages.fay.override {
  packages = with pkgs.haskellngPackages; [
    fay-base, fay-text, fay-jquery
  ];
};
```
Could possibly even be defined as `nixpkgs/development/compilers/fay` to keep using cabal2nix for the Fay library.

There might be other options that I'm not aware of. Help would be much appreciated. @peti @ocharles

**Comment by peti** [comment]
I don't know much about `fay`, I'm afraid. From the sound of it, having a wrapper similar to the one for `ghc` sounds reasonable, though.

**Comment by peti** [comment]
I'm closing this ticket because it isn't an actionable item. General discussion of the subject is probably more appropriate for the nix-dev mailing list or the #nixos irc channel.

**Comment by mschristiansen** [comment]
No problem. I've moved on to GHCJS.
