### ISSUE TITLE
Bless Hex Editor

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#74245]
**Project description**
Bless - Gtk# Hex Editor 

**Metadata**

* homepage URL: https://github.com/afrantzis/bless
* source URL: https://github.com/afrantzis/bless
* license: gpl2
* platforms: unix, linux, darwin, (win32?)

**Comment by mkg20001** [comment]
https://github.com/NixOS/nixpkgs/pull/75670

**Comment by bjornfor** [comment]
Bless was merged a week ago (see PR from previous post). Closing.
