### ISSUE TITLE
Twinkle SIP client

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#74244]
**Project description**
Twinkle is a SIP-based VoIP client

**Metadata**

* homepage URL: http://twinkle.dolezel.info/
* source URL: https://github.com/LubosD/twinkle
* license: gpl2
* platforms: linux

**Comment by mkg20001** [comment]
I've noticed that this package was removed

**Comment by rnhmjoj** [comment]
@globin: why did you remove twinkle in 538aed6dea201f3f4cee8cbfb4c2b5d075051962?

**Comment by globin** [comment]
From the history probably because I removed the broken libzrtpcpp package, also it depended on qt3 which will be removed. If someone wants to repackage it cleanly feel free, but it didn't seem anyone cared about the package for the last half a year,

**Comment by mkg20001** [comment]
PR https://github.com/NixOS/nixpkgs/pull/74767

**Comment by mkg20001** [comment]
Added
