### ISSUE TITLE
gsettings-desktop-schemas dep missing for Next browser

### ISSUE THREAD

**Issue by Ambrevar** [NixOS/nixpkgs#74258]
## Issue description

https://github.com/atlas-engineer/next/issues/496 says that Next only renders a blank page on Nix.  In my experience, this is because the propagated input `gsettings-desktop-schemas` is missing.

### Steps to reproduce

Install Next in a profile that does not have `gsettings-desktop-schemas`.  Start Next.

## Technical details

Reporting this on behalf of a Nix user, I don't have Nix myself, sorry.

**Comment by worldofpeace** [comment]
I've opened https://github.com/NixOS/nixpkgs/pull/74265 to fix this issue.

**Comment by Ambrevar** [comment]
Thanks!
