### ISSUE TITLE
kde5: keyboard layout control panel not enabled

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#7426]
I can't configure keyboard layouts in KDE keyboard control module. Is there some quick fix to add a layout until this can be enabled? @ttuegel

**Comment by ttuegel** [comment]
On NixOS, you can configure your keyboard layout with `services.xserver.layout` as seen [here](https://github.com/ttuegel/nixos-config/blob/master/common.nix#L157).

**Comment by joelmo** [comment]
I have that option set, but I switch between two different layouts. Sorry for not mentioning this first.

**Comment by ttuegel** [comment]
You can specify [multiple layouts](http://www.x.org/archive/X11R7.7/doc/man/man4/kbd.4.xhtml); in the end, whatever you put in `configuration.nix` is just going into `xorg.conf`.

**Comment by ttuegel** [comment]
This is fixed in latest channel update.

**Comment by joelmo** [comment]
Thanks :smiley: I will test when it arrives to unstable
