### ISSUE TITLE
UX: Should we use a NixOS short version?

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#74276]
**Describe the bug**

The NixOS version number is very long.

```
$ nixos-version 
19.09.1320.4ad6f1404a8 (Loris)
```

It's good to know from which nixpkgs commit it was built. Needed for issues here.

But a user don't have to know the exact version. One rather uses the release version like used in the [release-notes](https://nixos.org/nixos/manual/release-notes.html#sec-release-19.09) when talking about it.

The long version also leads to UI breaking. For example in the Pantheon settings about panel:

![Screenshot from 2019-11-26 16-45-04](https://user-images.githubusercontent.com/91113/69648728-1f8bf600-106c-11ea-91b3-021bad6b2d97.png)

That looks broken. I would like to have just "NixOS 19.09 (Loris)" there.

## Possible solution

I propose to use the **release version** in end-user facing places and the **full version** which includes the revision for developers and debug tools.

That would mean:

nixos version = "19.09"
nixos full version = "19.09.1320.4ad6f1404a8"

Use nixos version in:

- /etc/os-release
- lsb-release script

Use full nixos version in:

- nixos-version
- nix-info

What do you think?

**Comment by edolstra** [comment]
Maybe just shorten the `PRETTY_NAME` field in `/etc/os-release`?

**Comment by davidak** [comment]
Yes, that would be enough.

Our lsb-release script uses that too: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/lsb-release/lsb_release.sh#L156

That should improve Pantheon about panel, Mumble and Steam (and thereby Protondb).

@edolstra do you agree that programs that try to detect the OS should get the short version?
