### ISSUE TITLE
Evaluate the necessity of gdk-pixbuf-xlib

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#74272]
As per https://mail.gnome.org/archives/desktop-devel-list/2019-November/msg00009.html, gdk-pixbuf-xlib is being deprecated and will be moved into a separate package in the next GNOME release (March 2020). Before then, we should find out what packages depend on it. I suggest disabling the xlib support by default and see what breaks.

**Comment by jtojnar** [comment]
Ugh.

**Comment by tteggel** [comment]
`gdk-pixbuf-xlib` is still needed by `pkgs/applications/virtualization/open-vm-tools` (VMWare guest support). See #90544.

**Comment by jtojnar** [comment]
Looks like there is still quite a few projects depending on this so let’s keep it for now.
