### ISSUE TITLE
RStudio "failed to start because no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#74298]
I have installed RStudio on NixOS via `environment.systemPackages`. When I try to start it, it fails with an error message:
```
$ rstudio
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

[1]    2573 abort (core dumped)  rstudio
$ echo $QT_PLUGIN_PATH
/home/c74d/.nix-profile/lib/qt4/plugins:/home/c74d/.nix-profile/lib/kde4/plugins:/etc/profiles/per-user/c74d/lib/qt4/plugins:/etc/profiles/per-user/c74d/lib/kde4/plugins:/nix/var/nix/profiles/default/lib/qt4/plugins:/nix/var/nix/profiles/default/lib/kde4/plugins:/run/current-system/sw/lib/qt4/plugins:/run/current-system/sw/lib/kde4/plugins
```

RStudio worked fine for me on NixOS in 2018, when it would build at all. Rebooting my computer doesn't fix the problem, so I doubt it's a transient problem with my desktop session.

I note that this is the same error message from #33702, #48826, and #54872, but my issue involves RStudio installed via `environment.systemPackages` rather than run via `nix-shell` as in those issues.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84-hardened, NixOS, 20.03pre202088.e89b21504f3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre202088.e89b21504f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
see https://github.com/NixOS/nixpkgs/issues/65399
