### ISSUE TITLE
ocaml package version bump to 4.09.0

### ISSUE THREAD

**Issue by XVilka** [NixOS/nixpkgs#74307]
Nix has 4.07.1 packaged, while 4.09.0 is already available.

See also the repology https://repology.org/project/ocaml/versions

Maintainer information:
```yaml
attribute: ocaml
module: ocaml
```

**Comment by vbgl** [comment]
What do you mean? You can access a set of OCaml packages for OCaml 4.09.0 through `ocaml-ng.ocamlPackages_4_09`. See [Wiki](https://nixos.wiki/wiki/OCaml#Specific_version_of_the_OCaml_compiler) for details.

**Comment by XVilka** [comment]
@vbgl but why repology shows the 4.07.1 as the latest version in the nixpkgs? See the link in the issue, then grep for `nixpkgs`.

**Comment by marsam** [comment]
closing since it doesn't depend on our side
