### ISSUE TITLE
`ls` from `coreutils` doesn't colorize orphaned symlinks, should this be changed?

### ISSUE THREAD

**Issue by typetetris** [NixOS/nixpkgs#74317]
As in the title.

At the moment ls colors orphaned symbolic links just as normal symbolic links per default.

As symbolic links are really ubiquitous in nix or nixos, is it a good a idea to change that default setting?
(From reading the comments in the source, the idea is not following symbolic links, if it isn't really necessary, to avoid the work. Coloring orphaned links different per default, all the effort not to follow symbolic links, wouldn't be used usually.)

It's a one line change, I could happily provide a pr (or is it mr) for.

### Steps to reproduce

In a directory without the files `a` and `b`.

    ln -s a b
    LS_COLORS="" ls --color=always

**Comment by buckley310** [comment]
I like this idea. After playing with it a little bit I went ahead and created a PR, since I think it deserves more than a 1-liner. There are bound to be those who want it toggleable.
