### ISSUE TITLE
Port hoogleLocal to haskell-ng

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#7432]
Ditto. This should probably be done before dropping old Haskell infrastructure completely. Also affects e.g. `lambdabot` and other packages which use Hoogle.
cc @peti . Probably I'll look at it myself at some point, but unfortunately I don't know much about Hoogle and I couldn't understand what current wrapper does from quick reading.

**Comment by peti** [comment]
There is work underway in https://github.com/NixOS/nixpkgs/pull/5908. Personally, I don't know much about Hoogle and can't say much about that topic, I'm afraid.

**Comment by abbradar** [comment]
Thanks for the heads up, I've searched in issues but not in PRs ^_^

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/commit/75f82f50e6a43d871fd7442d3b2dc943d0eb0bb0 should add support for hoogle again. Let me know if there's any trouble!
