### ISSUE TITLE
julia-1.3.0 version bump

### ISSUE THREAD

**Issue by XVilka** [NixOS/nixpkgs#74338]
The Nix version is old. Current stable version is 1.3.0:

## Current stable release: v1.3.0 (Nov 25, 2019)

- https://github.com/JuliaLang/julia/releases/tag/v1.3.0
- https://github.com/JuliaLang/julia/releases/download/v1.3.0/julia-1.3.0.tar.gz

## New language features

-    Support for Unicode 12.1.0 (#32002).
-    Methods can now be added to an abstract type (#31916).
-    Support for unicode bold digits and double-struck digits 0 through 9 as valid identifiers (#32838).
-    Added the syntax var"#str#" for printing and parsing non-standard variable names (#32408).

## Multi-threading changes

-    New experimental Threads.@spawn macro that runs a task on any available thread (#32600).
-    All system-level I/O operations (e.g. files and sockets) are now thread-safe. This does not include subtypes of IO that are entirely in-memory, such as IOBuffer, although it specifically does include BufferStream. (#32309, #32174, #31981, #32421).
-    The global random number generator (GLOBAL_RNG) is now thread-safe (and thread-local) (#32407).
-    New Channel(f::Function, spawn=true) keyword argument to schedule the created Task on any available thread, matching the behavior of Threads.@spawn (#32872).
-    Simplified the Channel constructor, which is now easier to read and more idiomatic julia. Use of the keyword arguments csize and ctype is now discouraged (#30855, #32818).

**Comment by 7c6f434c** [comment]
I vaguely remember that 1.2.0 update couldn't be done in a completely straightforward way… but maybe it was about tests.

**Comment by Sean1708** [comment]
> I vaguely remember that 1.2.0 update couldn't be done in a completely straightforward way… but maybe it was about tests.

Just to expand on this, #67099 mentions that BinaryBuilder.jl causes the build scripts to break so I suspect that getting that to work properly has been more involved than expected.

**Comment by elecprog** [comment]
If I recall correctly, there were some issues with artifacts in 1.3 that were fixed in 1.3.1.

I don't know if that's related to the issues you mentioned.

**Comment by cstich** [comment]
I managed to build 1.3.0 locally. However, I only managed to build the Julia binary that ships all the dependencies. It's this one: https://github.com/JuliaLang/julia/releases/download/v1.3.0/julia-1.3.0-full.tar.gz

If people are happy with this approach I can turn it into a pull request and probably bump my local build to 1.3.1

**Comment by 7c6f434c** [comment]
>I managed to build 1.3.0 locally. However, I only managed to build the Julia binary that ships all the dependencies. It's this one: https://github.com/JuliaLang/julia/releases/download/v1.3.0/julia-1.3.0-full.tar.gz

Building with the bundled dependencies, then (over time) checking which of them can be replaced with system ones sounds like a good plan.

And it's definitely better to have a build based on bundled dependencies than none…

Thanks for your efforts!

**Comment by cstich** [comment]
> Building with the bundled dependencies, then (over time) checking which of them can be replaced with system ones sounds like a good plan.
Cool. I also just managed to build 1.3.1, so I can put together a pull request in the next couple of days.

**Comment by cstich** [comment]
I just submitted a [pull](https://github.com/NixOS/nixpkgs/pull/79174) request for julia 1.3.1.

**Comment by solson** [comment]
The [pull request](https://github.com/NixOS/nixpkgs/pull/79174) is merged, so I guess this can be closed?

**Comment by rht** [comment]
Closed via #79174.
