### ISSUE TITLE
Skypeforlinux asks for login details always after start

### ISSUE THREAD

**Issue by angordeyev** [NixOS/nixpkgs#74343]
**Skype does not save login and password.**

**To Reproduce**
Install package on a fresh system with KDE.

**Expected behavior**
Skype will save login and password, no need to enter it each time.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: skypeforlinux
```

**Comment by tohl** [comment]
skype uses gnome keyring

1) enable gnome keyring in your configuration.nix:

   services.gnome3.gnome-keyring.enable = true;

2) either set up the right password in the gnome keyring yourselves
    (e.g. using seahorse gui)
    or easier

    - ensure that ~/.local/share/keyrings is empty

    - reboot

    - start skypeforlinux

    - login

    - quit

    - next time you start skypeforlinux, it will take your login details from the keyring

**Comment by tohl** [comment]
this is not a bug

**Comment by bachp** [comment]
KDE doesn't support the required secret service interface. https://bugs.kde.org/show_bug.cgi?id=313216

Closing this as there is nothing that can be done on NixOS side.
