### ISSUE TITLE
Sourcetrail (all versions) is now FOSS

### ISSUE THREAD

**Issue by alter2000** [NixOS/nixpkgs#74351]
**Project description**

From now on I don't think it's necessary to download and patch binaries, given that we can build straight from [the source repo](https://github.com/CoatiSoftware/Sourcetrail). It requires CMake, which I don't even know how to handle even in a more traditional distro, which is why I'm asking for help here.

The version in the unstable channel is 2019.3.46, while in nixos 19.09 it's 2019.2.39; both of which are marked as unfree and built as patched binaries, even though their source is now available.

**Metadata**

* homepage URL:
* source URL: <https://github.com/CoatiSoftware/Sourcetrail>
* license: unfree -> gpl3

Thanks for all!

**Comment by jtojnar** [comment]
Generally, you add `cmake` into `nativeBuildInputs` and see if it builds. Setup hook will set the appropriate phases for you. You might need to adjust `cmakeFlags`, and, likely, patch something as no-one knows how to write `CMakeLists.txt` correctly.

**Comment by filalex77** [comment]
I'm currently trying to do just that: https://github.com/NixOS/nixpkgs/pull/73974
Currently, I'm a bit stumped. Any help would be greatly appreciated!

**Comment by alter2000** [comment]
Ooh nice bot! From what I can see, it's still downloading binaries so I guess it's still unresolved. I might probably try to get to this during summer vacation I guess.

**Comment by Moredread** [comment]
I think there is also a new version out

**Comment by midchildan** [comment]
#95530 is now ready if anyone wants to try it out.

**Comment by midchildan** [comment]
This is resolved per #95530.
