### ISSUE TITLE
Update rustc-beta package to 1.0.0-beta2

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#7438]
I would do this myself, but I don't know if I need to change the snapshots.

http://www.rust-lang.org/install.html

**Comment by domenkozar** [comment]
@madjar

**Comment by madjar** [comment]
Hello @Havvy 

The snaphots are listed in https://github.com/rust-lang/rust/blob/master/src/snapshots.txt, that's where we get the the snapshot's date, rev, and all the shas.

However, in this case, it looks like there is no new snapshot, so there's no need to change them. Considering that, would you like to upgrade rust?

@domenkozar Thanks for the ping :)

**Comment by Havvy** [comment]
I've updated it locally and am currently building. Once it has successfully built and `rustc --version` gives the correct version string, I'll send in a PR.

**Comment by Havvy** [comment]
PR #7511 submitted.

**Comment by madjar** [comment]
PR is merged, closing this issue.
