### ISSUE TITLE
xrandrHeads "RightOf" option generation doesn't seem to work properly.

### ISSUE THREAD

**Issue by NoxDeleo** [NixOS/nixpkgs#7441]
I just started using NixOS yesterday, and was overjoyed to see such a simple configuration for multiple monitors. Unfortunately the following configuration gives me the first two monitors fine, however the rightmost monitor is a clone of the middle one.

`services.xserver.xrandrHeads = [
    "DisplayPort-0" "DVI-0" "DVI-1"
  ];`

`xrandr -q` output:

`Screen 0: minimum 320 x 200, current 3520 x 1200, maximum 8192 x 8192
DisplayPort-0 connected 1600x1200+0+0 (normal left inverted right x axis y axis) 408mm x 307mm
   1600x1200     60.00*+
HDMI-0 disconnected (normal left inverted right x axis y axis)
DVI-0 connected 1920x1080+1600+0 (normal left inverted right x axis y axis) 1150mm x 650mm
   1360x768      60.02 +
   1920x1080     60.00*   50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1280x720      60.96    60.00    50.00    59.94  
   1440x576i     50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94    59.94  
   720x400       70.08  
DVI-1 connected 1600x1200+1600+0 (normal left inverted right x axis y axis) 408mm x 307mm
   1600x1200     60.00*+`

I went hunting for the xorg.conf that gets generated, and I think it's probably the one pasted below, although I don't know how to find which one is the latest configuration, so I'm not 100% sure. As you can see, both the center and right monitors are listed as "RightOf" the left one.

`Section "Monitor"
  Identifier "multihead1"
  
EndSection
Section "Monitor"
  Identifier "multihead2"
  Option "RightOf" "multihead1"

EndSection
Section "Monitor"
  Identifier "multihead3"
  Option "RightOf" "multihead1"

EndSection`

Setting manually with `xrandr --output DVI-1 --right-of DVI-0` works fine.

Edit: Not sure what's going on with markdown here. xrandr output has newlines in editor.

**Comment by Fuuzetsu** [comment]
Looks to me that the accumulator resupplied should be `current ++ previous`, not `previous ++ current`:

```
  xrandrMonitorSections = let
    mkMonitor = previous: current: previous ++ singleton {
      inherit (current) name;
      value = ''
        Section "Monitor"
          Identifier "${current.name}"
          ${optionalString (previous != []) ''
          Option "RightOf" "${(head previous).name}"
          ''}
        EndSection
      '';
    };
    monitors = foldl mkMonitor [] xrandrHeads;
```
