### ISSUE TITLE
powershell: add DOTNET_CLI_TELEMETRY_OPTOUT=1 to pwsh wrapper

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#74516]
Cc @yrashk (PowerShell maintainer)

**Describe the bug**

Powershell uses telemetry unless explicitly told not to do it.
In addition to its own environment variable `POWERSHELL_TELEMETRY_OPTOUT` (already set in the wrapper), it should require another one to disable telemetry from the underlying .NET platform, i.e. `DOTNET_CLI_TELEMETRY_OPTOUT` should be set to `1`

**To Reproduce**

1. install powershell with `nix-env -iA unstable.powershell` (assumes you have the unstable channel installed)
2. launch it with `pwsh`
3. Run `[System.Environment]::GetEnvironmentVariable('DOTNET_CLI_TELEMETRY_OPTOUT')` and verify that it's not set (i.e. no output)

**Expected behavior**

`DOTNET_CLI_TELEMETRY_OPTOUT` should be set to `1`:

```pwsh
PS /home/user> [System.Environment]::GetEnvironmentVariable('DOTNET_CLI_TELEMETRY_OPTOUT')
1
```

**Additional context**

Example of PowerShell's own CI config that disables telemetry on Linux:

https://github.com/PowerShell/PowerShell/blob/4ff9924cbf0d2a64106f04c19137bbb020d844c7/.vsts-ci/linux.yml#L34

This should be fairly easy to change here:

https://github.com/NixOS/nixpkgs/blob/50c265ef0ec2aa6e0b42980d61112c466412ea2b/pkgs/shells/powershell/default.nix#L34

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80-hardened, NixOS, 19.03.173669.27f48796194 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.03.173669.27f48796194"`
 - channels(user): `unstable-20.03pre203172.0ee0489d42e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: powershell
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
@yrashk
