### ISSUE TITLE
aqemu: does not work with current kvm with network

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#74638]
**Describe the bug**
aqemu does not work with current kvm-versions, if you want to include networking.

Reason: aqemu always uses the obsolete/removed parameter "vlan", which causes kvm to exit.

Since there is no newer upstream version of aqemu:
- this should be patched,
- or aqemu should be removed from nixpkgs

**Metadata**
aqemu 0.9.2

**Comment by tomodachi94** [comment]
`aqemu` was dropped in https://github.com/NixOS/nixpkgs/pull/249582.
