### ISSUE TITLE
xrandrHeads could use an option to designate primary monitor

### ISSUE THREAD

**Issue by NoxDeleo** [NixOS/nixpkgs#7463]
In my case I use xmobar, which appears on whichever monitor is designated as the primary. I'm sure there are other applications which make use of this option.

I can set it with e.g. `xrandr --output DVI-0 --primary`, however this change doesn't persist across boots, so since xrandrHeads generates xorg.conf monitor sections anyway, throwing in `"Option" "Primary" "true"` for a designated monitor would be a big help.

**Comment by Fuuzetsu** [comment]
It's likely that `xrandrHeads` is going to get on overhault that will let you specify such things. cc @aszlig

**Comment by zimbatm** [comment]
Right now it's possible to set it but only on the first monitor:
```nix
services.x11.monitorSection = ''
 Option      "Primary" "true"
'';
```

**Comment by CMCDragonkai** [comment]
@zimbatm Does that actually choose the first monitor listed in `xrandrHeads`?

Also this option is necessary so that XMonad doesn't get confused with `Super + {w,e,r}` and also controlling where `xmobar` puts the status bar.

**Comment by CMCDragonkai** [comment]
@zimbatm Setting with `services.xserver.monitorSection` does not work in conjunction with `xrandrHeads`, as it adds the primary option to `Monitor[0]` and `Monitor[0]` seems to have no relationship with the monitor sections added by `${xrandrMonitorSections}`.

**Comment by CMCDragonkai** [comment]
I'm going to add an option like`services.xserver.xrandrPrimaryHead = "DP-0";`. It will search the `xrandrHeads` list for a corresponding name, and that monitor section will be the one that is given `Option "Primary" "true"`.

**Comment by CMCDragonkai** [comment]
Actually upon thinking about this more. It would be more scalable to do it this way:

```
                # builtins.attrNames { DP-0 = ""; } = [ "DP-0" ];
                # builtins.attrValues { DP-0 = "Option ..."; } = [ "Option ..." ];
                xrandrHeads = {
                    DP-0 =  ''
                        Option "Primary" "true"
                    '';
                    HDMI-0 = "";
                };
```

That way, we can have section configuration for every head in Xrandr.

And I can use the 2 above functions to and zip them together when deploying to `xrandrMonitorSections`.

**Comment by CMCDragonkai** [comment]
https://github.com/NixOS/nixpkgs/pull/13916

**Comment by MP2E** [comment]
Issue was already resolved as far as I can tell, reopen if this is not the case.
