### ISSUE TITLE
eclipse: download link does not work

### ISSUE THREAD

**Issue by Sina72** [NixOS/nixpkgs#7469]
The package download link (url) for the "eclipse-sdk-4.4" is not working.

**Comment by bjornfor** [comment]
Could it be a temporal error? Works here:

```
$ nix-build -A eclipses.eclipse_sdk_44.src
these derivations will be built:
  /nix/store/g5a2rnxyf32fc8j4ax1s2536qjn998gs-eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz.drv
building path(s) ‘/nix/store/pcvfxwj2cvhvfqz555i9awpmk357n1l2-eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz’

trying http://archive.eclipse.org/eclipse/downloads/drops4/R-4.4-201406061215/eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  196M  100  196M    0     0  5156k      0  0:00:39  0:00:39 --:--:-- 9635kj
/nix/store/pcvfxwj2cvhvfqz555i9awpmk357n1l2-eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz

$ tar -tf /nix/store/pcvfxwj2cvhvfqz555i9awpmk357n1l2-eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz | head
eclipse/
eclipse/configuration/
eclipse/configuration/org.eclipse.equinox.simpleconfigurator/
eclipse/configuration/org.eclipse.update/
eclipse/configuration/org.eclipse.equinox.source/
eclipse/about_files/
eclipse/features/
eclipse/features/org.eclipse.ecf.filetransfer.httpclient4.source.feature_3.8.1.v20140528-1625/
eclipse/features/org.eclipse.ecf.filetransfer.httpclient4.source.feature_3.8.1.v20140528-1625/META-INF/
eclipse/features/org.eclipse.ecf.core.ssl.source.feature_1.0.0.v20140528-1625/
```

(Also tested the 32-bit variant.)

But we might want to switch to the official (mirrored) URLs anyway:

http://wiki.eclipse.org/IT_Infrastructure_Doc#Use_mirror_sites.2Fsee_which_mirrors_are_mirroring_my_files.3F

(We want to use the ```r=1&nf=1``` args.)

**Comment by magnetophon** [comment]
For me the url doesn't work either.  I've tried a couple of tis in the last few days.
Also a few older versions don't download.

**Comment by vcunat** [comment]
It seems to download for me, but it's very slow. (~50kB/s when normally I have megabytes/s) Switching to official mirrors is probably best in any case.

**Comment by vcunat** [comment]
Hmm, I tried that same file by the recommended download link (with auto-choosing the best mirror), but the speed seems equally slow. http://www.eclipse.org/downloads/download.php?r=1&nf=1&file=/eclipse/downloads/drops4/R-4.4-201406061215/eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz

**Comment by magnetophon** [comment]
Just tried again:
http://download.eclipse.org/eclipse/downloads/drops4/R-4.4-201406061215/eclipse-SDK-4.4-linux-gtk.tar.gz
works intermittently, and
http://download.eclipse.org/eclipse/downloads/drops4/R-4.4-201406061215/eclipse-SDK-4.4-linux-gtk-x86_64.tar.gz
gives a 404.

**Comment by vcunat** [comment]
ATM I'm getting 404 for both your URLs above, and the one I posted last works relatively fast (100MB in 90 seconds). The availability really seems significantly changing in time.

**Comment by bjornfor** [comment]
I've updated all URLs to the officially mirrored ones in commit f5954509122160ed8209a3158e49ae054c12fcf8. That's the best we can do. I got download speeds between 100K and 10M when testing all URLs.
