### ISSUE TITLE
Missing XTest headers needed for package build

### ISSUE THREAD

**Issue by NoxDeleo** [NixOS/nixpkgs#7475]
I've been packaging up various g15tools/g15daemon packages for my keyboard LCD. It's been fairly smooth sailing thus far (great tools!), but I've come across a missing X extension header needed to build the last one.

>checking X11/extensions/XTest.h usability... no
>checking X11/extensions/XTest.h presence... no
>checking for X11/extensions/XTest.h... no
>configure: error: "Xorg XTEST Extension devel headers could not be found. please install the devel package

I added `x11` in buildInputs, but I couldn't find XTest anywhere in the packages search. I only started using NixOS on Saturday, so apologies if I'm missing something obvious.

**Comment by devhell** [comment]
@NoxDeleo I think it's in `libXtst`.

**Comment by NoxDeleo** [comment]
Oops. Forgot to mention I had that in buildInputs as well. No dice. Looking in the nix store I see it though.

>$ ls /nix/store/lcxjy9i9kmkn7i5miih2dvdsn7k1pfyg-libXtst-1.2.2/include/X11/extensions/
>record.h  XTest.h

Maybe something peculiar in the build scripts. I'm not particularly familiar with them, so I'll have to do some investigating. Thanks anyway.
