### ISSUE TITLE
Package request: termius (deb, Electron app)

### ISSUE THREAD

**Issue by filalex77** [NixOS/nixpkgs#74777]
**Project description**
> Termius is the SSH client that works on Desktop and Mobile.

A cross-platform SSH client with cloud data sync and more. 

**Metadata**

* homepage URL: https://termius.com/
* source URL: https://www.termius.com/download/linux/Termius.deb
* license: unfree
* platforms: linux

**Comment by Th0rgal** [comment]
It would be really cool, I need it too!
