### ISSUE TITLE
python3Packages.fido2 doesn't build

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#74805]
**Describe the bug**
Since the commit https://github.com/NixOS/nixpkgs/commit/a8d207c605e4eeb37869c835f75fa5401e9e30fa this package does not build. It fails with the following output:
```
$ nix-build --no-build-output -A python3Packages.fido2
these derivations will be built:
  /nix/store/gf3idshzggbpz0r1jxg9bg75nmzn6wkd-python3.7-fido2-0.7.3.drv
building '/nix/store/gf3idshzggbpz0r1jxg9bg75nmzn6wkd-python3.7-fido2-0.7.3.drv'...
builder for '/nix/store/gf3idshzggbpz0r1jxg9bg75nmzn6wkd-python3.7-fido2-0.7.3.drv' failed with exit code 1; last 10 log lines:
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 33, in <module>
      if StrictVersion(__version__) < StrictVersion("20.2"):
    File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/version.py", line 40, in __init__
      self.parse(vstring)
    File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/version.py", line 137, in parse
      raise ValueError("invalid version number '%s'" % vstring)
  ValueError: invalid version number '41.6.0.post20191122'
error: build of '/nix/store/gf3idshzggbpz0r1jxg9bg75nmzn6wkd-python3.7-fido2-0.7.3.drv' failed
```

**To Reproduce**
1. `nix-build --no-build-output -A python3Packages.fido2`

**Expected behavior**
Package should be building without errors.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.1, NixOS, 20.03.git.bc25302560a (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-18.09.2574.a7e559a5504"`
 - nixpkgs: 83c24adfca6

Maintainer information:
```yaml
attribute:
- python3Packages.fido2
- yubikey-manager
- python3Packages.solo-python
```

**Comment by dtzWill** [comment]
Can reproduce, strange.  Good news is bumping (as I happened to do locally earlier today for other reasons, haha) seems to fix things-- can you confirm that moving to 0.8.1 as in 40ecc83d16f6c89b82870f655fe496792429fb32 fixes this?

**Comment by prusnak** [comment]
I can confirm that bump to 0.8.1 fixes the build. (However we have 0.7.3 already in master, so the change from 40ecc83 does not apply cleanly).
