### ISSUE TITLE
gitea startup is broken

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#74849]
**Describe the bug**
gitea fails to start due to a too restrictive systemd setup

**To Reproduce**
`nix-build nixos/tests/gitea.nix`

Looks like #63840 is a bit too restrictive. :smile:

**Comment by flokli** [comment]
ping @kolaente

**Comment by srhb** [comment]
Removing the blacklist of `@chown` and `@privileged` gets us past the test, I think, but there's still problems with the socket.

**Comment by kolaente** [comment]
Judging from this error output:
```
machine # [   19.150491] rfjnab4ywjlc4qd507xq8dky534bxidn-unit-script-gitea-pre-start[925]: /nix/store/rfjnab4ywjlc4qd507xq8dky534bxidn-unit-script-gitea-pre-start: line 22:   935 Bad system call         (core dumped) sed -e "s,#secretkey#,$KEY,g" -e "s,#dbpass#,$DBPASS,g" -e "s,#jwtsecet#,$JWTSECET,g" -e "s,#mailerpass#,$MAILERPASSWORD,g" -i /var/lib/gitea/custom/conf/app.ini
```
it looks like it fails in prescript during `sed` in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/gitea.nix#L365

Interestingly enough, there is a `chmod` right underneath that, in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/gitea.nix#L370 which does not seem to be the issue.

This does not look like an issue with Gitea itself, since it fails during the service pre script.

Since the `sed` and `chmod` will only be run if the configuration is managed by nix, the tests pass if I set `services.gitea.useWizard = true;` in the test config.

**Comment by aanderse** [comment]
Any chance the `dump` service is broken too? I recently updated and `dump` service failed to start. I haven't dug into it yet... I may have seen something about a database permission issue.

**Comment by jollheef** [comment]
Temporary fix for someone who using bleeding-edge Gitea:
```
systemd.services.gitea.serviceConfig.SystemCallFilter =
  lib.mkForce "~@clock @cpu-emulation @debug @keyring @memlock @module @mount @obsolete @raw-io @reboot @resources @setuid @swap";
```

**Comment by petabyteboy** [comment]
> Temporary fix for someone who using bleeding-edge Gitea:
> 
> ```
> systemd.services.gitea.serviceConfig.SystemCallFilter =
>   lib.mkForce "~@clock @cpu-emulation @debug @keyring @memlock @module @mount @obsolete @raw-io @reboot @resources @setuid @swap";
> ```

This doesn't solve the issue for me. I get the following output:

```
Dec 04 19:02:40 schinken systemd[1]: Starting gitea...
Dec 04 19:02:40 schinken systemd[28749]: gitea.service: Failed to apply ambient capabilities (before UID change): Operation not permitted
Dec 04 19:02:40 schinken systemd[28749]: gitea.service: Failed at step CAPABILITIES spawning /nix/store/330jkvmavmdldv4mjab2ms6bs4370p61-unit-script-gitea-pre-start: Operation not permitted
Dec 04 19:02:40 schinken systemd[1]: gitea.service: Control process exited, code=exited, status=218/CAPABILITIES
Dec 04 19:02:40 schinken systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 19:02:40 schinken systemd[1]: Failed to start gitea.
```

**Comment by jollheef** [comment]
Pretty strange. It works for me ([complete configuration](https://code.dumpstack.io/infra/code.dumpstack.io/src/branch/master/configuration.nix)).

You can try to disable it at all (`lib.mkForce "";`) and if it'll still not work then just change in the same way all other parameters to default values that were introduced in d0261f6036751a5daecc903569875c9c7a9eb259.

p.s. probably there's must be something like a mkForceRemove, but I haven't found anything in manual.

**Comment by petabyteboy** [comment]
Ok the fix is actually working, I just had an own AmbientCapabilities definition in my configuration which didn't play nicely with the new options.
