### ISSUE TITLE
mkIf is broken, modules get unexpected arguments

### ISSUE THREAD

**Issue by oxij** [NixOS/nixpkgs#7488]
05e8a48fb4af4c20134362c77ba6c5b4c6e49268 broke `mkIf` for me. Correct me if I happen to use it wrong. I have something like the following in my `configuration.nix`

      packageOverrides = mkIf (!graphical) (pkgs: {
        # allow some
        xorg = { inherit (pkgs.xorg)
          imake
          mkfontscale mkfontdir bdftopcf
          fontbhttf fontbh100dpi
          fontbhlucidatypewriter75dpi fontbhlucidatypewriter100dpi
          fontcursormisc fontmiscmisc;
        };

        # disallow the rest
        xlibsWrapper = {};
        gtk2 = null;
        gtk3 = null;
        qt3 = null;
        qt4 = null;
        qt48 = null;
        qt5 = null;
        qt54 = null;
      });

and after that patch the `mkIf` breaks with

    error: while evaluating the attribute ‘config.system.build.toplevel’ at ...
    .....
    attribute ‘_module.args.pkgs’ missing, at "nixpkgs/lib/modules.nix":138:17

That patch also introduced `_module` thingies to all the submodules, which is an unexpected development.

/cc @nbp

**Comment by nbp** [comment]
How is graphical defined?  Does it depends on pkgs?
Can you paste a minimal version of your configuration which reproduce this issue?

**Comment by oxij** [comment]
Nope, it's just a boolean.

The minimal `configuration.nix` that breaks on master:

    {lib, config, ...}: with lib;
    {
    
        fileSystems."/" = { fsType = "tmpfs"; };
        boot.loader.grub.device = "/dev/sda";
    
        nixpkgs.config = {
          packageOverrides = mkIf false (pkgs: {});
        };
    
    }

**Comment by nbp** [comment]
Oh, I did not caught this before, but the problem is that `packagesOverrides` is not an option, but at attribute within the `nixpkgs.config` option.

`mkIf` is a function which is processed within options and within the type of the options when it is specified.  So to solve this issue, you should move the `mkIf` to the `nixpkgs.config` line.

This behaviour is unfortunately expected and should never have been accepted, even before commit 05e8a48.  Then I admit the error message is terrible.

**Comment by oxij** [comment]
@nbp makes sense. But what should I do when there's a ton of other options in nixpkgs.config some of which are to be `mkIf`ed too? I guess I need to `mkMerge` `mkIf`ed attribute sets, but this is soooo ugly.

**Comment by nbp** [comment]
@oxij, otherwise, you can use `if … then … else …` instead of `mkIf … …`.
