### ISSUE TITLE
passwd doesn't set the password in the installer.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#7489]
If you type two different passwords in the installer, you are told so, but if you then manually run passwd, it claims to update the password but doesn't.

I've been  bitten by this a few times now: the screensaver kicked in during an install and I wasn't sure whether I typed enter or space, so I typed something else the second time, assuming I could rerun passwd...

Not a problem if you know (rerunning the installer fixes it), but a pita if you don't.

**Comment by domenkozar** [comment]
That's because `passwd` ran at installer level sets the password for live cd. If you want to set password for your installing system it should be done via `nixos-install --chroot`. We should probably loop until password is specified or tell the user how to set the password.

**Comment by Profpatsch** [comment]
(traige) still a problem?

**Comment by magnetophon** [comment]
Idk, I haven't installed in a while.
Probably nothing changed yet though, exactly because this is an uncommon situation.

**Comment by andrewufrank** [comment]
i was bitten yesterday when installing - typing two different passwords the first time. then rerun the installer (which is fast, but this is not necessarily what a novice user expects) and set the password correct this time - unfortunately, this did not set the password to the new value. (i did manually edit the shadow file to get into the system - not recommended). for most new users this is a final problem.

I would recommend that you set up all what a user has to put into the config file initially - including the password, possibly encrypted. or set a default password to be changed on first run) and then run the installer without any user interaction. the question at the end was surprising to me. 
better even: let the user define a admin user with sudo privileges and password in the configuration and disallow login as root.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by magnetophon** [comment]
Not as far as I know.
I very much like @andrewufrank's suggestions though!

**Comment by rnhmjoj** [comment]
The confusion should have been cleared with eaf98c7bcf12f5f211126eb82698b8c1e7b7a4d8.
The installer now tells the exact commands to run to set the password in case of a mismatch.

**Comment by magnetophon** [comment]
@rnhmjoj Thanks!
