### ISSUE TITLE
John the Ripper binaries require AVX512BW extensions

### ISSUE THREAD

**Issue by lambdafu** [NixOS/nixpkgs#74918]
**Describe the bug**

I installed john the ripper from the binary cache, and executing it fails with:

```
$ john
Sorry, AVX512BW is required for this build
```

I have a recent laptop (Thinkpad T480s) with i7-8550U CPUs, but apparently that's not good enough.

It would be good to compile john with less demanding requirements for the benefit of most users, and maybe output a message how to compile it yourself on nix systems.

**Comment by matthewbauer** [comment]
Yeah it looks like one of the builders has this feature so the configure script requires it:

```
configure: Testing build host's native CPU features
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for SSE4.2... yes
checking for AVX... yes
checking for XOP... no
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
```

It looks like we need to pass the ```--disable-native-tests``` flag.

**Comment by prusnak** [comment]
cc maintainer @offlinehacker

**Comment by flokli** [comment]
backported to 19.09 in 0449a653eb378ccb23712fa4ab0374a35658ef7f.
