### ISSUE TITLE
Should python3Packages.imutils support opencv4?

### ISSUE THREAD

**Issue by schonfinkel** [NixOS/nixpkgs#74914]
**Describe the bug**
Looking at the current derivation of [imutils](https://github.com/NixOS/nixpkgs/blob/bb1013511e1e5edcf314df8321acf2f3c536df0d/pkgs/development/python-modules/imutils/default.nix#L4) it seems opecv's version is set to 3. This makes some code break if you're working on a `opencv4` project, since it'll fall back to version 3.

**To Reproduce**
1. Add `imutils` to an existing `opencv4` project,

Given the following `shell.nix`:
```
{ pkgs ? import <nixpkgs> {} }:

let
  python = pkgs.python37Packages;

  pythonPkgs = with python; [
    opencv4
  ];

  systemPkgs = with pkgs; [
    opencv4
  ];
in
pkgs.mkShell {
  name = "py-env";
  buildInputs = systemPkgs ++ pythonPkgs;
}
```
Verify that's running `openc4`:
```
$ python
Python 3.7.5 (default, Oct 14 2019, 23:08:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.2'
```

Now add `imutils` to `pythonPkgs`:

```
>>> import cv2
>>> cv2.__version__
'3.4.8'
```

**Expected behavior**
The correct version of opencv should be picked. 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.1, NixOS, 20.03pre203904.bb1013511e1 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre203904.bb1013511e1"`
 - channels(usul): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixos.python37Packages.imutils
# a list of nixos modules affected by the problem
module:
```

**Comment by tomodachi94** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/260727.
