### ISSUE TITLE
Gnome 3.34 night mode doesn't work

### ISSUE THREAD

**Issue by teh** [NixOS/nixpkgs#74934]
* mutter requires this patch: https://gitlab.gnome.org/GNOME/mutter/merge_requests/840.diff
* I built and tested the patch on top of `bb1013511e` (current unstable) and it compiles + fixes the issue.

@jtojnar want me to create a PR?

**Comment by worldofpeace** [comment]
There's been so many bugs uncovered in mutter that we could easily backport 10+ patches.
Personally, I've been running off https://gitlab.gnome.org/GNOME/mutter/commits/gnome-3-34 without issue.

**Comment by hedning** [comment]
Yeah, I'm also running on the `gnome-3-34` branches without any problem (not sure why they haven't cut a new a release tbh).

**Comment by worldofpeace** [comment]
@teh Opened #75002
