### ISSUE TITLE
nixos/tests/flannel fails

### ISSUE THREAD

**Issue by x123** [NixOS/nixpkgs#74941]
**Describe the bug**
`nixos/tests/flannel` does not succeed.

**To Reproduce**
`nix-build nixpkgs/nixos/tests/flannel.nix`

**Expected behavior**
The test should pass.

**Additional context**
Was attempting to port the test to python, couldn't find a useful test success case with the current setup or with several variations. Not sure if flannel is just broken or the original test was bad.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.14, NixOS, 19.09.1471.d387c2dd552 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1471.d387c2dd552, nixos-hardware, unstable-20.03pre203904.bb1013511e1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
this thing has been broken for a while https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.flannel.x86_64-linux/.

**Comment by worldofpeace** [comment]
cc @johanot.

@x123 Feel free to PR your port anyways, we can mark the test as `broken` like
```
meta = {
  https://github.com/NixOS/nixpkgs/issues/74941
  broken = true;
};
```
