### ISSUE TITLE
libreoffice: broken build on master

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#74948]
**Describe the bug**
Using commit `d3f928282c0989232e425d26f0302120a8c7218b`. See build output [here](https://gist.github.com/tbenst/302e01b0c0479e08f32e5be22197c062).

Not sure who the maintainer is as no @raskin on github, so pinging recent committers @malbarbo @mmilata @adisbladis

**Comment by mmilata** [comment]
Guessing that poppler update broke it: 8718c78b6b807df77a7ff4b92eb9bf89c1dfd010

**Comment by veprbl** [comment]
cc @jtojnar @dtzWill

**Comment by mmilata** [comment]
One possibility to fix this would be to use `poppler_0_61`: #74951 ... haven't finished compiling but seems to work.

Other possibility is to use bundled version of poppler (0.74): #74952 ... haven't tested this at all.

I don't have fast machine to test this quickly, can someone perhaps ask the bot to build these?

**Comment by veprbl** [comment]
ArchLinux uses this patch https://github.com/LibreOffice/core/commit/2eadd46a.patch
Can you try it?

**Comment by jtojnar** [comment]
I thing the best option is using upstream patch https://gerrit.libreoffice.org/#/c/81545/

**Comment by mmilata** [comment]
Building #74955 now

**Comment by 7c6f434c** [comment]
@tbenst my maintainer handle is simply older than GitHub migration, it is in `maintainer-list.nix`, though
