### ISSUE TITLE
planner: use python3

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#74949]
**Describe the bug**
Expression: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/planner/default.nix

Debian has some downstream patches that switch it to python3 and gobject-introspection.
The patches can be found in the original debian archive
* http://deb.debian.org/debian/pool/main/p/planner/planner_0.14.6-8.debian.tar.xz
* https://packages.debian.org/unstable/source/planner

Here's the descriptions of the main patch.
```
Port to Python 3 / PyGI.
Switch to PyGI as PyGTK supports only Python 2.  OTOH, GTK 2.x does
not fully support introspection so this patch is kinda of a hack.
Hence, not forwarded upstream as it's likely to be rejected.
Author: Yavor Doganov <yavor@gnu.org>
Bug-Debian: https://bugs.debian.org/937299
```

And there's several others that drop uses of deprecated dependencies.

They have no plans to forward a lot of these patches, and they even mention this in the previous patch I mentioned.

cc @rasendubi @amiloradovsky

**Comment by davidak** [comment]
>PyGTK will be phased out with the transition to GTK+ version 3 and be replaced with PyGObject

https://en.wikipedia.org/wiki/PyGTK

Here is an issue of upstream: https://gitlab.gnome.org/GNOME/planner/-/issues/1

So we can just wait for that and continue to use python2 or just remove the package.

**Comment by worldofpeace** [comment]
@davidak I'm thinking it will likely be removed

**Comment by rasendubi** [comment]
Opened #111637 to remove planner
