### ISSUE TITLE
gimp-with-plugins: broken build on master

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#74950]
**Describe the bug**
Using commit d3f928282c0989232e425d26f0302120a8c7218b. See build output [here](https://gist.github.com/24e4a891e3e37db41b296e76493fca17). Gimp builds fine.

@jtojnar

**Comment by jtojnar** [comment]
I knew I was forgetting something. This is likely fallout from https://github.com/NixOS/nixpkgs/commit/b6aded3cd3d445fdfca86ef2c2e90e9da0f08640.

I was partially fixing it in #74301:

https://github.com/NixOS/nixpkgs/blob/537109e9ca24c3752f992b428d638e56320e6a83/pkgs/tools/graphics/gmic-qt/default.nix#L141-L142

but a more proper fix is necessary.
