### ISSUE TITLE
'nix-env -qP' returns numbers instead of package attr names

### ISSUE THREAD

**Issue by robinbb** [NixOS/nixpkgs#7497]
```shell
$ nix-env -qP
8   bash-4.3-p33
17  cabal-install-1.22.0.0
20  cabal2nix-1.73
24  cacert-20140715
9   coreutils-8.23
11  curl-7.40.0
27  darcs-2.8.5
22  dash-0.5.8
...
```

**Comment by edolstra** [comment]
Yeah, this is because we currently don't store attribute names in the generated `manifest.nix` file in user environments. Instead `manifest.nix` is a list of packages, hence the numbers.

**Comment by robinbb** [comment]
@edolstra is there a way that I can obtain the attributes from the names?

**Comment by edolstra** [comment]
No, they're not stored at all.

**Comment by vcunat** [comment]
In general, the information has been lost (isn't stored). Also, it isn't stored from which expressions the package came. And you don't need to know how a package was evaluated  to be able to install it, e.g. ``nix-env -i /nix/store/something`` and that might come just by using ``nix-copy-closure`` on some path...

**Comment by vcunat** [comment]
However, I find it handy to create named package sets for oneself, e.g. alike to what's [described on wiki](https://nixos.org/wiki/Howto_keep_multiple_packages_up_to_date_at_once). There I actually store "shorthands" for attribute paths of some packages I use.
