### ISSUE TITLE
Add pipx

### ISSUE THREAD

**Issue by layday** [NixOS/nixpkgs#74986]
**Project description**

Something of a package manager for Python CLIs available from PyPI - it isolates dependencies so that they don't leak into the surrounding environment or conflict with each other.

**Metadata**

* homepage URL: https://pipxproject.github.io/pipx/
* source URL: https://github.com/pipxproject/pipx
* license: MIT
* platforms: all

**Comment by yevhenshymotiuk** [comment]
Should be closed because of https://github.com/NixOS/nixpkgs/pull/96151

**Comment by layday** [comment]
Closing, thank you.
