### ISSUE TITLE
Update to cpio 2.13 removed `--extract-over-symlinks` option

### ISSUE THREAD

**Issue by zhenyavinogradov** [NixOS/nixpkgs#74984]
In update to cpio 2.13 the patch that added `--extract-over-symlinks` option (fetched from github gist) has been removed: https://github.com/NixOS/nixpkgs/commit/fe758f5fa368ebcdc03419c54412dd9abfd76b35

But this option is used in nixpkgs: https://github.com/NixOS/nixpkgs/blob/b6284fd70f7b4435b58fe7f97532454aa23de327/pkgs/build-support/vm/default.nix#L433 So that derivation fails now

**Comment by veprbl** [comment]
cc @lsix @FRidh

**Comment by lsix** [comment]
As far as I can see, the use of this option should be dropped.

I guess you have a use case that triggers it. Can you confirm that dropping the `--extract-over-symlink` option works as intended (this option was introduced in the patch to disable the action of the patch).

**Comment by lsix** [comment]
and by the way, thanks for reporting the issue !
