### ISSUE TITLE
NixOS manual improvements

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#75003]
It would be nice if someone could rewrite the [abstractions](https://nixos.org/nixos/manual/#sec-module-abstractions) section of the NixOS manual to use something other than `services.httpd` for examples. See https://github.com/NixOS/nixpkgs/pull/73113 for the primary motivation I have on this.

**Comment by flokli** [comment]
As discussed with @aanderse on IRC, the httpd submodule probably isn't a good candidate anymore, as a lot of the boilerplate has been removed.

The abstractions section could however showcase composing multiple declarative nixos containers with similar configuration.

**Comment by aanderse** [comment]
ping @Infinisil in case he has some ideas :heart:

**Comment by Infinisil** [comment]
Hm, I don't actually know of any example where I had to abstract like that in my config. Seems like most NixOS modules already do a pretty good job at being non-repetitive. So idea: How about removing that section, and instead writing a section on abstractions in Nix in general? The abstractions presented there aren't module system specific anyways.

**Comment by aanderse** [comment]
That's a reasonable idea too. Would you imagine that new section to be in the NixOS manual as well, or the Nix manual?

**Comment by Infinisil** [comment]
Probably in the [Nix manual](https://nixos.org/nix/manual/), it would fit nicely inbetween 15.3 and 15.4
