### ISSUE TITLE
Clojure's maven cache .m2 folder is under $HOME/’?’ folder

### ISSUE THREAD

**Issue by leira** [NixOS/nixpkgs#75011]
**Describe the bug**
I use Nix under Debian. I installed clojure through `nix-shell -p clojure`. clj successfully started the repl after downloaded some poms from maven. Then I found there is a folder named ‘?’ created under my $HOME. The maven cache .m2 is under this ‘?’ folder. I tried leiningen, it is the same. I suppose it should be a Java related issue rather than Clojure. But I’m not so familiar with Java to verify it. Is it normal to have .m2 under $HOME/’?’ ?

**To Reproduce**
1. `nix-shell -p clojure`
2. run `clj`

**Expected behavior**
After running clj REPL, a .m2 folder is expected to be created under $HOME

**Screenshots**
![Screenshot from 2019-12-04 18-40-35](https://user-images.githubusercontent.com/39118/70199367-54c8c180-16c6-11ea-9cc7-d3c64a4cf619.png)

**Additional context**
I was running Nix under Debian.

**Comment by marsam** [comment]
> Is it normal to have .m2 under $HOME/’?’ ?

yes, maven uses by default `${user.home}/.m2/repository` to store the local repository. See: https://maven.apache.org/settings.html

**Comment by leira** [comment]
@marsam, you misunderstood the issue. Please check the screenshot. There is a `'?'` folder under $HOME. `.m2` folder is under this `'?'`, the full path to it is `$HOME/\?/.m2`.

Or are you suggesting that `${user.home}` is mapped to `$HOME/\?` for some reason?

**Comment by Ramblurr** [comment]
I cannot reproduce this here in 2024 on NixOS. Maybe this has been resolved in the intervening years?

**Comment by leira** [comment]
This use case is gone. I don't have the environment anymore. Close the issue.
