### ISSUE TITLE
Package mcomix3

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#75028]
**Describe the bug**
There is a fork of mcomix, mcomix3, that's is currently in use by debian because it's ported to gtk3 and python3.

https://github.com/multiSnow/mcomix3/

A big issue though is it lacks a real build system to install
* https://github.com/multiSnow/mcomix3/issues/93

If anyone is up to maintaining this I could contribute https://github.com/multiSnow/mcomix3/issues/96.

cc @fuuzetsu @AndersonTorres.

**Comment by Fuuzetsu** [comment]
I haven't used mcomix for a long time. I just removed myself from all the maintainer lists to not cause further confusion on who to ping for what.

**Comment by ajs124** [comment]
I use mcomix semi-regularly, so I'd definitely appreciate having this fork in nixpkgs. Than again, we do have yacreader, so I guess I'll just switch to that.

**Comment by AndersonTorres** [comment]
Wow! Good to know! I wanna test it!

**Comment by emfox** [comment]
please contribute back to upstream if you finish this, so that all distro packagers benefit.

**Comment by con-f-use** [comment]
I would like to adopt mcomix @worldofpeace, and take you up on your offer to help.
What I got so far is:

```
{ stdenv
, fetchFromGitHub
, python3Packages
# Recommended Dependencies:
, unrar
, p7zip
, lhasa
, mupdf
}:

python3Packages.buildPythonApplication rec {
  pname = "mcomix3";
  version = "1.2.1+gc5afd370";

  # fetch from github because no official release on pypi and no build system
  src = fetchFromGitHub {
    ;repo   = "mcomix3";
    # Use my own for for now because of https://github.com/multiSnow/mcomix3/pull/126
    owner = "con-f-use";
    rev = "3ce83b6c68d85ade4bd4b8c0562abed5f4f8d389";
    sha256 = "0q9xgl60ryf7qmy5vgzgfry4rvw5j9rb4d1ilxmpjmvm7dd3fm2k";
    #owner  = "multiSnow";
    #rev    = "c5afd3707a1861ddf66eae889c425a5354131e70";
    #sha256 = "1bi0rqmy51jrfn0nj7d51b37szmqnh2v3hcg07xy60fy10clqbdi";
  };

  LC_ALL = "en_US.UTF-8";

  format = "other";

  installPhase = ''
    python installer.py --srcdir=mcomix
    mkdir -p $out/bin
    mv target/mcomix/* $out/bin
  '';

  propagatedBuildInputs = (with python3Packages; [ pillow pygobject3 pycairo ])
                          ++ [ unrar p7zip lhasa mupdf ];

  meta = with stdenv.lib; {
    description = "User-friendly, customizable image viewer, specifically designed to handle comic books and manga supporting a variety of container formats (including CBR, CBZ, CB7, CBT, LHA and PDF)";
    homepage = "https://github.com/multiSnow/mcomix3";
    changelog = "https://github.com/multiSnow/mcomix3/blob/gtk3/ChangeLog";
    license = licenses.gpl2;
    maintainers = [ "con-f-use <con-f-use@gmx.net>" ];
    platforms = platforms.all;
  };
}
```

but there seems to be a problem with `PangoCairo` and/or pygobject, that I don't know how to resolve:

```
17:19:14 [MainThread] ERROR: You do not have the required versions of GTK+ 3.0 installed.
Traceback (most recent call last):
  File "/nix/store/1bw11yq732hmc2hlbgw5q7j64m34i10i-mcomix3-1.2.1+gc5afd370/bin/mcomix/run.py", line 116, in run
    require_version('PangoCairo', '1.0')
  File "/nix/store/4rzakn394b7mfm26hjs7j8xs2liyid9c-python3.8-pygobject-3.36.1/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace PangoCairo not available
```

This is with a special debug version, I think the message about GTK+ 3.0 might be a red herring.

**Comment by con-f-use** [comment]
Chute! I forgot to `wrapGAppsHook` it, that was the problem. I think, I have it working now, but need help polishing, seeing this would be my first contribution.

**Comment by AndersonTorres** [comment]
Can you post the code in a gist or in a local Github clone?

**Comment by con-f-use** [comment]
Sure: https://gist.github.com/con-f-use/d7c569c8e3908ffa95e28dd44142f377

**Comment by AndersonTorres** [comment]
I made some comments there.
