### ISSUE TITLE
Hydra package, NixOS service, and NixOS VM test?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#7504]
I was tempted to make a package and/or NixOS service for it but it almost seems so obvious that now I'm wondering why it isn't already in nixpkgs. I know that the hydra repository contains a [NixOS service definition](https://github.com/NixOS/hydra/blob/master/hydra-module.nix) and a [nix build file](https://github.com/NixOS/hydra/blob/master/release.nix) but is there a reason there's no established way to access them from here?

**Comment by domenkozar** [comment]
Just needs to be done :)

**Comment by edolstra** [comment]
The module is in the Hydra repository because that's where it belongs. If we change something to the way Hydra runs, it would be bad to have to update 2 repositories.

**Comment by domenkozar** [comment]
But then it could  be argued the same for every NixOS service module we currently have

**Comment by edolstra** [comment]
If third-party packages came with NixOS modules, we'd definitely want to use those as well :-)

**Comment by domenkozar** [comment]
Right. Could we then have meta-module in NixOS that imports the module from hydra based on git rev?

**Comment by edolstra** [comment]
Another thing to realize is that there is no stable release of Hydra.

**Comment by nmikhailov** [comment]
Yeah, that's strange to not have nix related stuff in nixpkgs

**Comment by copumpkin** [comment]
@edolstra I agree, but nix itself has a package in nixpkgs (somewhat duplicated, unfortunately), right? It just seems like a strange line to draw. We're used to finding all packages/services from everywhere in here and many people don't even know how to import services from elsewhere. To me at least, there'd be value just from the sake of increasing accessibility of hydra. I've been trying to deploy a private one recently and I've seen several other people struggle with the same thing. No stable release just means we could call it `hydraUnstable` if necessary :smile: 

I guess this all ties into the bigger question of "what does the world look like when people start realizing how good nix is and include nix builds in their repos?" I'd imagine it'll be quite different from the way it looks right now, but there's still a big benefit to having the entire world's dependency/metadata structure in one place as opposed to thousands of different repos. That might mean that the metadata/dependency information will always be duplicated, even if the build data might not?

**Comment by Ericson2314** [comment]
+1 putting it in nixpkgs. I think with `hydra.nixpkgs.org` being quite behind, people are linking and getting confused for this more than ever.

**Comment by flosse** [comment]
+1 putting it in nixpkgs

**Comment by Ericson2314** [comment]
Can't we do a dynamic import like https://nixos.org/w/index.php?title=Installing_hydra_as_nixos_module&section=2 ?

**Comment by qknight** [comment]
**please put hydra and the service into nixpkgs**, today our cccamp2015 workshop kind of failed because **hydra is not versioned** and also did not build.

fun fact: we were **using hydra to find the last version which would build** and used that ...

**Comment by zimbatm** [comment]
Hydra is essential to any company deploys and really should as simple as setting `services.hydra.enable = true;` with maybe a list of admins.

**Comment by domenkozar** [comment]
Hydra is so essential to our ecosystem I think it's worth maintaining it twice (ha!). So here we go: https://github.com/NixOS/nixpkgs/commit/3e631800d1ddc93523be4a3a6880a33dc80efb2e

No tests yet, I'll make sure bumps are picked after upstream tests pass. If there's some issues please open a new issue.
