### ISSUE TITLE
networkd not obtaining DHCP

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#7505]
I guess we still have a problem with `networkd`. I had a chance to check out the last change to it, and as it turns out it won't obtain an IP address. The unit itself is running, but that's it. Rolling back to before 56f66dad97758a049f8f05e734cf41d936f7b476 and f8dbe5f376978947067283c6d03087d7948c50de works.

Thanks!

**Comment by auntieNeo** [comment]
Is this the source of the test failures in Hydra? For instance: http://hydra.nixos.org/build/21544979/log#line-1856

**Comment by devhell** [comment]
@auntieNeo I don't think so. From the log you linked it seems that `dhcpcd` is used and successfully acquires a configuration.

**Comment by wkennington** [comment]
Wait dhcpcd is being used in the networkd dhcp test?

**Comment by devhell** [comment]
@wkennington Uh, the log @auntieNeo linked is `vm-test-run-installer-btrfsSubvols`, so I guess not?

**Comment by wkennington** [comment]
Yeah that is using scripted so it's fine. I'll have to look into the dhcp
issue in networkd..

**Comment by devhell** [comment]
@wkennington Thanks, much appreciated!! :-D
