### ISSUE TITLE
dvisvgm upstream version

### ISSUE THREAD

**Issue by matthuszagh** [NixOS/nixpkgs#75070]
I was getting errors with the version of dvisvgm bundled with texlive 2019 so I created a separate, texlive-independent version which works well. (If you're curious about the issue I was seeing it was related to compatibility between ghostscript and dvisvgm. I can be more specific if anyone wants, but reporting that issue is not the main purpose of this).

Here's the build expression I'm using (`texlive-bin` is `pkgs.texlive.bin.core`):
```nix
{ stdenv, fetchFromGitHub, pkgconfig
, autoreconfHook
, texlive-bin
, ghostscript
, brotli
, woff2
, zlib
, freetype
, potrace
, xxHash
}:

stdenv.mkDerivation rec {
  version = "2.8.1";
  pname = "dvisvgm";
  tlType = "bin";

  src = fetchFromGitHub {
    owner = "mgieseki";
    repo = "dvisvgm";
    rev = version;
    sha256 = "0bnqqca15zdvz2rrjnkmnwgrr0d6hxs736ibw26588bpz54mag5i";
  };

  nativeBuildInputs = [ autoreconfHook pkgconfig ];
  propagatedBuildInputs = [
    texlive-bin
    ghostscript
    brotli
    woff2
    zlib
    freetype
    potrace
    xxHash
  ];

  configureFlags = [
    "--with-kpathsea=${texlive-bin}"
  ];

  enableParallelBuilding = true;

  meta = {
    platforms = stdenv.lib.platforms.linux;
  };
}
```

How would people feel about a PR with a dvisvgm package uncoupled from the texlive version in addition to the one currently there? I could name it `dvisvgm-upstream` or `dvisvgm-dev` or something like that. Note that I'm currently using this as a separate build expression but for a PR I'd put it in the texlive bin nix file. Note also that this package can be used identically to any other texlive package. The only difference to the end user is to get an option of a newer version.

**Comment by veprbl** [comment]
What is the issue, though?

**Comment by matthuszagh** [comment]
@veprbl it's been reported [here](https://github.com/mgieseki/dvisvgm/issues/118). The issue is apparently fixed in dvisvgm 2.7.2 (ours is 2.6.3).

Here's an additional MWE to test.

mwe.tex:
```latex
\documentclass{article}
\begin{document}
  mwe
\end{document}
```
`$ pdflatex mwe.tex`
```
$ dvisvgm -P mwe.pdf -n -b min -o mwe.svg

 *** WARNING - you have selected SAFER, indicating you want Ghostscript
               to execute in a safer environment, but at the same time
               have selected DELAYBIND. Unless you use this option with
               care (and specifically, remember to call .bindnow) it is
               possible that malicious code may be able to evade the
               limited security offered by the SAFER option.

 *** WARNING - you have selected SAFER, indicating you want Ghostscript
               to execute in a safer environment, but at the same time
               have selected WRITESYSTEMDICT. Unless you use this option with
               care and specifically, remember to execute code like:
                      "systemdict readonly pop"
           PostScript error: undefined in GS_PDF_ProcSet
Operand stack:
    mwe.pdf
```

**Comment by veprbl** [comment]
So what you say is our dvisvgm is broken because of the incompatible ghostscript version. Then I think we should be fixing dvisvgm for all of our users not just those who opt into using a separate package you propose. I would prefer to just patch the version from texlive, but, unfortunately, https://github.com/mgieseki/dvisvgm/commit/bc51951bc90b700c28ea018993bdb058e5271e9b doesn't apply cleanly, so we would have to craft our own patch or pin `texlive.bin.dvisvgm` to 2.8.1 (in this case, need to leave a TODO comment to remind to unpin for texlive 2020).

**Comment by matthuszagh** [comment]
To clarify, the idea is to generate a patch from a newer texlive version of dvisvgm and apply that to the existing derivation (along with the code comment about this being a temporary fix until 2020)?

**Comment by veprbl** [comment]
@matthuszagh Does #75335 fix the issue for you?
