### ISSUE TITLE
polkit prompt shows multiple users

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#75075]
On 19.09, when you `pkexec` on NixOS with default settings and your user being part of unix group `wheel`, you get a prompt whether you want to get admin capabilities via your user or the `root` user.

This is somewhat inconvenient, because you always have to choose the user by clicking on it (or pressing a number key in the terminal); on other systems like Ubuntu, it somehow figures out that these two are identical and prompts immediately for the password.

In
https://github.com/NixOS/nixpkgs/blob/a7aa5dbb194edff49f045882225b7568737611dd/nixos/modules/security/polkit.nix#L45

we have both `[ "unix-user:0" "unix-group:wheel" ]` as the default.

Setting it to `[ "unix-group:wheel" ]` only generates only 1 prompt.

What is the first one good for, should we just remove it from the default, given that adding users to the `wheel` is the default way of "making them admins"?

Or do we somehow want to depart from the unix group approach of making people admins?

**Comment by worldofpeace** [comment]
These are the patches used in ubuntu and also debian
* https://git.launchpad.net/ubuntu/+source/policykit-1/tree/debian/patches

The default upstream for `addAdminRule` is 
```
polkit.addAdminRule(function(action, subject) {
  return ["unix-group:wheel"];
});
```

So seemingly ubuntu and many other distro's aren't doing what we are doing.

We use
```
polkit.addAdminRule(function(action, subject) {
  return ["unix-user:0", "unix-group:wheel"];
});
```
for probably a specific reason at some point in time.

**Comment by worldofpeace** [comment]
It appears to have been this way for a long time
* https://github.com/NixOS/nixpkgs/commit/7980c71d9c56cc0b922f8bf27c24141657c4b9ca

My recommendation is we just use the default way it is in polkit.
As far as I can tell,  `given that adding users to the wheel is the default way of "making them admins"` is how it's done in NixOS.

**Comment by nh2** [comment]
> These are the patches used in ubuntu and also debian

Right, most notably https://git.launchpad.net/ubuntu/+source/policykit-1/tree/debian/patches/05_revert-admin-identities-unix-group-wheel.patch?id=e82a9d8125f9d70cea47044d2fb4637ff6305725

which does

```diff
-AdminIdentities=unix-group:wheel
+AdminIdentities=unix-user:0
```

saying

> On Red Hat derivatives, every member of group 'wheel' is necessarily privileged. On Debian derivatives, there is no wheel group, and gid 0 (root) is not used in this way. Change the default rule to consider uid 0 to be privileged, instead.

> My recommendation is we just use the default way it is in polkit.

Seems reasonable to me as well
