### ISSUE TITLE
docker-tools test fails to run nix image

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#75081]
**Describe the bug**

The docker-tools test is broken. 

**To Reproduce**

```bash
$ nix-build nixos/tests/docker-tools.nix
# ...
error: command `docker run --rm nix nix-store -qR /nix/store/xiqgdw8s05szign92b7q3mc1yvnkz8gx-nix-2.3.1' did not succeed (exit code 1)
```

The command before (loading the image) worked well but the failing command has no output. With my limited knowledge about docker i was not able to find out, why.

Maintainer information:

`nixos/tests/docker-tools.nix`

/cc @LnL7

**Comment by applePrincess** [comment]
Close this issue since the issue you are referencing is closed and I can not reproduce the problem at commit 9a3b4264c2876e03134b73a06a74068f0bb08b36.
