### ISSUE TITLE
Make buildLocalCabal available in  haskell-ng

### ISSUE THREAD

**Issue by phunehehe** [NixOS/nixpkgs#7512]
My apologies if it's already there and I failed to find it. I use `pkgs.haskellPackages.buildLocalCabal` to build a local package. It has been working fine until now, I want to use `timeit`, which is only available in haskell-ng. Is it possible to add `buildLocalCabal` to `pkgs.haskellngPackages`? Or is there an alternative?

**Comment by peti** [comment]
I've never used `buildLocalCabal` nor am I entire sure of its purpose. What exactly does that function do?

**Comment by phunehehe** [comment]
From what I have seen, `buildLocalCabal` takes a path and a name. It then runs `cabal2nix` on that path, then makes a derivation out of the output, giving it the specified name. It seems to be a nice way to build stuff that I don't intend to put in nixpkgs.

Is there a better way? I'm OK with running `cabal2nix` and storing the output myself, but I'm not OK with having to explicitly pass build dependencies to `callPackage`. Would you do it differently?

**Comment by peti** [comment]
Running `cabal2nix` with the `--shell` argument seems superior, IMHO. The output will be usable with `nix-shell`, and it's trivial to edit so that it works with `nix-build`, too.

**Comment by phunehehe** [comment]
Indeed, I use `cabal2nix --shell` and that works really well for development. However, having to modify a generated file to build (and deploy) your project doesn't sound right.

Also I notice that you didn't mention `cabal2nix` without `--shell`, does that mean it's not intended to work with the new Haskell infrastructure?

**Comment by peti** [comment]
> Indeed, I use cabal2nix --shell and that works really well for development. However, having to modify a generated file to build (and deploy) your project doesn't sound right.

IMHO, editing out the `.env` bit at the end of the generated file is not a particularly big problem. Arguably, it would be nice if `cabal2nix` would have a third mode to generate that kind of output directly. I just never bothered to make the necessary changes.

> Also I notice that you didn't mention cabal2nix without --shell, does that mean it's not intended to 
work with the new Haskell infrastructure?

`cabal2nix` works fine with the new infrastructure.

**Comment by phunehehe** [comment]
Uhm, then what's the intended way to use `cabal2nix` (without `--shell`) output with haskell-ng?

**Comment by peti** [comment]
I'm not sure whether I understand your question. When you run `cabal2nix`, does it not produce valid output? What is the problem you're experiencing?

**Comment by phunehehe** [comment]
I think I confused myself too. I thought that it didn't work while it actually works. Below is the scenario.

Let's say I have a little project with this structure:

 - foo
   - Main.hs
   - foo.cabal

Let's assume that this works, and `cabal build` produces an executable `foo`. Now, to deploy this little project as a service:

 - In the shell: `cabal2nix foo > foo/default.nix`
 - In `/etc/nixos/configuration.nix`:

```
foo = pkgs.haskellngPackages.callPackage /path/to/foo/default.nix {};
systemd.service.foo.execStart = "${foo}/bin/foo"; # or something similar
```

For some reason I was under the impression that the `callPackage` didn't work, that it wanted me to pass all of foo's dependencies instead of an empty set. Apparently I made some other mistake. Everything is fine now. Thanks for staying with me @peti :)

**Comment by peti** [comment]
Ah, okay. I'm glad everything turned out alright! :smile:
