### ISSUE TITLE
Issues with GNOME 3 and Nvidia EGLStream

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#75131]
> As long as the PR was tested on these commits with this config
> * https://discourse.nixos.org/t/need-gnome-3-tester-for-nvidia-eglstream-support/2904/2?u=worldofpeace

Yes.

> I don't think the firefox package in nixpkgs supports wayland yet.

We have a `firefox-wayland` package which is what I tried, but since it’s a thin wrapper around `firefox` it’s possible that it’s still not built with the right options.

Also I’ve noticed these messages from `journalctl --user -b 0 -t gnome-shell`:

```
gnome-shell[2106]: xwayland glamor: GBM backend (default) is not available
gnome-shell[2106]: Missing Wayland requirements for glamor GBM backend
gnome-shell[2106]: glamor: 'wl_eglstream_display' not supported
gnome-shell[2106]: Missing Wayland requirements for glamor EGLStream backend
gnome-shell[2106]: Failed to initialize glamor, falling back to sw
```

`xdpyinfo` does not show the `GLX` extension, and GLX applications fail to start.

_Originally posted by @andersk in https://github.com/NixOS/nixpkgs/pull/70295#issuecomment-558936554_

I probably merged https://github.com/NixOS/nixpkgs/pull/70295, too early.
I'm not totally sure this is working properly.

**Comment by worldofpeace** [comment]
This is pretty much a help wanted because I lack the depth of knowledge and hardware to help anymore with Nvidia things. My goal with finishing https://github.com/NixOS/nixpkgs/pull/70295 was that it could be possible and improved upon. i.e packages are built with the capability etc.

**Comment by baracoder** [comment]
The last few evenings, I have tinkered around a bit. I was not successful so far. Here are my findings:
* I have set the following options:
```
  hardware.nvidia.modesetting.enable = true;
  xserver.displayManager.gdm.nvidiaWayland = true;
  boot.kernelPackages = pkgs.linuxPackages_5_6; #  (5.6.3)
```
* This page says that there is no acceleration support for xwayland and nvidia yet https://wiki.gnome.org/Initiatives/Wayland/NVIDIA but glxgears fails   to start, so I think this is another issue
* There are multiple versions of `libnvidia-egl-wayland.so.1.1.4`: One from the egl-wayland package, the other from nvidia-x11 package. As the one in `/run/opengl-driver` is loaded, I tried to replace it with the one from egl-wayland. Though, the result is the same with both.
* When starting an application, which would use acceleration, I can observe this line in the kernel log:  `broken atomic modeset userspace detected, disabling atomic`
* Using `strace Xwayland :2 -rootless`, I can see that `/dev/dri/card0` is accessed, though one of the calls fails:
```
DRM_IOCTL_SET_VERSION) = EACCES (Permission denied)
```

If you have any suggestions, what to try next, I would be glad to give it a try.

**Comment by jsravn** [comment]
I'm trying to get this working as well. However I can't even get the session chooser in GDM in 20.09. Is it only working in unstable? Any tips?

Here's my config
```
hardware.nvidia.modesetting.enable = true;
services.xserver = {
  enable = true;
  displayManager.gdm = {
    enable = true;
    nvidiaWayland = true;
    autoSuspend = false;
  };
  desktopManager.gnome3.enable = true;
};
```

**Comment by baracoder** [comment]
With this overlay https://github.com/baracoder/nix/blob/master/overlays/egl-wayland.nix and the `nvidia_x11_beta` 470.42.01 driver, nvidia is usable with xwayland. :tada: 
`glxinfo`, unigene-valley and so far every game I started on Steam.
Only issues I have so far are that chrome does not start properly
 Workaround is to start it with some options:
```
google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland
```
and in CSGO there is noticeable input delay.

**Comment by felschr** [comment]
I've updated to the latest nixos-unstable (45fc7d4a35c5) which includes updated `xwayland` & `egl-wayland`, but I'm still facing issues.

While it's generally working I have problems with some apps.
`kitty`:
```
[192 13:26:15.149439] [glfw error 65542]: EGL: Failed to get EGL display: Success
[192 13:26:15.159831] Traceback (most recent call last):
  File "/nix/store/sdr311kij8ipyyg0was3a1mik84vmjl6-kitty-0.21.2/bin/../lib/kitty/kitty/main.py", line 344, in main
    _main()
  File "/nix/store/sdr311kij8ipyyg0was3a1mik84vmjl6-kitty-0.21.2/bin/../lib/kitty/kitty/main.py", line 337, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/nix/store/sdr311kij8ipyyg0was3a1mik84vmjl6-kitty-0.21.2/bin/../lib/kitty/kitty/main.py", line 183, in __call__
    _run_app(opts, args, bad_lines)
  File "/nix/store/sdr311kij8ipyyg0was3a1mik84vmjl6-kitty-0.21.2/bin/../lib/kitty/kitty/main.py", line 156, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow
```
`alacritty`:
```
Created log file at "/run/user/1000/Alacritty-8434.log"
[2021-07-11 13:27:51.630725226] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                        Error creating GL context; Could not create EGL display objec
```
`glxinfo`:
```
name of display: :0
Error: couldn't find RGB GLX visual or fbconfi
```

Additionally in my system logs I can see:
```
Jul 11 13:16:17 felix-nixos gnome-shell[2720]: Failed to initialize glamor, falling back to sw
Jul 11 13:16:17 felix-nixos gnome-shell[2720]: Missing Wayland requirements for glamor EGLStream backend
Jul 11 13:16:17 felix-nixos gnome-shell[2720]: glamor: 'wl_eglstream_display' not supported
Jul 11 13:16:17 felix-nixos gnome-shell[2720]: Missing Wayland requirements for glamor GBM backend
```

`firefox` & `firefox-wayland` are both working.

My relevant config:
```
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta;
  programs.xwayland.enable = true;

  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.displayManager.gdm.nvidiaWayland = true;
  services.xserver.displayManager.gnome.enable = true;
```

I also tried using an overlay to apply the new meson flags from @baracoder's overlay:
```
  xwayland = super.xwayland.overrideAttrs (a: rec {
    mesonFlags = a.mesonFlags ++ [ "-Ddri3=true" "-Dglamor=true" ];
  });
```

Is there anything else I need to set up?

**Comment by felschr** [comment]
`steam` also fails with
```
OpenGL GLX extension not supported by display
OpenGL GLX extension not supported by displaysrc/steamUI/Main.cpp (404) : Assertion Failed: Fatal Error: OpenGL GLX extension not supported by display
src/steamUI/Main.cpp (404) : Assertion Failed: Fatal Error: OpenGL GLX extension not supported by display
```

**Comment by astatide** [comment]
I have a very similar setup as @felschr and am experiencing precisely the same errors.  I'm not sure whether it's an issue with gnome, my particular config, or what.  Things work fine when running in an X session.

**Comment by baracoder** [comment]
:thinking: I don't see anything missing with your config @felschr .

I have updated my config to 45fc7d4 and removed the overlay.
`kitty` and `alacritty` are producing the same errors, and chrome won't function properly unless started with `--enable-features=UseOzonePlatform --ozone-platform=wayland`
`glxinfo` and `glxgears` are working for me, as well as `steam` and `firefox` and `firefox-wayland`.

Note: Seam is installed via `  programs.steam.enable = true;` but this should only be relevant for running games inside steam, not steam itself.

**Comment by jtrees** [comment]
I came here because I'm experiencing the same as @felschr and @astatide. Can't launch Steam or Kitty under Wayland:

- nvidia: 470.42.01
- xwayland: 21.1.2

Config is virtually identical to @felschr.

**Comment by jian-lin** [comment]
I found this issue because I had the same problem as @felschr.

After reading @babariviere's [comment](https://github.com/NixOS/nixpkgs/issues/75131#issuecomment-614621092), I tried to create a different `/etc/egl/egl_external_platform.d/nvidia_wayland.json` file (listed in the end). And that solved my problem. With this file, I can open steam. However, alacritty still has an error. Maybe that relates to another [issue](https://github.com/nvidia/egl-wayland/issues/34).
```
Created log file at "/tmp/Alacritty-4532.log"
[2021-08-24 20:20:17.028947543] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; eglCreateWindowSurface failed
```

The cause of this problem is that even though both `egl-wayland` and `nvidia-x11` packages provide `libnvidia-egl-wayland.so`, `libnvidia-egl-wayland.so` cannot be found without a json file. The [nvidia egl-wayland repo](https://github.com/NVIDIA/egl-wayland/#building-and-installing-the-library) says:
```
Notes:

The NVIDIA EGL driver uses a JSON-based loader to load all EGL External platforms available on the system.

If this library is not installed as part of a NVIDIA driver installation, a JSON configuration file must be manually added in order to make the library work with the NVIDIA driver.

The default EGL External platform JSON configuration directory is:

/usr/share/egl/egl_external_platform.d/
```

So, maybe we should add a json file `/usr/share/egl/egl_external_platform.d
/xxx.json` to the package of `nvidia-x11` and `egl-wayland`. I have tried to use a json file to load `libnvidia-egl-wayland.so` from each of them, and both of them work. The only difference I find is that using `libnvidia-egl-wayland.so` from `egl-wayland` helps gnome setting recognizes my nvidia card, while using `nvidia-x11`, gnome setting says my video card is "Unknown".

In the end, I will post my related config:
```
services.xserver = {
  enable = true;
  videoDrivers = [ "nvidia" ];
  displayManager.gdm = {
    enable = true;
    nvidiaWayland = true;
  };
  desktopManager.gnome.enable = true;
};
programs.xwayland.enable = true;
hardware.nvidia.modesetting.enable = true;
```
/etc/egl/egl_external_platform.d/nvidia_wayland.json
```
{
    "file_format_version" : "1.0.0",
    "ICD" : {
        "library_path" : "/run/opengl-driver/lib/libnvidia-egl-wayland.so"
    }
}
```

**Comment by colemickens** [comment]
I filed this issue to see if we can patch `libEGL_nvidia.so` to look in the right place: https://github.com/NVIDIA/egl-wayland/issues/39

If we can't get it to look in `/run/opengl-driver/share/...` then we should probably just add the etc symlink in the nixos module so that this works correctly for end users out of the box.

I'll send an initial PR shortly and will update it in that egl-wayland issue gets a useful answer (or if there's another way to patch a closed source SO that I'm not thinking of).

**Comment by colemickens** [comment]
BTW, I can confirm the different `egl-wayland` results. When I override nvidia's `egl-wayland` with our "upstream" one, I get more info in `gnome-settings`, but I'm not sure if there are other functional differences. Not sure what I would've expected, but it nags me that there's a difference.

**Comment by colemickens** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/139354

**Comment by colemickens** [comment]
Interesting, there IS a way to override the egl_externaplatform search path(s):

https://github.com/NVIDIA/egl-wayland/issues/39#issuecomment-927288015
