### ISSUE TITLE
versionAtLeast chokes on nix version "2.3pre..."

### ISSUE THREAD

**Issue by nmattia** [NixOS/nixpkgs#75149]
**Describe the bug**
The function `lib.versionAtLeast` does not handle the nix versioning scheme

**To Reproduce**

``` nix
/tmp/tmp.uRTMYxJaOR$ nix repl
Welcome to Nix version 2.3. Type :? for help.
nix-repl> :l <nixpkgs>
Added 10847 variables.
nix-repl> # is my nix version at least 2.2?
nix-repl> lib.versionAtLeast nix.version "2.2"
true
nix-repl> # is my nix vesion at least 2.3?
nix-repl> lib.versionAtLeast nix.version "2.3" 
true
nix-repl> nix.version
"2.3"
nix-repl> nixUnstable.version
"2.3pre6895_84de821"
nix-repl> # is the unstable version at least 2.3?
nix-repl> lib.versionAtLeast nixUnstable.version "2.3"
false
```

**Expected behavior**

`lib.versionAtLeast "2.3pre6895_84de821" "2.3"` should return `true`

**Comment by matthewbauer** [comment]
I think this is expected, with the idea that you should always upgrade from 2.3pre to post 2.3, so it is "before". See:

https://github.com/NixOS/nix/blob/6924bdf2bf8f50f2e6ec5d490571594450aba13a/src/libexpr/names.cc#L73

and

https://github.com/NixOS/nix/blob/6924bdf2bf8f50f2e6ec5d490571594450aba13a/tests/lang/eval-okay-versions.nix#L33

**Comment by nmattia** [comment]
Thanks so much for digging into this! Then it’s either a nix versioning issue, or me assuming that `unstable` means "the not yet stable but soon to be released next version" where in fact it means something completely different.
