### ISSUE TITLE
Request for a new nix package for openmesh: library for polygonal meshes

### ISSUE THREAD

**Issue by mtola** [NixOS/nixpkgs#75158]
Request for a new nix package for openmesh : library for polygonal meshes

https://www.openmesh.org/
https://www.openmesh.org/media/Releases/8.0/OpenMesh-8.0.tar.gz

Thank you.

---

OpenMesh is a generic and efficient data structure for representing and manipulating polygonal meshes. OpenMesh is developed at the Computer Graphics Group, RWTH Aachen. It was funded by the German Ministry for Research and Education ( BMBF).

It was designed with the following goals in mind:

    Flexibility : provide a basis for many different algorithms without the need for adaptation.
    Efficiency : maximize time efficiency while keeping memory usage as low as possible.
    Ease of use : wrap complex internal structure in an easy-to-use interface.

**Comment by prusnak** [comment]
I think it would help if you described why you need the library packaged. Do you plan to include any software that uses the library into the distribution?

**Comment by mtola** [comment]
Yes it will be feasible later. At the moment I would like to develop and launch continuous integration with Nix. I have 7/8 libraries and I need this last one under Nix to start. Note that this library is very stable, recognized in the domain of meshes, simpler than CGAL, small, without dependency... It is also on Mac with HomeBrew for example.

**Comment by MostAwesomeDude** [comment]
I don't want to maintain it, but this derivation will get you up off the ground:

```
{ stdenv, fetchurl, cmake }:
stdenv.mkDerivation rec {
  name = "openmesh-${version}";
  version = "8.0";

  src = fetchurl {
    url = "https://www.openmesh.org/media/Releases/${version}/OpenMesh-${version}.tar.gz";
    sha256 = "10pcaz85044kc8fng7fzr4rgsjr8db4vai8r2xxs7jna4r0d8x49";
  };

  buildInputs = [ cmake ];
}
```

**Comment by mtola** [comment]
Thanks a lot, I will look that maybe after summer and maybe I will propose to be the maintainer of this package, we will see !
Thanks

**Comment by prusnak** [comment]
@mtola Have you tried to package this?

**Comment by mtola** [comment]
No time for the moment... But i will look that when I can...

**Comment by yzx9** [comment]
Modified to fit the URL in version > 10.0:

```nix
{
  lib,
  stdenv,
  fetchurl,
  cmake,
  ...
}:

let
  version = "11.0.0";
  versionParts = builtins.splitVersion version;
  majorVersion = builtins.elemAt versionParts 0;
  minorVersion = builtins.elemAt versionParts 1;
  majorMinorVersion = "${majorVersion}.${minorVersion}";
in
stdenv.mkDerivation rec {
  pname = "openmesh";
  inherit version;

  src = fetchurl {
    url = "https://www.openmesh.org/media/Releases/${majorMinorVersion}/OpenMesh-${version}.tar.gz";
    sha256 = "sha256-x/NdKWc+bbttZbIUwQxMYklSGo8ej4226L3C7teYrtw=";
  };

  buildInputs = [ cmake ];
}
```

Hi @mtola, I saw your comment about the PR. If you have time now, that would be great. If not, I'd be happy to help and create the PR.

**Comment by mtola** [comment]
Hi @yzx9,

No time sorry, so you can do that.

Thanks !
