### ISSUE TITLE
Package Olive

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#7517]
Olive is a technology that streams a VM state on demand to a Linux client. Starting a VM from a server is very fast this way. The code is C and Python.

https://olivearchive.org/software/

**Comment by jgillich** [comment]
@vcunat I think this can be closed since nobody seems interested in packaging it and we don't really need to track things we don't have packages for IMO.

**Comment by vcunat** [comment]
Hmm, yes, this issue doesn't seem particularly useful as it is...
