### ISSUE TITLE
stdenv: Errors in hooks (such as postUnpack) get ignored

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#7524]
It seems that errors in stdenv hooks are being ignored.

For example, if I add this to `pkgs/tools/networking/socat/default.nix`:

```
  postUnpack = '' 
    false
    true
  '';
```

Then when I run `nix-build '<nixpkgs>' -A pkgs.socat`, it will succeed even though it should fail, because a subcommand failed (the `false` subcommand).

I'm not completely sure about the following, but as far as I can see, the problem is that `pkgs/stdenv/generic/setup.sh` has this code:
```bash
 15 runHook() {                                                                                          
 16     local hookName="$1"                                                                              
 17     shift                                                                                            
 18     local var="$hookName"                                                                            
 19     if [[ "$hookName" =~ Hook$ ]]; then var+=s; else var+=Hooks; fi                                  
 20     eval "local -a dummy=(\"\${$var[@]}\")"                                                          
 21     for hook in "_callImplicitHook 0 $hookName" "${dummy[@]}"; do                                    
 22         if ! _eval "$hook" "$@"; then return 1; fi                                                   
 23     done                                                                                             
 24     return 0                                                                                         
 25 }                                                                                                    
```

In line 22, we are evaluating the hook in the context of an `if` condition.

According to [this comment](http://unix.stackexchange.com/a/65564), POSIX specifies that `set -e` gets ignored if we're running inside an `if` condition. And it seems that there is nothing that we can do to get `set -e` to be obeyed when running inside that context, not even starting a subshell...

**Comment by vcunat** [comment]
Actually, I noticed lately that this problem is also in some phases (like ``postInstall`` but I'm unsure which).

Suggestion: in this if-case we can just directly run the hook without any if, right? It seems only to propagate the error, but ``-e`` should do it for us I hope.

**Comment by seppeljordan** [comment]
`runOneHook` seems to be a different story.  It looks like this function is supposed to try out different hooks until it finds one that succeeds.  So it would make more sense to leave the call for the hook inside of the if statement but pass a `-e` option to the subshell the executes the hook.
```
# Run all hooks with the specified name, until one succeeds (returns a                                                                                 
# zero exit code). If none succeed, return a non-zero exit code.                                                                                       
runOneHook() {
  ...
}
```

**Comment by wizeman** [comment]
>  So it would make more sense to leave the call for the hook inside of the if statement but pass a `-e` option to the subshell the executes the hook.

But based on the comment I linked above, I thought that if we're inside the if statement, then the `-e` option will not have any effect, even if run it inside a subshell?

**Comment by seppeljordan** [comment]
Yes you are right, but I meant some construct like this:
```
    for hook in "_callImplicitHook 1 $hookName" "${dummy[@]}"; do
        set +e
        (set -e; _eval "$hook")
        RES=$?
        set -e
        return $RES
    done
```

**Comment by edolstra** [comment]
`runHook` is easy to fix, I'll push a fix soon.

However, the `runOneHook` case is basically unfixable. We can't run the hook in an `if` because that will disable `-e`, and we can't execute it outside of an `if` because that will cause the shell to exit. Executing in a subshell is not really an option because the assumption has always been that hooks run in the same shell (e.g. variables set by a hook should be visible outside). Though maybe we should just specify that certain hooks are executed in subshells.

Bash is a terrible, terrible programming language.

**Comment by wkennington** [comment]
Maybe it's time for a better programming language in the stdenv? There is
always awk which we have :).

**Comment by vcunat** [comment]
The most important part of this is fixed on staging, i.e. failing hooks should fail the build again. Shall we close this?

**Comment by wizeman** [comment]
Fine by me. Thanks!
