### ISSUE TITLE
Add support for meta.licenses

### ISSUE THREAD

**Issue by edwtjo** [NixOS/nixpkgs#7528]
Some packages contains parts which are licensed differently. We should support this in nixpkgs.

**Comment by bjornfor** [comment]
I think meta.license already can be a list (of licenses). I just think we should rename meta.license to meta.licenses. (We already have 's' on meta.platforms and meta.maintainers.)

**Comment by vcunat** [comment]
Some put list of licenses into ``meta.license``. Some people mean what you say by that, and some mean that all files are under multiple licenses (you can choose). It's rather a mess. Currently we don't document what a list in ``meta.license`` mean.
