### ISSUE TITLE
Update `haskellPackages.stack2cabal` from 1.0.3 to 1.0.5

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#75397]
Currently, installing `pkgs.haskellPackages.stack2cabal` from `<unstable>` installs `stack2cabal 1.0.3`. This fails since it is marked as broken due to a broken downstream dependency in `stackage2hackage`. The maintainer of `stack2cabal` has updated the constraints such that it should no longer result in a broken build. Nix should update to version `1.0.5` and remove the `broken` flag. 

I have never updated a Haskell package version. How is this done?

**Comment by matthew-piziak** [comment]
@peti I see you've disabled `stack2cabal`, and you push generated files. Can you teach me how to make the PR?

**Comment by cdepillabout** [comment]
@matthew-piziak Thanks for the bug report here.

In case you just want to get this building on your own machine, I was able to do it like the following:

For 1.0.5:

```console
$ nix-build -E 'with import ./. {}; haskell.lib.doJailbreak (haskellPackages.callHackageDirect {pkg = "stack2cabal"; ver = "1.0.5"; sha256 = "0ba9v6s8jkvl8qhc9ypawvxabb3jzy7rk5q3hfijgbk94zdb7b0d";} { })'
```

For 1.0.4:

```console
$ nix-build -E 'with import ./. {config = {allowBroken = true;};}; haskell.lib.doJailbreak (haskellPackages.stack2cabal.override { })'
```

You'll have to be in a checked-out nixpkgs for the `master` branch.  I used commit 5174b5f66f1.

Let me try to explain a couple things that are going on here.

peti semi-automatically updates the `pkgs/development/haskell-modules/hackage-packages.nix` file with the current state of Hackage every week or so.  He does this live on Twitch if you're interested in following along:

https://www.twitch.tv/peti343

It appears that `master` is currently using `stack2cabal-1.0.4`.

The file `pkgs/development/haskell-modules/configuration-hackage2nix.yaml` has some meta-info about versions of packages to use, as well as which packages should be marked as broken.  You can see in this file that `stack2cabal` is marked as broken.

There is a short video from peti that describes the steps for marking a package as unbroken:

https://discourse.nixos.org/t/video-tutorial-how-to-fix-broken-haskell-packages-in-nix/3968

--------------------------------------------------------------------------

In the case of `stack2cabal`, it appears that there are two problems:

1. `stack2cabal` depends on `hpack >=0.31.0 && <0.32`, but `haskellPackages` currently has hpack-0.33.0.  (I figured this out with the command `nix-instantiate -A haskellPackages.hpack` and looking at the version number of the instantiated derivation.)

    You either need to jailbreak the cabal file for `stack2cabal` to allow for a higher hpack version (as I've done above), OR send a PR to `stack2cabal` bumping the version constraints on hpack, and have the maintainers do a new release.  The Haskell maintainers for nixpkgs would much rather you take this second option, getting the upstream stack2cabal package to relax its version bounds.

    If you send a PR upstream, please comment on this issue.

    If the upstream maintainers are not responsive, then we can add the `doJailbreak` thing here in nixpkgs.

2. `stack2cabal` is currently marked as broken.  After getting a new version released to Hackage with relaxed version bounds, you can send a PR to nixpkgs marking `stack2cabal` as unbroken.  Follow  https://discourse.nixos.org/t/video-tutorial-how-to-fix-broken-haskell-packages-in-nix/3968 for steps on how to do that.

**Comment by cdepillabout** [comment]
`stack2cabal` is now version 1.0.5 and I marked it as unbroken in  #75732.
