### ISSUE TITLE
It's impossible to override expressions that have "meta.broken = true" set.

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#7541]
I have the following in my `~/.nixpkgs/config.nix`:

```
  haskellngPackages_7101 = with self.haskell-ng.lib; self.haskell-ng.packages.ghc7101.override {
    overrides = self: super: {
      ghc-mod = overrideCabal super.ghc-mod (drv: {
        broken = false;
        src = pkgs.fetchFromGitHub {
          owner = "DanielG";
          repo = "ghc-mod";
          rev = "247e4e0e7616fe1fecc68fdcf80d6249ac4cee4f";
          sha256 = "02i6z0navp5a73nk9k46rh01hl5r10s6gzq1c6fmcrdrzjq6nwv4";
        };
        buildDepends = drv.buildDepends ++ [ self.cabal-helper self.cereal ];
      });
    };
  };
```

And yet, despite setting `broken = false;`, I still get the following error:

```
error: Package ‘haskell-ghc-mod-5.2.1.2’ in ‘/home/cstrahan/src/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:51580’ is marked as broken, refusing to evaluate.
For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.
For `nix-env` you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

I'm positive that my overrides are taking place, and that this isn't user error.

**Comment by peti** [comment]
This is a bug in Nix/Nixpkgs: `meta.broken` is too strict. See also https://github.com/NixOS/cabal2nix/issues/130.

**Comment by Mathnerd314** [comment]
I filed #9305 to fix this. Did GitHub notify anybody here?

**Comment by peti** [comment]
The first attempt from https://github.com/NixOS/nixpkgs/pull/9305 had to be reverted (81ce9be).

**Comment by vcunat** [comment]
Fixed by 67e8392383.

**Comment by peti** [comment]
@vcunat, unfortunately, this change had the undesired side-effect of re-enabling the builds of all kinds of broken packages on Hydra, so now I get hundreds of evaluation errors where there used to be none, i.e.: https://hydra.nixos.org/jobset/nixpkgs/haskell-updates#tabs-errors.

How am I supposed to remedy that issue?

**Comment by vcunat** [comment]
I'm a little confused by the fact/statement that there used to be none, but I think we can get rid of all, as there's now a lot of flexibility in handling the errors.

**Comment by peti** [comment]
Note that this is the `haskell-updates` jobset -- not `trunk`. That jobset always had zero evaluation errors until the behavior changed. I suppose I can fix most of them by changing the generator to set `meta.hydraPlatforms = []` at the same time as `meta.broken = true`. This used to be implicit before ...

**Comment by vcunat** [comment]
I noticed but I didn't know you managed to clear all of them in haskell packages.  I'll try to get rid of all (incl. trunk), as I expect that to be relatively easy now, but I can't promise it will be during this weekend already.
