### ISSUE TITLE
CUDA based derivations are not available in cache

### ISSUE THREAD

**Issue by GuillaumeDesforges** [NixOS/nixpkgs#75460]
**Describe the bug**
Installing tensorflow or pytorch with CUDA support enabled makes Nix compile from source every time.

**To Reproduce**
`nix-shell -p "python3.withPackages (ps: [ps.pytorchWithCuda])" `

**Expected behavior**
The package should not do a full recompilation.

**Additional context**
Pytorch and tensorflow take an extremely long time to compile.

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m                                                                         ~
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(arsleust): `"home-manager"`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tbenst** [comment]
Other discussion in https://discourse.nixos.org/t/improving-nixos-data-science-infrastructure-ci-for-mkl-cuda/5074

**Comment by FRidh** [comment]
This type of discussion is best taken on the mailing list (discourse)
