### ISSUE TITLE
Ocaml packages are not individually overridable

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#75485]
I am facing the problem that I want to use Ocaml 4.08, but the `base` package in nixpkgs (1.11.1) is incompatible with 4.08.

I wanted to use a local overlay to bump it to 1.13, but it would not get picked up by other packages, and the reason seems to be that the package set in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/janestreet/default.nix is a simple `rec`, and does _not_ take part in the global fixed-point of nix packages. Shouln’t this file take `base` as a parameter and _not_ be a `rec` set?

Is that intentionally or was it just an oversight? @vbgl?

**Comment by vbgl** [comment]
Oversight. Do not hesitate to contribute improvements! Many thanks.

BTW, recent nixpkgs have `base` for OCaml 4.08 (0.12.2).

**Comment by nomeata** [comment]
Thanks! I am always a bit hazy on the semantics of the various nixpkgs branches. With “recent” you mean `master`, but not yet any tagged “release”, right?

**Comment by nomeata** [comment]
Hmm, todays `master` (2cf477f28da9fa4ac501127c6b7cfbf1c23aa6e1) still has 0.11.1.

**Comment by nomeata** [comment]
> BTW, recent nixpkgs have base for OCaml 4.08 (0.12.2).

Is that on a particular branch maybe?

**Comment by nomeata** [comment]
Oh, now I see pkgs/development/ocaml-modules/janestreet/janePackage_0_12.nix :-)

**Comment by nomeata** [comment]
Seems to be still relevant

**Comment by sternenseemann** [comment]
This is still an issue with the `janeStreet` sub set.
