### ISSUE TITLE
Retroshare not installing  on nixos 20.03

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#75481]
# Retroshare not installing  on nixos 20.03

**Additional context**

... 

g++ -c -pipe -g -fno-omit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -O2 -fPIC -pthread -Wall -W -DRS_ENABLE_GXS -DENABLE_WEBUI -DRS_USE_BITDHT -DPATCHED_LIBUPNP -DPLUGIN_DIR="\"/nix/store/v28vzq18xyyril2mxhzbnh90q20xxd47-retroshare-0.6.2 DESTDIR=/nix/store/v28vzq18xyyril2mxhzbnh90q20xxd47-retroshare-0.6.2/lib/retroshare/extensions6\"" -DDATA_DIR="\"/nix/store/v28vzq18xyyril2mxhzbnh90q20xxd47-retroshare-0.6.2 DESTDIR=/nix/store/v28vzq18xyyril2mxhzbnh90q20xxd47-retroshare-0.6.2/share/RetroShare06\"" -DRS_USE_LIBUPNP -DSQLITE_HAS_CODEC -DGXS_ENABLE_SYNC_MSGS -I. -I. -I../../libbitdht/src -I../../openpgpsdk/src -isystem /nix/store/chfswxy20970mjchq7n7b9j9ir23r18g-openssl-1.1.1d-dev/include -isystem /nix/store/zdfnm7l3cp1gf15hck9khx2iiksgshxd-libupnp-1.8.4-dev/include/upnp -isystem /nix/store/dn2swhhhdzp5rhqva7shqgkwpz255zk7-zlib-1.2.11-dev/include -I/nix/store/m2ir14j3rzrm46iyh0f6v02r4jyfli88-qtbase-5.12.6-dev/mkspecs/linux-g++ -o temp/linux-g++/obj/p3grouter.o grouter/p3grouter.cc
In file included from ./retroshare/rsidentity.h:33,
                 from ./services/p3idservice.h:30,
                 from grouter/p3grouter.cc:190:
./retroshare/rstokenservice.h:65:3: warning: #warning RS_TOKREQ_ANSTYPE_* macros are deprecated! [-Wcpp]
 #warning RS_TOKREQ_ANSTYPE_* macros are deprecated!
   ^~~~~~~
In file included from ./gxs/rsgxsdataaccess.h:30,
                 from ./gxs/rsgenexchange.h:36,
                 from ./services/p3idservice.h:31,
                 from grouter/p3grouter.cc:190:
./gxs/rsgxsrequesttypes.h: In constructor 'GxsRequest::GxsRequest()':
./gxs/rsgxsrequesttypes.h:35:71: warning: 'GxsRequest::ansType' is deprecated [-Wdeprecated-declarations]
  GxsRequest() : token(0), reqTime(0), ansType(0), reqType(0), status(0) {}
                                                                       ^
./gxs/rsgxsrequesttypes.h:41:25: note: declared here
  RS_DEPRECATED uint32_t ansType; /// G10h4ck: This is of no use
                         ^~~~~~~
./gxs/rsgxsrequesttypes.h:35:71: warning: 'GxsRequest::ansType' is deprecated [-Wdeprecated-declarations]
  GxsRequest() : token(0), reqTime(0), ansType(0), reqType(0), status(0) {}
                                                                       ^
./gxs/rsgxsrequesttypes.h:41:25: note: declared here
  RS_DEPRECATED uint32_t ansType; /// G10h4ck: This is of no use
                         ^~~~~~~
In file included from /nix/store/vgn1sxcj5ma9m5bhjps1q9jx3q2ab27c-gcc-8.3.0/include/c++/8.3.0/map:60,
                 from ./serialiser/rsconfigitems.h:29,
                 from grouter/p3grouter.cc:189:
/nix/store/vgn1sxcj5ma9m5bhjps1q9jx3q2ab27c-gcc-8.3.0/include/c++/8.3.0/bits/stl_tree.h: In instantiation of 'class std::_Rb_tree<t_RsGenericIdType<16, false, 1>, t_RsGenericIdType<16, false, 1>, std::_Identity<t_RsGenericIdType<16, false, 1> >, RsGRouterTransactionChunkItem*, std::allocator<t_RsGenericIdType<16, false, 1> > >':
/nix/store/vgn1sxcj5ma9m5bhjps1q9jx3q2ab27c-gcc-8.3.0/include/c++/8.3.0/bits/stl_set.h:133:17:   required from 'class std::set<t_RsGenericIdType<16, false, 1>, RsGRouterTransactionChunkItem*>'
grouter/p3grouter.cc:543:65:   required from here
/nix/store/vgn1sxcj5ma9m5bhjps1q9jx3q2ab27c-gcc-8.3.0/include/c++/8.3.0/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.libretroshare:5655: temp/linux-g++/obj/p3grouter.o] Error 1
make[1]: Leaving directory '/build/source/libretroshare/src'
make: *** [Makefile:104: sub-libretroshare-src-libretroshare-pro-make_first] Error 2
builder for '/nix/store/pm16hvpqk042bp84pagxcvj2g70r5avh-retroshare-0.6.2.drv' failed with exit code 2
cannot build derivation '/nix/store/vgqrd1bil00hglrkxy2jlafj8z9kpxqc-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ja9haqjv0rspalsbj3y1iim23sn1w9wn-xsession.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d60j3460vblkcz1c3y9qcf2b0ah8lkyc-nixos-system-bx26-20.03pre204199.3140fa89c51.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d60j3460vblkcz1c3y9qcf2b0ah8lkyc-nixos-system-bx26-20.03pre204199.3140fa89c51.drv' failed

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by alciono** [comment]
**Here is the  --show-trace  of it when trying to install via nix-env:**
nix-env -iA nixos.retroshare --show-trace 
installing 'retroshare-0.6.2'
error: while evaluating the attribute 'handled' at /nix/store/qj16z9na0qazcarlbz3bjyjzxw06hli7-nixos-20.03pre204199.3140fa89c51/nixos/pkgs/stdenv/generic/check-meta.nix:251:7:
while evaluating 'handleEvalIssue' at /nix/store/qj16z9na0qazcarlbz3bjyjzxw06hli7-nixos-20.03pre204199.3140fa89c51/nixos/pkgs/stdenv/generic/check-meta.nix:147:38, called from /nix/store/qj16z9na0qazcarlbz3bjyjzxw06hli7-nixos-20.03pre204199.3140fa89c51/nixos/pkgs/stdenv/generic/check-meta.nix:252:14:
Package ‘retroshare-0.6.2’ in /nix/store/qj16z9na0qazcarlbz3bjyjzxw06hli7-nixos-20.03pre204199.3140fa89c51/nixos/pkgs/applications/networking/p2p/retroshare/default.nix:52 is marked as broken, refusing to evaluate.

**Comment by mehlon** [comment]
Retroshare is now marked as broken: https://github.com/NixOS/nixpkgs/pull/47350
A pull request is in progress https://github.com/NixOS/nixpkgs/pull/54213

**Comment by mnajib** [comment]
Hi, any progress on this?

**Comment by alciono** [comment]
It looks like **retroshare** has been removed from repository because it is broken.

Hope it will come back...

Closing the issue 21 11 23
