### ISSUE TITLE
systemd-cryptsetup-generator no longer working

### ISSUE THREAD

**Issue by aaron-williamson** [NixOS/nixpkgs#75540]
**Describe the bug**
Since the update (19.09) that moved generators from `systemd.generator-packages` to `systemd.packages`, the `systemd-cryptsetup-generator` no longer properly decrypts drives as specified in `/etc/crypttab` upon boot. Specifically, when running a ZFS setup with encrypted drives (only data drives, root/boot drive is not encrypted) the boot freezes when trying to mount my data drive ZFS pool due to the drives being unavailable. I've confirmed by checking the boot logs that prior to this update, there are `systemd-cryptsetup` logs durning boot but after the update there are no such logs before the system fails to boot.

**To Reproduce**
1. Have a drive (LUKS encrypted) specified in `/etc/crypttab`, for example:
   ```
   dev-mapper-name	/dev/disk/by-id/drive-id-123	/path/to/key
   ```
2. Configure NixOS to use `systemd-cryptsetup-generator` as per the new `systemd.packages` option:
   ```
   systemd.packages = [ pkgs.systemd-cryptsetup-generator ];
   ```
3. Reconfigure the system with `nixos-rebuild switch`
4. Reboot and observe that the drives do not get decrypted or mounted to `/dev/mapper/dev-mapper-name`

**Expected behavior**
When using `systemd.packages = [ pkgs.systemd-cryptsetup-generator ];`, crypttab should be read and the specified drives should be decrypted and available on `/dev/mapper`.

**Additional context**
Example successful boot log excerpt from before update (missing in 19.09):
```
Dec 11 17:20:46 hostname systemd[1]: Starting Cryptography Setup for drive-1...
Dec 11 17:20:46 hostname systemd-cryptsetup[1261]: Key file /path/to/key is world-readable. This is not a good idea!
Dec 11 17:20:46 hostname systemd-cryptsetup[1261]: Set cipher aes, mode xts-plain64, key size 256 bits for device /dev/disk/by-id/drive-id-123.
```

In my failed 19.09 boots, there _is_ mention of `dm_crypt` in the kernel boot logs but no mention of `cryptsetup` whatsoever. It may also be worth mentioning I am generating my `crypttab` file using `environment.etc.crypttab.text`, I am using the `dm_crypt` kernel module, and this setup worked fine in 19.03.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.75, NixOS, 19.09.1549.45ea6092203 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1549.45ea6092203"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: systemd-cryptsetup-generator, systemd, cryptsetup
# a list of nixos modules affected by the problem
module: systemd
```

**Comment by tristanpemble** [comment]
is there any workaround for this?

**Comment by aaron-williamson** [comment]
Some results of further investigation:

`systemd-cryptsetup-generator` appears to be working as intended, with units generated according to the `crypttab` file appearing in `/run/systemd/generator` as they should.

The root of the issue seems to be systemd not finding the generated units, as `systemctl list-units --all | grep cryptsetup` shows the desired units on 19.03 but does not on 19.09. This is despite the files being in the same location (properly generated at boot time) and having the same contents. Worth noting is that the systemd units generated by fstab are also in the generator directory and are being found by systemd.
This is most likely due to systemd not creating the `cryptsetup.target` and `cryptsetup-pre.target` targets as it is compiled without cryptsetup support due to a cyclic dependency between cryptsetup, systemd, and lvm2. It can be fixed with a patch that creates the targets regardless but ideally the cyclic dependency should be sorted out instead. If a maintainer is willing to point me in the right direction I'd be happy to implement either one and open a PR.

@tristanpemble the only workaround I've found is to just use the `boot.initrd.luks.devices.<name?>` or `fileSystems.<name?>.encrypted` options, but neither of these work for my use case. The boot option would work but my key is a file not a device.

**Comment by arianvp** [comment]
cc @flokli

**Comment by flokli** [comment]
Thanks for the highlight! I already had some patches cooking to finally fix cryptsetup generators by default - see https://github.com/NixOS/nixpkgs/pull/66856. I'll try to get back to this this week.

**Comment by flokli** [comment]
@aaron-williamson @rycee I updated #66856. Can you give this a try?

You should be able to test this simply by passing

```
systemd.package = (pkgs.callPackage ../../nixpkgs-customcheckout/pkgs/os-specific/linux/systemd { utillinux = pkgs.utillinuxMinimal; });
```

in your NixOS configuration. There'd no more cryptsetup-specific systemd, but once merged, the default systemd should have all the cryptsetup support and generators enabled.

**Comment by flokli** [comment]
With https://github.com/NixOS/nixpkgs/pull/66856 merged, let's close this. It should trickle into nixos-unstable after the next staging round.
