### ISSUE TITLE
Wordpress: no option to add languages

### ISSUE THREAD

**Issue by LarsBoeckel** [NixOS/nixpkgs#75598]
services.wordpress has no option to add different languages.

A simple option like services.wordpress.<name>.languages similiar to plugins or themes would suffice. 
${concatMapStringsSep "\n" (language: "cp -r ${language} $out/share/wordpress/wp-content/languages/${language.name}") cfg.languages}
in line 37 of the service definition would solve this.

**Comment by aanderse** [comment]
Seems like `wordpress 4` has the user define this in the web interface: https://wordpress.org/support/article/editing-wp-config-php/#language-and-language-directory

For any version below that `extraConfig` could be used: https://wordpress.org/support/article/editing-wp-config-php/#wordpress-v3-9-6-and-below

**Comment by LarsBoeckel** [comment]
If the language does not exist in the folder, it cannot be selected. Nixos seems to only offer en_us by default. Since the wordpress installation is read-only you cannot install languages, plugins, themes or updates via the normal way with ftp.

**Comment by aanderse** [comment]
Ah sorry I misunderstood your original post in this issue. Yes what you are saying makes perfect sense.

Any motivation to write a PR?

**Comment by LarsBoeckel** [comment]
Sorry but i cannot get it to run. I probably have too little knowledge about Nix as a language.

**Comment by aanderse** [comment]
@LarsBoeckel sure no problem. If you make a PR and ping me I can help out. Otherwise do you mind posting what you have and I'll try to get around to it?

Thanks!

**Comment by LarsBoeckel** [comment]
@aanderse i tried to do exactly what i wrote in the first message
${concatMapStringsSep "\n" (language: "cp -r ${language} $out/share/wordpress/wp-content/languages/${language.name}") cfg.languages}
 and the option:
    languages = mkOption {
          type = types.listOf types.path;
          default = [];
          description = ''
            List of path(s) to respective language(s) which are copied from the 'language' directory.
            <note><para>These languages need to be packaged before use, see example.</para></note>
          '';
          example = ''
            # Later
          '';
        };


this does not seem to work. even if i just simply try to add an already existing package like the theme i use, the language folder will not get created.

**Comment by aanderse** [comment]
I'll take a look when I get a chance.

**Comment by aanderse** [comment]
@LarsBoeckel try adding a `mkdir -p $out/share/wordpress/wp-content/languages` in there. That got me one step closer. I was able to have new languages show up in the options (kinda), but selecting them did nothing... Any ideas?

**Comment by Kloenk** [comment]
Stalebot, I would still like this to happen.

**Comment by Kloenk** [comment]
I got this as a somehow working solution, but currently no time to build it into an upstreamable version. Maybe somebody could do that for me, rr I could do it in a month or so.

https://git.kloenk.dev/kloenk/nix/commit/?id=c285ee8b65702e94d2c5511ef285efe5c76d9671

**Comment by Kloenk** [comment]
I think this is still relevant

**Comment by mweinelt** [comment]
Language packs would need to be update in parallel with wordpress itself, so to support languages declaratively we'd need an update script. Fortunately wordpress offers an API where it advertises all supported languages and download locations: https://api.wordpress.org/translations/core/1.0/
