### ISSUE TITLE
Unable to download package nerdfonts

### ISSUE THREAD

**Issue by Th0rgal** [NixOS/nixpkgs#75606]
**Describe the bug**
When I do ``home-manager switch`` it is blocked. 
Image: https://zupimages.net/up/19/50/72tl.jpg

**To Reproduce**
1. Add ``nerdfonts`` to ``home.packages`` in ``home.nix``. Screenshot: https://zupimages.net/up/19/50/ls6k.jpg
2. Save and perform ``home-manager switch``

**Expected behavior**
It will try to download nerdfonts from github but it'll never end.

**Screenshots**
Image: https://zupimages.net/up/19/50/72tl.jpg

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.2, NixOS, 19.09.1549.45ea6092203 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(thomas): `""`
 - channels(root): `"home-manager, nixos-19.09.1549.45ea6092203"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  https://github.com/NixOS/nixpkgs/tree/master/pkgs/data/fonts/nerdfonts
```

**Comment by pbogdan** [comment]
Out of curiosity how long did you wait? The source archive of this package is quite sizeable at ~ 2GB; depending on your connection it could take a good while to complete unless otherwise it downloads quickly outside of a Nix build.

**Comment by Th0rgal** [comment]
> 
> 
> Out of curiosity how long did you wait? The source archive of this package is quite sizeable at ~ 2GB; depending on your connection it could take a good while to complete unless otherwise it downloads quickly outside of a Nix build.

One hour and I got that at the end: https://zupimages.net/up/19/50/go50.jpg

**Comment by mkg20001** [comment]
It means the connection dropped during download and resuming it failed

Simply trying again could fix it

**Comment by Th0rgal** [comment]
> It means the connection dropped during download and resuming it failed
> 
> Simply trying again could fix it

Okay but then why does the percentage never changes? Also is there a way to download only one font? I'ld like to download only fura code.

**Comment by Th0rgal** [comment]
I'm currently downloading the entire tar.gz file using aria2c, how could I tell to nixpkgs to use this file instead of redownloading it?

**Comment by mkg20001** [comment]
`nix-prefetch-url file:///path/to/your/file --unpack` should do it AFAIK

**Comment by Th0rgal** [comment]
> 
> 
> `nix-prefetch-url file:///path/to/your/file --unpack` should do it AFAIK

I think nixos isn't able to recognize that this is the same file: https://zupimages.net/up/19/50/eamz.jpg

**Comment by mkg20001** [comment]
Hrm. Possibly wrong arguments given. Try without `--unpack`. But really, I have no clue

**Comment by Th0rgal** [comment]
> 
> 
> Hrm. Possibly wrong arguments given. Try without `--unpack`. But really, I have no clue

it still tries to download it :/

**Comment by michaelpj** [comment]
It's still quite annoying. They do have release archives for the individual fonts, but that would be a bit more effort to fetch since we couldn't just use `fetchFromGitHub` anymore. It would be nice to be able to just get a single font!

**Comment by evanjs** [comment]
I’ve also encountered issues when trying to fetch nerdfonts (via `nixos-rebuild`)
Download errors seem to occur the most at my workplace where queue trees are enabled. 

My best workaround so far has been to... use another network 😁

Haven’t seen it happen it quite some time, though.

**Comment by rycee** [comment]
The command
```console
$ nix-prefetch-url file:///path/to/your/file --unpack --name source
```
may work, I haven't tried.

**Comment by Th0rgal** [comment]
Fixed in last version.
