### ISSUE TITLE
Cannot use cm-super with TeXLive

### ISSUE THREAD

**Issue by mrkgnao** [NixOS/nixpkgs#75612]
**Describe the bug**

Using the following TeXLive package in my `home-manager` configuration

```nix
  (pkgs.texlive.combine { 
    inherit (pkgs.texlive) 
    scheme-full
    cm-super;
  })
```

causes `cm-super` to not be available during compilation despite the TeXLive package being built/patched/wrapped locally (indicating that a cached package is not being used):

```
$ kpsewhich cm-super.sty

```

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - channels(qq): `"home-manager, nixpkgs-20.03pre197053.d08a7431561"`
 - nixpkgs: `/home/qq/.nix-defexpr/channels/nixpkgs`
```

**Comment by veprbl** [comment]
```
# kpsewhich type1ec.sty
/nix/store/klycxmxqbxm28abf84g60pj9aw1vv6wz-texlive-combined-full-2019/share/texmf/tex/latex/cm-super/type1ec.sty
```

What is the actual problem?

**Comment by mrkgnao** [comment]
well, `\usepackage{cm-super}` doesn't work; i'd like to use Concrete in my document

**Comment by veprbl** [comment]
These are first two google results for "using cm super latex"
https://tex.stackexchange.com/questions/88368/how-do-i-invoke-cm-super/88374
https://tex.stackexchange.com/questions/117122/is-it-possible-to-write-a-cm-super-package
It doesn't seem like `\usepackage{cm-super}` is supposed to work.
