### ISSUE TITLE
Maven does not respect $JAVA_HOME

### ISSUE THREAD

**Issue by michas2** [NixOS/nixpkgs#75630]
**Describe the bug**

Maven has a hard dependency to the `jdk` package, which refers to openjdk8.

The [builder](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/apache-maven/builder.sh#L8) then uses `--set JAVA_HOME "$jdk"` to hardcode that java-Version to the `mvn` command.

It is therefore not even possible to choose a different jdk using something like `JAVA_HOME=... mvn`.

Therefore it seems not possible to build some maven projects that depend on newer features like the `-release` flag of newer jdk versions.

**Expected behavior**

There should be some easy way to specify which jdk to use.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - channels(michas): `"nixos-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
I noticed this also but never got to actually push a fix (its not hard).

**Comment by timokau** [comment]
Will be fixed by https://github.com/NixOS/nixpkgs/pull/80728.
