### ISSUE TITLE
[Package Request] btpd

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#75636]
**Project description**
Btpd is a utility for sharing files over the BitTorrent network protocol. It runs in daemon mode, thus needing no controlling terminal or gui. Instead, the daemon is controlled by btcli, its command line utility, or other programs capable of sending commands and queries on the control socket.

**Metadata**

* homepage URL: https://github.com/btpd/btpd
* source URL: https://github.com/btpd/btpd
* license: https://github.com/btpd/btpd/blob/master/COPYRIGHT
* platforms: linux

**Comment by tadeokondrak** [comment]
#56279

**Comment by MicrosoftTakeover** [comment]
Thanks, I searched the issues but not the pull requests. I'll leave this open until it's merged.

**Comment by veprbl** [comment]
@MicrosoftTakeover Would you mind testing that PR?

**Comment by MicrosoftTakeover** [comment]
I could test the binary but I'm not sure how to test a module yet.

**Comment by abathur** [comment]
Closing this since the posting account has been deleted. (this may still be completed if https://github.com/NixOS/nixpkgs/pull/56279 lands)
