### ISSUE TITLE
unable to extract maintainers

### ISSUE THREAD

**Issue by dirkx** [NixOS/nixpkgs#75662]
**Describe the bug**

I am unable to extract the mainainers of any package.

E.g `nix-env -q -a coreutils --xml --meta`  gives  `<meta name="maintainers" type="strings"></meta>`.  While  [coreutils.meta.maintainers](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/coreutils/default.nix#L144) contains [ maintainers.eelco ]- which seems [valid](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix#L2006).

**To Reproduce**
1. `nix-env -q -a XXX --xml --meta` where XXX is any package name
2. check XXX.meta.maintainer

**Expected behavior**

Both to contain the same values.

**Comment by danbst** [comment]
This must be Nix issue. JSON format works:
```
$ nix-env -q pv --json | jq -r .[].meta.maintainers[].email
jascha@geerds.org
```
