### ISSUE TITLE
Packaging request: Cryptomator

### ISSUE THREAD

**Issue by Fuzen-py** [NixOS/nixpkgs#75684]
**Project description**
Cryptomator is an application providing client-side encryption for cloud storage.

**Metadata**

* homepage URL: https://cryptomator.org/
* source URL:
* license: GPLv3
* platforms: linux, darwin

**Comment by NobbZ** [comment]
Source URL: https://github.com/cryptomator/cryptomator

**Comment by NobbZ** [comment]
This is still relevant to me.

There is currently no way to get transparent encryption on any cloud-drive.

**Comment by ivankovnatsky** [comment]
guys, whoever is interested in cryptomator testing/reviewing are welcome: https://github.com/NixOS/nixpkgs/pull/83434.

**Comment by bachp** [comment]
Let's first get it merged for linux, we can then base on that and check if we can get darwin working too.
