### ISSUE TITLE
texLiveCore fails to install on Mac OS X

### ISSUE THREAD

**Issue by andreasfrom** [NixOS/nixpkgs#7571]
I'm running Nix on OS X as instructed [here](https://nixos.org/wiki/Nix_on_OS_X) with nixpkgs from the master branch.
When trying to install TexLive with the following in `.nixpkgs/config.nix`

    {
      packageOverrides = super: let self = super.pkgs; in {
        myTexLive = with self; texLiveAggregationFun {
          paths = [ texLive ];
        };
      };
    }

it fails to install Web2C with the error [in this gist](https://gist.github.com/andreasfrom/ea6a7deda0a8b6ddbce5).

**Comment by vcunat** [comment]
This old `texLive` infrastructure is deprecated now that we have the `texlive` attribute. It should work on Darwin as well (report if it doesn't; I can't test it myself). Basic user docs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L1
