### ISSUE TITLE
emacsPackages.lua-mode fails to build (again)

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#75714]
**Describe the bug**

Cannot build lua-mode due to hash mismatch. This is similar to #54641 and #71948 but the hash mismatch is different.

Tried with both the latest `unstable` and `19.09` channels with the same result

**To Reproduce**

Build the below (substitue `unstable` or `nixos-19_09` as needed.

```nix
let

  unstable = {
    name = "nixos-unstable-2019-12-05";
    url = https://github.com/nixos/nixpkgs/archive/3140fa89c51233397f496f49014f6b23216667c2.tar.gz;
    sha256 = "1gwp3ss1955rrldml53nbam7gb6dj1ng6k1linh1dw7a5z3yd8p1";
  };

  nixos-19_09 = {
    name = "nixos-19.09-2019-12-05";
    url = https://github.com/nixos/nixpkgs/archive/d85e435b7bded2596d7b201bcd938c94d8a921c1.tar.gz;
    sha256 = "0pqq5dp7k6qzwivpz4g5jxjzfx8cigagyabv86mwzg59af1mlxlg";
  };

in

with import (builtins.fetchTarball nixos-19_09) {};

  pkgs.emacsPackagesNg.emacsWithPackages (
    epkgs: (with epkgs.melpaStablePackages; [
      lua-mode
    ]))

```

`unstable` fails with

> error: hash mismatch in file downloaded from 'https://github.com/nixos/nixpkgs/archive/3140fa89c51233397f496f49014f6b23216667c2.tar.gz':
> wanted: sha256:1gwp3ss1955rrldml53nbam7gb6dj1ng6k1linh1dw7a5z3yd8p1
> got:    sha256:18p0d5lnfvzsyfah02mf6bi249990pfwnylwhqdh8qi70ncrk3f8

`nixos-19_09` fails with

> error: hash mismatch in file downloaded from 'https://github.com/nixos/nixpkgs/archive/d85e435b7bded2596d7b201bcd938c94d8a921c1.tar.gz':
>   wanted: sha256:0pqq5dp7k6qzwivpz4g5jxjzfx8cigagyabv86mwzg59af1mlxlg
>   got:    sha256:1msjm4kx1z73v444i1iybvmc7z0kfkbn9nzr21rn5yc4ql1jwf99

**Expected behavior**
The package builds with no errors.

**Screenshots**
N/A

**Additional context**
N/A

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80-hardened, NixOS, 19.03.173672.5f7eae4bbb1 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.03.173672.5f7eae4bbb1"`
 - channels(user): `"nixos-latest-19.03.173670.3ead845da92, unstable-20.03pre203904.bb1013511e1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- emacsPackagesNg.melpaStablePackages.lua-mode
# a list of nixos modules affected by the problem
module:
```

**Comment by stefano-m** [comment]
My bad :bowing_man: , it seems I did something wrong. Closing this for now.

**Comment by endgame** [comment]
Can you elaborate on the wrong that you did? I'm having trouble building `lua-mode` again.

**Comment by stefano-m** [comment]
@endgame I messed up with the hashes and that's why I had the failure in the code I posted.

Apparently I can build the package OK with the code posted in this issue (minus the wrong hashes) but it fails when I build it for my emacs environment (`emacsWithPackages` etc...), since at the moment I have the old nixos stable and the latest channels, there might be something wrong with my setup, but I haven't had time to look into that yet.

**Comment by stefano-m** [comment]
Updated https://github.com/NixOS/nixpkgs/issues/71948#issuecomment-572505840 rather than reopening this one.
