### ISSUE TITLE
Enable tests for wxPython40

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#75759]
See https://github.com/NixOS/nixpkgs/pull/64047 , we wanted to get it merged so we can build on it, so we ended up disabling tests for now as everything seemed to work ok.

We should get tests enabled.

**Comment by tbenst** [comment]
@deliciouslytyped re: https://github.com/NixOS/nixpkgs/pull/64047#pullrequestreview-267514631, were you just building with doCheck= false; and then nix-shell to run tests?

**Comment by deliciouslytyped** [comment]
I don't remember a lot of details, probably look at the thread from this point https://github.com/NixOS/nixpkgs/pull/64047#issuecomment-516100572

I was building without `doCheck = false` and I think the problem was some tests were hanging due to reasons described in the thread (?, or possibly not). I asked upstream about it in https://github.com/wxWidgets/Phoenix/issues/1316 .
I think the next step would be to enable all tests, and disable the failing tests.

After that we can start figuring out how to fix the failing tests.

**Comment by deliciouslytyped** [comment]
Consider this a "remaining TODO" for wxPython4 thread.
cc @veprbl @lopsided98 @jonafato if you remember anything that would be good to look at from https://github.com/NixOS/nixpkgs/pull/64047.

**Comment by jonafato** [comment]
@deliciouslytyped I think you meant to mention @jonringer instead of me here, correct?

**Comment by deliciouslytyped** [comment]
Yes sorry!

**Comment by deliciouslytyped** [comment]
I think the tests that hang might have something to do with running in these various unattended environments like a backgrounded x session or Xephyr.

There's is also an error about g-settings missing, so there should be some kind of propagated build input for that? Or should we be getting that from gtk3 already?

**Comment by deliciouslytyped** [comment]
Tests:
- filectrl_Tests.test_filectrl4 and filectrl_Tests.test_filectrl5 are heisenbuggy.
- ...

[log.txt](https://github.com/NixOS/nixpkgs/files/4405843/log.txt)

**Comment by deliciouslytyped** [comment]
Some tests appear to fail nondeterministically.

**Comment by deliciouslytyped** [comment]
Funnily enough there is a large if not complete correspondence between the failing tests and what upstream disables, I just hadn't bothered to check;
https://github.com/swt2c/Phoenix/blob/baa0110158819fde7bd453aaeb90ff896f7fdd2c/.circleci/config.yml#L62

**Comment by FliegendeWurst** [comment]
For 4.2, tests were enabled in #190587
