### ISSUE TITLE
Can't install xonsh modules

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#75786]
## Issue description

To install extensions in the [xonsh](https://xon.sh/) shell, according to [the documentation](https://xon.sh/tutorial_xontrib.html), you run `xontrib z`, where `z` is the name of the extension you want to install. Running that gives: 

```
The following xontribs are enabled but not installed: 
   z
To install them run 
    xpip install xontrib-z

```

However, running `xpip` fails on NixOS with: 

`/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/bin/python3.7: No module named pip
`

It'd be great if this command worked as expected. But even better, it'd be great to have the Xontribs (xonsh extensions) installable via nix, too, somehow. You can list them with `pip search xontrib`, so they're just python modules. Someone with more nix-fu than I could probably make an option `programs.xonsh.plugins` that could install those python modules, such that `programs.xonsh.plugins = [ z simplejump shedule ];` would install the python modules `xontrib-schedule`, `xontrib-simplejump`, and `xontrib-z`. 

### Steps to reproduce

1. Install `xonsh`
2. Run `xpip`, either with or without arguments. 
3. Notice that it fails, and you can't install a xonsh extension. 

## Technical details

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.14, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(jon): `"home-manager, nixpkgs-20.03pre203529.e8f2764fe8d"`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

**Comment by KoviRobi** [comment]
For the xontrib in nix, looks like the modules just need to be on the PYTHONPATH, so perhaps we just need to wrap xonsh like we wrap python [default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/default.nix) [wrapper.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/wrapper.nix) [with-packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/with-packages.nix). Perhaps we could even just use the python wrapper.nix.

I might have a play around with xonsh, and then if you haven't already, try to package stuff for it. Until then, you could try installing xontrib-z into some path, then putting that into your PYTHONPATH?

**Comment by JonathanReeve** [comment]
This is still relevant, as far I I know.

**Comment by shadowrylander** [comment]
I actually use this mach-nix overlay: https://github.com/shadowrylander/shadowrylander/blob/system/etc/nixos/shared/global/_overlays/xonsh.nix

**Comment by tex** [comment]
Does anyone successfully solved this? @shadowrylander link is no longer available...

**Comment by shadowrylander** [comment]
@tex I believe I'm still using the overlay [in this issue](https://github.com/DavHau/mach-nix/issues/172#issue-737384163)! Though there still seems to be done problems.

**Comment by danilevy1212** [comment]
I can confirm than adding package to your `$PYTHONPATH` does work. Also from inside the xonsh shell, adding my local `pip` site-packages directory to `sys.path` does work, which is not ideal. It would be nice to be able to have some sort of wrapper to add xcontrib modules more easily without clashing with NixOS philosophy.

**Comment by Lassulus** [comment]
so I'm currently using xonsh like this in my configuration:
```
{ config, lib, pkgs, ... }: let

  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.3.0";
  }) {
    pkgs = pkgs;
  };

  pyenv = mach-nix.mkPython {
    requirements = ''
      xontrib-sh
      xxh-xxh
    '';
  };

  xonshrc = pkgs.writeText "xonshrc" ''
    $PROMPT = '{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{NO_COLOR}> '
    $XONSH_COLOR_STYLE = 'rrt'
    xontrib load sh
  '';

  xonsh_with_plugins = pkgs.xonsh.overrideAttrs (old: {
    propagatedBuildInputs = old.propagatedBuildInputs ++ pyenv.python.pkgs.selectPkgs pyenv.python.pkgs;
  });


in {
  environment.variables.XONSHRC = builtins.toString xonshrc;
  environment.systemPackages = [
    xonsh_with_plugins
  ];
}
```

**Comment by airways** [comment]
This is still happening to me.

@Lassulus where does this config go for your workaround? I tried to put it into ~/.xonshrc and that resulted in syntax errors so that might not be the right place?

**Comment by Lassulus** [comment]
uhm, I posted a nixos config. I would guess you are not on nixos since you are using apt-get?

**Comment by airways** [comment]
Oh yes indeed, very sorry about that. I didn't realize what repo I was in, and this issue was highly ranked when I searched Google for this error.

**Comment by charmoniumQ** [comment]
I was trying to do this without mach-nix, but I couldn't figure it out?

```
{ pkgs, config, ... }:
let
  python = pkgs.python311;
  pythonPkgs = with python.pkgs; [
    (python.pkgs.toPythonModule pkgs.xonsh)
    (python.pkgs.buildPythonPackage rec {
      pname = "xontrib-prompt-starship";
      version = "0.3.4";
      src = pkgs.fetchPypi {
        inherit pname version;
        sha256 = "2106d4e13618891f12657bd44f32ffba48cdeca18239031369de1a6fa4ff152b";
      };
      doCheck = false;
    })
  ];
in {
  home = {
    packages = [ (python.withPackages (ps: pythonPkgs)) ];
  };
}
```

But no dice,

```
@ home-manager switch
...
@ xontrib load starship_prompt
The following xontribs are enabled but not installed: 
   ['starship_prompt']
Please make sure that they are installed correctly by checking https://xonsh.github.io/awesome-xontribs/
```

**Comment by SamLukeYes** [comment]
There's a way to install xonsh modules introduced by https://github.com/NixOS/nixpkgs/pull/240246. I think this issue can be closed.
