### ISSUE TITLE
Sway not listed in SDDM sessions

### ISSUE THREAD

**Issue by thibran** [NixOS/nixpkgs#75793]
**Describe the bug**
After installing Sway and SDDM on NixOS stable and rebooting, SDDM starts but has no Sway entry.

nixos/modules/programs/sway.nix

**To Reproduce**
```
services.xserver.enable = true;
services.xserver.displayManager.sddm.enable = true;
programs.sway.enable = true;
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.3, NixOS, 19.09.1590.d85e435b7bd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1590.d85e435b7bd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matthewbauer** [comment]
I think this PR might resolve this:

https://github.com/NixOS/nixpkgs/pull/56988

**Comment by hedning** [comment]
#75363 recently added display manager support for sway, but that's currently not in 19.09.

**Comment by jonringer** [comment]
I feel like it might be time to add another option to nixos:

```
services.wayland = {
   ...
};
```

**Comment by worldofpeace** [comment]
This is an issue fixed on master so we can close this.
