### ISSUE TITLE
virtualbox: fails to start VMs, "Kernel driver not accessible"

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#75808]
**Describe the bug**

VirtualBox fails to start any VMs on my systems. I am on kernel 4.19.89, my user is a member of the "vboxusers" group, I deleted the dotfiles `.VirtualBox` and `VirtualBox VMs`.
VirttualBox was enabled using `virtualisation.virtualbox.host.enable = true;` in the configuration.nix and the kernel modules `vboxdrv, vboxnetadp, vboxnetflt` are loaded.

The VirtualBox Qt gui gives the error message "Kernel driver not accessible" and trying to start the same VM via VBoxManage results in

```
$ VBoxManage startvm "09267417-c6b7-4efc-adea-f18bc20341bc" --type headless
Waiting for VM "09267417-c6b7-4efc-adea-f18bc20341bc" to power on...
VBoxManage: error: The virtual machine 'sailfishx-patcher-f5321_sailfish_image_patcher_1576542468708_53472' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

**To Reproduce**
1. Adapt your system configuration according to this:
```
virtualisation.virtualbox.host.enable = true;
users.extraGroups.vboxusers.members = [ "user-with-access-to-virtualbox" ];
```
2. Try starting an existing VM or create a new one in `VirtualBox`

**Expected behavior**
The VirtualBox VM is expected to start.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 19.09.1590.d85e435b7bd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"home-manager-19.09, nixos-19.09.1590.d85e435b7bd, nixos-unstable-20.03pre204199.3140fa89c51"`
 - channels(user): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.virtualbox
# a list of nixos modules affected by the problem
module: virtualisation/virtualbox-host
```

**Comment by schmittlauch** [comment]
notifying maintainer @svanderburg

**Comment by schmittlauch** [comment]
Turns out this is an instance of NixOS/nixops#370.
Removing virtualbox from my user environment resolved it.

I wonder whether some kind of detection feature should be implemented to avoid this.

**Comment by iterprise** [comment]
I have the same problem. If i run Vbox not on root user I got "Kernel driver not accessible"

I don't have virtualbox in my user environment but i still have got this problem. 
type VirtualBox
VirtualBox /run/current-system/sw/bin/VirtualBox

groups 
users wheel networkmanager libvirtd vboxusers kvm

id
uid=1000(user) gid=100(users) группы=100(users),1(wheel),57(networkmanager),67(libvirtd),72(vboxusers),302(kvm)

ls -l /dev/vbox*
crw-rw---- 1 root vboxusers 10, 58 дек 20 19:59 /dev/vboxdrv
crw-rw-rw- 1 root root      10, 57 дек 20 19:59 /dev/vboxdrvu
crw-rw---- 1 root vboxusers 10, 56 дек 20 19:59 /dev/vboxnetctl

/dev/vboxusb:
итого 0
drwxr-x--- 2 root vboxusers 100 дек 20 19:59 002
drwxr-x--- 2 root vboxusers  60 дек 20 19:59 003
