### ISSUE TITLE
MASS_7.3-39 has wrong output hash

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#7581]
`nix-env --upgrade` fails.

```
output path ‘/nix/store/ikvh54f77i53jjpxsm3bspcc0839cbqp-MASS_7.3-39.tar.gz’ should have sha256 hash ‘08h94j5zcf8sgg2bynnhq2wcysw3rvzdw4hcp1il3y38i6d31zgm’, instead has ‘102rw6gw1mrbr00s8b1bnz2yh2nqk411qdhs6kncs6scalixjb5p’
building path(s) ‘/nix/store/1fr6vhibj3b896gmndj8b8a5vqxdpdl8-linux-4.0-rc2.tar.xz’
cannot build derivation ‘/nix/store/6h98vj5pa6yhs8k0wl2hwsqhs28rb1vi-r-MASS-7.3-39.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/x4ngv46inwwdgcdbkxvk0maqm8z050hm-rpart_4.1-9.tar.gz’
building path(s) ‘/nix/store/ra78h8ckrq3ddwqvyap9q7qfqrs38kfz-spatial_7.3-9.tar.gz’
building path(s) ‘/nix/store/5y2xxd64m8nkf8gdbfny2w5bl6xl0p6y-survival_2.38-1.tar.gz’
cannot build derivation ‘/nix/store/8mn3qhkfgskyrl7cq5hdc5jahcb2iw13-R-3.1.3-wrapper.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/8mn3qhkfgskyrl7cq5hdc5jahcb2iw13-R-3.1.3-wrapper.drv’ failed
```

**Comment by wmertens** [comment]
This is a CRAN package. @peti ?

**Comment by peti** [comment]
Yeah, sometimes those packages are updated in-place on the server. It happens rarely, but it does happen. :-( I'll commit a fix in a minute.

**Comment by peti** [comment]
Um, wait a minute ... on which branch are you working @wwat? I reckon it's not `nixos-unstable`, because the current `master` branch doesn't have `MASS` version 7.3-39 any more; we've updated to 7.3-40 a while ago.

**Comment by peti** [comment]
Fixed in `release-14.12` by https://github.com/NixOS/nixpkgs/commit/f86a148dad88c50aca3ffa3d097cc14dca89dd2d.

**Comment by wwat** [comment]
@peti It seems like it is a smarter idea to educate those people as to how to do a release (i.e. send them an e-mail). I.e., that a release has the property that it never changes. Otherwise, there should be a nightly process which checks these properties and patches nixpkgs automatically.

**Comment by wwat** [comment]
@peti This is the same issue:
‘/nix/store/z2sb0dh7f0s2hdaws5nmv8n042y1vnda-lattice_0.20-30.tar.gz’ should have sha256 hash ‘10985l95p7mx403kz3pc8j5iqfsb1zz7w6hsw53xwd436ykf132j’, instead has ‘102rw6gw1mrbr00s8b1bnz2yh2nqk411qdhs6kncs6scalixjb5p’

Are you already feeling like sending that e-mail to the R people? ;)

**Comment by peti** [comment]
> Are you already feeling like sending that e-mail to the R people? ;)

Actually, I'd prefer if you'd contact them to sort out this issue. I have too many other things to worry about at the moment.
