### ISSUE TITLE
Franz has incorrect executable in franz.desktop

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixpkgs#75819]
**Describe the bug**
Franz `franz.desktop` is pointing to an incorrect executable so launching it doesn't work.

**To Reproduce**
1. Install franz
2. Run franz via the `franz.desktop` file
3. Get an error saying `Could not find the program '/opt/Franz/franz'`

**Expected behavior**
Franz launches as expected

**Additional context**
According to https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/instant-messengers/franz/default.nix#L37-L38 the nix package is designed to replace the `/opt/Franz/franz` which just `franz` however in the latest version of Franz it doesn't seem to be working

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.3, NixOS, 20.03pre205624.8636580d6f4 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre205624.8636580d6f4, nixpkgs-unstable-20.03pre204216.cc6cf0a96a6"`
 - channels(mdedetrich): `"nixpkgs-20.03pre204216.cc6cf0a96a6"`
 - nixpkgs: `/home/mdedetrich/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: franz
```

**Comment by veprbl** [comment]
cc @davidtwco
