### ISSUE TITLE
Blender's GPU support

### ISSUE THREAD

**Issue by manpages** [NixOS/nixpkgs#7582]
On Arch Linux I didn't have problems with this GPU

```
λ lspci | grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 680] (rev a1)
```

rendering with this script

```
import bpy
bpy.context.scene.render.engine = 'CYCLES'
bpy.data.scenes['Scene'].cycles.samples=5000
bpy.context.scene.cycles.device = 'GPU'
```

calling it like this

```
time blender \
  -b "$1" \
  -o "/tmp/${1}$(date --iso-8601=seconds)" \
  -F JPEG \
  -P ~/bin/blender/gpurender.py \
  -x 1 -f 1
```

on NixOS, however, I can't get it to work neither with overriding cudaSupport to true, nor with hardcoding cuda toolkit and cudaSupport into blender expression.

I'd love to contribute to fixing this issue, but don't know how to proceed. Can somebody at least report that they can render a blender project on a GPU and provide an expression that makes it possible?

**Comment by codyopel** [comment]
Are you getting any specific errors or are you simply not able to get cuda support enabled.  I am not quite sure what is happening from your description.

If you are overriding it via `configuration.nix` you can use something like:
```nix
{ config, pkgs, ... }:
{
  nixpkgs.config.packageOverrides = self: with pkgs; rec {
    blender = self.blender.override {
      cudaSupport = true;
    };
  };
}
```

**Comment by robberer** [comment]
@manpages 

I have to start blender as user root one time to get access to the GPU.

1. start blender as user root
2. close blender
3. start blender as regular user

Note: You also have to load the nvidia_uvm kernel module.

**Comment by edolstra** [comment]
I use GPU rendering with blender.

Starting blender as root should not be necessary since a4e0278fcd8c6bd98b4e003fa273c4cd63d7b383.

**Comment by edolstra** [comment]
BTW, your script might need
```
bpy.context.user_preferences.system.compute_device = 'CUDA_0'
bpy.context.user_preferences.system.compute_device_type = 'CUDA'
bpy.context.scene.cycles.device = 'GPU'
```

**Comment by manpages** [comment]
Overwhelming response, thank you people.
Re: a4e0278 — I use nixos-unstable-small channel and the system is very fresh.
I will try suggestions and post findings in this issue.

@codyopel yeah, I have tried this, and tried hardcoding cudaSupport into the expression as well, it doesn't use GPU either way. Thanks for your suggestion though ;)

**Comment by manpages** [comment]
Tried Dr. Dolstra's suggestion; it didn't really work, however, if for somebody GPU rendering reportedly works, I think we should close this issue and I'll do a write-up about debugging blender GPU rendering with NixOS and reference it later on in here.

**Comment by manpages** [comment]
Fixed by installing x11vnc, connecting via vnc and tweaking default user settings in Blender. :(

**Comment by AdsonCicilioti** [comment]
Today, in 2021, I can't use Blender on NixOs with GPU / Cuda support.

NVIDIA drivers installed correctly, cudatoolkit too. Kernel modules (nvidia, nvidia_uvm, etc).

In Arch, this is all it takes to Work with cuda.
