### ISSUE TITLE
pygtk: cannot import gtk

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#75820]
**Describe the bug**
Python2 cannot "import gtk", although pygtk is installed.

It looks like the Python-GTK+2-modules are missing in pygtk.

Maybe this is like  #6607.

**To Reproduce**

```
$ nix-shell -p python2 -p gtk2 -p python27Packages.pygtk 
$ python2
>>> import  pygtk
>>> pygtk.require("2.0")
>>> import gtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gtk
```

**Metadata**
 - system: `"x86_64-linux"`
 - channels(root): `"nixos-19.09.1529.808d3c6d123"`

**Comment by matthewbauer** [comment]
I'm not sure why, but it looks like python2.withPackages works here:

```
$ nix-shell -p '(python2.withPackages (pkg: [ pkg.pygtk ]))' --run python2
```

**Comment by worldofpeace** [comment]
@matthewbauer I believe @FRidh has mentioned many times, what's in the OP is incorrect. People should use `withPackages` for this.

**Comment by matthewbauer** [comment]
It would be nice for `-p` to stack correctly in Nixpkgs, but I think @FRidh had some good reasons why we can't just use a setup hook here.
