### ISSUE TITLE
Log Directory Substitution Not Complete

### ISSUE THREAD

**Issue by polynomial** [NixOS/nixpkgs#7584]
I get this error when trying to use the kafka scripts from the package:
  $ /nix/store/12ndbm9by7ccsb77lsx4kc9566pk4y6l-apache-kafka-2.10-0.8.2.1/bin/kafka-server-start.sh /nix/store/yh8hdd378j1gaaq73gk88ca7gzf590vg-apache-kafka-2.10-0.8.2.1/config/server.properties
  mkdir: cannot create directory ‘/nix/store/12ndbm9by7ccsb77lsx4kc9566pk4y6l-apache-kafka-2.10-0.8.2.1/bin/../logs’: Read-only file system
  log4j:ERROR setFile(null,true) call failed.
  java.io.FileNotFoundException: /nix/store/12ndbm9by7ccsb77lsx4kc9566pk4y6l-apache-kafka-2.10-0.8.2.1/bin/../logs/kafka-request.log (No such file or directory)
  at java.io.FileOutputStream.open(Native Method)

**Comment by joachifm** [comment]
Looks like this was fixed in the referenced commit?

**Comment by kevincox** [comment]
This should probably be closed since it appears to be fixed and @polynomial isn't responding.

**Comment by joachifm** [comment]
Agreed
