### ISSUE TITLE
Package pixelfed

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#75858]
"A free and ethical photo sharing platform." Pixelfed uses federation, which makes it interesting in a ecosystem around ActivityPub platforms like Mastodon.

**Metadata**

* homepage URL: https://pixelfed.org/
* source URL: https://github.com/pixelfed/pixelfed
* license: GNU Affero General Public License v3.0
* platforms: (not sure) Unix

**Comment by matthiasbeyer** [comment]
still important to me

**Comment by lambdadog** [comment]
I'd definitely like to see this.

Willing to start investigating into doing so.

**Comment by GregTheHun** [comment]
I'd love to have this package, along with diaspora*: https://github.com/NixOS/nixpkgs/issues/127665

**Comment by flexagoon** [comment]
@matthiasbeyer As far as I can see, Pixelfed does not have an official desktop app.

**Comment by davidak** [comment]
@flexagoon this is not about a desktop app, but a web service.

@GregTheHun Diaspora* is pretty dead nowadays and is not connected to other decentralized social media platforms that use activity pub. check out mastodon if you want to interact with people! people there are talking about nixos https://chaos.social/tags/NixOS

**Comment by ejpcmac** [comment]
Still important to me.

**Comment by elikoga** [comment]
Looking at doing this

Seems like it's a usual PHP App: https://docs.pixelfed.org/running-pixelfed/prerequisites.html

**Comment by elikoga** [comment]
I'm struggling a bit with getting composer2nix to work so I think this won't get done anytime soon

**Comment by bezmuth** [comment]
Hey folks I worked on this for summer of nix 2022, I'm not super familiar with web hosting and php so there might be some issues in my pull, any feedback would be appreciated.

**Comment by abathur** [comment]
Looks like this was recently added in https://github.com/NixOS/nixpkgs/pull/207194
