### ISSUE TITLE
tree-sitter out of date

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#75863]
**Describe the bug**
 tree-sitter on nixos-unstable doesn't build.
So I tried bumping the package but ended up with another issue:

```
---- tests::highlight_test::test_highlighting_ejs stdout ----
thread 'tests::highlight_test::test_highlighting_ejs' panicked at 'called `Result::unwrap()` on an `Err` value: Error(["/build/source/target/scratch/html.so: invalid ELF header", "Error opening dynamic library \"/build/source/target/scratch/html.so\""])', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```
May need a patchelf ?

**To Reproduce**
nix build tree-sitter -f channel:nixos-unstable

**Expected behavior**

**Metadata**
```
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 20.03.git.2bb799f (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(teto): `"nixos-18.09.tar.gz-18.09"`
 - channels(root): `""`
 - nixpkgs: `/home/teto/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tree-sitter
# a list of nixos modules affected by the problem
module:
```
CC @Profpatsch as per  https://github.com/NixOS/nixpkgs/pull/66758

**Comment by teto** [comment]
hum I forgot to change the sha... trying to bump it right now

**Comment by teto** [comment]
My current progress https://github.com/teto/nixpkgs/tree/treesitter. I am on a slow laptop right now so I don't think I will make much progress in case anyone wants to have a look at it.

**Comment by Profpatsch** [comment]
Builds just fine on master.

**Comment by Profpatsch** [comment]
Is even cached on cache.nixos.org as far as I can see.

**Comment by Profpatsch** [comment]
This is fairly low-prio for me, but feel free to try updating it.

**Comment by bhipple** [comment]
> Builds just fine on master.

It appears to have race conditions in the test suite, but will eventually build.  Hydra has failed a few times, but is currently succeeding:
https://hydra.nixos.org/build/111630249

For me it just failed on NixOS with sandboxes enabled, then succeeded when I tried to re-run.  Hopefully fixed in the newer version :crossed_fingers:
