### ISSUE TITLE
Curl fails with "curl: (7) Failed to connect to ... port 80: Connection refused"

### ISSUE THREAD

**Issue by robberer** [NixOS/nixpkgs#7586]
On current master branch `nixos-rebuild` fails due to a curl error:

```
curl: (7) Failed to connect to www.linuxfromscratch.org port 80: Connection refused
error: cannot download pycairo-1.10.0-waf_unpack-1.patch from any mirror
```

It's not a local network error because Chrome, Lynx, Links are able to access this file.

I can reproduce this just by running ```curl http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_unpack-1.patch```

Any ideas ?

**Comment by pSub** [comment]
My first guess would be, that this is a user-agent issue. Try downloading it with the option `--user-agent 'Mozilla/5.0'`. However, I am not able to reproduce your problem.

```
% curl -O http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_unpack-1.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   597  100   597    0     0   1613      0 --:--:-- --:--:-- --:--:--  1617
```

**Comment by wwat** [comment]
The version of curl might also matter.

**Comment by pSub** [comment]
```
 % curl --version                                                                                               
curl 7.41.0 (x86_64-unknown-linux-gnu) libcurl/7.41.0 OpenSSL/1.0.1m zlib/1.2.8 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

**Comment by robberer** [comment]
Sorry for the delay and thanks for your responses.

```
# nixos-version 
15.05.git.5b03e5d (Dingo)
```

```
# which curl
/run/current-system/sw/bin/curl
```

```
# curl --version    
curl 7.39.0 (x86_64-unknown-linux-gnu) libcurl/7.39.0 OpenSSL/1.0.1k zlib/1.2.8 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

@pSub 

You're right. With ```--user-agent 'Mozilla/5.0'``` I'm able to download the file. But how can I pass this to nixos-rebuild ?

**Comment by pSub** [comment]
I have fixed it in e1c65ddfe11c8070dda00a66f2b4ae45bbddb0bc. I am not sure how you could pass the option to nixos-rebuild, but picking this commit should work.

**Comment by robberer** [comment]
Thanks for your affords but unfortunately it does not work. Still "connection refused".

**Comment by pSub** [comment]
That is strange are you sure you are at e1c65ddfe11c8070dda00a66f2b4ae45bbddb0bc and specify the nixpkgs repo correctly from nixos-rebuild?

**Comment by wwat** [comment]
Regardless of whether it works, this concept of faking the user-agent needs to be implemented elsewhere.

**Comment by pSub** [comment]
@wwat What is wrong with the current approach and what do you suggest?

**Comment by wwat** [comment]
Individual packages should not make up their own user-agent string. They should just call a program named 'curl-with-fake-user-agent' or better 'http-call-with-fake-user-agent'. That program can then concentrate on doing requests with an even more random user-agent or it could fall back to wget when curl isn't working. I.e., to make the program more robust. 

Nixpkgs is no place for hacks, imho.

**Comment by robberer** [comment]
@pSub My nixpkgs tree is at 74742ad

**Comment by robberer** [comment]
One more interessting thing is that ```curl --user-agent 'Mozilla/5.0' -O http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_unpack-1.patch``` works as user root but not as a regular user. Both use the same version under `/run/current-system/sw/bin/curl`.

**Comment by robberer** [comment]
OK, and root does not need the faked user-agent :-/ . So the problem is persistent only for regular users, which includes nixbld users.

**Comment by robberer** [comment]
Good news, I found the problem of this issue after reading some tcpdumps. There seems to be some Round-Robin mechanism that switches between IPv4 and IPv6 adresses. www.linuxfromscratch.org has DNS entries for both protocols but only listen on port 80 for IPv4.

Sorry. I think commit e1c65dd can be reverted.

You guys have a voucher for a free beer. @pSub @wwat
