### ISSUE TITLE
Conflicting definitions for programs.ssh.askPassword in plasma5 and seahorse

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#75867]
**Describe the bug**

When plasma5 and gnome3 are enabled on my configuration.nix I get the following error:
```
# nixos-rebuild boot 2>&1 | tee /var/log/nixos-rebuild.log
building Nix...
building the system configuration...
trace: warning: mlocate does not support searching as user other than root
error: The option `programs.ssh.askPassword' has conflicting definitions, in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/plasma5.nix' and `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/programs/seahorse.nix'.
(use '--show-trace' to show detailed location information)
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.3, NixOS, 20.03pre205624.8636580d6f4 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre205710.352f030b715"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services/x11/desktop-managers/plasma5.nix programs/seahorse.nix
```

**Comment by hedning** [comment]
Right, I thought `mkDefault` would take care of that, but apparently not. Is the only way to fix things like these to hardcode a specific priority @worldofpeace?

**Comment by worldofpeace** [comment]
> Right, I thought `mkDefault` would take care of that, but apparently not. Is the only way to fix things like these to hardcode a specific priority @worldofpeace?

In the instance of multiple declarations of `programs.ssh.askPassword`, I think it should just null itself out. There's no value that can be appropriately determined.

**Comment by knedlsepp** [comment]
Experienced this evaluation error when bumping to 20.03. Not yet knowing what this actually implies, I'm currently working around this by setting:
```nix
{ config, pkgs, ... }: {
  services.xserver.desktopManager.plasma5.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
  programs.ssh.askPassword = pkgs.lib.mkForce "${pkgs.plasma5.ksshaskpass.out}/bin/ksshaskpass";
}
```

**Comment by worldofpeace** [comment]
@knedlsepp This means, default, you can't evaluate using both gnome3 and plasma5?

**Comment by knedlsepp** [comment]
> @knedlsepp This means, default, you can't evaluate using both gnome3 and plasma5?

That's correct. I haven't tried the actual minimal example, but disabling either plasma5 or gnome3 would also make it evaluate, so I'm guessing it's the same issue as the OP describes.

**Comment by hedning** [comment]
So we could add different priorities to the gnome/plasma mkDefault, but that's pretty hacky. Ideally we'd have a better way to do per desktop config. That's doable by pushing things into shellInit and matching on `XDG_DESKTOP_SESSION`. That's hardly super pretty either, but it would solve the problem.

**Comment by jnoortheen** [comment]
I bumped into the same issue. 

> Experienced this evaluation error when bumping to 20.03. Not yet knowing what this actually implies, I'm currently working around this by setting:
> 
> ```nix
> { config, pkgs, ... }: {
>   services.xserver.desktopManager.plasma5.enable = true;
>   services.xserver.desktopManager.gnome3.enable = true;
>   programs.ssh.askPassword = pkgs.lib.mkForce "${pkgs.plasma5.ksshaskpass.out}/bin/ksshaskpass";
> }
> ```

this fixes the issue just after removing the gnome3 line.

![image](https://user-images.githubusercontent.com/6702219/87224955-f4f66f80-c3a6-11ea-9ca0-c0846850a0f9.png)

**Comment by romildo** [comment]
In nixpkgs unstable now I am getting the following error message:

``` console
error: The option `system.nixos-generate-config.desktopConfiguration' has conflicting definition values:
- In `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/gnome3.nix':
    ''
      # Enable the GNOME 3 Desktop Environment.
      services.xserver.enable = true;
      services.xserver.displayManager.gdm.enable = true;
      services.xserver.desktopManager.gnome3.enable = true;
    ...
- In `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/plasma5.nix':
    ''
      # Enable the Plasma 5 Desktop Environment.
      services.xserver.enable = true;
      services.xserver.displayManager.sddm.enable = true;
      services.xserver.desktopManager.plasma5.enable = true;
    ...
```

**Comment by worldofpeace** [comment]
I actually don't think even other distros have an elegant way to deal with this.
We could have something in the `ssh` module that tries to determine which `askPassword` program to use, and if we run into a situation where we have conflicting programs (these two desktops enabled), we just use the default `${pkgs.x11_ssh_askpass}/libexec/x11-ssh-askpass`. The drawback of this is there isn't an elegant way to choose which askpass program is used in what session you start.

The more complicated alternative could be that the ssh module has a `programs.askPassword.program = "";` and `programs.askPassword.per-session.gnome3.program` `programs.askPassword.per-session.plasma5.program` (rough name). That allows you to configure what program to use per-session, but the `askPassword.program` has a higher priority than `per-session`, a global override if you will. This could then be implemented using`services.xserver.displayManager.sessionCommands` matching on `XDG_CURRENT_DESKTOP`. The option names are terrible but I think this should work.

Personally, I think that being to configure `askPassword` program per-session is a pretty small subsection of users who use multiple desktops. I think option 1 is very simple and would fix the issue of conflicting definitions by driving the logic into the `ssh` module.

**Comment by worldofpeace** [comment]
Actually, I think maybe this discussion isn't correct. It makes more sense that Plasma, GNOME, etc. set this themselves. I think perhaps we've broken this by force setting `SSH_ASKPASS`.

**Comment by psydvl** [comment]
Or
```
programs.ssh.askPassword = pkgs.lib.mkForce "${pkgs.gnome.seahorse.out}/libexec/seahorse/ssh-askpass";
```

**Comment by bugQ** [comment]
> For anyone reading this in Oct 2022, the correct override is now:
> 
> ```
>   programs.ssh.askPassword = pkgs.lib.mkForce "${pkgs.ksshaskpass.out}/bin/ksshaskpass";
> ```
> 
> (ksshaskpass was moved out of plasma5 it appears)



> Or
> 
> ```
> programs.ssh.askPassword = pkgs.lib.mkForce "${pkgs.gnome.seahorse.out}/libexec/seahorse/ssh-askpass";
> ```

I'm grateful to know the latest workarounds (although `mkForce` is not necessary, because explicit options override implicit ones) but we all agree that it would be better to have a definitive solution to this problem, right ?

I know @worldofpeace has already abandoned their idea of per-session settings but it is exactly what I would want for my setup and I think it has potential to be useful for other DE-specific settings as well.

**Comment by slashformotion** [comment]
still an issue to this day on latest stable

**Comment by SuperSandro2000** [comment]
> still an issue to this day on latest stable

and it will likely always be one, as different desktop environments set different programs and there is no way to know which one the user prefers for both desktop sessions.

**Comment by bugQ** [comment]
> there is no way to know which one the user prefers for both desktop sessions.

Adding a way to specify that is exactly what is being proposed, though.

**Comment by SuperSandro2000** [comment]
The module system already informs you of the conflict and you need to explicitly choose one implementation. We don't need to add another indirecion which is likely badly tested by the DE maintainers.

**Comment by Sackbuoy** [comment]
January 2025, I was able to work around this with:
```
  programs.ssh.askPassword = pkgs.lib.mkForce "${pkgs.kdePackages.ksshaskpass.out}/bin/ksshaskpass";
```
