### ISSUE TITLE
autoupgrade allows to specify only dates (startAt)

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#75861]
When using autoupgrade in my NixOS, it allows me to set dates only. On laptop that goes sleep, resume, it means it barely has opportunity to upgrade since the dates can specify just one point in day (or repeat it). So it either does not upgrade or upgrades every specified intervals which might be too often (dates='00/2:00')

So whan is needed is to add `Persistent = true` to the systemd timer used for autoupgrade so it runs upgrade if timer was missed which allows to set dates='00:00' and it either updates at specified time or right after reboot if it did not.

**Comment by tex** [comment]
Actually having frequent upgrade does not hurt as it does not create a new configuration so it looks harmless.

**Comment by TLATER** [comment]
@tex would a `Persistent=` flag not still be nicer, simpy to avoid wasting away valuable processor time throughout the day? I'd much rather have my laptop update when I'm probably not actively using it for anything, or catching up when I turn it back on.

```
system.autoUpgrade = {
    enable = true;
    persistent = true;
};
```

would be very nice.

**Comment by tex** [comment]
Oh true, having persistent option would be good. Or be able to specify something like 15 min after boot and then every day. Basically to have access to the systemd timer setting.
