### ISSUE TITLE
Dillo does not allow accessing site served via https

### ISSUE THREAD

**Issue by wnklmnn** [NixOS/nixpkgs#75906]
**Describe the bug**
Despite the derivation adding the flag '--enable-ssl' to the ./configure invocation dillo is not able to access site served via https://

**To Reproduce**
1. Install dillo
2. try to access https://nixos.org/

**Expected behavior**
Either dillo should not be compiled with the --enable-ssl flag or dillo should be able to access sites served with https

**Additional context**
This seems to be a common issue with dillo. Applying [the patch](https://salsa.debian.org/debian/dillo/blob/da040e1ffcc88c8fd29395ea5a9597fe3f357399/debian/patches/fix-OpenSSL-1.1-detection.patch) provided by the Debian packaging team solves this issue.

My attempt to fix this. [Link](https://github.com/wnklmnn/nixpkgs/commit/33999f4dfd2c6cf9edfe80d0c205f249d72180b4)

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-6-amd64, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(....): `"nixpkgs-20.03pre204216.cc6cf0a96a6"`
 - nixpkgs: `/home/..../.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dillo
```

**Comment by AndersonTorres** [comment]
This is old!
Unfortunately I was not pinged on that time, however I have fixed it today.
