### ISSUE TITLE
Major arm regressions on hydra

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#76064]
now up to ~7000 packages broken from the last staging branch merge https://hydra.nixos.org/eval/1560883

cc @FRidh @jtojnar

**Comment by jtojnar** [comment]
Looks like ghostscript is a common issue: https://hydra.nixos.org/build/108502800/nixlog/1

**Comment by jonringer** [comment]
it only broken 700 builds, something else is breaking >1000

related: #76051

**Comment by jtojnar** [comment]
```
Array.from(document.querySelectorAll('tr')).filter(row => row.querySelector('.build-status[title="Failed"]') == null).forEach(el => el.parentNode.removeChild(el))
```

helps filtering it to causes.

Another high stakes package is pygobject2 https://hydra.nixos.org/build/108541385/nixlog/1 but it seems to be fixed on master.

**Comment by jonringer** [comment]
stale
