### ISSUE TITLE
NixOS manual on one page, please

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#7607]
http://nixos.org/nixos/manual/

I don't know who had the idea to split the manual in multi pages, but it's stupid: it's not searchable, hence it's useless for all the people past the installation. The search bar on top is for google, but I want to search the manual.

Suggestion: let the whole manual be in one page except nixos options.

cc @edolstra @domenkozar

**Comment by edolstra** [comment]
Having one gigantic manual page is not very scalable.

**Comment by lethalman** [comment]
@edolstra you haven't read my suggestion I guess: let the whole manual be in one page **except nixos options**. That's not gigantic.

**Comment by nmikhailov** [comment]
@lethalman see #7034

**Comment by nmikhailov** [comment]
I both agree that single-page doc is superior and including options sections results in a bit too big page. I will try to separate them in #7034

**Comment by jagajaga** [comment]
:+1:

**Comment by nmikhailov** [comment]
Preview: http://nmikhailov.github.io/nixpkgs

**Comment by vcunat** [comment]
Perhaps we should generate both single-page and multi-page version, as neither seems always superior to the other.

**Comment by bjornfor** [comment]
+1 for both single- and multipage manual. (I was about to suggest that myself, having seen that in many online GNU software manuals.)

**Comment by devhell** [comment]
+1 Not being able to search in a single page manual is a bit tedious.

**Comment by edwtjo** [comment]
I like multiple pages, this seems more like a UX complaint and that we should just fix the searchbar

**Comment by vcunat** [comment]
BTW, for searching I just use google ``site:nixos.org/nixos/manual foo bar``. We could have a clickable box redirecting to that, for example.

**Comment by devhell** [comment]
@edwtjo And how would you do that when using `nixos-help`?

**Comment by edwtjo** [comment]
@devhell easy peasy. You traverse the html files, using javascript of course, perhaps putting them in `localStorage` and using something like [reyes](https://github.com/reyesr/fullproof) for search results.

**Comment by devhell** [comment]
@edwtjo So an offline search engine? In that case I'm cool with multiple pages. Or, maybe there could be a toggle, between one-page an multi-page? Might be easier to implement.

**Comment by domenkozar** [comment]
This is why it would be easier to switch to Sphinx, all the tooling is
already done.

**Comment by edwtjo** [comment]
@domenkozar does it provide client side search capabilities like [fullproof](http://reyesr.github.io/fullproof/)?

**Comment by domenkozar** [comment]
See for yourself: https://alembic.readthedocs.org/en/latest/

**Comment by edwtjo** [comment]
@domenkozar sorry but I don't understand, that seems to be documentation for a database migration tool? I'm no expert on Sphinx/Albemic? But I can't see anything about client side indexing.

**Comment by domenkozar** [comment]
It's a sample documentation made with Sphinx

**Comment by edwtjo** [comment]
I'm retarded.. Thank you! Anyway it looks like it doesn't do the indexing locally but searches using a server process.

**Comment by devhell** [comment]
Okay, different question: Is there really a need to overcomplicate something so simple as presenting a documentation? I mean, every half-way decent browser has a search functionality. Instead of going mental with trying to implement something complex (and let's face it, compared to displaying one page and searching using the browser search) why don't we just give he user the choice of one-page or multi-page documentation?

**Comment by Profpatsch** [comment]
I approve of this. Since there is no working search, I relied on browser-search too.

@devhell Nonetheless, it would be advisable to have fulltext or even index-based search over all docuementation (nixos, nix, nixpkgs). Though I’m not sure a JS-based solution is a sensible solution.

**Comment by edwtjo** [comment]
@Profpatsch why isn't a js solution sensible? Versions are git rev based, which would identify their index, and it would therefore be simple to search nixos/nix/nixpkgs/nixops pages.

**Comment by edwtjo** [comment]
Of course the indexing will not be done until you actually open the docs, perhaps a sphinx process isn't a bad idea. Also the js solution will probably not be supported in the framebuffer.

**Comment by Profpatsch** [comment]
@edwtjo How about generating an index on build time, throw that into a derivation and access it when the docs are opened? Then there could even be a small command line utility for quick search or something.

**Comment by lethalman** [comment]
I'd like to hear some rationale behind single-page vs multi-page, because until now I haven't seen anybody claiming how multi-page is better than single-page, except single-page being heavy for the options chapter which can be simply separated.

So, please, anybody supporting multi-page explain why it's better.

About single-page: about every viewer has a built-in search, including the text terminals. When you search you get immediately the context, instead of parts of it. With single-page you also read part of the previous and next paragraph, so you know where you are, instead of clicking back and forth.

About multi-page: cool and modern back and next buttons with isolated paragraph contents (which can be done with single-page, anyways), search bar that should be customized and made it work for the different environments (online browser, local browser, terminal), a search-index to maintain for just a bunch of pages which brings nothing to speed and it's a hassle whenever we want to change the layout of the docs. Anything else I'm missing?

**Comment by devhell** [comment]
@lethalman I agree. From a pure usability point of view, and bearing in mind that the primary reason anyone will open the manual is to search for something, single-page is superior for the manual sans options. But again, I haven't heard a reason why we can't give the user the choice between both, even if it means that we won't have an in-built search function done in sphinx/js/whatever for the multi-page version.

My rationale so far for giving the user a choice:
  1. Give users a single-page manual without the options (which is separated out anyway), so they can easily search for stuff using their viewer of choice and its respective search function.
  2. Give users a multi-page manual for casual reading and studying. This would make it behave much more like the type of document one might want to read when wanting to learn something, similar to a book.

A simple landing page with a choice for either option presented to the user maybe?

**Comment by edwtjo** [comment]
@lethalman that about covers it; except for the scalability reason. My reason for endorsing multi-pages is that I wanted to generate infopages for the manual, which would've been nicer with multiple pages. However, in it's current state that doesn't work, it looks terrible.

**Comment by lethalman** [comment]
@devhell never said I'm contrary to both. I'm contrary to the current multi-page only version.

**Comment by devhell** [comment]
@lethalman I didn't mean you explicitly. It was a question posed more at the general readership of this thread. Sorry for the confusion.

**Comment by edwtjo** [comment]
So both and move on?

**Comment by lethalman** [comment]
@edwtjo so make single-page available ASAP, think about cool multi-page with search later... please.

**Comment by devhell** [comment]
Or y'all know, don't do cool multi-page at all.

**Comment by devhell** [comment]
But yeah, one single-page ASAP would be really cool.

**Comment by edwtjo** [comment]
@lethalman @devhell Guys, I'm not stopping anyone, how you want to make use of my suggestions is up to you.

**Comment by devhell** [comment]
@edwtjo Same here, just an observation/suggestion.

**Comment by lethalman** [comment]
Someone please bring back the old single-page manual, except the configuration options chapter for the next release. That unsearchable documentation is embarrassing.

**Comment by Shados** [comment]
> @edwtjo so make single-page available ASAP, think about cool multi-page with search later... please.

Very much in support of getting the single-page version back literally as soon as possible, even if we don't yet have the option appendix split-off. Usability is currently completely killed by the half-baked multi-page version -- it's not really relevant if a theoretical fancy multi-page version with good JS search would work or not, because we need something that works sanely **now**.
