### ISSUE TITLE
networking.nat - can't access services on the NAT box host

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#76115]
**Describe the bug**

I have a bit of a NAT scenario that doesn't work. Either due to a bug in the scripted NAT setup or due to gaps in my understanding/expectations here.

* Physical Network: 192.168.1.0/24.
* Gateway is 192.168.1.1.
* Clients:
  * `xeep`: 192.168.1.35
  * `denon_receiver`: 192.168.1.112

I have a WG interface configured to live on 192.168.2.1. It has two clients. The clients connect fine.

wg_client0 can (when forcing ALL connections through the VPN via Android 10) access: the Internet, other LAN devices (aka, the denon receiver). **But NOT services on the WG host itself 192.168.1.35**.

I have Home-Assistant running, for example, but the same thing happens when I try to just start python3. In both cases I've confirmed they're listening on all interfaces.

```
networking.nat = {
  enable = true;
  internalInterfaces = [ "wg0" ];
  externalInterface = "eth0";
}
```

I've also tried with `forwardPorts` like so ....
```
networking.nat.forwardPorts = [
  { destination="127.0.0.1:8123"; proto="tcp"; sourcePort=8123; }
];
```

But no matter what I do I can't access services on the NAT host.

Additional problems: I have limited experience with iptables (and what I have came from lots of reading last night), and I'm not even sure what level of support there is for this. But I can't imagine I'm the only one trying to run an additional accessible service on a VPN host/gateway.

**Comment by rnhmjoj** [comment]
pinging some NAT module contributors: @volth @ryantrinkle @lovesegfault

**Comment by volth** [comment]
Is it related?
https://github.com/NixOS/nixpkgs/pull/35161

**Comment by colemickens** [comment]
I'm not sure. I'm pretty confused and I've looked at this on a few occasions. I'm not sure that I actually want anything related to forwardPorts. If I think of the analogue of a router with forwarded ports... that's not what I'm looking for.

In the picture below, the wireguard client can access the receiver server, but cannnot access the python server running on the wireguard/web server.

My expectation is that it should be accessible via 192.168.1.35:8000 (possibly also 192.168.2.1:8000 as well).

```
                  +--------------------------------------------------+
+-------------+   |  +--------------------------+  +----------------+|
| 192.168.2.2 |   |  |                          |  |                ||
| wg client   |   |  | wireguard/web server     |  | receiver       ||
+-------------+   |  | 192.168.1.35 (en....)    |  | 192.168.1.112  ||
        |         |  | 192.168.2.1/24 (wgo)     |  |                ||
        |------------------------------wg0- -----------> OK!        ||
                  |  |                          |  |                ||
                  |  | python3 -m http.server   |  +----------------+|
                  |  | (http://0.0.0.0:8000)    |                    |
                  |  +--------------------------+                    |
                  |           home network = 192.168.1.1/24          |
                  +--------------------------------------------------+
                                                                      
```

**Comment by colemickens** [comment]
It looks like it simply came down to updating networking.firewall.allowedTCPPorts to allow access to home-assistant's port (or in my example, the python server port). Ouch.

I know the discussion about default opening ports has been had but it'd be cool to have a linter/warning system/tool that could tell users about potential misconfigurations. (If the user wanted to only run it locally, they could hint/declare this somehow, via some mechanism I'm handwaving into existence).
