### ISSUE TITLE
MuseScore 2.0.0: enabled plugins don't appear in the menu

### ISSUE THREAD

**Issue by cillianderoiste** [NixOS/nixpkgs#7612]
I recently updated MuseScore to 2.0.0 but I have since noticed that, although I can select and enable plugins, they don't appear in the plugins menu afterwards. I'll look in to it further.

@vandenoever, hopefully this doesn't break things for you, otherwise feel free to revert.

**Comment by Profpatsch** [comment]
(triage) still a problem?
