### ISSUE TITLE
rclone path missing from systemd unit created by services.restic.backups

### ISSUE THREAD

**Issue by srstevenson** [NixOS/nixpkgs#76146]
**Describe the bug**

The systemd unit created generated by the [`services.restic.backups`](https://nixos.org/nixos/manual/options.html#opt-services.restic.backups) module doesn't put `rclone` on the path, so backups to [`rclone` backends](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#other-services-via-rclone) fail.

**To Reproduce**

Configure `services.restic.backups` to backup to an `rclone` backend, for example:
```nix
services.restic.backups.remote = {
  passwordFile = "/path/to/password-file";
  paths = [ "/path/to/backup" ];
  repository = "rclone:remote:path-to-repo";
  timerConfig = { OnCalendar = "hourly"; };
};
```
Observe that the backup fails because `rclone` is not available on the path:
```
$ sudo journalctl -u restic-backups-remote
-- Logs begin at Thu 2019-11-28 21:44:35 GMT, end at Sat 2019-12-21 19:38:02 GMT. --
Dec 21 19:00:24 localhost systemd[1]: Starting restic-backups-remote.service...
Dec 21 19:00:24 localhost restic[8039]: Fatal: unable to open repo at rclone:remote:path-to-repo: exec: "rclone": executable file not found in $PATH
Dec 21 19:00:24 localhost systemd[1]: restic-backups-remote.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 19:00:24 localhost systemd[1]: restic-backups-remote.service: Failed with result 'exit-code'.
Dec 21 19:00:24 localhost systemd[1]: Failed to start restic-backups-remote.service.
```

**Expected behavior**

`rclone` is available on the path and the backup succeeds.

**Additional context**

I'm currently working around this by manually adding the `rclone` path to the generated systemd unit with:
```nix
systemd.services.restic-backups-remote.path = [ pkgs.rclone ];
```

**Metadata**
 Please run nix run nixpkgs.nix-info -c nix-info -m and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.90-hardened, NixOS, 19.09.1664.968381812b4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1664.968381812b4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.backup.restic
```

**Comment by eliasp** [comment]
Fixed in 56191821ea755a7e1cdd3985a89298d6ddfb8559 via #91424
