### ISSUE TITLE
wrapPython: makeWrapperArgs should be an array

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#76158]
**Describe the bug**
Trying to do 
```
preFixup = ''
  makeWrapperArgs+=("''${gappsWrapperArgs[@]}")
'';
```

doesn't work.

Looking at https://github.com/NixOS/nixpkgs/blob/e7c568a0b0d6a54a384a8a32b8cf278d58d681a7/pkgs/development/interpreters/python/wrap.sh#L84 it's not an array.

I believe `qtWrapperArgs` and `gappsWrapperArgs` are all arrays and if the above example was changed to use them it would work.

I unfortunately changed and documented this expecting it work at https://github.com/NixOS/nixpkgs/pull/75465 and broke things.

See also https://github.com/NixOS/nixpkgs/issues/75844 and https://github.com/NixOS/nixpkgs/pull/75054#discussion_r357656916.

cc @jonringer  @FRidh 

**To Reproduce**
Build aforementioned expressions and notice their wrappers are incomplete when utilizing wrapPython.

**Comment by worldofpeace** [comment]
cc @jtojnar as well.

**Comment by jonringer** [comment]
seems reasonable to me

**Comment by worldofpeace** [comment]
I believe this was fixed
