### ISSUE TITLE
rofi doesn't display hicolor icons

### ISSUE THREAD

**Issue by MetaDark** [NixOS/nixpkgs#76196]
**Describe the bug**
When using rofi with icons enabled, applications icons stored in `share/icons/hicolor` aren't shown. However, icons installed under `share/pixmaps` display as expected.

**To Reproduce**
1. Install an application that only has hicolor icons (firefox, emacs, ...) 
2. Run rofi with icons enabled: `rofi -show-icons -modi drun -show drun`

**Expected behavior**
Icons from the hicolor theme should be displayed if they are available.

**Screenshots**
![rofi](https://user-images.githubusercontent.com/382041/71330229-b2983e80-24f9-11ea-93a4-6998b9c1fdef.png)

**Additional context**
I've narrowed down the issue to one of rofi's dependencies: https://github.com/sardemff7/libnkutils/blob/8adccd3b1b33b2a9a29dd12a7e686907bbafc5d4/src/xdg-theme.c#L506-L529.

It looks like it expects the file `share/icons/hicolor/theme.index`, and since this file doesn't exist, the icon theme won't load. I'm not sure if it would be better to add `theme.index` or patch the library.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - channels(kira): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: rofi
# a list of nixos modules affected by the problem
module:
```

**Comment by MetaDark** [comment]
I copied over `/usr/share/icons/hicolor/index.theme` from my Arch machine to `~/.local/share/icons/hicolor/index.theme` as a workaround and the icons load as expected:

![rofi_000](https://user-images.githubusercontent.com/382041/71331539-a5328280-2500-11ea-8912-d4989b6c62ee.png)

**Comment by worldofpeace** [comment]
@MetaDark Is `hicolor-icon-theme` installed? at `/run/current-system/sw/share/icons/hicolor`?

**Comment by MetaDark** [comment]
@worldofpeace I didn't have it installed before, but it works after adding it, thank you! Should this be added as a propagatedBuildInput in rofi?

**Comment by worldofpeace** [comment]
> @worldofpeace I didn't have it installed before, but it works after adding it, thank you! Should this be added as a propagatedBuildInput in rofi?

It's possible to use `wrapGAppsHook` and put `hicolor-icon-theme` in `buildInputs`.
This will prefix `XDG_DATA_DIRS` with `hicolor-icon-theme`, so it wouldn't need to be installed.
However, I just recommend to have the theme installed if icons are being installed there.
