### ISSUE TITLE
The link to CLTools 404s

### ISSUE THREAD

**Issue by smobs** [NixOS/nixpkgs#7620]
Nixpkgs checkout: cb8f111a72a54888dea24b6ccbdb5a657577983f
OSX 10.10.3
http://swcdn.apple.com/content/downloads/27/02/031-06182/yiervn212jfs091cp9hwmb7gjq7ky91crs/CLTools_Executables_OSX109.pkg returns a 404 code.  This happens even if I try to access the url directly. This could be because I am in the UK.

**Comment by smobs** [comment]
@henrytill suggested I could get a new url from here:https://swscan.apple.com/content/catalogs/others/index-10.9-1.sucatalog and use nix-prefetch-url to add it to the store(based on https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/command-line-tools/default.nix).

However I'm not having any luck making head or taill of the sucatalog file.

**Comment by gridaphobe** [comment]
Hrm, the URL works for me from the US. Not sure what to do about this..

**Comment by copumpkin** [comment]
Someone else (@acowley) was also complaining that the link didn't work for them. When I tried the URL multiple times from my connection, most of the time it worked but sometimes it 404'd. No idea what's going on, but it doesn't seem like it would affect just us.

**Comment by acowley** [comment]
I'm in the US, too, btw.

**Comment by copumpkin** [comment]
Pure-darwin doesn't need CLTools for most of the stdenv, but is not ready to merge yet. It would still be good to understand why this URL (which is the same one used by Apple's software update service) is so unreliable.

**Comment by spwhitt** [comment]
As a stopgap until pure-darwin, maybe we should just mirror the url somewhere. Alternately, accept the impurity and require people to install cltools. Either works for me.

**Comment by adnelson** [comment]
Getting the same:

```
trying http://swcdn.apple.com/content/downloads/27/02/031-06182/yiervn212jfs091cp9hwmb7gjq7ky91crs/CLTools_Executables_OSX109.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by bflyblue** [comment]
Might be a problem with their CDN, NOT working for me from this host:

despina ~ % host swcdn.apple.com
swcdn.apple.com is an alias for swcdn.apple.com.akadns.net.
swcdn.apple.com.akadns.net is an alias for swcdn.apple.com.edgesuite.net.
swcdn.apple.com.edgesuite.net is an alias for a1271.gi3.akamai.net.
a1271.gi3.akamai.net has address 196.26.223.17
a1271.gi3.akamai.net has address 196.26.223.11

But IS working from a host in a different geo location:

umbriel ~ % host swcdn.apple.com
swcdn.apple.com is an alias for swcdn.apple.com.akadns.net.
swcdn.apple.com.akadns.net is an alias for swcdn.g.aaplimg.com.
swcdn.g.aaplimg.com has address 17.253.8.223

**Comment by ericbmerritt** [comment]
Just as a addition. This worked for me in the US a few weeks ago. Now I am visiting family in Peru and it no longer works for me.

**Comment by Profpatsch** [comment]
(triage) still a problem?
