### ISSUE TITLE
lightdm appears to have a dependency on accounts service

### ISSUE THREAD

**Issue by willtim** [NixOS/nixpkgs#7621]
Just tried installing unstable and the lightdm display manager fails to start with: 

"WARNING: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service"

Adding "services.accounts-daemon.enable=true", fixes the issue. Should this be a dependency of lighted?

**Comment by wkennington** [comment]
Are you using gnome?

**Comment by willtim** [comment]
Hi, 

No I'm using i3. Just to reiterate,  everything works great with 'services.accounts-daemon.enable=true'. It's as if the greeter is expecting that service. 

Best regards, 
Tim

**Comment by lethalman** [comment]
@wkennington maybe this new version has changed some requirement. On fedora it's clear it depends on accountsservice: http://pkgs.fedoraproject.org/cgit/lightdm.git/tree/lightdm.spec#n57

Also accountsservice is not a gnome thing.

**Comment by wkennington** [comment]
Well, it's an optional runtime dependency unless you are using gnome and it
changes the behavior of how lightdm registers users to its interface and
sets up portraits. You don't have to enable it, but there is no way to get
rid of the warning.

**Comment by wkennington** [comment]
It's really annoying to always enable account service because it breaks the
ability to hide users

**Comment by willtim** [comment]
I

**Comment by willtim** [comment]
Closing this issue as I've confirmed the warning is  harmless. Apologies for the noise.
