### ISSUE TITLE
anki no longer starts 

### ISSUE THREAD

**Issue by redfish64** [NixOS/nixpkgs#76252]
**Describe the bug**
anki-2.15 fails with:

qt: Could not find the Qt platform plugin "xcb" in ""
qt: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)

**To Reproduce**
Run anki

**Additional context**
I was able to fix this by reverting the change to ./pkgs/games/anki/default.nix made in the following commit:

commit abe3475df8fd133045cd01fb14e0d7013cecf66e
Author: worldofpeace <worldofpeace@protonmail.ch>
Date:   Tue Dec 10 18:23:57 2019 -0500

    treewide: remove bash snippets in flags
    
    Co-Authored-By: Jan Tojnar <jtojnar@gmail.com>

**Comment by veprbl** [comment]
cc @worldofpeace @jtojnar

**Comment by jtojnar** [comment]
Another instance of https://github.com/NixOS/nixpkgs/issues/76158

**Comment by peti** [comment]
Ping?

**Comment by jtojnar** [comment]
Was this not fixed by https://github.com/NixOS/nixpkgs/pull/76283?

**Comment by peti** [comment]
Oh, yeah! `anki` works in 7391a22a4467884d269ae61b298818bc7593f336. Thanks!
