### ISSUE TITLE
acme: "Selected IO plugins do not cover the following components: account_reg." (with fix)

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#76270]
**Describe the bug**

This is more advisory than anything.

If you see something like:

```
Dec 23 14:37:05 flexo.gsc.io simp_le[15797]: 2019-12-23 14:37:05,793:DEBUG:simp_le:1522: ('-v', '-d', 'flexo.gsc.io', '--default_root', '/var/lib/acme/acme-challenge', '--valid_min', '2592000', '--email', 'graham@grahamc.com', '-f', 'cert.pem', '-f', 'fullchain.pem', '-f', 'full.pem', '-f', 'key.pem', '-f', 'account_key.json', '-d', 'events.nix.gsc.io') parsed as  ...
Dec 23 14:37:05 flexo.gsc.io simp_le[15797]: Selected IO plugins do not cover the following components: account_reg.
Dec 23 14:37:05 flexo.gsc.io simp_le[15797]: Debugging tips: -v improves output verbosity. Help is available under --help.
```

you need to edit `services.acme.certs.NAME.plugins` to include `account_reg.json`. This is automatic by default, and only needed if you specify a custom list.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 19.09.1590.d85e435b7bd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1590.d85e435b7bd"`
 - channels(grahamc): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pvgoran** [comment]
It would be good to have an ability *not* to modify custom plugin list when something like this happens. Maybe add a new `additionalPlugins` option, or providing the "default" list of plugins somewhere...
