### ISSUE TITLE
services.rsyslogd.enable = true causes rebuild to fail (hvm instances)

### ISSUE THREAD

**Issue by jtbuchanan** [NixOS/nixpkgs#7634]
Hello, 
Adding services.rsyslogd.enable = true;   to a NixOS configuration file and attempting an nixos-rebuild switch causes a failure with the syslog.service 

There may be something wrong with the nixos.pkgs.rsyslog package?

Thank you

**Comment by geerds** [comment]
What NixOS version are you running? 14.12 or unstable? What's the exact error message?

**Comment by jtbuchanan** [comment]
On AWS
14.12.626.b0d594c (Caterpillar)

nixos-rebuild switch
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
warning: the following units failed: syslog.service

syslog.service - Syslog Daemon
   Loaded: loaded (/nix/store/s24qsl38yff4qnffwp8k6bmgdmw61h7b-unit-syslog.service/syslog.service)
   Active: failed (Result: exit-code) since Thu 2015-04-30 02:03:43 CEST; 17ms ago
  Process: 32461 ExecStart=/nix/store/fn9j761b6d3cwa66zny7av60mhdxdnjn-rsyslog-7.6.3/sbin/rsyslogd -f /nix/store/fkcalrlv3dlanpl1ahfx25yx5m6va14a-syslog.conf -n (code=exited, status=1/FAILURE)
  Process: 32456 ExecStartPre=/nix/store/wc472nw0kyw0iwgl6352ii5czxd97js2-coreutils-8.23/bin/mkdir -p /var/spool/rsyslog (code=exited, status=0/SUCCESS)
 Main PID: 32461 (code=exited, status=1/FAILURE)

Apr 30 02:03:43 ip-*-*-*-*.eu-west-1.compute.internal systemd[1]: Started Syslog Daemon.
Apr 30 02:03:43 ip-*-*-*-*.eu-west-1.compute.internal systemd[1]: syslog.service: main process exited, code=exited, status=1/FAILURE
Apr 30 02:03:43ip-*-*-*-*.eu-west-1.compute.internal systemd[1]: Unit syslog.service entered failed state.
Apr 30 02:03:43 ip-*-*-*-*.eu-west-1.compute.internal systemd[1]: syslog.service failed.
warning: error(s) occured while switching to the new configuration

Thank you for your help

**Comment by rbvermaa** [comment]
@jtbuchanan I have tried to reproduce the issue on EC2 ami 

   [root@ip-10-86-12-74:/etc/nixos]# nixos-version
   14.12.626.b0d594c (Caterpillar)

    [root@ip-10-86-12-74:/etc/nixos]# cat configuration.nix
    { modulesPath, ...}:
    {
      imports = [ "${modulesPath}/virtualisation/amazon-config.nix" ];
      services.journald.rateLimitBurst = 0;
      services.rsyslogd.enable = true;
    }

Could you try to rerun the nixos-rebuild switch and see if it is persistent? Perhaps there is a race condition somewhere.

**Comment by jtbuchanan** [comment]
Just ran again, same error.

It seems the issue may be HVM.

Configuration: 
```
[root@ip-172-30-2-16:/etc/nixos]# cat configuration.nix
{ config, pkgs, ...}:
{
  imports = [ ./amazon-base-config.nix ];
  ec2.hvm = true;
  services.rsyslogd.enable = true;
}
```

I just spun up a paravirtual version now, and that works. 

Updating the issue name to represent hvm instances 

Thank you

**Comment by rbvermaa** [comment]
Ok thanks, will try to test on HVM then.

**Comment by rbvermaa** [comment]
Tested now on HVM instance (r3.large) on which I could also not reproduce the issue. 

@jtbuchanan Do you have the original instance available still?

**Comment by jtbuchanan** [comment]
Yes - I still have the original instance

**Comment by jtbuchanan** [comment]
I just spun up a new hvm instance t2.micro and it did work.  It does seem to be an issue related specifically to my original instance. I will close this issue. 

Thank you for your help.
