### ISSUE TITLE
Generated hardware-configuration.nix files use deprecated attribute

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixpkgs#76391]
The generated `hardware-configuration.nix` files still use the now deprecated `i18n.consoleFont` attribute (it should now be `console.font`). Because of this you get warnings such as below

```
trace: warning: The option `i18n.consoleFont' defined in `/etc/nixos/hardware-configuration.nix' has been renamed to `console.font'.
```

**Comment by prusnak** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/76497
