### ISSUE TITLE
KDE Partition Manager not running with sudo

### ISSUE THREAD

**Issue by jamescostian** [NixOS/nixpkgs#76415]
**Describe the bug**
If you open KDE Partition Manager using its ```.desktop``` file, it tells you that you aren't running it as root, and you won't be able to make any changes with it (rendering the program useless). The only workaround is running ```sudo partitionmanager``` (which is probably unintuitive to people with less linux experience) or changing the ```.desktop``` file (a bad idea when you want Nix to manage your system)

**To Reproduce**
1. Install ```partition-manager``` by adding it to your ```environment.systemPackages```
2. Run the ```.desktop``` file (e.g. in KDE, click on the start menu in the bottom left, type in partition manager, and click on the program)

**Expected behavior**
Use ```pkexec``` when clicking the ```.destop``` file for a seamless experience

**Screenshots**
![image](https://user-images.githubusercontent.com/1456118/71418739-b4fdb400-2631-11ea-94a4-9a10f7400cbe.png)

**Additional context**
The message mentions ```kdesu``` so I tried adding it to ```environment.systemPackages``` by hand, but that did not work.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.90, NixOS, 19.09.1682.bfdae0860e4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1682.bfdae0860e4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Looks like the package is out of date. This dialogue does not appear to be part of the latest version: https://github.com/KDE/partitionmanager/commit/a1a535cb0330ed1bb1c25e1ad5c8a366caab4a93#diff-6433a1a19c7364347102f741d8b9cffd

**Comment by jtojnar** [comment]
This might work https://github.com/NixOS/nixpkgs/pull/61077
