### ISSUE TITLE
minimal iso can't reconfigure itself without internet

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#7648]
Steps to reproduce:

1. download https://nixos.org/releases/nixos/latest-iso-minimal-x86_64-linux
2. start a VM with it as the boot cd
3. log in as root
4. run `nixos-rebuild switch`

=> downloads and builds a bunch of stuff, including building manpages.

@edolstra thoughts? It would be great to be able to change the configuration.nix so you can enable ssh, add a user etc for install or testing purposes.

**Comment by copumpkin** [comment]
:+1:

**Comment by jagajaga** [comment]
I think it's connected to https://github.com/NixOS/nixpkgs/issues/7059

**Comment by wmertens** [comment]
Closing in favor of #7059
