### ISSUE TITLE
squashfsTools: add lzo compression support

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#76507]
The [LibreELEC][1] build for Raspberry Pi compresses its /flash/SYSTEM squashfs with LZO.
But the current squashfsTools package does not include support for it.
It might make sense to add this by default since the [Arch Linux][2] and [Ubuntu][3] packages do this too.

[1]: https://libreelec.tv/
[2]: https://www.archlinux.org/packages/community/x86_64/squashfs-tools/
[3]: https://packages.ubuntu.com/eoan/squashfs-tools

**Comment by AleXoundOS** [comment]
The issue seems to be reasonable.

**Comment by Artturin** [comment]
was enabled in 8a61e45f52ab4f8ce94b0cd8b4333b13e549efe1
