### ISSUE TITLE
steam: "Halo: The Master Chief Collection" fails to run on Proton

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#76516]
**Describe the bug**
While Steam and Proton can launch and execute "Halo: The Master Chief Collection", the game can't get past the title screen due to a nondescriptive Xbox Live sign in error textbox.

**To Reproduce**
1. Launch "Halo: The Master Chief Collection" with Proton 4.11-10 or newer
2. Wait for the title screen

**Expected behavior**
While the game still has some problems similar to this one even in Windows, it should be able to log into Xbox Live and get past the title screen.

**Additional context**
I suspect this may have to do with GnuTLS and chrootenv/Steam Runtime: the Proton patch notes specify you need gnutls newer than 3.5.4 or the Steam Beta client (which I have), and the console logs spews a "GnuTLS error: GnuTLS internal error" message. I think this issue may be due to the fact that the chrootenv script doesn't include GnuTLS, so it may be depending on the gnutls version included in the Steam Runtime, which may have been updated for the Steam Beta client, but not in our repos. The solution would be to update the Steam Runtime libraries to the Steam Beta runtime, or include gnutls into the environment.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206438.a06925d8c60 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206438.a06925d8c60"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by shirona** [comment]
Gonna tag @abbradar since I think he is usually the one who fixes Steam Runtime related bugs.

**Comment by fabianhjr** [comment]
Hi @shirona, trough trial and error I got Halo: MCC running on nixos-20.03pre with the following entry on systemPackages:

`(steam.override { extraPkgs = pkgs: [ cabextract gnutls openldap winetricks ]; nativeOnly = true; })`

Hope it helps

**Comment by anirrudh** [comment]
@fabianhjr your method worked for me, but broke other games in my library. I am still exploring the linux gaming/nix gaming ecosystem, but I know that gnutls was a problem looking at steam logs. Can we avoid using a broken version of Steam?

**Comment by fabianhjr** [comment]
Well, it would be great to have a nix expression with common required libraries. I am guessing the other games also have missing dependencies.

**Comment by anirrudh** [comment]
@fabianhjr the opposite - games like Half Live and Civ VI (Linux native games) break. Weirdly enough, though, Bioshock Infinite does not have this problem.

**Comment by fabianhjr** [comment]
Because this option isolates what libraries steam uses. (Only the system specified ones and not the ones shipped with steam)

**Comment by costrouc** [comment]
To not require a seperate installation you can use nix shell with this.

```
{ pkgs ? import <nixpkgs> {
    config = {
      allowBroken = true;
      allowUnfree = true;
      permittedInsecurePackages = [
        "p7zip-16.02"
      ];
    };
  }
}:

pkgs.mkShell {
  buildInputs = [
    (pkgs.steam.override {
      extraPkgs = pkgs: [ pkgs.cabextract pkgs.gnutls pkgs.openldap pkgs.winetricks ];
      nativeOnly = true;
    })
  ];
}
```

**Comment by SuperSamus** [comment]
Is this still an issue? (I don't own the game)

**Comment by fabianhjr** [comment]
Currently works for me

**Comment by Majiir** [comment]
@SuperSamus Halo MCC won't launch for me at all. Running NixOS 22.05, tested with both Proton Experimental and Proton 7.0-4. I don't get any error messages or title screens. Let me know what information I can collect to make this a more useful report.

**Comment by SuperSamus** [comment]
Useful information would be the output in the terminal (by launching `steam` in the terminal) when trying to launch the game.
Also, what about `nixos-unstable`/`nixpkgs-unstable`?

**Comment by Atemu** [comment]
Yes, please try the upcoming 22.11 release via `nixos-rebuild boot -p unstable -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.zip` + reboot if you can.  
It's trivial to revert back; just `nixos-rebuild boot`, reboot and delete the `unstable` link in `/nix/var/nix/profiles/system-profiles/`. Next GC will clean up the packages from unstable.

**Comment by Majiir** [comment]
Halo MCC is working again on NixOS 23.05.
