### ISSUE TITLE
vscodium: Unable to find pkexec or kdesudo.

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#76526]
**Describe the bug**
Codium fails to save a file as sudo.

**To Reproduce**
1. Open a file that requires administrator privileges in Codium, i.e. `/etc/nixos/configuration.nix`
2. Save the file, it fails due to lack of permissions. Click `Retry as Sudo...`
3. Receive the error: `Failed to save 'configuration.nix': Unable to find pkexec or kdesudo.`

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m                                                                                                                               
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-ck1, NixOS, 20.03pre206438.a06925d8c60 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206438.a06925d8c60, nixos-unstable-20.03pre205792.fb1bc1b891f"`
 - channels(nix): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
The problem lies in the library vscode uses for the prompt.
https://github.com/jorangreef/sudo-prompt/blob/3bfa62163b59e45111436c695ee8e7e2befbe310/index.js#L202, is a hardcoded FHS path. We need to patch the paths somehow.

**Comment by worldofpeace** [comment]
I tried
```
# Fix sudo-prompt pkexec path https://github.com/NixOS/nixpkgs/issues/76526
postPatch = ''
  source_file="resources/app/node_modules.asar"
  unpacked_dir="node_modules"
  output_file="node_modules.asar"

  ${nodePackages.asar}/bin/asar extract "$source_file" "$unpacked_dir"
  substituteInPlace "$unpacked_dir/sudo-prompt/index.js" \
    --replace "/usr/bin/pkexec" "pkexec"
  ${nodePackages.asar}/bin/asar pack "$unpacked_dir/" "$output_file"
  mv -f "$output_file" "$source_file"
  rm -rf "$unpacked_dir"
'';
```

but It didn't work, with surprising errors in `code --verbose` like it wasn't patched correctly.

**Comment by lsaether** [comment]
Are there any known workarounds?

I tried naively copying pkexec binary into `/usr/bin` but that didn't seem to do the trick.

**Comment by Synthetica9** [comment]
Related: https://github.com/jorangreef/sudo-prompt/issues/77

**Comment by Synthetica9** [comment]
> Are there any known workarounds?

There's always `env EDITOR="code --wait" sudoedit file"

**Comment by jul1u5** [comment]
I dug around the source code of the `sudo-prompt` (which VS Code uses) and found that when it's trying to run `pkexec` or `kdesudo` it also runs `/bin/bash` here: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L154.

I was able to fix it this way:

1. Cherry-picked the reverted commit from https://github.com/jorangreef/sudo-prompt/issues/77#issuecomment-445882729 (it fallbacks to which for finding `pkexec`)
2. Replaced `/bin/bash` with `/usr/bin/env bash` in https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L154.

I could make PR with the fix. However, I am not sure if this is the best way to solve this. Do all Linux distos have `/usr/bin/env`?

**Comment by schlichtanders** [comment]
I followed these notes - thank you so much for providing these steps! They have been of massive help.

> I tried
> 
> ```
> # Fix sudo-prompt pkexec path https://github.com/NixOS/nixpkgs/issues/76526
> postPatch = ''
>   source_file="resources/app/node_modules.asar"
>   unpacked_dir="node_modules"
>   output_file="node_modules.asar"
> 
>   ${nodePackages.asar}/bin/asar extract "$source_file" "$unpacked_dir"
>   substituteInPlace "$unpacked_dir/sudo-prompt/index.js" \
>     --replace "/usr/bin/pkexec" "pkexec"
>   ${nodePackages.asar}/bin/asar pack "$unpacked_dir/" "$output_file"
>   mv -f "$output_file" "$source_file"
>   rm -rf "$unpacked_dir"
> '';
> ```
> 
> but It didn't work, with surprising errors in `code --verbose` like either the unpacked node_modules or the binaries weren't patched correctly.

And finally could make it work for vscode :) - please see my comment over there https://github.com/NixOS/nixpkgs/issues/49643#issuecomment-873853897

**Comment by jul1u5** [comment]
I think this can be closed, as https://github.com/NixOS/nixpkgs/pull/137912 should also fix the issue in vscodium.

**Comment by jacopone** [comment]
This is still happening on Cursor 0.42.4 running on Nixos 24.11
