### ISSUE TITLE
rootbrowse in ROOT package cannot launch properly on macOS

### ISSUE THREAD

**Issue by yipengsun** [NixOS/nixpkgs#76524]
**Describe the bug**
I think this is another @veprbl problem:

After installing root (I'm using `nix-darwin`), when I launch `rootbrowse`, I got the following error:

```
Traceback (most recent call last):
  File "/run/current-system/sw/bin/rootbrowse", line 10, in <module>
    import cmdLineUtils
ModuleNotFoundError: No module named 'cmdLineUtils'
```

I managed to find an _improper_ workaround: First I located the installation directory of `root`:
```
/nix/store/<hash>-root-6.18.04
```

Then I manually specify the location of the Python library `cmdLineUtils` that comes with `root`:
```
export PYTHONPATH=/nix/store/<hash>-root-6.18.04/lib
```

Now `rootbrowse` can launch properly.

**To Reproduce**
1. List `root` in `environment.systemPackages`
2. `darwin-rebuild switch`
3. Launch `rootbrowse` in terminal

**Expected behavior**
It should run without problem.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(syp): `""`
 - channels(root): `"darwin, nixpkgs-20.03pre206486.a8fc904c7c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by yipengsun** [comment]
It is worth noting that if I manually source the supplied `thisroot.sh`, `rootbrowse` can run without problem, and I can import `ROOT` in a Python 3 interpreter.

I think a (not the) reasonable approach would be:
1. Make `rootbrowse` globally usable, since it really is an utility
2. Keep the Python `ROOT` moduel as-is (not available unless `thisroot.sh` explicitly sourced by user)

Arch linux takes the approach above, and they copy the `cmdLineUtils` module to global Python library path. But I'm not sure on how to do this sanely in nix.

For example, in my overlay, I have Python defined as:
```nix
  python3-base-dev = super.python3.withPackages (ps: with ps;
    [
      pynvim
      jedi
      flake8
      pylint
    ]
  );
```

But I don't know how to include `cmdLineUtils`---a Python library provided by `root` package---globally.

**Comment by yipengsun** [comment]
Alternatively, I can just source `/run/current-system/sw/bin/thisroot.sh` in my login shell. Which is actually not too bad.

**Comment by veprbl** [comment]
@yipengsun Yes, you are right about needing to source thisroot.sh. This is done automatically in our `setupHook` for `root`, so everything works when `root` is used in other nix builds and in nix-shell:
```
nix-shell -p root --run rootbrowse
```
nix-env does not run setupHook, so you would need to source it yourself, the way ROOT was intended to be used.

In nixpkgs we usually make sure that all of the binaries are wrapped or patched to be able to find their libraries in any environment, so this is considered to be a bug.
