### ISSUE TITLE
[RFP] JDownloader2

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#76568]
**Project description**
JDownloader is a free download-manager that makes downloading as easy, fast and automated as it should be.

It's like your personal internet robot that does all the work for you. He will download whole photoalbums, playlists or just about anything else with just one click. Go ahead and try it!

**Metadata**

* homepage URL: http://www.jdownloader.org/ & http://beta.jdownloader.org/
* source URL: svn://svn.jdownloader.org/jdownloader & https://svn.jdownloader.org/projects
* license: gpl3
* platforms: unix, linux, darwin, win32

**Comment by mkg20001** [comment]
Someone around to handle this?

**Comment by cole-h** [comment]
FYI: this is a dupe of https://github.com/NixOS/nixpkgs/issues/41321. As one of the commenters noted, you can get the standalone JAR file and run it with `java -jar JDownloader.jar`, which works fine in my experience.

Closing this issue in lieu of the aforementioned one.
