### ISSUE TITLE
Nvidia GTX 980 "(EE) No devices detected" 

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#76569]
I am unable to start Xorg due to a Nvidia problem on my desktop NixOS machine running the latest NixOS master with the latest kernel package.

The main error in my X log is this:

```
[   719.532] (EE) No devices detected.
[   719.532] (EE) 
Fatal server error:
[   719.532] (EE) no screens found(EE) 
```

I have read many threads from other people having similar issues, most of which seemed to be resolved by enabling both "intel" and "nvidia" graphics drivers, but this did not work for me (maybe not surprising as this is not a laptop and has no Intel GPU.)

Can someone please suggest a way to troubleshoot this?

## Attempts

I have had Xorg running with Nvidia drivers on this same machine using an only slightly different configuration and older NixOS version. However, alas, I have lost the details of this setup.

I have tried using `[ "intel" "nvidia" ]` as Xorg drivers.

I have tried several different recent NixOS releases.

I have tried the latest kernel package and the default kernel package.

## Hardware

This is a Supermicro desktop dual-socket Xeon E5 with a GeForce GTX 980 card in a PCIe x16 slot.

## Configuration and logs

- [X.0.log](https://gist.github.com/lukego/1857d6921222fff787757c11a1a5a728)
- [configuration.nix](https://gist.github.com/433eed569648adc13e9beda0cd0153dc)
- [lsmod](https://gist.github.com/06c709b1be5696a685aa090b8ec9eae0)
- [dmesg | grep -i nvidia](https://gist.github.com/ab7d41c4951ef6c1115e093262a3c5b0)
- [lspci](https://gist.github.com/ff5c5fc21cdb1fb4759033cd5a490923)
- [nvidia-smi](https://gist.github.com/0af0525c470d09d43a803382f124cb4b)

**Comment by vcunat** [comment]
I'd try just `[ "nvidia" ]` as the driver set.  IIRC there's not a good support for drivers from multiple packages _at once_.  I looked at our driver version's changelog, and your card is explicitly listed as supported.

**Comment by lukego** [comment]
@vcunat no dice - that's the config that's not working with the logs above.

**Comment by vcunat** [comment]
That must be some older master, as the log shows driver version 435.21 and on master I see 440.44, but both version explicitly list your card as supported, so I don't expect upgrading will help by itself.

**Comment by eadwu** [comment]
This might just be a conflict when it can't figure out which GPU to use?

Anyway you probably just want to use just `[ "nvidia" ]` while configuring the PCI ID in the Xorg configuration or trying Prime Sync.

**Comment by lukego** [comment]
I am using only `[ "nvidia" ]`. That's what in the config and the logs above. Any other ideas? (I have also tried running the latest `master` from today but no change.)

I only mentioned having tried `[ "intel" "nvidia" ]` because that was the resolution for many other people who experienced problems with the same Xorg error message.

**Comment by lukego** [comment]
I have been meaning to troubleshoot this further but now it's two months later I don't really have any new ideas. I already spent about a day trying all the ideas that I could find on the internet and nothing worked.

Guess I'll order a Radeon and hope that AMD drivers are more pleasant to work with. If anybody has a last "hail mary" idea before I do that though then please let me know :-)

**Comment by lukego** [comment]
Gave up.
