### ISSUE TITLE
Upgrade python package: PyYAML

### ISSUE THREAD

**Issue by kamadorueda** [NixOS/nixpkgs#76564]
**Project description**
Python Package - PyYAML

**Metadata**

* homepage URL: https://pypi.org/project/PyYAML
* source URL: https://github.com/yaml/pyyaml
* license: MIT
* platforms: OS independent

**Comment by FRidh** [comment]
Update is in staging-next (da5a7381609f82df8bf0fb477dc4a12f7028ba73)

**Comment by FRidh** [comment]
this is in master now
