### ISSUE TITLE
sway: display manager integration fails with gdm

### ISSUE THREAD

**Issue by Elyhaka** [NixOS/nixpkgs#76576]
**Describe the bug**
Sway is not shown in session list with GDM as the display manager.

**To Reproduce**
1. Enable GDM
2. Enable Sway

**Expected behavior**
With #75363 merged, it should be shown on the list.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206438.a06925d8c60 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206438.a06925d8c60"`
 - channels(ely): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
module:
 - sway
```

**Comment by hedning** [comment]
So there's a bug where GDM will fall back to X when the gnome desktop isn't enabled: https://github.com/NixOS/nixpkgs/issues/76169. This prevents GDM launching wayland sessions.

This is a quick fix you can apply in your own config (though you'll get broken gnome desktop entries):
```
    systemd.packages = with pkgs.gnome3; [ gnome-session gnome-shell];
    environment.systemPackages = with pkgs.gnome3; [ adwaita-icon-theme ];

```

**Comment by Elyhaka** [comment]
Thank you for the information @hedning. If `gnome-shell` is mandatory for `GDM`, maybe we could add an option to hide some entries, this way we could keep it clean. For instance, we should unhide these entries only if :
 - User unhides it
 - User explicitly enable Gnome 3 desktops

What do you think of this ? I will start to work on a PR for this unless you think there is a better way ?

**Comment by hedning** [comment]
Lets move the discussion to #76169.
