### ISSUE TITLE
Package request: opensnitch

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#76610]
**Project description**

OpenSnitch is a GNU/Linux port of the Little Snitch application firewall

**Metadata**

* homepage URL: https://github.com/evilsocket/opensnitch
* source URL: https://github.com/evilsocket/opensnitch
* license: gpl3
* platforms: linux

**Comment by adisbladis** [comment]
Opensnitch is unmaintained software. Closing.

**Comment by onny** [comment]
There is a new, actively maintained fork now https://github.com/gustavo-iniguez-goya/opensnitch/releases Waiting for a stable release :)

**Comment by revuwa** [comment]
> There is a new, actively maintained fork now https://github.com/gustavo-iniguez-goya/opensnitch/releases Waiting for a stable release :)

Finally, the [stable](https://github.com/gustavo-iniguez-goya/opensnitch/releases/tag/v1.0.0)-release is available.
@NixOS hackers: would you reopen this issue and have a look into this, please?

**Comment by prusnak** [comment]
@onny @revuwa feel free to create a pull request adding the package

**Comment by onny** [comment]
For testing purpose I continued this package in my [NUR](https://github.com/nix-community/NUR) repository. You can try the package ``nur.repos.onny.opensnitch`` if you want :) I've packaged version 1.0.1. Still not sure which features might be missing or bugs still present.

**Comment by abvbv** [comment]
Looks like the main repo is active now https://github.com/evilsocket/opensnitch. The latest release is v1.3.5 (23 days ago).

**Comment by davidak** [comment]
1.3.6 was released 19 days ago.

https://github.com/evilsocket/opensnitch/releases/tag/v1.3.6

@onny do you want to update your package and create a nixpkgs PR?

**Comment by onny** [comment]
> 1.3.6 was released 19 days ago.
> 
> https://github.com/evilsocket/opensnitch/releases/tag/v1.3.6
> 
> @onny do you want to update your package and create a nixpkgs PR?

 Hm I guess there might be more work to do until this package works :( Dont know when I'll look into this

**Comment by abvbv** [comment]
Looks like it's been added https://github.com/NixOS/nixpkgs/pull/117893.
