### ISSUE TITLE
docker-containers unit options could use lists

### ISSUE THREAD

**Issue by simon-weber** [NixOS/nixpkgs#76620]
**Describe the bug**
The docker-containers systemd services set strings for systemd options that can accept a list, like ExecStopPost and ExecStartPre: https://github.com/NixOS/nixpkgs/blob/59b0ab21e798647c97327a11e46715cc2734210f/nixos/modules/virtualisation/docker-containers.nix#L190

In my case I'd like to append an unrelated poststop task (a sqlite vacuum). If the options were set to lists I could just have my command merged, but because they're strings I need to mkForce and copy in the upstream commands.

**To Reproduce**
Create a config like:
```
    docker-containers.foo = {
      ...
    };
    systemd.services.docker-foo = {
      serviceConfig = {
        ExecStopPost = [ "echo foo" ];
      };
    };
```

This results in an error: "systemd.services.docker-foo.serviceConfig.ExecStopPost has conflicting definitions".

**Expected behavior**
Multiple poststop declarations in the resulting unit, like what happens with `ExecStopPost = [ "echo one" "echo two" ];`

**Additional context**
This is vaguely related to https://github.com/NixOS/nixpkgs/pull/76480, which also has to do with making `docker-containers` more flexible. 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.18-galliumos, GalliumOS, 3.1 (Bismuth)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(simon): `"nixpkgs-20.03pre206486.a8fc904c7c0"`
 - nixpkgs: `/home/simon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - virtualisation
```

**Comment by Atemu** [comment]
I believe `serviceConfig`'s attributes get put into the unit file verbatim.  

This would also be a systemd.services issue, not a Docker one.

Have you tried https://nixos.org/nixos/options.html#systemd.services.%3Cname%3E.prestop?

**Comment by simon-weber** [comment]
I'm not sure it's a systemd issue: it already seems to support using lists, but docker-containers doesn't make use of them.

`preStop` doesn't seem to help. It results in `serviceConfig.ExecStop` being set as well, so causes the same error.

To clarify, I'm proposing something like this:
```diff
# virtualisation/docker-containers.nix
- ExecStopPost = "-${pkgs.docker}/bin/docker rm -f %n";
+ ExecStopPost = [ "-${pkgs.docker}/bin/docker rm -f %n" ]; 
```

That would let docker-containers users who want to append other tasks avoid copying in the upstream config and overriding it:
```diff
# myconfig.nix
    docker-containers.foo = {
      ...
    };
    systemd.services.docker-foo = {
      serviceConfig = {
-       ExecStopPost = pkgs.lib.mkForce [ "-${pkgs.docker}/bin/docker rm -f %n" "my-custom-task" ];
+       ExecStopPost = [ "my-custom-task" ];
      };
    };
```

**Comment by CRTified** [comment]
I stumbled across this issue when trying to add something to `ExecStartPre`.

@simon-weber You are right about `preStop` not being useful, but you solution requires a change in the systemd definition (where I do not know whether it might break something). It also makes the `serviceConfig` section less of a direct mapping between the unit file and the option.

In my opinion, the correct solution would be to move the values for [`ExecStartPre`](https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/virtualisation/docker-containers.nix#L188) and [`ExecStopPost`](https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/virtualisation/docker-containers.nix#L190) to the mergable options [`preStart`](https://nixos.org/nixos/options.html#systemd.services.%3Cname%3E.prestart) and [`postStop`](https://nixos.org/nixos/options.html#systemd.services.%3Cname%3E.postStop).

Note that this fix should not interact with the two other proposed changes https://github.com/NixOS/nixpkgs/pull/77479 and https://github.com/NixOS/nixpkgs/pull/76479.

**Comment by danbst** [comment]
```
    systemd.services.docker-foo = {
      postStop = lib.mkAfter ''
        echo foo
      '';
    };
```
Unfortunately, it is not universal advice, as it won't work if there is already `ExecStopPost` defined.

**Comment by CRTified** [comment]
@danbst `ExecStopPost` is defined for all containers that are created with `docker-containers`, due to https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/docker-containers.nix#L232-L237.

In my opinion, the value for `ExecStartPre` should be moved to `preStart` and `ExecStopPost` to `postStop`. These options allow composing. I'll prepare a pull request to fix this when I have a bit of time (I think it will be ready in ~4-5 hours).
