### ISSUE TITLE
plasma5+xmonad no longer works after nixos/displayManager: introduce defaultSession #53843 

### ISSUE THREAD

**Issue by Kiwi** [NixOS/nixpkgs#76625]
**Describe the bug**

I woke up and tried to unlock my plasma5+xmonad session and it would not let me. Kept saying bad password or w/e. So I went to tty1 and `sudo systemctl restart display-manager.service` which it determined meant I wanted to shutdown. This, surprisingly, is 1. not the bug I'm reporting and 2. not the first time all of that has happened.

real problem: When I rebooted I tried to login to my plasma5+xmonad session from sddm and it was not xmonad... it was kwin (i think)!. The last time I did nixos-upgrade switch I didn't notice because I didn't logout but anyway it told me about deprecated xserver and console settings etc. which I fixed and then switched. As far as I can tell it happens whether I update my config or not. I tried both ways.

I did git bisect with nixos-rebuild -I nixpkgs=~/projects/github/nixpkgs test and trying to login each time and it told me what [I expected](https://gist.github.com/Kiwi/fde1619ecd62ec0722a0b0f5e05bd90c#file-gistfile1-txt)

```
22:10:50 [kiwi@mvp-nixos nixpkgs]$ git bisect bad
8dc5ff7dcfd1c58c32004ffae25e6d31ed83d86c is the first bad commit
commit 8dc5ff7dcfd1c58c32004ffae25e6d31ed83d86c
Author: Jan Tojnar <jtojnar@gmail.com>
Date:   Tue Dec 10 15:10:30 2019 +0100

    nixos/displayManager: deprecate separate options for default wm/dm

    The upstream session files display managers use have no concept of sessions being composed from
    desktop manager and window manager. To be able to set upstream session files as default
    session, we need a single option. Having two different ways to set default session would be confusing,
    though, so we decided to deprecate the old method.

    We also created separate script for each session, just like we already had a separate desktop
    file for each one, and started using displayManager.sessionPackages mechanism to make the
    session handling more uniform.

 nixos/doc/manual/configuration/x-windows.xml       |   3 +-
 nixos/doc/manual/configuration/xfce.xml            |   5 +-
 nixos/doc/manual/release-notes/rl-2003.xml         |  13 ++
 nixos/lib/testing-python.nix                       |   3 +-
 nixos/lib/testing.nix                              |   3 +-
 .../services/x11/desktop-managers/default.nix      |  23 +-
 .../services/x11/desktop-managers/pantheon.nix     |   2 +
 .../x11/display-managers/account-service-util.nix  |  39 ++++
 .../services/x11/display-managers/default.nix      | 231 +++++++++++----------
 .../modules/services/x11/display-managers/gdm.nix  |  62 ++----
 .../x11/display-managers/lightdm-greeters/mini.nix |   5 +-
 .../services/x11/display-managers/lightdm.nix      |  33 +--
 .../modules/services/x11/display-managers/sddm.nix |  16 +-
 .../services/x11/window-managers/default.nix       |  15 +-
 nixos/tests/common/x11.nix                         |   8 +-
 nixos/tests/i3wm.nix                               |   2 +-
 nixos/tests/lightdm.nix                            |   3 +-
 nixos/tests/plasma5.nix                            |   2 +-
 nixos/tests/sddm.nix                               |   6 +-
 nixos/tests/xmonad.nix                             |   4 +-
 20 files changed, 254 insertions(+), 224 deletions(-)
 create mode 100644 nixos/modules/services/x11/display-managers/account-service-util.nix
22:11:49 [kiwi@mvp-nixos nixpkgs]$
```

**To Reproduce**
be me (optional, i hope), use nixos-unstable, launch sddm xmonad+plasma5 session

**Expected behavior**
to be able to use my xmonad keybindings and not kwin which i've never used and don't know how  ;_;

**Screenshots**

**Additional context**
I would format this better but apparently my mouse has decided to move at double time so it is extremely annoying to do anything

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.16, NixOS, 20.03.git.8dc5ff7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213, nixos-1803-18.03.133402.cb0e20d6db9, nixos-1809-18.09.2574.a7e559a5504, nixos-1903-19.03.173676.d1dff0bcd9f, nixos-1909-19.09.1686.69ed29f5f41, nixos-unstable-20.03pre206632.b0bbacb5213"`
 - channels(kiwi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by hedning** [comment]
This should fix it (will make a PR):
```diff
modified   nixos/modules/services/x11/display-managers/default.nix
@@ -380,7 +380,7 @@ in
         wms = filter (s: s.manage == "window") cfg.displayManager.session;
 
         # Script responsible for starting the window manager and the desktop manager.
-        xsession = wm: dm: pkgs.writeScript "xsession" ''
+        xsession = dm: wm: pkgs.writeScript "xsession" ''
           #! ${pkgs.bash}/bin/bash
 
           # Legacy session script used to construct .desktop files from
```

Sorry for the breakage, should've caught that in the review, but didn't.

**Comment by Kiwi** [comment]
Thanks! that works
