### ISSUE TITLE
OpenSC is not reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#76665]
**Describe the bug**
Building the same source code of OpenSC twice does not yield the same result

**To Reproduce**
1. `nix-build '<nixpkgs>' -A opensc --check`

**Expected behavior**
The check succeeds

**Additional context**
This was [fixed upstream](https://github.com/OpenSC/OpenSC/pull/1839) in 0.20.0, released today. I checked that with that version (https://github.com/NixOS/nixpkgs/compare/master...raboof:opensc-0.20.0) it indeed now builds successfully, but I'm not sure how to reliably test that it also still works.

cc @erictapen

**Comment by erictapen** [comment]
> but I'm not sure how to reliably test that it also still works.

Well, it's impossible to prove that software builds reproducible anyway, but I guess the bump is a good step.

Would you mind opening a PR with that changed (needs to be backported) und could I interest you in participating in maintainership of the package?

If you have no time to open a PR I'll do it later in the day.

**Comment by raboof** [comment]
> it's impossible to prove that software builds reproducible anyway

true ;)

> Would you mind opening a PR with that changed

I've opened it against master (#76666)

> (needs to be backported)

Do you mean you also want it as a PR against another branch? (sorry I'm fairly new to Nix)

> could I interest you in participating in maintainership of the package?

Thanks for asking, but I think I have enough on my plate as it is... I'd be happy to do some further testing of this PR if you can point me in the right direction, though.
