### ISSUE TITLE
ATS-extsolve

### ISSUE THREAD

**Issue by sheganinans** [NixOS/nixpkgs#7667]
@shlevy any ideas?

> cd ~/Projects/github/ATS-Postiats-contrib/contrib/libats-/wdblair/prelude/
> patsopt --constraint-export -tc -d TEST/quicksort.dats | patsolve
exit(ATS): unmatched value at run-time:
/tmp/nix-build-ats-extsolve-0pre6a9b752.drv-0/ATS-Postiats-contrib-6a9b752efb8af1e4f77213f9e81fc2b7fa050877/projects/MEDIUM/ATS-extsolve/parsing/parsing_c3nstr.dats: 479(line=37, offs=5) -- 536(line=38, offs=41)

**Comment by shlevy** [comment]
Looks like unexpected JSON format: https://github.com/githwxi/ATS-Postiats-contrib/blob/6a9b752efb8af1e4f77213f9e81fc2b7fa050877/projects/MEDIUM/ATS-extsolve/parsing/parsing_c3nstr.dats#L37

This is an upstream issue, not a nixpkgs one.

**Comment by sheganinans** [comment]
Thanks!

**Comment by sheganinans** [comment]
Just would like to mention that atx-extsolve will be merged into ats in a week or two. Hongwei is working on it: githwxi/ATS-Postiats-contrib#35

**Comment by shlevy** [comment]
@sheganinans Fixed now in master by the way.
