### ISSUE TITLE
sudo nix-channel --update fails on recent unstable-channel

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#7669]
It seems like I hit an issue where I can't upgrade my system on the unstable channel anymore. ```sudo nix-channel --update``` or ```sudo nixos-rebuild ... --upgrade``` fails with:

```
downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable/nixos-15.05pre61665.4c01e6d/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
unpacking channels...
/nix/store/j7ghngyylfkl64xx1js6f2dfix48fw7g-xz-5.2.0/bin/xz: (stdin): File format not recognized
/nix/store/s16y2pk8lljsm37b55h2dsl6gpbsb62g-gnutar-1.27.1/bin/tar: This does not look like a tar archive
/nix/store/s16y2pk8lljsm37b55h2dsl6gpbsb62g-gnutar-1.27.1/bin/tar: Exiting with failure status due to previous errors
builder for ‘/nix/store/35lmnri499d3kifqbzaz35hz067zfwsv-nixos-15.05pre61665.4c01e6d.drv’ failed with exit code 2
```

This is on ```15.05pre61665.4c01e6d (Dingo)``` but as far as I know, @1126 hit the issue on earlier channels too.

If this is fixed in master already, can someone please document here how to get out of this? I can rebuild from git just fine, but we should document issues like this.

**Comment by jbgi** [comment]
I'm also in the same situation...

**Comment by domenkozar** [comment]
Could be related to https://github.com/NixOS/nix/commit/8a84bd8c8bda1e4c6764c10ecdef9d74e4884800, what's the output of `nix-env --version`?

**Comment by domenkozar** [comment]
cc @copumpkin

**Comment by vcunat** [comment]
I can't reproduce this
```
$ nix-channel --update
downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable/nixos-15.05pre61665.4c01e6d/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5592k  100 5592k    0     0  6484k      0 --:--:-- --:--:-- --:--:-- 6487k
unpacking channels...
created 7 symlinks in user environment
```
```
$ nix-env --version
nix-env (Nix) 1.8
```

**Comment by domenkozar** [comment]
Use Nix unstable

**Comment by vcunat** [comment]
So a nix issue, most likely, not nixpkgs (but we can keep it open here IMHO).

**Comment by globin** [comment]
I had this earlier to, seems it was an intermediate issue with a broken tarball.

**Comment by the-kenny** [comment]
@globin we had that for at least a week at the office. I just haven't experienced it locally.

@domenkozar Will try that, thanks!

**Comment by the-kenny** [comment]
@vcunat is this with ```sudo``` (or just as root)?

**Comment by the-kenny** [comment]
No luck with nixUnstable either:

```
% sudo nix-channel --update 
downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable/nixos-15.05pre61665.4c01e6d/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
unpacking channels...
/nix/store/j7ghngyylfkl64xx1js6f2dfix48fw7g-xz-5.2.0/bin/xz: (stdin): File format not recognized
/nix/store/s16y2pk8lljsm37b55h2dsl6gpbsb62g-gnutar-1.27.1/bin/tar: This does not look like a tar archive
/nix/store/s16y2pk8lljsm37b55h2dsl6gpbsb62g-gnutar-1.27.1/bin/tar: Exiting with failure status due to previous errors
builder for ‘/nix/store/d7a7whwvsdwqxqqmfv8ka727y7hdw5l0-nixos-15.05pre61665.4c01e6d.drv’ failed with exit code 2
error: build of ‘/nix/store/d7a7whwvsdwqxqqmfv8ka727y7hdw5l0-nixos-15.05pre61665.4c01e6d.drv’ failed
cannot unpack the channels at /run/current-system/sw/bin/nix-channel line 150.
```

```
% sudo nix-channel --version
nix-channel (Nix) 1.9pre4100_4bbcfaf
```

**Comment by domenkozar** [comment]
I'm saying this might be a bug in nix unstable, can you reproduce with nix
stable?

**Comment by copumpkin** [comment]
It seems most likely related to the `nix-channel` tarball change I made. In your `~/.nix-channels` files, do you have a url and a name per channel or just a url? I didn't even realize the latter was possible until recently so that might be the culprit.

I'm going to be traveling all day so will have limited internet, but will try to look into the issue whenever I can. If necessary, I won't be heartbroken if someone reverts the change until we can sort it out.

**Comment by vcunat** [comment]
@the-kenny: same for me when run with sudo.

**Comment by the-kenny** [comment]
@domenkozar I see that with nix 1.8 and nix 1.9. 

@copumpkin 

```
 % sudo cat /root/.nix-channels
https://nixos.org/channels/nixos-unstable nixos
```

Don't worry about time - I can easily rebuild from git - but we really should document this issue as people can easily get stuck right now.

**Comment by copumpkin** [comment]
Oh wait, `4bbcfaf` doesn't contain my changes in it, so I was wrong. I can repro the issue, but it's not my changes and I can't see anything obvious wrong with it.

**Comment by dezgeg** [comment]
I started getting this and did some debugging: clearing `/nix/var/nix/channel-cache/` makes it work.

**Comment by dezgeg** [comment]
Specifically, I think something has changed in `curl` such that `nix-prefetch-url` stops working: it does a curl call like

````
curl https://nixos.org/releases/nixos/unstable/nixos-15.05pre61665.4c01e6d/nixexprs.tar.xz -o /tmp/nixexprs.tar.xz --fail --location --max-redirs 20 --disable-epsv --cookie-jar /tmp/nix-prefetch-url.1C6gc3/cookies --remote-time --time-cond /nix/var/nix/channel-cache//1m9hxhkqprm4jy5la9jgxy59hgxx42lr8lypn1gqp4iaicqlqhzz.stamp
````

and assumes that if curl didn't create `/tmp/nixexprs.tar.xz`, then the file hasn't been changed on the server. But apparently new versions of curl always create the input file (which is now zero bytes, which causes the error from 'xz').

**Comment by the-kenny** [comment]
I can confirm clearing ```/nix/var/nix/channel-cache``` works. Can we please document this as news and/or in the manual so people on the current channel release aren't caught by this?

**Comment by copumpkin** [comment]
More than news it seems like a bug somewhere that needs fixing. Do any of
you have an idea as to what is actually breaking in the channel-cache?

**Comment by dezgeg** [comment]
Yes, clearing the channel cache is a workaround that would have to be done each time `nix-channel --update` is run.

The actual root cause of the bug is in my comment above: https://github.com/NixOS/nixpkgs/issues/7669#issuecomment-98805298.

**Comment by charles-cooper** [comment]
Just wanted to add that I have been having the same problem since yesterday, funny thing is it works fine for non-root but breaks on root

**Comment by surr** [comment]
This is a curl issue https://github.com/bagder/curl/issues/237
Upgrading to 7.42.1 should help.

**Comment by domenkozar** [comment]
We already have curl 7.42.1 in master, channel should update anytime now.

**Comment by vcunat** [comment]
I'm assuming it's fixed then.

**Comment by GuillaumeSeren** [comment]
Got the same issue here, fixed by cleaning the content of '/nix/var/nix/channel-cache/' as mentioned before in this issue.

But the issue back again if you try to 'nix-channel --update'.

**Comment by Twey** [comment]
Similar issue here with newer versions, even after clearing channel cache:

    [twey@othala:~]$ sudo rm /nix/var/nix/channel-cache/*
    
    [twey@othala:~]$ sudo nix-channel --update
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  5724  100  5724    0     0  56.8M      0 --:--:-- --:--:-- --:--:-- 56.8M
    these derivations will be built:
      /nix/store/aba411gcwjqcb0gk8r5n2fvh5pv723vf-nixos-15.06pre64030.e1af50c.drv
    building path(s) ‘/nix/store/r9qkkfiknfa7ksw1lladbx0kywjcqaz7-nixos-15.06pre64030.e1af50c’
    bzip2: (stdin) is not a bzip2 file.
    /nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: This does not look like a tar archive
    /nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: Exiting with failure status due to previous errors
    builder for ‘/nix/store/aba411gcwjqcb0gk8r5n2fvh5pv723vf-nixos-15.06pre64030.e1af50c.drv’ failed with exit code 2
    error: build of ‘/nix/store/aba411gcwjqcb0gk8r5n2fvh5pv723vf-nixos-15.06pre64030.e1af50c.drv’ failed
    downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable/nixos-15.06pre64030.e1af50c//nixexprs.tar.xz’...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 5535k  100 5535k    0     0  2282k      0  0:00:02  0:00:02 --:--:-- 2282k
    unpacking channels...
    
    [twey@othala:~]$ sudo nix-channel --version
    nix-channel (Nix) 1.9pre4153_b64988b
    
    [twey@othala:~]$ sudo curl --version
    curl 7.42.1 (x86_64-unknown-linux-gnu) libcurl/7.42.1 OpenSSL/1.0.1m zlib/1.2.8 libssh2/1.5.0
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
    Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by domenkozar** [comment]
@Twey could you try running nix-channel --update as root?

**Comment by Twey** [comment]
As opposed to via sudo?  Same outcome (also after clearing /nix/var/nix/channel-cache):

    [root@othala:/home/twey]# nix-channel --update
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  5724  100  5724    0     0  38.1M      0 --:--:-- --:--:-- --:--:-- 38.1M
    these derivations will be built:
      /nix/store/aba411gcwjqcb0gk8r5n2fvh5pv723vf-nixos-15.06pre64030.e1af50c.drv
    building path(s) ‘/nix/store/r9qkkfiknfa7ksw1lladbx0kywjcqaz7-nixos-15.06pre64030.e1af50c’
    bzip2: (stdin) is not a bzip2 file.
    /nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: This does not look like a tar archive
    /nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: Exiting with failure status due to previous errors
    builder for ‘/nix/store/aba411gcwjqcb0gk8r5n2fvh5pv723vf-nixos-15.06pre64030.e1af50c.drv’ failed with exit code 2
    error: build of ‘/nix/store/aba411gcwjqcb0gk8r5n2fvh5pv723vf-nixos-15.06pre64030.e1af50c.drv’ failed
    downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable/nixos-15.06pre64030.e1af50c//nixexprs.tar.xz’...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 5535k  100 5535k    0     0  2226k      0  0:00:02  0:00:02 --:--:-- 2227k
    unpacking channels...

**Comment by hiberno** [comment]
I can confirm this. 

```sh
~ » sudo nix-channel --update nixos
[sudo] password for hiberno: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3157  100  3157    0     0  10.3M      0 --:--:-- --:--:-- --:--:-- 10.3M
these derivations will be built:
  /nix/store/z11rma1jxq8fdxlc29ajycbncr8215ma-nixos-15.06pre63074.6276eba.drv
building path(s) ‘/nix/store/yl34z2cvazccm8r4syrdx1bbysim14y6-nixos-15.06pre63074.6276eba’
bzip2: (stdin) is not a bzip2 file.
/nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: This does not look like a tar archive
/nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: Exiting with failure status due to previous errors
builder for ‘/nix/store/z11rma1jxq8fdxlc29ajycbncr8215ma-nixos-15.06pre63074.6276eba.drv’ failed with exit code 2
error: build of ‘/nix/store/z11rma1jxq8fdxlc29ajycbncr8215ma-nixos-15.06pre63074.6276eba.drv’ failed
downloading Nix expressions from ‘http://nixos.org/releases/nixos/unstable-small/nixos-15.06pre63074.6276eba//nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
unpacking channels...
```

I am on 

```sh
~ » nixos-version
15.06.git.da7748a (Dingo)
```

**Comment by edolstra** [comment]
@hiberno I believe this is fixed by NixOS/nix@c48617671df2a1b894f802bf78f97e9c9dd7cf27. Note that there is no actual problem here, nix-channel still succeeds.

**Comment by hiberno** [comment]
@edolstra That's correct. The actual update still succeeds. Thanks for the heads up!

**Comment by Profpatsch** [comment]
This error is on the current `nixos-unstable` branch, so no updating there.

This is a common problem with nixos-unstable, there are no hotfixes and it is not updated until all tests pass. That took more than a month last time.
Shouldn’t it be easy to do hotfixes on unstable by simply cherry-picking commits like https://github.com/NixOS/nix/commit/c48617671df2a1b894f802bf78f97e9c9dd7cf27 ?

**Comment by magnetophon** [comment]
I seem to have the same issue:
```
root at borknix-rt in ~bart 
$ mv /nix/var/nix/channel-cache /nix/var/nix/channel-cache.old

root at borknix-rt in ~bart 
$ nix-channel --update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5724  100  5724    0     0  62.7M      0 --:--:-- --:--:-- --:--:-- 62.7M
these derivations will be built:
  /nix/store/hbdjbnmvydgggikpcfpak30f9a6hagw6-nixos-15.06pre64423.4e5e441.drv
building path(s) ‘/nix/store/5jsk0vllzakakyxz7qjql55ggks416ys-nixos-15.06pre64423.4e5e441’
bzip2: (stdin) is not a bzip2 file.
/nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: This does not look like a tar archive
/nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar: Exiting with failure status due to previous errors
builder for ‘/nix/store/hbdjbnmvydgggikpcfpak30f9a6hagw6-nixos-15.06pre64423.4e5e441.drv’ failed with exit code 2
error: build of ‘/nix/store/hbdjbnmvydgggikpcfpak30f9a6hagw6-nixos-15.06pre64423.4e5e441.drv’ failed
downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable/nixos-15.06pre64423.4e5e441//nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5580k  100 5580k    0     0   107k      0  0:00:52  0:00:52 --:--:--  195k
unpacking channels...
```
I probably misunderstood @edolstra, cause my channel seems to be not upgraded.
So when I subsequently do:
```
$ nixos-rebuild switch -I nixpkgs=/home/bart/source/nixpkgs
```
I get:
```
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
```
I am on
```
15.06.git.93a8515 (Dingo)
```

**Comment by magnetophon** [comment]
When I run a vanila
```
nixos-rebuild switch
```
all seems well.
The source tree I was referencing above was not in sync with my channel, so I guess that's where the problem was.
