### ISSUE TITLE
WPS-Office isn't working

### ISSUE THREAD

**Issue by Th0rgal** [NixOS/nixpkgs#76704]
**Describe the bug**
I tried to install WPS-Office from this derivation: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/wpsoffice/default.nix through home-manager
And I got this error:
0curl: (6) Could not resolve host: kdl.cc.ksosoft.com

**To Reproduce**
Try to install wpsoffice

**Comment by veprbl** [comment]
@Ninlives

**Comment by Ninlives** [comment]
Hi @Th0rgal, looks like wpsoffice has changed their host for downloading, I've updated the url and has in https://github.com/NixOS/nixpkgs/pull/76731
