### ISSUE TITLE
pam_time.so is useless in the default NixOS package

### ISSUE THREAD

**Issue by zeonin** [NixOS/nixpkgs#76713]
**Describe the bug**
pam_time only uses the example config file in NixOS and is useless without overriding and rebuilding almost every other package.

**To Reproduce**
1. Extend `<nixos/modules/security/pam.nix>` to add `account required pam_time.so` to all pam.d config files.
2. Create `/etc/security/time.conf` and add `sshd ; * ; user ; !Al0000-2400`.
3. Rebuild and attempt to ssh as `user` into the machine
4. Successfully log in.

**Expected behavior**
In the example above, I would expect ssh to forbid `user` from logging in at any time.

**Additional context**
Ideally, upstream linux-pam would allow pam_time to be configured at run time similarly to pam_env. However, I would still expect to be able to use pam_time without overriding the linux-pam package to manually change the location of time.conf.

In the current setup, pam_time only ever looks at the example time.conf file in the linux-pam package which makes it effectively useless. If the package is overridden to use a different location for that one file, a massive number of packages then needs to be rebuilt manually as they in one way or another depend on pam.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.11, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213"`
 - channels(locus): `"nix-1809-18.09.2574.a7e559a5504"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matthewbauer** [comment]
It looks like we may just need to pass `--sysconfdir=/etc` to linux-pam.

**Comment by matthewbauer** [comment]
Try this PR:

https://github.com/NixOS/nixpkgs/pull/76718
