### ISSUE TITLE
ffmpeg 0.10.15 and 2.5.4 can't find librtmp

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#7671]
This issue started with the 1st of May commits. Maybe 1d150637683b7cfcfcc3bfe8d4b4dda2afadb735 is the culprit.

Please see this [log](https://headcounter.org/hydra/build/649541/nixlog/58/raw) and this [log](https://headcounter.org/hydra/build/649541/nixlog/53/raw) for more details.

Thanks.

**Comment by aristidb** [comment]
I'll commit a fix shortly

**Comment by aristidb** [comment]
@wkennington
