### ISSUE TITLE
bandwhich

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#76750]
**Project description**
`bandwhich` is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname.

**Metadata**

* homepage URL: https://github.com/imsnif/bandwhich
* source URL: https://github.com/imsnif/bandwhich
* license: MIT
* platforms: unix

**Comment by Ma27** [comment]
Added quite recently in #76689

**Comment by matthew-piziak** [comment]
Oh, I missed that. Thanks @Ma27!
