### ISSUE TITLE
soapysdr: Python binding cannot be used

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#76808]
The soapysdr package contains a Python binding, but it is not possible to use it normally (e.g. via ``nix-shell -p soapysdr`` or ``python3.withPackages(ps: [ps.soapysdr])``) because it is not registered as a Python package in nixpkgs.

I am not sure what is the proper way of handling this case, since soapysdr is both a regular library and a Python package, and nixpkgs makes a distinction between the two. A workaround is to add ``${pkgs.soapysdr}/lib/python3.7/site-packages`` to ``PYTHONPATH``.

Cc @markuskowa @bennofs @FRidh

**Comment by FRidh** [comment]
See the section "15.17.2.2.4. toPythonModule function" in the Nixpkgs manual.

**Comment by sbourdeauducq** [comment]
Okay, I thought that ``toPythonModule`` was only supposed to be used inside derivations.
