### ISSUE TITLE
thunderbird: build fails if enableOfficialBranding = true

### ISSUE THREAD

**Issue by puzzlewolf** [NixOS/nixpkgs#76807]
**Describe the bug**
`thunderbird` does not build with `enableOfficialBranding = true`.

**To Reproduce**
1. in `configuration.nix`, use 
```
environment.systemPackages = with pkgs; [
  (thunderbird.override { enableOfficialBranding = true; })
];
``` 

2. observe rebuild failing with:
```
$ nixos-rebuild switch                                               ~
building Nix...
building the system configuration...
error: attribute 'proprietary' missing, at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/applications/networking/mailreaders/thunderbird/default.nix:203:38
(use '--show-trace' to show detailed location information)

```

**Expected behavior**
The build should go through, producing a thunderbird with normal logos.

**Additional context**
Maybe related to #75904.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 19.09.1686.69ed29f5f41 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: thunderbird
# a list of nixos modules affected by the problem
module: 
```

**Comment by andersk** [comment]
Although I haven’t tried it myself, at least this particular issue was removed in commit 8b8458ade5e0694b60cbecd7a7811d5fb2c11b77 (#75328).

**Comment by mkg20001** [comment]
Unstable seems to work

**Comment by vcunat** [comment]
Seems to work on all currently supported branches (including 19.09).
