### ISSUE TITLE
callgrind_annotate doesn't work

### ISSUE THREAD

**Issue by heca-project** [NixOS/nixpkgs#76800]
**Describe the bug**

`callgrind_annotate` doesn't work.

**To Reproduce**
1. `nix-shell -p valgrind --command callgrind_annotate`

**Expected behavior**
callgrind should work.

**Screenshots**

Instead I get `bash: /nix/store/7vwxxd11n9a86nxsc3mwly48whf8xdl0-valgrind-3.15.0/bin/callgrind_annotate: /usr/bin/perl: bad interpreter: No such file or directory`

**Additional context**

I noticed that `head /nix/store/7vwxxd11n9a86nxsc3mwly48whf8xdl0-valgrind-3.15.0/bin/callgrind_annotate` outputs

```
#! /usr/bin/perl -w
##--------------------------------------------------------------------##
##--- The cache simulation framework: instrumentation, recording   ---##
##--- and results printing.                                        ---##
##---                                           callgrind_annotate ---##
##--------------------------------------------------------------------##

#  This file is part of Callgrind, a cache-simulator and call graph
#  tracer built on Valgrind.
#
```

That `/usr/bin/perl` should be patched out.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 19.09.1693.eab4ee0c27c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1693.eab4ee0c27c, nixos-unstable-19.09pre189979.249b4ad9428, nixpkgs, nixpkgs-unstable, nixpos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by abathur** [comment]
This can be closed. I can invoke the command without error; it looks like it was fixed in https://github.com/NixOS/nixpkgs/commit/d22b4859a16a3f3e01cf3e6dfaeefc4424ac00cb and included in the 20.03 release.
