### ISSUE TITLE
TeXLive 2019 .enc vs. pdftex.map inconsistency with ebgaramond

### ISSUE THREAD

**Issue by mikesperber** [NixOS/nixpkgs#76826]
**Describe the bug**
The .enc files distributed with the ebgaramond package are inconsistent with those mentioned in `pdftex.map`.

**To Reproduce**
1. pdflatex this:

    \documentclass{article}

    \usepackage{ebgaramond}

    \begin{document}
    foo
    \end{document}

**Expected behavior**
Produces PDF output.

**Screenshots**
Instead produces:

    !pdfTeX error: /Users/sperber/.nix-profile/bin/pdflatex (file ebgm_nxqm35.enc): cannot open encoding file for reading
     ==> Fatal error occurred, no output PDF file produced!

**Additional context**

In today's Nix packages from Git.

The `ebgm_nxqm35.enc` file is mentioned in `pdftex.map`:

    EBGaramond-Bold-osf-ot1 EBGaramond-Bold " AutoEnc_nxqm357krn5asjgj4l52s7fwme ReEncodeFont " <[ebgm_nxqm35.enc <EBGaramond-Bold.pfb

However, `EBGaramond.map` has this:

    EBGaramond-Bold-osf-ot1 EBGaramond-Bold "AutoEnc_fc2mbn3xtktdfxsxdv3khcb5dh ReEncodeFont" <[ebgm_fc2mbn.enc <EBGaramond-Bold.pfb

I'd be happy to help formulate a patch here, but need handholding as to where to start looking how `pdftex.map` is generated.

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(sperber): `"nixpkgs-16.03pre70724.d4bebcb"`
 - nixpkgs: `/Users/sperber/build/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
> I'd be happy to help formulate a patch here, but need handholding as to where to start looking how `pdftex.map` is generated.

All files are shipped as is, the only modification is done in the `combine` function [1]. I would first try commenting out the call to the updmap.

[1] https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive/combine.nix

**Comment by mikesperber** [comment]
Thanks!

So it turns out that the `--syncwithtrees` flag makes `updmap` not re-generate the map file. (I'm unsure from the documentation what exactly this flag is supposed to do.) Removing it makes it work correctly, and that generates font maps with many other changes, too.

Pull request forthcoming.
