### ISSUE TITLE
NIX_GHC_DOCDIR not set properly

### ISSUE THREAD

**Issue by GuillaumeDesforges** [NixOS/nixpkgs#76837]
**Describe the bug**
When creating a Haskell development environment like this:
```
# shell.nix
{ pkgs ? import <nixpkgs> { } }:

let
  all-hies = import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {};
  hie = all-hies.selection { selector = p: { inherit (p) ghc865; }; };

in
  pkgs.haskellPackages.shellFor {
    buildInputs = with pkgs; [
      hie
      cabal-install
    ];

    packages = (hp: with hp; [ gloss ]);
    withHoogle = true;
  }
```

with `withHoogle = true`, the doc is generated in `${ghcEnv}/share/doc/hoogle/html`, however the `NIX_GHC_DOCDIR` is set to `${ghcEnv}/share/doc/ghc/html`.
The former does not even exist (no such file or directory error on `ls $NIX_GHC_DOCDIR`).

See this line:

https://github.com/NixOS/nixpkgs/blob/ff882242ea70502696b551c7c9bfb933a250c60f/pkgs/development/haskell-modules/make-package-set.nix#L322

Note that I have seen https://github.com/NixOS/nixpkgs/issues/20730 and think that it is a different issue.

This issue prevents from using HIE in a nix-shell. See https://discourse.nixos.org/t/cant-make-hie-work-on-vs-code-with-nix/5277/

**To Reproduce**
Use previous `shell.nix`
```
nix-shell --run "ls $NIX_GHC_DOCDIR"
nix-shell --run "whateverfolderghcisin/share/doc/hoogle"
```

**Expected behavior**
`nix-shell --run "ls $NIX_GHC_DOCDIR"` should point to `${ghcEnv}/share/doc/hoogle/html`

**Metadata**
```
% nix run nixpkgs.nix-info -c nix-info -m                                                                                                                                                                                                  ~
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 19.09.1686.69ed29f5f41 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(arsleust): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by matthewbauer** [comment]
I think https://github.com/NixOS/nixpkgs/pull/76842 fixes this.

**Comment by snawaz** [comment]
And while we fix this, I hope we also set another variable `HIE_HOOGLE_DATABASE` to `${ghcEnv}/share/doc/hoogle/default.hoo` (as required by [`haskell-ide-engine`][1] so that it works out of the box without any user settings.


[1]: https://github.com/haskell/haskell-ide-engine#docs-on-hovercompletion

**Comment by sternenseemann** [comment]
Is there a need for `HIE_HOOGLE_DATABASE` or similar today with HLS?

**Comment by maralorn** [comment]
HLS has no hoogle support, yet.
