### ISSUE TITLE
Molotov

### ISSUE THREAD

**Issue by eoli3n** [NixOS/nixpkgs#76849]
**Project description**
A french TV wrapper

**Metadata**

* homepage URL: https://www.molotov.tv/
* source URL: appimage package only : https://www.molotov.tv/download
* license: no idea
* platforms: linux

**Comment by eoli3n** [comment]
nobody ?

**Comment by apeyroux** [comment]
My personal package : https://github.com/apeyroux/molotov.nix

**Comment by Narice** [comment]
could you make a pull request for it @apeyroux?
