### ISSUE TITLE
Cannot connect to Nix store via SSH

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#76860]
**Describe the bug**
I'm following the instructions in: https://nixos.org/nix/manual/#ssec-ssh-substituter. Namely, 
```
nix.sshServe.enable = true;
nix.sshServe.keys = [ "ssh-dss AAAAB3NzaC1k... bob@example.org" ];
```

I've verified that I can successfully do `ssh nix-ssh@hydra.tylerbenster.com`, and this shows the public key authentication when monitored by `journalctl -u sshd -f`on server. However, `nix-env -i hello --substituters ssh://nix-ssh@hydra.tylerbenster.com` fails with:
```
error: cannot connect to 'nix-ssh@hydra.tylerbenster.com'
```
I've added `trustedBinaryCaches` and `binaryCachePublicKeys` in nix.conf on client for what it's worth. I've also tried setting `nix.requireSignedBinaryCaches = false;`, or using `root` instead of `nix-ssh`, but nothing has worked.

It appears that for some reason, `nix-env -i hello --substituters ssh://nix-ssh@hydra.tylerbenster.com` is not using my user's public key, as monitored by `journalctl` on server. As such, I think something may be missing from the manual.

Any ideas what may be wrong?

**Comment by tbenst** [comment]
Without changing anything, the problem resolved itself overnight. I did manually run `nix-store --serve` as root one time--not sure if this contributed.

**Comment by wamserma** [comment]
I have the same issue. When running
```
nixos-rebuild switch --upgrade --option extra-binary-caches ssh://nix-ssh@server
```

store paths are copied, but then client authentication somehow switches from publickey to keyboard-interactive (can be seen from journalctl)

```
copying path '/nix/store/6ibal5l8y78z2k24yiic6xvsrxq3yx6g-nix-2.3.1' from 'ssh://nix-ssh@server'...
building '/nix/store/9xjpxy3y98rri8zkcpcn7qisyc87czxd-nixos-rebuild.drv'...
building Nix...
building the system configuration...
error (ignored): cannot connect to 'nix-ssh@server'
error: cannot connect to 'nix-ssh@server'
```

Server is 19.09 (up-to-date), tested clients were 19.03 and 19.09

**Comment by tbenst** [comment]
@wamserma I also noticed that running as root first was useful for adding to root known-hosts and then worked from user space

**Comment by wamserma** [comment]
@tbenst for me it is not a SSH issue per se - nix-build is is copying stuff via ssh as expected.

To me it seems as if this call to `nix-build`:
https://github.com/NixOS/nixpkgs/blob/82875a20ba444110396f95537b18247898e40e22/nixos/modules/installer/tools/nixos-rebuild.sh#L147
should be prepended with `NIX_SSHOPTS=$SSH_OPTS `

But given that `nixos-rebuild` calls an updated version of itself before it reaches this line, hacking/testing here is not trivial.

**Comment by erikarvstedt** [comment]
What solved `error: cannot connect to 'myhost'` for me was to once run nix-build as root and then to confirm to add `myhost` to root's `known-hosts`.
 `sudo nix-build ... --option extra-substituters ssh://myhost`
