### ISSUE TITLE
mismatched sha256 code of moderntimeline.nix (14.12.648.c7f7f12 (Caterpillar))

### ISSUE THREAD

**Issue by shen390s** [NixOS/nixpkgs#7686]
1. nixos version
[root@pc13x:~/.nix-defexpr/channels/nixos]# nixos-version 
14.12.648.c7f7f12 (Caterpillar)

2. reproduce of problem
[root@pc13x:~/.nix-defexpr/channels/nixos]# nix-env -i texlive-full 
installing ‘texlive-full’
these derivations will be built:
  /nix/store/ydr4isx01gmncjx996n7mvblrv7pgwsn-moderntimeline.zip.drv
  /nix/store/mjv0b1d80yf65b7gkg7c2gcvb74kxm28-moderntimeline-0.7.drv
  /nix/store/0kf3cckq9qizlfmrzmhnxm6knd8ya1as-TeXLive-linkdir.drv
building path(s) ‘/nix/store/rw04h4i99w8816y4ihjw7l7fhq33i3cr-moderntimeline.zip’

trying http://www.ctan.org/tex-archive/macros/latex/contrib/moderntimeline.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   353  100   353    0     0    171      0  0:00:02  0:00:02 --:--:--     0
100  177k  100  177k    0     0  43998      0  0:00:04  0:00:04 --:--:--  159k
output path ‘/nix/store/rw04h4i99w8816y4ihjw7l7fhq33i3cr-moderntimeline.zip’ should have sha256 hash ‘0dxwybanj7qvbr69wgsllha1brq6qjsnjfff6nw4r3nijzvvh876’, instead has ‘0y2m0qd0izrfjcwrmf3nvzkqmrhkdhzbv29s4c0knksdnfgcchc8’
cannot build derivation ‘/nix/store/mjv0b1d80yf65b7gkg7c2gcvb74kxm28-moderntimeline-0.7.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/0kf3cckq9qizlfmrzmhnxm6knd8ya1as-TeXLive-linkdir.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/0kf3cckq9qizlfmrzmhnxm6knd8ya1as-TeXLive-linkdir.drv’ failed

**Comment by rbvermaa** [comment]
Fixed by 62b4419
