### ISSUE TITLE
python3Packages.pyopenssl fails to build

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#76879]
**Describe the bug**
```
nix-build -A python3Packages.pyopenssl --check
```

Apparently the build did succeed on Hydra.

nixpkgs at c4f6aff9dd318a792461f6f42733a38ea60c9a49

cc @knedlsepp

**Comment by FRidh** [comment]
https://hydra.nixos.org/build/109352116

**Comment by knedlsepp** [comment]
@FRidh Thx for pinging me on this.

**Comment by thefloweringash** [comment]
Looks like https://github.com/pyca/pyopenssl/issues/735. There's a patch linked to the issue.

**Comment by FRidh** [comment]
Fix is in staging-next.

**Comment by nh2** [comment]
My CI also got red due to this: https://buildkite.com/nh2/static-haskell-nix/builds/220
