### ISSUE TITLE
Flatpak TLS/SSL (gnutls) problem?

### ISSUE THREAD

**Issue by piotr-szegda** [NixOS/nixpkgs#76884]
**Describe the bug**

I installed GameHub flatpak but when I try connect to got error:

> /lib/libc.so.6: version `GLIBC_2.25' not found (required by /nix/store/624yy06ykz4wfn7n8msqmhbl5hsiizjw-gnutls-3.6.11.1/lib/libidinous.so.30)
> Failed to load module: /nix/store/lknqs5q1nsvn9j79467yjwxcapcqicmz-glib-networking-2.60.3/lib/gio/modules/libgiognutls.so
> 

I don't have this problem on Arch so it is probably NixOS Flatpak package problem.

**To Reproduce**
1. Install Flapak
2. Install last GameHub flatpak from https://github.com/tkashkin/GameHub/releases (I used  0.15.0-18-dev )
3. Try use GOG Connect

**Expected behavior**

Should load GOG logging screen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/977500/71730386-e9475080-2e39-11ea-9305-2b3774f21724.png)

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 nix-shell -p  'nix-info' --run 'nix-info -m' '<nixpkgs>'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 19.09.1748.ad1e1af5ad3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.09.1748.ad1e1af5ad3"`
 - channels(piotrek): `"home-manager, nixos_unstable-20.03pre207234.ec29bb50bf4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by matthewbauer** [comment]
Does the flatpak contain a libgiognutls version?

**Comment by piotr-szegda** [comment]
I don't see it. Probably app is broken and using lib from system. Sorry for problem.

**Comment by matthewbauer** [comment]
It is surprising it would work on Arch given they're probably on the same Glibc version as us.

**Comment by piotr-szegda** [comment]
I reported problem to package creator her https://github.com/tkashkin/GameHub/issues/332. But for now it seem to not be a NixOS flatpak problem.

**Comment by matthewbauer** [comment]
You may also want to try unsetting XDG_DATA_DIRS, LD_LIBRARY_PATH, or GIO_EXTRA_MODULES.

**Comment by piotr-szegda** [comment]
export XDG_DATA_DIRS = 
export LD_LIBRARY_PATH =
export GIO_EXTRA_MODULES =
Don't solve this problem.
Maybe filesystem=host on flatpak manifest is source of problem?
