### ISSUE TITLE
[HaskellNG] Document HaskellNG

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#7688]
There is basically no documentation about haskell-ng at the moment.

What is needed:

1. In-code reasoning about how it works internally (I don’t know how much there is)
2. API- and Function Documentation (where should that go? btw. there should be a nixdocs (read: haddock for nix) soon)
3. Tutorials
    - on the wiki
    - in the language section of the nixpkgs manual

**Comment by peti** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/4941.

**Comment by Profpatsch** [comment]
@peti Superset of #4941.
