### ISSUE TITLE
Incorrect example in builtinsreadDir path in Nix Package Manager Guide (Version 1.9pre4103_1f795f9)

### ISSUE THREAD

**Issue by shen390s** [NixOS/nixpkgs#7690]
builtins.readDirpath Returnthecontentsofthedirectorypathasasetmappingdirectoryentriestothecorresponding file type. For instance, if directory A contains a regular file B and another directory C, then builtins.readDir ./A will return the set
{ A = "regular"; B = "directory"; }
The possible values for the file type are "regular", "directory", "symlink" and "unknown".

The result should be:
{ B = "regular"; C = "directory"; }

**Comment by joachifm** [comment]
Please submit a pull request
