### ISSUE TITLE
Documenting Nix attributes in source files

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#7692]
Edit: I am not working on this, this is a proposal.

I propose to integrate API-documentation in Nixexprs, as to be able to write any sensible programmer-facing documentation at all.

I have a few ideas from my beginner-perspective, though I am probably simplifying the issue.

As far as I see it we have attributes as basic semantic building blocks. Those are anything from nullary to n-ary, or 1-ary if we take currying into account. Since they follow a simple definition scheme, it should be not hard to find a recursive strategy on how to handle documenting them.

There could be a haddock-like approach where there is a third-party program that parses special commands and generates documentation, but I think with nixexprs we can do better than that and store it directly as metainformation. That way it can even be used by tools like `nix-repl`.
A syntactic sugar version would be a haddock-like syntax built into the parser that is then stored as metainformation.

Example (syntax of course subject to debate):

``` nix
# | The actual default version of the haskellNG packages
haskellngPackages = haskell-ng.packages.ghc784.override { … }

# | My funny lambda function
myLambda =
  # ^ because it’s super it takes that as first argument
  super:
  # ^ give it packages and a name or anything really. Will use it, promise.
  { pkgs, name, … }:
    …
```

A thing that comes to mind with the aliases that are often defined and the propagation of attributes through re-definition is that it should be possible to display the inherited documentation, too.

Edit:
It might make sense to be able to document single attributes from input attrsets, too. I’m thinking about functions like [this one](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/default.nix#L84) where differences between e.g. `buildInputs` and `nativeBuildInputs` are not obvious. (Note that they are in fact documented, but [several lines down](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/default.nix#L143), between implementation noise; this took a rather long time to find).

**Comment by Profpatsch** [comment]
Probably better if I throw that to the ML.

**Comment by lethalman** [comment]
I hate inline documentation (not comments). It makes code unreadable for me unless your editor supports a decent comment-folding. But then you may hide important comments.

**Comment by Profpatsch** [comment]
Should this move to the mailing list?

**Comment by Profpatsch** [comment]
@lethalman Documentation of 0-ary attributes should be possible within one line in normal cases and as history teaches us variable names themselves are often ambiguous.

Library functions should be rigorously documented in any case (and in the code).

Of course arguments for lambdas you put into well-specified higher-order functions shouldn’t need documentation in the normal case, so no clutter there.

**Comment by lethalman** [comment]
Then what's the point of autogenerating a graphical docs. It's not docs, it's comments for critical/hard to understand piece of code.

**Comment by Profpatsch** [comment]
It’s called Application Programming Interface for a reason. Because one normally don’t want to read the standard library source to use its functions.

**Comment by peti** [comment]
@Profpatsch, how much time have you spent working with Nix so far? What is your level of experience with this project?

**Comment by lethalman** [comment]
So you are going to autogenerate an html docs for a couple of functions where a couple of comments are enough in the source code that you are going to read _anyway_ in most cases in nixpkgs. Hope that will be useful to anybody.

**Comment by vcunat** [comment]
I personally think it would be a nice to have a generated reference for nixpkgs functions. In many places there is already a good description before the function, only it's often not very easy to find out where a function is defined.

I feel people will be much more inclined to keep short comments up to date than to meddle with docs in external files. Functional programming style is much about creating many small composable functions, and we can't expect everyone to know all of them by heart. (Example: I find haddock+hayoo a very useful reference whenever doing something in haskell.)

It shouldn't be too hard to take an existing tool (e.g. doxygen) and add some basic support for *.nix files, maybe even using parser spec files from nix.

**Comment by Profpatsch** [comment]
Changed the title because that was not the primary idea: The source code comments are just **optional syntactic sugar**.
