### ISSUE TITLE
Add KeeWeb

### ISSUE THREAD

**Issue by ThibaultLemaire** [NixOS/nixpkgs#76931]
**Project description**
Keeweb webapp is a browser and desktop password manager compatible with KeePass databases.

It features an Electron-based desktop application.

**Metadata**

* homepage URL: https://keeweb.info/
* source URL: https://github.com/keeweb/keeweb
* license: mit
* platforms: Electron (unix, linux, darwin, windows) and Web

**Comment by ThibaultLemaire** [comment]
still important to me

**Comment by sikmir** [comment]
While PR to nixpkgs is still open, I've added keeweb to NUR repo ([nur.repos.sikmir.keeweb](https://github.com/nix-community/nur-combined/tree/master/repos/sikmir/pkgs/applications/keeweb)) as well.
