### ISSUE TITLE
support hdevtools in haskellng infrastructure

### ISSUE THREAD

**Issue by dmalikov** [NixOS/nixpkgs#7695]
There is a [paragraph "Local use via myEnvFun" at "Haskell" page](https://nixos.org/wiki/Haskell#Local_use_via_myEnvFun) describing so-called `myEnvFun` flow and how it could be used for building an isolated development environment with bunch of utilities like `hdevtools` and some others.

Despite the fact that there should be `pkgs.haskellPackages.ghcWithPackagesOld` used instead of `pkgs.haskellPackages.ghcWithPackages`, this method have been working properly providing adequate environment for tools like `hdevtools`.

There is [a comment at the page added](https://nixos.org/w/index.php?title=Haskell&diff=24023&oldid=24000) by Goibhniu at February 28th saying "Warning: this is outdated. It is recommended to use nix-shell instead of myEnvFun". And this comment seems to be very legit, because in this new infrastructure `hdevtools` [doesn't see any installed modules any more](https://gist.githubusercontent.com/dmalikov/8baef56b0e599037d454/raw/adcc78e9f1ecccb1ba937c717b22cdb94d7d0790/gistfile1.txt).

How to use hdevtools in haskellng infrastructure? If there is a solution, the documentation should be updated.

cc @peti : could you please shed some light on it?

**Comment by peti** [comment]
Does your shell environment have valid settings for `NIX_GHCPKG`, `NIX_GHC_LIBDIR`, and `NIX_GHC`?

**Comment by dmalikov** [comment]
I'm not quite sure what is valid in this case, but here are they:

```
>> echo $NIX_GHCPKG
/nix/store/cfyb8l2qy8wzrv3kah02qgdjy6wir7b7-ghc-7.10.1/bin/ghc-pkg
>> echo $NIX_GHC_LIBDIR
/nix/store/cfyb8l2qy8wzrv3kah02qgdjy6wir7b7-ghc-7.10.1/lib/ghc-7.10.1
>> echo $NIX_GHC
/nix/store/cfyb8l2qy8wzrv3kah02qgdjy6wir7b7-ghc-7.10.1/bin/ghc
```

**Comment by dmalikov** [comment]
@peti so could these settings be considered valid?

**Comment by peti** [comment]
Well, those settings look reasonable to me! If you run `$NIX_GHCPKG list`, then you should see the set of packages that `hdevtools` knows about when run in such an environment.

**Comment by peti** [comment]
@dmalikov, does `hdevtools` not find the modules that `$NIX_GHCPKG list` shows as registered?

**Comment by dmalikov** [comment]
After couple of `nix-channel --update`s I've tried it again. And it seems to be that `hdevtools` is working now.

So maybe what we need here is only a documentation update. Feel free to close
