### ISSUE TITLE
ldc-1.17.0 fails to build

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#76973]
**Describe the bug**
The ldc package (1.17.0) is currently failing to build properly in the unstable branch.

It looks like the following is the culprit:

`std/datetime/timezone.d(2013): Error: file "TZDatabaseDirFile" cannot be found or not in a path specified with '-J'`

**To Reproduce**
1. Run `nix-shell -p ldc`
2. Job done!

**Expected behavior**
The package should build and install cleanly.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre207998.e0470e11c7a, nixos-small-20.03pre208117.8440abe7e6f"`
 - channels(chrisaw): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @matthewbauer

**Comment by hedning** [comment]
Right, looks like a012d5eebba466d778945573295b22b2a0a1f3fd is commit introducing the failure. The `cmakeFlags` relied on shell expansion which no longer happens, so we get this: 
```
 -DD_FLAGS=-d-version=TZDatabaseDir;-d-version=LibcurlPath;-J$PWD
```
Instead of this:
```
-DD_FLAGS=-d-version=TZDatabaseDir;-d-version=LibcurlPath;-J/build/ldc-1.17.0-src
```

**Comment by veprbl** [comment]
cc @ThomasMader

**Comment by ThomasMader** [comment]
@hedning is right.

So a fix could be to use `-J/build/ldc-${version}-src` but I find the hardcoded /build quite ugly.
The path doesn't need to be in /build but I put it there to make sure it's not a file used by some other process.
Switching from /build to /tmp or whatever is for this reason not a good solution.

**Comment by worldofpeace** [comment]
I'm not sure with the changes for structured attrs we could use shell expansion for `$PWD` like before.
Perhaps @globin @Ma27 @jtojnar could comment since the fix looks obvious.

**Comment by jtojnar** [comment]
Right CMake does not interpolate environment variable.

Looks like `-J` was added in https://github.com/NixOS/nixpkgs/commit/3ff636fb2e756ac57d7f0007dc2c6c2425401997 and I agree that hardcoding `/build` is not a good idea but the presence of `-J$PWD` feels like a hack too. What is ts purpose? If the string imports are generated by the build system, I would expect them to be found without any extra flags. And if they are generated us during bootstrapping, I would expect them to be in a separate derivation, making referencing them work without variable interpolation.

If we cannot get rid of the `$PWD`, we should move the flag to `preConfigure` until we can.

**Comment by jtojnar** [comment]
Looks like the `-J` flag is needed for https://github.com/NixOS/nixpkgs/blob/a012d5eebba466d778945573295b22b2a0a1f3fd/pkgs/development/compilers/ldc/default.nix#L53

Could we copy the file to a build system’s natural directory like `src` or something, so that the flag could be omitted?

**Comment by ThomasMader** [comment]
The `-J` flag is the only possibility to get the tzdata path into the library.
See https://github.com/dlang/phobos/blob/v2.090.0/std/datetime/timezone.d#L2013 for the code in the library.
Where the file is doesn't matter but I don't see any better location as $PWD for now.

**Comment by jtojnar** [comment]
Is not it possible to put it to `phobos/std/datetime/` directory or something?

**Comment by ThomasMader** [comment]
Yes but I still need to get the full path to it for -J and there is no default directory so you could omit the -J if you mean that.
See point 3 in https://dlang.org/spec/expression.html#ImportExpression .
