### ISSUE TITLE
duplicity build is broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#76978]
~~~
$ nix-instantiate -A duplicity
error: cachetools-4.0.0 not supported for interpreter python2.7
~~~

This regression was caused by 62094862af271fd5299ad9c03c4d0cd3aa63be66 from @jonringer.

**Comment by FRidh** [comment]
Newer duplicity supports Python 3
https://github.com/NixOS/nixpkgs/commit/62094862af271fd5299ad9c03c4d0cd3aa63be66

**Comment by peti** [comment]
Yeah, fine, but we don't have a newer duplicity.

**Comment by jonringer** [comment]
actual regression was https://github.com/NixOS/nixpkgs/commit/5296ad0cb52fdcda812cbfa6be7690bb4bd8d07c I was just trying to have evaluation reflect build
