### ISSUE TITLE
VirtIO SCSI kernel module not detected by nixos-generate-config

### ISSUE THREAD

**Issue by R-VdP** [NixOS/nixpkgs#76980]
**Describe the bug**
When installing NixOS in a VirtualBox VM using a VirtIO disk device, `nixos-generate-config` does not include the `virtio_scsi` kernel module in the `boot.initrd.availableKernelModules` setting, rendering the resulting system unbootable.
In the live system, this kernel module is loaded (verified with `lsmod | grep virtio`).

The module is also not detected when running nixos-generate-config from the resulting VM, meaning that the system would be rendered unbootable when the hardware config is regenerated (e.g. to detect newly added hardware).

**To Reproduce**
1. Configure a new VM with an empty disk connected via a VirtIO interface
2. Install using the latest NixOS installation ISO, using `nixos-generate-config` to generate the initial config.
3. Try to reboot into the installed system, stage 1 will hang because the root filesystem cannot be found.

Or, easier:
1. Run `nixos-generate-config --show-hardware-config --no-filesystems` from within a VirtualBox VM with the root filesystem on a VirtIO disk.
2. Observe that the `virtio_scsi` kernel module is not included in the `boot.initrd.availableKernelModules` setting.

**Expected behavior**
The `virtio_scsi` kernel module should be added to the `boot.initrd.availableKernelModules` setting by `nixos-generate-config`.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.90, NixOS, 19.09.1629.ce54d9601ea (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by R-VdP** [comment]
The module is also not detected when running `nixos-generate-config` from the resulting VM, meaning that the system would be rendered unbootable when the hardware config is regenerated (e.g. to detect newly added hardware).

**Comment by jbenden** [comment]
I ran across this issue, too.

For the file  https://github.com/NixOS/nixpkgs/blob/7b2982e22eb3ca5016161abc0946f88bb43b1e09/nixos/modules/installer/tools/nixos-generate-config.pl#L187, the vendor ID is still correct but the device ID is `0x1048`.
