### ISSUE TITLE
gitea: backport latest releases to release-19.09

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#76983]
The gitea upstream [does not backport security fixes to old version branches.](https://discourse.gitea.io/t/security-maintenance-backporting-policy/1772/2) So the 1.9.x version currently present in release-19.09 is likely to contain several known bugs.
I suggest backporting the 1.10.x releases to NixOS stable as well. Alternatively, security patches could be picked and backported individually, but that's probably too much effort for avoiding a minor release bump.

/cc @disassembler @kolaente

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/pull/73741

**Comment by aanderse** [comment]
> is likely to contain several known bugs.

If this statement becomes more concrete we can reopenthis issue for discussion possibly, though I think most relevant parties agree current stance is either the right stance, or at least acceptable 

There is a `package` option in the `gitea` module and it is probably best to set that to `unstable.gitea`.
