### ISSUE TITLE
gids not consistent between stable and unstable.

### ISSUE THREAD

**Issue by stephenmw** [NixOS/nixpkgs#7700]
https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/nixos/modules/misc/ids.nix#L204
https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/nixos/modules/misc/ids.nix#L398
https://github.com/NixOS/nixpkgs-channels/blob/nixos-14.12/nixos/modules/misc/ids.nix#L291

While doing some development, I got a merge conflict. That made me look deeper and find this.

Is it standard to change a gid to match the new uid? Does this break anything? I know that I can't upgrade to unstable without nixos failing to boot, might this be a cause?

**Comment by edwtjo** [comment]
I'll repeat my previous comment on this.

There isn't a formed consensus on these things. I personally don't care that the integer value for the group doesn't match up with the uid value. I care that the default username and groupname match the servicename and that there is a default. The important thing is that the value isn't just changed on rut. If you decide to change a uid/gid value then you need to migrate previous installations using something like an activation chown/chmod checker. 

Also mistakes are a thing.

**Comment by vcunat** [comment]
The reasons for changes were discussed in https://github.com/NixOS/nixpkgs/issues/3727 and linked places.
