### ISSUE TITLE
openvpn service waits a long time and fails

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#7703]
So openvpn has been patched to use sd_notify, and the systemd service to be Type=notify. However it doesn't seem to work. systemctl start just hangs until the timeout occurs for the notify event, and it marks the unit as failed, although openvpn started successfully.

Looking at processes, it seems like it's asking for some kind of systemd password, I don't know why...

For now I'm using `Type=simple`.

**Comment by lethalman** [comment]
cc @edolstra do you experience this problem? Seems like the notify doesn't work at all, or it's not called through that code path.

**Comment by edolstra** [comment]
Works for me (in NixOS 14.12):
```
[root@mandark:~]# systemctl start openvpn-lb
Enter Private Key Password: ****
```
Systemctl then returns when the VPN connection is up.

**Comment by lethalman** [comment]
@edolstra so I only set up a vpn server, I don't need to specify any private key password. Also that prompt doesn't show on my headless-profile server. Hence it hangs because it's asking me a password.

**Comment by lethalman** [comment]
@edolstra also how does it work on boot for an headless server? That's going to fail, it can't start automatically. Why does one need to provide that password I don't even know what password is it?

**Comment by edolstra** [comment]
Don't know, I only have experience running it as a client. It's possible that the sd_notify call is not reached for the server case, so maybe another one needs to be added.

**Comment by lethalman** [comment]
No I see it clearly there's a process asking for a password, but I don't have to put any password there. How do I disable this kind of behavior?

**Comment by lethalman** [comment]
Seems like related to this: https://bugs.launchpad.net/ubuntu/+source/openvpn/+bug/1374782

I believe this is critical for headless servers. I'm currently overriding "Type=simple" in nixpkgs, because I'm unable to mkForce it from configuration.nix.

**Comment by edolstra** [comment]
Do you actually get a password prompt? I think systemctl always starts `systemd-tty-ask-password-agent --watch` to handle password prompts even if there are none.

**Comment by lethalman** [comment]
No don't get a password prompt, but systemctl start hangs until it times out.

**Comment by grahamc** [comment]
This should be able to be closed by now.

**Comment by lethalman** [comment]
@grahamc why? openvpn has been patched to use sd_notify for the client, but not for the server. In what why this can be closed?

**Comment by fpletz** [comment]
I'm also noticing this when using openvpn as tls-client. The private key doesn't have a password either.

**Comment by grahamc** [comment]
Can you all specify if you're using the more robust PKI methods, or the static key configuration method? With the more robust PKI method, this is a non-issue. When using static key, the server appears to expect a client to connect before indicating it is healthy.

**Comment by Profpatsch** [comment]
triage: still a problem?
