### ISSUE TITLE
less-475 upstream sha256 change

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#7706]
I'm getting a

> should have sha256 hash ‘1w7d10h6hzgz5zww8g4aja2fbl7xwx30vd07hcg1fcy7hm8yc1q2’, instead has ‘16703m6g5l97af3jwpypgac7gpmh3yjkdpqygf5a2scfip0hxm2g’

for the upstream "http://www.greenwoodsoftware.com/less/less-475.tar.gz".

This agrees with what I see if I manually download the file

    $ wget -d http://www.greenwoodsoftware.com/less/less-475.tar.gz
    $ nix-hash --flat --type sha256 --base32 less-475.tar.gz
    16703m6g5l97af3jwpypgac7gpmh3yjkdpqygf5a2scfip0hxm2g

Not sure what has changed as I don't have the original.  Maybe 475 isn't a stable release point as it isn't actually listed on their [download page](http://www.greenwoodsoftware.com/less/download.html) (the last one listed is 471)?  I guess they could also have got hacked...?

**Comment by copumpkin** [comment]
Perhaps email upstream and ask them whether it changed (and ask them to avoid changing it if it was intentional)?

**Comment by dezgeg** [comment]
Bah, didn't notice this issue before opening https://github.com/NixOS/nixpkgs/pull/7721. Anyway, I worked out the diff in that PR. Maybe we should indeed revert to an earlier `less` release if these aren't supposed to be stable releases.

**Comment by twhitehead** [comment]
I sent an email and received the following response back yesterday from Mark

> Yes, that was due to a procedural error on my part.  No hacking involved.  But I didn't think it would matter to anyone since less-475 hasn't been announced yet."

That agrees well with the diff dezgeg provided in #7721.

Cheers!  -Tyson

**Comment by edolstra** [comment]
Ah, thanks for looking into this!

**Comment by edolstra** [comment]
BTW, I got the 475 release from monitor.nixos.org, which in turn got it from Gentoo.

**Comment by lethalman** [comment]
Fixed via 901849ec
