### ISSUE TITLE
OfBorg CI is down

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#77139]
For the past seven hours, it seems that ofborg no longer automatically evaluates PRs, however, it's still able to perform `build` or `test` commands.

cc @grahamc @FRidh  (infrastructure)

**Comment by grahamc** [comment]
It is processing, but has an enormous backlog for some reason: https://monitoring.nix.ci/d/000000002/ofborg?orgId=1

**Comment by jonringer** [comment]
hmm, very odd https://monitoring.nix.ci/d/000000002/ofborg?orgId=1&refresh=10s&fullscreen&panelId=6&from=now-2d&to=now

**Comment by FRidh** [comment]
There have been many r-ryantm pr's which may be a cause.

**Comment by grahamc** [comment]
seems caught up

**Comment by jonringer** [comment]
agreed, also looks like it's doing 3 simultaneous evals too :)

**Comment by jonringer** [comment]
cc @grahamc, seems ofborg hasn't done any evals in a good while.

**Comment by grahamc** [comment]
Okay, but please make a new issue next time :)

**Comment by jonringer** [comment]
sorry :(

**Comment by jonringer** [comment]
110+ queue'd eval's are now going, thank you! :)

**Comment by grahamc** [comment]
Solved :)
