### ISSUE TITLE
Package Request: xwax

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#77136]
**Project description**
Open-source vinyl emulation software for Linux. Xwax allows DJs and turntablists to playback digital audio files (MP3, Ogg Vorbis, FLAC, AAC and more), controlled using a normal pair of turntables via timecoded vinyls. http://xwax.org/

**Metadata**

* homepage URL: http://xwax.org/
* source URL: https://github.com/xwax/xwax
* license: GPL2
* platforms: Linux

**Comment by mmilata** [comment]
FYI [Mixxx](https://www.mixxx.org/) can also do vinyl emulation and is already packaged (IIRC it uses xwax internally).

**Comment by abathur** [comment]
Closing. Posting account is deleted and there is no sign someone's anticipating this.
