### ISSUE TITLE
🏗️ ⚠️ Hydra database maintenance will stop builds on 2020-01-07.

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#77152]
The infrastructure team will be replacing Hydra's database server tomorrow (2020-01-07.) This upgrade will be to a much faster host with faster disks and more RAM. All good things for a database server!

As mentioned in #76106, Hydra's database server is [running out of disk space](https://status.nixos.org/prometheus/graph?g0.range_input=11w&g0.expr=node_filesystem_avail_bytes%7Bmountpoint%3D%22%2Fdata%22%2Cinstance%3D%22chef%3A9100%22%7D&g0.tab=0):

![image](https://user-images.githubusercontent.com/76716/71851067-abe5fb80-30a3-11ea-9180-060a97d1e829.png)

The down time will likely begin in [America/New_York's morning](https://everytimezone.com/s/957d0202), and we don't know how long it will take, but it will be more than a couple hours and hopefully less than 16.

**Comment by jonringer** [comment]
just curious, how long has that machine been running?

**Comment by davidak** [comment]
Thanks for your effort and informing us! :heart:

**Comment by grahamc** [comment]
@jonringer do you mean current uptime or how long it has been part of our infra?

**Comment by grahamc** [comment]
@jonringer if you mean uptime, about 17 days: https://status.nixos.org/prometheus/graph?g0.range_input=1h&g0.expr=(time()%20-%20node_boot_time_seconds%7Binstance%3D%22chef%3A9100%22%2Crole%3D%22database%22%7D)%20%2F%20(60%20*%2060%20*%2024)&g0.tab=1

if you mean how long have we had it, it seems 2016-03-08: https://github.com/NixOS/nixos-org-configurations/commit/15f4fd850e5b9ff98dafff5e2e39e1c35023f040#diff-0d35c1f291bb3530413fad1ff7c03b7c

**Comment by grahamc** [comment]
It is now in to America/New_York time and we haven't started yet. We're working on some tooling to get ready.

**Comment by grahamc** [comment]
The new machine, haumea, is up: https://status.nixos.org/grafana/d/5LANB9pZk/per-instance-metrics?orgId=1&refresh=30s&var-instance=haumea:9100&from=1578424500000&to=now

**Comment by grahamc** [comment]
We're going to take Hydra down any minute now.

**Comment by grahamc** [comment]
Haumea's postgres dashboard is here: https://status.nixos.org/grafana/d/rrbV5fdik/postgres-node?orgId=1&refresh=30s

Chefs postgres dashboard is here: https://status.nixos.org/grafana/d/rrbV5fdik/postgres-node?orgId=1&refresh=30s&var-host=postgresql&var-db=All

**Comment by jonringer** [comment]
those are some sexy dashboards

**Comment by grahamc** [comment]
If you're watching the per-instance-metrics dashboard you'll have noticed data transfer has tapered off and then completely stalled. There is still a lot of data to transfer. `postgresql` is doing a ton of read/write operations on the receiving end still, so I expect it has to do with index generation.

**Comment by grahamc** [comment]
I've confirmed this slowdown is due to creating indexes and a WAL not quite tuned for an import scenario.

**Comment by grahamc** [comment]
According to:

```
psql hydra -c "SELECT relname, n_live_tup FROM pg_stat_all_tables where schemaname = 'public'"
```

all the data has indeed been received. We're still working through indexes and constraints. Once this finishes, we're going to do a snapshot of the postgresql ZFS dataset, start postgres, point Hydra to the new system, and start everything back up. However, if it finishes quite late, I might wait until Eelco wakes up in the morning to do the final bring-up.

**Comment by grahamc** [comment]
Restore finished.

**Comment by grahamc** [comment]
Snapshot taken, and I'm realizing all my previous snapshots are named as if it was 2019.

**Comment by grahamc** [comment]
Chef's postgres is stopped, and Ceres (hydra.nixos.org) has had chef's wireguard peer removed to prevent accidental writes while Eelco updates hydra to use Haumea.

**Comment by grahamc** [comment]
```
ceres systemd[1]: hydra-queue-runner.service:
    Consumed 2w 1d 20h 41min 33.725s CPU time,
    received 4.3T IP traffic, sent 1.4T IP traffic.
```

**Comment by grahamc** [comment]
We're up!

**Comment by markuskowa** [comment]
Very nice! The machine is much more responsive.

**Comment by grahamc** [comment]
```
[root@haumea:~]# zfs get used,logicalused,compressratio rpool/safe/postgres
NAME                 PROPERTY       VALUE  SOURCE
rpool/safe/postgres  used           173G   -
rpool/safe/postgres  logicalused    332G   -
rpool/safe/postgres  compressratio  1.93x  -
```

**Comment by jonringer** [comment]
unpinning as this is no longer an active endeavor

**Comment by jonringer** [comment]
Thank you for the great work @grahamc :).

We appreciate you! :)

**Comment by grahamc** [comment]
Big thanks to @edolstra for doing the hard part :)
