### ISSUE TITLE
package request: Glimpse (re-branding of GIMP)

### ISSUE THREAD

**Issue by trusktr** [NixOS/nixpkgs#77157]
**Project description**

![](https://rawcdn.githack.com/glimpse-editor/Glimpse/a97c687be3eeceb89e4c649aa4096515310dedac/build-aux/snap/local/glimpse.png)

Glimpse is a re-branding of Gimp to make it more friendly. The word "gimp" may insult some people. The new branding looks nice too.

**Metadata**

* homepage URL: https://glimpse-editor.org
* source URL: https://wiki.glimpse-editor.org/index.php?title=Building_Glimpse
* license: "GNU GENERAL PUBLIC LICENSE"
* platforms: windows, linux, macos

**Comment by jtojnar** [comment]
I believe @ashkitten has it packaged.

**Comment by ashkitten** [comment]
affirmative, i've got it in my own fork of nixpkgs. i wasn't sure how many people wanted it, so my plan was to wait until at least after they switch the build system, especially since i believe the plan is to include release tarballs for future releases which hasn't been done for 0.1 and would simplify packaging somewhat

**Comment by wakest** [comment]
got here looking for glimpse, @ashkitten should it still be installed through your fork or can it be merged into mainline?

**Comment by ashkitten** [comment]
you can use my fork if you want, but i'd recommend cherry-picking the commit onto your own since my fork has other changes in it as well. as i said, i'll make a pull request after there is a release tarball available.

**Comment by ashkitten** [comment]
as promised, i created a pull request]  once a release tarball became available (via https://github.com/glimpse-editor/Glimpse/issues/242)

**Comment by TrechNex** [comment]
Monitoring this issue, so we can potentially list NixOS as a "community-supported source" on this page: https://glimpse-editor.org/downloads/

**Comment by ashkitten** [comment]
still planning to get this merged unless someone else does first. looks like i missed the release of glimpse 0.2.0 by a few days, which appears to have source tarballs. decided i'm going to try to rebase it so it does just override upstream's derivation, at least until the point at which that doesn't work anymore.
