### ISSUE TITLE
loaOf deprecation warnings or errors

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#77189]
**Describe the bug**
The type `loaOf` was [deprecated](https://github.com/NixOS/nixpkgs/issues/1800) and its use will spring up evaluation warnings like
```
trace: warning: In file <unknown-file>
a list is being assigned to the option config.fileSystems.
This will soon be an error as type loaOf is deprecated.
See https://git.io/fj2zm for more information.
Do
  fileSystems =
    { unnamed = {...}; ...}
instead of
  fileSystems =
    [ { name = "unnamed"; ...} ...]
```

This was done in https://github.com/NixOS/nixpkgs/pull/63103, but because the scope of the change
it wasn't feasible to get them all in one go and there was a few syntax related errors https://github.com/NixOS/nixpkgs/pull/77177.

`rg "loaOf"` returned this for me at the time of writing
```
nixos/modules/config/users-groups.nix:2
nixos/modules/security/pam.nix:1
nixos/modules/tasks/encrypted-devices.nix:1
nixos/modules/tasks/filesystems.nix:2
nixos/modules/tasks/network-interfaces.nix:1
nixos/modules/programs/tsm-client.nix:2
nixos/modules/programs/ssh.nix:1
nixos/modules/virtualisation/railcar.nix:2
nixos/modules/virtualisation/containers.nix:1
nixos/modules/services/backup/znapzend.nix:2
nixos/modules/system/etc/etc.nix:1
nixos/modules/services/desktops/geoclue2.nix:1
nixos/modules/system/boot/stage-1.nix:1
nixos/modules/system/boot/luksroot.nix:1
nixos/modules/services/networking/bitcoind.nix:1
nixos/modules/services/security/tor.nix:1
nixos/modules/services/networking/i2pd.nix:2
nixos/modules/services/x11/picom.nix:3
nixos/modules/services/networking/prosody.nix:1
nixos/modules/services/networking/nylon.nix:1
nixos/doc/manual/development/option-types.xml:1
nixos/modules/installer/tools/nixos-option/nixos-option.cc:1
nixos/modules/services/hardware/sane_extra_backends/brscan4.nix:1
nixos/modules/services/networking/hylafax/options.nix:2
nixos/modules/services/networking/ssh/sshd.nix:1
```

and it appears some modules were probably added while the PR was opened used the old format.

**What to do if encountered**
Duplicate such changes like in:
* https://github.com/NixOS/nixpkgs/pull/63103
* https://github.com/NixOS/nixpkgs/pull/77177

Here's the PR that added the release note, with details about the change https://github.com/NixOS/nixpkgs/pull/77109.

**Comment by Mindavi** [comment]
transmission is using the users.users and users.groups configuration, so also needs to be patched.

**Comment by worldofpeace** [comment]
I'm seeing the last bit of warnings at https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

**Comment by worldofpeace** [comment]
It seems to just be tests, these remain to be fixed in `fileSystems`:

- [ ] https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/glusterfs.nix

- [ ] https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/orangefs.nix

- [ ] https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/nfs/simple.nix

**Comment by worldofpeace** [comment]
The last warnings are just in tests.
Need to open an issue about actually removing it for 20.09 after this.

**Comment by xaverdh** [comment]
can this be closed now?
