### ISSUE TITLE
Starleaf Breeze

### ISSUE THREAD

**Issue by eoli3n** [NixOS/nixpkgs#77203]
**Project description**
StarLeaf Breeze voice and video softclient

**Metadata**

* homepage URL: https://support.starleaf.com/downloads/
* source URL: https://aur.archlinux.org/packages/starleaf-breeze/
* license: custom:starleaf 
* platforms: linux

**Comment by davidak** [comment]
@eoli3n do you need specifically this proprietary software or could you use a free software like https://meet.jit.si/ or the popular zoom-us we have already packaged?

Info for packaging: AUR just extracts the deb package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=starleaf-breeze#n12

**Comment by eoli3n** [comment]
We use starleaf at work, i can't change that but i'll check if meet and zoom-us are compatible which i doubt

**Comment by davidak** [comment]
@eoli3n that's a good reason to include it. they are probably all stand-alone solutions not compatible with each other

**Comment by eoli3n** [comment]
any update on this ?

**Comment by nim65s** [comment]
Starleaf is no longer a living thing, closing this.
