### ISSUE TITLE
packaging + module request: FreshRSS

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#77246]
**Project description**

FreshRSS is a self-hostable RSS aggregator web application. It is written in PHP.

**Metadata**

* homepage URL: https://www.freshrss.org/
* source URL: https://github.com/FreshRSS/FreshRSS
* license: AGPL3
* platforms: unix, linux, darwin (everything with PHP)

-----

**Motivation**: I am currently using  TinyTinyRSS (tt-rss) for aggregating my feeds, but I'd like to move away from that for 2 reasons and FreshRSS is a viable, actively developed alternative:

- tt-rss doesn't do proper releases, you just have to pull it from the master branch when installing
- The tt-rss community (especially the maintainer) [find the concept of gas chambers and the Holocaust funny](https://community.tt-rss.org/t/a-category-named-gas-chamber/649). I *personally* do not feel comfortable using a software developed with an edgy-antisemitic mindset.

I might get around to package FreshRSS myself at some point, but am currently busy with other packages.

**Comment by j0hax** [comment]
I am interested in this for the same reasons! Additionally, FreshRSS has the benefit over tt-rss of an excellent mobile layout.

**Comment by ajs124** [comment]
Closed via #190172
