### ISSUE TITLE
GITK without rebuilding all of git.

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#7726]
Looking at the git package, it seems the optional features are built always, and optionally pruned in postInstall. Would it be OK then to split the building of git, and post-install hooks into two different derivations? That way, users of the various non-standard combination of flags just end up running the postInstall fixes, not rebuilding all of git?

I'm willing to do the myself, just need to know if this is kosher.

**Comment by peti** [comment]
>  it seems the optional features are built always, and optionally pruned in postInstall.

I am pretty sure that's not accurate.

**Comment by Ericson2314** [comment]
Ah, in hindsight looking at `pkgs/applications/version-management/git-and-tools/git/default.nix`, i guess git's build system will just decide based on whether tcl/tk is available?

**Comment by peti** [comment]
Yes. Without Tcl/Tk available, `gitk` won't be built.

**Comment by Ericson2314** [comment]
Well, then best to close this, and revisit once we have a more general solution for building packages in their many configurations?

IIRC for really common alternatives a seperate top level package is added to get hydra to build it, right? Experience says few people use gitk besides my self so I doubt this deserves that.
