### ISSUE TITLE
Secrets handling in mailman server

### ISSUE THREAD

**Issue by kamadorueda** [NixOS/nixpkgs#77274]
**Describe the bug**
Hard-coded secret key

**To Reproduce**

1. `nixpkgs$ head -n 43 pkgs/servers/mail/mailman/settings.py | tail -n 1`

**Expected behavior**

secure secrets handling

**Comment by jonringer** [comment]
assigning peti, as he's on the commit

**Comment by FRidh** [comment]
Related PR https://github.com/NixOS/nixpkgs/pull/77444
