### ISSUE TITLE
services.gitlab crash with external db

### ISSUE THREAD

**Issue by neumantm** [NixOS/nixpkgs#77285]
When using services.gitlab with an external database (using databaseHost) the service gitlab does not start properly and crashes with the error "FATAL:  no pg_hba.conf entry for host <ip address of first network interface of this machine>, user "gitlab", database "gitlab", SSL off"

**To Reproduce**
1. Setup gitlab using the attached config.
2. nixos-rebuild and reboot
3. systemctl status gitlab

**Expected behavior**
I expect gitlab to start normally using the configured database host.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 19.09.1682.bfdae0860e4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1682.bfdae0860e4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information: (dunno what to enter 
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by neumantm** [comment]
As attaching files didn't seem to work i pasted them to pastebin:
* [journalctl -e output](https://pastebin.com/m4jz4BQ6)
* [config used](https://pastebin.com/EMuecGD8)

**Comment by aanderse** [comment]
ping @talyz or @flokli as people who probably use this module.

**Comment by talyz** [comment]
@neumantm Looks like the connection is refused by the server. Could you check that you've set up the correct permissions on the PostgreSQL server side and try connecting manually to it from the GitLab host?

**Comment by neumantm** [comment]
You are right. Thanks!
Don't have much experience with PostgreSQL and misinterpreted the error message.
Sorry for bothering you.

**Comment by talyz** [comment]
No worries! :)
