### ISSUE TITLE
gdal not packaged correctly on macOS (dyld: Library not loaded: libgif.dylib)

### ISSUE THREAD

**Issue by wereHamster** [NixOS/nixpkgs#77301]
**Describe the bug**
gdal for macOS is not packaged correctly. Running `ogr2ogr` fails with the following error:
```
$ ogr2ogr 
dyld: Library not loaded: libgif.dylib
  Referenced from: /nix/store/89frkjskn1pdzcp5fm5gc68snmaa41im-gdal-3.0.1/bin/ogr2ogr
  Reason: image not found
Abort trap: 6
```

**To Reproduce**
1. `nix-shell -p gdal`
2. `ogr2ogr`

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(tomc): `"nixpkgs-20.03pre207249.7e8454fb856, nixpkgs-unstable-20.03pre207249.7e8454fb856"`
 - channels(root): `"nixpkgs-20.03pre207249.7e8454fb856, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
attribute:
 - gdal
```

**Comment by LnL7** [comment]
Fixed in a03e68d593e691666906a4243cf1e43e001480ed.

**Comment by wereHamster** [comment]
I see that commit was made on 29 Nov 2019. How long does it usually take until a commit makes it into the nixpkgs-unstable channel?

**Comment by LnL7** [comment]
That depends on the status of builds, see https://status.nixos.org or http://howoldis.herokuapp.com.

**Comment by wereHamster** [comment]
The commit a03e68d593e691666906a4243cf1e43e001480ed is (among others) in the following branches: master, nixos-unstable, nixos-unstable-small, staging. What do I need to do to promote this commit to nixpkgs-unstable? Is it sufficient if I open a PR? Or are there specific reasons to not include commits in the nixpkgs-unstable branch?

**Comment by LnL7** [comment]
That branch is readonly and just reflects the status of the channel. A channel won't update while there are build problems, pushing a revision to users where important software doesn't work would not be a great experience. In this case it looks like there's still some fallout from the gcc9 update. https://github.com/NixOS/nixpkgs/labels/1.severity%3A%20channel%20blocker
