### ISSUE TITLE
Installation fails with empty error message

### ISSUE THREAD

**Issue by mwilson-ns** [NixOS/nixpkgs#7733]
**Note** -- this is a dupe of https://github.com/NixOS/nix/issues/527, but I thought it might be more appropriate here:

I'm having difficulty installing, and there are no error diagnostics to provide further information.

* I'm using Arch Linux
* uname -a: Linux octet 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux
```
[mwilson@octet nix-1.8-x86_64-linux]$ pwd
/home/mwilson/nix/nix-1.8-x86_64-linux
[mwilson@octet nix-1.8-x86_64-linux]$ ls
install  store
[mwilson@octet nix-1.8-x86_64-linux]$ ./install 
performing a single-user installation of Nix...
copying Nix to /nix/store..........................
initialising Nix database...
installing ‘nix-1.8’
building path(s) ‘/nix/store/l1jay99nhry9n4y1d7wij405q8rp2p9p-user-environment’
killing process 16684
error: 
./install: unable to install Nix into your default profile
```

**Comment by domenkozar** [comment]
Nix issue is fine, no need to duplicate
