### ISSUE TITLE
krop segfaults

### ISSUE THREAD

**Issue by moretea** [NixOS/nixpkgs#77339]
**Describe the bug**
`krop` segfaults when launched.

**To Reproduce**

```
$ nix-shell -p krop --run krop
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

/tmp/nix-shell-27194-0/rc: line 1: 27277 Aborted                 (core dumped) krop
```

**Expected behavior**
krop to not segfault.

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 19.09.1589.57b7b019812 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1791.ac218438bdb, nixos-19.03-19.03.173681.3907a44b70d, nixpkgs-19.09.1791.ac218438bdb, unstable-20.03pre208261.9beb0d1ac2e"`
 - channels(maarten): `"home-manager, unstable-20.03pre208261.9beb0d1ac2e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
This is #65399, it needs `wrapQtAppsHook`
