### ISSUE TITLE
ms-python.python: fails to build as file not hosted

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#77341]
**Describe the bug**
Unfortunately, python language server 0.4.24 is no longer hosted so curl fails. The quick fix is to use 0.4.71 instead.

Although I wonder if we can use https://github.com/Microsoft/python-language-server instead for greater stability? Not clear how to map version numbers, though. The contributing guide shows how to use GitHub checkout instead.

@jraygauthier

**Comment by jraygauthier** [comment]
It might be that this is now possible to package the language server. Its package was blocked by #29817. Which might just have been resolved by #66299.

In the quickfix seems like a good idea.

**Comment by tbenst** [comment]
Meh, @jonringer could you reopen? Unbelievably, 0.4.71 was hosted two days ago but no longer.

I wrote a script to check what's available:
```python
import requests

def check_url(url):
    request = requests.get(url)
    if request.status_code == 200:
        return True
    else:
        return False

for major in range(0,2):
    for minor in range(0,10):
        for patch in range(0,200):
            url = 'https://pvsc.azureedge.net/python-language-server-stable' \
                f'/Python-Language-Server-linux-x64.{major}.{minor}.{patch}.nupkg'
            if check_url(url):
                print(url)
```
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.1.80.nupkg
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.2.96.nupkg
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.3.76.nupkg
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.4.127.nupkg
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.10.nupkg
https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.30.nupkg

It appears they host only latest for old versions, and two for current. So perhaps we switch to `0.4.127` for now..?

**Comment by jonringer** [comment]
sigh... why do people do this :(
