### ISSUE TITLE
qutebrowser: update package to v1.9.0

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#77360]
qutebrowser v1.9.0 just came out. See https://github.com/qutebrowser/qutebrowser/releases/tag/v1.9.0

This "issue" is simply to report that I'm working on updating the Nix package.

**Comment by flokli** [comment]
@emmanuelrosa no need to open an issue - you can file a PR directly next time. Please make sure to add a `closes: ` in the PR, so the reference is there.
