### ISSUE TITLE
Enpass package only working with root privileges

### ISSUE THREAD

**Issue by Laobiz** [NixOS/nixpkgs#77435]
**Describe the bug**
When trying to start the Enpass password manager as non-root user you get the following error message:

```
QQmlApplicationEngine failed to load component
qrc:/qml/Enpass.qml:23 Type ApplicationWindow unavailable
file:///nix/store/b1kg6y4817i64cqvjkhy00w6czjf13km-qtquickcontrols2-5.12.3-bin/lib/qt-5.12.3/qml/QtQuick/Controls.2/Fusion/ApplicationWindow.qml:37 module "QtQuick" version 2.12 is not installed

[1]    8874 segmentation fault (core dumped)  Enpass
```
It runs normally when you start it as root.

**To Reproduce**
1. Install Enpass package through environment.systemPackages or users.users.<name>.packages
2. Start Enpass with the terminal.

**Expected behavior**
Should also be working as normal user.

**Additional context**
As DesktopManager KDE Plasma is used. Running on NixOs 19.09

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1784.fd4ccdbe3a6 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```
# a list of nixos modules affected by the problem
module: enpass
```

**Comment by berberman** [comment]
still important to me

**Comment by ewok** [comment]
> still important to me

@berberman 
I don't have KDE installation near at hand. Could you try an updated version from nixpkgs/master branch?

**Comment by berberman** [comment]
> > still important to me
> 
> @berberman
> I don't have KDE installation near at hand. Could you try an updated version from the nixpkgs/master branch?

Thanks for your reply. I'm using nixos-unstable, and this is my system information:
```
Operating System: NixOS 21.03.20201229.733e537
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.2
Kernel Version: 5.4.85
OS Type: 64-bit
```

**Comment by ewok** [comment]
@berberman  thank you I reproduced it in VM.

I tried to run a new version 6.5.1 from master branch on KDE, still getting error:

`"QtQuick.Controls.Fusion" plugin "qtquickcontrol2fusionstyleplugin" not found.`

I'll try to find out what this is all about.

**Comment by ewok** [comment]
@berberman I managed to get it working with your nixos-config.

I've created a Draft PR fixing that issue. Whoever is interested in testing are welcome https://github.com/NixOS/nixpkgs/pull/108713 .
Review is also appreciated.
