### ISSUE TITLE
Packgae Request: netbox

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#77448]
**Project description**
IP address management (IPAM) and data center infrastructure management (DCIM) tool.

**Metadata**

* homepage URL: -
* source URL: https://github.com/netbox-community/netbox
* license: Apache-2.0
* platforms: Linux

**Comment by hax404** [comment]
So far, I have packaged netbox and its remaining dependencies in https://github.com/NixOS/nixpkgs/compare/master...hax404:netbox_init?expand=1, but was not able to build the netbox module. Feel free to use this code base.

**Comment by n0emis** [comment]
I created a PR at #162624. But it still some issues, where I could need help with more experienced nixos-contributers.

**Comment by devhell** [comment]
That's an enormous amount of work you put in there, thank you! I'm currently not in a position to review this though. I'm sorry. Perhaps another member will be able to. Thank you again :beers:

**Comment by mweinelt** [comment]
I failed to mention this at the time, but I packaged up all dependencies at the time in https://github.com/NixOS/nixpkgs/pull/143112 and then failed to find the time to continue with the actual application. Thanks for picking this up, will be around for the review.
