### ISSUE TITLE
Various evil-related packages broken since the last ELPA bump

### ISSUE THREAD

**Issue by danieldk** [NixOS/nixpkgs#77455]
**Describe the bug**

Since 04c9af7d11967501a8a1987a2bb30755d0e776b3, various evil-related packages fail to compile with errors such as:

```
In toplevel form:
evil-magit.el:51:1:Error: Wrong type argument: number-or-marker-p, nil
Done (Total of 0 files compiled, 1 failed, 2 skipped)
Wrong type argument: number-or-marker-p, nil
```

Packages that fail for me:

* `evil-magit`
* `evil-mu4e`
* `evil-org`

1. Use 04c9af7d11967501a8a1987a2bb30755d0e776b3 (or later)
2. Attempt to use emacs with one of these packages

**Expected behavior**

Successful compilation.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.94, NixOS, 20.03pre208862.e116b4b331b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre208862.e116b4b331b, nixos-unstable-20.03pre205837.f2b55f28271"`
 - channels(daniel): `""`
 - nixpkgs: `/home/daniel/git/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: emacsPackagesNgGen
# a list of nixos modules affected by the problem
module:
```

**Comment by thefloweringash** [comment]
Reverting `undo-tree` from 0.7.0 to 0.6.5 seems to be enough to make most of the evil packages build again.

**Comment by danieldk** [comment]
Ping @adisbladis .

**Comment by frio** [comment]
It's hard to tell what's happening upstream with undo-tree, but it appears this was a bug and has (maybe?) been fixed in 0.7.2 (the changelog just says "bug fix release", see https://elpa.gnu.org/packages/undo-tree.html and http://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=commitdiff;h=0ba3bb020fee321eb66ee45a8997427e00353487).

Hopefully an ELPA bump should resolve.

**Comment by peterhoeg** [comment]
https://github.com/NixOS/nixpkgs/pull/77602 fixes it.

I'll merge this as soon as the tests pass.

**Comment by peterhoeg** [comment]
Closing this as the PR mentioned above has been merged.
