### ISSUE TITLE
Polkit popup appears after adjusting brightness in xfce

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#77485]
It seems an update of the last few days made it that after I adjust brightness on my Thinkpad with Fn-Home/End (brightness adjustment works), a policykit popup appears prompting for my password.

It says:

> **Authentication is needed to run `/nix/store/4psml7gxvbvdbm709f8ncvd7l9z6203-xfce-power-manager-1.4.4/sbin/xfpm-power-backlight-helper' as the super user**

I'm using i3 with xfce.

**Expected behavior**
No popup.

**Screenshots**
![image](https://user-images.githubusercontent.com/399535/72198910-003b0380-3435-11ea-94d4-9f3b659cd878.png)

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1815.caad1a78c47 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1815.caad1a78c47, nixos-hardware, unstable-20.03pre207249.7e8454fb856"`
 - channels(niklas): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
It might have the same cause as the issue in GNOME had: https://github.com/NixOS/nixpkgs/issues/14168#issuecomment-381759563

**Comment by worldofpeace** [comment]
Our fix in g-s-d is pretty simple too
* https://github.com/NixOS/nixpkgs/blob/0f9a4a2e556bd300db9d3f2fe12215d89c927586/pkgs/desktops/gnome-3/core/gnome-settings-daemon/default.nix#L106
* https://github.com/NixOS/nixpkgs/blob/0f9a4a2e556bd300db9d3f2fe12215d89c927586/pkgs/desktops/gnome-3/core/gnome-settings-daemon/global-backlight-helper.patch#L23

expecting there to be a similar situation in xfce-power-manager as @jtojnar mentioned.

**Comment by worldofpeace** [comment]
@nh2 Which xfce is being used? The `xfce` module or `xfce4-14`?

> Note there's only one packageset and module on master now https://github.com/NixOS/nixpkgs/issues/68737

**Comment by nh2** [comment]
The big update on 19.09 today seems to have fixed it (or my reboot for it fixed it for other unknown reasons).

Closing until it reoccurs.

**Comment by worldofpeace** [comment]
A reboot fixes this issue, but it shouldn't happen in the first place.
I've looked at `share/polkit-1/actions/org.xfce.power.policy` and it's the same issue we had with g-s-d.

**Comment by worldofpeace** [comment]
Updated the issue title

**Comment by psanford** [comment]
This also happens for me when I have auto dimming enabled after x minutes of idle. Is there a known work around?

**Comment by worldofpeace** [comment]
> This also happens for me when I have auto dimming enabled after x minutes of idle.

Does a reboot fix the issue? If not then that's a different issue.

**Comment by psanford** [comment]
> Does a reboot fix the issue? If not then that's a different issue.

Yup, a reboot fixes the issue temporarily.

**Comment by Mastermjr** [comment]
I ran into this today after upgrading from 23.05 -> 23.11 reboot fixed the issue, how can this be added into the https://nixos.wiki/wiki/Backlight wiki page? 
I'm happy to do that if someone lets me know how

**Comment by jtojnar** [comment]
This was fixed and when switching from a NixOS version without this fix to a version with it without rebuilding is the last time you will see this. So probably no need to document it. Also you should generally reboot NixOS after major updates of graphical environment anyway.

**Comment by jtojnar** [comment]
Weird, the polkit file looks fine:

```ShellSession
$ grep xfpm-power-backlight-helper $(nix-build -A xfce4-power-manager)/share/polkit-1/actions/org.xfce.power.policy
    <annotate key="org.freedesktop.policykit.exec.path">/run/current-system/sw/bin/xfpm-power-backlight-helper</annotate>
```

And it is installed by default:

https://github.com/NixOS/nixpkgs/blob/a635b5ee0773f24d5ff98157339b9560d4d07ef7/nixos/modules/services/x11/desktop-managers/xfce.nix#L149

Do you have `powerManagement.enable`?

https://github.com/NixOS/nixpkgs/blob/a635b5ee0773f24d5ff98157339b9560d4d07ef7/nixos/modules/config/power-management.nix#L18

**Comment by bobby285271** [comment]
- https://github.com/NixOS/nixpkgs/pull/485180
