### ISSUE TITLE
nix-env --install elinks fails with attribute 'fromTOML' missing

### ISSUE THREAD

**Issue by romanofski** [NixOS/nixpkgs#77486]
**Describe the bug**
Installing elinks in the current unstable channel fails with:

```
$ nix-env --version

nix-env (Nix) 2.0.4

$ nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.version or lib.nixpkgsVersion'
"20.03pre207234.ec29bb50bf4"

$ nix-env --install elinks
error: attribute 'fromTOML' missing, at /nix/store/ka51kjngvk4qdqjgmclvj9jqbhqdgnw2-nixpkgs-20.03pre207234.ec29bb50bf4/nixpkgs/pkgs/development/tools/poetry2nix/poetry2nix/lib.nix:27:20
(use '--show-trace' to show detailed location information)
The command "nix-env --install elinks" exited with 1.
```

**To Reproduce**
1. Subscribe to the unstable channel
2. Try to install elinks with `nix-env install elinks`
3. see above error message

**Expected behavior**
Installation succeeds and installs elinks

**Screenshots**
None, but I have our current travis build failing at:

https://travis-ci.org/purebred-mua/purebred/jobs/632490879?utm_medium=notification&utm_source=github_status

**Additional context**
None

**Metadata**

```
$ nix-env --version

nix-env (Nix) 2.0.4

$ nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.version or lib.nixpkgsVersion'

"20.03pre207234.ec29bb50bf4"
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
fromTOML only appeared in the nix 2.1: https://nixos.org/releases/nix/nix-2.1/manual/#ssec-relnotes-2.1

**Comment by veprbl** [comment]
Perhaps we should update https://github.com/NixOS/nixpkgs/blob/master/lib/minver.nix

**Comment by veprbl** [comment]
Discussion in the original PR
https://github.com/NixOS/nixpkgs/pull/76646#issuecomment-570817952

cc @adisbladis

**Comment by adisbladis** [comment]
I've added an IFD based fallback for older nix versions that do not have `fromTOML`. https://github.com/NixOS/nixpkgs/pull/77538

**Comment by romanofski** [comment]
@adisbladis Thank you for the fix and thank you for the pointer. I should have known better since I've been using `--attr` now and then. Again cheers for pointing it out.
