### ISSUE TITLE
postgres ensurePermissions not working

### ISSUE THREAD

**Issue by Zhen-hao** [NixOS/nixpkgs#77515]
The following config does give errors when building. But it has no effects on user permissions. I had to run the same command in a psql terminal to get the desired effects.

```
services.postgresql.ensureDatabases = ["mydb"];
services.postgresql.ensureUsers =	[
    {
        name = "me";
        ensurePermissions = {
          "DATABASE mydb" = "ALL PRIVILEGES";
          "ALL TABLES IN SCHEMA public" = "ALL";
        };
      }
];
```

**Comment by aanderse** [comment]
I was unable to reproduce this problem with the configuration provided above.

@Zhen-hao can you give some details on your setup? Which version of NixOS, postgres, etc...? Maybe a snippet of your `configuration.nix` file?

**Comment by Zhen-hao** [comment]
Hi, @aanderse, really sorry not to follow up earlier. I apologize for not providing enough info.
I can't share the whole NixOS configure because it is on our production server. 
I believe the relevant part is what I have posted. 
Maybe someone can post a working example for me to reproduce.
Feel free to close it if there is not much to do at this moment. 
Thank you very much!

**Comment by aanderse** [comment]
@Zhen-hao no problem. What is the actual user account name? The user account name has to match between `postgresql` and the linux account.

The post start `systemd` script looks right? Can you paste some commands to show what user exists is `psql` that you use to check?

Are you familiar with `postgresql` socket based authentication? Did you modify any authentication configuration with your `postgresql` instance?

If there is an unsure I would love to get to the bottom of it so don't feel like you are causing me trouble. Definitely not!

**Comment by Zhen-hao** [comment]
I didn't know about socket-based authentication for Postgres. I only used user/password authentication. Our authentication configuration looks like the following.
```
    authentication = lib.mkForce ''
      # Generated file; do not edit!
      # TYPE  DATABASE        USER            ADDRESS                 METHOD
      local   all             postgres                                peer map=postgres
      local   all             admins                                  peer map=zhen      
      host    all             all             127.0.0.1/32            md5
      host    all             all             ::1/128                 md5
    '';

    identMap = ''
      # MAPNAME       SYSTEM-USERNAME         PG-USERNAME
      zhen            zhen                    admins
      postgres        postgres                postgres
    '';

```

The user `me` is not among it because it is for an app role and doesn't match a Linux user. 
Are you saying that `ensureUsers` works only for Linux users?

**Comment by aanderse** [comment]
> Are you saying that ensureUsers works only for Linux users?

Yes, that is how it currently works. Give it another try after you change the username and let me know please.

**Comment by Zhen-hao** [comment]
Ah, thanks! 
We didn't create a Linux user for each app role. They share the same user. 
Maybe we can change that.
