### ISSUE TITLE
 Package Request: VVVVVV

### ISSUE THREAD

**Issue by kira-bruneau** [NixOS/nixpkgs#77519]
**Project description**
VVVVVV is a retro-styled 2D platformer that has recently been [open-sourced](http://distractionware.com/blog/2020/01/vvvvvv-is-now-open-source/).

**Metadata**

* homepage URL: https://github.com/TerryCavanagh/VVVVVV
* source URL: https://github.com/TerryCavanagh/VVVVVV
* license: [VVVVVV Source Code License v1.0](https://github.com/TerryCavanagh/VVVVVV/blob/master/LICENSE.md)
* platforms: linux & darwin

I have already packaged the game in my NUR repository (https://github.com/MetaDark/nur-packages/tree/master/pkgs/games/vvvvvv), but master is rapidly changing and currently doesn't have any releases. I will hold off on making a pull request until the project starts using releases.

Also, while the core game is open source, the assets are still proprietary. They are obtained from the Make and Play edition of the game.

**Comment by das-g** [comment]
Note that the VVVVVV Source Code License v1.0 disallows distribution for commercial advantage:

>  - You may not alter or redistribute this software in any manner that is primarily intended for or directed toward commercial advantage or private monetary compensation. This includes, but is not limited to, selling altered or unaltered versions of this software, or including advertisements of any kind in altered or unaltered versions of this software.

([deeplink](https://github.com/TerryCavanagh/VVVVVV/blame/f85622b7e95e8b63859e1f03eb900dec10f6ae5a/LICENSE.md#L13))

That doesn't seem to be in line with the Open Source Initiative's "Open Source Definition", particularly with section [1. Free Redistribution](https://opensource.org/osd#free-redistribution):

> The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.

I'm unsure what NixOS's conditions for classifying licenses are. Should the VVVVVV Source Code License v1.0 be considered unfree?

**Comment by MetaDark** [comment]
The wrapper that includes `data.zip` is already marked as unfree. It would probably be safe to also mark the core binary as unfree, with downside that the build couldn't be cached.

**Comment by leo60228** [comment]
I'm still interested in this.
