### ISSUE TITLE
Newest nixos-unstable cannot use string interpolation for `imports` in modules

### ISSUE THREAD

**Issue by aaronjanse** [NixOS/nixpkgs#77541]
**Describe the bug**
String interpolation (as shown below) suddenly seems to be no longer working on nixos-unstable.

```
{ config, lib, pkgs, ... }:
{
  imports = [
    "${builtins.fetchGit { url = "https://github.com/rycee/home-manager"; ref = "master"; }}/nixos"
  ];
}
```

**To Reproduce**
1. Use the nixos-19.09 channel and aa configuration.nix that uses string interpolation imports as shown above
2. Switch to nixos-unstable on xmas. Run `nixos-rebuild switch --upgrade`
2. Configuration still builds
3. Run `nixos-rebuild switch --upgrade` today (or maybe up to a few days ago)
5. Configuration no longer builds, failing with the following error for both home-manager and nixos-hardware: (but with the paths changed, of course)

```
error: the string '/nix/store/g7lxfz8hd2aiia6j8c6gj2pr7br1wnrx-source/nixos' is not allowed to refer to a store path (such as '/nix/store/g7lxfz8hd2aiia6j8c6gj2pr7br1wnrx-source')
(use '--show-trace' to show detailed location information)
```

(see [this gist](https://gist.github.com/aaronjanse/0102704868c7d9acb6bb394bc6ecff7f) for --show-trace)

**Expected behavior**
I expected imports with string interpolation to be legal just as they were a few weeks ago.

**Additional context**
I have reproduced this on two separate XPS 13 laptops.

Is this a Nix issue instead of Nixpkgs? I reported it here instead of the Discourse because this seems bug-like and depend on which version of nixpkgs that I use.

I don't have time to bisect today but I thought it would still be good to document what I know so far.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.18, NixOS, 20.03.git.be3f887 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre208857.e4134747f56"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information: (not sure what to put here)
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by eadwu** [comment]
It's been fixed in master, had the same issue.

**Comment by aaronjanse** [comment]
Hmmm, how would I update to this fix on my machine? I'm using nixos-unstable and even tried switching using the `-I` flag to a nixpkgs git repo.

**Comment by eadwu** [comment]
`-I nixpkgs=$PATH`.
