### ISSUE TITLE
pythonPackages causes nix-shell to be impure

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#77579]
**Describe the bug**
Suppose I have a shell.nix like so:
```
{ pkgs ? import <nixpkgs> {}}:
pkgs.python3Packages.jupyter_core
```
The result of `nix-shell --pure /my/path/to/shell.nix` depends on if the current working directory contains a `setup.py` or not. If so, this will be built and included in the shell. This is undesirable as it introduces an impure dependency that can be very tricky to troubleshoot.

**Comment by FRidh** [comment]
This is intentional and documented behavior to (partially) support development mode. I don't know what it is you wanted to do here, but if you just want to *use* packages from Nixpkgs, don't use `nix-shell` but use `nix run`.

**Comment by tbenst** [comment]
@FRidh yes I’m aware of development mode and use it regularly—it’s very useful! Here’s what the [documentation says](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#develop-local-package):
> If we create a shell.nix file which calls buildPythonPackage, and if src is a local source, and if the local source has a setup.py, then development mode is activated.


The behavior does not match. In the shell above I neither used `buildPythonPackage` nor set `src` to something local. Even if I had set `src` it would be relative to the `.nix` file, not `cwd` per Nix documentation.

**Comment by tbenst** [comment]
@FRidh could you reopen, or should I move discussion to discourse?

Another downside of current approach is the shell has to be re-built each time it's run in a new working directory, even if there are no python packages in that directory. This is particularly painful for me as I'm using the shell as a shebang script
