### ISSUE TITLE
Can't resume after hibernate

### ISSUE THREAD

**Issue by bakhtiyarneyman** [NixOS/nixpkgs#77584]
## Issue description

Machine doesn't resume after hibernate. Instead it goes through cold boot.

### Steps to reproduce

`systemctl hibernate`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.11, NixOS, 19.09.1300.08e503bac6d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1300.08e503bac6d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
https://github.com/niobium0/nixos-configs
[hibernate.log](https://github.com/NixOS/nixpkgs/files/4051745/hibernate.log)

**Comment by lourkeur** [comment]
Hi Bakhtiyar,

Your swap devices aren't listed in titanium.nix. Could you try again after adding them? I understand you have only `/dev/nvme0n1p2` right?

Failing that, can you try setting `boot.resumeDevice` to what seems appropriate and trying again?

**Comment by bakhtiyarneyman** [comment]
Adding a swap device fixed the problem, thank you so much! 

There was a brief period where touchpad wouldn't work after resume, but that seems to automagically have gone away.
