### ISSUE TITLE
Haskell package gi-gdkx11 fails to build

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#77588]
## Issue description

The Haskell package `gi-gdkx11` fails to build in the current unstable channel.

I'm not really across what is going on, but I believe the problem is that in [this commit](https://github.com/NixOS/nixpkgs/commit/2447c661d98dcccc6c1e9680edce7ac1387f9a00#diff-4f63d2d4f72ec861d911535a87a006a6) we updated `gi-gdkx11` from version 3.0.9 to 4.0.1. The newer version has a pkg-config dep on `gtk4-x11` where the old one needed `gtk3`; the nix description just passes null for that.

The Haskell `gi-gdk` package is in a similar situation, but there nixpkgs has version `3.0.22` as the default, and the gtk4 version under a separate `gi-gdk_4_0_1` name. I think we just need to set the same scheme up for `gi-gdkx11` as well?

### Steps to reproduce

`nix build nixpkgs.haskellPackages.gi-gdkx11`

## Technical details

```
building '/nix/store/1bwwkjlcqmpdhqh6m7mia5d1i37n9bib-gi-gdkx11-4.0.1.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/3gahzbx1zk54wlnrnpw8wdbcbdrzxqhd-ghc-8.6.5.
unpacking sources
unpacking source archive /nix/store/jgnqnyrw29hnnzm5270fic3g4ry43y6b-gi-gdkx11-4.0.1.tar.gz
source root is gi-gdkx11-4.0.1
setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file gi-gdkx11-4.0.1/stack.yaml
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/iqh9x5w03c8blqgp04y2ds2mavxc3c0m-gi-gdkx11-4.0.1 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/m66bylr2m102l523j5n5xk9jklgk7yqy-gi-gdkx11-4.0.1-doc/share/doc/gi-gdkx11-4.0.1 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-option=-j4 --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/axz48r922883wzpn3gpcg6lfmc4lxmz1-ncurses-6.1-20190112/lib --extra-lib-dirs=/nix/store/xcsv3hl6q072i63msbfjawsj3m56hq75-libffi-3.3/lib --extra-lib-dirs=/nix/store/2ag15c55hn2kk190qck2ghqd1zcapi8k-gmp-6.1.2/lib --extra-include-dirs=/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/include --extra-lib-dirs=/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/lib --extra-include-dirs=/nix/store/08gcl08524dw6r89rilgsqqdgc3j6yw1-libffi-3.3-dev/include --extra-lib-dirs=/nix/store/08gcl08524dw6r89rilgsqqdgc3j6yw1-libffi-3.3-dev/lib --extra-lib-dirs=/nix/store/xcsv3hl6q072i63msbfjawsj3m56hq75-libffi-3.3/lib --extra-include-dirs=/nix/store/g59xwl0sddrb7pp8sz2fzsc51giwcj2h-glib-2.62.4-dev/include --extra-lib-dirs=/nix/store/g59xwl0sddrb7pp8sz2fzsc51giwcj2h-glib-2.62.4-dev/lib --extra-include-dirs=/nix/store/72mklszjlpy55iiici6waz69dm5sphgf-zlib-1.2.11-dev/include --extra-lib-dirs=/nix/store/72mklszjlpy55iiici6waz69dm5sphgf-zlib-1.2.11-dev/lib --extra-lib-dirs=/nix/store/a3q9zl42d0hmgwmgzwkxi5qd88055fh8-zlib-1.2.11/lib --extra-include-dirs=/nix/store/7f9bh6wv0a7sss0kh3nx7w3w779sysvy-gettext-0.20.1/include --extra-lib-dirs=/nix/store/7f9bh6wv0a7sss0kh3nx7w3w779sysvy-gettext-0.20.1/lib --extra-include-dirs=/nix/store/6dv8b6clv953gl05z0arvgnmvq4fbmsj-glibc-iconv-2.27/include --extra-lib-dirs=/nix/store/y88s9xjbf5i47nbympmpwyssj1l422q1-glib-2.62.4/lib --extra-lib-dirs=/nix/store/car2npv5fxxs8ifgpqidgq052lp1zcrb-gobject-introspection-1.62.0/lib
Using Parsec parser
Did not find a GI repository for GdkX11-4.0 in ["/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/share/gir-1.0","/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/share/gir-1.0","/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/share/gir-1.0","/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/share/gir-1.0","/nix/store/42vd90lpdq2f0d53gnwhpybgmhidcpy7-gobject-introspection-1.62.0-dev/share/gir-1.0"].
CallStack (from HasCallStack):
  error, called at lib/Data/GI/GIR/Repository.hs:89:20 in haskell-gi-0.23.0-JBSVFHZjbEdDIPs6R7ZjaW:Data.GI.GIR.Repository
builder for '/nix/store/1bwwkjlcqmpdhqh6m7mia5d1i37n9bib-gi-gdkx11-4.0.1.drv' failed with exit code 1
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.90, NixOS, 20.03pre209091.100012e55bc (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre209091.100012e55bc"`
 - channels(cumber): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cdepillabout** [comment]
There is a PR that is trying to fix this, but we haven't heard anything from the author since the initial opening:

https://github.com/NixOS/nixpkgs/pull/76883

**Comment by PierreR** [comment]
Looks like `Taffybar` is broken in `20.3`.
@peti  do you know if the PR has been applied for the `20.03` release ?

**Comment by jtojnar** [comment]
Looking at https://github.com/NixOS/nixpkgs/blob/release-20.03/pkgs/development/haskell-modules/configuration-hackage2nix.yaml, it does not look like https://github.com/NixOS/nixpkgs/commit/15d71ed75bffc04157416c4d9fa5be24b5a532b7 made it. Also I do not think Haskell infrastructure is supported outside of unstable/master. https://github.com/NixOS/nixpkgs/commits/release-19.09/pkgs/development/haskell-modules/hackage-packages.nix supports that.

**Comment by cdepillabout** [comment]
@PierreR Yeah, @jtojnar is correct here.

The automatic Hackage updates are not done for the release branches.

However, we do still try to keep packages like Taffybar working in the release branches, so if Taffybar is broken in 20.03, please feel free to send a PR fixing it.

**Comment by PierreR** [comment]
@cdepillabout I guess every application including Taffybar that relies on gi-gdkx11 is broken in 20.03 

Apart from backporting  #79525 in the 20.03 is there a more appropriate fix ?

I understand why the haskell infrastructure in place would only works with unstable/master but then what is the point to propose a stable release based on it ?

**Comment by cdepillabout** [comment]
@PierreR 

> Apart from backporting #79525 in the 20.03 is there a more appropriate fix ?

I think backporting #79525 is the appropriate fix.  Although you'll have to manually update the `pkgs/development/haskell-modules/hackage-packages.nix` file since it doesn't get updated automatically on the release branches.

> I understand why the haskell infrastructure in place would only works with unstable/master but then what is the point to propose a stable release based on it?

I'm not sure what you're asking here.

Are you asking why we have stable nixpkgs branches?  I think it is so that people have a stable base of packages to build upon without having to frequently update versions.  I guess it is the same reason most Linux distros are split into a rolling release and a non-rolling stable release.
