### ISSUE TITLE
request: nota 

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#77590]
**Project description**

> Nota is a powerful terminal calculator with rich mathematical notation and chart rendering. It gives you a beautiful language that is readable and easy to type and then renders your input into a beautiful notation with result

See website (below).

**Metadata**

* homepage URL: https://kary.us/nota/
* source URL: http://codes.kary.us/nota/nota.git 
* license: `mpl20`
* platforms: unix, linux, darwin, ...

----

* Might be `unstable` for now/at first (no release tags yet?)
* Builds w/makefile driving what appear straightforward `stack` commands, FWIW.

**Comment by teto** [comment]
damn that looks cool. Reminds me of insect https://github.com/NixOS/nixpkgs/pull/70652 .

**Comment by dtzWill** [comment]
1.0 tagged: http://codes.kary.us/nota/nota/-/tags/V1.0 \o/

I gave this a go, think I sorted out how to approach this-- PR incoming!
