### ISSUE TITLE
propagatedUserEnvPackages vs. propagatedUserEnvPkgs

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#776]
While grepping my local nixpkgs checkout I noticed that some packages seem to have a typo with the user-env propagation mechanism. They use ```propagatedUserEnvPackages``` instead of the correct ```propagatedUserEnvPkgs``` attr.

For some it's clearly wrong, but the reason I don't attach a patch is that KDE seems to do some magic (via their ```passthru``` attr) and I'm not sure how to fix this without breaking KDE.

Maybe someone with more knowledge of the KDE stuff can have a look at this.

**Comment by kirelagin** [comment]
I was also looking for some explanation of this `passthru` attribute in the kde-4 expressions. Looks like it is something specific to it and it was meant to be a generic mechanism to propagate some dependency information but it was not properly implemented (only the propagated-user-env-packages part is used). E.g. `kdelibs/kdelibs.nix` sets `passthru.wantsUdisks2` which is then never used. But I’m not sure how this works exactly. Does anyone know what was going there?

Also it looks like other derivations also have the `passthru` attribute, but I couldn’t figure out how this magic works and what it actually does.

**Comment by risicle** [comment]
@kirelagin `passthru` from what I've learned is supposed to be a set of attributes that will get added to the derivation's set so that other (usually depending) packages can refer to it if needed. Example uses might be using it to expose a particular build setting a derivation was built with so that a depending package can maybe either compile itself differently or make an assertion if it knows it won't work with a dependent package built in a certain way.

**Comment by lethalman** [comment]
Whereas every attribute in a derivation gets passed as environment variable to the builder, `passthru` variables are not, that's it.

**Comment by Profpatsch** [comment]
(triage) git blame tells @ttuegel had something to do with this. Maybe he can clarify?

**Comment by ttuegel** [comment]
> git blame tells @ttuegel had something to do with this. Maybe he can clarify?

No, this was before my time. But, I'll clarify anyway. This pertains only to KDE 4, so it should be closed anyway.
