### ISSUE TITLE
Progress doesn't work on nixos

### ISSUE THREAD

**Issue by dali99** [NixOS/nixpkgs#77609]
**Describe the bug**
`cv`has a program called `progress` which allows you to see the progress of a lot of standard programs (cp, mv, dd, tar, cat, rsync, grep, fgrep, egrep, cut, sort, md5sum, sha1sum, sha224sum, sha256sum, sha384sum, sha512sum, adb, gzip, gunzip, bzip2, bunzip
2, xz, unxz, lzma, unlzma, 7z, 7za, zcat, bzcat, lzcat, split, gpg).

This has worked fine in the past for me, but running progress on nixos always gives me no output even if I am moving files around

it doesn't work in nix-shell, nor does it work if its in systemPackages

**To Reproduce**
1. install `cv`
2. move/copy a large file
3. `progress`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1840.f7d050ed4e3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1840.f7d050ed4e3, nixos-unstable-20.03pre208413.e1eedf29e5d"`
 - channels(dandellion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- cv
```

**Comment by emmanuelrosa** [comment]
What happens when you run `progress` with the `-d` (debug) flag? Any insights?

**Comment by dali99** [comment]
Nope running

`progress -M -d` in one tmux tab and `dd if=/dev/urandom of=file.txt bs=1048576 count=1000` yields nothing with root and without.

Same if it's a background task in the same session.

**Comment by buckley310** [comment]
This is an issue with the `progress` package.
Upstream: https://github.com/Xfennec/progress/pull/128
A workaround: `progress -c coreutils`.
