### ISSUE TITLE
Plugin packaging for OBS

### ISSUE THREAD

**Issue by NilsIrl** [NixOS/nixpkgs#77627]
Follow up to #61482

Integrate OBS plugin better with NixOS.

It intends to fix this:

https://github.com/NixOS/nixpkgs/blob/a23a985594bf7c3eb543bdaf1e7a9c5b6ddd6099/pkgs/applications/video/obs-studio/wlrobs.nix#L1-L7

**Comment by Munksgaard** [comment]
I'd like this to be fixed!

**Comment by kevincox** [comment]
Not stale!  And it looks like the new version has been released.

**Comment by deviant** [comment]
I published #125308 within 8 hours of the OBS release going live, but it still requires someone to hit the merge button :)
