### ISSUE TITLE
imv fails to build on aarch64 (due to freeimage vendoring libpng)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#77653]
**Describe the bug**

I am trying to build `nixpkgs-wayland` for `aarch64-linux`. `imv` is one giving me difficulty. Originally I filed an issue on `imv`: https://github.com/eXeC64/imv/issues/222

But the issue is instead with the libpng inside freeimage:

```/nix/store/mznipnfrls3sdir41xss9jgryhffcic1-binutils-2.31.1/bin/ld: /nix/store/npab969kihgbyzcz9s9k5aqh2m8d4lqx-freeimage-3.18.0/lib/libfreeimage.so: undefined reference to `png_init_filter_functions_neon'```

Basically, libpng applies an incorrect ARM optimization to aarch64 that isn't actually available. From briefly looking at `libpng` in nixpkgs, it seems that we patch with `libpng-apng` patches (and skimming that, it looks like it has a relevant aarch64 patch).

So, my goal is to patch the vendored `libpng` inside FreeImage, similar to how we patch `libpng` itself.

So far I've not had luck. I've tried with both the CRLF and LF patches from the 'apng' project and the regular patch used from the 'libpng-apng' project that is used in nixpkg's libpng. They all fail to apply and some complain about line endings, regardless of if I pipe the patch through dos2unix (or unix2dos) or not.

https://github.com/colemickens/nixpkgs/tree/imv-freeimage

**Comment by colemickens** [comment]
I seem to have fixed this by patching libpng inside of the freeimage source using the same patch as the `libpng` derivation.. I'm just debating whether or not to allow it to be toggle-able as it is in the libpng derivation.

**Comment by katattakd** [comment]
still important to me

**Comment by colemickens** [comment]
still important to me

**Comment by L-as** [comment]
You can close this I think
