### ISSUE TITLE
pybind11 fails to build on mac os

### ISSUE THREAD

**Issue by eldargab** [NixOS/nixpkgs#77660]
**Describe the bug**

Python package `pybind11` fails to build on mac os.

```
...
/tmp/nix-build-python3.7-pybind11-2.4.3.drv-0/source/include/pybind11/pybind11.h:1008:9: error: no matching function for call to 'operator delete'
...
error: build of '/nix/store/hb4rsprwcadi48rkjpvlxp2ahzf2j3p8-python3.7-pybind11-2.4.3.drv' failed
```

**To Reproduce**

```
nix-env -iA nixpkgs.python37Packages.pybind11
```

**Expected behavior**

Package successfully builds

**Metadata**

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(eldar): `""`
 - channels(root): `"nixpkgs-20.03pre207249.7e8454fb856"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by marsam** [comment]
no longer valid
