### ISSUE TITLE
ghcjs-base and ghcjs-prim versions seem inconsistent

### ISSUE THREAD

**Issue by purefn** [NixOS/nixpkgs#7768]
I'm seeing this error when comparing two `JSString` values using GHCJS 

    Could not deduce (Eq JSString) arising from a use of ‘==’

I'm not sure exactly what is going on, but it seems like maybe this commit https://github.com/ghcjs/ghcjs-prim/commit/1d622ffecace0f56a73b7d32b71865d83fa2d496 is in play and this commit https://github.com/ghcjs/ghcjs-base/commit/bcd6988b07d99e7984de92857e87593e882642d3 isn't.

But from what I can tell ghcjs-prim is using the 7.10 branch, which doesn't have the commit removing the `Eq` instance. So, I'm a bit stumped.

@ryantrinkle @cstrahan any ideas?

**Comment by cstrahan** [comment]
@purefn I've opened a PR upstream here: https://github.com/ghcjs/ghcjs-prim/pull/5

**Comment by cstrahan** [comment]
Due to `===` being not reflexive (e.g. `NaN === null`), he's not going to keep the Eq instance. He did, however, accept a patch to introduce the missing `eqRef` definition.

**Comment by purefn** [comment]
Thanks.
