### ISSUE TITLE
fprintd service is broken on nixos-unstable

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#77778]
**Describe the bug**
fprintd service is broken on nixos-unstable

**To Reproduce**
1. `services.fprintd.enable = true`

**Expected behavior**
nixos-rebuild should build the system

**Additional context**
```
configure: error: Package requirements (libfprint > 0.1.0) were not met:

No package 'libfprint' found
```

**Metadata**
https://github.com/NixOS/nixpkgs-channels/commit/7184df6beb88c4f5f3186e5b73d5437a3461ceaf

Maintainer information:
cc @Elyhaka @abbradar
Why not revert #74656 until #75435 is done?

**Comment by Elyhaka** [comment]
Hello, I believe we should revert the #74656 PR for now. Another option would be to use the master version of current `fprintd` but I believe that should not be a perfect idea. I'm monitoring closely the activity on upstream, and it seems that they are [thinking about releasing a 1.90.1](https://gitlab.freedesktop.org/libfprint/fprintd/merge_requests/19) version of `fprintd`.
