### ISSUE TITLE
Jetbrains IDE 2019.3.1 now crashes when launched with splash

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#77815]
Pretty much our jetbrains IDEs are affected by https://github.com/dubreuia/intellij-plugin-save-actions/issues/289

was able to get pycharm-community to work by doing: `pycharm-community nosplash`, but still annoying

regression(although upstream regression) introduced #73879

cc @kolaente  @Lassulus

**Comment by filalex77** [comment]
Can't reproduce with `nixpkgs-review pr 73879 -p jetbrains.pycharm-community`. Both `pycharm-community` (showing the splash screen) and `pycharm-community nosplash` work, I was able to open a project in both.

**Comment by Lassulus** [comment]
I also cannot reproduce this right now. tried with a fresh user profile

**Comment by kolaente** [comment]
A colleague of mine had this problem on ubuntu, he heavily customized his installation with plugins, themes, toolbars etc. He then asked the jetbrains support and they told him the would provide an update. I'd suspect this has the same root cause here, so not necessarily a nix issue I'd guess.

**Comment by jonringer** [comment]
the only plugin that I installed was vim. However, this may be enough to cause the issues I'm seeing. It looks like upstream is aware of the issues, I'll close this ticket. Hopefully this may be useful for some people who have similar plugins as I do.

**Comment by RunOrVeith** [comment]
I have the same problem with mypy, pylint and docker plugins installed
