### ISSUE TITLE
rxvt_unicode should have a dependency on rxvt_unicode.terminfo

### ISSUE THREAD

**Issue by bmuk** [NixOS/nixpkgs#7787]
After adding rxvt_unicode to environment.systemPackages, many terminal applications refuse to open in urxvt unless the value for TERM is modified by the user, as referenced in [this](https://github.com/NixOS/nixpkgs/issues/4768) issue. Adding rxvt_unicode.terminfo fixes this issue, but it is not obvious and may confuse new users. I suggest that rxvt_unicode should imply the installation of rxvt_unicode.terminfo; if there are those who (for what ever reason) wish to install urxvt without the accompanying terminfo, we could possibly have another package that provides that functionality.

**Comment by bluescreen303** [comment]
I agree.
Probably it's enough to just symlink the terminfo output into `rxvt_unicode`'s output itself.
Or perhaps there's a nicer way to have the terminfo propagate into environments?
