### ISSUE TITLE
Nix dependency sytem breaks perl

### ISSUE THREAD

**Issue by daniel-pfeiffer** [NixOS/nixpkgs#7800]
I get perl's @INC with /nix/store/py2az85s8vfbi26pc9mxcp2q2686gkiv-perl-5.20.1/lib/perl5/site_perl/5.20.1(/x86_64-linux-thread-multi)

But when I install modules they all get linked into .nix-profile/lib/perl5/site_perl/5.20.1(/x86_64-linux-thread-multi) which points to /nix/store/0bkf101vlcdgxfalz7b01xmargrymy2z-user-environment/lib/perl5/site_perl/5.20.1(/x86_64-linux-thread-multi)

I am sympathetic to the fact that perl does not depend on the modules installed later, hence can't know about them.  But the perverse effect is that any cron-job or other environment starting perl must export PERL5LIB or use -I to extend the search-path.

My crude solution would be to install perl to such a path /nix/store/py2az85s8vfbi26pc9mxcp2q2686gkiv-perl-5.20.1/././/lib/perl5/5.20.1, artificially extended to to be as long as xxx-user-environment.  Then each user env would have a copy of bin/perl and CORE/libperl.so, where the path gets substituted in the binary (harmless because the string lengths are identical).

A more elegant solution would be to split libperl.so into a tiny @INC setter, that then loads the original one.

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by daniel-pfeiffer** [comment]
I would guess that this is a general problem of all packages that can be later augmented with modules, plugins or what not.  On a normal Linux that path will often be burnt in, such that it works out of the box.  Then from a user perspective I would argue that all such setups are broken in Nix.
Therefore I really think Nix needs a general solution for allowing a profile to inject a path into an exe and so.  Rather than some libperl.so specific functionality, this would have to be some ld magic where a small wrapper can override the original path.  Maybe the elf section containing the path can be invalidated and replaced with one from the wrapper...

**Comment by Profpatsch** [comment]
(triage) what’s the way forward?
