### ISSUE TITLE
Update dotnet documentation

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#78054]
Reminder for myself (or someone else if they are really interested) to update dotnet documentation. 

2 major PRs were recently merged which changes the usage pretty significantly, but enables most dotnet use cases:
#73262 
#77961 

Related issue:
#28294

**Comment by worldofpeace** [comment]
@jonringer Release critical documentation for endusers/developers?

**Comment by jonringer** [comment]
Don't think there was much documenation initially.

Are you saying this for the upcoming 20.03 release?
I will make a PR tomorrow.

**Comment by worldofpeace** [comment]
> Don't think there was much documenation initially.
> 
> Are you saying this for the upcoming 20.03 release?
> I will make a PR tomorrow.

We should make an effort each release tracking what documentation needs updating/changing/adding. I will take that as a yes :+1:  (adding it to the milestone)

Perhaps we should have a documentation for release project.
