### ISSUE TITLE
re-run of nixos-rebuild may be failed if the first run of nixos-rebuild failed 

### ISSUE THREAD

**Issue by shen390s** [NixOS/nixpkgs#7806]
1. run nixos-rebuild as normal
```
[root@pc13x:~/tmp/nix]# nixos-rebuild switch --upgrade     
downloading Nix expressions from ‘https://nixos.org/releases/nixos/14.12/nixos-14.12.658.ccf672c/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5017k  100 5017k    0     0   378k      0  0:00:13  0:00:13 --:--:--  487k
unpacking channels...
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/22inggzrbd5gz2pk34ab73sl5qzf0vcx-system-path.drv
  /nix/store/x30c1qb53fabyvbw2kv373h4j83bvp5y-system-crontab.drv
  /nix/store/i5xab5p6l9f2blsqzrmjq3yhfa4lwgwc-unit-script.drv
```
<the first run has been failed>

2. retry to run nixos-rebuild
```
[root@pc13x:~/tmp/nix]# nixos-rebuild switch --upgrade
downloading Nix expressions from ‘https://nixos.org/releases/nixos/14.12/nixos-14.12.658.ccf672c/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
unpacking channels...
/nix/store/7rlvlgy875zs98y3rz06mmnaaa66vbr7-xz-5.0.7/bin/xz: (stdin): File format not recognized
/nix/store/rygv74phd82c106qynz7l0rmg4rvrlzd-gnutar-1.27.1/bin/tar: This does not look like a tar archive
/nix/store/rygv74phd82c106qynz7l0rmg4rvrlzd-gnutar-1.27.1/bin/tar: Exiting with failure status due to previous errors
builder for ‘/nix/store/z7i9x8hkhz4g3zwcgdy01s3ngwgc2f9p-nixos-14.12.658.ccf672c.drv’ failed with exit code 2
error: build of ‘/nix/store/z7i9x8hkhz4g3zwcgdy01s3ngwgc2f9p-nixos-14.12.658.ccf672c.drv’ failed
cannot unpack the channels at /run/current-system/sw/bin/nix-channel line 150.
```

<failed to retrieve the nixexprs.tar.xz>

3. The reason of problem is caused by following:
```
    if (defined $cacheDir) {
        my $urlHash = hashString("sha256", 1, $url);
        writeFile "$cacheDir/$urlHash.url", $url;
        $cachedHashFN = "$cacheDir/$urlHash.$hashType";
        $cachedTimestampFN = "$cacheDir/$urlHash.stamp";
        @cacheFlags = ("--time-cond", $cachedTimestampFN) if -f $cachedHashFN && -f $cachedTimestampFN;
    }
   
    # Perform the download.
    my @curlFlags = ("curl", $url, "-o", $tmpFile, "--fail", "--location", "--max-redirs", "20", "--disable-epsv", "--cookie-jar", "$tmpDir/cookies", "--remote-time", (split " ", ($ENV{NIX_CURL_FLAGS} || "")));
    (system $Nix::Config::curl @curlFlags, @cacheFlags) == 0 or die "$0: download of ‘$url’ failed\n";

    if (defined $cacheDir && ! -e $tmpFile) {
        # Curl didn't create $tmpFile, so apparently there's no newer
        # file on the server.
        $hash = readFile $cachedHashFN or die;
        $finalPath = makeFixedOutputPath(0, $hashType, $hash, $name);
        unless (isValidPath $finalPath) {
            print STDERR "cached contents of ‘$url’ disappeared, redownloading...\n";
            $finalPath = undef;
            (system $Nix::Config::curl @curlFlags) == 0 or die "$0: download of ‘$url’ failed\n";
        }
    }
```

 when curl run with option "--time-cond" but without new file to be retrieved, the local file will be created but with 0 byte size.

we can verify this by run following:
```
[rshen@pc13x:~/tmp/ex1]$ ls

[rshen@pc13x:~/tmp/ex1]$ curl https://nixos.org/releases/nixos/14.12/nixos-14.12.658.ccf672c/nixexprs.tar.xz -o x.tar.xz --remote-time --time-cond /nix/var/nix/channel-cache/09jbvf525lhchnbfbc1cfwqjwf0s6v6g166jrinlkzak1hmz6r7j.stamp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0

[rshen@pc13x:~/tmp/ex1]$ ls -l 
total 1
-rw-r--r-- 1 rshen wheel 0 May 11 17:44 x.tar.xz
```

**Comment by domenkozar** [comment]
Duplicate of #7669. Curl is updated in `release-14.12`, this shouldn't be happening anymore. Can you paste the output of `$ nix-store -qR `which nixos-rebuild``

**Comment by shen390s** [comment]
information from nix-store $(which nixos-rebuild)
[root@pc13x:/nix/store]#  nix-store -qR $(which nixos-rebuild)
/nix/store/qwwxgsg6l33lhx0v75mgmb077qggh8yl-linux-headers-3.12.32
/nix/store/la5imi1602jxhpds9675n2n2d0683lbq-glibc-2.20
/nix/store/584hmj4dvlp9aj9n4kcc52a5wz1aq9ac-zlib-1.2.8
/nix/store/lg4pnma41vc1vvlb4qsriphk7sq4762r-gcc-4.8.3
/nix/store/jd3gggw5bs3a6sbjnwhjapcqr8g78f5c-attr-2.4.47
/nix/store/c2p56z920h4mxw12pjw053sqfhhh0l0y-acl-2.2.52
/nix/store/wc472nw0kyw0iwgl6352ii5czxd97js2-coreutils-8.23
/nix/store/g9ybksy400pfn7fncw8dqfnz6m7fdyrk-perl-5.20.1
/nix/store/r5sxfcwq9324xvcd1z312kb9kkddqvld-bash-4.3-p30
/nix/store/2x9j7m0amgkhjg5wc8kw5qz0nxbj5iji-openssl-1.0.1m
/nix/store/56wza7bidg7xcvwqia1n4z2z6v39sh75-sqlite-3.8.7.4
/nix/store/d4b4avbsbcz4hbf35r1270rdkfk7gf7y-perl-DBI-1.631
/nix/store/45pawzla9avx638da2ik38kx9izr8cdj-perl-DBD-SQLite-1.44
/nix/store/7rlvlgy875zs98y3rz06mmnaaa66vbr7-xz-5.0.7
/nix/store/z0mhv10hyby5iza7024qcv2cmq3zx15s-libssh2-1.4.3
/nix/store/glz6p2cvfbhpjzqa6dxb9fi2chi93xsw-curl-7.42.0
/nix/store/ahnd93rm9fyia8zcxsncd49ik7qps1gr-perl-WWW-Curl-4.17
/nix/store/dqmh55k38i24h9xnb4qb5pqggfl4dvxm-bzip2-1.0.6
/nix/store/rygv74phd82c106qynz7l0rmg4rvrlzd-gnutar-1.27.1
/nix/store/sr65fbmyvsrzd4vbgvx1pkqm6a04hzas-gzip-1.6
/nix/store/x8l1vvq8fbwlx1iizf5sx2blb4fqcrlh-boehm-gc-7.2f
/nix/store/4kz3b6q83z1zqdrwp700ajqh66zyn3f2-nix-1.8
/nix/store/z5m93j90697jm3rl3l850nj3anzab0h9-nixos-rebuild

curl version 7.42.0 caused the problem

I will try to upgrade to the newest 14.12

**Comment by shen390s** [comment]
maybe it's better to add safe guard for this case, the problem will occur easily  when network connection is not very stable

**Comment by shen390s** [comment]
upgrade to 14.12.658.ccf672c can solve the problem

[root@pc13x:/nix/store]# nixos-rebuild switch --upgrade
downloading Nix expressions from ‘https://nixos.org/releases/nixos/14.12/nixos-14.12.658.ccf672c/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
unpacking channels...
created 2 symlinks in user environment
building Nix...
building the system configuration...
^Cerror: interrupted by the user

[root@pc13x:/nix/store]# nixos-rebuild switch --upgrade
downloading Nix expressions from ‘https://nixos.org/releases/nixos/14.12/nixos-14.12.658.ccf672c/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
unpacking channels...
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...

[root@pc13x:/nix/store]# nixos-version 
14.12.658.ccf672c (Caterpillar)

**Comment by domenkozar** [comment]
Yeah, it was a problem for a week but it's now gone.
