### ISSUE TITLE
`nixos-install` from the installation media unable to handle `builtins.fetchGit`

### ISSUE THREAD

**Issue by snicket2100** [NixOS/nixpkgs#78127]
**Describe the bug**
`nixos-install` when run from the installation media doesn't have access to `git` which makes it unable to resolve `builtins.fetchGit` expressions in `configuration.nix`.

**To Reproduce**
1. Boot the installation media.
2. Proceed with the standard installation steps (`nixos-generate-config --root /mnt` etc.).
3. Edit `/mnt/etc/nixos/configuration.nix` so that it refers to `builtins.fetchGit { ... }` in at least one place.
4. Run `nixos-install --root /mnt` and see it fail.

**Expected behavior**
Would be nice if I could build any complex configurations using `nixos-install`, including ones referring to `builtins.fetchGit { ... }`.

**Screenshots**
none

**Additional context**
If I run `nix-env -i git` before running `nixos-install --root /mnt`, the installation succeeds.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7, NixOS, 20.03pre198214.4cd2cb43fb3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
???

**Comment by worldofpeace** [comment]
I believe we would have to install `git` to the installation media profiles.
I've actually noticed this also and it's a nuisance if you use `builtins.fetchGit`.

**Comment by snicket2100** [comment]
happy to do it myself, just that I'm pretty new to nix and probably somebody would need to show me around how these images get generated

**Comment by worldofpeace** [comment]
@snicket2100 You can add `gitFull` at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/base.nix. I'm not sure if we should use the full version of git, or the regular one.

**Comment by snicket2100** [comment]
@worldofpeace does it mean that the fact that `nixos-rebuild` can see `git` is only because I have it in `systemPackackes`...? :/

**Comment by worldofpeace** [comment]
> @worldofpeace does it mean that the fact that `nixos-rebuild` can see `git` is only because I have it in `systemPackackes`...? :/

By having `git` in `systemPackages` the realized configuration is resultant in a running system having `git`. In the install media you still have access to `nix-env` to install a package imperatively.

**Comment by snicket2100** [comment]
@worldofpeace hmm but imagine I an not running the installation media but my NixOS machine, not having `git` in `systemPackages`. Would `fetchGit` work if I do `nixos-rebuild` or not?

**Comment by worldofpeace** [comment]
> @worldofpeace hmm but imagine I an not running the installation media but my NixOS machine, not having `git` in `systemPackages`. Would `fetchGit` work if I do `nixos-rebuild` or not?

`fetchGit` needs the `git` executable. So it wouldn't work without it.
You can use `nix-shell -p git` to use nixos-rebuild or `nix-env -iA nixos.git`.

**Comment by worldofpeace** [comment]
We discussed in nixos-dev on adding `git` totthe minimal media https://logs.nix.samueldr.com/nixos-dev/2020-01-21#2991326; and I believe we concluded that we be a bit much.
But it would probably be fine the graphical one.

**Comment by snicket2100** [comment]
https://github.com/NixOS/nixpkgs/pull/79098 adding it to the graphical one then

**Comment by danbst** [comment]
nixos-install without internet... is very strange. I wouldn't even bother doing that.

But if we have internet, we can prefetch git before evaluating configuration. Just like we prefetch Nix before building system.

Since this issue is not yet resolved for minimal image, I'll leave it open.

**Comment by AkechiShiro** [comment]
Is there any news, about this issue @worldofpeace  ? Still relevant ? Shouldn't it be closed ? I mean, this ought to be closed and a warning/note be made in the NixOS manual or the installation guide, saying that the Graphical ISO must be used if one plans to use `git`.

**Comment by SuperSandro2000** [comment]
builtins.fetchGit is an internal functions. Please use pkgs.fetchgit which works offline.
