### ISSUE TITLE
binutils 2.33.1

### ISSUE THREAD

**Issue by guibou** [NixOS/nixpkgs#78197]
**Describe the bug**

`binutils` is currently `2.31.1` in nixpkgs master. It was released in July 2018.

`2.33.1` was released in October 2019. It contains a few improvements and may also contains fix for some vulnerabilities: https://github.com/NixOS/nixpkgs/issues/63061

Is there a reason to keep the old version in nixpkgs, other than a lack of manpower?

I'd be happy to do this work, but I just want to be sure that I was not starting a long, difficult and redundant work. I already tried a "naive" bump of the `version` and `sha256` but it does not work, mostly because most of the patchs are not valid anymore.

**Comment by lovesegfault** [comment]
This was solved by https://github.com/NixOS/nixpkgs/pull/85951

cc. @flokli @veprbl

**Comment by guibou** [comment]
Thank you for continuing this work!
