### ISSUE TITLE
nix-shell eats all avaliable ram for a certain derivation

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#78202]
**Describe the bug**
nix-shell eats all avaliable ram for a certain derivation if you invoke it in a certain way

**To Reproduce**
1. Clone nixpkgs and pull `flutter-init` branch from `https://github.com/babariviere/nixpkgs`
2. Add this to `.config/nixpkgs/config.nix`:

```
{
  allowUnfree = true; 
  android_sdk.accept_license = true;
  packageOverrides = pkgs: with pkgs; rec {
    np = import (builtins.fetchGit {
      url = /path/to/nixpkgs;
      ref = "flutter-init";
    }) {};
  };
}
```
3. Run this command:

    nix-shell -p np.flutterPackages.stable

This should start instantiating the derivation without any issue

4. Run this command:

    nix-shell -p np.flutter

This will cause nix-shell to eat up all the available ram. Run with a system moniter and be prepared to kill it.

This happens even though both `np.flutterPackages.stable` and `np.flutter` refer to same derivation:

https://github.com/babariviere/nixpkgs/tree/flutter-init/pkgs/top-level/all-packages.nix#L25726

**Metadata**
```
 - system: `0`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(saga): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
I would avoid importing a copy of nixpkgs from a function that is evaluated in calculating the fixed point. Try moving the import into a `let ... in` block from out of the function. This should at least improve the performance.
