### ISSUE TITLE
Webkitgtk fails to build on master

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#78212]
bisect'd commit to https://github.com/NixOS/nixpkgs/commit/6803c951a7d5250fc25002c63977dbd725b6bac5

cc @teto @magnetophon

**Comment by jonringer** [comment]
hydra log: https://hydra.nixos.org/build/110721190/nixlog/1

**Comment by jonringer** [comment]
actually, I let the build finish locally. Seems to be fine, just times out on hydra for some reason

**Comment by hedning** [comment]
Hmm, yeah, this looks like one of these weird failures where the build looks like it has finished successfully, and fetching the derivation from the cache works, but reverse dependencies fail.

I've seen those a quite a few times. Not entirely sure what's the cause. Maybe a transient failure that's been restarted manually? (I don't think reverse dependencies are restarted automatically on hydra). That would make sense as I tried to do a nix-review of gjs yesterday, and that started a webkitgtk build, but today I can fetch it successfully from the cache :confused:

**Comment by teto** [comment]
hourra \o/

**Comment by worldofpeace** [comment]
> That would make sense as I tried to do a nix-review of gjs yesterday, and that started a webkitgtk build, but today I can fetch it successfully from the cache confused

Same here. I don't think this issue is one with webkitgtk though.
I guess it can be closed.
