### ISSUE TITLE
Could not import the zenmapGUI.App module: 'No module named gtk'.

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#78211]
**Describe the bug**
zenmap don't start

```
[davidak@X230:~]$ zenmap 
Could not import the zenmapGUI.App module: 'No module named gtk'.
I checked in these directories:
    /nix/store/860bq2fvahpgmk8bcqaxj1rg0zw0p7xs-nmap-graphical-7.80/bin
    /gtk-2.0
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python2.7/site-packages
    /nix/store/859xdb4bdrli8zfvhcy37hrqzkcdjs91-python2.7-pygtk-2.24.0/lib/python2.7/site-packages
    /nix/store/44h5agf77br5bpzbdki2aj4cv5w4kms1-python2.7-pygobject-2.28.6/lib/python2.7/site-packages
    /nix/store/mm3b9nlb9r8ay8a19g8i8lhq6xa7jp4b-python2.7-pycairo-1.18.1/lib/python2.7/site-packages
    /nix/store/6jlas4s61wawznv6bsanq8f3a8bsmfyr-python2.7-pysqlite-2.8.3/lib/python2.7/site-packages
    /nix/store/860bq2fvahpgmk8bcqaxj1rg0zw0p7xs-nmap-graphical-7.80/lib/python2.7/site-packages
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python27.zip
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python2.7
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python2.7/plat-linux2
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python2.7/lib-tk
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python2.7/lib-old
    /nix/store/q20xz6iq493vha5425cbr4l6q190b39i-python-2.7.17/lib/python2.7/lib-dynload
If you installed Zenmap in another directory, you may have to add the
modules directory to the PYTHONPATH environment variable.
```

**To Reproduce**
1. nix run nixpkgs.nmap_graphical
2. zenmap

same when installed with `nix-env -iA nixos.nmap_graphical`.

**Expected behavior**
zenmap starts :)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1815.caad1a78c47 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.1815.caad1a78c47, nixos-hardware, nixos-unstable-20.03pre208413.e1eedf29e5d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nmap_graphical
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
It works on unstable:

```
[davidak@X230:~]$ nix run -f channel:nixos-unstable nmap_graphical
[152 copied (722.9 MiB), 175.9 MiB DL]

[davidak@X230:~]$ zenmap 

(zenmap:13020): Gtk-WARNING **: 22:00:01.017: GTK+ module /run/current-system/sw/lib/gtk-3.0/modules/libpantheon-filechooser-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 22:00:01.017: Failed to load module "pantheon-filechooser-module"

(zenmap:13020): Gtk-WARNING **: 22:00:01.022: Unable to locate theme engine in module_path: "murrine",
...
```

**Comment by davidak** [comment]
unstable is now stable and it works

20.03.2611.bb8f0cc2279

**Comment by snakepeek** [comment]
Install python-gtk2-dev on kali

installing this solved my issues.

**Comment by iamrk1729** [comment]
can you tell me how to install python-gts2-dev i am getting some error while doing that

**Comment by dpickle13** [comment]
@snakepeek Yes, can you provide a little more clarification on your fix? Thanks in advance!

**Comment by Ashwani247** [comment]
> @snakepeek Yes, can you provide a little more clarification on your fix? Thanks in advance!

sure, gtk2 is not in apt repository so cannot install gtk2-dev package still not able to run zenmap still throwing the same error

**Comment by basherselmo** [comment]
hey everyone can someone help me in this proplem when i try to install zenmap
Could not import the zenmapGUI.App module: 'No module named gtk'.
I checked in these directories:
    /usr/bin
    /usr/share/offsec-awae-wheels/colorama-0.4.3-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/six-1.15.0-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/certifi-2020.4.5.1-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/pycparser-2.20-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/urllib3-1.25.9-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/PySocks-1.7.1-py27-none-any.whl
    /usr/share/offsec-awae-wheels/pyOpenSSL-19.1.0-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/ipaddress-1.0.23-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/chardet-3.0.4-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/soupsieve-1.9.5-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/enum34-1.1.10-py2-none-any.whl
    /usr/share/offsec-awae-wheels/ply-3.11-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/idna-2.9-py2.py3-none-any.whl
    /usr/share/offsec-awae-wheels/beautifulsoup4-4.9.1-py2-none-any.whl
    /usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl
    /usr/share/cffi-wheels/py-1.8.1-py2.py3-none-any.whl
    /usr/lib/python2.7
    /usr/lib/python2.7/plat-x86_64-linux-gnu
    /usr/lib/python2.7/lib-tk
    /usr/lib/python2.7/lib-old
    /usr/lib/python2.7/lib-dynload
    /usr/local/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages
    /usr/lib/python2.6/site-packages
If you installed Zenmap in another directory, you may have to add the
modules directory to the PYTHONPATH environment variable.

**Comment by UnknownSoldier32** [comment]
> Install python-gtk2-dev on kali
> 
> installing this solved my issues.

It took me a while to install all the dependencies manually, but it worked: D

**Comment by kelvin0371** [comment]
I'm still having the same problem, please any help

**Comment by Abdullrahman-Dawaliby** [comment]
> @snakepeek Yes, can you provide a little more clarification on your fix? Thanks in advance!



> I'm still having the same problem, please any help

hi people,
you may found solution but for other guys i want to help
i spent 1 hour finding this but this worked on debian bullseye and it will should work on ubuntu and kali
first go this link 
https://packages.debian.org/buster/python-gtk2
then choose your arch in the end of webpage and select any url and download file
then if you downloaded with browser go to downloads in your terminal then do 
`sudo dpkg -i name of downloaded file`
then you may find error in dependent  so go back to this website https://packages.debian.org/buster/python-gtk2 and select from dependent and select your arch and select url to download and do 
`sudo dpkg -i name of downloaded dependent pkg`
ther reinstall python-gtk2 as described above

**Comment by Anup-Kanse** [comment]
Use this command 
sudo apt install zenmap-kbx
After running this you search the application it will work
