### ISSUE TITLE
breeze icons missing in digikam, qt5ct

### ISSUE THREAD

**Issue by acarrico** [NixOS/nixpkgs#78225]
Main problem: no icons in digikam.  Digikam requires breeze icons.
@ttuegel I've noticed in other bug reports that I need to do something like this:

```
$ QT_QPA_PLATFORMTHEME="qt5ct" qt5ct
$ QT_QPA_PLATFORMTHEME="qt5ct" digikam
```

But when I run ```qt5ct```, there are no icon themes available to choose.

```
$ nix-env --query 
breeze-icons-5.61.0
breeze-qt5-5.16.5
digikam-6.2.0
dmenu-4.9
qt5ct-0.41
xmonad-with-packages-8.6.5
```

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-3-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixpkgs-20.03pre194957.bef773ed53f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Thanks!

**Comment by acarrico** [comment]
Using:

 ```XDG_CURRENT_DESKTOP=kde QT_QPA_PLATFORMTHEME="qt5ct" strace qt5ct```

And searching for ```share/icons``` I see it looking in these two locations:

```
stat("/home/acarrico/.local/share/icons"...
stat("/nix/store/s3774j50ympag50q9npjrwiw6wk9cmav-qt5ct-0.41/share/icons"...
```
But not in the nix store path where the icons reside. I can link that and see the icons in digikam:

```
$ ln -s /nix/store/1mpw4y0pgknjgrwlfq5av649bwb4qqgl-breeze-icons-5.61.0/share/icons/breeze .
$ ln -s /nix/store/1mpw4y0pgknjgrwlfq5av649bwb4qqgl-breeze-icons-5.61.0/share/icons/breeze-dark/ .
```

How is the icon location intended to be communicated?

**Comment by acarrico** [comment]
Those links in my previous comment were created in the ```~/.local/share/icons``` directory.

**Comment by ttuegel** [comment]
`qt5ct` should look in each entry of `XDG_DATA_DIRS` for icon themes. Does your `XDG_DATA_DIRS` include `$HOME/.nix-profile/share`? That is where icon themes installed with `nix-env` will go. If that entry is not present in `XDG_DATA_DIRS`, then I think your shell is probably not configured correctly. If that entry _is_ present, then there is probably a bug in `qt5ct` if it isn't respecting that variable.

**Comment by acarrico** [comment]
Indeed, 

``` XDG_DATA_DIRS=~/.nix-profile/share XDG_CURRENT_DESKTOP=kde QT_QPA_PLATFORMTHEME="qt5ct" qt5ct```

does allow ```qt5ct``` to see the icons. Next I'll investigate the ```XDG_DATA_DIRS``` setup.

Thank you.

**Comment by acarrico** [comment]
How should nixpkgs users know to include ```$HOME/.nix-profile/share``` in ```XDG_DATA_DIRS```?

```XDG_DATA_DIRS``` isn't mentioned in [7. Environment Variables](https://nixos.org/nix/manual/#ch-env-variables), and it isn't configured automatically when ```/etc/profile.d/nix.sh``` sources ```/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh```.

A carefully reading of [2.6. Declarative Package Management](https://nixos.org/nixpkgs/manual/#sec-declarative-package-management) suggests writing ```packageOverides``` to create a ```myProfile``` derivation to fix up missing manual/info pages. I guess this would work for the missing icons too.

In the short term, maybe XDG_DATA_DIRS should be mentioned in one of these sections of the manuals. Am I overlooking a better mechanism?
