### ISSUE TITLE
sbase

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#78228]
**Project description**
sbase is a collection of unix tools that are portable across unix-systems.

**Metadata**

* homepage URL: https://core.suckless.org/sbase/
* source URL: https://git.suckless.org/sbase/
* license: mit
* platforms: unix/linux/darwin

**Comment by dtzWill** [comment]
FWIW I have an expression for sbase in my tree: https://github.com/dtzWill/nixpkgs/blob/nixos-dtz/pkgs/tools/misc/sbase/default.nix

If interested/that looks good, please submit as a PR, should be ready-ish as-is.

**Comment by dtzWill** [comment]
FWIW I also packaged up ubase: https://github.com/dtzWill/nixpkgs/blob/nixos-dtz/pkgs/tools/misc/ubase/default.nix (more utillinux flavored).

**Comment by AndersonTorres** [comment]
@dtzWill still interested?
