### ISSUE TITLE
Darwin can't unpack nghttp2-0.7.13.tar.xz because there's no xz in stdenv

### ISSUE THREAD

**Issue by nomosyn** [NixOS/nixpkgs#7825]
`nix-env -u` leads to the above error.

log here: [gist: $nix-env -u](https://gist.github.com/nomosyn/b0dfc0368dfaf17d62f4)

**Comment by vcunat** [comment]
The relevant part will be
```
/nix/store/18cbyb968m1313sgxfhgyf2cc85fynmi-stdenv-darwin-boot-1/setup: line 500: xz: command not found
do not know how to unpack source archive /nix/store/262dmrsf8cnv9h915rasjsp77rwxgf49-nghttp2-0.7.13.tar.xz
```

Is there no ``xz`` in darwin stdenv?

**Comment by nomosyn** [comment]
nope...

**Comment by ericbmerritt** [comment]
well it is there. Line 108 of `stdenv/darwin/defualt.nix`. The question is why its not being picked up.

**Comment by copumpkin** [comment]
I think back in the days when I wrote that stdenv, there was no `xz` in the early bootstrap phases of the linux stdenv either, which was my model for the new darwin one. They all have an `xz` by the end of the bootstrapping, of course, but in the past `xz` wasn't needed in the earlier phases. It shouldn't be hard to add, but I don't have time to do that. Perhaps if you ask in ##nix-darwin on freenode, you'll get someone who knows what to do.

**Comment by ericbmerritt** [comment]
Ok. looking at this further. It looks like nghttp2 is trying to be downloaded *before* xz. Thats not going to work. Here is what part of my dependency list looks like.
```
unpacking source archive /nix/store/262dmrsf8cnv9h915rasjsp77rwxgf49-nghttp2-0.7.13.tar.xz
/nix/store/18cbyb968m1313sgxfhgyf2cc85fynmi-stdenv-darwin-boot-1/setup: line 500: xz: command not found
do not know how to unpack source archive /nix/store/262dmrsf8cnv9h915rasjsp77rwxgf49-nghttp2-0.7.13.tar.xz
builder for ‘/nix/store/23ss53g8jb0j64yv30d8711gnm05fqpk-libnghttp2-0.7.13.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/8lwp3v6lk673305gqbhrqajcia0daab8-curl-7.42.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/1c0axs0amcwy672ap1wb4fd5m9l5w1lj-xz-5.2.1.tar.bz2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/zp9fq4m5sqflladgvvn4ky5arf7facxb-xz-5.2.1.drv’: 1 dependencies couldn't be built
```

**Comment by vcunat** [comment]
@copumpkin: early phases? Why is nghttp2 needed during bootstrapping?

**Comment by copumpkin** [comment]
Beats me! It might not be, but early bootstrap phases are the only part of the stdenv that I can think of that don't have `xz`. Perhaps someone added a different `fetch*` routine that indirectly uses `nghttp2`?

**Comment by ericbmerritt** [comment]
The patch 5e3fe391 added libnghttp2 as a dependency to curl. Curl is a dependency for pulling anything down. It seems like this is a boot strapping problem of some sort.

This is not the correct fix, but you can get around this temporarily by removing libnghttp2 from curl/default.nix.

**Comment by ericbmerritt** [comment]
essentially, someone made it an optional dependency of curl. However, if it is in pkgs then it tries to get built, and causes a blowup.

**Comment by wkennington** [comment]
It's used to build curl with http2 support. We can switch it to tar.bz2 for
now, but the bootstrap phases should really support xz as applications have
been moving to xz almost exclusively.

**Comment by copumpkin** [comment]
That's fine, it shouldn't be hard to add `xz` support to the bootstrap, and the ongoing (white elephant) pure-darwin branch already has it.

**Comment by vcunat** [comment]
I didn't realize this was needed during bootstrap. Just add ``xz`` to buildInputs of nghttp then, that's the easiest way.

**Comment by wkennington** [comment]
Well, it's optional but used in all the curl builds now as it provides
support for fetching over http2.

**Comment by ericbmerritt** [comment]
you get a infinite recursion error then @vcunat

**Comment by vcunat** [comment]
Oh, we do that in quite a few expressions for packages involved during bootstrap. So *.bz2 source, I guess, as we probably want http2 in fetchurl.

**Comment by wkennington** [comment]
Fixed in 6516cc48c7082700905d23ab32b28a872fdbfa58

**Comment by copumpkin** [comment]
@wkennington will that cause a mass rebuild?

**Comment by nomosyn** [comment]
Well... looks like yes: building for more than 4 min now

**Comment by ericbmerritt** [comment]
@wkennington thats a fix to the symptom but not the underlying problem. That is, that is that, xz should be available earlier in the bootstrapping process. Should we open an issue for that?

**Comment by wkennington** [comment]
Definitely

**Comment by wkennington** [comment]
Fixed by the way

**Comment by jamesthompson** [comment]
The host (pub.wak.io) for `nghttp2-0.7.14.tar.xz` in the fix https://github.com/NixOS/nixpkgs/commit/6516cc48c7082700905d23ab32b28a872fdbfa58 is 404'ing. Any ideas of a workaround?

**Comment by jamesthompson** [comment]
Looks like it's working again...
