### ISSUE TITLE
Imapfilter is broken

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#78304]
**Describe the bug**
The nixos build of imapfilter is broken according to the author:
https://github.com/lefcha/imapfilter/issues/201#issuecomment-574868032

```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - imapfilter
```

**Comment by codygman** [comment]
Yeah, I just tried using imapfilter and ssl verify fails almost certainly because as the linked issue says it can't find ca-certs.

**Comment by codygman** [comment]
I wasn't able to get it working with this either though:

```shell
$ SSLCAFILE=/nix/store/ix06bh151ysvw2rrggk158bqji67zh6s-etc/etc/ssl/certs/ca-bundle.crt imapfilter -v -e 'a = IMAP { server = "imap.yourserver.com", username = "yourusername", password = "yourpassword", ssl = "auto" }'
imapfilter: initiating SSL connection to imap.yourserver.com; error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
imapfilter: login request to yourusername@imap.yourserver.com failed
```

**Comment by NorfairKing** [comment]
@codygman I worked around this by using an old version of imapfilter. What did you do?

**Comment by NorfairKing** [comment]
@codygman I think I found a way to fix it. Please have a look.

**Comment by makefu** [comment]
for anyone who is affected by the issue but has not yet updated, i currently run 
`imapfilter -t /etc/ssl/certs/ca-bundle.crt`
