### ISSUE TITLE
Downgrade wine-mono

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#78309]
**Describe the bug**

When installing a new prefix, wine takes the wine-mono installer from share/wine/mono and installs it.
However, the needed version is hardcoded:
```
[pid 12196] openat(AT_FDCWD, "/nix/store/f5n2fkylvyyvd6faj11h3x7agbdv3c33-wine-4.0.2/share/wine/mono/wine-mono-4.7.5.msi", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
```

nixpkgs bundles the wrong version, which is currently 4.9.2.
So we either patch the source code so it looks for the current version, or we downgrade wine-mono.

**To Reproduce**
1. Drop ~/.cache/wine
2. Create a new wine prefix

**Expected behavior**
wine-mono should automatically be installed without any further questions.

cc @avnik @7c6f434c @bendlas

**Comment by dasJ** [comment]
Ah, the version is hard coded at these locations:
```
wine/dlls/mscoree/mscoree_private.h:48:#define WINE_MONO_VERSION "4.9.4"
wine/dlls/appwiz.cpl/addons.c:61:#define MONO_VERSION "4.9.4"
```

The msi path is bu

**Comment by worldofpeace** [comment]
@lovesegfault ?

**Comment by lovesegfault** [comment]
@dasJ Can you wait until https://github.com/NixOS/nixpkgs/pull/78246 lands and see how this changes?

**Comment by dasJ** [comment]
I found a workaround for my specific problem, but we should keep track of the general problem of the coupled version.

**Comment by worldofpeace** [comment]
I'm assuming this is resolved. Comment if it isn't

**Comment by avnik** [comment]
Actually whole ticket have are incorrectly formed task. We need to have own wine mono and wine gecko for stable and unstable releases.
