### ISSUE TITLE
Purer extensions interface for Nemo

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#78327]
So installed extensions I guess will get linked at `/run/current-system/sw/lib/nemo/extensions-3.0` and NixOS will link things at `lib`.

It's very popularized within nixos to patch file managers with extensions like
* https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/xfce/core/thunar/thunarx_plugins_directory.patch

so we can set which directory to load extensions from via an environment variable.
And as you've mentioned, we'd use the `symlinkJoin` wrapper 
* https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/xfce/core/thunar/wrapper.nix

and some glue in the nixos module
https://github.com/NixOS/nixpkgs/blob/a65f338ccbd679c1d9f6886d17758d99c80cd938/nixos/modules/services/x11/desktop-managers/xfce.nix#L45

_Originally posted by @worldofpeace in https://github.com/NixOS/nixpkgs/pull/77979_

**Comment by worldofpeace** [comment]
not stale

**Comment by piegamesde** [comment]
> So installed extensions I guess will get linked at `/run/current-system/sw/lib/nemo/extensions-3.0`

How would this work on non-NixOS systems?

**Comment by worldofpeace** [comment]
> > So installed extensions I guess will get linked at `/run/current-system/sw/lib/nemo/extensions-3.0`
> 
> How would this work on non-NixOS systems?

That wasn't the suggested solution but the status quo, currently that will not work on any other platform but NixOS.

**Comment by piegamesde** [comment]
Getting my Nemo extensions back is still rotting on my backlog …

**Comment by bobby285271** [comment]
For people who still interested in this, the above PR should (hopefully) add an initial support for this :bowing_woman:
