### ISSUE TITLE
undefined reference to `gnutls_protocol_set_priority'

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7833]
Several important builds fail with that error, i.e.:

- git-annex: http://hydra.cryp.to/build/838505
- gwenhywfar-4.10.0beta: http://hydra.cryp.to/build/835742/nixlog/9/raw

Does anyone know what caused this linker error?

**Comment by lethalman** [comment]
@peti gnutls update merged from staging... cc @wkennington

**Comment by vcunat** [comment]
It's probably best to just override ``gnutls`` to ``gnutls33`` for the failing packages.

**Comment by peti** [comment]
ede1606 and 248b8ee.
