### ISSUE TITLE
Pass Extensions not working(pass-import, pass-update, pass-tomb ...)

### ISSUE THREAD

**Issue by Sathish-n** [NixOS/nixpkgs#78353]
**Describe the bug**
$ pass import
Error: import is not in the password store.

**To Reproduce**
1. Install pass globally through configuration.nix
```
  environment.systemPackages = with pkgs; [
    ### Pass
    pass
    passExtensions.pass-audit
    passExtensions.pass-genphrase
    passExtensions.pass-import
    passExtensions.pass-otp
    passExtensions.pass-tomb
    passExtensions.pass-update
    (pass.withExtensions (ext: with ext; [ pass-audit pass-otp pass-import pass-genphrase pass-update pass-tomb]))
  ];
```

**Expected behavior**
Pass import and other extensions working without error.
```
pass import keepassxml keepass.xml
(*) Importing passwords from keepass
 .  File: keepass.xml
 .  Number of password imported: 6
 .  Passwords imported:
       Social/mastodon.social
       Social/twitter.com
      
```

**Additional context**
Other pass extensions are also not working

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.96, NixOS, 19.09.1155.bae4d7daa01 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(quark): `"nixpkgs-20.03pre207249.7e8454fb856"`
 - nixpkgs: `/home/sathish/.nix-defexpr/channels/nixpkgs`

**Comment by danbst** [comment]
The order of your packages matters. You have both `pass` and `pass.withExtensions` in your global packages defined. The order of packages is important, because who comes first - wins. See an example:
```
$ nix-shell -E 'with import ./.{}; mkShell { buildInputs = [ 
    pass 
    (pass.withExtensions (ext: with ext; [pass-import])) 
]; }'

[nix-shell]$ pass import
Error: import is not in the password store.

$ nix-shell -E 'with import ./.{}; mkShell { buildInputs = [ 
      (pass.withExtensions (ext: with ext; [pass-import])) 
      pass 
]; }'

[nix-shell]$ pass import
 [x] Error: password manager not present. See 'pass import -h'
```
(but there are also `hiPrio` and `lowPrio` modifiers, which can change priority of a package)
