### ISSUE TITLE
package request: Peergos

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#78362]
**Project description**
An end-to-end encrypted, peer-to-peer file storage, sharing and communication network.
It's written in Java and uses IPFS. A bit similar to Nextcloud. 

**Metadata**

* homepage URL: https://peergos.org/
* source URL: https://github.com/Peergos/Peergos
* license: AGPL3
* platforms: linux (JVM)

**Comment by mehlon** [comment]
Related: https://github.com/Peergos/Peergos/issues/629

**Comment by bqv** [comment]
Still important

**Comment by bbigras** [comment]
Still important

**Comment by raspher** [comment]
I've a working package of peergos. after some testing i've experienced it a little buggy, so i don't want to push it into release. Let's see what i can do as it's my first package.

The example bug: after i've created task, clicking "tasks" from left menu forces me to create new task. However thecreated task is visible in my drive.

**Comment by bbigras** [comment]
Thanks!
