### ISSUE TITLE
TLS on wine doesn't work inside the sandbox

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#78365]
**Describe the bug**

Oof, this might be a very specific issue, but I wanted to report it anyway so it might save some time for other people troubleshooting the same issue.
I run a downloader in a nix build using wine. However, it seems like the [root certificate locations are hard coded](https://github.com/wine-mirror/wine/blob/6d801377055911d914226a3c6af8d8637a63fa13/dlls/crypt32/rootstore.c#L438).
This means I cannot establish any TLS connections from wine inside the nix sandbox.

**To Reproduce**
1. Try a TLS connection from wine inside a nix build

**Expected behavior**
There should be a way to specify the ca certificates.

**Additional context**
This does fix the issue for me:
```patch
diff --git a/dlls/crypt32/rootstore.c b/dlls/crypt32/rootstore.c
index f795181..fb4926a 100644
--- a/dlls/crypt32/rootstore.c
+++ b/dlls/crypt32/rootstore.c
@@ -18,6 +18,7 @@
 #include "config.h"
 #include <stdarg.h>
 #include <stdio.h>
+#include <stdlib.h> /* getenv */
 #include <sys/types.h>
 #ifdef HAVE_SYS_STAT_H
 #include <sys/stat.h>
@@ -916,6 +917,11 @@ static void read_trusted_roots_from_known_locations(HCERTSTORE store)

         for (i = 0; !ret && i < ARRAY_SIZE(CRYPT_knownLocations); i++)
             ret = import_certs_from_path(CRYPT_knownLocations[i], from, TRUE);
+
+        char *nix_cert_file = getenv("NIX_SSL_CERT_FILE");
+        if (nix_cert_file != NULL)
+            ret = import_certs_from_path(nix_cert_file, from, TRUE);
+
         check_and_store_certs(from, store);
     }
     CertCloseStore(from, 0);
```

If you're all okay with that, I can create a nixpkgs PR for this.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: wine
# a list of nixos modules affected by the problem
module:
```

cc @avnik @7c6f434c @bendlas @lovesegfault

**Comment by 7c6f434c** [comment]
Hm. I wonder if we should just apply this to the Wine package.

**Comment by avnik** [comment]
@7c6f434c on first glance offered patch looks obivious

**Comment by lovesegfault** [comment]
Yeah, I think adding this patch makes sense

**Comment by dasJ** [comment]
I opened #78406
