### ISSUE TITLE
sgtk-menu

### ISSUE THREAD

**Issue by eoli3n** [NixOS/nixpkgs#78370]
**Project description**
Simple menu, that behaves decently on sway, but also on i3 window manager.

**Metadata**

* homepage URL: https://github.com/nwg-piotr/sgtk-menu
* source URL: https://github.com/nwg-piotr/sgtk-menu
* license: gpl3 https://github.com/nwg-piotr/sgtk-menu/blob/master/LICENSE
* platforms: linux

**Comment by eoli3n** [comment]
nobody ?

**Comment by jtojnar** [comment]
The [successor project](https://github.com/nwg-piotr/nwg-launchers) by the same author has been packaged  in https://github.com/NixOS/nixpkgs/pull/93189.
