### ISSUE TITLE
cudatoolkit 10.2 is broken

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#78431]
**Describe the bug**
I believe the build failure emerged post https://github.com/NixOS/nixpkgs/commit/7a01e9096e94c924374eff58ace157ba2bcbc55d. 

I think the build failure is caused by
```rmdir: failed to remove '/nix/store/vqsy7ga805f95kz7hbkmmdsv2201mi7f-cudatoolkit-10.2.89/share': Directory not empty```

https://hydra.nix-data.org/build/134/nixlog/65/tail

Maintainer information:
cc @nand0p

**Comment by knedlsepp** [comment]
While it builds fine for me on current master on NixOS, the GUI applications actually don't work because of a missing java:
```
A Java Runtime Environment (JRE) or Java Development Kit (JDK)
must be available in order to run Nvvp. No Java virtual machine
was found after searching the following locations:
/nix/store/8lf7wd28llfp6hm8srqwkgzgrvbj5dgv-cudatoolkit-10.2.89/libnvvp/jre/bin/java
java in your current PATH
```
I'm gonna look into fixing that.

Could you provide some information on your exact setup (In the issue template this is listed as:
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.)

**Comment by tbenst** [comment]
Based off of a recent master commit: https://github.com/nixos/nixpkgs/commit/90441b4b47fc7280de6a5bd1a228017caaa0f97f. Technically there's a few extra commits but they only effect python / VScode: https://github.com/tbenst/nixpkgs/commits/nix-data-2020-01-22.

**Comment by knedlsepp** [comment]
Are you using sandboxing?

**Comment by tbenst** [comment]
Yes. Other info in the hydra log from first post.

**Comment by tomberek** [comment]
Unable to reproduce with recent nixpkgs versions. Is this still causing issues?

**Comment by tbenst** [comment]
Yes, I think it’s been resolved, thanks!

**Comment by knedlsepp** [comment]
I think then GUI applications might still be broken.

**Comment by tomberek** [comment]
> I think then GUI applications might still be broken.

I have not been able to get nvvp working yet. Ran into issues with gtk, eclipse, libswt, some jars, etc.

**Comment by bitonic** [comment]
I also get the same error as https://github.com/NixOS/nixpkgs/issues/78431#issuecomment-580678922 when trying to run the GUIs (e.g. nsight).
