### ISSUE TITLE
Upgrading Bazel to 2.0 breaks tensorflowWithCuda

### ISSUE THREAD

**Issue by Zhen-hao** [NixOS/nixpkgs#78472]
Upgrading Bazel to 2.0 breaks tensorflow build. 

this pull request
https://github.com/NixOS/nixpkgs/pull/76851
breaks
`python37Packages.tensorflowWithCuda`

to reproduce: just try installing `python37Packages.tensorflowWithCuda` with the unstable branch. Or see https://github.com/NixOS/nixpkgs/issues/77771

**Comment by cdepillabout** [comment]
cc @timokau @FRidh @jonringer (some of the people who were active on the recent PR upgrading tensorflow to 2.0: https://github.com/NixOS/nixpkgs/pull/70910)

**Comment by Zhen-hao** [comment]
@cdepillabout thanks! 
I agree we should close this one.
hopefully, I can contribute to this later.
