### ISSUE TITLE
Teamviewer 8 doesn't start

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#785]
it says daemon is not running, it think it's even not packaged. cc @viric

**Comment by danbst** [comment]
Teamviewer 8 is outdated and teamviewer service is already implemented
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/monitoring/teamviewer.nix

issue can be closed?

**Comment by domenkozar** [comment]
yup
