### ISSUE TITLE
nix shows "nixpkgs.*" instead of "nixos.*"

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#78529]
**Describe the bug**
nix shows nixpkgs.* package names instead of nixos.* on NixOS.

Example:
```
$ nix search hello
...
* nixpkgs.hello (hello)
  A program that produces a familiar, friendly greeting
...
$ nix-env -iA nixpkgs.hello
error: attribute 'nixpkgs' in selection path 'nixpkgs.hello' not found
$ nix-env -iA nixos.hello
installing 'hello-2.10'
```

**To Reproduce**
1. Run NixOS
2. search for a package

**Expected behavior**
```
$ nix search hello
...
* nixos.hello (hello)
  A program that produces a familiar, friendly greeting
...
```

**Comment by doronbehar** [comment]
See https://discourse.nixos.org/t/how-is-nix-path-managed-regarding-nix-channel/6079/ and https://discourse.nixos.org/t/use-only-1-channel-for-my-users-nix-env-and-roots-nixos-rebuild/6311/15
