### ISSUE TITLE
Bug in fetchFromGithub

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#78538]
## Issue description

Apparantly `fetchSubmodules` argument is not considered while calculating output hash. Also `fetchSubmodules` is not mentioned in `nixpkgs` manual:

### Steps to reproduce

1. Run `nix-collect-garbage`

2. Try to build this derivation:
```
    rofi-latest = rofi.override {
      rofi-unwrapped = rofi-unwrapped.overrideAttrs (
        o: rec {
          src = fetchFromGitHub {
            owner = "davatorium";
            repo = "rofi";
            rev = "a35a898";
            sha256 = "0d79iarrrfqrqcq4j4frdnycnfsd5dnnz7q21q8y4bzlni2cq7r6";
            # fetchSubmodules = true;
          };
        }
      );
    };
```

It will fail since submodules are not fetched

3. Uncomment `fetchSubmodules` lines and try to build it again. It will fail since nix will try to build the source fetched in step 2 to build this new derivation as well.

4. Run `nix-collect-garbage` again, change the `sha256` to `0d79iarrrfqrqcq4j4frdnycnfsd5dnnz7q21q8y4bzlni2cq7r6`, and try to build it again. It should work.

## Technical details

```
 - system: `0`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(saga): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by veprbl** [comment]
The fixed output derivations are not rebuilt when you change the arguments other than name and hash. This is made by-design and not considered as a bug.

**Comment by worldofpeace** [comment]
Closing as this has been discussed in length pretty much everywhere.
I wish I had a resource to link for you @fctorial. But @veprbl advice should be sufficent.

**Comment by fctorial** [comment]
@worldofpeace Yes. "fixed output derivations" was enough to find the discussions.
