### ISSUE TITLE
Cross compiling glibc for aarch64 on macOS fails

### ISSUE THREAD

**Issue by golddranks** [NixOS/nixpkgs#78590]
**Describe the bug**
Cross compiling glibc on macOS using `nix-build -A pkgsCross.aarch64-multiplatform.glibc` on the latest staging branch of nixpkgs produces an error.

**To Reproduce**
1. Be on macOS, have nix installed.
2. `git clone https://github.com/NixOS/nixpkgs.git && cd nixpkgs`
3. `git checkout staging`
4. `nix-build -A pkgsCross.aarch64-multiplatform.glibc`
5. Witness the error (only the tail of the build log reproduced here):
```
...
shrinking RPATHs of ELF executables and libraries in /nix/store/c255k53qvk8pszgljl88m5j183bl3qgz-glibc-2.27-aarch64-unknown-linux-gnu-dev
patching script interpreter paths in /nix/store/c255k53qvk8pszgljl88m5j183bl3qgz-glibc-2.27-aarch64-unknown-linux-gnu-dev
checking for references to /private/var/folders/v0/cvmfd5lj1kbfmbmmlt_l7f1c0000gp/T/nix-build-glibc-2.27-aarch64-unknown-linux-gnu.drv-0/ in /nix/store/c255k53qvk8pszgljl88m5j183bl3qgz-glibc-2.27-aarch64-unknown-linux-gnu-dev...
could not find build ID of /nix/store/vfpkr753ppq0a0skzf6rnjnyryxap5d0-glibc-2.27-aarch64-unknown-linux-gnu-static/lib/libmcheck.a, skipping
shrinking RPATHs of ELF executables and libraries in /nix/store/vfpkr753ppq0a0skzf6rnjnyryxap5d0-glibc-2.27-aarch64-unknown-linux-gnu-static
shrinking /nix/store/vfpkr753ppq0a0skzf6rnjnyryxap5d0-glibc-2.27-aarch64-unknown-linux-gnu-static/lib/libmcheck.a
wrong ELF type
patching script interpreter paths in /nix/store/vfpkr753ppq0a0skzf6rnjnyryxap5d0-glibc-2.27-aarch64-unknown-linux-gnu-static
checking for references to /private/var/folders/v0/cvmfd5lj1kbfmbmmlt_l7f1c0000gp/T/nix-build-glibc-2.27-aarch64-unknown-linux-gnu.drv-0/ in /nix/store/vfpkr753ppq0a0skzf6rnjnyryxap5d0-glibc-2.27-aarch64-unknown-linux-gnu-static...
wrong ELF type
find: '/nix/store/fj4dj3rdlydfca5gd36hchf8rczl1h3k-glibc-2.27-aarch64-unknown-linux-gnu-debug': No such file or directory
builder for '/nix/store/hqywchdq9qb9aqg0vz8l0j3rw1svcxib-glibc-2.27-aarch64-unknown-linux-gnu.drv' failed to produce output path '/nix/store/fj4dj3rdlydfca5gd36hchf8rczl1h3k-glibc-2.27-aarch64-unknown-linux-gnu-debug'
cannot build derivation '/nix/store/ahq5krbcjwxna8hbgzbpwq5r00y13kgd-glibc-2.27-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ahq5krbcjwxna8hbgzbpwq5r00y13kgd-glibc-2.27-aarch64-unknown-linux-gnu.drv' failed
```

**Expected behavior**
`pkgsCross.aarch64-multiplatform.glibc` builds without errors.

**Additional context**
A bug possibly related to this was fixed on the staging branch two weeks ago (ref: https://github.com/NixOS/nixpkgs/issues/77504 , https://github.com/NixOS/nixpkgs/pull/76972 , https://github.com/NixOS/nixpkgs/pull/77525). Indeed, when using `nixpkgs-unstable` channel that bug is reproduced. Instead, when checking out the latest `staging` or the commit https://github.com/NixOS/nixpkgs/commit/d08c6c73806eeab39bedfee9d2a02fae2bf1f2ce that contains the fix, it errors with different errors.

Interestingly, when running the build against the commit `d08c6c73`, the error message is slightly different, it's missing the line `find: '/nix/store/fj4dj3rdlydfca5gd36hchf8rczl1h3k-glibc-2.27-aarch64-unknown-linux-gnu-debug': No such file or directory
`:
```
...
shrinking RPATHs of ELF executables and libraries in /nix/store/5kinp1a0wixih3awjm4kfz31iyg2dhjm-glibc-2.27-aarch64-unknown-linux-gnu-dev
patching script interpreter paths in /nix/store/5kinp1a0wixih3awjm4kfz31iyg2dhjm-glibc-2.27-aarch64-unknown-linux-gnu-dev
checking for references to /private/var/folders/v0/cvmfd5lj1kbfmbmmlt_l7f1c0000gp/T/nix-build-glibc-2.27-aarch64-unknown-linux-gnu.drv-0/ in /nix/store/5kinp1a0wixih3awjm4kfz31iyg2dhjm-glibc-2.27-aarch64-unknown-linux-gnu-dev...
could not find build ID of /nix/store/23jvjfvshd9mmm4120rn93xyqd5109lm-glibc-2.27-aarch64-unknown-linux-gnu-static/lib/libmcheck.a, skipping
shrinking RPATHs of ELF executables and libraries in /nix/store/23jvjfvshd9mmm4120rn93xyqd5109lm-glibc-2.27-aarch64-unknown-linux-gnu-static
shrinking /nix/store/23jvjfvshd9mmm4120rn93xyqd5109lm-glibc-2.27-aarch64-unknown-linux-gnu-static/lib/libmcheck.a
wrong ELF type
patching script interpreter paths in /nix/store/23jvjfvshd9mmm4120rn93xyqd5109lm-glibc-2.27-aarch64-unknown-linux-gnu-static
checking for references to /private/var/folders/v0/cvmfd5lj1kbfmbmmlt_l7f1c0000gp/T/nix-build-glibc-2.27-aarch64-unknown-linux-gnu.drv-0/ in /nix/store/23jvjfvshd9mmm4120rn93xyqd5109lm-glibc-2.27-aarch64-unknown-linux-gnu-static...
wrong ELF type
builder for '/nix/store/igqi6m3z9v5pc4rz5gcginjwnv788whi-glibc-2.27-aarch64-unknown-linux-gnu.drv' failed to produce output path '/nix/store/i5kk87a4gzv7vvba0gnvax1rrdnhmjcr-glibc-2.27-aarch64-unknown-linux-gnu-debug'
cannot build derivation '/nix/store/7y3kbgn4q085xyvsnk92fr8km0gajav9-glibc-2.27-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
error: build of '/nix/store/7y3kbgn4q085xyvsnk92fr8km0gajav9-glibc-2.27-aarch64-unknown-linux-gnu.drv' failed
```

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(kon): `"nixpkgs-20.03pre210531.73a59af35bb"`
 - nixpkgs: `/Users/kon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by golddranks** [comment]
I'm very new to Nix, but I'm trying to investigate this problem to the best of my ability. Apparently `/nix/store/igqi6m3z9v5pc4rz5gcginjwnv788whi-glibc-2.27-aarch64-unknown-linux-gnu.drv` which is a dependency of the package, produces build artifacts separately:
```
[("bin","/nix/store/xcp22f640jc3ymqmvdjggfmcwkzi3kr1-glibc-2.27-aarch64-unknown-linux-gnu-bin","",""),
("debug","/nix/store/i5kk87a4gzv7vvba0gnvax1rrdnhmjcr-glibc-2.27-aarch64-unknown-linux-gnu-debug","",""),
("dev","/nix/store/5kinp1a0wixih3awjm4kfz31iyg2dhjm-glibc-2.27-aarch64-unknown-linux-gnu-dev","",""),
("out","/nix/store/9qxmc4vs26kbhg85wvrsbaa1xyn9g1m9-glibc-2.27-aarch64-unknown-linux-gnu","",""),
("static","/nix/store/23jvjfvshd9mmm4120rn93xyqd5109lm-glibc-2.27-aarch64-unknown-linux-gnu-static","","")],
```
In order: binaries, debug info (?), headers, libs, docs & other build artifacts, static libraries/objects. Out of these, debug info doesn't get outputted for some reason.

**Comment by golddranks** [comment]
Indeed, when I set `separateDebugInfo` to `false`, the build succeeds. So there's something wrong with that step.

**Comment by golddranks** [comment]
If there is a way to easily run the build with more logging and doing less things / skipping stuff unrelated to this bug, I'd like to know. I could try to modify the bash scripts to set -x but if there'd s global and easy setting to have more debug print, I'm all ears.

**Comment by matthewbauer** [comment]
Yeah separateDebugInfo does not work on macOS, but we should still be able to get debug info when cross-compiling it.  Perhaps just setting `separateDebugInfo = !stdenv.buildPlatform.isDarwin` is enough here though.

**Comment by matthewbauer** [comment]
This is now working in ee5a73f.
