### ISSUE TITLE
Vulkan has stopped working altogether (amdgpu?)

### ISSUE THREAD

**Issue by shirona** [NixOS/nixpkgs#78657]
Any Vulkan application attempting to launch crashes immediately, including `vulkaninfo`.

**To Reproduce**
1. Install `vulkan-tools`
2. Execute `vulkaninfo`
3. Receive the following message
```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.114

ac_rtld error: !ehdr
ELF error: Request error: not an ELF file
fish: “vulkaninfo” terminated by signal SIGSEGV (Address boundary error)
```
This happens for native programs and non-native programs.

**Additional context**
I'm using the amdgpu driver on a Radeon R9 380. Everything used to work fine before updating today (but I hadn't updated in almost a month, mind you).

Given I can freely switch between the good and bad configurations on runtime, I guess this has nothing to do with the kernel itself.

**Metadata**
Current (malfunctioning) version:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.15, NixOS, 20.03pre210639.e59dcf8ccec (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre210639.e59dcf8ccec"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Last known good version:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206438.a06925d8c60 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre210639.e59dcf8ccec"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by shirona** [comment]
Pinging @Ralith since he is the Vulkan maintainer

**Comment by Ralith** [comment]
Thanks for the ping! That's certainly an interesting failure, and my cold guess is that the driver isn't getting installed correctly, and is triggering a bug in vulkaninfo or the vulkan loader, which we should identify and upstream a fix for. Could you try with #78746, and if it repros, get a backtrace from a debug build?

**Comment by peterzky** [comment]
run strace on vulkaninfo. remove $home/.cache/radv_builtin_shaders64.

**Comment by Ralith** [comment]
If that fixes it, then it's a userspace AMD vulkan driver bug, which should be reported upstream.

**Comment by shirona** [comment]
Yes, deleting `radv_builtin_shaders64` worked! Even though I already tried to delete those files before, it only worked this time. I wonder if it was because the shaders were on cache last time I tried, and now I did it after a cold boot. Either way, now Vulkan runs for real, which is great.

Thanks for the help!

**Comment by Ralith** [comment]
Were you able to open an upstream bug report? This might affect others.

**Comment by davidak** [comment]
FYI: I can't reproduce this error with Radeon RX 480, amdgpu driver and Kernel 5.6.13.

```
[davidak@gaming:~]$ nix run nixpkgs.vulkan-tools -c vulkaninfo
==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.131


Instance Extensions: count = 18
====================
	VK_EXT_acquire_xlib_display            : extension revision 1
	VK_EXT_debug_report                    : extension revision 9
```

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.03.1879.91cdcf31357 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1879.91cdcf31357, nixos-hardware, nixos-unstable-20.09pre225931.32b8ed73809"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
