### ISSUE TITLE
Clean up or refactor all-packages.nix

### ISSUE THREAD

**Issue by C0DEHERO** [NixOS/nixpkgs#7866]
I just found out there were sections for different types of software in all-packages.nix, but nobody seems to know that either. Lots of packages are just all over. This really has to be either cleaned up, or the sections have to be split into multiple files. In my opinion splitting is the better option, but I'm not sure how to do it or if it is even possible/desirable. If cleaning is the only option then I can do that.

**Comment by spwhitt** [comment]
Relevant discussion from the mailing list: http://lists.science.uu.nl/pipermail/nix-dev/2015-May/017006.html

**Comment by copumpkin** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by edolstra** [comment]
I would just get rid of the sections, since they're pretty ad hoc anyway.

**Comment by C0DEHERO** [comment]
Yeah. I guess that getting rid of them would also work. If you want to search for packages by section you can just look through the folders anyways. I'll re-sort the declarations in all-packages and remove the sections once the lightdm issue is fixed.

**Comment by Fuuzetsu** [comment]
While the sections are pretty arbitrary, I think just sorting the whole thing is not a great approach either. Frequently we often want to keep the same family of packages together for discovery reasons: if we have a package and 5 plugins for it, it makes sense that they are physically close to each other. Same for any kind of wrapper, language + libs, whatever.

**Comment by benley** [comment]
one possible policy might be: "Alphabetic, except where that doesn't make sense. Use your judgement."

**Comment by Fuuzetsu** [comment]
That's pretty much just as arbitrary as what we have now.

**Comment by Profpatsch** [comment]
Flat is justice!

(triage) who cares, anyway? Maybe add a comment at the top to clarify the structure.

**Comment by jpierre03** [comment]
@C0DEHERO @Profpatsch @jagajaga  PR #17196 is merged.
Can this issue be closed ?

**Comment by Profpatsch** [comment]
Right, forgot about this issue. Thanks!
