### ISSUE TITLE
PulseAudio support in ALSA by default

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#7867]
I just realised that I don’t have sound in packages installed with Nix which are built without explicit PulseAudio support. The problem is that `alsaLib` that they use doesn’t know anything about my system ALSA config that tells it to use PulseAudio. Furthermore, even if it knew, it woudn’t be able to load the PulseAudio module, because it knows nothing about `alsaPlugins`.

I don’t see any easy way out of this situation (except for switching to NixOS, of course), so here is the proposal: ship PulseAudio support in `alsaLib` by default, including the plugin and configuration that uses PulseAudio when it is available. It won’t break anything, since if there is no PulseAudio, the extra config will just do nothing. If there are space constraints, this behaviour can be optional (e.g. enabled by default, disabled for minimal builds).

CC maintainers: @MarcWeber @lovek323 @wkennington

**Comment by bencef** [comment]
This is not PulseAudio specific but applies to all alsa plugins. see https://github.com/NixOS/nixpkgs/issues/6860

**Comment by Profpatsch** [comment]
(triage) maybe it’s already implemented?
