### ISSUE TITLE
More attributes for haskell-ng's interative environment

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#7874]
For my workflow, it would be nice if the `.env` environment worked more like the real package. In particular, I propose the following extra passthrough attributes for the shell environment:

* `base`: refers back to the "real" package. For example, `lens.env.base` would be equal to `lens`.
* `override`: behaves just like override on the original package. `lens.env.override f = (lens.override f).env`
* `overrideScope`: like `override`, overrides the scope of the original package and takes the env of the resulting package.

Any thoughts? @peti

**Comment by peti** [comment]
I'm not sure whether I see a use-case for those extensions. Can you give a brief example to illustrate a case where an attribute like `base` would be helpful?

**Comment by bennofs** [comment]
For one, with the `base` attribute, it is possible to build derivations generated by `cabal2nix --shell . > shell.nix`:
you can run `nix-build shell.nix -A base`. In my workflow, I have a `default.nix` that has the interactive environment, but I still need to import the package from other packages that depend on it. So for example, /data/libs/lens/default.nix would contain the interactive environment for the lens package. Then, in /data/libs/mylib/default.nix, I do something similar to this:

```
  { haskellngPackages ? (import <nixpkgs> {}).haskellngPackages }:
  mylib = callPackage ./mylib.nix {
    # my default.nix for lens also takes the haskellngPackages as an argument with a default value
    lens = (import ../lens { inherit haskellngPackages; }).base; 
  };
```

I noticed that for this use case, I could also have a `shell.nix` which imports the `default.nix` and calls `.env`. However, the use case of building cabal2nix --shell generated derivations remains.

**Comment by peti** [comment]
Does https://github.com/NixOS/cabal2nix/commit/a7998916868af0d09882468b3e43f5854082860f help alleviate this issue?

**Comment by bennofs** [comment]
@peti right, that should work. thanks!
