### ISSUE TITLE
Missing dependency for `calcurse` package: `oauth2client`

### ISSUE THREAD

**Issue by mfsch** [NixOS/nixpkgs#78751]
## Issue description

The `calcurse` package needs the Python 3 library `oauth2client` in order to set up synchronization with Google Calendar as described [here](https://github.com/lfos/calcurse/tree/master/contrib/caldav). I’ve been able to fix it on my system using `overrideAttrs` to add it to `postInstall`, but I’m not sure how the proper version would look to add to the package repository since I’ve just started with Nix. Maybe someone with more experience can add the fix?

### Steps to reproduce

- Install the `calcurse` package and run `calcurse-caldav` configured for OAuth2.
- Obtain `NameError: name 'OAuth2WebServerFlow' is not defined`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.14, NixOS, 19.09.1965.274e095f761 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(mfsch): `"nixpkgs-20.03pre210689.3fd22de7c23"`
 - channels(root): `"nixos-19.09.1965.274e095f761"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by patricksjackson** [comment]
This was fixed by #111747.
