### ISSUE TITLE
Package request: LBRY

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#78766]
**Project description**
Desktop client for the LBRY protocol. A YouTube alternative that uses the blockchain.

**Metadata**

* homepage URL: https://lbry.com/
* source URL: https://github.com/lbryio/lbry-desktop
* license: MIT
* platforms: Linux

**Comment by Soundtoxin** [comment]
Still not packaged.

**Comment by IslandUsurper** [comment]
Work has been started in #85769.

**Comment by ewok** [comment]
still actual

**Comment by srid** [comment]
PR https://github.com/NixOS/nixpkgs/pull/96368

**Comment by bqv** [comment]
PR closed, anyone else willing, reopen under a new PR and try your luck at the merge roulette

**Comment by enderger** [comment]
Small update, I'm currently working on packaging LBRY from source (it actually seems possible).

**Comment by enderger** [comment]
Ok, while not from source (that didn't work out) LBRY has been packaged.
