### ISSUE TITLE
Package request: Movim

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#78767]
**Project description**
A polished chat client for XMPP written in PHP and HTML5.

**Metadata**

* homepage URL: https://movim.eu/
* source URL: https://github.com/movim/movim
* license: AGPL-3.0
* platforms: Linux

**Comment by aanderse** [comment]
Looks reasonably straight forward for a primarily web based package. Just need a single `systemd` service to run a daemon, then configure a web server like `nginx` or `httpd` and configure it to proxy `.php` files over to a `phpfpm` pool.

After a quick glance through the source code it looks like the package itself would only need minimal tweaking to work. This would likely do it:
```
{ stdenv, fetchFromGitHub }:

stdenv.mkDerivation rec {
  pname = "movim";
  version = "0.16.1";

  src = fetchFromGitHub {
    owner = "movim";
    repo = "movim";
    rev = "v${version}";
    sha256 = "0w3x7xxnjbnd857znfy878r4lm08b8gmvwisyv5dpn03w782zcah";
  };

  prePatch = ''
    sed -i "s|define('CACHE_PATH'.*|define('CACHE_PATH', getenv('MOVIM_CACHE_PATH'));|" src/Movim/Bootstrap.php
    sed -i "s|define('PUBLIC_CACHE_PATH'.*|define('PUBLIC_CACHE_PATH', getenv('MOVIM_PUBLIC_CACHE_PATH'));|" src/Movim/Bootstrap.php
    sed -i "s|define('LOG_PATH'.*|define('LOG_PATH', getenv('MOVIM_LOG_PATH'));|" src/Movim/Bootstrap.php
    sed -i "s|DOCUMENT_ROOT.'/config/db.inc.php'|getenv('MOVIM_CONFIG')|" src/Movim/Bootstrap.php
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/movim
    cp -r * $out/share/movim

    runHook postInstall
  '';

  meta = with stdenv.lib; {
    description = "Decentralized social platform";
    license = licenses.agpl3;
    homepage = "https://www.movim.eu/";
    platforms = platforms.all;
    maintainers = [ maintainers.soundtoxin ];
  };
}
```
Notice the `sed` calls which introduce a few environment variables (`getenv('MOVIM_...`). You can pass the environment variables to your `php` environment to specify new paths, which reside outside the nix store, like `/var/cache/movim`, '/var/log/movim`, etc...

You could use [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/mediawiki.nix) as a guide. If you are interested in pursuing this, have any questions, or need any help feel free to ping me.

**Comment by Soundtoxin** [comment]
still not packaged

**Comment by aanderse** [comment]
@Soundtoxin right. Were you interested in chipping in?

**Comment by Soundtoxin** [comment]
> @Soundtoxin right. Were you interested in chipping in?

Not interested, sorry. I'm actually not running NixOS on anything right now, plus I've never written a package myself. I just noticed this piece of software wasn't packaged and wanted to make note of it, and my latest reply was to remove the stale marker. Not mission-critical for me then, but I think it should probably be packaged eventually. Perhaps it would've been fine to leave it stale.
