### ISSUE TITLE
Dwarf Fortress Package is vastly behind, update.sh just creates empty game.json file

### ISSUE THREAD

**Issue by TrevtheForthDev** [NixOS/nixpkgs#78791]
**Describe the bug**
Dwarf Fortress 0.47.01 was released today, and I was quite excited to play it
only to remember I'd likely have to package it. Ready to just throw a new hash in and be
done with it, I didn't realize I'd be spending my entire evening sitting there manually throwing hashes
in when an `update.sh` script was supposed to handle that all on it's own. I also realized that the last
version of Dwarf Fortress on NixOS was 0.44, is that not quite old by now?

**To Reproduce**
1. Clone Nix Repo
2. `nix-shell -p jq nix coreutils curl`
3. `sh update.sh`
3. `cat game.json`
**Expected behavior**
Functioning update script

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.13, NixOS, 19.09.1926.5d6da42cf79 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
for the script, it will try to parse to find the version but website format has changed, you can also pass a version, and that will work `update.sh 0.47.01`
