### ISSUE TITLE
singularity-tools.buildImage: FATAL: shell /bin/sh doesn't exist in container

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#78811]
**Describe the bug**
`singularity-tools.buildImage` does not appear to build valid singularity images. From https://github.com/NixOS/nixpkgs/issues/78743#issuecomment-579971706 it sounds like the container has `bash`, but it appears that singularity (now) requires `sh` instead

**To Reproduce**
1. create [default.nix](https://gist.github.com/jbedo/c32f6bb93470dc849e4d723c5cda7118):
```nix
{pkgs ? import <nixpkgs> {} }:
with pkgs;
singularity-tools.buildImage {
  name = "test";
  contents = [ hello ];
  runScript = "${hello}/bin/hello";
}
```
2. `nix-build`
3. As tested on NixOS (singularity 3.2.1):
```
> singularity run /nix/store/d57saxy6vhvnjjc4v6rqp9p7f6mwl6rp-singularity-image-test.img
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
FATAL:   exec /.singularity.d/actions/run failed: no such file or directory
> singularity shell /nix/store/d57saxy6vhvnjjc4v6rqp9p7f6mwl6rp-singularity-image-test.img
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
FATAL:   exec /.singularity.d/actions/shell failed: no such file or directory
```
4. As tested on [Sherlock](https://www.sherlock.stanford.edu/) (singularity 3.5.2-1.1.el7):
```
> singularity run ~/images/d57saxy6vhvnjjc4v6rqp9p7f6mwl6rp-singularity-image-test.img
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
FATAL:   shell /bin/sh doesn't exist in container
```

5. As tested on Ubuntu (singularity 2.5.2-dist)
```
> singularity run d57saxy6vhvnjjc4v6rqp9p7f6mwl6rp-singularity-image-test.img 
ERROR  : Unknown image format/type: d57saxy6vhvnjjc4v6rqp9p7f6mwl6rp-singularity-image-test.img
ABORT  : Retval = 255
```
I presume this failure on version <3 is expected.

Maintainer information:

@jbedo 
(appreciate the help!!)

**Comment by jbedo** [comment]
Thanks for finding this bug! I've patched it in my fork (bf25d312c43ca1483acc5baa6a5dfc0ac8cba28f), would you be able to test it?

**Comment by tbenst** [comment]
@jbedo that fix works! awesome. Built image on NixOS, tested image on NixOS and RHEL7 successfully

**Comment by jbedo** [comment]
Great, thanks for testing.
