### ISSUE TITLE
Catch Python modules build failures

### ISSUE THREAD

**Issue by ip1981** [NixOS/nixpkgs#7882]
We should catch Python modules build failures and fail the build, not allowing "renamed" modules like `_sqlite3_failed.so`:

```
*** WARNING: renaming "_sqlite3" since importing it failed: build/lib.linux-x86_64-2.7/_sqlite3.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
```

**Comment by ip1981** [comment]
a7028d3d07dade2305b7a94d39bec208d605617c

**Comment by ip1981** [comment]
Still makes sense.

**Comment by domenkozar** [comment]
We do catch them now.
