### ISSUE TITLE
nodePackages derivations not listed with nix-env --query

### ISSUE THREAD

**Issue by couchemar** [NixOS/nixpkgs#7888]
environment:
ubuntu + nix (nixpkgs-unstable)

later i'll check with NixOS unstable

**Comment by vcunat** [comment]
IIRC this was intentionally disabled due to nodePackages evaluation being expensive.

**Comment by couchemar** [comment]
Thank you for answer.
Is it a temporary decision?

**Comment by vcunat** [comment]
Well, IMHO it will be so until someone optimizes the problem away. Relevant discussion was in #3594.

**Comment by peti** [comment]
@couchemar, "`nix-env -qaP -A nodePackages`" should be a viable workaround for the time being.
