### ISSUE TITLE
gambit should use the gcc it was compiled with

### ISSUE THREAD

**Issue by fare** [NixOS/nixpkgs#78921]
## Issue description

When trying gerbil on macOS as installed with nix, it correctly invoked the gambit from nix that it was compiled with, but gambit itself invoked the gcc from the PATH, which was clang, with humorous results. Instead, gambit should somehow be made to use the gcc from nix that it was compiled in, at least by default.

### Steps to reproduce

The following steps will reproduce the bug in an obvious way on a mac where `gcc` by default is actually a link to `clang`. But the bug is latent on any installation where the `gcc` in the PATH is not fully compatible with the one used to compile gambit:
```
nix-env -iA nixpkgs.gerbil-unstable
gxpkg install github.com/fare/gerbil-utils
```

**Comment by fare** [comment]
Note: I'm creating an issue here, because this is the repository where the bug should be fixed, but I really am the sucker who ought to fix it and should be assigned the issue.

**Comment by fare** [comment]
Easier way to trigger this bug on my Linux box:
```
mkdir -p BUG
cd BUG
cat > foo.scm <<'EOF'
(display "hello world") (newline)
EOF
# Should work:
gsc foo.scm

cat > gcc <<'EOF'
#!/bin/sh
echo '@#%!*#@)(*^)@($^!#$@!$%@#$^'
exit 42
EOF
chmod a+x gcc
# should fail:
PATH=$PWD:$PATH gsc foo.scm
```

**Comment by eraserhd** [comment]
I'm coincidentally working on resolving some similar issues with this derivation - namely OpenSSL lib path is hard-coded to some random place, and not `${openssl}/lib`.  (I'm also working on getting it configured properly for Mac OS.)

@fare On MacOS, it should use clang.  Looking at your commit, it should be `export CC="$(command -v $CC)", I think.

**Comment by eraserhd** [comment]
The other issue I have that I'm not yet sure how to resolve is that binaries made with gsc, when installed, can't find libgambit.so.

**Comment by fare** [comment]
See #80224 for the latest version of my fixes:

1. I now removed the `(makeStaticLibraries openssl)` from `gambit/build.nix` in addition to commenting out more of the same in the gerbil build. Is that what your comment was referring to?

2. I also help Gerbil find its `GERBIL_HOME` where Nix puts it.

3. While Gambit can run with clang, it is much slower with it, because Gambit can take advantage of some GCC-only optimizations that clang doesn't have (IIUC; maybe clang has the equivalent, just not in a way that Gambit knows about, but I am not familiar with Gambit internals). Thus I'm using GCC even on macOS.

4. I'm not sure what the best way to use gsc with nix is, but I have two solutions that you may or may not like: use `nix-shell` with a recipe that depends on gambit, or use the `gerbil-nix-env.sh` script from https://github.com/fare/gerbil-utils
