### ISSUE TITLE
blivet: Merge nixpart -> blivet and pythonModules.blivet

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#78936]
Currently there is https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/nixpart/0.4/blivet.nix which is specific to nixpart and https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/blivet/default.nix which is ancient

The nixpart blivet package additionally includes an optional udev patch which is no longer in use due to https://github.com/NixOS/nixops/issues/1213 and should be removed

**Comment by danbst** [comment]
cc @aszlig

**Comment by aszlig** [comment]
@mkg20001: The issue here is that nixpart 0.4 monkey-patches blivet, so we can't easily jump to the latest blivet version. However updating the one included in `python-modules` is fine to update.

**Comment by Artturin** [comment]
nixpart has been removed from nixpkgs
