### ISSUE TITLE
Mounting the nix store on /nix/ fails but /nix works

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#78951]
**Describe the bug**

I have a separate  /nix/ ZFS dataset whose mountpoint I declare in my NixOS config.

However when I try to boot that system, it mounts the root dataset, tries to read something out of the nix store (before it's mounted) and fails, prompting me to reboot or ignore.

```Nix
  fileSystems."/nix" = {
    device = "Rpool/R/nix";
    fsType = "zfs";
  };
```

works but

```Nix
  fileSystems."/nix/" = {
    device = "Rpool/R/nix";
    fsType = "zfs";
  };
```
doesn't.

**To Reproduce**
1. Have a separate ZFS dataset for /nix/
2. Try to mount it on /nix and /nix/ respectively
3. Observe that /nix gets mounted before anything is read from the nix store while /nix/ isn't

**Expected behavior**

It should behave the same, no matter the trailing slash.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1970.6d9a4a615ee (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1970.6d9a4a615ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by danbst** [comment]
I think this is because of https://github.com/NixOS/systemd/commit/49e323d4d9c7ea5b405bf22aee5ab384d80e88f5

`/nix` is handled specially, in particular, it is not unmounted. But `/nix/` isn't matched, so it gets unmounted, which breaks everything (because everything lives in `/nix/store`).
