### ISSUE TITLE
singularity-tools.buildImage: No space left on device

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#78976]
**Describe the bug**
When trying to build non-trivial singularity images, I get ` cp: error writing /tmp/sbuild-360541823/fs/./nix/store/[...] : No space left on device` regardless of amount of space allocated to diskImage. Tested on computer with >200GB free space & >80GB available RAM.

Note that https://github.com/NixOS/nixpkgs/pull/78945 is needed for singularity to work

**To Reproduce**

`default.nix`:
```nix
{pkgs ? import <nixpkgs> {} }:

with pkgs;

singularity-tools.buildImage {
  name = "test";
  diskSize = 1024*25;
  contents = [ hello openjdk8 ];
  runScript = "${hello}/bin/hello";
}
```

This succeeds if openjdk8 is removed. Also fails if any other large derivation is used, not unique to openjdk8.

The dockerTools version succeeds however, so doesn't appear to be a VM issue:

`docker.nix`:
```nix
{pkgs ? import <nixpkgs> {} }:

with pkgs;

dockerTools.buildImage {
  name = "test";
  diskSize = 1024*25;
  contents = [ hello openjdk8 ];
  config = {
    Cmd = [ "${hello}/bin/hello" ];
  };
}
```

1. ...
2. ...
3. ...

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
@jbedo hope you're not getting sick of me! thanks for the great work and bugfixes :smiley:

**Comment by jbedo** [comment]
Fixed in my branch :). Sorry for the bugs, singularity changed considerably with the v3 rewrite.

**Comment by tbenst** [comment]
that's great, #78945 closes this issue, thanks!
