### ISSUE TITLE
'Permission denied' error when 'postBuild' script create file in '$out/share/bash-completion/completions/'

### ISSUE THREAD

**Issue by gomain** [NixOS/nixpkgs#78990]
**Describe the bug**
I use an overlay to define all my profile packages in one place. Some of my installed packages don't generate bash-completions upon install. So I add a `postBuild` attribute containing the required script.

All is fine when **none** of the installed packages generate any completions.

When one of the installed package (tmux) **dose** generate a  completion, i.e. generates a file in `$out/share/bash-completion/completions/`, scripts that attempt to create a file in that directory in `postBulid` fails with a 'Permission denied' error.

**To Reproduce**
This is my, simplified, overlay:
```
self: super:
{
  my-nix-env = with self; # self is nixpkgs
    buildEnv {
      name = "my-nix-env";
      paths = [
        #
        # other packages hidden
        #
        tmux # causes rclone completion installment below to fail
        rclone # rclone needs manual completion generation
      ];
      postBuild = ''
        echo "...mkdir -p $out/share/bash-completion/completions/..."
        mkdir -p $out/share/bash-completion/completions/
        echo "...install rclone completions..."
        $out/bin/rclone genautocomplete bash $out/share/bash-completion/completions/rclone
      '';
    };
}
```

**Expected behavior**
Manually created completion file is created and `nix-env -i ...` succeeds. Had 'tmux' been removed, the install would succeed as expected.

**Screenshots**
![nix-env-i-permmission-denied](https://user-images.githubusercontent.com/4217249/73587108-bd2af800-44e9-11ea-8226-7d9201ad5f81.jpg)

**Additional context**
Nixos running in VirtualBox, probably not relevant. 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1806.b047b7315d8 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(joe): `"nixpkgs-20.03pre211021.690dd986b23"`
 - channels(root): `"nixos-19.09.1806.b047b7315d8"`
 - channels(gomain): `"nixpkgs-20.03pre197053.d08a7431561"`
 - nixpkgs: `/home/joe/.nix-defexpr/channels/nixpkgs`
```

**Comment by gomain** [comment]
@veprbl Mind to answer?

**Comment by veprbl** [comment]
@gomain This has to do with how `buildEnv` works. If you add "ls -la $out" you will see that "$out/share" is a symlink to /nix/store/afd141s2x5qq3vi5l2v46wziycxpskzy-tmux-2.7 which is immutable.

**Comment by gomain** [comment]
> @gomain This has to do with how `buildEnv` works. If you add "ls -la $out" you will see that "$out/share" is a symlink to /nix/store/afd141s2x5qq3vi5l2v46wziycxpskzy-tmux-2.7 which is immutable.

Thanks for pointing this out. 'tmux' indeed created a symlink `$out/share/bash-completion` pointing to some `/nix/store/*-tmux-3.0a\share\bash-completion`. That explains why I can't create files there.

Would greatly appreciate if you could point me in the right direction here. I basically want to declare all my programs and env setup in a single place. Something I can take with me and rerun on multiple machines/users.

Anyway, thanks a lot.

**Comment by veprbl** [comment]
A solution I can think of is to move the bash completion generation into its own derivation. Something along the lines of:
```
runCommand "rclone-bash-completion" { buildInputs = [ rclone ]; } ''
  mkdir -p "$out"/share/bash-completion/completions/
  rclone genautocomplete bash "$out"/share/bash-completion/completions/rclone
''
```
Or it might be that this really ought to be done in the `rclone` itself, then you could contribute the completion generation functionality to nixpkgs for all users to use.

**Comment by veprbl** [comment]
Actually, this functionality is being added to `rclone` right now in #79062
