### ISSUE TITLE
services.btrfs.autoScrub: running scrub prevents system shutdown

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#79017]
**Describe the bug**

When the filesystem scrubbing service configured via `services.btrfs.autoScrub` is running, the system cannot shutdown until the scrubbing is completed.

**To Reproduce**
1. enable the autoscrub server on some Btrfs file system, e.g. by
  ```nix
  services.btrfs.autoScrub = {enable = true; fileSystems = [ "/" ];};
  ```
2. start the resulting service, e.g. `systemctl start btrfs-scrub-.service`
3. shutdown the system: `systemctl poweroff`
4. observe that the system only shuts down once the scrub has finished

**Expected behavior**

The scrub should be aborted properly when the system needs to shut down.

**Potential solution**

By default, running services are stopped by a SIGTERM, but apparently the btrfs scrubbing doesn't react to that.
We need to introduce a custom `ExecStop=btrfs scrub cancel <Mountpoint>` into the service definition.

This approach still needs to tested properly though. 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1970.6d9a4a615ee (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"home-manager-19.09, nixos-19.09.1970.6d9a4a615ee, nixos-unstable-20.03pre210639.e59dcf8ccec"`
 - channels(user): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- tasks/filesystems/btrfs.nix
```

**Comment by arianvp** [comment]
This will also need a `RemainAfterExit=true`

`btrfs scrub start` fires of a `kthread` iirc, and then exit immediately, so there is nothing to `systemctl stop`

So to get this to work we need:
```
ExecStart=btrfs scrub start -B $dev
RemainAfterExit=true
ExecStop=btrfs scrub cancel -B $dev
```

**Comment by symphorien** [comment]
Is `RemainAfterExit` really needed with `-B` ?
Also cancel does not accept `-B`.

**Comment by arianvp** [comment]
Oh my manpage-in-my-head read `-B` as block device .. not as blocking.... Scrub what I said! `ExecStop` should be enough here I think.

Also I think this is a great thing to add a NixOS VM test for

**Comment by schmittlauch** [comment]
@arianvp 
> Also I think this is a great thing to add a NixOS VM test for

While I'd love to have some tests for this, these may not be so easy: We need a filesystem large enough that the scrubbing doesn't immediately finish before the shutdown is initiated.

**Comment by symphorien** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/80141
