### ISSUE TITLE
auto upgrade doesn't work when there is more than one channel

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#79010]
With two channels (unstable and stable because I need some stable version of some packages) the nixos-rebuild --upgrade updates only first channel and wipes out the rest. Then nixos-rebuild switch complains when you reference from configuration.nix the non-default channel.

I made my own systemd unit and timer to run nix-channel --update && nixos-rebuild switch which seems to work correctly.

(edited: just fixed few typos)

**Comment by evanjs** [comment]
Hrm.  This all seems to be working fine with my configuration.  
FWIW, I put my [channels](https://github.com/evanjs/nixos_cfg/blob/463e6267d88ee3fff1b98517615a2e02a19fb914/config/new-modules/channels.nix) into `packageOverrides` and reference them via e.g. `pkgs.nixpkgs-unstable.gitkraken`.

Auto upgrade does seem to be working fine for me.

Ahhh wait, do you mean channels via `nix-channel`? In that case, I only have `nixos`.

**Comment by tex** [comment]
Yes, I meant via nix-channel. I have two channels there.

**Comment by tex** [comment]
Is it the way how channel(s) are supposed to be used? Have couple if them configured by nix-channel —add, let them update with nix-channel —update and reference them in configuration.nix with import <channel name>?

If yes then I would expect nix-rebuild —upgrade to update all present channels...

**Comment by evanjs** [comment]
> Is it the way how channel(s) are supposed to be used? To have couple of them configured by nix-channel —add, update them with nix-channel —update and reference them in configuration.nix with import ?
> 
> If yes then I would expect nix-rebuild —upgrade to update all present channels...

I think it's up to the user.  I used to have my machines configured this way, but got tired of having to manage both channels in `nix-channel` and `nixos-config`.

And yes, according to the [wiki](https://nixos.wiki/wiki/Nix_channels), one of the example commands is:
Updating all channels | `nix-channel --update`.

**Comment by tex** [comment]
Seems to work now. Closing.
