### ISSUE TITLE
TeXstudio crashes on open file dialog

### ISSUE THREAD

**Issue by smithtim** [NixOS/nixpkgs#79034]
## Issue description

TeXstudio 2.12.20 crashes whenever I try to access the open file dialog.  The terminal output is:

```
(texstudio:19954): GLib-GIO-ERROR **: 11:08:09.532: Settings schema
'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap
```

My desktop manager is MATE 1.22.1.

### Steps to reproduce

Open TeXstudio.  Click File -> Open.  TeXstudio crashes.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.44, NixOS, 19.09pre180443.4dd5c93998d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-20.03pre211190.a21c2fa3ea2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ajs124** [comment]
I can't reproduce this on 2.12.20 or 2.12.22, but I run KDE, so that might be a factor.

Do you experience similar problems with other QT apps?

**Comment by smithtim** [comment]
Not as far as I can tell.  I just tried SMPlayer and Media Player Classic Qute Theater, both of which seem to use QT, and was able to access the open file dialog in each.

**Comment by saulonio** [comment]
Hello,

I don't know if you'll still be getting updates on this issue but I found the same problem in TexStudio 3.0.1 running on Gnome in a different distro (Manjaro). 
What fixed it for me was to force TexStudio to not use the Gnome file dialog. I went to .config/texstudio/texstudio.ini and changed the line  
`Files\Use%20Native%20File%20Dialog=true` to  
`Files\Use%20Native%20File%20Dialog=false`. 
It is a bit unfortunate as I prefer Gnome's dialog over TexStudio's default one, but it did the trick. I haven't had this issue with any other Qt5 apps. I would bet this is a TexStudio bug and not a distro-specific one (but I honestly don't know).

**Comment by smithtim** [comment]
Thanks, I am now on MATE 1.24.0, and can no longer reproduce the issue.  I still have TeXstudio 2.12.20.

**Comment by rollf** [comment]
Here is a solution that worked for me:

https://discourse.nixos.org/t/firefox-crashes-when-opening-a-file-dialog/5323/13

**Comment by Artturin** [comment]
Works `env -i HOME="$HOME" DISPLAY="$DISPLAY" WAYLAND_DISPLAY="$WAYLAND_DISPLAY" XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" ./result/bin/texstudio`
