### ISSUE TITLE
Php not working with nginx

### ISSUE THREAD

**Issue by Th0rgal** [NixOS/nixpkgs#79081]
**Describe the bug**
I was trying to setup a nginx vhost using phpfpm, I followed the documentation and ended up with this: https://github.com/Th0rgal/vps-thor-nixos/blob/master/web.nix
I created an index.php file in order to test the php installation and I noticed two things:
When I connect to https://goblinmc.fr/, it doesn't find the index.php
When I connect to https://goblinmc.fr/index.php, it doesn find the index.php but show it to me as a text file (like if php wasn't running). But according to Wappalyzer, php is detected.

**To Reproduce**
1. Copy web.nix from https://github.com/Th0rgal/vps-thor-nixos/blob/master/web.nix
2. Create an index.php file with php info inside
3. Rebuild switch and connect to the server

**Expected behavior**
Php should work.

**Screenshots**
https://zupimages.net/up/20/05/63zl.png

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.16, NixOS, 19.09.1993.d3d2de8b99b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1993.d3d2de8b99b"`
 - channels(thomas): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pbogdan** [comment]
Perhaps I misread your configuration but I'm a bit surprised this works at all - as I understand it `fastcgi_pass` directive should not be allowed outside of a `location` block which AFAICT you don't specify anywhere. Could you perhaps post the full `nginx.conf` file the service definition generates?

**Comment by Th0rgal** [comment]
Here you go :)
[nginx-config.zip](https://github.com/NixOS/nixpkgs/files/4144981/nginx-config.zip)

**Comment by pbogdan** [comment]
The config doesn't even mention the `fastcgi` configuration for the `goblinmc.fr` vhost. I think the issue here is that your virtual host function will simply override whatever `extraConfig` you pass for a specific vhost. That's apart from the issue I mentioned earlier.

**Comment by Th0rgal** [comment]
Here is the final configuration, it is fixed but I need to nixos-rebuild switch two times in order to get any modifications to work: https://github.com/Th0rgal/vps-thor-nixos/blob/master/web.nix
