### ISSUE TITLE
NetworkManager VPN support isn't working

### ISSUE THREAD

**Issue by purefn** [NixOS/nixpkgs#7908]
It seems that since db3b86560f11437e260ae6d6661c69fb5bb36c75, network manager can no longer load the VPN modules properly. It was previously working with

```
  environment.systemPackages = with pkgs; [
    ...
    gnome3.networkmanagerapplet
    gnome3.networkmanager_openconnect
    gnome3.networkmanager_openvpn
    ...
  ];
```

in my `configuration.nix`. Now the VPNs I had configured previously don't show up in the VPN submenu and when I try and create a new VPN there are no options to select OpenConnect or OpenVPN.

**Comment by purefn** [comment]
It may or may not be relevant, but I am not using GNOME as my desktop environment. I am just using XMonad without any DE.

**Comment by lethalman** [comment]
Enabling networkmanager should be enough for VPN plugins to work. I've
tested with GNOME and they work. Perhaps I have to test better with the NM
applet.

On Wed, May 20, 2015 at 12:29 AM, Richard Wallace <notifications@github.com>
wrote:

> It may or may not be relevant, but I am not using GNOME as my desktop
> environment. I am just using XMonad without any DE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/7908#issuecomment-103684425>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by purefn** [comment]
My networking config is

```
  environment.systemPackages = with pkgs; [
    gnome3.networkmanagerapplet
    gnome3.networkmanager_openconnect
    gnome3.networkmanager_openvpn
  ];

  networking = {
    hostName = "tealc"; # Define your hostname.
    extraHosts = ''
      192.168.0.10 ronin
      192.168.0.4 tealc
      68.3.236.160 habitat
    '';
    networkmanager.enable = true;
  };
```

It was working fine before the update. Maybe try using networkmanager on a system without GNOME?

**Comment by lethalman** [comment]
I've tried NM with xfce already, but I don't remember if I tried the VPN
plugins. I will try tomorrow if I can.

On Wed, May 20, 2015 at 1:49 AM, Richard Wallace <notifications@github.com>
wrote:

> My networking config is
>
>   environment.systemPackages = with pkgs; [
>     gnome3.networkmanagerapplet
>     gnome3.networkmanager_openconnect
>     gnome3.networkmanager_openvpn
>   ];
>
>   networking = {
>     hostName = "tealc"; # Define your hostname.
>     extraHosts = ''
>       192.168.0.10 ronin
>       192.168.0.4 tealc
>       68.3.236.160 habitat
>     '';
>     networkmanager.enable = true;
>   };
>
> It was working fine before the update. Maybe try using networkmanager on a
> system without GNOME?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/7908#issuecomment-103699390>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by purefn** [comment]
Ok. For now I'm just using openconnect from the command line, which works good enough for me for now. Thanks.

**Comment by codyopel** [comment]
If you run the command `nmcli device` does it return an error about the version not matching?

**Comment by lethalman** [comment]
Should be fixed in master, please reopen if it's not.

**Comment by purefn** [comment]
Great, I'll give it a test as soon as I am able. Thanks!
