### ISSUE TITLE
DNS over TLS wiki setup not working

### ISSUE THREAD

**Issue by rht** [NixOS/nixpkgs#79102]
**Describe the bug**

I tried to setup DNS over TLS. I did exactly everything told in https://nixos.wiki/wiki/DNS_over_TLS.
But when I checked by going to `1.1.1.1/help`, I got a 'No' in the "DNS over TLS" section.

**To Reproduce**
Copy the configuration https://nixos.wiki/wiki/DNS_over_TLS verbatim except for the section "Manual Upstreams for Stubby."

**Expected behavior**
`1.1.1.1/help` should detect the DNS over TLS.

**Comment by rht** [comment]
Requesting a comment from @baroncharlus.

**Comment by rht** [comment]
And @vdot0x23.

**Comment by vdot0x23** [comment]
Hello, good on you for jumping on the DNS privacy train, try:
1. Validate with wireshark/tcpdump instead (I don't know how cloudflare validates).
2. Make sure your browser is using the system's DNS, some browsers come with preset DNS servers.

Btw, i don't think this issue belongs here, as it is related to the wiki and not nixpkgs :)

**Comment by rht** [comment]
@vdot0x23 thank you for the reply! I don't know of any other place to raise the issue, hence here.
I have another way to validate: I am currently in a region where reddit.com is blocked. I am able to visit reddit.com on Firefox by enabling DoH. My main browser is chromium, but unfortunately DoH is not supported on GNU/Linux yet, and hence my attempt at wiring up DoT at the system level. My additional test that the DoT is not working is that I still can't access reddit.com on chromium and when using nslookup.

**Comment by rht** [comment]
It works now!
What I did to make it work: I used cloudflare as my DNS server for Stubby
```
        # The Cloudflare server
          - address_data: 1.1.1.1
            tls_port: 853
            tls_auth_name: "cloudflare-dns.com"
````
@vdot0x23 I forgot to say that when I had the problem, I wasn't able to access any page, which possibly suggested that `unicast.censurfridns.dk` could be inaccessible in some region. Should the wiki be updated to include something along the line of "if you can't access any website, try using cloudflare instead"?

**Comment by vdot0x23** [comment]
Hm, nslookup _works on my machine_ ;). Does the output of your nslookup state that `127.0.0.1#53` is being used? If yes, maybe the default DNS servers are blocked in that region aswell. Alternatively, traffic could be blocked on port 853.

You can try to solve these problems by adding more DNS servers, that have other ports enables (examples are given on the wiki page), though that is the long way around. A packet capture would make identifying these issue much easier.

(I assume you have already considered that an SSH-, Shadowsocks-, or Tor proxy are overkill for that region, stay safe)

**Comment by rht** [comment]
Though one possible corner case: when port 853 is blocked, possibly in an airport wifi, there is no fallback resolver with the current wiki setup.
I think either:
1. dnsmasq-nm.conf needs to be amended to have external name server other than `127.0.0.1#5453`.
2. Set one of the upstream servers to use 443. This is suggested in the wiki, but not enforced. The default value of `services.stubby.upstreamServers` still uses 853 for everything.

**Comment by vdot0x23** [comment]
@rht , not enforced? How so?

I am under the impression that Stubby round robins by default.

**Comment by rht** [comment]
> I am under the impression that Stubby round robins by default.

That surely sounds like what Stubby would do. Apologies then for my assumption.
