### ISSUE TITLE
"No space left on device" running out of Inodes on server

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#79109]
**Describe the bug**
So I have several servers running on NixOS some use ext4 and some use zfs.
Note: I have `system.autoUpgrade.enable = true;` enabled on all of them.
On my ext4 servers I had a problem every set interval of 5-6 months where I had services failing silently or emails being undelivered. The machine would tell me that it had no space left on device, but inspecting it with `df -h` it told me that there was still more then enough space available. 
So I did a manual `nix-collect-garbage -d` an everything worked again.
So I just enabled `nix.gc.automatic` in hope that this would fix the problem but 5-6 months later I got it again. Turns out my inodes where depleted. A detailed explanation can be found here: https://www.ivankuznetsov.com/2010/02/no-space-left-on-device-running-out-of-inodes.html

**Expected behavior**
Because many people will run into this issue who do not use zfs, I suggest to document this problem in the manual and to make this the default `nix.gc.options = "--delete-older-than 60d";` in automatic garbage collection. 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.15-hardened, NixOS, 19.09.1993.d3d2de8b99b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1993.d3d2de8b99b, nixos-unstable-20.03pre208413.e1eedf29e5d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by sorki** [comment]
Happened to me as well recently and the error message `No space left on device` is not very helpful. Not much we can do about that I guess.

Documenting this is a good idea (not sure which section of the manual) but `nix.gc.options = "--delete-older-than 60d";` not so.

**Comment by Luis-Hebendanz** [comment]
Could you elaborate why not? Because out my perspective if someone enables automatic garbage collection the reason is because he/she wants to clear the floating packages automatically. If auto gc does not do that then I do find that misleading (and if I do others will probably too). I mean you could also set it to 90d default. 3 months of old packages should be more then enough, right?

**Comment by sorki** [comment]
Because it depends on individual usage patterns - for example I've recently updated my armv7 Novena which was running 18.03 and I wouldn't want it to gc older generations automatically (they were 2y old).

But I didn't quite realize it would be only used when `nix.gc.automatic` is enabled so it might be a reasonable default after all, maybe file a PR?

**Comment by danbst** [comment]
this isn't NixOS specific issue. Ubuntu with unattended upgrades generates lots of extra kernel headers, which may deplete inodes. The solution is same: cleanup kernel headers after each upgrade.

So, if it's gonna to be documented, it should have reference from option `system.autoUpgrade.enable`.
