### ISSUE TITLE
SmartOS support?

### ISSUE THREAD

**Issue by complyue** [NixOS/nixpkgs#79101]
Hello, I'd like to know the status for SmartOS being or to be a supported platform?

I'm building GHC 8 (wip though), it's native package manager - pkgsrc only have 7.6.3 up to date, while its upstream BSD repository already has ghc-8.8, no one is working on the migration yet.

I have some experience to build custom ghc 8.6 with nixpkgs on linux and mac, and tend to use nixpkgs to finally automate the build (bootstrap via 7.6->7.10->8.2->8.4/8.6->8.8 version path seems necessary) of ghc 8.6 or 8.8.

But obviously nix installation to SmartOS is not straightforward atm (or I missed something?), so I'd like to ask about the feasibility with this issue.

**Comment by complyue** [comment]
btw, I see https://nixos.org/nix-dev/2016-February/019415.html any continued effort since then on?

**Comment by abathur** [comment]
Is this still an issue? I'm not sure if it's in the right repo.

If the scope is just building/installing the Nix package manager itself, the ideal venue is https://github.com/nixos/nix

If you are indeed asking about support _in nixpkgs_, https://github.com/NixOS/rfcs/blob/master/rfcs/0046-platform-support-tiers.md outlines where existing platforms stand and roughly what it takes to raise the support level.

**Comment by abathur** [comment]
Taking this as a "no" but happy to reopen if anyone objects.
