### ISSUE TITLE
Package `stylish-haskell` is marked as broken, refusing to evaluate

### ISSUE THREAD

**Issue by rpearce** [NixOS/nixpkgs#79130]
**Describe the bug**
Trying to install `stylish-haskell` fails.

https://github.com/NixOS/nixpkgs/blob/bf4169178ec8c9d8c9947ae4ee7f018093a6e77f/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L1022

**To Reproduce**
1. `$ nix-env -i stylish-haskell`
1. watch it fail

**Expected behavior**
It should install `stylish-haskell`

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/592876/73616374-5f420180-460a-11ea-8a44-1547f09e9744.png">

**Additional context**
`stylish-haskell` has a dependency on `>=0.2.0 && <0.3`, but it looks like `HsYAML` is set to `0.1.2.0` in [`configuration-hackage2nix.yaml`](https://github.com/NixOS/nixpkgs/blob/bf4169178ec8c9d8c9947ae4ee7f018093a6e77f/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L1022)

**Metadata**
```
λ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (1.46 MiB download, 7.88 MiB unpacked):
  /nix/store/3lvcb4hxzax99zvb33ryk4whcv7zpjq2-bash-interactive-4.4-p23-info
  /nix/store/czg8zzd1qib1yafggnf5jsd14cmcfsdv-bash-interactive-4.4-p23-doc
  /nix/store/gr67mfj18zmyb0w7510ihi1qbivnjbaa-bash-interactive-4.4-p23-man
  /nix/store/kk512ydg1i1r0h5m9fizdrl9qxlrazrf-bash-interactive-4.4-p23-dev
  /nix/store/l5zsd7mphr5gp8p5y46ba6ahwlna1gnb-DarwinTools-1
  /nix/store/lq6lcv42lf7cp35lgxmxgs6qikqhvgg9-nix-info
  /nix/store/x3vwmx1y5l9ssy07i67395g1xzba1cyk-readline-7.0p5
  /nix/store/y27b4rnmiwzvpznb2hbqmvdzzk4a5472-bash-interactive-4.4-p23
copying path '/nix/store/czg8zzd1qib1yafggnf5jsd14cmcfsdv-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/l5zsd7mphr5gp8p5y46ba6ahwlna1gnb-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/3lvcb4hxzax99zvb33ryk4whcv7zpjq2-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/gr67mfj18zmyb0w7510ihi1qbivnjbaa-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/lq6lcv42lf7cp35lgxmxgs6qikqhvgg9-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/x3vwmx1y5l9ssy07i67395g1xzba1cyk-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/y27b4rnmiwzvpznb2hbqmvdzzk4a5472-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/kk512ydg1i1r0h5m9fizdrl9qxlrazrf-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.3.0, macOS 10.15.3`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(rpearce): `"home-manager, nixpkgs-20.03pre211437.e3a9318b6fd"`
 - nixpkgs: `/Users/rpearce/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - stylish-haskell
# a list of nixos modules affected by the problem
module:
```

**Comment by cdepillabout** [comment]
Feel free to send a PR overriding the dependencies of `stylish-haskell` in `configuration-common.nix`.

Alternatively, getting `stylish-haskell` into Stackage would also help out here.

**Comment by rpearce** [comment]
@cdepillabout Thank you for the :eyes:! I'll see about both of these

**Comment by cdepillabout** [comment]
Also, I've written a couple places about how Haskell packages are updated in nixpkgs.

Maybe this thread will help you:

https://discourse.nixos.org/t/haskellpackages-stm-containers-fails-to-build/5416/4

**Comment by rpearce** [comment]
While the fix isn't available to me yet on the unstable channel, that fix looks good, so I'll close this to get it out of your hair!
