### ISSUE TITLE
Drop ruby 2.4 for 20.03

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#79143]
## Issue description
Ruby version 2.4 is going to reach EOL on March 31, 2020
https://www.ruby-lang.org/en/downloads/branches/

**Comment by worldofpeace** [comment]
cc @manveru @alyssais

**Comment by manveru** [comment]
I'll take this one.

**Comment by manveru** [comment]
Here's a list to keep track of issues that need to be resolved:

- [ ] sonic-pi upstream hasn't been upgraded to a newer Ruby yet, although there seems to be some work in progress at https://github.com/samaaron/sonic-pi/issues/2179 -- So we might have to package a fork/branch if we want this in before the cutoff date. Pinging the maintainers @Phlogistique @kamilchm.
- [ ] chef also depends on 2.4, and is an ancient version. I tried updating it, but ran into issues with omnibus trying to take over `/nix/store`. I can't spend a lot of time on it, so pinging @offlinehacker and @nicknovitski. If nobody wants to take care of the package I'll prepare its deprecation.

**Comment by worldofpeace** [comment]
Oooh @manveru !! There's this #76600

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/commit/f8f607b824841943c53ed44fb7753c9e6814fbc9
