### ISSUE TITLE
Pin nodejs to 12.x for 20.03

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#79144]
## Issue description
Node.js 12.x is the current "Active LTS" https://medium.com/@nodejs/node-js-12-to-lts-and-node-js-13-is-here-e28d6a4a2bd

**Comment by disassembler** [comment]
Is anyone planning on doing this before release cut-off tomorrow?

**Comment by worldofpeace** [comment]
Reading the blog post it said
> Node.js 12 becomes the newest LTS release along with 10 and 8. Please note that 8 goes end-of-life in December (an exception to the regular LTS cycle due to the EOL of OpenSSL 1.02 so you should already be planning your migration off it to either 10 or 12.) 

I'm not sure we have to do anything here, and branchoff is today.
I'm going to close this.

**Comment by worldofpeace** [comment]
cc @adisbladis ?
