### ISSUE TITLE
postfix

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#7915]
# adding spamassassin to the postfix pipeline
in the postfix nix expression we have this hardcoded masterCf (see below).

in order to add a spamassassin pipeline one has to alter the nix expression, i would like to suggest that we make the masterCf a default value for a mkOption which can be changed from configuration.nix

what do you think?

<pre>
masterCf = ''
    # ==========================================================================
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (yes)   (never) (100)
    # ==========================================================================
    smtp      inet  n       -       n       -       -       smtpd
    #submission inet n       -       n       -       -       smtpd
    #  -o smtpd_tls_security_level=encrypt
    #  -o smtpd_sasl_auth_enable=yes
    #  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
    #  -o milter_macro_daemon_name=ORIGINATING
...
</pre>

https://github.com/NixOS/nixpkgs/blob/release-14.12/nixos/modules/services/mail/postfix.nix

**Comment by peti** [comment]
`services.postfix.extraConfig` and `services.postfix.extraMasterConf` don't suffice?

**Comment by qknight** [comment]
# the problem is this:

the manuals always mention to use: 
<pre>
smtp      inet  n       -       -       -       -       smtpd -o content_filter=spamfilter
</pre>
along with:
<pre>
spamfilter
          unix  -       n       n       -       -       pipe
   flags=Rq user=spamd argv=/usr/bin/spamfilter.sh -oi -f ${sender} ${recipient}
</pre>

**note:** this means that one has to alter main.cf as appending would not overwrite the configuration (i tried that already).

see:
https://wiki.apache.org/spamassassin/IntegratedSpamdInPostfix

# solution
do you have a better idea how to do that? i wonder, don't you use spamassassin?

**Comment by peti** [comment]
I see ... yes, fixing that issue needs a modification of the existing config rather than appending to it. You are right.

Personally, I use spamassasin via procmail:

    environment.etc = [
      {
        target = "procmailrc";
        source = pkgs.writeText "procmailrc" ''
          # generated global procmail configuration -- do not edit

          DEFAULT="/var/spool/mail/$LOGNAME"
          DROPPRIVS="yes"

          :0fw
          * < 512000
          | ${pkgs.spamassassin}/bin/spamc
        '';
      }
    ];

    services.postfix.extraConfig = ''
      mailbox_command = ${pkgs.procmail}/bin/procmail
    '';

**Comment by qknight** [comment]
so what do you think about my proposed solution?

**Comment by peti** [comment]
I think it sounds fine.

**Comment by peti** [comment]
@qknight, will you implement this patch?

**Comment by peti** [comment]
Pull requests to implement the described feature would be welcome.
