### ISSUE TITLE
texlive fails to build after poppler update

### ISSUE THREAD

**Issue by eraserhd** [NixOS/nixpkgs#79170]
**Describe the bug**

texlive on master fails to build since d1dfbfd8d97c5a36cfcdf2bc26f883437ac3a4e8 :

```
...
gcc -DHAVE_CONFIG_H -I. -I../../../texk/web2c -I./w2c   -I/build/texlive-20190410-source/WorkDir/texk -I/build/texlive-20190410-source/texk  -I/nix/store/zwlzd0c6adm3v2az2dr13r3i4zjq2vwb-zlib-1.2.11-dev/include -I/nix/store/2bjjwhbc7fidvcdrnxz77szfksr7wzgv-libpng-apng-1.6.37-dev/include/libpng16 -DPOPPLER_VERSION=\"0.84.0\" -I/nix/store/ylnp5xgas7zbb0kyxvh1nbm5h35bcww0-poppler-min-0.84.0-dev/include/poppler -I../../../texk/web2c/libmd5 -I../../../texk/web2c/pdftexdir  -Wimplicit -Wreturn-type -g -O2 -c -o pdftexdir/libpdftex_a-writefont.o `test -f 'pdftexdir/writefont.c' || echo '../../../texk/web2c/'`pdftexdir/writefont.c
In file included from ../../../texk/web2c/pdftexdir/utils.c:36:
/nix/store/ylnp5xgas7zbb0kyxvh1nbm5h35bcww0-poppler-min-0.84.0-dev/include/poppler/poppler-config.h:142:10: fatal error: cstdio: No such file or directory
  142 | #include <cstdio> // __MINGW_PRINTF_FORMAT is defined in the mingw stdio.h
      |          ^~~~~~~~
compilation terminated.
make[5]: *** [Makefile:13489: pdftexdir/libpdftex_a-utils.o] Error 1
...
```

This commit upgraded the poppler library, and upstream they "modernized the headers", including `<cstdio>` instead of `<stdio.h>` in the `poppler-config.h`.  texlive includes this file in a plain C program, so `<cstdio>` is not available.

**To Reproduce**

```
nix-build . -A texlive.combined.scheme-basic
```

**Expected behavior**

Should build.

**Additional context**

Gentoo had this issue too: https://bugs.gentoo.org/704166

I'm not familiar enough with gentoo to understand what the fix is doing, but it looks like they fixed it by moving to an r6 version of texlive?

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.95, NixOS, 20.03.git.08fa4c6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(jfelice): `"nixpkgs-19.09pre178484.8bc70c937b3"`
 - nixpkgs: `/home/jfelice/src/dotfiles/nixpkgs`
```

Maintainer information:
```yaml
attribute:
- texlive
- texlive.combined.scheme-basic
- texlive.combined.scheme-tetex
```

cc @ttuegel @ryantm

**Comment by vcunat** [comment]
> but it looks like they fixed it by moving to an r6 version of texlive?

No, that's versioning of gentoo-specific tarball with patches, currently http://distfiles.gentoo.org/distfiles/texlive-core-patches-2019-7.tar.xz and their workaround is in texlive-core-2019-poppler084.patch inside.

**Comment by vcunat** [comment]
The patch was applied in fc7e4c926.  I believe poppler should be blamed instead, but it should work now at least.
