### ISSUE TITLE
Helm synthesizer does NOT allow saving or loading

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/nixpkgs#79177]
**Describe the bug**
Using the Helm Synthesizer, the saving and loading of patches does not work. 

**To Reproduce**
1. `nix-env -iA nixos.helm` (in my case `nix-env -if "<nix-master>" -A helm` to get the version in master)
2. `helm`
3. Attempt to save a patch

**Expected behavior**
Saving patches works, as well as loading patches as per the helm documentation. [page 26](https://tytel.org/static/docs/helm_manual.pdf)

**Screenshots**
- Clicking save has no effect
- Clicking the `+` button under "bank" clears the input
- Clicking the `+` button under "folder" has no effect
![2020-02-03-124146_1198x533_scrot](https://user-images.githubusercontent.com/609279/73684859-42e1ab80-4682-11ea-955b-1df972fb5737.png)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1957.57c35c63004 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"musnix, nixos-19.09.1957.57c35c63004"`
 - channels(isaac): `"nixos-18.03-18.03.133402.cb0e20d6db9, nixos-19.03-19.03.173684.c8db7a8a16e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pennae** [comment]
problem still exists
