### ISSUE TITLE
NixOS 20.03 highlights

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#79180]
**Describe the goal**
Let's fill up the highlights section in the [release notes](https://github.com/NixOS/nixpkgs/blob/8ecbde9defe35df4169b5f5eebed999488b0182a/nixos/doc/manual/release-notes/rl-2003.xml#L13).

**Here's how you can help**
* Mention the highlight in this thread
* PR to the highlights section
* If docbook is inconvenient just comment it here, I can translate it

**Contributing to the manual**
Building the manual:
```
nix-build nixos/release.nix -A manualHTML.x86_64-linux
```
Open `./result/share/doc/nixos/release-notes.html`

https://nixos.org/nixos/manual/index.html#sec-writing-documentation

**Closing**

So much can happen to NixOS in 6 months, let's highlight what we feel is important.

:fire:  worldofpeace

**Comment by worldofpeace** [comment]
Guess this counts in helping me out a bit https://discourse.nixos.org/t/january-2020-in-nixos/5771 :wink:

**Comment by worldofpeace** [comment]
In detail we need to talk about https://github.com/NixOS/nixpkgs/issues/72828

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/79335

**Comment by jonringer** [comment]
proper azure-cli support #71797 (this was backported to 19.09 #74014)

**Comment by jonringer** [comment]
better dotnet development experience:  #73262

**Comment by rnhmjoj** [comment]
I'm not sure if worthy of mentioning but here's some stuff I care about:

- New module for dnscrypt-proxy: #78543
- New option to make dhcpcd not take forever to start: #78745
- Better rxvt-unicode plugins support: #77347
- Console colors working properly: #71473
- services.xserver.extraLayouts working in Gnome 3: #76591
- linux_latest 5.5, linux 5.4, mesa 19.3.3, wine 5.0!
- linux-libre appears to be working now

**Comment by vcunat** [comment]
I think `linux_latest` moves even on stable branches (though apparently not as often).

**Comment by worldofpeace** [comment]
Need to add GNOME 3.34 stuff and Pantheon 5.1.
This was really nice to have their redesigned greeter working completely in NixOS https://github.com/NixOS/nixpkgs/pull/68729.

**Comment by mkg20001** [comment]
cinnamon being wip, maybe?

**Comment by aanderse** [comment]
I should probably write something about the `httpd` changes, but I'm not sure I'm going to get around to it...

**Comment by mweinelt** [comment]
Some networkmanager bump during this cycle enabled WPA3-PSK (SAE) support.

**Comment by prusnak** [comment]
https://github.com/NixOS/nixpkgs/pull/80196 OpenSSH 8.2p1 with FIDO support allowing usage of private keys backed by hardware tokens

**Comment by vcunat** [comment]
Well, backport of that was proposed but not done yet (and seems not really decided to me).

**Comment by prusnak** [comment]
@vcunat as discussed in #80196: the backport to 20.03 will be done in https://github.com/NixOS/nixpkgs/pull/81368

**Comment by tokudan** [comment]
> Linux kernel is updated to branch 5.4 by default (from 4.19). Users of Intel GPUs may prefer to explicitly set branch to 4.19 to avoid some regressions.

What are these regressions? If there are known issues it would be useful to have links or a short explanation if that is about e.g. power saving or crashes.

**Comment by vcunat** [comment]
@tokudan: they were discussed on the PR https://github.com/NixOS/nixpkgs/pull/78713

**Comment by tokudan** [comment]
@vcunat I'd suggest to add something like this to the release notes:
> Linux kernel is updated to branch 5.4 by default (from 4.19). Users of Intel GPUs may prefer to explicitly set branch to 4.19 to avoid regressions for some hardware variants, including random freezes and power management issues. See https://github.com/NixOS/nixpkgs/pull/78713 for more details.

**Comment by worldofpeace** [comment]
@tokudan I believe @grahamc and I thought to add a tracking issue for all the regressions that had a nice spread of references.

**Comment by tokudan** [comment]
@worldofpeace I like that, but at least a rough information about the type of issues should be in the release notes, I believe, so users don't have to dig up the tracking issue, then follow that to the real issue and read through possible 50+ comments just to figure out how bad these issues are.

**Comment by worldofpeace** [comment]
> @worldofpeace I like that, but at least a rough information about the type of issues should be in the release notes, I believe, so users don't have to dig up the tracking issue, then follow that to the real issue and read through possible 50+ comments just to figure out how bad these issues are.

I agree with 

> Linux kernel is updated to branch 5.4 by default (from 4.19). Users of Intel GPUs may prefer to explicitly set branch to 4.19 to avoid regressions for some hardware variants, including random freezes and power management issues. See #78713 for more details.

completely, but let's not make it #78713, but instead a highly informational issue that also tracks the problems getting fixed.

**Comment by tokudan** [comment]
I'd suggest adding a notice regarding the Nextcloud-upgrade path (https://github.com/NixOS/nixpkgs/issues/82056), which requires a two-step upgrade process (first to nextcloud 17, then to the current nextcloud 18).

**Comment by Ma27** [comment]
The Nextcloud issue is fixed in #82353 (not merged yet).
Btw would be cool to get some feedback on my Hydra bump in case we want to have it in 20.03: #82176

**Comment by Ma27** [comment]
For the record, #82353 is merged and backported, so the upgrade-path for Nextcloud is fixed now :)

**Comment by davidak** [comment]
not a blocker

I have done a review of the release notes. It would be nice if someone could improve this 3 small annoyances before the release announcement. https://github.com/NixOS/nixpkgs/issues/82777
