### ISSUE TITLE
Harden our SSH configuration against Logjam attack

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7920]
https://stribika.github.io/2015/01/04/secure-secure-shell.html provides some useful suggestions how to defend against weakness in the Deploying Diffie-Hellman key exchange, i.e. removing entries from `/etc/ssh/moduli ` that are too small. We should implement those recommends ASAP.

Also, our version of Firefox appears to be vulnerable: visit https://weakdh.org/ to check.

**Comment by edolstra** [comment]
See https://github.com/NixOS/nixpkgs/pull/5870 and https://github.com/NixOS/nixpkgs/issues/5809 for previous discussion.
