### ISSUE TITLE
`haskellPackages.http-streams` is marked as broken although it builds

### ISSUE THREAD

**Issue by drever** [NixOS/nixpkgs#79227]
Running 

```
nix-build --no-out-link -A haskellPackages.http-streams 
```
Results in 

```
Package ‘http-streams-0.8.7.1’ in ~/workspace/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:132580 is marked as broken, refusing to evaluate.
```

Following [this](https://www.youtube.com/watch?v=KLhkAEk8I20) video I ran

```
nix-build --no-out-link -A haskellPackages.http-streams --arg config '{ allowBroken = true; }'
```
and it compiles properly. Why is the package marked as broken?

**Comment by cdepillabout** [comment]
@drever please feel free to send a PR marking this as no longer broken (as described in the video).

**Comment by drever** [comment]
The package builds again, @clkamp fixed it.
