### ISSUE TITLE
systemd-homed

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#79263]
systemd-homed has been merged, we should consider how best to implement this in NixOS and create the modules required to support it.

Documentation: https://systemd.io/HOME_DIRECTORY/
Git: https://github.com/systemd/systemd/tree/master/src/home
Phoronix: https://www.phoronix.com/scan.php?page=news_item&px=Systemd-Homed-Merged
Talk: https://www.youtube.com/watch?v=ZwjzfdLJtX4

**Comment by weilbith** [comment]
Mark as not stale

**Comment by florianjacob** [comment]
still important. related: #91243

**Comment by Atemu** [comment]
Still important to me.

**Comment by abathur** [comment]
Seems to have been satisfied by https://github.com/NixOS/nixpkgs/pull/205121
