### ISSUE TITLE
Various basic PHP packages (needed for azuriom)

### ISSUE THREAD

**Issue by Th0rgal** [NixOS/nixpkgs#79270]
**Project description**
I am trying to install this CMS: https://azuriom.com/docs/installation on my nixos vps, I installed php but I also need a few php extension packages that I'm not able to find:

BCMath PHP Extension
Ctype PHP Extension
JSON PHP Extension
Mbstring PHP Extension
OpenSSL PHP Extension
PDO PHP Extension
Tokenizer PHP Extension
XML PHP Extension
cURL PHP Extension
GD2 PHP Extension
Zip PHP Extension

**Metadata**

* homepage URL:  https://azuriom.com/
* source URL: https://github.com/Azuriom
* license: GPL 3.0

**Comment by aanderse** [comment]
Please include error message and some details of how to reproduce.

**Comment by abathur** [comment]
Most of the extensions mentioned here were added soon after this was opened in #82348.

I'm not certain about "gd2" (I see gd). JSON has also been since removed. (but IIRC that's because support is now built in?)
