### ISSUE TITLE
Packaging Request: Casebox

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#79284]
**Project description**
"It started as a project to provide a sophisticated case management solution to one NGO, and was subsequently expanded to become a flexible case management system for human rights organisations."
https://casebox.org/about/
![image](https://user-images.githubusercontent.com/47436522/73859587-90087d80-483a-11ea-8886-88eff30865ed.png)

**Metadata**

* homepage URL: https://www.casebox.org (?)
* demo URL: https://github.com/huridocs/casebox (broken?)
* source URL: https://github.com/huridocs/casebox (?)
* documentation URL: 
  * dev: https://www.casebox.org/dev/docs/ 
  * user(?): https://github.com/huridocs/casebox/wiki
  * user(?): https://www.casebox.org/userguide/
* license: ?
* platforms: ?

The repository (maintained by one of the organizations in the above mentioned about page) doesn't have the github issue tracker enabled and hasn't been touched (?) in 4 months, which isn't particularly encouraging.

The wiki says " As of 2018, HURIDOCS is no longer providing active development for new features for this version of Casebox." (but it looks like they still merge PRs?)

The upstream fork hasn't been touched in a long time and is abandoned per https://github.com/KETSE/casebox/issues/84#issuecomment-473272973 in favor of https://github.com/huridocs/uwazi . (but they are open to new maintainers.)

I accidentally found two penetration test reports from 2014 at
* https://cure53.de/pentest-report_casebox-1.pdf
* https://cure53.de/pentest-report_casebox-2.pdf
(additionally https://www.casebox.org/security/ )
followup: https://github.com/KETSE/casebox/issues/90

I'm evaluating options for a document repository for sharing lecture notes and such, see also #79285, so I intend to at least  try packaging this if the coming days allow.

**Comment by AndersonTorres** [comment]
Dead project
