### ISSUE TITLE
Remove Python 3.5 for 20.09

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#79322]
**Describe the bug**
There are no more planned releases for 3.5. We could remove it from 20.03, but it is still quite a popular Python version and technically not yet EOL. Let's remove it for 20.09. It's EOL in September 2020 according to https://devguide.python.org/#status-of-python-branches

cc @jonringer

**Comment by jonringer** [comment]
Sounds good to me, I don't think it will be nearly as divisive as 2.7 was.

**Comment by schmittlauch** [comment]
closed by #95305, am I right?

**Comment by jonringer** [comment]
yea, forgot to clean this up. Thanks @schmittlauch
