### ISSUE TITLE
libuv: fails to build on darwin

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#79331]
**Describe the bug**
```
nix-build -A libuv --check
checking outputs of '/nix/store/8fz2zmwl25spi9div0ja568hhzxg50fv-libuv-1.34.1.drv'...
unpacking sources
unpacking source archive /nix/store/rwamwvxn82p0ych5vgkvg9gi3vsy75ql-source
...
make  check-TESTS
...
not ok 294 - udp_send_unix
# exit code 6
# Output from process `udp_send_unix`:
# Assertion failed in test/test-udp-open.c on line 325: 0 == bind(fd, (const struct sockaddr*)&addr, sizeof addr)
...
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5316: check-TESTS] Error 1
```

This happens both on nixpkgs `master` as on `release-19.09`. 

This happens with and without `--sandbox`.

Note that during the tests I get the following popup:

<img width="532" alt="Screenshot 2020-02-06 at 13 22 19" src="https://user-images.githubusercontent.com/576355/73936730-c0582680-48e3-11ea-8446-9fdf638dbd93.png">

~Both "Deny" and "Allow" result in the same error.~ EDIT: I observed something differently [later on](https://github.com/libuv/libuv/issues/2675#issuecomment-582935490).

It looks like a flaky test because it seems to have been build fine on Hydra:
https://hydra.nixos.org/job/nixpkgs/trunk/libuv.x86_64-darwin/latest

**Metadata**
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
 - channels(bas): `"nixpkgs-19.09pre191265.c4adeddb5f8"`
 - nixpkgs: `/Users/bas/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libuv
```

CC maintainer: @cstrahan

**Comment by basvandijk** [comment]
The latest `libuv-1.34.2` exhibits the same issue.

**Comment by basvandijk** [comment]
`libuv` `master` also fails.

**Comment by basvandijk** [comment]
Fixed by: https://github.com/NixOS/nixpkgs/pull/79381 (`staging`) and https://github.com/NixOS/nixpkgs/pull/79383 (`staging-19.09`).

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/commit/97eda56797472f9a15e919e40ed14000c2878f78
