### ISSUE TITLE
yq-go v3

### ISSUE THREAD

**Issue by KyleOndy** [NixOS/nixpkgs#79353]
**Project description**
yq is a portable command-line YAML processor

**Metadata**

* homepage URL:  https://mikefarah.gitbook.io/yq/
* source URL: https://github.com/mikefarah/yq
* license: mit
* platforms: all? (golang)

`yq-go` version `2.4.0` is [currently packaged](https://github.com/NixOS/nixpkgs/blob/65f7fa4f6e9f7cbf8536f54dad217580a543b823/pkgs/development/tools/yq-go/default.nix). It would be nice to get the version bumped to v3. This is a breaking change so I do not know what the best way to handle it is.

Within the next few days I can try and submit an MR to update the version.

**Comment by veprbl** [comment]
cc @nlewo

**Comment by nlewo** [comment]
@KyleOndy Cool! Ping me in your PR, I could review it ;)

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/pull/79412/
