### ISSUE TITLE
Proposed plan to package the dotNET ecosystem in Nix [Discussion]

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#7938]
Hi all,

Would like to propose a plan for packaging the dotNET ecosystem in Nix.

Motivation:

Microsoft has opensourced the dotNET VM, as well as compilers and libraries. Until those things are packaged, Mono is a pretty decent runtime. F#, is an amazing language, its compiler is opensource and already packaged for Nix and it has good integration with open editors (vim/emacs/atom). In summary, it's a solid dev environment than even non-Windows users ought to consider.

Proposed Plan:

I propose that we create a pkgs/development/dotnet-modules directory which would contain dotNET libraries.
The output of these derivations should be a single file in the store in the nupkg format.
The nupkg (Nuget package) format is essentially is a zip file containing some metadata and the compiled library DLLs.
Some of the derivations would simply download packages from Nuget.org or Myget.org and the nix files would contain package name, version number, server (Nuget/Myget/etc.) and hash.
When source is available, and someone has taken the time to package it, derivations can also build the libraries from source and still produce the nupkg file.

Outputing a single nupkg (zip) file rather than a directory containing the DLLs might seem odd, but dotnet applications typically expect nupkg files as inputs to build and will copy all the DLLs they need in order to run. This may lead to some duplication of files, but that's a problem for another day..

Building from source can get tricky as the nuget tool typically hits the network to fetch dependencies, and obviously we can't have that in Nix. I think Paket (written by @forki et al.) can be a great resource to tackle that problem.

If we generate a directory containing all the nupkg dependencies of a project we are about to build, we can tell Paket to troll through all the project files (fsproj/csproj/etc.) and set them up to use our locally downloaded mirror (hopefully) without ever hitting the network.

Paket will also be invaluable in figuring what are the dependencies that are needed (and their dependencies), etc.

I think the build process should look something like:

```nix
{ stdenv, fetchgit, paket, paketHelper,
  mono, lib1, lib2, lib3 }:

stdenv.mkDerivation {
    version = "1.2.3";
    revision = "7560726734fc7267de2fa9abed2509968deefaa8";
    name = "blah-${version}";

    src = fetchgit {
        url = "https://github.com/blah/blah.git";
        rev = revision;
        sha256 = "1hbnckc4gvqkknf8gh1k7iwqb4vdzifdjd19i60fnczly5v8m1c3";
    };

    paketRepo = paketHelper.makePaketRepo [ lib1 lib2 lib3 ]
    paketDeps = ./paket.references

    postPatch = ''
      # Just copy the paket.references file patching the source line at
      # the beginning to point to the folder created by paketHelper.makePaketRepo
      (echo source ${paketRepo}; grep -v ^source "${paketDeps}") > paket.references

      # Copy the input packages in the packages folder and troll the project
      # files and patch them appropriately
      ${paket}/bin/paket install --hard
    '';

    build = ''
      ${mono}/bin/xbuild
      # Whatever commmand produces the nupkg file
    '';

    # For libraries, install phase should be to copy the nupkg file in the store
    # For applications, something like:
    install = ''
      mkdir -p "$out/opt/blah"
      cp -rv "bin/x64/Release/"* "$out/opt/blah"
      # cp -rv "bin/x64/Debug/"* "$out/opt/blah" <= if you want debugging symbols
      # Create some wrapper:
      cat > "$out/bin/blah" << EOF
      #! ${bash}/bin/bash
      exec ${mono}/bin/mono $out/opt/blah/Blah.exe
      EOF
      chmod 755 "$out/bin/blah"
    '';
}
```

We can of course create a buildDotNetPackage function once we've ironed out the kinks.

Let me know your thoughts.

Cc @lethalman

**Comment by obadz** [comment]
Linking to @svanderburg blog posts trying to use Nix to deploy dotNET apps on Windows.

http://sandervanderburg.blogspot.co.uk/2011/09/deploying-net-applications-with-nix.html
http://sandervanderburg.blogspot.co.uk/2011/09/deploying-net-applications-with-nix_14.html
http://sandervanderburg.blogspot.co.uk/2011/10/deploying-net-services-with-disnix.html
http://sandervanderburg.blogspot.co.uk/2014/06/porting-gnu-autotools-projects-to.html

**Comment by lethalman** [comment]
I know nothing about nuget or how mono libraries are usually packaged. Anyway it's ok if the nuget zip + copy is the easiest way at the beginning. Indeed using paket would be interesting for autogenerating dependencies somehow.

I would be ok to review any implementation, as long as it's viable for our nixpkgs. What does it mean: it works in most cases, maximizes sharing, it's easy to write packages (i.e. it suffices to just list the dependencies).

**Comment by codyopel** [comment]
Just a heads up that I have started cleaning up mono and several C# packages that aren't being built correctly at the moment, I haven't finished the changes yet, but hopefully will by the end of the month.

As far as binaries are concerned, they should be highly discouraged if the software can be built from source.  There are very few cases where any open source software should use pre-compiled binaries within nix.  The only valid case for this I have come across recently is electron (aka atom-shell) which would practically require rewriting their build system to build it on nix (although I think I can even get that to work).

**Comment by obadz** [comment]
Agree with your points on binaries.  It's really either (a) a hack to get there quicker or (b) a means to bootstrap (F# compiler is required to compile F#, Paket sort of needs Paket, etc.)

What's wrong with mono?

**Comment by obadz** [comment]
Note to self/others, we need to somehow point mono to the right root certs so that SSL connections work right out of the box.

**Comment by codyopel** [comment]
True, it does get thing up and going quickly.

The mono build works, but it is using and old improperly built llvm build. Unfortunately mono is not compatible with upstream llvm and they have their own fork that is poorly maintained and shouldn't be enabled by default (for comparison, no other distro even ships llvm support for mono of any kind, they rely on mono's internal JIT implementation).  I mainly am just cleaning a lot of little things where necessary (not just mono) and updating the mono-llvm build that is a year out of date.

Mono and and gtk-sharp are also generating invalid pkgconfig files that I am going to fix too.

**Comment by obadz** [comment]
Am I wrong in thinking that mono/llvm.nix isn't used and that mono/default.nix does not use llvm?

**Comment by obadz** [comment]
@codyopel, Am I wrong in thinking that mono/llvm.nix isn't used and that mono/default.nix does not use llvm?

**Comment by codyopel** [comment]
https://github.com/NixOS/nixpkgs/blob/416ac64143f50d76f523570f1ac243248d04047f/pkgs/development/compilers/mono/default.nix#L4
withLLVM is enabled by default pulling in mono-llvm

**Comment by obadz** [comment]
@codyopel, funny I touched this package twice and didn't notice that llvm was enabled by default.  Agree that's probably not a good idea.  Can we get AOT compiling without LLVM though?

**Comment by codyopel** [comment]
From what I can tell, mono-llvm is not required for AOT compilation, it is only needed if you have files that you previously compiled using LLVM, but you can alternatively use `mono –llvm hello.exe` for support without using llvm for those files.

**Comment by copumpkin** [comment]
:+1:

**Comment by obadz** [comment]
Closing as #7955 was merged
