### ISSUE TITLE
maintainers/scripts/update-python-libraries: cannot update babelgladeextractor

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#79411]
```ShellSession
$ nix run -f '<nixpkgs>' '(with import <nixpkgs> {}; python3.withPackages(ps: with ps; [ packaging requests toolz ]))' -c python ~/Projects/nixpkgs/pkgs/development/interpreters/python/update-python-libraries/update-python-libraries.py ~/Projects/nixpkgs/pkgs/development/python-modules/babelgladeextractor/default.nix
INFO:root:Updating packages...
WARNING:root:Path /home/jtojnar/Projects/nixpkgs/pkgs/development/python-modules/babelgladeextractor/default.nix: found too many values for pname
INFO:root:Finished updating packages.
INFO:root:0 package(s) updated
```

**Comment by jtojnar** [comment]
It appears to be caused by the confusion between `pname` from the `buildPythonPackage`:

https://github.com/NixOS/nixpkgs/blob/78956495de9930857962467b50de066e98eeb10b/pkgs/development/python-modules/babelgladeextractor/default.nix#L10

and `fetchPypi`:

https://github.com/NixOS/nixpkgs/blob/78956495de9930857962467b50de066e98eeb10b/pkgs/development/python-modules/babelgladeextractor/default.nix#L14

**Comment by FRidh** [comment]
There are a lot of improvements possible with that script, I am not sure whether we should track them here. It's an ugly way to get most of the packages to update.

By the way, you can just run `maintainers/scripts/update-python-libraries` directly, instead of using `nix run`.

**Comment by FRidh** [comment]
Closing this. Improvements are possible and welcome.
