### ISSUE TITLE
cannot login via xdmcp

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#7942]
NixOS 14.12
direct cable between 2 PC's.
kdm configured for xdmcp on both ends.
the boxes see each others  hostname
when I select it, get 3 seconds of screen blinks, and am back to the login screen

I can login from debian to nixos just fine. (X -query $IP)
I can also ssh -X from nixos to nixos, but really need a full desktop remotely for my application.

I have not found anything interesting in the logs, but I might have overlooked something.

**Comment by codyopel** [comment]
This is probably part of the same issue as #7902 that is more than likely caused by PAM.

**Comment by magnetophon** [comment]
I just tied again with 2 machines on the latest unstable channel.
Same result.

**Comment by magnetophon** [comment]
I forgot to update this issue, but it's fixed in 15.09.
