### ISSUE TITLE
"failed to remove /lib /lib64" when rebuild

### ISSUE THREAD

**Issue by eoli3n** [NixOS/nixpkgs#79439]
**Describe the bug**
When i rebuild my configuration, i get two warnings
```
rmdir: failed to remove '/lib': No such file or directory
rmdir: failed to remove '/lib64': No such file or directory
```

**To Reproduce**
https://github.com/eoli3n/nix-config/blob/master/hosts/work/configuration.nix
```
nixos-rebuild switch
```

**Expected behavior**
No warnings

**Logs**
```
[...]
building '/nix/store/896l193vlmnfw44pw3ci8a0yi2x9y6mz-user-units.drv'...
building '/nix/store/amykxli2n9nbbaxdrhp0s5g8cq1waab1-etc.drv'...
building '/nix/store/6zi5xbma3h5yyq2ch4kyph2xzspi6icp-nixos-system-work-20.03pre211190.a21c2fa3ea2.drv'...
NOT restarting the following changed units: systemd-fsck@dev-disk-by\x2duuid-D9FD\x2dE1F4.service
activating the configuration...
setting up /etc...
reloading user units for user...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: polkit.service
```

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.100, NixOS, 20.03pre211190.a21c2fa3ea2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre211190.a21c2fa3ea2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:

I don't know which package does this

**Comment by primeos** [comment]
I also noticed this recently and it's reproducible even on no-op rebuilds:
```
[root@nixos-unstable:~]# nixos-rebuild switch 
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
rmdir: failed to remove '/lib': No such file or directory
rmdir: failed to remove '/lib64': No such file or directory
reloading user units for michael...
setting up tmpfiles
```

I had a look though Nixpkgs and it seems to be fixed/reverted already: 26aba55951a09340959b68330875904ac43a3a31 I.e. it shouldn't be there on the next update.

Other relevant commits:
- 5495cb91eb7c3fe1d93be2ea08f75fdd7c907036
- 45db499d2de2235388212a911b8344b58ddfda36
- af665d822a166ae62547c1c310207f11acaded17

Relevant PR: https://github.com/NixOS/nixpkgs/pull/69057

**Comment by Synthetica9** [comment]
Got this a few times as well, followed instantly by a kernel panic on two occasions.

**Comment by primeos** [comment]
The fix is now in `nixos-unstable` and I don't get the error message anymore.

@Synthetica9 that's strange, though the kernel panic should definitely be unrelated to this issue (must be caused by something else later in the activation script (`/run/current-system/activate`)).
