### ISSUE TITLE
liquid haskell can't find module

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#7945]
While trying to use `liquidhaskell` on the following simple Haskell program:
```haskell
import qualified Data.Text.Lazy as L

main = print $ L.unpack $ L.pack "test"
```

I am running into the following error:
```
$ liquid -v test.hs
LiquidHaskell Copyright 2009-14 Regents of the University of California. All Rights Reserved.

Warning: Couldn't do create temp directory: ./.liquid: createDirectory: already exists (File exists)
parseSpec: test.hs
paths = ["/home/wizeman/tmp","/nix/store/hnk52pzwmxbc37kmdph07bwngk46vv3g-haskell-liquidhaskell-0.3.1.0/share/x86_64-linux-ghc-7.8.4/liquidhaskell-0.3.1.0/include/"]

**** DONE:  annotate ***********************************************************
 

**** ERROR: Invalid Source *****************************************************


 test.hs:1:18-31: Error: GHC Error
     Could not find module ‘Data.Text.Lazy’
Perhaps you meant
  Data.Map.Lazy (from containers-0.5.5.1)
  Data.STRef.Lazy (from base)
Use -v to see a list of the files searched for.
```

... while simply using `ghc` works fine:
```
$ ghc test.hs
[1 of 1] Compiling Main             ( test.hs, test.o )
Linking test ...
./
```

Any ideas?

**Comment by gridaphobe** [comment]
Hmm, I suspect the `liquid` binary needs to be wrapped similarly to `ghc` so the search paths are set correctly.

**Comment by gridaphobe** [comment]
As a temporary workaround, try setting

```
NIX_GHC_LIBDIR=$HOME/.nix-profile/lib/ghc-7.8.4
```

in your environment.

**Comment by wizeman** [comment]
@gridaphobe I only have a `manifest.nix` file in `$HOME/.nix-profile`, but based on your suggestion I came up with this command instead:

`(eval "$(grep "export NIX_GHC_LIBDIR" $(which ghc))" && liquid test.hs)`

... which seems to work for me.

Thanks!

**Comment by peti** [comment]
@wizeman, you should add the following snippet to your ~/.bashrc:

~~~~~~~~~~~~~~~ bash
if [ -e ~/.nix-profile/bin/ghc ]; then
  export NIX_GHC="$HOME/.nix-profile/bin/ghc"
  export NIX_GHCPKG="$HOME/.nix-profile/bin/ghc-pkg"
  export NIX_GHC_DOCDIR="$HOME/.nix-profile/share/doc/ghc/html"
  export NIX_GHC_LIBDIR="$HOME/.nix-profile/lib/ghc-$($NIX_GHC --numeric-version)"
fi
~~~~~~~~~~~~~~~

**Comment by wizeman** [comment]
@peti Why do I need to do that?

As I said, I don't have anything in `~/.nix-profile` (except a `manifest.nix` file, for some reason), not even when I'm inside a `nix-shell`.

**Comment by peti** [comment]
The `$HOME/.nix-profile/bin/` bit needs to be adapted to whatever location your compiler is installed at. The point is that `$NIX_GHC" et al must be defined and must point to valid locations, otherwise your installation won't work properly.
