### ISSUE TITLE
Force instaling binary packages only

### ISSUE THREAD

**Issue by eadmaster** [NixOS/nixpkgs#79483]
> When you ask Nix to install a package, it will first try to get it in pre-compiled form from a binary cache. By default, Nix will use the binary cache https://cache.nixos.org ; it contains binaries for most packages in Nixpkgs. Only if no binary is available in the binary cache, Nix will build the package from source.

is it possible to force installing binary/pre-compiled packages only and fail if not found?

Basically, the opposite of [this](https://github.com/NixOS/nixpkgs/issues/20542)

**Comment by matthewbauer** [comment]
You do this by adding some extra flag to nix commands

```
nix-build ... --builders '' --max-jobs 0
```

**Comment by bhipple** [comment]
If you run `nix-env --prebuilt-only` when installing packages, it will fail if it cannot find the package from a binary cache, rather than falling back to compiling from src.  See `nix-env --help` for details.

A similar option does not exist on `nix-build`, as far as I can tell from reading the src.

**Comment by eadmaster** [comment]
thank you, `nix-env --prebuilt-only --install` did the trick.

**Comment by fzakaria** [comment]
@eadmaster i think you actually want `--max-jobs 0` (poorly named) 
```
❯ nix-build --no-out-link lolhello.nix --option max-jobs 0
these derivations will be built:
  /nix/store/vwrgdjl9h1h53ch2zh8cb18nd2raz8a7-lolhello.drv
these paths will be fetched (0.35 MiB download, 0.34 MiB unpacked):
  /nix/store/vgaqghyhgk3apb503q5483v8cmn32ggm-hello-2.3.tar.bz2
error: 1 derivations need to be built, but neither local builds ('--max-jobs') nor remote builds ('--builders') are enabled
```

I think a better name to mimic "substitute" should be present.
