### ISSUE TITLE
Document why there is no JRE or a jre_headless for java derivations after 8

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#79490]
The variant jre11_headless is missing.

**Comment by veprbl** [comment]
cc @edwtjo

**Comment by asbachb** [comment]
Basically there is no jre variant of openjdk11 at all.

**Comment by asbachb** [comment]
relates to https://bugs.openjdk.java.net/browse/JDK-8200132

**Comment by edwtjo** [comment]
@asbachb does not `adoptopenjdk-jre-bin` suffice?

**Comment by doronbehar** [comment]
I also encountered this issue today when I noticed an end user java based program I use references all of `openjdk11` which is ~700Mb in size, whereas `jre8` is ~100Mb in size.

@asbachb:

> Basically there is no jre variant of openjdk11 at all.

Could you please elaborate on this? I mean, in `all-packages.nix`, `jre8` is just a reference to `opendjk8.jre` which is just an output:

https://github.com/NixOS/nixpkgs/blob/90c0191735bc729acd36e4ba72ef3ffd88f679c6/pkgs/development/compilers/openjdk/8.nix#L83-L84

And in `installPhase`, it is used via `$jre` (vs `$out`). Perhaps this approach could be used for all versions of `opendjk`?

**Comment by asbachb** [comment]
Sorry for the delay.

@edwtjo It might be sufficient. But the problem is what @doronbehar describes it seems that end user software is currently relying on a development kit not on a runtime environment.

**Comment by asbachb** [comment]
There an make target `legacy-jre-image` which is also used to generate AdoptOpenJDKs jre variants.

**Comment by ryantm** [comment]
@doronbehar Please do not add non-conversion issues to the conversion project.

**Comment by asbachb** [comment]
I went over some java related tickets. I wonder if we should close this one.

**Comment by doronbehar** [comment]
For reference: https://github.com/NixOS/nixpkgs/blob/2129356a6405cc342e860d87623d3823e8ee3b8c/doc/languages-frameworks/java.section.md#L51-L58

**Comment by asbachb** [comment]
Actually I thought about that issue again. I wonder if it really makes sense to have an individual jre for each application. As these jre are unlikely to match they'd need to be downloaded for every application where as a generic jre could be shared by most of the applications.
