### ISSUE TITLE
libnsgif needs to be exposed for other packages (imv)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#79503]
**Describe the bug**
The newest (next?) version of `imv` requires `libnsgif`. Right now this is only packaged inside the netsurf directory and is not available as a top level attribute for other packages (or an overlay) to use effectively.

We should split it out and then let the netsurf package consume it normally.

**Comment by colemickens** [comment]
Actually, it looks like this was added to imv a long time ago, but imv recently switched to meson. Maybe we just didn't have GIF support in `imv` previously?

I'll look into this. It blocks me from upgrading `imv` to HEAD for `nixpkgs-wayland`.

**Comment by colemickens** [comment]
This is probably not needed. It looks like `libnsgif` defaulted to disabled in the old makefile, so we can just disable it in `mesonFlags`.

**Comment by Artturin** [comment]
It's been available as `netsurf.libnsgif` for a long time
