### ISSUE TITLE
wpa_supplicant service fails when going out of sleep

### ISSUE THREAD

**Issue by MichielDerhaeg** [NixOS/nixpkgs#79514]
**Describe the bug**
When `networking.wireless.interfaces` is not configured, the script that is called by the wpa_supplicant service iterates over all wireless interfaces and adds them to the wpa_supplicant call.
When the service is restarted by udev however, the interface is not present at this point and wpa_supplicant fails because it gets no arguments.

**Comment by MichielDerhaeg** [comment]
If `networking.wireless.interfaces` is configured with the right interface I get:
Could not read interface flags: No such device

In either case, it works fine if I start the service manually.

**Comment by doronbehar** [comment]
Maybe you'll have better luck with iwd? https://nixos.org/nixos/options.html#iwd

**Comment by doronbehar** [comment]
@MichielDerhaeg I've just switched (back) to wpa_supplicant a while ago on my laptop and I don't experience any issues when I go our of sleep. I don't configure `interfaces`.

**Comment by MichielDerhaeg** [comment]
@doronbehar Tried without `interfaces`. Nothing has changed.

This problem is probably partially caused by the particular hardware I'm using (broadcom).
The service scripts can't deal with the interface taking a while to come back up.

Before `wpa_supplicant` just ran without interfaces specified (I think), and then it took care of that for us.

**Comment by doronbehar** [comment]
You may get some help then with discussing it with upstream..

**Comment by MichielDerhaeg** [comment]
Seems to be fixed after upgrading to NixOS 21.05
