### ISSUE TITLE
Haskell packages lose theire "overrideScope" attribute after a normal "override"

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7953]
The following override works fine:

```
hsemail = super.hsemail.overrideScope (self: super: { parsec = super.parsec; });
```

But if a "normal" override is added before the Haskell-specific-one

```
hsemail = (super.hsemail.override {}).overrideScope (self: super: { parsec = super.parsec; });
```

..., then evaluation fails:

> error: attribute ‘overrideScope’ missing, at "/home/simons/.nix-defexpr/pkgs/development/haskell-modules/configuration-common.nix":846:13

The reason is that the `overrideScope` attribute is added by our special `mkDerivation` function from Haskell NG, but `override` is a normal Nixpkgs mechanism that is unaware of this particular feature, i.e. the overridden version of the attribute returned by `override` no longer has `overrideScope`.

**Comment by jwiegley** [comment]
@peti What's the solution to this problem?  I'm trying to build a command-line script for building a given project with profiling enabled.  This fails due to the same problem:

``` bash
    nix-build "$@" -E 'let pkgs = import <nixpkgs> {}; in (pkgs.stdenv.lib.callPackageWith (pkgs // pkgs.haskell7102Packages) ./default.nix {}).overrideScope (self: super: {inherit (pkgs) stdenv; mkDerivation = drv: super.mkDerivation (drv // { enableLibraryProfiling = true; });})'
```

**Comment by peti** [comment]
Um, I don't understand what that command is doing and why it's doing things the way it is.

**Comment by jwiegley** [comment]
It doesn't work, so I guess a better question is: How do I do that?  I have a `default.nix` in a directory, and I want to "nix-build" in that directory, with profiling enabled for that build.

**Comment by peti** [comment]
@jwiegley, the following code will do that:

~~~~
let

  inherit (import <nixpkgs> {}) pkgs;

  haskellPackages = pkgs.haskellPackages.override {
    overrides = self: super: {
      mkDerivation = drv: super.mkDerivation (drv // {
        enableLibraryProfiling = true;
      });
    };
  };

in

  haskellPackages.callPackage ./. {}
~~~~

**Comment by Profpatsch** [comment]
(triage) looks like it is still a problem?
