### ISSUE TITLE
Cargo requires binutils

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#79590]
**Describe the bug**
Cargo doesn't work if `ar` isn't in the path.

**To Reproduce**
1. `cargo new app`
2. Add these to `Cargo.toml`:

     ureq = "0.11.4"

3. `cargo build` will fail with this message:

    error occurred: Failed to find tool. Is `ar` installed?

**Comment by mmahut** [comment]
I don't think this is a bug. This looks like ```ar``` is a dependency of ureq?
