### ISSUE TITLE
Cross-compilation is broken since glibc 2.30 got merged

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#79610]
**Describe the bug**
Cross-compilation is broken since we bumped to glibc 2.30.
- https://github.com/NixOS/nixpkgs/pull/79293#issuecomment-582624367
- https://github.com/NixOS/nixpkgs/pull/79293#issuecomment-583108181

**To Reproduce**
```
$ nix-build -A pkgsCross.raspberryPi.openssl
error: infinite recursion encountered, at /home/freddy/Code/libraries/nixpkgs/pkgs/top-level/all-packages.nix:13581:3
(use '--show-trace' to show detailed location information)
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
I opened a workaround PR :arrow_up:

Cross (boot) is probably best known by @Ericson2314 &ndash; in case you know pointers how to fix this better.  (Possibly later; I don't expect we want to wait long with this PR.)
