### ISSUE TITLE
Open Stage Control

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#79637]
**Project description**
Libre and modular OSC / MIDI controller

**Metadata**

* homepage URL: https://openstagecontrol.ammd.net/
* source URL: https://github.com/jean-emmanuel/open-stage-control
* license: GPLv3
* platforms: electron

**Comment by suhr** [comment]
Still would be cool.

**Comment by Sohalt** [comment]
still relevant

**Comment by Sohalt** [comment]
Still relevant

**Comment by lilyinstarlight** [comment]
I've opened a PR to add this package! See #170464
