### ISSUE TITLE
"bash: /run/user/1000/env-vars: cannot overwrite existing file" when I start nix-shell

### ISSUE THREAD

**Issue by jikamens** [NixOS/nixpkgs#79651]
[Moved here from https://github.com/NixOS/nix/issues/3348, where @zimbatm claims that this is an issue with stdenv and refers to https://github.com/NixOS/nixpkgs/blob/af6336aa34cf38cfbf3e0721b69903a29a9acbac/pkgs/stdenv/generic/setup.sh#L780-L784 as proof.]

When I run `nix-shell` in the source tree of https://github.com/rss2email/rss2email, I get this:

```
bash: /run/user/1000/env-vars: cannot overwrite existing file
```

I just installed nix today so I assume I am running the current version.

I have this in my `~/.bash_profile`:

```bash
if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
    . /home/jik/.nix-profile/etc/profile.d/nix.sh
fi
```

`nix-shell` points at:

```
jik@jik5:~/src/rss2email-1$ type nix-shell
nix-shell is hashed (/home/jik/.nix-profile/bin/nix-shell)
```

I freely admit that this may be a problem with rss2email rather than a problem with nix, but it's not self-evidently that and I don't know how to debug further. Any insight you have would be appreciated.

**Comment by zimbatm** [comment]
btw, this is happening all of the time for me, I am surprised nobody opened a ticket for this already.

**Comment by matthewbauer** [comment]
So we can fix this by doing a `! [ -f "$NIX_BUILD_TOP/env-vars" ]` in dumpVars.

It sounds like this happens when you have the `noclobber` option set in bash.

**Comment by matthewbauer** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/84860 to fix.

**Comment by worldofpeace** [comment]
Yay @matthewbauer , I also have this issue.
