### ISSUE TITLE
xfce+xmonad no longer an available option in NixOS

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#79655]
**Describe the bug**
It used to be possible to set the following in `/etc/nixos/configuration.nix`:

```nix
services.xserver = {
  desktopManager.xfce.enable = true;
  windowManager.xmonad.enable = true;
  displayManager.defaultSession = "xfce+xmonad";
};
```

Now, this configuration results in a warning after running `nixos-option services.xserver.displayManager.defaultSession`:

```
Value:
trace: Default graphical session, 'xfce+xmonad', not found.
Valid names for 'services.xserver.displayManager.defaultSession' are:
  xfce
  none+xmonad
```

And when logging in, “XFCE Session” and “none+xmonad” are the only options presented. I would expect also “xfce+xmonad”, but it is not there.

**To Reproduce**
1. Add the above code to `/etc/nixos/configuration.nix`.
2. Do `nixos-rebuild`.
3. Restart.

**Expected behavior**
xfce+xmonad can be selected in the display manager.

**Additional context**
I am currently using SDDM as my display manager, but I think the problem is deeper than this.

The last working version of nixos-unstable was `8a9807f1941d046f120552b879cf54a94fca4b38`. The first broken version of nixos-unstable is `73a59af35bb72e74c928515aeb6ed6d3f03c9034`. I've tried a couple of versions after this, and they're still broken.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 20.03.git.73a59af (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `""`
 - nixpkgs: `/home/james/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: []
# a list of nixos modules affected by the problem
module: [xfce, xmonad, sddm, displayManagers]
```

**Comment by worldofpeace** [comment]
I believe this was fixed in https://github.com/NixOS/nixpkgs/commit/5e307dc68d9ba72a056543fb0b9b9b8772515313

**Comment by laMudri** [comment]
Looks likely, yeah. I'll give it a go to check...
