### ISSUE TITLE
Package openssl 1.0.2a or higher

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#7970]
This is blocking #7907.

I'm not sure what the Github username of the maintainer (simons) is.

**Comment by peti** [comment]
I am sorry, but I won't have time to package the new version real soon now, because I'm busy finishing stuff for the upcoming 15.06 release. Would anyone else like to take a shot at this?

**Comment by peti** [comment]
A PR was submitted in https://github.com/NixOS/nixpkgs/issues/7970.
