### ISSUE TITLE
Missing pip in virtual env when using venv module from python3.withPackages 

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#79702]
**Describe the bug**
Building a **nixos** python environment with `python3.withPackages` and then creating a virtual environment with `python -m venv` does not install `pip`.

**To Reproduce**

Given the below `default.nix`

```nix
with import (
  builtins.fetchTarball {
    name = "nixos-unstable-2020-02-10";
    url = "https://releases.nixos.org/nixos/unstable/nixos-20.03pre212208.8130f3c1c2b/nixexprs.tar.xz";
    sha256 = "1a0i89rdpxc5fs17z2rradalf814gpyz0daw2qyk67l4dkmyxj2s";
  }) {};

  (pkgs.python37.withPackages (ps: with ps;
  [
    pip
    wheel
    setuptools
  ])).env
```
1. create a directory (e.g. `~/delme`)
2. copy the above `default.nix` in there
3. run `nix-shell`
4. verify that everything has been installed (`python`, `pip`, etc)
5. run `python -m venv venv`
6. inspect `venv/bin`: `pip` is missing and `python` is actually a nix-shell script

```
$ cd ~/delme
$ nix-shell
these derivations will be built:
  /nix/store/99jscyzj3i1vx6dbf1hnirp86ixyis2h-python3-3.7.6-env.drv
building '/nix/store/99jscyzj3i1vx6dbf1hnirp86ixyis2h-python3-3.7.6-env.drv'...
created 255 symlinks in user environment

[nix-shell:~/delme]$ type python
python is /nix/store/nkw3mqknggfw4b4zipqkxw3hkvdsfa9x-python3-3.7.6-env/bin/python

[nix-shell:~/delme]$ type pip
pip is /nix/store/nkw3mqknggfw4b4zipqkxw3hkvdsfa9x-python3-3.7.6-env/bin/pip

[nix-shell:~/delme]$ python --version
Python 3.7.6

[nix-shell:~/delme]$ python -m venv venv

[nix-shell:~/delme]$ ls venv/bin/
activate  activate.csh  activate.fish  python  python3  python3.7

[nix-shell:~/delme]$ file venv/bin/python*
venv/bin/python:    symbolic link to python3.7
venv/bin/python3:   symbolic link to python3.7
venv/bin/python3.7: symbolic link to /nix/store/nkw3mqknggfw4b4zipqkxw3hkvdsfa9x-python3-3.7.6-env/bin/python3.7

[nix-shell:~/delme]$ head venv/bin/python
#! /nix/store/715fljdrspphbdk255r729zxp4w7lcgk-bash-4.4-p23/bin/bash -e
export NIX_PYTHONEXECUTABLE='/nix/store/nkw3mqknggfw4b4zipqkxw3hkvdsfa9x-python3-3.7.6-env/bin/python3.7'
export NIX_PYTHONPATH='/nix/store/nkw3mqknggfw4b4zipqkxw3hkvdsfa9x-python3-3.7.6-env/lib/python3.7/site-packages'
export PYTHONNOUSERSITE='true'
exec "/nix/store/dkm6jsa0apc7vlpdkslpvsxw1qr7kxh2-python3-3.7.6/bin/python3.7"  "$@"
```

**Expected behavior**
A virtual environment with `pip` in it is created.

**Additional context**
- When the virtual environment is activated, it picks up the top level `pip` executable, so running `pip install <package>` results in an attempt to install in the nix store (which of course fails)
- The issue is **not** present when using just the `python3` attribute:
  * `nix-shell -p python37
  * `python -m venv venv`
  * `ls venv/bin`: `pip` is present and works as expected when the virtual env is activated
- Seems similar to #66366 but not quite the same.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101-hardened, NixOS, 19.09.2036.c49da6435f3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2036.c49da6435f3"`
 - channels(user): `"unstable-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [python3, python37]
# a list of nixos modules affected by the problem
module:
```

**Comment by danbst** [comment]
it may be also another example of https://github.com/NixOS/nixpkgs/issues/67211

**Comment by FRidh** [comment]
`venv` invokes by default `ensurepip` but we build our interpreters without `ensurepip` because we provide `pip` as separate packages instead.

**Comment by FRidh** [comment]
But indeed, `venv` does function with normal `python` but not with `python.withPackages`.

```
$ python3 -m venv /tmp/venv2
Error: Command '['/tmp/venv2/bin/python3.7', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Comment by FRidh** [comment]
I've looked into this, and I think the reason it won't work is because our Python is wrapped, we exec it. At that point, when it searches for a `pyvenv.cfg` it is unaware of the environment it was in.

I considered using a `pyvenv.cfg` for our Nix Python env, however, that fails because of exactly this.

**Comment by FRidh** [comment]
When possible, I recommend *not* using `virtualenv` but `venv`, which is part of the standard library in Python 3. No need to create a `python.withPackages` then. This won't work well if you want to use Nixpkgs Python packages as input, but that's anyway not recommended.

**Comment by stefano-m** [comment]
Just checking in after some inactivity. 

The issue is still present to date, my current workaround is to use `nix-shell -p python3 --command 'python -m venv venv` to create a virtual environment in the `venv` directory. 

I am not too bothered about that, but my use case of having a Python environment in my profile **and** being able to create virtual envs is that I both need to write quick and dirty scripts with a bunch of non standard library and do project development with virtual envs (hope this makes sense!)

Thanks again work working on NixOS!

**Comment by stefano-m** [comment]
Thanks for pinging me stalebot! I have verified again and this issue is not present with the current stable release. Yay! :tada: 

This can by using the code below and executing the same steps described in the issue.

``` nix
with import (
  builtins.fetchTarball {
    name = "nixos-unstable-2020-02-10";
    url = "https://releases.nixos.org/nixos/20.09/nixos-20.09.3087.2394284537b/nixexprs.tar.xz";
    sha256 = "0bnwjsamw5hmmv8j6yh9r11qap7gvy4hi0knd6vi7hm0y60wnrar";
  }) {};

  (pkgs.python3.withPackages (ps: with ps;
  [
    pip
    wheel
    setuptools
  ])).env
```


```
[nix-shell:~/code/3rd-party/delme]$ type python
python is /nix/store/fgmf6x7r91g0mxyfv7pmdni0k03izn75-python3-3.8.5-env/bin/python

[nix-shell:~/code/3rd-party/delme]$ type pip
pip is /nix/store/fgmf6x7r91g0mxyfv7pmdni0k03izn75-python3-3.8.5-env/bin/pip

[nix-shell:~/code/3rd-party/delme]$ python -m venv venv

[nix-shell:~/code/3rd-party/delme]$ ./venv/bin/pip --version
pip 20.1.1 from /home/user/code/3rd-party/delme/venv/lib/python3.8/site-packages/pip (python 3.8)

```
