### ISSUE TITLE
Merging JupyterWith in Nixpkgs

### ISSUE THREAD

**Issue by guaraqe** [NixOS/nixpkgs#79703]
I am the maintainer of [JupyterWith](https://github.com/tweag/jupyterWith), a system for setting up JupyterLab severs in a deterministic way using Nix, and I would like to work on a PR to merge it in Nixpkgs. This would give access to many Jupyter kernels to standard Nix users. I have been tracking my progress inside the project in this issue: https://github.com/tweag/jupyterWith/issues/71

I am opening this issue in order to ask some questions:

- I plan to do most of the work inside the current [Jupyter folder](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/jupyter). Is this the appropriate place for doing it?

- It may happen that we need to override some global packages so that they work correctly with Jupyter. What is the correct way for doing that? As an user, I use overlays, but this doesn't seem to make sense inside Nixpkgs. Maybe standard overrides? Should these overridden packages available only locally or also globally?

- I would like to add tests to every Jupyter kernel, which will involve running Jupyter on a sample Notebook. What would be the appropriate location for theses tests?

All feedback is welcome. As soon as I start the pull request, I will link it here.

**Comment by FRidh** [comment]
1. Yes, it's the correct folder. Do check what is there already, we should not be providing multiple implementations of the same or similar functionality. cc @aborsu
2. This is tricky. I imagine you need to override the sub packages sets for which kernels exist. Those typically provide functionality for overriding.
3. That could go in the `jupyter` folder, just make sure you use tiny notebooks (also no generated output).

**Comment by guaraqe** [comment]
Closing for the moment, will reopen if needed.

**Comment by FRidh** [comment]
Just want to point out the new Jupyter Hub service here https://github.com/NixOS/nixpkgs/pull/94783.
