### ISSUE TITLE
  system.copySystemConfiguration = true;     is broken

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#7974]
when I have it in my config, I get:

building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/mjbzg37h0bbmx3q1frvpi8zs9yqdd0cm-nixos-15.06.git.5b27d9bM.drv
building path(s) ‘/nix/store/nszq7y1qshvlys6nsb8z2cf0kmpkwdid-nixos-15.06.git.5b27d9bM’
cp: cannot stat '/etc/nixos/configuration.nix': No such file or directory
builder for ‘/nix/store/mjbzg37h0bbmx3q1frvpi8zs9yqdd0cm-nixos-15.06.git.5b27d9bM.drv’ failed with exit code 1
error: build of ‘/nix/store/mjbzg37h0bbmx3q1frvpi8zs9yqdd0cm-nixos-15.06.git.5b27d9bM.drv’ failed

same happens on 14.12.

**Comment by copumpkin** [comment]
Is your configuration.nix somewhere odd? Do you have chroot builds turned on?

**Comment by magnetophon** [comment]
@copumpkin 
Yes, I have chroot builds turned on:
https://github.com/magnetophon/nixosConfig/blob/master/common.nix#L20

**Comment by copumpkin** [comment]
I think chroot builds will break it, if I understand it correctly. That's probably a problem :smile:

**Comment by magnetophon** [comment]
Tested again on e1af50c, same problem.

**Comment by Profpatsch** [comment]
@magnetophon Current status?

**Comment by vcunat** [comment]
Not fixed, still the same problem. The file needs to be accessed during evaluation time already, not so late as build-time.

**Comment by magnetophon** [comment]
@vcunat: thanks, fixed!

**Comment by magnetophon** [comment]
@vcunat: thanks, fixed!
