### ISSUE TITLE
Creating an official NixOS Discord Server

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#79787]
I think it would be great to have a community "home" in which people can hang out and talk about NixOS in a more informal setting than Github/discourse and without the issues of irc (no chat history, no voice, non-intuitive UI's).

full detailed write up is on discourse here: https://discourse.nixos.org/t/nixos-nixpkgs-nix-discord-for-voice-communication/5845

I'm fine with setting up the channels and moderating (even though my time is limited), I think the role structure could reflect the github permissions, namely:
 - Committer -> Admin
 - Nixpkgs org member -> Moderator
 - Contributor -> Contributor

**Comment by kolbycrouch** [comment]
I think this is a great idea. There are apparently programs out there that can post irc logs on discord and vice-versa, so we could keep everyone connected regardless of their preferred platform ( irc, discord, gitter ).

**Comment by jonringer** [comment]
agreed about the sync'ing

**Comment by samueldr** [comment]
No, I absolutely must vouch *against* those IRC bridges.

The experience is terrible, and creates undue pressure on the IRC side. It's not like how matrix implements it, where every matrix user is a discrete IRC user, and mostly invisible.

Rather, the protocol bridge is one bot that spews endless lines. What's worse, is the way it handles multi-line messages, which is just nasty, even on servers where they are first-class citizen.

**Comment by jonringer** [comment]
Well, it would have been nice if there was a way to sync, but seeing as they are two different platforms with own opinions of users, I guess that makes sense.

**Comment by zimbatm** [comment]
I already had a group created a while ago. Anyone can join: https://discord.gg/MyQ3MpJ

**Comment by jonringer** [comment]
@zimbatm I joined yours, if want to give me admin rights, I can flesh out the rest of the roles, channels, permissions, and everything else

**Comment by zimbatm** [comment]
done

**Comment by jonringer** [comment]
Discord is still an unofficial platform.

Current community server can be found https://discord.gg/RbvHtGa

I'll be doing office hours twice a day if anyone would be interested in getting help: https://discourse.nixos.org/t/discord-office-hours-jonringer/5869
