### ISSUE TITLE
mkdir $out in development/go-modules/generic/default.nix fails because already there

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#7980]
# problem
when installing the gotk3 package from my hacked pkgs/top-level/go-packages.nix

<pre>
  gotk3 = buildGoPackage rec {
    rev = "7a6ce3ecbc883d4d6a7aa1821bbc9633751fd67e";
    name = "gotk3-${stdenv.lib.strings.substring 0 7 rev}";
    goPackagePath = "github.com/conformal/gotk3";
    propagatedBuildInputs = [ pkgconfig pkgs.gnome3.gtk ];
    src = fetchFromGitHub {
      inherit rev;
      owner = "conformal";
      repo = "gotk3";
      sha256 = "0lrav6s28s8vxsvsdr8gf6kzyv00yr3pxq4k66rri9wz0zcc05b1";
    };
  };
</pre>

i get this error:

<pre>
nix-env -f $NIXPKGS -i go1.3-gotk3
installing ‘go1.3-gotk3-7a6ce3e’
these derivations will be built:
  /nix/store/pnph33pn1y5bazgy6gi0ga2ryhwb069i-go1.3-gotk3-7a6ce3e.drv
building path(s) ‘/nix/store/i9vsrkrd82y4pwv4rq033gnww237im21-go1.3-gotk3-7a6ce3e’
unpacking sources
unpacking source archive /nix/store/5mf833k15njwsx3x6y17l1z3z86kvcni-gotk3-7a6ce3ecbc883d4d6a7aa1821bbc9633751fd67e-src
source root is gotk3-7a6ce3ecbc883d4d6a7aa1821bbc9633751fd67e-src
patching sources
configuring
building
github.com/conformal/gotk3/glib
github.com/conformal/gotk3/gdk
github.com/conformal/gotk3/cairo
github.com/conformal/gotk3/pango
github.com/conformal/gotk3/gtk
github.com/conformal/gotk3/gtk/examples/goroutines
github.com/conformal/gotk3/gtk/examples/drawingarea
github.com/conformal/gotk3/gtk/examples/textview
github.com/conformal/gotk3/gtk/examples/simple
github.com/conformal/gotk3/gtk/examples/grid
github.com/conformal/gotk3/gtk/examples/addremove
github.com/conformal/gotk3/gtk/examples/signals
github.com/conformal/gotk3/gtk/examples/boolprops
installing
hello world0
/nix/store/i9vsrkrd82y4pwv4rq033gnww237im21-go1.3-gotk3-7a6ce3e
total 3936
drwxr-xr-x    3 nixbld1 nixbld    4096 May 25 00:48 .
drwxrwxr-t 4044 root    nixbld 4018176 May 25 00:48 ..
drwxr-xr-x    3 nixbld1 nixbld    4096 May 25 00:48 lib
hello world1
mkdir: cannot create directory '/nix/store/i9vsrkrd82y4pwv4rq033gnww237im21-go1.3-gotk3-7a6ce3e': File exists
</pre>

the file called:
/nix/store/i9vsrkrd82y4pwv4rq033gnww237im21-go1.3-gotk3-7a6ce3e/lib/gdk-pixbuf-loaders-2.0/go1.3-gotk3-7a6ce3e/loaders.cache

is created in a different phase of installing gotk3 -> i've checked that as i removed it prior to the build.

# possible solution:
use 

    mkdir -p $out
instead of

    mkdir $out

in development/go-modules/generic/default.nix in the installPhase
# stats
joachim@lenovo-t530 ...ojects/nixos/nixpkgs/pkgs/development (git)-[webloop] % ag 'mkdir.*out' | grep -e '-p' | wc
    552    2303   36647
joachim@lenovo-t530 ...ojects/nixos/nixpkgs/pkgs/development (git)-[webloop] % ag 'mkdir.*out' | grep -v -e '-p' | wc
     46     140    2446

so 552 times it is used with -p and 46 times without. so maybe we just should change that to -p then?

# loaders.cache
<pre>
cat /nix/store/i9vsrkrd82y4pwv4rq033gnww237im21-go1.3-gotk3-7a6ce3e/lib/gdk-pixbuf-loaders-2.0/go1.3-gotk3-7a6ce3e/loaders.cache 
# GdkPixbuf Image Loader Modules file
# Automatically generated file, do not edit
# Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.31.3
#
# LoaderDir = /nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders
#
"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so"
"pnm" 4 "gdk-pixbuf" "PNM/PBM/PGM/PPM" "LGPL"
"image/x-portable-anymap" "image/x-portable-bitmap" "image/x-portable-graymap" "image/x-portable-pixmap" ""
"pnm" "pbm" "pgm" "ppm" ""
"P1" "" 100
"P2" "" 100
"P3" "" 100
"P4" "" 100
"P5" "" 100
"P6" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jasper.so"
"jpeg2000" 4 "gdk-pixbuf" "JPEG 2000" "LGPL"
"image/jp2" "image/jpeg2000" "image/jpx" ""
"jp2" "jpc" "jpx" "j2k" "jpf" ""
"    jP" "!!!!  " 100
"\377O\377Q" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so"
"bmp" 5 "gdk-pixbuf" "BMP" "LGPL"
"image/bmp" "image/x-bmp" "image/x-MS-bmp" ""
"bmp" ""
"BM" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so"
"ani" 4 "gdk-pixbuf" "Windows animated cursor" "LGPL"
"application/x-navi-animation" ""
"ani" ""
"RIFF    ACON" "    xxxx    " 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pcx.so"
"pcx" 4 "gdk-pixbuf" "PCX" "LGPL"
"image/x-pcx" ""
"pcx" ""
"\n \001" "" 100
"\n\002\001" "" 100
"\n\003\001" "" 100
"\n\004\001" "" 100
"\n\005\001" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ras.so"
"ras" 4 "gdk-pixbuf" "Sun raster" "LGPL"
"image/x-cmu-raster" "image/x-sun-raster" ""
"ras" ""
"Y\246j\225" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so"
"icns" 4 "gdk-pixbuf" "MacOS X icon" "GPL"
"image/x-icns" ""
"icns" ""
"icns" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so"
"png" 5 "gdk-pixbuf" "PNG" "LGPL"
"image/png" ""
"png" ""
"\211PNG\r\n\032\n" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so"
"qtif" 4 "gdk-pixbuf" "QuickTime" "LGPL"
"image/x-quicktime" "image/qtif" ""
"qtif" "qif" ""
"abcdidsc" "xxxx    " 100
"abcdidat" "xxxx    " 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so"
"tiff" 5 "gdk-pixbuf" "TIFF" "LGPL"
"image/tiff" ""
"tiff" "tif" ""
"MM *" "  z " 100
"II* " "   z" 100
"II* \020   CR\002 " "   z zzz   z" 0

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so"
"xbm" 4 "gdk-pixbuf" "XBM" "LGPL"
"image/x-xbitmap" ""
"xbm" ""
"#define " "" 100
"/*" "" 50

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so"
"xpm" 4 "gdk-pixbuf" "XPM" "LGPL"
"image/x-xpixmap" ""
"xpm" ""
"/* XPM */" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so"
"tga" 4 "gdk-pixbuf" "Targa" "LGPL"
"image/x-tga" ""
"tga" "targa" ""
" \001\001" "x  " 100
" \001\t" "x  " 100
"  \002" "xz " 99
"  \003" "xz " 100
"  \n" "xz " 100
"  \v" "xz " 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so"
"jpeg" 5 "gdk-pixbuf" "JPEG" "LGPL"
"image/jpeg" ""
"jpeg" "jpe" "jpg" ""
"\377\330" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so"
"ico" 5 "gdk-pixbuf" "Windows icon" "LGPL"
"image/x-icon" "image/x-ico" "image/x-win-bitmap" ""
"ico" "cur" ""
"  \001   " "zz znz" 100
"  \002   " "zz znz" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so"
"gif" 4 "gdk-pixbuf" "GIF" "LGPL"
"image/gif" ""
"gif" ""
"GIF8" "" 100

"/nix/store/qna860hc9r3vbj3vxq2fv1lazzsiwwy8-gdk-pixbuf-2.31.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-wbmp.so"
"wbmp" 4 "gdk-pixbuf" "WBMP" "LGPL"
"image/vnd.wap.wbmp" ""
"wbmp" ""
"  " "zz" 1
" `" "z " 1
" @" "z " 1
"  " "z " 1
</pre>

**Comment by wkennington** [comment]
Where is this the case in the current buildGoPackage as of HEAD?

**Comment by wkennington** [comment]
Should have been fixed by e89f90cd33f1efb7e5d52b74ffc24449968a41b1

**Comment by qknight** [comment]
nice
