### ISSUE TITLE
nix-shell can't be run

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#79800]
**Describe the bug**
Failing to start nix-shell in Fish shell and bash

```
> nix-shell -p python3                                                                                                                                                                                    The program ‘clear’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.busybox
  nix-env -iA nixos.ncurses
  nix-env -iA nixos.ncurses5
  nix-env -iA nixos.toybox

>  nix-shell                                                                                                                                                                                          
error: getting status of '/home/mudrii/default.nix': No such file or directory

> type clear
clear is /run/current-system/sw/bin/clear

> clear -V
ncurses 6.1.20190112
```

**To Reproduce**
1. Just run nix-shell

**Expected behavior**
Getting inside nix-shell

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.31 MiB unpacked):
  /nix/store/5h35s50503spks8gkxdv3kk4szz8vx9g-bash-interactive-4.4-p23-dev
  /nix/store/qghrkvk86f9llfkcr1bxsypqbw1a4qmw-stdenv-linux
copying path '/nix/store/5h35s50503spks8gkxdv3kk4szz8vx9g-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/qghrkvk86f9llfkcr1bxsypqbw1a4qmw-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.17, NixOS, 19.09.2036.c49da6435f3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"home-manager-19.09, nixos-19.09.2036.c49da6435f3, unstable-20.03pre212208.8130f3c1c2b"`
 - channels(mudrii): `"home-manager, unstable-20.03pre196836.1c40ee6fc44"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment]
I'm going to close this as expected behavior. The `nix-shell` is meant to provide an environment identical to the one used for `nix-build`, which means bash is used.

For what you seem to want to do, use `nix run` instead, e.g.:
```
nix run nixpkgs.python3
```

**Comment by FRidh** [comment]
As a work-around you could start bash and then `nix-shell`, and for convenience create a wrapper script that execs.

**Comment by LuluIto** [comment]
bash-4.4# nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/74dgx0ijqh94qmjs27285ywj10nkgvwb-nix-info
copying path '/nix/store/74dgx0ijqh94qmjs27285ywj10nkgvwb-nix-info' from 'https://cache.nixos.org/'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.104-linuxkit`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.2`
 - channels(root): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
