### ISSUE TITLE
Media keys don't work with xfce4-pulseaudio-plugin in xfce

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#79839]
**Describe the bug**
Moved over from discourse https://discourse.nixos.org/t/media-keys-not-working-with-xfce4/5846.

**To Reproduce**
1. Use Xfce and enable pulseaudio
2. Try to use media keys

**Comment by JeffLabonte** [comment]
Xfce4-14 on 19.09 doesn't allow me to use the volume key. I need to run the old version of Xfce if I want to have at least that working.

**Comment by worldofpeace** [comment]
This fixes that, https://github.com/NixOS/nixpkgs/pull/79844. Will backport to 19.09 somehow.

**Comment by vcunat** [comment]
Seems all done.
