### ISSUE TITLE
Cannot start nix-shell with "waf" package

### ISSUE THREAD

**Issue by lunaticare** [NixOS/nixpkgs#79909]
**Describe the bug**
Cannot start `nix-shell` environment with `waf` package.

**To Reproduce**
1. Add channel `nix-channel --add https://nixos.org/channels/nixos-19.09 nixos; nix-channel --update`
2. Start shell with waf package `nix-shell -I '<nixos>' -p waf`
3. See error message:
    ```
    bash:
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    
    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
    
    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
    
    3. The name of the author may not be used to endorse or promote products
       derived from this software without specific prior written permission.
    
    THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS: File name too long
    ```
    
**Expected behavior**
New shell is started with `waf` command available.

**Additional context**
 I need `waf` tool for my project, looking for some way to get it.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.3.0, macOS 10.15.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(user): `"nixos-19.09.2036.c49da6435f3, nixpkgs-19.09pre194742.2633e93f3ec, nixpkgs-unstable-20.03pre212770.cc1ae9f21b9"`
 - channels(root): `"darwin, nixpkgs-19.09pre193666.44fb9ec8719"`
 - nixpkgs: `/Users/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by jonringer** [comment]
took a look at the upstream install instructions... this is the most unusual python project I have ever seen. Not sure why they didn't got with a package structure, and just publish it on pypi

**Comment by matthewbauer** [comment]
Yeah - waf was originally the binary itself. But we can move it to $out/bin/waf so that nix-shell works properly. See https://github.com/NixOS/nixpkgs/pull/81867

**Comment by veprbl** [comment]
It doesn't seem to work with nix-shell now:
```
# nix-shell -p waf -I nixpkgs=channel:nixpkgs-unstable --run waf 
Error: Cannot unpack waf lib into /nix/store/lrq4kj81mc01rjdwkhj4b1s603bwqhw5-waf-2.0.20/bin/.waf3-2.0.20-72ad4a876e330a75f9f770e532535c96
Move waf in a writable directory
```
