### ISSUE TITLE
buildFHSUserEnv on non-x86

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#79926]
On non-x86 machines the `multiPkg` parameter needs to explicitly set to `null` at the use-site, so `buildFHSUserEnv` won't try to get `pkgsi686Linux`.

https://github.com/NixOS/nixpkgs/blob/ef38093b13e0eb522e59a03a51af6154621b1c90/pkgs/build-support/build-fhs-userenv/env.nix#L4

https://github.com/NixOS/nixpkgs/blob/ef38093b13e0eb522e59a03a51af6154621b1c90/pkgs/build-support/build-fhs-userenv/env.nix#L26

https://github.com/NixOS/nixpkgs/blob/ef38093b13e0eb522e59a03a51af6154621b1c90/pkgs/build-support/build-fhs-userenv/env.nix#L35

**To Reproduce**
1. be on anything else than x86
2. try commenting out the multiPkgs line and run nix-shell again
 ```
$ cat shell.nix 
{ pkgs ? import <nixpkgs> {} }:

(pkgs.buildFHSUserEnv {
  name = "TestEnv";
  multiPkgs = null;
  targetPkgs = pkgs: with pkgs; [ x y z ];
}).env
```
**Expected behavior**
Not having to set an unused option to `null`, which is achieved either by:
1.  `pkgsi686Linux` (defined in `pkgs/top-level/stage.nix`) should be replaced by a general  wrapper for 32 bit package sets for the current architecture
2. `multiPkgs` should be a synonym for `targetPkgs` on non-x86
3. (trivial) `multiPkgs` should default to `null`

**Comment by Aleksanaa** [comment]
Already fixed for bubblewrap and chroot

https://github.com/NixOS/nixpkgs/blob/df41961bd4b7e838cb997543ea1297f4cbd7da15/pkgs/build-support/build-fhsenv-chroot/env.nix#L30
