### ISSUE TITLE
Should HDF5 be unmarked as broken on Darwin?

### ISSUE THREAD

**Issue by tviti** [NixOS/nixpkgs#79952]
This package was [marked as broken](https://github.com/nixos/nixpkgs/commit/8836c4d71b13a3052fc5f360a987dea859c9bf5e) on macOS (w/ gfortran) in 2017, but as far as I can tell the issue encountered then (based on the associated [hydra build log](https://hydra.nixos.org/build/62044922/nixlog/1)) is no longer a problem ([if I re-enable it](https://github.com/tviti/nixpkgs/commit/5933a0699cfaeab19f19a04f265e824bc20d0539), the compilation plows through the section where it would normally throw an error).

I admittedly haven't done a whole lot of testing to see if something more subtle
could be amiss.

**Comment by veprbl** [comment]
@tviti If you think it works, please submit a PR.
