### ISSUE TITLE
VMWare tools doesn't support shared folders

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#7995]
https://github.com/NixOS/nixpkgs/pull/7829 is a great first step towards getting that, but upon further inspection, it appears to disable building the associated kernel module, which I think is what's needed to use `mount.vmhgfs` properly.

Mostly just putting this here to track that it's unsupported. Great work on the original issue!

**Comment by copumpkin** [comment]
cc @joamaki

**Comment by joamaki** [comment]
Looking into it, but it's not totally trivial. Will need some patches to make it work on newer kernels. I'll try to make it optional and disabled by default as not everyone needs it.

**Comment by joamaki** [comment]
Alright, preliminary support for this in #8004. Not the cleanest of approaches so suggestions welcome.

**Comment by Profpatsch** [comment]
(triage) can we close this?

**Comment by peterhoeg** [comment]
I'm going to go ahead an close this as shared folders should be supported now.
