### ISSUE TITLE
debootstrap: setup fail with jessie (systemd related)

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#8000]
`debootstrap jessie ./jessie-chroot` fails while setting up its dependencies.
The most likely source seems to be a systemd issue with /dev/urandom: https://gist.github.com/bendlas/d59bf45d879298aa1bd2#file-debootstrap-log-L920-L924

`debootstrap wheezy ./wheezy-chroot` works as expected.

EDIT: Tested on https://github.com/NixOS/nixpkgs-channels/commit/f93a8ee1105f4cc3770ce339a8c1a4acea3b2fb6 + a couple of unrelated, local commits

**Comment by bendlas** [comment]
This has already been patched upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776912
And I can confirm, that a debootstrap updated resolves this: https://github.com/NixOS/nixpkgs/pull/8001

**Comment by lethalman** [comment]
Closed by #8001
