### ISSUE TITLE
pcmanfm typing to search broken

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#80030]
**Describe the bug**
When focused in your pcmanfm window, typing some letters should focus the best matching file and continue cycling through selections as you type. It does not work this way on NixOS. Each new keypress is treated like a new search, starting over what was typed. I also occasionally get graphical glitching when I type, in the form of flashes that I can't quite screenshot.

**To Reproduce**
Open up pcmanfm in a directory with multiple files and start typing one of their names.

**Expected behavior**
If I have files "dab", "dabber", and "dob", typing d should go to "dab" because it's first alphabetically, but then if I type an o it should go to "dob", or if I type "dabb" it should go to "dabber".

**Additional context**
I am running Sway on Wayland. This bug did not seem to exist on Guix System, however I believe it has been a problem the whole time I've ran NixOS the last few months.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre212208.8130f3c1c2b"`
 - channels(brad): `"home-manager, nixos-20.03pre199897.471869c9185"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Notify maintainers**

@ttuegel 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pcmanfm
# a list of nixos modules affected by the problem
module:
```

**Comment by Soundtoxin** [comment]
Some errors (or rather warnings, maybe unrelated) launching pcmanfm from a terminal.
```
brad@anpan:~/ > pcmanfm

** (pcmanfm:8836): WARNING **: 03:27:43.246: The directory '~/Templates' doesn't exist, ignoring it

(pcmanfm:8836): Gtk-WARNING **: 03:27:43.348: Theme parsing error: <data>:2:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pcmanfm:8836): Gtk-WARNING **: 03:27:43.348: Theme parsing error: <data>:3:30: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version
```

These ones happen specifically if I start typing in the window with plans to search:
```
Gdk-Message: 03:27:53.484: Window 0x11829c0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 03:27:53.484: Window 0x11829c0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 03:27:53.484: Window 0x11829c0 is a temporary window without parent, application will not be able to position it on screen.
```
(repeated lines continuing with each keystroke...)

**Comment by FliegendeWurst** [comment]
Works for me on Plasma Wayland. Feel free to reopen if it is still an issue on Sway.
