### ISSUE TITLE
nixosTests.mathics is broken

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#80055]
The mathics test does not work because:

```bash
$ nix-build nixos/tests/mathics.nix
...
error: Django-2.2.10 not supported for interpreter python2.7
```

/cc @volth @benley (commit history)

**Comment by falsifian** [comment]
I see the same error with `nix-env -iA nixos.mkdocs` on the 20.03 beta channel. I think it also happens on Master. It used to work (maybe a few weeks ago? if I have time I'll bisect).

**Comment by flokli** [comment]
@tfc I added https://github.com/NixOS/nixpkgs/pull/95505 removing mathics.
