### ISSUE TITLE
Can't reconnect to machine after hibernation in a test

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#8005]
Follow-up to #6679. I've tried to write a test to check if hibernation works in NixOS. However, there's a problem: after hibernation and (successful) resume, I can't reconnect to the virtual machine from the testing script, which causes it to hang. Any ideas how to do this?

See https://github.com/abbradar/nixpkgs/commit/b98d16a839e0bcebc50f84608f2ab29994df39f4 for the actual test, you would also need https://github.com/abbradar/nixpkgs/commit/d7adc7375c559c42a0d7f6e63a5cefac23869aaf to make it work.

**Comment by edolstra** [comment]
This is probably because the test script cannot reconnect to the backdoor in the VM, because it's already running. Maybe it should be stopped before hibernation and restarted afterwards?

Alternatively, on the Perl side, you could set `$machine->{connected}` so that `connect()` will skip waiting for the backdoor to connect.

**Comment by abbradar** [comment]
Hm, it looks there's rather some problem with hibernation -- `powerManagement.resumeCommands` are not executed after the resume at all (tested by trying to write to /dev/kmsg), and so do commands after `systemctl hibernate` in daemonized scripts. Sadly I don't have time to further investigate this now; will look at this later in June.

**Comment by Profpatsch** [comment]
Unless @abbradar wants to continue working on this, we can close.

**Comment by abbradar** [comment]
Let's close, if I return to this I may reopen.

**Comment by abbradar** [comment]
I've found the core of the problem and workarounded it; the test is in https://github.com/NixOS/nixpkgs/commit/9cc70b419cc75bbf7f3224ad9f6848760adac1fd. I'll copy my description of the problem from comments:

9P doesn't support reconnection to virtio transport after a hibernation.
Therefore, machine just hangs on any Nix store access.
To work around it we run a daemon which listens to a TCP connection and
try to connect to it as a test.
