### ISSUE TITLE
dockerTools.buildLayeredImage

### ISSUE THREAD

**Issue by kamadorueda** [NixOS/nixpkgs#80086]
**Describe the bug**
Given the 'contents' (list of derivations to be included in the image) has a closure size (number of packages that are needed to build the 'contents') greater than 'maxLayers' (which is limited to 125)
Then the image is built but only $maxLayers derivations from 'contents' are shipped into the image
And the remaining ones are missing

**To Reproduce**
1. If I build a image with contents = [ bash ] and maxLayers 125 then I can find bash in the final image

2. Then I build a layered image with the following packages but bash is missing from the final image!! (one can see by the nix-build output that 125 layers were created)
```
      aws-iam-authenticator
      awscli
      bash
      cacert
      coreutils
      curl
      docker
      envsubst
      git
      jq
      kubectl
      nix
      nix-linter
      nss
      openssl
      shellcheck
      sops
      terraform
      tflint
      which
```
3. The bug is that when you include too many packages in the 'contents' list, some packages are just not shipped into the container

**Expected behavior**
Everything included in the final image

**Screenshots**

![bug](https://user-images.githubusercontent.com/47480384/74500589-588e7680-4eb5-11ea-800a-e5019b8cfb47.gif)

**Additional context**
Just trying to build an image with nix, learning and trying to apply this to my company :)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-29-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(kamado): `"nixos-20.03pre211190.a21c2fa3ea2, nixpkgs-20.03pre211998.57ed5db343f"`
 - nixpkgs: `/home/kamado/.nix-defexpr/channels/nixpkgs`
```
the packages used to build the image are:

```
  repo = "https://github.com/NixOS/nixpkgs";
  commit = "b78092a5511bfedb9b344543d30acb176d2b840d";
  digest = "0prv61cf37rpixmc62jln1xdzbw5vqnq944110smkgbhdrgvi512";
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dockerTools.buildLayeredImage
# a list of nixos modules affected by the problem
module:
```

**Comment by kamadorueda** [comment]
@grahamc nice article about the topic by the way

**Comment by kamadorueda** [comment]
If I'm pointed to the direction in which this bug could be solved I'm willing to work on the PR

**Comment by veprbl** [comment]
Possible duplicate of #78744?

**Comment by kamadorueda** [comment]
@veprbl thank you very much
