### ISSUE TITLE
python3Packages.spyder broken

### ISSUE THREAD

**Issue by marcus7070** [NixOS/nixpkgs#80083]
**Describe the bug**
Spyder won't build from master (c1741fc12a3329cf4c4509f22c60dfd4d54a192f).

**To Reproduce**
```
nixpkgs> nix-build -A python3Packages.spyder
<snipped>
installing
Executing pipInstallPhase
/build/spyder-4.0.0/dist /build/spyder-4.0.0
Processing ./spyder-4.0.0-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement intervaltree (from spyder==4.0.0) (from versions: none)
ERROR: No matching distribution found for intervaltree (from spyder==4.0.0)
builder for '/nix/store/sbrpfrncamjnhn8bvnx6ryw0b9xx490l-python3.7-spyder-4.0.0.drv' failed with exit code 1
error: build of '/nix/store/sbrpfrncamjnhn8bvnx6ryw0b9xx490l-python3.7-spyder-4.0.0.drv' failed
```

**Additional context**
A batch update of python packages bumped spyder from 3.3.6 to 4.0.0, but didn't add the new dependencies such as `intervaltree`.
https://github.com/NixOS/nixpkgs/blob/c1741fc12a3329cf4c4509f22c60dfd4d54a192f/pkgs/development/python-modules/spyder/default.nix

I'm confused why this version bump was done. Unless I'm missing something huge, I think this derivation would never have successfully built.

I think I can fix this all myself, I'll open up a draft PR as I work on it.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python3Packages.spyder
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
@marcus7070 did you run into any issues with code completions with 3.3.x? 

We won't be able to fulfill the dependency requirements for 4.x (specifically, the jedi package version), so it is probably best to revert to 3.3.x. However, that constraint was added because of issues with newer versions. Given the 3.3.x also needs jedi, I would expect those issues to exist there as well. If that is the case, reverting is pointless and we should just disable the version constraint.

**Comment by marcus7070** [comment]
Thanks for having a look @FRidh.

> did you run into any issues with code completions with 3.3.x?

I don't use Spyder standalone, it's a component of cq-editor which I maintain. But even in cq-editor, I still don't use code completion. So I can't shed any light on what the Spyder devs mean when they write:
```
    # This is here until Jedi 0.15+ fixes completions for
    # Numpy and Pandas
    'jedi==0.14.1',
```

I couldn't find and issues discussing the Jedi problems in either Spyder or Jedi, and python-language-server uses Jedi and was passing tests specifically with numpy and pandas, so I patched the version requirement for nixpkgs in my PR. 

But I've chased my tail in a complete circle anyway. Turns out cq-editor doesn't work with Spyder 4.x, so I would have to leave Spyder 3.x in nixpkgs. So reverting to 3.3.x is a good solution to me. 

Do you want to revert it or should I do it in my PR?

Note that spyder-kernels would need to be reverted as well. https://github.com/spyder-ide/spyder/blob/47e0d1dc1486755602a5800a90aa964b23bd3e0a/setup.py#L241

**Comment by marcus7070** [comment]
A new release came out a few hours ago: https://github.com/spyder-ide/spyder/releases/tag/v4.1.1
Jedi is pinned to 15.2 in this release.

I'll try to fix this myself, but I won't have any time to do it in the next few days.
