### ISSUE TITLE
haskellPackages.ghc not available on aarch64

### ISSUE THREAD

**Issue by thefloweringash** [NixOS/nixpkgs#80176]
On current master (74e9b1753dd3188790abf6445cd51d9bced5eb25).

```
nix-build -A haskellPackages.ghc
```

Fails with

```
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM 3.9

<no location info>: error: ghc: could not execute: opt

builder for '/nix/store/dazj2j2ccmg1kklfgn5igl77v7sbxk7m-hscolour-1.24.4.drv' failed with exit code 1
```

See also the [full log](https://gist.github.com/thefloweringash/f9446c04fa8e797838e996614d58b023).

**Additional context**

The hscolour derivation mentioned here does not contain `llvm` in its `buildInputs`. It seems sufficient to make `llvm` be a propagated build input for `ghc-8.2.2-binary`, after doing so I can build ghc itself.

```diff
diff --git a/pkgs/development/compilers/ghc/8.2.2-binary.nix b/pkgs/development/compilers/ghc/8.2.2-binary.nix
index 1f24b9a1ff2..bd1b8833087 100644
--- a/pkgs/development/compilers/ghc/8.2.2-binary.nix
+++ b/pkgs/development/compilers/ghc/8.2.2-binary.nix
@@ -53,7 +53,7 @@ stdenv.mkDerivation rec {
     or (throw "cannot bootstrap GHC on this platform"));
 
   nativeBuildInputs = [ perl ];
-  buildInputs = stdenv.lib.optionals (stdenv.targetPlatform.isAarch32 || stdenv.targetPlatform.isAarch64) [ llvm ];
+  propagatedBuildInputs = stdenv.lib.optionals (stdenv.targetPlatform.isAarch32 || stdenv.targetPlatform.isAarch64) [ llvm ];
 
   # Cannot patchelf beforehand due to relative RPATHs that anticipate
   # the final install location/

```

There's a lot of
```
You are using an unsupported version of LLVM!
Currently only 3.9 is supported.
```

**Metadata**
```
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.68, NixOS, 19.09.2070.b9cb3b2fb2f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2070.b9cb3b2fb2f"`
 - channels(lorne): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute: haskellPackages.ghc
```

**Comment by cdepillabout** [comment]
@thefloweringash Can you send a PR fixing this?

**Comment by thefloweringash** [comment]
> @thefloweringash Can you send a PR fixing this?

Done, see https://github.com/NixOS/nixpkgs/pull/80355

**Comment by vcunat** [comment]
- [ ] port to `release-20.03`

**Comment by thefloweringash** [comment]
Since this issue was opened the situation has changed. There's still no ghc on aarch64, but now it fails due to [the lack of aarch64 support][] in `bootPkgs` (aka `ghc863Binary`).

[the lack of aarch64 support]: https://github.com/NixOS/nixpkgs/blob/5f357b20b3b05aad591701c374ade77f470e4d89/pkgs/development/compilers/ghc/8.6.3-binary.nix#L31-L45

**Comment by vcunat** [comment]
After PR #83048 the default ghc builds for aarch64 (8c066853, ATM only in `haskell-updates` branch).
