### ISSUE TITLE
go get breaks with "ld: framework not found CoreFoundation"

### ISSUE THREAD

**Issue by r-darwish** [NixOS/nixpkgs#80177]
**Describe the bug**
Using macOS 10.15.3 for starting with go development. I installed Go 1.13.7 using nix and followed [these instructions](https://github.com/micro/micro#install). However, `go get` breaks with:

```
/nix/store/fws3qldkjn3mc183sa7ny1pk469z9w9a-go-1.13.7/share/go/pkg/tool/darwin_amd64/link: running /nix/store/2mf11yf4ggz39f1ryhwg528qfn9g5mbj-clang-wrapper-7.1.0/bin/cc failed: exit status 1
ld: framework not found CoreFoundation
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've seen https://github.com/NixOS/nixpkgs/issues/9329 and https://github.com/NixOS/nixpkgs/issues/10263 but I'm not sure if they're relevant as they are old and closed.

Compilation worked when I used Go 1.13.8 from Homebrew

**To Reproduce**
1. `nix-env -i go`
2. `export GO111MODULE=on`
3. `go get github.com/micro/micro/v2`

**Expected behavior**
Compilation should work

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.3.0, macOS 10.15.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(roey): `"nixpkgs-20.03pre212770.cc1ae9f21b9"`
 - channels(root): `"nixpkgs-20.03pre212770.cc1ae9f21b9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by LnL7** [comment]
It looks like this is during the build rather not the download. In which case this is expected, "installing" built time dependencies doesn't really work with nix. Compilers and interpreters generally need a build environment, see https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F for more details.

**Comment by r-darwish** [comment]
Makes sense. However, I'm not sure which library should I add to `buildInputs` as `CoreFoundation` is a macOS system library, isn't it?

Also, should I close this issue if it's not really a bug?

**Comment by clord** [comment]
Bad bot. This could be related to the changes made to macos dynamic loader, system libs are no longer present in the file system and can only be found with `dlopen`. solution would be to not `stat` before `dlopen`.

**Comment by toonn** [comment]
I believe thefloweringash has made these changes in #105026.
Nixpkgs does provide `darwin.CF` which is the [swift-corelibs-foundation](https://github.com/apple/swift-corelibs-foundation) implementation of CoreFoundation.
