### ISSUE TITLE
steam missing dependency: lsof

### ISSUE THREAD

**Issue by LouisTakePILLz** [NixOS/nixpkgs#80184]
Steam shows "Show in Steam" instead of the appropriate options without `lsof` installed:
![image](https://user-images.githubusercontent.com/920910/74591617-66dcaf80-4fe7-11ea-9986-599e579cf35c.png)

The following gets printed to stdout when right-clicking on a friend:
```
sh: lsof: command not found
```

With `lsof` installed:
![image](https://user-images.githubusercontent.com/920910/74591670-d6529f00-4fe7-11ea-9de9-3850718409c2.png)

NixOS version: 19.09

**Comment by jonringer** [comment]
@LouisTakePILLz thanks for opening a ticket :)
