### ISSUE TITLE
Launching a program through keyboard shortcut on Plasma removes context

### ISSUE THREAD

**Issue by Elyhaka** [NixOS/nixpkgs#80183]
**Describe the bug**
When I launch `Konsole` using a keyboard shortcut, it didn't get any context, resulting in it displaying strangely:

![konsole](https://user-images.githubusercontent.com/57923898/74591588-5d6c3b00-5019-11ea-8915-5afb834ffe70.jpg)

If I launch it using the menu it displays correctly.

For other applications, depending on what they requires, they sometime just don't open.

**EDIT** : I have the feeling that the reason that `krunner` is not opening when using the keybinding is the same reason.

**To Reproduce**
1. Create a shortcut to Konsole
2. Launch konsole with the shortcut

**Additional information**
While starting `Konsole` with the shortcut, this inputs is visible in `journalctl -f` :

```
févr. 15 17:50:23 ely-lenovo xsession[1137]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ely'
févr. 15 17:50:24 ely-lenovo xsession[1137]: QFSFileEngine::open: No file name specified
févr. 15 17:50:24 ely-lenovo xsession[1137]: QFSFileEngine::open: No file name specified
```

**Expected behavior**
The program should behave the same way as when launched using menu.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.2, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre212208.8130f3c1c2b"`
 - channels(ely): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
@ttuegel

**Comment by worldofpeace** [comment]
Woah, it doesn't seem to even have a PATH environment.

**Comment by Elyhaka** [comment]
**New way to reproduce the issue** : when the feature to restore previous window after a logout/login is active, it restarts the application with the same issue.

**Comment by Elyhaka** [comment]
Applying the fix from #79707 fixed this issue.

**Comment by roconnor-blockstream** [comment]
I cherry-picked #80356 and it fixed this issue for me; however my KDE windows are all still borderless.

**Comment by worldofpeace** [comment]
> I cherry-picked #80356 and it fixed this issue for me; however my KDE windows are all still borderless.

Hmm, that sounds like kwin died.
