### ISSUE TITLE
Make modulesPath work again in NixOS modules

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8018]
I think the recent modules change broke `modulesPath`. A remedy I've seen applied in a couple of places is to use `<nixpkgs>` paths, but those don't necessarily behave the same way in all contexts, so it would be nice to get the original functionality back. I still see evidence of `modulesPath` in the current code, so it seems like there might be some intent to support it, but the current implementation is somehow broken.

cc @nbp @shlevy

**Comment by nbp** [comment]
@edolstra , this was why I restored it.  Because we have no good substitute for it at the moment, what do you think?

**Comment by copumpkin** [comment]
If you can bring it back in the 15.06 timeframe, that'd simplify some of the EC2 work I want to get into it, but otherwise I can probably work around it.

**Comment by copumpkin** [comment]
#8188 is a more concrete version of proposal, so I'm closing this in favor of that.
