### ISSUE TITLE
gitolite-shell: No such file or directory

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8020]
Hi,

I have this Problem:

```
$ git push gitolite --all #in one of my repos, gitolite runs locally, too.
Enter passphrase for key '/home/m/.ssh/id_rsa': 
bash: /nix/store/64a6vzvzq50z288v4m40kyy7xczmhq5p-gitolite-3.6.2/bin/gitolite-shell: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Which seems to be quite critical to me, as I did not rebuild the system or anything (as I cannot atm due to dependency build errors somewhere). I also don't know whether this issue here is already fixed by #7755 because of this.

**Comment by bjornfor** [comment]
I'm guessing that gitolite writes some nix store paths somewhere, and then things break when the nix garbage collector removes those paths. Hack: search for the missing path (inside gitolite config files or whatnot) and possibly update it to a working path.

**Comment by Lassulus** [comment]
If you use "services.gitolite.enable = true" could you check if the "gitolite-init.service" started successfully?

**Comment by matthiasbeyer** [comment]
@Lassulus see #7340

**Comment by Lassulus** [comment]
you could try running "gitolite setup" as gitolite user in the gitolite datadir. Better backup your datadir beforehand but the procedure should be non destructive.

**Comment by matthiasbeyer** [comment]
Hm this does not work because of 

```
FATAL: fingerprinting failed for 'keydir/kqz1c85hv3b33i030dl4phrk38j8am0w-gitolite-admin.pub'
```

And there is no `keydir` in `/var/lib/gitolite/` (as also reported in #7340).

**Comment by Lassulus** [comment]
ah damn, i thought he wouldn't try to sign the key if you do not specify it.
Well, seems like you need to upgrade to v3.6.3 either through fixing your nixos-build errors or by installing gitolite v3.6.3 manually in /var/lib/gitolite.

**Comment by matthiasbeyer** [comment]
Fixing the build errors would be highly appreciated by me, but I guess I have to wait for hydra by now (see https://github.com/NixOS/nixpkgs/issues/7947).

**Comment by Lassulus** [comment]
this should be fixed i guess.

**Comment by matthiasbeyer** [comment]
I think so, too. I will close this.
