### ISSUE TITLE
openssh authentification passphrase request 

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#8028]
Ever since I switched to unstable, when I git push I get a popup with the above title.
@codyopel gave me the tip to
```
unset SSH_ASKPASS
```
in my bashrc and that got rid of the popup for a few days, and then it came back.

**Comment by codyopel** [comment]
I suppose this would be the the way to avoid ssh-askpass gui if you want to:
https://github.com/NixOS/nixpkgs/blob/4b109071524766c53910481cfb1894cbfcd366f4/nixos/modules/programs/ssh.nix#L29L33
https://github.com/NixOS/nixpkgs/blob/21247699ad1bbd7195a78693c23361a6a7600d77/pkgs/applications/version-management/git-and-tools/git/default.nix#L120L132

**Comment by magnetophon** [comment]
@codyopel thanks.

Is this a feature most of us want?
Shouldn't it be turned of by default?

**Comment by peti** [comment]
The pop-up is fine for me, I don't mind it. Especially since I run *ssh* commands sometimes that don't have a window attached. In those cases the pop-up is rather essential, really.

**Comment by magnetophon** [comment]
@codyopel I set ```programs.ssh.askPassword = "";```
I left alone git guiSupport, since afaik that only affects gitk.

I still have the popup.  :(

@peti OK, thanks.

**Comment by edolstra** [comment]
Hm, `$SSH_ASKPASS` is supposed to only be invoked if ssh is not connected to a terminal. That's the behaviour in 14.12, in any case.

**Comment by magnetophon** [comment]
@edolstra yes, that makes sense to me.
It worked like that in 14.12.

Reopen?

**Comment by Balletie** [comment]
This behavior still exists, I think it should be reopened.

**Comment by nixy** [comment]
I also ran into this behavior today and was temporarily disoriented. I think this should be reopened, as I can't imagine I am the only one who will get spooked by this.
