### ISSUE TITLE
trufont

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#80330]
**Project description**
"TruFont is a streamlined and hackable font editor."

**Metadata**

* homepage URL: http://trufont.github.io/
* source URL: https://github.com/trufont/trufont
* license: gpl3
* platforms: all

Never used it, but that's why I'm curious about seeing it packaged! :)

Looks like shouldn't be too rough to package, might need some python deps not yet packaged but nothing too outlandish at a glance (but dunno).

**Comment by AndersonTorres** [comment]
Closing since the project was discontinued.
