### ISSUE TITLE
`haskellPackages.cron` incorrectly marked as broken

### ISSUE THREAD

**Issue by Sir4ur0n** [NixOS/nixpkgs#80336]
Hello!

**Describe the bug**
I think the `cron` Haskell package in version `0.6.2` is incorrectly marked as broken. I have followed the steps from [the Youtube video](https://www.youtube.com/watch?v=KLhkAEk8I20) linked by the [Haskell wiki page](https://nixos.wiki/wiki/Haskell) and the build + tests succeed in branch `haskell-updates` using the command `nix-build --no-out-link -A haskellPackages.cron --arg config '{allowBroken = true;}'`

**To Reproduce**
1. `git checkout haskell-updates`
2. `git pull`
3. `nix-build --no-out-link -A haskellPackages.cron` -> fails as the package is flagged as broken
4. `nix-build --no-out-link -A haskellPackages.cron --arg config '{allowBroken = true;}'` -> succeeds

**Expected behavior**
I would expect this package to no longer be flagged as broken

**Screenshots**
N/A

**Additional context**
N/A

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101, NixOS, 19.09.2036.c49da6435f3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(sir4ur0n): `"nixos-unstable-20.03pre200231.7827d3f4497, home-manager"`
 - channels(root): `"nixos-19.09.2036.c49da6435f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: haskellPackages.cron
```

I hope this is the correct information and I have not overlooked something :/

Thank you!

**Comment by cdepillabout** [comment]
On the `haskell-updates` branch as of rev 2586e9169, `haskellPackages.cron` is no longer marked broken.
