### ISSUE TITLE
Proposal: Set HOME enviroment variable to current build directory in build phases

### ISSUE THREAD

**Issue by rushmorem** [NixOS/nixpkgs#8037]
I find myself packaging a few Java and Python programs these days. Most of these programs utilise build tools like `ant`, `gradle`, `maven`, `pip`, `pants` etc. Most of these tools try to create files in the current user's home directory at one point, e.g. to generate caches. Of course this breaks the build as they won't have write access to `/homeless-shelter`.

At first, once the build broke due to these permission issues, I would then go to the build tool's website to look for environment variables, command-line options etc to override the directory that it's trying to write to. You can easily waste a lot of time trying to track these. Some packages use a number of these build tools (for different languages). It then occurred to me that I could just set `HOME` to the current working directory before trying to build. As you can imagine, this made my life so much easier.

Sometimes, I have to override the build phase just to set this variable. I think setting HOME to default to current working directory in all build phases will make our lives easier as well as make Travis happier. I have seen quite a few packages fail Travis tests (eg Mesos) because of the said permission issues, yet the same packages build fine outside Travis. The reason being that these packages override the said variables in say the `preBuild` hook. I think Travis forks these as separate processes.

What do you guys think. Would this be a good idea?

**Comment by peti** [comment]
Builds should not use `$HOME`, IMHO. I've seen build scripts actually create directories there to store weird test data that's of no important beyond the scope of the build and that clearly belonged into `$TMPDIR` (which `nix-build` defines). From that point of view, I think it's great that those builds fail in Nix, because I want to be aware of the fact that these builds access `$HOME` so that I can investigate what is going on to decide how to remedy the issue. If `$HOME` would point to a legitimate place, then I would no longer notice builds doing something fishy in there.

**Comment by rushmorem** [comment]
@peti I see. Great point. In that case, how about we set it to `$TMPDIR` or generate another temporary directory and point it there. That way we don't even have to worry about those tools corrupting the source code. We know that after the build, anything written there will be thrown away.

**Comment by peti** [comment]
As I said, I *want* build to fail when they access `$HOME`.

**Comment by rushmorem** [comment]
I see. I thought the reason was that you were worried the output of these tools might get mixed up with source code or something. I feel like I'm missing something. Would you be kind enough to shed more light? I would love to learn more.

**Comment by edolstra** [comment]
Setting `HOME` would be a problem for `nix-shell` BTW. Of course, it can be made conditional.

**Comment by rushmorem** [comment]
@edolstra Noted, thanks.

**Comment by rushmorem** [comment]
@edolstra If the variable was made optional, would it be OK for you otherwise? What are your views on this?

**Comment by peti** [comment]
I'm closing this issue because there seems to be not much support in favor of making this change.
