### ISSUE TITLE
Stale nixpkgs branches

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#80413]
noticed we have a multitude of stale branches (18 of which have been closed/merged). Not trying to get rid of everything, but just trying to poke people to do some house cleaning on branches they know are no longer needed.

https://github.com/NixOS/nixpkgs/branches/stale

(these are just some people that are listed as the last committer of a stale branch)

* [ ] @adisbladis
* [ ] @aszlig
* [ ] @copumpkin
* [x] @domenkozar
* [ ] @edolstra
* [x] @fridh
* [x] @joachifm
* [x] @mmahut 
* [ ] @nbp
* [x] @nh2
* [ ] @offlinehacker
* [x] @orivej
* [ ] @pSub
* [x] @timokau
* [ ] @xeji
* [x] @zimbatm

apologize for the spam :/

related issues #36755 #12288

Interesting side-note: Going by the first issue as the beginning of nix on github, half of all PRs/issues have been created in the past 2 years, even though nix has been on github for ~8 years.

**Comment by orivej** [comment]
My branch (`hydra`) seems to be a mistake that should be deleted.

**Comment by nh2** [comment]
I've deleted my merged `texmacs-1.99.10` branch.

**Comment by FRidh** [comment]
Those that are referred to in papers should be made protected branches.

**Comment by domenkozar** [comment]
I deleted mine except for a few I'd like to keep around.

**Comment by joachifm** [comment]
Deleted the one I created

**Comment by mmahut** [comment]
Deleted mine, thank you for checking this out!

**Comment by zimbatm** [comment]
Updated the issue so we can just check our names.

After $TIMEOUT, I propose that we move all the remaining branches to another stable nixpkgs fork like nix-community/nixpkgs

**Comment by jonringer** [comment]
I think this can be closed
