### ISSUE TITLE
uid-map gets corrupted by Unicode usernames

### ISSUE THREAD

**Issue by notpeelz** [NixOS/nixpkgs#80426]
`/var/lib/nixos/uid-map` seems to get corrupted by usernames containing Unicode characters. With every boot and `nixos-rebuild switch`, the size of the file increases. On my live system, this file grew to 2.1GB.

While running `nixos-rebuild switch`, `update-users-groups.pl` will rapidly increase in memory usage (using up all ~62GB of RAM available) until triggering the OOM killer, thus terminating the build process.
![image](https://user-images.githubusercontent.com/920910/74725858-7852d100-520c-11ea-8a5b-e1aca7e51788.png)

In my case, I had created a user with the name of [`😛` (U+1F61B)](http://graphemica.com/%F0%9F%98%9B), but quickly removed it with the next build. Several rebuilds and reboots later, my system became increasingly slow to boot (1+ min). After trying to fix the issue (several rebuilds later), booting/rebuilding would take 5+ minutes.

When trying to boot, the system would hang on "running activation script..." at the beginning of stage 2.

**Artifacts**:
`/var/lib/nixos/uid-map` after running `nixos-rebuild build-vm` then launching the VM a couple times (4-5):
- `hexdump -C /var/lib/nixos/uid-map`: [uid-map-corrupted.hexdump.bin](https://gist.githubusercontent.com/LouisTakePILLz/3b167d4214cc6c441e641ca85d635168/raw/97c71bc8df8425f3859fa705a66dc5672e7183dd/uid-map-corrupted.hexdump.bin)
- raw file: [uid-map-corrupted.raw.bin](https://gist.githubusercontent.com/LouisTakePILLz/3b167d4214cc6c441e641ca85d635168/raw/97c71bc8df8425f3859fa705a66dc5672e7183dd/uid-map-corrupted.raw.bin)

**Steps to reproduce**:
1. Add user `😛` to users.users:
```nix
{ lib, config, pkgs, ... }:

{
  # ...
  users.users.myuser = { uid = 1000; extraGroups = [ "wheel" "docker" "libvirtd" ]; };
  users.users."😛" = { uid = 1001; };
}
```
2. `nixos-rebuild build-vm`
3. Execute the generated run-vm script
4. In the VM, observe the file size with `du -b /var/lib/nixos/uid-map`
5. Repeat from step 2 until system/build becomes unresponsive

Thanks to @cleverca22 for helping me figure this out.

**Comment by LouisTakePILLz** [comment]
Still relevant

**Comment by jonringer** [comment]
just cc'ing some people @Mic92 @Ma27 @aanderse  @volth  as I don't know perl

**Comment by aanderse** [comment]
ping @stigtsp as well.

**Comment by Mic92** [comment]
In long-term we should consider using https://systemd.io/USERDB_AND_DESKTOPS/ which is close to the concept of our database and also compatible with the rest of the Linux ecosystem.

**Comment by Mic92** [comment]
I noticed when testing the example configuration of https://github.com/NixOS/nixpkgs/issues/80426#issue-566802577 in nixos-shell that it tries to remove the user on every activation:


```
% /nix/store/hk1np5bxy22awzdkb1hclvqiai5y23dm-nixos-system-nixos-21.03.git.3a3da0950d5/activate test
removing user ‘😛’
setting up /etc...
$ /nix/store/hk1np5bxy22awzdkb1hclvqiai5y23dm-nixos-system-nixos-21.03.git.3a3da0950d5/activate test
removing user ‘😛’
setting up /etc...
```

For simplicity it should tried the user name as a series of bytes instead of trying to decode it.

**Comment by Mic92** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/98544
