### ISSUE TITLE
nixos/modules/programs/fish: completion generator patch does not work with fish 3.1.0 package

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#80423]
**Describe the bug**
When trying to use the nixos module `programs.fish` a patch is applied. This patch however does not match the updated fish package for `3.1.0`.

**To Reproduce**
1. Configuration containing: `programs.fish.enable = true`
2. `nixos-rebuild switch`

**Expected behavior**
The `programs.fish` module should be able to be enabled.

**Additional context**
```
building '/nix/store/flfdj6b0kjl5ncfllibhm4j13whklcxl-find-libs.drv'...
building '/nix/store/y54wzrnzassarw2p3jv361nqpf1hz5x1-fish_patched-completion-generator.drv'...
building '/nix/store/3aw30paxs1v05lbsi8xq1315cbg4if46-fix-bubblewrap-paths.patch.drv'...
unpacking sources
unpacking source archive /nix/store/z08mbgrf14gvv13i1hcw8wwjicdgn3k2-fish-3.1.0/share/fish/tools/create_manpage_completions.py
unpacking source archive /nix/store/z08mbgrf14gvv13i1hcw8wwjicdgn3k2-fish-3.1.0/share/fish/tools/deroff.py
source root is .
patching sources
applying patch /nix/store/r2bsz0sgmxjsm7jvcpmc0z113wfvfnkj-fish_completion-generator.patch
patching file create_manpage_completions.py
Hunk #1 FAILED at 776.
1 out of 1 hunk FAILED -- saving rejects to file create_manpage_completions.py.rej
builder for '/nix/store/y54wzrnzassarw2p3jv361nqpf1hz5x1-fish_patched-completion-generator.drv' failed with exit code 1
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.4, NixOS, 20.09.git.69efb5cd343 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: master @ 329102c47bd1c68f0acdf4feec64232202948c7a

Maintainer information:
```yaml
module:
- programs.fish
```

**Comment by cole-h** [comment]
Sorry about that. Could you see if #80456 solves your problem (it should, I hope)? I don't have an easy way to test this on NixOS :grimacing:
