### ISSUE TITLE
OfBorg is speedy again

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#80495]
Not sure what the infra team did, but the CI for the past week has been pretty unresponsive, but NO MORE.

Just want to give kudos :)

@grahamc (and others)

Thanks :)

**Comment by FRidh** [comment]
I did make it build a stdenv along with a package a bit higher up a couple of times. Maybe that's a bit too much.

**Comment by jonringer** [comment]
less relevant :)
