### ISSUE TITLE
Python impure pip install: cannot import pycurl

### ISSUE THREAD

**Issue by v0073** [NixOS/nixpkgs#80490]
## Issue description
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other) #9

### Steps to reproduce
sudo pip install --upgrade wfuzz
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                                                       
Processing ./.cache/pip/wheels/d6/38/a9/88b5c4b55f1edc23dfef52ba019d12082ad30dd40fe461af56/wfuzz-2.4.5-cp27-none-any.whl
Requirement already satisfied, skipping upgrade: future in /usr/lib/python2.7/dist-packages (from wfuzz) (0.18.2)
Requirement already satisfied, skipping upgrade: chardet in /usr/lib/python2.7/dist-packages (from wfuzz) (3.0.4)
Collecting pyparsing
  Using cached pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
Requirement already satisfied, skipping upgrade: configparser; python_version < "3.5" in /usr/lib/python2.7/dist-packages (from wfuzz) (3.5.0b2)
Collecting pycurl<=7.43.0.3
  Using cached pycurl-7.43.0.3.tar.gz (215 kB)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-packages (from wfuzz) (1.14.0)
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-XJXgre/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-XJXgre/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-avSu_Y              
       cwd: /tmp/pip-install-XJXgre/pycurl/                                                          
  Complete output (20 lines):                                                                        
  Using curl-config (libcurl 7.67.0)                                                                 
  Using SSL library: OpenSSL/LibreSSL/BoringSSL                                                      
  running bdist_wheel                                                                                
  running build                                                                                      
  running build_py                                                                                   
  creating build                                                                                     
  creating build/lib.linux-x86_64-2.7                                                                
  creating build/lib.linux-x86_64-2.7/curl                                                           
  copying python/curl/__init__.py -> build/lib.linux-x86_64-2.7/curl                                 
  running build_ext                                                                                  
  building 'pycurl' extension                                                                        
  creating build/temp.linux-x86_64-2.7                                                               
  creating build/temp.linux-x86_64-2.7/src                                                           
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-x6KfBw/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYCURL_VERSION="7.43.0.3" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o            
  In file included from src/docstrings.c:4:                                                          
  src/pycurl.h:164:13: fatal error: openssl/ssl.h: No such file or directory                         
    164 | #   include <openssl/ssl.h>                                                                
        |             ^~~~~~~~~~~~~~~                                                                
  compilation terminated.                                                                            
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                    
  ----------------------------------------                                                           
  ERROR: Failed building wheel for pycurl
  Running setup.py clean for pycurl
Failed to build pycurl
Installing collected packages: pyparsing, pycurl, wfuzz
    Running setup.py install for pycurl ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-XJXgre/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-XJXgre/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-DW4YCx/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/pycurl                                                                                            
         cwd: /tmp/pip-install-XJXgre/pycurl/                                                        
    Complete output (20 lines):                                                                      
    Using curl-config (libcurl 7.67.0)                                                               
    Using SSL library: OpenSSL/LibreSSL/BoringSSL                                                    
    running install                                                                                  
    running build                                                                                    
    running build_py                                                                                 
    creating build                                                                                   
    creating build/lib.linux-x86_64-2.7                                                              
    creating build/lib.linux-x86_64-2.7/curl                                                         
    copying python/curl/__init__.py -> build/lib.linux-x86_64-2.7/curl                               
    running build_ext                                                                                
    building 'pycurl' extension                                                                      
    creating build/temp.linux-x86_64-2.7                                                             
    creating build/temp.linux-x86_64-2.7/src                                                         
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-x6KfBw/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYCURL_VERSION="7.43.0.3" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o          
    In file included from src/docstrings.c:4:                                                        
    src/pycurl.h:164:13: fatal error: openssl/ssl.h: No such file or directory                       
      164 | #   include <openssl/ssl.h>                                                              
          |             ^~~~~~~~~~~~~~~                                                              
    compilation terminated.                                                                          
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                  
    ----------------------------------------                                                         
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-XJXgre/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-XJXgre/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-DW4YCx/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/pycurl Check the logs for full command output. 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by FliegendeWurst** [comment]
Hi, most likely it would be enough to add openssl and pkg-config to your environment (e.g. `nix-shell -p openssl pkg-config`).
