### ISSUE TITLE
dnsmasq build failure blocks KDE applications

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#80514]
**Describe the bug**
dnsmasq fails to build, thereby blocking the building of KDE applications

**To Reproduce**
```
$ nix-build -A dnsmasq
```
c65707bc25b252bc7474cb443f4fda1a93a1b12c

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dnsmasq
```

**Comment by clkamp** [comment]
This is due to the kernel update, SIOCGSTAMP is now defined in linux/sockios.h (see also https://bugs.gentoo.org/690788 and http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commitdiff;h=3052ce208acf602f0163166dcefb7330d537cedb )

I will try to prepare a patch for it.

**Comment by FRidh** [comment]
Fixed with https://github.com/NixOS/nixpkgs/commit/482642a733f1254d33b816f51c152fbd269db818.
