### ISSUE TITLE
nixos-14.12 release branch hasn't updated in 12 days

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#8059]
The channel https://github.com/nixos/nixpkgs-channels/tree/nixos-14.12 is at commit 0672315759b3e15e2121365f067c1c8c56bb4722 from May 8th.

**Comment by domenkozar** [comment]
@aszlig chromium is failing: http://hydra.nixos.org/build/22414128

misc tests also fail, it's probably transient: http://hydra.nixos.org/build/22439184

**Comment by aszlig** [comment]
@domenkozar: Thanks, going to throw more OCR at it :see_no_evil:

**Comment by vcunat** [comment]
The channel is on yesterday's commit times now.

**Comment by peti** [comment]
@vcunat, huh? The channel seems to be at bc4f18506cfad0564da1b7958ba3bb0206499233, according to https://github.com/nixos/nixpkgs-channels/tree/nixos-14.12.

**Comment by domenkozar** [comment]
That's the latest commit in 14.12:
https://github.com/NixOS/nixpkgs/commits/release-14.12

**Comment by peti** [comment]
Ah, okay. I was confused because that commit "was authored 24 days ago". Now I see it's the latest. Thanks!

**Comment by vcunat** [comment]
That's because cherry-picking preserves authoring time, but still it gives new commiting time.
