### ISSUE TITLE
Meson does not use compiler from stdenv

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#80598]
This change https://github.com/NixOS/nixpkgs/commit/284f75a258e0f766b8b5d047c486f11c4c4e102d#r32984674 broke meson using compilers from e.g. `clangStdenv` because it tells meson at every build that it should use the compiler that meson itself was built with.

This makes it impossible to switch the compiler, even

```nix
preConfigure = "CC=clang";
```

does not work.

See https://github.com/NixOS/nixpkgs/pull/35666#commitcomment-32984674

I think we must fix that.

CC @shlevy @vcunat

**Comment by worldofpeace** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/58831 ?

**Comment by nh2** [comment]
Yes.
