### ISSUE TITLE
Repackage `geogebra` at version 6.x

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#80593]
`pkgs.geogebra` appears to be maintained at version `5-0-x-0` which is why I occasionally update the package (e.g. in 7bdc103ac8424e08f02f6e9344979d0a821caa62).

However it seems as there's a version 6 available (https://repology.org/project/geogebra/versions). Sooner or later we should probably package a geogebra-6.x. I mainly created this issue as I don't use geogebra actively anymore and don't have the time at the moment to take care of this.

**Comment by LEXUGE** [comment]
Looking forward to the release of 6.x for GeoGebra here as well!

**Comment by Ma27** [comment]
It may take some time until I can work on this, so feel free to work on this if you want to :)

**Comment by voidIess** [comment]
Ive started on figuring it out although geogebra doesn't offer any source for this electron app, right? Asked in their forum but got no replies, so binary patching will be needed here I guess.

https://help.geogebra.org/topic/building-the-geogebra-portable-app

**Comment by voidIess** [comment]
made a pr:#95422
