### ISSUE TITLE
snort-2.9.7.2 cannot be downloaded -> Fails nixos-rebuild

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8065]
I did:

```
sudo nix-channel --update
sudo nixos-rebuild test
```

and it gave me:

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download snort-2.9.7.2.tar.gz from any mirror
builder for ‘/nix/store/sq9jaai089m8p0w1fgpslkkplld37j0i-snort-2.9.7.2.tar.gz.drv’ failed with exit code 1
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download daq-2.0.4.tar.gz from any mirror
builder for ‘/nix/store/rq38fv4p85xlcydhlvnfiqnclxkfx4vn-daq-2.0.4.tar.gz.drv’ failed with exit code 1
```

Whereas the second one was already reported in #7947 and should be fixed since, but unfortunately it still shows up. I'm not sure, though, whether the patch has already appeared in the unstable channel.

The first issue is still the version which is in master, at this moment. `daq` is on `2.0.5` already, which should fix the issue, seems it is not in the channel yet.

**Comment by vcunat** [comment]
The homepage only serves the latest version :-)

**Comment by matthiasbeyer** [comment]
That's why I opened a PR to fix this error.

**Comment by matthiasbeyer** [comment]
Damn, you were faster I guess. Anyways, thanks!

**Comment by matthiasbeyer** [comment]
I'm not happy with your patch. You download from sourceforge, which is not good. I guess [you heard why SF is bad](http://helb.github.io/goodbye-sourceforge/). I'd like to see another solution!

**Comment by vcunat** [comment]
We check the hashes, so I don't really mind using their bandwidth, even if they're bad.
