### ISSUE TITLE
Samba and it's dependencies

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#8067]
Why do we have `ceph`, `openldap`, `cups` etc. enabled by default in `samba4`?
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L8975
That makes a big overhead on desktop systems, where ceph and openldap are not needed in general.
I think it's better to disable them from current `samba4` pkg. And make smth like `samba_full` instead of `samba_light`.
cc @wkennington @rickynils @vcunat @edolstra @oxij @edwtjo

**Comment by wkennington** [comment]
Or we could make something like libsamba and smbclient which give just the
libraries and smbclient binary without any of those dependencies.

**Comment by jagajaga** [comment]
@wkennington good idea!

**Comment by wkennington** [comment]
I'll work on this as soon as I'm done splitting up all of the kerberos / pam / audit stuff.

**Comment by oxij** [comment]
I agree wholeheartedly.

**Comment by jagajaga** [comment]
@wkennington make this ASAP, please. That's a good enchantment for nix and nixos.

**Comment by edolstra** [comment]
I actually fixed this on a local branch (because of some gcc 4.9 issue). I'll push that in a moment.
