### ISSUE TITLE
duplicity fails when using the b2 backend due to unmet dependency

### ISSUE THREAD

**Issue by despresc** [NixOS/nixpkgs#80684]
**Describe the bug**
 Attempting to use the `b2` backend of `duplicity` now results in the error:
```
BackendException: B2 backend requires B2 Python SDK (pip install b2sdk)
```

I assume this is related to the recent merge of  #76988. This seems to require #78116?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.20, NixOS, 20.09pre213994.e2b4abe3c8f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre213994.e2b4abe3c8f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by sumnerevans** [comment]
I'm seeing this on the `https://nixos.org/channels/nixos-19.09` channel as well.

**Comment by despresc** [comment]
This ought to be resolved by https://github.com/NixOS/nixpkgs/pull/95714.
