### ISSUE TITLE
nixos-rebuild causes (Curl error 60) in download-from-binary-cache.pl

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#8070]
I'm assuming that the issue lies with d6cbb061e3bb5d2a93196a4543cfbd7c2359bd84. The certificate for the hydra I'm using is valid, so this is certainly not a problem.

Might it be that omitting `/etc` from the path is the culprit?

cc @wkennington

**Comment by devhell** [comment]
Additionally, mutt isn't having a good time with this either when trying to connect.

**Comment by vcunat** [comment]
I don't think that is the cause, as ``fetchurl`` uses curl with ``--insecure``, so no I assume no certificates are needed at all.
