### ISSUE TITLE
vscodium not working with xmonad?

### ISSUE THREAD

**Issue by zeta-00** [NixOS/nixpkgs#80749]
## Issue description

Using Nix I installed vscodium using these instructions: https://nixos.wiki/wiki/VSCodium , and it is not working with xmonad without a desktop environment, maybe xmonad is missing some functionality?

### Steps to reproduce

the maintainers of vscodium tell me that this is a nix related issue and sent me here, so here's the link: https://github.com/VSCodium/vscodium/issues/341

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by Kazimazi** [comment]
It works well with bspwm. Have you tried with other wm?

**Comment by zeta-00** [comment]
Hello @Kazimazi ,
No I haven't tried another wm, I am trying to figure why vscodium is not working with xmonad, maybe there is some nix setting that I need to set? at this point I have no idea?

**Comment by eadwu** [comment]
There's no detail whatsoever to even begin debugging this. VSCodium works fine on XMonad.

**Comment by zeta-00** [comment]
hello @eadwu ,
It's good to know that vscodium does work on xmonad, but for me it is not working. Here is the error that vscodium is throwing when I try to open it: https://hastebin.com/omubabiqab.rb

**Comment by zeta-00** [comment]
@eadwu 
also, i am using xmonad by itself without any desktop environment, so maybe xmonad needs some extra functionality for vscodium to work?

**Comment by eadwu** [comment]
I'm using xmonad alone as well, does `mkdir` work fine on your system?

**Comment by zeta-00** [comment]
@eadwu 
yes, mkdir is working fine on my system, searching my error on the internet does not bring up show anything similar to my issue, so i am not sure how to troubleshoot this?

**Comment by eadwu** [comment]
Try `--verbose --log trace`

**Comment by zeta-00** [comment]
@eadwu 
ok, i did that but it threw the same error:
[zeta@nixos:/~]$ codium --verbose --log trace
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
[5374:0221/191851.563880:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2020-02-22T02:18:51.611Z] Error: ENOENT: no such file or directory, mkdir
[main 2020-02-22T02:18:51.613Z] Lifecycle#kill()

[zeta@nixos:/~]$

**Comment by eadwu** [comment]
Output of `nix-shell -p nix-info --run "nix-info -m"`?

**Comment by zeta-00** [comment]
@eadwu 

[zeta@nixos:/~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.19, NixOS, 19.09.2079.8731aaaf8b3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2079.8731aaaf8b3, nixos-unstable-20.03pre211190.a21c2fa3ea2"`
 - channels(zeta): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


[zeta@nixos:/~]$

**Comment by eadwu** [comment]
I can't seem to reproduce on any of the channels you are on, did `vscodium` work before if you used it? Have you tried rebuilding it `nix-build "<nixpkgs>" -A vscodium --check` and seeing if the outputs match or building from another channel?

Here's a command to build from master for example `nix-build -I nixpkgs=https://api.github.com/repos/NixOS/nixpkgs/tarball/master "<nixpkgs>" -A vscodium`

**Comment by zeta-00** [comment]
@eadwu 
running: nix-build "<nixpkgs>" -A vscodium --check, threw this error:
searching for dependencies of /nix/store/djsy1j7d9b58543853wywaizia9qz0j4-vscodium-1.41.0/lib/vscode/libEGL.so
derivation '/nix/store/xi8pmp59yjh3s57dnkqykka5imz6nvng-vscodium-1.41.0.drv' may not be deterministic: output '/nix/store/djsy1j7d9b58543853wywaizia9qz0j4-vscodium-1.41.0' differs
error: build of '/nix/store/xi8pmp59yjh3s57dnkqykka5imz6nvng-vscodium-1.41.0.drv' failed


i didn't past the whole output because it's too long

**Comment by zeta-00** [comment]
i'll try: nix-build -I nixpkgs=https://api.github.com/repos/NixOS/nixpkgs/tarball/master "<nixpkgs>" -A vscodium , now

**Comment by zeta-00** [comment]
@eadwu 
i installed vscodium using these instructions so i don't know why the errors started getting thrown, i am thinking maybe it has to do with my home.nix configuration, i have no idea?
https://nixos.wiki/wiki/VSCodium

**Comment by zeta-00** [comment]
@eadwu 
at this point i have no idea, i'll go ask the people in the #nixos channel to see if they can help

**Comment by eadwu** [comment]
Did you try the executable from `nix-build -I nixpkgs=https://api.github.com/repos/NixOS/nixpkgs/tarball/master "<nixpkgs>" -A vscodium`?

**Comment by zeta-00** [comment]
@eadwu @Kazimazi : ok, I was finally able to get vscodium working with xmonad in home-manager(home.nix), it was a mistake on my end(typos and misplacementsof nix code), thanks for the help, and i'll close this issue now.
