### ISSUE TITLE
openafs build broken

### ISSUE THREAD

**Issue by Chattered** [NixOS/nixpkgs#8083]
There's an unclosed `"` in the preconfigure phase: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/openafs-client/default.nix#L38, which causes this to fail.

I still can't get it to build, due, I believe (though I cannot find the mailing list post to confirm this) that this is due to a buggy version of openafs. Version 1.6.11 with kernel 4.0 works fine for me, however.

**Comment by pSub** [comment]
After fixing the unclosed quote it fails for me in configure phase with 

```
configure: error: Couldn't guess your Linux version 2
```

**Comment by domenkozar** [comment]
works now
