### ISSUE TITLE
Long startup and shutdown on 20.03 BETA

### ISSUE THREAD

**Issue by dayflip** [NixOS/nixpkgs#80871]
**Describe the bug**
Very slow boot. And hang on shutdown. something about waiting for rngd

**To Reproduce**
Change channel to 20.03 BETA
update channel: nix-channel --update
nixos-rebuild switch --upgrade
boot.kernelPackages = pkgs.linuxPackages_latest;

**Expected behavior**
Be able to boot in under 30sec. And shutdown without hangs.

**Screenshots**
![sss](https://user-images.githubusercontent.com/16393032/75105589-83be4780-55d2-11ea-8c90-5b0275912428.png)
![sssb](https://user-images.githubusercontent.com/16393032/75105592-891b9200-55d2-11ea-8272-154e9e5cfb76.png)

**Additional context**
After login from sddm. I'm still waiting for gui to start. login to awesome window manager.
All my partition are on nvme m.2 ssd. 
I was not having this issue on 19.09. With the same setup.
One other thing I notice. I can only used reboot and shutdown now in root. was not the case in 19.09.

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.03beta216.d31e383c44e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta216.d31e383c44e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Elyhaka** [comment]
I reproduce the boot time issue on `20.03` too. 

On a `19.09` I have the following output for `rngd` (reversed journalctl output) :

```
-- Reboot --
févr. 22 23:08:33 ely-lenovo rngd[660]: [jitter]: Closing thread 3
févr. 22 23:08:33 ely-lenovo rngd[660]: [jitter]: Closing thread 2
févr. 22 23:08:33 ely-lenovo rngd[660]: [jitter]: Closing thread 1
févr. 22 23:08:33 ely-lenovo rngd[660]: [jitter]: Closing thread 0
févr. 22 23:08:33 ely-lenovo rngd[660]: [jitter]: Shutting down
févr. 22 23:08:33 ely-lenovo rngd[660]: [rdrand]: Shutting down
févr. 22 23:08:33 ely-lenovo rngd[660]: [hwrng ]: Shutting down
févr. 22 12:32:49 ely-lenovo rngd[660]: [pkcs11]: Initialization Failed
févr. 22 12:32:49 ely-lenovo rngd[660]: [pkcs11]: No pkcs11 slots available
févr. 22 12:32:49 ely-lenovo rngd[660]: [jitter]: Initialized
févr. 22 12:32:49 ely-lenovo rngd[660]: [jitter]: Enabling JITTER rng support
févr. 22 12:32:49 ely-lenovo rngd[660]: [jitter]: Unable to obtain AES key, disabling AES in JITTER source
févr. 22 12:32:49 ely-lenovo rngd[660]: [jitter]: Initializing AES buffer
févr. 22 12:32:49 ely-lenovo rngd[660]: [rdrand]: Initialized
févr. 22 12:32:49 ely-lenovo rngd[660]: [rdrand]: Enabling RDSEED rng support
févr. 22 12:32:49 ely-lenovo rngd[660]: [hwrng ]: Initialized
févr. 22 12:32:49 ely-lenovo rngd[660]: Initializing available sources
févr. 22 12:32:49 ely-lenovo systemd[1]: Started Hardware RNG Entropy Gatherer Daemon.
```

On `20.03` I have the following output (also reversed journalctl log) :

```
-- Reboot --
févr. 23 00:02:53 ely-lenovo rngd[665]: [pkcs11]: Initialization Failed
févr. 23 00:02:53 ely-lenovo rngd[665]: [pkcs11]: No pkcs11 slots available
févr. 23 00:02:53 ely-lenovo rngd[665]: [jitter]: Initialized
févr. 23 00:02:53 ely-lenovo rngd[665]: [jitter]: Enabling JITTER rng support
févr. 23 00:02:53 ely-lenovo rngd[665]: [jitter]: Unable to obtain AES key, disabling AES in JITTER source
févr. 23 00:02:53 ely-lenovo rngd[665]: [jitter]: Initializing AES buffer
févr. 23 00:02:53 ely-lenovo rngd[665]: [rdrand]: Initialized
févr. 23 00:02:53 ely-lenovo rngd[665]: [rdrand]: Enabling RDSEED rng support
févr. 23 00:02:53 ely-lenovo rngd[665]: [hwrng ]: Initialized
févr. 23 00:02:53 ely-lenovo rngd[665]: Initializing available sources
févr. 23 00:02:53 ely-lenovo systemd[1]: Started Hardware RNG Entropy Gatherer Daemon.
```

I have the feeling that the `rngd` daemon is not behaving properly and is causing bootup/shutdowns to be stuck while waiting it.

**Comment by ikervagyok** [comment]
I haven't seen any boot time increase, but shutdown seems to be waiting about 20 seconds for `rngd` on my laptop.

**Comment by worldofpeace** [comment]
Only most recent change to rngd service https://github.com/NixOS/nixpkgs/pull/79833.
Perhaps try reverting it and see if there's a difference (in a controllable environment)

**Comment by worldofpeace** [comment]
Yeah, if I revert https://github.com/NixOS/nixpkgs/pull/79833, shutdown doesn't have a `waiting for process to stop: rngd`.

Startup doesn't have an issue on my machine.

**Comment by worldofpeace** [comment]
The only change seems to be `unitConfig.DefaultDependencies = false;` for my config at least?

**Comment by samueldr** [comment]
@dayflip one of the changes with 20.03 is the default kernel changed from 4.19 (previous LTS) to 5.5 (current LTS).

As far as "slow boot" is concerned, If there is a kernel-side regression that is causing issues on your hardware, switching to 4.19 would help figuring out where the issue may lie.

```
boot.kernelPackages = pkgs.linuxPackages_4_19;
```

That is, assuming you weren't already using Linux 5.5 on NixOS 19.09.

**Comment by tokudan** [comment]
To figure out what's the problem on boot, I suggest:
`$ systemd-analyze plot > boot.svg`
That allows you to figure out exactly what's starting when and why it waited.

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/80920 Did it for me, at least for shutdown.

**Comment by dayflip** [comment]
@tokudan i had to convert it to png. to post it here.
From what I can tell. Half sec for display-manager.service and then 8 sec to user-175.slice to load. Then nscd.service took 21 sec. After that. 38.5 sec user-1000.slice. And dev-fuse.device took 19.5 sec.
![boots](https://user-images.githubusercontent.com/16393032/75125091-8f604b80-5670-11ea-93bb-b69341ae2cb2.png)

Don't think this is giving me the full picture. What other stuff can help pin point the long startup?

**Comment by lheckemann** [comment]
The graph looks like the slow startup isn't related to rngd, instead being caused by #60900?

**Comment by tokudan** [comment]
> From what I can tell. Half sec for display-manager.service and then 8 sec to user-175.slice to load. Then nscd.service took 21 sec. After that. 38.5 sec user-1000.slice. And dev-fuse.device took 19.5 sec.
dhcpcd took 9.8 seconds, then nscd started within 7ms.
Then there's a long delay until the user with uid 1000 logs in and another long wait until fuse becomes active, which I believe is probably the actual issue.
Can you try to mount your dav mountpoint through startup scripts of your user instead of systemd?
At the far end you can see network-interfaces.target is very late and marks the point when all network interfaces are online. Which probably means that your dependencies on the network may slow down the whole boot of the system.
My suggestion would be to try and disable your network mounts (webdav, etc) during boot and see if that changes anything.

**Comment by dayflip** [comment]
Will switching around display manager. I had one thing pop up. With lightdm and gdm. 
`A start job is running for /sys/subsystem/net/devices/wlp8s0 ( Xmin Xs / 1min 30s)`
But this does not pop up with sddm. Witch is odd.
I have not touch this part. Since configuration.nix was made. I mostly only used weird. But still keep wireless stuff for bluetooth.
>networking.useDHCP = false;
networking.interfaces.enp10s0.useDHCP = true;
networking.interfaces.wlp8s0.useDHCP = true;

And I have iwd enable. `networking.wireless.iwd.enable = true;`

**Comment by dayflip** [comment]
So I figure out my issue with boot. It not under 30sec. 
>Startup finished in 14.828s (firmware) + 4.153s (loader) + 5.459s (kernel) + 2.913s (userspace) = 27.353s 
graphical.target reached after 2.910s in userspace

Change I made so far. 
>networking.useDHCP = false;
#networking.interfaces.enp10s0.useDHCP = true;
#networking.interfaces.wlp8s0.useDHCP = true;

And added connman for my network + iwd for wifi backend.
But there a new issue.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.03beta-410.67c24f6f8a7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta-410.67c24f6f8a7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Now that a `reboot` or `poweroff`. I only get this: `_`
No other info pop up for me. Just `_`. It does not blinks.
