### ISSUE TITLE
Rust rls 1.41 does not build on Darwin

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#80915]
Attempting to build `rustPackages.rls`, after a fairly long compilation it aborts with:

```
  = note: ld: library not found for -lLLVM-9
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `rls`.
```

Add `llvm_9` as a `buildInput` to the `rls` expression had no effect.

**Comment by jwiegley** [comment]
Strangely, if I build this using `nix-build -A pkgs.rls`, it works, so I'm closing until I have a more accurate representation.

**Comment by jwiegley** [comment]
My mistake, it was only working because of a local change I'd made that effectively boils down to:

```
    overlays = [
      (self: super: {
         rustPackages_1_41_0 = super.rustPackages_1_41_0 // {
           rls = super.rustPackages_1_41_0.rls.overrideAttrs(attrs: {
               buildInputs = attrs.buildInputs ++ [ self.llvm_9 ];
             });
         };
         rustPackages = self.rustPackages_1_41_0;
         rls = self.rustPackages_1_41_0.rls;
       })
    ];
```

**Comment by cole-h** [comment]
Should already be fixed, per my PR: https://github.com/NixOS/nixpkgs/pull/80602. If you switch to a recent `nixos-unstable`, `nixkpgs-unstable`, or `nixos-20.03`, this will have been fixed. If you're still on `nixos-19.09`, you can either run that overlay until you update to 20.03, or get `rls` from one of the previously listed channels.

If any of that is a problem for you, let me know and I'll see about backporting to 19.09 as well.

**Comment by jwiegley** [comment]
Thank you, I've been using rls with 1.41 for a while now, just forgot about this ticket.
