### ISSUE TITLE
Package update: Freenet 1485

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#80964]
https://freenetproject.org/freenet-build-1485-released.html

**Comment by mehlon** [comment]
Freenet has changed from the Ant build system to Gradle since this package was last updated.
http://downloads.freenetproject.org is now a dead link, at least on my system.
This will probably require quite a bit of effort to update.

**Comment by nagy** [comment]
This can be closed, once #200101 is merged.

**Comment by SuperSandro2000** [comment]
Next time please add a fixes to the PR.
