### ISSUE TITLE
seafile-client: fails to launch due to `Could not find the Qt platform plugin "xcb"` in 20.03

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#80976]
**Describe the bug**
The `seafile-applet` binary fails to launch in `20.03beta`. 

Output:
```
$ seafile-applet
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort (core dumped)  seafile-applet
```

**To Reproduce**
1. Add `seafile-client` to `environment.systemPackages`
2. Start `seafile-applet` vis CLI

**Expected behavior**
The Seafile Applet starts without issues.

**Additional context**
This could be related to a missing `wrapQtAppsHook`, however [the expression](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/seafile-client/default.nix) looks like it does include an alternative way of the hook.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.03beta258.68df00b0ba6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta258.68df00b0ba6, nixos-unstable-20.03pre206201.00915dcb631"`
 - channels(wucke13): `"nixos-unstable-20.03pre211190.a21c2fa3ea2, nixpkgs-unstable-19.09pre170896.6e5caa3f8ac, nixos-unstable-small-19.03pre161392.50bb0afa7ce"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
Can you try to see if adding `wrapQtAppsHook` helps?

**Comment by worldofpeace** [comment]
> Can you try to see if adding `wrapQtAppsHook` helps?

Fixing this now.

**Comment by wucke13** [comment]
That's a fast response, thank you both! Just wondering: Why didn't this occur earlier?

**Comment by worldofpeace** [comment]
It was large issue that a lot of qt apps in nixpkgs weren't packaged correctly https://github.com/NixOS/nixpkgs/issues/65399. Hopefully people will read the qt section of the manual now, since it's always been to do https://github.com/worldofpeace/nixpkgs/commit/43bb5bffda01e7a6e7c18d24f755b729b43b957a

**Comment by wucke13** [comment]
@worldofpeace Oh, I'm well aware of the Qt Apps problem in general. What I'm wondering is why I did not run into this issue before 20.03. I'm using seafile since 17.03, and I'm not using a Qt DE that circumvents the problem, so I'm wondering why this problem ocured first in 20.03.

**Comment by worldofpeace** [comment]
Me trying to run it from nixos-unstable results in
```
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (8 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (8 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
Could not initialize GLX
```

That is indeed strange.

**Comment by worldofpeace** [comment]
@wucke13 I figured out the timeline and why you just now experienced this issue https://github.com/NixOS/nixpkgs/pull/80982#issuecomment-591186751.
