### ISSUE TITLE
No llvm_9 nor llvm_10 available via nix-env ?

### ISSUE THREAD

**Issue by jfaure** [NixOS/nixpkgs#81032]
**Project description**
_describe the project a little_

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by veprbl** [comment]
```
nix-env -iA llvm_9 -f channel:nixpkgs-unstable
unpacking 'https://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz'...
installing 'llvm-9.0.1'
```
`llvm_10` should be available after f111c6f9cebacc0201f59c25d6be0683014a3935 lands on the channel

**Comment by vcunat** [comment]
Maybe latest stable release was meant (19.09) and there's no 9 so far.  I can't see anything preventing a backport of new packages (and it's probably easy).

**Comment by xfix** [comment]
Closing as 19.09 is no longer supported.
