### ISSUE TITLE
ACME module does not request certificate afte rebuild

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#81069]
**Describe the bug**

I have configured the new ACME module (from 20.03) and after a rebuild nothing happened. I expected to have a certificate or a (failed) certificate request, but neither of these happened.

Apparently I have to wait four days until my certificates would automatically appear, that is a bit long.
```
NEXT                         LEFT        LAST                         PASSED  UNIT                            ACTIVATES
Wed 2020-02-26 01:01:55 CET  16min left  Tue 2020-02-25 01:01:55 CET  23h ago systemd-tmpfiles-clean.timer    systemd-tmpfiles-clean.service
Mon 2020-03-02 00:39:57 CET  4 days left n/a                          n/a     acme-hermes.lossy.network.timer acme-hermes.lossy.network.service
```

**To Reproduce**
1. Configure a certificate through security.acme
2. Rebuild
3. The certificate request doesn't happen before the systemd-timer is due

**Expected behavior**
I should have a certificate as soon as possible.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.09.git.e661d071f50 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre214664.d363be93b49, nixos-hardware, nixos-unstable-20.09pre214664.d363be93b49"`
 - channels(hexa): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:

@m1cr0man

**Comment by aanderse** [comment]
@mweinelt presumably you have a service which requires this certificate. You should make that service require your certificate service. Both `nginx` and `httpd` services do this with their `enableACME` options and could demonstrate for you how to do this. If any part of what I said isn't clear, or any part of the code please do not hesitate to ask for details.

**Comment by mweinelt** [comment]
Got it, I can make that work. But is that really the intended behaviour?

**Comment by aanderse** [comment]
Would you want each certificate to renew each and every time you rebuilt your system? That sounds like much more of a problem.

You could always manually execute the certificate service any time you want, but the intention is that you utilize systemd and make services depend on other services. Why provision a certificate unless you need it. If you need it, declare it so and it will be provisioned.

**Comment by Infinisil** [comment]
@aanderse It wouldn't renew on every rebuild: Starting the renew service doesn't do anything if no renew is needed.

I think having the certificate be created when a rebuild is done sounds reasonable. I think it might simply be a matter of adding `wantedBy = [ "multi-user.target" ]` to the acme services.

**Comment by mweinelt** [comment]
That and also making sure on boot that the certificate is in order is also a good practice.

**Comment by aanderse** [comment]
@Infinisil thanks for clarifying that. I think I was mistaking the `simp_le` implementation which did attempt to renew every time it was called, if I recall correctly :thinking:
