### ISSUE TITLE
Discord: package is out of date

### ISSUE THREAD

**Issue by btlvr** [NixOS/nixpkgs#81072]
## Issue description
Discord is now forcing me to update the app, leaving me unable to use it

### Steps to reproduce
Run Discord

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.88, NixOS, 19.09.1548.3a1861fcabc (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
it has already been updated 
master: #81044
20.03: #81052
19.09: #81053 

You'll have to build it off of git, or wait for a channel release to get it
