### ISSUE TITLE
Anydesk 5.2.2 fails to start

### ISSUE THREAD

**Issue by JeffLabonte** [NixOS/nixpkgs#81074]
**Describe the bug**
Anydesk simply crash on init

**To Reproduce**
1. Install anydesk.

**Expected behavior**
A window should appear and the icon in the notification area should be presnet

**Screenshots**
![image](https://user-images.githubusercontent.com/9425955/75300760-e730bb00-5806-11ea-8457-a1c3a62487cc.png)

**Metadata**
![image](https://user-images.githubusercontent.com/9425955/75300844-2101c180-5807-11ea-9392-34cdd137585e.png)

**Comment by jonringer** [comment]
can you do `anydesk --version`

I'm not even able to build anydesk to on 19.09. But i was able to run it fine on master

**Comment by JeffLabonte** [comment]
Yes sure!

```bash
5.5.2
```

**Comment by JeffLabonte** [comment]
It prompt me this `double free or corruption (fasttop) ` also!

I couldn't make the version from 19.09 build as well!

**Comment by jonringer** [comment]
interesting, 5.5.2 ran fine.

can you do `strace anydesk`

**Comment by JeffLabonte** [comment]
[anydesk_strace.log](https://github.com/NixOS/nixpkgs/files/4253261/anydesk_strace.log)

**Comment by jonringer** [comment]
do you run NixOS?

**Comment by jonringer** [comment]
only thing I could think of is that I have `hardware.opengl.driSupport32Bit = true;` in my configuration.nix. Which will expose `/run/opengl-driver-32`

do you mind doing `ls /run` ?

**Comment by jonringer** [comment]
```
$ ls -l /run/
...
lrwxrwxrwx   58 root    25 Feb 15:53 opengl-driver -> /nix/store/lwykaxahvjgbfw14pxkif7hzgyij1jyj-opengl-drivers
lrwxrwxrwx   64 root    25 Feb 15:53 opengl-driver-32 -> /nix/store/ypvzi2pkmw8khkl37jih01fzshyixmr3-opengl-drivers-32bit
```

**Comment by JeffLabonte** [comment]
```
total 28
-rw-r--r--  1 root    root       5 Feb 25 10:22 acpid.pid
srw-rw-rw-  1 root    root       0 Feb 25 10:22 acpid.socket
-rw-------  1 root    root       0 Feb 25 10:23 agetty.reload
drwxr-xr-x  2 root    root      40 Feb 25 10:22 binfmt
lrwxrwxrwx  1 root    root      92 Feb 25 10:22 booted-system -> /nix/store/g15bgzmqmxvnc7h40sx1p95ya5irm9mn-nixos-system-tuxbox-xps15-19.09.2155.57a4956bc25
-rw-r--r--  1 root    root       4 Feb 25 10:22 bumblebeed.pid
srw-rw----  1 root    wheel      0 Feb 25 10:22 bumblebee.socket
drwxr-xr-x  2 root    root      40 Feb 25 10:23 cryptsetup
drwxr-xr-x  2 root    root      60 Feb 25 10:22 cups
lrwxrwxrwx  1 root    root      92 Feb 25 21:54 current-system -> /nix/store/5d9qzvscsv0j711klnwc19c4fjyk3835-nixos-system-tuxbox-xps15-19.09.2155.57a4956bc25
drwxr-xr-x  2 root    root      60 Feb 25 10:22 dbus
-rw-r--r--  1 root    root       5 Feb 25 19:46 dhclient-wlp2s0.pid
drwx------  8 root    root     180 Feb 25 13:34 docker
-rw-r--r--  1 root    root       4 Feb 25 10:23 docker.pid
srw-rw----  1 root    docker     0 Feb 25 10:22 docker.sock
prw-------  1 root    root       0 Feb 25 10:22 initctl
drwxr-x---  2 root    root       0 Feb 25 10:22 keys
drwx--x--x  3 lightdm lightdm   60 Feb 25 15:37 lightdm
-rw-r--r--  1 root    root       5 Feb 25 19:46 lightdm.pid
drwxr-xr-x  2 root    root      60 Feb 25 10:22 lock
drwxr-xr-x  2 root    root      40 Feb 25 10:22 log
drwxr-xr-x  2 root    root      40 Feb 25 10:22 mount
drwxr-xr-x  4 root    root     140 Feb 25 19:46 NetworkManager
drwxr-xr-x  3 root    root      60 Feb 25 10:22 nixos
drwxr-xr-x  2 nscd    nscd      80 Feb 25 19:46 nscd
lrwxrwxrwx  1 root    root      58 Feb 25 10:22 opengl-driver -> /nix/store/v1vk4j1nbv32913jkvrr6khsz9xa099c-opengl-drivers
drwxr-xr-x  4 root    root      80 Feb 25 19:46 resolvconf
-rw-r--r--  1 root    root       5 Feb 25 10:22 sshd.pid
drwx--x--x  3 root    root      60 Feb 25 10:24 sudo
drwxr-xr-x 21 root    root     520 Feb 25 21:54 systemd
drwxr-xr-x  2 root    root      60 Feb 25 10:22 thermald
drwxr-xr-x  2 root    root      80 Feb 25 20:20 tlp
drwxr-xr-x  2 root    root      60 Feb 25 10:22 tmpfiles.d
drwxr-xr-x  8 root    root     180 Feb 25 22:39 udev
drwx------  2 root    root      40 Feb 25 10:23 udisks2
drwxr-xr-x  3 root    root      60 Feb 25 19:46 user
-rw-rw-r--  1 root    utmp    1152 Feb 25 19:46 utmp
drwxrwxrwt  3 root    root      80 Feb 25 21:54 wrappers
-rw-------  1 root    root       0 Feb 25 10:23 xtables.lock
```

That might be it. Let me try that out!

**Comment by JeffLabonte** [comment]
> do you run NixOS?

Yup

![image](https://user-images.githubusercontent.com/9425955/75309748-f2dcab80-581f-11ea-9ac5-c8e2c06598c3.png)

**Comment by jonringer** [comment]
do you mind adding `hardware.opengl.driSupport32Bit = true;`, doing a `sudo nixos-rebuild switch`, verifying that `/run/opengl-driver-32` is present and trying again?

**Comment by JeffLabonte** [comment]
I added the configuration and rebooted my computer just to make sure. Still doesn't work. This is strange.

https://pastebin.com/guFMQsJM -- result of ls /run/opengl-driver-32

[anydesk_strace.log](https://github.com/NixOS/nixpkgs/files/4253343/anydesk_strace.log)

**Comment by jonringer** [comment]
the output seems to complain about `gtkGL...`, sorry I'm not sure how to fix

**Comment by JeffLabonte** [comment]
I have found the issue. It was related to my video driver configurations. I have an intel and a nvidia GPU on my laptop. Removing the nvidia driver from my list of drivers fixed the issue!

**Comment by jonringer** [comment]
oh yea, nvidia doesn't play well with other drivers xD
