### ISSUE TITLE
Default consoleFont don't show UTF-8 characters

### ISSUE THREAD

**Issue by EPashkin** [NixOS/nixpkgs#8107]
On new installation of nixos, i18n.defaultFont defaults to lat9w-16
but it seems don't support UTF-8
so this command shows ? near nixos-help instead of ‘ and ’
```
less /etc/nixos/configuration.nix
```
Same for result for nixos-rebuild and others.

How to fix it?

**Comment by vcunat** [comment]
I think distros often use Terminus. I've got ``consoleFont = "Lat2-Terminus16";`` for years, and it shows those characters fine.

What about making it the default? Any opinions? No additional packages are needed &ndash; it's included with the basic set.

**Comment by EPashkin** [comment]
Thank you for the font.
Good, it's a fonts problem, not console itself.

**Comment by grahamc** [comment]
@vcunat how would you feel about changing to `latarcyrheb-sun32`? Does this font support the necessary characters? It is much larger, which is very helpful for users on modern laptops.

**Comment by vcunat** [comment]
@grahamc: hmm, yes, probably, until we have some auto-detection (during install?).  On my ~96 DPI screen it's huge, but not unusable.
