### ISSUE TITLE
nixpkgs-unstable release channel 2-4 days out-of-sync from hydra

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#81081]
According to hydra, "trunk" has been building regularly: https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents

However, according to https://howoldis.herokuapp.com/ it's 2 days old.

And this is verified by going to https://nixos.org/channels/nixpkgs-unstable which redirects to https://releases.nixos.org/nixpkgs/nixpkgs-20.09pre214374.1fe82110feb at the time of writing.

But if we go to the read-only channel repo: https://github.com/NixOS/nixpkgs-channels/tree/nixpkgs-unstable it says it's 4 days old

**Comment by jonringer** [comment]
While researching for this issue, I noticed that trunk on hydra was held up by `chromium.aarch64` https://hydra.nixos.org/eval/1572374 , specifically https://hydra.nixos.org/build/113412855

I think it might be worth while to have a discussion about packages which take obscene amounts of time to compile (most likely to be aarch64 jobs). The https://hydra.nixos.org/build/113412855 job is currently referenced in 15 evaluations, which means that it's taking roughly 60 hours since it was first evaluated.

**Comment by jonringer** [comment]
cc @grahamc @FRidh @worldofpeace

**Comment by thefloweringash** [comment]
Related https://github.com/NixOS/nixpkgs/pull/78347

**Comment by jonringer** [comment]
closing, issue seems to be related to either aarch or darwin taking a long time to munch through a package set
