### ISSUE TITLE
Audio doesn't work properly

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#81097]
**Describe the bug**

Only about two of the total of my six laptop speakers work, so the audio sounds really tinny. The audio quality feels at about 25% of what it sounds like on windows. 

**To Reproduce**
1. Have a Lenovo C-930 Yoga laptop.
2. Notice that the sound quality is awful.
3. Lament the sound quality. 

**Expected behavior**

It'd be nice if the sound quality were better, and all the speakers worked. 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.21, NixOS, 20.09pre214537.39892985b00 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(jon): `"home-manager, home-manager-sway, nixpkgs-20.09pre214168.686274ea62c"`
 - channels(root): `"nixos-20.09pre214537.39892985b00"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

For what it's worth, here's the alsa info dump: http://alsa-project.org/db/?f=87931920f5a8cbfcaa9a2490b88d8c1ed6337e9f

**Comment by JonathanReeve** [comment]
This is still valid, but I guess probably not best fixed in nixpkgs, but somewhere further upstream.

**Comment by makoConstruct** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/51037
