### ISSUE TITLE
lightdm webkit greeter package request

### ISSUE THREAD

**Issue by nothingelsematters** [NixOS/nixpkgs#81133]
**Project description**
brand fashionable greeter for lightdm display manager

**Metadata**

* homepage URL: https://github.com/Antergos/web-greeter
* source URL: https://github.com/Antergos/web-greeter
* license: GPL-3.0
* platforms: linux

**Comment by worldofpeace** [comment]
That is a dead project though. We don't package archived software if possible.

**Comment by MetaDark** [comment]
I have it available in my NUR repo if you want to use it, but I don't think this will ever make it into nixpkgs unless someone decides to maintain a fork.

```nix
{ config, pkgs, ... }:

let
  nur = import (builtins.fetchTarball {
    url = "https://github.com/nix-community/NUR/archive/02b1fdc4d33180d0f9cf03e7249353b75236a59e.tar.gz";
    sha256 = "04g9c78wjgqcj7h0gzlbdghkzc2mzq3iyl2p9ljzn5jjmi94yf67";
  }) {
    inherit pkgs;
  };
in {
  imports = [
    nur.repos.metadark.modules.lightdm-webkit2-greeter
  ];

  services.xserver.displayManager.lightdm = {
    enable = true;
    greeters.webkit2 = {
      enable = true;
      webkitTheme = fetchTarball {
        url = "https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases/download/v3.0.0/lightdm-webkit-theme-litarvan-3.0.0.tar.gz";
        sha256 = "0q0r040vxg1nl51wb3z3r0pl7ymhyhp1lbn2ggg7v3pa563m4rrv";
      };
    };
  };
}
```

**Comment by shadowninja55** [comment]
> I have it available in my [NUR repo](https://github.com/MetaDark/nur-packages/blob/master/pkgs/applications/display-managers/lightdm-webkit2-greeter/default.nix) if you want to use it, but I don't think this will ever make it into nixpkgs unless someone decides to maintain a fork.
> 
> ```nix
> { config, pkgs, ... }:
> 
> let
>   nur = import (fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {};
> in {
>   imports = [
>     nur.repos.metadark.modules.lightdm-webkit2-greeter
>   ];
> 
>   services.xserver.displayManager.lightdm = {
>     enable = true;
>     greeters.webkit2 = {
>       enable = true;
>       webkitTheme = fetchTarball {
>         url = "https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases/download/v3.0.0/lightdm-webkit-theme-litarvan-3.0.0.tar.gz";
>         sha256 = "0q0r040vxg1nl51wb3z3r0pl7ymhyhp1lbn2ggg7v3pa563m4rrv";
>       };
>     };
>   };
> }
> ```

do you have a method of contact like email, discord, irc, etc? i believe there's a bug (lightdm reports no users, tested on default, fallback, and a third party theme) from my testing that i'd like to work on patching.

**Comment by Vertecedoc4545** [comment]
@shadowninja55  heyy actually that doesn't works; there isn't an repo.metadark option on the fetched tarball

**Comment by shadowninja55** [comment]
> @shadowninja55 heyy actually that doesn't works; there isn't an repo.metadark option on the fetched tarball

their repo changed to `kira-bruneau`, that one works for me, though it has some bugs.
