### ISSUE TITLE
fontconfig: font names fonts instead of strings

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#8114]
When I add something like:

```
fonts.fontconfig.defaultFonts.monospace = [ "Source Code Pro" ];
```

I have to manually make sure `pkgs.source-code-pro` is available.

How about adjusting it to make

```
….monospace = [ pkgs.source-code-pro ]
```

(or similar) possible? This can then automatically fetch the dependencies.

**Comment by edolstra** [comment]
How would it know which font to use, given that a package can contain multiple fonts?

**Comment by vcunat** [comment]
They typically do contain at least multiple versions of the font (regular, bold, mono, etc.).

**Comment by vcunat** [comment]
What might be done is some kind of validation during the build to check the string resolves to a valid available font.

**Comment by copumpkin** [comment]
Font derivations could have checked attribute hierarchies, perhaps? Something like:

```nix
mkFontDerivation {
  name = "foo-1.2";
  fonts = {
    baskerville: [ "light", "bold", "boldlikewhoa" ];
    garamond-premier-pro: [ "poor" ];
  };
}
```

And the derivation builder would:
1. Ensure that those fonts are actually in the output
2. Ensure that they're valid
3. Create attributes on the output that match the implied hierarchy

Might be overcomplicating things, but doesn't seem too hard at first glance.

**Comment by Profpatsch** [comment]
I thought some kind of font type maybe. Like @copumpkin said, with `mkFontDerivation`.

Is there a good way to specify new types for modules already? Is that even wanted?

**Comment by ttuegel** [comment]
@Profpatsch If you are still interested in this, the types for NixOS configurations are defined [here](https://github.com/NixOS/nixpkgs/blob/master/lib/types.nix). This ticket isn't high-priority for me right now, but contributions are certainly welcome!
