### ISSUE TITLE
[Packaging request] Phabricator

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#81169]
**Project description**

From https://www.phacility.com/ : "Phabricator is a set of tools for developing software. It includes applications for code review, repository hosting, bug tracking, project management, and more. Phabricator is powerful, fast, scalable, and completely open source."

Installation instructions: https://secure.phabricator.com/book/phabricator/article/installation_guide/

EDIT: As this is a web service, it would be nice to have a corresponding service definition in NixOS.

**Metadata**

* homepage URL: https://secure.phabricator.com/ and https://www.phacility.com/
* source URL: https://github.com/phacility/phabricator.git
* license: Apache 2
* platforms: Linux at least

**Comment by aanderse** [comment]
We used to have a `httpd` submodule I'm pretty sure. `phabricator` is difficult to package in a clean and reproducible way for NixOS, if I recall correctly. Maybe @danbst remembers more than I do, he might even have a gist with an impure NixOS module that could be useful for you.

**Comment by danbst** [comment]
@jluttine @aanderse I'm no longer maintaining Phabricator installation.

From my experience the worst part about Phabricator are:
- absence of "stable" releases, they advocate using `master` branch and update regularly. This makes a maintenance burden for Nix
- they regularly do database migrations, this adds quite a lot of state mgmt, and prohibits rollbacks. Which is bad for Nix as well
- they don't have (or didn't have) conf files

Here's my module - https://gist.github.com/danbst/0580293476b963755e359e0aa7e9eac5

**Comment by jluttine** [comment]
Thanks for the comments and insight! I tested Phabricator in a bit more detail and wasn't actually too impressed by it. So, personally, I don't need to have it packaged after all. If anyone else wants it, this can be reopened.

**Comment by aanderse** [comment]
Thanks for your feedback @danbst!
