### ISSUE TITLE
Fuse doesn't work in appimage runned via appimage-run

### ISSUE THREAD

**Issue by piotr-szegda** [NixOS/nixpkgs#81208]
**Describe the bug**
I'd like to use pCloud on NixOS. There provide appimage client for Linux. Client need fuse library to mount virtual drive. So I add fuse to overlays of appimage-run:

```
appimage-run = super.appimage-run.override {
        extraPkgs = p:
          with p; [
            at-spi2-core
            gsettings-desktop-schemas
            fuse3
            fuse
          ];
      }; 
```
Unfortunately it's not working. App start but don't mount drive. I think this is bug or limitation of appimage-run.

**To Reproduce**
1. Add fuse to overlays of appimage-run.
2. Run app using fuse via appimage-run

**Expected behavior**
Directory should be mounted via FUSE.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.03beta321.be346a1f4bd (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta321.be346a1f4bd"`
 - channels(piotrek): `"home-manager, nixos-20.03pre212208.8130f3c1c2b, nixpkgs-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/home/piotrek/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bignaux** [comment]
It could come from the chrootenv , that both appimageTools.wrapAppImage and appimage-run shared on top of buildFHSUserEnv . If i were you, i'd try to confirm that trying to fusermounting in your setuped fuse chrootenv ... If you confirm that is the issue, you can try to make a native appimage derivation, like example #75392 or #80402  .

**Comment by bignaux** [comment]
Could you provide a direct link for  #82158 ?

**Comment by piotr-szegda** [comment]
@bignaux: Sorry for slow respond but I have been busy. I try to do it but it's a bit hard because there is no simple download link for this client. Thank you for hint.
Question about link is for me? I can do this but I don't see link option.

**Comment by bignaux** [comment]
Oki i found the src.url then i make a quick expression for this interesting use case. btw i've some more priority to fix in appimage right now, if your interesting to be the manager of that later (if my PR is merge). I found the url with "simple mass downloader" firefox addon with export selected item to file.

```
  pcloud = buildAppImage rec {
      pname = "pcloud";
      version = "1.7.2";
      extraPkgs = pkgs: with pkgs; [ at-spi2-core hicolor-icon-theme gsettings-desktop-schemas fuse ]; #fuse3
      profile = ''
        export LC_ALL=C.UTF-8
        export XDG_DATA_DIRS=${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas.name}:${gtk3}/share/gsettings-schemas/${gtk3.name}:$XDG_DATA_DIRS
      '';
      src = fetchurl {
        url = "https://p-par1.pcloud.com/cBZetST9hZtTO10SZZZm2yfa7Z2ZZnm5ZkZVcA5VZAkZJFZL5ZqZlJZ5XZX0Z2JZpFZ6JZ9XZG5Z5kZg5Z1EnhkZB1zEnYecd5SOvvU5sxCGhResxlKX/pcloud";
        sha256 = "37e15e46f3c5fb6958c22c752050f4effc096745afb3c4f6a97a5c98607bfbe6";
      };
      meta.description = "Decentralized Social Sharing Network";
  };
```

**Comment by piotr-szegda** [comment]
Yes, I can help in managing. Unfortunately this link will work only for short time. I tried to implement solution from this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pcloud-drive but it's also not perfect because you can't select fixed version number.

**Comment by piotr-szegda** [comment]
still important to me

**Comment by piotr-szegda** [comment]
still important to me

**Comment by Patryk27** [comment]
Closing, as this [has been already fixed some time ago](https://github.com/NixOS/nixpkgs/pull/91182) (at least for pCloud) 🙂
