### ISSUE TITLE
HomeAssistant fails to start if using dependencies

### ISSUE THREAD

**Issue by denibertovic** [NixOS/nixpkgs#81222]
I've managed to install home assistant but when I tried adding one of the sensors "mitemp_bt" it wouldn't boot
saying that the module mitemp_bt was not found. I tried upgrading to nixos-unstable but now it's refusing to boot because it can't setup the met.weather platform due to missing the metno module.

I tried turning off autoExtraComponents and adding extraComponents manually in the package override but that didn't work either.

```
  services.home-assistant = {
    package = pkgs.home-assistant.override {
      extraPackages = ps: with ps; [ colorlog ];
    };
    enable = true;
    openFirewall = true;
    port = 8123;
    config = {
      homeassistant = {
        name = "foo";
        time_zone = "Europe/Paris";
        latitude = ..;
        longitude = ....;
        elevation = 1;
        unit_system = "metric";
      };
      sensor = [
        { platform = "mitemp_bt";
          mac  = "......";
          monitored_conditions = [ "temperature" "humidity" "battery" ];
        }
      ];
      # I really don't know why this is needed but the interface doesn't work otherwise
      config = {};
      http = {
        server_host = "0.0.0.0";
        server_port = 8123;
      };
      lovelace = { mode = "yaml"; };
      logger = { default = "debug"; };
    };
  };
```

What am I doing wrong?

ping @dotlambda

**Comment by denibertovic** [comment]
Oh...actually it's missing another module: ModuleNotFoundError: No module named 'btlewrap'

**Comment by lheckemann** [comment]
You're not really doing anything wrong — just using a component that nobody has used with nixos before and thus isn't supported (yet :wink:). The dependencies for components need to be specified manually in `pkgs/servers/home-assistant/component-packages.nix` — a PR to do this for mitemp_bt and met would be welcome!

**Comment by denibertovic** [comment]
@lheckemann I did alredy check component-packages.nix and both "met" and "mitemp_bt" are listed there. What am I missing?

**Comment by denibertovic** [comment]
@lheckemann Also, what is bringing is this "met" dependency? I haven't explicitly set it anywhere.

**Comment by lheckemann** [comment]
Yes, all components should be listed there — but the purpose of that file is to specify which python libraries the components require, so you'll need to add the package providing the `btlewrap` module to `mitemp_bt` (potentially adding it to nixpkgs itself if it's not there yet). I think `met` might be enabled by default or something for weather info, not sure.

**Comment by denibertovic** [comment]
@lheckemann I see. So in essence if a component does not have dependencies specified it's just a placeholder. Why is this the case? Wouldn't it be better if the build failed if the component will not work at runtime, thus causing the entire server to not start?

**Comment by denibertovic** [comment]
As for the met component... this is really troublesome since this means that a default install of home-assistant will not work with current nixos-unstable.

**Comment by lheckemann** [comment]
Some components don't need any extra dependencies, so it arguably makes sense to keep them listed so that they work "for free".

Yes, it's a bit unfortunate that the default install doesn't work, particularly how if no config is specified _all_ the default components will fail (since nixos doesn't know which components are enabled by the config auto-generator). I'm unsure how to solve this problem nicely though.

**Comment by dasj19** [comment]
I'll take a look at this when time allows. Also there are quite some changes here: https://github.com/NixOS/nixpkgs/pull/82480/files

**Comment by mweinelt** [comment]
This seems to be due to a missing dependency for the `mitemp_bt` component. It can be seen here:

https://github.com/NixOS/nixpkgs/blob/c9e5c08eae4c0783c3ee04bf6eae20a9e9120315/pkgs/servers/home-assistant/component-packages.nix#L517

If you are still interested, please do tell, so we might get that dependency packaged. Otherwise this is not really actionable, but rather a generic observation of how our packaging works.
