### ISSUE TITLE
Flatpaks can't be run/installed without org.freedesktop.Accounts interface

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#81284]
**Describe the bug**
This is a followup bug from user reports on discourse https://discourse.nixos.org/t/flatpak-error-the-name-org-freedesktop-accounts-was-not-provided-by-any-service-file/6000.

Essentially, people cannot run/install a flatpak without `services.accounts-daemon.enable = true;`

**To Reproduce**
1. Enable flatpak but not AccountsService
2. Try to run/install a flatpak
3. Watch it fail with:
```
# running example
error: The name org.freedesktop.Accounts was not provided by any .service files

# installing example
Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
error: Failed to install org.signal.Signal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
```

**Expected behavior**
You can run/install a flatpak without needing AccountsService.
Looking at my comment here https://discourse.nixos.org/t/flatpak-error-the-name-org-freedesktop-accounts-was-not-provided-by-any-service-file/6000/7?u=worldofpeace, it didn't appear it need AccountsService exclusively.

**Additional context**
There was other issues with flatpak, but those will also be solved with https://github.com/NixOS/nixpkgs/pull/80698, which was backported to `staging-20.03`. (it's not in 20.03 yet).

Another thing that's unrelated to this bug, should plasma5 enable AccountsService?
I do see code that matches on that interface https://github.com/search?q=org%3AKDE+org.freedesktop.Accounts&type=Code.

**Workaround**
It's very easy, just enable
```
services.accounts-daemon.enable = true;
```

**Comment by worldofpeace** [comment]
cc @jtojnar @hedning 

If it's true that you actually do need AccountsService for flatpak, we can just enable it in the module.

**Comment by flokli** [comment]
Yeah, we should open a PR that just sets `services.accounts-daemon.enable = mkDefault true;` in the flatpak module.

**Comment by worldofpeace** [comment]
> Yeah, we should open a PR that just sets `services.accounts-daemon.enable = mkDefault true;` in the flatpak module.

I haven't because it doesn't hard depend on AccountsService for getting locales?

**Comment by hedning** [comment]
Hmm, right, looking at the code that calls out to the AccountsService bus: https://github.com/flatpak/flatpak/blob/f3b863a187243aa48745f91a79c5e289753ec468/common/flatpak-dir.c#L14884-L14886
```c
  /* Now add the user account locales from AccountsService. If accounts_proxy is
   * not NULL, it means that AccountsService exists */
  accounts_proxy = get_accounts_dbus_proxy ();
  if (accounts_proxy != NULL)
    get_locale_langs_from_accounts_dbus (accounts_proxy, langs);
  g_ptr_array_add (langs, NULL);
```

So it's quite strange that install wouldn't work. Though note that there's flatpaks that depend on accountsservice which might not handle it gracefully, so I guess it's prudent to add it anyway.

**Comment by shazow** [comment]
Confirmed that I'm no longer having this same issue with `services.accounts-daemon` enabled, though I'm having the SSL issue mentioned in #82422.

**Comment by ilya-fedin** [comment]
With `G_DBUS_DEBUG=call` I observed that it tries to call `org.freedesktop.Accounts.FindUserById()`
Looks like that request is made not by flatpak itself, but by libmalcontent
https://github.com/flatpak/flatpak/search?q=finduserbyid&unscoped_q=finduserbyid
https://github.com/endlessm/malcontent/search?q=finduserbyid&unscoped_q=finduserbyid

**Comment by jtojnar** [comment]
We have removed malcontent from flatpak on master since it has a dependency cycle in the latest version (https://gitlab.freedesktop.org/pwithnall/malcontent/-/merge_requests/38). And now did the same on release-20.03 branch as it is nowhere near usable without any integration: e8701fe486266edc600abb1f7399a48779cab995

**Comment by worldofpeace** [comment]
I believe this issue can now be closed, https://github.com/NixOS/nixpkgs/issues/81284#issuecomment-601245931 states that without libmalcontent we shouldn't be making any calls to accountsservice if you don't have it. The SSL issue is separate.
