### ISSUE TITLE
GHC 7.6.x can't run Haddock on Darwin

### ISSUE THREAD

**Issue by codedmart** [NixOS/nixpkgs#8129]
When trying to install random-1.1 on darwin it fails with
```
haddockPhase
Running Haddock for random-1.1...
Running hscolour for random-1.1...
Preprocessing library random-1.1...
Preprocessing test suite 'TestRandomRs' for random-1.1...
Preprocessing test suite 'TestRandomIOs' for random-1.1...
Preprocessing test suite 'T7936' for random-1.1...
Preprocessing library random-1.1...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0

System/Random.hs:2:2: parse error on input `#'
Haddock coverage:
builder for ‘/nix/store/5k6hmnivpjxpfnn1q220zps5czbban16-haskell-random-1.1.drv’ failed with exit code 1
```
as per @peti putting `doHaddock = false;` to the expression of `random` in pkgs/development/haskell-modules/hackage-packages.nix works as a workaround.

**Comment by peti** [comment]
@copumpkin, @jwiegley, @cstrahan, do you guys know why GHC 7.6.x builds fail like that on Darwin? Apparently, it's not just `random` that has this problem.

**Comment by Fuuzetsu** [comment]
It's probably CPP problems, would not be the first time.

**Comment by peti** [comment]
The generic build has the ability to use cpphs. Would that help?

Also, we have this wrapper script (`pkgs/development/haskell-modules/gcc-clang-wrapper.sh`) that's used to compile ghc itself. Maybe we should be using that stuff during normal builds, too?

**Comment by codedmart** [comment]
Here is the default.nix I am using:
```
let
  pkgs = import <nixpkgs> {};
  stdenv = pkgs.stdenv;
in rec {
  haskellRethinkDB763 = stdenv.mkDerivation rec {
    name = "haskell-rethinkdb-763";
    buildInputs = [
      pkgs.haskell.packages.ghc763.ghc
      pkgs.haskell.packages.ghc763.cabal-install
      pkgs.haskell.packages.ghc763.cabal2nix
    ];
    NIX_MYENV_NAME = "haskellRethinkDB763";
    shellHook =
      "source ~/.bash_prompt"
    ;
  };
}
```
here is a list of packages that were failing:
```
HUnit-1.2.5.2
ansi-terminal-0.6.2.1
extensible-extentions-0.1.1.4
hostname-1.0
random-1.1
stm-2.4.4
zlib-0.5.4.2
```
Things are still compiling so I will update this list if I hit any others. Thanks!

**Comment by Fuuzetsu** [comment]
It could help, maybe. There was a problem with 7.8 (see https://github.com/haskell/cabal/issues/1740) and cpphs was suggested so maybe we can do that here too though ultimately the fix went into cabal. But it might not even be that so I don't know, someone with OSX should do some testing.

**Comment by codedmart** [comment]
I am happy to test anything that I can since I use OSX. I am still pretty new to nix so I might need some direction on how/what to test.

**Comment by peti** [comment]
@codedmart, try replacing the line https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix#L45 with `useCpphs ? true` in your local Nixpkgs repository. That should force use of `cpphs` instead of the native `cpp` implementation. Does that make a difference?

If that doesn't help, then you can also add the following snippet to your `~/.nixpkgs/config.nix` file:

~~~~~ nix
{
  packageOverrides = super: let self = super.pkgs; in
  {
    myHaskellPackages = self.haskell.packages.ghc763.override {
      overrides = self: super: {
        mkDerivation = args: super.mkDerivation (args // { doHaddock = false; });
      };
    };
  };
}
~~~~~

Then run `nix-env -f "<nixpkgs>" -iA myHaskellPackages.cabal-install` to install from that package set, which has the Haddock phase disabled globally.

**Comment by codedmart** [comment]
@peti Should I uninstall the packages that caused that problem first and remove the `doHaddock = false;` from the expressions in pkgs/development/haskell-modules/hackage-packages.nix?

**Comment by peti** [comment]
Yes, please test those builds with a copy of Nixpkgs that has no chances except the `useCpphs ? true` one. Un-installing any packages prior to the testing is unnecessary, though; they won't affect the build.

**Comment by codedmart** [comment]
OK so changing `useCpphs ? true` results in this error:
```
cpphs: macro MIN_VERSION_template_haskell expected 3 arguments, but was given 0
```
This happened when trying to build `reflection-1.5.2.1`

**Comment by codedmart** [comment]
I am going to stick with the `doHaddock = false;` trick for now. Let me know if there is anything else I can test. Thanks guys!

**Comment by peti** [comment]
@codedmart, does this issue still occur when build `random` from the `haskell.packages.ghc7102` packages set? Does GHC 7.10.2 fix this error?

**Comment by peti** [comment]
If someone does still have that problem with GHC 7.10.2, please speak up!

**Comment by codedmart** [comment]
@peti Sorry was out on vacation. This is solved for me now. Thanks!

**Comment by bennofs** [comment]
Why was this bug closed? Shouldn't we at least disable haddock for older ghc versions on darwin in this case? Just letting the builds fail doesn't sound like a good solution to me.

**Comment by codedmart** [comment]
I did incorrectly say that this is solved for me. I don't have the problem with ghc 7.8 or ghc 7.10, but I do still have this problem with ghc 7.6.

**Comment by peti** [comment]
These issues seem to be relevant: https://github.com/haskell/haddock/issues/284 and
https://github.com/haskell/cabal/issues/1740.

**Comment by bennofs** [comment]
@peti Can we fix this by just disabling haddock on darwin for GHC < 7.10?

**Comment by codedmart** [comment]
@bennofs @peti If anything like that GHC < 7.8. I do not have problems with haddock on GHC 7.8 and GHC 7.10 only GHC 7.6. According to what I have read. If there was a way (which I have not tried since I only need GHC 7.6 on one project) to pass `--ghc-options=-optP-P` to `cabal haddock` only on GHC 7.6 that would be best.

**Comment by bennofs** [comment]
Ah right, GHC 7.8 has had minor releases with updated Cabal, so it doesn't affect the GHC 7.8 that we have in nixpkgs.

**Comment by peti** [comment]
@bennofs, I suppose the easiest solution is to adapt the default value of the `doCheck` argument to `pkgs/development/haskell-modules/generic-builder.nix` accordingly.

**Comment by bennofs** [comment]
@peti you probably mean `doHaddock`. Ok, I'll do that.

**Comment by peti** [comment]
Oh, yes, I meant doHaddock. Thanks!
