### ISSUE TITLE
Issue with vulkan and related packages

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#81290]
This is the content of `/nix/store/s1wrbh5lprvifmdj1l0qmjgzg8pxc85h-vulkan-loader-1.1.114.0-dev/lib/pkgconfig/vulkan.pc` on my system:

```
prefix=/nix/store/gj752368s9jdplvszcq3p37jfk6h4w88-vulkan-loader-1.1.114.0
exec_prefix=/nix/store/gj752368s9jdplvszcq3p37jfk6h4w88-vulkan-loader-1.1.114.0
libdir=${exec_prefix}//nix/store/gj752368s9jdplvszcq3p37jfk6h4w88-vulkan-loader-1.1.114.0/lib
includedir=/nix/store/s1wrbh5lprvifmdj1l0qmjgzg8pxc85h-vulkan-loader-1.1.114.0-dev/include

Name: Vulkan-Loader
Description: Vulkan Loader
Version: 1.1.114
Libs: -L${libdir} -lvulkan
Libs.private:  -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
Cflags: -I${includedir}
```

It has `includedir` set to `/nix/store/s1wrbh5lprvifmdj1l0qmjgzg8pxc85h-vulkan-loader-1.1.114.0-dev/include`, which does not exist. This path should point to the include directory of vulkan-headers package.

Also, the `glfw3` package contain headers that include headers from vulkan-headers package. Should the pc file for glfw3 add vulkan-headers to the include path?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(saga): `"nixos-19.09-19.09.2070.b9cb3b2fb2f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tadfisher** [comment]
Ping @Ralith (Vulkan maintainer), I'm seeing `-Wmissing-include-dirs` when building anything depending on vulkan-loader using pkgconfig.

**Comment by Ralith** [comment]
Thanks for the ping! Drafted https://github.com/NixOS/nixpkgs/pull/82425. Please confirm that this solves the problem.
