### ISSUE TITLE
intellij plugins

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#8130]
I would be really helpful to be able to define what plugins we want

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/idea/default.nix

**Comment by edwtjo** [comment]
This is on my todo list

**Comment by MasseGuillaume** [comment]
cool let me know if you need help. Thanks a lot for intellij package!

**Comment by Profpatsch** [comment]
(triage) @edwtjo updates? Otherwise I suggest we close.

**Comment by edwtjo** [comment]
I've previously made an attempt to package intellij with plugins to make an `intellijWithPlugins`, #18241 related, but finally dropped it since its to much effort with too little value added. An `ideaWithPlugins` would make more sense.
