### ISSUE TITLE
Where is Nixpkgs user documentation?

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#8131]
`doc/` contains a manual for people who want to contribute to Nixpkgs. But what documentation do we have for people who want to *use* Nixpkgs? I.e. people who don't care about the default builder, about meta attributes, or license tags, but who care about a manual that tells them how to get LaTeX set up or Haskell packages installed, etc.? Where is that kind of documentation supposed to live? On the Wiki?

**Comment by lethalman** [comment]
I'd like to see the nixpkgs manual be the nixpkgs manual... the contributing part can be a chapter.

**Comment by vcunat** [comment]
Yes, I'd put it in nixpkgs docs. Much information is neither hard-coded in nix nor nixos-specific (belonging to nix and nixos manuals, respectively).

**Comment by domenkozar** [comment]
All the manuals would need to be rethought based on the audience instead of technical background. (I really hate working with docbook, but) +100 if someone tackles that. Even if we just create a new section.

There is one drawback, Nix kind of doesn't separate "packaging" and "user" apis, as we're using the same language so those two have some intersections.

**Comment by lethalman** [comment]
It's about if you just want to install the package/override, or write a new
package.

On Tue, Jun 2, 2015 at 8:47 PM, Domen Kožar <notifications@github.com>
wrote:

> All the manuals would need to be rethought based on the audience instead
> of technical background. (I really hate working with docbook, but) +100 if
> someone tackles that. Even if we just create a new section.
>
> There is one drawback, Nix kind of doesn't separate "packaging" and "user"
> apis, as we're using the same language so those two have some intersections.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/8131#issuecomment-108051440>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by peti** [comment]
My problem now is that I wrote user documentation for Haskell NG and now I wonder where to put it? I thought that I'd put it into the Nixpkgs manual in `doc/`, but that document is kind of unfeasible for the purpose in its current form. I guess it could be restructured and renamed and polished, etc., and then everything would be fine -- but I don't want to get involved with that effort right now. So I'm a little clueless at the moment how to proceed with my Haskell manual. Do I justt dump it into the current manual and hope that it will be cleaned up later? That doesn't feel right. But what else can I do?

**Comment by lethalman** [comment]
@peti I'd say so, just put it somewhere as a chapter in the nixpkgs manual.
Let's not be too schematic.

On Thu, Jun 4, 2015 at 8:31 PM, Peter Simons <notifications@github.com>
wrote:

> My problem now is that I wrote user documentation for Haskell NG and now I
> wonder where to put it? I thought that I'd put it into the Nixpkgs manual
> in doc/, but that document is kind of unfeasible for the purpose in its
> current form. I guess it could be restructured and renamed and polished,
> etc., and then everything would be fine -- but I don't want to get involved
> with that effort right now. So I'm a little clueless at the moment how to
> proceed with my Haskell manual. Do I justt dump it into the current manual
> and hope that it will be cleaned up later? That doesn't feel right. But
> what else can I do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/8131#issuecomment-109000415>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by peti** [comment]
OK.

**Comment by peti** [comment]
Is the Nixpkgs documentation at http://nixos.org/nixpkgs/manual/ updated automatically from `master`? The version number of the current document seems incomplete.

**Comment by vcunat** [comment]
It's certainly from master IIRC (and 15.06 tag confirms that). I'm not sure it's completely automatic, though it's likely.

**Comment by peti** [comment]
OK, apparently the manual is updated by the Hydra job that published the `nixos-unstable` branch, which means there's no telling when my updates will actually show up on the site. 

Now, when I update the documentation, I'd expect the web site to reflect the changes withing a couple of minutes. The notion of waiting a few *hours*, even, seems ridiculous in this day and age. But with hydra.nixos.org driving the update process we're talking about a minimal delay of a *couple of days* at the best of times and delays of several weeks when the channel doesn't pass its test.

I don't think that's an adequate solution.

**Comment by edolstra** [comment]
Well, it's not entirely unreasonable that the online docs correspond to the "current" version, that is, the version in the NixOS or Nixpkgs channel. Otherwise the docs might reflect a reality that hasn't happened yet.

**Comment by peti** [comment]
My commit fdc1887a6ea15685ae725f5c8a33e1f699d98294 was pushed almost 2 weeks ago, but http://nixos.org/nixpkgs/manual/ remains unchanged even though there were successful channel updates. Is the machinery that updates the Nixpkgs manual stuck, maybe?

**Comment by edolstra** [comment]
The current Nixpkgs channel version (8e56452) predates your commit.

**Comment by edolstra** [comment]
@peti In the meantime, you can point people to http://hydra.nixos.org/job/nixpkgs/trunk/manual/latest/download-by-type/doc/manual#users-guide-to-the-haskell-infrastructure.

**Comment by peti** [comment]
OK. I've used the Hydra link now. Thank you for the help!
