### ISSUE TITLE
Stack is broken

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#81338]
stack is broken on all platforms

Normally I wouldn't mind. But it was also listed as a required job for darwin + ofBorg CI, and had to disable in https://github.com/NixOS/nixpkgs/pull/81334.

cc @peti

**Comment by peti** [comment]
Keeping `stack` compiling successfully is such a nightmare that I have essentially given up on maintaining that build. Removing it from `release.nix` was the right choice IMHO.

**Comment by cdepillabout** [comment]
I got `stack` building again in https://github.com/NixOS/nixpkgs/pull/81373 (although it was a pain).

**Comment by cdepillabout** [comment]
This should be fixed in #81373.
