### ISSUE TITLE
Request to package bluepy

### ISSUE THREAD

**Issue by denibertovic** [NixOS/nixpkgs#81330]
**Project description**

Python interface to Bluetooth LE on Linux 

_describe the project a little_

This package seems to be required by mitemp_bt component of home-assistant service. 

**Metadata**

* homepage URL: https://github.com/IanHarvey/bluepy
* source URL: https://github.com/IanHarvey/bluepy
* license: gpl2+ 
* platforms: linux

**Comment by denibertovic** [comment]
So far this is what I got:

```
{ stdenv, fetchPypi, buildPythonPackage, glib, pkgconfig }:

buildPythonPackage rec {
  pname = "bluepy";
  version = "1.3.0";

  src = fetchPypi {
    inherit pname version;
    sha256 = "1v0wjy1rz0rbwghr1z3xhdm06lqn9iig6vr5j2wmymh3w6pysw9a";
  };

  buildInputs = [ glib.dev pkgconfig ];
  nativeBuildInputs = [ glib.dev pkgconfig ];
  propagatedBuildInputs = [ pkgconfig ];

  # run tests?
  doCheck = false;

  meta = with stdenv.lib; {
    description = "Python module for interfacing with BLE devices through Bluez";
    homepage = https://github.com/IanHarvey/bluepy;
    license = licenses.gplv2;
  };
}
```

But it doesn't run because it can't find pkg-config or glib.h .

**Comment by denibertovic** [comment]
It's vendoring in a C dependency and compiling it sigh..... we would want to swap that out for one from nixpkgs but I'm not sure how. Given that there aren't any tests I'm not sure we can know if the version from nixpkgs (which might differ from the one vendored in) would even work.

**Comment by joonazan** [comment]
I am also interested in bluepy. It is the only reliable library for BLE on Linux that I've found.

**Comment by joonazan** [comment]
```nix
with import <nixpkgs> {};

let
bluepy = python37.pkgs.buildPythonPackage rec {
  pname = "bluepy";
  version = "1.3.0";

  src = python37.pkgs.fetchPypi {
    inherit pname version;
    sha256 = "1v0wjy1rz0rbwghr1z3xhdm06lqn9iig6vr5j2wmymh3w6pysw9a";
  };

  buildInputs = [ glib.dev pkgconfig ];
  nativeBuildInputs = [ glib.dev pkgconfig ];
  #propagatedBuildInputs = [ pkgs.pkgconfig ];

  # run tests?
  doCheck = false;

  meta = with stdenv.lib; {
    description = "Python module for interfacing with BLE devices through Bluez";
    homepage = https://github.com/IanHarvey/bluepy;
    #license = licenses.gplv2;
  };
};
in stdenv.mkDerivation {
  name = "position-sensor-dev-env";
  buildInputs = [
    # for receiving BLE
    (python37.withPackages (ps: [bluepy]))
  ];
}
```

This works for me.

**Comment by denibertovic** [comment]
@joonazan Can you provide an example of how you are using this in your configuration.nix?
