### ISSUE TITLE
security.acme module will not fix ownership/mode if cert already exists and isn't newer

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#81335]
**Describe the bug**

If I change `security.acme.certs."burbon.w17.io".group` and enable `security.acme.certs."burbon.w17.io".allowKeysForGroup` when the cert/key in question already exists the group access will not be granted after rebuilding and restarting the `acme-burbon.w17.io.service`. This is because a condition in the post start script does so only when the key is newer than the existing one.

```sh
# cat /nix/store/zk5qw1760629f3bx456kaj9jdgf4vvv3-acme-post-start
#!/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/bash -e
cd /var/lib/acme/burbon.w17.io

# Test that existing cert is older than new cert
KEY=/var/lib/acme/.lego/certificates/burbon.w17.io.key
if [ -e $KEY -a $KEY -nt key.pem ]; then
  cp -p /var/lib/acme/.lego/certificates/burbon.w17.io.key key.pem
  cp -p /var/lib/acme/.lego/certificates/burbon.w17.io.crt cert.pem
  cp -p /var/lib/acme/.lego/certificates/burbon.w17.io.issuer.crt chain.pem
  cat cert.pem chain.pem > fullchain.pem
  cat key.pem cert.pem chain.pem > full.pem
  chmod 750 *.pem
  chown 'root:acme' *.pem
fi
```

```bash
# ls -lah /var/lib/acme/burbon.w17.io/
total 28K
drwxr-x--- 1 root acme   90 Feb 26 15:02 .
drwxr-xr-x 1 root root   36 Feb 26 14:54 ..
-rwx------ 1 root root 3.4K Feb 26 15:02 cert.pem
-rwx------ 1 root root 1.7K Feb 26 15:02 chain.pem
-rwx------ 1 root root 5.0K Feb 26 15:02 fullchain.pem
-rwx------ 1 root root 5.3K Feb 26 15:02 full.pem
-rwx------ 1 root root  288 Feb 26 15:02 key.pem
```

**To Reproduce**
1. Enable security.acme without group/allowKeysForGroup
2. Rebuild and start the service to reques the certificate
3. Add group and allowKeysForGroup
4. Rebuild again and restart the service, the ownership/ode will not be updated

**Expected behavior**
The group and chmod setting should be set on existing certificates as well as new ones.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.6, NixOS, 20.09pre214664.d363be93b49 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre214664.d363be93b49"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: security.acme
```

@m1cr0man

**Comment by mweinelt** [comment]
Additionally, shouldn't chmod 0640 suffice on the `*.pem` files?

**Comment by aanderse** [comment]
cc @Infinisil @flokli @arianvp @emilazy as potentially interested individuals
