### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by gvolpe** [NixOS/nixpkgs#81374]
**Describe the bug**

I'm using `nixpkgs` in Ubuntu 19.10 and I get this error when installing and running Calibre:

```
Gtk-Message: 12:13:48.872: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:13:48.873: Failed to load module "canberra-gtk-module"
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
Aborted (core dumped)
```

**To Reproduce**

1. Install the program: `nix-env -i calibre`
2. Run the program: `calibre`

**Expected behavior**

The Calibre program opens normally.

**Metadata**

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
- system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-40-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(gvolpe): `"nixpkgs-20.09pre214374.1fe82110feb"`
 - nixpkgs: `/home/gvolpe/.nix-defexpr/channels/nixpkgs`
```

Probably related to this issue: https://github.com/NixOS/nixpkgs/issues/24006

**Comment by veprbl** [comment]
According to https://github.com/NixOS/nixpkgs/issues/66755#issuecomment-567016193, OpenGL currently does not work on non-NixOS. This is not specific to any toolkit or a program.

**Comment by veprbl** [comment]
Maybe try this workaround https://github.com/NixOS/nixpkgs/issues/34894#issuecomment-541037136

**Comment by gvolpe** [comment]
Thanks, I guess I'll just stick with installing these kinds of programs with `aptitude` instead of `nixpkgs`, they are not too many in my case.
