### ISSUE TITLE
Boot messages no longer shown during boot

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#8139]
I rebuilt off master sometime earlier today and rebooted. I was greeted by nice new GRUB background (nice) but also no boot messages after that. It just showed me the GRUB background for a while then a black screen for a while then lightdm finally came up.

How do I restore the boot messages? It's hard to tell if something is hanging or restarting or whatever without them.

**Comment by wkennington** [comment]
Is this an efi or bios install?

**Comment by Fuuzetsu** [comment]
bios

**Comment by wkennington** [comment]
I'll see if i can replicate this on a bios machine.

**Comment by wkennington** [comment]
Try passing boot.debug1 to the kernel command line and see if you get a shell in the stage 1. I think the graphical display is just laggy on the bios version.

**Comment by dezgeg** [comment]
I can see this on a 32-bit Virtualbox VM. Oddly enough, if I go to the 'All configurations' menu and boot the latest generation, then it works... which suggests there's a bug in Grub.

BTW, for a split second these errors are displayed: http://www.cs.helsinki.fi/u/tmtynkky/grub.jpg

**Comment by dezgeg** [comment]
There's also a difference in dmesg between good and broken boots:
````
--- bad	2015-06-03 13:31:46.414380706 +0300
+++ good	2015-06-03 13:31:56.962380305 +0300
@@ -121,12 +121,13 @@
 RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=3
 NR_IRQS:2304 nr_irqs:448 0
 CPU 0 irqstacks, hard=f4808000 soft=f480a000
-Console: colour dummy device 80x25
+Console: colour VGA+ 80x25
 console [tty0] enabled
````

**Comment by dezgeg** [comment]
Bah, I thought I tried to revert 159fed47bcfab67d36d4959fb3ac952a7ad9128c already, but reverting that fixes it on Virtualbox. Still, it sounds weird that booting via the 'All configurations' menu and not the default entry changes things.

**Comment by wkennington** [comment]
Try just getting rid of the efi insmods, and then separately try removing
the gfxpayload=keep. I have a feeling it's the gfx payload.

**Comment by dezgeg** [comment]
Yeah, presumably the `gfxpayload=keep` makes the kernel boot in framebuffer/non-text-mode. But since my Arch system also uses `gfxpayload=keep`, I decided to change this on the kernel side instead in PR #8173.

**Comment by vcunat** [comment]
I confirm both issues on legacy bios, i.e. the grub screen is shown until X starts, and text-mode console doesn't appear (it's unusable even after X starts), and grub complains about the missing modules.

Please, be careful about grub changes, as those may be rather difficult to roll back.

**Comment by wkennington** [comment]
Is this still the case even after the kernel config changes in #8173. I'm
going to merge that soon which fixes this issue.

**Comment by vcunat** [comment]
@wkennington: true, #8173 fixes the issue for me (except for the grub messages about modules not found, but that seems a trifle).

**Comment by wkennington** [comment]
Yeah we need a way go make grub ignore trying to load efi modules for
non-efi systems at boot time.

**Comment by jagajaga** [comment]
Confirming these problems on bios.
