### ISSUE TITLE
nix-shell -E doesn't work as expected

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#81422]
**Describe the bug**
Doing `overrideAttrs` on a derivation with `nix-shell -E` doesn't have any effect.

**To Reproduce**
1. Run `nix-shell -E '(import <nixpkgs> {}).zsnes'`.
This will setup zsnes as expected.
2. Exit that shell.
3. Run `nix-shell -E  '(import <nixpkgs> {}).zsnes.overrideAttrs (o: { src = ~/Downloads/wayland-1.18.tar.xz;})'`
This will create a shell with the original zsnes. The new source archive could be anything. Building this expression in nix repl works as expected.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(saga): `"nixos-19.09-19.09.2070.b9cb3b2fb2f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by veprbl** [comment]
Try
```
nix-shell -E 'with import <nixpkgs> {}; mkShell { buildInputs = [ (hello.overrideAttrs (o: { name = "q"; })) ]; }'
```
