### ISSUE TITLE
SDDM fails to start

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#8143]
On advice from an IRC user who claims SDDM works for them, I decided to give it another try. Unfortunately, SDDM still does not start! The relevant log from `journalctl -u display-manager` is:
```
Jun 02 18:29:40 mugen systemd[1]: Starting X11 Server...
Jun 02 18:29:40 mugen systemd[1]: Started X11 Server.
Jun 02 18:29:40 mugen sddm[31471]: Initializing...
Jun 02 18:29:40 mugen sddm[31471]: Starting...
Jun 02 18:29:40 mugen sddm[31471]: Adding new display 0 on vt 7 ...
Jun 02 18:29:40 mugen sddm[31471]: Adding cookie to "/var/run/sddm/:0"
Jun 02 18:29:40 mugen sddm[31471]: Display server starting...
Jun 02 18:29:40 mugen sddm[31471]: Running: /nix/store/b3x2zxb05j5vg0nnbpn754bvbs5vbjwc-xserver-wrapper :0 -auth /var/run/sddm/:0 -nolisten tcp -background none -noreset vt7
Jun 02 18:29:41 mugen sddm[31471]: Signal received: SIGUSR1
Jun 02 18:29:41 mugen sddm[31471]: Running display setup script  "/nix/store/gbygkv0i55igqpb32m1qr7hd4l3x4ca7-sddm-0.11.0/share/sddm/scripts/Xsetup"
Jun 02 18:29:41 mugen sddm[31471]: Display server started.
Jun 02 18:29:41 mugen sddm[31471]: Socket server starting...
Jun 02 18:29:41 mugen sddm[31471]: Socket server started.
Jun 02 18:29:41 mugen sddm[31471]: Greeter starting...
Jun 02 18:29:41 mugen sddm-helper[31530]: [PAM] Starting...
Jun 02 18:29:41 mugen sddm-helper[31530]: [PAM] Authenticating...
Jun 02 18:29:41 mugen sddm-helper[31530]: [PAM] returning.
Jun 02 18:29:41 mugen sddm[31471]: Greeter session started successfully
Jun 02 18:29:41 mugen sddm[31471]: Auth: sddm-helper exited with 2
Jun 02 18:29:41 mugen sddm[31471]: Greeter stopped.
Jun 02 18:33:06 mugen systemd[1]: Stopping X11 Server...
Jun 02 18:33:06 mugen sddm[31471]: Signal received: SIGTERM
Jun 02 18:33:06 mugen sddm[31471]: Socket server stopping...
Jun 02 18:33:06 mugen sddm[31471]: Socket server stopped.
Jun 02 18:33:06 mugen sddm[31471]: Display server stopping...
Jun 02 18:33:06 mugen sddm[31471]: Display server stopped.
```
The most important bit seems to be `sddm-helper exited with 2` which might be related to [this issue](https://github.com/sddm/sddm/issues/371) on the SDDM issue tracker.

It would be nice to have this fixed in NixOS 15.06 because we will be shipping the Plasma 5 desktop for the first time and SDDM is the KDE team's recommended display manager.

/cc @abbradar

**Comment by abbradar** [comment]
I have it working for me too, hm. One idea I can think of is:

1) Recompile SDDM with "-g"
2) Replace helper with a script running `gdbserver` on the helper.
3) Start SDDM
4) Connect to `gdb` from the other terminal
5) Trace-trace-trace; we can at least find a particular place where it exits.

We have proper user and home created by NixOS, but maybe there's a permissions problem or something else...

**Comment by srhb** [comment]
I have the same issue as @ttuegel .

**Comment by ttuegel** [comment]
> We have proper user and home created by NixOS, but maybe there's a permissions problem or something else...

On a hunch I checked the permissions on `/var/lib/sddm`, and its ownership was `sddm:nogroup` rather than `sddm:sddm`. So, I deleted that directory and rebuilt my configuration. Now SDDM works! It looks like we should check the permissions on the user's `$HOME` when `createHome = true`.

@srhb Can you check if `/var/lib/sddm` exists and what its permissions are on your system?

**Comment by srhb** [comment]
It exists, sddm:sddm and 700

**Comment by abbradar** [comment]
@ttuegel It's not so simple to fix permissions; what should we do if parent directory has root/700? Would be nice to do something about this, though.
@srhb Maybe try removing and rebuilding nevertheless? Also check parent directories' permissions.

**Comment by ttuegel** [comment]
@abbradar That's a good point. In that case, I think `nixos-rebuild` should just fail if the permissions are incorrect. We should also check that the user can `cd` into `$HOME` (provided it exists, of course). In this case, I think the problem was probably my earlier attempts at playing around with SDDM left that directory around with the wrong permissions.

**Comment by abbradar** [comment]
@ttuegel Hm, indeed -- I can't think of a case when you want to enable `createHome` and don't care about permissions (i.e. for `nobody` `createHome` should be (and is, IIRC) unset). Maybe though this should just be a warning (like ones when you have changed user/group IDs).

**Comment by srhb** [comment]
I'm experiencing a different error now.

**Comment by srhb** [comment]
I'm experiencing a different error now. The logs appear to contain no errors, but I still only get a black screen with a white dash.

    -- Logs begin at Thu 2015-04-30 20:43:53 CEST, end at Mon 2015-06-08 03:28:50 CEST. --
    Jun 08 03:28:16 nixmonster systemd[1]: Starting X11 Server...
    Jun 08 03:28:16 nixmonster systemd[1]: Started X11 Server.
    Jun 08 03:28:16 nixmonster sddm[738]: Initializing...
    Jun 08 03:28:16 nixmonster sddm[738]: Starting...
    Jun 08 03:28:16 nixmonster sddm[738]: Adding new display 0 on vt 7 ...
    Jun 08 03:28:16 nixmonster sddm[738]: Adding cookie to "/var/run/sddm/:0"
    Jun 08 03:28:16 nixmonster sddm[738]: Display server starting...
    Jun 08 03:28:16 nixmonster sddm[738]: Running: /nix/store/7m6x3gki9c09v2iqcajr7z4fjfkpn55c-xserver-wrapper :0 -auth /va
    Jun 08 03:28:17 nixmonster sddm[738]: Signal received: SIGUSR1
    Jun 08 03:28:17 nixmonster sddm[738]: Running display setup script  "/nix/store/kfnka3dzbpahsi96q9l2lsdpqqv41y56-sddm-0
    Jun 08 03:28:17 nixmonster sddm[738]: Display server started.
    Jun 08 03:28:17 nixmonster sddm[738]: Socket server starting...
    Jun 08 03:28:17 nixmonster sddm[738]: Socket server started.
    Jun 08 03:28:17 nixmonster sddm[738]: Greeter starting...
    Jun 08 03:28:17 nixmonster sddm-helper[801]: [PAM] Starting...
    Jun 08 03:28:17 nixmonster sddm-helper[801]: [PAM] Authenticating...
    Jun 08 03:28:17 nixmonster sddm-helper[801]: [PAM] returning.
    Jun 08 03:28:17 nixmonster sddm[738]: Greeter session started successfully
    Jun 08 03:28:17 nixmonster sddm[738]: Auth: sddm-helper exited successfully

**Comment by heydojo** [comment]
I am experiencing the same issue as @srhb. Getting to try out KDE5 using sddm would be great!

**Comment by heydojo** [comment]
I bumped the sddm version in my tree to 12.0 and the issue is still there. I get this from jourmalctl :
```
Sep 22 07:27:19 nixos kernel: .sddm-greeter-w[869]: segfault at 40 ip 00007f2537c4ad21 sp 00007ffc1bfcc2b0 error 4 in libX11.so.6.3.0[7f2537c0a000+137000]
Sep 22 07:27:21 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:24 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:27 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:30 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:33 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:37 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:40 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:42 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:42 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:43 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:46 nixos kernel: cfg80211: Calling CRDA to update world regulatory domain
Sep 22 07:27:49 nixos kernel: cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
Sep 22 07:27:49 nixos kernel: .sddm-greeter-w[943]: segfault at 40 ip 00007f07425a9d21 sp 00007ffe276ee830 error 4 in libX11.so.6.3.0[7f0742569000+137000]
Sep 22 07:28:15 nixos kernel: cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
Sep 22 07:28:15 nixos kernel: cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
Sep 22 07:29:36 nixos kernel: .sddm-greeter-w[997]: segfault at 19 ip 00007fe9208b293a sp 00007fff7b1df810 error 4 in libc-2.21.so[7fe92083c000+196000]
```
I switched to a console and restarted the display-manager systemd unit and it segfaulted each time and only a black screen appeared.

**Comment by ttuegel** [comment]
I no longer have any SDDM problems, and I have contributed a test to NixOS, so we should not see this again.

**Comment by abbradar** [comment]
Thank you for the test!
