### ISSUE TITLE
unreproducible python3.7 binaries refer to /build/pip-unpacked-wheel-​j79n_99h

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#81441]
**Describe the bug**
As can be seen on https://r13y.com, a number of python3.7 packages are unreproducible because the .pyc binaries refer to paths like '/build/pip-unpacked-wheel-​j79n_99h', where `​j79n_99h` appears to be arbitrary.

**To Reproduce**
For example `nix-build -A python37Packages.importlib-resources --check`

**Expected behavior**
Success ;)

**Additional context**
Bisecting shows this problem appears to have been introduced with #78344 /cc @jonringer

**Comment by FRidh** [comment]
Thanks for reporting. I've opened https://github.com/pypa/pip/issues/7808.

**Comment by misuzu** [comment]
Looks like this would be a long time before it would be fixed upstream.
Maybe we should just add something like this for `buildPythonPackage` for the time being?
```
# putting this in postCheck doesn't work 
postFixup = ''
  for pycache in $(find $out -name __pycache__) ; do
    rm -fr ''${pycache}
  done
'';
```

**Comment by FRidh** [comment]
We would also have to generate the bytecode again but in a reproducible way.

**Comment by misuzu** [comment]
> We would also have to generate the bytecode again but in a reproducible way.

Something like this? :D
```
postFixup = ''
  for pycache in $(find $out -name __pycache__) ; do
    rm -fr ''${pycache}
  done
  python -m compileall $out
'';
```

**Comment by FRidh** [comment]
@misuzu yes something like that https://github.com/NixOS/nixpkgs/pull/90208

**Comment by FRidh** [comment]
Fix is now in staging.

**Comment by simonchatts** [comment]
This seems to break `python3Packages.invoke`.

This package [includes vendored YAML packages for both Python 2 and 3](https://github.com/pyinvoke/invoke/tree/master/invoke/vendor), and ignores the unwanted one at build time. But the `find` in [pythonRecompileBytecodePhase](https://github.com/NixOS/nixpkgs/blob/staging-next/pkgs/development/interpreters/python/hooks/python-recompile-bytecode-hook.sh) tries to compile it all, and hits syntax errors for the Python2 code.

**Comment by FRidh** [comment]
Regressions can be reported in https://github.com/NixOS/nixpkgs/issues/90516

**Comment by FRidh** [comment]
Additional change in https://github.com/NixOS/nixpkgs/pull/102222 that will be reverted because pip 20.2 resolves the issue!

**Comment by raboof** [comment]
This is great!
