### ISSUE TITLE
ATLAS on OSX

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#8146]
About math atlas on a mac. Should it build? I recall having it successfully build (as a dependency for something), but now it seems to "tune" forever. No errors seen yet, though.

I'm buildling with "3 GHz Intel Core Duo 2" on OS X 10.10.3 and lost hope after waiting 84 hours at

        make[5]: Entering directory '/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-atlas-3.10.2.drv-0/ATLAS/build/tune

I'd be grateful for any hints.

**Comment by datakurre** [comment]
http://math-atlas.sourceforge.net/atlas_install/node39.html#sec-build

"For a system like the Core2Duo with architectural defaults, the build step may take 10 or 20 minutes--"

**Comment by vcunat** [comment]
In your place I would just try again. I rather thing we should purge atlas from default dependencies, as build-time auto-tuning goes against nix principles.

**Comment by datakurre** [comment]
Thanks. That was already second trial. I stopped the first one after a day. Now I'm trying to set cpuInfo (in atlas/default.nix) to match my CPU and see if I have better luck.

https://github.com/matthew-brett/math-atlas/wiki/ATLAS-configure-step

**Comment by datakurre** [comment]
*sigh*, it looks like the tune

    make[5]: Entering directory '/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-atlas-3.10.2.drv-0/ATLAS/build/tune/sysinfo'

gets into infinitive loop running this command again and again

    /opt/local/libexec/apple-gcc42/gcc/i686-apple-darwin13/4.2.1/cc1 -quiet -imultilib x86_64 -D__DYNAMIC__ smuladd.c -fPIC -quiet -dumpbase smuladd.c -mmacosx-version-min=10.7 -mfpmath=sse -msse3 -m64 -mtune=core2 -auxbase smuladd -O2 -fomit-frame-pointer -fPIC -o /private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-atlas-3.10.2.drv-0/cciLIXCS.s

only the output file changes.

**Comment by datakurre** [comment]
My issue was http://sourceforge.net/p/math-atlas/support-requests/856/ and was fixed with
    postConfigure = ''                                                            
        sed -i.bak "s/SMAFLAGS =\s*$/SMAFLAGS = -O0/" tune/sysinfo/Make.inc         
        sed -i.bak "s/DMAFLAGS =\s*$/DMAFLAGS = -O0/" tune/sysinfo/Make.inc

I now remember that my previous successful were on a different mac (different cpu), so this is probably Core2Duo specific issues.

**Comment by ttuegel** [comment]
@vcunat Our configuration disables all the tests... that can be disabled. There are some tests which we cannot disable. At least, I couldn't figure out how to disable them (and I have managed to disable some tests which are not documented as disable-able). I am working on improving our OpenBLAS package so we can switch all the Hydra builds over to that. Besides better support for new microarchitectures (IMHO), OpenBLAS has dynamic architecture detection so that people can actually use the Hydra-built OpenBLAS for Real Work.

**Comment by vcunat** [comment]
I once tried to switch some things from atlas to openblas, but it didn't go too well IIRC. Anyway, if you find some useful scraps in it: 87ce749c0, parent and grandparent.

**Comment by ttuegel** [comment]
@vcunat Yes, our OpenBLAS build has been pretty borken in the past; see my comments [here](https://github.com/NixOS/nixpkgs/issues/6392#issuecomment-108590527).
