### ISSUE TITLE
Huge performance regression in NixOS evaluation

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#8152]
Evaluating my NixOS configuration on 14.12 takes 1.0s:
```
$ command time nix-instantiate '<nixpkgs/nixos>' -A system --dry-run
...
1.04user 0.12system 0:01.17elapsed 99%CPU (0avgtext+0avgdata 283080maxresident)k
```
But on current master it takes 2.7s and much more memory:
```
$ command time nix-instantiate nixos -A system --dry-run
...
2.75user 0.16system 0:02.91elapsed 100%CPU (0avgtext+0avgdata 473772maxresident)k
```

This is a release blocker. This kind of performance regression is bad enough for a single system, but for (say) NixOps evaluations of many machines it would be really bad.

To reproduce: evaluating `nixos/tests/kde4.nix` gives an even worse regression, going from 0.79s to 2.52s.

**Comment by edolstra** [comment]
And kde4 evaluation went from using 176 MiB to 444 MiB.

**Comment by copumpkin** [comment]
Does hydra keep plots of this sort of measure? Could be handy to help someone track down when it started happening.

**Comment by edolstra** [comment]
Our buildfarm isn't suitable for keeping track of performance measurements because the system load on the build machines would make such numbers highly variable.

**Comment by vcunat** [comment]
Well, real time would be variable, but user&sys time and consumed memory shouldn't be affected significantly, should they?

**Comment by edolstra** [comment]
Memory wouldn't, but user and system time depends on the type of machine the build runs on.

**Comment by copumpkin** [comment]
The way I've seen one CI system do it is to plot build stats for different build nodes in different colors. Sure, the system can't figure out automatically if something is high or not, but by grouping by the machine that built it (or some classifier of the type of machine), a human looking at the graph can get a much better sense for abnormalities.

**Comment by vcunat** [comment]
That seems about the amount of slow-down noticed in nxipkgs itself #3594.

**Comment by vcunat** [comment]
I would expect this to be much better now that #3594 is fixed, but I haven't verified yet.

**Comment by vcunat** [comment]
As of now, evaluation of my system (including KDE) goes up by ~25% since 14.12. That seems acceptable to me, at least to unblock the release.

**Comment by edolstra** [comment]
It's better but still nearly a 100% slowdown. Currently evaluation of my system configuration takes 2.06s on master, and 1.18s on 14.12.

**Comment by nbp** [comment]
I was looking at the log of string concatenations between the 2 versions, and one of the big differences in recent version seems to be related to the package names which seems to be computed from the tarballs.

Also, I noticed that the number of concatenations of the cc-wrapper seems to have increased by ~40, which might induce some copies, as the generated script is ~4k.

Here are the raw results of the most frequents lines of the concatenated results, while running the latest nix with `nix-instantiate -A tests.kde4 ./release.nix`.  On the left we have release-14.12 branch, on the right we have the result from a branch for #7835 changes.

```
  27728                                                       |   29364
   4448 fi                                                    |    5618 fi
   1428 startNest                                             |    3278 /
   1360     # system profile.                                 |    3236 .tar
   1360     # If we can't find the program, fall back to the  |    1458     # system profile.
   1336 stopNest                                              |    1458     # If we can't find the program, fall back to the
   1152                                                       |    1112 kde-l10n
    550 :anon-2                                               |     566 :anon-2
    544 :anon-1                                               |     564 :anon-1
    486 null or string                                        |     534 }
    484 mkdir -p $out/'multi-user.target.wants'               |     524 mkdir -p $out/'multi-user.target.wants'
    464                 }                                     |     460 null or string
    424                                                       |     400 # you get tools like gcov, the manpages, etc. as well
    384 :anon-2:anon-1                                        |     400 wrap() {
    368 }                                                     |     400 # This confuses libtool.  So add it to the compiler t
    360 # you get tools like gcov, the manpages, etc. as well |     400 # (the *last* value counts, so ours should come first
```

**Comment by nbp** [comment]
Doing the same with attribute names leads to some extensive uses of `name` and `version`, which suggests that we are either building a lot more packages which were either not listed before or not present, and there is also a lot of `fst` and `snd` attributes which suggests that we might using `zipLists`.

```
 102335 name,                                                 |  795556 name,
  93775 value,                                                |  661218 version,
  66819 type,                                                 |  330448 snd,
  63821 options,                                              |  330142 fst,
  49993 _type,                                                |  163887 value,
  49523 all,                                                  |   86742 file,
  49268 out,                                                  |   79526 type,
  45726 declarations,                                         |   74841 options,
  45275 file,                                                 |   60604 all,
  42792 buildInputs,                                          |   60423 out,
  40376 builder,                                              |   56711 _type,
  38100 loc,                                                  |   52974 declarations,
```

**Comment by nbp** [comment]
The increase of `fst` and `snd` is related to the usage of `replaceChars`, I have a patch to reduce the number of attribute set created by `replaceChars`, which improves by creating ~9% less attribute sets:

```
- 330448 snd,
- 330142 fst,
+ 31174 snd,
+ 30868 fst,
```

I will submit this patch.

**Comment by vcunat** [comment]
I can't find any significant usage of `replaceChars` except for nixos/modules/system/boot/systemd{,-lib}.nix where we use `pathSafeName` and `shellEscape` in `makeUnit` and `makeJobScript`. However, that seems the same approach as in 14.12.

**Comment by nbp** [comment]
Locally, #8806 does not improves memory usage, but reduces the execution time by 6%.

**Comment by edolstra** [comment]
Plot of evaluation time of my system configuration since 14.12:
![user-time](https://cloud.githubusercontent.com/assets/1148549/8926298/ebbf8734-350e-11e5-8aff-2afca387872d.png)

Number of values allocated during evaluation (less noisy, but pretty well correlated):
![values](https://cloud.githubusercontent.com/assets/1148549/8926322/196875ba-350f-11e5-8fe7-13582ce9ba21.png)

The main events appear to have been KDE and module system changes.

**Comment by edolstra** [comment]
Closing, since performance is now within 10% or so of 14.12:
![user-time](https://cloud.githubusercontent.com/assets/1148549/8955422/de19be2c-35ec-11e5-8966-1cd567396a58.png)
(That using Nix 1.10 BTW, which has some new builtins to speed up Nixpkgs/NixOS).

**Comment by geerds** [comment]
Good job! :beers:

**Comment by davidak** [comment]
@edolstra how do you got the plot? how are the current values?

**Comment by edolstra** [comment]
@davidak Don't remember, probably just running nix-instantiate over a list of Git revisions and feeding the result into gnuplot. You can get current data from the `metrics` job on Hydra, e.g. https://hydra.nixos.org/job/nixpkgs/trunk/metrics/metric/nixos.kde.time (showing that KDE evaluation has gone from 1.2s to 6.5s in the last 3 years).
