### ISSUE TITLE
texlive: grffile package is very outdated

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#81544]
**Describe the bug**

Using TeX Live 2019 on NixOS 20.03, I noticed that [`grffile`](https://ctan.org/pkg/grffile) package is very outdated: the current version is `v2.1 2019-11-11`, but on my system i have `v1.18 2017-06-30`. This can cause [issues](https://tex.stackexchange.com/q/530805).

I wonder if there are more outdated TeX Live packages.

**To Reproduce**

1. Configure and install TeX Live so that `grffile` be included (`collection-latexrecommended`):
    ```nix
    # file: ~/.nixpkgs/config.nix
    {
      packageOverrides = pkgs: {
        myTexLive = pkgs.texlive.combine {
          inherit (pkgs.texlive) scheme-basic
                                 collection-latex
                                 collection-latexrecommended;
        };
      };
    }
    ```

    ```console
    $ nix-env -iA nixos.myTexLive
    ```

2. Inspect `grffile.sty`:
    ```console
    $ head -n15 $(kpsewhich grffile.sty)
    %%
    %% This is file `grffile.sty',
    %% generated with the docstrip utility.
    %%
    %% The original source files were:
    %%
    %% grffile.dtx  (with options: `package')
    %% 
    %% This is a generated file.
    %% 
    %% Project: grffile
    %% Version: 2017/06/30 v1.18
    %% 
    %% Copyright (C) 2006-2012 by
    %%    Heiko Oberdiek <heiko.oberdiek at googlemail.com>
    ```

**Expected behavior**

A recent version should be installed.

**Additional context**

The old version of `grffile` seems to cause [bugs](https://tex.stackexchange.com/q/530805) with TeX Live 2019.

**Metadata**

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.23-hardened, NixOS, 20.03beta377.ebc9620c3f6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3238.e984f9e48e1"`
 - channels(root): `"nixos-20.03beta377.ebc9620c3f6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by veprbl** [comment]
I'm looking to bump to the tlnet-final snapshot as soon as it is completely frozen. That will be in a few days.
