### ISSUE TITLE
Mariadb failing on darwin

### ISSUE THREAD

**Issue by pmahoney** [NixOS/nixpkgs#8155]
See http://hydra.nixos.org/build/22680121/nixlog/2

```
/nix/store/bjfqgngq93l9gabrjcy1sp16279inr27-clang-wrapper-3.6.1/bin/clang++
  doesn't support -std=c++11 or -std=c++0x, you need one that does.
```

The error message is a bit misleading. Turns out the error is due to `NIX_CFLAGS_COMPILE = "-Wno-error=cpp";` and this error in the cmake build log `error: unknown warning option '-Werror=cpp' [-Werror,-Wunknown-warning-option]`.

Setting `NIX_CFLAGS_COMPILE` to the empty string allows the build to proceed, but it fails later for reasons I don't understand:

```
...
/nix/store/kwpryad4dbp6z7ldssb1p1yc0skzz34k-cctools-port-862/bin/ranlib: file: libgroonga.a(mrb_type.c.o) has no symbols
/nix/store/kwpryad4dbp6z7ldssb1p1yc0skzz34k-cctools-port-862/bin/ranlib: file: libgroonga.a(mrb_variable_size_column.c.o) has no symbols
/nix/store/kwpryad4dbp6z7ldssb1p1yc0skzz34k-cctools-port-862/bin/ranlib: file: libgroonga.a(mrb_void.c.o) has no symbols
/nix/store/kwpryad4dbp6z7ldssb1p1yc0skzz34k-cctools-port-862/bin/ranlib: file: libgroonga.a(mrb_writer.c.o) has no symbols
[ 10%] Built target libgroonga
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

libgroonga was the last target to build (apparently successfully), but no error message beyond that.

**Comment by gridaphobe** [comment]
I'm hitting this as well, the next problem is that cmake tries to run `/var/empty/bin/libtool` which obviously doesn't exist.. I haven't had a chance to figure out **why** it's looking for libtool in `/var/empty` though instead of just looking in the PATH.

**Comment by pmahoney** [comment]
Getting a little farther disabling TokuDB

https://github.com/Homebrew/homebrew/commit/a14984cd174fb01221a3cb3058732b4f4855e428
https://mariadb.com/kb/en/mariadb/enabling-tokudb/

**Comment by pmahoney** [comment]
@gridaphobe I believe this is the cause of `/var/empty`: https://github.com/NixOS/nixpkgs/blob/03e4e3e92a25386ed559e3c4a70782c7f07fa355/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L5

**Comment by pmahoney** [comment]
@gridaphobe Did you run "patchPhase"? I assume you're using something like `nix-shell -A mariadb` to debug this?  It's that `prePatch` script in mariabd that changes `/usr/bin/libtool` to `libtool` so that the cmake hook won't later change it to `/var/empty`.

Still not building though...

**Comment by pmahoney** [comment]
Now I get to

```
Scanning dependencies of target mysql
[ 88%] Building CXX object client/CMakeFiles/mysql.dir/completion_hash.cc.o
[ 88%] Building CXX object client/CMakeFiles/mysql.dir/mysql.cc.o
[ 88%] Building CXX object client/CMakeFiles/mysql.dir/readline.cc.o
[ 88%] Building CXX object client/CMakeFiles/mysql.dir/__/sql/sql_string.cc.o
make[2]: *** No rule to make target '/nix/store/a13gd3pv849zwsdyn2abgjldnxsx63p1-ncurses-5.9/lib/libcurses.so', needed by 'client/mysql'.  Stop.
CMakeFiles/Makefile2:6795: recipe for target 'client/CMakeFiles/mysql.dir/all' failed
make[1]: *** [client/CMakeFiles/mysql.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by pmahoney** [comment]
...and ncurses doesn't build a shared lib on darwin: https://github.com/NixOS/nixpkgs/blob/03e4e3e92a25386ed559e3c4a70782c7f07fa355/pkgs/development/libraries/ncurses/default.nix#L25

**Comment by pmahoney** [comment]
Successfully built with these patches: https://github.com/NixOS/nixpkgs/compare/NixOS:master...pmahoney:mariadb-darwin?expand=1

Working on getting a pull request out, within a week I hope.

**Comment by pmahoney** [comment]
See pull request https://github.com/NixOS/nixpkgs/pull/8347

**Comment by gridaphobe** [comment]
This no longer appears to be an issue on master.
