### ISSUE TITLE
Spotify broken by libgcrypt upgrade

### ISSUE THREAD

**Issue by monocell** [NixOS/nixpkgs#8156]
a71f78acf71b4063be1912b8655ce53acb48f24e removed the older libgcrypt version, but the current spotify client seems to depend on libgcrypt.so.11. Pretending with libgcrypt.so.20 produces an error like: ``... libgcrypt.so.11: version `GCRYPT_1.2' not found ...``

Would it be ok to keep the old library as well, or do we make no concessions on account of disgusting binary blobs?

**Comment by lethalman** [comment]
@monocell if anything depends on an older version of a lib it's ok to readd it. Feel free to make a PR to reintroduce the older version and let spotify use it. cc @wkennington
