### ISSUE TITLE
Update Xfce to 4.16

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#81569]
**Describe the bug**
According to Xfce's roadmap https://wiki.xfce.org/releng/4.16/roadmap, they will release around June 2020. This is before 20.09 freeze so we can for sure have this in 20.09.

**Comment by worldofpeace** [comment]
They have now pushed it to October/November so this won't be a part of 20.09 but 21.03

**Comment by estysdesu** [comment]
[4.16 released!](https://xfce.org/about/news/?post=1608595200)

**Comment by lobre** [comment]
Things are moving there: https://github.com/NixOS/nixpkgs/pull/114567
