### ISSUE TITLE
nix-shell pegs CPU trying to evaluate a bad symbolic link to `shell.nix`

### ISSUE THREAD

**Issue by jjwatt** [NixOS/nixpkgs#81575]
**Describe the bug**
A circular symbolic link `shell.nix` -> `shell.nix` doesn't error out on `nix-shell ./shell.nix`, but instead will cause it to peg a CPU at 100% with no output (with default verbosity).

**To Reproduce**
1. ln -s shell.nix shell.nix
2. nix-shell ./shell.nix

**Expected behavior**
I would expect nix-shell to detect this issue beforehand and show a warning or refuse to run.
For example, some other Unix tools catch it:
```shell
[jwatt@wisdom-like-silence:/tmp]$ file shell.nix
shell.nix: broken symbolic link to shell.nix

[jwatt@wisdom-like-silence:/tmp]$ cat shell.nix
cat: shell.nix: Too many levels of symbolic links

[jwatt@wisdom-like-silence:/tmp]$ grep stuff shell.nix
grep: shell.nix: Too many levels of symbolic links
```

**Additional context**
I made a bad symbolic link from one directory where I was editing `shell.nix` to another one where I was wanting to run it in. After waiting for over 5 or 10 minutes and watching htop, I finally went and found the link to point to itself. I'm not sure exactly what error I made to make the faulty link, but it should be reproducible just by `cd /tmp && ln -s shell.nix shell.nix && nix-shell ./shell.nix` e.g.,

```shell
[jwatt@wisdom-like-silence:/tmp]$ ln -s shell.nix shell.nix
[jwatt@wisdom-like-silence:/tmp]$ ls -alh shell.nix
lrwxrwxrwx 1 jwatt users 9 Mar  2 22:04 shell.nix -> shell.nix
[jwatt@wisdom-like-silence:/tmp]$ nix-shell ./shell.nix
```

At the very least, it seems like one might be able to cause a little bit of a denial of service with this, since with standard user permissions to run `nix-shell` I can peg one CPU to 100%, I might imagine doing this several (hundred, thousand, etc) times and taking system resources.

Running with verbosity doesn't seem to give much more info, either:
```shell
[jwatt@wisdom-like-silence:/tmp]$ nix-shell -vvvv ./shell.nix
evaluating file '/nix/store/z4bjgjzc1xdw4b70mgym9klcqqkkd1n8-nix-2.3.2/share/nix/corepkgs/derivation.nix'
```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.21, NixOS, 19.09.2145.c2c5dcc00b0 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2145.c2c5dcc00b0"`
 - channels(jwatt): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
Issues regarding Nix the package manager should be filed to a different tracker https://github.com/NixOS/nix/issues

**Comment by jjwatt** [comment]
Sorry about that. Thank you. I'll file it there!

**Comment by jjwatt** [comment]
For reference, I opened the bug on `nix` here: https://github.com/NixOS/nix/issues/3385
