### ISSUE TITLE
foldingathome client version 7

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#81632]
**Project description**
Due to the recent Corona virus outbreak, the project needs more computing power, see

https://foldingathome.org/2020/02/27/foldinghome-takes-up-the-fight-against-covid-19-2019-ncov/

The package in NixOS is old (version 6) and only i686 ready. Here is the current version:

https://foldingathome.org/start-folding/

Available as a deb and rpm, apparently. I have no experience with this type of packaging, so I cannot do it myself in a reasonable amount of time, I think.

**Comment by andersk** [comment]
This was fixed by #82192.
