### ISSUE TITLE
Can't install vinyl, or anything that depends on it

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#81667]
**Describe the bug**

I went to install the haskell package `pkgs.haskellPackages.Frames`, and but it fails, since a package it depends on, vinyl, depends on an older version of hspec. It gives the error: 

```
Setup: Encountered missing dependencies:
hspec >=2.2.4 && <2.7
```

**To Reproduce**
1. nix-env -iA haskellPackages.Frames

**Expected behavior**

I can install this haskell package. 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.7, NixOS, 20.09pre215333.42f0be81ae0 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(jon): `"home-manager, home-manager-sway, nixpkgs-20.09pre214168.686274ea62c"`
 - channels(root): `"nixos-20.09pre215333.42f0be81ae0"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

**Comment by cdepillabout** [comment]
We'd appreciate a PR fixing any of these packages.

https://discourse.nixos.org/t/call-to-action-for-updating-haskell-packages-after-bump-to-lts-15/6071

**Comment by svmhdvn** [comment]
Both vinyl and Frames builds on haskell-updates, can this be closed?

**Comment by cdepillabout** [comment]
@svmhdvn Thanks for this report!
