### ISSUE TITLE
Systemd ignoring special prefixes

### ISSUE THREAD

**Issue by brano543** [NixOS/nixpkgs#81727]
**Describe the bug**
I have installed systemd 243 from nixpkgs repository and I am having trouble using special executable prefixes in service files. Every time I use prefix + or !, the respective line gets ignored.

**To Reproduce**
Modified /usr/lib/systemd/system/sshd.service
```
[Unit]
Description=OpenSSH server daemon
Documentation=man:sshd(8) man:sshd_config(5)
After=network.target sshd-keygen.service
Wants=sshd-keygen.service

[Service]
Type=notify
EnvironmentFile=/etc/sysconfig/sshd
ExecStartPre=!/bin/echo 'test'
ExecStart=/usr/sbin/sshd -D $OPTIONS
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartSec=42s

[Install]
WantedBy=multi-user.target
```
the output doesn't contain the echo.
```
sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-04 15:53:57 CET; 4s ago
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 24336 (sshd)
    Tasks: 1
   CGroup: /system.slice/sshd.service
           └─24336 /usr/sbin/sshd -D

Mar 04 15:53:57 pandora systemd[1]: Starting OpenSSH server daemon...
Mar 04 15:53:57 pandora sshd[24336]: Server listening on 0.0.0.0 port 22.
Mar 04 15:53:57 pandora sshd[24336]: Server listening on :: port 22.
Mar 04 15:53:57 pandora systemd[1]: Started OpenSSH server daemon.
```

**Expected behavior**
Output of systemctl status sshd should be following.
```
sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-04 15:43:23 CET; 6s ago
     Docs: man:sshd(8)
           man:sshd_config(5)
  Process: 23168 ExecStartPre=/bin/echo test (code=exited, status=0/SUCCESS)
 Main PID: 23170 (sshd)
    Tasks: 1
   CGroup: /system.slice/sshd.service
           └─23170 /usr/sbin/sshd -D

Mar 04 15:43:23 pandora systemd[1]: Starting OpenSSH server daemon...
Mar 04 15:43:23 pandora echo[23168]: test
Mar 04 15:43:23 pandora sshd[23170]: Server listening on 0.0.0.0 port 22.
Mar 04 15:43:23 pandora sshd[23170]: Server listening on :: port 22.
Mar 04 15:43:23 pandora systemd[1]: Started OpenSSH server daemon.

```

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by lheckemann** [comment]
`systemd` from nixpkgs is not expected to work on other distros at all. Additionally, you're probably still running your distro's systemd (because everything would AFAIK break horribly otherwise) and only using `systemctl` from nixpkgs's systemd to talk to it.

**Comment by brano543** [comment]
What would be your advice? I should just install the newer systemd from my distribution instead?

**Comment by evanjs** [comment]
Is there no way to utilize command prefixes in systemd on NixOS at the moment, then?
e.g. `ExecStartPre=-"some commands to execute here"`

According to the documentation (via the [ExecStartPre](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=) section on the `systemd.service` page):
> If any of those commands (not prefixed with "-") fail, the rest are not executed and the unit is considered failed.

**Comment by lheckemann** [comment]
@evanjs there shouldn't be any problem with that (this seems to be used by `modules/services/misc/tiddlywiki.nix` in fact). I think this issue is more a case of confusion with where @brano543's systemd is coming from.

@brano543 yes, install a newer version of systemd from your distribution and reboot. If there is none, you may need to perform a distribution upgrade.
