### ISSUE TITLE
Nix-prefetch-hg command does not work on darwin

### ISSUE THREAD

**Issue by curaloucura** [NixOS/nixpkgs#8174]
`myhost:rhodecode-momentum-fork anderson$ nix-prefetch-hg <url>`
`abort: could not find web.cacerts: /etc/ssl/certs/ca-bundle.crt`

@garbas

**Comment by garbas** [comment]
i guess you can override web.certs in hgrc file like explained here:

    https://mercurial.selenic.com/wiki/CACertificates

but it would be nice to provide some default that "just" works like we did for
git via GIT_SSL_CAINFO.

anybody has any idea how this works in marcurial?


--
Rok Garbas - http://www.garbas.si

**Comment by johbo** [comment]
Just ran into the same issue. Giving this a quick try. Found this in the wrapping script:

```
export HOME=:
```

This might make it difficult to use a setting from my ~/.hgrc, not sure yet though.

**Comment by johbo** [comment]
I guess this will be fixed by cd52c044568bdf1108428698048a9af92dc0b625 and ffd0539eba473348f752fa8ab1f1f55388634f8f

They seem to change from a hardcoded `/etc/ssl/...` to something based on `cacerts` in the nix-store.

**Comment by johbo** [comment]
Found a workaround:
```
HGRCPATH=~/.hgrc nix-prefetch-hg
```

Although I think that it is better to craft a special `.hgrc` for this case which has only the fingerprint in it. I am afraid that otherwise some settings might influence the result and thus lead to an unexpected result.

**Comment by johbo** [comment]
Just finished build of `nix-prefetch-scripts` on latest master, had to cherry-pick the commit 616ed6ee152ac16dd617fbbab2ee275e2e36d401 on top of it. Then it worked, so I guess we will see this soon fixed. :-)

**Comment by garbas** [comment]
@johbo looks like this has been fixed. please reopen ticket if this still persists afterwards.
