### ISSUE TITLE
Respect settings from ~/.pam_environment

### ISSUE THREAD

**Issue by dfoxfranke** [NixOS/nixpkgs#8177]
The file `~/.pam_environment` is convenient way to control environment variables because it gets used regardless of how the user session is initiated: you don't have to repeat yourself across `.bash_profile`, `.bashrc`, `.xsessionrc`, etc. Unfortunately, anything you set in this file gets trampled by /etc/profile when it sources `/nix/store/set-environment`. Please have this script check whether the environment variables it controls are already set, and if so leave them alone.

**Comment by wmertens** [comment]
@dfoxfranke do you feel up to adjusting the profile script for this? https://github.com/NixOS/nixpkgs/blob/31c158ad453547993095b9425a60697738fdac5d/nixos/modules/programs/bash/bash.nix

Also, are you sure this is always a good idea? For example, if something in PAM sets an environment variable to some wrong default, then the NixOS version won't overwrite it.

**Comment by Profpatsch** [comment]
No reply, so I’m closing.
