### ISSUE TITLE
wdisplays

### ISSUE THREAD

**Issue by eoli3n** [NixOS/nixpkgs#81825]
**Project description**
"It's intended to be the Wayland equivalent of an xrandr GUI, like ARandR."

**Metadata**

* homepage URL: https://github.com/cyclopsian/wdisplays
* source URL: https://github.com/cyclopsian/wdisplays
* license: custom : https://github.com/cyclopsian/wdisplays/blob/master/LICENSE
* platforms: linux

**Comment by primeos** [comment]
In case someone's interested: It might work to ask upstream via a GitHub issue if they could tag a release (e.g. a pre-release like 0.1) for distributions to package.

**Comment by Ma27** [comment]
Already part of `nixpkgs-unstable`, will appear in 20.03 (1bf0d4444ca2687fb4fd4c45c50fae519a576275).

In case you want it now (and are on 19.09), you can install it like this:

``` nix
{
  environment.systemPackages = [ # home.packages would work as well
    (import /path/to/nixpkgs-unstable {}).wdisplays # instead of a path you can also fetch a nixos-unstable rev using `builtins.fetchTarball` here
  ];
}
```
