### ISSUE TITLE
qgnomeplatform requires gsettings-desktop-schemas

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#81866]
Following the last couple, I can now reproduce the issue again. I'm running NixOS off of [this branch](https://github.com/lovesegfault/nixpkgs/commits/nixpkgs-lovesegfault), which is just `nixos-unstable` with the previous too patches, that were still in staging`, applied.

With that branch I get the following when I try to launch zoom:
```
❯ zoom-us
ZoomLauncher started.
cmd line:
CreateReportChannel bp_server_fd=4
$HOME = /home/bemeurer
export SSB_HOME=/home/bemeurer/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/nix/store/ysp9ql4l038m13gd3wyn5gr66xg60lc7-zoom-us-3.5.361976.0301/share/zoom-us; export BREAKPAD_CLIENT_FD=3; /nix/store/ysp9ql4l038m13gd3wyn5gr66xg60lc7-zoom-us-3.5.361976.0301/share/zoom-us/zoom ""
zoom started.
Client: Breakpad is using Client-Server Mode! client fd = 3

(process:24790): GLib-GIO-ERROR **: 20:13:11.433: Settings schema 'org.gnome.desktop.wm.preferences' is not installed
ZoomLauncher: new dump generated from pid 24790, path: /home/bemeurer/.zoom/logs/39619221-5fab-460d-0e59b3a3-b25c461f.dmp
$HOME = /home/bemeurer
sh: line 1: 24790 Trace/breakpoint trap   (core dumped) /nix/store/ysp9ql4l038m13gd3wyn5gr66xg60lc7-zoom-us-3.5.361976.0301/share/zoom-us/zoom ""
success to create child process,status is 34048.
zoom exited normally.
Something went wrong while running zoom,exit code is 133.
ZoomLauncher exit.
```

Edit: See https://github.com/NixOS/nixpkgs/issues/81866#issuecomment-602851994 https://github.com/NixOS/nixpkgs/issues/81866#issuecomment-599676558

**Comment by veprbl** [comment]
cc @danbst @tadfisher

**Comment by lovesegfault** [comment]
I think this is a non-issue and was due to `NIX_PATH` being an absolute pain in my ass. I'm testing and will update soon.

**Comment by lovesegfault** [comment]
Alright, I can confirm that this is an issue, but seems to only affect zoom.
```
❯ zoom-us
ZoomLauncher started.
cmd line:
CreateReportChannel bp_server_fd=4
$HOME = /home/bemeurer
export SSB_HOME=/home/bemeurer/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/nix/store/0isgrnbqfxm2315ljylp9i86m6n584zb-zoom-us-3.5.361976.0301/share/zoom-us; export BREAKPAD_CLIENT_FD=3; /nix/store/0isgrnbqfxm2315ljylp9i86m6n584zb-zoom-us-3.5.361976.0301/share/zoom-us/zoom ""
zoom started.
Client: Breakpad is using Client-Server Mode! client fd = 3

(process:14377): GLib-GIO-ERROR **: 21:32:14.611: No GSettings schemas are installed on the system
ZoomLauncher: new dump generated from pid 14377, path: /home/bemeurer/.zoom/logs/6086842b-5784-4b01-50abb6a0-075f0aa0.dmp
$HOME = /home/bemeurer
sh: line 1: 14377 Trace/breakpoint trap   (core dumped) /nix/store/0isgrnbqfxm2315ljylp9i86m6n584zb-zoom-us-3.5.361976.0301/share/zoom-us/zoom ""
success to create child process,status is 34048.
zoom exited normally.
Something went wrong while running zoom,exit code is 133.
ZoomLauncher exit.
```

cc. @jtojnar @worldofpeace

**Comment by jtojnar** [comment]
What actions did you take?

For me, on 242742d195926bf4fd9fee17f57bb6cfbd56ecab, it shows login page without an error (running `env XDG_DATA_DIRS= NIX_GSETTINGS_OVERRIDES_DIR= result/bin/zoom-us`).

**Comment by danbst** [comment]
I'm running Zoom from recent master (30631f74a08f4274bedbfb666ea97fb6791c5c1c) and it doesn't crash. @lovesegfault can you reproduce crash on that revision?

**Comment by lovesegfault** [comment]
@danbst I later isolated the issue with jtojnar on the IRC. Try adding this clause to your configuration and see if you can repro the issue:
```Nix
{
  qt5 = {
    enable = true;
    platformTheme = "gnome";
    style = "adwaita";
  };
}
```

**Comment by danbst** [comment]
@lovesegfault no crash for me, though I don't have an error "(process:14377): GLib-GIO-ERROR **: 21:32:14.611: No GSettings schemas are installed on the system" in a log. Maybe that's because I run gnome-shell, which has the `gsettings`?

**Comment by lovesegfault** [comment]
@danbst Maybe? I could/can consistently repro with the above

**Comment by worldofpeace** [comment]
There must be some gsettings related code in the platform theme that needs to be patched/hardcoded.

**Comment by worldofpeace** [comment]
Yeah, it wants the gnome hints which requires gsettings-desktop-schemas https://github.com/FedoraQt/QGnomePlatform/blob/a4a5788e754c0d55980454a60a04963a2ca31aa6/common/gnomehintssettings.cpp#L83. We can do a hardcode-gsettings patch like https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/glib-networking/hardcode-gsettings.patch, to make it depend on gsettings-desktop-schemas since we can't wrap it.
The issue doesn't appear in gnome because the global environment will have gsettings-desktop-schemas. @lovesegfault You use sway right? Even there these should be available...

**Comment by lovesegfault** [comment]
> @lovesegfault You use sway right? Even there these should be available...

That is correct; I use sway configured with home-manager. Relevant configs:
https://github.com/lovesegfault/nix-config/blob/cd133cb86e1fbc20083f2f7bbdb442c1834ae8f3/sway/default.nix#L12-L24
https://github.com/lovesegfault/nix-config/blob/cd133cb86e1fbc20083f2f7bbdb442c1834ae8f3/sway/sway.nix
https://github.com/lovesegfault/nix-config/blob/cd133cb86e1fbc20083f2f7bbdb442c1834ae8f3/users/bemeurer/sway/sway.nix

**Comment by worldofpeace** [comment]
> > @lovesegfault You use sway right? Even there these should be available...
> 
> That is correct; I use sway configured with home-manager. Relevant configs:
> https://github.com/lovesegfault/nix-config/blob/cd133cb86e1fbc20083f2f7bbdb442c1834ae8f3/sway/default.nix#L12-L24
> https://github.com/lovesegfault/nix-config/blob/cd133cb86e1fbc20083f2f7bbdb442c1834ae8f3/sway/sway.nix
> https://github.com/lovesegfault/nix-config/blob/cd133cb86e1fbc20083f2f7bbdb442c1834ae8f3/users/bemeurer/sway/sway.nix

This withGtkWrapper https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/sway/wrapper.nix#L36, should probably pull in `gtk3`, `glib`, and `gsettings-desktop-schemas` also.

**Comment by lovesegfault** [comment]
cc. @gnidorah who, IIRC, worked on the sway Gtk wrapper.

**Comment by gnidorah** [comment]
@lovesegfault Yes that's same for me. I've got crash using this WIP module until added gsettings-desktop-schemas https://github.com/NixOS/nixpkgs/pull/80866/files#diff-e646a22f973329b0f6a12f5f1f38ebd7R111

**Comment by gnidorah** [comment]
@jtojnar @worldofpeace
Found an issue with this solution:
1) Start i3wm
2) Launch VLC via dmenu
3) Click Media - Open file (Ctrl + O)
Boom - crash!
