### ISSUE TITLE
qt webkit for qt4 is very old, upgrade to community version of qtwebkit for qt4

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#8187]
There is a community version of QtWebKit that is based on a much more recent version webkit.

https://gitorious.org/webkit/qtwebkit-23/
https://blogs.kde.org/2012/11/14/introducing-qtwebkit-23

Most distributions are using that.
https://tracker.debian.org/pkg/qtwebkit
https://build.opensuse.org/package/show?project=openSUSE%3AFactory&package=libQtWebKit4
http://packages.ubuntu.com/trusty/libqtwebkit-dev

**Comment by vcunat** [comment]
Which packages using qt4 do you mean to target? I would guess they might often better be migrated to qt5.

**Comment by vandenoever** [comment]
Upgrading packages to qt5 is a lot of work and might not even be desired for upstream packages. The package which would need the newer qtwebkit is blink.
I would think that the adapted branch has a drop in replacement for the webkit directory.

**Comment by vcunat** [comment]
Blink is a fork of WebKit. Why would it depend on qtwebkit?

**Comment by vandenoever** [comment]
Blink here is not the webengine blink, but the voip application blink.
http://icanblink.com/
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/instant-messengers/blink/default.nix

**Comment by vcunat** [comment]
Aha, nice coincidence :-)

**Comment by vandenoever** [comment]
Yeah, the concrete issue is that an extension to blink has been developed and is about to be released as foss. The extension lets you edit collaboratively on a text document while doing chat or voip call, via the same connection. This is using webodf.
Unfortunately, the webkit in qt4 is not up to the task.

**Comment by Profpatsch** [comment]
(triage) Qt has seen many changes. Close?

**Comment by rasendubi** [comment]
(triage) is anyone still interested in this? we don't know the current status, so I will close the issue in a month if nobody replies back.

**Comment by Profpatsch** [comment]
Let’s just close it now, since I already asked a quarter year ago. ;)
