### ISSUE TITLE
Bring back modulesPath

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8188]
I'm thinking of bringing this line back:

https://github.com/NixOS/nixpkgs/commit/f69ce50529c5108d4dababfd221652ace55264bd#diff-e29cca50467118cb72b2d2c8f97cd7caL60

and getting rid of nixos/modules/misc/extra-arguments.nix. Does anyone have objections? I fully buy the ability to pass arguments in the module system using `_module.args`, but if it doesn't work (and breaks in a horrible way) for the most common use case (`modulesPath` in imports), that seems bad and the cost of restoring the old way seems pretty low.

Anyone have objections? I can make the change if nobody objects. Ideally, I'd like it in 15.06, since it's getting in the way of some work I'm trying to squeeze into 15.06.

cc @nbp @shlevy @edolstra

**Comment by shlevy** [comment]
IMO our only choices are to do this or to set as a prerequisite (perhaps enforced using `scopedImport`) that `<nixpkgs/nixos/modules>` points there. No strong preference either way.

**Comment by edolstra** [comment]
@copumpkin Yeah, this is probably the best solution.

**Comment by copumpkin** [comment]
Cool! Do any of you know of VM tests that would suitably make sure I don't break anything too obvious by making that change? I'd obviously rather not make the change and then discover a week from now that I broke someone's key use case :smile: 

I'll be making the change this evening at this rate.

**Comment by shlevy** [comment]
@edolstra Any thoughts on having `eval-config.nix` set `modulePath` using scopedImport? That way `lib/modules.nix` stays NixOS-independent. But not a huge difference IMO.

**Comment by edolstra** [comment]
I don't see how adding `modulesPath` back could break anything.

**Comment by shlevy** [comment]
Famous last words! :grinning: But I agree, as long as it evaluates at all it's almost certainly fine.

**Comment by edolstra** [comment]
@shlevy That sounds more complicated than the one-liner suggested by @copumpkin.
