### ISSUE TITLE
.tnix file extension for nix files whose only purpose is to be copied elsewhere?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8190]
I'm trying to systematize our common wisdom about when it's okay to see `<nixpkgs>` and other `NIX_PATH` paths in nixpkgs. It seems like it's okay iff the file is going to get copied into a target filesystem. `import` could refuse to load such files, or issue warnings if it does. Someone could grep for `<path>` in nixpkgs periodically and make sure it only appears in .tnix files.

Is that silly?

**Comment by copumpkin** [comment]
The more hardcore version of this is that only .tnix files are allowed to use angle brackets at all. That could be a nix evaluator flag.

**Comment by joepie91** [comment]
Disallowing angle brackets in non-`.tnix` files would interfere with systems running packages from multiple sources, where a secondary source would rely on one or more `nixpkgs` packages. An example would be [this](https://github.com/ArchiveTeam/nix) work-in-progress repository.

**Comment by grahamc** [comment]
Closing after about a year of inactivity.
