### ISSUE TITLE
ghc has a hidden run-time dependency on binutils

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#8192]
ghc won't work without `binutils` and currently users have to install that package to compile. This should be fixed or documented.

**Comment by copumpkin** [comment]
I assume it's just using tools from binutils based on $PATH? That seems easily fixable, if so, and seems better than documenting it :smile:

**Comment by peti** [comment]
I'm not so sure it's that easy. Cabal searches for tools like `ar` during the configure phase. I'm not sure what it does with those paths, really, but chances are that wrapping `ghc` is not good enough to guarantee a working build.

**Comment by copumpkin** [comment]
Oh, I was expecting a (relatively minor) patch to be needed. Basically, tracking down where we use those tools and inserting hard references to store paths.

**Comment by peti** [comment]
It's possible that it's that simple. I just don't know. Someone will have to try this and figure out whether it works or not. Maybe it's sufficient to patch the `$out/bin/ghc` script to add `binutils` to `$PATH` before executing the real `ghc` binary.

**Comment by Fuuzetsu** [comment]
Does it really need binutils? What's the error without it?

**Comment by peti** [comment]
@Fuuzetsu, http://permalink.gmane.org/gmane.linux.distributions.nixos/17337.

**Comment by peti** [comment]
A fix is in `staging`: d3ac5c534de18caa487ab3ee341f24a452027294.
