### ISSUE TITLE
Package request: Session Messenger

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#81927]
**Project description**
"Session is an end-to-end encrypted messenger that removes sensitive metadata collection, and is designed for people who want privacy and freedom from any forms of surveillance."
Session is a fork of [Signal](https://www.signal.org/) designed to be used on top of the [Loki Network](https://loki.network/) for onion routing and storage. 

The existing `signal-desktop` package can probably be adapted for this.
**Metadata**

* homepage URL: https://getsession.org/
* source URL: https://github.com/loki-project/session-desktop
* license: GPL3 ...
* platforms: linux, electron ...

**Comment by bqv** [comment]
Is there a usable appimage in the mean time?

**Comment by mehlon** [comment]
@bqv you can use my in-progress pull request https://github.com/NixOS/nixpkgs/pull/83698 , which currently extracts the pre-built AppImage.
Just clone the repository, checkout the `session-manager` branch, and run `nix-env -iA session-desktop -f .` in the repository directory.

**Comment by onny** [comment]
I guess it is already packaged https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/instant-messengers/session-desktop-appimage/default.nix#L17 ? Can we close this?

**Comment by ryneeverett** [comment]
Resolved via #135831.
