### ISSUE TITLE
lambdabot build broken due to failing patch on misfortune

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#8195]
❯ nix-env -I ~/nixpkgs -i lambdabot                         

> (...)
> output path ‘/nix/store/95wpvn67nypqpmiq9cqjzsb9jjb91flw-c41aa40ed63b74c069d1e4e3caa8c8d890cde960.patch’ should have sha256 hash ‘1gs8p89d1qsrd1qycbhf6kv4qw0sbb8m6dy106dqkmdzcjzcyq74’, instead has ‘0h1lx4z15imq009k0qmwkn5l3hmigw463ahvwffdnszi2n618kpg’
> cannot build derivation ‘/nix/store/ikbzsz4d2jmp1in1r8m4s9q0z9ivnjb3-haskell-mueval-0.9.1.1.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/xqr3jsa2n241ajw4izwl4y108v1yqcfj-haskell-lambdabot-haskell-plugins-5.0.2.1.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/hgww83ybwiccyarjyq6hal8y0lglpxjf-mueval-env.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/9nzsgs5rafwp2llmynswd9xqpr0b1cv6-lambdabot-5.0.2.2.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/9nzsgs5rafwp2llmynswd9xqpr0b1cv6-lambdabot-5.0.2.2.drv’ failed

**Comment by peti** [comment]
Attempts to build `lambdabot` in the current `master` branch look like this:

    $ nix-build ~/src/nixpkgs -A haskellPackages.lambdabot
    error: Package ‘haskell-mueval-0.9.1.1’ in ‘pkgs/development/haskell-modules/hackage-packages.nix:89867’ is marked as broken, refusing to evaluate.

**Comment by peti** [comment]
The modified patch checksum was fixed in 8cc5c08808b257f2b99582cc1112cd37426331e5.
