### ISSUE TITLE
meta.timeout has no effect with nix-build

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#81963]
**Describe the bug**
The build was not stopped when it took longer than the timeout value.

**To Reproduce**
1. create file

test.nix
```
with import <nixpkgs> {};

runCommand "test" { meta.timeout = 2; }
  ''
  sleep 4
  echo waited 4 seconds instead of 2!
  touch $out
  ''
```

2. run file `time nix-build test.nix`
3. see output

```
these derivations will be built:
  /nix/store/hhg321kp7xgmrryiwsia78mcr0i9l474-test.drv
building '/nix/store/hhg321kp7xgmrryiwsia78mcr0i9l474-test.drv'...
waited 4 seconds instead of 2!
/nix/store/b0mdw1wscm3z01f8cppc9kng8j06n506-test

real	0m5,272s
user	0m0,233s
sys	0m0,045s

```
**Expected behavior**

nixpkgs manual states:

>A timeout (in seconds) for building the derivation. If the derivation takes longer than this time to build, it can fail due to breaking the timeout.

**Additional context**
This came up in https://github.com/NixOS/nixpkgs/pull/75117

@jtojnar said there:

>I think `meta.timeout` only works on Hydra.

If that is the case, it would be nice to add this feature also to other tools
or at least document that this setting is only used by Hydra.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2196.00115f2f9c7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.2196.00115f2f9c7, nixos-hardware, nixos-unstable-20.09pre215702.1459b34afa9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by doronbehar** [comment]
> > I think meta.timeout only works on Hydra.
>
>If that is the case, it would be nice to add this feature also to other tools
or at least document that this setting is only used by Hydra.

Maybe file a Nix issue?

**Comment by puffnfresh** [comment]
Not a nixpkgs issue.
