### ISSUE TITLE
We need different flavors of qemu

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8210]
For VM tests on a headless machine, it's frustrating to have to wait for llvm -> clang -> mesa -> SDL -> qemu to build when they're completely unused. On the other hand, if someone is doing live VM work on a   "headful" machine, they'll probably want the graphics stuff.

@wkennington agrees!

**Comment by edolstra** [comment]
I agree, I've wanted to add a basic QEMU variant for a while. We could even appropriate qemu_kvm for this purpose.

Indeed the only problem is interactive use of the test driver script. Perhaps we could emit different scripts for interactive and non-interactive use.

(Slightly related, I think it should be possible to drop the clang dependency. Libclc apparently also builds with gcc.)

**Comment by Profpatsch** [comment]
(triage) what’s the status? Any new leads?

**Comment by tomberek** [comment]
close

**Comment by copumpkin** [comment]
We still need it don't we? Just because nobody's done anything doesn't make it any less useful or necessary, right?

**Comment by Profpatsch** [comment]
I don’t see any action items in this issue, so nothing is ever going to happen here.
