### ISSUE TITLE
Option for generators.toINI to allow duplicate keys (in the form of a list)

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#82205]
**Describe the bug**
I'd like the `generators.toINI` function to accept lists and produce duplicate keys, like so:

```
settings = {
some_key = "b";
another_key = [ "one" "two" "three" ];
};
```
which would yield:
```
some_key=b
another_key=one
another_key=two
another_key=three
```

**Comment by aanderse** [comment]
ping @Infinisil to see if he has any interest in implementing this :heart:

**Comment by Infinisil** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/82208 :)
