### ISSUE TITLE
Update riot-desktop & riot-web to v1.5.12

### ISSUE THREAD

**Issue by greghab** [NixOS/nixpkgs#82277]
**Describe the bug**
Package is outdated, and sign-in does not work (it's unusable).

**To Reproduce**
1. type in credentials, click sign-in button
2. see that nothing happens.

**Expected behavior**
Should sign in.

**Additional context**

Currently out-of-date package versions on NixOS are `riot-desktop-1.5.0` and `riot-web-1.5.10`

On arch linux, version of package is `1.5.12-1`, sign in works fine.

https://www.archlinux.org/packages/?sort=&q=riot-&maintainer=&flagged=

https://riot.im/download/desktop/

**Comment by eadwu** [comment]
https://github.com/NixOS/nixpkgs/pull/81849

**Comment by rnhmjoj** [comment]
Closing since the package was updated and backported to 20.03.
