### ISSUE TITLE
Octoprint broken due to Python 2.7 EOL

### ISSUE THREAD

**Issue by WhittlesJr** [NixOS/nixpkgs#82292]
**Describe the bug**
Similar to #71940, but probably more pernicious as Django is still a requirement:

```
Django-2.2.10 not supported for interpreter python2.7
```

The recent Octoprint 1.4.0 release supports Python 3. Update to Octoprint 1.4.0 (non-trivial, but WIP PR attached. I need some help with this one.)

**To Reproduce**
1. add `services.services.octoprint.enable = true` to your config
2. `nixos-rebuild switch`

**Expected behavior**
Octoprint builds

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.22, NixOS, 20.09pre214776.ca353185084 (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre214776.ca353185084"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by gebner** [comment]
Fixed by #82392, which upgrades octoprint to 1.4.0 and python 3.
