### ISSUE TITLE
Fonts got messed up on failing NixOS upgrade

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#82388]
**Describe the bug**

After a failing NixOS build/switch, the bug appeared in Emacs so that some normal characters were broken (see #82306). I'm guessing the font cache was somehow in a corrupted state.

**To Reproduce**

I don't know exactly how to reproduce and I cannot recall exactly what I had done. Not sure if this even can be easily reproduced because it's probably related to system state. But anyway, it's worrying that if NixOS build/switch fails to build some packages, the system state can be corrupted.

So, what I had done:

1. I updated my nixos-unstable channel.
2. `nixos-rebuild switch` or `nixos-rebuild build` (can't remember which one I used) complained that I have a nonfree font Symbola chosen. So, I removed that font from my configuration.nix.
3. I tried rebuilding again. However, after a short while, the rebuilding failed because building of a few packages failed (namely, electron-cash and monero-gui).
4. So, I thought, let's fix those later and continue with my current system. Then, my font was broken in Emacs.

So, my question is: Is it possible that `nixos-rebuild` touches the font cache even if the rebuild fails because some packages fail to build? I can't come up with any other reason why the fonts suddenly broke even though I didn't actually switch my system in the end.

Finally, when I resolved all those broken package issues by disabling them, I ran `nixos-rebuild switch` again, and then everything got fixed. So, it definitely seemed to me that the failing build/switch somehow messed up the font cache, and after actually finishing the build/switch successfully, everything worked. Or do you have any other ideas what could have happened?

If you think this cannot be true and there's no such bug, feel free to close the issue. This is more like a question that could someone check if something like this can happen, that is, can you easily see this kind of issue in the rebuild procedure.

**Expected behavior**

Running `nixos-rebuild switch` shouldn't affect the system state if it fails because some packages fail to build.

**Metadata**

The metadata of my final working system:

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.23, NixOS, 20.09.git.82b54d49066 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
The question is, in what stage did the build fail... and provided an stderr of the build it would have been possible to fetch some clues. But since this has happened so long ago and you probably can't reproduce it now no more then before. I see no point in leaving this open. Sorry, please reopen if you can reproduce.
