### ISSUE TITLE
nixos/mysql: Error first init mysql databases

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#82428]
**Describe the bug**
Erorr  first init mysql databases if use package mariadb.server builded `withoutClient = true`

**To Reproduce**
1. Apply this patch
```
diff --git a/nixos/tests/mysql.nix b/nixos/tests/mysql.nix
index 924bac84e26..a4a245f4741 100644
--- a/nixos/tests/mysql.nix
+++ b/nixos/tests/mysql.nix
@@ -26,6 +26,13 @@ import ./make-test-python.nix ({ pkgs, ...} : {
       { pkgs, ... }:

       {
+        nixpkgs.overlays = [
+          (self: super: {
+            mariadb = super.mariadb.override {
+              withoutClient = true;
+            };
+          })
+        ];
         users.users.testuser = { };
         users.users.testuser2 = { };
         services.mysql.enable = true;

```
2. run command `nix-build nixos/tests/mysql.nix`

**Expected behavior**
Error running this command
```
cat /nix/store/36wz42cljwgx94kba5pgfavrkjw57g61-mysql_init.sql | /nix/store/9zjrpl0blyi7rzlzsd2nx4pjjacgpybx-mariadb-server-10.3.22/bin/mysql -u root -N
    rm /tmp/mysql_init
fi
```
```
l /nix/store/9zjrpl0blyi7rzlzsd2nx4pjjacgpybx-mariadb-server-10.3.22/bin/mysql
ls: невозможно получить доступ к '/nix/store/9zjrpl0blyi7rzlzsd2nx4pjjacgpybx-mariadb-server-10.3.22/bin/mysql': No such file or directory

```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.9-hardened, NixOS, 20.09.git.ee6a3c3bd0a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre216451.ce961fad160"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

cc @aanderse

**Comment by aanderse** [comment]
Thanks for reporting @Izorkin! Any of the `ensureDatabases`, `ensureUsers`, `initialDatabases`, ` initialScript` options require a client so I'm guessing the best we can do is document this.

Any other ideas @flokli?

**Comment by flokli** [comment]
`withoutClient` is an argument that is only available for the `mariadb` derivation, and is not exposed in `all-packages.nix` - so it's hard people stumble over this by accident. They need to explicitly set a global package override.

Also,

> '/nix/store/9zjrpl0blyi7rzlzsd2nx4pjjacgpybx-mariadb-server-10.3.22/bin/mysql': No such file or directory

as error message by itself should already be clear enough, especially when looking at the system configuration.

I don't consider this a bug. It works as intended - if you override mysql globally to not contain the client components, you'd have to expect client operations to fail.


@Izorkin, given you added `withoutClient` by yourself in c8488b913a285b72bb9dc090f2903762b11ac9ce, and it doesn't really work properly anyways, what about removing that argument?

**Comment by Izorkin** [comment]
When I made this parameter, I did not test database creation on first run.
I wanted to split mariadb into components - server and client. Example in another distribution: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mariadb
But due to the different file locations, occur such errors.

Is this variant bad? (Not worked witn MySQL 8.0)
```
diff --git a/nixos/modules/services/databases/mysql.nix b/nixos/modules/services/databases/mysql.nix
index 8d520b82fb5..d1f06e2b328 100644
--- a/nixos/modules/services/databases/mysql.nix
+++ b/nixos/modules/services/databases/mysql.nix
@@ -398,7 +398,7 @@ in
                         # Execute initial script
                         # using toString to avoid copying the file to nix store if given as path instead of string,
                         # as it might contain credentials
-                        cat ${toString cfg.initialScript} | ${mysql}/bin/mysql -u root -N
+                        cat ${toString cfg.initialScript} | ${mariadb.client}/bin/mysql -u root -N
                       ''}

                     rm /tmp/mysql_init
```

**Comment by aanderse** [comment]
If you use `mariadb.client` then there no reason to split package because you install both anyways. Arch Linux probably doesn't offer `initialScript` option so it makes sense.

**Comment by flokli** [comment]
What was the initial idea of having a server without the client binaries? Closure size reduction?
In that case pulling in the client anyways in a separate derivation doesn't make much sense.

I understand we want to have a separate client without pulling in server components (and we have that for mariadb), but I having the server without client isn't much of use.

There's usually enough storage space on the database server to also ship the client binaries, and they are needed for most options in the mysql module, as well as for local administration / backups anyways.

I'm pretty much for removing the `withoutClient` argument. It causes a lot of confusion when uses for arguable benefit.
