### ISSUE TITLE
nixos.iso_minimal.i686-linux blocking channel again

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#82435]
The [build](https://hydra.nixos.org/build/114424234) is failing on `/nix/store/5mqkj30x927kvzlx64qym4whm8kg063q-i686-unknown-linux-musl-stage-static-gcc-debug-9.2.0.drv` with the following message:

```
/build/build/./gcc/xgcc -B/build/build/./gcc/ -xc -nostdinc /dev/null -S -o /dev/null -fself-test=../../gcc-9.2.0/gcc/testsuite/selftests
cc1: error: no include path in which to search for stdc-predef.h
cc1: note: self-tests are not enabled in this build
echo timestamp > s-selftest-c
```

Possibly the same issue as https://wiki.debian.org/toolchain/BootstrapIssues#stdc-predef.h_not_found.

Dependency graph:

![Screenshot from 2020-03-12 21-39-16](https://user-images.githubusercontent.com/705123/76565307-924d9f80-64aa-11ea-8802-e0eba51fbd78.png)

**Comment by LEXUGE** [comment]
As @jtojnar said in IRC, a per-arch channel could be better because therefore there would be no i368 tests failures to block x86 users.

**Comment by vcunat** [comment]
I thought the failure is:
```
builder for '/nix/store/5mqkj30x927kvzlx64qym4whm8kg063q-i686-unknown-linux-musl-stage-static-gcc-debug-9.2.0.drv' failed to produce output path '/nix/store/awrybl6dgpcs01yq89vjixacd03hza3h-i686-unknown-linux-musl-stage-static-gcc-debug-9.2.0-lib'
```
but I haven't looked into details yet.

Splitting archs has both advantages and disadvantages.  In this particular platform pair, note that x86_64 users commonly do have some i686 packages.

**Comment by vcunat** [comment]
Anyone, feel free to investigate deeper and find a better fix.  I've been delaying this attempt for days, in hope that someone else will take better care of it.
