### ISSUE TITLE
Home-assistant package integration test failure

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#82441]
**Describe the bug**

Related to ZHF: #80379 

It seems this test is broken because attribute sets in nix are sorted by default.

I've done some tests and found out that not specifying `--preserve-key-order` changes the order of the keys in the json and thus also breaks the conversion back to yaml, because homeassistant expects the yaml to be sorted.

```
$ nix-shell -p remarshal
$ cat tmp.yaml 
homeassistant:
  auth_providers:
    - type: legacy_api_password
      api_password: http_password

$ yaml2json tmp.yaml | json2yaml
homeassistant:
  auth_providers:
  - api_password: http_password
    type: legacy_api_password

$ yaml2json --preserve-key-order tmp.yaml | json2yaml --preserve-key-order
homeassistant:
  auth_providers:
  - type: legacy_api_password
    api_password: http_password
```

If the `- type: ...` is not the first key, this behavior breaks.
Because the builtins.toJSON builtin is used to create the first JSON and I already tested with setting `--preserve-key-order`, I think the nix attribute sets are ordered and that's causing this issue.

**To Reproduce**
1. Build a VM with the following file:
```
# vm.nix
{ pkgs, lib, config, ... }:
{
  services.home-assistant = {
    enable = true;
    config = {
      homeassistant = {
        name = "Home";
        time_zone = "UTC";
        latitude = "0.0";
        longitude = "0.0";
        elevation = 0;
        auth_providers = [
          {
            type = "legacy_api_password";
            api_password = "test1234";
          }
        ];
      };
    };
  };

  users.users.root.initialPassword = "root";
}
```
2. Run `cat /var/lib/hass/configuration.yaml`
3. See the `type` and `api_password` in the incorrect order.

**Expected behavior**

The original order as specified in the nix file is preserved, instead of ordering alphabetically (?).

**Other information**

Maybe #75584 will solve this or help fix this by allowing flags or something.
Possibly related to #81986.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.7-hardened, NixOS, 20.09pre215947.82b54d49066 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(rick): `""`
 - channels(root): `"nixos-20.09pre215947.82b54d49066, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Ping @dotlambda

**Comment by matt-snider** [comment]
I also came across this since I'm trying to fix another bug in the home-assistant module. I can confirm that setting `--preserve-key-order` does not work, and that the file generated by `builtins.toJSON` already has incorrect ordering.

**Comment by Mic92** [comment]
Mhm. I am not quite sure how to solve this.

**Comment by Mic92** [comment]
Is this only a problem for `auth_providers` or are other parts also affected?

**Comment by Infinisil** [comment]
From [the YAML spec](https://yaml.org/spec/1.2/spec.html#id2765608):

> #### 3.2.2.1. Keys Order
> In the representation model, mapping keys do not have an order. To serialize a mapping, it is necessary to impose an ordering on its keys. This order is a serialization detail and should not be used when composing the representation graph (and hence for the preservation of application data). In every case where node order is significant, a sequence must be used. For example, an ordered mapping can be represented as a sequence of mappings, where each mapping is a single key: value pair. YAML provides convenient compact notation for this case. 

So this is a problem with home-assistant not being compliant with the YAML spec. This should ideally be fixed upstream.

**Comment by Mic92** [comment]
I reported this upstream as well: https://github.com/home-assistant/core/issues/33466

**Comment by Mindavi** [comment]
Ok, so probably it hasn't got anything to do with the ordering of the keys. I've tried it in docker just now (I don't know why I didn't think about that earlier...), but in both cases I get 'Unauthorized' responses. I've made a bug report against home-assistant to request more information, because I'm not sure why it's not working as expected. Issue is linked in.

**Comment by Mindavi** [comment]
I've created a minimal 'config' directory which can be included in the home-assistant test (but not sure how to do so).
[config.zip](https://github.com/NixOS/nixpkgs/files/4428968/config.zip)

Credentials for the accounts:

username: `testuser`
password: `testing`
long-lived access token (valid for 10yrs from yesterday): `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxOTgxYzBiMDUyY2M0NGY5YmZkMWJiMTE3ZDAwMTYzMCIsImlhdCI6MTU4NTg2MDM1NSwiZXhwIjoxOTAxMjIwMzU1fQ.wDx84NmvlfJjyCE9mK70Njx-1luavPECcPk6mU-a1xM`

**Comment by Mic92** [comment]
Thanks for the research. If we would not need the token, we could just copy the onboarding file from `.storage`:

```
{
    "data": {
        "done": [
            "user",
            "core_config",
            "integration"
        ]
    },
    "key": "onboarding",
    "version": 3
}
```

**Comment by Mindavi** [comment]
Still important to me, but unsure how to solve this. When I find the time and feel like it I'll have an IRC discussion or something like this.

**Comment by Mindavi** [comment]
Still not sure how to solve this, and looking at hydra this still fails... :(

**Comment by Mindavi** [comment]
I don't really have interest in pursuing this. I'll close this. Open a new issue or (preferably) a PR if you want to see this fixed :smile:.
