### ISSUE TITLE
encountered with ` called with unexpected argument ‘extension’ ` when I use this cutting edge version

### ISSUE THREAD

**Issue by TorosFanny** [NixOS/nixpkgs#8245]
I ran `qs@BF:~/Programs/nixpkgs$ nix-env -qa -f .` under my forked directory. But nix exited with unexpected `error: anonymous function at "/home/qs/Programs/nixpkgs/pkgs/development/haskell-modules/default.nix":1:1 called with unexpected argument ‘extension’, at "/home/qs/Programs/nixpkgs/lib/customisation.nix":58:12`.

I tried both `nix-env -qa -f .` and `nix-env -qa` with both nix-1.8 and nix-1.9-pre respectively and all of them gave the same error prompt.

My channel list is: https://nixos.org/channels/nixpkgs-unstable.

It is very suspicious that this issue has some thing to do with haskell-modules, since I usually use cabal2nix to get newer version of haskell packages.

**Comment by peti** [comment]
The extension function that's used in your `~/.nixpkgs/config.nix` file has been renamed to `overrides`. https://nixos.org/wiki/Haskell has more information.
