### ISSUE TITLE
Vivaldi widevine outdated and/or broken

### ISSUE THREAD

**Issue by FrauH0lle** [NixOS/nixpkgs#82469]
**Describe the bug**
Vivaldi in NixOS 19.09 is a bit outdated and the `ffmpeg-codecs `and `widevine` plugins as well. 
NixOS Unstable is more up-to-date but `widevine` will also not work, e.g. on Netflix.

I have created updated packages locally which I would like to share. With them, Vivaldi is able to play videos from e.g. Netflix.

Required changes in `vivaldi/default.nix`

[Line 84](https://github.com/NixOS/nixpkgs/blob/b6ae8193edd5fb5188565d6163c86e76a096a500/pkgs/applications/networking/browsers/vivaldi/default.nix#L84) : 
```nix
mkdir -p $out/opt/google/chrome/
ln -sf ${vivaldi-widevine}/share/google/chrome/WidevineCdm $out/opt/google/chrome/WidevineCdm
ln -sf ${vivaldi-widevine}/share/google/chrome/WidevineCdm $out/opt/${vivaldiName}/WidevineCdm
```
Otherwise Vivaldi seems not to able to find the `widevine` plugin

Furthermore, I have updated the `ffmpeg-codecs `and `widevine` plugins, following their corresponding AUR packages:

```nix
{ stdenv, fetchurl
, dpkg
}:

stdenv.mkDerivation rec {
  name = "chromium-codecs-ffmpeg";
  version = "80.0.3987.87";
  _ubuver="0ubuntu0";
  _ubudist="18.04.1";

  src = fetchurl {
    url = "http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg-extra_${version}-${_ubuver}.${_ubudist}_amd64.deb";
    sha256 = "0gjqn1sbamb79acwinnyrcmigi1q3swh7rkq8h4h49pm8vwl00zy";
  };

  buildInputs = [ dpkg ];

  unpackPhase = ''
    dpkg-deb -x $src .
    find .
  '';

  installPhase = ''
    install -vD usr/lib/chromium-browser/libffmpeg.so $out/lib/libffmpeg.so
  '';

  meta = with stdenv.lib; {
    description = "Additional support for proprietary codecs for Vivaldi";
    homepage    = "https://ffmpeg.org/";
    license     = licenses.lgpl21;
    maintainers = with maintainers; [ betaboon lluchs ];
    platforms   = [ "x86_64-linux" ];
  };
}
```

```nix
{ stdenv, fetchurl
, unzip, dpkg,
}:

stdenv.mkDerivation rec {
  name = "widevine";
  version = "4.10.1610.0";
  _chrome_ver="80.0.3987.100";

  src = fetchurl {
    url = "https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${_chrome_ver}-1_amd64.deb";
    sha256 = "0l7a8nkhq7qy8lrl20icr169fni1nvkvvxibqipzjzmj7hxdxbpr";
  };

  buildInputs = [ unzip dpkg ];

  unpackPhase = ''
    dpkg --fsys-tarfile ${src} | tar -x --no-same-permissions --no-same-owner
    mv -v opt/google/chrome/WidevineCdm WidevineCdm
  '';

  installPhase = ''
    install -vD WidevineCdm/manifest.json $out/share/google/chrome/WidevineCdm/manifest.json
    install -vD WidevineCdm/LICENSE $out/share/google/chrome/WidevineCdm/LICENSE
    install -vD WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so $out/share/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
  '';

  meta = with stdenv.lib; {
    description = "Widevine support for Vivaldi";
    homepage = "https://www.widevine.com";
    license = licenses.unfree;
    maintainers = with maintainers; [ betaboon ];
    platforms   = [ "x86_64-linux" ];
  };
}
```

With these changes, everything seems to work as expected

**Screenshots**
Widevine module:
![2020-03-13-093230_443x132_scrot](https://user-images.githubusercontent.com/10484857/76603780-e0e05580-650d-11ea-92b6-8ac3965a40ff.png)

Netflix playing
![2020-03-13-093308_1892x1024_scrot](https://user-images.githubusercontent.com/10484857/76603824-f05f9e80-650d-11ea-9d02-fc4b95e8e8e0.png)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```sh
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.108, NixOS, 19.09.2220.92231f4f32f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"home-manager-19.09, nixos-19.09.2220.92231f4f32f, nixos-unstable-20.09pre215947.82b54d49066, nixpkgs-unstable-20.09pre216190.6b6f9d769a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eadwu** [comment]
Is it possible I missed some commits when asking for backports? I seem to find widevine in `vivaldi://components`, though I am running the latest snapshot.

While I believe `$out/opt/google/chrome/WidevineCdm` would work, it's because it's the fallback path from Vivaldi to detect the Chrome installation of widevine. Vivaldi's actually uses `ln -fs /opt/google/chrome/WidevineCdm "$VIVALDI_INSTALL_DIR/WidevineCdm"` in it's `update-widevine` script.

```
Widevine Content Decryption Module - Version: 4.10.1582.1
Status - Up-to-date
```

Anyway, I suggest you open a PR while waiting to see how much people are affected by this.

**Comment by JoshuaFern** [comment]
I believe Vivaldi updated recently and ffmpeg-codecs stopped working. Widevine untested.

**Comment by ajs124** [comment]
#102245 updated to a recent release, but I don't think anyone is backporting these right now.

**Comment by raspher** [comment]
Have issues related to widevine in nixos 21.11. YouTube works, with sound, but it's not using the default player.

Vivaldi showed me alert -> https://help.vivaldi.com/desktop/media/html5-proprietary-media-on-linux/ and media linked in this help page IS NOT working at all, it stuck at 0:00.

**Comment by pshirshov** [comment]
I'm not sure if this is relevant, though vivaldi-widevine seems to be broken for now:

```
error: hash mismatch in fixed-output derivation '/nix/store/wlyrs5f0lj05n33d3rfpmysbp31cllip-4.10.2449.0-linux-x64.zip.drv':
         specified: sha256-XZuXK3NCfqbaQ1tuMOXj/U4yJC18futqo1WjuMqMrRA=
            got:    sha256-vsr6eymKqU2Y6HM4DPHnUfVkB2BQ1HSSWvk1tNhUA5Y=
error: 1 dependencies of derivation '/nix/store/4ldxyq0bd8abl98mjc0rf2chwhis4p1s-widevine-4.10.2449.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3dq9aayzx2i0ajnxr672qkqjxpp12dcl-system-path.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-amdvlk-2022.Q2.1.drv-0/amdvlk-src/drivers/llvm-project/llvm/test/CodeGen/VE/VELIntrinsics': Directory not empty
error: 1 dependencies of derivation '/nix/store/3nx96hy75q8h1r9v6xr6myqmf08im6z8-nixos-system-pavel-nix-22.05.20220517.7502133.drv' failed to build
```
