### ISSUE TITLE
obs-ndi not working

### ISSUE THREAD

**Issue by Sohalt** [NixOS/nixpkgs#82506]
## Issue description
The obs-ndi plugin seems to be broken.

### Steps to reproduce
Install obs-studio and obs-ndi from unstable.
"Install" the plugin as described in https://github.com/NixOS/nixpkgs/blob/c95664665d15ccbf4a490c3db7c07b00925788a1/pkgs/applications/video/obs-studio/obs-ndi.nix
```
nix-env -f "<nixpkgs>" -iA obs-ndi
mkdir -p ~/.config/obs-studio/plugins/bin
ln -s ~/.nix-profile/lib/obs-plugins/obs-ndi.so ~/.config/obs-studio/plugins/bin/
```
When starting OBS the NDI settings don't show up under "Tools" and also not under Filters.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.103, NixOS, 19.09.git.177bc66 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2229.d7843c8add6, unstable-20.09pre215947.82b54d49066"`
 - channels(sohalt): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

**Comment by yvt** [comment]
The correct location seems to be `~/.config/obs-studio/plugins/obs-ndi/bin/64bit/obs-ndi.so` (replace `64bit` with `32bit` on a 32-bit system).

**Comment by TikhonJelvis** [comment]
Just ran into this issue myself, and @yvt's suggested fix worked. I also linked in `locale/en-US.ini` so that the menu labels showed up correctly.

I'm using home-manager, so here's the code I used instead of a manual `ln`:

```
# Managing the OBS-NDI plugin.
#
# Could be extended into an "OBS plugin" set of modules, probably...
home.file.".config/obs-studio/plugins/obs-ndi/bin/64bit/obs-ndi.so".source =
  "${pkgs.obs-ndi}/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so";
home.file.".config/obs-studio/plugins/obs-ndi/data/locale/en-US.ini".source =
  "${pkgs.obs-ndi}/share/obs/obs-plugins/obs-ndi/locale/en-US.ini";
```

**Comment by fpletz** [comment]
This should work now, tested with the recent OBS major version bump.
