### ISSUE TITLE
where is generate-shell.nix to be found?

### ISSUE THREAD

**Issue by timsears** [NixOS/nixpkgs#82500]
## Issue description

in `doc/languages-frameworks/r.section.md` it is not clear where the user should find a file called `generate-shell.nix` used in the following: 

~~~
nix-shell generate-shell.nix
~~~

This is a documentation issue.

**Comment by timsears** [comment]
The docs got moved from `development/r-modules`, where the referenced code resides, so that explains why it's confusing. Thinking about the right doc edits...

**Comment by abathur** [comment]
Looks like this was documented in #139312
