### ISSUE TITLE
GHC-8.6.5 can't build time-compat due to dependency conflict

### ISSUE THREAD

**Issue by maksbotan** [NixOS/nixpkgs#82501]
## Issue description

I tried a simple thing -- open `nix-shell` with GHC 8.6.5 and `cabal-install`. However, it fails to build `time-compat` package due to dependency conflict:

```
Configuring time-compat-1.9.2.2...
CallStack (from HasCallStack):
[CUT]
Setup: Encountered missing dependencies:
base-compat >=0.10.5 && <0.11
```

This happens both on macOS and Linux (Gentoo, not NixOS). But GHC 8.8.2 is okay.

Forcing older `base-compat` in `shell.nix` helps:

```nix
with import <nixpkgs> {};
let h = haskell.packages.ghc865.extend (self: super: {
  base-compat = self.callHackage "base-compat" "0.10.5" {};
  base-compat-batteries = self.callHackage "base-compat-batteries" "0.10.5" {};
}); in
let ghcWithCabal = h.ghcWithPackages (p: [p.cabal-install]); in
mkShell {
  buildInputs = [ghcWithCabal];
}
```

### Steps to reproduce

This fails:

```console
$ nix-shell '<nixpkgs>' -p 'haskell.packages.ghc865.ghcWithPackages (p: [p.cabal-install])'
```

This succeeds:

```console
$ nix-shell '<nixpkgs>' -p 'haskell.packages.ghc865.ghcWithPackages (p: [p.cabal-install])'
```

## Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(maksbotan): `"nixpkgs-20.09pre216412.04d6123309f"`
 - nixpkgs: `/Users/maksbotan/.nix-defexpr/channels/nixpkgs`
```

**Comment by cdepillabout** [comment]
@maksbotan Now that `master` is based on LTS-15 (GHC-8.8), the GHC-8.6 packages are no longer really being maintained.

Here's a couple things you could do if you're interested in having this work:

1. Just go back to 19.09.  `time-compat` should hopefully be working there?

1. Get upstream to release a new version that is compatible with both ghc-8.6.5 and ghc-8.8.

1. Send an override to nixpkgs to [configuration-ghc-8.6.x](https://github.com/NixOS/nixpkgs/blob/991bbef68351b4aa228f5f763c8d2ded2aeeb84e/pkgs/development/haskell-modules/configuration-ghc-8.6.x.nix) fixing up versions or whatever is required to get everything compiling.

**Comment by cdepillabout** [comment]
I'm going to close this since there hasn't been any activity.  Feel free to re-open if none of the above workarounds worked for you.
