### ISSUE TITLE
show better progress during nix builds

### ISSUE THREAD

**Issue by knupfer** [NixOS/nixpkgs#8252]
considering that upgrades can be quite huge (especially when changing from a channel to git) it would be nice to indicate how many packages have to be installed and how many are already installed

**Comment by vcunat** [comment]
There was some WIP on a curses UI, but it seems stalled https://github.com/qknight/nix-build-view/

**Comment by knupfer** [comment]
this wouldn't need ncurses, it could simply dump that info after each installed package, or behave a bit like apt-get

**Comment by copumpkin** [comment]
Seems like most of the progress we care about would be coming from `nix-build` and/or `nix-env`. `nixos-rebuild` would get it for free if those could provide it.

**Comment by vcunat** [comment]
Thinking of it, that linked project probably didn't use ncurses, just terminal commands.

**Comment by knupfer** [comment]
I've looked up, the linked project uses ncurses, but at the moment it doesn't work and has only an inbuild example.  Besides that, it looks much more pleasing than plain nix.

**Comment by matthiasbeyer** [comment]
@knupfer You could use `-Q` with `nix-env` or `nix-build`.

The linked project has stalled because (as far as I know) changes to have something like the proposed curses UI were rejected on the ML (I wasn't involved in the discussion, just heard about it).

**Comment by vcunat** [comment]
Let's move discussion to the nix repo https://github.com/NixOS/nix/issues/896
