### ISSUE TITLE
nixbld workers should be used in order

### ISSUE THREAD

**Issue by knupfer** [NixOS/nixpkgs#8253]
when installing stuff, it seems to me that the workers are used in random order (at least now I'm installing something with nixbld1, 2, 3 and 10). If they would be used in the proper order, one could identify in a glance how many workers are on work (approximately).

**Comment by vcunat** [comment]
And if one ends sooner than others? Again, closed in favor of "showing better progress" #8252 (although it might be better in nix repo instead anyway).
