### ISSUE TITLE
buildlog is randomly interleaved when using multiple cores

### ISSUE THREAD

**Issue by knupfer** [NixOS/nixpkgs#8254]
it would be much more readable if the workers would print only the entire output of a package (or dependency). While being a bit more boring it would be much easier to understand the output (especially with many cores).

**Comment by vcunat** [comment]
That's more about having an UI and it belongs rather to nix https://github.com/NixOS/nix, like #8252. BTW, it's one of the reasons I almost always use ``-Q``. I then inspect the logs separately by ``nix-store -l /nix/store/foobar.drv``.
