### ISSUE TITLE
Channels are not progressing

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#82547]
**Describe the bug**
None of the channels are progressing despite successful builds of all of its constituents.

https://howoldis.herokuapp.com/

**Comment by vcunat** [comment]
I thought that should've been [fixed about half a day ago](https://hydra.nixos.org/eval/1575603), but apparently it's still broken somehow.

BTW, https://status.nixos.org is nice, for me it's winning over howoldis e.g. thanks to channel-blocker links.

**Comment by FRidh** [comment]
Indeed. So, apparently channels are advancing according to https://channels.nixos.org/, it's just not being reported.
