### ISSUE TITLE
grub + encrypted disks and other quirks

### ISSUE THREAD

**Issue by oxij** [NixOS/nixpkgs#8259]
The commit 159fed47bcfab67d36d4959fb3ac952a7ad9128c made encrypted root somewhat less usable because

    set gfxpayload=keep

line leaves GRUB background where one expects to see an early console with a password prompt from initrd for the encrypted disk(s). I think the abstract grandmother would expect to actually see that prompt there.

That's not to mention that with that it is now impossible to see any early boot errors until KMS kicks in (which for my laptop is at around 60% of the wall boot time), since they are, too, hidden behind the absolutely useless picture.

And not to mention that

    gfxmode=auto

makes the font in GRUB so small on my screen that I won't be able to do anything in GRUB without a magnifying glass when the need arises.

And not to mention that the same commit makes my non-EFI system barf something not pretty to the screen just before the picture is loaded.

I simply reverted that change locally (because f*ck EFI, MBR FTW!), but I suppose it actually makes a difference for some poor EFI users.

/cc @wkennington

**Comment by wkennington** [comment]
Should be fixed by c891134.

**Comment by oxij** [comment]
Yep, it works. Thanks!
