### ISSUE TITLE
dotnet Newtonsoft.Json failes to build on Hydra

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#8260]
http://hydra.nixos.org/build/22994539/nixlog/1

Error:
```
/tmp/nix-build-Newtonsoft.Json-6.0.8.drv-0/Newtonsoft.Json-6.0.8/Src/Newtonsoft.Json/Newtonsoft.Json.csproj (default targets) ->
error : Error building target GetReferenceAssemblyPaths: Access to the path "/nix/store" is denied.
```

Builds fine locally.  How to reproduce?

strace shows xbuild accessing /a, then /a/b, then /a/b/c, etc. when trying to get to /a/b/c/d. 
But that happens for other dotnet libraries, not just for Newtonsoft.Json, so not clear why Newtonsoft.Json fails while the others build fine.

cc @lethalman 

(Not on IRC this week so creating this issue to have the conversation)

**Comment by lethalman** [comment]
I think this kind of errors are likely to be related to nixUnstable. cc @edolstra any idea?

**Comment by obadz** [comment]
Hydra now says it buidls fine... any idea what changed?

http://hydra.nixos.org/build/22994539

**Comment by lethalman** [comment]
Yes @edolstra updated nix on hydra.

On Sat, Jun 13, 2015 at 6:55 AM, obadz <notifications@github.com> wrote:

> Hydra now says it buidls fine... any idea what changed?
>
> http://hydra.nixos.org/build/22994539
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/8260#issuecomment-111670158>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by lethalman** [comment]
Btw that's only the i686 build, I'll wait until I see the x86_64 build before closing this issue.

**Comment by pSub** [comment]
Closing, builds fine on i686 and x86_64.
