### ISSUE TITLE
nixos/opengl: consider enabling S3TC by default

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#82627]
**Describe the bug**

`hardware.opengl.s3tcSupport` currently defaults to false, with an explanation that S3TC texture compression may require a patent license in some locations.

However, all the information I can find online says that S3TC patents expired in 2017, and a lot of major linux distros now ship S3TC on by default. Apparently this makes a significant difference for gaming.

AFAICT, the original S3TC switch dates back to ~2014, so it was correct at the time. But it looks like we could remove it now, and just turn on S3TC whenever OpenGL is enabled - or at least turn it on by default.

**Comment by emilazy** [comment]
Agreed; I could have sworn this had already been done. Opened #82630 to fix.
