### ISSUE TITLE
Strange openjdk8/jre collisions on master

### ISSUE THREAD

**Issue by MP2E** [NixOS/nixpkgs#8262]
Hi there, every time I try installing jdk or jre (which are really openjdk8 and openjdk8.jre, respectively) I get a collision error, even with no other packages installed in my user profile or java related packages in my system profile

Error message:
http://lpaste.net/134232

**Comment by wkennington** [comment]
This is due to some changes I made to how we propagate the derivations. I'll take a look at fixing the outputs of jdk and jre so that they don't collide since we were simply duplicating outputs before and making them independent.

**Comment by henrytill** [comment]
I'm running into this problem on the unstable channel, currently at revision e1af50c.

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by MP2E** [comment]
Sorry for the late response! this is no longer an issue so I'm closing the report
