### ISSUE TITLE
Next-Browser fails to start with a valid D-BUS address set

### ISSUE THREAD

**Issue by bqv** [NixOS/nixpkgs#82631]
**Describe the bug**
App fails to start.
Discussed with the developer (jmercouris / @atlas-engineer), this bug is due to the version of `lispPackages.cl-ppcre` being far older than expected, so the interface for cl-ppcre:split has changed.

**To Reproduce**
1. Install pkgs.next
2. Assert your environment has something similar to `DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-5jqEyA9hZ0,guid=53188fd8a34b6621461c79c65e6929ef` set
3. Attempt to run `next`

**Expected behavior**
Browser launched

**Screenshots**
```
Next version 1.5.0
Loading configuration from #P"~/.config/next/init.lisp"...
 <WARN> [03:46:26] next utility.lisp (setf get-default) -
  The (setf (get-default ...)) and (add-to-default-list ...) forms are deprecated.

debugger invoked on a UNKNOWN-KEYWORD-ARGUMENT in thread
#<THREAD "main thread" RUNNING {10005484C3}>:
  Unknown &KEY argument: :LIMIT

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Ignore all unknown keywords
  1: [ABORT   ] Exit from the current thread.

(STR:SPLIT "=" "DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-nmEmMACdtY,guid=08f16243476450baa2f5871c5e6da512" :LIMIT 2) [more]
   source: (DEFUN SPLIT (SEPARATOR S &KEY (OMIT-NULLS *OMIT-NULLS*))
             "Split s into substring by separator (cl-ppcre takes a regex, we do not)."
             (LET* ((RES (CL-PPCRE:SPLIT (CL-PPCRE:QUOTE-META-CHARS #) S)))
               (IF OMIT-NULLS
                   (REMOVE-IF (LAMBDA (IT) (EMPTY? IT)) RES)
                   RES)))
0] 1
```

**Additional context**
A local fix I have implemented is to override lispPackages as follows:
```nix
{
  nixpkgs = {
    config.packageOverrides = pkgs: {
      lispPackages = pkgs.lispPackages // {
        cl-ppcre = pkgs.lispPackages.cl-ppcre.override rec {
          version = "v2.1.1";
          src = pkgs.fetchurl {
            url = "https://github.com/edicl/cl-ppcre/archive/v2.1.1.tar.gz";
            sha256 = "1vsxv12hpzh5nz0vk0r0m915g7bai7v2iab5qpkdjj0nnxwi2qw9";
          };
        };
      };
    };
  };
}
```

**Metadata**
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.23, NixOS, 20.09pre216896.0729b8c55e0 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre216896.0729b8c55e0"`
 - channels(user): `"home-manager, nixpkgs-20.09pre216928.991bbef6835, nurpkgs"`
 - nixpkgs: `~/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: next cl-ppcre
# a list of nixos modules affected by the problem
module:
```

**Comment by nlewo** [comment]
This [readme](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/lisp-modules/README.txt) explains how to upgrade the lisp package set.
But it seems we are already using the  `v2.1.1` (based on date comparisin). However it's not really clear to me how to know from which commit the quicklisp package is coming:/
Could you compare the package we are using with the `v2.1.1` version?

**Comment by ysengrimm** [comment]
Hi, interestingly I don't have that problem on 19.09. 
Also the diff of the GitHub release and the version on quicklisp of cl-pprce shows no differences between the files.

<details> 
  <summary>Output </summary>

```
> echo $DBUS_SESSION_BUS_ADDRESS
unix:abstract=/tmp/dbus-RjRMIMARUB,guid=b3c51fa51b70c2eee05af5925e6b8ba1

> next
Loading configuration from #P"/home/yg/.config/next/init.lisp"...
 <INFO> [19:50:46] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-RjRMIMARUB">)
 <INFO> [19:50:46] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.2240
 <INFO> [19:50:46] next port.lisp (run-program port) -
  Current directory: /home/yg/mnt/
 <INFO> [19:50:46] next port.lisp (run-program port) -
  Platform port path: /nix/store/r7p12sddm2phjjvknq7akx89302343ny-next-gtk-webkit-1.5.0/bin/next-gtk-webkit
 <INFO> [19:50:46] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [19:50:46] next port.lisp (run-program port) -
  Platform port log file: /home/yg/.local/share/next/next-gtk-webkit.log
 <WARN> [19:50:47] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
 <INFO> [19:50:55] next minibuffer.lisp (echo form-fun-6) -
  "→ https://github.com/atlas-engineer/next"
```
</details>

**Comment by bqv** [comment]
Hrm, humblest apologies, I seem to have remembered wrong and upgraded the wrong package… [Note](https://imge.to/i/yQcaeH)

**Comment by bqv** [comment]
[This](https://github.com/vindarel/cl-str/commit/d020eb909dae95f223a3be9a407a167c2d0705d4) is the interface breaking commit. It seems our version of `str` is a [few days too old](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/lisp-modules/quicklisp-to-nix-output/str.nix)

**Comment by bqv** [comment]
http://quickdocs.org/cl-str the current latest version of cl-str is 20191227, this might be automatically updated

**Comment by bqv** [comment]
Hm, interesting. Seems dbus hasn't been in next code for 2 months. I might have had a bad environment. If nobody else can reproduce, this should be closed

**Comment by ysengrimm** [comment]
I opened #82687 with updates to quicklisp and the distinfo. This should include the newer version of `cl-str`.

**Comment by bqv** [comment]
Excellent, thanks.

**Comment by bqv** [comment]
PR has been merged. Closing
