### ISSUE TITLE
ucommon (openssl): use newer openssl

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#82688]
ucommon is currently using a vulnerable version for the openssl variant
It's needed for the twinkle package

Building it with the latest openssl version causes a build error.
It would propably need to be patched.

**Comment by flokli** [comment]
@mkg20001 I'm missing version numbers and CVE numbers in the report. Can you elaborate?

Maybe related, but without more details, I can only guess:

https://github.com/NixOS/nixpkgs/pull/84083
https://github.com/NixOS/nixpkgs/pull/84084
