### ISSUE TITLE
Packaging request: BigBlueButton

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#82737]
**Project description**

From their GitHub page:

> BigBlueButton is an open source web conferencing system.
>
> BigBlueButton supports real-time sharing of audio, video, slides (with whiteboard controls), chat, and the screen. Instructors can engage remote students with polling, emojis, multi-user whiteboard, and breakout rooms.
>
> Presenters can record and playback content for later sharing with others.
>
> We designed BigBlueButton for online learning (though it can be used for many other applications).

Would be nice to have it packaged and then NixOS service definition, so one could easily set up a server running BBB.

Motivation: This is currently very useful because of schools and other facilities being closed and online conferencing/learning tools are needed.

**Metadata**

* homepage URL: https://demo.bigbluebutton.org
* source URL: https://github.com/bigbluebutton/bigbluebutton
* license: couldn't find yet.. should be open source though
* platforms: linux at least

**Comment by davidak** [comment]
>The components developed by the BigBlueButton project are available under the GNU Lesser General Public License.

https://bigbluebutton.org/open-source-license/

You can also see it in the header of the actual code: https://github.com/bigbluebutton/bigbluebutton/blob/develop/video-broadcast/src/main/java/org/bigbluebutton/app/videobroadcast/VideoApplication.java

**Comment by ajs124** [comment]
Closing this with the same reason as #83072

-  we have packaged this and written modules for this here: https://github.com/helsinki-systems/bbb4nix
- as you can see, it's several thousand lines of packages and modules
- I'm convinced this software cannot be packaged to a standard fit for nixpkgs
