### ISSUE TITLE
imagemagick: unable to access configure file `configure.xml'

### ISSUE THREAD

**Issue by csernazs** [NixOS/nixpkgs#82749]
**Describe the bug**
I would like to use a shell script which would use the output `convert -list configure`, however on my nixos, along with some useful text, it prints the error:
`convert: unable to access configure file 'configure.xml' @ warning/configure.c/GetConfigureOptions/677.`

**To Reproduce**
1. Run `convert -list configure`
2. Look at the output

**Expected behavior**
No error, and some additional values are printed from the xml (as I cannot produce the correct output, I have no idea how it would look like).

**Additional context**
I'm trying to run one of the Fred's ImageMagick scripts which can be located at http://www.fmwconcepts.com/imagemagick/textcleaner/index.php.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/5h35s50503spks8gkxdv3kk4szz8vx9g-bash-interactive-4.4-p23-dev
copying path '/nix/store/5h35s50503spks8gkxdv3kk4szz8vx9g-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.109, NixOS, 19.09.2260.3b9b10e49be (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2260.3b9b10e49be, nixos-unstable-20.09pre216896.0729b8c55e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: imagemagick
# a list of nixos modules affected by the problem
module:
```

**Comment by juanmachuca95** [comment]
the problem persists in windows 10, I would be very grateful if anyone shares any solution

**Comment by rhendric** [comment]
Rather late to the party, but this seems to be due to the half-executed `dev` output split done in https://github.com/NixOS/nixpkgs/commit/73f1f5eb3969743fe459e7cc36cfb766c7f5318a. Setting the correct path in the ImageMagick binaries would create a circular dependency between `dev` and `out`.

A workaround for end users would be:
```sh
export MAGICK_CONFIGURE_PATH=$(echo $(nix-build '<nixpkgs>' -A imagemagick.dev --no-out-link)/lib/ImageMagick-*/config-*)
convert -list configure
```
