### ISSUE TITLE
Add python hook to enforce PEP420 namespace

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#82756]
**Problem**
Some python packages have poorly implemented namespaces (azure-mgmt?, google). It would be nice to have a way to set what namespace should be enforced and delete the corresponding `"namespace/__init__.py"` (PEP420 standard)

**Proposal**
Nix expression:
```
{...}:

buildPythonPackage rec {
  ...
  pythonNamespaces = [ "azure.mgmt" ];
 ..
}
```
corresponding actions (python3):
```
  ..
  rm -f ${python.sitePackages}/"azure/__init__.py"
  rm -f ${python.sitePackages}/"azure/mgmt/__init__.py"
  ..
```

just curious on your thoughts @FRidh

**Comment by FRidh** [comment]
But why do we want to force PEP 420? I am still confused by the need of removing the `__init__.py`. Was that because of `PYTHONPATH` not handling those types of namespace packages correctly?

**Comment by FRidh** [comment]
Otherwise, I think it's a clean solution to have such an *optional* hook.

**Comment by jonringer** [comment]
it's to help clean up some namespace packages. For example, the google python packages don't build (past the first few root packages) because they are not able to import many google packages (it will import the `__init__.py` from protobuf or google.*, and fail to traverse to other packages), as a result there will be some `ImportError/ModuleError: google.auth could not be imported` and fail a lot of the packages. To have many directories traversed, they need to be PEP420 compliant, or else python will assume that it will be able to import the module from a given `__init__.py`

**Comment by jonringer** [comment]
For the azure packages, some of the packages did install the `__init__.py`, some did not, so it was awkward to handle both the python2 pkgutil namespace, and the python3 implicit/native namespace

**Comment by jonringer** [comment]
@FRidh do you mind looking over the PR? I think it looks good, but i could remove the `dontUsePythonNamespaces` switch, since it won't run unless your opt-in to it with declaring a `pythonNamespaces` attr. But I put it in there, to follow the convention used by other hooks

**Comment by jonringer** [comment]
going to close, as it's now in staging
