### ISSUE TITLE
Doc: Release notes QA

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#82777]
I have read the release notes of 20.03, here are the things i noticed:

## B.1.1. Highlights

>Linux kernel is updated to branch 5.4 by default (from 4.19). Users of Intel GPUs may prefer to explicitly set branch to 4.19 to avoid some regressions.

Can you add a link to an open issue to see when it is fixed? At least link to "more information" e.g.:

https://linuxreviews.org/Linux_Kernel_5.5_Will_Not_Fix_The_Frequent_Intel_GPU_Hangs_In_Recent_Kernels

## B.1.2. New Services

Not all entries are services. Maybe "Modules" would be more accurate? If we decide to change it, apply it to all NixOS releases.

Some services are listed here, but they where just moved. For example:

./services/networking/ntp/chrony.nix
./services/networking/ntp/ntpd.nix

https://github.com/NixOS/nixpkgs/commit/a61e94329fd1698e31ffb798b7ed50e882249d49#diff-b2313bbf3af788db31010cee19681051

Best would be to update the tooling to exclude moved files and update it.

## B.1.3. Backward Incompatibilities

>The services.dnscrypt-proxy module has been removed as it used the deprecated version of dnscrypt-proxy. We've added services.dnscrypt-proxy2.enable to use the supported version.

can't it be a drop-in replacement? it would be more user friendly if the new version would just be used with services.dnscrypt-proxy (i don't know the software, so it might makes sense)

**Update**: This seems fine since the options have changed completely. It has `settings` option now.

https://nixos.org/nixos/options.html#dnscrypt
https://github.com/NixOS/nixpkgs/blob/92d689d66bf68e31acdc85b54a4d9d8866497b50/nixos/modules/services/networking/dnscrypt-proxy2.nix

Maybe mention that the options have changed. Like "options are now organized using a settings option" or something like that to make it really clear

---

fixed small typo myself https://github.com/NixOS/nixpkgs/pull/82776 (backported in https://github.com/NixOS/nixpkgs/pull/83726)

@worldofpeace

**Comment by worldofpeace** [comment]
I was hoping to do/address all these things @davidak :+1:
