### ISSUE TITLE
Swap partition should be encrypted

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#8277]
At least optionally, and probably by default.

http://askubuntu.com/a/313574

**Comment by peti** [comment]
I believe a pull request that adds the necessary code to NixOS would be happily accepted.

**Comment by geerds** [comment]
Debian's [decrypt_derived](http://anonscm.debian.org/viewvc/pkg-cryptsetup/cryptsetup/trunk/debian/README.initramfs?view=markup) script may be useful for this (in `/lib/cryptsetup/scripts/decrypt_derived`). This way you don't need to enter multiple passwords during boot and it works without LVM (for the case if the root partition is already encrypted)

[Here is the documentation](http://anonscm.debian.org/viewvc/pkg-cryptsetup/cryptsetup/trunk/debian/README.initramfs?view=markup)

**Comment by Profpatsch** [comment]
(triage) Anyone who wants to implement this?

**Comment by obadz** [comment]
There's a `randomEncryption = true` flag that can be applied on swap devices that was added by @abbradar in de8b8b35 but it did not work for me. Will provide more detailed errors soon.
