### ISSUE TITLE
Haskell package not registering with ghc when installed using nix-env

### ISSUE THREAD

**Issue by psibi** [NixOS/nixpkgs#8278]
I'm using Ubuntu with nix package manager in it.
    $ nix-env --version
    nix-env (Nix) 1.8

I try to install an haskell package:

    $ { ~ }-> nix-env -i -A nixpkgs.haskellPackages.xmonad-contrib
    replacing old ‘haskell-xmonad-contrib-0.11.4’
    installing ‘haskell-xmonad-contrib-0.11.4’
    building path(s) ‘/nix/store/fxfibqmw7s3aqhgl05cb3w3l0b29mi00-user-environment’
    created 440 symlinks in user environment

But when I try to see if it's registered with `ghc` I don't get anything:

    $ ghc-pkg list | grep xmonad*

I get nothing from the above command. The output of `ghc-pkg list` is in the following [gist](https://gist.github.com/psibi/52f3d5b2a7d8d1c56a31). So, why isn't the haskell package registered with ghc after it is installed ?

More information:

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.10.1
    $ which ghc
    /home/sibi/.nix-profile/bin/ghc

Let me know if any other information is needed. Am I missing something obvious or is it a bug ?

**Comment by psibi** [comment]
CC: @peti

**Comment by peti** [comment]
You'll find a detailed answer to this phenomenon in https://nixos.org/wiki/Haskell. The section *How to install a compiler with libraries* should be of particular interest. I hope this helps!

**Comment by psibi** [comment]
Thanks, that's exactly what I required.

**Comment by lynnard** [comment]
I'm facing the same problem but the link does not work anymore? Is there still a reference to the same section anymore?

**Comment by vyp** [comment]
@lynnard https://nixos.org/nixpkgs/manual/#how-to-install-a-compiler-with-libraries
