### ISSUE TITLE
binutils override withAllTargets does not work

### ISSUE THREAD

**Issue by parthy** [NixOS/nixpkgs#82792]
**Describe the bug**
I am trying to get binutils to support all targets by overriding the withAllTargets argument. But I get the following error message:

```
error: anonymous function at /nix/store/5w02kc6nw8xybgfy4n787ssks3a88c5i-nixpkgs-20.03pre211462.0c960262d15/nixpkgs/pkgs/build-support/fetchurl/boot.nix:5:1 called with unexpected argument 'meta', at /nix/store/5w02kc6nw8xybgfy4n787ssks3a88c5i-nixpkgs-20.03pre211462.0c960262d15/nixpkgs/pkgs/build-support/fetchpatch/default.nix:14:1
(use '--show-trace' to show detailed location information)
```

**To Reproduce**
1. Create shell.nix:
```
{
  pkgs ? import <nixpkgs> {},
}:

pkgs.mkShell {
  nativeBuildInputs = [ (pkgs.binutils-unwrapped.override { withAllTargets = true; }) ];
}
```

2. Execute nix-shell

**Expected behavior**
A shell environment containing binutils with all targets enabled.

**Additional context**
The higher-level goal is to obtain a version of `objcopy` that supports `pe-i386` and `pe-x86-64` targets. I need to copy a 32-bit PE object file to a 64-bit one. If there is a better way to accomplish this goal, I'd appreciate guidance.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-76-generic, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(parthy): `"nixpkgs-20.03pre211462.0c960262d15"`
 - nixpkgs: `/home/parthy/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by parthy** [comment]
Setting `enableShared = false` as well seems to be working fine. Is this expected? Then maybe the error message should somehow reflect that, if possible.

**Comment by Enteee** [comment]
Maybe i am completely wrong about this, but I think since this works with `enableShared = false` the issue most likely comes from [here](https://github.com/NixOS/nixpkgs/blob/ec352ccff6be1f03fa07a1452d4781cd51966008/pkgs/development/tools/misc/binutils/default.nix#L140).

**Comment by matthuszagh** [comment]
I'm experiencing the same issue with 7e9b0dff974c89e070da1ad85713ff3c20b0ca97.

**Comment by trofi** [comment]
Still a problem. I think the trigger is the use of `fetchpatch` in `libbfd`, but I don't understand why it matter for override.

CLI reproducer:

```
$ nix build  --impure --expr 'with import ./. {}; binutils-unwrapped.override { withAllTargets = true; }'
error: anonymous function at /home/slyfox/dev/git/nixpkgs-master/pkgs/build-support/fetchurl/boot.nix:5:1 called with unexpected argument 'postFetch'

       at /home/slyfox/dev/git/nixpkgs-master/pkgs/build-support/fetchpatch/default.nix:31:1:

           30| in
           31| lib.throwIfNot (excludes == [] || includes == [])
             | ^
           32|   "fetchpatch: cannot use excludes and includes simultaneously"
(use '--show-trace' to show detailed location information)
```

**Comment by trofi** [comment]
Proposed the fix (and a new explicit attribute) as https://github.com/NixOS/nixpkgs/pull/168106
