### ISSUE TITLE
Packaging request: Jitsi Meet

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#82805]
**Project description**

From the project website:

> Jitsi Meet - Secure, Simple and Scalable Video Conferences
>
> Jitsi Meet is an open-source (Apache) WebRTC JavaScript application that uses Jitsi Videobridge to provide high quality, secure and scalable video conferences. Jitsi Meet in action can be seen at here at the session #482 of the VoIP Users Conference.
>
> The Jitsi Meet client runs in your browser, without installing anything on your computer. You can try it out at https://meet.jit.si .
>
> Jitsi Meet allows very efficient collaboration. Users can stream their desktop or only some windows. It also supports shared document editing with Etherpad.

So this is a server side package. Clients can use just web browsers.

In addition to packaging Jitsi Meet, it'd be great to have a corresponding NixOS service definition, so it'd be easy to set up on a server.

Jitsi Meet requires Jitsi Videobridge (https://github.com/jitsi/jitsi-videobridge), so that would need packaging too.

**Metadata**

* homepage URL: https://jitsi.org/jitsi-meet/
* source URL: https://github.com/jitsi/jitsi-meet
* license: Apache 2
* platforms: linux at least

**Comment by mmilata** [comment]
Started working on it: https://github.com/otevrenamesta/nixpkgs/commits/jitsi-meet

The packages seem to build fine but the NixOS module is not there yet, mostly the prosody configuration is missing. Hopefully tomorrow the branch will be in shape to open a PR.

**Comment by mmilata** [comment]
Please review/test: #82920

**Comment by ryantm** [comment]
Just merged #92468 which provides the basic modules. It still needs documentation work.
