### ISSUE TITLE
strip: can't process non-object and non-archive file

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#8281]
on mac we see a lots of
strip: can't process non-object and non-archive file: /nix/store/whvwkx199knnyhm4k6g8bmyhslkbydwk-nixops-1.3pre0_abcdef/lib/python2.7/site-packages/nixops/statefile.pyc

should we worry about this ?

**Comment by vcunat** [comment]
No need to worry, as strip is tried on all executable files by default. It only generates annoying messages but causes no real problems AFAIK.
