### ISSUE TITLE
junixsocket is awfully out of date

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixpkgs#82889]
**Describe the bug**
currently `junixsocket-1.3` is in nixpkgs, which is from 2014
since then the project has moved to GitHub and Maven (from Google Code and Ant)

An updated `default.nix`should carry sth. like
```
  name = "junixsocket";
  version = "2.3.2";

  src = fetchurl {
    url = "https://github.com/kohlschutter/junixsocket/archive/${name}-parent-${version}.tar.gz";
    sha256 = "0xggvh2zndlfspld5g184sfg42abg0ksqyk18b8c6878dhgc42ml";
  };
```

**Comment by tari** [comment]
The current old version is also broken because it depends on `junit`. I'd have a go at updating it but don't really understand how maven packaging is supposed to work.

**Comment by wamserma** [comment]
Well, there is `mvn2nix` and this might get you further: https://ww.telent.net/2017/5/10/building_maven_packages_with_nix

**Comment by pongo1231** [comment]
Shouldn't this be closed now that it has been updated over a year ago (and completely removed a few months afterwards)?
