### ISSUE TITLE
Package request: pagraphcontrol

### ISSUE THREAD

**Issue by bew** [NixOS/nixpkgs#82898]
**Project description**
`pagraphcontrol` is a visual pulseaudio front end, it shows a graph of the pulseaudio's sources and sinks (can be life savior when doing complex setup!), and allows you to add a few modules, and configure them.

**Metadata**

* homepage URL: same as source url
* source URL: https://github.com/futpib/pagraphcontrol
* license: GPL-3.0
* platforms: linux

**Comment by bew** [comment]
still important to me, but less important, and as I've learnt to use and write Nix, the next time I need it I'll just package it myself I think.

**Comment by djahandarie** [comment]
I found myself wanting this today
