### ISSUE TITLE
Cross-compiling OpenSSL 1.1 is broken on most platforms

### ISSUE THREAD

**Issue by ebkalderon** [NixOS/nixpkgs#82924]
**Describe the bug**

It seems that OpenSSL 1.1 cannot be cross-compiled on most platforms on the current `HEAD` of Nixpkgs at the time of writing (`eb3e75e78832461c2462b9a5280b8a19cfc5246b`).

I haven't been able to confirm whether cross-compiling OpenSSL 1.0.2 works, but given that the package is labeled insecure and is EOL'ed, I didn't attempt to investigate.

**To Reproduce**

Given the following Nix expression:

```nix
{
  system ? builtins.currentSystem,
  crossSystem ? null,
}:
with import <nixpkgs> { inherit system crossSystem; };
openssl
```

And the following build command:

```bash
nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/eb3e75e78832461c2462b9a5280b8a19cfc5246b.tar.gz
```

I can confirm the following results:

`system` | `crossSystem` | Result
----|----|----
`x86_64-linux` | `null` | Works
`x86_64-darwin` | `null` | Works
`x86_64-linux` | `musl64` | Works
`x86_64-darwin` | `musl64` | Fails
`x86_64-linux` | `gnu64` | Fails
`x86_64-darwin` | `gnu64` | Fails

**Expected behavior**

I expected all tested combinations above (except perhaps `crossSystem = gnu64`) to succeed on both Linux and Darwin.

**Metadata**

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixpkgs-19.09pre192418.e19054ab3cd"`
 - channels(eyalkalderon): `"nixpkgs-20.09pre215991.93ba4ecd586"`
 - nixpkgs: `/Users/eyalkalderon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ openssl, openssl_1_1 ]
```

**Comment by ebkalderon** [comment]
Encountered while troubleshooting https://github.com/tenx-tech/cargo2nix/issues/96.

**Comment by vcunat** [comment]
For me `x86_64-linux` -> `gnu64` fails even before stdenv (already when building gcc).

**Comment by ebkalderon** [comment]
@vcunat Same here. I encounter this error on `x86_64-linux` -> `gnu64` while building `gcc`:

```
make[2]: Leaving directory '/tmp/nix-build-x86_64-unknown-linux-gnu-stage-static-gcc-debug-9.2.0.drv-0/build/libcpp'
configure: creating cache ./config.cache
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking LIBRARY_PATH variable... ok
checking GCC_EXEC_PREFIX variable... ok
checking whether to place generated files in the source directory... no
checking whether a default linker was specified... yes (/nix/store/0qr07mmbbspjmjlvswz6gf4dgk6vck8m-x86_64-unknown-linux-gnu-binutils-wrapper-2.31.1/bin/x86_64-unknown-linux-gnu-ld)
configure: error: cannot execute: /nix/store/0qr07mmbbspjmjlvswz6gf4dgk6vck8m-x86_64-unknown-linux-gnu-binutils-wrapper-2.31.1/bin/x86_64-unknown-linux-gnu-as: check --with-as or env. var. DEFAULT_ASSEMBLER
make[1]: *** [Makefile:4239: configure-gcc] Error 1
make[1]: Leaving directory '/tmp/nix-build-x86_64-unknown-linux-gnu-stage-static-gcc-debug-9.2.0.drv-0/build'
make: *** [Makefile:935: all] Error 2
builder for '/nix/store/jyr783c8m6ly8wbkq2y0k7amibi121ig-x86_64-unknown-linux-gnu-stage-static-gcc-debug-9.2.0.drv' failed with exit code 2
```

**Comment by ebkalderon** [comment]
Still important to me. Still broken in `master` to this day.

**Comment by Rizary** [comment]
I got the following error when building `openssl.dev` inside `buildInputs` attribute:

```
building
build flags: -j1 -l1 SHELL=/nix/store/516z50fm1jbpcl32qnzy7kynrh0vl22w-bash-4.4-p23/bin/bash MANDIR=\$\(man\)/share/man MANSUFFIX=ssl
/nix/store/03vh3lc5fymqjyck3v3rckbvs36qa74g-perl-5.32.0/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
/nix/store/03vh3lc5fymqjyck3v3rckbvs36qa74g-perl-5.32.0/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
/nix/store/03vh3lc5fymqjyck3v3rckbvs36qa74g-perl-5.32.0/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _all
make[1]: Entering directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
make[1]: Leaving directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
make[1]: Entering directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
x86_64-unknown-linux-musl-gcc  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 --disable-shared --enable-static --disable-shared -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/nix/store/ynqbb3qg52i53yn6camlclyda01dnhml-openssl-1.1.1h-x86_64-unknown-linux-musl/etc/ssl\"" -DENGINESDIR="\"/nix/store/ynqbb3qg52i53yn6camlclyda01dnhml-openssl-1.1.1h-x86_64-unknown-linux-musl/lib/engines-1.1\"" -DNDEBUG  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
cc1: error: unknown pass shared specified in '-fdisable'
cc1: error: unknown pass static specified in '-fenable'
cc1: error: unknown pass shared specified in '-fdisable'
make[1]: *** [Makefile:708: apps/app_rand.o] Error 1
make[1]: Leaving directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
make: *** [Makefile:174: all] Error 2
```

@ebkalderon does this error the same with you?

**Comment by siraben** [comment]
Ran into this today.

```ShellSession
$ nix build .#pkgsCross.raspberryPi.spasm-ng
```

fails on macOS due to the perl dependency of openssl failing to cross-compile. Specifically, the patchPhase failed to apply patches.

**Comment by Radvendii** [comment]
Status for Windows MinGW (if anyone cares :stuck_out_tongue:):
- openssl 1.1 doesn't cross-compile, but I think this is expected
  see https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L16898-L16901
  ```
  openssl =
    if stdenv.hostPlatform.isMinGW # Work around broken cross build
    then openssl_1_0_2
    else openssl_1_1;
  ```
  also see https://github.com/NixOS/nixpkgs/pull/108170, where that's getting fixed
  Also https://github.com/NixOS/nixpkgs/pull/108170 is trying to fix that
- openssl 1.0.2 cross-compiles if it's overriden with `withPerl = false;`. Currently perl does not cross-compile to windows.

Should `withPerl` get some default value besides "true"? Like, maybe `stdenv.buildPlatform == stdenv.hostPlatform`? That seemed to be causing issues on other platforms as well.

**Comment by easymoney322** [comment]
I'm sorry for necroposting, I'm already encouner this issue second time, and this page is still in top result.
The Issue is probably being caused by "--enable-static --disable-shared" flags. 
Try to "make distclean", then configure OpenSSL with "-static" instead of previous two flags, and run "make" after it. 


> I got the following error when building `openssl.dev` inside `buildInputs` attribute:
> 
> ```
> building
> build flags: -j1 -l1 SHELL=/nix/store/516z50fm1jbpcl32qnzy7kynrh0vl22w-bash-4.4-p23/bin/bash MANDIR=\$\(man\)/share/man MANSUFFIX=ssl
> /nix/store/03vh3lc5fymqjyck3v3rckbvs36qa74g-perl-5.32.0/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
>     "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
> /nix/store/03vh3lc5fymqjyck3v3rckbvs36qa74g-perl-5.32.0/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
>     "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
> /nix/store/03vh3lc5fymqjyck3v3rckbvs36qa74g-perl-5.32.0/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
>     "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
> make depend && make _all
> make[1]: Entering directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
> make[1]: Leaving directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
> make[1]: Entering directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
> x86_64-unknown-linux-musl-gcc  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 --disable-shared --enable-static --disable-shared -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/nix/store/ynqbb3qg52i53yn6camlclyda01dnhml-openssl-1.1.1h-x86_64-unknown-linux-musl/etc/ssl\"" -DENGINESDIR="\"/nix/store/ynqbb3qg52i53yn6camlclyda01dnhml-openssl-1.1.1h-x86_64-unknown-linux-musl/lib/engines-1.1\"" -DNDEBUG  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
> cc1: error: unknown pass shared specified in '-fdisable'
> cc1: error: unknown pass static specified in '-fenable'
> cc1: error: unknown pass shared specified in '-fdisable'
> make[1]: *** [Makefile:708: apps/app_rand.o] Error 1
> make[1]: Leaving directory '/tmp/nix-build-openssl-1.1.1h-x86_64-unknown-linux-musl.drv-0/openssl-1.1.1h'
> make: *** [Makefile:174: all] Error 2
> ```
> 
> @ebkalderon does this error the same with you?
