### ISSUE TITLE
Packaging request: deriving-aeson

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#82927]
**Project description**
Deriving ToJSON/FromJSON instances with DerivingVia

**Metadata**

* homepage URL: https://hackage.haskell.org/package/deriving-aeson
* source URL: https://github.com/fumieval/deriving-aeson
* license: bsd
* platforms: unix

**Comment by cdepillabout** [comment]
@poscat0x04 This is available as `haskellPackages.deriving-aeson` on the `master` branch.
