### ISSUE TITLE
Why do we have the release tagging policy that we do?

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#83024]
Pardon me for the stupid question. I recall that back in the day we created tags for upcoming releases like `18.09-beta`, which tagged the commit from which the release branch was branched off. However, something didn't work the way we expected with those tags, so we changed the policy to tag the first commit of the newly created branch, e.g. `18.09-beta` was effectively created on the `master` but the subsequent release tags were not. I recall that there was some reason, but I don't recall what the reason was! 

Can someone please enlighten me?

Ping @vcunat, who probably knows.

**Comment by FRidh** [comment]
I imagine it has to do with the `revCount` that needs to be adjusted when branching. We can't do that before branching because it would break the unstable channels.

**Comment by jonringer** [comment]
as tagged above, I have a PR to add a tagging step to the release, so that the latest tag on master will reflect the current unstable channel.

**Comment by jonringer** [comment]
the release wiki has been updated so that master only has `pre` tags, the `beta` tag is now the first commit on `release-YY.MM`
