### ISSUE TITLE
Package request: onionshare

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#83029]
**Project description**
OnionShare is an open source tool for securely and anonymously sending and receiving files using Tor onion services. It works by starting a web server directly on your computer and making it accessible as an unguessable Tor web address that others can load in Tor Browser to download files from you, or upload files to you. It doesn't require setting up a separate server, using a third party file-sharing service, or even logging into an account.

**Metadata**

* homepage URL: https://onionshare.org/
* source URL: https://github.com/micahflee/onionshare
* license: GPL3+
* platforms: unix, linux, darwin, ...

**Comment by lourkeur** [comment]
Been working on it. Not too sure how good my expression is. Please test it and ping me if it works for you, then I'll pull-request it into nixpkgs.

https://github.com/lourkeur/nur-expressions/tree/master/pkgs/onionshare

**Comment by mehlon** [comment]
I just tried it with NixOS on the unstable channel. Works fine.

**Comment by wamserma** [comment]
Running it as
```
nix run nixpkgs.nur.repos.lourkeur.onionshare --command onionshare-gui
```
on stable-19.09 also works as advertised (tested: Download with Tor Browser on Ubuntu)

@lourkeur The `.nix` also LGTM, so feel free to open the PR against `nixpkgs`.

**Comment by lourkeur** [comment]
@mehlon can you close this please?
