### ISSUE TITLE
Package requests should start with "Package request:"

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#83031]
Right now package requests do not have a template for the title. So the titles are usually something like: "package request: hello", "Package request: hello", "hello package", "hello packaging" or simply "hello".
I suggest that the most common title: "Package request:" be added to the GitHub template so people won't have to guess how to title their issue.

**Comment by leonardp** [comment]
would it be possible to use the [labels](https://github.com/NixOS/nixpkgs/labels?q=package) in the template?
maybe there should be more templates in the first place?

**Comment by donovanglover** [comment]
This is fixed now
