### ISSUE TITLE
KDE Wallet is not unlocked with SDDM

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#83095]
**Describe the bug**

After logging in with SDDM I see the following window:

![kde-wallet](https://user-images.githubusercontent.com/8165792/77233680-54870000-6ba9-11ea-8349-1593efb44d48.png)

Every time. This is annoying and should not happen. Previously, no manual intervention was necessary. This is a regression in 20.03.

**To Reproduce**

1. Switch to nixpkgs `b2935fbeceaea0b64df4401545d7c8ea29102120`. Set SDDM as your display manager and plasma5 as your desktop manager. Like so:

```nix
  services.xserver = {
    enable = true;
    layout = "us";
    libinput.enable = true;

    desktopManager = {
      plasma5.enable = true;
    };

    displayManager = {
      sddm.enable = true;
      defaultSession = "plasma5";
    };
  };
```

2. Reboot or I guess just logging out and then logging in again will do.
3. Observe the above-mentioned window.

**Expected behavior**

No manual intervention should be necessary.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.03.git.b2935fbecea (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre7250_94c93437`
 - channels(mark): `"nixos-18.09.2337.5d972dd2c94"`
 - channels(root): `"nixos-19.03.173651.ca6b6595392"`
 - nixpkgs: `/home/mark/nixpkgs`

**Comment by mrkkrp** [comment]
Here I obtained the portion of the system log that may be of interest:

[log.txt](https://github.com/NixOS/nixpkgs/files/4363689/log.txt)

**Comment by matthewbauer** [comment]
This is the same as #77290.
