### ISSUE TITLE
Rygel module needs to link /etc/rygel.conf

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#83108]
Rygel crashes without `/etc/rygel.conf`:

https://gitlab.gnome.org/GNOME/rygel/issues/153

**Comment by worldofpeace** [comment]
We do have a module https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/desktops/gnome3/rygel.nix. Do you mean it should be configurable too?

**Comment by jtojnar** [comment]
We need at least `environment.etc."rygel.conf" = "${pkgs.gnome3.rygel}/etc/rygel.conf"`.

Having it configurable would be even better.

We would need to research what good defaults are.

**Comment by worldofpeace** [comment]
The default config looks well documented
* https://gitlab.gnome.org/GNOME/rygel/-/blob/master/data/rygel.conf

More stuff
* https://wiki.gnome.org/Projects/Rygel/Configuration
* http://rygel-project.org/doc/latest/rygel.conf.html

I guess what's important for end users is being able to configure (on/off) plugins.
