### ISSUE TITLE
Package gvls

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#83118]
gnome-builder now needs gvls for vala support: https://gitlab.gnome.org/esodan/gvls

**Comment by worldofpeace** [comment]
I can do this.

**Comment by jtojnar** [comment]
Looks like elementary Code still does not use it: https://github.com/elementary/code/issues/727
And Builder removed it https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/1a37f5333a41a7820777990f5abf0b03b8e40ef4

**Comment by JohnRTitor** [comment]
https://github.com/NixOS/nixpkgs/pull/322332#issuecomment-2206858679
