### ISSUE TITLE
nix-shell warn when -p used with no arguments

### ISSUE THREAD

**Issue by codygman** [NixOS/nixpkgs#83169]
This cost me a little time in  GuillaumeDesforges/haskell-nix-dev-template#7.

A warning is correct for -p with no arguments I believe, not sure about nix-shell -p in a directory with shell.nix.

Maybe a notice that shell.nix isn't being used?

**Comment by matthewbauer** [comment]
Probably should be opened in https://github.com/NixOS/nix.

I actually do use `nix-shell -p` occasionally to just get gcc, binutils, etc.
