### ISSUE TITLE
patchShebangs doesn't patch files with dos newlines

### ISSUE THREAD

**Issue by Pamelloes** [NixOS/nixpkgs#8317]
I spent several hours today trying to determine why patchShebangs was missing some critical files. Turns out they had dos newlines. While changing the newlines in the files directly (my current solution) works well enough, it would be much better if the script would be able to handle the dos newlines directly.

I have tested and can repeat this on OS X 10.10.4 running nixpkgs unstable. I might test on a nixos machine later—I will edit with the results.

**Comment by matthiasbeyer** [comment]
@Pamelloes Any updates?

**Comment by Profpatsch** [comment]
(triage) I’m at a loss to where `patchShebangs` is defined in nixpkgs. Any hints?

**Comment by bjornfor** [comment]
pkgs/build-support/setup-hooks/patch-shebangs.sh

**Comment by Profpatsch** [comment]
We *could* insert something like

    sed -i 's/\r$//' "$f"

I’m not sure whether that is a valid dos→unix conversion.

**Comment by matthewbauer** [comment]
Is there an example of a package that has dos newlines? I am surprised that sed + grep aren't handling these correctly.

**Comment by Artturin** [comment]
looks like it's not a problem anymore

```diff
diff --git a/pkgs/test/patch-shebangs/default.nix b/pkgs/test/patch-shebangs/default.nix
index 5c49787eee3..7ae2b74664f 100644
--- a/pkgs/test/patch-shebangs/default.nix
+++ b/pkgs/test/patch-shebangs/default.nix
@@ -16,6 +16,20 @@ let
       };
     };
 
+    dos-newlines = stdenv.mkDerivation {
+      name         = "dos-newlines";
+      dontUnpack = true;
+      installPhase = ''
+        mkdir -p $out/bin
+        echo "#!/bin/sh" > $out/bin/test
+        printf "echo -n hello\r\n" >> $out/bin/test
+        chmod +x $out/bin/test
+      '';
+      passthru = {
+        assertion = "grep -v '^#!/bin/sh' $out/bin/test > /dev/null";
+      };
+    };
+
     ignores-nix-store = stdenv.mkDerivation {
       name = "ignores-nix-store";
       dontUnpack = true;
@@ -31,7 +45,7 @@ let
     };
   };
 in runCommand "patch-shebangs-test" {
-  passthru = { inherit (tests) bad-shebang ignores-nix-store; };
+  passthru = { inherit (tests) bad-shebang ignores-nix-store dos-newlines; };
   meta.platforms = lib.platforms.all;
 } ''
   validate() {
```
