### ISSUE TITLE
gnutls: "Error setting the x509 trust file"

### ISSUE THREAD

**Issue by ellis** [NixOS/nixpkgs#8321]
I'm seeing a problem with gnutls, both versions 3.3 and 3.4, whereby it doesn't use the CA certificates in /etc/ssl/certs/ca-certificates.crt by default, but does work if you pass it the appropriate command argument:

```{sh}
$ gnutls-cli nixos.org
Error setting the x509 trust file
...

$ gnutls-cli nixos.org --x509cafile /etc/ssl/certs/ca-certificates.crt
Processed 155 CA certificate(s).
...
```

(Strangely enough, if I use `nix-shell` to build gnutls33 and run `gnutls-cli nixos-org` from within nix-shell, it **does** work.)

My system is currently using nixpkgs from the unstable channel updated June 11 (nixos-15.06pre64030.e1af50c).

I downloaded the old .nix expression for v3.2 to test that too, and it works fine.

**Comment by vcunat** [comment]
This should be fixed by #8121, though it's only in the staging branch ATM (due to having nontrivial rebuild impact).
