### ISSUE TITLE
terraform-providers: update-all doesn't find all modules anymore

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#83215]
`pkgs/applications/networking/cluster/terraform-providers/update-all` is a bash script querying GitHub's API manually via `curl`.

GitHub requires clients to support pagination, the script currently doesn't, but only queries the "first 100 repositories", meaning it doesn't discover (and update) all of them.

Maybe it's time to rewrite this script in something that can make use some higher-level GitHub API bindings, like Python.

**Comment by zimbatm** [comment]
https://github.com/zimbatm/nixpkgs/blob/70cd3542017eebfe82fbebe703359e6b5f3609dc/pkgs/applications/networking/cluster/terraform-providers/update-all#L27-L31
clearly somebody thought about the pagination issue and then didn't implement it :)

**Comment by flokli** [comment]
After consulting the git blame output, I think I know that person, and it might have still worked 3 years ago ;-)
