### ISSUE TITLE
Package pantheon's mail client

### ISSUE THREAD

**Issue by 414owen** [NixOS/nixpkgs#83252]
**Project description**
The [elementary mail client](https://github.com/elementary/mail) shares a history with [geary](https://wiki.gnome.org/Apps/Geary), but is a different app, which fits the pantheon desktop.

**Metadata**

* homepage URL: https://elementary.io/
* source URL: https://github.com/elementary/mail
* license: GPLv3
* platforms: Linux

@worldofpeace I think you're coordinating pantheon efforts? I'd be happy to take a look at this.

**Comment by worldofpeace** [comment]
See the last bullet of https://github.com/NixOS/nixpkgs/issues/58161

**Comment by worldofpeace** [comment]
Not stale, still waiting for them to ship-it :shipit:

**Comment by kisik21** [comment]
@worldofpeace it seems like your wait might be over, judging by dependency list in README.md?

**Comment by worldofpeace** [comment]
@kisik21 I see this https://github.com/elementary/seeds/pull/41, so I will ask them in slack if they're shipping it. If so, I think I'll add it myself when they release odin, or anyone else is free to package it.
