### ISSUE TITLE
Zoneminder has unpatched absolute paths

### ISSUE THREAD

**Issue by unya** [NixOS/nixpkgs#83260]
**Describe the bug**
Zoneminder has unpatched absolute path to `/bin/rm` in the Event handling module. This results in Event files not being deleted

**To Reproduce**
1. Install zoneminder
2. Generate few events
3. Attempt to delete those events
4. Verify that the files are still on disk
5. Can be extra-checked by running `zmaudit.pl` under `strace -f -e execve`

**Expected behavior**
Event files are deleted when requested by ZoneMinder UI or Filters

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.17, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpgs.zoneminder
# a list of nixos modules affected by the problem
module: services.zoneminder
```

**Comment by peterhoeg** [comment]
zoneminder is currently unmaintained in nixpkgs/nixos. @unya , might you be interested in maintaining it?

**Comment by brainrake** [comment]
Looks like that fixed it, event files are deleted as of nixpkgs cfc3698c31b1fb9cdcf10f36c9643460264d0ca8
