### ISSUE TITLE
vimPlugins.vim-addon-nix: error when opening a .nix file

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#8328]
Steps to reproduce:

 0. Use nix-unstable
 0. Install nixos.pkgs.vimHugeX
 0. Install nixos.pkgs.vimPlugins.vim-addon-nix
 0. Open a .nix file
 0. Observe the following error:

```
Error detected while processing /nix/store/rx68gf8yszyxs7mzllgrbwvmy3nk8ik8-vimplugin-vim-addon-nix-2015-03-10/share/vim-plugins/vim-addon-nix/plugin/vim-addon-nix.vim:
line    8:
E117: Unknown function: funcref#Function
E15: Invalid expression: funcref#Function('vim_addon_nix#TagBasedCompletion')
line    9:
E117: Unknown function: funcref#Function
E15: Invalid expression: funcref#Function('vim_addon_nix#BuiltinsCompletion')
line   15:
E117: Unknown function: funcref#Function
E116: Invalid arguments for function actions#AddAction
Press ENTER or type command to continue

line   14:
E117: Unknown function: funcref#Function
E116: Invalid arguments for function on_thing_handler#AddOnThingHandler
line   22:
E117: Unknown function: vim_addon_completion#InoremapCompletions
line   14:
E117: Unknown function: funcref#Function
E116: Invalid arguments for function on_thing_handler#AddOnThingHandler
line   22:
E117: Unknown function: vim_addon_completion#InoremapCompletions
```

**Comment by flosse** [comment]
same here

**Comment by jagajaga** [comment]
Works fine for me. But I use this way to install vim+plugins https://github.com/jagajaga/my_configs/blob/master/.nixpkgs/common.nix#L85

**Comment by andrewrk** [comment]
@jagajaga this is incredible. Looks like it's time for me to completely redo the way I install and configure vim. Thanks for the link to your example config.

**Comment by jagajaga** [comment]
Oh, you are welcome :)
Check https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-utils.nix#L20 for a better example.

**Comment by jagajaga** [comment]
I can close issue?

**Comment by andrewrk** [comment]
well, I think it is still an issue. Are users not supposed to install vim, and then install vimPlugins.vim-addon-nix, and then open a .nix file?

**Comment by jagajaga** [comment]
Sorry, I don't know. AFAIK the "official" way of nix+vim+plugins is the one I've mentioned above.

**Comment by andrewrk** [comment]
If that's true, then I suppose this issue should be closed. As a user, how might I have discovered this without filing an issue?

**Comment by jagajaga** [comment]
You are right. I will write about that on the wiki page.

**Comment by andrewrk** [comment]
@jagajaga with your vim configuration, is `gvim` available? It is not available for me.

Here is my configuration so far: https://github.com/andrewrk/dotfiles

**Comment by jagajaga** [comment]
Run `vim -g`.

2015-06-16 3:48 GMT+03:00 Andrew Kelley <notifications@github.com>:

> @jagajaga <https://github.com/jagajaga> with your vim configuration, is
> gvim available? It is not available for me.
>
> Here is my configuration so far: https://github.com/andrewrk/dotfiles
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/8328#issuecomment-112246411>.
>



-- 
Sincerely,
Arseniy Seroka

**Comment by jagajaga** [comment]
https://nixos.org/wiki/Vim_plugins
