### ISSUE TITLE
[20.03] mailcather is broken since default ruby is 2.6

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#83351]
`mailcather` requires `ruby-2.5` and it is broken since default `pkgs.ruby` bumped to 2.6 in `nixpkgs-20.03`

it seems tricky to fix because the ruby infrastructure (`bundlerApp` and friends) does not have a straightforward way to replace ruby version for a particular derivation.

I started to fix and it quickly evolved to big refactoring which is not acceptable to do when there is only few days before releasing `nixpkgs-20.03`

**Comment by volth** [comment]
(in my branch I just reverted default ruby to 2.5)

**Comment by aanderse** [comment]
How unfortunate... it seems like `20.03` is suffering from [a](https://github.com/NixOS/nixpkgs/issues/78242) [number](https://github.com/NixOS/nixpkgs/issues/83222) [of](https://github.com/NixOS/nixpkgs/issues/81444) `ruby` related issues ☹️

@zarelit @nicknovitski any insight?

cc @manveru @thefloweringash @mawis

**Comment by zarelit** [comment]
@aanderse @volth I just tested the build and the service with nixos-shell against release-20.03 and it looks like it works as expected and it is based off ruby 2.6 as well. I think it has been fixed in another issue

**Comment by volth** [comment]
Interesting, here I have failed build with
```
these derivations will be built:
  /nix/store/vkffapci6ig30qiignhw3x2z1237zi9f-ruby2.6.5-mailcatcher-0.7.1.drv
  /nix/store/kkhi4vdrz6rmgdjwxnwwy9y1hdkh1ip8-mailcatcher-0.7.1.drv
  /nix/store/j4hdqy3gphnvad6w6jibb0bi2xyij1js-mailcatcher-0.7.1.drv
building '/nix/store/vkffapci6ig30qiignhw3x2z1237zi9f-ruby2.6.5-mailcatcher-0.7.1.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
buildFlags:
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/1fjlrfr3wc1ji2b0wc2dnlnhipzwmmyd-ruby2.6.5-mailcatcher-0.7.1/lib/ruby/gems/2.6.0/bin
  Gem home: /nix/store/1fjlrfr3wc1ji2b0wc2dnlnhipzwmmyd-ruby2.6.5-mailcatcher-0.7.1/lib/ruby/gems/2.6.0
Successfully installed mailcatcher-0.7.1
1 gem installed
/nix/store/1fjlrfr3wc1ji2b0wc2dnlnhipzwmmyd-ruby2.6.5-mailcatcher-0.7.1/lib/ruby/gems/2.6.0 /build
removed 'cache/mailcatcher-0.7.1.gem'
removed directory 'cache'
/build
cp: cannot create regular file '/nix/store/1fjlrfr3wc1ji2b0wc2dnlnhipzwmmyd-ruby2.6.5-mailcatcher-0.7.1/lib/ruby/gems/2.5.0/gems/mailcatcher-0.7.1/lib/mail_catcher/web/application.rb': No such file or directory
note: keeping build directory '/tmp/nix-build-ruby2.6.5-mailcatcher-0.7.1.drv-0'
builder for '/nix/store/vkffapci6ig30qiignhw3x2z1237zi9f-ruby2.6.5-mailcatcher-0.7.1.drv' failed with exit code 1
cannot build derivation '/nix/store/kkhi4vdrz6rmgdjwxnwwy9y1hdkh1ip8-mailcatcher-0.7.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/j4hdqy3gphnvad6w6jibb0bi2xyij1js-mailcatcher-0.7.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/j4hdqy3gphnvad6w6jibb0bi2xyij1js-mailcatcher-0.7.1.drv' failed
```
