### ISSUE TITLE
Packaging request: Remarkable

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#83366]
**Project description**

Remarkable is an open source Markdown Editor for Linux.

**Metadata**

* homepage URL: https://remarkableapp.github.io/index.html
* source URL: https://github.com/jamiemcg/Remarkable
* license: mit
* platforms: linux

**Comment by Aleksanaa** [comment]
Closing since the upstream source code has not been updated in three years. If you still need it, feel free to reopen this issue.
