### ISSUE TITLE
Package request: cwtch.im

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#83376]
**Project description**
Cwtch is a private messenger originally based on [Ricochet](https://github.com/ricochet-im/ricochet) but now featuring group chats, offline messages, and many other improvements. 

**Metadata**
* homepage URL: https://cwtch.im/
* source URL: https://git.openprivacy.ca/cwtch.im/ui (client); https://git.openprivacy.ca/cwtch.im/cwtch (server)
* license: mit
* platforms: linux, android, windows ...

**Comment by srid** [comment]
This was announced today on HN: https://news.ycombinator.com/item?id=27643171

**Comment by Ultra980** [comment]
Still important

**Comment by gmacon** [comment]
Hi, folks. I just opened a PR adding cwtch.im for Linux. I'd appreciate it if you could give it a try and let me know if you run in to any issues.
