### ISSUE TITLE
"vlock -ans" as a user fails because of permission

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#8337]
As root it works fine, but as a user (in the vlock group) I get:
```
vlock -as
vlock-nosysrq: could not open '/proc/sys/kernel/sysrq': Permission denied
```
and
```
vlock -n
vlock-new: cannot open virtual console: Permission denied
```

Debian once had the same problem, but I've not been able to distil their solution:
https://www.mail-archive.com/debian-bugs-closed@lists.debian.org/msg140033.html

@aszlig uses "vlock -ans" on NixOS, so it is possible:
https://github.com/openlab-aux/vuizvui/blob/master/modules/user/aszlig/services/vlock/default.nix#L50

**Comment by aszlig** [comment]
The reason this works on my machine is because it is started as root user. And it's probably not a good idea to allow access to `/proc/sys/kernel/sysrq` to normal users directly.

It works on Debian however, because the `vlock-main` binary is setuid-root:
```
-rwsr-xr-x root/root     31384 2014-07-15 23:11 ./usr/sbin/vlock-main
```

**Comment by magnetophon** [comment]
@aszlig OK, thanks.
Did I understand correctly that you need to type the root password when you want to lock?
I'm sorry I can't follow your code...

**Comment by aszlig** [comment]
I'm passing the `USER` environment variable to `vlock`, so it's prompting for the user passwd:

https://github.com/openlab-aux/vuizvui/blob/master/modules/user/aszlig/services/vlock/default.nix#L44-L45

**Comment by magnetophon** [comment]
@aszlig Alright, I'll stick with i3lock for now.  Thanks!
