### ISSUE TITLE
Bundle NixOS images we build with a channel pointing at the nixpkgs that built them

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8340]
Without this, you can't call `nixos-rebuild switch` and friends on a custom NixOS image without downloading a ton of stuff and aligning yourself to an official release of NixOS.

I've got some prototype code that does this but it's kind of unpleasant to work with, because with every change you make to your repository, you have to rebuild the image. If anyone has ideas on how to make this better, I'd love to hear them!

**Comment by vcunat** [comment]
When you change the repository files, you do need to change the channel, don't you?

**Comment by edolstra** [comment]
I don't understand. Our ISO images already contain a channel. See https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/channel.nix.

**Comment by copumpkin** [comment]
@edolstra ah, that's exactly it. I think we just need to factor out more common image-building code (something I've already been doing in a private branch), because the EC2 image doesn't get that and I didn't even realize it existed. I'll close this ticket and try to use a similar pattern, thanks!
