### ISSUE TITLE
strongswan: replace kmod with config.system.sbin.modprobe

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#8343]
As described in #5492, NixOS's `strongSwan` module needs to use `modprobe` so it [puts](https://github.com/NixOS/nixpkgs/blob/4bb1e611a2ac12ceb309566e44a172149aeb7539/nixos/modules/services/networking/strongswan.nix#L121) `kmod` in the `PATH`. I noticed errors in the journal saying that certain kernel modules weren't loaded. When I replaced `kmod` with `config.system.sbin.modprobe` the errors disappeared.

**Comment by ip1981** [comment]
Why did errors disappear?

**Comment by basvandijk** [comment]
I believe the errors disappeared because `pkgs.kmod` doesn't look in the right modules directory and
[config.system.sbin.modprobe](https://github.com/NixOS/nixpkgs/blob/3c559278b4b0afd12c6ec4cd9bfb598c9a223d21/nixos/modules/system/boot/modprobe.nix#L11 ) does.
