### ISSUE TITLE
Haskell's refined library is marked as broken

### ISSUE THREAD

**Issue by gvolpe** [NixOS/nixpkgs#83445]
**Describe the bug**

Haskell's library `refined` is mistakenly marked as broken on the unstable channel, release `1fe82110feb`. If I add `allowBroken = true;`, it builds without any issues.

**To Reproduce**

1. `git clone git@github.com:gvolpe/shopping-cart-haskell.git`
2. `nix-shell`

https://github.com/gvolpe/shopping-cart-haskell

**Expected behavior**

The Nix shell is successfully created with all its dependencies.

**Metadata**

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-40-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(gvolpe): `"nixpkgs-20.09pre214374.1fe82110feb"`
 - nixpkgs: `/home/gvolpe/.nix-defexpr/channels/nixpkgs`
```

I'd be happy to put up a PR to get this done if I get some help (never done this before).

**Comment by cdepillabout** [comment]
@gvolpe Please feel free to send a PR marking `refined` as unbroken.

Here are instructions on how to do so:

https://discourse.nixos.org/t/video-tutorial-how-to-fix-broken-haskell-packages-in-nix/3968

**Comment by gvolpe** [comment]
Thanks, I just compiled it on the latest `haskell-updates` branch and it compiles :+1:
