### ISSUE TITLE
removing linux kernel config option gives error: option not set correctly: CGROUP_WRITEBACK (wanted 'n', got 'y')

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#83480]
https://nixos.wiki/wiki/Linux_kernel shows how to add linux kernel
config options, e.g.:

  boot.kernelPatches = [ {
    name = "crashdump-config";
    patch = null;
    extraConfig = ''
            CRASH_DUMP y
          '';
    } ];

however, setting an option to n does not work:

  boot.kernelPatches = [{
    name = "nilfsfix-config";
    patch = null;
    extraConfig = ''CGROUP_WRITEBACK n'';
  }];

gives the following error:

   option not set correctly: CGROUP_WRITEBACK (wanted 'n', got 'y')

Is it possible to remove linux kernel config option?

nixos 19.09.2284.bf7c0f0461e (Loris) x86_64

**Comment by Emantor** [comment]
`CGROUP_WRITEBACK` is a boolean option within the kernel, depending on `CGROUPS [=y] && MEMCG [=y] && BLK_CGROUP [=y]` which can't be deselected.

**Comment by tohl** [comment]
Hi Rouven,

Rouven Czerwinski <notifications@github.com> writes:
> `CGROUP_WRITEBACK` is a boolean option within the kernel, depending on
> `CGROUPS [=y] && MEMCG [=y] && BLK_CGROUP [=y]` which can't be
> deselected.

can't be deselected?  why is it an option then?

It seems like the nilfs2 crash might be caused by a kernel change
related to CGROUP_WRITEBACK so I'd like to try disabling that option and
see if nilfs2 stops crashing.

It doesn't make sense to me that the kernel has options that are
actually no options (with only one possible value).

or do you mean that I need to deselect both MEMCG and BLK_CGROUP?
BLK_CGROUP depends on BLOCK and is n by default
MEMCG does not seem to have default value

actually the error message said that CGROUP_WRITEBACK was y
how do I achieve to have it set to n?

This is the first time I am looking into kernel options so I welcome any
help.

Thanks

Tomas

**Comment by Emantor** [comment]
> Hi Rouven, Rouven Czerwinski <notifications@github.com> writes:
> can't be deselected? why is it an option then?

These are often used to enable features when other features are selected which should not be user configurable. The option is defined in `init/Kconfig` like this:
```
config CGROUP_WRITEBACK
    bool
    depends on MEMCG && BLK_CGROUP
    default y
```
The `bool` is missing a configuration name here, thats why it is not user configurable. As for why, this should be asked upstream. Configurable would Look like this:
```
config CGROUP_WRITEBACK
    bool "Group writeback support"
    depends on MEMCG && BLK_CGROUP
    default y
```

> It seems like the nilfs2 crash might be caused by a kernel change related to CGROUP_WRITEBACK so I'd like to try disabling that option and see if nilfs2 stops crashing. It doesn't make sense to me that the kernel has options that are actually no options (with only one possible value). or do you mean that I need to deselect both MEMCG and BLK_CGROUP? 
> BLK_CGROUP depends on BLOCK and is n by default MEMCG does not seem to have default value actually the error message said that CGROUP_WRITEBACK was y how do I achieve to have it set to n? This is the first time I am looking into kernel options so I welcome any help. Thanks Tomas

This means that you need to deselect one of the dependencies to disable `CGROUP_WRITEBACK`. So either `CGROUPS`, `MEMCG` or  `BLK_CGROUP`.

**Comment by tohl** [comment]
Hi Rouven,

thanks for the great explanation.  Exactly what I needed.

Tomas

**Comment by gianlucarenzi** [comment]
So, no other way to disable **ONLY** than recompiling a new kernel for that? No cmdline parameter like "cgroup.writeback=0" or similar??? It's a real pity I cannot use stock Debian Buster linux kernel as it is... Modifiying kernel is too invasive to me...
