### ISSUE TITLE
vim: markdown syntax highlighting broken

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#83491]
## Issue description

The syntax-highlighting for vim is broken in the current stable version (nixos-19.09, vim-8.2.0013),
especially terminating asterisks do not work.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1785978

## Steps to reproduce

Open vim, set filetype=markdown, enter `This is **bold**, but this should be normal.`
The syntax-highlighting now renders `**, but this should be normal.` as italics.

## Solution/Workaround

vim from unstable (vim-8.2.343) works again.
So please fix in stable or update stable.

## Technical details

broken version:
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  1 1970 00:00:01)
Included patches: 1-13
```

working version from unstable:
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  1 1970 00:00:01)
Included patches: 1-343
```

**Comment by doronbehar** [comment]
This is a Vim issue, not a NixOS issue, I noticed there's also no bug open on Vim's end. Could you try to clone `https://github.com/vim/vim` and run vim with:

```
env VIMRUNTIME=/path/to/vim-repo/runtime vim test.md
```

**Comment by doronbehar** [comment]
Since no reply from OP, closing.
