### ISSUE TITLE
services.xserver.desktopManager.default ignored

### ISSUE THREAD

**Issue by maggesi** [NixOS/nixpkgs#8352]
The configuration
`services.xserver.desktopManager.default = "xfce";`
in `configuration.nix` has no effect.

(I expect that when I log in xfce is loaded, instead kde is loaded.)

**Comment by Wizek** [comment]
@maggesi Shouldn't that be `services.xserver.desktopManager.xfce.enable = true;`?

**Comment by yegortimoshenko** [comment]
`desktopManager.default` option is only there to resolve ambiguity, not to specify desktop manager that you want to install. I think this can be safely closed as now we throw an error if it's invalid:

https://github.com/NixOS/nixpkgs/blob/17.09/nixos/modules/services/x11/desktop-managers/default.nix#L98-L104

@maggesi Is it still an issue?

**Comment by dbwest** [comment]
I am also interested in specifying a defaul desktopManager. I hope this works.
