### ISSUE TITLE
chromium: Disable the hidden closed-source Hotword module by default

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#8358]
If I go to chrome://voicesearch/ I can see that the closed-source Hotword Shared Module was installed without my permission. This module is hidden from the extension list and is allowed to record audio without any permission or notification.

This is way too surprising, unexpected (and some would say unacceptable) behavior for an open-source project. We should disable it by default.

See: https://code.google.com/p/chromium/issues/detail?id=491435
Also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786909
And: https://news.ycombinator.com/item?id=9724409

**Comment by aszlig** [comment]
Thanks for the report, will remove it on Thursday.

**Comment by aszlig** [comment]
Going to sleep while my Hydra builds/tests the [evaluation](https://headcounter.org/hydra/eval/175494), will push (and fix errors if any) after waking up.

**Comment by aszlig** [comment]
Okay, needed to fix a bit more, current evaluation is:

https://headcounter.org/hydra/eval/176023

**Comment by aszlig** [comment]
Fixed by cadd675e7ae4dc1572b0536b8f036b0901dfacde.
