### ISSUE TITLE
chromium: illegible PDF font rendering

### ISSUE THREAD

**Issue by dfoxfranke** [NixOS/nixpkgs#8360]
In the embedded PDF reader in chromium 43, no antialiasing or subpixel rendering is being applied to fonts. This makes documents illegible except at very high zoom levels.

This behavior just appeared with the new nix packaging of chromium 43. Reverting to chromium 41 (which as of this writing is still what's appearing on the unstable channel) makes the problem go away.

All the PDFs I've looked at so far which show this problem were in Comptuer Modern Roman, generated from LaTeX sources. I haven't verified whether it extends to other fonts.

**Comment by dfoxfranke** [comment]
Looks like the same issue as https://code.google.com/p/chromium/issues/detail?id=479400

**Comment by vcunat** [comment]
An upstream bug then, it seems. Judging from https://code.google.com/p/chromium/issues/detail?id=479400#c11 it might be worked around by not using system freetype. /cc maintainers @goibhniu, @chaoflow, @aszlig.
