### ISSUE TITLE
window-managers are not where documentation requires

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#8364]
In the nixpkgs manual, [it is said](http://nixos.org/nixpkgs/manual/#sec-hierarchy):

```
If it’s a desktop environment (including window managers):
    desktops (e.g. kde, gnome, enlightenment)
```

but 37 window-managers are in `applications/window-managers`. Should I change the documentation to reflect this?

**Comment by lethalman** [comment]
I don't know if that hierarchy makes sense at all, but yes we can change it.

**Comment by DamienCassou** [comment]
I that hierarchy does not make sense, I think we should just remove it.
