### ISSUE TITLE
`stdenv.isStatic` to check whether we're creating a static build?

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#83664]
**Describe the bug**
Several times now I've needed to add a patch conditional on whether we're creating a static build. Thus far, the way has been to add a parameter `static` and set it to `true` in `static.nix`. This gets messy in certain cases, such as Python that references itself.

**Comment by FRidh** [comment]
This was partially discussed in https://github.com/NixOS/nixpkgs/pull/65213.

**Comment by FRidh** [comment]
> This gets messy in certain cases, such as Python that references itself.

Turns out it's not actually an issue.

**Comment by matthewbauer** [comment]
I think you can always pass in some sort of isStatic / buildStatic / enableStatic argument in the package function, of course this requires maintaining it at two places, as the overlay has to know about it as well.

Perhaps it could be useful in certain situations though. In an ideal world all of these packages and their build systems would have uniform `--enable/disable-static` and `--enable/disable-shared` switches. Obviously the tons of overrides in static.nix shows we are a long way off for that.

I'm not sure if I exactly like "isStatic". Probably a better name is `isStaticLibraries` and `isStaticBinaries` for each of the stdenv adapters.

**Comment by FRidh** [comment]
I'm thinking `callPackage` should also start considering configuration parameters, not just packages. That would clean up `static.nix` considerably. We have `config` but that makes it harder to override when `config` is the parameter.
https://discourse.nixos.org/t/package-set-wide-configuration-and-callpackage/6216

**Comment by Ericson2314** [comment]
We have `*Platform.isStatic` now!

**Comment by Ericson2314** [comment]
See also #107238
