### ISSUE TITLE
Zotero cannot open file chooser dialog

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#83699]
**Describe the bug**
Zotero crashes whenever it tries to open the file chooser (e.g. when you try to install addons, or add a file to a reference), complaining that no GSettings schemas are installed on the system:

```
(zotero:17678): GLib-GIO-ERROR **: 17:57:10.802: No GSettings schemas are installed on the system
/nix/store/r4b8x5x7v3cb40cnlg5zwi0kdc1cw2rm-zotero-5.0.83/bin/.zotero-wrapped: line 13: 17678 Trace/breakpoint trap   (core dumped) "$CALLDIR/zotero-bin" -app "$CALLDIR/application.ini" "$@"
```

**To Reproduce**
1. Run Zotero
2. Tools -> Add-ons
3. In the new window, click the settings cog -> Install Add-on From File...
4. Crash

**Expected behavior**
Zotero opens the file chooser dialog (from Gtk3)

**Additional context**
I am only running xmonad with no desktop environment, which might explain why `$GSETTINGS_SCHEMA_DIR` is unset - the problem is that it's looking for `org.gtk.Settings.FileChooser`. As a workaround, one can set the value of `GSETTINGS_SCHEMA_DIR` to `${gtk3}/share/gsettings-schemas/gtk+3-3.24.14/glib-2.0/schemas/`.
Glancing at the Zotero's nixexpr, it's using `wrapGAppsHook` and `gtk3` is listed as a build input, so I'm not sure why this is happening.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09.git.1752a52e1ec (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre217537.d96bd3394b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zotero
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
@NickHu can you see if adding `wrapGAppsHook` to `nativeBuildInputs` fixes this, and file a PR if it does?

**Comment by worldofpeace** [comment]
(also glib to buildInputs if it isn't there already)

**Comment by NickHu** [comment]
@flokli Yes, it is strange that `wrapGAppsHook` is listed in `buildInputs` - it should definitely go in `nativeBuildInputs`, however, this does not seem to fix the problem (neither does @worldofpeace's suggestion)

**Comment by worldofpeace** [comment]
Maybe phases is messing this up https://github.com/NixOS/nixpkgs/blob/592507780c4e8f851d67b9ad6510663697e332b3/pkgs/applications/office/zotero/default.nix#L47. It should instead probably set `dontBuild = true;` `dontConfigure = true;`

**Comment by NickHu** [comment]
@worldofpeace can confirm why this addresses the issue. Could you please elaborate on why `glib` needs to be in `buildInputs`? It seems to work either way.

**Comment by worldofpeace** [comment]
@NickHu See https://nixos.org/nixpkgs/manual/#sec-language-gnome and the first item in https://nixos.org/nixpkgs/manual/#ssec-gnome-common-issues. GLib has a setup hook for gsettings-schemas that wrapGAppsHook needs

**Comment by worldofpeace** [comment]
It can work either way because gtk3 propagates it, but it still should be added.
