### ISSUE TITLE
xdg_utils: missing/impure runtime dependencies

### ISSUE THREAD

**Issue by Chattered** [NixOS/nixpkgs#8377]
The `xdg-open` script uses `which` to find executables, but `which` is not one of its dependencies.

**Comment by vcunat** [comment]
Yes, it also uses grep and some coreutils, and maybe more. I didn't look too closely.

**Comment by garbas** [comment]
i had this in my nixpkgs forgot to push it upstream. anyway here it is ... not sure if this is all.

**Comment by geerds** [comment]
Can we close this issue?

**Comment by vcunat** [comment]
I suppose, until some more deps are found...
