### ISSUE TITLE
Mark failing to build packages in 20.03 as broken

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#83805]
**Describe the bug**
As Per ZERO Hydra Failure https://github.com/NixOS/nixpkgs/issues/80379, we're supposed to mark every package that fails to build on the stable branch as broken. People can backport fixes to unbreak packages after we cut the final release. This is best done all at once semi-automatically, so this will be a task for @disassembler and I to perform when we are about to cut the final release. (in a PR please :exclamation:)

**Comment by symphorien** [comment]
Is it possible to not only mark these packages as broken but also ping their maintainers?
See https://discourse.nixos.org/t/please-fix-all-packages-which-were-broken-by-the-qt-wrapping-changes/6444/8 and some later posts for a motivation.

**Comment by worldofpeace** [comment]
@symphorien I don't think GitHub allows that many @'s

**Comment by jtojnar** [comment]
I believe @sorki expressed some interest in this on IRC.

**Comment by sorki** [comment]
On it, currently looking for a way to add/remove meta.broken programmatically. Then I need to find a way to match builds from Hydra channel with attributes and right files.

**Comment by vcunat** [comment]
I'd perhaps try `builtins.unsafeGetAttrPos` on the `meta` attribute or something similar, but even so it might not be 100%.
