### ISSUE TITLE
acme module does not renew certificates obtained from the staging server

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#83800]
**Describe the bug**

1. I prepared myself to add a vhost, so I set `security.acme.production=false`
2. Well, it has been removed, so I set `security.acme.server= "https://acme-staging-v02.api.letsencrypt.org/directory"` as recommended in the error message.
3. added my vhost, rebuilt
4. removed the line added in 2
5. rebuilt. All vhosts (even preexisting ones!) now serve invalid certificates obtained from the staging server.

Expected: a new, valid certificate is requested for hosts where only an invalid staging certificated is available.

I had already done a similar procedure at least once in the past, and I don't remember noticing this behavior at the time. So I think it may be a regression. Otherwise, one could classify this as a request for enhancement instead of a bug report.

**Metadata**
 - system: `"x86_64-linux"`                                                                      
 - host os: `Linux 5.5.13, NixOS, 20.03beta874.b0c285807d6 (Markhor)`                            
 - multi-user?: `yes`                                                                            
 - sandbox: `yes`                                                                                
 - version: `nix-env (Nix) 2.3.2`                                                                
 - channels(root): `"nixos-20.03beta874.b0c285807d6, nixos-unstable-20.09pre217446.ddf87fb1baf"` 
 - channels(symphorien): `"home-manager-19.09"`                                                  
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`                                 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: security.acme
```

**Comment by arianvp** [comment]
Great catch. It doesn't sound too hard to add.

**Comment by m1cr0man** [comment]
If we include the server option in the hash for the cert data it should be possible to fix this.

**Comment by symphorien** [comment]
I haven't tried to reproduce again but still interested.

**Comment by m1cr0man** [comment]
Hey so I think this is solved now. I did end up including the server option [in the hash](https://github.com/NixOS/nixpkgs/blob/4e55c8bc6703699a016093e9bf745bd713bcdfba/nixos/modules/security/acme.nix#L118) which is used to check for configuration changes that should trigger a full renewal, and I have tested it myself. I'll close this issue now but feel free to reopen it if you see it happening still.
