### ISSUE TITLE
Segfault in sudo or pam_ssh_agent_auth

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#83870]
**Describe the bug**

After upgrading to NixOS 20.03, sudo often (but not always) segfaults:
```
$ sudo -i
Segmentation fault
```

From the logs:
```
Mar 31 14:03:40 vyr kernel: sudo[7607]: segfault at 5592619e2000 ip 00007efd01c84685 sp 00007ffedecefd48 error 6 in libcrypto.so.1.1[7efd01adb000+1aa000]
```

Disabling `security.pam.enableSSHAgentAuth` appears to have made this problem to away, so the problem may be in `pam_ssh_agent_auth`.

**Metadata**

NixOS 20.03.20200328.b0c2858

**Comment by worldofpeace** [comment]
@edolstra Maybe the patch to use a not insecure openssl is the source of the issue for you https://github.com/NixOS/nixpkgs/commit/b6b3e047593dff14c871214bf5df691a8c2c23ed

**Comment by wmertens** [comment]
same issue here - the sourceforge repo is way old, there's a github mirror but not maintained either, and there's a fork of the mirror which includes fixes for openssl 1.1.1: https://github.com/eric-brechemier/pam_ssh_agent_auth

**Comment by wmertens** [comment]
Hmm, kinda forgot about this

**Comment by wmertens** [comment]
I missed the fact that the "supported" branch didn't actually include the patch to fix this.
