### ISSUE TITLE
isabelle: version 2014 no longer available to download

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#8391]
@jwiegley, you seem to be the guy for this job.
I have tried to update the nix expression for Isabelle2015, but the update is not trivial (java paths, polyml paths, etc).

Not really urgent to me, but nobody will be able to install this package now that it has been removed from upstream.

**Comment by matthiasbeyer** [comment]
Maybe you could provide a patch which marks the package as broken?

**Comment by vbgl** [comment]
Isabelle-2014 is still available for download. I’ve fixed the URL in 542d203.
Updating to isabelle-2015 is still an open issue, though.

**Comment by layus** [comment]
thanks !
