### ISSUE TITLE
Package request: KNOME desktop

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixpkgs#83961]
**Project description**

Knome is the new joint DE by Gnome and KDE which brings immediate synergy fusion power now.
By adopting Knome we can harvest the benefits of maintaining a single DE instead of two.

**Metadata**

* homepage URL: https://knome.org/ 
* source URL: https://knome.org/
* license: AFL*
* platforms: linux

**Comment by devhell** [comment]
Oh my.... screw my workload, gonna go package that right now! :rofl:

**Comment by worldofpeace** [comment]
This is literally an april fools day joke.

**Comment by wamserma** [comment]
Yes. AFL* is the April Fool's License, not to be confused with AFL, the Academic Free License.
@devhell @worldofpeace Thanks for playing along!
