### ISSUE TITLE
nixos.vimPlugins.youcompleteme fails to start server

### ISSUE THREAD

**Issue by chrissound** [NixOS/nixpkgs#83977]
ycmd seems to fail starting the 'server':

```
2020-04-01 14:02:06,299 - DEBUG - No global extra conf, not calling method YcmCorePreload
2020-04-01 14:02:06,300 - ERROR - ycm_core library not detected; you need to compile it by running the build.py script. See the documentation for more details.
Traceback (most recent call last):
  File "/home/chris/.config/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 480, in ImportAndCheckCore
    ycm_core = ImportCore()
  File "/home/chris/.config/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 471, in ImportCore
    import ycm_core as ycm_core
ModuleNotFoundError: No module named 'ycm_core'
```

**To Reproduce**
```
nix-env -iA nixos.vimPlugins.youcompleteme
```

Vim configured with:
```
Plug 'ycm-core/YouCompleteMe'
```

**Metadata**

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.102, NixOS, 19.09.2070.b9cb3b2fb2f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2070.b9cb3b2fb2f, unstable-20.03pre212770.cc1ae9f21b9"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ryneeverett** [comment]
If I understand you correctly you're using vim-plug directly to manage your plugins and wanting to use the global vimPlugins.youcompleteme package to avoid building YCM with vim-plug. I believe other distros support this use case but I don't think we do. (It would probably be exposed separately as a top-level package rather than within vimPlugins.) As far as I know nixpkg's vimPlugins are only supported using [nixpkg's vimPlugins infrastructure](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md).

**Comment by ryneeverett** [comment]
Looks like nixos.ycmd may be what you're looking for.

**Comment by chrissound** [comment]
That does not seem to be the case: 

```
nix-shell -p ycmd --run python3
Python 3.9.0a3 (default, Jan 24 2020, 21:42:57) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ycm_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ycm_core'
```

Strange, I don't actually see what is responsible for bringing in the python module though. Everything seems to be correct in https://github.com/NixOS/nixpkgs/blob/7a411e7ad673a2cd87d125a49aa38dbc0e6c1785/pkgs/development/tools/misc/ycmd/default.nix otherwise.

**Comment by ryneeverett** [comment]
I believe the issue is the library is not added to the `PYTHONPATH` because ycmd is built with the generic `mkDerivation` rather than `buildPythonPackage`.

**Comment by teto** [comment]
closing because stale. Feel free to reopen if you can still reproduce.
