### ISSUE TITLE
perl warning: setting locale failed

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#8398]
When some perl scripts are run, this warning message is outputted:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

Here's my nix configuration: https://github.com/andrewrk/dotfiles/blob/e3bf84568abe49af84c5bb45c0954d3a1d5f73fa/nixconfigs/configuration.nix

**Comment by edolstra** [comment]
Make sure `$LOCALE_ARCHIVE` is set in the context where you're running those scripts.

**Comment by andrewrk** [comment]
Pardon my ignorance, but could you link to some documentation about what `LOCALE_ARCHIVE` is and what value it should be set to?

**Comment by edolstra** [comment]
On NixOS, it should be set to `/run/current-system/sw/lib/locale/locale-archive`.

**Comment by andrewrk** [comment]
```
[nix-shell:~]$ echo $LOCALE_ARCHIVE
/run/current-system/sw/lib/locale/locale-archive
```

In this example I'm building some stuff with [mxe](http://mxe.cc/) but I'll see if I can come up with a simpler test case for reproducing the problem.

**Comment by aragnon** [comment]
On Ubuntu, I also get this. IMHO, this is a source of impurity, which should be eliminated.

**Comment by joepie91** [comment]
Ran into this issue on openSUSE Leap 42.1 as well, and it actually broke the installation of the Brackets package for me. This workaround worked for me:

```bash
nix-env -iA nixpkgs.glibcLocales
```

Then add the following to the end of your `.bashrc`: 

```bash
export LOCALE_ARCHIVE="$(readlink ~/.nix-profile/lib/locale)/locale-archive"
```

Then restart your shell, and reinstall the package if needed. Not sure how to do the latter correctly - I went for the nuclear option by removing the store paths and running a repair, but that might have undesirable consequences. Perhaps @edolstra can clarify on the correct way to do this?

I don't know whether this workaround affects non-Nix stuff - as far as I can tell, `$LOCALE_ARCHIVE` is a Nix thing.

I do agree that this seems like a source of impurity, and should probably be fixed somehow.

Ref #6878.

**Comment by dezgeg** [comment]
For those who are getting this outside NixOS, https://github.com/NixOS/nix/issues/599 is likely related.

**Comment by davorb** [comment]
In case anyone else is having this issue, I fixed it by adding the following to my `.zshrc`:

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by instantepiphany** [comment]
To add visibility in search engines, I was experiencing this issue with non-perl programs - bash and python to be specific. The cause for me, I believe, is that I have my system (NixOS) following the stable channel, but my user environment following the unstable channel. My theory (I don't have any understanding of locale settings or `(nixos|nixpkgs).glibcLocales`) is that my user environment (unstable) derivations were not compatible with the system locales from the stable channel.

Following @joepie91's suggestion above fixed my problem.

**Comment by nbp** [comment]
I have the same issue and @joepie91 suggestion did not work for me.
Running `nix-env -u \*` fixed a few issues with `grep` and `git grep`, but I still have the `perl` error message which makes `mosh` unusable.

**Comment by domenkozar** [comment]
merging into https://github.com/NixOS/nixpkgs/issues/38991

**Comment by wpcarro** [comment]
@joepie91 fix seemed to work for me. I'm just using `nix-env` and I'm confused about how this issue arose. I'm new to Nix, but my limited understanding gave me confidence that installations should bundle every dependency they needed to run properly. Needing to set `LOCALE_ARCHIVE` in my `~/.profile` (of all places) feels like a leaky workaround, which makes me uncomfortable.

Can someone help me better understand what exactly is going on? I've read in other threads that this is an issue with `glibc` version `2.27`. That's about all I understand at the moment. Any pointers would be greatly appreciated.

**Comment by nbp** [comment]
Adding a comment here, at least for future me.

When updating NixOS, `mosh` no longer works and raises the issue mentioned above.
The solution is to update `mosh` as well, with `nix-env -u mosh --leq` to update its `perl` dependency and fix this issue, as it is installed in user-land and not with NixOS.

**Comment by hasufell** [comment]
> export LOCALE_ARCHIVE="$(readlink ~/.nix-profile/lib/locale)/locale-archive"

This file does not exist on my installation.

```
$ ls ~/.nix-profile/lib/                                                                  Tue 10:22
  libnixexpr.so      libnixmain.so     libnixutil.so    pkgconfig
  libnixformat.so    libnixstore.so    perl5            systemd
```

**Comment by aaronjanse** [comment]
Perhaps this issue should be re-opened? It seems to still be an issue on a fresh Ubuntu install, and it's very discouraging for new users

**Comment by tmnvanderberg** [comment]
Currently experiencing this

**Comment by danyildiabin** [comment]
Also experiencing this on nearly-fresh install. I'm using fish shell if this is somehow connected.

**Comment by rumpelsepp** [comment]
I am experiencing this with `sudo`. The reason is that `sudo` strips `LOCALE_ARCHIVE` from the environment. `sudo -E` is a workaround.

**Comment by forgondolin** [comment]
I also just saw this for me, outta nowhere.
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "pt_BR",
        LC_ALL = (unset),
        LC_ADDRESS = "pt_BR.UTF-8",
        LC_NAME = "pt_BR.UTF-8",
        LC_MONETARY = "pt_BR.UTF-8",
        LC_PAPER = "pt_BR.UTF-8",
        LC_IDENTIFICATION = "pt_BR.UTF-8",
        LC_TELEPHONE = "pt_BR.UTF-8",
        LC_MEASUREMENT = "pt_BR.UTF-8",
        LC_TIME = "pt_BR.UTF-8",
        LC_NUMERIC = "pt_BR.UTF-8",
        LANG = "pt_BR"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by rumpelsepp** [comment]
I somehow fixed it with this: https://github.com/rumpelsepp/nixos-hosts/blob/7099bb2f59363d5e6fc6453199ab2b73fdba0ccf/hosts/kronos/configuration.nix#L79-L95

Found by trial and error…
