### ISSUE TITLE
Why does `location.provider` exist?

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#84013]
**Describe the bug**
If you set `location.provider` to `geoclue2` it enables `geoclue2`.
It seems to exist only for `clight`.

cc @eadwu and @Infinisil maybe?

**Comment by matthewbauer** [comment]
It can probably be removed if this is the only place it's used. It looks like it means "is location.latitude and location.longitude set and should it be used to determine location".

I think location.latitude and location.longitude should probably just default to null and we only set those values when it's not null.

**Comment by Infinisil** [comment]
It also exists for the redshift module. This was done on my request in https://github.com/NixOS/nixpkgs/pull/64309, since both redshift and clight would have exactly the same options for location.

**Comment by jonringer** [comment]
the redshift module doesn't consume provider though, only lat/long. from what I saw, it was only there to do `services.geoclue2.enable = true;` see https://github.com/NixOS/nixpkgs/pull/84019

**Comment by Infinisil** [comment]
@jonringer It very much does:
https://github.com/NixOS/nixpkgs/blob/f75c11cfdfff3448623250e151cb47df70d4f224/nixos/modules/services/x11/redshift.nix#L107-L109

**Comment by jonringer** [comment]
could be re-written as:
```
 providerString = if !services.geoclue2.enable
   then "${toString lcfg.latitude}:${toString lcfg.longitude}" 
   else "geoclue2";
```

**Comment by worldofpeace** [comment]
It's certainly an interesting thing, but I'm not sure any action is needed on it.
