### ISSUE TITLE
Packaging Request: Jitsi Meet Electron

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#84082]
Related to #82805

**Project description**

Jitsi Meet desktop application powered by Electron

**Metadata**

* homepage URL: https://github.com/jitsi/jitsi-meet-electron
* source URL: https://github.com/jitsi/jitsi-meet-electron
* license: Apache-2.0
* platforms: unix, linux, darwin,

**Comment by wamserma** [comment]
+1 as the App seems to have some benefits over using just a browser. Whoever starts working on this, please remember to deactivate the auto-update functionality.

**Comment by petabyteboy** [comment]
Also I would suggest to make sure we are using a recent version of Electron and nodejs, as don in this fork: https://github.com/freifunkMUC/jitsi-meet-electron/

**Comment by prusnak** [comment]
There was a 2.0.0 release two days ago: https://github.com/jitsi/jitsi-meet-electron/releases

I think this fixes the outdated dependencies issue mentioned in the previous comment.

**Comment by petabyteboy** [comment]
Yes a pull request from the fork I mentioned before was accepted.

**Comment by prusnak** [comment]
I created a preliminary package in https://github.com/NixOS/nixpkgs/pull/84898

However, I am not able to run it. Maybe someone with more Electron experience can me help (in the PR).

**Comment by prusnak** [comment]
I fixed the outstanding issues and PR https://github.com/NixOS/nixpkgs/pull/84898 is ready for review
