### ISSUE TITLE
llvmPackages and llvmPackages_latest are outdated

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#84099]
## Update: Current progress

- `llvmPackages`: #85151
- `llvmPackages_latest`: #84096

## Issue description

- `llvmPackages` still points to LLVM 7, while version 10 is already out now.
- `llvmPackages_latest` could/should be bumped to LLVM 10, as #83350 is merged now.

cc:
- Maintainers: @lovek323 @7c6f434c @dtzWill
- Recent PRs: @DieGoldeneEnte @ggreif

Note: This is optional and I'm not familiar with the process here, but to me it seems like it would be a good time to bump both aliases, if someone has time for it (noticed this while reviewing the LLVM 10 backport).

**Comment by DieGoldeneEnte** [comment]
The PR for this is #84096 :)
Wanted to wait until the other passed,

**Comment by bqv** [comment]
That PR is only for llvmPackages_latest, no? Why on earth is llvmPackages still pointing at 7?

**Comment by DieGoldeneEnte** [comment]
@bqv correct, I missed the llvmPackages part, I am now looking into it and will open a PR once I know it works on linux.
It could be a problem for darwin, since it uses clang as default compiler as far as I know.

**Comment by bqv** [comment]
@Mic92 this is not cosed until https://github.com/NixOS/nixpkgs/pull/85143 is merged.

**Comment by primeos** [comment]
It was closed automatically due to the link to this issue. I agree that this issue is still not resolved, thanks for pointing that out. However, I also think we can use #85151 now instead of this issue to track the rest of the work (I don't think this issue adds much value as I'm sure that PR will remain active - but I can of course also re-open this issue if desired).

@DieGoldeneEnte and @LnL7 thank you very much for working on this! :)
