### ISSUE TITLE
Package nix-diff does not seem to be broken

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#84116]
## Issue description
This package is marked as broken, but I successfully installed and used it. What is the procedure for the hackage2nix packages?

### Steps to reproduce
Try to install the package `nix-diff`, notice it is marked broken.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09.git.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-18.09.2574.a7e559a5504"`
 - channels(terje.larsen): `""`
 - nixpkgs: `/home/terje.larsen/src/github.com/terlar/nix-config/external/nixpkgs`

**Comment by cdepillabout** [comment]
See https://discourse.nixos.org/t/video-tutorial-how-to-fix-broken-haskell-packages-in-nix/3968 for how to unbreak packages like `nix-diff`.
