### ISSUE TITLE
home-assistant/ha-ffmpeg: try to use ffmpeg from PATH

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#84140]
**Describe the bug**
Home assistant's ONVIF integration uses ha-ffmpeg to run ffmpeg. It fails to find ffmpeg.

It seems like we need to patch ha-ffmpeg to access `${pkgs.ffmpeg}/bin/ffmpeg` instead.

**Comment by mweinelt** [comment]
Should be covered by https://github.com/benleb/surepy/commit/f0bfffa32aaf07e5285db68395d64f59e6ca9873.
