### ISSUE TITLE
Update OpenSSL 1.0.2a to 1.0.2c

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#8415]
Needed for updating io.js

**Comment by copumpkin** [comment]
Does io.js actually need these minor version updates or is it just expressing a preference for them?

**Comment by Havvy** [comment]
I think it's probably just a preference, though leaving people vulnerable to the widely publicized vulnerabilities is probably not a good idea. I'm not sure of any other packages currently using this version of OpenSSL.

**Comment by wkennington** [comment]
Yeah this should definitely be bumped forward and shouldn't cause any
rebuild issues.

**Comment by vcunat** [comment]
2b was a security bump. Pushed directly to master, as no other package uses it.
