### ISSUE TITLE
Not getting binaries from the zalora repo for OSX 10.10

### ISSUE THREAD

**Issue by usharf** [NixOS/nixpkgs#8419]
Seems like all installations end up compiling from source. 

In my 'nix.conf' I have:

```sh
binary-caches = http://zalora-public-nix-cache.s3-website-ap-southeast-1.amazonaws.com/ http://cache.nixos.org/ http:\
//hydra.nixos.org/
```

**Comment by Fuuzetsu** [comment]
This is not really an issue for nixpkgs. The Zalora repo was a community-provided repository. I believe @shlevy set it up (correct me if I'm wrong) but he is no longer with us at Zalora so I don't know what its state is.

Either way you should seek whoever is overseeing the Zalora cache, nixpkgs is the wrong place to file this.

**Comment by shlevy** [comment]
The cache should still be up and running, compiling from both master and pure-darwin. I'm still maintaining it with the guys at Zalora, feel free to email me directly with issues.

**Comment by usharf** [comment]
Thanks guys. 
Should I be getting binaries from the other bin caches setup in my conf file? It doesn't seem like I do. Just tried installing gnupg and I seem be compiling all the dependencies (which is killing my mbp).

**Comment by Fuuzetsu** [comment]
Try seeking help in #nixos or ##nix-darwin on Freenode, easier to help that way.

**Comment by usharf** [comment]
@Fuuzetsu thanks, I will
