### ISSUE TITLE
Packaging the OWL graphical editor Eddy

### ISSUE THREAD

**Issue by koslambrou** [NixOS/nixpkgs#84195]
**Project description**
A graphical editor for the specification and visualization of Graphol ontologies.

**Metadata**

* homepage URL: https://www.obdasystems.com/eddy
* source URL: https://github.com/obdasystems/eddy
* license: gpl3
* platforms: linux

**Comment by koslambrou** [comment]
PR awaiting to be merged: #95857

**Comment by abathur** [comment]
This was added in https://github.com/NixOS/nixpkgs/pull/115261
