### ISSUE TITLE
Package request: transmission-qt

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#84290]
**Project description**
The QT variant of the Transmission bittorrent client.

**Metadata**

* homepage URL: https://transmissionbt.com/
* source URL: https://github.com/transmission/transmission
* license: GPL-2.0 or GPL-3.0
* platforms: linux

The QT client notably is able to connect to a remote daemon a bit like `transmission-remote-gtk`, but also rename remote files, a feature missing from both `transmission-remote-gtk` and `transmission-remote-cli` as far as I can tell. `stig` has this feature, but is not a graphical client and also doesn't build successfully right now.

**Comment by MetaDark** [comment]
transmission-qt was added in 83018f4fc6c47419c5fb0e12852fe3ff4759449a
