### ISSUE TITLE
package request: musikcube

### ISSUE THREAD

**Issue by evertedsphere** [NixOS/nixpkgs#84318]
**Project description**

"a cross-platform, terminal-based audio engine, library, player and server written in c++"

**Metadata**

* homepage URL: https://musikcube.com/
* source URL: https://github.com/clangen/musikcube
* license: bsd
* platforms: linux, darwin, windows (?)

**Comment by fabaff** [comment]
Is now [available](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=musikcube).
