### ISSUE TITLE
s3cmd: ERROR: [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#8431]
When I try to use s3cmd I get an error:

```
$ s3cmd ls s3://superjoe/
ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

I verified that accessing my s3 account via a different program worked fine.

```
$ nixos-version 
15.06pre64030.e1af50c (Dingo)
```

config: https://github.com/andrewrk/dotfiles/blob/master/nixconfigs/configuration.nix

**Comment by domenkozar** [comment]
Relevant to #8247

**Comment by domenkozar** [comment]
So that's Python HTTP  failing ssl certificate validation. Most probably s3cmd doesn't have set CA bundle location

**Comment by rushmorem** [comment]
@domenkozar This might not be a Python only problem. Seems like Amazon's SSL certificates have a broken chain of trust lately. For example, trying to check `s3.amazonaws.com` using [SSLShopper's SSL Checker](https://www.sslshopper.com/ssl-checker.html#hostname=s3.amazonaws.com), I'm getting:
```
The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. You can fix this by following Symantec's Certificate Installation Instructions for your server platform. Pay attention to the parts about Intermediate certificates.
```

and if I try with curl...

```
[bash:~]$ echo $SSL_CERT_FILE
/etc/ssl/certs/ca-certificates.crt

[bash:~]$ curl -L https://s3.amazonaws.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by domenkozar** [comment]
Hmm https://www.ssllabs.com/ssltest/analyze.html?d=s3.amazonaws.com&s=54.231.244.1&latest looks good

**Comment by rushmorem** [comment]
Even though that test appears to pass, if you look closely you will see that certificate has "chain issues".  Look under "Additional Certificates (if supplied)", you will see that it says `Chain issues	Extra certs`.

I had also tried the `SSL Labs` tool but I preferred to link the `SSL Checker` result because in this case it is more explicit. Last time (a couple of weeks back. I think), I could "curl" that URL just fine.

**Comment by rushmorem** [comment]
@domenkozar I've just realised that on `NixOS 15.06pre62649.f93a8ee` I can still curl that URL fine but on `NixOS 15.06pre64030.e1af50c` I no longer can but I can still curl other HTTPS endpoints fine.

**Comment by domenkozar** [comment]
Hmmm, @wkennington @vcunat any ideas? I think something changed again regarding CA bundles

**Comment by vcunat** [comment]
Interesting, as the behavior changes without changing the certificate bundle. However, curl from *both* revisions you specified fail for me (but my own still succeeds).
```
$ ./result/bin/curl -v -L https://s3.amazonaws.com
* Rebuilt URL to: https://s3.amazonaws.com/
*   Trying 54.231.12.136...
* Connected to s3.amazonaws.com (54.231.12.136) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2, TLS handshake, Client hello (1):
* TLSv1.2, TLS handshake, Server hello (2):
* TLSv1.2, TLS handshake, CERT (11):
* TLSv1.2, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
...
```

**Comment by vcunat** [comment]
And it "regresses" for me on some other locations, too (tried local https://seznam.cz), but most importantly, https://nixos.org is OK ;-)

After picking just the openssl bump 415407bd93 it curls all these again. I can't see anything relevant in the news file https://github.com/openssl/openssl/blob/OpenSSL_1_0_1-stable/NEWS#L16, but I guess that the behavior of only a few versions in-between was wrong.

**Comment by vcunat** [comment]
Unless someone's willing to dig deeper upstream, I think we can close with *fixed in staging*.
