### ISSUE TITLE
Feature request: additional dictionaries for wps-office

### ISSUE THREAD

**Issue by fusion809** [NixOS/nixpkgs#84327]
**Describe the bug**
This isn't a bug report, but I can't seen an option to file a feature request and that is what this is. I want WPS Office to have additional dictionaries available, and there is a way to achieve this. This [repository directory](https://github.com/wps-community/wps_community_website/tree/master/root/download/dicts) has zip archives, that if decompressed and their contents placed in $out/usr/lib/office6/dicts/spellcheck, should add these dictionaries to WPS Office. The AUR has a package that does this for the UK English dictionary (en-GB.zip) and it works perfectly. I'm afraid I don't know how to do this for nixpkgs myself, I don't really know enough about Nix packaging to do this.

@Ninlives: pinging you as this is your package.

**Comment by Ninlives** [comment]
You can add something like this in a file under ~/.config/nixpkgs/overlays to archieve this:
```nix
self: super: {
    wpsoffice = let dict = builtins.fetchurl { url = "<url/of/zip/file>"; sha256 = "..."; };
    in super.wpsoffice.overrideAttrs (attrs: {
        installPhase = attrs.installPhase + ''
           ${super.unzip}/bin/unzip ${dict} -d $out/opt/kingsoft/wps-office/office6/dicts/spellcheck
        '';
    });
}
```
Check the build result, there may be something wrong in the command args but you got the idea.
I almost give up maintaining the wpsoffice package because I do not have enough skill to solve problems listed in this PR and recently tend to use Google Doc or Office inside a VM: https://github.com/NixOS/nixpkgs/pull/82408

**Comment by fusion809** [comment]
Thanks mate, I'm happy with that as a workaround. Although, it does prevent me from having `wps = callPackage ...` in my `~/.config/nixpkgs/overlays.nix`. I ordinarily have that line in that so that I can run the latest wpsoffice that I have specified in my own fork of the nixpkgs repo.

**Comment by Ninlives** [comment]
This is a bit ugly but should work: `wps = (callPackage ...).overrideAttrs(...)`.
There may be a better solution, but I'm too hungry now to come up with one.

**Comment by fusion809** [comment]
With the help of the NixOS community I've found an alternative:

```nix
  wpsoffice = let dict = builtins.fetchurl { url = "https://github.com/wps-community/wps_community_website/raw/master/root/download/dicts/en_GB.zip"; sha256 = "0056c14xjx7zz90cla4xajr6qznlim4lnr22cp3gfiqkvm32dzx0"; };
   in fork.wpsoffice.overrideAttrs (attrs: {
        installPhase = attrs.installPhase + ''
           ${super.unzip}/bin/unzip ${dict} -d $out/opt/kingsoft/wps-office/office6/dicts/spellcheck
        '';
    });
```

Thanks for trying to help though, I do appreciate it. :)
