### ISSUE TITLE
Leksah in NixOS 14.12 - fails to install

### ISSUE THREAD

**Issue by jhegedus42** [NixOS/nixpkgs#8442]
Details:

http://stackoverflow.com/questions/30958505/leksah-in-nixos-14-12-fails-to-install-why

**Comment by peti** [comment]
Please see the responses on that very page. That build failure did not occur on the release-14.12 branch. I don't believe a package for Leksah even exists in that branch.

**Comment by jhegedus42** [comment]
sorry, yes, it is in unstable
