### ISSUE TITLE
contributing guide: Commit message name not clear

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8444]
The `CONTRIBUTING.md` states:

> * Format the commit in a following way:
> 
> ```
> (pkg-name | service-name): (update from -> to | init at version | refactor | etc)
> 
> Additional information.
> ```

but also:

> * Examples:
>   * foo-pkg: init at 2.0.1
>   * bar-pkg: update 3.0 -> 3.1.1
>   * lala-service: add bazBaz option
>   * tata-service: refactor config generation

So I'm not sure whether I should name my commit now

```
systemd: init at 123
```

or 

```
systemd-pkg: init at 123
```

Can someone clearify this please?

**Comment by matthiasbeyer** [comment]
@jagajaga Just told me which one is right in https://github.com/NixOS/nixpkgs/pull/8443#issuecomment-113890756

I'd like to see clearification in the guide, though.

**Comment by jagajaga** [comment]
> Format the commit in a following way:
> **(pkg-name | service-name)**: (update from -> to | init at version | refactor | etc)

So the `-pkg` part in the example is a part of a name. You have to write only name (of pkg, of service), nothing more.

**Comment by matthiasbeyer** [comment]
I'd like to propose that we rewrite the examples from:

```
foo-pkg: init at 2.0.1
bar-pkg: update 3.0 -> 3.1.1
lala-service: add bazBaz option
tata-service: refactor config generation
```

to

```
fooPkg: init at 2.0.1
barPkg: update 3.0 -> 3.1.1
lalaService: add bazBaz option
tataService: refactor config generation
```

Which is, IMHO much clearer. I can more clearly see that there is no `-pkg` postfix after the actual package name.

If you want me to, I can write the patch myself.

**Comment by domenkozar** [comment]
What about real examples like:

```
nginx: init at 2.0.1
firefox: 3.0 -> 3.1.1
hydra service: add bazBaz option
nginx service: refactor config generation
```

**Comment by matthiasbeyer** [comment]
@domenkozar even better!

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/commit/ef22e1157bfa33e47c11e5134b85af0244046998

**Comment by matthiasbeyer** [comment]
:+1:
