### ISSUE TITLE
Installing "ruby" does not provide "bundler", but the helptext says so.

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8445]
```
$ bundler help
The program ‘bundler’ is currently not installed. You can install it by typing:
  nix-env -i ruby
```

This is wrong. When installing "ruby" (I actually have ruby installed) bundler is not available. When installing "bundler", it is:

```
nix-env -iA pkgs.bundler
bundler help # brings up manpage
```

I'm not sure whether this should be reported here or elsewhere, though.

**Comment by philandstuff** [comment]
This seems to be fixed for me, because the helptext refers to attribute path, not package name:

    $ bundler
    The program ‘bundler’ is currently not installed. You can install it by typing:
      nix-env -iA nixos.bundler_HEAD
