### ISSUE TITLE
nixos/tests/taskserver fails

### ISSUE THREAD

**Issue by jtraue** [NixOS/nixpkgs#84507]
**Describe the bug**
nixos/tests/taskserver does not succeed. The test has failed for a while: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.taskserver.x86_64-linux

**To Reproduce**
`nix-build nixos/tests/taskserver.nix`

**Expected behavior**
The test should pass.

**Additional context**
The two subtests fail with the following message:
```
error: command `su - bar -c 'gnutls-cli --x509cafile=/home/bar/.task/keys/ca.cert --x509keyfile=/home/bar/.task/keys/private.key --x509certfile=/home/bar/.task/keys/public.cert --port=53589 server < /dev/null'' unexpectedly succeeded 
```
These tests address the deletion of users and organizations. They check that certificates are revoked when a user/organization is deleted and fail because the certificates continue to exist. The delete functionality is not part of the taskserver package - it comes from `nixos/modules/services/misc/taskserver/helper-tool.py`.

/cc @tfc

**Comment by wamserma** [comment]
Looking at the logs and the [diffs between the last good and the first broken test}(https://hydra.nixos.org/api/scmdiff?type=git&rev2=32767d139f28fd3c00d687c04ec406258f7341e7&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev1=fa82ebccf66eef185d063d49a9e294a7a1e15d36&branch=), it seems something changed the behaviour of `gnutls-cli` - either the update from 3.6.2 to 3.6.6 or something in the environment causes swallowing of its outputs.

log from passed test:
```
client1: must fail: su - bar -c 'gnutls-cli --x509cafile=/home/bar/.task/keys/ca.cert --x509keyfile=/home/bar/.task/keys/private.key --x509certfile=/home/bar/.task/keys/public.cert --port=53589 server < /dev/null'
client1# [   97.274372] su[1177]: Successful su for bar by root
client1# [   97.277968] su[1177]: pam_unix(su:session): session opened for user bar by (uid=0)
client1# *** Fatal error: The TLS connection was non-properly terminated.
server# [   98.285559] taskd[870]: 2019-02-20 05:00:54 Error: Handshake failed. Error in the certificate.
client1# *** handshake has failed: The TLS connection was non-properly terminated.
client1# [   97.424443] su[1177]: pam_unix(su:session): session closed for user bar
client1: exit status 1
(0.17 seconds)
```

log from failed test:
```
client1: must fail: su - bar -c 'gnutls-cli --x509cafile=/home/bar/.task/keys/ca.cert --x509keyfile=/home/bar/.task/keys/private.key --x509certfile=/home/bar/.task/keys/public.cert --port=53589 server < /dev/null'
client1# [   48.990939] su[928]: Successful su for bar by root
client1# [   49.005016] su[928]: pam_unix(su:session): session opened for user bar by (uid=0)
server# [   49.615531] taskd[926]: 2020-05-22 01:41:54 Error: Handshake failed. Error in the certificate.
client1# [   49.193260] su[928]: pam_unix(su:session): session closed for user bar
client1: exit status 0
```
note the missing error messages from `gnutls-cli`.
