### ISSUE TITLE
Package Request: gitlab-pages

### ISSUE THREAD

**Issue by dali99** [NixOS/nixpkgs#84525]
**Project description**
[gitlab-pages](https://docs.gitlab.com/ce/administration/pages/index.html) is a part of gitlab that allows static hosting of sites built by gitlab-ci. It seems like a fairly simple daemon to build and run.

Will take a look at making this work soon myself. But if anyone has more time on their hands and wants to submit a PR don't hesitate!

This would also need to be integrated into the nixos module.

**Metadata**

* homepage URL: https://about.gitlab.com/stages-devops-lifecycle/pages/
* source URL: https://gitlab.com/gitlab-org/gitlab-pages
* license: mit
* platforms: linux

**Comment by flokli** [comment]
cc @thilobillerbeck

**Comment by dali99** [comment]
Still important to me
