### ISSUE TITLE
type_traits not found

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#84552]
With the hopes that someone possibly running into this issue _maybe_ being able to find something; I'm leaving a note here (most google results are about reinstalling stuff and don't drill into the underlying issue):

If you're trying to parse qt headers with clang similar to: 
```
NIX_DEBUG=1 CLANG_INSTALL_DIR=/nix/store/bznxa332165jfr1mgs88a92ilc3aq5ij-clang-7.1.0 clang -xc++ -std=c++11 -stdlib=libc++ -nostdinc++ -I /nix/store/8n70nbqwpnpnl5rf6p48m18g09ki8y4s-libc++-7.1.0/include/c++/v1/ -I qtheaders/include/ -fsyntax-only qtheaders/include/QtWidgets/QPushButton -v
```

If you get errors like
```
qtheaders/include/QtCore/qglobal.h:45:12: fatal error: 'type_traits' file not found
```
-- the reason is because you dont have the `libcxx` includes in your search path (which `type_traits`[1] is a part of, and not `type_traits.h` which is in `includes/llvm/Support`).

This I have half kludged in with the above command (there's probably a better way to do this) via https://libcxx.llvm.org/docs/UsingLibcxx.html 

[1] https://en.cppreference.com/w/cpp/header/type_traits

**Comment by prehonor** [comment]
> `NIX_DEBUG=1 clang -xc++ -std=c++11 -stdlib=libc++ -nostdinc++ -I $(nix-build --no-out-link '<nixpkgs>' -A llvmPackages.libcxx)/include/c++/v1/ -I qtheaders/include/ -fsyntax-only qtheaders/include/QtWidgets/QPushButton -v`

Hi, I still got this error, when I tried to compile smokeqt from https://github.com/commonqt/commonqt5/,
this is my mkshell.nix https://github.com/prehonor/nixscript/blob/master/project/qt5env.nix

this is log :
[  0%] Generating smokedata.cpp, x_1.cpp, x_2.cpp, x_3.cpp, x_4.cpp, x_5.cpp, x_6.cpp, x_7.cpp, x_8.cpp, x_9.cpp, x_10.cpp, x_11.cpp, x_12.cpp, x_13.cpp, x_14.cpp, x_15.cpp, x_16.cpp, x_17.cpp, x_18.cpp, x_19.cpp, x_20.cpp
using generator "/home/prehonor/.local/bin/../lib/smokegen/generator_smoke.so"
didn't find file "/home/prehonor/CLionProjects/smokeqt/build/qtdefines"
parsing "/home/prehonor/CLionProjects/smokeqt/qtcore/qtcore_includes.h"
In file included from /home/prehonor/CLionProjects/smokeqt/qtcore/qtcore_includes.h:1:
In file included from /nix/store/q2s73wjkn5shgn2swp1gwibvzwipnlyi-qtbase-5.15.3-dev/include/QtCore/QtCore:4:
/nix/store/q2s73wjkn5shgn2swp1gwibvzwipnlyi-qtbase-5.15.3-dev/include/QtCore/qglobal.h:45:12: fatal error: 'type_traits' file not found
#  include <type_traits>
           ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [qtcore/CMakeFiles/smokeqtcore.dir/build.make:75: qtcore/smokedata.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:259: qtcore/CMakeFiles/smokeqtcore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
