### ISSUE TITLE
Could the default hash value of `fetchGit` be something of the correct length?

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#84625]
This would help with being able to copy-paste from the error message more easily..

Here:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/default.nix

**Comment by flokli** [comment]
I don't understand the question TBH.

**Comment by NorfairKing** [comment]
The default hash value is `""` instead of `"000000000000....00"` with the correct amount of zeroes. As a result the error message doesn't show the right hash and instead just says that the hash is of an incorrect length.

**Comment by flokli** [comment]
… if you don't pass a hash in first place, right?

**Comment by flokli** [comment]
Do you want to file a PR changing this?

**Comment by NorfairKing** [comment]
> … if you don't pass a hash in first place, right?

That's right

> Do you want to file a PR changing this?

I'd like to know if this is a good change first.
One possible concern could be: "what if a file has a 000..000 hash?"

**Comment by kylesferrazza** [comment]
>  "what if a file has a 000..000 hash?"

Seems like this could easily be avoided by changing the error message for a blank string to output the correct hash instead of relying on filling in zeroes to get to the error message.

**Comment by NorfairKing** [comment]
> Seems like this could easily be avoided by changing the error message for a blank string to output the correct hash instead of relying on filling in zeroes to get to the error message.

Absolutely! That's even better.

**Comment by flokli** [comment]
I fear the current error message when not providing a hash is coming from nix itself, and I don't think adding an intermediate layer into nixpkgs for everything using fixed-output derivations is desirable. I propose opening an issue to nix itself. Also note there have been some changes recently, and hashes are moving to [SRI hashes](https://www.w3.org/TR/SRI/). `fetchgit` is still hardcoded to `sha256` for now, but this might change - have a look at `fetchurl` for example.

**Comment by matthewbauer** [comment]
Tried to do this in https://github.com/NixOS/nix/pull/3544. An annoying thing is it assumes that you want the 0 hash, which I guess could be a valid thing in some cases.
