### ISSUE TITLE
gnome-boxes: unable to use ISO installation media

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#84637]
**Describe the bug**
As per the title.

**To Reproduce**

1. Try to install Fedora 31 / Windows 10 in a fresh VM via gnome-boxes.

**Expected behavior**

Installation is successful and the VM is usable.

**Screenshots**

N/A

**Additional context**

Initially the installation aborts with `'startupPolicy' is only valid for 'file' type volume`. This appears to be an upstream `libvirt` issue - https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/481
Fixing the above starting the VM aborts with `Unable to find any firmware to satisfy 'bios'`. This appears to be an upstream `gnome-boxes` issue - https://gitlab.gnome.org/GNOME/gnome-boxes/issues/488
Applying the `libvirt` patch from Fedora and using `gnome-boxes` 3.36.2 mitigates both issue and allows the installation and subsequent booting of the VM to succeed.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.30, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(pbogdan): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

nixpkgs revision 39247f8d04c04b3ee629a1f85aeedd582bf41cac

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by pbogdan** [comment]
Hmm, I'm somehow back to getting the first error even with the patch applied. No clue I how managed to get it working temporarily...

**Comment by flokli** [comment]
I didn't fully read everything on the linked issues, but this reads to me like "get the proposed fix into libvirt and ask for a release" and "bump gnome-boxes to 3.36.2".

If it's not feasible to get a libvirt release soon, and the patch is applied in fedora, we could `fetchpatch` the patch inside our nix derivation and apply it to libvirt.

Do you want to file 2 PRs doing this? ;-)

**Comment by worldofpeace** [comment]
@flokli We're about to update GNOME to the point release, that involves updating gnome-boxes. @hedning @jtojnar  and I probably would have found this out anyway (I actually tested boxes yesterday and figured this out).

**Comment by pbogdan** [comment]
Boxes update is now in https://github.com/NixOS/nixpkgs/pull/84694 

The libvirt patch is actually included upstream - https://gitlab.com/libvirt/libvirt/-/commit/3918dbd84e4951b43f93fbf50ef52be00274850c 

From what I see it's part of 6.2.0 release with NixOS / nixpkgs currently shipping 6.1.0. I could test the version bump locally instead of patching 6.1.0 but I'm hestitant to submit an update myself as I know next to nothing about libvirt stuff so would prefer to leave it to someone else.

**Comment by pbogdan** [comment]
Boxes update is now in master :laughing: And coupled with a local libvirt bump to 6.2.0 the issue is fixed for me.

**Comment by flokli** [comment]
@pbogdan I propose filing a PR bumping libvirt nevertheless. The nix changes required to do the bump should be minimal, you'll provide an easy way for others to test it, and get back feedback about potential breakages.

**Comment by pbogdan** [comment]
Alright, will do in a bit. Only changes I needed locally were bumping the version / hash / src but then I only tested my specific use case.
