### ISSUE TITLE
MenuLibre

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NixOS/nixpkgs#84652]
**Project description**

An advanced menu editor that provides modern features in a clean, easy-to-use interface. MenuLibre is developed for users who want to manage their menus without ever needing to read the spec or use a text editor. Budgie, Cinnamon, GNOME, KDE (Plasma), LXDE, LXQt, MATE, Pantheon, Unity, and Xfce are all supported.

**Metadata**

* homepage URL: https://bluesabre.org/menulibre
* source URL: https://github.com/bluesabre/menulibre
* license: gpl3
* platforms: linux

**Comment by davidak** [comment]
This project now managed on GitHub: https://github.com/bluesabre/menulibre

- Code: https://github.com/bluesabre/menulibre
- Bugs: https://github.com/bluesabre/menulibre/issues
- Translations: https://www.transifex.com/bluesabreorg/menulibre
- Wiki: https://github.com/bluesabre/menulibre/wiki

Homepage: https://bluesabre.org/menulibre/

**Comment by louwers** [comment]
There's a module helper function [make-desktopitem](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/make-desktopitem/default.nix) that can generate `.desktop` files. Not as easy to use as menulibre of course, but reproducible.

**Comment by TheEvilSkeleton** [comment]
> This project now managed on GitHub: https://github.com/bluesabre/menulibre
> 
>     * Code: https://github.com/bluesabre/menulibre
> 
>     * Bugs: https://github.com/bluesabre/menulibre/issues
> 
>     * Translations: https://www.transifex.com/bluesabreorg/menulibre
> 
>     * Wiki: https://github.com/bluesabre/menulibre/wiki
> 
> 
> Homepage: https://bluesabre.org/menulibre/

Thank you. I edited the description for it to be accurate

**Comment by pshirshov** [comment]
Well, it would be good to have a formula for this.

**Comment by daemonspudguy** [comment]
This would be really useful. I would write a derivation but I'm not confident in my Nix skills to do so.
