### ISSUE TITLE
Tartube

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NixOS/nixpkgs#84655]
**Project description**

Tartube is a GUI front-end for youtube-dl, partly based on youtube-dl-gui and written in Python 3 / Gtk 3.

**Metadata**

* homepage URL: https://tartube.sourceforge.io/
* source URL: https://github.com/axcore/tartube
* license: gpl3
* platforms: linux

**Comment by pbogdan** [comment]
I can't say I tested it extensively but here's my current derivation I have kicking around in a local overlay - https://gist.github.com/pbogdan/12caf879d07cd7b8ae3bf1fdf1f65d49

Should at the very least be a starting point for someone.

**Comment by TheEvilSkeleton** [comment]
Thank you so much. I'll keep this issue open until someone decides to close it.

**Comment by pbogdan** [comment]
You're welcome. And the issue should probably be kept open until someone contributes a derivation to nixpkgs proper (which I don't plan to for time being btw).
