### ISSUE TITLE
GOverlay

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NixOS/nixpkgs#84685]
**Project description**

GOverlay is a GUI to manage graphical overlays such as vkBasalt and MangoHud.

**Metadata**

* homepage URL: https://github.com/benjamimgois
* source URL: https://github.com/benjamimgois/goverlay
* license: gpl3
* platforms: linux

**Comment by MetaDark** [comment]
@TheEvilSkeleton I have GOverlay packaged in my [NUR repo](https://github.com/MetaDark/nur-packages/blob/9602514d17dbe4c7b947d202ff1a8a25d98dde2b/pkgs/tools/graphics/goverlay/default.nix), but I don't think it would make sense to submit a pull request until [MangoHud](https://github.com/NixOS/nixpkgs/issues/84686) and [vkBasalt](https://github.com/NixOS/nixpkgs/pull/92401) are in nixpkgs.

**Comment by TheEvilSkeleton** [comment]
> @TheEvilSkeleton I have GOverlay packaged in my [NUR repo](https://github.com/MetaDark/nur-packages/blob/9602514d17dbe4c7b947d202ff1a8a25d98dde2b/pkgs/tools/graphics/goverlay/default.nix), but I don't think it would make sense to submit a pull request until [MangoHud](https://github.com/NixOS/nixpkgs/issues/84686) and [vkBasalt](https://github.com/NixOS/nixpkgs/pull/92401) are in nixpkgs.

I appreciate it a lot. Unfortunately, I left NixOS and switched from NixOS due to having so many issues with gaming, Lutrix, GNOME, etc. I'm still looking forward to this. Thank you so much

**Comment by MetaDark** [comment]
@TheEvilSkeleton Aww that's frustrating, NixOS can definitely a pain some times, but I find it worth it. Hopefully we will see you back again when things are better. I'm not a huge gamer, but I've managed to deal with all the issues I've had so far with gaming.

**Comment by TheEvilSkeleton** [comment]
@MetaDark I'm planning to join back anyway sooner or later. I love configuration.nix, and Flatpak has helped a LOT. The only the problem currently is that there's no official Lutris Flatpak, so I can't really play any games from Lutris since the official package in nixpkgs was quite broken

**Comment by MetaDark** [comment]
@TheEvilSkeleton My only issue I had with Lutris was that it crashed when the file dialog was opened, but that was fixed in https://github.com/NixOS/nixpkgs/issues/90645. Did you have any other problems?

**Comment by TheEvilSkeleton** [comment]
@MetaDark Lutris was just not launching games, but I will try it someday, once I have the time for that.

*I just realized that I could've and should've created an issue when I had this problem*

**Comment by bryanasdev000** [comment]
Up!
