### ISSUE TITLE
librsvg broken on darwin

### ISSUE THREAD

**Issue by kylesferrazza** [NixOS/nixpkgs#84690]
**Describe the bug**
The latest channel update to `nixos-unstable` seems to have broken `librsvg` on darwin.

See my build output here:
https://github.com/kylesferrazza/nix/runs/569661756?check_suite_focus=true#step:5:643

Hydra job:
https://hydra.nixos.org/job/nixpkgs/trunk/librsvg.x86_64-darwin

Maintainer information:
```yaml
attribute:
- librsvg
```

**Comment by Kha** [comment]
Notably, this prevents `nixpkgs-unstable` from advancing

**Comment by Kha** [comment]
Hopefully fixed by https://github.com/NixOS/nixpkgs/pull/84458
