### ISSUE TITLE
[20.03] backport newer webkitgtk

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#84696]
Only the newest iteration of webkitgtk (2.28.x) receives security updates, we should therefor backport to the stable channel. I did attempt this a few months back, but got some build failures. It should hopefully be smoother this time around as 2.26 already contains the multi-process stuff which caused problems IIRC.

cc @worldofpeace @jtojnar

**Comment by onny** [comment]
I also would like to see newer versions backported. I'm trying to get the program ``foliate`` running but it requires at least ``webkitgtk`` version 2.28 (the nur package I'm using: https://git.project-insanity.org/onny/nur-packages/-/blob/master/pkgs/applications/office/foliate/default.nix)
