### ISSUE TITLE
Chromium downloads binary blob - should we patch this?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8471]
As some of you might have heard, [chromium downloads binary blobs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786909).

Should we patch this in nixos? Maybe a opt-out/opt-in patch? Or is this already patched?

**Comment by jb55** [comment]
See cadd675e7ae4dc1572b0536b8f036b0901dfacde
