### ISSUE TITLE
termite sets unknown TERM variable

### ISSUE THREAD

**Issue by ehahn** [NixOS/nixpkgs#8473]
Termite sets the TERM variable to xterm-termite. There is a terminfo definition in `~/.nix-profile/share/terminfo` but apparently no program looks there. The TERMINFO_PATH variable is unset.

I'm using plain Nix on Linux. Programs installed via Nix also cannot find the terminfo definition.

**Comment by zimbatm** [comment]
On NixOS the `TERMINFO_DIRS` is set properly. Can you confirm that this is still an issue in other Linuxes ?

On remote NixOS servers I also add `termite.terminfo` to the `environment.systemPackages` but sshing into debian boxes is always a pain because of the missing terminfo

**Comment by rardiol** [comment]
Not sure how related this is, but I'm also having a problem with termite's terminfo not being found on nixos. I do have a $TERMINFO_DIRS set, but none of them contain xterm-termite.

**Comment by zimbatm** [comment]
Did you add `termite` or `termite.terminfo` to your systemPackages?

**Comment by rardiol** [comment]
I just tried that, now it wants to compile gtk+ and a dozen other stuff....

But why do I have to add it to systemPackage? Can't a user install a terminal?

**Comment by zimbatm** [comment]
Right now it's part of the nixos modules mechanism. As part of the `environment.profileRelativeEnvVars` variable it will look into all the packages with a `share/terminfo` folder and populate the environment variable accordingly. I think we should move that on a package level to support the user scenario like you remarked.

**Comment by rardiol** [comment]
I don't know how this part of nix works, but why can't the user installed terminfo get linked into ~/nix-profile/share/terminfo? It seems it works for ~/nix-profile/share/applications for example.

**Comment by zimbatm** [comment]
It will but TERMINFO_DIRS also needs to be set to point to that folder. Right now `~/.nix-profile/etc/profile.d/nix.sh` sets a couple of environment variables not TERMINFO_DIRS and I also don't see an extension mechanism to it.

**Comment by ocharles** [comment]
Note that not installing termite as a system package means things like `sudo` will mess up, as `TERMINFO_DIRS` will change.

**Comment by tomberek** [comment]
close as resolved?
