### ISSUE TITLE
 The hyperswarm js library cannot find the other nodes in a nixos test.

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#84740]
**Describe the bug**
The `hyperswarm` js library cannot find the other nodes in a nixos test.

**To Reproduce**
1. `git clone https://github.com/pasqui23/hackerchat`
2. `nix-build test.nix -A t.driver`
3. `./result/bin/nixos-run-vms`
4. In the qemu terminals spawned run `hackerchat`

**Expected behavior**
In each terminal `hackerchat`,using `hyperswarm`,would find the other nodes and print 
```
✅  Your network is hole-punchable!
🎉 new friend 0!
```

**Screenshots**
![20200408_194326-1](https://user-images.githubusercontent.com/6931743/78817269-74e4f600-79c2-11ea-8d63-6b778fab4e86.png)
**Additional context**
`hyperswarm` is a node.js library to build p2p applications and `hackerchat` is a trivial chat app built on top.
To note that `npx hackerchat` work normally with a true NixOS laptop connected to the internet.
Also pinging to the other vms works with the ip address inserted manually

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09pre218613.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200220_4a4521f`
 - channels(root): `"nixos-20.09pre218613.ae6bdcc5358, home-manager"`
 - channels(paki): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by pasqui23** [comment]
Of note that adding a node with coturn enabled in the network still does not work
https://nixos.org/nixos/options.html#coturn.enable

**Comment by Emantor** [comment]
Did you open up the firewall on your nodes? Looking at the source code hackerchat requires port 31337 to be open.

**Comment by pasqui23** [comment]
Still relevant.In fact I encounter the same problem with `hyperswarm-web`

**Comment by pasqui23** [comment]
Cannot check this again
