### ISSUE TITLE
Document wine's builder-wow.sh

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#8476]
@bendlas can you explain the purpose of `build-wow.sh` and `wineWow` and whatnot? A comment somewhere would be great. Does `wine64` not work? I remember back in the day when wine was 32-bit only there were some problems but maybe now that changed?

**Comment by bendlas** [comment]
wineWow is a mixed 32/64 build, that can run programs of either architecture. See here http://wiki.winehq.org/Wine64

I'll add a comment, the next time I touch the wine package

**Comment by Fuuzetsu** [comment]
OK, http://wiki.winehq.org/Wine64ForPackagers shed some light on this. I'll close issue but dropping a comment when you can there would be great, thanks.

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/pull/9137
