### ISSUE TITLE
python3Packages.vtk: can't be used to satisfy a dep on vtk due to missing packaging metadata

### ISSUE THREAD

**Issue by bcdarwin** [NixOS/nixpkgs#84774]
`python3Packages.vtk` works in the sense that `import vtk` succeeds, but any Python package which lists `vtk` as a dependency (currently there are none in Nixpkgs) fails to install with `ERROR: Could not find a version that satisfies the requirement vtk`, probably since `lib/python3.7/site-packages` directory contains no `vtk-7.1.1.dist-info` or similar.

Also see #75125 - `z3` has a similar issue and is packaged in a similar way via `toPythonModule`.

@knedlsepp

**Comment by knedlsepp** [comment]
I worked around this issue for mayavi too: https://github.com/NixOS/nixpkgs/blob/f5a65df77c1a142ebbfbd5bc32cbe445fb5c3b13/pkgs/development/python-modules/mayavi/default.nix#L17
Probably should be fixed in vtk itself.

**Comment by bcdarwin** [comment]
This is still unresolved.

**Comment by bcdarwin** [comment]
Will be closed by #208522.
