### ISSUE TITLE
Chromium doesn't see WideVine component needed by Netflix, even if enabled

### ISSUE THREAD

**Issue by travisbhartwell** [NixOS/nixpkgs#8479]
I attempted to watch Netflix with Chromium and got this error:

![netflix](https://cloud.githubusercontent.com/assets/10110/8325007/fd5cb276-1a12-11e5-9a15-e7cdf08eb942.png)

I saw in pkgs/applications/networking/browsers/chromium/plugins.nix an option `enableWideVine` exists, which I did like this in my configuration.nix:

```
  nixpkgs.config = {
    chromium = {
      enablePepperFlash = true;
      enablePepperPDF = true;
      enableWideVine = true;
    };
  };
```

After doing `nixos-rebuild switch` I see that a directory ending in `chromium-binary-plugins-widevine` exists.  Even after restarting the browser, this same error still shows up.  I was running chromiumBeta and I even downgraded to the regular stable chromium package and still no luck.

I'm running an up-to-date NixOS unstable channel.

How can I help debug this?  I'm Nafai on #nixos.

**Comment by badi** [comment]
I see this as well.


In my `~/.nixpkgs/config.nix`:
```
  allowUnfree = true;

  chromium = {
    enablePepperFlash = true;
    enablePepperPDF = true;
    enableWideVine = true;
  };
```

From `chrome://version` (full content below) I see that the widevide `.so` exists:
```
$ file /nix/store/kc99yzqnb51idfc17vz7y4y4h4136lk5-chromium-binary-plugins-widevine/lib/libwidevinecdmadapter.so
/nix/store/kc99yzqnb51idfc17vz7y4y4h4136lk5-chromium-binary-plugins-widevine/lib/libwidevinecdmadapter.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a31ee5335effa7e3b8724bc6a448b4146cbaeebc, stripped
```

Contents of `chrome://version`:
```
Chromium	43.0.2357.124 (Developer Build) (64-bit)
Revision	11832b02dce94758da67c44a4bdbf1ab191a0d99
OS	Linux 
Blink	537.36 (@196519)
JavaScript	V8 4.3.61.27
Flash	18.0.0.160
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
Command Line	/nix/store/pdia27w9l97gxqivra7vxy07510hn8z9-chromium-43.0.2357.124/libexec/chromium/chromium --ppapi-flash-path=/nix/store/whgnhqh8vbwkxxy1wgz0xiwxi57shmms-chromium-binary-plugins-flash/lib/libpepflashplayer.so --ppapi-flash-version=18.0.0.160 --register-pepper-plugins=/nix/store/kc99yzqnb51idfc17vz7y4y4h4136lk5-chromium-binary-plugins-widevine/lib/libwidevinecdmadapter.so#Widevine Content Decryption Module#Playback of encrypted HTML audio/video content:application/x-ppapi-widevine-cdm --flag-switches-begin --flag-switches-end
Executable Path	/nix/store/pdia27w9l97gxqivra7vxy07510hn8z9-chromium-43.0.2357.124/libexec/chromium/chromium
```

**Comment by CestDiego** [comment]
I see this as well :( so there is no way of packaging chrome then?

**Comment by aszlig** [comment]
`enableWideVine` only registers the WideVine Pepper plugin, but it seems there are more components involved for getting it to work. And I also have a gut feeling that (one of) this could be NaCl (see also: #8560).

Can anyone confirm that?

**Comment by aszlig** [comment]
Also, can anyone test whether f098967293d9fc018badb3e3a7d7339f3e11aa9a improves anything or even fixes the whole issue?

**Comment by CestDiego** [comment]
@travisbhartwell

**Comment by travisbhartwell** [comment]
@CestDiego I'm compiling to test as I write this comment. :)  Will report back.

**Comment by benley** [comment]
With f098967 applied, the widevine plugin should show up in chrome://plugins, but netflix is still unhappy.  I also applied #8560 and was able to get NaCl working (naclbox games work, for instance), but unfortunately that also does not fix netflix. I don't really know how to debug widevine any further at the moment... any clues would be very welcome.

**Comment by travisbhartwell** [comment]
I had this compiling already and can confirm the same as @benley.  It shows up in chrome://plugins.  Interestingly, I get a different error before when I try to play a video in Netflix.  As shown in my screenshot above, I had `Error code: M7357-1003`.  Now I get `Error Code: M7357-1269`.

Looking around on Netflix's help page, I found this, which of course, only had instructions for Mac and Windows:

https://help.netflix.com/article/en/node/25703

But the interesting thing is that it seems like something should be showing up in `chrome://components` named `WidevineCdm` as well as the `Widevine Content Decryption Module` that shows up in `chrome://plugins`.

So something else needs to be done for the component to show up.  What, I'm not sure.

I'm not sure if this is related, but I saw this in the Console when I opened the developer tools:
 > requestMediaKeySystemAccess() is deprecated on insecure origins in the specification. Support  will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by benley** [comment]
I checked on an Ubuntu system where netflix is working in chrome, and it appears that there is *not* a WidevineCdm component that shows up in `chrome://components`, even when everything is working.

**Comment by badi** [comment]
I get the same result as @travisbhartwell with f098967.

**Comment by msteen** [comment]
I just installed NixOS and tried to use Netflix after installing chromium with wide vine enabled, but I also get the error code M7357-1269. Most other Linux distributions package both Chromium and Google Chrome. I may be naive here, but would packing Google Chrome besides Chromium be a solution? Because as far as I understand, the differences between Chromium and Google Chrome that Google Chrome comes prepackaged with a bunch of extra stuff including the DRM plugins and some extra branding.

**Comment by msteen** [comment]
I have packaged Google Chrome and can confirm that Netflix works without a problem. For those who are interested, I made a pull request #10324.

**Comment by benley** [comment]
That is pretty awesome, @msteen - thanks for working on that!

**Comment by puffnfresh** [comment]
I'm playing Netflix right now using Chromium. Just had to use a patch from Arch Linux:

https://projects.archlinux.org/svntogit/packages.git/tree/trunk/chromium-widevine.patch?h=packages/chromium

**Comment by puffnfresh** [comment]
Closed in 492ccdd52d0ab63584057e08e21e79da04e7cc37

**Comment by colemickens** [comment]
I'm still experiencing this. Both with `chromium` and `chromiumDev` with `nixpkgs.config.chromium.enableWidevine = true`.

PepperFlash works, but Widevine does not.

**Comment by cheecheeo** [comment]
@colemickens Try the config `chromium.enableWideVine = true` note the capital _V_.

**Comment by colemickens** [comment]
That did the trick, thanks @cheecheeo !

**Comment by jgillich** [comment]
Does anyone know how to make it work with Amazon Video? It's telling me I don't have WideVine installed, but according to `chrome://plugins/` I do have it.

**Comment by cstrahan** [comment]
@jgillich I'm seeing the exact same thing. Really annoying. Trying to find some sort of test page to make sure it's not just Amazon, and google doesn't turn up anything useful...

**Comment by cstrahan** [comment]
Just tried the `google-chrome` package, and that worked. Comparing `chrome://plugins`, there's an obvious difference: chromium doesn't show "Native Client". That might be key.

**Comment by colemickens** [comment]
What version are you on? I'm watching House of Cards on chromium right now on the latest nixos-unstable.

**Comment by cstrahan** [comment]
@colemickens  The latest nixos-unstable (0bf8a1a86df67649893726d50761567121330006).

**Comment by cstrahan** [comment]
I don't have Netflix, so I can't try that... but I do know that Amazon Video doesn't work for me (they supposedly don't detect WideVine, but my guess is that it really has something to do with the lack of NaCl in our Chromium).

**Comment by notanewbie** [comment]
For me, chrome://plugins shows that I have no plugins. A component with the title "Widevine Content Decryption Module - Version: 0.0.0.0" shows up when I go to chrome://components

I am (ironically) somewhat a newbie when it comes to Linux and have no idea how to use the git file mentioned earlier (https://git.archlinux.org/svntogit/packages.git/tree/trunk/chromium-widevine.patch?h=packages/chromium)

**Comment by puffnfresh** [comment]
@notanewbie that patch is included in nixpkgs, you shouldn't have to do anything with it.

**Comment by MasseGuillaume** [comment]
Still an isssue today:

```
Nixos version: 19.09.2470.4a0df0ce263 (Loris)
Chromium version: 81.0.4044.122 (Developer Build) (64-bit)
```

**Comment by MasseGuillaume** [comment]
ah actually it's an option you need to enable now:

```
nixpkgs.config = {
    allowUnfree = true;
    chromium.enableWideVine = true;
};
```
