### ISSUE TITLE
gst-plugins-bad: consider disabling zbar by default

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#84845]
While packaging a gtk application depending on gst-plugins-bad (it needs the hls decoder), I discovered that gst-plugins-bad by default pulls in qtbase and qtx11extras because of the default dependency on zbar.
This unnecessarily increases the dependency size for gtk applications hugely. gstreamer is a media framework used accross different UI toolkits, so IMHO it should depend on UI toolkit specific stuff as little as possible.
I could just disable zbar support for my build, but honestly I assume that *not* needing zbar support is the default case rather then the other way around.

Alternatively, the zbar expression could be refactored a bit: Enabling video support pulls in *both* qt and gtk3, as it build widgets for both of them. It might be possible to split these 2 widgets up. But then we'd need to somehow pass through gstreamer what toolkit we actually need now.

What do you think of that?

/cc-ing maintainers:
@matthewbauer for gst-plugins-bad
@delroth @7c6f434c for zbar

**Comment by worldofpeace** [comment]
cc @jtojnar who I believe worked on stuff like this last.

**Comment by jtojnar** [comment]
Yeah, I was hit by this again last week. Splitting the derivation at our side is probably the only way. Or maybe we could ask upstream if they would be amenable to making the individual parts buildable separately while depending on the zbar library from system. Last time I was annoyed by this in September, I even started porting the project to Meson to facilitate this.

Until then I am fine with disabling zbar by default. Only thing depending on it I am aware of is `gnome-keysign`.

**Comment by schmittlauch** [comment]
I'm still waiting for the Hydra to build qtbase for me, until I can finish my backport :D 
It's probably a good idea to wait for the other maintainers before preparing a PR.

**Comment by jtojnar** [comment]
I doubt there will be any opposition. Especially since we just recently introduced it https://github.com/NixOS/nixpkgs/pull/54398.

**Comment by schmittlauch** [comment]
I wonder what is the best way to override the `gst-plugins-bad` passed to gnome-keysign to enable zbar.
As the derivation is passed `gst_all_1` where I didn't manage to override just the plugins-bad attribute. While it should be possible to pass all components of `gst_all_1` individually, maybe there is a better way.

**Comment by jtojnar** [comment]
You would just override it inside the expression (see the wine part in https://github.com/NixOS/nixpkgs/commit/9332773e5108b096d1e67fb01158cd1a9530e0b0)

**Comment by 7c6f434c** [comment]
zbar use in gstreamer is indeed not a usecase I have ever been thinking about in my barcode tool use.

**Comment by schmittlauch** [comment]
PR is out

**Comment by muydipalma** [comment]
hi, i have a cuestion, in a fresh arch distro i found this zbar, i was looking for some webcam app and only found this zbarcam and zbarcam-gtk wich freeze my pc, why i cant unistall this zbar? why "gst-plugins-bad" depends on a program to decode barcodes that i nerver would or  ever needed to use? i dont understand

**Comment by jtojnar** [comment]
@muydipalma gst-plugins-bad depends on zbar because it contains a plug-in that decodes bar codes. For webcam app, try [Cheese](https://archlinux.org/packages/extra/x86_64/cheese/).

Also note that this is not really a place for questions like these, https://bbs.archlinux.org/ would probably be better.
