### ISSUE TITLE
es-git: failure while installing from source

### ISSUE THREAD

**Issue by tmmcguire** [NixOS/nixpkgs#8487]
Trying to install es-git, I get:

    $ nix-env -i es-git
    installing ‘es-git-2015-04-11’
    building path(s) ‘/home/mcguire/soft/nix/nix/store/8wxi38yv1rzn7q9g77jnvg2x4k92w7lj-user-environment’
    Wide character in die at /home/mcguire/soft/nix/nix/store/lzwp5qxj464a0w0j5s135d9x2mq7rc58-buildenv.pl line 57.
    collision between directory ‘/home/mcguire/soft/nix/nix/store/p3qbm7ggz152jqgxa8c97dblcgw4xh8s-hello-2.10/share/man/man1’ and non-directory ‘/home/mcguire/soft/nix/nix/store/1aw072yinb2vjg6408m9qhwggp3dpz8x-es-git-2015-04-11/share/man/man1’ at /home/mcguire/soft/nix/nix/store/lzwp5qxj464a0w0j5s135d9x2mq7rc58-buildenv.pl line 57.
    builder for ‘/home/mcguire/soft/nix/nix/store/xykkhwsl4j4vckscn9599s5rqv58ckgi-user-environment.drv’ failed with exit code 255
    error: build of ‘/home/mcguire/soft/nix/nix/store/xykkhwsl4j4vckscn9599s5rqv58ckgi-user-environment.drv’ failed

It appears there is a bug in the upstream package when installing the man page without an existing man/man1 directory. I'll try getting a fix for that together as soon as I remember my `install` voodoo. In the mean time, a fix in `default.nix` is pretty simple; I'll have a pull request shortly. (I'm new here, BTW. Geeze, all these new-fangled hula-hoops and transistor radios....)

**Comment by geerds** [comment]
Fixed: 6c19145
