### ISSUE TITLE
akvcam: alternative to v4l2loopback?

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#84889]
**Project description**

Stumbled upon this, looks like an alternative to v4l2loopback. Might be working packaging and writing a module for: https://github.com/webcamoid/akvcam

**Metadata**

* homepage URL: https://github.com/webcamoid/akvcam
* source URL: https://github.com/webcamoid/akvcam
* license: gpl2
* platforms: linux

**Comment by colemickens** [comment]
still important to me

**Comment by austinbutler** [comment]
This is now packaged, can the issue be closed?

https://github.com/NixOS/nixpkgs/commit/bab529c9fffabc4abd21181f05a6be057219fc3b

**Comment by colemickens** [comment]
A module would be nice, but this issue doesn't say anything about a module! Makes sense to close this. Thanks for the heads up @austinbutler .
