### ISSUE TITLE
Reportpython3.7-cherrypy-18.3.0 build failure

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#84897]
**cherrypy-18.3.0 fails to build**
1. nix-channel --update
2. nixos-rebuild switch

**Expecting a clean rebuild**

**Additional context**
...
XPASS cherrypy/test/test_caching.py::CacheTest::test_antistampede #1536
XPASS cherrypy/test/test_conn.py::LimitedRequestQueueTests::test_queue_full #1535
XPASS cherrypy/test/test_static.py::StaticTest::test_file_stream #1475
SKIPPED [1] /build/CherryPy-18.3.0/cherrypy/test/helper.py:328: skipped (not running HTTPS)...
SKIPPED [5] /build/CherryPy-18.3.0/cherrypy/test/test_session.py:411: memcached not available
SKIPPED [1] cherrypy/test/test_static.py:196: Windows only
= 1 failed, 286 passed, 7 skipped, 1 deselected, 3 xpassed, 1 warning in 135.78s (0:02:15) =
/build/CherryPy-18.3.0/cherrypy/process/wspbus.py:258: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STARTED state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.
  'main thread exits.' % self.state, RuntimeWarning)
kBuild: Compiling RuntimeGuestR3Shared - /build/VirtualBox-6.1.4/src/VBox/Runtime/r3/posix/filelock-posix.cpp
kBuild: Compiling RuntimeGuestR3Shared - /build/VirtualBox-6.1.4/src/VBox/Runtime/r3/posix/ldrNative-posix.cpp
kBuild: Compiling RuntimeGuestR3Shared - /build/VirtualBox-6.1.4/src/VBox/Runtime/r3/posix/RTPathUserDocuments-posix.cpp
builder for '/nix/store/fwrh1p37p823s7v59v4jk3hn93ayzb16-python3.7-cherrypy-18.3.0.drv' failed with exit code 1
cannot build derivation '/nix/store/3p93cka8bfgr57yjhvr5zaij1zma3x2h-mnemosyne-2.7.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/71dax7a2ah6aksrk3wk9x1hsimzfg865-tribler-7.4.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/aqh19w173161f9c86qjfp70mccqsa6s1-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xg9ff4z4kbf6nlmxsvablp8pm9sd9y1f-xsession-wrapper.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5fapgqqjglkpndaxslk1pdq3nfq8sh4l-nixos-system-bx26-20.09pre220217.39247f8d04c.drv': 1 dependencies couldn't be built
error: build of '/nix/store/5fapgqqjglkpndaxslk1pdq3nfq8sh4l-nixos-system-bx26-20.09pre220217.39247f8d04c.drv' failed

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.09pre218613.ae6bdcc5358 (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre220217.39247f8d04c"`
 - channels(k): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by unode** [comment]
I'm seeing this too. One of the tests is failing. I found [a mention](https://github.com/cherrypy/cherrypy/pull/1668#issuecomment-397970893) of the test being flaky upstream. Didn't manage to identify the cause yet.

I don't quite understand the failing test so I'll ask upstream. For now we could try disabling the failing test.

In the meantime there's now a build in `cache.nixos.org` so this is consistent with the flaky status of this test.

Also a slightly more helpful error log below:
```
(... extra lines omitted ...)
cherrypy/test/test_tools.py::ToolTests::testCombinedTools FAILED         [ 86%]
(... extra lines omitted ...)
_________________________ ToolTests.testCombinedTools __________________________

self = <cherrypy.test.test_tools.ToolTests testMethod=testCombinedTools>

    def testCombinedTools(self):
        expectedResult = (ntou('Hello,world') +
                          europoundUnicode).encode('utf-8')
        zbuf = io.BytesIO()
        zfile = gzip.GzipFile(mode='wb', fileobj=zbuf, compresslevel=9)
        zfile.write(expectedResult)
        zfile.close()
    
        self.getPage('/euro',
                     headers=[
                         ('Accept-Encoding', 'gzip'),
                         ('Accept-Charset', 'ISO-8859-1,utf-8;q=0.7,*;q=0.7')])
        self.assertInBody(zbuf.getvalue()[:3])
    
        zbuf = io.BytesIO()
        zfile = gzip.GzipFile(mode='wb', fileobj=zbuf, compresslevel=6)
        zfile.write(expectedResult)
        zfile.close()
    
        self.getPage('/decorated_euro', headers=[('Accept-Encoding', 'gzip')])
        self.assertInBody(zbuf.getvalue()[:3])
    
        # This returns a different value because gzip's priority was
        # lowered in conf, allowing the rotator to run after gzip.
        # Of course, we don't want breakage in production apps,
        # but it proves the priority was changed.
        self.getPage('/decorated_euro/subpath',
                     headers=[('Accept-Encoding', 'gzip')])
>       self.assertInBody(bytes([(x + 3) % 256 for x in zbuf.getvalue()]))

expectedResult = b'Hello,world\xc2\x80\xc2\xa3'
self       = <cherrypy.test.test_tools.ToolTests testMethod=testCombinedTools>
zbuf       = <_io.BytesIO object at 0x7ffff48ce830>
zfile      = <gzip on 0x7ffff49cc390>

cherrypy/test/test_tools.py:374:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/nix/store/73vm9wzl2779zggh5yp4yp3pi2bby7fn-python3.7-cheroot-8.2.1/lib/python3.7/site-packages/cheroot/test/webtest.py:401: in assertInBody
    self._handlewebError(msg)
/nix/store/73vm9wzl2779zggh5yp4yp3pi2bby7fn-python3.7-cheroot-8.2.1/lib/python3.7/site-packages/cheroot/test/webtest.py:254: in _handlewebError
    if not self.interactive:
/nix/store/73vm9wzl2779zggh5yp4yp3pi2bby7fn-python3.7-cheroot-8.2.1/lib/python3.7/site-packages/cheroot/test/webtest.py:98: in __get__
    return self.fget(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cherrypy.test.test_tools.ToolTests testMethod=testCombinedTools>

    @NonDataProperty
    def interactive(self):
        """Determine whether tests are run in interactive mode.
    
        Load interactivity setting from environment, where
        the value can be numeric or a string like true or
        False or 1 or 0.
        """
        env_str = os.environ.get('WEBTEST_INTERACTIVE', 'True')
        is_interactive = bool(json.loads(env_str.lower()))
        if is_interactive:
            warnings.warn(
                'Interactive test failure interceptor support via '
                'WEBTEST_INTERACTIVE environment variable is deprecated.',
>               DeprecationWarning,
            )
E           DeprecationWarning: Interactive test failure interceptor support via WEBTEST_INTERACTIVE environment variable is deprecated.

env_str    = 'True'
is_interactive = True
self       = <cherrypy.test.test_tools.ToolTests testMethod=testCombinedTools>

/nix/store/73vm9wzl2779zggh5yp4yp3pi2bby7fn-python3.7-cheroot-8.2.1/lib/python3.7/site-packages/cheroot/test/webtest.py:244: DeprecationWarning
----------------------------- Captured stdout call -----------------------------

    ERROR: b'"\x8e\x0b\x03~\x97\x94a\x03\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03' not in body: b'"\x8e\x0b\x03~\x97\x94a\x05\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03'
------------------------------ Captured log call -------------------------------
INFO     cherrypy.access.140737297570000:_cplogging.py:284 127.0.0.1 - - [11/Apr/2020:09:57:15] "GET /euro HTTP/1.1" 200 33 "" ""
INFO     cherrypy.access.140737297570000:_cplogging.py:284 127.0.0.1 - - [11/Apr/2020:09:57:15] "GET /decorated_euro HTTP/1.1" 200 35 "" ""
INFO     cherrypy.access.140737297570000:_cplogging.py:284 127.0.0.1 - - [11/Apr/2020:09:57:15] "GET /decorated_euro/subpath HTTP/1.1" 200 35 "" ""
```

**Comment by bachp** [comment]
I did a bisect and the issue accures since the update from Python 3.7.6 to 3.7.7.

**Comment by unode** [comment]
A workaround to this issue that disables the failing test is part of #84954 .
We should still wait for upstream before closing as it's unclear if this affects functionality.

**Comment by webknjaz** [comment]
Looks like it's reproducible in nightly: https://travis-ci.org/github/cherrypy/cherrypy/jobs/674223158#L569.

**Comment by alciono** [comment]
My system is now building correctly. 
Many thanks to whoever fixed the problem!
Closing.
