### ISSUE TITLE
package request: webcamoid

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#84890]
**Project description**
similar to #84889

webcam manipulation software. I'm wondering if I can use it to get my old webcams to go into the "correct" mode that isn't totally useless under Linux. :/ 

**Metadata**

* homepage URL: https://github.com/webcamoid/webcamoid
* source URL: https://github.com/webcamoid/webcamoid
* license: gpl2
* platforms: linux

**Comment by colemickens** [comment]
still important to me

**Comment by fgaz** [comment]
Looks like this was packaged #86261
