### ISSUE TITLE
Remove configurable Java support in browsers, or comment that it does not work?

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#84909]
* The **Chromium** NixOS wiki article https://nixos.wiki/wiki/Chromium#Java says:

  > To use Oracle's JRE as a browser's Java implementation, use the option "jre = true;"

  or

  > use the option "icedtea = true;"

  but these options do not even seem to exist for Chromium, and I cannot find them in the nixpkgs history.
* The **Firefox** NixOS wiki article https://nixos.wiki/wiki/Firefox#Firefox_ESR_and_Oracle_JDK says:
  > Firefox stops support of Java plugin. To use Java plugin you have to use special Firefox ESR, Extended Support Release.
  but that seems impossible with current nixpkgs, as we do not provide the ESR 52 release.
  https://github.com/NixOS/nixpkgs/pull/67214#issuecomment-523636125 says
  > One could technically try to build `firefox-esr-52` with icedtea support
  but this package no longer exists.

It seems that Java browser applet support is completely broken (upstream and for nixpkgs), and these wiki resources as well as the code in the Firefox [`wrapper.nix`](https://github.com/NixOS/nixpkgs/blob/87d321776199bdeb1febfffebac3d496644bd5db/pkgs/applications/networking/browsers/firefox/wrapper.nix#L42) are just misleading and inviting people to spend time on what cannot work anyway.

Does anybody know if it is actually possible to build any browser with Java support in nixpkgs >= 20.03?

If no, I think we should update the wiki and remove these pluging options, or at least comment that they do not work unless you override e.g. Firefox with a much older source code version that nixpkgs does not provide.

**Comment by nh2** [comment]
I have added a sentence in the Firefox and Chromium wiki articles until this is cleared up:

> Note: It is not clear whether this section is out of date, and whether any Firefox release in Nixpkgs allows to use Java. See https://github.com/NixOS/nixpkgs/issues/84909.

**Comment by danbst** [comment]
note, that even if this gonna to be removed, it is still possible to launch Firefox+IcedTea from prebuilt binaries with following overlay entry:
```
  firefofx-esr-icedtea = with (import (builtins.fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/0a70d65fd471e30fc1f300cc4eebaf18b56d90b8.tar.gz) {
    config = {
      firefox = {
        icedtea = true;
      };
    };
  });
    wrapFirefox firefoxPackages.firefox-esr-52 { };
```
I'm active user of this because of banking software (sigh).

I also _think_ it's possible to build this from current nixpkgs with:
```
  ff_java = (import <nixpkgs> {
    config = {
      permittedInsecurePackages = [
        "firefox-52.9.0esr"
        "firefox-esr-unwrapped-52.9.0esr"
      ];
      firefox = {
        icedtea = true;
      };
    };
  }).firefox-esr-52;
```
however I never tried to rebuild ff from source.

**Comment by xaverdh** [comment]
Building from current `nixpkgs`wont work since https://github.com/NixOS/nixpkgs/pull/79115 was merged. Well not on current master anyway.

**Comment by nh2** [comment]
## Firefox

I think Java applet support is now completely gone. https://github.com/NixOS/nixpkgs/blob/0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb/pkgs/applications/networking/browsers/firefox/packages.nix has Firefox ESR 78 which has no support.

So I think we should update the wiki articles to reflect that.

@xaverdh has removed the misleading attributes in PR #85307 for Firefox.

@danbst Would you be up for updating the wiki to share your exact current workaround that uses old nixpkgs? I imagine there are more legacy banking users that would appreciate it.

## Chromium

@gebner You udated the `jre` argument to Chromium in https://github.com/NixOS/nixpkgs/commit/705ecdc1927b5523f6e728f1418af8cfb0eceb88, do you know if it actually still works?

**Comment by gebner** [comment]
> @gebner You udated the `jre` argument to Chromium in [705ecdc](https://github.com/NixOS/nixpkgs/commit/705ecdc1927b5523f6e728f1418af8cfb0eceb88), do you know if it actually still works?

On the contrary, I didn't update anything in *chromium*.  Chromium was already using openjre8 (because `jre = jre8`).  I then updated the default `jre` attribute to `openjdk14`, and changed chromium to use `jre8` explicitly so that I don't need to rebuild it.

I have no idea what chromium uses the jre for, could we upgrade it to openjdk14?

**Comment by primeos** [comment]
I've dropped the Java section of the Chromium page in the NixOS wiki:
https://nixos.wiki/index.php?title=Chromium&type=revision&diff=5826&oldid=5673

https://www.java.com/en/download/help/chrome.html states:
> The Java Plugin for web browsers relies on the cross-platform plugin architecture NPAPI, which had been supported by all major web browsers for over a decade. Google's Chrome version 45 and above have dropped support for NPAPI, and therefore Java Plugin do not work on these browsers anymore.

IIRC Java is being completely removed from Chromium (although last I've checked it was unfortunately still required for building on Linux... :o).

**Comment by tomodachi94** [comment]
> Can we close this issue then?

Yes, definitely.
