### ISSUE TITLE
Correct electron package wrapGAppsHook usage

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#84913]
**Describe the bug**
The electron package tries to wrap in `buildCommand`.
Because of this the wrapper is completely void of any entries in `XDG_DATA_DIRS`.
It needs to be rewritten in whatever fashion that the `makeWrapper` call happens in `postFixup`.

This is why `riot-desktop` has needed to be wrapped recently https://github.com/NixOS/nixpkgs/commit/fe6addbbf717d4977434e81acd7535c3b074e3a3, it's because `electron` isn't wrapped correctly itself. A change should be made to stable to revert this to riot-desktop, and to backport this fix instead.

Expression: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/electron/generic.nix#L59

buildInputs should also have `glib` for it's setup-hook https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/electron/generic.nix#L37.

**Comment by prusnak** [comment]
cc @travisbhartwell @manveru

**Comment by prusnak** [comment]
I started to work on this and posted a draft PR here: https://github.com/NixOS/nixpkgs/pull/84981

I can confirm that the revert in the first commit will cause riot-desktop to crash when a native file dialog is triggered.

However, the second commit (electron fix) is not finished and I need help with it. I moved the `wrapProgram` call into `postFixup` but this fails with:

```
rewriting symlink /nix/store/9a88ajwl2kr0nkywgaf2f2f2iwz2c6p5-electron-7.1.10/bin/electron to be relative to /nix/store/9a88ajwl2kr0nkywgaf2f2f2iwz2c6p5-electron-7.1.10
strip is /nix/store/sq2b0dqlq243mqn4ql5h36xmpplyy20k-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/9a88ajwl2kr0nkywgaf2f2f2iwz2c6p5-electron-7.1.10/lib  /nix/store/9a88ajwl2kr0nkywgaf2f2f2iwz2c6p5-electron-7.1.10/bin
patching script interpreter paths in /nix/store/9a88ajwl2kr0nkywgaf2f2f2iwz2c6p5-electron-7.1.10
checking for references to /build/ in /nix/store/9a88ajwl2kr0nkywgaf2f2f2iwz2c6p5-electron-7.1.10...
not an ELF executable
builder for '/nix/store/pskssipf7k5qq93z8v7inbq4pbrazgm3-electron-7.1.10.drv' failed with exit code 1
cannot build derivation '/nix/store/37pyspyyj88wgwh58zadcijy8nnfa90h-riot-desktop-1.5.15.drv': 1 dependencies couldn't be built
error: build of '/nix/store/37pyspyyj88wgwh58zadcijy8nnfa90h-riot-desktop-1.5.15.drv' failed
```
