### ISSUE TITLE
Could we have fetchurl save files which do not match the checksum?

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#8493]
It should still definitely fail as it does now if the checksum is wrong as well as print both checksums, but it would be good if we could avoid re-downloading the file after correcting the checksum.

I'm not implement this feature but I do find myself downloading the same (large) files two, sometimes three times.

nix-prefetch-url is good but not convenient when used in conjunction with fetchFromGitHub and not exactly practical when changing a large number of files.

One downside is genuinely corrupted files would end up in the store but they would eventually get garbage collected so I don't think that's a big deal.

Thoughts?

**Comment by vcunat** [comment]
- ``nix-prefetch-url`` checks certificates, whereas fetchurl doesn't, at least until now (there's WIP to have that);
- for ``fetchFromGitHub`` and ``fetchzip`` there's ``nix-prefetch-zip``, I think, although it probably still isn't as comfortable to use, unfortunately.

**Comment by bjornfor** [comment]
I'd definitely like this. (I also asked about the same thing a while back.)

**Comment by domenkozar** [comment]
This feature is present as `--hash` in Nix unstable
