### ISSUE TITLE
Some fonts from nerd-fonts are missing 

### ISSUE THREAD

**Issue by albakham** [NixOS/nixpkgs#84947]
**Describe the bug**
Since the recent change to the way nerd-fonts are handled (PR https://github.com/NixOS/nixpkgs/pull/84858), a few fonts from nerd-fonts are not downloaded.

**To Reproduce**
Simply install the nerd-fonts, some part of it won't be downloaded such as "InconsolataGo" and "UbuntuMono".

**Expected behavior**
All fonts should be specified in this file : https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/nerdfonts/shas.nix, for now some are missing.

**Comment by worldofpeace** [comment]
cc @doronbehar

**Comment by worldofpeace** [comment]
@albakham It's very important to ping the maintainers of the package so they can see the bug.
