### ISSUE TITLE
How can I undefine a systemd option

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#84955]
_I would like to document the answer to:_

A NixOS-provided service module I am using sets `systemd.services.someservice.serviceConfig.StartLimitInterval = "somevalue";`.

How can I, in a different module or my top-level config, override that value to disappear completely?

If I try

```
systemd.services.someservice.serviceConfig.StartLimitInterval = null;
```

then it still gets rendered out as

```
[Service]
StartLimitInterval=
```

while I would like it to not render at all (also because I could not find systemd documentation on whether leaving the part after `=` empty has the same effect as the value not being talked about at all; *edit:* it fails with `Failed to parse sec value, ignoring:`).

`mkIf` and `mkMerge` don't seem to help me here (`mkIf false` naturally makes my override not be an override).

How can one do this?

**Comment by nh2** [comment]
Should we perhaps implement it such that setting it to `null` makes that field disappear?

**Comment by flokli** [comment]
Can't we just apply the systemd semantics here, which basically translates to this?

> if it's a single value, it can be overridden by defining it again, if it's a list type and there's an assignment to the empty string, the entire list prior to this is reset?

We can't really "make fields disappear" if we ship a upstream unit and just add overrides on top.

**Comment by nh2** [comment]
@flokli I don't quite understand how that works: How would we use that to allow a user to get rid of e.g.

```
systemd.nginx.serviceConfig.StartLimitInterval = "1min";
```

defined in nginx, so that systemd's default `StartLimitInterval` is used instead of what's defined in the NixOS nginx module?

Setting that to the empty string gets you a read `Failed to parse sec value, ignoring:` message in `journalctl`.

> We can't really "make fields disappear" if we ship a upstream unit and just add overrides on top.

That's right, but I'm mainly concerned about overriding things defined in NixOS `systemd.services.*` module units, not upstream-shipped ones.

In derivations, setting e.g. `configureFlags` to `null` makes that entire environment variable disappear from the builder environment.

**Comment by flokli** [comment]
We probably can't "undefine" a key in an attrset.
We could probably filter out keys that are `null`, but then we'd still have different behaviour between units fully defined in NixOS, and those deriving from upstream-shipped units, so not sure if it's a good idea.

**Comment by doronbehar** [comment]
Try:

```
systemd.services.someservice.serviceConfig.StartLimitInterval = pkgs.lib.mkForce null;
```

**Comment by nh2** [comment]
> Try:
> 
> ```
> systemd.services.someservice.serviceConfig.StartLimitInterval = pkgs.lib.mkForce null;
> ```

@doronbehar I already tried that, it has the same effect as foring it to `""`: Will render out as `StartLimitInterval=` in the unit file and result in a red `Failed to parse sec value, ignoring:`.

**Comment by doronbehar** [comment]
Then in that case you may need to refer to `systemd.unit(5)` where that directive is documented - it says the default value is `0`. So maybe:

```
systemd.services.someservice.serviceConfig.StartLimitInterval = pkgs.lib.mkForce 0;
````

**Comment by flokli** [comment]
I agree with @doronbehar here - we can't really keep track of all of systemd's defaults for each value, and can't "make them disappear" either (as we also support extending upstream-provided units) - and the behaviour should here definitely be consistent.

We should really ask the users to be more explicit. @nh2, @doronbehar, could one of you file a PR updating the docs in that regard?

**Comment by doronbehar** [comment]
I think this is somewhat implied already in the docs. For example:

https://nixos.org/nixos/options.html#systemd.mounts.*.unitconfig

Says:

> Each attribute in this set specifies an option in the `[Unit]` section of the unit. See `systemd.unit(5)` for details.

The error @nh2 got was generated by Systemd - not us, so I think "see `systemd.unit(5)`" is good enough.

**Comment by flokli** [comment]
Alright then.

**Comment by Atemu** [comment]
For anyone else digging this issue up via their search engine:

Drop-in overrides work by declaring the relevant setting with an empty value:

```
[section]
Foo=
Foo=Bar
```

In NixOS, this can be achieved using `section.Foo = [ "" "Bar" ]`. 

The empty String *is* allowed despite what the option type might suggest. `null` is not allowed however! This was a bit counter-intuitive for me; I tried `null` first.
