### ISSUE TITLE
Mirror for file-5.22 tool behaving strangely

### ISSUE THREAD

**Issue by shunxing** [NixOS/nixpkgs#8500]
Hi everyone,

I have been trying to build the file-5.22 tool (in nixpkgs/pkgs/tools/misc/file) from source and the mirror (namely "ftp://ftp.astron.com/pub/file/file-5.22.tar.gz") has been kicking me out several times with a "401 Unauthorized" for no reason.

I tried several times and eventually the server replied appropriately.

Shouldn't we find a more stable mirror for the package?

Thanks in advance!

**Comment by peti** [comment]
Which one would you suggest?

**Comment by shunxing** [comment]
@vcunat Thanks for adding a new mirror :)
