### ISSUE TITLE
Powerline git support is broken

### ISSUE THREAD

**Issue by process0** [NixOS/nixpkgs#85022]
**Describe the bug**

Current python powerline package is missing python `powerline-gitstatus` module dependency. 

**To Reproduce**

Installed powerline 
```
nix-env -iA nixos.python38Packages.powerline
```

Running `powerline-lint -d` returns 
```
failed to import module powerline_gitstatus
  in "/home/user/.config/powerline/themes/shell/default_leftonly.json", line 13, column 18:
    >--->--->--->---"function": "powerline_gitstatus.gitstatus",
```

**Expected behavior**

No error about failing to import gitstatus module.

**Comment by FliegendeWurst** [comment]
Works on 21.11.
