### ISSUE TITLE
Package request: vala-language-server

### ISSUE THREAD

**Issue by LinArcX** [NixOS/nixpkgs#85024]
**Project description**
Code Intelligence for Vala 

**Metadata**

* homepage URL: https://github.com/benwaffle/vala-language-server
* source URL: https://github.com/benwaffle/vala-language-server
* license: LGPL2.1
* platforms: unix, linux, darwin, ...

**Comment by worldofpeace** [comment]
any relation to https://github.com/NixOS/nixpkgs/pull/83386?

**Comment by jtojnar** [comment]
There are some efforts to merge the two servers but otherwise they are independent.
