### ISSUE TITLE
nix-shell does not respect shell variables like NIX_PATH 

### ISSUE THREAD

**Issue by codygman** [NixOS/nixpkgs#85037]
**Description/Reproduction/Expected Behavior**

```shell
$ unset NIX_PATH
$ NIX_PATH=nixpkgs=channel:nixos-20.03 nix-shell -p --keep NIX_PATH --run "echo $NIX_PATH"
```

Workaround using export:

```shell
$ unset NIX_PATH
$ export NIX_PATH=nixpkgs=channel:nixos-20.03 
$ nix-shell --pure -p --keep NIX_PATH --run "echo $NIX_PATH"
nixpkgs=channel:nixos-20.03
```

I think nix should have the same behavior as sh where both of these work:

```shell
$ unset var
$ var=value sh -c 'echo "$var"'
value
$ unset var
$ export var=value
$ sh -c 'echo "$var"'
value
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24, NixOS, 20.09pre216896.0729b8c55e0 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(cody): `"home-manager, nixos-unstable-20.09pre216896.0729b8c55e0"`
 - channels(root): `"nixos-20.09pre216896.0729b8c55e0, nixos-unstable-20.09pre216896.0729b8c55e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
This issue does not belong to nixpkgs the collection of packages.
Questions can be posted to our Discourse https://discourse.nixos.org
Nix issue tracker: https://github.com/NixOS/nix/issues

> --run "echo $NIX_PATH"

> 'echo "$var"'

Better stick to single quotes in your examples.

**Comment by danbst** [comment]
yes, this is an issue with double quotes. Replace with single quotes and bug disappears.
