### ISSUE TITLE
there is no flag to en/disable patchPhase

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#85038]
There is no flag to en/disable patchPhase but there is for other phases;
https://github.com/NixOS/nixpkgs/blob/eb54aa1f6cc9a817bad76145894a49722cd0005b/pkgs/stdenv/generic/setup.sh#L1267

**Comment by prusnak** [comment]
I guess that's because you can conditionally set/modify the `patches` variable.
