### ISSUE TITLE
Installing a stdenv as part of the system configuration to avoid bootstrap dependencies

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#8504]
From what I can tell, a simple fetchurl may require building all of this:

```
  /nix/store/8vs8drxdjisk2fillxaz0bbdp09j33c8-binutils-2.23.1.drv
  /nix/store/nr1bvrs6x4g3p6q4d1dmy0hjhc8zd9qi-bootstrap-gcc-wrapper.drv
  /nix/store/kn2602d46r2bvnb2kry1k99v4d3qknbd-bootstrap-gcc-wrapper.drv
  /nix/store/qy7h93j94nw1s6f6w2cbcaynhphpzqxw-stdenv-linux-boot.drv
  /nix/store/smf7xkrxi8nqiv56j2pm4ia014rr9c7x-patchelf-0.8.drv
  /nix/store/aa4cx35di3xb216cxsrbmlyzlap71cwx-stdenv-linux-boot.drv
  /nix/store/k2x8w6vjf0531ad6mw8alqz7jz09qsrn-xz-5.2.1.drv
  /nix/store/zri5mf052vvbkad559hm3iar0fvwrjhs-gcc-wrapper-4.8.4.drv
  /nix/store/cjc9cpn9afkhqpr7w3wvh0rx687inzb2-stdenv-linux-boot.drv
  /nix/store/04gfj78ssjwg1dv3bhh9nqp34w7l3f4j-paxctl-0.9.drv
  /nix/store/5zpyl6cj9y7jw130gxpbmvdya6l5063m-libsigsegv-2.10.drv
  /nix/store/gjc7cixlsd427pxd2kavxjbjsn05dn5f-stdenv.drv
  /nix/store/8cvrqzxsdfh0iza3l40x2241hnysy5yb-mirrors-list.drv
```

The stdenv in the second-last line is the normal `pkgs.stdenv` (not one of the bootstrap stdenvs), and all the stuff above it is seem to be *build-time* dependencies of stdenv. When one does not have the stdenv out path in the store (e.g. after GCing, or in a nixops-deployed machine), then to build pretty much anything, it will be necessary to build all the bootstrap packages as seen. Imporantly this includes gcc, which is a very long build.

Once I have set up my nixops deployment to install a reference to stdenv, then building stuff on the target system no longer requires much of the packages listed, including these bootstrap versions of binutils and gcc. However, it is not as easy as putting `pkgs.stdenv` into `environment.systemPackages`, this does not result in a reference to stdenv. I was able to do it by abusing an etc file: ```environment.etc."stdenv-reference".source = pkgs.stdenv;```

I think it would be good to have a specific configuration option that would add a stdenv reference somewhere, and to highlight this behavior in the documentation, in order to prevent people losing lots of time and electricity rebuilding the otherwise unneeded bootstrap packages.

**Comment by vcunat** [comment]
Seems disputed recently 21dd114f8204.

**Comment by dezgeg** [comment]
Sounds like the proper solution is https://github.com/NixOS/nixpkgs/issues/7118

**Comment by ambrop72** [comment]
I agree that #7118 is a good idea but I still think that an easy option to install the stdenv would be useful. Because one may want to have the full stdenv around for actually building stuff. Let me emphasize, it seems that bootstrap versions binutils and gcc are *build dependencies* of stdenv, but not runtime dependencies (but I'm not sure how deep in the dependency graph they are though).

**Comment by edolstra** [comment]
If you want stdenv to be kept, you can set
```
system.extraDependencies = [ pkgs.stdenv ];
```

**Comment by ambrop72** [comment]
Thank you the extraDependencies is a nicer solution. I'm closing this.
