### ISSUE TITLE
pytorch derivation evaluates mkl even when mklSupport is set to false

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/nixpkgs#85053]
**Describe the bug**

The default PyTorch derivation evaluates the `mkl` argument even when `mklSupport` is set to false.

Here is the `mkl` argument to the PyTorch derivation:

https://github.com/NixOS/nixpkgs/blob/d121a3992cc268bf3ebd66eed53ed73b62687ef9/pkgs/development/python-modules/pytorch/default.nix#L3

Here are a couple asserts about `mkl`:

https://github.com/NixOS/nixpkgs/blob/d121a3992cc268bf3ebd66eed53ed73b62687ef9/pkgs/development/python-modules/pytorch/default.nix#L28-L40

Here is the offending line that evaluates `mkl` even if `mklSupport` is set to `false`:

https://github.com/NixOS/nixpkgs/blob/d121a3992cc268bf3ebd66eed53ed73b62687ef9/pkgs/development/python-modules/pytorch/default.nix#L161-L168

My guess is that this line should be changed to something like:

```nix
  NIX_CFLAGS_COMPILE = lib.optionals (mklSupport && numpy.blas == mkl) [ "-Wno-error=array-bounds" ];
```

**To Reproduce**

On `master` (commit d121a3992), run the following command:

```console
$ nix-build -A python3Packages.pytorch
error: Package ‘mkl-2020.1.217’ in /home/illabout/git/nixpkgs/pkgs/development/libraries/science/math/mkl/default.nix:133 has an unfree license (‘issl’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Expected behavior**
PyTorch should be able to be built without setting `allowUnfree` to `true` (or even requiring that `mkl` be evaluated).

**Workaround**

You can explicitly set `mkl` to `null`:

```console
$ nix-build -E 'with import ./. {}; python3Packages.pytorch.override { mkl = null; }'
```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-8-amd64, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(illabout): `"nixpkgs-20.03beta874.b0c285807d6"`
 - nixpkgs: `/home/illabout/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.pytorch
# a list of nixos modules affected by the problem
module: 
```

cc @teh @thoughtpolice @stites @tscholak (maintainers of pytorch)

**Comment by stites** [comment]
@cdepillabout Your proposed fix is already in https://github.com/NixOS/nixpkgs/pull/75827/files#diff-84b29016f8c93846ea69f3885d709770R39 -- can you see if this is still the case?

**Comment by cdepillabout** [comment]
Looks like this is fixed, thanks Sam!
