### ISSUE TITLE
leanpkg (package lean) fails on macos due to missing greadlink

### ISSUE THREAD

**Issue by robx** [NixOS/nixpkgs#85066]
**Describe the bug**

`leanpkg` on macos fails because it can't find `greadlink`.

**To Reproduce**

1. Install lean: `$ nix-env -iA nixpkgs.lean`
2. Run leanprover. It bails out with

       OSX 'readlink' command does not support option '-f', please install 'greadlink'. If you use 'brew', you can install 'greadlink' using 'brew install coreutils'

**Expected behavior**

No errors.

**Additional context**

This is because leanpkg has an [explicit check for greadline on macos](https://github.com/leanprover-community/lean/blob/ec1613aef1eee72e601f192b16740629c6d49690/bin/leanpkg#L4):

```
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
    # OSX
    if command -v greadlink >/dev/null 2>&1; then
        # macOS readlink doesn't support -f option
        READLINK=greadlink
    else
        echo "OSX 'readlink' command does not support option '-f', please install 'greadlink'. If you use 'brew', you can install 'greadlink' using 'brew install coreutils'"
        exit 1
    fi
else
    READLINK=readlink
fi
```

It can be worked around presently by installing `coreutils-prefixed`. Options I see for fixing the package:

- depend on `coreutils-prefixed` on darwin
- patch out this check, since (presumably) nix provides the GNU `readlink` anyway
- fix this upstream by changing the check to not fail under nix (e.g. by having an explicit check for the `-f` argument instead of relying on command name), and pull in the fixed version

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(rob): `"nixpkgs-20.09pre218717.05f0934825c"`
 - nixpkgs: `/Users/rob/.nix-defexpr/channels/nixpkgs`
```

**Comment by veprbl** [comment]
> depend on coreutils-prefixed on darwin

Sounds most easiest to implement and maintain.
