### ISSUE TITLE
iosevka: needs update from 2.3.3 to 3.0.0-rc.6

### ISSUE THREAD

**Issue by luc65r** [NixOS/nixpkgs#85088]
## Issue description
2.3.3 is getting old.
Updating Iosevka-bin is easy, but I have no idea how to update Iosevka with all the Node packages.

@cstrahan @jfrankenau @ttuegel @babariviere @rileyinman Could someone do it ?

**Comment by rileyinman** [comment]
As noted by the versioning, 3.0.0-rc.6 is a release candidate but not yet approved by the developer as ready for packaging. Once 3.0.0 is released proper, then it can be packaged.

**Comment by luc65r** [comment]
I'm sorry. I thought releases were all ready for packaging.
