### ISSUE TITLE
Vapoursynth R49 and nasm

### ISSUE THREAD

**Issue by maddovr** [NixOS/nixpkgs#85128]
Vapoursynth in nixpkgs is still version R47 which is affected by serious (crashes on some CPUs, artifacts) bugs that were fixed in R49 (Audio support was also merged since then). Moreover R47 is the first vapoursynth version to not require nasm anymore (all asm was removed in favor of intrinsics). For details, the last few articles on the [vapoursynth's blog](http://www.vapoursynth.com/) are a good read. It'd be nice to have an upgraded package for it. It's my first issue so I'm not sure I did this correctly.

**Comment by rnhmjoj** [comment]
Tested and backported to 20.03 in b3fbd4f5b4d0ea1d0014ab9602b28bc8dce15331.
