### ISSUE TITLE
some programs ignoring my gtk theme

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#85135]
**Describe the bug**
transmission-remote-gtk and pcmanfm are showing up white despite my gtk theme being dark and working fine elsewhere (lxappearance and deluge both show up dark)

**To Reproduce**
1. install (for example) pcmanfm and lxappearance
2. install and select adwaita-dark theme (I think part of gnome-themes-standard)
3. compare the look of pcmanfm and lxappearance

**Expected behavior**
I would think these should all be dark, or at least the same if not correct.

**Screenshots**
Clockwise from top left, transmission-remote-gtk, deluge, lxappearance
![2020-04-13-045407_grim](https://user-images.githubusercontent.com/3146494/79112017-3f823480-7d43-11ea-9ab8-089311444dc2.png)

pcmanfm
![2020-04-13-045541_grim](https://user-images.githubusercontent.com/3146494/79112020-414bf800-7d43-11ea-9005-c2c13fc608e1.png)

**Additional context**
I've only just realized this issue, so I'm unsure if it was something that broke or if it hasn't worked since I've used these programs.
edit: changing the theme in lxappearance to something else will live-update lxappearance and deluge, but transmission-remote-gtk and pcmanfm continue to not change.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.114, NixOS, 20.09pre220429.9b0d2f3fd15 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre220429.9b0d2f3fd15"`
 - channels(brad): `"home-manager, nixos-20.09pre220429.9b0d2f3fd15"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pcmanfm, transmission-remote-gtk
# a list of nixos modules affected by the problem
module:
```

**Comment by Emantor** [comment]
What desktop system/compositor/window manager are you using? GTK-3.0 is known to ignore settings in the configuration ini file on wayland managers and will instead look for a dconf database.

**Comment by Soundtoxin** [comment]
I am using Sway.

**Comment by doronbehar** [comment]
@Soundtoxin you are mixing QT and GTK based apps in your screenshots. I have transmission-remote-gtk working with the dark theme. I'm not sure how to narrow this down to you but here's the relevant configuration of my system:

```nix
    environment.systemPackages = with pkgs; [
      # ...
      gtk3
      gnome3.adwaita-icon-theme
      # ...
    ];
``` 

And manually set in my dotfiles:

```
export GTK_THEME=Adwaita:dark
```

**Comment by Soundtoxin** [comment]
> you are mixing QT and GTK based apps in your screenshots.

No... I am not doing that. There exists a QT variant of pcmanfm, but I'm using the regular pcmanfm package, not pcmanfm-qt. The other thing failing to be themed literally has gtk in its name, and the themes I'm selecting are gtk themes.

I'll try your suggest and see if I can get anything different to happen.

**Comment by doronbehar** [comment]
You can test it with:

```
env GTK_THEME=Adwaita:dark transmission-remote-gtk
```

**Comment by Soundtoxin** [comment]
> You can test it with:
> 
> ```
> env GTK_THEME=Adwaita:dark transmission-remote-gtk
> ```

This works! It actually shows up dark when launched this way. It seems to work for lxappearance and pcmanfm as well.
![2020-04-13-170900_grim](https://user-images.githubusercontent.com/3146494/79165805-83a82000-7da9-11ea-9683-bee3272286f6.png)

So, didn't have to change any packages, just this environment variable. Thank you for the help. Is this not a bug then? Will everyone on Wayland have to do this?

**Comment by doronbehar** [comment]
> Is this not a bug then?

No and that's why I had the suspicion right from the start that lxappearance doesn't handle the GTK theme. I never heard of a graphical program like qt5ct that does the same for GTK apps. Also the Arch Wiki doesn't mention any such package from as far as I know.

> So, didn't have to change any packages, just this environment variable. Thank you for the help.

Glad to help :) Please close the issue now.

**Comment by Soundtoxin** [comment]
> No and that's why I had the suspicion right from the start that lxappearance doesn't handle the GTK theme.

It definitely changes the GTK theme before my very eyes for deluge and lxappearance itself as I select different things, it just didn't change for transmission-remote-gtk and pcmanfm. Maybe it's a gtk2/gtk3 difference or something else. I won't bother thinking about it anymore.
