### ISSUE TITLE
nixos-install/nixos-rebuild fails with "Out of memory" on systems with 512MB RAM

### ISSUE THREAD

**Issue by sasoiliev** [NixOS/nixpkgs#85148]
**Describe the bug**
512MB of RAM seem to be insufficient for a successful NixOS installation via the installer. Bumping the memory size of the VM from the steps to reproduce below ends up in a successful installation, but bringing the memory back down to 512MB renders the VM unable to do `nixos-rebuild switch` (fails with `error: unable to fork: Cannot allocate memory`).

Even though 512MB is quite low by today's standards, there are still use cases where you don't really need more than that (e.g., I discovered this while building a VM that will act as a Wireguard VPN endpoint for a couple of boxes doing just routing between them).

I didn't find any requirements in the NixOS Manual regarding the amount of memory needed. I would suggest adding this in the documentation at minimum. (I can try to submit a PR if the project maintainers agree with my suggestion.)

(Apologies if this is a known problem, I couldn't find an existing issue describing it.)

**To Reproduce**
1. Create a qemu disk image: `qemu-img create /tmp/nixos.img 8G`
2. Start a qemu VM with 512MB RAM and the NixOS minimal ISO: `qemu-kvm -m 512M -drive file=/tmp/nixos.img -cdrom ~/Downloads/nixos-minimal-19.09.1957.57c35c63004-x86_64-linux.iso`
3. Create a Linux partition through `sudo fdisk`
4. Create a filesystem: `sudo mkfs.ext4 /dev/sda1`
5. Mount the partition under `/mnt`: `sudo mount /dev/sda1 /mnt`
6. Generate the NixOS config: `sudo nixos-generate-config --root /mnt`
7. Set the GRUB boot device - in `/mnt/etc/nixos/configuration.nix` uncomment the `boot.loader.grub.device` setting
8. Run the installer: `sudo nixos-install --root /mnt`

**Actual behavior**
The installation fails with:
```
building the configuration in /mnt/etc/nixos/configuration.nix...
[  103.481160] Out of memory: Kill process 891 (nix) score 749 or sacrifice child
[  103.481676] Killed process 891 (nix) total-vm:494588kB, anon-rss:371860kB, file-rss:0kB, shmem-rss:8kB
/run/current-system/sw/bin/nixos-install: line 99:   891 Killed                       ...
```

**Expected behavior**
The NixOS installer completes successfully.

**Metadata**
```
- system: `"x86_64-linux"`
- host os: `Linux 4.19.98, NixOS, 19.09.1957.57c35c63004 (Loris)`
- multi-user: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.2`
- channels(root): `"nixos-19.09.1957.57c35c63004"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eadwu** [comment]
Have you tried using swap?

**Comment by sasoiliev** [comment]
@eadwu, fair enough. Documenting the minimum requirements for building a NixOS configuration is still worthwhile IMO.

**Comment by petabyteboy** [comment]
I agree we should have some documentation on the minimum system requirements for evaluating a normal NixOS config.

However there are ways around this. You can actually install NixOS without running a rebuild on the target.

- Boot the NixOS ISO or [kexec a NixOS netboot image](https://github.com/cleverca22/nix-tests/tree/master/kexec)
- Set up ssh access
- Do partitioning, formatting and mounting
- On another NixOS computer: 
  - `ssh root@target "nixos-generate-config --root /mnt --show-hardware-config" > ./hardware-configuration.nix`
  - Write a configuration for the new machine in ./configuration.nix and make sure it imports `./hardware-configuration.nix`
  - `nixos-rebuild build -I nixos-config=./configuration.nix`
  - `nix-store --export $(nix-store -qR result) | ssh root@target "nix-store --import --store /mnt"`
  - `ssh root@target "nixos-install --system $(readlink result)"`
- reboot the target machine
- profit

**Comment by lheckemann** [comment]
https://discourse.nixos.org/t/adding-nixos-entry-to-libosinfo-recommended-resources/6441/ somewhat related to system requirements documentation

**Comment by raidenovich** [comment]
I'm having this issue with 16 gb of ram, probably a bug
