### ISSUE TITLE
Split lego state directories causes account rate limits

### ISSUE THREAD

**Issue by m1cr0man** [NixOS/nixpkgs#85152]
**Describe the bug**
When writing #77578, it was important to ensure that the .lego state directory was common to all certs to ensure that new accounts were not being created for every certificate. The rate limit on new accounts is 10 every 3 hours. This is fine for most cases, but in my deployment I have 30 different domains to request certificates for, and that's after a lot of deduplication and grouping of domains.

As of #84781 this has been changed such that all certificates get their own state directories, and thus their own account credentials. As pointed out, the account directory can be symlinked using preStart scripts if necessary. I feel this isn't a matter of migrating user data but more about maintaining compatibility with existing setups like my own and also avoiding rate limits in LE's service. This should be part of the module's configuration by default.

**Comment by aanderse** [comment]
cc @flokli @arianvp @immae @emilazy @Mic92 and whoever else I'm missing...

**Comment by m1cr0man** [comment]
I have been focused on getting a mail stack in Nixos working over the past week and I missed that PR and other things :/ sorry about that. I would've commented if I had seen it sooner.

**Comment by emilazy** [comment]
Seems like reverting #84781 for now would probably be for the best; multiple certs for the same domain seems like a less important feature than not spamming LE with account creations. It should be possible to reuse the same account while keeping the certificates split, but maybe we'll have to make some ugly symlink forests?

I wish lego's CLI was more explicit.

**Comment by m1cr0man** [comment]
Well that or, we can patch in symlinking of accounts directories back a folder. I think it wouldn't be too hard, I can prepare a PR now

**Comment by emilazy** [comment]
@Mic92 You [posted about this issue](https://github.com/NixOS/nixpkgs/pull/84781#issuecomment-611378583) before self-merging the PR and backporting it to 20.03; could you please subject your changes to critical infrastructure to wider review in future? It's quite frustrating to work with Let's Encrypt engineers to make the NixOS service well-behaved, only to have a change merged and backported that runs roughshod over rate limits and can potentially result in hundreds of certificates being renewed at once on upgrade just to avoid incorporating [a few lines of migration code](https://github.com/NixOS/nixpkgs/pull/84781#issuecomment-611439942), with less than three hours between the PR being opened and merged, and only one recent contributor to the service being pinged. It's a lot easier to fix issues before merge than it is to rush to fight fires after something's hit the channels...

**Comment by immae** [comment]
@emilazy : there is no need to shout on people like that...

@m1cr0man : merging every certificates in a single directory leads to this issue: https://github.com/NixOS/nixpkgs/issues/84409
It was considered blocking for 20.03 because it broke a behavior that was authorized and expected in simp_le’s age.

**Comment by m1cr0man** [comment]
@immae I saw that issue and I don't intend to reintroduce it, but sharing _just_ the accounts folder would fix this issue without regression. Of course, I will test and ensure that is the case on my system first but rest assured I have no intention to completely undo #84781

**Comment by immae** [comment]
Thanks @m1cr0man :bow:

**Comment by m1cr0man** [comment]
I created a PR...but I still don't fully understand the use case behind having multiple certs for the same domain? Surely, on a single system, you would only want one certificate per domain, even if they are for different services?

Also I did think of an issue with the .lego folder as a whole... if a user uses different user and group for 2 certificates then 1 of them will own the directory and the other will not be able to write to it. I don't know if we want to support that sort of configuration? It would certainly prevent us optimising around rate limits, but it is solvable if the .lego directory is under `/var/lib/acme/${cert}`

**Comment by emilazy** [comment]
You can use different key types (to serve both RSA and ECDSA certificates for the same domain), or perhaps set other alternate names.

In terms of `accounts` directory sharing, I increasingly think that the only permissions option that makes sense from a privilege separation point of view is to have `/var/lib/acme` unconditionally owned by `acme:acme` and just selectively add other services like nginx to the acme group for read access.

**Comment by m1cr0man** [comment]
Yeah I had read that earlier and I agree that an `acme` user + group would make sense. How do people feel about a PR for a complete revamp of the module? This was suggested back when I finished DNS-01 due to the number of changes and the complexity of the module at this stage. I would be tempted to at least try and do this (now that I have the time again), and see what can be simplified. It's becoming quite the monster.

**Comment by immae** [comment]
@m1cr0man : if you want to completely rewrite the module, you might be interested in my recently listing of some issues regarding ACME: https://github.com/NixOS/nixpkgs/issues/84633

I think the last one might be very annoying: once a certificate is created, changing the list of domains in the certificate won’t work (in other words, in the current state of the module you cannot add or delete domains from a certificate after it’s generated)

**Comment by m1cr0man** [comment]
@immae Yep also started tracking that issue already :) I think that one is resolvable by writing some file that hashes the domains + extraDomains, and takes action accordingly, but RemainAfterExit is a bigger bummer. I'll continue conversations about a rewrite over in that issue.

**Comment by emilazy** [comment]
I think a rewrite of the module would be great, as long as compatibility with the basic configuration options was kept; there's a fair bit held over from simp_le that no longer makes sense, and a lot of nits with the current implementation. I know @yegortimoshenko was working on a refactor at some point; maybe they'd be able to share WIP code?

**Comment by emilazy** [comment]
For what it's worth, one possible way to fix the various renewal bugs in one shot would be to derive the certificate subdirectory from a hash of its configuration like `/var/lib/acme/.lego/$domain-$hash`; that way, any changes to the OCSP Must-Staple configuration, alternate domains, etc. would change the underlying internal path to the certificate and force a new one to be issued. We'd still need explicit `acme-*{,-force,-revoke}.service` or similar that users could run manually for edge-cases, but that should ensure that the 90% case is handled out of the box without hacks to manually check the configuration differences and remove certificates. (The implementation of force renewal will still probably involve manually removing certificates from underneath lego since I think it doesn't implement this directly; it'd be best to just rename the directory to `$domain-$hash-old-$timestamp` or similar so that people can still revoke them if necessary.)

**Comment by Mic92** [comment]
@emilazy It was reviewed by @flokli and @immae. Catching ratelimits is not something one can easily test or fix. If one has 30 certificates they will run into certificate creation limits, in which only SAN certificates would help

**Comment by rkoe** [comment]
PLEASE backport this to 20.03, since it's a serious bug, with effectively completely breaks the lets-encrypt-certificate-renewal in 20.03 if more than 10 certificates are used on a server.

**Comment by arianvp** [comment]
It was backported already. https://github.com/NixOS/nixpkgs/commit/ecfd73db44a9337ffbe4816c82c953399a19ca4f 

Are you actually experiencing issues? If so; please open a new bug for that

**Comment by rkoe** [comment]
I've updated a server to 20.03 today, and I'm experiencing exactly this issue.
