### ISSUE TITLE
Installing libtiff : Network is unreachable

### ISSUE THREAD

**Issue by shunxing** [NixOS/nixpkgs#8516]
Hi everyone,

I wanted to install libtiff-4.0.3 but it uses svn to download the package. However, I got this error when I try to install it:

svn: E000101: Unable to connect to a repository at URL 'svn://svn.archlinux.org/packages/libtiff/trunk'
svn: E000101: Can't connect to host 'svn.archlinux.org': Network is unreachable

I'm wondering if the source is out of date. Indeed, there is no package called trunk in http://archlinux.org.

Could someone try to fix this issue with me ? Is there something wrong with fetchsvn?

Moreover, I configured ~/.subversion/servers to add a proxy for svn.

Thanks in advance :)

**Comment by vcunat** [comment]
- Information from ``~/*``  wouldn't be used during nix builds.
- Since f40c885a34c on staging, libtiff won't be using svn to fetch patches. You can pick that commit to work around your problems.

**Comment by matthiasbeyer** [comment]
Just wondering: The Archlinux guys migrated package repos to git, didn't they?

**Comment by vcunat** [comment]
Yes, that could be why it no longer works.

**Comment by matthiasbeyer** [comment]
Any progress here? @shunxing ? Or can we close this?

**Comment by vcunat** [comment]
This is long fine on master and 15.09.
