### ISSUE TITLE
Add ruby bundler support

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#852]
It would be nice to have an option to generate nix packages from ruby bundler like packages and add relevant support in nixpkgs. I want to make some nixos modules for packages which use bundler.

I would like to implement this. I know @MarcWeber was working on this, but i don't know what is the state of his work.

What do you think is the best approach here? There are two ways I can think of, which all involves first parsing of Gemfile.lock and then:

- Use gem nix to add dependencies, but this would mess up generated ruby packages with speciffic version of pacakges, which is not nice.
- Generate dependecies using gem nix in some other file and somehow include them in generated nix expression.
- Add bundler support in gem nix

**Comment by matthiasbeyer** [comment]
This seems to be really outdated, isn't it? 

**Ping** (randomly) @lethalman

**Comment by Pitometsu** [comment]
Is it still not implemented yet?

**Comment by cyraxjoe** [comment]
I think this is no longer the case @Pitometsu [manual](https://nixos.org/nixpkgs/manual/#sec-language-ruby) and [bundix](https://github.com/cstrahan/bundix).

**Comment by zimbatm** [comment]
Bundix is now part of nixpkgs
