### ISSUE TITLE
haskell: lens doctests take forever

### ISSUE THREAD

**Issue by dnhgff** [NixOS/nixpkgs#8522]
The lens library provides the `-f-test-doctests` flag for disabling doctests. These take a really really really long time to run. If they have not, the code is still good.

Lens comes with a broad array of tests to verify it's functionality. These doctests are more to make sure no one gets an exception or type error when they copy a code snippet from the haddock.

**Comment by peti** [comment]
I don't think that's necessarily true. Doctests execute a wide range of checks that go well beyond checking the consistency of the documentaion, i.e. it's possible to state QuickCheck invariants in documentation, etc.

**Comment by dnhgff** [comment]
I agree that you can state many properties in doctests. I guess I just disagree about the purpose of lens' doctests. I would not be surprised if there are lens doctests that happen to also be reasonable tests, but that is not why they were written. Perhaps i am just splitting hairs. It is true that there are bugs in the lens issue tracker that the doctest has found.

I will close this and leave it to be reopened if there is further support of my view.
