### ISSUE TITLE
terminus needs a maintainer

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#85232]
**Describe the bug**
See https://github.com/NixOS/nixpkgs/issues/85179, as it's very out of date.
In https://github.com/NixOS/nixpkgs/pull/85212 the then current maintainer @jlesquembre no longer uses the package, and it needs someone new to maintain it. I believe if orphaned long enough without its needed update, it should be removed. (since it won't continue to work eventually).

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/terminus/default.nix

**Metadata**
* homepage URL: https://eugeny.github.io/terminus/
* source URL: https://github.com/Eugeny/terminus/releases
* license: mit,
* platforms: unix, linux, darwin

**Comment by jlesquembre** [comment]
Terminus has been removed: #134974
