### ISSUE TITLE
mdmonitor failing with no option to configure it

### ISSUE THREAD

**Issue by andir** [NixOS/nixpkgs#85311]
**Describe the bug**
After deploying a recent version of nixpkgs master to a machine I  was alerted by my monitoring that the service `mdmonitor.service` is now failing.

The  journal of the failing service:
```
Mar 11 01:00:48 bertha systemd[1]: Starting MD array monitor...
Mar 11 01:00:48 bertha systemd[486]: mdmonitor.service: Executable /usr/lib/mdadm/mdadm_env.sh missing, skipping: No such file or directory
Mar 11 01:00:48 bertha systemd[1]: Started MD array monitor.
Mar 11 01:00:48 bertha mdadm[488]: mdadm: No mail address or alert command - not monitoring.
Mar 11 01:00:48 bertha systemd[1]: mdmonitor.service: Main process exited, code=exited, status=1/FAILURE
Mar 11 01:00:48 bertha systemd[1]: mdmonitor.service: Failed with result 'exit-code'.
```

This seems to have been introduced by b9b27912ce1 (cc @abbradar).

It seems like all systems that have an mdraid device will see this error

**To Reproduce**
1. deploy a recent version of NixOS based on nixpkgs master to a machine with a linux raid (mdadm, …)
2. reboot
3. `systemctl status mdmonitor.service`

**Expected behavior**
The service should not be started when it wasn't properly configured.

**Notify maintainers**

@Ekleog  (mdraid maintainer)

**Comment by pbogdan** [comment]
Just FYI there's some prior discussion in https://github.com/NixOS/nixpkgs/issues/72394 which might be relevant.

**Comment by andir** [comment]
Ah, so this is probably just a duplicate. I'll  close this one.
