### ISSUE TITLE
Using Nix to install Nix does the wrong thing in a prefix environment

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nixpkgs#8533]
To build a prefix environment you have to go build `nix` with `--prefix` and some other configurations described in the manual. After the environment is up, you might think, why not start by using Nix to build Nix? It does the wrong thing. Rather than inheriting the configuration it builds a Nix that thinks there's a `/nix`.

**Comment by domenkozar** [comment]
This issue belongs to https://github.com/NixOS/nix

**Comment by gitfoxi** [comment]
I don't know enough to say for sure, but I thought maybe the nixpkgs formula for nix could be improved to account for the prefix rather than have the configure for nix detect that it's being built in a prefix.
