### ISSUE TITLE
git package can't find it's ssl certs or something

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nixpkgs#8534]
```
$ git clone https://github.com/NixOS/nixpkgs.git
Cloning into 'nixpkgs'...
fatal: unable to access 'https://github.com/NixOS/nixpkgs.git/': SSL certificate problem: unable to get local issuer certificate
```

This is running under Ubuntu. I guess the local issuer certificate must have been in the nix store at some point for git to have built. I did do a garbage collection (unfortunately) before trying git so maybe the certificate-providing package gets garbage collected because it's a build dependency and not a runtime dependency.

This is from the channel, not github. Channel version is 2.4.1 and this repo has 2.4.4. I'm rebuilding to see if maybe it's already been fixed.

update
---------

I rebuilt from this repo and the problem persists. Strange since the package directory for git has all kinds of patches having to do with certificates.

**Comment by gitfoxi** [comment]
So it seems git uses openssl for transport and looking in the openssl directory in the store I see that `/nix/store/7lw0x4dgvmkh9w3cr5b0ri34ps0rkpwm-openssl-1.0.1m/etc/ssl/certs` is empty. Different from my system `/etc/ssl/certs` which is full of certs. This is very surprising that no one has noticed this because no way anything is working for anyone.

**Comment by gitfoxi** [comment]
Thanks to this obscure gist https://gist.github.com/cartazio/21523fb72db0227611ac I find out that this is just how things work. You're meant to do something like:

    export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

I guess it's meant to do something good for security. But it's so obscure. I'd just like to register my opinion that this is the most annoying fucking default I can even imagine.

**Comment by wmertens** [comment]
I fully agree, it is very annoying. Work is underway for a better user environment on non-NixOS, search for that.

Since this is working as it should, closing.

On phone, sorry for brevity…
