### ISSUE TITLE
Setting profile picture in gnome-control-center no longer works

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#85357]
What I can say is that on unstable, with Gnome 3.36.1, it does not seem to work.

```
Apr 15 23:29:12 laptop accounts-daemon[18839]: g_file_info_get_attribute_uint32: assertion 'G_IS_FILE_INFO (info)' failed
Apr 15 23:29:12 laptop accounts-daemon[18839]: g_file_info_get_file_type: assertion 'G_IS_FILE_INFO (info)' failed
Apr 15 23:29:12 laptop accounts-daemon[18839]: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed
Apr 15 23:29:12 laptop .gnome-control-[23124]: SetIconFile call failed: GDBus.Error:org.freedesktop.Accounts.Error.Failed: file '/tmp/gnome-control-center-user-icon-K0IWI0' is not a regular file
```

I am certain this worked before, at least in 3.32, IIRC.

cc @austinbutler

**Comment by doronbehar** [comment]
I _can_ set my profile picture, at least it appears in the lock screen.

**Comment by austinbutler** [comment]
I still get the same issue on a new install of NixOS 21.03/Gnome 3.36.5. The built-in icons work fine, but selecting a custom image results in the same errors in the logs.

**Comment by nerosnm** [comment]
I'm still getting the same issue under NixOS 21.11 and GNOME 40.1.0.

**Comment by jtojnar** [comment]
I managed to get it work after fiddling with it a bit – cannot recall what exactly I did (choose one of the avatars from gallery, take a picture, try selecting a file multiple times, not sure). cc @tholzschuh

**Comment by psydvl** [comment]
Still actual

**Comment by Couapy** [comment]
> Hi, someone knows how to solve this manually ? Thank's !

Okay, I just solve the problem by toggling this line : https://gitlab.freedesktop.org/accountsservice/accountsservice/-/blob/main/data/accounts-daemon.service.in#L28

**Comment by OCharnyshevich** [comment]
Thanks @Couapy ♥️
Works fine for me by just changing the settings:

`sudo systemctl edit accounts-daemon.service`

```
### Editing /etc/systemd/system/accounts-daemon.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

[Service]
PrivateTmp=false
```

`sudo systemctl restart accounts-daemon.service`

Ready to go

**Comment by jtojnar** [comment]
Thanks for pointing that out, upstream issue: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1629

**Comment by jtojnar** [comment]
I would try something like `systemd.services.accounts-daemon.serviceConfig.PrivateTmp = false;`.

I am also backporting the patch in https://github.com/NixOS/nixpkgs/pull/161966. Would appreciate if someone here could test it.

**Comment by tad-lispy** [comment]
The setting works. Finally I can have my cute avatar on my laptop :grin: Thanks @jtojnar 

The PR is merged. Does it mean I don't need the custom setting anymore?

**Comment by jtojnar** [comment]
If you update to a version containing the patch, the option is no longer necessary. You can track which branch it is in using https://nixpk.gs/pr-tracker.html?pr=161966
