### ISSUE TITLE
Slim: can't easily benefit from `services.xserver.startGnuPGAgent`

### ISSUE THREAD

**Issue by listx** [NixOS/nixpkgs#8538]
I've posted a comment at https://github.com/NixOS/nixpkgs/issues/5200#issuecomment-116205862.

But long story short, I need to first start `gpg-agent`, and then *after* X is loaded and ready, execute `gpg-connect-agent updatestartuptty /bye` once upon login.

The workaround is to invoke the `gpg-connect-agent` command manually or in my own script somewhere (and do some check like "did this command already run? if so, skip"), but the problem seems easily avoidable and suited to the concept of X logins.

**Comment by kirelagin** [comment]
Default `slim.conf` (the one shipped with the source) has:

~~~~
login_cmd           exec /bin/bash -login ~/.xinitrc %session
~~~~

Unfortunately it is a little more complicated on NixOS. The slim module uses `login_cmd` to execute `${dmcfg.session.script}`, which is defined in `display-managers/default.nix` via some crazy [`apply` magic](https://github.com/NixOS/nixpkgs/blob/3ff2dfb7fa9c9ad8c06eac6199aa8443fbd6f003/nixos/modules/services/x11/display-managers/default.nix#L271). So it ends up executing the `xsession` script [defined above](https://github.com/NixOS/nixpkgs/blob/3ff2dfb7fa9c9ad8c06eac6199aa8443fbd6f003/nixos/modules/services/x11/display-managers/default.nix#L38) and… um… I don’t really see any way to configure that right now :disappointed:.

But what I do see is that the script sources `/etc/profile` but not `~/.profile` _and_ it also sources `~/.xprofile`. So, even though I’m not a great fan of how all this stuff works right now, seems that this can be easily fixed.

First of all, you can already use `~/.xprofile`. Second, sourcing `$HOME/.profile` can be easily added next to `. /etc/profile`.

**Comment by listx** [comment]
I've done some more digging, and here are my findings:

(1) `~/.xprofile` does indeed get executed by Slim on login just once. Great!
(2) Unfortunately, `gpg-connect-agent updatestartuptty /bye` (same as `echo UPDATESTARTUPTTY | gpg-connect-agent`) does not pick up the right tty because from inside `~/.xprofile`, the `tty` command returns `not a tty`.

I am assuming that `~/.xprofile` gets invoked too early --- I am not familiar with the intricacies of `tty`. 
On the other hand, I can probably just manually invoke `gpg-agent` as stated in `gpg-agent(1)`.
I am very curious though why running `tty` inside `~/.xprofile` results in `not a tty`.

To summarize my issue as stated in #5200 , basically I cannot use gpg-agent to access the SSH private key stored in my Yubikey in an X session with `services.xserver.startGnuPGAgent` because the `tty` field is not set properly, resulting in the pinentry box never showing up unless I invoke `gpg-connect-agent updatestartuptty /bye` in some terminal after I log in with Slim.
Sorry about the mouthful, but I think it bears repeating.

At this point I'm actually leaning toward not using `services.xserver.startGnuPGAgent` at all --- for one thing, I cannot customize the pinentry program to use `pinentry-tty` because it calls `gpg-agent` with `pinentry-gtk-2`, like this:

```
 > ps aux | grep gpg
l        16589  0.0  0.0 121960  2516 ?        Ss   12:10   0:00 /nix/store/9knqbd4bhg841y5q5xg76dc8ybp6kv7f-gnupg-2.0.27/bin/gpg-agent --enable-ssh-support --daemon --pinentry-program /nix/store/s3h0906y4qg2x6iq9h4vc9jjy37bajj0-pinentry-0.9.1/bin/pinentry-gtk-2 --write-env-file /home/l/.gpg-agent-info /nix/store/i4yzyjcxbj4l95vgp76wcjqjmdr28hcc-xsession /nix/store/i4yzyjcxbj4l95vgp76wcjqjmdr28hcc-xsession 'none + xmonad'
```

I am tempted to make our `startGnuPGAgent` less hard-coded, so that it actually relies on `~/.gnupg/gpg-agent.conf` for all settings as per the upstream guidelines, but (1) I do not know Nix expressions that well and (2) I'd rather just start the daemon myself manually for more control (I use a Yubikey for work and need a stabilized solution sooner than later).

If someone does end up refactoring `startGnuPGAgent`, please call it with just `gpg-agent --daemon` as suggested in `gpg-agent(1)`.

**Comment by listx** [comment]
As an aside, I just read `gpg-agent(1)` and in there there's this text:

```
--daemon [command line]
    Start the gpg-agent as a daemon; that is, detach it from the console and run it
    in the background. Because gpg-agent prints out important informa‐ tion
    required for further use, a common way of invoking gpg-agent is: eval
    $(gpg-agent --daemon) to setup the environment variables. The option
    --write-env-file is another way commonly used to do this. Yet another way
    is creating a new process as a child of gpg-agent: gpg-agent --daemon /bin/sh.
    This way you get a new shell with the environment setup properly; if you exit
    from this shell, gpg-agent terminates as well.
```

.
If you look at what I pasted in my comment above, we actually call xsession with an argument to itself:

```
/nix/store/9knqbd4bhg841y5q5xg76dc8ybp6kv7f-gnupg-2.0.27/bin/gpg-agent ... /nix/store/i4yzyjcxbj4l95vgp76wcjqjmdr28hcc-xsession /nix/store/i4yzyjcxbj4l95vgp76wcjqjmdr28hcc-xsession 'none + xmonad'
```

.
If I look into the file `/nix/store/i4yzyjcxbj4l95vgp76wcjqjmdr28hcc-xsession`, it is just a `/bin/sh` script.
That script has this part in it:

```
if test -z "$SSH_AUTH_SOCK"; then
    # Restart this script as a child of the GnuPG agent.
    exec "/nix/store/9knqbd4bhg841y5q5xg76dc8ybp6kv7f-gnupg-2.0.27/bin/gpg-agent"                         \
      --enable-ssh-support --daemon                             \
      --pinentry-program "/nix/store/s3h0906y4qg2x6iq9h4vc9jjy37bajj0-pinentry-0.9.1/bin/pinentry-gtk-2"  \
      --write-env-file "$HOME/.gpg-agent-info"                  \
      "$0" "$sessionType"
fi
```

.
I believe this is a bug.
We are executing `gpg-agent` with "$0" and "$sessionType", but somewhere along the way we end up calling `xsession` with an argument to itself.
This probably has something to do with the "crazy apply magic" you stated above.
FWIW, `gpg-agent` called this way correctly exits if I do `CTRL-ALT-BackSpace`, but still, it's weird and confusing.

I'm using gnupg 2.0.27.

**Comment by listx** [comment]
For what it's worth, I've tried just calling `gpg-connect-agent updatestartuptty /bye` as a hotkey fired up by Xmonad (my window manager), and it still does not work.

So, the motivation behind me filing this bug in the first place is no longer there (as it's probably some quirky gpg-agent issue).

Not sure what to do with this issue --- feel free to close (although I suspect future Yubikey SSH + NixOS + Slim users might want to reopen it).

**Comment by lethalman** [comment]
The fact that we call xsession again is correct. We rerun the xsession again and again for every session modifier program, like dbus-launch, systemd-inhibit ecc.. It's expected to work like that, it's not  a bug.

**Comment by peti** [comment]
Our whole gpg-agent strategy in NixOS is obsolete with GnuPG 2.1.x anyway. Users can now start the daemon entirely for themselves without support from the OS. See  c4018c0e65f825584f6154fd91b85d7ad6fe9896 for details.
