### ISSUE TITLE
qemu fails building EC2 AMI: `CPU model ‘host’ requires KVM`

### ISSUE THREAD

**Issue by anmonteiro** [NixOS/nixpkgs#85394]
**Describe the bug**
When trying to generate an EC2 AMI, `qemu` fails with:

> qemu-system-x86_64: CPU model ‘host’ requires KVM

This has been reported by someone else in the NixOS Discourse too: https://discourse.nixos.org/t/new-constraint-between-release-19-09-and-20-03-in-package-qemu/6297

I've tried reverting https://github.com/NixOS/nixpkgs/commit/2bd296a7e9551fcc74330460d6bf47810a8f9555 and it succeeds for me, noting that's the commit that introduced the problem.

**To Reproduce**
1. Launch an EC2 instance
2. Run the following:
```shell
$ export NIXOS=/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/
$ nix-build -A amazonImage.x86_64-linux $NIXOS/release.nix
```

**Expected behavior**
Qemu would succeed in creating a disk image

**Notify maintainers**
cc @volth who's the author of the referenced commit. I'm not sure what the right fix is here, so would appreciate some guidance.

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/pull/83920 should fix nested virtualization

**Comment by anmonteiro** [comment]
Oh cool! I missed that. I suppose this can be closed then. Thanks for the link

**Comment by jpgu-epam** [comment]
I faced the same issue and reverting was the only option that worked. The proposed solution in #83920 didn't work. Still getting the same error message.
