### ISSUE TITLE
Adding a host to the `serverAliases` does not cause a refetch of the let's encrypt certificate.

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#85437]
**Describe the bug**

I use code like this:
```
        services.nginx.virtualHosts =
          {
            "${head (cfg.hosts)}" =
              {
                enableACME = true;
                forceSSL = true;
                locations."/".proxyPass =
                  "http://localhost:${builtins.toString (cfg.port)}";
                serverAliases = tail cfg.hosts;
              };
          };
```

Whenever I add a host to `cfg.hosts` at the end, the let'sencrypt certificate is not refetched, and as a result the certificate is not valid for that alias.
When I add the new alias to the front of `cfg.hosts`, it does work. (Then it's not a `serverAlias`.)

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.92, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- nginx
```

**Comment by nh2** [comment]
It seems to me that `serverAliases` was intended to be taken care of by

https://github.com/NixOS/nixpkgs/blob/2a6c9b13c0f55301ed96b865cf64b3a1fd3d108f/nixos/modules/services/web-servers/nginx/default.nix#L744

**Comment by NorfairKing** [comment]
I think the service may be restarted correctly, but the service doesn't actually get a new certificate because previous one is supposedly still valid..

**Comment by lheckemann** [comment]
Yes, can confirm this after a quick test — I added a server alias without setting appropriate DNS records and the cert service didn't fail.

**Comment by NorfairKing** [comment]
Still relevant.

**Comment by NorfairKing** [comment]
Still relevant, but may have been fixed. Will check soon.

**Comment by aanderse** [comment]
I think @m1cr0man resolved this one...

**Comment by NorfairKing** [comment]
Jup, seems to be fixed!
