### ISSUE TITLE
musl missing dynamic-linking

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nixpkgs#8543]
This derivation isn't usable because it looses track of a key file. `/lib/ld-musl-x86_64.so.1` has to be available. Otherwise anything built with `musl-gcc` will fail to run with the mysterious `-bash: ./a.out: No such file or directory` error.

This might present a particular problem for `nix` since it has to be an absolute path to the interpreter. Anything built with `musl-gcc` will need it's interpreter set to the absolute path of `ld-musl*.so.1` in the nix store.

**Comment by gitfoxi** [comment]
I take it back. It's not totally unusable. You can compile like `musl-gcc -static`. It's just dynamic linking which it can't handle.

Might be interesting to try to build a completely statically linked system this way.

**Comment by gitfoxi** [comment]
I think it will be as simple as modifying `musl-gcc.specs`, this line:

    -dynamic-linker /lib/ld-musl-x86_64.so.1 -nostdlib %{shared:-shared} %{static:-static} %{rdynamic:-export-dynamic}

needs to point to the nix store and `/lib/ld-musl-x86_64.so.1` needs to be in the store.

**Comment by gitfoxi** [comment]
It would suffice to pass `--syslibdir=...` to `configure` but that would mean knowing before you build your ultimate path in the nix store. I don't know if it's possible to calculate that ahead of time but I guess probably not.

**Comment by dnhgff** [comment]
@gitfoxi the nix store path is available by the `$out` environment variable in stdenv build scripts (i assume `source`ing `$stdenv/setup` is what initializes those variables)

the nix store path is computed as a function of the inputs to a build. you can notice this if your build is not deterministic and you find yourself with different binaries under the same path on different machines

**Comment by dnhgff** [comment]
ah, i was correct initially (i deleted my comment out of fear of lying)

@gitfoxi the output store path is available in the `$out` variable in stdenv build scripts (set by `buildPhase` etc). Even if you set the `builder` argument to stdenv, you can `source $stdenv/setup` and then this variable will be available to you

**Comment by dnhgff** [comment]
remember, the output path is computed as a function of the inputs to a package, not a hash of its output. you can notice this if your build is not deterministic, and you end up with different binaries under the same store path on separate computers

**Comment by gitfoxi** [comment]
Thanks @dnhgff. I'm still figuring it out. No matter what I do, I can't get get configureFlags or configurePhase to pass the interpolated value of `$out`. It just ends up literally configuring it as `./configure --prefix=$out`. I did have success using a builder script.

```
source $stdenv/setup

tar xvfz $src
cd musl*

./configure --prefix=$out --enable-static --enable-shared --syslibdir="$out"/lib
make -j16
make install
```

This clunky solution works, but I'm sure it's not how the pros do it.

**Comment by domenkozar** [comment]
Fixed
