### ISSUE TITLE
Packaging request: ssh-chat

### ISSUE THREAD

**Issue by mnajib** [NixOS/nixpkgs#85447]
**Project description**

Custom SSH server written in Go. Instead of a shell, you get a chat prompt.

**Metadata**

* homepage URL: https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc
* source URL: https://github.com/shazow/ssh-chat
* license: MIT
* platforms: MacOS (darwin/amd64) and Linux (386, amd64, and ARM6 for your RaspberryPi)

**Comment by IvarWithoutBones** [comment]
Package seems to have been added to nixpkgs, so the issue can be closed
