### ISSUE TITLE
Microsoft teams: while calling, teams fallbacks on ALSA plugin back-end which butchers the output

### ISSUE THREAD

**Issue by Elyhaka** [NixOS/nixpkgs#85449]
**Describe the bug**

When calling somebody using Microsoft Teams, it seems that the softwares fallback on ALSA plugin, which makes the audio output butchered (hearing noises when someone's talking, but unable to understand what this person is saying).

**To Reproduce**

1. Install teams (require an Office 365 accounts)
2. Call somebody

**Expected behavior**
It should use the PulseAudio backend during calls.

**Additional context**
I'm using Sway as my window manager (thus, running on wayland).

**Notify maintainers**

 - Microsoft Teams package maintainer: @liff 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.3, NixOS, 20.09pre221322.8686922e68d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre221322.8686922e68d"`
 - channels(ely): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by liff** [comment]
How can one tell it that it falls back to the ALSA plugin? Apart from the butchered sound that is?

**Comment by Elyhaka** [comment]
Inside Pavucontrol, you see it uses an "ALSA Plugin" as a backend. It shows ALSA __only__ during a call, on the rest of the software it shows as a standard pulseaudio program output.
