### ISSUE TITLE
Unexposed taskwarrior theme files

### ISSUE THREAD

**Issue by andyseve** [NixOS/nixpkgs#85444]
**Unexposed taskwarrior theme files**
Only place where taskwarrior theme files are available is inside nix store path of taskwarrior. This means that .taskrc needs to be changed every time after taskwarrior is built. It would be great if taskwarrior has an option to expose its theme files.

Please do let me know if there is any way of solving this apart from exposing files.

I am currently running a script manually to fix my taskrc. Here is the script:

```
#!/run/current-system/sw/bin/bash
sed -i '$d' ~/.taskrc
tw_path=$(nix-build "<nixpkgs>" -A taskwarrior)
echo "include $tw_path/share/doc/task/rc/solarized-dark-256.theme" >> ~/.taskrc
```

Apologies if the bug report is in wrong format.

**Comment by doronbehar** [comment]
I install taskwarrior via `environment.systemPackages` and I have the themes installed at `/run/current-system/sw/share/doc/task`.

**Comment by andyseve** [comment]
Thanks a lot! That is working on my system.
