### ISSUE TITLE
Discussion: Usage of gn in Nixpkgs + Chromium dependencies

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#85457]
This issue results from the following discussion: https://github.com/NixOS/nixpkgs/pull/83290#issuecomment-615382049

## Open questions

- Should we even package `gn` in Nixpkgs?
- How do we know when to update `gn` and to which version (since there are no tagged releases), if we don't base it on the current Chromium release (stable channel)?
  - Personally, I'd base the `gn` version on the version that is currently required by Chromium stable (even if we wouldn't use it to build Chromium)

## Related Chromium questions

- Should we use `gn``from Nixpkgs to build Chromium (83290#issuecomment-615382049)
- Generally: Which Chromium dependencies should be re-used from Nixpkgs and which should be built from the tarball?
  - AFAIK most distributions are somewhere between building everything from the Chromium sources and re-using all system libraries
  - Should we use (i.e. trust) pre-built binaries for some dependencies (like `gn`)
- Should we backport `gn` updates to the stable channel or override the `gn` version for Chromium (if we'd use `gn` from Nixpkgs)

cc `gn` maintainers: @stesie @matthewbauer

PS: Personally I don't have a strong opinion here. I'm fine with the current situation, but I also wouldn't mind if we wanted to change something (though I cannot guarantee that I'll have time for the necessary Chromium changes - PRs are obviously welcome).

**Comment by volth** [comment]
I made `chromium-git` (which is able to build `chromium`s from 64 to 84, (probably older too, but it would require older nixos with older glibc)) free from `pkgs.gn` and `pkgs.nodejs`:

https://github.com/NixOS/nixpkgs/pull/66438/commits/ac46de7f7c30d71670ee690c2b2244c002d2965f

**Comment by primeos** [comment]
This should be (at least partially) resolved since d7f53864741aa0cb3a992e74ada3153a89a85f69.
