### ISSUE TITLE
Request: Terminal plots with sgreben/jp

### ISSUE THREAD

**Issue by operator-name** [NixOS/nixpkgs#85479]
**Project description**
Dead simple terminal plots from JSON (or CSV) data. Bar charts, line charts, scatter plots, histograms and heatmaps are supported. Written in go.

**Metadata**

* homepage URL: https://github.com/sgreben/jp
* source URL: https://github.com/sgreben/jp
* license: [mit, apache2](https://github.com/sgreben/jp#licensing)
* platforms: [unix, linux, darwin](https://github.com/sgreben/jp#get-it)

**Issues**
At the moment [nixpkgs.jp is taken by jmespath/jp](https://nixos.org/nixos/packages.html?attr=jp&channel=nixpkgs-unstable&page=2&query=jp) ([pkgs/development/tools/jp/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/jp/default.nix)).

**Comment by operator-name** [comment]
still import to me

**Comment by papojari** [comment]
There is already a package named `jp`.
