### ISSUE TITLE
makeWrapper --add-flags only prepends flags

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#85510]
In short: in `makeWrapper`, `--add-flags` adds the given flags before any user given flags, if I understand correctly. It would be great if this could be altered, because some programs only take into account the first occurrence of an option (e.g., rofi). So, if the wrapper has added some flags, it's impossible for the user to override those flags.

**Comment by veprbl** [comment]
Regarding composable wrappers there is a discussion in #78792

**Comment by jluttine** [comment]
still important to me

**Comment by veprbl** [comment]
>  some programs only take into account the first occurrence of an option (e.g., rofi)

This is a somewhat unusual behaviour. Usually a program would validate the options for correctness, so if it only uses the first occurrence then the second identical option should cause a failure to validate. @jluttine I don't know what your use case yet, but from general considerations it seems like it might be not widespread enough to warrant a complicated implementation in the generic `makeWrapper`. This is only my opinion.

**Comment by jluttine** [comment]
At least Rofi is one usecase. I read about this somewhere and it turned out that there isn't any standard on how the program should behave (e.g., whether to take into account the first or last occurrence), so either way is an ok behavior for an application. That's why it'd be nice if `--add-flags` would work with both ways.

**Comment by tomberek** [comment]
Also occurs when trying to wrap gcc where order matters.

**Comment by citriqa** [comment]
resolved with #172769.
