### ISSUE TITLE
Introducing services.acme.email encourages setups which potentially leak security information

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixpkgs#85534]
## Issue description

With the replacement of simp_le with lego (#77578), the new, required `services.acme.email` option was introduced. I suspect that many NixOS admins don't have a email address readily suitable for this option, especially when they maintain several servers for different purposes/organizations; creating and maintaining such email address(es) is non-trivial. (At least, the statement above is true for me.)

So, without having an obvious value for this option, a certain percentage of admins will put dummy values like `foo@example.com` or `foo@bar.com` there, to get it out of the way. This is a problem because potentially sensitive information (expiration notices) is sent to this email address, and, moreover, this email address is said to allow to recover access to the account (whatever it means).

### Steps to reproduce

1. Use ACME certificate in a 19.09 system.
2. Try to switch to master/unstable/20.03.
3. Be challenged with the requirement to specify the email address for ACME.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.32, NixOS, 20.09pre221706.b61999e4ad6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre221706.b61999e4ad6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by flokli** [comment]
I'm not sure if this is much of a nixpkgs problem TBH - Configuring an email and asking to accept the TOS, has been required by Letsencrypt for some time by almost all clients, we are now consistent with that too.

If users configure an email adress that they don't control, that's not really something we can detect or prevent. The description

> Contact email address for the CA to be able to reach you

Is already quite how this email address is likely to be used.

I (really) hope you can do any sort of actions (revocations, renewals) by just acessing the underlying mailbox.

**Comment by m1cr0man** [comment]
Having received a few expiry emails from Lets Encrypt already, I went back to check them for data that could be used to take malicious actions against the cert owner.

The list of domains really isn't a security issue. If someone looks at the certificate for my domain, they can read all the domains it is associated with. It's public information.

Beyond the list of domains, there is the ability to unsubscribe from the list. Given that if the certificate owner has used a dummy address (or one that exists but does not belong to them), I don't see a security issue with this at all.

There is an explicit statement in the email that would infer that you can't do anything certificate-oriented with this email address:
```
Unfortunately, we can't provide support by email.
```
On top of this, Let's Encrypt specify [on their site](https://letsencrypt.org/docs/expiration-emails/#subscribing) that there is only one use for the email address:
```
If you provide an email address to Let’s Encrypt when you create your account, we’ll automatically send you expiry notices when your certificate is coming up for renewal
```
This issue would imply that a person exists that 1) Wants to keep their cert domains list private, and 2) Used a dummy address in their configuration. I feel that such a person is practically non existent, and there's not much we could do in Nix about them either.

**Comment by pvgoran** [comment]
> I'm not sure if this is much of a nixpkgs problem TBH - Configuring an email and asking to accept the TOS, has been required by Letsencrypt for some time by almost all clients, we are now consistent with that too.

If NixOS's ACME integration required the email from the beginning, it would be just the same issue (or non-issue) like everyone face. However, introducing this requirement when upgrading an already working system is a bit different, like I described before.

> I (really) hope you can do any sort of actions (revocations, renewals) by just acessing the underlying mailbox.

I don't quite understand you here. Maybe you intended to write "can not do" instead of "can do"?

> The list of domains really isn't a security issue. If someone looks at the certificate for my domain, they can read all the domains it is associated with. It's public information.

Rather, I was thinking about disclosure of information about certificates' (non-)renewal. However, since LetsEncrypt sends data to certificate logs (https://www.certificate-transparency.org/how-ct-works), anyone can just grab this information anyway.

> There is an explicit statement in the email that would infer that you can't do anything certificate-oriented with this email address:
> On top of this, Let's Encrypt specify on their site that there is only one use for the email address:

Well, from what I see, that's not true. https://certbot.eff.org/docs/using.html says:

```
  --register-unsafely-without-email
                        Specifying this flag enables registering an account
                        with no email address. This is strongly discouraged,
                        because in the event of key loss or account compromise
                        you will irrevocably lose access to your account. You
                        will also be unable to receive notice about impending
                        expiration or revocation of your certificates. Updates
                        to the Subscriber Agreement will still affect you, and
                        will be effective 14 days after posting an update to
                        the web site. (default: False)
  -m EMAIL, --email EMAIL
                        Email used for registration and recovery contact. Use
                        comma to register multiple emails, ex:
                        u1@example.com,u2@example.com. (default: Ask).
```

This does imply that access to the email is supposed to provide some ability to do "recovery", and absence of email means "losing access to your account" (which in turn implies that presence of email gives some kind of access to the account).

**Comment by flokli** [comment]
I propose checking back with LE (via their forum) about how this mail address is being used, if you're concerned about account compromise.

> If NixOS's ACME integration required the email from the beginning, it would be just the same issue (or non-issue) like everyone face. However, introducing this requirement when upgrading an already working system is a bit different, like I described before.

When switching to a new release, NixOS users are expected to read and act on the release notes, as well as on evaluation failures due to changed module options.

We do change options via a new release, and the fact that the email address is now required is clearly visible.

I don't really see anything actionable in nixpkgs at this time, closing.
