### ISSUE TITLE
Add package for kwin-lowlatency

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixpkgs#85541]
**Project description**
kwin-lowlatency is a fork of kwin (KDE windows manager) which provides many adjustments that greatly reduce latency, especially on monitors with high refresh rates.

**Metadata**

* homepage URL: https://github.com/tildearrow/kwin-lowlatency
* source URL: https://github.com/tildearrow/kwin-lowlatency
* license: gpl2
* platforms: unix, linux

**Additional notes for packaging**

Currently kwin-lowlatency only really works for X11 so as a nice to have it would be great if kwin-lowlatency would provide a warning (or even stop installing itself) if you are using wayland instead of X11

**Comment by ajs124** [comment]
There was #89234

@pasqui23, now that #84542 is merged, how about it?

**Comment by pasqui23** [comment]
Yeah @ajs124 ,I will takle it ASAP
Still important to me

**Comment by InternetUnexplorer** [comment]
This should probably be closed, as it was mentioned in #108987 that an overlay is probably the best way to go.

For anyone still interested, I've set up an overlay and binary cache [here](https://github.com/InternetUnexplorer/kwin-lowlatency-overlay) which I plan on keeping up-to-date for the foreseeable future.

**Comment by pasqui23** [comment]
Yep the overlay is the best way
