### ISSUE TITLE
System sound and pop-up notifications broken on 20.03 Beta

### ISSUE THREAD

**Issue by freeman42x** [NixOS/nixpkgs#85559]
**Describe the bug**

After upgrade of NixOS from 19.03 to 20.03 Beta sound and pop-up system notifications stopped working for some programs such as Pidgin or Hexchat.

The system notifications are still working fine for Slack, Riot or Discord for example.

**To Reproduce**

Upgrade NixOS to 20.03 Beta

**Expected behavior**

Expecting system notifications to work.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.32, NixOS, 20.03beta1405.a17e021b948 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03beta1405.a17e021b948"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by razvan-flavius-panda** [comment]
If there are any tests I can do on my machine to help fix this I would be glad to help.

**Comment by worldofpeace** [comment]
System sound and notifications are very specific, what is your configuration.nix for the desktop manager or window manager you are using? (display-manager is also useful to know).

**Comment by razvan-flavius-panda** [comment]
@worldofpeace This are my settings under that:

>   # Enable the X11 windowing system.
>   services.xserver.enable = true;
>   services.xserver.layout = "us";
>   services.xserver.xkbOptions = "eurosign:e";
>   services.xserver.libinput.enable = true; # Enable touchpad support.
>   services.xserver.videoDrivers = [ "nvidia" ]; # NVidia drivers
>   
>   # Enable the KDE Desktop Environment.
>   services.xserver.displayManager.sddm.enable = true;
>   services.xserver.desktopManager.plasma5.enable = true;

**Comment by razvan-flavius-panda** [comment]
I downgraded NixOS to `19.09` and the issue persists. For both Hexchat and Pidgin I am getting no pop-ups or message notification sounds.

**Comment by razvan-flavius-panda** [comment]
And also downgraded NixOS to `19.03` and the issue persists. This is the original NixOS version I upgraded from to 20.03 Beta when it got broken. At this point I am not sure what to do but it does not seem related to the NixOS version.
