### ISSUE TITLE
Update to gtk3 3.24.17 added a bug that prevents displaying windows with a custom surface. Manifests in waybar.

### ISSUE THREAD

**Issue by calbrecht** [NixOS/nixpkgs#85555]
**Describe the bug**
Changes in gtk3 `3.24.17` introduced a bug that [prevented displaying windows with custom surface](https://gitlab.gnome.org/GNOME/gtk/-/issues/2572). A fixed version `3.24.18` is available.
The consequence of this bug is that those windows are invisible to the user.
A manifestation of this bug is reproducible with `waybar`, that is where i noticed.
The culprit seems to be `gtkmm3`, please see following details.

<details><summary>Overlays that fix the behaviour</summary>

```diff
+   gtk3_24_18 = pkgs.gtk3.overrideAttrs (old: rec {
+     version = "3.24.18";
+     src = fetchurl {
+       url = "mirror://gnome/sources/gtk+/${stdenv.lib.versions.majorMinor version}/gtk+-${version}.tar.xz";
+       sha256 = "1lia2ybd1661j6mvrc00iyd50gm7sy157bdzlyf4mr028rzzzspm";
+     };
+   });
+ 
+   gtkmm3_24_18 = pkgs.gtkmm3.override {
+     gtk3 = self.gtk3_24_18;
+   };
+ 
+   waybar = pkgs.waybar.override {
+     gtkmm3 = self.gtkmm3_24_18;
+   };

```
</details>

**To Reproduce**
1. Be on `sway` window manager
2. Have the `waybar` installed
3. Run it

**Expected behavior**
Waybar is visible while running

**Screenshots**
;)

**Notify maintainers**
@FlorianFranzen @minijackson @synthetica @eonpatapon @raskin @vcunat @lethalman @worldofpeace

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.4, NixOS, 20.09.git.a2d9f584333M (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/home/alab/ws/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
version: "3.24.17"
# a list of nixos modules affected by the problem
module:
```

**Comment by hedning** [comment]
Yeah, there's a fix in staging so should hopefully get into the pipeline soon: https://github.com/NixOS/nixpkgs/pull/84695

**Comment by worldofpeace** [comment]
@hedning I interpret that as a committed fix so I think we can close this.
