### ISSUE TITLE
cabal-install needs ghc

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#8558]
Should be a dependency.

**Comment by peti** [comment]
Actually, `cabal-install` works just fine without `ghc`. Remember that some people use other compilers, too, like `jhc` , `uhc`, or even `hugs`.

**Comment by Profpatsch** [comment]
@peti It doesn’t work *at all* without a compiler. So at least a default shoud be set.

**Comment by peti** [comment]
If you'd like to suggest a concrete improvement, then please don't hesitate to open a pull request!
