### ISSUE TITLE
nodePackages: regeneration error

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#85618]
**Describe the bug**
`pkgs/development/node-packages/generate.sh` on current master fails:
```
< ... omitted ... >
http 200 https://registry.npmjs.org/nodemon
info attempt registry request try #1 at 10:55:29 PM
http request GET https://registry.npmjs.org/ts-node
http 200 https://registry.npmjs.org/ts-node
info attempt registry request try #1 at 10:55:32 PM
http request GET https://registry.npmjs.org/@apollographql%2Fapollo-tools
http 200 https://registry.npmjs.org/@apollographql%2Fapollo-tools
Cannot resolve version: @apollographql/apollo-tools@>=0.4.6 <0.5.0
```

It's hard to discover which package causes the error.
Note that the latest version of package `@apollographql/apollo-tools` on [npm](https://www.npmjs.com/package/@apollographql/apollo-tools) is 0.4.5 now.

**To Reproduce**
1. `cd pkgs/development/node-packages && ./generate.sh`

**Expected behavior**
Successfully update `node-packages-v*.nix`.

**Notify maintainers**

@Mic92 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.32, NixOS, 20.09pre221706.b61999e4ad6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre221706.b61999e4ad6"`
 - channels(oxa): `"home-manager, mozilla"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nodeModules
```

**Comment by Mic92** [comment]
I would say vue/cli is pulling that in.

**Comment by Mic92** [comment]
Upstream issue: https://github.com/vuejs/vue-cli/issues/5403
They say it has been fixed?

**Comment by oxalica** [comment]
Checked to be fixed by upstream.
