### ISSUE TITLE
incompatible chrome and chromedriver

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#85629]
**Describe the bug**
Chrome and Chromedriver are incompatible on my install.

**To Reproduce**
1. Install chrome and chromedriver from nixpkgs
2. Try using chrome with selenium.
3. Get this error
    This version of ChromeDriver only supports Chrome version 78

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.108, NixOS, 19.09.2218.a81842b6994 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2218.a81842b6994"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

**Comment by ldeck** [comment]
It is possible to make your own derivations to solve this (which I’ve done locally), following the instructions from https://www.chromium.org/getting-involved/download-chromium. It’s laborious to do so, however, so this would definitely be a welcome option.

**Comment by alexanderkranga** [comment]
Hi,

Recently I had this same issue. Google Chrome was updated to version 87 in all channels, but chromedriver was still at version 85. When running my tests from nix-shell environment 
```nix-shell -p google-chrome chromedriver -I nixpkgs=channel:nixos-unstable```
I got an error message that chromedriver is only compatible with Google Chrome version 85. I think to fix this issue `google-chrome` package needs to be updated along with `chromedriver`. And to ensure this, we could add a test like https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/chromium.nix but for `google-chrome` package.
@primeos @msteen I see that you guys are maintainers for `google-chrome` package. Can you please let me know what needs to be done to address this issue?

Thank you in advance!

**Comment by primeos** [comment]
> @primeos @msteen I see that you guys are maintainers for google-chrome package. Can you please let me know what needs to be done to address this issue?

Ideally `chromedriver` would also source `pkgs/applications/networking/browsers/chromium/upstream-info.json` which we use to update Chromium and Google Chrome. However, I just tried to update `chromedriver` to version `87.0.4280.66` (to see if that would work) but that version doesn't seem to be available (yet?):
```
$  nix-prefetch-url -A chromedriver.src
[0.0 MiB DL]
error: unable to download 'https://chromedriver.storage.googleapis.com/87.0.4280.66/chromedriver_linux64.zip': HTTP error 404
```

So unfortunately it doesn't look like we could keep them in sync. But maybe that isn't even required and we only need the latest `chromedriver` release. I'm not familiar with `chromedriver` though.

@cillianderoiste @marsam (`chromedriver` maintainers) do you have any insight how this could be solved? Would the latest `chromedriver` be compatible with Chrome 87.0.4280.66? And is there a feed/URL to get the latest version programmatically?

**Comment by alexanderkranga** [comment]
@primeos thank you for this pull request, I tested your change and all works good for me. Below are the steps I did to test it from my side:
1. Created this URL by using sha of your commit:
```https://github.com/NixOS/nixpkgs/archive/1179b29954de59f1057e6272c4b35ce38591a913.tar.gz```
2. Used this URL to start a nix-shell environment like this:
```nix-shell -p google-chrome chromedriver -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/1179b29954de59f1057e6272c4b35ce38591a913.tar.gz```
3. Executed my tests there, here is some output:
```
unpacking 'https://github.com/NixOS/nixpkgs/archive/1179b29954de59f1057e6272c4b35ce38591a913.tar.gz'...
11:47:49 these derivations will be built:
11:47:49   /nix/store/xx6yds6f2ba7riszfvifs19zx6bc5fzd-google-chrome-stable_87.0.4280.66-1_amd64.deb.drv
11:47:49   /nix/store/kzw4c2kmz88794h84iwigbaji4mcx7bn-google-chrome-87.0.4280.66.drv
...
11:48:35 copying path '/nix/store/q7n4jzldkz17b2fa5b2qmr83p0iw7366-chromedriver-87.0.4280.20' from 'https://cache.nixos.org'...
...
11:48:37 building '/nix/store/xx6yds6f2ba7riszfvifs19zx6bc5fzd-google-chrome-stable_87.0.4280.66-1_amd64.deb.drv'...
...
11:51:07     Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 5717
11:51:07     Only local connections are allowed.
11:51:07     Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
11:51:07     ChromeDriver was started successfully.
```

From my side I can confirm that your fix is working properly. Thank you so much!
