### ISSUE TITLE
hakyll package on 20.03 has preview server disabled

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#85670]
**Describe the bug**

The `hakyll` package on NixOS 20.03 has the preview server disabled, but this does not seem to be explicitly configured anywhere, and the dependencies are still pulled in which suggests that this isn't intentional. Previously the preview server has always been available, so I was hoping this could be reinstated.

**To Reproduce**
1. `git clone https://github.com/vaibhavsagar/website`
2. `cd website`
3. `git checkout b07fce730ed566300e0a6304e875965b5bb1a7ff`
4. `nix-shell --run 'runhaskell site.hs server'`

**Expected behavior**
A web server is launched.

**Screenshots**

**Additional context**
I looked at the source and couldn't find any mentions of `previewServer`, which is the flag that disables the preview server for Hakyll.

**Notify maintainers**
@cdepillabout(?)

**Metadata**
This is my system info, although the problem is with commit `5272327b81ed355bbed5659b8d303cf2979b6953` of `nixpkgs` (see `versions.json` in my repository)

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 19.09.2345.6d445f8398d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(vaibhavsagar): `""`
 - channels(root): `"nixos-19.09.2345.6d445f8398d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Sir4ur0n** [comment]
I confirm the issue, I just stumbled on exactly the same issue after upgrading to 20.03 today :disappointed: 

I think ideally the default flags should respect the default, that is all enabled except `buildwebsite`.

In the mean time, if anyone has a workaround, I'd be interested!

**Comment by cdepillabout** [comment]
I took a quick look at this as well, and I also don't see why the preview server wouldn't be enabled.

If one of you (or anyone else) wants to take a look at this and figure out why the preview server is disabled, I'd be happy to merge in a fix.

**Comment by vaibhavsagar** [comment]
Here's a snippet of the build output of `callHackage "hakyll" "4.13.0.1" {}`:
```
Configuring hakyll-4.13.0.1...
Flags chosen: buildwebsite=False, checkexternal=True, previewserver=False,
usepandoc=True, watchserver=True
```

I don't understand why the `previewServer=False` flag is being set though. Still investigating.

**Comment by vaibhavsagar** [comment]
I think I've figured this out: the upper bound on `warp` is too restrictive, so Cabal seems to be setting that flag to `False` for us.

If I clone the `hakyll` repository, check out the `v4.13.0.1` tag, and try to build it with this `default.nix`:

```nix
let
  nixpkgs-src = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/tarball/5272327b81ed355bbed5659b8d303cf2979b6953";
    sha256 = "0182ys095dfx02vl2a20j1hz92dx3mfgz2a6fhn31bqlp1wa8hlq";
  };
  nixpkgs = import nixpkgs-src {};
  hakyll = nixpkgs.haskellPackages.callCabal2nix "hakyll" ./. {};
in if nixpkgs.lib.inNixShell then hakyll.env else hakyll
```

Then I get this (`previewServer=False`):
```
Flags chosen: buildwebsite=False, checkexternal=True, previewserver=False,
usepandoc=True, watchserver=True
```

When I try to `runghc Setup.hs configure --enable-tests; runghc Setup.hs build` then I also get the same thing.

However, if I look at the version of `warp` that's pulled in:

```bash
[nix-shell:~/repos/hakyll]$ ghc-pkg list | grep warp
    warp-3.3.5
```

I see that it is higher than the upper bound of `3.3` in `hakyll.cabal`. After changing the upper bound to `3.4`, this is what I get from `nix-build` (`previewServer=True`):
```
Flags chosen: buildwebsite=False, checkexternal=True, previewserver=True,
usepandoc=True, watchserver=True
```

I suggest patching `hakyll` in `nixpkgs` to bump the upper bound on `warp`, because `doJailbreak` doesn't work on conditional stanzas anyway.

**Comment by vaibhavsagar** [comment]
Here's my suggested fix: https://github.com/NixOS/nixpkgs/pull/85753
