### ISSUE TITLE
emacs GUI doesn't respect XDG_DATA_DIRS

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#85672]
**Describe the bug**

I have defined custom `XDG_DATA_DIRS` but emacs GUI doesn't use that (emacs CLI does).

I looked at `wrapGAppsHook` but didn't spot anything wrong..

**To Reproduce**

Build a clean Emacs (I had aliases affecting, so wanted to bypass all such stuff by using full path to the emacs executable):

```
nix-build '<nixpkgs>' -A emacs
```

Set some custom `XDG_DATA_DIRS`:

```
export XDG_DATA_DIRS="/FOO/BAR/JOHN/DOE:$XDG_DATA_DIRS"
```

Run Emacs GUI:

```
./result/bin/emacs
```

In Emacs, check the environment variable: Press `Alt :` and type `(getenv "XDG_DATA_DIRS)`. You'll get a lon list of paths, but `/FOO/BAR/JOHN/DOE` is not included.

Run Emacs CLI:

```
./result/bin/emacs -nw
```

Again, in Emacs, check the environment variable as previously, and now you'll see `/FOO/BAR/JOHN/DOE` included.

How can this be? Any ideas where's the issue?

**Expected behavior**

I would have expected the environment variables be defined in Emacs so that `XDG_DATA_DIRS` would have included all paths I had in the environment when launching Emacs.

**Notify maintainers**

@lovek323 @peti @the-kenny @jwiegley @adisbladis 

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.31, NixOS, 20.09.git.226bc290434M (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: emacs
# a list of nixos modules affected by the problem
module:
```

**Comment by jluttine** [comment]
Oh, of course, should've tried with vanilla Emacs (remove `.emacs.d` temporarily). Then, it works. So, maybe it's an issue in Spacemacs then.. Perhaps I'll close this, but any ideas are welcome anyway.

**Comment by jluttine** [comment]
Ok, figured it out. Spacemacs had written environment variables to `.spacemacs.env` and read them there. That file had some stupid values for the environment variables and overwrote.

Sorry for bothering you maintainers! Well, at least if someone else hits this same issue, they might find the answer here.

**Comment by michaelpj** [comment]
I too have been bitten by Spacemacs' odd decision to totally change how environment variables work. I recommend just turning it off.
