### ISSUE TITLE
Problems trying to fix tvheadend build on hydra

### ISSUE THREAD

**Issue by simonvandel** [NixOS/nixpkgs#8570]
So I got a mail from hydra saying that tvheadend failed building. Looking at the build results on the hydra page ([x86_64-linux build](http://hydra.nixos.org/build/23343173) and [i686-linux build](http://hydra.nixos.org/build/23339387)) , I don't see the possibility to view the build log to actually know what went wrong. Have I missed something? I think such a feature would make it faster to know what went wrong in build failures.

I then tried to reproduce the build locally by using the "Reproduce locally" feature in the Actions tab. The script hydra however looks faulty in that nothing happens in the "fetch the inputs" phase in the script. Looking at the template in https://github.com/NixOS/hydra/blob/master/src/root/reproduce.tt, a bug must have occurred in generating the script.

Another question: I want to have the tvheadend package available in one of the nix channels. When and how is commits in nixpkgs/master merged into nixpkgs-channels/nixos-unstable?

Thanks

**Comment by simonvandel** [comment]
I just tried checking out the revision of the hydra build, and it built just fine locally. I do not know what the failure on hydra is.

**Comment by pSub** [comment]
I could reproduce the build failure, the relevant part of the log is

```
fetching dvb-scan files ...                       fail
ERROR: Failed to fetch dvb-scan data (use --disable-dvbscan)
```

I guess this worked for you because you don't chroot builds enabled (see `nix.useChroot`). I fixed the build in 18308e6b563cef25f126cd434255f236ebdd6cde by disabling dvbscan. I think this is fine, as you can always run dvbscan later on manually.

**Comment by simonvandel** [comment]
Thanks!

Regarding the missing build log viewable on the Hydra build - wouldn't that be a great feature addition?

**Comment by pSub** [comment]
Normally there are build logs. I don't know why there are currently missing.
