### ISSUE TITLE
Touchpad broken in mysterious ways on 20.03

### ISSUE THREAD

**Issue by jakobrs** [NixOS/nixpkgs#85707]
**Describe the bug**
The touchpad is broken in multiple ways:
- The vertical dpi is *very* low compared to the horizontal dpi
- rolling back and forth again appears to temporarily fix the problems until I reboot, except the dpi is maybe slightly lower than it used the be
- clicking while resting a finger on the touchpad registers as a right click (as in, two finger clicking is too active)

**To Reproduce**
1. Have my laptop
2. Try to move the mouse

Configs: jakobrs/nixos-configuration@13b163d (before), jakobrs/nixos-configuration@c97b111 (after)

**Expected behavior**
Nothing changing.

**Additional context**
It's an AlpsPS/2 ALPS GlidePoint device, on a Lenovo Yoga 500-14ISK. Also, the kernel version is different: 5.6.4 contra 5.6.5.

**Notify maintainers**
There's no `meta.maintainers` list.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.5, NixOS, 20.03.1418.5272327b81e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1422.1e90c46c2d9, nixos-19.09-19.09.2426.9237a09d8ed, nixos-unstable-20.09pre222244.22a3bf9fb9e, nixos-unstable-small-20.09pre222254.77cb7ad618a"`
 - channels(jakob): `"nixpkgs-20.09pre221814.10100a97c89"`
 - nixpkgs: `/home/jakob/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: 
```

**Comment by worldofpeace** [comment]
This is probably an issue with libinput, from looking at your config.
If you could somehow override the version of libinput used by the module, so that it is the version from 19.09, you'd know for sure. 

It's also bit strange, you have many root channels
> "nixos-20.03.1422.1e90c46c2d9, nixos-19.09-19.09.2426.9237a09d8ed, nixos-unstable-20.09pre222244.22a3bf9fb9e, nixos-unstable-small-20.09pre222254.77cb7ad618a"

**Comment by jakobrs** [comment]
I've got so many root channels so that I can import packages from different channels in configuration.nix (see the line with `bluez` or `linuxPackages_latest`). The "main" `nixos` channel is `nixos-20.03`.

I'll try overriding the version of libinput soon.

**Comment by worldofpeace** [comment]
> I'll try overriding the version of libinput soon.

The main issue is you don't want to override libinput for all other packages in nixpkgs, just what is used by the module. If you do the first, you will be rebuilding a huge amount of things, I believe.

**Comment by jakobrs** [comment]
Yeah, I literally just tried it, and gave up once I saw how many packages depend on libinput.

**Comment by jakobrs** [comment]
I applied the following patch to `nixpkgs` and rebuild (using `sudo nixos-rebuild switch -I nixpkgs=./nixpkgs`), and while it didn't fix it right away, it seems doing that and then rebooting fixed it. So yeah, it might be a regression in libinput.

```diff
diff --git a/nixos/modules/services/x11/hardware/libinput.nix b/nixos/modules/services/x11/hardware/libinput.nix
index 9548ecb8ef6..f618d9c85ba 100644
--- a/nixos/modules/services/x11/hardware/libinput.nix
+++ b/nixos/modules/services/x11/hardware/libinput.nix
@@ -4,6 +4,9 @@ with lib;
 
 let cfg = config.services.xserver.libinput;
     xorgBool = v: if v then "on" else "off";
+
+    nixos-19-09 = import <nixos-19.09> {};
+
 in {
 
   options = {
@@ -198,19 +201,19 @@ in {
 
   config = mkIf cfg.enable {
 
-    services.xserver.modules = [ pkgs.xorg.xf86inputlibinput ];
+    services.xserver.modules = [ nixos-19-09.xorg.xf86inputlibinput ];
 
-    environment.systemPackages = [ pkgs.xorg.xf86inputlibinput ];
+    environment.systemPackages = [ nixos-19-09.xorg.xf86inputlibinput ];
 
     environment.etc =
       let cfgPath = "X11/xorg.conf.d/40-libinput.conf";
       in {
         ${cfgPath} = {
-          source = pkgs.xorg.xf86inputlibinput.out + "/share/" + cfgPath;
+          source = nixos-19-09.xorg.xf86inputlibinput.out + "/share/" + cfgPath;
         };
       };
 
-    services.udev.packages = [ pkgs.libinput.out ];
+    services.udev.packages = [ nixos-19-09.libinput.out ];
 
     services.xserver.config =
       ''
```

**Comment by worldofpeace** [comment]
I guess this should be a bugreport to libinput then.

**Comment by worldofpeace** [comment]
@jakobrs If you're up to it, you could git bisect on libinput. It could be rather time consuming, but it looks like a regression.

I good way would be to clone libinput, and overrideAttrs the libinput attribute in the module to change `src =` to it.

**Comment by jakobrs** [comment]
I'll try to bisect. According to git it's only ca 6 steps.

**Comment by jakobrs** [comment]
I believe I've found the relevant commit: It's commit libinput@e7a9c07.

> commit e7a9c07ffe9009c370ba73494729713ee9a7a279 (HEAD, refs/bisect/bad)
> Author: Peter Hutterer <peter.hutterer@who-t.net>
> Date:   Wed Sep 4 15:09:13 2019 +1000
> 
>     udev: parse the EVDEV_ABS properties for a potential fuzz setting
>     
>     Where a fuzz is defined in the 60-evdev.hwdb, we rely on a udev builtin to
>     set the kernel device to that fuzz value. Unfortunately that happens after our
>     program is called with this order of events:
>     1. 60-evdev.rules calls IMPORT(builtin) for the hwdb which sets the EVDEV_ABS_*
>       properties. It also sets RUN{builtin}=keyboard but that's not invoked yet.
>     2. 90-libinput-fuzz-override.rules calls IMPORT{program} for our fuzz override
>       bits. That sets the kernel fuzz value to 0 and sets the LIBINPUT_FUZZ_*
>       propertie
>     3. The keyboard builtin is run once all the rules have been processed.
>     
>     Our problem is that where the fuzz is set in a hwdb entry, the kernel fuzz is
>     still unset when we get to look at it, so we always end up with a fuzz of zero
>     for us and a nonzero kernel fuzz.
>     
>     Work around this by checking the EVDEV_ABS property, extracting the fuzz from
>     there and re-printing that property without the fuzz. This way we ensure the
>     kernel remains at zero fuzz and we use the one from the hwdb instead.
>     
>     Fixes #346
>     
>    Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>

**Comment by jtojnar** [comment]
Could you please report that upstream https://gitlab.freedesktop.org/libinput/libinput/-/issues?

**Comment by jakobrs** [comment]
I realised I should probably test on libinput master and ... it's fixed in master. Commit: wayland-desktop/libinput@19898eb2, issue [#424](https://gitlab.freedesktop.org/libinput/libinput/-/issues/424), pr [!384](https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/384). It's in release 1.15.2.

**Comment by worldofpeace** [comment]
@jakobrs I believe we can pick this patch to stable, or upgrade.

**Comment by jakobrs** [comment]
Applying the patch directly fails, unless I messed something up.

```nix
pkgs.libinput.overrideAttrs (old: {
  patches = old.patches ++ [
    (pkgs.fetchpatch {
      name = "dont-override-udev.patch";
      url = "https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/384.patch";
      sha256 = "184z9awskbs19qmlngqzvp5hp43g6lkxrzzqqpppb16j1y4gs45r";
    })
  ];
})
```

fails.

**Comment by jtojnar** [comment]
`fetchpatch` does not handle patches that create files well.

**Comment by jakobrs** [comment]
I doubt that's the problem. The patch is rejected due to a file that's modified, not new (specifically, test/litest.h). And `wget`ing the patch and adding it directly doesn't fix the problem:

```nix
# wget https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/384.patch
pkgs.libinput.overrideAttrs (old: {
  patches = old.patches ++ [ 384.patch ];
})
```

is still rejected for the same reason.

Here is the .rej file:
```diff
--- test/litest.h
+++ test/litest.h
@@ -302,6 +302,7 @@ enum litest_device_type {
  LITEST_WACOM_ISDV4_4200_PEN,
  LITEST_ALPS_3FG,
  LITEST_ELAN_TABLET,
+ LITEST_ABSINFO_OVERRIDE,
 };

 #define LITEST_DEVICELESS  -2
```

While it would probably be possible to edit the patch directly, upgrading seems much less error-prone to me.

**Comment by jakobrs** [comment]
Is there anything I can do here? Should I backport just the patch (which will require fixing the patch manually), or should I pick 2277a41? If I do the latter, should I only cherry-pick 2277a41, or all the way up to libinput-1.15.4?

**Comment by jtojnar** [comment]
20.03 is EOL soon so we probably should not bother. 20.09 has libinput 1.16.1, which contains the fix.
