### ISSUE TITLE
nixpkgs-unstable blocked by failing inkscape on darwin

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#85713]
**Describe the bug**
See https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents.
https://hydra.nixos.org/job/nixpkgs/trunk/inkscape.x86_64-darwin
https://hydra.nixos.org/build/116949829

It appears numpy is failing on darwin https://hydra.nixos.org/build/116949583.
cc @jonringer @FRidh

**Comment by veprbl** [comment]
> It appears numpy is failing on darwin https://hydra.nixos.org/build/116949583.

I believe this one is before #85636 was merged.

The new failure is:
```
Original error was: dlopen(/nix/store/b1b1g8vq6ij23pcyi6k2ik1p9pfszrmv-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: liblapacke.dylib
  Referenced from: /nix/store/b1b1g8vq6ij23pcyi6k2ik1p9pfszrmv-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: image not found

builder for '/nix/store/hzqbrirlqj6yicf0al4j9g7ryc24ralb-python3.7-numpy-1.18.1.drv' failed with exit code 1
```

cc @matthewbauer

**Comment by jonringer** [comment]
I don't see a .so being explicitly referenced in the nix expression, there's probably something that needs to be patched for darwin to look for the correct shared-library extension.

**Comment by LnL7** [comment]
This was https://github.com/NixOS/nixpkgs/pull/83888, specifically the install_name_tool invocations.
