### ISSUE TITLE
Skype deb package 8.55.0.141 can't be downloaded (404)

### ISSUE THREAD

**Issue by nick-korsakov** [NixOS/nixpkgs#85724]
**Describe the bug**
```shell
building '/nix/store/63nkkxr95y7kghxhihswljwi95qmp5b0-skypeforlinux_8.55.0.141_amd64.deb.drv'...

trying https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.55.0.141_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

https://repo.skype.com/deb/pool/main/s/skypeforlinux/ doesn't contains skypeforlinux_8.55.0.141_amd64.deb.

**To Reproduce**
1. Switch to nixos-20.03 channel.
2. Add skypeforlinux into environment.systemPackages
3. Run sudo nixos-rebuild switch

**Expected behavior**
Skype installed.

**Metadata**
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/0rbnlnd1pvlpii8p72ybvvg672j2wc2f-bash-interactive-4.4-p23-dev
copying path '/nix/store/0rbnlnd1pvlpii8p72ybvvg672j2wc2f-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.03.1422.1e90c46c2d9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(nick): `""`
 - channels(root): `"nixos-20.03.1422.1e90c46c2d9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
I don't know if you absolutely need the dropbox client but you could consider `maestral` as an alternative until this is fixed.

**Comment by nick-korsakov** [comment]
@peterhoeg, DropBox? This issue is about Skype. What do you mean?

**Comment by peterhoeg** [comment]
Sorry, brain fart here.

**Comment by bachp** [comment]
Is sthis still an issue after https://github.com/NixOS/nixpkgs/pull/86354?

**Comment by nick-korsakov** [comment]
Fixed.
