### ISSUE TITLE
Automate updating our osinfo-db entry

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#85774]
Now that we have a osinfo-db entry, we should work on making it auto-update.

* Introducing MR: https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/107#note_328457637
* Script for endlessOS: https://gitlab.com/libosinfo/osinfo-db/-/blob/ab0ae67cf3df4ff6abd7ced9b482902bf04071eb/scripts/updates/endlessos.py

cc @mmilata @worldofpeace

**Comment by mmilata** [comment]
Proposed script: https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/130

As usual I didn't discuss this with anyone and will be modifying it based on feedback, PTAL.

**Comment by Artturin** [comment]
the mr was merged
