### ISSUE TITLE
Haskell: handling of cabal flags for dependencies

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#85777]
**Describe the bug**
Building packages that hide broken dependencies with a Cabal-flag is hard, since overriding that Flag doesn't remove the build-time dependency.

**To Reproduce**
A simple testcase I found is `adler32` built with GHC and GHCJS. By default `adler32` uses the `zlib` library. This doesn't work on GHCJS, but after disabling the default `zlib` Cabal-flag, it should work, since the remaining code is pure Haskell and this is the way it works in Cabal.

Tested:
- [x] Build `adler32` with GHC (default flags)
- [x] Build `adler32` with GHC (disable zlib flag)
- [ ] Build `adler32` with GHCJS (default flags) - expected failure
- [ ] Build `adler32` with GHCJS (disable zlib flag) - unexpected failure
- [x] Build `adler32` with GHCJS (disable zlib flag) and manually override `librarySystemDepends =[];`

the complete override for this simple package is:
```
self: super: {
  # works on GHC, not GHCJS
  adler32-expected = with pkgs.haskell.lib; disableCabalFlag super.adler32 "zlib";
  # works on GHC and GHCJS
  adler32-current = with pkgs.haskell.lib; overrideCabal (disableCabalFlag super.adler32 "zlib") (old: { librarySystemDepends = [];});
};
```

relevant part of `<nixpkgs>/pkgs/development/haskell-modules/hackage-packages.nix` as reference:
```
  "adler32" = callPackage
    ({ mkDerivation, base, bytestring, hspec, zlib }:
     mkDerivation {
       pname = "adler32";
       version = "0.1.2.0";
       sha256 = "1936b05mx842wm8swz3g3jv6m9absa04islq4rwysicz72gkrd16";
       libraryHaskellDepends = [ base bytestring ];
       librarySystemDepends = [ zlib ];
       testHaskellDepends = [ base bytestring hspec ];
       description = "An implementation of Adler-32, supporting rolling checksum operation";
       license = stdenv.lib.licenses.bsd3;
     }) {inherit (pkgs) zlib;};
```

**Expected behavior**
Flags changing dependencies should be reflected in nix expression.

**Possible Solution**
Generate this form for every flag touching an option:
```
  {library,test}{System,Haskell}Depends = [ not touched by any flag ]
    ++ lib.optionals (flags.flag or false) [ depending on flag and disabled when flag unavailable ];
```
```
  "adler32" = callPackage
    ({ mkDerivation, base, bytestring, hspec, zlib, flags ? {} }:
     mkDerivation {
       pname = "adler32";
       version = "0.1.2.0";
       sha256 = "1936b05mx842wm8swz3g3jv6m9absa04islq4rwysicz72gkrd16";
       libraryHaskellDepends = [ base bytestring ];
       librarySystemDepends = []
         ++ lib.optionals (flags.zlib or false) [ zlib ];
       testHaskellDepends = [ base bytestring hspec ];
       description = "An implementation of Adler-32, supporting rolling checksum operation";
       license = stdenv.lib.licenses.bsd3;
     }) {inherit (pkgs) zlib;};
```

**Additional context**
Use-case: working on a SPA with `reflex-platform` and wondered why some packages failed on GHCJS even though they should be pure Haskell.

**Notify maintainers**
@peti 

**Metadata**
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.3, NixOS, 20.09.git.81a6a80436e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/repos/nixpkgs`
```

**Comment by cdepillabout** [comment]
I believe this is a well-known problem with https://github.com/NixOS/cabal2nix.  Please take a look on the issue tracker for cabal2nix for people talking about this.

Also, I don't know if you're aware of it, but https://github.com/input-output-hk/haskell.nix is usually able to generate builds that respect cabal flags more faithfully.
