### ISSUE TITLE
Derivation for ZenStates

### ISSUE THREAD

**Issue by savannidgerinel** [NixOS/nixpkgs#85789]
**Project description**

ZenStates is a Python application for manipulating the various AMD processor settings.

In particular, it is valuable on AMD-based Lenovo systems (such as my own) for disabling the C6 sleep state, which appears to have implementaiton defects. Disabling C6 appears to reduce the frequency at which buggy implementations fail to awake from sleep mode.

Since I have one of the affected systems and am now using ZenStates, I volunteer to write the derivation.

**Metadata**

* homepage URL: https://github.com/r4m0n/ZenStates-Linux
* source URL: https://github.com/r4m0n/ZenStates-Linux
* license: mit
* platforms: linux

**Comment by evils** [comment]
this is resolved now?

**Comment by savannidgerinel** [comment]
Ah. Yes. Thanks for the reminder.
