### ISSUE TITLE
systemd: ship dbus system services

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#85855]
**Describe the bug**
Systemd ships dbus system services (in `${pkgs.systemd}/share/dbus-1/system-services/*.service`), which are used for dbus system activation (see https://dbus.freedesktop.org/doc/system-activation.txt)

This includes some of the units shipped with systemd itself:
```
-r--r--r-- 1 root root 482 Jan  1  1970 org.freedesktop.hostname1.service
-r--r--r-- 1 root root 513 Jan  1  1970 org.freedesktop.import1.service
-r--r--r-- 1 root root 513 Jan  1  1970 org.freedesktop.locale1.service
-r--r--r-- 1 root root 511 Jan  1  1970 org.freedesktop.login1.service
-r--r--r-- 1 root root 515 Jan  1  1970 org.freedesktop.machine1.service
-r--r--r-- 1 root root 515 Jan  1  1970 org.freedesktop.network1.service
-r--r--r-- 1 root root 515 Jan  1  1970 org.freedesktop.resolve1.service
-r--r--r-- 1 root root 462 Jan  1  1970 org.freedesktop.systemd1.service
-r--r--r-- 1 root root 517 Jan  1  1970 org.freedesktop.timedate1.service
-r--r--r-- 1 root root 517 Jan  1  1970 org.freedesktop.timesync1.service
```

We currently don't have the proper tooling ready to make these available in NixOS.

Also, we shouldn't blindly enable all. For example, we might not want to enable `share/dbus-1/system-services/org.freedesktop.resolve1.service, if resolved is enabled.

Originally discovered in #85794, but it always hasn't worked, so it's not a regression.

**Notify maintainers**
@andir @NinjaTrappeur @Mic92 @arianvp

**Comment by doronbehar** [comment]
I wonder if that's why every program I have that uses dBus in some way or another, spits from time to time:

```
message bus security policy blocked the reply
```

**Comment by arianvp** [comment]
Can you tell me which programs those are?

**Comment by doronbehar** [comment]
Sure, `syhncthingtray` from `nixpkgs.syncthingtray`, prints:

```
"Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```

I'm using `startx` as my display manager and I'm using `awesome` as my desktop environment but I don't use `services.xserver.windowManager.awesome.enable`. Not sure if that matters..

**Comment by arianvp** [comment]
It does seem that `dbus` somehow picks up the systemd `dbus` configuration; though I do not fully understand _how_

```
[arian@t490s:/run/current-system/sw]$ ls /run/current-system/sw/share/dbus-1/system.d/
avahi-dbus.conf      dbus-wpa_supplicant.conf       org.freedesktop.ColorManager.conf    org.freedesktop.import1.conf   org.freedesktop.ModemManager1.conf   org.freedesktop.resolve1.conf   org.freedesktop.UDisks2.conf
bluetooth.conf       nm-dispatcher.conf             org.freedesktop.GeoClue2.Agent.conf  org.freedesktop.locale1.conf   org.freedesktop.network1.conf        org.freedesktop.systemd1.conf   org.freedesktop.UPower.conf
bluetooth-mesh.conf  org.freedesktop.Accounts.conf  org.freedesktop.GeoClue2.conf        org.freedesktop.login1.conf    org.freedesktop.NetworkManager.conf  org.freedesktop.timedate1.conf
cups.conf            org.freedesktop.bolt.conf      org.freedesktop.hostname1.conf       org.freedesktop.machine1.conf  org.freedesktop.portable1.conf       org.freedesktop.timesync1.conf

```

it's just missing the `dbus-org.freedesktop.resolve1.service` when `systemd-resolved.service` is enabled

**Comment by arianvp** [comment]
Ah apparently _all_ applications are loaded into dbus by default? Not sure how I feel about that ...

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/system/dbus.nix#L95

so the only reason why resolved wasn't working is because we didnt included `org-dbus.freedekstop.resolve1.service` unit file in `upstreamSystemdUnits` Easy fix!


Also; we set `LD_LIBRARY_PATH` on `dbus.service` to load nssModules. Why is this needed?

**Comment by flokli** [comment]
> Also; we set `LD_LIBRARY_PATH` on `dbus.service` to load nssModules. Why is this needed?

It seems we do, but we shouldn't do that. If we try to not restart `dbus.service`, changes in there don't get propagated. It should just use nscd like everything else.

@arianvp can you file a PR removing this?

**Comment by flokli** [comment]
reopened, as #87263 got reverted.

**Comment by doronbehar** [comment]
@arianvp I've found another example for:

> > message bus security policy blocked the reply
>
> Can you tell me which programs those are?

`nixpkgs.picard` prints:

```
"Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```

**Comment by symphorien** [comment]
Another symptom is:
```
$  systemd-run --user --pipe --wait env
Failed to start transient service unit: The name org.freedesktop.systemd1 was not provided by any .service files
```

**Comment by arianvp** [comment]
@symphorien  I'm not sure if that is a symptom of what I am solving here. I recall @grahamc recently running into the same issue and I think it's a problem with how we set up user environment in certain desktop managers.

**Comment by symphorien** [comment]
Should I open a distinct issue then?
