### ISSUE TITLE
starship.rs does not build on 20.03

### ISSUE THREAD

**Issue by Elyhaka** [NixOS/nixpkgs#85927]
**Describe the bug**

On current version `20.03` it seems that we have an hash mismatch:

```
hash mismatch in fixed-output derivation '/nix/store/w7m5nwisgnvn1mh8993my87qq81m70bm-starship-0.40.1-vendor':
  wanted: sha256:1jrlzihcq543z6hb1gq8zq6hqvgralzsknj3xnb6gia1n49b3zxz
  got:    sha256:19fblmbk7nszaxkig7db7jl6zxpg0xg6hpv1zkhbam8wixm5fzkk
cannot build derivation '/nix/store/ay641786w2q5sqzgsrj5fgqrp52lrkzi-starship-0.40.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nb1qhhk0dinsmdpwqs29cyw2l0p21mhr-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ss2anx0ppbbcg6qpzg2ark6b7hsl5kf6-nixos-system-ely-lenovo-20.03.1445.95b9c99f6d0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ss2anx0ppbbcg6qpzg2ark6b7hsl5kf6-nixos-system-ely-lenovo-20.03.1445.95b9c99f6d0.drv' failed
```

I had the same issue while trying to package the `sentry-cli` for a NixOS server I'm running, the calculated hash differs between my 2 computers.

I thought I had made a mistake, but now I believe they might be an issue with the way the hash is calculated with rust vendored dependencies ?

**To Reproduce**
1. Install starship

**Expected behavior**
Should install

**Comment by bbigras** [comment]
Doesn't 20.03 has starship 0.35.1?

![image](https://user-images.githubusercontent.com/24027/81339250-d5c42480-907b-11ea-9a2f-512f613a00cf.png)
https://repology.org/project/starship/versions

**Comment by Elyhaka** [comment]
You're right, I wasn't on 20.03 I guess, I might have missed something. Closing this issue (cannot reproduce it on my side anymore).
