### ISSUE TITLE
[20.03] installing tensorflow-gpu fails

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#85931]
**Describe the bug**

Tried to install `tensorflowWithCuda` from the `nixos-20.03` stable channel. Ended up with the following:

```
hash mismatch in fixed-output derivation '/nix/store/cpqk2vhw0glf4vrlj2b0828aa4barjfy-tensorflow-gpu-1.15.2-deps':
  wanted: sha256:1qygfcvvn9vysap9nk6xccxi9mgmzyxiywz6k456f811l1v70p2c
  got:    sha256:1hc0hd48znzwhwcnf23kl2i82hnpl12c7vkyjx7ji7zk9ldmpxsk
cannot build derivation '/nix/store/rbnw39v7fc28dqxk8in3awz4ii0y54i2-tensorflow-gpu-1.15.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bbnw7k1db2cj80pvni0n2mllpb2kk4lq-python3.7-tensorflow-gpu-1.15.2.drv': 1 dependencies couldn't be built
```

**Notify maintainers**

@jyp @abbradar 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.97, NixOS, 20.03pre210300.05626cc86b8 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03.1445.95b9c99f6d0"`
 - channels(stick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by thefenriswolf** [comment]
@prusnak I know this is not a fix, but [tensorman](https://github.com/pop-os/tensorman) relies on docker and it's already in the nixpkgs tree.

**Comment by prusnak** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/86795
