### ISSUE TITLE
Hydra fails to build due to broken darcs

### ISSUE THREAD

**Issue by MarceColl** [NixOS/nixpkgs#85936]
**Describe the bug**
I am trying to deploy Hydra to my server using nixops, but the hydra derivation is failing because `darcs-2.14.2` is marked as broken.

**To Reproduce**
`$ nix-env -i hydra`

**Expected behavior**
Hydra derivation should pass

**Additional context**
```
$ nix-env -i hydra
installing 'hydra-2020-02-06'
error: Package ‘darcs-2.14.2’ in /nix/store/kp80b1nh6irma99x44ysj4ggb7djjkzd-nixpkgs-20.09pre217398.e808d11c431/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:64363 is marked as broken, refusing to evaluate.
```
**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-1079-oem, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(mcoll): `"nixpkgs-20.09pre217398.e808d11c431"`
 - nixpkgs: `/home/mcoll/.nix-defexpr/channels/nixpkgs`

**Comment by sorki** [comment]
I think that Darcs is fixed in master for GHC 8.8.3 but not yet released - you can either use older GHC for it (GHC 8.6.5 should work) or disable darcs as a dependency for hydra.

**Comment by cdepillabout** [comment]
Yup, looks like darcs is fixed in the `master` branch.  You may have to wait a few days until it is available on the unstable channel.

**Comment by MarceColl** [comment]
Okay, thanks everyone!
