### ISSUE TITLE
libarchive does not support zstd

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#85957]
While experimenting with zstd I noticed that libarchive is not compiled with zstd support.

I tried to simply add the dependency to libarchive buildInputs, but I noticed the circular dependency.

`libarchive -> zstd -> cmake -> libarchive`

It seems the easiest way is to compile zstd without cmake (it supports compilation via plain make or meson). But there might be other options.

What do you think? @jcumming @orivej

**Comment by worldofpeace** [comment]
Hehe, I will always encourage mesonbuild usage.

**Comment by prusnak** [comment]
I just noticed this will be fixed https://github.com/NixOS/nixpkgs/pull/78910
