### ISSUE TITLE
gitlab error when open the page of 'background jobs' and 'logs'

### ISSUE THREAD

**Issue by shen390s** [NixOS/nixpkgs#8598]
Check background jobs get following information:
500
We're sorry, but something went wrong.

Please contact your GitLab administrator if this problem persists.

Check logs will get:
500
We're sorry, but something went wrong.

Please contact your GitLab administrator if this problem persists.

**Comment by shen390s** [comment]
Apply following patch to get it correctly:
diff --git a/nixos/modules/services/misc/gitlab.nix b/nixos/modules/services/misc/gitlab.nix
index 4505c5c..bdf5888 100644
--- a/nixos/modules/services/misc/gitlab.nix
+++ b/nixos/modules/services/misc/gitlab.nix
@@ -50,7 +50,7 @@ let
           --set GEM_HOME '${gemHome}'\
           --set UNICORN_PATH "${cfg.stateDir}/"\
           --set GITLAB_PATH "${pkgs.gitlab}/share/gitlab/"\
-          --set GITLAB_APPLICATION_LOG_PATH "${cfg.stateDir}/log/application.log"\
+          --set GITLAB_APPLICATION_LOG_PATH "${cfg.stateDir}/log/"\
           --set GITLAB_SATELLITES_PATH "${cfg.stateDir}/satellites"\
           --set GITLAB_SHELL_PATH "${pkgs.gitlab-shell}"\
           --set GITLAB_REPOSITORIES_PATH "${cfg.stateDir}/repositories"\
@@ -178,7 +178,7 @@ in {
       environment.GEM_HOME = gemHome;
       environment.UNICORN_PATH = "${cfg.stateDir}/";
       environment.GITLAB_PATH = "${pkgs.gitlab}/share/gitlab/";
-      environment.GITLAB_APPLICATION_LOG_PATH = "${cfg.stateDir}/log/application.log";
+      environment.GITLAB_APPLICATION_LOG_PATH = "${cfg.stateDir}/log/";
       environment.GITLAB_SATELLITES_PATH = "${cfg.stateDir}/satellites";
       environment.GITLAB_SHELL_PATH = "${pkgs.gitlab-shell}";
       environment.GITLAB_REPOSITORIES_PATH = "${cfg.stateDir}/repositories";
@@ -198,6 +198,8 @@ in {
         ruby
         openssh
         nodejs
+       procps
+       coreutils
       ];
       serviceConfig = {
         Type = "simple";
@@ -216,7 +218,7 @@ in {
       environment.GEM_HOME = gemHome;
       environment.UNICORN_PATH = "${cfg.stateDir}/";
       environment.GITLAB_PATH = "${pkgs.gitlab}/share/gitlab/";
-      environment.GITLAB_APPLICATION_LOG_PATH = "${cfg.stateDir}/log/application.log";
+      environment.GITLAB_APPLICATION_LOG_PATH = "${cfg.stateDir}/log/";
       environment.GITLAB_SATELLITES_PATH = "${cfg.stateDir}/satellites";
       environment.GITLAB_SHELL_PATH = "${pkgs.gitlab-shell}";
       environment.GITLAB_REPOSITORIES_PATH = "${cfg.stateDir}/repositories";
@@ -234,6 +236,8 @@ in {
         ruby
         openssh
         nodejs
+        procps
+        coreutils
       ];
       preStart = ''
         # TODO: use env vars
diff --git a/pkgs/applications/version-management/gitlab/remove-hardcoded-locations.patch b/pkgs/applications/version-management/gitlab/remove-hardcoded-locations.patch
index f5532bb..e1c17ab 100644
--- a/pkgs/applications/version-management/gitlab/remove-hardcoded-locations.patch
+++ b/pkgs/applications/version-management/gitlab/remove-hardcoded-locations.patch
@@ -96,14 +96,31 @@ index e7a8d08..834ecaf 100644
      # When you run tests we clone and setup gitlab-shell
 diff --git a/lib/gitlab/app_logger.rb b/lib/gitlab/app_logger.rb
 index 8e4717b..abfe2e4 100644
---- a/lib/gitlab/app_logger.rb
-+++ b/lib/gitlab/app_logger.rb
-@@ -1,7 +1,7 @@
- module Gitlab
-   class AppLogger < Gitlab::Logger
-     def self.file_name
--      'application.log'
-+      ENV["GITLAB_APPLICATION_LOG_PATH"]
+--- a/lib/gitlab/logger.rb
++++ b/lib/gitlab/logger.rb
+@@ -8,21 +8,22 @@
+       build.info(message)
      end
  
-     def format_message(severity, timestamp, progname, msg)
+     def self.read_latest
+-      path = Rails.root.join("log", file_name)
++      path = File.join(ENV['GITLAB_APPLICATION_LOG_PATH'], file_name)
+       self.build unless File.exist?(path)
+       tail_output, _ = Gitlab::Popen.popen(%W(tail -n 2000 #{path}))
+       tail_output.split("\n")
+     end
+ 
+     def self.read_latest_for(filename)
+-      path = Rails.root.join("log", filename)
++      path = File.join(ENV['GITLAB_APPLICATION_LOG_PATH'], filename)
+       tail_output, _ = Gitlab::Popen.popen(%W(tail -n 2000 #{path}))
+       tail_output.split("\n")
+     end
+ 
+     def self.build
+-      new(Rails.root.join("log", file_name))
++      path = File.join(ENV['GITLAB_APPLICATION_LOG_PATH'], file_name)
++      new(path)
+     end
+   end
+ end

**Comment by cillianderoiste** [comment]
Hi @shen390s is this still an issue?
