### ISSUE TITLE
xserver.displayManager does not correctly deprecate xserver.desktopManager and xserver.windowManager

### ISSUE THREAD

**Issue by inferencerules** [NixOS/nixpkgs#86009]
**Describe the bug**
Per the [20.03 release notes](https://nixos.org/nixos/manual/release-notes.html#sec-release-20.03), `services.xserver.desktopManager.default` and `services.xserver.windowManager.default` were replaced by `services.xserver.displayManager.defaultSession`, which must be a string formatted like `"${desktopManager}+${displayManager}"`.

Using xmonad with no desktop manager, this string should be `"none+xmonad"` (see [this test](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/xmonad.nix), but `nixos-rebuild` throws an error saying the setting is not a valid session name, preventing upgrade from 19.09 to 20.03. When `services.xserver.windowManager.xmonad.enable = true` is set at the same time as the new services.xserver.displayManager.defaultSession setting, `nixos-rebuild` does not throw an error and proceeds with the build.

Furthermore, the error message returned by `nixos-rebuild` contains an empty list of suggested values for this setting.

**To Reproduce**
1. Replace services.xserver.desktopManager.default and services.xserver.windowManager.default declarations with services.xserver.displayManager.defaultSession, containing the string "none+xmonad".
2. Execute a `nixos-rebuild`.

**Expected behavior**
`nixos-rebuild switch` should begin building the new configuration.

**Screenshots**
> unpacking channels...
> building Nix...
> building the system configuration...
> trace: Default graphical session, 'none+xmonad', not found.
> Valid names for 'services.xserver.displayManager.defaultSession' are:
>
>
>error: The option value 'services.xserver.displayManager.defaultSession' in '/etc/nixos/configuration.nix' is not of type 'session name'.
>(use '--show-trace' to show detailed location information)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.32, NixOS, 19.09.2407.b67bc34d4e3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.03, home-manager-20.03, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
cc @jtojnar @hedning

**Comment by jtojnar** [comment]
Maybe we could add empty check and suggest enabling some DM. But I wonder how did it work before without `services.xserver.windowManager.xmonad.enable = true`.

**Comment by inferencerules** [comment]
After some discussion, I now understand that the old `default` options only set the initial choice of session in the greeter/display manager, and has no impact on which desktop/window manager is actually installed for use.

This was confusing as many people have, for example, `services.xserver.desktopManager.xfce.enable = true` and 
`services.xserver.desktopManager.default = "xfce"` set, where the latter is the only `desktopManager` option set. Here the `enable` option is or should be unnecessary as the display manager only has one option for passing control anyway. Perhaps this is just an artifact of terse documentation: the `desktopManager.default` option has "default desktop manager loaded if none have been chosen", and `windowManager.default` has "default window manager loaded if none have been chosen" as descriptions, which I (incorrectly) read as another way to enable the `windowManager` option without explicitly including it.

An empty check as suggested above would be great. Closing this.
