### ISSUE TITLE
Problem with grub after nixos-install

### ISSUE THREAD

**Issue by odi** [NixOS/nixpkgs#8600]
I have a problem with installing NixOS on my Thinkpad X1 Carbon. After generating my nixos-config file with 

$ nixos-generate-config --root /mnt

and changing the boot.loader to grub. I get following error after `nixos-install`:  

grub-install: error: /nix/store/../lib/grub/x86_64-efi/modinfo.sh doesn't exist. Please specify --target or --directory
/nix/store/..-install-grub.pl: installation of GRUB on /dev/sda failed

My `nixos-version` is: 14.12.496.5f7d374 (Caterpillar)

My config could be found here: https://gist.github.com/odi/fe00ece89b9f79c85f22

**Comment by odi** [comment]
Comment my own issue.

Tested with version 15.06 (Dingo) works fine for me. I am not sure what the problem was.

**Comment by chris-martin** [comment]
I am currently having this problem with NixOD 14.12.

**Comment by chris-martin** [comment]
Resolved by switching to release [15.09.336.83cc494](https://nixos.org/releases/nixos/15.09/nixos-15.09.336.83cc494/).

**Comment by jamesthompson** [comment]
Does anybody have this version kicking around still, @chris-martin perhaps? I'd need the x64-64bit iso... More recent versions hang my install screen immediately after BIOS->usb boot. I see the blue nixos install screen, but then it disappears...

**Comment by chris-martin** [comment]
Sorry, I'm no help here.
