### ISSUE TITLE
Specifying a trailing-slash-less path with nginx alias feature results in path traversal error

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#86025]
**Describe the bug**

~~When specifying a path literal (ie. something that will be stored in the Nix store) for the `services.nginx.virtualHosts.<name>.locations.<name>.alias` option, the following kind of error will be produced on build:~~

Original issue description was wrong, see comments below.

```
==================== Results ===================

>> Problem: [alias_traversal] Path traversal via misconfigured alias.
Description: Using alias in a prefixed location that doesn't ends with directory separator could lead to path traversal vulnerability.
Additional info: https://github.com/yandex/gixy/blob/master/docs/en/plugins/aliastraversal.md
Pseudo config:

server {
        server_name haless.cryto.net;

        location /knex-mirror {
                alias /nix/store/8xzzvw74q5sp2nv347a138gjg3j4rh46-knex-mirror;
        }

        location /shadow {
                alias /nix/store/m00i6nkgnmf454h98dyxpmrvn8cvqsj6-shadow-generator;
        }
}

==================== Summary ===================
Total issues:
    Unspecified: 0
    Low: 0
    Medium: 2
    High: 0
```

**To Reproduce**

Have a config that looks something like this:

```nix
{
	services.nginx = {
		enable = true;
		virtualHosts = {
			"haless.cryto.net" ={
				locations."/shadow" = {
					alias = ./sources/shadow-generator;
				};
				locations."/knex-mirror" = {
					alias = ./sources/knex-mirror;
				};
			};
		};
	};
}
```

**Expected behavior**

Configuration should work, and automatically append a `/` if needed.

**Screenshots**

N/A

**Additional context**

N/A

**Notify maintainers**

@thoughtpolice @raskin @fpletz @globin

**Metadata**
N/A, this happens in a Morph deployment for Linux x86_64. Module and package originate from current 20.03 (95b9c99f6d09).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nginx
```

**Comment by joepie91** [comment]
Hold on, I think I misinterpreted the error, and it will probably fail again later during the current rebuild. Will update this issue when I know more.

**Comment by joepie91** [comment]
Right, so a correction: it was actually complaining about the URL paths themselves, ie. `/shadow` and `/knex-mirror`.

If we consider this invalid, perhaps the module should just auto-append `/` here? (Rather than for the `alias` option, like I suggested originally)

**Comment by lheckemann** [comment]
Paths without trailing slashes can be useful, they just shouldn't be used with `alias` — hence the warning. And I think you meant @7c6f434c, not `@raskin` :)

**Comment by joepie91** [comment]
> Paths without trailing slashes can be useful, they just shouldn't be used with `alias`

Hm, good point, I guess that it might introduce too much unpredictable complexity to auto-append slashes only if `alias` is in use. Suppose this can be closed then.

> And I think you meant @7c6f434c, not `@raskin` :)

I copied the maintainer list from the nixpkgs expression, and prefixed each name with `@`. Isn't there a rule that maintainer identifiers in nixpkgs should match their GitHub usernames?

**Comment by lheckemann** [comment]
```
$ nix eval nixpkgs.lib.maintainers.raskin.github
"7c6f434c"
```
:)

I'll go ahead and close it then.

**Comment by pdg137** [comment]
For people who come here searching for this error, if you want to alias a single file, you can do something like this:

```conf
    location = /assets/whatever.css {
        root /;
        try_files ${./myfile.css} ${./myfile.css};
    }
```

[source](https://serverfault.com/questions/817607/most-efficient-way-to-serve-a-single-file-for-entire-server-block)
