### ISSUE TITLE
git man page references files that do not exist

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#86022]
**Describe the bug**
I see the following near the end of the output of `man 1 git`:

    NOTES
            1. Git User’s Manual
               file:///nix/store/87q13rjbf4v6n8qc3wh8ric207w33zxp-git-2.26.1/share/doc/git/user-manual.html

            2. Trace2 documentation
               file:///nix/store/87q13rjbf4v6n8qc3wh8ric207w33zxp-git-2.26.1/share/doc/git/technical/api-trace2.html

            3. Git concepts chapter of the user-manual
               file:///nix/store/87q13rjbf4v6n8qc3wh8ric207w33zxp-git-2.26.1/share/doc/git/user-manual.html#git-concepts

            4. howto
               file:///nix/store/87q13rjbf4v6n8qc3wh8ric207w33zxp-git-2.26.1/share/doc/git/howto-index.html

            5. Git API documentation
               file:///nix/store/87q13rjbf4v6n8qc3wh8ric207w33zxp-git-2.26.1/share/doc/git/technical/api-index.html

            6. git@vger.kernel.org
               mailto:git@vger.kernel.org

            7. git-security@googlegroups.com
               mailto:git-security@googlegroups.com

But note of the files referenced exist. The .../share/doc/git directory only contains `git-subtree.html`.

**To Reproduce**

1. In a nixpkgs checkout (verified at 6a627c41 on master branch) run `nix-build -o git -A git`. (I also observe the problem with `gitFull`.)
2. `man man -M git/share/man 1 git`

(Alternatively, just `man git`, but these instructions should help reproduce if it turns out the behaviour is different at different revisions.)

**Expected behavior**
Any files referenced should exist. My own preference would be for the documentation to be installed at those local paths as promised, but failing that, it would be better to point to a website.

**Notify maintainers**
@globin @wmertens 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

     - system: `"x86_64-linux"`
     - host os: `Linux 5.4.33, NixOS, 20.03.1445.95b9c99f6d0 (Markhor)`
     - multi-user?: `yes`
     - sandbox: `yes`
     - version: `nix-env (Nix) 2.3.4`
     - channels(james): `""`
     - channels(root): `"nixos-20.03.1445.95b9c99f6d0"`
     - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by wmertens** [comment]
🤔 well this is odd - since the store path exists, it means that those files don't make it into the installed package, either because they were never added or because they were removed. The former seems more likely.
Either way I don't have time to look into this now :(

**Comment by doronbehar** [comment]
I think that's because we don't `make install-html`:

https://github.com/git/git/blob/d61d20c9b413225793f8a0b491bbbec61c184e26/Documentation/Makefile#L267-L268

Here:

https://github.com/NixOS/nixpkgs/blob/eeb4e522b5d25408faab02c79a34ead8228531c9/pkgs/applications/version-management/git-and-tools/git/default.nix#L236-L238

Though it's a bit unpleasing that these files are referenced and we don't ship them, I'm not up to `make install-html` as that increases the closure size for not good enough reason IMO. Perhaps we should `sed` these links to upstream's http links? Or perhaps add another `withHtmlDocs` flag?

**Comment by primeos** [comment]
> Perhaps we should sed these links to upstream's http links?

I like this idea :)
I think we could e.g. set `MAN_BASE_URL` in `Documentation/Makefile` to `https://git-scm.com/docs/` (maybe there's even a versioned URL which would be better) to get links like this one https://git-scm.com/docs/user-manual.html#git-concepts (didn't test this approach yet, but I think it should work).

And if there's demand for it we could additionally add the `withHtmlDocs` flag later.

**Comment by falsifian** [comment]
I'm not the maintainer, but from the peanut gallery: wouldn't replacing the file: urls with http: urls increase the complexity of this expression, increasing the maintenance burden in nixpkgs?

If I remember right, there's already an option for git in nixpkgs to disable building the documentation altogether. Wouldn't it be simpler to just say you either get all the documentation (man pages + html) or none? If the upstream man pages have the (relative) local html paths baked-in, then it seems to me upstream is making the assumption that they come as a package deal, and I'm not sure it's good to break upstream assumptions without good reason.

To me, at least, it also conceptually makes sense to include the offline html documentation for people who've requested the offline man documentation, though admittedly my expectation of having a man page is somewhat stronger than my expectation of being able to browse the html documentation offline.

**Comment by doronbehar** [comment]
Maybe a split output will be more appropriate... Debian splits it:

https://packages.debian.org/sid/all/git-doc/filelist

**Comment by falsifian** [comment]
@doronbehar Interesting. I just confirmed that on my Debian system, `/usr/share/doc/git/html/user-manual.html` is referenced by the man page but doesn't exist (unless I install `git-doc`). If that's good enough for Debian, maybe I'm overreacting.

**Comment by primeos** [comment]
I just opened a PR for a possible solution that follows the approach from Debian: #86848
I've also determined the output sizes so that we have some numbers for this discussion.

**Comment by primeos** [comment]
I guess we can close this issue now since #86848 is merged. It isn't a perfect solution but it should be good enough.
