### ISSUE TITLE
two single quoted string escaping not comprehensive

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#86021]
There are strings that are impossible to write with the current escaping rules of two single quoted strings. For instance, how to generate the following string: `'${foo}`. You'd need to escape the dollar with two single quotes like `'''${foo}`, but because there already was one single quote before the dollar sign, the escaping breaks. As far as I understand, if there are strings that cannot be written, the escaping rules are broken. But probably I'm missing something.

**Comment by primeos** [comment]
> But probably I'm missing something.

IIRC this is indeed problematic and AFAIK a known problem.

There are of course dirty hacks to circumvent this, e.g.:
```nix
let foo = "'" + ''''${foo}'';
in ''text ${foo} text''
```

And it should be possible to create a nicer library function for such (luckily rare) use-cases, but I don't think there is one yet.

**Comment by ryantm** [comment]
Thanks for the report, but this sounds more like a nix issue than a nixpkgs issue. I'm closing this, and feel free to report at https://github.com/NixOS/nix
