### ISSUE TITLE
Scanning with hplip and hplip commands seem broken in nixos-unstable

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#86048]
**Describe the bug**

In nixos-unstable, hplip seems to be quite broken.

**To Reproduce**

1. Install `simple-scan` and `hplipWithPlugin`
2. Enable hardware.sane and services.printing with hplip/hplipWithPlugins drivers.
3. Switch to the new configuration
4. Start "Document scanner": the scanner (from my hp photosmart premium) is not recognized

```
$ hp-diagnose_plugin 
[...]
ModuleNotFoundError: No module named 'gi'

$ hp-uiscan 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**Expected behavior**

My HP Photosmart Premium should be detected by simple-scan.

**Notify maintainers**

/cc @ttuegel 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.09.git.87aea649013 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(cassou): `""`
 - channels(root): `"nixos-20.09pre222244.22a3bf9fb9e"`
 - nixpkgs: `/home/cassou/Documents/projects/nixos/system`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
Yea I encountered that in the past.... These tools need to be wrapped in order to work with `wrapQtAppsHook` and/or `wrapGAppsHook`. But, wrapping them would increase their closure size while not everyone need or use these command line versions of them. Perhaps the best solution would be to add a `withGui` build flag that will add these wrappers.

**Comment by flokli** [comment]
I implemented the wrapping for `hplip` in https://github.com/NixOS/nixpkgs/pull/90609.

**Comment by DamienCassou** [comment]
Thank you for your work @flokli. I'm closing that now and will reopen if I have more issues.
