### ISSUE TITLE
[20.03] nixos-rebuild fails to switch system configuration

### ISSUE THREAD

**Issue by dadada** [NixOS/nixpkgs#86047]
During upgrade from 19.09 `nixos-rebuild switch` tries to call `sudo` as root and fails with

```
...
building the system configuration...
sudo: Account expired or PAM config lacks an "account" section for sudo, contact your system administrator
```

**To Reproduce**

As user in group `wheel` do 

1. Install NixOS version 19.09 with `nixos-install --no-root-passwd` 
1. `sudo -i nixos-channel --add https://nixos.org/channels/nixos-20.03 nixos` followed by
2.  `sudo -i nixos-rebuild switch --upgrade`

**Expected behavior**
`nixos-rebuild` re-execs from the new derivation, which procedes without doing an additional `sudo`, since `$SUDO_USER` should be set. Switching to the new system succeeds.

**Additional context**

```
$ sudo passwd -S root
root NP 01/01/1970 -1 -1 -1 -1
```

Contents of `/etc/sudoers`

```
# Don't edit this file. Set the NixOS options ‘security.sudo.configFile’
# or ‘security.sudo.extraRules’ instead.

# Keep SSH_AUTH_SOCK so that pam_ssh_agent_auth.so can do its magic.
Defaults env_keep+=SSH_AUTH_SOCK

# "root" is allowed to do anything.
root        ALL=(ALL:ALL) SETENV: ALL

# extraRules
%wheel  ALL=(ALL:ALL)   SETENV: ALL


# Keep terminfo database for root and %wheel.
Defaults:root,%wheel env_keep+=TERMINFO_DIRS
Defaults:root,%wheel env_keep+=TERMINFO
```

Contents of /etc/pam.d/sudo

```
# Account management.
account required pam_unix.so

# Authentication management.
auth sufficient pam_unix.so  likeauth try_first_pass
auth required pam_deny.so

# Password management.
password sufficient pam_unix.so nullok sha512

# Session management.
session required pam_env.so envfile=/nix/store/fg7qwjqb2j4xxap23zir7yy01mr04mdf-pam-environment

session required pam_unix.so
```

`sudo -i sudo echo hello` as the user in group wheel fails with the same error. Upgrading from one version of 19.09 to another works just fine and does not produce the error.

**Notify maintainers**

@edolstra @bjornfor

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.116, NixOS, 19.09.2437.c4799f080ba (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2437.c4799f080ba"`
 - channels(dadada): `"home-manager-19.09, nixpkgs-unstable-20.09pre221814.10100a97c89"`
 - channels(iserv): `"home-manager-19.09, nixpkgs-unstable-20.09pre217039.13e7a3e1127"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Error from sudo
```
root : Account expired or PAM config lacks an "account" section for sudo, contact your system administrator ; TTY=pts/1 ; PWD=/root ; USER=root ; COMMAND=/tmp/nixos-rebuild.ZiILsN/nix/bin/nix-env -p /nix/var/nix/profiles/system --set /nix/store/5hkd8ai4zfmzsghgzn1gyzg31a6g3g0a-n
```

PAM says
```
pam_unix(sudo:account): account root has expired (account expired)
```

See also 263a81e285faacb968d11f58e0dba2bb75a92a45 that introduced `sudo` into nixos-rebuild (not contained in 19.09)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixos-system
```

**Comment by bjornfor** [comment]
I think this might come from https://github.com/NixOS/nixpkgs/commit/ab10bac1b177832b5e6b883ba95bf35f87229267#diff-3a927177ca4e2581b1a7269f33805f74R105. The `if [ -n "$SUDO_USER" ]; then` bit.

**Comment by bjornfor** [comment]
CC @zimbatm.

**Comment by dadada** [comment]
> The `if [ -n "$SUDO_USER" ]; then` bit.

My guess would be that `$SUDO_USER` is not passed to the new version of nixos-rebuild or the env is lost somehow.

**Comment by dadada** [comment]
Root account was expired. In `/etc/shadow`:

```
root:!:::::::
```

Fixed it for me. Unsure if the previous value was due to `nix-install --no-root-pwd` or if I messed something up myself. 

Anyway, `nixos-rebuild` should not require root to be able to `sudo`. Probably irrelevant though.
