### ISSUE TITLE
Terminator is not rendering URLs with links

### ISSUE THREAD

**Issue by dsyer** [NixOS/nixpkgs#86049]
Terminator comes with 3 URL handlers. If you open up Preferences in the nix version of Terminator (installed via nix-env) it looks identical to a "normal" Ubuntu one, and the plugins show as "installed". But when a URL is on the console it is not rendered specially, and the right-click menu does not pick up the "Open Link" item, like it should.

UPDATE: I just tried it in a "Live CD" VM with nixos 20.03 and that works as expected. So it's only when I install terminator in my Ubuntu host (20.04) that the URL links are broken.

**Comment by veprbl** [comment]
cc @bjornfor

**Comment by dsyer** [comment]
Another observation: if you have text that wraps over a line ending and you select it in terminator and paste, the line endings from the wraps are inserted, which corrupts the text and makes it kind of unusable. Again, this isn't the case in nixos, but it is in Ubuntu.

**Comment by SFrijters** [comment]
I have updated terminator to the new 1.92 version released by a new group of maintainers and the PR just got accepted - could you check if that fixes your issue?

**Comment by dsyer** [comment]
Great! Nix newbie here. How can I install it without upgrading my whole system to "unstable"?

**Comment by SFrijters** [comment]
You could try
```
nix-env -f https://github.com/NixOS/nixpkgs/archive/8855c3a1c728a16b4a9e5e4071d7fc63ef63973a.tar.gz -iA terminator
```
The commit hash is the hash for the merge commit for the PR.

**Comment by dsyer** [comment]
Awesome. So both problems go away if I use that version. What do I need to watch out for to know when I can pick it up from "stable"?

**Comment by SFrijters** [comment]
As far as I know the stable channel is on a fixed 6-month (approx.) release cycle, so I would expect this change to go into nixos-20.09. See https://nixos.wiki/wiki/Nix_channels. But it should get from master into an unstable channel a lot sooner. Maybe https://discourse.nixos.org/t/nixpkgs-flow-from-master-to-channel/4727 explains things better?

**Comment by veprbl** [comment]
@SFrijters You can open a "backport" PR against release-20.03 branch. You will need to use `cherry-pick -x 8855c3a1c728a16b4a9e5e4071d7fc63ef63973a`.

**Comment by SFrijters** [comment]
Thanks, backport PR opened as #86490.

**Comment by SFrijters** [comment]
@dsyer Looks like the backport is in, so it should be in stable soonish I guess.
