### ISSUE TITLE
Duplicates in androidenv generated/addons.nix

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nixpkgs#86043]
**Describe the bug**
There are duplicate entries in `pkgs/development/mobile/androidenv/generated/addons.nix` which cause errors.

**Links**
There are three sections:
https://github.com/NixOS/nixpkgs/blob/7c399a4ee080f33cc500a3fda33af6fccfd617bd/pkgs/development/mobile/androidenv/generated/addons.nix#L659-L720
and
https://github.com/NixOS/nixpkgs/blob/7c399a4ee080f33cc500a3fda33af6fccfd617bd/pkgs/development/mobile/androidenv/generated/addons.nix#L723-L752
and
https://github.com/NixOS/nixpkgs/blob/7c399a4ee080f33cc500a3fda33af6fccfd617bd/pkgs/development/mobile/androidenv/generated/addons.nix#L883-L944

**Additional context**
I had to fix this in my own fork with https://github.com/status-im/nixpkgs/commit/9897bd27ddf192960e8f3ca2479835e408507318.

I assume there needs to be a proper fix that will prevent this in the future in either of these files:
* [`pkgs/development/mobile/androidenv/generate.sh`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/mobile/androidenv/generate.sh)
* [`pkgs/development/mobile/androidenv/convertaddons.xsl`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/mobile/androidenv/convertaddons.xsl)

**Notify maintainers**
@OmnipotentEntity @lucafavatella @svanderburg

**Comment by numinit** [comment]
I have some changes I'd like to merge into androidenv that will end up fixing this.

**Comment by numinit** [comment]
Update on this: haven't forgotten, just moving at the speed of open source...

**Comment by numinit** [comment]
@jakubgs Check out #89775. I'm not completely satisfied with the solution but it's better than nothing.

**Comment by numinit** [comment]
Should be closed by #89775.

**Comment by jakubgs** [comment]
Yep, thanks @numinit, great work!
