### ISSUE TITLE
Qt applications cannot find qt translations

### ISSUE THREAD

**Issue by sikmir** [NixOS/nixpkgs#86054]
**Describe the bug**
If qt application uses `QLibraryInfo::location(QLibraryInfo::TranslationsPath)` (see [docs](https://doc.qt.io/qt-5/qlibraryinfo.html)) to get location of qt translations, it will get `/nix/store/n2zczzqp7dwc2kmf3s82wymw08asdhi6-qtbase-5.12.7/translations`, while qt translations actually live in separate derivation `/nix/store/725gncv0pvf9izasn55w5mcv8f6bcx3n-qttranslations-5.12.7/translations`.

**Notify maintainers**

@ttuegel

**Comment by worldofpeace** [comment]
This might be an issue triggered by wrapping.

**Comment by ttuegel** [comment]
This is caused by our multi-derivation Qt build, that is by building each module as a separate package. However, I suspect it's even worse: that applications may not find _their own_ translations, which won't be at the (read-only) `QLibraryInfo::TranslationPath`.

**Comment by sikmir** [comment]
> However, I suspect it's even worse: that applications may not find _their own_ translations, which won't be at the (read-only) `QLibraryInfo::TranslationPath`.

Applications find their own translations by:
```
QStandardPaths::locate(QStandardPaths::AppDataLocation, "translations", QStandardPaths::LocateDirectory)
```
And that's OK.

**Comment by sikmir** [comment]
Problem still exists.

**Comment by sikmir** [comment]
Up

**Comment by sikmir** [comment]
Up.

**Comment by K900** [comment]
Fixed.
