### ISSUE TITLE
pkg-config needs prefixes and wrappper like cc and binutils

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#86077]
Pkg-config needs a wrapper, so we we have `${target-prefix}` pkg-config and `BUILD_PKG_CONFIG_PATH` environment variables.

CC @matthewbauer

**Comment by danielfullmer** [comment]
Just adding a note here to remove this workaround if support for prefixed `pkg-config` is merged into `nixpkgs`:
https://github.com/NixOS/nixpkgs/blob/92d9d07c61d06c044af0261ab1741340151e4d3b/pkgs/development/libraries/ffmpeg/generic.nix#L166

**Comment by flokli** [comment]
This is solved by https://github.com/NixOS/nixpkgs/pull/87705.
