### ISSUE TITLE
nixos/acme: document DNS-01 challenge

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#86114]
https://github.com/NixOS/nixpkgs/pull/77578 introduces DNS-01 challenge support, yet `nixos/modules/security/acme.xml` states only webroot verification is supported.

We should update this file, and add a section explaining how to configure DNS-01 challenges.

cc @m1cr0man

**Comment by m1cr0man** [comment]
I'll try and do that tonight

**Comment by m1cr0man** [comment]
I ended up rewriting the whole doc for acme, it was badly outdated and not particularly helpful.

Still need to build an example for DNS-01, will try do that tomorrow.
