### ISSUE TITLE
open-zwave: built version is too specific

### ISSUE THREAD

**Issue by nuxeh** [NixOS/nixpkgs#86125]
Hi, i need to use open-zwave as a dependency for a build, but the version built in the Nix package is a specific fork for supporting home-assistant, which does not work for my package build due to linking errors.

https://github.com/NixOS/nixpkgs/blob/98dbff9a65c4d0f67834787398021a636896f204/pkgs/development/libraries/openzwave/default.nix#L12

I will happily contribute a new package, but I'm not sure how to proceed, with regards to how it would fit in with this package, or if indeed the best way would be to modify this package to use the upstream repo.

Pinging people who have maintained the package, apologies for the noise!

@etu 
@volth 
@dotlambda 
@OmnipotentEntity 
@matthewbauer 
@WhittlesJr

**Comment by dotlambda** [comment]
We should replace the `openzwave` package with an official version and make `omeassistant-pyozw` use the fork.
