### ISSUE TITLE
How to build own build of package

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#86149]
Well that is more a mix of a packaging request and a question:

I want to use the youtubeviewer package:
[link to the file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/perl-modules/WWW-YoutubeViewer/default.nix)

but it lacks the optional dependency of Unicode linebreak:
> [WARN] Please install Unicode::GCString or Text::CharWidth in order to use this functionality.

So I thought let's load a modified version of this package similar than a modified emacs package I could add in a nix package so I tried that:

```
{ pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) {} }:
let
  my-youtubeviewer = (
    pkgs.perl530Packages.WWWYoutubeViewer.override {
      propagatedBuildInputs = [
        LWP
        LWPProtocolHttps
        DataDump
        JSON
        UnicodeLineBreak
      ];
    });
in my-youtubeviewer
```

Can somebody explain me what I am missing or if that is not possible or to difficult add this functionality to the package? I can install that unicodelinebreak package manually but youtubeviewer then don't finds it.

**Comment by abathur** [comment]
Not sure if this is still relevant given how long it's been, but I'll take a swing just in case:

I imagine you're stumbling over the difference between override and overrideAttrs. `override` enables you to override the arguments the package is called with, while `overrideAttrs` enables you to change the attributes themselves. 

Something like this might do what you need:
```nix
{ pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) {} }:
let
  my-youtubeviewer = (
    pkgs.perl530Packages.WWWYoutubeViewer.overrideAttrs(prev: {
      propagatedBuildInputs = prev.propagatedBuildInputs ++ [
        pkgs.perl530Packages.UnicodeLineBreak
      ];
    }));
in my-youtubeviewer
```

 (this seems to build for me, but it looks like I need API keys to test this out...)
