### ISSUE TITLE
ruby: bundle != bundler

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8619]
I guess this is not expected behaviour:

When I exec `bundle` I get install issues as a package in my rails application needs `ruby 2.2.0`, when I use `bundler` (mind the additional R), it works.

Seems like these two are not the same, but I guess they should be.

**Comment by zimbatm** [comment]
@matthiasbeyer can you run `ls -la "$(which bundler)"` and `ls -la "$(which bundle)"` to find out to which packages they belong to ? (if it's not too late)

**Comment by matthiasbeyer** [comment]
That looks like fun:

```
$ ls -la $(which bundle)
-r-xr-xr-x 1 root nixbld 511  1. Jan 1970  /nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/bin/bundle

$ ls -la $(which bundler)
-r-xr-xr-x 1 root nixbld 283  1. Jan 1970  /nix/store/yfcppfmkdnd7xgi9wnc3mxkibcsp8ziz-bundler-1.10.5/bin/bundler
```

Maybe this issue was fixed already? I'm not sure here...

**Comment by zimbatm** [comment]
Yeah it looks fine. Maybe close the issue and re-open if it happens again.
