### ISSUE TITLE
Weird graphical glitches

### ISSUE THREAD

**Issue by M-Gregoire** [NixOS/nixpkgs#86212]
Hello everyone,

I don't exactly when this started (20.03 update?, compton->picom?) but I'm encountering a lot of graphical glitches, only on popups and menus.

Screenshots are worth a thousand words:
`notify-send hello`
![2020-04-28-153032_2048x1152_scrot](https://user-images.githubusercontent.com/9469313/80493563-dcf57f00-8965-11ea-812c-a831044b3110.png)

`A firefox menu`
![2020-04-28-153115_2048x1152_scrot](https://user-images.githubusercontent.com/9469313/80493567-de26ac00-8965-11ea-83e6-f41a6a48cdb4.png)

My graphic card is a `Radeon HD 6870`.
`lspci`
```
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge (rev 02)
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD/ATI] RD890S/RD990 I/O Memory Management Unit (IOMMU)
00:02.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GFX port 0)
00:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 0)
00:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 1)
00:06.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 2)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barts XT [Radeon HD 6870]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Barts HDMI Audio [Radeon HD 6790/6850/6870 / 7720 OEM]
```

Looking at `lsmod` I can see `radeon` is loaded.

I believe my graphics card is compatible with `amdgpu` so I tried setting 
`services.xserver.videoDrivers = [ "amdgpu" ];` but after rebooting, X11 doesn't start: `Failed to start X11 server`.

Here is an extract of `/var/log/X.0.log`:
```
[    14.477] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    14.480] (--) PCI:*(1@0:0:0) 1002:6738:1682:3101 rev 0, Mem @ 0xd0000000/268435456, 0xfe920000/131072, I/O @ 0x0000e000/256, BIOS @ 0x????????/131072
[    14.480] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[    14.480] (II) "glx" will be loaded by default.
[    14.480] (II) LoadModule: "glx"
[    14.480] (II) Loading /nix/store/c6fs9jmj1j5lvmi8b216gc6qphfa3mbz-xorg-server-1.20.8/lib/xorg/modules/extensions/libglx.so
[    14.481] (II) Module glx: vendor="X.Org Foundation"
[    14.481] 	compiled for 1.20.8, module version = 1.0.0
[    14.481] 	ABI class: X.Org Server Extension, version 10.0
[    14.481] (II) LoadModule: "amdgpu"
[    14.482] (II) Loading /nix/store/ajjabcanpc021r0idrwp6yj5m47hk4xn-xf86-video-amdgpu-19.0.1/lib/xorg/modules/drivers/amdgpu_drv.so
[    14.482] (II) Module amdgpu: vendor="X.Org Foundation"
[    14.482] 	compiled for 1.20.8, module version = 19.0.1
[    14.482] 	Module class: X.Org Video Driver
[    14.482] 	ABI class: X.Org Video Driver, version 24.1
[    14.482] (II) AMDGPU: Driver for AMD Radeon:
	All GPUs supported by the amdgpu kernel driver
[    14.482] (II) AMDGPU(0): [KMS] drm report modesetting isn't supported.
[    14.482] (EE) Screen 0 deleted because of no matching config section.
[    14.482] (II) UnloadModule: "amdgpu"
[    14.482] (EE) Device(s) detected, but none match those in the config file.
[    14.482] (EE) 
Fatal server error:
[    14.482] (EE) no screens found(EE) 
[    14.482] (EE) 
Please consult the The X.Org Foundation support 
	at http://wiki.x.org
 for help. 
[    14.482] (EE) Please also check the log file at "/var/log/X.0.log" for additional information.
[    14.483] (EE) 
[    14.485] (EE) Server terminated with error (1). Closing log file.
```

During my research, I found https://discourse.nixos.org/t/working-amdgpu-configurations/2305/11

However, he fixed it by upgrading his kernel. However, I'm currently at a more recent version that what fixed it for him:
`uname -a`:
```
Linux <hostname> 5.5.17 #1-NixOS SMP Mon Apr 13 11:16:42 UTC 2020 x86_64 GNU/Linux
```
`file -L /run/current-system/kernel`:
```
/run/current-system/kernel: Linux kernel x86 boot executable bzImage, version 5.5.17 (nixbld@localhost) #1-NixOS SMP Mon Apr 13 11:16:42 UTC 2020, RO-rootFS, swap_dev 0x4, Normal VGA
```

I'm not even sure moving to `amdgpu` would fix my glitching problem but I'm not sure how I can diagnose this issue.

Any help would be greatly appreciated!

**Comment by vcunat** [comment]
A quick look in [arch wiki](https://wiki.archlinux.org/index.php/AMDGPU#Installation) says that pre-GCN isn't supported by amdgpu, which seems to be your case (GCN introduced in 7xxx).

**Comment by M-Gregoire** [comment]
Oh I'm sorry I missed it. So it's probably not a driver issue since the HD 6870 is listed in `man radeon` (https://www.x.org/releases/current/doc/man/man4/radeon.4.xhtml).

That was the only idea I had concerning these glitches. Do you have any idea how I can diagnose this issue?

I found this especially weird since everything other than menus/popups are working perfectly (No issue on Windows either).

**Comment by vcunat** [comment]
I don't know.  Perhaps it's some regression in newer mesa... these older parts surely get less attention and testing today.

**Comment by M-Gregoire** [comment]
Thanks for your answer.
If this is the case, do you believe it would be easy to test using an older version of mesa or is there too much inter-dependency?

**Comment by vcunat** [comment]
It might not be too hard.  For smaller version changes I think it should work to put this into `configuration.nix`
```nix
{
  hardware.opengl.package = (pkgs.mesa.overrideAttrs (_a: rec {
    version = "19.2.8";
    src = pkgs.fetchurl {
      url = "https://mesa.freedesktop.org/archive/mesa-${version}.tar.xz";
      sha256 = "0mssds8hdh894vmpqlxfpghdk4m0f2vs17632kh2qhn7ankqzyng";
    };
  })).drivers;
} # wrapper to fix highlighting
```

but e.g. in this example I see that something with patches was changed in the meantime...

**Comment by M-Gregoire** [comment]
After looking into bugs with mesa and Radeon I found a few reports of glitches similar to mine, which were resolved by downgrading (Some were also apparently fixed in v20) so thank you for giving me a promising lead!

Unfortunately, I wasn't able to make your code work as I got some patching errors:
```
applying patch /nix/store/2fm899chzqgdksawbd6f7zkala2kb5ir-missing-includes.patch
patching file src/gallium/winsys/svga/drm/vmw_screen.h
patching file src/gallium/state_trackers/nine/threadpool.h
Hunk #1 succeeded at 28 with fuzz 2 (offset 4 lines).
patching file src/util/rand_xor.c
patching file src/amd/vulkan/winsys/amdgpu/radv_amdgpu_winsys.h
Hunk #1 succeeded at 28 with fuzz 1.
applying patch /nix/store/jms62vn187lqyvifjgyd4i30zc3771wf-opencl-install-dir.patch
patching file src/gallium/targets/opencl/meson.build
Hunk #1 succeeded at 70 (offset 2 lines).
applying patch /nix/store/z7ljzakr5xjk2hwkbny96a6vz6slv86c-disk_cache-include-dri-driver-path-in-cache-key.patch
patching file meson_options.txt
Hunk #1 succeeded at 333 (offset -8 lines).
patching file src/util/disk_cache.c
Hunk #1 succeeded at 391 (offset -4 lines).
Hunk #2 succeeded at 415 (offset -4 lines).
patching file src/util/meson.build
Hunk #1 FAILED at 158.
1 out of 1 hunk FAILED -- saving rejects to file src/util/meson.build.rej
```

I also tried `19.2.7` with the same result. I also tried going back as far as `18.3.6` with the identical patching error.

Would you be kind enough to help me a bit further?

**Comment by chico-miles** [comment]
Maybe the same reason as in https://github.com/NixOS/nixpkgs/issues/86212 ?

**Comment by vcunat** [comment]
@chico-miles: wrong number by accident ;-)

**Comment by jtojnar** [comment]
@M-Gregoire Taking the expression from older revision of nixpkgs should work. You will need to adjust the hashes and maybe the attributes passed to match the line in `pkgs/top-level/all-packages.nix` of the nixpkgs revision you chose:

```
(with pkgs; let
  oldNixpkgs = fetchzip {
    name = "old-nixpkgs";
    url = "https://github.com/NixOS/nixpkgs/archive/9073a0cb8b2f419785a60969e11e96733f29b200.tar.gz";
    hash = "sha256-0C94cOmB7dxpWzSXlLNt2OyhEt20qX9murBWUh52HLo=";
  };
in callPackage "${oldNixpkgs}/pkgs/development/libraries/mesa/default.nix" {
  llvmPackages = llvmPackages_9;
  inherit (darwin.apple_sdk.frameworks) OpenGL;
  inherit (darwin.apple_sdk.libs) Xplugin;
})
```

**Comment by vcunat** [comment]
You can try, but I suspect e.g. glibc versions mismatch may cause problems.

**Comment by jtojnar** [comment]
The code above would use the expression with your package set (including glibc).

**Comment by vcunat** [comment]
Oh, right, clever :-)  I didn't read it properly.

**Comment by M-Gregoire** [comment]
Thank you again for your answers! I've just learned about SRI Hashes thanks to your post. Excuse my ignorance but something doesn't really make sense to me.
Using your example, I got:
```
hash mismatch in fixed-output derivation '/nix/store/yzdbb04wlff6i5r78zfjr5ihb4vf59m7-old-nixpkgs':
  wanted: sha256:1fhwfqg54mmhp9k7zadlvl9a3v6qdnrr95rlbdlxrvc1x5q7hbyh
  got:    sha256:18yshdnzjh2azaff5k5rmvc44w2x59abk5wc9gwmrypg708qdn2w
```

So I tried playing a bit with the hashes and found the following commit: https://github.com/NixOS/nix/commit/6024dc1d97212130c19d3ff5ce6b1d102837eee6

According to it:
> SRI hashes (w3.org/TR/SRI) combine the hash algorithm and
a base-64 hash.

The following example is given: `5d22dad058d5c800d65a115f919da22938c50dd6ba98c5e3a183172d149840a4` becomes `sha256-XSLa0FjVyADWWhFfkZ2iKTjFDda6mMXjoYMXLRSYQKQ=` but I couldn't find a way to go from one to the other:

```
$ echo 5d22dad058d5c800d65a115f919da22938c50dd6ba98c5e3a183172d149840a4 | base64
NWQyMmRhZDA1OGQ1YzgwMGQ2NWExMTVmOTE5ZGEyMjkzOGM1MGRkNmJhOThjNWUzYTE4MzE3MmQx
NDk4NDBhNAo=

$ echo XSLa0FjVyADWWhFfkZ2iKTjFDda6mMXjoYMXLRSYQKQ= | base64 -d
㡃-@%
```

Could you explain how the `hash = "sha256-0C94cOmB7dxpWzSXlLNt2OyhEt20qX9murBWUh52HLo=";` from your code became `wanted: sha256:1fhwfqg54mmhp9k7zadlvl9a3v6qdnrr95rlbdlxrvc1x5q7hbyh`?

**Comment by vcunat** [comment]
It seems JTojnar got the hash wrong; I don't know why.  I'm getting the same one as you.
```
$ nix-prefetch-url --unpack https://github.com/NixOS/nixpkgs/archive/9073a0cb8b2f419785a60969e11e96733f29b200.tar.gz
unpacking...
[18.1 MiB DL]
path is '/nix/store/l7b04q2x3dlgjnz57dgqjr6yg3vb6hvd-9073a0cb8b2f419785a60969e11e96733f29b200.tar.gz'
18yshdnzjh2azaff5k5rmvc44w2x59abk5wc9gwmrypg708qdn2w
```
Hashes can be written in multiple formats, but that's not an issue in here.

**Comment by M-Gregoire** [comment]
> Hashes can be written in multiple formats, but that's not an issue in here.
Indeed, I was just trying to understand how SRI hashes were implemented :).

So, I have tried few commits down to release 19.03 (Where I didn't had any problems) to try mesa 20 & 19 down to 18.3.4. Unfortunately, I have the same issue independently of the version of mesa I'm using.

I also tried a few kernel options described in https://wiki.archlinux.org/index.php/ATI#Driver_options such as `TearFree` or tried to use `exa` instead of `glamor` without any success.

**Comment by jtojnar** [comment]
Sorry about not being precise enough, I used a random nixkpkgs `rev`, you will need to find a commit that has the old version of mesa and substitute that.

A sha256 hash is a binary string. For convenience (so you do not have to deal with non-printable characters), it is typically presented in base-16 encoding. So it is not enough to encode the base-16 encoding but you have to get the hash value by decoding it first:

```ShellSession
$ echo 5d22dad058d5c800d65a115f919da22938c50dd6ba98c5e3a183172d149840a4 |  xxd -r -p | base64
XSLa0FjVyADWWhFfkZ2iKTjFDda6mMXjoYMXLRSYQKQ=
```

Nix even has a convenience function for that:

```ShellSession
$ nix to-sri --type sha256 5d22dad058d5c800d65a115f919da22938c50dd6ba98c5e3a183172d149840a4
sha256-XSLa0FjVyADWWhFfkZ2iKTjFDda6mMXjoYMXLRSYQKQ=
```

**Comment by M-Gregoire** [comment]
Seems like we wrote our post at the exact same time!

> Sorry about not being precise enough, I used a random nixkpkgs rev, you will need to find a commit that has the old version of mesa and substitute that.

That was perfectly clear, thank you :+1: .
This is what I did, without any success unfortunately (See post https://github.com/NixOS/nixpkgs/issues/86212#issuecomment-621939030).

Concerning the hashes, thank you for your explanation, I was really perplex and wasn't able to find an answer!

**Comment by marius851000** [comment]
Hello, I had a similar problem with any videogame that use opengl (but not with firefox). I downgraded the mesa driver ( with

    oldNixPkgs = import (fetchzip {
      name = "old-nixpkg";
      url = "https://github.com/NixOS/nixpkgs/archive/3f3ead76fdb741a0dd71a694a7b24efa024848d8.tar.gz";
      sha256 = "0a7k0d70bf88lvfxa8lvr6xiammqxbmvaf9rilf5bg3pd2ccad8r";
    }) {};

and

`package = oldNixPkgs.mesa.drivers;`

This fixed both strange texture in xonotic, and the fact that the driver wasn't able to use antialising, preventing azimuth from starting. I made a post some time before in the discourse:

https://discourse.nixos.org/t/some-app-cant-start-with-couldnt-find-matching-glx-visual/6508/4

**Comment by marius851000** [comment]
I've made a bisect, and the first version with problem is b5c1cb2e8a934980efa0c47e13da202f01b38f6b , that upgraded meso from 19.3.3 to 20.0.1

**Comment by vcunat** [comment]
@marius851000: my guess is that you haven't updated the non-working games to a version built against newer nixpkgs/mesa.  (The discourse post shows older mesa versions than 20.x, BTW.)

**Comment by marius851000** [comment]
No, all my game is up to date (with nixos-unstable-small), however, I bissected the error, and found that it correspond with "implement sdma for GF9" (082d1c168649edc6dc0f83e452347011905713d8) on mesa. I will report an error here.

**Comment by M-Gregoire** [comment]
Thank you for your suggestion @marius851000, I've tried your commit (Even though I tried Mesa 18, 19 and 20 prior to your message) but that unfortunately didn't solve my issue.

I have no idea what could be the issue but I'm starting to believe that's not from mesa (Probably not hardware either since everything is fine on Windows).

**Comment by marius851000** [comment]
The commit I mentioned was the first to have the problem. A commit that work is 4cacba0c86c75f7b022eedbdb3f12957f495e893 , the latest that didn't have the problem. I reported the bug on mesa now, it can be found here https://gitlab.freedesktop.org/mesa/mesa/-/issues/2908

**Comment by marius851000** [comment]
If you have tried older version of mesa, however, it may a different error.

**Comment by zarelit** [comment]
I have the same issue @M-Gregoire , I think so because the artifacts are the same: a weird band in the corner just like in your screenshots.
I used the workaround of pinning mesa to an older version, the latest I know it's working: the latest commit of release-19.09.
It's a bit radical so I'll let you know if I have issues with it but for now it's working for me.

This is what I put in nixpkgs, switched and rebooted:
```
  hardware.opengl.package = (import (pkgs.fetchzip {
      name = "old-nixpkgs";
      url = "https://github.com/NixOS/nixpkgs/archive/0a11634a29c1c9ffe7bfa08fc234fef2ee978dbb.tar.gz";
     sha256 = "0vj5k3djn1wlwabzff1kiiy3vs60qzzqgzjbaiwqxacbvlrci10y";
  }) {}).mesa.drivers;
```

**Comment by jul1u5** [comment]
Downgrading mesa also solved my issue with Intel integrated graphics. Previously, CS:GO was flickering horribly with improperly loaded textures.

**Comment by M-Gregoire** [comment]
> I have the same issue @M-Gregoire , I think so because the artifacts are the same: a weird band in the corner just like in your screenshots.
> I used the workaround of pinning mesa to an older version, the latest I know it's working: the latest commit of release-19.09.
> It's a bit radical so I'll let you know if I have issues with it but for now it's working for me.
> 
> This is what I put in nixpkgs, switched and rebooted:
> 
> ```
>   hardware.opengl.package = (import (pkgs.fetchzip {
>       name = "old-nixpkgs";
>       url = "https://github.com/NixOS/nixpkgs/archive/0a11634a29c1c9ffe7bfa08fc234fef2ee978dbb.tar.gz";
>      sha256 = "0vj5k3djn1wlwabzff1kiiy3vs60qzzqgzjbaiwqxacbvlrci10y";
>   }) {}).mesa.drivers;
> ```

Thank you so much! This works perfectly :tada: 
I'm not sure why it didn't worked when I tried multiple version of mesa in my older posts but I'm so relieved this finally works. I was getting a bit desperate of not having any readable menu!
