### ISSUE TITLE
[steam] Steam Remote Play Together no longer works; libtier0_s.so missing

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#86257]
**Describe the bug**
Steam Remote Play no longer works. The client never manages to start, and instead prompts a "The streaming client exited unexpectedly (2)" message.

**To Reproduce**
1. Open Steam
2. Be invited by a friend to play Steam Remote Play Together.
3. Accept invitation.

**Additional context**
I get the following line in the console logs shortly before the client crashes. It complains about a missing `libtier0_s.so`, but said library is present in the `ubuntu12_32` folder.
```
/home/localuser/local/share/Steam/ubuntu12_32/streaming_client: error while loading shared libraries: libtier0_s.so: cannot open shared object file: No such file or directory
```
I haven't managed to find information on that library by searching the web, other than many games and the Steam client itself seem to fail when it is not found. I also tried using `steam --reset`, but it did not work.

**Notify maintainers**

@jagajaga @abbradar @hrdinka

**Comment by ashkitten** [comment]
launching steam with `LD_LIBRARY_PATH=~/.steam/root/ubuntu12_32:$LD_LIBRARY_PATH steam` makes this work, but controller input does not seem to work on the remote client, unsure if that's related.

**Comment by ZerataX** [comment]
@ashkitten I have the same issue, is there an issue for this already, otherwise would probably make sense to create an separate issue?

**Comment by ZerataX** [comment]
okaaaaay soooo I've got a workaround but it confuses me extremely.
I noticed that when I rearrange controller order that my remote play partner could suddenly control the game, but I couldn't anymore.

So now I plugged in a 2nd controller on my side and rearranged the controllers until it suddenly worked, I was able to play with my friend, but had a 2nd controller just by the side doing nothing.

so yeah weirdest workaround, really not sure what's going on here.

**Comment by aanderse** [comment]
I just tried `steam` remote play and had this error when trying without a controller:
![Screenshot_20200809_153937](https://user-images.githubusercontent.com/7755101/89740430-9cbe9600-da56-11ea-8fc8-3fb22310f37f.png)

Does anyone have any ideas for a proper solution?

**Comment by jonringer** [comment]
i do use steam, but I don't use remote play :(

**Comment by deviant** [comment]
I ran into this last week.

**Comment by jonringer** [comment]
please test the PR

```
$ nix-shell -p nixpkgs-review --run 'nixpkgs-review pr 120829 --package steam'
$ ./results/steam/bin/steam
```

**Comment by jonringer** [comment]
> makes this work, but controller input does not seem to work on the remote client, unsure if that's related.

This should work if remote client has the correct udev rules installed. For Nixos, this is accomplished by doing `programs.steam.enable = true` or `environment.systemPackages = [ steam ];` or `services.udev.packages = [ steam ];`.

**Comment by deviant** [comment]
@jonringer I took that out for a spin, but no dice. Tried @ashkitten's solution as well, but that doesn't seem to work either— it seems something about how Steam launches subprocesses (or our sandboxing infra) has changed since then.

This does resolve the `libtier0_s.so missing` error, but now there's this even more mysterious one in its place:

```
/home/belle/.local/share/Steam/ubuntu12_32/streaming_client: symbol lookup error: /home/belle/.local/share/Steam/ubuntu12_32/streaming_client: undefined symbol: SDL_GameControllerTypeForIndex
```

What *does* work, however, is moving `~/.steam/root/ubuntu12_32/streaming_client` to `~/.steam/root/ubuntu12_32/streaming_client~`, and putting a script in its place that prefixes `LD_LIBRARY_PATH` with `~/.steam/root/ubuntu12_32` and chainloads. I'm definitely not familiar with how steam works internally, but I did snoop through its processes and found env vars `STEAM_LD_LIBRARY_PATH` and `SYSTEM_LD_LIBRARY_PATH` that are absent of our additional paths.

Obviously, replacing files managed by Steam isn't really an option, but I hope this sheds a little more light on the problem.

I will note that even after all of this, I'm still not getting more than a [non-game, generic steam] loading screen— playing around with the firewall suggests that it actually needs more ports to be open than are documented. That belongs in another issue, though, and we can get to that once everyone can actually launch this at all.

**Comment by jonringer** [comment]
@deviant thanks for looking into this.

Yea, unfortunately I don't have a `~/.steam/root/ubuntu12_32/streaming_client` directory on my system, so I'm not really in a position to test this further. This may only be populated if you use the service. But I don't see the harm in adding additional paths to `LD_LIBRARY_PATH` which may be empty for some individuals, the linking logic should just move on to the next paths.

> I will note that even after all of this, I'm still not getting more than a [non-game, generic steam] loading screen— playing around with the firewall suggests that it actually needs more ports to be open than are documented. That belongs in another issue, though, and we can get to that once everyone can actually launch this at all.

:(

**Comment by deviant** [comment]
@jonringer https://github.com/ValveSoftware/steam-for-linux/issues/7686 seems potentially related— if this is true, setting env vars like we are currently won't help for subprocesses at all, as they only affect Steam itself. :(

I assume this is done to avoid user-set environment variables from causing havoc with games (e.g. libraries needed to run Steam may not be what you want to load into a specific game, if it requires a specific version of SDL, etc). I'm not sure how to go about solving this, as it may require changes to Steam as well.

**Comment by deviant** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/7542 Actually, found this which looks suspiciously like the issue we're having. I'll see if I can test whatever beta has the purported fix later & report back.

**Comment by jonringer** [comment]
We also set ` SYSTEM_LD_LIBRARY_PATH` to `LD_LIBRARY_PATH`, as some zachtronics games did the scrubbing as well.

https://github.com/NixOS/nixpkgs/blob/c8dff328e51f62760bf646bc345e3aabcfd82046/pkgs/games/steam/fhsenv.nix#L55

**Comment by deviant** [comment]
Steam is definitely not respecting those: checking the env vars from `/proc` doesn't show our changes, and they differ from `LD_LIBRARY_PATH`. I'm fairly sure its subprocesses are then taking `LD_LIBRARY_PATH` from these 'cleansed' variables.

**Comment by ashkitten** [comment]
is there some way automatic steam runtime updates could be PR'd by a bot so this doesn't happen again in the future?

**Comment by jonringer** [comment]
> I think that would require removing the `dontRecurseIntoAttrs` on `steamPackages`?

I already added the ability for it to be able to update itself in https://github.com/NixOS/nixpkgs/commit/e6bf8328806f19f8025bba23732117f7c2fb262d#diff-5d79ccf52364858ab3c31de5a30fe7c45c93c2729efded70dd4842f110579c0f I just forgot about `nixpkgs-update` only caring about packages that it can query through `nix-env -qa` :)
