### ISSUE TITLE
Can boot fallback img, but not main img.

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#8633]
So as some of you know, I tried to install nixos on my ThinkPad X220 today. I want to report the following issue:

I was not able to boot from the 14.02-live-stick (minimal) with the default boot entry. I was only able to boot the fallback image. The former always resulted in what I've reported in [this issue](https://github.com/NixOS/nixpkgs/issues/7132).

**Comment by schrislambert** [comment]
+1.  I'm having the same issue.

**Comment by matthiasbeyer** [comment]
@schrislambert You mean the filesystem label for the bootstick? I had that set to "NIXOS_ISO", didn't work, though.

**Comment by davidak** [comment]
What do you mean by "fallback image"?

**Comment by matthiasbeyer** [comment]
When booting, the boot menu shows the normal entry and a "fallback" entry.

**Comment by davidak** [comment]
![img_4098](https://cloud.githubusercontent.com/assets/91113/12277245/a65853ce-b97a-11e5-8ab9-0b6e760dcfe0.JPG)

**Comment by matthiasbeyer** [comment]
Seems that this is not true for the latest versions of the image...

**Comment by jagajaga** [comment]
@matthiasbeyer is this true nowadays?

**Comment by davidak** [comment]
@jagajaga what do you mean exactly?

I still can't boot NixOS from USB on a PC with BIOS! Tested today with 15.09 and 16.03-beta.

**Comment by jagajaga** [comment]
@davidak that's strange. I've booted nixos from usb on a bios PC about 1 month ago... I just did `dd` of an image to my usb flash drive.

**Comment by davidak** [comment]
@jagajaga i can confirm that it works with dd!

**Comment by jagajaga** [comment]
So what's the problem? :confused:

**Comment by davidak** [comment]
@matthiasbeyer is this issue solved for you or covered by the one of the linked issues? then please close it.

**Comment by matthiasbeyer** [comment]
This has long been solved, as I managed to install nixos from the fallback image.

I don't care anymore as I run nixos for more than 1 year now and I know about this... strange behaviour. I kept this open so one can fix it...

So yes, I will close this now.
