### ISSUE TITLE
mf-install

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#86370]
**Project description**

A Media Foundation workaround for Wine. Enables Linux support via Proton for certain games like Borderlands 3.

An integration with the `steam` package might make sense.

**Metadata**

* homepage URL: https://github.com/z0z0z/mf-install
* source URL: https://github.com/z0z0z/mf-install
* license: None provided
* platforms: Unix

**Comment by Atemu** [comment]
The files in the GH repo are illegally distributed binary DLLs, see https://github.com/z0z0z/mf-install/issues/1.

The only legal way of getting these would be to make the user agree to M$'s EULA, sell their soul etc. to download the a Windows ISO and provide them with a script that extracts the relevant files on their machine locally.

**Comment by matthew-piziak** [comment]
Thanks for the straight talk, @Atemu!

**Comment by urandom2** [comment]
considering the [upstream comment](https://github.com/z0z0z/mf-install#october-2021-notice) and discussion from #108598, I am going to close this as stale; feel free to push back and I can assist with packaging
