### ISSUE TITLE
New Terminator package using Python 3

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#86415]
**Project description**

`terminator` is already packaged in nixpkgs, but the upstream project has been taken over by new maintainers who have ported it to Python 3 and are continuing development. As far as I know this new version is also used by Debian/Ubuntu (it has python3 dependencies in those distros).

I have a local attempt at a new derivation and it Works For Me™, but it has a patch in it which I don't think it should need. Also, maybe the original maintainer @bjornfor may want to do the update? If desired I can open a PR with my current state of affairs.

**Metadata**

* homepage URL: https://github.com/gnome-terminator/terminator
* license: GPL2
* platforms: Linux

**Comment by bjornfor** [comment]
I have limited spare time these days (months), so please be my guest 😀
