### ISSUE TITLE
systemd-boot: default boot entry ignored with systemd v245

### ISSUE THREAD

**Issue by danielfullmer** [NixOS/nixpkgs#86422]
**Describe the bug**
With systemd-boot  v245, the `default` set in `loader.conf` by `systemd-boot-builder.py` is no longer respected. In the current state, it will always choose the boot loader entry with the largest `version` in the loader `.conf` file. This corresponds to the largest generation number.

**To Reproduce**
1. On `nixos-unstable`, run `bootctl install` or `bootctl update` to ensure the latest `systemd-boot` is used. 
2. Run `nixos-rebuild boot --rollback` to switch back to a previous generation.
3. Reboot and notice that it still defaults to the latest generation, not the previous one.

**Additional context**
This is a result of the following change:  https://github.com/systemd/systemd/commit/6cd12ebcfe459466257ea63022a32515d756e719
The fix seems fairly straightforward, to just have `systemd-boot-builder.py` include the `.conf` suffix on the `default` entry in the `loader.conf` file. However, we would still have a problem if the user is using an older version of `systemd-boot` (if he or she hasn't updated with `bootctl update`).
Similarly, a user who hasn't updated `systemd-boot` using `bootctl update` since updating to `v235` would not encounter this issue, since the `default` is still correct for their version of `systemd-boot`.

Upstream issue: https://github.com/systemd/systemd/issues/15068

**Notify maintainers**
@flokli  @andir @edolstra

**Comment by flokli** [comment]
Does the following patch fix it for you?

```diff
From 9b9f91e985ac45fbad64f2781f1bc1bfe7aee412 Mon Sep 17 00:00:00 2001
From: Florian Klink <flokli@flokli.de>
Date: Thu, 30 Apr 2020 23:57:39 +0200
Subject: [PATCH] nixos/systemd-boot: fix default boot entry selection

https://github.com/systemd/systemd/commit/6cd12ebcfe459466257ea63022a32515d756e719
changed behaviour - now the "default" entry needs to identity an entry
with its full name, including the ".conf".

Reported-In: https://github.com/NixOS/nixpkgs/issues/86422
---
 .../system/boot/loader/systemd-boot/systemd-boot-builder.py   | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py b/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py
index f48a085ce57..fb0b396d078 100644
--- a/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py
+++ b/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py
@@ -47,9 +47,9 @@ def write_loader_conf(profile, generation):
         if "@timeout@" != "":
             f.write("timeout @timeout@\n")
         if profile:
-            f.write("default nixos-%s-generation-%d\n" % (profile, generation))
+            f.write("default nixos-%s-generation-%d.conf\n" % (profile, generation))
         else:
-            f.write("default nixos-generation-%d\n" % (generation))
+            f.write("default nixos-generation-%d.conf\n" % (generation))
         if not @editor@:
             f.write("editor 0\n");
         f.write("console-mode @consoleMode@\n");
-- 
2.26.2

```

**Comment by danielfullmer** [comment]
Yes, it does. But my concern is that it would break this for people who hadn't already run `bootctl update`.

**Comment by flokli** [comment]
Yeah, this is definitely a problem - currently, all fresh installations with systemd 245 won't have a working default selection, and if we update with above patch, all existing ones will break. 

I don't think upstream will revert the change either - it has been in their codebase since November 2019.

We could add some code to `systemd-boot-builder.py` that compares ${systemd}/lib/systemd/boot/efi/systemd-boot[x64,aa64].efi with what's in `/boot` and invokes `bootctl update` if it differs to always update bootctl - @aszlig @Mic92, what do you think?

**Comment by Mic92** [comment]
Updating the bootloader seems like a good idea in general.
I would not perform the check the file manually but rather parse the output of `bootctl status` for now. This would result in less updates (only for systemd version upgrades) and is therefore less risky (at the cost of missing some fixes of without a bump). It also saves us from re-implementing things like finding out where $ESP is and what infix needs to got into `${systemd}/lib/systemd/boot/efi/systemd-boot-${EFI_MACHINE_TYPE_NAME}.efi` path

**Comment by flokli** [comment]
@danielfullmer would you be willing to file a PR doing as @Mic92 suggested?

**Comment by danielfullmer** [comment]
@flokli Unfortunately, I won't be able to work on this in the near future. I'm up against some deadlines for graduation.

**Comment by flokli** [comment]
@danielfullmer all good, thanks for the heads-up! Maybe someone else picks it up in the meantime :-)
