### ISSUE TITLE
CONTRIBUTING.md: add some advice about testing (including tarball evaluation)

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#8645]
As we know, adding a package that builds fine on NixOS may still break tarball evaluation. There are a few ways to check: building `tarball` job from `release.nix`, running `./maintainers/scripts/test-eval-release.sh` etc. I think we may want to mention one of this checks in `CONTRIBUTING.md`. I am not sure which one is the best recommendation. 

Also, in the `Write in comment if you have tested your patch.` part it might be useful to ask specifically to mention dependent packages tested after the update (if any). Such a question could encourage some people to go and test a few reverse dependencies if they have a fast build machine available.

I am not sure about details in either case, so I am not doing a PR (yet?) but asking for opinions in an issue.

**Comment by dezgeg** [comment]
The Travis script already attempts some variant of this check:
````
    echo "=== Verifying that nixpkgs evaluates..."
    nix-env -f. -qa --json >/dev/null
````
So whatever is the better way can be added to that script once it's decided.

**Comment by 7c6f434c** [comment]
>The Travis script already attempts some variant of this check:

Well, the point is that we don't trust Travis too much…

Also, if something is quick and easy to check before submitting the PR,
it makes sense to write about it there.

**Comment by cillianderoiste** [comment]
Travis uses nox-review which works quite reliably. Travis often fails for other reasons, building takes too long, uses too much memory or the log file is too long etc. Should we just standardize on recommending people use `nox-review wip` before commiting the change?

**Comment by 7c6f434c** [comment]
> Should we just standardize on recommending people use `nox-review wip` before commiting the change?

Are we at the point where we already want fewer contributions? I am not
even sure how much disk space it would need for many apparently small 
updates (for example, when one of reverse dependencies has other large
dependencies untouched by the change).

Although looking at PR count, maybe yes, we want fewer PRs and
preferably from contributors who are confident enough to get commit
rights soon afterwards…

**Comment by cillianderoiste** [comment]
>> Should we just standardize on recommending people use `nox-review wip` before commiting the change?

> Are we at the point where we already want fewer contributions? ...

I'm not sure I understand. Are you saying that recommending nox-review will add an obstacle to people who want to contribute? It could be more of a recommendation than a hard requirement: "If you want to verify that your change doesn't break anything inadvertently you can use the nox-review tool [link to info]. Be sure to mention if you've already used this for testing when opening your PR". That could help us in the case where a PR looks reasonable, but Travis fails because of resource constraints.

**Comment by 7c6f434c** [comment]
Requiring using ```nox-review``` would deter some contributions, in my opinion.

If we recommend it in a softer way, cheap partial checks can a good thing to recommend (and I am not sure which of them are better).

**Comment by cillianderoiste** [comment]
The manual has quite a few pointers on checks you can do before opening a PR now, should we close this ticket @7c6f434c?

**Comment by kamilchm** [comment]
Is there a way to run ``nox-review`` locally in the same way as travis do it?

**Comment by vcunat** [comment]
@kamilchm: I suppose you want the link https://github.com/madjar/nox... and it's in nixpkgs as well.

**Comment by Profpatsch** [comment]
triage: this issue is very old, can we close it?

**Comment by 7c6f434c** [comment]
Right, with ofborg deployed what I wondered about is now useless to emphasize anyway.
