### ISSUE TITLE
PHP Module Rdkafka

### ISSUE THREAD

**Issue by alebon** [NixOS/nixpkgs#86463]
**Project description**
_Providing the librdkafka module for php_

I tried to use the existing build suport (https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-pecl.nix) and install the rdkafka module in the same manner. I am still new to nix and couldn't figure out how to make it work in a way so the header files (which are checked/required? during phpize) are not on the path.

I'm not sure if it really needs to be an official package. But would be nice to have some kind of guidance on how to create this kind of packages.

I ended up with the following error and gave up :/:

```
checking for rdkafka support... yes, shared
checking for librdkafka/rdkafka.h" in default path... not found
```

And I used the following package definition:

```
 phpRdkafka = buildPecl {
   version = "3.0.3";
   pname = "rdkafka";

   sha256 = "0lwhdh3nqqgxbm5f6r7661ybigrgi114z6y7l9y9dj25hx27vrii";

   buildInputs = [ pkgs.php72 pkgs.rdkafka ];
   doCheck = false;
   checkTarget = "test";
   checkFlagsArray = ["REPORT_EXIT_STATUS=1" "NO_INTERACTION=1"];
   makeFlags = [ "phpincludedir=$(dev)/include" ];
   outputs = [ "out" "dev" ];
};
```

**Comment by veprbl** [comment]
cc @etu

**Comment by etu** [comment]
cc @NixOS/php :)

**Comment by etu** [comment]
@alebon It was a broken configure script, so I added a `substituteInPlace` to patch the script in the `postPhpize` argument.

I don't have any experience with Apache Kafka, but it's big and common enough to include I think. So I made a PR for it. :)

**Comment by alebon** [comment]
Wow, that was fast :) Thanks!

**Comment by alebon** [comment]
Can confirm that with the fix rdkafka for PHP is built and installed properly. :)

Mabe a sidenote: apcu_bc extension seems to be installed als apc.so but linked as apcu_bc.so, which leads to warnings. I had to point to apc.so by adding an entry to the custom ini configuration

**Comment by talyz** [comment]
@alebon Thanks for reporting the broken `apcu_bc` extension. I'm working on a fix for it and a few other issues that popped up on the way. :)
