### ISSUE TITLE
[feat] composable buildGoModules deps

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#86465]
> What if buildGoModules took a deps attribute?

I thought a bit about that:

> 
> ```nix
> # use `go vendor` like in this PR
> buildGoModule rec {
>   src = fetchFromGitHub { };
>   deps = fetchGoVendor {
>     inherit src;
>     sha256 = "...";
>   };
> }
> ```

This makes the usage significantly more complex to what we currently have.
It adds a new import and a new function. The advantage is though is that it more obvious to the user what is happening under the hood.

> 
> or:
> 
> ```nix
> # generate a vendor from pre-calculated deps using a tool like vgo2nix
> buildGoModule {
>   src = fetchFromGitHub {};
>   deps = fetchGoDeps ./deps.nix;
> }
> ```

While `fetchGoVendor` is returning a derivation containing the vendor directory, `fetchGoDeps` would ideally an attribute set (go import paths -> derivation) which will be linked into the vendor directory at runtime. The reason for the latter is to save one derivations or one download. I suppose the interface could check the type of `deps` and act accordingly.

> 
> or:
> 
> ```nix
> # use the __noChroot version
> buildGoModule rec {
>   src = fetchFromGitHub { };
>   deps = fetchGoVendorImpure {
>     inherit src;
>   };
> }
> ```
> 
> or:
> 
> ```nix
> # the vendor/ folder is shipped with the source, nothing to do
> buildGoModule rec {
>   src = fetchFromGitHub { };
> }
> ```
> 
> The usage would be slightly more complicated but it would allow to compose the vendor code fetching method.

The questions is, should we not set `deps = fetchGoVendor { inherit vendorSha256; };` internally and make `fetchGoVendor` the default fetcher for `buildGoModule`? This would still allow composability but makes the interface simple for the common case.

_Originally posted by @Mic92 in https://github.com/NixOS/nixpkgs/pull/86376#issuecomment-622254718_

**Comment by zimbatm** [comment]
Yet another idea before compacting the tree of possibilities:
```nix
buildGoModule rec {
  src = fetchFromGitHub { };
  depsFetcher = fetchGoVendor;
  depsSha256 = "...";
}
```
Where buildGoModule takes:
```
{ name
# ...
, depsFetcher ? someDefaultDepsFetcher
, deps ? depsFetcher (filterAttrPrefix "deps" attrs)
, ...
} @ attrs:
implementation
```
Where `filterAttrPrefix <prefix> <attrs>` goes through an attribute set keys and selects the ones that start with the prefix, strip the prefix and lower-case the first character of the remaining key, then returns a new attribute set with just those keys.

That way it's possible to pass all the arguments as a flat attribute set. And have different parameters for each depsFetcher.

**Comment by blaggacao** [comment]
I would suggest to circumvent the `depsSha256` &mdash; coming from a go perspective it feels very redundand (bad) deep down in the guts. It feels disregarding the principle of standing on the shoulders of giants, which is very prominent in the go community. It's a value clash between nix way and go way.

In order to resolve this conflict, and have nix more acceptable for go people, here is what we can do:

&rarr; pre-fetch `go.sum` & `go.mod` and put it alongside `default.nix`

Everyone would _intuitively_ understand what it's for and nix go packaging boilerplate would try to step out of the way as much as possible and would honour the go-ish way of doing things.

If it reinvent things, it implicitly says "we have to reinvent because how it is now, it's plain bad you st*p*d id**ts".

I think that is not a subliminal message anyone want's to send out to the go community.

**Comment by blaggacao** [comment]
Furthermore, while going down this route, I'd want to leave a breadcrumb to [this document about fetching non-go resources from subfolders without a `.go` file](https://github.com/go-modules-by-example/index/blob/master/012_modvendor/README.md) &mdash; such as c files or assets.

**Comment by doronbehar** [comment]
> In line with @doronbehar's stance,
> [...]
> 
> pre-fetch `go.sum` & `go.mod` and put it alongside `default.nix`
>
> [..]
>
> If we reinvent things, without a prominent and lengthy rock solid explanation, it implicitly says "we have to reinvent because how it is now, it's plain bad you st*p*d id**ts".

1. **Never** quote me in a message where you use words such as 'stupid' or 'idiots'.
2. Review your comments _before_ posting them, and don't edit it to the point where the comment on the web is almost not recognized. 
3. Pre-fetching go.sum & go.mod files is not my _stance_, it's just an idea I brought up in [a discourse thread](https://discourse.nixos.org/t/creating-vendor-directories-directly-in-srcs-of-go-and-rust-packages-so-fixed-output-derivations-wont-be-needed/7367/) - read it thoroughly before jumping into conclusions about what people think.
4. If _you_ have an idea or a stance, write some Nix+Bash code to bring it to life, don't make a fuss about it and expect others to implement it. Consider that we lack manpower to implement changes we agree on (e.g RFC72), so the issues we less agree on or are harder to understand are the really hard issues to tackle.

**Comment by blaggacao** [comment]
I did remove the reference.

**Comment by blaggacao** [comment]
@doronbehar Let's don't frustrate ourselves mutually :wink:. I only assume the best of your intentions. Ping me on discourse if you want to coach me. I'm actually really thankful for coaching. ❤️

**Comment by AndersonTorres** [comment]
I will close this, because it is basically abandoned.

Feel free to reopen.
