### ISSUE TITLE
qtox on master missing 99% of in-application icons

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#8648]
kde4.qtox, as seen in master, as of July 3, is missing 99% of in-application icons -- I have seen just one.

**Comment by Fuuzetsu** [comment]
cantata also started to miss most of its icons, I don't know if it's related…

**Comment by vcunat** [comment]
That could be some qt5 change. So far I've only solved some gtk in-app icons by wrap-extending ``$XDG_DATA_DIRS`` by ``$XDG_ICON_DIRS`` (defined by some icon-providing packages that need to be in build inputs for this to work).

**Comment by ttuegel** [comment]
I'm not sure what this has to do with Qt 5? If it's under `kde4`, it should be a Qt 4 application.

General comments: Qt doesn't have an "icon theme" concept like GTK does. Icons are loaded by application-specific means. Setting those variables would help if qtox respects them. Note that KDE does provide the "icon theme" abstraction. You'll probably have to poke at the source code to see how qtox gets its icons.

**Comment by deepfire** [comment]
This is what I see, for example for the friendlist widget code -- which is all iconless:
```
    avatar->setPixmap(QPixmap(":img/contact.svg"), Qt::transparent);
    statusPic.setPixmap(QPixmap(":img/status/dot_offline.svg"));
```

**Comment by deepfire** [comment]
..which is in qTox:///src/widget/friendwidget.cpp

**Comment by ttuegel** [comment]
That looks very much like they are trying to use embedded resources, but the [syntax](http://doc.qt.io/qt-4.8/resources.html) is wrong.

**Comment by vcunat** [comment]
@ttuegel: that's a mistake, I believe: I see no ``kde4.qtox``, just plain ``qtox`` attribute which depends on qt5 (and not qt4).

**Comment by ttuegel** [comment]
I can't tell from this issue; did the icons it qTox ever work correctly in NixOS? (I will presume so until told otherwise.) The resources should be compiled in, so it's not an issue of being unable to find files at runtime. Does the build show any errors related to `rcc`?

**Comment by deepfire** [comment]
I have seen an older NixOS build of qtox with icons, yes. February or so..

**Comment by aloiscochard** [comment]
Same problem with `qgis`, interestingly enough it happen on a computer but not on an other and they both share the same system packages configuration.

**Comment by vcunat** [comment]
Icons are typically picked up from XDG dirs which typically means that also some `~/.foo` locations are searched, for example. Wrapping the executables with correct icon path is *the nix solution* (meaning some work per package).

**Comment by Profpatsch** [comment]
(triage) Is that still a problem?

**Comment by aloiscochard** [comment]
@Profpatsch I can not reproduce it for `qgis`, I'm unsure about the OP issue though.

**Comment by deepfire** [comment]
@Profpatsch, I confirm that this is no longer an issue as of `master` `ee8fbaf4110f29d5473c659168cf9bed3f72c86f`.
