### ISSUE TITLE
systemd-tmpfiles /tmp cleanup surprises applications and cannot easily be overridden

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#86600]
We found that sometimes the `/tmp/ourservice/ourprogram-temp` dir disappears on our servers.

Our program creates it but then just disappears some days later, leading to a crash.

The reason is that `systemd` ships a [timer](https://github.com/systemd/systemd/blob/db1442260a56963a8aa507787e71b97e5f08f17c/units/systemd-tmpfiles-clean.service) running a [service](https://github.com/systemd/systemd/blob/db1442260a56963a8aa507787e71b97e5f08f17c/units/systemd-tmpfiles-clean.service) that runs `systemd-tmpfiles --clean`. It shows up under `systemctl list-timers`.

It has a default definition to clean `/tmp` ([code](https://github.com/systemd/systemd/blob/db1442260a56963a8aa507787e71b97e5f08f17c/tmpfiles.d/tmp.conf#L10-L12)):

```
# Clear tmp directories separately, to make them easier to override
q /tmp 1777 root root 10d
q /var/tmp 1777 root root 30d
```

This is described in the man page of [`tmpfiles.d`](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html).

`10d` in the `Age` column means things will be deleted if unchanged for 10 days, which can totally happen in many cases.

The problem is aggravated by the fact that a dir's `mtime` and `ctime` are bumped when its direct contents (dirs and files immediately below it) are changed. But if you have `/tmp/ourservice/ourprogram-temp` and create and delete files in that, then only the times of `ourprogram-temp/` are bumped, the times of the parent dir `/tmp/ourservice/` do not change, because it always only contained the same unchanged contents (1 directory called `ourservice/`). This means that even though the service may continuously create and delete temp files in the subdirectory, systemd will still remove the parent directory.

Overall, I believe the upstream default of `q /tmp 1777 root root 10d` to be a bad default, because it deletes files under the feet of running applications that created them, and most applications do not expect that.

A better default would be `q! /tmp 1777 root root 10d`, which works similarly but is constrained to run only at boot time (the `!` does that).

---

Now, point of this issue is that it is difficult to implement this better default in NixOS.

The systemd upstream `tmpfiles.d` conf files are copied here: 

https://github.com/NixOS/nixpkgs/blob/9c4b22793ee2ff61615acf65f0903280c9b542f5/nixos/modules/system/boot/systemd.nix#L922

Contrary to intuition, you cannot just define

```nix
systemd.tmpfiles.rules = [
  "q! /tmp 1777 root root 10d"
];
```

because that renders out in [`tmpfiles.d/nixos.conf`](https://github.com/NixOS/nixpkgs/blob/9c4b22793ee2ff61615acf65f0903280c9b542f5/nixos/modules/system/boot/systemd.nix#L926-L931), which, confusingly, does not override the upstream default; I believe this to be a systemd bug or a systemd documentation bug, see https://github.com/systemd/systemd/issues/15675.

Next, even if it _did_ override it, it would be unreliable, because as per `tmpfiles.d` man page,

> All configuration files are sorted by their filename in lexicographic order, regardless of which of the directories they reside in. If multiple files specify the same path, the entry in the file with the lexicographically earliest name will be applied.

That means this override would only work because the created `nixos.conf` file name is lexicographically earlier than systemd's default `tmp.conf`, and you could not override other default files that have a file name starting with a letter smaller than `n`.

### My current workaround

```nix
{
# Stop systemd from cleaning /tmp files/dirs older than 10 days
# without constraints, restricting it to that check at boot only.
# The added `!` adds the boot-only, see `man tmpfiles.d` and #1249.
# systemd's default of `q /tmp 1777 root root 10d`, see
#     https://github.com/systemd/systemd/blob/db1442260a56963a8aa507787e71b97e5f08f17c/tmpfiles.d/tmp.conf#L10-L12
# is not good because many programs do not expect that the
# temp dirs they created disappear on them.
#
# The run of `systemd-tmpfiles` can be checked with verbosity like so (from
# https://unix.stackexchange.com/questions/438471/when-are-files-from-tmp-deleted):
#
#     SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --clean
#
# Note that as of writing, that command has some weird (and apparently
# undocumented) pipe special case logic, so you cannot e.g. `grep` it.
#
# Note thet using `systemd.tmpfiles.rules` here did not work, instead
# we have to override the upstream file, see
# * https://github.com/systemd/systemd/issues/15675
environment.etc."tmpfiles.d/tmp.conf".source =
  lib.mkForce (pkgs.runCommand "tmp-clean-only-on-boot.conf" {} ''
    cp "${pkgs.systemd}/example/tmpfiles.d/tmp.conf" "$out"

    exit=0
    grep 'q /tmp ' "$out" || exit=$?
    if [ $exit -ne 0 ]; then
      >&2 echo "Systemd upstream 'tmpfiles.d/tmp.conf' changed, review override!"
      exit 1
    fi

    substituteInPlace "$out" --replace "q /tmp " "# OVERRIDDEN to clean /tmp only on boot!
    q! /tmp "
  '');
}
```

## Desired solution

* We should make it so that `systemd.tmpfiles.rules` can take precedence over default files, no matter their lexicographical file names.
* We should warn about these things in the docs of `systemd.tmpfiles.rules`.

**Comment by flokli** [comment]
@nh2 let's see what upstream has to say on the lexicographical order.

Any chance you could run your services with `PrivateTmp=yes`? That way, they also shouldn't be removed by systemd-tmpfiles?

**Comment by nh2** [comment]
> Any chance you could run your services with `PrivateTmp=yes`? That way, they also shouldn't be removed by systemd-tmpfiles…

I will have to investigate that for my own program, but the problem with it is that _arbitrary_ programs may have that assumption that their temp dirs must not disappear from under them, and it's a big task to read all the the code.

**Comment by flokli** [comment]
There's quite some distros (RHEL, CentOS, Ubuntu, …) that also remove contents in `/tmp` regularily, not just on boot, so I wouldn't consider occasional cleaning up of `/tmp` that unusual.

I didn't check how these scripts would behave in your `/tmp/ourservice/ourprogram-temp` scenario, but if you create multiple files a directory structure, and these stay around for longer than 10 days, I wouldn't consider them temporary, but "state", or "runtime files" (so they'd belong to `/var/lib/$myservice`, or `/run/$myservice` IMHO) ;-)

We might want to make `q` overridable with `q!` upstream, or if that doesn't fly, document how to override the systemd-provided tmpfiles.

**Comment by nh2** [comment]
> these stay around for longer than 10 days, I wouldn't consider them temporary, but "state", or "runtime files"

They are certainly temp files, just that the application maintains them in subdirectories; it would create:

````
/tmp/ourservice/ourprogram-temp/tmpfile1
/tmp/ourservice/ourprogram-temp/tmpfile2
/tmp/ourservice/ourprogram-temp/...
```

and `tmpfile1` and `tmpfile2` would live somewhere between 1 second and 5 hours and then be deleted.

But that does not bump the `mtime`/`ctime` of `/tmp/ourservice`.

**Comment by nh2** [comment]
> There's quite some distros (RHEL, CentOS, Ubuntu, …) that also [remove contents in `/tmp` regularily](https://serverfault.com/questions/377348/when-does-tmp-get-cleared/377349), not just on boot, so I wouldn't consider occasional cleaning up of `/tmp` that unusual.

I don't think that is the case.

On my Ubuntu 18.04, `/tmp` does not have an `age` column set, so it should not get cleared at all:

```
% grep ' /tmp ' /usr/lib/tmpfiles.d/tmp.conf
D /tmp 1777 root root -
```

Same for 20.04.

All of the Debian family distros change it from the default, because debian upstream does it:

https://sources.debian.org/patches/systemd/241-7%7Edeb10u4/debian/Bring-tmpfiles.d-tmp.conf-in-line-with-Debian-defaul.patch/

**Comment by flokli** [comment]
If you can't change your applications, I propose the same workaround as suggested in https://github.com/NixOS/nixpkgs/pull/85368#issuecomment-623940109 would apply here (but with `tmp.conf`, of course).

Fedora does ship the same `tmp.conf` - so the same surprising behaviour should be expected there, too - I don't see much of a reason to patch it downstream the debian way.
