### ISSUE TITLE
tig: fails to run on Darwin

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#8660]
```console
benley@clango:~$ tig
tig: Failed to create status window
```

After a bit of googling I get the impression that people think this may be a flaw in ncurses, but I haven't managed to pin it down.  Something to do with tig trying to create windows that are 0 lines high, which the ncurses api claims to allow but the code doesn't, maybe?

This happens in the unstable channel as well as master as of 806291b.  I also verified that it's not fixed upstream in the tig source.

**Comment by matthiasbeyer** [comment]
Can you provide more information? GDB logs, etc? I'm not able to test on darwin, but I try to help whereever I can...

**Comment by benley** [comment]
I'll see if I can produce more debugging info later, once I'm back home where my mac is.

**Comment by necramirez** [comment]
I also get this error when I installed tig from nix-env.

I installed tig from the Git repo (https://github.com/jonas/tig), and it works fine.

**Comment by matthiasbeyer** [comment]
@necramirez Did you install the very same release or did you use latest master (or something) from the repo?

**Comment by necramirez** [comment]
I just did a `nix-env -i tig`, so it's `tig-2.1.1`, as of now.

**Comment by matthiasbeyer** [comment]
But how did you install it from the git repo?

**Comment by necramirez** [comment]
I followed the instructions here:  https://github.com/jonas/tig/blob/master/INSTALL.adoc
```
$ git clone https://github.com/jonas/tig.git
$ make configure
$ ./configure --prefix=$HOME/local
$ make
$ make install
```

**Comment by matthiasbeyer** [comment]
Can you try to checkout the tag for 2.1.1 in your tig clone and `configure --prefix... && make && make install` from there? Does it fail like when installing via `nix-env`?

**Comment by necramirez** [comment]
Just tested the `tig-2.1.1` tag and it works just fine.

**Comment by matthiasbeyer** [comment]
Okay, so it is an issue with the package definition. Someone with a darwin machine has to investigate, I cannot as I do not have a darwin machine, sorry. The information posted in this issue should be helpful anyways.
