### ISSUE TITLE
nvidia_x11 uses non-standard ICD filename

### ISSUE THREAD

**Issue by KaneTW** [NixOS/nixpkgs#86620]
nvidia_x11 uses a non-standard ICD filename: nvidia.json instead of nvidia_icd.json. This breaks applications that rely on nvidia_icd.json existing (e.g. NixGL).

https://github.com/NixOS/nixpkgs/blob/f2d1041b6b5ba35662d1ffd53d2cdfd89951807e/pkgs/os-specific/linux/nvidia-x11/builder.sh#L76

**Comment by prusnak** [comment]
@KaneTW Can you try to send a pull request with a fix?

**Comment by veprbl** [comment]
cc @baracoder @eadwu

**Comment by eadwu** [comment]
I'll make a PR tomorrow if no one ends up making one by then. Currently setting my machine up after a recent filesystem bork.

**Comment by baracoder** [comment]
I think we would need to also add an arch suffix, like in the mesa package
```
/nix/store/iwwfzyd72a37nbfmq0p7pxqxan5zj1hk-mesa-19.1.3-drivers/share/vulkan/icd.d
intel_icd.x86_64.json  radeon_icd.x86_64.json
```
The nvidia package contains both 32 and 64 bit version of the associated library file.

**Comment by eadwu** [comment]
nixGL seems to rely on the current path [1] so the update would actually break it.

[1] https://github.com/guibou/nixGL/commit/a02035314b3bfcea855f465bf7ff0ad0e4a665f1

**Comment by veprbl** [comment]
cc @guibou regarding https://github.com/NixOS/nixpkgs/issues/86620#issuecomment-623679718

**Comment by baracoder** [comment]
:thinking: According to [this](https://vulkan.lunarg.com/doc/sdk/1.0.61.1/windows/LoaderAndLayerInterface.html)  the file names don't have to to follow any schema

> The following section discusses the details of the ICD Manifest JSON file format. The JSON file itself does not have any requirements for naming. The only requirement is that the extension suffix of the file is ".json".

**Comment by guibou** [comment]
Thank for the notification. I'll update nixGL so it wildcard on `nvidia*.json` instead.

**Comment by eadwu** [comment]
So I'll keep the file as `nvidia_icd.json` if it's bundled while for `i686-linux`, I'll create `nvidia-icd.i686.json`. I'm not sure if there's a point for creating both files for x86_64 since the file contents are the same.
