### ISSUE TITLE
unity-editor from unity3d cannot find libnss3.so

### ISSUE THREAD

**Issue by setzer22** [NixOS/nixpkgs#86639]
**Describe the bug**
I've tried installing unity3d, both from 20.03 and unstable channels, but in both cases running `unity-editor` fails with the following error: 

```
/nix/store/8wv3wak51bjb3bmws76jrnbxsmfl5hl0-unity-editor-2018.3.0xf2/opt/Unity/Editor/Unity: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Add `unity3d` to system packages in `/etc/nixos/configuration.nix`
2. Run `nixos-rebuild switch`
3. In a terminal, run `unity-editor`

**Expected behavior**
The program should start

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1619.ab3adfe1c76 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1619.ab3adfe1c76"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by setzer22** [comment]
I thought an strace might also be relevant in this case: https://pastebin.com/D5Fuyyxf

In particular, by looking at this, it seems the nss package path in the nix store is being checked, but only for other files. When it actually tries to find libnss3.so, it only checks the two following locations:

- `/nix/store/8wv3wak51bjb3bmws76jrnbxsmfl5hl0-unity-editor-2018.3.0xf2/opt/Unity/Editor/libnss3.so`
- `/nix/store/bwzra330vib0ik4d3l8rq6gp6y2ah1fr-glibc-2.30/lib/libnss3.so`

**Comment by veprbl** [comment]
cc @tesq0

**Comment by antonsmetanin** [comment]
I have the same problem.
After researching it for a while I found that libnss3.so seems to be a dependency of libcef.so. Even though the Unity executable has the correct path to libnss3.so in its RUNPATH, libcef.so only has $ORIGIN in its RPATH. I guess this is why it's looking for libnss3.so in the same directory the executable is located in.

**Comment by veprbl** [comment]
Can you try running with `LD_DEBUG=libs`?

**Comment by antonsmetanin** [comment]
That's what I originally did to find the root of the problem.
Here's the output:
```
     11617:	find library=libnss3.so [0]; searching
     11617:	 search path=/nix/store/645yd4gr2zvgxd9sjsj7w88f04hwr4f1-unity-editor-2018.3.0xf2/opt/Unity/Editor		(RUNPATH from file /nix/store/645yd4gr2zvgxd9sjsj7w88f04hwr4f1-unity-editor-2018.3.0xf2/opt/Unity/Editor/Unity)
     11617:	  trying file=/nix/store/645yd4gr2zvgxd9sjsj7w88f04hwr4f1-unity-editor-2018.3.0xf2/opt/Unity/Editor/libnss3.so
     11617:	 search cache=/nix/store/jx19wa4xlh9n4324xdl9rjnykd19mmq3-glibc-2.30/etc/ld.so.cache
     11617:	 search path=/nix/store/jx19wa4xlh9n4324xdl9rjnykd19mmq3-glibc-2.30/lib		(system search path)
     11617:	  trying file=/nix/store/jx19wa4xlh9n4324xdl9rjnykd19mmq3-glibc-2.30/lib/libnss3.so
     11617:	
/nix/store/645yd4gr2zvgxd9sjsj7w88f04hwr4f1-unity-editor-2018.3.0xf2/opt/Unity/Editor/Unity: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

If I patchelf libcef.so with the correct RPATH manually, Unity runs but segfaults. I have to set write permissions first, though. Could it be the issue? I tried adding `chmod +w "$1"` to the default.nix file, just before `patchelf --set-rpath "$rpath" "$1"` but it didn't seem to help: the permissions on libcef.so are still 555 after rebuilding, and RPATH is still $ORIGIN.

**Comment by antonsmetanin** [comment]
Okay, so the problem is in this line:
https://github.com/NixOS/nixpkgs/blob/cdfb8286d93a073fba893a2b187ecfcb89888092/pkgs/development/tools/unity3d/default.nix#L66

The regular expression does not match for some reason.

**Comment by veprbl** [comment]
I don't understand how these lines work:
```
https://github.com/NixOS/nixpkgs/blob/cdfb8286d93a073fba893a2b187ecfcb89888092/pkgs/development/tools/unity3d/default.nix#L89-L90
```
The comment says that it excludes "PlaybackEngines", but the actual call to find includes only files with the name "PlaybackEngines". Should the condition be `! -name PlaybackEngines` instead?

**Comment by antonsmetanin** [comment]
No, that line works correctly. The `-prune` switch does the exclusion.

**Comment by antonsmetanin** [comment]
The regular expression does not match because `file -b` for libcef.so gives the following result when executed in the build script:
```
ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=5229b493dda90f6790b0f97eca1ed3743c30d02f, not stripped
```

And this is when I run the command manually after the build:
```
ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5229b493dda90f6790b0f97eca1ed3743c30d02f, not stripped
```

What could possibly cause this?

**Comment by veprbl** [comment]
@antonsmetanin Can you calculate hashes before/after? Are the versions of `file` identical in both environments?

**Comment by antonsmetanin** [comment]
MD5 hash of libcef.so is the same in both cases: `6acc3db46e8951bceaa21dba80194b87`
`file` versions are the same, although their magic file paths are different:
```
file-5.38
magic file from /nix/store/xgsfk0ld6w8w13qmcmlh8jbsi395n9gy-file-5.38/share/misc/magic
```

```
file-5.38
magic file from /etc/magic:/usr/share/misc/magic
```

Their binaries' MD5 hashes are also different.

I tried running `file -b` on libcef.so using the magic files from /nix/store: `-m /nix/store/xgsfk0ld6w8w13qmcmlh8jbsi395n9gy-file-5.38/share/misc/magic`. It didn't change the output:
```
ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5229b493dda90f6790b0f97eca1ed3743c30d02f, not stripped
```

On the other hand, running the binary from /nix/store: `/nix/store/xgsfk0ld6w8w13qmcmlh8jbsi395n9gy-file-5.38/bin/file -b` prints
```
ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=5229b493dda90f6790b0f97eca1ed3743c30d02f, not stripped
```

**Comment by antonsmetanin** [comment]
I've been able to successfully run Unity Editor by downgrading `file` to this commit:
https://github.com/NixOS/nixpkgs/blob/ecff7d3a56abb41d4349e48418d9c582db92b0f1/pkgs/tools/misc/file/default.nix

Still have no idea why the latest version determines the file type incorrectly.

**Comment by antonsmetanin** [comment]
I've been able to successfully run Unity Editor by downgrading `file` to this commit:
https://github.com/NixOS/nixpkgs/blob/ecff7d3a56abb41d4349e48418d9c582db92b0f1/pkgs/tools/misc/file/default.nix

Still have no idea why the latest version determines the file type incorrectly.

**Comment by Orisphera** [comment]
Sorry for necroposting, but:
IIRC Unity 3D uses Compiz, but it's not available on NixOS. How did you try to run it?
