### ISSUE TITLE
ghcjs broken?

### ISSUE THREAD

**Issue by spl** [NixOS/nixpkgs#8663]
I've tried and failed to build ghcjs on Mac OS X and Linux at several points over the last few weeks. During this time, I noticed fbe153989ccd8ba4955e16bd44e2ffcc9a9710cc which marked the package broken and af21595ecaf0003496933b46beb9c841d828ca4e which claimed to fix it. There was additional work in 942f5070107213a884e2fe9cb987abd07df15aad to upgrade it. Yet I'm still seeing the same issue noted in fbe153989ccd8ba4955e16bd44e2ffcc9a9710cc when I've tried to build it:

```
Configuring ghcjs-0.1.0...
Setup: At least the following dependencies are missing:
aeson >=0.7 && <0.9, syb ==0.4.*, text-binary ==0.1.*
builder for ‘/nix/store/b234ajazd7v2qdl6scxzpipf5l5251c9-ghcjs-0.1.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/j17bjr4i4fs4661x8495ddj8kxang5g6-ghcjs-0.1.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/j17bjr4i4fs4661x8495ddj8kxang5g6-ghcjs-0.1.0.drv’ failed
```

The above is with a fresh install of Nix 1.9 and a fresh checkout of nixpkgs (HEAD was 4b836fb680116ad5fa85ea2bb43ffeff3be4ec53).

**Comment by spl** [comment]
Hmm. I realized I might have not used the nixpkgs I thought I did. I'll try again just to be sure.

**Comment by spl** [comment]
It probably was the old nixpkgs. I rebuilt with 6bb0436bb3b773b741d842d27f1b7a84596891e8 and failed at attoparsec:

```
Preprocessing test suite 'tests' for attoparsec-0.13.0.0...
[ 1 of 25] Compiling QC.Rechunked     ( tests/QC/Rechunked.hs, dist/build/tests/tests-tmp/QC/Rechunked.dyn_o )
[...]
[25 of 25] Compiling Main             ( tests/QC.hs, dist/build/tests/tests-tmp/Main.dyn_o )
Linking dist/build/tests/tests ...
running tests
Running 1 test suites...
Test suite tests: RUNNING...
bs:
  anyWord8: [OK, passed 100 tests]
[...]
  members: [OK, passed 100 tests]
  nonmembers: [Failed]
*** Failed! Exception: 'Prelude.chr: bad argument: 140737122496936' (after 11 tests and 1 shrink):
"xA\EMbR"
"J\SYN\ETBq"
(used seed -2009180548307453083)

         Properties   Total
 Passed  64           64
 Failed  1            1
 Total   65           65
Test suite tests: FAIL
Test suite logged to: dist/test/attoparsec-0.13.0.0-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for ‘/nix/store/v5gbfalxp6wvpj2f4hjmak3aq27p2cqp-haskell-attoparsec-0.13.0.0.drv’ failed with exit code 1
```

This seems to be due to upstream: bos/attoparsec#103

**Comment by spl** [comment]
The attoparsec bug is nondeterministic, so I'm now continuing with the rest of the build.

**Comment by peti** [comment]
@spl, please report the attoparsec bug upstream.

ghcjs builds fine on Linux: http://hydra.nixos.org/job/nixpkgs/trunk/haskell.compiler.ghcjs.x86_64-linux. On Darwin, there appears to be a problem in recent versions: http://hydra.nixos.org/job/nixpkgs/trunk/haskell.compiler.ghcjs.x86_64-darwin.

**Comment by spl** [comment]
Yes, it appears to be a false alarm. ghcjs did build with the latest nixpkgs. I was unintentionally using the one that came with Nix 1.9.

**Comment by peti** [comment]
@spl, please do report the attoparsec failures upstream, though!

**Comment by spl** [comment]
@peti It's already been reported. I linked to the issue above.

**Comment by peti** [comment]
Very cool, thank you!
