### ISSUE TITLE
jetbrains.rider: crash at startup with version 2020.1

### ISSUE THREAD

**Issue by mausch** [NixOS/nixpkgs#86657]
jetbrains.rider 2020.1 ( https://github.com/NixOS/nixpkgs/commit/d7df6591263a954fefe0e074c96e02ea3317f578 ) crashes at startup, stack trace: https://gist.github.com/mausch/c144b9e110d02f36c56d02a3f267e037

Previous versions work fine.

@mkg20001
@miltador

**Comment by pushkinma** [comment]
2020.1.**1** too

**Comment by Elyhaka** [comment]
Can reproduce too

**Comment by Elyhaka** [comment]
Giving more context to this issue: https://youtrack.jetbrains.com/issue/RIDER-35932 

It seems there is an issue while loading dotnet environement at boot. Unfortunatly, the PR that is supposedly fixing this (https://github.com/NixOS/nixpkgs/pull/86227) is not fixing it (same issue).

**Comment by mkg20001** [comment]
Rider seems to work for me - fixed?

**Comment by DamienCassou** [comment]
2020.2 works for me.

**Comment by mausch** [comment]
yep https://github.com/NixOS/nixpkgs/pull/86227 actually did fix the issue, and was eventually merged :+1:
