### ISSUE TITLE
request: GitQlient

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#86702]
**Project description**
GitQlient: Multi-platform Git client written with Qt. 

**Metadata**

https://github.com/francescmm/GitQlient

A non-serious start: https://github.com/colemickens/nixpkgs/commits/gitqlient

* homepage URL: https://github.com/francescmm/GitQlient
* source URL: https://github.com/francescmm/GitQlient
* license: lgpl2
* platforms: unix, linux, darwin, ...

**Comment by colemickens** [comment]
Alright, it builds and launchs on my machine but the build output bin path is weird and the GUI is almost unusable, it doesn't look right.

**Comment by sikmir** [comment]
Up.

**Comment by sikmir** [comment]
1.3.0 works good for me.
