### ISSUE TITLE
nixos/modules/security/acme: Specify SyslogIdentifier= for systemd services

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#86797]
By default, systemd services for the ACME modules log messages with a cumbersome `SYSLOG_IDENTIFIER` such as:
- `0z8ay39fv3nq5sry037gkh0ir25yqng0-unit-script-acme-selfsigned-example.com-start`.
-  `6nbb5ilfs4lw8dp940w1wr4i0581v6a7-acme-start`

Could we specify an explicit `SyslogIdentifier=` with [`systemd.services.<name>.serviceConfig`](https://nixos.org/nixos/manual/options.html#opt-systemd.services._name_.serviceConfig) to use easier to use identifiers such as :
- `acme-selfsigned-example.com`
- `acme-example.com`

I suggest this because of an undesired behavior in systemd (<https://github.com/systemd/systemd/issues/2913>). Some journal fields such as `_SYSTEMD_UNIT` are not consistently attached to the journal logs making it difficult to work with the journal.

Notify maintainers
@abbradar @fpletz @globin @m1cr0man

**Comment by emilazy** [comment]
cc @NixOS/acme 

It might be better to systematically set these in the systemd machinery rather than playing whack-a-mole with every service (#86911, #86915)?

**Comment by bjornfor** [comment]
An alternative to setting SyslogIdentifier is using service programs with short basenames. E.g. using writeShellscriptBin instead of writeShellscript.

**Comment by flokli** [comment]
`makeJobScript` from `nixos/modules/system/boot/systemd.nix` explicitly says:
```
        # The derivation name is different from the script file name
        # to keep the script file name short to avoid cluttering logs.
```

The script file names are short:
`/nix/store/msci5xyl3lpsajdli80swrhpy5ivwwn8-unit-script-prepare-kexec-start/bin/prepare-kexec-start`

`systemd.exec(5)` says about `SyslogIdentifier=`:
```
       SyslogIdentifier=
           Sets the process name ("syslog tag") to prefix log lines sent to the logging system or the kernel log
           buffer with. If not set, defaults to the process name of the executed process. This option is only
           useful when StandardOutput= or StandardError= are set to journal or kmsg (or to the same settings in
           combination with +console) and only applies to log messages written to stdout or stderr.
```

It seems systemd for some reason the whole binary name is picked for `SyslogIdentified=`, not `prepare-kexec-start`. If we could get this to work, we wouldn't need to manually fixup each module…

**Comment by bjornfor** [comment]
I think this got fixed with https://github.com/nixos/nixpkgs/pull/85428.

**Comment by datafoo** [comment]
> I think this got fixed with #85428.

It definitely helps but there are still the `-pre-start`, `-start`, `-post-start`, `-reload`, `-pre-stop` and `-post-stop` suffixes in the `SYSLOG_IDENTIFIER`.

**Comment by datafoo** [comment]
We could modify [`nixos/modules/system/boot/systemd.nix`](https://github.com/serokell/nixpkgs/blob/master/nixos/modules/system/boot/systemd.nix) to set `systemd.services.<name>.serviceConfig.SyslogIdentifier` without the `-pre-start`, `-start`, `-post-start`, `-reload`, `-pre-stop` and `-post-stop` suffixes.

However, this is going to be a matter of personal preference.

@kirelagin @lheckemann : what do you think after your work on #85428?

**Comment by lheckemann** [comment]
IMHO removing the hash is good enough and the suffixes would be good to keep to make it clear which part of a unit is producing the output.

**Comment by datafoo** [comment]
> IMHO removing the hash is good enough and the suffixes would be good to keep to make it clear which part of a unit is producing the output.

That makes sense
