### ISSUE TITLE
Node.js module PM2

### ISSUE THREAD

**Issue by pingpwned** [NixOS/nixpkgs#86838]
**Project description**
 _Production process manager for Node.js applications with a built-in load balancer._

**Metadata**

* homepage URL: https://pm2.keymetrics.io/
* source URL: https://github.com/Unitech/pm2
* license: [gnu-apgl](https://github.com/Unitech/pm2/blob/master/GNU-AGPL-3.0.txt)
* platforms: unix, linux, darwin, ...

**Comment by jtojnar** [comment]
Resolved by https://github.com/NixOS/nixpkgs/pull/99992
