### ISSUE TITLE
syslinux broken on i686, blocking nixos-unstable

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#86846]
**Describe the bug**
https://hydra.nixos.org/build/118203954/nixlog/2

**To Reproduce**
`nix-build nixos/release-combined.nix --arg supportedSystems '["i686-linux"]' -A nixpkgs.syslinux`

Bisect reveals a09878c2056867fea2fa74914d6af8570cdfd870 #85094 as the cause

cc @ajs124 @peterhoeg :wave:

**Comment by ajs124** [comment]
Seems like I only tested this on x86_64… I'll see what I can find.

**Comment by ajs124** [comment]
A quick and dirty fix would be something like:
```
diff --git a/pkgs/os-specific/linux/syslinux/default.nix b/pkgs/os-specific/linux/syslinux/default.nix
index 06b31302eb8..afcbcffad8d 100644
--- a/pkgs/os-specific/linux/syslinux/default.nix
+++ b/pkgs/os-specific/linux/syslinux/default.nix
@@ -70,6 +70,7 @@ stdenv.mkDerivation {
     "DATADIR=$(out)/share"
     "MANDIR=$(out)/share/man"
     "PERL=perl"
+    (stdenv.lib.optionalString stdenv.isi686 "bios")
   ];
 
   doCheck = false; # fails. some fail in a sandbox, others require qemu
```

I'm not sure if I can come up with anything better in any reasonable timeframe, tbh.

**Comment by peterhoeg** [comment]
>   I'm not sure if I can come up with anything better in any reasonable
>   timeframe, tbh.

Looks sensible. Opening a PR?
