### ISSUE TITLE
haskell-updates: Syntax error in autogenerated haskell-packages.nix

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#86904]
**Describe the bug**

As of f617f240d, `haskell-packages.nix` contains a syntax error in line `3443`.

The Package `ConcurrentUtils` introduced a dependency on a package called `assert`. Which is a protected keyword in nix.

See [hydra](https://hydra.nixos.org/jobset/nixpkgs/haskell-updates#tabs-errors) for the error message.

**Notify maintainers**
@peti

**Comment by maralorn** [comment]
Fixed

**Comment by peti** [comment]
Thanks for the heads-up!
