### ISSUE TITLE
nixos/postgresql: Specify SyslogIdentifier= for the systemd service

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#86911]
By default, the systemd service for the PostgreSQL module logs messages with a cumbersome `SYSLOG_IDENTIFIER` such as `01vhcnp2c1jr9vyla2qlqnc35lc3jv1b-unit-script-postgresql-start`.

Could we specify an explicit `SyslogIdentifier=` with [`systemd.services.<name>.serviceConfig`](https://nixos.org/nixos/manual/options.html#opt-systemd.services._name_.serviceConfig) to use an easier to use identifier such as `postgresql`?

I suggest this because of an undesired behavior in systemd (<https://github.com/systemd/systemd/issues/2913>). Some journal fields such as `_SYSTEMD_UNIT` are not consistently attached to the journal logs making it difficult to work with the journal.

Notify maintainers
@thoughtpolice @danbst

**Comment by flokli** [comment]
Let's try to fix this more globally as proposed in https://github.com/NixOS/nixpkgs/issues/86797#issuecomment-629872567.

**Comment by bjornfor** [comment]
I think this got fixed with https://github.com/nixos/nixpkgs/pull/85428.
