### ISSUE TITLE
channels do not advance? (e.g. nixos-unstable-small)

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#86922]
**Describe the bug**
On hydra [unstable-small](https://hydra.nixos.org/jobset/nixos/unstable-small) appears to build fine, but the channel does not advance ?

**Comment by doronbehar** [comment]
Same with `unstable`, something is blocking it...

**Comment by xaverdh** [comment]
Only `nixpkgs-*` channels appear to make progress, although the `tested` jobs for the other channels do succeed. I also updated my system directly against a `nixpkgs` commit from one of the succeeding builds, it works just fine (everything was in cache, as expected).

**Comment by xaverdh** [comment]
So something in the channel update mechanism is broken I guess? Who do you ping for this?

**Comment by xaverdh** [comment]
Ok, judging from the [channel-script repo](https://github.com/NixOS/nixos-channel-scripts):
cc  @grahamc

**Comment by xaverdh** [comment]
The unstable-small channel just updated, unstable is still stuck.

**Comment by peterhoeg** [comment]
A workaround for people using a local checkout of nixpkgs is to use the commit id for the most recent completed evaluation instead of the channel name. For unstable as of right now that 683c68232e9.

**Comment by vcunat** [comment]
They don't even need a local checkout, e.g.:
```bash
nixos-rebuild -I nixpkgs=https://github.com/nixos/nixpkgs/archive/683c682.tar.gz ...
```

**Comment by i077** [comment]
`nixos-unstable` advanced to [`683c682`](https://github.com/NixOS/nixpkgs/commit/683c68232e91f76386db979c461d8fbe2a018782) 3 hours ago.
