### ISSUE TITLE
Some packages will no longer build with Inkscape 1.0

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#86930]
After https://github.com/NixOS/nixpkgs/pull/85169, these packages will no longer build:

- [ ] adapta-gtk-theme
- [ ] arx-libertatis – https://github.com/arx/ArxLibertatis/pull/256, https://github.com/dm0-/ArxLibertatis/commit/60faf97edaba362ba1a8e1280766e102e48c7726#diff-15a99766ff4ff7cc41f6b4c436ceb63f
- [x] emojione fixed by https://github.com/NixOS/nixpkgs/pull/97862
- [ ] gnome3.gnome-documents – https://gitlab.gnome.org/GNOME/gnome-documents/-/merge_requests/31
- [ ] mojave-gtk-theme
- [ ] numix-solarized-gtk-theme
- [x] plata-theme
- [x] pantheon.elementary-icon-theme https://github.com/NixOS/nixpkgs/pull/87136
- [ ] dblatex https://sourceforge.net/p/dblatex/dblatex/merge-requests/4/
- [x] twemoji-color-font – https://github.com/eosrei/twemoji-color-font/pull/82 & https://github.com/eosrei/twemoji-color-font/pull/90, fixed by https://github.com/NixOS/nixpkgs/pull/97862
- [x] wpa_supplicant_gui – http://lists.infradead.org/pipermail/hostap/2020-May/041659.html, fixed in 219382bf283
- [ ] arc-theme
- [ ] bibata-cursors
- [ ] bibata-extra-cursors
- [ ] bibata-cursors-translucent
- [ ] capitaine-cursors
- [ ] fim
- [ ] mate-utils
- [x] numix-cursor-theme
- [ ] pop-gtk-theme

Please help creating patches and adding them to nixpkgs.

_Originally posted by @jtojnar in https://github.com/NixOS/nixpkgs/pull/85169#issuecomment-623995720_

cc `lib.concatMapStringsSep ", " (m: "@${m.github}") (lib.unique (lib.concatMap (p: p.meta.maintainers or []) [adapta-gtk-theme arx-libertatis emojione gnome3.gnome-documents mojave-gtk-theme numix-solariz`:
@romildo, @rnhmjoj, @abbradar, @hedning, @jtojnar, @worldofpeace, @offlinehacker, @tadfisher, @infinisil, @fgaz

**Comment by Infinisil** [comment]
Ripcord builds successfully on #83169 (f714685a3935abbfabbc86dfffad84e5cc9899b2), maybe the original failure was caused by the unfree license

**Comment by jtojnar** [comment]
Yes, https://github.com/NixOS/nixpkgs/commit/f714685a3935abbfabbc86dfffad84e5cc9899b2 re-added the old Inkscape. Ideally we could do without it.

**Comment by romildo** [comment]
What is the fix for the individual packages: just remove the `-z` or `--without-gui` option from the command line invocation of `inkscape`?

**Comment by jtojnar** [comment]
Remove `-z`/`--without-gui`, change `--export-png` to `--export-filename` (the name should have `.png` extension) were the changes I encountered so far.

**Comment by jtojnar** [comment]
Apparently, the ripcord failure was propagated from `twemoji-color-font`.

**Comment by tadfisher** [comment]
`plata-theme` seems to build fine at least since 0.9.7, so I think it can be checked off.

**Comment by stephaneyfx** [comment]
`numix-cursor-theme` was fixed in #102007 .

**Comment by prusnak** [comment]
@jtojnar does it still make sense to have this issue open? (after merging inkscape 1.0.1 into master which re-introduced the previously used CLI interface)

**Comment by FliegendeWurst** [comment]
All of the listed items build on 21.11, except for gnome-documents (which is broken for unrelated reasons).
