### ISSUE TITLE
vimPlugins: wombat256 plugin wont build because the builder tries to unpack a .vim file

### ISSUE THREAD

**Issue by lihop** [NixOS/nixpkgs#8694]
**nixpkgs version**: nixos-unstable (rev: 4e5e44140b)
**configuration**: [~/.nixpkgs/config.nix](https://github.com/lihop/dotfiles/blob/master/nix/.nixpkgs/config.nix)
**steps**:
```
nix-env -f ~/git/nixpkgs -i vim-env
```
**error**:
```
installing ‘vim-env’
these derivations will be built:
  /nix/store/34na0rlhbj9sc4y0yy9f2ccp1ngnr0zw-vimplugin-wombat256.drv
  /nix/store/s8s0yvmcwazrz8lcpy32xr9z09ja2ckj-vimrc.drv
  /nix/store/kgxdpzimvak8ilsjzj735lv7ifaj2ra7-vim.drv
  /nix/store/kkfpdwbf5j14jclr2fps63an0x27clm3-vim-env.drv
building path(s) ‘/nix/store/v8mfqibna3zspr6pz70299ipd3cgdjpq-vimplugin-wombat256’
unpacking sources
unpacking source archive /nix/store/8601hil0via1ad94zbvri987fm7cc9xy-wombat256mod.vim
do not know how to unpack source archive /nix/store/8601hil0via1ad94zbvri987fm7cc9xy-wombat256mod.vim
builder for ‘/nix/store/34na0rlhbj9sc4y0yy9f2ccp1ngnr0zw-vimplugin-wombat256.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/s8s0yvmcwazrz8lcpy32xr9z09ja2ckj-vimrc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kgxdpzimvak8ilsjzj735lv7ifaj2ra7-vim.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kkfpdwbf5j14jclr2fps63an0x27clm3-vim-env.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/kkfpdwbf5j14jclr2fps63an0x27clm3-vim-env.drv’ failed
```
If I remove the wombat256 plugin from my configuration, then vim-env builds fine.

Currently, wombat256 seems to be the only plugin in nixpkgs affected by this issue. However, I have auto-generated another plugin [here](https://github.com/lihop/nixpkgs/commit/f51184ecfa720a17e1b37c3136ef2708a4375d62) which is also affected.

What these two plugins have in common is that they are both using `fetchurl`, and are downloading `.vim` files rather than `zip` archives.

cc @jagajaga

**Comment by jagajaga** [comment]
Isn't it a better idea to download those plugins from github? And add them to `vim-plugin-names` as `github:vim-scripts/wombat256.vim`? Because I personally don't like fetching from vim site.
I can change the behavior to load them from vim-scripts repo.

**Comment by jagajaga** [comment]
Isn't it a better idea to download those plugins from github? And add them to `vim-plugin-names` as `github:vim-scripts/wombat256.vim`? Because I personally don't like fetching from vim site.
I can change the behavior to load them from vim-scripts repo.

**Comment by lihop** [comment]
@jagajaga Yes, downloading from github works well and is better I think.
I'll update wombat256 and use github when adding plugins from now on.
