### ISSUE TITLE
Sabaki SGF editor (Electron/Node)

### ISSUE THREAD

**Issue by dustinlacewell** [NixOS/nixpkgs#86970]
**Project description**
Sabaki is the most featureful SGF editor/viewer available. SGF is the file-format which backs game-records for the game Go/Baduk. Sabaki is also able to hook up to various Go playing backends such as the modern ML based AI engines.

Sabaki is Electron / Node based. 

I have tried to build it with node2nix, but the commands required for actually building Sabaki are not run. Sabaki is built with `npm run build`. I have tried to use nix-shell in conjunction with node2nix in order to run `npm run build` myself, and this works, the build process completes -- but the output is unpatched, resulting in "cannot find bash", etc.

I am not able to reason how to modify the node2nix artifacts to apply the correct patching required to get it to actually run. 

**Metadata**

* homepage URL: https://sabaki.yichuanshen.de/
* source URL: https://github.com/SabakiHQ/Sabaki
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by oati** [comment]
Why was this closed?
