### ISSUE TITLE
fwupd in nixos-20.03 is failing to apply some capsules

### ISSUE THREAD

**Issue by akotulski** [NixOS/nixpkgs#87000]
**Describe the bug**
Release in the stable branch is looping when applying capsule and failing.
It's a known issue that was fixed in the subsequent release (version 1.3.8)
https://github.com/fwupd/fwupd/issues/1756
https://github.com/fwupd/fwupd/issues/1764

**To Reproduce**
I ran following commands on my thinkpad t470s
1. `fwdupdmgr update`
2. restart computer and boot into firmware update
3. fwdupd got stuck and didn't apply the upgrade

**Expected behavior**
The fwdupd should finish

**Additional context**
I used fwupd from unstable and it succeeded (version 1.4)
```
nixpkgs.config.packageOverrides = pkgs: { fwupd = unstable.fwupd;}
```

**Notify maintainers**
@jtojnar 

**Metadata**
```
[:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1619.ab3adfe1c76 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(akotulski): `"nixos-unstable-20.09pre223023.fce7562cf46"`
 - channels(root): `"home-manager-20.03, nixos-20.03.1619.ab3adfe1c76, nixos-hardware, nixos-unstable-20.09pre223023.fce7562cf46"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
I guess #80101 could be backported, #82001 probably too. Even #83755 should be okay changes-wise but maybe too much of a pain.
