### ISSUE TITLE
VS Code: MS 

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#87064]
I'm trying to use MS Liveshare under VS Code, which is a proprietary thing, and comes with a binary. It's not one of the defined vscode extensions

It needs libstdc++.so:
```
-rwxr--r-- 1 wmertens users 86584 Apr 30 18:17 /home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent
$ ldd -d ~/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent
	linux-vdso.so.1 (0x00007ffd2e5ae000)
	libpthread.so.0 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libpthread.so.0 (0x00007f834c1b5000)
	libdl.so.2 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libdl.so.2 (0x00007f834c1b0000)
	libstdc++.so.6 => not found
	libm.so.6 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libm.so.6 (0x00007f834c070000)
	libgcc_s.so.1 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libgcc_s.so.1 (0x00007f834c056000)
	libc.so.6 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libc.so.6 (0x00007f834be97000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib64/ld-linux-x86-64.so.2 (0x00007f834c1d8000)
undefined symbol: _ZTVN10__cxxabiv116__enum_type_infoE, version CXXABI_1.3	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZTVSt15basic_stringbufIcSt11char_traitsIcESaIcEE, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZTTSt18basic_stringstreamIcSt11char_traitsIcESaIcEE, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZNSt8ios_base4InitD1Ev, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZNSs4_Rep11_S_terminalE, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZTTSt13basic_fstreamIcSt11char_traitsIcEE, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZTVSt15basic_streambufIcSt11char_traitsIcEE, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
undefined symbol: _ZNSs4_Rep20_S_empty_rep_storageE, version GLIBCXX_3.4	(/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent)
```

So I try providing it:
```
$ LD_LIBRARY_PATH=/nix/store/jy89v2q2zv074mvw91jgqcvkmk7yqx69-gcc-9.3.0-lib/lib ldd -d ~/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent 
	linux-vdso.so.1 (0x00007ffe51f2a000)
	libpthread.so.0 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libpthread.so.0 (0x00007fa9e77cd000)
	libdl.so.2 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libdl.so.2 (0x00007fa9e77c8000)
	libstdc++.so.6 => /nix/store/jy89v2q2zv074mvw91jgqcvkmk7yqx69-gcc-9.3.0-lib/lib/libstdc++.so.6 (0x00007fa9e75e7000)
	libm.so.6 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libm.so.6 (0x00007fa9e74a7000)
	libgcc_s.so.1 => /nix/store/jy89v2q2zv074mvw91jgqcvkmk7yqx69-gcc-9.3.0-lib/lib/libgcc_s.so.1 (0x00007fa9e748d000)
	libc.so.6 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libc.so.6 (0x00007fa9e72ce000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib64/ld-linux-x86-64.so.2 (0x00007fa9e77f0000)
```

Seems ok! But:
```
$ LD_LIBRARY_PATH=/nix/store/jy89v2q2zv074mvw91jgqcvkmk7yqx69-gcc-9.3.0-lib/lib ~/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent 
bash: /home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent: No such file or directory
```

Strace doesn't help:
```
$ LD_LIBRARY_PATH=/nix/store/jy89v2q2zv074mvw91jgqcvkmk7yqx69-gcc-9.3.0-lib/lib strace -f ~/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent 
execve("/home/wmertens/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104/dotnet_modules/vsls-agent", ["/home/wmertens/.vscode/extension"...], 0x7ffc9e63d988 /* 93 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++
```

LD_DEBUG also shows nothing, this seems to happen before ld is involved?

**Notify maintainers**
@eadwu @synthetica

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.4, NixOS, 20.09pre221814.10100a97c89 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(wmertens): `"home-manager, nixpkgs-20.09pre224255.e23f5308583"`
 - channels(root): `"nixos-20.09pre223023.fce7562cf46, nixos-hardware, nixpkgs-20.09pre221814.10100a97c89"`
 - nixpkgs: `/home/wmertens/.nix-defexpr/channels/nixpkgs`

**Comment by eadwu** [comment]
How about the interpreter? You can check via `file`.

**Comment by wmertens** [comment]
d'oh, I forgot about that. That made it run, and then I had to set `DOTNET_ROOT` to the path of `dotnetCorePackages.netcore_3_1`.

:thinking: since these packages update often, it's a bit of a drag to manage them through nix. How would I go about wrapping vscode so it fixes binaries automatically?

Perhaps a wrapper that provides the dotnet variable and scans the extensions at startup for all binaries and patches them if needed?

**Comment by eadwu** [comment]
If it's an executable, you should probably use a wrapper. I would assume that there is a variable that allows you to set DOTNET_ROOT, in which you can manage your vscode configuration through Nix.

**Comment by wmertens** [comment]
This can patch the interpreters:

```sh
#!/usr/bin/env nix-shell
#! nix-shell -i sh -p patchelf gcc

# todo install 
    # checkNetCoreDeps  gcr liburcu openssl-1.0 krb5 icu zlib
    # checkKeyringDeps  gnome-keyring libsecret
    # checkBrowserDeps  desktop-file-utils xorg-xprop

# TODO env var for vscode location
find ~/.vscode/extensions/ -type f -perm -100 -print0 | xargs -0 file | \
	grep 'interpreter /lib' | cut -d: -f1 | while read f; do
	# TODO grab actual interpreter
	patchelf --set-interpreter /nix/store/bwzra330vib0ik4d3l8rq6gp6y2ah1fr-glibc-2.30/lib/ld-linux-x86-64.so.2 "$f"
	# TODO rpath other dependencies, libstdc++
done
```

It seems that the NixPkgs install is also missing some libraries, I get prompted to install them, explanations at https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/linux#install-linux-prerequisites

Since these packages are used by extensions, I think the best way is to wrap vscode to put the extra deps into LD_LIBRARY_PATH :-/

That, or create and update each extension definition in nixpkgs

**Comment by wmertens** [comment]
@eadwu I managed to get it working: https://discourse.nixos.org/t/vs-code-liveshare/7022/2

I wonder if something like this wrapper should be used by default for vscode? (not vscodium)

**Comment by eadwu** [comment]
Default for vscode, probably not. You can probably port the extension part with patchelf under a derivation under `vscode-extensions`, but the environment variables might take a bit more work. If no bash scripts/executables are called, I'm not sure anything can be done about it, but if there are, you can create a wrapper with `makeWrapper`.

**Comment by wmertens** [comment]
The thing is, this is the MS Live Share extension, proprietary from MS, updated several times per month. It would be very annoying to manage the extension from nixpkgs.

It is also almost all of the reason to run vscode instead of vscodium, so I think it would be good to make it easy for Nix users to have ms-vsls working.

Furthermore, there are several extensions that install binaries that need elf loaders, and those would be helped with a wrapper like this too.

**Comment by jul1u5** [comment]
Related issue: #41189

**Comment by wmertens** [comment]
closing in favor of #41189
