### ISSUE TITLE
Declarative partitioning with systemd-repart/growfs/makefs

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#87073]
Currently we are still manually partition block devices and formatting them with filesystems. However with systemd 245 there is support for declarative disk management. The question is do we need anything beyond a simple module + documentation to support this feature?

https://www.freedesktop.org/software/systemd/man/systemd-repart.html#
https://www.freedesktop.org/software/systemd/man/systemd-growfs.html#

**Comment by flokli** [comment]
I think we already have a lot of manual code doing this in bash in stage2. If https://github.com/NixOS/nixpkgs/issues/72401 is done, we could move all this logic to native implementations.

**Comment by srhb** [comment]
Still relevant to me.

**Comment by emilazy** [comment]
(I wish you could mark an issue as "never stale")

**Comment by xaverdh** [comment]
I think one issue is that `systemd-repart` only supports `gpt`?

**Comment by emilazy** [comment]
I think it’s fine for new, optional features to only support GPT disks, which have many advantages over MBR anyway and work with both UEFI and legacy BIOS systems.

**Comment by xaverdh** [comment]
> (I wish you could mark an issue as "never stale")

Or maybe the stale bot should implement some form of exponential backoff?

So when should `systemd-repart` be run? From stage-2 (or initrd even), or when the system is running?

**Comment by flokli** [comment]
Linking https://github.com/NixOS/nixpkgs/pull/74842#issuecomment-800681307, as it seems to be related.

**Comment by flokli** [comment]
Linking https://github.com/NixOS/nixpkgs/pull/74842#issuecomment-800681307, as it seems to be related.

**Comment by flokli** [comment]
Also related, https://github.com/NixOS/nixpkgs/pull/120015 adds `systemd-makefs` to initrd

**Comment by weilbith** [comment]
This is exactly the feature I'm searching for. Looking forward to get this closed. 🤗

**Comment by blitz** [comment]
Is this solved with `image.repart`: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/image/repart.md ?

/cc @nikstur

**Comment by nikstur** [comment]
I believe this was solved with general systemd-repart support introduce in https://github.com/NixOS/nixpkgs/pull/214396
growfs and makefs were already supported before. @Mic92 please re-open if you thought about something different.
