### ISSUE TITLE
gst-rtsp-server pkgconfig file is buggy

### ISSUE THREAD

**Issue by dawagner** [NixOS/nixpkgs#87110]
/nix/store/.../lib/pkgconfig/gstreamer-rtsp-server-1.0.pc contains:
includedir=/nix/store/...//nix/store/.../include/gstreamer-1.0

Develop something using gst-rtsp-server and try to compile it with nix.

Applying the same patch as for all the other gstreamer packages (e.g. https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gstreamer/core/fix_pkgconfig_includedir.patch) Fixes the issue. I might submit a PR but I've not contributed to nixpkgs and am nix newbie.

cc @bkchr as the documented maintainer, cc @dtzWill as the latest commiter.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.16-300.fc29.x86_64, Fedora, 29 (Workstation Edition)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(deubeuliou): `"nixpkgs-20.09pre221814.10100a97c89"`
 - nixpkgs: `/home/deubeuliou/.nix-defexpr/channels/nixpkgs`

**Comment by bqv** [comment]
Please do!

**Comment by doronbehar** [comment]
This is fixed now, since https://github.com/NixOS/nixpkgs/commit/e30287c590de2d65595c47e142af08d8030ca240 .
