### ISSUE TITLE
Hash error when installing the Symbola font

### ISSUE THREAD

**Issue by Mayeu** [NixOS/nixpkgs#8717]
Hello,

In Nixos with the unstable channel I get the following hash error when trying to install the symbola font:
```
output path ‘/nix/store/86kr0hl5yvm377pjhmwyryvjkacqjd9b-Symbola.pdf’ should have sha256 hash ‘0jjjydb6c0glfb6krvdyi9kh5bsx9gz5w66j378bdqgkrvspl0d2’, instead has ‘1zmq1ijl0k5hrc6vpa2xp9n1x2zrrd7ng3jwc9yf0qsi3pmkpk0p’
```

Regards,

**Comment by vcunat** [comment]
Yeah, upstream just updates tarballs in place, so that breaks hashes every time...
