### ISSUE TITLE
keys.pub - cryptographic key management

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#87194]
**Project description**

Now that Keybase [is dead](https://keybase.io/blog/keybase-joins-zoom) (j/k), we could try to use https://keys.pub/ - a viable alternative without any bloat. 

**Metadata**

* homepage URL: https://keys.pub/
* source URL: https://github.com/keys-pub/keysd + https://github.com/keys-pub/app
* license: MIT
* platforms: unix (linux + darwin)

**Comment by cnnrro** [comment]
I'm still interested in this.

**Comment by tomodachi94** [comment]
> Unfortunately, this project is not currently being worked on. I may revisit this in the future, if you would like to sponsor development or hire me please reach out at gabriel@keys.pub.

Not sure if this is a good candidate because of this, particularly because this is cryptography-related.
