### ISSUE TITLE
No DNS until restarting firefox

### ISSUE THREAD

**Issue by mjlbach** [NixOS/nixpkgs#87221]
**Describe the bug**

This is a weird problem. Upon logging in, intermittently Firefox (which starts up automatically depending on if it was open when I last rebooted), refuses to connect to any webpages until I restart the browser entirely (opening a new tab does not help).

**To Reproduce**

Pertinent component of my configuration.nix. I've tried various permutations of these settings.

```
  # Enable networking
  networking.interfaces.enp0s31f6.useDHCP = true;
  # networking.interfaces.wlp2s0.useDHCP = true;
  networking.networkmanager.enable = true;
  networking.resolvconf.dnsExtensionMechanism = false;
```

1. Restart with Firefox open
2. Attempt to navigate to any webpage
3. curl ifconfig.co (confirm internet is working)
3. Restart Firefox (internet works)

**Expected behavior**
Firefox connects immediately to internet, or connects to the internet once the network has fully initialized.

**Comment by arianvp** [comment]
How exactly are you starting firefox on login?

**Comment by mjlbach** [comment]
I use KDE, so it restores open application open login. These is my journalctl logs

[internet_failure.log](https://github.com/NixOS/nixpkgs/files/4596416/internet_failure.log)

**Comment by aanderse** [comment]
I see this once in a while too, but never paid enough attention to recall exact details...

**Comment by vcunat** [comment]
From the log it seems that Firefox is starting even before some network stuff hasn't started up yet.  Perhaps it should just work even without waiting, but I can't immediately see what's the matter.

**Comment by colemickens** [comment]
I have experienced this randomly, on and off, for probably 2 years now. I have never managed to figure out what it is, but it does happen more often when I'm roaming wifi networks. If I wait long enough (too long) sometimes it recovers without restarting.

**Comment by arianvp** [comment]
My gut feeling is that it has something to do with `nscd`

I'd tell you to make a `systemd-analyze graph` plot to debug this; but nscd restarts like 3 times (For reasons i do not understand) during bootup which causes it not to get rendered in that graph :(

**Comment by ehmry** [comment]
I had this problem until I configured Firefox to use a local Privoxy instance as a proxy.

**Comment by sevenfourk** [comment]
new to nixos, configured X with dwm session and starting up chromium and st on login in xinitrc.

I can easily `dig` the world and `ping` anything, but chromium would not resolve anything, until i restart it.

**Comment by mjlbach** [comment]
Seems like this is a duplicate of #63754. Closing.
