### ISSUE TITLE
wvdial fails, broken wvstreams?

### ISSUE THREAD

**Issue by cheecheeo** [NixOS/nixpkgs#8725]
When I try to fire up wvdial it fails with the following error message:

```
% sudo /home/jchee/.nix-profile/bin/wvdial --config=$HOME/wvdial.conf Verizon4G
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
...
--> Modem initialized.
wvdial: utils/wvtask.cc:410: static void WvTaskMan::_stackmaster(): Assertion `magic_number == -0x123678' failed.
```

Searching around leads to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=674006 It looks like libwvstreams (a dependency of wvdial) doesn't compile correctly with newer gccs.

**Comment by pSub** [comment]
Upps, I did not intend to close the issue. Could you please check whether this issue is fixed now in master?

**Comment by cheecheeo** [comment]
@pSub commit 3523f41aa54029dbdd3e03b31f5266f6fe9813e0 works for me :+1:
