### ISSUE TITLE
Mount points are not created automatically on `nixos-rebuild switch`

### ISSUE THREAD

**Issue by glasserc** [NixOS/nixpkgs#87291]
**Describe the bug**
The documentation in https://nixos.org/nixos/manual/#ch-file-systems says that "Mount points are created automatically if they don’t already exist." However, they do not appear to be created on `nixos-rebuild switch`. (Maybe they are created at some other time or on reboot.)

**To Reproduce**
I wanted to access my NAS over NFS so I added this to my `configuration.nix`:

```
   fileSystems."/mnt/taos/backups" = {
    device = "taos.local:/volume1/backups";
    fsType = "nfs";
    options = [ "noauto" "intr" "norelatime" "noatime" ];
  };
```

Then, `sudo nixos-rebuild switch`.

Then, `mount /mnt/taos/backups`.

**Expected behavior**
A successful NFS mount.

**Actual behavior**
```
> sudo mount /mnt/taos/backups
[sudo] password for ethan: 
mount.nfs: mount point /mnt/taos/backups does not exist
```

**Additional context**
This line in the docs goes back to 2013 (https://github.com/NixOS/nixpkgs/commit/454e3477b6561e89a6b5cf98be1a6bcf6623e7af). I found https://github.com/NixOS/nixpkgs/commit/440b793a5b8fcd5250229ce9821e50a6f1065063#diff-221418a23a1340820bbec53797dbf70b which explains that systemd creates mount points automatically. Maybe I am mounting the filesystem wrong somehow?

**Notify maintainers**
`filesystems.nix` does not appear to have a `maintainers` attribute.. @flokli ?

**Metadata**
```
> nix-shell -p nix-info --run "nix-info -m"                                  ~
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/hzrq5ccamfkwdkl9gqqsh3ryprzvs044-bash-interactive-4.4-p23-dev
copying path '/nix/store/hzrq5ccamfkwdkl9gqqsh3ryprzvs044-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.30, NixOS, 20.03.1782.210d8624ac4 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(ethan): `""`
 - channels(root): `"nixos-20.03.1782.210d8624ac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
@glasserc [`systemd.mount#Where=`](https://systemd.network/systemd.mount.html#Where=) says the location is created.

Above Nix code creates the `/etc/fstab` entry, and [`systemd-fstab-generator`](https://systemd.network/systemd-fstab-generator.html) should translate `/etc/fstab` to `.mount` units:
> systemd-fstab-generator is a generator that translates /etc/fstab (see fstab(5) for details) into native systemd units early at boot and when configuration of the system manager is reloaded. This will instantiate mount and swap units as necessary.

We might not relead the system manager if only mountpoints are updated. After switching, do you see the new `.mount` unit? Does a `systemctl start ….mount` work?

Maybe it's also just the `mount` binary doesn't produce these directories…

**Comment by glasserc** [comment]
Should I be running `systemd-fstab-generator` by hand? I assume not..

I tried adding a new NFS mount and running `nixos-rebuild switch` and then `systemctl list-units | grep mnt`. Interestingly, it shows `backups` now (as `loaded mounted active`), but not the one I added. Doing `systemctl start mnt-taos-new.mount` does actually work. I wouldn't have even tried it because it didn't show up in `systemctl`. This could be user error (I'm not very knowledgeable about systemd) or a documentation issue (it would be great if the NixOS documentation instructed the user to use `systemd` to mount filesystems instead of whatever they might have been used to).

**Comment by flokli** [comment]
`systemd-fstab-generator` runs automatically on a `systemctl daemon-reload`, and from my understanding of `nixos/modules/system/activation/switch-to-configuration.pl`, L400, we run `systemctl daemon-reload` every time we switch to a new configuration.

`systemctl list-units --all` should list the new `mnt-taos-new.mount` unit.

It wasn't listed without the `--all` option, as the unit wasn't active or failed in the past (from systemctl(1)`:

           List units that systemd currently has in memory. This includes units that are either
           referenced directly or through a dependency, units that are pinned by applications
           programmatically, or units that were active in the past and have failed. By default only units
           which are active, have pending jobs, or have failed are shown; this can be changed with option
           --all.

If you can confirm this, we should indeed update `nixos/doc/manual/configuration/file-systems.xml` to recommend users they'd need to start the `.mount` units instead of invoking the `mount` binaries if they don't have "auto"  (or [x-systemd.automount](https://www.freedesktop.org/software/systemd/man/systemd.automount.html)) options. I assume this is not only the case on a switch, but also after a reboot (but would need checking).

Could you open a PR for this?

**Comment by glasserc** [comment]
I just tried adding another (fictitious) one and it does not show in `systemctl list-units --all`. However, removing it from `configuration.nix` and rebuilding produces `stopping the following units: mnt-taos-blah.mount`. Further investigation shows that it is present in `systemctl list-unit-files`. Indeed it seems that the file was created in `/run/systemd/generator`. That's fantastic, thank you very much for explaining it to me. I'll open a documentation PR later today.
