### ISSUE TITLE
Clarify the policy on branches, point contribution.md to the manual

### ISSUE THREAD

**Issue by cillianderoiste** [NixOS/nixpkgs#8734]
Update the manual to include the policy about the branches such as staging: http://comments.gmane.org/gmane.linux.distributions.nixos/13447

Instead of maintaining separate contribution guidelines in github and in the manual, we should link the contribution.md to the relevant section in the manual.

**Comment by lethalman** [comment]
I just did in https://github.com/NixOS/nixpkgs/commit/b4e5181dde01c6938825484f210120b54f1a7d2a for CONTRIBUTING.md.

**Comment by Profpatsch** [comment]
(triage) does this suffice?

**Comment by Profpatsch** [comment]
(triage) does this suffice?
