### ISSUE TITLE
Rollup GCC toolchains outside of pkgs.gcc

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#8735]
There are other toolchains such as gcj, gfortran, gccgo which are still pinned to gcc4.8 versions even though we are using gcc4.9 for gcc. We should bring these into line with the major version of gcc we are using.

**Comment by edolstra** [comment]
:+1:

**Comment by vcunat** [comment]
gfortran done in 784025c747.

**Comment by vcunat** [comment]
Fixed all on master, except for ADA, but I'd leave that one, at least for now. (There were updating problems in past.)
