### ISSUE TITLE
pavucontrol output menu on playback screen doesn't spawn on wayland

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#87446]
**Describe the bug**
When on the playback screen of pavucontrol where you see per-program audio streams, there's a dropdown that lets you select which output to send the program's sound to. When I click it, the menu doesn't appear, so I can't change what my output gets sent to.

**To Reproduce**
1. Run Wayland (perhaps with Sway), and within it run pavucontrol
2. open something that makes sound, like mpv
3. on the playback tab, try to open the menu next to the program

**Expected behavior**
I should see a list of all my output devices that can be used.

**Screenshots**
![2020-05-09-181543_grim](https://user-images.githubusercontent.com/3146494/81487321-38a2f080-9221-11ea-8f72-75e0227fe145.png)

**Additional context**
Choices should be things like built-in analog audio, hdmi audio, any additional sound cards, that sort of thing. I think even with just the one choice, you should get a working dropdown to open when things aren't broken, though.

Here's some error output if I launch it from a terminal and then try to open the dropdown menu. The lines don't appear until interacting with the menu, so they're about the problem I'm having.
```
Gdk-Message: 18:07:01.979: Window 0x1d5e260 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 18:07:01.979: Window 0x1d5e260 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 18:07:01.979: Window 0x1d5e260 is a temporary window without parent, application will not be able to position it on screen.

(pavucontrol:27686): Gdk-CRITICAL **: 18:07:01.984: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```

**Notify maintainers**

@abbradar 
**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.115, NixOS, 20.09pre223023.fce7562cf46 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre223023.fce7562cf46"`
 - channels(brad): `"home-manager, nixos-20.09pre223023.fce7562cf46"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pavucontrol
# a list of nixos modules affected by the problem
module:
```

**Comment by ZeiP** [comment]
Thought I'd let you know that I'm also occasionally hitting this bug on Fedora 32 with Wayland + Sway. On my system a reboot fixes this and it works fine most of the time. Not sure if this is useful in debugging the issue on your system also, but couldn't find other issues regarding the same bug elsewhere.

**Comment by jtojnar** [comment]
This might possibly fix it: https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/merge_requests/20
