### ISSUE TITLE
caffe python bindings

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs#8749]
the (new) caffe package, added in #8644 misses the python bindings.

```
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffe
```

 Because I really don't know how the python stuff works, I would be very delighted if someone else could add them.

**Comment by jb55** [comment]
yeah I wasn't sure how to package the included python stuff, I imagine it would have to be a separate package?

**Comment by jb55** [comment]
@domenkozar not sure if you're the right one to ask, does it make sense to use the multiple outputs feature to have caffe provide python libs here?

**Comment by puffnfresh** [comment]
@vcunat was this the right issue to close?

**Comment by vcunat** [comment]
Thanks, I've made a typo.

**Comment by sorpaas** [comment]
+1

**Comment by Profpatsch** [comment]
triage: fixed?

**Comment by FRidh** [comment]
I hate cmake. Fixed with https://github.com/NixOS/nixpkgs/commit/4b2336ea283707686c3a1f674e03add420720dd4
