### ISSUE TITLE
gnuradio: incomplete dependencies for gnuradio-companion

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#87510]
**Describe the bug**
gnuradio-companion does not work; it looks like it cannot find some Python modules / the PYTHONPATH is incomplete.

**To Reproduce**
1. Install gnuradio: `nix-env -iA nixos.gnuradio-with-packages` or `gnuradio-companion`
2. Try to start gnuradio-companion:
   ```
   $ gnuradio-companion
   ImportError

   Failed to initialize GTK. If you are running over ssh, did you enable X forwarding and start ssh with -X?

   (No module named gtk)
   ```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1795.d6c1b566b77 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1795.d6c1b566b77"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by doronbehar** [comment]
Yea gnuradio is pretty broken and outdated. See https://github.com/NixOS/nixpkgs/issues/82263 .

**Comment by povik** [comment]
Should someone need GNU Radio 3.7 before this issue is fixed, [these derivations I put together](https://github.com/MLAB-project/TALIR01/tree/master/sw/support/nix) might be helpful.

**Comment by mdvmeijer** [comment]
After updating my system I have this problem as well. It seems to have been introduced (again?) sometime in the last few weeks.

**Comment by doronbehar** [comment]
You are correct, this bug slipped into the channels recently but was recently fixed. See http://nixpk.gs/pr-tracker.html?pr=312173 .
