### ISSUE TITLE
RclusTool installation freezes

### ISSUE THREAD

**Issue by pahebert** [NixOS/nixpkgs#87598]
**Describe the bug**

The installation of the package **RclusTool** freezes just after this message:  

>   ** byte-compile and prepare package for lazy loading

**To Reproduce**

> nix-shell -p pkgs.rPackages.RclusTool

**Additional context**

I am the main maintainer of this package.

- This issue may be related to the fact that our package requires a X server (issue already noticed with mac os X).
- I have some difficulties to build the package with Nixos.This may be related too :

> cat RclusTool.Rcheck/00install.out
> * installing *source* package ‘RclusTool’ ...
> ** using staged installation
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘lattice’
> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
> Exécution arrêtée
> ERROR: lazy loading failed for package ‘RclusTool’
> * removing ‘/home/hebert/programmation/R/RclusTool/RclusTool.Rcheck/RclusTool’

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1619.ab3adfe1c76 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1619.ab3adfe1c76"`
 - channels(hebert): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jbedo** [comment]
I took a look at this and attached to the R process during the byte compilation. Looks like it's stuck in an infinite loop that continuously looks through the r-tcltk2 package files. Other packages that depend on tcltk2 (PDE) seem to work fine, so something specific to RclusTool is triggering this.

**Comment by jbedo** [comment]
Yeah it was missing from the list of packages requiring X.

**Comment by pahebert** [comment]
Thanks for your answer. I will think about giving another chance to Nixos. (I went back to Linux, because I couldn’t use R and its packages properly…)

Regards,
Pierre Hébert

**Comment by jbedo** [comment]
No worries, you can always run Nix on top of your current distribution and see if R is suitable for your needs without installing NixOS. A healthy R ecosystem is very important to me as we use R heavily in my lab. Tag me in on any R related issues you might have and I'll do my best to resolve them.
