### ISSUE TITLE
Package request: greetd

### ISSUE THREAD

**Issue by hallabro** [NixOS/nixpkgs#87603]
**Project description**
greetd is a minimal and flexible login manager daemon that makes no assumptions about what you want to launch.

**Metadata**

* homepage URL: https://git.sr.ht/~kennylevinsen/greetd
* source URL: https://git.sr.ht/~kennylevinsen/greetd
* license: gplv3
* platforms: linux

**Comment by MetaDark** [comment]
I started looking into packaging this, and building it was easy, but I've been having troubles in the NixOS module trying to launch the session defined in `services.xserver.displayManager.defaultSession`.

Does anyone else have more experience setting up display managers in NixOS?

**Comment by MetaDark** [comment]
Here is my current progress so far on a branch in my NUR repo: https://github.com/MetaDark/nur-packages/blob/greetd/modules/services/x11/display-managers/greetd/greetd.nix.

**Comment by bnjmnt4n** [comment]
As someone with minimal nix and systemd knowledge, I found @bqv's [module](https://github.com/bqv/nixrc/blob/7c7d4a75f03267c96d0194e27fa3b06fff9c35cc/profiles/wayland.nix) very helpful in setting up greetd on my [system](https://github.com/bnjmnt4n/home/blob/6780163efe1128214e900f2c2cb17e83fcc7b0cf/modules/greetd.nix). Here's hoping we can land greetd and friends in nixpkgs, with an easy-to-use module for the setup. (Although, it should probably be named under a new configuration option for that, since stuffing everything under `xserver.displayManager` doesn't make sense.)

**Comment by bqv** [comment]
I take no responsibility for how hideous my current X11+wayland setup is. It does work though, yes

**Comment by ymatsiuk** [comment]
#102242 🎉 

@luc65r do you by any chance plan to PR module mentioned [here](https://github.com/NixOS/nixpkgs/pull/102242#issuecomment-776856925)

**Comment by luc65r** [comment]
@ymatsiuk Yes, but I need to find motivation…
I thought @qzle was going to do it, but it seems like he lost motivation too

**Comment by ymatsiuk** [comment]
@luc65r you did a great job adding a package. I (and potentially more people) appreciate your effort! 🙂 Thanks.

**Comment by ymatsiuk** [comment]
@luc65r I didn't mean anything, just wanted to thank you for the work that has been done though.

I'm now curious what is this major issue you've faced with module?

**Comment by luc65r** [comment]
@ymatsiuk I don't remember well, but I think I couldn't get wayland running in qemu to test the greeters.
Now that I rethink of it, it maybe wasn't a major issue.

**Comment by qzle** [comment]
> I thought @qzle was going to do it, but it seems like he lost motivation too

I'm still interested, I was waiting for greetd to get merged and didn't have time since then. Thanks for getting greetd in, I'll open the PR soon!

**Comment by zimbatm** [comment]
#102242 includes the package but the NixOS module is still missing.

**Comment by ymatsiuk** [comment]
@zimbatm this is what I've [mentioned](https://github.com/NixOS/nixpkgs/issues/87603#issuecomment-809423568). @qzle agreed to submit a PR for module. Does it makes sense to wait before we can close this one WDYT?

**Comment by zimbatm** [comment]
My bad, I didn't read the whole thread. I started packaging greetd on my own and found this afterward. I have a WIP NixOS module: https://github.com/zimbatm/nixpkgs/tree/nixos-greetd
