### ISSUE TITLE
module request: keycloak

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#87673]
**Project description**
>  Add authentication to applications and secure services with minimum fuss. No need to deal with storing users or authenticating users. It's all available out of the box.
>
> You'll even get advanced features such as User Federation, Identity Brokering and Social Login. 

**Metadata**

* homepage URL: https://www.keycloak.org/
* source URL: https://github.com/keycloak/keycloak
* license: Apache-2.0
* platforms: linux, darwin (maybe?)

**Comment by elohmeier** [comment]
There exists a package: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/keycloak/default.nix
A module is currently missing.

**Comment by bbigras** [comment]
Uh I was pretty sure I checked in my local nixpkgs checkout. Weird, I wonder if I just made a typo while checking. Sorry about that.

We can leave this issue for the module part.

**Comment by rileyinman** [comment]
It looks like the maintainer is @ngerstle. Have you started work on a module already, or would you prefer someone else step up to work on that part? I haven't dealt with creating modules in the past, but I'd be willing to learn.

**Comment by ngerstle** [comment]
I haven't dug into making a module previously. I suspect there's a bit of ugliness around the setup and configuration decoratively, but I'm happy to work with someone on it.

**Comment by wmertens** [comment]
@ngerstle yes please :)
