### ISSUE TITLE
no asound.conf from host-etc in steam-chroot-env

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#8767]
steam-chroot-env symlinks lots of files from /host-etc to /etc, but asound.conf is not one of them. On my laptop without asound.conf I don't have sound at all. Therefore I don't have sound in steam games.

When I symlinked /host-etc/asound.conf to /etc/asound.conf everything worked as expected.

**Comment by ktosiek** [comment]
This should be fixed in unstable (with the new Steam packaging based on FHSUserEnv).

**Comment by cpages** [comment]
@ktosiek do you mean it's already fixed in there or that we should commit the fix in there?

**Comment by ktosiek** [comment]
I mean it already works in unstable

**Comment by cpages** [comment]
Then I'm closing this. @sorokin feel free to reopen if it doesn't work for you.
