### ISSUE TITLE
nixos/systemd: missing systemd units proc-sys-fs-binfmt_misc.mount

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#87687]
**Describe the bug**
The [source code](https://github.com/NixOS/nixpkgs-channels/blob/f75784a33bd8b6944c18f8543e5fb4648bb7f8f3/nixos/modules/system/boot/systemd.nix#L1038) indicates a dependency on `proc-sys-fs-binfmt_misc.mount`. However, this unit is not automatically included with the help of [`systemd.additionalUpstreamSystemUnits`](https://nixos.org/nixos/manual/options.html#opt-systemd.additionalUpstreamSystemUnits).

It is therefore listed as `not-found`:
```
$ systemctl status proc-sys-fs-binfmt_misc.mount
Unit proc-sys-fs-binfmt_misc.mount could not be found.
```

`nixops check` highlights this:
```
$ nixops --version
NixOps 1.7

$ nixops info -d mydeployment
[…]
Nix path: -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03-small.tar.gz
[…]
$ nixops show-option -d mydeployment myserver systemd.services.systemd-binfmt.wants
[ "proc-sys-fs-binfmt_misc.mount" ]

$ nixops show-option -d mydeployment myserver systemd.additionalUpstreamSystemUnits
[ "systemd-timesyncd.service" "emergency.target" "emergency.service" ]

$ nixops show-option -d mydeployment myserver boot.binfmt.registrations
{ }

$ nixops check -d mydeployment
Machines state:
+----------+--------+-----+-----------+----------+----------------+----------------------------------------+-------+
| Name     | Exists | Up  | Reachable | Disks OK | Load avg.      | Units                                  | Notes |
+----------+--------+-----+-----------+----------+----------------+----------------------------------------+-------+
| myserver | Yes    | Yes | Yes       | N/A      | 0.00 0.00 0.00 | proc-sys-fs-binfmt_misc.mount [failed] |       |
+----------+--------+-----+-----------+----------+----------------+----------------------------------------+-------+
Non machines resources state:
+------+--------+
| Name | Exists |
+------+--------+
+------+--------+

```

**Expected behavior**
Units that are relied upon should be found.

**Additional context**
Commit eb862c48ddc288243c5447e8decc623b10ef165c seems to something to do with it.

**Notify maintainers**
@fpletz @flokli @andir 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.40, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  - nixos/systemd
```

**Comment by flokli** [comment]
This has last been touched in https://github.com/NixOS/nixpkgs-channels/commit/eb862c48ddc288243c5447e8decc623b10ef165c.

I see we set `additionalUpstreamSystemUnits` in `nixos/modules/system/boot/binfmt.nix` if `boot.binfmt.registrations != {}`, so we could move https://github.com/NixOS/nixpkgs-channels/blob/f75784a33bd8b6944c18f8543e5fb4648bb7f8f3/nixos/modules/system/boot/systemd.nix#L1038 there as well.

After reading a bit on `systemd-binfmt.service` and `binfmt.d`, is this currently halfway broken? Maybe more of the logic should be moved into nixos/modules/system/boot/binfmt.nix…

**Comment by flokli** [comment]
@datafoo Can you see if https://github.com/NixOS/nixpkgs/pull/87742 fixes this for you? You might want to reboot, to make sure the mount isn't active.

Also, do you use any binfmt stuff?

**Comment by datafoo** [comment]
> @datafoo Can you see if #87742 fixes this for you? You might want to reboot, to make sure the mount isn't active.

Yes, it fixes the problem:
```
$ nixops --version
NixOps 1.7

$ nixops info -d mydeployment 
[…]
Nix path: -I nixpkgs=https://github.com/flokli/nixpkgs/archive/e6b15128b110e537775e9be2d8de28b8c047f4c4.tar.gz
[…]

$ nixops show-option -d mydeployment myserver systemd.services.systemd-binfmt.wants
error: attribute 'systemd-binfmt' in selection path 'nodes.myserver.config.systemd.services.systemd-binfmt.wants' not found
error: evaluation of the deployment specification failed

$ nixops show-option -d mydeployment myserver systemd.additionalUpstreamSystemUnits
[ "systemd-timesyncd.service" "emergency.target" "emergency.service" ]

$ nixops show-option -d mydeployment myserver boot.binfmt.registrations
{ }

$ nixops check -d mydeployment
Machines state:
+----------+--------+-----+-----------+----------+----------------+-------+-------+
| Name     | Exists | Up  | Reachable | Disks OK | Load avg.      | Units | Notes |
+----------+--------+-----+-----------+----------+----------------+-------+-------+
| myserver | Yes    | Yes | Yes       | N/A      | 0.02 0.12 0.06 |       |       |
+----------+--------+-----+-----------+----------+----------------+-------+-------+
Non machines resources state:
+------+--------+
| Name | Exists |
+------+--------+
+------+--------+
```

> Also, do you use any binfmt stuff?

I do not think so. I am not familiar with binfmt.
