### ISSUE TITLE
postgresql: module depends on sudo

### ISSUE THREAD

**Issue by emilazy** [NixOS/nixpkgs#87695]
The PostgreSQL module [uses `sudo`](https://github.com/NixOS/nixpkgs/blob/d623b3cb071f87c59c2e5ccd73ed8ab74887445a/nixos/modules/services/databases/postgresql.nix#L334), but doesn't turn on or assert `security.sudo.enable`. I think it would be ideal to avoid the `sudo`  entirely here (I noticed this when switching to the new `security.doas` module on my system), but I don't know enough about Postgres to know what the best way to do that would be. The `postStart` script seems awfully elaborate; I wonder if how other distros accomplish this?

cc @thoughtpolice @danbst

**Comment by aanderse** [comment]
Known issue which I'm looking to address for `20.09`: https://github.com/NixOS/nixpkgs/pull/84146

**Comment by emilazy** [comment]
Fixed by b7ddd316f1ba041c0d9f79973996f097708681fb, though #84146 remains relevant.
