### ISSUE TITLE
Package request: Bombadillo

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#87780]
**Project description**
Bombadillo is a non-web browser for the terminal. It supports several protocols, such as gopher, gemini, and finger.

**Metadata**

* homepage URL: http://bombadillo.colorfield.space/
* source URL: https://tildegit.org/sloum/bombadillo
* license: gpl3
* platforms: unix, linux, darwin

**Comment by ehmry** [comment]
https://git.sr.ht/~ehmry/gemini-flakehttps://git.sr.ht/~ehmry/gemini-flake/commit/47a915de5f13fb26b426c8dc034bd23b699d0417
