### ISSUE TITLE
Package request: ncgopher

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#87784]
**Project description**
A Gopher client written in Rust with NCurses. Also supports Gemini.

**Metadata**

* source URL: https://github.com/jansc/ncgopher
* license: bsd 2-clause
* platforms: unix, linux, darwin

**Comment by SCOTT-HAMILTON** [comment]
Opened PR https://github.com/NixOS/nixpkgs/pull/96372.
If you wan't to try it now, checkout my nur repository http://nur.nix-community.org/repos/shamilton/.
