### ISSUE TITLE
KDE Connect non-functional on Sway

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#87785]
**Describe the bug**
I can't get my machine to show up on my phone on the pairing screen, nor does it show as available when I manually enter its ip or hostname on my phone.

**To Reproduce**
1. install sway and kdeconnect
2. run `kdeconnect-indicator` or `kdeconnect-cli -l`
3. if `kdeconnect-indicator`, right click the new icon on your panel and select "configure" with the arrow keys, then press enter (something is wonky and the window may just disappear if you move your mouse to select it)

**Expected behavior**
I should've seen my other device available in the list to pair with.

**Additional context**
I heard from someone that the issue may be dbus related
An Android phone + accompanying app may be needed for testing this.

**Notify maintainers**

@FRidh 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.118, NixOS, 20.09pre223023.fce7562cf46 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre225264.683c68232e9"`
 - channels(brad): `"home-manager, nixos-20.09pre225264.683c68232e9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: kdeconnect
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
I'm using KDE connect without flaws on Awesome WM (Xorg). It could be a networking issue. Could you give some info regarding your network configuration? Also, if you use any of https://nixos.org/nixos/options.html#avahi it could help to list the options you set from that category as well.

Also, it'll be nice to see the output of kdeconnect-indicator when you start it from a terminal. When you do that, make sure via a processes viewer that no `kdeconnectd` process is running (to make sure `kdeconnect-indicator` will spawn it on it's own).

**Comment by Soundtoxin** [comment]
>Could you give some info regarding your network configuration?
(unsure if you meant physical network layout or software, but...)
Plain old ethernet on the computer, although occasionally it auto connects to my WiFi despite being plugged into ethernet, but this doesn't seem to cause issues elsewhere and it's the same LAN. Android phone is on the house WiFi. I can ssh/sftp to the computer from the phone by hostname, so they can clearly connect to each other in general.
I don't have any mention of avahi in my configuration.nix, but I'm using NetworkManager, which does all sorts of things.

```
brad@anpan:~/ > kdeconnect-indicator
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
```
I ran this first, went to check if kdeconnectd had been running via htop, and it had been, but killing it and running the command again gave identical output.
Thanks for the help so far, I hope we can figure this out.
By the way, I'm not sure if it was clear in my original post, but when I heard that it may be a dbus issue, I'd heard that Sway specifically had given some people dbus issues. So, there's a chance that your experience wouldn't be the same on Sway as it is on Awesome WM.

**Comment by doronbehar** [comment]
Do you have firewall enabled? Try
 https://userbase.kde.org/KDEConnect#I_have_two_devices_running_KDE_Connect_on_the_same_network.2C_but_they_can.27t_see_each_other

Usually upstream is better at debugging this. Although NixOS is a weird beast, it's not that different in certain senses compared to other distros. If you'll open a thread at their community forums, I'll be happy to help you if they ask you "what is the output of this command?" or "what are the contents of your "/etc/file" and you don't have that command or that file available. Commenting to such questions by other distros' users will need just a bit of adaptation from you, as a NixOS user but it's not impossible.

Feel free to ping me here if you need help. Also, tell them you use NixOS and don't worry that they won't help you because of that.

**Comment by Soundtoxin** [comment]
>Do you have firewall enabled?

I don't believe I have a firewall enabled. All the lines with "firewall" in my config are commented out.

>If you'll open a thread at their community forums

Alright, I'll at least consider doing that in the next couple days. Thanks for the idea.

**Comment by Thra11** [comment]
> I don't believe I have a firewall enabled. All the lines with "firewall" in my config are commented out.

`networking.firewall.enable` defaults to `true`, so if you aren't explicitly disabling the firewall or opening ports, then it's possible you have a firewall enabled which is blocking the necessary ports. You could try temporarily setting it to false, and if that works, setting something like `network.firewall.allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];` and `network.firewall.allowedUDPPortRanges = [ { from = 1714; to = 1764; } ];` (I think that's the right ports for kdeconnect?).

**Comment by Soundtoxin** [comment]
> `networking.firewall.enable` defaults to `true`, so if you aren't explicitly disabling the firewall or opening ports, then it's possible you have a firewall enabled which is blocking the necessary ports. You could try temporarily setting it to false, and if that works

Holy cow! That really did work.

> `network.firewall.allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];` and `network.firewall.allowedUDPPortRanges = [ { from = 1714; to = 1764; } ];`

It seems like it's `networking` rather than `network` (got an error pasting your exact thing at first), but it seems like this worked now! I did the pairing while the firewall was disabled, then enabled it and added your suggest settings and I'm still paired, so I think that means it worked. I will consider this solved for now and close the issue. If it's broken on reboot or something, guess I'll then come back.

Thank you for the help @Thra11 (and also @doronbehar )
