### ISSUE TITLE
Package Request: Upgrade Ly recipe

### ISSUE THREAD

**Issue by mtekman** [NixOS/nixpkgs#87809]
**Project description**

There [already exists a Ly](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/display-managers/ly/default.nix) (display manager) recipe in nixpkgs, but it cannot be enabled as a service and it is lacking in other features.

On Gitlab, there exists [this fantastic ly recipe](https://gitlab.com/roosemberth/dotfiles/-/commit/dc50bb9e36613cad6612c46decaa74ea087bd66f) from @roosemberth which already improves functionality.

Would it be easy to make this the default?

(apologies if I'm breaking some kind of cross-site decorum...)

**Metadata**

* homepage URL: https://github.com/cylgom/ly
* source URL: https://github.com/cylgom/ly
* license: wtfpl
* platforms: linux

**Comment by puzzlewolf** [comment]
Hi @mtekman,

Unfortunately, @roosemberth says in the commit message you linked:

> This is a reference commit and shall not be merger in master.

and he mentions (https://github.com/roosemberth/dotfiles/issues/3) that there is at least one issue with ly that needs to be fixed. 

I guess you'll have to contact him about this :)

**Comment by mtekman** [comment]
Oh I see, I thought it was a clean commit.

Okay, thank you for pointing me to that issue

**Comment by roosemberth** [comment]
FWIW, it is my intention to fix [my upstream pr](https://github.com/cylgom/ly/pull/137) and add a support for the ly display manager in nixpkgs since I use this myself.

**Comment by mtekman** [comment]
Greatly looking forward to it :-D

**Comment by MatthewCroughan** [comment]
Would love this to be expanded.

**Comment by petersjt014** [comment]
Same. This would be great for minimal installs that still need gui-ness.

**Comment by WolfangAukang** [comment]
Hey everyone, I have been trying this one and I was able to get `ly` to show after booting (https://github.com/NixOS/nixpkgs/issues/150515#issuecomment-1127139968). Now, I just need to check if the reason for the Desktop Manager (I was trying Enlightenment, but never used it before) is not booting is because of the module or not.

**Comment by patrickaldis** [comment]
Hey, I was wondering if there was any update on this? I see that `ly` [0.6.0](https://github.com/NixOS/nixpkgs/pull/237912) has been packaged. I was wondering if anyone had a working module?
