### ISSUE TITLE
Video conferences are not working with Firefox

### ISSUE THREAD

**Issue by jgeerds** [NixOS/nixpkgs#87835]
**Describe the bug**
It seems to me that it is currently not possible to use Firefox for video conferences like Google Meet or Jitsi. In both services, after joining a conference room, I see no video/audio from the other attendees and nobody can hear/see me.

I'm not sure what exactly the problem is. I don't think it's a permission problem in Firefox or something similar. For example in Google Meet, before joining a room, there is a step where you can see yourself (configure the correct camera/microphone and so on) and that works. That sounds to me that Firefox can access the camera/microphone.

**To Reproduce**
1. `nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/6bcb1dec8ea16f20e6404631668cf69e76424eef.tar.gz -p firefox --run "firefox --ProfileManager"` (current `nixpkgs-unstable`)
2. Create a new temporary profile to make sure that no installed plugin causes the trouble
3. Join a [Google Meet](https://meet.google.com) or [Jitsi](https://meet.jit.si/) room.

**Expected behavior**
I should see see and hear the other attendees (and they should hear/see me).

**Additional context**
I'm running NixOS 20.03 and using the `firefox` package from `nixpkgs-unstable`. I've already tried:
* `firefox-wayland` from `nixpkgs-unstable`
* `firefox` from `nixpkgs-unstable`
* `firefox-esr` from `nixpkgs-unstable`
* `Xorg` and `Wayland`
* Clean Firefox profile (e.g. no installed plugins)

Here comes the interesting thing: `firefox-bin` from `nixpkgs-unstable` works. Maybe we miss some (optional) dependency or something like that? Unfortunately, I don't see any interesting logs.

**Notify maintainers**
@edolstra @andir

**Metadata**
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.38, NixOS, 20.03.git.5adf2a6c116 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(jgeerds): `""`
 - nixpkgs: `/var/src/nixpkgs` # I'm using krops: https://github.com/krebs/krops
```

Maintainer information:
```yaml
- nixpkgs.firefox
- nixpkgs.fiefox-esr
```

**Comment by fabianhjr** [comment]
Hi @jgeerds, I am using firefox from `nixos-20.03` rather than `nixos-unstable`. However, as additional context other applications like discord also have this issue. (Noticed it a week and a half or so ago)

**Comment by fabianhjr** [comment]
Investigating the differences between nixos.firefox and nixos.firefox-bin, in particular:

```
dependency: firefox -> firefox-bin
-------------------------
ffmpeg: 3.4.7 -> ffmpeg-4.2.2
libva: missing -> 2.7.1
```

**Comment by xaverdh** [comment]
Might be that https://github.com/NixOS/nixpkgs/pull/87708 (or a `backport` of it) fixes this.

**Comment by jgeerds** [comment]
@xaverdh I'm pretty sure that this patch will fix it. Thank you! I'm closing the issue.

**Comment by jgeerds** [comment]
FYI: It's working again on recent nixpkgs-unstable :+1:
