### ISSUE TITLE
Gnome Live Install ISO

### ISSUE THREAD

**Issue by shadowrylander** [NixOS/nixpkgs#87839]
Hello!

If possible, would anyone be able to point me towards a live iso version of NixOS, through which I can install it, which uses Gnome as the default DE? I use a Surface Book 2, and with KDE, in order to increase the scale, I have to reboot the system, which I believe discards the effects of the previous session, as it is a live session. Since I've noticed that Gnome has much better support for HiDPI screens in live sessions, I was wondering whether anyone knows where I can get such an iso, or guide me in creating my own iso with Gnome!

My sincerest apologies if this isn't the right place to ask about this, but I couldn't quite seem to find anything else on Google; thank you kindly for the help!

**Comment by shadowrylander** [comment]
Also, while booting the KDE iso on another one of my machines, I noticed a HiDPI options; I assuming that would work for the Surface Book 2 as well, with a 3240x2160 resolution at 260 DPI?

**Comment by Gaelan** [comment]
It looks like there is such a configuration in nixpkgs, so you should be able to do this on any machine with Nix installed (instructions based on [this](https://nixos.org/nixos/manual/index.html#sec-building-cd)):

```sh
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs/nixos
nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-graphical-gnome.nix default.nix
```

That'll create a `./result` folder with the iso inside.

**Comment by shadowrylander** [comment]
Does this require you to be on a NixOS live iso or install from beforehand?

**Comment by Gaelan** [comment]
Not necessarily. Any NixOS machine (ISO or otherwise) would work, but you could also install Nix (the package manager) on another distro with `curl -L https://nixos.org/nix/install | sh`, then run the commands above.

**Comment by shadowrylander** [comment]
Fair enough! Thanks for the help!
