### ISSUE TITLE
Package hsphfpd & pali’s pulseaudio patches

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#87910]
**Project description**
It would be nice to have hsphfpd and PulseAudio variant that includes support for hsphfpd and patchset from: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/288

This should allow, among other things, to control the system volume from headphones.

Relevant issue:

* https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/722

Other interesting patches are:

* Improved codecs: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227
* https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/254#note_479030
* absolute volume: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/239#note_479656

**Metadata**

* homepage URL: https://github.com/pali/hsphfpd-prototype
* license: confirmed via IRC: “for my perl projects I'm using standard perl license, see: <https://dev.perl.org/licenses/>”
* platforms: linux

**Comment by jtojnar** [comment]
It now has a rudimentary support in pipewire: https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/295

**Comment by gebner** [comment]
Pulseaudio support has been merged in #103225, pipewire support for hsphfpd is enabled and works as of #105362.
