### ISSUE TITLE
Firefox extensions

### ISSUE THREAD

**Issue by mucaho** [NixOS/nixpkgs#8793]
I would like to install firefox with additional extensions / add-ons from my configuration file.
What is the default procedure to add plugins for applications available in the nixpkgs expressions? Do they have to be maintained manually? Keep in mind there are probably thousands of add-ons with constantly changing versions and checksums.

I wrote a little script that can be added to a build phase (e.g. `postInstall`). It automatically downloads & installs the extensions specified via an additional `extensions ? [ ]` function parameter.
The url attribute: 
```sh
extension_urls = map (name: "https://addons.mozilla.org/firefox/downloads/latest/${name}/addon-${name}-latest.xpi") extensions;
```
The script:
```bash
# download extensions and extract them to installation folder
for xpiurl in $extension_urls; do
  wget $xpiurl -O tmp.xpi
  id=$(unzip -qc tmp.xpi install.rdf | xmlstarlet sel \
      -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# \
      -N em=http://www.mozilla.org/2004/em-rdf# \
      -t -v \
      "//rdf:Description[@about='urn:mozilla:install-manifest']/em:id")
  mkdir -p $out/lib/browser/extensions/$id
  unzip tmp.xpi -d $out/lib/browser/extensions/$id
  rm tmp.xpi
done
```

See [installing extensions](http://kb.mozillazine.org/Installing_extensions) for more details.

**Comment by nbp** [comment]
The problem of this approach is that you have no idea which version of the extension you got and unless there is a Firefox update, you will get no update of the extensions.  Basically, you should be doing no network access at all, except under fetchURL.

Thus the extensions would have to be listed with their checksum, in order to verify that you are not downloading a compromised version.  As you don't want a modified version, you probably don't want to have a URL which is possibly changing over time.  Do addon.m.o have a static address for addons?  Can we get a listing with all addons versions?

Some addons are also shipped with some binaries, it would be nice if we could wrap these binaries in a way which is working with Nix packages, and avoid references to `/lib`.

**Comment by mucaho** [comment]
> Thus the extensions would have to be listed with their checksum, in order to verify that you are not downloading a compromised version.

The extensions are served over `https`. Doesn't that implicitly guarantee that we can't retrieve compromised versions? (The identity of the `addons.mozilla.org` host is validated using a chain of certificates starting at the root certificate installed on our system. The data transferred between `AMO` and our system is encrypted).

> Do addon.m.o have a static address for addons?

* `https://addons.mozilla.org/firefox/downloads/latest/<id>/addon-<id>-latest.xpi`  for latest version
* `https://addons.mozilla.org/firefox/downloads/file/<id>/<name>-<version>-<applications>-<platform>.xpi` for specific version (`<applications>` seems to be either `fx` for FF only or `tb+fx` for FF & Thunderbird, `<platform>` seems to be `linux`).

> Can we get a listing with all addons versions?

Haven't found a web service or something more accessible unfortunately. I can only think of web page parsing to extract all that information.

-----------------------------------------------------

I found [another tutorial](https://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/) about how to integrate add-ons into firefox. [The corresponding tool](https://addons.mozilla.org/en-US/firefox/addon/cck2wizard/) may allow installing a list of extensions after firefox has been installed. I will investigate further.

----------------------------------------------------

As a side note, there is the possibility to specify & lock-down a lot of the configuration options for firefox at install time, using an enterprise version of firefox with a slower release cycle - [have a look at the documentation](https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment#Example_configuration_file). Could this be a potential new `firefox-esr` package?

**Comment by nbp** [comment]
>>    Thus the extensions would have to be listed with their checksum, in order to verify that you are not downloading a compromised version.

> The extensions are served over https. Doesn't that implicitly guarantee that we can't retrieve compromised versions? (The identity of the addons.mozilla.org host is validated using a chain of certificates starting at the root certificate installed on our system. The data transferred between AMO and our system is encrypted).

No, the security of the transport does not ensure that the content is not changed.  Plus we use the checksum to store the compressed version in the nix store.


>>    Can we get a listing with all addons versions?

> Haven't found a web service or something more accessible unfortunately. I can only think of web page parsing to extract all that information.

Hum … I don't think scrapping any website is a good idea.  Maybe @clouserw will have a better idea on how to get a list of all addons with their checksums.

> As a side note, there is the possibility to specify & lock-down a lot of the configuration options for firefox at install time, using an enterprise version of firefox with a slower release cycle - have a look at the documentation. Could this be a potential new firefox-esr package?

We don't need an ESR version to change the preferences of Firefox, but I will not recommend abusing this, as this will provide a different user experience.

**Comment by clouserw** [comment]
I don't have good news for you. :(

Add-ons used to be hosted on ftp.mozilla.org.   See https://bugzilla.mozilla.org/show_bug.cgi?id=1074960 for that discussion.  What you want, a feed of add-on versions, is https://bugzilla.mozilla.org/show_bug.cgi?id=1140538.  With a single developer working on AMO though, it's not at the top of any priority lists.

It's cliche, but if you're interested in writing a patch for it, we could help you get the site up and running.  Find us in #amo on irc.mozilla.org if so.  Cheers.

**Comment by grahamc** [comment]
Can this be closed?

**Comment by CMCDragonkai** [comment]
Would it be correct to say that the only declarative plugins for Firefox are those specified inside the firefox wrapper expression, anything else would have to be installed imperatively, or somebody has to write an expression for it and put it into nixpkgs?
