### ISSUE TITLE
amdgpu-pro don't work with mainline linux kernel

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#87986]
**Describe the bug**

```
[root@gaming:~]# nixos-rebuild switch
building Nix...
building the system configuration...
error: The option `boot.kernelPackages' has conflicting definitions, in `/etc/nixos/configuration.nix' and `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/hardware/video/amdgpu-pro.nix'.
```

**To Reproduce**
1. use `linuxPackages_latest` and `amdgpu-pro` together

```
  # use latest kernel to have best performance
  boot.kernelPackages = pkgs.linuxPackages_latest;
  services.xserver.videoDrivers = [ "amdgpu-pro" ];
  nixpkgs.config.allowUnfree = true;
```

2. `nixos-rebuild switch`

**Expected behavior**
beeing ble to use latest linux kernel and amdgpu-pro together. if it's not pissible, give useful error message and not something that looks like an error in nixos

**Additional context**
It also don't work with default kernel, but that is unrelated https://github.com/NixOS/nixpkgs/issues/87984

**Notify maintainers**
@corngood

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.03.1879.91cdcf31357 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1879.91cdcf31357, nixos-hardware, nixos-unstable-20.09pre225931.32b8ed73809"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by adamlwgriffiths** [comment]
This is still an issue on 22.05.

**Comment by tomodachi94** [comment]
`amdgpu-pro` was removed by https://github.com/NixOS/nixpkgs/pull/320228. It was unmaintained.
