### ISSUE TITLE
fetchurl "name" can be a little surprising when the url has parameters

### ISSUE THREAD

**Issue by abathur** [NixOS/nixpkgs#88039]
**Describe the bug**
[This patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/attr/default.nix#L18) for attr gets named after its URL parameter:

> copying path '/nix/store/6afjbhgxgl3jrwiwackzslkjcn0bhd1z-?id=14adc898a36948267bfe5c63b399996879e94c98' from 'https://cache.nixos.org'...

This, in turn, freaks people out a little. As soon as I saw it, I remembered someone mentioning it in #nixos a few days ago: https://logs.nix.samueldr.com/nixos/2020-05-13#1589349075-1589349302;

I mentioned this in #nixos myself, and clever added the following:
> 19:04           clever | abathur: ah, the nix function just grabs whatever is after the last / and uses that as a name
> 19:05           clever | abathur: it should probably have a name= added to the fetchurl, to make it cleaner, and/or use fetchpatch

I assume clever is correct that these would "fix" the odd name here, but I wanted to open a general/broad issue first since it isn't obvious to me whether the fetchurl naming should change.

**Comment by Ekleog** [comment]
I just tried `wget` on this same URL, and it creates a file with the same name as this one. Does anyone have a better idea of name to use by default?

**Comment by Artturin** [comment]
the fetchers already have a name attribute that can be set

**Comment by abathur** [comment]
@Artturin not sure thst implies the issue is fixed? For reference, here was the patch at the time: https://github.com/NixOS/nixpkgs/blob/50a5c1853d571c26bab9f22e49e94ff13e1ffc92/pkgs/development/libraries/attr/default.nix#L18

If the API can be used in this way, and doing so yields a name with a query parameter in it, some people get spooked.
