### ISSUE TITLE
build error with firebird-2.5.7 on nixos 20.09

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#88048]
**Bug description**

nixos-build switch produces a build error due to  firebird-2.5.7.27050-0 while firebird is not explicitly mentioned anywhere in the nixox/congiuration.nix file...

**To Reproduce**
1. nix-channel --update
2. nixos-build switch 
3. build  error message
4. removed a few apps from congiuration.nix file hoping that one of them would be asking for firebird to be installed behind the scene at no avail...

**Expected behavior**
A clean error free build.

**Screenshot**

...
making all in engines/ccgost...
g++ -D_REENTRANT -I. -I../common -I../common -I./unicode -I./.. -D_REENTRANT -DHAVE_CONFIG_H -DU_LAYOUT_IMPLEMENTATION -O  -c -DPIC -fPIC -o HebrewLigatureData.o HebrewLigatureData.cpp
make[2]: Entering directory '/build/openssl-1.0.2u/engines/ccgost'
gcc -I../../include -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o e_gost_err.o e_gost_err.c
g++ -D_REENTRANT -I. -I../common -I../common -I./unicode -I./.. -D_REENTRANT -DHAVE_CONFIG_H -DU_LAYOUT_IMPLEMENTATION -O  -c -DPIC -fPIC -o HebrewShaping.o HebrewShaping.cpp
g++ -D_REENTRANT -I. -I../common -I../common -I./unicode -I./.. -D_REENTRANT -DHAVE_CONFIG_H -DU_LAYOUT_IMPLEMENTATION -O  -c -DPIC -fPIC -o IndicClassTables.o IndicClassTables.cpp
gcc -I../../include -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o gost2001_keyx.o gost2001_keyx.c
IndicClassTables.cpp:229:117: error: narrowing conversion of '2147483651' from 'unsigned int' to 'icu_3_0::IndicClassTable::ScriptFlags' {aka 'int'} [-Wnarrowing]
  229 | static const IndicClassTable teluClassTable = {0x0C00, 0x0C6F, 3, TELU_SCRIPT_FLAGS, teluCharClasses, teluSplitTable};
      |                                                                                                                     ^
IndicClassTables.cpp:231:117: error: narrowing conversion of '2147483651' from 'unsigned int' to 'icu_3_0::IndicClassTable::ScriptFlags' {aka 'int'} [-Wnarrowing]
  231 | static const IndicClassTable kndaClassTable = {0x0C80, 0x0CEF, 4, KNDA_SCRIPT_FLAGS, kndaCharClasses, kndaSplitTable};
      |                                                                                                                     ^
make[4]: *** [../config/mh-linux:43: IndicClassTables.o] Error 1
make[4]: Leaving directory '/build/Firebird-2.5.7.27050-0/extern/icu/source/layout'
make[3]: *** [Makefile:98: all-recursive] Error 2
make[3]: Leaving directory '/build/Firebird-2.5.7.27050-0/extern/icu/source'
make[2]: *** [../gen/Makefile.extern.icu:39: libicu] Error 2
make[2]: Leaving directory '/build/Firebird-2.5.7.27050-0/gen'
make[1]: *** [Makefile:193: external_libraries] Error 2
make[1]: Leaving directory '/build/Firebird-2.5.7.27050-0/gen'
make: *** [Makefile:6: firebird] Error 2
builder for '/nix/store/589jgyzjbbn6zl870qswm80pi4xh8ffq-firebird-2.5.7.27050-0.drv' failed with exit code 2
building '/nix/store/f5v53hni9pnldx4l0v4svxv0ibl62ir3-tor-browser-linux64-9.0.9_en-US.tar.xz.drv'...
cannot build derivation '/nix/store/c1wpclz112ssp5ki6m546llszn144bq8-wt-4.2.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8izfzp2k51zz3385cq14ffd31l2c8bwg-fileshelter-4.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wi7fzbgmwj9rrzm48mlcsvw51lymmcz8-system-path.drv': 1 dependencies couldn't be built
building '/nix/store/75r17sql3df7jq3azd76w9fjw6870wm6-torrc.drv'...
building '/nix/store/0zq0cb92k0w72ri9jb2zd65gzpnhx6fv-udev-rules.drv'...
building '/nix/store/jqc775s8a0m6r6qhwcfssjdya326s6z0-unit-NetworkManager-dispatcher.service.drv'...
building '/nix/store/bvg0a7ah4bd77s86f16rq7jsl7sh3nxy-unit-NetworkManager-wait-online.service.drv'...
building '/nix/store/vbnnzk9kdx828c8vi3pqcjayrf1ja43n-unit-NetworkManager.service.drv'...
building '/nix/store/df1ffd22pbca5x7ya5mwa8prm40mg54p-unit-alsa-store.service.drv'...
cannot build derivation '/nix/store/4375h9w8pmppld22s4jb6ag05riw87vg-xsession-wrapper.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gi689m2ph1avv6n2svvlzr5d2v2xm4p1-nixos-system-bx26-20.09pre226012.b47873026c7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gi689m2ph1avv6n2svvlzr5d2v2xm4p1-nixos-system-bx26-20.09pre226012.b47873026c7.drv' failed

**Notify  @maintainers**
@Marc Weber <marco-oweber@gmx.de>

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.09pre221706.b61999e4ad6 (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226012.b47873026c7"`
 - channels(k): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wamserma** [comment]
This is pulled in as an indirect dependency of `fileshelter` via `wt`.
