### ISSUE TITLE
What is the difference with install nixpkgs.xxx and nixpkgs.haskellPackages.xxx

### ISSUE THREAD

**Issue by arkrost** [NixOS/nixpkgs#88042]
Hi! I am stumped with installing a few haskell packages

```
arost ~/Projects > nix-env -f "<nixpkgs>" -iA haskellPackages.hlint haskellPackages.cabal2nix
installing 'hlint-3.1.1'
installing 'cabal2nix-2.15.3'
building '/nix/store/l3zqxfn3l5pd8d9ffyc2x78018v9yvcb-user-environment.drv'...
error: packages '/nix/store/bgp49zlcahfx7ss1h64yfhyp52yzq8zj-hlint-3.1.1/lib/links/libgmpxx.4.dylib' and '/nix/store/8w66h699jzjwnmc88sl111fzf0rp1rda-cabal2nix-2.15.3/lib/links/libgmpxx.4.dylib' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/l3zqxfn3l5pd8d9ffyc2x78018v9yvcb-user-environment.drv' failed with exit code 1
error: build of '/nix/store/l3zqxfn3l5pd8d9ffyc2x78018v9yvcb-user-environment.drv' failed
arost ~/Projects > nix-env -f "<nixpkgs>" -iA hlint cabal2nix 
installing 'hlint-3.1.1'
installing 'cabal2nix-2.15.3'
building '/nix/store/bd0mpv69nz2yrj4ig29s736lm3rcanb1-user-environment.drv'...
created 164 symlinks in user environment
```

What is the difference between two install commands?

**Comment by wamserma** [comment]
The clue is in `pkgs/top-level/all-packages.nix`:
```
hlint = haskell.lib.justStaticExecutables haskellPackages.hlint;
```
The `haskellPackages.xxxx` also have some (intermediate) build results, which are removed by `haskell.lib.justStaticExecutables`.

**Comment by arkrost** [comment]
So the right way to install `haskellPackages` is use the one in `nixpkgs`? I am confused because "haskell.section.md" suggests to use the attribute path `haskellPackages`...

**Comment by cdepillabout** [comment]
This looks to me like another bug introduced by https://github.com/NixOS/nixpkgs/pull/78738 (and partly fixed in #87881).

@Infinisil has described an approach that should fix this, https://github.com/NixOS/nixpkgs/pull/84985#pullrequestreview-405946347, although it hasn't been implemented yet.

Ping @peti and @roberth as well.

**Comment by roberth** [comment]
Here's the relevant bit from Infinisil:

> I think a proper fix for this would be to only link libraries to $out/lib/links that have non-colliding names, while leaving the others in the dynamic-library-dirs of each individual package.

Making `enableSeparateBinOutput` the default would be great but is only a partial solution to these build errors (and it's a lot of work!). I don't think we need to explore that here, or `justStaticExecutables` for that matter.

**Comment by arkrost** [comment]
Thanks for your responses. Now I understand more. I'll close the ticket.
