### ISSUE TITLE
Since installing texlive.combined.scheme-full, system updates cause recompilations

### ISSUE THREAD

**Issue by est31** [NixOS/nixpkgs#88045]
**Describe the bug**

Since I've added `texlive.combined.scheme-full` to my system's configuration.nix, it's compiling some tex related packages manually whenever I'm updating my system. Why is it not cached on hydra? Biber is broken for me with anything other than `texlive.combined.scheme-full`.

**Notify maintainers**
@veprbl

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.11, NixOS, 20.03.1896.025deb80b24 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1896.025deb80b24"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: texlive.combined.scheme-full
```

**Comment by veprbl** [comment]
Not fixed. I think, the problem might be that we are missing `texlive.bin.core-big.meta.platforms`.

**Comment by est31** [comment]
I can't tell personally because I use the stable 20.03 branch of nix and the fixes went into master. looking forward to nix 20.09 fixing it!

**Comment by est31** [comment]
For some reason the issue still persists, I see tons of tex related packages being rebuilt at updates. From a feeling though, the issue has lessened.

**Comment by veprbl** [comment]
Just had another idea...
