### ISSUE TITLE
linuxPackages.rtl8821ce can't be compiled

### ISSUE THREAD

**Issue by lerhyd** [NixOS/nixpkgs#88068]
**Describe**
The package rtl8821ce can't be compiled due to errors.
https://github.com/NixOS/nixpkgs/blob/8568f68e612d203c54c14f39f38350d0043364b6/pkgs/os-specific/linux/rtl8821ce/default.nix

**Comment by msfjarvis** [comment]
The package is [rather behind](https://github.com/tomaspinho/rtl8821ce/compare/ab6154e150bbc7d12b0525d4cc1298ae196e45de...master) the upstream GitHub repository it tracks which is the cause of this breakage. Bumping it to master should suffice in resolving this.

**Comment by msfjarvis** [comment]
https://github.com/NixOS/nixpkgs/pull/88809 fixes this for me and WiFi works perfectly.
