### ISSUE TITLE
Android Studio needs a new maintainer

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#88071]
## Issue description

I don't use Android Studio anymore so it would be good to have a new maintainer. The Nix expression is unfortunately a bit complex but updates are usually really simple / trivial
(i.e. only `version`, `build`, and `sha256Hash` need to be updated in `pkgs/applications/editors/android-studio/default.nix`).
Would be great if the new maintainer could also test the emulator (my current test setup is unfortunately not compatible).

Update notifications can be obtained via the following feed:
https://androidstudio.googleblog.com/feeds/posts/default

I'm happy to help out if there are any questions/problems ;)
I could also review (code only as the update should already be tested) and merge the PRs in a timely manner if that would help.

Currently we track all three channels (`stable`, `beta`, and `dev`/`canary`) but this could be reduced to `stable` only (in which case we'd mark the other channels as broken so that users that depend on them could step up and start maintaining them).

**Comment by meutraa** [comment]
Hi there. I use android studio and nix almost daily for my work. I would be interested in taking over the maintenance of the three channels. 

I am new to contributing though, and while I do know how to use git, if you could provide a basic bulleted list of the steps I would take to do this work, it would make me a little less anxious.

**Comment by galagora** [comment]
Hi. I can help maintain the beta branch. This way, we can split the effort. I've updated and tested it by building and running a sample app on the emulator. Check out my pull request: #93558.

**Comment by galagora** [comment]
@meutraa, if you want to easily test the new versions (after forking, cloning, branching, and bumping the version), create a directory, say, `~/nix-contrib`, and add a `default.nix` file with the following code (assuming you cloned nixpkgs to `~/nixpkgs`):
```lang-nix
{nixpkgs ? (import ../nixpkgs {})}:
let
  pkgs = with nixpkgs; [
    androidStudioPackages.stable
    androidStudioPackages.dev
  ];
in nixpkgs.stdenv.mkDerivation {
    name = "env";
    buildInputs = pkgs;
}
```
`cd` into the directory, run `nix-shell`, then run `android-studio` or `android-studio-dev` inside the nix shell. Then you don't have to add the packages to your user environment.

**Comment by meutraa** [comment]
@galagora Thanks for that tip. That would be handy, since I only use the canary and stable builds in work.

**Comment by meutraa** [comment]
@primeos Do you still want to maintain the stable package or shall I take over that?

**Comment by meutraa** [comment]
Is there really a dev channel? I always found it odd dev was listed in the definitions.
https://developer.android.com/studio/archive

**Comment by primeos** [comment]
> Do you still want to maintain the stable package or shall I take over that?

No, I don't use it anymore so feel free to take it over ;)

> Is there really a dev channel?

There is: https://developer.android.com/studio/intro/update.html#channels
It's also mentioned in the news feed but IIRC there was never a difference between the two channels (maybe the Canary channel gets more or earlier updates than mentioned in the update feed).

Anyway, we could drop the `dev` channel if you want as it might only cause confusion.

**Comment by meutraa** [comment]
I think it might be a relic in the documentation and application. Since in the archives there are no dev builds, and they are not referenced at all in the /preview section of the site.

I would be a bit worried about dropping the package since some people might use it instead of the canary package.

**Comment by galagora** [comment]
We can mark it as broken and tell people to use canary. That way, we give people time to migrate.

**Comment by meutraa** [comment]
I agree with the above. 

This issue can be closed now.
