### ISSUE TITLE
ModemManager should set --filter-policy to STRICT

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#88089]
**Describe the bug**
I've been [told by upstream](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/212#note_502831) that we should consider passing `--filter-policy=STRICT` to our `ModemManager.service` unit.

**Additional context**
See https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/212

ping @worldofpeace @Mic92 @jtojnar @flokli

**Comment by jtojnar** [comment]
We just use the upstream service file, AFAICT.

**Comment by aanderse** [comment]
@jtojnar I had confirmed this ahead of time, you are correct. It sounds like `upstream` is considering changing their service file soon, but already prompting distros to go ahead now and apply `--filter-policy=STRICT`.

**Comment by jtojnar** [comment]
Looks like it was mentioned in 1.8 news: https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/blob/1.8.0/NEWS#L28

I guess we should add it then.

**Comment by flokli** [comment]
@aanderse can you file a PR that adds this?

**Comment by aanderse** [comment]
Yes.

**Comment by aanderse** [comment]
This was resolved a while ago.
