### ISSUE TITLE
oh-my-zsh prompt error

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#88088]
**Describe the bug**

Error on prompt:

```
cdls:cd:1: no such file or directory: -q /nix/store/4fcnmsxa6yyscjh2cak4hlp9w60d8xw5-oh-my-zsh-2020-05-11/share/oh-my-zsh
```

This happens on every prompt.

**To Reproduce**

No clue to be honest. I'm assuming just using `zsh` with `oh-my-zsh` should reproduce this.
It started happening after an upgrade today.

**Additional context**

Given the path in the error, I'm guessing this started happening after https://github.com/NixOS/nixpkgs/commit/a9e3b1103cb3ccf2c2a2083055c4d8ff0e8b518c

**Notify maintainers**

@NeQuissimus 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.09pre226012.b47873026c7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226012.b47873026c7"`
 - channels(syd): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- oh-my-zsh

# a list of nixos modules affected by the problem
module:
```

**Comment by NeQuissimus** [comment]
@NorfairKing Is this still an issue? It doesn't seem to happen to me

```shell
~ took 5s λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13-hardened, NixOS, 20.09pre226148.0f5ce2fac0c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(nequi): `""`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


~ took 3s λ echo $SHELL
/nix/store/k1mja3s1q2d2sff7c5580a6603gbv7nz-zsh-5.8/bin/zsh
```

**Comment by NorfairKing** [comment]
Hi @NeQuissimus yes I'm still having this problem.
But I made a mistake, this doesn't happen on every prompt but only when starting the shell.

It looks like the whole `-q /nix/...` is considered one argument somewhere.
But I don't have `-q` anywhere in my config..

**Comment by NorfairKing** [comment]
To be clearer, here is my config:
```
        programs = {
          zsh = {
            enable = true;
            ohMyZsh = {
              enable = true;
            };
          };
```

**Comment by NeQuissimus** [comment]
Do you have any plugins in your `~/.zshrc`?
I have tried various things but nothing reproduces the issue for me... :(

**Comment by NorfairKing** [comment]
@NeQuissimus It looks like my `.zshrc` is managed by `home-manager`:

```
    zsh = {
      enable = true;
      enableCompletion = true;
    };
```
It generates this file:
```
typeset -U path cdpath fpath manpath

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/a6lrf0glzangr2zssydys99ad2s6fbzq-zsh-5.8/share/zsh/$ZSH_VERSION/help"









# Oh-My-Zsh calls compinit during initialization,
# calling it twice causes sight start up slowdown
# as all $fpath entries will be traversed again.
autoload -U compinit && compinit



# Environment variables
. "/nix/store/ik4zkfwlma5z46ywbr1yn9nz2v9f5hb6-home-manager-path/etc/profile.d/hm-session-vars.sh"






# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/rycee/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"
HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


GPG_TTY="$(tty)"
export GPG_TTY


# Aliases
```

**Comment by NorfairKing** [comment]
I'm just also updated my usage of home-manager to see whether that fixes anything but it didn't.

**Comment by NorfairKing** [comment]
If I remove the `zsh` stuff from my home-manager config then I still have the same problem as well.

**Comment by NorfairKing** [comment]
It would really help if I could figure out where this error came from.

**Comment by NeQuissimus** [comment]
Very strange. For reference, my config is here:
https://github.com/NeQuissimus/DevSetup/blob/ca7d646f366c0a0a63e560d4a5dc9ef0e9f87639/nixos-common.nix#L165-L181
My zshrc: https://github.com/NeQuissimus/DevSetup/blob/067a4ecd59d8963da7dcc1f8eb94087bf97b4bb2/users/nequi/default.nix#L185-L233 (everything after the aliases is broken, just haven't had time to fix :D)

**Comment by NorfairKing** [comment]
I figured out that it doesn't happen if I only run a command: 
```
$ zsh -c echo          
          
$ zsh
cdls:cd:1: no such file or directory: -q /nix/store/iypj5c9ja4k3ad24nrnqs6am4z2a30kj-oh-my-zsh-2020-05-16/share/oh-my-zsh
```

**Comment by NorfairKing** [comment]
By removing `hastory`, the last command in my `interactive-shell.nix`, I noticed that the problem is after that but before the `precmd`:

```
/etc/zshrc:188: command not found: hastory
/etc/zshrc:192: command not found: hastory
cdls:cd:1: no such file or directory: -q /nix/store/iypj5c9ja4k3ad24nrnqs6am4z2a30kj-oh-my-zsh-2020-05-16/share/oh-my-zsh
hastory_gather_: command not found    
```

**Comment by NorfairKing** [comment]
I think this may be related: https://github.com/ohmyzsh/ohmyzsh/pull/8937
@NeQuissimus can you try overriding `cd` and see if you have the same problem?

**Comment by NorfairKing** [comment]
I can confirm that removing my `cd` override fixes the problem.

**Comment by NorfairKing** [comment]
If this is the problem then that will fix itself as soon as any oh-my-zsh version after 8937 is in nixpkgs.

**Comment by NeQuissimus** [comment]
Oh wow, good job figuring this one out :)
The latest oh-my-zsh should be coming down the unstable channel...

**Comment by NorfairKing** [comment]
@NeQuissimus Super! I'll ping you when I upgrade next time!

**Comment by NorfairKing** [comment]
This seems to have fixed itself now. Thanks @NeQuissimus !
