### ISSUE TITLE
Steam fails to start: `glXChooseVisual failed`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#88092]
**Describe the bug**
Steam fails to start with `Assertion Failed: Fatal Error: glXChooseVisual failed`.

**To Reproduce**
1. Install [steam](https://nixos.org/nixos/packages.html?attr=steam&channel=nixpkgs-unstable&query=steam) via nix.
2. Try running steam.

**Expected behavior**
Expected Steam to start.

**Screenshots**
![Screenshot from 2020-05-18 13-26-56](https://user-images.githubusercontent.com/226872/82260799-c2824600-9912-11ea-87a4-0787bb55b8be.png)

**Additional context**
Output and strace output here: https://gist.github.com/samuela/f8473d28d700a3fb36aaf9299f3cf7eb.

**Notify maintainers**

@jagajaga 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
skainswo@skainswo-X58A-UD3R:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-51-generic, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(skainswo): `"home-manager, nixpkgs-20.09pre226070.6feee80de09"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module: steam
```

**Comment by caaaaaa** [comment]
I get the same Message on Nixos since update to 20.03 (unstable is the same). 

It might have to do with the Nvidia card, i have a GeForce GT 560M with noveau drivers (i.e. nothing special set in configuration.nix). It does work with proprietary Nvidia drivers, but they bring a whole lot of other problems. 

@samuela what graphics card do you have?

**Comment by samuela** [comment]
I have an Nvidia gtx 1060. I'm running on Ubuntu and have installed the Ubuntu-recommended drivers (proprietary I think)

**Comment by samuela** [comment]
The nix package doesn't work, but the stream website install process works without any hiccups.

**Comment by caaaaaa** [comment]
It worked after removing and reinstalling steam. I don't know why that should make a difference, but since it has its own update mechanism outside of nix it is probably not our problem. 
I guess this can be closed?

**Comment by ssbothwell** [comment]
@caaaaaa what do you mean removing and reinstalling worked?

I tried to install it via `nix-env` and got this same error. I removed it with `nix-env -e steam` and then collected the garbage: `sudo nix-collect-garbage -d`. I'm still getting the same error when i reinstall.

**Comment by ssbothwell** [comment]
Fixed my issue with: https://github.com/NixOS/nixpkgs/issues/47932#issuecomment-447508411
