### ISSUE TITLE
Nixos-Taskserver: CA setup not done or incomplete

### ISSUE THREAD

**Issue by addcninblue** [NixOS/nixpkgs#88097]
**Describe the bug**
After following directions on the [manual](https://nixos.org/nixos/manual/index.html#module-taskserver) for setting up Taskserver, running the `nixos-taskserver user export group username` command fails with `Error: CA setup not done or incomplete, missing file /var/lib/taskserver/keys/ca.key.`.

**To Reproduce**
`configuration.nix`:
```
  services.taskserver = {                                                              
    enable = true;                                                                     
    fqdn = "example.com";                                                  
    listenHost = "::";                     
    organisations.group.users = [ "username" ];
  }; 
```

Export command: `nixos-taskserver user export group username`

**Expected behavior**
Export key was expected. Currently on Nixos 20.03.

I dug into it a bit more, and it seems that the file _is_ present at `/var/lib/taskserver/keys/ca.key`:

```
> sudo ls -al /var/lib/taskserver/keys/ca.key

-rw------- 1 root root 10722 May 18 15:17 /var/lib/taskserver/keys/ca.key
```

I then tried to change the permissions of the folder to allow `taskd` to reach it, but it still didn't work.

**Notify maintainers**
Unsure about maintainers

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/hzrq5ccamfkwdkl9gqqsh3ryprzvs044-bash-interactive-4.4-p23-dev
copying path '/nix/store/hzrq5ccamfkwdkl9gqqsh3ryprzvs044-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1896.025deb80b24 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"home-manager-20.03, nixos-20.03.1896.025deb80b24, nixpkgs-20.09pre226041.1ccc512b39a, unstable-20.09pre226012.b47873026c7, unstable-small-20.09pre226046.c19fa9be5ef"`
 - channels(addison): `"home-manager-19.09, unstable-small-20.09pre221158.5709214f80f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Thanks in advance!

**Comment by addcninblue** [comment]
I eventually fixed it by chmod'ing the certificates and running the nixos-taskserver as root; unsure if this is a bug or is intended behavior, but marking as closed for the time being.

**Comment by AkechiShiro** [comment]
I'm encountering the same issue, don't know whether it's intended or not.
