### ISSUE TITLE
Make it possible to override python3 pip

### ISSUE THREAD

**Issue by ktosiek** [NixOS/nixpkgs#8813]
The python3 package at the moment bundles pip 6, which makes it ignore the one in pythonPackages.
I need pip 7+ for building https://github.com/ktosiek/pip2nix/.

**Comment by ktosiek** [comment]
Turns out I only have problem with this on Debian host. I'll try enabling chroot builds and check again.

**Comment by ktosiek** [comment]
It looks like /nix/store/1kfab8hs8d94f9n0xcscn6pzyqkwc9g1-python3-3.4.3/lib/python3.4/site-packages is waaay before my overriden pip in sys.path. With pip bundled with Python, shouldn't the Python's site-packages be moved to the end of sys.path?
I still have to look at where is the PYTHONPATH set

**Comment by ktosiek** [comment]
Oh, it gets better: the wrapper script generated by buildPythonPackage creates the right PYTHONPATH (my pip before the bundled site-packages)

**Comment by ktosiek** [comment]
It looks like packages in buildPythonPackage's propagatedBuildInputs cannot override those bundled with Python, but packages in buildInputs can. And it's only at build time, wrappers are OK.
Is that by design?

**Comment by FRidh** [comment]
A while ago we upgraded to pip8 so I am closing this issue. If you have a specific issue or question, please open a new issue.
