### ISSUE TITLE
KRunner (KDE "Run Command") global keybinding broken after upgrade to 20.03 (+ workaround)

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#88175]
**Describe the bug**
After upgrading from 19.09 to 20.03, the KRunner global keybinding (alt+space) no longer works.

**To Reproduce**
1. Upgrade to 20.03
2. Boot into KDE Plasma
3. Press Alt+Spacebar
4. *eerie and uncomfortable silence, nothing happens*

**Expected behavior**
The command runner dialog should come up at the top of the screen.

**Screenshots**
N/A

**Additional context**
The problem appears to be that the global keybinding entry was changed somehow, in the "Global Shortcuts" KDE settings panel. 

The keybinding was still set for "Run Command":

![Global Shortcuts — System Settings Module_999](https://user-images.githubusercontent.com/1663259/82342401-dbadf400-99f1-11ea-8b35-d2c9d3dec458.png)

But there is now also a "KRunner" entry in "Application Launchers", which *did not* have any keybindings set, despite exposing the same actions:

![Global Shortcuts — System Settings Module_999(001)](https://user-images.githubusercontent.com/1663259/82342478-f8e2c280-99f1-11ea-82d1-68309be35487.png)

Assigning the keybinding to "KRunner" instead of "Run Command" fixes the issue.

**Notify maintainers**

@nyanloutre @ttuegel 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1896.025deb80b24 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(sven): `""`
 - channels(root): `"nixos-20.03.1896.025deb80b24"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FliegendeWurst** [comment]
Works for me on 21.11 without any workarounds.
