### ISSUE TITLE
ofono: crashes when OFONO_PLUGIN_PATH is unset due to patch

### ISSUE THREAD

**Issue by jonascarpay** [NixOS/nixpkgs#88178]
**Describe the bug**
The nixpkgs version of `ofono` is [patched](https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/tools/networking/ofono/default.nix#L26) to read a `OFONO_PLUGIN_PATH` environment variable. It crashes when this variable is not set.
This also means that the `services.ofono` service does not work if `services.ofono.plugins` is empty.

**To Reproduce**
Run `nix-shell -p ofono --run "sudo ofonod -n"`:
```console
$ nix-shell -p ofono --run "sudo ofonod -n"
ofonod[9865]: oFono version 1.31

(ofonod:9865): GLib-CRITICAL **: 01:26:47.382: g_strsplit: assertion 'string != NULL' failed
ofonod[9865]: Aborting (signal 11) [ofonod]
ofonod[9865]: ++++++++ backtrace ++++++++
-C: 'ofonod': No such file
ofonod[9865]: +++++++++++++++++++++++++++
```

**Expected behavior**
The same behavior you get as when `OFONO_PLUGIN_PATH` is set, or you compile without the patch:
```console
$ nix-shell -p ofono --run "sudo env OFONO_PLUGIN_PATH='' ofonod -n"
ofonod[9976]: oFono version 1.31
ofonod[9976]: parse_devices_reply: found 1st battery device: /org/freedesktop/UPower/devices/battery_BAT1
```

**Notify maintainers**
@jtojnar 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1896.025deb80b24 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1896.025deb80b24"`
 - channels(jmc): `"haskell-nix, nixpkgs-20.03.1795.d6c1b566b77, nur, unstable-20.09pre223023.fce7562cf46"`
 - nixpkgs: `/home/jmc/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - ofono
# a list of nixos modules affected by the problem
module:
  - ofono
```

**Comment by jtojnar** [comment]
Ugh, loooks like this line should be `if (plugin_path) {`

https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/tools/networking/ofono/0001-Search-connectors-in-OFONO_PLUGIN_PATH.patch#L101

**Comment by jonascarpay** [comment]
Ohhhh... I also completely missed it when looking at it
