### ISSUE TITLE
xfs_repair is missing from initrd

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#8820]
I've got a (possible) corrupted xfs partition mounted at /. Grub prints errors "not a correct xfs inode", but xfs_repair think the partition is ok. I'm not sure who is right.

I got a problem running xfs_repair on / partition. To run a xfs_repair I have to umount /. I booted a system with boot.debug1devices option. fsck.xfs is a simple script that tell user to run xfs_repair. The problem is there is no xfs_repair on initrd!

To run xfs_repair I had to mount root partition, copy xfs_repair and all its dependencies on initrd, umount root partition. It would be great if initrd contains xfs_repair out of the box. At least in cases when a computer has at least for one xfs partition.

**Comment by jagajaga** [comment]
Vanya, do you use release or do you use unstable?

**Comment by Profpatsch** [comment]
(triage) status?

**Comment by grahamc** [comment]
After a year of no response from @sorokin, I'm closing.

**Comment by ajs124** [comment]
I just ran into this issue! A NixOS (19.03) initrd includes fsck.xfs, but that is only a bash script, which cannot actually fix a xfs partition.

**Comment by dasJ** [comment]
Me too!
