### ISSUE TITLE
VirtualBox headless mode

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#8834]
According to [VirtualBox docs](https://www.virtualbox.org/manual/ch02.html#install-linux-host) Qt and SDL are not required when only headless mode is used. Would be nice to implement `headless = true` config switch for VirtualBox. This can reduce size when deploying to virtualbox in NixOps on EC2, for example.

**Comment by copumpkin** [comment]
:+1:

**Comment by domenkozar** [comment]
+1

**Comment by garbas** [comment]
:+1: @danbst you're willing to implement this?

**Comment by danbst** [comment]
@garbas ok, I'll find some time

**Comment by garbas** [comment]
@danbst awesome! :+1: could you assign yourself to this ticket?

**Comment by danbst** [comment]
@garbas, either I'm not fluent with GH ui or I have no rights to assign.

**Comment by danbst** [comment]
@garbas, I'm currently struck with running test https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/virtualbox.nix
I shall try to fix it first and then think about headless support. Though I'm limited in time and knowledge, so it won't be very fast

**Comment by garbas** [comment]
@danbst i'm also just getting familiar with permission system in gh.... weird that you can not assign somebody to the ticket. anyway i'll try to help as much as i can... i can not increase your time, but i can help you with knowledge (or find the right ppl). if you fail let me know how you failed and maybe i can help you.

**Comment by danbst** [comment]
Found out, that virtualbox cli test was broken after https://github.com/NixOS/nixpkgs/commit/1541fa351b4d664c51dddaeaa67ee0652892f405
Ping @edolstra in case he has quick fix
