### ISSUE TITLE
nixpkgs.overlays not working inside NixOS containers

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#88621]
**Describe the bug**

Since the introduction of the `containers.*.pkgs` option in  https://github.com/NixOS/nixpkgs/pull/85570 on master and https://github.com/NixOS/nixpkgs/pull/88402 for release-20.03, overlays defined in containers with `nixpkgs.overlays` are no longer working.

**To Reproduce**
Execute this test: https://github.com/NixOS/nixpkgs/pull/88619/commits/0eec48c89a147ccc057d9512b6b51aef104ae952

**Expected behavior**
Overlays should work inside the containers.

**Notify maintainers**
@adisbladis (author of the change)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1942.6d68b920eb2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(kea): `""`
 - channels(root): `"home-manager-20.03, nixos-20.03.1942.6d68b920eb2, nixos-19.09-19.09.2503.2efedf8fc74, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- containers.*.pkgs
- nixpkgs.overlays

# a list of nixos modules affected by the problem
module:
- nixos/modules/virtualisation/containers.nix
```

**Comment by pacien** [comment]
I propose to revert the change for the current stable release-20.03: https://github.com/NixOS/nixpkgs/pull/88619

The option seems useful and should be kept on master for the next release, but it needs to be fixed to work with overlays.

**Comment by boxofrox** [comment]
It appears 20.09 is affected by this.  While trying to upgrade to 20.09 my containers that use personal overlays fail to build.

```sh
# nixos-rebuild test
building Nix...
building the system configuration...
error: attribute 'fuzzyd' missing, at /etc/nixos/overlays/fuzzyd/modules/fuzzyd.nix:37:17
(use '--show-trace' to show detailed location information)
```

Looking at the git history for tag 20.09, I see ab37d7e in the history, but not the revert commit a808fe4, and commit logs for `nixos/modules/virtualization/containers.nix` does not include a fix for this bug.

@jonringer
