### ISSUE TITLE
mailutils tests fail on stdenv-updates after switch to GCC 4.8.

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#887]
I haven't looked too deeply into it, but couldn't find anything obvious on the web.

The test failures:

    Running /tmp/nix-build-mailutils-2.2.drv-0/mailutils-2.2/imap4d/testsuite/imap4d/fetch.exp ...
    FAIL: FETCH 3 BODY[1.MIME]
    FAIL: FETCH 4 BODY[2.2.1]
    FAIL: FETCH 4 BODY[2.2.1.TEXT]
    FAIL: FETCH 4 BODY[2.2.TEXT]
    FAIL: FETCH 5 BODY[2.TEXT]

Full build output: https://gist.github.com/falsifian/ad1fd6fbc097b5a4d321

The offending commit is e9b30710, which switches stdenv to GCC 4.8.0.

**Comment by domenkozar** [comment]
This is passing now, closing.
