### ISSUE TITLE
metasploit: package needs to be updated

### ISSUE THREAD

**Issue by rdesfo** [NixOS/nixpkgs#8870]
The metasploit package no longer builds.  I've [tried](https://github.com/rdesfo/nixpkgs/commit/81c41d5896b82a70469b989cafb9918d05bb5333#commitcomment-12037805) updating it myself, but I haven't been very successful.

If someone could point out my mistake I would gladly correct it and submit a PR.

**Comment by matthiasbeyer** [comment]
Is this issue still relevant?

@lethalman , @pSub (pinging you because you are able to close this if necessary)

**Comment by pSub** [comment]
Looks relevant to me, as there was no commit to metasploit that updates or fixes it.

**Comment by Profpatsch** [comment]
Current version: 3.3.1
Last stable version: 4.12

We definitely need a maintainer. @pSub is there a tag for `needs:maintainer`?
