### ISSUE TITLE
gotools package no longer installing gopls

### ISSUE THREAD

**Issue by roman** [NixOS/nixpkgs#88716]
**Describe the bug**

The `gotools` package [was relying on the fact](https://github.com/NixOS/nixpkgs/blob/1694c0b3f7ab9416f266e719001f74116878e1fa/pkgs/development/tools/gotools/default.nix#L14-L19) that there was a `cmd/gopls` directory in go's tools repo. Unfortunately, this directory was removed on commit [`8647d4c87977ec65bfce87fe963652c71cd2e0db`](https://github.com/golang/tools/commit/8647d4c87977ec65bfce87fe963652c71cd2e0db)

Not sure when the `gopls` binary stopped being shipped in nixpkgs.

**To Reproduce**
1. install latest version of the `gotools`
2. Search the `bin` directory of the output from the derivation and assert the `gopls` command is no longer there
3. n/a

**Expected behavior**
The gopls command should be available, it's a crucial binary, as it is used for lsp support

**Notify maintainers**
@rvolosatovs 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-51-generic, Ubuntu, 18.04.3 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.1`
 - channels(roman): `"nixpkgs-20.09pre218717.05f0934825c"`
 - nixpkgs: `/home/roman/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `gotools`
```

**Comment by rvolosatovs** [comment]
`gopls` is now available in `gopls` package. This was changed in https://github.com/NixOS/nixpkgs/pull/85868

**Comment by roman** [comment]
Uhm, silly me, didn't check there was an independent `gopls` package now. 

Would you say it is a good idea to update the referenced comment in this ticket? I can volunteer to update the comment.

**Comment by rvolosatovs** [comment]
> Uhm, silly me, didn't check there was an independent `gopls` package now.
> 
> Would you say it is a good idea to update the referenced comment in this ticket? I can volunteer to update the comment.

Yes, I think so. Let's add a reference to this issue as well.

**Comment by roman** [comment]
Created the PR: https://github.com/NixOS/nixpkgs/pull/89372

Apologies for the delay
