### ISSUE TITLE
cargo: problem with CA certificates

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#8872]
using `15.06pre65267.6ad8fab (Dingo)` and `cargo 0.3.0 (a2dd2ac 2015-06-24) (built 2015-07-17)` leads to this error:
```
cargo test --verbose                                                                                        
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  Peer certificate cannot be authenticated with given CA certificates
```
What can I do?

**Comment by vcunat** [comment]
Find how it searches for certificates. Curl with our CA accepts the URL.

**Comment by flosse** [comment]
I see. It seems to be related to https://github.com/rust-lang/cargo/issues/976.
@sjmackenzie & @telotortium  are you able to run `cargo v0.3.0` with `rustc v1.1.0`?

**Comment by flosse** [comment]
using `cargo 0.3.0-nightly (14e8ed9 2015-06-15) (built 2015-06-16)` works fine.
But I still have no idea if this problem is nixos or cargo related :-\

**Comment by vcunat** [comment]
> A "simple" fix would be to rebuild cargo against openssl 1.0.2b or superior.

This might be another work around. We do have that version in nixpkgs, only it isn't the default one yet.

**Comment by flosse** [comment]
> We do have that version in nixpkgs, only it isn't the default one yet.

so we cold write this:

```
  cargo = callPackage ../development/tools/build-managers/cargo {
    rustPlatform = rustCargoPlatform;
    openssl = openssl_1_0_2;
  };
```

Or what would be the problem with that?

**Comment by vcunat** [comment]
None that I know of.

**Comment by telotortium** [comment]
A preliminary run of `git bisect` between `git bisect start 6eab106 71c1644` (6eab106 was the master as of yesterday, 71c1644 is the merge commit for #8668) found 333f145 to possibly be the first bad commit (I ran `git bisect run sh -c "nix-env -f $PWD -qa 'cargo-0.3.0' >/dev/null 2>&1 || exit 125; nix-build $PWD -A cargo"` to attempt building cargo at each commit while skipping commits for which cargo hadn't been updated to 0.3.0, which was merged from #8668).

**Comment by globin** [comment]
I haven't experienced this for quite a while, can be closed.

**Comment by vcunat** [comment]
Reopen if you experience again.
