### ISSUE TITLE
haskell.compiler.ghcHEAD can not be built on aarch64-linux

### ISSUE THREAD

**Issue by L-as** [NixOS/nixpkgs#88738]
**Describe the bug**
When trying to build haskell.compiler.ghcHEAD, I encounter errors in the compilation process.

**To Reproduce**
nix-build '\<nixpkgs\>' -A haskell.compiler.ghcHEAD

**Expected behavior**
It should build, since ghc8101 builds fine.

**Additional context**
```
[...]
for dir in libraries/time/dist-install/build/Data/ libraries/time/dist-install/build/Data/Time/ libraries/time/dist-install/build/Data/Time/Calendar/ libraries/time/dist-install/build/Data/Time/Clock/ libraries/time/dist-install/build/Data/Time/Clock/Internal/ libraries/time/dist-install/build/Data/Time/Format/ libraries/time/dist-install/build/Data/Time/Format/Format/ libraries/time/dist-install/build/Data/Time/Format/Parse/ libraries/time/dist-install/build/Data/Time/LocalTime/Internal/; do if test ! -d $dir; then mkdir -p $dir; fi done
grep -v ' : [a-zA-Z]:/' libraries/time/dist-install/build/.depend-v-p-dyn.haskell.tmp > libraries/time/dist-install/build/.depend-v-p-dyn.haskell.tmp2
rts/Libdw.c:363:6: error: #error "Please implement set_initial_registers() for your arch"
  363 | #    error "Please implement set_initial_registers() for your arch"
      |      ^~~~~
rts/ghc.mk:585: rts/dist/build/.depend-v-p-dyn-l-debug-thr-thr_debug-thr_l-thr_p-debug_dyn-thr_dyn-thr_debug_dyn-l_dyn-thr_l_dyn-thr_debug_p-debug_p.c_asm: No such file or directory
make[1]: *** [rts/ghc.mk:586: rts/dist/build/.depend-v-p-dyn-l-debug-thr-thr_debug-thr_l-thr_p-debug_dyn-thr_dyn-thr_debug_dyn-l_dyn-thr_l_dyn-thr_debug_p-debug_p.c_asm] Error 1
make[1]: *** Waiting for unfinished jobs....
[...]
```
[Source code for rts/Libdw.c](https://gitlab.haskell.org/ghc/ghc/-/blob/master/rts/Libdw.c)

**Notify maintainers**
@MarcWeber @kosmikus @peti 

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.7.0-rc6-10+, NixOS, 20.09pre225931.32b8ed73809 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: haskell.compiler.ghcHEAD
# a list of nixos modules affected by the problem
module:
```

**Comment by cdepillabout** [comment]
@L-as Could you look through the old PRs that are updating the GHC derivations here on github?

Most of them are sent by a single person, but I forget what his handle is.  If you cc him here, he might have a good idea about how to fix it.  (Although I don't know if he is an aarch64 user.)

@L-as for what it's worth, I don't think many people care about ghcHEAD, because many packages end up being incompatible with it.  I've personally never met someone that often uses ghcHEAD and is not a GHC hacker.  I don't think it is generally considered high-priority here in nixpkgs.

----------------------------------

Also, cc @Ericson2314 (I think you do a lot of cross compilation stuff?  Or maybe I'm

**Comment by L-as** [comment]
@cdepillabout I ran into it when I was trying to compile the linear haskell fork, where I just changed the src attribute for the ghcHEAD attribute, and noticed that regular ghcHEAD had the exact same problem.

I assume you're talking about @ggreif, since he updated ghcHEAD last.

**Comment by cdepillabout** [comment]
Hasn't been any activity on this in a while, and we now have compilers with linear haskell available.  I'll go ahead and close.
