### ISSUE TITLE
dnsmasq should have dependency on networking.extraHosts for restarting purposes

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#8874]
I removed an entry from networking.extraHosts and ran `nixos-rebuild switch`. However the old value was still cached by dnsmasq, so I had to manually restart that service. NixOS should ideally be smart enough to realize itself that changing /etc/hosts and rebuilding implies restarting dnsmasq

**Comment by joachifm** [comment]
I think `systemd.services.dnsmasq.restartTriggers` is what you're looking for.
