### ISSUE TITLE
Warnings about uninitialized variables during GRUB install

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#8876]
I got this warning when updating to latest master (49791a4dd46a604f04e3bdfdd9e3f513d9b6f389):

```
$ sudo nixos-rebuild switch -I nixpkgs=.
...
updating GRUB 2 menu...
Use of uninitialized value $efiMountPoint in scalar chomp at /nix/store/scz75l9qar1494fpg1y3mhsfdvy7q1pc-install-grub.pl line 456, <FILE> line 4.
Use of uninitialized value in string ne at /nix/store/scz75l9qar1494fpg1y3mhsfdvy7q1pc-install-grub.pl line 507.
```

**Comment by bjornfor** [comment]
(It completed successfully though.)

**Comment by wkennington** [comment]
Yeah that section of code is just for change detection so chomp failing is
not a big deal as the empty string will differ in the efisysmountpoint and
force a reinstall.

**Comment by bjornfor** [comment]
Ok. But it looks like we don't know what we're doing :-)  Better make those warnings go away.

**Comment by bjornfor** [comment]
This still happens. I put milestone 15.09 because I think it gives a really bad impression of the project when greeted with such warning/errors (although not fatal) in the installer.

**Comment by Profpatsch** [comment]
(triage) does it still happen @

**Comment by bjornfor** [comment]
This is fixed! Tested on NixOS 16.03 and 16.09pre/unstable/master. Thanks for the reminder, @Profpatsch.

**Comment by magnetophon** [comment]
I just updated 17.03, and got 2 of these warnings:
```
Use of uninitialized value in numeric comparison (<=>) at /nix/store/w6mb7x0kngq9wmgl0bscfghf32ry6wa6-install-grub.pl line 405.
Use of uninitialized value in concatenation (.) or string at /nix/store/w6mb7x0kngq9wmgl0bscfghf32ry6wa6-install-grub.pl line 420.
```
nixos-version: ``17.03.1247.05126bc850 (Gorilla)``

**Comment by magnetophon** [comment]
I just updated 17.03, and got 2 of these warnings:
```
Use of uninitialized value in numeric comparison (<=>) at /nix/store/w6mb7x0kngq9wmgl0bscfghf32ry6wa6-install-grub.pl line 405.
Use of uninitialized value in concatenation (.) or string at /nix/store/w6mb7x0kngq9wmgl0bscfghf32ry6wa6-install-grub.pl line 420.
```
nixos-version: ``17.03.1247.05126bc850 (Gorilla)``

**Comment by bjornfor** [comment]
Cannot reproduce on NixOS 18.03.132192.ce0d9d638de (Impala):

```
$ sudo nixos-rebuild boot
...
updating GRUB 2 menu...
(no more output, success)
```
