### ISSUE TITLE
openttd: Use XDG specification?

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#88760]
## Issue description

OpenTTD as it is currently packaged does not support the XDG base directory specification.
According to https://bugs.openttd.org/task/6630 OpenTTD can support it if libxdg-basedir is available.
I've tested this locally and indeed it works if I add libxdg_basedir to the buildInputs.
But, adding this would be surprising behaviour to current users, since OpenTTD may suddenly start looking in a different place for its mods and saves and such.
Is this something we'd want to change in nixpkgs, or maybe hide it behind a flag? I can open a PR for it but I'd also be happy leaving it in my local config.

**Comment by veprbl** [comment]
It's a game, so it's unlikely that people will mind a change.

cc @fpletz
