### ISSUE TITLE
Package Request: Subspace

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#88769]
**Project description**
A simple WireGuard VPN server GUI.

**Metadata**

* homepage URL: https://github.com/subspacecommunity/subspace
* source URL: https://github.com/subspacecommunity/subspace
* license: mit
* platforms: linux

**Comment by Sohalt** [comment]
I've briefly looked into this and found subspace to be a fairly poor fit for NixOS. The codebase is pretty tightly coupled to their Docker deployment and of somewhat questionable quality.
Maybe Tailscale, which is already packaged for NixOS and even has a module also works for you?

**Comment by devhell** [comment]
Thank you for your assessment @Sohalt, Tailscale requires an account with them though, no?

I was after something that would allow easy management of dozens of WG client peers on NixOS (similar perhaps to https://github.com/vx3r/wg-gen-web).

I will close this now since there's no point including something that is a poor fit. :)
