### ISSUE TITLE
Sidequest No GSettings schemas

### ISSUE THREAD

**Issue by NicolasGuilloux** [NixOS/nixpkgs#88781]
**Describe the bug**
When I go in the "Install APK file from folder" tab on KDE, I get the following critical error and have SideQuest crashed. I tried on another desktop with the same configuration except Gnome installed on it and it works perfectly.

I use the 20.03 channel to install SideQuest

```sh
(sidequest:5848): GLib-GIO-ERROR **: 16:43:17.961: No GSettings schemas are installed on the system
 ```

**To Reproduce**
1. Use KDE plasma desktop environment
2. Start SideQuest
3. Click on the "Install APK file from folder" tab

**Expected behavior**
Should display a dialog to pick a file

**Screenshots**
![image](https://user-images.githubusercontent.com/4090627/82757177-037ccd80-9ddf-11ea-93d5-648b5bde41d4.png)
![image](https://user-images.githubusercontent.com/4090627/82757194-15f70700-9ddf-11ea-93be-badba1172887.png)

**Additional context**
I installed SideQuest using Home Manager from the main nixos configuration.

```nix
{ config, lib, pkgs, ... }:
{
	home-manager.users.nover = {
		# Packages
		home.packages = with pkgs; [
			sidequest
			discord
			simplenote
			steam
			minecraft
		];
	};
}
```

**Notify maintainers**
@joepie91 @rvolosatovs 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(nover): `"home-manager-20.03, nixos-20.03.1950.48723f48ab9, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - channels(root): `"nixos-20.03.1950.48723f48ab9, home-manager-20.03, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by confususs** [comment]
I'm curious, were you able to resolve this? I tried several variations of adding the `wrapGAppsHook`, but unfortunately I couldn't get it to work.

**Comment by davidgarland** [comment]
Same issue here 4-5 years later, curious what the fix was..

**Comment by NicolasGuilloux** [comment]
Hello! Sorry, I didn't see the first comment.
It has been a long time, and I don't remember how I had it fixed. From what I can remember, just an update fixed it. Maybe it was a side effect from another program installed on the machine.

I'm sorry, I don't have more information but feel free to open another issue :)
