### ISSUE TITLE
copy to clipboard is broken in mupdf-gl

### ISSUE THREAD

**Issue by aindlq** [NixOS/nixpkgs#88805]
**Describe the bug**
Clipboard is broken in mupdf-gl because it should be used with its own fork of `freeglut` (http://git.ghostscript.com/?p=thirdparty-freeglut.git;a=summary).

**To Reproduce**
Open any pdf file with `mupdf-gl` and try to copy anything to the clipboard with right mouse button selection.

**Expected behavior**
Text that is selected when right mouse button is pressed should be copied into the clipboard.

**Additional context**
see https://bugs.ghostscript.com/show_bug.cgi?id=699079#c1
> However, since you mention not being able to copy the selection at all, you should be aware that you MUST build with OUR copy of FreeGLUT. The standard system FreeGLUT does NOT have copy & paste support. We have added clipboard support to our fork of FreeGLUT. I have tried to get our additions adopted upstream, but the maintainers are slow to respond, so please use our version of freeglut when building mupdf.

**Notify maintainers**
@vrthra @fpletz

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1950.48723f48ab9, unstable-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mupdf
# a list of nixos modules affected by the problem
module:
```

**Comment by wamserma** [comment]
The root cause is [this issue](https://github.com/NixOS/nixpkgs/issues/104017), so closing this as a duplicate.
