### ISSUE TITLE
Patch systemd-nspawn to check /etc/localtime agains /etc/zoneinfo instead of /usr/share/zoneinfo

### ISSUE THREAD

**Issue by Jumblemuddle** [NixOS/nixpkgs#88852]
**Describe the bug**
Whenever a `systemd-nspawn` instance is started, this message is logged: `/etc/localtime does not point into /usr/share/zoneinfo/, not updating container timezone.`.
This seems to be due to NixOS using `/etc/zoneinfo` instead of `/usr/share/zoneinfo`.

**To Reproduce**
1. `mkdir tmp`
2. `systemd-nspawn -D tmp`
```
Spawning container tmp on /home/garrett/dld/tmp.
Press ^] three times within 1s to kill container.
/etc/localtime does not point into /usr/share/zoneinfo/, not updating container timezone.
execv(/bin/bash, /bin/sh) failed: No such file or directory
Container tmp failed with error code 1.
```

**Expected behavior**
`systemd-nspawn` should not log this message and should perform it's normal behavior of updating the container's timezone.

**Potential solution**
Add a patch to https://github.com/NixOS/nixpkgs/blob/a2d5351b6361cd33fe7e1806410067e10f1d44b7/pkgs/os-specific/linux/systemd/default.nix#L46 to update https://github.com/systemd/systemd-stable/blob/v245-stable/src/nspawn/nspawn.c#L1657 to look for NixOS's `/etc/zoneinfo` directory.

**Notify maintainers**
@andir @edolstra @flokli

**Comment by flokli** [comment]
Can you give us some more detail about your system, and the container you're trying to run?

We do patch some paths in `src/nspawn/nspawn.c` (and we could probably patch more), but I was able to do the following:

```
mkdir -p tmp
cd tmp
wget https://nspawn.org/storage/archlinux/archlinux/tar/image.tar.xz
sudo tar xvJf image.tar.xz
rm image.tar.xz
sudo systemd-nspawn -D . -M foo
```

without getting the error message.

**Comment by Jumblemuddle** [comment]
Huh, that's strange.

Is your `localtime` file somehow pointing to `/usr/share/zoneinfo`?
`ls -l /etc/localtime`: `/etc/localtime -> /etc/zoneinfo/America/Chicago`.

I'm running the latest Archlinux bootstrap archive.
https://www.archlinux.org/download
https://mirrors.acm.wpi.edu/archlinux/iso/2020.05.01/archlinux-bootstrap-2020.05.01-x86_64.tar.gz

I unarchive this file and then run `sudo systemd-nspawn -D root.x86_64` (`root.x86_64` is the root folder of the bootstrap image.)

```
> sudo systemd-nspawn -D root.x86_64
Spawning container root.x8664 on /$path/root.x86_64.
Press ^] three times within 1s to kill container.
/etc/localtime does not point into /usr/share/zoneinfo/, not updating container timezone.
[root@root ~]#
```

I'm running NixOS with the `https://nixos.org/channels/nixos-20.03` channel and `systemctl --version` gives me `systemd 243`.

My timezone is configured via the `time.timeZone` NixOS configuration property.

**Comment by flokli** [comment]
Can you check with unstable?

**Comment by Jumblemuddle** [comment]
I'd rather not update my entire system to the unstable channel at the moment. Is there an easy way to update only systemd perhaps?

**Comment by Jumblemuddle** [comment]
It's worth noting that this doesn't appear to cause any issues, so I'd be alright with just closing it unresolved. I just figured it would be an easy fix. I'm surprised to learn that it doesn't happen on your machine though.

**Comment by flokli** [comment]
You could set `systemd.package` in your NixOS configuration, and import nixpkgs from an unstable nixpkgs:

https://discourse.nixos.org/t/installing-only-a-single-package-from-unstable/5598/4

**Comment by Jumblemuddle** [comment]
Huh, apparently something between `systemd 243` and `systemd 245` fixed it. :man_shrugging:
It still seems like hard-coded paths that are uniquely different in NixOS should perhaps be patched, but this solved my issue.
