### ISSUE TITLE
nix-prefetch-docker skopeo: command not found

### ISSUE THREAD

**Issue by danstn** [NixOS/nixpkgs#88854]
**Describe the bug**
Running `nix-prefetch-docker` fails with `skopeo: command not found`

**To Reproduce**
```
$ nix-prefetch-docker --image-name alpine --image-tag 3.10.5 --arch amd64                            
/nix/store/882jy9my0jkqk8c6ac1j2bw7b8xa8w8g-nix-prefetch-docker/bin/.nix-prefetch-docker-wrapped: line 42: skopeo --insecure-policy --tmpdir=: command not found
```

**Extra info**
On [line 42](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/docker/nix-prefetch-docker#L42) of that script scopeoCmd isn't called correctly. Seems like [this commit](https://github.com/NixOS/nixpkgs/commit/42232493a378bb901b47214a71364ad654fedb36#diff-d84fec21e79483ecff51f49cefb83371R42) introduced the problem in this PR https://github.com/NixOS/nixpkgs/pull/87821. @zowoq

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/88856
