### ISSUE TITLE
Package Request: cargo-sort-ck - rust tool

### ISSUE THREAD

**Issue by neonphog** [NixOS/nixpkgs#88904]
**Project description**
A tool to check that your Cargo.toml dependencies are sorted alphabetically.

**Metadata**

* homepage URL: https://github.com/DevinR528/cargo-sort-ck
* source URL: https://github.com/DevinR528/cargo-sort-ck
* license: MIT/Apache-2.0
* platforms: unix, linux, darwin, windows

**Comment by SCOTT-HAMILTON** [comment]
Available at my nur repo http://nur.nix-community.org/repos/shamilton/.
Not sure if this is worth the PR on Nixpkgs?

**Comment by SCOTT-HAMILTON** [comment]
@neonphog please close.
