### ISSUE TITLE
bump mongodb-compass from 1.17 -> 1.21 (crashes on nixos-unstable)

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#88971]
**Project description**

I wanted to try mongodb-compass for a new project but the nixos-unstable version crashes on startup. I tried a 30sec bump but it's more involving apparently:

https://www.mongodb.com/download-center/compass

```
➜ nix-build -A mongodb-compass                                                                                                ~/nixpkgs
these derivations will be built:
  /nix/store/5jbpg1vk0gzbzf9y6bqjda67xi197s0b-mongodb-compass-1.21.2.drv
building '/nix/store/5jbpg1vk0gzbzf9y6bqjda67xi197s0b-mongodb-compass-1.21.2.drv'...
tar: ./usr/lib/mongodb-compass/chrome-sandbox: Cannot change mode to rwsr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
dpkg-deb: error: tar subprocess returned error exit status 2
note: keeping build directory '/tmp/nix-build-mongodb-compass-1.21.2.drv-0'
```
If anyone has another mongodb gui to recommend I would be glad to try it.

**Comment by teto** [comment]
I dont care anymore as I've discovered robo3t that works very well. Leaving open though since the problem still exists.

**Comment by wamserma** [comment]
FTR, the issue is the sticky bit on `chrome-sandbox`. `dpkg-deb -x` tries to preserve permissions when extracting. See also https://github.com/NixOS/nixpkgs/issues/89482

**Comment by emanueleperuffo** [comment]
See https://github.com/NixOS/nixpkgs/issues/86126#issuecomment-662842282.

**Comment by SuperSandro2000** [comment]
PR #98198 closes this issue.
