### ISSUE TITLE
fetchgit fetches submodules sequentially instead of in parallel

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#88982]
**Describe the bug**
`fetchgit` clones each submodule in sequence instead of in parallel, which is unnecessarily slow for repos that have a lot of submodules (such as `bat` which has 64 direct submodules).

At first I thought this was because git's `submodule.fetchJobs` setting defaults to `1`, but it turns out `fetchgit` doesn't even use that, it instead recursively clones the submodules by hand. @nbp it looks like you added this 10 years ago; is there any reason we can't just use `git submodule update --init --recursive` today?

I don't know why it doesn't just use git's built-in submodule handling, doing so would make fixing this trivial. Parallelizing the manual clone loop seems a lot more complicated (especially because of the problem of mixed output).

**To Reproduce**
1. Build `bat.src` from scratch. (Edit: `bat` was recently updated to not use submodules anymore. This can be reproduced using an older version)

**Expected behavior**
It should clone the repo in a reasonable amount of time.

**Notify maintainers**
Last few changes to `fetchgit/nix-prefetch-git` were @Mic92 and @bhipple

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(lily): `"nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/Users/lily/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fetchgit
# a list of nixos modules affected by the problem
module:
```

**Comment by domenkozar** [comment]
See #238467

**Comment by domenkozar** [comment]
Simplified in https://github.com/NixOS/nixpkgs/pull/238733
