### ISSUE TITLE
xkeyboard-config manpage

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#88990]
**Project description**
I wanted to consult the xkeyboard-config manpage via `nix shell nixpkgs#xkeyboard_config` but it doesn't exist (I checked the store as well).

Also seems like it's outdated when I looked at https://www.x.org/releases/individual/data/xkeyboard-config/ .

**Comment by lourkeur** [comment]
Resolved in master following #101695. The `nix shell` command does as intended now. Can you close this @teto?

**Comment by teto** [comment]
you wear your nickname proudly ! sure thing
