### ISSUE TITLE
Please, fix a patch in KeePass-2.45 so the package would able to build

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#88999]
**Describe the bug**

Upgrade reporting that a patch for KeePass-2.45 is malformed.

```fish
sudo -i nixos-rebuild switch --upgrade

...

unpacking source archive /nix/store/nr5iq1pdlr6ic9nv4hdgry0s12f034qz-KeePass-2.45-Source.zip
source root is .
setting SOURCE_DATE_EPOCH to timestamp 1590540982 of file ./.attr-0
warning: file ./.attr-0 may be generated; SOURCE_DATE_EPOCH may be non-deterministic
patching sources
applying patch /nix/store/4rlva4587sjvya7krd11sd0ryf5x8wla-fix-paths.patch
patching file KeePass/Native/NativeMethods.Unix.cs
patching file KeePass/UI/UISystemFonts.cs
patching file KeePass/Util/AppLocator.cs
patching file KeePass/Util/ClipboardUtil.Unix.cs
patching file KeePassLib/Native/ClipboardU.cs
patching file KeePassLib/Native/NativeLib.cs
patching file KeePassLib/Utility/MonoWorkarounds.cs
patching file KeePass/Forms/MainForm.cs
patch: **** malformed patch at line 23:                                 m_pluginManager.AddMenuItems(PluginMenuType.Main, tsicM, tsiPrevM);


```

So you can choose all your keys and passwords, or a software update.

**To Reproduce**

```
# derivation.nix

let

  keepass-with-plugins = pkgs.keepass.override {
      plugins = [
        pkgs.keepass-keeagent
        pkgs.keepass-keepassrpc
      ];
  };

in {
  environment.systemPackages = with pkgs; [

    keepass-with-plugins

};

```

```

# Configurations

  environment.sessionVariables = {
    SSH_AUTH_SOCK = "\"$XDG_RUNTIME_DIR\"/keepass-ssh-agent.socket";
  };

```

**Expected behavior**

Patch working normally

**Notify maintainers**

@wnklmnn - recently updated the KeePass and a patch in #88157
@joncojonathan as the most recent maintainer

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.20, NixOS, 20.09pre214209.f098b0dd2cd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c, unstable-20.09pre226148.0f5ce2fac0c, stable-19.09.2503.2efedf8fc74, nixpkgs-20.09pre226586.571212eb839"`
 - channels(pyro): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wnklmnn** [comment]
Hi, 
I added to commits to my [keepass](https://github.com/wnklmnn/nixpkgs/tree/keepass) branch. 
One to add the missing string replacement variable which I missed to see in my update. 
The second commit would update keeagent to version 0.12.0 since version 0.10.1 is not comaptible with keepass 2.41+.

**Comment by NobbZ** [comment]
Can you make a PR from that branch?

**Comment by Anton-Latukha** [comment]
PR was merged.

Waiting until the changes arrive into `nixos-unstable`, since the last thing anyone wants is broken access & password storage.

**Comment by Anton-Latukha** [comment]
20 days, still not in `nixos-unstable`.

Well, you solved it, it is merged upstream. And I already overloaded and tested it in `nixpgs-unstable`.

Thank you.
