### ISSUE TITLE
nixos/networking: ICMPv6: RA: ndisc_router_discovery failed to add default route

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#89025]
**Describe the bug**
When a IPv6 [networking.defaultGateway6](https://nixos.org/nixos/manual/options.html#opt-networking.defaultGateway6) is configured and a RA (Router Advertisement) message sends the same information as the manually configured gateway then an error is logged:
```
[root@myhost:~]# journalctl SYSLOG_IDENTIFIER=kernel -f
-- Logs begin at Fri 2020-05-22 11:59:36 UTC. --
May 27 13:44:49 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:44:57 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:04 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:11 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:18 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:27 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:35 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:42 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:49 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
May 27 13:45:56 myhost kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
```

**To Reproduce**
1. Set the option [networking.defaultGateway6](https://nixos.org/nixos/manual/options.html#opt-networking.defaultGateway6) with the same information that is send by the RA messages.
2. Wait a few seconds

**Expected behavior**
The fact that the router is advertising its prefix is not incompatible with a manually configured gateway, therefore no error should be logged.

**Additional context**
Specifying a [networking.defaultGateway6.metric](https://nixos.org/nixos/manual/options.html#opt-networking.defaultGateway6.metric) (different than the one provided by RA) will avoid the route conflict and no error is logged.
```
[root@myhost:~]# ip -6 route show
::1 dev lo proto kernel metric 256 pref medium
2001:xxxx:xxxx:xxxx::/64 dev ens33 proto kernel metric 256 pref medium
fe80::yyyy:yyyy:yyyy:yyyy dev ens33 proto static metric 64 pref medium
fe80::/64 dev ens33 proto kernel metric 256 pref medium
default via fe80::yyyy:yyyy:yyyy:yyyy dev ens33 proto static metric 64 pref medium
default via fe80::yyyy:yyyy:yyyy:yyyy dev ens33 proto ra metric 1024 expires 597sec hoplimit 64 pref medium
```

**Notify maintainers**
@volth @flokli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03post-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  - nixos/networking
```

**Comment by flokli** [comment]
This message is a warning coming from the kernel.

If the network is announcing RAs, and you manually configure a gateway, but don't ignore RAs (via the corresponding `sysctl`s), this is kinda expected.

Sounds like a WONTFIX to me.

**Comment by datafoo** [comment]
> If the network is announcing RAs, and you manually configure a gateway, but don't ignore RAs (via the corresponding `sysctl`s), this is kinda expected.

Wouldn't ignoring RAs be a sensible default when manually configuring a gateway?

**Comment by flokli** [comment]
Not really - routers can still send RAs with prefix(es) not covered in the config, not send a default router, or send [more specific routes than the default router](https://tools.ietf.org/html/rfc4191).

It's probably fine to acknowledge the warning, or disable receiving RAs in your local config, if you explicitly want to configure it statically and know your setup, but we shouldn't default to disable receiving RAs on the distro level.
