### ISSUE TITLE
Disable syncthing's update notification

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#8910]
It's a bit annoying to see the web interface get spammed with error messages (due to not being able to update) every time a `syncthing` update is available.

After a bit of searching there seems to be a way to disable [updates](https://github.com/syncthing/syncthing/blob/master/build.sh#L61). However, I'm not at all familiar with `go`, and doubly not in the context of `nix`.

Would it be possible to build `syncthing` with updates disabled?

Thanks!

/cc @matejc @ctheune

**Comment by ctheune** [comment]
Interesting. Good idea. I for myself would like to keep it activated optionally because that popup is what reminds me to make an update PR. :)

**Comment by ctheune** [comment]
Looking at the link you posted this seems reasonable. Now. I'm not a committer, so I can't assign the issue to me, but I'd be happy to work on this the next time I update.

**Comment by devhell** [comment]
@ctheune Yes, you're right, I would have thought that it's rather practical as a reminder ;-). But as I've noticed now, the NixOS stable releases will not be getting timely updates and so those users will be stuck with this annoying pop-up. :-/

Either way, thanks a lot for looking into this :-)

**Comment by ctheune** [comment]
Hmm. There's also the option to set the environment variable

```
STNOUPGRADE     Disable automatic upgrades.
```

That might be even better.

**Comment by devhell** [comment]
@ctheune Interesting. It's up to you really, you're the maintainer. ;-)

**Comment by devhell** [comment]
Should we close this?

**Comment by ctheune** [comment]
Sorry, I've been really busy. I'm happy if any of those got implemented. When I tried to look at this the last time I got caught up in go build management and then there was a major restructuring. I'd be happy to keep this open.

**Comment by devhell** [comment]
Cool. We'll keep it open then. ;-)

**Comment by ctheune** [comment]
At the moment I think the update message is disabled - the current build process results in a release that thinks that it is not a real release and thus does not seem to update at all. At least I get this message (in the 0.12 branch).

I found that we could also set "buildFlags = [ "-tags noupgrade" ]" in the buildFromGithub function, but I haven't been able to prove that this actually does anything: the non-release version might be  superceding this setting.

**Comment by devhell** [comment]
Thanks for the update @ctheune!

**Comment by jagajaga** [comment]
Any more ideas or progress? :)

**Comment by devhell** [comment]
As far as I can see `syncthing` doesn't actually nag anymore when an update is available. Now, I don't know if that's something @ctheune fixed or if that's a change from upstream. Either way, it's gone now, and this can be safely closed. Thank you for reminding me @jagajaga!

**Comment by ctheune** [comment]
It's kinda an accident. It detects that it's not running from an official release package and thus stops the autoupdate. Could go away at anytime.

**Comment by devhell** [comment]
@ctheune Thanks for the info. We'll have to see :)
