### ISSUE TITLE
code-server

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#89110]
**Project description**
`code-server` lets one run a server, which serves the vscode UI from a browser. It is a bit different thant `vscode` in the same way as `vscodium`, in the way that it is debranded. I'd really like to use this, as vscodium currently seems to not work withe Microsoft Remote extensions (which is a shame - this would be a very powerful feature). 

I tried packing this, however the differences are big enough so that a modified version of [`vscodium.nix`](https://github.com/NixOS/nixpkgs/blob/91fce0fb2f4b79c6e4a3f4ea129c4e665197cd35/pkgs/applications/editors/vscode/vscodium.nix) was not sufficient to make the build succeed. Probably somebody with more experience on packaging node/electron stuff in Nix will be able to get this working fast.

For the sake of completeness my failed attempt at packaging this can be found here: https://github.com/wucke13/nixpkgs/blob/code-server/pkgs/applications/editors/vscode/code-server.nix

**Metadata**

* homepage URL: https://github.com/cdr/code-server
* source URL: https://github.com/cdr/code-server
* license: mit
* platforms: linux, darwin

**Comment by FRidh** [comment]
related PR https://github.com/NixOS/nixpkgs/pull/87258

**Comment by jupblb** [comment]
I believe this issue can be marked as resolved
