### ISSUE TITLE
pokerth in gnome3 crashes, but works in plasma5

### ISSUE THREAD

**Issue by reirob** [NixOS/nixpkgs#89113]
**pokerth does not work in gnome 3, on NixOS 20.03**
Installed pokerth on 20.03, it works nicely in KDE (plasma5), but when I am in Gnome (gnome3) then it crashes

**To Reproduce**

1. On NixOS 20.03, log in to Gnome 3 Desktop
2. Open a terminal
3. Type pokerth
You should get:

> #> pokerth
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: wayland-org.kde.kwin.qpa.
> 
> Aborted (core dumped)

**Expected behavior**
pokerth should start. It should be as well possible to start it without the terminal but from the gnome application start menu.

**Additional context**

I spoke with people in IRC on #nixos channel and they said that the issue is resolved in unstable and provided the link to this pull request: [](https://github.com/NixOS/nixpkgs/pull/84612).

And they adviced me to open this issue so that the solution might be backported to 20.03.

**Comment by jtojnar** [comment]
Linking the pull request here might be helpful.

**Comment by 06kellyjac** [comment]
Related: #84612
PR that (I think) fixed this in unstable

**Comment by reirob** [comment]
I just installed the unstable package and I can confirm that it works in gnome, after having logged out and restarting the display manager. However the HiDPI scaling does not work for this application under gnome (in KDE it works).

I don't know if this can be fixed too, but as a workaround I can start it from the terminal with:

`QT_SCALE_FACTOR=1.8 pokerth`

and it seems to be reasonable.

**Comment by alexarice** [comment]
I think this is fixed now
