### ISSUE TITLE
buildGoModule: vendoring doesn't copy C sources

### ISSUE THREAD

**Issue by betawaffle** [NixOS/nixpkgs#89128]
**Describe the bug**
Some modules-based packages build fine when using `modSha256`, but break when using `vendorSha256` because `go mod vendor` does not copy C files from the source.

**To Reproduce**
Attempt to build this package:

```nix
{ buildGoModule, fetchFromGitHub, lib }:

buildGoModule rec {
  pname   = "sqlc";
  version = "1.3.0";

  src = fetchFromGitHub {
    owner  = "kyleconroy";
    repo   = pname;
    rev    = "v${version}";
    sha256 = "1cj73zjbb1clc8c0dk8gzhzfycch5c6qfgzixc19kcpcq16sifyl";
  };

  vendorSha256 = "0y4n6w3dhplmkcd5lym7cngfn0h017sdzs2rw5bcabfyiyzm6dfa";

  subPackages = [ "cmd/${pname}" ];

  meta = with lib; {
    description = "Generate type-safe Go from SQL";
    homepage    = https://sqlc.dev;
    license     = licenses.mit;
    platforms   = platforms.linux ++ platforms.darwin;
  };
```

**Expected behavior**
It should build the `sqlc` binary with no errors.

**Notify maintainers**
@kalbasit

**Metadata**
I personally ran into this problem using nixpkgs @ 571212eb839d482992adb05479b86eeb6a9c7b2f, but it should be the same on master.

**Comment by Mic92** [comment]
cc @c00w

**Comment by Mic92** [comment]
I am surprised that `go mod vendor` does not handle that. 
I think you can call `modvendor` manually in `https://github.com/NixOS/nixpkgs/pull/86376/files#diff-e52a12f0ff2d93a44ea65f92f17aaac7R18` to copy the C code over.

**Comment by Mic92** [comment]
If we get more of these case we might extend our `buildGoModule` abstraction.

**Comment by c00w** [comment]
Honestly this is never going to work. The upstream go issue is
https://github.com/golang/go/issues/26366
but in short, go is stripping the c code semi intentionally and you really shouldn't be distributing c via go :)
If you look in the tree there are multiple cases where c code had to manually be copied into the vendor folder.

@betawaffle The simplest solution if you're using your own source code is to make a vendor folder with the correct source, then set ```vendorSha256 = null;``` in your nix derivation. Alternatively, manually constructing the vendor directory within nix may also solve your problem.

**Comment by betawaffle** [comment]
I figured out a workaround, so this isn't causing a problem for me anymore. Also, I think I agree that this isn't really reasonable to fix, though it's disturbing that it works in the non-vendored case, but not in the vendored case.

**Comment by doronbehar** [comment]
Someone at https://github.com/golang/go/issues/26366 mentioned they wrote a tool: https://github.com/nomad-software/vend .

**Comment by c00w** [comment]
@doronbehar Nice - Let me see if I can make that an option :)

**Comment by c00w** [comment]
@doronbehar Done :D

**Comment by Mic92** [comment]
thanks @c00w !

**Comment by blaggacao** [comment]
Upstream support for `go tools modvendor` seems at least _planned_ in some way &rarr; https://github.com/NixOS/nixpkgs/pull/102426

**Comment by eblechschmidt** [comment]
@betawaffle would you mind sharing your workaround? I'm quite new to NixOS and I'm also trying to get sqlc

**Comment by betawaffle** [comment]
> @betawaffle would you mind sharing your workaround? I'm quite new to NixOS and I'm also trying to get sqlc

I actually don't remember what the workaround was. Maybe @euank or @brhoades can re-discover it from the source?

**Comment by eblechschmidt** [comment]
Thank you for your answer. I found a workaround that works for me I posted over on discourse https://discourse.nixos.org/t/trouble-packaging-sqlc/18261/11

Is that workaround worth mentioning on the wiki for people running into similar problems or is it just an odd use case?

**Comment by euank** [comment]
@eblechschmidt I checked the commit log for @betawaffle original workaround, and it was:

```
overrideModAttrs = (_: {
  postBuild = ''
   ${modvendor}/bin/modvendor -copy="**/*.c **/*.h **/*.proto" -v
  '';
});
```

(the full derivation was the following)

<Details>

<summary>Original sqlc derivation</summary>

```nix
{ buildGoModule, fetchFromGitHub, lib, modvendor }:

buildGoModule rec {
  pname = "sqlc";
  version = "1.3.0";

  src = fetchFromGitHub {
    owner = "kyleconroy";
    repo = pname;
    rev = "v${version}";
    sha256 = "1cj73zjbb1clc8c0dk8gzhzfycch5c6qfgzixc19kcpcq16sifyl";
  };

  vendorSha256 = "1l0kshmml2qjfggfknadqwp991xfrhg1h569rblabccpni6y3l9x";

  subPackages = [ "cmd/${pname}" ];

  overrideModAttrs = (_: {
    postBuild = ''
      ${modvendor}/bin/modvendor -copy="**/*.c **/*.h **/*.proto" -v
    '';
  });

  meta = with lib; {
    description = "Generate type-safe Go from SQL";
    homepage = https://sqlc.dev;
    license = licenses.mit;
    platforms = platforms.linux ++ platforms.darwin;
  };
}
```

</Details>

This was for an older version of sqlc, and also I think an older version of buildGoModule, so I kinda suspect it won't work anymore.

What we've got now is to just use `runVend = true`, which got everything to work.

<Details>

<summary>Current derivation</summary>

```nix
{ buildGoModule, fetchFromGitHub, lib }:

buildGoModule rec {
  pname = "sqlc";
  version = "1.12.0";

  src = fetchFromGitHub {
    owner = "kyleconroy";
    repo = pname;
    rev = "v${version}";
    sha256 = "sha256-YlOkjqkhN+4hL1+KJ0TuqcbQXJad/bHZclgpgFPr4to=";
  };

  runVend = true;
  vendorSha256 = "sha256-DUYuTvI7vErXMXJiIKB371v/uyZwjrImKyXXooB43GQ=";

  subPackages = [ "cmd/${pname}" ];

  meta = with lib; {
    description = "Generate type-safe Go from SQL";
    homepage = https://sqlc.dev;
    license = licenses.mit;
    platforms = platforms.linux ++ platforms.darwin;
  };
}
```

</Details>

I think the `runVend = true;` solution to this is recommended way to deal with this problem nowadays, and has some documentation indicating that, it just didn't exist yet when this issue was first filed.

Hopefully that helps, @eblechschmidt

**Comment by eblechschmidt** [comment]
@euank I found a (more complex) workaround before but your solution works as good. I think my problem was that I was running into caching "problems" that came from my lack of knowledge how nix works.
