### ISSUE TITLE
nixos/dbus : Restarting the dbus service blocks for +5 seconds, waiting for a timeout on nscd

### ISSUE THREAD

**Issue by pstch** [NixOS/nixpkgs#89123]
**Describe the bug**

`systemctl restart dbus` often, but not always, blocks for 5 seconds (sometimes 10).

**To Reproduce**
1. `systemctl restart dbus`
2. `systemctl restart dbus`

*WARNING:* Do not run this from a graphical session, on my system it logged me out.

**Expected behavior**

Not blocking for 5 seconds.

**Additional context**

When running dbus-daemon manually, the same behaviour is exhibited (before exiting because of the missing socket). Because of that I was able to `strace` and identify the cause for these 5 second delays:

```
21:20:58 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
21:20:58 connect(5, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0
21:20:58 sendto(5, "\2\0\0\0\17\0\0\0\21\0\0\0systemd-timesync\0", 29, MSG_NOSIGNAL, NULL, 0) = 29
21:20:58 poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 0 (Timeout)
21:21:03 close(5)                       = 0
```

Or:

```
21:25:00 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
21:25:00 connect(5, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0
21:25:00 sendto(5, "\2\0\0\0\17\0\0\0\20\0\0\0systemd-network\0", 28, MSG_NOSIGNAL, NULL, 0) = 28
21:25:00 poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 0 (Timeout)
21:25:05 close(5)                       = 0
```

Full strace from one of the tests : 
[dbus-daemon-strace.txt](https://github.com/NixOS/nixpkgs/files/4697800/dbus-daemon-strace.txt)

**Notify maintainers**

I could not find specific maintainers for this module, so pinging the last committers.

cc @rnhmjoj 
cc @worldofpeace 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1950.48723f48ab9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services/system/dbus.nix
```

**Comment by peterhoeg** [comment]
The system wide dbus instance should have no impact on your graphical session so restarting it should be completely safe. I just tried and it was fine.

Can you show the output of `systemd-cgls` to show what it has launched directly?

**Comment by pstch** [comment]
Here is the output of `systemd-cgls --full` : [systemd-cgls.txt](https://github.com/NixOS/nixpkgs/files/4724322/systemd-cgls.txt).

Here is the output of `journalctl` when `dbus` is stopping : 
[dbus-restart-logs.txt](https://github.com/NixOS/nixpkgs/files/4724390/dbus-restart-logs.txt). We can see that the `display-manager` service fails because it `Failed to get D-Bus connection`. The display manager I use is LightDM.

Note that this particular problem might be best for another issue, here I was more interested in reporting the 5/10 second delay in restarting D-Bus.

**Comment by peterhoeg** [comment]
Can you share the full log with the start phase as well so we can see where the delay is?

**Comment by pstch** [comment]
Here is the output of "journalctl -f" while restarting dbus twice : [dbus-restart-logs.txt](https://github.com/NixOS/nixpkgs/files/4728105/dbus-restart-logs.txt). This was done on another machine, without a display manager.
 
These are the commands that were executed to restart dbus:

```
[root@tinix:~]# date; time systemctl restart dbus
Thu 04 Jun 2020 08:56:09 AM CEST

real	0m0.013s
user	0m0.001s
sys	0m0.004s

[root@tinix:~]# date; time systemctl restart dbus
Thu 04 Jun 2020 08:56:10 AM CEST

real	0m5.020s
user	0m0.002s
sys	0m0.004s

```

The problem is intermittent, and didn't show in the log I shared to show that the display manager fails, but it does happen on this machine as well. Most of the time, the first time I restart it there is no delay, and there is a ~5 seconds (sometimes more, sometimes less) delay on the following restart. However, in some cases, this delay happens at the first attempt to restart D-Bus.

I'm not sure if the `strace` logs I shared are relevant, since sometimes the delay is less than 5 seconds, and since as the logs show the delay is when stopping D-Bus rather than starting it.

**Comment by peterhoeg** [comment]
This is quite a few years old so I'm not sure it applies (although it seems like it does): https://wiki.ubuntu.com/DbusRestart

Basically this can be boiled down to "don't restart dbus".

**Comment by pstch** [comment]
Right. This is unfortunate as it means that the whole system must be restarted in order to apply security updates. Also, this link seems to be about applications not handling dbus restarts correctly, not about dbus blocking for a few seconds when restarting, but I guess it doesn't change much.

Closing the issue as it looks like we can't do much about this.
