### ISSUE TITLE
direnv tries to run bash from $PATH

### ISSUE THREAD

**Issue by akho** [NixOS/nixpkgs#89129]
**Describe the bug**
Installing direnv without having bash in `$PATH` makes the shell throw errors on every command

**To Reproduce**
1. No `bash` executable in `$PATH`
2. `nix-env -i direnv`
3. Do anything in the shell

**Expected behavior**
Direnv works regardless of presence of `bash` in `$PATH`.

**Notify maintainers**
@zimbatm 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84-microsoft-standard, Alpine Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `""`
 - channels(akho): `"home-manager, nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/home/akho/.nix-defexpr/channels/nixpkgs`

**Comment by akho** [comment]
Putting

    export DIRENV_BASH=$(nix eval -f ~/.nix-defexpr/channels/nixpkgs --raw bash)

in `.zshrc` before 

    eval "$(direnv hook zsh)"

solves this for me (but does not look like something I should have to have).

**Comment by zimbatm** [comment]
thanks for the report!

**Comment by akho** [comment]
Thank you! That was very quick.
