### ISSUE TITLE
Enable Microsoft python language server on Darwin

### ISSUE THREAD

**Issue by mjlbach** [NixOS/nixpkgs#89139]
**Project description**
In https://github.com/NixOS/nixpkgs/pull/85930, Darwin support was not included because of the lack of dotnet core support. As of https://github.com/NixOS/nixpkgs/pull/88750, that is now addressed and unavailable in unstable.

I managed to get python-language-server built by substituting the dependencies for osx-64 and disabling the post fixup phase of the derivation.
```
  postFixup = ''
    patchelf --set-rpath ${icu}/lib $out/lib/System.Globalization.Native.so
    patchelf --set-rpath ${openssl.out}/lib $out/lib/System.Security.Cryptography.Native.OpenSsl.so
  '';
```

Which patch libraries distributed as  dylib's under darwin. @thomasjm I know you had tested this on macOS, so I'm not sure if you already had the correct patch enabled.

**Comment by thomasjm** [comment]
@mjlbach I did not test on macOS

**Comment by mjlbach** [comment]
Ah, I'm sorry! It was @worldofpeace who mentioned it. My bad!

**Comment by thomasjm** [comment]
no worries, just wanted to avoid confusion

**Comment by mjlbach** [comment]
I'm going to close this since the package is archived in favor of pyright by Microsoft
