### ISSUE TITLE
Metrics job failure blocks nixpkgs-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#89152]
**Describe the bug**
Metrics job fails for nixpkgs:trunk https://hydra.nixos.org/build/120792505

I think it's the following command where it fails:
```
$ nix-env -f . -qa --drv-path --meta --xml --show-trace

error: while querying the derivation named 'chunkwm-0.4.9':
while evaluating the attribute 'buildInputs' of the derivation 'chunkwm-0.4.9' at /home/freddy/Code/libraries/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'apple-framework-Cocoa' at /home/freddy/Code/libraries/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:57:5:
while evaluating the attribute '__propagatedImpureHostDeps' of the derivation 'apple-framework-AppKit' at /home/freddy/Code/libraries/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:57:5:
attribute '__propagatedImpureHostDeps' missing, at /home/freddy/Code/libraries/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:191:36
```

cc @NixOS/darwin-maintainers  @vcunat

**Comment by vcunat** [comment]
I'm not sure if there's some error like this (as well), but in the past few days I suspected that the job is starting to hit RAM limit.  (When I started the box, it was OK with 4G RAM, now it has 6G for a long time.)

**Comment by vcunat** [comment]
BTW, any idea why https://status.nixos.org/ is showing old commits despite the channels having advanced?

**Comment by domenkozar** [comment]
cc @grahamc

**Comment by LnL7** [comment]
> BTW, any idea why https://status.nixos.org/ is showing old commits despite the channels having advanced?

The [scraper](https://status.nixos.org/grafana/d/fBW4tL1Wz/scheduled-task-state-channels-website?orgId=1&refresh=10s&fullscreen&panelId=6&from=now-7d&to=now) gets stuck sometimes.

**Comment by vcunat** [comment]
> in the past few days I suspected that the job is starting to hit RAM limit

I've watched it recently to run close (a couple hundred MBs) and the recent failures usually take many minutes instead of the usual few, so I'm fairly certain it's getting low on RAM.  I plan to cannibalize from another system to increase it by another 2G in 24h.

**Comment by vcunat** [comment]
Done now.  It looks green, too.  I expect the RAM will suffice for another year at least.
