### ISSUE TITLE
Update libclc

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#89187]
## Issue description

libclc is now part of the [llvm-project](https://github.com/llvm/llvm-project/tree/master/libclc) monorepo. it also has a different build system (cmake or ninja)

i tried to update it, but don't get it to build https://github.com/davidak/nixpkgs/tree/libclc

https://gist.github.com/davidak/55cba0d104cb8b69c58c01ecb9b6bc0d

upstream has a CI where it builds https://github.com/llvm/llvm-project/runs/718659557?check_suite_focus=true

please continue my effort. i hope it will fix the problem with geekbench and opencl

in this turn, it can get included in the LLVM infrastructure https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/llvm

cc @pSub @globin @vcunat @athas @DieGoldeneEnte

**Comment by athas** [comment]
libclc is really unloved.  I'm not sure what you mean by "included in the LLVM infrastructure", but I can take a swing at getting it building at all.

**Comment by davidak** [comment]
>I'm not sure what you mean by "included in the LLVM infrastructure"

maintain it as LLVM subproject, like https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/llvm/10/openmp.nix in that directory, so it will get updated when LLVM is

thanks for looking into it!

**Comment by jljusten** [comment]
@davidak: Is this fixed by #111065?

**Comment by davidak** [comment]
@jljusten yes. very nice
