### ISSUE TITLE
nodePackages: follow up track/clean/fix broken packages after switch to 12.x and 14.x in #89184

### ISSUE THREAD

**Issue by calbrecht** [NixOS/nixpkgs#89205]
Following packages were found to be broken (in the sense of not building at all) with `nodejs-10_x` before change already:

- [ ] `coc-imselect` /cc @eyJhb 
- [ ] `fast-cli-1.x` /cc @svanderburg 
- [ ] `git-ssb` /cc @patrl @matthewbauer 
- [x] `pulp` /cc @Mic92 -> fixed #89210
- [x] `insect` /cc @lilyball -> fixed #89210
- [ ] `node-red` 
- [ ] `node-inspector`
- [x] `stf` /cc @jollheef -> remove 
- [x] `ssb-server` /cc @FRidh -> remove

\
Following packages were found to be broken (not building) after the switch in `nodePackages` (that is with `nodejs-12_x`):

- [x] `dat` /cc @mmahut, build fails on `node-gyp-build` for `utp-native` -> update to `dat@next`

\
Following packages were found to be broken (not building) after the switch in `nodePackages_latest` (that is with `nodejs-14_x`):

- [x] `dnschain` /cc @rnhmjoj [dnschain](https://github.com/okTurtles/dnschain) received last code commit 5 years ago, a dependency [hiredis](https://github.com/redis/hiredis-node) (that breaks the build) is archived and won't get any updates. -> remove (incl. nixos module)

\
This issue is here to track and inform maintainers/adders of the packages about the broken state and decide about removing or fixing the broken packages.

**Comment by Mic92** [comment]
I would remove dnschain. It is no longer developed.

**Comment by rnhmjoj** [comment]
I know very well the state of dnschain. If migrating hiredis -> node-redis is non-trivial I don't think it will be ever fixed. I guess you can remove the package and the nixos module.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/89210

**Comment by prusnak** [comment]
It seems the `dat` issue has been already reported here: https://github.com/datproject/dat/issues/1162

Oddly enough it's been closed as `utp-native` is an optional dependency.

**Comment by FRidh** [comment]
Will need to remove `ssb-server` as I haven't been following it in a while.

**Comment by jollheef** [comment]
So far openstf does not support node newer than 8 because of some dependencies, so I guess you can just remove it.

**Comment by calbrecht** [comment]
@FRidh i can take care of it, just need the infos. Thanks :)
@jollheef, ok, i will remove it then. Thanks :)

**Comment by calbrecht** [comment]
@prusnak, ok, i will investigate dat. Thanks :)

**Comment by prusnak** [comment]
@calbrecht `dat@next` is fine. mmahut packaged it for me

**Comment by calbrecht** [comment]
@prusnak Thanks. I will update it with the other changes then (when all cases closed).

**Comment by arapov** [comment]
@calbrecht, I am new to processes nixos/nixpkgs [might] have... Could you help me? Is there anything I can do in order to make node-red fixes progress further?

**Comment by SuperSandro2000** [comment]
Broken packages should be moved to buildNpmPackage and fixed there. see #229475
