### ISSUE TITLE
haskell: generated package set contains deprecated versions

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#8924]
For example, `stack-9.9.9` was an accidental upload and is marked as deprecated on Hackage. When generating package sets, we should probably pick latest non-deprecated version instead.

Needs fixing in `cabal2nix` but filing here as nixpkgs problem, feel free to migrate (@peti)

**Comment by peti** [comment]
Well, the question is how to detect that this particular version is deprecated. How would `cabal2nix` know to avoid this version?

**Comment by peti** [comment]
I figure it out: the `preferred-versions` contains the necessary information.

**Comment by peti** [comment]
Commit 816e1f8 remedies this issue. I'll merge it to `master` soon -- just waiting for some more test builds.

**Comment by Fuuzetsu** [comment]
Diff looks good
