### ISSUE TITLE
cachix tests fail - report too old Nix

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#89255]
**Describe the bug**
See e.g. https://hydra.nixos.org/build/121014543

**To Reproduce**
Running the build locally reproduces it, though I can't see any relation with the reported Nix version on my system.

Speculation: some dependency of the cachix build might have "cached" version of the nix daemon running on its builder (and succeeded)?  Maintainers will probably know much quicker than me.

**Notify maintainers**
@domenkozar

**Comment by cole-h** [comment]
A clarification:

This appears to just be a test at parsing various Nix versions, not that Nix `2.0.1pre6053_444b921` is installed on whatever machine ran the build/test. This was discussed on @peti's livestream last Friday, where he filed this issue: https://github.com/cachix/cachix/issues/308.

(Here's the part of the stream where it occurred: https://www.twitch.tv/videos/635552787?t=00h28m33s.)
