### ISSUE TITLE
Agda builder ignores deprecated modules

### ISSUE THREAD

**Issue by alexarice** [NixOS/nixpkgs#89287]
**Describe the bug**
Agda builder doesn't build deprecated modules

**To Reproduce**
1. Build Standard library
2. Realise Data.List.Any.agdai is not there

**Expected behavior**
I'm not sure if these should be included by i expect it is a good idea. This issue may be specific to standard library. We build the `Everything.agda` which does not include deprecated modules. However I have had a quick look and cannot see an alternative to this.

**Notify maintainers**
@turion 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09pre227577.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre227577.135073a87b7, all-hies, emacs, home-manager, nixpkgs-wayland"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by turion** [comment]
IMHO, this is fine. Your documentation clearly states that an `Everything.agda` file is the default way to build something, following common Agda conventions. If that doesn't include certain files then it's primarily an upstream issue.

**Comment by alexarice** [comment]
I only ask because this currently blocks building agda-categories

**Comment by turion** [comment]
> I only ask because this currently blocks building agda-categories

How so? Does `agda-categories` need that module?

In that case I'd suggesting to patch `Everything.agda` or forking the standard library on our side temporarily, and file an upstream bug.

**Comment by turion** [comment]
Maybe I misunderstood. If `agda-categories` doesn't build because it needs a deprecated module, then `agda-categories` needs to be patched.

**Comment by alexarice** [comment]
I asked for a tag to be placed on a commit that works, though the commit that "works" depends on a deprecated module (`Data.List.Any`). This has been fixed in later commits so I have made a comment on the issue and will wait for the result of that. Worst case a patch could be used so I'll close this
