### ISSUE TITLE
stack creates executables with (potentially invalid) nix store paths

### ISSUE THREAD

**Issue by hyperfekt** [NixOS/nixpkgs#89280]
**Describe the bug**
Stack, the Haskell tool, creates executables in `~/.stack/setup-exe-cache` that refer to an interpreter contained in the Nix store path. If that store path gets garbage collected, this linker will disappear and stack will fail to build things.

**To Reproduce**
1. Run stack build with a particular GHC and Cabal version.
2. Remove linker used by Stack from the Nix store.
3. Run stack build again with the same-numbered GHC and Cabal version

**Expected behavior**
stack build executes without error.

**Actual behavior**
stack reports this error and fails the build:
```
/home/[username/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_[string of letters]_[cabal version number]_ghc-[ghc version number]: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Workaround**
Delete the file mentioned in the error message so that stack recreates it with a valid interpreter.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.03post-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.2013.e985ffea2d6"`
 - nixpkgs: `/cfg/patched`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - stack
# a list of nixos modules affected by the problem
module:
```

**Comment by cdepillabout** [comment]
@hyperfekt Unfortunately this is a `stack` problem, and it not directly related to nixpkgs.

Please file a bug report about this on the stack repo.

I'm going to ahead and close this, but if you think this is actually a nixpkgs problem, and there is something we could do in nixpkgs to fix this, please feel free to reopen.
