### ISSUE TITLE
some xfce panel plugins don't work unless defined in systemPackages

### ISSUE THREAD

**Issue by jficz** [NixOS/nixpkgs#89302]
**Describe the bug**
At least 
```
    xfce.xfce4-xkb-plugin
    xfce.xfce4-cpugraph-plugin
    xfce.xfce4-systemload-plugin
    xfce.xfce4-cpufreq-plugin
```
plugins are not available in xfce panel setup unless installed via `environment.systemPackages`. 

Tried `home-manager` packages and `nix-env -iA` options, neither works.

**To Reproduce**
1. `xserver.....xfce.enable = true`
2. `nix-env -iA xfce.xfce4-xkb-plugin` || `home.packages = [ ... pkgs.xfce.xfce4-xkb-plugin ...]`
3. setup plugin in xfce panel (panel -> add new items)

**Expected behavior**
_Keyboard plugin_ should be listed among available plugins.

**Actual behavior**
The plugin is *not* listed.

**Additional context**
Using `home-manager` for `~`.

**Notify maintainers**
@AndersonTorres 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre227577.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(user): `"home-manager, nixos-20.09pre227294.46f975f81e0, stable-19.09.2505.35eda4aede5, unstable-20.09pre227294.46f975f81e0"`
 - channels(test): `"home-manager"`
 - channels(root): `"nixos-20.09pre227577.135073a87b7, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: pkgs.xfce
```

**Comment by novoid** [comment]
I most probably do have the very same issue: https://github.com/novoid/nixos-config/issues/2 https://github.com/novoid/nixos-config/issues/3 https://github.com/novoid/nixos-config/issues/4 https://github.com/novoid/nixos-config/issues/5

**Comment by novoid** [comment]
I just moved the list of xfce packages including the add-ons/plugins from `homemanager/xfce.nix` to `configuration.nix` (NixOS without/outside of Home-Manager) and then it worked.

So with Home-manager, it seems to be the case that xfce plugins are not indexed/found.

**Comment by D3vil0p3r** [comment]
Same issue: probably the issue should be more related to [home-manager](https://github.com/nix-community/home-manager)?

**Comment by AldebaraanMKII** [comment]
I got the same issue. Placing them inside environment.systemPackages made them appear after rebuild.

**Comment by bobby285271** [comment]
This is changed since https://github.com/xfce-mirror/xfce4-panel/commit/894c6d9f2804092333c0134cebdf293cfefe98a0, on unstable I tested that a `nix profile install nixpkgs#xfce.xfce4-weather-plugin` works for me.
