### ISSUE TITLE
git subcommands display uncolored output in all terminals under xfce

### ISSUE THREAD

**Issue by cxandru** [NixOS/nixpkgs#89315]
**Describe the bug**
`git status`, `git pull` shows (red and green) colors, whereas `git diff`,`git show`,`git log` no longer do.
I first noticed this issue when I updated unstable to commit 3320a06049f
PS: This has nothing to do with `dircolors` or git's color configuration.

**To Reproduce**
1. open a terminal emulator. Tested with xterm, xfce-terminal and alacritty under xfce

**Expected behavior**
git diff/ git show have colored output, unless you have changed this in preferences

**Notify maintainers**
@peti @wmertens @globin 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre227577.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre227577.135073a87b7, nixpkgs-20.09pre218717.05f0934825c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by doronbehar** [comment]
What's the output of `dircolors` on the terminals you tested? I think you should also try `eval "$(eval dircolors)"`.

**Comment by gregor-alexandru** [comment]
> What's the output of `dircolors` on the terminals you tested? I think you should also try `eval "$(eval dircolors)"`.
```> dircolors
LS_COLORS='';
export LS_COLORS
```
```
> $(eval dircolors)
LS_COLORS='';: command not found
````

**Comment by doronbehar** [comment]
Sorry, typed wrong. I meant:

```
eval "$(dircolors)"
```

But that's irrelevant, because the issue is that you don't have any colors set on your terminal. What is your `$TERM`?

**Comment by doronbehar** [comment]
Well, on xterm, if you'd run:
```
eval "$(dircolors)"
```

I expect colors to work for you.

**Comment by gregor-alexandru** [comment]
Hm. On xterm `eval "$(dircolors)"` produces no output, while just dircolors produces the above output.
On alacritty eval "$(dircolors)"` produces:
```
LS_COLORS='';
export LS_COLORS
```

**Comment by doronbehar** [comment]
It shouldn't produce output, it should make git be colroful afterwards.

**Comment by gregor-alexandru** [comment]
Well, it doesn't do that. As before, git status shows colorful elements, but git log, git diff etc don't.

**Comment by doronbehar** [comment]
For alacritty, ideally `dircolors` would have print non empty strings. See: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=35247  I'm not sure what's the status of this though...

What's the output of `git config --get color.ui`?

**Comment by gregor-alexandru** [comment]
```
> git config --get color.ui
```
output is empty. But setting it to always also doesn't do anything

**Comment by doronbehar** [comment]
Set it to `true`.

**Comment by gregor-alexandru** [comment]
Also does nothing

**Comment by gregor-alexandru** [comment]
I didn't change any configuration for this to happen. I just updated my system, to the best of my knowledge. Can you reproduce this behavior?

**Comment by doronbehar** [comment]
No .... When did you update it?

**Comment by gregor-alexandru** [comment]
It was working before for me before commit https://github.com/NixOS/nixpkgs/commit/3320a06049fc259e87a2bd98f4cd42f15f746b96 (March 27). I updated again today in the hopes that the problem might have gone away.

**Comment by doronbehar** [comment]
Seems unrelated to me, though I feel you my friend, these stuff are totally annoying. If I were you, I'd `git config --global alias.log 'log --color=auto'`.

**Comment by gregor-alexandru** [comment]
Obviously I'm not saying that particular commit caused it, that just happened to be the version I pulled in. It could be anything between that and the last version that worked. This problem clearly has nothing to do with git's color configuration, and unlikely with any particular terminal either. Thanks for your time, if you could delete your comments though that would be great because maybe someone else can help and doesn't have to read this conversation. I will add the findings to the original description.

**Comment by wmertens** [comment]
I don't think deleting the columns is necessary. In any case, for me colored `git log` is still working and I'm on latest unstable. I use bash and my $TERM is xterm-256color

**Comment by gregor-alexandru** [comment]
Perhaps it has something to do with `less`? Since both `log` and `diff` allow scrolling in a `less`-like manner.

**Comment by gregor-alexandru** [comment]
Hm. It seems to be my version of `less` is bundled as part of the busybox multi-call executable. Is this normal? My `man`, `ls` etc are also.

**Comment by doronbehar** [comment]
Maybe `export LESS=-r`?

**Comment by seppeljordan** [comment]
I can observe the same behavior as the OP. I am pretty desperate.

All the basic linux programs seem to be busybox commands.
```
# readlink $(which less)
/nix/store/hf8bf3n475a5ag6hj5983zs5d16c77fd-busybox-1.31.1/bin/less
```

I am bringing this up since my man pages don't work anymore

```
# man man
man: no manual entry for 'man'
# ls /run/current-system/sw/share/man/man1/man.1.gz 
/run/current-system/sw/share/man/man1/man.1.gz
```

And other nixos commands are doing weird things, e.g.:
```
# nixos-container create my-system --flake grep: unrecognized option '--flake'
BusyBox v1.31.1 () multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

	-H	Add 'filename:' prefix
	-h	Do not add 'filename:' prefix
	-n	Add 'line_no:' prefix
	-l	Show only names of files that match
	-L	Show only names of files that don't match
	-c	Show only count of matching lines
	-o	Show only the matching part of line
	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
	-v	Select non-matching lines
	-s	Suppress open and read errors
	-r	Recurse
	-i	Ignore case
	-w	Match whole words only
	-x	Match whole lines only
	-F	PATTERN is a literal (not regexp)
	-E	PATTERN is an extended regexp
	-m N	Match up to N times per file
	-A N	Print N lines of trailing context
	-B N	Print N lines of leading context
	-C N	Same as '-A N -B N'
	-e PTRN	Pattern to match
	-f FILE	Read pattern from file
```
This output appears when I try to expand the command `nixos-container create my-system --flake ` and then tap TAB to complete.

**Comment by seppeljordan** [comment]
@cxandru Hey, I think I found a cure.

I had a version of busybox installed in my nix profile as `root` user. I removed it from the root profile and since then I can access man pages again, do have colored `git` output and the weird behavior of the `nixos-container` command stopped.

**Comment by doronbehar** [comment]
I'm closing assuming OP has found a fix for the issue / got along somehow.
