### ISSUE TITLE
Package request: timeshift (System restore tool for Linux)

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#89348]
**Project description**
_System restore tool for Linux_

This program takes snapshots for the root directory periodically or when told to using either `rsync` or `btrfs`, and allow the user restore them if need be. It is capable to do cross-distribution restore, or 
to work from a live CD/USB.

![Screenshot of Timeshift GUI listing the snapshots](https://raw.githubusercontent.com/teejee2008/timeshift/master/images/main_window.png)

Not sure if snapshots are important for NixOS, but it saves the day when you need to restore _another distribution_ to the previous state inside NixOS, or if you are using nix package manager on other distributions.

**Metadata**

* homepage URL: https://github.com/teejee2008/timeshift
* source URL: https://github.com/teejee2008/timeshift
* license: gpl3
* platforms: linux

**Comment by davidak** [comment]
>Not sure if snapshots are important for NixOS

from their readme:

>It is designed to protect only system files and settings. User files such as documents, pictures and music are excluded.

that is not really usefull since nixos already allows rollbacks

**Comment by Atemu** [comment]
It could be useful with Nix on non-NixOS Linux but you might as well use the native package manager to install Timeshift then.

Being able to offline timeshift non-NixOS distros from your NixOS installation seems like the most sensible use-case.

**Comment by ShamrockLee** [comment]
>Being able to offline timeshift non-NixOS distros from your NixOS installation seems like the most sensible use-case.

Actually, my original motivation is to rescue my Debian Testing in the laptop.

It crashed after the system partition was filled up suddenly (probably by the inflating system logs). 

I have a working NixOS installation in a USB stick (it  is one of the very distros that can be installed onto a removable storage device, making it boot able elsewhere and not affecting the local boot loader at the same time.), and it seems to be a good idea to rescue it from the USB stick.

It's probably a bit user-specific. :sweat_smile:

BTW, what is the Nixy way to deal with the trouble if something similar (something fills up the disk space suddenly) happen to a NixOS installation?

Thanks you very much for answering, and for this wonderful distro!

**Comment by Atemu** [comment]
> BTW, what is the Nixy way to deal with the trouble if something similar (something fills up the disk space suddenly) happen to a NixOS installation?

Delete older generations, run garbage collection and optimise the store. Preferably in that order.

**Comment by Atemu** [comment]
Oh and getting rid of stray gcroots can also help a ton. I had one that kept an old 19.09 system closure  around for months.

**Comment by ShamrockLee** [comment]
It might not be needed by most of the NixOS users. But the project itself seems to be easy to build (with well-written make files and simple dependencies). I can write one when I have time.

**Comment by ShamrockLee** [comment]
I hope it's still relevant.

**Comment by cicildihar** [comment]
I think this is going to help those who want to upgrade from a previous system's version.

**Comment by ShamrockLee** [comment]
AFAIK, this snapshot tool is commonly seen in Debian-based distros, and is enabled by default on Ubuntu and Linux Mint.

Remaining issues:

*   The "periodic snapshot" functionality requires crontab access from superuser. This is not enabled by deafult, and can be disabled at run time. If we want to have it on NixOS, it may require special patches and a NixOS module.

*   `timeshift-gtk` expects `/etc/timeshift/timeshift.json` to exist before it starts. I'm not sure how other packages manage that.
