### ISSUE TITLE
tuxtype segfaults

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#89374]
**Describe the bug**
the menu works, but without sound. Segmentation fault when try to start the game

```
[davidak@gaming:~]$ tuxtype
load_settings_filename(): no theme-specific settings found: /home/davidak/.tuxtype/settings.txt
Mix_Init: Failed to init required ogg and mod support!
Mix_Init: Mixer not built with MOD support
LoadSound() - could not load harp.wav
LoadSound() - could not load tock.wav
LoadSound() - could not load pop.wav
Could not load menu sounds - turning menu_sound off
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
Segmentation fault (core dumped)
```

**To Reproduce**
1. launch `tuxtype`
2. start game
3. crash

**Expected behavior**
working game

**Additional context**
i use the pantheon desktop

**Notify maintainers**
@aanderse 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.14, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"home-manager-20.03, nixos-20.03.1950.48723f48ab9, nixos-hardware, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:tuxtype
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
@davidak sorry my oldest is done with this program so I don't need it for another few years. And to be honest... when I do need it again, I'll likely just pull it from an older channel instead of trying to fix this (or buy a much nicer typing game on `steam`...). It might be ideal to remove the package and put a wiki entry or something noting it can always be pulled from an old channel.

**Comment by davidak** [comment]
It can at least get marked as broken.

Maybe some day someone wants to fix it.
