### ISSUE TITLE
Designing a port-knocking NixOS module

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8938]
I recently packaged [knockknock](http://www.thoughtcrime.org/software/knockknock/), a super-simple Python port-knocking daemon. I'm now trying to decide how best to write a NixOS service for it, and am looking for input from more experienced module writers.

The basic idea is that it makes your system look like ports are closed, unless you send specially (cryptographically) crafted SYN packets to predetermined ports. Ignoring the question of how to allocate those ports for now, I'm wondering how to handle the firewall interactions.

I'm thinking, potentially, of having something like `networking.portknocking.enable = true`, and having it barf if you've explicitly set any `networking.firewall.allowedTCP*` rules. That feels somewhat unfriendly to other modules, but I also don't want users accidentally leaving firewall ports open when enabling port knocking is a pretty explicit statement that such a thing is not intended.

Does anyone have better ideas for how to handle mutually exclusive concepts in NixOS modules like this one?

**Comment by lethalman** [comment]
Can you please rephrase the whole thing about `allowedTCP*` rules? I think one may want to open 10 tcp ports, and only 5 of them with port knocking. I don't understand your statement about the `allowedTCP*` rules.

Also `networking.portknocking` is too generic I think, there may be several services providing it. I'd threat this service like anything else: `services.knockknock`.

**Comment by copumpkin** [comment]
@lethalman the idea would be that the machine doesn't have any open ports unless you "knock" properly to open them temporarily for your own IP. I'm having trouble envisioning a situation in which someone would want some ports wide open but others hidden behind port knocking. Do you have some? 

Independent of that, at a more basic level, it seems hard to ensure that the funky port-knocking `iptables` config doesn't clobber the various other `networking.firewall.*`-managed rules or vice versa.

**Comment by lethalman** [comment]
@copumpkin yes I have a situation: there's no need to restrict people setups. It makes sense what you say, for your own case only.

How does the port knocking software work? Maybe it just creates an independent chain in iptables and it's easy to integrate with the nixos firewall.

**Comment by henrytill** [comment]
What about a `networking.portknocking.strict` option which will throw an `abort` if there are other open ports?

**Comment by lethalman** [comment]
@henrytill what about a warning when you are trying to hammer your own feet in every way? There are a number of occasions where we'd have to assert any single user mistake, and we don't do it as it would clutter everything uselessly. I don't really see the reason for this nitpicking as it's not a requirement for the module/system to work.

**Comment by tomberek** [comment]
@copumpkin I also would like to have the option of choosing to open ports while having other open via knockknock.

I am agnostic over including a `services.knockkock.strict`, I probably would not use it, though I can see it being handy for some. It's up to you if default is `true` or `false`.

**Comment by copumpkin** [comment]
Part of the issue is that the design of knockknock is to allow the person connecting to request which ports to open. That means you don't really get to configure ports on our side of things, unless we change the code, or try to create intersecting iptables rules.

**Comment by jagajaga** [comment]
ping

**Comment by spacekitteh** [comment]
@grahamc security

**Comment by spacekitteh** [comment]
Did you give up on this @copumpkin ?

**Comment by grahamc** [comment]
Closing for being very stale.
