### ISSUE TITLE
Add support for zfs's mount generator

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#89396]
Since zfs 0.8.4 we have proper systemd support for zfs datasets.

https://github.com/openzfs/zfs/commit/55d80e651a8c19919b8ee6a1c05fb36ad97ab5ad

This can be used to mount zfs datasets with zfs's native mount without relying on legacy mounts.

**Comment by Mic92** [comment]
still an issue.

**Comment by Mic92** [comment]
.

**Comment by lheckemann** [comment]
Duplicate of #62644
