### ISSUE TITLE
Mesa DriConf defaults are being ignored

### ISSUE THREAD

**Issue by buckley310** [NixOS/nixpkgs#89421]
**Describe the bug**
Mesa is looking for `drirc.d` in the wrong place, which results in many default configurations being ignored.

**To Reproduce**
```
nix-shell -p '[strace mesa-demos]' --run 'strace -f glxgears |& grep drirc.d'
```
note that drirc.d is not found.
my results:
```
$ nix-shell -p '[strace mesa-demos]' --run 'strace -f glxgears |& grep drirc.d'
openat(AT_FDCWD, "/nix/store/nzkkagmvyg8xbraqd58jcddn09i9xjah-mesa-20.0.2/share/drirc.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/nzkkagmvyg8xbraqd58jcddn09i9xjah-mesa-20.0.2/share/drirc.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/nzkkagmvyg8xbraqd58jcddn09i9xjah-mesa-20.0.2/share/drirc.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/nzkkagmvyg8xbraqd58jcddn09i9xjah-mesa-20.0.2/share/drirc.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/nzkkagmvyg8xbraqd58jcddn09i9xjah-mesa-20.0.2/share/drirc.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```

**Expected behavior**
`drirc.d` should be searched for in `/run/opengl-driver/share/`

**Additional context**
This issue causes all the configs in `/run/opengl-driver/share/drirc.d/00-mesa-defaults.conf` to be ignored. This contains many application-specific workarounds from the Mesa project, the most noticable to me being that enabling Freesync without these configs results in a sub-par experience.

In my testing, I have using this workaround which seems to resolve the issue locally:
`ln -s /run/opengl-driver/share/drirc.d/00-mesa-defaults.conf ~/.drirc`

**Notify maintainers**
@vcunat

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09pre227577.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre228204.467ce5a9f45"`
 - channels(sean): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
@buckley310 I drafted #89657, which should fix this, but it currently doesn't work due to cyclic dependencies.
