### ISSUE TITLE
Disable jit support for rubyMinimal - to reduce closure size significantly

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#89445]
**Describe the bug**

I'm hunting down packages that reference gcc. One of them is `ruby` (maintainers: @vrthra & @manveru ). Here's why:

```
$ nix why-depends nixpkgs.ruby nixpkgs.gcc
/nix/store/8nlbhrrs2y2y3y7alqj8h40q8hh9miyf-ruby-2.6.6
╚═══lib/ruby/2.6.0/x86_64-linux/rbconfig.rb: …CONFIG["MJIT_CC"] = "/nix/store/2ddwl0cyff2cd4dkb2nqf1xich7halj0-gcc-wrapper-9.3.0/bin/gcc".  CO…
    => /nix/store/2ddwl0cyff2cd4dkb2nqf1xich7halj0-gcc-wrapper-9.3.0
```

The fault is ~~JIT support, which is enabled by default~~ the fact that the build flag `removeReferencesToCC` doesn't remove all references, as one might expect (EDIT, see: https://github.com/NixOS/nixpkgs/pull/89726#issuecomment-640226713 ).

I'm up to including this feature, but I was wondering perhaps it'd be legit to disable this feature for the `rubyMinimal` derivation? I opened a PR at https://github.com/NixOS/nixpkgs/pull/89726#issuecomment-640226713 (EDIT).

**Comment by peterhoeg** [comment]
But that would mean gems that require a compiler would no longer work.

**Comment by doronbehar** [comment]
The suggestion is for `rubyMinimal`, not `ruby`. Isn't `ruby` the derivation that's used to build the gems? According to:

https://github.com/NixOS/nixpkgs/blob/171b556f1c25d8ea55b323a2c709b528114a08d8/pkgs/development/ruby-modules/bundler/default.nix#L1-L3

**Comment by peterhoeg** [comment]
It still has support for gems, so some will fail with gcc. What exactly is the use case for `rubyMinimal`?

**Comment by doronbehar** [comment]
> What exactly is the use case for rubyMinimal?

Technically it's not used anywhere, according to `git grep`.

**Comment by doronbehar** [comment]
I'd like to make `rubyMinimal` my `ruby` - with an overlay. The goal is to make the 1 or 2 pure ruby scripts I have on my system not pull `gcc`, as they do today.

**Comment by peterhoeg** [comment]
> The goal is to make the 1 or 2 pure ruby scripts I have on my system not pull gcc, as they do today

But what is the reason? You're likely to have a version of ruby that includes gcc on your system anyway, so you don't really save any space. And the use-case would be plain ruby scripts with only the gems that don't require system libraries. We have no users in nixpkgs of `rubyMinimal` presumably because it's rather pointless. And while of course we can strip gcc from rubyMinimal (there's no harm), I'd rather say drop `rubyMinimal` instead.

**Comment by doronbehar** [comment]
> But what is the reason? You're likely to have a version of ruby that includes gcc on your system anyway

Not If I'll apply #90151 and this overlay:

```nix
self: super:

{
  ruby = super.ruby.override {
    # rubyMinimal disables too much features required by asciidoctor
    rubygemsSupport = true;
    JitSupport = false;
    useRailsExpress = false;
    zlibSupport = true;
    opensslSupport = true;
    gdbmSupport = false;
    cursesSupport = false;
    docSupport = false;
    yamlSupport = false;
    fiddleSupport = false;
  };
}
```

This allows me to not need GCC  for `asciidoctor` for example - which is the only ruby gem I use. For example, run with this PR and that overlay applied:

```sh
$ nix why-depends -f. asciidoctor gcc
```

And you should get:

```
'asciidoctor' does not depend on 'gcc'
```

And without #90151, (and without the overlay because it would fail) you should get:

```
/nix/store/nyb3ry2yvhskrlni9dphfmj3w1ylakaw-asciidoctor-2.0.10
╚═══bin/asciidoctor -> /nix/store/06rmj52zhnb7kkp3dzvicaiddj9a8zmx-asciidoctor-2.0.10/bin/asciidoctor
    => /nix/store/06rmj52zhnb7kkp3dzvicaiddj9a8zmx-asciidoctor-2.0.10
    ╚═══bin/.asciidoctor-epub3-wrapped: …#!/nix/store/ighz4wp6bmpsm8x1lrsvwjz4m81r6a6d-ruby-2.6.6/bin/ruby.#.# This fi…
        => /nix/store/ighz4wp6bmpsm8x1lrsvwjz4m81r6a6d-ruby-2.6.6
        ╚═══lib/ruby/2.6.0/x86_64-linux/rbconfig.rb: …CONFIG["MJIT_CC"] = "/nix/store/r4l53b461b2lyclxn1pdj0n4hvbxl2l6-gcc-wrapper-9.3.0/bin/gcc".  CO…
            => /nix/store/r4l53b461b2lyclxn1pdj0n4hvbxl2l6-gcc-wrapper-9.3.0
```

`asciidoctor` is the only derivation that needs ruby that I actually use. I've updated the 1st comment in #90151 to exemplify this overlay as a possible usecase.

> We have no users in nixpkgs of rubyMinimal presumably because it's rather pointless.

Well I tend to agree - even for asciidoctor which should be pretty much a pure ruby gem, it still required `zlibSupport` and `opensslSupport` which aren't enabled in current `rubyMinimal`. Hence I tend to agree.

> And while of course we can strip gcc from rubyMinimal (there's no harm), I'd rather say drop rubyMinimal instead.

OK so I've updated #90151 to include a drop to `rubyMinimal`, including release notes and an alias. Waiting for your review :crossed_fingers: .
