### ISSUE TITLE
channel nixos-20.03 not advancing

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixpkgs#89460]
**Describe the bug**

The channel `nixos-20.03` is not advancing since a installer test has timed out 5 days ago, see https://hydra.nixos.org/job/nixos/release-20.03/tested

see https://hydra.nixos.org/job/nixos/release-20.03/tested

**Expected behavior**
Tests succeed and `nixos-20.03` advances to the current HEAD of branch `release-20.03`

**Additional context**
Might be related to https://github.com/NixOS/nixpkgs/issues/89305, but that is just a wild guess.

This should be marked as critical/blocker.

**Notify maintainers**

**Metadata**
not relevant

**Comment by vcunat** [comment]
Advanced already.

**Comment by wamserma** [comment]
Indeed. Classic race condition. :grinning:

**Comment by Ma27** [comment]
>  Might be related to #89305, but that is just a wild guess.

Just for the record, the Hydra package in `nixpkgs` is not related to those kinds of issues. The jobs that have to pass to advance the channel are listed in `nixos/release-combined.nix`.
