### ISSUE TITLE
Can't install write_stylus-209

### ISSUE THREAD

**Issue by xbonnetain** [NixOS/nixpkgs#89473]
**Describe the bug**
The installation of write_stylus fails because the file https://oyra.eu/write/icon.tar.gz does not exists.

**To Reproduce**
1. run `nix-env -i write_stylus`

**Expected behavior**
The package is installed.

**Additional context**
Note that the version 209 is outdated, and the version 300 is available upstream.

**Comment by oyren** [comment]
Hello this was actually already fixed by https://github.com/NixOS/nixpkgs/commit/e92866d74f3a795dc4b6f50d53815b50dab01b37#diff-d91944d0c56d0ad196f89f861a306072
