### ISSUE TITLE
Typora package (link) broken.

### ISSUE THREAD

**Issue by DubKoldun** [NixOS/nixpkgs#89482]
**Describe the bug**
Current version 0.9.73 is broken (download link at least). 

**To Reproduce**
Steps to reproduce the behaviour:
1. niv-env -i typora 
2. ...
3. ...

**Expected behaviour**
Typora installed successfully.

**Screenshots**
![problem](https://user-images.githubusercontent.com/34633910/83765313-ae18aa00-a683-11ea-92ab-e1c6534a8d8b.png)

**Additional context**
https://github.com/NixOS/nixpkgs/issues/76249#issuecomment-636187665
Maybe we should replace the deb package:
https://www.typora.io/linux/typora_${version}_amd64.deb
by
https://typora.io/linux/Typora-linux-x64.tar.gz

**Notify maintainers**
@jensbin 

**Metadata**
`  /nix/store/5k0id2x2sqj9k7kb9f1jzf382mpn6b2r-nix-info
copying path '/nix/store/5k0id2x2sqj9k7kb9f1jzf382mpn6b2r-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.116, NixOS, 19.09.2503.2efedf8fc74 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2503.2efedf8fc74"`
 - channels(vutaliy): `"home-manager, nixos-20.09pre228204.467ce5a9f45, nixpkgs-20.09pre228333.1ae28ebfdb7"`
 - nixpkgs: `/home/vutaliy/.nix-defexpr/channels/nixpkgs` `

**Comment by wamserma** [comment]
The version referenced is simply outdated and not available any more from upstream. Switching to the `tar.gz` is no solution, as the contents may change without being visible through the file name, leading to a hash mismatch and breaking the build.

**Comment by wamserma** [comment]
@jensbin I tried updating to 0.9.89 with sha256 `0gk8j13z1ymad34zzcy4vqwyjgd5khgyw5xjj9rbzm5v537kqmx6` but the .deb has setuid for the chrome sandbox and with `unpackPhase = "dpkg-deb --fsys-tarfile $src | tar xf -";` it builds, but crashes at startup.

**Comment by irimi1** [comment]
> @jensbin I tried updating to 0.9.89 with sha256 `0gk8j13z1ymad34zzcy4vqwyjgd5khgyw5xjj9rbzm5v537kqmx6` […]

This version too now seems to be unavailable. The whole versioning in the [changelog](https://typora.io/dev_release.html) has changed over night (compare with the [windows version changelog](https://typora.io/windows/dev_release.html), which still has the old versioning).
Also the linux releases now seem to be *.dmg image files instead of *.deb packages. 

Not sure what’s going on there.
