### ISSUE TITLE
Function get localtime in binary built by nix work incorrectly

### ISSUE THREAD

**Issue by thongpv87** [NixOS/nixpkgs#89487]
**Describe the bug**
Function get `localtime` in binary built by nix work incorrectly

**To Reproduce**
I have written a simple project at https://github.com/thongpv87/nix-test . The code in `main.cpp` set the `TZ` environment variable then call function `localtime` and print the timezone. Compile this file with g++, nix-build, g++ in docker image by dockerfile, docker image from dockerTools and run these binary/image and compare the result.

My host system time zone is Singapore. The current time in Singapore when I run this is 23:48:40. The output when run with binary from nix-build is:
```
TZ=(null)
Current local time and date: Thu Jun  4 23:48:25 2020
 
TZ=America/New_York
Current local time and date: Thu Jun  4 15:48:25 2020
 
TZ=Asia/Tokyo
Current local time and date: Thu Jun  4 15:48:25 2020
 
TZ=Europe/London
Current local time and date: Thu Jun  4 15:48:25 2020
```
More output: https://pastebin.com/t8FAixyL

**Expected behavior**

```
TZ=(null)
Current local time and date: Thu Jun  4 23:48:40 2020
 
TZ=America/New_York
Current local time and date: Thu Jun  4 11:48:40 2020
 
TZ=Asia/Tokyo
Current local time and date: Fri Jun  5 00:48:40 2020
 
TZ=Europe/London
Current local time and date: Thu Jun  4 16:48:40 2020
```

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-70-generic, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(gitlab-runner): `"nixpkgs-20.09pre213040.f77e057cda6"`
 - channels(root): `"nixpkgs-20.09pre213040.f77e057cda6"`
 - channels(tpham): `"home-manager, nixpkgs-20.09pre228165.00df2371122"`
 - nixpkgs: `/home/tpham/.nix-defexpr/channels/nixpkgs`
```

**Comment by matthewbauer** [comment]
This looks like the same issue as https://github.com/NixOS/nixpkgs/issues/65415.

**Comment by aanderse** [comment]
Any update on this?

**Comment by fpletz** [comment]
Duplicate of #65415.
