### ISSUE TITLE
ghcjs broken due to lens >= 4.12

### ISSUE THREAD

**Issue by spl** [NixOS/nixpkgs#8948]
As of at least 551a26dad196ae1370b5ea84783784c9f0fce62f, ghcjs doesn't build due to a missing lens dependency:

```
building path(s) ‘/nix/store/45mxks65ddrgx37iwy4i7h8k11yr10f7-ghcjs-0.1.0’
setupCompilerEnvironmentPhase
Build with /nix/store/45crga7ddaifpdxlbxs5sy15kqq6pyfx-ghc-7.10.1.
unpacking sources
unpacking source archive /nix/store/6ny3x250f4dvk2lgqdjwr4jjp9dpl81v-ghcjs-c1b6239
source root is ghcjs-c1b6239
patching sources
applying patch /nix/store/52gz6wci2vws1x382rhp1qcmz00x6ssg-ghcjs.patch
patching file src-bin/Boot.hs
patching file src/Compiler/Info.hs
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-ghcjs-0.1.0.drv-0/package.conf.d -j2 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-ghcjs-0.1.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/45mxks65ddrgx37iwy4i7h8k11yr10f7-ghcjs-0.1.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-ghcjs-0.1.0.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/45mxks65ddrgx37iwy4i7h8k11yr10f7-ghcjs-0.1.0/lib/ghc-7.10.1/ghcjs-0.1.0 --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-lib-dirs=/nix/store/jax1b2pl5xck6lplf3dq51v4zv14gb73-git-2.4.6/lib --extra-include-dirs=/nix/store/9xlh2rw7g388vsbnkcv5ynrbsmigs2jj-gnumake-4.1/include --extra-include-dirs=/nix/store/xhmz9arlx4rg4kafrv6rn8w1zh86qffa-libtool-2.4.6/include --extra-lib-dirs=/nix/store/xhmz9arlx4rg4kafrv6rn8w1zh86qffa-libtool-2.4.6/lib --extra-include-dirs=/nix/store/1laighizq55j6v32g1scgdnkm4k8akmf-gmp-5.1.3/include --extra-lib-dirs=/nix/store/1laighizq55j6v32g1scgdnkm4k8akmf-gmp-5.1.3/lib --extra-include-dirs=/nix/store/q0m70q5wg21hxrixkp1xk4x95sfs2fln-glibc-2.21/include --extra-lib-dirs=/nix/store/q0m70q5wg21hxrixkp1xk4x95sfs2fln-glibc-2.21/lib --extra-include-dirs=/nix/store/k4kwfwblsxz2339x3giliqc67llkk360-nodejs-0.12.7/include --extra-lib-dirs=/nix/store/k4kwfwblsxz2339x3giliqc67llkk360-nodejs-0.12.7/lib
Configuring ghcjs-0.1.0...
Setup: At least the following dependencies are missing:
lens >=4.0 && <4.12
builder for ‘/nix/store/w1rnfj776h37ph6wk30rax8cpzn2dadb-ghcjs-0.1.0.drv’ failed with exit code 1
```

I'm guessing this is due to 60accda79fe13fa938c6237be9af7e1f60e2ed46, which bumped lens:

```diff
      mkDerivation {
        pname = "lens";
-       version = "4.11.1";
-       sha256 = "1f3xyz9y6510nbskc15brjdg226qpwgjnzddc29kg0g79x5wwcpi";
+       version = "4.12";
+       sha256 = "195fhzw8z15zrbav7mdzia052g7sfy7zm5banjkk3azsb9mjvvan";
```

Would it work to bump the lens upper bound for ghcjs?

Is it possible to have a test for building ghcjs so that the build doesn't break in the future?

**Comment by spl** [comment]
Looks like there's already a PR for bumping the lens dep: ghcjs/ghcjs#369.

**Comment by peti** [comment]
I don't think we can (or rather: *should*) fix this in Nixpkgs. This ought to be fixed upstream, and then we'll pick up the new version ASAP for distribution.

**Comment by spl** [comment]
> I don't think we can (or rather: should) fix this in Nixpkgs. This ought to be fixed upstream, and then we'll pick up the new version ASAP for distribution.

I assume “this” means the lens upper bound version. If so, that's fine.

How do we prevent ghcjs from becoming broken by another Hackage package update (e.g [these](https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/haskell-modules/hackage-packages.nix))?

**Comment by peti** [comment]
> How do we prevent ghcjs from becoming broken by another Hackage package update?

We can't. Or rather: we *can*, but it requires a significant manual effort to keep `ghcjs` building in the presence of a breaking update. Personally, I cannot do it. If someone else is willing to dedicate their spare time to this effort, then I'd be all for it, of course. All that is necessary is to configure the necessary extra versions in https://github.com/NixOS/cabal2nix/blob/master/src/hackage2nix.hs#L298 so that we can build an old version of the offending package and then to add an override that passes the old version to `ghcjs` rather than the latest one. Furthermore, all that cruft needs to be removed again after a `ghcjs` update arrives that works fine with the respective latest version.

**Comment by spl** [comment]
@peti I'm not sure I understand.

It seems like you're suggesting a way to keep ghcjs building in its current state with the current nixpkgs. That's fine, of course. If there is a maintainer for the ghcjs package, the work doesn't sound like too much. If there is no maintainer, a simpler solution to a broken ghcjs would be to mark it broken and note the reason, allowing somebody else to fix it when possible.

On the other hand, I'm asking how to detect when a Hackage update will break ghcjs. Is there any existing automated procedure/infrastructure for testing Nix packages against other package updates? Is it not possible to add ghcjs to that?

Lastly, I think it would be a good idea to leave this ticket open until the issue is actually resolved.

**Comment by peti** [comment]
> how to detect when a Hackage update will break ghcjs

We detect that breakage via Hydra. Whoever is configured in the `meta.maintainer` field of the `ghcjs` expression receives an automatic e-mail every time the build fails.

> I think it would be a good idea to leave this ticket open until the issue is actually resolved.

What do we gain by keeping this ticket open?
