### ISSUE TITLE
please delete libjpeg-drop

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#89535]
the drop patches were upstreamed to libjpeg in version 9d  2020-01-12: https://abi-laboratory.pro/index.php?view=changelog&l=libjpeg&v=9d and are no longer maintained so the separate package can be safely removed.

**Comment by prusnak** [comment]
https://github.com/NixOS/nixpkgs/pull/89550 will fix this

**Comment by RamKromberg** [comment]
thx.
