### ISSUE TITLE
Packaging requests: chewing-editor

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#89554]
**Project description**
_Cross platform chewing user phrase editor_

Chewing editor is a widely-used bopomofo input method for traditional Chinese, and chewing-editor is the tool to edit the database of user phrases stored by the input method. Users of chewing will need chewing-editor sooner or later.
NixOS have chewing include as a fcitx engine (`nixpkgs.fcitx-engines.chewing`) that can be used in the `i18n` module, but not chewing-editor.

**Metadata**

* homepage URL: http://chewing.im/
* source URL: https://github.com/chewing/chewing-editor
* license: gpl2
* platforms: unix

**Comment by iblech** [comment]
(Just a random passer-by.) Awesome, thank you for making NixOS more accessible for users of traditional Chinese! I confirm that the package builds here. :-)

**Comment by ShamrockLee** [comment]
The corresponding pull request #91270 is merged. Closing.
