### ISSUE TITLE
Mopidy Can't find local directories "Local Media Dir does not exist"

### ISSUE THREAD

**Issue by CestDiego** [NixOS/nixpkgs#8959]
I have mopidy running as a service. but it gives me an error that doesn't make sense. I have this in my config

```nix
    services.mopidy = {
        enable = true;
        configuration = ''
            [local]
            enabled = true
            media_dir = /home/jarvis/Music/mopidy
        '';
    };
```

Even though /home/jarvis/Music/mopidy exists and tried both having it to users `mopidy:mopidy` or `jarvis:users`

```
...
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Disabled extensions: none
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Starting Mopidy mixer: SoftwareMixer
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Starting Mopidy audio
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Starting Mopidy backends: StreamBackend, M3UBackend, LocalBackend
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Loaded 0 M3U playlists from /var/lib/mopidy/.local/share/mopidy/m3u
Jul 22 17:07:41 nixos mopidy[25977]: WARNING  Local media dir /home/jarvis/Music/mopidy does not exist.
Jul 22 17:07:41 nixos mopidy[25977]: WARNING  Local media dir /home/jarvis/Music/mopidy does not exist.
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Loaded 0 local tracks using json
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Starting Mopidy core
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Audio output set to "autoaudiosink"
Jul 22 17:07:41 nixos mopidy[25977]: INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
Jul 22 17:07:41 nixos mopidy[25977]: INFO     MPD server running at [::ffff:127.0.0.1]:6600
Jul 22 17:07:41 nixos mopidy[25977]: INFO     HTTP server running at [::ffff:127.0.0.1]:6680
```

So I cannot make it work either way I try :( any help on this?

**Comment by lethalman** [comment]
You should put that path in a string.

**Comment by CestDiego** [comment]
It gives the same error but with an scaped double quote
```
Jul 23 07:00:34 nixos mopidy[17930]: WARNING  Local media dir /"/home/jarvis/Music/mopidy" does not exist.
Jul 23 07:00:34 nixos mopidy[17930]: WARNING  Local media dir /"/home/jarvis/Music/mopidy" does not exist
```

**Comment by lethalman** [comment]
@CestDiego really sorry, didn't realize that was the textual configuration... perhaps mopidy runs as a particular user and cannot read your home?

**Comment by CestDiego** [comment]
it runs as mopidy user in the `audio` group. I changed permissions on the folder. and still nothing...Weird thing is that it says it doesn't exist, not that it doesn't have permissions to access it

```
~/Music|⇒ l                                                               
total 12K
drwxr-xr-x  3 jarvis users 4.0K Jul 22 16:10 .
drwx------ 31 jarvis users 4.0K Jul 23 02:15 ..
drwxrwxr-x  2 jarvis audio 4.0K Jul 22 16:17 mopidy
```

**Comment by lethalman** [comment]
cc maintainer @rickynils maybe he knows

**Comment by vcunat** [comment]
I wonder if services are automatically run in a separate mount namespace.

**Comment by CestDiego** [comment]
how could I find out?

**Comment by fpletz** [comment]
@CestDiego Your `..` directory, namely `/home/jarvis`, has a permission set of 700 but it should also have `o+x` (701) so that other users like `mopidy` can enter your home directory.

Note that to read the contents of directories addtionally`+r` is required, so other users can't list the files in the home directory. Another option would be putting the music directory into another path and make it also readable & writeable by your user and just use a symbolic link for `/home/jarvis/Music/mopidy`.
