### ISSUE TITLE
including syslimits.h fails if glibc is in build inputs

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#8962]
Failure: http://hydra.nixos.org/build/23953373/nixlog/1/raw

```
In file included from /tmp/nix-build-virtualbox-5.0.0-3.18.19.drv-0/VirtualBox-5.0.0/src/VBox/ExtPacks/VBoxDTrace/include/VBoxDTraceLibCWrappers.h:33:0,
                 from /tmp/nix-build-virtualbox-5.0.0-3.18.19.drv-0/VirtualBox-5.0.0/src/VBox/ExtPacks/VBoxDTrace/onnv/cmd/dtrace/dtrace.c:71:
/nix/store/84ff6922izmz0g6akrpslibvabf7xf40-gcc-4.9.3/lib/gcc/i686-pc-linux-gnu/4.9.3/include-fixed/syslimits.h:7:25: error: no include path in which to search for limits.h
 #include_next <limits.h>
```

It seems to be a toolchain issue on i686 only for virtualbox:

a.c:

```
#include <limits.h>
#include <syslimits.h>

void main() {
}
```

Test: `gcc a.c`

OK x64: `nix-shell -A linuxPackages.virtualbox`

OK x86 stdenv: `nix-shell -A pkgsi686Linux.utillinux`

FAIL x86 for virtualbox: `nix-shell -A pkgsi686Linux.linuxPackages.virtualbox`

cc @vcunat @aszlig

**Comment by lethalman** [comment]
It's a problem with `NIX_CFLAGS_COMPILE`, unsetting them in the nix-shell for virtualbox fixed the problem.

**Comment by vcunat** [comment]
Note that these don't use standard stdenv on 64-bit but the multilib one.

**Comment by aszlig** [comment]
bisecting...

**Comment by aszlig** [comment]
Done. The issue seems to be in commit e08b9ab8d3d6362c774a786797347fa7483af773.

**Comment by aszlig** [comment]
Indeed, after reverting e08b9ab8d3d6362c774a786797347fa7483af773 in `master`, VirtualBox compiles fine on `i686-linux` and `x86_64-linux`, now the interesting part is: why? Because that commit seems to be architecture-unrelated.

**Comment by lethalman** [comment]
@aszlig I think because previously we were linking against libiconv. Now instead libiconv is glibc and it gets to NIX_CFLAGS_COMPILE and breaks the syslimits.h.

**Comment by vcunat** [comment]
Ah, of course, I think the problem should be that it's a different glibc than in the stdenv it uses, because it uses a multi-lib stdenv.

**Comment by vcunat** [comment]
Actually, no, that doesn't make sense, because problems occur only on 32-bit and the stdenv there is equal to the usual 32-bit one (no real multi-lib).

**Comment by lethalman** [comment]
@vcunat if you read carefully what I explained above, that error also happens on x64 when glibc is in NIX_CFLAGS_COMPILE. But, virtualbox luckily compiles on x64 for some other reason.

**Comment by vcunat** [comment]
OK, filtering out that glibc include path fixes the build, so I pushed that for now.

It seems some interaction with usage of `#include_next`, but I don't see the particular cause nor why it doesn't appear anywhere else. Perhaps having `libiconv = glibc;` on linux isn't a good thing.

**Comment by lethalman** [comment]
Possible problem. Without glibc in cflags: include limits.h is found in gcc include-fixed. With glibc in cflags, limits.h is first found in glibc and then syslimits.h from gcc breaks.

**Comment by lethalman** [comment]
This happens also on other systems, e.g. ubuntu when adding `-isystem /usr/include`. In other words, the correct fix is that glibc should not be in `-isystem`.

**Comment by lethalman** [comment]
And I wonder, why do we use `-isystem` instead of `-I`?

**Comment by lethalman** [comment]
Relevant: 6671bb8b

**Comment by lethalman** [comment]
So @edolstra you appear to have some insight about that `-isystem`. Why isn't `-I` enough?

**Comment by lethalman** [comment]
Possible solution: use `-idirafter`, which is after `-I` and **after** system dirs. While `-isystem` is after `-I` but before system dirs which breaks gcc includes.

**Comment by lethalman** [comment]
Ok so this is what happens, with the help of @vcunat on IRC that let me understand what's going on:

Search path order in normal case: gcc, glibc. So syslimits.h is found in gcc, include_next limits.h which is in glibc. Ok.

With `-isystem glibc`: glibc, gcc. As expected, because -isystem glibc comes before -idirafter gcc. So syslimits.h is found in gcc, but there's no limits.h next.

With `-I glibc: gcc, glibc`. That's because -I ignores the option if it's a system directory, hence glibc is not moved! And it works.

With `-idirafter glibc`: gcc, glibc. As expected, because it's already -idirafter gcc.

What to do? :)

**Comment by vcunat** [comment]
Some -isystem discussion: 51713fbbfcaf.

**Comment by vcunat** [comment]
This shouldn't be a blocker now, although the -isystem situation is (still) perhaps suboptimal.

**Comment by wizeman** [comment]
Maybe I'm mistaken, but gcc 4.9 seems to be failing due to what looks like a similar glibc/gcc header issue: https://hydra.nixos.org/build/24001011

**Comment by vcunat** [comment]
Yes, maybe. I know this problem; notice that `stdenv.cc` **is** gcc-4.9. I consider it a bootstrapping bug that our `gcc` and `gcc49` is a different derivation.

**Comment by edolstra** [comment]
This can be fixed by adding `gcc49 = cc` to `overrides` in `stdenvLinux` in `pkgs/stdenv/linux/default.nix`, but we'll have to remember to keep that up to date when switching to a newer gcc.

**Comment by domenkozar** [comment]
@edolstra a friendly ping so you remember about this for gcc5

**Comment by vcunat** [comment]
In master we already have `stdenv.cc == gcc`. I suppose it was fixed with #2817.

**Comment by Mathnerd314** [comment]
Right, now ``gcc != gcc49``. But nothing uses ``gcc49`` so it's not a problem.

Perhaps this could be fixed by setting ``libiconv = stdenv``? Since glibc is included in stdenv, and ``stdenv`` acts as a no-op in ``buildInputs``.

**Comment by fpletz** [comment]
Works as of 16.09.
