### ISSUE TITLE
chromium: use a less frightening updater script

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#89635]
The chromium updater script uses a Nix fixed-output derivation doing network access, and makes use of a hash collision to emit contents that have the same sha1 hash.

Before ed8f3b5fa3cebfc3662ad5fff098567616220cf8, this was MD5, and also used collisions.

While this is funny and cool, it's probably not a good idea to be this tooling essential to do things like security updates in a browser.

Before 28b289efa642261d7a5078cfa3a05ef1d6fa2826, it was a 101 line bash script. Now we're with a 271 line nix script that is (at least for me) very hard to read.

@aszlig can you elaborate on if we really need a nix-based updater script, or can this be moved back to the 101 line bash script?

cc @primeos

**Comment by primeos** [comment]
Also relevant: #72932 (cc @alyssais).

**Comment by flokli** [comment]
Oh yeah, that'd also be fine. Let's carry over discussion to that thread.
