### ISSUE TITLE
purescript test fails

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#8965]
broken since 0.7.0.0

it look like it cannot open test files
https://hydra.nixos.org/build/23422483/nixlog/1#line-553

**Comment by peti** [comment]
Please report that issue to the authors of `purescript` at https://github.com/purescript/purescript.

**Comment by MasseGuillaume** [comment]
@peti it does work: https://travis-ci.org/purescript/purescript/jobs/72047386#L657

**Comment by peti** [comment]
Try running the test suite from a release tarball instead of the git repository checkout.

**Comment by MasseGuillaume** [comment]
I don't understand what you mean.

This is what I use:
https://github.com/NixOS/nixpkgs/blob/ea3382bb69e542b7af7cdc1407abd9e0dc757c68/pkgs/development/haskell-modules/configuration-ghc-7.8.x.nix#L64

I'm using nixos pre release ((nixos-15.06) and the following config:
```
...
environment.systemPackages = with pkgs; [
  haskellPackages.purescript
]
```

**Comment by peti** [comment]
The test fails because required files are missing from the release tarball! The release available from Hackage is incomplete. This is a bug that should be fixed upstream.

**Comment by MasseGuillaume** [comment]
purescript 0.7.2 will fix this issue.It will be released soon: https://github.com/purescript/purescript/issues/1302#issuecomment-124498777
