### ISSUE TITLE
firefox: context menus stop working after opening an URL from the command line

### ISSUE THREAD

**Issue by hlandau** [NixOS/nixpkgs#89701]
**Describe the bug**
When Firefox is already open, launching an URL by running `firefox $URL` at the command line results in menus and context menus in Firefox bugging. A context menu may be opened exactly one additional time after doing this, and then all future attempts to open menus result in the menu flickering for a second and closing. This can only be rectified by restarting Firefox.

**To Reproduce**
1. Launch firefox with `MOZ_WEBRENDER=1 MOZ_ACCELERATED=1 firefox` at a terminal. Close the terminal. Open a few tabs.
2. Open a new terminal and run `MOZ_WEBRENDER=1 MOZ_ACCELERATED=1 firefox https://example.com/`.
3. Right click on the page. The context menu opens. Close the context menu.
4. Right click on the page again. The context menu opens for an instant, flickering, and closes again. All future attempts to open the context menu result in this. The menu button also stops working; all forms of menus stop working and only flicker for an instant.

Window manager is i3.

**Notify maintainers**
@eelco @andir

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.116, NixOS, 20.03.2059.05a32d8e771 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2059.05a32d8e771"`
 - channels(hugo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by andir** [comment]
This sounds like an upstream issue. Have you tried to reproduce this
with an equivalent setup on another distribution?

**Comment by thornycrackers** [comment]
This is a long shot but I've experienced a similar behavior before. When you right click to open the context menu, hold the right click down. Does the context stay open? If it does try hovering over an option and then releasing the button. If this is how your context menu is working you can go to `about:config` in your address bar and then look for `ui.context_menus.after_mouseup` and set it to `true` and see if that fixes the weird behavior. I found this from a reddit thread. 

https://old.reddit.com/r/i3wm/comments/88k0yt/right_mouse_btn_instantly_clicks_first_option_in/
