### ISSUE TITLE
meld: Crash when closing inner tab

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#89707]
**Describe the bug**
Meld crashes when closing an inner window.
```
Gtk:ERROR:../gtk/gtkwidget.c:5579:gtk_widget_unrealize: assertion failed: (!widget->priv->mapped)
Bail out! Gtk:ERROR:../gtk/gtkwidget.c:5579:gtk_widget_unrealize: assertion failed: (!widget->priv->mapped)
Aborted (core dumped)
```

**To Reproduce**
1. mkdir /tmp/folder1 && echo "1" > /tmp/folder1/file.txt
2. mkdir /tmp/folder2 && echo "2" > /tmp/folder2/file.txt
3. meld /tmp/folder1 /tmp/folder2
4. open file.txt in meld
5. close file.txt comparission in meld

**Expected behavior**
no crash

**Additional context**

**Notify maintainers**
@jtojnar @mimame

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.03.2059.05a32d8e771 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(asbachb): `""`
 - channels(root): `"nixos-20.03.2059.05a32d8e771, nixos-19.09-19.09.2510.2f9bafaca90, nixos-unstable-20.09pre228204.467ce5a9f45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by prusnak** [comment]
From which channel did you install meld? I tried both stable on unstable and don't see the problem.

**Comment by asbachb** [comment]
> From which channel did you install meld? I tried both stable on unstable and don't see the problem.

I'm using 20.03 channels and I'm running Wayland - maybe that's part of the problem.

**Comment by asbachb** [comment]
Maybe related: https://gitlab.gnome.org/GNOME/meld/-/issues/227

**Comment by asbachb** [comment]
seems to be related with Wayland:
`GDK_BACKEND=x11 meld /tmp/folder1 /tmp/folder2`
is working fine.

**Comment by dasj19** [comment]
20.03 reached end-of-life... is this still an issue in 20.09 or the master branch?

**Comment by jtojnar** [comment]
We have since switched to a new version of Meld with refreshed UI so I will assume this has been fixed. If not, please reply so we can reopen.

**Comment by guibou** [comment]
I've migrated to sway recently and observe the same crash:

```
Gtk:ERROR:../gtk/gtkwidget.c:5590:gtk_widget_unrealize: assertion failed: (!widget->priv->mapped)
Bail out! Gtk:ERROR:../gtk/gtkwidget.c:5590:gtk_widget_unrealize: assertion failed: (!widget->priv->mapped)
```

The first "gtk" error in the long list of error is:

```
Traceback (most recent call last):
  File "/nix/store/iv8sxkjmyah7xppi2nnk03v7mkq77kz1-meld-3.23.1/lib/python3.13/site-packages/meld/diffgrid.py", line 35, in do_realize
    self._handle1.realize(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/iv8sxkjmyah7xppi2nnk03v7mkq77kz1-meld-3.23.1/lib/python3.13/site-packages/meld/diffgrid.py", line 281, in realize
    attr.cursor = Gdk.Cursor.new_from_name(
                  ~~~~~~~~~~~~~~~~~~~~~~~~^
        widget.get_display(),
        ^^^^^^^^^^^^^^^^^^^^^
        "col-resize",
        ^^^^^^^^^^^^^
    )
    ^
TypeError: constructor returned NULL
```

Running meld with `GDK_BACKEND=x11` fix the problem.

using nixos-unstable.

*edit*:

Problem solved by changing my cursors. I removed this from my home-manager logic:

```diff
   gtk = {
     enable = true;
-
-    cursorTheme.package = pkgs.xcursor-themes;
-    cursorTheme.name = "whiteglass";
-    cursorTheme.size = 16;
   };
```
