### ISSUE TITLE
python-xdis out of date for uncompyle6

### ISSUE THREAD

**Issue by irimi1** [NixOS/nixpkgs#89713]
The latest packaged version of xdis is 4.2.4, while uncompyle6 already requires `xdis<4.6.0,>=4.5.1`.

**To Reproduce**
`nix-env -i python3.7-uncompyle6`

**Expected behavior**
Required dependencies are packaged.

**Additional context**
uncompyle6 is required for unrpa, which is the package I originally tried to install.

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre228204.467ce5a9f45"`
 - channels(manu): `"home-manager, nixos-20.09pre228204.467ce5a9f45, nixpkgs-20.09pre228384.c27e54de99d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: unrpa
# a list of nixos modules affected by the problem
module: python3.7-uncompyle6
```
I tried bumping xdis to 4.5.1, but the load file test fails. Unfourtunately I have no idea how to fix it (yet):

```
ImportError: File name: '/build/source/xdis/__pycache__/load.cpython-37.pyc' doesn't exist
```

**Comment by deliciouslytyped** [comment]
I also have this issue.

**Comment by onny** [comment]
xdis has been updated, should be fixed now
