### ISSUE TITLE
python37Packages.apache-airflow no longer builds on master

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixpkgs#89746]
Starting an issue to track, as this may involve several steps to fix.

First problem is that dependencies are broken from a pytest upgrade:
https://github.com/NixOS/nixpkgs/pull/89586

CC @ingenieroariel @jonringer @FRidh

**Comment by ingenieroariel** [comment]
@bhipple thanks for taking on this - is there something we can wire up to the regular tests to detect breakage like this automatically in the future?

**Comment by bhipple** [comment]
I think Hydra is OK, with `nixpkgs-review` on PRs and some care.  

Once we get it fixed, it'd also be nice to upgrade to the latest 1.10.10 version.

**Comment by jonringer** [comment]
> @bhipple thanks for taking on this - is there something we can wire up to the regular tests to detect breakage like this automatically in the future?

hydra can be configured to issue emails to maintainers. I don't remember the history as to why it was disabled

**Comment by FRidh** [comment]
It would sent mails not just when your package build fails, but also if a dependency failed, causing mass spam in case of bigger failures on staging.

**Comment by jonringer** [comment]
@FRidh is there a way to enable it per jobset, so that it would only ping people for nixpkgs-unstable?

**Comment by drewrisinger** [comment]
I would appreciate something like this Hydra email. I don't constantly rebuild against ``nixpkgs-unstable``, and occasionally find that my packages are broken due to upstream changes, which I could have fixed earlier.

**Comment by jonringer** [comment]
@drewrisinger I guess it was disabled as it was causing mass spam
