### ISSUE TITLE
Second login session immidiatly terminated

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#89757]
**Describe the bug**
When another user is logged in, logging as second user fails (X is started but it finishes soon after).

**To Reproduce**
1. Log in as user 1 into Wayland session
2. Switch user to go to login screen
3. Log in as user 2

**Expected behavior**
User 2 session starts.

**Additional context**
```
Jun 06 21:45:00 babylon5 /nix/store/wr537kjb3gkashinv79jx1fz34fjhikz-gdm-3.34.1/libexec/gdm-x-session[5079]: (WW) modeset(0): flip queue failed: Permission denied
Jun 06 21:45:00 babylon5 /nix/store/wr537kjb3gkashinv79jx1fz34fjhikz-gdm-3.34.1/libexec/gdm-x-session[5079]: (WW) modeset(0): Page flip failed: Permission denied
Jun 06 21:45:00 babylon5 /nix/store/wr537kjb3gkashinv79jx1fz34fjhikz-gdm-3.34.1/libexec/gdm-x-session[5079]: (EE) modeset(0): present flip failed
```
I would note that it worked on Arch in the same configuration of drivers.

**Notify maintainers**
 - linux: @thoughtpolice 
 - systemd (loginctl): @andir @edolstra @flokli @Mic92 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.03.2059.05a32d8e771 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2059.05a32d8e771"`
 - channels(mpiechotka): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
Please provide more information here, like a minimal system configuration, and how and what wayland session you start. @prusnak added `gnome3` here, not sure if that's just a guess.

**Comment by siraben** [comment]
Any updates on this?

**Comment by prusnak** [comment]
> Any updates on this?

Does this still affect you on 20.09? 20.03 is not supported anymore.

**Comment by siraben** [comment]
@uzytkownik
