### ISSUE TITLE
nix-shell and lorri interact badly with vulkan-validation-layers

### ISSUE THREAD

**Issue by loewenheim** [NixOS/nixpkgs#89816]
**Describe the bug**
`nix-shell --pure` and `lorri shell` report `XDG_DATA_DIRS: unbound variable` and fail when `vulkan-validation-layers` is included.

**To Reproduce**
For `nix-shell`: `nix-shell --pure -p vulkan-validation-layers`
For `lorri`:
1. Call `lorri init` in a new directory
2. Add `vulkan-validation-layers` to `shell.nix`
3. Call `lorri shell`

**Expected behavior**
You get an environment in which `vulkan-validation-layers` is active.

**Additional context**
It's probably related to this: https://github.com/NixOS/nixpkgs/blame/b56c66e7e8565b16a4964840ef40243e07f78e84/pkgs/development/tools/vulkan-validation-layers/default.nix#L22-L25

Also see this `lorri` issue: https://github.com/target/lorri/issues/262

**Notify maintainers**
@acowley 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09pre227577.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"home-manager, nixos-20.09pre228622.029a5de0839"`
 - channels(sebastian): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by acowley** [comment]
I’m open to suggestions for a different way to fix that.

**Comment by matthewbauer** [comment]
I think you just need to allow XDG_DATA_DIRS to be unset like:

```
    export XDG_DATA_DIRS=@out@/share:${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
```

**Comment by matthewbauer** [comment]
actually `addToSearchPath` should do it:

```
addToSearchPath XDG_DATA_DIRS @out@/share
export XDG_DATA_DIRS
```

**Comment by acowley** [comment]
@matthewbauer Still in the `shellHook`?

**Comment by matthewbauer** [comment]
yes

**Comment by Profpatsch** [comment]
I think we can close this, feel free to reopen.
