### ISSUE TITLE
No documentation on valid symbol/variable names

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#8983]
There is no section in the manual explaining what symbols (variables) may look like.

Considering that, an unambiguous and easy no-nonsense way would be to add a grammar for nixexprs.

**Comment by vcunat** [comment]
The docs could be improved in this respect, I suppose, though I find adding a full grammar counter-productive (and it is in the source tree). This is more of a nix issue than nixpkgs, but I'll leave it open.

There are some examples in http://nixos.org/nix/manual/#ssec-values (in "sets" section); specifically, it's mentioned that you can use anything as attribute names as long as it's double-quoted. This could be split away into a section about identifier names, as I think the same rules should apply to let-bindings as well (i.e. if they don't, we should unify them).

**Comment by Profpatsch** [comment]
> This is more of a nix issue than nixpkgs, but I'll leave it open

Right, it actually is.

> This could be split away into a section about identifier names, as I think the same rules should apply to let-bindings as well

Exactly this is why a formal specification is always of value. And then it’s easy to find bugs in the implementation, because it’s well defined what a bug /is/

**Comment by Profpatsch** [comment]
Moved it to the nix repo. https://github.com/NixOS/nix/issues/592
