### ISSUE TITLE
libcxxStdenv broken on linux

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#8988]
I fixed this issue in 172ed10426df966ee5df76a1ef18f683698fe23f (see also #8546 and #8549). @pikajude reverted this commit without discussion in b62baacbc177cf799d88c2b519015a13ef91891c. I assume this was due to an unspecified error he alluded to at https://github.com/pikajude/nixpkgs/commit/172ed10426df966ee5df76a1ef18f683698fe23f#commitcomment-11921957. As can be seen there, I tried to get more information so his issue could be correctly fixed, but now we're back where we started.

I use libcxxStdenv for some of my projects, and need it to be functional on linux. I had assumed the merge was good until I pulled nixpkgs master today, seeking to update my development tools, and found the revert. I don't understand why this commit was reverted with no meaningful discussion. At the very least, I'd like to hear the details of what, if any, issues actually exist with the fix on OSX, so that I can attempt to fix them. As discussed in the above links, the previous--and now once again current--behavior of libcxxStdenv was clearly wrong, and should not remain on any platform.

**Comment by Ralith** [comment]
I got in touch with @pikajude on IRC, and we resolved the OSX breakage and restored the changes to staging as of fa6c8445c768a64c908fcd4d2955843622ba2550.

**Comment by vcunat** [comment]
Good!
