### ISSUE TITLE
insanity:  polkit depends on spidermonkey

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#8989]
Citing the offender:
```
[deepfire@andromedae:~/src/nixpkgs]$ head -n3 pkgs/development/libraries/polkit/default.nix
{ stdenv, fetchurl, pkgconfig, glib, expat, pam, intltool, spidermonkey
, gobjectIntrospection, libxslt, docbook_xsl, docbook_xml_dtd_412
, useSystemd ? stdenv.isLinux, systemd }:
```

**Comment by deepfire** [comment]
Quoting thoughtpolice from #nixos:
```
<thoughtpolice> You can disable polkit in your configuration.nix. It's
                      unclear how much stuff will continue to work without it,
                      I dunno.
<thoughtpolice> e.g. networkmanager enables polkit authorization
                      rules. These require JavaScript. Although, it would be
                      nice to replace the spidermonkey dependency anyway...
<thoughtpolice> Or rather, the way it will work.
```

**Comment by vcunat** [comment]
Upstream decided to write configs in javascript. I saw no good way around the dependency when it was introduced, but anyone can try.

**Comment by domenkozar** [comment]
Not sure how we can really fix that at NixOS without changing upstream.

**Comment by edolstra** [comment]
Indeed, not much we can do about this. Also, spidermonkey isn't that big (3.7 MB). It could be reduced a bit further by splitting libraries and headers and getting rid of the static library.

**Comment by edolstra** [comment]
Sorry, was looking at the wrong spidermonkey version. 17.0 is quite a bit bigger (9.8 MB).

**Comment by deepfire** [comment]
@edolstra, from my point of view, it's not as much about the size, as it is about making a crucial piece of security architecture depend on a humongously complicated piece of.. JavaScript.

**Comment by edolstra** [comment]
Why is it humongously complicated? I doubt it's more complicated than (say) Glibc, Python, Perl, ...

**Comment by deepfire** [comment]
The point is, it's extra complexity. Security rules should be declarative in nature, not executable code.

**Comment by edolstra** [comment]
That's something you should take up with the polkit maintainers.

But note that only root can specify such rules, so I don't really see the (security) problem.

**Comment by deepfire** [comment]
I understand it's not NixOS choice.. just at least spelling it out, for the record..

**Comment by cyraxjoe** [comment]
This has just come to my attention and just for the record too...  the "work around" on debian/ubuntu land is to use the 0.105 version, before the change in the format for the config files, therefore before the spider monkey dependency.

**Comment by matthewbauer** [comment]
Spidermonkey has gotten bigger and bigger over the years. I found this thread on removing it from polkit:

https://forums.gentoo.org/viewtopic-t-1092476-start-0.html

Might be worth investigating if we ever want a very minimal NixOS.

**Comment by Arnaudv6** [comment]
For the record
https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/35

**Comment by deliciouslytyped** [comment]
This caught my attention because by trying to rebuild PAM with debugging enabled in sshd (not sure if thats even sufficient, and also ridiculous as well, but ...), it causes a rebuild of polkit, spidermonkey, the rust compiler (i think?).

**Comment by zhangn1985** [comment]
debian is still using 0.105
