### ISSUE TITLE
NixOS closure size increase

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#8990]
The closure size of my KDE4-based configuration has increased significantly between 14.12 and 15.07 (6ad8fab), from 3.2 GB to 4.1 GB.

Some causes:
* OpenJDK is now pulled in by libbluray.
* Mysql has been replaced by mariadb, which is much larger.
* `firmware-linux-nonfree` has exploded from 34 MB to 106 MB.
* Samba has grown by 20 MB.
* `mesa-noglu` has a runtime dependency on llvm.
* libdmtx (whatever that is) now pulls in imagemagick and graphviz.
* Emacs and librsvg now depends on GTK+ 3, causing the system closure to contain 2 versions of GTK+.
* Heimdal pulls in flex.
* Libtool pulls in gnum4.

Non-regressions: the system closure contains linux-dev and 2 versions of ffmpeg.

**Comment by vcunat** [comment]
- Pushed a libdmtx fix.
- Libtool: it's because I made it a propagated build input in 0ffb98828. I don't see any documentation why (and don't remember clearly), so we can try no longer propagating it and fixup builds that do need `m4` with `libtool`. It's ~0.5 MB, pulls in nothing else, and I consider `libtool` a build tool that shouldn't be in system closures anyway, but we can try it.
- Heimdal: attribute `heimdalFull` does but `libHeimdal` doesn't. /cc maintainer @wkennington.

**Comment by vcunat** [comment]
- libbluray: I read java support [is required](https://en.wikipedia.org/wiki/BD-J) for BR player compliance. /cc maintainer @abbradar. Personally, I wouldn't need any BR support by default in players, but having basic support (without java) might be a good compromise.

**Comment by abbradar** [comment]
Fair enough; if someone actually needs it, he can override it for his
video player of choice making build times manageable (disclaimer: I
don't watch BRs by myself and don't know someone who does, so I cannot
assess how common BD-J is). I can't do this till Tuesday, but I don't
mind if you (or someone else) change the `withJava` default earlier.

On 07/26/2015 11:43 AM, Vladimír Čunát wrote:
>   * libbluray: I read java support is required
>     <https://en.wikipedia.org/wiki/BD-J> for BR player compliance. /cc
>     maintainer @abbradar <https://github.com/abbradar>. Personally, I
>     wouldn't need any BR support by default in players, but having basic
>     support (without java) might be a good compromise.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/8990#issuecomment-124957957>.
> 

-- 
Nikolay.

**Comment by edolstra** [comment]
Also of interest: the closure contains 3 copies of poppler:
```
6.2M    /nix/store/grx717yjk1i06db171cp9gfqvs26vsyx-poppler-glib-0.32.0/
6.9M    /nix/store/5sgyjzp9cmpkplzigw8rkdcqywwl82z1-poppler-qt4-0.32.0/
6.8M    /nix/store/1k2zyrww5c0zh71ddabq4ba78zncf97n-poppler-utils-0.32.0/
```

**Comment by vcunat** [comment]
The separate building of poppler parts is a problem; maybe with some extra amount of work it could be fixed. c0d5cd0ff9 Therefore, we either get a bloat in space or in build-time dependencies (qt4, qt5).

**Comment by rbvermaa** [comment]
Is this still a blocker? What is left to do here? What are the goal closure sizes before we can release?

**Comment by domenkozar** [comment]
@edolstra is this done?

**Comment by edolstra** [comment]
I think the staging branch still needs to be merged, but there currently is some breakage there (https://github.com/NixOS/nixpkgs/commit/4a495cfbab2b3ab9ae8219ef1812c766bf27b01e#commitcomment-12780893). Also, the whole thing needs to be rebuilt due to a Glibc security patch.

**Comment by domenkozar** [comment]
This is now in master

**Comment by vcunat** [comment]
All resolved now, I believe.
