### ISSUE TITLE
python does not build on macOS with current staging

### ISSUE THREAD

**Issue by parthy** [NixOS/nixpkgs#89912]
**Describe the bug**
#84072 seems to have broken the build for python3Minimal on macOS. The error is:

```bash
$ clang -L/nix/store/53kj31vsfqa4j8p1dz2y6n85sn5dbn3d-zlib-1.2.11/lib -L/nix/store/i36f95v4mjdx7bll0kzhl5mwqk49cj1m-bzip2-1.0.6.0.1/lib -L/nix/store/xv5zvirmalz6x7fx2h3axzkqxfpxicb6-expat-2.2.8/lib -L/nix/store/my4hsdi9hhp6lgh90vf6v8rsqmwaqwh5-xz-5.2.5/lib -L/nix/store/ppm2qmsxip74vxzrdvwg14f66ar9hzv9-libffi-3.3/lib -L/nix/store/53kj31vsfqa4j8p1dz2y6n85sn5dbn3d-zlib-1.2.11/lib -L/nix/store/i36f95v4mjdx7bll0kzhl5mwqk49cj1m-bzip2-1.0.6.0.1/lib -L/nix/store/xv5zvirmalz6x7fx2h3axzkqxfpxicb6-expat-2.2.8/lib -L/nix/store/my4hsdi9hhp6lgh90vf6v8rsqmwaqwh5-xz-5.2.5/lib -L/nix/store/ppm2qmsxip74vxzrdvwg14f66ar9hzv9-libffi-3.3/lib   -Wl,-stack_size,1000000  -framework CoreFoundation -o Programs/_testembed Programs/_testembed.o -L. -lpython3.8 -lintl -ldl    -framework CoreFoundation    
ld: warning: ld: warning: object file (/nix/store/0lsij4jl35bnhqhdzla8md6xiswgig5q-Libsystem-osx-10.12.6/lib/crt1.10.6.o) was built for newer OSX version (10.12) than being linked (10.6)object file (/nix/store/0lsij4jl35bnhqhdzla8md6xiswgig5q-Libsystem-osx-10.12.6/lib/crt1.10.6.o) was built for newer OSX version (10.12) than being linked (10.6)
```

Reverting that MR seems to work fine.

**To Reproduce**
1. check out staging
2. nix-build . -A pkgs.python3Minimal

**Expected behavior**
The package should build correctly.

**Notify maintainers**
@gnprice @FRidh 

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.3`
 - channels(parthy): `"nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/Users/parthy/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
cc @NixOS/darwin-maintainers 

Does `python38` built currently on darwin? Aside from the optimizations we changed default Python from 3.7 to 3.8, that goes also for `python3Minimal`.

**Comment by parthy** [comment]
After reverting that PR I mentioned, I was able to build `/nix/store/jxjwj1aa7srdkaivv72ifgf60ryprj3a-python3-minimal-3.8.3`.

**Comment by FRidh** [comment]
One part got reverted, the other significant part is behind a switch, which is put to false for `python3Minimal`.

If you take staging (where it failed), and you would set `python3 = python37`, does it build then?

**Comment by parthy** [comment]
If I do `python3Minimal = (python37.override {` instead of `python3Minimal = (python38.override {`, it still doesn't work.

Only the revert does the trick for me.

**Comment by vcunat** [comment]
BTW, default python38 is also affected (non-minimal), e.g. [this build](https://hydra.nixos.org/build/121923309).

**Comment by FRidh** [comment]
This has been fixed.
