### ISSUE TITLE
php --ini has unexpected output when built with xml extension

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#89913]
**Describe the bug**

I noticed a warning with our new `php` build that I was hoping we might be able to dig into.

**To Reproduce**
1. build `php.withExtensions ({ all, enabled }: with all; [ bcmath ctype fileinfo json mbstring openssl pdo pdo_mysql tokenizer xml ])`
2. run `php` binary built from above expression: `/nix/store/zrbqc3i9fbi2znb0sb23p2j7j2xad1lh-php-with-extensions-7.4.6/bin/php --ini`

**UNexpected behavior**
A clear and concise description of what you *didn't* expect to happen.
```
PHP Warning:  Module 'xml' already loaded in Unknown on line 0
Configuration File (php.ini) Path: /nix/store/mzd7225qpg6m005fqnlhd5b97yg07dpi-php-7.4.6/lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /nix/store/zrbqc3i9fbi2znb0sb23p2j7j2xad1lh-php-with-extensions-7.4.6/lib
Additional .ini files parsed:      /nix/store/zrbqc3i9fbi2znb0sb23p2j7j2xad1lh-php-with-extensions-7.4.6/lib/php.ini
```

**Screenshots**

**Additional context**

**Notify maintainers**

ping @etu @talyz

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Running on a recent copy of `master`.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: php
# a list of nixos modules affected by the problem
module:
```

**Comment by etu** [comment]
The `xml` extensions is one of very few that we actually have enabled by default in the minimal build.

**Comment by aanderse** [comment]
Ah, OK. Should we document that, issue a warning when something has been added multiple times, or filter out duplicates internally, etc... Thoughts?

**Comment by Ma27** [comment]
Shouldn't we make sure that this doesn't happen in the first place?

**Comment by aanderse** [comment]
"filter out duplicates internally" would accomplish that. What did you have in mind?

**Comment by etu** [comment]
We could remove `php.extensions.xml`

**Comment by Ma27** [comment]
I understand that we want to keep it as separate package as well. But I mean, why not filtering already loaded extensions during eval or build?

**Comment by talyz** [comment]
@Ma27 Well, mainly because it doesn't really have a way of knowing what extensions are built into PHP right now - we would need to expose that from the PHP derivation somehow, but it's probably not worth the effort, since this only is a warning and can be easily solved by disabling the `xml` extension until we can build PHP without it.

**Comment by aanderse** [comment]
@talyz what would it take for us to compile without? Are there any major obstacles?

**Comment by etu** [comment]
We have two problems to compile without XML:
1) pearSupport requires XML

And even if we were to ditch pearSupport by default (who uses that?), we ran into:
2) It seems like mysql, but worse, needs patching, and not sure how much or little patching.

**Comment by aanderse** [comment]
I'm still interested in coming back to this at some point so I'll mention now to remove the stale marker.
