### ISSUE TITLE
VirtualBox: shared clipboard does not work

### ISSUE THREAD

**Issue by vanschelven** [NixOS/nixpkgs#89923]
**Describe the bug**

Copy pasting from host to guest and vice versa is not working on NixOS 20.03. It was working on 19.09. My host system in MacOS; VirtualBox Versions 6.0.16 r135674 (Qt5.6.3) and 6.0.22 r137980 (Qt5.6.3) both exhibit this problem.

I’ve set all of the below in my configuration.nix

```
{
  nixpkgs.config.allowUnfree = true;
  virtualisation.virtualbox.host.enable = true;
  nixpkgs.config.virtualbox.host.enableExtensionPack = true;
}
```

The associated dropdown in the settings pane (“Shared Clipboard”) is set to “Bidirectional”.

Further debugging:

Trying to see what's running:

```
$ ps aux | grep irtual

klaas      870  0.0  0.0 229464   528 ?        S    13:29   0:00 /nix/store/vvjqmj4ghyfdsvh11j0ysnjy7az2hzgl-VirtualBox-GuestAdditions-6.1.6-5.4.43/bin/VBoxClient --seamless
klaas      872  0.0  0.1 361568  2884 ?        Sl   13:29   0:00 /nix/store/vvjqmj4ghyfdsvh11j0ysnjy7az2hzgl-VirtualBox-GuestAdditions-6.1.6-5.4.43/bin/VBoxClient --seamless
klaas      876  0.0  0.0 229464   528 ?        S    13:29   0:00 /nix/store/vvjqmj4ghyfdsvh11j0ysnjy7az2hzgl-VirtualBox-GuestAdditions-6.1.6-5.4.43/bin/VBoxClient --draganddrop
klaas      877  0.3  0.1 362084  2936 ?        Sl   13:29   0:29 /nix/store/vvjqmj4ghyfdsvh11j0ysnjy7az2hzgl-VirtualBox-GuestAdditions-6.1.6-5.4.43/bin/VBoxClient --draganddrop
```

Comparing this with the same command on 19.09 reveals that I'm missing lines for `--display`, `--checkhostversion` and, most tellingly, `--clipboard`

Trying to get it to run:

```
$ /nix/store/vvjqmj4ghyfdsvh11j0ysnjy7az2hzgl-VirtualBox-GuestAdditions-6.1.6-5.4.43/bin/VBoxClient -f --clipboard

Shared Clipboard: Starting X11 event thread
Shared Clipboard: Stopping X11 event thread ... 
Shared Clipboard: X11 event thread terminated successfully
Error connecting to host service, rc=VERR_NOT_IMPLEMENTED
Service terminated abnormally with VERR_NOT_IMPLEMENTED
Running service failed: VERR_NOT_IMPLEMENTED
```

This seems to be the same bug as the following one for Ubuntu:

https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1875160

**Notify maintainers**
@svanderburg  @m-scr @Ma27 @fabian @B4dM4n

**Comment by Ma27** [comment]
Just for the record, I'm not a virtualbox maintainer :)

**Comment by vanschelven** [comment]
@Ma27 sorry about that, I noticed you were one of the past 4 or 5 committers to the package, and the official maintainer hasn't committed since 2011 (!).

**Comment by vanschelven** [comment]
This is for the VirtualBox Guest Additions 6.1.6 (just to clarify, since it can be deduced from the above).

**Comment by m-scr** [comment]
Can you try to update the host system's VirtualBox? I suspect the most recent Guest Additions may have developed some incompatibility with older versions of VBox.

**Comment by vanschelven** [comment]
> @vanschelven: can you try to update the host system's VirtualBox?

I did without success, but did not update the issue's description yet. It's updated now. (to reflect that this is still a problem for 6.0.22 r137980)

**Comment by vanschelven** [comment]
The following pages describe similar symptoms (although no fix):

* https://www.virtualbox.org/ticket/19234
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946843
* https://forums.virtualbox.org/viewtopic.php?f=3&t=96309

**Comment by NobbZ** [comment]
I think I have to add, that I do not have any problems with bidirectionally shared clipboard, I'm using the official virtualbox image. Currently on guests additions 6.1.6.

Host is windows 10, but I can't say anything more right now, as I'm not at that computer.

I will try to check with a nixOS host later this evening. Also I'll provide more info about my setup at work tomorrow to narrow this down.

**Comment by vanschelven** [comment]
In a further attempt at getting at the source of this I replaced my rather non-standard xmonad setup with a (presumably) more standard gnome setup... but to no avail:

before:

```
  services.xserver.windowManager.xmonad.enable = true;
  services.xserver.windowManager.xmonad.enableContribAndExtras = true;
  services.xserver.windowManager.default = "xmonad";
```

after:
```
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
```

**Comment by NobbZ** [comment]
Using the provided OVA (https://nixos.org/download.html#nixos-virtualbox) works for me OotB for the bidirectionally shared clipboard on nixOS host as well after enabling it in the machine settings.

Won't go to the office today, so can't tell more about the windows hosted machine.

Anyway, automatic resize did not work, but thats kind of expected as I neither have installed the patch from the forum, nor the PR from the repo as this was just a 5 minute test machine.

You need to show more of your configuration.

**Comment by gloaming** [comment]
It's working for me in 6.1.10: https://github.com/NixOS/nixpkgs/pull/89798/
but see https://github.com/NixOS/nixpkgs/issues/62980#issuecomment-647117120

**Comment by kerrnelPanic** [comment]
I ran into a similar problem with a nixos guest on win10 host. running 
`VBoxClient-all` in the guest made cnp working

**Comment by PsychoDude** [comment]
Still having this issue, running `VBoxClient-all` works but needs to be ran after every reboot
