### ISSUE TITLE
Sushi can't show videos

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#89922]
**Describe the bug**
When I try to preview videos like .mp4 or webm in Nautilus using Sushi, it says "Your GStreamer installation is missing a plug-in".

**To Reproduce**
1. run NixOS with Gnome3 desktop
2. Press space on a video file in Nautilus

**Additional context**
It's possible that there's some configuration in my homedir that makes it break, since I have the same homedir that I had under other Linux installs, not sure how to find it however.

`jourmalctl` outputs
```
Jun 09 15:15:21 wmertens-nixos .org.gnome.Naut[19899]: gst_object_unref: assertion 'object != NULL' failed
Jun 09 15:15:21 wmertens-nixos .org.gnome.Naut[19899]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Jun 09 15:15:21 wmertens-nixos .org.gnome.Naut[19899]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 09 15:15:21 wmertens-nixos .org.gnome.Naut[19899]: gst_object_unref: assertion 'object != NULL' failed
Jun 09 15:15:21 wmertens-nixos .org.gnome.Naut[19899]: Your GStreamer installation is missing a plug-in.
```

**Notify maintainers**
@jtojnar maybe?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.09pre226107.62e866e4fd6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(wmertens): `"home-manager, nixpkgs-20.09pre228384.c27e54de99d"`
 - channels(root): `"nixos-20.09pre228622.029a5de0839, nixos-hardware, nixpkgs-20.09pre226107.62e866e4fd6"`
 - nixpkgs: `/home/wmertens/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sushi
# a list of nixos modules affected by the problem
module: sushi
```

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/blob/4f9e07deb2645999257a5de7cc15e15c1d4a8744/pkgs/desktops/gnome-3/core/sushi/default.nix#L58-L60

Would need to add `bad` here, I think.

**Comment by wmertens** [comment]
@jtojnar that makes sense - it seems like I would like the bad and the ugly too.

How about a nixpkgs configuration setting that decides which plugin sets to load, and having plugins-base include them? That should make it backwards-compatible.

**Comment by jtojnar** [comment]
Most of them depend on base so that would be a dependency cycle. Also we would need to move the wrappers into a separate derivation or we would have to rebuild everything.

Alternately, you can set `GST_PLUGIN_SYSTEM_PATH_1_0` environment variable (I believe some NixOS module does that). Not a fan but it should work provided some ABI break does not sneak in.

**Comment by wmertens** [comment]
Still a problem

**Comment by doronbehar** [comment]
> Most of them depend on base so that would be a dependency cycle. Also we would need to move the wrappers into a separate derivation or we would have to rebuild everything.

@jtojnar if sushi is not a dependent of any package then why would we have to rebuild everything? What do you mean by everything? Perhaps until a separate wrapper derivation is composed we can add a configuration option to the `sushi` nixos module that would add these gstreamer `buildInputs` to it if needed.

Also, `sushi` doesn't work at all for me nowadays, I think since Gnome 41.

**Comment by jtojnar** [comment]
@doronbehar I was replying to Wout’s question above regarding a general solution pulling extra plug-ins into gst-plugins-base.

For now, I would be fine with adding everything unconditionally to sushi as mentioned in https://github.com/NixOS/nixpkgs/issues/89922#issuecomment-641293602.

I must have forgotten to test it during the update when I removed libmusicbrainz but forgot to add libsoup:

> org.gnome.NautilusPreviewer[1480843]: Unsatisfied dependency: Soup

Could you try https://github.com/NixOS/nixpkgs/pull/147292
