### ISSUE TITLE
nix-prefetch-git produce wrong hash on git LFS

### ISSUE THREAD

**Issue by igsha** [NixOS/nixpkgs#89926]
**Describe the bug**

Github uses `Git LFS` to store binary files in repos. This leads to mismatched hashes between `nix-prefetch-git` and `nix-prefetch-url --unpack`.

**To Reproduce**

Example for https://github.com/KhronosGroup/OpenVX-cts.

nix-prefetch-git:
```
$ nix-prefetch-git --quiet https://github.com/KhronosGroup/OpenVX-cts --branch-name openvx_1.3 | jq -r .sha256
1cgp1nrwbh3mcpcaa7i8yfqvl9pa3iq0vhzpym4ypwarl268228k
```

nix-prefetch-url (this is equal to fetchFromGitHub):
```
$ nix-prefetch-url --unpack https://github.com/KhronosGroup/OpenVX-cts/archive/openvx_1.3.tar.gz
[38.1 MiB DL]
path is '/nix/store/a030nyv0db095z1yvbpfgzak705wij0f-openvx_1.3.tar.gz'
1z882v2j91p1217sm0qvs0wzhrrkgpd2j8ybsz042f2laiivy4jv
```

**Expected behavior**

The hashes should be equal for both methods.

**Additional context**

I've noticed difference in files `OpenVX-cts/test_conformance/Networks/Binaries`. There are a lot of binary files but their contents after `git clone` (without `git lfs checkout` step) is like
```
$ cat OpenVX-cts/test_conformance/Networks/Binaries/Alexnet/conv1_bias.bin
version https://git-lfs.github.com/spec/v1
oid sha256:651901ab77fd02ea8f247a65d720973ca4ef1ebe32bc137476aea2653c203721
size 192
```
`fetchFromGitHub` produced correct binary files:
```
$ sha256sum /nix/store/n13p4cmzb76vfc9wwhadyby1kxq9a8cc-source/test_conformance/Networks/Binaries/Alexnet/conv1_bias.bin
651901ab77fd02ea8f247a65d720973ca4ef1ebe32bc137476aea2653c203721  /nix/store/n13p4cmzb76vfc9wwhadyby1kxq9a8cc-source/test_conformance/Networks/Binaries/Alexnet/conv1_bias.bin
```
Does this problem affect `fetchgit` module?

**Notify maintainers**

cc @jtojnar @bhipple as last active maintainers.

**Metadata**

`nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.44, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre228622.029a5de0839"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SuperSandro2000** [comment]
> Github uses `Git LFS` to store binary files in repos.

that is not quite right, GitHub only does that if it got configured.

This is related to GitHub not adding the files in the archive download, see https://github.com/git-lfs/git-lfs/issues/903
