### ISSUE TITLE
Silent runtime error due to not finding LLVMPolly.so

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#89954]
**Describe the bug**
Applications using https://github.com/pocl/pocl silently die at runtime when built with SLEEF and llvm 10. LD_DEBUG=libs reveals this to be due to a missing symbol "getPollyPluginInfov" which seems like it's part of llvm-polly. The llvm path in the nix store does contain a library called LLVMPolly.so, but llvm-lib (which llvm-config sets as the library path) does not.

**To Reproduce**
1. Build pocl with host CPU devices, SLEEF and ICD enabled.
2. Use said ICD to run any OpenCL application (clinfo will probably do)
3. application exits silently, setting LD_DEBUG=libs shows fatal error message about getPollyPluginInfov

**Expected behavior**
Applications making use of polly Just Work with no tweaks now that it is included in the default llvm package.

**Notify maintainers**

@ggreif @DieGoldeneEnte were active in the PR that enabled polly by default so I guess you might know something useful.

**Metadata**
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: llvmPackages_10
```

**Comment by DieGoldeneEnte** [comment]
can you tell me how to use te ICD to run clinfo (point 2)? I managed to compile pocl (I assume you meant https://github.com/pocl/pocl).

**Comment by DieGoldeneEnte** [comment]
ok I think I managed it :)
I compile using this Enviroment: `nix-shell -p clang_10 cmake pkgconfig hwloc llvm_10 ocl-icd lttng-ust llvmPackages_10.clang-unwrapped`
and run cmake with -DENABLE_ICD=True (I didn't find a SLEEF flag, but it is enabled).
running `OCL_ICD_VENDORS=./ocl-vendors clinfo` I get following output:
```
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 1.6-pre master-0-gf522111b, Debug+Asserts, LLVM 10.0.0, RELOC, SPIR, SLEEF, LTTNG, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   Portable Computing Language
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   
  clCreateContext(NULL, ...) [default]            No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.10
  ICD loader Profile                              OpenCL 2.1
```
Even with LD_DEBUG=libs I didn't get any mention of polly. Probaby, because it can't find my CPU?

How do you set it up, maybe I have missed an important flag?

**Comment by jansol** [comment]
Yes, `OCL_ICD_VENDORS` is the way to go, as explained in the [documentation](https://github.com/pocl/pocl/blob/master/doc/sphinx/source/using.rst). You'll also need to build with `-DENABLE_LLVM=1 -DENABLE_HOST_CPU_DEVICES=1`, SLEEF is then on by default IIRC.

When you have it built, set `POCL_DEVICES=basic` to enable the CPU as a compute device.

I used to import things like llvmPackages.libstdcxxClang since I was getting some build errors without them. Seems that is not necessary anymore with clang_10 and llvm_10, nice. 

Anyhow even with the environment set up like yours I still get `build/lib/CL/libpocl.so.2.5.0: error: symbol lookup error: undefined symbol: _Z18getPollyPluginInfov (fatal)`.

**Comment by DieGoldeneEnte** [comment]
How do you build pocl?
I quickly wrote a [package](https://gist.github.com/DieGoldeneEnte/5ff16544bf5b46ba216998e50e835d43), because I had problems with pocl include/library paths without it. Dropping into the shell it works without problems.

**Comment by jansol** [comment]
I'm using [this](https://gist.github.com/jansol/beef2a9787cd50c6c43ce8681acd03a8) for development with some additional cmake flags & env variables that are needed for the private branch I'm working on but not related to any thing that touches llvm stuff.

I'm on nixos-unstable as well.

**Comment by DieGoldeneEnte** [comment]
I can't reproduce it, but I also don't understand how you would build pocl with your script.
When I try to compile it in that environment I get a whole bunch of errors unrelated to Polly.

**Comment by jansol** [comment]
Interesting, what kind of errors? I just open nix-shell with `nix-shell --run /run/current-system/sw/bin/bash` (I have an alias from that because using zsh as the default shell was causing problems) and do the standard routine of
```
$configureCommand
ninja
```

**Comment by DieGoldeneEnte** [comment]
The build itself is not the problem, but the placement of the resulting files. For example is it searching `libpocl-devices-basic.so` in the wrong place and one I symlink it, another file can't be found.

```
$ POCL_DEBUG=1 POCL_DEVICES=basic clinfo
```
Errors when using master:
```
[2020-05-15 10:58:48.388453966]POCL: in fn pocl_init_devices at line 571:
  |   GENERAL |  Installing SIGFPE handler...
[2020-05-15 10:58:48.388493568]POCL: in fn pocl_init_devices at line 602:
  |   WARNING |  Loading /tmp/pocl/build/lib/CL/pocl/libpocl-devices-basic.so failed.
[2020-05-15 10:58:48.388505846]POCL: in fn pocl_init_devices at line 602:
  |   WARNING |  Loading /tmp/pocl/build/lib/CL/pocl/libpocl-devices-pthread.so failed.
[2020-05-15 10:58:48.388509735]POCL: in fn pocl_init_devices at line 621:
  |     ERROR | CL_DEVICE_NOT_FOUND no devices found. POCL_DEVICES=basic
```
Errors when using v1.5:
```
[2020-05-15 11:03:24.708948525]POCL: in fn compile_and_link_program at line 634:
  |   GENERAL |  building from sources for device 0
1 error generated.
[2020-05-15 11:03:24.719180075]POCL: in fn void appendToProgramBuildLog(cl_program, unsigned int, std::string&) at line 140:
  |     ERROR |  error: <built-in>:1:10: '/tmp/pocl/build/lib/CL/../share/pocl/include/pocl_types.h' file not found
[2020-05-15 11:03:24.720767575]POCL: in fn compile_and_link_program at line 640:
  |     ERROR | build_error_code pocl_llvm_build_program() failed
=== CL_PROGRAM_BUILD_LOG ===
error: <built-in>:1:10: '/tmp/pocl/build/lib/CL/../share/pocl/include/pocl_types.h' file not found
[2020-05-15 11:03:24.720780354]POCL: in fn POclCreateKernel at line 59:
  |     ERROR | CL_INVALID_PROGRAM_EXECUTABLE Last BuildProgram() was not successful
```

**Comment by jansol** [comment]
Ah right, you'll need to set the `POCL_BUILDING` [environment variable](https://github.com/pocl/pocl/blob/master/doc/sphinx/source/using.rst#tuning-pocl-behavior-with-env-variables) to 1 so it searches for the builtin headers etc from the build directory.

On another note, I did try using your package but it does not seem to import the dependencies into the shell environment at all? What nix-shell command are you using it with?

**Comment by DieGoldeneEnte** [comment]
Following your instructions, it searches `open-cl-cbase.h` in the wrong directory (should be clang not clang-wrapped).
```
error: <built-in>:3:10: '/nix/store/hk7rk8p5nzxl1jxr0q5y1fjjz659zyqs-clang-wrapper-10.0.0/lib/clang/10.0.0/include/opencl-c-base.h' file not found
```

With my package you can just execute `nix-shell` and are dropped in an environment with pocl installed and the `OCL_ICD_VENDORS` variable set accodingly , so you just need to execute `clinfo` to test it.

I retried my package and found these missing symbols: `clSetProgramSpecializationConstant`, `clIcdGetPlatformIDsKHR` and `clGetPlatformInfo` resulting in these warnings:
```
[2020-05-15 12:18:22.086227973]POCL: in fn cl_context POclCreateContextFromType(const cl_context_properties *, cl_device_type, void (*)(const char *, const void *, size_t, void *), void *, cl_int *) at line 87:
  |   WARNING |  Couldn't find any device of type 4; returning a dummy context with 0 devices
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
[2020-05-15 12:18:22.086239039]POCL: in fn cl_context POclCreateContextFromType(const cl_context_properties *, cl_device_type, void (*)(const char *, const void *, size_t, void *), void *, cl_int *) at line 87:
  |   WARNING |  Couldn't find any device of type 8; returning a dummy context with 0 devices
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
[2020-05-15 12:18:22.086245013]POCL: in fn cl_context POclCreateContextFromType(const cl_context_properties *, cl_device_type, void (*)(const char *, const void *, size_t, void *), void *, cl_int *) at line 87:
  |   WARNING |  Couldn't find any device of type 16; returning a dummy context with 0 devices
```

**Comment by jansol** [comment]
Huh, I don't seem to have that issue. But yes, clang vs clang-wrapped did cause quite some headaches while I was experimenting.

The problem with your package is that I need an environment where I can *develop* the library, not just use it, so I need all the build dependencies as constantly updating hashes and using nix-build is not exactly my idea of a good developer experience. It is also very possible that I have no idea what I'm doing with nix-shell and there is a more elegant way to go about this that I'm just not aware of. I also need to set a number of environment variables in addition to OCL_ICD_VENDORS and POCL_DEVICES since the feature I am working on uses them for configuration. The configureCommand variables is just for convenience, cmake does not handle changing config very well so I tend to erase the build directory whenever I need to do that, at which point it is nice to not have to type out the annoyingly long cmake line over and over again.

Not sure about those missing symbols, but the warnings don't seem to relate to them? They are caused by pocl not exposing any device that it counts as GPU or Accelerator devices. This is because no device of that type is enabled with `POCL_DEVICES` (assuming you actually have one and built the relevant driver in pocl). Also a co-worker told me that the pthread device is likely working better than basic. (I mostly need the CPU backend for sanity checking so which one exactly I use is not so important. Both need LLVM though so that is not particularly relevant to this issue.)

**Comment by DieGoldeneEnte** [comment]
I have an idea what the problem might be, you can test it with the [updated version](https://gist.github.com/DieGoldeneEnte/02a19a22b4986a3ca32a511b9e72ed08) of your nix-file.
It might not fix your problem and will rebuild clang so it will take a while, but it should be the minimum amount of rebuilds to test my hypothesis. What it does is compiling clang with RTTI enabled, so it matches llvm (which also has RTTI enabled).

**Comment by jansol** [comment]
That version gives me errors about missing `stddef.h` while configuring, and missing `opencl-c.h` while building. I vaguely recall running into that before, not sure what made it go away though..

**Comment by DieGoldeneEnte** [comment]
Maybe it was too hacky to change the build-parameters in this way (I don't often do it and usually not on this scale). If you could get it to reproduce using nix-build it would make it easier to get the same environment.

If I understand it correctly it worked with llvm 9?
There are some changes to the Plugin-Infrastructure from 9 to 10. They could cause a problem (but didn't for the simple tests I did).

**Comment by jansol** [comment]
It worked with the stock llvmPackages_10 and clang_10, maybe just a flag missing from the clang build? Also works on ubuntu 18.04

**Comment by jansol** [comment]
Closing this as the packaged version apparently works fine and the build environment issue is no longer relevant to me.

Thanks for your help & patience!
