### ISSUE TITLE
darwin: build fails for apple core services framework

### ISSUE THREAD

**Issue by mjhoy** [NixOS/nixpkgs#9002]
Hello,

I'm trying to build the `hakyll` haskell package, which has `fsnotify` as a dependency, which has a bunch of apple frameworks as dependencies.

```
$ nix-shell --dry-run '<nixpkgs>' -A haskell-ng.packages.ghc7101.fsnotify
these derivations will be built:
  /nix/store/9k8532id7k24nv0ql1gn5qkrk5p3llgi-CF-855.17.drv
  /nix/store/6vkyxzqqa0idldakvnfr6kp44jzhp3lc-apple-framework-CFNetwork.drv
  /nix/store/cmbbibd256fi4z663zbwfxxjj47dl5a3-apple-framework-IOKit.drv
  /nix/store/ds4ycc9hffbx3bn285lyaka0v0xznka7-apple-framework-NetFS.drv
  /nix/store/l71cq3yiajh2153qnw414ypl978a713k-apple-framework-Security.drv
  /nix/store/rkmr0xhzzp4fxa5iml10qvjw8yairfa0-apple-framework-DiskArbitration.drv
  /nix/store/x6wzjrjs3dwwqk26npjkqkjqj0rcqg4m-apple-framework-CoreAudio.drv
  /nix/store/xiscggk50vrp2n45y16dqihnvyhjsd9b-apple-framework-ServiceManagement.drv
  /nix/store/svlq48jnl0glk88djk920mn0r91wrzn2-apple-framework-CoreServices.drv
  /nix/store/lglnfgkkvr7zsyvjfn30rfdgv0j0qg8g-haskell-hfsevents-0.1.5.drv
```

And when I try to build them,

```
nix-shell '<nixpkgs>' -A haskell-ng.packages.ghc7101.fsnotify
```

I get a bunch of build output, which looks fine, but then at the bottom:

```
[....]
cp CF-Objects/normal/CoreFoundation_normal /nix/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks/CoreFoundation.framework/V
ersions/A/CoreFoundation
dsymutil /nix/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation -o /nix/s
tore/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks/CoreFoundation.framework.dSYM
chmod -R a-w,a+rX /nix/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks/CoreFoundation.framework
chmod -R u+w /nix/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks
install_name_tool -id /nix/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation /ni
x/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
Installing done.  The framework is in /nix/store/9h4ir7w1k5f3qwg979cnvrl32isjf4kw-CF-855.17/System/Library/Frameworks
cp: cannot stat '/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAttributedString.h': No such file or directory
builder for ‘/nix/store/9k8532id7k24nv0ql1gn5qkrk5p3llgi-CF-855.17.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/svlq48jnl0glk88djk920mn0r91wrzn2-apple-framework-CoreServices.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/lglnfgkkvr7zsyvjfn30rfdgv0j0qg8g-haskell-hfsevents-0.1.5.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/lglnfgkkvr7zsyvjfn30rfdgv0j0qg8g-haskell-hfsevents-0.1.5.drv’ failed
/Users/mjhoy/.nix-profile/bin/nix-shell: failed to build all dependencies
```

The culprit seems to be:

```
cp: cannot stat '/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAttributedString.h': No such file or directory
```

Any help appreciated! I'm on 10.9.5.
Mike

**Comment by mjhoy** [comment]
ah! It looks like I needed to install the (latest?) apple command line tools -- which I thought I had done, but perhaps it was an earlier version? It's working now.

**Comment by xor-xor** [comment]
@mjhoy - what version of XCode / Command Line Tools do you have..? I have similar problem while installing golang (with ``nix-env -i go-1.5.1``), which boils down to the same culprit that you have mentioned:
```
cp: cannot stat '/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAttributedString.h': No such file or directory
```
(I'm also on OS X 10.9.5)

**Comment by mjhoy** [comment]
hmm. i'm not quite sure how to figure that out? my xcode version is 6.2, but that was updated more recently -- it was definitely reinstalling the command line tools that fixed my issue.

```
$ xcodebuild -version
Xcode 6.2
Build version 6C131e

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by xor-xor** [comment]
It seems that I had the same version of `Xcode` and `gcc`, but `gcc --version` gave me a somewhat different result when it comes to the `--with-gxx-include-dir` flag:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```
After reinstalling Command Line Tools with `xcode-select --install` I got it exactly the same as in your output and now problem with `CFAttributedString.h` is gone. Thanks!

I've got another problem, this time with `sysctl` (reported already as #9437), but that's a different story.

**Comment by mjhoy** [comment]
looks like you had the 10.10 sdk installed? wonder if it had to with that.

**Comment by xor-xor** [comment]
Yeah, I've noticed that too. I do not recall installing this version manually, though - I guess that some update may pulled that in or something...

**Comment by ctheune** [comment]
Interestingly I couldn't update my Command Line Tools with xcode-select --install, it wanted me to use one of the update dialogs (App Store? X-Code?). I'm currently trying to update by installing a full xcode suite.

**Comment by xor-xor** [comment]
@ctheune - you mean this dialog:
<img width="468" alt="dialog" src="https://cloud.githubusercontent.com/assets/2082842/10506775/ae006c2e-731b-11e5-9f65-302ce2806234.png">
?
If yes, then I've got it too (after typing `xcode-select --install`) - simply clicked "Install" and my CLT got updated. I guess that `xcode-select` is just some wrapper.

**Comment by ctheune** [comment]
Nah, I just got weird compile errors. I'm actually hoping my problems will go away once I profit from the pure darwin environment.
