### ISSUE TITLE
Overriding user-agent used by fetchurl

### ISSUE THREAD

**Issue by sikmir** [NixOS/nixpkgs#90034]
**Describe the bug**
I'm trying to override User-Agent header used by **fetchurl** (#17757) using:
```
curlOpts = "--user-agent 'Mac OS X'";
```
That leads to:
```
curl: (28) Resolving timed out after 15001 milliseconds
curl: (6) Could not resolve host: X'
curl: (22) The requested URL returned error: 404 Not Found
```
That's caused by whitespaces in the 'Mac OS X' string, otherwise it works correctly (e.g. with 'Mac_OS_X').

**Comment by lheckemann** [comment]
I'm not sure this can be worked around with the way fetchurl is currently implemented: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/builder.sh#L20

This could be avoided with the help of structuredAttrs, but that work isn't complete yet.

**Comment by gdamjan** [comment]
shouldn't be enough to just add quotes around `$curlOpts` here:

https://github.com/NixOS/nixpkgs/blob/06b27898a4563ef2e0e653fd78f76b77c31820ff/pkgs/build-support/fetchurl/builder.sh#L26

**Comment by gdamjan** [comment]
[replying to myself] obviously not. since then the two strings in `"--user-agent 'Mozilla 5.0'"` are considered a single argument given to curl :/

**Comment by sikmir** [comment]
Still important.

**Comment by dermetfan** [comment]
Probably duplicate of #41820.

**Comment by Infinisil** [comment]
Duplicate of #41820
