### ISSUE TITLE
Lock screen does not work in Gnome 3

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9006]
Pressing Ctrl+L is supposed to lock the screen. But the screen is not locked, instead this message is written to the journal:

```
gnome-session[717]: (gnome-settings-daemon:734): media-keys-plugin-WARNING **: Couldn't lock screen: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```

(For as long as I've been using Gnome 3 on NixOS, this has not been working.)

**Comment by geerds** [comment]
Works for me. Do you use GDM?

**Comment by bjornfor** [comment]
Hm, I think I've never tried GDM. (I think it was added some time after basic Gnome3 desktop support was in place.) Now I'm using displayManager.auto, and before that it was displayManager.lightdm.

**Comment by geerds** [comment]
http://unix.stackexchange.com/questions/86221/how-can-i-lock-my-screen-in-gnome-3-8-without-gdm:

> Starting in Gnome Shell 3.8 (included in Fedora 19), gnome-screensaver support has been dropped completely. This was done for three reasons: reduced code complexity coupled with the fact that the screensaver is seen as an unneeded feature, and the fact that the eventual move to Wayland will require screensaver, locking, etc. support to be in the compositor.

> So the only Gnome-integrated way of locking the screen is to have GDM running, which will respond to a dbus message telling it to lock the screen. Other display managers (such as XDM) have not been designed to respond to this dbus message, and so the screen cannot be locked.

**Comment by bjornfor** [comment]
Thanks. Then I'll switch to GDM :-)

**Comment by geerds** [comment]
no problem :)

**Comment by falsifian** [comment]
[The NixOS manual currently says "GDM is very experimental and may render system unusable."](https://nixos.org/nixos/manual/options.html) Is this warning still warranted?

**Comment by lethalman** [comment]
@falsifian I'm using it since the first version in nixos. It works quite well, but I never tested it outside of gnome. So we can change the text to something that says it may not work with other desktops.

**Comment by falsifian** [comment]
Thanks @lethalman. Please check my phrasing in #10955.
