### ISSUE TITLE
perlPackages.ExtUtilsPkgConfig is broken on master

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#90084]
**Describe the bug**

**To Reproduce**
1. `nix-build -A perlPackages.ExtUtilsPkgConfig`

This is a bit annoying, as `perlPackages.ExtUtilsPkgConfig` -> `rxvt-unicode-plugins.bidi` -> `rxvt-unicode`.

**Comment by rnhmjoj** [comment]
Uhm, It looks like it's also a problem for i3 users.
I'm not a perl programmer so I don't think I can do much to fix the package.
For rxvt-unicode, you can temporarily remove bidi from your plugins, see the [manual](https://nixos.org/nixpkgs/manual/#sec-urxvt-conf).

**Comment by noneucat** [comment]
Looks like some tests are failing for `perlPackages.ExtUtilsPkgConfig`. Temporary workaround is to turn off tests for the package.

**Comment by luc65r** [comment]
It is expecting `test_glib-2.0.pc` in `PKG_CONFIG_PATH`, but `glib` doesn't seem to provide it, so I have no idea what should provide it...

**Comment by flokli** [comment]
Bisecting showed this to be broken by c71ab32a678a98ce1ec069956bc55d6ea606f55c.

@Ericson2314, can you take a look?

**Comment by Ericson2314** [comment]
Looking
