### ISSUE TITLE
Git tags for NixOS releases

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9009]
I propose that when NixOS releases are made, an *annotated git tag* is made. Simply ```git tag -a -m "Release X.Y" vX.Y [commit]```. Of course, if you want to make it also *signed*, be my guest :-)

Git tags should solve this (IMHO) unfortunate situation:

```
$ cd nixpkgs
$ git describe 
fatal: No annotated tags can describe '1bb59f2c571fa5ab9c1718162ea958ab30a959c5'.
However, there were unannotated tags: try --tags.
$ git describe --tags
last-glibc-2.13-41859-g1bb59f2
```

For the last couple of releases, @edolstra has implemented logic on the release branches to embed the "number of commits since release" into the NixOS version number (```nixos-version```, ```/etc/os-release```). With a git tag, ```git describe``` in a nixpkgs git tree would also give this info "for free".

**Comment by peti** [comment]
I completely agree -- I'd like to have a tag for branch points, too. Doesn't cost anything, but it provides nicer `git describe` output.

**Comment by peti** [comment]
One problem I see is that people may be mislead into thinking that the tag denotes a particular release version of Nixpkgs, when in fact it's just the commit where the release and master began to diverge. Not sure how to convey that information properly ...

**Comment by vcunat** [comment]
@peti: sounds like you just want to use `git describe --all --first-parent`. Example in my case:
```
$ git co master^ && git describe --all --first-parent
remotes/ch/nixos-unstable-461-g2f97de9
```

**Comment by domenkozar** [comment]
I don't see a reason why we wouldn't create a tag. I think we should clear the current ones, at least releases published on github though.

**Comment by domenkozar** [comment]
Done

**Comment by peti** [comment]
@domenkozar, @bjornfor's description in https://github.com/NixOS/nixpkgs/commit/f8785253d76b2d8f7d984dde4245e4813e7f1057#commitcomment-13044824 made a lot of sense. Why didn't you create the tag the way he described?

**Comment by peti** [comment]
Also, the current `15.09` tag isn't visible from `master`, i.e. `git describe` gives no useful result on the `master` branch. This would be better if we'd tag the branching point, as described in https://github.com/NixOS/nixpkgs/commit/f8785253d76b2d8f7d984dde4245e4813e7f1057#commitcomment-13044824.

**Comment by bjornfor** [comment]
Just to clear up a thing here.

I'm not generally in favor of tagging the branch split with the final release tag, because it _isn't_ the final release point. (We could of course create an -rcX tag there, but that's a different thing and something that can be discussed later.) What I wanted to point out in https://github.com/NixOS/nixpkgs/commit/f8785253d76b2d8f7d984dde4245e4813e7f1057#commitcomment-13044824 was that "nixos-version" already indicated that the release had happened (that's the root of the issue), and that "git describe" should align with "nixos-version".

So now that the tag has been made, do we update "nixpkgs.revCount - 67824" to correspond with the tag? It's a bit ugly to reset the nixos-version number like that, but isn't it better than having the discrepancy?

**Comment by bjornfor** [comment]
@peti: Yes, it'd be nice to have "git describe" on master too, but I'm not sure the best way to do it.

1. make the final release on master (stabilize master, tag and _then_ create release-X branch)
2. create release branch, stabilize it for a while, but then tag back-in-time at the branch point (feels like cheating/lying to me :-D)
3. merge the release tag from the stable branch into master branch. (By the speed of which master diverges from stable, this will create so many conflicts that it's impractical. I just did a test...)

Hm, now that I think about it, we're talking about two different branches here, with different (recent) histories. Because the master branch technically isn't based off of the latest release (at least not the _release tag_ point), I'm not sure what kind of tag "git describe" on master really should find...? (Unless we change how we handle the release, ref. above list.)

**Comment by peti** [comment]
Personally, I don't care whether that `git describe` output has some super profound meaning or not. I just want the branching point tagged so that `git describe` gives me *some* notion of how many commits have occurred since the last release. I realize that this number is no accurate measure for anything, really, but I'd still like to have it.

We could tag the branch point with some other name, like `15.09-split-off` or maybe `15.09.x`.

**Comment by domenkozar** [comment]
What about `15.09-beta` when we branch off and `15.09` once it's released?

**Comment by peti** [comment]
Sounds good to me, too.

**Comment by bjornfor** [comment]
@domenkozar: Sounds fine.

**Comment by domenkozar** [comment]
now documented in #4442, thanks!

**Comment by bjornfor** [comment]
@domenkozar: Since you are the release manager, would you mind creating the "15.09-beta" tag?

I believe this is the commit to tag:

```
$ git merge-base origin/release-15.09 origin/master
977731f6c2227bc48ff2f9f628a30e3e38e09b4b
```

**Comment by domenkozar** [comment]
Done

**Comment by bjornfor** [comment]
@domenkozar: Thanks.
