### ISSUE TITLE
nixpkgs-unstable fails on Hydra because of `mariadb`

### ISSUE THREAD

**Issue by GuillaumeDesforges** [NixOS/nixpkgs#90134]
**Describe the bug**
All last builds on Hydra have failed because of `mariadb` (top level package).

E.g. https://hydra.nixos.org/build/121987551

Nr | What | Duration | Machine | Status
-- | -- | -- | -- | --
1 | Build of /nix/store/cpd44xn7kqjm88nmd7bh1b6jj4zbrb17-mariadb-server-10.4.13-man,/nix/store/n2nvzbpclai3jwfnzvz7wf8d27anmsjs-mariadb-server-10.4.13 | n/a | n/a | Cached failure (log, raw, tail) (propagated from build 121469753)

First broken build 2020-06-05 19:14:56: https://hydra.nixos.org/build/121385458

Nr | What | Duration | Machine | Status
-- | -- | -- | -- | --
1 | Build of /nix/store/gid5m5kxdh4q3mv8ar2a7l4wgr35g512-mariadb-server-10.4.13-man,/nix/store/8ksp3vsqycq52vrjx527qijbsbxlkzlk-mariadb-server-10.4.13 | n/a | mac2-guest | Failed (log, raw, tail) (propagated from build 121385505)

Log: https://hydra.nixos.org/build/121385458/nixlog/1

```
...
-- Installing: /nix/store/8ksp3vsqycq52vrjx527qijbsbxlkzlk-mariadb-server-10.4.13/lib/pkgconfig/mariadb.pc
-- Installing: /nix/store/8ksp3vsqycq52vrjx527qijbsbxlkzlk-mariadb-server-10.4.13/share/aclocal/mysql.m4
-- Installing: /nix/store/8ksp3vsqycq52vrjx527qijbsbxlkzlk-mariadb-server-10.4.13/share/doc/mysql/mysql.server
mv: cannot stat '/nix/store/8ksp3vsqycq52vrjx527qijbsbxlkzlk-mariadb-server-10.4.13/OFF/suite/plugins/pam/pam_mariadb_mtr.so': No such file or directory
builder for '/nix/store/qm5xwgfb5cr1jw2zsiryp997czs8ja21-mariadb-server-10.4.13.drv' failed with exit code 1
```

**To Reproduce**
I can't reproduce the issue locally though, `nix-build . -A mariadb` does compile.

**Expected behavior**
Hydra job should not fail on mariadb.

**Notify maintainers**

@thoughtpolice

**Metadata**
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(theo): `"home-manager"`
 - channels(root): `"nixos-20.09pre228622.029a5de0839"`
 - channels(arsleust): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
Reproduction: are you sure you tried it on darwin?  (That's what fails.)

**Comment by FRidh** [comment]
Probably caused by a1ec0288122ab8e1ebcf800a0c4fadcf51c87414, Darwin doesn't have .so 's right? cc @Izorkin
