### ISSUE TITLE
nixos/home-assistant: test failure

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#90149]
```
hass # Connection to localhost 8123 port [tcp/*] succeeded!
(11.48 seconds)
hass: must succeed: curl --fail http://localhost:8123/lovelace
(0.07 seconds)
hass: must succeed: curl --fail -H 'x-ha-access: some_secret' http://localhost:8123/api/
hass # [   25.987891] hass[751]: 2020-06-11 14:06:25 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 127.0.0.1
hass # curl: (22) The requested URL returned error: 401 Unauthorized
hass: output: 
Test "Check that Home Assistant's web interface and API can be reached" failed with error: "command `curl --fail -H 'x-ha-access: some_secret' http://localhost:8123/api/` failed (exit code 22)"
```

**Comment by dotlambda** [comment]
I tried adding

    with subtest("Complete Home Assistant onboarding"):
        hass.succeed(
            "curl http://localhost:8123/api/onboarding/users --data-binary "
            """'{"client_id":"http://localhost:8123/","name":"user","username":"user","password":"pass","language":"en"}'"""
        )
        hass.succeed("curl http://localhost:8123/api/onboarding/core_config")
        hass.succeed("curl http://localhost:8123/api/onboarding/integration")

and configuring a `trusted_networks` auth provider without success.

**Comment by Mic92** [comment]
Onboarding had at least three phases if I remember correctly.

**Comment by dotlambda** [comment]
Yes: users, core_config and integration.
