### ISSUE TITLE
wicd doesn't work on unstable

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#9014]
Hi.

I'm on 6ad8fab at the moment (which was unstable from a few days ago), because on newer versions of the unstable channel, `wicd` doesn't work anymore. I'm sorry I cannot investigate further at this point.

**Comment by matthiasbeyer** [comment]
**CC** service author @edolstra 
**CC** Package maintainers @roconnor

**Comment by matthiasbeyer** [comment]
It actually works "a bit" - In the GTK interface it fails connecting. It says:

* Connecting
* Not connected

(or what the actual terms are) But afterwards I am connected.

**Comment by roconnor** [comment]
I'm afraid I haven't actually used wicd in many years. :(

**Comment by matthiasbeyer** [comment]
@roconnor I'm not using wicd since this issue came up. This is still open so others can respond to that.

**Comment by grahamc** [comment]
Is wicd still broken?
