### ISSUE TITLE
"systemctl reboot" doesn't give programs a chance to ask to save

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#90155]
**Describe the bug**
When I run ''systemctl reboot`` I expect any programs with open files to ask to save.
This doesn't happen, instead the system reboots immediately.
I also tried ``systemctl start reboot.target`` and ``shutdown -r now``, all with the same result.

When I open a new file in emacs, change it but don't save it, emacs will warn me when I try to shut the program down, asking to save.

**To Reproduce**
1. create a file in your $EDITOR
2. change it, but don't save it
3. run ``'systemctl reboot``

**Expected behavior**
The system does not yet shutdown.
$EDITOR asks if I want to save my file.

**Actual behavior**
The system shuts down immediately.

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.6.14-rt7, NixOS, 20.09.git.24285cf64fc (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.5`
 - channels(bart): `""`
 - channels(root): `"nixos-20.09pre228204.467ce5a9f45, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by matthewbauer** [comment]
I think this is going to depend on what DE you use. Systemd will send a SIGINT to the system processes including display-manager.service. It's up to display-manager to handle exiting your user programs.

I've actually hit a similar but slightly different issue in SDDM/Plasma5 where `systemctl reboot` takes too long. Systemd sees that there are some programs still running under the user and waits for them to quit. Somehow, the display-manager exits without killing those programs. Eventually systemd does reboot, but you have to wait for the 1:30m timeout.

**Comment by magnetophon** [comment]
@matthewbauer Thanks. That's helps me a lot.

For anyone finding this issue and looking for a solution in a WM, [this script](https://github.com/5hir0kur0/dotfiles/blob/master/scripts/.local/bin/exit.sh) seems to be really nice, though I haven't got it fully working yet.
