### ISSUE TITLE
p11-kit binaries are in p11-kit.dev

### ISSUE THREAD

**Issue by Habbie** [NixOS/nixpkgs#90156]
**Describe the bug**
`nix run p11-kit` does not provide the `p11-kit` binary, while I would expect it to.

**To Reproduce**
1. `nix run p11-kit`
2. note `/nix/store/g42ihp14dd8hz4lmp0kysgfd16yqldry-p11-kit-0.23.20/bin` in `$PATH`
3. `ls: cannot access '/nix/store/g42ihp14dd8hz4lmp0kysgfd16yqldry-p11-kit-0.23.20/bin': No such file or directory`

**Expected behavior**
`p11-kit` (and `trust`) are installed for operator usage of p11-kit.

**Screenshots**
See step 3.

**Additional context**
It turns out the binaries are present when I do `nix run p11-kit.dev`.

Debian ships the binaries as part of the base non-dev package. RHEL/CentOS ship the `p11-kit` binary as part of `p11-kit` and have `trust` separated out into `p11-kit-trust`.

**Notify maintainers**
(based on git history, there is no meta.maintainers for p11-kit)
@worldofpeace @hedning 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.0-0.bpo.2-amd64, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(peter): `"nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/home/peter/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by matthewbauer** [comment]
p11-kit is a library as well, so it makes sense to have headers, library, and binaries in separate outputs.  I think we can fixed this by setting:

```
outputs = [ "bin" "out" "dev" ];
```

in the derivation.

**Comment by worldofpeace** [comment]
If we do this we need to fix it in flatpak's patch to hardcode the path to the p11-kit binary.

**Comment by siraben** [comment]
Any updates on this?
