### ISSUE TITLE
EmacsWithPackages' wrapper.nix should take an arguments parameter for emacs byte compilation

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#90169]
So, for example, the packages can be compiled natively with the native-comp branch, rather than just byte compilation.

**Comment by adisbladis** [comment]
@spacekitteh Is this issue still valid given that native-comp now has options for this exact case?

**Comment by spacekitteh** [comment]
I'm not sure. How can it be used from Nix?

**Comment by adisbladis** [comment]
It's already being used since https://github.com/NixOS/nixpkgs/pull/94637

**Comment by bhipple** [comment]
Seems like this issue can be closed; if I'm off-base feel free to re-open.
