### ISSUE TITLE
Qt5 TLS is not packaged properly

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#9018]
See [this comment](https://github.com/NixOS/nixpkgs/commit/c61d048427719d6e0c131f58825331df0a9d4ccc#commitcomment-12379971). Quassel cannot detect Qt5's TLS module for some reason.

**Comment by wkennington** [comment]
Strange, it looks like this is working now in master as of 2+ days ago. http://hydra.nixos.org/build/24040627/log/raw

**Comment by ttuegel** [comment]
That's what I saw too, when I was rebuilding Quassel with KF5 support. I'll try out the build on my server tonight and if all goes well, I'll switch back to the Qt 5 build for the NixOS module.

**Comment by vcunat** [comment]
Ping.

**Comment by wkennington** [comment]
This is fixed. Closed. (I hope that works from my phone)
