### ISSUE TITLE
nixos/systemd: missing systemd unit tmp.mount

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#90188]
**Describe the bug**
`tmp.mount` appears in the result of `systemctl list-units --state not-found`. See #88597 for context.

**Expected behavior**
`tmp.mount` should not appear in the result of `systemctl list-units --state not-found`.

**Additional context**
- `basic.target` has a reference on `tmp.mount` (see `systemctl cat basic.target`).
- `basic.target` is included in: https://github.com/NixOS/nixpkgs/blob/e9a0ec8142c366777792d12e97798eb81ade0de7/nixos/modules/system/boot/systemd.nix#L16
- should [nixpkgs/nixos/modules/system/boot/systemd.nix](https://github.com/NixOS/nixpkgs/blob/e9a0ec8142c366777792d12e97798eb81ade0de7/nixos/modules/system/boot/systemd.nix) also include `tmp.mount`?

**Notify maintainers**
@flokli 

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- nixos/systemd
```

**Comment by flokli** [comment]
It seems the upstream `basic.target` already includes a `Wants=tmp.mount`:

https://github.com/systemd/systemd/blob/master/units/basic.target#L22

The line below explicitly says "this should not be considered an error", so it seems `tmp.mount` could be a missing unit on other distros as well, and should be ignored - meaning it's not a nixpkgs issue.

Let's carry the more general discussion over to https://github.com/NixOS/nixpkgs/issues/88597#issuecomment-643605108.
