### ISSUE TITLE
chromium: deb is out of date and gives 404 not found

### ISSUE THREAD

**Issue by CestDiego** [NixOS/nixpkgs#9021]
[![alt](https://i.imgur.com/KZyKnmC.png)](https://i.imgur.com/KZyKnmC.png)

with 
```
    nixpkgs.config = {
        chromium = {
            enablePepperFlash = true;
            enablePepperPDF = true;
        };
    };
```

This makes it download the google-chrome-stable deb file but the path is wrong..as in the AUR PKGBUILD https://aur.archlinux.org/packages/go/google-chrome/PKGBUILD they use
```
https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
```

And the other mirrors simply don't work either

**Comment by aszlig** [comment]
Okay, going to add a few more mirrors. I initially used http://95.31.35.30/ and http://mirror.pcbeta.com/ not only because the "current" URL isn't stable but also because they remove the older `.deb`s from the upstream location whenever there is a new version available.

**Comment by aszlig** [comment]
Hm, http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_44.0.2403.89-1_amd64.deb seems to exist.

**Comment by CestDiego** [comment]
not from here :( https://i.imgur.com/X9TJPQL.png

**Comment by aszlig** [comment]
@CestDiego: Does http://repo.fdzh.org/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_44.0.2403.89-1_amd64.deb work for you?

**Comment by CestDiego** [comment]
it does

**Comment by aszlig** [comment]
Thanks, adding that mirror.

**Comment by CestDiego** [comment]
why does the one from google fail though?

**Comment by aszlig** [comment]
As I said before: The upstream file is deleted from the repository as soon as there is an updated version.

**Comment by CestDiego** [comment]
oh that makes sense

**Comment by CestDiego** [comment]
Thanks @aszlig :)

**Comment by aszlig** [comment]
@CestDiego: From which country are you trying to get that `.deb`?

**Comment by CestDiego** [comment]
US
