### ISSUE TITLE
CSGO and other 3d games broken in Steam by commit ...

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#90229]
This commit breaks all my 3d games in Steam. They start, they react, but graphics is terribly broken - nothing can be seen other than pink color all over sreen with some artifacts. Reverting this commit fixes the issue.

I have Intel integrated card

00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

Commit 593c28b88617241a5ca69986a6aa5f57581e247a
steam: switch to the newer steam-runtime packaging
    
    Valve has started releasing tarballs of the steam runtime. It seems a
    lot easier to download and extract a single tarball than to download a
    buncha debs, extract them, and splat em around a bit.
    
    Let's just use the runtime they build. It's a buncha random binary
    packages anyway.
    
    Also, the download url for their debs broke, so there's that too.

**Comment by tex** [comment]
@euank Ping.

**Comment by killercup** [comment]
I have seen graphics issues on an AMD card (5700XT) as well. Thanks for the hint about reverting the commit.

**Comment by euank** [comment]
Thanks for the ping! I'll dig into this a little this weekend and see if I can understand what's going on, and if I can't figure it out fairly quickly, we can revert that.

**Comment by euank** [comment]
I can't reproduce this, so it's going to be tricky to debug by myself.
I've got an nvidia card in my machine.

However, it's easy to build the runtime directory from before and after that change and diff it, which is what I should have done in that PR (oops).

There's a lot of differences that look quite suspicious. In fact, it looks like I messed up and grabbed the wrong upstream runtime tarball entirely.
The main difference is that previously, there was `/usr`, and the new runtime... yeah, it doesn't have a `/usr` folder at all. I'm surprised it worked at all.

If switching to the correct runtime tarball fixes it with no additional work, that would be great. As above, I can't repro these issues locally, so I'll need help to see if that fixes it.

A commit switching to what I _think_ is the right artifact is here: https://github.com/euank/nixpkgs/commit/71b8215b0c777dca279e25c396de01a1052f3d08

After that change, there's far fewer differences between the old working setup and the new runtime folder.
The main one that looks like it may be of note is:

```
Only in old/usr/lib/x86_64-linux-gnu/dri: i915_dri.so
Only in old/usr/lib/x86_64-linux-gnu/dri: nouveau_dri.so
Only in old/usr/lib/x86_64-linux-gnu/dri: nouveau_vieux_dri.so
...
Only in old/usr/lib/x86_64-linux-gnu: mesa
Only in old/usr/lib/x86_64-linux-gnu: xorg
```

However, other than those, it's a lot more similar!

To test that commit locally, you can close steam and then run the following:

```
$ nix-build https://github.com/euank/nixpkgs/archive/71b8215b0c777dca279e25c396de01a1052f3d08.tar.gz -A steam -o test-steam
$ ./test-steam/bin/steam
# See if everything works
```

I'm not certain that'll fix it. If it doesn't, I'll make a PR to revert my previous change, and then figure out how to properly use valve's packaged runtime separately.

Can one of you check if the above commit does fix the issue you're running into? If not, more detailed information would help me dig into this further, most notably whether there's any debug output if you run the game from a terminal (I think `steam-run` lets you do that?)

**Comment by tex** [comment]
I did what you asked and it WORKS!!!

**Comment by euank** [comment]
Thanks for testing that, @tex, I opened a PR with the change over in #90286.

**Comment by killercup** [comment]
Can confirm this works with my AMD card as well. Thanks a lot!

**Comment by danieldk** [comment]
Thanks @euank ! This fixes Steam games on my Intel GPU as well!

**Comment by diamondburned** [comment]
I also have this bug on my AMD 2400G (so an APU). This only happened in Source games such as CSGO or TF2. `test-steam` fixed this bug.

**Comment by jul1u5** [comment]
Although building steam from @euank's repo works perfectly. For some reason, steam is still broken for me on nixos-unstable. My `configuration.nix` looks something like this:
```
environment.systemPackages = [ pkgs.steam ];
```

Output from `nix-info`:
```
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.7, channels(julius): "", channels(root): "nixos-20.09pre234194.8d05772134f", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by euank** [comment]
@jul1u5 Just to double check, you're sure there's not some other version in your path (i.e. from `nix-env -i` or such in the past)?

The nix channel commit you're on (8d05772134f) should include all relevant changes there, so it seems mostly likely there's either a different version in your path, or something weird going on.

**Comment by jul1u5** [comment]
Yeah, sorry. The issue was with `nix-env`. I've somehow completely forgot to check if steam was installed there.

**Comment by AleXoundOS** [comment]
_`nix-env` often comes up in issues and confuses people_.
