### ISSUE TITLE
Kodi cannot be built with enableControllers

### ISSUE THREAD

**Issue by tyrion** [NixOS/nixpkgs#90235]
**Describe the bug**
Kodi does not build with `enableControllers = true`

```
building '/nix/store/3r83h8vp2lc4zhgxwn1jsin4bkphr4dg-kodi-with-plugins-18.6.drv'...
collision between `/nix/store/65i43az84szd6yqsnc93k47vg2avvs6r-kodi-plugin-game-controller-default-1.0.3/share/kodi/addons/game.controller.default/resources/layout.png' and `/nix/store/zzk8am4j09lf4wmi1nvvr1yslixadz32-kodi-18.6/share/kodi/addons/game.controller.default/resources/layout.png'
builder for '/nix/store/3r83h8vp2lc4zhgxwn1jsin4bkphr4dg-kodi-with-plugins-18.6.drv' failed with exit code 25
```

**To Reproduce**

```
nixpkgs.config.kodi.enableControllers = true;
environment.systemPackages = [ ... pkgs.kodi ... ];
```

**Additional context**
Same error both on 20.03 and on unstable

**Notify maintainers**
@domenkozar @titanous @edwtjo @peterhoeg  @sephalon 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.2133.8946799e079 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(tyrion): `""`
 - channels(root): `"unstable-20.09pre228622.029a5de0839, nixos-20.03.2133.8946799e079, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tyrion** [comment]
Apparently the `default` and `snes` game controllers are installed by default, so they cause a conflict when enabled again. Since I am not interested in other controllers than the default, I am simply disabling `enableControllers`.

I think a quick fix would be to remove `default` and `snes` from the controller installed by `enableControllers`.

**Comment by aanderse** [comment]
I'll fix this before the next release. Hopefully sooner.

**Comment by aanderse** [comment]
I'm getting around to this... soon.
