### ISSUE TITLE
Packaging requests: scenebuilder

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#90243]
**Project description**
_Scene Builder is a drag n drop layout tool for designing JavaFX application user interfaces._

It is now distributed under 3-clause BSD License, without the need of registration or manually accept EULAs.
There was a pull request when it had not been open-sourced (#51564). Now it would be easier to package.

**Metadata**

* homepage URL: https://gluonhq.com//products/scene-builder/
* source URL: https://github.com/NixOS/nixpkgs/pull/51564
* license: bsd3
* platforms: unix

**Comment by ShamrockLee** [comment]
I am still looking forward to this one.

**Comment by wirew0rm** [comment]
@ShamrockLee If you're still interested, you could build scenebuilder from my PR linked above, test if it works for you or if I missed anything and report your results there.
