### ISSUE TITLE
haskellPackages.path-io: Instability in cabal2nix hash?

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#90255]
**Describe the bug**

The hydra built for `haskellPackages.path-io` fails with a hash mismatch for the sources.

https://hydra.nixos.org/build/121987969/nixlog/1

@peti How can something like that happen? Does that automatically get fixed by a hackage2nix update?

**Comment by maralorn** [comment]
I just realized this also the reason for the build failure that we have on stack right now. (see https://hydra.nixos.org/build/122143838)
So fixing this would be a really good idea.

**Comment by cdepillabout** [comment]
I'm not sure what could be going on here, but there is a weird line in the log:

```
trying http://hackage.haskell.org/package/path-io-1.6.0/revision/2.cabal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2668    0  2668    0     0   3822      0 --:--:-- --:--:-- --:--:--  3816
(23) Failed writing body
fixed-output derivation produced path '/nix/store/89s969r5mn9w7vmy39z8cpm8ckl3c73y-path-io-1.6.0-r2.cabal' with sha256 hash '0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73' instead of the expected hash '1x52j77g075k79c7fma0khhbcpja88wylgllnky6q7nccwazm2c2'
```

The line `(23) Failed writing body` is somewhat worrying.

Maybe someone like @peti or @domenkozar could restart the build at https://hydra.nixos.org/build/121987969 for us?

**Comment by maralorn** [comment]
Look I found another one: https://hydra.nixos.org/build/121987976/nixlog/1

Note how it fails with the same hash. I guess 0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73 is the empty file or something like that?

**Comment by maralorn** [comment]
Also, they are both on the same build machine. At this point I don't believe this has anything to do with Haskell.^^

**Comment by maralorn** [comment]
@andir has triggered a rebuilt of this package and all dependencies. Thanks!

As a result the stack  build has now succeeded.
