### ISSUE TITLE
openssh: upgrade to version 8.3

### ISSUE THREAD

**Issue by j4m3s-s** [NixOS/nixpkgs#90262]
**Project description**
OpenSSH is the premier connectivity tool for remote login with the SSH protocol.

**Metadata**

* homepage URL: openssh.com

**Comment by prusnak** [comment]
FIxed by https://github.com/NixOS/nixpkgs/pull/90264

**Comment by j4m3s-s** [comment]
Oh indeed. Didn't show up when I searched.
