### ISSUE TITLE
fonts.fonts requires a reboot

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9027]
When I added japanese fonts to `fonts.fonts` it took a reboot to display the new glyphs (instead of just boxes). An xserver restart might be enough, though I didn’t try that.

Update: The specific program was chromium, I don’t know which other programs were affected.

**Comment by danbst** [comment]
xserver is not restarted by default under changes, and I think this is right

what is wrong, is that nothing is echo-ed into console when some user actions are required after `nixos-rebuild`. There are "preactions", like "download this file yourself because it is non-free", but no "postactions"

though these are thoughts only on "An xserver restart might be enough" part, not on bug itself

**Comment by edolstra** [comment]
Surely this is only the case for server-side font rendering, which hardly any modern application uses anymore?

Also, `nixos-rebuild` does show a warning:
```
NOT restarting the following changed units: display-manager.service
```

However, it would be good if such changes took effect on X logout/login (rather than requiring a `systemctl restart display-manager`).

**Comment by danbst** [comment]
@edolstra as a beginner, I read 

```
NOT restarting the following changed units: display-manager.service
```
as 
```
Guy, I do some magic, and for that magic I require display-manager.service NOT to restart. Don't bother me on that stuff
```

Would be better:
```
Some services are not auto restarted. You can restart them manually with 'systemctl restart service'
- changed attributes <list of changed attributes> may require display-manager.service restart
- changed attributes <list of changed attributes> require postgresql.service restart
...
```

**Comment by vcunat** [comment]
I'm fairly certain display-manager is a red herring. Nowadays, fonts are provided by `/etc/fonts`, which is set up in our default to be re-scanned every 30 seconds. (When FcFontSetList is called; beware of applications caching such results.) Running `fc-list` might be a good way to find out the status.

**Comment by vcunat** [comment]
@danbst: there may be other things changed than just attributes (e.g. implementation). Note that restarting display-manager would kill *all* graphical programs and force you to re-log, which is why we don't do it by default.

**Comment by Profpatsch** [comment]
For Chromium it didn’t pick up the changes.

No idea how font configuration works on Linux, so I’m not much of help with the internals.

**Comment by Profpatsch** [comment]
Can’t reproduce anymore.
