### ISSUE TITLE
Package Request: UtahFS

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#90338]
**Project description**
UtahFS is a state-of-the art encrypted storage solution, meant to be similar to Dropbox. It has a FUSE binding that creates a synthetic drive on the user's computer that they can interact with like an external hard-drive. Files stored in the drive are uploaded to a cloud storage provider, which means the drive will never run out of space and minimizes the likelihood of any files being lost. However the files are encrypted such that the cloud storage provider knows almost nothing about what's being stored.

Completely written in *Go*.

**Metadata**

* homepage URL: https://github.com/cloudflare/utahfs
* source URL: https://github.com/cloudflare/utahfs
* license: bsd
* platforms: unix

**Comment by snglth** [comment]
Looks interesting, but we gotta wait for a official release/git tag/
