### ISSUE TITLE
nixos/stage-1: initialRamdiskSecretAppender does not respect boot.initrd.compressor

### ISSUE THREAD

**Issue by S-NA** [NixOS/nixpkgs#90352]
**Describe the bug**
It assumes the compressor is always gzip.
https://github.com/NixOS/nixpkgs/blob/c6c5c927ec48ec4c3fedaafc50bb9234abbe2039/nixos/modules/system/boot/stage-1.nix#L377

**To Reproduce**
1.
```
boot.initrd.compressor = "${pkgs.lzop}/bin/lzop -9";
boot.initrd.secrets = { "/key.bin" = /path/to/something; };
```
2. `nixos-rebuild switch`
3. `systemctl reboot`

Which results in a kernel panic, unable to mount root fs error.

**Expected behavior**
No kernel panic, it boots normally.

**Additional context**
I found this when moving to `boot.initrd.secrets` from removal of `boot.loader.grub.extraInitrd` in #85418. Digging into the files in `/boot/kernels` I noticed that the file suffixed with `-secrets` was gzipped. Decompressing the (`gzip -d`) file and recompressing it using `lzop -9` allowed me to then boot back into my machine.

**Notify maintainers**

According to `git blame`:
@shlevy 

People who might have some related interest:
@lopsided98 @Kloenk @emilazy @Mic92 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.2-ck1, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre228622.029a5de0839"`
 - channels(sna): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Mic92** [comment]
Gzip should be replaced by `${config.boot.initrd.compressor}` in this line.

**Comment by S-NA** [comment]
It probably would be a good idea to handle the non-determinism introduced by the host filesystem when using find.

https://github.com/NixOS/nixpkgs/blob/e36c7e61c39bb78ab6bf0b0894ed418af4ab5f03/pkgs/build-support/kernel/make-initrd.sh#L43

Seems to do that with `find` piped to `sort` but it also has a lot more arguments to `cpio` as well.

**Comment by Mic92** [comment]
Do you mind open a pull request for this?

**Comment by lopsided98** [comment]
See #92964

**Comment by S-NA** [comment]
@Mic92 have you had a chance to see the pull request mentioned above? It works for me and I have been using it regularly for awhile now.
