### ISSUE TITLE
clickhouse: upgrade to latest version

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixpkgs#90354]
This is blocking an upgrade of `capnproto`:
https://github.com/NixOS/nixpkgs/pull/86809

It would be nice to upgrade to a newer stable release:
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md
https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/clickhouse/default.nix

CC @orivej

**Comment by Ma27** [comment]
Should be fixed in #92694
