### ISSUE TITLE
caprine

### ISSUE THREAD

**Issue by plabadens** [NixOS/nixpkgs#90375]
**Project description**
Caprine is an unofficial and privacy-focused Facebook Messenger app with many useful features.

**Metadata**
* homepage URL: <https://sindresorhus.com/caprine/>
* source URL: <https://github.com/sindresorhus/caprine>
* license: mit
* platforms: linux, darwin

**Comment by michielboekhoff** [comment]
I'd love to have this, too. I tried to take a stab at it a while back (using Atom and other Electron apps as a base) but it kept core dumping. I'm going to have to give it another try soon.

**Comment by ShamrockLee** [comment]
@plabadens @michielboekhoff I have a binary package PR ( #108400 ) dangling for a long time.
You may want to take a look.
