### ISSUE TITLE
Please, update `nixos-unstable` channel, if it is possible - more frequently, so contributors can test and contribute

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#90384]
**Describe the bug**

I am for a long time can not update on the `nixos-unstable`, last one there was `keepass` inconsistent patching blocker, but I and other contributor addressed it properly.

`nixos-unstable` last updated a week ago (https://status.nixos.org/), writing basically because I wait for a release to be able to close the other Report. I am waiting from [July 3](https://github.com/NixOS/nixpkgs/pull/89393) to test it and close its according [Report](https://github.com/NixOS/nixpkgs/issues/88999). Since one should be careful with stash of all secrets, I am waiting on the properly consolidated `nixos-unstable` update to arrive.

`nixpkgs-unstable` was released recently, and `nixos-unstable` passed tests successfully recently: https://hydra.nixos.org/job/nixos/trunk-combined/tested.
Me, waiting July 3 merges not hit the channel, IDK how much checkout is older, and so contributors wait.

**Expected behavior**

Be able to update on `nixos-unstable`. I couldn't switch the revision of NixOS for quite some time.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.20, NixOS, 20.09pre214209.f098b0dd2cd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre228622.029a5de0839, unstable-20.09pre226148.0f5ce2fac0c, nixpkgs-20.09pre226586.571212eb839"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Anton-Latukha** [comment]
It belongs to `nixos-channels` repo.

**Comment by Anton-Latukha** [comment]
Reopening, since `nixos-channels` does not getting-in reports, so report belongs here.

**Comment by veprbl** [comment]
I believe, the channel should update soon.

**Comment by andersk** [comment]
It seems that recently `nixos-unstable` being blocked for weeks at a time has been the rule rather than the exception. While it’s tempting to dismiss this as a combination of unrelated bugs, maybe there’s something more fundamental we could do to reduce the impact of such bugs or facilitate faster fixes? For example, what if Hydra did an automatic `git bisect` to locate channel-blocking regressions and filed an issue cc-ing the appropriate maintainers?

**Comment by domenkozar** [comment]
status.nixos.org is broken, channels are being updated: https://channels.nixos.org/

**Comment by veprbl** [comment]
> status.nixos.org is broken, channels are being updated: https://channels.nixos.org/

It was accurate few hours ago.

The channel, indeed, advanced now. Let’s close.

**Comment by Anton-Latukha** [comment]
Why close a report when the topic of the Report was not addressed in any way?

`nixos-unstable` was last updated 8 days ago. And it was broken for me.

Why not to release the "stable" build that passed CI checks and adhere to official way of releasing `nixos-unstable`. But favor newer broken CI build in favor of previous stable checkout? And close the Report while the builds are broken?

Have I missed some logic here?

**Comment by vcunat** [comment]
> Why close a report when the topic of the Report was not addressed in any way, shape, or form?

The report (and title at that point) was about channel not being updated.  That had been fixed.

**Comment by vcunat** [comment]
Passing tests isn't the only condition.  Also all builds have to finish, which often takes more time (various non-critical aarch64 builds/tests, etc.).

> See [HowOldIs](http://howoldis.herokuapp.com/) and the [NixOS Wiki](https://nixos.wiki/wiki/Nix_channels) for information on how channel updates progress.

**Comment by Anton-Latukha** [comment]
Ok. Please, there should be some timely manner for `nixos-unstable`, I wait for changes to hit from July 3d, it soon be two weeks of just solid waiting.

If contributors at least knew the least frequency of the trickle-down of `master` into `nixos-unstable` that the process and maintainers keep - 3 days, week, two, three, month, they would know how long it can be awaited to arrive.

**Comment by vcunat** [comment]
I don't know... more Hydra power would help (more frequent evaluations, faster builds of any fixes), and more people watching the channel-critical jobs and doing whatever they need to fix them (sometimes issues are not even related to any nixpkgs commits).  I do watch the jobs relatively frequently, but my paid work isn't really related to any Nix* stuff, so for me it's just free time and I certainly can't seriously promise anything... not sure if someone else would be willing to provide such guarantees to the community for free :-)

Yes, maybe some other technical measures could be implemented to decrease the longest waits (I'm not sure), but first... it holds the same &ndash; someone has to implement them.

BTW, anyone can try newer stuff _easily_ without waiting for channels (or use the small channels) and still get all binaries that are available at that time, but I'll assume all readers of this thread already know about that...

**Comment by Anton-Latukha** [comment]
I do not demand or expect anything really, I just need to know some standard norm of the longer bound of the timeframe the `master` things arrive into `nixos-unstable` that maintainers call "at least it hit our <period> norm" , so contributors know when to check and await it.

I know, can we have some arbitrary big time period, like `nixos-unstable` is expected in 3 weeks or month.

Maybe someone or I can from `nixos-channels` figure and contribute the documentation on the frequency of `nixos-unstable` syncs to `master` checkout, going from what is real data on that. I can document that on the Wiki, but it also should be kind of at least an upstream norm before the contributor can document it to the wiki.

Thank you @vcunat, I know you are moving things in Nixpkgs already for a several years at the least.

**Comment by lheckemann** [comment]
Note also the `nixos-unstable-small` channel, which does update more frequently by having a smaller test set. Maybe that's better suited for your use case?
