### ISSUE TITLE
LSOF url is broken

### ISSUE THREAD

**Issue by curaloucura** [NixOS/nixpkgs#9043]
The current URL on nixpkgs/pkgs/development/tools/misc/lsof/default.nix is broken.  It seems the the ualberta.ca had some url updates.

Old link: ftp://sunsite.ualberta.ca/pub/Mirror/lsof/lsof_4.88.tar.bz2

I've got it working with a HTTP mirror at

http://mirrorservice.org/sites/lsof.itap.purdue.edu/pub/tools/unix/lsof/OLD/lsof_4.88.tar.bz2

**Comment by vcunat** [comment]
The point is that the mirrors are both good, but the tarball changes location because they keep the newest one on a different path than the others (add `OLD/`). Now we try both locations.
