### ISSUE TITLE
Discord fails to build on unstable

### ISSUE THREAD

**Issue by eliaslfox** [NixOS/nixpkgs#90475]
Discord fails to build on unstable

```
searching for dependencies of /nix/store/rqvq2j27zd5qbbqy5jcjxq22jq8if2yf-discord-0.0.10/opt/Discord/.Discord-wrapped
  libuuid.so.1 -> not found!
```

CC @ldesgoui @MP2E  @tadeokondrak   

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.16-hardened, NixOS, 20.09pre229574.0a146054bdf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(elf): `"nixpkgs-20.03.1619.ab3adfe1c76"`
 - channels(root): `"nixos-20.09pre229574.0a146054bdf, home-manager"`
 - nixpkgs: `/home/elf/.nix-defexpr/channels/nixpkgs`
```

```yaml
attribute: pkgs.discord
```

**Comment by iblech** [comment]
It appears that @rtldg already fixed that [yesterday](https://github.com/NixOS/nixpkgs/commit/4f7d82999145ca1d4514c3c72d510a2dbe1b5d52#diff-cbea7d49db86f0deb9f01862c30b5d6f). :-)

If you do not want to wait till the unstable channel is updated, you can use:

    nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz -p discord
