### ISSUE TITLE
Supercollider fails to build in unstable

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#9048]
after updating to commit 9d5508d85c33b8fb22d79dde6176792eac2c2696 in the unstable channel, supercollider fails to build. The only possibly relevant customization in my configuration.nix is that I have jack support enabled in pulseaudio, with

```
  hardware = {
    pulseaudio = {
      enable = true;
      package = pkgs.pulseaudioLight.override { jackaudioSupport = true; };
    };
  };
```

the build error is something to do with libsupernova and the c++ stl

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/863d426a3b8a4a56e34af3f687d18f42dad2ac44
