### ISSUE TITLE
pythonRecompileBytecodeHook regressions

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#90516]
**Describe the bug**

This hook was introduced for reproducibility in #90208.

Issues:
- some packages don't have a site-packages folder https://github.com/NixOS/nixpkgs/pull/90208#issuecomment-644051108 (`gtk-doc`)
- package may install tests that are written for Python 2 (`python2.pkgs.linecache2`). We should not install tests (https://github.com/NixOS/nixpkgs/issues/12379). A hook is ran that removes tests 3973a3c79c255db358a82f1ffc88dc2cda0f03d6. Maybe order of execution is a problem here?

Work-around for now is to disable the recompilation of reproducible bytecode by setting
```
dontUsePythonRecompileBytecode = true;
````

**Comment by FRidh** [comment]
zope-testrunner
```
pythonRecompileBytecodePhase
*** Error compiling '/nix/store/ggczy6q0ind1wkllzviil5a5n5gb6kgj-python3.8-zope.testrunner-5.1/lib/python3.8/site-packages/zope/testrunner/tests/testrunner-ex/sample2/badsyntax.py'...
  File "/nix/store/ggczy6q0ind1wkllzviil5a5n5gb6kgj-python3.8-zope.testrunner-5.1/lib/python3.8/site-packages/zope/testrunner/tests/testrunner-ex/sample2/badsyntax.py", line 16
    importx unittest
            ^
SyntaxError: invalid syntax

builder for '/nix/store/mndgcl5f2mrfvgzzfvlkk94vi1q80cca-python3.8-zope.testrunner-5.1.drv' failed with exit code 1
```
Again its the tests that are installed.

**Comment by simonchatts** [comment]
(Copying over from the wrong thread for completeness): `python3Packages.invoke`.

This package includes [vendored YAML packages for both Python 2 and 3](https://github.com/pyinvoke/invoke/tree/master/invoke/vendor), and ignores the unwanted one at build time. But `pythonRecompileBytecodePhase` hits syntax errors for the Python2 code.

**Comment by FRidh** [comment]
@simonchatts https://github.com/NixOS/nixpkgs/pull/90555

**Comment by FRidh** [comment]
Effectively reverted this hook in b7aec77a7ba690dc9643a9989ad4e38b65fee4c6 because of too many regressions. The code is still there, its just turned off.

**Comment by jonringer** [comment]
maybe in a different `python-unstable` branch, we can apply the changes. There's already a lot going on in this current `staging-next`. I think the change is fine

**Comment by jonringer** [comment]
going to close as I think this has been solved through other means, @FRidh feel free to re-open.
