### ISSUE TITLE
moreutils: Version 0.55 vanished from the mirror

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#9051]
moreutils is broken on unstable because it is not longer available through the mirror.

**CC** maintainer: @k0ral 

I will try to provide a fix.

**Comment by matthiasbeyer** [comment]
The update from https://github.com/NixOS/nixpkgs/commit/72d7e4048c62574fb4c3d9d15556b531ab5a65da might fix this.

**Comment by vcunat** [comment]
But it will disappear in future &ndash; that's how debian mirrors work.

**Comment by matthiasbeyer** [comment]
Ah, okay. 0.57 is the latest version of the package on the debian mirrors atm. I guess I will file a package update to use the git version from the upstream repository, so we do not have the hassle with the debian mirrors.

**Comment by vcunat** [comment]
From my search, git seems the only alternative, but it would be an added build-time dependency (I don't see the html git front end providing tarballs).

**Comment by matthiasbeyer** [comment]
Bah, I'm sorry it is more complicated than I thought and I do not have that much time right now, sorry. I will submit the change anyways if I get it working before my vacation.

**Comment by bjornfor** [comment]
IMHO, I think we should wait it out and see when/if the next release arrives and breaks the download. If it's seldom, what we do now is acceptable. If it's often, we might want to switch to git.

Or if there is a git -> dynamic-tarball URL (like @vcunat suggests) that'd probably be the best.

**Comment by vcunat** [comment]
No luck. http://git.kitenet.net/?p=moreutils.git;a=snapshot;h=refs/tags/0.57 shows
> 403 - Snapshots not allowed

Let's "wait it out" then.
