### ISSUE TITLE
update-luarocks-packages script changes fetch url

### ISSUE THREAD

**Issue by Pablo1107** [NixOS/nixpkgs#90532]
**Describe the bug**
When I ran `update-luarocks-packages`, the `generated-packages` which previously has `fetchurl` set to `http://luarocks.org` is changed to `mirror://luarocks`. I don't know if this is an expected behaviour or not, in case it is I would like to be explained how can I contribute a luarocks package to nixpkgs.

Also the `luv` derivation stops working on my system.

**To Reproduce**
1. Add an entry to `maintainers/scripts/luarocks-packages.csv` (optional)
2. Run `maintainers/scripts/update-luarocks-packages pkgs/development/lua-modules/generated-packages.nix`

**Expected behavior**
The `generated-packages` diff shows a new derivation for the added entry and maybe some updated derivations for some other package.

**Actual behavior**
The `generated-packages` diff shows the new derivations, but show changes for all derivations. Mainly changes urls from `http://luarocks.org` to `mirror://luarocks` and license from a block to a one-liner.

**Notify maintainers**

@teto @Shados 

**Metadata**
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.44, NixOS, 20.03.git.d4be3fdc80eM (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(pablo): `"home-manager-20.03"`
 - nixpkgs: `/home/pablo/code/nixpkgs`
```

**Comment by teto** [comment]
answering quickly but the doc https://github.com/NixOS/nixpkgs/pull/55302 got updated recently. the change to use mirror:/// is normal. When adding or updating a module, use `git add -p` to just add what you want.
`Also the luv derivation stops working on my system.` that's too vague. You may want to check out the tracker too for related issues.

**Comment by Pablo1107** [comment]
> answering quickly but the doc #55302 got updated recently. the change to use mirror:/// is normal. When adding or updating a module, use `git add -p` to just add what you want.
> `Also the luv derivation stops working on my system.` that's too vague. You may want to check out the tracker too for related issues.

Thanks for the quick reply. You're right, my description on luv stop working was too vague, as I don't use it particularly or didn't intended to update it I didn't put too much attention to it. 

Would then be ok for me too add the package I want to the `csv` and just commit the relevant diff on the `generated-packages` so it doesn't impact other packages?
