### ISSUE TITLE
redis warns about transparent huge pages support in kernel

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#90602]
**Describe the bug**

**To Reproduce**
1. Install redis via:
```
services.redis.enable = true;
services.redis.vmOverCommit = true;
```
2. Look at the `redis` log `journalctl -u redis.service` and observe:
> WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
3. reboot

**Expected behavior**
No warnings or errors in `redis` log.

**Additional context**
I thought [this](https://github.com/NixOS/nixpkgs/blob/a84b797b28eb104db758b5cb2b61ba8face6744b/nixos/modules/services/databases/redis.nix#L196) line was supposed to prevent such a warning... :thinking: 

**Notify maintainers**

ping @peti @flokli @Mic92 @maralorn  

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1589.9137f05564e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1589.9137f05564e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: redis
```

**Comment by flokli** [comment]
If the sysctl doesn't work, we can probably also put the suggested line into the `preStart` script. :thinking: 

This should be relatively easy to test, given we have a NixOS vm test :-)

**Comment by maralorn** [comment]
As long as another solution does not fail loudly in containers, i.e. reintroduce bug https://github.com/NixOS/nixpkgs/issues/71414 which we fixed by switching to sysctl. I’m game.

But my question is: Is the broken since that "fix"? Can others reproduce this issue? Or is maybe @aanderse running redis in a container where this line doesn’t take effect?

**Comment by aanderse** [comment]
I'm just running on a regular NixOS install which happens to be running on VMWare.

**Comment by aanderse** [comment]
Strange... when I add `vmOverCommit = true;` to the test I don't see the warning :thinking:
