### ISSUE TITLE
Firewall blocks internal libvirtd packets

### ISSUE THREAD

**Issue by jgeerds** [NixOS/nixpkgs#9067]
libvirtd creates a default virtual switch (called `virbr0`) with a running DHCP server for all guest VMs. Our firewall seems to block all (or DHCP specific?) packets to guest VMs because when I disable the firwall it works.

I've already put all libvirt related interfaces to `networking.firewall.trustedInterfaces` and allowed DHCP specific ports for TCP/UDP but the problem isn't solved.

Any ideas?

**Comment by geerds** [comment]
cc @wkennington @rickynils @wizeman

**Comment by globin** [comment]
Same issue as #8967, it's not specific to libvirt's dnsmasq and radvd has the same problems.

I cant make it work by disabling the firewall.

**Comment by globin** [comment]
Caused by #10101

**Comment by domenkozar** [comment]
I think we should just  set `networking.firewall.checkReversePath = false` for libvirt

**Comment by wkennington** [comment]
Thats a very unintuitive side effect of enabling libvirt

**Comment by domenkozar** [comment]
@wkennington The end result is less secure firewall. Currently the unintuitive side effect is that libvirt basically doesn't work, because DHCP server it uses won't work. We could document what people need to do, but then, why not just do it?

**Comment by makefu** [comment]
wouldn't it be possible to configure the firewall for exactly is needed, namely disabled reverse path checking on the virtual interfaces created by libvirt?

I also think that the current defaults brick the libvirt package which then results in mails like "nixnops does not work with libvirt".

Additionally i am not really sure what kind of attacks checkReversePath really protects against (or fails to protect if disabled).

**Comment by jgillich** [comment]
As mentioned in #10101, the kernel exposes reverse path checking per interface via sysctl. What we currently have is a netfilter rule that applies to all interface, I think we should make it a per-interface configuration via the sysctl option.

**Comment by domenkozar** [comment]
Relevant: https://github.com/NixOS/nixops/issues/500

**Comment by Profpatsch** [comment]
(triage) any progress?

**Comment by c0bw3b** [comment]
Should be good since #17325
