### ISSUE TITLE
Spacemacs packaging (incl. layer support)

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9068]
It would be very nice to have support for spacemacs in nixpkgs.

I wrote up a few thoughts about packaging it: https://gist.github.com/Profpatsch/ddff34d495f57b505a6b

**Comment by devhell** [comment]
:+1:

**Comment by puffnfresh** [comment]
Would love to have this!

**Comment by robbinch** [comment]
Good idea!

**Comment by CestDiego** [comment]
have you guys had succes using spacemacs with multiple layers?

**Comment by Profpatsch** [comment]
A layer would need to bring its own dependencies, yes.
In the end Emacs needs to see
1. the layers
2. the external program dependencies

I’m pretty sure emacs packages in nixpkgs already do a part of the wrapping, so we need to package each layer to use the right emacs packages and then do any wrapping of stuff the spacemacs layer adds.

The spacemacs derivation then takes a list of layers and wraps emacs with those.

**Comment by johbo** [comment]
Any new insights on this? Got started on Spacemacs two weeks ago and I like it, so I started to wonder how to wrap it up in Nix.

**Comment by Profpatsch** [comment]
Not from my side, no.

**Comment by fullofcaffeine** [comment]
+1, any news here?

**Comment by Profpatsch** [comment]
I haven’t pursued this further, no. Right now there are more pressing issues imo, for example [laziness of `mkDerivation`](https://github.com/NixOS/nixpkgs/pull/11094).

**Comment by Profpatsch** [comment]
Personally I don’t think I’ll pursue this any further. Emacs is a strange beast, and Spacemacs is a moving target, so it’s hard enough to keep everything working when following upstream in a local `emacs.d`.

**Comment by deliciouslytyped** [comment]
I coincidentally might have worked on something helpful for this. https://github.com/syl20bnr/spacemacs/issues/12029 It at least might help separate the spacemacs fetchgit result from other stuff.
