### ISSUE TITLE
Activation script for binfmt fails

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#90683]
**Describe the bug**
With `boot.binfmt.emulatedSystems = [ "armv7l-linux" ];` set on an aarch64 machine, switching to a new config with nixos-rebuild produces the following error:
```
ln: invalid option -- 'c'
Try 'ln --help' for more information.
Activation script snippet 'binfmt' failed (1)
```
The relevant snippet in `/nix/var/nix/profiles/system/activate` is as follows:
```
#### Activation script snippet binfmt:
_localstatus=0
mkdir -p -m 0755 /run/binfmt
ln -sf /nix/store/d805030x8w6qzn3nrjfqd37pgl4rrcwr-bash-4.4-p23/bin/bash -c '"$@"' -- /run/binfmt/armv7l-linux


if (( _localstatus > 0 )); then
  printf "Activation script snippet '%s' failed (%s)\n" "binfmt" "$_localstatus"
fi
```
It looks like it expected a file path, but the `interpreter` it got was `/nix/store/d805030x8w6qzn3nrjfqd37pgl4rrcwr-bash-4.4-p23/bin/bash -c '"$@"' --` instead.

**To Reproduce**
1. Set `boot.binfmt.emulatedSystems = [ "armv7l-linux" ];` in `/etc/nixos/configuration`
2. Run `nixos-rebuild switch`

**Expected behavior**
It switches to the new system without any errors, and creates `/run/binfmt/armv7l-linux`as a symlink to something. 

**Notify maintainers**
@shlevy @matthewbauer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"aarch64-linux"`
 - host os: `Linux 5.7.0, NixOS, 20.09.git.c9abca93271 (Nightingale)`
\<nix-info appeared to hang after the first two lines\>

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: boot.binfmt
```

**Comment by Thra11** [comment]
```
❯ nixos-option boot.binfmt.registrations
Value:
{ armv7l-linux = {
  fixBinary = false;
  interpreter = "/nix/store/d805030x8w6qzn3nrjfqd37pgl4rrcwr-bash-4.4-p23/bin/bash -c '\"$@\"' --";
  magicOrExtension = "\\x7fELF\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x28\\x00";
  mask = "\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xfe\\xff\\xff\\xff";
  matchCredentials = false;
  offset = null;
  openBinary = false;
  preserveArgvZero = false;
  recognitionType = "magic";
}; }
```

**Comment by Thra11** [comment]
The `interpreter` has ultimately come from here:
https://github.com/NixOS/nixpkgs/blob/d3a40e7cfccba5f7362a5d14a2eedb5bfae3a661/lib/systems/default.nix#L114-L116

I assume most places which use this interpreter aren't symlinking to it, so they don't run into this bug.

**Comment by apo-llonx** [comment]
I have the same issue with i686-linux, yet for aarch64-linux, activation script links qemu-aarch64.

**Comment by matthewbauer** [comment]
Should be fixed with https://github.com/NixOS/nixpkgs/pull/108072.
