### ISSUE TITLE
package request: vouch-proxy

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#90728]
**Project description**
an SSO solution for Nginx using the auth_request module.

**Metadata**

* homepage URL: https://github.com/vouch/vouch-proxy
* source URL: https://github.com/vouch/vouch-proxy
* license: mit
* platforms: unix

**Comment by em0lar** [comment]
This can be closed as #135395 is merged

**Comment by aanderse** [comment]
Thanks!
