### ISSUE TITLE
nixos-install hang on https://cache.nixos.org/nix-cache-info (SSL issue ?)

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#9081]
Using the nixos-minimal-14.12.496.5f7d374-x86_64-linux.iso I am trying to install on [vultr](https://www.vultr.com/)

```
[root@nixos:~]# nixos-install
building the system configuration...
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/nix-cache-info’ after 5 seconds...
```

curl hangs during the SSL handshake:
```
[root@nixos:~]# curl -vvvv https://cache.nixos.org/nix-cache-info
* Hostname was NOT found in DNS cache
*   Trying 54.192.195.147...
* Connected to cache.nixos.org (54.192.195.147) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
```

the same command without SSL works just fine. It it possible that SSLv3 is not supported by CloudFront anymore ?

**Comment by vcunat** [comment]
My curl succeeds with `TLSv1.2`. IIRC SSLv3 is deprecated and currently being disallowed on various places, though I don't see if that would cause this problem. Your version of curl succeeds for me with a slightly different log:
```
SSLv3, TLS handshake, Client hello (1):
[...]
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
```

Could it be just some temporary problem? If not, your part of curl log doesn't show any error.

**Comment by zimbatm** [comment]
Thanks for taking the time to test it with the same curl version. I have a different-one on my machine that initiates the connection with TLSv1.2 so I assumed that was the issue.
I don't understand why CloudFront would work using HTTP but not HTTPS unless it was a software error. I have seen situations where the responses get lost but then the TCP handshake wouldn't complete and plain HTTP wouldn't work.
After running the same command a lot of time I had one instance where the response would hang after the HTTP headers being returned.

**Comment by zimbatm** [comment]
It's definitely a routing problem. I changed the MTU from 1500 to 1000 and everything seem to be going fine now.

**Comment by zimbatm** [comment]
thanks for listening :)

**Comment by zimbatm** [comment]
https://en.wikipedia.org/wiki/Path_MTU_Discovery#Problems

It seems like someone is blocking Path MTU Discovery. Ping messages bigger than 1448 don't seem to work.

```
> ping -n -M do -s 1448 cache.nixos.org
PING d3m36hgdyp4koz.cloudfront.net (54.230.60.122) 1448(1476) bytes of data.
1456 bytes from 54.230.60.122: icmp_seq=1 ttl=55 time=31.1 ms
1456 bytes from 54.230.60.122: icmp_seq=2 ttl=55 time=30.2 ms
> ping -n -M do -s 1449 cache.nixos.org
...
```

**Comment by vcunat** [comment]
It might be a location-dependent cloudfront problem. I found a report of a [MTU problem](https://forums.aws.amazon.com/thread.jspa?threadID=121976).

**Comment by zimbatm** [comment]
Thanks again for your help. I've raised an issue with Vultr, let's see what
else they can find out.

Most of these issues seem so mechanical to find, I'm surprised there is not
a tool that checks everything (DNS, routing, MTU path discovery, SSL
negociation, HTTP protocol, ...) and make a report that points to the most
likely error.

**Comment by obadz** [comment]
@zimbatm, how do you change the MTU?

**Comment by zimbatm** [comment]
for testing use ifconfig enp0s3 mtu 1450 (wherer enp0s3 is your network
interface name and 1450 the new MTU)

if you want to set it for the next reboot you can set it in your
/etc/nixos/configuration.nix file

{
  networking.interfaces.enp0s3.mtu = 1450;
}

​
