### ISSUE TITLE
Keymap files are missing in vim

### ISSUE THREAD

**Issue by nkaretnikov** [NixOS/nixpkgs#9083]
This is true for both `vim` and `vimHugeX`, so I ended up doing this:
https://github.com/nkaretnikov/dotfiles-tau/commit/906b43285053df376c207bd2ce39c7bbee1c1f93

**Comment by lheckemann** [comment]
`/nix/store/gzicsv3ij7rzcwv69f5rmlmcl3z1375y-vim-8.0.0329/share/vim/vim80/keymap/` contains keymap files for me. Suggest close?
