### ISSUE TITLE
binutils update to 2.23.2 breaks builds

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#909]
15f96c8 (updating binutils 2.23.1 -> 2.23.2 on the stdenv-updates branch) causes gnuplot to fail to build with libX11.so.6 not found:

    /nix/store/1nn46zq5b4mv6m8krjffzbrpzjngkviq-binutils-2.23.2/bin/ld: warning: libX11.so.6, needed by /nix/store/qykvkm3k35frzzfmhhgqhingvrpnmq8x-wxGTK-2.8.12.1/lib/libwx_gtk2u_adv-2.8.so, not found (try using -rpath or -rpath-link)

Full build output: https://gist.github.com/falsifian/6428621

I'll look into this later if I have time.

**Comment by vcunat** [comment]
@edolstra: I remove 15.06 milestone, assuming you don't insist on it.

**Comment by domenkozar** [comment]
Setting milestone to 16.03

**Comment by vcunat** [comment]
@domenkozar: 16.03? You plan to resolve this issue today?

**Comment by domenkozar** [comment]
@edolstra has raised concern yesterday to bump GCC5 and use binutils. Hopefully with the new Hydra logic we can test this in a few days to get an estimate.

**Comment by vcunat** [comment]
gcc-5 as well? I just assumed "feature-freeze" is today, but it was foolish of me to think we might avoid the last-minute rush :-)

**Comment by domenkozar** [comment]
That was the plan, at least.

**Comment by edolstra** [comment]
Yeah, sorry about that. I thought we were branching March 1st, not today. And I've been rather busy with Hydra stuff lately.

But I do think we need to get GCC 5 in this release. We've been stuck at 4.9 for several releases now. And the release highlights currently list only one item: that we renamed firefox-wrapper to firefox. That's not much of a reason to upgrade...

**Comment by vcunat** [comment]
I'm certain there have been lots of other important updates and improvements, only they aren't listed. GNOME and KDE bumps could be listed, for example (it seems customary elsewhere), but I guess different people are interested in different kind of features.

**Comment by edolstra** [comment]
Binutils 2.26 is now in staging.

**Comment by domenkozar** [comment]
For the record, this is causing pgadmin failing to build: http://hydra.nixos.org/build/33606524/nixlog/1/raw
