### ISSUE TITLE
global search for most recent version (across the different branches python-updates/haskell-updates/staging etc)

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#90915]
**Project description**
I run on nixos-unstable. Upon a problematic package, I used to check master/staging for any potential solution or the tracker. In last resort I would try to bump it myself or use the last working version.

I've now realized I also "have to" check python-updates/haskell-updates maybe even staging-next.
I hope we can have a search engine to search for the highest version across those (maybe a nix search with nixFlake could show this), document it a bit. Alternatively if anyone has a snippet to accomplish this, I would gladly steal it.

Unrelated but not worth its own ticket on the python-update branch @FRidh, at runtime, gevent complains with
```
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by FRidh** [comment]
I think it would be valuable if we had a cron job that would hourly or so evaluate all branches/channels to obtain available attributes, and present that data so it can be queried.
