### ISSUE TITLE
NixOS/NixOps best practices for small lab?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#9099]
I would like some workflow tips for how to manage a small computer lab with NixOS (and potentially NixOps). The lab is less than 10 machines and has no dedicated system administrator. Ideally each machine could be managed independently by different people but they could also be synchronized.

Currently I have installed NixOS on two hosts and put their configurations in a Github [repo](https://github.com/SnabbCo/snabblab-nixos). This is already a humongous improvement from the original imperatively operated Ubuntu installations. However, I am sure there is room for improvement.

Problems I see now:

1. NixOS version is not being tracked by Git. Rather it is determined by running `nix-channel` commands on the hosts. This means that from a network-wide perspective each machine is being managed imperatively rather than declaratively from the Git repository. How should I solve this? (Is NixOps the solution?)
2. The current state of the machine with respect to the Git repository is not clear. How do I know what is *really* running? One idea I have is to give each machine its own branch and have it always push its current running configuration there. This would then be manually reconciled with the master branch when machines should be brought closer into sync. This may be insanely over-complicated. The problem I want to avoid is losing changes when reinstalling a server from the master Git repo.

Generally I suppose that what I want to know is how other people would approach these problem and where I could find example configurations for reference. Also: is this a use case for NixOps or not? I am not sure because the collection of servers I am running is static and I am not dynamically provisioning new ones.

**Comment by nbp** [comment]
> I would like some workflow tips for how to manage a small computer lab with NixOS (and potentially NixOps). The lab is less than 10 machines and has no dedicated system administrator. Ideally each machine could be managed independently by different people but they could also be synchronized.

NixOps would imply that all your machines are managed from a central one.  This may not be ideal for your use case.

> NixOS version is not being tracked by Git.

NixOS version is reported by a program named `nixos-version`.  You can use it[1] to track which nixpkgs version you are based on.  What you can do, is have one directory to hold each computer configuration, and then have everybody run a script to update the git-submodule reference to the nixpkgs repository at the revision returned by `nixos-version`.

[1] https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/update-channel-branches.sh#L59-L66

**Comment by tohl** [comment]
>  1. NixOS version is not being tracked by Git. Rather it is
>     determined by running nix-channel commands on the hosts.
>     This means that from a network-wide perspective each machine
>     is being managed imperatively rather than declaratively from
>     the Git repository. How should I solve this? (Is NixOps the
>     solution?)
>  2. The current state of the machine with respect to the Git
>     repository is not clear. How do I know what is really
>     running? One idea I have is to give each machine its own
>     branch and have it always push its current running
>     configuration there. This would then be manually reconciled
>     with the master branch when machines should be brought
>     closer into sync. This may be insanely over-complicated. The
>     problem I want to avoid is losing changes when reinstalling
>     a server from the master Git repo.
>
> Generally I suppose that what I want to know is how other people
> would approach these problem and where I could find example
> configurations for reference. Also: is this a use case for
> NixOps or not? I am not sure because the collection of servers I
> am running is static and I am not dynamically provisioning new
> ones.

You could use NixOps.  Then the machines whould be built on the central
configuration machine (which has the NixOps sqlite database) with the
same NixOS version and the closure copied and deployed on the target
machine.

I haven't found a way to specify a different NixOS channel per machine
(e.g. something on stable and something on unstable).  It might be
possible to have NixOS channel per NixOps network, but that doesn't seem
so convenient.

You don't have to use the standard NixOS channel but instead manage your
own.  Or you can specify your own nixpkgs repo instead.  The more your
nixpkgs differ from the official hydra, the more compilation you'll have
to do.

But you don't have to use NixOps.  It might be easier to simply manage
the machines via ssh.

And if you want complete control over the packages, fork nixpkgs and use
your fork for the machines directly, instead of nix-channel.

**Comment by lukego** [comment]
Thanks for the ideas! This is really helpful information and I am moving forward.
