### ISSUE TITLE
14.12 bootstrapping problems when using nix-1.9

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#9105]
If one downloads `stdenv` from binary cache, downloading with that one works, but one is unable to bootstrap (without prefetching manually). Example output:
```
curl: (6) Couldn't resolve host 'tarballs.nixos.org'

trying http://tukaani.org/xz/xz-5.0.7.tar.bz2
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (6) Couldn't resolve host 'tukaani.org'
error: cannot download xz-5.0.7.tar.bz2 from any mirror
```
I also tried with bzip2, and it looks the same. Interestingly, just running the bootstrapping curl by hand fetches the files.

Noticed by @devhell on IRC.

**Comment by sorokin** [comment]
I can not switch to release-14.12 too, but because MesaLib 10.2.9  is missing from ftp.freedesktop.org:

```
building path(s) ‘/nix/store/hx3xsi2z51w21hpdsy6mm0f07xd32l0s-MesaLib-10.2.9.tar.bz2’

trying ftp://ftp.freedesktop.org/pub/mesa/10.2.9/MesaLib-10.2.9.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (9) Server denied you to change to the given directory
error: cannot download MesaLib-10.2.9.tar.bz2 from any mirror
builder for ‘/nix/store/qp0px1v204x4ig5w4i07n1sbqwn8pv4x-MesaLib-10.2.9.tar.bz2.drv’ failed with exit code 1
```

**Comment by vcunat** [comment]
@Sorokin: that should be fixed by a5444111bc1, contained in the current nixos-14.12 channel.

**Comment by sorokin** [comment]
@vcunat probably I tried too old version. I confirm that it is fixed now.

**Comment by edolstra** [comment]
I think this was fixed in master in 3d7f66e955b64735a6881c9d0fc36ede45f5168e. This problem should also only occur with Nix 1.9 (because it made fetchurl run in a chroot), but 1.8 is the default in NixOS 14.12. A workaround on 1.9 is to set `build-use-chroot` to `relaxed`.

**Comment by vcunat** [comment]
Hmm, so only nix-1.9 and channel 14.12... that's probably not worth fixing. 14.12 will be well-supported only for a few months from now, I suppose.

**Comment by vcunat** [comment]
No use to keep this open anymore...
