### ISSUE TITLE
python38Packages.boto3 broken due to miss-match  of botocore version

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#91081]
**Describe the bug**
Currently the package `python38Packages.boto3` does not build. I believe this was due to the boto3 package being updated without the botocore package being updated to 1.16.23

**To Reproduce**
1. nix-build -A python38Packages.boto3

**Expected behavior**
Package builds without issues.

**Additional context**
```
/build/boto3-1.13.23/dist /build/boto3-1.13.23
Processing ./boto3-1.13.23-py2.py3-none-any.whl
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /nix/store/0vk0gk32sfflvqkk02idsd1lv72j4vik-python3.8-jmespath-0.9.5/lib/python3.8/site-packages (from boto3==1.13.23) (0.9.5)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /nix/store/f055iykbyb45vgbrh177fm5ga4l32901-python3.8-s3transfer-0.3.3/lib/python3.8/site-packages (from boto3==1.13.23) (0.3.3)
ERROR: Could not find a version that satisfies the requirement botocore<1.17.0,>=1.16.23 (from boto3==1.13.23) (from versions: none)
ERROR: No matching distribution found for botocore<1.17.0,>=1.16.23 (from boto3==1.13.23)
builder for '/nix/store/li6s8dl2sb90q2gwcz4vi63cgyzlyfn1-python3.8-boto3-1.13.23.drv' failed with exit code 1
error: build of '/nix/store/li6s8dl2sb90q2gwcz4vi63cgyzlyfn1-python3.8-boto3-1.13.23.drv' failed
```

**Notify maintainers**
@FRidh 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.2, NixOS, 20.09.20200615.22c9881 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200521_00b562c`
 - channels(root): `"nixos-20.03.1950.48723f48ab9"`
 - channels(terje.larsen): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- python38Packages.boto3
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
Please use the search function before opening an issue.

**Comment by terlar** [comment]
I did, but I guess I failed by searching with the default filters (open issues). Didn't know about staging-next. Good to know that master is not always the most "bleeding edge". Thanks for the great work and sorry for the noise.
