### ISSUE TITLE
nix 2.3.6 fails to build on darwin blocking nixpkgs-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#91091]
**Describe the bug**
Nix fails to build on darwin blocking nixpkgs-unstable.
https://hydra.nixos.org/build/122542010

**Notify maintainers**
@NixOS/darwin-maintainers

**Comment by domenkozar** [comment]
https://github.com/NixOS/nix/issues/3605

**Comment by vcunat** [comment]
This way it will keep re-appearing randomly on Hydra (now happened on `staging-next`).  As it doesn't seem likely to be fixed soon or important, do we disable this particular test on darwin?
