### ISSUE TITLE
dotnet core debugging

### ISSUE THREAD

**Issue by luxferresum** [NixOS/nixpkgs#91179]
**Describe the bug**
I'm trying to get `dotnet core` working with debugging from vscode.
`dotnet run` works fine. But attaching a debugger from vscode breaks. And I'm really not sure from where the error comes. Its just that nothing happens. When I go for "attach" it just stops the debugger immediatly after selecting the process. And `launch` fails in a similar way

**To Reproduce**
1. install `dotnet-sdk_3`, `omnisharp-roslyn` and `vscode`
2. run `dotnet new console -o testdotnetcore && cd testdotnetcore`
3. open `code` in that folder, install the `C#` extension
4. create a `omnisharp.json` with the following content:
 ```
{
    "MsBuild": {
        "UseLegacySdkResolver": true
    }
}
```
5. now press `Ctrl+Shift+P` and run `Restart Omnisharp`
6. it will ask to generate a `launch.json` and `tasks.json`. Say OK.
7. Set a breakpoint
8. Press `F5` and select the `Launch (console)` profile
9. It does not hit the breakpoint but only builds the project and then stops

**Expected behavior**
I clearly expected it to run the project, attach a debugger and hit the breakpoint.

**Additional context**
I'm not sure if this is related but `omnisharp` fails to load the project without `UseLegacySdkResolver: true`. I'm not sure why this fixes the problem but I dont think this is related.

Looking at the launch configuration:
```
{
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/testdotnetcore.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
}

What seems to launch something seems to be the `"type": "coreclr",` part. But I cant figure out if this is part of `omnisharp-roslyn` or `dotnet-sdk`. And vscode shows no kind of errors at all.

**Comment by veprbl** [comment]
cc @jonringer

**Comment by jonringer** [comment]
Generally this has to do with how dotnet publishes/builds outputs. It will usually dump some native libraries into a directory, but those shared libraries aren't able to reference the correct dependencies they need. 

In your shell, you could probably do something like:
```
lpath = lib.makeLibraryPath [ stdenv.cc.cc libunwind libuuid icu openssl zlib curl ];
export LD_LIBRARY_PATH=${lpath}
```
and it may solve your issue.


I just switched teams at work, and will be using dotnet again. I'll try to improve the usability of it then.
