### ISSUE TITLE
Misleading systemd.network.netdevs..vlanConfig.Id documentation

### ISSUE THREAD

**Issue by otopetrik** [NixOS/nixpkgs#91172]
`systemd.network.netdevs.<name>.vlanConfig.Id` as shown in the documentation is wrong:
https://github.com/NixOS/nixpkgs/blob/fea8c13075b10093db6716378fbba6636bfa7fa6/nixos/modules/system/boot/networkd.nix#L422

using string `"4"` fails with
```
building Nix...
building the system configuration...
error: cannot compare a string with an integer
(use '--show-trace' to show detailed location information)
```
using number `4` (without quotes) succeeds.

looks like it is not processed as a string, it is checked as an integer:
https://github.com/NixOS/nixpkgs/blob/fea8c13075b10093db6716378fbba6636bfa7fa6/nixos/modules/system/boot/networkd.nix#L86

**Comment by flokli** [comment]
I filed a PR at https://github.com/NixOS/nixpkgs/issues/91172, PTAL.
