### ISSUE TITLE
Onlykey package broken

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#91175]
**Describe the bug**
Attempting to installing the onlykey package via options fails with the following error:

```
error: undefined variable 'builtin' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/hardware/onlykey.nix:29:32
(use '--show-trace' to show detailed location information)
```

**To Reproduce**
1. Add `hardware.onlykey.enable = true;` to your nixos config.
2. Run `nixos-rebuild switch --upgrade`

**Expected behavior**
The necessary packages for Onlykey should be installed.

**Maintainer Mentions**

@yrashk

**Comment by prusnak** [comment]
The file `nixos/modules/hardware/onlykey.nix` should read `builtins.readFile` instead of `builtin.readFile`. @cawilliamson are you interested in sending a PR with the fix?

**Comment by cawilliamson** [comment]
@prusnak Raised as https://github.com/NixOS/nixpkgs/pull/91296

**Comment by prusnak** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/91296 but the issue wasn't closed. Closing now
