### ISSUE TITLE
tmux broken on macOS

### ISSUE THREAD

**Issue by davidarmstronglewis** [NixOS/nixpkgs#91185]
**Describe the bug**
Running tmux on macOS fails with the error:
```
➜ tmux
error creating /run/user/$(id -u)/tmux-501 (No such file or directory)
```

I've tracked down the issue to [this line](https://github.com/NixOS/nixpkgs/blob/132ace5fe60d50e45afa5904e0d85b83e376463f/nixos/modules/programs/tmux.nix#L180) which provides a default for the `TMUX_TMPDIR` value of `"/run/user/$(id -u)"`. Unfortunately, on macOS, there is no such `/run` directory, so the only option is to provide an override for `$XDG_RUNTIME_DIR`.

**To Reproduce**
1. Turn on Mac
2. Install Nix
3. Install tmux
4. Start tmux

**Notify maintainers**
@shlevy
@matthiasbeyer
@wkennington
@peterhoeg
@fpletz
@xrelkd
@Pamplemousse
@dezgeg
@tobias-hammerschmidt
@ruediger
@dupgit
@globin
@kimat
@Mic92
@ookhoi
@doronbehar
@darklajid
@LnL7
@kmille
@bjornfor
@aneeshusa
@7c6f434c

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.5.0, macOS 10.15.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(davidlewis): `"home-manager, nixpkgs-20.09pre230446.a84cbb60f02"`
 - nixpkgs: `/Users/davidlewis/.nix-defexpr/channels/nixpkgs`
```

**Random**
There seems to be a significant number of maintainers for this package based on what I've seen in GitHub. Sorry for notifying you all, I have no idea who would have been the best person to notify.

**Comment by LnL7** [comment]
The file you mentioned is a nixos module, that's no relevant for other platforms, including non nixos linux distributions.

**Comment by matthiasbeyer** [comment]
> There seems to be a significant number of maintainers for this package based on what I've seen in GitHub. Sorry for notifying you all, I have no idea who would have been the best person to notify.

I don't know what you're talking about, there are only two maintainers:

```
maintainers = with stdenv.lib.maintainers; [ thammers fpletz ];
```

(taken from pkgs/tools/misc/tmux/default.nix)

---

Also what @LnL7 said. I propose to close this, as this is not an issue with the module.

**Comment by marsam** [comment]
I think I remember this error, it comes from home-manager https://github.com/rycee/home-manager/blob/1f174f668109765183f96b43d56ee24ab02c1c05/modules/programs/tmux.nix#L306. 
You can set `secureSocket = false` as a workaround:
```nix
tmux = {
  enable = true;
  secureSocket = false;
};
```
Closing since it doesn't belong to nixpkgs

**Comment by Mic92** [comment]
In other words please open this issue in either home-manager or darwin-nix depending what module you are using, thanks!

**Comment by davidarmstronglewis** [comment]
> The file you mentioned is a nixos module, that's no relevant for other platforms, including non nixos linux distributions.

You're absolutely right. Sorry about that, I'm new to the project and missed that fact in the path.



> > There seems to be a significant number of maintainers for this package based on what I've seen in GitHub. Sorry for notifying you all, I have no idea who would have been the best person to notify.
> 
> I don't know what you're talking about, there are only two maintainers:
> 
> ```
> maintainers = with stdenv.lib.maintainers; [ thammers fpletz ];
> ```
> 
> (taken from pkgs/tools/misc/tmux/default.nix)
> 
> Also what @LnL7 said. I propose to close this, as this is not an issue with the module.

Ah, I must have missed that - thanks for pointing that out for me.

> I think I remember this error, it comes from home-manager https://github.com/rycee/home-manager/blob/1f174f668109765183f96b43d56ee24ab02c1c05/modules/programs/tmux.nix#L306.
> You can set `secureSocket = false` as a workaround:
> 
> ```nix
> tmux = {
>   enable = true;
>   secureSocket = false;
> };
> ```
> 
> Closing since it doesn't belong to nixpkgs

I see what you mean, still getting used to Nix, so I appreciate the response. Thanks!

> In other words please open this issue in either home-manager or darwin-nix depending what module you are using, thanks!

Appreciate you all taking the time to set me off in the right direction. Apologies if I've derailed you all from your current work.

And thank you for putting your effort into this project - I'm absolutely loving it, despite going through the ol' learning curve 😅
