### ISSUE TITLE
GPIO only accessible as root on Raspberry Pi (4)

### ISSUE THREAD

**Issue by moritzschaefer** [NixOS/nixpkgs#91219]
**Describe the bug**
As @LongLiveCHIEF described in [another issue](https://github.com/adafruit/Adafruit_Blinka/issues/150#issuecomment-609078669), 

> 
> On some distros, there may not be a gpio group, in which case /dev/gpiomem would be owned by root instead of gpio. (for example, ubutu server for rpi 3+)
> 
> In this case, you'll need to add a gpio group, add your user to the gpio group, and then create a udev rule for gpio. The RPI.GPIO library has a good [python script](https://sourceforge.net/p/raspberry-gpio-python/code/ci/default/tree/create_gpio_user_permissions.py) for this, and you just need to change the name of the user from 'pi' to whatever your user is

A possible solution would be to add "gpio" to the existing groups in RPi images and add the following udev rule (from the mentioned python script):
```
SUBSYSTEM=="bcm2835-gpiomem", KERNEL=="gpiomem", GROUP="gpio", MODE="0660"
SUBSYSTEM=="gpio", KERNEL=="gpiochip*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:gpio /sys/class/gpio/export /sys/class/gpio/unexport ; chmod 220 /sys/class/gpio/export /sys/class/gpio/unexport'"
SUBSYSTEM=="gpio", KERNEL=="gpio*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:gpio /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value ; chmod 660 /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value'"
```

**To Reproduce**
1. Install NixOS on RaspberryPi (4)
2. Try to access gpio-Pins as non-root
3. Fail

**Expected behavior**
- All users within the "gpio" group should have access to the gpio ports

**Additional context**
I only tried this on RPi4 but suspect it's the same situation on other Pis.

**Metadata**

[moritz@monix:~]$ sudo ls -l !$
sudo ls -l /dev/gpiomem
crw------- 1 root root 244, 0 Jan  1  1970 /dev/gpiomem

[moritz@monix:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/shvkq93g10s832yc711dv22p3ddvrmkk-bash-interactive-4.4-p23-dev
copying path '/nix/store/shvkq93g10s832yc711dv22p3ddvrmkk-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.75, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-unstable-20.09pre230335.9480bae3370, nixos-20.03pre206632.b0bbacb5213"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by flokli** [comment]
I wouldn't consider this a nixpkgs bug, more a deviation from how things look on Raspian. Having a `gpio` group is one way to do this, and it really depends on the individual system configuration.

On ArchlinuxARM, [you also need to add your own udev rule for that](https://gist.github.com/gavinhungry/1ab5b5450e0409765ad8906fcdd69997).

I propose adding some information to the NixOS wiki instead.

**Comment by flokli** [comment]
Let's close this. This works as intended - if these GPIO ports should be accessible for users other than root, an udev rule is the right way to get access.

**Comment by LongLiveCHIEF** [comment]
agree.
