### ISSUE TITLE
Bitmap fonts are completely unusable

### ISSUE THREAD

**Issue by LunarLambda** [NixOS/nixpkgs#91252]
Installing bitmap font packages like `tewi-font`, `dina-font`, or `terminus_font` does not make the fonts available in any fontconfig compatible programs.

**To Reproduce**

```
# add this to configuration.nix
fonts.fontconfig.allowBitmaps = true;
fonts.fontconfig.useEmbeddedBitmaps = true;
fonts.enableFontDir = true;
fonts.fonts = with pkgs; [ terminus_font ];
```

Then, attempt to use `Terminus` in a program such as `gnome-terminal`, `gedit`, etc...
The font does not appear in any font listing in these programs, though it can be found with `fc-match terminus`.

**Expected behavior**
The fonts should appear.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.03.2262.2b417708c28 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
I believe this is a duplicate of https://github.com/NixOS/nixpkgs/issues/75160

**Comment by LunarLambda** [comment]
It is. When searching for similar issues I did not see it, thank you
