### ISSUE TITLE
Unable to build environment with texlive.scheme-infraonly

### ISSUE THREAD

**Issue by nyraghu** [NixOS/nixpkgs#91263]
**Describe the bug**
I am unable to build an environment with texlive.scheme-infraonly and just the texlive packages that I want to use.

**To Reproduce**
1. Create this `default.nix` file, where the package `amsmath` is used only as an example.
``` nix
let
  nixpkgsPath = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/92c3267ad4adcf5db15baf2cbb25c15f65b6b86f.tar.gz";
    sha256 = "09fza5yn29jy6pgj9x3ad7phrgdyz35xw0gb8z7bi9dks7c875kj";
  };
  nixpkgs = import nixpkgsPath {};
  texlive = nixpkgs.texlive;
  texlivePackages = texlive.combine {
    inherit (texlive) scheme-infraonly amsmath;
  };
in nixpkgs.buildEnv {
  name = "nix-texlive";
  paths = [ texlivePackages ];
}
```
2. Do `nix-build`:
``` bash
$ nix-build 
these derivations will be built:
  /nix/store/mxp8mr3l21kf2b34dagv97i6r9qqmc4y-texlive-combined-2019.drv
  /nix/store/2gk1s82n6llj3fvlcig3m3mxksvmpwd8-nix-texlive.drv
building '/nix/store/mxp8mr3l21kf2b34dagv97i6r9qqmc4y-texlive-combined-2019.drv'...
created 37 symlinks in user environment
rm: cannot remove './language.dat': Permission denied
builder for '/nix/store/mxp8mr3l21kf2b34dagv97i6r9qqmc4y-texlive-combined-2019.drv' failed with exit code 1
cannot build derivation '/nix/store/2gk1s82n6llj3fvlcig3m3mxksvmpwd8-nix-texlive.drv': 1 dependencies couldn't be built
error: build of '/nix/store/2gk1s82n6llj3fvlcig3m3mxksvmpwd8-nix-texlive.drv' failed
```

**Expected behavior**
A symlink `result` to a directory containing `bin` and `share` with the requested `texmf` files.

**Additional context**
I am trying to build a texlive environment with only the packages I need.

**Notify maintainers**
@veprbl

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-53-generic, Linux Mint, 18.1 (Serena)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(raghu): `"nixpkgs-20.09pre228453.dcb64ea42e6"`
 - nixpkgs: `/home/raghu/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: texlive.scheme-infraonly
# a list of nixos modules affected by the problem
module:
```

**Comment by nyraghu** [comment]
It works now.  Many thanks.

**Comment by veprbl** [comment]
Applied to release-20.03 as well, should hit the channel soon. Enjoy!
