### ISSUE TITLE
Cross compiling ruby pulls in host package despite it being in nativeBuildInputs

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#91265]
**Describe the bug**

**To Reproduce**

- run `nix-build -A pkgsCross.armv7l-hf-multiplatform.ruby` on an x86_64 system
- Observe that it fails trying to run an arm binary of bison
- Observe that that derivation lists the wrong architecture bison in nativebuildInputs(!) 

    ```
    , ( "nativeBuildInputs"
      , "/nix/store/p8frky3amk07n2illsnqbn1k8lhy6mci-hook /nix/store/ppb9620xh5gri16lgf6f9sn46mdv2xyk-bison-3.5.4-armv7l-unknown-linux-gnueabihf /nix/store/dbjqx0r50sf5sanmsb0lgyq9zf3vck2k-groff-1.22.4 /nix/store/33nr5mknv9wc75f7lbgnck0z3xipya6s-ruby-2.6.6"
      )
    ```

- Remove the bison override for ruby in `all-packages.nix`
- Observe that the native bison is used and present in the derivation (although the build fails with this version of bison as expected)

**Additional context**

I conjecture that `bison_3_5` `overridesAttrs` is somehow interfering with getting the native derivation when it is passed to `nativeBuildInputs`

**Notify maintainers**

@FRidh I think you added this override.

@vrthra @manveru maintainers for ruby.
 
**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.git.48723f48ab9M (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/home/j/src/nixpkgs2`
```

Maintainer information:
```yaml
attribute:
  - pkgsCross.armv7l-hf-multiplatform.ruby
```

**Comment by expipiplus1** [comment]
This certainly doesn't seem like a problem specific to ruby btw.

**Comment by FRidh** [comment]
fixed with 7bf20d7c17fe08f5c8ceb914b27b9be08da4454e

**Comment by FRidh** [comment]
> This certainly doesn't seem like a problem specific to ruby btw.

Many expressions have not been written with cross-compilation in mind, and so don't separate native build inputs from host inputs.

**Comment by expipiplus1** [comment]
Thanks @FRidh! Is there a short reason why the usual `nativeBuildInputs` machinery didn't do this already? It seems to work when one has `bison=bison`

**Comment by FRidh** [comment]
When you use `callPackage`, the splicing automatically passes it the correct version (`buildPackages` or not). However, if you pass in something explicitly, you need to choose. Have a look at https://github.com/NixOS/nixpkgs/issues/68967#issuecomment-532432617.

**Comment by expipiplus1** [comment]
Thanks again, makes sense!
