### ISSUE TITLE
NAR info file 'xxx' is signed by unknown key ‘hydra.nixos.org-1’; ignoring

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#9129]
I updated my system to 8c6a2e3b5d291bfc08bb62a50772431e3a5f1854.

Trying to perform nixos-rebuild on this system gives many errors:
```
building Nix...                                                                                                                                                                               
building the system configuration...                                                                                                                                                          
download-from-binary-cache.pl: NAR info file ‘https://hydra.nixos.org/fnllqp1q22grns4jhy5lm3sq3jxcz8k6.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
download-from-binary-cache.pl: NAR info file ‘https://hydra.nixos.org/a9hwfazbbbbjcjm5p5661d4kb8b37hnw.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
download-from-binary-cache.pl: NAR info file ‘https://hydra.nixos.org/7cnmdrg84sl6bgggr80pac3xmmh38r8w.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
```

and nix falls back to building everything from source.

On older system nixos-rebuild works.

**Comment by sorokin** [comment]
Yes. I booted a previous system (based on revision 09db60c5ef3895c5f42f208f17856ca5902f5bde) and nixos-rebuild work correctly here.

**Comment by wkennington** [comment]
That's because signing is enforced in master now and we don't have a
trusted key added for hydra by default.

**Comment by sorokin** [comment]
Ok. I have added to /etc/nixos/configuration.nix a line
```
  nix.binaryCachePublicKeys = [ "hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs=" ];
```
and it resolved the issue.

Probably it worth noting in error message where user can change list of keys?

**Comment by peti** [comment]
Where can I find instructions on how to configure my own Hydra server to provide signed binaries?

**Comment by edolstra** [comment]
@peti Generate a key pair:
```
$ nix-store --generate-binary-cache-key example.org-1 ./secret ./public
```
Add this line to `hydra.conf`:
```
binary_cache_secret_key_file = /path/to/secret
```
And add the contents of `./public` to the `binary-cache-public-keys` option in `nix.conf` on the client machines.

**Comment by peti** [comment]
@edolstra, thank you for the quick response!

**Comment by cstrahan** [comment]
Here's the announcement from the mailing list: http://lists.science.uu.nl/pipermail/nix-dev/2015-April/016834.html

If you like living dangerously, you can alternatively add this to your `configuration.nix`:

    nix.requireSignedBinaryCaches = false;
