### ISSUE TITLE
Nix does not fetch packages from the binary cache

### ISSUE THREAD

**Issue by josephtheengineer** [NixOS/nixpkgs#91338]
Original Title: Nix does not fetch qtwebkit / freecad / kdenlive from the binary cache

**Describe the bug**
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [Source/JavaScriptCore/shell/CMakeFiles/testb3.dir/build.make:83: Source/JavaScriptCore/shell/CMakeFiles/testb3.dir/__/b3/testb3.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:879: Source/JavaScriptCore/shell/CMakeFiles/testb3.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
builder for '/nix/store/siw6vm0ygg339h2m9aij9amgv08i2h8s-qtwebkit-5.212-alpha-01-26-2018.drv' failed with exit code 2
cannot build derivation '/nix/store/n1n2zwlch17f91c2pgfqac3530pmlf7y-freecad-0.18.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/70pmqcqar1m8pjfzdmxi75ripbkq4768-kdenlive-19.12.3.drv': 1 dependencies couldn't be built
building '/nix/store/j423rw7v955wcrd0bjw8kc6bs3055hzn-quran.r50980.tar.xz.drv'...
building '/nix/store/l5c6y8q2j86942ky9004dd07h21j2k6m-ragged2e.r51780.tar.xz.drv'...
building '/nix/store/vfrhabi1qrrar9pr3150zfhf1q7lfh08-rtkit-0.13.drv'...
building '/nix/store/5rspm3irk2cdivc2gxvfkj1xrkw9jwvh-snmp.conf.drv'...
cannot build derivation '/nix/store/mlc8szd98ywqblj2gbzynsjlmdm5n8s9-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/f3rk6s6iaj87bnc3q939njshqka3b0pl-nixos-system-ghost-20.09pre230335.9480bae3370.drv': 1 dependencies couldn't be built
error: build of '/nix/store/f3rk6s6iaj87bnc3q939njshqka3b0pl-nixos-system-ghost-20.09pre230335.9480bae3370.drv' failed
```

**To Reproduce**
1. `sudo nixos-rebuild switch --upgrade`

**Expected behavior**
Nix to download the binary from cache.nixos.org

**Screenshots**
![Screenshot](https://i.imgur.com/8Kv0ccQ.png)

**Additional context**
Been trying to update my system for 2 days D:

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.18, NixOS, 20.03.2262.2b417708c28 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre230335.9480bae3370"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
Do you have some "overrides"?  With commit 9480bae3 and x86_64-linux, I'm getting
```
$ nix-instantiate -A kdenlive
/nix/store/vjkqg5083j48zslzii5igwmvv1iarwwr-kdenlive-19.12.3.drv
```
(different derivation path than you) and that one is fully in cache.  Same story with `qt5qtwebkit`.

_A dependency of `freecad` won't build at that commit, but that apparently isn't the core of_ your _problem._

**Comment by josephtheengineer** [comment]
I do have one override but it's for R that shouldn't effect it, right?
```
{ config, pkgs, ... }:
with pkgs;
let
        R-packages = rWrapper.override{ packages = with rPackages; [ rmarkdown ]; };
in
{
	environment.systemPackages = with pkgs; [
             ...
```

**Comment by josephtheengineer** [comment]
Something werid is going on though, it's the same thing that happend 5 days ago #90668

**Comment by josephtheengineer** [comment]
Seems that nix is downloading binaries again, werid.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.2, NixOS, 20.09pre229574.0a146054bdf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre230335.9480bae3370"`
 - channels(josephtheengineer): `"nixos-19.09pre186326.62cb4f72282"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by josephtheengineer** [comment]
Seems that after the reboot Linux updated from `5.6.18, NixOS, 20.03.2262.2b417708c28 (Markhor)` to `5.7.2, NixOS, 20.09pre229574.0a146054bdf (Nightingale)`

So maybe something to do with a old linux kernal making packages differ from cache.nixos.org?

**Comment by vcunat** [comment]
No, I'm fairly confident that running kernel won't affect it.

**Comment by josephtheengineer** [comment]
hmmm currently building `/nix/store/al9wk2c1l2j6fdpclj4k9cnxyc4i0k3b-glibc-2.30-dev`

**Comment by vcunat** [comment]
That's normally in cache
```
$ nix build /nix/store/al9wk2c1l2j6fdpclj4k9cnxyc4i0k3b-glibc-2.30-dev
[6 copied (41.4 MiB), 8.6 MiB DL]
$
```

**Comment by wamserma** [comment]
> Seems that after the reboot Linux updated from `5.6.18, NixOS, 20.03.2262.2b417708c28 (Markhor)` to `5.7.2, NixOS, 20.09pre229574.0a146054bdf (Nightingale)`

Nah. But it seems you switched channels. Your initial post also shows that you are running 20.03 and root was following 20.09pre. Additionally the auto-upgrade in your config follows unstable. This might lead to a mix of channels and therefore to the local re-builds.

**Comment by josephtheengineer** [comment]
Closing as unreproducible ¯\\_(ツ)_/¯
