### ISSUE TITLE
vim plugins can't be updated (github 429)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#91339]
**Describe the bug**

I can't update vim plugins.

1. The script doesn't auth to GitHub.

2. The script seems to hit GitHub with 30 parallel reqs which... GH doesn't like.

3. The script doesn't output anything verbosely so I have no idea what's doing on at runtime when trying to fix it.

4. I've tried to fix it and instead just... well, this is what it output, all at once, on my last attempt and I'm sort of just done with python for the night: https://gist.github.com/7c68e193b81f72a1d1944fc71868d97f

**To Reproduce**
1. Try to add a vim plugin `./update.py --add owner/repo`

**Comment by flokli** [comment]
I had some success using `hub api` and their graphql endpoint for the terraform provider bump script - this should at least allow you to get the latest tag and whether there are any submodules in the same request. (And possibly some batching to look up multiple repositories per query).

**Comment by colemickens** [comment]
https://github.com/NixOS/nixpkgs/pull/91656 fixes this by accepting and using `GITHUB_API_TOKEN`. (And needs a merge :wink: )

**Comment by colemickens** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/91656.

**Comment by gvolpe** [comment]
As commented in #91656 , this doesn't seem to work. Can anyone else confirm whether this works for you or not? Otherwise, we would need to re-open this issue.

**Comment by vdot0x23** [comment]
> As commented in #91656 , this doesn't seem to work. Can anyone else confirm whether this works for you or not? Otherwise, we would need to re-open this issue.

Yeah, doesn't seem to work for me either. Even with `GITHUB_API_TOKEN` I get HTTP 429.

**Comment by colemickens** [comment]
You might need to check your permissions: I think the token needs `public_repos` access, at least. (@gvolpe's issue was different than still getting 429s)

**Comment by vdot0x23** [comment]
> You might need to check your permissions: I think the token needs `public_repos` access, at least. (@gvolpe's issue was different than still getting 429s)

Ah, that did the trick, thanks :)
