### ISSUE TITLE
borgmatic – for Linux et al.

### ISSUE THREAD

**Issue by x80486** [NixOS/nixpkgs#91358]
## Project description

**borgmatic** is simple, configuration-driven backup software for servers and workstations. Protect your files with client-side encryption. Backup your databases too. Monitor it all with integrated third-party services.

## Metadata

* Homepage: `https://torsion.org/borgmatic/`
* Source: `https://projects.torsion.org/witten/borgmatic/issues`
* License: GPL v3 (`https://projects.torsion.org/witten/borgmatic/src/branch/master/LICENSE`)
* Platforms: UNIX, Linux, Darwin (I guess anywhere Python is supported)

**Comment by bryanasdev000** [comment]
Up!
