### ISSUE TITLE
packaging request: (g)feeds

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#91370]
**Project description**

An RSS/Atom feed reader for GNOME.

**Metadata**

* homepage URL: https://gitlab.gnome.org/World/gfeeds
* source URL: https://gitlab.gnome.org/World/gfeeds
* license: GPL v3
* platforms: linux, possibly others?

**Comment by pbogdan** [comment]
I haven't tested it extensively yet but here's my current expression:

https://gist.github.com/pbogdan/8eefec4cef068bbcc91e34062a6b3d27

The basic at the very least seem to work.

**Comment by MetaDark** [comment]
@pbogdan I haven't run into any problems using your expression, are you planning on creating a pull request for this?

**Comment by pbogdan** [comment]
Glad you found it useful. And thank you for the reminder, I forgot about this (just stashed it into a local overlay) but will try and prepare a PR in the next couple of days.
