### ISSUE TITLE
openldap: fails to cross-compile

### ISSUE THREAD

**Issue by betaboon** [NixOS/nixpkgs#91407]
**Describe the bug**
`openldap` fails to cross-compile for (at least) `aarch64` and `armv7l`.

**To Reproduce**
- `nix-build https://github.com/NixOS/nixpkgs/archive/d8d19f249793966d1cce391d54203cc717764e63.tar.gz -A pkgsCross.aarch64-multiplatform.openldap`
- `nix-build https://github.com/NixOS/nixpkgs/archive/d8d19f249793966d1cce391d54203cc717764e63.tar.gz -A pkgsCross.armv7l-hf-multiplatform.openldap`

**Expected behavior**
Build succeeds

**Additional context**
- fails with `../../../../libtool: line 1322: gcc: command not found`
- possible root cause: https://git.openldap.org/openldap/openldap/-/blob/master/contrib/slapd-modules/passwd/sha2/Makefile#L11

**Notify maintainers**
cc @lovek323 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.2, NixOS, 20.09pre229870.22c98819ccd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre229870.22c98819ccd, nixos-20.03-20.03.2176.a84b797b28e"`
 - channels(betaboon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by alyssais** [comment]
Seems to work fine now.
