### ISSUE TITLE
Unable to build libxml2 in latest macos

### ISSUE THREAD

**Issue by swarnpriya** [NixOS/nixpkgs#91414]
Unable to build libxml2

Repro: nix-env -i libxml2

make[4]: Entering directory '/private/var/folders/7g/1ptqqd597r76dqzk7hjy0bgc0000gn/T/nix-build-libxml2-2.9.10.drv-0/libxml2-2.9.10/python'
  CC       libxml.lo
  CC       libxml2-py.lo
  CC       types.lo
libxml.c:1649:43: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        message = libxml_charPtrConstWrap(ptr);
                                          ^~~
./libxml_wrap.h:240:48: note: passing argument to parameter 'str' here
PyObject * libxml_charPtrConstWrap(const char *str);
                                               ^
1 warning generated.
  CCLD     libxml2mod.la
ld: library not found for -lintl
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:600: libxml2mod.la] Error 1
make[4]: Leaving directory '/private/var/folders/7g/1ptqqd597r76dqzk7hjy0bgc0000gn/T/nix-build-libxml2-2.9.10.drv-0/libxml2-2.9.10/python'
make[3]: *** [Makefile:694: all-recursive] Error 1
make[3]: Leaving directory '/private/var/folders/7g/1ptqqd597r76dqzk7hjy0bgc0000gn/T/nix-build-libxml2-2.9.10.drv-0/libxml2-2.9.10/python'
make[2]: *** [Makefile:528: all] Error 2
make[2]: Leaving directory '/private/var/folders/7g/1ptqqd597r76dqzk7hjy0bgc0000gn/T/nix-build-libxml2-2.9.10.drv-0/libxml2-2.9.10/python'
make[1]: *** [Makefile:1479: all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/7g/1ptqqd597r76dqzk7hjy0bgc0000gn/T/nix-build-libxml2-2.9.10.drv-0/libxml2-2.9.10'
make: *** [Makefile:893: all] Error 2
builder for '/nix/store/xcqdl8cfjjbjvh7g9ka0ip3r4awy80a8-libxml2-2.9.10.drv' failed with exit code 2
error: build of '/nix/store/xcqdl8cfjjbjvh7g9ka0ip3r4awy80a8-libxml2-2.9.10.drv' failed

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.5.0, macOS 10.15.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(swarnpriya): `"nixpkgs-20.09pre230446.a84cbb60f02"`
 - nixpkgs: `/Users/swarnpriya/.nix-defexpr/channels/nixpkgs`

**Comment by jsoo1** [comment]
Disclaimer: I barely know what I'm doing.

I tried adding `lintl` as a build input to libxml2.

```patch
diff --git a/pkgs/development/libraries/libxml2/default.nix b/pkgs/development/libraries/libxml2/default.nix
index 7c39d803906..fb139e96fa4 100644
--- a/pkgs/development/libraries/libxml2/default.nix
+++ b/pkgs/development/libraries/libxml2/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, lib, fetchurl, fetchpatch
+{ stdenv, lib, fetchurl, fetchpatch, libintl
 , zlib, xz, python, ncurses, findXMLCatalogs
 , pythonSupport ? stdenv.buildPlatform == stdenv.hostPlatform
 , icuSupport ? false, icu ? null
@@ -45,6 +45,7 @@ stdenv.mkDerivation rec {
 
   buildInputs = lib.optional pythonSupport python
     ++ lib.optional (pythonSupport && python?isPy3 && python.isPy3) ncurses
+    ++ [ libintl ]
     # Libxml2 has an optional dependency on liblzma.  However, on impure
     # platforms, it may end up using that from /usr/lib, and thus lack a
     # RUNPATH for that, leading to undefined references for its users.
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 4d88c63bcfb..b862b1b78eb 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -13673,6 +13673,7 @@ in
 
   libxml2 = callPackage ../development/libraries/libxml2 {
     python = python3;
+    libintl = libintl;
   };
 
   libxml2Python = let
```

That got this error: 
```
output '/nix/store/7czx189wk20ss9yd1dw62s51r16fq83c-bootstrap-stage2-stdenv-darwin' is not allowed to refer to the following paths:
  /nix/store/f73jl5d5x4csv6n5p19643d35xly9hgm-gettext-0.20.1
  /nix/store/yqqpnmzvfmki829n705yw7b2x2vh3fyv-libiconv-osx-10.12.6
```

**Comment by dhess** [comment]
I've been getting this as well, since 2cd2e7267e5b9a960c2997756cb30e86f0958a6b.

@lnl7 Any clue? I think this sort of thing has happened before, but I don't recall the details.

**Comment by LnL7** [comment]
I thought somebody else already fixed this after some discussion no irc. My proposal was essentially the patch above but guarded for python2 only.
