### ISSUE TITLE
Wrong hash for libpam-fix-build-with-eglibc-2.16.patch

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#91434]
I am seeing this:
```
trying https://git.alpinelinux.org/cgit/aports/plain/main/linux-pam/libpam-fix-build-with-eglibc-2.16.patch?id=05a62bda8ec255d7049a2bd4cf0fdc4b32bdb2cc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0  16900      0 --:--:-- --:--:-- --:--:-- 16900
100    17  100    17    0     0   1214      0 --:--:-- --:--:-- --:--:--  1214
100   242  100   242    0     0   5902      0 --:--:-- --:--:-- --:--:--  5902
hash mismatch in fixed-output derivation '/nix/store/35sx1hbc4klaps39sxs3lcbynib44in3-libpam-fix-build-with-eglibc-2.16.patch?id=05a62bda8ec255d7049a2bd4cf0fdc4b32bdb2cc':
  wanted: sha256:1ib6shhvgzinjsc603k2x1lxh9dic6qq449fnk110gc359m23j81
  got:    sha256:1dp8p26sxdsi0abcar83gxl7w9jzcrrqah4r90zizzh79cb547n5
```

And indeed:
```
~/dfinity/nixpkgs $ nix-prefetch-url 'https://git.alpinelinux.org/cgit/aports/plain/main/linux-pam/libpam-fix-build-with-eglibc-2.16.patch?id=05a62bda8ec255d7049a2bd4cf0fdc4b32bdb2cc'
[0.0 MiB DL]
path is '/nix/store/35sx1hbc4klaps39sxs3lcbynib44in3-libpam-fix-build-with-eglibc-2.16.patch?id=05a62bda8ec255d7049a2bd4cf0fdc4b32bdb2cc'
1dp8p26sxdsi0abcar83gxl7w9jzcrrqah4r90zizzh79cb547n5
```
but https://github.com/NixOS/nixpkgs/blob/10b11fe5c819d92382ba06e095740da87dc60dd7/pkgs/os-specific/linux/pam/default.nix#L17-L20

(Something like this has bitten me occasionally. Is there a system in place to ensure that such hashes stay up to date, or URLs are changed to suitable copies?)

**Comment by nomeata** [comment]
Also, is there a work-around I can apply locally that is not patching `nixpkgs`?

**Comment by nomeata** [comment]
Unfortunately, not in http://tarballs.nixos.org/sha256/1ib6shhvgzinjsc603k2x1lxh9dic6qq449fnk110gc359m23j81

**Comment by veprbl** [comment]
I can't reproduce by building `builtins.elemAt pkgsMusl.pam.patches 1`. How are you executing the build?

The result of `fetchpatch` is normalized, so the has of the resulting file will not match the hash of the downloaded file. `nix-prefetch-url` is consistent with `fetchurl`.

**Comment by nomeata** [comment]
> I can't reproduce by building builtins.elemAt pkgsMusl.pam.patches 1. How are you executing the build?

This was somewhere deep in our CI, while building libc or something similarly deep as part of https://github.com/nh2/static-haskell-nix (which pins `nixpkgs` at 0c96026 – maybe that’s a difference)?

I don’t have the concrete log any more to see the precise derivation that causes this :-/

**Comment by nomeata** [comment]
Ah, probalby fixed in 751729914624e57888e85e6e178fc258db004d9an. sorry for the noise!
