### ISSUE TITLE
ZFS fails to build with latest kernel

### ISSUE THREAD

**Issue by mfsch** [NixOS/nixpkgs#91509]
**Describe the bug**
On 20.03, `linuxPackages_latest` now installs Linux 5.7. The available version of ZFS (0.8.3) as well as the latest version (0.8.4, available on the unstable channel) only support Linux 5.6, so upgrades currently fail when using ZFS and the latest kernel. It’s not the worst behavior since the error message basically states that ZFS only supports  <= 5.6, but it took me a bit of digging to figure out why my upgrade is failing on the stable NixOS. Is it possible to handle such incompatibilities in a cleaner way?

**To Reproduce**
1. set `boot.supportedFilesystems = [ "zfs" ];`
2. set `boot.kernelPackages = pkgs.linuxPackages_latest;`
3. upgrade to new configuration

**Expected behavior**
Perhaps an error message when Nix is reading the configuration?

**Additional context**
It looks like there have been [similar issues](https://github.com/NixOS/nixpkgs/issues/59770) before, though that was using unstable ZFS.

**Metadata**
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.18, NixOS, 20.03.2349.6460602eec5 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(mfsch): `"nixpkgs-20.09pre231837.2cd2e7267e5"`
 - channels(root): `"nixos-20.03.2349.6460602eec5"`
 - nixpkgs: `/home/mfsch/.nix-defexpr/channels/nixpkgs`
```

**Comment by jahkeup** [comment]
At build time, the `./configure` script prints the following which does indicate that this will require an upstream change to resolve:

```
checking whether make_request_fn() returns blk_qc_t... configure: error: 
        *** None of the expected "make_request_fn" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
        *** ZFS Version: zfs-0.8.3-1
        *** Compatible Kernels: 2.6.32 - 5.6
```

**Comment by mfsch** [comment]
That’s the message I meant with "the error message basically states that ZFS only supports <= 5.6", thanks @jahkeup for adding it!

**Comment by jahkeup** [comment]
Looks like there's a [check which was updated just prior to the zfs release](https://github.com/openzfs/zfs/commit/e6142ac0f28891a0ef3de366a45bb857a17ee25a) which is why we're seeing this message ([see `zfs-0.8.4` commit log](https://github.com/openzfs/zfs/commits/zfs-0.8.4)).

I suspect we could patch the check to unblock (re)builds after confirming compatibility and stability.

**Comment by jahkeup** [comment]
I mistook the [update to use `zfs-0.8.4`](https://github.com/NixOS/nixpkgs/commit/1b3825ebcbe7a855097208f579d09525cea94f72) to be released in the `nixos-20.03` channel. I was able to pull in this change and build the kernel module successfully. 

To me, this suggests that the `0.8.4` patchset (ie: the [mentioned change](https://github.com/NixOS/nixpkgs/commit/1b3825ebcbe7a855097208f579d09525cea94f72)) should be backported to `nixos-20.03`, tested, and then released to its channels. Otherwise, we'll be unable to use `kernelPackages_latest` with `zfs`.

**Comment by Atemu** [comment]
Fixed as of https://github.com/NixOS/nixpkgs/pull/92850

**Comment by mfsch** [comment]
Does this really fix the issue? In the [release notes of zfs-0.8.4](https://github.com/openzfs/zfs/releases/tag/zfs-0.8.4) it says that kernel versions up to 5.6 are supported, but `linuxPackages_latest` is version 5.7.

**Comment by Atemu** [comment]
It compiled on my machine. I'm running the ZFS test now to make sure but I don't see why it shouldn't work.

0.8.4 in unstable even works on 5.8.

**Comment by mfsch** [comment]
Ah, I thought ZFS had a build-time check for the kernel version (they still have `Linux-Maximum: 5.6` even in master), but I guess they only print that error message if some interface is found to be missing.

Still, it seems a bit strange to me to ship an unsupported combination (0.8.4 & 5.7) on a stable system, and it looks like the ZFS derivation already contains code for handling such a situation. It seems to me that `incompatibleKernelVersion = "5.7"` should be set for `zfsStable`, in which case users can decide whether to downgrade to 5.6 or opt in to an unsupported combination by using `zfsUnstable`. There’s a good chance that I’m wrong though since I’m still pretty new to Nix.

**Comment by Atemu** [comment]
If you wanted a super stable experience that's nearly guaranteed to work, you'd be using the regular linuxPackages and not opt into _latest. I think on stable these don't even get updated when a new LTS kernel is available.

Compatibility with the latest linux kernel from the ZFS side is usually added pretty quickly after the -rcs have stabilised a bit, so at most it should take a backport on our side when the kernel is actually released.

The zfsStable/Unstable packages aren't really used anymore I think. I haven't seen them being used the past year.

The breakage should've been noticed when _latest was set to 5.7 though and the ZFS fix backported before _latest was updated. Afaict 5.7 was backported outside the regular PR process oddly. Backporting the addition of a newer version that way would be fine by me but at updating _latest should be handled with greater care IMO.

Another interesting thought that just crossed my mind would be making _latest evaluate to the latest linuxPackages that work with all of your external modules for a true Just Works^TM experience but I'm not sure how trivial that'd be and ideally everything would be kept compatible to begin with.

**Comment by mfsch** [comment]
Thanks for the additional details! I guess it depends on how solid ZFS is for kernels that are not officially supported, and from the sound of it things are pretty stable.

I’m not sure having `latest` refer to different kernels based on the rest of the configuration is the way to go. If you just want the latest kernel that works with your setup that seems like a good solution, but if you need the latest kernel for e.g. hardware support, it could be difficult to figure out which of your settings is blocking the upgrade.
