### ISSUE TITLE
netdata: cloud streaming support

### ISSUE THREAD

**Issue by RaghavSood** [NixOS/nixpkgs#91549]
**Project description**

Netdata agent plugin 
**Metadata**

* homepage URL: 
* source URL: https://github.com/netdata/netdata
* license: GPL 3.0
* platforms: unix, linux, darwin

We already do have netdata, however it seems to be built without support for the cloud agent that allows it to stream to the cloud or other netdata servers.

**Comment by leotaku** [comment]
I have a local checkout with some edits that allow me to build netdata with cloud support. Unfortunately they also require a change in the libwebsockets build expression. Should I open a PR to integrate my changes into nixpkgs?

**Comment by RaghavSood** [comment]
@leotaku A PR would be great! I'm not a maintainer, but if they decide it's out of scope for nixpkgs, perhaps one on NUR might work - I'd try for a PR here first though

**Comment by leotaku** [comment]
Great, I think having a configuration option that is `true` per default would make sense. Maybe `withCloud`?

**Comment by RaghavSood** [comment]
Yeah, that seems to fall in line with the various `withXXX` flags present in other packages

**Comment by RaghavSood** [comment]
Upstream has incorporated some of the suggestions in this thread, I intend to pick up on it again soon

**Comment by wmertens** [comment]
@RaghavSood what would be needed to make this work? Perhaps I can help?

**Comment by leotaku** [comment]
@wmertens The newest major release of Netdata (1.30.0) includes a cloud link implementation without the need for censored dependencies. Unfortunately, it is not currently in a reliable state because of a bug in the custom HTTP implementation. The relevant fix has already been merged into Netdata master and will be included in the next release. I plan to make a PR that enables cloud support as soon as that release is available.

**Comment by wmertens** [comment]
@leotaku v1.31.0 dropped 12 minutes ago :) Anything I can do to help?

**Comment by leotaku** [comment]
@wmertens Thanks, I've already gotten a notification for that. Planning to draft a PR when I get off work today.

**Comment by leotaku** [comment]
@wmertens Just FYI, I have opened the PR that enables cloud support a few days ago. If you are still interested it would be greatly appreciated if you could test if everything works for you and maybe drop a comment.

**Comment by wmertens** [comment]
Sorry, missed this but the pr looks good! I propose we backport this to stable?
