### ISSUE TITLE
RStudio fails to build plugins downloaded from plugins repository

### ISSUE THREAD

**Issue by mucaho** [NixOS/nixpkgs#9163]
Reason: It can't find `make`.
Adding `gnumake` to my user environment solved the issue, thus I think this issue could be solved by adding a (update: runtime-) dependency to `gnumake` to the nix expression of RStudio.
cc @ehmry

~~Hold on, there are some additional errors, will investigate.~~ **UPDATE:**
Managed to resolve the issues while trying to install `rgdal` plugin from CRAN:
* first make sure that `gdal` is installed in your user environment
* next make sure that `proj` is installed in your user environment
* then make sure to provide additional configure options when installing `rgdal` in RStudio:
   * `whereis proj` to get the nix store location `proj`, strip the last part `/bin/proj`
   * type `install.packages('rgdal', type = "source", configure.args=c('--with-proj-include=/<NIX-STORE-PROJ>/include','--with-proj-lib=<NIX-STORE-PROJ>/lib'))` in RStudio console, replacing the location accordingly
   * credits to [http://stackoverflow.com/a/26836125/3041008](http://stackoverflow.com/a/26836125/3041008)

**Comment by ehmry** [comment]
I packaged rstudio for a friend and haven't used it much since, so I'm actually not that familiar with it or CRAN.

**Comment by peti** [comment]
This makes no sense. `make` is part of our standard environment; that tool cannot possibly be missing from the build.

**Comment by mucaho** [comment]
> `make` is part of our standard environment, that tool cannot possibly be missing from the build

We are talking about runtime dependency here when you want to install additional plugins after RStudio has been installed, not the actual build time of RStudio. `make` is not available in my terminal (and thus probably also not available to RStudio) without an explicit `nix-env -i gnumake`

**Comment by stites** [comment]
+1
