### ISSUE TITLE
Make gtk3 the default gtk

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#9164]
Support should be included in many common applications and this is the future direction as dictated by gnome. In firefox this seems to be a performance win and makes it more usable on hiDPI displays. These improvements should translate to other gtk2 -> gtk3 applications.

**Comment by vcunat** [comment]
I believe most packages shouldn't use the unversioned `gtk` attribute. Maybe for those actually supporting both, but that seems rare and often the expression needs other changes, so it seems better to provide "switching" between the two possibilities by a separate flag anyway.

**Comment by wkennington** [comment]
This is what I was hoping for, using gtk3 where possible and gtk2 only
where needed.

**Comment by jtojnar** [comment]
Superseded by #18559
