### ISSUE TITLE
steam try to update at every start, preventing offline lauch

### ISSUE THREAD

**Issue by marius851000** [NixOS/nixpkgs#91670]
**Describe the bug**
Since I first used steam on nixos, it try to update every time I start to lauch it. This include when I am offline, making it refusing to start, as it can't connect to internet to update, and offer no way to not update it.

**To Reproduce**
When online, run `nix-shell -p steam --command steam`, and connect to an account.
close steam
stop the internet connection
run `nix-shell -p steam --command steam`
steam refuse to start, after trying to extract package, saying "Fatal Error: Steam needs to be online to update. Please confirm your network connection and try again".

**Expected behavior**
Steam open a pop-up saying I am offline, but allow me to proceed anyway.

**Additional context**
The game I want to play offline is a proton game, but it have bugs with vanilla wine, and proton refuse to work due to missing steam (I use smartsteamemu for both vanilla wine and proton).

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.4, NixOS, 20.09pre231796.22a81aa5fc1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - channels(marius): `"home-manager, mariusnur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module:
```

**Comment by L-as** [comment]
I don't think this is an issue with NixOS. This happens on other distros too AFAIK.

**Comment by vcunat** [comment]
Hmm, I agree this doesn't sound distro specific.  Now I just tried once and the dialog showed (same as I remember from many months ago) and it started up fine in offline mode afterwards.  I'm not sure what's different in your case, maybe it only gets blocked if it hasn't been online for too long.

**Comment by marius851000** [comment]
It seem that switching to offline mode in the steam menu doesn't solve this problem. I'll try to remove the .steam folder.

**Comment by marius851000** [comment]
That actually solved the problem (should have tried that first). Thank anyway.
