### ISSUE TITLE
Packaging requests: `lossless-cut`

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#91685]
**Project description**
_LosslessCut the swiss army knife of lossless video/audio editing that makes use of FFmpeg_
A ready-to-merge binary build: #108512 
The draft PR for the source-build: #91683

<img src=https://github.com/mifi/lossless-cut/raw/v3.23.7/main_screenshot.jpg width=75% />

**Metadata**

* homepage URL: https://mifi.no/losslesscut
* source URL: https://github.com/mifi/lossless-cut
* license: mit
* platforms: unix

**Comment by romildo** [comment]
I still would like to have this application in nicolas.

**Comment by ShamrockLee** [comment]
lossless-cut-bin is now in pr #108512

Considering the time and effort it would take to build from source, I made the binary package first.

**Comment by ryneeverett** [comment]
Resolved via #108512.
