### ISSUE TITLE
ledger: 3.1.3 -> 3.2.*

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixpkgs#91702]
It looks like [upstream ledger has had a new release](https://github.com/ledger/ledger/releases), which among other things ports to python3.  It'd be great to update the package version in NixPkgs.

I gave it a shot myself, but it looks like there are some CMake changes the expression will need to adapt to; maybe someone closer has better context.

CC maintainer @jwiegley

**Comment by purcell** [comment]
This appears to have been addressed by @jonringer in c9c8acf, though I'm finding it doesn't build on Darwin, so I'll open a separate issue for that.

**Comment by jonringer** [comment]
I was bored, so I did the bump :)

**Comment by bhipple** [comment]
Wow, thanks @jonringer !
