### ISSUE TITLE
callPackage_i686 is counter-intuitive with parameter overrides

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#9170]
When one uses

```
foopkg = callPackage_i686 ../foopkg {
  barpkg = barpkg_baz;
}
```

the barpkg is a 64-bit version. Currently I don't see how to improve it.

**Comment by peti** [comment]
`barpkg_baz` is resolved in the package set that contains `callPackage_i686`, not in the one that `callPackage_i686` constructs to resolve implicit arguments. It's not easy to remedy that without change the functions signature, IMHO.

**Comment by vcunat** [comment]
Yes, I thought there might be some different way to have 32-bit overrides.

**Comment by peti** [comment]
The function could pass the 32-bit package set as an argument to another function that returns the override -- like `ghcWithPackages` does.

**Comment by Profpatsch** [comment]
(triage) status?

**Comment by alexozer** [comment]
(triage) status?

**Comment by vcunat** [comment]
I wouldn't expect any changes.  Let me close it.  It would be rather hard to remedy and the improvement wouldn't be *that much* useful anyway.
