### ISSUE TITLE
yaru: no shell theme (for GNOME Shell)

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#91710]
**Describe the bug**

Yaru theme does not appear in shell theme selection menu in Gnome Tweaks tool.

**To Reproduce**

1. Install `yaru-theme`
2. Using GNOME Desktop, open Gnome Tweaks and on the Appearance page look for Yaru in Shell theme selection.

**Expected behavior**

I expect Yaru theme to be available for Shell. On Ubuntu 20.04 i have a choice between "Default" and "Yaru Dark".

**Screenshots**

![Gnome Tweaks Window](https://user-images.githubusercontent.com/712698/85943095-0d3da780-b92e-11ea-984f-d432186119e9.png)

**Additional context**

...

**Notify maintainers**

@jD91mZM2 

**Metadata**

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.48-hardened, NixOS, 20.03.2351.f8248ab6d9e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3238.e984f9e48e1"`
 - channels(root): `"nixos-20.03.2351.f8248ab6d9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Links**

`nixpkgs/pkgs/data/themes/yaru/default.nix`:

 * [Latest version in `release-20.03`](https://github.com/NixOS/nixpkgs/blob/release-20.03/pkgs/data/themes/yaru/default.nix)
 * [Latest version in `master`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/themes/yaru/default.nix)

**Comment by jD91mZM2** [comment]
Hmm, I don't personally use GNOME, but I guess you could try passing the `gnome-shell` option (`-Dgnome-shell` I think) to the meson flags somehow: [source](https://github.com/ubuntu/yaru/blob/95718a3508235c1f855a614e424958a62f7bf6d4/meson.build#L8-L17)

**Comment by lourkeur** [comment]
Seems like it's really just a missing symlink. I managed to fix it. It also does not affect master, only 20.03.

**Comment by lourkeur** [comment]
Note that the Yaru-Dark gnome-shell theme is not present in this package either so you might just want to install yaru-theme from the unstable channel and be done with it.

**Comment by alexeymuranov** [comment]
#91901 : Thanks @lourkeur !

Why is master not affected? Is it because of some change between Yaru 19 and Yaru 20?

**Comment by lourkeur** [comment]
@alexeymuranov Yes, upstream added a script to make those links in 20.04.1 and no sooner.

https://github.com/ubuntu/yaru/commits/master/gnome-shell/src/install-shell.sh

**Comment by jtojnar** [comment]
Thanks. Merged.
