### ISSUE TITLE
services.searx.enable throws a werkzeug.contrib error in unstable

### ISSUE THREAD

**Issue by emilysnow2477** [NixOS/nixpkgs#91739]
Steps to reproduce: 
1) Set `services.searx.enable` to true.
2) `doas nixos-rebuild switch`

It also seems to happen when using `nix-shell -p searx`. 

Version: `20.09pre231796.22a81aa5fc1 (Nightingale)`
Kernel: 5.7.4
Architecture: x86_64
Pastebin: http://ix.io/2qqP

**Comment by aciceri** [comment]
Same problem here, moreover I noticed that the module simply starts `searx-run`, which means that the builtin python web server is used, which is recommended only for debug purposes.
Maybe this is not the correct place to talk about this, I could open an issue but I don't think to personally have the skills to fix it.

**Comment by emilysnow2477** [comment]
I read more about this. Seems #72345 is the culprit. There also appears to be <a href=https://github.com/pallets/werkzeug/pull/1242#issuecomment-629678431>someone looking into it</a>. 

I'm closing this issue as it's not specific to just searx.
