### ISSUE TITLE
nut: nut-scanner can't find dynamic libraries at runtime

### ISSUE THREAD

**Issue by lodi** [NixOS/nixpkgs#91730]
**Describe the bug**
Network UPS Tools (`nut`), ships a `nut-scanner` binary to enumerate currently connected power devices.  On my system `nut-scanner` looks for libraries like `libusb-0.1.so` in hardcoded paths like `/usr/lib64` and fails to find them.  I see that the `nut` package wraps the `nut-scanner` binary to override `LD_LIBRARY_PATH` with correct values, but `nut-scanner` loads these libraries manually with `lt_dlopen` and doesn't seem to respect `LD_LIBRARY_PATH`.

**To Reproduce**
```
> nix-shell -p nut
$ nut-scanner
USB library not found. USB search disabled.
Neon library not found. XML search disabled.
AVAHI client library not found. AVAHI search disabled.
IPMI library not found. IPMI search disabled.
No start IP, skipping NUT bus (old connect method)

$ strace nut-scanner
...
openat(AT_FDCWD, "/nix/store/yzs5y9sr5i6s4b7awln4ng8j9bamd09x-nut-2.7.4/lib", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0555, st_size=16, ...}) = 0
brk(NULL)                               = 0x1839000
brk(0x185a000)                          = 0x185a000
getdents64(3, 0x18392d0 /* 16 entries */, 32768) = 608
getdents64(3, 0x18392d0 /* 0 entries */, 32768) = 0
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
write(2, "USB library not found. USB searc"..., 44USB library not found. USB search disabled.
) = 44
...
```

**Expected behavior**
`nut-scanner` should be able to load libraries at runtime from dependencies like `libusb-compat-0_1`.

**Additional information**
As a quick and dirty test, I added `libusb-compat-0_1` to my systemPackages, added an overlay to a local copy of the nut source...

```
self: super: {
  nut = super.nut.overrideAttrs(oldAttrs: {
    src = ~/Downloads/nut-2.7.4;
  });
}
```

... and directly patched the nut-scanner source to look in `/run/current-system`.

```
// nut-scanner/nutscan-init.c:46
char * search_paths[] = {
	LIBDIR,
	"/usr/lib64",
	"/lib64",
	"/usr/lib",
	"/lib",
	"/usr/local/lib",
        "/run/current-system/sw/lib",
	NULL
};
```

This allowed `nut-scanner` to find `libusb-0.1.so` and proceed with USB support.  I'm not sure what the proper fix would be though.

**Notify maintainers**
CC @nbp 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.47, NixOS, 20.09pre231796.22a81aa5fc1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by flokli** [comment]
I quickly googled for `lt_dlopen`, and found http://doc.gnu-darwin.org/autobook/autobook_165.html, which seems to suggest it honors `LTDL_LIBRARY_PATH`.

However, setting `{LTDL,LD}_LIBRARY_PATH` in a wrapper is discouraged, as it propagates through to binaries executed by the wrapped binary.

As we build from source here, any chance we could get the build system to add these paths to the binaries' `RUNPATH`?
Otherwise, you probbaly should use patchelf to do that, instead of wrapping.

**Comment by lodi** [comment]
LTDL_LIBRARY_PATH doesn't seem to work either.  The GNU docs state that "If filename is not an absolute path...", and nut-scanner constructs absolute paths based on the prefixes below:

```
/* FIXME: would be good to get more from /etc/ld.so.conf[.d] */
char * search_paths[] = {
	LIBDIR,
	"/usr/lib64",
	"/lib64",
	"/usr/lib",
	"/lib",
	"/usr/local/lib",
	NULL
};

...

snprintf(current_test_path, LARGEBUF, "%s/%s", search_paths[index], dirp->d_name);
```

**Comment by flokli** [comment]
@lodi brr, I don't understand why they implemented their own dynamic linker.

I'd propose reaching out to upstream, if some of that behaviour can be changed - otherwise, we could ship a patch downstream in nixpkgs, replacing some of the paths with dependencies (patch replacing with placeholder, `substituteAll` before applying, like done in the `bazel` derivation)

**Comment by lodi** [comment]
Yeah it's strange that they did it this way, especially since libtool provides an lt_dladdsearchdir() function that I think would take care of all this.

There's one other nix-related thing I don't understand.  I modified the nut-scanner source to look for "libusb-0.1.so" (with no leading directory) which now allows libtool to automatically search LD_LIBRARY_PATH.  However, it still doesn't find anything.  It only works if I use "libusb-0.1.so.4" instead.  Looking at the contents of the libusb derivation, it indeed doesn't have any "libusb-0.1.so -> libusb-0.1.so.4" symlinks.

@flokli, any idea how I can handle this cleanly?

**Comment by flokli** [comment]
I think these links symlinks don't matter too much if build systems ask pkg-config about which library to link against. For `libusb`:

```
❯ nix-shell -p pkgconfig -p libusb

[nix-shell:~]$ pkg-config --libs libusb
-L/nix/store/kjw25n365v4iw4n399dmpphrx197fs89-libusb-compat-0.1.5/lib -lusb

[nix-shell:~]$ pkg-config --libs-only-l libusb
-lusb
```

This means it'll look for `libusb.so`.

**Comment by flokli** [comment]
This probably won't help us here, though - we can't really reuse the output of `pkgconfig` to update the patches.

Can you get their build system to discover things with pkgconfig? Otherwise, probably just hardcoding (and waiting for it to break again) might be fine.

In any case, I'd encourage opening an issue upstream. Not honoring `LD_LIBRARY_PATH`, `RUNPATH` etc. and instead just writing your own logic sounds like a bug to me.

**Comment by lodi** [comment]
Okay, sorry for the delay.  I just opened [#805](https://github.com/networkupstools/nut/issues/805) with upstream.

**Comment by jakubgs** [comment]
This is still an issue:
```
 > /nix/store/h3l3m38hw04wif0j3axf1nrb86l79cw3-nut-2.7.4/bin/nut-scanner -C
USB library not found. USB search disabled.
Neon library not found. XML search disabled.
AVAHI client library not found. AVAHI search disabled.
IPMI library not found. IPMI search disabled.
No start IP, skipping NUT bus (old connect method)
```
And I guess the maintainers do not want to support `LD_LIBRARY_PATH`. So what are some other options?

**Comment by winny-** [comment]
Confirming this is still an issue

```
[root@stargate:~]# nut-scanner -C
USB library not found. USB search disabled.
Neon library not found. XML search disabled.
AVAHI client library not found. AVAHI search disabled.
IPMI library not found. IPMI search disabled.
No start IP, skipping NUT bus (old connect method)

```

**Comment by flokli** [comment]
Can someone using this try https://github.com/networkupstools/nut/issues/805#issuecomment-1210805036 and report back?

**Comment by lodi** [comment]
@flokli, yes it works.  Tracking the packaging update in #170930.
