### ISSUE TITLE
Package request: firefly-iii

### ISSUE THREAD

**Issue by tobkratz** [NixOS/nixpkgs#91741]
**Project description**
"Firefly III" is a (self-hosted) manager for your personal finances. It can help you keep track of your expenses and income, so you can spend less and save more. Firefly III supports the use of budgets, categories and tags. It can import data from external sources and it has many neat financial reports available.

**Metadata**

* homepage URL: https://www.firefly-iii.org/
* source URL: https://github.com/firefly-iii/firefly-iii
* license:  AGPL-3.0 License
* platforms: unix, linux

**Comment by asbachb** [comment]
I'd be interested in a packaging as well.

**Comment by eliasp** [comment]
See https://github.com/NixOS/nixpkgs/pull/184362

**Comment by tyleroconnell** [comment]
@DavideFauri @asbachb @aaronjanse @haztecaso @Avaq @eliasp @Stunkymonkey it looks like you're interested in this too, do you by chance know who might be able to review #184362?

**Comment by stackcoder** [comment]
The firefly-iii package and service module were already merged to unstable. #302136
Could this issue be close?
