### ISSUE TITLE
nixos/networkd: cannot use the option DNSDefaultRoute=

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#91761]
**Describe the bug**
I cannot use the option `DNSDefaultRoute=` in [`systemd.network.networks.<name>.networkConfig`](https://nixos.org/nixos/manual/options.html#opt-systemd.network.networks._name_.networkConfig).

**To Reproduce**
1. Set `systemd.network.networks.<name>.networkConfig = { DNSDefaultRoute = true; };`
2. Notice the error message `Systemd Network has extra fields [DNSDefaultRoute].`

**Expected behavior**
We should be able to use the option `DNSDefaultRoute=`.

**Additional context**
The problem seems to originate from the following *stale* assertion: https://github.com/NixOS/nixpkgs/blob/e0f4ee72bc08beb30b840d662b2ded5a9b0888a3/nixos/modules/system/boot/networkd.nix#L199

**Notify maintainers**
@arianvp @flokli @andir 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.49, NixOS, 20.03post-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- nixos/networkd
```

**Comment by datafoo** [comment]
There are more options missing and not only for the "[Network]" section of .network files.

I can submit a PR that updates options according to the man pages. Would that be OK?

That means I would remove some options that do not appear in the man page. For example, `OriginalName` is one of them (cf https://github.com/NixOS/nixpkgs/commit/aa251bbc3e39e19cb9a897793e66d6d3edb940d6). @eadwu: I cannot find the option `OriginalName` in the `[LINK] SECTION OPTIONS` of the `man systemd.link` for `systemd 245`. Am I missing something?

**Comment by eadwu** [comment]
https://github.com/NixOS/nixpkgs/pull/66703#issuecomment-521865138

If it was changed, it should be updated.

**Comment by datafoo** [comment]
> [#66703 (comment)](https://github.com/NixOS/nixpkgs/pull/66703#issuecomment-521865138)
> 
> If it was changed, it should be updated.

I can see that it was changed but why? `OriginalName` is not part of the `[Link]` section of the .link files but `Name`is. Actually @fooker and @Lassulus put `Name` back into it [later](https://github.com/NixOS/nixpkgs/commit/943508a7fa95ce6aa8f14a9a717881e436b3816e).

Can you confirm it is OK to revert the changes made in commit https://github.com/NixOS/nixpkgs/commit/aa251bbc3e39e19cb9a897793e66d6d3edb940d6?

**Comment by datafoo** [comment]
I started to work on a PR but I would like some feedbacks on what is best to do.

Currently master is using systemd 254 so I am basing my work on the man pages of this version. But let's take the example of this recent change https://github.com/systemd/systemd/commit/de697db05b08464180af4a257f6df88b00d60b9e.

Should I leave the possibility to use the old `PrefixRoute=` option so that NixOS users can use the module with an older systemd version? If yes, what is the oldest version of systemd that we should support? 

Or should I only allow the new `AddPrefixRoute=` option in v245 and remove `PrefixRoute=`?

You may see where I am going here, the tight control of this module makes it lack flexibility.

@flokli: I see you [migrated](https://github.com/NixOS/nixpkgs/commits/master/pkgs/os-specific/linux/systemd/default.nix) to newer versions of systemd. I imagine you have valuable inputs on this?
@wkennington: you [added](https://github.com/NixOS/nixpkgs/commit/045132a9b096a22cb6f84210fcd5223b9a770d62) the assertions, any thoughts on this?

**Comment by Ma27** [comment]
> Should I leave the possibility to use the old PrefixRoute= option so that NixOS users can use the module with an older systemd version? If yes, what is the oldest version of systemd that we should support?

IMHO we should only support the options that the `systemd` package of the *same* nixpkgs checkout supports.

**Comment by flokli** [comment]
Usually, systemd upstream tends to keep old names for backwards compat (but removes them from the docs). This is mostly to not silently break units written while an older systemd was around.

Being able to use the docs to generate some of the field name validators sounds nice. We'd a bit more strict on not supporting "maintance-mode only config", but nudging people to not use config keys anymore that arent documented probably isn't a bad idea either ;-)

Regarding https://github.com/NixOS/nixpkgs/commit/aa251bbc3e39e19cb9a897793e66d6d3edb940d6: I assume there was some confusion between Match.OriginalName and Link.Name. I don't think `Link.OriginalName` is a valid field (or ever was (?)), so we shouldn't allow it IMHO.
