### ISSUE TITLE
tbb doesn't come with cmake files

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#91773]
**Describe the bug**
Tbb doesn't come with any information on how to link against it (neither pkgconfig files nor cmake files). The upstream project defines cmake files to make linking against it easier. Naturally third parties rely on this in their own cmake files. Not shipping them in the nix derivation introduces additional hassle to package software from said third parties.

Would it be a possibility to ship the cmake files together with tbb?

**Notify maintainers**

@thoughtpolice 
@DIzFer

**Comment by foolnotion** [comment]
The following override works with `2020_U3`, but fails with `2021.1.1`:

```nix
  tbb = pkgs.tbb.overrideAttrs (old: rec {
    version = "2020_U3";

    src = pkgs.fetchFromGitHub {
      owner = "01org";
      repo = "tbb";
      rev = "${version}";
      sha256 = "0r9axsdlmacjlcnax4vkzg86nwf8lsx7wbqdi3wnryaxk0xvdcx6";
    };

    installPhase = old.installPhase + ''
        ${pkgs.cmake}/bin/cmake \
            -DINSTALL_DIR="$out"/lib/cmake/TBB \
            -DSYSTEM_NAME=Linux -DTBB_VERSION_FILE="$out"/include/tbb/tbb_stddef.h \
            -P cmake/tbb_config_installer.cmake
    '';
  });
```

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/122587 added a pkg-config file.

**Comment by wucke13** [comment]
@jtojnar Thank you, that settles it.
