### ISSUE TITLE
python3Packages.opencv4 missing the UMat type

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#91791]
**Describe the bug**
When trying to access GPU acceleration from OpenCV's python bindings, the UMat type does not exist, even though OpenCV is clearly built with OpenCL support and the OpenCL runtime is detected correctly by `opencv_version --opencl`

**To Reproduce**
1. `nix-shell -p python3 python3Packages.opencv4 --run python3`
2. `import cv2; help(cv2.UMat)`

**Expected behavior**
The documentation of the UMat class is displayed

**Actual behaviour**
`AttributeError: module 'cv2' has no attribute 'UMat'`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.4, NixOS, 20.09pre231796.22a81aa5fc1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.opencv4
```

**Comment by jansol** [comment]
The problem might not be limited to OpenCL, yes. I have not tested with other backends so can't say for sure though.

**Comment by tpwrules** [comment]
I found the problem at this line:

https://github.com/NixOS/nixpkgs/blob/13a3e5023192b62d6c5662c37549d8bb9e5e6a28/pkgs/development/libraries/opencv/4.x.nix#L175 

The patch causes `modules/python/src2/gen2.py` to skip over `modules/core/misc/python/shadow_umat.hpp` which contains the actual definition of UMat used by the Python bindings. I commented out that line and everything works now. It appears the original issue #26304 mentioned in the comments was fixed another way in the meantime as `enableContrib = true` builds and works too.

I'm not sure of the overall implications of just removing this line. Maybe an exception for that specific file should be added instead? By the way, the 3.x version has the same problem and solution.

Maintainers, do you have any input? I can submit a PR to just cut out that line. @mdaiter @basvandijk
