### ISSUE TITLE
Hydra farm: bad state of aarch64 builders - blocking nixos-20.03 channel

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#91816]
In particular, [I've been unable](https://hydra.nixos.org/build/123127187#tabs-buildsteps) to make the default kernel build, but on the community aarch64 machine it built just fine.

Unfortunately I have no idea what's wrong; the logs themselves don't seem to show any error, but it could be e.g. some form of resource exhaustion.

**Comment by srhb** [comment]
All channels advanced < 17 hrs ago. Not sure if that means problems are fixed, or we just got lucky, but there we go. :)

**Comment by vcunat** [comment]
The success rate did seem to change significantly after around half a day.  I have no idea why, but I suppose I'll close this, for now at least.
