### ISSUE TITLE
setting LD_LIBRARY_PATH breaks meld, ansible, possibly any Python app in Nixpkgs that use lib-dynload

### ISSUE THREAD

**Issue by tril0byte** [NixOS/nixpkgs#9186]
export LD_LIBRARY_PATH=/usr/lib
/usr/lib contains libpython2.7.so

meld (with no arguments) fails with:
Traceback (most recent call last):
  File "/nix/store/9nmwbn4qlkr19mxv6qkdqcmkjblb86xv-meld-3.12.3/bin/..meld-wrapped-wrapped", line 22, in <module>
    import locale
  File "/nix/store/5aq9sjd0g4frmpqni0a6zykzkcnzc3al-python-2.7.9/lib/python2.7/locale.py", line 18, in <module>
    import operator
ImportError: /nix/store/5aq9sjd0g4frmpqni0a6zykzkcnzc3al-python-2.7.9/lib/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString

ansible (when called with any arguments or no arguments) fails with:
Traceback (most recent call last):
  File "/nix/store/y9c69z1iyfnxxfzv0h4v64cx6lvfad45-ansible-1.9.1/bin/.ansible-wrapped", line 37, in <module>
    from ansible.runner import Runner
  File "/nix/store/y9c69z1iyfnxxfzv0h4v64cx6lvfad45-ansible-1.9.1/lib/python2.7/site-packages/ansible/runner/__init__.py", line 25, in <module>
    import tempfile
  File "/nix/store/ss1aq46xwhnqikq5bjs02sb9xrim2bb3-python-2.7.10/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/nix/store/ss1aq46xwhnqikq5bjs02sb9xrim2bb3-python-2.7.10/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /nix/store/ss1aq46xwhnqikq5bjs02sb9xrim2bb3-python-2.7.10/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException

I believe the compiled python .so files are being linked with the system libpython2.7.so in this case.
I expect environment variables set in my shell not to interfere with the operation of these packages.
I expect it is a bug that they break when the variable is set.

**Comment by vcunat** [comment]
Why shouldn't programs break when you set such an `LD_LIBRARY_PATH`? I believe you can "break" any program on any regular distro by these flags (`LD_PRELOAD` is probably even better for that purpose).

**Comment by copumpkin** [comment]
I could see an argument for wrapper scripts unsetting most environment variables (with a whitelist) before running the wrapped executables.

**Comment by vcunat** [comment]
Just beware that we need it for libGL, which may well be used by libs like cairo.

**Comment by copumpkin** [comment]
@vcunat you need `LD_LIBRARY_PATH` to pass through the wrapper from the caller? Or just the ability to set it for a given execution?

**Comment by edolstra** [comment]
It needs to be passed through. On NixOS, `LD_LIBRARY_PATH` is set to `/run/opengl-driver/lib` so that the run-time configured OpenGL implementation (like the nvidia driver) is used instead of Mesa.

**Comment by copumpkin** [comment]
Ah, I see. Seems like a function in disguise!

**Comment by vcunat** [comment]
Yes, it's an intentional impurity. The wrapper could hardcode it to the value NixOS normally sets, so you wouldn't be able to override it. Thinking of this, we might just get rid of it, i.e. rewrite `${mesa_noglu}` in RPATH to `/run/opengl-driver*`. That might also typically remove the actual runtime dependency on libGL (which is unused normally and subsumed by the NixOS one).

**Comment by copumpkin** [comment]
All I meant is that it feels like this sort of thing would be captured "naturally" (probably a pain in practice) by having something like:

```nix
{ stdenv, dep1, dep2 }:

let 
  pkg = stdenv.mkDerivation {
    buildInputs = [ dep1 dep2];
  };
in { runtimeDep1, runtimeDep2 }:
mkWrapperOverriding pkg [ runtimeDep1 runtimeDep2 ]
```

And then you can do most of the work "up front" using the compile-time dependency. At runtime, the wrapper would let you override the dependency without rebuilding the whole thing.

**Comment by vcunat** [comment]
I actually thought a pattern like the above might be generated by just specifying `wrapPhase`. Anyway, if some *library* needs "being wrapped" (e.g. cairo), it's getting complicated.

**Comment by vcunat** [comment]
I believe there are a few special vars that just should matter, e.g. LD_PRELOAD, etc.
