### ISSUE TITLE
firestarter: hash mismatch

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#91866]
**Describe the bug**

7110bf59e9fa7e867ded61a1199b475c8451b8ef

```
building '/nix/store/miamjhr86rsx5l494jmhskyakmm22i1l-source.drv'...

trying https://github.com/tud-zih-energy/FIRESTARTER/archive/v1.7.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134  100   134    0     0    572      0 --:--:-- --:--:-- --:--:--   572
100 79570    0 79570    0     0   114k      0 --:--:-- --:--:-- --:--:--  857k
unpacking source archive /build/v1.7.4.tar.gz
hash mismatch in fixed-output derivation '/nix/store/ifh785pzf4zf9y7lhrnvm7kyj0drihw1-source':
  wanted: sha256:161mg0h1hvp6bxfjdhyfqrljvphys896mfd36254rbgzxm38ibi7
  got:    sha256:0zqfqb7hf48z39g1qhbl1iraf8rz4d629h1q6ikizckpzfq23kd0
cannot build derivation '/nix/store/y3bb96h3cx39pphm1q5l53gm9rsac3wq-firestarter-1.7.4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/y3bb96h3cx39pphm1q5l53gm9rsac3wq-firestarter-1.7.4.drv' failed
```

I don't know if we should just update it or not.

**To Reproduce**
1. `nix-build -A firestarter` on master

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**
@astro

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.47, NixOS, 20.09pre231796.22a81aa5fc1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(bbigras): `"home-manager, unstable-20.09pre231796.22a81aa5fc1"`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
* I can reproduce the issue locally
* It used to build previously https://github.com/NixOS/nixpkgs/pull/72334#pullrequestreview-309790046
* The current `firestarter.src` is not in the Hydra cache because `firestarter` was never built by Hydra, so, unless someone else has the `/nix/store/az95sr2aj3rcwyhp3wxy84zyx88x5kcy-source`, we can't compare
* Upstream tag doesn't appear to be updated, git repo doesn't use export-subst

It is not clear to me what has happened here.

**Comment by marenz2569** [comment]
Dear all,
the tag v1.7.4 has been changed after October 2019. It was not published for long as it involuntarily got into a commit. There have been no public releases for v1.7.4 marked on Github or our the FIRESTARTER Website as of October 2019.

**Comment by bbigras** [comment]
Thanks everyone for the help. :heart:
