### ISSUE TITLE
mutableUsers is named confusingly

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#9192]
You can't know if "true" means NixOS can mutate users, or if you can do it yourself.
Something like users.declarative would be more clear I think.

@cillianderoiste also said he found the name confusing.

**Comment by robbinch** [comment]
I must admit I find this confusing too.

**Comment by pSub** [comment]
I was never confused about this, but I see how this can be confusing. :+1: for something like `users.declarative`.

**Comment by edolstra** [comment]
Note that in either mode NixOS supports declarative user accounts. It's just that in `mutableUsers = false`, it *only* has declarative users.

**Comment by bjornfor** [comment]
Suggestion: ```users.onlyDeclarative```

**Comment by magnetophon** [comment]
I like @bjornfor his suggestion. Totally self-explanatory.

**Comment by lethalman** [comment]
I kind of like @bjornfor name too, too simple english but also needed for clarity.

**Comment by Profpatsch** [comment]
(triage) I don’t see what is confusing about the term, but if nobody goes forth and submits a PR I’m gonna close.

**Comment by wmertens** [comment]
I like `onlyDeclarative` too, anybody up for making that the documented default and making `mutableUsers` an alias?

**Comment by Profpatsch** [comment]
> making mutableUsers an alias?

reminds me, we don’t have a good deprecation scheme yet. I’d be in favor of actually deleting deprecated stuff after a while (that is with the next official release) and keeping aliases to an absolute minimum.
