### ISSUE TITLE
z3: Add Java bindings

### ISSUE THREAD

**Issue by lorenzleutgeb** [NixOS/nixpkgs#91939]
I saw that there are [derivations related to Z3](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/science/logic/z3), which is nice. The current version of the derivation for `z3` builds bindings for C, C++ (these two are always enabled) and Python (explicitly enabled the derivation, by [passing `--python` to `mk_make.py` in the configure phase](https://github.com/NixOS/nixpkgs/blob/5168c4de2d6574d5f6a71bab9450bce2037dacff/pkgs/applications/science/logic/z3/default.nix#L19)).

According to the [`README.md` of the Z3 Project](https://github.com/Z3Prover/z3/tree/17b8db95c18897614fff1b9ce3ef9d76972308b5#z3-bindings) there are multiple other bindings (.NET, Java, ML, Julia, WebAssembly).

I am working on a scientific project that uses Z3 and want to set it up on NixOS. Specifically, I need the **Z3 bindings for Java**.

So, I'd like to get the Z3 bindings for Java into Nixpkgs in some form:
 1. I could change the [`z3`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/logic/z3/default.nix) derivation to also build Java bindings by adding `--java` and moving the generated file(s) accordingly. The Java bindings are in no way more or less special than the Python bindings, so I'd prefer doing it this way.
 2. I could add another derivation, say `z3-java`, that will just provide `${lib}/libz3java.so`, and could re-use parts of `z3`, like `z3-tptp` does.
 3. Add `javaPackages.z3` which brings JAR and shared library (there are `{haskell,python}Packages.z3` but I think that they will only bring the Haskell/Python part of the bindings, not the shared library).
 4. Suggest something! 

Just as inspration: [Fedora](https://src.fedoraproject.org/rpms/z3/blob/ffaa2f2743a0335ee808c2a950d81d1b9d10da40/f/z3.spec#_60-89) has `{java,python}-z3` and `ocaml-z3{,-devel}`. And [Ubuntu](https://launchpad.net/ubuntu/+source/z3/4.8.8-1) has `libz3-j{ni,ava}` (`*jni` contains the shared library and `*java` contains the JAR as far as I can see) and `python3-z3`.

CC: @thoughtpolice and @7c6f434c since you are the maintainers of the Z3 related derivations.

**Comment by 7c6f434c** [comment]
If Java support is an expression option, a couple of optional dependencies, and a few flags here and there — I am for the first option.

**Comment by lorenzleutgeb** [comment]
@7c6f434c Cool, thanks for the quick feedback. I am new to nix, so please excuse me, but do you mean to implement something analogous to, say [`sslSupport` in `mutt`](https://github.com/NixOS/nixpkgs/blob/391c2778d4ad9cc5167387d788041c1b53be97f6/pkgs/applications/networking/mailreaders/mutt/default.nix#L2)?

**Comment by 7c6f434c** [comment]
>@7c6f434c Cool, thanks for the quick feedback. I am new to nix, so please excuse me, but do you mean to implement something analogous to, say [`sslSupport` in `mutt`](https://github.com/NixOS/nixpkgs/blob/391c2778d4ad9cc5167387d788041c1b53be97f6/pkgs/applications/networking/mailreaders/mutt/default.nix#L2)?

Yes, looks good.

(not sure if I should also make Python optional now that bindings are optional…)

**Comment by vbgl** [comment]
Fixed in #92096. Thank you Lorenz!
