### ISSUE TITLE
Wrong/confusing package name for Dracula Vim colorscheme plugin

### ISSUE THREAD

**Issue by kpine** [NixOS/nixpkgs#91976]
**Describe the bug**
The package name for the [Dracula colorscheme vim plugin](https://github.com/dracula/vim/) is confusingly named `nixpkgs.vimPlugins.vim`. 

**To Reproduce**
N/A

**Expected behavior**
I was expecting the package to be named something like `nixpkgs.vimPlugins.dracula` or `nixpkgs.vimPlugins.vim-dracula`. For example, another colorscheme, gruvbox, is called `nixpkgs.vimPlugins.gruvbox`. Searching the packages for "dracula" turns up no results related to vim.

**Screenshots**
![image](https://user-images.githubusercontent.com/791794/86295889-6d418180-bbac-11ea-9b85-5ca0a7dc3907.png)

![image](https://user-images.githubusercontent.com/791794/86295171-da541780-bbaa-11ea-965c-399f2c0013aa.png)

**Additional context**
If I understand correctly, it looks like when it was [originally added](https://github.com/NixOS/nixpkgs/pull/20313) the package was named `dracula`. At some point the vim plugins were updated to be automatically generated based on the Github project name. Since the project is `dracula/vim`, the package name becomes `vim`.

**Notify maintainers**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-9-amd64, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(foo): `"home-manager, nixpkgs-20.09pre231837.2cd2e7267e5"`
 - nixpkgs: `/home/foo/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by kpine** [comment]
This looks like it's fixed now.

https://github.com/NixOS/nixpkgs-channels/commit/1a6f998619fa0f93a10aeb1b4e0763535076960a
https://github.com/NixOS/nixpkgs-channels/commit/40970bee0ea64784c72237ba062ad838cb1f4361

**Comment by teto** [comment]
indeed
