### ISSUE TITLE
Swap file created by the module not compatible with Linux 5.7

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#91986]
**Describe the bug**

I have the following in my `configuration.nix`:

```nix
{pkgs}: {
  boot.kernelPackages = pkgs.linuxPackages_latest;
  swapDevices = [
    {
      device = "/var/swap";
      size = 1024 * 8 * 2; # twice the RAM should leave enough space for hibernation
    }
  ];
}
```

but the service fails with:

```
Jul 02 06:32:27 kaiser swapon[3741]: swapon: /var/swap: swapon failed: Invalid argument
Jul 02 06:32:27 kaiser kernel: swapon: swapfile has holes
Jul 02 06:32:27 kaiser systemd[1]: var-swap.swap: Swap process exited, code=exited, status=255/EXCEPTION
```

Apparently this is because the swapfile is created by `fallocate`:

https://github.com/NixOS/nixpkgs/blob/48704fbd4fc4dc9660ab04f938048b4894ecb140/nixos/modules/config/swap.nix#L197

which kernel does not like.

See the [Arch bug](https://bugs.archlinux.org/task/66921) and the [kernel bug](https://bugzilla.kernel.org/show_bug.cgi?id=207585).

Running nixos-unstable @ 22a81aa5fc15b2d41b12f7160a71cd4a9f3c3fa1.

**Comment by jtojnar** [comment]
As a walk-around, I ran the `dd` code path manually:

```bash
sudo dd if=/dev/zero of=/var/swap bs=1M count=$((1024 * 8 * 2))
sudo mkswap /var/swap
sudo systemctl restart var-swap.swap
```

**Comment by LEXUGE** [comment]
Any update here?

**Comment by jtojnar** [comment]
The fix should be rather straightforward:

1. Remove the `fallocate` branch.
2. Find out how to detect files with holes in them.
3. Add that as another condition that will trigger `dd` when not fulfilled.
4. Test it thoroughly.

**Comment by yshui** [comment]
> Find out how to detect files with holes in them.

To clarify: these file _does not_ have holes. It's a bug in the kernel causing the kernel to think it has holes when using it as swap.

**Comment by jtojnar** [comment]
Tagging this for 20.09 since it will likely break swap for people upgrading. cc @NixOS/nixos-release-managers

**Comment by yshui** [comment]
There is now a patch that's likely to be merged: https://lore.kernel.org/linux-fsdevel/20200825123650.3AA34AE045@d06av26.portsmouth.uk.ibm.com/

**Comment by jonringer** [comment]
Just as a reminder, the 20.09 release is scheduled to happen this monday, the 28th.

If this is still relevant to blocking the release, then there should be some forward movement.

A blocker meeting has still yet to be scheduled. But, if you consider this item to still warrant blocking the entirety of the nixos-20.09 release, the please do so on the [Feature freeze discussion issue](https://github.com/NixOS/nixpkgs/issues/95475). A template for proposing an item can be found https://github.com/NixOS/nixpkgs/issues/95475#issuecomment-699218336

**Comment by jtojnar** [comment]
Looks like `linuxPackages_latest` → `linuxPackages_5_7` bump [also happened in 20.03](https://github.com/NixOS/nixpkgs/commit/86a9689852f6e867d364e62f98b2ce0c50621c39) so people using swap created by the module and running `linuxPackages_latest` already encountered the bug. People using regular `linuxPackages` will not be affected in 20.09 since it still points to `linuxPackages_5_4`. Moving this to 21.03 Blockers.

**Comment by BK1603** [comment]
Since this is a good first bug, I'd like to help with this. I'm a bit confused with the approach to this though. [This](https://lkml.org/lkml/2020/9/24/810) says that a patch was applied for the problem, but I don't see it in the [linux kernel source tree](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/).

Can we use an overlay to add the patch to the `linux-5.7` package?

**Comment by jtojnar** [comment]
I would expect https://github.com/NixOS/nixpkgs/blob/c2bb4af48d26ed091e5674394bacbf8d488c7939/pkgs/os-specific/linux/kernel/patches.nix would be the right place to add a patch to, plus listing it in `pkgs/top-level/all-packages.nix` (search for `linux_5_7 = `).

For testing, you can use `boot.kernelPatches` NixOS option.

**Comment by BK1603** [comment]
I made a PR [here](https://github.com/NixOS/nixpkgs/pull/99915). I'll tag you in there, you can take a look whenever you can find the time :)

**Comment by mvnetbiz** [comment]
I don't think this is only a linux 5.7 bug, I have the same issue on 5.4 with /swapfile on f2fs. I think it is dependent on how the file system implements whatever calls fallocate uses, so I think the dd fallback is a better general solution than the ext4 patch.

**Comment by mvnetbiz** [comment]
Maybe we should support more file system specific behavior at runtime of the creation script
using something like `df --output=fstype $SWAPFILE` for example to create nocow files on btrfs.

If not I think we should always use dd since it is the most portable option, as noted below.

From man page SWAPON(8)
```
NOTES
   Files with holes
       The swap file implementation in the kernel expects to be able to write to the file directly, without the assistance of the filesystem.  This is a problem on files
       with holes or on copy-on-write files on filesystems like Btrfs.

       Commands like cp(1) or truncate(1) create files with holes.  These files will be rejected by swapon.

       Preallocated files created by fallocate(1) may be interpreted as files with holes too depending of the filesystem.  Preallocated swap files are supported  on  XFS
       since Linux 4.18.

       The most portable solution to create a swap file is to use dd(1) and /dev/zero.

   Btrfs
       Swap files on Btrfs are supported since Linux 5.0 on files with nocow attribute.  See the btrfs(5) manual page for more details.

   NFS
       Swap over NFS may not work.

   Suspend
       swapon automatically detects and rewrites a swap space signature with old software suspend data (e.g., S1SUSPEND, S2SUSPEND, ...). The problem is that if we don't
       do it, then we get data corruption the next time an attempt at unsuspending is made.
```

**Comment by cristian-rivera** [comment]
For those of you who are still having this problem, the following has worked well for me:

The proper way to create a Swap file on BTRFS is https://wiki.archlinux.org/index.php/btrfs#Swap_file, so I set up a `oneshot` systemd service to create this file for me that is wanted by the NixOS `swap-*.service` defined in my `hardware-configuration.nix` file. This will create the non-compressed, CoW disabled file in my `/swap` subvolume. Then I leave the allocation and enabling of the swap file to NixOS in `hardware-configuration.nix`

configuration.nix
```
  systemd.services = {
    create-swapfile = {
      serviceConfig.Type = "oneshot";
      wantedBy = [ "swap-swapfile.swap" ];
      script = ''
        ${pkgs.coreutils}/bin/truncate -s 0 /swap/swapfile
        ${pkgs.e2fsprogs}/bin/chattr +C /swap/swapfile
        ${pkgs.btrfs-progs}/bin/btrfs property set /swap/swapfile compression none
      '';
    };
  };
```

hardware-configuration.nix
```

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/545353bc-238b-4a5b-bb48-94832272e0b2";
    fsType = "btrfs";
    options = [ "subvol=swap" "compress=lzo" "noatime" ]; # Note these options effect the entire BTRFS filesystem and not just this volume, with the exception of `"subvol=swap"`, the other options are repeated in my other `fileSystem` mounts
  };

  swapDevices = [{
    device = "/swap/swapfile";
    size = (1024 * 16) + (1024 * 2); # RAM size + 2 GB
  }];
```

**Comment by Artturin** [comment]
#145758

**Comment by Artturin** [comment]
@cristian-rivera
adding logic for btrfs should be pretty simple but we need to figure out if the target location will be a file or a partition 
```
filesystem=$(touch testfile && stat -f -c %T testfile && rm testfile)
```
