### ISSUE TITLE
TeXLive 2020 update

### ISSUE THREAD

**Issue by XVilka** [NixOS/nixpkgs#91994]
**Describe the bug**
TeXLive 2020 was released on 10 April 2020, Nix has only 2019 version at the moment.

- https://www.tug.org/texlive/

### Changes:

-    LuaHBTeX: lualatex is now based on LuaHBTeX, meaning that one can use the HarfBuzz renderer which in particular for complicated scripts (Tibetan, Bengali, …) works better than the Lua-based renderer. Note that luatex itself remains normal LuaTeX, only the luaLAtex one uses LuaHBTeX.
-    Versioned containers: this is a change under the hood we have been working on slowly over the last half year. Many distributions had problems with the changing content of our package containers (foobar.tar.xz while the name never changed. We have now changed all the infrastructure and TeX Live Manager to work with versioned containers foobar.rNNNNN.tar.xz. This should help quite some distributors!
-    Haranoaji (原ノ味): the default font for Japanese text was for long time the IPAex fonts, one of the few free fonts available. With 2020 we have switched to Haranoaji font family, which provides better support for JIS90/04 charsets, and more weights.

General:

-    The \input primitive in all TeX engines, including tex, now also accepts a group-delimited ﬁlename argument, as a system-dependent extension. The usage with a standard space/token-delimited ﬁlename is completely unchanged. The group-delimited argument was previously implemented in LuaTeX; now it is available in all engines. ASCII double quote characters (“) are removed from the ﬁlename, but it is otherwise left unchanged after tokenization. This does not currently aﬀect LaTeX’s \input command, as that is a macro redeﬁnition of the standard \input primitive.
-    New option –cnf-line for kpsewhich, tex, mf, and all other engines, to support arbitrary conﬁguration settings on the command line.
-    The addition of various primitives to various engines in this and previous years is intended to result in a common set of functionality available across all engines (LaTeX News #31).

- epTeX, eupTeX: New primitives \Uchar, \Ucharcat, \current(x)spacingmode, \ifincsname; revise \fontchar?? and \iffontchar. For eupTeX only: \currentcjktoken.

- LuaTeX: Integration with HarfBuzz library, available as new engines luahbtex (used for lualatex) and luajithbtex. New primitives: \eTeXgluestretchorder, \eTeXglueshrinkorder.

- pdfTeX: New primitive \pdfmajorversion; this merely changes the version number in the PDF output; it has no eﬀect on any PDF content. \pdfximage and similar now search for image ﬁles in the same way as \openin.

- pTeX: New primitives \ifjfont, \iftfont. Also in epTeX, upTeX, eupTeX.

- XeTeX: Fixes for \Umathchardef, \XeTeXinterchartoks, \pdfsavepos.

- Dvips: Output encodings for bitmap fonts, for better copy/paste capabilities (https://tug.org/TUGboat/tb40-2/tb125rokicki-type3search.pdf).

- MacTeX: MacTeX and x86_64-darwin now require 10.13 or higher (High Sierra, Mojave, and Catalina); x86_64-darwinlegacy supports 10.6 and newer. MacTeX is notarized and command line programs have hardened runtimes, as now required by Apple for install packages. BibDesk and TeX Live Utility are not in MacTeX because they are not notarized, but a README ﬁle lists urls where they can be obtained.

tlmgr and infrastructure:

-    Automatically retry (once) packages that fail to download.
-    New option tlmgr check texmfdbs, to to check consistency of ls-R ﬁles and !! speciﬁcations for each tree.
-    Use versioned ﬁlenames for the package containers, as in tlnet/archive/pkgname.rNNN.tar.xz; should be invisible to users, but a notable change in distribution.
-    catalogue-date information no longer propagated from the TeX Catalogue, since it was often unrelated to package updates.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: texlive
# a list of nixos modules affected by the problem
module: texlive
```

cc @veprbl

**Comment by TredwellGit** [comment]
@veprbl, are you currently working on this? If not, I will look into it.

**Comment by veprbl** [comment]
@TredwellGit I have other texlive-related things I wanted to do for nixpkgs, so help with the update would be appreciated.
