### ISSUE TITLE
buildPythonPackage uses postFixup for itself

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9204]
I was under the impression that pre/post hooks were available to users. But in the case of python packages, or rather the standard buildPythonPackage function, uses postFixup for itself. This makes it a bit cumbersome if you want to do something custom _after_ the wrapping has taken place (without manually copying the postFixup hook from buildPythonPackage...).

I don't know whether this is best fixed by adding another kind of phase, or if the wrapping currently done in postFixup should be moved to the end of installPhase (before calling postInstall).

The use case I had in mind was to generate bash-completion files for python programs that use "click" or "argh". But to do that we need to be able to run the _wrapped_ python program at the end of the build/install phase.

**Comment by domenkozar** [comment]
Agreed, we can't use `fixup` phase itself since it proves to be useful. We should probably define our own phase where wrappers are generated.

**Comment by Profpatsch** [comment]
(triage) has this changed?

**Comment by bjornfor** [comment]
Nope. buildPythonPackage still wraps programs in postFixup.
