### ISSUE TITLE
python-zstandard fails to install

### ISSUE THREAD

**Issue by tpwrules** [NixOS/nixpkgs#92075]
**Describe the bug**
Attempting to create a Python derivation with the `zstandard` package fails with a "collision" error message (written below). 

**To Reproduce**
1. Attempt to create a nix shell with such a Python derivation by executing the command `nix-shell -p 'python38.withPackages(p: with p; [ zstandard ])'`

**Expected behavior**
A shell containing a Python with the `zstandard` module importable and functional.

**Screenshots**
The following is printed when I execute the command in step 1:
```$ nix-shell -p 'python38.withPackages(p: with p; [ zstandard ])'
these derivations will be built:
  /nix/store/y8rkdg9d85ncnaz5ykycgicym8m53crs-python3-3.8.3-env.drv
these paths will be fetched (0.94 MiB download, 5.67 MiB unpacked):
  /nix/store/fdc7zi9sk8jlmw0rshcb585xawxb2r5m-bash-interactive-4.4-p23-dev
  /nix/store/x4gd806afbgx0ag1jf8y7blzrrhiyx8q-bash-interactive-4.4-p23
building '/nix/store/y8rkdg9d85ncnaz5ykycgicym8m53crs-python3-3.8.3-env.drv'...
collision between `/nix/store/j5w6bhaba6p6in8qz763gkz259424r53-python3.8-zstd-1.4.5.1/lib/python3.8/site-packages/zstd.cpython-38-x86_64-linux-gnu.so' and `/nix/store/6jm2lbix0paw38ydvnpjlrqlgyf463n4-python3.8-zstandard-0.13.0/lib/python3.8/site-packages/zstd.cpython-38-x86_64-linux-gnu.so'
builder for '/nix/store/y8rkdg9d85ncnaz5ykycgicym8m53crs-python3-3.8.3-env.drv' failed with exit code 25
error: build of '/nix/store/86fq7sfdw8jgi76kp6yfn5i26s4rshhf-bash-interactive-4.4-p23.drv', '/nix/store/y8rkdg9d85ncnaz5ykycgicym8m53crs-python3-3.8.3-env.drv' failed
```

**Additional context**
This seems to be because `zstandard` module derivation includes the unrelated `zstd` module derivation and they both vendor different versions of the underlying zstd library.

**Notify maintainers**
@arnoldfarkas 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-39-generic, Ubuntu, 20.04 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(<username>): `"nixpkgs-20.09pre232692.7db146538e4"`
 - nixpkgs: `/home/<username>/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
`zstandard` should not install their zstd module directly in site-packages because that conflicts with the namespace of the `zstd` package. Python packages are free to do so, but its bad practice.

**Comment by FRidh** [comment]
Note in case of the `zstd` package, these are actual Python bindings to `libzstd.so`. You can see that with `ldd`.
In case of `zstandard`, it appears they vendor essentially `libzstd.so` and built it differently for themselves. Fine, but then they should install it within `zstandard/`.

**Comment by FRidh** [comment]
3b4df94aeb6e215085d08e3d5b0edc1313b9f584 should solve your issue. Note, however, you cannot use `zstandard` and `zstd` in one environment because of this naming clash. `zstandard` upstream needs to fix this.

**Comment by tpwrules** [comment]
My solution was to just remove the zstd input completely. It builds and the tests run without a problem. I couldn't work out why it was there in the first place.

I agree that upstream needs to fix it though. I can file a bug and see what happens. Thank you for the prompt response.

**Comment by FRidh** [comment]
Ohh, good point, I did not try that. Yes, it actually vendors its own version so indeed.

**Comment by tpwrules** [comment]
By the way if you're going to modify it again, consider upgrading it too. There's version 0.14.0 out now. Not sure if you have the ability or desire to shortcut the PR process though. I can file one later too.

**Comment by FRidh** [comment]
Removed dependency in 0091e0358bec6952511786b28676753b02bdf860.

I typically don't bother with random "leaf" packages. The reason I looked deeper at this issue is because of the collision which is something we really should avoid. So, feel free to open a PR with an update.
