### ISSUE TITLE
gcc fails to build non-deterministically

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#9212]
See e.g. http://hydra.nixos.org/build/24406532. The problem is most likely on master already, only we were lucky there (and unlucky with gfortran 784025c747) . I can sometimes reproduce it; it seems a parallel-make problem, so the probability of failure is likely to grow with the number of real threads available.

Any idea what to do about this? I don't like disabling parallel make for our `stdenv.cc`, as it terribly slows down testing some kinds of mass-rebuild changes.

**Comment by wkennington** [comment]
I was having the same problem prior to switching to gcc5

**Comment by vcunat** [comment]
I tried to skim through changes in relevant makefiles betwen 4.9.3 and 5.2, but I haven't found anything of use.

**Comment by vcunat** [comment]
As it is now, the best I see is to really disable parallel building for gcc on the release branch. It will slow down deploying some kind of updates (even security ones), but randomly failing rebuilds seem worse.

On staging/master we'll soon switch to `gcc5` which hopefully won't suffer from that problem, so developing of stdenv changes won't be slowed down, at least.

**Comment by vcunat** [comment]
I just tried rebuilding `gcc5` four times on an idle 8-core without a problem. I did have a problem with `gcc49` on that machine, so it really seems to have been fixed.

**Comment by dezgeg** [comment]
Seems like it's this one: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61899

Probably we could steal this patch file (found via some relevant googling): https://github.com/openembedded/oe-core/blob/master/meta/recipes-devtools/gcc/gcc-4.9/0054-gcc-Makefile.in-fix-parallel-building-failure.patch

**Comment by wkennington** [comment]
Seems sane enough, it doesn't change any of the logic of the compilation.

**Comment by vcunat** [comment]
I'm unsure, as we were getting completely different error messages, but we can try.

**Comment by dezgeg** [comment]
Well, there's actually a common error message in the full compile logs (in the bug report's attachment):
````
In file included from ../../gcc-4.10-20140720/gcc/gcc-ar.c:22:0:
../../gcc-4.10-20140720/gcc/system.h:512:34: error: declaration of C function ‘const char* strsignal(int)’ conflicts with
In file included from /usr/include/c++/4.7/cstring:44:0,
                 from ../../gcc-4.10-20140720/gcc/system.h:211,
                 from ../../gcc-4.10-20140720/gcc/gcc-ar.c:22:
/usr/include/string.h:562:14: error: previous declaration ‘char* strsignal(int)’ here
```

Wheras build fails like this:
````
In file included from ../../gcc-4.9.3/gcc/gcc-ar.c:22:0:
../../gcc-4.9.3/gcc/system.h:506:34: error: conflicting declaration of C function 'const char* strsignal(int)'
 extern const char *strsignal (int);
                                  ^
In file included from /tmp/nix-build-gcc-4.9.3.drv-0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include/cstring:42:0,
                 from ../../gcc-4.9.3/gcc/system.h:205,
                 from ../../gcc-4.9.3/gcc/gcc-ar.c:22:
/nix/store/47ayh028d8c9w0h4dqk1wv1yij1zpgb4-glibc-2.21/include/string.h:563:14: note: previous declaration 'char* strsignal(int)'
 extern char *strsignal (int __sig) __THROW;
              ^
```

**Comment by vcunat** [comment]
Confirmed, thanks a lot @dezgeg. Tested and pushed to staging. Some with Hydra admin privileges would better abort the useless (partial) intermediate rebuilds.

**Comment by dezgeg** [comment]
BTW, let's not forget to revert 3d6bd6a1facff3993d1b581dfcf9ee2b6a751642

**Comment by vcunat** [comment]
Yeah, I was already in the process of testing that. Pushed now.
