### ISSUE TITLE
clang-tools as a separate package

### ISSUE THREAD

**Issue by hotpxl** [NixOS/nixpkgs#9214]
I noticed that `clang-tools` (`clang-format` and friends) is part of `clang` right now. Installing it means it will override systems `ld` and such. Is there a separate package that contains only `clang-tools`?

**Comment by hotpxl** [comment]
Closing since nobody is giving a **** about this request.

**Comment by bjornfor** [comment]
When people don't respond it does not necessarily mean they don't care, but they may have more important (in their opinion) matters to deal with first.

**Comment by hotpxl** [comment]
I understand. I'm totally OK with this because sometimes I don't respond to issues either. It's not urgent and I can hack around this.

**Comment by bjornfor** [comment]
Even better than hacking around it, you can submit a pull request :-)
