### ISSUE TITLE
gnome-subtitles: package request

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#92176]
**Project description**
Gnome Subtitles is a subtitle editor for the GNOME desktop.
It supports the most common text-based subtitle formats, video previewing, timings synchronization and subtitle translation. 

**Metadata**

* homepage URL: gnomesubtitles.org
* source URL: https://gitlab.gnome.org/GNOME/gnome-subtitles
* license: gpl2
* platforms: linux

I would add some initial code to begin with:
```
{ stdenv, fetchFromGitLab, pkg-config, intltool, autoconf, automake, libtool, yelp-tools,
mono, gstreamer, enchant, gtkspell3, }:

let
  version = "1.6";
in stdenv.mkDerivation {
  pname = "gcolor3";
  inherit version;

  src = fetchFromGitLab {
    domain = "gitlab.gnome.org";
    owner = "GNOME";
    repo = "gnome-subtitles";
    rev = "gnome-subtitles-${version}";
    sha256 = "1crmmcx32i6ca7dlr3xhnc7vgv9jhlpwh6hxhv2fl1x1zbasf42z";
  };

  nativeBuildInputs = [ intltool pkg-config automake automake libtool yelp-tools ];

  buildInputs = [ mono gstreamer enchant gtkspell3];

  installPhase = ''
    make install
  '';

  meta = with stdenv.lib; {
    description = "Gnome Subtitles is a subtitle editor for the GNOME desktop.";
    homepage = "http://gnomesubtitles.org/";
    license = licenses.gpl2;
    maintainers = with maintainers; [ dasj19 ];
    platforms = platforms.unix;
  };
}
```
As I'll get more experienced with packaging for NixOS I'll add to the upper non-working code.... but until then this is what I have so far

**Comment by prusnak** [comment]
I shortly looked at packaging this, but it seems it requires gtk-sharp3 >= 2.99.2 which is broken in NixOS since 2018. If you want to have this packaged, gtk-sharp3 needs to be fixed in NixOS first.

https://github.com/NixOS/nixpkgs/blob/62501ed497b257f83181933f54c786d5e950ea9a/pkgs/development/libraries/gtk-sharp/3.0.nix#L50

**Comment by dasj19** [comment]
@prusnak Thanks for looking into this case, I'll take a look at gtk-sharp3 when time allows

**Comment by dasj19** [comment]
Fixed gtk-sharp3 in https://github.com/NixOS/nixpkgs/pull/92857

**Comment by dasj19** [comment]
Hello @prusnak ... would you take a look at my attempt to package gnome-subtitles: https://github.com/NixOS/nixpkgs/pull/95098

**Comment by dasj19** [comment]
Closing this as the work continues here: https://github.com/NixOS/nixpkgs/pull/95098
