### ISSUE TITLE
Can't build nvidiaLegacy340 on unstable release.

### ISSUE THREAD

**Issue by kalhauge** [NixOS/nixpkgs#9218]
I tried to change to the unstable channel. Seeing that it have changed to the nvidia 352-ish drive I tried to activate the nvidiaLegacy340:
```
services.xserver.videoDrivers = [ "nvidiaLegacy340" ];
```
But It was unable to build it. Having litte to none knowledge about the nvidia drivers it might a problem here. nixos-rebuild is yeilding these errors:
```
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
false)
```
and
```
/tmp/nix-build-nvidia-x11-340.76-3.18.19.drv-0/kernel/nv-pat.c: In function 'nv_disable_caches':
/tmp/nix-build-nvidia-x11-340.76-3.18.19.drv-0/kernel/nv-pat.c:39:5: error: implicit declaration of function 'read_cr4' [-Werror=implicit-function-declaration]
     *cr4 = read_cr4();
     ^
/tmp/nix-build-nvidia-x11-340.76-3.18.19.drv-0/kernel/nv-pat.c:40:5: error: implicit declaration of function 'write_cr4' [-Werror=implicit-function-declaration]
     if (*cr4 & 0x80) write_cr4(*cr4 & ~0x80);
     ^
cc1: some warnings being treated as errors
```
and 
```
NVIDIA: left KBUILD.
nvidia.ko failed to build!
Makefile:181: recipe for target 'nvidia.ko' failed
make: *** [nvidia.ko] Error 1
```

**Comment by vcunat** [comment]
This looks like a kernel version mismatch.

**Comment by vcunat** [comment]
.76 is the newest version provided by upstream, but it's possible we'll find patches in other distros to fix this.

**Comment by kalhauge** [comment]
Following `https://devtalk.nvidia.com/default/topic/813458/linux/linux-4-0-rc1-346-35-build-error-_cr4-functions-fix/`

This patch should work, on linux kernels over 3.20:
```patch
--- nv-pat.c~	2015-02-22 20:39:43.889075396 -0800
+++ nv-pat.c	2015-02-22 20:29:33.519735577 -0800
@@ -35,8 +35,8 @@
     unsigned long cr0 = read_cr0();
     write_cr0(((cr0 & (0xdfffffff)) | 0x40000000));
     wbinvd();
-    *cr4 = read_cr4();
-    if (*cr4 & 0x80) write_cr4(*cr4 & ~0x80);
+    *cr4 = __read_cr4();
+    if (*cr4 & 0x80) __write_cr4(*cr4 & ~0x80);
     __flush_tlb();
 }
 
@@ -46,7 +46,7 @@
     wbinvd();
     __flush_tlb();
     write_cr0((cr0 & 0x9fffffff));
-    if (cr4 & 0x80) write_cr4(cr4);
+    if (cr4 & 0x80) __write_cr4(cr4);
 }
 
 static int nv_determine_pat_mode(void)
```
But I'm new to nixos and have no idea how to apply it.

**Comment by vcunat** [comment]
I wonder why distros tend to apply this only for some 4.x kernels, e.g. https://projects.archlinux.org/svntogit/packages.git/tree/trunk/nvidia-4.0.patch?h=packages/nvidia-340xx

**Comment by kalhauge** [comment]
Yep. Really strange looking through the src code of the kernel, it is possible to see that the API change is not made in version [3.18](https://github.com/torvalds/linux/blob/v3.18-rc7/arch/x86/include/asm/paravirt.h) but first in [4.00](https://github.com/torvalds/linux/blob/v4.0/arch/x86/include/asm/paravirt.h).
Maybe some of the kernel headers are wrong?

**Comment by vcunat** [comment]
It occurs to me that the change might've been backported to (some) stable branches. That would be why this used to build with 3.18 (which I tested myself a few weeks ago) and doesn't anymore.

**Comment by kalhauge** [comment]
Seams like the patch is allready in place [here](https://github.com/NixOS/nixpkgs/blob/6257425dabe7ad9190d7e5d5fab3d0bc5dad366e/pkgs/os-specific/linux/nvidia-x11/nvidia-340.76-kernel-4.0.patch), but a more succesful solution seams to be in place in some [ati-drivers](https://github.com/NixOS/nixpkgs/blob/6cf49480a6a192f7f0f0ed5d5550e7fb11197f7e/pkgs/os-specific/linux/ati-drivers/kernel-api-fixes.patch) which solves the problem with macros, but it seams to be a little hacky.

```c
#if LINUX_VERSION_CODE < KERNEL_VERSION(3,18,0)
#define __read_cr4 read_cr4
#define __write_cr4 write_cr4
#endif
```

**Comment by vcunat** [comment]
Yeah, our approach for ati is much "less safe" IMO, but since it can't affect other packages directly, I'm leaving it...

**Comment by kalhauge** [comment]
Thx, when does this affect the channel?

**Comment by vcunat** [comment]
That's difficult to predict, unfortunately.

**Comment by vcunat** [comment]
Note that the channel won't provide binaries for these packages (or any other unfree) in any case...
