### ISSUE TITLE
Official nagios plugins package: check_sensors not wrapped correctly

### ISSUE THREAD

**Issue by ctheune** [NixOS/nixpkgs#9219]
The check_sensors package depends on lm_sensors (which is available but not shown as a dependency for the nagiosPluginsOfficial package). However, the check_sensors script itself isn't wrapped properly:

```
#! /nix/store/dbxpkswwc7rh6g1iy6dwqklzw39hihb1-bash-4.3-p33/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="2.0.3"

. $PROGPATH/utils.sh
```

This doesn't get very far ... :)

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by ctheune** [comment]
Unclear. Not on my radar at the moment.

**Comment by Profpatsch** [comment]
Do you have a way to test it?

**Comment by ctheune** [comment]
Yeah, but not working on that end right now. I'm abit tight on time. You could assign it to me and whenever I get around I'll check.

**Comment by ctheune** [comment]
Alright, this has been fixed in the newer version (which followed the rename to `monitoring-plugins`).
