### ISSUE TITLE
nixos manuals are way too big and hard to navigate

### ISSUE THREAD

**Issue by jnoortheen** [NixOS/nixpkgs#92272]
**Describe the bug**
As of now the manual pages are big and takes too long to load. Also it is hard to navigate between titles. 
The initial page load take too long https://nixos.org/nixos/manual/index.html . If I hit any of the title's that too makes the page load again https://nixos.org/nixos/manual/index.html#sec-writing-documentation .

It is just a small usability thing. But it makes look like that nixOS coming from last era. 

Can we adopt something like [this](https://bashtage.github.io/sphinx-material/customization.html) ? on most of the doc frameworks, this is just a config change. But I haven't used docbook and want to help in anyway I can.

**Comment by jnoortheen** [comment]
Here are two theme which I think would be helpful if it is to use hugo as the docs generator

https://example.docsy.dev/docs/tasks/beds/
https://themes.gohugo.io//theme/hugo-book/

**Comment by jtojnar** [comment]
This is a known issue and it is being worked on, see https://github.com/NixOS/rfcs/pull/64 and https://github.com/NixOS/nixpkgs/pull/68020

**Comment by jnoortheen** [comment]
Oh I see. It is sad that there doesn't seems to be any decision made yet. The RFCs are rejected.

**Comment by jtojnar** [comment]
We (the RFC shepherds) have decided to focus on a more focused RFC (currently being prepared) instead.

**Comment by jnoortheen** [comment]
OK. I am closing this.
