### ISSUE TITLE
GCC and Clang include paths missing

### ISSUE THREAD

**Issue by hotpxl** [NixOS/nixpkgs#9230]
By default, GCC and Clang have some paths for finding include files. I could print out the location by

    g++ -v -E -x c++ - < /dev/null

For Debian system G++, it has `/usr/include` and `/usr/local/include` in its search path. So I expect Nix-built G++ to include `<NIX_PROFILE>/include`. But it doesn't. So every time I installed a new library using Nix, and I want to use it in development, I still need to add `<NIX_PROFILE>/include` manually to headers search paths. I wonder if it's a bug or a Nix philosophy?

**Comment by hotpxl** [comment]
Also, `nixpkgs.gcc5 (gcc-wrapper-5.2.0)` would automatically "upgrade" to `nixpkgs.gcc (gcc-wrapper-4.9.3)` if not set flag keep.

**Comment by vcunat** [comment]
It's nix philosophy &ndash; we are explicit about dependencies and don't want to pick up undeclared ones. Probably see the wiki entry about [developing with nix](https://nixos.org/wiki/Development_Environments).

**Comment by vcunat** [comment]
An for quickly setting up oneshot environments, it's probably best to just call `nix-shell -p foo -p bar`; I'm not sure if there's a tutorial for that somewhere, but `man nix-shell` at least describes what it does.

**Comment by hotpxl** [comment]
Thanks for the explanation. I got a second question that `nixpkgs.gcc5 (gcc-wrapper-5.2.0)` would automatically "upgrade" to `nixpkgs.gcc (gcc-wrapper-4.9.3)` if not set flag keep. But it's actually downgrading. I wonder how to prevent this from happening (besides setting adhoc flag).

**Comment by hotpxl** [comment]
Ah I get it! It's because of `lowPrio`!
