### ISSUE TITLE
Add option for pam_fscrypt

### ISSUE THREAD

**Issue by alanpearce** [NixOS/nixpkgs#92352]
I would like to use `fscrypt` to encrypt my home directory. `fscrypt` is already packaged (as `fscrypt-experimental`, for some reason)

What's missing is the PAM setup ([upstream documentation](https://github.com/google/fscrypt#enabling-the-pam-module-on-other-linux-distros)). Given that `security.pam.enableEcryptfs` exists for EcryptFS, I would like to request support for `pam_fscrypt` via the `security.pam.enableFscrypt` option, or something similar. 

## Motivation
I am aware that EcryptFS is available, to achieve the same goals, however it seems to be considered deprecated by other distributions ([1](https://ubuntu.com/server/docs/security-ecryptfs), [2](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/6.9_technical_notes/chap-red_hat_enterprise_linux-6.9_technical_notes-deprecated_functionality)) and has some [limitations](https://wiki.archlinux.org/index.php/ECryptfs#Deficiencies) which I am not comfortable with.

**Comment by kamentomov** [comment]
This is just to say hi and to share that I too am interested in this feature
