### ISSUE TITLE
singularity may be out-dated

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#92466]
**Describe the bug**
The current version singularity 3.2.1 may be out-dated, so that it work abnormally. Should be upgraded to 3.5.3

**To Reproduce**
```
singularity shell <any sif file>
```
**Expected behavior**
Start a shell normally

**Screenshots**
```
container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument
```

**Additional context**
According to [this issue of singularity](https://github.com/hpcng/singularity/issues/5414#issue-651548186)
This is because that the singularity 3.2.1 is out-dated, 
"This issue is due to a mount option passed, which is not ignored on newer kernels and leads to an error. Please use Singularity 3.5.3 to address this issue."

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.03.2447.afa9ca61924 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2447.afa9ca61924"`
 - channels(astrojhgu): `"nixos-19.09beta317.88f32cca5a4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
cc @jbedo

**Comment by jbedo** [comment]
Working on this jbedo/nixpkgs@6c4b4a255dd14b45bf171b2f7578d94ed1acda3b. Haven't fully tested yet.
