### ISSUE TITLE
gstreamer-1 does not honor /etc/asound.conf; potentially breaking audio for machines with more than one sound card

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#9247]
The current `master` version of Firefox can play Youtube videos fine, but audio doesn't work anymore. When I go back to an older version, the issue disappears, so I'm fairly confident that Firefox is the problem, not my system. Curiously enough, other sites like Vimeo can play audio -- it's just Youtube that's broken.

**Comment by peti** [comment]
May or not be related: I also get regular segmentation faults from the new version:

~~~~
[NPAPI 8724] ###!!! ABORT: Aborting on channel error.: file /tmp/nix-build-firefox-40.0.drv-0/mozilla-release/ipc/glue/MessageChannel.cpp, line 1659
~~~~

**Comment by vcunat** [comment]
BTW, I read somewhere firefox should already support gstreamer-1, so it might be good to switch. Maybe it would even solve this problem, but it's more likely it's pulseaudio-related.

**Comment by retrry** [comment]
I think that @wkennington already switched Firefox to gstreamer-1 with https://github.com/NixOS/nixpkgs/commit/f6c1004b2a64138f84bb03c9bf473151adfa50dd commit. I do think that after that update I can't play h264 video from Youtube with Firefox (but I didn't test older version to be sure)

**Comment by vcunat** [comment]
Ah, sorry, so it's likely the other way around :-)

**Comment by peti** [comment]
I've tried to git-bisect the issue, but I had little success because the Firefox build is broken quite a lot and thus a lot of changes occur that are impossible to test. :disappointed: Here is what I got marking all broken build commits as "bad":

~~~~
Bisect Rest:
8164d28 bad libpng: 1.6.16 -> 1.6.18

Bisect Log:
git bisect start
git bisect bad 234754cb0b511fd9095a20e592847ee075a808ba
234754c bad ghc: make sure the nokinds version is built with a deterministic version number
git bisect good f63fd63eb1e6900dbe4d9ce0db895f2af1d94939
f63fd63 good yaws: update from 1.99 to 2.0
git bisect bad 61b44f4ef70df9629f273929f0e5021d1a0105c9
61b44f4 bad haskell-pcap: override to fix undeclared dependency
git bisect bad a0f50b487e38a5dfae4d15d2404605d156239e09
a0f50b4 bad Merge pull request #9108 from titanous/libcec3
git bisect good eda4fd9be716a34e8dedc5929b2f50e54b58d620
eda4fd9 good gnome-video-effects: init at 0.4.1
git bisect good 34fbb4150044d50bdeea8c4ba97df7a7820b6c03
34fbb41 good ceph: Support newer git version
git bisect bad 980fee9fe0673a413553c2e2e7334e782bdca8de
980fee9 bad Merge pull request #9142 from hiberno/bump-rofi-pass
git bisect bad 863fa55cc183c35533cdfd73a8046a30f1085f2c
863fa55 bad Merge pull request #9102 from ts468/upstream.e19
git bisect bad f6c1004b2a64138f84bb03c9bf473151adfa50dd
f6c1004 bad firefox: Use more system libraries
git bisect bad 8164d28315eae1b0cb4aeb26f7dc3334e6ff9e69
8164d28 bad libpng: 1.6.16 -> 1.6.18
git bisect good 666629f30b0e740c2deb72d5539e9a93ca4ab61e
666629f good ceph-pre: Update
8164d28315eae1b0cb4aeb26f7dc3334e6ff9e69 is the first bad commit
~~~~

**Comment by peti** [comment]
Another possibly worthwhile bit of information is that this issue does not occur on all my machines. My laptop displays the issue, but my desktop does not; on my desktop machine all versions of Firefox work okay.

**Comment by peti** [comment]
The new `gstreamer` version does not seem to respect `/etc/asound.conf`. My laptop has two sound cards -- HDMI and PCH: 

    $ aplay -l
    **** List of PLAYBACK Hardware Devices ****
    card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
      Subdevices: 1/1
      Subdevice #0: subdevice #0
    card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
      Subdevices: 1/1
      Subdevice #0: subdevice #0
    card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
      Subdevices: 1/1
      Subdevice #0: subdevice #0
    card 1: PCH [HDA Intel PCH], device 0: ALC3226 Analog [ALC3226 Analog]
      Subdevices: 1/1
      Subdevice #0: subdevice #0

Now, the sound card used by default is card 0 (HMDI) -- which is no good for me, because the laptop's speaker works only with PCH. So I switched the default device to card 1 by having `configuration.nix` create an `/etc/asound.conf` file that says:

    sound.extraConfig = ''
      pcm.!default {
              type hw
              card PCH
      }

      ctl.!default {
              type hw
              card PCH
      }
    '';

This worked fine, until @wkennington updated to `gstreamer-1.0`, which does not respect that setting for some reason. I managed to work around that issue by replacing the `/etc/asound.conf` bit with a slightly more hard-core approach:

    boot.extraModprobeConfig = "options snd_hda_intel index=1";

This config option makes sure that PCH becomes card 0 -- the default -- and Firefox works fine ever since.

**Comment by wkennington** [comment]
I've been digging around firefox / gstreamer / alsaLib to see where it pulls that file from. From what i can tell it should be reading ${alsaLib}/share/alsa/alsa.conf which instructs the library to load /etc/asound.conf. Obviously this isn't happening in gst1. I wonder if there is something different between gstreamer-ffmpeg and gst-libav which is causing this issue pnly for h.264 content.

**Comment by peti** [comment]
For what its worth: I've just had the exact same problem on a machine running openSUSE Tumbleweed. After a system update, Firefox stopped playing audio, apparently because it ignored the ALSA configuration and tried to use the HDMI card. Only after swapping the device order via modprobe did it work again, asoundrc et al had no effect.

**Comment by mogorman** [comment]
@peti I can't recreate on current firefox. I believe this has been resolved. Can you confirm and close?
