### ISSUE TITLE
buildEnv fails on empty list

### ISSUE THREAD

**Issue by ts468** [NixOS/nixpkgs#9248]
buildEnv fails on empty list. For example, the following fails to build:

testenv = pkgs.buildEnv {
  name = "test";
  paths = [];
  pathsToLink = ["/bin"];
};

Whereas changing pathsToLink to the default makes an empty list work:
testenv = pkgs.buildEnv {
  name = "test";
  paths = [];
  pathsToLink = ["/"];
};

The same is true if only one package is included in the list to paths.

Any hints on how to solve that issue?

**Comment by copumpkin** [comment]
Looks like it's fixed by https://github.com/NixOS/nixpkgs/commit/e2a9541efcc2de656d40e641fe378218e5109383.

**Comment by lethalman** [comment]
Yes confirming, that was the fix for the current nixos tests are failing.
