### ISSUE TITLE
gohufont package collision with spleen

### ISSUE THREAD

**Issue by crinklywrappr** [NixOS/nixpkgs#92534]
**Describe the bug**
package collision between gohufont and spleen

**To Reproduce**
1. install buildEnv
2. add gohufont and spleen
3. nix-update-profile

Alternatively, just install with nix-env (which is what buildEnv does).

**Expected behavior**
They should coexist.

**Screenshots**
![image](https://user-images.githubusercontent.com/56522/86668791-9a30d280-bfb8-11ea-965d-48a86127aadb.png)

**Additional context**
I have seen collisions with other bitmap fonts such as Tamzen.

**Notify maintainers**
@rnhmjoj @OmnipotentEntity 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.6-artix1-1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixpkgs-20.09pre232692.7db146538e4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by rnhmjoj** [comment]
I would expect this to happen with any font: the fonts.dir and fonts.scale files contain metadata used by X to load the fonts and are present in any font package.

On NixOS fonts should go into the `fonts.fonts` options, which is a list of paths used by fontconfig to build its cache, not `environment.systemPackages` or similar options. If you're not using NixOS, I'm not sure what's the best way to install fonts.

**Comment by crinklywrappr** [comment]
I am able to install some fonts side-by-side. For example, all of these fonts install alongside terminus.

**Comment by rnhmjoj** [comment]
It works by chance: terminus fonts.dir file is inside `share/fonts/terminus/`, while it's common to put it under `share/fonts/misc`.

**Comment by rnhmjoj** [comment]
I'm closing because the way you're installing font it's not correct.
On NixOS, fonts must be installed by adding them to `fonts.fonts`.
In a nix-shell or non-NixOS, font can be made available to fontconfig-based program like this:
```
FONTCONFIG_FILE = makeFontsConf { fontDirectories = [ /* font here */ ]; };
```
