### ISSUE TITLE
Some applications installed via nix-env crashes outside nixos

### ISSUE THREAD

**Issue by ishan9299** [NixOS/nixpkgs#92579]
**Describe the bug**
I am not using nixos. I have installed some packages via nix-env :-  
- emacs
- kitty
- alacritty 
- Libreoffice
- blender

All the applications (except blender) show a Fontconfig error when launching.
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
```
**Emacs**
The application launches after showing the error shown above but I am not able to change the font of the text editor itself.
![Screenshot from 2020-07-07 19-06-10](https://user-images.githubusercontent.com/47824004/86789468-f4976500-c084-11ea-926d-836ce8207531.png)

Also the font seen on the dashboard is not the default font I use on the system.

**Libreoffice**
Similar error is seem but the application launches just like emacs. Since I don't have any documents with me as of now I can't test how the fonts would be rendered when openning the documents. Otherwise it seems to work fine.
![Screenshot from 2020-07-07 19-13-51](https://user-images.githubusercontent.com/47824004/86790414-06c5d300-c086-11ea-8fad-979fd643fc30.png)
(NOTE: The blender icon is the one installed from my distros repository.)

**Kitty**
Aside from the Fontconfig error another error is seen in case of this application and it fails to launch.
```
[189 19:15:42.964316] [glfw error 65542]: GLX: No GLXFBConfigs returned
[189 19:15:42.964338] [glfw error 65545]: GLX: Failed to find a suitable GLXFBConfig
[189 19:15:42.964353] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

**Alacritty**
Similar to kitty with the Fontconfig error but a slightly different error is shown and it fails to launch.
```
Alacritty encountered an unrecoverable error:

	Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("`glXQueryExtensionsString` found no glX extensions")]`
``` 
**Blender**
It fails to launch with the following error
```
Read prefs: /home/me/.config/blender/2.83/config/userpref.blend
/build/blender-2.83.0/intern/ghost/intern/GHOST_WindowX11.cpp:206: X11 glXChooseVisual() failed, verify working openGL system!
initial window could not find the GLX extension
Writing: /tmp/blender.crash.txt
fish: “blender” terminated by signal SIGSEGV (Address boundary error)
```
This happened to me on both fedora (selinux disabled) and arch ( currently running arch ). I tried this in a virtual machine nixos these applications work fine when installed via nix-env.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.7-zen1-1-zen, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(me): `"home-manager, nixpkgs-20.09pre232692.7db146538e4"`
 - nixpkgs: `/home/me/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:nixpkgs
blender
kitty
alacritty
Libreoffice
```

**Comment by veprbl** [comment]
Problems with OpenGL on non-nixos are well known. See https://github.com/guibou/nixGL

**Comment by ishan9299** [comment]
I tried nixGL I have managed to run alacritty , kitty and blender with my Intel card can't use the nvidia card but it's okay. Problem with Fontconfig still remains for the applications(except blender).

**Comment by flokli** [comment]
These fontconfig are the result of applications reading from `/etc/fonts/fonts.conf`, whose contents are outside of Nix' control on non-NixOS, so font rendering might be in various stages of brokennes and pretty much dependent on your system - there's not much we can do here unfortunately.

**Comment by veprbl** [comment]
I suppose, one could set up a local overlay to append `"--with-baseconfigdir=${placeholder"out"}/etc/fonts"` to the `configureFlags`.

**Comment by veprbl** [comment]
Actually it seems like there is no need to change anything. Looking at this:

https://github.com/NixOS/nixpkgs/blob/1ceecdd109d0c30fd48fc6af295d9c8b05d6c6c6/pkgs/development/libraries/fontconfig/config-compat.patch#L18-L25

One only needs to create `/etc/fonts/2.11/fonts.conf` (probably by copying from `${fontconfig.out}/etc/fonts`)

**Comment by flokli** [comment]
@veprbl Yeah, our fontconfig first tries to load from `/etc/fonts/@configVersion@/fonts.conf`, and if it fails, from `/etc/fonts/fonts.conf`. We don't currently provide `/etc/fonts/@configVersion@/fonts.conf` at all, and generate the `/etc/fonts` dynamically in the NixOS module system.

I did some archeology on `config-compat.patch` - This was introduced 2014 in c0e2aceef46033e43ab8b4f6aa0b36b25ba35f3d to still support applications using pre-2.11 fontconfig. I consider this a NixOS-internal workaround, not a API that non-NixOS distros should use.

@ishan9299, can you check what version of fontconfig your main distro runs with? Maybe it's outdated, or otherwise incompatible.

**Comment by ishan9299** [comment]
I think it's incompatible on running fc-cache -V the version is 2.13.91 on archlinux .

**Comment by flokli** [comment]
This issue is now only about the nixpkgs fontconfig being incompatible with that one of newer releases - closing as a dup to https://github.com/NixOS/nixpkgs/issues/82983.
