### ISSUE TITLE
python-cryptography is failing to build

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#9261]
http://hydra.nixos.org/eval/1214570?filter=cryptography&compare=1214551&full= suggests that it's an across-the board failure, and the specific issue appears to be a missing dependency:

```
Searching for py>=1.4.29

Note: Bypassing https://pypi.python.org/simple/py/ (disallowed host; see http://bit.ly/1dg9ijs for details).

Couldn't retrieve index page for 'py'
Scanning index of all packages (this may take a while)

Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/1dg9ijs for details).

No local packages or download links found for py>=1.4.29
error: Could not find suitable distribution for Requirement.parse('py>=1.4.29')
builder for ‘/nix/store/fv88n1xjn6lpmj24hsxbwj0vdp4gbnhp-python3.4-cryptography-0.6.1.drv’ failed with exit code 1
```

@domenkozar last time this package broke you seemed to know what was going on...

**Comment by domenkozar** [comment]
py dependency is missing or is too new

**Comment by mdorman** [comment]
So, I tried to do a little work to resolve this.  My conclusions are sufficiently counterintuitive---I found not one or two, but three reasons that seem like they should have broken cryptography all along---that I feel like I must be doing something wrong.

First, as @domenkozar observed, the `cryptography` dependency on `py` was not stated in its nix expression.  Since this expression doesn't appear to have changed significantly in the last week or so---that being the last time I installed a package that depended on it---I'm confused as to how it ever successfully built without that.

Adding that dependency, I found that the version of `py` that is currently in nixpkgs is older than what `cryptography` expects.  So that's another mark in the "how did `cryptography` ever build" column.

Finally, having updated the dependency, I found that `cryptography` now gets a runtime error during testing.  Again, I don't understand how it ever built.

So I am now trying to upgrade `cryptography` as well.  I will post a PR when I have one, but I am inherently uncertain whether it's the right thing to do because I have no idea why it worked before, or why it broke now.

**Comment by vbgl** [comment]
Apparently, `cryptography` tests have been broken by #9253.

**Comment by mdorman** [comment]
@vbgl Ah, I see you are likely correct.  It is actually the pytest update that requires an updated version of py.

**Comment by FRidh** [comment]
Yes, that's indeed the case. I didn't do a nox-review wip on pytest so that's likely why I didn't see at the time.

**Comment by mdorman** [comment]
FWIW, if I apply the change revving the py package to 1.4.30 that's linked above, I *still* get an error in the cryptography test suite, though it seems to be an actual issue with the cryptography package.

**Comment by FRidh** [comment]
There's a much newer package at PyPi, version 1.0:
https://pypi.python.org/pypi/cryptography

**Comment by mdorman** [comment]
And I've actually got a change that upgrades it (and a couple of things it depends on), which I will submit once I've finished running `nox-review` on it. :)

**Comment by FRidh** [comment]
Likely that one will fail due to `python-fedora`, #9260

**Comment by mdorman** [comment]
And python-novaclient, which is apparently no longer present on any mirrors.  And others for similar reasons.  But it's easy enough to run it and at least see if any of the failures actually appear to be because of the change in the cryptography package.

**Comment by mdorman** [comment]
I don't know the process---should this stay open until these changes land in a particular branch, or is it remaining open because I didn't ever mention #9274 in the thread?

**Comment by domenkozar** [comment]
Can be closed now, yup :)
