### ISSUE TITLE
open-vm-tools spams the logs

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#9262]
I am running NixOS under ESXi and using the vmware service results in lots of log entries like this one:
```
Aug 15 13:47:18 nixos vmsvc[366]: [ warning] [guestinfo] Failed to get OS info.
Aug 15 13:47:48 nixos vmsvc[366]: [ warning] [vmsvc] HostinfoOSData: Error: no distro file found
```

Here is how Alpine Linux solved it: [discussion](https://bugs.alpinelinux.org/issues/1221) [patch](https://bugs.alpinelinux.org/projects/alpine/repository/revisions/651dae1c8329865d3819df8e81ce29c70ebfdcfa/entry/main/open-vm-tools/0001-lib-misc-Recognize-Alpine-Linux.patch)

I'm not sure if that will work for us because we don't use the LSB key names. I'd be happy with just not the log spam.

I also created vmware/open-vm-tools#33 for what I think would be the correct solution.

**Comment by wmertens** [comment]
Cc @joamaki @jagajaga

**Comment by jagajaga** [comment]
Maybe let's create a patch and try to make a PR to https://github.com/vmware/open-vm-tools?
For example checking if we have `nixos-config` in `$NIX_PATH`? Or what's a best way to determ that this OS is NixOS?

**Comment by wmertens** [comment]
Well - I don't think that open-vm-tools needs to know about NixOS, it should just read the os-release... Not a very difficult task I think but more than I have time for :(

**Comment by jagajaga** [comment]
So you suggest to create `/etc/nixos-release` and patch for open-vm-tools? Hmm, sounds good.

**Comment by wmertens** [comment]
Yeah, that seems the least work…

On Sun, Aug 16, 2015, 00:17 Arseniy Seroka <notifications@github.com> wrote:

> So you suggest to create /etc/nixos-release and patch for open-vm-tools?
> Hmm, sounds good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/9262#issuecomment-131456460>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by wmertens** [comment]
Actually, just creating /etc/release with the LSB keys might make it work
without patch, it checks that for Solaris

On Sun, Aug 16, 2015, 16:12 Wout Mertens <wout.mertens@gmail.com> wrote:

> Yeah, that seems the least work…
>
> On Sun, Aug 16, 2015, 00:17 Arseniy Seroka <notifications@github.com>
> wrote:
>
>> So you suggest to create /etc/nixos-release and patch for open-vm-tools?
>> Hmm, sounds good.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NixOS/nixpkgs/issues/9262#issuecomment-131456460>.
>>
> --
>
> Wout.
> (typed on mobile, excuse terseness)
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by jagajaga** [comment]
Maybe let's create `/etc/nixos-release` with contents of `nixos-version`? cc @edolstra

**Comment by wmertens** [comment]
A really simple workaround:

```
# cat /etc/release 
DISTRIB_ID=NixOS
DISTRIB_RELEASE="15.08pre67355.1357692 (Dingo)"
```

This shuts up the errors. I don't see any of this appearing in the ESXi interface though (v5.1).

**Comment by edolstra** [comment]
I would prefer *not* having `/etc/release` or `/etc/nixos-release`, since we already have `/etc/os-release` which is supposed to be standard. I'm guessing it shouldn't be too hard to patch open-vm-tools to use `/etc/os-release`, and that would benefit other distros as well.

**Comment by jagajaga** [comment]
I've made https://github.com/vmware/open-vm-tools/pull/35.
And add temporary https://github.com/NixOS/nixpkgs/commit/3ebe6fa802f19b05eea7923287d1cd7ee6c2bcc9.
Builds fine, but please test.

**Comment by peterhoeg** [comment]
A workaround is to simply:
```
ln -s /etc/os-release /etc/release
```
I'm aware it goes against anything that NixOS stands for, but if you only have a single/few host(s) it might be a temporary workaround.

**Comment by wmertens** [comment]
Closing this, since the temp fix is in the tree and it presumably works fine.

**Comment by wmertens** [comment]
@jagajaga VMWare is finally ready to accept your patch :) you need to sign their CLA…

**Comment by jagajaga** [comment]
@wmertens just signed something :D 
Will wait for the result.
