### ISSUE TITLE
Setting browsers (Firefox, Chromium) as default have no effect in Sway.

### ISSUE THREAD

**Issue by Kazimazi** [NixOS/nixpkgs#92751]
**Describe the bug**
"Set browser as default" functionality doesn't work for Firefox and Chromium in Sway. (bspwm and other x11 wms worked)

**Additional context**
If I have xdg_utils installed globally, it works as expected.

**Notify maintainers**
xdg_utils & firefox:
@edolstra
firefox:
@andir

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev
copying path '/nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.7, NixOS, 20.03.2459.c9d124e39db (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2459.c9d124e39db, nixos-unstable-20.09pre228622.029a5de0839"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Kazimazi** [comment]
Chromium seems to be ok now.

**Comment by Kazimazi** [comment]
Added additional context, which might lead to solving the main issue.

**Comment by primeos** [comment]
Oh, I forgot that this is also for Firefox.
