### ISSUE TITLE
Package request: fslint

### ISSUE THREAD

**Issue by operator-name** [NixOS/nixpkgs#92768]
**Project description**
> FSlint is a utility to find and clean various forms of lint on a filesystem.
> I.E. unwanted or problematic cruft in your files or file names.
> For example, one form of lint it finds is duplicate files.
> It has both GUI and command line modes.

**Metadata**

* homepage URL: https://www.pixelbeat.org/fslint/
* source URL: https://github.com/pixelb/fslint
* license: gpl2+
* platforms: linux

**Comment by dasj19** [comment]
Hello, fslint is a tool I miss as well... I'll give it a try at packaging tommorrow

**Comment by dasj19** [comment]
Just added a preliminary build of fslint... apparently it needs some patching of functionality.
Let's move the discussion here: https://github.com/NixOS/nixpkgs/pull/92833

**Comment by dasj19** [comment]
This issue can be closed. The package `fslint` was released yesterday.
