### ISSUE TITLE
Add several missing lisp packages for nyxt-browser

### ISSUE THREAD

**Issue by bqv** [NixOS/nixpkgs#92763]
The follwing set (at least) are required for next-browser (nyxt)'s "upcoming" version. I have been waiting [four literal months](https://logs.nix.samueldr.com/nixos/2020-04-30#3390471) for them to release so it can be updated, but they appear to have gone implicitly rolling release.

Could these be added to lispPackages:
cl-cffi-gtk cl-markup cl-webengine cl-webkit2 enchant moptilities trivial-features trivial-main-thread trivial-package-local-nicknames uiop

It will then at least be possible to build a derivation locally.

**Comment by bqv** [comment]
Ping lastModified:

@ramzibenyahyasonos 
@7c6f434c 
@tviti 
@nlewo 
@joachifm 

Since you all know how to successfully update lispPackages

**Comment by bqv** [comment]
New version has been tagged. If anyone has the ability to sort this out, please do, but in the mean time, I have my own solution.

**Comment by teto** [comment]
dont know how to do the update but I am interested as well.

**Comment by jmercouris** [comment]
I would also like to voice my support for this issue. Any assistance in packaging Nyxt for Nix would be greatly appreciated.

**Comment by nlewo** [comment]
To update lisp packages, there is a bit a documentation [here](https://github.com/NixOS/nixpkgs/blob/6068afe0fdca6043af185cfa2a02fada1f8066b2/pkgs/development/lisp-modules/README.txt).
Hoping this could help.

**Comment by 7c6f434c** [comment]
>I would also like to voice my support for this issue. Any assistance in packaging Nyxt for Nix would be greatly appreciated.

Now I want a bot that will remind me next Thursday, after three more talks at non-Nix-related places, to try to see if we have a bit of time next weekend that is also timezone-compatible…

**Comment by 7c6f434c** [comment]
Oops, sorry, that was for related https://github.com/NixOS/nixpkgs/pull/94913

**Comment by 7c6f434c** [comment]
Do we close it now?

**Comment by 7c6f434c** [comment]
`cl-webengine` is a separate story in a few ways, the rest seems to build now

**Comment by jmercouris** [comment]
Thank you so much!  You can just ignore `cl-webengine` for now, it will undergo many changes...
