### ISSUE TITLE
`lib.isStorePath': Don't error on lists-of-derivations as input 

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#9278]
I just found out rather painfully that `lib.isStorePath` errors when given lists-of-derivations like `[ pkgs.emacs ]`.

This leads to unintuitive error messages if you accidentally put lists of derivations inside `environment.systemPackages`.

Test: 

`lib.isStorePath [pkgs.emacs]` 

=>

`error: cannot coerce a list to a string, at /home/moritz/dev/nixpkgs/lib/strings.nix:224:73`

One solution suggested in IRC by @bennofs is wrapping the whole thing in `tryEval`, but we're unsure about the performance implications.

**Comment by copumpkin** [comment]
My initial reaction is why you (or someone else) would expect `isStorePath` to accept a list or do anything sensible with it. My assumption is that you'd `map` or `filter` or something similar.

Is there existing code written that expects that to work? It's not very clear from what you wrote above.

**Comment by bennofs** [comment]
@copumpkin types.nix uses it to check whether something is a `package`. Because `isStorePath` throws an exception instead of returning false for lists, we get an exception instead of a friendly type-mismatch message when you put a list of things into `systemPackages`.

**Comment by copumpkin** [comment]
Ah, I see, that was the missing ingredient from my understanding, thanks!

**Comment by edolstra** [comment]
It's probably best to add a `isPath` primop to Nix, since then we can write `isStorePath = x: (isPath x || isString x) && ...)`.

**Comment by wmertens** [comment]
(triage) did the situation change?
