### ISSUE TITLE
nixops-1.7 sub-dependency python2.7-Pillow-6.2.2 build fails on macOS

### ISSUE THREAD

**Issue by abathur** [NixOS/nixpkgs#92818]
Updated channel and seeing build failures identical to those reported on hydra starting Jun 6:
- latest builds: https://hydra.nixos.org/job/nixpkgs/trunk/python27Packages.pillow.x86_64-darwin#tabs-status
- first broken: https://hydra.nixos.org/build/121487331
- tail of first broken: https://hydra.nixos.org/build/121487331/nixlog/1/tail

Dependency graph here is nixops-1.7.drv -> python2.7-datadog-0.36.0.drv -> python2.7-Pillow-6.2.2.drv

Tagging those involved in the spate of recent pillow issues since neither of the listed maintainers were involved and I assume this is related: @jonringer @FRidh @adisbladis @evanjs @marsam

**Comment by evanjs** [comment]
I think this might be related to the changes I made, and it looks like @jonringer froze at 6.2.2 _after_ I changed the expression.

Maybe if we replace the current (frozen) [6.nix](https://github.com/NixOS/nixpkgs/blob/7abf70b244b7a0d599729a6ae2222b81cb861704/pkgs/development/python-modules/pillow/6.nix) with the contents of the [previous (6.2.2) expression](https://github.com/NixOS/nixpkgs/blob/f342b667a50798670ce3dd7e5d975c96009e5ea3/pkgs/development/python-modules/pillow/default.nix), this might be enough to resolve the issue.
