### ISSUE TITLE
Can't build mesa with  `override stdenv llvmPackages_10.lldClang`

### ISSUE THREAD

**Issue by L-as** [NixOS/nixpkgs#92828]
**Describe the bug**
I can't build mesa with llvmPackages_10.lldClang set as my CC for my stdenv. Might be related to #39936 ?

**To Reproduce**
Try building the expression below
```nix
with import <nixpkgs> {overlays = [];};
mesa.override {
  stdenv = overrideCC stdenv llvmPackages_10.lldClang;
}
```

**Expected behavior**
It is expected to build

**Additional context**
mako and wl-clipboard build fine.

**Notify maintainers**
@primeos @vcunat 

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.8.0-rc1-10+, NixOS, 20.09pre233323.dc80d7bc4a2 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre233323.dc80d7bc4a2, stable-20.03.2491.6a00eba02a3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute: mesa
module:
```

**Comment by vcunat** [comment]
Well, I am in `mesa.meta.maintainers`... but honestly I don't see motivation for me to invest time into making it work with a non-default compiler.

**Comment by primeos** [comment]
I guess we can close this then.
