### ISSUE TITLE
Emacs package should build with Cocoa on OSX

### ISSUE THREAD

**Issue by wolverian** [NixOS/nixpkgs#9292]
Installing `emacs` on OS X doesn't install a graphical (i.e. toolkit) version at all as far as I can see. The `--with-ns` option to Emacs's `./configure` would enable the Cocoa toolkit GUI. 

I know the macport version of emacs is available as a separate package. I don't think that's a reason not to enable Cocoa in the `emacs` package.

**Comment by johbo** [comment]
I already created an override for this for my macbook, maybe that's a good point to start:

```nix
{
    emacs = pkgs.lib.overrideDerivation pkgs.emacs (oldAttrs: {
      # Adding support for the GUI integration for darwin
      configureFlags = oldAttrs.configureFlags ++ pkgs.lib.optional pkgs.stdenv.isDarwin [
        "--with-ns --disable-ns-self-contained"
      ];

      # Copy over the generated Emacs.app data
      postInstall = oldAttrs.postInstall + pkgs.lib.optionalString pkgs.stdenv.isDarwin ''
        mkdir -p $out/Applications
        cp -r nextstep/Emacs.app $out/Applications
      '';

    });
}
```
I am using currently a symlink to get emacs also into the applications inside of the launcher:
```
$ ls -l ~/Applications/
total 4
lrwxr-xr-x 1 johannes staff 51 May  1 19:20 Emacs.app -> /Users/johannes/.nix-profile/Applications/Emacs.app
```

Works quite ok for me, maybe it's time to throw this into a small PR.

**Comment by johbo** [comment]
hehe, just checked master, it's already in there: 3506c0bf04538c4a25b57dd43600b61907796008

I suggest to close this issue.
