### ISSUE TITLE
Mono 6.10 (existing mono is 6.0, outdated)

### ISSUE THREAD

**Issue by r-k-b** [NixOS/nixpkgs#92984]
I'm opening this as I'm hitting various issues while trying to build an existing .Net project on NixOS 20.03, such as:

- `The current .NET SDK does not support targeting .NET Core 3.1`
- `The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run`
- `[CS0012] The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

and it seems at least one of them has been fixed since mono 6.0.

(The .Net project has no issues being built in other distros, such as Ubuntu, and is also fine on MacOS)

tangentially related? #39216

---

**Project description**
> Sponsored by Microsoft, Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime
https://www.mono-project.com/docs/about-mono/releases/6.10.0/

**Metadata**

* homepage URL: https://www.mono-project.com/
* source URL: https://github.com/mono/mono
* license: [several?](https://github.com/mono/mono/blob/master/LICENSE)
* platforms: linux (+others?)

Existing package: <https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/mono>

**Comment by dasj19** [comment]
Do you want specific 20.03 support for mono 6.10 or unstable is enough? I might cover the unstable side of the issue.

**Comment by r-k-b** [comment]
unstable should be enough, thanks dasj19!

**Comment by dasj19** [comment]
I updated the packages for mono5 and mono6 here: https://github.com/NixOS/nixpkgs/pull/93043
You could test with `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 93043"` or from my branch: https://github.com/dasj19/nixpkgs/tree/mono6-update

**Comment by r-k-b** [comment]
awesome, thanks!

That's quite helpful, I'm still learning Nix and it's useful to see what changes needed to happen

**Comment by dasj19** [comment]
I am new as well ;) just couple of months active within nix community... not even finished reading Nix Pills, but I guess I learn more by doing stuff ;)

**Comment by r-k-b** [comment]
This is resolved, thanks dasj19!
