### ISSUE TITLE
Postgresql timeout leaves postresql dead

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#92998]
**Describe the bug**
Postgresql service startup can timeout and is then never restarted.

**To Reproduce**
1. slow startup
2. systemd kills postgresql (reason: timeout)
3. postgresql and dependencies which require it are and stay down

**Expected behavior**
Either:

1/ systemd is told to wait for postgresql (with TimeoutStartSec=0)
2/ systemd restarts postgresql (with Restart=on-failure)

1 is prefered because this way dependencies which Require=postgresql.service will eventually start

**Additional context**
Debian sets infinite startup time, with interesting comments
```ini
[Service]
Type=forking
# -: ignore startup failure (recovery might take arbitrarily long)
# the actual pg_ctl timeout is configured in pg_ctl.conf
ExecStart=-/usr/bin/pg_ctlcluster --skip-systemctl-redirect %i start
# 0 is the same as infinity, but "infinity" needs systemd 229
TimeoutStartSec=0
ExecStop=/usr/bin/pg_ctlcluster --skip-systemctl-redirect -m fast %i stop
TimeoutStopSec=1h
ExecReload=/usr/bin/pg_ctlcluster --skip-systemctl-redirect %i reload
PIDFile=/run/postgresql/%i.pid
SyslogIdentifier=postgresql@%i
# prevent OOM killer from choosing the postmaster (individual backends will
# reset the score to 0)
OOMScoreAdjust=-900
# restarting automatically will prevent "pg_ctlcluster ... stop" from working,
# so we disable it here. Also, the postmaster will restart by itself on most
# problems anyway, so it is questionable if one wants to enable external
# automatic restarts.
#Restart=on-failure
# (This should make pg_ctlcluster stop work, but doesn't:)
#RestartPreventExitStatus=SIGINT SIGTERM
```
Fedora has no timeout at all:
```
# No artificial start/stop timeout (rhbz#1525477, pgrpms#2786).
TimeoutSec=0
```
Arch does like NixOS: `TimeoutSec=120`
Gentoo waits longer: `TimeoutSec=300`
**Notify maintainers**
@thoughtpolice @danbst

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.8, NixOS, 20.03.2513.009c50976b5 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2513.009c50976b5, nixos-unstable-20.09pre233124.f7c7509ecd0"`
 - channels(symphorien): `"home-manager-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: [ postgresql ]
```

**Comment by symphorien** [comment]
Still interested in this.
I can make a PR increasing/disabling the timeout, but I'd like the opinion of maintainers first.

**Comment by aanderse** [comment]
I think the defaults are fine as they are. If you're "seriously" using a database on any distro you're expected to do some tweaking.

I have a 3 node `galera` cluster and I have added `systemd.services.mysql.serviceConfig.TimeoutSec = "infinity";` to my configurations because with a large dataset this is what upstream recommends.

Certain decisions have to be pushed onto the sysadmin... NixOS can only provide reasonable defaults - preferably from upstream.

I wish we had something like the arch wiki that was contained in the nixpkgs repo. We could write up detailed explanations like this and it would be the standard place to have a more detailed explanation of each module/package.

**Comment by symphorien** [comment]
That makes sense.
