### ISSUE TITLE
amdvlk 32bit

### ISSUE THREAD

**Issue by ZerataX** [NixOS/nixpkgs#93027]
**Project description**
#82305 introduced amdvlk to nixos already, but afaict this only works with 64bit application, but since a lot of especially games are still 32bit it really would be nice to also be able to run those with amdvlk.

I currently have this:
```nix
{
environment.variables.VK_ICD_FILENAMES = "${pkgs.amdvlk}/share/vulkan/icd.d/amd_icd64.json:/run/opengl-driver-32/share/vulkan/icd.d/radeon_icd.i686.json";
}
```

In my nixos configuration to make sure that if possible amdvlk is used but also to make sure 32bit applications can still run

**Metadata**

should be the same

**Comment by Flakebi** [comment]
What would be the right way to do this with nix?

The possibilities I see are:
1. Build with `-DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32`
2. Use the nix i686 toolchain (working amdvlk here: https://github.com/Flakebi/nixpkgs/commit/71f08eb979ca2de060e2717c0a1c83e5703b8ef1, can be used as `pkgsi686Linux.amdvlk`)

A disadvantage of 2. is that it does not support lto.
