### ISSUE TITLE
remmina not usable as NX client

### ISSUE THREAD

**Issue by fowlay** [NixOS/nixpkgs#9303]
I am trying to use 'remmina' as a client towards a legacy NX server. Using remmina as a legacy NX client does work on other platforms, e g Ubuntu 14.04.

My Nix version is 1.9. Here is what happens:

Starting remmina-1.0.0 succeeds, a GUI comes up and I get the following progress messages in the console (NX is mentioned which makes hope rise):

Remmina plugin GKEYRING (type=Secret) registered.
NX: detected keyboard type pc105/se
Remmina plugin NX (type=Protocol) registered.
Remmina plugin XDMCP (type=Protocol) registered.
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin SFTP (type=Protocol) registered.

Creating a connection (Connection->New) works. I give the connection a name, set the Protocol to NX and specify Server as host:port.

Menu-clicking the connection and selecting Connect works. I enter username and password and I get an "NX Sessions" window. In this window I can see my existing session (previously started from a different NX client).

However, clicking Restore does not work. I get a pop-up saying

Failed to execute child process "nxproxy" (No such file or directory)

**Comment by abbradar** [comment]
You should install `nxproxy` in your environment -- I think maintainers avoided adding it as a dependency on purpose, to make package closure smaller.

**Comment by fowlay** [comment]
Thanks for the hint! I installed 'remmina' and 'nxproxy' now and all seems fine (the channel is nixos-15.09).
