### ISSUE TITLE
[azure] boot.growPartition + filesystems.*.autoResize did not grow the partition as expected

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#93032]
**Describe the bug**

```
    virtualisation.azureImage.diskSize = 2500;

    fileSystems."/" = {
      fsType = "ext4";
      autoResize = true;
    };
    
    boot = {
      cleanTmpDir = true;
      kernelPackages = pkgs.linuxPackages_latest;
    };
```

Just booted an instance with both options set, I ssh in after a boot and reboot, and check fdisk -- the partition was still the same size as the templated image (not even the initial OS size).

**Notify maintainers**
@colemickens

**Comment by colemickens** [comment]
still important to me

**Comment by kfollesdal** [comment]
Hi, think #115391 fix your problem. With the changes in PR os disk in azure auto expand to disk size when created or changed.

**Comment by VergeDX** [comment]
Same issues here, it seems the fixes PR not in `nixos-21.11` channel, I will try `nixos-unstable` channel.

**Comment by VergeDX** [comment]
`nixos-unstable` channel works for me well, please container close this issues! :wink: @colemickens

**Comment by VergeDX** [comment]
After switch to `nixos-unstable`, the disk can scale for me well. :wink: 
If you still encounter the same issues, please reopen : )
