### ISSUE TITLE
Bug in Minio object storage server, devs of Minio suggest to upgrade

### ISSUE THREAD

**Issue by JosephLucas** [NixOS/nixpkgs#93086]
Hi,
I really like using [Minio](https://min.io/) to share files. The current package of Minio worked well until I added permission policies.
There is a bug in the current version (2020-05-01T22-19-14Z) of the package. A detailed description of the bug is written in Minio's repo https://github.com/minio/minio/issues/10039.
Developers of Minio are confident that the bug is solved in newer versions.

I have tried to write an overlay with the last release
```
self: super: with super; {
  myminio = super.minio.overrideAttrs (oldAttrs: rec {
  # myminio = super.minio.override {
    version = "2020-07-02T00-15-09Z";
    src = super.fetchFromGitHub {
      owner = "minio";
      repo = "minio";
      rev = "RELEASE.2020-07-02T00-15-09Z";
      sha256 = "0vwqcrkqzfs34y26f0qsl5z0sndz7rhxxgi7dyk5izc9p2dq3d99";
    };
    buildFlagsArray = [''-ldflags=
      -s -w -X github.com/minio/minio/cmd.Version=2020-07-02T00-15-09Z
    ''];
  });
}
```
but I am stuck with this error while compiling
```
building
Building subPackage ./.
go: inconsistent vendoring in /build/source:
        github.com/go-sql-driver/mysql@v1.5.0: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/go-sql-driver/mysql@v1.4.1

...

        gopkg.in/yaml.v2@v2.2.8: is explicitly required in go.mod, but vendor/modules.txt indicates gopkg.in/yaml.v2@v2.2.4

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
```
I don't know the Go packaging enough to solve this by myself.
Can someone help me upgrade Minio ? I would like to help maintaining/packaging the apps that I use on nixpkgs but I am still a bit lost among all the nixpkgs attributes.

**Comment by JosephLucas** [comment]
The the last GNU/Linux binary release at https://docs.min.io/docs/minio-quickstart-guide.html does fix the issue.

You can use 
```
minio = pkgs.stdenv.mkDerivation rec {
        name = "minio";
        src = pkgs.fetchurl {
          url = "https://dl.min.io/server/minio/release/linux-amd64/minio";
          sha256 = "1989sy47yz3vckfj4kv880s054js31ykl0npmizdlvrdjnhahaxn";
        };
        phases = ["installPhase" "patchPhase"];
        installPhase = ''
          mkdir -p $out/bin
          cp $src $out/bin/${name}
          chmod +x $out/bin/${name}
        '';
    };
```
before any version upgrade of the nixpkgs derivation.

**Comment by flokli** [comment]
@JosephLucas I'd happily help you out in filing a PR against nixpkgs that bumps minio to its latest version.

It should just be a matter of bumping the version number in `pkgs/servers/minio/default.nix`, changing both hashes to zeroes, and then trying to `nix-build -A minio` from the root folder of the checkout.

**Comment by JosephLucas** [comment]
Ok I will try that when I will have some times, thanks.
