### ISSUE TITLE
sudo update request.can't use FOLLOW and NOFOLLOW on security.sudo

### ISSUE THREAD

**Issue by btwiusegentoo** [NixOS/nixpkgs#93090]
**Describe the bug**
Hi! As I'm using NixOS, I want to edit symlinks of /etc/ssh/sshd_config directly with sudoedit.(I don't want to write private port on nix file.)
looks like it's editable using FOLLOW option on sudoers refering to http://sudo.usenix.org.uk/man/1.8.20/sudoers.man.html
(Just an example. I can use seperate file to configure ssh listed on gitignore and I will use but regardless of that it's nice if I can edit symlinks with sudoedit on NixOS.)

**To Reproduce**
Add this to configuration.nix
<code>security.sudo = { enable = true; extraRules = [ { groups = [ "wheel" ]; commands = [ "ALL" { options = [ "FOLLOW" ]; } ]; } ]; };</code>

**Additional context**
Maybe it can fix adding FOLLOW option here https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/sudo.nix
line 147
```
               options = mkOption {
                  type = with types; listOf (enum [ "NOPASSWD" "PASSWD" "NOEXEC" "EXEC" "SETENV" "NOSETENV" "LOG_INPUT" "NOLOG_INPUT" "LOG_OUTPUT" "NOLOG_OUTPUT" ]);
                  description = ''
                    Options for running the command. Refer to the <a href="https://www.sudo.ws/man/1.7.10/sudoers.man.html">sudo manual</a>.
                  '';
                  default = [];
                };
              };

            }));
          };
        };
      });
    };
```
Sorry if i'm something wrong as I'm new to NixOS and my English is not good.
I'm not sending as pull request because I'm not sure I am correct.

EDIT: Ok, looks like it is a feature implemented on some newer version. change title to update request.

**Comment by dasj19** [comment]
Hello, I can make a package update for you if you mean that feature will be present in the latest release... but you will have access to it at first only if you are using nixpkgs unstable.

**Comment by btwiusegentoo** [comment]
> Hello, I can make a package update for you if you mean that feature will be present in the latest release... but you will have access to it at first only if you are using nixpkgs unstable.
> 
> Edit: Done. Opened this pull request: #93100
> You could test it with: `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 93100"`

Thanks! AFAIK, on man page for 1.7.10 doesn't have that feature. but maybe I was idiot, sorry, I didn't thought anything about unstable. I tried unstable sudo and it could edit symlinks by "manually" adding <code>%wheel  ALL=(ALL:ALL)   FOLLOW: ALL</code> below setenv. using security.sudo.configFile doesn't work someway.
I'm cloning repo to try latest release and I think it's good to have latest release on unstable though. I'm sorry for the trouble.
Using latest release now, I think adding on extrarule inside modules/security/sudo.nix is needed now.

**Comment by btwiusegentoo** [comment]
I will close for now. Maybe make PR in the future.
