### ISSUE TITLE
RFP: matrix-dimension

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#93095]
**Project description**
A selfhostable Matrix integrations manager.

Useful for setting up bridges in already existing rooms, adding a variety of bots and the possibility for embeds of 3rd-party services. Check the homepage for a detailed list.

All this is functionality that one can currently only get by using the hosted, closed-source `scalar.vector.im` service.

**Metadata**

* homepage URL: https://dimension.t2bot.io/
* source URL: https://github.com/turt2live/matrix-dimension
* license: gpl3
* platforms: linux, darwin

**Remark**

I fail spectactularly at packaging nodejs. In particular I gave node2nix a try with this project and one library called sharp, an image processing library, tries to download it's dependencies during build time.

```
$ git clone https://github.com/turt2live/matrix-dimension.git
$ cd matrix-dimension
$ nix run nixpkgs.nodePackages.node2nix
$ node2nix -i package.json -l package-lock.json 
$ nix-build -A package
[...]
> sharp@0.21.3 install /nix/store/gs53lqqw9b81l8q0mscgal0gj77qghda-node_matrix-dimension-1.0.0/lib/node_modules/matrix-dimension/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
/nix/store/gs53lqqw9b81l8q0mscgal0gj77qghda-node_matrix-dimension-1.0.0/lib/node_modules/matrix-dimension/node_modules/sharp/install/libvips.js:78
          throw err;
          ^

Error: getaddrinfo ENOTFOUND github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'github.com'

make: Entering directory '/nix/store/gs53lqqw9b81l8q0mscgal0gj77qghda-node_matrix-dimension-1.0.0/lib/node_modules/matrix-dimension/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
   25 | #include <vips/vips8>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:134: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/nix/store/gs53lqqw9b81l8q0mscgal0gj77qghda-node_matrix-dimension-1.0.0/lib/node_modules/matrix-dimension/node_modules/sharp/build'
```

I'm stuck and asking for help.

Poking people already taking part in the matrix ecosystem:
@pacien
@Ralith 
@roblabla 
@Ekleog
@Ma27
@kampka

**Comment by pacien** [comment]
> I gave node2nix a try with this project and one library called sharp, an image processing library, tries to download it's dependencies during build time.

You can try adding libvips [as a build input][node2nix-native-dep] and see whether sharp's install script detects and uses it instead of trying to download its own copy. Otherwise, I think you'll have to patch sharp to disable this behaviour.

[node2nix-native-dep]: https://github.com/svanderburg/node2nix#adding-unspecified-dependencies

**Comment by yrd** [comment]
@mweinelt Have you had any success packaging the `sharp` library? According to [here](https://github.com/lovell/sharp/blob/master/lib/libvips.js#L93-L95) and [here](https://github.com/lovell/sharp/blob/master/package.json#L153), it seems to depend on libvips >= 8.11.3, which is present in the unstable branch. Sharp finds to find the library using pkg-config, and this seemed to work for me (on another project with this dependency), maybe you can adapt it:

```nix
{ pkgs ? import <nixpkgs> { inherit system; }
, system ? builtins.currentSystem
, unstable ? import <nixos-unstable> { }
}:

let
  nodePackages = import ./default.nix {
    inherit pkgs system;
  };
in
nodePackages // {
  shell = nodePackages.shell.override {
    nativeBuildInputs = [ pkgs.pkg-config ];
    buildInputs = with pkgs; [ vips ];
  };
}
```

The basic override file is taken from documentation pacien linked above.

**Comment by mweinelt** [comment]
We had this packaged for hackint a while ago, but not in a format that is upstreamable.

https://github.com/andir/mirc/

We were primarily interested in the IRC bridging flow, but that didn't pan out due to issues in dimension.
