### ISSUE TITLE
Boot problems for channel 14.12

### ISSUE THREAD

**Issue by markWot** [NixOS/nixpkgs#9310]
Hello community,

I ran into some serious problems today that took my many hours to trace and fix.

I changed from the unstable channel to channel 14.12, because I ran into some trouble with some applications (redmine for example). Well after changing it on my server it worked like a charm. So I tried on my laptop. During build my machine freezed. After that It did not boot into Grub. It only showed the Lenovo logo. So I booted into a USB with NixOS 15.06. I changed the channels again from unstable to 14.12, tried a new config and rebooted. No change. After a while I gave up and formated the disk. I repeated, no change. Lastly I did not change to 14.12 and did nix-install.... and its boots again.

So maybe downgrading like this is not intended (even if it worked on my fresh server) or this is some other problem.

I have a Lenovo Y510p, 500g ssd, 1tb hdd, 16g ram.

**Comment by vcunat** [comment]
> So maybe downgrading like this is not intended

I did switch back and forth between 14.12 and unstable on a machine without any problems. I would expect that switching is not the problem itself, only some versions may not work on some HW due to driver issues (different kernel version) or other bugs.

**Comment by vcunat** [comment]
You might want to try 14.12 with a newer kernel branch, e.g. 3.18.

**Comment by MarkusWotringer** [comment]
Hello vcunat, I already have this kernel branch:

Linux y510p 3.18.20 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux

I am running NixOS 15.08pre67291.42ea0d3 (Dingo) again.
