### ISSUE TITLE
buildRustPackage: broken installCheckPhase and ignore custom installCheckPhase

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#93119]
**Describe the bug**
It is a regression since #91689.

1. When `doInstallCheck = true`, `cargo test` will be run and result in infinite `Blocking waiting for file lock on build directory`.
2. The custom `installCheckPhase` is always ignored and overrided by `cargo test`.

**To Reproduce**
1. Choose any rust package using `buildRustPackage` with custom `installCheckPhase`, like `rls`.
2. Build it with `nix build -f . rls -L`.
3. The log shows that it ignores custom `installCheckPhase` and tries to run `cargo test`, but stuck in `Blocking waiting for file lock on build directory`.

**Expected behavior**
- It should print `custom check phase` and be built successfully.
- Without setting `installCheckPhase`, it should correctly run `cargo test` without infinite blocking.

**Additional context**
#91689 (may accidentally) mixes hooks, flags, phase scripts of `checkPhase` and `installCheckPhase`, and breaks some packages (including `rls` and #91359).
I think it is poor designed and should be reverted.

**Notify maintainers**

@Flakebi 
cc @zowoq  @symphorien 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.09pre234194.8d05772134f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre234194.8d05772134f"`
 - channels(oxa): `"home-manager, mozilla"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - buildRustPackage
  - rls
# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
I'm working on a fix...
