### ISSUE TITLE
Package ugrep

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#93125]
**Project description**
magNEW ultra fast grep with interactive query UI: search file systems, source code, text, binary files, archives (cpio/tar/pax/zip), compressed files (gz/Z/bz2/lzma/xz), documents, fuzzy search, and more. A faster, user-friendly replacement for GNU/BSD grep.

**Metadata**

* homepage URL: https://github.com/Genivia/ugrep
* source URL: https://github.com/Genivia/ugrep
* license: BSD-3-Clause
* platforms: Portable (Linux, Unix, MacOS, Windows, etc), includes x86 and x64 binaries for Windows in the releases

**Comment by numkem** [comment]
I've managed to create this [package](https://gist.github.com/numkem/580dc86e848a1173843c370d2db4d25f). It seems to be working as expected.

**Comment by davidak** [comment]
@numkem looks good. do you want to make a pull request?
