### ISSUE TITLE
suspend does not trigger, despite desktopManagerHandlesLidAndPower = false

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#9313]
I've noticed recently that this option has mostly stopped working for me. Occasionally closing the laptop lid will prompt a suspend (as it should), but most of the time, it appears to be entirely ignored. Prior to maybe this week (not sure of the exact time), it always worked.

I am running slim and i3, and have reproed this with linux 4.0 and 4.1

I am on commit 6a99539d72c760ecdc641e5c18c83ff38138b452 of nixpkgs

**Comment by anderspapitto** [comment]
for example, here's some output from journald that shows suspend triggering twice out of several lid closes

```
$ journalctl -b0 -u systemd-logind
-- Logs begin at Sat 2015-02-14 17:45:21 PST, end at Mon 2015-08-17 17:40:51 PDT. --
Aug 17 17:25:43 gurney systemd[1]: Starting Login Service...
Aug 17 17:25:43 gurney systemd-logind[675]: New seat seat0.
Aug 17 17:25:43 gurney systemd-logind[675]: Watching system buttons on /dev/input/event3 (Power Button)
Aug 17 17:25:43 gurney systemd-logind[675]: Watching system buttons on /dev/input/event6 (Video Bus)
Aug 17 17:25:43 gurney systemd-logind[675]: Watching system buttons on /dev/input/event1 (Lid Switch)
Aug 17 17:25:43 gurney systemd-logind[675]: Watching system buttons on /dev/input/event2 (Sleep Button)
Aug 17 17:25:43 gurney systemd-logind[675]: Watching system buttons on /dev/input/event4 (ThinkPad Extra Buttons)
Aug 17 17:25:43 gurney systemd[1]: Started Login Service.
Aug 17 17:25:47 gurney systemd-logind[675]: New session 1 of user anders.
Aug 17 17:26:06 gurney systemd-logind[675]: Lid closed.
Aug 17 17:26:09 gurney systemd-logind[675]: Lid opened.
Aug 17 17:26:18 gurney systemd-logind[675]: Lid closed.
Aug 17 17:26:20 gurney systemd-logind[675]: Lid opened.
Aug 17 17:39:43 gurney systemd-logind[675]: Lid closed.
Aug 17 17:39:43 gurney systemd-logind[675]: Suspending...
Aug 17 17:39:50 gurney systemd-logind[675]: Lid opened.
Aug 17 17:39:50 gurney systemd-logind[675]: Operation finished.
Aug 17 17:40:30 gurney systemd-logind[675]: Lid closed.
Aug 17 17:40:30 gurney systemd-logind[675]: Suspending...
Aug 17 17:40:35 gurney systemd-logind[675]: Lid opened.
Aug 17 17:40:35 gurney systemd-logind[675]: Operation finished.
Aug 17 17:40:47 gurney systemd-logind[675]: Lid closed.
Aug 17 17:40:51 gurney systemd-logind[675]: Lid opened.
```

**Comment by anderspapitto** [comment]
I've updated to the latest unstable (2c933ad) and this behavior still persists

**Comment by lethalman** [comment]
Try:

```

  services.logind.extraConfig = ''
    HandleLidSwitchDocked=suspend
  '';
```

**Comment by anderspapitto** [comment]
Ok, I'll give that a go.

However, note from my description that sometimes (maybe 15% of lid closes) the laptop does suspend correctly, which wouldn't seem to fit with logind not knowing what action to take.

**Comment by anderspapitto** [comment]
I added that to my config, rebuilt and restarted systemd-logind. The issue still persists - sometimes suspend triggers, sometimes not.

Also note that I am never using an actual docking station and/or external monitors - however sometimes a usb keyboard and/or mouse

**Comment by anderspapitto** [comment]
Looks like it may be the same as this issue - https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1444166

I'll close this bug until we get systemd-2.19 or higher in NixOS and I can test if the new configuration option fixes it.
