### ISSUE TITLE
Update llvm 3.5 to llvm 3.5.2

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#9314]
I tried forking and editing the nix files myself but I've messed up somewhere and polly can't seem to find some ISL functions.

Also, if possible, please add an openmp package.

**Comment by spacekitteh** [comment]
The polly bug seems to be a problem upstream. I'll submit a pull request for the 3.5.2 move anyway, but I have no idea how to create a nix file for openmp.

**Comment by vcunat** [comment]
Solved in #9315.
