### ISSUE TITLE
appimage-run is missing gmp

### ISSUE THREAD

**Issue by billop** [NixOS/nixpkgs#93169]
**Describe the bug**
AppImages assume that the gmp library is present on the system, but appimage-run does not include gmp.

**To Reproduce**
1. Download https://github.com/project-slippi/Ishiiruka/releases/download/v2.2.0/Slippi_Online-x86_64.AppImage
2. chmod +x the appimage
3. `appimage-run Slippi_Online-x86_64.AppImage`

`./AppRun: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory`

**Expected behavior**
The app should run.

**Additional context**
I believe it is because of this commit: https://github.com/AppImage/pkg2appimage/commit/368ac998d44e4f6efbec93285ad1680966157411#diff-978e30d6cb148c91d5ea873b9d6af6a6

I fixed it on my end with:
```
  environment.systemPackages = with pkgs; [
    (appimage-run.override {
      extraPkgs = pkgs: [gmp];
    })
  ];
```

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.03.2533.76adfc180c0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2533.76adfc180c0, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by t-paul** [comment]
Also affected: [OpenSCAD AppImage](https://openscad.org/downloads.html#snapshots)

**Comment by evils** [comment]
as pointed out by t-paul,
appimage specifically assumes GMP is provided by the system

https://github.com/AppImage/pkg2appimage/blob/227f2001063cf205d8010da80ed178c3797e4d37/excludelist#L219
