### ISSUE TITLE
Packaging grpc-tools from grpc-node

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#93173]
**Project description**

The https://github.com/grpc/grpc-node repository has a number of GRPC related packages usable in the Node ecosystem.

In particular the https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools tries to bring `grpc_tools_node_protoc` and `grpc_tools_node_protoc_plugin` for generating JS code from protobuf spec.

However it's using C++ code inside, and it's not really built by the `node-pre-gyp`. It only uses that `node-pre-gyp` to download a precompiled binary hosted on node-precompiled-binaries.grpc.io.

So this package doesn't work just be overriding from `node2nix` output.

```
{ pkgs ? import <nixpkgs> {} }:

let p = import ./nix/default.nix { pkgs = pkgs; };
in p.package.override (oldAttrs: {
  buildInputs = oldAttrs.buildInputs ++ [ pkgs.nodePackages.node-pre-gyp ];
})
```

The above does not work, with `nix-build`, and just produces:

```
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io
node-pre-gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
node-pre-gyp ERR! System Linux 4.19.128
node-pre-gyp ERR! command "/nix/store/rcxlrj41836ps5iqv3jikqn6h7msbjpw-nodejs-12.15.0/bin/node" "/nix/store/hzw29a3cf0ync2mn4jbwd1x5sfpqdiwi-node_grpc-tools-1.9.0/lib/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /nix/store/hzw29a3cf0ync2mn4jbwd1x5sfpqdiwi-node_grpc-tools-1.9.0/lib/node_modules/grpc-tools
node-pre-gyp ERR! node -v v12.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.9.0 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc-tools@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-07-15T11_46_32_675Z-debug.log

builder for '/nix/store/avrmmjcpa2yybrdv77n5w95q86dvsvjz-node_grpc-tools-1.9.0.drv' failed with exit code 1
error: build of '/nix/store/avrmmjcpa2yybrdv77n5w95q86dvsvjz-node_grpc-tools-1.9.0.drv' failed
```

So we need some help packaging the C++ in Nix.

**Metadata**

* homepage URL: https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools
* source URL: https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools
* license: APL2
* platforms: unix, linux, darwin, ...

**Comment by CMCDragonkai** [comment]
Attempting to do this with:

```
```nix
{ stdenv
, protobuf
, cmake
, jq
, fetchgit
, bash
}:

let
  repo = fetchgit {
    url = "https://github.com/grpc/grpc-node.git";
    sha256 = "1a7l91kxc3g7mqfqvhc3nb7zy0n21ifs5ck0qqg09qh3f44q04xm";
    fetchSubmodules = true;
  };
in
stdenv.mkDerivation {
  name = "grpc_node_plugin";
  src = repo;
  # src = "${repo}/packages/grpc-tools";
  nativeBuildInputs = [ bash cmake jq ];
  dontUseCmakeConfigure = true;
  buildPhase = ''
    bash ./packages/grpc-tools/build_binaries.sh
  '';
}
```

Didn't work... Some cmake errors.

**Comment by tobiasBora** [comment]
@CMCDragonkai I also need the `grpc_tools_node_protoc` binary produced by `grpc-node` according to https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/README.md but doing `nix-shell -p grpc-tools` does not bring this executable back

@nzhang-zh if you have an idea…

**EDIT**: seems like `grpc_tools_node_protoc` is defined as
```
$ /nix/store/6vf38sbabgii6x9fihjm0x60f34pqzx6-grpc-tools-1.12.4/bin/protoc --plugin=protoc-gen-grpc=/nix/store/6vf38sbabgii6x9fihjm0x60f34pqzx6-grpc-tools-1.12.4/bin/grpc_node_plugin
```
(fixing the hash of course)
according to https://github.com/grpc/grpc-node/blob/179dbfaeccc19bce786788a6b8e986990ab51329/packages/grpc-tools/bin/protoc.js (at least it is basically what the node script is doing). We should add one executable there that does this for these two binaries

https://github.com/grpc/grpc-node/blob/179dbfaeccc19bce786788a6b8e986990ab51329/packages/grpc-tools/package.json#L19-L21
