### ISSUE TITLE
appimage-run: depends on broken gst-plugins-base

### ISSUE THREAD

**Issue by IvarWithoutBones** [NixOS/nixpkgs#93174]
**Describe the bug**
appimage-run currently depends on gst-plugins-base-0.10.36, which has been marked broken with d034a0039d8937aca2f64d1d3911e8b71f416137. This is causing it to fail:
```
error: Package ‘gst-plugins-base-0.10.36’ in /nix/store/d6ccdwwij22dfkcpiy1asznli5n0fvyv-nixpkgs-20.09pre234801.1facbd61b17/nixpkgs/pkgs/development/libraries/gstreamer/legacy/gst-plugins-base/default.nix:55 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**To Reproduce**
1. `nix run nixpkgs.appimage-run`

**Expected behavior**
This should drop you into an environment with `appimage-run` installed.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.7, NixOS, 20.09pre234194.8d05772134f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre234194.8d05772134f"`
 - channels(ivar): `"home-manager, nixpkgs-20.09pre234801.1facbd61b17, nixos-20.09pre231796.22a81aa5fc1"`
 - nixpkgs: `/home/ivar/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: appimage-run
```

**Comment by worldofpeace** [comment]
I really don't think this could possibly depend on the old version.
We'd just need to switch everything to `gst_all_1.*`.

**Comment by ajs124** [comment]
It seems to depend on gstreamer 1.x and 0.10.x. From the looks of it, it has had these dependencies since it was initialized in  #41762 by @tilpner. That code was moved around and improved a whole bunch, but these dependencies seem to have stayed the same.
