### ISSUE TITLE
qutebrowser fails to start with webkit backend

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#93273]
The current version of qutebrowser (1.13.0, nixpkgs svn-revision: 234831.e97fdce4e1b) packaged in unstable fails to start with webkit backend. 

Forcing the backend in the resulting error dialog does nothing.

**To Reproduce**
1. set `c.backend = "webkit"` in `~/.config/qutebrowser/config.py`
2. start qutebrowser

**Screenshots**
![2020-07-16-164107_446x259_scrot](https://user-images.githubusercontent.com/11145016/87685301-8557fa00-c783-11ea-8472-c9241305b0eb.png)

**Notify maintainers**
@jagajaga @rnhmjoj @ebzzry

**Comment by rnhmjoj** [comment]
The qtwebkit backend was disabled in 8df467ebd6f50eec35f42209e2282df33f32441d. Apparently at the time there was talk about dropping the backend but eventually they decided to keep it for a while. In any case here's what the current README says about it

> The latest QtWebKit release is based on old WebKit revision with known unpatched vulnerabilities. Please use it carefully and avoid visiting untrusted websites and using it for transmission of sensitive data.

Soo, we could revert the commit but it seems it's going to be [dropped in a couple years](https://github.com/qutebrowser/qutebrowser/issues/4039#issuecomment-642067027) anyway.

> Forcing the backend in the resulting error dialog does nothing.

This is the reason, it looks like a variable that points to the qutebrowser executable is not actually resolved:
```
Traceback (most recent call last):
  File "/nix/store/nr58vw4zcr5sfw9xn7zfqxq5w2vpr9zq-qutebrowser-1.11.1/lib/python3.7/site-packages/qutebrowser/misc/quitter.py", line 193, in restart
    subprocess.Popen(args)
  File "/nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '@qutebrowser@': '@qutebrowser@'
```

**Comment by con-f-use** [comment]
I'm pretty new to nix. Let me now if this would be a viable solution: https://github.com/con-f-use/nixpkgs/commit/0e0960f5c30898448a402e6d3ffe1f86ca9a9ffe and I'll make the PR

**Comment by rnhmjoj** [comment]
You can just revert the commit I mentioned: that should take care of also enabling qtwebkit by default, which is probably what you want. To make a PR you should target the master branch, also take a look at the [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

**Comment by con-f-use** [comment]
Hmm... I don't really know, what to make of this part:

```nix
  postFixup = lib.optionalString (! withWebEngineDefault) ''
    wrapProgram $out/bin/qutebrowser --add-flags "--backend webkit"
  '';
```

in the current version it reads:

```nix
   postFixup = ''
     wrapProgram $out/bin/qutebrowser \
      "''${gappsWrapperArgs[@]}" \
      "''${qtWrapperArgs[@]}"
   '';
```
and reverting just the other changes gives me build-errors.

**Comment by rnhmjoj** [comment]
Uhm, try something like this:
```
   postFixup = ''
     wrapProgram $out/bin/qutebrowser \
      "''${gappsWrapperArgs[@]}" \
      "''${qtWrapperArgs[@]}" \
      ${optionalString (! withWebEngineDefault) "--add-flags '--backend webkit'"}
   '';
```

**Comment by con-f-use** [comment]
Now I get the original import error on starting qutebrowser, when I have `withWebEngineDefault` set to `false`.  Maybe https://github.com/con-f-use/nixpkgs/commit/0e0960f5c30898448a402e6d3ffe1f86ca9a9ffe was the right solution after all, because that at least worked.
