### ISSUE TITLE
Rambox can't find GSettings schemas

### ISSUE THREAD

**Issue by billop** [NixOS/nixpkgs#93289]
**Describe the bug**

Rambox apps cause rambox to crash when attempting to upload a file.

It gives the message:
```
(rambox:15067): GLib-GIO-ERROR **: 10:09:18.390: No GSettings schemas are installed on the system
```

**To Reproduce**
1. Install rambox
2. Run rambox in terminal
2. Add any app that has file upload functionality (I tested Google Messages, Element, and Slack)
3. Attempt to upload file

**Expected behavior**
Rambox apps should be able to upload files from filesystem

**Additional context**
I've seen from browsing other issues that this has been solved before for riot-desktop at first by adding gsettings schema to the package wrapper but currently fixed by using `wrapGAppsHook` in electron. However, for some reason this did not fix the issue in Rambox.

**Notify maintainers**

@gnidorah @Ma27 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev
copying path '/nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.49, NixOS, 20.03.2533.76adfc180c0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2533.76adfc180c0, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
Add wrapGAppsHook to https://github.com/NixOS/nixpkgs/blob/df81d9a41c94792e02527dc9fa105153155f2e7c/pkgs/applications/networking/instant-messengers/rambox/default.nix#L21
