### ISSUE TITLE
nodePackages: npm2nix: add --merge key

### ISSUE THREAD

**Issue by manpages** [NixOS/nixpkgs#9332]
Feature request (which I'll most certainly implement once I have enough time, but feel free to take over).

We need ``--merge`` key for npm2nix.

Rationale — sadly, sometimes an outage hits hosts of otherwise healthy packages, as we have a lot of packages in nodePackages, probability of that happening is pretty large.

While adding a new package (I'm adding pulp now), we want to only re-scan the relevant part of npmjs repositories and then merge the output of npm2nix into ``node-packages-generated.nix``.

/cc @offlinehacker

**Comment by Profpatsch** [comment]
(triage) since npm2nix is being completely revamped, is this still relevant?

**Comment by manpages** [comment]
@Profpatsch I don't think so. I think we should close this issue, but keep in mind UX of adding new packages in revamp! Please close at your convenience.

**Comment by fpletz** [comment]
I think the consensus is to move away from big packages.nix files for every language, so we can safely close this for now.
