### ISSUE TITLE
LLVM 11

### ISSUE THREAD

**Issue by conferno** [NixOS/nixpkgs#93324]
A LLVM newer than 10.0 is required to build Chromium 86 (current dev version)

**Comment by vcunat** [comment]
The _newest_ released LLVM is 10.0.0, but 11.0.0 should have a RC very soon (I presume chromium needs >= 11).

**Comment by conferno** [comment]
Google fixed my "LLVM 11" query to "LLVM 12", so I trusted them :)

![](https://archive.is/IwbKi/7195791dcf8ecb9aefc00f0255b573baf5026218/scr.png)

**Comment by vcunat** [comment]
:-)  yes, master branch is heading for 12 already but 11 doesn't even have an RC yet, so consequently 12 is more visible than 11.

**Comment by primeos** [comment]
Update: LLVM 11.0.0-rc1 was released a few days ago: https://lists.llvm.org/pipermail/llvm-dev/2020-July/143839.html
There's already a draft PR: #94204
