### ISSUE TITLE
Audio USB adapter does not work with pulseaudio

### ISSUE THREAD

**Issue by Mesabloo** [NixOS/nixpkgs#93335]
**Describe the bug**
Running NixOS 20.03, I haven't been able to make my USB sound card adapter work. Everything seems to be correctly recognized in `pavucontrol`, but the sound played from the USB adapter is very very slow. It also seems to affect video playback speed on `brave`.

**To Reproduce**
1. Install NixOS 20.03
2. add
    ```nix
    sound.enable = true;
    hardware.pulseaudio = {
      enable = true;
      support32Bit = true;
      package = pkgs.pulseaudioFull;
    };
    ```
    to your `/etc/nixos/configuration.nix`
3. Plug-in a USB sound card (might be relevant to include the [reference of my product](https://www.amazon.com/UGREEN-External-Converter-Adapter-Desktops/dp/B06XP5R449/ref=sr_1_5?crid=2XE1D19ERP60J&dchild=1&keywords=ugreen+usb+audio+adapter&qid=1594972532&sprefix=ugreen+usb%2Caps%2C318&sr=8-5))

**Expected behavior**
The sound outputted has a normal speed and is audible.

**Screenshots**
Working as expected when the jack is selected in `pavucontrol`: https://imgur.com/a/h80pTyC
Not working as expected when the USB adapter is selected in `pavucontrol`: https://imgur.com/a/Pst09BC

**Additional context**
On an old NixOS installation (I believe was NixOS 19.03, linux kernel 4.19), the USB sound card adapter worked as expected. I haven't been able to pinpoint exactly when (what version) it stopped working.
The adapter has no problem, as it is working on Windows, on my phone, and on my old Manjaro setup (which I overwrote for NixOS) running the 5.4 linux kernel with pulseaudio. I believe this is a NixOS-only problem related to the `pulseaudio` package.
Downgrading the linux kernel to 4.19 (this was the kernel of my old NixOS installation) does not help. Reintroducing the working configuration with channel updates (19.03 -> 20.03) make the bug appear on the previously working configuration.
There are no errors regarding `pulseaudio` in `journalctl` and `dmesg` reports a correctly registered USB audio interface.

I include my [`/etc/nixos/configuration.nix`](https://pastebin.com/dGpWmx6F) cleaned (without any comments), if it can be of any help.
I also include my [`/etc/nixos/hardware-configuration.nix`](https://pastebin.com/5jBvHsVJ).
My [`home-manager`](https://github.com/rycee/home-manager) can be found [here](https://github.com/mesabloo/nix-config) if needed (those are the files that go in `~/.config/nixpkgs`).

**Metadata**
Result of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.7, NixOS, 20.03.2491.6a00eba02a3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(mesabloo): `"home-manager, nixos-unstable-20.09pre233323.dc80d7bc4a2, nixpkgs-20.09pre233849.1d801806827"`
 - channels(root): `"home-manager, nixos-20.03.2491.6a00eba02a3, nixos-unstable-20.09pre233323.dc80d7bc4a2"`
 - nixpkgs: `/home/mesabloo/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- pulseaudio
```

**Comment by davidak** [comment]
I don't have any issues with USB sound devices.

![Screenshot from 2020-07-18 06-01-55](https://user-images.githubusercontent.com/91113/87844316-5abd8c80-c8bc-11ea-9550-425490342955.png)

Tested with:

- plugable USB Audio Adapter
- Sharkoon Gaming DAC Pro S

Pulseaudio is enabled by Pantheon desktop using `hardware.pulseaudio.enable = mkDefault true;`. Maybe test with the default package?

---

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"home-manager-20.03, nixos-20.03.1950.48723f48ab9, nixos-hardware, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Mesabloo** [comment]
The default package neither worked for me. I tried putting the full package to see whether it would work or not, which turned out not to be the case, unfortunately.

I have been able to reproduce this on a clean NixOS 20.03 install with only KDE and the sound enabled, on my other computer.
I also wanted to try directly in the graphical installer, just to see if it works, but haven't done it at the moment.

I don't think the issue comes from the adapter, as it correctly works elsewhere...

**Comment by wmertens** [comment]
Can you inspect the kernel logs to see if there's anything interesting? `journalctl -k`

**Comment by Mesabloo** [comment]
As far as I can see, everything seems ok regarding sound devices.
```
[...]
Jul 20 08:58:43 subsystem kernel: snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
Jul 20 08:58:43 subsystem kernel: snd_hda_intel 0000:00:1f.3: enabling device (0000 -> 0002)
[...]
Jul 20 08:58:43 subsystem kernel: snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC233: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
Jul 20 08:58:43 subsystem kernel: snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
Jul 20 08:58:43 subsystem kernel: snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
Jul 20 08:58:43 subsystem kernel: snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
Jul 20 08:58:43 subsystem kernel: snd_hda_codec_realtek hdaudioC0D0:    inputs:
Jul 20 08:58:43 subsystem kernel: snd_hda_codec_realtek hdaudioC0D0:      Mic=0x1b
Jul 20 08:58:43 subsystem kernel: input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1f.3/sound/card0/input24
Jul 20 08:58:43 subsystem kernel: input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input25
Jul 20 08:58:43 subsystem kernel: input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input26
Jul 20 08:58:43 subsystem kernel: input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input27
Jul 20 08:58:43 subsystem kernel: input: HDA Intel PCH HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input28
Jul 20 08:58:43 subsystem kernel: input: HDA Intel PCH HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input29
[...]
Jul 20 08:58:43 subsystem kernel: usbcore: registered new interface driver snd-usb-audio
Jul 20 08:58:43 subsystem kernel: audit: type=1334 audit(1595228323.015:84): prog-id=57 op=LOAD
Jul 20 08:58:43 subsystem kernel: audit: type=1334 audit(1595228323.015:85): prog-id=58 op=LOAD
Jul 20 08:58:43 subsystem kernel: audit: type=1334 audit(1595228323.055:86): prog-id=59 op=LOAD
Jul 20 08:58:43 subsystem kernel: audit: type=1334 audit(1595228323.055:87): prog-id=60 op=LOAD
Jul 20 08:58:43 subsystem kernel: audit: type=1334 audit(1595228323.235:88): prog-id=61 op=LOAD
[...]
```

(here is the full log: https://pastebin.com/6aR6YWGy)

**Comment by wmertens** [comment]
Well, since it works in other distros, I would try comparing the full
system log in NixOS and a working distro.

Wait until the system is loaded fully, then start logging, plug in the
device and play a sound.

Compare these logs. Also compare versions of everything touching audio.

Wout.

**Comment by Mesabloo** [comment]
I ended up doing a clean install of two NixOS.
One for my main computer, and one for my other computer.

I tried creating new users (instead of the basic `mesabloo` one I always create) and the audio worked correctly through the USB adapter on the first installation (the other computer).
The second installation is done (need to reinstall my entire working environment) and the audio also seems to work flawlessly through the USB adapter.

I'm wondering whether I add some file in my home folder that caused pulseaudio to not work correctly or something, but I absolutely have no clue at this point.
I'll reinstall my working environment, switch back to my old account name (praying for it not to be cursed) and see if it still works. If yes, I will close this issue as the problem is not happening anymore. However I don't know why it was happening in the first place.

**Comment by Mesabloo** [comment]
Everything finished downloading. I had a little bit of trouble with one thing, but it is kinda solved, and unrelated to this issue.
On the other hand, my USB adapter correctly picks the audio now. I have yet to test my microphone but I believe it will work just as good.

I still have no clue on what may have caused this issue. Probably some leftover files from my old Linux installations. But I can't seem to understand how those might have influenced the new system that much (I am even more perplex as I tried to move only the config that wasn't working and it made the same problem on another problem). Every is a bit weird, but in the end it works.
As said earlier this day, I'm closing this issue because the problem is solved.

Thanks everyone for your time. :smile:
