### ISSUE TITLE
zoom-us: meeting recordings have no sound

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#93341]
**Describe the bug**
Zoom-us recordings have no sound, tested on three different NixOS machines, other non-NixOS Linux machines work well.

**To Reproduce**
1. Open `zoom-us`.
2. Start a meeting.
3. Have someone record it.
4. Wait for conversion to finish.
5. Play it → no sound.
6. Verify with `ffmpeg -i zoom_0.mp4` → no sound stream.
7. Also, `audio_only.m4a` file is just 292 **bytes**.

**Expected behavior**
To have sound stream muxed into the resulting `mp4` file.

**Screenshots**
n/a

**Additional context**
n/a

**Notify maintainers**
@danbst @tadfisher @doronbehar

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.18, NixOS, 20.03.2506.68c599acd58 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(m): `""`
 - channels(root): `"nixos-20.03.2506.68c599acd58"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute: pkgs.zoom-us
module:
```

**Comment by doronbehar** [comment]
Because it's not free software I see no way at all I can help debug this. Did it work for you on a different distro?

**Comment by michalrus** [comment]
> Because it's not free software I see no way at all I can help debug this.
I don’t know how either. :'(

> Did it work for you on a different distro?
Yes, exactly. Also I suppose that zoom.us have rather extensive tests in place, and wouldn’t release a version with such a bug.

Perhaps, as the first step, we could look at its `strace` when “Record” is being pressed — maybe it’s missing some library?

**Comment by spinus** [comment]
I cannot confirm, works for me.

**Comment by michalrus** [comment]
@spinus huh, that’s good to hear! Can you show your `nix-shell -p nix-info --run "nix-info -m"`?

**Comment by tadfisher** [comment]
Another way to test on NixOS is to enable `services.flatpak` and install the Flatpak package from here: https://flathub.org/apps/details/us.zoom.Zoom

If the Flatpak package also does not work, we may be able to rule out the package itself, but not necessarily vice-versa.

**Comment by tadfisher** [comment]
Incidentally, I am able to reproduce this on Gnome + Wayland with nixpkgs-unstable. The Zoom application does show a popup saying "Your speakers and microphone are not working correctly". Investigating.

**Comment by tadfisher** [comment]
Using `strace` reveals that Zoom requires `libfaac1.so` on its PATH. PR incoming.
