### ISSUE TITLE
LibreOffice does not get some fonts including WQY ZenHei

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#93396]
**Describe the bug**
Some fonts such as WQY ZenHei cannot be used in LibreOffice after these fonts are installed.

**To Reproduce**
1. Install `libreoffice`.
2. install `wqy_zenhei`.
3. Open LibreOffice.
4. Choose "Create: Writer Document" or "Create: Impress Presentation", etc.
5. Navigate to the choice box of fonts.
6. Notice that WQY ZenHei is not inside.

**Expected behavior**
Expected installed fonts such as WQY ZenHei to appear in the font choice box in LibreOffice Writer, LibreOffice Impress, and other pieces of software in LibreOffice suite.

**Screenshots**
![Screenshot_20200718_165917](https://user-images.githubusercontent.com/44064051/87849042-195aca80-c918-11ea-95c8-fece27a0389f.png)

**Additional context**

**Notify maintainers**

@7c6f434c

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.132, NixOS, 20.09pre234194.8d05772134f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(shamrock): `"home-manager"`
 - channels(root): `"nixos-20.09pre234194.8d05772134f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libreoffice
# a list of nixos modules affected by the problem
module:
```

**Comment by Thra11** [comment]
> 2. install wqy_zenhei.

How did you install wqy_zenheI? Did you add it to `fonts.fonts` in `/etc/nixos/configuration.nix`, or try to install it in some other way (e.g. by putting it in `environment.systemPackages` or using `nix-env` or `nix-shell`)?

I added it to my `/etc/nixos/configuration.nix` like this:
```
  fonts.fonts = with pkgs; [
    wqy_zenhei
  ];
```
Libreoffice is already in my `environment.systemPackages`. After running `nixos-rebuild switch`, libreoffice (I tested Writer) has three variants, "WenQuanYi Zen Hei", "WenQuanYi Zen Hei Mono", and "WenQuanYi Zen Hei Sharp".

**Comment by ShamrockLee** [comment]
> How did you install wqy_zenheI? Did you add it to `fonts.fonts` in `/etc/nixos/configuration.nix`, or try to install it in some other way (e.g. by putting it in `environment.systemPackages` or using `nix-env` or `nix-shell`)?

I didn't know about `fonts.fonts`. Thanks a lot for your help!
