### ISSUE TITLE
Removing qt{4,5}SDK

### ISSUE THREAD

**Issue by akaWolf** [NixOS/nixpkgs#9342]
Now we have qt{4,5}SDK, that are described in /development/qtcreator.
Well, how can SDK be described in IDE package file?

It was https://github.com/NixOS/nixpkgs/commit/45851fc39abb0172c8c16b66913e22344da8c3fb commit.

qt{4,5}SDK is Qt Creator + qt{4,5}Full.
Anyone can install Qt Creator and refer/install Qt independently.

Qt Creator is a different project, latest versions of which are only can be compiled with Qt > 5.4, which can be used standalone for non-Qt projects.
Now Qt Creator can be builded without developer build of Qt (now no need to use qt5Full for building Qt Creator, qt5 is enough).

From qt54 Qt is now modularized package. It makes impossible to handle in one qtcreator package file both: qt{4,5}SDK, since qt4 is non-modularized.

Based on the foregoing I offer to delete qt{4,5}SDK.

P.S.: If someone need qt{4,5}SDK, I offer to move definition of qt{4,5}SDK to own package file (at least) or just using qtcreator & qt{4,5}[Full] independently.

CC @bbenoist @ttuegel

**Comment by bjornfor** [comment]
If the overall functionality is preserved (being able to easily use qtcreator and qt together), I don't see why not.

**Comment by akaWolf** [comment]
@bjornfor, from my point of view, the overall functionality is preserved. You are still can use qt{4,5}[Full], just not as qt{4,5}SDK.qt, but as qt{4,5}[Full].
If someone want to mix Qt Creator and Qt framework, he can write own .nix realization of that.

**Comment by bjornfor** [comment]
What might that nix expression look like (that combine qt and qtcreator)? Why not have it in nixpkgs?

I prever distros to be mostly "invisible", in that packages behave like upstreams intend to. When you download a qt sdk and run in on a typical linux distro, you get a fully working environment out of the box. I think we should aim for the same.

But it may be a good idea to split qtcreator and qt apart in nixpkgs and create the SDK part with a wrapper?

**Comment by akaWolf** [comment]
Well, there is no Qt SDK in such distributives, as Gentoo, Arch Linux.
There is exists qt-sdk in Ubuntu, which just install Qt modules and tools and Qt.

So I don't think, that there is any need in Qt SDK package.

But if someone want, he can write that package using wrapper.

**Comment by bjornfor** [comment]
I guess in Ubuntu, installing qtcreator and qt as separate packages will still allow qtcreator to be fully useable as a qt SDK, without further configuration? On NixOS, packages typically don't "find eachother" like that.

So what I'm asking for is just that we preserve (by whatever means) the ability to get a qt SDK without having to write nix expressions.

**Comment by akaWolf** [comment]
Well, if you look at qtXSDK code, you'll find, that there is no big difference between Qt Creator and Qt SDK (only in name and in propagated build inputs).

So previous SDKs didn't solve described above problem ("qtcreator to be fully useable as a qt SDK, without further configuration").

**Comment by ttuegel** [comment]
> Well, if you look at qtXSDK code, you'll find, that there is no big difference between Qt Creator and Qt SDK (only in name and in propagated build inputs).

That can be a very big difference if the Qt Creator build remembers the location of `qmake`. Have you tried to use the Qt SDK without configuration before and after your changes?

**Comment by akaWolf** [comment]
@ttuegel, adding Qt lib to propagated build inputs instead of just build inputs don't make Qt Creator remember the location of qmake.

**Comment by akaWolf** [comment]
https://github.com/akaWolf/nixpkgs/commit/e921dec0d32b6fc70becd54664418317f8bbb5ba should make Qt Creator automatically detect Qt5 with docs.

**Comment by bjornfor** [comment]
qt{4,5}SDK is removed now (e4410bfd8565ce317d31e4a670ba50ebbfec74df), closing.

**Comment by vcunat** [comment]
Does it make sense to port these or related to 15.09?

**Comment by ttuegel** [comment]
@vcunat I thought I already did...

**Comment by vcunat** [comment]
Oh, my bad. I didn't find a27531323ed because I'm used to only follow the first parent when browsing logs.
