### ISSUE TITLE
OpentTX doesn't compile due to gcc version

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixpkgs#93438]
**Describe the bug**
`opentx` package is broken. The issue seems to be related to:

- Bug in GCC https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36566
- The fact that we use incompatible gcc version https://github.com/opentx/opentx/issues/6529

**To Reproduce**
1. `nix-env -iA nixos.opentx`

**Expected behavior**
Build should work

**Additional context**

**Notify maintainers**
@elitak @lopsided98

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre234242.c71518e75bf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(marek): `"nixos-20.09pre217537.d96bd3394b7"`
 - channels(root): `"nixos-20.09pre234242.c71518e75bf, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: opentx
# a list of nixos modules affected by the problem
module:
```

**Comment by lopsided98** [comment]
I can't reproduce this, and the build is [succeeding on Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/opentx.x86_64-linux). Perhaps you have an overlay that might be causing this failure?

**Comment by turboMaCk** [comment]
Thanks for quick reply @lopsided98 It was my mistake indeed. I used `nix-env` for installing it but I've updated channel only for root not for the user I was running nix-env with. `nix-channel --update` fixed the problem for me.
