### ISSUE TITLE
mailutils- cannot send email, cc: zfs(zed)

### ISSUE THREAD

**Issue by asdf8dfafjk** [NixOS/nixpkgs#93458]
**Describe the bug**
Mailutils cannot send email. 

I get `mail: cannot send message: Process exited with a non-zero status` when I try to send an email. 

**To Reproduce**

```
# echo hi | nix run  nixos.mailutils --command mail nixbld1 -s hi
mail: cannot send message: Process exited with a non-zero status

$ echo hi | nix run  nixos.mailutils --command mail root -s hi               
mail: cannot send message: Process exited with a non-zero status
```

**Additional context**
###Environment

I have mailutils installed by way of installing zfs. 

```
$nix-store --query --referrers /nix/store/2pc1la3wf96yz0cqfxpdfvfv19mkg64j-mailutils-3.8/
/nix/store/2pc1la3wf96yz0cqfxpdfvfv19mkg64j-mailutils-3.8
/nix/store/3zyfmdw13fw2qpaxjp0pmh3amwyrk8qy-etc-zed.rc

$nixos-option networking.hostName                                           
Value:
"Nix_Desk"


$hostname                                                                   
Nix_Desk


[~]
$cat /etc/hosts                                                             
File: /etc/hosts
127.0.0.1 localhost
127.0.1.1 Nix_Desk
::1 localhost
            192.168.225.1 router.ld
            127.0.0.1 lh.ld
            127.0.0.1 ll
            127.0.0.1 lh
            172.245.47.148 kudo.internet


```

**Possible hint**
https://unix.stackexchange.com/a/433074

**Notify maintainers**

I'm also trying to figure out why Nix_Desk is assigned `127.0.1.1` and not `127.0.0.1`. since I suspect that's where the problem is from (link above). 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by asdf8dfafjk** [comment]
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/networking.nix has some recent changes. I am going to update myself to the latest nixos code and then see if the problem persists. Will report later.

**Comment by asdf8dfafjk** [comment]
I made local changes such that 


```
$cat /etc/hosts                                                                                                             
File: /etc/hosts
127.0.0.1 localhost
::1 localhost
127.0.0.1 Nix_Desk
::1 Nix_Desk
            192.168.225.1 router.ld
            127.0.0.1 lh.ld
            127.0.0.1 ll
            127.0.0.1 lh
            172.245.47.148 kudo.internet

```

Notice that Nix_Desk now poitns to 127.0.0.1 (as a suggested solution to the problem in the hints in my original post), but the error still stands.

**Comment by asdf8dfafjk** [comment]
I cc'ed wrong maintainers, I meant @orivej @vrthra

**Comment by orivej** [comment]
I do not normally use `mail`, and running your command I get the same error. `mail root -s hi --debug-level=65535` gives me `/nix/store/…-system-sendmail-1.0/bin/sendmail exited with: 1`, and manually running this command prints `Unable to find system sendmail.`, so it seems that I should install `sendmail` program to use `mail`. Running `sendmail` prints:
```
The program «sendmail» is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.busybox
  nix-env -iA nixos.exim
  nix-env -iA nixos.msmtp
  nix-env -iA nixos.nullmailer
  nix-env -iA nixos.postfix
  nix-env -iA nixos.ssmtp
  nix-env -iA nixos.system-sendmail
```
At the first glance any of these options except the last seems fine, I would start with nullmailer, ssmtp, and postfix. (Install a package, see if `sendmail` and `mail` now works, uninstall if it does not.)
Hope this helps.

**Comment by asdf8dfafjk** [comment]
Sorry I haven't had time to follow up on this, I intend to change and test the zfs module.

**Comment by asdf8dfafjk** [comment]
https://github.com/NixOS/nixpkgs/pull/109345 at least fixes part of the problem where the user doesn't
