### ISSUE TITLE
nixos-rebuild switch kills bluetooth keyboard

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#93461]
I have a BLE keyboard, and every time I run `nixos-rebuild switch` and the kernel changes (not sure), it kills my connection and I need to reboot.

I'm guessing it's because the kernel modules are part of the activation and `/run/current-system` already contains the new kernel.

The connection drops when systemd does a bunch of service stop/starts. I've not been able to ascertain exactly what kills it.

Anyway, it seems to me that we also need a `/run/current-kernel`, since we can't switch it without rebooting, unlike `/run/current-system`.

**Comment by rnhmjoj** [comment]
Are you sure it's the kernel and not the `bluetooth` service? For me it's enough to restart that to lose connections for a couple seconds.

**Comment by wmertens** [comment]
Hmm right. Not at my computer right now, I'll check if restarting the
service does the same thing

Wout.

**Comment by wmertens** [comment]
Ok, so restarting the bluetooth service indeed kills my BT keyboard. It actually comes right back and thinks it's connected, but no input makes it into the session. I need to suspend and resume to recover functionality.

Interesting tidbit: whenever my keyboard reconnects it gets a new virtual device: I'm at `/devices/virtual/misc/uhid/0005:000D:0000.000D/input/input61` already.

**Comment by rnhmjoj** [comment]
In any case, I think the service shouldn't be restarted by a `nixos-rebuild switch`. I know there are exclusion because I noticed a message like "Not restarting the following services: display-manager ...", but I don't know how that works.

**Comment by rnhmjoj** [comment]
Found, It's the property `X-RestartIfChanged`. I would try setting
```
  systemd.services.bluetooth.unitConfig.X-RestartIfChanged = false;
```
and see if this solves the connection issue.

**Comment by rnhmjoj** [comment]
ping

**Comment by wmertens** [comment]
Oh wow sorry I missed this. Actually I recently did an upgrade without encountering issues :thinking: I'll try to reproduce the problem and then I'll apply this change.

**Comment by rnhmjoj** [comment]
Thank you

**Comment by wmertens** [comment]
@rnhmjoj indeed, this fixes the problem. I'd make a PR, but I can't find any other examples of X-RestartIfChanged being used in modules :-/

**Comment by wmertens** [comment]
This is fixed in master now
