### ISSUE TITLE
Replacing protonvpn-cli naming

### ISSUE THREAD

**Issue by privateseabass** [NixOS/nixpkgs#93478]
Protonvpn-cli is version 1.1.2 (no longer supported and recommended against using)
Protonvpn-cli-ng is version 2.2.4
@offlinehacker would like to init a GUI version called protonvpn-linux-gui and change protonvpn-cli-ng to protonvpn-linux-cli.

What are the thoughts on replacing protonvpn-cli with protonvpn-cli-ng and making protonvpn-linux-gui into protonvpn-gui?

**Comment by offlinehacker** [comment]
Ok, so i agree with naming `protonvpn-cli` and `protonvpn-gui` and to drop old `protonvpn-cli` and rename `protonvpn-cli-ng` to `protonvpn-cli`.

**Comment by offlinehacker** [comment]
If have something like macos version, we can still name if `protonvpn-macos` or something like this or just have a smart way to provide right version.

**Comment by offlinehacker** [comment]
Ok, let's wrap this up, by thumbs up i assume we agree, so i will continue with merging pull request and closing this issue.
