### ISSUE TITLE
pango-view don't work

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#93491]
**Describe the bug**

I want to preview a font (https://github.com/NixOS/nixpkgs/issues/93108). pango-view fails to do that.

**To Reproduce**

pango-view works with different backends. all don't work

```
nix-env -iA nixos.fira-code
nix run nixpkgs.pango

pango-view --backend=cairo ~/.nix-profile/share/fonts/truetype/FiraCode-Bold.ttf

pango-view --backend=xft ~/.nix-profile/share/fonts/truetype/FiraCode-Bold.ttf

$ pango-view --backend=ft2 ~/.nix-profile/share/fonts/truetype/FiraCode-Bold.ttf
pango-view: When running ImageMagick 'display' command: Failed to execute child process “display” (No such file or directory)

$ pango-view --backend=x ~/.nix-profile/share/fonts/truetype/FiraCode-Bold.ttf
pango-view: Available --backend options are: cairo/xft/ft2
```

so https://linux.die.net/man/1/pango-view is wrong :|

with cairo and xft, a tiny window opens with white background. that can even be exported
![Screenshot from 2020-07-20 00-23-16](https://user-images.githubusercontent.com/91113/87886658-3cbc6d00-ca1f-11ea-8f6e-7deba389b542.png)

`pango-view --no-display --output=foo.png --backend=cairo ~/.nix-profile/share/fonts/truetype/FiraCode-Bold.ttf`

**Expected behavior**
get font preview

**Additional context**
I use the Pantheon desktop. Any reason why that could lead to this problem? @worldofpeace elementary OS even use pango and cairo themselves https://elementary.io/open-source

**Notify maintainers**
cc pango maintainer @7c6f434c

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.8, NixOS, 20.03.2611.bb8f0cc2279 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"home-manager-20.03, nixos-20.03.2611.bb8f0cc2279, nixos-hardware, nixos-unstable-20.09pre234242.c71518e75bf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pango
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
`pango-view` is for viewing texts, not font files. The file it expects is a text file so when you pass it a binary file it will not do anything.

You can use it for installed fonts like: `pango-view --font 'Fira Code Bold' --text 'Quick brown fox jumped over the lazy dog.'`. Or you can use some other tool like `font-manager` or `gnome-font-viewer`.

**Comment by davidak** [comment]
Thanks. Then it's not really useful for the intended usecase.
