### ISSUE TITLE
llvm-binutils links llvm-diff to diff

### ISSUE THREAD

**Issue by DavidTruby** [NixOS/nixpkgs#93523]
**Describe the bug**
The LLVM binutils package sets diff in the path to be llvm-diff. However, llvm-diff is _not_ a replacement for POSIX diff, it's intended for diffing two LLVM IR files while ignoring non-semantic differences between the two. It doesn't operate as a drop in replacement for diff, so when trying to use a llvm-based stdenv to build anything that relies on diff the build will fail.

**To Reproduce**
1. Install llvmPackages.bintools (affects 7, 8, 9 and 10)
2. Observe that diff now points to llvm-binutils-${VERSION}/bin/diff

**Expected behavior**
diff should continue to point to GNU diff which has the expected POSIX diff behaviour.

**Additional context**
There may be other tools in llvm-binutils that shouldn't be being linked without their llvm- prefix. `as` also gets linked, and llvm-as is an LLVM IR -> LLVM bitcode assembler not a system assembler. 

**Notify maintainers**
@ggreif 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-40-generic, Ubuntu, 20.04 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(davtru01): `"home-manager, nixpkgs-20.09pre235189.d7e20ee25ed"`
 - nixpkgs: `/home/davtru01/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
:-)  The current code in `pkgs/development/compilers/llvm/*/bintools.nix` is:
```bash
   for prog in ${llvm}/bin/*; do
     ln -s $prog $out/bin/${prefix}$(echo $(basename $prog) | sed -e "s|llvm-||")
     # ...
```

**Comment by DavidTruby** [comment]
Yeah, I would propose we just remove that line from each version. The llvm- prefixed binaries are not, in general, drop in replacements for the tools they share names with. In fact I think the only one that is is llvm-cxxfilt and that doesn't even have the same spelling as the tool it replaces when the prefix is removed.

**Comment by vcunat** [comment]
I think these links were first added in b86e62d30d46, so let's at least mention @matthewbauer.  I actually don't even know much about the LLVM-related stuff.
