### ISSUE TITLE
There should be a way to set your emacs.d file in a nix expression

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#9367]
As per the title!

**Comment by jagajaga** [comment]
Now we don't have ways to create dotfiles. Only `vim` has such support, but it differs from what we want as a final result.
And there is a https://github.com/NixOS/nixpkgs/pull/9073.

**Comment by peti** [comment]
I'm closing this issue because this subject has come up dozens of times before and there's plenty of other tickets here that address all kinds of aspects revolving around the subject of how to manage your home directory ("dot files") with Nix.
