### ISSUE TITLE
Avoid setuptools_scm

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#93688]
Since .git is considered not very reproducible, we should check (at least in my case) for usages of setuptools_scm and leaveDotGit in packages.

It might be reasonable to manually or otherwise pass versioning information, which I believe is usually what the package is used for.

This has the additional advantage of probably removing a git dependency.

**Comment by deliciouslytyped** [comment]
See for example
(maybe?) https://github.com/NixOS/nixpkgs/issues/90494
https://github.com/NixOS/nixpkgs/issues/41136#issuecomment-392332099
and after it's updated, qtile.

**Comment by deliciouslytyped** [comment]
The documentation seems to be the readme (at https://github.com/pypa/setuptools_scm).
The way to provide a fallback (I didn't see anything about "overriding", but this should work for us) seems to be:
```
fallback_version: | A version string that will be used if no other method for detecting the version worked (e.g., when using a tarball with no metadata). If this is unset (the default), setuptools_scm will error if it fails to detect the version.
```

**Comment by MetaDark** [comment]
In [protontricks](https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/tools/package-management/protontricks/default.nix#L25) & [pytest-datadir](https://github.com/NixOS/nixpkgs/blob/29062cec8d214013a8e1f944d16e32c36294e0d0/pkgs/development/python-modules/pytest-datadir/default.nix#L20), I've used `SETUPTOOLS_SCM_PRETEND_VERSION`. Maybe it would make sense to add a setup hook to `setuptools_scm` to automatically set this?

However, python packages use `strictDeps` by default, so `setuptools_scm` would also need to be added to `nativeBuildInputs`, unless `strictDeps` is disabled.

**Comment by flokli** [comment]
I think we already use `SETUPTOOLS_SCM_PRETEND_VERSION` throughout nixpkgs.

What exactly is this issue trying to accomplish?

**Comment by deliciouslytyped** [comment]
Ok maybe nothing. I just wasn't aware of it.

**Comment by flokli** [comment]
Okay :-) 

The fetchers usually don't include the `.git` folder (except if `leaveDotGit` is set to true), so if `setuptools_scm` is used, it'll complain about not being able to find its version (which is why one then needs to set `SETUPTOOLS_SCM_PRETEND_VERSION`.

If there's any remaining occurences where we rely on `.git` being around for `setuptools_scm`, these should be fixed.
