### ISSUE TITLE
gnome3: calendar and gtkdialog conflict

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9369]
```
collision between ‘/nix/store/v5mlpd0bq3nxsx7h6fxj0ks535vfmm6w-gnome-calendar-3.16.2/share/icons/hicolor/icon-theme.cache’
and ‘/nix/store/g75h5dlk8rzym8ljgf4cgj04pl8m6zy6-gtkdialog-0.8.3/share/icons/hicolor/icon-theme.cache’;
use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
```

CC @lethalman

**Comment by vcunat** [comment]
So we make them depend on `hicolor_icon_theme`? It has a hook to clean those files; maybe there are some other potential advantages?

**Comment by geerds** [comment]
Yes, hicolor_icon_theme is the right way. Fixed it with 304a5e6168f7c11f975a87fd29be6a1c49e22ba6 and 50d90a2538ceb953fe3e88ae7ad29bd048b406c2

**Comment by lethalman** [comment]
About gnome packages, it's always better to use directly `gnome3.defaultIconTheme` which fixes icons on non-nixos and also propagates `hicolor_icon_theme`.

**Comment by geerds** [comment]
@lethalman thanks for the clarification, I'll fix it in a few hours
