### ISSUE TITLE
Allow fetchzip to use fetchurl's urls attribute

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#93690]
**Project description**

It appears that `fetchurl` has the ability to set multiple urls to be tried. If `fetchzip` is built on top of `fetchurl` it should be possible to have a list of mirror urls to try.

Especially when some upstream sources are broken and there's mirrors.

**Comment by panicgh** [comment]
fetchzip supports `urls` since 9f78dd4a1cb4b20c820ed98c7a69e9c6534fff71.
