### ISSUE TITLE
lxd: missing LXD LTS versions on nixos stable channel

### ISSUE THREAD

**Issue by otopetrik** [NixOS/nixpkgs#93720]
**Describe the bug**

LXD is released every month with bugfixes and new features, LXD version in stable nixpkgs stays the same, and does not get bugfixes.
There are bugfix-only LXD LTS releases, but they are not available in nixpkgs.

**Expected behavior**
Having nixpkgs containing both LXD _and_ LXD LTS packages, making it possible to run maintained version of LXD on nixos stable.

**Additional context**
Latest version in 3.x branch of LXD is [3.23](https://discuss.linuxcontainers.org/t/lxd-3-23-has-been-released/7140)
Latest version in 4.x branch of LXD is [4.3](https://discuss.linuxcontainers.org/t/lxd-4-3-has-been-released/8303)
Upstream marks LTS 4.0 as LTS, currently at [4.0.2 LTS](https://discuss.linuxcontainers.org/t/lxd-4-0-2-lts-has-been-released/8268).
There is only one version of LXD package available in each channel (3.18 in nixos-20.03, 4.2 in unstable).

It looks like LXD module already supports selecting different lxd packages:
https://github.com/NixOS/nixpkgs/blob/c24ad298133a4c94785b31f7c8c093c73bad5450/nixos/modules/virtualisation/lxd.nix#L36

It would be nice to have the option to use LTS version of LXD.

The lxd package would stay as-is with latest LXD version at the time of nixos release (LXD 3.18 in case of nixos-20.03, probably one of LXD 4.3, LXD 4.4 or LXD 4.5 in case of nixos-20.09).

The lts lxd package would start with latest _LTS_ version at the time of nixos release (probably LXD 4.0.3 or LXD 4.0.4 for nixos-20.09), and then track 4.0.x LTS releases, even in the stable channel.

**Notify maintainers**
@fpletz 
@wucke13 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.03.2634.1975b868747 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2634.1975b868747, home-manager-20.03, nixos-unstable-20.09pre234242.c71518e75bf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

$ nix-env -qaP lxd
nixos.lxd           lxd-3.18
nixos-unstable.lxd  lxd-4.2

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by adamcstephens** [comment]
I spent some time in an out of tree repo supporting both latest and LTS. Maintaining the LTS version is a non-trivial amount of effort due to the speed at which other dependency packages are updated in nixpkgs. In some cases it requires pinning downgraded versions in order to keep working.

On the bright side, latest releases of LXD are quite well tested and stable.

I'd be happy to review and help anybody who wants this to happen. Given the age of this issue, I'm going to close this for now. Please reopen or ping me if you'd like to discuss further.
