### ISSUE TITLE
Go 1.4.2 on OSX fails to build inside tmux.

### ISSUE THREAD

**Issue by miah** [NixOS/nixpkgs#9374]
Hi,

I just migrated away from homebrew to nix on my osx laptop and I'm trying to get my development environment to where I need it. For some reason, `nix -i go` is failing while executed in tmux. If I open another tab in iterm2 and `nix -i go` outside of tmux it installs without error.

    ok      net/url 0.035s
    ok      os      0.915s
    ok      os/exec 0.825s
    --- FAIL: TestNohup (0.89s)
        signal_test.go:205: ran test with -send_uncaught_sighup=1 under nohup and it failed: expected success.
                Error: exit status 127
                Output:
                nohup: can't detach from console: No such file or directory
    FAIL
    FAIL    os/signal       1.625s
    ok      os/user 0.018s
    ok      path    0.016s

... trim ...

    builder for ‘/nix/store/kxnf172fi6d3bsk1qji0l7h9p6jjmqwy-go-1.4.2.drv’ failed with exit code 1
    error: build of ‘/nix/store/kxnf172fi6d3bsk1qji0l7h9p6jjmqwy-go-1.4.2.drv’ failed

Outside of that tmux window though..

    ALL TESTS PASSED

    ---
    Installed Go for darwin/amd64 in /nix/store/14x05dmnipijz0wvmdln6ld1b89qrjaj-go-1.4.2/share/go

**Comment by domenkozar** [comment]
cc @wkennington @lethalman

**Comment by garbas** [comment]
@miah with #10543 ... does it work now on darwin?

i'm closing this ticket and if it doesn't work please open it.
