### ISSUE TITLE
Please package Open Observatory of Network Interference (OONI) Probe

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#93765]
**Project description**
The Open Observatory of Network Interference (OONI) is a free software project that aims to empower decentralized efforts in increasing transparency of Internet censorship around the world.

please package as "ooniprobe-cli" ("ooniprobe" as alias) and "ooniprobe-desktop" like used here:

- https://github.com/ooni/probe-desktop/blob/master/package.json
- https://github.com/ooni/probe-cli/blob/v3.0.6/ooni_test.go#L18

**Metadata**

* homepage URL: https://ooni.org/
* source URL:
  - https://github.com/ooni/probe-desktop
  - https://github.com/ooni/probe-cli
* license: mit (hidden in https://github.com/ooni/probe-desktop/blob/master/package.json) / BSD 3-Clause https://github.com/ooni/probe-cli/blob/master/LICENSE.md
* platforms: unix, linux, darwin, windows

**Comment by davidak** [comment]
...

**Comment by chekoopa** [comment]
Still relevant.
