### ISSUE TITLE
jetbrains.idea-ultimate: Needs FHS to run downloaded JDKs

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#93829]
**Describe the bug**
Downloaded JDKs should "just work" :tm: 

**To Reproduce**
1. Install idea-ultimate (if idea-community allows downloading JDKs then that can be used aswell)
2. Open any java project
3. file > settings - search "gradle" -> gradle jvm > download jdk... > download oracle 14 jdk
4. sync gradle with selected jdk

**Expected behavior**
It just works

**Screenshots**
![image](https://user-images.githubusercontent.com/7735145/88461288-8a632a80-cea2-11ea-9e7a-f1e97faac038.png)

**Additional context**
It's a classic "program can't find it's libraries" bug, I suppose

Output from ldd .jdks/*/bin/java

```
	linux-vdso.so.1 (0x00007ffc64dff000)
	libz.so.1 => not found
	libjli.so => /home/maciej/.jdks/openjdk-14.0.2/bin/./../lib/libjli.so (0x00007fe24126a000)
	libpthread.so.0 => /nix/store/bpgdx6qqqzzi3szb0y3di3j3660f3wkj-glibc-2.31/lib/libpthread.so.0 (0x00007fe241249000)
	libdl.so.2 => /nix/store/bpgdx6qqqzzi3szb0y3di3j3660f3wkj-glibc-2.31/lib/libdl.so.2 (0x00007fe241244000)
	libc.so.6 => /nix/store/bpgdx6qqqzzi3szb0y3di3j3660f3wkj-glibc-2.31/lib/libc.so.6 (0x00007fe241085000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/bpgdx6qqqzzi3szb0y3di3j3660f3wkj-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007fe241281000)
	libz.so.1 => not found
```

**Notify maintainers**

@edwtjo 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.52, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre235279.5717d9d2f7c, nixpkgs-20.09pre235573.b8c367a7bd0"`
 - channels(maciej): `"nixpkgs-20.09pre235573.b8c367a7bd0, solaros"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - jetbrains.idea-ultimate
# a list of nixos modules affected by the problem
module:
```

**Comment by mkg20001** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/93832

**Comment by mkg20001** [comment]
Still an issue

**Comment by gytis-ivaskevicius** [comment]
@mkg20001 and other Intellij users - may I request some input on this: https://github.com/NixOS/nixpkgs/pull/112268#issuecomment-780062673 ?
