### ISSUE TITLE
neovim: customRC causes regular config files not to be imported

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#93825]
I find it rather surprising, that when I do:

```nix
{
  # ...
  environment.systemPackages = with pkgs; [
    (neovim.override {
       configure = {  customRC = "...<some vim commands>..."; };
    })
  ];
}
```

and have a global neovim config in `/etc/...` and/or a user one in `~/.config/nvim/init.vim`, both are no longer loaded because of this line: https://github.com/NixOS/nixpkgs/blob/d800d1e884ebdc1f81f1f797d797c489ce61538f/pkgs/applications/editors/neovim/wrapper.nix#L128

Can we either change that or at least have some form of warning or hint? 

Note that the current situation means, there is no way for a normal user to have a custom neovim configuration, short of using the `-u <path to config>` option every time they start neovim.

I know, I can put something like `source $HOME/.config/nvim/init.vim` in the `customRC` string, but it took me quite some time to figure out what was going on.

@manveru @rvolosatovs @ma27

**Comment by doronbehar** [comment]
In general, Nixpkgs lacks _automatic_ documentation to configuration options of derivations. Not automatically generated configuration docs are available [here](https://nixos.org/nixpkgs/manual/#chap-packages). You are experiencing a symptom of this big issue. I'd recommend users in general to read the source code before `.override`ing a drv. Feel free to PR a documentation section to https://nixos.org/nixpkgs/manual/#chap-packages - i.e in https://github.com/NixOS/nixpkgs/tree/67ae7987e99035e8488f03eb3180851616d97c18/doc/builders/packages/

**Comment by teto** [comment]
with the latest neovimUtils utilities, you can generate the config your self and choose to not wrap the binary and write the file yourself somewhere else see https://github.com/NixOS/nixpkgs/issues/55376

**Comment by doronbehar** [comment]
I'm closing assuming OP is satisfied with our responses / got along eventually.
