### ISSUE TITLE
Vietnamese input method ibus-bamboo

### ISSUE THREAD

**Issue by thongpv87** [NixOS/nixpkgs#93828]
**Vietnamese input engine for ibus**
- Support encodings: Unicode, TCVN, VIQR, VNI, VPS, VISCII, ...
- Support input methods: Telex, Telex W, Telex 2, Telex + VNI + VIQR, VNI, VIQR, Microsoft layout
- Easy to customize
- Spell check

**Metadata**

* homepage URL: https://github.com/BambooEngine/ibus-bamboo
* source URL: https://github.com/BambooEngine/ibus-bamboo
* license: GPLv3
* platforms: Linux

**Comment by asdf8dfafjk** [comment]
Here is the code by the author of this post https://discourse.nixos.org/t/how-to-add-an-ibus-engine-into-to-nixos/8147 

Looks like it wasn't responded to.

**Comment by SuperBo** [comment]
https://github.com/NixOS/nixpkgs/pull/89176. Waited so long for it to be reviewed or merged

**Comment by thongpv87** [comment]
> #89176. Waited so long for it to be reviewed or merged

I think you should ping worldofpeace since he is maintainer of `ibus` package

**Comment by hopingstar1806** [comment]
I know this thread is old. But seem like ibus-bamboo already in NixOS repo and it work pretty well for me. Can someone close this thread?

**Comment by hopingstar1806** [comment]
Should we close this thread?

**Comment by goatastronaut0212** [comment]
I guess this thread can be closed now @thongpv87. I will maintain ibus-bamboo from now https://github.com/NixOS/nixpkgs/pull/313316.
