### ISSUE TITLE
CUDA support in onnxruntime

### ISSUE THREAD

**Issue by Zhen-hao** [NixOS/nixpkgs#93830]
we already have onnxruntime in nixpkgs. but it doesn't seem to support CUDA.
I wonder if there are other people interested in this feature.

**Comment by matthewbauer** [comment]
It looks like onnxruntime was removed in bc2b132f98b48220fa5ec148aa2ba170aeb9a891.

**Comment by Zhen-hao** [comment]
it seems this has low interest in the nix community.
I'll pick it up if I need to use it in production.
