### ISSUE TITLE
gdal: python bindings fail  on non-NixOS systems

### ISSUE THREAD

**Issue by michelk** [NixOS/nixpkgs#9386]
On linux with `nixpkgs`, gdal-python-scripts fail. Eg.

    gdal_merge.py -h
         Traceback (most recent call last):
          File "/home/michelk/.nix-profile/bin/gdal_merge.py", line 37, in <module>
            import gdal
        ImportError: No module named gdal

I have the suspicion, that the python-library-path is set to the system's path (`/usr/lib/python2.7/`).

**Comment by vbgl** [comment]
In a suitable `nix-shell`, they appear to work.

```
% nix-shell -p python gdal
$ gdal_merge.py -h
Unrecognised command option: -h
Usage: gdal_merge.py [-o out_filename] [-of out_format] [-co NAME=VALUE]*
                     [-ps pixelsize_x pixelsize_y] [-tap] [-separate] [-q] [-v] [-pct]
                     [-ul_lr ulx uly lrx lry] [-init "value [value...]"]
                     [-n nodata_value] [-a_nodata output_nodata_value]
                     [-ot datatype] [-createonly] input_files
                     [--help-general]
```

**Comment by michelk** [comment]
Thanks, I can confirm.
Any idea how to use the python-scripts directly, without calling `nix-shell`.
