### ISSUE TITLE
cq-editor aborts when started

### ISSUE THREAD

**Issue by rowanG077** [NixOS/nixpkgs#93956]
**Describe the bug**
the cq-editor application fails to launch and aborts almost immediately.

```
λ nix-shell -p cq-editor

[nix-shell:~]$ CQ-editor
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)

[nix-shell:~]$
```

**To Reproduce**
1. Type into the terminal `nix-shell -p cq-editor`
2. Type into the terminal `CQ-editor`.

**Expected behavior**
I expected cq-editor to be started.

**Notify maintainers**
@costrouc  @marcus7070

**Metadata**

```
λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.37, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre235279.5717d9d2f7c"`
 - channels(rowan.goemans): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by marcus7070** [comment]
Hi @rowanG077, unfortunately I can't reproduce on my machine from master (f52e3212cb43eabc59a2fe5b026ebd7869411604). 

I should point out that I'm on Wayland (Sway window manager), but I still run CQ-Editor with `QT_QPA_PLATFORM=xcb cq-editor`. 

Are you able to `git bisect` nixpkgs and figure out when your version broke? 

If bisecting doesn't show anything, then running `QT_DEBUG_PLUGINS=1 cq-editor` might tell us something more. For comparison I've attached a log from my machine. 
[log.txt](https://github.com/NixOS/nixpkgs/files/4987742/log.txt)

**Comment by rowanG077** [comment]
I did some investigating.

It seems the cq-editor is not properly wrapped. If I add `qt512.full` in the shell I can succesfully run cq-editor:

```
λ nix-shell -p qt512.full cq-editor

[nix-shell:~]$ CQ-editor
Namespace(filename=None)
/nix/store/gxmlv3cza16rwmk4q87nplpf0yb13v7f-python3.7-cadquery-2.0/lib/python3.7/site-packages/cadquery/utils.py:21: FutureWarning: Default walue of centerOption will change in next relase to ProjectedOrigin
  FutureWarning,
Layer manager created
Layer dimensions: 1824, 1397

[nix-shell:~]$
```

I think `wrapQtAppsHook` should be included in the `nativeBuildInputs`. See https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt.

**Comment by marcus7070** [comment]
Ah, you're right. Back when I wrote that the wrappers didn't work on Python scripts.

https://github.com/NixOS/nixpkgs/blob/f033c3470fcfccb4cad462fd555e1a2849373eb9/doc/languages-frameworks/qt.xml#L92

I'll update the nixpkgs expression to the `mkDerivationWith buildPythonPackage {` format soon, I think that's preferred over `wrapQtAppsHook`. 

It's still odd that the current nixpkgs works on one machine and not another. I should probably make a clean VM for testing this, I'll try to get that done later on today.

**Comment by marcus7070** [comment]
Finally got NixOS VMs working properly, damn this is so cool. @rowanG077, would you mind testing this on your machine for me? Stick the following in a file called `cq-editor-vm.nix`:
```
{ pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/virtualisation/qemu-vm.nix>
  ];
  virtualisation = {
    memorySize = 8096;
    diskSize = 4000;
    cores = 4;
  };

  environment.systemPackages = [ pkgs.cq-editor ];
  system.stateVersion = "20.03";

  services.xserver = {
    enable = true;
    desktopManager.plasma5.enable = true;
    displayManager.lightdm = {
      enable = true;
      autoLogin = {
        enable = true;
        user = "user";
      };
    };
  };

  users.extraUsers.user = {
    isNormalUser = true;
    extraGroups = [ "audio" ];
    createHome = true;
  };
}
```
You might want to change the virtualisation settings to suit your machine. You can also change plasma5 to xfce if you need something lighter.
Build it with the command `nix-build '<nixpkgs/nixos>' -A config.system.build.vm -I nixos-config=/home/full/path/to/cq-editor-vm.nix` (this process only took about 30 seconds :satisfied:). Run `./result/bin/run-nixos-vm` to open the QEMU VM. Then open up a terminal and test `cq-editor`.

**Comment by rowanG077** [comment]
I didn't change any settings and in the VM I can run cq-editor without issues.

**Comment by marcus7070** [comment]
Ok, so if you want to look further into this, my log shows:
```
QFactoryLoader::QFactoryLoader() looking at "/nix/store/7bkrw9385g1h5zlmdzxr0184zkcs6296-qtbase-5.12.7-bin/lib/qt-5.12.7/plugins/platforms/libqxcb.so"
  1 Found metadata in lib /nix/store/7bkrw9385g1h5zlmdzxr0184zkcs6296-qtbase-5.12.7-bin/lib/qt-5.12.7/plugins/platforms/libqxcb.so
```

My cq-editor wrapper has:
```
[nix-shell:~]$ cat $(which cq-editor)
#! /nix/store/58in3hsawf6g1adx99sphi460nzmaqxq-bash-4.4-p23/bin/bash -e
export QT_PLUGIN_PATH='/nix/store/7bkrw9385g1h5zlmdzxr0184zkcs6296-qtbase-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/gzw5hx0qp47ygn9kmyhgx2k4k52092cw-qtsvg-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/blsgzgs3ny6jdgp036rv6j3wh3hfjy4z-qtdeclarative-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/blsgzgs3ny6jdgp036rv6j3wh3hfjy4z-qtdeclarative-5.12.7-bin/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QML2_IMPORT_PATH='/nix/store/5cip2504lmh94x4g7srwwjv8s7cvb30a-qtquickcontrols-5.12.7/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QT_PLUGIN_PATH='/nix/store/1dl6kziv997nwp36nk51xd1i49ig5n55-qtwayland-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/1dl6kziv997nwp36nk51xd1i49ig5n55-qtwayland-5.12.7-bin/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
exec -a "$0" "/nix/store/dzpaw7whinw8pjmfs09wca76148xayjn-cq-editor-0.1.1/bin/.cq-editor-wrapped_"  "$@"
```

Is your cq-editor wrapper the same as mine? In particular that `QT_PLUGIN_PATH` line? And those store paths exist and contain `platforms/libqxcb.so`?

**Comment by rowanG077** [comment]
My log doesn't show anything with qtbase-5.12.7. I posted the log in my second comment!

My wrapper has:

```
[nix-shell:~]$ cat $(which cq-editor)
#! /nix/store/c4wxsn4jays9j31y5z9f83nr2cp7l4pa-bash-4.4-p23/bin/bash -e
export QT_PLUGIN_PATH='/nix/store/bbik3kdfb5chyxsam71i4cf16jk8r4ws-qtbase-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/hwhi3dbhnymipg9jmnamg4vl4hf0ryin-qtsvg-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/3mdrhyarpy1bnxfzawqvpdqqpn0n662p-qtdeclarative-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/3mdrhyarpy1bnxfzawqvpdqqpn0n662p-qtdeclarative-5.12.7-bin/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QML2_IMPORT_PATH='/nix/store/wlixawhwlc0mw80zb02mm10jnglkdf9d-qtquickcontrols-5.12.7/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QT_PLUGIN_PATH='/nix/store/zj42zkhghi586hmbpsi665wn0cpl4p4q-qtwayland-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/zj42zkhghi586hmbpsi665wn0cpl4p4q-qtwayland-5.12.7-bin/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
exec -a "$0" "/nix/store/63j7sl08acw8kjpc805vhwqr4w5r029r-cq-editor-0.1.1/bin/.cq-editor-wrapped_"  "$@"
```

I have different hashes but not sure if that indicates something is wrong...

**Comment by marcus7070** [comment]
That wrapper looks good to me. 

If I make a copy of the `cq-editor` wrapper and change all my store paths to point to nothing, ie.:
```
[nix-shell]$ cat ./cq-editor-bad 
#! /nix/store/58in3hsawf6g1adx99sphi460nzmaqxq-bash-4.4-p23/bin/bash -e
export QT_PLUGIN_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtbase-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtsvg-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtdeclarative-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtdeclarative-5.12.7-bin/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QML2_IMPORT_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtquickcontrols-5.12.7/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QT_PLUGIN_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtwayland-5.12.7-bin/lib/qt-5.12.7/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-qtwayland-5.12.7-bin/lib/qt-5.12.7/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
exec -a "$0" "/nix/store/dzpaw7whinw8pjmfs09wca76148xayjn-cq-editor-0.1.1/bin/.cq-editor-wrapped_"  "$@"
```
I can reproduce your log (just some different hashes on the store paths, as I would expect given we are probably building from different commits to nixpkgs). So that's why I'm suspecting `QT_PLUGIN_PATH`. 

When I create the VM above, my `cq-editor` wrapper is identical to the one I get through `nix-shell -p cq-editor`, is that the same for you? 

I'm running out of ideas here though. If you have the file `/nix/store/bbik3kdfb5chyxsam71i4cf16jk8r4ws-qtbase-5.12.7-bin/lib/qt-5.12.7/plugins/platforms/libqxcb.so`, then with your wrapper `cq-editor` should be able to find it.

Also, regarding the correct way to wrap cq-editor, I got my nixpkgs manuals mixed up in my earlier comment. `nativeBuildInputs = [ wrapQtAppsHook ]` still only catches ELF binaries, the current method to wrap Python scripts like CQ-editor is with `mkDerivationWith` and then `wrapQtApp` in the fixup phase, like the current `cq-editor` expression does.

**Comment by rowanG077** [comment]
Hmmm :/. In the VM the hashes in the wrapper match what I have on my normal machine just like you. I will attempt a full rebuild of my system later this week to see if this resolves the issue...

**Comment by rowanG077** [comment]
I have done a full system rebuild. The issue is gone now... No clue what it was.

@marcus7070 Thank you very much for your patience and investigation!!
