### ISSUE TITLE
lightworks needs libGL.so.1

### ISSUE THREAD

**Issue by lhrkkk** [NixOS/nixpkgs#94012]
**Describe the bug**
lightworks needs libGL.so.1

**To Reproduce**
After `nix-env -i lightworks` , when run lightworks-14.0.0, there is en error:
```
/nix/store/rsh3rqhlfi6lv4dlwr2xm4cvykccbp2z-lightworks-14.0.0/lib/lightworks/ntcardvt: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

**Additional context**
The pkg file is here `nixpkgs/pkgs/applications/video/lightworks/default.nix `

**Notify maintainers**
@antonxy

**Comment by veprbl** [comment]
Is this on NixOS?

**Comment by lhrkkk** [comment]
> Is this on NixOS?

Yes

**Comment by veprbl** [comment]
Duplicate of #80535
Also see #83702

**Comment by austinbutler** [comment]
Probably fixed by https://github.com/NixOS/nixpkgs/pull/121663. At any rate Lightworks is working now so closing.
