### ISSUE TITLE
Icons missing from Inkscape

### ISSUE THREAD

**Issue by a12l** [NixOS/nixpkgs#94080]
**Describe the bug**

There's a problem displaying almost all the icons in Inkscape. See attached screenshot.

**To Reproduce**

1. Install Inkscape from the 20.03 channel.
2. Start Inkscape

**Expected behavior**

There's actual icons showing in the application.

**Screenshots**

![Inkscape](https://user-images.githubusercontent.com/38804798/88673904-6f362c00-d0e9-11ea-960f-ae916839b7bc.png)

**Additional context**

Installed _Inkscape_ by adding it to Home Manager's `home.packages` list.

**Notify maintainers**

@jtojnar 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-201.fc32.x86_64, Fedora, 32 (Thirty Two)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(alo): `"home-manager-20.03, nixpkgs-20.09pre234801.1facbd61b17"`
 - nixpkgs: `/home/alo/.nix-defexpr/channels/nixpkgs`
```

```
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by prusnak** [comment]
Sounds like a home-manager bug

**Comment by MetaDark** [comment]
I cannot reproduce this using commit 1facbd61b17. It seems like this might be something related to your specific environment. Inkscape still loads the icons even in a pure environment for me:

![Screenshot from 2020-07-28 14:36:13](https://user-images.githubusercontent.com/382041/88707256-00080a00-d0e0-11ea-9e68-0bddc4859889.png)

**Comment by aaronjanse** [comment]
@MetaDark note that Inkscape was updated to 1.0 (https://github.com/NixOS/nixpkgs/commit/5107b24c83a4c93df9ff25bc76ef64f5883720f9) after that commit of Nixpkgs

**Comment by aaronjanse** [comment]
Although @inquisitiv3 could still be using an old version of Inkscape

**Comment by MetaDark** [comment]
Oh right, that commit is for a different channel

**Comment by inquisitiv3** [comment]
> @aaronjanse Oh right, that commit might be for a different channel. @inquisitiv3, what nixpkgs commit are you using to build inkscape with? You mentioned that it was from 20.03, but you only have a 20.09 unstable channel.

See that now. I'm actually not sure. I just assumed before now that when installing Nix the latest stable channel was chosen. Now I'm not sure if I choose the correct Home Manager channel. :S

$ inkscape --version
```
(process:36663): Gtk-WARNING **: 23:38:03.138: Locale not supported by C library.
	Using the fallback 'C' locale.
Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)
```

**Comment by aaronjanse** [comment]
> Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)

Oh, I vaguely recall having this same icon problem. I think it was fixed by globally installing an icon theme. A bad, unclean solution. But maybe this anecdote should help with debugging.

```
$ nix-env -q | grep adwa
adwaita-icon-theme-3.34.3
```

**Comment by inquisitiv3** [comment]
> > Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)
> 
> Oh, I vaguely recall having this same icon problem. I think it was fixed by globally installing an icon theme. A bad, unclean solution. But maybe this anecdote could help with debugging.
> 
> ```
> $ history 1203 | head
>  1203  nix-shell -p inkscape
>  1204  nix-env -iA nixos.gnome3.adwaita-icon-theme
> ```


$ inkscape

```
(process:38734): Gtk-WARNING **: 23:53:29.292: Locale not supported by C library.
	Using the fallback 'C' locale.

(inkscape:38734): Gtk-WARNING **: 23:53:29.301: Unable to locate theme engine in module_path: "adwaita",

(inkscape:38734): Gtk-WARNING **: 23:53:29.307: Unable to locate theme engine in module_path: "adwaita",
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
```

The error message is shown both before and after adding `gnome3.adwaita-icon-theme` to my `home.packages` list when I start Inkscape.

**Comment by aaronjanse** [comment]
Hmm. Does inkscape 1.0 work, built from nixpkgs unstable? I recall some icon issues (possibly unrelated) being fixed there

**Comment by inquisitiv3** [comment]
> Does inkscape 1.0 work, built from nixpkgs unstable? I recall some icon issues (possibly unrelated) being fixed there

I switched the Home Manager channel to the master/unstable and updated the packages. Icons works now!

**Comment by inquisitiv3** [comment]
Not sure if I should close the issue, or leave it open because it's a bug against the current stable branch?

**Comment by jtojnar** [comment]
Yeah, it seems the `strictDeps` break gdk-pixbuf setup hook too, so https://github.com/NixOS/nixpkgs/pull/68287 is not sufficient. If someone is able to test adding `gdk-pixbuf` to 20.03 as mentioned in https://github.com/NixOS/nixpkgs/pull/85169#issuecomment-653793890, feel free to open a PR.

**Comment by jtojnar** [comment]
20.03 is EOL now.
