### ISSUE TITLE
KDE Plasma 5.19

### ISSUE THREAD

**Issue by jwinnie** [NixOS/nixpkgs#94103]
Plasma 5.19 was released on June 9 but nixos-unstable still packages 5.17 (released on October 15, 2019!). What is the status on this?

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/84542
https://github.com/NixOS/nixpkgs/pull/84232

**Comment by worldofpeace** [comment]
@jwinnie From the looks of it the qt update is going to be merge very very soon, and I believe that likely means the plasma update as well.

**Comment by w4** [comment]
Is this targeting the 20.09 release @petabyteboy? :)

**Comment by petabyteboy** [comment]
It would be good to have that in 20.09, but I can not say for sure that I can completely fix up the Plasma 5.18.x PR until the freeze.

**Comment by worldofpeace** [comment]
@petabyteboy I believe last release we made a bit of an exception to try to get plasma 5.19 into the release. Considering Plasma 5.17 was released on October 15, 2019 I think this should (perhaps) be a priority. 

Are you still waiting on re-review of https://github.com/NixOS/nixpkgs/pull/84542 from @ttuegel ?

**Comment by petabyteboy** [comment]
The new GTK settings menu is not working. It was rewritten and new patches need to be written from scratch. That's the only real thing, but I don't know how and where to start with this, so the chances of getting it done in the next month or so are small if noone else takes up the task of fixing the GTK settings menu.

**Comment by ajs124** [comment]
We're on 5.20, with #110536 updating to 5.21 now, so can this be closed?
