### ISSUE TITLE
syslinux: mtools runtime dependency

### ISSUE THREAD

**Issue by KoviRobi** [NixOS/nixpkgs#9412]
Syslinux fails with  `sh: mcopy: command not found` when mtools is not installed, on 15.08pre67355.1357692 (Dingo).

To reproduce just try running `syslinux --install [device]` with mcopy not in `$PATH`.

I would do this myself but I am not sure how to manually add runtime dependencies.

**Comment by dezgeg** [comment]
This has been fixed by 985bd0808e5f0c43cd378ac4ba1fe51575a3bbd3
