### ISSUE TITLE
purescript tests fail with 'npm: callProcess: runInteractiveProcess: exec: does not exist'

### ISSUE THREAD

**Issue by MarkusBarthlen** [NixOS/nixpkgs#9413]
Currently, purescript tests fail. It seems that npm is missing during the test runs.

This seems to be related to https://github.com/fpco/stackage/issues/736.
Is there a way to make it work under NixOS or is this an upstream issue?

Linking dist/build/psci-tests/psci-tests ...
running tests
Running 2 test suites...
Test suite tests: RUNNING...
tests: npm: callProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite tests: FAIL
Test suite logged to: dist/test/purescript-0.7.3.0-tests.log
Test suite psci-tests: RUNNING...
### Failure in: completionTests:5          
expected: [":b Control.Monad.Eff",":b Control.Monad.Eff.Class",":b Control.Monad.Eff.Console",":b Control.Monad.Eff.Unsafe"]
 but got: []
### Failure in: completionTests:6          
expected: [":b Control.Monad.Eff.Class",":b Control.Monad.Eff.Console",":b Control.Monad.Eff.Unsafe"]
 but got: []
...
snip
...
### Failure in: completionTests:35           
expected: ["ST.newSTRef"]
 but got: []
### Failure in: completionTests:36           
expected: ["Control.Monad.ST.newSTRef"]
 but got: []
Cases: 37  Tried: 37  Errors: 0  Failures: 17
Test suite psci-tests: FAIL
Test suite logged to: dist/test/purescript-0.7.3.0-psci-tests.log
0 of 2 test suites (0 of 2 test cases) passed.

**Comment by peti** [comment]
A work-around was committed in https://github.com/NixOS/nixpkgs/pull/9377.
