### ISSUE TITLE
Spacemouse support for Blender?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#94191]
Has anybody ever packaged up 3D Mouse (e.g. [Spacemouse](https://www.3dconnexion.com/products/spacemouse.html)) support for Blender in Nixpkgs? Or have any tips to keep in mind before attempting to add support to NixOS/Blender?

The software is here http://spacenav.sourceforge.net/ and it seems like `spacenavd` would need to run as a NixOS service and `libspnav` would need to be made available to Blender at build-time and run-time. Right?

**Comment by prusnak** [comment]
> The software is here http://spacenav.sourceforge.net/ and it seems like `spacenavd` would need to run as a NixOS service and `libspnav` would need to be made available to Blender at build-time and run-time. Right?


Correct. I would suggest packaging `spnavcfg` too for GUI configuration.

**Comment by lukego** [comment]
Thanks @prusnak. I'm testing packaging of the basic spacenav packages now. Then have to look at making a nixpkgs module for spacenavd, haven't done a module before.

**Comment by prusnak** [comment]
You can have a look at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/trezord.nix which is a similar service (daemon for enabling hardware support).

**Comment by lukego** [comment]
Have implemented in #94234.
