### ISSUE TITLE
install-grub.pl fails when / is tmpfs

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nixpkgs#94210]
## Issue description
I'm attempting to migrate my root onto a tmpfs. When rebuilding the system, the system errors when switching configurations and the grub boot menu doesn't get properly updated. The exact error is:
```
Failed to get blkid info (returned 512) for / on none at /nix/store/...-install-grub.pl line 189.
```

**Comment by worldofpeace** [comment]
More information on your partition/filesystem layout is going to help us a bunch. Could you provide this?

**Comment by nrdxp** [comment]
Of course, my mistake, I wrote this in a hurry after an exhuasting day. Forgive my sloppiness. So I'm currently on NixOS 20.03. I need to use grub because I am using an encrypted boot parition. Here is my root file-system declaration:
```
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=2G" "mode=755" ];
  };
```

The interesting thing is that the system built and deployed the first time it was run, but once I actually booted into the system and root was on the tmpfs, I couldn't rebuild any new configurations due to the mentioned error, `nixos-rebuild` failed every time. I was only able to revert thanks to a previous boot generation.

**Comment by sheeldotme** [comment]
This is still an issue on 2.4pre20201201_5a6ddb3 with the following mount:
`tmpfs on /mnt type tmpfs (rw,relatime)`

```
fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };
```

**Comment by nrdxp** [comment]
@sheeldotme, for now, I was successfully able to workaround this using ZFS as explained by [grahamc](https://grahamc.com/blog/erase-your-darlings)

**Comment by Baitinq** [comment]
Having the same issue in the latest unstable nixos.

**Comment by buckley310** [comment]
Can someone provide a full test case for this? My machine runs tmpfs as root with grub and it works fine.

**Comment by byrongibson** [comment]
Related:  https://github.com/NixOS/nixpkgs/issues/130125

**Comment by buckley310** [comment]
A properly configured tmpfs-as-root system will not run into this issue, so the problem is going to be based in the way the machine was configured. This issue sort of looks abandoned since it's been most of a year with no response, so I'm going to close it, but if you want to re-open and post the config that exhibits this issue, I can give it a look.

**Comment by eclairevoyant** [comment]
For anyone happening upon this via search engine, this error can happen when `/boot` is part of the `tmpfs` (e.g. because you used `/boot/efi` as ESP) and you go with the default config for grub2. As mentioned above, this is misconfiguration.
