### ISSUE TITLE
Cannot change to ad2p bluetooth profile with pipewire

### ISSUE THREAD

**Issue by alexarice** [NixOS/nixpkgs#94223]
**Describe the bug**
When `config.xdg.portals.extraPortals` is set to something and `services.pipewire.enable` is true, I cannot set my bluetooth profile to ad2p, which effectively makes the sound on my computer unusable (which is unideal as setting these options was an attempt to get screen sharing working in video calls)

**To Reproduce**
1. Set `services.pipewire.enable = true`
2. Set `config.xdg.portals.enable = true; config.xdg.portals.extraPortals = [ pkgs.xdg-desktop-portal-wlr ]` (also fails with xdg-desktop-portal-kde)
3. Try to set bluetooth profile with `pactl` or pavucontrol.

**Expected behavior**
Bluetooth profile should switch

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.09pre236091.28fce082c8c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre236091.28fce082c8c, all-hies, emacs, home-manager, nixpkgs-wayland"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by colemickens** [comment]
I've tested this and am also seeing this behavior when trying to change the profile via `pulsemixer`. (and though I don't think it matters, in my case I am commanding bluetooth via `bluetoothctl`.)

**Comment by alexarice** [comment]
It turns out pipewire doesn't support ad2p yet which is why this problem arises.
A temporary workround is to build pipewire without bluetooth support with the following overlay:
```
self: super: {
  pipewire = super.pipewire.overrideAttrs (attrs: {
    mesonFlags = attrs.mesonFlags ++ [
      "-Dbluez5=false"
      "-Dbluez-backend-native=false"
      "-Dbluez-backend-ofono=false"
    ];
  });
};
```
Then bluetooth works as normal and you can still do all the wayland screen sharing stuff
