### ISSUE TITLE
`torbrowser` 9.5 unavailable

### ISSUE THREAD

**Issue by jpdoyle** [NixOS/nixpkgs#94252]
**Describe the bug**
```
trying https://dist.torproject.org/torbrowser/9.5/tor-browser-linux64-9.5_en-US.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download tor-browser-linux64-9.5_en-US.tar.xz from any mirror
```
It looks like `9.5` has been removed and there is now only `9.5.{1,2,3}` at https://dist.torproject.org/torbrowser/

**To Reproduce**
1. Try to install `torbrowser`

**Expected behavior**
Package installs

**Additional context**
Tested on NixOS with `20.03` and `unstable`.

**Notify maintainers**
@offline @matejc @doublec @thoughtpolice @joachifm @hax404 @cap

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.44, NixOS, 20.03.2304.9c42eb70cfd (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2668.7c85b915892, nixos-unstable-20.09pre236419.a45f68ccac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by colemickens** [comment]
See #94200 #94019 that both would address this.

**Comment by jonringer** [comment]
#94019  has been merged, closing ticket. Hopefully this will show up in a few days on unstable. If not, you can checkout from master branch.
