### ISSUE TITLE
New OSX changes break pure-darwin dyld

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#9432]
Any executable built with the `pure-darwin` stdenv will print "Killed: 9" when run; the culprit is our copy of dyld, which I assume is now blacklisted by the security changes Apple has made.

I'll investigate the changes and see if I can get a copy of dyld that works properly, but in the meantime, we can use `/usr/lib/dyld`. Fortunately it has no external dependencies so we don't have to poke more holes in the sandbox.

@copumpkin @jwiegley

**Comment by henrytill** [comment]
Could we close this?

**Comment by vcunat** [comment]
Yeah, from what I've heard it isn't an issue anymore.
