### ISSUE TITLE
Idris2: all compilations fail

### ISSUE THREAD

**Issue by theduke** [NixOS/nixpkgs#94381]
**Describe the bug**

There seems to be an issue with the `idris2` `0.2.0` package on `NixOS`.

Trying to compile any source file results in errors, regardless of the file content.

```bash
❯ idris2 -o hello hello.idris
Uncaught error: INTERNAL ERROR: build/ttc/hello.ttc: File Read Error
```

**To Reproduce**
1. `nix-env -iA nixos.idris2`
2. `touch hello.idris && idris2 -o hello ./hello.idris`

**Expected behavior**

The idris2 compiler works correctly.

**Notify maintainers**

@wchresta 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.09pre233323.dc80d7bc4a2 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre233323.dc80d7bc4a2"`
 - channels(theduke): `"home-manager, nixos-20.09pre236419.a45f68ccac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: idris2
# a list of nixos modules affected by the problem
module:
```

**Comment by wchresta** [comment]
I just tested it on my nixos installation with the `nixos-unstable` (which points to the same channel as you are using in your user)  and didn't have an issue.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.14, NixOS, 20.03.1998.93b68c7cc5a (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2680.c9f5211b769, nixos-hardware"`
 - channels(monoid): `"nixos-unstable-20.09pre236419.a45f68ccac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Can you try to explicitly choose the nixos-20.09pre236419.a45f68ccac4 channel you use in your user-env and try again with that?

**Comment by theduke** [comment]
Hmm, very weird. 

I nuked my `.nix-profile` and `.nix-defexpr`, re-intialized my `home-manager` setup, and then installed `idris2` again. 

It's working now. And I reckon it's pretty much impossible to trace down where this came from...
