### ISSUE TITLE
can't switch panes away from processes in GNOME system monitor

### ISSUE THREAD

**Issue by enolan** [NixOS/nixpkgs#94406]
**Describe the bug**
If I click on the "Resources" or "File Systems" buttons the display switches to the correct pane for a tiny fraction of a second then immediately switches back to proceses.

**To Reproduce**
1. Open GNOME system monitor
2. Click "resources"
3. Be disappointed

**Expected behavior**
It should stay on the pane you click on until you click on another one.

**Additional context**
I'm running Awesome WM and not the actual GNOME desktop environment. Don't know if that matters.

Also, this message is printed in the console output:
`(gnome-system-monitor:27260): dconf-WARNING **: 22:05:21.138: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files`.
It appears twice when the application starts, then appears once each time I try to change panes.

**Notify maintainers**
@hedning

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.03.2651.0a40a3999eb (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2676.38516a273cd, unstable-20.03pre200828.1e7ddf233a5"`
 - channels(enolan): `"nixos-20.03.2516.674ab2dffa5, unstable-20.09pre234236.c87c474b17a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Jiehong** [comment]
@enolan : I just tried on gnome3, and the system monitor runs just fine.
Also, I don't get the dconf warning that you get.

So, it might be an issue with Awesome WM and its interaction with Gnome System monitor.

**Comment by hedning** [comment]
Yeah, you'll probably have to enable `programs.dconf.enable = true;` in you system config.

**Comment by enolan** [comment]
That fixes it, thanks. I have to say this is pretty bad UX though.
