### ISSUE TITLE
Replacing a stdenv for an entire nixpkgs set

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#9443]
I see that there's a `config.replaceStdenv` option, but I don't want to set that field in a (user-)global config file.

For example, for the purposes of building an image, I want to build my entire set of packages with `-fPIE`. That doesn't mean I want all my normal packages to be built with the `-fPIE` stdenv.

Note that I don't just want to pass a custom `stdenv` to one package, which I know how to do. I want to pass the custom `stdenv` to a package and all its dependencies, and basically have `pkgs` such that any attribute I ask for in it will use the custom `stdenv`.

For now, I can import `all-packages.nix` and pass it a dummy config with the `replaceStdenv` attribute, but I'm hoping for a better way. Is there one?

**Comment by lethalman** [comment]
You can try `pkgs.overridePackages`.

**Comment by Profpatsch** [comment]
(triage) Can be closed I think.
