### ISSUE TITLE
python37Packages.onnx libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by Zhen-hao** [NixOS/nixpkgs#94443]
Hi, I am using the unstable branch.
When I try to import the onnx package in Python, I get the following error.

```
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/ln8r1m11ypy3a642g4vab9c06mqmpsdn-python3.7-onnx-1.7.0/lib/python3.7/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: /nix/store/6qx8ijrs82bnq60vp09pv46mdx4rnq9d-gcc-7.5.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /nix/store/ln8r1m11ypy3a642g4vab9c06mqmpsdn-python3.7-onnx-1.7.0/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by Zhen-hao** [comment]
I don't if this can be solved in the package itself. 
I managed solve this in a nix shell by adding `export LD_LIBRARY_PATH=${pkgs.stdenv.cc.cc.lib}/lib:$LD_LIBRARY_PATH` to the `shellHook`.

feel free to close this one.

**Comment by acairncross** [comment]
@Zhen-hao It sounds like it ought to be solvable, but I'm unable to reproduce your error on Linux. Are you on Darwin?

Also are you able to reproduce this with the latest unstable nixpkgs?

**Comment by Zhen-hao** [comment]
@acairncross sorry, I didn't get time to build a new environment.  
did you mean it is solved on the unstable branch?

**Comment by acairncross** [comment]
>  did you mean it is solved on the unstable branch?

It might be, I haven't seen the problem on the unstable branch, or any other branch. I'm just trying to understand if/when this problem occurs. If it's not possible to reproduce the error then I agree we can close this issue.

**Comment by Zhen-hao** [comment]
it makes sense to closes it. 
other people can use my solution as a workaround in case they have to use earlier revs.
