### ISSUE TITLE
plasma5 + i3 ignore qt theme settings

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#94482]
**Describe the bug**
When using `plasma5 + i3` session, the qt theme (and color scheme) is always set to default, even if you choose a different theme in systemsettings5.

**To Reproduce**
1. Enable `plasma5` and `i3`
2. Login using `plasma5 + i3` session
3. Change the theme in the settings

**Expected behavior**
The Qt theme and colors should match the KDE settings.

**Notify maintainers**
@ttuegel

**Comment by doronbehar** [comment]
Did you try using qt5ct?

**Comment by suhr** [comment]
No, I used the KDE settings.

**Comment by ttuegel** [comment]
It's not clear to me what "Login using plasma5 + i3 session" means, could you say more?

**Comment by suhr** [comment]
Nix creates `plasma5+i3` session, which is available in SDDM. So I logged in using this session.

**Comment by ttuegel** [comment]
> Nix creates `plasma5+i3` session, which is available in SDDM.

That's a mistake, NixOS should not be creating any sessions for Plasma, but using upstream's `plasma` session. This created configuration is not supported.

**Comment by poscat0x04** [comment]
possible dupe of https://github.com/NixOS/nixpkgs/issues/82074
