### ISSUE TITLE
Switcheroo package.

### ISSUE THREAD

**Issue by ishan9299** [NixOS/nixpkgs#94538]
There is a similar issue over here #87005 I am opening one here as there aren't any interactions going on over there. So feel free to close this.

**Project description**
It  allows to launch applications using our discrete graphics card from the menu at least in gnome. It does not work in plasma as stated by the developer [here](http://www.hadess.net/2019/12/dual-gpu-support-follow-up-nvidia.html).

It is already present in major distributions like -
+ Ubuntu
+ Fedora
+ Pop_OS!
+ Arch(via AUR)

**Metadata**

* source URL:https://gitlab.freedesktop.org/hadess/switcheroo-control/
* license: gpl3
* platforms: linux

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/95337

**Comment by ishan9299** [comment]
Shall I close the issue now or wait for the pull request to be merged?

**Comment by AndersonTorres** [comment]
Yes. The discussion would be more useful there.
