### ISSUE TITLE
[QUESTION] After installing NixOS, doesn't boot up afterward.

### ISSUE THREAD

**Issue by jcs090218** [NixOS/nixpkgs#94547]
**Describe the bug**

I am trying to install NixOS onto my laptop previously with Windows 10 installed. But after I have installed NixOS and everything works fine the first time then I restart my laptop. Windows 10 boots up instead of NixOS. 😕 What did I do wrong?

**To Reproduce**

I use rufus version `3.1.1` to build by USB boot device. The iso image is the latest version `20.03`.

**Expected behavior**

NixOS should completely overwrite my old OS, hence the Windows 10.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by prusnak** [comment]
Please post questions into discussion forum here: https://discourse.nixos.org/
