### ISSUE TITLE
 Cannot run the result of writeScriptBin when using fish shell.

### ISSUE THREAD

**Issue by guillaumecherel** [NixOS/nixpkgs#94577]
**Describe the bug**
Cannot run the result of `writeScriptBin` when using fish shell. 

**To Reproduce**

1. Create a script ./hello.sh and a derivation to package it.
./hello.sh:
```
#!/usr/bin/env bash

echo "Just saying hello:"
```

./default.nix
```
with (import <nixpkgs> {}); {
  my-hello = writeScriptBin "my-hello" ./hello.sh;`
}
```

2. Install:

````
nix-env -f . -iA my-hello
````

3. Start fish if not already running and run `my-hello`, it gives the following error:
```
$ fish
$ my-hello
Failed to execute process '/home/guillaume/.nix-profile/bin/my-hello'. Reason:
exec: Exec format error
The file '/home/guillaume/.nix-profile/bin/my-hello' is marked as an executable but could not be run by the operating system.
```

**Additional context**

The file that `which my-hello` links to in the store, i.e. `/nix/store/...-my-hello/bin/my-hello`, contains a single line which is the path to the actual hello.sh script in the nix store:
```
/nix/store/...-hello.sh
```

I suppose it is supposed to be interpreted like a script and simply run the executable file at the given path. This maybe why fish cannot run it: it expects a shebang at the beginning of an executable script. There is a shebang at the beginning of `/nix/store/...-hello.sh`, but not at the beginning of `/nix/store/...-my-hello/bin/my-hello`. Perhaps bash can execute such files without a shebang, which would explains why it works when I use bash as my shell but not fish.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
❯ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev
copying path '/nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.03.2648.69af91469be (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(guillaume): `""`
 - channels(root): `"nixos-20.03.2648.69af91469be, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.writeScriptBin
# a list of nixos modules affected by the problem
module:
```

**Comment by guillaumecherel** [comment]
As a workaround (or maybe a solution) using `writeShellScriptBin` works as it adds the shebang automatically at the head of the file. In the end, I'm not sure if this issue should be considered a bug of `writeScriptBin` or not and if this behaviour should be documented somewhere.

**Comment by Ma27** [comment]
The problem isn't related related to `fish`, `writeScriptBin` expects the scripts *content*, not a path as second argument:

``` nix
with import ./. {};
writeScriptBin "foo" ''
  #! ${runtimeShell} -e
  echo hello
''
```

In your case you probably want to do sth like this:

``` nix
with import ./. {};
writeScriptBin "foo" (builtins.readFile ./hello.sh)
```

**Comment by guillaumecherel** [comment]
Indeed, `builtins.readFile` was exactly what I was missing. Thanks!
