### ISSUE TITLE
Zig fails to build

### ISSUE THREAD

**Issue by svmhdvn** [NixOS/nixpkgs#94613]
**Describe the bug**
`nixpkgs.zig` fails to build on nixpkgs master

**To Reproduce**
1. `nix-build --no-out-link -A zig`

**Additional context**
Terminal output
```
Scanning dependencies of target zig0
[ 98%] Building CXX object CMakeFiles/zig0.dir/src/main.cpp.o
[ 98%] Building CXX object CMakeFiles/zig0.dir/src/stage2.cpp.o
[ 99%] Linking CXX executable zig0
[ 99%] Built target zig0
Scanning dependencies of target zig_build_libstage2
: CommandLine Error: Option 'polly' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
make[2]: *** [CMakeFiles/zig_build_libstage2.dir/build.make:77: CMakeFiles/zig_build_libstage2] Error 1
make[1]: *** [CMakeFiles/Makefile2:252: CMakeFiles/zig_build_libstage2.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
builder for '/nix/store/bix9iqj77x932pzvlwdn5f8zhrx7qifs-zig-0.6.0.drv' failed with exit code 2
error: build of '/nix/store/bix9iqj77x932pzvlwdn5f8zhrx7qifs-zig-0.6.0.drv' failed
```

**Notify maintainers**
@andrewrk 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.09pre236419.a45f68ccac4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre236419.a45f68ccac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/94559
