### ISSUE TITLE
Update package ssh-audit

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#94618]
**Project description**
SSH server & client auditing (banner, key exchange, encryption, mac, compression, compatibility, security, etc)
Latest version: 2.2.0, forked from https://github.com/arthepsy/ssh-audit

**Metadata**

* homepage URL: https://www.ssh-audit.com
* source URL: https://github.com/jtesta/ssh-audit
* license: mit
* platforms: unix, linux

**Comment by mweinelt** [comment]
I looked into this and their project setup is a bit off, which makes it a bit harder than necessary to package.

They do plan to start fixing things after the next release though.

https://github.com/jtesta/ssh-audit/issues/46

**Comment by Izorkin** [comment]
Thanks. I didn't know how to fix the testPhase, so I created a request.
