### ISSUE TITLE
Kotlin native

### ISSUE THREAD

**Issue by vctibor** [NixOS/nixpkgs#94627]
**Project description**
Kotlin can compile to native targets but this version of compiler is distributed separately from main kotlin compiler distribution. Please add kotlin native to either kotlin ackage or its own package.

**Metadata**

* homepage URL: https://kotlinlang.org/
* source URL: https://github.com/JetBrains/kotlin/releases/tag/v1.3.72
* license: apache
* platforms: linux, darwin

**Comment by vctibor** [comment]
Created PR: https://github.com/NixOS/nixpkgs/pull/94671

I'll appreciate comments.

**Comment by fabianhjr** [comment]
Closed by the merging of #142709
