### ISSUE TITLE
erlang_odbc not building correctly on OSX/darwin

### ISSUE THREAD

**Issue by mradke** [NixOS/nixpkgs#94644]
**Describe the bug**
On OSX (Catalina, v. 10.15.5) the odbc erlang support is not correctly built.

**To Reproduce**
1. Run `nix-shell -p unixODBC erlang_odbc` on Mac OS
2. Run `erl`
3. in the repl type `odbc:start().`
4. You'll get the exception "undefined function odbc:start/0"

**Expected behavior**
When following the steps above, `erl` should answer `ok`

**Additional context**
When building on the machine (with a local clone of nixpkgs) I noticed the following warning:

```
*********************************************************************
**********************  APPLICATIONS DISABLED  **********************
*********************************************************************

jinterface     : No Java compiler found
odbc           : ODBC library - link check failed
```

Also this is not a problem with NixOS. There everything is working as expected.

**Notify maintainers**
@sjmackenzie @couchemar @gleber 

**Metadata**

- system: `"x86_64-darwin"`
- host os: `Darwin 19.5.0, maxOS 10.15.5`
- multi-user?: `no`
- sandbox: `no`
- version: `nix-env (Nix) 2.3.7`
- channel($USER): `"nixpkgs-20.09pre236343.78215a8395f"`
- nixpkgs: `/Users/${USER}/.nix-defexpr/channels/nixpkgs`

**Comment by gleber** [comment]
Sorry, I do not have macOS handy nowadays to test this stuff.

**Comment by mradke** [comment]
Could you probably give me a pointer where to start looking for the root of this problem?
How would you approach the debugging?

I don't mind figuring this out by myself, but I really have no clue where to start looking :smile: I already tinkered with `genric-builder.nix` but to no avail.

The next step I would take is to download and compile the erlang sources manually though I'm not sure if there are other things I could check first.

**Comment by DianaOlympos** [comment]
I would advise to try to build erlang locally, you can just try `nix-build -A erlang`. That should give you the logs from the configure step that is trying to figure out if odbc should be build. From there, you should be able to get a bit more ideas about what made that check fail.

**Comment by mradke** [comment]
The log for the configure step is this:
```
=== Running configure in /private/tmp/nix-build-erlang-22.3-odbc.drv-0/source/lib/odbc ===
./configure '--prefix=/nix/store/f34wl56wrxxpga6lcm0xwvz1xhjfsks1-erlang-22.3-odbc' '--with-ssl=/nix/store/qd3zw6h4fm0k0nlrya02xi921m4n74fb-openssl-1.1.1g-dev' '--enable-threads' '--enable-smp-support' '-
-enable-kernel-poll' '--enable-hipe' '--with-odbc=/nix/store/2z0cwqcwk21ai7mspflgx0ry4c7jr92k-unixODBC-2.3.7' '--enable-wx' '--enable-darwin-64bit' --disable-option-checking --cache-file=/dev/null --srcdi
r="/private/tmp/nix-build-erlang-22.3-odbc.drv-0/source/lib/odbc"
checking build system type... x86_64-apple-darwin17.7.0
checking host system type... x86_64-apple-darwin17.7.0
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for mixed cygwin or msys and native VC++ environment... no
checking for mixed cygwin and native MinGW environment... no
checking if we mix cygwin with any native compiler... no
checking if we mix msys with another native compiler... no
checking whether make sets $(MAKE)... yes
checking for ld.sh... ld
checking for rm... /bin/rm
checking for connect... yes
checking for gethostbyname... yes
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /nix/store/9lhg46zfb4i3sl7faaknhfimh3pliwhw-gnugrep-3.4/bin/grep
checking for egrep... /nix/store/9lhg46zfb4i3sl7faaknhfimh3pliwhw-gnugrep-3.4/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for sql.h... yes
checking for sqlext.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for struct sockaddr_in6.sin6_addr... yes
checking for memset... yes
checking for socket... yes
checking for native win32 threads... no
checking for pthread_create in -lpthread... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking pthread/mit/pthread.h usability... no
checking pthread/mit/pthread.h presence... no
checking for pthread/mit/pthread.h... no
checking for SQLAllocHandle in -liodbc... no
checking if we can add -Werror=return-type to CFLAGS (via CFLAGS)... yes
configure: creating ./config.status
config.status: creating c_src/x86_64-apple-darwin17.7.0/Makefile
configure: WARNING: "ODBC library - link check failed"
```

For me this one `checking for SQLAllocHandle in -liodbc... no` stands out: am I wrong, or is the linker trying to link again `iODBC` instead of `unixODBC`, which would need the flag `-lodbc` (if I'm not mistaken)?

Next I'll try to adjust the buildscripts to use `-lodbc` as its flag. Or maybe I'll try to use iODBC instead of unixODBC first in the generic-builder in order to check if my suspicion is correct...

**Comment by mradke** [comment]
When I change `unixODBC` with `libiodbc` in `erlang/generic-builder.nix` the linker check does not fail anymore. Although, the build fails this seems like progress.

Can anyone comment on how / where one can change the flags from `-liodbc` to `-lodbc`? I think this should happen in the prepatch phase, but I don't know how to inspect the configure scripts...

**Comment by mradke** [comment]
It seems that I've figured it out.
I added `substituteInPlace lib/odbc/configure.in --replace 'iodbc' 'odbc'` to the preConfigure part in `erlang/generic-builder.nix`. Now the build log looks good and the compilation succeeds.

Although running `nix-shell -I localpkgs=./nixpkgs -p erlang_odbc unixODBC` still fails the test of `odbc:start().`, but this might be due to a caching issue...

**Comment by mradke** [comment]
I don't know why my proposed change did result in correctly building the dependency but not actually making it available.

Since I settled for a Rust solution as the driver in the meantime (due to issues with a size limit in the erlang odbc driver) I won't pursue this issues any longer.
