### ISSUE TITLE
Getting GhcLibWays: command not found when crossbuilding a haskell package

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#94649]
**Describe the bug**
Using ` run: nix-build -j4 --option system aarch64-linux --option sandbox false --extra-platforms aarch64-linux shell.nix` with checked out `refs/heads/master` of https://github.com/srid/neuron (https://github.com/srid/neuron/commit/b400d90d59f6a4fd32e832569bc9bd212fe2ae45)

**To Reproduce**
Run the github action https://github.com/573/neuron-archived/actions/runs/194557289

**Expected behavior**
The build should succeed as it does regarding the nightly build (https://github.com/srid/neuron/releases/tag/nightly)

**Additional context**
Locally I was able to circumvent the error by using ghc883 instead of ghc884.

**Comment by maralorn** [comment]
Okay, so do I understand this correctly:

ghc-8.8.4 is broken on aarch64?

And the build error is this:
```
configuring
/nix/store/iccnwksp0hfffsv3x7qcf73f043b4znq-stdenv-linux/setup: line 106: GhcLibWays: command not found
builder for '/nix/store/2wmkbb4vb1k1cqzaazbwvpnnikwg7n8n-ghc-8.8.4.drv' failed with exit code 127
```

We should first figure out, if ghc 8.8.4 is really broken on aarch64 right now.

I sadly have no experience with aarch64 at all.

If someone more experienced could enlighten me on how/where we have tests for this, that would be great. Do we build aarch64 on hydra?

/cc @cdepillabout

Maybe we picked a bad commit in neuron?

**Comment by domenkozar** [comment]
this should be fixed in master.

**Comment by maralorn** [comment]
@573 it was my intention anyways to bump the nixpkgs pin in neuron. That hopefully should fix this in neuron.

**Comment by maralorn** [comment]
Fix apparently confirmed.
