### ISSUE TITLE
wpa_cli is totally broken with the default wpa_supplicant settings

### ISSUE THREAD

**Issue by thoughtpolice** [NixOS/nixpkgs#9466]
User `jplayer01` on the `#nixos` IRC channel reported that they spent a lot of time and frustration on the LiveCD trying to get `wpa_supplicant` to work properly, because they needed `wpa_cli` to connect to the right network with correct settings.

So you would think that's just the end of the story, but that's broken out of the box. From `./modules/services/networking/wpa_supplicant.nix`:

```
    # FIXME: start a separate wpa_supplicant instance per interface.
    jobs.wpa_supplicant =
      { description = "WPA Supplicant";

        wantedBy = [ "network.target" ];

        path = [ pkgs.wpa_supplicant ];

        preStart = ''
          touch -a ${configFile}
          chmod 600 ${configFile}
        '' + optionalString cfg.userControlled.enable ''
          if [ ! -s ${configFile} ]; then
            echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=${cfg.userControlled.group}" >> ${configFile}
            echo "update_config=1" >> ${configFile}
          fi
        '';
```

The important bit is `ctrl_interface` which will specify for the daemon to create a unix socket which `wpa_cli` can talk to. The problem is that this depends on `config.networking.wireless.userControlled.enabled = true;`, which obviously is not set by default.

The fix is to `systemctl stop wpa_supplicant` first, then start it with your own configuration and talk to it with `wpa_cli`.

Users with NixOS installed can live with this but I consider this behavior seriously broken for the LiveCD. I would absolutely reach for `wpa_cli` first thing and finding it broken is problematic.

Second, there are numerous problems with this module, including:
- Using old `jobs` interface. Must be nuked from orbit.
- Does not provide a separate unit for every interface. We should see what other distributions do here (following 'the law of least surprise'), although at least we could make a `systemctl status wpa_supplicant@<iface>` parameterized unit.
- Does not provide `wpa_cli` access by default, `ctrl_interface` should be explicit opt-out, and root-only by default.
- In the event `userControlled` is enabled, a `wireless` group should be created and the documentation should be changed to reflect that fact that the user should be part of the `wireless` group. I see very little point in this being arbitrary and user-controlled, as opposed to fixed and sensible OOTB (NixOS users don't even _come_ with a default group which IMO does violate the law of least surprise, as most other distros do, so they just have to invent some arbitrary group to do it. Not cool)

I'd guess most of these problems are not relevant to a lot of people because they talk to `wpa_supplicant` over dbus. Regardless, these are serious problems.

In light of all this I'd say this module is almost obviously unmaintained. So I guess I sign up for putting my money where my mouth is and fixing this.

**Comment by puffnfresh** [comment]
I just hit this about an hour ago and accidentally came across this issue.

Just did a `pgrep -a wpa_supplication; systemctl stop wpa_supplicant` then manually ran it with `-O /var/run/wpa_supplicant` on the end. Is there a problem with exposing the interface directory like this by default?

**Comment by domenkozar** [comment]
Anyone wants to take a stab at this issue? I'd include it into 15.09 release if it was done in time.

**Comment by jagajaga** [comment]
Aren't there any new fixes on that?

**Comment by globin** [comment]
In case you are using declarative network definitions wpa_{cli,gui} works for all tasks not writing to the config file, e.g. connecting to networks temporarily, reassociating, disconnecting, switching networks. If no networks are declared you have to specify the whole /etc/wpa_supplicant.conf yourself and will not be touched by the module. (#12172)

**Comment by Profpatsch** [comment]
Closing because no reaction and second issue.
