### ISSUE TITLE
nixos.tests.latestKernel.login.x86_64-linux fails with Linux 5.8

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#94678]
**Describe the bug**
The [nixos.tests.latestKernel.login.x86_64-linux test](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.latestKernel.login.x86_64-linux) is failing. I bisected this problem to 3a8cbea4f7398ddd705b9b72b58bc0b6e0cced91 “linux: Init 5.8”. The error message `Failed to parse bus message: Invalid argument` matches [RHBZ #1853736](https://bugzilla.redhat.com/show_bug.cgi?id=1853736), which points to both a workaround of recompiling systemd against Linux 5.8 headers, and an upstream systemd patch (systemd/systemd#16424) that’s in systemd 246 (#94354) and was backported in 245.7 as systemd/systemd-stable@5325d280ab8468b981014c700d1d6cc1f01a3c02.

```
machine: waiting for success: [ $(fgconsole) = 2 ]
machine # [   18.137166] systemd[1]: Started Getty on tty2.
(0.06 seconds)
machine # Failed to parse bus message: Invalid argument
Test "Check whether switching VTs works" failed with error: "retrieving systemctl info for unit "getty@tty2.service"  failed with exit code 1"
error: 
Traceback (most recent call last):
  File "/nix/store/4h6d340vj8ccr09g6nv73g66c2wq6y12-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 894, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 13, in <module>
  File "/nix/store/4h6d340vj8ccr09g6nv73g66c2wq6y12-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 347, in wait_for_unit
    retry(check_active)
  File "/nix/store/4h6d340vj8ccr09g6nv73g66c2wq6y12-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 137, in retry
    if fn(False):
  File "/nix/store/4h6d340vj8ccr09g6nv73g66c2wq6y12-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 329, in check_active
    info = self.get_unit_info(unit, user)
  File "/nix/store/4h6d340vj8ccr09g6nv73g66c2wq6y12-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 352, in get_unit_info
    raise Exception(
Exception: retrieving systemctl info for unit "getty@tty2.service"  failed with exit code 1
```

**To Reproduce**
`nix build -f nixos/release-combined.nix nixos.tests.latestKernel.login.x86_64-linux`

**Notify maintainers**
Cc @NeQuissimus @andir @eelco @flokli

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [systemd linuxHeaders]
# a list of nixos modules affected by the problem
module: []
```

**Comment by leo60228** [comment]
My PR wasn't merged, Linux 5.8 ended up being added by someone else.

**Comment by flokli** [comment]
Linking for visibility: that PR was https://github.com/NixOS/nixpkgs/pull/94614.

**Comment by flokli** [comment]
The PR bumping systemd to 245.7 is at https://github.com/NixOS/nixpkgs/pull/94681.

**Comment by andersk** [comment]
Is it really helpful to send that to `staging` given that `nixos-unstable` will be unable to advance without it? Or are you thinking we also want to revert the `linuxPackages_latest = linuxPackages_5_8` bump in `master` for now?

**Comment by flokli** [comment]
Maybe we should revert 3a8cbea in master, and re-revert it in staging again.

I let @FRidh and @vcunat decide about this, they've been doing the staging rounds.

**Comment by doronbehar** [comment]
Hey all, question: How do you spot which tests block the channels? I always track https://status.nixos.org and every few days I notice nixos-unstable doesn't progress. When it don't I see an issue with the "channel blocker" label and I always wonder..

**Comment by andersk** [comment]
@doronbehar Click on the “Hydra job for tests” link and go to the “Constituents” tab.
