### ISSUE TITLE
Synergy: Autostart option starts regardless of whether X11 is up.

### ISSUE THREAD

**Issue by joshuafcole** [NixOS/nixpkgs#9468]
Synergy crashes without an X Display available, but the autostart option attempts to start synergy  regardless of whether login is graphical or TTY. It would probably make more sense to spawn this after graphical.target.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/synergy.nix#L98

**Comment by Profpatsch** [comment]
(triage) status?

**Comment by pbogdan** [comment]
In case this is still relevant - would it make sense for those to run as user services instead to take advantage of recent changes merged in https://github.com/NixOS/nixpkgs/pull/26094
