### ISSUE TITLE
broken python27Packages.urwid 2.1.1

### ISSUE THREAD

**Issue by kidd** [NixOS/nixpkgs#94684]
I'm not sure how to tackle this, but I recently updated my channels (unstable) and getting this issue with urwid (python2.7) after https://github.com/NixOS/nixpkgs/pull/94034 went in.  Here's the logs just in case it's helpful to anyone:

`nixos-rebuild switch -v`
https://gist.github.com/kidd/fe75e247756e2ad18bcc3793633a6c22

trying to build just that package fails in the same way:
```
 ~/programmingStuff/nixpkgs $ nix repl                                                                                                                                                       
 Welcome to Nix version 2.3.7. Type :? for help.                                                                                                                                                                     
 nix-repl> :l ./                                                                                                                                                                                                     
 Added 12175 variables.
 nix-repl> :b python27Packages.urwid     
builder for '/nix/store/4c764s06m509s5a0m91j8gvywp5ipk7i-python2.7-urwid-2.1.1.drv' failed with exit code 1; last 10 log lines:
      self.module)
    File "/nix/store/984x0xnjaf00ms5nh1r1ki3h6qd5q399-python-2.7.18/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
      suites = [self.loadTestsFromName(name, module) for name in names]
    File "/nix/store/984x0xnjaf00ms5nh1r1ki3h6qd5q399-python-2.7.18/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
      return self.loadTestsFromModule(obj)
    File "/nix/store/hcdzwm3d90p9qa4082il8ja6n6x1q03b-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
      tests.append(self.loadTestsFromName(submodule))
    File "/nix/store/984x0xnjaf00ms5nh1r1ki3h6qd5q399-python-2.7.18/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
      parent, obj = obj, getattr(obj, part)
  AttributeError: 'module' object has no attribute 'test_container'
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/4c764s06m509s5a0m91j8gvywp5ipk7i-python2.7-urwid-2.1.1.drv' failed
```

**Notify maintainers**
@FRidh @veehaitch 

**Metadata**
```
~ $ nix-shell -p nix-info --run "nix-info -m"                                                                               [20-08-04 22:47]
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.09pre236138.970b2b853d4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(rgrau): `"nixos-20.03.2657.b50d55871fb, nixpkgs-20.09pre236005.2b7c0dcdaab"`
 - channels(root): `"nixos-20.03.2666.eeb91b03a5c, nixpkgs-20.09pre236138.970b2b853d4"`
 - nixpkgs: `/home/rgrau/.nix-defexpr/channels/nixpkgs`
```

**Comment by DIzFer** [comment]
To my own dismay, this was circumvented in my system by disabling tests. However, again, in my system, the only reason I needed python2Packages.urwid was because targetcli is hard set to build with python2. It would probably make sense to switch whatever made you hit this issue to py3 too.

**Comment by jonringer** [comment]
this looks more like urwid doesn't support python2 for testing

**Comment by kidd** [comment]
@jonringer isn't that what #95339 does? (disable tests on python2?). I tried to install the package with those modifications locally and worked. (Skipped tests).
 
(for other newbies' future ref): I figured out the reason why python2Packages.urwid was installed was as a dependency for `wicd`.  I'm not using `wicd`, so just ended up removing wicd.

`nix-store -q --tree /run/current-system` was the command that helped me to figure it out.

**Comment by jonringer** [comment]
I made a PR to disable the python2 tests, however, I'm not sure that upstream is checking the results of python2 anymore as the tests seemed to have issues decoding string correctly. This could be just the tests are python3 only, but I wouldn't use python2.... for anything right now
