### ISSUE TITLE
elementary-files fails to build blocking nixos-20.03 (through pantheon nixos vm test)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#94707]
**Describe the bug**
https://hydra.nixos.org/build/124686072

**Comment by vcunat** [comment]
For reference, it was triggered by bfb78aaf0e.

**Comment by pstn** [comment]
This seems to be an issue with vala. I applied `9220264fbc48b83fb1d99eea676cef24dd91212f` `943c870092be7a539b0478ac5f021e6bec9dd913` and `519606eb119aa38845ba1c10bd0a225a4a343d00` (vala updates and switching vala default to `0.48` on `release-20.03` and was able to build `elementary-files`. I don't know what thet prodecure is though. Changing the  default vala version doesn't seem to be right for stable.

**Comment by vcunat** [comment]
Adding packages is fine for stable.  We could switch just for that single package or just for `pantheon.*` &ndash; or give up on that update.

**Comment by worldofpeace** [comment]
Hi, I really would have appreciated a ping on this. After all I'm its sole maintainer and any duplicate work just ends up creating a headache for me. Thanks.

**Comment by vcunat** [comment]
The ping from bfb78aa didn't arrive?

**Comment by worldofpeace** [comment]
Oh, just now got that. If only ofborg could assign via issues :grin: 

Going to link to what I think the ideal solution will be for this https://github.com/NixOS/nixpkgs/pull/94711#issuecomment-669370342. atm it will look like a revert.
