### ISSUE TITLE
Revert jack2 to the v1.9.10 release

### ISSUE THREAD

**Issue by cillianderoiste** [NixOS/nixpkgs#9470]
As discussed in #9467 I'd rather use the stable jack2 release as the default version. I'll try reverting it, if it doesn't work out I'll report why and take it from there. I can also add a jack2-git expression for people who need that, since jack2 releases can take a year or two.

**Comment by cillianderoiste** [comment]
I've tested reverting jack2 to v1.9.10 by building:

nix-build -A mpd -A kde5.ktp-filetransfer-handler -A dirt -A mailnag -A 3dfsb -A a2jmidid -A kde4.kdenlive -A bristol -A kde4.telepathy.contact_runner -A sound-juicer -A linuxsampler -A rili -A liferea -A fluidsynth -A rakarrack -A python34Packages.rtmidi -A empathy -A kde5.ktp-accounts-kcm -A gnash -A guitarix -A tetraproc -A jaaa -A synthv1 -A mlt-qt5 -A simutrans_binaries -A openxcom -A RhythmDelay -A ballAndPaddle -A freewheeling -A milkytracker -A castle_combat -A qtractor -A gst_all_1.gst-vaapi -A pulseaudioFull -A kde5.krfb -A alsaPluginWrapper -A kde4.telepathy.send_file -A e19.rage -A kde4.telepathy.kded_integration_module -A xsynth_dssi -A ufoai -A calf -A telepathy_qt -A kde5.ktp-kded-module -A puredata -A jack_rack -A freeciv -A kde4.krfb -A ocamlPackages.ocamlsdl -A kde5.ktp-auth-handler -A jack_capture -A onscripter-en -A extremetuxracer -A zexy -A zandronum-bin -A constant-detune-chorus -A moc -A kde5.ktp-text-ui -A bitmeter -A guile-sdl -A qsynth -A jackmeter -A kde4.telepathy.call_ui -A solfege -A d2x_rebirth -A kde4.kdenetwork -A tennix -A frescobaldi -A kde4.telepathy.auth_handler -A faust2jack -A dssi -A gnome3.gnome-music -A chocolateDoom -A gl117 -A musescore -A pithos -A x42-plugins -A CompBus -A VoiceOfFaust -A python33Packages.rtmidi -A kde4.telepathy.contact_list -A trackballs -A liquidsoap -A sooperlooper -A sonic-visualiser -A cyclone -A artyFX -A mrpeach -A freedink -A brasero -A zod -A vmpk -A puremapping -A qjackctl -A kodiPlain -A kde5.ktp-common-internals -A distrho -A zynaddsubfx -A helmholtz -A eternity -A mhwaveedit -A kde4.telepathy.filetransfer_handler -A kde5.ktp-send-file -A aubio -A lash -A kde5.krdc -A farstream -A openlierox -A simplescreenrecorder -A renpy -A kde4.telepathy.accounts_kcm -A SDL_mixer -A kde4.telepathy.common_internals -A wesnoth -A pingus -A asc -A jack_oscrolloscope -A kde5.ktp-contact-runner -A liquidwar -A crrcsim -A drumkv1 -A samplv1 -A njam -A supercollider_scel -A timidity -A zam-plugins -A xmoto -A mednafen -A ingen -A xfce.parole -A python27Packages.rtmidi -A vectoroids -A foo-yc20 -A supercollider -A impressive -A seq24 -A warmux -A d1x_rebirth -A instead -A kde4.telepathy.text_ui -A maxlib -A pygame -A pitivi -A MBdistortion -A rosegarden -A jamp -A timbreid -A jack2Full -A libjack2 -A ardour -A ardour3 -A CharacterCompressor -A gnome3.cheese -A alsaPlugins -A pypyPackages.rtmidi -A kde5.kdenlive -A kde5.ktp-approver -A telepathy_farstream -A kodi -A teetertorture -A simutrans -A gnome3.totem -A lincity_ng -A setbfree -A naev -A hydrogen -A LazyLimiter -A drumgizmo -A kde5.ktp-contact-list -A odamex -A kde4.telepathy.desktop_applets -A gav  -A darkice -A QmidiNet -A kde4.krdc -A yoshimi -A kde4.telepathy.approver -A fish-fillets-ng -A gst_all_1.gst-plugins-bad -A faust2jaqt -A jalv -A libretro.scummvm -A ffmpeg-full -A telepathy_qt5 -A rkrlv2 -A widelands -A gajim -A ffadoFull -A lmms -A sauerbraten -A mlt-qt4 -A egoboo

Apart from an unrelated download issue with helmholtz everything builds fine, so I'll go ahead and revert it in master and release-15.09.

If any issues do arise, I'm happy to add a snapshot of jack2-git for those packages.

I hope that's OK with you too @wkennington.

**Comment by wkennington** [comment]
If it takes no modification that seems fine. I'll have to test this
building against pulseaudio.

**Comment by cillianderoiste** [comment]
Great, thanks!

**Comment by cillianderoiste** [comment]
@wkennington any luck with this? Can I help out?

**Comment by wkennington** [comment]
`nix-build -A pkgs.jack2Full`
http://sprunge.us/aKcH

**Comment by wkennington** [comment]
Basically, the stable version is broken under gcc5 but can be fixed by using the git version which corrects their improper use of inline functions.

**Comment by cillianderoiste** [comment]
@wkennington isn't gcc49 the default?

**Comment by vcunat** [comment]
@cillianderoiste: it is in current master (and 15.09), but likely not for too long.

**Comment by cillianderoiste** [comment]
Ah ok, in which case wouldn't it be better to pin gcc to 4.9 for packages which break with gcc 5, until new stable versions of those packages are released?

**Comment by vcunat** [comment]
It might be better to cherry-pick an upstream patch fixing the problems, if it's simple. I suppose it depends on the particular case.

**Comment by cillianderoiste** [comment]
I think this patch is used by debian and fedora: http://pkgs.fedoraproject.org/cgit/jack-audio-connection-kit.git/plain/jack-gcc5.patch I'll try it out.

**Comment by cillianderoiste** [comment]
With this patch it builds fine using gcc5, I've opened a PR with the change. Does that look OK?

**Comment by vcunat** [comment]
The patch seems very safe to me.

**Comment by andrewrk** [comment]
jack2-git would be much appreciated - see the above linked pull request.

**Comment by andrewrk** [comment]
Is this still WIP?

**Comment by wkennington** [comment]
No
