### ISSUE TITLE
Zero Hydra Failures for release-15.09

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#9471]
We have ~50 builds failing for 15.09 release, let's do our best to get it down to 0. 
http://hydra.nixos.org/eval/1219538#tabs-still-fail

**Comment by domenkozar** [comment]
cc @peti quite some haskell packages fail (+ikiwiki)

**Comment by peti** [comment]
I'll update the haskell package set to a more stable version soon'ish. Getting rid of *all* errors is going to be hard, though, because Darwin/x86_64 is living in the wild west Haskell-wise and a *lot* of builds fail on that platform.

**Comment by domenkozar** [comment]
:+1:

**Comment by peti** [comment]
The `ikiwiki` test suite failure [was reported a while ago](https://ikiwiki.info/bugs/img_test_failure_on_nix/), but upstream doesn't seem to care much. Unfortunately, the principle author, Joey Hess, doesn't work much on that project any more, so it's anybody's guess whether that issue will be fixed.

**Comment by domenkozar** [comment]
Should we just disable the test suite for the time being and link to that
bug?

**Comment by peti** [comment]
It's hard for me to judge whether the test suite failure is harmless. It looks like we updated some Perl bindings to ImageMagick, and that update changed the API somehow, breaking the test. IMHO, it's conceivable that the update would break production, too. Personally, I don't care much because I don't use the ImageMagick module for anything, but others might. Anyway, I'm not sure what we can do other than downgrading that plugin.  I'll try a git-bisect to find out what caused the test suite failure in the first place.

**Comment by FRidh** [comment]
python packages `gmpy` and `gmpy2` fail with pypy. They're both C python extension modules that are incompatible with pypy and thus should be disabled. `gmpy_cffi` is supposed to be compatible but we haven't packaged that.

**Comment by lethalman** [comment]
Also I think that ruby 2.0 not building on i686 is a relevant issue for the stable release?

**Comment by peti** [comment]
Further `ikiwiki` stuff lives at https://github.com/NixOS/nixpkgs/issues/9473.

**Comment by domenkozar** [comment]
@lethalman I fixed docker.

**Comment by FRidh** [comment]
`pypyPackages.importlib` is failing. This package should not be available because PyPy comes with importlib (as the log also indicates). The expression for importlib is
```
 importlib = if isPy26 then (buildPythonPackage {
    name = "importlib-1.0.2";
    src = pkgs.fetchurl {
      url = "http://pypi.python.org/packages/source/i/importlib/importlib-1.0.2.tar.gz";
      md5 = "4aa23397da8bd7c7426864e88e4db7e1";
    };
    doCheck = false;
  }) else null;
```
Apparently this is not working. Use `disabled = !isPy26` instead?

**Comment by domenkozar** [comment]
yup!

**Comment by domenkozar** [comment]
rust cargo is failing to build: http://hydra.nixos.org/build/25160080/nixlog/1/raw /cc @wizeman @laMudri

**Comment by domenkozar** [comment]
xen is failing cc @ts468 http://hydra.nixos.org/build/25185514

**Comment by domenkozar** [comment]
@peti there are still a bunch of packages failing at http://hydra.nixos.org/eval/1218528?full=1

**Comment by globin** [comment]
@domenkozar cargo failure looks like a temporary failure fetching from github.

**Comment by vcunat** [comment]
@globin: that's a regular building derivation &ndash; those should never have network access. Any sources have to get downloaded in advance by fixed-output derivations (`fetch*` typically).

**Comment by domenkozar** [comment]
anyone interested into fixing xen?

**Comment by ts468** [comment]
I'll have a look again, but it's still unclear to me where the error comes from.

**Comment by domenkozar** [comment]
More broken builds:

- categories http://hydra.nixos.org/build/25459655 /cc @Fuuzetsu 
- dolphinEmu http://hydra.nixos.org/build/25461029 /cc @MP2E 
- dragonegg http://hydra.nixos.org/build/25426494 /cc @gridaphobe 
- tessel http://hydra.nixos.org/build/25478695 /cc @cillianderoiste 
- pycangije http://hydra.nixos.org/build/25479118 /cc @linquize
- perlPackages.UnicodeICUCollator http://hydra.nixos.org/build/25141764 /cc @ocharles 
- panamax_ui http://hydra.nixos.org/build/25464702 /cc @offlinehacker 
- hhvm http://hydra.nixos.org/build/25462015 /cc @thoughtpolice

**Comment by domenkozar** [comment]
For linux-perf see https://github.com/NixOS/nixpkgs/issues/9095

**Comment by vcunat** [comment]
- dragonegg: maybe it will be enough to just update it to 3.6.2. There is even llvm-3.7.0 released now, but I see no dragonegg link in there.

**Comment by Fuuzetsu** [comment]
I can fix or mark broken (as needed) `categories` today. In general will check my packages today and see what I can fix.

**Comment by domenkozar** [comment]
Broken NixOS tests:

- [ ] blivet http://hydra.nixos.org/eval/1219538#tabs-still-fail /cc @aszlig 
- [ ] virtualbox http://hydra.nixos.org/build/25474534 /cc @aszlig 
- [ ] docker http://hydra.nixos.org/build/25475445 /cc @offlinehacker 
- [ ] etcd http://hydra.nixos.org/build/25466795 /cc @offlinehacker 
- [ ] caadvisor http://hydra.nixos.org/build/25474355 /cc @offlinehacker 
- [ ] ec2-nixops http://hydra.nixos.org/build/25480840 /cc @copumpkin 
- [ ] fleet http://hydra.nixos.org/build/25479202 /cc @offlinehacker 
- [ ] quake3 http://hydra.nixos.org/build/25478604 /cc @edolstra

**Comment by Fuuzetsu** [comment]
`categories` can be marked as broken, needs upstream fixes; I plan to do it later today but if I forget or whatever you can go ahead and do it

**Comment by ragnard** [comment]
I believe (hope) failing docker test is adressed by https://github.com/NixOS/nixpkgs/pull/9638

**Comment by aszlig** [comment]
@iElectric: Going to work on vbox/blivet on Monday.

**Comment by vcunat** [comment]
I can't reproduce those cups problems on i686 (likely causing almost 4k failures); would someone restart them unless you have an idea what causes them?

**Comment by offlinehacker** [comment]
I would really consider systemd update for release, it hasn't been upgraded
for a long time and we need some of its features. It's a core feature and
without it I wouldn't do a release, but that's just my opinion.

V ned., 6. sep. 2015 12:14 pop. je oseba Vladimír Čunát <
notifications@github.com> napisala:

**Comment by vcunat** [comment]
Someone would have to do that updating job, I guess. ATM it seems a little late to me to start testing such large changes, but the #6671 issue seems rather dead anyway...

**Comment by offlinehacker** [comment]
Etcd tests fixed in https://github.com/NixOS/nixpkgs/commit/a79d732243376652d96187a8aa8ec055c5a59589

**Comment by offlinehacker** [comment]
Logstash tests fixed on master

**Comment by domenkozar** [comment]
I'm going to update cups to fix the transient failure.

**Comment by domenkozar** [comment]
junit fails to build /cc @copumpkin

**Comment by lethalman** [comment]
@offlinehacker people is living without the new shiny systemd already. This is just one release, there's no point in delaying further.

**Comment by domenkozar** [comment]
@offlinehacker I agree systemd is a critical component (the most critical?) in our ecosystem, but we've delayed the release for too many months already. If I have anything to say at this, we will skip systemd upgrade in this release and do it for the next one.

We have to be aware bumping systemd isn't a task that comes 2 weeks before the release, but rather somewhere in middle of development.

**Comment by peti** [comment]
Is https://github.com/NixOS/nixpkgs/issues/9674 relevant for the 15.09 release? It certainly causes trouble on `master`.

**Comment by lethalman** [comment]
@peti nixos is not darwin, so not relevant for the nixos release.

**Comment by peti** [comment]
We have stable Nixpkgs releases other than those tied to NixOS?

**Comment by lethalman** [comment]
@peti in which way are nixpkgs releases tied to nixos?

**Comment by peti** [comment]
Do we have stable Nixpkgs releases?

**Comment by lethalman** [comment]
Ups no that was a typo.

**Comment by domenkozar** [comment]
Nope, we don't.

**Comment by peti** [comment]
Do we care whether the `release-15.09` branch of Nixpkgs can be used on Darwin?

**Comment by domenkozar** [comment]
We haven't so far, but I'm willing to change that if there is a user base / reason

**Comment by lethalman** [comment]
Chromium fails to build: http://hydra.nixos.org/build/25574416 that's quite blocker.

**Comment by wkennington** [comment]
Looks like the usual oom issues.

g++: internal compiler error: Segmentation fault (program as) Please submit
a full bug report, with preprocessed source if appropriate. See <
http://gcc.gnu.org/bugs.html> for instructions.

**Comment by domenkozar** [comment]
How do you know it's OOM?

**Comment by wkennington** [comment]
Well it's that (which I've seen lots more concrete proof for) or its that
gc4.9 is so horribly broken this is happening on numerous builds multiple
times per day. But I'm still sticking with the oom guess as I've seen
similar errors combined with oom messages. Plus this never seems to be a
problem on my personal build instances.

**Comment by edolstra** [comment]
The segfaults seem to have started after I rebooted the build machines into Linux 3.18 (was 3.14). I've now switched the two machines that were segfaulting the most back to 3.14. We'll see if that helps.

**Comment by edolstra** [comment]
@peti Yes I care about having the 15.09 branch work on Darwin. At LogicBlox we use the release branch for both Linux and Darwin builds, so it would be annoying if we had to do Darwin builds from another branch.

**Comment by domenkozar** [comment]
OK /cc @vcunat

**Comment by peti** [comment]
OOK kills show up in the system / dmesg log, so it should be quite easy to see whether a process was killed by OOM or not.

**Comment by domenkozar** [comment]
chronos is still failing to build @offlinehacker @rushmorem

**Comment by vcunat** [comment]
The gcr failures: I can't reproduce the problem. It might be a parallel-make issue, or something else.

**Comment by domenkozar** [comment]
Yes it was. Only a few tests left to fix: http://hydra.nixos.org/eval/1221074#tabs-still-fail

**Comment by vcunat** [comment]
That looks close enough to zero &ndash; IMO the important thing isn't to reach zero but to keep the number low in the long run, at least on the release branches.

**Comment by domenkozar** [comment]
Yes, VirtualBox test failure worries me as it's the same as https://github.com/NixOS/nixops/issues/332, but it does succeed for me locally. I've restarted it, just to be sure it's not transient.

**Comment by Mathnerd314** [comment]
The Quake failure looks similar to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775235, basically we need to pass ``-cpu pentium3`` or ``-cpu host`` or in general something with SSE.

**Comment by vcunat** [comment]
But i686 does *not* guarantee SSE, just MMX. https://en.wikipedia.org/wiki/P6_(microarchitecture)

**Comment by Mathnerd314** [comment]
Maybe if we update LLVM to 3.7, which includes https://github.com/llvm-mirror/llvm/commit/87f3799e5634fe4e615ee994eaa23128d0317c14, the problem will go away.

**Comment by vcunat** [comment]
Yes, sounds possible. I'm not sure whether to do such a change in 15.09 now. It would certainly need some re-testing of the drivers.

**Comment by domenkozar** [comment]
As soon as VirtualBox test/issue with missing IP is addressed, we're ready for the release.

**Comment by peti** [comment]
I take it that we've given up on the notion of having zero evaluation errors in our code?

**Comment by domenkozar** [comment]
We need semantic errors in Nix for that, to be able to distinguish between a user error message (unsupported package) and anything else

**Comment by peti** [comment]
Well, there *are* other options, i.e. to make sure that our package set doesn't instantiate inconsistent configurations in the first place. Avoiding evalution errors is not the same thing as not printing them.

**Comment by vcunat** [comment]
Perhaps a related issue: warnings on using of deprecated attributes, discussed at 8e8e23de33. The main problem there is the inability to completely distinguish listing of available packages from instantiating some explicitly.

**Comment by domenkozar** [comment]
I suggest we continue the debate on https://github.com/NixOS/nixpkgs/issues/6561

**Comment by peti** [comment]
So, I take it that we've given up on the notion of having zero evaluation errors release-15.09?

**Comment by domenkozar** [comment]
We haven't given up, the work just wasn't done for `release-15.09` in time

**Comment by domenkozar** [comment]
We're literally 1 blocker away from the release, it's too late to talk about this for `15.09` (although I'd love to have that fixed)

**Comment by peti** [comment]
In other words, we are going to release 15.09 with all those evaluation errors included.

**Comment by domenkozar** [comment]
Yes

**Comment by edolstra** [comment]
@peti Though I'd like a solution for this, it's really only a Hydra issue, not something that affects end users.

**Comment by domenkozar** [comment]
cargo on 32bit linux has transient failures, sometimes it's trying to fetch a git repository. http://hydra.nixos.org/build/25136475/log/raw

cc @madjar @wizeman

**Comment by domenkozar** [comment]
We're pretty much done here, `cargo` (only i686), `nixos.tests.blivet` and `nixos.tests.nixops` are failing, but I guess we'll have to live with that for now.

**Comment by copumpkin** [comment]
I started looking at the tests.nixops one but it's not immediately obvious what's causing it and I haven't had much time recently to work on it.

**Comment by copumpkin** [comment]
I'll try to get to it in the next few days.
