### ISSUE TITLE
python-packages scikit-learn: doctests fail at 15.09 and master

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#9472]
Several doctests fail. 
http://hydra.nixos.org/build/25138079/log/raw
All values are actually correct in the failed tests, its just that the doctests haven't explicitly specified the dtype:
```
Expected:
    array([[1, 0, 0, 0],
           [0, 0, 0, 1]])
Got:
    array([[1, 0, 0, 0],
           [0, 0, 0, 1]], dtype=int32)
```
I'll send a PR upstream to add the dtypes. How to handle this for now? Is it possible to only disable doctests?

cc @domenkozar

**Comment by domenkozar** [comment]
Tracking to #9471 9471

**Comment by domenkozar** [comment]
@FRidh depends on the test runner, but usually it's possible

**Comment by garbas** [comment]
i got scikitlearn build for i686 down to 1 test failure

**Comment by FRidh** [comment]
Just for reference, the PR https://github.com/scikit-learn/scikit-learn/pull/5197
I am surprised disabling doctests in #9547 didn't work

**Comment by garbas** [comment]
@FRidh waiting for https://github.com/scikit-learn/scikit-learn/pull/5197 to pass

**Comment by garbas** [comment]
looks like my fix broke it for python2.7 ... http://hydra.nixos.org/build/25458591

**Comment by garbas** [comment]
should be fixed on python2 as well now 
master -> https://github.com/NixOS/nixpkgs/commit/25a29e667141688f780d155f65fd1c65df7f82cb
release-15.09 -> https://github.com/NixOS/nixpkgs/commit/df0f7639fd8e9d4f76683120c45c2956503d5ee8
