### ISSUE TITLE
ikiwiki test suite is broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#9473]
git bisect says:

> Bisect Rest:
> 7f0a596 bad imagemagick: Reduce dependency bloat
>
> Bisect Log:
> git bisect start
> git bisect good 54d86f86fdbfe4efbf83f015bbf6cbdde3a2c158
> 54d86f8 good haskell-base: update override for new version
> git bisect bad 372e5a7dcfab16c1c01b1a5dc7a1a906967e652d
> 372e5a7 bad Merge pull request #9072 from benley/shout
> git bisect bad e3d359a507cd24ba761829b6563f7efd6ab9bda9
> e3d359a bad haskellPackages.misfortune: remove redundant patch
> git bisect bad 5960a652f1502260348ad7375ace20959b80abe4
> 5960a65 bad rethinkdb: Force dynamic linking and allow dependency substitution
> git bisect good d24a5a49ea34c1690c4a142bfce6e9724ba87c44
> d24a5a4 good kde-workspace: Disable gpsd dependency
> git bisect bad fa0b84c446a75b3cc9e95323bd9fc7b0cd324794
> fa0b84c bad iproute: Fix reference to /etc instead of /etc at runtime
> git bisect bad 77d33f77d7cffa9e53c780398ae0fadc8dd0eda5
> 77d33f7 bad nixos: redshift service: add extraOptions
> git bisect good a68de0cc168f443ce65367bd8ce5e8d77b2e236a
> a68de0c good Revert "geeqie: update from 1.1 to 1.2"
> git bisect bad f07b2121f9dc23f6a69bbc815e7991c7f52fe551
> f07b212 bad Fix grub-reboot
> git bisect bad 7e8165b27714f66f553b54481c69760f592329c9
> 7e8165b bad imagemagick: Move docs to separate output
> git bisect bad 7f0a596473227a4cda01cb427a06e10332ec86ca
> 7f0a596 bad imagemagick: Reduce dependency bloat
> 7f0a596473227a4cda01cb427a06e10332ec86ca is the first bad commit

Apparently, @edolstra's revert broke the tests -- supposedly by removing some Perl-related feature that used to be there earlier.

**Comment by vcunat** [comment]
For now, what about making the imagemagick module optional and disable it by default?

**Comment by peti** [comment]
ImageMagick is a mandatory dependency; the test suite fails with an error if the module is missing.

**Comment by lethalman** [comment]
Yes the fact is that ghostscript is no more a runtime dep for imagemagick. @edolstra reverted the commits but forgot the necessary configureFlags.

**Comment by lethalman** [comment]
So first of all I've committed 873a6ce9a86181335e222e481b6c48ce94bbd48c to enable ghostscript in imagemagickBig, otherwise there was no difference with imagemagick.

Then either:
- ikiwiki needs a PerlMagick with imagemagickBig
- or ikiwiki needs ghostscript at buildtime and runtime, but I doubt that fonts will work correctly.

**Comment by peti** [comment]
I'll take a look at option (1). I, too, think it's the way to go.

**Comment by vcunat** [comment]
Simplest way I could come with within five minutes:
```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index f49bdf4..89b7bb2 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -8712,7 +8712,7 @@ let
 
   buildPerlPackage = import ../development/perl-modules/generic perl;
 
-  perlPackages = recurseIntoAttrs (import ./perl-packages.nix {
+  perlPackages = recurseIntoAttrs (callPackage ./perl-packages.nix {
     inherit pkgs;
     overrides = (config.perlPackageOverrides or (p: {})) pkgs;
   });
@@ -11819,8 +11819,9 @@ let
   ikiwiki = callPackage ../applications/misc/ikiwiki {
     inherit (perlPackages) TextMarkdown URI HTMLParser HTMLScrubber
       HTMLTemplate TimeDate CGISession DBFile CGIFormBuilder LocaleGettext
-      RpcXML XMLSimple PerlMagick YAML YAMLLibYAML HTMLTree Filechdir
+      RpcXML XMLSimple YAML YAMLLibYAML HTMLTree Filechdir
       AuthenPassphrase NetOpenIDConsumer LWPxParanoidAgent CryptSSLeay;
+    inherit (perlPackages.override { pkgs = pkgs // { imagemagick = imagemagickBig;}; }) PerlMagick;
   };
 
   imagemagick_light = imagemagick.override {
```

**Comment by peti** [comment]
Duh, perl packages have hard-coded references to `pkgs` instead of taking arguments that can be overridden. Weird.

**Comment by peti** [comment]
@lethalman, thank you for finding the fix to this issue!
