### ISSUE TITLE
kdelibs has propagated dependency on cmake, automoc

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#9478]
Such propagated dependencies are bad because they cause unnecessary bloat of the runtime closure (e.g. cmake is ~47 MB).

@ttuegel Can you change the `propagatedNativeBuildInputs` to regular build inputs in `pkgs/applications/kde-apps-15.04/default.nix`?

**Comment by vcunat** [comment]
It's likely that would break compilation of some reverse dependencies. I believe such problems are more about splitting the `$dev` output &ndash; that's what's supposed to "propagate" build-time dependencies (either through *.pc files, this way, or some other way).

**Comment by ttuegel** [comment]
It would definitely break some builds, but those could be manually propagated.

**Comment by edolstra** [comment]
Probably `cmake` can be added to `buildInputs` by the `kdePackage` function, since I guess every KDE package requires cmake.

**Comment by ttuegel** [comment]
Yes, I think that would suffice.

**Comment by ttuegel** [comment]
This is fixed.
