### ISSUE TITLE
tinygo does not contain files from gen-device

### ISSUE THREAD

**Issue by yvesf** [NixOS/nixpkgs#94793]
**Describe the bug**
The files generated in the build-process from files in git submodules are not included.

**To Reproduce**
```
$ nix run nixos.go_1_13 nixos.tinygo -c tinygo build -target=microbit -o test
error: no buildable Go source files in /nix/store/kqwyw27rxyr876g7hc2fzdc0dhbps45b-tinygo-0.11.0/share/tinygo/src/device/nrf
```

**Expected behavior**
The files should not be reported as missing.

**Notify maintainers**
@Chiiruno

**Comment by viric** [comment]
Maybe this was fixed here: https://github.com/NixOS/nixpkgs/pull/106754 ?

**Comment by Madouura** [comment]
Is this still relevant @yvesf?

**Comment by nagy** [comment]
The tinygo derivation has now been shipping these files for a while, so I am going to close this. In particular, the command in the first post is now working for me. Feel free to reopen, if this is not the case for you.
