### ISSUE TITLE
xrdb has runtime dependency on cpp

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#9480]
Obviously this is bad for closure size reduction, since we don't want the whole gcc package pulled in.

(Is xrdb even needed anymore in a modern desktop?)

**Comment by dezgeg** [comment]
At least Arch Linux uses the `mcpp` preprocessor, so it should work for us as well. It's only 992K

**Comment by dezgeg** [comment]
PR: #9501
