### ISSUE TITLE
parted: error while loading shared libraries

### ISSUE THREAD

**Issue by jcs090218** [NixOS/nixpkgs#94844]
**Describe the bug**

While I am trying to install NixOS and following the install manual with the command `parted` (the very first command) then I got the following error.

```
parted: error while loading shared libraries: /nix/store/rmc7nwnzcbzbrah6ma9xfi26jpzrhx9s-readline-6.3p08/lib/libreadline.so.6: cannot read file data: Input/Output error
```

**To Reproduce**

1. I am using `rufus` to boot with an USB on to my old Vaio laptop.
2. Start Konsole and enter command `parted`.

**Additional context**
Just cannot install NixOS properly. 😕

**Comment by symphorien** [comment]
I cannot reproduce, neither on 20.03 nor or master. Can you run nix-info and report the output ?

**Comment by jcs090218** [comment]
I think this is something do to the USB drive? While I am installing NixOS, I assume I cannot eject USB. I think that is the issue, and now I know I should not eject the USB even though NixOS is already boot up. Sorry for disturbing! Close this for now.
