### ISSUE TITLE
fetchurl caches based on sha256, even when url is changed

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#9484]
this just caused me some confusion. I updated a package's version but forgot to change the sha256. When I built, nix transparently substituted the old version from tarballs.nixos.org.

I can see where this behavior would be handy, but it can also cause problems

**Comment by peti** [comment]
I'm not sure whether I see the point is this ticket. What are you suggesting?

**Comment by anderspapitto** [comment]
actually, this is more of a nix concern than a nixpkgs concern. I'll open an issue on that repo with more detail.
