### ISSUE TITLE
Status of packaging the Deepin Desktop Environment (DDE)

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#94870]
Some time ago I have started an effort to package the Deepin Desktop Environment for NixOS, with the help of @worldofpeace. It has been a difficult task. In the following I comment some aspects of it.

- Packaging for NixOS is incomplete, missing basically a module service for the deepin desktop and bug fixes.
- It depends on KWin, which still does not work when launched from DDE.
- There are too many things to fix related to upstream assumptions about Filesystem Hierarchy Standard (FHS) compliance when packaging for NixOS.
- Upstream develops for both a proprietary linux distribution ([UOS](https://en.wikipedia.org/wiki/Unity_Operating_System)) and a free one ([Deepin Linux)](https://www.deepin.org/en/), clearly prioritizing the first one.
- Upstream releases are of poor quality in general, many times with serious bugs, and without a distinction between stable and unstable versions.
- There was a hiatus in upstream releases from middle 2019 to about April 2020, as upstream were focusing only in UOS.
- Packages already in nixpkgs are now too old, and many of them are broken.
- Recently upstream released applications (like deepin-terminal, deepin-editor, etc.) do not run well outside of DDE anymore.
- It seems that only Archlinux is currently trying to keep their distribution of DDE up to date.

It has taken too much of my time to try to evolve DDE on NixOS. As I have no expertise on Qt development, the issue of making KWin work for DDE seems too difficult also.

Considering all of this, I am inclined to abandon this project and remove the packages from nixpkgs.

I would like to know what other NixOS developers think about this situation. What directions should we follow?

cc @worldofpeace @jtojnar @ttuegel

**Comment by worldofpeace** [comment]
This was also on my mind as well, it seems that having the desktop environment won't be feasible for us atm without a contact point inside Deepin. I believe other distro's that were packaging Deepin have had to make similar calls. One notably was OpenSUSE, which was instigated by  some serious security issues in regards to dbus. And things like that could only be handled better with a security contact. IMHO, this project would be okay to abandon and remove the desktop packages from nixpkgs. However, I believe some of the applications could remain in nixpkgs, or is there an issue with even those?

You are in no way inclined to maintain those if you do not wish too, but I'd think at the bear minimum those shouldn't be too difficult to keep in nixpkgs. Let me know what your thoughts are, and re your ping on IRC (which I assume might be in relation to this), if you need to discuss further we should do so in a PM either on Freenode or if you're available on Matrix.

---

If we do decide to remove all or a large portion of DDE we should try to do it in a clearly defined way. Making sure we have release notes and the not cosmetically elegant `throw` in `aliases.nix` that gets the point across.

**Comment by worldofpeace** [comment]
Hmm, I didn't read closely this point

> Recently upstream released applications (like deepin-terminal, deepin-editor, etc.) do not run well outside of DDE anymore.

Yeah, I think I have an idea as to what the issue there is, but it sounds like it would be better to just remove them entirely.
As I understand it, you maintain actually a large amount of DE related infrastructure in nixpkgs, so I think it would probably the best choice for you to drop this particular project in its entirety.

**Comment by romildo** [comment]
I have a local branch where I am trying to follow recent releases of the packages.

Some of the issues I am seeing with the applications are referred to [here](https://github.com/linuxdeepin/deepin-terminal/issues/17). Also [here](https://github.com/linuxdeepin/developer-center/issues/1806).

Upstream have migrated applications from GTK to DTK (the Deepin Desktop Toolkit), which is based on Qt.

I have forget to mention also that most of the discussions available on upstream github repositories are in Chinese, which I can not read.

**Comment by worldofpeace** [comment]
@romildo Could we remove this before 20.09 release? (so it's not in 20.09)

**Comment by asdf8dfafjk** [comment]
I just want to say one thing, I've only ever used a single deepin software (screenshot) and it's absolutely the best screenshot software I've ever used including on windows. There is no point in removing what already works until it starts breaking or it deals with files downloaded from internet. 

Deepin screenshot is, to me, an example of how user friendly software is written.

**Comment by worldofpeace** [comment]
@asdf8dfafjk I would agree, deepin-screenshot was even better than flameshot which is very similar. I use elementary-screenshot which has a very good flow, it's just lacking all the features the latter have. I guess we can also close this issue since the status of packaging DDE is that it is now abandoned.

**Comment by asdf8dfafjk** [comment]
While my comment was specifically about deepin, I would say it would be great if you leaders could have a policy of sorts on removing a package. Personally I would wait until its broken or there is a security risk in some adversarial model. (screenshot, for example, doesn't have one in my limited understanding).

**Comment by worldofpeace** [comment]
@asdf8dfafjk I think collectively maintainers of desktop managers should be responsible for deciding if we should have a different DE added into nixpkgs and what expectations are going to be made of it. And yes, having policies for these things is actually a thing I've discussed in length in some videos (I think?) and on discourse. I believe the deprecation RFC would be something you're interested in, since it essentially covers this.

**Comment by jtojnar** [comment]
@asdf8dfafjk You can argue that for packages that are abandoned upstream but for live software there is another issue – including a package that is out of date has a negative impact not just on us as a distribution but at the upstream project as well, see for example the Debian vs xscreensaver drama. We cannot be good free software citizens while essentially misrepresenting the upstream project by shipping an outdated version.

**Comment by asdf8dfafjk** [comment]
@worldofpeace My point was about individual softwares where the quality is so high that its clear that an archived software still beats others. That said, since you say there already exists and policy and since you and romildo seem to be the maintainers, I defer.
