### ISSUE TITLE
Package LibreWolf

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#94918]
**Project description**
A fork of Firefox, focused on privacy, security and freedom.

**Metadata**

* homepage URL: https://librewolf-community.gitlab.io/
* source URL: https://gitlab.com/librewolf-community/browser
* license: Mozilla Public License 2.0
* platforms: linux, darwin, windows

**Comment by SCOTT-HAMILTON** [comment]
Already packaged on NUR http://nur.nix-community.org/repos/sikmir/.

**Comment by vcunat** [comment]
Note: [the one on NUR](https://github.com/nix-community/nur-combined/blob/master/repos/sikmir/pkgs/applications/librewolf/default.nix) is only binary version for darwin.

**Comment by onny** [comment]
I made an easy package out of the Librewolf AppImage and it's working :) https://git.project-insanity.org/onny/nur-packages/-/blob/master/pkgs/librewolf-bin/default.nix

**Comment by zyansheep** [comment]
This would be nice to have to replace firefox

**Comment by zeorin** [comment]
I would also love the ability to replace Firefox.

I wonder if it would make sense to take the same approach that was taken for the Chromium browsers, and create a general `mkGeckoDerivation` that is then used by Firefox, Librewolf, and maybe even GNU IceCat's expressions.

**Comment by Masacaai** [comment]
Is work being done on this issue? The AppImage version works, but a native package in the NixOS repository would be greatly appreciated!

**Comment by TLATER** [comment]
I've also made a stab at this in #136343, this time using the existing Firefox packaging infrastructure - I don't think a `mkGeckoDerivation` is really necessary for this, librewolf is actually just a few patches on top of latest Firefox, this can already be done easily with the existing infrastructure. The wrapper is more complex, though, and could use some rethinking.

I'd appreciate a look through from someone more familiar with all of this, to see if the approach even makes sense :)
