### ISSUE TITLE
Docker depends on utillinux

### ISSUE THREAD

**Issue by fduraffourg** [NixOS/nixpkgs#9492]
Hi,

I'm using 
Docker needs blkid (depends on utillinux).
I enable docker with the following configuration only:

    virtualisation.docker.enable = true;

I get the following status:

    ● docker.service - Docker Application Container Engine
       Loaded: loaded (/nix/store/avhm5zj9rzq6rbh9idlzndqzvp26v7r2-unit-docker.service/docker.service)
       Active: failed (Result: exit-code) since Fri 2015-08-28 13:15:26 UTC; 1min 53s ago
      Process: 10372 ExecStartPost=/nix/store/q3riq7z8n850lgqrzrn31qjf5j3yb92k-unit-script/bin/docker-post-start (code=exited, status=0/SUCCESS)
      Process: 10371 ExecStart=/nix/store/dnk6r07m4ds4ji2n2p4kbpp3abv4h-docker-1.8.1/bin/docker --daemon=true --group=docker (code=exited, status=1/FAILURE)
     Main PID: 10371 (code=exited, status=1/FAILURE)

    Aug 28 13:15:26 n4 systemd[1]: Started Docker Application Container Engine.
    Aug 28 13:15:26 n4 docker[10371]: Warning: '--daemon' is deprecated, it will be removed soon. See usage.
    Aug 28 13:15:26 n4 docker[10371]: time="2015-08-28T13:15:26Z" level=warning msg="please use 'docker daemon' instead."
    Aug 28 13:15:26 n4 docker[10371]: time="2015-08-28T13:15:26.447966291Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
    Aug 28 13:15:26 n4 docker[10371]: time="2015-08-28T13:15:26.482644879Z" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: Could not query and save base device UUID:exec: \"blkid\": executable file not found in $PATH"
    Aug 28 13:15:26 n4 docker[10371]: time="2015-08-28T13:15:26.482713086Z" level=fatal msg="Error starting daemon: error initializing graphdriver: Could not query and save base device UUID:exec: \"blkid\": executable file not found in $PATH"
    Aug 28 13:15:26 n4 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
    Aug 28 13:15:26 n4 systemd[1]: Unit docker.service entered failed state.
    Aug 28 13:15:26 n4 systemd[1]: docker.service failed.

The path from utillinux is missing from the service unit:

    [Unit]
    After=network.target
    Description=Docker Application Container Engine

    [Service]
    Environment="LOCALE_ARCHIVE=/nix/store/2mbqc6p36xlyl21d4mf1zhmprmqijwkk-glibc-locales-2.21/lib/locale/locale-archive"
    Environment="MODULE_DIR=/run/current-system/kernel-modules/lib/modules"
    Environment="PATH=/nix/store/z0rgmk4hqwhskmskm0c65680v4652n32-kmod-21/bin:/nix/store/p48nbf29nkv54vbvwqfqccwym58zf6bb-coreutils-8.24/bin:/nix/store/vmfzhzfh5w3hzxh7y0i4pf28h6jbqi62-findutils-4.4.2/bin:/nix/store/qrk6cndaf867z1blcfa9hpxrlar265j7-gnugrep-2.21/bin:/nix/store/5i5salk61869jjac0mgvj4n4agg2k2q0-gnused-4.2.2/bin:/nix/store/p0smmqn5jvf8hc34k8blixarpv3kj5q0-systemd-217/bin:/nix/store/z0rgmk4hqwhskmskm0c65680v4652n32-kmod-21/sbin:/nix/store/p48nbf29nkv54vbvwqfqccwym58zf6bb-coreutils-8.24/sbin:/nix/store/vmfzhzfh5w3hzxh7y0i4pf28h6jbqi62-findutils-4.4.2/sbin:/nix/store/qrk6cndaf867z1blcfa9hpxrlar265j7-gnugrep-2.21/sbin:/nix/store/5i5salk61869jjac0mgvj4n4agg2k2q0-gnused-4.2.2/sbin:/nix/store/p0smmqn5jvf8hc34k8blixarpv3kj5q0-systemd-217/sbin"
    Environment="TZDIR=/nix/store/pl3066vi01b5ynjxi9wf51yyg8dnv43b-tzdata-2015f/share/zoneinfo"

    X-RestartIfChanged=false

    ExecStart=/nix/store/dnk6r07m4ds4ji2n2p4kbpp3abv4h-docker-1.8.1/bin/docker --daemon=true --group=docker 
    ExecStartPost=/nix/store/q3riq7z8n850lgqrzrn31qjf5j3yb92k-unit-script/bin/docker-post-start
    LimitNOFILE=1048576
    LimitNPROC=1048576

If I add utillinux as a buildInputs on the derivation, it doesn't solve the issue. The unit is generated by:
https://github.com/NixOS/nixpkgs/blob/release-15.09/nixos/modules/virtualisation/docker.nix

I'm using nixos 15.09:

    [root@n4]# nixos-version 
    15.09.17.9be7d99 (Dingo)

**Comment by offlinehacker** [comment]
I have this fixed already, will push during the weekend, tnx!

**Comment by domenkozar** [comment]
@fduraffourg can you confirm the fix?

**Comment by fduraffourg** [comment]
It's OK now.
Thanks
