### ISSUE TITLE
Add agda library Generic

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#94932]
**Project description**

Generics library for agda

**Metadata**

* homepage URL: https://github.com/effectfully/Generic
* source URL: https://github.com/effectfully/Generic
* license: ? (https://github.com/effectfully/Generic/issues/3)
* platforms: All I guess

CC: @alexarice

**Comment by alexarice** [comment]
Is this 2.6.1 compatible?

**Comment by turion** [comment]
That's a good question. I haven't tried yet.

**Comment by turion** [comment]
The license is MIT, and there was a recent release compatible with 2.6.1.

**Comment by turion** [comment]
(See https://github.com/effectfully/Generic/issues/3#issuecomment-670977151)
