### ISSUE TITLE
CMake: Set CMAKE_OSX_ only on Darwin?

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#94952]
In 68513e40711cd942144a1da9c9e434b378c2c762 (part of #77632) `CMAKE_OSX_ARCHITECTURES=x86_64` was moved from `pkgs/stdenv/darwin/default.nix` to `pkgs/development/tools/build-managers/cmake/setup-hook.sh`. As a result `-DCMAKE_OSX_ARCHITECTURES=x86_64` is since then set on Linux as well.
Until now this wasn't a problem as https://cmake.org/cmake/help/v3.18/variable/CMAKE_OSX_ARCHITECTURES.html states that:
> This variable is ignored on platforms other than Apple.

Unfortunately that behaviour changed in CMake 3.18:
- Nixpkgs issue: https://github.com/NixOS/nixpkgs/issues/94905
- CMake issue: https://gitlab.kitware.com/cmake/cmake/-/issues/21072

To avoid such regressions in the future it might be a good idea to set the following two CMake flags ([source](https://github.com/NixOS/nixpkgs/blob/68513e40711cd942144a1da9c9e434b378c2c762/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L53)) only on Darwin:
```
    # on macOS i686 was only relevant for 10.5 or earlier.
    cmakeFlags="-DCMAKE_OSX_ARCHITECTURES=x86_64 $cmakeFlags"

    # we never want to use the global macOS SDK
    cmakeFlags="-DCMAKE_OSX_SYSROOT= $cmakeFlags"
```

cc CMake maintainers: @ttuegel @lnl7
cc @orivej (found this regression)

**Comment by ttuegel** [comment]
I don't think setting it as an environment variable will have any effect, so we will need to put a guard around it in the setup hook.

**Comment by matthewbauer** [comment]
I think just adding `if [ "$(uname)" = Darwin ]` on the CMake setup-hook is probably the easiest working.

**Comment by doronbehar** [comment]
Why not use a Nix conditional? It should spare at least the Darwin rebuilds if done right.

**Comment by matthewbauer** [comment]
> Why not use a Nix conditional? It should spare at least the Darwin rebuilds if done right.

That will probably work, but splitting the setup hook could be a little tricky. We'd need two setup hooks - one for all systems, and one for darwin (and maybe even one for linux for consistency). It would definitely be better for issues like these in the future, but I'm always a little hesitant to rework some of the Bash logic given its brittleness.

**Comment by primeos** [comment]
> I think just adding if [ "$(uname)" = Darwin ] on the CMake setup-hook is probably the easiest fix.

I kinda like that idea as it's simple and minimal. Though that might cause problems for cross-builds (if that even works between e.g. Darwin and Linux)? Would be nice if there would be an environment variable available in the Nix build for this (both with and without sandboxing).

> That will probably work, but splitting the setup hook could be a little tricky.

Yeah, I guess merging the common parts is the most tricky part. One option could be to add scripts for Linux and Darwin that set and export an environment variable and then source `setup-hook.sh`? Or I guess we could use Nix conditionals if we change `setup-hook.sh;` to a Nix expression like `writeText` (but that would likely be less optimal as it won't be recognized as a shell script if we cannot somehow read the content of `setup-hook.sh` and interpret it as text with Nix expressions).

**Comment by kvtb** [comment]
Another problem: since https://github.com/libjpeg-turbo/libjpeg-turbo/commit/399aa374bd4778377c7d1b90658ea40da0ef38d6 `libjpeg-turbo` is broken on `i686-linux`.

`cmakeFlags = [ "-DCMAKE_OSX_ARCHITECTURES="` does fix the build, but it would be much better if OSX featued won't leak into Linux at al.

**Comment by kvtb** [comment]
I hope it is fixed in https://github.com/NixOS/nixpkgs/pull/114817

**Comment by primeos** [comment]
Nice! d16a8753d91365d0239eec9549b11e7a61c1c61b (#114817) fixes/avoids the issues came from `CMAKE_OSX_ARCHITECTURES` so I guess we can close this now.

`CMAKE_OSX_SYSROOT` is still set on Linux but at least that didn't seem to cause any issues so far. If someone has time and motivation it might be nice to drop it on Linux as well (like in d16a8753d91365d0239eec9549b11e7a61c1c61b).
