### ISSUE TITLE
zoom-us fails to start

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#94958]
**Describe the bug**

**To Reproduce**
1. Run Ubuntu 20.04
2. Use home-manager to install `pkgs.zoom-us`
```
❯ zoom-us
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
$HOME = /home/skainswo 
Can't load/home/skainswo/.config/zoomus.conf
export SSB_HOME=/home/skainswo/.zoom; export QSG_INFO=1; export QT_AUTO_SCREEN_SCALE_FACTOR=1; export LD_LIBRARY_PATH=/nix/store/74ji3kkar98bpn386hds7yaarcpp69d3-zoom-us-5.1.422789.0705/share/zoom-us; export BREAKPAD_CLIENT_FD=3; /nix/store/74ji3kkar98bpn386hds7yaarcpp69d3-zoom-us-5.1.422789.0705/share/zoom-us/zoom "" 
zoom started.
Client: Breakpad is using Client-Server Mode! client fd = 3
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 1C:6F:65:30:25:46][client: Linux][OS: Ubuntu 20.04.1 LTS][Hardware: CPU Core:4 Frenquency:2.8 G Memory size:11978MB CPU Brand:Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz GPU Brand:][Req ID: ]
Linux Client Version is 5.1.422789.0705
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = ubuntu:GNOME;   GDMSESSION = ubuntu
Graphics Card Info:: 03:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB Rev. 2] (rev a1)
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name: ubuntu 
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
ZoomLauncher: new dump generated from pid 29520, path: /home/skainswo/.zoom/logs/2629ad45-07ca-4c74-7ffa99a0-b4b529da.dmp
$HOME = /home/skainswo 
Aborted (core dumped)
success to create child process,status is 34304.
zoom exited normally.
Something went wrong while running zoom,exit code is 134.
ZoomLauncher exit.
```

**Expected behavior**
Zoom to work.

**Screenshots**
n/a

**Additional context**
I'm running with a GTX 1060 graphics card.

**Notify maintainers**

@danbst @tadfisher @doronbehar

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-42-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"nixpkgs-20.09pre237352.8d57f75f7a1, home-manager"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by samuela** [comment]
Update: after a quick `nix-channel --update` and `home-manager switch`, and now when I launch zoom simply nothing happens:
```
~/dev 
❯ zoom-us

~/dev 
❯ echo $?   
0

~/dev 
❯ 
```
But there's no window that opens, no new app in the tray, nothing as far as I can tell...

**Comment by doronbehar** [comment]
Try update your system and reboot it along with your user channels. Also, there should be logs somewhere at ~/.local/share or ~/.cache . I once experienced such issue and it was due to the system fonts not activated after system update.

**Comment by doronbehar** [comment]
@samuela there are logs found at: `~/.zoom/logs`. Could you paste the content of the files there so I could try to help you?

**Comment by samuela** [comment]
Ok, I did a `nix-channel --update`, `home-manager switch`, and reboot and then tried launching `zoom-us`. Here are the contents of my `~/.zoom/logs`:

[crash_skainsworth@gmail.com-757 1369 2318-5.1.422789.0705_skainswo-X58A-UD3R__2020-0816-193656.dmp.gz](https://github.com/NixOS/nixpkgs/files/5081284/crash_skainsworth%40gmail.com-757.1369.2318-5.1.422789.0705_skainswo-X58A-UD3R__2020-0816-193656.dmp.gz)
[crash_skainsworth@gmail.com-757 1369 2318-5.1.422789.0705_skainswo-X58A-UD3R__2020-0816-194852.dmp.gz](https://github.com/NixOS/nixpkgs/files/5081285/crash_skainsworth%40gmail.com-757.1369.2318-5.1.422789.0705_skainswo-X58A-UD3R__2020-0816-194852.dmp.gz)
[crash_skainsworth@gmail.com-757 1369 2318-5.1.422789.0705_skainswo-X58A-UD3R__2020-0816-195151.dmp.gz](https://github.com/NixOS/nixpkgs/files/5081286/crash_skainsworth%40gmail.com-757.1369.2318-5.1.422789.0705_skainswo-X58A-UD3R__2020-0816-195151.dmp.gz)
[zoom_stdout_stderr.log](https://github.com/NixOS/nixpkgs/files/5081287/zoom_stdout_stderr.log)

**Comment by samuela** [comment]
bump, still an issue for me!

**Comment by arathunku** [comment]
This issues and logs looks very similar to https://github.com/NixOS/nixpkgs/issues/82959

(I've the same issue)

**Comment by SebTM** [comment]
Closed due to duplicate and stale ✌🏻 (please reopen if not)
