### ISSUE TITLE
fetchFromGithub fails with `fatal: reference is not a tree`

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#94951]
```
error: --- Error --- nix-daemon
builder for '/nix/store/j0792kyxfki3pkwczyjvgbl31rdyqd8v-source.drv' failed with exit code 1; last 10 log lines:
   * [new tag]         v1.3.1     -> v1.3.1
   * [new tag]         v1.3.2     -> v1.3.2
   * [new tag]         v1.3.3     -> v1.3.3
   * [new tag]         v1.4.0     -> v1.4.0
   * [new tag]         v1.5.0     -> v1.5.0
   * [new tag]         v2.0.0     -> v2.0.0
   * [new tag]         v2.0.1     -> v2.0.1
   * [new tag]         v2.1.0     -> v2.1.0
  fatal: reference is not a tree: 29030f55ca518bb1be5113ab0a8e134772024a9d
  Unable to checkout 29030f55ca518bb1be5113ab0a8e134772024a9d from https://github.com/peterrudenko/hopscotch-map.git.
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix-build
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/ai2lk98dn6imair70q29f261blsgq743-helio-workstation-3.1.drv' failed to build
```

**To Reproduce**
1. Clone https://github.com/NixOS/nixpkgs/pull/94950
2. `nix-build -A helio-workstation`

**Expected behavior**
`fetchFromGithub` should successful pull the source code.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.11, NixOS, 20.09.20200805.8e2b14a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `"nixos-20.09pre237279.8e2b14aceb1, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

My `flake.lock`: https://gist.github.com/suhr/297987502513837fe6142adde4acfd69

**Comment by prusnak** [comment]
Seems like an issue of included submodule `hopscotch-map`. However, the upstream repo does contain the reference commit:

https://github.com/peterrudenko/hopscotch-map/commit/29030f55ca518bb1be5113ab0a8e134772024a9d

**Comment by jonringer** [comment]
I don't think this is an issue with nix, but rather that the repo, in fact, does not contain that commit.

https://github.com/peterrudenko/hopscotch-map/commit/29030f55ca518bb1be5113ab0a8e134772024a9d

**Comment by suhr** [comment]
I would like to agree, but running `git clone --recurse-submodules https://github.com/helio-fm/helio-workstation.git` manually does not causes any errors.

**Comment by suhr** [comment]
Though nix can successfully clone tag `3.0`. Well, then it makes sense.

**Comment by suhr** [comment]
Yet nix can't clone `develop` as well.

**Comment by suhr** [comment]
Fixed in Helio repository.
