### ISSUE TITLE
tdesktop (telegram-desktop) fails to build

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#94988]
**Describe the bug**
Telegram desktop fails to build.

**To Reproduce**
1. On the updated unstable channel, run `nix-env -iA nixos.tdesktop`.

**Expected behavior**
`tedesktop` should build.

**Notify maintainers**
@primeos @abbradar

**Comment by primeos** [comment]
Duplicate of #94905 and already fixed in https://github.com/NixOS/nixpkgs/commit/e7987936c1b28b0de3d774731bc26cde47c24c44.
