### ISSUE TITLE
ROOT from nixos-unstable fails to build on aarch64-linux (Nix-on-Droid)

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#94993]
**Issue description**
ROOT (CERN ROOT) installation on nix-on-droid failed after Android update and reinstallanion of nix-on-droid-app. Not sure if ROOT is also updated recently.

After adding `root` to `home-packages` inside `~/.config/nixpkgs/nix-on-droid.nix` and do `nix-on-droid switch`,

```console
ilding activation package...                  note: keeping build directory '/data/data/com.termux.nix/files/usr/tmp/nix-build-root-6.18.04.drv-0'                                            builder for '/nix/store/lqwl135xdj8bd62cw8wanmxxch4qj8i7-root-6.18.04.drv' failed with exit code 1; last 10 log lines:

                                                    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:12 (project)
                                                                                                  -- Configuring incomplete, errors occurred!     See also "/tmp/nix-build-root-6.18.04.drv-0/root-6.18.04/build/CMakeFiles/CMakeOutput.log".     See also "/tmp/nix-build-root-6.18.04.drv-0/root-6.18.04/build/CMakeFiles/CMakeError.log".    cannot build derivation '/nix/store/b0scwpdl9zi9vnsg933iji88mk7zy3zz-home-manager-path.drv': 1 dependencies couldn't be built                   cannot build derivation '/nix/store/c53k5vz7zrn89mlrgxwq5dy5jjn03zzq-nix-on-droid-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pfrmgffbrmw8abwf6pr55p6r918v39dr-nix-on-droid-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/pfrmgffbrmw8abwf6pr55p6r918v39dr-nix-on-droid-generation.drv' failed
```

I'm not sure if it is the issue of ROOT or that of Nix-on-Droid. It was convenient to have ROOT installed on the cellphone.

**teps to reproduce**
1.  Download and install Nix-on-Droid from f-Droid.
2.  Install with the default bootstrapping tarball.
3.  Run
    ```
    nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
    nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz
    ```
4.  Uncommend the recommended element of `environment.packages` and the settings of  `home-manager` in `~/.config/`.
5. Add `home.useUserPackages = true;` to enable `home-manager` to cesolve the same-priorty conflicts automatically.
6.  Run
    ```
    nix-channel --update
    nix-env --upgrade
    nix-on-droid switch
    ```
7.  Add
    ```nix
    home.packages = with pkgs; [
      gcc
      root
    ];
    ```
    in the home-manager settings in `nix-on-droid.nix`.
8. Run `nix-on-droid switch`.

**Additional context**
`CMakeOutput.log`:
```
The system is: Linux - 4.9.186-perf+ - aarch64  Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.             Compiler: /nix/store/b7n1cgzx8vqd28fqkz2nf77844xyg47n-gcc-wrapper-9.3.0/bin/gcc                 Build flags:                                    Id flags:

The output was:                                 0

                                                Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"       
The C compiler identification is GNU, found in "/tmp/nix-build-root-6.18.04.drv-0/root-6.18.04/build/CMakeFiles/3.18.0/CompilerIdC/a.out"       
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.       Compiler: /nix/store/b7n1cgzx8vqd28fqkz2nf77844xyg47n-gcc-wrapper-9.3.0/bin/g++                 Build flags:
Id flags:

The output was:
0


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is GNU, found in "/tmp/nix-build-root-6.18.04.drv-0/root-6.18.04/build/CMakeFiles/3.18.0/CompilerIdCXX/a.out"
```

`CMakeError.log`
```
Detecting C compiler ABI info failed to compile with the following output:                      Change Dir: /tmp/nix-build-root-6.18.04.drv-0/root-6.18.04/build/CMakeFiles/CMakeTmp                                                            Run Build Command(s):/nix/store/mrgylqc5qgcig49whzdjixdxb3z54vnk-gnumake-4.3/bin/make cmTC_7815a/fast && /nix/store/mrgylqc5qgcig49whzdjixdxb3z54vnk-gnumake-4.3/bin/make  -f CMakeFiles/cmTC_7815a.dir/build.make CMakeFiles/cmTC_7815a.dir/build                                              make: /nix/store/mrgylqc5qgcig49whzdjixdxb3z54vnk-gnumake-4.3/bin/make: Function not implemented
make: *** [Makefile:140: cmTC_7815a/fast] Error 127                                                                                                                                             
                                                Determining if the C compiler works failed with the following output:                           Change Dir: /tmp/nix-build-root-6.18.04.drv-0/root-6.18.04/build/CMakeFiles/CMakeTmp                                                            Run Build Command(s):/nix/store/mrgylqc5qgcig49whzdjixdxb3z54vnk-gnumake-4.3/bin/make cmTC_0cc3f/fast && /nix/store/mrgylqc5qgcig49whzdjixdxb3z54vnk-gnumake-4.3/bin/make  -f CMakeFiles/cmTC_0cc3f.dir/build.make CMakeFiles/cmTC_0cc3f.dir/build
make: /nix/store/mrgylqc5qgcig49whzdjixdxb3z54vnk-gnumake-4.3/bin/make: Function not implemented
make: *** [Makefile:140: cmTC_0cc3f/fast] Error 127
```

**Notify maintainers**

@veprbl @t184256 

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 4.9.186-perf+`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(nix-on-droid): `"home-manager, nix-on-droid-20.03, nixpkgs-20.09pre237606.b50ef9afa11"`
 - nixpkgs: `/data/data/com.termux.nix/files/home/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: root
# a list of nixos modules affected by the problem
module:
```

**Comment by cab404** [comment]
Are you sure that's not https://github.com/t184256/nix-on-droid you should be sending this to?

**Comment by t184256** [comment]
Depends on whether it fails on hydra, but I can't find any recent unstable aarch64 jobs.

@ShamrockLee, I don't think it makes much sense to compile root on-device anyway, root is giant (pun intended), it times out even on hydra: https://hydra.nixos.org/job/nixos/release-20.03-aarch64/nixpkgs.root.aarch64-linux. The best course of action is probably to install it from a pin that did compile on hydra.

**Comment by ShamrockLee** [comment]
I used to be able to install it on my phone within a reasonable amount of time, which is much shorter than that required to have ROOT compiled.
@t184256  What can I do to install a version of ROOT that is built successfully on Hydra?

**Comment by t184256** [comment]
@ShamrockLee, poke around https://hydra.nixos.org/build/124088542#tabs-buildinputs, there is a mention of the specific nixpkgs commit that resulted in the last successful cached build. Then [pin nixpkgs](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs) in your config and use `root` from there.

There's also 'Actions -> Reproduce locally', though I'm not sure what it does. Still, might be helpful.

**Comment by ShamrockLee** [comment]
@t184256 Thanks a lot!

BTW, I started installing ROOT from channel `nixos-20.03` 90 minutes ago. As the binary cache for `root` is currently not available, it started compiling on my device. It has currently done 53% of the work, and is still running.

There might be some problem in the `root` package in the `nixos-unstable` channel that stops it from compiling.

**Comment by ShamrockLee** [comment]
I got it installed from the nixos-unstable binary cache on Aug 31st, and it works.
The abscence of binary substitution before may result from Hydra's timeout, and the failure to build locally may be the problem of nix-on-droid itself, as the package `hello` cannot be built without the binary cache. ([nix-on-droid issue 80](https://github.com/t184256/nix-on-droid/issues/80))

**Comment by ShamrockLee** [comment]
UPDATE: It is [nix-on-droid issue 91](https://github.com/t184256/nix-on-droid/issues/91) that cause the build to fail locally.
Closing.
