### ISSUE TITLE
vim_configurable: feature request: Install plugins only for (or not for) certain users

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#95128]
One can, and I do, use `vim_configurable` to declare in my NixOS configuration what Vim plugins I want.  However, the same configuration of `vim_configurable` is available via `environment.systemPackages` for all users, and its plugins are loaded for all users, including if I log in as root and run Vim to edit root-owned files.  I install various plugins for development use that root does not need and, optimally, should not be running.  Would it be feasible to include an option in the configuration of `vim_configurable` to restrict given plugins to given users, or simply to non-root users?  I know nothing of the internals of `vim_configurable` and am unlikely to do this work myself, for which I apologize.

**Comment by 8573** [comment]
I suppose it would be equivalent to allow installing different instances of `vim_configurable` for different users— and indeed I see that there is the `users.users.<name?>.packages` option, of which I think I once knew but had forgotten long ago.  I'll leave this ticket open in case the feature request somehow nevertheless is thought sensible, but feel free to close it.

**Comment by symphorien** [comment]
I think this is the kind of features home-manager is used for.

**Comment by teto** [comment]
not sure for vim but for neovim, you can use neovimUtils to write a per-user init.vim .

**Comment by teto** [comment]
this is how it's done in home-manager https://github.com/nix-community/home-manager/blob/7591c8041d290d4bb99679e9fed2d8061a8f0435/modules/programs/neovim.nix#L244
