### ISSUE TITLE
20.3 initrd.network.ssh Dropbear does not find SSH host key

### ISSUE THREAD

**Issue by AntonLydike** [NixOS/nixpkgs#95166]
**Describe the bug**
dropbear initrd ssh doesn't find host keys

**To Reproduce**
1. enable ssh in initrd:
  ```
  boot.initrd.availableKernelModules = [ "igb" ];
  boot.initrd.network = {
    enable = true;
    ssh = {
      enable = true;
      port = 2222;
      authorizedKeys = [ "ecdsa-sha2-nistp256 <key>" ];
      hostECDSAKey = /etc/nixos/host_ecdsa_key;
    };
    postCommands = ''
      echo 'cryptsetup-askpass' >> /root/.profile
    '';
  };
  ```
2. generate a host key `nix run nixpkgs.dropbear -c dropbearkey -t ecdsa -f host_ecdsa_key`
3. build the config and reboot

**Expected behavior**
dropbear should find the ecdsa host key and start on port 2222

**screenshot**
![boot image](https://i.imgur.com/Sqmx8MK.jpg)

**Additional context**
I suspect that `boot.initrd.secrets` is at least partly broken. I unpacked the built initrd image and the host key is not packaged there (nor anywhere in `/boot/kernels`), although I have to admit that I don't really know how this should work.

All my boot and networking config (as requested)
```nix
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  fileSystems.boot.device = "/dev/disk/by-uuid/<uuid>";
  fileSystems.boot.mountPoint = "/boot";

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/EFI";
  boot.loader.grub = {
    enable = true;
    device = "nodev";
    version =   2;
    efiSupport = true;
    enableCryptodisk = true;
    useOSProber = true;
  };
  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/<uuid>";
    preLVM = true;
    allowDiscards = true;
  };
  # enable ssh in initrd
  boot.initrd.availableKernelModules = [ "igb" ];
  boot.initrd.network = {
    enable = true;
    ssh = {
      enable = true;
      port = 2222;
      authorizedKeys = [ "ecdsa-sha2-nistp256 <key>" ];
      hostECDSAKey = /etc/nixos/host_ecdsa_key;
    };
    postCommands = ''
      echo 'cryptsetup-askpass' >> /root/.profile
    '';
  };

  boot.tmpOnTmpfs = true;

  networking.hostName = "hostname"; # Define your hostname.
  networking.networkmanager = {
    enable = true;
  };
  networking.nameservers = [
      "192.168.0.1"
      "194.150.168.168"
      "212.82.226.212"
      "1.1.1.1"
  ];

  networking.wireless.enable = false;  # Enables wireless support via wpa_supplicant.

  networking.interfaces.enp10s0.useDHCP = true;
  # other settings
```

**Notify maintainers**
@abbradar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.03.2685.977000f149b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2685.977000f149b, nixos-unstable-20.09pre225264.683c68232e9"`
 - channels(anton): `"nixos-unstable-20.09pre236721.840c782d507, nixos-20.03.2685.977000f149b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module: boot.initrd.network.ssh
```

**Comment by Ma27** [comment]
>  dropbear initrd ssh doesn't find host keys

can you tell what *exactly* happened? To set this up, you also need to configure a network interface in initrd and you usually have to wait a bit until the ssh server is up and running.

**Comment by AntonLydike** [comment]
Here is a screenshot of the boot sequence:
![boot sequence](https://i.imgur.com/Sqmx8MK.jpg)

I also added this line to my configuration:
```
  boot.initrd.availableKernelModules = [ "igb" ];
```
as suggested by [this nixos wiki entry about luks+ssh](https://nixos.wiki/wiki/Remote_LUKS_Unlocking)

**Comment by Ma27** [comment]
Which boot-loader do you use?

**Comment by AntonLydike** [comment]
Ah sorry, I use EFI+grub. This is the whole boot + networking section in my config:

```nix
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  fileSystems.boot.device = "/dev/disk/by-uuid/<uuid>";
  fileSystems.boot.mountPoint = "/boot";

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/EFI";
  boot.loader.grub = {
    enable = true;
    device = "nodev";
    version =   2;
    efiSupport = true;
    enableCryptodisk = true;
    useOSProber = true;
  };
  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/<uuid>";
    preLVM = true;
    allowDiscards = true;
  };
  # enable ssh in initrd
  boot.initrd.availableKernelModules = [ "igb" ];
  boot.initrd.network = {
    enable = true;
    ssh = {
      enable = true;
      port = 2222;
      authorizedKeys = [ "ecdsa-sha2-nistp256 <key>" ];
      hostECDSAKey = /etc/nixos/host_ecdsa_key;
    };
    postCommands = ''
      echo 'cryptsetup-askpass' >> /root/.profile
    '';
  };

  boot.tmpOnTmpfs = true;

  networking.hostName = "hostname"; # Define your hostname.
  networking.networkmanager = {
    enable = true;
  };
  networking.nameservers = [
      "192.168.0.1"
      "194.150.168.168"
      "212.82.226.212"
      "1.1.1.1"
  ];

  networking.wireless.enable = false;  # Enables wireless support via wpa_supplicant.

  networking.interfaces.enp10s0.useDHCP = true;
  # other settings
```

**Comment by Ma27** [comment]
Hmm why are both `systemd-boot` and `grub` enabled? Which one is used as boot-loader? It might be possible that you're booting through `grub`, but have a few settings internally declared due to `systemd-boot` being enabled (e.g. `systemd-boot` sets `boot.loader.supportsInitrdSecrets` to `true`).

**Comment by AntonLydike** [comment]
Oh okay, that was indeed the issue, should have probably caught that myself. Thanks for the help!
