### ISSUE TITLE
qt514.qtbase build broken on darwin

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#95199]
Example log: https://hydra.nixos.org/build/125099625
```
ERROR: Cannot compile a minimal program. The toolchain or QMakeSpec is broken.
```

On master this started to fail in the moment of update: #84232 &ndash; but it was merged at once with other staging changes, so I'm not 100% sure that MR was what triggered the failure.  This blocks the `nixpkgs-unstable` channel.

**Comment by acowley** [comment]
The few lines before that seem informative:

```
> /private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/mkspecs/features/mac/toolchain.prf:3: Cannot find feature sdk
> Info: creating stash file /private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/config.tests/.qmake.stash
> /private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/mkspecs/features/mac/default_post.prf:5: 'xcodeSDKInfo' is not a recognized replace function.
> Project WARNING: Qt requires at least version 10.14 of the platform SDK, you're building against version . Please upgrade.
+ cd /private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/config.tests/verifyspec && MAKEFLAGS= /nix/store/k3b37yadbn54kbc4yyhf621bxc234zw4-gnumake-4.3/bin/make
> Makefile:69: /private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/mkspecs/features/mac/sdk.mk: No such file or directory
> make: *** No rule to make target '/private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/mkspecs/features/mac/sdk.mk'.  Stop.
```

The `requires at least version 10.14 of the platform SDK, you're building against version ` part is concerning because our `darwin.apple_sdk.sdk.version` is 10.12.

**Comment by vcunat** [comment]
I expect we could keep darwin default at 5.12 for now.  We even still have outdated comment about an earlier case
```nix
  # TODO bump to 5.12 on darwin once it's not broken
```

**Comment by sikmir** [comment]
> The `requires at least version 10.14 of the platform SDK, you're building against version` part is concerning because our `darwin.apple_sdk.sdk.version` is 10.12.

https://github.com/NixOS/nixpkgs/issues/86299#issuecomment-621368897

**Comment by acowley** [comment]
@matthewbauer is the only person who's been steering the Apple SDK in nixpkgs ship for a while now, so I think it would be good to let him weigh in on whether or not we hold Qt back on darwin or push to update the SDK. I do not understand how the darwin bootstrapping works well enough to help with an SDK update.

**Comment by matthewmazzanti** [comment]
I've done some digging here to see if I can help get the channel unblocked. Unfortunately I don't have a Darwin system available, so I cant write/test a patch for this.

First thing to note is that it looks like you can define the platform SDK version you want to build against according to the docs [here](https://github.com/qt/qtbase/blob/3a6d8df5219653b043bd642668cee193f563ec84/config_help.txt#L194). This may allow us to set the platform SDK version without breaking a bunch of other builds by trying to upgrade the platform SDK version.

Digging through the logs, right before erroring out it seems that there are two things that blow up:
```
> /private/tmp/nix-build-qtbase-5.14.2.drv-0/qtbase-everywhere-src-5.14.2/mkspecs/features/mac/default_post.prf:5: 'xcodeSDKInfo' is not a recognized replace function.
> Project WARNING: Qt requires at least version 10.14 of the platform SDK, you're building against version . Please upgrade.
```

Specifically, the `xcodeSDKInfo` function is not defined, and from what I can tell is entirely removed as a part of this patch:
https://github.com/NixOS/nixpkgs/blob/f9d53e78941588ef66ded0d4ee27ec5e4b514988/pkgs/development/libraries/qt-5/5.14/qtbase.patch.d/0001-qtbase-mkspecs-mac.patch#L342-L346

Where its defined [here](https://github.com/qt/qtbase/blob/c1da6347e8d3ba73de20ab8fb3e50ec3359b75ac/mkspecs/features/mac/sdk.prf#L8-L21). I don't know the history here, so this may be a non-issue, but something to look at.

The other thing of note in the logs is the line `version 10.14 of the platform SDK, you're building against version .` The empty variable for the current version *might* indicate that qt is not able to find the platform SDK version. Again, I don't know the full history here so this may be a red herring.

**Comment by siraben** [comment]
I ran into this issue today when trying to compile `pkgs.python3.pkgs.pyqt5`

**Comment by prusnak** [comment]
For reference:
* update macOS SDK issue: https://github.com/NixOS/nixpkgs/issues/101229
* update macOS SDK PR: https://github.com/NixOS/nixpkgs/pull/101940

**Comment by prusnak** [comment]
Possible fix in https://github.com/NixOS/nixpkgs/pull/125548

**Comment by siraben** [comment]
@prusnak any updates on this?

**Comment by prusnak** [comment]
> @prusnak any updates on this?

We need to update macOS SDK to 10.14+ first.

**Comment by veprbl** [comment]
Why is this open? https://hydra.nixos.org/job/nixpkgs/trunk/libsForQt514.qt5.qtbase.x86_64-darwin
