### ISSUE TITLE
Packaging Request: Veloren

### ISSUE THREAD

**Issue by JonathanILevi** [NixOS/nixpkgs#95226]
**Project description**
Veloren is a multiplayer voxel RPG written in Rust. Veloren takes inspiration from games such as Cube World, Minecraft and Dwarf Fortress. The game is currently under heavy development, but is playable.

* homepage URL: veloren.net
* source URL: github.com/veloren/veloren
* license: GPL3
* platforms: "Linux, Mac, and Windows"

**Comment by MetaDark** [comment]
Veloren actually already has embedded nix files: https://github.com/veloren/veloren/tree/master/nix. Hey @AngelOnFira! I guess you might not recognize me, but I remember you telling me about the nix build for Veloren when I was visiting Colorado last year. Is there a reason why this hasn't been submitted to nixpkgs yet?

**Comment by AngelOnFira** [comment]
@MetaDark Hey :wave: I haven't looked too much into nix for Veloren, I know we had a contributor that added nix configs, but I don't think we've looked at packaging it. I think we officially build for the AUR, flatpak, and maybe a few others, not 100% sure though. I don't think there are any issues with doing this, but I'm not sure if there is anything special this might entail. Also, is it possible to package from a Gitlab repo? Our Github mirror isn't doing too hot since we're running into LFS restrictions. Github currently shows that the last commit was over a month ago :grimacing:

**Comment by AngelOnFira** [comment]
I'll include @yusdacra on this thread as they were the one to get our Nix stuff set up :100:

**Comment by MetaDark** [comment]
@AngelOnFira Yep, there's a helper called `fetchFromGitLab` which can be used. I'm not really sure how it integrates with LFS though since I think the archive it grabs doesn't include files from LFS.

**Comment by MetaDark** [comment]
It looks like it might be better to just use `fetchgit` and run the git lfs commands as part of of the `postFetch`. See https://discourse.nixos.org/t/how-to-fetch-lfs-enabled-repo-with-fetchfromgithub/5890/8.

**Comment by lboklin** [comment]
I tried to write a derivation to add to my flake-based system:
```nix
{ 
    veloren =
      let
        velorenSrc = pkgs.fetchgit {
          url = "https://gitlab.com/veloren/veloren";
          rev = "v0.8.0";
          sha256 = "sha256-Y/z9pLVknTJbz0QkZFsXtgBkMlaYAmKcGS4dqy9ApSQ=";
          leaveDotGit = true;
        };
        system = "x86_64-linux";
        sources = import "${velorenSrc}/nix/sources.nix" { inherit system pkgs; };
      in
        import "${velorenSrc}/nix" { inherit system sources; };
    #...
}
```
The git-lfs stuff is handled already in there, but I get stuck on this error:
```
error: --- Error -------------------------------------------------------------------------------- nix
in pure evaluation mode, 'fetchurl' requires a 'sha256' argument
```
which originates from `/nix/store/fghm13lvj2l83bxradhxkjvn2x0h8n7k-nixpkgsMoz-src/rust-overlay.nix` (meaning I don't know what I can do about this). This is getting pulled in from here: https://gitlab.com/veloren/veloren/-/blob/bce6e1c6e953c4531519ee4c4138ea0a7e34bb78/nix/nixpkgs.nix

**Comment by yusdacra** [comment]
Hello! That looks like an issue with `nixpkgs-mozilla`, which is what we use to pull in the Rust toolchain version we use (which is declared in the `rust-toolchain` file, in the root of the repo). I will try to reproduce that (i didn't try flakes much yet). For now you can try the `yusdacra/fix-nix-build-tag-bug` branch of the Veloren repository and see if it fixes it, or use `nix-env` to install it.

**Comment by lboklin** [comment]
> Hello! That looks like an issue with `nixpkgs-mozilla`, which is what we use to pull in the Rust toolchain version we use (which is declared in the `rust-toolchain` file, in the root of the repo). I will try to reproduce that (i didn't try flakes much yet). For now you can try the `yusdacra/fix-nix-build-tag-bug` branch of the Veloren repository and see if it fixes it, or use `nix-env` to install it.
> 
> EDIT: The branch is merged into `master` now, so you can use `master` branch :)

It seems to have fixed the issue. I'm now getting a failure from `/nix/store/h42zql6d38gwglnb8q0dabsp3ypxkl5p-gitLfsCheck.drv`: [stderr](https://gist.github.com/lboklin/9deb52d755af38d388b243cfa9678d80).

Using same expression as before but with latest rev from master.

**Comment by yusdacra** [comment]
> > Hello! That looks like an issue with `nixpkgs-mozilla`, which is what we use to pull in the Rust toolchain version we use (which is declared in the `rust-toolchain` file, in the root of the repo). I will try to reproduce that (i didn't try flakes much yet). For now you can try the `yusdacra/fix-nix-build-tag-bug` branch of the Veloren repository and see if it fixes it, or use `nix-env` to install it.
> > 
> > EDIT: The branch is merged into `master` now, so you can use `master` branch :)
> 
> It seems to have fixed the issue. I'm now getting a failure from `/nix/store/h42zql6d38gwglnb8q0dabsp3ypxkl5p-gitLfsCheck.drv`: [stderr](https://gist.github.com/lboklin/9deb52d755af38d388b243cfa9678d80).
> 
> Using same expression as before but with latest rev from master.

Yikes, that's my fault. It should've given you a message that says "git-lfs isn't setup, bla bla". `fetchgit` doesn't handle git-lfs so you'll need to setup git-lfs with the `postFetch` hook.

**Comment by lboklin** [comment]
I'm not having any luck getting LFS to work. 

I wrote this wrapper for `fetchgit`:
```nix
let
  fetchgitLFS = args:
    let
      args' = args // {
        fetchSubmodules = true;
        leaveDotGit = true;
        postFetch = ''
          git lfs install --local
          git lfs fetch
          git lfs checkout
        '';
      };

    in
      (pkgs.fetchgit args').overrideAttrs (oldAttrs: {
        nativeBuildInputs = oldAttrs.nativeBuildInputs or [] ++ [ pkgs.git-lfs ];
      });
in  # ...
```
and just substituted my usage of `fetchgit` for it, but when those `git lfs ...` commands are run, the current directory is `/build`, which neither is nor contains the repo. I figured this out by setting `postFetch` to 
```nix
''
pwd
ls -A
exit 1
''
```

**Comment by lboklin** [comment]
Aha, I had to `cd $out` before running the `git lfs ...` commands. Seems weird to me that it wouldn't put me in the repo in `postFetch` though.

**Comment by yusdacra** [comment]
> Aha, I had to `cd $out` before running the `git lfs ...` commands. Seems weird to me that it wouldn't put me in the repo in `postFetch` though.

 So does it work now? If so, nice!

**Comment by lboklin** [comment]
I now another error:
```
[...]
Nothing new to pack.
Updated git hooks.
Git LFS initialized.
fetch: Fetching reference refs/heads/fetchgit
Downloading LFS objects:   0% (0/1), 0 B | 0 B/s^Mbatch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
batch request: missing protocol: ""
error: failed to fetch some objects from ''
```
but at least the commands are run.

**Comment by lboklin** [comment]
Ok, so far I have this:
```nix
{ pkgs, ... }:

let
  fetchgitLFS = args:
    let
      args' = args // {
        fetchSubmodules = true;
        leaveDotGit = true;
        # deepClone = true;
        postFetch = ''
          cd $out
          git remote add origin ${args.url}
          git lfs install --local
          git lfs fetch
          git lfs checkout
        '';
      };

    in
      (pkgs.fetchgit args').overrideAttrs (oldAttrs: {
        nativeBuildInputs = oldAttrs.nativeBuildInputs or [] ++ [ pkgs.git-lfs ];
      });

  velorenSrc = fetchgitLFS {
    url = "https://gitlab.com/veloren/veloren";
    rev = "30563f59f3d09115b8b6a7d9fddb6cfb1f842e6a";
    sha256 = "sha256-vMl6FmpK7DLa7wtNh+n1H0MS0t6wcFqpDdqbjbFRj2Q=";
  };

  system = "x86_64-linux";

in
  import "${velorenSrc}/nix" { inherit system; }
```
but the problem is that every time I get a different hash, so there's always a mismatch.

**Comment by lboklin** [comment]
I don't know what it means by `error: assets/voxygen/audio/ambient/wind.ogg: cannot add to the index - missing --add option?
`

There's no `--add` flag for `git lfs checkout`, but that's the command producing the error. I don't really know how this works, tbh. 

I went through the process manually with a local clone of the repo and it worked fine.

**Comment by yusdacra** [comment]
> I don't know what it means by `error: assets/voxygen/audio/ambient/wind.ogg: cannot add to the index - missing --add option? `
> 
> There's no `--add` flag for `git lfs checkout`, but that's the command producing the error. I don't really know how this works, tbh.
> 
> I went through the process manually with a local clone of the repo and it worked fine.

That sounds like the index file is missing in the repo, which git-lfs can't operate without. Can you try putting `git checkout ${args.rev}` after adding the remote? TBH I don't see how it will help since `fetchgit` should already do that... But maybe that will work?

I can add a way to override the version & git-lfs command so that git and git-lfs commands won't run (we use git to determine what to put in the version string, both in game and in Nix derivation) and then you should be able to fetch it via `fetchFromGitLab`, which should have the assets too (downloading an archive from GitLab does at least). It would work, but I feel that's kinda dirty.

**Comment by lboklin** [comment]
Progress! Sort of.. 

We're back to 
```
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
builder for '/nix/store/h42zql6d38gwglnb8q0dabsp3ypxkl5p-gitLfsCheck.drv' failed with exit code 1
------------------------------------------------------------------------------------------------ show-trace ------------------------------------------------------------------------------------------------
trace: while evaluating the attribute 'DISABLE_GIT_LFS_CHECK' of the derivation 'rust_veloren-common-0.8.0'
```

**Comment by yusdacra** [comment]
> Progress! In a narrow sense of the word..
> 
> Adding `${args.rev}` helped. Now we're back to
> 
> ```
> error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
> builder for '/nix/store/h42zql6d38gwglnb8q0dabsp3ypxkl5p-gitLfsCheck.drv' failed with exit code 1
> ------------------------------------------------------------------------------------------------ show-trace ------------------------------------------------------------------------------------------------
> trace: while evaluating the attribute 'DISABLE_GIT_LFS_CHECK' of the derivation 'rust_veloren-common-0.8.0'
> ```

Can you try with the latest commit on branch `yusdacra/override-git-lfs`, and adding `disableGitLfsCheck = true;` to last `import "${velorenSrc}/nix" { ... }`? That should disable the git-lfs check. I want to see if the assets are *actually* in place since the git-lfs check fails. If the game builds and can't load one of the assets it'll panic and abort.

**Comment by lboklin** [comment]
When I tried to build my system flake I got this:
```
error: --- Error --- nix-daemon
builder for '/nix/store/dcq4i2vxf95p745k1g8rr8j14x6zn5k8-iced-f464316.drv' failed with exit code 1; last 5 log lines:
exporting https://github.com/hecrj/iced (rev f46431600cb61d4e83e0ded1ca79525478436be3) into /nix/store/qn43ka6287ih8932kc252wrap4ngmiw1-iced-f464316
Initialized empty Git repository in /nix/store/qn43ka6287ih8932kc252wrap4ngmiw1-iced-f464316/.git/
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing
Unable to checkout f46431600cb61d4e83e0ded1ca79525478436be3 from https://github.com/hecrj/iced.
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/2phv70v90z0ja1zs2mn02ipaq4x6civk-rust_iced_core-0.2.1.drv' failed to build
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/cqvdfdz6lc6vb9mq8k12mbqx2xlcvmbq-veloren-voxygen_e7eb51ce-2020-12-04-18-28.drv' failed to build
```

I'm currently building it with `nix-build --arg pkgs '(builtins.getFlake "nixpkgs").outputs.legacyPackages.x86_64-linux'`. I'll let you know what comes out of it after it finished compiling. I have no idea how long it'll take.

**Comment by lboklin** [comment]
The assets are indeed not where they should be.

**Comment by yusdacra** [comment]
> The assets are indeed not where they should be.
> 
> Also, the error from my `nixos-rebuild build` was a fluke. At least after building it once with `nix-build`.

Hmm, then that means the git-lfs commands don't do anything? I'm quite confused here. Perhaps check if there are anything under the `assets` directory before running each `git` command in `postFetch` hook? Also what happens if you make `deepClone` `true`?

**Comment by lboklin** [comment]
It's very strange. I appended `postFetch` with `[ -f assets/voxygen/audio/ambient/wind.ogg ] || exit 1` just to make sure.

Then I did `import (pkgs.lib.traceVal "${velorenSrc}/nix") # ...` so that I can manually check the contents, which does indeed have assets (`wind.ogg` at least). Still the build panics with:
```
Panic Payload: "Failed loading essential asset: voxygen.texture.noise (error=ParseError(Unsupported(UnsupportedError { format: Unknown, kind: Format(Unknown) })))"
PanicInfo: panicked at 'Failed loading essential asset: voxygen.texture.noise (error=ParseError(Unsupported(UnsupportedError { format: Unknown, kind: Format(Unknown) })))', /source/src/assets/mod.rs:220:1
3
Game version: e7eb51ce [2020-12-04]

Backtrace:
0: veloren_voxygen::main::{{closure}}
1: std::panicking::rust_panic_with_hook
2: std::panicking::begin_panic_handler::{{closure}}
3: std::sys_common::backtrace::__rust_end_short_backtrace
4: rust_begin_unwind
5: std::panicking::begin_panic_fmt
6: veloren_common::assets::Asset::load_expect::{{closure}}
7: veloren_voxygen::render::renderer::Renderer::new
8: veloren_voxygen::window::Window::new
9: veloren_voxygen::main
10: std::sys_common::backtrace::__rust_begin_short_backtrace
11: std::rt::lang_start::{{closure}}
12: std::rt::lang_start_internal
13: main
14: __libc_start_main
15: _start
```

The contents of `/nix/store/...-veloren-e7eb51c/assets/voxygen/texture/` (the fetched source) are these two files: 
* noise.png
* waves.png

I'm trying with `deepClone = true;`. After that I'll insert recursive `ls` or something for the assets dir before each git command as you suggest.

**Comment by lboklin** [comment]
Wait, where does the game look for the assets?

**Comment by yusdacra** [comment]
> Wait, where does the game look for the assets?

If you check the `default.nix` file, you'll see a `veloren-assets` variable, which is basically created like this:
```nix
  veloren-assets = pkgs.runCommand "makeAssetsDir" { } ''
    mkdir $out
    ln -sf ${../assets} $out/assets
  '';
```

Then I wrap the binary and set `VELOREN_ASSETS` to `veloren-assets`, so that's where the game looks for the `assets` directory.

**Comment by lboklin** [comment]
Updated my comment. I don't get the problem really.

**Comment by yusdacra** [comment]
> Updated my comment. I don't get the problem really.

Those errors basically mean that git-lfs doesn't work properly. I'm at a loss here too.

I will add a "override version" option so that we can also skip the version checks and directly use `fetchFromGitLab` and see if it works.

**Comment by lboklin** [comment]
Ohh..
```
$ file /nix/store/xwdgn945fjikr5d8hicz1wpn8l3l8w1h-makeAssetsDir/assets/voxygen/audio/ambient/wind.ogg
/nix/store/xwdgn945fjikr5d8hicz1wpn8l3l8w1h-makeAssetsDir/assets/voxygen/audio/ambient/wind.ogg: ASCII text
```

**Comment by yusdacra** [comment]
Ok, so I added a way to override the version. Try the latest commit of the same branch. Now instead of using `fetchgit`, try using `fetchFromGitLab`, without any `postFetch` hooks or whatever. Just make sure to pass the `disableGitLfsCheck = true;` and `overrideVersion = <revision of commit used to fetch source>` while `import`ing.

**Comment by lboklin** [comment]
I seem to be stuck on
```
trying https://gitlab.com/api/v4/projects/veloren%2Fveloren/repository/archive.tar.gz?sha=96d68d9e542735c2596b4fa7e0ef600a7359c839
```

There's no reported progress, but maybe it is progressing and it just takes a _reeeaally_ long time. My network activity is mostly idle too, so I don't know what it's doing. I cancelled two or three times but I'll leave it for an hour or two this time.

**Comment by lboklin** [comment]
It runs!

The window isn't actually displaying anything (it's just a frozen image of my screen), but no other bad things are happening.

**Comment by lboklin** [comment]
The server does not run, however:
```
$ RUST_BACKTRACE=1 ./result/bin/veloren-server-cli                                                                                                                                      home  ✭ ✈ ✱
thread 'main' panicked at 'failed to retrieve git_datetime!', src/util/mod.rs:13:75
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::option::expect_failed
3: std::sync::once::Once::call_once::{{closure}}
4: std::sync::once::Once::call_inner
5: std::sync::once::Once::call_once::{{closure}}
6: std::sync::once::Once::call_inner
7: std::sync::once::Once::call_once::{{closure}}
8: std::sync::once::Once::call_inner
9: std::sync::once::Once::call_once::{{closure}}
10: std::sync::once::Once::call_inner
11: <veloren_common::util::DISPLAY_VERSION_LONG as core::ops::deref::Deref>::deref
12: veloren_server_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by yusdacra** [comment]
> The server does not run, however:
> 
> ```
> $ RUST_BACKTRACE=1 ./result/bin/veloren-server-cli                                                                                                                                      home  ✭ ✈ ✱
> thread 'main' panicked at 'failed to retrieve git_datetime!', src/util/mod.rs:13:75
> stack backtrace:
> 0: rust_begin_unwind
> 1: core::panicking::panic_fmt
> 2: core::option::expect_failed
> 3: std::sync::once::Once::call_once::{{closure}}
> 4: std::sync::once::Once::call_inner
> 5: std::sync::once::Once::call_once::{{closure}}
> 6: std::sync::once::Once::call_inner
> 7: std::sync::once::Once::call_once::{{closure}}
> 8: std::sync::once::Once::call_inner
> 9: std::sync::once::Once::call_once::{{closure}}
> 10: std::sync::once::Once::call_inner
> 11: <veloren_common::util::DISPLAY_VERSION_LONG as core::ops::deref::Deref>::deref
> 12: veloren_server_cli::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

Both freeze and crash is caused since the game expects a proper formatted `gitHash`, which we aren't giving here. So I want to fix the git-lfs issue, but in the mean time I will upstream an `assets` argument, which will point to assets of the game. This will fix the issue, but you'll need to use `fetchgit` (for version detection) *and* `fetchFromGitLab` (to get the assets), which is a dirty workaround.

Thanks for your time :)

**Comment by lboklin** [comment]
I too would really like to get `fetchgit` to work with `git-lfs`. Anything else would be too embarrassing for a PR, hehe.

Thanks for being accommodating on the other end :)

**Comment by yusdacra** [comment]
@lboklin can you try the branch `yusdacra/nix-assets`? You need to pass in the assets using the `assets` argument as I explained above *but* use the `fetchgit` source for `import`ing `default.nix`.

**Comment by lboklin** [comment]
It works perfectly.

This is cleaned up from what worked for me just now. I'll update in a bit with the real hash when I've confirmed it works verbatim.
```nix
{ pkgs, ... }:

let
  rev = "a5c285a13d8a0d174a2bb397dededdc94b40f544";

  velorenAssets = pkgs.fetchFromGitLab {
    owner = "veloren";
    repo = "veloren";
    inherit rev;
    sha256 = pkgs.lib.fakeHash;
  };

  velorenSrc = pkgs.fetchgit {
    url = "https://gitlab.com/veloren/veloren";
    branchName = "yusdacra/nix-assets";
    inherit rev;
    leaveDotGit = true;
    sha256 = "sha256-moPhJ1+y5fuWtg/Osk+wO6gIErxEfbzRzFox0CTYW1Q=";
  };

  system = "x86_64-linux";

in
  import "${velorenSrc}/nix" {
    inherit system;
    assets = "${velorenAssets}/assets";
  }
```

**Comment by yusdacra** [comment]
> It works perfectly.
> 
> This is cleaned up from what worked for me just now. I'll update in a bit with the real hash when I've confirmed it works verbatim.
> 
> ```nix
> { pkgs, ... }:
> 
> let
>   rev = "a5c285a13d8a0d174a2bb397dededdc94b40f544";
> 
>   velorenAssets = pkgs.fetchFromGitLab {
>     owner = "veloren";
>     repo = "veloren";
>     inherit rev;
>     sha256 = "sha256-n1EqxxYDuDM9Cz10csf2EJoeOKaWCwXvkL7LX5IP+Yo=";
>   };
> 
>   velorenSrc = pkgs.fetchgit {
>     url = "https://gitlab.com/veloren/veloren";
>     branchName = "yusdacra/nix-assets";
>     inherit rev;
>     leaveDotGit = true;
>     sha256 = "sha256-moPhJ1+y5fuWtg/Osk+wO6gIErxEfbzRzFox0CTYW1Q=";
>   };
> 
>   system = "x86_64-linux";
> 
> in
>   import "${velorenSrc}/nix" {
>     inherit system;
>     assets = "${velorenAssets}/assets";
>   }
> ```
> 
> Edit: Hashed and confirmed.

That's nice! I'll try and see if I can get `git-lfs` to work properly. I decided to not merge the workaround branch, but I'll rebase it daily so don't worry :P

**Comment by lboklin** [comment]
Alright; thanks to user jonringer, who [figured out](https://discourse.nixos.org/t/how-to-fetch-lfs-enabled-repo-with-fetchfromgithub/5890/13) that the issue was with `git-lfs` needing some configuring, I have managed to write a working `fetchgitLFS` helper. This expression will create the derivation attributes `veloren-voxygen` and `veloren-server-cli` from latest master: 

```nix
{ pkgs, ... }:

let
  fetchgitLFS = args:
    let
      gitconfig = pkgs.writeText "gitconfig" ''
        [filter "lfs"]
          clean = "git-lfs clean -- %f"
          process = "git-lfs filter-process"
          required = true
          smudge = "git-lfs smudge -- %f"
      '';

    in
      (pkgs.fetchgit (args // { leaveDotGit = true; })).overrideAttrs
        (oldAttrs: {
          fetcher = pkgs.writeText "git-lfs.sh" ''
            #! /usr/bin/env bash

            export HOME=$TMPDIR
            mkdir -p $HOME/.config/git/
            cp ${gitconfig} $HOME/.config/git/config

            bash ${oldAttrs.fetcher} $@
          '';

          nativeBuildInputs =
            oldAttrs.nativeBuildInputs or [] ++ [
              pkgs.git-lfs
            ];
        });

  velorenSrc = fetchgitLFS {
    url = "https://gitlab.com/veloren/veloren";
    rev = "20b45a12023739cb9c303f90092868ed526bb931";
    sha256 = "sha256-ncubJuUpGNQGUV0jrQGg0GlLbZGAiIVpvqQ3hUl2zHw=";
  };

in
  import "${velorenSrc}/nix" { system = "x86_64-linux"; }
```

**Comment by lboklin** [comment]
Now that it everything appears to be working well I suppose as the next step the repo-committed nix files should be locally included for an upstream PR into nixpkgs, as I seem to recall that nixpkgs doesn't accept reliance on remote nix expressions.

**Comment by lboklin** [comment]
The `niv` stuff has to be ported. `crate2nix` has to be in the same `nixpkgs` and all extensions to `nixpkgs` in `nixpkgsMoz` needs to be upstreamed or otherwise included in the PR.

**Comment by yusdacra** [comment]
Still need to make the game work on Wayland as that is currently broken. It fallbacks to X fine but I'd rather have it work properly.

**Comment by lboklin** [comment]
* [x] crate2nix was recently upstreamed: https://github.com/NixOS/nixpkgs/pull/104106 so that's all good
* [x] niv stuff has been eliminated with (no longer using `nix/sources.nix`)
* [x] removed nixGL stuff
* [ ] need to figure out what to do with `nix/Cargo.nix` since it refers to repo-local crates. I can import it from the repo but I don't think that's clean nor accepted.

**Comment by jonringer** [comment]
I have a PR to add support for LFS here: https://github.com/NixOS/nixpkgs/pull/105998

**Comment by lboklin** [comment]
I have a WIP branch for adding Veloren to nixpkgs here: https://github.com/lboklin/nixpkgs/tree/veloren

**Comment by lboklin** [comment]
Orthogonal to this issue, but maybe of interest to some is that I've opened a PR for a flake, which at least makes life easier for us flakers.

**Comment by jansol** [comment]
Any news on this? Looks like the fetchgit LFS support PR got merged as well.

**Comment by jonringer** [comment]
it's already packaged within the upstream repo. However, I'm fine with including it in nixpkgs. We just probably wont have it built in hydra as it has sever GBs worth of assests.

**Comment by jansol** [comment]
Would it be feasible to split the assets off into their own package that isn't built on hydra while still building the binaries?

**Comment by RPGHank** [comment]
Maybe Airshipper could be shipped instead?

**Comment by marius851000** [comment]
actually, there is only 174 MiB of assets in the release 0.11

**Comment by yusdacra** [comment]
> Maybe Airshipper could be packaged instead?

Airshipper package is merged into nixpkgs now.

**Comment by mkroehnert** [comment]
@yusdacra thank you very much for providing Airshipper with PR #137315.

It worked yesterday but stopped working today with the error message when trying to update to the latest binaries

```
[WARN] Unable to open libEGL.so: Library(DlOpen { desc: "libEGL.so: cannot open shared object file: No such file or directory" })
[INFO] Private capabilities: PrivateCapabilities { flip_y_requires_shift: true, imageless_framebuffers: true, image_view_usage: true, timeline_semaphores: true, texture_d24: true, texture_d24_s8: true, non_coherent_map_mask: 63 }
[INFO] Unzipping to "/home/<username>/.local/share/airshipper/profiles/default"
[ERROR] Error while performing filesystem operations. => Read-only file system (os error 30)
[ERROR] Installation failed with: Error while performing filesystem operations.
```

The directory itself is not read-only, but some links inside point to nix-store which is read only

```
drwxr-xr-x 10 <username> users      4096  3. Okt 08:38 assets
drwxr-xr-x  4 <username> users      4096  2. Okt 19:41 userdata
-rw-r--r--  1 <username> users 196031486  3. Okt 08:38 veloren
lrwxrwxrwx  1 <username> users        76  2. Okt 19:30 veloren-server-cli -> /nix/store/y6qvkg3fx2ljzbsp5p2bnnxl9n68ah8s-veloren-patch/veloren-server-cli
lrwxrwxrwx  1 <username> users        73  2. Okt 19:30 veloren-voxygen -> /nix/store/y6qvkg3fx2ljzbsp5p2bnnxl9n68ah8s-veloren-patch/veloren-voxygen
```

Please let me know, if this should be created as a separate issue.

**Comment by yusdacra** [comment]
It seems to be working fine for me currently. Maybe try deleting your profile? I know there is a bug that messes up the profile (if the symlinks are broken) but that's probably not related.

**Comment by mkroehnert** [comment]
@yusdacra thanks for the fast reply and the hint.
For anyone also having this issue, I removed the `veloren-server-cli` and `veloren-voxygen`, started `airshipper` again and the download/install worked.

**Comment by peterhoeg** [comment]
As mentioned earlier, veloren is both in nixpkgs and working well.

**Comment by rnhmjoj** [comment]
I'm not too keen on using a launcher that fetches random binaries from the internet.
The flake provided by upstream is also broken (it has been for a [while](https://gitlab.com/veloren/veloren/-/issues/1418)).

I would appreciate a proper package in Nixpkgs, maybe with the assets split out if that's a concern.

**Comment by rnhmjoj** [comment]
If you're still interested I have made a [PR](https://github.com/NixOS/nixpkgs/pull/267239) to add the full veloren package.
Reviews are welcome.
