### ISSUE TITLE
Replace gummi boot with systemd-boot

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#9523]
http://www.freedesktop.org/wiki/Software/systemd/systemd-boot/

**Comment by ryantm** [comment]
The arch wiki says that systemd-boot is the new name for gummiboot https://wiki.archlinux.org/index.php/Systemd-boot

**Comment by domenkozar** [comment]
yes, but once we have systemd-220 we can use their fork/version

**Comment by domenkozar** [comment]
We now have systemd-229, so this would could go forward. But not for `16.03`

**Comment by viric** [comment]
The current gummiboot hangs in my system if I press any key (usb keyboard). I wonder if a newer version would fix that.

**Comment by domenkozar** [comment]
See https://github.com/triton/triton/commit/397001ca5b1ccb0db2636138f1c64e736054ef6b, I think it should be pretty straightforward replacing it.

**Comment by wkennington** [comment]
Note that change doesnt fix boot.gummiboot, just the iso

**Comment by domenkozar** [comment]
done in https://github.com/NixOS/nixpkgs/commit/f222689aba0b0f5c7c06c77406d33538d9f40cb9
