### ISSUE TITLE
Tracking GNOME 3.38 update in September

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#95248]
The GNOME 3.38 release is [planned](https://wiki.gnome.org/ThreePointThirtyseven) for September 16, 2020.

Things we need to consider:

- gjs packaging will need extra patches for SpiderMonkey: https://mail.gnome.org/archives/distributor-list/2020-August/msg00000.html

cc @NixOS/gnome

**Comment by hedning** [comment]
Haven't got a head start this time around as I've been busy with work.

**Comment by hedning** [comment]
Did the bare minimum necessary to get gnome-shell running: https://github.com/hedning/nixpkgs/tree/gnome-3.38

Mostly useful for the spidermonkey bump as it was somewhat time consuming (required a bunch of new dependencies).

**Comment by worldofpeace** [comment]
I've updated libhandy in https://github.com/NixOS/nixpkgs/pull/92204. We should be sure to move that change into the forthcoming PR.

**Comment by worldofpeace** [comment]
>  switched from yelp to gnome-tour

I packaged gnome-tour already, so it will just have to be updated :+1:

**Comment by pbogdan** [comment]
> > switched from yelp to gnome-tour
> 
> I packaged gnome-tour already, so it will just have to be updated

Looking at my changes (it's been a while) it will need `librsvg` to render the pictures for the walk-through.

Also just a heads up I had to commit some sins (https://github.com/pbogdan/nixpkgs/commit/2cac0a1ab4f5709b2d403c3c0e24c9e2c1ceeaa7 https://github.com/pbogdan/nixpkgs/commit/be86a1a63a8029a39eaa4d47684a98398b84ddb9) to actually get a working GNOME session at the time. Likely just my own lack of knowledge / ignorance but `gdm` and `gnome-session` updates may need a careful review (I haven't actually updated my branch to the latest beta sources).

**Comment by hedning** [comment]
Hmm, not sure what's up with GDM, though 3.38 is released now, which fixes an issue (https://gitlab.gnome.org/GNOME/gdm/-/issues/555), that could be related. Else it might be worth checking setting `initial-vt=1` fixes the problem.

There's a typo (missing `@`) in a gnome-session patch, so that might be causing some issues (potentially for both GDM and the session):
https://github.com/NixOS/nixpkgs/blob/b46981417ed816104b4633426924ecf39078c83a/pkgs/desktops/gnome-3/core/gnome-session/fix-paths.patch#L39

**Comment by pbogdan** [comment]
Grr... Thanks for catching this, will try and fix this up tomorrow and re-test.

**Comment by doronbehar** [comment]
https://www.gnome.org/news/2020/09/gnome-3-38-released/

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/pull/98216

**Comment by pbogdan** [comment]
This reminds me:

> Grr... Thanks for catching this, will try and fix this up tomorrow and re-test.

Fixing up the patch didn't seem to help nor did changing `initial-vt`, and didn't seem to help with `gnome-session` either.
It could be all moot though as I haven't been keeping up with upstream updates for a good while.

**Comment by pbogdan** [comment]
Managed to figure out how to get rid my gdm / gnome-session hacks so thankfully it turns out they aren't necessary.

Just another few notes after updating to 3.38:

- `nautilus` and `gnome-music` both need `tracker{,-miners}-3`, this includes both libraries and the runtime services
  - `gnome-music` also needs tracker-3 grilo plugin, and `grilo-plugins` can't build tracker-2 and tracker-3 plugins at the same time
  - not everything upgraded to tracker-3 so this may require both versions (including NixOS modules) + another build of `grilo-plugins` (though I can't say I looked into this too deeply)

**Comment by jtojnar** [comment]
I would default to Tracker 3 everywhere and keep tracker 2 for stuff that did not update as suggested in https://discourse.gnome.org/t/gnome-3-38-uses-tracker-3-by-default-but-one-core-app-still-uses-tracker-2/4191

**Comment by pbogdan** [comment]
Sorry for the scattered notes but one more which I didn't mention

- gnome-settings-daemon
  - needs to be patched to find `gnome-session-ctl` from `gnome-session`, ATM it expects it under its own libexecdir

**Comment by worldofpeace** [comment]
> Sorry for the scattered notes but one more which I didn't mention
> 
>     * gnome-settings-daemon (perhaps others)
>       
>       * needs to be patched to find `gnome-session-ctl` from `gnome-session`, ATM it expects it under its own libexecdir

We can PR to add something that's already in `gnome-control-center`
```
core/gnome-control-center/default.nix
154:    "-Dgnome_session_libexecdir=${gnome-session}/libexec"
```

**Comment by worldofpeace** [comment]
Heh, I guess that only existed in 3.34 https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/3.34.0/meson_options.txt#L3, so we need to drop that flag in `gnome-control-center`. Though basically the same code could be used.

**Comment by worldofpeace** [comment]
PR'd https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/202

**Comment by worldofpeace** [comment]
I'm going to move a lot of your comments into the gnome 3.38 project @pbogdan

**Comment by pbogdan** [comment]
Speaking of patches `gdm` will probably need something similar to https://github.com/NixOS/nixpkgs/blob/684d691c6e9d49d3aab96f4053d011c225aa75bf/pkgs/desktops/gnome-3/core/rygel/add-option-for-installation-sysconfdir.patch after conversion to meson. I have an ugly hack for now but ideally it needs separation between sysconfdirs configured for the build and installation.

**Comment by jtojnar** [comment]
GNOME 3.38 has been merged to master so now is the time to update extensions.

**Comment by dotlambda** [comment]
Can this be closed?
