### ISSUE TITLE
PulseAudio fails to start on nixos-unstable with linuxPackages_latest.

### ISSUE THREAD

**Issue by jakobrs** [NixOS/nixpkgs#95243]
**Describe the bug**
PulseAudio fails to start on the unstable channel on linuxPackages_latest. Playing audio directly via ALSA works, however. This seems to have occurred between commits 2111240b9f7e5704045763fbdc66534609a62a65 and 56de5bed5f1e8af8db7893fb3b456184bf1b63a2. #86168 seems relevant, but it was backported.

**To Reproduce**
1. Rebuild on nixos-unstable with linuxPackages_latest
2. Reboot
3. `paplay ~/path/to/file.wav`

**Expected behavior**
Audio

**Screenshots**
This shows up in the systemd journal:
```
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device HDMI3, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device HDMI2, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device HDMI1, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Headset, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Headphones2, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Mic, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Speaker, assuming stereo duplex.
Aug 12 08:45:34 girafarig pulseaudio[969]: W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Headphones1, assuming stereo duplex.
```

**Additional context**
- Realtek ALC3204

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixos/pulseaudio
```

**Comment by doronbehar** [comment]
https://forums.opensuse.org/showthread.php/539285-No-sound-aftert-latest-snapshot?s=e1b596855369604c62f5433031a35245&p=2928594#post2928594 suggests there might be some alsa config you might be able to apply?

**Comment by jonringer** [comment]
can confirm pulseaudio issues as well. 

Generally I need to kill all pulseaudio process (There's usually 3 of them `pulseaudio --start`), and then do `pulseaudio --start` to get it to work normally.

**Comment by jonringer** [comment]
could be related https://github.com/NixOS/nixpkgs/pull/95374

**Comment by jtojnar** [comment]
Possibly we might need the pulseaudio end of https://mail.gnome.org/archives/distributor-list/2020-September/msg00001.html

**Comment by jakobrs** [comment]
The following makes audio work:

```nix
{
  hardware.pulseaudio.package = pkgs.pulseaudioFull.override {
    alsaLib = pkgs.alsaLib.override {
      alsa-ucm-conf = pkgs.alsa-ucm-conf.overrideAttrs (old: rec {
        name = "alsa-ucm-conf-${version}";
        version = "4626beb75442e7de81ccb71a8bf34c85976b9dc1";

        src = pkgs.fetchFromGitHub {
          owner = "alsa-project";
          repo = "alsa-ucm-conf";
          rev = "4626beb75442e7de81ccb71a8bf34c85976b9dc1";
          hash = "sha256:11gpfnilrbhpzh26r23jxvp7fsk361pxk5l7cbl3xk4pimpnnsbb";
        };
      });
    };
  };
}
```

It seems an update to the ucm configuration used by the alsaLib package caused the issue (presumably #83155). It's fixed on alsa-ucm-conf master. However, this only makes pulseaudio work (not other applications which use alsa), and rebuilding every application takes time, so as a workaround I'm using `boot.kernelParams = [ "snd_hda_intel.dmic_detect=0" ]`.

**Comment by jakobrs** [comment]
See #101302

**Comment by roastiek** [comment]
There are `ALSA_CONFIG_UCM`, `ALSA_CONFIG_UCM2` and `ALSA_CONFIG_TPLG` env variables. Setting them should allow you use custom ucm and topology withtou rebuilding.
