### ISSUE TITLE
20.09 Blocker Project

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#95269]
Created another project to track issues and PRs which are critical to the 20.09 Release. https://github.com/orgs/NixOS/projects/4

"There's already a 20.09 milestone, why another project?"
The milestone has many "nice-to-haves" which have been carried over from previous releases, and does not represent a true blocker for a given release. I'll try to address the items in the 20.09 milestone, but I won't consider them as blockers, and able to be carried over to the 21.03 release if time doesn't permit them to be resolved.

This issue is also meant to be used as a discussion thread for whether or not certain items to be considered blockers

EDIT: Blocker project was moved to https://github.com/orgs/NixOS/projects/4

**Comment by doronbehar** [comment]
Super small change that would be a shame not to have in 20.09: https://github.com/NixOS/nixpkgs/pull/95254 . I'm fairly familiar with the derivation and I wrote myself most of it, though that small thing has slipped me.

**Comment by worldofpeace** [comment]
@jonringer Yep, I think I like having a project.

**Comment by jonringer** [comment]
@worldofpeace I know with the 20.03 release, we had the "go, no-go" meetings, but I thought this would be more transparent and easier to track :)

I was going to message you, but I know you're pretty busy.

**Comment by mt-caret** [comment]
Considering that the fix to https://github.com/NixOS/nixpkgs/issues/93580, while probably minor, is potentially a breaking change and the issue itself has security implications, I feel it should be a blocker for 20.09

**Comment by numinit** [comment]
Fair enough, was mainly referring to the number of issues submitted about a single problem.

In a similar vein, how's rpi4 support coming? If we want it for 20.09, we might want to get #91295 integrated.

**Comment by sephii** [comment]
I'd love to see https://github.com/NixOS/nixpkgs/issues/92992 fixed (which should be fixed by https://github.com/NixOS/nixpkgs/pull/86686). Also the docs for caddy v1 are [buried in the documentation page](https://caddyserver.com/docs/) and they're hardly usable at all. I'm currently working on the PR at the moment, since the original author doesn't seem reachable, and I hope I'll be able to submit it over the weekend.

**Comment by kirelagin** [comment]
#98349 needs to be included.

**Comment by worldofpeace** [comment]
I've moved the thing org wide since there's other repos with blocking stuff https://github.com/orgs/NixOS/projects/4

**Comment by rissson** [comment]
In my mind #101099 is a blocker. Sorry if that was the wrong issue to post this.

**Comment by jonringer** [comment]
This has served it's purpose. Remaining items should be closed today.
