### ISSUE TITLE
grex

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#95315]
**Project description**
 A command-line tool and library for generating regular expressions from user-provided test cases 

**Metadata**

* homepage URL: https://github.com/pemistahl/grex
* source URL: https://github.com/pemistahl/grex
* license: `apl2`
* platforms: `unix`

**Comment by AndersonTorres** [comment]
Closed because the package now exists.

**Comment by davidak** [comment]
Was merged in https://github.com/NixOS/nixpkgs/pull/100173.
