### ISSUE TITLE
gjs failed to build

### ISSUE THREAD

**Issue by indocomsoft** [NixOS/nixpkgs#95433]
Specifically, I'm getting exactly as this failed hydra job: https://hydra.nixos.org/build/125198506

**Describe the bug**
gjs failed to build with seemingly spurious test failure

**To Reproduce**
installing (+ building) gjs nix package should succeed

**Expected behavior**
The job should pass

**Screenshots**
nil

**Additional context**
https://hydra.nixos.org/build/125198506

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.14, NixOS, 20.09.git.d4bbe9a3ed8 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.03.1950.48723f48ab9"`
 - nixpkgs: `/home/julius/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: 
```

**Comment by doronbehar** [comment]
This also clocks the channel to progress as this failure causes hydra tests to fail, ref #95440 . cc @NixOS/gnome .

**Comment by jtojnar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/95382

**Comment by benley** [comment]
(closing on the assumption that #95382 actually fixes this; please reopen if that's not the case)

**Comment by indocomsoft** [comment]
Using branch `staging-next` and `# nixos-rebuild switch` works wonderfully!

Not too familiar with the processes at this repo: just wondering, from the way I understand, this change will be merged to `master` once `staging-next` is merged to `master`, is that correct?
