### ISSUE TITLE
20.03: Kernelmodule `rtl8192eu` causes kernel panics during boot when using 5.x kernel

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#95448]
**Describe the bug**
When using any of the provided linux kernels that are 5.x, then there will be a Kernel panic on boot when the `rtl8192eu` module gets loaded. No WiFi possible once the system is booted.

When using one of the provided 4.x kernels, the system boots as expected.

**To Reproduce**

Have a WiFi card with an RTL-8192-EU chipset, and configure its usage like this:

```nix
boot.blacklistedKernelModules = [ "rtl8xxxu" ]; # Not sure if this really necessary, but at least on my system it was always loaded
boot.extraModulePackages = with config.boot.kernelPackages; [
  rtl8192eu
];
```

**Expected behavior**
System boots without a Kernelpanic and WiFi works even with 5.x Kernels

**Screenshots**
Not a screenshot, but full Kernelringbuffer of a boot I tried a couple of weeks ago and remembered to capture for a help thread in the discourse.

https://gitlab.com/snippets/1975107#LC1118 (Line on which the panic starts)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Can't currently run this, as I the affected Laptop is physically dislocated, won't have access before monday.

**Comment by xaverdh** [comment]
looks like the version in `nixpkgs` is too old..
cc @troydm

**Comment by mweinelt** [comment]
I did a quick bump of the package to something more recent, can you give that a try?

**Comment by NobbZ** [comment]
Not before monday, but I'll give it a try then.

**Comment by troydm** [comment]
I did PR not long ago which I've checked personally and it's working fine, but it's still open: https://github.com/NixOS/nixpkgs/pull/82451
Haven't tried your PR @mweinelt but will try it out when I'll have

**Comment by NobbZ** [comment]
I am currently rebuilding my system based on @mweinelt PR. I think this will take quite a while. The laptop in question is just a ~10yr old dualcore with 4GiB of RAM and my regular buildHost is currently not available.

**Comment by NobbZ** [comment]
Okay. It seems as if @mweinelt PR works for me.

**Comment by mweinelt** [comment]
> I did PR not long ago which I've checked personally and it's working fine, but it's still open: #82451
> Haven't tried your PR @mweinelt but will try it out when I'll have some time

Sorry, I missed that.

> Okay. It seems as if @mweinelt PR works for me.

Okay, so when @troydm is also happy we can merge #95497.

**Comment by troydm** [comment]
@mweinelt your PR seems okey, could you add bc as build input just as in my PR as it's used during build process, after that you can merge your PR and I'll close mine as it has older hashes
