### ISSUE TITLE
haskellPackages.hocker marked as broken

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#95517]
**Describe the bug**
```
error: Package ‘hocker-1.0.5’ in /path/to/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:127808 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

This currently breaks the `fetchdocker` tooling, which breaks the `nixosTests.hocker-fetchdocker`, which is a problem for https://github.com/NixOS/nixpkgs/issues/72828

We should either try to fix hocker, or migrate fetchdocker to something like skopeo if possible.

cc @maralorn

**Comment by maralorn** [comment]
This is pretty trivial to fix. `1.0.5` is a bit out-dated. But the `1.0.6` release of `hocker` builds without a problem with 
```nix
  hocker = overrideCabal super.hocker (
    old: {
      version = "1.0.6";
      src = pkgs.fetchFromGitHub {
        owner = "awakesecurity";
        repo = "hocker";
        rev = "fee4e37";
        sha256 = "11bsb08ilhl1bcjgx3sllm22y2gr7m5sircnm0ks502lzi9svwjv";
      };
      libraryHaskellDepends = old.libraryHaskellDepends ++ [ self.word8 ];
      broken = false;
    });
```
added to `pkgs/development/haskell-modules/configuration-common.nix`

While in theory we could do this in nixpkgs, it would be a very bad practice. The correct solution here is that `hocker` publishes a `1.0.6` to hackage. That would automatically fix the build in nixpkgs (besides from removing the broken flag.)

Opening in issue over there.

**Comment by flokli** [comment]
hocker has been uploaded to hackage: https://github.com/awakesecurity/hocker/issues/52#issuecomment-674980745

@maralorn Would you mind doing a bump?

**Comment by maralorn** [comment]
@flokli No, that happens automatically via cronjob. But after that happened I can remove the broken flag.

**Comment by maralorn** [comment]
Fixed in haskell-updates. Will hit master friday evening.
