### ISSUE TITLE
python3Packages.qiskit-aer fails if you have too many cores

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#95527]
The test suite expects you to have 64 or less cores. Fails with my 3990X's 128

```
>           self.assertEqual(threads, target)
E           AssertionError: {'experiments': 1, 'shots': 1, 'state_update': 64, 'total': 64} != {'experiments': 1, 'shots': 1, 'state_update': 128, 'total': 128}
E           - {'experiments': 1, 'shots': 1, 'state_update': 64, 'total': 64}
E           ?                                                ^^           ^^
E
E           + {'experiments': 1, 'shots': 1, 'state_update': 128, 'total': 128}
E           ?                                                ^^^           ^^^

```

cc @drewrisinger 

Full gist: https://gist.github.com/jonringer/a86a889f2684ee64bb95732f0b065126

**Comment by drewrisinger** [comment]
@jonringer forgot to comment earlier, drafted it in my head...

I cross-posted this issue to https://github.com/Qiskit/qiskit-aer/issues/892. I wanted to push #95713 for you to build against to know if the error was still in that version vs trying to fix an older version. From a quick glance it probably is, but just curious.

If it's still erroring, I'll just disable the relevant tests, it should be pretty thoroughly tested without those specific ones.

**Comment by jonringer** [comment]
I dropped my `nix.buildCores` to 32 on my server. I was also getting build errors with ninja.

**Comment by drewrisinger** [comment]
I'm closing because the cross-posted issue https://github.com/Qiskit/qiskit-aer/issues/892 was resolved, and I haven't heard any other complaints from @jonringer that this is failing to build when that patch is incorporated. The real test is PR #100007, which has that patch.
See also #102724.
