### ISSUE TITLE
20.09 Timeline

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#95535]
Current timeline for the 20.09 release (subject to change):

 7 Sept  - Branch-off https://github.com/NixOS/nixpkgs/commit/0cebf41b6683bb13ce2b77bcb6ab1334477b5b29
 8 Sept - ZHF #97479
24 Sept  - "Beta" release
26 Oct - End of ZHF period
27 Oct - 20.09 release

### Goals:
 - release in september :smile: 

#### Definitions:
- branch-off:
  - `release-20.09`, `nixpkgs-20.09`, `nixos-20.09` branches will be created along with related infrastructure (hydra, channels, etc).
- Zero Hydra Failures (ZHF):
  - Period in which stabilization is done to ensure everything is "green as possible", and minimize failures being part of the release.
- "Beta" Release:
  - Have release candidates available for people to tests scenarios
- End of ZHF:
  - A script will be ran to mark all failing builds as broken. Broken packages can still be fixed at anytime through backport process.

### Changes from last year
The "Beta" release is delayed a week. There's going to be a lot of work done to get all of the release channels in place and ZHF stabilization. Felt like that could be a task which could be postponed, especially seeing as it would benefit from the extra stabilization during ZHF

Last year, the branch-off date was in the mid-september, but this gives little time for ZHF and quality assurance. I believe having another week for ZHF + "Beta" release will help with the timeline.

### Feature Freeze discussion: #95475

cc @worldofpeace

**Comment by itshaydendev** [comment]
What's ZHF?

**Comment by worldofpeace** [comment]
Okay so, as we were planning to branch and begin ZHF today, this didn't happen. This was an issue because we couldn't get in contact with anyone from @NixOS/infra so we could have jobsets. We have now tentatively pushed our plans to branch and ZHF to 7th Sep. If someone either over the weekend could create the jobsets beforehand (is this even possible) or be available to us (my TZ is EDT and Jon's is PST) on Monday it would be great as it's currently essential to gestation of 20.09.

**Comment by worldofpeace** [comment]
I've created the PR to nixos-org-configurations in advance https://github.com/NixOS/nixos-org-configurations/pull/120

**Comment by vcunat** [comment]
I can create jobset(s) for you, but I can't see a branch yet and I assumed it's waiting for https://github.com/NixOS/nixpkgs/issues/96479#issuecomment-687312654

**Comment by worldofpeace** [comment]
@vcunat Ohh cool. I forgot this. Is it possible you can add yourself to https://github.com/orgs/NixOS/teams/infra (or I guess some admin could do this).

**Comment by worldofpeace** [comment]
Yeah, I believe we're trying to somehow get https://github.com/NixOS/nixpkgs/pull/97146 into the release.

**Comment by worldofpeace** [comment]
Are you available on Freenode?

**Comment by vcunat** [comment]
For reference, I/we don't think my "level of access" makes me suitable for that team.  I suggest to ping me in this topic when there's a branch ready (I should be fast if not asleep).

**Comment by worldofpeace** [comment]
Just figured out what the team is for exactly https://github.com/NixOS/nixos-org-configurations#team

**Comment by FRidh** [comment]
Yes, I think a separate team is needed for maintaining Hydra jobsets.

**Comment by jonringer** [comment]
Just an update, branchoff was delayed til Sept 7th due to some issues with stage1 boot when using luks.

ZHF was delayed until hydra was able to populate a full evaluation. https://hydra.nixos.org/eval/1611945

**Comment by con-f-use** [comment]
Can we have an update on the timeline for 20.09, please?

**Comment by vcunat** [comment]
Some recent updates were on Discourse (topic linked above though not directly): https://discourse.nixos.org/t/go-no-go-meeting-nixos-20-09-nightingale/9169/25

**Comment by jonringer** [comment]
This release took a lot longer than expected; mostly around providing a decent Desktop experience.

For the next release, I started some discussions around improving the release process (minimizing risk, and potential timeline changes)

https://discourse.nixos.org/t/what-should-stable-nixos-prioritize/9646/28
https://discourse.nixos.org/t/fixing-the-staging-staging-next-workflow/9643/2
https://github.com/NixOS/nixpkgs/issues/101789

20.09 isn't "officially" released yet, however, there's a successful stableBranch [hydra evaluation](https://hydra.nixos.org/build/129285763), so it's unofficial at the time of writing.
