### ISSUE TITLE
Channels blocked by `nixos.ova` failing?

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#95577]
This build fails and blocks the nixos-unstable from progressing: https://hydra.nixos.org/build/125499777/nixlog/1/tail It failed previous evaluations as well but I tested this command just a few hours ago on latest master and it didn't fail:

```
nix-build nixos/release.nix -A ova
```

**To Reproduce**

I know I can `curl https://hydra.nixos.org/build/125499777/reproduce | bash` but I'm not sure how to find the latest commit sha with it this fails.

**Expected behavior**

Channels progress.

**Additional context**
I hope the other jobs currently marked as "cancelled" will pass eventually.

**Notify maintainers**

IDK :/.

**Comment by doronbehar** [comment]
Not failing anymore.

**Comment by vcunat** [comment]
753a2371, for reference.
