### ISSUE TITLE
buildRustPackage: honor NIX_BUILD_CORES

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#95595]
**Describe the bug**
Building packages that use `buildRustPackage` always try to use all cores, independent of `NIX_BUILD_CORES` (`--cores` argument to nix-build)

**To Reproduce**
Run `nix-build '<nixpkgs>' --check -A nix-index --cores 1`, and observe that it spawns many rustc processes (depending on the amount of available processors).

**Expected behavior**
The `buildRustPackage` function should pass `$NIX_BUILD_CORES` as `--jobs` argument to cargo.

**Additional notes**
Fixing this will probably cause a rebuild of all rust packages, so should we batch this with other changes to the cargo builder?

**Notify maintainers**
@zowoq @bhipple @Mic92 @Ma27

**Comment by jonringer** [comment]
#95622 has been merged
