### ISSUE TITLE
Terraform hcloud provider moved

### ISSUE THREAD

**Issue by fionera** [NixOS/nixpkgs#95602]
**Describe the bug**
The hcloud terraform provider moved to https://github.com/hetznercloud/terraform-provider-hcloud

**Comment by jlesquembre** [comment]
I think we can close it:
https://github.com/NixOS/nixpkgs/blob/cc496fd42dcd5a902f920045a537cba700b94a9a/pkgs/applications/networking/cluster/terraform-providers/hcloud/default.nix

@fionera let me know if you think we should keep this issue open
