### ISSUE TITLE
Attempting to build Iosevka Sparkle results in monospace (should be proportional)

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#95610]
**Describe the bug**
I am trying to use overrides in the `iosevka` package to build the proportional Iosevka Sparkle variant, but the resulting font is monospaced.

**To Reproduce**
1. The relevant parts of my `configuration.nix`:
```nix
{ config, pkgs, ... }:

let
  unstable = import <nixos-unstable> { config = config.nixpkgs.config; };
in
{
  # -snip-
  nixpkgs.config.packageOverrides = pkgs: {
    iosevka-sparkle = unstable.iosevka.override {
      set = "sparkle";
      privateBuildPlan = {
        family = "Iosevka Sparkle";
        design = [
          "type"
          "v-at-fourfold"
          "v-j-narrow-serifed"
          "no-cv-ss"
          "no-ligation"
        ];
        upright = [
          "v-i-serifed"
          "v-l-serifed"
          "v-f-serifed"
          "v-r-serifed"
        ];
        italic = [
          "v-i-italic"
          "v-l-italic"
          "v-f-tailed"
          "v-r-top-serifed"
        ];
        oblique = [
          "v-i-serifed"
          "v-l-serifed"
          "v-f-serifed"
          "v-r-serifed"
        ];
        quasiProportionalDiversity = 1;
        snapshotFamily = "iosevka-sparkle";
        widths = {
          normal =
            {
              shape = 576;
              menu = 5;
              css = "normal";
            };
          };
        };
      };
      # -snip-
    };

  fonts.fonts = with pkgs; [
    # -snip-
    iosevka-sparkle
  ];
  # -snip-
}
```
2. `nix-rebuild test`
3. Use "Iosevka Sparkle" in e.g. Libreoffice Writer

**Expected behavior**
"Iosevka Sparkle" should be proportional but is monospaced

**Screenshots**

![20200816_19h26m51s_grim](https://user-images.githubusercontent.com/13547699/90341331-a451e200-dff6-11ea-9766-e838d6349c50.png)

**Additional context**
I took the paramters used in `privateBuildPlan` from https://github.com/be5invis/Iosevka/blob/master/build-plans.toml

**Notify maintainers**

@cstrahan 
@jfrankenau 
@ttuegel 
@babariviere 
@rileyinman 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.15, NixOS, 20.03.2791.05195accdc5 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2791.05195accdc5, nixos-unstable-20.09pre237781.32b46dd897a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - iosevka
# a list of nixos modules affected by the problem
module:
```

**Comment by ttuegel** [comment]
The configuration has `design = [ "type" ... ]`, so it should produce a monospaced font. I don't understand what the bug is supposed to be here.

**Comment by lunik1** [comment]
I couldn't find much documentation on how the proportional variants of Iosevka should be built. `design = [ "type" ... ]` comes from [the build-plans.toml in the Iosveka repo](https://github.com/be5invis/Iosevka/blob/master/build-plans.toml), where it is specified only for the proportional variants.

I tried removing `"type"` but the font is still monospaced.

**Comment by ttuegel** [comment]
> I tried removing `"type"` but the font is still monospaced.

It's quite likely that my knowledge is out-of-date. At one point, years ago, `type` did what `sp-fixed` does now. At least, I think that's what the options did and do; as you pointed out, there's not much documentation. :sweat_smile: 

I notice that our private build plan parameter doesn't allow settings like this:

```.toml
[buildPlans.iosevka-sparkle.widths.normal]
shape = 576
menu  = 5
css   = "normal"
```

I have a notion that the problem is here.

**Comment by lunik1** [comment]
Could be, but I was under the impression that that part of the config covered the width of individual glyphs rather than proportionality (i.e. Iosevka vs Iosevka Extended).

Maybe it would be worth having binary packages covering the three pre-built proportional variants?

**Comment by lunik1** [comment]
Sparkle no longer exists and other proportional variants build correctly now.
