### ISSUE TITLE
LibreWolf

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NixOS/nixpkgs#95624]
**Project description**

This project is an independent “fork” of Firefox, with the primary goals of privacy security and user freedom. It is the community run successor to LibreFox.

LibreWolf is designed to minimize data collection and telemetry as much as possible. This is achieved through hundreds of privacy/security/performance settings and patches. Intrusive integrated addons including updater, crashreporter, and pocket are removed too.

**Metadata**

* homepage URL:

https://librewolf-community.gitlab.io/docs/

* source URL:

https://gitlab.com/librewolf-community/browser/linux

* license: mit, bsd, gpl2+ , ...

mpl2

* platforms: unix, linux, darwin, ...

linux

**Comment by veprbl** [comment]
Duplicate of #94918

**Comment by TheEvilSkeleton** [comment]
Yikes, sorry
