### ISSUE TITLE
 Not access  local   directory (such as '/home/user/...')   in the runHook such as  “patchPhase”，“installPhase” ... ?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#95656]
I change the file /home/prehonor/Public/Code/nixpkgs/pkgs/applications/editors/jetbrains/common.nix as below:
  makeWrapper "${yourProgrameLoc}/bin/${loName}.sh" "$out/bin/${execName}" \
  ...
Then ,I got the error
"Builder called die: Cannot wrap '/ah/prehonor/Programmers/WebStorm/bin/webstorm.sh' because it is not an executable file"

**Comment by sternenseemann** [comment]
You can use a local file as an input to a derivation. It will then be converted into a derivation itself and copied to `/nix/store`.

Just make sure `yourProgrameLoc` points to a valid path and `webstorm.sh` can be executed which `makeWrapper` complains about.

You also might not want to edit nix expressions in nixpkgs: It works just fine, but it's annoying to maintain and update what is effectively your own fork of it then: For every upstream update you have to make sure your change is still good. You could use an [overlay](https://nixos.org/nixpkgs/manual/#chap-overlays) and override the `postInstall` hook to achieve what you want for example.

**Comment by prehonor** [comment]
> You can use a local file as an input to a derivation. It will then be converted into a derivation itself and copied to `/nix/store`.
> 
> Just make sure `yourProgrameLoc` points to a valid path and `webstorm.sh` can be executed which `makeWrapper` complains about.
> 
> You also might not want to edit nix expressions in nixpkgs: It works just fine, but it's annoying to maintain and update what is effectively your own fork of it then: For every upstream update you have to make sure your change is still good. You could use an [overlay](https://nixos.org/nixpkgs/manual/#chap-overlays) and override the `postInstall` hook to achieve what you want for example.

I am confirm that “/ah/prehonor/Programmers/WebStorm/bin/webstorm.sh” is an executable file，but it still say the error “t is not an executable file” when I execute “nixos-rebuild switch   -I nixpkgs=/home/prehonor/Public/Code/nixpkgs”。I dont know why it is。 So, I custom mymakewrapper.sh  that is copy of "/home/prehonor/Public/Code/nixpkgs/pkgs/build-support/setup-hooks/make-wapper.sh" with comment on line "assertExecutable "$prog" in the function "wrapProgram" called by "makeWrapper".

**Comment by sternenseemann** [comment]
I suspect your script is maybe not copied into the nix store properly, try:

```nix
''
  makeWrapper "${yourProgrameLoc + "/bin/${loName}.sh"}" ...
''
```

instead. This is just a guess it might be helpful if you could post your full nix expression.

Maybe a bit more readable:

```nix
let
  scriptPath = yourProgrameLoc + "/bin/${loName.sh}";
in ''
  makeWrapper "${scriptPath}" …
''
```

This will make a path *to* your script and convert it into a derivation and only copy itself into the nix store instead of the whole directory `${yourProgrameLoc}`. I suspect however that its not the issue here.

**Comment by jonringer** [comment]
generally, `nixos-rebuild` is unaware of a particular users home. This is usually something that is handled by `home-manager` which uses nixos modules but on a per-user level.

However, you can also use the `runCommand` or another helper (writeScriptBin would probably be best) if don't mind installing the script globally. https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/trivial-builders.nix

```
  environment.systemPackages = let
     my-script = writeScript "my.sh" ''
        # some script to run
     '';
  in [ my-script firefox wget curl ];
```

after doing a `nixos-rebuild`, you should be able to call `my.sh`, as it will be on your PATH

**Comment by prehonor** [comment]
> generally, `nixos-rebuild` is unaware of a particular users home. This is usually something that is handled by `home-manager` which uses nixos modules but on a per-user level.
> 
> However, you can also use the `runCommand` or another helper (writeScriptBin would probably be best) if don't mind installing the script globally. https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/trivial-builders.nix
> 
> ```
>   environment.systemPackages = let
>      my-script = writeScriptBin "my.sh" ''
>         # some script to run
>      '';
>   in [ my-script firefox wget curl ];
> ```
> 
> after doing a `nixos-rebuild`, you should be able to call `my.sh`, as it will be on your PATH

First of all ，Thank you very much。
But I wonder that how to tell nixos-rebuild  “user home”。

> I suspect your script is maybe not copied into the nix store properly, try:
> 
> ```nix
> ''
>   makeWrapper "${yourProgrameLoc + "/bin/${loName}.sh"}" ...
> ''
> ```
> 
> instead. This is just a guess it might be helpful if you could post your full nix expression.
> 
> Maybe a bit more readable:
> 
> ```nix
> let
>   scriptPath = yourProgrameLoc + "/bin/${loName.sh}";
> in ''
>   makeWrapper "${scriptPath}" …
> ''
> ```
> 
> This will make a path _to_ your script and convert it into a derivation and only copy itself into the nix store instead of the whole directory `${yourProgrameLoc}`. I suspect however that its not the issue here.

Thank you very much。
But it doesn‘t work. You can scan the script from "https://prehonor.coding.net/p/nixpkgs/d/nixpkgs/git/tree/master/pkgs/applications/editors/jetbrains/comn.nix"

**Comment by prehonor** [comment]
> generally, `nixos-rebuild` is unaware of a particular users home. This is usually something that is handled by `home-manager` which uses nixos modules but on a per-user level.
> 
> However, you can also use the `runCommand` or another helper (writeScriptBin would probably be best) if don't mind installing the script globally. https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/trivial-builders.nix
> 
> ```
>   environment.systemPackages = let
>      my-script = writeScriptBin "my.sh" ''
>         # some script to run
>      '';
>   in [ my-script firefox wget curl ];
> ```
> 
> after doing a `nixos-rebuild`, you should be able to call `my.sh`, as it will be on your PATH

Thank you very mush.
I wonder that  how to tell nixos-rebuild "use home" by hacking the some functions in the scripts of the nixpkgs.

**Comment by jonringer** [comment]
You would have to use something like `$HOME`, which wont get evaluated until runtime.

**Comment by prehonor** [comment]
> You would have to use something like `$HOME`, which wont get evaluated until runtime.

The value of "$HOME" is "/homeless-shelter" ,
![image](https://user-images.githubusercontent.com/10784632/90864084-a3d49500-e3c2-11ea-84f1-b45831677146.png)

**Comment by jonringer** [comment]
at build time, yes it is.

instead of trying to make nix aware of your script, why don you make your script aware of nix?

```
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash wget curl

# the rest of t he script
```
you can also look at https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/nix-diff.sh

**Comment by jonringer** [comment]
if you prefer video, I also did a recording about this as well https://youtu.be/sO57VV4Ho5s?t=378

**Comment by prehonor** [comment]
> not sure if it's super well documented anywhere, but perhaps you should look at nix-pills

Do you know anythings about the  nix.sandboxPaths  from "https://nixos.org/nixos/manual/options.html#opt-nix.sandboxPaths" ?

**Comment by jonringer** [comment]
> Do you know anythings about the nix.sandboxPaths from "https://nixos.org/nixos/manual/options.html#opt-nix.sandboxPaths" as well as nix.sandboxPaths ?

That might work, but it could hinder reproducibility. I think you should be asking, "why do i need a home directory when building this package".

Generally we just do something like `HOME=$TMPDIR` if it's just for temp files. If it's trying to install files in HOME, then that's a different issue.
