### ISSUE TITLE
Packaging request: pythonPackages.rdflib-jsonld

### ISSUE THREAD

**Issue by koslambrou** [NixOS/nixpkgs#95707]
**Project description**
This is an implementation of JSON-LD for RDFLib.

**Metadata**

* homepage URL: https://pypi.org/project/rdflib-jsonld/
* source URL: https://github.com/RDFLib/rdflib-jsonld
* license: bsd
* platforms: linux

**Comment by koslambrou** [comment]
Awaiting PR acceptance #95711

**Comment by jonringer** [comment]
added
