### ISSUE TITLE
nixos: manage lid by default?

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9571]
Currently, `services.xserver.displayManager.desktopManagerHandlesLidAndPower` is set to true by default.
This creates a problem for users without desktop environments activated, since lid management simply doesn’t work (and they have to be lucky to find this option).

I propose renaming this option to `displayManager.handleLidAndPower` and set it to `true` by default. Devs creating a new desktop environment can set it `false` in their config, so that it still automatically works when `e.g.` GNOME is activated. It then Just Works in all cases.

**Comment by lethalman** [comment]
To make things more confusing, GNOME doesn't manage the lid, we set it to false :P

**Comment by edolstra** [comment]
I don't think there is a need to change the name of the option, but changing the default to `false` seems fine (provided we ensure that KDE etc. set it to true).

**Comment by Profpatsch** [comment]
Does it make sense to set it to `true` for every desktop manager except GNOME? That’s the only place where it is changed `ack` tells me.

**Comment by lethalman** [comment]
:+1: for setting it to `false` by default

**Comment by vcunat** [comment]
I think we should always specify it in desktops, whether it is the one option or the other. That way we will know the correct setting has been decided for that DE.

**Comment by Profpatsch** [comment]
https://github.com/NixOS/nixpkgs/pull/9590
