### ISSUE TITLE
wpa_supplicant: service won't start if config file is a link to the store

### ISSUE THREAD

**Issue by dfoxfranke** [NixOS/nixpkgs#9578]
The `preStart` script for `wpa_supplicant` tries to set permissions and possibly append text to `/etc/wpa_supplicant.conf`. If these operations fail, the daemon won't start. This is annoying for users who have their own system modules which generate a `wpa_supplicant` configuration as a read-only file in the store.

See also #9466, cc @thoughtpolice.

**Comment by globin** [comment]
I think this has been fixed by #12172
