### ISSUE TITLE
Enabling gnome keyring blocks login via sssd

### ISSUE THREAD

**Issue by mrschyte** [NixOS/nixpkgs#95798]
**Describe the bug**
If gnome keyring is enabled, it is not possible to login from the console or the display manager with a user managed by sssd.

**To Reproduce**
1. Setup the sssd identity provider with ad integration or ldap + kerberos
2. Enable gnome keyring with `services.gnome3.gnome-keyring.enable = true`
3. Try logging in from the console or display manager with a user managed by sssd (this fails)
4. Try logging in using ssh with a user managed by sssd (this succeeds)

**Expected behavior**
The sssd managed user should be able to login to both the text based and graphical consoles.

**Additional context**
When gnome keyring is enabled the `security.pam` module adds the line `auth required pam_unix.so  likeauth try_first_pass` to `/etc/pam.d/login`. This requires the presence of a local user account to be able to successfully authenticate. ssh login succeeds, since this line is not present in `/etc/pam.d/sshd`.

Instead of requiring `pam_unix` when gnome keyring is enabled, it would be better to implement the authentication flow similar to the below snippet. The only downside is that if additional authentication modules are added, the `success=n` parameters need to be updated for the flow to jump to the correct module.

```
auth [success=2 default ignore] pam_unix.so nullok_secure
auth [success=1 default ignore] pam_sss.so use_first_pass
auth requisite pam_deny.so
auth optional pam_gnome_keyring.so
auth optional pam_permit.so
```

Alternatively the solution utilizing the substack parameter described in https://wiki.gnome.org/Projects/GnomeKeyring/Pam could be implemented.

This issue is also present when enabling other pam modules:

```
          (optionalString (cfg.unixAuth &&
          (config.security.pam.enableEcryptfs
            || cfg.pamMount
            || cfg.enableKwallet
            || cfg.enableGnomeKeyring
            || cfg.googleAuthenticator.enable
            || cfg.duoSecurity.enable)) ''
              auth required pam_unix.so ${optionalString cfg.allowNullPassword "nullok"} ${optionalString cfg.nodelay "nodelay"} likeauth
              ${optionalString config.security.pam.enableEcryptfs
                "auth optional ${pkgs.ecryptfs}/lib/security/pam_ecryptfs.so unwrap"}
              ${optionalString cfg.pamMount
                "auth optional ${pkgs.pam_mount}/lib/security/pam_mount.so"}
              ${optionalString cfg.enableKwallet
                ("auth optional ${pkgs.plasma5.kwallet-pam}/lib/security/pam_kwallet5.so" +
                 " kwalletd=${pkgs.libsForQt5.kwallet.bin}/bin/kwalletd5")}
              ${optionalString cfg.enableGnomeKeyring
                "auth optional ${pkgs.gnome3.gnome-keyring}/lib/security/pam_gnome_keyring.so"}
              ${optionalString cfg.googleAuthenticator.enable
                "auth required ${pkgs.googleAuthenticator}/lib/security/pam_google_authenticator.so no_increment_hotp"}
              ${optionalString cfg.duoSecurity.enable
                "auth required ${pkgs.duo-unix}/lib/security/pam_duo.so"}
```

**Notify maintainers**

@edolstra
@Mic92
@ixmatus
@gnidorah
@flokli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
 - security.pam
```

**Comment by tbsmoest** [comment]
The problem here appears to be that `pam_unix.so` is `required` when for example `cfg.enableGnomeKeyring` is true. That means if the authentication with pam_unix fails, the pam_sss authentication wail fail, too. 
In my opinion the line
```
              auth required pam_unix.so ${optionalString cfg.allowNullPassword "nullok"} ${optionalString cfg.nodelay "nodelay"} likeauth
```
needs to be removed entirely. 

The case `pam_unix` is already correclty covered a few lines below:
```
auth sufficient pam_unix.so  likeauth try_first_pass
```

**Comment by wucke13** [comment]
related to https://github.com/NixOS/nixpkgs/issues/128116
