### ISSUE TITLE
VNC service with KDE

### ISSUE THREAD

**Issue by sg2002** [NixOS/nixpkgs#9585]
Since jobs are deprecated, people who want to get a VNC server running need to use systemd.

The problem is that writing a systemd unit for, for example tightvnc with KDE is extremely hard, since you have to pass to it every single path that KDE needs.

So NixOS would probably need to provide some kind of "KDE in VNC" package, that would provide those paths and can be easily required by a systemd unit.

**Comment by heydojo** [comment]
NixOS could do with a tigervnc service. It is on my todo list. Porting it from Fedora _should_ be trivial.
tigervnc installs the required vnc module for the xserver already. It should be as simple as install tiger vnc, open the correct ports on the firewall, vncpasswd, start the systemd unit and vnc into the machine.
I will probably be referring to https://wiki.archlinux.org/index.php/TigerVNC when I find time to have a bash at this as it is very helpful.

**Comment by Profpatsch** [comment]
(triage) what’s the further plans?
