### ISSUE TITLE
Tahoe-LAFS package is outdated

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#9586]
Currently, the [Tahoe-LAFS package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/p2p/tahoe-lafs/default.nix) is at 1.10.0, whereas the latest version is 1.10.2 (even though the download page still says 1.10.1).

cc @peti

**Comment by zimbatm** [comment]
Fixed by 443072799dc228ef1ebb8573c4ed55cf569c2b2a
