### ISSUE TITLE
The Eclipse executable launcher was unable to locate its companion shared library

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#9587]
I installed eclipse with:

    nix-env -iA nixos.pkgs.eclipses.eclipse_sdk_45 -I nixpkgs=/home/cassou/nixpkgs -I nixos=/home/cassou/nixpkgs/nixos

when I launch it, I immediately get

    The Eclipse executable launcher was unable to locate its companion shared library.

cc @rycee @bjornfor

**Comment by bjornfor** [comment]
Confirmed. That must have been broken quite recently.

**Comment by DamienCassou** [comment]
In the generated `eclipse` script, removing the `exec` seems to fix the problem:

```patch
--- /nix/store/ab0nff29jim5vmsgj9phaqg1bh5sgkzh-eclipse-sdk-4.5/bin/eclipse	1970-01-01 01:00:01.000000000 +0100
+++ /tmp/eclipse	2015-09-01 10:56:52.056133253 +0200
@@ -1,4 +1,4 @@
 #! /nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash -e
 export PATH=/nix/store/rf9gx5mr9shzabhhr2rx1sj6k5pv2c3w-openjdk-8u60b24-jre/bin${PATH:+:}$PATH
 export LD_LIBRARY_PATH=/nix/store/26zyb2byw1sqr2afbz6ql3352ri847jd-glib-2.44.1/lib:/nix/store/c62hagflgrp9n1bahmxwlfyn0a2c4kwf-gtk+-2.24.28/lib:/nix/store/mjn78jwnbnskllxrq7r6rp2kw87fq0yn-libXtst-1.2.2/lib:/nix/store/yvm7gs12sn0pdiqy9ij76012wafxzjr6-webkitgtk-2.4.9/lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH
-exec -a "$0" /nix/store/ab0nff29jim5vmsgj9phaqg1bh5sgkzh-eclipse-sdk-4.5/eclipse/eclipse -configuration $HOME/.eclipse/org.eclipse.platform_4.5.0/configuration "${extraFlagsArray[@]}" "$@"
+/nix/store/ab0nff29jim5vmsgj9phaqg1bh5sgkzh-eclipse-sdk-4.5/eclipse/eclipse -configuration $HOME/.eclipse/org.eclipse.platform_4.5.0/configuration "${extraFlagsArray[@]}" "$@"
```

**Comment by bjornfor** [comment]
More specifically, it's the ```-a "$0"``` flag to exec that is the problem.

**Comment by vcunat** [comment]
`makeWrapper` now accepts `--argv0 newA0`. I think this case should be fine again after some commits already in both master and 15.09 #9562. Now only `wrapProgram` specifies `-a` by default, not `makeWrapper` anymore (it did only for a brief period). Also /cc @ttuegel for argv0 issue reference.

**Comment by peti** [comment]
I've installed Eclipse using todays Git HEAD and it worked fine.

**Comment by bjornfor** [comment]
Confirmed working on release-15.09 too (the ```-a "$0"``` is removed).
