### ISSUE TITLE
Can't build a go program with buildGoModule

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#95913]
**Describe the bug**
I'm trying to build this go program: https://github.com/mellow-io/go-tun2socks

It builds fine with `nix-shell -p go --pure` then just `make`, but when I try to put it in a derivation, I got the following error message:
```
# github.com/eycorsican/go-tun2socks/core
../../vendor/github.com/eycorsican/go-tun2socks/core/addr.go:5:10: fatal error: 'lwip/tcp.h' file not found
#include "lwip/tcp.h"
         ^~~~~~~~~~~~
1 error generated.
```

**To Reproduce**
1. Go to [this gist](https://gist.github.com/capsensitive/7983e2e32b5c6488d98a5c777650da73) and download both `default.nix` and `generic.nix`
2. `nix-shell -E "with import <nixpkgs> {}; callPackage ./default.nix {}"`

**Expected behavior**
It builds without problems, just like in a `nix-shell`.

**Additional context**
I was told by @Mic92 on IRC to inspect the `go-modules` attribute with `nix-build`.

I put the `buildGoModule` part in a separate file, removed `make` in the `buildPhase`, and use:
```
nix-build -E "with import <nixpkgs> {}; callPackage ./default.nix {}" -A go-modules
```

I got:
```
/nix/store/1pwszg205n9sm20sw3jdrgfnf5jlxwmn-go-tun2socks-1.0.10-go-modules
```

The tree structure of that folder is also posted in the same gist.

**Notify maintainers**
@Mic92 @zowoq 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(devwork): `"darwin"`
 - channels(root): `"nixpkgs-20.03pre215563.2f3bec63d65, unstable-20.09pre236138.970b2b853d4, darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
Considering this user was deleted, I doubt there'll be any more feedback. Closing.
