### ISSUE TITLE
go depending on procps?

### ISSUE THREAD

**Issue by ctheune** [NixOS/nixpkgs#9592]
I just updated my nixos-unstable channel tracking branch and got this when trying to build syncthing:

```
installing ‘go1.5-syncthing-0.11.21’
error: Package ‘procps-3.3.11’ in ‘/Users/ctheune/Code/nixpkgs.ctheune.vagrant/nixpkgs.ctheune/pkgs/os-specific/linux/procps-ng/default.nix:26’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

This is new - I'm getting a lot of packages build, not sure what the dependency tree is here.

I'm trying to work around this by allowing broken packages for now ...

**Comment by domenkozar** [comment]
cc @wkennington

**Comment by copumpkin** [comment]
Seems like the right thing here is to have a top-level logical `ps` attribute, which on linux evaluates to `procps`, on darwin evaluates to `adv_cmds` (or a single output of it, or whatever), and on other platforms evaluates to something sensible too. I doubt many things care about the specific `ps` implementation they get.

**Comment by copumpkin** [comment]
cc @gridaphobe, who (iirc) wrote the original darwin `ps` derivation using `adv_cmds`.

**Comment by gridaphobe** [comment]
@copumpkin's suggestion sounds good to me, we obviously can't use `procps` on darwin.
