### ISSUE TITLE
Cabal2nix hash keeps changing

### ISSUE THREAD

**Issue by woehr** [NixOS/nixpkgs#9599]
While attempting to build cabal2nix from the current head (1820dd8e21727d6d3601a8d1ed3546de5ca7ca33):

```
output path ‘/nix/store/byz7yir4yr395nsan1dvxbhs8vlj2gfh-cabal2nix-560fb2b’ should have r:sha256 hash ‘1pyjy9kb8g18g6shlg7vnyaspa892zaq4hqvmqvdbxrlf24vg0wp’, instead has ‘18prg51b3s884fk5qgrfnm86623ihy278yzr8xify4zywl2lx02c’
cannot build derivation ‘/nix/store/wzn08sdniccfa6hpg00s0y2xx110dngn-cabal2nix-20150824.drv’: 1 dependencies couldn't be built

```

However commit b2c3c58476aaa228269b1a9c70a3be695ffbed59 from three days ago builds successfully while no changes have been made to pkgs/development/tools/haskell/cabal2nix/default.nix.

Am I missing something obvious here? As I understand it ```fetchgit``` should not be resulting in different hashes.

I'll add that this appears to have happened in the past where commits 523cd395c711278cbb52b51d866474f548195843 and afe6f0531068c43ac40555755a625aec16a1a7bb have updated the hash.

**Comment by jb55** [comment]
I have also run into this recently, had to remove it from my config when installing nixos.

**Comment by vcunat** [comment]
Sounds like #8567 with `deepClone` as well. /cc maintainer @peti.
