### ISSUE TITLE
services.virtualboxGuest.enable obsolete warning after updated in config

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#9600]
I am building nixos against the latest head

````
4fecf15 master syncthing: Fix top-level expression
````

and I get this warning message when running my Makefile command in my configuration https://github.com/ryantm/nixfiles

````
`services.virtualboxGuest.enable' is used. It was renamed to `virtualisation.virtualbox.guest.enable'.
````

It seems like it warns you about the obsolete option even after you've removed it from your configuration.

**Comment by vcunat** [comment]
That's because it's used internally https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/virtualbox-image.nix#L131.

**Comment by vcunat** [comment]
It should be fine now, I believe. Thanks.
