### ISSUE TITLE
nixos/nginx: should ensure /var/cache/nginx and /var/log/nginx

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#96052]
NixOS `nginx` module does not create `/var/cache/nginx` and `/var/log/nginx` directories, but when the directories do not exist, nginx service fails to start
```
nginx: [emerg] mkdir() "/var/cache/nginx/client_body" failed (2: No such file or directory)
```  

Test suite explicitly creates the directories using `mkdir -p`
https://github.com/NixOS/nixpkgs/blob/11c18faa4e4ab42bcb926e45b89811eb74be411d/nixos/tests/service-runner.nix#L26
and so every nginx user has to do

It would be nice to of nixos module ensures the directories before starting nginx (using `mkdir -p` or `systemd.tmpfiles.rules`)

**Comment by misuzu** [comment]
Maybe there is some kind of regression in `systemd`?
It should create those directories:
https://github.com/NixOS/nixpkgs/blob/22e8ada3b3c5fe6d33da9bf8e4d73e3be9fdc993/nixos/modules/services/web-servers/nginx/default.nix#L721
https://github.com/NixOS/nixpkgs/blob/22e8ada3b3c5fe6d33da9bf8e4d73e3be9fdc993/nixos/modules/services/web-servers/nginx/default.nix#L724

**Comment by volth** [comment]
Probably I have systemd from 20.03 (running since last reboot) and
nginx module after the change.
