### ISSUE TITLE
KDE applications over-scaled on HiDPI display

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#96055]
**Describe the bug**
Some KDE applications like Dolphin and Konsole get GUI over-scaled on current master. But they works fine before #84232 .

**To Reproduce**
1. Checkout current master(`5be356a9`)
1.  Use this configuration to `build-vm`:
```nix
{
  users.users.root.initialPassword = "";
  services.xserver = {
    enable = true;
    dpi = 144;
    desktopManager.plasma5.enable = true;
    displayManager.sddm.enable = true;
  };
}
```
2. Run the VM and check Dolphin GUI.
3. Checkout `de1c8a03^` (the parent of the merge commit of staging branch, actually `eac5ef8a`) and repeat steps above.

**Expected behavior**
Font size, icon size and menu height should be smaller and be the same as previous.

**Screenshots**
Note that for comparison, "System Settings" has correct GUI scale in both screenshots, but "Dolphin" does not.
Title bar always has correct font size.

Current master: (Dolphin GUI is too large)
<img width="512" alt="Screenshot_20200823_124257" src="https://user-images.githubusercontent.com/14816024/90971416-92b29200-e542-11ea-8dbf-b22cf9acb280.png">

Expected: (Previous. Tested on `eac5ef8aa9c0ddd948b20e83d9d7b37cd0132a81`)
<img width="513" alt="Screenshot_20200823_130950" src="https://user-images.githubusercontent.com/14816024/90971417-96461900-e542-11ea-93a4-add3b4c68e76.png">

**Additional context**
In KDE "Display Configuration", "Global scale" is always set to `1.0`. Only xserver dpi is set.

**Notify maintainers**

@petabyteboy 
cc @worldofpeace @ttuegel

**Metadata**
> Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - channels(oxa): `"home-manager, mozilla"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.plasma5
```

**Comment by ttuegel** [comment]
There were [changes upstream](https://doc.qt.io/qt-5/whatsnew514.html#qt-gui-module) to HiDPI support in Qt 5.14. The linked changelog suggests some environment variables you could try. In particular, you might make sure that `QT_AUTO_SCREEN_SCALE_FACTOR` is not set. You might also look at `QT_SCREEN_SCALE_FACTORS` to make sure that global scaling is _actually_ disabled.

This is somewhat strange, but on my physical HiDPI display, I don't see any overscaling. Actually, I have to enable global scaling to get readable text, but I tried it with global scaling disabled for debugging. The only scaling problem I have is that the desktop (including tray icons and cursor) doesn't seem to be scaled correctly. :thinking:

**Comment by ttuegel** [comment]
> I don't see any overscaling

Actually, I do see some overscaling, but it's not consistent. Some applications seem to be OK, some are underscaled, and some are overscaled. I want to see if this persists in Plasma 5.18; I think that Plasma handles scaling itself and disables Qt auto-scaling, and I wonder if Plasma 5.17 just isn't compatible with Qt 5.14 (which is much newer).

**Comment by oxalica** [comment]
@ttuegel
> Actually, I do see some overscaling, but it's not consistent. 

Yeah... For me, just Dolphin and Konsole have the issue, which can be most common used apps.

> In particular, you might make sure that `QT_AUTO_SCREEN_SCALE_FACTOR` is not set. You might also look at `QT_SCREEN_SCALE_FACTORS` to make sure that global scaling is actually disabled.

They are both not set (also not occur in nixpkgs or wrappers). And I did some other tests on `dolphin`:
- `QT_AUTO_SCREEN_SCALE_FACTOR=0` results in normal (expected) scale. `1` or unset cause overscale.
  Maybe it's on by default now?
- `QT_SCREEN_SCALE_FACTORS=1` or `2` or unset cause overscale. (Seems current (over)scale is 2.)
  `1.5` results in expected scale. (Why isn't it to be `1.5*1.5=2.25`? Does it ignore `xserver.dpi`?)
- `QT_AUTO_SCREEN_SCALE_FACTOR` only takes effect when `QT_SCREEN_SCALE_FACTORS=1` or unset.
  Otherwise, the given scale factors is used.

**Comment by ttuegel** [comment]
> For me, just Dolphin and Konsole have the issue, which can be most common used apps.

I also have overscaling in window title bars and desktop panels, but in both those places, only the fonts are overscaled, not icons as in other applications.

> QT_AUTO_SCREEN_SCALE_FACTOR=0 results in normal (expected) scale. 1 or unset cause overscale. Maybe it's on by default now?

It is off by default on my desktop, and I still see overscaling. :thinking: 

`QT_SCREEN_SCALE_FACTORS` is supposed to take a list of display names and scale factors; I don't know what happens when it's set to a single number, but that's not how it's supposed to be used. This is the environment variable that the System Settings module sets, for example. It ignores DPI and overrides `QT_AUTO_SCREEN_SCALE_FACTOR`.

**Comment by oxalica** [comment]
@ttuegel

Played with `System Setting - Hardware - Display and Monitor - Global scale`.
It's even more confusing. I expect the scale to be slightly bigger than `1.4x` but it seems to jump to `2.0x` when set to `1.5x` or larger, or `1.0x` (default).

![Screenshot_20200831_231347](https://user-images.githubusercontent.com/14816024/91735981-a2377800-ebdf-11ea-821e-5814ea9c3379.png)

Well, I don't know the detail about how global settings work. I can't discover `QT_SCREEN_SCALE_FACTORS` from `env`, but it is somehow passed to the apps.

> It (QT_AUTO_SCREEN_SCALE_FACTOR) is off by default on my desktop, and I still see overscaling. :thinking:

Do you check it by `env`? Not sure if there's any other hidden configuration.

**Comment by ttuegel** [comment]
I check the settings by `env` or `echo`:

```
echo $QT_SCREEN_SCALE_FACTORS
DisplayPort-0=2;DisplayPort-1=2;DisplayPort-2=2;
```

There is no hidden configuration, just the environment. However, it is possible that programs will get a different environment depending on how they are started because some things are launched via D-Bus and inherit the environment from there. The environments are supposed to be synchronized, but it's hard to rule out a problem.

There is a lot of good information in [this blog post](https://pointieststick.com/2020/07/08/high-dpi-update/). It looks like this is not a NixOS specific issue, but something that many people are struggling with using Plasma and Qt >= 5.14.

**Comment by ttuegel** [comment]
As always, [ArchWiki](https://wiki.archlinux.org/index.php/HiDPI#Qt_5) has lots of information.

On the "bad" configuration, I have:

- `PLASMA_USE_QT_SCALING` is unset
- `QT_SCREEN_SCALE_FACTORS=HDMI-A-0=2;DVI-D-0=2;VGA-0=2;`
- `QT_AUTO_SCREEN_SCALE_FACTOR=0`
- `QT_SCREEN_SCALE_FACTOR` is unset

On the "good" configuration, I have:

- `PLASMA_USE_QT_SCALING=1`
- `QT_SCREEN_SCALE_FACTORS=DisplayPort-0=2;DisplayPort-1=2;DisplayPort-2=2;`
- `QT_AUTO_SCREEN_SCALE_FACTOR` is unset
- `QT_SCREEN_SCALE_FACTOR` is unset
