### ISSUE TITLE
discord: Frequent segmentation faults in libappindicator

### ISSUE THREAD

**Issue by goffrie** [NixOS/nixpkgs#96063]
**Describe the bug**
Discord crashes intermittently (maybe every 30 minutes) for me. This is especially noticeable when in a voice room, but I think it happens independently of that.

**To Reproduce**
1. Leave Discord running for a long period of time.
2. Observe that Discord segfaults.

**Additional context**
Stack trace in libappindicator-gtk3:
```
(gdb) bt
#0  0x00007f09f8fa015b in status_icon_changes () from /nix/store/s20y6yrgbrr1p5h70ydwim8z1q9niizk-libappindicator-gtk3-12.10.0/lib/libappindicator3.so
#1  0x00007f0a1ad94ec2 in g_closure_invoke () from /nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/libgobject-2.0.so.0
#2  0x00007f0a1ada7dc4 in signal_emit_unlocked_R () from /nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/libgobject-2.0.so.0
#3  0x00007f0a1adb2fef in g_signal_emit_valist () from /nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/libgobject-2.0.so.0
#4  0x00007f0a1adb397f in g_signal_emit () from /nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/libgobject-2.0.so.0
#5  0x00007f09f8f9f1d6 in app_indicator_set_icon_full () from /nix/store/s20y6yrgbrr1p5h70ydwim8z1q9niizk-libappindicator-gtk3-12.10.0/lib/libappindicator3.so
```

The rest of the stack has no symbols at all.

This has also been reported at https://www.reddit.com/r/linuxquestions/comments/fprclz/discord_segmentation_fault/ with the workaround being to remove libappindicator.

The crashes only started recently, presumably when #91375 landed.

**Notify maintainers**
@ldesgoui @MP2E @tadeokondrak @benley 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.57, NixOS, 20.09pre237781.32b46dd897a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(goffrie): `"home-manager, nixpkgs-20.09pre238508.729e7295cf7"`
 - channels(root): `"nixos-20.09pre237781.32b46dd897a"`
 - nixpkgs: `/home/goffrie/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by JJJollyjim** [comment]
Other sources report that things are fixed by installing an up-to-date libappindicator from Launchpad (they haven't put out a release in 8 years, but development has continued somewhat). Arch is now packaging revision 296 from bzr. I'm testing the latest version here: https://github.com/JJJollyjim/nixpkgs/tree/libappindicator-unstable

**Comment by goffrie** [comment]
Nice, that worked for me (though I needed [another patch to get things building](https://github.com/goffrie/nixpkgs/commit/68eda259519ba31dadaa23eaa7bdb841c6fd6bb2)).

**Comment by jonringer** [comment]
please try discord off of master to ensure this works:
```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz nix-shell -p discord --run Discord
```

**Comment by worldofpeace** [comment]
libappindicator is dead, we should use libayatana-appindicator which is maintained by debian

**Comment by jonringer** [comment]
@goffrie does it work with the above command I gave?

**Comment by goffrie** [comment]
Sorry, I (mostly) don't use my NixOS machine on weekdays, so I'll find out
tomorrow :)

**Comment by jobojeha** [comment]
> please try discord off of master to ensure this works:
> 
> ```
> NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz nix-shell -p discord --run Discord
> ```

I had this issue in Discord video conferences for the past two weeks with crashes every hour or so. The command @jonringer provided fixes it for me 🙏 Thanks a lot!

**Comment by goffrie** [comment]
Yup, this is working for me now too. Thanks everyone!
