### ISSUE TITLE
Haskell: fix meta.platforms vs. meta.hydraPlatforms logic in the generic builder

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#9608]
The values for `meta.platforms` and `meta.hydraPlatforms` should be determined as follows:
1. `meta.platforms` defaults to `ghc.meta.platforms`. 
2. If a `platforms` argument is provided, then `meta.platforms` should be `platforms` intersected with `ghc.meta.platforms`.
3. `meta.hydraPlatforms` defaults to the value of `meta.platforms`.
4. If `hydraPlatforms' is provided, then`meta.hydraPlatforms`should be`hydraPlatforms`intersected with`meta.platforms`.

**Comment by Profpatsch** [comment]
(triage) @peti have you fixed this in the meantime?

**Comment by Profpatsch** [comment]
(triage) ping

**Comment by peti** [comment]
Yes, this was fixed a while ago.
