### ISSUE TITLE
anystyle/anystyle-cli

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#96082]
**Project description**
>AnyStyle is a very fast and smart parser for academic references. It was originally inspired by ParsCit and FreeCite; AnyStyle uses machine learning algorithms and aims to make it easy to train the model with data that is relevant to your parsing needs.

**Metadata**

* homepage URL: https://github.com/inukshuk/anystyle, https://github.com/inukshuk/anystyle-cli
* source URL: https://github.com/inukshuk/anystyle, https://github.com/inukshuk/anystyle-cli
* license: BSD
* platforms: Linux? Not sure. It's a Ruby app.

**Comment by SCOTT-HAMILTON** [comment]
Opened PR here https://github.com/NixOS/nixpkgs/pull/96186.
If you prefer using it now, check out my nur repository http://nur.nix-community.org/repos/shamilton/.

**Comment by davidak** [comment]
Closing since PR was merged.
