### ISSUE TITLE
gst-plugin-base doesn't build on master

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#96108]
Ran `nix-build -A gst-streamer-base` on master, [build log](https://gist.github.com/sternenseemann/15c28c6ad666169d6b091d2b79013d15).

cc @matthewbauer

**Comment by jtojnar** [comment]
You probably want `gst_all_1.gst-plugins-base`. The `gst-plugins-base` is unmaintained and insecure ancient branch that ought to be removed: https://github.com/NixOS/nixpkgs/issues/39975

**Comment by sternenseemann** [comment]
Alright then it's not a big ìssue, just wondered about it popping up in `nixpkgs-review` every now and then.

**Comment by FRidh** [comment]
It's marked as broken om master since d034a0039d8937aca2f64d1d3911e8b71f416137. Did you set `allowBroken = true;`?

**Comment by sternenseemann** [comment]
Yeah, my bad. A bit strange that `nixpkgs-review` also adheres by this setting and tries to build broken packages?!
