### ISSUE TITLE
pandoc doesn't build on Raspberry Pi 4

### ISSUE THREAD

**Issue by golddranks** [NixOS/nixpkgs#96154]
**Describe the bug**
On latest unstable, installing pandoc with `nix-env -f "<nixpkgs>" -iA pandoc` doesn't manage to build it. The haskell library that actually fails the build is Trifecta 2.1. The dependency chain is: pandoc-2.9.2.1→haddock-library-1.8.0→tree-diff-0.1->trifecta-2.1. This also affects packages that uses pandoc, such as ShellCheck.

**To Reproduce**
1. On Raspberry Pi 4, type `nix-env -f "<nixpkgs>" -iA pandoc`
2. Observe the failure:
```
...
Preprocessing library for trifecta-2.1..
Building library for trifecta-2.1..
[ 1 of 13] Compiling Text.Trifecta.Util.Combinators ( src/Text/Trifecta/Util/Combinators.hs, dist/build/Text/Trifecta/Util/Combinators.o )
[ 2 of 13] Compiling Text.Trifecta.Util.IntervalMap ( src/Text/Trifecta/Util/IntervalMap.hs, dist/build/Text/Trifecta/Util/IntervalMap.o )
[ 3 of 13] Compiling Text.Trifecta.Util.Pretty ( src/Text/Trifecta/Util/Pretty.hs, dist/build/Text/Trifecta/Util/Pretty.o )
[ 4 of 13] Compiling Text.Trifecta.Delta ( src/Text/Trifecta/Delta.hs, dist/build/Text/Trifecta/Delta.o )
[ 5 of 13] Compiling Text.Trifecta.Rope ( src/Text/Trifecta/Rope.hs, dist/build/Text/Trifecta/Rope.o )
[ 6 of 13] Compiling Text.Trifecta.Util.It ( src/Text/Trifecta/Util/It.hs, dist/build/Text/Trifecta/Util/It.o )
[ 7 of 13] Compiling Text.Trifecta.Rendering ( src/Text/Trifecta/Rendering.hs, dist/build/Text/Trifecta/Rendering.o )
[ 8 of 13] Compiling Text.Trifecta.Result ( src/Text/Trifecta/Result.hs, dist/build/Text/Trifecta/Result.o )
[ 9 of 13] Compiling Text.Trifecta.Highlight ( src/Text/Trifecta/Highlight.hs, dist/build/Text/Trifecta/Highlight.o )
[10 of 13] Compiling Text.Trifecta.Combinators ( src/Text/Trifecta/Combinators.hs, dist/build/Text/Trifecta/Combinators.o )
[11 of 13] Compiling Text.Trifecta.Parser ( src/Text/Trifecta/Parser.hs, dist/build/Text/Trifecta/Parser.o )
[12 of 13] Compiling Text.Trifecta    ( src/Text/Trifecta.hs, dist/build/Text/Trifecta.o )
[13 of 13] Compiling Text.Trifecta.Tutorial ( src/Text/Trifecta/Tutorial.hs, dist/build/Text/Trifecta/Tutorial.o )
Preprocessing test suite 'doctests' for trifecta-2.1..
Building test suite 'doctests' for trifecta-2.1..
[1 of 2] Compiling Build_doctests   ( dist/build/doctests/autogen/Build_doctests.hs, dist/build/doctests/doctests-tmp/Build_doctests.o )
[2 of 2] Compiling Main             ( tests/doctests.hs, dist/build/doctests/doctests-tmp/Main.o )
Linking dist/build/doctests/doctests ...
Preprocessing test suite 'quickcheck' for trifecta-2.1..
Building test suite 'quickcheck' for trifecta-2.1..
[1 of 1] Compiling Main             ( tests/QuickCheck.hs, dist/build/quickcheck/quickcheck-tmp/Main.o )
Linking dist/build/quickcheck/quickcheck ...
running tests
Running 2 test suites...
Test suite doctests: RUNNING...
doctests: rts/linker/elf_reloc_aarch64.c:95: encodeAddendAarch64: Assertion `isInt64(21+12, addend)' failed.
Test suite doctests: FAIL
Test suite logged to: dist/test/trifecta-2.1-doctests.log
Test suite quickcheck: RUNNING...
Test suite quickcheck: PASS
Test suite logged to: dist/test/trifecta-2.1-quickcheck.log
1 of 2 test suites (1 of 2 test cases) passed.
builder for '/nix/store/s69nqi4s3zmkccngmszgqg90fb8ax66g-trifecta-2.1.drv' failed with exit code 1
cannot build derivation '/nix/store/bq2xlk5vnn229db7gzrj9mqllz5nx4qv-tree-diff-0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/idjfga934g9iyw2q6c7kip2lxiqrgr0j-haddock-library-1.8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dah5382l9shy5qh6addsjrl8wd1d6v0h-pandoc-2.9.2.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/dah5382l9shy5qh6addsjrl8wd1d6v0h-pandoc-2.9.2.1.drv' failed
```

**Expected behavior**
Pandoc builds succesfully.

**Additional context**
I suspect that the bug is this one, fixed by GHC 8.10.2, but I haven't been able to test it: https://gitlab.haskell.org/ghc/ghc/-/issues/15275

**Metadata**
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/vjz9r8xp8j2i4hlr81dgpkb7srn936ki-bash-interactive-4.4-p23-dev
copying path '/nix/store/vjz9r8xp8j2i4hlr81dgpkb7srn936ki-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.118, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre239912.7e545bd7f35"`
 - channels(nixos): `"nixos-20.03pre209708.5088ef5a19c"`
 - channels(kon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by golddranks** [comment]
I'm currently testing building pandoc with the offending haskell library, trifecta, set not to run it's tests:

In `pkgs/development/haskell-modules/configuration-common.nix`:
```
trifecta = if (pkgs.stdenv.hostPlatform.isAarch64) then dontCheck super.trifecta else super.trifecta;
```

I'm also testing whether building trifecta with GCH 8.10.2 helps, as I suspect:
```
$ nix-env -iA nixos.haskell.packages.ghc8102.trifecta
```

I'll report back once these builds end; it seems that they might take a while.

**Comment by golddranks** [comment]
Confirmed that building with GHC 8.10.2 (`$ nix-env -iA nixos.haskell.packages.ghc8102.trifecta`) doesn't help. Reported the situation at https://gitlab.haskell.org/ghc/ghc/-/issues/15275#note_295437 .

**Comment by golddranks** [comment]
Pandoc builds without problems, when disabling the Trifecta tests.

**Comment by golddranks** [comment]
This should get fixed once https://github.com/NixOS/nixpkgs/pull/96272 gets merged. However, the root cause isn't easy to fix, so the tests are likely to stay disabled for a while. I wonder what should be done for this issue.

**Comment by peti** [comment]
This bug report is very confusing to me. According to https://github.com/NixOS/nixpkgs/issues/97407, we cannot even build `ghc` on `aarch64` at the moment. When I try to build `pandoc` on my machine locally, I get a totally different result than what you reported, i.e. my build fails trying to install the ghc-8.6.5 binary for bootstrapping the build of the proper compiler, which would be required to build plenty of packages before we'd get even close to building `trifecta`.

**Comment by golddranks** [comment]
Sorry, this bug is fixed and I forgot to close it. Pandoc should build fine with https://github.com/NixOS/nixpkgs/pull/96287 merged. Closing this.

**Comment by golddranks** [comment]
You are correct in that the ghc-8.6.5 binary bootstrapping problem prevents a lot of haskell packages from compiling, but it's a different issue from what was reported here.

**Comment by golddranks** [comment]
Just for the future reference: the root cause (https://gitlab.haskell.org/ghc/ghc/-/issues/15275), a linking? bug in GHC isn't fixed, but it seems that no fix is to be expected in near future.
