### ISSUE TITLE
fzf fails to find perl

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#96178]
**Describe the bug**
I use fzf to search history and after updating to nixos-unstable today saw ctrl+r fails with `perl: can not find binary` or something similar.
Seems like fzf-history-widget()  (fzf 0.22)  references perl like `selected=( $(fc -rl 1 | perl -ne 'print if !$seen{(/^\s*[0-9]+\s+(.*)/, $1)}++' |` 

the package doesn't list perl as a dependency. As a quickfix, I've installed perl globally.
CC @zowoq

**Comment by zowoq** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/95930 but it's not in `nixos-unstable` yet.

**Comment by teto** [comment]
I searched the tracker with `fzf` and `perl` though Oo'' thanks should have checked master's log :'(
