### ISSUE TITLE
The option `services.mysql.configFile' defined in `/etc/nixos/configuration.nix' does not exist 

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#96176]
**Describe the bug**
The option `services.mysql.configFile' defined in `/etc/nixos/configuration.nix' does not exist 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.git.9fdca7179c2M (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:

**Comment by aanderse** [comment]
Could use a few more details, like how to reproduce please.

**Comment by prehonor** [comment]
> Could use a few more details, like how to reproduce please.
This is my configuration:
https://prehonor.coding.net/public/nixpkgs/etc/git/files/master/nixos/configuration.nix

**Comment by Infinisil** [comment]
You're on 20.03, which doesn't have that option yet as it was only introduced afterwards. Use nixos-unstable instead or cherry-pick https://github.com/NixOS/nixpkgs/pull/81940 to get that option

**Comment by prehonor** [comment]
> You're on 20.03, which doesn't have that option yet as it was only introduced afterwards. Use nixos-unstable instead or cherry-pick #81940 to get that option

Thank you.
