### ISSUE TITLE
terraform.withPlugins does not work for Terraform 0.13

### ISSUE THREAD

**Issue by brainrape** [NixOS/nixpkgs#96195]
**Describe the bug**

Terraform 0.13 has a new plugin directory structure, so it doesn't find plugins in the directory created by the `withPlugins` helper.

The documentation describes the new format: https://www.terraform.io/docs/configuration/provider-requirements.html#source-addresses

**To Reproduce**
```
$ echo 'provider "aws" {}' > example.tf
$ nix-shell -p 'terraform_0_13.withPlugins (p : [p.aws])' --run 'terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
provider registry.terraform.io/hashicorp/aws was not found in any of the
search locations

- /nix/store/854kmpfd5bl8q0gs6jrbaswxy5s3vpcx-tf-plugin-env/bin
```

**Expected behavior**
Terraform should find the plugin.

**Additional Context**
Here's an earlier similar bug: https://github.com/NixOS/nixpkgs/issues/49316

**Notify maintainers**

@zimbatm @peterhoeg @kalbasit @marsam @babariviere @Chili-Man

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre234194.8d05772134f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre239228.bd0e645f024"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: terraform_0_13
# a list of nixos modules affected by the problem
module:
```

**Comment by timstott** [comment]
Focusing resolution in https://github.com/NixOS/nixpkgs/issues/98652

**Comment by brainrape** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/99198
