### ISSUE TITLE
androidenv: ability to use packages outside of android-sdk

### ISSUE THREAD

**Issue by eyJhb** [NixOS/nixpkgs#96205]
There is a need to use e.g. cmake, outside of android-sdk, at least setting `cmake.dir` in `local.properties`, which is required to package some android apps.

Currently I have to use this one-time-hack `printf "cmake.dir = ${sdk.androidsdk}/libexec/android-sdk/cmake/3.10.2.4988404\n" >> local.properties`.

Can this currently be archived, is it a bug, or is there a better way?

Ping @numinit @jakubgs  and anyone else that knows about androidenv.

**Comment by numinit** [comment]
Just to follow up on this, there's a slightly better way that's been added to the example shell.nix in #89775.

**Comment by eyJhb** [comment]
Out of date, unsure if it's still a thing, reopen if so.
