### ISSUE TITLE
nixos/victoriametrics: NixOS module incorrectly formats arguments

### ISSUE THREAD

**Issue by zeonin** [NixOS/nixpkgs#96206]
All arguments passed to Victoriametrics by the systemd service after httpListenAddr are improperly formatted and ignored.

[Source](https://github.com/NixOS/nixpkgs/blob/32718c9992f5b49fbe6fb81bfc3dd3cc8316a3a8/nixos/modules/services/databases/victoriametrics.nix#L52)

**Test Case:**

```
{
  services.victoriametrics.enable = true;
}
```

Renders to:

```
ExecStart=/nix/store/dvbwzwkiyb729jxbcsly05zzdb8ljb3g-VictoriaMetrics-1.33.1/bin/victoria-metrics \
    -storageDataPath=/var/lib/victoriametrics \
    -httpListenAddr :8428
    -retentionPeriod 1
```

Which gives the following error messages in the logs:

```
Aug 24 14:22:40 thor systemd[1]: Started VictoriaMetrics time series database.
Aug 24 14:23:43 thor systemd[1]: /nix/store/gsmmm1yzb74w321r53q483idk1yjias6-unit-victoriametrics.service/victoriametrics.service:14: Missing '=', ignoring line.
```

Looks like the generated service config should be escaping newlines in the whole file.

**Maintainer:** @yorickvP

**System info:**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09.git.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
@yorickvP How did this ever work in https://github.com/NixOS/nixpkgs/pull/78038? There are clearly some `\` missing

**Comment by yorickvP** [comment]
Well, now I know why my `retentionPeriod` was ignored.
