### ISSUE TITLE
httpd.enablePHP option force PHP version

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#9623]
Hi,

With the following configuration to use php 5.4:

~~~~
      services.httpd = {
        enable = true;
        documentRoot = "/srv/http";
        enablePHP = true;
        extraModules = [
          { name = "php5"; path = "${pkgs.php54}/modules/libphp5.so"; }
        ];
      }
~~~~

The following `httpd.conf` file is generated:

~~~~
....
LoadModule php5_module /nix/store/fmwdjsmrkx9zlcf950mxhd9wkhi9wc3c-php-5.6.12/modules/libphp5.so
LoadModule php5_module /nix/store/jzh3ah2p1yz36jn62ybfr5m2jamxb2fk-php-5.4.44/modules/libphp5.so
....
~~~~

so PHP 5.6.12 is used. ([related code](https://github.com/NixOS/nixpkgs/blob/release-14.12/nixos/modules/services/web-servers/apache-httpd/default.nix#L339))

On the other side, skipping `enablePHP` setting like this:

~~~~
      services.httpd = {
        enable = true;
        documentRoot = "/srv/http";
        extraModules = [
          { name = "php5"; path = "${pkgs.php54}/modules/libphp5.so"; }
        ];
      }
~~~~

activate the desired PHP version(5.4), but no `php.ini` is generated and `phpOptions` setting is ignored. ([related code](https://github.com/NixOS/nixpkgs/blob/release-14.12/nixos/modules/services/web-servers/apache-httpd/default.nix#L649))

It would be nice to be able to use specific PHP versions with httpd.

**Comment by globin** [comment]
In configuration.nix you can change the default PHP version with an override:
```
  nixpkgs.config = {
    packageOverrides = {
      php = pkgs.php54;
    };
  };
```

**Comment by ericsagnes** [comment]
Works perfectly, Thanks!
I added the info to the [wiki](https://nixos.org/wiki/PHP).
