### ISSUE TITLE
qtquickcontrols-5.14.2 fails to build

### ISSUE THREAD

**Issue by dbeecham** [NixOS/nixpkgs#96268]
**Describe the bug**
682c2y33slg99jznhp1nzcymjs8jxdnb-qtquickcontrols-5.14.2 from latest nixpkgs fails to build

**To Reproduce**
1. Get "global flake:nixpkgs github:NixOS/nixpkgs" into your nix registry
2. nix shell nixpkgs#openscad

**Expected behavior**
Stuff builds

**Screenshots**

> @nix { "action": "setPhase", "phase": "qmakePrePhase" }
> qmakePrePhase
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> unpacking sources
> unpacking source archive /nix/store/5mbp0acfr2wx1vp8bymxhhbnf6da3599-qtquickcontrols-everywhere-src-5.14.2.tar.xz
> source root is qtquickcontrols-everywhere-src-5.14.2
> setting SOURCE_DATE_EPOCH to timestamp 1585386146 of file qtquickcontrols-everywhere-src-5.14.2/.QT-FOR-DEVICE-CREATION-LICENSE-AGREEMENT
> @nix { "action": "setPhase", "phase": "patchPhase" }
> patching sources
> @nix { "action": "setPhase", "phase": "configurePhase" }
> configuring
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/basiclayouts/basiclayouts.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/calendar/calendar.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/filesystembrowser/filesystembrowser.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/gallery/gallery.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/styles/styles.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/tableview/tableview.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/texteditor/texteditor.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/touch/touch.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/controls/uiforms/uiforms.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/dialogs/systemdialogs/systemdialogs.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/extras/dashboard/dashboard.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/extras/flat/flat.pro'...
> fixQtBuiltinPaths: Fixing Qt builtin paths in `./examples/quickcontrols/extras/gallery/gallery.pro'...
> QMAKEPATH=/nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev:/nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev:/nix/store/bp05fhg68za8qn8sgv8f35jl0mvj154d-qtdeclarative-5.14.2-dev:/nix/store/bp05fhg68za8qn8sgv8f35jl0mvj154d-qtdeclarative-5.14.2-dev:/nix/store/2ds37d6vqlnjygszrn4c229ch4azwj1a-qtsvg-5.14.2-dev:/nix/store/2ds37d6vqlnjygszrn4c229ch4azwj1a-qtsvg-5.14.2-dev
> qmake PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release
> Info: creating stash file /build/qtquickcontrols-everywhere-src-5.14.2/.qmake.stash
> Info: creating cache file /build/qtquickcontrols-everywhere-src-5.14.2/.qmake.cache
> @nix { "action": "setPhase", "phase": "buildPhase" }
> building
> build flags: -j8 -l8 SHELL=/nix/store/npfsrhkjww5q7sax7p7ijcrj3wlbrxn7-bash-4.4-p23/bin/bash
> cd src/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/src.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> make[1]: Entering directory '/build/qtquickcontrols-everywhere-src-5.14.2/src'
> cd controls/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/controls/controls.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> cd extras/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/extras/extras.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> cd extras/Styles/ && ( test -e Makefile.styles || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile.styles /build/qtquickcontrols-everywhere-src-5.14.2/src/extras/Styles/styles.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile.styles 
> cd dialogs/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/dialogs/dialogs.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> cd dialogs/Private/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/dialogs/Private/Private.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> cd widgets/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/widgets/widgets.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> make[2]: Entering directory '/build/qtquickcontrols-everywhere-src-5.14.2/src/extras/Styles'
> cd Flat/ && ( test -e Makefile || /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -o Makefile /build/qtquickcontrols-everywhere-src-5.14.2/src/extras/Styles/Flat/Flat.pro PREFIX=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_OUT=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DEV=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev NIX_OUTPUT_BIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2 NIX_OUTPUT_DOC=/nix/store/13xprpqkq8chhlcxd4ikrjbcm562mqan-qtquickcontrols-5.14.2-dev/share/doc/qt-5.14.2 NIX_OUTPUT_QML=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml NIX_OUTPUT_PLUGIN=/nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/plugins CONFIG+=release ) && make -f Makefile 
> make[2]: Entering directory '/build/qtquickcontrols-everywhere-src-5.14.2/src/dialogs/Private'
> /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -install qinstall qmldir ../../../qml/QtQuick/Dialogs/Private/qmldir
> /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -install qinstall plugins.qmltypes ../../../qml/QtQuick/Dialogs/Private/plugins.qmltypes
> g++ -c -pipe -O2 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtGui/5.14.2 -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtGui/5.14.2/QtGui -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtGui -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtCore/5.14.2 -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtCore/5.14.2/QtCore -isystem /nix/store/bp05fhg68za8qn8sgv8f35jl0mvj154d-qtdeclarative-5.14.2-dev/include/QtQml -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtNetwork -isystem /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/include/QtCore -I.moc -I/nix/store/74vgx9n01x5vrvd3mx53kiqrx0sh0521-mesa-20.1.5-dev/include -isystem /nix/store/pqvqlrqg76jwgcr7kh7abgr09xpzn3yg-icu4c-67.1-dev/include -isystem /nix/store/ki8k1a2pkpf862pxa0pms0j9mwjcb2xd-zlib-1.2.11-dev/include -isystem /nix/store/52r7kis7dcph1g9nl8874q69zi6cic0k-libjpeg-turbo-2.0.4-dev/include -isystem /nix/store/k36zxfggq83hvg14wp9lbgfbc5qdz3bq-harfbuzz-2.6.7-dev/include -isystem /nix/store/hfkbyfqjkizij1pb4wx4gfcw07qaqw51-openssl-1.1.1g-dev/include -I/nix/store/gwpvind68r3rb6i4aha59yfr4ygwjh00-libX11-1.6.8/include -I/nix/store/p5kqm5w7hc0rw6dx7ay1dl8f5ai23q4d-libXext-1.3.4/include -I/nix/store/4g3jai58qp0hs32vlfff48zmwbmww1qv-libXrender-0.9.10/include -I/nix/store/as6r0w9xvfwwd31hmnr0gpaf8di6qx4k-cups-2.3.3-dev/include -I/nix/store/jjwnwgk4n9w56vbg75rvgnxab8r15gqc-mariadb-connector-c-3.1.8/include -I/nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/mkspecs/linux-g++ -o .obj/qquickfontlistmodel.o qquickfontlistmodel.cpp
> ...
> g++ lots of stuff ...
> ...
> qmake -install lots of stuff...
> ....
> /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -install qinstall /build/qtquickcontrols-everywhere-src-5.14.2/src/controls/Styles/Base/images/check.png /nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml/QtQuick/Controls/Styles/Base/images/check.png
> /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -install qinstall /build/qtquickcontrols-everywhere-src-5.14.2/src/controls/Styles/Base/images/check@2x.png /nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml/QtQuick/Controls/Styles/Base/images/check@2x.png
> /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -install qinstall /build/qtquickcontrols-everywhere-src-5.14.2/src/controls/Styles/Base/images/knob.png /nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml/QtQuick/Controls/Styles/Base/images/knob.png
> /nix/store/ysxchaa5rjjg28vqlfsy4k479wwqviqp-qtbase-5.14.2-dev/bin/qmake -install qinstall /build/qtquickcontrols-everywhere-src-5.14.2/src/controls/Styles/Base/images/needle.png /nix/store/i9lljvzpgfxwj79nka6lb8cids7pgyvb-qtquickcontrols-5.14.2/lib/qt-5.14.2/qml/QtQuick/Controls/Styles/Base/images/needle.png
> mkdir: cannot create directory '/nix/store/w8k3lq0mxlwkjxqvak956p3jfrhhbmx7-qtdeclarative-5.14.2-bin/lib/qt-5.14.2/qml/QtQuick/Controls': Permission denied
> make[2]: *** [Makefile:1642: install_qmlcacheinst] Error 1
> make[2]: Leaving directory '/build/qtquickcontrols-everywhere-src-5.14.2/src/controls'
> make[1]: *** [Makefile:64: sub-controls-install_subtargets] Error 2
> make[1]: Leaving directory '/build/qtquickcontrols-everywhere-src-5.14.2/src'
> make: *** [Makefile:61: sub-src-install_subtargets] Error 2

**Additional context**
Not sure how to provide info on the nixpkgs flake

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.03.20200801.977000f (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `"nixos-20.03.2685.977000f149b"`
 - channels(dbe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ju1m** [comment]
May have been "fixed" by the revert merged in https://github.com/NixOS/nixpkgs/pull/96248

**Comment by Ma27** [comment]
I can confirm that this is fixed on master, I already had to build it locally :)
