### ISSUE TITLE
Is there the yarn2+ that yarnpkg / berry ？

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#96283]
**Project description**
_describe the project a little_
I want use yarn2 on NixOS.
**Metadata**

* homepage URL: https://github.com/yarnpkg/berry
* source URL: https://github.com/yarnpkg/berry
* license: mit, bsd, gpl2+ , ...
* platforms: linux

**Comment by bbigras** [comment]
I'm not sure if I'm using it in the optimal way but you can use yarn 2 with yarn 1. I use it on NixOS.

> Yarn 2 and later are meant to be managed on a by-project basis

```sh
# Move into your project folder:

cd ~/path/to/project

# Run the following command:

yarn policies set-version berry # below v1.22
yarn set version berry          # on v1.22+
```

https://yarnpkg.com/getting-started/install/

**Comment by prehonor** [comment]
> I'm not sure if I'm using it in the optimal way but you can use yarn 2 with yarn 1. I use it on NixOS.
> 
> > Yarn 2 and later are meant to be managed on a by-project basis
> 
> ```shell
> # Move into your project folder:
> 
> cd ~/path/to/project
> 
> # Run the following command:
> 
> yarn policies set-version berry # below v1.22
> yarn set version berry          # on v1.22+
> ```
> 
> https://yarnpkg.com/getting-started/install/

Yarn2 strictly uses ..yarnrc.yml  as a config file in your NIXOS？

**Comment by bbigras** [comment]
I guess. I'm not that familiar with how yarn 2 works but I add to edit that file to fix some problems with dependencies when using offline-mode (zero-Installs).

https://yarnpkg.com/advanced/qa/#which-files-should-be-gitignored

**Comment by prehonor** [comment]
> I guess. I'm not that familiar with how yarn 2 works but I add to edit that file to fix some problems with dependencies when using offline-mode (zero-Installs).
> 
> https://yarnpkg.com/advanced/qa/#which-files-should-be-gitignored

Yarn2 is diffrent from the old one  I used a few months ago ,when I used it through "npm install -g yarn@berry" and it had a global config file ".yarnrc.yml" which hasn't exist now. 
It works well so far in the newest way. Thanks , bbigras .
