### ISSUE TITLE
Add VokoscreenNG to nixpkgs

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#96286]
**Project description**
VokscreenNG is a user friendly Open Source screencaster for Linux and Windows.

**Metadata**

* homepage URL: https://github.com/vkohaupt/vokoscreenNG
* source URL: https://github.com/vkohaupt/vokoscreenNG
* license: gpl2
* platforms: linux

**Comment by SCOTT-HAMILTON** [comment]
Opened PR https://github.com/NixOS/nixpkgs/pull/96297/checks?check_run_id=1027814368.
If you can't wait for it to be merged, you can get it from my nur repository http://nur.nix-community.org/repos/shamilton/.

**Comment by SCOTT-HAMILTON** [comment]
*https://github.com/NixOS/nixpkgs/pull/96297

**Comment by romildo** [comment]
@SCOTT-HAMILTON thanks
