### ISSUE TITLE
murmur: skip build qt5 libraries

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#96305]
**Describe the bug**
When building the murmur package, the qt5 libraries are prebuilding.
How can I skip prebuilding qt5 libraries?

**Temporary solution**
Replace `qt5.mkDerivation` to `stdenv.mkDerivation`:
```
diff --git a/pkgs/applications/networking/mumble/default.nix b/pkgs/applications/networking/mumble/default.nix
index 8490c0509a1..4b4cbac79bf 100644
--- a/pkgs/applications/networking/mumble/default.nix
+++ b/pkgs/applications/networking/mumble/default.nix
@@ -16,7 +16,7 @@ assert iceSupport -> zeroc-ice != null;

 with stdenv.lib;
 let
-  generic = overrides: source: qt5.mkDerivation (source // overrides // {
+  generic = overrides: source: stdenv.mkDerivation (source // overrides // {
     pname = overrides.type;
     version = source.version;
```
cc @flokli @greizgh @Infinisil @mmahut @abbradar

**Comment by Infinisil** [comment]
Prebuilding?

**Comment by Infinisil** [comment]
What exactly are you seeing and how does it differ from what you expect?

**Comment by Izorkin** [comment]
If I building the murmur package, then the qt5 libraries are downloaded for its building. The murmur server does not use them.
If the qt5 libraries are not found at `cache.nixos.org`, they start buildied locally.
```
nix build -f ./default.nix murmur
[1/0/4 built] building qtquickcontrols-5.14.2 (buildPhase): /nix/store/jd400l0y85igavsj0q4jj6c76d8vn7j8-qtdeclarative-5.14.2-dev/bin/qmlcachegen -o ../../qml/QtQuick/Controls/Sta
```

**Comment by K900** [comment]
Murmur definitely does use Qt, at the very least QtCore.

**Comment by Izorkin** [comment]
I see, thanks for the explanation.
