### ISSUE TITLE
Question as to whether it would be possible to update to the lastest ZFS release candidate

### ISSUE THREAD

**Issue by shadowrylander** [NixOS/nixpkgs#96348]
Hello!

I'd like to know whether, as the title says, it would be possible to update the ZFS derivation to the latest release candidate, `Tag 2.0.0-rc1`, as it allows for `zstd` compression, and I am exceptionally eager to try it out; if not, how could I update the derivation in my own configuration?

Thank you kindly for your consideration on the matter!

**Comment by hmenke** [comment]
Crosspost: https://www.reddit.com/r/NixOS/comments/ihc2se/help_in_packaging_the_latest_zfs_release/
