### ISSUE TITLE
ld doesn't find libevent 

### ISSUE THREAD

**Issue by sucrecacao** [NixOS/nixpkgs#96356]
Tried to compile a crystal binary, but it couldn't find the libevent library that I installed with nix.
I found the solution by adding an alias the library with the following symlink:
`sudo ls -s /lib/x86_64-linux-gnu/libevent-2.1.so.6 /lib/x86_64-linux-gnu/libevent.so`

For more details: https://github.com/alexherbo2/snippets/issues/1

So the problem is solved and this could be closed. But I already encountered similar library problem with nix, so I'm wondering if I am missing something when I'm installing package  or is it nix that miss creating the right symlink ?

**Comment by symphorien** [comment]
you are supposed to run the compiler inside nix-shell with appropriate dependencies available: https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F

**Comment by jonringer** [comment]
having a `/lib` would mean impurity, which is someting that nix/nixpkgs/nixos tries to stay clear of, @symphorien suggestion is correct. You should pass the build store paths.

**Comment by sucrecacao** [comment]
Thanks you both for your quick answer

> you are supposed to run the compiler inside nix-shell with appropriate dependencies available: https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F

I think the link you sen. I put it in the category of documentation that is only clear for people who don't really need the documentation ;)
I'm not a compiler and c/c++ expert, I just want to  `sudo make install` to run smoothly. 
In ubuntu the workflow is usually:
```
sudo apt install dep1 dep2 ...
sudo make install
```
What is the equivalent with nix ?

**Comment by jonringer** [comment]
For just building?
```
nix-shell -p dep1 dep2 ...
make
```

for installing, I would look at https://www.youtube.com/watch?v=LiEqN8r-BRw where I package a small c application locally

**Comment by sucrecacao** [comment]
Thanks @jonringer !
I though for building it would simply be:
`nix-env -i libfoo`
I know it's not recommanded because it's slow, but it work fine for me !
