### ISSUE TITLE
Request to add ocaml-print-intf

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#96376]
**Project description**

Pretty prints a compiled OCaml interface file into the corresponding human-readable OCaml signature.

**Metadata**

* homepage URL: https://github.com/avsm/ocaml-print-intf
* source URL: https://github.com/avsm/ocaml-print-intf
* license: ISC
* platforms: unix

**Comment by romildo** [comment]
Still relevant.

**Comment by NerdyPepper** [comment]
Closed in  #134110.
