### ISSUE TITLE
Unknown SSL protocol error in connection to fedorahosted.org:443

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#9640]
I am relatively new to NixOS. While installing a very simple nixos configuration with bare minimum hardware.nix and openssh service, I am receiving the above mentioned error. It complains about following:
"error: cannot download liberation-fonts-ttf-2.00.1.tar.gz from any mirror builder for /nix/store/1vigkpqw48s1vqryzkq8p...."
I have already checked that:
- Internet connection is connection is fine.

**Comment by vcunat** [comment]
```nix-prefetch-url https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz``` works for me fine. Are you sure it wasn't just a temporary error, likely on the side of the server?

**Comment by rowhit** [comment]
Thanks. Sorry for putting this silly thing. I should have directly pinged the server where it was fetching from. I am not able to ping that server.
