### ISSUE TITLE
`composeExtensions` cannot be used for flake `overlay` output

### ISSUE THREAD

**Issue by chkno** [NixOS/nixpkgs#96405]
**Describe the bug**
`composeExtensions` is the standard way to compose overlays.  `foldl' composeExtensions`, in particular, is extremely useful for making the old-style `~/.config/nixpkgs/overlays` available as a flake overlay.

`nix flake check` requires the `overlay` output's parameter names to be `final` and `prev`. `composeExtensions`'s parameter names are `self` and `super`, which causes `nix flake check` to fail.

**To Reproduce**

    git init cant-composeExtensions
    cd cant-composeExtensions
    cat > flake.nix <<EOF
    {
      inputs = { nixpkgs.url = "github:NixOS/nixpkgs/nixos-20.03"; };
      outputs = { self, nixpkgs, }: {
        overlay = nixpkgs.lib.composeExtensions (final: prev: { }) (final: prev: { });
      };
    }
    EOF
    git add flake.nix
    nix flake check

**Expected behavior**
`nix flake check` succeeds.

**Actual behavior**

    error: --- Error ------------------------------------------ nix
    overlay does not take an argument named 'final'

**Additional context & Notify maintainers**
2019 https://github.com/NixOS/nix/commit/dc3f52a1447df8523f44c89e25e48e8b7f5341a0 by @edolstra created this `final`/`prev` check.
2017 https://github.com/NixOS/nixpkgs/commit/0a15af2ed170b30636a264b6b535a9327effddc5 by @shlevy created `composeExtenions`
2015 https://github.com/NixOS/nixpkgs/commit/405fda497ae1943c6ca3dab783687a01ff63c04f by @peti brought the `self`/`super` naming convention into `lib`
2011 https://github.com/NixOS/nixpkgs/commit/3e0ac9b040b0a15041faa74e7ffa87cc705e0f96 by @kosmikus introduced the `self`/`super` naming convention.

**Possible fixes**
https://github.com/chkno/nixpkgs/commit/9ae2e286a1700abf0377878ba7a3bdcf5330e706  Δ10 Narrowly change `composeExtension`'s parameter names so this works, leaving `composeExtension` using a different naming convention than the rest of nixpkgs.
https://github.com/chkno/nixpkgs/commit/c64f63385beff3b03916b485a756091178ddaec8 Δ4620 Rename `self`/`super` to `final`/`prev` treewide.
https://github.com/NixOS/nix/commit/ce6980746b4b557b427828b39743ac79f699a3bc Δ4 Allow `self`/`super` in `nix flake check`.

**Comment by sellout** [comment]
This seems to have been fixed in #135794.
