### ISSUE TITLE
Packaging Request: spicetify-cli

### ISSUE THREAD

**Issue by svrana** [NixOS/nixpkgs#96419]
** spicetify-cli

Allows users to change css, javascript used by the proprietary spotify client

**Metadata**

* Project page:  https://github.com/khanhas/spicetify-cli
* License: gpl3
* Platforms: linux & darwin

spicetify-cli works by making changes to software distributed in the spotify client (css/javascipt).  I'm imaging support for this program in nixpkgs would look somewhat like spicetify-cli's [flatpak](https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-flatpak) support where users would have to tell spicetify-cli where the spotify client files are located. Course this would break as spotify is updated, but that might be a good first step.

Happy to take a swing at this. Is there an existing package that does something similar?

**Comment by aaronjanse** [comment]
Ooh! I have this packaged! I'll try to pull it from my dotfiles
