### ISSUE TITLE
ctypes_sh segfaults after glibc update

### ISSUE THREAD

**Issue by singron** [NixOS/nixpkgs#96428]
**Describe the bug**
ctypes_sh (ctypes.sh) segfaults after sourcing ctypes.sh file.

**To Reproduce**
1. Write this content to `ctypes-shell.nix` in the nixpkgs root
```nix
let
  pkgs = import ./. {};
in
  pkgs.mkShell {
    shellHook = ''
      . ${pkgs.ctypes_sh}/bin/ctypes.sh
    '';
  }
```
2. `nix-shell ./ctypes-shell.nix`
3. See output: `Segmentation fault (core dumped)`

**Expected behavior**
ctypes.sh loads ctypes.so, which defines some extra builtins but should appear to do nothing and not crash.

**Screenshots**

**Additional context**
See this gist for a backtrace taken with gdb and a git bisect log.
https://gist.github.com/singron/15aa08eb168bb97313b8976cbf5c16ea

From the git bisect:
* first bad commit: [4a78b2b04f3f63eaf1c29dca12d44d820bb9374a] glibc: 2.30 -> 2.31

**Notify maintainers**

@tadeokondrak
**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.12-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixpkgs-20.09pre221814.10100a97c89"`
 - channels(eric): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ctypes_sh
# a list of nixos modules affected by the problem
module:
```

**Comment by tadeokondrak** [comment]
Hm, I don't remember seeing this. It works for me, though. Please reopen if it's still broken.
