### ISSUE TITLE
Amazon has killed KindleGen

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#96439]
[Amazon is no longer hosting KindleGen](https://www.amazon.com/gp/feature.html/?docId=1000765211). Consequently, the [nix kindlegen package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/kindlegen/default.nix) is broken. I suppose we need to choose whether to remove the package or find a mirror?

CC maintainer: @peterhoeg

Side notes: Sadly, its replacement, [Kindle Previewer](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261), has no Linux support. But on a more positive note, there are other programs that can produce mobi files, some mentioned in [this discussion](https://news.ycombinator.com/item?id=24275231).

**Comment by peterhoeg** [comment]
I suggest we just drop it. Considering that kindlegen was under an unfree license, we're probably not allowed to distribute it, so let's just blow it away with a release note entry that mentions some alternatives.

**Comment by Mic92** [comment]
My current recommendation for NixOS is to use calibre for conversion. It also has commandline tools for scripting.
