### ISSUE TITLE
Creating LVM RAID fails due to missing device-mapper target

### ISSUE THREAD

**Issue by akamaus** [NixOS/nixpkgs#96433]
**Describe the bug**
Besides regular volumes Logical Volume Manager also support software RAID (man 7 lvmraid). Unfortunately, only raid0 works.

**To Reproduce**
1. sudo vgcreate vg_test /dev/sda1 /dev/sdb1
2. sudo lvcreate -n tst_raid1 vg_test --mirrors 2  
3.  Error `raid1: Required device-mapper target(s) not detected in your kernel.` is displayed

**Expected behavior**
A logical volume mirroring it's contents to two physical volumes should be created.

**Additional context**
Trying to create different raid types results in similar errors. There are some reports saying you should manually load kernel modules required. i tried `modprobe raid0 raid1 raid456`, didn't make a difference.
https://www.suse.com/support/kb/doc/?id=000017819

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.git.041aaf644a0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `""`
 - channels(test): `""`
 - channels(dvyal): `""`
 - nixpkgs: `/home/dvyal/nixpkgs`
```
Built with a couple of innocent commits on top of the official commit ab3adfe1c769

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment]
Try `modprobe dm_mirror` (or `dm_raid` for other RAID modes) that should work IIRC.

**Comment by akamaus** [comment]
`modprobe dm_raid` works, indeed, thanks! 
To others. Please note, there are other similar looking modules like `raid1`. Loading them doesn't fix the problem.
