### ISSUE TITLE
Okular now extremely slow at rendering EPUB documents

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#9644]
Flipping a page now takes several seconds on some documents. This used to be fast until quite recently. E.g. /nix/store/ldw6mbpz0gkp63gaxq2zpknzvvb46zb8-okular-4.14.3 (KDE 4.14.9) is fast, /nix/store/4p1hdlxpqn56bzgr0lp85jvicsqmrb36-okular-4.14.3 (KDE 4.14.10) is slow.

**Comment by vcunat** [comment]
The KDE5 version is also extremely slow for me. (I much preferred fbreader personally anyway.) 

A quick search showed no references to epub slowness elsewhere. @ttuegel: any ideas?

**Comment by ttuegel** [comment]
The KDE 5 version is the same (Qt 4 based) for now, but I don't know why either slowed down.

**Comment by nortexoid** [comment]
I just noticed the slowness of epub on my relatively fast quad core that is faster with much larger pdf files. Okular version is 0.23.2 on Qt version 4.8.6 (though I'm running plasma 5.5.3, qt version 5.5.1)

**Comment by layus** [comment]
Searching this over the internet now yields some similar issues and one bug in the KDE bug tracker https://bugs.kde.org/show_bug.cgi?id=350798.

Apparently disconnected network printers may cause issues.
Do you still experience the slowness when network is disabled or these printers removed ?
If not, the only hint in the above bug is that our build may be wrong... Not very helpful.

Anyway, could you attach examples of such slow files ?

**Comment by AlexYeCu** [comment]
>Anyway, could you attach examples of such slow files ?

I can.
http://www.spacians.net/files/spacians.epub
22 seconds to open, scrolling is slow.
Tested at Fedora 22 (so, this bug is distributive-independent), core2duo(3166) + 4Gb RAM.
Nexus 7 with Android 6 opens this file in ~8 seconds (tested DocumentViewer and CoolReader).

**Comment by AlexYeCu** [comment]
BTW, I have no problem with opening PDF, even if they are large or have a lot of pictures embedded. I have no printers in current system also.

**Comment by layus** [comment]
Thanks @AlexYeCu.
@edolstra, If this is really distribution independent, then we should file a bug at https://bugs.kde.org and close this issue.

**Comment by edolstra** [comment]
@layus The slowness also happens on systems with no configured printers.

**Comment by AlexYeCu** [comment]
@edolstra
But where, how and why to configure printers at the system without printers?

**Comment by layus** [comment]
@AlexYeCu For the current matter, shutting the network down should do it.

**Comment by AlexYeCu** [comment]
@layus, shutting down the network does not make Okular fster. May be there are some different bugs? Just checked: Okular opens spacians.epub in 20+ seconds with and without network, calibre viewer do the same thing in about 3 or less seconds.
Strace shows that Okular freezes  after:
libepub (II):   adding nav point item->navPoint-81 ch80.xhtml (d:1,p:81)
libepub (II):   finished parsing nav map
libepub (II):   finished parsing toc
libepub (II):   found item cover
libepub (II):   found item title_page
libepub (II):   found item ch1
…
libepub (II):   found item ch80
So, all parts of the book parsed and found.
The other thing I`ve noticed, Calibre viewer does not show a cover and starts almost instantly. And Okular shows cover, but starts slow…
Do not know if this information useful or not.

**Comment by AlexYeCu** [comment]
Well, deleting pictures and styles do not make Okular faster…

After removing Misc/com.apple.ibooks.display-options.xml:

libepub (II):   found item ch80
libepub (II):   parsing guides

But still slow.

**Comment by layus** [comment]
I created a bug report @ KDE: https://bugs.kde.org/show_bug.cgi?id=359932 after reproducing the issue on archlinux.
My analysis with KCacheGrind seems to indicate that the application spends a lot (66%) of time in libfreetype.so, but it is unclear who calls these functions and why.

**Comment by edolstra** [comment]
@layus Thanks, that should be very helpful. BTW, did you run that on 15.09 or master?

**Comment by layus** [comment]
@edolstra I ran my tests on Arch mainly (my main OS at work), but I just tried again with NixOS 16.03pre75806.77f8f35 (Emu). Both nixos.kde{4,5}.okular have the issue.

**Comment by layus** [comment]
The upstreambug is open and draw some attention.
They will need testers at some point, so you should definitely subscribe to that bug: https://bugs.kde.org/show_bug.cgi?id=359932

I also think we should close this issue, as it is not related with nix/nixos.

**Comment by ttuegel** [comment]
Thanks! I followed the issue upstream.

**Comment by edolstra** [comment]
Are you sure this is the same issue? I'm talking about a performance regression, while that upstream issue talks about some particular epubs being slow.

**Comment by layus** [comment]
@edolstra Could you check the qt version used by the different okular versions. I think the issue may come with Qt4.8.7.
I have narrowed the issue between 7acbdcd02b52fd99a826b16c832888dbff64088f and 317dd06aa438fb2e49a578a7bbefc5ed677cdc13... But then the cache misses derivations, and I do not want to bisect local qt/kde builds.

The range contains 16b40c7b which is the most probable cause for the issue.

I have cherry-picked 16b40c7b on top of 7acbdcd02b52fd99a826b16c832888dbff64088f, and we will see if it makes okular freeze.

Hang tight !

PS: I think the upstream issue is related to yours, as the freeze described appeared nearly at the same time as your issue. As I see it,  "Okular freezes on big files" == "Okular is slow on normal files".

**Comment by edolstra** [comment]
The first path (`/nix/store/ldw6mbpz0gkp63gaxq2zpknzvvb46zb8-okular-4.14.3`) was indeed Qt 4.8.6. The second path is no longer available so I can't check for sure if it was using 4.8.7.

Thanks for looking into this!

**Comment by edolstra** [comment]
And indeed running the fast Okular (`/nix/store/ldw6mbpz0gkp63gaxq2zpknzvvb46zb8-okular-4.14.3`) with `LD_LIBRARY_PATH` set to Qt 4.8.7 (to be precise `/nix/store/msfjykq61a6mjj8sajaf896r98nk3nkp-qt-4.8.7/lib`) makes it slow :-)

**Comment by layus** [comment]
Nice ! Now, we only have to bisect qt v4.8.6 to v4.8.7 :grinning:

Fear not:
```
qt$ git log v4.8.6..v4.8.7 --pretty=oneline | wc -l   
164
```

**Comment by vcunat** [comment]
Only about 8 more steps then :-)

**Comment by layus** [comment]
The problem does not seem to come from Qt itself. I have cherry-picked 16b40c7 on top of 7acbdcd, and okular is fast. Something else happens between 7acbdcd and 317dd06.

Any idea how to continue debugging ?

**Comment by AlexYeCu** [comment]
I have rebuilded okular from Fedora 20 okular-14.12.3 and downgraded qt-4 to 4.8.6 from 4.8.7. Opening of epubs is still too slow, but a bit faster: 17 seconds vs. 22 seconds. So, may be there are more than one regression causes the slowdown? Unfortunately the experiment is not clean enough: my system got some updates after previous attempt.

**Comment by layus** [comment]
This is also my feeling after many build attempts. The okular as an epub reader has room for improvement :-). I would recommend to use calibre viewer instead.
Okular's implementaion relies on the bloated QTextDocument, a class that can manage _enriched_ html-like documents, undo-redo and more...
Most probably that class received extra features (or even bugfixes) at the cost of efficiency.
