### ISSUE TITLE
Konqueror location bar does not work

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#9645]
To reproduce:
- Start konqueror.
- Type a URL.
- Press Enter.
- Nothing happens.

This is KDE 4.14.10 on NixOS 15.09.179.93a41c5.

**Comment by vcunat** [comment]
It does work for me on 15.09 (2a237e7ab3 and a few irrelevant commits on top). I have `kde5.enable = true`, but the version is still 4.14.10 anyway.

**Comment by davidak** [comment]
It does work on 16.03.948.a96c308 (Graphical live CD, 64-bit).

**Comment by vcunat** [comment]
I can reproduce the problem with kde4 baseapps on master when I don't have kde4 enabled system-wide. In that case it's probably missing some KIO or other plugin, but I don't think we ever had that with kde4.

**Comment by Profpatsch** [comment]
triage: still reproducible?
