### ISSUE TITLE
linux-5.9.0-rc2: NixOS stage1 boot does not recognize disk

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#96466]
First of all: of course this is not supported and I cannot expect this to work. I'm just opening this issue to record my progress and make it findable in search engines :)

When I switch to linux versions 5.9.0-rc1 (vanilla) or 5.9.0-rc2 (vanilla from the drm-tip branch), NixOS does not get through the stage1, but produces the following error instead of asking for my disk password:

```
nvme nvme0: failed to set APST feature (-19)
```

-19 is the Linux error code `ENODEV`/'No such device'.

I tried setting kernel parameters `nvme_core.default_ps_max_latency_us=5500` (or 200 or 0), but that didn't have any effect.

Reading https://nixos.org/nixos/manual/#sec-boot-problems and adding `boot.shell_on_fail` to `kernelParams` gave me an opportunity to look at dmesg, which revealed the attached trace
![IMG_20200827_183231](https://user-images.githubusercontent.com/131856/91470595-2fec2e00-e895-11ea-910d-10bfbb39dd7f.png). Some highlights:

```
WARNING: CPU: 10 PID: 7 at mm/page_alloc.c:4864 __alloc_pages_nodemask
Workqueue: nvme-reset-wq nvme_reset_work [nvme]
RIP: 0010:__alloc_pages_nodemask
Call Trace:
  dma_direct_alloc_pages
  nvme_alloc_queue
  nvme_reset_work
  ? enqueue_task_fair
  ? check_preempt_curr
  ? nvm_irq_check
nvme nvme0: Removing after probe failure status: -12
nvme nvme0: failed to set APST feature (-19)
```

Linux error code -12 is 'Out of memory', which matches the fact that the trace ends in dma_direct_alloc_pages.

The warning at mm/page_alloc.c:4864 is:

```
        /*
	 * There are several places where we assume that the order value is sane
	 * so bail out early if the request is out of bound.
	 */
	if (unlikely(order >= MAX_ORDER)) {
		WARN_ON_ONCE(!(gfp_mask & __GFP_NOWARN));
		return NULL;
	}
```

**Comment by Emantor** [comment]
If this happens on a vanilla upstream kernel, it's usually worth it to start a bisect and post about it on the LKML.

**Comment by raboof** [comment]
> it's usually worth it to start a bisect

Makes sense, doing that now.

It's pretty time-consuming since 'nixos-rebuild switch' starts the build from scratch each time, but that's probably still the easiest way to do it?

**Comment by raboof** [comment]
The first failing commit was https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=61f3b89630973037f67d8e25e5d26e80a51a7b37. I'm not sure why that's mixing `unsigned int` and `u16`, but my C is rusty, might be fine.

Based on that I found a related fix at https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2268336.html which, while it didn't make it to 5.9.0-rc2, is actually available on master.

So lessons learned are:
* pinpointing the introduction of the problem by bisecting is pretty easy (though time-consuming)
* but check master first :)
