### ISSUE TITLE
qbittorent trayicon doesn't show correctly on sway

### ISSUE THREAD

**Issue by Kazimazi** [NixOS/nixpkgs#96482]
**Describe the bug**
I'm using swaywm and when I have qbittorent opened I get a default looking trayicon instead of what it supposed to be.

**To Reproduce**
1. Start qbittorent.

**Expected behavior**
Qbittorent icon appears.

**Screenshots**
[Pic here](https://imgur.com/QEANb4K). The right icon belongs to qbittorent.

**Notify maintainers**
@Anton-Latukha

**Metadata**
```
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.17, NixOS, 20.03.2849.feff2fa6659 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2849.feff2fa6659, nixos-unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
setting QT_QPA_PLATFORMTHEME to qt5ct and setting a icon theme in qt5ct is atleast a workaround

**Comment by Kazimazi** [comment]
Indeed it works as a workaround. Although, it messed up icons in the gui.

**Comment by Kazimazi** [comment]
Here comes a weird thingy. When I use magnet link to open qbittorent the correct trayicon loads.

**Comment by Kazimazi** [comment]
updated my system, and I cannot reproduce anymore
