### ISSUE TITLE
w3m: fails to build with mouseSupport

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#9652]
The build fails with this error:

    terms.o: In function `do_getch':
    /tmp/nix-build-w3m-0.5.3.drv-0/w3m-0.5.3/terms.c:1915: undefined reference to `Gpm_Wgetch'

Full log [here](http://nixpaste.lbr.uno/9ENnSW4r?sh)

**Comment by pSub** [comment]
You have to build gpm with curses support. E.g. `gpm = gpm.override { inherit ncurses; };`. Maybe we should add a variant of w3m with mouse support.
