### ISSUE TITLE
KWin missing window resize cursor

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#9659]
KWin does not display the correct resize cursor when one hovers over the edge of the window. The window may still be resized, but the normal cursor is displayed.

**Comment by Mathnerd314** [comment]
Which version of KDE is this? I have a working resize cursor in kde4 revision https://github.com/NixOS/nixpkgs/commit/bd84ebaa1e0359f41350e053ed24592b169b5714

**Comment by ttuegel** [comment]
Plasma 5.3.2

**Comment by ttuegel** [comment]
This was fixed by the upgrade to Plasma 5.4.
