### ISSUE TITLE
Packaging request: update OpenRA

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#96600]
**Project description**

OpenRA is already in nixpkgs, but the stable release is outdated by about a year (20200503 vs 20190314).
I tried to do the basic things myself (updating hashes, fixing up some stuff related to upstream changes), but I ran into a mono/msbuild wall where I don't understand what is going on. Also, I only looked into the engine part - maybe the mods also need updating?

@fusion809 @msteen @rardiol Would you be able to take a look at this?

Known required changes:
* 'default' make target is now 'all'
* The build now needs msbuild
* ???

**Comment by SFrijters** [comment]
FWIW, I made another attempt, had to put in a bunch of NuGet stuff to get dependencies resolved, but now it seems that the NuGet available in nixpkgs is too old. And I don't know what other issues are still lurking behind that.
If anyone wants to pick this up, feel free to look at https://github.com/SFrijters/nixpkgs/tree/openra .

**Comment by turbio** [comment]
Heyo looks like the openra nix package is coming up on 3 years out of date :disappointed:. Would really like to get this updated as it's not very useful so far behind release.
I can update it to pull the latest AppImage release if you guys are alright not building from source.

**Comment by louwers** [comment]
Not stale!

**Comment by jtrees** [comment]
@SFrijters You interested in taking another stab at this?

**Comment by SFrijters** [comment]
@jtrees Sorry, no. I have neither the time nor the inclination to look into dotnet packaging at the moment.

**Comment by mdarocha** [comment]
Hey! I started work on that in https://github.com/NixOS/nixpkgs/pull/220888

Unfortunately due to amount of changes, I had to completely redo how the packaging is done. So the out-of-tree mods will need another PR in the future.
