### ISSUE TITLE
Plasma "Add Widgets" menu is empty

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#9660]
The "Add Widgets" menu is empty in Plasma. The desktop and panel are still populated with widgets, so it appears that Plasma can find the widgets and the problem is with the menu itself.

**Comment by FRidh** [comment]
Alternatives (e.g. for the menu) are also not available.

**Comment by ttuegel** [comment]
This was fixed in the upgrade to Plasma 5.4.
