### ISSUE TITLE
`tests.systemd-networkd` occasionally breaks

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#96642]
**Describe the bug**
After fixing the the evaluation of the [`systemd-networkd` test](https://github.com/NixOS/nixpkgs/blob/d416facd395254666e0333f609520d86e64059a7/nixos/tests/systemd-networkd.nix) in d416facd395254666e0333f609520d86e64059a7 I realized that it occasionally breaks with the following error:

```
node1: output: PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.

--- 10.0.0.2 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4085ms


error:
Traceback (most recent call last):
  File "/nix/store/b6m9jif1kib2dqc6fy2ym31vzs4f7hhd-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 830, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/nix/store/b6m9jif1kib2dqc6fy2ym31vzs4f7hhd-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 363, in succeed
    raise Exception(
Exception: command `ping -c 5 10.0.0.2` failed (exit code 1)
cleaning up
killing node1 (pid 6)
killing node2 (pid 18)
error: --- Error ------------------------------------------------------------------------------- nix-build
error: --- Error --- nix-daemon
builder for '/nix/store/g14icd814yvak6syxjimgc6g8y459ki1-vm-test-run-networkd.drv' failed with exit code 1
```

Please note that the functionality isn't broken per se, on 19c3507ab1a I managed to successfully build it as `/nix/store/a61kx4fisa19hwipx54zhv4r87r3v39p-vm-test-run-networkd`.

**Notify maintainers**
cc @flokli @NinjaTrappeur

**Comment by JJJollyjim** [comment]
I'm guessing that having the pings be `wait_until_succeeds` would resolve this, unless we want to assert that `wait-online.service` actually ensures that the peers are fully connected?

**Comment by Ma27** [comment]
No it doesn't, I already tried this out, the command times out then. I guess that sometimes the `wg0` isn't configured properly.

**Comment by NinjaTrappeur** [comment]
The issue is coming from the private key (/run/wg-priv), for some
reason, it looks like networkd is sometimes trying to load it to
wireguard before the systemd tmpfile gets linked.
