### ISSUE TITLE
securefs is broken

### ISSUE THREAD

**Issue by sephii** [NixOS/nixpkgs#96658]
**Describe the bug**
securefs doesn't work on Linux >= 5.4. See https://github.com/netheril96/securefs/issues/87 for details. [A fix](https://github.com/netheril96/securefs/commit/e5b9e5d41a6dcdee60ab4a18b46b9a0c6475ba21) was released in 0.11.1 and 0.9.0.

**To Reproduce**
1. Try to mount a securefs directory, eg. `securefs mount /mnt/foobar ~/foobar

You'll get `fuse: reading device: Invalid argument` (see the bug report above for discussion about the bug).

**Expected behavior**
The directory gets correctly mounted.

**Notify maintainers**
There are no maintainers in the file. The last person who did a commit was @nckx in 2016. I'd be happy to submit a PR.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.03.2835.ebf59916232 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(sephi): `""`
 - channels(root): `"nixos-20.03.2835.ebf59916232, nixos-hardware, taxi"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:

pkg: tools/filesystems/securefs

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/97024
