### ISSUE TITLE
fwupd fails to build since systemd 246 upgrade

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#96663]
**Describe the bug**
fwupd is [failing to build](https://hydra.nixos.org/build/126218420/nixlog/1). After it installs `fwupd.service` to the correct path, it tries to install `fwupd.shutdown` to an incorrect path in systemd’s prefix rather than its own.

I bisected this to commit 2865490dc23d240fad0dc3eeb7102d10bd259e3c “systemd: 245.7 -> 246” (#94354).

```
Installing /build/fwupd-1.4.5/build/data/fwupd.service to /nix/store/r464h503syq81w6vsmkp7yz4yzxhcv8w-fwupd-1.4.5/lib/systemd/system
Installing /build/fwupd-1.4.5/build/data/fwupd.shutdown to /nix/store/5k9cqf17a0hn2x2yj9fdrszd3syy86f3-systemd-246/lib/systemd/system-shutdown
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
pkexec must be setuid root
FAILED: meson-install 
/nix/store/cg1lyk9naby9pl4srl3igi5cca6qjzqc-meson-0.55.1/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
builder for '/nix/store/d3bl0l7354gzbxdqhw8nja1kdml5alga-fwupd-1.4.5.drv' failed with exit code 1
```

**To Reproduce**
`nix build -f . fwupd`

**Notify maintainers**
@flokli 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.57, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(anders): `""`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [fwupd, systemd]
# a list of nixos modules affected by the problem
module: []
```

**Comment by arianvp** [comment]
Sigh. I wish our CI would complain loudly if we break things that depend on other thing inside PRs...

**Comment by vcunat** [comment]
That's not really practical.  For example, with systemd the rebuild amount is quite large.

**Comment by jtojnar** [comment]
Yup, systemd renamed the pkg-config variables https://github.com/systemd/systemd/commit/4908de44b0a0409f84a7cdc5641b114d6ce8ba03 so this commit no longer works:

https://github.com/fwupd/fwupd/commit/463db5162fe4f6fea417973ff95a44ed51ec6402

**Comment by jtojnar** [comment]
Could you try if https://github.com/fwupd/fwupd/compare/master...jtojnar:patch-1 fixes it?

**Comment by andersk** [comment]
@jtojnar Yes, that makes it build. (Although I’m curious why the other copies of `rootprefix` in the adjacent lines aren’t affected.)

**Comment by jtojnar** [comment]
Opened an upstream PR then https://github.com/fwupd/fwupd/pull/2344

**Comment by jonringer** [comment]
> Sigh. I wish our CI would complain loudly if we break things that depend on other thing inside PRs...

I think i ran `nixpkgs-review` off the PR, and it's around 17k rebuilds. 

The other issue is that there's 1000's of already failing packages, it's very difficult to know what failed as a result of your change.
