### ISSUE TITLE
Darwin: CF-855.17 is broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#9674]
hydra.nixos.org has Darwin build errors (such as `cabal2nix`) because `CF` is broken in `master`: http://hydra.nixos.org/build/25570197. Does anyone know what that package is and how it might be possible to fix it?

**Comment by lethalman** [comment]
Being a darwin error is not to be a 15.09 milestone bug.

**Comment by domenkozar** [comment]
Are there any benefits fixing darwin stuff on 15.09? As far as I know darwin users just use master branch

**Comment by vcunat** [comment]
Yeah, I haven't noticed much interest in changing it. Also, our Hydra is relatively weak on Darwin platform, so having another branch to build might not go too well.

**Comment by peti** [comment]
This issue is really bad for Haskell users on Darwin. `cabal2nix` won't build because of `CF`, and neither will `stack`. It would be great if someone with access to a Mac could take a look at http://hydra.nixos.org/build/25570197 and fix that. @cstrahan, @jwiegley, or @copumpkin maybe?

**Comment by jwiegley** [comment]
@copumpkin Knows far more about the Frameworks stuff than I do.

**Comment by copumpkin** [comment]
I'll try to take a look this weekend if nobody gets to it first.

**Comment by henrytill** [comment]
This has since been fixed.  See http://hydra.nixos.org/build/27208901, for example.

Close?
