### ISSUE TITLE
Overriding files in /etc/tmpfiles.d is now more difficult

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#96755]
## Issue description

With #93073 merged overriding files in `/etc/tmpfiles.d` with e.g.: `"tmpfiles.d/tmp.conf".source = lib.mkForce (pkgs.writeTextFile ...` isn't possible anymore. See https://github.com/NixOS/nixpkgs/pull/93073#discussion_r468475818 for a discussion of this.

A workaround is to patch Nixpkgs but that isn't really desirable. I've decided to open this issue to make this easier to discover / search for and track the progress.

**Comment by orivej** [comment]
I have made a fix, will open a PR when I'll figure out the commit message :)
