### ISSUE TITLE
Can no longer use ibus-anthy

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#9676]
I noticed that the ibus-anthy package has been updated recently (though just for a change of version). It seems to have coïncided with it not appearing to be available in IBus.

I'm not running GNOME, and have the following in /etc/nixos/configuration.nix:
```nix
programs.ibus = {
  enable = true;
  plugins = [
    pkgs.ibus-anthy
    #pkgs.ibus-hangul
    pkgs.ibus-table
    pkgs.ibus-table-others
  ];
};
```
ibus-table and ibus-table-others were packaged by me and never did work. IBus runs perfectly fine, but just with no useful input methods.

**Comment by laMudri** [comment]
Probably worth mentioning @gebner.

**Comment by gebner** [comment]
It seems that some variables in `anthy.xml` are not being expanded:
```
» grep exec $IBUS_COMPONENT_PATH/anthy.xml
        <exec>${exec_prefix}/libexec/ibus-engine-anthy --ibus</exec>
        <engines exec="${exec_prefix}/libexec/ibus-engine-anthy --xml" />
```
