### ISSUE TITLE
spacefm: warnings on startup, missing dependencies, thumbnails don't work

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#9678]
I installed spacefm on nixos-unstable channel. I observed a couple of problems:
1. Most of the program icons are missing.
2. Thumbnails do not work. I tried view -> preferences, click "show thumbnails" asked to edit /etc/spacefm and said it was going to ask for a root password. After that thumbnails still did not work but the checkbox shows checked.

**Comment by ryantm** [comment]
Here is a log https://gist.github.com/ryantm/066e581d1ccc607c8c61

**Comment by ryantm** [comment]
Adding

````
    hicolor_icon_theme
    gnome3.adwaita-icon-theme
````
as dependencies, fixes the icon warnings.

**Comment by ryantm** [comment]
Turning on the at-spi2-core service fixes the accessibility warning.

````
  services.gnome3.at-spi2-core.enable = true;
````

**Comment by ryantm** [comment]
This looks relevant to 
````
** (.spacefm-wrapped:14409): WARNING **: No root settings found in /etc/spacefm/  Setting a root editor in Preferences should remove this warning on startup.   Otherwise commands run as root may present a security risk.
````
 https://github.com/IgnorantGuru/spacefm/issues/577

**Comment by lethalman** [comment]
Is this issue fixed by #9681 ?

**Comment by ryantm** [comment]
@lethalman Unfortunately, no. I didn't figure out how to fix the thumbnailing.

**Comment by ryantm** [comment]
On my system, it is not coming up with the correct mime-type for a .jpg file, so that might be why the thumbnails are not working.

**Comment by pSub** [comment]
I haven't tried, but I guess the solution I have purposed for #9679 should also work here.

**Comment by vcunat** [comment]
The mime problem might be fixed by afdfe76.

**Comment by vcunat** [comment]
And the thumbnailing issue does look same as in #9679 (not that I have a good solution for that though).

**Comment by nioncode** [comment]
Are these issues still relevant? Also see my recent fix #36797, which should improve the mime-type situation.

**Comment by ryantm** [comment]
I'm not sure, I stopped using spacefm. I'll close this.

**Comment by TinaRussell** [comment]
Thumbnails aren’t working for me at all, for anything. I have the “show thumbnails” option checked. I’m using SpaceFM 1.0.5 in Ubuntu MATE 18.04 LTS. (note: I originally posted this at #9679, whoops)
