### ISSUE TITLE
pcmanfm: image thumbnails do not work

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#9679]
I am using the nixos-unstable channel without a desktop environment and when I run pcmanfm the image thumbnails for .JPG do not work.

The Arch Wiki says it should support image thumbnails out of the box https://wiki.archlinux.org/index.php/PCManFM#Thumbnail_support

"Show thumbnails of files" is checked in the preferences -> display menu.

**Comment by pSub** [comment]
It seems that pcmanfm is not able to generate thumbnails on its own. I stumbled upon https://wiki.archlinux.org/index.php/File_manager_functionality#Thumbnail_previews which suggest that `tumbler` (nixpkgs.xfce.tumbler) needs to be installed. After installing tumbler and adjusting the maximum filesize for images for which thumbnails should be generated it works for me.

**Comment by vcunat** [comment]
Right, tumbler should be found via dbus normally. I don't know if it's possible to wrap an executable to find it. You can try. (I'm using xfce, so I have tumbler provided by default and not even clearing `$PATH` can avoid it.)

**Comment by pSub** [comment]
Ok, here is clearly some magic at work. I just removed tumbler from my profile (it was only installed there), I even rebooted, but thumbnails still work in pcmanfm. So far I am a bit clueless.

**Comment by Profpatsch** [comment]
(triage) what’s the status?

**Comment by ryantm** [comment]
@Profpatsch I gave up on using these things standalone and just went with Gnome. Maybe we should close until some user has an issue.

**Comment by Profpatsch** [comment]
Okay, cc @pSub

**Comment by pSub** [comment]
I'm closing this. Thumbnails are still working for me.

**Comment by TinaRussell** [comment]
Thumbnails aren’t working for me at all, for anything. I have the “show thumbnails” option checked. I’m using SpaceFM 1.0.5 in Ubuntu MATE 18.04 LTS.

**Comment by TinaRussell** [comment]
> I’m using SpaceFM 1.0.5

…Right, I just realized this is a “pcmanfm” thread… I found my way here from #9678.
