### ISSUE TITLE
(Some?) KDE apps not usable outside of full kde install

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#9680]
1. Some e.g. okular, gwenview cannot open files from cmd args but not in-app (error dialog: "Could not open /p/t/foobar"). gwenview loses browsing and thumbnailing capabilities.
2. All (e.g. above + okteta) are missing (oxygen) icons.

This doesn't occur if `services.xserver.desktopManager.kde4.enable = true` (same for kde5).

A quick search found kdewrapper but it doesn't seem to be applied to core(?) KDE packages.

Pinging maintainer @ttuegel (I believe).

Example output from gwenview:
```
Could not find drkonqi at /nix/store/0cv53qzh2vjpvflapa8ay48za4m4i6hp-kcrash-5.10.0/lib/libexec/drkonqi
Icon theme "oxygen" not found.
kf5.kiconthemes: Couldn't find current icon theme, falling back to default.
Icon theme "oxygen" not found.
Error: standard icon theme "oxygen" not found!
Invalid pixmap specified.
QTimeLine::setDuration: cannot set duration <= 0
"URL cannot be listed
trash:/"
Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kglobalaccel was not provided by any .service files")
Invalid pixmap specified.
QTimeLine::setDuration: cannot set duration <= 0
Invalid pixmap specified.
QTimeLine::setDuration: cannot set duration <= 0
Invalid pixmap specified.
QTimeLine::setDuration: cannot set duration <= 0
"URL cannot be listed
trash:/"
Couldn't start kded5 from org.kde.kded5.service: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kded5 was not provided by any .service files") , falling back to running kbuildsycoca5
kf5.kservice.sycoca: Trying to open ksycoca from "/home/e/.cache/ksycoca5"
Invalid pixmap specified.
QTimeLine::setDuration: cannot set duration <= 0
ui/ui_standards.rc not found in ("/home/e/.config", "/home/e/.nix-profile/etc/xdg", "/nix/var/nix/profiles/default/etc/xdg", "/run/current-system/sw/etc/xdg")
"URL cannot be listed
trash:/"
"URL cannot be listed
trash:/"
Could not generate thumbnail for file "file:///home/e/"
Could not generate thumbnail for file "file:///"
mCurrentMainPageId == 'StartMainPageId'
```
Output from okular:
```
okular(27918)/kdeui (KIconLoader): Error: standard icon theme "oxygen" not found! 

okular(27918)/kdeui (KIconLoader): Error: standard icon theme "oxygen" not found! 

okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "okular/Generator"  not found 
okular(27918)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(27918)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(27918)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(27918)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(27918)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(27918) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "text/plain.xml" 
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "ThumbCreator"  not found 
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "ThumbCreator"  not found 
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "ThumbCreator"  not found 
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "ThumbCreator"  not found 
okular(27918) KSambaSharePrivate::isSambaInstalled: Samba is not installed!
okular(27918) KSambaSharePrivate::isSambaInstalled: Samba is not installed!
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "ThumbCreator"  not found 
okular(27918)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "ThumbCreator"  not found 
okular(27918)/kdecore (trader): KMimeTypeTrader: couldn't find service type "okular/Generator" 
Please ensure that the .desktop file for it is installed; then run kbuildsycoca4. 
okular(27918)/okular (app) Okular::Document::openDocument: No plugin for mimetype '"text/plain"'.
okular(27918)/kdecore (trader): KMimeTypeTrader: couldn't find service type "okular/Generator" 
Please ensure that the .desktop file for it is installed; then run kbuildsycoca4. 
okular(27918)/okular (app) Okular::Document::openDocument: No plugin for mimetype '"text/plain"'.
okular(27918): Couldn't start knotify from knotify4.desktop:  "Could not find service 'knotify4.desktop'." 

okular(27918)/kdeui (KNotification) KNotification::slotReceivedIdError: Error while contacting notify daemon "The name org.kde.knotify was not provided by any .service files" 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded 
okular(27918) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(27918) KPixmapSequence::frameSize: No frame loaded
```

**Comment by vcunat** [comment]
This is a known bug, which has always been there. KDE behaves really nix-unfriendly in this respect, searching for its daemons on `$PATH`, etc. I heard from @ttuegel he's got some WIP to improve this.

**Comment by ttuegel** [comment]
The biggest problem is the sycoca database, which is used by each KDE component to find its runtime dependencies: it is assumed to be per-user and mutable. Essentially, KDE applications live in this mutable-state database (very anti-Nix). My Qt 5.5 branch attempts to solve this by providing an immutable sycoca database for every application. The main annoyance (and the reason this update is so long delayed) is that I have to track down all the runtime dependencies by hand. At least it only needs to be done once! However, I don't expect to backport these improvements to KDE 4.

**Comment by eduarrrd** [comment]
@vcunat Yeah, I've run into it before but it didn't bother me enough to formally open an issue until now.

@ttuegel Interesting. Do you have a starting point for me to read up on how this works by any chance? // Regarding the immutable sycoca db, how does it work with optional dependencies like kparts, kipi plugins, etc? Also, I looked at your branch---wow, you're doing awesome work!

Should we perhaps mark kde apps as conditionally broken e.g. `meta.broken = !config.services.xserver.desktopManager.kde4.enable` (probably invalid but I hope the idea gets across)?

**Comment by ttuegel** [comment]
> Do you have a starting point for me to read up on how this works by any chance?

Not yet, everything is still very much in flux. It's a process of continually tweaking the infrastructure to fix programs that break.

> Regarding the immutable sycoca db, how does it work with optional dependencies like kparts, kipi plugins, etc?

It doesn't. Runtime (optional) dependencies are against the Nix Way because they prevent reproducible program behavior. All those runtime dependencies will now be built-in.

**Comment by jraygauthier** [comment]
@ttuegel: I'm curious about your plan for applications that need the presence of the `klauncher`
daemon (or any other daemon lauched by `kdeinit*`)? I'm currently blocked on this issue for fixing the kde4 `digikam` package.

**Comment by ttuegel** [comment]
@jraygauthier My plan is the same as everything else: make it a built time dependency. If it's built into the Sycoca database, it should be launchable on-demand. Of course, this won't help KDE 4 at all.

**Comment by jraygauthier** [comment]
@eduarrrd : I managed to package digikam so that it work in any DE. I used some of the strategies
@ttuegel used in his branch for the KDE 5 packages (immutable sycoca + wrapper). You can see
the details in #10219. I am certain same techniques can be used to fix both okular and genview (I had
the same oxygen issue with digikam). For `gwenview` to use the kipiplugins, we will however have to
create a separate kipiplugins package built from digikam sources (this is what is done on debian / ubuntu).

**Comment by ttuegel** [comment]
This is no longer an issue; the latest KDE Frameworks have been updated to propagate dependencies correctly.

**Comment by solson** [comment]
> For gwenview to use the kipiplugins, we will however have to
create a separate kipiplugins package built from digikam sources (this is what is done on debian / ubuntu).

I assume this still hasn't been done? There are no plugins in gwenview and no online exports available in spectacle. I couldn't find existing issues on this, so I wasn't sure if the problem is on my end or there's just too few of us KDE5 NixOS users for it to have been reported yet.

**Comment by vcunat** [comment]
@solson: see https://github.com/NixOS/nixpkgs/issues/17448#issuecomment-246200371 for more recent discussion. KDE packaging still isn't designed to handle installation by `nix-env` (although it does work partially).

**Comment by solson** [comment]
@vcunat Ah, well I'm only referring to the specific sentence I quoted, not this issue as a whole. I'm not using `nix-env` at all.

Gwenview and and Spectacle still have no plugins, even when you install KDE5 through the NixOS module and whatnot.

**Comment by vcunat** [comment]
I see. I don't know. We do have `kde4.kipi_plugins` at least.

**Comment by ttuegel** [comment]
> There are no plugins in gwenview and no online exports available in spectacle.

I'm preparing a PR to add the KIPI plugins to gwenview, but all of Spectacle's optional dependencies are already included, and none of them has anything to do with online exports. Can you tell me what package provides this plugin?

**Comment by solson** [comment]
@ttuegel Thanks for working on this. It was my understanding that Spectacle used some of the same plugins as gwenview, but I may have misunderstood. I will investigate more in depth soon.

**Comment by ttuegel** [comment]
It seems like (at least most of) the missing plugins come from Digikam. This should be fixed in 0q4j7iv20cxgfsr14qwzx05wbp2zkgc7cg2pi7ibcnwba70ky96g.

**Comment by solson** [comment]
@ttuegel I figured out the true cause of Spectacle not being able to find the KIPI plugins today. This PR fixes it for me: https://github.com/NixOS/nixpkgs/pull/21918

**Comment by ttuegel** [comment]
Nice catch, thank you!
