### ISSUE TITLE
How to use anbox in Nixos?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#96888]
I installed anbox ，but I cant find out tutorial  about anbox from nixos wiki

**Comment by rnhmjoj** [comment]
I haven't used it recently but Anbox requires some tweaking to the system in order to work (installing a kernel modules, enabling LXC containers, setting up NAT, etc.). There is a NixOS that does that for you, you only have to set `virtualisation.anbox.enable = true`. Then it should just work, for example try
```
anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
```

Unfortunately there is an issue with recent kernels (https://github.com/NixOS/nixpkgs/issues/91367), so you must use an older kernel until this is fixed.

**Comment by prehonor** [comment]
> I haven't used it recently but Anbox requires some tweaking to the system in order to work (installing a kernel modules, enabling LXC containers, setting up NAT, etc.). There is a NixOS that does that for you, you only have to set `virtualisation.anbox.enable = true`. Then it should just work, for example try
> 
> ```
> anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
> ```
> 
> Unfortunately there is an issue with recent kernels (#91367), so you must use an older kernel until this is fixed.

Thank you  for your help， I have another problem yet：How to support arm64 arch for anbox ？

**Comment by Atemu** [comment]
It should just work; the Anbox package supports the aarch64 platform and hydra builds it successfully.

**Comment by prehonor** [comment]
> It should just work; the Anbox package supports the aarch64 platform and hydra builds it successfully.

Support arm64 and x86 ， x86_64 ?

**Comment by rnhmjoj** [comment]
AFAIK arm64 and aarch64 are the [same thing](https://en.wikipedia.org/wiki/ARM64).

**Comment by prehonor** [comment]
> AFAIK arm64 and aarch64 are the [same thing](https://en.wikipedia.org/wiki/ARM64).

Sorry, I'm not very familiar with Android，Please give me a hand： I failed to install some apk with the errors below：
![image](https://user-images.githubusercontent.com/10784632/91881708-7cc86e00-ecb4-11ea-904b-f7a3d275000c.png)

**Comment by rnhmjoj** [comment]
Sorry, I'm not either and this is probably not the best place to ask for android issues.

**Comment by prehonor** [comment]
> Sorry, I'm not either and this is probably not the best place to ask for android issues.

Well，Thanks again。

**Comment by Atemu** [comment]
FYI, the issue here is that not native library for the system µarch is inlcuded in the APK. Make sure you downloaded the correct version for your processor.
