### ISSUE TITLE
Chromium and Discord doesn't use xdg-open correctly when using sway

### ISSUE THREAD

**Issue by Kazimazi** [NixOS/nixpkgs#96897]
**Describe the bug**
Opening magnet links in Chromium fails and so does opening links in Discord when I'm using Sway.

**To Reproduce**
1. Go to piratebay.
2. Try using a magnet link.

1. Open Discord.
2. Click a link.

**Expected behavior**
When I use a magnet link to download torrent I expect it to open my torrent client (qbittorrent).
In Discord clicking on links should open in Chromium.

**Screenshots**
Clicking on the open button doesn't do the thing.
[Pic here.](https://imgur.com/a/ILOjN5Y)

**Additional context**
I only tried in Sway among the wayland compositors. X11 is fine. I haven't tried in Gnome wayland.
The same might be the case with other electron apps.
### If I have xdg_utils installed globally, it works as expected. I have no idea why, doesn't Chromium has it as dependency?

**Notify maintainers**

Give advice if you know whom I should @.
xdg_utils:
@edolstra
Chromium:
@bendlas
@thefloweringash
@primeos 
Discord:
@ldesgoui
@MP2E
@tadeokondrak

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.18, NixOS, 20.03.2868.ff6a070b4ef (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2868.ff6a070b4ef, nixos-unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
Have you tried configuring xdg using https://unix.stackexchange.com/a/59088 ?

**Comment by jonringer** [comment]
Another possible option is that something like `$XDG_CONFIG_HOME` isn't set correctly within the sway context, so it doesn't find the correct settings

**Comment by primeos** [comment]
@Kazimazi could you give #96922 a test without xdg_utils installed globally?

**Comment by Kazimazi** [comment]
> Have you tried configuring xdg using https://unix.stackexchange.com/a/59088 ?

I'm not sure how to do it, although xdg.mime.enable is true by default, xdg tools are not available on PATH when I use sway unlike on for say bspwm.

**Comment by Kazimazi** [comment]
> Another possible option is that something like `$XDG_CONFIG_HOME` isn't set correctly within the sway context, so it doesn't find the correct settings

Setting `$XDG_CONFIG_HOME` didn't help.

**Comment by Kazimazi** [comment]
> @Kazimazi could you give #96922 (doesn't require rebuilding Chromium, only the wrapper) a test without xdg_utils installed globally?

I'm currently rebuilding Chromium with `nix-env -f . -iA chromium`, how do I avoid the full rebuild?

**Comment by jonringer** [comment]
> I'm currently rebuilding Chromium with `nix-env -f . -iA chromium`, how do I avoid the full rebuild?

you can only avoid it if hydra populated the binary cache for you. You most likely CANT avoid it in this situation.

**Comment by Kazimazi** [comment]
that's gonna take like 6 hours

**Comment by jonringer** [comment]
I haven't had an issue with x11, so i changed your title

**Comment by Kazimazi** [comment]
> @Kazimazi could you give #96922 (doesn't require rebuilding Chromium, only the wrapper) a test without xdg_utils installed globally?

Just finished compiling, idd it works. On the other hand is it really a good solution?

**Comment by rvolosatovs** [comment]
FWIW, I use sway *and* have `xdg_utils` part of my user's packages and never had any issues with this, magnet links, mailto etc. links work just fine in Firefox, Chromium and everywhere else.

**Comment by primeos** [comment]
> I'm currently rebuilding Chromium with nix-env -f . -iA chromium, how do I avoid the full rebuild?

Next time you can try to e.g. cherry-pick the commit onto a channel like nixos-unstable. Should've mentioned that, sorry. In that case my branch was based on master the `master` branch and the `chromium-unwrapped` build on Hydra was still pending.

> Just finished compiling, idd it works. On the other hand is it really a good solution?

I don't really see a problem with it. It is a bit strange/hacky but Chromium depends on these binaries and in such cases we usually prefix `$PATH` accordingly (see `git grep -- "--prefix PATH"` for other Nixpkgs examples, usually via `wrapProgram`).

**Comment by alexarice** [comment]
All the discussion here seems to be about chromium, was there a fix for discord? I am having the same problem

**Comment by primeos** [comment]
@alexarice You can e.g. "fix" it by installing `xdg_utils`.
