### ISSUE TITLE
GCC in pkgsCross.armhf-embedded does not build

### ISSUE THREAD

**Issue by guibou** [NixOS/nixpkgs#96921]
**Describe the bug**

`pkgsCross.armhf-embedded.buildPackages.gcc` fails the build.

**To Reproduce**

```
$ nix build -f channel:nixpkgs-unstable pkgsCross.armhf-embedded.buildPackages.gcc -L
[...]
arm-none-eabihf-stage-static-gcc-debug> echo | /build/build/./gcc/xgcc -B/build/build/./gcc/ -E -dM - | \
arm-none-eabihf-stage-static-gcc-debug> sed -n -e 's/^#define \([^_][a-zA-Z0-9_]*\).*/\1/p' \
arm-none-eabihf-stage-static-gcc-debug> -e 's/^#define \(_[^_A-Z][a-zA-Z0-9_]*\).*/\1/p' | \
arm-none-eabihf-stage-static-gcc-debug> sort -u > tmp-macro_list
arm-none-eabihf-stage-static-gcc-debug> /build/build/./gcc/xgcc -B/build/build/./gcc/ -xc -nostdinc /dev/null -S -o /dev/null -fself-test=../../gcc-9.3.0/gcc/testsuite/selftests
arm-none-eabihf-stage-static-gcc-debug> cc1: error: '-mfloat-abi=hard': selected processor lacks an FPU
arm-none-eabihf-stage-static-gcc-debug> cc1: error: '-mfloat-abi=hard': selected processor lacks an FPU
arm-none-eabihf-stage-static-gcc-debug> cc1: note: self-tests are not enabled in this build
arm-none-eabihf-stage-static-gcc-debug> make[2]: *** [../../gcc-9.3.0/gcc/c/Make-lang.in:124: s-selftest-c] Error 1
arm-none-eabihf-stage-static-gcc-debug> make[2]: *** Waiting for unfinished jobs....
arm-none-eabihf-stage-static-gcc-debug> /nix/store/npfsrhkjww5q7sax7p7ijcrj3wlbrxn7-bash-4.4-p23/bin/bash ../../gcc-9.3.0/gcc/../move-if-change tmp-macro_list macro_list
arm-none-eabihf-stage-static-gcc-debug> echo timestamp > s-macro_list
arm-none-eabihf-stage-static-gcc-debug> rm gcc.pod
arm-none-eabihf-stage-static-gcc-debug> make[2]: Leaving directory '/build/build/gcc'
arm-none-eabihf-stage-static-gcc-debug> make[1]: *** [Makefile:4296: all-gcc] Error 2
arm-none-eabihf-stage-static-gcc-debug> make[1]: Leaving directory '/build/build'
arm-none-eabihf-stage-static-gcc-debug> make: *** [Makefile:934: all] Error 2
[...]
```

**Expected behavior**

I'm trying to build a gcc for cross compilation to hard float arm embedded. I'd like this to succed.

**Notify maintainers**

@Synthetica9

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.11, NixOS, 20.09pre236419.a45f68ccac4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre236419.a45f68ccac4"`
 - channels(guillaume): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alexameen** [comment]
I've got the same issue.

**Comment by malte-v** [comment]
This currently breaks [QMK Firmware](https://qmk.fm/).

**Comment by NomisIV** [comment]
I'm trying to build qmk_firmare, but it fails just like @malte-v points out. Is there any way to circumvent the error until there is a proper solution? I'm thinking it could be possible to override qmk_firmware to use an older, non-breaking, version of gcc, but I'm not sure how I could go about doing that (if it would even work).

**Comment by malte-v** [comment]
@NomisIV If you just want to build & flash some firmware,  you may want to have a look at QMK's [Docker guide](https://beta.docs.qmk.fm/using-qmk/guides/development-environments/getting_started_docker). That's what I'm using at the moment.

**Comment by NomisIV** [comment]
@malte-v Well, that was easy enough. Thanks!

**Comment by aforemny** [comment]
I bisected this to 63de09eec3acc5d9d9985f3d2c01aebb3a525be5 being the first bad commit. Note that starting from gcc8 we are not disabling the selftests via 0900-remove-selftests.patch when cross-compiling anymore.

I have read that specifying `-mfpu` might help in this situation, but I did not investigate any further.

**Comment by AndersonTorres** [comment]
Can the patch be reinserted?

**Comment by aforemny** [comment]
It likely does not apply cleanly to newer versions (although I have not tried).

**Comment by aforemny** [comment]
When testing whether that patch would apply to newer versions, I have come to the conclusion that the patch is not even applied in our situation, because `hostPlatform == targetPlatform`. I think the breakage has to do with updating `gccFun` from `gcc7` to `gcc8`.

**Comment by AndersonTorres** [comment]
Hey, maybe it would be... an upstream bug??

**Comment by aforemny** [comment]
@AndersonTorres It seems so! I am having some success compiling with `-with-arch=armv5t --with-fpu=vfp` as suggested in [83105](https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg552339.html).

**Comment by AndersonTorres** [comment]
If you fix this issue, I can try to update QMK tools in #109639
