### ISSUE TITLE
package request: cchat-gtk/cchat-discord: a chat client with discord backend

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#96936]
**Project description**
- cchat-gtk appears to be a generic chat frontend
- cchat-discord appears to be a discord-capable backend

gtkcord3 was the predecessor and was quite nice, I'm excited to get this packaged.

**Metadata**

* homepage URL: https://github.com/diamondburned/gtkcord3
* source URL: https://github.com/diamondburned/gtkcord3
* license: gpl3
* platforms: linux

**Comment by colemickens** [comment]
updated OP to reflect that we should package cchat-gtk/cchat-discord now instead of gtkcord3.

**Comment by figsoda** [comment]
still important to me

**Comment by colemickens** [comment]
I have this packaged in my own config: https://github.com/cole-mickens/nixcfg/tree/bcdaa4416db5a8bb9749ffd7706a0017a87028fe/pkgs/cchat-gtk
