### ISSUE TITLE
Teamviewer 8: url doesn't include version and updates break the hash

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#970]
I haven't found an url that contains version that is officially supported, no idea how we should handle that. Also need to check if it's redistributable.

**Comment by Profpatsch** [comment]
(triage) Since TV has been updated multiple times in the meantime, we can close this, right @domenkozar?

**Comment by domenkozar** [comment]
Well, nothing actionable here, so yes.
