### ISSUE TITLE
TBB uses @rpath on macOS

### ISSUE THREAD

**Issue by hannesweisbach** [NixOS/nixpkgs#97014]
**Describe the bug**

The TBB library has `@rpath` set in the dylibs and/or install names of dylibs are wrong (not absolute paths).

This causes issues when linking against TBB, I think. I'm not sure, but the packages I have been working with always had the entire path specified. Maybe this is related to #91773, though.

**To Reproduce**
1. install TBB on macOS: `nix-env -i tbb-2019_U9`
2. cd into install directory, for example: `cd /nix/store/1g22i3bj0fdm9x5d9fjnfaganr1bq270-tbb-2019_U9`
3. show dependencies/install name of dylibs: `otool -L lib/*.dylib`

**Expected behavior**

I *think* that the dylibs should be installed with an absolute path as install name, i.e. `/nix/store/…`, etc, to make linking against TBB possible.

**Screenshots**

```
 lib % pwd
/nix/store/cakh7lwipbml8b5i1sy9ispms3p9dmkg-tbb-2019_U9/lib
 lib % otool -L *
libtbb.dylib:
	@rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/nb9givrwj0m1jbjf65x4g4i6y1n7pjf0-Libsystem-osx-10.12.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/nix/store/cssjpd1zzddj6md9n4wgxngyv50ha3wj-libc++-7.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
libtbbmalloc.dylib:
	@rpath/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/nb9givrwj0m1jbjf65x4g4i6y1n7pjf0-Libsystem-osx-10.12.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libtbbmalloc_proxy.dylib:
	@rpath/libtbbmalloc_proxy.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/nb9givrwj0m1jbjf65x4g4i6y1n7pjf0-Libsystem-osx-10.12.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	@rpath/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/cssjpd1zzddj6md9n4wgxngyv50ha3wj-libc++-7.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Additional context**

I'm trying to make opencascade (OCE) compile/work on Darwin/macOS, to have it as alternative to opencascade (OCT) on macOS for KiCaD

**Notify maintainers**

@thoughtpolice 
@DIzFer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.5.0, macOS 10.15.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(hannesweisbach): `""`
 - channels(root): `"nixpkgs-20.09pre239930.b4aa1309779"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
Does adding `fixDarwinDylibNames` to `nativeBuildInputs` of TBB fix this?

**Comment by hannesweisbach** [comment]
Thanks! It seems to do the trick: the dylibs now have an absolute path.

Let me try building/installing OCE/KiCad with that change and if that works I'll make a PR.

**Comment by hannesweisbach** [comment]
Ok, I can confirm that this fixes my issue and results in a working version of KiCad using OCE with TBB for me.
