### ISSUE TITLE
`desktopManagerHandlesLidAndPower` should be set per session not global

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#9706]
The state of `services.xserver.displayManager.desktopManagerHandlesLidAndPower` be set per session and not globally as my "none + xmonad" session wants to be true and my kde5 session wants it to be false.

While @Profpatsch 's commit 44c12dc0ff131653f35fc63e97257bf089082c21 moves the act setting downstream, this now creates a problem if the variable is set to different values as it is still of global scope. In the above example I needed to disable it globally to remove the conflict (or rather, I let kde5.enable set it globally for me).

**Comment by vcunat** [comment]
I suppose you've missed #9642 &ndash; we don't have the option anymore, for related reasons.

**Comment by Profpatsch** [comment]
Also see my comment https://github.com/NixOS/nixpkgs/pull/9642#issuecomment-138590745

**Comment by eduarrrd** [comment]
@vcunat I did, thanks for pointing it out!
@Profpatsch ACK.
