### ISSUE TITLE
libseccomp does not cross compile

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#97117]
**Describe the bug**
Tried cross compiling `libseccomp` for the raspberry pi. Didn't work.

**To Reproduce**
1. `nix-shell -p pkgsCross.raspberryPi.libseccomp`

```
[…]
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether make supports nested variables... (cached) yes
checking for linux/seccomp.h... yes
checking for cython3... no
checking for cython... no
checking for armv6l-unknown-linux-gnueabihf-gperf... no
checking for gperf... no
configure: error: please install gperf
builder for '/nix/store/3v5likmzzdkjn5q7zszh0g64klrmxj41-libseccomp-2.5.0-armv6l-unknown-linux-gnueabihf.drv' failed with exit code 1
```

**Expected behavior**

`gperf` must be declared as `nativeBuildInput`. Therefore, `nix-shell -p pkgsCross.raspberryPi.libseccomp.overrideAttrs(old: {nativeBuildInputs = [gperf]})` works.

**Notify maintainers**

@thoughtpolice 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.5-arch1-1, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(piegames): `"home-manager, nixpkgs-20.09pre241765.7bc3a08d3a4"`
 - nixpkgs: `/home/piegames/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by sorki** [comment]
Looks like fix landed in 0730d80e40f4fcb8d0b1bcfa6711f87c33777027
