### ISSUE TITLE
Updating Pharo to the latest version

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#97138]
## Issue description
Pharo is unmaintained at the moment.
I don't have the technical knowledge to upgrade the package myself.
@lukego, could you update the package?
If you don't want to be the maintainer anymore, do you think this is a good first package for a beginner or is it a tricky first one?

**Comment by matklad** [comment]
For the reference, I was able to just use official binary distribution of pharo without too much pain.

I needed to:

* patch `pharo` shell script to not use absolute paths like `/bin/fgrep`
* `patchelf` actual pharo binary
* add libX11, libGL and freetype to LD_LIBRARY_PATH

**Comment by ehmry** [comment]
Squeak is also using an old VM and should be updated to use OpenSmalltalk.

**Comment by matklad** [comment]
Not really -- I haven't been touching faro since that time

**Comment by trofi** [comment]
Silly question: how does one run pharo on `x86_64-linux`? I wondered if we could drop `gcc48` from `nixpkgs` (`pharo` is the last user). And tried to transition pharo from `gcc48` to something newer until update is ready. But I'm struggling to check if current state works today:

```
$ nix run nixpkgs#pharo-launcher
using VM selected by image type.
  image: /nix/store/l3n508mqg5ma22z38ijwvqbzfa8j1fb3-pharo-launcher-2017.02.28/share/pharo-launcher/pharo-launcher.image
  type:  Smalltalk image Spur 32b +C+NF (6521)
  vm:    /nix/store/2qvb6pslh0rkglmhmv5kxjq6pqrq4jlj-pharo-spur32/bin/pharo-spur
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.

You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
```

There is a window flash for a second and nothing else. Should it normally work as is?

**Comment by qbit** [comment]
@trofi you need to set `security.pam.loginLimits` for the user you are running pharo as. For example:
```
  security.pam.loginLimits = [
    {
      domain = "qbit";
      type = "hard";
      item = "rtprio";
      value = "2";
    }
    {
      domain = "qbit";
      type = "soft";
      item = "rtprio";
      value = "2";
    }
  ];
```

That said, there are other issues like the version being to old to run recent images :D
