### ISSUE TITLE
Cannot switch to latest unstable

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#9719]
Commit bd84eba: ![](http://i.imgur.com/uL3KI9e.png)

**Comment by lethalman** [comment]
Here's the problem: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/channel.nix#L20

@edolstra shouldn't this code be updated w.r.t the new channel layout?

**Comment by domenkozar** [comment]
Should we just add `-f`?

**Comment by Profpatsch** [comment]
I believe this was a temporary issue @domenkozar

**Comment by domenkozar** [comment]
Yes, fixed.
