### ISSUE TITLE
KeepassXC failed to build on Darwin

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nixpkgs#97194]
**Describe the bug**
Tried both nixpkgs-unstable and nixpkgs-20.03-darwin, both failed with "Segment fault: 11"

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.6`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixpkgs-20.09pre241765.7bc3a08d3a4"`
 - channels(mlatus): `"home-manager, nixpkgs-20.09pre241765.7bc3a08d3a4"`
 - nixpkgs: `/Users/mlatus/.nix-defexpr/channels/nixpkgs`

**Comment by Ninlives** [comment]
It was successfully built in previous Catalina version, but I did not remember the exact version number before I update

**Comment by sikmir** [comment]
Not reproduced on macOS 10.13.6.

**Comment by turion** [comment]
@Ninlives do you still have a build error?

**Comment by turion** [comment]
According to https://hydra.nixos.org/build/175226618 it doesn't build anymore on darwin since nearly a year.

**Comment by Ninlives** [comment]
@turion Sorry, I'm not using darwin anymore

**Comment by turion** [comment]
No worries :) I'll close this issue and open a new one.
