### ISSUE TITLE
cross-compiling for Windows on Darwin fails at mcfgthreads

### ISSUE THREAD

**Issue by mroi** [NixOS/nixpkgs#97214]
**Describe the bug**
Trying to build a Windows cross-compiler on Darwin fails at the build of mcfgthreads.

**To Reproduce**
On a Darwin host, macOS 10.15.6 (19G2021) in my case:
```
nix-shell -p '(import <nixpkgs> { crossSystem = { config = "x86_64-w64-mingw32"; libc = "msvcrt"; }; }).hello'
```

**Expected behavior**
The `hello` package should be built using a Windows cross-compiler.

**Additional context**
Compiling fails at the `mcfgthreads` package. The `configure` phase runs through, but `make` fails:
```
building
build flags: SHELL=/nix/store/v2s6gfd99q8hl2l1ysc56158ry1csjas-bash-4.4-p23/bin/bash
Makefile:1490: warning: ignoring prerequisites on suffix rule definition
  GEN      .pch.h
  CC       .pch.h.gch
make  all-am
make[1]: Entering directory '/nix/var/tmp/nix-build-mcfgthreads-git-x86_64-w64-mingw32.drv-0/source'
Makefile:1490: warning: ignoring prerequisites on suffix rule definition
  CC       src/mcfgthread_12_dll-dll_startup.o
cc1: error: ./.pch.h.gch: had text segment at different address [-Werror]
cc1: all warnings being treated as errors
```

This overlay fixes the problem for me:
```
(self: super: {
    windows = super.windows // {
        mcfgthreads = super.windows.mcfgthreads.overrideAttrs (attrs: {
            prePatch = "sed -i 's/-Werror//' Makefile.am";
        });
    };
})
```

You can reproduce a successful build like this:
```
nix-shell -p '(import <nixpkgs> { overlays = [ (self: super: { windows = super.windows // { mcfgthreads = super.windows.mcfgthreads.overrideAttrs (attrs: { prePatch = "sed -i \'s/-Werror//\' Makefile.am"; }); }; }) ]; crossSystem = { config = "x86_64-w64-mingw32"; libc = "msvcrt"; }; }).hello'
```

However, I am uncertain, whether this is the proper fix or whether I should dig deeper to diagnose the root cause of this `had text segment at different address` diagnostic.

**Notify maintainers**
@Ericson2314 (not listed as maintainer, but introduced `mcfgthreads` and might know how to fix)

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(Michael): `"nixpkgs-20.09pre241485.4aa5466cbc7"`
 - nixpkgs: `/Users/Michael/.nix-defexpr/channels/nixpkgs`

**Comment by abbec** [comment]
I also get this exact same bug. Any ideas on where to start looking?

**Comment by mroi** [comment]
I just opened pull request #115603 to suggest my fix. With this, I can build a Windows cross-compiler on Darwin.

**Comment by abbec** [comment]
But why does it happen on macos and not Linux? That would still be interesting to know. Someone suggested ASLR might have something to do with it?

**Comment by mroi** [comment]
It is a warning that happens with precompiled headers on macOS.

I deduce from [other reports](https://lists.debian.org/debian-gcc/2012/12/msg00118.html) that `gcc` expects its own text segment to be in the same location when it creates the precompiled header and when it uses it. This is not the case on macOS, due to aggressive ASLR. I think this leads to `gcc` simply ignoring the precompiled header, which is not a problem.

The problem only happens here, because the `mcfgthreads` build system treats all warnings as hard errors. This is what my patch changes.

**Comment by abbec** [comment]
True, since it just skips using the pch it is not that bad :)
