### ISSUE TITLE
specialisation + flakes results in infinite recursion

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#97255]
**Describe the bug**
Example config
```
specialisation.gnome3 = {
  inheritParentConfig = true;
  configuration = {
    services.xserver.desktopManager = {
      pantheon.enable = lib.mkForce false;
      gnome3.enable = true;
    };
  };
};
```

gives me this [full traceback](https://gist.github.com/worldofpeace/2fdb54b73cd1b7bfebf899433f2c4332).

**To Reproduce**
1. Use `specialisation` your nixos-config while using nix flakes 
2. infinite recursion

**Additional context**
Code in nixos https://github.com/NixOS/nixpkgs/blob/f439dc71011a95d527ba115ea5a7b9764616b42b/nixos/modules/system/activation/top-level.nix#L151

**Comment by colemickens** [comment]
I think it's because of `specialArgs`. This patch works, though I'm not sure how robust it is:

```diff
diff --git a/nixos/modules/system/activation/top-level.nix b/nixos/modules/system/activation/top-level.nix
index 03d7e749323..f52ff2d8da1 100644
--- a/nixos/modules/system/activation/top-level.nix
+++ b/nixos/modules/system/activation/top-level.nix
@@ -1,9 +1,10 @@
-{ config, lib, pkgs, modules, baseModules, ... }:
+args_@{ config, lib, pkgs, modules, baseModules, ... }:
 
 with lib;
 
 let
-
+  ignorekeys = [ "config" "lib" "pkgs" "modules" "baseModules" ];
+  args = filterAttrs (n: v: (!builtins.elem n ignorekeys)) args_;
 
   # This attribute is responsible for creating boot entries for
   # child configuration. They are only (directly) accessible
@@ -19,6 +20,7 @@ let
            (optionals childConfig.inheritParentConfig modules)
         ++ [ ./no-clone.nix ]
         ++ [ childConfig.configuration ];
+        specialArgs = args;
       }).config.system.build.toplevel
     ) config.specialisation;
 
```

**Comment by wedens** [comment]
any chance this patch will be upstreamed?

**Comment by zarelit** [comment]
Just for information to everyone who comes here because they try to create specialised configs in flakes, if you use `extraArgs` (I did to inject home-manager) then it should be possible to replace it with an inline module like explained here:
https://discourse.nixos.org/t/accessing-flake-outputs-in-the-flake-itself/14662/6
