### ISSUE TITLE
Handling lid events

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9725]
Continuing the thoughts at https://github.com/NixOS/nixpkgs/pull/9642.

We have the option `services.acpid.lidEventCommands` (https://nixos.org/nixos/manual/ch-options.html#opt-services.acpid.lidEventCommands).
And by default, systemd handles the lid, too.

An idea is to create an option `standbyOnLidClose`, default `true`, that can change the way systemd behaves. Related is the power button.
Not sure where it should go. `systemd.` or `hardware.`?

As a reference, here is the a snippet how to implement it:
```nix
      ${optionalString cfg.displayManager.desktopManagerHandlesLidAndPower ''
        # Stop systemd from handling the power button and lid switch,
        # since presumably the desktop environment will handle these.
        if [ -z "$_INHIBITION_LOCK_TAKEN" ]; then
          export _INHIBITION_LOCK_TAKEN=1
          if ! ${config.systemd.package}/bin/loginctl show-session $XDG_SESSION_ID | grep -q '^RemoteHost='; then
            exec ${config.systemd.package}/bin/systemd-inhibit --what=handle-lid-switch:handle-power-key --why="Desktop environment handles power events" "$0" "$sessionType"
          fi
        fi

      ''}
```

**Comment by dezgeg** [comment]
This can be done with out any custom code by configuring `HandleLidSwitch` in http://www.freedesktop.org/software/systemd/man/logind.conf.html, can't it?

**Comment by Profpatsch** [comment]
You are right. I wasn’t aware `logind` is part of systemd.

https://nixos.org/nixos/manual/ch-options.html#opt-services.logind.extraConfig
