### ISSUE TITLE
system.copySystemConfiguration + flake = ThrownError

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#97252]
**Describe the bug**
Trying to play a bit with flakes, having `system.copySystemConfiguration = true;` prevents the nixos-rebuild. 

```
evaluating file '/nix/store/8anqrx7539im215b8p0ka5lhrzpbgj9z-source/nixos/lib/from-env.nix'
error: --- ThrownError ------------------------------------------------------------------------------------------------------------- nix
at: (276:68) in file: /nix/store/8anqrx7539im215b8p0ka5lhrzpbgj9z-source/nixos/modules/system/activation/top-level.nix

   275|         config.system.copySystemConfiguration
   276|         ''ln -s '${import ../../../lib/from-env.nix "NIXOS_CONFIG" <nixos-config>}' \
      |                                                                    ^
   277|             "$out/configuration.nix"

cannot look up '<nixos-config>' in pure evaluation mode (use '--impure' to override)

```
On a recent unstable:
c59ea8b8a0e7f927e7291c14ea6cd1bd3a16ff38

**Comment by cole-h** [comment]
This is because `NIX_PATH` is impure (env vars in general, really), and thus flakes disallows it by default (as you can see in the error message).

I don't think there's any pure (i.e. flakes-supporting) way to make this work -- or, at least, I can't think of any.

What sort of functionality would you expect out of this? With flakes, I think it'd be hard to distill people's arbitrarily-complex configurations into a single configuration.nix to place at /run/current-system/configuration.nix...

**Comment by teto** [comment]
the configuration is taken via `nixos-rebuild switch --flake ~/myFlakeDir` so it doesnt  need to look into `<nixos-config>`. Couldn't it just copy the flake used instead ?

**Comment by cole-h** [comment]
The error happens in the top-level activation -- how would the activation script know which flake to use? It isn't connected to `nixos-rebuild` in any way except that it is passed to a `nix build` invocation. You'd have to get `~/myFlakeDir` all the way into the top-level activation script, and I don't think there's any sane way to do so. This would require special logic in a multitude of places.

Instead, what's your use case for this option? Maybe we could brainstorm a workaround that would suffice.

**Comment by teto** [comment]
I dont use it (I already version my configuration.nix) and got rid of the item. 20.09 may be the opportunity to add some warning (I hope we can switch to flakes by 21.04 xD ?!).

**Comment by berbiche** [comment]
Is this resolved?

**Comment by teto** [comment]
triaging my issue, I think it's enough that google can find it,

**Comment by isomorpheme** [comment]
I'm not sure if this should be a separate issue, but it'd be nice if there were a clearer / more context-appropriate error message in this case. It took me a moment to realise that `copySystemConfiguration` was the source of the problem, and I couldn't find this issue via search before I did.

**Comment by CyberShadow** [comment]
An explicit error message was added in https://github.com/NixOS/nixpkgs/pull/223760.
