### ISSUE TITLE
Clean up the nixos option tree

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9726]
Is there a guideline on where to put new options?

I can find categories like `ec2`, `gnu`, `qtPlugins` and `zramSwap` in the option root, on the same level as e.g. `hardware`, `nix` and `lib`.

Apart from fulltext option search it is hard to find anything in the current structure.
I’m all for flat hierachies, mind you, but designed systematically.

**Comment by edolstra** [comment]
Ouch, that's very ugly. Those definitely should not be at top-level.

**Comment by Profpatsch** [comment]
A strategy for the cleanup is needed. Since renaming options causes a lot of user breakage, a sensible deprecation model is needed first. So this depends on https://github.com/NixOS/nixpkgs/issues/15357

**Comment by Nadrieril** [comment]
There are still `zramSwap`, `gnu`, `dysnomia` and `powerManagement` that look out of place to me. Do we have a deprecation model by now ?

**Comment by Profpatsch** [comment]
I’ll close this for now, because I don’t think it’s an extremely important thing to do. Grepping for keywords is much easier in any case.
