### ISSUE TITLE
First-class Nix knowledge of reproducible builds

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#9731]
Debian is putting [a lot of effort into getting full reproducibility](https://wiki.debian.org/ReproducibleBuilds), and I'm hoping we might be able to piggyback off of it. Has there been any effort to carry any of those patches over?

We also have the underused `nix-build --check` tool which would be nice to run during CI, at least on things that we declare to be reproducible.

One nice feature we could have is to add an attribute on a derivation called `meta.reproducible`. This would instruct Hydra (or some kind of build helper tool) to try running `nix-build --check` on it, because the package maintainer believes it should be reproducible. A builder would raise an error if it turned out not to be byte-for-byte identical, and we could have some sort of "verify trust" on supposedly reproducible builds that with probability `p` tries rebuilding substitutes from upstream and makes lots of noise if things don't match up.

**Comment by domenkozar** [comment]
It's way more complicated than that. If you want to be sure the build is binary deterministic, you need at least two different environments that differ in a lot of things and then you can compare the results.

**Comment by copumpkin** [comment]
Running in a chroot build seems mostly sufficient these days, right? It's basically a full container already, with isolated network, filesystem, PIDs, and so on.

**Comment by domenkozar** [comment]
Yeah, that's correct, our isolated environments help a lot. It would be still interesting to see difference between two builds of `release-15.09` binaries.

**Comment by domenkozar** [comment]
We should package stuff from https://reproducible-builds.org/tools/

**Comment by pSub** [comment]
The tools from https://reproducible-builds.org/tools/ are now packaged. See ba5402a32822193577219cef2682359c2e3587e1, 5f34fb2c16e2e471e584a7d4488ed098fff7180f and 5e0dca6d062fdce53be93d2f99ddffb8e52f5ae7.

**Comment by garbas** [comment]
is somebody working on this? how would one go to use ``nix-build --check`` with ``diffoscope``? to compare the outputs?

**Comment by Profpatsch** [comment]
@copumpkin With https://github.com/NixOS/nix/commit/8fdd156a650f9b2ce9ae8cd74edcf16225478292 and the tools packaged, would you consider this closed for now?

**Comment by tomberek** [comment]
close?
