### ISSUE TITLE
how to use GravitDesigner on Nixos?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#97337]
GravitDesigner,please.
This is office website:
https://www.designer.io/en/

**Comment by AndersonTorres** [comment]
Closed source? Does it has some TGZ/DEB/WTH package?

**Comment by 06kellyjac** [comment]
https://www.designer.io/en/download/ has a download link with a zip and a snap link. The zip contains an AppImage

Closed source with a typical big ol' EULA

**Comment by AndersonTorres** [comment]
Well, I don't think it needs a package in Nixpkgs, then. It can be solved by creating a [custom overlay](https://nixos.wiki/wiki/Overlays). If any serious doubt, just ask [Discourse](http://discourse.nixos.org/)!

Can I close this issue?

**Comment by prehonor** [comment]
Well，thanks
