### ISSUE TITLE
virtualbox 5.0 breaks /dev/vboxusb permissions

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#9736]
# virtualbox 5.0 breaks /dev/vboxusb permissions

after 2 hours of debugging:

    crw-rw----   1 root vboxusers  10,  58  9. Sep 00:04 vboxdrv
    crw-rw-rw-   1 root root       10,  57  9. Sep 00:04 vboxdrvu
    crw-rw----   1 root vboxusers  10,  56  9. Sep 00:04 vboxnetctl
    drwxr-x---   4 root vboxusers       80  9. Sep 00:14 vboxusb/

i found the vboxusb permissions to be wrong in /dev/vboxusb/*

* **dirs** need to be 0750 root:vboxusers and the 
* **nodes** need to be 0660 root:vboxusers.

this was the case before i switched to:
  16.03pre68239.bd84eba (Dingo)

the permission problem is also shown when doing this as root:

    VBoxManage list usbhost

vs. doing this as normal user, where the list was empty.

**Comment by domenkozar** [comment]
cc @aszlig

**Comment by aszlig** [comment]
@qknight: Thanks for debugging, what is the actual error message that is shown?

**Comment by qknight** [comment]
there is not much of an error message but as i said: **VBoxManage list usbhost** as root returns a device while as normal user it won't.

if i find the time, in a few days, i will debug this futher. sorry i can't help more than to report this finding right now!

**Comment by bjornfor** [comment]
On NixOS 15.09.343.1b83abb (with VirtualBox 5.0.4) I get the same number of devices listed with/without sudo ```[sudo] VBoxManage list usbhost```. My user is in the "vboxusers" group (of course).

```
$ ls -lR /dev/vbox*
crw-rw---- 1 root vboxusers 10, 58 Sep 15 17:11 /dev/vboxdrv
crw-rw-rw- 1 root root      10, 57 Sep 15 17:11 /dev/vboxdrvu
crw-rw---- 1 root vboxusers 10, 56 Sep 15 17:11 /dev/vboxnetctl

/dev/vboxusb:
total 0
drwxr-x--- 2 root vboxusers 100 Sep 15 17:11 001
drwxr-x--- 2 root vboxusers  60 Sep 15 17:11 002

/dev/vboxusb/001:
total 0
crw-rw---- 1 root vboxusers 189, 5 Sep 15 17:11 006
crw-rw---- 1 root vboxusers 189, 6 Sep 15 17:11 007
crw-rw---- 1 root vboxusers 189, 7 Sep 15 17:11 008

/dev/vboxusb/002:
total 0
crw-rw---- 1 root vboxusers 189, 129 Sep 15 17:11 002
```

@qknight: Still an issue? Are you on master or release branch now?

**Comment by domenkozar** [comment]
I also see all usb devices with my normal user.

**Comment by qknight** [comment]
i will check


On 15.09.2015 17:24, Bjørn Forsman wrote:
> On NixOS 15.09.343.1b83abb (with VirtualBox 5.0.4) I get the same number
> of devices listed with/without sudo |[sudo] VBoxManage list usbhost|. My
> user is in the "vboxusers" group (of course).
> 
> |$ ls -lR /dev/vbox* crw-rw---- 1 root vboxusers 10, 58 Sep 15 17:11
> /dev/vboxdrv crw-rw-rw- 1 root root 10, 57 Sep 15 17:11 /dev/vboxdrvu
> crw-rw---- 1 root vboxusers 10, 56 Sep 15 17:11 /dev/vboxnetctl
> /dev/vboxusb: total 0 drwxr-x--- 2 root vboxusers 100 Sep 15 17:11 001
> drwxr-x--- 2 root vboxusers 60 Sep 15 17:11 002 /dev/vboxusb/001: total
> 0 crw-rw---- 1 root vboxusers 189, 5 Sep 15 17:11 006 crw-rw---- 1 root
> vboxusers 189, 6 Sep 15 17:11 007 crw-rw---- 1 root vboxusers 189, 7 Sep
> 15 17:11 008 /dev/vboxusb/002: total 0 crw-rw---- 1 root vboxusers 189,
> 129 Sep 15 17:11 002 |
> 
> @qknight <https://github.com/qknight>: Still an issue? Are you on master
> or release branch now?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/9736#issuecomment-140428441>.
> 


-- 
Joachim Schiele

blog: http://blog.lastlog.de
wiki: http://lastlog.de
jabber: josh@jabber.ccc.de
GPG: C6AC8770
