### ISSUE TITLE
perl 'illegal mode string' Darwin

### ISSUE THREAD

**Issue by miah** [NixOS/nixpkgs#9737]
build log: https://gist.github.com/miah/6aa9a52afe954106a2dd

    patching script interpreter paths in /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8
    find: -perm: /0100: illegal mode string
    builder for ‘/nix/store/c7as6qpcysyl0s6820nzcjc0y9n9h3m9-zlib-1.2.8.drv’ failed with exit code 1

Unless I'm mistaken, `find` on Darwin doesn't support `/ form`. See: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/find.1.html vs http://linux.die.net/man/1/find

**Comment by vcunat** [comment]
Yet another duplicate of #9044. This is only resolved in the staging branch currently.
