### ISSUE TITLE
cantata: dynamic playlists broken due to removal of perl from default system packages

### ISSUE THREAD

**Issue by cole-h** [NixOS/nixpkgs#97402]
**Describe the bug**
When trying to start a dynamic playlist, the user is greeted by an error banner stating the following: `You need to install "perl" on your system in order for Cantata's dynamic mode to function.`

**To Reproduce**
1. Open Cantata
2. Create dynamic playlist
3. Attempt to play dynamic playlist

**Expected behavior**
I expected Cantata to start the dynamic playlist.

**Screenshots**
![image](https://user-images.githubusercontent.com/28582702/92417333-77d14780-f116-11ea-818f-c5cb9b264ffe.png)

**Additional context**
This is likely fallout from perl's removal in https://github.com/NixOS/nixpkgs/pull/91213. However, this exposed something impure about Cantata's packaging, so it's a good thing! I tried simply patching the shebang to point to `${perl}/bin/perl` (as well as changing this `if` condition to never return true: https://github.com/CDrummond/cantata/blob/b8645d135817ba893beb8a384f1ae330e1db3019/playlists/dynamicplaylists.cpp#L214), but to no avail.

**EDIT**: Even adding `perl` to my `environment.systemPackages` does nothing -- when I click on the play button by the dynamic playlist, it turns to the red stop button, and then back to the play button without ever playing or queuing any songs. Seems like this might need more work.

**Notify maintainers**
@peterhoeg 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.9-zen1, NixOS, 20.09.20200906.bcce737-cosmere (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200903_8a945d6`
 - channels(root): `""`
 - nixpkgs: `/home/vin/.config/nixpkgs/compat`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cantata
# a list of nixos modules affected by the problem
module:
```

**Comment by peterhoeg** [comment]
If you have the time to give it go, I think this should do the trick:

```nix
postPatch = ''
  patchShebangs playlists
'';
```

And then add `perl` to `buildInputs`.

**Comment by cole-h** [comment]
Thanks for the tip.

It was slightly more involved than that, but fixed in this PR: https://github.com/NixOS/nixpkgs/pull/97464.
