### ISSUE TITLE
Improvement items for release process

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#97405]
Mostly so i don't forget, as i don't have time right now while visiting family

Noticed a few things which could be improved for the next release:

- [x] reflect changes to suffix to nixos search repo
- [x] move release info over to https://github.com/NixOS/release-wiki
- [x] fix https://github.com/NixOS/nixpkgs/issues/99646
- [x] mention that release branch needs to be pushed alongside tag
- [x] creation of staging-YY.MM branch off of release-YY.MM
- [ ] Rephrase `git rev-list --count release-19.09` to use HEAD
~~there is an alpha phase with tag~~
- [x] should the changes to the release notes not be on the release branch (so we don't have to forward port them separately?) 
- [x] to complete an evaluation, it will take hydra about a day for most jobsets (can be more for darwin due to compute constraints)
  - This also means that branchoff should occur 1-3 days before ZHF
  - Just mention which parts require a hydra evaluation to finish, so these can be better planned in advance
- [x] Have default Channel be read from file, makes it easier to parse  `nixos/modules/misc/version.nix` @garbas 
- [x] Include `version-tag` file to hold the "pre", "beta" value
- [x] Update https://nixos.org/teams/nixos_release.html , better summary
- [ ] Add section around marking failing builds as broken https://github.com/NixOS/release-wiki/issues/4
  - [ ] Make this process not super painful
- [x] Add instructions around final QA of website
  - I forgot to check that the release channel propagated the ec2 ami images, so they were broken until a more recent evaluation completed)
 - [x] update the release team presentation at https://nixos.org/teams/nixos_release.html
 - [x] include osinfo-db update steps https://github.com/NixOS/nixpkgs/pull/104854 https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/252

Somehow incorporate scripts for generating some of the module and major package differences:
```
#!/usr/bin/env bash
changed_files=$(git diff origin/release-20.03..release-20.09 nixos/modules/module-list.nix | grep ^+ | tail -n +2 | sed 's/^+  //g')

for file in $changed_files; do
        echo "  <listitem>"
        echo "    <para>"
        echo "      <filename>$file</filename>"
        echo "    </para>"
        echo "  </listitem>"
done
```

More to be added later :)

**Comment by cole-h** [comment]
> should the changes to the release notes not be on the release branch (so we don't have to forward port them separately?)

Honestly, that sounds like a good idea to me -- as long as backporting it isn't forgotten :P

---

Also +1 on the inclusion of various scripts to ease the process -- maybe in `nixos/maintainers/scripts/release/*` (or `/release-managers/*`)?

**Comment by jonringer** [comment]
still relevant....

**Comment by jonringer** [comment]
marking closed, as most items have been addressed
