### ISSUE TITLE
Running unstable apps on 20.03 can corrupt the font cache

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#97418]
**Describe the bug**

Running on 20.03, running an app from unstable can break the font cache, requiring it to be removed, or refreshed.

**To Reproduce**

WARNING: this may make your apps, and desktop environment hard to use. Make sure you have a way to non-graphically reset the fontconfig config.

```
# Assuming it runs a31736120c5de6e632f5a0ba1ed34e53fc1c1b00
$ nix-shell -I nixpkgs=channel:nixos-unstable -p piper --run piper
# (Quit piper)

# Assuming it runs 42674051d12540d4a996504990c6ea3619505953
$ nix-shell -I nixpkgs=channel:nixos-20.03 -p piper --run piper
# OBSERVE: fonts are broken
# (Quit piper)

```

To fix, statefully:

```
$ rm -rf ~/.cache/fontconfig
# or
$ fc-cache -r
```

Note that I have only reproduced using piper, but I'm pretty sure any good old app using fontconfig can cause grief.

I also expect that this can, more simply, prevent running 20.03 applications on unstable. This is untested.

Note that this is a user-wide stateful issue. Rebooting the machine does not help (assuming it keeps state). And could even make things worse for the end-user depending on the application. Note that some applications are extremely unhappy with that, like Quassel crashing.

**Expected behavior**

Unstable should not trample user state in a rude way

**Screenshots**

![image](https://user-images.githubusercontent.com/132835/92431843-86474f80-f166-11ea-90e0-2d81604e0121.png)

**Notify maintainers**

Hi @jtojnar fonts wizard. Maybe @worldofpeace have insights too?

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.132, NixOS, 20.03post-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(samuel): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by samueldr** [comment]
No problems with the previous unstable update, the one that lived for about two weeks:

```
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/c59ea8b8a0e7f927e7291c14ea6cd1bd3a16ff38.tar.gz -p pango --run 'pango-view /etc/issue'
```

Starts having issues with:

``` 
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/a31736120c5de6e632f5a0ba1ed34e53fc1c1b00.tar.gz -p pango --run 'pango-view /etc/issue'
```

**Comment by Artturin** [comment]
there were lots of changes with fonts in the latest unstable

**Comment by jtojnar** [comment]
Hmm, this is quite weird. The biggest change is the fontconfig 2.14 update but that has already been a part of c59ea8b8.

The main change between the two commits would be that fontconfig now loads config from /etc/fonts/fonts.conf instead of /etc/fonts/2.11/fonts.conf, which might cause some issues but would not expect it to break stable apps, which would keep using the versioned config and the cache generated by it. The caches in the user profile should be versioned by default.

**Comment by worldofpeace** [comment]
This should be fixed now

**Comment by dukebarman** [comment]
Same bug, thx for fast fix
