### ISSUE TITLE
Packaging request: BRL-CAD

### ISSUE THREAD

**Issue by foo-dogsquared** [NixOS/nixpkgs#97417]
**Project description**
A solid modeling CAD system.

**Metadata**

* homepage URL: https://brlcad.org/
* source URL: https://sourceforge.net/projects/brlcad/
* license: various components are licensed under different free licenses
* platforms: unix, linux, darwin, bsd

**Comment by foo-dogsquared** [comment]
I have a draft created for this package.
Since BRL-CAD produces more than 100 binaries (262 on my build), it will take a while for this to do the testing and I already spotted some binaries on my part.

```nix
{ clangStdenv,
  cmake,
  fetchsvn,
  libGL,
  libXi,
  libXft,
  ncurses
}:

# Reference for gathering info for compiling is at https://brlcad.org/wiki/Compiling.
clangStdenv.mkDerivation rec {
  pname = "brl-cad";
  version = "7.30.10";
 
  src = let
    repo = "brlcad";
    tag = builtins.replaceStrings ["."] ["-"] version;
    revision = "77067";
    in fetchsvn {
      url = "svn://svn.code.sf.net/p/${repo}/code/${repo}/tags/rel-${tag}";
      rev = revision;
      sha256 = "1wmx1mr2a2zk20qx1inngsi0d4cfvfaqdzb9k84ijzrkil2zbs7d";
  };

  nativeBuildInputs = [ cmake ];

  buildInputs = [
    libGL
    libXft
    libXi
    ncurses
  ];

  cmakeFlags = [
    # Suppress the developer warnings.
    "-Wno-dev"

    # It is recommended to disable strict mode since the build will throw errors at trivial errors.
    "-DBRLCAD_ENABLE_STRICT=OFF"
    "-DBRLCAD_BUNDLED_LIBS=ON"
    "-DCMAKE_BUILD_TYPE=Release"
  ];

  enableParallelBuilding = true;

  meta = with clangStdenv.lib; {
    description = "A free and open-source 3D solid modelling system";
    homepage = "http://www.brlcad.org/";
    license = licenses.free;
    maintainers = with maintainers; [ foo-dogsquared ];
  };
}
```

**Comment by AndersonTorres** [comment]
Some questions:

1 - Does it need Clang?

**Comment by foo-dogsquared** [comment]
According from the [compiling instructions](https://brlcad.org/wiki/Compiling), it doesn't need to be. Though, I'm using Clang since compiling with GCC gives a compilation error.

**Comment by luzpaz** [comment]
This can be closed as it is in the repo: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/brlcad/default.nix
