### ISSUE TITLE
Slightly confusing user management in the NixOS installation guide

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#97422]
The [Installing section](https://nixos.org/manual/nixos/stable/index.html#sec-installation-installing) of the NixOS manual:

- It asks us to add user using `useradd`, while the generated config suggests creating the user declaratively.
- If user was created declaratively but without a password (as the generated config suggests), and login manager was enabled, the user account will be preselected, even though it will not be possible to log in.
- It asks us to change root password, even though we just set it through `nixos-install` in the previous step.
- It asks us to login as root but SDDM (suggested in the config) does not allow root login.
- It shows `$` prompts in the last step, even thought it probably means `#`.
- But really, we probably should not permit root login by default, like other distros.

Mentioned by https://distrowatch.com/weekly.php?issue=20200907#nixos

**Comment by misuzu** [comment]
Would be great for `nixos-install` to ask passwords for declared users.

**Comment by kanashimia** [comment]
Still is an issue.
