### ISSUE TITLE
‘openjdk-8u60b24’ upgrades to ‘openjdk-8u60b24-bootstrap.tar.xz’

### ISSUE THREAD

**Issue by ebzzry** [NixOS/nixpkgs#9743]
When performing a:

```
nix-env --upgrade
```

the package 'openjdk-8u60b24' upgrades to a different package, 'openjdk-8u60b24-bootstrap.tar.xz', which is a different package.

**Comment by wkennington** [comment]
This breaks the ability to have the bootstrap tested as being buildable as
part of the release. This expression should be alive and built regularly to
ensure its possible to rebuild the bootstrap when JAVA changes are made.
