### ISSUE TITLE
VSCode Segmentation fault after update

### ISSUE THREAD

**Issue by cschmatzler** [NixOS/nixpkgs#97443]
## Issue description
After running `nix-rebuild switch --upgrade`, Visual Studio Code (unstable) doesn't run anymore.
`/nix/store/q5clzxjmv0bkdvpvb93q3s45znf65wp5-vscode-1.48.0/bin/.code-wrapped: line 54: 32134 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"`

The same error occurs when swapping the unstable package to the stable 1.45.0 one.

### Steps to reproduce
1. Run previous build of NixOS.
2. Upgrade packages
3. VSCode does not start up anymore with above mentioned error.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.03.2910.42674051d12 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2910.42674051d12, home-manager-20.03, nixos-unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
cc @eadwu @jonringer @Synthetica9

**Comment by gebner** [comment]
AFAICT your system is on 20.03, and you want to run vscode from unstable?  I am afraid this bug might be related to the breaking fontconfig changes in master.

#94073 cc @jtojnar

**Comment by cschmatzler** [comment]
The same issue occurs with the stable channel VSCode, unfortunately.

I have also followed the issue you linked, running `nix run -f https://github.com/NixOS/nixpkgs/archive/5717d9d2f7ca0662291910c52f1d7b95b568fec2.tar.gz fontconfig -c fc-cache -f`.
The issue unfortunately still occurs. I have looked into my `/nix/store` directory and found two installations of vscode-1.45.0 with two different hashes - one works, one doesn't.

```
> nix-store -qR $(readlink -f $(which code)) | grep fontconfig
/nix/store/a8s8f3qkcswnfbf4dcfgkq5xzs34lk8v-fontconfig-2.12.6
/nix/store/71v85g151amsy5n8lyd6ifz3vc58cw42-fontconfig-2.12.6-lib

> exa /nix/store | grep vscode
[...]
bwhpiypkbj78fi1p902ppcsbpbd3p7rc-vscode-1.45.0
dlww6piqa4rbl59jj512kvsk2k772q7a-vscode-1.45.0
[...]

> /nix/store/dlww6piqa4rbl59jj512kvsk2k772q7a-vscode-1.45.0/bin/code
/nix/store/dlww6piqa4rbl59jj512kvsk2k772q7a-vscode-1.45.0/bin/.code-wrapped: line 45: 22307 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

> /nix/store/bwhpiypkbj78fi1p902ppcsbpbd3p7rc-vscode-1.45.0/bin/code
```

The installation with `bwhpiypkbj78fi1p902ppcsbpbd3p7rc` hash works fine and the UI opens.
Pretty new to this entire system so I might be looking in the wrong directions, let me know if you need me to look elsewhere.

**Comment by jtojnar** [comment]
I would try updating to https://github.com/NixOS/nixpkgs/pull/97441 and deleting `~/.cache/fontconfig`.

**Comment by jonringer** [comment]
I haven't noticed this failure since then. Closing
