### ISSUE TITLE
substitute / substituteInPlace don't fail on missing files

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#9744]
For example, the upower expression has:
```
      substituteInPlace src/notify-upower.sh \
        --replace /usr/bin/dbus-send ${dbus_tools}/bin/dbus-send
```
but `src/notify-upower.sh` doesn't exist. The builder just prints
```
cat: src/notify-upower.sh: No such file or directory
```
and continues.

**Comment by lethalman** [comment]
Why shouldn't it fail? It has to be fixed.

**Comment by domenkozar** [comment]
+1

**Comment by pSub** [comment]
+1

**Comment by vcunat** [comment]
What about making it fail also if the pattern wasn't matched (and thus nothing was substituted). I think this kind of rot is not uncommon and I haven't seen a use case for not failing in such case (though we could add an option for this if there was one).

**Comment by rushmorem** [comment]
+1
I also agree with @vcunat that it should also fail when the pattern doesn't match. I've always wished for this feature. I depend on these commands to setup configuration files.

**Comment by wmertens** [comment]
:+1: While we're at it, the nix-on-windows report claims that this function is quite slow in bash so perhaps this should be rewritten with gnused?

https://github.com/NixOS/nixpkgs/blob/e4644a5b582703e6fa3b1c2e97a99e3bc3f7ce4c/pkgs/stdenv/generic/setup.sh#L370-L409

**Comment by edolstra** [comment]
@vcunat Sounds good, but that should really be a separate issue.

**Comment by domenkozar** [comment]
Bumping milestone (this would possibly break many packages)

**Comment by vcunat** [comment]
Staged.
