### ISSUE TITLE
Attempting to coerce a list to a string may fail with confusing error "cannot coerce a set/function to a string"

### ISSUE THREAD

**Issue by lboklin** [NixOS/nixpkgs#97455]
**Describe the bug**

Attempting to call `toString` on a list containing a set will produce the very confusing error:
> cannot coerce a set to a string

or a list containing a function:
> cannot coerce a function to a string

This can take a long time to figure out the first time it happens, given that the error focuses on the list, rather than the element in question.

**To Reproduce**
1. `nix eval --expr 'toString [ (x: x) ]'` or `nix eval --expr 'toString [ {} ]'`

**Expected behavior**
A more helpful error, such as 
> cannot coerce a list to a string because of one of its elements: cannot coerce a set to a string

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.7.16, NixOS, 20.09.20200820.c59ea8b (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.4pre20200721_ff314f1`
- channels(root): `"nixos-20.03.2806.cb1996818ed"`
- channels(ludvig): `"home-manager, nixpkgs-20.09pre238994.078b9f8aa68, nixos-19.09-19.09.2284.bf7c0f0461e"`
- nixpkgs: `/home/ludvig/.nix-defexpr/channels/nixpkgs`

**Comment by jonringer** [comment]
this should probably be made in https://github.com/NixOS/nix as it relates to the nix cli, and not the nixpkgs package set

**Comment by lboklin** [comment]
> this should probably be made in https://github.com/NixOS/nix as it relates to the nix cli, and not the nixpkgs package set

Good point.

**Comment by lboklin** [comment]
Opened at https://github.com/NixOS/nix/issues/4000 instead.
