### ISSUE TITLE
Package allegro fails to build on latest NixOS 20.09

### ISSUE THREAD

**Issue by Alderaeney** [NixOS/nixpkgs#97458]
## Issue description
When trying to update the system to the latest release of nixos 20.09 unstable, allegro package fails to build at 45% build, this is a dependency from lutris, maybe a solution could be replacing allegro with allegro5.

This is the error appearing:
```
[ 45%] Built target allegro
make: *** [Makefile:149: all] Error 2
builder for '/nix/store/b1wkisbdv3gcd4k49cicz2drlv8x0ly9-allegro-4.4.3.1.drv' failed with exit code 2
cannot build derivation '/nix/store/whszqk6rdr0si7nsv0w40c066pka0dal-lutris-usr-target.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ia4p6pmh7y2g7l6cnfi46a4cbqy1262g-lutris-fhs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/n023xqpp7igxy5g5dzg66hnhpk2cy238-lutris.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1la5ylfn8aa7868cyx2w7mclv5fj2jwj-lutris.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6cf6rjbg5k3ygiy4m904mv7p8wqbdb96-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h1gfil56krpgsmdhvjaxjyavbgvwqkjy-nixos-system-link-gl63-8rc-20.09pre242714.a31736120c5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/h1gfil56krpgsmdhvjaxjyavbgvwqkjy-nixos-system-link-gl63-8rc-20.09pre242714.a31736120c5.drv' failed
```

### Steps to reproduce
1. Run `nixos-rebuild switch --upgrade`
2. The package fails to build

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre242714.a31736120c5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
I was ... forced to go to bed so I did make the  backport til now

**Comment by Alderaeney** [comment]
Well, thanks for fixing the issue.

**Comment by jonringer** [comment]
lutris now builds on release-20.09
