### ISSUE TITLE
Regenerate CRAN packages

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#9748]
cc @peti This needs a Hydra run, I suppose.

One way to stop fast rot of packages (after which we have to wait forever) would be to interleave "latest" and "archive" URLs, but I don't know easy way to do this. Other way would be to use https://mran.revolutionanalytics.com/snapshot/ as a mirror, which contains daily snapshots of CRAN (this may however require permission).

**Comment by abbradar** [comment]
I've regenerated them myself -- https://github.com/abbradar/nixpkgs/commit/8eb379d2e4a81db895cb3078e09f370238d01cd8, if you want to use that.

**Comment by vcunat** [comment]
Heh, a good mirror of CTAN archives would also be good.

**Comment by abbradar** [comment]
You might also pull a fix from https://github.com/abbradar/nixpkgs/commit/8e018e63a7b22381eb1cd18d9fbba86abd40775e

**Comment by peti** [comment]
Builds are running at http://hydra.cryp.to/jobset/nixpkgs/r-updates.

**Comment by FRidh** [comment]
Is there any reason why certain packages are not included?
Example: https://cran.r-project.org/web/packages/eba/index.html

**Comment by abbradar** [comment]
More fixes: https://github.com/abbradar/nixpkgs/commit/0735a4ff71f87e40c457ef2099825c30f0f1126a

**Comment by abbradar** [comment]
This seems to be resolved already.

**Comment by abbradar** [comment]
@FRidh I see `eba` in `cran-packages` and it doesn't seem it's disabled -- what do you mean?

**Comment by FRidh** [comment]
yep you're right, I must have mislooked.
