### ISSUE TITLE
nixos-rebuild + flakes to support build-vm

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#97487]
**Describe the bug**
It was left out being implemented in the initial PR https://github.com/NixOS/nixpkgs/pull/68897#discussion_r375983736, but it's a **very** useful feature for nixos development and endusers. I do understand it's nothing `nix build` can't do, but it's a useful wrapper.

cc @edolstra

**Comment by cole-h** [comment]
See https://github.com/NixOS/nixpkgs/pull/97738 for an attempt at adding support for this.
