### ISSUE TITLE
ocaml packaging seems broken e.g. ocsigen

### ISSUE THREAD

**Issue by tomjridge** [NixOS/nixpkgs#9749]
```
nix-env -i ocsigenserver # should install executable 
ocsigenserver

Fatal error: cannot load shared library dllssl_threads_stubs
Reason: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

Somehow the .so from openssl package should be made available. Also, when using nix-shell with the following default.nix:

```
let
    pkgs = import <nixpkgs> {};
    stdenv = pkgs.stdenv;
    eliom = pkgs.ocamlPackages.eliom;
    ocaml = pkgs.ocaml;
    findlib = pkgs.ocamlPackages.findlib;
    ocsigen_server = pkgs.ocamlPackages.ocsigen_server;
    op = pkgs.ocamlPackages;
    ocsigen_deriving     = op.ocsigen_deriving;
    js_of_ocaml          = op.js_of_ocaml      ;
    ocaml_react          = op.ocaml_react      ;
    ocaml_lwt            = op.ocaml_lwt        ;
    calendar             = op.calendar         ;
    cryptokit            = op.cryptokit        ;
    tyxml                = op.tyxml            ;
    ipaddr               = op.ipaddr           ;
    ocamlnet             = op.ocamlnet         ;
    ocaml_ssl            = op.ocaml_ssl        ;
    ocaml_pcre           = op.ocaml_pcre       ;
    ocaml_optcomp        = op.ocaml_optcomp    ;
    reactivedata         = op.reactivedata     ;
    openssl         = pkgs.openssl     ;
in stdenv.mkDerivation {
    name = "env";

    buildInputs = [ ocaml eliom findlib ocsigen_server  ocsigen_deriving js_of_ocaml ocaml_react ocaml_lwt calendar cryptokit tyxml ipaddr ocamlne\
t ocaml_ssl ocaml_pcre ocaml_optcomp reactivedata  openssl ];   
}
```

I get errors such as 

```
Fatal error: cannot load shared library dlllwt-unix_stubs
Reason: dlllwt-unix_stubs.so: cannot open shared object file: No such file or directory
```

when trying to compile other ocaml code. This presumably happens because LD isn't picking up directories like /nix/store/qmw8i4vdm20pnbx28xg29cknnv1w6cjm-ocaml-lwt-2.4.6/lib/ocaml/4.01.0/site-lib/lwt/

(ocamlfind does know about these paths, but plain LD desn't)

This thread:

http://lists.science.uu.nl/pipermail/nix-dev/2015-April/016917.html

seems relevant, but grepping CAML_LD_LIBRARY_PATH in nixpkgs didn't show many hits (with the exception of utop). What is the best way to fix these issues?

(If this sounds incomprehensible, I can explain more fully)

**Comment by vbgl** [comment]
About your first issue (`ocsigenserver` failing): does the native version of the server (`ocsigenserver.opt`) work? is your issue solved by the following change: https://github.com/NixOS/nixpkgs/commit/cbd2ae34751361cbae039f6066459493fa3a0885?

About your second issue (errors when compiling OCaml programs in a specific environment): could you be more precise about the code you attempt to compile and the compilation commands you use? (i.e., provide a minimal example to help understanding and fixing the issue). Thanks.

**Comment by tomjridge** [comment]
(ashamed) how do I fetch that particular commit to a locally checked-out
nixpkgs git repo?

Thanks

**Comment by vbgl** [comment]
My bad. The link is not what I expected. You can just clone the branch `fix-ocsigen` from my fork of `nixpkgs`.

```
git clone -b fix-ocsigen --depth 1 https://github.com/vbgl/nixpkgs
# local environment with ocsigenserver
NIX_PATH=. nix-shell -p ocamlPackages.ocsigen_server
# or to install it
nix-env -f nixpkgs -iA ocamlPackages.ocsigen_server
```

**Comment by tomjridge** [comment]
make test.opt works ok (I think it did before).

Your change almost works. The following does work for me:

```
  wrapProgram $out/bin/ocsigenserver \
    --prefix CAML_LD_LIBRARY_PATH : "${mkpath ocaml_ssl "ssl"}:${mkpath ocaml_lwt "lwt"}:${mkpath ocamlnet "netsys"}:${mkpath ocamlnet "netstring"\
}:${mkpath ocaml_pcre "pcre"}:${mkpath cryptokit "cryptokit"}:${mkpath ocaml_sqlite3 "sqlite3"}"                                                   
  '';
```

(I've added sqlite3)

But this approach seems a bit haphazard - you have to guess which ocaml libs are necessary and fix up the CAML_LD_LIBRARY_PATH. Wouldn't it be better to somehow have each module add the path to CAML_LD_LIBRARY_PATH?

**Comment by vbgl** [comment]
Thanks for the feedback. I’ve applied the patch in fb09fca7b78d49f7e251b67af3482a43b58f1197, including `sqlite3` as you rightly suggested.

I agree that this is a quick fix and not very satisfying. I’ve no better suggestion though. It cannot be entirely solved in the library derivations: programs that perform dynamic loading should be wrapped to capture the build-time value of the environment variable.

**Comment by tomjridge** [comment]
And thanks for doing all this nixpkgs packaging!
