### ISSUE TITLE
how to install Maplesoft Maple 2019.0  on Linux by any way？

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#97498]
**Project description**
_describe the project a little_

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by wamserma** [comment]
You can probably still download the installer here: https://de.maplesoft.com/download/index.aspx, then run `Maple2019.0LinuxX64Installer.run`. Note that this might not work on NixOS.
Supported Linux Systems for Maple 2019: https://www.maplesoft.com/support/install/2019/Maple/Install.html#MapleInstallGuide_Linux64SysReq

As the Installer is not freely redistributable or available for anonymous download, Maple will likely not be packaged in Nixpkgs. Sage is available as an alternative.

**Comment by prehonor** [comment]
> You can probably still download the installer here: https://de.maplesoft.com/download/index.aspx, then run `Maple2019.0LinuxX64Installer.run`. Note that this might not work on NixOS.
> Supported Linux Systems for Maple 2019: https://www.maplesoft.com/support/install/2019/Maple/Install.html#MapleInstallGuide_Linux64SysReq
> 
> As the Installer is not freely redistributable or available for anonymous download, Maple will likely not be packaged in Nixpkgs. Sage is available as an alternative.

Thank you , I have used Maple successfully.

**Comment by huijunchen9260** [comment]
May I ask how to install Maple on nixos here?

I've gotten the installer, make it executable, and just got this message even if I use `sh -x `:

```sh
./Maple2019.2LinuxX64Installer.run: cannot execute binary file`
```

What should I do to open the installer?

Thank you!

**Comment by wamserma** [comment]
> May I ask how to install Maple on nixos here?
> 
> I've gotten the installer, make it executable, and just got this message even if I use `sh -x `:
> 
> ```shell
> ./Maple2019.2LinuxX64Installer.run: cannot execute binary file`
> ```
> 
> What should I do to open the installer?

Your best bet is to run a supported Linux Distro (in a Virtual Machine). 
Your other option is fiddling around with patchelf and/or using an FHS environment.

**Comment by imsofi** [comment]
For anyone meeting this in the future, you can now use [`toolbox`](https://github.com/containers/toolbox) to do this easily with OCI containers and podman. First set `virtualization.podman.enable = true` and add `pkgs.toolbox` to your enviroment.

Follow below, changing the Fedora release to what is most recent. Right now its `37`.

```bash
$ toolbox create --release 37
...
$ toolbox enter --release 37
(toolbox) $ sudo dnf install lsb
...
(toolbox) $ exit
```

Install maple normally either inside the toolbox or trough `toolbox run` commands.

Finally you can edit the created desktop file, `~/.local/share/applications/maple2021.desktop`. Find the `Exec` line and edit it to something similar to:
```
Exec=/run/current-system/sw/bin/toolbox run --release 37 -- /opt/maple2021/bin/xmaple %f
```

Change accordingly to fit where you installed maple.

---

While this is not packaging for nix and essentially sidestepping NixOS entirely, i see it as a good compromise to allow non-free software that ships with custom Java, Python, and C libraries, all which depend on `lsb`, to be a good middle ground for allowing use.

**Comment by Sikeen** [comment]
Another way is to use nix-ld, it has worked for me after installing the most common lsb binaries and some additional ones. Here is my config:
`
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [

# Maple
    xorg.libXi
    dejavu_fonts
    corefonts
    javaPackages.openjfx21
    gtk3
    glib

 # X11 dependencies (for GUI apps)
    xorg.libX11
    xorg.libXext
    xorg.libXrender
    xorg.libXtst

 # fonts
    fontconfig
    freetype

    ];
`

How I found out what to install was to launch maple through the terminal(/home/$user/maple2024/bin/xmaple) and when it threw the error `/home/siken/maple2024/jre.X86_64_LINUX/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory` I installed (in this example libfreetype) the library it was missing.
Just in case your installation needs additional dependencies

it has to be said that the TestMaple binary throws the error
`
# Test l00: for distributed versions of MAPLE
bytes used=4689720, alloc=8781824, time=0.04
No differences encountered
rm: cannot remove 'tmp': No such file or directory
rm: cannot remove 'ZMpLtmp': No such file or directory
rm: cannot remove 'ZMpLtmp.m': No such file or directory
`

but other then that it works
