### ISSUE TITLE
Tool to sort mirrors list by distance

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#9751]
This clicked in my head while I was stopping system rebuild to manually download huge `texLive` tarballs from an another Debian mirror (a routine which I perform each time `texLive` needs to be redownloaded). We can write a tool which:
1. Takes `pkgs/build-support/fetchurl/mirrors.nix`
2. For each group of hosts there, sorts them by e.g. average ping.
3. Resulting file can be placed to `/etc/nixos` and used via some `config` option.

**Comment by Profpatsch** [comment]
When would that tool be run? I mean profiling the mirrors could take more time than actually downloading from a slower connection.
