### ISSUE TITLE
Firefox: chrome://ubufox/locale/ubufox.properties not found on new window

### ISSUE THREAD

**Issue by simonvandel** [NixOS/nixpkgs#9753]
If a new firefox window is started, the first page is a "Problem loading page" error:

File not found
Firefox can't find the file at chrome://ubufox/locale/ubufox.properties.

I am guessing we are using a configuration from Ubuntu (ubufox).

**Comment by edolstra** [comment]
I can't reproduce this. And the string "ubufox" does not occur anywhere in our Firefox build, as far as I can tell. Maybe there is something in your Firefox settings?

**Comment by simonvandel** [comment]
You are right, it was my settings...

**Comment by GapsoNtm** [comment]
I know it's solved. I found this topic and I would just like to add a solution in settings:
Options>General tab: change your Home Page to something different
