### ISSUE TITLE
Libvirtd: In RockPro64 enabling Libvirtd triggers kernel panic on boot

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#97544]
**Describe the bug**
In RockPro64 enabling `libvirtd` will kernel panic on boot.

**To Reproduce**
1. Use RockPro64, uboot-rockpro64-rk3399_defconfig-2020.07, Linux kernel 5.7.19, NixOS "unstable"
2. Add `virtualisation.libvirtd.enable = true;` to /etc/nixos/configuration.nix
3. nixos-rebuild boot
4. reboot
5. See the kernel panic.

**Expected behavior**
It should not kernel panic.

**Screenshots**
[kernel_panic](https://user-images.githubusercontent.com/5861043/92599769-111c6d00-f281-11ea-9c0e-51f5ffa24e9d.jpg)

**Additional context**
https://gist.github.com/superherointj/fa478aba365245ef87d7400892a88e2f

IRC logs [heavily edited]:

> .:superherointj:. Hello. Does ARM virtualization (libvirtd / qemu / kvm) in NixOS works? Tried enabling it (virtualisation.libvirtd.enable=true) but it kernel panicked w/ RockPro64.
> .:samueldr:. kvm is known to work
> .:samueldr:. so that means qemu should, and probably libvirtd
> .:samueldr:. now, why this KPd? good question
> .:superherointj:. More info: https://gist.github.com/superherointj/014ee3ffc5c19d014c3f54253f3042c6
> .:superherointj:. Kernel pacnic picture: https://photos.google.com/share/AF1QipPJiwAbGLEUcW_D9SBcQU1aNGC5fvuS0sw0OEK-kk1Sui9O0l0iW4rRl1gPLGjypQ/photo/AF1QipPt1Cx6lJT-X4uEwKXLmCIO6a_IcQdcn30KPgi0?key=Zk15WC1od1dpNHluaW1fOU9YY3JhZHQzTG55bVVn%40superherointj
> .:samueldr:. Kernel panic - not syncing: Asynchronous SError Interrupt
> .:superherointj:. What does it mean?
> .:samueldr:. I don't know, but that's the error
> .:samueldr:. it seems to be an issue on another pine64 rockchip-based board, but not with kvm seemingly
> .:samueldr:. can you try off of linuxPackages_latest?
> .:samueldr:. AFAICT the error message itself (Asynchronous SError Interrupt) might not be *specific* to your problem :/
> .:superherointj:. What do I have to change to use 'linuxPackages latest'? I'm using 'unstable' channel.
> .:samueldr:. https://developer.arm.com/documentation/100403/0200/register-descriptions/aarch64-system-registers/disr-el1--deferred-interrupt-status-register--el1
> .:samueldr:. so it seems to be something related to the firmware and/or hardware and/or ARM throwing its hands out in the air?
> .:samueldr:. https://search.nixos.org/options?query=boot.kernelPackages
> .:samueldr:. boot.kernelPackages = pkgs.linuxPackages_latest; # IIRC
> .:samueldr:. you should have u-boot that shows you a selection at boot, not sure if it inits the display on that board though
> <samueldr> you might want to not enable libvirtd in your next rebuild, and instead just run qemu with kvm manually to test
> .:samueldr:. you know, it might not even be kvm, but rather libvirtd doing something weird? (though unlikely)
> .:superherointj:. It still kernel panics with "pkgs.linuxPackages_latest".
> .:samueldr:. tried without libvirtd, and running qemu kvm directly?
> .:samueldr:. might need to find something to run
> .:superherointj:. Will try.

Debugging - To-Do:  `run qemu with kvm manually`
---
Discord logs [heavily edited]:

> superherointjYesterday at 6:51 PM
> Has anyone here tested running QEMU/KVM in RockPro64 as host (to run some guest VMs)? Tried NixOS but kernel panicked.
> 
> superherointjYesterday at 7:18 PM
> This is the kernel panic error.
> Does anyone here by any chance knows why Libvirtd (NixOS) won't work with RockPro64? Any suggestion?
> 
> pgwipeoutYesterday at 11:47 PM
> @superherointj Serror is aarch64's "you did a naughty thing" error handler. Most likely you are running an old kernel and tried crossing the a57 and a73 boundary. The two cpu clusters are not interchangeable, so if you want to run kvm you need to pin qemu and the guest cpu cores to one cluster or the other.
> 
> superherointjToday at 8:36 AM
> @pgwipeout Would upgrading kernel be able to solve this problem?
> 
> pgwipeoutToday at 8:38 AM
> @superherointj The new kernel protects against crossing the boundary and triggering the serror. But you can do that by setting up KVM properly.
> 
> pgwipeoutToday at 8:42 AM
> For KVM, the A53 and A72 cores are not compatible. If you have qemu running on the A53 cluster, all cores must remain on the A53 cluster. Same for the A72 cluster. If you just try running qemu without accounting for this, the kernel scheduler will eventually toss it on a core in a cluster other than the one it started in and crash.
> 
> [I] <ccnut> Today at 8:47 AM
> I'd be curious to know what the incompaitibilites are. It doesn't quite make sense to me. What shared resources are you accessing from the two clusters that would throw an SError?
> 
> pgwipeoutToday at 8:47 AM
> You can fix this by setting up cpu pinning in virsh. <vcpu placement='static'>3</vcpu> would pin qemu to cpu 3. <cputune> \ <vcpupin vcpu='0' cpuset='0'/> \ <vcpupin vcpu='1' cpuset='1'/> \ <vcpupin vcpu='2' cpuset='2'/> \ </cputune> would set up your virtual machine to only use the A53 cluster.
> 
> superherointjToday at 8:48 AM
> @ccnut In a RockPro64, running NixOS, with only  libvirtd enabled will trigger that kernel panic (picture above).
[8:49 AM]
> @pgwipeout To clarify, I have no virtual machine created yet. I have only enabled libvirtd and rebooted.
> 
> pgwipeoutToday at 8:51 AM
> @superherointj That is odd, do you have a pcie card inserted?
> 
> superherointjToday at 8:51 AM
> Only SDCard and eMMC are attached to board.
> 
> pgwipeoutToday at 8:51 AM
> I also saw the kernel version in that picture, you are on a new one that respects the boundary.
> 
> [M] <stikonas:kde.org> Today at 8:51 AM
> even device tree is coming from U-boot
> 
> superherointjToday at 8:55 AM
> I am using a prebuilt uboot: 
> https://hydra.nixos.org/build/126171011
> uboot-rockpro64-rk3399_defconfig-2020.07(edited)
> 
> pgwipeoutToday at 9:09 AM
> Seems they are using mainline atf for their u-boot build.
> 
> superherointjToday at 9:26 AM
> Would it work if I used a newer version of Uboot and ATF?
> 
> pgwipeoutToday at 9:27 AM
> No, it seems they are pulling the most recent versions of both straight from their git repos.
> So unless their kernel or their u-boot configurations are borked, and I don't see why they would change them, I doubt that's the problem.
> Reach out to ARM? [superherointj: my wording]

> pgwipeout Today at 11:19 AM
Huh, looking at the error again. With asynchronous aborts the kernel doesn't always get the offending process correct. But it's calling out dmidecode, which reads the smbios info from u-boot. If it's right that's an odd failure. Are you booting grub and the kernel through efi?
> [11:21 AM] https://lists.debian.org/debian-kernel/2019/03/msg00122.html
> [11:21 AM] Seems it's a known issue with dmidecode.
> [11:22 AM] It's trying to do an x86 fallback when it fails to find smbios, which if you don't enable it in u-boot doesn't exist.
> [11:22 AM] Which it shouldn't be doing.

> [I] ccnut Today at 11:23 AM
> Still, userspace should never panic the kernel. I suppose you can't help it if you provide /dev/mem and allow writes, but reading should only fault.
> [11:23 AM] So that's just bad code.
> [11:25 AM] Who is running demicode anyway? Try removing it from the filesystem and retrying whatever you were doing with qemu virtualizatio.
>  [11:31 AM] Anyway, latest dmidecode does not do the legacy scan: https://github.com/mirror/dmidecode/blob/fd4a87bffcf55db6c9c9d460b1b0b5e6fe9a0f03/dmidecode.c#L5710
> [11:31 AM] Seems like it was patched since then. If you need it, try rebuilding it from source

---
**Notify maintainers**

@grahamc 

**Metadata**
[intj@k3:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/rpw05vnjcsz914x0bpckf71n04yg2xbn-bash-interactive-4.4-p23-dev
copying path '/nix/store/rpw05vnjcsz914x0bpckf71n04yg2xbn-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.03.2910.42674051d12 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2910.42674051d12"`
 - channels(intj): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
virtualisation.libvirtd.enable = true;

**Comment by pgwipeout** [comment]
It seems this should be fixed by this patch for dmidecode: 
http://git.savannah.gnu.org/cgit/dmidecode.git/commit/?id=e12ec26e19e02281d3e7258c3aabb88a5cf5ec1d

It is listed as a recommended patch for v3.2, which needs to be applied to the base package.

**Comment by superherointj** [comment]
I'm proposing this patch:
https://github.com/superherointj/nixpkgs/commit/b087fa715cb33e6fa3aece552d7452a452308c35

**Comment by superherointj** [comment]
Dmidecode bugfix landed. Libvirtd in now working in ARM. And my RockPro64 is now doing well. 
It certainly was rockier than expected (for me at least). 
I appreciate all the patience you guys had with me.
Thanks everyone that helped!
