### ISSUE TITLE
Some packages downgrade when using `--upgrade`

### ISSUE THREAD

**Issue by ebzzry** [NixOS/nixpkgs#9758]
Packages like rsnapshot, and gcc-wrapper point to lower versions, when performing an upgrade:

```
% nix-env --upgrade rsnapshot gcc-wrapper
upgrading ‘rsnapshot-1.4git’ to ‘rsnapshot-1.3.1’
upgrading ‘gcc-wrapper-5.2.0’ to ‘gcc-wrapper-4.9.3’
```

**Comment by vcunat** [comment]
This seems a bug in `nix-env`. Not even `--leq` helps. I believe this didn't happen, not long ago.

**Comment by vcunat** [comment]
Filed a PR to fix this.
