### ISSUE TITLE
tests.nfs3.simple fails, blocking nixos-unstable

### ISSUE THREAD

**Issue by cole-h** [NixOS/nixpkgs#97582]
**Describe the bug**

https://hydra.nixos.org/build/127006497

```
can get a lock
client2: must succeed: time flock -n -s /data/lock true
client2 # [   16.007022] rpc.statd[714]: Failed to insert: creating /var/lib/nfs/sm/server: No such file or directory
client2 # [   16.168621] lockd: cannot monitor server
client2 # flock: /data/lock[   16.015233] rpc.statd[714]: STAT_FAIL to client2 for SM_MON of 192.168.1.3: No locks available
client2 # 
client2 # 
client2 # real  0m0.044s
client2 # user  0m0.001s
client2 # sys   0m0.007s
client2: output: 
Test "can get a lock" failed with error: "command `time flock -n -s /data/lock true` failed (exit code 71)"
```

**To Reproduce**
1. `nix-build -A nixosTests.nfs3.simple`
2. Wait
3. Observe the above log

**Expected behavior**
This shouldn't happen...

**Additional context**
Exit code 71 appears to correspond with EPROTO. This is the extent of my knowledge; I know nothing about NFS.

**Notify maintainers**
cc @edolstra (as the listed maintainer of the test)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.9-zen1, NixOS, 20.09.20200909.219b5ed-cosmere (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200903_8a945d6`
 - channels(vin): `""`
 - channels(root): `""`
 - nixpkgs: `/home/vin/.config/nixpkgs/compat`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nfs
```

**Comment by vcunat** [comment]
Reverted for now in 538e558.
