### ISSUE TITLE
Waybar fonts broken by #97146

### ISSUE THREAD

**Issue by rvolosatovs** [NixOS/nixpkgs#97585]
**Describe the bug**

**To Reproduce**
1. Update to c1c85b9bade
2. Run `waybar`

**Expected behavior**
Configured fonts working the same as before

**Screenshots**
Before #97146
![2020-09-09-20:50:57-screenshot](https://user-images.githubusercontent.com/12877905/92641044-781c3f00-f2de-11ea-8a77-d28abeec7281.png)

After #97146
![2020-09-09-20:52:51-screenshot](https://user-images.githubusercontent.com/12877905/92641085-82d6d400-f2de-11ea-8c07-c2298658d18e.png)

**Additional context**

`Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"`
is present in the log of waybar starting on c1c85b9bade

I am running `waybar` from unstable on `nixos-20.03`
I was unable to test on `nixos-20.09`, because the manual pages failed to build on that branch. Note, that I'm tracking branches from https://github.com/NixOS/nixpkgs-channels

`waybar` from latest master works fine on 20.03.

**Notify maintainers**

cc @FRidh as author of #97146

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-zen1, NixOS, 20.03.git.89e0acdf158 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/home/rvolosatovs/src/github.com/rvolosatovs/infrastructure/vendor/nixpkgs/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: waybar
# a list of nixos modules affected by the problem
module:
```

**Comment by gebner** [comment]
AFAICT your system is on 20.03, and you want to run waybar from unstable? I am afraid this bug might be related to the breaking fontconfig changes in master.

Can you try the workaround from https://github.com/NixOS/nixpkgs/issues/94073#issuecomment-668775738?
`nix run -f https://github.com/NixOS/nixpkgs/archive/5717d9d2f7ca0662291910c52f1d7b95b568fec2.tar.gz fontconfig -c fc-cache -f`

#94073 cc @jtojnar

**Comment by rvolosatovs** [comment]
I solved the issue by just using waybar from a custom fork of 20.03, which uses latest version of waybar. 
FTR, this is the list of all packages from unstable I use on top of 20.03 https://github.com/rvolosatovs/infrastructure/blob/4973d900dc29d931f7f873207293de79a21869c6/nixpkgs/overlays.nix#L9-L219

> Can you try the workaround from [#94073 (comment)](https://github.com/NixOS/nixpkgs/issues/94073#issuecomment-668775738)?
> `nix run -f https://github.com/NixOS/nixpkgs/archive/5717d9d2f7ca0662291910c52f1d7b95b568fec2.tar.gz fontconfig -c fc-cache -f`
> 
> #94073 cc @jtojnar

Unfortunately it does not help, but that also makes sense because I'm on 20.03, so the "old" font cache is already there and more likely the issue is that waybar from unstable needs "new" font cache

**Comment by jtojnar** [comment]
There has been yet another fontconfig break, hopefully, a final one, see https://github.com/NixOS/nixpkgs/pull/97441
