### ISSUE TITLE
SSMTP (networking.defaultMailServer) does not supply "/var/setuid-wrappers/sendmail"

### ISSUE THREAD

**Issue by nathan-gs** [NixOS/nixpkgs#9759]
The networking.defaultMailServer module does not publish a sendmail under the expected location of `/var/setuid-wrappers/sendmail`, which breaks several packages.

There is however a link at `/run/current-system/sw/bin/sendmail`.

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by nathan-gs** [comment]
Still an issue. If you do a search on [``/var/setuid-wrappers/sendmail``](https://github.com/NixOS/nixpkgs/search?utf8=✓&q=%2Fvar%2Fsetuid-wrappers%2Fsendmail) most packages refer to this path. In the ssmtp this is still not supplied.

**Comment by nathan-gs** [comment]
Hm, sounds like ``services.mail.sendmailSetuidWrapper`` will fix this. Maybe we should add some documentation to the ``networking.defaultMailServer``.

I'll add the doc.
