### ISSUE TITLE
help packaging cisco packet-tracer computer networking tool:

### ISSUE THREAD

**Issue by zeta-00** [NixOS/nixpkgs#97635]
hello there,
do you think that your dev team in nixpkgs will be able to package the ciscs packet-tracer computer networking tool ? I am taking a computer networks online course, and currently, as a workaround, I setup virtualbox, created a virtual machine, installed ubuntu on there, installed the .deb packet-tracer file from the cisco netacad website, and finally installed packet-tracer with apt. this virtualbox setup is very painful to setup, and has things that don't work correctly, so i was wondering if you could package this networking tool? it would really save me the hassle, i'm no nix expert, so if i were to help, i would need guidance, i'm available on mondays and tuesdays to contribute to get this tool packaged, let me know, thanks in advance for the help !

note, here's 2 related links:

https://www.reddit.com/r/NixOS/comments/inyo1i/what_is_a_simple_and_easy_way_to_installbuild_a/

https://www.netacad.com/

**Comment by vojta001** [comment]
One might use this #38305 as a starting point

**Comment by buckley310** [comment]
Just playing with it today, this gets version 7.3.1 running.
https://gist.github.com/buckley310/b4e718e71fb1c7403fb4ceb8fabbc1c4
`nix-shell -p 'callPackage ./packet_tracer.nix {}' --run packettracer`

**Comment by zeta-00** [comment]
@buckley310  : thank you, i was able to get packet tracer working on my nixos, but my instructor of the online cisco networking course said that he is unable to open packet tracers of version 7.3.1 of linux, and he told me to downgrade to packet tracer version 7.3.0 in linux. so how do I do this packet tracer version downgrade to 7.3.0 ?

**Comment by zeta-00** [comment]
@buckley310 , i'll try downgrade the version myself in the nix file, if for some reason i run into any issues, i'll let you know.

**Comment by buckley310** [comment]
@zeta-00 I don't think there's an official way to get 7.3.0, unless you already had it downloaded. The page doesn't have it listed anymore.

**Comment by buckley310** [comment]
If anyone wants to take my gist and make a PR out of it, that's fine with me. I have not done it because I almost never use this software, and it would probably be better to have someone who uses it more be the maintainer.

**Comment by ranfdev** [comment]
I've edited @buckley310 derivation a bit to suit my needs.
I run packettracer with bubblewrap, so it can't access the net and I can skip the login

https://gist.github.com/ranfdev/88c4b49a26b1c9ed5fb540f0cbf75532

**Comment by ahdyt** [comment]
> I've edited @buckley310 derivation a bit to suit my needs.
> I run packettracer with bubblewrap, so it can't access the net and I can skip the login
> 
> https://gist.github.com/ranfdev/88c4b49a26b1c9ed5fb540f0cbf75532
> 
> To run (you probably need to add the nixpkgs-unstable channel before):
> 
> ```shell
> nix-shell -p "with import <nixpkgs-unstable> {}; callPackage ./packet-tracer.nix {}" --run packettracer
> ```

do you have workaround for version 8? there's strange issue with the permission.

**Comment by buckley310** [comment]
I updated my gist to 8.0. Needed to add a couple things to get it working. Might be able to be cleaned up a bit, but it works.

**Comment by ahdyt** [comment]
> I updated my gist to 8.0. Needed to add a couple things to get it working. Might be able to be cleaned up a bit, but it works.

chmod 755 "$out"

Oh, so you add chmod 755 to the output, that's how to fix the suspicious ownership or permission?

**Comment by buckley310** [comment]
Yep. Then there were just some new library issues that i fixed by adding more libraries and autoPatchelfHook, and using qt5.callPackage.

**Comment by ahdyt** [comment]
Ah okay, thank you for the chmod, lol, I looking for anywhere on nixos community but didn't find a clue about it.

**Comment by lucasew** [comment]
I have both cisco 7 and 8 working on my dotfiles repo

You are free to take what you want

I am looking to upstream it in a near future

**Comment by lucasew** [comment]
I am working on it 

https://github.com/NixOS/nixpkgs/pull/135789

**Comment by lucasew** [comment]
Solved by #135789 and some bumps after that
