### ISSUE TITLE
mysql-workbench cannot be built after bcrypt update

### ISSUE THREAD

**Issue by vojta001** [NixOS/nixpkgs#97642]
**Describe the bug**
Trying to use `mysql-workbench` I am served with the error message:
```
error: bcrypt-3.2.0 not supported for interpreter python2.7
```

**To Reproduce**
1. Make sure you are using latest nixos-unstable
2. Run `nix-shell -p mysql-workbench`

**Expected behavior**
Having `mysql-workbench` in my environment

**Additional context**
`mysql-workbench` uses Python2 paramiko. Paramiko uses bcrypt, however, it does not support Python older than 3.6 since 87371b8f6338af8398410443868c1f7750840c4b.

**Notify maintainers**
@domenkozar - bcrypt's maintainer

**Comment by ZerataX** [comment]
Also breaks syncthing-gtk

**Comment by mvnetbiz** [comment]
This is fixed, closing.
