### ISSUE TITLE
services.openvpn.enable defaults to true

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#9764]
When I came across [this](http://nixos.org/nixos/manual/ch-options.html#opt-services.openvpn.enable), I did a double-take, because I wasn't expecting it to default to true. The code has a comment saying it's obsolete, but the documentation looks scary.

Any particular reason the option is still around?

It looks like @edolstra changed it in 2012: https://github.com/NixOS/nixpkgs/commit/b2910df04e4ec3e707ad08074bd128dedf9b2c23.

**Comment by peti** [comment]
I believe the `enable` option has no effect. What counts is `servers`, which defaults to `{}`. Without any servers defined, the OpenVPN module won't do anything.

**Comment by copumpkin** [comment]
Yep, thanks!
