### ISSUE TITLE
Package power-profiles-daemon

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#97714]
**Project description**
Makes power profiles handling available over D-Bus.

Announcement: http://www.hadess.net/2020/09/power-profiles-daemon-new-project.html

Might be part of GNOME 3.40: https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/816

**Metadata**

* source URL: https://gitlab.freedesktop.org/hadess/power-profiles-daemon/
* license: GPLv3+
* platforms: linux

**Comment by mvnetbiz** [comment]
I am going to try working on this
