### ISSUE TITLE
some packages have bad name/version

### ISSUE THREAD

**Issue by ebzzry** [NixOS/nixpkgs#9771]
When running the command

    nix-env --query --compare-versions

Some packages are compared with a different package.

    openjdk-8u60b24 < 8u60b24-bootstrap.tar.xz
    qemu-2.4.0 < 2.4.0-x86-only

**Comment by edolstra** [comment]
I removed the openjdk bootstrap thingy the other day.

**Comment by ebzzry** [comment]
Yes, but that was for the `--upgrade`, I think, not `--compare-versions`

**Comment by globin** [comment]
I have `ruby-2.2.2-p0 < 2.2.2-p0-bundler-2015-01-11` to add.

**Comment by vcunat** [comment]
@ebzzry: these are issues in the way the individual packages are named. Version starts at the first dash followed by a digit; qemu renamed in ab295420c.

As for the ruby problem, this is how `buildRubyGem` composes names. It will be best when some ruby users will decide a better way. /cc @cstrahan, @pSub, @pikajude (judging by recent logs).

**Comment by vcunat** [comment]
All bad names mentioned here have been fixed.

**Comment by cstrahan** [comment]
Thanks, @vcunat.
