### ISSUE TITLE
chrony: Run as unprivileged user.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#97718]
We should consider running chrony in nixos as an unprivileged user.

**Comment by kevincox** [comment]
According to a discussion on the mailing list this mostly works, however it can cause issues for some functions: https://www.mail-archive.com/chrony-users@chrony.tuxfamily.org/msg01751.html

However maybe it would make sense to downgrade the current assertion to a warning.

**Comment by kevincox** [comment]
I tried to revive the discussion https://www.mail-archive.com/chrony-users@chrony.tuxfamily.org/msg02297.html

**Comment by 8573** [comment]
Tagging overarching ticket: #11908

**Comment by kevincox** [comment]
I asked on the mailing list and it looks like [the maintainer prefers that chrony is not run as a regular user by default](https://www.mail-archive.com/chrony-users@chrony.tuxfamily.org/msg02298.html). The reason is that the set of devices and permissions that crony needs depends on the configuration so it will quite easily result in a less secure setup if the distribution allows access to everything that chrony *might* need.

However due to NixOS's unique configuration system we could possibly do better. We could run chrony as an unprivileged user iff the user configures chrony only via the provided configuration options. This way we know exactly what permissions are needed. However if `extraConfig` or `extraFlags` are passed then we don't give capabilities or device access and default to running as root.

That being said this is complicated and confusing to the user so it is probably best to leave chrony running as root as it is now. However instructions could be provided how users can set this up themselves and explain the tradeoff that they are making.

**Comment by birlorg** [comment]
Chrony runs as the `chrony` user now, it's probably safe to close this.
