### ISSUE TITLE
OpenVPN service doesn't fail if there are startup errors

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#9774]
I followed the example config on http://nixos.org/nixos/manual/ch-options.html#opt-services.openvpn.servers but accidentally didn't write the full path for the static key. Checking `journalctl -u openvpn-server.service` reveals

```
Sep 10 13:52:14 myserver.mydomain systemd[1]: Starting OpenVPN instance ‘server’...
Sep 10 13:52:14 myserver.mydomain openvpn[13349]: Options error: --secret fails with 'static.key': No such file or directory
Sep 10 13:52:14 myserver.mydomain openvpn[13349]: Options error: Please correct these errors.
Sep 10 13:52:14 myserver.mydomain openvpn[13349]: Use --help for more information.
Sep 10 13:52:14 myserver.mydomain systemd[1]: openvpn-server.service: main process exited, code=exited, status=1/FAILURE
Sep 10 13:52:14 myserver.mydomain systemd[1]: Failed to start OpenVPN instance ‘server’.
Sep 10 13:52:14 myserver.mydomain systemd[1]: Unit openvpn-server.service entered failed state.
Sep 10 13:52:14 myserver.mydomain systemd[1]: openvpn-server.service failed.
Sep 10 13:52:14 myserver.mydomain systemd[1]: openvpn-server.service holdoff time over, scheduling restart.
Sep 10 13:52:14 myserver.mydomain systemd[1]: Stopping OpenVPN instance ‘server’...
Sep
```

This is despite `nixos-rebuild switch` claiming to have succeeded. It seems like `nixos-rebuild switch` should have failed because the service was unable to start up.

**Comment by copumpkin** [comment]
I'm on 14.12 for this problem, by the way.

**Comment by grahamc** [comment]
I believe this issue can be closed - it seems to fail just fine now.

**Comment by grahamc** [comment]
```
[grahamc@NdNdNx:~]$ systemctl status openvpn-....service
● openvpn-....service - OpenVPN instance ‘...’
   Loaded: loaded (/nix/store/v60vpinii3vy17xad6bh4nivl3h1jny4-unit-openvpn-....service/openvpn-....service)
   Active: failed (Result: start-limit) since Sun 2016-01-24 16:15:43 CST; 5s ago
  Process: 19323 ExecStart=openvpn --config /nix/store/anlszqd9dbg5f1wny3xkjbv2bgskmn4s-openvpn-config-... (code=exited, status=1/FAILURE)
 Main PID: 19323 (code=exited, status=1/FAILURE)
```

Jan 24 16:17:57 NdNdNx systemd[1]: Starting OpenVPN instance ‘...’...
Jan 24 16:17:57 NdNdNx openvpn[19344]: Options error: Unrecognized option or missing parameter(s) in /nix/store/anlszqd9dbg5f1
Jan 24 16:17:57 NdNdNx openvpn[19344]: Use --help for more information.
Jan 24 16:17:57 NdNdNx systemd[1]: openvpn-....service: main process exited, code=exited, status=1/FAILURE
Jan 24 16:17:57 NdNdNx systemd[1]: Failed to start OpenVPN instance ‘...’.
Jan 24 16:17:57 NdNdNx systemd[1]: Unit openvpn-....service entered failed state.
Jan 24 16:17:57 NdNdNx systemd[1]: openvpn-....service failed.
Jan 24 16:17:57 NdNdNx systemd[1]: openvpn-....service holdoff time over, scheduling restart.
```
