### ISSUE TITLE
how to update julia  to 1.5.1 please or how to make  the ”use-system-utf8proc-julia-1.3.patch“ to ”use-system-utf8proc-julia-1.5.patch“ in  /home/prehonor/Public/Code/nixpkgs/pkgs/development/compilers/julia/ ?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#97778]
old version of julia  has some bugs， I need use the newest Julia。How to update it ？

**Comment by doronbehar** [comment]
@prehonor To reduce the duplicate open issues in Nixpkgs, I'm closing this in favor of https://github.com/NixOS/nixpkgs/issues/91930 .
