### ISSUE TITLE
SDDM Crashes when displayManager.autoLogin is set

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#97795]
**Describe the bug**
On a cold boot, `sddm-helper` exits uncleanly, leaving a black screen.

This issue seems to have appeared on 20.03 (stable) up to the (at the time of this report) latest `nixos-unstable-small` channel. 

Running `sudo systemctl restart display-manager.service` from a different TTY will immediately load Plasma with the expected automatic login.

**To Reproduce**
1. Include `nixpkgs/nixos/modules/profiles/graphical.nix` as an import at the top of the system configuration
2. Enable `services.xserver.displayManager.autoLogin` and set `services.xserver.displayManager.autoLogin.user`

**Expected behavior**
Automatic login to Plasma after the Plymouth screen.

**Screenshots**
No screenshots, but here's an excerpt of the output of `systemctl -b -u display-manager.service`:

```
...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Starting...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Authenticating...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Preparing to converse...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Conversation with 1 messages
Sep 11 19:08:24 nixos sddm[812]: Authentication error: "\"System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8).\""
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] authenticate: Authentication failure
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] returning.
Sep 11 19:08:24 nixos sddm[812]: Authentication error: "Authentication failure"
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Ended.
Sep 11 19:08:24 nixos sddm[812]: Auth: sddm-helper exited with 1
Sep 11 19:09:24 nixos xserver-wrapper[826]: (EE) event12 - Telink Wireless Receiver: client bug: event processing lagging behind by 17ms, your system is too slow
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event2  - Power Button: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event13 - Video Bus: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event0  - Power Button: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event1  - Sleep Button: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event9  - Telink Wireless Receiver Mouse: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event11 - Telink Wireless Receiver System Control: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event12 - Telink Wireless Receiver: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event7  - HP WMI hotkeys: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event10 - Telink Wireless Receiver Consumer Control: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) AIGLX: Suspending AIGLX clients for VT switch
Sep 11 19:11:05 nixos sddm[812]: Signal received: SIGTERM
Sep 11 19:11:05 nixos sddm[812]: Display server stopping...
Sep 11 19:11:05 nixos systemd[1]: Stopping X11 Server...
...
```

**Additional context**
Using the same configuration this issue appears on only 2 of my 3 machines. The affected ones are using Intel integrated graphics with SSDs, while the other one has an older AMD GPU and HDD. I'm unsure if this could be an issue relating to drivers (with autologin off, SDDM and X work OOTB) or the significant difference in boot times.

**Notify maintainers**
@abbradar @ttuegel 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.8, NixOS, 21.03pre243391.b38c90caa22 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(johannes): `""`
 - channels(root): `"nixos-21.03pre243391.b38c90caa22"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ToxicFrog** [comment]
I can reproduce this on a machine with AMD graphics; the issue seems to be a race condition with individual user login not being permitted before SDDM starts. Normally you don't notice because it's done by the time you finish typing in your password, but with autologin enabled it doesn't have to wait for the human.

I have had luck with this configuration:
```
systemd.services.display-manager.wants = [ "systemd-user-sessions.service" "multi-user.target" "network-online.target" ];
systemd.services.display-manager.after = [ "systemd-user-sessions.service" "multi-user.target" "network-online.target" ];
```
Which may be overkill, but does appear to work.

**Comment by ttuegel** [comment]
> Which may be overkill, but does appear to work.

That doesn't sound like overkill to me. As a user, I definitely want the network and user sessions available before I log in! :sweat_smile:

**Comment by ToxicFrog** [comment]
Well yes :P But I mean, it's possible that it only needs one of `wants` or `after`, not both, or that, say, `multi-user.target` implies `systemd-user-session.services` so there's no need to explicitly list the latter.

**Comment by ttuegel** [comment]
> it's possible that it only needs one of `wants` or `after`

I doubt this part: `wants` and `after` are independent, and we need the display manager to wait until the other services are started, so we probably do need both. I'm not sure about the second part, I need to investigate.

**Comment by j0hax** [comment]
Shouldn't be marked as stale, there are still [people affected by this](https://www.reddit.com/r/NixOS/comments/mrq6z7/machine_doesnt_launch_sddm_after_switching_to/?utm_source=share&utm_medium=ios_app&utm_name=iossmf).

Would it be wise to start a PR for the tweaks suggested by @ToxicFrog? They seem to work on hardware and configurations affected by this.

**Comment by ttuegel** [comment]
> Would it be wise to start a PR for the tweaks suggested by @ToxicFrog? They seem to work on hardware and configurations affected by this.

I agree, this is not stale. I think the suggestion above is the appropriate solution.

**Comment by ilmari-lauhakangas** [comment]
Thanks a lot, the annoying workaround is no longer needed and time to desktop is fast again!
