### ISSUE TITLE
hamster-time-tracker doesn't start on current 15.09

### ISSUE THREAD

**Issue by meteficha** [NixOS/nixpkgs#9780]
I have no idea what to do here. I'm new to NixOS so I have no idea when hamster started having trouble.

```
$ hamster 

** (process:3475): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:3475): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:3475): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Traceback (most recent call last):
  File "/nix/store/h6fl65v9gl876py3maxjxba0d5gb0vli-hamster-time-tracker-1.04/bin/.hamster-wrapped", line 31, in <module>
    from hamster import client, reports
  File "/nix/store/h6fl65v9gl876py3maxjxba0d5gb0vli-hamster-time-tracker-1.04/lib/python2.7/site-packages/hamster/reports.py", line 31, in <module>
    from configuration import runtime
  File "/nix/store/h6fl65v9gl876py3maxjxba0d5gb0vli-hamster-time-tracker-1.04/lib/python2.7/site-packages/hamster/configuration.py", line 304, in <module>
    conf = GConfStore()
  File "/nix/store/h6fl65v9gl876py3maxjxba0d5gb0vli-hamster-time-tracker-1.04/lib/python2.7/site-packages/hamster/configuration.py", line 188, in __init__
    self._client.add_dir(self.GCONF_DIR[:-1], gconf.CLIENT_PRELOAD_RECURSIVE)
glib.GError: Falha ao contatar o servidor de configuração; a causa mais comum é a falta ou má configuração do servidor D-Bus. Para mais informações consulte: http://projects.gnome.org/gconf/. (Detalhes -  1: GetIOR falhou: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files)

$ nixos-version 
15.09.295.f9799e7 (Dingo)
```

@bjornfor

**Comment by bjornfor** [comment]
Looks like it requires dbus to know about the org.gnome.GConf service. I'm running NixOS 15.09 with GNOME 3 desktop, and it seems to be already enabled (so hamster works). Grepping through nixpkgs source tree, I expected to find something like ```services.dbus.packages = [ gconf ]```, but I couldn't find it.

If you don't want to change your desktop configuration, could you try adding ```services.dbus.packages = [ pkgs.gnome3.gconf ];``` in /etc/nixos/configuration.nix?

**Comment by meteficha** [comment]
I'm using GNOME 3 as well :).  Adding `services.dbus.packages = [ pkgs.gnome3.gconf ];` made it work ([and its extension too!](https://extensions.gnome.org/extension/425/project-hamster-extension/)). 

Whose fault is it then? Hamster, dbus, gconf, GNOME?

**Comment by bjornfor** [comment]
Oh, then I guess it's a different setting in my config that pulls in gconf (not GNOME).

I don't think applications can specify dbus service dependencies, because that goes against NixOS principle (installing applications with nix-env cannot affect the global system). So in that regard, I don't know who to blame :-)
There _could_ be a programs.hasmter.enable nixos option (that sets ```services.dbus.packages = [ gconf ]```), but I don't think that its a perfect solution (you have to do two things to get one app working).

**Comment by meteficha** [comment]
BTW, I'm not using `nix-env` at all, I have one giant `configuration.nix` with all apps :).  But I guess it wouldn't be a nice solution if it worked on `configuration.nix` but not on `nix-env`.

**Comment by bjornfor** [comment]
Right. We _could_ do magic with systemPackages, but it would be ... magic and unintuitive :-(

**Comment by meteficha** [comment]
How about adding this DBus magic to `services.xserver.desktopManager.gnome3.enable` at the very least?

**Comment by bjornfor** [comment]
CC @lethalman.

**Comment by joachifm** [comment]
Please provide a PR
