### ISSUE TITLE
python.pkgs.grpcio is broken in latest master

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#97811]
**Describe the bug**
python.pkgs.grpcio is broken in latest master

**To Reproduce**
1. nix-build -A lieer

```
/build/source/third_party/boringssl-with-bazel/linux-x86_64/crypto/chacha/chacha-x86_64.S:56: undefined reference to `OPENSSL_ia32cap_P'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: python_build/temp.linux-x86_64-3.8/third_party/boringssl-with-bazel/linux-x86_64/crypto/chacha/chacha-x86_64.o: relocation R_X86_64_PC32 against undefined hidden symbol `OPENSSL_ia32cap_P' can not be used when making a shared object
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

cc @matthewbauer @lopsided98 @jonringer https://github.com/NixOS/nixpkgs/pull/85246

**Comment by flokli** [comment]
I reverted 849f26d61cb4fcacb74de3c4d907688b85624f4f locally, and got it to build again - so it's definitely some incompatibility with the openssl we pass in.

**Comment by jonringer** [comment]
that commit is from 4 years ago, I wonder why it's making an appearance now

**Comment by das-g** [comment]
This error seems to be present since  #97623 (more specifically 4051e867ba04cf4c1bccf0a2da5553cde2645821), so 849f26d61cb4fcacb74de3c4d907688b85624f4f is probably mostly unrelated to it.
