### ISSUE TITLE
help packaging the `Eclipse JDT Language Server` with nix, and placing it in nixpkgs:

### ISSUE THREAD

**Issue by zeta-00** [NixOS/nixpkgs#97814]
hello there, i setup emacs with lsp-java, but i'm currently having some trouble getting the `Eclipse JDT Language Server` to install when executing the emacs command: `M-x lsp-install-server`, the command returns: `there are no servers with automatic installation`.

anyways, it would be nice if i could package this java language server with nix in nixpkgs, so i can install it through a nix-channel in my shell.nix environment, i would like to do this, but i'm not a nix expert, so i'm going to need some help and about how long will it take to package this java lsp  with nix and push it to nixpkgs?

if you could help me out with this issue !

here's the related links:

https://github.com/eclipse/eclipse.jdt.ls

https://github.com/emacs-lsp/lsp-java

https://www.reddit.com/r/NixOS/comments/ihwi53/how_to_install_eclipse_jdt_language_server/

https://nixos.org/manual/nixpkgs/stable/#sec-language-java

https://nixos.wiki/wiki/Java

**Comment by matt-snider** [comment]
@zeta-00 I packaged jdtls and opened #99330. Could you try it out?

**Comment by zeta-00** [comment]
@matt-snider , hello there, cool, this weekend when i have a little bit more time, i'll try out your packaged java-language-server, also, will you be able to push this java-language-server nix package to nixpkgs, so that it can be installed on the 20.09 channel? i'm just wondering! anyways, thank you for the help, i can't wait to try out your nix packaged java-language-server!

**Comment by zeta-00** [comment]
@matt-snider , hello again, ok, I tried to place the nix code from your commit code into a file named java-lsp.nix and import it into shell.nix, to install java-lsp in an isolated environment, but the terminal returned a nix type error, pasted below is my issue posted in reddit:

https://www.reddit.com/r/NixOS/comments/kghs1w/can_someone_help_me_with_this_terminal_nix_error/

**Comment by zeta-00** [comment]
@matt-snider , hello again, ok, I tried to place the nix code from your commit code into a file named java-lsp.nix and import it into shell.nix, to install java-lsp in an isolated environment, but the terminal returned a nix type error, pasted below is my issue posted in reddit:

https://www.reddit.com/r/NixOS/comments/kghs1w/can_someone_help_me_with_this_terminal_nix_error/

**Comment by zeta-00** [comment]
@matt-snider , and I need java-lsp to be able to run an old jdk8 code base, so I hope that jdk11 and above are backwards compatible with jdk8, so hopefully I don't run into any issues!

**Comment by matt-snider** [comment]
@zeta-00 Yes it works with older code bases. Regarding your issue, it looks like someone else has already provided some feedback. You just need to call the function with the correct attr set. In this case `callPackage` should do that.

**Comment by zeta-00** [comment]
@matt-snider , Hello again, thanks for the response, substituting pkgs.CallPackage for import worked for me, and java-lsp is working in emacs with my (direnv+nix-direnv+emacs-direnv) setup, to work in isolated nix environments!
Anyways, thanks again for packaging java-lsp with nix!
