### ISSUE TITLE
restic: module path example wrong

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#97821]
**Describe the bug**

![Screenshot from 2020-09-12 02-35-49](https://user-images.githubusercontent.com/91113/92982946-c5e0a500-f4a0-11ea-93f4-9f0564082d28.png)

`["/var/lib/postgresql", "/home/user/backup"]` is not a valid nixlang list. the `,` has to be removed

**To Reproduce**

https://search.nixos.org/options?show=services.restic.backups.%3Cname%3E.paths&query=restic&from=0&size=30&sort=alpha_asc&channel=unstable#disabled

**Notify maintainers**
@jerith666

**Comment by jerith666** [comment]
I'm not sure what's going on here.  The option declaration at https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/nixos/modules/services/backup/restic.nix#L95 does not contain a comma in its ``example``, and when I run `man configuration.nix` locally I don't have a comma in the example value either.

I wonder if this is a bug in the way that https://search.nixos.org renders its results or something?  The same issue is present in lots of other cases, for example `boot.initrd.network.ssh.hostKeys`: https://search.nixos.org/options?show=boot.initrd.network.ssh.hostKeys&query=hostKeys&from=0&size=30&sort=alpha_asc&channel=unstable#disabled

**Comment by jerith666** [comment]
Yeah, this looks like it's just an instance of https://github.com/NixOS/nixos-search/issues/175.  Closing.
