### ISSUE TITLE
GitHub bug test issue

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#97827]
GitHub has a bug where [searching](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+gcc+mysql) for issues containing "mysql" and "gcc" only gives a HTTP 500 response. A support agent asked me to open an issue matching the search for further debugging, so here it is.

**Comment by fabianhjr** [comment]
Oh my, it hasn't been fixed.

**Comment by fabianhjr** [comment]
Seems like the issue was fixed, that search no longer produces a 500 error and does return results.
