### ISSUE TITLE
twemoji-color-font: Use release tarball font instead of building from source to reduce build times?

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#97871]
The package `twemoji-color-font` takes a long time to build the individual glyphs using [e.g. 1.5 hours on Hydra](https://hydra.nixos.org/build/126808851).

See also https://github.com/eosrei/twemoji-color-font/issues/83.

Other distros simply use the release tarball (e.g. AUR [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-twemoji-color&id=d1258f544f6d4ed653748a15181fb47e0c1cfa48)) which already has the resulting 13 MB `.ttf` file prebuilt.

Should we do this as well, given that it's a font?

CC maintainer: @fgaz

**Comment by fgaz** [comment]
I'm conflicted, on one hand NixOS is a source based distribution and building from source makes it possible to apply patches and whatnot, but on the other it's just a font without any executable stuff and 1.5 hours is a lot.

I guess it depends on how valuable build time is?

**Comment by nh2** [comment]
It seems quite common for fonts in nixpkgs to use the upstream-release-provided font files; examples I picked randomly by clicking around in [`fonts/`](https://github.com/NixOS/nixpkgs/tree/f73b1097bcb1fb02c63d72c45cf35572c7ccdce6/pkgs/data/fonts):

* [baskerville](https://github.com/NixOS/nixpkgs/blob/f73b1097bcb1fb02c63d72c45cf35572c7ccdce6/pkgs/data/fonts/libre-baskerville/default.nix#L12)
* [hasklig](https://github.com/NixOS/nixpkgs/blob/f73b1097bcb1fb02c63d72c45cf35572c7ccdce6/pkgs/data/fonts/hasklig/default.nix#L12)
* [fira](https://github.com/NixOS/nixpkgs/blob/f73b1097bcb1fb02c63d72c45cf35572c7ccdce6/pkgs/data/fonts/fira/default.nix#L15)

Some fonts are generated by a call to `fontforge`, for example [libertine](https://github.com/NixOS/nixpkgs/blob/f73b1097bcb1fb02c63d72c45cf35572c7ccdce6/pkgs/data/fonts/libertine/default.nix#L17), but there doesn't seem to be a requirement for that.

So I propose to make `twemoji-color-font` one of the former category.

**Comment by vcunat** [comment]
In current settings the job often times out on Hydra.

**Comment by fgaz** [comment]
Ow. Well, that's a good enough reason to switch I guess :)

I'll open a pr.

**Comment by worldofpeace** [comment]
cc @jtojnar

**Comment by jtojnar** [comment]
I have a sentiment for source builds but no rational arguments. The above arguments for building `twemoji-color-font` from source are reasonable.

We also have `twitter-color-emoji` package for a bitmap version of the font (using build system from Noto). That artefact is not available upstream so we need to build it ourselves, unless we want to depend on Fedora.

**Comment by worldofpeace** [comment]
> I have a sentiment for source builds but no rational arguments

Yeah, I'm similar (at least for fonts, outside fonts there's many rational arguments :rofl: ). And I think considering how it times out... It's the best choice for now as there's not a ton of benefit to argue. Though https://github.com/eosrei/twemoji-color-font/issues/83 doesn't seem to be incredibly difficult to do :frowning_face.

**Comment by worldofpeace** [comment]
>  edit: or I could Increase the timeout >:)

I think in practice this is still not going to address the root issue that the calling of inkscape is highly inefficient.
Hehe, I bet nix being content addressed would make a lot of us much happier with not having to rebuild stuff pointlessly.

**Comment by vcunat** [comment]
> In current settings the job often times out on Hydra (and needs to be restarted manually).

I'm sorry, I confused the two packages.  It's apparently the other one that's timing out on Hydra: https://hydra.nixos.org/job/nixos/release-20.03/nixpkgs.twitter-color-emoji.x86_64-linux

**Comment by nh2** [comment]
> I think in practice this is still not going to address the root issue that the calling of inkscape is highly inefficient.

Even with the 5x speedup I found in https://github.com/eosrei/twemoji-color-font/issues/83 it'd still take 20 minutes to build it though.

If somebody goes through the effort of fixing it upstream, we may want to consider switching back to fully-from-source. But there are 1000s of open-source tasks higher than this on my list :)

**Comment by worldofpeace** [comment]
> But there are 1000s of open-source tasks higher than this on my list :)

Can relate. (says ever opensource contributor ever while submitting 10x README PRs in a day :grin: )

**Comment by fgaz** [comment]
https://github.com/NixOS/nixpkgs/pull/110186
