### ISSUE TITLE
compile julia wrong with the output info "No rule to make target '/nix/store/mr8q9cdzmpgc8q8jy2s2fgk50kxmkqjv-pcre2-10.34/include/pcre2.h', needed by 'pcre_h.jl'.  Stop "

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#97886]
I use this nix script to build julia locally:  https://github.com/prehonor/nixscript/blob/master/juliacomplie.nix

and I configure the Make.user, of which contents :
prefix = /home/prehonor/Public/Program/julia/
ARCH = x86_64
MARCH = x86-64
JULIA_CPU_TARGET = x86-64
SHELL = /nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/bash
USE_SYSTEM_BLAS = 1
USE_BLAS64 = 1
LIBBLAS = -lopenblas
LIBBLASNAME = libopenblas
USE_SYSTEM_LAPACK = 1
LIBLAPACK = -lopenblas
LIBLAPACKNAME = libopenblas
USE_SYSTEM_ARPACK = 1
USE_SYSTEM_FFTW = 1
USE_SYSTEM_GMP = 1
USE_SYSTEM_LIBGIT2 = 1
USE_SYSTEM_LIBUNWIND = 1
USE_SYSTEM_MPFR = 1
USE_SYSTEM_OPENLIBM = 1
USE_SYSTEM_OPENSPECFUN = 1
USE_SYSTEM_PATCHELF = 1
USE_SYSTEM_PCRE = 1
PCRE_CONFIG = /nix/store/lwckfw91n1r02r0r51d0pymiwi54y1vy-pcre2-10.34-dev/bin/pcre2-config
PCRE_INCL_PATH = /nix/store/lwckfw91n1r02r0r51d0pymiwi54y1vy-pcre2-10.34-dev/include/pcre2.h
USE_SYSTEM_READLINE = 1
USE_SYSTEM_UTF8PROC = 1
USE_SYSTEM_ZLIB = 1
USE_BINARYBUILDER = 0

I got the error output:
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
rm: cannot remove './': Directory not empty
rm: cannot remove './bin/': Directory not empty
removed './bin/7z'
cat: /home/prehonor/Downloads/julia-1.5.1/usr/manifest/suitesparse-wrapper: No such file or directory
WARNING: using mismatched version for :
  want 
PATH="/nix/store/4xb9z8vvk3fk2ciwqh53hzp72d0hx1da-bash-interactive-4.4-p23/bin:/nix/store/71n1xcigc00w3z7yc836jqcx9cb2dys8-patchelf-0.9/bin:/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin:/nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/bin:/nix/store/0k65d30z9xsixil10yw3bwajbdk4yskv-glibc-2.30-bin/bin:/nix/store/x0jla3hpxrwz76hy9yckg1iyc9hns81k-coreutils-8.31/bin:/nix/store/n48b8n251dwwb04q7f3fwxdmirsakllz-binutils-wrapper-2.31.1/bin:/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin:/nix/store/0k65d30z9xsixil10yw3bwajbdk4yskv-glibc-2.30-bin/bin:/nix/store/x0jla3hpxrwz76hy9yckg1iyc9hns81k-coreutils-8.31/bin:/nix/store/llg20y02q88001c4p5f5gbqk269a8rm3-fftw-double-3.3.8-dev/bin:/nix/store/1mvyzs3dgyp73vrh4brz4c3ki56p6vr0-fftw-single-3.3.8-dev/bin:/nix/store/mm0w8jc58rn01c4kz2n9jvwd6bibcihs-xz-5.2.4-bin/bin:/nix/store/lwckfw91n1r02r0r51d0pymiwi54y1vy-pcre2-10.34-dev/bin:/nix/store/y5612mgzla5l0x685lalfya8xps30xxl-pcre2-10.34-bin/bin:/nix/store/rzcnnp4q8g4acg74kq38qndng1l65vw3-openblas-0.3.7/bin:/nix/store/84g84bg47xxg01ba3nv0h418v5v3969n-ncurses-6.1-20190112-dev/bin:/nix/store/xhhkr936b9q5sz88jp4l29wljbbcg39k-ncurses-6.1-20190112/bin:/nix/store/rmc7nwnzcbzbrah6ma9xfi26jpzrhx9s-readline-6.3p08/bin:/nix/store/azvrlhwk730afm25h5973apmk5vr2wn3-curl-7.70.0-dev/bin:/nix/store/c35xvmzfdwgvd0hkzkm5v19msmql0wlj-nghttp2-1.40.0-bin/bin:/nix/store/gnqgyxda6la4gw6hjh4gpmmlcnjbqn2a-libkrb5-1.17-dev/bin:/nix/store/bxjyac4385pw8cwrlgm7d18bmmndf4p5-libkrb5-1.17/bin:/nix/store/cfkappcqwnk1kmnnqqwxrg73fjdsa2am-openssl-1.1.1g-bin/bin:/nix/store/6qqx5lginadxlypif6px4mmwphp65jdk-curl-7.70.0-bin/bin:/nix/store/0grk11qa4y0a55v33hgdpl88h1j6gbnf-gfortran-wrapper-9.2.0/bin:/nix/store/17gzxpcfym0y144dhg6g9s962ydqdhis-gfortran-9.2.0/bin:/nix/store/0k65d30z9xsixil10yw3bwajbdk4yskv-glibc-2.30-bin/bin:/nix/store/x0jla3hpxrwz76hy9yckg1iyc9hns81k-coreutils-8.31/bin:/nix/store/n48b8n251dwwb04q7f3fwxdmirsakllz-binutils-wrapper-2.31.1/bin:/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin:/nix/store/0k65d30z9xsixil10yw3bwajbdk4yskv-glibc-2.30-bin/bin:/nix/store/x0jla3hpxrwz76hy9yckg1iyc9hns81k-coreutils-8.31/bin:/nix/store/rap8fk264z136wqd1rmp7h8y5y8wvdis-gnum4-1.4.18/bin:/nix/store/71n1xcigc00w3z7yc836jqcx9cb2dys8-patchelf-0.9/bin:/nix/store/sg42gk32rbx5b3klmw9ql2sy165rnq8v-perl-5.30.1/bin:/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/bin:/nix/store/24kwvc2lzv8njibq6w9qkmsa69ghh47b-which-2.21/bin:/nix/store/x0jla3hpxrwz76hy9yckg1iyc9hns81k-coreutils-8.31/bin:/nix/store/97vambzyvpvrd9wgrrw7i7svi0s8vny5-findutils-4.7.0/bin:/nix/store/dqq1bvpi3g0h4v05111b3i0ymqj4v5x1-diffutils-3.7/bin:/nix/store/p34p7ysy84579lndk7rbrz6zsfr03y71-gnused-4.8/bin:/nix/store/b0vjq4r4sp9z4l2gbkc5dyyw5qfgyi3r-gnugrep-3.4/bin:/nix/store/c8balm59sxfkw9ik1fqbkadsvjqhmbx4-gawk-5.0.1/bin:/nix/store/g7dr83wnkx4gxa5ykcljc5jg04416z60-gnutar-1.32/bin:/nix/store/kkvgr3avpp7yd5hzmc4syh43jqj03sgb-gzip-1.10/bin:/nix/store/rw96psqzgyqrcd12qr6ivk9yiskjm3ab-bzip2-1.0.6.0.1-bin/bin:/nix/store/dp6y0n9cba79wwc54n1brg7xbjsq5hka-gnumake-4.2.1/bin:/nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin:/nix/store/xac1zfclx1xxgcd84vqb6hy3apl171n8-patch-2.7.6/bin:/nix/store/mm0w8jc58rn01c4kz2n9jvwd6bibcihs-xz-5.2.4-bin/bin:/home/prehonor/Downloads/julia-1.5.1/usr/tools" PATCHELF="patchelf" FC="gfortran -march=x86-64 -m64" /home/prehonor/Downloads/julia-1.5.1/contrib/fixup-libgfortran.sh --verbose /home/prehonor/Downloads/julia-1.5.1/usr/lib
Discovered traces of libgfortran within 
Got SONAMES of 
Warning: git information unavailable; versioning information limited
make[1]: *** No rule to make target '/nix/store/mr8q9cdzmpgc8q8jy2s2fgk50kxmkqjv-pcre2-10.34/include/pcre2.h', needed by 'pcre_h.jl'.  Stop.
make: *** [Makefile:66: julia-base] Error 2

**Comment by doronbehar** [comment]
@prehonor the state of Julia in Nixpkgs is tracked at https://github.com/NixOS/nixpkgs/issues/91930 . A draft PR to fix it is at #98043 . A PR to remove / disable broken / old julia derivations is at #93333 . I'm closing this in favor of the other issues.

Regards.
