### ISSUE TITLE
Thunderbird 78.2.2 rendering issues

### ISSUE THREAD

**Issue by mohe2015** [NixOS/nixpkgs#97994]
**Describe the bug**
Thunderbird 78.2.1 f56bda0c0c6ccdd405398a0ab3a5cbc75aaad405 is working.
master cc4a33d78c0fdfc8d64274179c24d8188153287a (Thunderbird 78.2.2) has rendering issues (see screenshot). Most buttons do not react to clicks and the menu is also not reacting.

**To Reproduce**
Switch to the mentioned commit and rebuild.

**Expected behavior**
Normally working thunderbird.

**Screenshots**
![image](https://user-images.githubusercontent.com/13287984/93130992-ab424200-f6d3-11ea-9230-3bfcdfa38544.png)

**Notify maintainers**
@edolstra 
@lovesegfault
@nbp

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.8, NixOS, 21.03.20200914.cc4a33d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-20.09pre242714.a31736120c5, home-manager"`
 - channels(moritz): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by beardhatcode** [comment]
This was also a bug in Ubuntu, it was fixed there with:

https://bazaar.launchpad.net/~mozillateam/thunderbird/thunderbird.groovy/revision/563

https://bugs.launchpad.net/ubuntu/+source/thunderbird/+bug/1895898
https://bugzilla.opensuse.org/show_bug.cgi?id=1176384#c0

**Comment by kevincox** [comment]
Upstream bug appears to be
https://bugzilla.mozilla.org/show_bug.cgi?id=1664607

**Comment by mohe2015** [comment]
Btw temporary fix would be to switch to thunderbird-bin-78 if you are not opposed to binaries
