### ISSUE TITLE
git: do not install distributed zsh completion

### ISSUE THREAD

**Issue by smancill** [NixOS/nixpkgs#98010]
## Issue description

PR #79578 installs Git's own Zsh completion script without much justification. This is not necessary as Zsh already provides completion for Git by default, and it is much better than Git's own Zsh completion (which is based on Bash completion).

Also, a quick search shows that other mayor distros do not install Git's own Zsh completion neither (which would be in `/usr/share/zsh/site-functions/_git`).

- [Debian doesn't](https://packages.debian.org/buster/amd64/git/filelist)
- [Ubuntu doesn't](https://packages.ubuntu.com/focal/amd64/git/filelist)
- [Fedora doesn't](https://src.fedoraproject.org/rpms/git/blob/master/f/git.spec)
- [Arch doesn't](https://www.archlinux.org/packages/extra/x86_64/git/files/)
- [Gentoo doesn't](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-vcs/git/git-2.28.0.ebuild)

The only one I can find that are doing it is [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb), but trying to reason with those maintainers is an exercise in futility.

So, please, revert the PR. Otherwise Git's own completion will be first in the `fpath` and picked instead of the default and better Zsh-provided Git completion.

**Comment by cole-h** [comment]
Should have been closed by https://github.com/NixOS/nixpkgs/pull/98012, so closing it now.

The revert will be available in the next staging cycle (whenever that happens).

**Comment by keith** [comment]
Looking for a recommendation here from someone who prefers the completion that ships with Git. I converted to nix from homebrew on macOS and at least 1 place where the git completion is superior is with custom `git-foo` binaries elsewhere in your $PATH. The git completion handles these but the default zsh completion doesn't.

How are situations like this normally handled? Would supporting both cases (but the current value as the default) be a proper path forward?

**Comment by smancill** [comment]
Something like this should do the trick.

Create an overlay file in `~/.config/nixpkgs/overlays/git-zsh-completion.nix` with the following content, to create a new package that depends on `git` and installs the Zsh completion file. The code is based on #79578, but adapted to the proper paths (copy the completion file from `git` output into `git-zsh-completion` output).

``` nix
self: super:
{
  git-zsh-completion = super.stdenvNoCC.mkDerivation {
    pname = "git-zsh-completion";
    version = super.git.version;

    phases = [ "installPhase" ];

    installPhase = ''
      mkdir -p $out/share/zsh/site-functions
      cp ${super.git}/share/git/contrib/completion/git-completion.zsh $out/share/zsh/site-functions/_git

      # Patch the zsh completion script so it can find the Bash completion script.
      sed -i -e "/locations=(/a \${"\t\t"}'${super.git}/share/git/contrib/completion/git-completion.bash'" \
        $out/share/zsh/site-functions/_git
    '';
  };
}
```

Then install normally:

``` shell
$ nix-env -f <nixpkgs> -iA git git-zsh-completion
```

**Comment by keith** [comment]
That's perfect! Thanks so much for taking the time to write this up!
