### ISSUE TITLE
Using `buildTools = [ ghcjs ];` results in file permission error

### ISSUE THREAD

**Issue by mayhewluke** [NixOS/nixpkgs#9802]
In order to work around #9175 I had hoped to use Stack to build my project while using Nix to provide GHCJS and other non-Hackage tools (such as Stack itself, for example). However, trying to use both Stack and GHCJS in my nix-shell results in the following error:

```
$ nix-shell --pure test.nix
these derivations will be built:
  /nix/store/rwmh696jvag43hxrwlp1a81g6fchwf6s-ghc-7.10.2.drv
building path(s) ‘/nix/store/p9dg14iyn9dk0mmy1xb6zsq56gxjpada-ghc-7.10.2’
collision between `/nix/store/8swzwadr3ls54jna9rk8hw7bga5qv3zq-ghc-7.10.2/bin/haddock' and `/nix/store/k41ds33459i137dp9qgs8vnih4hvi4r1-haddock-2.16.1/bin/haddock'
builder for ‘/nix/store/rwmh696jvag43hxrwlp1a81g6fchwf6s-ghc-7.10.2.drv’ failed with exit code 2
error: build of ‘/nix/store/rwmh696jvag43hxrwlp1a81g6fchwf6s-ghc-7.10.2.drv’ failed
/home/vagrant/.nix-profile/bin/nix-shell: failed to build all dependencies
```

Installing them via `nix-env -i` works just fine, however:

```
$ nix-env -f "<nixpkgs>" -i -A haskellPackages.stack -A haskell.compiler.ghcjs
installing ‘stack-0.1.4.1’
installing ‘ghcjs-0.1.0’
building path(s) ‘/nix/store/xa6w23y64nwcvzl2nc8aj3c4fryxba83-user-environment’
created 65 symlinks in user environment
```

Running `nix-build` also works fine (although I get a warning about dumping a very large path). I attempted the whole process with a fresh install (via vagrant, as seen in the examples above) and it had the same error. **Is this collision thing a bug, or is this something I can/should fix on my end?**

---

Here are the contents of the nix file I'm using (mostly generated via cabal2nix):

```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "default" }:

let

  inherit (nixpkgs) pkgs;

  ghcjs = pkgs.haskell.compiler.ghcjs; # Added manually

  f = { mkDerivation
      , ...
      , stack # Added manually
      }:
      mkDerivation {
        pname = "foo";
        version = "0.0.0";
        src = ./.;
        isLibrary = true;
        isExecutable = true;
        libraryHaskellDepends = [ ... ];
        executableHaskellDepends = [ ... ];
        buildTools = [ stack ghcjs ]; # Added manually
        license = "undefined";
      };

  haskellPackages = if compiler == "default"
                       then pkgs.haskellPackages
                       else pkgs.haskell.packages.${compiler};

  drv = haskellPackages.callPackage f {};

in

  if pkgs.lib.inNixShell then drv.env else drv
```

**Comment by mayhewluke** [comment]
My mistake, this has nothing to do with Stack. Just having `buildTools = [ pkgs.haskell.compiler.ghcjs ];` is enough to trigger the collision error (even with a fresh install of Nix, and `nix-shell` being the first Nix command ever run).

**Comment by mayhewluke** [comment]
I think my problem was that I had ended up mixing up `pkgs.haskellPackages.callPackage` with a derivation that used `ghcjs`. Modifying the code so that it uses `pkgs.haskell.packages.ghcjs.callPackage` instead solves the collision error message. However, I now get the following error:

```
these derivations will be built:
  /nix/store/sj3i553ka89nzwj4jikmjplzm3if9v0c-ghcjs-0.1.0.drv
building path(s) ‘/nix/store/m9pj4b51h0nxqhpwfw9k0iz501lm2y3s-ghcjs-0.1.0’
created 335 symlinks in user environment
ghcjs-pkg-0.1.0-7.10.2: /nix/store/m9pj4b51h0nxqhpwfw9k0iz501lm2y3s-ghcjs-0.1.0/lib/ghcjs-0.1.0/package.conf.d/package.cache: you don't have permission to modify this file
builder for ‘/nix/store/sj3i553ka89nzwj4jikmjplzm3if9v0c-ghcjs-0.1.0.drv’ failed with exit code 1
error: build of ‘/nix/store/sj3i553ka89nzwj4jikmjplzm3if9v0c-ghcjs-0.1.0.drv’ failed
/home/vagrant/.nix-profile/bin/nix-shell: failed to build all dependencies
```

Strangely enough, I don't get this error with `nix-shell --pure -p haskell.compiler.ghcjs`, but I do when using the `*.nix` file. `chmod`-ing the file listed in the error message and its containing folder(s) solves the error, but that's obviously not a viable solution.

------

Contents of the `*.nix` file:

```
{ nixpkgs ? import <nixpkgs> {} }:

let

  inherit (nixpkgs) pkgs;

  f = { mkDerivation }:
      mkDerivation {
        pname = "foo";
        version = "0.0.0";
        src = ./.;
        isLibrary = true;
        isExecutable = true;
        libraryHaskellDepends = [ ];
        executableHaskellDepends = [ ];
        buildTools = [ pkgs.haskell.compiler.ghcjs ];
        license = "undefined";
      };

  drv = pkgs.haskell.packages.ghcjs.callPackage f {};

in

  if pkgs.lib.inNixShell then drv.env else drv
```

**Comment by mayhewluke** [comment]
After further digging it looks like the problem is in `ghcjs` being passed to `ghc.withPackages`.

`ghcjs` is a Haskell package according to `isHaskellPkg` ([here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix#L107)), and thus gets passed into`ghc.withPackages` in the definition of `ghcEnv` ([here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix#L123)). However, `ghcEnv` is only used when accessing the final Haskell derivation's `env` attribute, which was only used by `nix-shell`, not `nix-build`. This explains why those two commands were giving me different results.

I've tested overriding `ghcjs` so that it does not register as a Haskell package (I removed its `env` to trick `isHaskell`). This prevents `ghcjs` from being given to `ghc.withPackages` and solves the error that I was seeing (but is obviously not a good solution).

**Comment by peti** [comment]
Creating a `ghcWithPackages` environment that contains `ghcjs` *in addition* to the other GHC feels like a mistake, and it's no surprise that this doesn't work IMHO.

**Comment by mayhewluke** [comment]
Essentially what I wanted to create was a `nix-shell` environment where I had access to both `ghc` and `ghcjs`. This way I could compile both parts of my project without having to leave the shell and come back in to switch between `ghc`/`ghcjs`. Since the way `cabal2nix` sets up a `nix-shell` environment is to use the `env` attribute of a Haskell derivation I figured this is the recommended way, and stuck with that approach.

However, doing so passes *every* Haskell dependency of the derivation to `ghcWithPackages`, including `ghcjs` itself. This then results in an error, which as you say is unsurprising. The fact that `ghcjs` is passed to `ghcWithPackages` does seem a little surprising, though.

I think ultimately the question boils down to "How can I have a `nix-shell` environment with access to both `ghc` and `ghcjs`?"

**Comment by peti** [comment]
~~~~~
$ nix-shell -p haskell.packages.ghcjs.ghc -p haskell.packages.ghc7102.ghc

[nix-shell:~]$ type -p ghc
/nix/store/7hnlpxpmpka84zrhyq7z11bs0q3vgak1-ghc-7.10.2/bin/ghc

[nix-shell:~]$ type -p ghcjs
/nix/store/snnrizkv6cqapmrpcn5c1900sywaxjlr-ghcjs-0.1.0/bin/ghcjs
~~~~~~

**Comment by joachifm** [comment]
I believe the question has been answered. Please re-open if that's not the case.
