### ISSUE TITLE
Documentation loaOf is still in the nixos manual and not marked deprecated

### ISSUE THREAD

**Issue by voidIess** [NixOS/nixpkgs#98037]
**Describe the bug**
types.loaOf is described in the nixos manual under 44.2.3 although it has been marked deprecated: https://github.com/NixOS/nixpkgs/issues/1800. I think it should be removed or marked deprecated.

**Comment by worldofpeace** [comment]
If it's in the `20.03` manual which is default presented it wasn't removed yet so I guess it will still be in the manual. But now in `20.09` it has been removed https://github.com/NixOS/nixpkgs/pull/96042.
