### ISSUE TITLE
nixos containers with more security constraints

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#9804]
Systemd-nspawn already supports user namespaces, network namespaces, capability dropping. Also assigning an apparmor profile should proabably be possible. This could eventually make nixos containers usable in production. This also probably neeeds systemd upgrade.

**Comment by offlinehacker** [comment]
Also instead of systemd-nspawn we could use https://github.com/opencontainers/runc which is what docker uses.

**Comment by edolstra** [comment]
Yeah, using the new systemd-nspawn features sounds great. (We should have systemd-226 soon: http://hydra.nixos.org/jobset/nixos/systemd-226.)

**Comment by lethalman** [comment]
The recent systemd-nspawn is about on par with runc I think, plus systemd-nspawn has a great integration with the host systemd. I often use `systemctl -M machine` to control the container systemd. I wouldn't replace systemd-nspawn with runc.

**Comment by grahamc** [comment]
Should this ticket get some more attention, or closed until renewed interest comes along?

**Comment by zimbatm** [comment]
Closing as it's just an idea and we got Eelco's approval. Feel free to re-open if working on it or just push a PR.
