### ISSUE TITLE
how to install r pakage  in Rstudio  on Nixos？ 

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#98048]
> install.packages("rJava")
Installing package into ‘/home/prehonor/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/rJava_0.9-13.tar.gz'
Content type 'application/x-gzip' length 664898 bytes (649 KB)
==================================================
downloaded 649 KB

* installing *source* package ‘rJava’ ...
** package ‘rJava’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... /nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc accepts -g... yes
checking for /nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -E
checking for grep that handles long lines and -e... /nix/store/b0vjq4r4sp9z4l2gbkc5dyyw5qfgyi3r-gnugrep-3.4/bin/grep
checking for egrep... /nix/store/b0vjq4r4sp9z4l2gbkc5dyyw5qfgyi3r-gnugrep-3.4/bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether time.h and sys/time.h may both be included... yes
configure: checking whether /nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc supports static inline...
yes
checking whether setjmp.h is POSIX.1 compatible... yes
checking whether sigsetjmp is declared... yes
checking whether siglongjmp is declared... yes
checking Java support in R... present:
interpreter : '/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/jre/bin/java'
archiver    : '/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/jar'
compiler    : '/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/javac'
header prep.: '/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/javah'
cpp flags   : '-I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include'
java libs   : '-L/nix/store/yj12zbiana4dmyp9zxm09z1nx5cia6j0-openjdk-8u265-ga-jre/lib/openjdk/jre/lib/amd64/server -ljvm'
checking whether Java run-time works... yes
checking whether -Xrs is supported... yes
checking whether -Xrs will be used... yes
checking whether JVM will be loaded dynamically... no
checking whether JNI programs can be compiled... yes
checking whether JNI programs run... yes
checking JNI data types... ok
checking whether JRI should be compiled (autodetect)... yes
checking whether debugging output should be enabled... no
checking whether memory profiling is desired... no
checking whether threads support is requested... no
checking whether callbacks support is requested... no
checking whether JNI cache support is requested... no
checking whether headless init is enabled... no
checking whether JRI is requested... yes
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating R/zzz.R
config.status: creating src/config.h
=== configuring in jri (/run/user/1000/RtmpFdL883/R.INSTALL12bf14c0331a/rJava/jri)
configure: running /nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  'CC=gcc' --cache-file=/dev/null --srcdir=.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /nix/store/b0vjq4r4sp9z4l2gbkc5dyyw5qfgyi3r-gnugrep-3.4/bin/grep
checking for egrep... /nix/store/b0vjq4r4sp9z4l2gbkc5dyyw5qfgyi3r-gnugrep-3.4/bin/grep -E
checking for ANSI C header files... yes
checking Java version... 1.8.0_265
checking Java compatibility version (integer)... 8
checking whether /nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/javah actually works... yes
checking for target flags...  -target 1.4 -source 1.4
checking whether Java interpreter works... checking whether JNI programs can be compiled... yes
checking whether JNI programs can be run... yes
checking JNI data types... ok
checking whether Rinterface.h exports R_CStackXXX variables... yes
checking whether Rinterface.h exports R_SignalHandlers... yes
configure: creating ./config.status
config.status: creating src/Makefile
config.status: creating Makefile
config.status: creating run
config.status: creating src/config.h
** libs
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c Rglue.c -o Rglue.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c arrayc.c -o arrayc.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c callJNI.c -o callJNI.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c callback.c -o callback.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c fields.c -o fields.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c init.c -o init.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c jri_glue.c -o jri_glue.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c loader.c -o loader.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c otables.c -o otables.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c rJava.c -o rJava.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c registration.c -o registration.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -I"/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include" -DNDEBUG -I. -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include    -fpic  -g -O2  -c tools.c -o tools.o
/nix/store/m6h7zh8w6s52clnyskffj5lbkakqgywn-gcc-wrapper-9.2.0/bin/cc -shared -L/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/lib -o rJava.so Rglue.o arrayc.o callJNI.o callback.o fields.o init.o jri_glue.o loader.o otables.o rJava.o registration.o tools.o -L/nix/store/yj12zbiana4dmyp9zxm09z1nx5cia6j0-openjdk-8u265-ga-jre/lib/openjdk/jre/lib/amd64/server -ljvm -L/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/lib -lR
(cd ../jri && make)
make[1]: Entering directory '/run/user/1000/RtmpFdL883/R.INSTALL12bf14c0331a/rJava/jri'
make -C src JRI.jar
make[2]: Entering directory '/run/user/1000/RtmpFdL883/R.INSTALL12bf14c0331a/rJava/jri/src'
/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/javac -target 1.4 -source 1.4 -d . ../Rengine.java ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../RFactor.java ../REXP.java ../package-info.java
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
if [ -n "/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/javah" ]; then /nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/bin/javah -d . -classpath . org.rosuda.JRI.Rengine; fi
gcc -c -o Rengine.o Rengine.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2  -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include  -fpic -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include
gcc -c -o jri.o jri.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2  -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include  -fpic -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include
gcc -c -o Rcallbacks.o Rcallbacks.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2  -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include  -fpic -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include
In file included from /nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include/string.h:494,
                 from /nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include/R_ext/RS.h:34,
                 from /nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include/R.h:91,
                 from jri.h:5,
                 from Rcallbacks.c:4:
In function ‘strncpy’,
    inlined from ‘Re_ReadConsole’ at Rcallbacks.c:91:4:
/nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rcallbacks.c: In function ‘Re_ReadConsole’:
Rcallbacks.c:90:10: note: length computed here
   90 |    int l=strlen(c);
      |          ^~~~~~~~~
In file included from /nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include/string.h:494,
                 from /nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include/R_ext/RS.h:34,
                 from /nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include/R.h:91,
                 from jri.h:5,
                 from Rcallbacks.c:4:
In function ‘strncpy’,
    inlined from ‘Re_ChooseFile’ at Rcallbacks.c:190:6:
/nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rcallbacks.c: In function ‘Re_ChooseFile’:
Rcallbacks.c:189:11: note: length computed here
  189 |      slen=strlen(c);
      |           ^~~~~~~~~
gcc -c -o Rinit.o Rinit.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2  -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include  -fpic -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include -I/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/include
gcc -c -o globals.o globals.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2  -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include  -fpic -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include
gcc -c -o rjava.o rjava.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2  -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include  -fpic -I/nix/store/vjnc23gin8agj2d51mq86ypan8m59ljq-openjdk-8u265-ga/lib/openjdk/include
rjava.c: In function ‘RJava_request_lock’:
rjava.c:22:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   22 |   write(ipcout, buf, sizeof(ptrlong));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_clear_lock’:
rjava.c:30:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   30 |   write(ipcout, buf, sizeof(ptrlong));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_request_callback’:
rjava.c:39:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   39 |   write(ipcout, buf, sizeof(ptrlong) * 3);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_init_ctrl’:
rjava.c:51:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   51 |   write(ipcout, buf, sizeof(ptrlong));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c:52:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
   52 |   read(resin, buf, sizeof(ptrlong) * 2);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -o libjri.so Rengine.o jri.o Rcallbacks.o Rinit.o globals.o rjava.o  -shared -L/nix/store/yj12zbiana4dmyp9zxm09z1nx5cia6j0-openjdk-8u265-ga-jre/lib/openjdk/jre/lib/amd64/server -ljvm -Wl,--export-dynamic -fopenmp  -L/nix/store/vqzygc41gbzb1psnnxlvx7dcsf622svl-R-3.6.2/lib/R/lib -lR -lpcre -llzma -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/ld: cannot find -lpcre
/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/ld: cannot find -llzma
/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/ld: cannot find -lbz2
/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile.all:35: libjri.so] Error 1
make[2]: Leaving directory '/run/user/1000/RtmpFdL883/R.INSTALL12bf14c0331a/rJava/jri/src'
make[1]: *** [Makefile.all:19: src/JRI.jar] Error 2
make[1]: Leaving directory '/run/user/1000/RtmpFdL883/R.INSTALL12bf14c0331a/rJava/jri'
make: *** [Makevars:14: jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/home/prehonor/R/x86_64-pc-linux-gnu-library/3.6/rJava’
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

The downloaded source packages are in
	‘/run/user/1000/RtmpGZwN3M/downloaded_packages’

**Comment by Kazimazi** [comment]
I use rstudioWrapper and override packages.
Like this: (rstudioWrapper.override { packages = with rPackages; [ foreign readxl ]; })

**Comment by prehonor** [comment]
> I use rstudioWrapper and override packages.
> Like this: (rstudioWrapper.override { packages = with rPackages; [ foreign readxl ]; })

Thank you , I add the dependency of rJava package according to https://github.com/NixOS/nixpkgs-channels/blob/nixos-20.03/pkgs/development/r-modules/default.nix ,that works.
