### ISSUE TITLE
plover.dev: broken in nixos-unstable (master)

### ISSUE THREAD

**Issue by dnaq** [NixOS/nixpkgs#98069]
**Describe the bug**
plover in latest nixpkgs-master and nixos-unstable segfaults on start

**To Reproduce**
```
$ plover
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

**Expected behavior**
plover should start and not crash.

**Additional context**
This seems related to commit 7c07beb2a9388e78343ecb37caa739b0c9bbc4d4. Reverting that commit makes plover start again.

**Notify maintainers**
@Twey @KoviRobi @ttuegel 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.64, NixOS, 21.03pre243434.e0759a49733 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre243434.e0759a49733, home-manager"`
 - channels(dna): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ttuegel** [comment]
This looks like a failure to wrap the application correctly. Does it depend on `wrapQtAppsHook`?

**Comment by galagora** [comment]
Related to #98067

**Comment by delroth** [comment]
Just checked that this issue still reproduces on master, and there are reports it reproduces on 20.09 too. @ttuegel: it does, via libsForQt514.callPackage + mkDerivationWith.
