### ISSUE TITLE
Discord out of date

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#98085]
![Screenshot from 2020-09-16 21-24-14](https://user-images.githubusercontent.com/364160/93318700-1f5f2000-f863-11ea-9ead-20621820bf00.png)

**Notify maintainers**

@ldesgoui @MP2E @tadeokondrak

**Comment by tadeokondrak** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/97828
