### ISSUE TITLE
Use proper SDK and command-line tools on OS X 10.11

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#9809]
Some packages do not compile on OS X 10.11 (e.g., #9329). I believe this is because the 10.9 SDK and command-line tools no longer work reliably on 10.11. Replacing the 10.9 SDK and command-line tools with the 10.11 versions fixes the problem in my environment.

I don't know Nix well enough to provide a pull request for a proper fix that works for 10.11 and earlier versions, but for someone more knowledgeable, I believe the relevant Software Update catalog for the 10.11 tools is here:

https://swscan.apple.com/content/catalogs/others/index-10.11-1.sucatalog

**Comment by dhess** [comment]
BTW, once you do this, the next thing that happens is that, once clang is built, you will run into the linker problems again as described in #2208 (can't find <tt>-lSystem</tt>). So far, the only way I've been able to get around that is to add:

<pre>
export NIX_LDFLAGS_AFTER+=" -L/usr/lib"
export NIX_ENFORCE_PURITY=
</pre>

to the Darwin stage 3 stdenv prehook.

I've worked on it for 2 days and am really perplexed why the linker needs this when bootstrapped with the 10.11 command-line tools, but I don't understand the clang/ld wrapper script very well.

**Comment by dhess** [comment]
Actually, the built linker doesn't look in any of the standard locations, so you need to tell it about the system framework paths, as well:

<pre>
export NIX_LDFLAGS_AFTER+=" -L/usr/lib -F/Library/Frameworks -F/System/Library/Frameworks"
export NIX_ENFORCE_PURITY=
</pre>

**Comment by gridaphobe** [comment]
nixpkgs should be using the 10.11 SDK on 10.11, just like it uses the 10.9 SDK on 10.9, and 10.10 on 10.10.

We run

```
/usr/bin/xcrun --sdk macosx"$(/usr/bin/sw_vers -productVersion | /usr/bin/cut -d. -f1,2)" --show-sdk-path 2> /dev/null || echo /
```

to find the correct SDK, falling back to `/` in case XCode isn't present. Can you paste the output of that command? I don't have 10.11.

**Comment by dhess** [comment]
It's finding the 10.11 SDK correctly. Here are some relevant environment variables from a nix-shell:

<pre>
NIX_LDFLAGS_AFTER= -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib -L/usr/lib -F/Library/Frameworks -F/System/Library/Frameworks
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
NIX_CFLAGS_COMPILE= --sysroot=/var/empty -idirafter /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -Wno-multichar -Wno-deprecated-declarations -isystem /nix/store/bzslh5v1pq5wbj22a31j1cachqpjkwzl-libc++-3.7.0/include
</pre>

(Note that I added the <tt>/usr/lib</tt> and Frameworks bits to <tt>NIX_LDFLAGS_AFTER</tt> in my fork.)

**Comment by gridaphobe** [comment]
If it's finding the 10.11 SDK, you shouldn't need to add `-L/usr/lib`, the correct place to look for system libraries **is** the SDK.

Can you post a concrete error that your `NIX_LDFLAGS` fixes? Perhaps also the contents of `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib`?

**Comment by dhess** [comment]
See #2208 for the kind of errors that it fixes. Without <tt>-L/usr/lib</tt> the very first 'configure' check that runs after stdenv stage 3 is built (I believe it's perl?) breaks, saying that the compiler can't produce executables because it can't find <tt>-lSystem</tt>.

I'm afraid I don't have time at the moment to go back to master and rebuild from scratch to give you a specific error. I've already spent way too much time fixing this recently, and I've had to hack in a bunch of other fixes for 10.11 and Xcode 7 just to get to the point of being able to produce a stage 3 stdenv in the first place. They're in my darwin branch on my nixpkgs fork, if you're curious. (I haven't opened a pull request for them as they're just expedient hacks and will need some work from someone more knowledgeable about Nix than I before they're ready to be committed.)

Here are the contents of the 10.11 SDK /usr/lib: https://gist.github.com/dhess/b3a4efed3a2e3c1c042e

As you can see from the listing, libSystem.dylib has been replaced by a <tt>.tdb</tt> file, which contains some textual information about the dylib and its path, but not the modules. This is why the ldflags are needed to point at the actual dylib and Framework locations.

**Comment by gridaphobe** [comment]
The `.tdb` stuff is very strange, in the current version of XCode we have actual `.dylib`s in the SDKs. No wonder things are majorly broken on 10.11..

Based on https://forums.developer.apple.com/thread/4572 it seems that the `.tdb` files aren't actually supported by xcode (and presumably clang) yet. @pikajude do you know anything about this?

**Comment by dhess** [comment]
I've had no problems linking with the Xcode 7 command-line clang, so either it knows about the <tt>.tdb</tt> files in the SDK or it just looks in the system default areas. But even llvm-3.7 clang (released early September) doesn't know how to handle the .tdb files, so unless there's a 3.7.1 with support for them very soon, it seems pretty clear that Nix won't be able to use the SDK as a source for dylibs or Frameworks on 10.11.

**Comment by itkovian** [comment]
@dhess I've tried building with your changes to the stage3 prehook, but it's still not finding System, e.g., when building bzip2. Seems like it's not picking up the changes at all:

~~~~
...
clang -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c decompress.c
clang -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c bzlib.c
rm -f libbz2.a
ar cq libbz2.a blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o
ranlib libbz2.a
clang -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c bzip2.c
clang -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64  -o bzip2 bzip2.o -L. -lbz2
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~~

**Comment by dhess** [comment]
Try my fork, the 'elcap' branch. Works fine for me.

**Comment by itkovian** [comment]
I cannot get it to work. Restarted over, from master, with the changes mentioned above.

Ran ```nix-build pkgs/top-level/all-packages.nix -K -A bzip2```
~~~~
<snip>
clang -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64  -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib -L/usr/lib -F/Library/Frameworks -F/System/Library/Frameworks -o bzip2 bzip2.o -L. -lbz2
ld: library not found for -lSystem
~~~~

Running from the build dir that's kept yields (adding -v):

~~~~
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
 "/nix/store/0ygdzy2h6vvd81kxiqll678lbg9bl30a-CLTools_Executables_OSX109/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.7.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -o bzip2 -lcrt1.10.6.o -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib -L/usr/lib -L. bzip2.o -lbz2 -lSystem /nix/store/0ygdzy2h6vvd81kxiqll678lbg9bl30a-CLTools_Executables_OSX109/Library/Developer/CommandLineTools/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a -F/Library/Frameworks -F/System/Library/Frameworks
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~~

Removing the syslibroot option finally makes it build.

~~~~
/nix/store/0ygdzy2h6vvd81kxiqll678lbg9bl30a-CLTools_Executables_OSX109/Library/Developer/CommandLineTools/usr/bin/ld -demangle -dynamic -arch x86_64 -macosx_version_min 10.7.0 -o bzip2 -lcrt1.10.6.o -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib -L/usr/lib -L. bzip2.o -lbz2 -lSystem /nix/store/0ygdzy2h6vvd81kxiqll678lbg9bl30a-CLTools_Executables_OSX109/Library/Developer/CommandLineTools/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a -F/Library/Frameworks -F/System/Library/Frameworks
~~~~

At this point I've not really an idea how to remove that when building the stdenv. When syslibroot is defined, it's prepended to the other search dirs, so it can only find the .tbd files and not the actual .dylib files.

**Comment by henrytill** [comment]
Could we close this?  

For 10.11/Xcode 7 the new default stdenv should address some of these issues.

More information here: https://nixos.org/wiki/Nix_on_OS_X

**Comment by dhess** [comment]
Which should address these issues, the pure stdenv, or the impure stdenv?

**Comment by henrytill** [comment]
The new default, pure stdenv.

**Comment by dhess** [comment]
I'll try it on my 10.11 system and let you know.

**Comment by dhess** [comment]
Before I do so, a) is it safe to enable the sandbox now? and b) I assume I need to do this with nixpkgs from git as it's not in the unstable channel yet, yes?

**Comment by henrytill** [comment]
I would use Nix HEAD:
```
git clone https://github.com/NixOS/nix
cd nix
nix-env -f release.nix -iA build.x86_64-darwin --option build-use-chroot false
```
and set 
```
build-use-chroot = true
```
in `/etc/nix/nix.conf`

And yes, I would use a clone of nixpkgs, as suggested in the [wiki](https://nixos.org/wiki/Nix_on_OS_X)

**Comment by dhess** [comment]
OK, just for starters, after starting over from a clean slate (removed all traces of nixpkgs from my system, then installed nix-1.10 from the install script on https://nixos.org/nix, Xcode 7.1 and CLI tools are present), building Nix head fails:

```shell
checking whether Perl is recent enough... yes
checking for the Perl installation prefix... ${exec_prefix}/lib/perl5/site_perl/5.20.2/darwin-2level
checking for cat... /nix/store/vwyalibj4ml22gcniih6laf2ld37vbi9-coreutils-8.24/bin/cat
checking for tr... /nix/store/vwyalibj4ml22gcniih6laf2ld37vbi9-coreutils-8.24/bin/tr
checking for openssl... /nix/store/83za6xpr2jw6s93fxz4n3hf0fqdn6hcd-openssl-1.0.1p/bin/openssl
checking for pkg-config... /nix/store/d0fnz0f5kkiymiyjxyp0q8qkclibv98h-pkg-config-0.28/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OPENSSL... yes
checking for BZ2_bzWriteOpen in -lbz2... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for SQLITE3... yes
checking for LIBCURL... yes
checking for SODIUM... yes
checking for LIBLZMA... no
configure: error: Package requirements (liblzma) were not met:

No package 'liblzma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBLZMA_CFLAGS
and LIBLZMA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
build time elapsed:  0m0.083s 0m0.068s 0m3.731s 0m2.171s
builder for ‘/nix/store/x7rv5ar8yq5ayqdzl850z9m9gkj37m9l-nix-tarball-1.11pre1234_abcdef.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/c8x6g910wd3vnznr3w566nm54qp8mzlp-nix-1.11pre1234_abcdef.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/c8x6g910wd3vnznr3w566nm54qp8mzlp-nix-1.11pre1234_abcdef.drv’ failed
```

**Comment by dhess** [comment]
Looks like https://github.com/NixOS/nix/issues/671

**Comment by dhess** [comment]
I've worked around it, now doing a full build of my standard environment and I'll update you on how it goes.

**Comment by dhess** [comment]
OK, it's working fine here -- tested with several personal Haskell projects using GHC 7.10.2 from nixpkgs. Thanks for everyone's work on the Darwin pure stdenv! I think you can close this issue now.

**Comment by henrytill** [comment]
Glad to hear it.  I don't have the permissions to close this, but can't you do it as the person who opened it?
