### ISSUE TITLE
Add Desktop Item to Google-Play-Music-Desktop-Player

### ISSUE THREAD

**Issue by AlexGoico** [NixOS/nixpkgs#98139]
**Describe the bug**
There is no desktop item after installing google play music player.

**To Reproduce**
1. Install nixos
2. Enable KDE plasma in configuration.nix
3. `nix-env -i google-play-music-desktop-player`
4. Open the KDE search menu and search for google play music -- no results appear.

**Expected behavior**
When you search for google play music after installing google-play-music-desktop-player it should appear in the search bar as an option.

**Screenshots**
N/A

**Additional context**
This is an enhancement not a bug. This can probably most easily be fixed by using `makeDekstopItem`. See jetbrains IDE as an example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/jetbrains/common.nix

**Notify maintainers**
@SuprDewd 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.61, NixOS, 20.03.2964.252bfe01075 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(typedeph): `""`
 - channels(root): `"nixos-20.03.2964.252bfe01075"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
N/A

**Comment by h7x4** [comment]
Closing, the package has been removed from nixpkgs
