### ISSUE TITLE
can't install plasma: undefined variable 'colord-kde' 

### ISSUE THREAD

**Issue by ZerataX** [NixOS/nixpkgs#98142]
## Issue description

Trying to install plasma as a desktop manager results in the following error:

```
error: undefined variable 'colord-kde' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/plasma5.nix:312:55
(use '--show-trace' to show detailed location information)
```

### Steps to reproduce

1. use nixos-unstable channel
2. add `services.xserver.desktopManager.plasma5.enable = true;` to your config
3. run `nixos-rebuild switch`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre243434.e0759a49733"`
 - channels(kaine): `"home-manager-20.03, nixos-unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/97974
