### ISSUE TITLE
nixos manual: local version references online links (github)

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9820]
**EDIT: now see https://github.com/NixOS/nixpkgs/issues/9820#issuecomment-139850971 only.**

```
> nix-build nixos/release.nix -A manual.x86_64-linux
```

This creates the (offline) manual in a store path, but the links _in_ the docs lead to
1. an _online_ location
2. an _nonexisting_ location (e.g. https://github.com/NixOS/nixpkgs/blob/gfedcba/nixos/modules/services/misc/zookeeper.nix)

The solution is kind of meta, and I’m not sure how to make that work:
You need to put the nixpkgs _that are evaluated_ to create the documentation into a store path and link that from the created documentation.

**Comment by Profpatsch** [comment]
As a sidenote: I use this script to open the current manual:

```shell
#!/bin/sh
# build the current nixos manual and open the given file.
# nixos <file> <path-to-nixpkgs>
# where <file> is e.g. index or options

WHAT=$1
NIXPKGS=$2

cd "$NIXPKGS"
STOREPATH=$(nix-build nixos/release.nix -A manual.x86_64-linux | tail -n 1)

xdg-open "$STOREPATH/share/doc/nixos/$WHAT.html"
```

**Comment by vcunat** [comment]
Why not just run `nixos-help`? It's built with actual revision parameters of your installation (e.g. "gfedcba" is replaced).

Still, I do agree the github.com/NixOS/nixpkgs links should be replaced to local paths, at least optionally.

**Comment by Profpatsch** [comment]
Whoa, I’m reimplementing obvious stuff again.

But yeah, the absolute paths are still there.

**Comment by rasendubi** [comment]
(triage) still an issue

**Comment by Profpatsch** [comment]
yeah, hasn’t changed unfortunately.

**Comment by Profpatsch** [comment]
I don’t think it will change in the near future, and I haven’t been bothered enough by it, so it goes.
