### ISSUE TITLE
"nixos-rebuild switch" (seemingly) kills networking

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9821]
This is a thing that's happened numerous times. I'm logged into a remote system with ssh and run ```nixos-rebuild switch``` and my ssh session freezes, and I cannot reach the remote machine anymore.

Today I did a relatively small change (or so I thought):

```
$ sudo nixos-rebuild switch -Q
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
reloading the following units: dbus.service
restarting the following units: polkit.service
the following new units were started: docker.service
$
```

At this point my session froze. I cannot reach the machine anymore. It's not only ssh that's gone, I cannot even ping the machine. What is going on?

**Comment by bjornfor** [comment]
The first time this happened must have been more than a year ago. My remote machines have never been remote enough that I've bothered really debugging it (until now).

**Comment by lethalman** [comment]
It's weird, it never happened to me. What ssh client do you use?

**Comment by bjornfor** [comment]
The default one, openssh.

I have an ssh alias that runs screen inside the ssh session. (But I don't think that is relevant.)

**Comment by wkennington** [comment]
Reloading dbus is worrying because afaik that will completely break systemd.

**Comment by bjornfor** [comment]
@wkennington: Interesting.

On monday I'll check the journal and see if there is any hints about what went wrong. Btw, anyone else seen this issue?

**Comment by dezgeg** [comment]
On my server box I sometimes see the ssh connection getting stuck for a while (~a minute or so) after a upgrade, but then the connection resumes.

**Comment by lethalman** [comment]
@wkennington reloading doesn't break anything, maybe you thought restarting?

**Comment by wkennington** [comment]
Well, is the activation script not actually showing everything being
triggered to restart? It doesn't seem right that docker and polkit changing
would break networking.

**Comment by bjornfor** [comment]
Another data point, this one _without_ any issue. This is updating another NixOS machine on my LAN:

```
$ sudo nixos-rebuild switch -Q
...
updating GRUB 2 menu...
stopping the following units: ModemManager.service, accounts-daemon.service, alsa-store.service, avahi-daemon.service, cpufreq.service, cron.service, cups-browsed.service, cups.service, dbus-org.bluez.service, fail2ban.service, kmod-static-nodes.service, network-local-commands.service, network-manager.service, network-setup.service, nix-daemon.service, nscd.service, ntpd.service, rtkit-daemon.service, samba-nmbd.service, samba-smbd.service, samba-winbindd.service, systemd-logind.service, systemd-modules-load.service, systemd-sysctl.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-settle.service, systemd-udev-trigger.service, systemd-udevd.service, systemd-vconsole-setup.service, udisks2.service, upower.service, wpa_supplicant.service
Warning: Stopping nix-daemon.service, but it can still be activated by:
  nix-daemon.socket
Warning: Stopping systemd-udevd.service, but it can still be activated by:
  systemd-udevd-control.socket
  systemd-udevd-kernel.socket
NOT restarting the following changed units: display-manager.service, getty@tty1.service, systemd-backlight@backlight:intel_backlight.service, systemd-journal-flush.service, systemd-journald.service, systemd-random-seed.service, systemd-remount-fs.service, systemd-rfkill@rfkill0.service, systemd-tmpfiles-setup.service, systemd-update-utmp.service, systemd-user-sessions.service, user@1000.service
activating the configuration...
setting up /etc...
regenerating udev hardware database...
restarting systemd...
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, sys-fs-fuse-connections.mount, sys-kernel-debug.mount
restarting the following units: polkit.service, sshd.service
starting the following units: ModemManager.service, accounts-daemon.service, alsa-store.service, avahi-daemon.service, cpufreq.service, cron.service, cups-browsed.service, cups.service, dbus-org.bluez.service, fail2ban.service, kmod-static-nodes.service, network-local-commands.service, network-manager.service, network-setup.service, nix-daemon.service, nscd.service, ntpd.service, rtkit-daemon.service, samba-nmbd.service, samba-smbd.service, samba-winbindd.service, systemd-logind.service, systemd-modules-load.service, systemd-sysctl.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-settle.service, systemd-udev-trigger.service, systemd-udevd.service, systemd-vconsole-setup.service, udisks2.service, upower.service, wpa_supplicant.service
the following new units were started: NetworkManager-dispatcher.service
$
```

Ssh session works fine at this point, even with restarting/reloading of dbus, polkit and sshd.

**Comment by domenkozar** [comment]
@bjornfor for the first example breaking networking, can you post your configuration.nix changes and from and to what channel version did you upgrade?

**Comment by bjornfor** [comment]
@domenkozar: I'll see what I can find out on monday (when I get access to the machine again). But from memory, I only added "services.docker.enable = true;" and updated the 15.09 channel, before nixos-rebuild. I'm guessing either from 15.09.75.something (or later) and up to 15.09.308.2734724 (or something slightly earlier).

Note that I've had this issue a couple of times before, on the 14.12 branch. Then it was two completely different machines (and different network) than I use now.

Hm, if nobody else has ever seen this, I must be doing something weird/wrong. I hope I figure out something from the system log on monday.

**Comment by domenkozar** [comment]
It would also help to specify what kind of networking configuration do you use

**Comment by bjornfor** [comment]
I'm on the "remote" system now (it's a desktop machine at work). The only network config I have is ```networking.hostName = "i7pc-nixos"```. In other words, I use DHCP. (On the other system I've had this issue with, on nixos-14.12 about a 6 - 12 months ago, I used static IP address and disabled firewall.)

I don't see anything alarming in the journal (I can post the whole thing if necessary), but I find it interesting that even though the output of "nixos-rebuild switch -Q" didn't mention networking, the journal has this:

```
Sep 12 13:39:42 i7pc-nixos sudo[10166]: bfo : TTY=pts/3 ; PWD=/home/bfo/work/fara ; USER=root ; COMMAND=/run/current-system/sw/bin/nixos-rebuild switch -Q
...
Sep 12 13:39:46 i7pc-nixos nixos[10186]: switching to system configuration /nix/store/lgwal2xmx9wh0pa8c6y2b8n7zlc6ds19-nixos-15.09.295.f9799e7
...
Sep 12 13:39:46 i7pc-nixos systemd[1]: Stopping All Network Interfaces.
Sep 12 13:39:46 i7pc-nixos systemd[1]: Stopped target All Network Interfaces.
...
Sep 12 13:39:48 i7pc-nixos systemd[1]: Starting All Network Interfaces.
Sep 12 13:39:48 i7pc-nixos systemd[1]: Reached target All Network Interfaces.
```

I just learned that because I haven't configured the firewall, pings are not allowed (doh!). Further, my colleagues can ssh to my machine (all on local network, no VPN). So maybe the problem is at the other end. I'm confused.

**Comment by vcunat** [comment]
Our firewall disables ICMPv4 ping by default (I don't like that default personally). See `networking.firewall.allowPing`. The networking might be restarted by systemd because of some of the other (re)started units, e.g. you have `NetworkManager-dispatcher.service` in there (I'm just guessing).

**Comment by bjornfor** [comment]
There is no match for "NetworkManager" in the journal, in the relevant time period.

I've rebooted the machine now. When I get back home I'll try to SSH into it. I'm guessing my issue has little to do with NixOS :-/

**Comment by bjornfor** [comment]
It seems the VPN connection between home and work that is at fault. The timing just threw me off (it died immediately after nixos-rebuild over the SSH session).

I'm positive I've had some issues with nixos-rebuild over SSH in the past, but since I cannot reproduce this I'll close this now.
