### ISSUE TITLE
Packaging request: riscv-gnu-toolchain

### ISSUE THREAD

**Issue by leungbk** [NixOS/nixpkgs#98220]
**Project description**
GNU toolchain for RISC-V, including GCC.

**Metadata**

* homepage URL: https://github.com/riscv/riscv-gnu-toolchain
* source URL: https://github.com/riscv/riscv-gnu-toolchain
* license: gpl2
* platforms: linux, darwin

**Comment by ajs124** [comment]
What exactly are you looking for? nixpkgs does have support for cross-compiling to riscv, e.g. you can just build gnu hello with `nix-build -A pkgsCross.riscv64.hello` in a nixpkgs checkout.
