### ISSUE TITLE
Add gh (GitHub) CLI

### ISSUE THREAD

**Issue by rpearce** [NixOS/nixpkgs#98279]
**Project description**
The official `gh` (GitHub) CLI is now at `v1.0.0`.

**Metadata**

* homepage URL: https://github.com/cli/cli
* source URL: https://github.com/cli/cli/releases/tag/v1.0.0
* license: MIT
* platforms: linux, darwin, windows

**Comment by rpearce** [comment]
I'll try to contribute this, myself, but any advice would be appreciated on where it should live (like `pkgs/development/tools/github/gh`? Or `pkgs/development/tools/gh`?).

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/blob/61d75820cc77ae1e50cebb4e3102d9b2ebab173b/pkgs/applications/version-management/git-and-tools/gh/default.nix#L1-L43

It's available as in the attribute: `gitAndTools.gh`.

**Comment by rpearce** [comment]
Amazing! Apologies for the noise
