### ISSUE TITLE
nix: Nix cannot be install without `libcrypto.so.1.1` in the environment

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#98286]
**Describe the bug**
During the installation of Nix on CentOS 7.8.2003 with nix-user-chroot, it complains:
`/nix/store/4vz8sh9ngx34ivi0bw5hlycxdhvy5hvz-nix-2.3.7/bin/nix-store: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

It's true that there is no `libcrypto.so.1.1` (other versions of `libcrypto.so` are available in `/usr/lib`), but I think Nix should be able to download one itself and use it to ensure reproducibility.

I haven't tested in without nix-user-chroot (for that requires building a vm), and I don't have the root privilige of the machine where the issue occurs.

I have also filed an issue at nix-community/nix-user-chroot, which is [issue 18](https://github.com/nix-community/nix-user-chroot/issues/18).

**To Reproduce**
1. Boot into CentOS 7.8.2003 on a x86-64 machine
2. Make sure that `libcrypto.so.1.1` is not in the sysstem
3. Make sure that user namespaces are available for unpriviliged users, i.e. <br />
```console
$ unshare --user --pid echo YES
YES
```
4. Download `nix-user-chroot-bin-1.0.3-x86_64-unknown-linux-musl` from nix-community/nix-user-chroot [release 1.0.3](https://github.com/nix-community/nix-user-chroot/releases/tag/1.0.3)
5. Rename the above binary to `nix-user-chroot` and move it to a directory you like, said, `mydir`
6). Do <br />
```sh
cd mydir
chmod +x ./nix-user-chroot
mkdir -m 0755 .nix
./nix-user-chroot $PWD/.nix bash -c "curl -L https://nixos.org/nix/install | bash"
```

**Expected behavior**
Nix get installed without error.

**Screenshots**

**Additional context**
* Different versions of `libcrypto` in the environment
```console
$ find /usr/lib -name "*libcrypto*"
/usr/lib/.libcrypto.so.1.0.2k.hmac
/usr/lib/.libcrypto.so.10.hmac
/usr/lib/libcrypto.so.1.0.2k
/usr/lib/libcrypto.so.10
/usr/lib/pkgconfig/libcrypto.pc
/usr/lib/libcrypto.so.0.9.8e
/usr/lib/libcrypto.so.6
/usr/lib/.libcrypto.so.0.9.8e.hmac
/usr/lib/.libcrypto.so.6.hmac
/usr/lib/libcrypto.so
```
* `libcrypto` in the half-finished `/nix` directory.
```console
$ find .nix | grep libcrypto
.nix/store/0x3bf23q5lmdq77x5icr7c0ngvz25ms3-openssl-1.1.1g/lib/libcrypto.so
```

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
Nix hasn't been installed yet.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nix
# a list of nixos modules affected by the problem
module:
```

**Comment by symphorien** [comment]
can you check that 
* LD_LIBRARY_PATH is empty 
* ldd on nix only reports libs in the nix store ?

**Comment by ShamrockLee** [comment]
@symphorien 
* `LD_LIBRARY_PATH` is empty.
* Nix hasn't been (successfully) installed yet. There is no file named `ldd` in `/nix`.

**Comment by knedlsepp** [comment]
This issue seems very much specfic to `nix-user-chroot`. I'm closing this here to focus the discussion on: https://github.com/nix-community/nix-user-chroot/issues/18
