### ISSUE TITLE
RFP: libavif

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#98303]
**Project description**
friendly, portable C implementation of the AV1 Image File Format

**Metadata**

* homepage URL: https://github.com/AOMediaCodec/libavif
* source URL: https://github.com/AOMediaCodec/libavif
* license: mit?
* platforms: unix/linux

Notes: Building with libaom recommended, provides "avifenc"

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/98307
