### ISSUE TITLE
Impossible to initialize nvidia nvml : Driver/library version mismatch

### ISSUE THREAD

**Issue by khssnv** [NixOS/nixpkgs#98328]
**Describe the bug**
The issue is related to [nvtop](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/nvtop/default.nix) package. It does not work for with legacy driver intalled producing the following error.
```console
 % nvtop   
Impossible to initialize nvidia nvml : Driver/library version mismatch
```
I have a laptop (Asus UX32VD) with NVIDIA GeForce GT 620M GPU. It does not work with most recent driver requiring legacy one I install with
```console
services.xserver.videoDrivers = [ "modesetting" "nvidiaLegacy390" ];
```
in my `configuration.nix`. 

While [nvtop readme](https://github.com/Syllo/nvtop#gpu-support) says it should work with all GeForce 600+ GPU's, it fails on NixOS installation with legacy driver. How can we fix that? Thank you.

**To Reproduce**
1. Install nvidia legacy driver on NixOS tracking `unstable` channel with something like `services.xserver.videoDrivers = [ "modesetting" "nvidiaLegacy390" ];` in your `configuration.nix`
2. Install `nvtop` with `nix-shell -p nvtop`
3. Run `nvtop`

**Expected behavior**
I'm expecting `nvtop` works both with recent and legacy drivers too.

**Notify maintainers**
@willibutz

**Metadata**
```console
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.65, NixOS, 21.03pre243690.441a7da8080 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre243690.441a7da8080, home-manager"`
 - channels(khassanov): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eadwu** [comment]
This can probably be fixed by overriding `nvidia_x11` to point at `boot.kernelPackages.nvidiaPackages.legacy_390`
