### ISSUE TITLE
How to get Harfbuzz-0.0.gir into gobject-introspection?

### ISSUE THREAD

**Issue by cohomology** [NixOS/nixpkgs#98341]
## Issue description

I am beginner, but I try to use `NixOS` to compile a Haskell package which apparently needs gobject-introspection data for `harfbuzz`. Other distributions ship `HarfBuzz-0.0.gir` (see [Arch](https://www.archlinux.org/packages/extra/x86_64/harfbuzz/files/) here). I am no expert in NixOS, but there seems to be a Hen-Egg problem here, as all gobject-introspection data should reside inside `gobject-introspection`, but `Harfbuzz` needs `gobject-introspection`.

I looked how it's done for `cairo`, but the trick there doesn't seem to work, as the dependency there is reversed: `cairo` doesn't need `gobject-introspection`, but just the other way around.

@jtojnar : As you packaged `gobject-introspection`, you might have a clue.

See also [here](https://github.com/NixOS/nixpkgs/issues/34080), where the similar problem for `cairo` is addressed.

### Steps to reproduce

Not applicable

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 5.4.66, NixOS, 20.03.3000.faf5bdea5d9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(kilian): `"home-manager-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
I'm seeing the gir in
```
harfbuzz.dev
└── share
    └── gir-1.0
        └── HarfBuzz-0.0.gir
```

please see https://nixos.org/manual/nixpkgs/stable/#sec-language-gnome.
The bit on `gobject-introspection` setup hook and `wrapGAppsHook` are likely the issue here, and that I'm guessing `wrapGAppsHook` is missing from `nativeBuildInputs`.

**Comment by cohomology** [comment]
So you mean that `wrapGAppsHook` is missing in this [file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/harfbuzz/default.nix)?

**Comment by worldofpeace** [comment]
> So you mean that `wrapGAppsHook` is missing in this [file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/harfbuzz/default.nix)?

No, it would be the haskell package's executable that needs to be wrapped (as that is what I believe the issue here is)

> I am beginner, but I try to use NixOS to compile a Haskell package which apparently needs gobject-introspection data for harfbuzz.

**Comment by cohomology** [comment]
In my `/nix/store/10vkxyyap1spqphd73w198y3ig8120mb-harfbuzz-2.6.4-dev` there is no `gir` file. How did you get that?
```
./nix-support/propagated-build-inputs
./include/harfbuzz/hb-blob.h
./include/harfbuzz/hb-face.h
./include/harfbuzz/hb-font.h
./include/harfbuzz/hb-common.h
./include/harfbuzz/hb-aat-layout.h
./include/harfbuzz/hb-ot-shape.h
./include/harfbuzz/hb-unicode.h
./include/harfbuzz/hb.h
./include/harfbuzz/hb-subset.h
./include/harfbuzz/hb-ot-color.h
./include/harfbuzz/hb-aat.h
./include/harfbuzz/hb-version.h
./include/harfbuzz/hb-ot-var.h
./include/harfbuzz/hb-graphite2.h
./include/harfbuzz/hb-shape.h
./include/harfbuzz/hb-ft.h
./include/harfbuzz/hb-map.h
./include/harfbuzz/hb-shape-plan.h
./include/harfbuzz/hb-set.h
./include/harfbuzz/hb-ot-font.h
./include/harfbuzz/hb-buffer.h
./include/harfbuzz/hb-ot-layout.h
./include/harfbuzz/hb-ot-name.h
./include/harfbuzz/hb-ot.h
./include/harfbuzz/hb-glib.h
./include/harfbuzz/hb-ot-deprecated.h
./include/harfbuzz/hb-ot-math.h
./include/harfbuzz/hb-ot-meta.h
./include/harfbuzz/hb-deprecated.h
./include/harfbuzz/hb-ot-metrics.h
./bin/hb-ot-shape-closure
./bin/hb-shape
./bin/hb-view
./bin/hb-subset
./lib/cmake/harfbuzz/harfbuzz-config.cmake
./lib/pkgconfig/harfbuzz-subset.pc
./lib/pkgconfig/harfbuzz.pc
```

**Comment by jtojnar** [comment]
> No, it would be the haskell package's executable that needs to be wrapped (as that is what I believe the issue here is)

I believe the `*-gi` Haskell packages use GIRs to generate the bindings at build time (similarly to Rust).

> In my `/nix/store/10vkxyyap1spqphd73w198y3ig8120mb-harfbuzz-2.6.4-dev` there is no `gir` file. How did you get that?

We have only enabled building harfbuzz introspection files [recently](https://github.com/NixOS/nixpkgs/pull/93799) so you might need to update nixpkgs

**Comment by cohomology** [comment]
Ok thanks! I now got the `.gir` file. I don't get the Haskell `-gi` packages to compile yet, I always get these:
```
Linking /home/.../Development/github/cohomology/hlabyrinth/dist-newstyle/tmp/src-13832/gi-gdkpixbuf-2.0.24/dist/setup/setup ...
Could not load typelib for "GdkPixbuf" version "2.0".
Error was: Typelib file for namespace 'GdkPixbuf', version '2.0' not found (0)
CallStack (from HasCallStack):
  error, called at lib/Data/GI/CodeGen/LibGIRepository.hs:106:44 in haskell-gi-0.24.4-7a9abc5ed7778c1fbd53fc5feba145d091eb1277388694e0adff61d138da1e62:Data.GI.CodeGen.LibGIRepository
```
but I guess this is no bug for nixpkgs ;-).

**Comment by jtojnar** [comment]
Maybe some setup hooks are missing. I would look at other `-gi` packages that compile how they do it.

**Comment by jtojnar** [comment]
Actually, `haskellPackages.gi-harfbuzz` seems to be fetched from binary cache on 2a35f664394b379e0c0785cc769ff6ccc791be39 so it builds on nixos-unstable.

**Comment by cohomology** [comment]
Very probably, I might be doing something wrong ;-). Probably something to do with my `pkg-config` setup. I will try tomorrow again and now close the ticket. Thanks for you help!
