### ISSUE TITLE
Steam segfaults on specific hardware (though it works under Fedora)

### ISSUE THREAD

**Issue by unclechu** [NixOS/nixpkgs#98362]
**Describe the bug**
On my PC Steam is failing to run. I followed all the instructions on the [NixOS Steam Wiki page](https://nixos.wiki/wiki/Steam) and tried it with all the possible options (it works absolutely fine on my laptop though).

I also tried to run SOMA the game from GOG via `steam-run`. It shows me modal window with this text: `FATAL ERROR: Could not create window!` with nothing useful in the log.

Also I used to run both Steam and SOMA on this same PC under Fedora Workstation 30 distro and it was absolutely fine. So I know for sure it should work on this hardware.

I tried both `amdgpu` and `radeon` drives, the same story for both.

`glxgears` are running fine (as well as hardware acceleration in Firefox and `picom` with `glx` backend).

**To Reproduce**
Steps to reproduce the behavior (but only on specific hardware):
1. `nix-shell -p steam --run steam`

Or try to run SOMA:
1. `cd GOG\ Games/SOMA/`
1. `nix-shell -p steam --run 'steam-run ./start.sh'`
   It shows only `Running SOMA` in the log and then a monal window: `FATAL ERROR: Could not create window!`

**Expected behavior**
Steam runs without segfaults showing the authorization modal window.

**Screenshots**
Steam:
![2020-09-21 04-14-10](https://user-images.githubusercontent.com/799353/93726914-38e4cc80-fbc1-11ea-92e6-f8b4009c6d41.png)
SOMA:
![2020-09-21 01-35-59](https://user-images.githubusercontent.com/799353/93727109-49e20d80-fbc2-11ea-9db9-163678f3676f.png)

**Additional context**
Here is my config: https://github.com/unclechu/nixos-config/tree/ec2cb7314b2b19ac32e0fc98d486c8107b3c9e4e

I can successfully run Steam on my laptop: https://github.com/unclechu/nixos-config/blob/ec2cb7314b2b19ac32e0fc98d486c8107b3c9e4e/hardware/rw-wenzel-nixos-laptop.nix (hardware-specific config).

And here is the hardware-specific config of my PC: https://github.com/unclechu/nixos-config/blob/ec2cb7314b2b19ac32e0fc98d486c8107b3c9e4e/hardware/wenzel-nixos-pc.nix on which Steam is failing to run with a segfault.

Stdout & stderr log of Steam: [steam.log](https://github.com/NixOS/nixpkgs/files/5253103/steam.log)

Strace log of Steam (nothing useful if you ask me): [steam.strace.log](https://github.com/NixOS/nixpkgs/files/5253118/steam.strace.log)

CPU:
```
λ grep 'model name' </proc/cpuinfo
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
```

GPU (with `radeon` driver it looks different):
```
λ glxinfo | rg -i opengl
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) R7 300 Series (BONAIRE, DRM 3.37.0, 5.7.19, LLVM 9.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.7
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.7
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

```
λ glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
349 frames in 5.0 seconds = 69.738 FPS
```

OpenGL configuration:
https://github.com/unclechu/nixos-config/blob/ec2cb7314b2b19ac32e0fc98d486c8107b3c9e4e/configuration.nix#L199-L215

**Notify maintainers**
@jagajaga

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.09alpha290.3b8ddb2f1ee (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09alpha290.3b8ddb2f1ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
according to https://www.ibm.com/support/pages/x-error-failed-request-badwindow-invalid-window-parameter, you could try setting `LC_ALL=C` before launching. But I'm not actually sure.

**Comment by unclechu** [comment]
@jonringer This didn’t change anything,

**Comment by unclechu** [comment]
I wonder if these libGL errors are caused by all other X errors:
```
X Error of failed request:  GLXBadContext
Major opcode of failed request:  152
Serial number of failed request:  164
xerror_handler: X failed, continuing
libGL error: failed to create drawable
libGL error: failed to create drawable
```

**Comment by unclechu** [comment]
It starts with this one:

**Comment by unclechu** [comment]
It starts with this one:
```
Loaded SDL version 2.0.13-5919606
Installing breakpad exception handler for appid(steam)/version(1599174997)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  1 (X_CreateWindow)
Serial number of failed request:  57
xerror_handler: X failed, continuing
Steam: An X Error occurred
```
**P.S. Accidentally closed the issue and reopened it**

**Comment by unclechu** [comment]
Ha! Fixed it by replacing `DefaultDepth 30` to `DefaultDepth 24`.
Thanks to [Arch Wiki](https://wiki.archlinux.org/index.php/AMDGPU) (see *“Xorg or applications will not start”*).
Both Steam and SOMA are working fine now.
