### ISSUE TITLE
Ponyc out of date (should be 0.37.0 at least)

### ISSUE THREAD

**Issue by jasoncarr0** [NixOS/nixpkgs#98376]
## Issue description

Previously, `ponyc` was updated automatically, but it has fallen off this track after the project switched to cmake

### Steps to reproduce

N/A

## Technical details

The project now needs to use `cmake` and possibly a few other changes. https://github.com/ponylang/ponyc/blob/master/BUILD.md has the updated build instructions, which include a preconfigure `make libs` piece. I was unable to get cmake to be happy with LLVM for these pieces

**Comment by jasoncarr0** [comment]
Maintainers are @doublec @kamilchm  @patternspandemic

**Comment by redvers** [comment]
https://github.com/NixOS/nixpkgs/pull/98568

See PR#98568

**Comment by redvers** [comment]
Completed.

<3
