### ISSUE TITLE
pkg freeoffice (softmaker) - sha256 missmatch

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#98385]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

pkg
https://github.com/NixOS/nixpkgs-channels/blob/nixos-20.03/pkgs/applications/office/softmaker/freeoffice.nix

### error (via home-manager)
trying https://www.softmaker.net/down/softmaker-freeoffice-976-amd64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   356  100   356    0     0   4564      0 --:--:-- --:--:-- --:--:--  4564
100  121M  100  121M    0     0  3117k      0  0:00:39  0:00:39 --:--:-- 3029k
hash mismatch in fixed-output derivation '/nix/store/1n38gbp3z91w0i3wiwsgzxw7ilb477vn-softmaker-freeoffice-976-amd64.tgz':
  wanted: sha256:13yh4lyqakbdqf4r8vw8imy5gwpfva697iqfd85qmp3wimqvzskl
  got:    sha256:1c5div1kbyyj48f89wkhc1i1759n70bsbp3w4a42cr0jmllyl60v

# 
nix-env -iA nixos.freeoffice

### test sha
#
nix-prefetch-url --unpack https://www.softmaker.net/down/softmaker-freeoffice-976-amd64.tgz
 1107zpbzx5ga9iylixsdr6bdkdvd69kzcj09shv5wy54b5nis3kj

nix-prefetch-url '<nixpkgs>' -A freeoffice.src 
 1c5div1kbyyj48f89wkhc1i1759n70bsbp3w4a42cr0jmllyl60v

wget https://www.softmaker.net/down/softmaker-freeoffice-976-amd64.tgz
nix-hash --flat --base32 --type sha256 softmaker-freeoffice-978-amd64.tgz
 1c5div1kbyyj48f89wkhc1i1759n70bsbp3w4a42cr0jmllyl60v

**Notify maintainers**

@danieldk

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.03.2652.076c67fdea6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(ae): `"OsUnstable-21.03pre243854.2a14d21224f, NxUnstable-21.03pre243968.2a35f664394, home-manager-20.03, nixos-20.03.3002.773ef5ae783"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by danieldk** [comment]
This is a known problem, upstream replaces existing versions when there is a new release:

https://discourse.nixos.org/t/hosting-binary-source-tarballs/5998
https://forum.softmaker.com/viewtopic.php?f=320&t=19327

This is quite a frustrating problem - I don't see these failures, because I the old FreeOffice and Softmaker Office versions in my binary cache and Hydra doesn't build these derivations because they are non-free. If it was a rare occurrence, it would be ok, but there are quite regular updates. I will try to make an update script, hopefully that simplifies maintenance.

**Comment by InLaw** [comment]
is there an known rev of nixpkgs or nixos which I could use where the sha was right?

**Comment by danieldk** [comment]
> is there an known rev of nixpkgs or nixos which I could use where the sha was right?

The sha was always right when a new version was added to nixpkgs. The problem is that Softmaker retroactivaly makes the URLs of all old version redirect to the latest.

**Comment by danieldk** [comment]
The update for `freeoffice` is now in master. I have made a backport for 20.09 (#98411). I will also backport to 20.03, but for that we need to land #98413 in master first, because otherwise FreeOffice/SoftMaker Office segfault in various commands for a minute before starting.
