### ISSUE TITLE
Get rid of bundled dependencies in libreoffice

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#9841]
Bonus points: set `lib` as an extra output.

**Comment by 7c6f434c** [comment]
@vcunat Yes, I have read the issue already.

Various versions of LO make getting rid of some of the bundled dependencies easier or harder; getting rid of all of the bundled dependencies is quite a lot of work, but possibly Debian has already published most of that work in a usable form.

Getting rid of all bundled dependencies will be a net loss of reliability of the build for some time, maybe it will et better later.

**Comment by domenkozar** [comment]
I've partially addressed this in https://github.com/NixOS/nixpkgs/commit/66e6f99d40350a4b2a235913a1fa77d88b1a44a6

**Comment by vcunat** [comment]
Ah, then we might prefer to wait a while to see whether there are (significant) problems after such changes or not...

**Comment by 7c6f434c** [comment]
Well, if the related functionality looks like working after such a change, there is a good chance that it actually works.

My experience is based on some of similar changes breaking builds completely; hopefully, partial breakage is less  common.

**Comment by domenkozar** [comment]
A good reference is Gentoo ebuild, they have packaged everything except the ddl: https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-office/libreoffice/libreoffice-5.0.0.5.ebuild?view=markup

**Comment by edolstra** [comment]
Note that this kind of change is likely to make the libreoffice closure *larger* because you get all the unnecessary stuff from the dependencies (like header files).

**Comment by domenkozar** [comment]
We should be able to just set `lib` as extra output, right?

**Comment by edolstra** [comment]
Yes, but we don't have multiple outputs for most packages yet.

**Comment by domenkozar** [comment]
OK, I've updated the description, I agree closure size should also be accounted for. The hardest part will be figuring out what build dependencies for libreoffice won't be needed anymore (which was my primary goal)

**Comment by vcunat** [comment]
Well, unbundling libraries that aren't used anywhere else (in nixpkgs) won't bring many benefits, I suppose.

**Comment by domenkozar** [comment]
Actually let's close this due to points raised above.
