### ISSUE TITLE
GDM autoLogin doesn't work

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9843]
This is my config:

```
services.xserver.displayManager.gdm = {
  enable = true;
  autoLogin.enable = true;
  autoLogin.user = "bfo";
};
```

I'm still presented with the login screen and have to type my password. Tested on git master (nixos-version => 16.03.git.bb1540c (Emu)).

**Comment by bjornfor** [comment]
CC @lethalman.

**Comment by lethalman** [comment]
It does work for me, but it takes a few seconds.

**Comment by lethalman** [comment]
Ok turns out `AutomaticLogin` is faster than using `TimedLogin` with 0 seconds.

**Comment by bjornfor** [comment]
How many seconds? I guess I didn't wait very long, because I thought the login screen shouldn't be visible at all.

**Comment by lethalman** [comment]
@bjornfor seemed to me like 5-10 seconds. Yes, with AutomaticLogin the login screen is not even presented.

**Comment by bjornfor** [comment]
@lethalman: Thanks. I'll test when I get back home. And backport to release-15.09 if it works OK.
