### ISSUE TITLE
20.09: allow hardware.u2f to be superfluously set, to ease staged migrations

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#98456]
**Describe the bug**
I am performing a staged upgrade of my machines from 20.03 to 20.09: one machine at a time.

My machines all use a common module, which sets `hardware.u2f.enable = true`.

`hardware.u2f` is no longer used (as of https://github.com/NixOS/nixpkgs/pull/90343), and thus the existence of it is treated as a failed assertion.

Though I can see setting `hardware.u2f.enable = true` is useless on a 20.09 machine, it is convenient to set it, since it allows my 20.09 machines and 20.03 (soon to be deployed) machines to continue use my common module.

Concrete proposal:
* For 20.09, warn if hardware.u2f is set.
* For 21.03, error if hardware.u2f is set.

This then allows fleets of machines to be upgraded in a staged manner (one machine at a time), and still preserve's NixOS's goal of deprecating superfluous options.

**To Reproduce**
1. Have two 20.03 machines (A,B), that each use a common module that sets `hardware.u2f.enable = true`
1. Set A to use 20.09 (ba0bd29a1aef66a67b50f377413b05ae402f4fc3 is what I'm using)
1. Build A

**Expected behavior**
A is able to build against 20.09, but a warning is output that `hardware.u2f` is superfluous.
B is able to build against 20.03 (since hardware.u2f is useful on 

**Actual behaviour**
```
Failed assertions:
- The option definition `hardware.u2f' in `/blah/blah/blah/common.nix' no longer has any effect; please remove it.
The U2F modules module was removed, as all it did was adding the
udev rules from libu2f-host to the system. Udev gained native support
to handle FIDO security tokens, so this isn't necessary anymore.
```

**Notify maintainers**
@flokli 

**Metadata**
I'm using commit ba0bd29a1aef66a67b50f377413b05ae402f4fc3 as my nixos 20.09 version.

Maintainer information:
```yaml
attribute: udev
module: hardware
```

**Comment by tomfitzhenry** [comment]
https://github.com/NixOS/nixpkgs/pull/90343 uses mkRemovedOptionModule which uses an assertion in `master`: https://github.com/NixOS/nixpkgs/blob/23370afcedc46f63ea0dc7328bcb1f40d78887bf/lib/modules.nix#L711-L737 .

Historically this function produced a warning, which was changed in https://github.com/NixOS/nixpkgs/commit/b08b0bcbbec77046e5a7082177cedc12fbf1dc6c.

So I think this issue is ultimately asking for:
* mkRemovedOptionModule, which will use an assertion (i.e. stay the same)
* mkSuperfluousOptionModule, which will warn
* hardware.u2f to use mkSuperfluousOptionModule in 20.09
* hardware.u2f to use mkSuperfluousOptionModule in 21.03.

**Comment by tomfitzhenry** [comment]
> Do we have a way to remember to change options that defined with mkSuperfluousOptionModule to use mkRemovedOptionModule instead?

I suppose this isn't different to how we remember to clean up old occurrences mkRemovedOptionModule. This issue is just proposing having an extra step.

Option is used => Option is marked as deprecated (mkSuperfluousOptionModule) => Option is marked as removed. (mkRemovedOptionModule) => Option is removed from VCS.

I'll write a PR.

**Comment by flokli** [comment]
I'm not sure if this is desirable - it creates much more git noise when changing `mkSuperfluousOptionModule` to `mkRemovedOptionModule`.

If you can't migrate all your machines at once, can't you just check for the nixpkgs version in your configuration code, and set it optionally, depending on `(pkgs.lib.versionOlder pkgs.lib.version "20.09")`?

**Comment by tomfitzhenry** [comment]
> I'm not sure if this is desirable - it creates much more git noise when changing mkSuperfluousOptionModule to mkRemovedOptionModule.

Yes, that makes sense.

> If you can't migrate all your machines at once, can't you just check for the nixpkgs version in your configuration code, and set it optionally, depending on (pkgs.lib.versionOlder pkgs.lib.version "20.09")?

Yes. It'd be nice if nixpkgs did this where appropriate, but I agree the downsides of introducing mkSuperfluousOptionModule aren't worth the benefits.

I'll close this.
