### ISSUE TITLE
Add sof (modern laptop sound) support for PulseAudio & GNOME

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#98470]
**Project description**

Some recent Dell and Lenovo laptops use SOF for audio, which requires UCM support in PulseAudio:

* https://mail.gnome.org/archives/distributor-list/2020-September/msg00001.html
* https://gitlab.gnome.org/GNOME/libgnome-volume-control/-/merge_requests/10#note_915865

NixOS [supports](https://github.com/NixOS/nixpkgs/commit/6fc9fd53dba25f61a6493e7c0d8fef5eca9c51bf) sof since kernel 5.5 (backported to NixOS 20.03) so we need to apply the patches above if we want sound on modern laptops to work.

**Comment by jtojnar** [comment]
I am not sure which patch is needed for Pulseaudio so we might need to package master like Arch does. But beware of https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1000.

**Comment by worldofpeace** [comment]
This is what fedora did for fedora 32 https://src.fedoraproject.org/rpms/pulseaudio/commits/f32
