### ISSUE TITLE
fstab "user" and "users" options need setuid mount/umount commands

### ISSUE THREAD

**Issue by khumba** [NixOS/nixpkgs#9848]
Currently, the "user" and "users" fstab mount options, that let users mount predefined mount points without authenticating, don't work on NixOS because mount and umount from util-linux need to be setuid.  It seems to be standard to install these with setuid (I looked at Gentoo and Debian).  Any objections to making them so on NixOS?

**Comment by jagajaga** [comment]
I'm using both `user,users` and everything works.

**Comment by edolstra** [comment]
I don't think we should make mount setuid. The modern approach is to use udisks.

**Comment by khumba** [comment]
On Mon, Sep 14, 2015 at 03:30:26AM -0700, Arseniy Seroka wrote:
> I'm using both `user,users` and everything works.

What do you mean, how are you mounting it?  It doesn't work with
util-linux's mount command with those flags in fstab, e.g.

    fileSystems."/mnt/usb" = { options = "noauto,user,users"; }

    $ mount /mnt/usb
    mount: must be superuser to use mount

On Mon, Sep 14, 2015 at 03:51:21AM -0700, Eelco Dolstra wrote:
> I don't think we should make mount setuid. The modern approach is to
> use udisks.

What's wrong with the existing approach?  You're still communicating
with a process that has root.  I understand wanting to minimize the
number of setuid binaries on the system, but I think the risk is low
given the maturity of util-linux.  DEs integrate with udisks, but I
would think this would more be hit by WM and CLI users, and for my use
case, enabling this seems simpler than switching to udisks.
Configuring fstab is way simpler than configuring polkit, and also
udisksctl doesn't seem to support mounting by mountpoint.  It
shouldn't take a mounting daemon to mount filesystems as a user.  So
much needless complexity :(.

If you don't want to support this, then I'll respect that; at least
it's a simple setting to maintain.  I do wish there had been some
indication of what was wrong so I didn't have to investigate.  Perhaps
fstab generation should fail if it contains one of these options and
mount and umount aren't setuid.  I'd suggest a configuration option
for this setuid, but that would be more code than simply adding mount
and umount to security.setuidPrograms, and that seems silly.

**Comment by jagajaga** [comment]
You have to mount it by root and it will be accessible to users via these options. (That is what I do).

**Comment by khumba** [comment]
On Mon, Sep 14, 2015 at 01:32:59PM -0700, Arseniy Seroka wrote:
> You have to mount it by root and it will be accessible to users via
> these options. (That is what I do).

Apologies, I don't follow.  If you're mounting it as root, then what
do "user" and "users" give you?  I thought they were only for allowing
mounting as non-root.  Are they useful with filesystems without
permissions to give group and other permissions or something?

**Comment by vcunat** [comment]
I do think the main point of those fstab options is to be able to mount as a user. I'm not certain of extending our setuid usage for this (by default).

BTW, for you it's probably easier to add `security.setuidPrograms` into your `configuration.nix` than maintaining a patch atop nixpkgs.

**Comment by wkennington** [comment]
`man fstab`

Common for all types of file system are the options ''noauto'' (do not
mount when "mount -a" is given, e.g., at boot time), ''user'' (allow a user
to mount)

I think this is directly relevant and is the feature he is asking for here.
I don't know if udisks handles this now but it would require setuid to
mount if not.

**Comment by khumba** [comment]
Okay, let's see if Github is any happier with this quoting style...

"BTW, for you it's probably easier to add `security.setuidPrograms`
into your `configuration.nix` than maintaining a patch atop nixpkgs."

Aye, it makes more sense, although it's six of one, half a dozen of
the other, already having nixpkgs.git and nixos-etc.git and forgetting
to make sure they're on corresponding branches sometimes :).

"I don't know if udisks handles this now but it would require setuid
to mount if not."

Udisks ignores user/users completely, and quoting udisks(8):

"By default, logged-in users in active log-in sessions are permitted
to perform operations (for example, mounting, unlocking or modifying)
on devices attached to the seat their session is on."

So yes you can use udisksctl as long as your session is active, and
you only use the device path.  This is more permissive than fstab in
that users can mount devices that aren't in fstab.

One possible argument against is that NixOS modules' list options are
additive by nature; I'm not sure if it's possible to specify a value
to remove?

Vladimír, Eelco, what do you think of fstab generation asserting
setuid mount/umount then?  It should abort if it knows that part of
fstab is not going to work.

**Comment by vcunat** [comment]
Hmm, this thread's syntax seems broken in a way I haven't yet seen on GitHub. I'm unable to completely fix it within a minute or two.

> what do you think of fstab generation asserting setuid mount/umount then? It should abort if it knows that part of fstab is not going to work.

I think warning when the options are specified an wouldn't work is fine. It could even advise you to add (u)mount to `security.setuidPrograms`.

**Comment by khumba** [comment]
> Hmm, this thread's syntax seems broken in a way I haven't yet seen
> on GitHub. I'm unable to completely fix it within a minute or two.

Aha, that looks better, thanks.  I've had other recent comments of
mine look totally messed up as well, sigh.

https://github.com/haskell/haskell-mode/issues/851#issuecomment-138134386
https://github.com/haskell/haskell-mode/issues/851#issuecomment-138140917

**Comment by lethalman** [comment]
:+1: , otherwise the fstab user feature is like being removed in nixos. mount and umount ae setuid in every distro, I don't see why not on nixos too. Don't really care about udisks.

**Comment by edolstra** [comment]
Setuid programs were never a good idea on *any* distribution, but they're especially problematic on NixOS because Nix doesn't support them. So we need hacks like setuid wrappers to support them. The fewer setuid binaries we have, the better. There are cases where we don't have an alternative for making something setuid at the moment (e.g. `passwd`), but IMHO that's not the case for mount - we've done fine without setuid mount for years.

**Comment by joachifm** [comment]
What is the verdict on this issue? Can it be closed? Makes sense to me, fwiw.

**Comment by alexvorobiev** [comment]
Note that in case of CIFS (Windows) mounts there has to be a wrapper for `mount.cifs` as well:
```
"mount.cifs".source = "${pkgs.cifs-utils}/bin/mount.cifs";
```
