### ISSUE TITLE
Cannot mount ZFS filesystems as of ZFS 0.6.5 update 

### ISSUE THREAD

**Issue by Shados** [NixOS/nixpkgs#9850]
As of the ZFS update to 0.6.5 in commits 6727f767395b8da7700bc56694a51e13e7f07144 and 9cb93e7966414be2b7fe11bd361a6893463c7ea7, my system fails to mount ZFS filesystems with `invalid argument`. It does successfully import the pool, and running a scrub doesn't return any errors, I just can't mount any filesystems inside the pool.

This is somewhat problematic when I'm using a ZFS root. Reverting just those two changes on top of the current unstable channel causes ZFS to work fine.

I ran into the issue using the git version of zfs, @nathanielbaxter has the same problem running on the stable version of zfs.

**Comment by wkennington** [comment]
I just ran a test to try and replicate the breakage and it seems to be
working fine for me. I created a pool called test on a single disk. Set the
mountpoint to legacy. Then added a filesystems entry for that mountpoint.
At bootup it looks like it was mounted successfully and present with the
file i added prior to rebooting. This is using 0.6.5 on kernel 4.2.

**Comment by Shados** [comment]
Hmmm. Non-default properties on the fs that is failing to mount:

```
NAME                  PROPERTY              VALUE                  SOURCE
snu1_root/ROOT/nixos  mountpoint            legacy                 local
snu1_root/ROOT/nixos  compression           lz4                    inherited from snu1_root
snu1_root/ROOT/nixos  relatime              on                     inherited from snu1_root
```

All supported feature flags on the git version are enabled for the pool. I tried using 0.6.5 with kernels 3.18, 4.1 and 4.2, all of them had the same issue.

It's possible the issue only occurs inside the initramfs environment, given both me and @nathanielbaxter were testing with ZFS root systems.

**Comment by dasjoe** [comment]
This, too, should be fixed by upgrading to ZoL 0.6.5.1.

**Comment by nathanielbaxter** [comment]
0.6.5.1 fixed the issue for me. Thanks.

**Comment by Shados** [comment]
Mm, I've given this a test with 0.6.5.1 and it works for me as well, so I'll close this issue off :).
