### ISSUE TITLE
[20.09] plasma5: printer dialog not working

### ISSUE THREAD

**Issue by samuelgrf** [NixOS/nixpkgs#98536]
**Describe the bug**
The printer dialog in the Plasma 5 taskbar doesn't work and outputs this error message:
```
Error loading QML file: file:///nix/store/anghgivrxfzkkag6s8rkxb6dr25p29i1-print-manager-20.08.1/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/printmanager.qml:64:34: Type PopupDialog unavailable
file:///nix/store/anghgivrxfzkkag6s8rkxb6dr25p29i1-print-manager-20.08.1/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/PopupDialog.qml:81:23: Type PrinterItem unavailable
file:///nix/store/anghgivrxfzkkag6s8rkxb6dr25p29i1-print-manager-20.08.1/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/PrinterItem.qml:28:1: Type PlasmaExtras.ExpandableListItem unavailable
file:///nix/store/sgi7dk5siyfarhq30piyx6f7m1wpk0kc-plasma-framework-5.73.0-bin/lib/qt-5.12.7/qml/org/kde/plasma/extras/ExpandableListItem.qml:20:1: module "QtQuick" version 2.14 is not installed
```

**To Reproduce**
1. Enable the plasma desktop.
2. Have the printer widget in your taskbar, or add it to your desktop.

**Screenshots**
![Screenshot_20200922_092032](https://user-images.githubusercontent.com/67663538/93979201-5068b480-fd7d-11ea-9af7-90d9a3d5914a.png)

**Additional context**
This issue also happens on a newly created user with an empty home directory.

**Notify maintainers**
@ttuegel @andir @edolstra @flokli

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-zen1, NixOS, 20.09alpha290.3b8ddb2f1ee (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager, nixos-20.09alpha290.3b8ddb2f1ee, nixos-unstable-21.03pre244365.06b27898a45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:plasma5
```

**Comment by samuelgrf** [comment]
I ran git bisect on nixpkgs, the culprit is ce4eb0b79b3b8e830d40345fb6457fac6ca9a9ec (plasma5: pin to qt512) from https://github.com/NixOS/nixpkgs/pull/97524.

**Comment by worldofpeace** [comment]
Is this still an issue?
cc @ttuegel 

I would block on this since printing is a minimal release requirement in DE's.

**Comment by ttuegel** [comment]
I'm investigating.

I wouldn't block on this because there is a workaround: the user can point their browser at `localhost:631` and use the CUPS web interface.

**Comment by worldofpeace** [comment]
@ttuegel I drafted some requirements and printing was one of them https://github.com/NixOS/nixpkgs/issues/99648#issuecomment-703933134. It seems it has been reported in the Q.A confirming it doesn't work https://github.com/NixOS/nixpkgs/issues/99648#issuecomment-706641386. I do get there is a workaround, but I think printing is just one of those things that people get super annoyed when broken (lol, and printing in general). 

I think the issue is just that qtquick is missing https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/kde/print-manager.nix. Easy enough to block on if that's true.

**Comment by jonringer** [comment]
is this still an issue? there's been ~700+ revisions since this was posted with `20.09alpha290`

**Comment by worldofpeace** [comment]
> t seems it has been reported in the Q.A confirming it doesn't work #99648 (comment). 

@jonringer see my quoted comment above

**Comment by ttuegel** [comment]
I can't get it working with #100236, or by adding `qtdeclarative` and `qtquickcontrols2` directly to the runtime environment. So, I can't say what the problem really is, or what it will take to fix it. :frowning:

**Comment by JosWolfkamp** [comment]
Maybe we do not have the qml-module-qtquick-controls2 included?

**Comment by jonringer** [comment]
the `qtquickcontrols2` is added to almost everything.

I spent the night looking into this, it seems like each kdeApplication has the needed qt framework. HOWEVER, the issue seems to only appear in the system tray's widgets. For some reason, these widgets do not inherit the "QML2_PLUGIN_PATH" from the user or from the wrapped programs.

The "clipboard" widget is also affected:

![Selection_043](https://user-images.githubusercontent.com/7673602/96358911-2460fa80-10c1-11eb-8ab4-478dd56df405.png)

**Comment by jonringer** [comment]
I don't use plasma, and hacking on it is very much outside my comfort zone.

Seeing as this is the last "blocking" issue with no clear resolution, I'm not sure how much longer I want to delay the release for this issue.

**Comment by jonringer** [comment]
actually, the qml files for `qt5XX.qtquickcontrols2` never get installed:
```
$ tree -L 2 /nix/store/zy45r169g2c8b22kb9y6yx40ky8vm3qk-qtquickcontrols2-5.12.7/lib/
/nix/store/zy45r169g2c8b22kb9y6yx40ky8vm3qk-qtquickcontrols2-5.12.7/lib/
├── libQt5QuickControls2.la
├── libQt5QuickControls2.prl
├── libQt5QuickControls2.so -> libQt5QuickControls2.so.5.12.7
├── libQt5QuickControls2.so.5 -> libQt5QuickControls2.so.5.12.7
├── libQt5QuickControls2.so.5.12 -> libQt5QuickControls2.so.5.12.7
├── libQt5QuickControls2.so.5.12.7
├── libQt5QuickTemplates2.la
├── libQt5QuickTemplates2.prl
├── libQt5QuickTemplates2.so -> libQt5QuickTemplates2.so.5.12.7
├── libQt5QuickTemplates2.so.5 -> libQt5QuickTemplates2.so.5.12.7
├── libQt5QuickTemplates2.so.5.12 -> libQt5QuickTemplates2.so.5.12.7
└── libQt5QuickTemplates2.so.5.12.7
```
inside the qtquickcontrols2 source:
```
[nix-shell:/home/jon/projects/nixpkgs/qtquickcontrols2-everywhere-src-5.15.0]$ tree -L 2 qml/
qml/
├── Qt
│   └── labs
└── QtQuick
    ├── Controls.2
    └── Templates.2
```

**Comment by jonringer** [comment]
After burning a few hours, I think I'm at the point that I will just make a release note that some plasmoids/widgets don't inherit qml paths correct, and may not work as intendend.

cc @worldofpeace

**Comment by jonringer** [comment]
Just to define what works:

- [X] Cups, configuring printers through cups, and shows as an option when doing the smart search
- [X] Applications > Print , works fine
- [ ] Print widget located on the system tray. (Shows qml import error from first post)

**Comment by jonringer** [comment]
actually, was able to get this working. `qtquickcontrols` was getting prefixed first in `QML2_IMPORT_PATH`, and so it was always picking up the previous version

![Selection_044](https://user-images.githubusercontent.com/7673602/96377904-9414cb00-113d-11eb-9606-5100f06d1334.png)

**Comment by jonringer** [comment]
qtquickcontrols has been deprecated since, 5.12, and qtquickcontrols has been available since 5.7. I'm going to see if there's any regressions with just setting `qtquickcontrols = null;`

**Comment by jonringer** [comment]
hmm, in my attempt to make things more consistent. I broke some things. I'll have to try another plan of attack

**Comment by jonringer** [comment]
I'm not actually sure how my nullifying qtquickcontrols was able to work in the first place. But I think #101078 is a reasonable change
