### ISSUE TITLE
Autorandr service config does not specify the correct kill mode

### ISSUE THREAD

**Issue by karthikiyengar** [NixOS/nixpkgs#98592]
**Describe the bug**
As of autorandr 1.6, the service definition was changed per [this](https://github.com/phillipberndt/autorandr/issues/111) issue so that processed spawned by hooks aren't killed.

**To Reproduce**
Try spawning a long living process from autorandr hooks

**Expected behavior**
The processes should not be killed

**Additional context**
IIUC, this can be rectified by adding `KillMode=process` [here](https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/nixos/modules/services/misc/autorandr.nix#L40)

I would have tested and PRed this myself, but I'm not super familiar with Nix at the moment :-(

**Notify maintainers**
@globin @gnidorah

**Comment by IllustratedMan-code** [comment]
This is a bit late, but I just made a [pull request](https://github.com/NixOS/nixpkgs/pull/155715) on the file you suggested and it worked like a charm on my system.

**Comment by zhaofengli** [comment]
Closing as the PR was merged :tada:
