### ISSUE TITLE
Emacs source code is missing despite `withCsrc = true`

### ISSUE THREAD

**Issue by bcc32** [NixOS/nixpkgs#98615]
**Describe the bug**
The Emacs variable `find-function-C-source-directory` points to a directory in the nix store which does not exist, even though it should based on the default value of `withCsrc` set to true.

**To Reproduce**
1. Install emacs with `nix-env -iA nixos.emacs`
2. Start emacs
3. Press `M-x find-function RET set-buffer RET`
4. Observe that the following error message is produced:

> find-function-C-source: The C source file buffer.c is not available

**Expected behavior**
Emacs should find the C file named `buffer.c` and display the following function:

```
DEFUN ("set-buffer", Fset_buffer, Sset_buffer, 1, 1, 0,
       doc: /* Make buffer BUFFER-OR-NAME current for editing operations.
BUFFER-OR-NAME may be a buffer or the name of an existing buffer.
See also `with-current-buffer' when you want to make a buffer current
temporarily.  This function does not display the buffer, so its effect
ends when the current command terminates.  Use `switch-to-buffer' or
`pop-to-buffer' to switch buffers permanently.
The return value is the buffer made current.  */)
```

**Notify maintainers**

@lovek323 @peti @jwiegley @adisbladis 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.03.3014.6ec10fc77e5 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3014.6ec10fc77e5, nixos-unstable-21.03pre244045.1179840f9a8"`
 - channels(aaron): `"nixpkgs-21.03pre243353.6d4b93323e7"`
 - nixpkgs: `/home/aaron/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by alyssais** [comment]
This seems to have been fixed by https://github.com/NixOS/nixpkgs/commit/e4fcc9aed14abc5fd5acd38ca4d5384d993a625b.

**Comment by bcc32** [comment]
Yep, looks fixed!  Thanks!
