### ISSUE TITLE
[gitit]: Cannot override staticDir or templatesDir

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#9863]
It tells me that these variables already exist in the configuration.

In fact, these variables are set [here](https://github.com/NixOS/nixpkgs/blob/d5505ae75732b3313015804b915aca30746767cd/nixos/modules/services/misc/gitit.nix#L646). I don't know why this needs to be done the way it is done, but I'd really like to be able to move my `staticDir` and `templatesDir` to other places.

**Comment by edwtjo** [comment]
Gitit must now be manually added to the configuration.nix using for instance:
```
imports = [ <nixos/modules/services/misc/gitit.nix> ];
```

**Comment by matthiasbeyer** [comment]
Isn't this another ugly hack?

**Comment by edwtjo** [comment]
Contrary, the module is now fine again. It is, since @edlostra has the final say, the unwanted overhead from its inclusion that is the problem.
