### ISSUE TITLE
Terraform 0.13 providers update strategy

### ISSUE THREAD

**Issue by timstott** [NixOS/nixpkgs#98652]
**Project description**

Terraform 0.13 introduces a new backwards incompatible filesystem layout for providers ([terraform 0.13 upgrade guides](https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers)). As a result none of the [providers defined in nixpkgs](https://github.com/nixos/nixpkgs/tree/012b501a12d140953355c311c7319883f5e71105/pkgs/applications/networking/cluster/terraform-providers/default.nix) work with terraform 0.13.

There are several options available to resolve this and wanted to consult with the community.

1.  Support Terraform 0.13 only
    Update providers to the latest version and adapt the [terraform-provider derivation](https://github.com/nixos/nixpkgs/tree/012b501a12d140953355c311c7319883f5e71105/pkgs/applications/networking/cluster/terraform-providers/default.nix) to the new filesystem layout.
    
    This is the simplest approach but previous terraform versions won&rsquo;t be able to use the modules.

2.  Support Terraform 0.13 and 0.12
    Introduce two distinct sets of `terraform-provider` to support both terraform versions.
    
    This approach is more involved but provides extended support for previous versions. It has the advantage to incrementally move providers to 0.13 as the [special providers](https://github.com/nixos/nixpkgs/tree/012b501a12d140953355c311c7319883f5e71105/pkgs/applications/networking/cluster/terraform-providers/default.nix) maybe more complex to port.
    
**Upgrade to 0.13 notes**

Plugins directory filesystem layout different
```
# 0.12
plugins_dir/terraform-provider-aws_v3.7.0

# 0.13
plugins_dir/registry.terraform.io/hashicorp/aws/3.7.0/linux_amd64/terraform-provider-aws_v3.7.0
```

The provider [data](https://github.com/nixos/nixpkgs/tree/012b501a12d140953355c311c7319883f5e71105/pkgs/applications/networking/cluster/terraform-providers/data.nix) file for 0.13 providers may have to be extended with `provider-source-address` to compute the filesystem path.
```diff
aws =
  {
    owner   = "terraform-providers";
    repo    = "terraform-provider-aws";
    rev     = "v2.65.0";
    version = "2.65.0";
    sha256  = "005vs1qd6payicxldc9lr4w6kzr58xw9b930j52g1q7hlddl5mbb";
+    provider-source-address = "registry.terraform.io/hashicorp/aws";
  };
```

**Comment by timstott** [comment]
Had a discuss with @zimbatm who's proposed the following:

1. Since there is now an official provider registry. We can rewrite the update script to use that as a data source instead of GitHub. This would also give us with the provider source address.
2. Once we used the official registry we can use a similar approach to [this](https://github.com/numtide/generate-terraform-provider-shim/blob/38be151c4c24655317ad4f7f47fde7bcd873d8ea/provider_release.go#L71) to compute the path.

I was also incorrect about provider incompatibilities between versions, which is a relief :sweat_smile:

**Comment by arnarg** [comment]
>     1. Since there is now an official provider registry. We can rewrite the update script to use that as a data source instead of GitHub. This would also give us with the provider source address.

Be warned that not all currently packaged providers are present in the registry, see terraform-providers.libvirt.

https://github.com/dmacvicar/terraform-provider-libvirt/issues/747

**Comment by zimbatm** [comment]
Since it's a big refactor, I think it's okay to drop non-standard providers. Those can be re-added later by extending the set of providers using purely nix code.

**Comment by MalloZup** [comment]
@arnarg  is something we plan to put the provider libvirt to the registry for 0.7.0 version  :star:
