### ISSUE TITLE
overrideCabal calls nest in an unexpected way

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#9871]
If `overrideCabal` is used to modify a derivation that was subjected to an 'overrideCabal' already, then the second (outer) invocation will use the `mkDerivaiton` function created by the first (inner) one. This means that the outer `overrideCabal` cannot undo changes made by the inner one. For example, the derivation `foo2` will have a dependency on `self.bar` in the following example:

```
foo  = overrideCabal super.foo (drv: { executableHaskellDepends = [ self.bar ] });
foo2 = overrideCabal self.foo (drv: { executableHaskellDepends = [] });
```

This seems counter-intuitive at best.

**Comment by Mathnerd314** [comment]
Solution:
```
      mkDerivationX = ...
      mkDerivation = stdenv.lib.makeOverridable mkDerivationX;
      overrideCabal = drv: f: drv.override (args: args // {
        mkDerivation = drv: (args.mkDerivation drv).override f;
      });
```
Test:
```
with import ./. {};
rec {
  super = haskellPackages;
  overrideCabal = drv: f: drv.override (args: args // {
    mkDerivation = drv: (args.mkDerivation drv).override f;
  });
  foo  = overrideCabal super.AES (drv: { executableHaskellDepends = [ 123 ]; });
  foo2 = overrideCabal foo (drv: { executableHaskellDepends = []; });
$ nix-instantiate --eval test.txt  -A super.AES.propagatedNativeBuildInputs
[ null null <CODE> <CODE> <CODE> null ]
$ nix-instantiate --eval test.txt  -A foo.propagatedNativeBuildInputs
[ null null <CODE> <CODE> <CODE> null 123 ]
$ nix-instantiate --eval test.txt  -A foo2.propagatedNativeBuildInputs
[ null null <CODE> <CODE> <CODE> null ]
```
On another note, it would be much more convenient if haskellPackages.overrideCabal existed. There are too many copies of overrideCabal as-is...

**Comment by Profpatsch** [comment]
(triage) what’s the status of this?

**Comment by domenkozar** [comment]
test case: https://gist.github.com/shajra/15ef77cdd4e83a823857ffe8a6c11df9

**Comment by domenkozar** [comment]
Proposed patch for the above test case: https://gist.github.com/c89d63a14972339a51729511ed44f8ff

**Comment by shajra** [comment]
I tried to implement @domenkozar's proposed fix, but I ended up with an infinite recursion: 8f3d1659ccb0a77110ff0feba38c86139212aff4

I have to walk away from this for a moment (also, recursion in nixpkgs can be intense, so not sure I'm in the right headspace)... hopefully this helps further discussion until I get back to it.

**Comment by shajra** [comment]
@Mathnerd314 I'm playing around with your solution now, but having a hard time getting all the "dynamic" types to work themselves out correctly.  Did you test your solution already?  Do you have a working patch?

**Comment by shajra** [comment]
I tried this other approach too, but it's also broken.  I wonder if someone here can figure out a fix: c2dc3e3816eef930e572ce5597a064a05d51da6f

I feel I'm missing something simple here.

**Comment by shajra** [comment]
@Mathnerd314 it was a very simple error on my part.  I got it working (more or less as you suggested).  I'm eager to see if you all are content with this change, or dissatisfied with the direction it takes overriding.  From my perspective, the code doesn't seem any hackier than it already was.

**Comment by Profpatsch** [comment]
@peti should take a look at it.

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/22613
