### ISSUE TITLE
Instructions on how to set a user shell correctly

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9872]
A the moment the instructions on how to set a user shell correctly are rather hand-wavey and easy to misconfigure. For example I was told that `bash` is the wrong choice (https://github.com/NixOS/nix/issues/644#issuecomment-140075874) which is mentioned nowhere.

This is further complicated because `users.defaultUserShell` has no default.

The way of setting it to `current-system/sw` does look like more of a hack to me.

What I’d like have is a nix symbol for the most used shells and an easy way to turn a shell into one.
Maybe a shell type would make sense?

**Comment by matthiasbeyer** [comment]
> Maybe a shell type would make sense?

Nope. Not a type, please. But maybe something like

```
users.defaultUserShell = pkgs.bash;
```

should translate to the appropriate `current-systems/sw` path, which would enable us to set `fish`, `zsh` etc as default shell as simple as changing a variable.

**Comment by peti** [comment]
The default shell for NixOS users is `/run/current-system/sw/bin/bash`, which is exactly what it should be, IMHO. If some overwrites that default value with something else, then they'll get a different shell. I'm not sure how that situation ought to be improved?

@Profpatsch, would you mind making a concrete suggestion which part of the documentation should be changed and *how* it should be changed in your opinion? A PR would be best, really.
