### ISSUE TITLE
Deepspeech

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#98770]
**Project description**

DeepSpeech is an open source Speech-To-Text engine, using a model trained by machine learning techniques based on Baidu's Deep Speech research paper. Project DeepSpeech uses Google's TensorFlow to make the implementation easier.

**Metadata**

* homepage URL: https://github.com/mozilla/DeepSpeech
* source URL: https://github.com/mozilla/DeepSpeech
* license: Mozilla Public License https://github.com/mozilla/DeepSpeech/blob/master/LICENSE
* platforms: Unsure

**Comment by NorfairKing** [comment]
I already tried this with a local clone of deepspeech:

```
let
  pkgs = import <nixpkgs> {};

  deepspeechPythonPackages = python-packages: with python-packages; [
  ];
  pythonPackages = pkgs.python3.withPackages deepspeechPythonPackages;

  deepspeech = pkgs.python3Packages.buildPythonApplication {
    version = "0.8.2";
    pname = "deepspeech";
    src = ./DeepSpeech;
    propagatedBuildInputs = with pkgs; [ sox ];
    buildInputs = with pkgs; [ sox ];
    checkInputs = with pkgs; [ sox ];
  };      
in deepspeech
```
But I get this error for unknown reasons:

```
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/DeepSpeech/dist /build/DeepSpeech
Processing ./deepspeech_training-0.9.0a10-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement sox (from deepspeech-training==0.9.0a10) (from versions: none)
ERROR: No matching distribution found for sox (from deepspeech-training==0.9.0a10)
```

**Comment by davidak** [comment]
I guess pip is searching for a python package named sox.

https://pypi.org/project/sox/1.4.0/

**Comment by NorfairKing** [comment]
@davidak That one doesn't seem to be in nixpkgs, is that right?

**Comment by Fuzen-py** [comment]
> @davidak That one doesn't seem to be in nixpkgs, is that right?

Doesn't look like it, you might want to package that as well

**Comment by povik** [comment]
> looks like this would need packaged as well http://sox.sourceforge.net/

There is [sox in nixpkgs](https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/applications/misc/audio/sox/default.nix).

**Comment by NorfairKing** [comment]
:(

**Comment by rvolosatovs** [comment]
@NorfairKing I added binary package in https://github.com/NixOS/nixpkgs/pull/117416, which works fine for my use case (linking to it from Rust). The binary itself works fine as well
