### ISSUE TITLE
Static overlay for `fmt` is broken

### ISSUE THREAD

**Issue by FrancisRussell** [NixOS/nixpkgs#98778]
**Describe the bug**
The `fmt` library cannot be used via `pkgsStatic`

**To Reproduce**
1. `nix-shell -p pkgsStatic.fmt`

**Expected behavior**
`fmt` is compiled statically and I get Nix shell.

**Notify maintainers**
@FRidh

**Comment by FRidh** [comment]
Why am I notified on this package? I am not a maintainer nor have I ever touched this expression.

**Comment by FrancisRussell** [comment]
The bug filing template suggested I use `git blame` to determine who last touched this expression, which was the commit 157ca8eb752674dc9e15e50921462386b545ce19.

**Comment by FRidh** [comment]
Thank you, that clarifies!

Indeed, it seems I added `pkgsStatic` support at the time, but it was broken directly when `staging-next` was merged into `master`. Fixed with 759a2815ec5b6fddb10c637fceec0f1eba88449a and backported to 20.09.
