### ISSUE TITLE
Problem connecting to Eduroam with NetworkManager

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#9878]
Hi,

I can't connect to the Eduroam network with NixOS, even though i can with all other distros (Debian, Arch, Gentoo, Ubuntu). I know the issue[1] is already known, but the resolution is not (yet) satisfactory for me.

I'm trying to get people from my university to try NixOS, but without a working Eduroam no one will consider trying/using it. If this is not a NixOS issue, then tell me what to tell/write our IT-Department so they can fix our Eduroam. Currently i only know that this is the config[2] that should work.

ikervagyok

p.s.: I'm using unstable/master, didn't try my old wpa_supplicant.conf yet, but i will, shortly (I would still prefer a working NetworkManager)
[1] https://github.com/NixOS/nixpkgs/issues/8332
[2] http://www.zid.tuwien.ac.at/tunet/wlan/anleitungen/eduroam_linux/

**Comment by vcunat** [comment]
Ah, better reopen the original issue, so we have context, original participants are notified, etc.

**Comment by domenkozar** [comment]
I'm interested helping out, but indeed we need more details on original issue.
