### ISSUE TITLE
Request: OpenJDK 15

### ISSUE THREAD

**Issue by lorenzleutgeb** [NixOS/nixpkgs#98784]
I am missing version 15 of the `openjdk` package, see https://jdk.java.net/15/

**Comment by jerith666** [comment]
cc folks who've worked on JDK updates recently: @asbachb @bachp @edwtjo @Ma27 @petabyteboy

**Comment by raboof** [comment]
I started on adding openjdk15 in #100403 - it's usable but not complete. I have to move on to other tasks right now though, so feel free to take over.
