### ISSUE TITLE
Freecad 0.19

### ISSUE THREAD

**Issue by bootstrap-prime** [NixOS/nixpkgs#98821]
**Project description**
Add the freecad 0.19 package to the nixos repository to enable the mass exodus of fusion360 people to have the latest version

**Metadata**

* homepage URL: https://freecadweb.org/
* source URL: https://github.com/FreeCAD/FreeCAD
* license: mit, bsd, gpl2+ , ...GPLv2
* platforms: unix, linux, darwin, ... Windows, Linux, Mac

**Comment by redvers** [comment]
Both Stable and Unstable currently at 0.18.4

**Comment by gebner** [comment]
Please note that there is no 0.19 release yet.  I don't really understand why freecad seemingly wants everybody to use nightlies but doesn't make an official 0.19 release.  Personally, I would also prefer to have the git version in nixpkgs.  This would also allow us to upgrade opencascade to 7.4.0 and get rid of the qtwebkit dependency.

cc @viric

**Comment by gebner** [comment]
I've made a PR to upgrade FreeCAD #98845.  Let's see if there is a large opposition to the change.

**Comment by redvers** [comment]
Since 0.19.0 doesn't exist yet and there's another PR in place it may make sense to close this ticket @bootstrap-prime  - what say you?
