### ISSUE TITLE
Problem with Qt5 applications in 20.09

### ISSUE THREAD

**Issue by freezeboy** [NixOS/nixpkgs#98834]
**Describe the bug**

A lot of Qt5 apps seems broken in hydra on 20.09 branch.
But they usually work on master, it looks like it is due to a version pinning to Qt5.12 (I think for plasma5), but apps usually want 5.14 or 5.15.

I am not sure of the clean way to fix it:
 * plasma 5.20 is in beta and should be released in october
 * default Qt should be for apps or plasma ?
 * there must be some valid patch in master that we could cherrypick... but no idea to find it

**Notify maintainers**

@ttuegel as the main kde maintainer
@jonringer @worldofpeace as release managers

Any idea ?

**Comment by jonringer** [comment]
This is being addressed in #98657

**Comment by freezeboy** [comment]
Ok then we can close this one
