### ISSUE TITLE
ZRythm

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#98871]
**Project description**

A highly automated and intuitive digital audio workstation.

**Metadata**

* homepage URL: https://www.zrythm.org
* source URL: https://github.com/zrythm/zrythm
* license: AGPLv3+
* platforms: linux

**Comment by suhr** [comment]
This is a stub of a derivative for ZRythm: https://gist.github.com/suhr/1f22371c3ee8c70f6948e7984e39318a

**Comment by magnetophon** [comment]
@suhr Did you see https://github.com/NixOS/nixpkgs/pull/85553
It's for an older version, and I haven't compared it to your gist, but maybe you would like to do that?

**Comment by suhr** [comment]
Still relevant.
