### ISSUE TITLE
Wine 64+WoW bins from Hydra

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#9887]
Can we add wine64 in top-level so that Hydra builds them? They take a long time to compile here.

cc @bendlas

**Comment by bendlas** [comment]
WineWow is the default on x86_64, and should be available from hydra. Do you think use of wine64 is so widespread as to warrant adding it to hydra? Is there a use case where wineWow can't be used?

**Comment by bendlas** [comment]
As of https://github.com/NixOS/nixpkgs/commit/60a0bb7f66fd51a5b935ed50f8f39a34a5fc55cc the default is wine32 again. So maybe having a separate wine64 build for hydra makes sense. @edolstra ?

**Comment by joelmo** [comment]
It's fine for me to keep it as it is. But let's consider building wine64 in hydra if other use it. Another thing. I checked default version on other distros and they use 1.7.x. I submitted a pull for airwave that use wine and mostly is tested against unstable. My impression is that unstable get used mostly.

**Comment by ben0x539** [comment]
Having to spend all that time compiling wine to be able to run 32bit exe files on a x86_64 system is pretty offputting.

**Comment by vcunat** [comment]
The default is the wine that can run only 32-bit stuff, and it works on both i686-linux and x86_64-linux.
