### ISSUE TITLE
[20.09] qutebrowser does not start

### ISSUE THREAD

**Issue by woffs** [NixOS/nixpkgs#98885]
Qutebrowser in release-20.09 does not run:
```
nixpkgs (release-20.09=)$ ./result/bin/qutebrowser 
21:31:39 INFO: Could not load the Qt platform plugin "xcb" in "" even though it was found.
21:31:39 CRITICAL: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Fatal Python error: Aborted

Current thread 0x00007fbd93264280 (most recent call first):
  File "/nix/store/3fvywg6zzkbp1kcjy0zxkx4yllr9d9xk-qutebrowser-1.13.1/lib/python3.8/site-packages/qutebrowser/app.py", line 508 in __init__
  File "/nix/store/3fvywg6zzkbp1kcjy0zxkx4yllr9d9xk-qutebrowser-1.13.1/lib/python3.8/site-packages/qutebrowser/app.py", line 92 in run
  File "/nix/store/3fvywg6zzkbp1kcjy0zxkx4yllr9d9xk-qutebrowser-1.13.1/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 202 in main
  File "/nix/store/3fvywg6zzkbp1kcjy0zxkx4yllr9d9xk-qutebrowser-1.13.1/bin/.qutebrowser-wrapped", line 9 in <module>
Aborted
```

Apparently it links with qtbase-5.14.2-bin and all other qt components 5.15. Building
`qutebrowser = pkgs.libsForQt5.callPackage <nixpkgs/pkgs/applications/networking/browsers/qutebrowser> { };`
(instead of `libsForQt514.callPackage`) fixes this and results in a running executable. Another way to fix is applying https://github.com/NixOS/nixpkgs/commit/7abb57c7b5eaa9aa34ea289fc1e23ed259547bdb

The Python / Qt team should have a look and fix this.

**Comment by woffs** [comment]
maintainers are @jagajaga @rnhmjoj @ebzzry

**Comment by rnhmjoj** [comment]
Updating qutebrowser to use 5.15 should work too but there are a number [issue](https://github.com/qutebrowser/qutebrowser/search?q=5.15&type=issues) still,
so I would continue to use 5.14. Backporting that commit seems the best solution, there's a PR already: https://github.com/NixOS/nixpkgs/pull/98854

**Comment by woffs** [comment]
fixed by https://github.com/NixOS/nixpkgs/commit/54ef32d2c6e70f1084d10628713bc196b4c4c968
