### ISSUE TITLE
Update gitlab

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#9890]
I'm not familiar with ruby. So, please, can anyone update gitlab? There are several errors in the version we have now in nixpkgs. For example https://github.com/gitlabhq/gitlabhq/issues/7413
cc @offlinehacker @teh

**Comment by teh** [comment]
Running gitlab was such a pain that we moved away from it. I can create a PR to remove it from nixpkgs so we don't have unmaintained code?

**Comment by jagajaga** [comment]
@teh no. I will try to update it myself then.

**Comment by offlinehacker** [comment]
I agree with @teh to remove it. Packiging rails on nix is real pain, and it's a lot of hacking to make it work. @jagajaga I would suggest you to run it in docker instead. Of course you can waste some of time to make it work, but it's not really worth it.

**Comment by jagajaga** [comment]
@offlinehacker how can I run it in docker?

**Comment by offlinehacker** [comment]
The easiest way is to use docker-compose and docker-compose.yml from
offical gitlab repo. Then you just run "docker-compose up"

V sre., 23. sep. 2015 11:05 pop. je oseba Arseniy Seroka <
notifications@github.com> napisala:

**Comment by jagajaga** [comment]
@offlinehacker thank you. So if you think it's better to remove -- let's do it.

@manpages please read this thread.

**Comment by offlinehacker** [comment]
@jagajaga I could think of a way to run it using lightweight container with overlayfs mounted over read only gitlab package in nix store. We can already do this with runc/docker/lxc but I think we need some official way embeded in nix.
