### ISSUE TITLE
tdm: The Dark Mod fails to start on NixOS 20.09

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#98936]
**Describe the bug**

**To Reproduce**
1. Install pkgs.tdm
2. Execute tdm_updater
3. Execute tdm

**Expected behavior**
tdm starts.

**Actual behaviour**

tdm starts with a black error and has stderr errors such as:
```
----- R_ReloadARBPrograms -----
WARNING:LoadARBProgram: 'glprogs/test.vfp' not found
WARNING:LoadARBProgram: 'glprogs/test.vfp' not found
WARNING:LoadARBProgram: 'glprogs/interaction.vfp' not found
WARNING:LoadARBProgram: 'glprogs/interaction.vfp' not found
glprogs/bumpyEnvironment.vfp 5
glprogs/bumpyEnvironment.vfp 6
WARNING:LoadARBProgram: 'glprogs/ambientLight.vfp' not found
WARNING:LoadARBProgram: 'glprogs/ambientLight.vfp' not found
WARNING:LoadARBProgram: 'glprogs/shadow.vp' not found
glprogs/environment.vfp 3
glprogs/environment.vfp 4
WARNING:LoadARBProgram: 'glprogs/test_direct.vfp' not found
WARNING:LoadARBProgram: 'glprogs/test_direct.vfp' not found
WARNING:LoadARBProgram: 'glprogs/interaction_direct.vfp' not found
WARNING:LoadARBProgram: 'glprogs/interaction_direct.vfp' not foun
```

**Additional context**

It looks like the problem might be that pkgs.tdm and the assets downloaded via tdm_updater are different versions:

```
$ ls -lah $(which tdm)
lrwxrwxrwx 1 root root 60 Jan  1  1970 /run/current-system/sw/bin/tdm -> /nix/store/izddmzwjwv6aaim6kq65lbyax4qp6qf5-tdm-2.07/bin/tdm
$ tail ~/.local/share/tdm/tdm_version_info.txt 
filesize = 17967512

[Version2.08 File thedarkmod.x86]
crc = 38ef5a25
filesize = 18517512

[Version2.08 File TheDarkModx64.exe]
crc = 160957d2
filesize = 19812352
```

** Workaround

`cd ~/.local/share/tdm && steam-run ./thedarkmod.x64`

(Steam isn't actually used for this. This is just a lazy way to run FHS programs.)

**Notify maintainers**
@cizra 

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tdm
# a list of nixos modules affected by the problem
module:
```

**Comment by cizra** [comment]
There's a version update in master. I don't know when it'll land in
unstable (maybe it already did?) or stable.

**Comment by tomfitzhenry** [comment]
Is it possible to have NixOS stable not break when upstream changes?

Either:
(a) NixOS stable should include the TDM assets (in which case tdm_update is not needed)
(b) pkgs.tdm becomes solely a shim to grab assets from the TDM assets, so it doesn't matter which version of pkgs.tdm is used.

**Comment by cizra** [comment]
2. would require patching the path to ELF interpreter, along with worrying
about lib dependencies.

1. is complicated: TDM players are accustomed to dowloading extra missions,
which requires a writable directory to hold the data. Do you have a
proposal how to do this securely? Hardlinking the default install to /home
would break if /home is on a different FS. Suid wrappers smell.
World-writable bits in /nix smell too.

**Comment by peterhoeg** [comment]
Surely the engine supports multiple asset directories, so we can load the assets from the nix store in addition to whatever was installed manually into a local directory.

**Comment by tomfitzhenry** [comment]
The comments on https://aur.archlinux.org/packages/thedarkmod-bin/ suggest The Dark Mod stores save games in its installation directory. https://bugs.thedarkmod.com/view.php?id=3567 tracks this issue.

**Comment by marius851000** [comment]
I have another issue that seem to be related. Running tdm via the ``tdm`` command start and I can start a game, but there is not audio. Running ``cd ~/.local/share/tdm && steam-run ./thedarkmod.x64`` work however. The relevent line are:
```
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: no device found, sound disabled
```
When it doesn't work and
```
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'ALSA Default'
OpenAL: found device 'HD-Audio Generic, HDMI 0 (CARD=Generic,DEV=3)'
OpenAL: found device 'HD-Audio Generic, HDMI 1 (CARD=Generic,DEV=7)'
OpenAL: found device 'HD-Audio Generic, HDMI 2 (CARD=Generic,DEV=8)'
OpenAL: found device 'HD-Audio Generic, HDMI 3 (CARD=Generic,DEV=9)'
OpenAL: found device 'HD-Audio Generic, ALC236 Analog (CARD=Generic_1,DEV=0)'
OpenAL: using 'OpenAL Soft'
OpenAL: HRTF is available
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found EFX extension
OpenAL: HRTF is disabled (reason: 0 = ALC_HRTF_DISABLED_SOFT)
OpenAL: found 256 hardware voices
```
with the second option

**Comment by cizra** [comment]
I poked around - and I don't have any ideas why OpenAL might not be finding hardware.
Right now, it seems that the best course of action is to remove TDM from repos (to avoid creating false expectations), and run it with steam-run.
@tomfitzhenry and @marius851000 do you agree?
