### ISSUE TITLE
pitivi outdated

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9894]
And the current version (0.93) doesn’t start.

I tried just updating to 0.94, but apparently they have moved to `python3` and just replacing `pythonPackages` with `python3Packages` leads to some runtime dependencies missing.

cc @iyzsong

**Comment by bjornfor** [comment]
I tried to update it once, I think the problem (or one of them?) was that it needs gst-python with python3. And that was not readily available (IIRC).

**Comment by Profpatsch** [comment]
They release a complete bundle on their website and actively state they don’t support anything else (exactly because they need very stable dependencies).

**Comment by bjornfor** [comment]
Ok. I knew about the "Pre-built, distro-agnostic bundle", but I didn't know how strongly they recommended it:

```
[...] when reporting bugs, you should test against those [pre-built], rather than distribution packages.
```

+1 for packaging that. I guess all it needs is ```patchelf --set-interpreter ${glibc}...``` to work.

**Comment by iyzsong** [comment]
I have do the update, it work fine fine for me.
but the crash problem @Profpatsch reported is another issue.
