### ISSUE TITLE
elementary-tweaks: init at 0.0.1

### ISSUE THREAD

**Issue by Eisiem** [NixOS/nixpkgs#98954]
**Project description**
Elementary-tweaks is a system settings panel for elementary OS Juno that lets you easily and safely customize your desktop's appearance

**Metadata**

* homepage URL: https://github.com/elementary-tweaks/elementary-tweaks
* source URL: https://github.com/elementary-tweaks/elementary-tweaks/releases/tag/0.0.1
* license: GPL-3.0
* platforms: Linux

**Comment by worldofpeace** [comment]
@Eisiem Hi, pantheon's maintainer in nixpkgs. I've actually considered packaging this application myself, but I noticed that it's really out of date and probably won't work with the latest Pantheon (and it doesn't seem to be actively maintained anymore). For that reason I will close this as I don't think it's really usable atm.  (especially at its last released version at 0.0.1 in 2017)

**Comment by Eisiem** [comment]
> @Eisiem Hi, pantheon's maintainer in nixpkgs. I've actually considered packaging this application myself, but I noticed that it's really out of date and probably won't work with the latest Pantheon (and it doesn't seem to be actively maintained anymore). For that reason I will close this as I don't think it's really usable atm. (especially at its last released version at 0.0.1 in 2017)

Hello. While it's true that is not being updated very often (Last commit 9 month ago), the project is not closed, it still working on the latest Pantheon (I'm using it on elementary rn), and it's yet a tool that users frequently install.
Please consider reopening it, at least for someone else to package it. (Also, I was planning to offer a [bounty](https://www.bountysource.com/teams/nixos) on it)
