### ISSUE TITLE
Install NixOS on Hyper-v

### ISSUE THREAD

**Issue by LiliDeng** [NixOS/nixpkgs#9899]
We installed it by following steps here http://nixos.org/nixos/manual/sec-installation.html against hyper-v

After reboot hit below issues, do you know if the NixOS can run against hyper-v? Is it the issue related with our configuration? 

Issue - 
waiting for device /dev/disk/by-uuid/... to appear...
Time out waiting for device /dev/disk/by-uuid/..., trying to mount anyway.
mounting /dev/disk/by-uuid/... on /...
mount: mounting /dev/disk/by-uuid... on /mnt/root/ failed: No such file or directory 

An error occurred in stage 1 of the boot process, which must mount the root filesystem on `/mnt-root` and then start stage 2. Press one of the following keys:

r) to reboot immediately
*) to ignore the error and continue

**Comment by wkennington** [comment]
We are missing the hyperv kernel modules from the initrd part of the ISO
and I believe we are lacking detection in hardware configuration.

**Comment by LiliDeng** [comment]
Thanks William for your quick response so much. 
Does it mean NixOS can't install on hyper-v? Any plan for this? Also Microsoft has developed the hyper-v kernel modules, can it apply into NixOS?

**Comment by LiliDeng** [comment]
Thanks William for your quick response so much.
Does it mean NixOS can't install on hyper-v currently? Any plan for this? Also Microsoft has developed the hyper-v kernel modules, can it apply into NixOS?
We are trying this to see if we can run NixOS on Microsoft Azure.

Thanks,
Lili

**Comment by LiliDeng** [comment]
Thanks William for your quick response so much. 
Does it mean NixOS can't install on hyper-v currently? Any plan for this? Also Microsoft has developed the hyper-v kernel modules, can it apply into NixOS?
We are trying this to see if we can run NixOS on Microsoft Azure.

**Comment by lizzha** [comment]
Hi Lili,

There're following words in the installation guidance.
Note: Depending on your hardware configuration or type of file system, you may need to set the option boot.initrd.kernelModules to include the kernel modules that are necessary for mounting the root file system, otherwise the installed system will not be able to boot. (If this happens, boot from the CD again, mount the target file system on /mnt, fix /mnt/etc/nixos/configuration.nix and rerun nixos-install.) In most cases, nixos-generate-config will figure out the required modules.

Can you please have a try to include driver hv_vmbus and hv_storvsc in the initrd in this way?

**Comment by wkennington** [comment]
I believe my branch from a while back fixes the issue. I'll rebase it against our more current tree.

https://github.com/wkennington/nixpkgs/commits/master.hyperv

**Comment by wkennington** [comment]
It should be up to date and fixed up. Let me know if it works. You should be able to build an iso after checking out the codebase using
`nix-build nixos/release.nix -A iso_minimal_new_kernel.x86_64-linux`

**Comment by LiliDeng** [comment]
lizzha's suggestion resolve my problem currently, now I can enter into the system. Thanks both.

**Comment by farukc** [comment]
I verified that adding the drivers to your .nix file resolves the issue and wanted to share the line added : 
`boot.initrd.kernelModules = ["hv_vmbus" "hv_storvsc"];

**Comment by LiliDeng** [comment]
Thanks, it also works for me.
