### ISSUE TITLE
aircrack-ng: "airmon-ng start" complains that "iw" is not available

### ISSUE THREAD

**Issue by fazo96** [NixOS/nixpkgs#9901]
I installed `aircrackng` from `configuration.nix` and it complains that `iw` is not avaiable while it is.

Steps to reproduce:
1. install `aircrackng` either from `nix-env` or `configuration.nix`
2. run `sudo airmon-ng start wlp3s0` (replace wlp3s0 with your wireless interface name, you can see a list by running `airmon-ng`)
3. see that it complains that it can't do that because `iw` is missing, then run `iw` to prove that it's not

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by fazo96** [comment]
I stopped using NixOS a year ago, but reinstalled it this morning (what a coincidence).

I'll check as soon as I can!

**Comment by fazo96** [comment]
aircrack now works, but it still complains about missing required software for the airmon functionality: ethtool, lsusb (found in usbutils) and iw. Should these be runtime dependencies of aircrack? Some of its functionality won't work without these, but they can be installed manually and it will work.

**Comment by Profpatsch** [comment]
> Should these be runtime dependencies of aircrack?

If it needs those at runtime, you should probably use `makeBinPath` and call `wrapProgram` in the `installPhase`
