### ISSUE TITLE
embree fails to build on macOS

### ISSUE THREAD

**Issue by valencik** [NixOS/nixpkgs#99049]
**Describe the bug**
[embree](https://github.com/NixOS/nixpkgs/blob/6fb0a4dd2a6e10f4b966b6be664348302f578985/pkgs/development/libraries/embree/default.nix) is failing on macOS currently:

<details> 
  <summary>nix-build -A embree output:</summary>
these derivations will be built:
  /nix/store/bz97d7ny5gklf93nfj07xmkyls0dr4qi-embree-3.11.0.drv
building '/nix/store/bz97d7ny5gklf93nfj07xmkyls0dr4qi-embree-3.11.0.drv'...
unpacking sources
unpacking source archive /nix/store/ayfz4widjdpcng9kp1swrrxbxbnba7i8-source
source root is source
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/share/doc/embree -DCMAKE_INSTALL_INFODIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/include -DCMAKE_INSTALL_SBINDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/qmxmk9l5ldy8zp50qaxmyv2r1sdfw7az-cctools-binutils-darwin-927.0.2/bin/strip -DCMAKE_RANLIB=/nix/store/qmxmk9l5ldy8zp50qaxmyv2r1sdfw7az-cctools-binutils-darwin-927.0.2/bin/ranlib -DCMAKE_AR=/nix/store/qmxmk9l5ldy8zp50qaxmyv2r1sdfw7az-cctools-binutils-darwin-927.0.2/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/77i2qdml21lg9nnm4s17nhv3nsxv0x62-embree-3.11.0 -DEMBREE_TUTORIALS=OFF -DEMBREE_RAY_MASK=ON 
-- The C compiler identification is Clang 7.1.0
-- The CXX compiler identification is Clang 7.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/sw7b2gcklaj3iy5ikv7ag163bpry3ivb-clang-wrapper-7.1.0/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/sw7b2gcklaj3iy5ikv7ag163bpry3ivb-clang-wrapper-7.1.0/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Intel SPMD Compiler (ISPC): /nix/store/crcx45ydr3g0r0h0l175ih3fmazfdzav-ispc-1.13.0/bin/ispc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for TBB components tbb; ()
-- Found TBB version 2019.9 at /nix/store/zhs084vi30aqaky6hmpa69121akwxbf4-tbb-2019_U9
-- Found OpenImageIO: /nix/store/j0sccvfcl2x6l29zhb067qi06ajpa5dq-openimageio-1.8.17-dev/include  
-- Found JPEG: /nix/store/4s4zmzds6igf11036p9r1qaj9578zrxw-libjpeg-turbo-2.0.4/lib/libjpeg.dylib (found version "62") 
-- Found PNG: /nix/store/9c010n7a2qj0yh051gdiggpbxrnwvjcn-libpng-apng-1.6.37-dev/include  
-- Configuring done
CMake Warning (dev):
  Policy CMP0068 is not set: RPATH settings on macOS do not affect
  install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, the install_name fields for
  the following targets are still affected by RPATH settings:

   embree

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_POLICY_DEFAULT_CMP0025

-- Build files have been written to: /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/build
cmake: enabled parallel building
building
build flags: -j4 -l4 SHELL=/nix/store/smimdn17mp2ih6nfxwl78mswwdkmcm56-bash-4.4-p23/bin/bash
Scanning dependencies of target math
Scanning dependencies of target sys
Scanning dependencies of target tasking
Scanning dependencies of target simd
[  0%] Building CXX object common/math/CMakeFiles/math.dir/constants.cpp.o
[  0%] Building CXX object common/simd/CMakeFiles/simd.dir/sse.cpp.o
[  0%] Building CXX object common/tasking/CMakeFiles/tasking.dir/taskschedulertbb.cpp.o
[  0%] Building CXX object common/sys/CMakeFiles/sys.dir/sysinfo.cpp.o
[  1%] Linking CXX static library ../../libmath.a
[  1%] Built target math
[  1%] Building CXX object common/sys/CMakeFiles/sys.dir/alloc.cpp.o
In file included from /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/sys/sysinfo.cpp:6:
In file included from /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/sys/string.h:7:
In file included from /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/sys/../math/vec2.h:6:
/private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/sys/../math/math.h:205:5: error: use of undeclared identifier '__sincosf'; did you mean 'sincosf'?
    __sincosf(x,sin,cos);
    ^~~~~~~~~
    sincosf
/private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/sys/../math/math.h:204:22: note: 'sincosf' declared here
  __forceinline void sincosf(float x, float *sin, float *cos) {
                     ^
In file included from /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/simd/sse.cpp:4:
In file included from /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/simd/sse.h:33:
In file included from /private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/simd/vint4_sse2.h:6:
/private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/simd/../math/math.h:205:5: error: use of undeclared identifier '__sincosf'; did you mean 'sincosf'?
    __sincosf(x,sin,cos);
    ^~~~~~~~~
    sincosf
/private/var/folders/t8/_t753d_94qj0q6mfxv4kjmn40000gp/T/nix-build-embree-3.11.0.drv-0/source/common/simd/../math/math.h:204:22: note: 'sincosf' declared here
  __forceinline void sincosf(float x, float *sin, float *cos) {
                     ^
1 error generated.
make[2]: *** [common/simd/CMakeFiles/simd.dir/build.make:82: common/simd/CMakeFiles/simd.dir/sse.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: common/simd/CMakeFiles/simd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object common/sys/CMakeFiles/sys.dir/filename.cpp.o
1 error generated.
make[2]: *** [common/sys/CMakeFiles/sys.dir/build.make:82: common/sys/CMakeFiles/sys.dir/sysinfo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  3%] Linking CXX static library ../../libtasking.a
[  3%] Built target tasking
make[1]: *** [CMakeFiles/Makefile2:330: common/sys/CMakeFiles/sys.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
builder for '/nix/store/bz97d7ny5gklf93nfj07xmkyls0dr4qi-embree-3.11.0.drv' failed with exit code 2
error: build of '/nix/store/bz97d7ny5gklf93nfj07xmkyls0dr4qi-embree-3.11.0.drv' failed

</details>

**To Reproduce**
1. nix-build -A embree

**Expected behavior**
builds successfully

**Additional context**
This came up in [trying to build blender on macOS](https://github.com/NixOS/nixpkgs/pull/98982#issuecomment-700075638)

**Notify maintainers**
@hodapp @gebner 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(andrewvalencik): `"nixpkgs-20.09pre224406.5f14d99efed, nixpkgs-unstable-20.03pre212209.eee784a1bb6"`
 - nixpkgs: `/Users/andrewvalencik/.nix-defexpr/channels/nixpkgs`

**Comment by valencik** [comment]
Interestingly (to me, perhaps not to others) I can build embree via homebrew with:
`brew install --build-from-source embree`

I've also tried modifying the embree derivation by [copying some of the cmake flags from the homebrew definition](https://github.com/Homebrew/homebrew-core/blame/fa5a718eed99599c3d887619dc86d5608d9399ee/Formula/embree.rb#L23-L29), but the same error remained.

**Comment by gebner** [comment]
My first guess is that we use a different compiler, maybe gcc instead of clang?  Or maybe we need to use this version of `sincosf` on macos as well, but it's only used on freebsd on windows: https://github.com/embree/embree/blob/80b6f7e97e2e0d1e1de32bd0ccdeeb920adb111a/common/math/math.h#L209-L213

**Comment by siraben** [comment]
Related: #31725

**Comment by gebner** [comment]
Fixed by #99728
