### ISSUE TITLE
sshfs: failed to exec fusermount3: No such file or directory

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#99044]
**Describe the bug**
I'm on Ubuntu 20.04.1, and installed `sshfs`, but it fails:
```
> sshfs n64:/home/samuela sshfs_n64 
fuse: failed to exec fusermount3: No such file or directory
```

**To Reproduce**
1. Install sshfs via nix on an Ubuntu machine that does not have FUSE installed.
2. Try running sshfs

**Expected behavior**
Either to have FUSE installed as a dependency or an error message to be presented if that's not possible on non-NixOS systems.

**Screenshots**

**Additional context**

**Notify maintainers**
@primeos 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-48-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"home-manager, nixpkgs-21.03pre244418.cc7d3ff1538"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by samuela** [comment]
Actually I already have FUSE installed:
```
> apt policy fuse             
fuse:
  Installed: 2.9.9-3
  Candidate: 2.9.9-3
  Version table:
 *** 2.9.9-3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```
And I have `fusermount` just not `fusermount3` apparently.

**Comment by primeos** [comment]
> And I have `fusermount` just not `fusermount3` apparently.

It should work then if you have `fuse3` installed: https://packages.ubuntu.com/focal/amd64/fuse3/filelist

> Either to have FUSE installed as a dependency

Unfortunately we cannot do this outside of NixOS. The library will be installed as a dependency but `fusermount3` must be a suid binary (which Nix cannot install for security reasons) and the `fuse` kernel module needs to be installed/loaded as well (will provide `/dev/fuse`).

> or an error message to be presented if that's not possible on non-NixOS systems.

That would be nice. But AFAIK we don't have a (good) mechanism for that. So unfortunately I don't think we can improve this situation.

**Comment by primeos** [comment]
I'll close this then due to the lack of actionable options. But we can reopen it if someone has any ideas what to do here.
