### ISSUE TITLE
Nixpkgs repo is getting unreasonably large

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#9907]
Doing a fresh clone now pulls down almost 200MB. I haven't tried to see where all the space is going, but it doesn't seem like a good situation.

[I accidentally posted this bug to my fork](https://github.com/copumpkin/nixpkgs/issues/78) so a bit of discussion emerged there, but it should continue here.

**Comment by copumpkin** [comment]
So this commit single-handedly added about 25MB to the history: https://github.com/NixOS/nixpkgs/commit/8bae32afb58b2bd21395f4ddb1236c41c3561e67

**Comment by vcunat** [comment]
IIRC one can work reasonably well with a shallow clone nowadays. That seems the best way to approach it in the current situation, if you consider this big...

Other tip I use is sharing `.git` for multiple checkouts on a single machine (I used `git-new-workdir` script). For me this shared `.git` is less than 200 MB and I have all pull requests in there and also some non-official commits. For a nixpkgs dev that doesn't seem much at all, as e.g. a clean work tree takes over 50 MB for me (reported by `du`).

**Comment by vcunat** [comment]
As for that specific commit example, it's only reachable from the 14.12 branch, which you presumably don't care about at all, so you don't need to fetch it.

**Comment by edolstra** [comment]
We probably should have done a force-push to get rid of that commit right away. But that's a bit too late now...

Anyway, 200 MB doesn't strike me as excessive. It's just the price you pay for using git.

**Comment by peti** [comment]
Besides, I don't see what we're supposed to do about it, really. 200 MB may or may not be "unreasonably large", but that's what it is now and I am not aware of a way to reduce that size (other than throwing away history, which nobody wants I supppose).

**Comment by lethalman** [comment]
Or we can split the current history into two parts. We might split the history in 2 parts, from first commit to commit X, and from commit X to today. Nixpkgs master will be only the last part, and the older part will be in a different repository.

If one wants to have the whole history, one can cherry-pick all the commits of nixpkgs master on top of the older history.

**Comment by edolstra** [comment]
Well, that will be a lot of work and it will invalidate every commit hash. Much easier for people who don't care about history to just do `git clone --depth 1`.

**Comment by vcunat** [comment]
More on the shallow clones: you can have also `git clone --depth 1000` or something and choose just the master and release-15.09 branches. With recent git versions you're supposed to even be able to push and pull normally with such a setup.

**Comment by copumpkin** [comment]
I know about all those solutions, but it still bugs me to be accumulating crap like that :smile: but if everyone else is fine with it, I'll close this ticket.
