### ISSUE TITLE
RFP: Lomiri (Unity8) desktop environment

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#99090]
**Project description**
> A convergent desktop environment.

![img.png](https://unity8.io/img.png)

Canonicals previously-abandoned DE, picked up by the community and renamed to "Lomiri". It's Qt5-based and runs on Wayland via Mir.

Main point of interest for me is *eventually* using it on my PinePhone that I intended to run NixOS on (soon:tm:), but as a convergent DE it's supposed to be usable on desktops too. UB Touch is the de-facto showcase distro using Lomiri, Manjaro started distributing PP builds bundled with Lomiri recently and afaict postmarketOS is working on supporting it too. It is easily the smoothest-handling FOSS DE for Linux phones right now. (IMO anyway :stuck_out_tongue:)

**Metadata**

* homepage URL: https://lomiri.com/
* source URL:
  - https://github.com/ubports/unity8 (UBports version)
  - https://gitlab.com/ubports/development/core/lomiri ("the upstream for packaging Lomiri outside of Ubuntu Touch")
* license: gpl3
* platforms: linux

**Comment by AndersonTorres** [comment]
- Lomiri? Or Unity8?
- Runs on Wayland *only* via Mir?

**Comment by OPNA2608** [comment]
> - Lomiri? Or Unity8?

It was called "Unity8" when Canonical were still developing it (as the next version of Unity, the graphical shell of Ubuntu until LTS 18.04). It has been officially abandoned by Canonical and picked up by the UBports community in 2017. Earlier this year, it has been renamed to "Lomiri". From the repository description:

> Now called Lomiri, but still developed in this repository.

---

> - Runs on Wayland *only* via Mir?
>   - Is Mir some "Wayland implementation"?

For the former, that seems to be the case yes. My understanding of Mir was that it's still an independent display server with some sort of Wayland support, but [MirServer/mir](https://github.com/MirServer/mir) sounds more like it's a Wayland compositor in general now?

> **Mir - Wayland compositor**
> 
> Mir is a set of libraries for building Wayland based shells.

I'm not *super* knowledgable about Wayland, Mir or Lomiri though, sorry.

**Comment by AndersonTorres** [comment]
Then it is two projects in one: Mir and Lomiri. If my HA doesn't hinder, I will try this too.

**Comment by OPNA2608** [comment]
I got a unity8 derivation and all of its compile-time dependencies to compile, but haven't tested any functionality or set up NixOS modules yet. Currently restructuring one big overlay into smaller derivations & commits so people can take a look at it, I'll prolly have everything in https://github.com/OPNA2608/nixpkgs/tree/lomiri within the next few hours to days. Would opening a WIP PR help with visibility & feedback or do you think it's too early for that?

**Comment by AndersonTorres** [comment]
It is never early to show some novelty.

But, what do you think about write an overlay like the colemickens' wayland one?

**Comment by OPNA2608** [comment]
> It is never early to show some novelty.

https://github.com/NixOS/nixpkgs/pull/108366

> But, what do you think about write an overlay like the colemickens' wayland one?

That looks way too complicated for me, sorry. I wouldn't even know where to begin since I've barely discovered overlays so far! :sweat_smile:

**Comment by OPNA2608** [comment]
I picked up work on this again. Still busy with packaging & making everything work as good as possible: [OPNA2608/nixpkgs@init/lomiri-junk](https://github.com/OPNA2608/nixpkgs/tree/init/lomiri-junk)

![screenshot20230225_105054669](https://user-images.githubusercontent.com/23431373/221350632-4d372fe6-da7c-4fa3-95c5-bca9b650e4c8.png)

**Comment by onny** [comment]
This is impressive :) Is this the latest Lomiri used in Ubuntu Touch?

**Comment by OPNA2608** [comment]
As latest as it can get, most of the packages are using tags from 1-2 weeks ago (and I'm bumping them as I notice new tags being made [though I should prolly add update scripts to all of these packages at some point to automate that]): [`lomiri 0.1`](https://gitlab.com/ubports/development/core/lomiri/-/tags/0.1). I'm not sure, but I assume upstream's current UT 20.04 efforts will be using the same / similar versions. [Their package upstreaming to Debian for the upcoming Debian Bookworm release certainly does](https://qa.debian.org/developer.php?login=team%2Bubports%40tracker.debian.org).

The main thing differentiating it from UT is that their transition from Mir 1.x & mirclient to Mir 2.x & miroil has been delayed to UT 22.04, so we'll be pulling in some WIP patches to jump ahead to Mir 2.x - same as the Debian packaging. I had Mir 1.x *kind-of* working on my desktop, but it wouldn't run on my laptop (where in the mean time, I've grown quite accustomed to the in-between Miriway WM on Mir 2.x). It seemed not worth the extra headache, especially considering that the patches are good enough that Debian folks have accepted them for the packaging there.

My plan right now is to
1. iron out some leftover problems as I notice them, package stuff as needed, likely add some tiny NixOS-specific customisations to the logo & default wallpaper like Manjaro & postmarketOS; until this stuff works more or less like it does on Debian
2. go back and fix up all the individual packages where I've been lazy on the first go (get tests working if possible, meta details)
3. rebase on master to check if anything's broken / been made obsolete since I started this
4. tidy up the commit order
5. start upstreaming stuff :checkered_flag:

I'm fairly determined to pull through with the packaging this time, considering the progress I've made so far. Haven't really put much thought into what we'll need in terms of maintenance & management in Nixpkgs though. Taking a look at what i.e. Pantheon does: prolly a [Lomiri maintainer team](https://github.com/NixOS/nixpkgs/blob/41657484f4aa506e1121a3ece6564494cd9e2982/maintainers/team-list.nix#L578-L589) and [our own `lomiri.*` scope](https://github.com/NixOS/nixpkgs/blob/41657484f4aa506e1121a3ece6564494cd9e2982/pkgs/desktops/pantheon/default.nix)? Dunno if that should include [UBports' `click`](https://click.readthedocs.io/en/latest/index.html) to save it from a naming conflict with the unrelated-but-already-packaged [`click` Kubernetes CLI](https://github.com/databricks/click).

If anyone would like to organise & maintain this stuff with me, feel free to reach out so we can discuss this stuff. I'm mainly on Discord & on the official-unofficial Nix/NixOS server, but I can join on Matrix if necessary <sub>and try to use that more frequently :sweat_smile:</sub>.

:wink:
![screenshot20230226_124956536](https://user-images.githubusercontent.com/23431373/221408802-3249edf1-80d2-4162-9df5-863a2b443da5.png)

**Comment by jcleng** [comment]
is there documentation on how to use it?

**Comment by phossil** [comment]
@jcleng  you can check my flake for reference :)
[all: move lomiriConfig and miscConfig to new files](https://github.com/phossil/nixfiles/blob/8cfba97f27568dd5791efaa142aa124383f0e439/common/lomiri.nix)

**Comment by lidgnulinux** [comment]
Does the `tap to click` work ?

**Comment by OPNA2608** [comment]
Hmm. There is an option for tap-to-click in lomiri-system-settings, but for me it doesn't work. Haven't looked into how that setting is hooked up to the input stuff. When I'm not using Lomiri on my test machine I'm using Miriway, where this is said to require a libinput configuration implementation in Mir: https://github.com/MirServer/mir/issues/2886. Unsure if this extends to Lomiri though.

**Comment by OPNA2608** [comment]
`services.desktopManager.lomiri.enable` has been merged. It will be available on the unstable channel [soon](https://nixpk.gs/pr-tracker.html?pr=292872), and will find its way into the upcoming NixOS 24.05. Additional components that still need to be packaged for the full experience are being tracked in https://github.com/NixOS/nixpkgs/issues/260859.

**Comment by jcleng** [comment]
👍
