### ISSUE TITLE
virtualbox VMs cause hard lockups with linux 3.18(?)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9912]
I'm having trouble starting virtualbox guests when running linux 3.18 (default kernel). Sometimes I cannot start them at all and I get this error:

```
The VM session was aborted.

Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
SessionMachine
Interface: 
ISession {7844aa05-b02e-4cdd-a04f-ade4a762e6b7}
```

But other times the VM starts but then the system (including my host) might hard lock up (SysRq+REISUB doesn't even work).

I think I saw some comments about this issue on github, but I cannot find it now.

Using linux 4.1 seems to work. But I've done insufficient testing to be certain.

**Comment by bjornfor** [comment]
I'm on NixOS 15.09.343.1b83abb (Dingo).

**Comment by bjornfor** [comment]
Argh, now it doesn't work on linux 4.1 either (VM won't start).

**Comment by edolstra** [comment]
My workaround was to go back to Linux 3.18.16. See https://github.com/NixOS/nixpkgs/issues/9732#issuecomment-139484473.

**Comment by domenkozar** [comment]
I'm running `15.09.git.d774f60 (Dingo)` (kernel 4.1.6) and I can boot NixOS ova image with no problems.

**Comment by krgn** [comment]
I can reliably reproduce the problem starting first a win7 instance and then firing up chromium. My setup is:
 
```
➜  ~ uname -a
Linux pong 3.18.21 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
```

with latest nvidia on the unstable channel.

**Comment by retrry** [comment]
I remember that I had the same problem and from my configuration I see that I switched to 4.1 kernel on July 14 (+- couple of days). I thought that it was connected to Nvidia drivers, but same problem existed with Nouveau.

**Comment by krgn** [comment]
After a bit of trial and error I found out that with `nvidiaLegacy304`, I needed to use `linuxPackages_3_14`, and `linuxPackages_4_1` for the regular `nvidia` driver. I am not sure my problem is related to this issue though.

**Comment by vcunat** [comment]
@krgn: `nvidiaLegacy304`? #10015 claims those versions are incompatible with our xorg-server version, and nvidia doesn't seem like wanting to fix that.

**Comment by krgn** [comment]
@vcunat oh that is disconcerting! Here is some info on my current system:

```
➜  ~ uname -a
Linux lorax 3.14.51 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
```

```
➜  ~ modinfo nvidia
filename:       /run/current-system/kernel-modules/lib/modules/3.14.51/misc/nvidia.ko
alias:          char-major-195-*
version:        304.125
supported:      external
license:        NVIDIA
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd00000AA3sv*sd*bc0Bsc40i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        drm,agpgart,i2c-core
vermagic:       3.14.51 SMP mod_unload modversions 
parm:           NVreg_EnableVia4x:int
parm:           NVreg_EnableALiAGP:int
parm:           NVreg_ReqAGPRate:int
parm:           NVreg_EnableAGPSBA:int
parm:           NVreg_EnableAGPFW:int
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_RemapLimit:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UseVBios:int
parm:           NVreg_RMEdgeIntrCheck:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_NvAGP:int
```

```
➜  ~ X -version

X.Org X Server 1.17.2
Release Date: 2015-06-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.14.27 x86_64 
Current Operating System: Linux lorax 3.14.51 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64
Kernel command line: BOOT_IMAGE=(hd0,msdos1)//kernels/q2hkkbh0nazpcqk0g8qjl8h7n6vx8mbv-linux-3.14.51-bzImage systemConfig
=/nix/store/3bxrg51jaclycd6if4lxp4zdv8ls2v6d-nixos-16.03pre68782.54e430a init=/nix/store/3bxrg51jaclycd6if4lxp4zdv8ls2v6d
-nixos-16.03pre68782.54e430a/init loglevel=4
Build Date: 09 September 2015  02:07:07AM
 
Current version of pixman: 0.32.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

I live on the `nixos-unstable` channel, so far quite happily!  :)

**Comment by vcunat** [comment]
@codyopel: do you have a reference about the xorg-server versions supported?

**Comment by codyopel** [comment]
@vcunat According to nvidia the max xorg-server version for each driver version is 
```
355.xx,   xorg <=1.17.x, kernel <=4.2
352.xx,   xorg <=1.17.x, kernel <=4.2 (stable) <- default
340.xx,   xorg <=1.17.x, kernel <=4.2
304.xx,   xorg <=1.16.x, kernel <=3.16
173.14.x, xorg <=1.15.x, kernel <=3.13
96.43.x,  xorg <=1.12.x, kernel <=3.7
71.86.x,  xorg <=?,      kernel <=?
```
Regardless of what nvidia says for kernels you could probably patch the kernel module to work with newer kernels.

I can't remember the exact details and I can't find it at the moment, but xorg made breaking api changes to do with the cursor, so everything should work in 304.xx, with 1.17, but you may or may not have a cursor.

I'll add is back to the PR for now regardless, but I'll have to dig out an old card and run some tests to see if it works with everything.

**Comment by bjornfor** [comment]
I've been running a day now with virtualbox 5.0.4/.6 and linux 4.2. No issues.

However, there was some fiddling needed to get the VMs running again after this hickup. They were in "Aborted" state and wouldn't start at all. It seemed creating a new VM (re-using the disk image) "unlocked" the VMs. Another way seemed to be changing the system type to something different (or just back and forth). Your VM -> Settings -> General -> Version.

Weird...

**Comment by bjornfor** [comment]
Has this issue been fixed? I'm on a different machine now, with NixOS 15.09 and linux 3.18.21. I'm able to run VirtualBox VM without issues. (They used to crash immediately on start, but this one has run for several minutes.)

**Comment by bjornfor** [comment]
@edolstra: Do you still have Virtualbox/linux 3.18.x issues?

**Comment by domenkozar** [comment]
Closing until someone reports this is still and issue.

**Comment by afranchuk** [comment]
This is still an issue. I'm on NixOS 15.09 with linux 3.18.24, and I can reliably make the kernel panic by starting up a VirtualBox VM (running Windows 7) and then opening Firefox.

**Comment by domenkozar** [comment]
Unfortunately that's the solution we recommend from users, I see no better way.

`boot.kernelPackages =  pkgs.linuxPackages_4_2;`

**Comment by geraldus** [comment]
Ok, I've faced this issue with 3.18.24 kernel and nvidia 352.55 driver. Switching to to 4.3 kernel seems to resolve this (I can't be certain but at least now I can run Chromium, Firefox while VirtualBox running).  Thank you, pals!
