### ISSUE TITLE
fish is called twice

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9914]
I am going crazy.

Fish seems to be called twice on invocation, but I cannot find the reason (or even see the second process).

This patch inserts a print statement in the config file:

```patch
diff --git a/pkgs/shells/fish/default.nix b/pkgs/shells/fish/default.nix
index 12cd864..8fffc50 100644
--- a/pkgs/shells/fish/default.nix
+++ b/pkgs/shells/fish/default.nix
@@ -31,6 +31,18 @@ stdenv.mkDerivation rec {
   '' + ''
     sed -i "s|/sbin /usr/sbin||" \
            "$out/share/fish/functions/__fish_complete_subcommand_root.fish"
+
+    cat >> "$out/etc/fish/config.fish" <<EOF
+    echo foo
+    EOF
+
   '';
 
   meta = with stdenv.lib; {
```

    nix-build -A pkgs.fish
    result/bin/fish

Now this prints

    foo
    foo

on my system (regardless whether I call it from fish, from bash, from sh, &c.).

Of course it could simply be sourced twice; that’s why I dug into the code and inserted print statements. You can find that patch here: https://github.com/Profpatsch/nixpkgs/commit/fca33985ce0e8225bd6260959b70bf017c897d52 

Output:
```
starting to read initsourcing data config
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/share/fish
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/share/fish
sourcing sys config
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/etc/fish
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/etc/fish
foo
Woot /home/philip/.config/fish
Woot /home/philip/.config/fish
starting to read initsourcing data config
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/share/fish
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/share/fish
sourcing sys config
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/etc/fish
Woot /nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/etc/fish
foo
Woot /home/philip/.config/fish
Woot /home/philip/.config/fish
```

(forgot one `\n` after the first line)
This means it calls `main()` twice!

Now, strace.

    strace -o trace result/bin/fish
    ^D

The resulting trace file (`./trace`) has exactly one `execve` (at the very beginning) and no further reference to `result/bin/fish`. Furthermore, showing the process tree from within the new fish only shows one fish process, not two stacked ones, as one would assume.

I am missing something. Any ideas?

**Comment by vcunat** [comment]
I don't see the whole `main` in the patch, but just the scrap **above** your inserted print mentions some **forking**...

**Comment by Profpatsch** [comment]
Holy moley:

```
> env fish_log_forks=1 result/bin/fish
546: g_fork_count: 0
starting to read initsourcing data config
…
fork #1: Executing keepalive fork for 'echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0'
fork #2: Executing fork for internal builtin for 'echo'
fork #3: forking for '/nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/bin/fish' in '-'
546: g_fork_count: 0
starting to read initsourcing data config
```

**Comment by Profpatsch** [comment]
But no idea how to find out where that second fish is forked.

**Comment by pSub** [comment]
@Profpatsch From what I read in the upstream issue, I assume that we can close this issue. Right?

**Comment by Profpatsch** [comment]
Right.
