### ISSUE TITLE
libinput synaptics like configuration support

### ISSUE THREAD

**Issue by eskimor** [NixOS/nixpkgs#9920]
Already started here:

https://github.com/eskimor/nixpkgs/tree/libinput-master

It works for me, but not all options are supported yet. I hope to find time polishing it and make a proper pull request soon. In the meantime, you can use what I have, if you need it.

**Comment by colemickens** [comment]
This is great. I've added this and by touchpad now works as expected. An option for inverting scrolling would be neat (or is that handled at a different layer?).

**Comment by eskimor** [comment]
Implemented: Option - NaturalScrolling - completely untested unfortunately, but you might want to try it out.

**Comment by vcunat** [comment]
I believe we should strive to abstract away whether you're using synaptics or libinput and whether you're using X or something else. For example, we have `services.xserver.synaptics.accelFactor` and now you add `services.xserver.libinput.accelSpeed`. I'd imagine that instead we should have, for example, `hardware.touchpad.accelSomething` that would be shared, and `hardware.touchpad.driver = "libinput";`.

**Comment by colemickens** [comment]
How would that work? Each Wayland compositor is responsible for configuring libinput, and they each have their own internal configuration formats.

**Comment by vcunat** [comment]
I expect we need special setup code in nixos for each (wayland) compositor anyway.

**Comment by colemickens** [comment]
Not for sway or orbment.

**Comment by eskimor** [comment]
@vcunat : Well this would make the switch for users easier between synaptics and libinput, but I believe it is not worth the trouble:
1. The capabilities of libinput and synaptics are not the same
2. At the moment the options to be set in nix match the options described in the libinput man page - which is kind of nice.

As libinput is both for X and wayland, changing the name to something like hardware.touchpad indeed makes sense.

**Comment by wkennington** [comment]
Also keep in mind libinput isnt supported by some wms like xmonad based on
my testing. I could control applications fine but keybinds were broken

**Comment by eskimor** [comment]
Could you elaborate on this - I am using xmonad with libinput - no issues so far.

**Comment by datakurre** [comment]
What would be the easiest way to try this out? Is there anything else besides building configuration from a github checkout with @eskimor's additions?

**Comment by eskimor** [comment]
@datakurre that is at least the most straight forward approach right now. As there seems to be some interest I will try to find some time to make a pull request out of it.

**Comment by datakurre** [comment]
@eskimor Thanks. Libinput made my touchpad usable. And works with xmonad for me.

**Comment by colemickens** [comment]
@eskimor I have a commit you might want to take too. It adds scroll method and two finger right click support: https://github.com/colemickens/nixpkgs/commit/397139d8ed6e76703460882956d4071ff0c4b04e

**Comment by eskimor** [comment]
@colemickens Thanks - integrated.

**Comment by Ericson2314** [comment]
Could we have a PR for that work?

@vcunat I appreciate the goal, but making such an abstraction without having it leak seems difficult. Also, consider that the drivers work for overlapping sets of hardware, so if the choice of driver is intentional rather than transparent, maybe there is less need to have the configurations be reusable. Finally, if we get in this now, and somehow mark it unstable/tentative, it should be an excellent foundation for such unified configurations in the future.

**Comment by vcunat** [comment]
It was just and idea. You (the implementers) should know better than me whether it's feasible (or worth their time).

> if we get in this now, and somehow mark it unstable/tentative

Yeah, well, I don't know how to do that, and I think it would be useful in general to have a means to mark some parts of our "interfaces" as unstable/tentative, meaning they can change without providing backward compatibility. IIRC we were discussing these problems on the case of NixUP after NixCon, as without people using the "interfaces" it's harder to improve them.

**Comment by eskimor** [comment]
@Ericson2314 Yeah - I will do some polishing this Friday. Expect a PR by Saturday.

**Comment by Ericson2314** [comment]
Sweet!
