### ISSUE TITLE
systemd.lib was removed

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#99240]
**Describe the bug**

#94354 removed `systemd.lib`. Thus anything that had `systemd.lib` in its closure now depends on `systemd`, which causes a significant closure size increase. For instance, the Emacs closure grew by 85 MiB, and `dbus.lib` (which many packages depend on) grew by 119 MiB. Making things worse, `systemd` currently depends on another copy of `systemd`.

**Expected behavior**

We should bring back `systemd.lib`.

**Comment by flokli** [comment]
dup of https://github.com/NixOS/nixpkgs/issues/98094#issuecomment-695797574.
