### ISSUE TITLE
Archive the nixpkgs-channels repository

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#99257]
A while ago we added the channel branches (`nixos-*` etc.) to the nixpkgs repository, so nixpkgs-channels is no longer necessary. However it still exists, which confuses people. I propose to archive it. Thus existing references will still work but we won't add new channels to it.

Concretely:

* In the channel mirroring script, stop mirroring NixOS >= 20.09. (Also delete the nixos-20.09 branches in nixpkgs-channels. It's not released yet so we can do that.)
* Once we stop updating NixOS < 20.09, archive the nixpkgs-channel repo.

**Comment by vcunat** [comment]
> Once we stop updating NixOS < 20.09, archive the nixpkgs-channel repo.

That may be a tough condition (e.g. we bumped 19.09 a few days ago), but I think it's OK to stop after they get officially unsupported.

**Comment by worldofpeace** [comment]
I'm just wondering if the end user could get some kind of warning when their NIX_PATH uses a url to nixpkgs-channels

**Comment by worldofpeace** [comment]
> stop mirroring NixOS >= 20.09. (Also delete the nixos-20.09 branches in nixpkgs-channels. It's not released yet so we can do that.)

This would mean we cannot release 20.09 without this repo being archived first. That makes this a blocker.

**Comment by JustinLovinger** [comment]
> > stop mirroring NixOS >= 20.09. (Also delete the nixos-20.09 branches in nixpkgs-channels. It's not released yet so we can do that.)
> 
> This would mean we cannot release 20.09 without this repo being archived first. That makes this a blocker.

A compromise could be to keep 20.09 in nixpkgs-channels, but not put 21.03 in nixpkgs-channels. At least that would prevent this issue from being a 20.09 blocker.

**Comment by veprbl** [comment]
> Once we stop updating NixOS < 20.09, archive the nixpkgs-channel repo.

This will not prevent Hydra from advancing those channels because they are hosted on NixOS.org, right?

**Comment by vcunat** [comment]
Well, there might be some forgotten dependencies like https://github.com/NixOS/nixos-org-configurations/blob/master/modules/tarball-mirror.nix#L37 (just a quick search)

**Comment by worldofpeace** [comment]
> > > stop mirroring NixOS >= 20.09. (Also delete the nixos-20.09 branches in nixpkgs-channels. It's not released yet so we can do that.)
> > 
> > 
> > This would mean we cannot release 20.09 without this repo being archived first. That makes this a blocker.
> 
> A compromise could be to keep 20.09 in nixpkgs-channels, but not put 21.03 in nixpkgs-channels. At least that would prevent this issue from being a 20.09 blocker.

Yeah, I really wouldn't want to add another blocker on an already due release. @edolstra Do you think we could have that for 21.03? 20.09 should be ready hopefully fairly soon.

**Comment by edolstra** [comment]
> This would mean we cannot release 20.09 without this repo being archived first. That makes this a blocker.

I'm not following, why does it mean that?

**Comment by vcunat** [comment]
My understanding of the plan:
1. Stop pushing 20.09 to nixpkgs-channels repo (without changing anything else) and remove those references.  This should be done **before** 20.09 is released, so it can be considered a blocker.
2. Wait until 20.03 is officially unsupported and thus it (and all older) won't be getting many updates anymore.  (could be e.g. around the end of 2020 already)
3. Archive the repo.

**Comment by edolstra** [comment]
Right. I can do step 1 today.

**Comment by edolstra** [comment]
Step 1 is done. So nixpkgs-channels doesn't contain branches for nixos-20.09.

I'll set the milestone for this issue to 21.03 as a reminder to archive the repo around then.

**Comment by domenkozar** [comment]
Should we archive it?

**Comment by domenkozar** [comment]
Actually since we already agreed to do it, I just finished this.
