### ISSUE TITLE
Lua 5.3 needs to be bumped to 5.3.6, package Lua 5.4.0

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#99261]
**Describe the bug**
Lua 5.3.6 was released on 25.09. and we finally received Lua 5.4.0 on 29.06.(!), see https://www.lua.org/news.html and https://www.lua.org/manual/5.4/readme.html#changes.

**To Reproduce**
1. Check [pkgs/development/interpreters/lua-5/default.nix](https://github.com/NixOS/nixpkgs/blob/43f09cbd6d2c1011a81a9e2742406529d9fe5dfa/pkgs/development/interpreters/lua-5/default.nix)
2. See that lua5_3 is on release 5, and a lua5_4 is nowhere to be found

**Expected behavior**
Shiny new version to play with. :stuck_out_tongue_winking_eye:

**Screenshots**
\-

**Additional context**
\-

**Notify maintainers**
There are no `meta.maintainers` specified for the Lua interpreters… I'll blindly ping some ppl that look to be relevant to the Nixpkgs Lua ecosystem. (sorry!)
cc @teto @vcunat 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-112-generic, Ubuntu, 18.04.5 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(bt1cn): `"nixpkgs-20.09pre242495.3c0e3697520"`
 - nixpkgs: `/home/bt1cn/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ lua5_3 ]
```

**Comment by teto** [comment]
should be easy enough to add them, duplicate the file and look what's up :) I dont have a specific interest in providing this  but can review if needed.

**Comment by nagy** [comment]
I think this can be closed.
