### ISSUE TITLE
google-cloud-sdk - install additional components: gcloud components install cloud-build-local

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#99280]
**Describe the bug**
```
gcloud components install cloud-build-local
ERROR: (gcloud.components.install) You cannot perform this action because this Cloud SDK installation is managed by an external package manager.
Please consider using a separate installation of the Cloud SDK created through the default mechanism described at: https://cloud.google.com/sdk/
```

**To Reproduce**
```
nix-env -i google-cloud-sdk
gcloud components install cloud-build-local
```

```
cloud components list

Your current Cloud SDK version is: 306.0.0
The latest available version is: 312.0.0

+---------------------------------------------------------------------------------------------------------------+
|                                                   Components                                                  |
+------------------+------------------------------------------------------+--------------------------+----------+
|      Status      |                         Name                         |            ID            |   Size   |
+------------------+------------------------------------------------------+--------------------------+----------+
| Update Available | BigQuery Command Line Tool                           | bq                       |  < 1 MiB |
| Update Available | Cloud SDK Core Libraries                             | core                     | 16.1 MiB |
| Update Available | Cloud Storage Command Line Tool                      | gsutil                   |  3.5 MiB |
| Not Installed    | App Engine Go Extensions                             | app-engine-go            |  4.9 MiB |
| Not Installed    | Appctl                                               | appctl                   | 21.0 MiB |
| Not Installed    | Cloud Bigtable Command Line Tool                     | cbt                      |  7.7 MiB |
| Not Installed    | Cloud Bigtable Emulator                              | bigtable                 |  6.6 MiB |
| Not Installed    | Cloud Datalab Command Line Tool                      | datalab                  |  < 1 MiB |
| Not Installed    | Cloud Datastore Emulator                             | cloud-datastore-emulator | 18.4 MiB |
| Not Installed    | Cloud Firestore Emulator                             | cloud-firestore-emulator | 41.0 MiB |
| Not Installed    | Cloud Pub/Sub Emulator                               | pubsub-emulator          | 34.9 MiB |
| Not Installed    | Cloud SQL Proxy                                      | cloud_sql_proxy          |  7.5 MiB |
| Not Installed    | Cloud Spanner Emulator                               | cloud-spanner-emulator   | 21.4 MiB |
| Not Installed    | Emulator Reverse Proxy                               | emulator-reverse-proxy   | 14.5 MiB |
| Not Installed    | Google Cloud Build Local Builder                     | cloud-build-local        |  6.0 MiB |
| Not Installed    | Google Container Registry's Docker credential helper | docker-credential-gcr    |  1.8 MiB |
| Not Installed    | Kind                                                 | kind                     |  4.5 MiB |
| Not Installed    | Kustomize                                            | kustomize                | 25.9 MiB |
| Not Installed    | Minikube                                             | minikube                 | 24.1 MiB |
| Not Installed    | Nomos CLI                                            | nomos                    | 17.7 MiB |
| Not Installed    | Skaffold                                             | skaffold                 | 14.5 MiB |
| Not Installed    | anthos-auth                                          | anthos-auth              | 16.0 MiB |
| Not Installed    | gcloud Alpha Commands                                | alpha                    |  < 1 MiB |
| Not Installed    | gcloud Beta Commands                                 | beta                     |  < 1 MiB |
| Not Installed    | gcloud app Java Extensions                           | app-engine-java          | 59.5 MiB |
| Not Installed    | gcloud app Python Extensions                         | app-engine-python        |  6.1 MiB |
| Not Installed    | gcloud app Python Extensions (Extra Libraries)       | app-engine-python-extras | 27.1 MiB |
| Not Installed    | kpt                                                  | kpt                      | 11.1 MiB |
| Not Installed    | kubectl                                              | kubectl                  |  < 1 MiB |
+------------------+------------------------------------------------------+--------------------------+----------+

```

**Expected behavior**
install the component (e.g. cloud-build-local)

**Screenshots**

**Additional context**

**Notify maintainers**

@pradyuman
@stephenmw
@zimbatm

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.9, NixOS, 20.03.2652.076c67fdea6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(ae): `"OsUnstable-21.03pre243854.2a14d21224f, NxUnstable-21.03pre243968.2a35f664394, home-manager-20.03, nixos-20.03.3002.773ef5ae783"`

**Comment by InLaw** [comment]
Is there a way to do this with nixpkgs?

**Comment by InLaw** [comment]
any update?

**Comment by InLaw** [comment]
would be nice to get in nix-native (and flexible)

**Comment by zimbatm** [comment]
Looks like you will have to do it yourself. You probably want something similar to terraform where you could do `google-cloud-sdk.withPlugins(p: [ p.cloud-build-local)`

**Comment by xlambein** [comment]
FYI this was just added to nixpkgs.  You can do the following:
```nix
google-cloud-sdk.withExtraComponents ([google-cloud-sdk.components.cloud-build-local])
```

**Comment by shinzui** [comment]
Is there a reason why it's not supported on `aarch64-darwin`?

```
error: Package ‘gke-gcloud-auth-plugin’ in /nix/store/69l88zcx53mg0zqmxjamnp0srnn7whyr-source/pkgs/tools/admin/google-cloud-sdk/components.nix:169 is not supported on ‘aarch64-darwin’, refusing to evaluate.
```

**Comment by xlambein** [comment]
Two reasons:

1. I don't have a darwin ARM machine so I didn't have a way to test this myself.

2. Components in google-cloud-sdk have an `architecture` field that can specify `arm`, but it's unclear whether this is `aarch64` or any other kind of ARM architecture, so I didn't really know what the right mapping was, and preferred not to make a decision.

You're welcome to try it out and make a PR tho :-]

**Comment by shinzui** [comment]
It looks like there is an existing [PR](https://github.com/NixOS/nixpkgs/pull/193554).

**Comment by DawidJanczak** [comment]
Hello,

Apologies if this is something obvious since I'm pretty new to nix, but the following doesn't work for me:
```
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/a62844b30250.tar.gz") {} }:

pkgs.mkShell {
  buildInputs = [
    pkgs.google-cloud-sdk.withExtraComponents [pkgs.google-cloud-sdk.components.cloud-build-local]
...
```
fails with `error: Dependency is not of a valid type: element 1 of buildInputs for nix-shell`

I'm pretty sure I'm doing something wrong, but can't figure it out, would appreciate some help.

**Comment by xlambein** [comment]
That's not normal indeed, I'm looking into it.

**Comment by learnitall** [comment]
I was facing the same deal, but came across this: https://github.com/michielboekhoff/nixos-conf/commit/3833fcc9a67f071e4191dfb751ea4bb8a2b76a69. Try adding `()` around the package in your `buildInputs`, should fix the issue:
```
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/a62844b30250.tar.gz") {} }:

pkgs.mkShell {
  buildInputs = [
    (pkgs.google-cloud-sdk.withExtraComponents [pkgs.google-cloud-sdk.components.cloud-build-local])
  ];
}
```

**Comment by DawidJanczak** [comment]
Thank you @learnitall , that did it!

**Comment by xlambein** [comment]
Oh, how did I miss that :sweat_smile: Thanks @learnitall

**Comment by DerekMaffett** [comment]
I noticed an issue with a separate component - cloud-run-proxy

It seems to install fine with `(google-cloud-sdk.withExtraComponents ([google-cloud-sdk.components.cloud-run-proxy]))`, and the executable is added to the bin, but trying to run `cloud-run-proxy` causes a command not found error - so far as I can tell, the symlink in the store that's being pointed to appears to simply point to itself, but with no actual executable anywhere. 

```
ERROR: (gcloud.beta.run.services.proxy) Error executing command on [cloud-run-proxy]: [/nix/store/vh0vainhfkp83dilxp60fsx3pjipd24s-google-cloud-sdk-408.0.1/google-cloud-sdk/bin/cloud-run-proxy: command not found]
```

I'm not sure if there's something I'm missing for the installation of components? `gcloud components list` does claim that Cloud Run Proxy is installed.

**Comment by xlambein** [comment]
Here's a fix: https://github.com/NixOS/nixpkgs/pull/215526

**Comment by xlambein** [comment]
@DerekMaffett Fix was just merged in upstream nixpkgs :-)

**Comment by ckt114** [comment]
> FYI this was just added to nixpkgs. You can do the following:
> 
> ```nix
> google-cloud-sdk.withExtraComponents ([google-cloud-sdk.components.cloud-build-local])
> ```

@xlambein Could you please give the full example how this is used? What file to add this too? Thanks.

**Comment by xlambein** [comment]
@ckt114 Same way as you'd use `google-cloud-sdk` alone, so e.g. in a devShell's `buildInputs`.  See e.g. https://github.com/NixOS/nixpkgs/issues/99280#issuecomment-1267627236

**Comment by ckt114** [comment]
Lol I can’t believe I missed that comment. Thanks a lot @xlambein.

**Comment by ckt114** [comment]
@xlambein Would you able to show me how to install it with `nix-env`? I tried the below command below but it's throwing error.

_command_
`nix-env -f '<nixpkgs>' -iA (google-cloud-sdk.withExtraComponents [google-cloud-sdk.components.cloud-build-local])`

_error_
`
error: attribute '(google-cloud-sdk' in selection path '(google-cloud-sdk.withExtraComponents' not found
       Did you mean google-cloud-sdk?
`

**Comment by xlambein** [comment]
I've actually never used `nix-env`, but looking at your command, it seems like you didn't quote the Nix expression, so maybe try doing that?

Also, in general I'd recommend using a dev shell instead of `nix-env`, see https://nixos.wiki/wiki/Development_environment_with_nix-shell.  It makes it easier to create a reproducible environment for a specific project.

**Comment by ckt114** [comment]
I did quote it with single and double quote but still getting same error. I use nix mainly for the shell to avoid brew updating my tools that I can't downgrade. I tried using nix-shell but it took 3+ seconds to start a nix shell which is quite annoying.

**Comment by kkimdev** [comment]
Hi, what would be the full install command with `nix profile install... ` ?  I tried the following and failed miserably

```bash
$ nix profile install (nixpkgs#google-cloud-sdk.withExtraComponents [pkgs.google-cloud-sdk.components.cloud-build-local])
-bash: syntax error near unexpected token `('
```
