### ISSUE TITLE
catfs

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixpkgs#99315]
**Project description**
caching file-system, written in rust. Designed to work with https://github.com/kahing/goofys

**Metadata**

* homepage URL: https://github.com/kahing/catfs
* source URL: https://github.com/kahing/catfs
* license: Apache2
* platforms: unix, linux, darwin

**Comment by jonringer** [comment]
I don't see any activity for 6+ months, I think I should close my PR and this ticket

**Comment by jonringer** [comment]
I didn't mean activity in my PR, I meant in the upstream repo
