### ISSUE TITLE
handbrake cli broken on x86_64-darwin

### ISSUE THREAD

**Issue by gekoramy** [NixOS/nixpkgs#99317]
**Describe the bug**
I am unable to install [handbrake cli](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/handbrake/default.nix) on macOS.

**To Reproduce**
```
$ nix-env -iA nixpkgs.handbrake
installing 'handbrake-1.3.3'
error: Package ‘numactl-2.0.13’ in /nix/store/zwhn5hiv8y5cm2psrdb33xkwyzz52dh8-nixpkgs-21.03pre243895.72b9660dc18/nixpkgs/pkgs/os-specific/linux/numactl/default.nix:26 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

**Additional context**
https://github.com/NixOS/nixpkgs/blob/ebb5b9ab2e38afb58abd4723a407b39198675754/pkgs/applications/video/handbrake/default.nix#L5-L8

From what I read, handbrake cli should work on macOS

**Notify maintainers**
- @Anton-Latukha 
- @wmertens 

**Metadata**
- system: `"x86_64-darwin"`
- host os: `Darwin 19.6.0, macOS 10.15.7`
- multi-user?: `no`
- sandbox: `no`
- version: `nix-env (Nix) 2.3.7`
- channels(gekoramy): `"home-manager, nixpkgs-21.03pre243895.72b9660dc18"`
- nixpkgs: `/Users/gekoramy/.nix-defexpr/channels/nixpkgs`

**Comment by Anton-Latukha** [comment]
Lets merge the https://github.com/NixOS/nixpkgs/issues/99317 macOS fixes first. It is long without merge, and then troubleshoot this.

**Comment by Anton-Latukha** [comment]
Yep, `numactl` should be solved by that merge.

There is basically a bottleneck of volume that can be processed by the merge throughput.

**Comment by gekoramy** [comment]
I did not notice the PR
Good to know 👍
