### ISSUE TITLE
CMake gets rebuilt for cross because of run-time dependency on pkg-config

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#99325]
I try to do some weird cross and notice that cmake is being rebuilt. That's odd.

Here's why:

1. pkg-config now has a target-specific wrapper.
2. CMake has long had a run-time dep on package config

So either we give CMake a wrapper too (ugh...) or we just remove pkg-config from `buildDepends` of CMake. I learn towards the latter.

CC @matthewbauer and @LnL7, who I think added the dep?

**Comment by LnL7** [comment]
I only made some dependencies optional at some point to reduce the number of things needed to bootstrap. What's the issue exactly? I you mean moving pkgconfig to nativeBuildInputs the that sounds fine to me.

**Comment by Ericson2314** [comment]
> What's the issue exactly?

CMake is rebuilt when it's target platform changes..

> If you mean moving pkgconfig to nativeBuildInputs then that sounds fine to me.

Oh, I assume it had some `nativeBuildInputs` and so it was in `buildInputs` in purpose, but maybe it wasn't!

Also, do we know what the setup hook is a `buildInput`?
