### ISSUE TITLE
nix-env: Install-name/uninstall-name mismatch

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#9937]
Hi,

I really dislike that there are a lot of packages where the install name is not the same as the uninstall name:

``` 
nix-env -iA nixos.utillinuxCurses # installing ...
nix-env -e utillinuxCurses # nope...
nix-env -e util-linux # nope ...
nix-env -e util-linux-curses # aah, here we go
```

Why is that and is there a way to fix this?

**Comment by vcunat** [comment]
The -e names should correspond to the names used by -i without -A. It's also what's shown in the list of installed packages (`nix-env -q`).

Still, the two "naming systems" are a thing to improve, IMO, in the long term.

**Comment by Profpatsch** [comment]
Isn’t the solution adding `-eA`?

And in the long term finally changing `-i` to mean `-iA`?

**Comment by matthiasbeyer** [comment]
> `-eA`

Such a thing exists?

**Comment by Profpatsch** [comment]
Nope, it doesn’t (yet?).

**Comment by Profpatsch** [comment]
But I (and most mathematicians) think it’s nice to have inverses.

**Comment by matthiasbeyer** [comment]
> Nope, it doesn’t (yet?).

Do you want to file a feature request for `nix` or shall I? :smile:

**Comment by Profpatsch** [comment]
The stage is yours. :P

**Comment by vcunat** [comment]
So I guess we close this one when we have the feature request.
