### ISSUE TITLE
df location

### ISSUE THREAD

**Issue by halturin** [NixOS/nixpkgs#99387]
**Describe the bug**
current location of 'df' is /run/current-system/sw/bin/df
but some application is expected to find it at /bin directory (Erlang, to be specific - https://github.com/erlang/otp/blob/maint-22/lib/os_mon/src/disksup.erl#L266 )

**To Reproduce**
1. install erlang
2. run erl shell
` $ erl `
3. in erl shell
`  1> application:ensure_all_started(os_mon). `
4. try to get info about available disks 
`  2> disksup:get_disk_data(). `

you get empty result: []

**Expected behavior**
![image](https://user-images.githubusercontent.com/118860/94926750-8d415380-04c1-11eb-8cbd-b144c7dd5710.png)

**Screenshot of the problem**
![image](https://user-images.githubusercontent.com/118860/94926833-b19d3000-04c1-11eb-919f-440efd41eafd.png)

**Additional context**
as a workaround i created symlink manualy
`sudo ln -s  /run/current-system/sw/bin/df /bin/df`

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 21.03pre244669.5aba0fe9766 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244932.84d74ae9c9c"`
 - channels(taras): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by deliciouslytyped** [comment]
From my understanding, this is an issue with the applications that depend on df having a specific path, and either need to be compiled with the appropriate flags (if path flexibility is provided in that manner) or patched to, for example, search for binaries from the PATH environment variable.

For erlang, you probably want to search for how that library function implements calling df, and then figure out how something with a nonstandard FHS should interface with it/how it should interface with a nonstandard FHS. ideally it already uses the standard PATH method and you just need to make sure df is in scope.

**Comment by deliciouslytyped** [comment]
My bad, I see you already linked the erl file.

**Comment by deliciouslytyped** [comment]
Ok so yeah, peeking at that erl file, this probably needs an issue filed against OTP upstream. I hope they don't have a specific reason they need to use absolute paths or something. An hackaround in the meantime could be to patch the my_cmd function to try to search PATH for the file name at the end of the path?

**Comment by deliciouslytyped** [comment]
The Erlang issue tracker is at https://bugs.erlang.org/issues , can you please file an issue and then link it here?

**Comment by deliciouslytyped** [comment]
It may be helpful if you can search for additional locations in the OTP codebase that may have this issue.

**Comment by deliciouslytyped** [comment]
Though I don't think it's necessary here, for cases like this you can probably make oneliner repros using nix-shell to get the approrpiate packages in scope and then using --run to pass a script to the language's

**Comment by halturin** [comment]
reported https://bugs.erlang.org/browse/ERL-1370

**Comment by halturin** [comment]
Regarding to the FHS standard https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf (see page 5) df must be located in /bin directory.

**Comment by deliciouslytyped** [comment]
@mikpe /usr/bin/env is one of the few things NixOS seems to leave in place.

**Comment by halturin** [comment]
@deliciouslytyped that fix was just merged into the master. is it possible to backport it into the unstable package here?

**Comment by deliciouslytyped** [comment]
I'm not intimately familiar with erlang and I'm not a nixpkgs maintainer so I don't know how likely it is;

You have a few options:
1. create an overlay for yourself and build your modified erlang locally. You can do this while you wait for something to happen in nixpkgs and while waiting for erlang to release a stable version eventually
2. it looks like we dont currently ship any patches https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/interpreters/ so I'd try to ask the maintainers and / or someone on Freenode/#nixos-dev about shipping modifications
3. you could try making an "unstable" attribute that points to a recent erlang commit

We generally do option 2 for things that aren't yet, or wont be upstreamed, but of course people are allowed to use their judgment.
Option 1 is probably the fastest thing to get something working for you _right now_.
Option 3 is easier than option 2, if it's viable.

**Comment by puffnfresh** [comment]
I can see that OTP 27.1.2 is packaged and contains a fix for this: https://github.com/erlang/otp/blob/44ffe8811dfcf3d2fe04d530c6e8fac5ca384e02/lib/os_mon/src/disksup.erl#L441

In any case, I'd argue this is a problem needs to be followed up with OTP and probably not nixpkgs.
