### ISSUE TITLE
buildah from fedora - while pulling "fedora" as "localhost/fedora": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#99400]
**Describe the bug**

**To Reproduce**
```
buildah from fedora
(image name "fedora" is a short name and no search registries are defined in /etc/containers/registries.conf): while pulling "fedora" as "localhost/fedora": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory


```
**Expected behavior**
add fedora image

**Screenshots**

**Additional context**

**Notify maintainers**

@Profpatsch
@adisbladis
@saschagrunert
@vdemeester
@zowoq

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.9, NixOS, 20.03.2652.076c67fdea6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(ae): `"OsUnstable-21.03pre243854.2a14d21224f, NxUnstable-21.03pre243968.2a35f664394, home-manager-20.03, nixos-20.03.3002.773ef5ae783"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by saschagrunert** [comment]
Since buildah has no module, you probably have to enable:

```
virtualisation.containers.enable = true;
```

**Comment by InLaw** [comment]
The option `virtualisation.containers' defined in `/etc/nixos/configuration.nix' does not exist.

that's a 20.09 option
- a way to use buildah in 20.03?
