### ISSUE TITLE
Broadcom drivers don't compile with linuxPackages_4_2

### ISSUE THREAD

**Issue by aaronlevin** [NixOS/nixpkgs#9948]
I have NixOS installed on a mid-2015 Macbook Pro. The WiFi is not working. More specifically, the wireless chip is not being detected. When enabling the broadcom drivers I get a compile error while running `nixos-rebuild switch`.

Some info:

```
$ sudo lshw -C network
  *-network
       description: Ethernet interface
       physical id: 0
       bus info: pci@0000:0b:00.0
       logical name: enp11s0
       version: 00
       serial: 98:5a:eb:c6:9d:c7
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm vpd msi msix pciexpress bus_master cap_list rom ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=tg3 driverversion=3.137 duplex=full firmware=57762-a1.10 ip=192.168.178.95 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:16 memory:bcf00000-bcf0ffff memory:bcf10000-bcf1ffff memory:b0f00000-b0f0ffff
  *-network UNCLAIMED
       physical id: 0
       bus info: pci@0000:04:00.0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: latency=0
       resources: memory:b0800000-b0807fff memory:b0400000-b07fffff
```

In my `hardware-configuration.nix` I have: 

```
boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
```

and in my `configuration.nix` I have:

```
boot.kernelPackages = pkgs.linuxPackages_4_2;
networking.enableB43Firmware = true;
```

When I run `sudo nixos-rebuild switch` I get the following error:

```
building Nix...
building the system configuration...
download-from-binary-cache.pl: NAR info file ‘http://hydra.nixos.org/aavdh644qh7f0ca8x26is5wqark11635.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
download-from-binary-cache.pl: NAR info file ‘http://hydra.nixos.org/7nc7c92vb7in9bn37rwkyrzk8qgw06rx.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
these derivations will be built:
  /nix/store/32n3c0lwc7lfi57kqzakvjpn3rw8ginn-user-units.drv
  /nix/store/hrswk4cpgffwbvy43igw438l2h3xn9kx-google-talkplugin_5.4.2.0-1_amd64.deb.drv
  /nix/store/k5ddwa2hv1gk5fd8cb3fq9v6254nqky6-google-talk-plugin-5.4.2.0.drv
  /nix/store/d13jzak7pp4dyb71l420vn1rg6l7k734-firefox-with-plugins-40.0.3.drv
  /nix/store/ql6blgah6lspzwf1n8dby3mv23zc04l2-sbt-0.13.9.drv
  /nix/store/8i6vsri1sgqlj7gx4fl2j9npr203r8ak-X11-fonts-builder.drv
  /nix/store/zjy5cncncrh7pv8v2dwc5fxph2m49p3v-X11-fonts.drv
  /nix/store/yxyinypqblj2qv80qm1xv5amq6y309sm-system-path.drv
  /nix/store/ay3sxk83qhbcdviagj37qf54gw3ww01j-system-crontab.drv
  /nix/store/bmj7501q0ahb09bpgykq4dxpk0wa65hx-crontabs.drv
  /nix/store/fna82s9jylyys47yqg39a09nzvq5xmzg-fonts.conf.drv
  /nix/store/1v7p581awpm73dbqvyw38py89gr5di1b-unit-polkit.service.drv
  /nix/store/xwrhxpxrgdhzxrlbs7dkppk6ry6ac4lb-dbus-conf.drv
  /nix/store/99gahjsngh7gg64k2q2w7l5knxzfad85-unit-dbus.service.drv
  /nix/store/xkhjr9l3fg7fmcddim9xv1g7ifklp9vx-unit-mpd.service.drv
  /nix/store/9kv5v2j0214ahs455fd72y5h80zx7v9x-xserver.conf.drv
  /nix/store/6hcsqrz6qxrfv4ac544h32yhzjj7x1fh-slim.cfg.drv
  /nix/store/y7bxgnwp8p0mxa54yklzdmh6sm5mz358-unit-display-manager.service.drv
  /nix/store/raa4ph9apk94dpdz0p5ydzbzwwimnrzr-additional-cups-backends.drv
  /nix/store/3lg1p0qqrd8sib1w972cmwvc835i9sw4-cups-progs.drv
  /nix/store/k5zw89n7x6p433r9kccsj2ld119csfq6-etc-file.drv
  /nix/store/n3054q4v9khvxc0c6czn5i4qm37zq1gh-etc-file.drv
  /nix/store/z67ksfaafxcy7h28jci1hxqb6j68kwip-unit-cups.service.drv
  /nix/store/h7b4z981z2zl41m3pgg4n83209qfq5xc-system-units.drv
  /nix/store/s5w0pparlbj3nmb0b6vyw48a92xhnznn-etc-file.drv
  /nix/store/0kddaxw3s6xhwisfwmhifvd9rr9ng38f-etc.drv
  /nix/store/48hyzscjdn04qcpqh0ql7mr8cj6k2l6b-broadcom-sta-6.30.223.248-4.2.drv
  /nix/store/5yb2aavlhkd3yny9hg821ykbdrcrjgci-kernel-modules.drv
  /nix/store/wwy0jds8q53qmjx6d0jnmwfrz6cr6cfk-kernel-modules-shrunk.drv
  /nix/store/fqdc51hhcg235w3fznxl92f1282h23d9-stage-1-init.sh.drv
  /nix/store/bvlxsjp592bcqkf6hg7341hzrlqnww47-initrd.drv
  /nix/store/xx2lvsjxgm2lvcwg6gwrav9jiwmldfzd-nixos-16.03pre68782.54e430a.drv
these paths will be fetched (250.20 MiB download, 767.39 MiB unpacked):
  /nix/store/0g7rmqfr9dffcyphws47qn40sp5jb7ww-openjdk-8u60b24
  /nix/store/47dnfhys2lg77gwaqd4kzkip478a54ln-gst-ffmpeg-0.10.13
  /nix/store/5kiysgqlvj1bav4lsdig18qagwp4a0g1-libcanberra-0.30
  /nix/store/6b00gxasd16i2hnbd3brxcff6sni1s4j-scala-2.11.7
  /nix/store/6z09n9v7lr9yvrss88jp51h3dlal9n1l-emacs-24.5
  /nix/store/8znia9rh4q4adpy585xazlvk041d31xq-pinentry-0.9.5
  /nix/store/b769ca6819hrw9di5z30icwalsp9jkav-vim_configurable-7.4.826
  /nix/store/dc75l5z9a2ygyyff9jxsrsiwxifvd1db-gnupg-2.0.29
  /nix/store/djw5ypfs2g53jgilwzj8243vl1xxpdl0-cups-2.0.4
  /nix/store/dv7iyy7c6f3gjivdz4j7j23dy2h8ydar-ghostscript-9.15
  /nix/store/iazdmmdnm7b0n2q631q1xjxlism1ckyj-ffmpeg-2.7.2
  /nix/store/ksqcmi2dm946yjb0mbdqs4jjdkgm1qmm-gtk+-2.24.28
  /nix/store/mj1jp68djrww4yijqs2kg67yisp4qcil-chromium-45.0.2454.85
  /nix/store/mrfs4pvcb4n4lvh2jy25476ygy5af21r-chromium-45.0.2454.85
  /nix/store/n694qy03na8m8l4fm5p8685vav9dbjlb-mpd-0.19.9
  /nix/store/przrk1zc7piqry30mr9nsig1m3slqd6c-openjdk-8u60b24-jre
  /nix/store/psgrfdiy91bl04shxpl01j7qb63njada-cups-filters-1.0.71
  /nix/store/wh3vh650g53rfvh5ghbbhlb0vpnm5zxs-ffmpeg-0.10.16
  /nix/store/z0k67cl5zcbyg43qz0wmmrrn679jj41g-firefox-40.0.3
download-from-binary-cache.pl: NAR info file ‘http://hydra.nixos.org/aavdh644qh7f0ca8x26is5wqark11635.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
download-from-binary-cache.pl: NAR info file ‘http://hydra.nixos.org/7nc7c92vb7in9bn37rwkyrzk8qgw06rx.narinfo’ is signed by unknown key ‘hydra.nixos.org-1’; ignoring
fetching path ‘/nix/store/djw5ypfs2g53jgilwzj8243vl1xxpdl0-cups-2.0.4’...
fetching path ‘/nix/store/iazdmmdnm7b0n2q631q1xjxlism1ckyj-ffmpeg-2.7.2’...
fetching path ‘/nix/store/przrk1zc7piqry30mr9nsig1m3slqd6c-openjdk-8u60b24-jre’...
building path(s) ‘/nix/store/bf5r7pc8srzrjz1gid2vh845nlaqs45p-broadcom-sta-6.30.223.248-4.2’
fetching path ‘/nix/store/wh3vh650g53rfvh5ghbbhlb0vpnm5zxs-ffmpeg-0.10.16’...
building path(s) ‘/nix/store/g215knj20szfsjd9hfqkzyn4pvmcsfpr-google-talkplugin_5.4.2.0-1_amd64.deb’
unpacking sources
Makefile
lib/
lib/LICENSE.txt
lib/wlc_hybrid.o_shipped

*** Downloading ‘http://cache.nixos.org/nar/1k76z6s2agv6594xsmwm2gds9jx27bbh6ggdrr7b0diw4gs2s969.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/djw5ypfs2g53jgilwzj8243vl1xxpdl0-cups-2.0.4’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Spe
*** Downloading ‘http://cache.nixos.org/nar/11rg6pn49a5cw384kdx8ncp2yd5d2jsjr2vgx8jhhjyzcv75xlny.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/iazdmmdnm7b0n2q631q1xjxlism1ckyj-ffmpeg-2.7.2’...
ed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
*** Downloading ‘http://cache.nixos.org/nar/1892k35jblq0kdj7p2w276c4ilz788mh6p5f7rxvpfjk3bx9nv7d.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/przrk1zc7piqry30mr9nsig1m3slqd6c-openjdk-8u60b24-jre’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
*** Downloading ‘http://cache.nixos.org/nar/016is493vkzd4ryp87hfxs8is9ihnl34h08y52i3qc8icb3wp90z.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/wh3vh650g53rfvh5ghbbhlb0vpnm5zxs-ffmpeg-0.10.16’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0src/
src/common/
src/common/include/
src/common/include/proto/
src/common/include/proto/802.11.h
src/common/include/proto/bcmevent.h
src/common/include/proto/bcmeth.h
src/common/include/proto/ethernet.h
src/common/include/proto/ieee80211_radiotap.h
src/common/include/proto/802.1d.h
src/common/include/proto/wpa.h
src/common/include/proto/bcmip.h
src/include/
src/include/packed_section_end.h
src/include/bcmutils.h
src/include/packed_section_start.h
src/include/bcmdefs.h
src/include/epivers.h
src/include/pcicfg.h
src/include/bcmcrypto/
src/include/bcmcrypto/tkhash.h
src/include/siutils.h
src/include/wlioctl.h
src/include/linux_osl.h
src/include/bcmendian.h
src/include/linuxver.h
src/include/osl.h
src/include/typedefs.h
src/shared/
src/shared/bcmwifi/
src/shared/bcmwifi/include/
src/shared/bcmwifi/include/bcmwifi_rates.h
src/shared/bcmwifi/include/bcmwifi_channels.h
src/shared/linux_osl.c
src/wl/
src/wl/sys/
src/wl/sys/wl_linux.c
src/wl/sys/wlc_key.h
src/wl/sys/wlc_utils.h
src/wl/sys/wl_iw.c
src/wl/sys/wlc_types.h
src/wl/sys/wl_export.h
src/wl/sys/wlc_ethereal.h
src/wl/sys/wl_iw.h
src/wl/sys/wlc_wowl.h
src/wl/sys/wl_cfg80211_hybrid.h
src/wl/sys/wl_linux.h
src/wl/sys/wl_cfg80211_hybrid.c
src/wl/sys/wl_dbg.h
src/wl/sys/wlc_pub.h
patching sources
applying patch /nix/store/1x0famv0lh5sm6snqp24yx2zl9wf6nsz-license.patch
patching file src/wl/sys/wl_linux.c
Hunk #1 succeeded at 148 (offset -23 lines).
applying patch /nix/store/6pffh4h8kpd87fr2z4047x938nhr9lcd-linux-recent.patch
patching file src/wl/sys/wl_cfg80211_hybrid.c
patching file src/wl/sys/wl_dbg.h
patching file src/wl/sys/wl_linux.c
Hunk #1 succeeded at 880 (offset 2 lines).
Hunk #2 succeeded at 1272 (offset 2 lines).
Hunk #3 succeeded at 1310 (offset 2 lines).
Hunk #4 succeeded at 1659 (offset 2 lines).
Hunk #5 succeeded at 2161 (offset 2 lines).
Hunk #6 succeeded at 2459 (offset 2 lines).
Hunk #7 succeeded at 2541 (offset 2 lines).
Hunk #8 succeeded at 2672 (offset 2 lines).
Hunk #9 succeeded at 3000 (offset 2 lines).
Hunk #10 succeeded at 3234 (offset 2 lines).
Hunk #11 succeeded at 3313 (offset 2 lines).
Hunk #12 succeeded at 3327 (offset 2 lines).
Hunk #13 succeeded at 3356 (offset 2 lines).
applying patch /nix/store/2m9lvi88kwm3n1mka728zpva8nb54ybs-gcc.patch
patching file Makefile
configuring
no configure script, doing nothing
building
make flags: SHELL=/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash KBASE=/nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0   
KBUILD_NOPEDANTIC=1 make -C /nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0/build M=`pwd`
make[1]: Entering directory '/nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0/build'

trying http://dl.google.com/linux/talkplugin/deb/pool/main/g/google-talkplugin/google-talkplugin_5.4.2.0-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/built-in.o
  CC [M]  /tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/shared/linux_osl.o

  0 26.0M    0  189k    0     0   224k      0  0:01:58 --:--:--  0:01:58  224k
  7 7824k    7  604k    0     0  1118k      0  0:00:06 --:--:--  0:00:06 1160k
  3 3944k    3  145k    0     0   176k      0  0:00:22 --:--:--  0:00:22  176k
  3 6138k    3  194k    0     0   223k      0  0:00:27 --:--:--  0:00:27  223k
  3 7047k    3  229k    0     0   261k      0  0:00:26 --:--:--  0:00:26  261k  CC [M]  /tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_linux.o
  CC [M]  /tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_iw.o
  CC [M]  /tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o
/tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c: In function 'wl_notify_connect_status':
/tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:2075:4: error: too few arguments to function 'cfg80211_disconnected'
    cfg80211_disconnected(ndev, 0, NULL, 0, GFP_KERNEL);
    ^
In file included from /tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:33:0:
/nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0/source/include/net/cfg80211.h:4584:6: note: declared here
 void cfg80211_disconnected(struct net_device *dev, u16 reason,
      ^
/nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0/source/scripts/Makefile.build:258: recipe for target '/tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o' failed
make[4]: *** [/tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o] Error 1
/nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0/source/Makefile:1386: recipe for target '_module_/tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta' failed
make[3]: *** [_module_/tmp/nix-build-broadcom-sta-6.30.223.248-4.2.drv-0/broadcom-sta] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:24: recipe for target '__sub-make' failed
make[1]: *** [__sub-make] Error 2
make[1]: Leaving directory '/nix/store/kqd3h8p1v9mn95d5i6brznkzrir7pm0k-linux-4.2-dev/lib/modules/4.2.0/build'
Makefile:142: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/48hyzscjdn04qcpqh0ql7mr8cj6k2l6b-broadcom-sta-6.30.223.248-4.2.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/5yb2aavlhkd3yny9hg821ykbdrcrjgci-kernel-modules.drv’: 1 dependencies couldn't be built
killing process 4001
killing process 4002
killing process 4011
killing process 4000
cannot build derivation ‘/nix/store/xx2lvsjxgm2lvcwg6gwrav9jiwmldfzd-nixos-16.03pre68782.54e430a.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/xx2lvsjxgm2lvcwg6gwrav9jiwmldfzd-nixos-16.03pre68782.54e430a.drv’ failed
```

**Comment by cstrahan** [comment]
I found some useful info here: https://github.com/longsleep/bcmwl-ubuntu/issues/6

I'll see if I can cook up a patch within the next 24 hours.

**Comment by cstrahan** [comment]
@aaronlevin I think this should be resolved by #9953 (I still need to test it out, though). If you're feeling impatient, feel free to give it a whirl :).

**Comment by aaronlevin** [comment]
@cstrahan thanks so much for the quick fix!

How do I point my `nix-channel` at a specific commit so I can see if this change fixes my WiFi issues?

**Comment by vcunat** [comment]
@aaronlevin: get a nixpkgs tree (e.g. by `git clone`) and use `-f` with `nix-env` or `-I` with many other tools to make them use that custom tree.

**Comment by aaronlevin** [comment]
@vcunat I'm trying that and it's not working. I've cloned nixpkgs, ensured they have the changes, and run `sudo nixos-rebuild -I /home/aaronlevin/dev/oss/nixpkgs/pkgs switch` and it failed. I also tried `/home/aaronlevin/oss/nixpkgs`, same error.

**Comment by vcunat** [comment]
That approach works for me (for many months regularly). You likely need to be more specific about the error.

**Comment by aaronlevin** [comment]
@vcunat the error is that the `broadcom-sta` patch still fails, in the same way it did before, indicating that the alternative `nixpkgs` isn't being picked up.
/cc @cstrahan

**Comment by aaronlevin** [comment]
@vcunat oh, nevermind, the proper command is `-I nixpkgs=....`

**Comment by vcunat** [comment]
I think `-I nixpkgs=/home/aaronlevin/oss/nixpkgs` should work. Perhaps also `-I /home/aaronlevin/oss` will. (On my checkouts I have symlinks that allow a wider range of specifications.)

**Comment by aaronlevin** [comment]
@vcunat yes, I can confirm this worked. 

alas, my WiFi is still not working! 

Thanks for your help.

**Comment by cstrahan** [comment]
@aaronlevin Could you run the following, please?

``` bash
$ cat /sys/class/dmi/id/product_name
```

**Comment by cstrahan** [comment]
My laptop is a late 2014 model: MacBookPro11,3

If you can tell me your product name, I can see if I can find anything relevant on lkml or elsewhere. I'm about to receive a mid-2015 model, and it would certainly be nice to have wifi working when I get it.

**Comment by aaronlevin** [comment]
@cstrahan thanks for looking into this. I feel a bit out of my element but I've been trying hard to figure this out!

my product name is: `MacBookPro11,5`

I've heard tell from some Arch and Fedora users that they have WiFi using so it may be a configuration issue? Though my configuration is pretty basic.

**Comment by cstrahan** [comment]
@aaronlevin Btw, does your MacBook Pro use the ForceTouch trackpad (or whatever it's called)? Curious if you're using 4.2 in order to have keyboard/trackpad work, and if so, how well that's working for you. I saw on the lkml (maybe a month or two ago) that some patches were sent in for keyboard/trackpad fixes on the 2015 models. It's been my intention to backport those patches for NixOS, but I haven't had a chance yet.

**Comment by aaronlevin** [comment]
@cstrahan : yes it's forcetouch. For kernels `3.17`, `3.18`, and `4.1`, the mouse worked and single-clicks worked, but double-tap clicks did not, nor did right-clicks. 

On the `4.2` kernel the mouse works pretty well! I have two-finger scroll and right click and the response is decent.

**Comment by cstrahan** [comment]
@aaronlevin 

Ah, you might want to try removing this line from your config:

    networking.enableB43Firmware = true;

My understanding is that B43 is an alternative implementation, which might be conflicting with broadcom-sta on your machine. Aside from that line, your configuration looks similar to mine.

**Comment by aaronlevin** [comment]
@chaoflow : ok, I'll try that (though I thought I tried that). should I keep the `config.boot.kernelModules.broadcom_sta` in `hardware-configuration.nix`?

**Comment by cstrahan** [comment]
> should I keep the `config.boot.kernelModules.broadcom_sta` in `hardware-configuration.nix`?

Yep. Let me know if that helps, and if not, we'll try something else.

**Comment by aaronlevin** [comment]
@cstrahan still no luck. I've posted my conifguration here: https://gist.github.com/aaronlevin/6d0526fc075c2a2d2c71 let me know if you see anything weird in there. I've messed around a lot in there so likely there's weird stuff happening.

I appreciate the help!

**Comment by cstrahan** [comment]
Hrm...

So, the only real difference I see is that where you have this:

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "wl" ];
    boot.kernelModules = [ "kvm-intel" ];

I have:

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" ];
    boot.kernelModules = [ "kvm-intel" "wl" ];

I suppose it's pretty unlikely, but I perhaps `wl` and/or `cfg80211` kernel modules might not be loaded? If you run `lsmod`, you should see some entries like the following:

    wl                   6294258  0
    cfg80211              440586  1 wl

Meanwhile, I'll try making my config look more like yours and see if I can break my wifi. Thanks for being patient :).

**Comment by aaronlevin** [comment]
@cstrahan yes, I have exactly that on the `lsmod`:

```
[aaronlevin@aaronlevin-nixos:~]$ lsmod | grep wl
wl                   6294258  0
cfg80211              440586  1 wl
```

I think `wl` is attempted to get loaded but there's an error? Here is what dmesg says:

```$ dmesg | grep wl
[    0.481423] wl: module license 'MIXED/Proprietary' taints kernel.
[    0.521045] wl driver 6.30.223.248 (r487574) failed with code 1
[    0.521047] [wl_cfg80211_detach()] in ndev=ffff88046abb1000: IEEE80211ptr=          (null)
```

I'll match your config and see what happens.

**Comment by aaronlevin** [comment]
still no luck!

**Comment by cstrahan** [comment]
Interesting. So, I also have a line like so:

    [    0.481423] wl: module license 'MIXED/Proprietary' taints kernel.

However, I don't see those other two messages. A little googling led me here: https://github.com/coldnew/macbookpro-2015-config

That suggests that there's a driver shipped as part of the kernel which might be usable, depending on your model. Could you run this, please?

    lspci -nn | grep "Network controller"

That should give you the PCI device ID for your network interface. For example, that gives me:

    03:00.0 Network controller [0280]: Broadcom Corporation BCM4360 802.11ac Wireless Network Adapter [14e4:43a0] (rev 03)

Where `14e4:43a0` is the ID.

Let me know what your ID is. If it's listed the following page, we can see if we can skip third-party drivers entirely: https://wireless.wiki.kernel.org/en/users/drivers/brcm80211

**Comment by aaronlevin** [comment]
here is what I get:

```
04:00.0 Network controller [0280]: Broadcom Corporation BCM43602 802.11ac Wireless LAN SoC [14e4:43ba] (rev 01)
```

it says supported in `3.17+`. But if I disable the broadcom drivers (by removing the line from `hardware-configuration.nix`) it still doesn't work. Is there anything else I should do?

I'm am going to try again just for good measure, though.

**Comment by aaronlevin** [comment]
@cstrahan: I disabled the `broadcom-sta` package in `hardware-configuration.nix` and it still didn't work. Looking at `journalctl` logs I see this:

```
Sep 20 21:37:40 aaronlevin-nixos systemd-modules-load[463]: Failed to find module 'wl'
```

**Comment by cstrahan** [comment]
@aaronlevin:

Ok, so this suggests that there's a firmware that has to be fetched separately for `brcmfmac`: http://askubuntu.com/questions/639198/macbook-11-5-wifi-14e443ba-doesnt-work-on-14-04

In fact, I just realized that's what the link form earlier was suggesting, that on Gentoo one would need to install their `sys-kernel/linux-firmw` package to get the firmware.

After a little detective work, it looks like we have the relevant firmware (`brcmfmac43602-pcie.bin`) available as part of our `firmwareLinuxNonfree` package. You should be able to add the following to your config to make the extra firmware available:

    hardware.enableAllFirmware = true;

After that, you'll want to remove any references to `wl` in your config, and I think replace them with `brcmfmac`. After a restart, you might want to try greping `lsmod` for `brcmfmac` and/or grep `lspci -v` (which will tell you which kernel module is in use for each device). After all of that, hopefully wifi works :).

Unfortunately, my device isn't supported, otherwise I'd be my own guinea pig. Mind giving that a go?

**Comment by aaronlevin** [comment]
@cstrahan I will try this now. thanks!!

**Comment by aaronlevin** [comment]
OK, so I removed `'wl"` from the `hardware-configuration.nix`, replaced it with `brcmfmac` and put the `enableAllFirmware` flag there. Still no luck.

here is what `lspci -v` reports:

```
04:00.0 Network controller: Broadcom Corporation BCM43602 802.11ac Wireless LAN SoC (rev 01)
	Subsystem: Apple Inc. Device 0152
	Flags: bus master, fast devsel, latency 0
	Memory at b0800000 (64-bit, non-prefetchable) [size=32K]
	Memory at b0400000 (64-bit, non-prefetchable) [size=4M]
	Capabilities: [48] Power Management version 3
	Capabilities: [58] MSI: Enable- Count=1/16 Maskable- 64bit+
	Capabilities: [68] Vendor Specific Information: Len=44 <?>
	Capabilities: [ac] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [13c] Device Serial Number 47-91-32-ff-ff-7d-ac-bc
	Capabilities: [150] Power Budgeting <?>
	Capabilities: [160] Virtual Channel
	Capabilities: [1b0] Latency Tolerance Reporting
	Capabilities: [220] #15
	Capabilities: [240] L1 PM Substates
```

Also, `sudo lshw -C network` returns (I've removed the ethernet noise):

```
  *-network UNCLAIMED
       physical id: 0
       bus info: pci@0000:04:00.0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: latency=0
       resources: memory:b0800000-b0807fff memory:b0400000-b07fffff
```

Lastly, `lsmod | grep brcmfmac` returns:

```
[aaronlevin@aaronlevin-nixos:~]$ lsmod | grep brcmfmac
brcmfmac              171296  0
brcmutil                5753  1 brcmfmac
mmc_core               94507  1 brcmfmac
cfg80211              440586  1 brcmfmac
```

**Comment by cstrahan** [comment]
Are there any interesting message in `demsg`? Want to make sure `brcmfmac` found the firmware. At least the kernel module is loaded, which is a good sign.

**Comment by vcunat** [comment]
This answer might be what's missing: http://unix.stackexchange.com/questions/225216/driver-for-broadcom-14e443ba-chip

**Comment by aaronlevin** [comment]
@cstrahan: `dmesg | grep brcmfmac` returns nothing.

**Comment by aaronlevin** [comment]
@vcunat I can confirm that when I run `iwconfig` I get:

```
[aaronlevin@aaronlevin-nixos:~]$ iwconfig 
enp11s0   no wireless extensions.

lo        no wireless extensions.
```

I'm unsure how to incorporate the changes suggested in that stack exchange answer.

**Comment by cstrahan** [comment]
@vcunat Oh, right - I stumbled across that tidbit, and then promptly forgot after getting carried away with all of the other tidbits. Thanks!

Any pointers on how to make that change in our kernel builder?

**Comment by cstrahan** [comment]
Ah, this is relevant: https://nixos.org/wiki/How_to_tweak_Linux_kernel_config_options

(What's sort of sad is that I helped write some of that content. Poor memory...)

Something like the following should work, I think:

    nixpkgs.config.packageOverrides = super: let self = super.pkgs; in rec
      {
        linux_4_2 = super.linux_4_2.override {
          extraConfig = "BRCMFMAC_PCIE y";
        };
      };

(I found the config option here: http://cateee.net/lkddb/web-lkddb/BRCMFMAC_PCIE.html)

**Comment by cstrahan** [comment]
@aaronlevin Try putting that snippet in your config. I just started a kernel build to sanity check it, and it looks like I got the incantation right:

    QUESTION:     PCIE bus interface support for FullMAC driver, NAME: BRCMFMAC_PCIE, ALTS: Y/n/?, ANSWER: y

**Comment by vcunat** [comment]
I wonder if there's a reason not to put that into our default config. Moreover, the config line suggests that "Y" is the upstream default.

> (What's sort of sad is that I helped write some of that content. Poor memory...)

That's unavoidable. Therefore, comments and docs *are* needed even in one-man projects.

**Comment by cstrahan** [comment]
> Moreover, the config line suggests that "Y" is the upstream default.

Oh, is that what the capitalization of the "Y" means? I'm still pretty new to this stuff. Only started digging this deep into kernel configuration and such about a year and a half ago - back when I first started contributing to Nix{,OS} :).

**Comment by cstrahan** [comment]
If that config option is supposed to default to "Y", I wonder if it's been enabled all this time. I mean, the only reason I can think of that wifi isn't working for @aaronlevin is because it's *not* enabled... It would be nice to have a way to know at a glance what configuration options were enabled for a given kernel.

If it's not being enabled by default, then yes, I think we ought to enable it for all supporting kernels.

**Comment by aaronlevin** [comment]
@cstrahan : ok, I will try this. I had to dip out to run an errand, will be back in about 15-20. Shoudl I add that to my `configuration.nix` or `hardware-configuration.nix` (I assume the former).

**Comment by cstrahan** [comment]
@aaronlevin The former.

**Comment by cstrahan** [comment]
I think we'll want to add the following to `pkgs/os-specific/linux/kernel/common-config.nix`:

```nix
${if versionAtLeast version "3.17" then ''
  BRCMFMAC_SDIO y
  BRCMFMAC_USB y
  BRCMFMAC_PCIE y
''}
```

That way `brcmfmac` should work without the user needing to customize their kernel. I think I'll open a PR shortly.

**Comment by aaronlevin** [comment]
back. trying now.

**Comment by aaronlevin** [comment]
building the kernel now.

**Comment by cstrahan** [comment]
Oops, I forgot to reopen this. Better late than never, I suppose.

**Comment by aaronlevin** [comment]
@cstrahan success!!!! Writing this to you via wifi! Thanks so, so much for all your help! And to @vcunat as well!!!

**Comment by cstrahan** [comment]
@aaronlevin You're very welcome - glad I could help! And thank you for being so responsive. I just opened a PR to turn on those config settings by default, so you shouldn't need to customize your kernel for too much longer. I'll also update the wiki.

I'm not sure what it would entail, but I might also see if we can have our `nixos-generate-config` detect that the `brcmfmac` driver should be used, instead of `wl` - and also add the `enableAllFirmware` line.

**Comment by rbvermaa** [comment]
@cstrahan Awesome support!

**Comment by vcunat** [comment]
:-) Anyway, closing this, as the original issue was pushed already.
