### ISSUE TITLE
nix-channel --update nixos removes nixos-20.09 channel

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#99552]
**Describe the bug**
nixos-rebuild --upgrade removes one of my channels

**To Reproduce**
Adding a nixos-20.09 channel and then running nixos-rebuild --upgrade removes the channel.
```shell
#  nix-channel --remove nixos-20.09 ; nix-channel --add https://nixos.org/channels/nixos-20.09 nixos-20.09 ; nix-channel --update; nix-instantiate --find-file nixos-20.09 && nixos-rebuild --upgrade test --no-build-output
unpacking channels...
/root/.nix-defexpr/channels/nixos-20.09
unpacking channels...
building Nix...
building the system configuration...
error: file 'nixos-20.09' was not found in the Nix search path (add it using $NIX_PATH or -I), at /etc/nixos/common.nix:20:26
(use '--show-trace' to show detailed location information)

#  echo $NIX_PATH
/root/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels


#  nix-channel --list
nixos https://nixos.org/channels/nixos-20.03
nixos-20.09 https://nixos.org/channels/nixos-20.09
nixos-unstable https://nixos.org/channels/nixos-unstable
                                                                                                                                                                                                     
#  nix-instantiate --find-file nixos-20.09 
error: file 'nixos-20.09' was not found in the Nix search path (add it using $NIX_PATH or -I)

#  ls /root/.nix-defexpr/channels/ 
manifest.nix  nixos  nixos-unstable
```

The channel is still listed in nix-channel --list but is not available to nix.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.03.3087.b4db68ff563 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3087.b4db68ff563, nixos-unstable-21.03pre244932.84d74ae9c9c"`
 - channels(symphorien): `"home-manager-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by symphorien** [comment]
(Note: I also use the channel nixos-unstable with success)

**Comment by symphorien** [comment]
nixos-rebuild without --upgrade is fine.

**Comment by symphorien** [comment]
Minimized to an issue with nix-channel only:
```
#  set -x; nix-channel --remove nixos-20.09 ; nix-channel --add https://nixos.org/channels/nixos-20.09 nixos-20.09 ; nix-channel --update; nix-instantiate --find-file nixos-20.09; nix-channel --update nixos ; nix-instantiate --find-file nixos-20.09 ; set +x
 -zsh:69> nix-channel --remove nixos-20.09
 -zsh:69> nix-channel --add https://nixos.org/channels/nixos-20.09 nixos-20.09
 -zsh:69> nix-channel --update
unpacking channels...
 -zsh:69> nix-instantiate --find-file nixos-20.09
/root/.nix-defexpr/channels/nixos-20.09
 -zsh:69> nix-channel --update nixos
unpacking channels...
 -zsh:69> nix-instantiate --find-file nixos-20.09
error: file 'nixos-20.09' was not found in the Nix search path (add it using $NIX_PATH or -I)
 -zsh:69> set +x
```

**Comment by veprbl** [comment]
It seems like this belongs to the NixOS/nix tracker

**Comment by worldofpeace** [comment]
I think this will be an issue with users that start to use 20.09? I think we should for sure block on it. Though, if we move it to `nix` it won't be in the project. It should probably a an org wide project.

**Comment by symphorien** [comment]
I opened a new issue on  nixos/nix, so you can keep this one if you want :)

**Comment by JustinLovinger** [comment]
@worldofpeace if this only occurs with `nix-channel --add https://nixos.org/channels/nixos-20.09 nixos-20.09`, then I'm not sure it warrants a blocker. A user upgrading to NixOS 20.09 would do `nix-channel --add https://nixos.org/channels/nixos-20.09 nixos`.

When I tested `nix-channel --add https://nixos.org/channels/nixos-20.09 nixos` a couple of weeks ago, I didn't have an issue. @symphorien do you see the same issue with `nix-channel --add https://nixos.org/channels/nixos-20.09 nixos`?

**Comment by symphorien** [comment]
No it does not affect the preexisting `nixos` or `nixos-unstable` channels I had.

**Comment by stephane-rolland** [comment]
Just to say "it happens to me also": I happen to have faced this issue while moving to 20.09

Not horribly blocking since I can of course point to the current nixos channel... 
But I manage a list of all channel on previous and next version just so as to pick package when they break, etc... so it does not mix well with my current setup, since all my machines are not at the same nixos version:

- I have to modify the configuration.nix when the channel 20.09 is suppressed for the package that are explictely pointing at the 20.09 version. In my case it was only for the package "nasm".

**Comment by Artturin** [comment]
nix issue resolved
