### ISSUE TITLE
0ad crashes at startup 

### ISSUE THREAD

**Issue by jorisgio** [NixOS/nixpkgs#9956]
I installed  `nixos.zeroad  0ad-0.0.17`  (`n3qkw6y4hs4zzc666npswz3w0imayqxq-0ad-0.0.17`) and i get a backtrace at startup : 

    [joris@nix:~]$ pyrogenesis 
    Paths.cpp(169): Function call failed: return value was -110301 (Error during IO)
    Function call failed: return value was -110301 (Error during IO) 
    Location: Paths.cpp:169 (Root)
    
    Call stack:
    
    (0x8b988b) pyrogenesis() [0x8b988b]
    (0x8680e1) pyrogenesis() [0x8680e1]
    (0x8683f4) pyrogenesis() [0x8683f4]
    (0x5f1acb) pyrogenesis() [0x5f1acb]
    (0x5f38c8) pyrogenesis() [0x5f38c8]
    (0x5e85c2) pyrogenesis() [0x5e85c2]
    (0x42ceeb) pyrogenesis() [0x42ceeb]
    (0x4210c7) pyrogenesis() [0x4210c7]
    (0x7f4b64f61995) /nix/store/qlxp7vb63fp8kx5vk9a0y3rj8svbvl27-glibc-2.21/lib/libc.so.6(__libc_start_main+0xf5) [0x7f4b64f61995]
    (0x42be89) pyrogenesis() [0x42be89]
     
     errno = 0 (Error during IO)
     OS error = ?

    
    (C)ontinue, (S)uppress, (B)reak, Launch (D)ebugger, or (E)xit?

**Comment by anderspapitto** [comment]
could you try version 18? It's in the unstable channel

**Comment by jorisgio** [comment]
Forgot to comment on this issue, it's fixed indeed.
