### ISSUE TITLE
[security/acme] Enabling OCSP Must-Staple causes Lego to fail

### ISSUE THREAD

**Issue by AstroSnail** [NixOS/nixpkgs#99584]
**Describe the bug**
`security.acme.certs.<name>.ocspMustStaple = true;` causes Lego to fail.

**To Reproduce**
1. In `configuration.nix` set `security.acme.certs.<name>.ocspMustStaple = true;` on an enabled certificate.
2. Switch to this configuration.
3. Observe `acme-<name>.service` fail. Lego complains about an unrecognized (really misplaced) `-must-staple` flag.

**Expected behavior**
The certificate will be successfully fetched, with Must-Staple enabled.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Additional context**
I think the problematic code is here:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme.nix#L124
`--must-staple` should not be in commonOpts, it should instead be in runOpts and renewOpts. Lego runs successfully when `[ "--must-staple" ]` is added to `security.acme.certs.<name>.extraLegoRunFlags` and `extraLegoRenewFlags`.

**Notify maintainers**
@aanderse @andrew-d @arianvp @emilazy @flokli @m1cr0man (the acme team)

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 21.03.20200915.00bf6ab (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-21.03pre244932.84d74ae9c9c"`
 - channels(astro): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: security/acme.nix
```

**Comment by m1cr0man** [comment]
Thanks for the report :) It appears that the --must-staple option is common to both "run" and "renew" modes, but is not _actually_ a common option that can be specified before the mode. I'll get a PR ready for this.
