### ISSUE TITLE
borgbackup: Generated start script is broken

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#99588]
**Describe the bug**
I tried to configure the borgbackup service as described in the wiki to backup `/home/` daily to a remote server, but the generated script that is used by the systemd service is broken.

**To Reproduce**
1. Add `borgbackup` service to your `configuration.nix` with the following content:
```nix
services.borgbackup.jobs.home = {
  paths = "/home";
  encryption = {
    mode = "repokey";
    passphrase = "test";
    # TODO set pass command for password-store
    # passCommand = "echo test";
  };

  doInit = false; #Dont create repo if it does not exist

  # environment.BORG_RSH = "ssh -i /home/danbst/.ssh/id_ed25519";
  repo = "ssh://borg@backup-server:/mnt/backup/borgbackup/${config.networking.hostName}/";
  extraCreateArgs = "--verbose --list --checkpoint-interval 600";
  exclude = [
    "*.pyc"
    ".cache"
  ];
  compression = "lz4";
  startAt = "daily";
};
```

2. Run `nixos-rebuild switch`
3. Look at the generated `/etc/systemd/system/borgbackup-job-home.service`, locate the `ExecStart=` line.
4. Look at the `borgbackup-job-home-start` script, for me it looks like this:
```bash
#!/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/bash -e
on_exit()
{
  exitStatus=$?
  # Reset the EXIT handler, or else we're called again on 'exit' below
  trap - EXIT
  
  exit $exitStatus
}
trap 'on_exit' INT TERM QUIT EXIT

archiveName="baobab-home-$(date +%Y-%m-%dT%H:%M:%S)"
archiveSuffix=".failed"

borg create $extraArgs \
  --compression lz4 \
  --exclude-from /nix/store/hpinywzk3wh8ikjlq7chdbpj30r0kwhz-excludefile \
  $extraCreateArgs \
  "::$archiveName$archiveSuffix" \
  '/home'
borg rename $extraArgs \
  "::$archiveName$archiveSuffix" "$archiveName"

```

5. The ` "::$archiveName$archiveSuffix" \` line does not include a host, the script instantly failes when started. To start the script just run it manually from the `ExecStart=` path.
```
[130] root@baobab> /nix/store/v7bjswwdy688ah66njd4i4ywq0igmc0f-unit-script-borgbackup-job-home-start/bin/borgbackup-job-home-start                                                                                              /home/pinpox
usage: borg create [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
                   [--remote-ratelimit RATE] [--consider-part-files] [--debug-profile FILE] [--rsh RSH] [-n | -s] [--list] [--filter STATUSCHARS] [--json] [--no-cache-sync] [--no-files-cache] [--stdin-name NAME] [-e PATTERN]
                   [--exclude-from EXCLUDEFILE] [--pattern PATTERN] [--patterns-from PATTERNFILE] [--exclude-caches] [--exclude-if-present NAME] [--keep-exclude-tags] [--exclude-nodump] [-x] [--numeric-owner] [--noatime] [--noctime]
                   [--nobirthtime] [--nobsdflags] [--ignore-inode] [--files-cache MODE] [--read-special] [--comment COMMENT] [--timestamp TIMESTAMP] [-c SECONDS] [--chunker-params PARAMS] [-C COMPRESSION]
                   ARCHIVE [PATH [PATH ...]]
borg create: error: argument ARCHIVE: Invalid location format: "::baobab-home-2020-10-04T21:19:20.failed"
```
Borg obviously complains, because there is no `user@host` in the repo specified by the script

**Expected behavior**
Borg backups `/home` daily to my server

**Notify maintainers**
@dotlambda @Mic92 @jonringer @ngiger @yorickvP @danbst @Ma27 @volth @ciil 

**Metadata**

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
`root@baobab> nix-shell -p nix-info --run "nix-info -m"`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 21.03pre244932.84d74ae9c9c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244932.84d74ae9c9c"`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: borgbackup
# a list of nixos modules affected by the problem
module: borgbackup
```

**Comment by Ma27** [comment]
Well calling the script manually doesn't work since it depends on the environment defined in the systemd service. So can you please show us what's in the `journald`-logs when starting the script (`journalctl -u borgbackup-job-home.service`) and what your systemd unit looks like (`systemctl cat borgbackup-job-home.service`)?

**Comment by pinpox** [comment]
@Ma27 Nevermind, it's working. I had an unrelated bug in my configuration which made it fail, then tried to debug the script by running it manually, which - like you said above - doesn't work. All fixed and working now, sorry for the inconvenience!

**Comment by Ma27** [comment]
Great to hear that it works now! :)

**Comment by yorickvP** [comment]
If you want to call these borg scripts for manual intervention, the module installs some wrappers in the form of `borg-job-$NAME` into your environment, in your case, `sudo borg-job-home`
