### ISSUE TITLE
Invalid hash validation at pkgs.fetchFromGitHub

### ISSUE THREAD

**Issue by diegobernardes** [NixOS/nixpkgs#99597]
**Describe the bug**
Looks like the hash is not being correctly checked with `pkgs.fetchFromGitHub`.

**To Reproduce**
This snippet works fine on my machine. But I've added an invalid hash at the `fzf` plugin.
```
{ config, pkgs, ... }:

{
  programs.fish = {
    enable = true;

    plugins = [
      {
        name = "fzf";
        src = pkgs.fetchFromGitHub {
          owner = "jethrokuan";
          repo = "fzf";
          rev = "c3defd4a922e97120503b45e26efa775bc672b50";
          sha256 = "0hvj3zqrx5vhbhcszrgd9cczkn97236zfbx7iwjx3grnk556r53c";
        };
      }
    ];
  };
}
```

Changing the hash to `0000000000000000000000000000000000000000000000000000` gives me this error:
```
trying https://github.com/jethrokuan/fzf/archive/c3defd4a922e97120503b45e26efa775bc672b50.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   156  100   156    0     0    861      0 --:--:-- --:--:-- --:--:--   861
100  4422    0  4422    0     0  10681      0 --:--:-- --:--:-- --:--:--  166k
unpacking source archive /private/var/folders/0m/_pktt2gj0sjcmjt7dhv7gc442j_tbb/T/nix-build-source.drv-0/c3defd4a922e97120503b45e26efa775bc672b50.tar.gz
hash mismatch in fixed-output derivation '/nix/store/83jc0zp2qw3rvzjpd5xnfhyvzh0h2klr-source':
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:1zfn4ii6vq444h5rghsd7biip1x3zkh9nyvzd1l8ma8ja9y6q77x
cannot build derivation '/nix/store/km3d8rhgha3qyarq6xnnhdh23g78q9bm-hm_fishconf.dpluginfzf.fish.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x2yx9j27310qbk3z9v73z8dchb25d30j-home-manager-files.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/aacbk2v31qfy15likm4qx620h1iv2qga-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/aacbk2v31qfy15likm4qx620h1iv2qga-home-manager-generation.drv' failed
```

**Expected behavior**
I would expect to have an error using the wrong hash.

**Metadata**
```
➜  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(dbernardes): `"home-manager, nixpkgs-21.03pre244772.502845c3e31"`
 - nixpkgs: `/Users/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by veprbl** [comment]
> I would expect to have an error using the wrong hash.

You must have had some fixed output derivation producing an output with the `0hvj3zqrx5vhbhcszrgd9cczkn97236zfbx7iwjx3grnk556r53c` hash. This is a design decision for the `fetchFromGitHub`'s output to not change on the repo address or revision change. It allows to avoid rebuilds in certain situations at a cost of having occasional problems during the development like the one you've encountered.

**Comment by rmcgibbo** [comment]
(I was sent here by CodeTriage)

I think @veprbl's answer sums this up as a "feature, not a bug". Or, it's really a necessary corollary of a feature of not re-downloading fixed-output derivations.

IMHO this issue can be closed.

**Comment by jalaziz** [comment]
Sorry to be commenting on a closed issue, but I just ran into this myself trying to update a package for nixpkgs. I get that it's a feature, but it's super confusing and not very intuitive. Especially given that https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes doesn't really mention this caveat.

I love what Nix is trying to do, but I keep running into gotchas that make me want to run for the hills as someone who is new to the community.
