### ISSUE TITLE
[20.09] nixosTests.latestKernel.hardened fails

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#99600]
**Describe the bug**
See https://hydra.nixos.org/build/128036443. Its done it several times so far https://hydra.nixos.org/job/nixos/release-20.09/nixos.tests.latestKernel.hardened.x86_64-linux.
It fails very early in the test (20~ secs) at this step
```
hidepid=2 option is applied and works
machine: must succeed: grep -Fq hidepid=2 /proc/mounts
machine: output: 
Test "hidepid=2 option is applied and works" failed with error: "command `grep -Fq hidepid=2 /proc/mounts` failed (exit code 1)"
error: 
Traceback (most recent call last):
  File "/nix/store/rnf8h4jq33rgc1sczhchkksgxnykar0j-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 901, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 21, in <module>
  File "/nix/store/rnf8h4jq33rgc1sczhchkksgxnykar0j-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 423, in succeed
    raise Exception(
Exception: command `grep -Fq hidepid=2 /proc/mounts` failed (exit code 1)
```

The code in the test in question: https://github.com/NixOS/nixpkgs/blob/77cdb1f64f9e365e41beb61f1683948e6261152c/nixos/tests/hardened.nix#L68

Interestingly, the regular `hardened` test doesn't fail https://hydra.nixos.org/build/128029367. So it's an issue with `latestKernel` specifically.

**Expected behavior**
:green_circle:  not :red_circle: 

**Notify maintainers**

@joachifm @emilazy @NeQuissimus 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixosTests.latestKernel.hardened
# a list of nixos modules affected by the problem
module:
```

**Comment by NeQuissimus** [comment]
Should be fixed in #99622

**Comment by vcunat** [comment]
I didn't notice you opened this and unblocked the channel temporarily by ad3a5d509.

**Comment by worldofpeace** [comment]
Thanks for fixing :heart:
