### ISSUE TITLE
awsebcli Missing service ID

### ISSUE THREAD

**Issue by cschmatzler** [NixOS/nixpkgs#99627]
**Describe the bug**
Initiating a project fails with `ERROR: MissingServiceIdError - The model being used for the service elasticbeanstalk is missing the serviceId metadata property, which is required.`

**To Reproduce**
1. Install awsebcli on stable channel declaratively
2. Run `eb init`

**Expected behavior**
CLI intiates project

**Screenshots**
N/A

**Additional context**
N/A

**Notify maintainers**
@eqyiel

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 20.03.2964.252bfe01075 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2964.252bfe01075"`
 - channels(christoph): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by maluramichael** [comment]
Is there a workaround for this?

**Comment by simonc-cn** [comment]
This is because `botocore` has advanced, but the version of `awsebcli` packaged by NixOS is from 2018.  It needs to be bumped to something a bit more modern.

**Comment by kirillrdy** [comment]
I am not a nix expert but i managed to get `awsebcli` working https://github.com/kirillrdy/nixpkgs/commit/7902a02c74e830b6b3952928f98649b4eb75f5d0
Hopefully someone who knows what they are doing can make it into mergeable PR

**Comment by kirillrdy** [comment]
I still use awsebcli

**Comment by kirillrdy** [comment]
if you are using nix flakes you can install awsebcli using 
```
nix profile install github:kirillrdy/nixpkgs/awsebcli#awsebcli
```

**Comment by kirillrdy** [comment]
@cschmatzler this issue should be now resolved
