### ISSUE TITLE
py3exiv2 version 0.7.0 -> 0.8.0

### ISSUE THREAD

**Issue by zoranbosnjak** [NixOS/nixpkgs#99623]
**Describe the bug**
`py3exiv2` package is currently at version 0.7.0 and is marked broken.
The version 0.8.0 which is available from the same source seems OK.

It is very likely that switching to version 0.8.0 will fix the problem.
Setup patch might not be necessary any more.

**To Reproduce**
```bash
nix-build '<nixpkgs>' -A python3Packages.py3exiv2
```
**Expected behavior**
- successfull build
- non-broken package

**Additional context**
I have successfully built version 0.8.0 (with build dependencies of version 0.7.0).

**Notify maintainers**
@vinymeuh 

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/q2bh089frm32ys4gx104gc2c3p96b647-nix-info
copying path '/nix/store/q2bh089frm32ys4gx104gc2c3p96b647-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-42-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(zoranb): `"nixpkgs-21.03pre243895.72b9660dc18"`
 - nixpkgs: `/home/zoranb/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.py3exiv2
# a list of nixos modules affected by the problem
module:
```

**Comment by vinymeuh** [comment]
I no more using nix so can't easily help you. If you already have a working version, perhaps you can clone ﻿nixpkgs and then submit a pull request
