### ISSUE TITLE
How to find the oracle-xe default password for system admin ?

### ISSUE THREAD

**Issue by cata0309** [NixOS/nixpkgs#99649]
I installed oracle-xe but I cannot find the password ! How to find it ?

**Comment by aanderse** [comment]
@aszlig do you have any capacity to bump the version of this software. Seems like the latest release is `18.4.0.0.0`... there must be a **ton** of CVEs against our version.

ping @flokli in case you still have to manage and `oracle` stuff these days (though I'm guessing not).

@cata0309 does [this] (https://www.oracle.com/ca-en/database/technologies/howto-connect-xe.html) help at all?

**Comment by aszlig** [comment]
> do you have any capacity to bump the version of this software. Seems like the latest release is 18.4.0.0.0... there must be a ton of CVEs against our version.

Unfortunately no, since I never used it and I'd rather opt for removing it entirely if nobody suddenly steps up to maintain it.

**Comment by cata0309** [comment]
@aanderse I tried that but it doesn't work, it doesn't work at all, at least remove it from the repos

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/pull/100088 removes `oracleXE`.
