### ISSUE TITLE
QA ISO images

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#99648]
**Describe the bug**
Some amount of manual QA is needed to verify these images are in good shape. In 20.03 we had a pretty silly bug slip through and got dragged on HN :rofl: 

Even without that as encouragement this is a good idea.

The main goal is to determine the following:
> It needs to be verified that all ISO's that are using a release blocking desktop boot cleanly in their supported configurations. They must boot live when written to a USB stick with **any** of our supported methods documented in the NixOS manual.

I've drafted some criteria to look out for when testing a desktop. The version for this exact issue can be seen at this [gist](https://gist.github.com/worldofpeace/019e0b77020affbe3c3623d807f73f22).
After having testing please comment with a checklist on the items like
```markdown
- [x] Shutdown, reboot, login, logout
...
```

The following images need testing:

- [x] Plasma5 ISO
- [x] GNOME ISO

Here are links to the latest images:
https://channels.nixos.org/nixos-20.09/latest-nixos-plasma5-x86_64-linux.iso
~https://channels.nixos.org/nixos-20.09/latest-nixos-gnome-x86_64-linux.iso~

The gnome iso isn't added to the channel atm: 
You can get it from an eval of it on hydra: https://hydra.nixos.org/job/nixos/release-20.09/nixos.iso_gnome.x86_64-linux
picking a build  https://hydra.nixos.org/build/128080348
and selecting `Link` from `Build Products`.

# Remaining Q.A tasks

## Plasma
- [x] Printing https://github.com/NixOS/nixpkgs/issues/98536
- [ ] Keyboard layout configuration
  - [ ] unlocking encrypted storage volumes
  - [x] console - this is tested automatically
  - [ ] When logging in via the default login manager for a release-blocking desktop
  - [ ] After logging in to a release-blocking desktop, if the user account does not have its own keyboard layout configuration for that desktop (if there is such a user/desktop-specific configuration, it must be used when that user logs in to that desktop)
- [ ] Desktop Keyring
- [ ] User Switching?

## GNOME
- [x] configured keyboard layout (using nixos options) is used when unlocking encrypted storage volumes
- [x] Desktop Keyring

**Comment by davidak** [comment]
This is very important! I plan to test the images when time permits.

(the link is for 20.03)

Very good that you also document the process.

**Comment by worldofpeace** [comment]
Hmm, I will see what the link to the gnome image is. It should be distributed now.

**Comment by worldofpeace** [comment]
Okay, it's not being put in the channel :frowning: https://releases.nixos.org/nixos/20.09/nixos-20.09beta977.ad3a5d5092e

**Comment by worldofpeace** [comment]
I opened an issue, we need to have that in the channel.
I will get a link from hydra for now in the issue description.

**Comment by rissson** [comment]
> USB Drive created with dd on linux (NixOS)

You can tick "boots on EFI" I tried that last Saturday :D

**Comment by edolstra** [comment]
FWIW I did a successful installation from USB using a Plasma5 ISO. Didn't test it very systematically but the desktop environment and wireless (nmcli) seemed to work fine.

The only issue was that the initrd couldn't mount the root filesystem automatically because I didn't label the USB stick, but I think that's a long-standing issue.

**Comment by davidak** [comment]
>The only issue was that the initrd couldn't mount the root filesystem automatically because I didn't label the USB stick, but I think that's a long-standing issue.

how have you created the stick? i think this don't happen when you follow the manual und use dd

**Comment by birlorg** [comment]
I just did a successful installation today from USB using the Plasma5 ISO(https://channels.nixos.org/nixos-20.09/latest-nixos-plasma5-x86_64-linux.iso)

Worked fine used `dd` from a macOS machine to write the ISO to a USB stick, didn't have any trouble finding the root FS.

Thanks everyone for your work so I could have happy installs!

**Comment by worldofpeace** [comment]
So here are the last few items that need testing in the plasma5 image, I seemed to have missed these from @davidak review:

- [ ] Printing
- [ ] Keyboard layout configuration
- [ ] Desktop Keyring
- [ ] User Switching

The points that had **needs instructions**, I will try to link to Plasma docs:
* https://docs.kde.org/index.php?language=en&package=kde-workspace
* https://docs.kde.org/stable5/en/kde-workspace/plasma-desktop/index.html

and add `Instructions` to some of the sections below.

#### Printing
Printing must work in release-blocking desktops on at least one printer available to those performing validation testing.

####  Keyboard layout configuration
If a particular keyboard layout has been configured for the system, that keyboard layout must be used:
  * When unlocking encrypted storage volumes during boot
  * When logging in at a console
  * When logging in via the default login manager for a release-blocking desktop
  * After logging in to a release-blocking desktop, if the user account does not have its own keyboard layout configuration for that desktop (if there is such a user/desktop-specific configuration, it must be used when that user logs in to that desktop)

This one is kinda complex and probably does require an install to verify.
There are keymap tests https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/keymap.nix, but these aren't for how keymaps are handled in plasma5 or gnome. So you can cross off `When logging in at console` because that is validated automatically.

This is how you configure your keymap in nixos:
```nix
console.keyMap = "dvorkak";
services.xserver = {
  layout = "us";
  xkbVariant = "dvorak";
};
```

that's an example for us+dvorak.

In addition to this, a user can configure their layout without those options from `systemsettings` in `plasma` and `gnome-control-center` in `gnome`. The third point `When logging in via the default login manager for a release-blocking desktop` is actually **very** important and I've actually seen this regress in some places. It would look like "I configured dvorak", "but at display-manager it's colemak" or whatever layout. But in the actual desktop it's the configured layout.

I hope this is helpful and let me know if you have any other questions.

#### Desktop Keyring
Saving passwords to and retrieving passwords from the default keyring must work for all release-blocking desktops.

#### Instructions
In plasma they use `kwallet`:
- https://docs.kde.org/stable5/en/kdeutils/kwallet5/index.html

Using the `kwallet` application should suffice.

The way I usually test this is by using `networkmanager` and creating a new connection and using `store only for this user`, which should be default IIRC. I believe on an installed system the default wallet will be created from your login credentials, so you **shouldn't** have to create it. As for in the ISO, there is a default password but it is **empty**, so I'm wondering if this is going to work.

In gnome they use `gnome-keyring`:
- https://wiki.gnome.org/Projects/GnomeKeyring/

Opening `seahorse` and checking if the `Login` keyring is created
**and** unlocked. If it isn't unlocked this means the PAM module is broken somehow.

You can also test this with `networkmanager` like how I mentioned above.

#### User Switching
User switching must work using the mechanisms offered (if any) by all release-blocking desktops in their default configuration.

#### Instructions 
This is best tested on an installed system with `users.users` creating a secondary user, and then using the `switch user` dialog. I know in `gnome` you can create a user imperatively (I know terrifying). I've never looked if you could do that in Plasma on NixOS, but it should be there.

**Comment by worldofpeace** [comment]
# NixOS 20.09 GNOME Q.A

### Shutdown, reboot, login, logout
Shutting down, rebooting, logging in and logging out must work using standard console commands and the mechanisms offered (if any) by all release-blocking desktops. 

- [x] shutdown/poweroff
- [x] reboot
- [x] login
- [x] logout

I also tested suspend, but that can be fickle.

### Required Applications
It must be possible to run a browser and a terminal applications from all release blocking desktops.

- [x] browser 

Firefox started.

- [x] terminal

gnome-terminal is tested to start anyways.

### Desktop Background


The desktop background should be different than the last release.

This was more of a todo, so skipping.

### Artwork
Proposed artwork for the new NixOS release should be used as the background on release-blocking desktops and there should be a new logo.

This was also more of a todo, but we do use a NixOS wallpaper
- [x] uses nixos wallpaper

### Release-blocking images must boot
It needs to be verified that all ISO's that are using a release blocking desktop boot cleanly in their supported configurations.

They must boot live when written to a USB stick with **any** of our supported methods documented in the NixOS manual.

USB Drive created with dd on linux (NixOS)

- [X] Boots on EFI
- [ ] Boots on BIOS

### Release-blocking images must not be excessively large
Firefox told me the download was 1.3 GiB, that's pretty good.

### Working sound
Installed system should be able to play back sound

I tested this in various ways, since I think it should be able to play back **sound** in several ways

- [x] Played a video in firefox
- [x] system bell and volume sound
- [x] Plugged in a headphones and listened to same video
- [x] Downloaded video with youtube-dl and listening in gnome-music
- [x] The above with headphones

### Non-crashing desktop
Not any part of the release blocking desktop should crash when interacted with, on startup, or be non-functional.

- [x] doesn't crash

### Automatic mounting
Automatic mounting of removable media on insertion must work in release-blocking desktops.

- [x] Mounted a LUKS encrypted USB

### Printing
Printing must work in release-blocking desktops on at least one printer available to those performing validation testing.

- [x] Printed a test page on installed system

### `nix-env`
Software should be able to be installed, removed, and updated with nix-env.

- [x] Install
- [x] Remove
- [x] Update

### Keyboard layout configuration
- [ ] unlocking encrypted storage volumes - didn't test :x: 
- [x] console - this is tested automatically
- [x] When logging in via the default login manager for a release-blocking desktop
- [x] After logging in to a release-blocking desktop, if the user account does not have its own keyboard layout configuration for that desktop (if there is such a user/desktop-specific configuration, it must be used when that user logs in to that desktop)

In this case I made a new user, configured it for dvorak, and it was dvorak when I logged in.

### Desktop Keyring 


Saving passwords to and retrieving passwords from the default keyring must work for all release-blocking desktops. 

- [ ] :red_circle: It asks me to create `Default Keyring` in live environment

### User switching
User switching must work using the mechanisms offered (if any) by all release-blocking desktops in their default configuration. This requires creating another user.

- [x] User switching

GNOME doesn't seem to provide a "Switch User", so logging and and logging out seem to suffice. And I could create a new user for this.

### GNOME specific etc.
GNOME initial setup shows up which is actually very very helpful in a LIVE environment.

* `services.xserver.libinput.tapping` which enables `tap-to-click` is **not** respected. I think we can use a dconf override in the `gnome3.nix` module to make this work for now.

* We need to override `favorite-apps` to use `firefox`. This will make it a default item in the dock.

* Don't ship epiphany anymore

This browser is not doing good in nixos atm https://github.com/NixOS/nixpkgs/issues/98819


* firefox was not using Cantarell

It was using DejaVu instead. Why isn't firefox preferring the system font?

* subpixel rendering?

With the default font of Cantarell it is noticable that lcd subpixel rendering is better. With fonts like Inter I don't really see a different between grayscale or subpixel.

**Comment by worldofpeace** [comment]
This is the remaining testing needed for GNOME, and anyone is free to duplicate my tests

- [ ] configured keyboard layout (using nixos options) is used when unlocking encrypted storage volumes
- [ ] Desktop Keyring

**Comment by birlorg** [comment]
Everything below is from the booted nixOS ISO image (not booted from the internal hard drive):

# KWallet

Kwallet seems to work OK. I had to "force close".  I've never used Kwallet before, but I could create a wallet, create a password int he wallet save it all, close Kwallet, open the wallet and view my password.

# Keyboard Layout

Keyboard Layout Config: via plasma's system settings I changed to English UK, applied and the changes took effect in the desktop, but did not take effect in the console.

# wallpaper

Wasn't on your list, but my Plasma ISO does not use the NixOS wallpaper or logo anywhere within Plasma.  The default wallpaper (desktop background) image is labeled "Next"

# Printers

I don't have a printer around, but launching the printer config dialog I get a box saying: "Print Service is Unavailable, Bad File Descriptor"

If I click the printer icon on the bottom right, I get a nix store error: "Error loading QML file: then a nix store path ending in "printmanager.qml"  looks like it's trying to load from package "printmanager-20.08.1"

full error:

```
Error loading QML file: file:///nix/store/5byybbmrl6x408ykwg46xb49jxszb47b-print-manager-20.08.1/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/printmanager.qml:64:34: Type PopupDialog unavailable
file:///nix/store/5byybbmrl6x408ykwg46xb49jxszb47b-print-manager-20.08.1/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/PopupDialog.qml:81:23: Type PrinterItem unavailable
file:///nix/store/5byybbmrl6x408ykwg46xb49jxszb47b-print-manager-20.08.1/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/PrinterItem.qml:28:1: Type PlasmaExtras.ExpandableListItem unavailable
file:///nix/store/79fasdyzfj50ybrygl90qy0aj8i3j2wb-plasma-framework-5.73.0-bin/lib/qt-5.12.7/qml/org/kde/plasma/extras/ExpandableListItem.qml:20:1: module "QtQuick" version 2.14 is not installed
```

# users

There doesn't appear to be a way to add/switch users from within KDE, while booted from the ISO.  

I've never really used KDE/Plasma before, so I have no idea what I'm doing.  Overall it all seemed to work. I pushed a bunch of buttons and generally tried to mess things up.

Again, everything above was done from the live ISO, not booted from the HDD.

**Comment by worldofpeace** [comment]
I've thought to seed the configuration.nix from nixos-generate-config with the config for the desktop environment https://github.com/NixOS/nixpkgs/pull/100199. Probably should add that to requirements that the generated hardware and configuration.nix are all build-able and match the ISO environment as close as possible so the user can reproduce it easily.

**Comment by davidak** [comment]
- [X] I also bootet the plasma iso on EFI successfully on my system

**Comment by worldofpeace** [comment]
> with GNOME desktop, you don't have the manual and terminal on desktop, so you might get lost. an introductions opens, but that is just an intro. to GNOME. maybe we can inject a link to the manual there?

We could add it as a favorite https://github.com/NixOS/nixpkgs/blob/230728216ab79a7579b6549a91380aa9a1a3a0a0/nixos/modules/services/x11/desktop-managers/gnome3.nix#L46

**Comment by worldofpeace** [comment]
Tracking the issue with plasma5 printing here https://github.com/NixOS/nixpkgs/issues/98536. I'm going to move what's left for plasma5 QA etc. into the OP

**Comment by davidak** [comment]
GNOME Software is not usable in the live environment and i think also in GNOME unless you activate Flatpak, so maybe don't have it by dafault in GNOME? People will review NixOS and say it's broken...

![Screenshot from 2020-10-11 10-25-24](https://user-images.githubusercontent.com/91113/95676575-594fe780-0bbf-11eb-948e-6a937adce97b.png)


Also, i noticed GNOME uses Wayland now. Does that generally work, for example with games using Steam?

**Comment by worldofpeace** [comment]
> GNOME Software is not usable in the live environment and i think also in GNOME unless you activate Flatpak, so maybe don't have it by dafault in GNOME? People will review NixOS and say it's broken...
> 
> ![Screenshot from 2020-10-11 10-25-24](https://user-images.githubusercontent.com/91113/95676575-594fe780-0bbf-11eb-948e-6a937adce97b.png)
> 
> Also, i noticed GNOME uses Wayland now. Does that generally work, for example with games using Steam?

There's Xwayland :+1: We thought to default to the xorg session, but that's old news (it's been default for a bit) and the Wayland session should be fine for the live system. I've played stuff using Steam on the Wayland session just fine, I believe it will just use Xwayland when necessary.

**Comment by worldofpeace** [comment]
> GNOME Software is not usable in the live environment and i think also in GNOME unless you activate Flatpak, so maybe don't have it by dafault in GNOME? People will review NixOS and say it's broken...

I think in the future we should document this. Though I can't help but feel there was some other reason we did this, like maybe it was for shell extensions and opening .flatpakref files cc @hedning @jtojnar

**Comment by hedning** [comment]
> like maybe it was for shell extensions

Yeah, IIRC that was the reasoning, but Software no longer provides shell extensions, so it's fairly useless without flatpak at the moment.

Perhaps a `services.flatpak.guiPackages` option makes sense, that way the gnome desktop could add `gnome-software` and other desktops could add their preferred options without any clashes. And people would get a flatpak gui automatically if they enabled flatpak.

**Comment by worldofpeace** [comment]
> > like maybe it was for shell extensions
> 
> Yeah, IIRC that was the reasoning, but Software no longer provides shell extensions, so it's fairly useless without flatpak at the moment.
> 
> Perhaps a `services.flatpak.guiPackages` option makes sense, that way the gnome desktop could add `gnome-software` and other desktops could add their preferred options without any clashes. And people would get a flatpak gui automatically if they enabled flatpak.

Sounds slick, that would mean Plasma Discover users could benefit from, and pantheon with appcenter and... I think that makes the point pretty clear :grin:

**Comment by worldofpeace** [comment]
I'm considering this as close to finished as it will be since we only have a few days. Thanks everyone :+1:
