### ISSUE TITLE
Remove current release documentation from the NixOS manual

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#99646]
**Describe the bug**
We've decided internally that this documentation would best live in a GitHub wiki at https://github.com/NixOS/release-wiki.
What's important is we can easily edit it as the release process changes. The current documentation being in the nixos manual makes no sense. This is a manual for users of NixOS, yet we also have "hey, if you were interested in seeing how we release nixos in detail there's this". This information seems to live best in a wiki anyway However, we should still have documentation about the nixos release structure in the manual. It just needs to be information that is important to the enduser to understand.

**Comment by jonringer** [comment]
completed in #124418
