### ISSUE TITLE
nixpkgs-lint: don't find license with new syntax

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#9966]
for example this has a correct license:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/ioping/default.nix#L17

but nixpkgs-lint don't recognize it:

```
$ nixpkgs-lint -f /home/davidak/nixpkgs/ -p ioping
=== Package meta information ===

ioping: Lacks a license

=== Package name collisions ===

=== Bottom line ===
Number of packages: 1
Number of bad names: 0
Number of missing maintainers: 0
Number of missing platforms: 0
Number of missing licenses: 1
Number of missing descriptions: 0
Number of bad descriptions: 0
Number of name collisions: 0
```

**Comment by pSub** [comment]
Fixed with https://github.com/NixOS/nix/pull/712 in the next version of nix.

**Comment by vcunat** [comment]
Thanks!

**Comment by vcunat** [comment]
Next step: have a bot using it on PRs :-)

**Comment by davidak** [comment]
@vcunat great idea. remind if basic meta-data is missing. would you create an issue for that?
