### ISSUE TITLE
obs-ndi 4.7.1 -> 4.9.1

### ISSUE THREAD

**Issue by jshcmpbll** [NixOS/nixpkgs#99681]
**Project description**
The version for the obs-ndi plugin is a bit out of date 

**Metadata**

* homepage URL: https://github.com/Palakis/obs-ndi
* license: gpl2+
* platforms: linux

**Comment by davidak** [comment]
ping maintainer @peti

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/obs-studio/obs-ndi.nix
