### ISSUE TITLE
git-cola: qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by mschneiderwng** [NixOS/nixpkgs#99696]
**Describe the bug**
running `git-cola` results in the error
`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""`

**To Reproduce**
1. try to start git-cola

**Notify maintainers**
@bobvanderlinden 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 21.03pre244932.84d74ae9c9c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244932.84d74ae9c9c"`
 - channels(mschneider): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/99956

**Comment by doronbehar** [comment]
#99956 merged.
