### ISSUE TITLE
nnn fm plugins and icons feature

### ISSUE THREAD

**Issue by timsofteng** [NixOS/nixpkgs#99822]
It would be great to have option to fetch nnn plugins with nxpkgs or with additional package instead of manually fetching it like developer advise.
And second is it possible to implement some option to include icons support from nerdfont to nnn binary file instead of recompiling it?

Thanks.
@jfrankenau

**Comment by Parasrah** [comment]
I think this issue was closed preemptively by the `Partially fixes #99822.` line in the PR, there doesn't seem to be any way to include plugins as of now

**Comment by plabadens** [comment]
nnn seems to expect plugins in `$XDG_CONFIG_HOME/nnn/plugins`. This might work better as a home-manager module, maybe with the plugins themselves in as an output of nixpkgs. I might take a look at this next week.

**Comment by fedoranvar** [comment]
I've recompiled nnn with icons, by using unstable branch and overriding nnn-package:

```nix
# <...>

environment.systemPackages = with pkgs;
    let
      unstable = import (fetchTarball https://nixos.org/channels/nixos-unstab  unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) { config = config.nixpkgs.config; };
    in
      [
        (unstable.nnn.override { withNerdIcons = true; })
     ]
     
# <..>
```
