### ISSUE TITLE
newt isn't built with python module

### ISSUE THREAD

**Issue by Dieken** [NixOS/nixpkgs#99918]
**Describe the bug**

byobu-config depends on newt's python module, but newt in nixpkgs doesn't have python module built.

**To Reproduce**
1. nix-env -iA nixos.byobu
2. byobu-config reports "Could not import python snack module"

**Expected behavior**

byobu-config runs successfully.

**Additional context**

The newt/configure and newt/configure.ac should be patched to detect python, and newt should depend on some python version.

https://github.com/Homebrew/legacy-homebrew/issues/43989

**Notify maintainers**

@viric

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.68, NixOS, 20.03.3087.b4db68ff563 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
- byobu
```

**Comment by berbiche** [comment]
My PR fixes this: https://github.com/NixOS/nixpkgs/pull/90430

**Comment by FRidh** [comment]
Fixed
