### ISSUE TITLE
ati-drivers - nix store collision /lib/xorg/modules/extensions/libglx.so

### ISSUE THREAD

**Issue by heydojo** [NixOS/nixpkgs#9993]
I use the proprietary ati catalyst drivers and there is a store collision between :
```
ati-drivers-15.7-4.1.7/lib/xorg/modules/extensions/libglx.so' and xorg-server-1.17.2/lib/xorg/modules/extensions/libglx.so
```
Is there any way to fix this without just deleting xorg-server-1.17.2/lib/xorg/modules/extensions/libglx.so if ati-drivers are installed?
Would linking do it?
I am asking because I have a weird bug where the xserver will not start after a rebuild boot and I have to reboot the machine again and then it does.
Tnx

**Comment by vcunat** [comment]
I don't think this should cause any problems. I think xserver is supposed to read its modules from `services.xserver.modules` list, not from anything installed by `systemPackages` or such.

BTW, to enable catalyst, you (only) need to have `services.xserver.videoDrivers = [ "ati_unfree" ]`.

**Comment by heydojo** [comment]
It does cause problems on my Fedora system if I do not remove libglx.so and symlink it to the ati supplied one. Especially applications which are looking specifically for libglx.so and expect it to be in /lib/xorg/modules/extensions/. The ati supplied libglx.so is very different to the libglx.so supplied by the xserver and the libglx.so supplied with the xserver will not work if an application tries to use it with firegl.
I have seen it cause issues. I think it was playonlinux which exposed this issue to me on Fedora.

**Comment by vcunat** [comment]
Hmm, we tend to use the GPU driver from the host OS, although not really automatically on non-nixos. Just "installing" such stuff via nix-env doesn't mean anything will use it, AFAIK.

**Comment by blueberry** [comment]
I have ati_unfree drivers selected in configuration.nix, but glxinfo reports "direct rendering: no"
I suppose that the problem is in the incompatibility of catalyst and xorg-server 1.17.

I am confused: is my graphic card 3d capability is switched off or what?
Is there a way to switch it on? Can I select in my configuration.nix that xorg-server 1.16 should be used instead of 1.17?

**Comment by heydojo** [comment]
Please use fglrxinfo for AMD proprietary drivers.

---- Dragan Djuric wrote ----

**Comment by blueberry** [comment]
Thank you for the tip. fglrxinfo output seems to be normal, but does not seem to provide information on whether 3d hardware rendering is being used.

When I try fgl_glxinfo, CPU usage is 96%, so I guess ati_unfree works for 2d, but 3d is inactive?

**Comment by vcunat** [comment]
I suppose you mean fgl_glxgears (or something like that), and it would mean 3d is rendered in SW, perhaps unless the framerate is very high.

**Comment by blueberry** [comment]
Yes. Frame rate is 6000 FPS, but that's probably because the GPU is a recent high-end radeon. Yep, it is a software 3d then. Is there any way to activate hardware 3d? I suppose I would need to downgrade xorg-server to 1.16, and I would gladly do that, only if I could find information HOW.

**Comment by vcunat** [comment]
No, 6000 is high, so that looks like HW-accelerated. For comparison, my notebook with nvidia 420M and proprietary driver gives around 1000 FPS on fullscreen with ~1000^2 resolution.

**Comment by blueberry** [comment]
Maybe that was my mistake. 6000 was the fps rate for the rotating cube. The gears do not show the number, and I am not by that computer now to check. Can you please confirm that your CPU usage also goes to almost 100% when you run any of those tests? Shouldn't the CPU stay relatively idle when the simulation is hardware rendered on the GPU? That is what causes my doubts...

**Comment by vcunat** [comment]
For me glxgears take 100% of one thread when getting those 1000 FPS. IMHO in HW rendering GPU typically does most of the work but not all. Normally when FPS aligns to monitor refresh, I'm getting practically no CPU usage. Note: `$ glxgears -info` displays some extra information; perhaps the fgl versions also give such.

**Comment by blueberry** [comment]
Thank you very much. That is clarifies much. I'll report what happens on my machine for future reference.

**Comment by heydojo** [comment]
I want to look at separating libglx.so in both packages into their own derivations so that if ati unfree is selected in configuration.nix the libglx.so which ships with catalyst becomes the link to libglx.so and the collision is avoided. Obviously whilst being mindful that a removal of catalyst needs to reverse the link so that the libglx.so shipped with the xserver becomes the default libglx.so.
Are there any examples within nixpkgs I can look at which do a similar thing? Does it seem likely that what I want to try to do is even a thing?
Cheers :)

**Comment by blueberry** [comment]
I am not sure. Due to inability to make OpenCL work on Nixos (and I tried),
i switched back to Arch linux.

**Comment by vcunat** [comment]
@heydojo: if it's included in the driver, it should get on `/run/opengl-driver/lib/xorg/modules/extensions/` which should take precedence IIRC.

**Comment by heydojo** [comment]
Answered this one myself. Looking at https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/nvidia-x11/default.nix the problem was occurring when installing the nvidia drivers too.
Adding
```
priority = 4; # resolves collision with xorg-server's "lib/xorg/modules/extensions/libglx.so"
```
appears to solve the issue.
