### ISSUE TITLE
Upgrade python sip

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#99936]
The SIP python module ([homepage](https://www.riverbankcomputing.com/software/sip/download)) says sip v4 is no longer supported, and it's the only version we ship. See also [`8e41a44` (#99933)](https://github.com/NixOS/nixpkgs/pull/99933/commits/8e41a44dc9b1bc91f0d1129255e9d48b4e25f19c).

It seems there have been breaking changes in v5. They also ship it in pypi. I haven't done the update to sip myself because the `sip-module` override mechanism and the `configurePhase` are not compatible with v5, and they are used by pyqt5 for example. There are many uncommentted sip related workarounds in pyqt5's expression. For instance:

https://github.com/NixOS/nixpkgs/blob/433db454f3f6925addb1d7e26f134ef67567ac02/pkgs/development/python-modules/pyqt/5.x.nix#L18-L29

And:

https://github.com/NixOS/nixpkgs/blob/433db454f3f6925addb1d7e26f134ef67567ac02/pkgs/development/python-modules/pyqt/5.x.nix#L106-L117

cc @sander

**Comment by doronbehar** [comment]
Still an issue.

**Comment by flokli** [comment]
@doronbehar it seems `sip` now points to sip 6.5.0, and there's a `sip_4` pointing to 4.19.25, so I guess this is solved?

However, it seems right now a lot of packages using `sip` are broken in weird ways - see https://github.com/NixOS/nixpkgs/issues/114051 and https://github.com/NixOS/nixpkgs/issues/120203, for example.

**Comment by doronbehar** [comment]
Can be closed.
