### ISSUE TITLE
noto-fonts-cjk doesn't include serif fonts

### ISSUE THREAD

**Issue by Dieken** [NixOS/nixpkgs#99940]
**Describe the bug**

According to https://packages.debian.org/sid/all/fonts-noto-cjk/filelist and https://packages.debian.org/sid/all/fonts-noto-cjk-extra/filelist,  noto-fonts-cjk should have 14 ttc files, but noto-fonts-cjk in nixpkgs downloads NotoSansCJK.ttc.zip from https://github.com/googlefonts/noto-cjk/tree/master, this zip files doesn't include serif fonts.

**To Reproduce**
1. nix-env -iA nixos.noto-fonts-cjk
2. fc-list : family | grep 'Noto Serif CJK'

**Expected behavior**

It should output:
```
Noto Serif CJK KR,Noto Serif CJK KR Black
Noto Serif CJK TC,Noto Serif CJK TC ExtraLight
Noto Serif CJK JP,Noto Serif CJK JP Light
Noto Serif CJK KR,Noto Serif CJK KR Medium
Noto Serif CJK SC,Noto Serif CJK SC ExtraLight
Noto Serif CJK JP
Noto Serif CJK KR
Noto Serif CJK TC,Noto Serif CJK TC Black
Noto Serif CJK SC
Noto Serif CJK TC
Noto Serif CJK JP,Noto Serif CJK JP ExtraLight
Noto Serif CJK SC,Noto Serif CJK SC SemiBold
Noto Serif CJK SC,Noto Serif CJK SC Black
Noto Serif CJK KR,Noto Serif CJK KR Light
Noto Serif CJK TC,Noto Serif CJK TC Medium
Noto Serif CJK TC,Noto Serif CJK TC Light
Noto Serif CJK TC,Noto Serif CJK TC SemiBold
Noto Serif CJK JP,Noto Serif CJK JP SemiBold
Noto Serif CJK SC,Noto Serif CJK SC Medium
Noto Serif CJK JP,Noto Serif CJK JP Black
Noto Serif CJK SC,Noto Serif CJK SC Light
Noto Serif CJK JP,Noto Serif CJK JP Medium
Noto Serif CJK KR,Noto Serif CJK KR SemiBold
Noto Serif CJK KR,Noto Serif CJK KR ExtraLight
```

**Notify maintainers**

@mathnerd314 @emily 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.68, NixOS, 20.03.3087.b4db68ff563 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Dieken** [comment]
The nix file should download 14 .ttc files and install to target directory in a loop, it's a simple logic, but sorry I'm not familiar with Nix language yet.

Mention more people involved in this file since 2020: @samueldr @sternenseemann @Lassulus @OmnipotentEntity @jonringer @Mic92 @rileyinman @emilazy @yegortimoshenko   hope this gets fixed soon, thanks!

**Comment by Mathnerd314** [comment]
As I recall, the issue with packaging it initially is there was no Super OTC version of the noto serif cjk font available. There still isn't a Super OTC in the repository. There is https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJK.ttc.zip from https://www.google.com/get/noto/help/cjk/, but that URL doesn't look stable.

I guess for now you could use `source-han-serif`, it is 99% the same font.

**Comment by Dieken** [comment]
@Mathnerd314 , thanks for your quick response!

Although `source-han-serif` is almost same, fontconfig can’t assure it will alway be selected for document using `noto-fonts-cjk`, there are a few other popular cjk font such as Arphic PR UMing & UKai, WenQuanYi, GNU freefont, GNU unifont.

https://packages.gentoo.org/packages/media-fonts/noto-cjk

Like Debian, Gentoo also packages separate ttc files.

https://www.freshports.org/x11-fonts/noto-sc/
FreeBSD even packages separate otf font, I guess this can save some memory and time for applications to load a font subset.

It’s a pity google doesn’t upload a single super otc file for noto serif cjk, but I guess the huge noto sans zip is uploaded to git by mistake, it’s kept there just to not break download url.

So I suggest to just package 14 separate ttc file, it’s convenient enough compared to those separate otf files.

Another reminder, it’s better to also include a fontconfig configuration snippet like Debian and Gentoo.

**Comment by Dieken** [comment]
https://www.archlinux.org/packages/extra/any/noto-fonts-cjk/

Arch also package separate ttc and include a fontconfig configuration file.

**Comment by KouAkitaki** [comment]
Still important to me.
