### ISSUE TITLE
python3Packages.sphinx-argparse missing

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#99945]
**Describe the bug**
``python3Packages.sphinx-argparse`` has been incorrectly removed in master and release-20.09.
The ``development/python-modules/sphinx-argparse`` files still exist but are no longer referenced.

**To Reproduce**
```
> nix-shell -p python3Packages.sphinx-argparse
error: attribute 'sphinx-argparse' missing, at (string):1:94
```

**Expected behavior**
sphinx-argparse is available.

**Additional context**
This has been introduced with 6b23dc8f965652ad7d246ae01d95c1d77eac904d

**Notify maintainers**
@jonringer

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.sphinx-argparse
```

**Comment by jonringer** [comment]
oh yea, sorry it must have been collected with some comments.

Major refactors are hard to eye-ball
